### ISSUE TITLE
Store url directive in anchor inside WYSIWYG

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#10003]
### Preconditions
1. Magento 2.1.7

### Steps to reproduce

1. Edit product in backend
2. Hide editor in 'Description field'
3. Try to insert anchor with store url directive (`<p><a href="{{store url="test"}}">Test</a></p>`)
4. Show editor
5. Hide editor again

### Expected result

1. It should be shown unchanged

### Actual result

1. Code is broken: `<p><a href="{{store url=">Test</a></p>`

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70070 was created.

**Comment by Bartlomiejsz** [comment]
@vityakopin @veloraven it looks like it is fixed in #10131. Will you merge it into 2.1 branch soon?

**Comment by magento-engcom-team** [comment]
@Bartlomiejsz, thank you for your report.
We've created internal ticket(s) MAGETWO-70070 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by Bartlomiejsz** [comment]
@magento-engcom-team Should not-solved issue be closed after two weeks? Really?

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz 

It's not being closed, as now it's apparent that somebody is still interested in it. Thank you for the feedback.

**Comment by Bartlomiejsz** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz, here is your [Magento instance](https://i-10003-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-10003-2-3-develop.instances.magento-community.engineering/admin](https://i-10003-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Bartlomiejsz** [comment]
Closing as no longer reproducible on 2.3-develop
