### ISSUE TITLE
CatalogImportExport: Cannot import value 0 for price attributes

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#10006]
When you import a value of 0 for a price attribute, the value will not be imported and Magento will keep its current value for the attribute.

### Preconditions
1. MG2 CE 2.1.7 (also tested on 2.1.5, 2.1.6)
2. PHP 7.0

### Steps to reproduce
1. Create a product and set its price to greater than 0
2. Create an import CSV with data for the product and a price of 0
3. Import the CSV

### Expected result
1. Product price should be 0

### Actual result
1. Product price is still the old value

Backtraced to \Magento\CatalogImportExport\Model\Import\Product\Type\AbstractType where in the function clearEmptyData an empty check is being done. 

```
public function clearEmptyData(array $rowData)
{
    foreach ($this->_getProductAttributes($rowData) as $attrCode => $attrParams) {
        if (!$attrParams['is_static'] && empty($rowData[$attrCode])) {
            unset($rowData[$attrCode]);
        }
    }
    return $rowData;
}
```

Empty() will treat 0 as empty (http://php.net/manual/en/function.empty.php) and thus removing the price value from the data to be imported.

**Comment by vityakopin** [comment]
Internal ticket MAGETWO-70073 was created.

**Comment by magento-engcom-team** [comment]
@koenner01, thank you for your report.
We've created internal ticket(s) MAGETWO-70073 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#38
