### ISSUE TITLE
Customer Backend: Confirmation Flag is being overwritten by save of the Customer

### ISSUE THREAD

**Issue by EliasKotlyar** [magento/magento2#10017]
Customer Backend: Confirmation Flag is being overwritten by save of the Customer

### Preconditions
Current Development Version of Magento(appears in any Version)

### Steps to reproduce
1. Register a Customer trough the Frontend. Customer should get an Confirmation Email with a link to confirm his Account. Do not use the link yet.
2. Go to Admin Panel, and save the Customer

### Expected result
The Customer could use the link in the email to finish his registration

### Actual result
The Email Link is broken, and the customer is automatically "registered"

### Why this error occurs?

The Customer-Save-Controller in the Backend(Adminhtml) will fill the "confirmation" flag with a void value. The Value is actually extracted from the post-request, but there is no form-element which will pass any value to it. The "confirmation" flag will be saved in the database overriding the value which is needed to finish the registration.

**Comment by okorshenko** [comment]
Hi @EliasKotlyar Issue is not reproducible. Please, see the comment in PR.

**Comment by okorshenko** [comment]
hi @veloraven Did you verified this issue? Is it reproducible?

**Comment by EliasKotlyar** [comment]
Hello okorshenko,

Here is a video for reproducing the issue:
https://www.youtube.com/watch?v=LCUUJbUV8Ig&feature=youtu.be

Greetings
Elias

**Comment by okorshenko** [comment]
Hi @EliasKotlyar 
Thank you for provided video. I see the issue exists on your installation. 
I will send this issue to QA department one more time for re-verification. Could you please provide more details about your environment:
 - PHP version
 - Web server
 - Magento edition (CE/EE) (I saw latest CE commit, but may be you have EE on top)
 - Additional modules (if any)
 - Any changes in store config (non default values)
 - Additional stores/websites or any other created entities
 - Sample data: installed or not

**Comment by EliasKotlyar** [comment]
Hello okorshenko,

 * PHP version
PHP Version 7.0.18-0ubuntu0.17.04.1
* Web server
Apache 2
* Magento edition (CE/EE) (I saw latest CE commit, but may be you have EE on top)
I am using only CE. 
* Additional modules (if any)
No, its completely clean. I installed it yesterday.
* Any changes in store config (non default values)
Only the Flag in "Require Emails Confirmation" which i turned to yes.
Its in the Config under Customer->Create-New-Account Option
* Additional stores/websites or any other created entities
No
*Sample data: installed or not
No sample data installed.

If its a Browser dependent issue: I am using FireFox 54(64Bit).

Greetings
Elias

**Comment by okorshenko** [comment]
Thank you @EliasKotlyar for provided information. 👍

**Comment by okorshenko** [comment]
Hi @EliasKotlyar 
We got a report from QA department. This flow was tested on 4 different environments by different QA engineers. Unfortunately we can not reproduce the issue. 
We will keep this issue as Open. We have your video that demonstrates incorrect behavior. We will provide detailed information about testing flow soon.
Thank you

**Comment by vherasymenko** [comment]
@EliasKotlyar  Hi. I Tried reproduce your bug, but without success.

Steps which I execute:

1. Install clean Magento from develop branch
2. After install run commands:
 - `php bin/magento cron:run`
 - `php bin/magento indexer:reindex`
 - `php bin/magento cache:flush`
3. In admin side change config `"Customer->Create-New-Account Option->Require Emails Confirmation" set to "Yes"`
4. On latest develop branch Magento need repeat steps described in step №2
5. On Frontend side register new customer
6. Then in Admin side open created customer and click "Save"

**Actual Result:** Status of customer is still "Confirmation required" (And it` correct behavior)

**Were executed many variations of installations:**

1. Install Magento from `develop` branch, then downgrade version to `2.1-develop`, then upgrade to latest `develop`.
2. Install Magento from `2.1-develop` and then upgrade to `develop` branch.
3. Install Magento on clean DB, and DB with some data.
4. Install Magento with sample data.
5. Install Magento and try reproduce described steps without run `cron:run` etc.

Thanks for Your attention.

**Comment by sdzhepa** [comment]
Hello @EliasKotlyar 

We spend some more time and tried to reproduce this issue again.
Was performed several attempts to repro on several commits(starting from 1st of Jun and ending with latest up to date code )
Each iteration was based on provided steps: 
- Clear CE installation (using WEB install wizard)
- All Magento settings in default mode(as after installation), except Require Emails Confirmation" set to "Yes"
- Magento has NO any entities(like products/customer/categories/websites etc) on start
- Go to Storefront and create new customer by clicking "Create an Account" link in the top of the Home page
- Perform reindex from bash: php bin/magento indexer:reindex
- Go to Admin Panel open and save customer

Result: Issue cannot be reproduced 

possible reasons/ideas why it occurs
- Posible there is some crucial precondition/action that was missed in steps. I see Your customer ID = 2 and it means that, probably, was/were some action with customer ID = 1
- Issue depends on unexpected merge/git pull/upgrade action when you update code base

Could you pls re-check this issue on the latest Magento code based on clear "git cloned" code

**Comment by okorshenko** [comment]
Thank you @sdzhepa for additional research.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69297

**Comment by magento-engcom-team** [comment]
@EliasKotlyar thank you for your report.
The fix for this issue is already available in release 2.2.0
