### ISSUE TITLE
Widget content does not show up when edit on Chrome

### ISSUE THREAD

**Issue by ducnhdtn** [magento/magento2#10016]
**This error has been defined in here, and they have solution to fix it too: https://magento.stackexchange.com/questions/178624/cannot-edit-widgets-in-wysiwyg-editor-anymore**
------------------------------------------

Widget content does not show up when edit on Chrome

### Preconditions

1. Magento Version 2.1.7
2. Fresh install and demo content, no extension.

### Steps to reproduce

1. Edit a CMS page
2. Double click on widget to change widget content as below:
![click-to-edit](https://user-images.githubusercontent.com/12104465/27421694-b48d993e-5755-11e7-8202-1a1149fb451b.jpg)

### Expected result

1. Current widget content should show up as below:
![expected-result](https://user-images.githubusercontent.com/12104465/27421684-adad42cc-5755-11e7-97c7-4efb95e64134.jpg)

### Actual result

1. Nothing show up:
![actual-result](https://user-images.githubusercontent.com/12104465/27421719-c7e3bde2-5755-11e7-8894-edb9889501bd.jpg)

**Comment by ducnhdtn** [comment]
Hi, 
This error is the same with: https://github.com/magento/magento2/issues/9518

**Comment by veloraven** [comment]
@ecentura thank you for your update.
I'm closing this issue as duplicate.
Please note, that the issue was already fixed and the fix will be available in one of the nearest releases.
