### ISSUE TITLE
M2.1.7, Checkout as logged in user: Validation Error 'Please enter less or equal than {0} symbols' on empty 2nd address line when adding new address

### ISSUE THREAD

**Issue by jhruehl** [magento/magento2#10010]
If one tries to add a new address during the checkout process as a logged in user, whose default address has no 2nd address line, one gets the validation error 'Please enter less or equal than {0} symbols' on this line.
Once anything is entered in the 2nd address line and removed, the error doesn't show up on retries unless store cookies are deleted.

### Preconditions
1.  Magento 2.1.7
2. PHP Version 7.0.17
3. MySQL Version 5.6.34

### Steps to reproduce
1. Delete shop cookies.
2. Login as user with given postal address with an empty second address line.
3. Enter the checkout process to the shipping options step.
4. Having a default address shown, choose to add a new address.

### Expected result
1. Nothing except input fields are filled with values from default address

### Actual result
1. ![image-2017-06-02-13-51-26-630](https://user-images.githubusercontent.com/29142982/27382702-4f762890-5688-11e7-847f-d91b677a89ce.png)

### Probable Cause
js validation error/bug on given template, because both address-lines are stored as one string with 'newline' as separator in the database. While retrieving the address lines from the database the string is converted to an array using the 'newline' separator. If there is no second line given, the array will have just one entry. But even though there is no entry given in the street[] array, the js-validation process runs on street[1] = null.

**Comment by smoskaluk** [comment]
@jhruehl Unfortunately, I could not reproduce the issue as you described it. May you please advise if this problem reproducing on latest version of Magento2 with English localization?

**Comment by jhruehl** [comment]
No, I can't, but it occurs with French localization, too. We just have German (CH) and French localization running on our servers and the error started to occur after the update from 2.1.5 to 2.1.7.

**Comment by smoskaluk** [comment]
@jhruehl  May you please check if your problem would reproduce on "clean" Magento 2 without any localization (on default English)?

**Comment by jhruehl** [comment]
I tried to reproduce it in the 2.1.6 ce Docker Installation, because that was the easiest thus cheapest way to get a clean installation going. I think the problem is that by default the address fields like street, etc. on adding a new address aren't filled with values from the default values as they are in our store.
If I have time to spare, I may try to reproduce the error in a more accurate installation. until then it has to wait.
Though it really would be nice, if others, who have the same problem, would comment here. So I know we are not alone with this.

**Comment by veloraven** [comment]
@jhruehl thank you for your update.
Unfortunately it's unclear if you were able to reproduce the issue on English locale.
Could you please also check if you have the same issue on your locales but with default Magento theme?

**Comment by jhruehl** [comment]
Yes. It was reproducable with the default theme.

What I found out while trying to reproduce the validation error in the default docker installation, is that by default the address fields in the new-adress template aren't filled with the given customer default address values like they are in our template. Because I didn't implement/set that, I don't know, if that is an availabe standard Magento 2 setting.

**Comment by magento-engcom-team** [comment]
@jhruehl, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by Kaushik-Roy** [comment]
### Hi guys, even i am facing the same issue here.This happens whenever i am going to checkout page and try to add a new shipping address. I get this particular error message under the additional street address fields.
### "Please enter less or equal than 255 symbols."

**Preconditions**
- Magento 2.1.5
- PHP Version 7.0.30 
- MySQL Ver 14.14 Distrib 5.7.23, for Linux (x86_64)

**Steps to reproduce**
- Add product to cart and go to checkout page.
- Add new shipping address and place order.
- Again come back to checkout page with a new product in cart.
- Click "+ New Address" button.

**Expected result**
- Nothing except input fields are filled with values from default address.

**Actual result**
- Additional input fields of Street address is having a validation message as "Please enter less or equal than 255 symbols."

![checkout_new_address_form_error](https://user-images.githubusercontent.com/18119362/44511079-03b0dc00-a6d4-11e8-8a39-2005828076b5.png)
