### ISSUE TITLE
Database Schema: Missing important Foreign Keys

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#1001]
During my database schema comparison I discovered several missing foreign keys and one incorrect unique index (at least I think the unique key is wrong 8-) Issue #1002 ).

The following 5 screenshots shows the missing keys. Left side Magento2 and right side Magento1.

If there is a technical reason why you haven't implemented the keys: Please explain :-)

![catalog_product_index_eav_decimal](https://cloud.githubusercontent.com/assets/372027/5916266/83f192c6-a663-11e4-90f3-931c0e856094.png)
![catalog_product_index_eav](https://cloud.githubusercontent.com/assets/372027/5916267/83f22060-a663-11e4-8083-4ca070ea6b80.png)
![cataloginventory_stock_status](https://cloud.githubusercontent.com/assets/372027/5916268/83f97c16-a663-11e4-8c42-c21ebba96842.png)
![catalogrule_product_1](https://cloud.githubusercontent.com/assets/372027/5916269/84005cd4-a663-11e4-8d7a-c04b45076004.png)
![catalogrule_product_price_1](https://cloud.githubusercontent.com/assets/372027/5916270/84010be8-a663-11e4-9a57-12abb738738a.png)

**Comment by orlangur** [comment]
Few of keys you mentioned were identified as unused with http://www.percona.com/doc/percona-toolkit/2.1/pt-duplicate-key-checker.html and thus eliminated.

**Comment by kokoc** [comment]
@SchumacherFM There are two main reasons why we removed such keys:
* @orlangur mentioned the first one
* We removed some foreign keys from index tables in order to speed up insert/update operations. Consistency is guaranteed by application. 

Do you have any additional questions?

**Comment by SchumacherFM** [comment]
Thank you for answering!
