### ISSUE TITLE
Checkout Config Added To Checkout/Cart/Index Via Unnecessary Block

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10021]
The checkout is more complicated than necessary because checkoutConfig is relied upon by other blocks but is tied into the shipping-estimation block.

Removing the following block breaks many other parts of the cart page:

(checkout_cart_index.xml)
  <block class="Magento\Checkout\Block\Cart\Shipping" name="checkout.cart.shipping" as="shipping" template="cart/shipping.phtml" after="checkout.cart.summary.title">...

Suggest adding to layout via a separate block.

**Comment by veloraven** [comment]
@xAvarice please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by ghost** [comment]
No, because it's pointless. It doesn't need reproducing - it's an issue in a template.

window.checkoutConfig is used by many elements on the checkourt/cart/index page, therefore it should be added to the page independently. If a Magento developer would struggle to find where the window.checkoutConfig is added - that is the entire essence of the problem.

**Comment by magento-engcom-team** [comment]
hi @xAvarice we will take a look at the design and will try to address it in the future releases or you can create pull request to fix the issue. Thank you
Closing this issue for now. This is not a bug but design issue.
