### ISSUE TITLE
Product Atributes issue after updating from 2.1.5 to 2.1.7

### ISSUE THREAD

**Issue by Moppelfett** [magento/magento2#10024]
Hi,
after updating from Magento 2.1.5 to 2.1.7 it shows all product atributes on the product page even the fields are empty in the backend.
![unbenannt-1](https://user-images.githubusercontent.com/12279931/27452657-aa6aaa4e-5793-11e7-87aa-8ede82a3a93d.jpg)

How can I fix that?
I want Magento to show only atributes that contains information.

thanks for your help.

Experienced this too.

### Preconditions:
Magento 2.1.7

### Steps to Reproduce

Go to product creation
Scroll down to a product attribute with a text field.
Leave the text field blank
Save the Product
Navigate to that product on the frontend
### Expected Result
Attributes with blank text fields will not show up on the frontend

### Actual Result
Attributes with blank text fields show up with N/A ie "Color: n/a"

**Comment by veloraven** [comment]
@Moppelfett thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by gediminaskv** [comment]
This is related to https://github.com/magento/magento2/issues/9961

**Comment by PieterCappelle** [comment]
Any update on this one?

**Comment by Ctucker9233** [comment]
@magento-engcom-team 
Experienced this too.

Preconditions:
Magento 2.1.7

Steps to Reproduce:
1. Go to product creation
2. Scroll down to a product attribute with a text field.
3. Leave the text field blank
4. Save the Product
5. Navigate to that product on the frontend

Expected Result:
Attributes with blank text fields will not show up on the frontend

Actual Result:
Attributes with blank text fields show up with N/A ie "Color: n/a"

**Comment by magento-engcom-team** [comment]
Hi @Moppelfett the issue has been fixed in 2.1.8
Thank you for your report
