### ISSUE TITLE
Missing attributes in attribute sets

### ISSUE THREAD

**Issue by MaxC808** [magento/magento2#10026]
Missing newly created attributes in all attribute sets

### Preconditions

1. Magento 2.1.7 recently upgraded from 2.1.2
2. 

### Steps to reproduce

1. create new attribute called 'Type'
2. configure the attribute properties
3. move newly created product attribute into an attribute set
4. create new simple product and specify the relevant attribute set (with the newly added product attribute)

### Expected result

1. Newly created product attribute is visible in list of attributes while creating new simple product

### Actual result

1. The new attribute is nowhere to be found in the product creation section.
2. Only the standard, default attributes are displayed
3. I've reindexed and it doesn't seem to help

**Comment by smoskaluk** [comment]
@MaxC808 Unfortunately, I could not reproduce the issue as you described it.  I need more information about your configuration to reproduce this issue. Please identify the OS and web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by MaxC808** [comment]
@smoskaluk OS is Debian 8, web sever is a combined NGINX and Apache (hosted on Cloudways) PHP 5.6 and MySQL 5.6. At this time, I can't think of any other issues that would cause this type of problem. It was working correctly before the upgrade to 2.1.7 and there have been no new plugins or extensions installed since the upgrade. thanks.

**Comment by smoskaluk** [comment]
@MaxC808  May you please give more detailed steps for reproducing this issue? eg what type of attribute you created, full configuration of this attribute, did you create it before upgarde or after.

**Comment by MaxC808** [comment]
@smoskaluk we have 2 scenarios, an attribute that was created prior to upgrade and a newly created attribute after the upgrade - neither attribute will show. Here are the details on the newly created attribute:

**New Product Attribute:
Properties:**
Default Label: Product Type
Catalog Input Type for Store Owner: Text Field
Values Required: Yes

Advanced Attribute Properties:

Attribute Code: product_type
Scope: Store View
Default Value: 
Unique Value: No
Input Validation for Store Owner: Letters or Numbers
Add to Column Options: Yes
Use in Filter Options: Yes

**Manage Labels:** Product Type (for all store views )

**Storefront Properties:**
Use In Seach: No
Comparable on Storefront: No
Use in Layered Navigation: No
Use in Search Results Layered Navigation: No
Position:
Use for Promo Rule Conditions: No
Allow HTML Tags on Storefront: Yes
Visible on Catalog Pages on Storefront: Yes
Used in Product Listing: Yes
Used for Sorting in Product Listing: Yes

Add attribute; product_type to attribute set NewTest

Create new Simple Product
Select NewTest from attribute set dropdown
New attribute does not appear

**Comment by smoskaluk** [comment]
@MaxC808  Still cann't reproduce this problem. May you please add some screenshots to see how to reproduce it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
