### ISSUE TITLE
Better overview for Payment Methods

### ISSUE THREAD

**Issue by avoelkl** [magento/magento2#1003]
Given that you run a big shop with a lot of payment methods, some of the payment extensions bring a lot of unneeded/unwanted payment methods with them which appear in the payment method list. Of course you can generate a list and hide them via custom xml (at least in M1), but it's not very handy.

Edit: To get an idea what I mean:
Currently we have a shop which has 68 payment methods in this list.
These 68 payment methods are added by 10 payment extensions whereas one of them brings > 20 possible payment methods.
Only 8 of the payment methods are currently activated in the shop frontend.
This makes the list quite confusing.

The list under Configuration > Payment Methods can get quite long so I'd like to suggest to either

**1 Highlight activated Payment Methods (having "Enabled" > "Yes")**

![paymentmethod_var1](https://cloud.githubusercontent.com/assets/1798594/5921832/0961a210-a647-11e4-86d3-fd58652583b1.png)

**2 Put the enabled payment methods on top incl. highlighting**

This would require to prioritize the status "Enabled" over the defined sort order.

![paymentmethod_var2](https://cloud.githubusercontent.com/assets/1798594/5921831/095ff0dc-a647-11e4-8e00-3f871030e805.png)

Another addition to this could be to sort them into activated and deactivated payment methods and hide the deactivated by default.

I think version 1 would already bring an improvement.

**Comment by andreaspenz** [comment]
this could be very helpful :metal:

**Comment by cbmd** [comment]
@avoelkl this could be not just for payment methods, but for all similar functionality, shipping methods for example....

**Comment by avoelkl** [comment]
@cbmd yes, at least for shipping methods this would also make sense.

**Comment by avoelkl** [comment]
I have updated my issue with some details regarding payment method count.

**Comment by vpelipenko** [comment]
@avoelkl, thanks for contribution. This issue will be reviewed by responsible product owner soon.

**Comment by asemenenko** [comment]
Hi Avoelkl,

Thank you for contribution. We added this improvement into the backlog. The issue will be updated once it fixed.

/regards
Andrii

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-33515

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Better-overview-for-Payment-Methods/idi-p/46659).
