### ISSUE TITLE
Disabled simple product still shows up as an option when status is disabled

### ISSUE THREAD

**Issue by gediminaskv** [magento/magento2#10036]
### Preconditions

1. Magento 2.1.7
2. Simple product is in stock and has some stock.
3. Only configurable products are shown on category page.
4. The simple product is a variation of a configurable product.

### Steps to reproduce

1. Disable simple product
2. Reindex
3. Cache flush

### Expected result

1. Configurable product would not show that disabled simple product as an option (particular color and size)

### Actual result

1. Product variation still appears on frontend and can be purchased.

**Comment by VasylShvorak** [comment]
@gediminaskv, thank you for your report.
Unfortunately I was not able to reproduce this issue.
Please describe all steps you have done in more detailed way.
And if you can attach screenshot it may help as well.

**Comment by gediminaskv** [comment]
@VasylShvorak My bad. Maybe cache didn't clean up well. Everything seems working now.
