### ISSUE TITLE
Download back-up .tgz always takes the latest that's created

### ISSUE THREAD

**Issue by GuidoHub** [magento/magento2#10032]
I have created several backups on my production enviroment. When I choose to download the backup tgz, never mind which you click it always downloads the latest created backup. I have checked folder "/var/backups" and all back-ups are there.

### Preconditions

1. Magento 2.1.7
2. PHP 7.0.20

### Steps to reproduce

1. Create several back-ups
2. Click on a backup (.tgz), different then the latest to download
3. 

### Expected result

1. I would expect the backup I clicked.

### Actual result

1. Always getting the latest back-up

**Comment by Stas94** [comment]
@GuidoHub Thanks for reporting this issue. Internal ticket MAGETWO-70427 was create.

**Comment by magento-engcom-team** [comment]
@GuidoHub, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by PieterCappelle** [comment]
Created backport to 2.2 & 2.1 branch.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82710

**Comment by okorshenko** [comment]
the issue has been fixed and delivered to 2.2-develop branch. WIll be available with 2.2.2 release
