### ISSUE TITLE
Checkout: adding coupon codes in the checkout process causes 'Request does not match any route' error message

### ISSUE THREAD

**Issue by jhruehl** [magento/magento2#10035]
If one adds a coupon code starting with a hashtag '#' during the last step of the checkout process (not in the cart view itself), one gets the error message 'Request does not match any route' instead of the typical 'Coupon applied/Coupon invalid' messages.

### Preconditions
1. Magento 2.1.7
2. PHP Version 7.0.17
3. MySQL Version 5.6.34

### Steps to reproduce
1. Open the payment page of the checkout process, where you can add coupons (bug doesn't occur in the cart view itself)
2. Add random coupon code starting with a hashtag '#'
3. Click 'apply coupon'

### Expected result
1. standard success/error frontend messages 'coupon applied/invalid'.

### Actual result
'Request does not match any route' error messages shown in frontend.

![checkout_coupon_notice](https://user-images.githubusercontent.com/29142982/27483363-57cbb444-5825-11e7-8d30-83a5c3135158.jpeg)

### Cause
The coupon code isn't correctly encoded in
/vendor/magento/module-checkout/view/frontend/web/js/model/resource-url-manager.js,
so before the ajax call happening the following piece of code in require.js removes the complete coupon code from the request URL:

"// Remove hash character (#7531: and string promotion)
// Add protocol if not provided (#5866: IE7 issue with protocol-less urls)
// Handle falsy url in the settings object (#10093: consistency with old signature)
// We also use the url parameter if available
s.url = ( ( url || s.url || ajaxLocation ) + "" )
       .replace( rhash, "" )
       .replace( rprotocol, ajaxLocParts[ 1 ] + "//" );"

### Patch

[bugfix.txt](https://github.com/magento/magento2/files/1097879/bugfix.txt)

**Comment by AlexWorking** [comment]
Hello @jhruehl. Based on Your issue an internal ticket MAGETWO-70415 has been created. You'll be informed as the bug is fixed. Thanks for applying.

**Comment by magento-engcom-team** [comment]
@jhruehl, thank you for your report.
We've created internal ticket(s) MAGETWO-80388 to track progress on the issue.

**Comment by RomaKis** [comment]
It is fixed in https://github.com/magento/magento2/commit/fb84267.

**Comment by magento-engcom-team** [comment]
@jhruehl We are closing this now per comment above. Please use that commit as a reference if needed.
