### ISSUE TITLE
2.1.7 Update issue

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#10042]
Having a really stupid problem when updating magento 2.1.6 to 2.1.7 its asking for Php xdebug extension to be installed, well xdebug should be installed on development site only not on live or production site and my website is live if i install xdebug on my live site it can cause security and performance issue on my server which is not acceptable, so this is really stupid requirement for magento, does anyone know how to possible get rid of this issue and update magento 2.1.7

**Comment by rvkvino** [comment]
![image](https://user-images.githubusercontent.com/3162291/27508936-4e1dfbf2-590e-11e7-8f42-0f09a8ab1b19.png)
When I upgrade magento 2.1.6 to 2.1.7 showing the error like attached file. Having issue on showing product images in front page in 2.1.6

**Comment by veloraven** [comment]
@terrybakshi thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by SyedMuneebb** [comment]
You can easily upgrade your store to Magento 2.1.7.  Go to the root directory and run the following commands:

```
omposer require magento/product-community-edition 2.1.7 --no-update
composer update
rm -rf var/di/* var/generation/* var/cache/* var/log/* var/page_cache/*
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:clean
php bin/magento cache:flush
```

Here's a full guide: [Update Magento 2](https://magenticians.com/update-magento-2-using-composer/)
