### ISSUE TITLE
Wrong Currency

### ISSUE THREAD

**Issue by josealgardataborges** [magento/magento2#1005]
Portuguese Currency is EURO since 1st of January 2002, so someone needs to update the install screen to reflect that reality,

The install url is STEP4: http://localhost/magento2/setup/#/customize-your-store

![portugueseeuros](https://cloud.githubusercontent.com/assets/8929655/5942655/d824cc70-a710-11e4-88cf-4a624a8e0af9.png)

**Comment by mazhalai** [comment]
For internal tracking MAGETWO-33378

**Comment by mazhalai** [comment]
@josealgardataborges Thank you for reporting this issue. We will look into it.

**Comment by vancoz** [comment]
Hello @josealgardataborges, we have an Euro in the currency list, please, chose it.
Countries in the list presented just as extended information for currencies, but not main entity.

And thank you for the report, we will consider using some service/tool for filtering out inactive currencies.

**Comment by tanya-soroka** [comment]
Closed. Thank you
