### ISSUE TITLE
Welcome Email not sent after importing new customer with csv file

### ISSUE THREAD

**Issue by MattDelac** [magento/magento2#10055]
### Preconditions

1. Magento 2.1.6
2. Php7  / Varnish / MySQL

### Steps to reproduce

1. Import new customers with a CSV file
2. Use the standard "customer and addresses (single file)" import

### Expected result

1. A "welcome email" is send to the new customers

### Actual result

1. The "welcome email" has not been sent

Is there someone that knows how to bypass this ?

**Comment by jordanbrauer** [comment]
Are you able to use the REST API? I do everything via backdoor with the API and Guzzle in a CLI application I made with the Symfony 3 Console Component which seems to work just fine.

**Comment by MattDelac** [comment]
Hello @jordanbrauer ,

Thanks for your reply.

I will get a look at the REST API. Which on do you think I should use in order to send the welcome email ?
However, API is a bit long and to synchronize 7000 clients per day, it will take too much time.
The csv import is just fine. I use a module that let me import any csv with a cli (==> easy to script)

Thanks in advance

**Comment by magento-engcom-team** [comment]
@MattDelac, thank you for your report.
We've created internal ticket(s) MAGETWO-80547 to track progress on the issue.

**Comment by jigar48** [comment]
Hello M2,

Is this issue is fixed.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#85
