### ISSUE TITLE
[2.2 RC][2.1-dev] Make RC and dev branches available in magento/product-community-edition

### ISSUE THREAD

**Issue by tmotyl** [magento/magento2#10051]
# Please make 2.2RC and 2.1-dev versions available through composer magento/product-community-edition metapackage. 

Without it its' not possible to test upcoming versions with real life projects which are using composer. 

In the docs the preferred way of installing magento is described here:
http://devdocs.magento.com/guides/v2.2/install-gde/prereq/integrator_install_ce.html

Unfortunately you can't use this method to test upcoming releases - 2.2 (branch develop from https://github.com/magento/magento2 ) nor 2.1 (branch 2.1-develop).

This result in many issues being submitted multiple times, because there is no way of validating if the issue still exists. It also force developers to wait for the official release before they start using new version.
So issues and regressions are found to late.

**Comment by ihor-sviziev** [comment]
It would be really good, because right now it's almost impossible to test 2.2 RC or 2.1-develop for current projects that were installed via composer. I think it can be done only for 2.2 RC 1.1 because it's tag and it's not updating.

**Comment by korostii** [comment]
I haven't tested this myself yet, but: shouldn't you be able to add https://github.com/magento/magento2 to your `"repositories"` section and then just use `"dev-develop"` or `"dev-2.1-develop"` as the version in your composer.json? 
As described [here](https://lornajane.net/posts/2014/use-a-github-branch-as-a-composer-dependency)

**Comment by zelgerj** [comment]
It should be possible to install the 2.2.0 rc via composer create project line like all the other releases.
```bash
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.2.0-rc1 /var/www/magento
```

**Comment by ihor-sviziev** [comment]
Unfortunately both variants doesn't work because magento should prepare
packages for this version before we can work with it.

**Comment by zelgerj** [comment]
@ihor-sviziev i know that both variants are not working right now, but it should be possible in my opinion to keep the install process consistent and all automated continuous integrations can be used without modifying any logic. I'd really love to see that 👍

**Comment by sivajik34** [comment]
first we can clone the repo.then checkout to particular tag.now you can install.

**Comment by ihor-sviziev** [comment]
@okorshenko @vrann could someone make rc1 available to install from composer?

**Comment by okorshenko** [comment]
hi @ihor-sviziev 2.2.0-rc1 (pre-release) is an alpha release. Alpha won't be available at repo.magento.com 
But we are going to publish release candidate on repo.magento.com after the alpha.

**Comment by tmotyl** [comment]
@okobchenko  and what about v2.1-dev ? 
Please please please add possibility of fetching both **develop** and **2.1-dev** branch via composer, or publish the metapackage on github, so people can fork it and configure it themselves. 

Reasoning:
1) the release cycle minor (patch versions) of Magento is extremely long
2) Many bugs are already fixed in 2.1-dev or develop branch, but are not released because of 1). This is frustrating and makes Magento 2 bad PR. 
3) There is no way for people to test upcoming releases (2.1.x and 2.2) with real life projects, so regressions can't be found early. Which means additional work for you and integrators.
4) All above means that Magento integrator is forced to use unsupported / not recommended way of deploying Magento, to be able to port already made fixes to custom repository.
This makes developing project using Magento 2 a real and unnecessary pain.

I would really love to spend time on improving Magento and making PR instead of burning it with fiddling and working around issues which were reported and fixed (but not released) months ago.

**Comment by okorshenko** [comment]
Thank you @tmotyl for suggestion. We will take into account your request

**Comment by zelgerj** [comment]
Any news here? Thanks!

**Comment by tgrzemski** [comment]
It would be really useful!!!

**Comment by hostep** [comment]
Just noticed the `2.2.0-rc2.0` tag was republished today and decided to try this (hadn't tested this before, so it might have already worked for a couple of days):

So this now works (notice the stability flag):
```
$ composer create-project --no-install --repository-url=https://repo.magento.com/ --stability=RC magento/project-community-edition
  - Installing magento/project-community-edition (2.2.0-rc20)
...
```

Upgrading a Magento 2.1.8 project also works, by changing this in the `composer.json` file:
```diff
diff --git a/composer.json b/composer.json
index 3a97104..1506d21 100644
--- a/composer.json
+++ b/composer.json
@@ -8,20 +8,17 @@
         "AFL-3.0"
     ],
     "require": {
-        "magento/product-community-edition": "2.1.8",
+        "magento/product-community-edition": "2.2.0-rc20",
         "composer/composer": "@alpha"
     },
     "require-dev": {
-        "phpunit/phpunit": "4.1.0",
-        "squizlabs/php_codesniffer": "1.5.3",
+        "phpunit/phpunit": "~6.2.0",
+        "squizlabs/php_codesniffer": "3.0.1",
         "phpmd/phpmd": "@stable",
-        "pdepend/pdepend": "2.4.0",
-        "fabpot/php-cs-fixer": "~1.2",
-        "lusitanian/oauth": "~0.3 <=0.7.0",
-        "sebastian/phpcpd": "2.0.0"
-    },
-    "config": {
-        "use-include-path": true
+        "pdepend/pdepend": "2.5.0",
+        "friendsofphp/php-cs-fixer": "~2.1.1",
+        "lusitanian/oauth": "~0.8.10",
+        "sebastian/phpcpd": "2.0.4"
     },
     "autoload": {
         "psr-4": {
@@ -30,10 +27,17 @@
             "Magento\\": "app/code/Magento/"
         },
         "psr-0": {
-            "": "app/code/"
+            "": [
+                "app/code/"
+            ]
         },
         "files": [
             "app/etc/NonComposerComponentRegistration.php"
+        ],
+        "exclude-from-classmap": [
+            "**/dev/**",
+            "**/update/**",
+            "**/Test/**"
         ]
     },
     "autoload-dev": {
```

**Comment by zelgerj** [comment]
thanks for this! Very nice 👍 
I'll test it right away -> update: works :)

**Comment by davidalger** [comment]
Closing. Packages for 2.2 RC are now available. There are instructions to install via the rc packages on DevDocs: http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html

**Comment by tmotyl** [comment]
@davidalger this issue was not about installing single RC release. 
It was about being to install current dev branches. 
So if a new commit is merged to a dev branch like 2.1-develop, 2.2-preview I would like to be able to download it via composer.
Can you confirm that this is now possible?

**Comment by davidalger** [comment]
@tmotyl Sorry, I missed that in my original reading of the request. I'm asking about this to see what might be possible.

**Comment by tmotyl** [comment]
thanks a lot @davidalger

**Comment by tmotyl** [comment]
@davidalger please reopen the issue, as it's not solved and it's really a pain

**Comment by tmotyl** [comment]
@davidalger any update?

**Comment by davidalger** [comment]
@tmotyl I don't have any update and have actually stepped away from being a GitHub maintainer due to limited availability personally. Tagging @okorshenko here as he may be able to see about picking this back up.
