### ISSUE TITLE
Editing order with backordered items results in new order not correctly marking order items as backordered

### ISSUE THREAD

**Issue by develpr** [magento/magento2#10057]
### Preconditions
1. Magento version 2.1.5 
2. Tested on a few different specific PHP 7.x versions, but all php 7

### Steps to reproduce
1. Set a product up as backorderable - 0 quantity stock, "allow orders below 0", in stock, enabled
2. As a frontend customer, add this backordered product to a cart
3. Add an additional "normal" stock item to the cart (not backordered - this step may not be strictly required but is useful to make it easier to compare normal vs backordered line items) 
4. Go through a normal customer frontend order process with this product
3. After placing the order, note that in the order history / admin order view that the order items list shows "backordered" in the "item status" column, indicating that this particular product was ordered as a backorder product - **this is correct**

<img width="816" alt="screen shot 2017-06-26 at 10 17 11 am" src="https://user-images.githubusercontent.com/3022076/27543858-6dfca83c-5a59-11e7-8fda-c7bb1c4c0c07.png">

You can also look in the database and see that the `sales_order_item` table has a `qty_backordered` column with `1` - again, this is expected and correct

<img width="824" alt="screen shot 2017-06-26 at 10 22 07 am" src="https://user-images.githubusercontent.com/3022076/27543908-997d6316-5a59-11e7-935a-a274c5d6a750.png">

4. In the admin view on this order click "edit" and confirm that you want to cancel the previous order and place a new order. 
5. Do not change any quantities or other values, simply scroll down to the payment section and enter a valid payment
6. Submit the new "edited" order in the admin interface

### Expected result
1. The new order should be created with the same increment ID but with an appended `-1`
2. The order items / line items in the order should show up exactly as they were in the original order - **most critically, the product that was setup as a backorder item should show up as backordered status, and the previously referenced `qty_backordered` should also be 1 indicating that it was placed as a backorder - this should be exactly the same as the original order**

### Actual result
1. The backordered item shows up as a regular item - it is not correctly marked as backordered status

<img width="817" alt="screen shot 2017-06-26 at 10 25 16 am" src="https://user-images.githubusercontent.com/3022076/27544123-2f75dca4-5a5a-11e7-9555-4c3219c860d5.png">

Additionally, looking at the database directly shows that as you might guess the `qty_backordered` column is `NULL` and `qty_ordered` is 1. This is not correct, and incorrectly marks the item as a normal item.

<img width="501" alt="screen shot 2017-06-26 at 10 25 48 am" src="https://user-images.githubusercontent.com/3022076/27544175-53eacf36-5a5a-11e7-8a8a-b2019cb8b87f.png">

**Comment by smoskaluk** [comment]
Internal ticket created MAGETWO-70570

**Comment by magento-engcom-team** [comment]
@develpr, thank you for your report.
We've created internal ticket(s) MAGETWO-80464 to track progress on the issue.

**Comment by devamitbera** [comment]
Same issue is also existing for Magento 2.2.X

Have any update on this ?

**Comment by swnsma** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@swnsma thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by okorshenko** [comment]
Hi @develpr. Thank you for your report. 
The issue has been fixed in magento/magento2#14327 by @swnsma in 2.2-develop branch
Related commit(s):
 - [9addb449f372b66b2b73af6dafcbf1fb1b672f94](https://github.com/magento/magento2/commit/9addb449f372b66b2b73af6dafcbf1fb1b672f94)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @develpr. Thank you for your report. 
The issue has been fixed in magento/magento2#14444 by @mastiuhin-olexandr in 2.3-develop branch
Related commit(s):
 - [1f008f4f846993c62a433c029587124eebad0c5a](https://github.com/magento/magento2/commit/1f008f4f846993c62a433c029587124eebad0c5a)

The fix will be available with the upcoming 2.3.0 release.

**Comment by seansan** [comment]
Is this fix available or not? It should be available in 2.2 then in 2.3 ..... but I think it is still not solved and now an issue almost 3 years old

Also see here where a similar issues has existed for 3 years going on 4: https://github.com/magento/magento2/issues/10079
