### ISSUE TITLE
Captcha not working in Forgot password Frontend in magento2.1

### ISSUE THREAD

**Issue by Gammatesting123** [magento/magento2#10053]
Magento2.1 version in forgot password page captcha not working while I am entering the true captcha.
![iqjww](https://user-images.githubusercontent.com/22314841/27539135-eae057d8-5a98-11e7-9111-b7b0759fa927.png)

I did reindex and clean cache but it's not working.

**Comment by veloraven** [comment]
@Gammatesting123 if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
