### ISSUE TITLE
Make all Address (and others) Validation functions PUBLIC and accessible to bind into Plugins

### ISSUE THREAD

**Issue by pisc-software** [magento/magento2#10054]
### Steps to reproduce
1. Magento\Customer\Model\Address\AbstractAddress->validate() is a PUBLIC function
2. Magento\Customer\Model\ResourceModel\AddressRepository->_validate() is a PRIVATE function

### Expecation
All validation is handled on the Magento\Customer\Model\Address\AbstractAddress->validate()

### Actual Situation
1. All validation on Frontend Forms for CREATE ACCOUNT and EDIT ADDRESS use the AddressRepository->_validate() function which is a PRIVATE function.
2. Checkout, Multishipping, Paypal are using the Address->validate() function.
 
Question #1:
Why are there 2 validation routines for the same purpose?
One is a public function on the Address Model we can nicely tie into our extensions using a Plugin. For tying into the validation on AddressRepository we need to override the whole class. As the validation function there is private we even need to duplicate the save() function to add our validation code there.

Question #2:
Why are different validation approaches used for different frontend functions? Can this be please unified to ONE point of validation we can access and extend using the Plugin approach?

Please unify the code here, and allow Plugin Access to the ADDRESS VALIDATION routine. The current structure is making it difficult for us developers to add Address Validation nicely and without risking conflicts with other extensions trying to do the same.

Same applies to all other Validations on other models, these should be accessible to the Plugin Interceptor scheme to allow adding custom validation routines.

**Comment by magento-engcom-team** [comment]
@pisc-software please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.
It would be very helpful if you can submit pull request with the fix for the issue. Thank you
