### ISSUE TITLE
FedEx Track this shipment admin pop up shows no information

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/magento2#10066]
**Preconditions**
1. Magento 2.1.7, PHP 7.0.19, MYSQL 5.6.36-2.el6, CentOS 6.9
2. Created shipping connected to FedEx Web Services API

**Steps to reproduce**
1. Open shipment
2. Clik on Track this shipment

**Expected result**
1. Get tracking information (works well with other carrier : Colissimo on the same website)

**Actual result**
1. Lacking information
<img width="830" alt="capture d ecran 2017-06-27 a 11 23 02" src="https://user-images.githubusercontent.com/4211076/27581333-b9244c8c-5b2d-11e7-8172-160217148789.png">

I managed to temporarily solve this with seanbreeden's answer : 
[https://magento.stackexchange.com/questions/147075/magento-2-my-orders-order-shipments-track-this-shipment-results-in-invalid-met](https://magento.stackexchange.com/questions/147075/magento-2-my-orders-order-shipments-track-this-shipment-results-in-invalid-met)

<img width="846" alt="capture d ecran 2017-06-27 a 11 09 40" src="https://user-images.githubusercontent.com/4211076/27581407-eb660e88-5b2d-11e7-87a6-98c27e9ec965.png">

**Comment by YevSent** [comment]
Hi, @ShapesGraphicStudio, this issue already fixed on the develop branch.
I've created the ticket to backport the fix to 2.1.x version (`MAGETWO-69898`).

Duplicates https://github.com/magento/magento2/issues/8219.

**Comment by AirmanAJK** [comment]
I just upgraded to 2.1.8 and this bug still occurs. It has an easy fix and is well on its way to being a year old. What gives?

**Comment by orlangur** [comment]
@AirmanAJK you can try to backport fix https://github.com/magento/magento2/search?q=MAGETWO-63215&type=Commits&utf8=✓ by yourself if you don't want to wait for next `2.1.x` release containing a fix.

**Comment by magento-engcom-team** [comment]
Closing this issue as it duplicates #8219. Additionally fix is going to be delivered in `2.2.0` and `2.1.10`.

Thank you.
