### ISSUE TITLE
I am trying to modify the product data displayed on the home page

### ISSUE THREAD

**Issue by Darrendeng12** [magento/magento2#10063]
I am trying to modify the product data displayed on the home page

[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Product`;s:9:`attribute`;s:3:`sku`;s:8:`operator`;s:2:`()`;s:5:`value`;s:60:`MK1523, MK1368, MT86, M82, B102, WH04, MS08, L055`;]]"}}</p>

but But there is such a error：
![error](https://user-images.githubusercontent.com/24515279/27574414-ded0d30e-5b48-11e7-8924-e65f0306bf28.jpg)

We're sorry, an error has occurred while generating this email.

 Please help me out to get solution of this problem.

**Comment by Darrendeng12** [comment]
![error](https://user-images.githubusercontent.com/24515279/27574524-55d5be9c-5b49-11e7-8c83-66b54d77ab35.jpg)

**Comment by sivajik34** [comment]
enable developer mode, check in system.log,exception.log or apache error logs.

**Comment by Darrendeng12** [comment]
Thank@sivajik34 ，enable developer mode.The magento have a new error ：

main.CRITICAL: Exception: Notice: unserialize(): Error at offset 304 of 365 bytes in /opt/lampp/htdocs/ma/vendor/magento/module-widget/Helper/Conditions.php on line 34 in /opt/lampp/htdocs/ma/vendor/magento/framework/App/ErrorHandler.php:61

how should I do to solve this problem?

**Comment by korostii** [comment]
Looks like your single quotes got broken by an editor or some thing like that. Plus, the character count for the serialized SKUs list is wrong: you shouldn't edit it manually, really.
Try changing the quoted part to the following:

```
[s:4:'type';s:50:'Magento|CatalogWidget|Model|Rule|Condition|Product';s:9:'attribute';s:3:'sku';s:8:'operator';s:2:'()';s:5:'value';s:49:'MK1523, MK1368, MT86, M82, B102, WH04, MS08, L055';]]"}}
```
Alternatively, remove the whole widget and create again from scratch using admin UI, that shouldn't take too long.

If you are looking for some additional help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.

**Comment by Darrendeng12** [comment]
thank@korostii, I did not expect the character count for the SKUs count is wrong

**Comment by korostii** [comment]
Sure, glad I could help you.
Feel free to close the issue if it's resolved for you.
