### ISSUE TITLE
Paypal Payflow Pro Test credit card not working

### ISSUE THREAD

**Issue by mageprince** [magento/magento2#10068]
### Preconditions

1. Magento 2.1.7
2. PHP 7.0.17

### Steps to reproduce

1. Enable paypal payflow pro from admin with credentials
2. Set Test Mode "Yes" and Debug "Yes"
3. On checkout page enter paypal test credit card number for test transaction
4. But It shows "Please enter a valid credit card type number" validation error
5. Then I check this issue in Magento 2.1.5. It's working fine in Magento 2.1.5.

### Expected result

1. Paypal test Credit card number supported in Test mode.
2. It's working fine in Magento 2.1.5

### Actual result

1. Checkout Page
![checkout](https://user-images.githubusercontent.com/24751863/27583161-231b6f80-5b51-11e7-8341-802dff432719.png)

**Comment by mageprince** [comment]
It's conflicted with other payment modules.

**Comment by noahendale** [comment]
@mageprince Which payment modules was it conflicting with?
