### ISSUE TITLE
country_id dropdown not removed from shipping address form in new address popup

### ISSUE THREAD

**Issue by steros** [magento/magento2#10065]
### Preconditions
1. Magento 2.1.5
2. have only one country selected in "General" -> "General" -> "Country Options" -> "Allow Countries"
3. checkout as guest and go to shipping step, see that there is no country dropdown

### Steps to reproduce
1. log in as customer
2. go to shipping step
3. add a new address

### Expected result
1. the popup to add a new address opens
2. the popup form does not include a country dropdown 

### Actual result
1. the popup form has a country dropdown

**Comment by IlnitskiyArtem** [comment]
@steros, Thanks for reporting this issue.
We need more information about your configuration to reproduce this issue. Please identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue. 
In addition, please attach screenshots "Checkout page" (shipping step) for registered and unregistered customer.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
