### ISSUE TITLE
In Magento ver. 2.2.0-dev sort by & Pagination not showing in product list page( front end).

### ISSUE THREAD

**Issue by bluethink164** [magento/magento2#10064]
in front page sort by not showing up?
pagination does not show in the footer?

**Comment by misha-kotov** [comment]
@bluethink164 Please format your post to follow our [issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) so we can better troubleshoot the problem.

**Comment by davidalger** [comment]
Closing due to no reply from OP.
