### ISSUE TITLE
Magento adds tax to price, even though admin price already includes tax

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#10067]
### Precondtions
* Windows 10
* Apache 2.4.17
* MySQL  5.0.11-dev
* PHP 5.6.15
* Magento 2.1.7

### Steps to reproduce
1. Create a product with price £120
2. Add a Tax rate/rule which applies 20% tax to the product
3. Set [Stores > Configuration > Sales > Tax > Calculation Settings > Catalog Prices] to "Including Tax"
4. Set [Stores > Configuration > Sales > Tax > Price Display Settings > Display Product Prices In Catalog] to "Including and Excluding Tax"
5. Refresh caches
6. Load product from step 1 on frontend

### Expected result
* "Price excl Tax £100" and "Price incl Tax £120"

### Actual result
* "Price excl Tax £120" and "Price incl Tax £144"

**Comment by oleg-onufer** [comment]
Hi @JacobDrummond.
I cannot reproduce this issue.
What is  operating system where  your project is installed?
Please add screenshots "Calculation Settings" ,"Price Display Settings" sections

**Comment by JacobDrummond** [comment]
@oleg-onufer, here are my replication screenshots:

### Build product
![github_1](https://user-images.githubusercontent.com/8377620/27874368-2f70b086-61a7-11e7-8e0d-97e0d7fd6922.png)

### Configure tax
![github_2](https://user-images.githubusercontent.com/8377620/27874369-3153d48c-61a7-11e7-95f7-62057b8befd7.png)

I then clear caches and reindex.

### Wrong price shows on frontend
![github_3](https://user-images.githubusercontent.com/8377620/27874371-32f42bd4-61a7-11e7-9d9a-9d0c37c550ff.png)

**Comment by oleg-onufer** [comment]
Hi @JacobDrummond.
I cannot reproduce this issue.
What is operating system where your project is installed?
What is version your magento CE or EE?

-- Try clear the magento cache (php bin/magento cache:flush") and browser cache
-- Make sure that the settings relate to a particular website (If you have two or more websites)

**Comment by JacobDrummond** [comment]
@oleg-onufer,

**Environment**

This issue is present in our Windows dev environment and Ubuntu staging environment.

* Windows 10 / Ubuntu 14.04 LTS
* Magento CE 2.1.7

**Caches**

I am clearing all Magento and Google Chrome caches before refreshing frontend pages

**Scopes**

* No website/store scopes override tax settings
* No website/store scopes override product tax class or price

**Comment by oleg-onufer** [comment]
@JacobDrummond 
I cannot reproduce this issue 
Do this: 
 -- Caching Application = "Build-in cache"
 -- If you need to clear the cache use this command:  php bin/magento cache:flush
Maybe the problem is related to the new extension
Can you reproduce the issue on fresh installed  magento(and create a video)?

**Comment by oleg-onufer** [comment]
Hi @JacobDrummond.
Thanks for reporting this issue.
Internal ticket MAGETWO-70568 was created.

**Comment by JacobDrummond** [comment]
@oleg-onufer, this issue is still tagged as "needs update", despite an internal ticket being created. Do you still need replication guidance from me?

**Comment by oleg-onufer** [comment]
No thanks.

**Comment by korostii** [comment]
@oleg-onufer, in such case, could you please either update the issue status, or forward it to someone who can?

**Comment by JacobDrummond** [comment]
Hi @oleg-onufer,

Any idea when someone will be working on this? I understand you guys are very busy, but unfortunately this issue is blocking a project signoff.

Given that no-one else has chimed in, I'm guessing most users input pre-tax prices, thereby avoiding this bug. 

Do you have any suggestions for those who can only input post-tax prices?

**Comment by giorg** [comment]
Hi,
exactly same problem here, using 2.1.7 on linux/nginx. And as Jacob, also here this is blocking a project signoff.
please help

**Comment by giorg** [comment]
@JacobDrummond found the solution: the problem is the country.
https://github.com/magento/magento2/issues/7043

**Comment by JacobDrummond** [comment]
@giorg, that works for me. Thank you so much!

@oleg-onufer, it's a bit alarming that a major tax setting isn't even referenced from the "Tax" tab. E.g. somewhere in "Tax" have a field comment that says "Have you checked shipping origin?".

**Comment by kaseyfurlong** [comment]
@giorg the resolution outlined in #7043 is not solving the problem for us.  is there another solution to this issue? 
![capture](https://user-images.githubusercontent.com/28807148/29341470-83b86538-81f2-11e7-8618-6ac7d12509b9.JPG)

![capture2](https://user-images.githubusercontent.com/28807148/29341509-b55ae660-81f2-11e7-981f-d91b26285a47.JPG)

**Comment by kaseyfurlong** [comment]
@giorg please confirm what steps we can take to help expedite solution or assistance with this issue.

**Comment by kaseyfurlong** [comment]
work around found here: https://blog.amasty.com/little-known-discount-issue-in-magento-and-how-to-fix-it/

**Comment by magento-engcom-team** [comment]
@JacobDrummond, thank you for your report.
We've created internal ticket(s) MAGETWO-80015 to track progress on the issue.

**Comment by Tomasz-Silpion** [comment]
I've had exactly same problem several minutes ago and fixed it with setting shipping origin, cache flush, reindex and cache flush again.

**Comment by VincentMarmiesse** [comment]
Hello,
Any news on this issue?
I'm still having it on a Magento 2.2.2.

Shipping origin is set to France and France has 20% tax in my example.
Tax is calculated on shipping address.
Price entered in Catalog are Including tax and config is set accordingly.

In front, tax is added twice so if a product has a price of 100€, it's displayed as 120€.

**Comment by BrianHeeseIs** [comment]
Still having this issue on 2.2.4, any update on when this will be fixed?

**Comment by magently** [comment]
We couldn't reproduced the bug - tried on Magento 2.1, 2.2 and 2.3-alpha with PHP 7.0, 7.1 and 7.2.

**Comment by TristanPerchec** [comment]
You should check the **Sales > Tax > Calculation Settings > Enable Cross Border Trade** option and set it to **Yes**.
It should fix your problem.

**Comment by syno-ght** [comment]
Hello guys,

Any update on this issue ?

We need a fix for one of our clients.

Cross border trade is not an option in my case, I want the tax automatically deducted from the price.

Thanks,

**Comment by eliadcohenn** [comment]
> @oleg-onufer, here are my replication screenshots:
> 
> ### Build product
> ![github_1](https://user-images.githubusercontent.com/8377620/27874368-2f70b086-61a7-11e7-8e0d-97e0d7fd6922.png)
> 
> ### Configure tax
> ![github_2](https://user-images.githubusercontent.com/8377620/27874369-3153d48c-61a7-11e7-95f7-62057b8befd7.png)
> 
> I then clear caches and reindex.
> 
> ### Wrong price shows on frontend
> ![github_3](https://user-images.githubusercontent.com/8377620/27874371-32f42bd4-61a7-11e7-9d9a-9d0c37c550ff.png)

Hey,
How I creating the rule? :
**Add a Tax rate/rule which applies 20% tax to the product**

**Comment by ghost** [comment]
Best,

This is what happening on magento 2.3.2

![Calculation wrong](https://user-images.githubusercontent.com/15247780/62470262-5a56df00-b79a-11e9-8644-2b9d0dd91451.png)
![Calculation](https://user-images.githubusercontent.com/15247780/62470264-5a56df00-b79a-11e9-9d0b-0caf083755ba.png)

If i change Stores > Configuration > Sales > tax: Catalog prices including tax
Magento calculates + 21 Vat correctly. But my prices have the vat already.

If i change back to Catalog prices excluding tax it calculates 17.3600 Percent of Vat
So what is going on?

Best regards, hoping for a solution soon.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by Jeffrey-H** [comment]
> You should check the **Sales > Tax > Calculation Settings > Enable Cross Border Trade** option and set it to **Yes**. It should fix your problem.

This is true, except for when you want a customer group without tax. Then the price will be the same as the price including tax.
