### ISSUE TITLE
Request: ability to refresh cache (and FPC) per store

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1006]
Request: ability to refresh cache (and FPC) per store

We have many stores. And it becomes a problem when you are building/working on store B when store A is actually live and hence static. Now when we refresh the cache or all other related (like FPC) then it affects ALL stores ... this is a shame. 

It would be great if a store swticher or store selector could be added to throw away or relaod cache only for 1 specific store

(dont know if this is possible)

**Comment by snohe** [comment]
Thank you for your suggestion, @seansan.  We have logged this internally as MAGETWO-33595 and will review this request.

**Comment by pboisvert** [comment]
passing to Chuck as Performance PM

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Request-ability-to-refresh-cache-and-FPC-per-store/idi-p/46655).
