### ISSUE TITLE
have issue with Magento indexing from admin panel getting Fatal error: Uncaught Error: Class 'Bss\Reindex\Block\Backend\Grid\ItemsUpdater' not found in AbstractFactory.php:93

### ISSUE THREAD

**Issue by avanish512** [magento/magento2#10069]
I have issue with Magento 2 Indexing getting Fatal error: Uncaught Error: Class 'Bss\Reindex\Block\Backend\Grid\ItemsUpdater' not found in AbstractFactory.php:93 and things are working in SSH like upgrade Magento, indexing, cache flush everything working 
### Preconditions

1. Magento Version: 2.1.7
2. PHP 7.0.20

### Steps to reproduce

1. Login admin panel and hit indexing menu

### Expected result

1. able to load the site and admin panel. instead of showing error.

### Actual result

geting this Fatal error: Uncaught Error: Class 'Bss\Reindex\Block\Backend\Grid\ItemsUpdater' not found in AbstractFactory.php:93

**Comment by korostii** [comment]
`Bss\Reindex` part is a clear sign that something went wrong with [this 3rd-party module](https://bsscommerce.com/reindex-from-backend-for-magento-2.html) you use. 

Please contact the customer support of the seller/vendor (BSS Commerce, I assume) of that module you use. They should be able to provide you with an update or a patch.

**Comment by avanish512** [comment]
Thanks for your valuable comment it's same my lots of time
