### ISSUE TITLE
Magento Composer install

### ISSUE THREAD

**Issue by gxela** [magento/magento2#1007]
Why? if I have composer installed I should NOT have to git clone the magento repo. I should be able to create-project. Can we fix this? otherwise it's pretty lame, we have all these great command laying around and no developer knows about them to build around them. Times change. Lets all work together, no?
    
    composer create-project magento/magento my-store

**Comment by gxela** [comment]
What happens when someone says Magento three-times-in-a-row?

    (RSA) ~/Projects $ composer create-project magento/magento magento


                                                                 
      [InvalidArgumentException]                                     
      Could not find package magento/magento with stability stable.  
                                                                 


    create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]


    (RSA) ~/Projects $

**Comment by gxela** [comment]
your dreams may come true

**Comment by buskamuza** [comment]
If you want to use Composer only, you should use this project - https://github.com/magento/magento2-community-edition

Command will be:
```
composer create-project --stability=beta magento/product-community-edition .
```

This GitHub repository for contributions, so someone can clone the repository and fix/implement something.
