### ISSUE TITLE
Not authorized. issue with advanced reporting

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#10072]
When i click 'Go to advanced reporting' getting following message in the browser.
https://advancedreporting.rjmetrics.com/report
`Not authorized.`

Magento tag:
2.2.0-RC1.1 
community version.

**Comment by antboiko** [comment]
@sivajik34 What OS and PHP version are you using?

**Comment by sivajik34** [comment]
Ubuntu Linux 14.04.4
php 7.1

**Comment by IlnitskiyArtem** [comment]
@sivajik34, Thanks for contributing to this forum.
We've created internal ticket MAGETWO-70324 to address this issue.

**Comment by misha-kotov** [comment]
When this reporting functionality is released, it will require a subscription to Advanced Reporting, as well as a real domain name and SSL. More info and documentation to come on this. The internal ticket has been closed.
