### ISSUE TITLE
Magento 2-Notice: Undefined offset: 0 in /vendor/magento/module-configurator-product/model/product/type/variationMatrix.php online 39

### ISSUE THREAD

**Issue by raceves2005** [magento/magento2#10076]
Imported a list of Simple Products, all with consistent Attributes. Create a Configurable Product, when adding configurations certain Simple Products with the same Attribute Values will not show as a eligible Simple Product to associate with config product, we do not get any errors just a glitch that will not allow to associate with a config product. The second issue is that we have a manufacturer with an Extra Attribute "Concavity Profile", when importing those product and creating configurable products, when we hit save we get the error  "Magento 2-Notice: Undefined offset: 0 in /vendor/magento/module-configurator-product/model/product/type/variationMatrix.php online 39" When exporting the products "Concavity Profile" is removed from the list of attributes on simple products, in order to fix it we must import the simple products alone per Config product. These issues must be associated so that is why we are listing them together. 

### Preconditions

1. Magento 2.1.7
2. Stock Magento, using configurable products. 

### Steps to reproduce

1. Configurable Product with Attributes- Wheel Diameter, Wheel Bolt Pattern, Wheel Width, Concavity Profile, Wheel Offset
2. Import all Products with Excel and Attributes 
3. Create a configurable product
4.Create Configurations, then create only one automatic product, 
5. Remove Magento Created Configuration, 
6. Add Products Manually
7. Hit Save

### Expected result

1. Should save all attributes and Product Selection should have dropdown dependent on other selectoins. 

### Actual result

1. Replicates Error
2. Export Product and "Concavity Profile" Attribute is Missing
3. Must Re-Import Product Alone and at times it fixes the issue.

**Comment by heyqule** [comment]
Confirmed. I was tweaking some attributes and then the test config product got hit with this error when it loads in product edit.

**Comment by magento-engcom-team** [comment]
@raceves2005, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by katesuykovskaya** [comment]
@magento-engcom-team the condition to reproduce is - when creating configurable product you need to choose an attribute, that is not present in attribute set, that future simple products will be created
