### ISSUE TITLE
Price does not changed when selecting attribute values on category view.

### ISSUE THREAD

**Issue by zorenleolumosbog** [magento/magento2#10077]
### Preconditions

1. Magento ver. 2.1.7

### Expected result

1. What if the price label should be changed with their corresponding price when selecting attribute values  and if ever also the product title since the thumbnail is changing.

### Actual result

1. [Screenshot, logs]
<img src="https://s15.postimg.org/wl0kgr6iz/magento_category_view_price_does_not_changed.gif">

**Comment by Stas94** [comment]
@zorenleo We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by veloraven** [comment]
@zorenleo thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please format steps like:

**Steps:**
1. ...
2. ...
3. ....

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by eduard-kistner** [comment]
Just for someone landing here from search:
https://github.com/magento/magento2/issues/3150
https://github.com/magento/magento2/issues/10976
