### ISSUE TITLE
Save shipping cost when place order

### ISSUE THREAD

**Issue by kassner** [magento/magento2#1008]
Hi,

I'm not sure if this is widely used, but I have some clients where the shipping cost is not the same that is charged from their customers. I often see M1 shipping modules with `$rate->setCost(x.xx)`, but that information is not saved anywhere.

Can this be added to Magento 2 at least? Should I send a pull request?

Thanks!

**Comment by vpelipenko** [comment]
Hi @kassner, could you provide here business cases where it can be used?

**Comment by kassner** [comment]
@vpelipenko I'm not sure what are you expecting me to reply here, but it's pretty straight forward: some of my clients charge more for the shipping than it actually costs for them, but today is impossible to know the real cost of an order, since only the amount (which is displayed and billied) is saved on `sales_flat_order`.

**Comment by vpelipenko** [comment]
@kassner, thanks for explanation. Look like it will be valuable improvement. Could you create a pull request for that?

**Comment by vpelipenko** [comment]
@kassner, could you inform us about your decision on creating PR with suggested changes? Are you going to do it?

**Comment by kassner** [comment]
@vpelipenko what's the deadline? I can provide this PR but not yet.

**Comment by vpelipenko** [comment]
@kassner, there is no hard deadline, it is up to you. But please confirm, that you will on on it and provide approximate dates when you expect to see it ready.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-34880

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Save-shipping-cost-when-place-order/idi-p/46646).
