### ISSUE TITLE
Duplicate SKU possible if importing products

### ISSUE THREAD

**Issue by pointia** [magento/magento2#10080]
It is possible in Magento to save a product with a sku that has a leading or trailing whitespace. This can lead to duplicate skus when you import products without the leading or trailing slash. 

### Preconditions
1. Magento version 1.x and 2.x - the code is the same in both versions
2. PHP 5.5 5.6 7.0 7.1
3. MySql 5.5 5.6

### Steps to reproduce
1. First create a product in Magento Backend that has a trailing whitespace e.g. "SKU123 "
2. If you try to create a product with the sku "SKU123" you will get an error which is correct
3. Export de product data of the product with "SKU123 " and edit the file to remove the trailing whitespace
4. Import the new product data with the sku "SKU123" and a new product in Magento will be imported
5. Now we have 2 different products
6. Now open the first product with the sku "SKU123 " and edit the sku and remove the trailing whitespace
7. The product gets stored and now we have 2 products with the exact same sku - this is because the first product has a lower entity_id
8. If you now try to store the second product with the higher SKU you will get an error that the SKU does already exist

### Expected result
- Import should trim whitespaces as uniuqe validator does OR
- Unique validator should not allow to save the product with the lowest ID if the SKU is the same

### Actual result
- Import create 2 products
- Validator only displays a unique notice at products with a higher entity_id

**Comment by koenner01** [comment]
Probably related https://github.com/magento/magento2/issues/8235

**Comment by OleksandrBurianyk** [comment]
Thx for your reporting. We've created intenal ticket MAGETWO-70528

**Comment by magento-engcom-team** [comment]
@pointia, thank you for your report.
We've created internal ticket(s) MAGETWO-70528 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#37
