### ISSUE TITLE
Invalid login and password in magento 2

### ISSUE THREAD

**Issue by likhamahudda** [magento/magento2#10083]
Upgrade magento 1.9.x to 2.0.x with migration data tool. 
Actual result

When I try to login with any customer email and password I got "Invalid login and password.", but in the old store, the same customers working perfectly.

when i create  new user and New customer are login perfectly.

I have also change
 key Different.
vi magento1/app/etc/local.xml
vi magento2/app/etc/env.php

I have done all clear cache and re index  by command line
Please help me this is very difficulty issue for me

**Comment by likhamahudda** [comment]
I have got resole this issue on my self

After migration M1 to M2
old customer login error resole
Please update this query in database

**UPDATE customer_entity_varchar,customer_entity SET customer_entity_varchar.value = customer_entity.password_hash WHERE customer_entity_varchar.entity_id = customer_entity.entity_id and customer_entity_varchar.attribute_id='12'**

attribute_id means password type values id in customer_entity_varchar table

main problem old password value and new password values not match in magneto
![login_password](https://user-images.githubusercontent.com/23294648/27686097-de3314f0-5cee-11e7-9c07-79cb71a4d442.png)
![passwordmissmtah](https://user-images.githubusercontent.com/23294648/27686098-de37f0e2-5cee-11e7-8519-f04c08dd02ec.png)

**Comment by victor-v-rad** [comment]
Hi @likhamahudda 

Data Migration Tool **move** passwords from customer_entity_varchar to customer_entity table. So normally, **no** passwords data should be left in customer_entity_varchar table after migration. It is strange you have it. Maybe you changed the behavior of \Migration\Step\Customer\Data class in the tool.

**Comment by likhamahudda** [comment]
Hi **Victor**

Thanks for information
But we have faced this problem and data migration time we did not change anything in tool.
I think it may be issues thats why i post this may to help full for other

**Comment by victor-v-rad** [comment]
Oh. I see you migrated to Magento 2.0.x. The latest tool 2.1.7 ver. most likely contains the fix for your issue.

**Comment by likhamahudda** [comment]
Hello,

I got another solution and very quick and easy

Just Empty the table (TRUNCATE) " customer_entity_varchar "

100% sure login old customer in New magento 2

Thanks

**Comment by wcladesh** [comment]
Hello @victor-v-rad,
I have the same issue in Magento Version 2.2.4 which is migrated from Magento 1.9.1.0.
I have already run command "php -f bin/magento customer:hash:upgrade"
but this is not helping me. Please suggest me.

Can I Truncate table as suggested @likhamahudda  
 **customer_entity_varchar** 

is this solution is ok and will not harm for other functionality.

Please help me.

**Comment by wcladesh** [comment]
Hello @victor-v-rad,
Please give any solution to this issue, I have more than 1.4 million customers but after migration old password is not working.

Please help me.

**Comment by wcladesh** [comment]
Hello @victor-v-rad,
This is Magento Migration issue,Magento2 is not proper encrypt/decrypt password same as per Magento.

this Issue is still in 2.2.4 version, please provide either any patch or help to resolve that issue. 

Thanks.

**Comment by jimains** [comment]
@wcladesh Did you ever get a solution for this?

**Comment by wcladesh** [comment]
Hi @jimains ,I found the solution and develop a custom module for it.
below is the di.xml in vendorname/modulename/etc/frontend/di.xml

`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Framework\Encryption\Encryptor" type="Vendorname\Modulename\Encryption\Encryptor" />
</config>`

 Encryptor.php file  in path  vendorname/modulename/\Encryption\


`class Encryptor extends \Magento\Framework\Encryption\Encryptor {
    private $hashVersionMap = [
        self::HASH_VERSION_MD5 => 'md5',
        self::HASH_VERSION_SHA256 => 'sha256'
    ];

    public function hash($data, $version = self::HASH_VERSION_LATEST) {
        return sha1($data);
    }

}`

**Comment by damianm2007** [comment]
> Hi @jimains ,I found the solution and develop a custom module for it.
> below is the di.xml in vendorname/modulename/etc/frontend/di.xml
> 
> `<?xml version="1.0"?> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd"> <preference for="Magento\Framework\Encryption\Encryptor" type="Vendorname\Modulename\Encryption\Encryptor" /> </config>`
> 
> Encryptor.php file in path vendorname/modulename/\Encryption\
> 
> `class Encryptor extends \Magento\Framework\Encryption\Encryptor {
> private $hashVersionMap = [
> self::HASH_VERSION_MD5 => 'md5',
> self::HASH_VERSION_SHA256 => 'sha256'
> ];
> 
> ```
> public function hash($data, $version = self::HASH_VERSION_LATEST) {
>     return sha1($data);
> }
> ```
> 
> }`

Please send me this fix... Because this code have bugs views on the place... THX.
