### ISSUE TITLE
Cannot change error message on checkout "An error occurred on the server. Please try again"

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#10084]
### Preconditions

1. Magento 2.1.4
2. PHP 7
3. Production mode

### Steps to reproduce

1. Wanted to change the generic "An error occurred on the server. Please try to place the order again" to "We could not place this order. Please call us to complete."
2. Changed the text in vendor/magento/module-checkout/Model/PaymentInformationManagement.php 
vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php
3. Cleared the static files, re-deployed static files, cleaned and flushed the cache. Also re-compiled for good measure.

### Expected result

1. When an error occurs in checkout the error message should read "We could not place this order. Please call us to complete."

### Actual result

1. Same error message occurs everytime "An error occurred on the server. Please try to place the order again."

**Comment by YevSent** [comment]
Hi, @pioneerathletics, you should not change any files in the `vendor` directory. Instead, if you want to implement custom error message for the place order flow, you need to create your own implementation of `\Magento\Checkout\Api\PaymentInformationManagementInterface` and `\Magento\Checkout\Api\GuestPaymentInformationManagementInterface`, and change preferences of these interfaces to new implementations in the `di.xml`

**Comment by pioneerathletics** [comment]
Hi,

Could you point me to any articles that show how to do this? Or could you be more implicit in explaining this process?

**Comment by YevSent** [comment]
@pioneerathletics, you can try to find more details on https://magento.stackexchange.com/ or on [Magento Forums](https://community.magento.com/). This Github, only for the bug reports.

But, in general you need to implement `PaymentInformationManagementInterface` and `GuestPaymentInformationManagementInterface` interfaces. Your behavior should be similar to the current implementation to do not break the place order functionality. And after that, you need to specify new preference like in [Checkout Module di.xml](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/etc/di.xml#L23-L24).

As another solution you can use [plugins](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html) to customize exception messages. I suppose the `after` plugin should be enough to analyze exception and provide customization.

But anyway, you should be sure what error messages customization won't "open" sensitive data to the customer.

I'm closing this ticket as not a bug.

**Comment by pioneerathletics** [comment]
So why is there just a generic "an error occurred on the server" message when a customer inputs something incorrectly? We've had customers complain because they think something is wrong with the website, because it says an error occurred on the server. Instead why not display "we could not place the order" or something that doesn't make it seem like there's something wrong with the website?

**Comment by gx2g** [comment]
yeah I'm having this same issue with customers as well. the fact that we can't change error messages at checkout makes our life very hard when dealing with customers. the idea is for the customer to make the transaction not shy away because the default error messages are to vague and make the platform look buggy.

**Comment by YevSent** [comment]
Hi, we are working on payment error messages customization. Unfortunately, I can't provide in which release it will be published but we are planning to do it in one of the next patch releases.

**Comment by pioneerathletics** [comment]
Hi @joni-jones,

That's fantastic! Can you answer if it will be released with a 2.1.x patch, hopefully not just a 2.2.x patch?

**Comment by YevSent** [comment]
@pioneerathletics, I'm not sure if it possible to do in a backward compatible way but we will discuss such possibility.

**Comment by pioneerathletics** [comment]
I really hope you can, for us using 2.1.x this would be a huge improvement. In my opinion, you wouldn’t even really need to make a “customizable” error message, although it would be nice. Just a message that tells customers “We cannot complete your order please call [store phone number]” instead of the customer thinking there is an error on the server and thus the website.

**Comment by YevSent** [comment]
But such customization you can do even now. Not the best solution but you can use "around plugins" or provide own implementation for `PaymentInformationManagementInterface` or `GuestPaymentInformationManagementInterface` interfaces.

**Comment by pioneerathletics** [comment]
True, but as you say it's not the best solution. Either way implementing this in the native Magento install will be a large improvement in this area. I am excited to see when this is implemented-is there an internal ticket number for this so I can see the progress?
