### ISSUE TITLE
Invalid URL's : Unable to load theme by specified key 

### ISSUE THREAD

**Issue by noprobz09** [magento/magento2#10081]
**Preconditions**
Magento 2.1.3

**Steps to reproduce**

I tried to input invalid URL's or URL's not found on the site.

**Expected result**
404 page

**Actual result**
Error display: Exception #0 (LogicException): Unable to load theme by specified key: '4'
Screenshot: https://www.screencast.com/t/8e4nN5O94h

I tried to fixed using the suggestion from google search but nothing works.

**Comment by 1408sheva** [comment]
@noprobz09 Are you using a theme that you made yourself or a theme bought from a vendor?
Does the error show when switching to the Magento luma theme? If not please contact the theme vendor
and please close the ticket as there is a good chance it is to do with your theme are a custom module or a module shipped with the theme. If it is not, then please add more details to your description of the steps you followed when identifying this issue. Screenshot, movie or logs would be helpful, too.

**Comment by noprobz09** [comment]
Hello @1408sheva , Yes, I made the custom theme and the issue still occur when I switch the theme into Magento Luma and Magento Blank. Is there any sql code that would resolved this issue?

**Comment by allamsettiramesh** [comment]
Team, am also facing this issue, is there any solution

**Comment by 1408sheva** [comment]
Please add screenshots of the problem.

**Comment by 1408sheva** [comment]
Hi, @noprobz09. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by noprobz09** [comment]
Hello @1408sheva, this is the only screenshot that I can provide https://www.screencast.com/t/8e4nN5O94h. It occurs only when the page is not found :(

**Comment by magento-engcom-team** [comment]
@noprobz09, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
