### ISSUE TITLE
Currency Price filter is only using the base currency

### ISSUE THREAD

**Issue by jaycroll** [magento/magento2#10092]
When switching currencies, the price filter on the layered navigation only filters using the base currency price and not the current currency price.

### Preconditions
1.  Magento 2.1.7
2. Apache 2.4
3. PHP 7.0.4
4. MariaDB 10
5. Block_html Caching is disabled 
6. OS: MAC OSX(El Capitan), Ubuntu 16, Windows 10 (tested on three environments)

### Steps to reproduce

1. Set base currency to AUD, add USD as additional allowed currency
Store>Configuration>Web>Currency Setup
![screen shot 2017-07-03 at 12 11 21 pm](https://user-images.githubusercontent.com/1792445/27778060-a21c9a50-5fea-11e7-9492-fe77968e3eb9.png)
Store>Currency Rates
![screen shot 2017-07-03 at 12 25 27 pm](https://user-images.githubusercontent.com/1792445/27778148-2b5ecf4a-5feb-11e7-9705-7a1657a6ee51.png)
2. Go to (any) category page, then filter current products using the price filter on the layered navigation. (see image 1)
![screenshot at jul 03 12-23-44](https://user-images.githubusercontent.com/1792445/27778169-529fecec-5feb-11e7-8299-6e361a341d10.png)

3. Switch Currencies and see price filter results
![screen shot 2017-07-03 at 12 24 09 pm](https://user-images.githubusercontent.com/1792445/27778189-70e1f344-5feb-11e7-9a6a-9b677d1aec8b.png)

### Expected result
1. Products should be filtered according to the current currency 

### Actual result
1. Products are filtered using the base currency only

![image](https://user-images.githubusercontent.com/1792445/27672987-d3748954-5cd0-11e7-911e-a847620a4342.png)

![image](https://user-images.githubusercontent.com/1792445/27672911-80f252f6-5cd0-11e7-9982-a4f19ff31178.png)

**Comment by Stas94** [comment]
@jaycroll We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by jaycroll** [comment]
The pre conditions are already in the post

Anyway, updated steps

**Comment by oleg-onufer** [comment]
Hi @jaycroll.
I cannot reproduce this issue.
Please add more details to your description of the steps you followed when identifying this issue. 
Screenshots would be helpful, too.

**Comment by jaycroll** [comment]
Hi @oleg-onufer, I've updated the procedures and also added some screenshots.

**Comment by oleg-onufer** [comment]
Hi @jaycroll.
I cannot reproduce this issue.
Do this:
 -- Caching Application = "Build-in cache"
 -- Block_html Caching is enable
 -- Try clear the magento cache (php bin/magento cache:flush") and browser cache 
If that does not help fix it install  fresh magento2 and try  reproducing this issue

**Comment by moejoee91** [comment]
Hello jaycroll
please let me know, did you find a solution? 
i'm facing the same issue, and i think that's a misconfiguration somewhere, but i'm not sure where, please let me know if you have any update
