### ISSUE TITLE
passwordMinCharacterSets not including international characters

### ISSUE THREAD

**Issue by yumicom** [magento/magento2#10095]
passwordMinCharacterSets not including international (not latin) characters in /lib/web/mage/validation.js

### Preconditions
Magento 2.1.7, PHP 7.0.20 & MySQL 10.1.24-MariaDB

### Steps to reproduce
1. Go to adminpanel - stores - configuration - customers - customers configuration - Number of Required Character Classes and set 3.
2. Go to /customer/account/create/
3. Enter the password, using Lower not latin letters, Upper not latin letters and Digits.

### Expected result
1. Registration succesfull

### Actual result
1. Error "Minimum of different classes of characters in password is 3. Classes of characters: Lower Case, Upper Case, Digits, Special Characters."

**Comment by Andrii-Deineha** [comment]
@yumicom Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-70472.

**Comment by magento-engcom-team** [comment]
@yumicom, thank you for your report.
We've created internal ticket(s) MAGETWO-70472, MAGETWO-80384 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @yumicom. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/60

**Comment by magento-engcom-team** [comment]
Moved per @misha-kotov label update.
