### ISSUE TITLE
There is no way to add stock items to configurable used products collection

### ISSUE THREAD

**Issue by idziakjakub** [magento/magento2#10098]
I wanted to add modification to load stock items for simple products associated to configurable product. I spend few hours of finding why collection items hasn't stock info loaded, and when I added plugin beforeLoad collection with method from stock helper "[addIsInStockFilterToCollection](https://github.com/magento/magento2/blob/2.1/app/code/Magento/CatalogInventory/Helper/Stock.php#L148-L163)" I have found there is no way to allow stock items loading because in this method collection flag "has_stock_status_filter" is always setted:

https://github.com/magento/magento2/blob/2.1/app/code/Magento/ConfigurableProduct/Model/Product/Type/Configurable.php#L624

My proposition is to add new boolean parameter to method "getUsedProducts" which will be adding stocks info to this collection items.

### Preconditions
1. Magento 2.1.7

### Steps to reproduce
1. Add plugin with method "beforeLoad" for class "Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable\Product\Collection" which is calling method from stock helper "addIsInStockFilterToCollection"
```
public function beforeLoad(Collection $productCollection, $printQuery = false, $logQuery = false)
    {
        $this->stockHelper->addIsInStockFilterToCollection($productCollection);
        return [$printQuery, $logQuery];
    }
```
2. Try to load used products for configurable product
3. Check loaded products has information "is_salable"

### Expected result
1. Simple products collection with "is_salable" information in data

### Actual result
1. Simple products collection without "is_salable" information in data

**Comment by magento-engcom-team** [comment]
@idziakjakub, thank you for your report.
We've created internal ticket(s) MAGETWO-80539 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @idziakjakub

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@idziakjakub thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
