### ISSUE TITLE
Adding http-equiv meta tag in default_head_blocks.xml

### ISSUE THREAD

**Issue by RedEnzian** [magento/magento2#10090]
### Preconditions

1. Magento 2.1.7
2. Apache 2.4 / PHP 7.0.19

### Steps to reproduce

1. In your Theme add a "Magento_Theme/layout/default_header_blocks.xml" file
2. add a head section with
`<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />`

### Expected result

1. When rendering the HTML der should be a 
`<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />` 
somewhere in the Head section

### Actual result

1. After Rendering the HTML the following can be found:
`<meta name="" content="IE=edge,chrome=1" />`

Also tried other types of meta tags (property, itemprob) they also get removed.

**Comment by IlnitskiyArtem** [comment]
@RedEnzian, Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70448 to address this issue.

**Comment by pooshok** [comment]
You should use `<meta name="x_ua_compatible" content="IE=edge,chrome=1"/>`
See getMetadataTemplate in magento/framework/View/Page/Config/Renderer.php for details

**Comment by magento-engcom-team** [comment]
@RedEnzian, thank you for your report.
We've created internal ticket(s) MAGETWO-70448 to track progress on the issue.

**Comment by briscoda** [comment]
I am working on this one, can you please assign it to me?  #squashtoberfest

**Comment by briscoda** [comment]
I think this one could be resolved with documentation rather than code as @pooshok has mentioned.

@okorshenko @magento-engcom-team
