### ISSUE TITLE
Invoice increment id uses wrong entity type

### ISSUE THREAD

**Issue by WJdeBaas** [magento/magento2#1009]
When I place an order it gets increment id 100000001, the invoice receives the next increment id 100000002.
The next order gets increment id 100000003, and the invoice receives the next increment id 100000004 and so on.

I've inserted a new record in table eav_entity_store with the correct entity_type_id (6) , but this is ignored.

**Comment by WJdeBaas** [comment]
The same goes for the shipments, it gets increment id 100000005

**Comment by WJdeBaas** [comment]
Where / how can I submit a patch ?

**Comment by Sanuch** [comment]
You can create pull request

**Comment by WJdeBaas** [comment]
Hi Sanuch,

The button "Create Pull Request" is visible but disabled.

**Comment by Sanuch** [comment]
You should fork this repository and made changes in your fork and after them you can create pull request from your repository

https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request/

**Comment by WJdeBaas** [comment]
Thanks for the explanation Sanuch, I've just submitted the pull request.

**Comment by vpelipenko** [comment]
Pull request: https://github.com/magento/magento2/pull/1010

**Comment by joanhe** [comment]
@WJdeBaas Since you submitted the pull request, would you mind to close this issue?
