### ISSUE TITLE
API Rest. How to get product list with store infomation?

### ISSUE THREAD

**Issue by davbludev** [magento/magento2#10093]
Hello!
How to get products with {store_id}/{store_code} in response or by {store_id}/{store_code}?
At the moment I request products and accept response without store information.

**Comment by misha-kotov** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

PS you may want to use the <store_code> parameter in the REST request URL as described on [this page](http://devdocs.magento.com/guides/v2.0/rest/rest_endpoints.html).
