### ISSUE TITLE
Swagger schema doesn't show the services with session-based authentication

### ISSUE THREAD

**Issue by alessandroniciforo** [magento/magento2#10099]
In the Swagger UI the services with session-based authentication are not shown even if I'm logged in.

This bug has been introduced in Magento CE 2.1.7, more precisely by APPSEC-1679 (https://magento.com/security/patches/magento-2014-and-217-security-update). This security fix disables the session-based authentication on any request without the header `X-Requested-With: XMLHttpRequest`. Swagger UI to load the services list makes a request to `http://your.domain/rest/default/schema?services=all` without that header, thus receiving the list of services with anonymous authentication.

### Preconditions
1. Magento CE 2.1.7
2. Browser Chrome

### Steps to reproduce
1. Open the homepage of your Magento instance in a browser
2. Log in as a customer
3. Open the Swagger UI (`http://your.domain/swagger`)

### Expected result
4. I see all the services with anonymous AND session-based authentication

### Actual result
4. I don't see the services with session-based authentication

### Technical details
The class providing the check on the `X-Requested-With` header is `Magento\Webapi\Model\Plugin\Authorization\CustomerSessionUserContext`. In my opinion, this class should not restrict the access if the current request is for the API schema.

**Comment by RomanKrut** [comment]
Hi @alessandroniciforo 
Thanks for your report. The internal ticket was created MAGETWO-70502

**Comment by pyyick** [comment]
How's it going on? It's very inconvenient not showing those APIs.

**Comment by magento-engcom-team** [comment]
@alessandroniciforo, thank you for your report.
We've created internal ticket(s) , MAGETWO-80328 to track progress on the issue.

**Comment by engcom-Charlie** [comment]
Hello @alessandroniciforo 
We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

**Testing scenario:**

1. Open the homepage of your Magento instance in a browser
2. Log in as a customer
3. Open the Swagger UI (http://your.domain/swagger)

**Result:**
I see all the services with anonymous AND session-based authentication
![image](https://user-images.githubusercontent.com/51680850/70431047-c87f1b80-1a84-11ea-88c2-d78ba883d3e2.png)

So i have to close this issue as not reproducible on Magento 2.4-develop.

Thanks for your report!
