### ISSUE TITLE
Why can't select product attribute set when add new product at version updated 10/11/2012

### ISSUE THREAD

**Issue by SunshineTech** [magento/magento2#101]
When adding new product, the product type list can't open in IE9. At same time, there is not the product attribute set to select.

**Comment by rapidmod** [comment]
I can create and view the sets when creating a new product. I cant add an attribute set to any products.

**Comment by davidalger** [comment]
@RapidMod Please open a new issue, and be sure to include complete details on what you're attempting and where it's going awry. Thanks!
