### ISSUE TITLE
Magento2 in admin category showing many products but in frontend it shows limited product.

### ISSUE THREAD

**Issue by bluethink164** [magento/magento2#10104]
![iphone 4 4s id 92 categories inventory products magento admin](https://user-images.githubusercontent.com/29700825/27725190-ce26c486-5d92-11e7-8cc2-d10b55167c5b.png)
![apple shop by brands](https://user-images.githubusercontent.com/29700825/27725195-d2e4a600-5d92-11e7-98a9-821d485207db.png)

as shown in all product list pages.

**Comment by antboiko** [comment]
@bluethink164 Please format your post to follow our [issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) so we can better troubleshoot the problem.

**Comment by ihor-sviziev** [comment]
@bluethink164 products could be assigned to category, but they are out of stock, not assigned to website, not visible individually, etc. From your description it's not possible to identify the issue.

**Comment by epson121** [comment]
This might be relevant: https://github.com/magento/magento2/issues/8018

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
