### ISSUE TITLE
Unable to use cart price rule when assigned to a specific customer group (No coupon)

### ISSUE THREAD

**Issue by araranga** [magento/magento2#10103]
### Preconditions
Magento 2.1.7

### Steps to reproduce
1. Navigate to admin
2. Create a new customer group

<img src="https://preview.ibb.co/b5AwTQ/cs1.png" alt="cs1" border="0">

3. Create a new account and assign to the new customer group:

<img src="https://preview.ibb.co/nsXX2k/cs2.png" alt="cs2" border="0">

4. Create a new cart price rule with no coupon and assign only for the customer group

<img src="https://preview.ibb.co/bEQVoQ/cs3.png" alt="cs3" border="0">

5. Navigate to the front end of the site and login as the customer
6. Add a product to cart
7. Pay attention to the cart page total price

### Expected result
1.10% should be taken from the cart based on the cart price rule setup

### Actual result
No changes in the price.

**Comment by antboiko** [comment]
@araranga thanks for the report. Please also add the information about the environment you're running and Magento version.

**Comment by araranga** [comment]
Hi @antboiko , We are using Magento 2.1.7

**Comment by RomanKrut** [comment]
@araranga Hi, i was tried to reproduce this issue, and i can`t. 
![cart_price_rule](https://user-images.githubusercontent.com/27814479/27735226-1deb36d2-5da7-11e7-9d30-b04f0e3fce42.png)
Please check your cart price rule "Discount Amount" configuration 
![config](https://user-images.githubusercontent.com/27814479/27735324-96949bc8-5da7-11e7-90c4-cac8c28791f5.png)

**Comment by araranga** [comment]
Hi @krutkoroma79911 ,

Did you create new customer group and assign the customer? and assign the cart rule to trigger on specific customer group only?

Regards.

**Comment by RomanKrut** [comment]
@araranga Yes, Create a new group
![screenshot_1](https://user-images.githubusercontent.com/27814479/27779759-d1021420-5fcd-11e7-8ab6-06636c9383f6.png)
Create customer and assign him to new group
![screenshot_2](https://user-images.githubusercontent.com/27814479/27779765-dd49735e-5fcd-11e7-9e1f-def4aa952824.png)
Create new cart price rule
![screenshot_3](https://user-images.githubusercontent.com/27814479/27779779-ed44648a-5fcd-11e7-8509-0d78bc48a9eb.png)
![screenshot_4](https://user-images.githubusercontent.com/27814479/27779794-fc6947aa-5fcd-11e7-8da3-9513555b6f72.png)
Login in as a customer and go to checkout on the product
![screenshot_5](https://user-images.githubusercontent.com/27814479/27779807-09c73dda-5fce-11e7-9dc0-a476055501bb.png)
If i missed some steps to reproduce your issue, please provide more detailed steps.

**Comment by araranga** [comment]
Hi @krutkoroma79911 ,

Can you try also to exclusion of some categories in the cart rules? Ex. Only products not assign in category 1, will be able to trigger the discount.

Regards,
Ardee

**Comment by RomanKrut** [comment]
@araranga Hello, I was tried to do it and see the result
At the first I added new thing at the rule and include two categories (each category has product in)
![new](https://user-images.githubusercontent.com/27814479/27834285-0de32da4-60df-11e7-803e-35ef39450417.png)
Then I try to add products to cart and checkout them
Only product from category 2 added, discount = 10
![category 2 product](https://user-images.githubusercontent.com/27814479/27834404-8c8dd29e-60df-11e7-837a-a7b4db45fd0b.png)
Added product from category 4, discount = 20
![cat2andcat4](https://user-images.githubusercontent.com/27814479/27834436-abbcd9da-60df-11e7-8a6e-24c22ad7e23c.png)
Added product from category 1, discount still = 20. It works correctly
![cat2andca4andcat1png](https://user-images.githubusercontent.com/27814479/27834471-c9085afa-60df-11e7-94e5-dd0dbffa6d3a.png)

**Comment by araranga** [comment]
Hi @krutkoroma79911 ,

below is my configuration of customer and assign it to the customer group:
<img width="416" alt="screen shot 2017-07-06 at 10 31 59 am" src="https://user-images.githubusercontent.com/12805287/27893364-d591cc80-6237-11e7-897d-7002d7e24896.png">

Here is my configuration and settings for my cart rule:
<img width="1133" alt="screen shot 2017-07-06 at 10 39 01 am" src="https://user-images.githubusercontent.com/12805287/27893365-d59303ac-6237-11e7-9616-e8dc67d0911b.png">
<img width="1145" alt="screen shot 2017-07-06 at 10 39 15 am" src="https://user-images.githubusercontent.com/12805287/27893363-d5902a1a-6237-11e7-8325-4fa199cce775.png">

10% off is not showing correctly.
<img width="1189" alt="screen shot 2017-07-06 at 10 39 29 am" src="https://user-images.githubusercontent.com/12805287/27893366-d59c32b0-6237-11e7-8123-05552e74b8a5.png">

**Comment by RomanKrut** [comment]
@araranga Can you please recheck this problem on fresh install of Magento 2? In my case i cannot to reproduce it.

**Comment by sonline** [comment]
@krutkoroma79911 this is not right ... the problem only exists in cart ... when i go to checkout (shipping or billing) the cart rule/coupon is displayed .. but in cart the rule/coupon fpr specific Group isnts displayed!

When i give the rule to all groups then in cart also is displayed.

**Comment by eldonbite** [comment]
Seems related to issue #10009

**Comment by RomanKrut** [comment]
@eldonbite #10009 Issue is about catalog price rule, but this issue is about cart price rule and it is not reproducible on clean instance.

**Comment by magento-engcom-team** [comment]
@araranga, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
