### ISSUE TITLE
Permanent Redirect for old URL didn't created on Store View level

### ISSUE THREAD

**Issue by klakovsky** [magento/magento2#10101]
### Preconditions

1. Magento CE 2.1.7 fresh instans without sample data.

### Steps to reproduce

1. Create new simple product with Product Name="simple1", Price=1 and save them.
2. Click Edit this product. Select "Store View = Default Store View". Change URL Key = simple1-new1, uncheck checkbox "Use Default Value" and save product.
3. Go to "Marketing->URL Rewrites", set filters "Request path"="simple1".

### Expected result

1. We see 1 permanent redirect from "simple1.html" to "simple1-new1.html"

### Actual result

1. We can not see  any permanent redirects.

**Comment by 1408sheva** [comment]
@klakovsky Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70437 to address this issue.

**Comment by magento-engcom-team** [comment]
@klakovskiy, thank you for your report.
We've created internal ticket(s) MAGETWO-70437 to track progress on the issue.

**Comment by p-bystritsky** [comment]
This issue is already fixed in 2.2-develop.
