### ISSUE TITLE
Minicart is not getting updated when the product price in the cart is changed from the backend.

### ISSUE THREAD

**Issue by abhilashv1985** [magento/magento2#10119]
### Preconditions

1.  Magento ver. 2.1.7 CE
 2. PHP 7.0.15-0ubuntu0.16.04.4
 3. MySQL version 5.7.17-0ubuntu0.16.04.1

### Steps to reproduce

1. Add any product into cart
2. Change the product price from the backend.
3. Refresh the cart. 
4. The price of the product in cart is getting updated in the cart but not getting updated in the minicart.

### Expected result

1. Once the price of the product is changed from the backend, it should get reflected in the minicart as well.

**Comment by oleg-onufer** [comment]
Hi @abhilashv1985.
There is internal ticket MAGETWO-56534 for your issue. This bug was fixed in 2.2 (branch 'develop')

**Comment by abhilashv1985** [comment]
@oleg-onufer 
Thanks for the reply !

May I know when 2.2 will be released ? Should we wait for 2.1.8 and 2.1.9 to get released before 2.2 releases ?

**Comment by EmilyPepperman** [comment]
@abhilashv1985 I think Magento is planning on releasing 2.2 in September.

**Comment by abhilashv1985** [comment]
Are there any patches available for the fix ? September seems too long :)

**Comment by magento-engcom-team** [comment]
@abhilashv1985 You may look at the [commits](https://github.com/magento/magento2/search?q=MAGETWO-56538&type=Commits) which have `MAGETWO-56538` in the description.

We are closing this issue for now as fix is going to be released together with 2.2.0 soon.
Thank you.
