### ISSUE TITLE
CAN'T CREATE A NEW USER ROLES

### ISSUE THREAD

**Issue by lojasmarques** [magento/magento2#10116]
### Preconditions

1. 
2. 

### Steps to reproduce

1. Fiz o Login no Magento 2.1.6 
2. Acessei o Menu 'Sistema'
3.  Cliquei em 'User Roles'
4. E depois em "Adionar nova permissão"

### Expected result

1.  Criar outro nível de acesso ao sitema

### Actual result

1. [Screenshot, logs]
Não consegui criar outro

**Comment by veloraven** [comment]
@lojasmarques thank you for your report.
Could you please translate your message to English to avoid miss communication?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
