### ISSUE TITLE
302 redirects instead of right 301 redirects when https is enabled / big SEO mistake

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#10113]
Precoditions:
All magento 2 versions

When enabling https in the magento2 backend for all sites the fronted pages are redirected to the https versions like:

http://www.domain.com
-->
https://www.domain.com

Great so far - but the redirects should be a 301 (permanent) and not a 302 like it is when enabling this option.

We had the same issue now on 3 shops (no matter if nginx / apache etc.) - all redirects where 302.

This normally ends up in critical ranking drops in the Google SERPS.
Can anyone confirm the 302 redirects as well and has anyone an idea how we can get 301 instead of 302 (nginx with varnish and redis installed).

Thanks!

**Comment by davidalger** [comment]
@andidhouse What I do is include the following in the vhost configuration for each domain we deploy on:

```
server {
    listen 80;
    server_name .example.com;
    return 301 https://$host$request_uri;
}
```

This also has the benefit of a super fast 301 since it's coming from Nginx vs having to bubble down to the application. That said, I believe there is a configuration in Magento settings to send a 301 vs a 302 (the default). Pretty sure the default is 302 because it's (original) primary use case was redirecting the user to the configured base URL when they landed on say example.com vs www.example.com. Be that as it may, I'd recommend just putting the above in your nginx configuration.

**Comment by andidhouse** [comment]
hi @davidalger , many thanks!

Just found that option and it is really set by default to 302 - in my opinion a big mistake to not set this as default to a 301 from a SEO perspective.

But thanks! Do you have any experience with this config and running varnish also?

**Comment by davidalger** [comment]
@andidhouse We run varnish on all our M2 sites.

In our stack, a request moves through like this: nginx (ssl termination and static assets) -> varnish (cache layer) -> nginx (application/backend) -> php-fpm (magento).

This redirect happens in that first nginx layer. I put it in the vhost configuration along with the the ssl termination.

**Comment by veloraven** [comment]
@andidhouse thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by andidhouse** [comment]
@veloraven thanks but no thanks.

Did that too often and not one bug we reported was fixed (some are reported over one year ago).

I think we wills stop reporting - i cannot see any benefit of reporting bugs here any more. Most of them get a "internal ticket created" and never get fixed.

Thanks and hope you understand. You can close this one!

**Comment by inelukipg** [comment]
Hi,
Anyone know which file to hard code to fix this?

**Comment by lano-vargas** [comment]
@davidalger adding this: 
return 301 https://$host$request_uri; 
 bellow the server_name like you have, gives me too many redirects error

Do you know what could be going wrong?Thanks.
