### ISSUE TITLE
PayPal Payflow iframe not showing up on second try

### ISSUE THREAD

**Issue by epson121** [magento/magento2#10110]
### Preconditions

1. Magento CE 2.1.5 (probably 2.1.7 as well), Linux, nginx, Varnish, PHP 7.0, MySQL 5.6
2. Paypal Payflow pro payment method is enabled (with iframe)

### Steps to reproduce
1. Customer adds a product to cart, and goes to checkout
2. On second step, customer selects Payflow Pro method
3. iframe is displayed, and customer enters **wrong** data
4. iframe is removed, and message is displayed asking to try again
5. customer selects the same payment method again

### Expected result
Iframe should be displayed

### Actual result
Iframe is not displayed

#### Overview of the issue:
Second time the iframe is to be displayed,` vendor/magento/module-paypal/view/frontend/web/js/view/payment/method-renderer/iframe-methods.js` `afterPlaceOrder` method is triggerred, and the following code executed:

```
if (this.iframeIsLoaded) {
        document.getElementById(this.getCode() + '-iframe')
        	     .contentWindow.location.reload();
}
```

However, this fails because the source of the iframe is no longer on the stores domain - it is on paypal - and we have a cross-domain request which is blocked.

#### Workaround:

change the code above to the following:

```
 if (this.iframeIsLoaded) {
    var iframe = document.getElementById(this.getCode() + '-iframe');
    iframe.src = this.getActionUrl();
}
```

**Comment by Stas94** [comment]
@epson121 If this issue is actual for Enterprise Edition only, please address it to Magento Support.

**Comment by epson121** [comment]
@Stas94 it was experienced in CE. I've updated the ticket.

**Comment by veloraven** [comment]
@epson121 thank you for your update.
Unfortunately I was not able to reproduce this issue.
Could you please provide screenshots and additional information of **wrong** data? What type of wrong data did you use? 
Please also confirm that the issue reproduces on ver. 2.1.7.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
