### ISSUE TITLE
how to add a new customizable product option?

### ISSUE THREAD

**Issue by steros** [magento/magento2#10118]
In Magento 2.1.x ... 2.2.x how are we meant to add a new customizable product option?
Looking at the code I'm not sure there is a clean way just yet.
Here is what I have tried:
https://magento.stackexchange.com/q/181639/42007

It would be nice to have documentation about this, but I couldn't find anything. Is there?

**Comment by misha-kotov** [comment]
The GitHub issue tracker is intended for reporting technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) sites for technical questions. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by steros** [comment]
@misha-kotov ah okay, I've seen issues marked as "question" and other labels alike. I thought if there is no clean way to add an option it is an issue for real. Cause there should be a way.

**Comment by Ctucker9233** [comment]
@steros There is a way. Under configurations in the edit product page, click the button that says "Create Configurations". If you already have configurations that you just want to add, Magento doesn't show the link to do so until you create a dummy configuration. That in itself should be considered a bug but no one seems to want to fix it.

**Comment by steros** [comment]
@Ctucker9233 Thanks for your comment but I don't think this is what I'm talking about.
