### ISSUE TITLE
Search on Frontend not match with backend

### ISSUE THREAD

**Issue by dulv** [magento/magento2#10115]
Hi Team,
I have a problem
I try search a word in backend and compare with frontend but result is diffirent, on frontend only one result
See frontend: http://prntscr.com/fq9i1t
See backend: http://prntscr.com/fq9ibz
Please help me

Thanks

**Comment by veloraven** [comment]
@dulv thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
