### ISSUE TITLE
Unable to show multiple blocks with diffrent .phtml

### ISSUE THREAD

**Issue by AgenturSchroeder** [magento/magento2#10129]
### Preconditions
1. Magento 2.1.7

### Steps to reproduce
**Create two Catalog Product list widgets with different templates**
1. Go to Content->Blocks
2. Create a new block
3. Insert a widget with **Catalog Product list**
4. Select a template
5. Select in Conditions a category
6. Insert widget

**Do this twice for two widgets with different templates.**

7. Insert in the **catalog_category_view.xml** 
```
    <block class="Magento\Cms\Block\Block" name="Block_name">
    <arguments>
        <argument name="block_id"  xsi:type="string">Block_id</argument>
    </arguments>
    </block>    
```
(and change it to your own name/id)

### Expected result

1. Show 2 category lists with different templates on a category page

### Actual result

1. The category list is shown with the same template
2. the second widget with the other template looks like the first widget.

### It works if I do this
If I add **two blocks** with **one "category product list widget"** and I change the code in the xml to:
```
    <block class="Magento\Cms\Block\Block" name="Block_name1">
    <arguments>
        <argument name="block_id"  xsi:type="string">Block_id1</argument>
    </arguments>
    </block>    
    <block class="Magento\Cms\Block\Block" name="Block_name2">
    <arguments>
        <argument name="block_id"  xsi:type="string">Block_id2</argument>
    </arguments>
    </block>
```

it works and the template from each block is on the category page.

**Comment by Stas94** [comment]
@Hopfrosch We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by AgenturSchroeder** [comment]
Hi, Im sorry but now i got it to work.
I can't reproduce it all time and I noticed it is a cache problem with my local xampp installation. (I didn't said that, I'm sorry).

But if you still want this information:
Windows Version:  Pro  64-bit
XAMPP Version: 7.0.15
php 7

I think we can close this report beause it's more like a virtual machine problem than a magento 2 bug.
I'm sorry for the trouble!

**Comment by veloraven** [comment]
@Hopfrosch thank you for your update.
I'm closing this issue then.
If you can still reproduce this issue, please create a new GitHub issue report.
But please note that Magento does not support the operating system you've listed. Un case of new issue creation please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).
