### ISSUE TITLE
Invoice entity_model in table eav_entity_type

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#10123]
### Preconditions

1. Magento CE 2.1.7 with sample data, CE 2.1.6 or CE 2.1.7 without sample data

### Steps to reproduce

1. Install Magento 2 from archive
2. In table `eav_entity_type` for `entity_type_code` = "invoice" the 'entity_model' is `Magento\Sales\Model\ResourceModel\Order`

### Expected result

1. Shouldn't it be `Magento\Sales\Model\ResourceModel\Order\Invoice` (with \Invoice at the end). I see shipment and creditmemo entity_model classes have at the end \Creditmemo and \Shipment

### Actual result

1. 'entity_model' is `Magento\Sales\Model\ResourceModel\Order`

**Comment by OleksandrBurianyk** [comment]
Hi, thanks for reporting this issue. We created internal issue MAGETWO-70479 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@daniel-ifrim, thank you for your report.
We've created internal ticket(s) MAGETWO-70479 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @daniel-ifrim 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.
