### ISSUE TITLE
Product Status Not Updating in Product Grid and FrontEnd

### ISSUE THREAD

**Issue by elsandkls** [magento/magento2#10120]
This is a brand new install Magento 2.1.6. 
On the GoDaddy CPanel Linux shared server.

I created the first product. And set it to enabled during the inital creation.
http://shop.craftedbylittledragons.net/catalog/product/view/id/1/s/set-of-5-handmade-glass-swizzle-sticks-mix/category/3/

When I copied the product and then edited it, the product database is updated, but the product grid is not. 
The status does not update. 
The thumbnail does not update. 
The title/name does not update.
The price, and quantity both update correctly. 
If you pull up the individual products all of the fields are updated, only in the admin grid and the front end are not updated.  

This is also an issue for new items created, and then edited, these three fields do not update in the adming product grid. And the front end does not display the products if they were set to "Disabled" initially on creation (new or copy).  

![screenshot from 2017-07-01 15-31-39](https://user-images.githubusercontent.com/6315828/27765882-821916c0-5e8c-11e7-8854-c98fd875d3c5.png)
![screenshot from 2017-07-01 15-33-06](https://user-images.githubusercontent.com/6315828/27765884-85a6a96a-5e8c-11e7-8b9d-173083cc1387.png)

cPanel Shared Hosting
Component 	Version (Subversion)
Apache 	2.4.25
cURL 	7.36.0
MySQL 	5.6.33
PHP 	 5.6 (5.6.30)
PEAR 	1.9.4
Perl 	5.10.1
phpMyAdmin 	4.0.10.14
Python 	2.6.6
Zend 	2.6.0
 
### Expected result  
1.  Updating individual products should immediately update the product grid in the admin interface, and it should update front end as well. (for example all of my products should be visible on the front end under the category swizzle sticks)

### Actual result 
1.  There are no errors in the logs. There are no warning other than "invalidated cache" in the logs. 
2.  The products are updated.
3.  The admin grid is not updated.

I have not tested on another platform.

**Comment by veloraven** [comment]
@elsandkls thank you for your report.
Please format steps to reproduce as clear and specific actions like 'open', 'click', 'add', etc. As currently it's unclear what you mean as 'When I copied the product'. Do you mean duplicate functionality? Also there is some mess of steps and actual results at the first part of your description which is hard for understanding.

**Comment by elsandkls** [comment]
Do you have n FAQ for developers that explains how the GRID for products in the admin iterface is generated? what tables it looks at? where the modules and objects are located in the code? Give me a starting place to troubleshoot this?
