### ISSUE TITLE
USPS Priority Mail To Canada Is Not Displaying

### ISSUE THREAD

**Issue by seattletechworks** [magento/magento2#10121]
### Preconditions
1.  Magento 2.1.7, PHP 7.0.20, Nginx 1.20.2, MySQL 5.6.34-79.1
2.  Set up and enable USPS for checkout under admin panel:
Stores -> Configuration -> Sales -> Shipping Methods
Allowed Methods should include First-Class Package International Service and Priority Mail International.

### Steps to reproduce
1. Add a product to your cart which has a weight of more than 4 pounds
2. Go to the cart page - Example https://www.yourstore.com/checkout/cart/
3. In the Estimate Shipping and Tax section, enter these values:
Country - Canada
State/Provide - British Columbia
Zip/Postal Code - V8G 4R6

### Expected result
1. A live quote from USPS for Priority Mail International should be returned

Correct rates are displayed for other countries.  For example, specify these values to get a positive result:
Country - Australia
State/Provide - NSW
Zip/Postal Code - 2000

Additionally, if the product weight is 4 pounds or less, the correct First-Class International service quote is displayed for Canada. The issue only occurs with Priority Mail International quotes.

### Actual result
1. A message in the Summary box displays: "Sorry, no quotes are available for this order at this time"

Error from ~/var/log/debug.log file:

The Origin ZIP Code and the Destination Postal Code is required for ECOMPRO when mailing to Canada.

### Other comments
I found a similar defect from March - https://github.com/magento/magento2/pull/8041
![usps_priority_canada_issue](https://user-images.githubusercontent.com/29831856/27768260-92a8e984-5ec3-11e7-9d68-703cf4f3c25c.jpg)

**Comment by veloraven** [comment]
@seattletechworks thank you for your report.
We already have a fix in develop branch, you can find it in commit 69a0f5cea8c7297d4011493a188dd18df60ab8ac from the PR #8041

**Comment by korostii** [comment]
Hi @veloraven, I see that you've added a `needs update` label.
Would you please care to explain what kind of information you need from community in order to proceed with backporting an existing fix to the 2.1.x branch?

**Comment by orlangur** [comment]
Closing as the fix for this issue is already available on Magento 2.2.0 branch.
