### ISSUE TITLE
Flash messages are not displayed due to multiple mage-messages cookie.

### ISSUE THREAD

**Issue by rakesh-gangani** [magento/magento2#10127]
Flash messages are not displayed due to multiple mage-messages cookie.
### Preconditions

1. Magento 2.1.7, PHP 5.6, Developer mode, Ubuntu

### Steps to reproduce

1. Setup 2 store view.

### Expected result

1. Flash Message show be shown when user performs some action like Add to cart, incorrect login, delete item form cart.

### Actual result

1. None of the messages are show when performing action like add to cart, incorrect login .. etc
2. Found Multiple mage-message cookie.
![magento-message](https://user-images.githubusercontent.com/10204501/27792456-5713ef82-5fe9-11e7-842b-b1e78f1f3aa5.png)

After comparing it with older version I found that there are changes in messages.js(vendor/magento/module-theme/view/frontend/web/js/view/messages.js) file. 

`.setConf({path: '/', expires: -1})`

Is deleted from new code.

**Comment by veloraven** [comment]
@rsquarem thank you for your report.
Please write down more detailed steps in format like:

**Steps:**
1. ...
2. ....
3. ....

And clear expected result.

As now it's hard to understand what exact actions should be done to get the result. And who should do this actions.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
