### ISSUE TITLE
requirejs-config.js in pub/static not added when pub/static gets cleared (manually)

### ISSUE THREAD

**Issue by quisse** [magento/magento2#10137]
When clearing the contents of the `pub/static` directory (except .htaccess offcourse), `pub/static/_requirejs/frontend/MyName/my-theme/en_US/requirejs-config.js` is missing

### Preconditions
1. Magento 2.1.7
2. PHP 7.0.19
3. MySQL 5.7.16

### Steps to reproduce
1. Remove all content from `pub/static` directory except for .htaccess
2. Refresh a page of your magento site.

### Expected result
1. `pub/static/_requirejs/frontend/MyName/my-theme/en_US/requirejs-config.js` gets loaded

### Actual result
1. `pub/static/_requirejs/frontend/MyName/my-theme/en_US/requirejs-config.js` is missing
2. run `bin/magento cache:clean`
3. Refresh a page of your magento site.
4. `pub/static/_requirejs/frontend/MyName/my-theme/en_US/requirejs-config.js` is back

**Comment by 1408sheva** [comment]
@quisse Please tell me which application mod is yours? You can see it using the command: php bin/magento deploy:mode:show

**Comment by quisse** [comment]
@1408sheva It is developer, all other files get symlinked.

**Comment by 1408sheva** [comment]
@quisse I cannot reproduce this issue. 
Try to go to the login tab, and it should all appear.
Or try to on fresh Magneto installation.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
