### ISSUE TITLE
Support addition of sibling category

### ISSUE THREAD

**Issue by shanavas786** [magento/magento2#10136]
Magento supports addition of root category and subcategory. It would be nice to add sibling category addition too.

**Comment by magento-engcom-team** [comment]
@shanavas786 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.
Feel free to submit pull request for this issue 👍
