### ISSUE TITLE
Installation error | Module 'Magento_Tax'

### ISSUE THREAD

**Issue by azotez** [magento/magento2#10138]
Magento installation stops at 94%:

![screencapture-localhost-magento2-setup-1499166164346](https://user-images.githubusercontent.com/7289147/27827760-2b58bc30-60b9-11e7-8218-4c9b46710dcc.png)

Here you are the complete log:

-

Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Backend':

Module 'Magento_Theme':

Module 'Magento_Config':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':

Module 'Magento_Security':

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':

Module 'Magento_Rule':

Module 'Magento_Catalog':

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Payment':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_User':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':

Module 'Magento_Integration':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_CatalogInventory':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Analytics':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_CheckoutAgreements':

Module 'Magento_QuoteAnalytics':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_Paypal':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_GoogleAdwords':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_GiftMessage':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SampleData':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':

Module 'Magento_WishlistAnalytics':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Backend':

Module 'Magento_Theme':

Module 'Magento_Config':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_Security':

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':

Module 'Magento_Rule':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_Widget':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Payment':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_User':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_Analytics':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_ProductVideo':

Module 'Magento_CheckoutAgreements':

Module 'Magento_QuoteAnalytics':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_Paypal':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_GoogleAdwords':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_GiftMessage':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SampleData':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':
Running schema recurring...

Module 'Magento_WishlistAnalytics':

Installing user configuration...

Enabling caches:
Current status:
Array ( [config] => 1 [layout] => 1 [block_html] => 1 [collections] => 1 [reflection] => 1 [db_ddl] => 1 [eav] => 1 [customer_notification] => 1 [config_integration] => 1 [config_integration_api] => 1 [full_page] => 1 [translate] => 1 [config_webservice] => 1 ) 

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Backend':

Module 'Magento_Theme':

Module 'Magento_Config':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':

Module 'Magento_Security':

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':

Module 'Magento_Rule':

Module 'Magento_Catalog':

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Payment':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_User':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':

Module 'Magento_Integration':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_CatalogInventory':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Analytics':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_CheckoutAgreements':

Module 'Magento_QuoteAnalytics':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_Paypal':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_GoogleAdwords':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_GiftMessage':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SampleData':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':

Module 'Magento_WishlistAnalytics':

Data post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Backend':

Module 'Magento_Theme':
Running data recurring...

Module 'Magento_Config':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':
Running data recurring...

Module 'Magento_Security':

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':

Module 'Magento_Rule':

Module 'Magento_Catalog':

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Payment':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_User':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':

Module 'Magento_Integration':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_CatalogInventory':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Analytics':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_CheckoutAgreements':

Module 'Magento_QuoteAnalytics':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Authorizenet':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_Paypal':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_GoogleAdwords':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':
Running data recurring...
[ERROR] Magento\Framework\Exception\InputException: percentage_rate is a required field. in C:\xampp\htdocs\magento2\app\code\Magento\Tax\Model\Calculation\RateRepository.php:229 Stack trace: #0 C:\xampp\htdocs\magento2\app\code\Magento\Tax\Model\Calculation\RateRepository.php(114): Magento\Tax\Model\Calculation\RateRepository->validate(Object(Magento\Tax\Model\Calculation\Rate)) #1 C:\xampp\htdocs\magento2\app\code\Magento\Tax\Setup\RecurringData.php(70): Magento\Tax\Model\Calculation\RateRepository->save(Object(Magento\Tax\Model\Calculation\Rate)) #2 C:\xampp\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(895): Magento\Tax\Setup\RecurringData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #3 C:\xampp\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(791): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #4 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #5 C:\xampp\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(342): call_user_func_array(Array, Array) #6 C:\xampp\htdocs\magento2\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #7 C:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #9 C:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #10 C:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #11 C:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #12 C:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #14 C:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #15 C:\xampp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #16 C:\xampp\htdocs\magento2\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #17 C:\xampp\htdocs\magento2\setup\index.php(35): Zend\Mvc\Application->run() #18 {main}

-

Could someone please help?
Thanks a lot,
Davide

**Comment by veloraven** [comment]
@azotez thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by ebanolopes** [comment]
Hi, @azotez, I got the same issue on my local installation of Magento 2.2.0-dev on MAMP using PHP 7.1.1. I didn't dig this too deep, but as a workaround I've modified app/code/Magento/Tax/Setup/RecurringData.php adding the code bellow after line 69:

`if (empty($taxRateData->getData('percentage_rate'))) continue;`

After installation I've removed the code.

**Comment by avoelkl** [comment]
same here, received the same error today. the temporary resolution as @ebanolopes suggested works.

**Comment by a1tem** [comment]
Agree, I've got the same error on my dev machine.

**Comment by joshuaswarren** [comment]
@veloraven - we'll get some more steps here on how to reproduce, but one thing that the original issue report by azotez didn't make clear I think is that this is on the Magento 2.2 release candidate. It's definitely an issue in the release candidate, and needs some attention because it's slowing many developers from being able to test the 2.2 release candidate and provide feedback.

Thanks!

**Comment by misha-kotov** [comment]
@azotez @avoelkl  @ebanolopes @a1tem 
Can you guys please provide some information about your environments so we can have someone try to reproduce and fix the issue? Seems like only a subset of our users are running into this and I want to make sure we get this taken care of. Thank you!

**Comment by ebanolopes** [comment]
Hi, I'm using MAMP 4, Apache, PHP 7.0.15 on macOS Sierra. But to me it don't look like it is a environment problem. Can I provide any other information that can be useful?

**Comment by avoelkl** [comment]
Tried it as a developer install (git clone of this repo) on the following system:

* Debian GNU/Linux 8 (jessie)
*  PHP Version:
PHP 7.0.21 (cli) (built: Jul 11 2017 15:53:41) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by azotez** [comment]
I tried on Windows 7 64bit with a MAMP installation..
Could it be a composer related problem?
I had to use the zio download for my tests..
Have all a nice day!!

**Comment by misha-kotov** [comment]
Thanks guys, we will see if we can reproduce this. Internal issue is MAGETWO-70705.

**Comment by akiuni** [comment]
Hello, same issue here.

- CentOS
- Linux release 7.3.1611 (Core)
- PHP 7.1.7 (fpm-fcgi) (built: Jul 13 2017 16:38:15)
- Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

Installation settings : 
- Timezone : GTM(UTC)
- Language : French
- Currency : Euro

@ebanolopes suggestion worked fine for me too

**Comment by avoelkl** [comment]
Installation settings :
Installation settings could be interesting as well, thanks for the heads up @akiuni 
Mine were:
Timezone : Central European Time (Vienna)
Language : German (Germany) or English (tried it 2 times)
Currency : Euro

**Comment by magento-engcom-team** [comment]
@azotez, thank you for your report.
The issue is already fixed in 2.2.0
