### ISSUE TITLE
Magento 2.2 EE RC1 - Installation Fails - Class 'PhpAmqpLib\Connection\AMQPStreamConnection' not found

### ISSUE THREAD

**Issue by careys7** [magento/magento2#10134]
### Preconditions

1. Magento CE 2.2 RC1, EE 2.2 RC1, B2B RC1

### Steps to reproduce

1. Follow the instructions at [DevDocs](http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html) to install the RC
2. Run `bin/magento setup:install`

### Expected result

1. Installation successful

### Actual result

1. Exits with the following error:

```
[Progress: 220 / 845]
Module 'Magento_Amqp':
Running schema recurring...PHP Fatal error:  Uncaught Error: Class 'PhpAmqpLib\Connection\AMQPStreamConnection' not found in /var/www/html/magento2ee/lib/internal/Magento/Framework/Amqp/Config.php:183
Stack trace:
#0 /var/www/html/magento2ee/lib/internal/Magento/Framework/Amqp/Config.php(130): Magento\Framework\Amqp\Config->createUnsecureConnection()
#1 /var/www/html/magento2ee/lib/internal/Magento/Framework/Amqp/TopologyInstaller.php(86): Magento\Framework\Amqp\Config->getChannel()
#2 /var/www/html/magento2ee/app/code/Magento/Amqp/Setup/Recurring.php(36): Magento\Framework\Amqp\TopologyInstaller->install()
#3 /var/www/html/magento2ce/setup/src/Magento/Setup/Model/Installer.php(895): Magento\Amqp\Setup\Recurring->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#4 /var/www/html/magento2ce/setup/src/Magento/Setup/Model/Installer.php(775): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#5 [internal function]: Magento\Setup\Model\Installer->installSchema()
#6 /var/www/ht in /var/www/html/magento2ee/lib/internal/Magento/Framework/Amqp/Config.php on line 183
```

It looks like this is because the instructions provided (or dev/tools/build-ee.php) do not update the composer.json in use to include the Enterprise-specific dependencies.

Running the following looks like a suitable workaround:

```bash
cp /path/to/ee/composer.json /path/to/ce/composer.json
cp /path/to/ee/composer.lock /path/to/ce/composer.lock
```

**Comment by YevSent** [comment]
The public Github is only for CE version of Magento. To solve your problem, please, create a ticket via [EE support](https://account.magento.com/customer/account/login/), thanks, for your reporting.

**Comment by careys7** [comment]
@joni-jones you might want to update [Submit Comments on the Release Candidate](http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/submit-issues.html):

> Your input is critical to the success of all editions of Magento 2.2.0! All feedback should be submitted [here](https://github.com/magento/magento2/issues).

**Comment by YevSent** [comment]
@careys7, you are right.

**Comment by misha-kotov** [comment]
Thanks @careys7 for reporting this issue. We've updated the instructions on the [devdocs page](http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html#update-installation-dependencies). Closing issue.

**Comment by careys7** [comment]
Thanks @misha-kotov
