### ISSUE TITLE
NO toolbar(add widget , add table, chage font etc...) when i go to admin panel content->page->edit->content 

### ISSUE THREAD

**Issue by IvanKirchev** [magento/magento2#10139]
I installed Magento2.1.7 with all re requirements PHP7 with all extension (changed memory_limit) apache with mod_rewrite mysql 5.7
PROBLEM:  I installed  and deleted Magento2.1.7 because of various problems, however
now when i want to change the content of the home page i go to page->edit->content and i want to add 
a widget for example and the toolbar i used to see above is gone all i see is a simple textarea 

![screenshot 2017-07-04 14 22 02](https://user-images.githubusercontent.com/19436069/27828319-4f62b602-60c4-11e7-8228-94fdb177df4a.png)

**Comment by southerncomputer** [comment]
yeah you have to reload to see the tiny_mce editor!

**Comment by veloraven** [comment]
@IvanKirchev thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
