### ISSUE TITLE
Postcode max length not working in My Account pages.

### ISSUE THREAD

**Issue by teuma86** [magento/magento2#10147]
Adding a max-length to the postcode attribute is being ignored when adding a new address in my account section but works within the checkout section for adding a new address.

Magento Version: 2.1.7

### Steps to reproduce
1. within the admin panel, go to Stores -> Customer Address 
2. Edit Postcode
3. Set Input Validation to AlphaNumeric and set Max Length to 10 and min Length to 0
4. Within the front end, log in and go to my account section
5. You can enter a postcode of any length, however, validation for the type is working.

### Expected result
1. You should not be able to enter more than 10 characters in the postcode. 

### Actual result
You can enter a postcode of any length, however still matching the Alphanumeric rule type.

**Comment by AlexWorking** [comment]
Hello, @teuma86. It is only in Magento Enterprise Edition that Admin panel has Customer Address and the other options You have described, unless You have installed some external extensions. If You have Magento Community Edition and You use some extensions that makes it possible to work with Customer Attributes, please specify them. In case You use the Enterprise Edition please address it to Magento Support. Anyway, Thank You for applying.

**Comment by teuma86** [comment]
Hi

I have raised a bug with Magento Support.

Thank you

Jamie

**Comment by veloraven** [comment]
@teuma86 thank you for update.
I'm closing this issue.
