### ISSUE TITLE
`php index.php update` - Class Magento\Store\Model\StoreManagerInterface does not exist

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1014]
Module 'Magento_Webapi':
Module 'Magento_Weee':
Module 'Magento_CurrencySymbol':
Module 'Magento_Wishlist':
======================================================================
   The application has thrown an exception!
======================================================================
 Magento\Framework\Exception
 Error in file: "/srv/www/magento2.dev/pub/app/code/Magento/Theme/data/theme_setup/data-install-2.0.0.php" - Class Magento\Store\Model\StoreManagerInterface does not exist
----------------------------------------------------------------------
/srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/DataSetup.php:232
#0 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/DataSetup.php(132): Magento\Framework\Module\DataSetup->_modifyResourceDb('data-install', '', '2.0.1')
#1 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/DataSetup.php(119): Magento\Framework\Module\DataSetup->_installData('2.0.1')
#2 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/Updater.php(60): Magento\Framework\Module\DataSetup->applyDataUpdates()
#3 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Model/Installer.php(586): Magento\Framework\Module\Updater->updateData()
#4 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Controller/ConsoleController.php(362): Magento\Setup\Model\Installer->installDataFixtures()
#5 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\ConsoleController->updateAction()
#6 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Controller/ConsoleController.php(302): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 [internal function]: Magento\Setup\Controller\ConsoleController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /srv/www/magento2.dev/pub/setup/index.php(25): Zend\Mvc\Application->run()
#17 {main}
======================================================================
   Previous Exception(s):
======================================================================
 ReflectionException
 Class Magento\Store\Model\StoreManagerInterface does not exist
----------------------------------------------------------------------
/srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:37
#0 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/DataSetup.php(132): Magento\Framework\Module\DataSetup->_modifyResourceDb('data-install', '', '2.0.1')
#1 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/DataSetup.php(119): Magento\Framework\Module\DataSetup->_installData('2.0.1')
#2 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/Updater.php(60): Magento\Framework\Module\DataSetup->applyDataUpdates()
#3 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Model/Installer.php(586): Magento\Framework\Module\Updater->updateData()
#4 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Controller/ConsoleController.php(362): Magento\Setup\Model\Installer->installDataFixtures()
#5 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\ConsoleController->updateAction()
#6 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Controller/ConsoleController.php(302): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 [internal function]: Magento\Setup\Controller\ConsoleController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /srv/www/magento2.dev/pub/setup/index.php(25): Zend\Mvc\Application->run()
#17 {main}
======================================================================
 ReflectionException
 Class Magento\Store\Model\StoreManagerInterface does not exist
----------------------------------------------------------------------
/srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29
#0 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/DataSetup.php(132): Magento\Framework\Module\DataSetup->_modifyResourceDb('data-install', '', '2.0.1')
#1 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/DataSetup.php(119): Magento\Framework\Module\DataSetup->_installData('2.0.1')
#2 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/Updater.php(60): Magento\Framework\Module\DataSetup->applyDataUpdates()
#3 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Model/Installer.php(586): Magento\Framework\Module\Updater->updateData()
#4 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Controller/ConsoleController.php(362): Magento\Setup\Model\Installer->installDataFixtures()
#5 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\ConsoleController->updateAction()
#6 /srv/www/magento2.dev/pub/setup/module/Magento/Setup/src/Controller/ConsoleController.php(302): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 [internal function]: Magento\Setup\Controller\ConsoleController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /srv/www/magento2.dev/pub/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /srv/www/magento2.dev/pub/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /srv/www/magento2.dev/pub/setup/index.php(25): Zend\Mvc\Application->run()
#17 {main}

**Comment by otoolec** [comment]
@Mackovey can you try clearing out your var/generation directory?  That fixed the problem for me.  I think there is an old generated file that is using an outdated class reference.  We can use this ticket to see about getting the setup script to clear that directory for you.

**Comment by otoolec** [comment]
Internal ticket is MAGETWO-33519

**Comment by snohe** [comment]
@Mackovey, this is now resolved in 0.74.0-beta1.  Thank you again for submitting this issue.  Should you have any additional questions, please don't hesitate to let us know.
