### ISSUE TITLE
Magento 2 grand total not including shipping until reload

### ISSUE THREAD

**Issue by haydencarlson** [magento/magento2#10144]
### Preconditions

Magento 2.0, PHP 7.0.20-2, MySQL 5.7.18
Running Ubuntu

### Steps to reproduce

```

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
	$grandTotal = $cart->getQuote()->getGrandTotal();
```

This is in my ConfigProvider.
I console.log checkoutConfig.payment.[my_gateway]

On the first load of the checkout when I get the grand total it does not include shipping cost.
If I reload page or click go to checkout again I get the correct amount.

The totals are properly shown on the checkout page just not through the method renderer.

### Expected result

Correct Grand total.

**Comment by haydencarlson** [comment]
Has anyone else had this issue?

**Comment by haydencarlson** [comment]
BMUP

**Comment by minesh0111** [comment]
@haydencarlson yes grand total does not include shipping amount. checked in version 2.1.5

**Comment by haydencarlson** [comment]
But it only does it on first load. If I reload the checkout it gets the right price

**Comment by haydencarlson** [comment]
Is this a bug in CE 2.1.5

**Comment by haydencarlson** [comment]
Bump...

**Comment by magento-engcom-team** [comment]
Hi @haydencarlson 
`\Magento\Quote\Api\CartTotalRepositoryInterface` is supposed to be used to obtain totals.

**Comment by kashukov** [comment]
Can be solved by cache cleaning.
At least it works locally.

```php
$objectManager = ObjectManager::getInstance();
$cacheFrontendPool = $objectManager->create('Magento\Framework\App\Cache\Frontend\Pool');
foreach ($cacheFrontendPool as $cacheFrontend) {
    $cacheFrontend->getBackend()->clean();
}
```
