### ISSUE TITLE
forbidden pub/media/catalog/category

### ISSUE THREAD

**Issue by tomnyson** [magento/magento2#10145]
### Preconditions

1. php-fpm 7.0, mysql 5.7, nginx
2. magento 2.1.7

### Steps to reproduce

1. php bin/magento catalog:images:resize
2. open web browser 
3. tail -f /var/log/nginx/error.log

### Expected result

 1408#1408: *14443 directory index of "/home/vmax/pub                                                                                   lic_html/vmaxprj/current/pub/media/catalog/category/" is forbidden, client: 127.                                                                                   0.0.1, server: v1.vmax.vn, request: "GET /media/catalog/category/ HTTP/1.0", hos                                                                                   t: "v1.vmax.vn"

1. 

### Actual result

show many message in file log error of nginx.
forbidden access /media/catalog/category/
1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/10257765/27852779-af677c7e-618a-11e7-880b-20979bbf41e4.png)

**Comment by joe-vortex** [comment]
You should probably chmod those folders. See the M2 docs:
http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_file-sys-perms.html
Either that or chown to your server's web user i.e. `www-data`

**Comment by tomnyson** [comment]
I did chmod and chown for www-data , but it still shows error

**Comment by Shade634** [comment]
Depends:
step1, can have different settings and users for cli and web...

**Comment by magento-engcom-team** [comment]
@tomnyson, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
