### ISSUE TITLE
Developer ACL incorrect

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#10148]
### Preconditions
1.  Magento 2.x (bug still exists in Magento 2-dev)

### Steps to reproduce
1. Create a new role in the backend
2. Give the role access to the resource 'Developer Section'
3. Create a new account
4. Give the account the new role
5. Login with the new account and go to Stores -> Configuration -> Advanced -> Developer

### Expected result
1. User should be able to go to 'Developer Section'

### Actual result
1. User cannot go to 'Developer Section' and menu is not visible

**Comment by PascalBrouwers** [comment]
Made a PR to fix it :)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70466

**Comment by magento-engcom-team** [comment]
@PascalBrouwers, thank you for your report.
The issue is already fixed in 2.2.0
