### ISSUE TITLE
Ufter success setup/index.php update - "Missing required argument $engines of Magento\Framework\View\TemplateEngineFactory"

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1015]
a:4:{i:0;s:83:"Missing required argument $engines of Magento\Framework\View\TemplateEngineFactory.";i:1;s:10175:"#0 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#1 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(69): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#2 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#3 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'factory', 'Magento\\Framewo...')
#4 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#5 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(69): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#6 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#7 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'enginePool', 'Magento\\Framewo...')
#8 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#9 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(69): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#10 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#11 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'context', 'Magento\\Framewo...')
#12 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#13 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#14 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/View/Result/PageFactory.php(53): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#15 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/App/View.php(74): Magento\Framework\View\Result\PageFactory->create(true)
#16 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(107): Magento\Framework\App\View->__construct(Object(Magento\Framework\View\Layout\Interceptor), Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\App\Response\Http), Object(Magento\Framework\Config\Scope), Object(Magento\Framework\Event\Manager\Proxy), Object(Magento\Framework\View\Result\PageFactory), Object(Magento\Framework\App\ActionFlag))
#17 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#18 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(69): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#19 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#20 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'view', 'Magento\\Framewo...')
#21 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#22 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#23 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/App/ActionFactory.php(38): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#24 /srv/www/magento2.dev/pub/app/code/Magento/Core/App/Router/Base.php(302): Magento\Framework\App\ActionFactory->create('Magento\\Cms\\Con...', Array)
#25 /srv/www/magento2.dev/pub/app/code/Magento/Core/App/Router/Base.php(162): Magento\Core\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)
#26 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/App/FrontController.php(41): Magento\Core\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#27 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /srv/www/magento2.dev/pub/var/generation/Magento/Framework/App/FrontController/Interceptor.php(48): call_user_func_array(Array, Array)
#29 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Interception/Chain/Chain.php(65): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#30 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Interception/Chain/Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#31 /srv/www/magento2.dev/pub/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(88): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#34 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Interception/Chain/Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#35 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(66): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#38 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Interception/Chain/Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#39 /srv/www/magento2.dev/pub/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#40 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#42 /srv/www/magento2.dev/pub/var/generation/Magento/Framework/App/FrontController/Interceptor.php(90): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#43 /srv/www/magento2.dev/pub/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}(Object(Magento\Framework\App\Request\Http))
#44 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /srv/www/magento2.dev/pub/var/generation/Magento/Framework/App/FrontController/Interceptor.php(95): call_user_func_array(Array, Array)
#46 /srv/www/magento2.dev/pub/var/generation/Magento/Framework/App/FrontController/Interceptor.php(119): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#47 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /srv/www/magento2.dev/pub/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\Http->launch()
#49 /srv/www/magento2.dev/pub/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#50 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}

**Comment by Mackovey** [comment]
Problem was in etc/config.php

diff config.php config.php.exception
<     'config' => 1,
<     'layout' => 1,
<     'block_html' => 1,
<     'view_files_fallback' => 1,
<     'view_files_preprocessing' => 1,
<     'collections' => 1,
<     'db_ddl' => 1,
<     'eav' => 1,
<     'full_page' => 1,
<     'translate' => 1,
<     'config_integration' => 1,
<     'config_webservice' => 1,
<     'config_integration_api' => 1,
---
>     'config' => 0,
>     'layout' => 0,
>     'block_html' => 0,
>     'view_files_fallback' => 0,
>     'view_files_preprocessing' => 0,
>     'collections' => 0,
>     'db_ddl' => 0,
>     'eav' => 0,
>     'full_page' => 0,
>     'translate' => 0,
>     'config_integration' => 0,
>     'config_webservice' => 0,
>     'config_integration_api' => 0,

**Comment by wojtekn** [comment]
I also spotted that issue and I fixed that by removing config.php and running installation again. 

It looks two modules have been added in config.php: Magento_Developer and Magento_Quote and order of a few others has changed.

Is there any other recommended way to update config.php after pulling new code? Or should Magento 2 be reinstalled each time during dev beta?

**Comment by alankent** [comment]
This is a known issue. A tool to update config.php is on the backlog (but not done yet). We need to make it easier to add and remove modules without losing any other config details, but getting the load order of the new modules correct (you cannot just add at the end of the array). Until then, updating config.php by hand is the best solution. Adding new modules at the end will generally work safely (but not always). Redoing the full install process is safer, but normally is not required.

**Comment by mazhalai** [comment]
@Mackovey @wojtekn Thank you for reporting this issue. We have created MAGETWO-33555 to track this issue internally.

**Comment by snohe** [comment]
@Mackovey @wojtekn, this is now resolved in 0.74.0-beta1.  Thank you again for submitting this issue.  Should you encounter any other issues, feel free to reach out to us.  Thank you for using Magento!
