### ISSUE TITLE
bin/magento catalog:images:resize - Often reported - never fixed!

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#10152]
If you search for the resize command here at GitHub or over the web - you find hundreds of reports.

It was so often reported and never fixed by the magento 2 team. It runs forever, has no option and includes magento native and luma theme.

I am not shure why reporting bugs makes any sense here any more. 
You find over 1 year old bugs (like the email logo bug) here which are simple to solve in about minutes for the developers but magento just ignores these.

**Comment by andidhouse** [comment]
We just decided as a company to not report any more tickets - so this one can be closed as well pls.

We did report too often and not one bug we reported was fixed (some are reported long over one year ago).

We cannot see any benefit of reporting bugs here any more. Most of them get a "internal ticket created" and never get fixed (the last magento 2.1.7 update included exactly .... 0! - just a credit card and security update if i can remember).

Thanks and hope you understand. You can close this one as well!

**Comment by rgoncharuk** [comment]
Thank you for the feedback.
As you can see in the guide we recommend to find the same reported issue instead of creation a new one. 
Issues voted by a lot of people show us defects that we process first.

You may search, create relation among issues, join a group of other community members  and vote for an issue impacted your group.

Feel free to build collaboration among community.

Regards.

**Comment by andidhouse** [comment]
hi @rgoncharuk - thanks for the reply. 

"Issues voted by a lot of people show us defects that we process first."

I do not see this at all - but this is our personal view as an agency reporting bugs here for over one year. Also bugs which are reported 10 times here or more often are not fixed in any new release. 

As i said we have lost interest in helping to improve magento at the moment. It is very annoying if bugs exist. It is more annoying if these bugs are reported and confirmed by magento but nothing changes. 

I realy do not get it - hundreds of internal tickets and you release a new magento version with 0! bugs fixed.

For us we will stop now and wait how this develops.

Thanks and regards

**Comment by veloraven** [comment]
I'm closing this issue as GitHub issue tracker is intended for technical issues only.
