### ISSUE TITLE
Currency rate applying twice for configurable products

### ISSUE THREAD

**Issue by sergiynezbritskiy** [magento/magento2#10150]
# Description
When I set up multiple currencies and go to product page, then switching from default currency will cause applying currency rate twice (for configurable products only)

# Preconditions
- Create configurable product with two configurations with prices NOK 10 000 and NOK 5 000 respectively.

# Steps to reproduce
- Go to frontend product page, I see price 5 000 NOK, but when switch currency to EUR, i see price 50 EUR.
- Setup multiple curencies: NOK (default, base currency), EUR.
- Configured currency rate  1 NOK = 0.1000 EUR
- Go to created product page on frontend
- Change store currency from NOK to EUR
# Expected result
Price should be displayed 500.00 EUR
# Actual result
Product price displayed 50.00 EUR
# Additional information
I even can see some price blinking when page is loading from 500.00 to 50.00, you can see it on the video below https://www.screencast.com/t/IqRI8tMkYJi
So price for configurations is calculating correctly, and seems like it is calculating twice for configurable product price.
The same issues with other currencies.
Tested on Magento versions: 2.1.6 and 2.1.7 (2.1.6 - fresh vesion of Magento with default theme Luma)
OS: Ubuntu Ubuntu 14.04.5 LTS and Windows 10 x64
PHP 5.6.30
Apache 2.4

**Comment by veloraven** [comment]
@sergeynezbritskiy thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by sergiynezbritskiy** [comment]
@veloraven done

**Comment by VasylShvorak** [comment]
@sergeynezbritskiy Thanks for reporting this issue. Created internal issue MAGETWO-71029 to investigate and track this issue.

**Comment by Danielc3** [comment]
Hello,

I have some more information on this issue. It seems that conversion is happening twice due to it happening in the price classes e.g. RegularPrice.php which gets cached via a class variable and it is also happening when getting the JSON config for the price box (\Magento\Catalog\Block\Product\View::getJsonConfig).

My fix for this was simply to create an after plugin for getJsonConfig and to modify the price amounts that are returned to not be converted again.

**Comment by magento-engcom-team** [comment]
@sergeynezbritskiy, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by oirad** [comment]
For everyone still waiting for the fix on magento 2.1 I made a hotfix that I am using on my side. https://github.com/oirad/magento2-fix10150

**Comment by Mahmoud-Refaat** [comment]
@oirad  Thanks
