### ISSUE TITLE
Attribute options are unexpectably modified during attribute update REST call

### ISSUE THREAD

**Issue by okovalov-commer** [magento/magento2#10157]
### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. Install magento 
2. create an admin user and obtain a token to be used for rest calls
3. create one more store view (to have two store views in total. those ids would be used in the payload as values for 'store_id'
4. create a product attribute by making a POST call to {{baseurl}}/rest/V1/products/attributes and using given json payload

```
{
  "attribute": {
    "is_wysiwyg_enabled": false,
    "is_html_allowed_on_front": false,
    "used_for_sort_by": true,
    "is_filterable": false,
    "is_filterable_in_search": false,
    "position": 0,
    "apply_to": ["simple","virtual","configurable"],
    "is_searchable": "1",
    "is_visible_in_advanced_search": "1",
    "is_comparable": "0",
    "is_used_for_promo_rules": "0",
    "is_visible_on_front": "1",
    "used_in_product_listing": "1",
    "is_visible": true,
    "scope": "store",
    "extension_attributes": {},
    "attribute_code": "web_attribute_4",
    "frontend_input": "multiselect",
    "entity_type_id": "4",
    "is_required": false,
    "is_user_defined": true,
    "default_frontend_label": "web_attribute_4_def_frontend_label",
    "frontend_labels": [
      {
        "store_id": 1,
        "label": "web_attribute_4_label_en"
      }
    ] ,    
    "options": [
        {
            "label": "label opt1",
            "value": "value_opt1",
            "is_default": true,
            "store_labels": [
          {
            "store_id": 0,
            "label": "option_1_labl_adm"
          },
          {
            "store_id": 1,
            "label": "option_1_labl_en"
          }
         ]   
        },
        {
            "label": "label opt2",
            "value": "value_opt2",
            "store_labels": [
          {
            "store_id": 0,
            "label": "option_2_labl_adm"
          },
          {
            "store_id": 1,
            "label": "option_2_labl_en"
          }
         ]   
        }        
    ],
    "note": "dummy note",
    "backend_type": "varchar",
    "default_value": "0",
    "is_unique": "0",
    "custom_attributes": [
      {
        "attribute_code": "web_attribute_4",
        "value": "web_attribute_4_value"
      }
    ]
  }
}
```

5. update an attribute using given json payload (**NOTE** replace YOUR_ID with an actual attribute_id from the previous step response )

```
{
  "attribute": {
    "attribute_id": **YOUR_ID**,
    "frontend_labels": [
      {
        "store_id": 1,
        "label": "web_attribute_4_label_en_new2"
      }
    ]    
  }
}

```

### Expected result

1. Only frontend label should be updated and **NO changes in attribute options should be made** when no **option** element is given in the payload 
![image](https://user-images.githubusercontent.com/23319907/27876321-a951d286-6184-11e7-8050-4d471b8e2a79.png)
![image](https://user-images.githubusercontent.com/23319907/27876354-c88d3622-6184-11e7-9220-86419ca08987.png)

### Actual result

1. Options have been changed - one empty option being inserted at the top of the list, two remained options lost their Admin values which are replaced with Default store view values , wheare Default store values became empty.

![image](https://user-images.githubusercontent.com/23319907/27876498-53c9d0b0-6185-11e7-9d0d-559d6cf84440.png)

![image](https://user-images.githubusercontent.com/23319907/27876542-7bd16884-6185-11e7-8404-87d6552faa94.png)

### **PLEASE NOTE**
Sending an array of options within an update payload does not help either (example of the payload below)

```
{
  "attribute": {
  	"attribute_id": **YOUR_ID**,
    "options": [
        {
            "label": "label opt1",
            "value": "value_opt1",
            "is_default": true,
            "store_labels": [
          {
            "store_id": 0,
            "label": "option_1_labl_adm"
          },
          {
            "store_id": 1,
            "label": "option_1_labl_en"
          }
         ]   
        },
        {
            "label": "label opt2",
            "value": "value_opt2",
            "store_labels": [
          {
            "store_id": 0,
            "label": "option_2_labl_adm"
          },
          {
            "store_id": 1,
            "label": "option_2_labl_en"
          }
         ]   
        }        
    ],  	
    "frontend_labels": [
      {
        "store_id": 1,
        "label": "web_attribute_4_label_en_new2"
      }
    ]    
  }
}
```
This way it causes options duplication

![image](https://user-images.githubusercontent.com/23319907/27878278-abeb2d4c-618b-11e7-8429-59979cf8339a.png)

**Comment by misha-kotov** [comment]
@okovalov-commer  Do you need to have multiple store views set up to reproduce this (your payload refers to store_id=0 and store_id=1)? If that's the case, can you add this to preconditions? I was testing with one store view and am seeing somewhat different results. 
The extra option being inserted on PUT is an existing issue reported in a previous GH issue: https://github.com/magento/magento2/issues/5963. It is fixed in the develop branch. 
I will try to reproduce the duplication next.

**Comment by okovalov-commer** [comment]
@misha-kotov good point, thank you. that note has been added to the list of steps to reproduce

**Comment by RomanKrut** [comment]
@okovalov-commer Hi. Thanks for your report. The internal ticket was created MAGETWO-70522

**Comment by magento-engcom-team** [comment]
@okovalov-commer, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
