### ISSUE TITLE
magento admin dashboard is not showing after login to admin panel

### ISSUE THREAD

**Issue by wiztechsarfaraz** [magento/magento2#10153]
After login to my admin panel the dashboard is not showing it shows error

"This page isn’t working

mydomain.in is currently unable to handle this request.
HTTP ERROR 500"  in google chrome.

And in firefox it shows blank page .

There's the screenshot below that shows error in chrome.
![screenshot 2017-07-05 18 08 03](https://user-images.githubusercontent.com/29625931/27864618-ebdb2a08-61ac-11e7-8cf7-7374596bb72e.png)

**Comment by veloraven** [comment]
@wiztechsarfaraz thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
