### ISSUE TITLE
Newsletter Problems Report

### ISSUE THREAD

**Issue by sunnylee5** [magento/magento2#10166]
### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. we set up the newsletter queue, and it shows " sent " , but we did not receive any newsletter, so we checked the Newsletter Problems Report, it shows:  Newsletter Problems Report -> Error Code 0 & Error Text - Invalid User 

### Actual Result
2. all the user are subscribed and valid, we can receive the other email like order , and other email, but only newsletter can not receive after sent. 

### Expected result

1. newsletter sent without error

**Comment by magento-engcom-team** [comment]
@sunnylee5 thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
