### ISSUE TITLE
Order confirmation email sent on pending/cancelled order -Payment 

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#10162]
The customer tried placing an order 4 times, for the first three times he cancelled the order himself.but the fourth time he hasn't even gone to the payment page from checkout, but he received an order confirmation email on pending state and it went to cancelled state after 8hours.

Since the customer received the order confirmation email, he thought the payment was taken from his card and was asking for an invoice. But we don't have any record either on Magento 2 or Sagepay.
On Magento 2 database for that particular order, it shows null value for sgaepay tracking id, which means customer hasnt even gone to payment page. On the order grid it shows pending, notified and cancelled. even on the database tables it shows pending at 20:54 and cancelled at 05:00.

This is creating a huge issue for us, as the order has been placed for a huge amount where the email has been sent without actually paying for the items.

### Preconditions
1. Debian 8 
2. Php 7
3.Maria DB(Mysql)
4.Magento 2.1.6

### Steps to reproduce
1.Cancelled the order (email not sent)
2. cancelled the order(email not sent)
3. cancelled the order(email not sent)
4.Pending to cancelled.(email sent)
### Expected result

1. Order cancelled and email not sent. 

### Actual result
1. order email sent on cancelled order/pending orders
![db 1](https://user-images.githubusercontent.com/19605497/27902631-58a1db10-622e-11e7-8cf5-fc2a6f9d4ea6.PNG)
![db 2](https://user-images.githubusercontent.com/19605497/27902639-5ca4e73e-622e-11e7-9da9-19b26559c0b0.PNG)
![email sent on cancelled](https://user-images.githubusercontent.com/19605497/27902652-63ec5356-622e-11e7-8e3e-590ddce60c7b.PNG)
![email sent 1](https://user-images.githubusercontent.com/19605497/27902659-68574298-622e-11e7-9bc8-0a890a778fb6.PNG)
![email not sent on 3 orders](https://user-images.githubusercontent.com/19605497/27902665-6c85a60c-622e-11e7-944b-f794199ed177.PNG)

.

1. [Screenshot, logs]

**Comment by fwegberts** [comment]
Same problem here, any solution for this?

**Comment by keevitaja** [comment]
Anyone know from where this email is sent?

**Comment by magento-engcom-team** [comment]
@nmallepally, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by keevitaja** [comment]
Guys, This is not an bug. Magento just uses wrong event for sending out these emails. 

The event we want it to use is `sales_order_payment_pay` but it is using something different

**Comment by nmallepally** [comment]
Hi @magento-engcom-team  ,

The issue again occurred today, any work around solution please.
This is causing a big headache with big orders as customers gets notified by email as an order is placed.
Magento 2.1.6
see below again for screen shots
![image](https://user-images.githubusercontent.com/19605497/32598662-387d163a-c532-11e7-80fd-3e535afe2673.png)

![image](https://user-images.githubusercontent.com/19605497/32598695-4ee3e502-c532-11e7-8307-0eb323cdcd99.png)
![image](https://user-images.githubusercontent.com/19605497/32598757-72c7298e-c532-11e7-8a6a-6df7d4fcdd0c.png)

![image](https://user-images.githubusercontent.com/19605497/32598787-83654d66-c532-11e7-9b1a-a847664f8b6a.png)

Any work around or a quick fix to stop this.
@keevitaja do you have any work around to avoid this issue?, please advise.

**Comment by michel334** [comment]
We have the same issue on Magento 2.1.9
Order with status Payment pending and confirmation email is send.

**Comment by sebfie** [comment]
Hello, same bug here, I use one step checkout? Can it be the reason?

**Comment by sunil-gcet** [comment]
We are also facing same problem on magento v 2.2.2, is there any solution for this error yet ?

**Comment by sebfie** [comment]
Do you use ogone/engenico?

Sébastien fieloux
Développeur freelance
0698458781 <//0698458781>
sebastien.fieloux@gmail.com
http://www.sebfie.com

Le 15 janvier 2018 à 09:25:14, Sunil Verma (notifications@github.com) a
écrit:

**Comment by sunil-gcet** [comment]
@sebfie no we have created a new payment gateway and no where in the code we are sending the email, so its triggering from core magento somewhere.

**Comment by sebfie** [comment]
I think the called which send email is : `->registerAuthorizationNotification()`

**Comment by nmallepally** [comment]
Hi @sebfie 
Yes, we use one step checkout extension from magestore as well.
Any work around?

**Comment by sebfie** [comment]
Yes, that's an issue on the module.

I overrided this method : 

```
<?php
namespace Sebfie\Core\Model\Response\Type;

class Authorize extends \Netresearch\OPS\Model\Response\Type\Authorize {
    /**
     * @param \Magento\Sales\Model\Order $order
     * @param \Magento\Sales\Model\Order\Payment $payment
     */
    protected function registerFeedback(\Magento\Sales\Model\Order $order, \Magento\Sales\Model\Order\Payment $payment)
    {
        if ($this->getShouldRegisterFeedback()) {
            if ($order->getState() === \Magento\Sales\Model\Order::STATE_PAYMENT_REVIEW) {
                if (\Netresearch\OPS\Model\Status::canResendPaymentInfo($this->getStatus())
                    && $this->oPSPaymentHelper->isInlinePayment($payment)
                ) {
                    $targetState = \Magento\Sales\Model\Order::STATE_CANCELED;
                    $payment->setNotificationResult(true);
                    $payment->deny(false);
                } else {
                    $targetState = \Magento\Sales\Model\Order::STATE_PENDING_PAYMENT;
                    $payment->setIsTransactionApproved(true);
                    $payment->update(false);
                }

                if ($order->getState() != $targetState) {
                    $order->setState($targetState);
                    $order->addStatusHistoryComment($this->getFinalStatusComment(), true);
                }
            } elseif ($order->getState() === \Magento\Sales\Model\Order::STATE_PENDING_PAYMENT
                || $order->getState() === \Magento\Sales\Model\Order::STATE_NEW
            ) {
                // SPECIAL FIX FOR CANCELED BY CUSTOMER STATUS
                if ($this->getStatus() != \Netresearch\OPS\Model\Status::CANCELED_BY_CUSTOMER) {
                    $payment->registerAuthorizationNotification($this->getAmount());
                    $order->setState(\Magento\Sales\Model\Order::STATE_PENDING_PAYMENT);
                } else {
                    $order->setState(\Magento\Sales\Model\Order::STATE_CANCELED);
                }
                $order->addStatusHistoryComment($this->getFinalStatusComment(), true);
            }
        } else {
            $this->addFinalStatusComment();
        }
    }
}

```


Check the line : 

` // SPECIAL FIX FOR CANCELED BY CUSTOMER STATUS`

**Comment by ElundKasper** [comment]
Where is the file located and its the OneStepCheckout extension right?
Have the problem that order witout payment gets send out the order email confirmation.

**Comment by techd7** [comment]
We are using payu plugin in magento 2.3.3 the movement the it goes to the payment gateway page the order confirmation mail is sent out 

We need to know how we can get this working to send mail only after payment confirmation

I se that the above solution working for lower version but not for  2.3.3 do you have any support on this ?

**Comment by nmallepally** [comment]
Hi,

Same issue here on Magento 2.3.4-p2 version as well. 
The moment it goes to the payment gateway page an order confirmation email is sent out without payment being completed.

This creates a lot of confusion for us and the customer, this could be a possible fraud situation where users can receive order emails without actually making a payment.

Would be great, if the magento team can looking into this quickly @magento-engcom-team

**Comment by mnasman** [comment]
Any help on this issue, we are facing it with magento 2.4.1 !!!
