### ISSUE TITLE
Attribute Sets not updating on import

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#10167]
### Preconditions

1. Magento 2.1.6
2. CSV file with valid SKUs and attribute set codes (that map to attribute sets in Magento)

### Steps to reproduce

1. Import file with SKUs and changed attribute set codes

### Expected result

1. Attribute set is changed on product (just like it does when doing manually in the Product Edit form)

### Actual result

1. Attribute set is not changed on product

**Comment by jameswithers** [comment]
https://github.com/magento/magento2/issues/5498 shows a fix was merged, but this is not in Magento 2.1.6?

**Comment by korostii** [comment]
@jameswithers, well, if you look closely enough, you can see that it's been only merged to the `develop` branch so far: http://take.ms/FVIYF

It still needs to get merged to `2.1-develop` and then after release it'll appear on `2.1` branch as well. The release process here is rather slow, so it'll probably take a couple months and a couple versions more, at least.
