### ISSUE TITLE
Backend Javascript Errors (new instalation)

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1016]
Folder /static/adminhtml/Magento/backend/en_US/jquery doenst present

![m1218](https://cloud.githubusercontent.com/assets/813985/5988129/8853d424-a95a-11e4-8759-229d02c823c2.png)

**Comment by anupdugar** [comment]
@Mackovey Is mod_rewrite enabled in Apache?
Check http://devdocs.magento.com/guides/v1.0/install-gde/system-requirements.html
For apache configuration: http://devdocs.magento.com/guides/v1.0/install-gde/prereq/apache.html

**Comment by anupdugar** [comment]
Also check similar issue previously reported for static content not being loaded: https://github.com/magento/magento2/issues/972

**Comment by vpelipenko** [comment]
@Mackovey, did you have a chance to look at previous comments with suggestions?

**Comment by Mackovey** [comment]
Looked #972, my apache2/php configuration is ok, mod_rewrite is enabled.

Did new installation (beta7), error still presents (screenshot is similar to above one).
> "NetworkError: 404 Not Found - pub/static/adminhtml/Magento/backend/en_US/jquery/jquery-migrate.js"
> "NetworkError: 404 Not Found - pub/static/adminhtml/Magento/backend/en_US/jquery/jquery-ui-1.9.2.js"

Attached new screenshot of folder `pub/static/adminhtml` after first launch.

![m1255](https://cloud.githubusercontent.com/assets/813985/6096211/e7b1b204-af8d-11e4-8243-400e94dedc3a.png)

**Comment by anupdugar** [comment]
Thanks for the information. 
Interestingly, all the static content except jquery related files are getting generated ( assuming your Magento instance is not running in developer mode). Looking into reproducing this on our end. Meanwhile feel free to share any additional steps (if not previously specified) to help reproduce it.

**Comment by buskamuza** [comment]
@Mackovey , Error 404 may be sent in case of any exception during processing of the file.
Would you mind to try the following experiment?
1. enable "developer" mode (add `SetEnv MAGE_MODE developer` in root `.htaccess` file)
2. remove everything, except `.htaccess` file from `pub/static` folder
3. open the web-site
4. find one of non-loaded jquery resources and open it in the browser

If any exception happens during processing of this resource, the error should be displayed on step 4.
If not, please, look at `pub/static` folder - it should contain only `.htaccess` file.

**Comment by Mackovey** [comment]
In `developer` mode everything works fine.

**Comment by buskamuza** [comment]
@Mackovey , thanks for the testing. I created an issue in our internal tracker.

Internal ticket MAGETWO-34173

**Comment by dmytroleonenko** [comment]
Disable MultiViews in pub/static/.htaccess like
Options -MultiViews

**Comment by hrmnngithub** [comment]
After disabling MultiViews, everything goes well with admin navigation, ver. 0.42.0-beta8.
Similar problem I experienced in ver. 0.42.0-beta7, so the solution was installing the public key for ssl connection  in root directory, after that everything gone well

**Comment by vpelipenko** [comment]
This issue is fixed internally and will be available for public after next weekly update.

**Comment by snohe** [comment]
@Mackovey, this is now available in 0.74.0-beta1.  Thank you again for submitting this issue!
