### ISSUE TITLE
Coupon codes not showing in invoice

### ISSUE THREAD

**Issue by DesignDesignInc** [magento/magento2#10168]
### Preconditions

1. Magento 2.1.7
2. 

### Steps to reproduce

1. Apply a coupon code and then place an order. 
2. Coupon code shows on order, then try to invoice order. 
3. 

### Expected result

1. Invoice and Order to show the same coupon code and totals.

### Actual result

1. Invoice doesn't show coupon code and invoice totals don't reflect the discount.

**Comment by RomanKrut** [comment]
@DesignDesignInc Hi. Thanks for the feedback. We already know about this problem. The internal ticket already exist MAGETWO-69705 to address this issue.

**Comment by magento-engcom-team** [comment]
@DesignDesignInc, thank you for your report.
We've created internal ticket(s) , MAGETWO-80428 to track progress on the issue.

**Comment by keyurshah070** [comment]
I'm working on it #SQUASHTOBERFEST @okorshenko

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82563

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82562

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release soon

**Comment by jaykobi** [comment]
Will this be backported to 2.1.x?

**Comment by okorshenko** [comment]
Hi @DesignDesignInc. Thank you for your report. 
The issue has been fixed in magento/magento2#13261 by @PieterCappelle in 2.1-develop branch
Related commit(s):
 - 2523177a7811dd237e56046b8b73b7a95671d362

The fix will be available with the upcoming patch release.
