### ISSUE TITLE
Can't use module names beginning with same characters

### ISSUE THREAD

**Issue by steros** [magento/magento2#10177]
### Preconditions
1. Magento 2.1.5
2. have a module enabled called "DeliveryPickupDate"

### Steps to reproduce
1. create a new module
2. create all necessary files (registration.php, module.xml, composer.json)
3. name it "DeliveryNote"

### Expected result
1. I can call `bin/magento module:enable`
2. the module is enabled

### Actual result
1. I call `bin/magento module:enable`
2. I get this error: "Unknown module(s): 'vendor_DeliveryNote'"
3. change the name in all appropriate files to "NoteDelivery"
4. now you can call `bin/magento module:enable`
5. the module is enabled successfully

**Comment by ihor-sviziev** [comment]
I've installed a few modules with the same vendor & modeled name prefix without any issues on 2.1.7. could you run ```bin/magento module:enable -v``` to have more detailed stack trace? Also would be great to have modules examples (just empty modules) on which this issue reproducing. I think there is some issue in your modules.

**Comment by steros** [comment]
Ah I didn't know that existed. I'll try it and see what it says.

**Comment by steros** [comment]
I changed the name back to DeliveryNote and tried to enable with -v and now it works %-)
I'll reopen when I hit the problem again and can give further information.
