### ISSUE TITLE
How to write custom query in Magento 2 collection format

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#10178]
I need following query in magento format.

SELECT * FROM ( SELECT * FROM TABLE_NAME WHERE customer_id IN ( 0, 5 ) ORDER BY feed_id DESC ) AS t1 GROUP BY position limit 0,5

**Comment by nntoan** [comment]
@aasim110  This repo is not proper section for this, if you want to ask programming question. Please use [Magento StackExchange](https://magento.stackexchange.com) or [Magento Forums](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2)

Regards,
Toan.
