### ISSUE TITLE
Image quality suffers

### ISSUE THREAD

**Issue by ambergithub** [magento/magento2#10186]
There is an issue with image resizing , the image quality suffers a lot Please refer the attached image.
The actual image on right and the magento resized image on left.
![bf1c2b08-a4af-4dbb-aa3c-546d392a4537](https://user-images.githubusercontent.com/8517353/27983587-da7f5c50-63d9-11e7-93b0-2d42c61f4c1d.jpg)

**Comment by hostep** [comment]
@ambergithub: github isn't really the place to ask these kind of questions. It's better if you ask them over at [Magento Stack Exchange](https://magento.stackexchange.com/) or in the [Magento Forums](https://community.magento.com/).

Nevertheless, there might be some interesting information over here which could help you out: https://github.com/magento/magento2/issues/5748

**Comment by magento-engcom-team** [comment]
@ambergithub, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
