### ISSUE TITLE
Massive action "Update attributes" doesn't works... need requirement fields

### ISSUE THREAD

**Issue by coachdesign** [magento/magento2#10191]
### Preconditions

1. Magento: 2.1.7
2. PHP: 7.0.16
3. MySQL: 5.5.32

### Steps to reproduce

1. Open in Admin: Products » Catalog
2. Select multiple items
3. Select action "Update Attributes"
4. check a "change" checkbox
5. insert value
6. Save

### Actual result

1. ![catalog___inventory___products___magento_admin___eko](https://user-images.githubusercontent.com/1880893/27988408-72c6f350-6421-11e7-8363-3b01bf907b53.png)

2. ![update_attributes___magento_admin___eko](https://user-images.githubusercontent.com/1880893/27988414-7ec54b20-6421-11e7-8ba8-aefd8f8a5d1b.png)

### Expected result
TBD

**Comment by orlangur** [comment]
Please describe `reperibilita` attribute and which attributes you trying to update.

For example, if it is a required attribute created after some products creation, you'll not be able to update these products without entering proper value for this new attribute.

**Comment by coachdesign** [comment]
If I have the following case: "A product with 3 required attributes"

attr1, attr2 and attr3

Selecting from list 5 products to change the value of attr3... Magento asks me to modify also attr1 and attr2 because they are mandatory.

But I just want to change attr3.

**Comment by orlangur** [comment]
How happened attr1 and attr2 to be empty for these products?

**Comment by coachdesign** [comment]
No, I want them to remain with the values previously entered ... since they only change attr3

**Comment by orlangur** [comment]
Thanks, I see, definitely a bug if they have valid values.

**Comment by magento-engcom-team** [comment]
Hi @coachdesign
We cannot reproduce this issue as described. 
My steps are:
1. Create two simple products with "default" attribute set;
2. Create attributes "attribute_1" and "attribute_2" with "Input Type" = "Text Field" and "Values Required" = "Yes";
3. Add attributes to "default" attribute set;
4. Go to Product > Catalog, select created products and click "Update attributes" action;
5. Check a "Change" checkbox on attribute_1 and set value;
6. Click Save

Message is: "A total of 2 record(s) were updated."
http://prntscr.com/gntfq3

Please provide the detailed steps we must follow to reproduce this issue.

**Comment by coachdesign** [comment]
![catalog___inventory___products___magento_admin___eko_](https://user-images.githubusercontent.com/1880893/30733386-07a73e9a-9f77-11e7-8bd7-de7c82277b18.png)
![update_attributes___magento_admin___eko 2](https://user-images.githubusercontent.com/1880893/30733385-07a0fbca-9f77-11e7-8877-cfe609444524.png)
![update_attributes___magento_admin___eko 3](https://user-images.githubusercontent.com/1880893/30733384-07998d54-9f77-11e7-984f-534436e2188a.png)

**Comment by magento-engcom-team** [comment]
@coachdesign, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by coachdesign** [comment]
I've updated Magento to version 2.2 the problem is still there
