### ISSUE TITLE
Order relation child is not set during edit operation.

### ISSUE THREAD

**Issue by dankocherga** [magento/magento2#10195]
Order relation child is not set during edit operation.

### Preconditions

Magento v2.1.7

### Steps to reproduce
1. Create an order
2. Edit the order through admin panel
3. Check `relation_child_id`and `relation_child_real_id` fields of the **old** order.

### Expected result
1. `relation_child_id`and `relation_child_real_id` fields are set to the IDs of the **new** order.
2. Link to the new order is displayed on old order's admin page

### Actual result
1. Fields **are null** in the database
2. Link to the new order **is not displayed** on old order's admin page

The problem seems to be related to how these fields are set: https://github.com/magento/magento2/blob/2.1.7/app/code/Magento/Sales/Model/AdminOrder/Create.php#L1878-L1882

The old order is not saved in that code segment.

**Comment by VasylShvorak** [comment]
@dankocherga Thanks for reporting this issue. Created internal issue MAGETWO-71006 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@dankocherga, thank you for your report.
We've created internal ticket(s) MAGETWO-71006 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83083

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release
