### ISSUE TITLE
Can't add products to cart with an IPad Mini 1

### ISSUE THREAD

**Issue by harrigo** [magento/magento2#10198]
Using an Ipad Mini 1 i am redirected to an empty cart page upon clicking add to cart button. This has been tested on a range of Ipads (Ipad 2, Ipad Mini 1 & 2, Ipad Air) however Mini 1 was only one with the issue. I have tested on Magento 2.1.7 however I have tried on a range of Magento 2 stores and all seem to all have the issue.

### Preconditions
Magento 2.1.7
PHP 7.0.15-1~dotdeb+8.1 (cli) ( NTS )
mysql Ver 14.14 Distrib 5.6.33, for Linux (i686) using EditLine wrapper

### Steps to reproduce

1. Navigate to a product
2. Add Product to Cart

### Expected result

1. Product Added to Cart

### Actual result

1. Redirected to empty cart page.

**Comment by magento-engcom-team** [comment]
Hi @harrigo

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@harrigo thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
