### ISSUE TITLE
Contact Us Email - Cannot have same to and from email address (Fails Silently)

### ISSUE THREAD

**Issue by fray-d** [magento/magento2#10194]
### Preconditions

1.  Magento 2.1.7
2. All other emails appear to work as expected.

### Steps to reproduce

1. Specify send to address manually
2. Select send from address as a configuration with the same email address
3. Submit contact us form.

### Expected result

1. System should send email, or throw a validation error when saving config, or throw an error when sending the email

### Actual result

1. Form submits with 'Thanks for contacting us'. Email never shows up.

**Comment by RomanKrut** [comment]
@parksddd Hi. Thanks for reporting this issue. I was trying to reproduce it. I use Gmail system, in admin Email option - Send Emails To - i put my working gmail. In contact us form i was using the same mail as in admin Send Emails To field. Then after I submit the message, it was send to my gmail correctly. I cannot reproduce the issue on clean instance 2.1.7 .
