### ISSUE TITLE
"Filter" option not loading on Catalog page load

### ISSUE THREAD

**Issue by RWCC-LTD** [magento/magento2#10193]
### Preconditions
Magento version 2.1.7
Browser: Firefox for Mac Sierra
No pre-set filters have been chosen

### Steps to reproduce
Click on Products > Catalog, the page will load but the "fitlers" option is blacked out, upon refreshing this can sometimes load or sometimes not. 

### Expected result
Filter option should be selectable on page load

### Actual result
The filters option is greyed out

**Comment by magento-engcom-team** [comment]
@sjhill-rwcc, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
