### ISSUE TITLE
Email shows € as â‚¬

### ISSUE THREAD

**Issue by EthicalErik** [magento/magento2#10190]
The email that is created by magento after a new order is placed contains â‚¬ instead of a euro sign.

### Preconditions
1. Magento 2.1.7
2. Magento default new order template
3. Browser version of hotmail & thunderbird used.

### Steps to reproduce
1.  Set the store currency to euro.
2.  Make an order so you get the new order email
3.  The email will display the items bought with their value. € is displayed as â‚¬

### Expected result
1.  â‚¬ should be €

### Actual result
https://cl.ly/2U0H2p3R041W

**Comment by 1408sheva** [comment]
Hi, @erik921. In file PHP.ini, find "iconv.input_encoding" and send me the value..

**Comment by EthicalErik** [comment]
Hey @1408sheva !
Sorry for the late reply.
It is empty, default value is being used.

**Comment by TomashKhamlai** [comment]
Hello @erik921, if I ececute this command `cat /etc/php.ini | grep -in iconv.input_encoding`, I have this output in the CLI:
```text
901:; If empty, default_charset or input_encoding or iconv.input_encoding is used.
902:; The precedence is: default_charset < intput_encoding < iconv.input_encoding
903:;iconv.input_encoding =
```
Yes, it is empty. But pay attention to line 902, where there is the order of precedence shown. According to this the next thing to do is execute this:
`cat /etc/php.ini | grep -in intput_encoding`
output in the CLI:
```text
902:; The precedence is: default_charset < intput_encoding < iconv.input_encoding
1528:; The precedence is: default_charset < intput_encoding < mbsting.http_input
```
`cat /etc/php.ini | grep -in default_charset`
output in the CLI:
```text
677:default_charset = "UTF-8"
680:; If empty, default_charset is used.
685:; If empty, default_charset is used.
690:; If empty, default_charset is used.
901:; If empty, default_charset or input_encoding or iconv.input_encoding is used.
902:; The precedence is: default_charset < intput_encoding < iconv.input_encoding
906:; If empty, default_charset or internal_encoding or iconv.internal_encoding is used.
907:; The precedence is: default_charset < internal_encoding < iconv.internal_encoding
911:; If empty, default_charset or output_encoding or iconv.output_encoding is used.
912:; The precedence is: default_charset < output_encoding < iconv.output_encoding
1055:;ibase.default_charset =
1520:; If empty, default_charset or internal_encoding or iconv.internal_encoding is used.
1521:; The precedence is: default_charset < internal_encoding < iconv.internal_encoding
1527:; If empty, default_charset or input_encoding or mbstring.input is used.
1528:; The precedence is: default_charset < intput_encoding < mbsting.http_input
1535:; If empty, default_charset or output_encoding or mbstring.http_output is used.
1536:; The precedence is: default_charset < output_encoding < mbstring.http_output
```
So, in my CentOS 7 default_charset = intput_encoding = iconv.input_encoding = "UTF-8"
Can you confirm that you have CentOS and you have the same settings?

**Comment by TomashKhamlai** [comment]
@erik921, paste this line '€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ+hello%&nbsp;world.' when you create the shipment and make sure that checkbox 'Send email to customer' is checked. It's very interesting what you will get in Thunderbird. Show us please.

**Comment by EthicalErik** [comment]
We changed the mailserver to the office 365 mailserver.
The € is now correctly displayed.
