### ISSUE TITLE
New handles for the Category, Product and CMS pages

### ISSUE THREAD

**Issue by paales** [magento/magento2#102]
### Add handles to category page

If you are viewing a category: /products/dvds.html (category id: 5)

You'll get a handle by default: `CATEGORY_5`

We add the following:
##### Handle: `CATEGORY_2_child_child`

Category 2 is the root category for this store, so allows for store specific configuration. If the category path is
longer it will show something like `CATEGORY_2_child_child_child`
##### Handle: `CATEGORY_2_child_dvds`

This one is kinda cool, this one allows you have one layout for multiple childcategories. Imagine the following categories:
- /playgroup/books.html
- /kindergarten/books.html
- /elementary/books.html

All these categories will have the `CATEGORY_2_child_books` handle, so you can all style them the same!
##### Handle: `CATEGORY_3_child`

Child of a certain category.
If the category path is longer it will show something like `CATEGORY_3_child_child`.
### Add category handle to product page.

The same as for the category applies, except everything is prefixed with `PRODUCT_CATEGORY_` instead of `CATEGORY_`.
### Add attribute set handle to product page

```
PRODUCT_ATTRIBUTE_SET_default
```

For styling based on the attribute set handle.
### Add handles to CMS page

If you have the page: customerservice/faq/question_one, you'll get the following handles (same idea as for the categories):

```
CMS_PAGE_customerservice_child_child
CMS_PAGE_customerservice_faq_child
CMS_PAGE_customerservice_faq_question_one
```

**Comment by ilnytskyi** [comment]
Not sure what it was like in 2012 but that would be nice to have possibility to disable additional (product_id,sku/category_id) handles.
Check my comment https://github.com/magento/magento2/issues/189#issuecomment-698430804
Now we have thousands of entries in the cache storage that we do not need...

**Comment by paales** [comment]
@ilnytskyi Wow, that is an old issue! I don't thing you'll get any meaningful response. In 2012 this looked like a great idea, but not so much any more ;)

**Comment by ilnytskyi** [comment]
When we removed entity ids from layout handles. We reduced used cache space significantly and it also improved overall page performance.
![Selection_639](https://user-images.githubusercontent.com/3192770/115952943-36e14400-a4e9-11eb-863f-b08a43a30edb.png)
