### ISSUE TITLE
Email footer template does not render

### ISSUE THREAD

**Issue by fray-d** [magento/magento2#10201]
### Preconditions

1.  2.1.7
2. 

### Steps to reproduce

1. Send any email
2. 
3. 

### Expected result

1. Email renders as expected

### Actual result

1. Email Footer Template does not render. Never shows up.

**Comment by fray-d** [comment]
As a follow up. I created my own module, and set up some additional email templates, and all of them render correctly. This appears to only be an issue with the out of the box footer_template and the ability to override the footer_template either via web admin or theme code.

**Comment by magento-engcom-team** [comment]
@parksddd, thank you for your report.
We've created internal ticket(s) MAGETWO-81246 to track progress on the issue.

**Comment by davidverholen** [comment]
starting to work on it

**Comment by davidverholen** [comment]
@magento-engcom-team cannot reproduce this on develop branch.
Footer Template is loaded and rendered as expected from the luma theme

tested by sending order emails with a new installation from develop branch

**Comment by ishakhsuvarov** [comment]
Hi @davidverholen 
We have followed these steps in order to reproduce the issue, please confirm it doesn't work for you:

### Steps to reproduce
1. Go to backend -> Marketing -> Email Templates -> Add new Template
2. Load default template: choose `Footer` or `Footer blank/luma` and click load template button
3. Make some changes in Template Content and hit save
4. Try to receive any email from website

### Expected result
Footer is updated with new content in emails

### Actual result
Emails still use default footer

**Comment by davidverholen** [comment]
@ishakhsuvarov  just tested it. There is a configuration design/email/footer_template.
After changing it the footer is loaded as expected (at least in the develop branch)

**Comment by ishakhsuvarov** [comment]
@davidverholen Thank you for your investigation. We will check this again based on your research.

**Comment by magento-engcom-team** [comment]
@parksddd, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
