### ISSUE TITLE
Will the upgrade help with an error?

### ISSUE THREAD

**Issue by LigeiaPoe** [magento/magento2#10202]
Hello.
I am using Magento 2.1.2. I'm trying to edit category in different store views. One store view hasnt any issues, but another one displays such error: 
_URL key for specified store already exists._
Is it fixed in the Magento 2.1.7?

**Comment by southerncomputer** [comment]
see https://github.com/magento/magento2/issues/9290

**Comment by andidhouse** [comment]
no - this bug is still present in 2.1.7.

The magento team knows this now over 1 year but does not fix this.

**Comment by LigeiaPoe** [comment]
@andidhouse thank you for your answer. I will hope, that will be fix in next versions.

**Comment by magento-engcom-team** [comment]
@LigeiaPoe Closing this issue as it seems to be a duplicate of #9290 as @southerncomputer pointed out.

Thank you.
