### ISSUE TITLE
There is no active from to date in product

### ISSUE THREAD

**Issue by karthigesh** [magento/magento2#10216]
https://shop.maxmuscle.com/
Preconditions

    Magento 2.1.2
    Php 7

Steps to reproduce

    Create a product in admin if i have to give the product active only till this date there is no option

Expected result

    There should be a date similar to special date

Actual result

    There is no such option
I think this is the basic option in any shopping cart if the client has to set the product visible only for two or three days etc., but there is no possibility to choose from

**Comment by Dart18** [comment]
The same feature should be implemented for the categories. Managing the visibility of seasonal products such as food, flowers, sports equipment, etc. and landing pages related to the year time or recurring events is a feature often required by my clients.

**Comment by okorshenko** [comment]
Hi @karthigesh this feature is available in EE. Please use Staging functionality for that. Closing as non issues
