### ISSUE TITLE
Content expiry flag is not added to header for image files in /media/ on Nginx

### ISSUE THREAD

**Issue by shabanriaz** [magento/magento2#10217]
### Preconditions
1. Magento 2.1.7, PHP 7
2. MySQL 5.7

### Steps to reproduce
1. Create a product, and upload some images with the product.
2. Open page in chrome browser.
3. Open developer tools and go to Network tab.
4. Click on the product image in list of resources.

### Expected result
1. As per nginx configuration all images loaded from /media/ folder should have an "expires".

```
location /media/ {
    try_files $uri $uri/ /get.php?$args;

    location ~ ^/media/theme_customization/.*\.xml {
        deny all;
    }

    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
        add_header Cache-Control "public";
        add_header X-Frame-Options "SAMEORIGIN";
        expires +1y;
        try_files $uri $uri/ /get.php?$args;
    }
    location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
        add_header Cache-Control "no-store";
        add_header X-Frame-Options "SAMEORIGIN";
        expires    off;
        try_files $uri $uri/ /get.php?$args;
    }
    add_header X-Frame-Options "SAMEORIGIN";
}

```
### Actual result

1. No "expires" tag is available in image headers.
![headers](https://user-images.githubusercontent.com/9161452/28105628-6e0fb738-671f-11e7-9bea-44aefabc40e4.JPG)

**Comment by magento-engcom-team** [comment]
@shabanriaz, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
