### ISSUE TITLE
Is it good practice for a child theme to inherit from luma?

### ISSUE THREAD

**Issue by rossmc** [magento/magento2#10212]
Can clarification on best practice for theme inheritance be give on this?  I can't find anything definitive in the [documentation](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-inherit.html).

I have read in a comment from @alankent that it was not recommended that a child theme inherit from Luma:
> The Luma theme is not designed to be inherited from - it is purely developed as a demo store for people to explore and play with
https://github.com/magento/magento2/issues/2547#issuecomment-160783766

But later he posted that the plan is to change this:
> I checked with the PM's more recently, and they said aim is now to allow people to inherit from Luma. 
https://github.com/magento/magento2/issues/3220#issuecomment-177296871

Is this the case now?

Recently we upgraded to version RC3 and I found new style rules had been added to:
[luma/Magento_Checkout/web/css/source/module/checkout/_progress-bar.less](https://github.com/magento/magento2/blob/develop/app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/checkout/_progress-bar.less) see [gitdiff](https://www.diffchecker.com/SqKKheTV).  Our child theme inherited this change and it sigly changed the appearance of the progress bar in our theme.

It's not a big deal to fix but it would be good to know which theme should be used for stable stable CSS rules, blank or luma?  Or is it possible both could change on a upgrade?

It would be nice to inherit from either, luma has a slightly better base design design features, e.g. the layered nav is responsive on luma but not on blank.

**Comment by rossmc** [comment]
There is a thread on magento.stackexchange discussing this issue in more detail.

https://magento.stackexchange.com/q/183130/6549

Basically, this is an issue others have experienced and have had to make clones of the core magento theme's to overcome it.  Yet, this means they could miss important updates.

Also, if you compare Luma & Blank themes from different releases with a diff command it shows lots of changes to LESS files.

As style rules from both Luma & Blank are subject to a lot of change on new Magento releases, this could cause problems in your child theme on every upgrade, the whole theme would need to be checked and CSS fixes applied.

Unless there is a better approach?

**Comment by magento-engcom-team** [comment]
@rossmc please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
