### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getTracking()

### ISSUE THREAD

**Issue by iamkerly** [magento/magento2#10214]
Hi there

What seem's to be the problem with this log? I suspected that this log came from checkoutpage when the customer process her/his details.

[08-Jun-2017 02:41:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getTracking() on array in /home/xxx/public_html/vendor/magento/module-shipping/view/frontend/templates/tracking/details.phtml:22
Stack trace:
#0 /home/xxx/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 /home/xxx/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/home/xxx/...', Array)
#2 /home/xxx/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/xxx/...')
#3 /home/xxx/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#4 /home/xxx/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#5 /home/xxx/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Fr in /home/xxx/public_html/vendor/magento/module-shipping/view/frontend/templates/tracking/details.phtml on line 22

Magento ver. 2.1.4
PHP Version 7.0.20

Thanks,
iamkerly

**Comment by scottsb** [comment]
For anyone else that comes across this on Google, this was fixed under #8842.
