### ISSUE TITLE
In split database not able update Statistics for coupon report

### ISSUE THREAD

**Issue by ram10raj** [magento/magento2#10215]
Hi Team,

I have configured the fresh  Magento ee 2.1.5  when trying to refresh the statistics of coupon report i'm getting error "We can't refresh lifetime statistics."

**Note** : I'm using split database

### Preconditions
1.Magento EE 2.1.5 
2. PHP 5.6.28
3.Mysql 5.6.32

### Steps to reproduce
1. Login to admin panel with valid username and password
2. Goto to Reports >> Statistics >> Refresh statistics  >> in that grid check the coupon >> refresh lifetime statistics  

### Expected result
1. Successfully refreshed the Statistics 

### Actual result
1. We can't refresh lifetime statistics.
![refresh](https://user-images.githubusercontent.com/5101136/28104517-0e67c364-66f9-11e7-8c84-4bbec6ff20d4.png)

**Comment by ram10raj** [comment]
@team:

After my research i have changed the connection di.xml then i'm able to update the statistics 

```
<type name="Magento\SalesRule\Model\ResourceModel\Report\Rule\Createdat">
        <arguments>
            <argument name="connectionName" xsi:type="string">default</argument>
        </arguments>
    </type>
    <type name="Magento\SalesRule\Model\ResourceModel\Report\Rule\Updatedat">
        <arguments>
            <argument name="connectionName" xsi:type="string">default</argument>
        </arguments>
    </type>

```

**Reason for this change :** 

After splitting database salesrule table is under main database but connection is refers to sales database it's throwing " Base table or view not found: 1146 Table 'mage_sales.salesrule_coupon_aggregated' doesn't exist"

After changing the connection sales to default it's working .

**@team** : But still report showing empty. Because I'm getting error after clicking show report 

> "Base table or view not found: 1146 Table 'mage_sales.salesrule_coupon_aggregated' doesn't exist,"

Please advise me how fix this issue.

**Comment by orlangur** [comment]
@ram10raj your bug report is brilliant but it is unlikely to be replied here.

> Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Community Edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by veloraven** [comment]
@ram10raj thank you for your report.
Unfortunately we can not treat it as an issue in GitHub as it is intended for CE issues only and split database functionality is present in EE only.
Please report it via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
