### ISSUE TITLE
Elastic Search

### ISSUE THREAD

**Issue by pavanusn** [magento/magento2#10224]
When I enable elastic search I'm getting below exception on the store front. Please provide a solution to fix this

2 exception(s):
Exception #0 (Elasticsearch\Common\Exceptions\BadRequest400Exception): query_parsing_exception: [terms] query does not support [eq] within lookup element
Exception #1 (Elasticsearch\Common\Exceptions\BadRequest400Exception): {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[terms] query does not support [eq] within lookup element","index":"magento21.stg1u217_product_1_v4","line":1,"col":108}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento21.stg1u217_product_1_v4","node":"-rpy-CSGQ1iwKsXEAJ_Dlw","reason":{"type":"query_parsing_exception","reason":"[terms] query does not support [eq] within lookup element","index":"magento21.stg1u217_product_1_v4","line":1,"col":108}}]},"status":400}

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Community Edition, isn't it?

In such case
> Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Community Edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by pavanusn** [comment]
Yes I'm using enterprise

**Comment by pboisvert** [comment]
As noted, if using Enterprise please file a ticket in the Partner portal or via the Merchant account.
