### ISSUE TITLE
Support requestAutocomplete out of the box

### ISSUE THREAD

**Issue by navarr** [magento/magento2#1022]
Suggested Labels: feature request, up for grabs

Request Autocomplete is a web technology implemented in Chrome that enables *very* speedy entry of a customers credit card details, addresses, and more.

It is very simple to implement, and would be a general improvement to Magento in all forms.

More information:
* [HTML5 Rocks page](http://www.html5rocks.com/en/tutorials/forms/requestautocomplete/)
* [HTLM5 Rocks Demo Store (check it out!)](https://googledrive.com/host/0B28BnxIvH5DueUxvWVNsQXd5dU0/)
* [Firefox browser implementation bug](https://bugzilla.mozilla.org/show_bug.cgi?id=990367)
* [Previous Art: Magento1 Extension by the Chromium team](https://github.com/chromium/requestautocomplete-magento-extension)

**Comment by joanhe** [comment]
@navarr Thanks for your suggestion. I have created an internal feature request for this: MAGETWO-33670

**Comment by tkacheva** [comment]
Thanks for the suggestion! We will consider adding requestAutocomplete. MAGETWO-13847

**Comment by navarr** [comment]
Is this accepted, rejected, "on backlog", or in limbo?

Internal tickets MAGETWO-33670, MAGETWO-13847

**Comment by vpelipenko** [comment]
@navarr, task is added to product backlog. Correct link is MAGETWO-33670.

**Comment by navarr** [comment]
This may no longer be worthwhile as Chrome is removing requestAutocomplete:

https://codereview.chromium.org/1931043002/#ps110001

**Comment by navarr** [comment]
This should be updated for the standardized "Payment Request" API

Details: https://developers.google.com/web/fundamentals/primers/payment-request/?hl=en

**Comment by navarr** [comment]
Should I close this issue and move it to the forums as a Feature Request for the Payment Request API?

**Comment by pboisvert** [comment]
@navarr we will move this to forums and close this issue

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Support-requestAutocomplete-out-of-the-box/idi-p/47313).
