### ISSUE TITLE
CE 2.2.0-RC1.3, EE 2.2.0-RC1.3, B2B 1.0.0-RC1.3 - Error creating company via admin "Could not save company"

### ISSUE THREAD

**Issue by careys7** [magento/magento2#10229]
### Preconditions

1. CE 2.2.0-RC1.3
2. EE 2.2.0-RC1.3
3. B2B 1.0.0-RC1.3
4. MySQL 5.7
5. PHP 7.0.20

### Steps to reproduce

1. Create company with default settings and minimum fields required via admin

### Expected result

1. Company created successfully

### Actual result

1. Error appears "Could not save company". 
2. Company is visible in grid
3. Trying to open produces the error "The requested company is not found"
4. No exception or relevant error logs produced

**Comment by smoskaluk** [comment]
@careys7 Please provide more detailed steps we must follow to reproduce this issue.

**Comment by careys7** [comment]
@smoskaluk we get this result after entering any data into the required fields in admin

**Comment by magento-engcom-team** [comment]
@careys7 thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by celorodovalho** [comment]
@careys7 I had the same problem, but I could edit the company, after follow this step:

https://docs.magento.com/user-guide/customers/account-company-manage.html#activate-company-accounts
```
Activate company accounts
Set the Actions control to Set Active.

When prompted to confirm, click OK.
```
