### ISSUE TITLE
Pagination controls missing.

### ISSUE THREAD

**Issue by fray-d** [magento/magento2#10238]
### Preconditions

1. Magento 2.1.7
2. Any theme including blank.

### Steps to reproduce

1.  Create a category
2. Populate with many items
3. Visit category page on front end

### Expected result

1. Items should be shown with pagination

### Actual result

1. No pagination, filtering works, but only the first page or results is available.

**Comment by SanderJP** [comment]
Do you not see the pagination on the bottom of the page?
(clean 2.1.7 with sample data)

![image](https://user-images.githubusercontent.com/2470914/28271829-f91949f0-6b09-11e7-8a1c-7ca5982f11d3.png)

**Comment by fray-d** [comment]
I've done some additional testing and it seems to be stemming from a module included with the FreeGo theme called Solwin_SoldOut. Disabling this module will reenable the pagination controls. I'll try and contact the developer to make them aware.

**Comment by SanderJP** [comment]
Ah good to know you figured it out.
If it isn't an issue anymore, you can close this ticket.
