### ISSUE TITLE
InputException : Recoverable Error

### ISSUE THREAD

**Issue by minesh0111** [magento/magento2#10230]
### Preconditions

1.  Magento ver. 2.1.5 

### Steps to reproduce

1. Error when apply coupon code to cart when minimum order amount is enabled from 

> Stores -> Configuration -> Sales -> Minimum Order Amount

### Expected result

1. It should display only warning 

### Actual result

1. throw InputException with invalid argument

2. Recoverable Error: Argument 1 passed to Magento
.Recoverable Error: Argument 1 passed to Magento\Framework\Exception\InputException::__construct() must be an instance of Magento\Framework\Phrase, string given, called in[ /vendor/magento/module-quote/Model/ShippingAddressManagement.php](https://github.com/magento/magento2/blob/develop/app/code/Magento/Quote/Model/ShippingAddressManagement.php#L119) on line 119 and defined in /vendor/magento/framework/Exception/InputException.php on line 51

i see minimum order amount issue is fixed in latest version but InputException with invalid parameter still exist in code.

**Comment by Andrii-Deineha** [comment]
@minesh0111 Hi, I cannot reproduce this issue. Please add more details to your description of the steps you followed when identifying this issue(type of product, summ of minimum order quantity, price without cupon, cupon discount) . Screenshots or logs would be helpful, too. Thank.

**Comment by minesh0111** [comment]
@veloraven 

Below are the steps to reproduces issue.
 
1. add minimum order amount to 10 in `Stores -> Configuration -> Sales -> Minimum Order Amount`
2. now add any product in cart with amount less than 10
3. go to checkout page and try to apply valid coupon code

**Comment by minesh0111** [comment]
@veloraven any updates on this ?

**Comment by minesh0111** [comment]
[Magento/Framework/Exception/InputException.php](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Exception/InputException.php#L54) check this file. calling parameter is wrong in file [Magento/Quote/Model/ShippingAddressManagement.php](https://github.com/magento/magento2/blob/develop/app/code/Magento/Quote/Model/ShippingAddressManagement.php#L119)

**Comment by magento-engcom-team** [comment]
@minesh0111, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by minesh0111** [comment]
@magento-engcom-team  i am also can not reproduce this issue again but code issue is still there if you check code. argument miss match is still present in code.
