### ISSUE TITLE
Feature Request: Integrate Google Recapcha

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1023]
How about instead of using the very intrusive capcha that exists right now, you integrate *Google No Captcha Recaptcha*? https://www.google.com/recaptcha/intro/index.html

**Comment by piotrekkaminski** [comment]
This is on the roadmap, tentatively scheduled for next year. Internal ticket MAGETWO-46399.

**Comment by piotrekkaminski** [comment]
Merging into one  issue https://github.com/magento/magento2/issues/3023
