### ISSUE TITLE
Can't access Magento Admin on Multiple Computers (IPv6 Issue)

### ISSUE THREAD

**Issue by ooples** [magento/magento2#10249]
This is a complicated issue for me so I will do my best to explain the steps I have taken to try to figure out what is going on. The issue seems to be coming from ipv6 on my server if I had to give my best guess because the issue only seems to happen when I login from a newer computer. This issue only just happened by the way. I was able to login before with the same computer and I have made no changes on my end.

Here is what I see when I try to login from a newer computer that uses ipv6

[![enter image description here][1]][1]

When I do a ping for my website from this same computer, this is what I get

[![enter image description here][2]][2]

When I check the ipv6 on my server, this is what I get

[![enter image description here][3]][3]

So is this a magento login issue that someone has come across or is this a server issue that I'm not aware of? Does anyone know what to do to fix this?

UPDATE: I have confirmed that any computer that uses ipv6 can't access my magento admin section but any computer that uses ipv4 can access without any issues and I need to figure out how to fix this issue instead of asking all my customers and employees to disable their ipv6

  [1]: https://i.stack.imgur.com/ygjm8.png
  [2]: https://i.stack.imgur.com/Rvl03.png
  [3]: https://i.stack.imgur.com/0jjTr.png

**Comment by southerncomputer** [comment]
Discover DNS ipv6 and the AAAA record to go along with your  magento's A record!

**Comment by ooples** [comment]
I'm not exactly sure what you mean

**Comment by nntoan** [comment]
Your storefronts works?

**Comment by ooples** [comment]
Yes the storefront works just fine but it is only the admin section that shows that error message for anyone using ipv6 on their computer

**Comment by magento-engcom-team** [comment]
@ooples, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
