### ISSUE TITLE
Magento 2 404 error on some pages of admin panel

### ISSUE THREAD

**Issue by tjain90** [magento/magento2#10247]
Hi everyone I am getting 404 error on some configuration of admin panel like product view, design configuration etc.

Here is the snapshot:
![catalog](https://user-images.githubusercontent.com/6376301/28238497-8d0028bc-6972-11e7-82e0-40ccbe39f704.PNG)
![design](https://user-images.githubusercontent.com/6376301/28238498-8d01f1e2-6972-11e7-992d-217a5e88feb5.PNG)

I have flush magento cache, run deploy and update command but none of them work

Even i am unable to add javacsript to my header.

**Comment by Flyingmana** [comment]
Hi @tjain90,

could you look into the dev tools of your browser and into the network tab there to get the complete URLs which respond with 404?

**Comment by misha-kotov** [comment]
Thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with system versions and config, steps to reproduce, actual result and expected result.

**Comment by tjain90** [comment]
Hi Flyingmana,

It is due to this page

In Design Configuration :
pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/grid/controls/bookmarks/bookmarks.html/

There is some issue with text.min.js.

Is there any way i can update it or replace it with default.
Please help ! its really urgent.

**Comment by misha-kotov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
