### ISSUE TITLE
Merge customer name fields

### ISSUE THREAD

**Issue by kassner** [magento/magento2#1024]
Hi,

Can you guys think about merging all customer's name-related fields (`prefix`, `firstname`, `middlename`, `lastname` and `suffix`) into a single `name` field? I think this makes magento a more international product.

Motivational literature:
http://www.w3.org/International/questions/qa-personal-names
http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
http://blog.jgc.org/2010/06/your-last-name-contains-invalid.html

Thanks!

**Comment by ilol** [comment]
Great idea, @kassner. I created the feature request with internal tracking number MAGETWO-33841. Please, reference to this id in further conversation.

**Comment by vpelipenko** [comment]
Also if you would like to contribute suggested changes, your pull request is always welcome :-).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Merge-customer-name-fields/idi-p/47309).

**Comment by gety9** [comment]
So right now Magento 2 has Full Name instead of Separate First and Last Names?
