### ISSUE TITLE
Incorrect URL's

### ISSUE THREAD

**Issue by noprobz09** [magento/magento2#10240]
**Steps to reproduce**

**Magento 2.1.3**
Product URL Key set to "superman.html"

**Expected result**
URL will be like www.domain.com/superman.html

Catalog URL Key Setting:
Screenshot: https://www.screencast.com/t/UWteehVoep

Store Config:
https://www.screencast.com/t/L4wURlNw0Qm

**Actual result**
There were weird URL's generated on the URL Rewrites.
Wierd URL's
https://www.foundmi.com/superman-rebirth.html.html - weird
https://www.foundmi.com/superman-rebirth.html - correct
https://www.foundmi.com/catalog/product/view/id/16/s/superman-rebirth/ - weird

**Comment by Flyingmana** [comment]
Hi @noprobz09 
I believe  the URL Key should not contain a ".html" which would explain the first weird case. (actually, you dont have the .html inside your screenshot, so its maybe the other sufix setting which is causing this)
The second weird case is the controller specific url, which is normal to be available, but nothing should point to it.

I dont know about the best config here, but it looks like https://blog.amasty.com/magento-2-seo-full-overview-default-settings/ is a good overview. I suggest you to also activate the canonical meta tag for products.

I hope this is helpfull to solve your issues.

**Comment by SanderJP** [comment]
@noprobz09 I cannot re-produce this. When I create a product with a clean Magento 2.1.3 install, it'll make one URL rewrite only: `test-product.html >> catalog/product/view/id/1`.
If I add `.html` to the URL key on a product page, the URL becomes: `test-product2-html.html`, so not `.html.html`. Please provide more information if this is still an issue.

**Comment by keevitaja** [comment]
I have the same issue. Under specific category product urls lool like this:

```
catalog/product/view/id/7874/s/muets-sall-breden-1/category/103/
```

I moved the product under the new category, but it did not solve the problem. Any help here?

**Comment by orlangur** [comment]
@keevitaja it looks like URL Rewrites are missing for this product (incorrect import?). Try to re-save this product and find corresponding URL Rewrites in grid.

**Comment by keevitaja** [comment]
Thank you. 

I found this plugin and it fixed the issue: https://github.com/Iazel/magento2-regenurl

**Comment by magento-engcom-team** [comment]
@noprobz09, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
