### ISSUE TITLE
Session-based authentication doesn't work

### ISSUE THREAD

**Issue by piavgh** [magento/magento2#10258]
### Preconditions

1. XAMPP for MacOS 5.6.31 / PHP 5.6.31
2. Magento 2.1.7
3. I followed guideline in this article: http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-session.html

### Steps to reproduce

1. Create new customer at Magento 2 website
2. Login customer with email/password
3. On the same browser, open new tab
4. Go to http://<magento_host>/rest/V1/customers/me

### Expected result

1. The information of customer should displayed (as xml because we are using browser)

### Actual result

1. Screenshot: http://prntscr.com/fwn2mu

I tried to create another GET endpoint with permission "self", and the result is the same "Consumer is not authorized to access %resources"

**Comment by piavgh** [comment]
I checked something, and it seems both token based and session based authentication is using a same checking mechanism, which goes through this function:

```
/**
     * Perform authentication and authorization.
     *
     * @throws \Magento\Framework\Exception\AuthorizationException
     * @return void
     */
    private function checkPermissions()
    {
        $route = $this->router->match($this->request);
        if (!$this->authorization->isAllowed($route->getAclResources())) {
            $params = ['resources' => implode(', ', $route->getAclResources())];
            throw new AuthorizationException(
                __(AuthorizationException::NOT_AUTHORIZED, $params)
            );
        }
    }
```
in class RequestValidator.php

So it seems session based authentication in Magento 2 is not implemented yet.

**Comment by misha-kotov** [comment]
The session based authentication functionality was restricted to only allow for AJAX calls and not direct browser requests due to security vulnerabilities. This is why the docs mention you must do this via a JS widget to invoke the `self` endpoints. 
The use case is for an extension or a developer to be able to create a custom storefront widget that can issue requests without additional authentication steps. 
Adding @keharper here to clarify this in our docs.

**Comment by piavgh** [comment]
Hi @misha-kotov 
Thank you for your response.

I'm using Postman chrome extension with Interceptor (which mean Postman uses the same cookie as Chrome browser) to make request. This is similar to an AJAX call of JS widget in my opinion.
But the result is the same, I can not access the "self" endpoint. 

Do I have to use a real JS application which calls AJAX (jquery, angular,...) to verify that "self" endpoints is working normally?
Thanks

**Comment by misha-kotov** [comment]
@piavgh if you want to use session-based authentication, yes. Alternatively you can send these requests using [token-based authentication](http://devdocs.magento.com/guides/v2.1/get-started/authentication/gs-authentication-token.html) (with a customer token) to test the endpoint.

**Comment by piavgh** [comment]
Thank you very much @misha-kotov 

Our team managed to use session based authentication. We need to use some custom header and also some config in .htaccess.

**Comment by ghost** [comment]
@piavgh Can you share some information on how you solved this?

I don't seem to be able to workaround it since Magento uses two cookies for authentication.

https://github.com/magento/magento2/issues/14297
https://github.com/magento/magento2/issues/9138

**Comment by VarunAgw** [comment]
@misha-kotov I don't know how to even AJAX request. Chrome sent OPTIONS request first (probably something to do with `Access-Control-Allow-Origin`. But Magneto don't allow OPTIONS and it crash.

**Comment by VarunAgw** [comment]
nvm found this functionality is not implemented in magento yet.

https://github.com/splashlab/magento-2-cors-requests
https://stackoverflow.com/questions/35174585/how-to-add-cors-cross-origin-policy-to-all-domains-in-nginx

Seems to be only workaround.

**Comment by wojtekn** [comment]
This looks as not connected with CORS at all. This behavior was introduced in 2.1.7 by adding the \Magento\Webapi\Model\Plugin\Authorization\CustomerSessionUserContext plugin:

    public function afterGetUserId(
        \Magento\Customer\Model\Authorization\CustomerSessionUserContext $userContext,
        $result
    ) {
        return $this->request->isXmlHttpRequest() ? $result : null;
    }

The simplest workaround is to set X-Requested-With = XMLHttpRequest header for the request.
