### ISSUE TITLE
Error on saving plugin settings: "There has been an error processing you request. Notice: Array to string conversion in ..."

### ISSUE THREAD

**Issue by christophbee** [magento/magento2#10256]
We run a plugin of Rocket Web that provides product data as a .csv for Google Shopping Feed (https://xtensiongalaxy.com/rocket-shopping-feeds-for-magento2.html). I create this Issue because support of Rocket Web already checked the error and told me that this error is caused by our magento installation. We already made the latest magento updates and completely reinstalled the plugin. Error occurs not when creating a new feed and saving settings then. Only when settings are changed afterwards.

### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. Enter plugin settings under "Products" --> "Feeds Management"
2. Choose an **existing** feed setup, change settings and click "SAVE"

### Expected result
1. Enter plugin settings under "Products" --> "Feeds Management"
2. Choose an existing feed setup, change settings and click "SAVE"
3. Settings are being saved

### Actual result
1. Enter plugin settings under "Products" --> "Feeds Management"
2. Choose an existing feed setup, change settings and click "SAVE"
3. There was an error processing your request! Notice: Array to string conversion in [magento-root]/vendor/magento/zendframework1/library/Zend/Json.php on line 76

**Comment by magento-engcom-team** [comment]
@christophbee The GitHub issue tracker is intended for Magento Core technical issues only. Please contact appropriate extension vendors with issues regarding third-party extensions.
