### ISSUE TITLE
Default values for system config of type image/file is not working

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#10252]
This is a clone of https://github.com/magento/magento2/pull/5085 that was closed because of a deleted repository.

### Preconditions

1. Install Magento from `develop` branch 

### Steps to reproduce

1. Add config field with type `image`.
2. Add default config value for that field.
3. Save the config field without uploading a new file.

### Expected result

1. New record created in the database table `core_config_data` with default value.

### Actual result

1. New record created in the database table `core_config_data` with value NULL.

If you set a default value for a config field type image/file and you save it. It won't set the default value in the database. Instead it will save NULL and so overwrite the default config.

With this change the default value will be set as value.

**Comment by orlangur** [comment]
Seems like this can be closed now. Thanks for the fix!

**Comment by AntonEvers** [comment]
@orlangur you are right. Thanks for handling this ticket fast.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70764
