### ISSUE TITLE
Product Attributes - Size 0

### ISSUE THREAD

**Issue by mcnamee** [magento/magento2#10266]
### Preconditions

1. Magento ver. 2.1.7

### Steps to reproduce

1. Add new product attribute called 'Size'
2. `Catalog Input Type for Store Owner` : `Text Swatch`
3. Try adding a size of `0` (zero) in the `Admin` column

### Expected result

1. A size 0 (eg. the size of clothing for babies) should be available as an attribute option

### Actual result

1. Returns error of `Admin is a required field in the each row`

**Comment by korostii** [comment]
See also #9619

**Comment by okorshenko** [comment]
Fix for 2.1-develop: MAGETWO-70838

**Comment by okorshenko** [comment]
Fix for develop: MAGETWO-66160

**Comment by mcnamee** [comment]
I created an extension with the code shown in the pull request, and it has worked.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70838
