### ISSUE TITLE
Layered Navigation: Configurable product price filter

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#10267]
### Preconditions

1. Magento 2.1.6

### Steps to reproduce

1. Configurable Product with multiple variants and prices from 49$ to 199$
2. Within the Layered Navigation there are price steps each 50$

### Expected result

1. The Configurable Product should be displayed on each price-filter there is a simple product within range.

### Actual result

1. The Configurable is only selectable within the highest applicable price range 150$ -> 200$, but there are also simple products within the cheaper range of 0-50 or 100-150.

Is it the Magento default behavior to select the most expensive simple product for the price filter?
If so, where am I able to change it to choose the cheapest one, or display the configurable on every price range there is a simple product for.

Thank you!

**Comment by RomanKrut** [comment]
@lfritsche Hi. Thanks for reporting this issue. I was tried to reproduce it, and in my case Layered Navigation take the lowest price from Configurable product and it`s work correctly.
![screenshot_4](https://user-images.githubusercontent.com/27814479/28574082-7de8b67e-7155-11e7-8196-bc1ffd289c9d.png)
![screenshot_5](https://user-images.githubusercontent.com/27814479/28574083-7e23fd7e-7155-11e7-986c-be20333c76b1.png)

**Comment by lfritsche** [comment]
Thank you for your response @krutkoroma79911 
Could my issue be related to using special prices? 
Due to the fact, that I'm using only special prices in my shop and also disabled the normal price attribute to be filtered in the layered navigation and replaced it with the special_price attribute filter, I haven't compared it to the normal price filter.

I now enabled the normal price filter and there it selects the cheapest price, as you are saying.
But trying the same on the special price filter, the issue persists.

Could you check if you can reproduce this?

Thank you :D

**Comment by RomanKrut** [comment]
@lfritsche Thank you for your response. I check the Special price filter with Configurable product, and in my case it works little differently. After creating Simple product and Configurable with special prices i have this issue and the Internal ticket was created to address this issue MAGETWO-71026.

**Comment by magento-engcom-team** [comment]
@lfritsche, thank you for your report.
The issue is already fixed in develop branch, 2.1.9

**Comment by alinasrullahkhan** [comment]
I am having the same issue on version 2.1.6. It would be great if anyone can share the code patch so i can apply and the the filter working.

Thanks

**Comment by raulsinapsis** [comment]
Any commit to fix this in 2.2.* version?

**Comment by magento-engcom-team** [comment]
Hi @lfritsche. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24730` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
