### ISSUE TITLE
Adminhtml css property `col-date` has a lack of width

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1026]
![m1250](https://cloud.githubusercontent.com/assets/813985/6091715/f95bd7c2-aec1-11e4-8fb4-c941c4994775.png)

**Comment by villageseo** [comment]
Hi Mackovey! 

Thank you for your contribution! 

The current solution was implemented for design accuracy requirements for all grid tables. In future we are going to correct the grid tables implementation. 

Thanks again, 
Oleg

**Comment by vpelipenko** [comment]
We are going to work on enhanced data grids in the nearest future and probably current implementation will be completely changed. Thank you again for pointing this issue, we will consider it.
