### ISSUE TITLE
Theme set option not available in admin configuration

### ISSUE THREAD

**Issue by gzchauhan** [magento/magento2#10269]
### Preconditions

1. install latest magento 2.1.7

### Steps to reproduce

1. Store -> Configuration -> General -> Design

### Expected result

1. Not found theme select option

### Actual result

1. Theme set option should be thare.

**Comment by orlangur** [comment]
It was moved to another place https://magento.stackexchange.com/a/122652

Shortcut to the new place from old config section wouldn't hurt though :)

**Comment by Ctucker9233** [comment]
Or change the name to something other than design to avoid the confusion.

**Comment by orlangur** [comment]
@Ctucker9233 then bug report would be "Design section is missing in System Configuration" :D The best option as to me is to add a note in place of old section with active link to a new place.
