### ISSUE TITLE
Can't add new subctegory

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1027]
Can't add new subctegory
(Button `save`doesn't have any reaction after the javascript error appeared)

![m1256](https://cloud.githubusercontent.com/assets/813985/6096237/514d4d12-af8f-11e4-8ad5-ee6080de60eb.png)

**Comment by kokoc** [comment]
@Mackovey Thank you for reporting the issue.
Internal reference - MAGETWO-33893

**Comment by mahesh004** [comment]
I am also having same issue.

**Comment by vpelipenko** [comment]
@Mackovey, @mahesh004, this issues is fixed and already available. Please, take the latest code base and check it again.

**Comment by anjenehm** [comment]
i have the same issue 
downloaded today from github https://github.com/magento/magento2/archive/develop.zip

save button to creat products or something else have no function
