### ISSUE TITLE
Magento_Amqp error when setup:install

### ISSUE THREAD

**Issue by valugi** [magento/magento2#10272]
I am installing Magento 2 EE from command line:

> /usr/bin/php /var/www/store-local//bin/magento setup:install --admin-firstname=Max --admin-lastname=Eisenhardt --admin-email=magento@test.com--admin-user=magento --admin-password='securePassword' --base-url='https://my.site' --backend-frontname=admin --db-host=localhost --db-name=magento2 --db-user=root --db-password='db.password' --session-save=db --timezone='Europe/Zurich' --use-secure='1' --base-url-secure='https://my.site' --use-secure-admin=1

My install does not do configure RabbitMq.  I do get the following error on Task 190:
> [Progress: 190 / 725]
Module 'Magento_Amqp':
Running schema recurring...
                                                                                                                                   
> [Exception]                                                                                                                      
  Warning: stream_socket_client(): unable to connect to tcp://: (Failed to parse address ":") in /var/www/store-local/vendor/php-  
  amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 101      

I get the source from composer at 2.1.* version and this worked lastly with 2.1.7. Any suggestions?

**Comment by orlangur** [comment]
> Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Community Edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by valugi** [comment]
ok. Thanks

**Comment by erikhansen** [comment]
For the record, I ran into a similar error and resolved it by changing the `app/etc/env.php` file to change this:

```
  'queue' => 
  array (
    'amqp' => 
    array (
      'host' => '',
      'port' => '',
      'user' => '',
      'password' => '',
      'virtualhost' => '/',
      'ssl' => '',
    ),
  ),
```

to this:

```
  'queue' => 
  array (
  ),
```

I did this since I was not using AMQP.
