### ISSUE TITLE
Admin login suddenly stopped working

### ISSUE THREAD

**Issue by rzinnatullin** [magento/magento2#10284]
### Preconditions
1. Magento 2.1.7
2. Ubuntu 16.04.1
3. PHP 7.0.15
4. Apache 2.4.18
5. MySql 5.7.18

### Steps to reproduce
1. Go to `http://hostname/magento/admin`
2. Enter admin's credentials
3. Click Sign In

### Expected result
1. Should open admin dashboard

### Actual result
1. Stays in the login page w/o any error message

This happens only on concrete browser instance (the browser is Firefox). Login page works find on any other Firefox running on a different machine.
I tried restoring Magento database from scratch. Run commands like `setup:upgrade`, `setup:di:compile`, `setup:static-content:deploy` and etc. Nothing helped.

It's interesting that the issue is reproducible on a specific browser instance. I noticed that login URL changes from instance to instance.
This URL doesn't work:
`http://<hostname>/magento/admin/admin/index/index/key/ecafe9019e727b7dbdb8223de34a5151ae5ad8af9b3151304c1ae792a3cbe997/`

However, for example, this URL works:
`http://<hostname>/magento/admin/admin/index/index/key/d1a5d73c4ab6e785ecf7a17ca979ed0e7ebf4231f8937a1d640c4f0c46c92a81/`

As I understand, the problem lays around that key.
The problem is that when I enter `http://<hostname>/magento/admin` it automatically redirects me to the URL that ends with `/key/ecafe9019e727b7dbdb8223de34a5151ae5ad8af9b3151304c1ae792a3cbe997/`
Even if I enter full URL (that includes another key) it redirects me to the URL with previous key.

In network console of Firefox I can see that Magento responds with code `302 Found`:
![image](https://user-images.githubusercontent.com/11244866/28354907-5c917172-6c6a-11e7-91f2-6128d38166e3.png)

![image](https://user-images.githubusercontent.com/11244866/28354859-33480f1a-6c6a-11e7-8738-7838d166cda0.png)

I cleared the browser's history (including cookies), the key is changed and then I was able to login.
I don't know how to reproduce the issue, but I guess Magento 2 developers can reproduce it. And fix?

And yes - since I develop Magento 2 extension I frequently restore Magento database, run setup commands and so on.

**Comment by korostii** [comment]
This is an old known issue. Basically, the cookies don't get stored because the host name you use on your local machine is considered invalid.

The host name _must_ have at least one `.`(dot) in it. 
Try using `magento.dev` or similar as your local host instead - that should resolve your issue.

See [this article](https://www.yireo.com/tutorials/magento/magento-administration/651-unable-to-login-into-the-magento-backend) for more details.

**Comment by magento-engcom-team** [comment]
Hi @rzinnatullin
@korostii's suggestion is correct in this case. Please use hostname with a dot.
