### ISSUE TITLE
Invalid block type : First time run admin panel after installtion without index.php in url

### ISSUE THREAD

**Issue by rvpatel** [magento/magento2#1028]
I have setup in magento xampp on localhost when i have run first time generate this error.

a:4:{i:0;s:46:"Invalid block type: Magento\Backend\Block\Menu";i:1;s:2975:"#0 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Layout\Generator\Block.php(155): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\\Backend...', Array)
#1 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Layout\Generator\Block.php(134): Magento\Framework\View\Layout\Generator\Block->createBlock('Magento\\Backend...', 'menu', Array)
#2 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Layout\Generator\Block.php(86): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'menu')
#3 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Layout\GeneratorPool.php(64): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#4 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Layout.php(291): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#5 C:\xampp\htdocs\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(198): Magento\Framework\View\Layout->generateElements()
#6 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Layout\Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#7 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Page\Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#8 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Layout\Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#9 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Page\Config.php(148): Magento\Framework\View\Layout\Builder->build()
#10 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Page\Config.php(160): Magento\Framework\View\Page\Config->build()
#11 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Result\Page.php(225): Magento\Framework\View\Page\Config->publicBuild()
#12 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\View\Result\Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http))
#13 C:\xampp\htdocs\magento2\var\generation\Magento\Backend\Model\View\Result\Page\Interceptor.php(289): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http))
#14 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\App\Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http))
#15 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\App\Bootstrap.php(245): Magento\Framework\App\Http->launch()
#16 C:\xampp\htdocs\magento2\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#17 {main}";s:3:"url";s:16:"/magento2/admin/";s:11:"script_name";s:19:"/magento2/index.php";}

**Comment by anupdugar** [comment]
@rvpatel Thanks for reporting the issue..
If you previously installed Magento 2 using XAMPP, can you try clearing the contents of var/cache and var/generation.
Am assuming you followed steps from http://devdocs.magento.com/guides/v1.0/install-gde/install/pre-install.html to setup and install Magento.
What version of XAMPP are you using?
Also, feel free to share additional steps, if any, that may help us reproduce/debug the issue further.

**Comment by anupdugar** [comment]
@rvpatel Any updates on this?

**Comment by anupdugar** [comment]
@rvpatel Closing this since we haven't heard back on this. Feel free to open a new issue if you have any questions or concerns. Thanks again for reporting it.
