### ISSUE TITLE
Creation of shipments does not update the order update_date

### ISSUE THREAD

**Issue by bertonha** [magento/magento2#10287]
### Preconditions
1. Magento 2.1.7 running on docker php:7.0-apache
2. MySQL 5.6.23 also docker

### Steps to reproduce
1. Create a order, with multiple items
2. Create the invoice
3. Create a parcial shipment

### Expected result
1. the update_date of the order should be the same time when you create a shipment

### Actual result
1. update_date of the order does not change

**Comment by orlangur** [comment]
Did such behavior exist in Magento 1? Invoice, order, shipment are different entities thus I'm not sure expected behavior is reasonable.

**Comment by bertonha** [comment]
About Magento 1 I am not sure, but in my point of view if you create a shipment or an invoice, it should progress the order one step further to completion. In a perfect business case scenario, order is the parent and other instances like shipments and invoices are the children. When a child is updated the parent should retrieve this information and perform an update as well, at least on a field that has a a date field, in this case - 'update_date'.

**Comment by magento-engcom-team** [comment]
@bertonha, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
