### ISSUE TITLE
USPS Shipping Rates to Canada not showing.

### ISSUE THREAD

**Issue by iamkerly** [magento/magento2#10283]
[2017-07-19 06:33:35] main.DEBUG: array (
  'request' => '<?xml version="1.0" encoding="UTF-8"?>
<IntlRateV2Request USERID="****"><Revision>2</Revision><Package ID="0"><Pounds>5</Pounds><Ounces>1.7008</Ounces><MailType>All</MailType><ValueOfContents>158.55</ValueOfContents><Country>Canada</Country><Container>VARIABLE</Container><Size>REGULAR</Size><Width/><Length/><Height/><Girth/></Package></IntlRateV2Request>
',
  'result' => '<?xml version="1.0" encoding="UTF-8"?>
<IntlRateV2Response><Package ID="0"><Prohibitions>An issue of a publication in which more than 5 percent of its total advertising space is primarily directed to a Canadian market and which indicates:
(a) Specifically where goods or services may be obtained in Canada, or 
(b) Specific items or conditions relating to the sale or provision of goods or services in Canada. 
All alcoholic beverages including wines, etc.
An issue of a publication that contains an advertisement primarily directed to a Canadian market is a prohibited import if that advertisement does not appear in identical form in all editions of the issue distributed in the country of origin.
Articles so marked as to create the false impression that they were made in Canada, Great Britain or any other British country.
Commercial tags of metal.
Firearms, except as follows: Firearms may be mailed to Canada provided that they meet the requirements in DMM 601.11.1, 601.11.2, 601.11.3, and 601.11.6 and that the importer has the required documentation. Customers must visit http://cbsa-asfc.gc.ca/publications/pub/bsf5044-eng.html prior to mailing for Canadian import requirements.
Gold bullion, gold dust, and nonmanufactured precious metals.
Non-refillable lighters or any other lighter that contains fuel. New lighters with no fuel may be sent.
Oleomargarine and other butter substitutes, including altered or renovated butter.
Perishable infectious biological substances.
Perishable noninfectious biological substances.
Plumage and skins of wild birds.
Prison-made goods being sold or intended for sale by a person or firm.
Radioactive materials.
Replica or inert munitions, as well as other devices that simulate explosive devices or munitions, including replica or inert grenades or other simulated military munitions, whether or not such items are for display purposes.
Reprints of Canadian or British works copyrighted in Canada.
Reproductions of Canadian postage stamps unless printed in publications in black and white only and with a defacing line drawn across each reproduction.
Shipments bearing caution labels indicating the contents are flammable.
Smoke-making devices for motor vehicles and boats.
Used or secondhand hives or bee supplies.</Prohibitions><Restrictions>Coins; banknotes; currency notes; securities payable to bearer; traveler\'s checks; gold, silver, platinum, manufactured or not; jewelry; and other valuable articles may be sent only in registered items. 
Exceptions:
Coins sent to or from collectors or dealers may be mailed in ordinary (uninsured) parcels.
Drugs and medicines must comply with Canadian law.
Eggs for hatching must be packed in new, clean containers and accompanied by a certificate issued by a veterinarian of the U.S. Department of Agriculture, or one issued by a State veterinarian and endorsed by a veterinarian of that Bureau, stating that to the best of his or her knowledge the eggs come from a flock that is free from Newcastle disease, fowl pest, or fowl typhoid. See 135.3 for method of packing.
Meat and meat food products must be accompanied by an export certificate issued by the U.S. Department of Agriculture and labeled in accordance with Canadian regulations. Exception to these requirements are:
1. bona fide sample shipments weighing less than 10 kg; 
2. meat products addressed to a government department or agency; 
3. meat products intended for personal consumption when they enter Canada in the possession of the importer. 
Precious stones, set or not set; all items used as dress ornaments and coming under the term "jewelry" including articles of gold or other precious metal for personal use such as cigarette holders, cases, powder cases, card cases, opera glasses, fountain pens, watches, etc., are permitted in insured parcels provided the articles have value not over $5 U.S. A parcel containing a number of such articles valued at $5 or less may be insured for the total value of the contents up to a maximum of $200.
Veterinary biological products including serums and vaccines must be accompanied by a permit issued by the Veterinary Director General, Ministry of Agriculture of Canada.</Restrictions><Observations>1. Electronic smoking products (i.e., electronic products for the vaporization and administration of inhaled doses of nicotine including electronic cigarettes, cigars, cigarillos, and pipes, as well as cartridges of nicotine solutions and related products) require market authorization by Department of Health Canada prior to being imported. Failure to obtain this authorization will result in the items being refused entry by Canada Border Services Agency (CBSA). For additional information, refer to the Department of Health Canada website at http://www.hc-sc.gc.ca/dhp-mps/prodpharma/applic-demande/pol/notice_avis_e-cig-eng.php.
2. Banknotes valued at $100 or more must be put up in a compact package and securely tied with strong twine before wrapping. The wrapper must be linen or other strong, woven material, linen lined paper, or two thicknesses of strong kraft paper. After wrapping, the package must be again securely tied or stitched and sealed at the points of closing. 
3. The name of the Canadian province in which the office of destination is located must appear as part of the address. 
4. The following must not be accepted for insurance: 
Bees, postage stamps (canceled and uncanceled) and albums in which they are mounted, and parcels addressed to CFPOs. 
5. Canadian Forces Mail (CFPO) is processed through Canadian military post offices and must be addressed in the following manner: 
(a) NUMBER, RANK, NAME UNIT 
(b) CFPO (NUMBER) 
(c) BELLEVILLE ON K0K 3R0 
(d) CANADA 
Maximum weight limits for mail addressed to members of the Canadian Forces based outside of Canada (CFPO) is 22 pounds. Parcels for CFPO addresses may not be insured. Direct sacks of printed matter (M-bags) are not permitted for CFPO addresses.
6. A letter fully prepaid and bearing the same address as that of a parcel may be tied or otherwise securely attached to the outside of the parcel. Stamps to cover postage on the parcel must be affixed to the wrapper of the parcel. Stamps to pay postage on the letter must be affixed to the envelope thereof. 
7. Certain types of merchandise must be marked to show country of origin in the manner prescribed by the Canadian customs regulations. 
8. Goods valued under 20 Canadian dollars are duty and excise tax exempt. Goods over 20 Canadian dollars will be subject to the applicable duties and excise taxes. Gift shipments received by mail that are valued under 60 Canadian dollars are duty and excise tax exempt. 
9. For all casual and commercial goods valued at or under 1,600 Canadian dollars, Canada Post will collect assessed duties, excise taxes, and a handling fee from the addressee.  This handling fee is set by Canada Post (see http://www.canadapost.ca/tools/pg/manual/PGcustoms-e.asp). All commercial mail items over 1,600 Canadian dollars will be held by Canada Customs and Excise until proper invoice and accounting documentation is provided by the addressee.
10. The Canada Customs Invoice can be obtained from stationery, office supply, or printing companies. If mailers are unable to obtain the Canada Customs Invoice locally, they should visit the following Web site: www.canadapost.ca. In addition, commercial invoices are acceptable provided that each invoice has the required information for customs purposes. 
11. Information on Canadian customs regulations may be obtained from the Office of International Marketing/223, Bureau of International Commerce, Department of Commerce, Washington, DC 20230, or any field office of that Department. 
Obtaining post code information: 
12. Information on Canadian post code directories can be obtained from: 
(a) NATIONAL PHILATELIC CENTER
CANADA POST CORPORATION 
STATION 1 
ANTIGONISH NS B2G 2R8 
Telephone: 1-800-565-4362 
Fax: 1-902-863-6796
(b) To obtain Canadian post codes for specific addresses, call the General Information line at 1-416-979-8822 or access the Canada Post Corporation web site on the Internet at http://www.canadapost.ca. 
13. Pursuant to the Canada Customs Act and a need to heighten border security, Canada will deny entry of all postal items (except postcards) that do not bear complete sender and addressee information in roman letters and arabic numerals. </Observations><CustomsForms>First-Class Mail International items and Priority Mail International Flat Rate Envelopes and Small Flat Rate Boxes: 
PS Form 2976 (see 123.61)
Priority Mail International parcels:
PS Form 2976-A inside 2976-E (envelope)</CustomsForms><ExpressMail>Country Code:
CA

Reciprocal Service Name: 
There is no reciprocal service. 

Required Customs Form/Endorsement
1. Business papers and commercial documents.
PS Form 2976-B placed inside PS Form 2976-E (plastic envelope).
 
2. Merchandise samples and gift shipments (non-commercial parcels). 
PS Form 2976-B placed inside PS Form 2976-E (plastic envelope). 
 
3. Merchandise (commercial shipments) and all articles subject to customs duty. 
PS Form 2976-B placed inside PS Form 2976-E (plastic envelope).
 

Notes:
1. Gift shipments (non-commercial parcels) require a sales receipt, invoice or other documentation to support the declared value. 
2. Coins; banknotes; currency notes, including paper money; securities of any kind payable to bearer; traveler\'s checks; platinum, gold, and silver; precious stones; jewelry; watches; and other valuable articles are prohibited in Priority Mail Express International shipments to Canada. 
3. Priority Mail Express International shipments may have a street address or a post office box address. A local telephone number for the addressee MUST be provided for shipments addressed to a post office box address. A local telephone number for the addressee should be provided if possible for shipments to a street address. 

Areas Served: All</ExpressMail><AreasServed>Please reference Express Mail for Areas Served.</AreasServed><AdditionalRestrictions>No Additional Restrictions Data found.</AdditionalRestrictions><Service ID="12"><Pounds>5</Pounds><Ounces>1.7008</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>CANADA</Country><Postage>99.25</Postage><ExtraServices><ExtraService><ServiceID>106</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>1.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService></ExtraServices><ValueOfContents>158.55</ValueOfContents><SvcCommitments>1 - 3 business days to many major markets</SvcCommitments><SvcDescription>USPS GXG&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt; Envelopes</SvcDescription><MaxDimensions>USPS-Produced regular size cardboard envelope (12-1/2" x 9-1/2"), the legal-sized cardboard envelope (15" x 9-1/2") and the GXG Tyvek envelope (15-1/2" x 12-1/2")</MaxDimensions><MaxWeight>70</MaxWeight></Service><Service ID="1"><Pounds>5</Pounds><Ounces>1.7008</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>CANADA</Country><Postage>68.50</Postage><ExtraServices><ExtraService><ServiceID>107</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService></ExtraServices><ValueOfContents>158.55</ValueOfContents><SvcCommitments>3 - 5 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail Express International&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt;</SvcDescription><MaxDimensions>Max. length 42", max. length plus girth combined 79"</MaxDimensions><MaxWeight>66</MaxWeight></Service><Service ID="11"><Pounds>5</Pounds><Ounces>1.7008</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>CANADA</Country><Postage>59.95</Postage><ExtraServices><ExtraService><ServiceID>108</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService><ExtraService><ServiceID>105</ServiceID><ServiceName>Return Receipt</ServiceName><Available>True</Available><Price>3.85</Price></ExtraService></ExtraServices><ValueOfContents>158.55</ValueOfContents><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Large Flat Rate Box</SvcDescription><MaxDimensions>USPS-Produced Box: 23-11/16" x 11-3/4" x 3" or 12" x 12" x 5-1/2"&lt;br>Maximum weight 20 pounds.</MaxDimensions><MaxWeight>20</MaxWeight></Service><Service ID="9"><Pounds>5</Pounds><Ounces>1.7008</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>CANADA</Country><Postage>45.95</Postage><ExtraServices><ExtraService><ServiceID>108</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService><ExtraService><ServiceID>105</ServiceID><ServiceName>Return Receipt</ServiceName><Available>True</Available><Price>3.85</Price></ExtraService></ExtraServices><ValueOfContents>158.55</ValueOfContents><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Medium Flat Rate Box</SvcDescription><MaxDimensions>USPS-Produced Box: 13-5/8" x 11-7/8" x 3-3/8" or 11" x 8-1/2" x 5-1/2"&lt;br>Maximum weight 20 pounds.</MaxDimensions><MaxWeight>20</MaxWeight></Service><Service ID="2"><Pounds>5</Pounds><Ounces>1.7008</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>CANADA</Country><Postage>0.00</Postage><ExtraServices><ExtraService><ServiceID/><ServiceName/><Available>False</Available><Price/></ExtraService></ExtraServices><ServiceErrors><ServiceError><Id>50050</Id><Description>The Origin ZIP Code and the Destination Postal Code is required for ECOMPRO when mailing to Canada.</Description></ServiceError></ServiceErrors></Service></Package></IntlRateV2Response>',
) {"is_exception":false} []

**Comment by YevSent** [comment]
Hi, @iamkerly, please, follow to [issue reporting guideline](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

Also, I've checked USPS integration on Magento 2.1.7 version, the rates for Canada are available. Please, update attached `debug.log` with request details and format the response because posted XML is broken and unreadable.
