### ISSUE TITLE
Configurable Products Checkout Issue

### ISSUE THREAD

**Issue by pankajok** [magento/magento2#10294]
### Preconditions

1. Magento ver. 2.1.2
2. Browser: Any
3. Hosted on Nexcess

### Steps to reproduce

1. Create Any configurable product like in my case: Software 1 user, 3 users.
2. I can add the desired product to cart, but when i click on "Place Order Now" its doesnt redirect to payment gateway page.  
3. Example: https://www.letsgocart.com/gdata-internet-security.html 
4. Also "One Page Checkout" page doesn't show address details.
5. But If I add any simple product along with configurable product, then everything works fine. 

### Expected result

1. Clicking on "Place Order now" should open payment gateway page.
2. Cart should show customer address column etc in proper format.

### Actual result

1. [Screenshot, logs] : ISSUE
![image](https://user-images.githubusercontent.com/30312019/28415737-9e98e1e0-6d6e-11e7-94cb-4c44b145bdae.png)

2. AFTER ADDING SIMPLE PRODUCT
![image](https://user-images.githubusercontent.com/30312019/28415818-025f402a-6d6f-11e7-95d1-7a7f5bbbdbc3.png)

**Comment by mvalenziano** [comment]
I found the problem. When you create a configurable product, for some reason, magento consider all the children as virtual products. If you try to edit all the child products adding a weight ( for example 1 lbs ) you will see the shipping form.

**Comment by magento-engcom-team** [comment]
@pankajok @mvalenziano Products which have no weight are consider virtual and may not counted towards shipping. If all products in the cart are virtual – shipping step on checkout is not visible. This is a standard Magento behavior.

**Comment by mvalenziano** [comment]
Hi, i know that. The issue begin in that case scenario:
1. product with weight 
2. move that product to configurable using the wizard 
3. result -> all the child products of the configurable don't have the weight as the parent has

**Comment by pankajok** [comment]
Thank you guys for identifying the issue and suggesting solution. 
I hope Magento also listening and correct the issue. 

For now I wouldn't try to add the weight to child products, as as soon as I Refresh Cache, my site & Magento panel crashes; and I need to restore from backup. :D 
As way around I created another product Named "Quick Delivery" with zero price, no weight and added to Configurable products as Bundle with default qty as 1. Then everything goes smooth. 
Example: https://www.letsgocart.com/g-data-antivirus.html

And for last 2 months I am not clearing the cache. On debug i found the error:

_[ReflectionException]
Class Magento\Ccavenuepay\Helper\Hss does not exist
This looks to be related to this module: https://www.magentocommerce.com/magento-connect/ccavenue-payment-gateway-1.html__

But CCAvenue Payment Gateway developers say, that its not their issue. And something to do with Magento. 
May be If you may guide me on this too. 

Thanks in advance.

**Comment by magento-engcom-team** [comment]
> May be If you may guide me on this too.

We can not provide any guidance on third-party modules. Please contact their vendors for support.
