### ISSUE TITLE
Changing language on a product twice gives error: Requested store is not found

### ISSUE THREAD

**Issue by EthicalErik** [magento/magento2#10299]
### Summary 
If you change the language twice in a store this system won't redirect you back to the right store. Instead it gives a server error with the message: Requested store is not found

(However This only happends on a product page. On the homepage this does not happen)

### Preconditions
1.  Magento 2.1.7
2.  Multiple store views on one store

### Steps to reproduce
1.  Setup 1 store with two store views
2.  Go to the website
3. Go to a product
4.  Change the language
5. Change the language again.
6. The error will display now

### Expected result
1.  Just change back to the previous store view

### Actual result
1. Server error: Requested store is not found
Gif showing the problem : https://cl.ly/3c2h2C0E3v1Q

**Comment by RomanKrut** [comment]
@erik921 Thanks for reporting this issue. Unfortunately, I could not reproduce the issue as you described it. Can you try to reproduce it on default theme and using clean instance? And also tell us, is your instance upgraded from previous version?

**Comment by johnny-longneck** [comment]
I can confirm this. Exact same behaviour after upgrading from 2.1.3 to 2.1.7
I expect Magento has made some changes in 
\Magento\Store\Model\StoreManagerInterface $storeManager

**Comment by EthicalErik** [comment]
We upgraded from 2.1.2 all the way up to 2.1.7

**Comment by johnny-longneck** [comment]
I have a custom Website Switcher Module which uses the storeManager to get the current url.
My temporary workaround for this, is to set $fromStore parameter to false, so the links are actually correct again. 
$storeManager->getCurrentUrl($fromStore = false).

You can adapt this to the basic switcher, too - I guess. 
I just wonder, why no one else is yelling that this is an issue.

**Comment by magento-engcom-team** [comment]
We are closing this issue because we cannot reproduce this issue as described. If you have questions, please refer to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.
