### ISSUE TITLE
Question about the session cookie: proper way to set the "secure" flag

### ISSUE THREAD

**Issue by enrico69** [magento/magento2#10290]
### Preconditions
1. In the back-office of Magento 2, there is an option enabling to set the HTTP Only flag to the session cookie. However, I didn't find one to set the secure flag

However this seems to be handled, as we can see the below code in __Framework\Session\Config.php__ : 

>
>/**
>     * Set session.cookie_secure
>     *
>     * @param bool $cookieSecure
>     * @return $this
>     */
>    public function setCookieSecure($cookieSecure)
>    {
>        $this->setOption('session.cookie_secure', (bool)$cookieSecure);
>        return $this;
>    }
>

Is there and option to enable it from the back-office? If not, what would be the proper way to add this one?

**Comment by orlangur** [comment]
There is no option for that, if you grep all over the code you may notice this flag is already used when reasonable:

```
$this->setCookieSecure($this->_httpRequest->isSecure());
```

```
$secureURL = $this->_scopeConfig->getValue('web/secure/base_url', $this->_scopeType);
$unsecureURL = $this->_scopeConfig->getValue('web/unsecure/base_url', $this->_scopeType);
$isFullySecuredURL = $secureURL == $unsecureURL;
$this->setCookieSecure($isFullySecuredURL && $this->_httpRequest->isSecure());
```

Setting `session.cookie_secure` for more cases may lead to https://stackoverflow.com/a/25047234 

I'm not sure why HTTP Only is an option in UI and not always enabled...

**Comment by enrico69** [comment]
` $isFullySecuredURL = $secureURL == $unsecureURL;`
` $this->setCookieSecure($isFullySecuredURL && $this->_httpRequest->isSecure())`

> I'm not sure why HTTP Only is an option in UI and not always enabled...

I agree but why would we not be able to force if from the UI, giving the admin user the total control over it?

I propose to add this option juste below the "Use HTTP only" one?

**Comment by orlangur** [comment]
@enrico69 it's already forced everywhere when applicable (according to my understanding).

From the link I posted:
> If you're using HTTP, you won't get any cookies from the server. That's why you don't have a session.

You can try to hardcode `setCookieSecure(true)` and see if it still works in HTTP or mixed mode.

**Comment by magento-engcom-team** [comment]
@enrico69 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by alextricity** [comment]
The inability to conveniently control security settings for an E-COMMERCE site is an issue in many environments...

**Comment by Supplement** [comment]
I've put in a ticket with magento but is there any updates here on getting the secure check on the browser side. I'm running https on both the frontend and backend.

**Comment by TdAmi** [comment]
After many search, I've found a solution.

In the Admin panel, go to **STORES > Configuration > General > Web** and just configure your "**Base URL**" and "**Secure Base URL**" with https.

I found by reading these lines in Magento\Framework\Session\Config : 
`$isFullySecuredURL = $secureURL == $unsecureURL;
$this->setCookieSecure($isFullySecuredURL && $this->_httpRequest->isSecure());`
