### ISSUE TITLE
Upgrade fro 2.1.6 to 2.1.7 site broke

### ISSUE THREAD

**Issue by jobsmartdesigner1507** [magento/magento2#10295]
Im not super familiar with Magento, so I would really appreciate any help that you can provide

### Preconditions

1. Magento 2.1.6
2.  PHP Version 5.6.30  

### Steps to reproduce

1. I think the site is trying to auto update
2. There is also a third party plugin that I was trying to install that my boss needed to run some code for to get it active but we were never able to do that bc the site went down

### Expected result

1. Site should update to Magento 2.1.7

### Actual result

1. but it doesnt

Warning: ltrim() expects parameter 1 to be string, object given in /home/wworks/public_html/store/vendor/magento/framework/Code/Generator/EntityAbstract.php on line 152

Notice: Uninitialized string offset: 0 in /home/wworks/public_html/store/vendor/magento/framework/Autoload/ClassLoaderWrapper.php on line 81

Notice: Uninitialized string offset: 0 in /home/wworks/public_html/store/vendor/composer/ClassLoader.php on line 375
An error has happened during application run. See exception log for details.

Site is currently back up bc my boss did a restore from backup, but its still needs to be upgraded and I am sure that we are going to get this issue again if we try to upgrade it

This is the most recent log:

text/x-generic 538679168928 ( ASCII text )

a:4:{i:0;s:25:"Cannot initialize product";i:1;s:9275:"#0 /home/wworks/public_html/store/vendor/magento/framework/App/Action/Action.php(102): Magento\Review\Controller\Product\ListAjax->execute()
#1 /home/wworks/public_html/store/vendor/magento/module-review/Controller/Product.php(169): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#2 /home/wworks/public_html/store/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Review\Controller\Product->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Review\Controller\Product\ListAjax\Interceptor->___callParent('dispatch', Array)
#4 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Review\\...', 'dispatch', Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Array, 'contextPlugin')
#5 /home/wworks/public_html/store/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Review\\...', 'dispatch', Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Array, 'storeCheck')
#8 /home/wworks/public_html/store/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Review\\...', 'dispatch', Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Array, 'customer-app-ac...')
#11 /home/wworks/public_html/store/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Review\\...', 'dispatch', Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Array, 'tax-app-action-...')
#14 /home/wworks/public_html/store/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /home/wworks/public_html/store/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Review\\...', 'dispatch', Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Array, 'weee-app-action...')
#17 /home/wworks/public_html/store/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Review\Controller\Product\ListAjax\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /home/wworks/public_html/store/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Review\Controller\Product\ListAjax\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /home/wworks/public_html/store/var/generation/Magento/Review/Controller/Product/ListAjax/Interceptor.php(26): Magento\Review\Controller\Product\ListAjax\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /home/wworks/public_html/store/vendor/magento/framework/App/FrontController.php(55): Magento\Review\Controller\Product\ListAjax\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /home/wworks/public_html/store/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#24 /home/wworks/public_html/store/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#27 /home/wworks/public_html/store/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#30 /home/wworks/public_html/store/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/wworks/public_html/store/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/wworks/public_html/store/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#33 /home/wworks/public_html/store/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /home/wworks/public_html/store/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /home/wworks/public_html/store/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /home/wworks/public_html/store/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /home/wworks/public_html/store/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /home/wworks/public_html/store/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}";s:3:"url";s:39:"/store/review/product/listAjax/id/3415/";s:11:"script_name";s:16:"/store/index.php";}

**Comment by EthicalErik** [comment]
Hey,

Have you tried running the upgrade from the command line interface?
Upgrading from the website never works for me however if I do the upgrade using the command line it always works perfectly fine.

**Comment by jobsmartdesigner1507** [comment]
My boss always does the update through the command line, Ive never updated it through the website before

**Comment by jobsmartdesigner1507** [comment]
My boss said the he gets the same error when he tries to run it in the command line, not sure if that helps

**Comment by EthicalErik** [comment]
Did he do it like:

composer require magento/product-community-edition 2.1.7 --no-update
composer update
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
php bin/magento setup:di:compile
php bin/magento indexer:reindex
php bin/magento cache:flush
php bin/magento cache:clean

And the setup the permissions again

**Comment by jobsmartdesigner1507** [comment]
I dont know I will ask him

**Comment by orlangur** [comment]
Here is an example of similar problem solved by a way similar to suggested by @erik921:  https://magento.stackexchange.com/questions/142453/error-after-deleting-all-cache-in-magento-2#comment193145_142455
