### ISSUE TITLE
Newsletter Error 5.1.7 Bad address mailbox syntax.

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#10305]
### Preconditions

Magento: 2.1.6
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15
### Steps to reproduce

1. Create Nesletter queue.
2. Send Nesletter queue.
![newsletter_sent](https://user-images.githubusercontent.com/2456408/28510118-1e2abb8a-704f-11e7-9340-21405a3663d5.jpg)

3. See Newsletter Problems Report

### Expected result

1. Users received email
2. No errors in Newsletter Problems Report

### Actual result

1.Users did not receive emails.
2. There are errors is Newsletter Problems Report
![newsletter_report](https://user-images.githubusercontent.com/2456408/28510125-273f5c30-704f-11e7-9ec4-aa41fa7d7302.jpg)

**Comment by smoskaluk** [comment]
@Tonop Unfortunately, I could not reproduce the issue as you described it. Please provide the detailed steps I must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by Tonop** [comment]
@smoskaluk ,
Server version: Apache/2.2.15 (Unix)
Server built:   Nov 15 2012 15:52:50

No specific steps to reproduce, default settings. Emails are set up correctly. When order is received, email are sent. What additional info do you need else?

**Comment by magento-engcom-team** [comment]
@Tonop, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by Tonop** [comment]
Still facing the problem!
