### ISSUE TITLE
Sample data setup:upgrade should fail if "base" website does not exist

### ISSUE THREAD

**Issue by kirkmadera** [magento/magento2#10307]
### Preconditions

1. Install Magento 2.1.7 ```composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition myproject && cd myproject && 
bin/magento setup:install --db-host=localhost --db-name=myproject --db-user=dev --db-password=password1 --base-url=https://local.myproject.com/ --timezone="America/New_York" --use-rewrites=1 --use-secure=1 --base-url-secure=https://local.myproject.com/ --use-secure-admin=1 --admin-use-security-key=1 --admin-user=dev --admin-password=password1 --admin-email=dev@localhost.com --admin-firstname=Dev --admin-lastname=Dev```

### Steps to reproduce

1. Log into the admin and change your "Main Website" code from "base" to anything else
2. Run ```bin/magento sampledata:deploy && 
bin/magento setup:upgrade && 
bin/magento cache:flush```

### Expected result

1. Sample data should either install products into all websites or should error on setup:upgrade if "base" website does not exist

### Actual result

1. Sample data installs with no complaints. All configurable products are missing. The "Gear", "Training", "Gift Cards" categories populate which makes the root cause much less obvious to find.

**Comment by 1408sheva** [comment]
Hi, @kirkmadera. We've created internal ticket MAGETWO-70995 to address this issue.

**Comment by magento-engcom-team** [comment]
Hi @kirkmadera

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@kirkmadera thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
