### ISSUE TITLE
Access Restriction field not disabled when "Use Default" is checked. 

### ISSUE THREAD

**Issue by tjgamble** [magento/magento2#10308]
**Preconditions:**
**Version:** Magento 2.2.0-dev

We have a B2C site set as the default site, and have a B2B site set up as the secondary site.   

**Expected Results:**
When the "Use Default" checkbox is checked upon page load, the input should be disabled.  

**Actual Results:**
The "Use Default" checkbox is checked upon page load, but the input is not disabled.  

**Steps to reproduce**
1. Log in to the admin as an administrator role
2. Go to Stores->Configuration
3.  Select a website scope from the selector
4.  Scroll down and look under "Website Restrictions" for the input "Access Restriction".  
5.  If the "Use Default" checkbox is selected when the page loaded, the "Access Restriction" will not be disabled.   If you uncheck the "Use Default" checkbox and check it again, it will disable the input. Saving it or reloading the page will again have the "Use Default" box checked but the input not disabled.   
6.  If the "Use Default" checkbox is not selected, select it and save it. After it is saved the page reloads and the "Use Default" box is checked but the input is not disabled.  

![screencapture-b2c-jamersan-admin_11ozn0-admin-system_config-edit-section-general-website-2-key-0283e1640a907cb298a041ac848e33c78a1128a2dae6d80054bc17b62db0dd9a-1500929146543](https://user-images.githubusercontent.com/1413906/28544563-4375413c-7089-11e7-8336-6acd1fce0906.png)

**Comment by misha-kotov** [comment]
@tjgamble do you have any b2b modules installed? I could only reproduce on a b2b instance. 
Also internal issue is MAGETWO-72111

**Comment by tjgamble** [comment]
As stated in the original comment, I have a multi-site install.  The primary site has only B2C functionality configured, but the B2B modules are installed and working on the secondary site.   

So, yes, B2B modules are installed in the codebase that shows this error.

**Comment by misha-kotov** [comment]
Thanks for clarifying

**Comment by magento-engcom-team** [comment]
@tjgamble thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
