### ISSUE TITLE
Backorders not working when product is marked as "Out of Stock" (Can't add product to cart)

### ISSUE THREAD

**Issue by nikoelgatito** [magento/magento2#10304]
From the official Magento documentation both for the first edition and Magento 2 we can read the following very logical definition for **Out of Stock** products:

> **Out of Stock: Unless Backorders are activated**, prevents the product from being available for purchase and removes the listing from the catalog.

Source: http://docs.magento.com/m2/ce/user_guide/catalog/settings-advanced-advanced-inventory.html

### Preconditions

1. Magento 2.3.x
2. Edit/Create a product,
3. Set **Manage Stock** to "Yes",
4. Set **Qty** to "0",
5. Enable Backorders
6. Set **Stock Status** to "Out of Stock".

### Steps to reproduce

1. Visit the product page,
2. Add the product to cart.

### Expected result

1. The **Add to Cart** button shows and we **can** add the product to the shopping cart.

### Actual result

1. The **Add to Cart** button does not show,
2. Even after forcing the isSalable() method to return true, then refreshing the page and clicking on the Add to Cart button that is now showing, the product is not added to cart and the red "_This product is out of stock._" notification message is showing.

______________________________________________________________________________
## Remarks regarding the Add to Cart button not showing:
It seems that the isSalable() method depends more on the **In Stock** status than the real item quantity. This function should rely on real quantity for every product that has the **Manage Stock** option enabled. Solely relying on the **Stock Status** for product with real quantity is not reliable.

**The logic should be as follow:
Manage Stock = No:**
- isSalable() should return true/false based on **_Stock Status_**.

**Manage Stock = Yes:**
1. **Backorders are not allowed:** isSalable() should return true/false based on stock **_qty_** and **_threshold_**.
2. **Backorders are allowed:** isSalable() should **_always_** return true.

https://stackoverflow.com/questions/9038988/what-is-the-difference-between-issaleable-and-isavailable

______________________________________________________________________________
## Remarks regarding the product not adding to cart:

**It seems that the "magic" preventing the product to be added to cart reside in this class:**
Magento\CatalogInventory\Model\Quote\Item\QuantityValidator::validate()

**As we can see on line 103, the verification here again solely rely on Stock Status and not on the actual quantity even though Manage Stock is enabled:**

```
103 | if (!$stockItem->getIsInStock() || $parentStockItem && !$parentStockItem->getIsInStock()) {
       ...
      }
```

______________________________________________________________________________

This is unfortunate as we though backorders were well implemented in Magento and we are currently on a project for which we will have to modify the default (wrong) Magento behavior by the meantime this bug gets officially resolved and released.

# [UPDATE]

## Possible Solution:

It seems that these two small changes would correct this bug!

> **Magento\CatalogInventory\Model\Quote\Item\QuantityValidator::validate()**

```
Line 103 | - if (!$stockItem->getIsInStock() || $parentStockItem && !$parentStockItem->getIsInStock()) {
Line 103 | + if ((!$stockItem->getIsInStock() || $parentStockItem && !$parentStockItem->getIsInStock()) && !$stockItem->getBackorders()) {
```

> **Magento\CatalogInventory\Model\StockStateProvider::checkQuoteItemQty()**
```
Line 155 | - if (!$stockItem->getIsInStock()) {
Line 155 | + if (!$stockItem->getIsInStock() && !$stockItem->getBackorders()) {
```

These are making sure that the product Stock Status being out of stock has no impact if backorders are enabled. The process will then continue its nomal verification flow and the backorder notices will still be shown where applicable. It has been tested and completely working.

**Comment by smoskaluk** [comment]
@nikoelgatito Unfortunally, despite what is written in docs.magento, products with status “Out of stock” couldn’t be available for purchase. If you turned on “Backorder” function, it makes your product “In stock” even with negative qty in stock, so it remains purchasable

**Comment by nikoelgatito** [comment]
Thank you @smoskaluk for your comments,

I do understand how it is currently unlogically working. I also do understand that basically the `Stock Status` attribute was to control the availability of an item for which stocks are **not** managed. However when managing stocks this logic does not apply. An item for which a store accept backorders should always be recognized as not in stock as it is not, stocks might be on their way already or will be once an order has been placed (special order) but in any cases it should be recognized as out of stock. Most store managing stocks and backorders **will** want the threshold to switch `Stock Status` to `Out of Stock` for all products that has a qty below what they consider unavailable. Still they would like to be able to use the backorder function. The issue here is most merchant think that way because it is simply logically the way to do it but as Magento did it wrong unfortunately everyone had to adapt. What the doc says is the right way to do it and the very simple solution that is perfectly working for us is the fixed I shared above.

After all the `Stock Status` attribute could almost be nonexistent and the `isSalable()` function could simply rely on real stocks for every products that has its stocks managed. Some might say that the `Stock Status` attribute acts more as a "Force Availability" attribute than anything but this does not add up to the current Magento logic. The `backorders` attribute should be switched if one is willing to allow or disallow negative qty. In my point of view, `Stock Status` is there more as informative to the visitor than anything, it is simply an indicator, whatever the current qty is, that the merchant decides from this point on this product should be indicated as out of stock. Still if backorders are enabled it should be saleable.

Say for example that a store has an unreliable inventory, an inventory that is updating every hour with lots of stock movements. They do accept backorders but the processing delay raise up to three days instead of 1 day for in stock products. Then to better be safe than sorry, they decide that the out of stock threshold is 5 qty. This way they ensure that a customer has much less chance to perceive unforeseen extra delays. Now what happens, the qty goes to 5 qty and the product is marked as out of stock, this makes sure that all visitors are aware that this is currently out of stock (backordered) and that an additional delay is to be expected. Unfortunately, this very popular situation does not work with the current Magento implemented logic, the product won't be saleable! The only way to make it saleable would be to put it **In Stock**, "lying" to ourselves and to the visitors showing it is in stock and "hopefully" we can add a notice in the cart.

Now of course added to the fix I proposed above, a great idea would be a way to "override" the **Out of Stock** status showing on the product page for **Backordered** if backorders are enabled for this product, this would be even more transparent to the customer. This is a part of what we do with a custom extension.
____________________________________________________________________________________

At this time, my understanding is that there probably was two different developers working on this aspect of the stock management for Magento and both did go with a different approach reaching in the middle.

**This unfortunately does not work as there is a large difference between:**

1. A displayed stock status that serves as indicator to the customer.
2. The actual availability or saleability of the product.
3. The real physical qty available.

These surely should be related and are meant to influence each other but they should still be independant and a product should definitely still be saleable while showing out of stock or backorder on the frontend. A merchant should also be able to control from which qty level a product will be displayed as out of stock.

The solution # 2 below should allow for all case scenario.

____________________________________________________________________________________

# Solution # 2 (Best)
The solution I initially proposed when creating this bug report is the simplest way requiring only a few edits for achieving what most users expect from a stock management logic. There is of course a much better approach to this that would require more code change but would also allow for better understanding, flexibility and much more satisfied merchants and customers.

**The much better way to make it work keeping the actual Stock Status "almost" how it is (directly control the product saleability) would be in the case where ALL the following would apply:**
**1.** The current `Stock Status` attribute would be called "Availability" [Allow Sale/Disallow Sale] which would not relate to actual physical stocks BUT to the fact that we allow of disallow this product to be ordered. In this case it would be a "simple" way to keep a product enabled but still prevent sales.
**2.** The stock status displayed for a product would be controlled by an isInStock() that would rely both on availability and qty versus threshold. This would NOT affect the saleability of the product itself, only the stock status to be displayed on the frontend. The function logic would be the following:
```
true - `manage stock` is set to No.
true - `manage stock` is set to Yes or qty is above threshold
false - isAvailable() returns false
false - `manage stock` is set to Yes and qty is under threshold
```
**3.** In the case where isInStock() returns false but isAvalaible() returns true, isSalable() should verify if backorders are enabled and return the result. This also means that backorders logic should NOT solely be relying on qty < 0 to be taken into account.

This would mean that a product could appear out of stock if its qty is below the threshold even though availability is set to "available" and it would still be possible to order if backorders are enabled.

___________________________________________________________________________________

**For those whose requirements include a way to disallow sales when a certain threshold has been reach (as with current wrong logic), my Solution # 2 still allows it:** 
Simply setting up an out of stock threshold as usual and making sure that backorders are disabled should be enough to ensure that both isInStock() and isSalable() return false therefore making the product both showing out of stock while preventing it sales once the threshold has been reached.

**Comment by magento-engcom-team** [comment]
@nikoelgatito thank you for research. Would you like to submit pull request with your proposal?

**Comment by torlokken** [comment]
Any update on this? Still an issue in 2.2.

**Comment by magento-engcom-team** [comment]
@nikoelgatito, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by saumil171188** [comment]
Backorders are not working for me

**Comment by sebfie** [comment]
Same here !

**Comment by zuber11** [comment]
Set positive QTY(1) of product, staus should be enabled and stock should be in stock.

So for this product, ADD TO CART button will be appeared now. Place an order of this product by 1 QTY so the product will be out of stock. Now check the detail page and this time Add To Cart button will be there instead of Out Of Stock Button.

I don't why but this works for me. Try with yours

**Comment by duckchip** [comment]
@nikoelgatito Did you implement your second solution? 

We're dealing with the same issue at the moment, I can't believe magento sees this as intended behaviour and this is still an issue in 2.3 

Would you be so kind to share your code with us? Or create a PR? :) 

Big thanks for all the research you already did!

@magento-engcom-team I think this more an issue than an improvement. Many shop-owners will struggle with the same problem as they assume that backorders allow the sale of out-of-stock products with a negative qty. 

Thx in advance!

**Comment by magento2dev** [comment]
We have the same issue, I can't believe Magento considers this as the normal behaviour... By allowing the backorders, of course, I would like to allow customers to purchase out of stock products, it's the definition of backorders...
Does anyone has found a solution ?

Thanks !

**Comment by samuelmafra** [comment]
Magento 2.2.5 with the same problem. We are waiting years for this correction. The correct logic would be to be able to backorder product out of stock and with quantity below 1.

Still waiting...

**Comment by simonmaass** [comment]
i agree and have the same issue!

**Comment by theschwag** [comment]
I agree with @samuelmafra as well. Our site is running 2.1.8 and we cannot get backorders to work either. Very annoying

**Comment by goranhorvathr** [comment]
@magento-engcom-team This is not an improvement. By what standards do you consider this an improvement? Hmm? Tell me? I would very much like to hear your opinion on this. I want facts from programming stand of point. This was already investigated in depth and model can be refactored in a custom module however i still cant understand where are you basing your statement that this is an improvement.

**Comment by ghost** [comment]
> From the official Magento documentation both for the first edition and Magento 2 we can read the following very logical definition for **Out of Stock** products:
> 
> > **Out of Stock: Unless Backorders are activated**, prevents the product from being available for purchase and removes the listing from the catalog.
> 
> Source: http://docs.magento.com/m2/ce/user_guide/catalog/settings-advanced-advanced-inventory.html
> 
> ### Preconditions
> 1. Magento 2.1.6
> 2. Edit/Create a product,
> 3. Set **Manage Stock** to "Yes",
> 4. Set **Qty** to "0",
> 5. Set **Stock Status** to "Out of Stock".
> 
> ### Steps to reproduce
> 1. Visit the product page,
> 2. Add the product to cart.
> 
> ### Expected result
> 1. The **Add to Cart** button shows and we **can** add the product to the shopping cart.
> 
> ### Actual result
> 1. The **Add to Cart** button does not show,
> 2. Even after forcing the isSalable() method to return true, then refreshing the page and clicking on the Add to Cart button that is now showing, the product is not added to cart and the red "_This product is out of stock._" notification message is showing.
> 
> ## Remarks regarding the Add to Cart button not showing:
> It seems that the isSalable() method depends more on the **In Stock** status than the real item quantity. This function should rely on real quantity for every product that has the **Manage Stock** option enabled. Solely relying on the **Stock Status** for product with real quantity is not reliable.
> 
> **The logic should be as follow: Manage Stock = No:**
> 
> * isSalable() should return true/false based on **_Stock Status_**.
> 
> **Manage Stock = Yes:**
> 
> 1. **Backorders are not allowed:** isSalable() should return true/false based on stock **_qty_** and **_threshold_**.
> 2. **Backorders are allowed:** isSalable() should **_always_** return true.
> 
> https://stackoverflow.com/questions/9038988/what-is-the-difference-between-issaleable-and-isavailable
> 
> ## Remarks regarding the product not adding to cart:
> **It seems that the "magic" preventing the product to be added to cart reside in this class:**
> Magento\CatalogInventory\Model\Quote\Item\QuantityValidator::validate()
> 
> **As we can see on line 103, the verification here again solely rely on Stock Status and not on the actual quantity even though Manage Stock is enabled:**
> 
> ```
> 103 | if (!$stockItem->getIsInStock() || $parentStockItem && !$parentStockItem->getIsInStock()) {
>        ...
>       }
> ```
> This is unfortunate as we though backorders were well implemented in Magento and we are currently on a project for which we will have to modify the default (wrong) Magento behavior by the meantime this bug gets officially resolved and released.
> 
> # [UPDATE]
> ## Possible Solution:
> It seems that these two small changes would correct this bug!
> 
> > **Magento\CatalogInventory\Model\Quote\Item\QuantityValidator::validate()**
> 
> ```
> Line 103 | - if (!$stockItem->getIsInStock() || $parentStockItem && !$parentStockItem->getIsInStock()) {
> Line 103 | + if ((!$stockItem->getIsInStock() || $parentStockItem && !$parentStockItem->getIsInStock()) && !$stockItem->getBackorders()) {
> ```
> > **Magento\CatalogInventory\Model\StockStateProvider::checkQuoteItemQty()**
> 
> ```
> Line 155 | - if (!$stockItem->getIsInStock()) {
> Line 155 | + if (!$stockItem->getIsInStock() && !$stockItem->getBackorders()) {
> ```
> These are making sure that the product Stock Status being out of stock has no impact if backorders are enabled. The process will then continue its nomal verification flow and the backorder notices will still be shown where applicable. It has been tested and completely working.


I could not find this line in that file,
Line 103 | - if (!$stockItem->getIsInStock() || $parentStockItem && !$parentStockItem->getIsInStock()) {

**Comment by soundararajanm1990** [comment]
Backorders not working for me in magento2.3.2

**Comment by sriharsha184** [comment]
Issue still occurs in M 2.3.2 Enterprise Edition.Is there any patch available to fix this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21832` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shubhajay** [comment]
Backorders not in magento2.3.2 it does't show add to cart button it was working in magento 2.3.1

**Comment by sdzhepa** [comment]
Hello @nikoelgatito and all from this thread:
@torlokken @saumil171188 @sebfie @zuber11 @duckchip @magento2dev @samuelmafra @simonmaass @theschwag @goranhorvathr @veneu @soundararajanm1990 @sriharsha184 @shubhajay 


Internal Magento team worked on this issue in the scope of `MC-21832`. 
The described flow in the Issue description was reconsidered again after reopen(issue was closed on Nov 1, 2017 [here](https://github.com/magento/magento2/issues/10304#issuecomment-341160070))

After multiple discussions and confirmation from the Product Owner of this functionality, the internal Jira ticket was closed as Not a Bug.
It is expected behavior for Magento 2 now.

POs resolution quote:

> The Out of Stock status is a way for the merchant to take a product out of stock on the website without having to adjust the quantity. There may be several reasons they want to do this. By using the out of stock status, they can:
> 
> - Show the product on the storefront, which is not possible if they disable the product instead of using stock status
>  - Keep the existing quantity for the product unchanged, which may reflect the actual physical quantity in a warehouse
>
> This is also shown in our documentation here: https://docs.magento.com/m2/ee/user_guide/catalog/inventory-backorders.html#stock-status
>> Stock Status
>> Products **must be set to In Stock status when enabling backorders.**...


This issue should be closed as well

**Comment by frostbitten** [comment]
Hi, @sdzhepa, sorry if this is a silly question but I'm a bit confused. What do you mean by "Product Owner of this functionality?" What is that? The person who opened this ticket? An internal engineer? An EE customer?

Also can you clarify. Is the **sole** purpose of the Stock Status field to enable and disable the ability to purchase an item (while allowing it stay visible)?

Thanks!

**Comment by CompactCodeEU** [comment]
Let me clarify some things :

1. This should really be 2 separate things. Backorders should allow the order of out of stock products. Another setting could be made to disable the add to cart like an 'Is Saleable' boolean field on product level.

2. We have enabled 'Allow Qty Below 0 and Notify Customer' and it is still automatically setting '`stock_status`' to 0 in `cataloginventory_stock_status` . When i turn off 'Manage stock' it does not change it to 0. So something is definitely off here.

Please consider this and re open this issue.

**Comment by bo91** [comment]
Hi
Does anybody know where the stock count should be decreased? It's also not happening if I just overwrite the two methods as mentioned by @nikoelgatito :

`Magento\CatalogInventory\Model\Quote\Item\QuantityValidator::validate()
Magento\CatalogInventory\Model\StockStateProvider::checkQuoteItemQty()`

**Comment by trucatchtraps** [comment]
Been experiencing this same issue forever and now still not fixed in 2.3.4. You should be able to order Out of Stock products when you allow Backorders. It is very confusing to our customers when the product shows In Stock but yet it will be backordered.

**Comment by studio16** [comment]
Along with this is issue the product alert function does not work/show combined with allowing backorders and after using a workaround to get the alert link  it seems the trigger of sending the email is also the is_in_stock setting (which needs to be true if u want to allow backorders) in stead of the real quantity causing sending email alerts while the quantity is still 0.

**Comment by suneth2** [comment]
I'm facing same issue on Magento ver. 2.3.0, screen shot is settings of a  simple product of configurable product which gives these two error messages when try to add to cart, any idea how to fix this
"The requested quantity is not available
This product is out of stock."
![simple pro](https://user-images.githubusercontent.com/1442079/83671933-19666b80-a5f3-11ea-828f-ec255db4f4cd.png)

**Comment by siliconalchemy** [comment]
> After multiple discussions and confirmation from the Product Owner of this functionality, the internal Jira ticket was closed as Not a Bug.
> It is expected behavior for Magento 2 now.

@sdzhepa  - the PO/Magento has misunderstood what BackOrder means then.  Back Orders allow customers to order a product even if it is *out of stock*.  Falsely marking a product as In Stock when it has zero or negative quantity is nonsensical, and doing so breaks other functionality/logic (Eg. In Stock filters).
The whole point of Back Order is to allow products to be marked Out of Stock.  In researching this problem I've come across countless others confused by the same thing, this behaviour is obviously not what admins/users/customers expect.

**Comment by atIOCrON** [comment]
We have the same complaint. This is so annoying. We should be able to set out of stock AND still allow backorders because right now, if we enable backorders, our products must be shown in stock and then also syndicated to Google and other places as in stock when they're not.

**Comment by LiamKarlMitchell** [comment]
Please allow ordering out of stock products but show Out of stock and notify the customer that the product is out of stock but that they can still order it. This seems like a bug to store owners.

**Comment by thomas-thaulow** [comment]
This is really frustrating, feels like Adobe is saying its expected functionality, so they can close one of the thousands of issues here, rather then actually spend time fixing it. Backordering is backordering, and if the functionality of disabling sales for a product is important, Magento should add another attribute for "allow sale". Using out of stock or in stock for this, seems like horrible practice.

Can someone (@sdzhepa) pitch to the product owner that it should rather be added an "Is sellable" attribute, so that there isnt any logical flaws in Magento, as it is now, when forcing "In stock" for out of stock products.

**Comment by siliconalchemy** [comment]
One thing I've noticed from involvement in other issues in Magento github - once an issue is closed they very rarely read/reopen/care about that issue any longer.  If you want action on a closed issue, open a new issue and reference the old one.

**Comment by ioweb-gr** [comment]
@magento give me 2.4-develop instance

**Comment by RenoBekel** [comment]
> Sorry, update my link: https://www.fixbugs.xyz/2021/10/25/magento-2-4-3-backorders-inconsistent-reference-for-interface-magentoinventorysalesapiapiisproductsalableinterface/

Hello do you have a new link for me available? 
We have I think the same issue. We have orders made in magento, but a few days later I need to change this order, because something is out of stock. Suddenly I cannot change the order anymore, because we've changed the status of the products in the backend to ''out of stock''. So this is very difficult.

**Comment by trunglv** [comment]
@RenoBekel . 
Problem-solving:
There is an inconsistency that a class reference for interface \Magento\InventorySalesApi\Api\IsProductSalableInterface is different between Adminhtml scope and Frontend scope.

You can check di files to find which class will reference to IsProductSalableInterface:

vendor/magento/module-inventory-indexer/etc/frontend/di.xml
<preference for="Magento\InventorySalesApi\Api\IsProductSalableInterface" type="Magento\InventoryIndexer\Model\IsProductSalable"/>
vendor/magento/module-inventory-sales/etc/di.xml
<preference for="Magento\InventorySalesApi\Api\IsProductSalableInterface" type="Magento\InventorySales\Model\IsProductSalableCondition\IsProductSalableConditionChain"/>
The first one defines a reference for Frontend scope, so when a system checks a product is whether saleable or not, it will use Magento\InventoryIndexer\Model\IsProductSalable.

My Solution :
Create a new module
Create etc/frontend/di.xml
<preference for="Magento\InventorySalesApi\Api\IsProductSalableInterface" type="Magento\InventorySales\Model\IsProductSalableCondition\IsProductSalableConditionChain"/>
But now, add to cart button has not been shown. So I need to do more:

Create a plugin for a class “Magento\InventorySales\Model\IsProductSalableCondition\IsAnySourceItemInStockCondition”. It will check whether a product is a backorder kind or not. If a backorder flag was set then we ignore a condition “Is Any Source Item In Stock Condition”
<type name="Magento\InventorySales\Model\IsProductSalableCondition\IsAnySourceItemInStockCondition">
        <plugin name="betagento_backorders_fixing" type="Betagento\Backorder\Plugin\IsAnySourceItemInStockCondition"/>
    </type>
<?php 
namespace Betagento\Backorder\Plugin;

use Magento\InventoryConfigurationApi\Api\Data\StockItemConfigurationInterface;
use Magento\InventoryConfigurationApi\Api\GetStockItemConfigurationInterface;
use Magento\InventorySalesApi\Api\IsProductSalableInterface;


class IsAnySourceItemInStockCondition {

    /**
     * @var GetStockItemConfigurationInterface
     */
    private $getStockItemConfiguration;

    /**
     * @param GetStockItemConfigurationInterface $getStockItemConfiguration
     */
    public function __construct(
        GetStockItemConfigurationInterface $getStockItemConfiguration
    ) {
        $this->getStockItemConfiguration = $getStockItemConfiguration;
    }

    public function aroundExecute(IsProductSalableInterface $subject, \Closure $proceed, string $sku, int $stockId){

        
        $stockItemConfiguration = $this->getStockItemConfiguration->execute($sku, $stockId);
        if ($stockItemConfiguration->getBackorders() !== StockItemConfigurationInterface::BACKORDERS_NO
            && $stockItemConfiguration->getMinQty() >= 0) {
            return true;
        }else{
            return $proceed($sku, $stockId);
        }

    }
}
My suggestion is to merge two conditions classes below into only one class:

Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\BackOrderCondition

Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsAnySourceItemInStockCondition

… But anyway

**Comment by RenoBekel** [comment]
> @RenoBekel . Problem-solving: There is an inconsistency that a class reference for interface \Magento\InventorySalesApi\Api\IsProductSalableInterface is different between Adminhtml scope and Frontend scope.
> 
> You can check di files to find which class will reference to IsProductSalableInterface:
> 
> vendor/magento/module-inventory-indexer/etc/frontend/di.xml vendor/magento/module-inventory-sales/etc/di.xml The first one defines a reference for Frontend scope, so when a system checks a product is whether saleable or not, it will use Magento\InventoryIndexer\Model\IsProductSalable.
> 
> My Solution : Create a new module Create etc/frontend/di.xml But now, add to cart button has not been shown. So I need to do more:
> 
> Create a plugin for a class “Magento\InventorySales\Model\IsProductSalableCondition\IsAnySourceItemInStockCondition”. It will check whether a product is a backorder kind or not. If a backorder flag was set then we ignore a condition “Is Any Source Item In Stock Condition”
> 
> getStockItemConfiguration = $getStockItemConfiguration; } public function aroundExecute(IsProductSalableInterface $subject, \Closure $proceed, string $sku, int $stockId){ $stockItemConfiguration = $this->getStockItemConfiguration->execute($sku, $stockId); if ($stockItemConfiguration->getBackorders() !== StockItemConfigurationInterface::BACKORDERS_NO && $stockItemConfiguration->getMinQty() >= 0) { return true; }else{ return $proceed($sku, $stockId); } } } My suggestion is to merge two conditions classes below into only one class: Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\BackOrderCondition Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsAnySourceItemInStockCondition … But anyway


So will this solve our problem? Our problem specified: 

We have customers who do not directly pay for the order when placing the order. So we have to change these later to give them the correct invoice. But when we then try to change these orders we get the following error. (in the attachment) Do you have any idea how to solve this?

He only gives this error when one of the products in the order is turned to ''not in stock''

We now keep the products enabled, but turn them out on our store by switching between ''in stock or not in stock'' products with 0 stock are not visible on the store.

Hope to hear from you
![not-available](https://user-images.githubusercontent.com/97195581/148346094-66ca4b53-bc6d-4222-b3e9-beca6c3b28bc.png)
.

**Comment by trunglv** [comment]
@RenoBekel 
- Please try to get error detail in var/log or var/report. It may help to identify what the problem is.
