### ISSUE TITLE
Identifiers of specific pages not work

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento2#10300]
### Preconditions

1. Magento2.1.7ce
2. PHP7.0.16-3
3.MYSQL5.7.17-1

### Steps to reproduce

![20170721162108](https://user-images.githubusercontent.com/4518013/28455166-a6c3bdfa-6e30-11e7-9e2a-e4119ec9c001.png)
![20170721162204](https://user-images.githubusercontent.com/4518013/28455205-c74e6f0c-6e30-11e7-80f4-3e04e18082ff.png)
![20170721161012](https://user-images.githubusercontent.com/4518013/28454796-2659248a-6e2f-11e7-9971-913586ccd76a.png)
![20170721161353](https://user-images.githubusercontent.com/4518013/28454951-a8e9ff46-6e2f-11e7-86b2-878a0642efc4.png)

**Comment by atishgoswami** [comment]
@michaeldyl520 you will need to use the url-key of the CMS page for the XML layout file.

![issue_cms_page](https://user-images.githubusercontent.com/2647377/28455429-b609442e-6e1c-11e7-96dc-483ffefd2b1d.png)


For example if you have a cms page with the URL Key `home` then you XML layout file would be `cms_page_view_id_home.xml`

Hope this helps!!

**Comment by michaeldyl520** [comment]
@atishgoswami I try that,it goes work.Thanks,that`s the best sollution.

**Comment by atishgoswami** [comment]
@michaeldyl520 Please close the issue if you are satisfied with the answer.

**Comment by magento-engcom-team** [comment]
@michaeldyl520 Closing this report, as it seems @atishgoswami provided a working solution.

Thank you.
