### ISSUE TITLE
Magento Customer Registration form on how to display Address field setting?

### ISSUE THREAD

**Issue by rvpatel** [magento/magento2#1030]
Magento Customer Registration form on how to display Address field without customize like 
```
<?php $this->setShowAddressFields(true); ?> 
```
adding on before Line 56.
```
<?php if ($block->getShowAddressFields()): ?>
```

**Comment by vpelipenko** [comment]
@rvpatel, could you provide more details about described issue? Please, describe what and how you are going to customize in customer registration form.

**Comment by rvpatel** [comment]
How to display Address Field on customer registration form. 
On now lattest magento version have issue then solve in magento2 or not without fixing using this code.

Any setting u have provide for this?

```
<?php setShowAddressFields(true); ?>
```
![Customer Account Register Fronted](http://s12.postimg.org/502ma8x3h/Create_New_Customer_Account.png)

**Comment by vpelipenko** [comment]
@rvpatel, thanks for the update. We'll assign this issue to appropriate PO who will make a decision about current behavior.

**Comment by ilol** [comment]
@rvpatel, thanks for this improvement.
I created the ticket inside our Requirements Management System MAGETWO-34179 with label "up for grabs". Welcome to  pull-request creation.

**Comment by ilol** [comment]
@rvpatel, hi. Thank you for this issue. I decided to add flag "Show Address Info"  and then show address info on Account Registration form (internal tracking number MAGETWO-34191).

**Comment by versdivers** [comment]
Is this already implemented? Can't find the option

**Comment by ilol** [comment]
@versdivers  not yet.

**Comment by versdivers** [comment]
I did it with the code above but i think this should be an option within magento to add fields to the registration. just seems so basic setup.

**Comment by c11media** [comment]
I simply changed the <?php if ($block->getShowAddressFields()): ?> **TO** <?php if ($block->setShowAddressFields(true)): ?> in register.phtml in the core magento (even though it should be done on the theme level but the address fields just weren't showing through the UI and I have a very heavy there) /public_html/vendor/magento/module-customer/view/frontend/templates/form

you'll notice i didn't call the object with this--> and left $block--> and it worked. 

 and now everything is working correctly. BTW running Magento 2.10

**Comment by vovan1983** [comment]
When I set <?php if ($block->setShowAddressFields(true)): ?> instead <?php if ($block->getShowAddressFields()): ?> the address fields are showing, but if I submit form  then I get notice that 'Delete operation is forbidden for current area' without login and redirect to dashboard (but customer was register) in Magento 2.1.

**Comment by vovan1983** [comment]
Solve it. I forgot add country_id field.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-Customer-Registration-form-on-how-to-display-Address/idi-p/46634).

**Comment by Moinashraf** [comment]
I am trying all above possibilities to resolve this issue but the error shown in the frontend and In admin The address data should not display.
![screenshot from 2017-02-21 13-24-02](https://cloud.githubusercontent.com/assets/25338993/23155579/3a259208-f839-11e6-89a7-dbe3691a4fad.png)
![screenshot from 2017-02-21 13-25-52](https://cloud.githubusercontent.com/assets/25338993/23155593/50021b14-f839-11e6-8541-8f394506d35c.png)
