### ISSUE TITLE
Region is being overridden when changing from a required-state country to one that is not required

### ISSUE THREAD

**Issue by nei** [magento/magento2#10317]
On Magento 2.1.7 the user change the country from EUA with region Alaska to Uruguay for instance the region dropdown is hidden and the region input text is showed with Alaska as value.. 

So, if you change to XXX and save Magento is still posting the region_id Alaska and on the backend we are now checking if the region_id exists and if it does we override the value of region.

This behavior was introduced on this commit https://github.com/magento/magento2/commit/77504152dfcd777f76080777f4929a5086a6dc4a#diff-9fadca60a49535a2817d9fc5c4535d3a

My solution was to disable the region_id dropdown element so it will not be posted when it is hide.

### Preconditions
1. Magento 2.1.7
2. PHP 7.0.4

### Steps to reproduce
1. Log into your Account on the frontend
2. Edit your billing address and save using EUA for country and pick a state, save it.
3. Edit your billing address again, change from EUA to Uruguay, change the region input for Test
4. Save it and you will see EUA state still being showed.

### Expected result
4. After save you should be able to see the new state being displayed

### Actual result
4. After save it is showing the old state value.

### Proposal Solution

Not post region_id if we don't need it.

[region-updater.patch.txt](https://github.com/magento/magento2/files/1173026/region-updater.patch.txt)

**Comment by magento-engcom-team** [comment]
@nei, thank you for your report.
We've created internal ticket(s) MAGETWO-75591 to track progress on the issue.

**Comment by romainruaud** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @nei the issue has been fixed in 2.2.1 (#11254) and will be available soon

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81019

**Comment by magento-team** [comment]
Hi @nei. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1282 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
