### ISSUE TITLE
Timeout during generating product urls after newly created store view

### ISSUE THREAD

**Issue by Jeroenll** [magento/magento2#10315]
### Preconditions
1. Magento v2.1.7
2. PHP v7.0.14
3. MySQL v5.6.33

### Steps to reproduce
1. Create 65K products (our use case).
2. Create new Store View.

### Expected result
1. Store View will be created and all products are assigned to that newly created Store View.

### Actual result
1. Store View will be created but not all products are assigned to that newly created Store View.

Exception being thrown: `PHP Fatal error:  Maximum execution time of 120 seconds exceeded in /data/web/magento2/vendor/magento/module-catalog-url-rewrite/Model/Category/Plugin/Store/View.php on line 136`. Most servers are configured with a timeout of 60 or 120 seconds. When adding 65k products Magento will need more time to generate all URLs. This should not be done through a web process.

**Comment by Jeroenll** [comment]
Temporarily using a custom created cron job that will re-generate all urls.

**Comment by orlangur** [comment]
This is due to poor URL Rewrites performance, tracked as MAGETWO-69145 internally according to https://github.com/magento/magento2/issues/10242#issuecomment-324371473.

Not sure if it works better already on Magento 2.2.0 branch.

**Comment by magento-engcom-team** [comment]
@JeroenVanLeusden, thank you for your report.
We've created internal ticket(s) MAGETWO-69145, MAGETWO-80341 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@JeroenVanLeusden, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
