### ISSUE TITLE
Travis build "too many arguments"

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#10316]
### Preconditions
Magento version: develop branch

### Steps to reproduce
1. Run a build via travis

### Expected result

1. System completes without issues

### Actual result

1. Error "./dev/travis/before_install.sh: line 24: [: too many arguments",

https://travis-ci.org/magento/magento2/jobs/257087136#L647

**Comment by magento-engcom-team** [comment]
@dmanners, thank you for your report.
We've created internal ticket(s) MAGETWO-84823 to track progress on the issue.

**Comment by dmanners** [comment]
I have checked the latest builds for 2.1-develop, 2.2-develop and 2.3-develop and this issue does not seem to appear anymore.
