### ISSUE TITLE
Multisite Store not showing products

### ISSUE THREAD

**Issue by crantron** [magento/magento2#10310]
I have created a multistore in magento 2, the "base" store shows theme. categories, and all products fine while the second store, shows: theme, and categories but does not show products.

### Preconditions
CentOs 7.5
PHP 7.0.14 
MySql 5.6.35
Apache 2.4.6
Magento 2.1.7

### Steps to reproduce
pub/index.php

```<?php
/**
 * Public alias for the application entry point
 *
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Bootstrap;
use Magento\Framework\App\Filesystem\DirectoryList;

try {
    require realpath(__DIR__) . '/../app/bootstrap.php';
} catch (\Exception $e) {
    echo <<<HTML
<div style="font:12px/1.35em arial, helvetica, sans-serif;">
    <div style="margin:0 0 25px 0; border-bottom:1px solid #ccc;">
        <h3 style="margin:0;font-size:1.7em;font-weight:normal;text-transform:none;text-align:left;color:#2f2f2f;">
        Autoload error</h3>
    </div>
    <p>{$e->getMessage()}</p>
</div>
HTML;
    exit(1);
}

$params = $_SERVER;
$params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS] = [
    DirectoryList::PUB => [DirectoryList::URL_PATH => ''],
    DirectoryList::MEDIA => [DirectoryList::URL_PATH => 'media'],
    DirectoryList::STATIC_VIEW => [DirectoryList::URL_PATH => 'static'],
    DirectoryList::UPLOAD => [DirectoryList::URL_PATH => 'media/upload'],
];

switch($params['HTTP_HOST']) {
    case '****pro.dev' :
    case 'www.****pro.dev':
        //recpro website config.
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'base';
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
        break;
    case '****dders.dev':
    case 'www.****dders.dev':
        //boatladders website config.
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = '******dders';
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
        break;
}

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
/** @var \Magento\Framework\App\Http $app */
$app = $bootstrap->createApplication('Magento\Framework\App\Http');
$bootstrap->run($app);
```

![screen-shot-2017-07-24-at-8 18 11-pm](https://user-images.githubusercontent.com/3859969/28554320-afebef72-70ad-11e7-9726-4322c7035234.jpg)
![screen-shot-2017-07-24-at-8 17 30-pm](https://user-images.githubusercontent.com/3859969/28554318-afebaf62-70ad-11e7-88d7-e723003d762e.jpg)

![screen-shot-2017-07-24-at-8 02 45-pm](https://user-images.githubusercontent.com/3859969/28554319-afebd140-70ad-11e7-9c36-50d7596b2adf.jpg)

**PERECT!!!!**
![screen shot 2017-07-24 at 8 08 34 pm copy](https://user-images.githubusercontent.com/3859969/28554321-afee9bf0-70ad-11e7-951a-a05ab8ee9e31.png)

**..not perfect....**
![screen shot 2017-07-24 at 8 01 56 pm copy](https://user-images.githubusercontent.com/3859969/28554317-afeb9f4a-70ad-11e7-857d-c034d0c1f20c.png)

### Expected result
*dders test prod should be showing up in both websites. 
1. 

### Actual result
*dders does not show up in both sites

if anyone needs mores information please let me know. Everything seems to be functioning perfectly :theme...categories...just no products on the non base website.

**Comment by Shade634** [comment]
Did you check if the products are enabled in the specific storeviews? (happened to me once) 
If you added the products before adding the non base website, this will most likely be the case.

**Comment by crantron** [comment]
You're a legend.

**Comment by amandeep-singh9** [comment]
> Did you check if the products are enabled in the specific storeviews? (happened to me once)
> If you added the products before adding the non base website, this will most likely be the case.

This was exactly the problem I was facing, Products were enabled but not for specific website which I added later on. Thank you so much.
