### ISSUE TITLE
TypeError: <Array>.each is not a function in dynamics-rows-grid.js

### ISSUE THREAD

**Issue by yonitjio** [magento/magento2#10321]
### Preconditions

1. Magento Version: 2.1.6
2. Devbox (Beta)

### Steps to reproduce

1. Create form (uiComponent) with related product modifier as reference:
[practice_document_customform.txt](https://github.com/magento/magento2/files/1174159/practice_document_customform.txt)

### Expected result

1. Should work like related product on create/edit product page.

### Actual result

1. Uncaught TypeError: max.each is not a function:
![magento-2-typeerror](https://user-images.githubusercontent.com/22361729/28584601-33145370-7122-11e7-88e5-6cd50b0e2d71.PNG)

### Proposed Solution

Use of underscore.
1. _checkGridData:
before:
~~~~
max.each(function (record, index) {
    obj[this.map[this.identificationDRProperty]] = record[this.map[this.identificationDRProperty]];

    if (!_.where(this.cacheGridData, obj).length) {
        changes.push(data[index]);
    }
}, this);
~~~~
after:
~~~~
_.each(max, function (record, index) {
                obj[this.map[this.identificationDRProperty]] = record[this.map[this.identificationDRProperty]];

                if (!_.where(this.cacheGridData, obj).length) {
                    changes.push(data[index]);
                }
            }, this);
~~~~
2. processingInsertData:
before:
~~~~
changes.each(function (changedObject) {
    this.mappingValue(changedObject);
}, this);
~~~~
after:
~~~~
_.each(changes, function (changedObject) {
    this.mappingValue(changedObject);
}, this);
~~~~

After changing to underscore's each it run as expected:
![magento-2-typeerror-corrected](https://user-images.githubusercontent.com/22361729/28584610-39b53be0-7122-11e7-9f20-01e13ebb52d8.PNG)

**Comment by magento-engcom-team** [comment]
Hi @yonitjio 
Please provide more information, how can be reproduce it without your custom module.

**Comment by yonitjio** [comment]
Hi,

Actually, I don't think it can be reproduced without custom module. 

I was trying to practice to build a custom module when I encounter the bug. The basic idea was to create a sample module with generic "document - document detail" model, but instead of using modifier, I used UIComponent.

I can give you the project source if you want it, but it kinda messy tho, and I've abandon it since it was just for practice.

A side note: I think using UIComponent to build forms is great idea and opens new opportunities. I really hope in the future we can have a kind of WYSIWYG editor.

**Comment by magento-engcom-team** [comment]
I understand you @yonitjio.
If you know where the error is, then please give part of your module with which the problem can be reproduced if use your file "practice_document_customform.txt".

**Comment by yonitjio** [comment]
Sorry for the late reply,

I don't know where exactly, and since it's not a big module, I've attached all.

Anyway, I've just restored the project and tried to reproduce the error, it did not occur.
But this time I'm using 2.1.9.

So I guess it's been fixed somehow?


[Fonel.zip](https://github.com/magento/magento2/files/1445292/Fonel.zip)

**Comment by magento-engcom-team** [comment]
Hi @yonitjio 
I can not reproduce the issue with you attached module.
My steps are present in video:
[Screen 11-06-2017 10-50-15.zip](https://github.com/magento/magento2/files/1445545/Screen.11-06-2017.10-50-15.zip)

**Comment by magento-engcom-team** [comment]
@yonitjio, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by msieprawski** [comment]
Hello @magento-engcom-team, seems like I've found the problem. @yonitjio attached whole module which contains custom javascript - `view/adminhtml/web/document/customedit/doctool.js`. This file loads prototype library as it have it registered in dependencies. Once you comment out `<block class="Magento\Backend\Block\Template" template="Fonel_Practice::document/customedit/js.phtml"/>` in `view/adminhtml/layout/practice_document_customedit.xml` it will stop working.

Seems like Magento doesn't load prototype library when defining custom modal with insertListing linked to dynamicRows. If that is not enough please let me know so I will create custom module to help reproduce that bug.

**Comment by msieprawski** [comment]
Hi again @magento-engcom-team, any chances of reopening that issue? A lot of people potentially are losing their time because of that issue. It's not that easy to track it and fix it.

**Comment by flamboy** [comment]
@magento-engcom-team, The same issue. Trying to create my own ui component in ui form using modifiers http://devdocs.magento.com/guides/v2.1/howdoi/customize_product.html#modifier
Got the same error, trying using undescore library fix the issue http://i.prntscr.com/_7bIGxD8SqubGdxoAdlhkw.png

**Comment by flamboy** [comment]
temporary solution add code to layout (without using mixins)
```
<head>
		<script src="prototype/prototype.js"/>
	</head>
```

**Comment by chakravarthykalyan90** [comment]
We faced similar issue with javascript error `Uncaught TypeError: data.forEach is not a function`

![image](https://user-images.githubusercontent.com/3271931/37145492-0888be76-22e7-11e8-928f-b3a237eda916.png)


To reproduce the issue, create a product with custom options. First, keep the field type and next dropdown. Save the product and try to open the custom options section. It will not open.

If you keep the field type, at last, there won't be an issue. This is weird but issue depends on the sort order of custom options not sure why.

@yonitjio solution worked for us. We replaced this line `data.forEach(function (obj)` with `_.forEach(data,function (obj) {`

**Comment by theCapypara** [comment]
Hi, I can confirm this is a real issue. Using a custom ui component modal with a insertListing and a dynamicRow component does not work for custom modules without that workaround. Could you consider reopening this issue? @magento-engcom-team
