### ISSUE TITLE
Magento 2 PUT to update customer info is returning 404 Not found

### ISSUE THREAD

**Issue by mbelyamani** [magento/magento2#10324]
Running Magento 2.1.7 and trying in postman to update customer with the following setup:
PUT      https://domain/index.php/rest/V1/customers/7 

Headers:
Content-Type:application/json
Authorization:Bearer 0nmhlpx6euuqia9r7q44430hvcramnd0 

Body:
{"customer": {"id": 7,"dob": "1972-08-20 00:00:00","firstname": "NewFirstName",
				"lastname": "NewLastName","middlename": "NewMiddleName", 
				"email": "test@email.com", "website_id":1,
				"store_id":1}
}

===> Getting as response:
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title>Error 404: Not Found</title>
    <base href="https://mage2.stealthcoms.ca:443/pub/errors/default/" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="*"/>
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <main class="page-main">
        
<h1>404 error: Page not found.</h1>
    </main>
</body>
</html>

In Magento documentation:

404 | Not found | The specified REST endpoint does not exist. The caller can try again.

Please let me know if I'm missing something.

Note: I can create a new user using api with no issue, updating an existing customer is not working.

**Comment by magento-engcom-team** [comment]
@mbelyamani please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.
