### ISSUE TITLE
Allow multiple roles per admin user

### ISSUE THREAD

**Issue by airbone42** [magento/magento2#1032]
Currently it's only possible to have one role per admin user, which is quite difficult to handle if you have multiple users which have overlapping roles.

E.g. we have usually Editors and Sales people. So we need two roles. Besides that we also have people who're allowed to do both, so we already have to maintain three roles which have a very big overlap in the ressources. We always have to update all the roles if something in the ressources changes. This problem gets even bigger if you have three or four normal roles which have to be mixed up.

Also the ressources which everyone should have, like the section to change the own password has to be added to every role individually instead of just having a "my account" role which you have to maintain only once and add it to every user.

**Comment by tzyganu** [comment]
:+1:

**Comment by ilol** [comment]
Thanks, @airbone42. Great idea, and we even have registered task (MAGETWO-11357) in our product backlog related to this topic. But that is expensive feature.

I would discuss other side of this problem. What do you think about connection of our user role with Active Directory (FreeIPA) group? This would be helpful for user administrators to setup and sync Magento permissions with permissions to other system resources of merchant`s infrastructure.

**Comment by airbone42** [comment]
Hi @ilol,

a sync to AD is definitely a great feature but I would see it separated from this one. AD sync might be interesting for enterprise systems, but having shared roles is required by almost every merchant that has more than two users. We would even need that as an agency for our different set of supporting users, which btw are usually not registered in the AD of the merchants. ;)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Allow-multiple-roles-per-admin-user/idi-p/47304).
