### ISSUE TITLE
Updating quantity on multiple variants

### ISSUE THREAD

**Issue by 1f47a** [magento/magento2#10323]
### Preconditions

1. Magento 2.1.7
2. Sample data installed

### Steps to reproduce

1. Edit a configurable product from catalog
2. Click Edit Configurations
3. Hit next until you have an editable table OR Apply unique quantity by attribute to each SKU
4. Change/update quantity
5. Save product

### Expected result

1. Quantity updated to new value

### Actual result

1. Quantity stays the same

**Comment by magento-engcom-team** [comment]
@lclghst , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Please consider backporting to 2.1 branch since this is the branch the problem was reported on. Or mark it up for grabs.
