### ISSUE TITLE
Magento2.1.7 miss State/Province after edit orders in admin

### ISSUE THREAD

**Issue by sharkpee** [magento/magento2#10332]
I install m2.1.7
When I edit an order
try to change the billing address
when I confirm and save
check the information
I found the State/Province was missing
each order is the same after edit
the other informations are there
only the State/Province is missing
Is that a bug ?
how can I fix that ?
much appreciate ~.~

![28617200-12510a96-7232-11e7-9843-a2aea36c9ac7](https://user-images.githubusercontent.com/26791568/28617456-f60f29ca-7232-11e7-80ee-ab839731a81e.png)
![12312](https://user-images.githubusercontent.com/26791568/28617454-f60972e6-7232-11e7-81d7-498f6ae903ea.png)
![123](https://user-images.githubusercontent.com/26791568/28617455-f60a407c-7232-11e7-8b9b-ed7d12f33a1c.png)

**Comment by sharkpee** [comment]
I try 2.1.5
it is missing again~

**Comment by southerncomputer** [comment]
search existing issues for fix! https://github.com/magento/magento2/issues/9439

**Comment by sharkpee** [comment]
#9439
<script src="https://gist.github.com/heyqule/2e6f2ebfd1717031a3c30e1b156587c0.js"></script>

It works! Thanks a lot ~~
