### ISSUE TITLE
Magento2 Installation with Sample data Error - 0.42.0-beta7

### ISSUE THREAD

**Issue by andreasacca** [magento/magento2#1033]
Hi, installing Magento2 with sample the installation stops at 96%.
The version is 0.42.0-beta7 and the <em><strong>composer.json</strong></em> file is modified by adding
<pre>
"repositories": [
    {
        "type": "composer",
        "url": "http://packages.magento.com/"
    }
    ],
</pre>
and 

<pre>"magento/sample-data": "0.42.0-beta6",
"magento/sample-data-media": "~0.42.0-beta1"</pre>

After launching <strong>composer install</strong>, and after running the wizard, the installation stops at 96% with the following error:

<strong>Installation is incomplete. Check the console log for errors before trying again. </strong>

<pre>
Installing sample data:
[ERROR] exception 'Magento\Framework\Exception' with message 'Source class Magento\Core\Model\Resource\Theme\Collection doesn't exist.' in /users/andreasacca/Sites/magento2-beta7/lib/internal/Magento/Framework/Code/Generator.php:103
Stack trace:
 . . .

Next exception 'ReflectionException' with message 'Class Magento\Core\Model\Resource\Theme\CollectionFactory does not exist' in /users/andreasacca/Sites/magento2-beta7/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29
Stack trace:
 . . .
Next exception 'ReflectionException' with message 'Class Magento\Core\Model\Resource\Theme\CollectionFactory does not exist' in /users/andreasacca/Sites/magento2-beta7/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:37
Stack trace:
</pre>

**Comment by bluk** [comment]
Can you check if:

``vendor/magento/sample-data/composer.json``

has `"version": "0.42.0-beta1"`?

If it does, can you remove your `vendor/magento/sample-data` directory and do a `composer update` and `composer install`?

**Comment by Antonioele** [comment]
on my computer linux ubuntu 14.04  magento 0.42.0-beta7
first composer install
after edit composer
"repositories": [
    {
        "type": "composer",
        "url": "http://packages.magento.com/"
    }
    ],
"magento/sample-data": "0.42.0-beta6",
"magento/sample-data-media": "~0.42.0-beta1"

composer update
chmod 777 -R  magento2.dev
chown -R www-data:www-data  .

sample data "0.42.0-beta6" installed.
sample data "0.42.0-beta7" deadlock.

**Comment by kokoc** [comment]
Thank you for reporting the issue.
Internal reference - MAGETWO-34007

**Comment by andreasacca** [comment]
Hi @bluk 
this is my composer json:

<pre>
{
    "name": "magento/project-community-edition",
    "description": "Magento project (Community Edition)",
    "type": "project",
    "version": "0.42.0-beta7",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
    {
        "type": "composer",
        "url": "http://packages.magento.com/"
    }
    ],
    "require": {
        "php": "~5.5.0|~5.6.0",
        "zendframework/zend-stdlib": "2.3.1",
        "zendframework/zend-code": "2.3.1",
        "zendframework/zend-server": "2.3.1",
        "zendframework/zend-soap": "2.3.1",
        "zendframework/zend-uri": "2.3.1",
        "zendframework/zend-validator": "2.3.1",
        "zendframework/zend-console": "2.3.1",
        "zendframework/zend-modulemanager": "2.3.1",
        "zendframework/zend-mvc": "2.3.1",
        "zendframework/zend-text": "2.3.1",
        "zendframework/zend-eventmanager": "2.3.1",
        "zendframework/zend-view": "2.3.1",
        "zendframework/zend-servicemanager": "2.3.1",
        "zendframework/zend-json": "2.3.1",
        "zendframework/zend-config": "2.3.1",
        "zendframework/zend-form": "2.3.1",
        "zendframework/zend-di": "2.3.1",
        "zendframework/zend-serializer": "2.3.1",
        "zendframework/zend-log": "2.3.1",
        "zendframework/zend-http": "2.3.1",
        "magento/zendframework1": "1.12.9-patch1",
        "composer/composer": "1.0.0-alpha8",
        "monolog/monolog": "1.11.0",
        "tubalmartin/cssmin": "2.4.8-p4",
        "magento/sample-data": "0.42.0-beta6",
		"magento/sample-data-media": "~0.42.0-beta1"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "lib-libxml": "*",
        "ext-ctype": "*",
        "ext-gd": "*",
        "ext-spl": "*",
        "ext-dom": "*",
        "ext-simplexml": "*",
        "ext-mcrypt": "*",
        "ext-hash": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3"
    },
    "replace": {
        "magento/module-admin-notification": "self.version",
        "magento/module-authorization": "self.version",
        "magento/module-backend": "self.version",
        "magento/module-backup": "self.version",
        "magento/module-bundle": "self.version",
        "magento/module-captcha": "self.version",
        "magento/module-catalog": "self.version",
        "magento/module-catalog-import-export": "self.version",
        "magento/module-catalog-inventory": "self.version",
        "magento/module-catalog-rule": "self.version",
        "magento/module-catalog-search": "self.version",
        "magento/module-catalog-url-rewrite": "self.version",
        "magento/module-catalog-widget": "self.version",
        "magento/module-centinel": "self.version",
        "magento/module-checkout": "self.version",
        "magento/module-checkout-agreements": "self.version",
        "magento/module-cms": "self.version",
        "magento/module-cms-url-rewrite": "self.version",
        "magento/module-configurable-import-export": "self.version",
        "magento/module-configurable-product": "self.version",
        "magento/module-contact": "self.version",
        "magento/module-core": "self.version",
        "magento/module-cron": "self.version",
        "magento/module-currency-symbol": "self.version",
        "magento/module-customer": "self.version",
        "magento/module-customer-import-export": "self.version",
        "magento/module-design-editor": "self.version",
        "magento/module-developer": "self.version",
        "magento/module-dhl": "self.version",
        "magento/module-directory": "self.version",
        "magento/module-downloadable": "self.version",
        "magento/module-eav": "self.version",
        "magento/module-email": "self.version",
        "magento/module-fedex": "self.version",
        "magento/module-gift-message": "self.version",
        "magento/module-google-adwords": "self.version",
        "magento/module-google-analytics": "self.version",
        "magento/module-google-optimizer": "self.version",
        "magento/module-google-shopping": "self.version",
        "magento/module-grouped-import-export": "self.version",
        "magento/module-grouped-product": "self.version",
        "magento/module-import-export": "self.version",
        "magento/module-indexer": "self.version",
        "magento/module-integration": "self.version",
        "magento/module-layered-navigation": "self.version",
        "magento/module-log": "self.version",
        "magento/module-msrp": "self.version",
        "magento/module-multishipping": "self.version",
        "magento/module-newsletter": "self.version",
        "magento/module-offline-payments": "self.version",
        "magento/module-offline-shipping": "self.version",
        "magento/module-page-cache": "self.version",
        "magento/module-payment": "self.version",
        "magento/module-persistent": "self.version",
        "magento/module-product-alert": "self.version",
        "magento/module-quote": "self.version",
        "magento/module-reports": "self.version",
        "magento/module-require-js": "self.version",
        "magento/module-review": "self.version",
        "magento/module-rss": "self.version",
        "magento/module-rule": "self.version",
        "magento/module-sales": "self.version",
        "magento/module-sales-rule": "self.version",
        "magento/module-search": "self.version",
        "magento/module-sendfriend": "self.version",
        "magento/module-shipping": "self.version",
        "magento/module-sitemap": "self.version",
        "magento/module-store": "self.version",
        "magento/module-tax": "self.version",
        "magento/module-tax-import-export": "self.version",
        "magento/module-theme": "self.version",
        "magento/module-translation": "self.version",
        "magento/module-ui": "self.version",
        "magento/module-ups": "self.version",
        "magento/module-url-rewrite": "self.version",
        "magento/module-user": "self.version",
        "magento/module-usps": "self.version",
        "magento/module-webapi": "self.version",
        "magento/module-weee": "self.version",
        "magento/module-widget": "self.version",
        "magento/module-wishlist": "self.version",
        "magento/theme-adminhtml-backend": "self.version",
        "magento/theme-frontend-blank": "self.version",
        "magento/theme-frontend-luma": "self.version",
        "magento/language-de_de": "self.version",
        "magento/language-en_us": "self.version",
        "magento/language-es_es": "self.version",
        "magento/language-fr_fr": "self.version",
        "magento/language-nl_nl": "self.version",
        "magento/language-pt_br": "self.version",
        "magento/language-zh_cn": "self.version",
        "magento/framework": "self.version",
        "oyejorge/less.php": "1.7.0",
        "trentrichardson/jquery-timepicker-addon": "1.4.3",
        "components/handlebars.js": "1.3.0",
        "colinmollenhour/cache-backend-redis": "dev-master#193d377b7fb2e88595578b282fa01a62d1185abc",
        "colinmollenhour/credis": "dev-master#f07bbfd4117294f462f0fb19c49221d350bf396f",
        "linkorb/jsmin-php": "1.1.2",
        "phpseclib/phpseclib": "0.2.1",
        "components/jquery": "1.11.0",
        "blueimp/jquery-file-upload": "5.6.14",
        "components/jqueryui": "1.10.4",
        "twbs/bootstrap": "3.1.0",
        "tinymce/tinymce": "3.4.7"
    },
    "extra": {
        "component_paths": {
            "oyejorge/less.php": "lib/internal/Less",
            "trentrichardson/jquery-timepicker-addon": "lib/web/jquery/jquery-ui-timepicker-addon.js",
            "components/handlebars.js": "lib/web/jquery/handlebars",
            "colinmollenhour/cache-backend-redis": "lib/internal/Cm/Cache/Backend/Redis.php",
            "colinmollenhour/credis": "lib/internal/Credis",
            "linkorb/jsmin-php": "lib/internal/JSMin",
            "phpseclib/phpseclib": "lib/internal/phpseclib",
            "components/jquery": [
                "lib/web/jquery.js",
                "lib/web/jquery/jquery.min.js",
                "lib/web/jquery/jquery-migrate.js",
                "lib/web/jquery/jquery-migrate.min.js"
            ],
            "blueimp/jquery-file-upload": "lib/web/jquery/fileUploader",
            "components/jqueryui": [
                "lib/web/jquery/jquery-ui.js",
                "lib/web/jquery/jquery-ui.min.js"
            ],
            "twbs/bootstrap": [
                "lib/web/jquery/jquery.tabs.js"
            ],
            "tinymce/tinymce": "lib/web/tiny_mce"
        }
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\ToolkitFramework\\": "dev/tools/performance-toolkit/framework/Magento/ToolkitFramework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/"
        }
    }
}
</pre>

**Comment by voleye** [comment]
Hi @andreasacca, may you just try to reinstall Magento?
 - remove db
 - clean "var" folder
 - re-run installation process

**Comment by andreasacca** [comment]
Hi @voleye I've done what you suggested
and the setup completed successfully. 

I tried also with the updated version (beta-8) and the installation with sample data is working well too.

Thanks!

**Comment by refaelgold** [comment]
Hi still have this issue and i really try all solution and nothing works!

i use https://github.com/rgranadino/mage2_vagrant for  vagrant server

```
Installing theme:
.
exception 'ReflectionException' with message 'Class Magento\Framework\Store\StoreManagerInterface does not exist' in /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29
Stack trace:
#0 /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(29): ReflectionParameter->getClass()
#1 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Tools\\S...')
#2 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Tools\\S...')
#3 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#4 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#5 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'storeManager', 'Magento\\Tools\\S...')
#6 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#7 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#8 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#9 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'customerSetup', 'Magento\\Tools\\S...')
#10 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#11 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...', Array)
#12 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/SetupFactory.php(38): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Tools\\S...')
#13 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(82): Magento\Tools\SampleData\SetupFactory->create('Magento\\Tools\\S...')
#14 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/InstallerApp.php(96): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#15 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Tools\SampleData\InstallerApp->launch()
#16 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/install.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Tools\SampleData\InstallerApp))
#17 {main}

Next exception 'ReflectionException' with message 'Class Magento\Framework\Store\StoreManagerInterface does not exist' in /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:37
Stack trace:
#0 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Tools\\S...')
#1 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Tools\\S...')
#2 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#3 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#4 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'storeManager', 'Magento\\Tools\\S...')
#5 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#6 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#7 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#8 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'customerSetup', 'Magento\\Tools\\S...')
#9 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#10 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...', Array)
#11 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/SetupFactory.php(38): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Tools\\S...')
#12 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(82): Magento\Tools\SampleData\SetupFactory->create('Magento\\Tools\\S...')
#13 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/InstallerApp.php(96): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#14 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Tools\SampleData\InstallerApp->launch()
#15 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/install.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Tools\SampleData\InstallerApp))
```

**Comment by voleye** [comment]
@refaelgold 
This Interface was moved to model in framework version beta9 and sample data version beta7
Please, check the versions you used
Also it can be a problem with DI cache so just remove it from var folder

**Comment by refaelgold** [comment]
thanks

what i need to replace in my composer.json? 
can i have the line i should have replace and with what ? 

thanks

**Comment by akhan522** [comment]
Hello!

I am getting an error when trying to add a new attribute. I can add the attribute fields but when I save it I get error saying "class Magento\Framework\Serialize\Serializer\json does not exist". 
Can anyone help me please?
![unnamed](https://user-images.githubusercontent.com/30791760/29102068-d8fe93c0-7c73-11e7-9e42-04a2faec3f43.png)

**Comment by Ctucker9233** [comment]
@akhan522 How did you install? With composer or .zip/CLI?
