### ISSUE TITLE
Provide an OpenTracing implementation for the Magento profiler

### ISSUE THREAD

**Issue by andrewhowdencom** [magento/magento2#10336]
### Preconditions

1. 2
2. Not relevant

### Request

Currently, the Magento 2 profiler is abstracted such that it can either be expressed as a CSV or as something interpreted by Firebug. However, a cursory glance of this indicates that it is possible Magento could implement support for the OpenTracing stack also.

http://opentracing.io/

This support may be later extended to pass the trace all the way through the stack from the webserver to downstream services, and can be consumed with tooling such as zipkin or appdash. This may help debugging problems in a production environment without the use of callgraph profilers such as blackfire et. al.

**Comment by orlangur** [comment]
Is there any reason to not use Blackfire?

**Comment by andrewhowdencom** [comment]
So, only money. But more generally the OpenTracing standard is a cross applications standard for measuring performance; usually among microservices, but there's no reason it would not work here. It comes with the inherent niceties of adopting a standardised approach:

- Common, usually superior tooling
- Free tools to support it (zipkin) 
- Local replicability

Using blackfire or new relic inherently builds a dependency on these organisations, which I'd like to try and avoid. I don't have the same problem with (for example) tideways, as their traces are XHPROF compatible. 

I haven't really looked at the feasibility of this yet. It's well in the "this would be cool" column -- it might not even make sense. But I like setting up the issues early, in case other people are similarly inclined.

**Comment by orlangur** [comment]
It looks like this issue didn't get much attention here...

GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.
