### ISSUE TITLE
Break in address in order grid when using multiple address lines

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#10330]
When a Magento installation uses multiple address lines, these lines are seperated with an HTML break element (`<br/>`) in the order grid in the admin, instead of a space. The HTML code of the break element is also visible in the grid.

### Preconditions

1. Tested on Magento 2.1.5
2. Installation uses PHP 7.0.17 on nginx and MySQL 5.7.18

### Steps to reproduce

1. Make sure the installation uses two or more address lines.
2. Create an order where the address uses two or more address lines.
3. Go to the order grid in the admin.

### Expected result

1. The address should be formatted in a readable way.

### Actual result

1. The address lines are seperated by an HTML break which is also visible.
![image](https://user-images.githubusercontent.com/6915990/28616095-aedc93a8-71fb-11e7-800d-e699bdf4e5b8.png)

**Comment by southerncomputer** [comment]
yes i noticed this as well! 2.1.7

**Comment by Quinten** [comment]
I noticed this in the 2.2-develop branch as well. @okorshenko I'll try to fix it.
