### ISSUE TITLE
Product category URL Keys do not take store view specific URL key in mind

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#10348]
### Preconditions
1. Install latest Magento 2.1.X version
2. Have multiple storeviews setup
3. Change the scope of the URL key field to the store view specific level

### Steps to reproduce
1.  Create a category and on the store view level change the URL key to something different. In my example the URL key in the global scope is "music" on  the storeview level it's "muziek"
2. Add a product to the category in the global scope and save the category.
3. Check the URL's generated in the url_rewrite table in the database.

### Expected result
1. URL keys generated should take the store view specific URL key into account. So for this particular category I would expect products to have the following URL key:
products/**muziek**/single-presley-elvis.html

### Actual result
1. The following has been added to the database for the specific store: 
products/music/single-presley-elvis.html

![image](https://user-images.githubusercontent.com/1058480/28662213-9fe80486-72b9-11e7-9f47-4ea8be4b6821.png)

![image](https://user-images.githubusercontent.com/1058480/28662204-9aac88a2-72b9-11e7-8d15-03a0886ad5dd.png)

**Comment by magento-engcom-team** [comment]
@dverkade, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
