### ISSUE TITLE
problems with jquery plugins

### ISSUE THREAD

**Issue by Antonioele** [magento/magento2#1034]
Magento The version is 0.42.0-beta7 with sample data
in luma/Magento_Theme/layout I have insert file default_head_blocks.xml :
in the head  I have insert
<head>
        
        <css src="css/camera.css"/>
        <script src="camera.js"/>
</head>

1° problem :
camera.js there is in pub/static/frontend/Magento/luma/it_IT

I see whith firebug
 some times load camera.js  at other times do not.
problem layout magento and requirejs ??????????
 2° problem
I have create block camera with widget camera 
but some times when I call camera plugin I have this  problem: jquery not found
magento load first camera.js or block camera and after jquery.

**Comment by antonkril** [comment]
You should use data-mage-init attribute on your widget node to initialize your camera widget. Its source file will be automatically loaded by requirejs.  (see http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/javascript/js-mage-plugin.html#fedg_js-mage_widgets_dataattrib)

To make your widget load after jquery, declare jquery as a dependency in your widget (http://requirejs.org/docs/api.html#funcmodule)

**Comment by vpelipenko** [comment]
@Antonioele, did @antonkril comment solve your problem?

**Comment by Antonioele** [comment]
@vpelipenko , I solve my problem with the help of antonkril , using requirejs , sorry if I insist, it is not advisable to use the layout to load jquery plugins, it would be comfortable as in magento 1.9.

**Comment by vpelipenko** [comment]
@Antonioele, due to last changes in the framework, it is strongly recommended now to use requirejs to load any js plugins.

**Comment by vpelipenko** [comment]
@Antonioele, do you have other questions about plugins? if no, can we assume this issue resolved?

**Comment by vpelipenko** [comment]
@Antonioele, this issue will be closed. I hope we've helped you to resolve your problem. If you have any other problems or questions about jquery plugins, feel free to reopen this issue or create new one.
