### ISSUE TITLE
Table Does Not Exist When Running Reindex

### ISSUE THREAD

**Issue by ooples** [magento/magento2#10344]
I'm using magento 2.1.7 and I'm getting the following errors when I run the reindex command (I reset the indexers first) and I'm not sure how these tables got deleted or how to create them so please let me know

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/eiYjL.jpg

**Comment by southerncomputer** [comment]
did you create a dummy website? then delete it?

If so, you may wish to drop the whole database and re-install to make sure things are created properly!

**Comment by ooples** [comment]
I don't believe I ever created a dummy website. What command do I need to
run to fix this?

**Comment by southerncomputer** [comment]
Try changing the indexers from update on schedule to update on save and then try reindexing!
You may need to flip/flop them a couple of times!

**Comment by ooples** [comment]
That worked so thank you!
