### ISSUE TITLE
'Cannot read property 'sjcl' of undefined'

### ISSUE THREAD

**Issue by ongwle** [magento/magento2#10349]
### Preconditions

1. Magento 2
2. PHP7.0

I have enabled Braintree payment. When I proceed to the checkout page, the Braintree payment method did not appear. In the browser console, it throws js error in attached screenshot.
Braintree : sandbox

![screen shot 2017-07-27 at 5 34 38 pm](https://user-images.githubusercontent.com/4442874/28664206-287928c4-72f2-11e7-8324-7b3700f661da.png)
![screen shot 2017-07-27 at 5 35 48 pm](https://user-images.githubusercontent.com/4442874/28664217-32e2f81c-72f2-11e7-8114-a854bcbce505.png)
![screen shot 2017-07-27 at 5 49 31 pm](https://user-images.githubusercontent.com/4442874/28664747-018c8308-72f4-11e7-9ed6-9f6d502e0dcf.png)

**Comment by orlangur** [comment]
Magento cannot fix errors on [Braintree side](https://js.braintreegateway.com/js/braintree-2.32.0.min.js). Similar issue was reported as https://github.com/braintree/braintree-web/issues/228 without clear reproducible steps.

Are you able to replicate issue on clean Magento 2 installation?

**Comment by orlangur** [comment]
Closing for now due to no reply for more than two weeks. Please provide more details if you will be able to reproduce issue on clean Magento 2 installation.

**Comment by webspeaks** [comment]
Just for info, this issue occurs in Magento 2.2.5. Not sure if Magento should look into it.
