### ISSUE TITLE
Quality drops and transparency replaced with solid color when uploading .png with transparent background

### ISSUE THREAD

**Issue by MichaelJamesParsons** [magento/magento2#10343]
### Preconditions

1. Magento 2.1.7
2. PHP 7.1

### Steps to reproduce

1. Navigate to "add new CMS page" view of the admin panel
2. Using the WYSIWYG editor, click "insert/edit image"
3. Click the "browse" button
4. Upload an image with colored text over a transparent background
5. Insert the image and save

### Expected result

1. The image should be inserted into the CMS page without any loss in quality, and should keep a transparent background.

### Actual result

1. The image is inserted into  the CMS page, but there is a very noticeable loss in quality (the colored portions of the image look rough). All transparent layers are replaced with solid black.

##### Original Transparent Image
![28398027-c9dd62a8-6cca-11e7-8354-6368d691c4a7](https://user-images.githubusercontent.com/2666285/28650402-5e41fa5a-7241-11e7-9ccf-a95be5e20e0a.png)

##### Post-Upload Image

![28398006-ad37aad2-6cca-11e7-89ff-528df066bb88](https://user-images.githubusercontent.com/2666285/28650417-765b5e42-7241-11e7-9284-f0c3aa10dbb3.png)

### Related Issues

https://github.com/magento/magento2/issues/5401
https://github.com/magento/magento2/issues/2312

### Attempts to fix

https://github.com/magento/magento2/pull/7307

**Comment by orlangur** [comment]
Did mentioned fix solve your problem in `develop` after all?

**Comment by MichaelJamesParsons** [comment]
@orlangur Version 2.1.7 does not include [the fix](https://github.com/magento/magento2/pull/7307).

### Magento 2.1.7
[Gd2.php Line 349](https://github.com/magento/magento2/blob/2.1.7/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L349)
[ImageMagick.php Line 171](https://github.com/magento/magento2/blob/2.1.7/lib/internal/Magento/Framework/Image/Adapter/ImageMagick.php#L171)

**vs**

### Development
[Gd2.php Line 349](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L349)
[ImageMagick.php Line 171](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Image/Adapter/ImageMagick.php#L171)

I am hesitant to use the dev branch in production. Are there any plans in the near future to include that fix in 2.1.*?

**Comment by orlangur** [comment]
@MichaelJamesParsons, yeah, that's why I was asking about `develop` branch.

The fix was backported to `2.1.x` in https://github.com/magento/magento2/pull/9662 and will be released in [2.1.8](https://github.com/magento/magento2/blob/2.1.8-preview/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L349) 😉

**Comment by MichaelJamesParsons** [comment]
@orlangur Is there an official release date for 2.1.8?

**Comment by orlangur** [comment]
Yesterday :)

**Comment by magento-engcom-team** [comment]
@MichaelJamesParsons, thank you for your report.
The fix for this issue is already available in the 2.1, 2.2 and develop branches.

**Comment by artskeem** [comment]
Magento 2.2 is having the same problems - using a fresh install with no errors - and using image magic
