### ISSUE TITLE
URL key "use default" & "Create Permanent Redirect for old URL" not consistent

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#10350]
### Preconditions
1. Install latest Magento 2.1.X version

### Steps to reproduce
1.  Check the category edit screen
2.  Check the product edit screen

### Expected result
1.  Consistent field behaviour. The order of the "Use default" field and the "Create Permanent Redirect for old URL" field should be the same for the category screen as well as the product screen. 
2. The text "Use default" is not consistent in all screens, should be "Use default" or "Use default value" for every screen. 

### Actual result
1. Order of the fields is different. 
2. The text is "Use default" instead of "Use default value" 

URL Key field when editing a category
![image](https://user-images.githubusercontent.com/1058480/28664505-05e813fa-72c1-11e7-9ece-03618eb7744b.png)

URL Key field when editing a product
![image](https://user-images.githubusercontent.com/1058480/28664506-060faf8c-72c1-11e7-96a4-e6ed0f9db9f5.png)

**Comment by magento-engcom-team** [comment]
@dverkade, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0

**Comment by dverkade** [comment]
Hi, tested this again and this is solved in 2.2, so this issue can be closed.
