### ISSUE TITLE
SQLSTATE[HY000]: General error: 1116 Too many tables; MariaDB can only use 61 tables in a join when doing mass update attributes on product admin grid 

### ISSUE THREAD

**Issue by calabanzas** [magento/magento2#10358]
When doing mass update attribute on the product admin grid, I am redirected to a page with no attribute fields options to update, see screenshot http://take.ms/klkyF

### Preconditions

1. Magento ver. 2.1.3
2. PHP 7.0 and mysql  Ver 15.1
3. Around 49000 products

### Steps to reproduce

1. On catalog product admin grid using "FILTERS" option (eg. Visibilty is CATALOG, SEARCH)
2. Then ticking on the mass action drop down menu either SELECT ALL or SELECT ALL on this PAGE
3. Under ACTIONS drop down menu, select UPDATE ATTRIBUTES and it will redirect to a page where there are no option for you to edit the attributes

### Expected result

1. Update Attributes page should be displayed along with its Product Information tab with attribute fields option, see screenshot http://take.ms/MzqME

### Actual result

1. See screenshot http://take.ms/klkyF and if you checked the log file, error below can be found  
SQLSTATE[HY000]: General error: 1116 Too many tables; MariaDB can only use 61 tables in a join

**Comment by AVoskoboinikov** [comment]
Hi @calabanzas 
We already have internal ticket for this issue - MAGETWO-63226.
As a workaround you can try to decrease number of products that you want to update at one time.

Thanks!

**Comment by calabanzas** [comment]
Hi @AzVo ,

Thanks for the reply.
Yes, as a workaround we are decreasing number of products to update.
Can we know when is the timeline for the patch to release?
Or better yet, do you have an accessible link for the ticket where we can see the updates/status?

**Comment by magento-engcom-team** [comment]
@calabanzas, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
