### ISSUE TITLE
Error installing sample data for magento v0.42.0-beta7 - sample data 0.42.0-beta6

### ISSUE THREAD

**Issue by mahesh004** [magento/magento2#1036]
I have successfully installed magento v0.42.0-beta7 without loading sample data during installation. After that I have added sample date in composer.json and updated it.

"magento/sample-data": "0.42.0-beta6",
"magento/sample-data-media": "~0.42.0-beta1"

Sample data files are created in \magento2\dev\tools\Magento\Tools\SampleData but got error. 

---------------------------------------------------------------
@MAHESH d:\xampp\htdocs\magento2
 composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/sample-data could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

----------------------------------------------------------------------------

I have added "minimum-stability": "dev", in composer.json but no use. I have attached the image for reference.

I have tried like beta7 also
"magento/sample-data": "0.42.0-beta7",
"magento/sample-data-media": "~0.42.0-beta1"

![sample-datat-error](https://cloud.githubusercontent.com/assets/10938283/6163275/e395f1be-b2b5-11e4-9eaf-1624e3dc5742.png)

**Comment by kokoc** [comment]
@mahesh004 Thank your for reporting the issue.

Could you please provide your composer.json content?

Internal reference - MAGETWO-34087

**Comment by voleye** [comment]
@mahesh004 Do you specified the repository http://packages.magento.com/ in your composer.json?

"repositories": [
        {
            "type": "composer",
            "url": "http://packages.magento.com/"
        }
    ]

**Comment by mahesh004** [comment]
Thanks for your attention. Here is my composer.json code.

{
    "name": "magento/project-community-edition",
    "description": "Magento project (Community Edition)",
    "type": "project",
    "version": "0.42.0-beta7",
	"minimum-stability": "dev",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "php": "~5.5.0|~5.6.0",
        "zendframework/zend-stdlib": "2.3.1",
        "zendframework/zend-code": "2.3.1",
        "zendframework/zend-server": "2.3.1",
        "zendframework/zend-soap": "2.3.1",
        "zendframework/zend-uri": "2.3.1",
        "zendframework/zend-validator": "2.3.1",
        "zendframework/zend-console": "2.3.1",
        "zendframework/zend-modulemanager": "2.3.1",
        "zendframework/zend-mvc": "2.3.1",
        "zendframework/zend-text": "2.3.1",
        "zendframework/zend-eventmanager": "2.3.1",
        "zendframework/zend-view": "2.3.1",
        "zendframework/zend-servicemanager": "2.3.1",
        "zendframework/zend-json": "2.3.1",
        "zendframework/zend-config": "2.3.1",
        "zendframework/zend-form": "2.3.1",
        "zendframework/zend-di": "2.3.1",
        "zendframework/zend-serializer": "2.3.1",
        "zendframework/zend-log": "2.3.1",
        "zendframework/zend-http": "2.3.1",
        "magento/zendframework1": "1.12.9-patch1",
        "composer/composer": "1.0.0-alpha8",
        "monolog/monolog": "1.11.0",
        "tubalmartin/cssmin": "2.4.8-p4",
	"magento/sample-data": "0.42.0-beta6",
	"magento/sample-data-media": "~0.42.0-beta1"
    },
	"repositories": [
    {
        "type": "composer",
        "url": "http://packages.magento.com/"
    }
    ],
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "lib-libxml": "*",
        "ext-ctype": "*",
        "ext-gd": "*",
        "ext-spl": "*",
        "ext-dom": "*",
        "ext-simplexml": "*",
        "ext-mcrypt": "*",
        "ext-hash": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3"
    },
    "replace": {
        "magento/module-admin-notification": "self.version",
        "magento/module-authorization": "self.version",
        "magento/module-backend": "self.version",
        "magento/module-backup": "self.version",
        "magento/module-bundle": "self.version",
        "magento/module-captcha": "self.version",
        "magento/module-catalog": "self.version",
        "magento/module-catalog-import-export": "self.version",
        "magento/module-catalog-inventory": "self.version",
        "magento/module-catalog-rule": "self.version",
        "magento/module-catalog-search": "self.version",
        "magento/module-catalog-url-rewrite": "self.version",
        "magento/module-catalog-widget": "self.version",
        "magento/module-centinel": "self.version",
        "magento/module-checkout": "self.version",
        "magento/module-checkout-agreements": "self.version",
        "magento/module-cms": "self.version",
        "magento/module-cms-url-rewrite": "self.version",
        "magento/module-configurable-import-export": "self.version",
        "magento/module-configurable-product": "self.version",
        "magento/module-contact": "self.version",
        "magento/module-core": "self.version",
        "magento/module-cron": "self.version",
        "magento/module-currency-symbol": "self.version",
        "magento/module-customer": "self.version",
        "magento/module-customer-import-export": "self.version",
        "magento/module-design-editor": "self.version",
        "magento/module-developer": "self.version",
        "magento/module-dhl": "self.version",
        "magento/module-directory": "self.version",
        "magento/module-downloadable": "self.version",
        "magento/module-eav": "self.version",
        "magento/module-email": "self.version",
        "magento/module-fedex": "self.version",
        "magento/module-gift-message": "self.version",
        "magento/module-google-adwords": "self.version",
        "magento/module-google-analytics": "self.version",
        "magento/module-google-optimizer": "self.version",
        "magento/module-google-shopping": "self.version",
        "magento/module-grouped-import-export": "self.version",
        "magento/module-grouped-product": "self.version",
        "magento/module-import-export": "self.version",
        "magento/module-indexer": "self.version",
        "magento/module-integration": "self.version",
        "magento/module-layered-navigation": "self.version",
        "magento/module-log": "self.version",
        "magento/module-msrp": "self.version",
        "magento/module-multishipping": "self.version",
        "magento/module-newsletter": "self.version",
        "magento/module-offline-payments": "self.version",
        "magento/module-offline-shipping": "self.version",
        "magento/module-page-cache": "self.version",
        "magento/module-payment": "self.version",
        "magento/module-persistent": "self.version",
        "magento/module-product-alert": "self.version",
        "magento/module-quote": "self.version",
        "magento/module-reports": "self.version",
        "magento/module-require-js": "self.version",
        "magento/module-review": "self.version",
        "magento/module-rss": "self.version",
        "magento/module-rule": "self.version",
        "magento/module-sales": "self.version",
        "magento/module-sales-rule": "self.version",
        "magento/module-search": "self.version",
        "magento/module-sendfriend": "self.version",
        "magento/module-shipping": "self.version",
        "magento/module-sitemap": "self.version",
        "magento/module-store": "self.version",
        "magento/module-tax": "self.version",
        "magento/module-tax-import-export": "self.version",
        "magento/module-theme": "self.version",
        "magento/module-translation": "self.version",
        "magento/module-ui": "self.version",
        "magento/module-ups": "self.version",
        "magento/module-url-rewrite": "self.version",
        "magento/module-user": "self.version",
        "magento/module-usps": "self.version",
        "magento/module-webapi": "self.version",
        "magento/module-weee": "self.version",
        "magento/module-widget": "self.version",
        "magento/module-wishlist": "self.version",
        "magento/theme-adminhtml-backend": "self.version",
        "magento/theme-frontend-blank": "self.version",
        "magento/theme-frontend-luma": "self.version",
        "magento/language-de_de": "self.version",
        "magento/language-en_us": "self.version",
        "magento/language-es_es": "self.version",
        "magento/language-fr_fr": "self.version",
        "magento/language-nl_nl": "self.version",
        "magento/language-pt_br": "self.version",
        "magento/language-zh_cn": "self.version",
        "magento/framework": "self.version",
        "oyejorge/less.php": "1.7.0",
        "trentrichardson/jquery-timepicker-addon": "1.4.3",
        "components/handlebars.js": "1.3.0",
        "colinmollenhour/cache-backend-redis": "dev-master#193d377b7fb2e88595578b282fa01a62d1185abc",
        "colinmollenhour/credis": "dev-master#f07bbfd4117294f462f0fb19c49221d350bf396f",
        "linkorb/jsmin-php": "1.1.2",
        "phpseclib/phpseclib": "0.2.1",
        "components/jquery": "1.11.0",
        "blueimp/jquery-file-upload": "5.6.14",
        "components/jqueryui": "1.10.4",
        "twbs/bootstrap": "3.1.0",
        "tinymce/tinymce": "3.4.7"
    },
    "extra": {
        "component_paths": {
            "oyejorge/less.php": "lib/internal/Less",
            "trentrichardson/jquery-timepicker-addon": "lib/web/jquery/jquery-ui-timepicker-addon.js",
            "components/handlebars.js": "lib/web/jquery/handlebars",
            "colinmollenhour/cache-backend-redis": "lib/internal/Cm/Cache/Backend/Redis.php",
            "colinmollenhour/credis": "lib/internal/Credis",
            "linkorb/jsmin-php": "lib/internal/JSMin",
            "phpseclib/phpseclib": "lib/internal/phpseclib",
            "components/jquery": [
                "lib/web/jquery.js",
                "lib/web/jquery/jquery.min.js",
                "lib/web/jquery/jquery-migrate.js",
                "lib/web/jquery/jquery-migrate.min.js"
            ],
            "blueimp/jquery-file-upload": "lib/web/jquery/fileUploader",
            "components/jqueryui": [
                "lib/web/jquery/jquery-ui.js",
                "lib/web/jquery/jquery-ui.min.js"
            ],
            "twbs/bootstrap": [
                "lib/web/jquery/jquery.tabs.js"
            ],
            "tinymce/tinymce": "lib/web/tiny_mce"
        }
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\ToolkitFramework\\": "dev/tools/performance-toolkit/framework/Magento/ToolkitFramework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/"
        }
    }
}

**Comment by voleye** [comment]
@mahesh004 

In the description above you described 

>Problem 1
>- The requested package magento/sample-data could not be found in any version, there may be a
> typo in the package name.

But from the print screen image I can see the different error message about problems with packages:
 - magento/framework
 - magento/sample-data-media

Could you please clarify which exactly error do you have?
