### ISSUE TITLE
SKU attribute non-Default label is not reflected on the storefront

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10368]
### Steps to reproduce

1. Navigate to Admin Panel > Stores > Attributes > Product
2. Filter the grid for "sku" attribute and click to edit the "sku" attribute
3. Click the Manage Labels tab and enter a value (e.g. Item) for the attribute label on Default Store View column
4. Save it and observe the SKU label on Product Detail Page on the storefront

### Expected result

On the Product Detail Page on the storefront, instead of the default label `SKU# ABC123` we should see the updated label as per above instruction, in this case, `Item# ABC123`.

### Actual result

The label of SKU attribute does not change the default value on Product Detail Page on the storefront.

### More info
However, by changing the Default Label for the SKU attribute will reflect the changes on Product Detail Page on the storefront. 

It seems that the current implementation for displaying SKU (and possibly other) attributes on the Product Detail Page on the storefront does not take into consideration the values entered under Manage Labels as described above under Steps to reproduce. 

Updated info:
Magento 2.2.0

**Comment by orlangur** [comment]
Isn't this behavior configurable via https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml#L41?

**Comment by ghost** [comment]
@orlangur please read the issue description again. 
Everything can be done via code in Magento but that's not the point. What you are suggesting is defeating the purpose of using the administration panel's attribute configuration to change attribute labels.

**Comment by orlangur** [comment]
I'm saying that at first glance making this configuration node empty will fix the "bug".

But it would be nice to understand why it was set to `default` in the first place.

**Comment by okorshenko** [comment]
@alexgifts thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version

**Comment by magento-engcom-team** [comment]
@alexgifts, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
