### ISSUE TITLE
Magento 2 Insert Static Block to wysiwyg editor do not renders html in the editor mode.

### ISSUE THREAD

**Issue by anujeetphj** [magento/magento2#10364]
### Preconditions
I am using Magento 2.1.3

### Steps to reproduce

1. In the product description, HTML is used. There is quite HTML that is rendered and the client does not know how to work in HTML. So he works in the wysiwyg editor mode.

2. So I planned to divide HTML into a number static blocks and he can insert it as a widget in the product description.

### Expected result
Static block's HTML is rendered and is shown in Editor mode

### Actual result
Instead of the HTML, an image and text 'static block' is rendered. How can one know which block is rendered from this? If someone wants to position them up or down, how he will know which block has which content , as  with 'static block' nothing can be understood.

Please solve this problem, insetad of this text 'static block' use bock title , so that one can know which block he has inserted.

Thanks

**Comment by magento-engcom-team** [comment]
Hi @anujeetphj please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only. If you would like to have this feature, feel free submit the pull request! 👍

**Comment by magefan** [comment]
You can use this solution [magefan/module-catalog](https://github.com/magefan/module-catalog).
