### ISSUE TITLE
Is local.xml present in Magento 2 theme?

### ISSUE THREAD

**Issue by mahesh004** [magento/magento2#1037]
I am trying to add .phtml file to home page content area. I used the following code

`<referenceContainer name="content">
            <block class="Magento\Framework\View\Element\Template" name="html_home" as="html_home" template="Magento_Theme::html/home.phtml"/>
</referenceContainer>`

This is working in Admin-> Pages's layout, default.xml file in \magento2\app\design\frontend\Magento\MyTheme\Magento_Theme\layout and default.xml file in \magento2\app\code\Magento\Theme\view\frontend\layout.

I put code in local.xml but it is not working. I wonder local.xml present or not in Magento 2.

**Comment by vpelipenko** [comment]
@mahesh004, thank you for posting this issue, but could you clarify where did you put the local.xml?

**Comment by mahesh004** [comment]
I have tried in three places
1) \magento2\app\design\frontend\Magento\MyTheme\Magento_Theme\layout
2) \magento2\app\design\frontend\Magento\MyTheme\etc (Working theme)
3) \magento2\app\code\Magento\Theme\view\frontend\layout

for 1 and 3 I put the code in default.xml and it worked.

**Comment by villageseo** [comment]
Hi mahesh004!

local.xml is not present in Magento 2 themes anymore. 

Documentation about new Magento 2 layout structure can be read here: 
http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/layouts/layout-overview.html 

Thank you for the question.

**Comment by mahesh004** [comment]
Hi @villageseo 

Thank you for your answer.
