### ISSUE TITLE
Can i access Magento 2.1.7 admin URL with domain name and as well as ip address

### ISSUE THREAD

**Issue by arunkumar2687** [magento/magento2#10371]
### Preconditions

1. 
2. 

### Steps to reproduce

1. http://yourdomain.com/admin_12345
2. http://youripaddress/admin_12345
3. 

### Expected result

1. You should be able to load admin by using ipaddress or domain name

### Actual result

1. [Screenshot, logs]
But its loading only what ever URL configured in core_config_data table, if ip is configure for 'admin/url/custom' it will work fine with IP address, if domain name is configured in 'admin/url/custom' it will work fine with domain name

Please let me know any insight about this! thanks in advance

**Comment by orlangur** [comment]
No, you cannot. Why do you need that?

But, you can deploy Magento on `http://yourdomain.com` and then specify `youripaddress` in your `/etc/hosts` locally. So that browser will open corresponding domain from correct IP address.

**Comment by arunkumar2687** [comment]
Hi Orlangur,

The scenario is this, 

We are trying to give a our admin URL accessible to just one vendor who uses our magento admin through his modules to send and receive curl post.

But our magento admin is in a private instance in a AWS. What we are trying to do is to create a public accessible load balancer with that private instance registered to it and restrict the access through the inbound and outbound rules only for that particular vendor's IP address range.

can you let me know your thoughts on how to allow restricted access to magento admin?

Thanks

**Comment by southerncomputer** [comment]
https://github.com/magespecialist/m2-MSP_AdminRestriction 

I use this to restrict access by ip range!

**Comment by arunkumar2687** [comment]
Thanks Man, I will try this and let you know whether it works for me! Appreciate it!

**Comment by magento-engcom-team** [comment]
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
