### ISSUE TITLE
Unable to upload Visual Swatch image on Magento 2.1.7

### ISSUE THREAD

**Issue by ebubekirkaragol** [magento/magento2#10379]
### Preconditions

1. Magento 2.1.7
2. PHP 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce

1. Create a visual swatch attribute
2. Select Visual Swatch from drop down menu for 'Catalog Input Type for Store Owner' option 
3. Click add swatch button
4. Select Upload File from Swatch drop down menu
5. Select file to upload.

### Expected result

1. Uploaded file is shown in Manage Swatch section

### Actual result

1. File uploaded to "root_directory/pub/media/catalog/product/a/l/al-image.jpg" path.
2. But image doesn't shown in Manage Swatch section. 
3. It's uploaded on server but not working with that attribute.

**Comment by lexwet** [comment]
Maybe you have a similar problem as here #9849

Try to disable EAV cache. Flush the cache. 
Can you see the image in Manage Swatch section?

**Comment by ebubekirkaragol** [comment]
I tried it, but didn't work. 

I also tried to disable all cache types. Then flushed tha cache. But still i can not see any image in Manage Swatch section.

**Comment by magento-engcom-team** [comment]
@ebubekirkaragol, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by lammanh0405** [comment]
In file vendor/magento/module-swatches/view/adminhtml/web/js/visual.js 
Change this code "var imageParams = $.parseJSON($(this).contents().find('body').html())" 
to "var imageParams = $.parseJSON(this.contentWindow.document.body.innerHTML)"

Hope this helps.
