### ISSUE TITLE
Magento 2 Minimum order value  in Free Shipping not working.

### ISSUE THREAD

**Issue by albertoedigital** [magento/magento2#10384]
I set the minimum order value in tab Free Shipping of Shipping Method but it is not working. I
I can select this method on the checkout page even if the condition is not established. My version of Magento is 2.1.5 

Best regards.

**Comment by cirilloblu** [comment]
Same problem here, Magento 2.1.7

**Comment by vherasymenko** [comment]
@albertoedigital , thank you for your report.
Please use the issue reporting guidelines to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by albertoedigital** [comment]
I solved through the following link :https://github.com/magento/magento2/issues/7672.

_"@dimitrovv This fixed it for us: Setting Stores > Configuration > Customer > Customer Configuration > Name and Address Options: Number of Lines in a Street Address make it 1. #4921"_

But it was necessary to create a new client to work.
