### ISSUE TITLE
System Messages Block in Admin panel is annoying.

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#10389]
Magento 2.2.0-dev

The System Messages Block moves the page down when it appears. It is annoying such as it happens on each page.
It is not always possible to perform suggested actions, so the messages appear and shift page in 1-2s after it's loaded.

Is it possible to change this behavior?
For example, show amount of messages without shifting a whole page?
<img width="1318" alt="screen shot 2017-08-01 at 11 16 53" src="https://user-images.githubusercontent.com/6418650/28815905-9a910802-76ab-11e7-939a-4893d6b07e54.png">

Thanks!

**Comment by magento-engcom-team** [comment]
@ytorbyk thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
Hi @ytorbyk 
The best way to address the issue is to create a pull request. You are very experienced Magento 2 developer, so you can help us with this issue. We are looking for pull request from you 👍

**Comment by vapopov** [comment]
![](http://cs4.pikabu.ru/images/big_size_comm/2014-07_4/14055817207938.png)

**Comment by magento-engcom-team** [comment]
@ytorbyk, thank you for your report.
We've created internal ticket(s) MAGETWO-84415 to track progress on the issue.

**Comment by orbitrod** [comment]
Until a proper fix can be rolled out, I created a userscript  to fix this problem using Tampermonkey.   For those that do not know what Tampermonkey is, it is a userscript manager browser extension, that allows users to install scripts that make on-the-fly changes to web page content after or before the page is loaded in the browser.

Here is the script
https://github.com/EnochDataSystems/gists/blob/master/magento2-system_messages-fix.js

The script will reduce the width of the systemMessageBlock and move it to the top left corner.   When the systemMessageBlock is loaded, it will hover over any text or elements in that corner, but after 5 seconds it will fade away.

This is an easy quick fix and doesn't involve touching the Magento code.

**Comment by magento-engcom-team** [comment]
@ytorbyk, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
