### ISSUE TITLE
updating products breaks shopping cart with pre-existing items

### ISSUE THREAD

**Issue by steros** [magento/magento2#10392]
### Preconditions
1. Magento 2.1.7 
2. PHP 7.0
3. Apache 2.4.10
4. MariaDB 10.0.30

### Steps to reproduce
1. place an item into the cart
2. change the product of that item (ie. upload a video or change the description text)
3. place another item of that product into the cart
4. go to the cart

### Expected result
1. you have a button to proceed to the checkout

### Actual result
1. there is not "proceed to checkout" button

### "Fix"
1. remove the item that you placed AFTER you changed the product
2. the button is still missing
3. add another item of that product
4. the button is still missing
5. remove the item that you placed BEFORE you changed the product
6. the button now appears

As there is no error message or hint at all what is wrong this creates much confusion.
I guess if there is a hard link between products in the cart and products in different versions in the database. All carts should be pruned that have those products upon updating the product in the backend.

**Comment by EmilyPepperman** [comment]
We have a similar issue. We have been reorganizing and changing how some of our products are configured... if a customer has any of the products that we just changed in their shopping cart it breaks their shopping cart badly. It will just show part of the tax and shipping estimate box and that is all. Magento 2 should be smart enough to update those products in the cart or at least not break the shopping cart from proceeding to place the order.

**Comment by magento-engcom-team** [comment]
@steros, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
