### ISSUE TITLE
Product Bundle Items can't have a decimal default quantity

### ISSUE THREAD

**Issue by thatguynz** [magento/magento2#10399]
### Preconditions

1.  Magento 2.1.7
2. 

### Steps to reproduce

1.  Create a number of simple products - each with decimals enabled
2.  Create a new bundled product and add the simple products to it as Bundled Items
3.  Try to set default quantity of Bundled Items to a decimal value

### Expected result

1.  Default quantity of bundled item should enter fine as a decimal (as it used to in Magento 1.9) and allow Product Bundle to be saved

### Actual result

1.  Error message is displayed directly below default quantity box (attached) "Please enter a valid number in this field." and product bundle can not be saved.
![error](https://user-images.githubusercontent.com/6167770/28853152-a6dbed84-7782-11e7-8d6e-dc54d5304d6a.png)

**Comment by choukalos** [comment]
This is a feature request;  Tagging so automated system moves to forum/feature request list.

**Comment by thatguynz** [comment]
choulakos: Respectfully, I disagree that this is a feature request as opposed to a defect for a couple of reasons.  
Firstly, the expected behaviour is precisely how the previous release of Magento behaved so it wouldn't be unreasonable to expect the current version doesn't regress on functional capability.
Secondly, it doesn't make a lot of sense to have the capability to maintain decimal quantities for products and then not support that function in every use case. 
Lastly, given the database structure stores the field as a decimal, the implementation has erred in error checking the field as an integer - surely that would constitute a defect?

Kind regards.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-Bundle-Items-can-t-have-a-decimal-default-quantity/idi-p/73599).
