### ISSUE TITLE
Order get free shipping without fulfilling the conditions. 

### ISSUE THREAD

**Issue by vishveskrish** [magento/magento2#10394]
### Preconditions

1. Magento 2.1.6
2. PHP 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce

1. Create free-shipping rule from the promotion rules.
2. Set the condition which must need to satisfy before applying the rule. example total must be 500 or greater as well as only for the California shipping.
3. Add to cart products with subtotal 500 and go to the checkout.
4. Rule satisfied both conditions so it shows free-shipping applies which is correct.
5. Now We are able to replicate this in two cases, 
	a.) first case user updating the shipping address without California and place the order. It takes free-shipping.  
	b.) Second, Total was 500 and customer already on last step to place an order, Now Customer updates the cart total by opening the site in the different browser window. After that total is 100 and user refresh the last step of the previous browser window. Total get updated but still, it takes free-shipping 0.0.
 
### Expected result

1.  It should not takes free-shipping as total get updated below 500.

### Actual result

1. It allows the customer to checkout with free shipping.

**Comment by Turv** [comment]
Same issue as #6040

**Comment by magento-engcom-team** [comment]
@vishveskrish, thank you for your report.
We've created internal ticket(s) MAGETWO-80335 to track progress on the issue.

**Comment by apotdar** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by vishveskrish** [comment]
Hello @magento-engcom-team,

Do we get the resolution?

**Comment by apotdar** [comment]
Ran into issues on my local vm instance and I got a new vm up and running.  Working on it.  Sorry for the delay.

**Comment by ashishjob0424** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
@ashishjob0424 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ashishjob0424** [comment]
@vishveskrish 
As this was an old issue and no update on this issue from you or any other member, looks like issue is fixed now in updated release.
I tried to reproduce the issue in 2.3-develop branch but unable to reproduced.
As far as your steps is concerns.
- Magento saves address into quotes only after selecting shipping method and navigating to payment method step. So to apply cart rule based on address you have only two options either fill all details and after selecting shipping method navigate back to cart page and apply code or apply code from payment method. 
- In your case whenever you update address from shipping method step which is non California it will regenerate shipping charges so no chance of getting free shipping.
- In second case where total updated from other tab. In 2.3-develop all totals are also getting updated properly as well as shipping cost also charged in totals.

I am closing this as both above scenario are not reproducible.
