### ISSUE TITLE
Magento/Catalog/Plugin/Block/Topmenu.php does not follow single responsibility principle

### ISSUE THREAD

**Issue by SerhiyShkolyarenko** [magento/magento2#10401]
### Preconditions

Fresh mainline/develop branch.
Plugin Magento/Catalog/Plugin/Block/Topmenu.php has beforeGetHtml() and beforeGetIdentities() public methods.

### Steps to reproduce
1. Take a look at `Magento/Catalog/Plugin/Block/Topmenu.php`
2. Find `public function beforeGetHtml`
3. Find `public function beforeGetIdentities`

### Expected result
Plugin follows single responsibility principle and interferes only one method.
Method beforeGetIdentities should be moved to another plugin as far as it was added later.

### Actual result
One plugin interferes two methods.

**Comment by orlangur** [comment]
Whether you override multiple methods of class or only one, it has nothing to do with SRP actually.

Both mentioned methods use `getCategoryTree` implementation, the worst you could do here is creating two different plugin classes with duplicated implementation.

Nevertheless, this category mangling logic could be refactored to a separate class making this plugin much more tiny. But, again, this has nothing to do with SRP violation, while it was decided that `Topmenu` class is responsible for both HTML rendering and providing identities for FPC, any such plugin is perfectly valid.

More than that, splitting this plugin into two or more classes by interfered methods will break the class encapsulation which is a much bigger problem than fictional "SRP violation".

**Comment by magento-engcom-team** [comment]
@SerhiyShkolyarenko, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
