### ISSUE TITLE
Reindex catalog_product_flat takes 17min for 22000 products. Is it ok?

### ISSUE THREAD

**Issue by brswdeveloper** [magento/magento2#10405]
### Preconditions:
 ssd, i7 processor
Ubuntu 16.04 desktop (local machine)
Mysql 5.7.18
PHP 7.0.18
Mgento 2.1.7 EE
No additional package dependencies, original m2 composer.json
app/code folder is empty
Product count ~22000
culumns count going to catalog_product_flat_1 table is 83
attributes count for product entity - 185

### Steps to reproduce
php bin/magento indexer:reindex catalog_product_flat

### Expected result
More faster

### Actual result
Duration: 17min

### Additional information:
The result on customer server is about the same. What will be when product count rises? We would like to get advice about performance or confirmation that it is normal for Magento 2 EE for our customer

**Comment by choukalos** [comment]
Hi @brswdeveloper - we've updated our performance optimization recommendations.  We no longer recommend using the 'flat' settings - [DevDocs Optimization Guide](http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_perf-optimize.html).  We find performance increase is minimal now and are re-evaluating the approach (it's legacy from M1).  17min index time is fine.

In our upcoming 2.2.0 release we've done considerable work on indexers to speed them up for large effective sku count stores (effective sku count is how big Magento really thinks your DB is... it's a multiplicative function of # skus, #store views, #Customer Groups/Shared Catalogs).  Bigger = longer index, url rewrite management.  We've updated the long running indexers so they run in batches and use a table aliasing approach to not impact store front while they're running.  This significantly improves index times for those larger effective sku count stores (our published profiles all index in 4h or less out of the box - that includes the 500k, 5 store view B2C large profile) and ensures customer traffic isn't impacted.  You can tweak batch size and MySQL configuration to speed that up as well in 2.2+ ([link](http://devdocs.magento.com/guides/v2.2/config-guide/prod/prod_perf-optimize.html)).

**Comment by orlangur** [comment]
@choukalos thanks for the information, however I didn't manage to find 'flat' mentioned in http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_perf-optimize.html or http://devdocs.magento.com/guides/v2.2/config-guide/prod/prod_perf-optimize.html. Is it something just not published yet?
