### ISSUE TITLE
Magento2 Cybersoure Payment success page 302 error

### ISSUE THREAD

**Issue by arunkumar2687** [magento/magento2#10408]
### Preconditions

1. Configured cybersource in magento 2.1.7 EE
2. 

### Steps to reproduce

1. Place an order
3. 

### Expected result

1. When i try to place order it process the payment and says "Sorry, but something went wrong."
2. but i can see the order on cybersource test business center, but the amount is always set to zero

### Actual result

1. [Screenshot, logs]
It should redirect to the success page. like /checkout/onepage/success/

![screen shot 2017-08-02 at 10 36 20 am](https://user-images.githubusercontent.com/26555200/28881666-7a4f7470-776e-11e7-8f19-e15f239e1a77.png)
![screen shot 2017-08-02 at 10 35 03 am](https://user-images.githubusercontent.com/26555200/28881673-7d710628-776e-11e7-9f7e-11a7cd8740c5.png)

**Comment by YevSent** [comment]
This Github repository only for issues related to the Magento Community Edition. Please, create a ticket in the Partner portal or via the Merchant account.

**Comment by davidduong90** [comment]
Hello @arunkumar2687,

Do you find the solution?
