### ISSUE TITLE
Magento\Catalog\Model\Product\Interceptor returned by repository after creation is missing ID

### ISSUE THREAD

**Issue by wintermute-84** [magento/magento2#10406]
I don't know if it is a bug or env. related issue.
I can't reproduce this locally to debug properly.
But on a remote server running in production mode I create a configurable with simples via custom service.
Simples are created first. Configurable last using the same method with addition of extension attributes.
When products get created using `$product = $this->productRepository->save($product)` - result simple $product has an id. Configurable how ever does not.

In the end all products are created, but I need to reload a product using $product->loadByAttribute('sku', $product->getSku()); if id is empty, because I need that id down the road.

Is ProductRepository::get() messing it up? I don't see how.

### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. Creating a new product with repository using 
$product = $this->productRepository->save($product);
2. Products are created in a loop, simples first, configurable last.

### Expected result

1. When simples are creates, id is returned,
2. $product->getId() should return and id when configurable is created as well.

### Actual result

1. returned $product is an instance of Magento\Catalog\Model\Product\Interceptor
but the id is empty.

**Comment by orlangur** [comment]
Returning `\Magento\Catalog\Model\Product\Interceptor` is correct when you have some plugins attached to product model.

Just set breakpoint in interceptor's `getId` method and debug every plugin in chain called before original `$product->getId()`.

**Comment by wintermute-84** [comment]
No, it's not related to the getId method
When product is saved using repository, ProductRepository::get() gets called multiple times.
Looks like on some occasion when creating a configurable the get() loads a simple product. (getTypeInstance()) returns Simple and then something fails down the road because getType is still configurable, but configurable specific functions can't be executed.

Will debug more to see why this might be happening.

**Comment by orlangur** [comment]
> I can't reproduce this locally to debug properly.

Did you manage to reproduce it reliably after all? I doubt it can be reproduced by anyone else without additional info.

**Comment by wintermute-84** [comment]
Unfortunately doing it as dev docs say is not an option.
Magento core itself is not using repositories probably for a reason - product repository save does not work in many cases as intended which is ridiculous. 
Ended up using model save() directly and wrapping it in custom code.

Don't know if this (and other repository save() related problems, like image save) is fixed in 2.2 as we are not spending more time to debug and using module resource directly.

So probably this can be just closed.

**Comment by orlangur** [comment]
Yeah, here is some insight: https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/EntityManager/EntityManager.php#L19

So, instead of using repositories for now you can rely on resource models, just like repositories mostly do currently. Thanks for the quick response!
