### ISSUE TITLE
Required date validation on magento2 Backend.

### ISSUE THREAD

**Issue by rvpatel** [magento/magento2#1040]
On Adminpanel i have add Category page custom design tab on date validation required.

I have add Active From Date 4th Feb 2015 and  Active To Date add 1th january 2015 which older then Active From.

I have suggest to **manage date validation on magento2**.

![Backend Date validation](http://s10.postimg.org/kjvcg2f0p/On_category_page_date_validation.png)

**Comment by kokoc** [comment]
@rvpatel Thank you for reporting the issue
Internal reference - MAGETWO-34194

**Comment by kokoc** [comment]
@rvpatel the fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?

**Comment by kozhemyakin** [comment]
@kokoc @magento-team 
The bug is reproduced on Magento 2.1.6.
