### ISSUE TITLE
Customer group code

### ISSUE THREAD

**Issue by avoelkl** [magento/magento2#1041]
When working with various customer groups, it's not very handy to work with fixed ID's which are returned by `getCustomerGroupId()`.
Working with customer group codes would be more flexible. Currently the *name* of the customer group is set as 'customer_group_code' in the admin.
I would recommend to distinguish between *name* and *code* as the name might be something more user-friendly for backend admins whereas the code can be used for development.

What are your thoughts on this?

**Comment by andreaspenz** [comment]
![](http://cdn.meme.am/instances/500x/59130794.jpg)

**Comment by andreaspenz** [comment]
![](http://cdn.meme.am/instances/500x/59130943.jpg)

**Comment by ilol** [comment]
Hi @avoelkl,
You suggestion worth to study, thanks. I`ve create user story in our product backlog. Please, save the internal tracking number MAGETWO-34160.

@andreaspenz, nice pic :)

**Comment by avoelkl** [comment]
Hi @ilol, thanks for the fast reply!
Looking forward to your findings.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Customer-group-code/idi-p/46629).
