### ISSUE TITLE
How to setup cybersource payment in magento 2.1.7 ee 

### ISSUE THREAD

**Issue by arunkumar2687** [magento/magento2#10413]
Any documents, tutorials etc. I know there is a default module in magento 2 ee for cybersource. but its not helping out

**Comment by YevSent** [comment]
This Github repository only for issues related to the Magento Community Edition. If you have an issue with CyberSource payment method, please, create a ticket in the Partner portal or via the Merchant account.

**Comment by vantucker** [comment]
@arunkumar2687 Were you able resolve the issue? Having the same issue and awaiting Magento EE support for solution.

**Comment by arunkumar2687** [comment]
Hi Van,

I heard from magento 2 ee that their default cybersource module which comes out of box with magento has only authorize option and no authorize and capture as of latest release.

Try this one https://marketplace.magento.com/cybersource-global-payment-management.html

But when i try to get the source of this module through composer i couldnt get the correct source code. Then i contacted their support to get the correct one. Lets see what you are getting. This module has auth and capture payment option in it.

This is the implementation guide.
https://marketplace.magento.com/media/catalog/product/cybersource-global-payment-management-1-0-0-ee/user_guides.pdf

Let me know if you need anything.

**Comment by arunkumar2687** [comment]
if you need source for this module, contact me at arunkumar2687@gmail.com
