### ISSUE TITLE
Can not update a "Schedule Changes"

### ISSUE THREAD

**Issue by hoangnm89** [magento/magento2#10410]
### Preconditions

1. php 5.6
2. mysql 5.6
3. M2 EE 2.1.7
4. mac os 10.11.6
5. Apache/2.4.18

### Steps to reproduce

1. Admin go: Content > Staging > Dashboard
2. Edit a campaign
3. Update value of `End Time` field with future date (like: 00:00 01/01/2018). `Start Time` field is disabled.
4. Save
![image](https://user-images.githubusercontent.com/655821/28884781-7d6b6ece-77dd-11e7-8438-ed986a26a815.png)

### Expected result

1. Schedule will be saved with new date

### Actual result

1. Error: Future Update Start Time cannot be earlier than current time.
![image](https://user-images.githubusercontent.com/655821/28884606-b64976ec-77dc-11e7-8f8e-aac94a6716b1.png)

**Comment by nntoan** [comment]
This is EE issue and should not reported on GitHub, someone from M2 team will close this ticket after my comment.

By the way, I feels your pain. Your issue is just a small part of big picture, the whole Staging module delivered to EE version is completely not working. It also means all **module-*-staging** are not working for any EE versions.

Sigh... @magento-team

**Comment by magento-engcom-team** [comment]
@hoangnm89, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by HuaZilly** [comment]
> This is EE issue and should not reported on GitHub, someone from M2 team will close this ticket after my comment.
> 
> By the way, I feels your pain. Your issue is just a small part of big picture, the whole Staging module delivered to EE version is completely not working. It also means all **module-*-staging** are not working for any EE versions.
> 
> Sigh... @magento-team

Oke @nntoan
