### ISSUE TITLE
OAuth fails with message "Consumer key has expired"

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#10423]
### Preconditions
1. Magento 2.1.7 deployed from zip file then updated using composer
2. Bog standard install

### Steps to reproduce
1. Create integration. It doesnt matter what values you use.
2. Using an OAuth client, attempt to get access token

### Expected result
1. An access token is returned to the oauth client

### Actual result
1. Error "Consumer key has expired" is returned

Investigation shows that database table "oauth_consumer" field "updated_at" has the default value set to 0 and on update set to CURRENT_TIMESTAMP

When a new consumer is added, the "updated_at" field is set to 0. Since this field is used to validate the access token request, it fails stating that the consumer key has expired.

The "updated_at" field is only ever updated whenever the consumer is updated, not when it is added.

Surely the correct behaviour should be that the default value of updated_at should be CURRENT_TIMESTAMP so that on creation, "created_at" and "updated_at" are the same.

**Comment by misha-kotov** [comment]
@gwharton Cannot reproduce your issue. Please provide more detail. What info do you provide when creating the integration? Do you fill out all fields? Which Oauth client are you using and how are you requesting the token?

**Comment by gwharton** [comment]
Add new Integration

Name : Test
Email : test@test.com
Callback : https://www.test.com
Identity : https://www.test.com
API Permissions : ALL

A dump of the database shows the following in auth_consumer

INSERT INTO `oauth_consumer` (`entity_id`, `created_at`, `updated_at`, `name`, `key`, `secret`, `callback_url`, `rejected_callback_url`) VALUES
(2, '2017-08-03 20:00:34', '0000-00-00 00:00:00', 'Integration2', 'slakyhmbmct3aysjstilot83oai1hvqp', 'pa9pbqlap6rm25bfifb4xq08cdxpkw9o', NULL, '');

Notice that "updated_at" is zero. "created_at" is correct.

Because of this the following function always fails as $updatedTimestamp is always 0.

/vendor/magento/module-integration/Model/Oauth/Consumer.php

```
    public function isValidForTokenExchange()
    {
        $expiry = $this->dataHelper->getConsumerExpirationPeriod();
        $currentTimestamp = $this->getDateHelper()->gmtTimestamp();
        $updatedTimestamp = $this->getDateHelper()->gmtTimestamp($this->getUpdatedAt());
        return $expiry > ($currentTimestamp - $updatedTimestamp);
    }

```
I test the OAuth using a php client as follows.

```
<?php
try {
      $oauth = new OAuth("slakyhmbmct3aysjstilot83oai1hvqp","pa9pbqlap6rm25bfifb4xq08cdxpkw9o",OAUTH_SIG_METHOD_HMACSHA1,OAUTH_AUTH_TYPE_AUTHORIZATION);
   
      $oauth->setVersion("1.0");
      $oauth->enableDebug();    
      $oauth->disableSSLChecks();
      
      $req = $oauth->getRequestToken("https://myserver.com/oauth/token/request");   
      
      if(!empty($req)) 
      {
          print_r($req);
      } 
      else 
      {
          print "Failed fetching request token, response was: " . $oauth->getLastResponse();
      }   
} 
catch(OAuthException $E) 
{
    echo "Response: ". $E->lastResponse . "\n";
}      
?> 
```

which gives the output

C:\Users\Graham Wharton\Documents\oauth>php test.php
Response: oauth_problem=Consumer+key+has+expired

**Comment by misha-kotov** [comment]
Thanks. Did you activate your integration after creating it?

**Comment by gwharton** [comment]
No I didn't. I am trying to diagnose failing activation with a third party service, so my first port of call was to just create an integration and attempt oath. I guess as part of the activation process, the consumer entry could get updated, which would then cause the correct "updated_at" field to be entered in the database.

**Comment by gwharton** [comment]
My bad. You can close this issue. If I attempt to activate my test integration, which fails as https://www.test.com doesn't exist, then I attempt to reget the request token again, it now works and I get a request token back. I can see in the database that "updated_at" has been updated.

**Comment by misha-kotov** [comment]
Glad you figured it out!
