### ISSUE TITLE
Lost catalog rewrite url after page/list-mode/limit changed 

### ISSUE THREAD

**Issue by zbych** [magento/magento2#1042]
Case:
1. I am entering the category "Test", address is http://magento2.dev/test.html
2. I am doing one of following operation:
* changed List mode
* switch page
* sorting products
* change limit of display products

Category "Test" url is: http://magento2.dev/catalog/category/view/id/3/

**Comment by kokoc** [comment]
@zbych Thank you for reporting the issue
Internal reference - MAGETWO-34192

**Comment by snohe** [comment]
@zbych, this issue has been resolved in 0.74.0-beta1.  Thank you again for submitting this issue.  Feel free to reach out to us in case you encounter new issues.
