### ISSUE TITLE
Many requests made for search autocomplete

### ISSUE THREAD

**Issue by dersam** [magento/magento2#10422]
### Preconditions

1. Magento 2.1.7
2. Nginx 1.12

### Steps to reproduce
1. On a category page, with the browser developer console open to the Network panel.
2. Enter a search term

### Expected result

1. No requests should be made until typing is complete or a short pause has occurred.

### Actual result

A request is made for nearly every entered character. These requests are "cancelled" but the web server continues to process them. These additional requests slow down the response time of the final autocomplete.

The slowdown is illustrated by the difference when a search term is pasted in. Only one request will be made, and the response will be noticeably faster.

Entry to this field should be debounced, so that the request isn't sent until a specified time has elapsed since the last character was entered. This would prevent the glut of requests being sent to the server.

![image](https://user-images.githubusercontent.com/475851/28924657-7b8a1828-7830-11e7-80b5-3b740ebb057a.png)

**Comment by dersam** [comment]
This was originally reported in https://github.com/Smile-SA/elasticsuite/issues/433, but was found to be behavior provided by Magento 2.

**Comment by magento-engcom-team** [comment]
@dersam Thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
