### ISSUE TITLE
`We can't save the invoice right now` when trying to create invoice of an order

### ISSUE THREAD

**Issue by skashish** [magento/magento2#10427]
### Preconditions

1. operating system - Debian 8.9
2. php 7.0 Mysql 5.6
3. Magento 2.1.1 CE
### Steps to reproduce

1. Place an order.
2. Go to Admin -> Sales -> Order
3. Select that order -> Click Invoice -> Submit Invoice

### Expected result

Invoice is generated.

### Actual result

`We can't save the invoice right now.`

**Things I tried to solve the issue:**

As mentioned [#5324](https://github.com/magento/magento2/issues/5324) I tried to add the column `base_grand_total ` into the `table sales_invoice_grid`, but it was already present. I even added a value into it from database and it become visible on Admin Panel.
    
I looked into var/logs/* for some error logs, but didn't find anything related whatsoever.

**Comment by YevSent** [comment]
Hi, @skashish, please, provide details about used payment method.

**Comment by skashish** [comment]
@joni-jones 
Thanks for quick reply.

There is no payment method. 
After adding product to cart, I proceed for checkout and get my order ID.
I can see the corresponding order ID in Admin Panel.

**Comment by YevSent** [comment]
How did you place the order without any payment method?

**Comment by skashish** [comment]
@joni-jones 
Sorry for last comment.

In my payment methods, Check/Money order is enabled.
http://i.imgur.com/BdLDcxd.png

**Comment by YevSent** [comment]
I've checked on Magento 2.1.7 CE with different payment methods, all works as expected, the invoices have been created successfully.

**Comment by skashish** [comment]
@joni-jones 

I'm on Magento 2.1.1 CE

**Comment by YevSent** [comment]
Please, upgrade your instance to the latest version and check again.

**Comment by skashish** [comment]
@joni-jones 

is there any other way.
Mine is a very complex website.

**Comment by YevSent** [comment]
I do not see any other way to get all fixes beginning with 2.1.1 release without updating your instance to the latest version. From version to version we fix different issues and release patch versions instead only minor releases. This approach provides more easy updates for the merchants.

**Comment by magento-engcom-team** [comment]
@skashish, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by Puru2016** [comment]
I also getting this error in Magento ver. 2.2.6, please let me know any fix to solve this issue.
