### ISSUE TITLE
Unable to show Special Price with Magento2

### ISSUE THREAD

**Issue by magentocj** [magento/magento2#10428]
Hey Guys 

I have created the shell script to remove all products images after Run script successfully we got issue with special price when I try to edit and add special price for products  then we are unable to show the special price at front end side 

Our Magento2 version is: 2.1.7 

Our code is: 

$_products = $this->_productCollectionFactory->create()->addAttributeToFilter('type_id', \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE);

        $this->logger->info('Total Products count: ' . count($_products));

        foreach ($_products as $_product)
        {
            try
            {

               $product = $this->_getProductById($_product->getId());
              // $product = $this->_getProductById(10572);

                $images = $product->getMediaGalleryEntries();
                if(count($images))
                {
                    foreach ($images as $key => $value)
                    {
                        unset($images[$key]);
                    }

                    $product->setMediaGalleryEntries($images);
                    $product->setUrlKey(FALSE);
                    $this->productRepository->save($product);
                }
            }
            catch (\Exception $e)
            {
                $output->writeln('<info>Error during deleting product Image: ' . $e->getMessage() . '</info>');
                // we must have an exit code higher than zero to indicate something was wrong
                return \Magento\Framework\Console\Cli::RETURN_FAILURE;
            }
            $count++;
        }

**Comment by magento-engcom-team** [comment]
@magentocj please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.
