### ISSUE TITLE
getDestCity returns null for saved selected address on checkout page

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10437]
I tried to checkout using magento DHL shipping with saved address but always getting error -
**'The destination country HK location postal code  or City  is invalid. Please check the destination country location details.'** for **'Hong Kong SAR China'** country

### Preconditions

1. Magento ver. 2.1.5, 2.1.6, 2.1.7 with sample data
2. PHP Version 7.0.8

### Steps to reproduce

1. Login to magento admin panel and enable magento DHL shipping (set debug field as yes).
2. Set Origin shipping address as shown in the screenshot 
![screenshot_56](https://user-images.githubusercontent.com/14589296/28970116-f9e105b4-7944-11e7-97ab-8d126b2a10a5.png)

3. Login to Customer Account
4. Saved default shipping and billing address as 
   street - 4 Moray Rd
   city - Kowloon
   country - Hong Kong SAR China
but did not set any State/Province and Zip/Postal Code as not required.
5. Visited Product "Joust Duffle Bag"
6. Go to checkout page
7. Selected saved shipping address
8. No shipping results was there for DHL Shipping
9. Checked console log 
![screenshot_53](https://user-images.githubusercontent.com/14589296/28969867-ea1d5e62-7943-11e7-93b7-922755e04b87.png)
10. Checked debug.log for more details

### Expected result
![screenshot_54](https://user-images.githubusercontent.com/14589296/28969770-9b3be188-7943-11e7-9c55-1d4a73f35c3c.png)
debug.log - 
[debug.log.txt](https://github.com/magento/magento2/files/1200463/debug.log.txt)

### Actual result
![screenshot_55](https://user-images.githubusercontent.com/14589296/28969782-a69606b2-7943-11e7-98b1-1c3f4d2fb7b1.png)
debug.log - 
[debug.log.txt](https://github.com/magento/magento2/files/1200458/debug.log.txt)

Sample data is not required, but product in cart must have Weight > 0

Solution -
There should be get and set method for city in estimate address class, for this will need to update classes -
1. Magento\Quote\Api\Data\EstimateAddressInterface

`   

    namespace Magento\Quote\Api\Data;

    /**
    * Interface EstimateAddressInterface
    * @api
    */
    interface EstimateAddressInterface extends \Magento\Framework\Api\CustomAttributesDataInterface
    {
        /**#@+
        * Constants defined for keys of array, makes typos less likely
        */
        const KEY_COUNTRY_ID = 'country_id';

        const KEY_REGION_ID = 'region_id';

        const KEY_REGION = 'region';

        const KEY_POSTCODE = 'postcode';

        const KEY_CITY = 'city';

        /**#@-*/

        /**
        * Get region name
        *
        * @return string
        */
        public function getRegion();

        /**
        * Set region name
        *
        * @param string $region
        * @return $this
        */
        public function setRegion($region);

        /**
        * Get region id
        *
        * @return int
        */
        public function getRegionId();

        /**
        * Set region id
        *
        * @param int $regionId
        * @return $this
        */
        public function setRegionId($regionId);

        /**
        * Get country id
        *
        * @return string
        */
        public function getCountryId();

        /**
        * Set country id
        *
        * @param string $countryId
        * @return $this
        */
        public function setCountryId($countryId);

        /**
        * Get postcode
        *
        * @return string
        */
        public function getPostcode();

        /**
        * Set postcode
        *
        * @param string $postcode
        * @return $this
        */
        public function setPostcode($postcode);

        /**
        * Get city
        *
        * @return string
        */
        public function getCity();

        /**
        * Set city
        *
        * @param string $city
        * @return $this
        */
        public function setCity($city);

        /**
        * Retrieve existing extension attributes object or create a new one.
        *
        * @return \Magento\Quote\Api\Data\EstimateAddressExtensionInterface|null
        */
        public function getExtensionAttributes();

        /**
        * Set an extension attributes object.
        *
        * @param \Magento\Quote\Api\Data\EstimateAddressExtensionInterface $extensionAttributes
        * @return $this
        */
        public function setExtensionAttributes(
            \Magento\Quote\Api\Data\EstimateAddressExtensionInterface $extensionAttributes
        );
    }
`
2. Magento\Quote\Model\EstimateAddress

`   

    namespace Magento\Quote\Model;

    use Magento\Framework\Model\AbstractExtensibleModel;
    use Magento\Quote\Api\Data\EstimateAddressInterface;

    class EstimateAddress extends AbstractExtensibleModel implements EstimateAddressInterface
    {
        /**
        * Get region name
        *
        * @return string
        */
        public function getRegion()
        {
            return $this->getData(self::KEY_REGION);
        }

        /**
        * Set region name
        *
        * @param string $region
        * @return $this
        */
        public function setRegion($region)
        {
            return $this->setData(self::KEY_REGION, $region);
        }

        /**
        * Get region id
        *
        * @return int
        */
        public function getRegionId()
        {
            return $this->getData(self::KEY_REGION_ID);
        }

        /**
        * Set region id
        *
        * @param int $regionId
        * @return $this
        */
        public function setRegionId($regionId)
        {
            return $this->setData(self::KEY_REGION_ID, $regionId);
        }

        /**
        * Get country id
        *
        * @return string
        */
        public function getCountryId()
        {
            return $this->getData(self::KEY_COUNTRY_ID);
        }

        /**
        * Set country id
        *
        * @param string $countryId
        * @return $this
        */
        public function setCountryId($countryId)
        {
            return $this->setData(self::KEY_COUNTRY_ID, $countryId);
        }

        /**
        * Get postcode
        *
        * @return string
        */
        public function getPostcode()
        {
            return $this->getData(self::KEY_POSTCODE);
        }

        /**
        * Set postcode
        *
        * @param string $postcode
        * @return $this
        */
        public function setPostcode($postcode)
        {
            return $this->setData(self::KEY_POSTCODE, $postcode);
        }

        /**
        * Get postcode
        *
        * @return string
        */
        public function getCity()
        {
            return $this->getData(self::KEY_POSTCODE);
        }

        /**
        * Set city
        *
        * @param string $city
        * @return $this
        */
        public function setCity($city)
        {
            return $this->setData(self::KEY_CITY, $city);
        }

        /**
        * Retrieve existing extension attributes object or create a new one.
        *
        * @return \Magento\Quote\Api\Data\EstimateAddressExtensionInterface|null
        */
        public function getExtensionAttributes()
        {
            return $this->_getExtensionAttributes();
        }

        /**
        * Set an extension attributes object.
        *
        * @param \Magento\Quote\Api\Data\EstimateAddressExtensionInterface $extensionAttributes
        * @return $this
        */
        public function setExtensionAttributes(
            \Magento\Quote\Api\Data\EstimateAddressExtensionInterface $extensionAttributes
        ) {
            $this->_setExtensionAttributes($extensionAttributes);
        }
    }
`
3. Magento\Quote\Model\ShippingMethodManagement

`   

        namespace Magento\Quote\Model;

    use Magento\Framework\Exception\CouldNotSaveException;
    use Magento\Framework\Exception\InputException;
    use Magento\Framework\Exception\NoSuchEntityException;
    use Magento\Framework\Exception\StateException;
    use Magento\Quote\Api\Data\AddressInterface;
    use Magento\Quote\Api\Data\EstimateAddressInterface;
    use Magento\Quote\Api\ShipmentEstimationInterface;
    use Magento\Quote\Model\Quote;

    /**
    * Shipping method read service.
    * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
    */
    class ShippingMethodManagement implements
        \Magento\Quote\Api\ShippingMethodManagementInterface,
        \Magento\Quote\Model\ShippingMethodManagementInterface,
        ShipmentEstimationInterface
    {
        /**
        * Quote repository.
        *
        * @var \Magento\Quote\Api\CartRepositoryInterface
        */
        protected $quoteRepository;

        /**
        * Shipping method converter
        *
        * @var \Magento\Quote\Model\Cart\ShippingMethodConverter
        */
        protected $converter;

        /**
        * Customer Address repository
        *
        * @var \Magento\Customer\Api\AddressRepositoryInterface
        */
        protected $addressRepository;

        /**
        * @var Quote\TotalsCollector
        */
        protected $totalsCollector;

        /**
        * Constructs a shipping method read service object.
        *
        * @param \Magento\Quote\Api\CartRepositoryInterface $quoteRepository
        * @param Cart\ShippingMethodConverter $converter
        * @param \Magento\Customer\Api\AddressRepositoryInterface $addressRepository
        * @param Quote\TotalsCollector $totalsCollector
        */
        public function __construct(
            \Magento\Quote\Api\CartRepositoryInterface $quoteRepository,
            Cart\ShippingMethodConverter $converter,
            \Magento\Customer\Api\AddressRepositoryInterface $addressRepository,
            \Magento\Quote\Model\Quote\TotalsCollector $totalsCollector
        ) {
            $this->quoteRepository = $quoteRepository;
            $this->converter = $converter;
            $this->addressRepository = $addressRepository;
            $this->totalsCollector = $totalsCollector;
        }

        /**
        * {@inheritDoc}
        */
        public function get($cartId)
        {
            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $this->quoteRepository->getActive($cartId);

            /** @var \Magento\Quote\Model\Quote\Address $shippingAddress */
            $shippingAddress = $quote->getShippingAddress();
            if (!$shippingAddress->getCountryId()) {
                throw new StateException(__('Shipping address not set.'));
            }

            $shippingMethod = $shippingAddress->getShippingMethod();
            if (!$shippingMethod) {
                return null;
            }

            $shippingAddress->collectShippingRates();
            /** @var \Magento\Quote\Model\Quote\Address\Rate $shippingRate */
            $shippingRate = $shippingAddress->getShippingRateByCode($shippingMethod);
            if (!$shippingRate) {
                return null;
            }
            return $this->converter->modelToDataObject($shippingRate, $quote->getQuoteCurrencyCode());
        }

        /**
        * {@inheritDoc}
        */
        public function getList($cartId)
        {
            $output = [];

            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $this->quoteRepository->getActive($cartId);

            // no methods applicable for empty carts or carts with virtual products
            if ($quote->isVirtual() || 0 == $quote->getItemsCount()) {
                return [];
            }

            $shippingAddress = $quote->getShippingAddress();
            if (!$shippingAddress->getCountryId()) {
                throw new StateException(__('Shipping address not set.'));
            }
            $shippingAddress->collectShippingRates();
            $shippingRates = $shippingAddress->getGroupedAllShippingRates();
            foreach ($shippingRates as $carrierRates) {
                foreach ($carrierRates as $rate) {
                    $output[] = $this->converter->modelToDataObject($rate, $quote->getQuoteCurrencyCode());
                }
            }
            return $output;
        }

        /**
        * {@inheritDoc}
        */
        public function set($cartId, $carrierCode, $methodCode)
        {
            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $this->quoteRepository->getActive($cartId);
            try {
                $this->apply($cartId, $carrierCode, $methodCode);
            } catch (\Exception $e) {
                throw $e;
            }

            try {
                $this->quoteRepository->save($quote->collectTotals());
            } catch (\Exception $e) {
                throw new CouldNotSaveException(__('Cannot set shipping method. %1', $e->getMessage()));
            }
            return true;
        }

        /**
        * @param int $cartId The shopping cart ID.
        * @param string $carrierCode The carrier code.
        * @param string $methodCode The shipping method code.
        * @return void
        * @throws InputException The shipping method is not valid for an empty cart.
        * @throws CouldNotSaveException The shipping method could not be saved.
        * @throws NoSuchEntityException Cart contains only virtual products. Shipping method is not applicable.
        * @throws StateException The billing or shipping address is not set.
        */
        public function apply($cartId, $carrierCode, $methodCode)
        {
            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $this->quoteRepository->getActive($cartId);
            if (0 == $quote->getItemsCount()) {
                throw new InputException(__('Shipping method is not applicable for empty cart'));
            }
            if ($quote->isVirtual()) {
                throw new NoSuchEntityException(
                    __('Cart contains virtual product(s) only. Shipping method is not applicable.')
                );
            }
            $shippingAddress = $quote->getShippingAddress();
            if (!$shippingAddress->getCountryId()) {
                throw new StateException(__('Shipping address is not set'));
            }
            $shippingAddress->setShippingMethod($carrierCode . '_' . $methodCode);
        }

        /**
        * {@inheritDoc}
        */
        public function estimateByAddress($cartId, \Magento\Quote\Api\Data\EstimateAddressInterface $address)
        {
            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $this->quoteRepository->getActive($cartId);

            // no methods applicable for empty carts or carts with virtual products
            if ($quote->isVirtual() || 0 == $quote->getItemsCount()) {
                return [];
            }

            return $this->getEstimatedRates(
                $quote,
                $address->getCountryId(),
                $address->getPostcode(),
                $address->getRegionId(),
                $address->getRegion(),
                $address->getCity()
            );
        }

        /**
        * @inheritdoc
        */
        public function estimateByExtendedAddress($cartId, AddressInterface $address)
        {
            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $this->quoteRepository->getActive($cartId);

            // no methods applicable for empty carts or carts with virtual products
            if ($quote->isVirtual() || 0 == $quote->getItemsCount()) {
                return [];
            }
            return $this->getShippingMethods($quote, $address->getData());
        }

        /**
        * {@inheritDoc}
        */
        public function estimateByAddressId($cartId, $addressId)
        {
            /** @var \Magento\Quote\Model\Quote $quote */
            $quote = $this->quoteRepository->getActive($cartId);

            // no methods applicable for empty carts or carts with virtual products
            if ($quote->isVirtual() || 0 == $quote->getItemsCount()) {
                return [];
            }
            $address = $this->addressRepository->getById($addressId);

            return $this->getEstimatedRates(
                $quote,
                $address->getCountryId(),
                $address->getPostcode(),
                $address->getRegionId(),
                $address->getRegion(),
                $address->getCity()
            );
        }

        /**
        * Get estimated rates
        *
        * @param Quote $quote
        * @param int $country
        * @param string $postcode
        * @param int $regionId
        * @param string $region
        * @return \Magento\Quote\Api\Data\ShippingMethodInterface[] An array of shipping methods.
        */
        protected function getEstimatedRates(\Magento\Quote\Model\Quote $quote, $country, $postcode, $regionId, $region, $city)
        {
            $data = [
                EstimateAddressInterface::KEY_COUNTRY_ID => $country,
                EstimateAddressInterface::KEY_POSTCODE => $postcode,
                EstimateAddressInterface::KEY_REGION_ID => $regionId,
                EstimateAddressInterface::KEY_REGION => $region,
                EstimateAddressInterface::KEY_CITY => $city
            ];
            return $this->getShippingMethods($quote, $data);
        }

        /**
        * Get list of available shipping methods
        * @param \Magento\Quote\Model\Quote $quote
        * @param array $addressData
        * @return \Magento\Quote\Api\Data\ShippingMethodInterface[]
        */
        private function getShippingMethods(Quote $quote, array $addressData)
        {
            $output = [];
            $shippingAddress = $quote->getShippingAddress();
            $shippingAddress->addData($addressData);
            $shippingAddress->setCollectShippingRates(true);

            $this->totalsCollector->collectAddressTotals($quote, $shippingAddress);
            $shippingRates = $shippingAddress->getGroupedAllShippingRates();
            foreach ($shippingRates as $carrierRates) {
                foreach ($carrierRates as $rate) {
                    $output[] = $this->converter->modelToDataObject($rate, $quote->getQuoteCurrencyCode());
                }
            }
            return $output;
        }
    }
`

**Comment by ghost** [comment]
Is there any update regarding this issue?

**Comment by magento-engcom-team** [comment]
We update description:

> Sample data is not required, but product in cart must have Weight > 0

**Comment by magento-engcom-team** [comment]
@poojawebkul, thank you for your report.
We've created internal ticket(s) MAGETWO-77713 to track progress on the issue.

**Comment by YevSent** [comment]
Closed as the duplicate to https://github.com/magento/magento2/issues/3789.
