### ISSUE TITLE
B2B sharedCatalog price issue in category page (potential cache issue)

### ISSUE THREAD

**Issue by aunik** [magento/magento2#10439]
After shared catalog is created with x% discount and assigned to a company, which ever company customer / public(Gust customer) view the category page the price get cached. For product page it is behaving OK.

### Preconditions
Magento 2.2 RC with B2B with sample data
SharedCatalog is created with X% discount
assign the SharedCatalog to a company

### Steps to reproduce
1.  Create a sheredCatalog with 50% discount and assign to a company
i.e: all products under     Men >Tops category 
2. Clear cache and reindex
3. Login Fontend as the company buyer
4. 1st view the category page which has the 50% discount. you will see the discounted price in category page
5. logout or open a new browser with privet mode. (You are as guest mode)
6. Visit the same category page (i.e: Men >Tops).

### Expected result
1. Should show price without discount for guest/public customer
### Actual result
1. showing discounted price

::: Test step 02:
1. clear cache and reindex
2. visit the page (i.e: Men >Tops) as guest. Showing original full price
3. login as the company buyer. visit the category page (i.e: Men >Tops)

### Expected result
1. Should show price with discount for company buyer
### Actual result
1. showing full price

**Comment by orlangur** [comment]
Are you sure B2B Edition issues are supposed to be reported here? For example, Enterprise Edition issues not...

**Comment by aunik** [comment]
Where to report for M2.2 EE B2B ?

**Comment by misha-kotov** [comment]
Yes, we've asked for all 2.2-RC issues to be reported here, including EE and B2B. A bit of deviation from what we normally do, but this helps us organize the issues a little better. I'll ask someone to take a look. 
cc: @mbrinton01

**Comment by mbrinton01** [comment]
Tracking as MAGETWO-71444

**Comment by magento-engcom-team** [comment]
@aunik thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
