### ISSUE TITLE
Customer group CUST_GROUP_ALL not selected in adminhtml after attribute save

### ISSUE THREAD

**Issue by mashb1t** [magento/magento2#10436]
### Preconditions
1. Magento 2.1.7  EE
2. PHP 7.0.20 

### Steps to reproduce
1. Call method` \Magento\Customer\Model\Customer\Source\Group::toOptionArray`

### Expected result
1. All `$customerGroups['value']` should be of type string

### Actual result
1. First customer group value (`\Magento\Customer\Api\Data\GroupInterface::CUST_GROUP_ALL`) is integer

### Solution
1. Cast `GroupInterface::CUST_GROUP_ALL` to string 

https://github.com/magento/magento2/blob/354fc11a1a2011f6ff4ce9a352ef59f22953b88f/app/code/Magento/Customer/Model/Customer/Source/Group.php#L59

When using the result of `\Magento\Customer\Model\Customer\Source\Group::toOptionArray` as options in an (multiselect) attribute source model, the respective customer group `CUST_GROUP_ALL` is not getting selected in the Magento Admin-Panel despite the value of the group being set.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71432
