### ISSUE TITLE
Can't do reindex

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1044]
There is not any action to do reindex from backend

![m1294](https://cloud.githubusercontent.com/assets/813985/6209962/86299f0a-b5d3-11e4-8223-ae291ebebf01.png)

**Comment by vpelipenko** [comment]
This behavior is as expected by design. Indexing has become a background operation with automatic consideration for partial or full re-indexing by cron.  

The same issue https://github.com/magento/magento2/issues/824.
