### ISSUE TITLE
Changed Use Secure URLs in Admin and store to yes and the UI has lost its CSS.

### ISSUE THREAD

**Issue by yousufbadar** [magento/magento2#10448]
through the admin moduled Changed Use Secure URLs in Admin and store to yes and the UI has lost its CSS. the display has corrupted and cannot change it back.

### Preconditions

everything was ok till i changed the secure thing. please help me reset it to default.

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

![image](https://user-images.githubusercontent.com/7120463/29005461-0f26f33c-7aaa-11e7-8367-0924e9710bb1.png)

**Comment by yousufbadar** [comment]
![image](https://user-images.githubusercontent.com/7120463/29005502-9de12ba6-7aaa-11e7-9bae-b80f034040f2.png)

**Comment by magento-engcom-team** [comment]
@yousufbadar, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
