### ISSUE TITLE
Unable to get Gift Card Amount used in Order JSON via API

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#10449]
### Preconditions
1. Magento 2.1.7 EE

### Steps to reproduce
1. Create a gift card account.
2. Use gift card while creating order
3. Make API call to get the order.

### Expected result
1. Order JSON should contain gift card amount used. So that we can use them in third party console.

### Actual result
1. Order JSON does not contain Gift card amount used.
[order.txt](https://github.com/magento/magento2/files/1204502/order.txt)

Please check and let us know your analysis.

**Comment by orlangur** [comment]
> Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Community Edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
