### ISSUE TITLE
State/Province Not displayed after edit Billing Address on Sales Orders - Backend Admin.

### ISSUE THREAD

**Issue by gerardojofre** [magento/magento2#10441]
### Preconditions

1. PHP 7.0
2. Mysql 5.7
3. Magento 2.1.7 C.E

### Steps to reproduce

1. Go to the backend -> Sales -> Orders -> View any order.
2. Select the section  -> Information -> Address Information 
3. Edit Billing Address, for example the street address.
4. Save Order Address.

**Note**: The same issue happen with the Shipping Address.

### Expected result

1. The State/Province must be displayed on Order View -> Information -> Address Information.

### Actual result

1. The State/Province is empty on Order View -> Information -> Address Information.

Before Save

![beforesave](https://user-images.githubusercontent.com/23035783/28982392-019da41a-792c-11e7-85e8-b3c76e000528.png)

After Save

![aftersave](https://user-images.githubusercontent.com/23035783/28982488-6e99eae2-792c-11e7-9e5c-5e165426c19c.png)

**Comment by southerncomputer** [comment]
see https://github.com/magento/magento2/issues/9439

**Comment by magento-engcom-team** [comment]
@gerardojofre, thank you for your report.
We've created internal ticket(s) MAGETWO-75479 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80916

**Comment by okorshenko** [comment]
The issue has been fixed and merged to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81675

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81676
