### ISSUE TITLE
Special character gets stripped from invoice

### ISSUE THREAD

**Issue by squishz** [magento/magento2#10452]
### Preconditions
1. Magento 2.1.6

### Steps to reproduce
1. Create a customer with the following name: Josef Průša
2. Order something of website
3. Download invoice.

### Expected result
1.  The correct, full name should show up on the invoice

### Actual result
1. Special character is being stripped from the name
![image](https://user-images.githubusercontent.com/17438260/29030246-5239941c-7b82-11e7-9f5e-32f4075b9b04.png)

**Comment by magento-engcom-team** [comment]
@squishz, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
