### ISSUE TITLE
404 Error when customer signs up - v2.1.7

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#10451]
## Preconditions

Version 2.1.7
PHP version 5.6

## Steps to reproduce

Set Config->Customer->Customer Configuration: Require Emails Confirmation = Yes
Create a new Account

## Expected result

1. Account should be created
2. confirmation request email sent
3. customer directed to login page

## Actual result

Account is created but Customer is redirected to a 404 Page

**Comment by magento-engcom-team** [comment]
@msawyers, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
