### ISSUE TITLE
Enable PayPal Credit option not available for United Kingdom

### ISSUE THREAD

**Issue by DigitalStartupUK** [magento/magento2#10450]
### Preconditions
1. Magento 2.1.7

### Steps to reproduce

1. **Stores** > **Config** > **Sales** > **Payment Methods**
2. Set **Merchant Country** to **United Kingdom**
3. Select **PayPal Express Checkout**

### Expected result

1. **Enable PayPal Credit** [Yes/No] option should appear after **Enable In-Context Checkout Experience**

### Actual result

1. **Enable PayPal Credit** [Yes/No] option does **not** appear at all

### Notes
I presume this was originally by design, as PayPal Credit in the United Kingdom was only introduced last year (April 2016 *I believe*). I'm not sure if setting **Merchant Country** to **United States** in **Payment Settings** is a viable fix until it's patched, as I don't know whether this setting only affects the configuration options or runs deeper. However, setting this option does make the **Enable PayPal Credit** appear.

**Comment by magento-engcom-team** [comment]
@DigitalStartupUK, thank you for your report.
We've created internal ticket(s) MAGETWO-80637 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @DigitalStartupUK

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@DigitalStartupUK, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by DigitalStartupUK** [comment]
wow... I guess UK stores  won't ever be able to offer PayPal Credit

**Comment by diazwatson** [comment]
Same happens in 2.2.3 Enterprise Edition

**Comment by dtfdigital** [comment]
Same in open source 2.3. We have customers requesting this feature now.

**Comment by diazwatson** [comment]
I received this reply today from an Integration Engineer, UK Sales Engineering guy

> It sounds like you’re trying to use the PayPal Express Checkout module to enable PayPal Credit. I believe this module was developed to enable PayPal Credit for the US and because of different regulations, it cannot be used for the UK.

They recommended us to use PayPal Credit through this Braintree module:
http://support.gene.co.uk/support/solutions/articles/35000047010-how-do-i-install-the-magento-2-braintree-module-

**Comment by dtfdigital** [comment]
> I received this reply today from an Integration Engineer, UK Sales Engineering guy
> 
> > It sounds like you’re trying to use the PayPal Express Checkout module to enable PayPal Credit. I believe this module was developed to enable PayPal Credit for the US and because of different regulations, it cannot be used for the UK.
> 
> They recommended us to use PayPal Credit through this Braintree module:
> http://support.gene.co.uk/support/solutions/articles/35000047010-how-do-i-install-the-magento-2-braintree-module-

I'm not sure this is an adequate response/solution to the problem, PayPal Express checkout is available out of the box in Magento2, Paypal Credit works in the US for this, but not in the UK. Surely there is a business case to make the standard functionality work correctly/adhere to UK regulations rather than recommending a third party addon?

**Comment by lexiconnect** [comment]
We also now have a client requiring this on their website.

**Comment by diazwatson** [comment]
@dpdesignthatfits @lexiconnect if it helps, the module PayPal recommended us to install actually replaces the one in the core.

What are their reasons for not having this version of the module already pre installed in Magento and instead tell UK customers to install/upgrade when they request PayPal Credit? Honestly I have no idea.

All I can say is we installed it, it replaced the one in the core and it works.

Hope it helps!

**Comment by lexiconnect** [comment]
@diazwatson thanks for the update.  Was the module PayPal recommended to you one of their own or from a third party?

**Comment by diazwatson** [comment]
As I can see it was developed by a UK agency https://www.gene.co.uk/braintree-payments/
