### ISSUE TITLE
Bad rendering frontend category menu.

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1045]
Incomplete menu appears during downloading page.

![m1295](https://cloud.githubusercontent.com/assets/813985/6210639/30b7fe20-b5da-11e4-882d-eb776247205a.png)
![m1296](https://cloud.githubusercontent.com/assets/813985/6210640/31d7292a-b5da-11e4-8ba3-a83d3cf89b9b.png)

**Comment by villageseo** [comment]
Hi Mackovey! 

Yes, we know about this issue. 
Internal ticket MAGETWO-32309 has been raised.

**Comment by vpelipenko** [comment]
@Mackovey, this issue is already fixed by internal team and will be delivered to public repository with next weekly update.

**Comment by snohe** [comment]
@Mackovey, this fix is now available in 0.74.0-beta1.  Thank again for submitting this issue and for your continued support in Magento!
