### ISSUE TITLE
Product page spinner loading forever (Magento ver. 2.1.3)

### ISSUE THREAD

**Issue by uniquedeveloper17** [magento/magento2#10456]
### Preconditions

I am using Magento ver. 2.1.3

### Steps to reproduce
When I click the add product button the page just loads forever with the spinner icon.

### Expected result

Please suggest me.

Thanks.

### Actual result
Product page spinner loading forever.

ScreenShot : http://prntscr.com/g5pc72

**Comment by magento-engcom-team** [comment]
@uniquedeveloper17, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
