### ISSUE TITLE
Generate fixtures does not generate images

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10455]
### Preconditions

1.  M2 latest clean install no sample data

### Steps to reproduce

1.  Install M2
2. Run generate fixtures with small or other profile per http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-perf-data.html
3. Deploy prod mode + resize images/clear all caches
No product images

### Expected result

1.  Product images should be randomly generated?

### Actual result

1. Products have no images
The documentation makes it seem as if they should be generated but this never occurs nor is it noted anywhere.

**Comment by rganin** [comment]
@sylink yes, images should be generated randomly. Is the `pub/media` directory writable on your instance?

**Comment by ghost** [comment]
Yes, and the generation never yields any errors.

**Comment by magento-engcom-team** [comment]
@sylink, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by erlendeide** [comment]
I had the same issue, twice. No errors while generating. Both these installations had the sample data installed before generating fixtures. I just ran a test now without sample data installed, and the product images were generated like they should - on both installations.
