### ISSUE TITLE
getOrigData() returns empty array on category save

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#10458]
### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. simply debug `afterSave` method on a Category model. `getOrigData()` method, it returns an empty array.

### Expected result

1. Simple category changes (`name`, `is_active`) should not force full reindexing.

### Actual result

1. The problem is related to saving category in the backend. When observer checks data with `dataHasChangedFor` method, it is actually using a NULL variable instead of original data before it was saved / modified. By doing so it is forcing full reindex of URLs each time a category is saved. With large databases it takes over 30 minutes to save a category (100000 products assigned to a category).

**Comment by magento-engcom-team** [comment]
@qsolutions-pl, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
