### ISSUE TITLE
Unable reset form in Edit URL Rewrite 

### ISSUE THREAD

**Issue by thenguyenit** [magento/magento2#10459]
### Steps to reproduce
1. Login to Admin Magento
2. Navigate to Marketing / SEO & Search / URL Rewrites
3. Click Edit Link in Action column
4. Change something in field Description
5. Click button Reset and observe

### Expected result
1. The form will be reset

### Actual result
1. The form unable reset
<img width="1391" alt="reset in edit url rewrite" src="https://user-images.githubusercontent.com/3337137/29065786-621ac31c-7c57-11e7-8f8d-5f239c78a376.png">

**Comment by dmanners** [comment]
@thenguyenit I added a PR that will fix this issue I wonder if there could be more forms with the same problem in the admin.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71407

**Comment by okorshenko** [comment]
@thenguyenit thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version

**Comment by magento-engcom-team** [comment]
Thank you @dmanners  for the fix!
