### ISSUE TITLE
 Minicart qty empty + edit link not working / "Message: product_sku is not defined" 

### ISSUE THREAD

**Issue by rcmcronny** [magento/magento2#10466]
### Preconditions
1.  Using Magento version 2.1.7 PHP 7.0 and MySQL 5.6.36-82.0-log - Percona Server (GPL), Release 82.0 
2. Custom Theme 

### Steps to reproduce
1. Add simple product to cart.
2. Then on top,click cart icon.
3. In Minicart input field for qty is empty. The edit link is not working, the delete link works.
4. empty/flush caches does NOT help with this, issue remains

### Expected result
1. In minicart show quantity .Edit and delete link are working properly.
2. When we click edit link redirect to product detail page for editing product.
3. When we click delete icon product should be removed from cart.

### Actual result
1. In Minicart input field qty empty.Edit link is not working.
2. Browser console show below error

```
Uncaught ReferenceError: Unable to process binding "attr: function (){return {
                           id:'cart-item-'+item_id+'-qty','data-cart-item':item_id,'data-item-qty':qty,'data-cart-item-id':product_sku} }"
Message: product_sku is not defined
;
```

This happens only, when there is a custom theme in use, with the luma theme, this does NOT happen.

There are references to this issue in stackexchange also:
1. https://magento.stackexchange.com/questions/153145/magento-2-minicart-error
2. https://magento.stackexchange.com/questions/126301/magento2-knockout-js3012-uncaught-referenceerror-unable-to-process-binding

**Comment by magento-engcom-team** [comment]
@rcmcronny, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
