### ISSUE TITLE
No API to get websites linked with product.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#10463]
### Preconditions
1.  Magento 2.1.7 CE

### Steps to reproduce
1. Create/Update product using API /all/V1/products POST/PUT data 

Required things:
Need API which we can use to get list of websites linked with products

Any help please

**Comment by ankursachdeva11** [comment]
@veloraven  @magento-team  @SerhiyShkolyarenko @orlangur 
Can anyone please take a look on this query?

Thanks

**Comment by careys7** [comment]
See #8121 and #4806

**Comment by misha-kotov** [comment]
Closing as duplicate - the linked tickets will contain the relevant commits to develop branch.

**Comment by ankursachdeva11** [comment]
@careys7 & @misha-kotov,
this ticket is not related to #8121 and #4806
please read the description again. What is required or what's not.
