### ISSUE TITLE
Two equal files

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1046]
app/code/Magento/Catalog/Model/Category/Attribute/Source/Mode.php
app/code/Magento/Catalog/Model/Resource/Category/Attribute/Source/Mode.php

excess / unnecessary file?
app/code/Magento/Catalog/view/frontend/templates/category/view.phtml

**Comment by kokoc** [comment]
@Mackovey Thank you for reporting the issue
Internal reference - MAGETWO-34193

**Comment by kokoc** [comment]
The fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?

**Comment by kokoc** [comment]
@Mackovey The fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?
