### ISSUE TITLE
Reindexing / product lost

### ISSUE THREAD

**Issue by marionvdw** [magento/magento2#10471]
### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Reindexing datas with php bin/magento indexer:reindex

### Expected result

1. All product should appear on frontend

### Actual result

1.  Products (not all) disappear on frontend
To get products back we append root categories on all products…
Products are back

We don't think that is a solution.

Someone to help us?

**Comment by satishashilwar** [comment]
So far we know following are some indexing issues:
1. Product disappears during the indexing is running specifically catalog search. - possible fixes may be release with Magento 2,2

2. After re-indexing some product get disappeared due to some categories data update. I think following fixes may be work in your case.
https://github.com/magento/magento2/issues/8018

**Comment by magento-engcom-team** [comment]
@marionvdw, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by shansari25** [comment]
Im facing this issue in Magento 2.2.4 - products disappeared after reindex. Pls suggest a solution.

Magento is seriously a very bad tool, i made a big mistake, i have gone through several issues. And now this one and no patch and no solution anywhere.

Pls suggest a solution to solve this issue. The solution given above doesnt fit for Magento 2.2.4, pls suggest a solution for Magento 2.2.4 version. The folder structure doesn't match with 2.2.4 version.

@marionvdw 
@vherasymenko 
@aredridel 
@satishashilwar 
@schizek
@LiamKarlMitchell
@versdivers 
@Silarn @caesarcxiv @pravalitera @dnadle @siment @sjovanig 

I request you all - pls suggest a solution - we are stuck and not able to move this through.
