### ISSUE TITLE
Use splat operator from PHP 5.6 in \Magento\Framework\ObjectManager\Factory\AbstractFactory::createObject

### ISSUE THREAD

**Issue by airbone42** [magento/magento2#1047]
Hi,

I just stumbled over the createObject function which has a massive switch to decide how an object should be created, depending on the amount of arguments.

        switch (count($args)) {
            case 1:
                return new $type($args[0]);
            case 2:
                return new $type($args[0], $args[1]);
            case 3:
                return new $type($args[0], $args[1], $args[2]);
            case 4:
                return new $type($args[0], $args[1], $args[2], $args[3]);
            case 5:
                return new $type($args[0], $args[1], $args[2], $args[3], $args[4]);
            case 6:
                return new $type($args[0], $args[1], $args[2], $args[3], $args[4], $args[5]);
            case 7:
                return new $type($args[0], $args[1], $args[2], $args[3], $args[4], $args[5], $args[6]);
            case 8:
                return new $type($args[0], $args[1], $args[2], $args[3], $args[4], $args[5], $args[6], $args[7]);
            case 9:
                return new $type(
                    $args[0], $args[1], $args[2], $args[3], $args[4], $args[5], $args[6], $args[7], $args[8]
                );
            case 10:
                return new $type(
                    $args[0], $args[1], $args[2], $args[3], $args[4], $args[5], $args[6], $args[7], $args[8], $args[9]
                );
            case 11:
                return new $type(
                    $args[0],
                    $args[1],
                    $args[2],
                    $args[3],
                    $args[4],
                    $args[5],
                    $args[6],
                    $args[7],
                    $args[8],
                    $args[9],
                    $args[10]
                );
            case 12:
                return new $type(
                    $args[0],
                    $args[1],
                    $args[2],
                    $args[3],
                    $args[4],
                    $args[5],
                    $args[6],
                    $args[7],
                    $args[8],
                    $args[9],
                    $args[10],
                    $args[11]
                );
            case 13:
                return new $type(
                    $args[0],
                    $args[1],
                    $args[2],
                    $args[3],
                    $args[4],
                    $args[5],
                    $args[6],
                    $args[7],
                    $args[8],
                    $args[9],
                    $args[10],
                    $args[11],
                    $args[12]
                );
            case 14:
                return new $type(
                    $args[0],
                    $args[1],
                    $args[2],
                    $args[3],
                    $args[4],
                    $args[5],
                    $args[6],
                    $args[7],
                    $args[8],
                    $args[9],
                    $args[10],
                    $args[11],
                    $args[12],
                    $args[13]
                );
            case 15:
                return new $type(
                    $args[0],
                    $args[1],
                    $args[2],
                    $args[3],
                    $args[4],
                    $args[5],
                    $args[6],
                    $args[7],
                    $args[8],
                    $args[9],
                    $args[10],
                    $args[11],
                    $args[12],
                    $args[13],
                    $args[14]
                );
            default:
                $reflection = new \ReflectionClass($type);
                return $reflection->newInstanceArgs($args);
        }

So PHP 5.6 added a new operator, also named the splat operator in other languages to unpack arguments, so whenever you decide to change the min. version to 5.6 this massive switch could be replaced by this simple line:

    return new $type(...$args);

**Comment by orlangur** [comment]
Thanks, this well-known new feature was planned to be tried where applicable if performance boost is significant.

Also, even if PHP 5.6 will not be a minimum supported version we can switch ObjectManager implementations using DI or place such in separate composer package with appropriate PHP requirement.

**Comment by antonkril** [comment]
Interception will also benefit from this feature.

**Comment by aohorodnyk** [comment]
https://gist.github.com/aohorodnyk/c3c1011afa4ddc3d0365

Splat new faster than createObject method ~21%
But createObject faster than reflection only ~6%

In default installation magento2 has 700+ shared objects and 2100+ used createObject method, argument resolving slowly than creating new object, I think that using any method will not has important performance improvement or performance degradation for magento2 project.

**Comment by adragus-inviqa** [comment]
Should this be closed now?

**Comment by aohorodnyk** [comment]
Yes, thanks

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Use-splat-operator-from-PHP-5-6-in/idi-p/45809).
