### ISSUE TITLE
Seo - CMS Pages rank way higher than catalog pages

### ISSUE THREAD

**Issue by johnny-longneck** [magento/magento2#10488]
### Preconditions

1. Magento 2 Shop in Production 

### Steps to reproduce

1. Optimize Product Pages for SEO

### Expected result

1. Optimized Page gets higher ranked

### Actual result

1. First pages to be listed on google are with a big distance cms pages

Long Description:
I have 3 Magento 2 shops running now and first I was glad that our ranking recovered after the new launch.
But I noticed that for all 3 Sites the CMS pages rank much much higher than the actual optimized product pages.

Call me suspicious but there must be something wrong there.

**Comment by orlangur** [comment]
How do you think this issue can be reproduced and fixed? Is there any bug on Magento side making product pages not highly ranked?

If there was some experiment with CMS or product page SEO optimization on your side which would reveal correlation between core implementation and page ranking it would probably allow to improve  current implementation.

By optimizing product pages you mean that they currently show higher score in Google PageSpeed than CMS pages?

**Comment by johnny-longneck** [comment]
I am not speaking about page speed and I am aware this is hard to reproduce. I just can confirm that in 3 live sites cms pages are higher listed on google search results than actual products. 
A cms page about the company with 4 sentences is higher than a product page with the actual key words.

I just thought there must be a ranking factor which is an issue maybe. For example product images which load after the page is loaded do not get crawled correctly.

**Comment by orlangur** [comment]
Things like images loaded after page load is exactly what Google PageSpeed may reveal. Magento default implementation is not about making particular pages higher or lower ranked but just about, more or less, following Google recommendations.

Without knowing what exactly went wrong there is nothing to fix.

**Comment by johnny-longneck** [comment]
Okay I understand that. I just opened the topic so maybe others have an experience or opinion about it and we find a solution.
It is always said that Magento claims "We are not a CMS, we are an eCommerce system" and with that in mind I thought this would be some interesting feedback from actual running sites.

I will go on and analyse cms and product pages in the mean time.

**Comment by pboisvert** [comment]
Google uses dozens if not hundreds of ranking factors--increasingly more that have nothing to do with on-page factors. Magento on the whole performs very well in terms of SEO factors and often is top ranked in terms of platforms for producing SEO friendly pages. You are reporting Google results vs a specific issue. Try to isolate to something that has changed within the Magento code that can be tracked back to Google ranking factors. Is the sitemap not listing some pages? Is the crawl budget crawling the same pages? Has the site navigation changed significantly?
