### ISSUE TITLE
Backorders not possible with bundle products

### ISSUE THREAD

**Issue by sippsolutions** [magento/magento2#10480]
### Preconditions

1. Magento 2.1.7
2. PHP 7.0.16
3. MySQL 5.7.17

### Steps to reproduce

1. Allow backorders via configuration (cataloginventory/item_options/backorders)
2. Create a bundle product
3. Set one of the bundle product's options' quantity to 0

### Expected result

1. The option's single product's detail page shows "in stock"
2. The bundle product's detail page shows "in stock"

### Actual result

1. The option's single product's detail page shows "in stock"
2. The bundle product's detail page shows "out of stock"

**Comment by larsroettig** [comment]
@maghamed please take a look -> thank you

**Comment by misha-kotov** [comment]
Can you take a look at #10061 and see if this is a duplicate issue?

**Comment by sippsolutions** [comment]
@misha-kotov Maybe the bug for both issues is in the same function, but I think they reference different problems.

**Comment by magento-engcom-team** [comment]
@sippsolutions We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. Screenshots or logs would be helpful, too.

**Comment by benvansteenbergen** [comment]
Hi, problem comes up when simple product (child of the bundle) has lower stock then asked for in the bundle option and manage stock is on (on bundled product).

Fix on line 572:
` ? ($this->_stockRegistry->getStockItem($selection->getId())->getBackorders() ? 1 : $selection->getSelectionQty() <= $this->_stockState->getStockQty($selection->getId()))`

In code vendor/magento/module-bundle/Model/Product/Type.php:
```
foreach ($selectionCollection as $selection) {
            /* @var $selection \Magento\Catalog\Model\Product */
            if ($selection->isSalable()) {
                $selectionEnoughQty = $this->_stockRegistry->getStockItem($selection->getId())
                    ->getManageStock()
                    ? $selection->getSelectionQty() <= $this->_stockState->getStockQty($selection->getId())
                    : $selection->isInStock();

                if (!$selection->hasSelectionQty() || $selection->getSelectionCanChangeQty() || $selectionEnoughQty) {
                    $requiredOptionIds[$selection->getOptionId()] = 1;
                    $salableSelectionCount++;
                }
            }
        }
```

**Comment by magento-engcom-team** [comment]
@sippsolutions, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by wildrness** [comment]
I am also having this issue on two magento installs

when constituent part of bundle has stock of zero, bundle shows as OOS even though all constituent parts are not stock managed.
