### ISSUE TITLE
Unable to perform argument replacement due to lack of Interface usage in class constructor of `\Magento\Framework\App\PageCache\Identifier`

### ISSUE THREAD

**Issue by dfelton** [magento/magento2#10481]
### Preconditions

1. Magento EE 2.1.7 (Applies to CE as well)
2. PHP version, MySQL version, etc are irrelevant for this issue

### Steps to reproduce

1. Create & enable a new module, that includes a PHP class that implements `\Magento\Framework\App\RequestInterface`
2. In this module configure `etc/di.xml` and specify a different `$request` argument preference for object type `\Magento\Framework\App\PageCache\Identifier` (the new preference should be the PHP class mentioned above in step 1, which implements the interface).

### Expected result

1. By replacing the argument with an object that implements `\Magento\Framework\App\RequestInterface`, the argument replacement should work. 

### Actual result

1. Since the constructor defines a Class rather than an Interface in it's argument list, a PHP Fatal Error is thrown when the argument is replaced with any object that does not extend `\Magento\Framework\App\Request\Http`

## Related Information

- Slightly Related: #1675 

### Additional Information

An applicable scenario for this is a task I am working on to manipulate the return value of `\Magento\Framework\App\PageCache\Identifier::getValue()` so that HTTP requests with **certain** query parameters results in the same FPC identifying cache key as an HTTP request without. Mainly due to page visits which are originating from ad clicks on other sites, which include analytics related query parameters attached to the URL.

**Comment by magento-engcom-team** [comment]
@dfelton thank you for your bug report.
We've created internal ticket MAGETWO-75508 to track progress on the issue.

**Comment by orlangur** [comment]
Expectation is wrong as it does not correspond to a constructor signature https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/App/PageCache/Identifier.php#L37 Moreover, it cannot be changed due to BC constraints.

It is no blocker for an argument replacement, you have to extend concrete class if you go this way, just replace every method with stub so that no original logic is used.

>  I am working on to manipulate the return value of `\Magento\Framework\App\PageCache\Identifier::getValue()`

Argument replacement is not needed here, just override return value implementing plugin-interceptor.

**Comment by dfelton** [comment]
@orlangur 

> Expectation is wrong as it does not correspond to a constructor signature

This in fact was the whole point of the original reported issue, that the constructor signature you referenced does not specify an Interface, but rather, an exact class. I reported this in order to propose that the constructor signature for `\Magento\Framework\App\PageCache\Identifier` inject `\Magento\Framework\App\RequestInterface`. 

> Moreover, it cannot be changed due to BC constraints.

Could you please elaborate a bit on why? Unless I am missing something I do not see how this impacts backwards compatibility. The constructor signature is currently injecting `\Magento\Framework\App\Request\Http`, which is already an interface of `\Magento\Framework\App\RequestInterface`. So I don't see how this change would not be BC. 

Please don't misinterpret my comments. This isn't a complaint but rather an attempt to gain better understanding. 


> Argument replacement is not needed here, just override return value implementing plugin-interceptor.

Yes I did go with a similar approach. I can't remember off the top of my head but we either extended the class and redefined the method or as you suggested used an after plugin-interceptor. I suggested argument replacement as it has the benefit of 

1. Does not cause redundant logic execution (which an after plugin-interceptor would)
2. Does not require extending the class (which I try to avoid in favor of event observers and plugin-interceptors) 


Regardless, thank you for your time.

**Comment by orlangur** [comment]
> The constructor signature is currently injecting `\Magento\Framework\App\Request\Http`

Existing customizations can rely on this and not just on `RequestInterface`.

> Does not cause redundant logic execution (which an after plugin-interceptor would)

Performance impact is negligible. There is even such example in core: https://github.com/magento/magento2/blob/develop/app/code/Magento/PageCache/Model/App/CacheIdentifierPlugin.php

For this particular customization replacing `$request` via DI preference would be an unneeded complication, this class is properly designed for interception. Another good thing is that it has fair constructor: there are quite many classes injecting `\Magento\Framework\App\RequestInterface` but using a much wider interface.

**Comment by dfelton** [comment]
Thanks again @orlangur
