### ISSUE TITLE
Creating a Product via Rest API without store code should not assign website to it.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#10495]
### Preconditions
1.  Magento 2.1.7 CE

### Steps to reproduce
1.  Create Product using /V1/products API

### Expected result
1. Should not select any website during product creation.

### Actual result
Main Website is getting selected.

Please let us know the way so that we can create product and website should not be selected because we need to make a post API call for linking web sites. If we do not want to select Main Website selected then we can not do that.

**Comment by ankursachdeva11** [comment]
@vherasymenko, Just following up.
Any updates on this issue?

**Comment by magento-engcom-team** [comment]
@ankursachdeva11 Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too. Add commands you use via Rest API and and options you insert in "body" of your call

**Comment by korostii** [comment]
Hi @magento-engcom-team, the issue seems pretty much straightforward, and the description fits your beloved template.
Have you actually tried reproducing it? 
Would you please care to explain what kind of information do you intend to get from screenshots and logs in this case?

**Comment by ankursachdeva11** [comment]
Thanks, @korostii for replying to Magento team.

We are also facing one more issue. If we have linked some websites to any product then there is no API which will provide details what all websites linked to the single product.

@magento-engcom-team, Can you please help with this request?

**Comment by RomanKrut** [comment]
@ankursachdeva11 Hi. Thanks for your report. There is a work ground with it. When you start to create a product, The product is pre selected to Main Website automatically. The same is via Rest API, when you create a product he is assigned to Main Website. 
Following [Swagger documentation](http://devdocs.magento.com/swagger) after creation a product you have to unassign it from website by command `DELETE /V1/products/{sku}/websites/{websiteId}` and also if you want to assign a product to some website use 
`PUT /V1/products/{sku}/websites
body {
  "productWebsiteLink": {
    "sku": "string",
    "website_id": 0
  }
}`

**Comment by magento-engcom-team** [comment]
@ankursachdeva11 thank you for report, but you need to check swagger documentation on Magento devdocs for correct using Web API. If you'd like to update it, please reopen the issue.

**Comment by ankursachdeva11** [comment]
Hi, @krutkoroma79911, @magento-engcom-team 
Have you guys read my previous comment "If we have linked some websites to any product then there is no API which will provide details what all websites linked to the single product.".

I have already know about swagger documentation as I am working on Magneto. If I am unable to find such kind of API that's why I have requested some information here.

@krutkoroma79911 , I know how to link and unlink website to any product. Can you please check with a request that to get a list of the website who all linked with the product. It is not coming in either product list or product info API

**Comment by ankursachdeva11** [comment]
@magento-engcom-team, please use some mind before closing all tickets.

**Comment by ankursachdeva11** [comment]
@magento-engcom-team, please go through requirement again and please open ticket,
