### ISSUE TITLE
Flag - site on service

### ISSUE THREAD

**Issue by chrom** [magento/magento2#1049]
mode when the site is under maintenance and visitors are redirected to a separate page.
Example: Update magento version.

**Comment by vpelipenko** [comment]
@chrom, could you describe the issue with more details? What do you suggest to fix?

**Comment by buskamuza** [comment]
@chrom , if you want to switch the site to maintenance mode, you can use a CLI Maintenance Tool for this:
```
php -f setup/index.php maintenance [--set=1|0] [--addresses=127.0.0.1,...|none]
```

**Comment by chrom** [comment]
@buskamuza Snx.

But that users will see?

**Comment by buskamuza** [comment]
@chrom , the user will see the following:

> **Service Temporarily Unavailable**
>
> The server is temporarily unable to service your request due to maintenance downtime or capacity  problems. Please try again later.

**Comment by chrom** [comment]
@buskamuza  Snx for you work.

**Comment by snohe** [comment]
@chrom, thanks for submitting this issue.  I see that @buskamuza has answered your question.  I'll go ahead and close this, however, if you do have any other questions, feel free to submit a new issue.
