### ISSUE TITLE
trying to login to backend bounces back

### ISSUE THREAD

**Issue by gfxguru** [magento/magento2#105]
latest build as of 10/18/2012 - Trying to login with correct username and password bounces back to "The page your requested was not found,... everytime. I have "www.mydomain.com/index.php/admin/admin/dashboard/index/key/c4f8e034f76ef10384......." in the url. I tried with the new "backend" url and, same thing.

Please do not close this issue until you look at what we are saying!. You closed anothers issue with the same problem and why? https://github.com/magento/magento2/issues/85

**Comment by alihalabyah** [comment]
`PHP 5.6` same issue!

**Comment by ihor-sviziev** [comment]
Which OS? Do you have some messages in var/log, Apache error log?

**Comment by alihalabyah** [comment]
Hello @ihor-sviziev,

I'm using `Ubuntu 14.04 LTS` and tried to clear the cache, disable the cache, clear the broswer cookies, switch the session to DB but nothing worked!

**Comment by kandy** [comment]
Please, try login with Firefox

**Comment by alihalabyah** [comment]
@kandy forgot to mention that I've tried the following too:

- Chrome incognito
- Firefox
- Opera

And the same issue happened!

**Comment by kandy** [comment]
Can you attach headers from "login" request (for example screenshot of developer tools from browser)

**Comment by alihalabyah** [comment]
Following the response header:

```

HTTP/1.1 302 Found
Date: Sun, 29 Mar 2015 08:56:15 GMT
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: admin=m57j1f7948v20vtd7d07djg1b5; expires=Sun, 29-Mar-2015 09:56:17 GMT; Max-Age=3600; path=/index.php/default/admin; domain=magento2.shopgo.io; HttpOnly
Expires: Sat, 29 Mar 2014 08:56:17 GMT
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Pragma: no-cache
Set-Cookie: admin=i3e40r57cmu2vjcgdu69nc2mj4; expires=Sun, 29-Mar-2015 09:56:17 GMT; Max-Age=3600; path=/index.php/default/admin; domain=magento2.shopgo.io; HttpOnly
Set-Cookie: X-Magento-Vary=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Location: http://magento2.shopgo.io/index.php/admin/admin/dashboard/index/key/5dd715ef21b8c87fcba6d6dab64708e7a0be0234ce1caa21ac522af3a2326144/
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

```

**Comment by kandy** [comment]
Thanks
Can you provide your local machine time with timezone (or in GMT)

**Comment by kandy** [comment]
looks like problem in cookies path - for same reason it sets to /index.php/default/admin instead of /index.php/admin

**Comment by alihalabyah** [comment]
Hello @kandy,

My current time is `Sun Mar 29 13:24:16 EEST 2015`

Any suggestions to solve this issue?

**Comment by kandy** [comment]
No, currently :(
Can you provide the result of this query `select * from core_config_data where path like 'web%'`

**Comment by alihalabyah** [comment]
@kandy,

Here you go, I see that your trying to make sure of the cookies configuration, anything wrong?

![screen shot 2015-03-29 at 3 02 14 pm](https://cloud.githubusercontent.com/assets/1836535/6885339/cc8e64dc-d624-11e4-81e7-463a3bd8c732.png)

**Comment by EliasZ** [comment]
Used to encounter this problem and it had to do with the timezone on my machine not being the same as selected during the Magento 2 installation process. When debugging, it was something with cookies being set for expiration in the past which translated to being able to log in and then immediately having an expired session which would result in the login screen.

**Comment by kandy** [comment]
@alihalabyah,  
Looks like issue caused by enabling "Add Store Code to Urls" 
Run query `update core_config_data set value = 0 where path  = 'web/url/use_store'`, clear cache and try religion

**Comment by alihalabyah** [comment]
@kandy,

mmm that fixed it, but it should work even with the store code in the urls enabled, no?

Thank you for your help!
Ali

**Comment by kandy** [comment]
Yes, it's definitely should work with this option
