### ISSUE TITLE
[Fron-end wise discussion] Browser support list and supporting features of modern browsers

### ISSUE THREAD

**Issue by cbmd** [magento/magento2#1050]
Hello everyone, i would like to start discussion about support list of browsers and supporting features (and their adoption on M2 codebase) in front-end prospective for GA release.
Due to major problem of adopting new features is always was IE (historically that occurs like that) we were not been able to adopt in spread basis, it most of the time depends on requirements of clients/agencies, but since Microsoft [announces](http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx) theirs plans to support only latest version of browser in order to be up to date and open for developers community, we can adopt new things for M2 GA release (it is because if will be just 3 month off from MS will drop support of current version in flavour of latest).
So i would like to propose you to adopt following techs (as a basis to be consistent with modern requirements of industry).
List of need features (as per my opinion) looking like this:
1. Modern use of picture management. Like for example creating an model for manipulating images in platform wise use of <picture/> element with scrset attribute in order to be perfectly rendered in all platforms (for raster images) with adoption it for all types of images (to be able to manipulate it with declarative way, for example in theme layouts, can be discussed), with fallback for non-supporting or non-standard support of those (like for example using [this](https://github.com/scottjehl/picturefill) polyfill)
2. Use of vector based techniques (for images that differ from manipulation from backend management) as standard base (with possibility to utilise many ways how to adopt them)
3. Make component based structure, which will not be only for stylesheets but for structure of HTML and JS as well (like BEM, or SMACSS techniques). This will give us possibility to adopt ether micro-formats/RDFa or (more preferred one) Schema.org rich snippets which will definitely increase conversion for end customer, and will give us flexibility to re-use components across platform without worrying of something will be broken, since component will be atomic (with minimum tightness per components as it possible). Additionally this will increase in flexibility to achieve more control over responsiveness of components.
4. Creating of components (composite ones) will give us possibility to make (for example) custom elements like select boxes and input masks (there are many of scenarios) be just plug-and-play`able without worrying about structure of HTML and work of JS
5. Adoption of extended front-end validation by browser (since it is more performant then JS one, but yes, it gives less flexibility that can be extended rather be implemented from scratch via JS)
6. Discuss some way to be technology agnostic (for front-end prospective), to be able for example not to tight with RequireJS or jQuery widgets (i do not argue about that but at least to try to discuss)
7. Front-end caching strategies
etc..

This list can be extended during discussion, but from my stand point we need to adopt those things (or at least some of them), since during of GA release we can be in that spot when technologies that will be used in M2 can be already obsolete in terms of modern requirements of web apps.
I do raised this issue due to want to know, is effort is required or not, since there is more than just effort need from community and M2 core team to achieve that, due to many changes needs to be done in codebase to achieve that.

What do you think about that M2 community?

**Comment by cbmd** [comment]
Additionally this list can be extended by list of server-side solutions like containers, instances manipulation, deployment strategies (which is not an agnostic way, but if we would provide possibility to do that from code prospective it will be better for platform i think), etc.
Those can be adopted for front-end side as well, if you like i could describe how and what for :)

**Comment by cbmd** [comment]
Summoning @alankent @vasiliyseleznev @maksek for discussion.

**Comment by cbmd** [comment]
List of some of the issues raised in this prospective:
1. #1022
2. #1034
3. #957

**Comment by cbmd** [comment]
In this topic we could additionally discuss things like rich snippets (as mentioned before), but as well accessibility standards adoption on magento platform...

**Comment by alankent** [comment]
Sorry, I have been doing some traveling with work. Just catching up with email etc.  This has been tagged for product and tech to have a look. (A warning - large requests with lots of items take longer to get through and tend to get pushed down the backlog as they take a significant effort to just review.)  

What would be helpful however is to get other community feedback on the relative importance to this to other work. As always, its not a question of whether its a good idea or not - its normally a question of whether this is more important than other things on the backlog. Feedback from multiple community members helps us make this determination.

I do want to note that just because IE does not officially support a version of a browser does not mean its acceptable for us to not support it. We are driven by usage stats - if enough users still use a web browser then I don't think Merchants want us dropping support for that browser (regardless of whether the browser version is EOL or not)

**Comment by navarr** [comment]
Where appropriate it would be beneficial to Magento to use "graceful degradation." (e.g. my ticket #1022).   I.e. Magento programs for the lowest common denominator and for browsers that support better features better features become activated (e.g. #1022).

Chrome and Firefox have been evergreen for a long time now, and IE will be evergreen soon.  My suggestion for browser compatibility then would be IE10+, Latest Chrome, Latest FF.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
