### ISSUE TITLE
newsletter json display

### ISSUE THREAD

**Issue by gitbiorobert** [magento/magento2#10505]
### Preconditions

1. Magento ver. 2.1.7
2. PHP Version 7.0.21
#. Mysql 5.6.36

### Steps to reproduce

1. click subscribe to newsletter on any page
2. 
3. 

### Expected result

1.  "thanks for joining our mailing list" or normal error message in a modal

### Actual result

1. The page reloads and gives this message. 
"{"status":"OK","msg":"Thank you for your subscription."}"
![screen shot 2017-08-11 at 2 45 52 pm](https://user-images.githubusercontent.com/25350604/29229409-cec572ac-7ea3-11e7-98c1-d65e09e1a542.png)

**Comment by orlangur** [comment]
Do you see any JavaScript errors in browser console?

**Comment by gitbiorobert** [comment]
Resource interpreted as Document but transferred with MIME type application/json: "https://www.foundmi.com/newsletter/subscriber/new/".

**Comment by orlangur** [comment]
https://www.foundmi.com/newsletter/subscriber/ does not work for me.

> Resource interpreted as Document but transferred with MIME type application/json: 

This is just a consequent I believe. The problem looks like some JavaScript click handler didn't work to handle AJAX response.

**Comment by gitbiorobert** [comment]
https://www.foundmi.com/newsletter/subscriber/new/ is the correct url.

**Comment by gitbiorobert** [comment]
Response Headers:

Cache-Control: max-age=0, must-revalidate, no-cache, no-store
Connection: Keep-Alive
Content-Type: application/json
Date: Tue, 15 Aug 2017 15:39:11 GMT
Expires: Mon, 15 Aug 2016 15:39:11 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache
Set-Cookie: form_key=xViqJW9mgcbqvDf4; expires=Tue, 15-Aug-2017 16:39:11 GMT; Max-Age=3600; path=/; domain=www.foundmi.com
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.0.8
X-UA-Compatible: IE=edge
X-XSS-Protection: 1; mode=block

Request Headers:

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Content-Length: 25
Content-Type: application/x-www-form-urlencoded
Cookie: _ga=GA1.2.508263792.1498232942; __ar_v4=REQCDD56JBCQTKC4G642GP%3A20170810%3A4%7CUIOHZLLPSNDBZALL7BMWTS%3A20170810%3A4%7CP6UKJX7ZVJCYRBCH3J2FNC%3A20170810%3A4; mage-messages=; _ceg.s=ouqgt0; _ceg.u=ouqgt0; _hjIncludedInSample=1; mage-translation-storage=%7B%7D; mage-translation-file-version=%7B%7D; _ceir=1; mage-cache-storage=%7B%7D; mage-cache-storage-section-invalidation=%7B%7D; section_data_ids=%7B%22cart%22%3A1502811542%2C%22messages%22%3A1000%7D; form_key=xViqJW9mgcbqvDf4; _gid=GA1.2.479849420.1502811190; PHPSESSID=8i19cnmsg1oiu6trug8sqpdme3; form_key=xViqJW9mgcbqvDf4; _gat=1; mage-cache-sessid=true
Host: www.foundmi.com
Referer: https://www.foundmi.com/?SID=8i19cnmsg1oiu6trug8sqpdme3
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by orlangur** [comment]
I was asking about console tab. Does it contain some red message, like JavaScript file not loaded or something undefined?

**Comment by gitbiorobert** [comment]
no, there is just a font file 404

**Comment by magento-engcom-team** [comment]
@gitbiorobert, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by gitbiorobert** [comment]
http://www.foundmi.com/
scroll down to the bottom email signup.
input an email address and click subscribe
you will get the error
