### ISSUE TITLE
Please check Store>Configuration>Developer Any Change Content Page is Going to Blank Page.

### ISSUE THREAD

**Issue by geliyoo** [magento/magento2#10515]
Hi have big issue from Magento 2.1 i will explain some think.

1. If i change SEO url setting direcly content page configuration is going not show any think after click toı edit. Please check this issue first. 
2. Js and Css setting if i will click to javascript render setting also Content page setting going i can see black page after click to edit inside to content configuration inside. I dont see noting. 

All developer tools is if edit some think content page show black page after click to edit. We dont see noting for all theme or default theme. Please check step by step. 

Open SEO URL setting No to ye
Open JS Minify or Css Minifiy or any setting from Developer tools than you will go content page after click to configuration than you will click o any edit link you dony see noting.

**Comment by geliyoo** [comment]
Fixed this problem i will close this ticket. Because if you will use PHP7 you have problem with this issue if you use 5.6 you will fixed this issue. PHP 7 with magento 2 not working correcly.

**Comment by vherasymenko** [comment]
@geliyoo Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.
