### ISSUE TITLE
Magento 2.1.8 w/Sample Data is not responsive in categories with text containers

### ISSUE THREAD

**Issue by addison74** [magento/magento2#10510]
### Preconditions

1. Magento 2.1.8 with Sample Data
2. Desktop environment resolution 1920 x 1024 px

### Steps to reproduce

1.  Go visiting [What's New] category. It has content blocks instead of listing products
2. Resize your browser to the smallest width of the window

### Expected result

1. Text containers should be responsive
2. There is no horizontal scroll bar

### Actual result

1. There is a horizontal scroll bar.
2. Text containers are not resizing

Here is a screenshot

![magento_responsive](https://user-images.githubusercontent.com/8360474/29239658-266b1008-7f5c-11e7-933e-6547666e318b.jpg)

**Comment by magento-engcom-team** [comment]
@ADDISON74, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-75311
