### ISSUE TITLE
Upgrade from 2.17 to 2.1.8 - Site Broken, MiBSegmentation fault (core dumped) on recompile

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10517]
### Preconditions

1.  CENTOS 7.3 x86_64 virtuozzo – host cPanel & WHM 64.0 (build 36)
2.  mySQL 5.6, PHP 7.0.22

### Steps to reproduce
1.  Upgrade from Magento 2.1.7 to 2.1.8
2. 
3. 

### Expected result
1.  Upgrade complete

### Actual result

1. All website images broken, attempt to re-compile via php -d memory_limit=-1 bin/magento setup:di:compile
2. Error: Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 44.0 MiBSegmentation fault (core dumped)

**Comment by johnny-longneck** [comment]
I know it's basic but check file permissions. After every composer update I have to reset file permissions.

**Comment by magento-engcom-team** [comment]
@carbide01, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
