### ISSUE TITLE
Grand Total Excl. Tax: Wrong Calculation with discount on price excluding taxes

### ISSUE THREAD

**Issue by storepeinture** [magento/magento2#10513]
### Preconditions
1. Magento Version 2.1.7
2. Theme Smartwave Porto
3. Multistore
4. php 5.6

### Steps to reproduce
1. Install Magento 2.1.7 and add some products
2. Setup Tax Rule (in my case 20%)
3. In Stores > Settings >Configuration > Sales > Tax: Set **Apply Discount On Prices = Excluding Tax**
    _Please note: The numbers are calculated correctly if it is set to = Including Tax_
4. Create a Cart Price Rule: 
    Coupon Code -> discount_10%
    Percent of product price discount -> 10%
5. Create a new product order in backend and add a product
6. Apply the cart price rule by entering the coupon code (in my case "discount_10%")
7. Free Shipping (to make things simple)
8. Look in the bottom right for **Order Totals** and check the numbers

### Expected result
The **Grand Total Excl. Tax** should be: Subtotal (excl. tax) - 10% Discount

### Actual result
The **Grand Total Excl. Tax** IS NOT: Subtotal (excl. tax) - 10% Discount
I was not able to find out what exactly is calculated here ... but it is certainly not the expected result.

Please see Screeshots below:

![grandtotal1](https://user-images.githubusercontent.com/21140651/29240003-50343978-7f5c-11e7-9754-8a3863c1db89.PNG)
![grandtotal2](https://user-images.githubusercontent.com/21140651/29240004-50407760-7f5c-11e7-8d21-b4f30d36c486.PNG)

**Comment by storepeinture** [comment]
I have upgraded to Magento 2.1.8. - and the problem persists.

Now, I also figured out what "strange stuff" is being calculated here. Instead of writing it all down, I decided to post the Excel Calculation, which better displays what miscalculation causes the issue:

![taxes](https://user-images.githubusercontent.com/21140651/29273776-c99f5b8a-8105-11e7-8043-982e5e0d417e.PNG)

Does anybody else have this issue or am I the only one?

A comment from somebody would be highly appreciated!

**Comment by storepeinture** [comment]
vherasymenko, thanks for adding the **bug report label**. Has the issue been acknowledged or do you need any further info?
Thank you for a quick update.

**Comment by magento-engcom-team** [comment]
@storepeinture thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details regarding your environment, or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@storepeinture, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
