### ISSUE TITLE
We need a warming up script with Varnish

### ISSUE THREAD

**Issue by addison74** [magento/magento2#10523]
### Preconditions

1. Magento 2.1.8
2. Debian 8, Apache 2.4, Php 7.0 + OpCache, Percona 5.6, Varnish 4.0

### Steps to reproduce

1. First page load time takes 10 sec. - 22 sec. It is ridiculous comparing with Magento 1 which loads a page in 2 sec. - 4 sec.  In my case it is a dedicated server with 4 cores/8 threads, 16 GB of RAM, SSD, 1 Gbps bandwidth.
2. Once the page is loaded first time, Varnish is doing the job from now on, page loads in 3 ms.

### Expected result

1. We need a warming up script for loading all pages when using Varnish. It will do the hard job.

### Actual result

1. First time page load is taking too much time.

**Comment by orlangur** [comment]
>  Varnish is doing the job from now on, page loads in 3 sec

This has nothing to do with Varnish. Varnish responses within 0.0x seconds.

Did you perform all the [deployment steps](http://devdocs.magento.com/guides/v2.1/config-guide/prod/single-machine-deployment.html#deployment-steps)?

**Comment by hostep** [comment]
@orlangur: it looks like those deployment steps are missing one very crucial step:
`php bin/magento deploy:mode:set production`

This might explain @ADDISON74's problem...

**Comment by orlangur** [comment]
@hostep it is not so crucial here, I believe the problem is just `var/cache`, `var/di` an `var/generation` are not warmed up and existing steps would be enough to see "page loads in 3 sec" on first load.

**Comment by addison74** [comment]
I did a mistake in my initial post, it is 3 milliseconds not 3 seconds. Corrected by now.

@orlangur: before posting I followed all the deployment steps. This dedicated server has Magento 1 and 2 installed with default sample packs. For Magento 1 I am using Varnish with Nexcess Turpentine extension (I am a strong supporter of this extension for long time). Comparing both versions, Magento 1 is loading first time any page with an average of 1.5 seconds. Second time Varnish is doing the job in 3 - 7 ms. In Magento 2 there are pages which load first time in 21 seconds ( Sale -> Jackets) and this is what I call ridiculous. Second time Varnish is doing the job same like in Magento 1. 

I am exploring Magento 2 for the times when I will do the switch with my heart large opened. For the moment I am not convinced Magento 2 can beat Magento 1 in many ways, one of them is speed.

First time page load

![first](https://user-images.githubusercontent.com/8360474/29293438-d5366b34-8153-11e7-9c9f-f2c869598c2c.jpg)

Second time page load

![second](https://user-images.githubusercontent.com/8360474/29293445-d99f1e28-8153-11e7-825b-7fea2da885fa.jpg)

**Comment by orlangur** [comment]
I see, with 3s -> 3ms correction it totally makes sense.

Sounds like a feature request to me rather than a bug report.

Until it is implemented, something like https://magento.stackexchange.com/a/3815 could be used.

>  In Magento 2 there are pages which load first time in 21 seconds

Way too slow according to my experience, may be worth profiling (poor customization? some core bug which appears only in particular circumstances?).

**Comment by addison74** [comment]
Both Magento versions are out of the box. There are no changes in core files. Webserver configuration is the same in both cases. The only difference between versions I had to use two extensions for Magento 1: Nexcess Turpentine and Inchoo PHP7  in order to use Varnish 4.0.5 and PHP 7.0.22. I agree you too slow page loading with a dedicated server.

That post on Stackexchange is following an idea from Nexcess. I will check it, important is not being related to a session particularly.

**Comment by andidhouse** [comment]
@ADDISON74 there are two or more "page cache crawler" extensions out there which will do the job for you. Just google it because i do not like to advertise here.

They are run via cron and warm the pages which are not in the cache.

**Comment by magento-engcom-team** [comment]
Hi @ADDISON74 thank you for investigation. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
