### ISSUE TITLE
Make SKU not mandatory for Configurable Product

### ISSUE THREAD

**Issue by gputignano** [magento/magento2#10526]
Tested on a blank installation of Magento 2.2 RC1.8.

When I create a new configurable product SKU field is mandatory but I think it is mandatory only for simple products.

**Comment by jordanbrauer** [comment]
What is the problem here? This is an intended feature.

**Comment by gputignano** [comment]
There isn't a real problem. I think that it could be not mandatory.

**Comment by jordanbrauer** [comment]
Easy. I don't recommend doing this (SKU is a system attribute), but ¯\\\_(ツ)_/¯

Go to your admin panel, click **Stores** > **Attributes** > **Product** > **SKU** > **Attribute Properties** > **Values Required** > **No** > **Save Attribute**

This will make it so that the SKU will not be a required attribute during your product creation.

**Comment by orlangur** [comment]
> There isn't a real problem. I think that it could be not mandatory.

What is the value in making it not mandatory? Obviously it would require some development efforts.

**Comment by vherasymenko** [comment]
@gputignano Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by misha-kotov** [comment]
Actually sounds like more like a suggestion/feature request than reporting a bug. Please keep in mind that feature requests and improvement suggestions should be filed in our [forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Make-SKU-not-mandatory-for-Configurable-Product/idi-p/73564).
