### ISSUE TITLE
Bug on greek backend when creating custom order

### ISSUE THREAD

**Issue by nikmem** [magento/magento2#10522]
### Preconditions

1.  Magento 2.1.6
2.  PHP Version 3.6.30 - MySQL Version 5.5.55

### Steps to reproduce

1. Greek version on backend does not let me select customer when creating a custom order. When turning backend to English version everything works fine. 

### Expected result

1. Be able to complete a custom order with no issues as English version does. When creating a new order from backend, step 2 is to select an existing customer or create a new one. When you select a new customer, step 3 is to select the store view you want and then you proceed with the order creation.

### Actual result

1. When you select an existing customer on step 2, page reloads and remains on the same page with the existing customers list. If you refresh page manually it goes to next step to select store view. When you select the required store view though, there is not always the next button to proceed nor refresh helps. This is not very helpful when you have a lot of orders to proceed with.

**Comment by orlangur** [comment]
Are you able to reproduce this issue on clean Magento installation with some [predefined locale](https://github.com/magento/magento2/tree/develop/app/i18n/Magento)?

**Comment by nikmem** [comment]
Hello, I tried on clear installation too but could not procedure either.

**Comment by magento-engcom-team** [comment]
@roknav We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
