### ISSUE TITLE
Product custom options incorrectly reused when adding to cart

### ISSUE THREAD

**Issue by scottsb** [magento/magento2#10538]
### Preconditions
Magento 2.1.3

### Steps to reproduce
Add a product to a cart first with a custom option set, and then again with no custom options set.

Sample code:

    // Set these to values for an actual product in the catalog
    const PRODUCT_ID = 12345;
    const PRODUCT_OPTION_ID = 12345;
    const PRODUCT_OPTION_VALUE_ID = 12345;

    // Use object manager for demo purposes only.
    $cartManagement = $objectManager->get('Magento\Quote\Api\CartManagementInterface');
    $cartRepository = $objectManager->get('Magento\Quote\Api\CartRepositoryInterface');
    $productRepository = $objectManager->get('Magento\Catalog\Api\ProductRepositoryInterface');

    $quoteId = $cartManagement->createEmptyCart();
    $quote = $cartRepository->get($quoteId);
    $buyRequest = [
        'product' => PRODUCT_ID,
        'qty' => 1
    ];

    // Add product to quote with an option set.
    $product = $productRepository->getById(PRODUCT_ID);
    $buyRequest['options'] = [PRODUCT_OPTION_ID => PRODUCT_OPTION_VALUE_ID];
    $quote->addProduct($product, new \Magento\Framework\DataObject($buyRequest));

    // Refetch the product (just for completeness) and add to quote without any option set.
    $product = $productRepository->getById(PRODUCT_ID);
    $buyRequest['options'] = [];
    $quote->addProduct($product, new \Magento\Framework\DataObject($buyRequest));

### Expected result
First item in cart should have custom option set, and second item in cart should not.

### Actual result
Both items in cart have the custom option set.

### Preliminary analysis
The issue is that when the product is added to the cart again, the options are still set on the `$product` object. Because no options are provided with the second buy request to replace the options from the first time, the first item's options are retained. There are two junctures where this might be resolved. It may even be advantageous to do both:

1. Make sure that custom options are cleared from any objects that are returned from the product repository. In the example both cart actions happened in sequence, but it's possible that the first could be in unrelated code to the second. The user of the repository should be able to assume that when it gets a product object, it is fresh and ready to use.
2. When adding to cart based on a buy request object, clear any existing custom options from the product object before adding the options from the buy request. This seems to be logical behavior, but I'm not sure if there are any edge cases where this is undesirable. For reference, the logic that would need to be adjusted is in method `_prepareProduct()` of class `\Magento\Catalog\Model\Product\Type\AbstractType`.

**Comment by magento-engcom-team** [comment]
@scottsb Thank you for your input.  If you want get cleared object from repository, you should use forceReload. For instance: $productRepository->getById(PRODUCT_ID, false, null, true);
This issue is solved in Magento 2.1.8 already.

**Comment by scottsb** [comment]
@magento-engcom-team: Can you please clarify what the resolution in Magento 2.1.8 is? Does it still require forcibly reloading the product as you describe? That involves a roundtrip to the database to refetch the product data, which shouldn't be necessary just to add the same product twice with different options.

**Comment by magento-engcom-team** [comment]
@scottsb Yes, you still have to use force reload in order to get "clean" instance of product(caused by Product Repository cache system). The code, you provide, will work perfectly fine on Magento 2.1.8 with help of force reload in Product Repository.

**Comment by scottsb** [comment]
@magento-engcom-team Just to clarify this: it's considered intentional that you have to run a roundtrip to the database just to be able to reuse the same product object you already have? I understand the cause (the repository cache system), but that seems like a design flaw.
