### ISSUE TITLE
Magento upgrade issue 2.1.7 to 2.1.8

### ISSUE THREAD

**Issue by ranesh26** [magento/magento2#10535]
### Preconditions
1. magento 2.1.7 to 2.1.8 php7.0-fpm,mysql 5.7

### Steps to reproduce

1. composer require magento/product-community-edition 2.1.8 --no-update
2. composer update

### Expected result

1. composer update is not working

### Actual result

1. ![ungrade_magento_issue](https://user-images.githubusercontent.com/24241838/29302946-2734cc44-81a6-11e7-95e6-8fe58ab21b77.png)

**Comment by orlangur** [comment]
Try comparing your `composer.json` to https://github.com/magento/magento2/blob/2.1/composer.json, especially the `"minimum-stability": "alpha"` part.

**Comment by delidiscount** [comment]
I upgrade from a clean 2.1.7 with sampledata to 2.1.8 with the system upgrade build in in Magento and now I cannot acces my admin anymore ?

**Comment by korostii** [comment]
@delidiscount,
Please consider creating a separate issue and providing some more details about your situation. 
It's impossible to guess want went wrong based on the little info you've provided in the comment

**Comment by IlnitskiyArtem** [comment]
Hi @ranesh26.
I observed similar behavior with update from 2.1.7 to 2.1.8, but after dropping my database and installing a clean instance of magento cannot reproduce it anymore. Also tried to reproduce it by filling up my store using performance toolkit, but it doesn't helped. Please, provide more information. Maybe there is some store configurations or additional modules that triggers this issue.
