### ISSUE TITLE
Migration from 1.9 to 2.1.7 wysiwyg product description formatting gone

### ISSUE THREAD

**Issue by KojoSlayer** [magento/magento2#10544]
Product descriptions have lost all of the wysiwyg editor formatting (Bullet points,paragraphs, bold etc). The products still have listed stars next to the bullet points e.g:

```
* bullet one
* bullet two
* bullet three
```

### Preconditions

1.  Magento 1.9.1.0 migration to 2.1.7
2.  PHP Version 7 

### Steps to reproduce

1.  Run data migration tool on new 2.1.7 install from site with product description formatting
2.  Check product descriptions after successful migration

### Expected result
1.  All formatting like bold and paragraphs to show on the product descriptions.

### Actual result
1.  Product descriptions show as blocks of text no formatting or bullet points etc apart from * character where bullet points were.

---

Hopefully I haven't just missed something here, no idea whats going on with it.

**Comment by orlangur** [comment]
Problems with data migration should be reported in https://github.com/magento/data-migration-tool repository I believe.

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.
