### ISSUE TITLE
Unable to save multi-select attributes with grouped/configurable products

### ISSUE THREAD

**Issue by apsummers** [magento/magento2#10540]
This issue appears to be similar to #4822, but is more like what @daniel-ifrim describes in the last comment. When updating product attributes on a Grouped Product, attributes using a multi-select field do not get saved correctly, and the values are ignored.

Simply saving the product does not trigger `ArrayBackend::beforeSave` at all. "Save and Duplicate" will trigger `ArrayBackend::beforeSave`, though the data returned by `$object->getData($attributeCode);` only contains the current selection. `$object`, which is passed to `ArrayBackend::beforeSave` _does_ show the correct selections.

Multi-select fields do save correctly on Simple Products, and the other field types (dropdown, text) seem to save correctly on Grouped Products.

### Preconditions

1. Magento 2.1.7
2. PHP 7.0.15
3. MariaDB 10.1

### Steps to reproduce

1. Create a Grouped Product with a multi-select attribute
2. Select one or more new values for that attribute
3. Save

### Expected result

1. The attribute is updated

### Actual result

1. The original attribute value is still there

**Comment by apsummers** [comment]
I've been looking into this more, and I've got some more info to hopefully help narrow this down:

* The issue doesn't exist when the Grouped Product is composed of two Simple Products
* The issue _does_ exist when the Grouped Product contains multiple Configurable Products
* The Configurable Products in the Grouped Product that does exhibit this behavior are using different attribute sets

**Comment by magento-engcom-team** [comment]
@apsummers  Thank you for report. We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by A-1A** [comment]
I Found Solution after R&D On Magento database.
Login In your phpmyadmin
Go to your website database 
Open "eav_attribute" table
Find Your multiselect "attribute_id"
Edit Row
If "backend_model" Column blank then paste this **Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend**
And Also Please check this
https://magento.stackexchange.com/questions/224621/warning-array-filter-expects-parameter-1-to-be-array/230444#230444
