### ISSUE TITLE
  Class Magento\Store\Helper\Cookie does not exist

### ISSUE THREAD

**Issue by madhur99** [magento/magento2#1055]
Class Magento\Store\Helper\Cookie does not exist

Please find the error log below.
I am not able to find where is this class located and how can I resolve the issue

a:4:{i:0;s:48:"Class Magento\Store\Helper\Cookie does not exist";i:1;s:6878:"#0 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\Code\Reader\ClassReader.php(19): ReflectionClass->__construct('Magento\\Store\\H...')
#1 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\ObjectManager\Definition\Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Store\\H...')
#2 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Store\\H...')
#3 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php(69): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\H...')
#4 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(125): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Store\\H...')
#5 C:\wamp\www\magento2-develop\app\design\frontend\UberTheme\craft\Magento_Theme\templates\html\notices.phtml(76): Magento\Framework\View\TemplateEngine\Php->helper('Magento\\Store\\H...')
#6 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('C:\\wamp\\www\\mag...')
#7 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Element\Template.php(252): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Theme\Block\Html\Notices), 'C:/wamp/www/mag...', Array)
#8 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Element\Template.php(272): Magento\Framework\View\Element\Template->fetchView('C:/wamp/www/mag...')
#9 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(637): Magento\Framework\View\Element\Template->_toHtml()
#10 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Layout.php(461): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Layout.php(437): Magento\Framework\View\Layout->_renderBlock('global_notices')
#12 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Layout\Interceptor.php(302): Magento\Framework\View\Layout->renderElement('global_notices', true)
#13 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderElement('global_notices')
#14 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Layout.php(439): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
#15 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Layout\Interceptor.php(302): Magento\Framework\View\Layout->renderElement('after.body.star...', true)
#16 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderElement('after.body.star...')
#17 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Layout.php(439): Magento\Framework\View\Layout->_renderContainer('root')
#18 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Layout\Interceptor.php(302): Magento\Framework\View\Layout->renderElement('root', true)
#19 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Layout.php(857): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#20 [internal function]: Magento\Framework\View\Layout->getOutput()
#21 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Layout\Interceptor.php(101): call_user_func_array(Array, Array)
#22 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Layout\Interceptor.php(590): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#23 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Result\Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#24 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\View\Result\Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http))
#25 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http))
#26 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(48): call_user_func_array(Array, Array)
#27 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\Interception\Chain\Chain.php(65): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#28 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\Interception\Chain\Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#29 C:\wamp\www\magento2-develop\app\code\Magento\PageCache\Model\Controller\Result\VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http))
#30 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http))
#31 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\Interception\Chain\Chain.php(63): call_user_func_array(Array, Array)
#32 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(93): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#33 C:\wamp\www\magento2-develop\app\code\Magento\PageCache\Model\Controller\Result\BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\View\Result\Page\{closure}(Object(Magento\Framework\App\Response\Http))
#34 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http))
#35 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(98): call_user_func_array(Array, Array)
#36 C:\wamp\www\magento2-develop\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(226): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#37 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\App\Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http))
#38 C:\wamp\www\magento2-develop\lib\internal\Magento\Framework\App\Bootstrap.php(245): Magento\Framework\App\Http->launch()
#39 C:\wamp\www\magento2-develop\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#40 {main}";s:3:"url";s:18:"/magento2-develop/";s:11:"script_name";s:27:"/magento2-develop/index.php";}

**Comment by Sanuch** [comment]
This class was moved to namespace [`Magento\Cookie`](https://github.com/magento/magento2/blob/develop/dev/tests/static/testsuite/Magento/Test/Legacy/_files/obsolete_classes.php#L2216)

You should replace it on correct namespace

**Comment by joanhe** [comment]
@madhur99 The class has been moved to Magento_Cookie module. Please try to sync up code with magento2 repository and clean up var directory. Please let us know if the problem still presents for you.

**Comment by vpelipenko** [comment]
Closed. There are more complaints from contributor.
