### ISSUE TITLE
BUG REPORT Can not change stock status with product CSV product import 

### ISSUE THREAD

**Issue by SitionDenBosch** [magento/magento2#10552]
### Preconditions
1.  Magento 2.1.5 and 2.1.7

### Steps to reproduce

1.  Import some products
2.  Export products to CSV 
3. edit is_in_stock to 1 (or 0)
4. import the CSV back into magento with is_in_stock edited

### Expected result
1. Stock status changes according to is_in_stock

### Actual result
1. It does not change stock status 

I have tried this on 3 separate magento installs, does not work anywhere.

Best regards,
Thom

**Comment by magento-engcom-team** [comment]
@SitionDenBosch Thank you for your report. May you please check sequence of steps to reproduce your issue in description.

**Comment by magento-engcom-team** [comment]
@SitionDenBosch, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by SitionDenBosch** [comment]
I missed the 4th step to reproduce: 

4. import the CSV back into magento with is_in_stock edited. 

This is basically all I do and I expect the stock status to update, but it does not

**Comment by magento-engcom-team** [comment]
@SitionDenBosch, thank you for your report.
We've created internal ticket(s) MAGETWO-81890 to track progress on the issue.

**Comment by SitionDenBosch** [comment]
@magento-engcom-team Thank you for acknowledging , will updates about the issue be reported back in this bug report, or should I follow the internal ticket somewhere?

**Comment by ishakhsuvarov** [comment]
@SitionDenBosch This issue will be closed once fix is released.

**Comment by SitionDenBosch** [comment]
@ishakhsuvarov When the fix is released, is it possible to see the solution, so I can create my own patch to fix it?

**Comment by SitionDenBosch** [comment]
@magento-engcom-team When the fix is released, is it possible to see the solution, so I can create my own patch to fix it?

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#36
