### ISSUE TITLE
Magento Upgrade 2.1.7 to 2.1.8

### ISSUE THREAD

**Issue by AaronONeill** [magento/magento2#10550]
Hey,

I have been updating our Magento 2 installs from 2.1.7 to 2.1.8 which had been going well on the majority of the sites. However on one of the sites I have been running into a fatal error whenever I try to run any magento upgrade/cache/compile etc commands.

### Preconditions

1. PHP 7
2. Magento 2.1.7 -> 2.1.8
3. Command Line Upgrade

### Steps to reproduce

1. Update composer to use Magento v2.1.8 
2. Run the composer update and wait till it has finished
3. Once completed, try running any Magento command - results in a fatal error

### Expected result

1. It should run the magento command without issue

### Actual result

1. Results in a fatal error

`Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\App\Config\ConfigSourceInterface in /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73
Stack trace:
#0 /home/user/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'source', 'Magento\\Config\\...')
#3 /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Arr in /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73`

Nothing on the site has been changes recently and a direct replica of the site upgraded without any issues. It just appears to be an issue on this site but I can't work out what is causing the error. I was able to successfully revert back to Magento 2.1.7 and the commands begun working again but as soon as I use Magento 2.1.8, I receive the fatal error.

**Comment by philipvandebriel** [comment]
Hi,
After composer update ,
If you use redis, then first ==> redis-cli then ==> flushall

Regards

**Comment by AaronONeill** [comment]
Hi Philip,

That worked perfectly, very good to know for future upgrades.

Thank You!

**Comment by PieterCappelle** [comment]
Nice! Had the same problem. Great 👍

**Comment by davidvarney** [comment]
Had the same problem going from 2.1.6 to 2.1.9 and this fixed the issue. Thank you, @philipvandebriel!

**Comment by dchaykas** [comment]
Same problem updating 2.1.7 to 2.1.9, the fix worked perfectly. Thank you.

**Comment by MalibuCommerce** [comment]
Thanks a bunch, @philipvandebriel! Lifesaver!

**Comment by davidxdbp** [comment]
Again, another website saved :) flushing redis did the trick.

**Comment by eltonmota** [comment]
Nice!!! @philipvandebriel, thank you!
