### ISSUE TITLE
Magento 2.1.8- Problem Installing Extensions w/ Dependencies

### ISSUE THREAD

**Issue by raceves2005** [magento/magento2#10561]
I have been attempting to Build Magento 2 with a large amount of Configurable Product Combinations. I have been attempting to Install an Extension Called Advanced Custom Options From MageWorx, we have been working with the developer for weeks now and they cannot seem to be able to get this extension to work. I get a Knockout.js error, after so many attempts to fix the store crashed i was forced to rebuild. I then purchased another extension called Configurable Bundle, this also is an extension that adds more configurations to the product page, the goal to these extensions is to be able to have customers purchase a set of wheels and within the same page have the ability to add a tire to the package. As soon as that extension was installed i am also getting a .js error as listed below. I have not been able to seemlessly install an extension without producing product errors in the front end.
 If we cant get these extensions to work that means no one else can, these are brand new installations, is there different structure with the product page from previous versions of magento 2?
Wizkunde - Configurable Bundle
http://unleashed-motorsports.com/aodhan-ds01-gloss-black-black-chrome-gold-chrome.html
![configbundle install](https://user-images.githubusercontent.com/29742107/29396183-2b3b562a-82cb-11e7-8b3b-502740c815c9.png)

MageWorx - Advanced Custom Options -
http://mage2.unleashedwheels.com/avid-1-av-02.html

![script error after developer work around](https://user-images.githubusercontent.com/29742107/29395946-76976ed0-82c9-11e7-8fb3-eb97a1aa37ba.png)

 

### Preconditions
1. PHP 7.0.2
2. MySQL 5.6
3. Same Error on Magento 2.1.7 and 2.1.8

### Steps to reproduce
Configurable Bundle:

1. Extracted Zip File to Root Folder and Installed Extension Correctly: Setup:Upgrade and setup:static-content:deploy
2. With Configurable Bundle we created 3 Configurable Products and Created one Bundle Product with 3 Configurable Products attached

- MageWorx Advanced Custom Options- 
1. Extracted Zip file to Root Folder and Installed Extension Correctly:Setup:Upgrade and setup:static-content:deploy
2. Created a new simple product
3. Created a new Custom option with a dependent option.

### Expected result
Configurable Bundle:
1. Listed Wheel which is priority will have a selection for Bolt Pattern> Diameter> Finish> Wheel Specs>
All dependent on prior selections
2. The Second Configurable product that is part of the bundle is an optional Product, 2 Brand of tires resulting in 2 Configurable products, you Select the swatch image and Configurable Attributes populate in sort order with relevant options based on selections. 

Mageworx- Custom Options
1. Save Custom Options
2. Front End will have a Custom Option that once selected the children option with populate

### Actual result
Configurable Bundle-
1. All dependencies no longer work
2. All options are displayed regardless of selection
3. Only 2 Configurable Options are displayed when there are supposed to be 3
4. we get error on developer toosl
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at run (pub/static/version1502938077/frontend/Mgs/orson/en_US/Magento_Ui/js/core/renderer/layout.js:79)
    at pub/static/version1502938077/frontend/Mgs/orson/en_US/Magento_Ui/js/core/app.js:14
    at pub/static/version1502938077/frontend/Mgs/orson/en_US/mage/apply/main.js:30
    at Object.execCb (require.js:1650)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132
    at require.js:1156
    at each (require.js:57)

MageWorx: Advanced Custom Options

1. Cannot save dependent options
2. After developer attempted to fix the issue we get the error below

Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:141 Uncaught Error: Script error for: MageWorx_OptionInventory/js/catalog/product/inventory
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
features.js Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:141 Uncaught Error: Script error for: MageWorx_OptionFeatures/js/catalog/product/features
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
require.js:141 Uncaught Error: Mismatched anonymous define() module: function (){"use strict";function e(e,t){var i,n=document.createElement(e||"div");for(i in t)n[i]=t[i];return n}function t(e){for(var t=1,i=arguments.length;i>t;t++)e.appendChild(arguments[t]);return e}function i(e,t,i,n){var r=["opacity",t,~~(100*e),i,n].join("-"),a=.01+100*(i/n),o=Math.max(1-(1-e)/t*(100-a),e),l=u.substring(0,u.indexOf("Animation")).toLowerCase(),s=l&&"-"+l+"-"||"";return p[r]||(f.insertRule("@"+s+"keyframes "+r+"{"+"0%{opacity:"+o+"}"+a+"%{opacity:"+e+"}"+(a+.01)+"%{opacity:1}"+(a+t)%100+"%{opacity:"+e+"}"+"100%{opacity:"+o+"}"+"}",f.cssRules.length),p[r]=1),r}function n(e,t){var i,n,r=e.style;for(t=t.charAt(0).toUpperCase()+t.slice(1),n=0;n<c.length;n++)if(i=c[n]+t,r[i]!==void 0)return i;return r[t]!==void 0?t:void 0}function r(e,t){for(var i in t)e.style[n(e,i)||i]=t[i];return e}function a(e){for(var t=1;t<arguments.length;t++){var i=arguments[t];for(var n in i)e[n]===void 0&&(e[n]=i[n])}return e}function o(e){for(var t={x:e.offsetLeft,y:e.offsetTop};e=e.offsetParent;)t.x+=e.offsetLeft,t.y+=e.offsetTop;return t}function l(e,t){return"string"==typeof e?e:e[t%e.length]}function s(e){return"undefined"==typeof this?new s(e):(this.opts=a(e||{},s.defaults,h),void 0)}function d(){function i(t,i){return e("<"+t+' xmlns="urn:schemas-microsoft.com:vml" class="spin-vml">',i)}f.addRule(".spin-vml","behavior:url(#default#VML)"),s.prototype.lines=function(e,n){function a(){return r(i("group",{coordsize:u+" "+u,coordorigin:-d+" "+-d}),{width:u,height:u})}function o(e,o,s){t(p,t(r(a(),{rotation:360/n.lines*e+"deg",left:~~o}),t(r(i("roundrect",{arcsize:n.corners}),{width:d,height:n.width,left:n.radius,top:-n.width>>1,filter:s}),i("fill",{color:l(n.color,e),opacity:n.opacity}),i("stroke",{opacity:0}))))}var s,d=n.length+n.width,u=2*d,c=-(n.width+n.length)*2+"px",p=r(a(),{position:"absolute",top:c,left:c});if(n.shadow)for(s=1;s<=n.lines;s++)o(s,-2,"progid:DXImageTransform.Microsoft.Blur(pixelradius=2,makeshadow=1,shadowopacity=.3)");for(s=1;s<=n.lines;s++)o(s);return t(e,p)},s.prototype.opacity=function(e,t,i,n){var r=e.firstChild;n=n.shadow&&n.lines||0,r&&t+n<r.childNodes.length&&(r=r.childNodes[t+n],r=r&&r.firstChild,r=r&&r.firstChild,r&&(r.opacity=i))}}var u,c=["webkit","Moz","ms","O"],p={},f=function(){var i=e("style",{type:"text/css"});return t(document.getElementsByTagName("head")[0],i),i.sheet||i.styleSheet}(),h={lines:12,length:7,width:5,radius:10,rotate:0,corners:1,color:"#000",direction:1,speed:1,trail:100,opacity:.25,fps:20,zIndex:2e9,className:"spinner",top:"auto",left:"auto",position:"relative"};s.defaults={},a(s.prototype,{spin:function(t){this.stop();var i,n,a=this,l=a.opts,s=a.el=r(e(0,{className:l.className}),{position:l.position,width:0,zIndex:l.zIndex}),d=l.radius+l.length+l.width;if(t&&(t.insertBefore(s,t.firstChild||null),n=o(t),i=o(s),r(s,{left:(l.left=="auto"?n.x-i.x+(t.offsetWidth>>1):parseInt(l.left,10)+d)+"px",top:(l.top=="auto"?n.y-i.y+(t.offsetHeight>>1):parseInt(l.top,10)+d)+"px"})),s.setAttribute("role","progressbar"),a.lines(s,a.opts),!u){var c,p=0,f=(l.lines-1)*(1-l.direction)/2,h=l.fps,b=h/l.speed,g=(1-l.opacity)/(b*l.trail/100),m=b/l.lines;(function y(){p++;for(var e=0;e<l.lines;e++)c=Math.max(1-(p+(l.lines-e)*m)%b*g,l.opacity),a.opacity(s,e*l.direction+f,c,l);a.timeout=a.el&&setTimeout(y,~~(1e3/h))})()}return a},stop:function(){var e=this.el;return e&&(clearTimeout(this.timeout),e.parentNode&&e.parentNode.removeChild(e),this.el=void 0),this},lines:function(n,a){function o(t,i){return r(e(),{position:"absolute",width:a.length+a.width+"px",height:a.width+"px",background:t,boxShadow:i,transformOrigin:"left",transform:"rotate("+~~(360/a.lines*d+a.rotate)+"deg) translate("+a.radius+"px"+",0)",borderRadius:(a.corners*a.width>>1)+"px"})}for(var s,d=0,c=(a.lines-1)*(1-a.direction)/2;d<a.lines;d++)s=r(e(),{position:"absolute",top:1+~(a.width/2)+"px",transform:a.hwaccel?"translate3d(0,0,0)":"",opacity:a.opacity,animation:u&&i(a.opacity,a.trail,c+d*a.direction,a.lines)+" "+1/a.speed+"s linear infinite"}),a.shadow&&t(s,r(o("#000","0 0 4px #000"),{top:"2px"})),t(n,t(s,o(l(a.color,d),"0 0 1px rgba(0,0,0,.1)")));return n},opacity:function(e,t,i){t<e.childNodes.length&&(e.childNodes[t].style.opacity=i)}});var b=r(e("group"),{behavior:"url(#default#VML)"});return!n(b,"transform")&&b.adj?d():u=n(b,"animation"),s}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:166)
    at intakeDefines (require.js:1221)
    at require.js:1408
dependency.js Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:141 Uncaught Error: Script error for: MageWorx_OptionDependency/js/dependency
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
select.js Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:141 Uncaught Error: Script error for: MageWorx_OptionDependency/js/select
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
![testsite](https://user-images.githubusercontent.com/2

9742107/29395922-51f3d1cc-82c9-11e7-919c-26888a164129.png)

**Comment by orlangur** [comment]
> Extracted Zip File to Root Folder and Installed Extension Correctly

Does not look like a proper bug report for this repository to me, respective extension developers should be contacted instead.

Buggy code tries to parse `undefined` while some valid JSON string is expected.

**Comment by orlangur** [comment]
@raceves2005 bugs in third-party extensions must be fixed but their respective vendors. Please provide additional details if you reveal a problem in Magento core.
