### ISSUE TITLE
Admin: Manage Attributes -> Manage Label / Options - Needs a limit / paging

### ISSUE THREAD

**Issue by fr0x** [magento/magento2#1056]
This may be fixed in Magento 2 (I dont have a current 2.x install to check but recently ran into this in a 1.6.2 install).

The Manage Label / Options screen when you are editing an attribute has no limit on the number of options it displays.  For one attribute, we have thousands of options.  The admin screen tries to load every single one and it tends to cause the browser to crash/hang.

**Comment by kokoc** [comment]
@fr0x Thank you for the idea! We have created an issue in the product backlog - MAGETWO-34525. We will get back to you once we complete the analysis.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Admin-Manage-Attributes-gt-Manage-Label-Options-Needs-a-limit/idi-p/46626).

**Comment by teodorpav** [comment]
It is very important functions for big stores.
