### ISSUE TITLE
Large customer export don't work well (Export only a few records)

### ISSUE THREAD

**Issue by Jalondhara** [magento/magento2#10573]
Unable to export customer list - I go to Customers -> All Customers -> export to CSV or Excel - neither allows me to export the list.  I get following error in magento 2.1.4

Notice: Undefined offset: 1 in /chroot/home/tgoldkam/tgoldkamp.com/html/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php on line 103
![error](https://user-images.githubusercontent.com/31101994/29415172-c2253ccc-837f-11e7-87f2-69062b09b754.png)

Updated info:
**Preconditions**: Magento ver. 2.1.8
**Steps to reproduce**: Go to Customers / All customers, select any number of entries >=7 and export to csv
**Expected result**: csv file with customer data
**Actual result**: error message above

**Comment by vherasymenko** [comment]
@Jalondhara Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by Jalondhara** [comment]
Please help me to resolved this issue on magento 2.1.4 version.

**Comment by magento-engcom-team** [comment]
@Jalondhara  thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by msbt** [comment]
Hi!
I have almost the same issues, but it occurs when I try to export more than 6 customers at a time. As soon as i try to export 7 or more, it throws this error

> There has been an error processing your request

> Notice: Undefined offset: 2 in /var/www/magento/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php on line 103

Infos: 
Magento ver. 2.1.8
Steps to reproduce: Go to Customers / All customers, select any number of entries >=7 and export to csv
Expected result: csv file with customer data
Actual result: error message above

Best regards, M

**Comment by magento-engcom-team** [comment]
@Jalondhara, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by wget** [comment]
I'm experiencing this problem as well. With exports above 10-20 customers, this fails with the same undefined index. Will debug this more closely later. I'm on Magento 2.1.10.

**Comment by wget** [comment]
I have just found the culprit of the problem.

The problem was due to the way the data coming from 1.5 have been migrated. On 1.5, for some reason I had a website_id with `0` as identifier.

As I migrated the clients of that website_id as well, Magento 2 complained for some reason the offset in the table `$list[$value]` was incorrect/non existent.

```
     private function setWebsiteValue()
     {
         $value = $this->getData(self::$websiteAttributeCode);
         $list = $this->storeManager->getWebsites();
         $this->setCustomAttribute(self::$websiteAttributeCode, $list[$value]->getName());
     }
```

So I removed the client from website_id and the issue is now gone. These clients were all duplicated any way.

To check whether you are impacted by the same problem as me, check if you can export clients by defining a specific website id in the customer filters.
![screenshot_20171207_225355](https://user-images.githubusercontent.com/2997662/33740604-884790f2-dba1-11e7-9bde-6b0e4acdd637.png)

**Comment by rahuldambare** [comment]
Hi @wget,
I tried your solution by changing incorrect website id with specific stores. 
But I didn't understand where did you change in code. 
Can you please explain in details. 

Thanks

**Comment by wget** [comment]
@rahuldambare This is simple.
I went in the table `customer_entity` and searched for the clients being in the website_id 0 with
```
select entity_id from customer_entity 
where website_id=0
```
You might have some results. The ids you get are the customer IDs responsible for this error.

Then, just go in the Magento 2 admin panel and remove the clients with these client number. (entity_id being the customer id).

Another solution might be just to change the `website_id` to `0` for these customers, but in my use case, these customers were duplicated, so I removed them any way :)

**Comment by rahuldambare** [comment]
@wget Yes I already checked this. No customer with website-id = 0 found in my database;

**Comment by wget** [comment]
@rahuldambare This issue can also happen when you have clients saved in store views that do not exist. I realized this issue can happen with data coming from some old outdated Magento 1.x series especially if they have been bruteforced/SQL injected.

If this doesn't help, check your Magento stacktrace/debug info, your PHP fpm logs. As the ultimate debug solution, log your database queries with `general-log` and `general-log-file` on MySQL/MariaDB.

Hope this helps.

**Comment by shahabhameed** [comment]
@magento-engcom-team,

This issue is reproducible on Magento 2.2.3 EE. 

The following is the JSON error log: 

```
{
  "0": "Notice: Undefined offset: 7 in /vendor/magento/module-customer/Ui/Component/DataProvider/Document.php on line 136",
  "1": "#0 /vendor/magento/module-customer/Ui/Component/DataProvider/Document.php(136): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Undefined offse...', '/app/wtzyes327l...', 136, Array)\n#1 /vendor/magento/module-customer/Ui/Component/DataProvider/Document.php(102): Magento\\Customer\\Ui\\Component\\DataProvider\\Document->setGenderValue()\n#2 /vendor/magento/module-ui/Model/Export/MetadataProvider.php(159): Magento\\Customer\\Ui\\Component\\DataProvider\\Document->getCustomAttribute('gender')\n#3 /vendor/magento/module-ui/Model/Export/ConvertToCsv.php(84): Magento\\Ui\\Model\\Export\\MetadataProvider->getRowData(Object(Magento\\Customer\\Ui\\Component\\DataProvider\\Document), Array, Array)\n#4 /vendor/magento/module-ui/Controller/Adminhtml/Export/GridToCsv.php(72): Magento\\Ui\\Model\\Export\\ConvertToCsv->getCsvFile()\n#5 /vendor/magento/framework/App/Action/Action.php(107): Magento\\Ui\\Controller\\Adminhtml\\Export\\GridToCsv->execute()\n#6 /vendor/magento/module-backend/App/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#7 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Ui\\Controller\\Adminhtml\\Export\\GridToCsv\\Interceptor->___callParent('dispatch', Array)\n#9 /vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\\Ui\\Controller\\Adminhtml\\Export\\GridToCsv\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#10 /vendor/magento/framework/Interception/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Ui\\Controller\\Adminhtml\\Export\\GridToCsv\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#11 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Ui\\Controller\\Adminhtml\\Export\\GridToCsv\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#12 /generated/code/Magento/Ui/Controller/Adminhtml/Export/GridToCsv/Interceptor.php(26): Magento\\Ui\\Controller\\Adminhtml\\Export\\GridToCsv\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#13 /vendor/magento/framework/App/FrontController.php(55): Magento\\Ui\\Controller\\Adminhtml\\Export\\GridToCsv\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#14 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#15 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#16 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#17 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#18 /vendor/magento/framework/App/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#19 /vendor/magento/framework/App/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#20 /pub/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#21 {main}",
  "url": "/admin/mui/export/gridToCsv/key/4b1c73d5e71f0802f16b0380aecd481a7ec5f2b6a45b7006a243d13dd3ce9be4/?filters%5Bplaceholder%5D=true&search=&namespace=customer_listing&selected=false",
  "script_name": "/index.php"
}
```

@rahuldambare , @wget : I have also checked the database, no customers with website_id=0 exist in the database.

cc: @msbt 

**Update:**

I was able to solve the issue by replacing the following function in "Magento\Customer\Ui\Component\DataProvider\Document.php":

```
   /**
     * Update customer gender value
     * Method set gender label instead of id value
     * @return void
     */
    private function setGenderValue()
    {
        $value = $this->getData(self::$genderAttributeCode);

        if (!$value) {
            $this->setCustomAttribute(self::$genderAttributeCode, 'N/A');
            return;
        }

        try {
            $attributeMetadata = $this->customerMetadata->getAttributeMetadata(self::$genderAttributeCode);
            $option = $attributeMetadata->getOptions()[$value];
            $this->setCustomAttribute(self::$genderAttributeCode, $option->getLabel());
        } catch (NoSuchEntityException $e) {
            $this->setCustomAttribute(self::$genderAttributeCode, 'N/A');
        }
    }
```

by 

```
   /**
     * Update customer gender value
     * Method set gender label instead of id value
     * @return void
     */
    private function setGenderValue()
    {
        $value = $this->getData(self::$genderAttributeCode);


        if (!$value) {
            $this->setCustomAttribute(self::$genderAttributeCode, 'N/A');
            return;
        }

        try {
            $attributeMetadata = $this->customerMetadata->getAttributeMetadata(self::$genderAttributeCode);

            foreach ($attributeMetadata->getOptions() as $option) {
                if ($option->getValue() == $value) {
                    $this->setCustomAttribute(self::$genderAttributeCode, $option->getLabel());
                    break;
                }
            }
        } catch (NoSuchEntityException $e) {
            $this->setCustomAttribute(self::$genderAttributeCode, 'N/A');
        }
    }
```

**Comment by Vaibhavm1987** [comment]
Unable to download/export Contact details of all customers, neither CSV nor XML.

Always gives a an error:

"There has been an error processing your request
Notice: Undefined index:  in /home/dentbaydemolocat/public_html/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php on line 135
Error log record number: 254440957557"


I am using: Magento 2.1.7:: Please help

**Comment by wget** [comment]
@Vaibhavm1987 The cause of this particular issue is multiple, see the possible solutions explained above ^
e.g.: removing the client, client duplicated in another website id but not in all, etc.

**Comment by Vaibhavm1987** [comment]
Dear Sir, I am new to magento, My developer is currently not available for some time soon. And I am totally new to this and have no clue what to do...I do have the all the necessary access. Please help, what shoul I do step by step..to resolve the issue.

**Comment by wget** [comment]
@Vaibhavm1987 Best bet is not to touch to such critical part if you are not used to develop with Magento. Ask for help via a short job offer on [freelancer](https://www.freelancer.com/) for example. You may find someone willing to help you just in exchange of a small fee. :)

**Comment by ghost** [comment]
After migration of 1.9.3.8 to 2.2.7 I had the same issue. 2 of my "customer_entity.website_id" were NULL
