### ISSUE TITLE
Unable to create new integration in Magento2

### ISSUE THREAD

**Issue by jobsmartdesigner1507** [magento/magento2#10571]
### Preconditions

Magento 2.1.7, PHP Version 5.6.31 & MySQL version--Not Sure, This is a test site that is up and running live. 

Cache cleared and re- indexed and I have disable any third party extension one by one to see if they were causing it. It did not restore when they were disabled. 

We have Magento 2.1.6 running on another demo site with the same extensions--on that site the integrations sections is fine and the payment method and shopping cart were blank so we made this site and those are working great on this new site but not the integration section which absolutely needs to be working

### Steps to reproduce

1. Got to System  ----> Integrations ----> ADD NEW
2. All you see is a back button and a save button but the form doesnt show up to create the API and have it connected.
3. Error is created in the error log

### Expected result

1. Should be able to create and connect a third party API

### Actual result

1. 
![screenshot 271](https://user-images.githubusercontent.com/30318718/29413607-ebd85b12-832a-11e7-9eba-c36d06afe88b.png)

Error Log:

a:4:{i:0;s:154:"Notice: Undefined index: all_resources in /home/wworks/public_html/demo/vendor/magento/module-integration/Controller/Adminhtml/Integration.php on line 129";i:1;s:5311:"#0 /home/wworks/public_html/demo/vendor/magento/module-integration/Controller/Adminhtml/Integration.php(129): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/wworks/pu...', 129, Array)
#1 /home/wworks/public_html/demo/vendor/magento/module-integration/Controller/Adminhtml/Integration/NewAction.php(18): Magento\Integration\Controller\Adminhtml\Integration->restoreResourceAndSaveToRegistry()
#2 /home/wworks/public_html/demo/var/generation/Magento/Integration/Controller/Adminhtml/Integration/NewAction/Interceptor.php(24): Magento\Integration\Controller\Adminhtml\Integration\NewAction->execute()
#3 /home/wworks/public_html/demo/vendor/magento/framework/App/Action/Action.php(102): Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor->execute()
#4 /home/wworks/public_html/demo/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor->___callParent('dispatch', Array)
#7 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Integra...', 'dispatch', Object(Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor), Array, 'adminAuthentica...')
#8 /home/wworks/public_html/demo/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Integra...', 'dispatch', Object(Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor), Array, 'adminMassaction...')
#11 /home/wworks/public_html/demo/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /home/wworks/public_html/demo/var/generation/Magento/Integration/Controller/Adminhtml/Integration/NewAction/Interceptor.php(39): Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /home/wworks/public_html/demo/vendor/magento/framework/App/FrontController.php(55): Magento\Integration\Controller\Adminhtml\Integration\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#17 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#18 /home/wworks/public_html/demo/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /home/wworks/public_html/demo/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /home/wworks/public_html/demo/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /home/wworks/public_html/demo/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/wworks/public_html/demo/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#23 /home/wworks/public_html/demo/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#24 {main}";s:3:"url";s:120:"/demo/pub/index.php/okthxoyt/admin/integration/new/key/efbaf92708927695175eaa3b69ff509e5719dbe76363a3418d9f468bda8c1032/";s:11:"script_name";s:19:"/demo/pub/index.php";}

**Comment by misha-kotov** [comment]
@jobsmartdesigner1507  please add your Magento version and system information in accordance with reporting guidelines. 
- How many and what kinds of integrations do you already have created? 
- Is this reproducible on clean Magento? 
- Did disabling all extensions work in your case? 
- Does refreshing the page help?

**Comment by jobsmartdesigner1507** [comment]
sorry I had it in there but it was commented out

**Comment by magento-engcom-team** [comment]
@jobsmartdesigner1507, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
