### ISSUE TITLE
Ui form elements are not reacting on Safari autofill events 

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#10576]
When using Magento2 storefront with ios , osx or win Safari browser and using it's autofill functionality , native change events are not fired and knockoutjs observable subscriptions not evoked 

### Preconditions

1. all m2 versions 

### Steps to reproduce

1. go to checkout with safari browser (both win and osx are affected) or any page where you have address form and at least subscriber to value change on some element 
2. use autofill to fill the form 

### Actual Result
3. events are not fired, no subscribed functions evoked 

### Expected result

1. should work as expected and events fired 

### Temporary solution

1. add data binding to element templates:  valueUpdate: 'blur' as blur event is fired by autofill. 

###  related m2 issues 
1. https://github.com/magento/magento2/issues/6826 

### related knockoutjs issues 
1. https://github.com/knockout/knockout/issues/1949

**Comment by magento-engcom-team** [comment]
@speedupmate, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
