### ISSUE TITLE
[2.2.0-RC2.0] composer/composer dependency in generated composer.json still at stability @alpha

### ISSUE THREAD

**Issue by hostep** [magento/magento2#10577]
### Preconditions
1. PHP 7.0.22
2. Have composer installed

### Steps to reproduce
1. Execute:
```
$ mkdir mage22test
$ cd mage22test
$ composer create-project --no-install --repository-url=https://repo.magento.com/ --stability=RC magento/project-community-edition .
$ cat composer.json | grep composer/composer
```

### Expected result
1. No requirement on `composer/composer` and especially not with the `@alpha` constraint

### Actual result
1. Output of grep: `"composer/composer": "@alpha"`

### Discussion
It was decided to stabilize the composer dependency over here: https://github.com/magento/magento2/issues/4359

So there should be no `@alpha` constraint in the resulting `composer.json`
The requirement can probably be removed entirely since it is already a dependency of the packages: `magento/composer` and `magento/framework` and `magento/magento2-base` and `magento/product-community-edition`

(`magento/magento-composer-installer` also still has a dependency on: `"composer/composer": "*@dev"`, but that's probably less important to fix)

**Comment by fooman** [comment]
Can confirm this - resulting composer.json:

    "require": {
        "magento/product-community-edition": "2.2.0-rc20",
        "composer/composer": "@alpha"
    }

**Comment by korostii** [comment]
By the way, composer is also still at `@alpha` if you download the prepackaged archive from https://magento.com/tech-resources/download

**Comment by hostep** [comment]
Just FYI: this is still the case with Magento 2.3.0-beta2, @okorshenko: maybe this can get cleaned up before 2.3.0 GA gets released?

**Comment by pdohogne-magento** [comment]
Confirmed no issues, this will be cleaned up in the 2.3.0 project files.

**Comment by hostep** [comment]
Just tested `2.3.0-beta12` and it looks like `composer/composer` is gone from the main `composer.json` file now, let's close this issue then, thanks!
