### ISSUE TITLE
Stock Managment issue 2.1.8

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#10578]
### Preconditions

1. Magento 2.1.8, php7

### Steps to reproduce

1. When trying to reduce stock or put item out of stock its giving date error 

### Actual Result:

Error (Invalid input datetime format of value '26/07/2017')

![screenshot 31](https://user-images.githubusercontent.com/13229022/29436474-1530fa40-83ef-11e7-9891-1fe738c1351a.png)

### Expected Result
no error on the form

**Comment by terrybakshi** [comment]
After Changing my account locale to Eng Us it started working, I think Magento should consider fixing this major bug ASAP as its causing too many issue. for more info refer to https://github.com/magento/magento2/issues/10485

**Comment by allanpaiste** [comment]
I'm unable to repeat this :( 

Would it be possible to get more detailed steps on how to repeat it?

Preferably with demo data (a'la, using some product in demo and then setting it out of stock).

**Comment by AlexWorking** [comment]
Hello, @terrybakshi. According to Your issue an internal ticket has been created - MAGETWO-71936. You'll be informed as the bug is fixed. Thanks for reporting.

**Comment by magento-engcom-team** [comment]
@terrybakshi, thank you for your report.
We've created internal ticket(s) MAGETWO-71936 to track progress on the issue.

**Comment by cproboscht** [comment]
i'm working on it

**Comment by cproboscht** [comment]
in 2.1.10 the problem is not there, but the display in the date picker is different
Its because in 2.1.10 its displaying and posting in en_US format (mm/dd/yyyy)
From 2.1.10 to 2.2 the format for date changed for en_UK to dd/mm/yyyy 

Problem also in 2.2 for locale en_UK: Date: 03. March 2017 will be set to 06.June 2017 ( dd/mm <> mm/dd )
![datepicker_2 1 10](https://user-images.githubusercontent.com/16148781/31043736-91531c72-a5c1-11e7-91bb-a418d3dfb7b7.png)

**Comment by engcom-Delta** [comment]
@cproboscht Unfortunately, I cannot reproduce this issue by steps you described on 2.4-develop
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
