### ISSUE TITLE
M2.1.8 Production Mode Issue

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#10581]
I have set my store to Production Mode and every time I do an edit in the Admin it gives me the normal "Refresh Cache" system message but now it is giving me a second system message about my "indexers being invalid" and to check if my cron jobs are running - see screenshot. This was not occurring in Default mode, why is this occurring now?

![production](https://user-images.githubusercontent.com/10808588/29447955-aa5db34a-8437-11e7-93ad-04bf8b638eea.jpg)

### Additional Information
Experiencing multiple bugs in Production mode after applying optimizations.

### Preconditions
1. Magento 2.1.8 PHP 7.0.2
2. Production Mode
3. Optimizations outlined in http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_perf-optimize.html

### Steps to reproduce
1. Not relevant 

### Expected result
1. Indexing should be instant
2. Orders should appear immediately after they are placed
3. Products should appear in frontend when added in Admin

### Actual result
1. Changes in Admin take up to 1 minute to index and clear
2. Orders take up to 10 minutes to appear in Admin
3. Products stop appearing in frontend after being added in Admin. Requires cli indexing.

Platform dependent comment
1. Production Mode 
2. All optimizations outlined in http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_perf-optimize.html apart from Varnish

Additional note.
1. Issues do not occur in Default mode

**Comment by rbur0425** [comment]
Is the cron set up correctly? Can you paste your crontab?

**Comment by jordanbrauer** [comment]
Check your crontab settings and ensure that your paths to the Magento binary are correct.

---

The indexer is sort of broken it seems. It doesn't properly invalidate things from what I gather on the issues #5836, #9174 and #9228.

I've got a similar problem that is solved by manually running the indexer from your Magento root directory and then flushing the cache.

```shell
$ bin/magento indexer:reindex
$ bin/magento cache:flush
```

**Comment by bondimedical3** [comment]
* * * * * /usr/local/bin/php /home/extende/public_html/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /home/extende/public_html/var/log/magento.cron.log
* * * * * /usr/local/bin/php /home/extende/public_html/update/cron.php >> /home/extende/public_html/var/log/update.cron.log
* * * * * /usr/local/bin/php /home/extende/public_html/bin/magento setup:cron:run >> /home/extende/public_html/var/log/setup.cron.log

^^ these are my cron jobs. what I am finding is that the issue clears after a while, I am guessing after cron has run but shouldn't it reindex immediately?

**Comment by johnny-longneck** [comment]
Had a similar problem and you also have to set the indexer update behaviour from "update on save" to "update on schedule".

Hope this helps

**Comment by vherasymenko** [comment]
@bondimedical3 Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by bondimedical3** [comment]
Experiencing multiple bugs in Production mode after applying optimizations.

### Preconditions
1. Magento 2.1.8 PHP 7.0.2
2. Production Mode
3. Optimizations outlined in http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_perf-optimize.html

### Steps to reproduce
1. Not relevant 

### Expected result
1. Indexing should be instant
2. Orders should appear immediately after they are placed
3. Products should appear in frontend when added in Admin

### Actual result
1. Changes in Admin take up to 1 minute to index and clear
2. Orders take up to 10 minutes to appear in Admin
3. Products stop appearing in frontend after being added in Admin. Requires cli indexing.

Platform dependent comment
1. Production Mode 
2. All optimizations outlined in http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_perf-optimize.html apart from Varnish

Additional note.
1. Issues do not occur in Default mode

**Comment by magento-engcom-team** [comment]
Hi @bondimedical3 
thank you for update. We updated issue description

**Comment by magento-engcom-team** [comment]
@bondimedical3, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
