### ISSUE TITLE
Low Stock Report Grid Empty

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#10595]
### Preconditions
1. Magento 2.1.8 CE
2. Single website, single store view, single store mode.

### Steps to reproduce
1. Create product with 0 stock, out of stock.
2. View Low Stock Report

### Expected result
1. Grid should show product out of stock

### Actual result
1. Grid is empty

This is a reopen of #9408 but I couldnt see a way of reopening.

This bug is caused because the code to generate the report is expecting either the website, store or view to be passed into the function on the url as a get parameter. If none is present, as is the case in the default store, then storeid is not set.

vendor/magento/module-reports/Block/Adminhtml/Product/Lowstock/Grid.php

Line 54 change from
            $storeId ='';
to
            $storeId = $this->_storeManager->getStore()->getId();

Seems to work for me. Only tested in single store mode.

**Comment by orlangur** [comment]
> This is a reopen of #9408 but I couldnt see a way of reopening.

It seems to be open.

Could you please prepare a pull request for consideration? This is always better than discuss possible ways to fix in issue description.

**Comment by oleg-onufer** [comment]
Hi @gwharton.
Thanks for reporting this issue.
Internal ticket MAGETWO-60947 was created.

**Comment by Linek** [comment]
I'm on it

**Comment by magento-engcom-team** [comment]
@gwharton, thank you for your report.
We've created internal ticket(s) MAGETWO-75540 to track progress on the issue.

**Comment by miguelbalparda** [comment]
There is a proposed fix for this [here](https://github.com/magento/magento2/pull/10935), can you check it and report back?

**Comment by gwharton** [comment]
Works for me on a single store installation of 2.2.0-rc30 and a multiwebsite install of 2.1.9.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-75320

**Comment by miguelbalparda** [comment]
This should be fixed by #10935

**Comment by gwharton** [comment]
@miguelbalparda What is the process of getting #10935 backported into 2.1 and 2.2

**Comment by gwharton** [comment]
Still Broken in 2.2.2

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#13682 by @gwharton in 2.2-develop branch
Related commit(s):
 - [bf941eb6655ddf120b58691aaa1722412bd957d8](https://github.com/magento/magento2/commit/bf941eb6655ddf120b58691aaa1722412bd957d8)

The fix will be available with the upcoming 2.2.4 release.
