### ISSUE TITLE
Error connected to M2E

### ISSUE THREAD

**Issue by Zu-Hause-Plattform** [magento/magento2#10606]
I am using a commercial plugin with Magento and every time i tried to load products i get some error message: see snapshot. Magento ver. 2.1.7
![magentobug](https://user-images.githubusercontent.com/31216612/29527774-1dbe0e66-869a-11e7-8e83-274d60b93b03.png)

### Preconditions
Windows
FF

**Comment by orlangur** [comment]
GitHub is intended for bug reports in Magento 2 core modules.

Developer of `Ess_M2ePro` extension should be contacted in your case.
