### ISSUE TITLE
Fix documentation link indocs.magento.com/m2/ee/user_guide......

### ISSUE THREAD

**Issue by Tjmstudios** [magento/magento2#10609]
### Preconditions

1. Access to the internet
2. Any Magento version

### Steps to reproduce

1. Go to http://docs.magento.com/m2/ee/user_guide/marketing/google-tag-manager.html
2. Expand "Step 2: Configure Your Google Tag Manager Account"
3. Right-click this link: GMT M2 Config.json. Then, choose “Save link as” to download the sample configuration file.
4. Result: downloaded the github 404 HTML page as .JSON
5. Cry

--

### Expected result

1. Go to http://docs.magento.com/m2/ee/user_guide/marketing/google-tag-manager.html
2. Expand "Step 2: Configure Your Google Tag Manager Account"
3. Right-click this link: GMT M2 Config.json. Then, choose “Save link as” to download the sample configuration file.
4. Result: Downloaded a JSON file that is compatible with Google Tag Manager import.
See example of what the file may look like, expect it should be .json and not .txt ().[GTM-PZ8GMML_workspace13.txt](https://github.com/magento/magento2/files/1240363/GTM-PZ8GMML_workspace13.txt)
5. :smile:

### Actual result

1. Click link to check file
2. See GitHub 404
![screen shot 2017-08-22 at 9 23 22 am](https://user-images.githubusercontent.com/11372070/29542035-a1b21682-871b-11e7-84b8-da462db0bbcb.png)

**Comment by pboisvert** [comment]
Thanks for the report but this Issues board is specific to issues in the code of M2--not documentation issues. To report documentation issues please go to the Dev docs repo here: https://github.com/magento/devdocs/issues You can file an issue or submit a PR to fix an issue
