### ISSUE TITLE
Google Shopping

### ISSUE THREAD

**Issue by 5mehulhelp5** [magento/magento2#1060]
I think Google Shopping api is going to expire soon but i show in magento 2 we are using still a V1 so it's better if we can Update that to V2.......

**Comment by Tiurnikova** [comment]
Hello @5mehulhelp5, sorry for the late reply. You're right. Google Shopping api is expired, so it was removed from Magento 2 due to low usage of that functionality.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Google-Shopping/idi-p/46624).
