### ISSUE TITLE
Configurable Products - Website Category Page - Product Thumbnail - How to Show View Details Instead Add to Cart?

### ISSUE THREAD

**Issue by hardik18882** [magento/magento2#10617]
Magento ver. 2.1.8
PHP 7

We have all products as "Configurable Products". Now on Front Website when we browse Category, It shows "Add to Cart" button on ALL products.. When we click on "Add to Cart" it takes to Detail page with this error message "You need to choose options for your item." since all product has some selection required. If we click "Add to Cart" from Product detail page after doing all required selection of Attributes it works fine.  

Shouldn't it show "View Detail" Button on Category View page under each product? Am I missing any configuration for the same?

Please help.

Thanks,

**Comment by orlangur** [comment]
Not sure about the "View Detail" functionality, here you can see some demo with swatches configured: http://magento2-demo.nexcess.net/men/tops-men/hoodies-and-sweatshirts-men.html

**Comment by hardik18882** [comment]
Hello @orlangur 
Our website has all products as Configurable products still it shows "Add to Cart" button instead "View Detail". Now If you see theme demo on http://ultimo.infortis-themes.com/demo/fifth/fashion.html it shows "View Detail" button if product is Configurable. This doesnt show into our website. 
Thanks,

**Comment by hardik18882** [comment]
Hello, I believe it's NOT possible with Magento 2.. Since this was showing to "View Detail" in Magento 1.X by default when Product type is configurable product. While with magento 2 it shows "Add to Cart" only.. Am I thinking it correct?

**Comment by orlangur** [comment]
It's up to the theme how to display product listing. There does not seem to be "View Details" in core templates in catalog.

However, here is something similar to logic you need: https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/templates/product/list/items.phtml#L219

In your case, when product does not have required options, just display in `else` something like
```
<a title="View Details" class="button btn-cart" href="http://ultimo.infortis-themes.com/demo/fifth/top1.html">View Details</a>
```
