### ISSUE TITLE
no changes in date at special prices

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#10618]
### Preconditions

1. M2 2.1.8
2. PHP 7.0.22

### Steps to reproduce

1.  Go to Price -> extendet price -> special price 
2. at this on special price from  i have entered the date from a special price, but if i wont to change it in a new one, the old date will stay
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/31250340/29574507-11aa6296-8762-11e7-8f20-da7345a58a8d.png)

**Comment by RomanKrut** [comment]
@Olek89 Hi, thanks for reporting this issue. The internal ticket MAGETWO-71918 was created to address this issue.

**Comment by gediminaskv** [comment]
it may be linked to https://github.com/magento/magento2/issues/10580

Try workaround https://github.com/magento/magento2/issues/10485#issuecomment-321543660

**Comment by Olek89** [comment]
thank you for the workaround but i think it does not work.

**Comment by magento-engcom-team** [comment]
@Olek89, thank you for your report.
We've created internal ticket(s) MAGETWO-71918  to track progress on the issue.

**Comment by bka** [comment]
I was not able to reproduce this one on 2.2-develop

**Comment by okorshenko** [comment]
### Updated Steps to Reproduce:

*Preconditions:*
* Install Magento 2 CE

*Steps to reproduce:*
* Go to *Products* -> *Catalog*  -> Create new Simple product
* Fill next data
** Name - Simple
** Sku - Simple
** Price - 100
** Advanced pricing:
*** Special price - 50
*** Special price from - click go Today button
*** (!) Do not fill the field Special price to
** qty - 1000
** Category - cat
* Save product
* Open product on edit
* Change *Special price To* field, click *Go today Button*
* Save the product

(/) *Expected result:*
* Product *Special price To* field is saved and applied.

(x) *Actual result:*
* Product *Special price To* field is not saved and applied. Field is empty

(!) *Note:*  
* If you fill  not Today's date in the *Special price To* field so it be saved, then if you save *Today's date* it be saved again

**Comment by bka** [comment]
I cannot find any issue here, or I don't get the expected behaviour. If I leave **Special price to** _empty_ what should be saved? I think it could be valid to leave this field empty, or otherwise make it a required field. Special price is also applied if I create a special price from todays date and leave **Special price to** empty, to me everything looks valid on 2.2-dev

![auswahl_036](https://user-images.githubusercontent.com/584644/31011517-e0ea7dce-a50e-11e7-9d0a-931b0f62c220.png)
![auswahl_037](https://user-images.githubusercontent.com/584644/31011508-d9545d96-a50e-11e7-9e18-40f52e66575a.png)

**Comment by okorshenko** [comment]
@Olek89 could you please confirm that the issue still exists?

**Comment by okorshenko** [comment]
@bka thank you for investigation

**Comment by Olek89** [comment]
@okorshenko yes stil exist at 2.1.9

**Comment by okorshenko** [comment]
Hi @Olek89 the issue already fixed in 2.2.0
MAGETWO-71918 is created to backport the issues into 2.1-develop branch

**Comment by maqlec** [comment]
Hi guys last comment from @magento-engcom-team looks like its done in 2.1 but It's not. Please mark this issue right.
