### ISSUE TITLE
Magento 2.1.8 backend openVideoModal.js not found > error 404

### ISSUE THREAD

**Issue by roman204** [magento/magento2#10612]
### Preconditions

1. Magento Version 2.1.8
2. static-content language de_DE

### Steps to reproduce

1. Install Magento 2.1.8
2. login to backend
3. go to product-edit page
4. open images tab 
5. open console of your browser

### Expected result

1. video-modal.js should be loaded

### Actual result

1. in require-config.js line 10 the openVideoModal is defined with a path to a js file
```
var config = {
    map: {
        '*': {
            newVideoDialog:  'Magento_ProductVideo/js/new-video-dialog',
            openVideoModal:  'Magento_ProductVideo/js/video-modal'
        }
    }
};
```
browser want to load a file with name openVideoModal.js which does not exist
![image](https://user-images.githubusercontent.com/584168/29557145-6bf3b642-8728-11e7-9906-5be0a645af82.png)

**Comment by orlangur** [comment]
> Magento_ProductVideo/js/video-modal

What Network tab says about this file loading?

**Comment by roman204** [comment]
![image](https://user-images.githubusercontent.com/584168/29559844-7f75ba64-8730-11e7-9130-c6d02b9dfcaf.png)

**Comment by roman204** [comment]
the js file is correct deployed via static-content:deploy

the path http://www.domain.local/static/adminhtml/Magento/backend/de_DE/Magento_ProductVideo/js/video-modal.js return a status 200

**Comment by korostii** [comment]
Ah so it attempts to access the wrong path. Looks like the require-config.js didn't get included for whatever reason.

**Comment by roman204** [comment]
yes the configuration from the module's requirejs-config.js is not in the deployed requirejs-config.js. I am trying to debug right now.

**Comment by roman204** [comment]
found the error
![image](https://user-images.githubusercontent.com/584168/29564667-18117544-8743-11e7-9bfd-c469009b1908.png)
module output was disabled, but should that result in errors?

**Comment by orlangur** [comment]
Yeah, surely, as it ignores all layout instructions and, as you see, JavaScript files as well.

Just activate output for all modules and forget about `Disable Module Output` poor legacy Magento 1 feature as it was deprecated in 2.2 :wink:

**Comment by korostii** [comment]
I'd say that having a weird error blow up in your face after slightly adjusting functionality using stock admin options is definitely a bug. 
You can call it low-priority or P4 or whatever, but it's still a bug.

But yes, I've also read somewhere that there are plans to remove the "disable module output" functionality completely in the future versions.
@roman204 Have you tried disabling the module via `php -f bin/magento module:disable Magento_ProductVideo` instead?

**Comment by orlangur** [comment]
> using stock admin options is definitely a bug

It was ALWAYS buggy. Just because it is poorly designed to be buggy due to tons of `if (isModuleOutputDisabled(...))`.

Feature works as intended: if module output is disabled, no need to load its `*.js` files. It's just `Magento_ProductVideo` module or static files materialization implementation didn't take such a cool feature into account.

Nothing to fix here as of https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/Manager.php#L78

**Comment by korostii** [comment]
> Nothing to fix here

Are you saying `2.1.x` branch should be denied the luxury of bugfixing completely or what?

Unless you provide a reasonable workaround (and last time I checked, it's not recommended to use a release candidate in production), this is still an issue. Just like the other issues ignored with that boilerplate "fixed on branch `develop`" response.

**Comment by orlangur** [comment]
Yes, deprecated in `2.2.x` functionality definitely shall not be improved in `2.1.x`.

This is not an issue as it is encouraged to simply not use `Disable Module Output` functionality. The one who uses it should understand the risks.

**Comment by roman204** [comment]
so we can close it
