### ISSUE TITLE
Magento 2.2 rc 2.1 doesn't work after installation

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#10613]
### Preconditions

1. Magento 2.2.0-rc2.1. I tried to downlaod from github and from [repo](https://repo.magento.com/) with helpof composer
2. `PHP 7.0.22-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-2+ubuntu16.04.1+deb.sury.org+4, Copyright (c) 1999-2017, by Zend Technologies
`
3. `Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-07-27T14:34:01
`

4. `
+-------------------------+
| version()               |
+-------------------------+
| 5.7.19-0ubuntu0.16.04.1 |
+-------------------------+
`

### Steps to reproduce

1. Download magento src from github
2. Start setup via webWizard.
3. Check requirements passed (button on first page on wizard)
4. Go ahea and receive 'Success' message
5. Open store page
6. Open admin page

Also i tried:
1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2`
2. receive message: `Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Writing lock file
Generating autoload files
`
3. Install from command line
4. receive message: `[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin_isq95k
`
5. Open store page
6. Open admin page

### Expected result

1. Correct store page
2. Correct admin page

### Actual result

1. 404 instead of admin page
2. Page without styles, links and menu doesn'r work instead of store page.
![virtualbox_2017-08-22_15-35-19](https://user-images.githubusercontent.com/4807486/29565674-9258316a-874f-11e7-9b36-86c653292ce2.png)

![virtualbox_2017-08-22_15-33-47](https://user-images.githubusercontent.com/4807486/29565650-7ad1047c-874f-11e7-8bd3-d436b504640f.png)
![virtualbox_2017-08-22_15-35-53](https://user-images.githubusercontent.com/4807486/29565688-a42b2b40-874f-11e7-886e-c1d41513d031.png)

for me it looks similar to [this](https://github.com/magento/magento2/issues/2309)

**Comment by mrkhoa99** [comment]
First of all, don't use `localhost` as the top level domain. Try to use another domain like `mage217.loc`, `mysite.loc`, etc.

Second, the layout broken, we need to run static deploy command.

Third, check your web server mode rewrite. We can add `index.php` to the url, for example: `localhost/magento2-2-0-2-1/index.php/admin_`

**Comment by misha-kotov** [comment]
@MaximKitsenko  did the suggestions resolve the issue?

**Comment by serblama** [comment]
I have exactly the same problem.
I can't not find the problem. 
I have debian with apache2

**Comment by misha-kotov** [comment]
@serblama did you try the suggestions listed above?

**Comment by serblama** [comment]
yes, but the second option, I don't understand what do you mean with deploy command

**Comment by misha-kotov** [comment]
Read about it [here](http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.html).
CLI command: `magento setup:static-content:deploy`

Are you running in default mode? 
CLI command to check: `magento deploy:mode:show`

**Comment by kolarix** [comment]
The solution for this is to add this in the default apache2 server config (/etc/apache2/sites-available/000-default.conf).

`<Directory "/var/www/html">
	AllowOverride  All
</Directory>`

**Comment by magento-engcom-team** [comment]
@Stike999 thank you for suggestion
