### ISSUE TITLE
Different class names causes crash

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#1061]
This error message is for Magento 1.7 but the code is for all new versions including Magento2 the same:

Recoverable Error: Argument 1 passed to Mage_Eav_Model_Attribute_Data::factory() must be an instance of Mage_Eav_Model_Attribute, instance of Mage_Eav_Model_Entity_Attribute given, called in app/code/core/Mage/Eav/Model/Form.php on line 327 and defined  in app/code/core/Mage/Eav/Model/Attribute/Data.php on line 59

Snippets are from 1.7:

app/code/core/Mage/Eav/Model/Form.php Line 327

```
    protected function _getAttributeDataModel(Mage_Eav_Model_Entity_Attribute $attribute)
    {
        $dataModel = Mage_Eav_Model_Attribute_Data::factory($attribute, $this->getEntity());
        $dataModel->setIsAjaxRequest($this->getIsAjaxRequest());

        return $dataModel;
    }
```

And `Mage_Eav_Model_Attribute_Data`:

```
public static function factory(Mage_Eav_Model_Attribute $attribute, Mage_Core_Model_Abstract $entity)
    {
    }
```

Which is now the correct class name `Mage_Eav_Model_Entity_Attribute` or `Mage_Eav_Model_Attribute`?

**Comment by vpelipenko** [comment]
@SchumacherFM, how can we get this error?

**Comment by SchumacherFM** [comment]
Sorry. I've encountered this when saving a customer in the backend to apply to the customer a new password.

**Comment by vpelipenko** [comment]
@SchumacherFM, I've tried to do the same in Magento1 1.7 and it works without any errors. Also In Magento2 it is not possible to change password to customer, it can be only reset by sending email. So any other details about this issue are welcome.

**Comment by SchumacherFM** [comment]
I'm closing this. Maybe it only relates to older PHP versions....
