### ISSUE TITLE
Track Order Link not working

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#10629]
### Preconditions

1.  Click on "Track Order" link on order Admin page

### Expected result

1.  Should display carrier and tracking number

### Actual result

1.  Only order number is displayed - view screenshots

![track order](https://user-images.githubusercontent.com/10808588/29604241-3a6e6cea-882a-11e7-9227-70334a92e945.jpg)

![track order 2](https://user-images.githubusercontent.com/10808588/29604278-5a7f86fe-882a-11e7-90f5-3e0e8066611d.jpg)

**Comment by YevSent** [comment]
Hi, @bondimedical3, please, provide a version of Magento, used shipping carrier, debug (should be enabled for a selected shipping carrier) and exception logs.

**Comment by bondimedical3** [comment]
Magento 2.1.8 on Production mode.
"Custom Value" was selected

**Comment by andidhouse** [comment]
I can confirm this on a magento 2.1.7 system. 
Maybe it would help if the magento2 team would publish the file which can be adapted here.

**Comment by YevSent** [comment]
This issue already fixed on the develop branch but doesn't have a backport for 2.1.x version.
Closed as duplicated to https://github.com/magento/magento2/issues/10066 (the fix solves problems for FedEx and custom tracking numbers).
