### ISSUE TITLE
Thumbnail Image Role Missing 

### ISSUE THREAD

**Issue by nishantbkw** [magento/magento2#10621]
I a

  | I am trying to figure out where to debug this missing thumbnail role issue 
![guinness created like no other wetstop runner products inventory products magento admin](https://user-images.githubusercontent.com/11628633/29580617-3a1c55a4-8794-11e7-952f-ddcfb8516265.png)
in Magento 2 back-end
-- | --

**Comment by vherasymenko** [comment]
@nishantbkw TandyCorp hank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by orlangur** [comment]
Closing in favor of https://github.com/magento/magento2/issues/10642. @nishantbkw, next time please just edit existing issue instead of reporting a new one.
