### ISSUE TITLE
During save first customer address Magento 2 does not save customer_address_id for shipping address in quote_address table

### ISSUE THREAD

**Issue by sichensol** [magento/magento2#10632]
### Preconditions
1. Found in Magento 2.1.3 and still reproduced in 2.1.7 
2. PHP: 7.0.18
3. RDBMS: MariaDB 10.1.21
4. Magento version with sample data

### Steps to reproduce
1. Go to front of site and create new customer
2. Go to customer account, push down manage addresses and add new address 
3. Check that billing and shipping addresses were set automatically
4. Go to admin panel and enable multishipping
5. Go front of site and got to catalog, buy some products
6. Go to cart and go to multishipping page
7. Go to shipping information
8. Try edit shipping address by click on "change" link

### Expected result
1. You should be able to edit existed shipping address

### Actual result
1. You get empty form, and after fill data, you get new address created

![screenshot-m2cesd magento2 local-2017-08-23-12-28-52](https://user-images.githubusercontent.com/14057429/29609126-e7375d46-87fe-11e7-9156-fca63afc7d83.png)

This is happening due Magento 2 does not save customer_address_id in the quote_address table for shipping address during saving new address. And on the shipping step, Magento 2 can't get actual an address id to edit this.

**Comment by marcinfr** [comment]
For me it works correctly, cant reproduce.

**Comment by magento-engcom-team** [comment]
@molneek, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by nuovecode** [comment]
Same for me in 2.1.9
