### ISSUE TITLE
Product save displays wrong SKU after error while saving

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#10637]
### Preconditions
1. Install clean version of Magento 2.1.8

### Steps to reproduce
1. Create a new product where the name of the product is different from the SKU. See my screenshot as an example.
2. Make sure that saving the product creates an error, for instance use an URL key which is already in use by another product.
3. After saving the SKU that is displayed is suddenly changed to the name of the product.
4. Issue only occurs when saving of the product goes wrong, otherwise SKU is correctly saved and retrieved again.

### Expected result
1. The displayed SKU should not change from the one you entered. It should stay the same. 

### Actual result
1. The SKU is different then the one entered and is the same as the name of the product.

Screenshot of settings before saving:
![image](https://user-images.githubusercontent.com/1058480/29618652-2cf7e87c-8819-11e7-82fd-694ebce5a9b0.png)

Screenshot of settings after saving, SKU has changed: 
![image](https://user-images.githubusercontent.com/1058480/29618863-be7a9a06-8819-11e7-87dc-2f47af1e0168.png)

**Comment by magento-engcom-team** [comment]
@dverkade Thank you for your submission. 
Unfortuanlly, the issue you described is standart feature. 
If you want to make Feature Requests and Improvements, please submit them to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by dverkade** [comment]
@magento-engcom-team could you describe the standard feature? This issue describes changing the SKU value after a product save. I don't think this is a standard feature and it should not be possible that a SKU entered by the user suddenly changes without notification of this change. Please reproduce this issue with the steps mentioned in above and checkout the screenshots to see what exactly goes wrong here. If you like I can to a screendump / screenshare as well.

**Comment by korostii** [comment]
@magento-engcom-team calling some wrong behavior "standard" doesn't make it right.

This is clearly a bug report, not a feature request. This issue needs to be reopened.
