### ISSUE TITLE
Browser cache not invalidated after configurable product is back in stock

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#10646]
### Preconditions
1. Magento2.1.8 via download, Varnish, redis, nginx

### Steps to reproduce

1. One or more simple products belonging to a configurable products are out of stock
2. Qty of these products is changed (for example via import or external ERP system etc.) 

### Expected result

1. The browser cache of the configurable product is invalidated - so the simple products are back in stock again

### Actual result

1. If the configurable product is visited before by a user the browser has cached the site - and on the next visit the cached site is shown again, with the out of stock products which is wrong.
If the site is reloaded via the browser icon (page reload) the products are shown right as in stock.

For me it seems that magento does not invalidate the browser cache in this case which is crucial as in stock products are shown as out of stock.

**Comment by misha-kotov** [comment]
I believe this one is related, if not duplicate, of your issue: https://github.com/magento/magento2/issues/8009

What are you actually using for cache in your case - varnish or redis?

**Comment by magento-engcom-team** [comment]
Unfortunately, I could not reproduce the issue as you described it. Please provide more information on this issue.

**Comment by magento-engcom-team** [comment]
@andidhouse, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
