### ISSUE TITLE
Magento 2 : Thumbnail Role Missing In Product EDIT page admin 

### ISSUE THREAD

**Issue by nishantbkw** [magento/magento2#10642]
Update : Now Upgraded to 2.1.8 before it was 2.1.1 
### Preconditions
1. Magento 2 version 2.1.8

## ISSUE 
I am trying to figure out why thumbnail role suddenly missing when i try to edit a product from admin and want to change thumbnail image also for new products thumbnail role not showing please see attached image

### Steps to reproduce

1. From Magento 2 admin go to products->catalog try to edit any product 
2. Click Images and Videos Tab 
3. Select any image which i want to assign as thumbnail image a popup appears with roles but thumbnail role is not here also same happens for add new product see attached image for details 

### Expected result

1.  In the Popup Roles section thumbnail role should appear as it used to show here but suddenly stopped showing for unknown reason

### Actual result

1. Thumbnail Role Is Missing It used to be here before 
![guinness small wetstop runner products inventory products magento admin 1](https://user-images.githubusercontent.com/11628633/29660894-1a1d5d46-88e0-11e7-92ad-060883d93854.png)

**Comment by orlangur** [comment]
`2.1.1` is quite old, can you reproduce this issue on latest stable `2.1.8` version?

**Comment by nishantbkw** [comment]
Ok , now i upgraded to latest version 2.1.8 but it does not fixed the issue please assist me 
thank you

**Comment by nishantbkw** [comment]
Solved!
the Attribute "thumbnail" was not assigned to "Default" attribute set now i manually assigned it through backend and it started appearing in Role section.
Not sure how it suddenly unassigned from Default attribute set
