### ISSUE TITLE
Product View Stars on Catalog Grid Widget

### ISSUE THREAD

**Issue by coatesjonathan** [magento/magento2#10654]
### Precondtions
Magento 2.1.7

### Steps to reproduce
The product review stars do not show up on Catalog Widget grid.phtml
you can find this in /vendor/magento/module-catalog-widget/view/frontend/templates/product/widget/content/grid.phtml

### Expected result

1. The review stars should appear when reviews show on products

### Actual result

1. no review stars appear

**Comment by TomashKhamlai** [comment]
Hello, @coatesjonathan! Thank you for your report. Can you add the steps that you have performed to enable the review stars?
Please, add **Steps to Reproduce** section of the issue and use the issue reporting guidelines to report an issue. Include the steps required to reproduce, and attach the screenshot of the page where you expect that stars should appear.

| Example 1  | Example 2 |
| ------------- | ------------- |
| ![screenshot1](https://user-images.githubusercontent.com/11827230/30017270-3ab45912-90f4-11e7-9db5-cbbd4972c68c.png) | ![screenshot2](https://user-images.githubusercontent.com/11827230/30017269-3aaa1d76-90f4-11e7-9cd5-7b40c2923d96.png)
 |

**Comment by TomashKhamlai** [comment]
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
