### ISSUE TITLE
Exception #0 (LogicException): Front controller reached 100 router match iterations

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#10659]
I am facing this error in admin url. Magento 2.1.7

I could not find any viable solution it simple appeared out of the blue when I try to access the admin url.
mysql user:root  host:localhost
> SHOW GRANTS FOR CURRENT_USER();

OUTPUT:

> # Grants for root@localhost
> 'GRANT ALL PRIVILEGES ON *.* TO \'root\'@\'localhost\' WITH GRANT OPTION'
> 'GRANT PROXY ON \'\'@\'\' TO \'root\'@\'localhost\' WITH GRANT OPTION'

Now in CLI when I run: 

> php bin/magento setup:upgrade

Is a different error from the admin url:

> [Magento\Setup\Exception]                                                                                                                                                                             
>   Database user does not have enough privileges. Please make sure SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, View, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, S  
>   HOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER privileges are granted to table 'dev'.

Table ? **privileges are granted to table 'dev'.**

 I don't have a table called **dev** my database name is called 

> dev

I need some help and answer please what could have happened as I have been working with magento for the past year I've never experience so many error and relentless problems with such and on any other platform.

Your help is mostly appreciated .
Thank you.
Juliano.

**Comment by magento-engcom-team** [comment]
@lano-vargas please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.

**Comment by lano-vargas** [comment]
@magento-engcom-team.
Hi Thank's for your reply.
The community are really  help full but I have had no luck here or  there ref:https://magento.stackexchange.com/questions/190582/magetno-2-admin-front-controller-reached-100-router-match-iterations .

This seen to be very technical to me and I am not alone ref:
https://magento.stackexchange.com/questions/135532/magento-2-ce-front-controller-reached-100-router-match-iterations-issue
https://github.com/convenient/magento-ce-ee-config-corruption-bug#the-fix
