### ISSUE TITLE
question template

### ISSUE THREAD

**Issue by Antonioele** [magento/magento2#1065]
in  magento2/app/design/frontend/Magento/luma/Magento_Catalog/layout/catalog_product_view.xml
I found 
<page layout="1column  and 

 when I visualize
<body class="page-with-filter page-products categorypath-men-bottoms-men-pants-men category-pants-men catalog-category-view page-layout-2columns-left" data-mage-init="{"loaderAjax": {}, "loader": { "icon": "http://magento2.dev/pub/static/frontend/Magento/luma/it_IT/images/loader-2.gif"}}" data-container="body">

definitely make a mistake

**Comment by Antonioele** [comment]
in magento2/app/design/frontend/Magento/luma/Magento_Catalog/layout/catalog_product_view.xml
I found
<page layout="1column and

when I visualize I found
page-layout-2colums-left

definitely make a mistake

**Comment by villageseo** [comment]
Hi Antonioele! 

If I understood properly, you should use <page layout="2columns-left"  for correct layout changes for this file.

**Comment by Antonioele** [comment]
Hi @villageseo! villaseseo, I would like change layout 1 column  page of category product.
 in module app/catalog/view/frontend/layout/catalog_category_view  <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd"> not change.
I ovverride  this layout in my template vendor/theme/Magento_Catalog/override/layout/catalog_product_view.xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">
 not change 
When Ivisualize whith firebug in body I found 
body Class page-layout-2colums-left

**Comment by villageseo** [comment]
Antonioele, did you clean /var folder after updating catalog_product_view.xml ?

**Comment by versedi** [comment]
@villageseo by using the occasion...is there anyway to develop theme without having to delete files corresponding to theme in /var/....? (i.e. some theme development mode where files are refreshed every page visit).

**Comment by villageseo** [comment]
Hi @versedi! 

For now there is no theme development mode or other solution except deleting files manually/using task runner.  

Thank you, 
Oleg

**Comment by vpelipenko** [comment]
@Antonioele, did you have a chance to try @villageseo's suggestion?

**Comment by vpelipenko** [comment]
@Antonioele, we close this issue due to no response from your side. If you have other concerns, questions or suggestions, please, feel free to post new issues.
