### ISSUE TITLE
2.1.8: Product repository save and 'admin' store

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#10653]
I set 'admin' store ('default' works as expected) using Store Manager then l load product by SKU. Product object contains ~88 attributes in $_data array. Then I save product using Product Repository and load product again. Product object contains ~41 attributes only in $_data array. 

            /** @var \Magento\Store\Model\StoreManagerInterface */
            $this->manStore->setCurrentStore('admin');
            /** @var \Magento\Catalog\Api\ProductRepositoryInterface */
            $found = $this->repoProd->get($sku, true);
            $countFound = count($found->getData()); // $countFound = 88
            $this->repoProd->save($found);
            $saved = $this->repoProd->get($sku, true);
            $countSaved = count($saved->getData()); // $countSaved = 41

Yes, some attributes (including 'image', 'small_image', 'thumbnail', 'swatch_image') are removed on save from all stores. I expect either 88 attrs after save (if 88 are loaded) or 41 attrs on load for admin store.

This behavior is appeared after upgrade to 2.1.8.

**Comment by TomashKhamlai** [comment]
Thank you for your report. Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by flancer64** [comment]
Before creating an issue, please do the following:
- Check the [documentation](http://devdocs.magento.com/) to make sure the behavior you are reporting is really a bug, not a feature.

You win, guys. I agree - this is a feature.
