### ISSUE TITLE
2.1.7 - Checkout loader is not removed after page load using empty theme

### ISSUE THREAD

**Issue by minlare** [magento/magento2#10662]
### Preconditions

1. Magento CE 2.1.7 without sample data is installed.
2. Create and set "empty" theme (without parent fallback)

### Steps to reproduce

1. Go to checkout with product in cart

### Expected result

1. Checkout loading icon should be removed from DOM
2. `hideLoader()` should be called in file `vendor/magento/module-checkout/view/frontend/web/js/checkout-loader.js` 

### Actual result

1. Div id `#checkout-loader` does not get removed after checkout loads

![checkout-loading-bug](https://user-images.githubusercontent.com/1862882/29720023-666bf704-89b0-11e7-8f08-ea5be5215f6b.png)

`init()` is called with the correct div and config but `hideLoader()` is never called in file `vendor/magento/module-checkout/view/frontend/web/js/checkout-loader.js`  

**Switching theme to "Magento Blank Theme" or "Magento Luma Theme" fixes the problem.**

**Comment by magento-engcom-team** [comment]
@minlare , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.

**Comment by RahulBhut21** [comment]
Magento 2.2.2 issue Checkout loader is not removed after page load using LUMA
![screenshot 5](https://user-images.githubusercontent.com/31387311/35468617-e1147ace-0347-11e8-8974-dccdf8bc38dd.png)
 theme

**Comment by cedricziel** [comment]
The problem persists with 2.2.2, when an adblocker is active. The problem disappears if it's off.

I applied the patch from https://github.com/magento/magento2/pull/13061 but no changes to the ui behaviour. It seems the code from checkout-loader.js is not called at ll.

**Comment by afourmeaux** [comment]
@magento-engcom-team can you tell us what's the fix applied, so that we can apply it without upgrading in 2.2.2 ? Because, for us, all our internet explorer 11 users can't order anything because of that.

And that be great if, for every issue resolved, you could link the pull request that concern it, so that the people that can patch their version are not stuck with a bugged version. Thanks.

**Comment by useapp** [comment]
I also have this BUG, in IE loader is not removed after page load 
how to fix this in magento 2.1.11 ?
