### ISSUE TITLE
[2.2.0-RC 2.1] Can not install B2B extensions via composer

### ISSUE THREAD

**Issue by toddwolaver** [magento/magento2#10666]
### Description
As indicated via the dev docs (http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html) RC B2B modules should be installable via composer. However, the modules do not appear to be available.

### Preconditions
1.  PHP 7.0.15 (cli)
2. Composer version 1.5.1

### Steps to reproduce
1. Create a new enterprise project via composer
    1. `composer create-project -s RC --repository-url=https://repo.magento.com/ magento/project-enterprise-edition magento-220-rc21 2.2.0-rc21`
2. After successful download of project-enterprise-edition, run command to install B2B modules, per documentation 
    1.  `cd magento-220-rc21`
    2.  `composer require magento/extension-b2b`
3.  Attempt to install using the name in the B2B module composer.json file: `"name": "magento/module-b2b",`
    1.  `composer require magento/module-b2b`
3.  Attempt to install B2B Shared Catalog
    1.  `composer require magento/module-shared-catalog`

### Expected result
1. Installation of B2B modules 

### Actual result
1. Error on magento/extension-b2b:
    1. `[InvalidArgumentException] Could not find package magento/extension-b2b at any version for your minimum-stability (RC). Check the package spelling or your minimum-stability`
2. Error on magento/module-b2b:
    1. `[InvalidArgumentException] Could not find package magento/module-b2b at any version for your minimum-stability (RC). Check the package spelling or your minimum-stability`
3. Error on magento/module-shared-catalog
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/module-shared-catalog 100.0.0-rc21 requires magento/module-b2b 100.0.* -> no matching package found.
    - magento/module-shared-catalog 100.0.0-rc20 requires magento/module-b2b 100.0.* -> no matching package found.
    - Installation request for magento/module-shared-catalog ^100.0@RC -> satisfiable by magento/module-shared-catalog[100.0.0-rc20, 100.0.0-rc21].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by misha-kotov** [comment]
Hi @toddwolaver can you try again with RC22 packages? There were some packaging issues we worked out last week. If that doesn't work there could be a potential issue with your keys.

**Comment by mbrinton01** [comment]
@toddwolaver let us know the outcome. If it doesn't work now, we may need to provision your keys for this access.

**Comment by misha-kotov** [comment]
Also your command statement should specify the version of the composer package (notice the `=` in the following): 
`create-project -s RC --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.2.0-rc22` and
`composer require magento/extension-b2b=1.0.0-rc22`
Not sure if it's anything, but could be something. Thanks!

**Comment by toddwolaver** [comment]
@mbrinton01, thanks for the feedback, however the results are the same on RC22. Can you point me to how we can have our keys provisioned. The RC Software agreement has already been signed.

**magento/extension-b2b**
` Could not find package magento/extension-b2b at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability  
`

**magento/module-b2b**
`
Could not find package magento/module-b2b at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability`

**magento/module-shared-catalog**
```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/module-shared-catalog 100.0.0-rc22 requires magento/module-b2b 100.0.* -> no matching package found.
    - magento/module-shared-catalog 100.0.0-rc21 requires magento/module-b2b 100.0.* -> no matching package found.
    - magento/module-shared-catalog 100.0.0-rc20 requires magento/module-b2b 100.0.* -> no matching package found.
    - Installation request for magento/module-shared-catalog ^100.0@RC -> satisfiable by magento/module-shared-catalog[100.0.0-rc20, 100.0.0-rc21, 100.0.0-rc22].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by misha-kotov** [comment]
Hi @toddwolaver - looks like a temporary issue on our side. Please reach out to Mark at mbrinton@magento.com to request access to our pre-release Composer repositories. We've added instructions in our [devdocs](http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html) as well in case other people run into the same.

**Comment by toddwolaver** [comment]
@misha-kotov, thank you for the followup. Mark was able to facilitate a resolution and provisioning of keys. This is no longer an issue for us.

**Comment by mbrinton01** [comment]
@toddwolaver glad it's working now.

**Comment by josefbehr** [comment]
Got the same situation:
➜  magento22 composer search extension-b2b
➜  magento22 composer require magento/extension-b2b=1.1.0-rc30
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/extension-b2b could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
➜  magento22 composer require magento/extension-b2b           

                                                                                                                                                     
  [InvalidArgumentException]                                                                                                                         
  Could not find package magento/extension-b2b at any version for your minimum-stability (RC). Check the package spelling or your minimum-stability

**Comment by mbrinton01** [comment]
Please send me a message as described here: http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html

**Comment by mpchadwick** [comment]
This is happening to me. In my case I downloaded the tar from Magento.com and unzipped. Then when I tried to install the b2b module I got the error.

```
$ composer require magento/extension-b2b

  [InvalidArgumentException]
  Could not find package magento/extension-b2b at any version for your minimum-stability (stable). Check the package
  spelling or your minimum-stability
```

**Comment by mbrinton01** [comment]
@mpchadwick please email me directly and I can help you resolve this.

**Comment by pardco** [comment]
@mbrinton01 I have the same problem

**Comment by keharper** [comment]
@pardco Make sure there's no extraneous spaces before or after your auth keys. I'm not sure if this will fix your problem, but others have encountered the error @mpchadwick reported.

**Comment by xpoback** [comment]
I'm getting the same issue in Magento Commerce 2.2.1. 
There are no spaces in the auth keys, I've checked that a million times
```
$ composer require magento/extension-b2b 
                                                                                                                                                        
  [InvalidArgumentException]                                                                                                                            
  Could not find package magento/extension-b2b at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability 
```
Adding a `require` to composer.json and running `composer update` gives no result as well.

**Comment by imransheik** [comment]
This is happening to me as well, like the case mentioned by @mpchadwick, I have also downloaded the 
tar from Magento.com and unzipped. Then when I tried to install the b2b module I got the error.

@mbrinton01 Can you please let us know the soultion for this if you have.
$ composer require magento/extension-b2b

  ```
[InvalidArgumentException]
  Could not find package magento/extension-b2b at any version for your minimum-stability (stable). Check the package
  spelling or your minimum-stability
```

**Comment by giacomoleopardi** [comment]
I'm getting the same error in Magento Commerce 2.2.0.
```
$ composer require magento/extension-b2b 
                                                                                                                                                        
  [InvalidArgumentException]                                                                                                                            
  Could not find package magento/extension-b2b at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 
```

```
$ composer require magento/module-b2b 
                                                                                                                                                        
  [InvalidArgumentException]                                                                                                                            
  Could not find package magento/module-b2b at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 

```

This is my composer.json:

```
{
    "name": "magento/project-enterprise-edition",
    "description": "eCommerce Platform for Growth (Enterprise Edition)",
    "type": "project",
    "version": "2.2.0",
    "license": [
        "proprietary"
    ],
    "require": {
        "magento/product-enterprise-edition": "2.2.0",
        "composer/composer": "@alpha",
        "faonni/module-product-most-ordered": "^2.1"
    },
    "require-dev": {
        "phpunit/phpunit": "~6.2.0",
        "squizlabs/php_codesniffer": "3.0.1",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.5.0",
        "sjparkinson/static-review": "~4.1",
        "friendsofphp/php-cs-fixer": "~2.1.1",
        "lusitanian/oauth": "~0.8.10",
        "sebastian/phpcpd": "2.0.4"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\ToolkitFramework\\": "dev/tools/performance-toolkit/framework/Magento/ToolkitFramework/"
        }
    },
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

**Comment by mbrinton01** [comment]
For any partners still experiencing this issue, please submit a support request for resolution. Now that B2B has been released in 2.2.0, this is the correct channel for assistance.

**Comment by webds** [comment]
Magento2   v2.2.3

 [InvalidArgumentException]
  Could not find a matching version of package magento/extension-b2b. Check t
  he package spelling, your version constraint and that the package is availa
  ble in a stability which matches your minimum-stability (stable).

**Comment by arijit-de93** [comment]
I am facing the same problem. Is there any update on this?

**Comment by devendra1991** [comment]
instead of running require command specify package name in composer.json file.
 "require": {
        "magento/product-enterprise-edition": "2.2.2",
        "composer/composer": "@alpha",
        "gene/bluefoot": "^1.0",
       ........
       ........
	"magento/mcom-connector": "2.0.9",
	"magento/module-catalog-permissions": "100.2.1",
	"magento/extension-b2b": "^1.0"
    },

also, verify the repository URL
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],

don't forget to put forword slash.

Clear composer cache 
`composer clear-cache`
then re-execute 
`composer update`  command

hope it will help

**Comment by biplab-r** [comment]
Make sure the public and private key used is a valid account using which the Magento Commerce package was downloaded. As normal account credentials won't work.

**Comment by kazim-krish** [comment]
I have got a solution which worked for me.

1. If you get an error when trying to install the B2B module for a local instance of Magento Commerce (for example: `[InvalidArgumentException] Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).`), you need to create an `auth.json` file in the Magento root directory and add the following code, using the actual values of your `public_key` and `private_key` for `username` and `password`:

2. Create `auth.json` file like 
`{
   "http-basic": {
      "repo.magento.com": {
         "username": "<public_key>",
         "password": "<private_key>"
      }
   }
}`

3. Execute `composer require magento/extension-b2b=^1.0`

4. Execute `composer update`

5. Run Magento commands
````
bin/magento setup:upgrade

bin/magento setup:di:compile

bin/magento setup:static-content:deploy -f

bin/magento cache:clean
````

**Comment by kazimnoorani** [comment]
I have got a solution which worked for me.

1. If you get an error when trying to install the B2B module for a local instance of Magento Commerce (for example: `[InvalidArgumentException] Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).`), you need to create an `auth.json` file in the Magento root directory and add the following code, using the actual values of your `public_key` and `private_key` for `username` and `password`:

2. Create `auth.json` file like 
````
{
   "http-basic": {
      "repo.magento.com": {
         "username": "<public_key>",
         "password": "<private_key>"
      }
   }
}
````

3. Execute `composer require magento/extension-b2b=^1.0`

4. Execute `composer update`

5. Run Magento commands
````
bin/magento setup:upgrade

bin/magento setup:di:compile

bin/magento setup:static-content:deploy -f

bin/magento cache:clean
````

**Comment by sreenulanka** [comment]
Magento 2 Cloud throwing error while trying to install b2b modules.

Error:
composer require  magento/extension-b2b
Using version ^1.1 for magento/extension-b2b            
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)           
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: magento/module-user[101.1.0, 101.0.1].
    - Can only install one of: magento/module-user[101.1.0, 101.0.1].
    - Can only install one of: magento/module-user[101.0.1, 101.1.0].
    - magento/module-shared-catalog 100.1.0 requires magento/module-user 101.1.0 -> satisfiable by magento/module-user[101.1.0].
    - magento/extension-b2b 1.1.0 requires magento/module-shared-catalog 100.1.0 -> satisfiable by magento/module-shared-catalog[100.1.0].
    - Installation request for magento/extension-b2b ^1.1 -> satisfiable by magento/extension-b2b[1.1.0].
    - Installation request for magento/module-user (locked at 101.0.1) -> satisfiable by magento/module-user[101.0.1]

Issue: 
Run composer update always look modules from compose cache
if we are trying to use multiple magento cloud versions. Magento 2.2.2 conflict with old b2b module versions and throw this error

SOlution:
composer clear-cache 
composer update
composer require magento/extension-b2b=^1.0
git add . & git commit -m "added b2b modules"
git push

**Comment by sdouma** [comment]
@sreenulanka seems so obvious thanks
