### ISSUE TITLE
Drop down menu bug for tablets

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#10678]
Cannot access subcategories on a parent category drop down menu on a tablet.

### Preconditions

1. If you try to open the menu you are simply navigated to the parent category page.

![screenshot_20170828-202626](https://user-images.githubusercontent.com/10808588/29770003-2952c28a-8c30-11e7-9508-213cbf8ab827.jpg)

**Comment by orlangur** [comment]
Closing in favor of more complete bug report https://github.com/magento/magento2/issues/10724, @bondimedical3 please simply edit issue next time.
