### ISSUE TITLE
Use Scrutinizer CI

### ISSUE THREAD

**Issue by navarr** [magento/magento2#1067]
In addition to Travis CI, investigate and setup Magento 2 on Scurtinizer CI for Code Quality Analysis.

http://scrutinizer-ci.com

Despite how well the pricing page hides it Scrutinizer CI is free for Open Source repositories.

**Comment by orlangur** [comment]
And all other fancy modern services, like [Code Climate](https://codeclimate.com/github/yiisoft/yii2), [Coveralls](https://coveralls.io/r/yiisoft/yii) and [SensioLabs Insight](https://insight.sensiolabs.com/projects/88aa66d1-82bb-4b4d-8b9a-0658211d06ed/analyses/5).

**Comment by vpelipenko** [comment]
@navarr, really do you see a lot of advantages in using Scrutinizer CI?

**Comment by navarr** [comment]
Biggest advantage may be better served by Coveralls - Code Coverage.

**Comment by vpelipenko** [comment]
@navarr, thanks for suggestions, but we don't have plans now for using something else besides Travis.
