### ISSUE TITLE
B2B Add new user: Issue while customzing Add new user form

### ISSUE THREAD

**Issue by yogisoni** [magento/magento2#10677]
Hello Magento Team, 

When we are trying to customize "Add New User" form(logged in as Company Administrator), we are facing an issue that when we are creating any checkbox on that new user popup the value is getting blank on the click on Add new user button. So this makes "Null" value to be passed on form post. This issue seems to be related to JS. Please look into it.

### Preconditions
1.  You have to edit file company/management/dialog/customer/add.phtml
2.  Add checkbox code in this file

### Steps to reproduce

1. edit add.phtml file which is used for generating add new user popup and add any checkbox on the page with some value in the checkbox option.
2. Logged in as company Administrator. 
3. Go to company users page. 
4. View source of the page and see you'll find the the value in checkbox. 5. Now click on add new user button and now see the same checkbox and this time you'll not see the value in checkbox option.

### Expected result

1. Checkbox option value should not get blank after click on Add new user button.

### Actual result
1. value get blank once we click on Add new user button.

**Comment by mbrinton01** [comment]
Internal ID MAGETWO-72084

**Comment by yogisoni** [comment]
Is there any update on this bug?

**Comment by yogisoni** [comment]
Is this issue resolved? I am not aware about the status G1 Passed.

**Comment by mbrinton01** [comment]
@yogisoni more information about G1,2,3 status is available here: https://github.com/magento/magento2/wiki/Magento-Issue-Gates

This issue has been fixed and will be part of the 2.2.0 release.

PR with fix here: https://github.com/magento/magento2b2b/pull/268
_Note: PR only visible to partners with B2B repo access_
