### ISSUE TITLE
Dynamic Price on Bundled Products

### ISSUE THREAD

**Issue by brandontamm** [magento/magento2#10684]
### Preconditions
1. Magento 2.1.8
2. PHP 7.0
3. Percona 5.7.18

### Steps to reproduce
1. Create Bundled Product
2. Set Dynamic Price to No

### Expected result
1. Should be able to set dynamic price back to yes

### Actual result
1. Cannot set dynamic price back to yes

**Comment by magento-engcom-team** [comment]
@brandontamm Unfortunally, it is not possible to enable "dynamic price" for Bundled product after you have saved it disabled once. If you wouls like to make Feature Requests for Improvements, you should  submit it on the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by magento-engcom-team** [comment]
@brandontamm, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by kkdg** [comment]
@magento-engcom-team , could you tell me the detailed explanation why once dynamic price status saved for a bundled product, can't change it later?

**Comment by taylorhgmailcom** [comment]
iI know this is a but I just manually corrected this issue in the database.  Here's what worked for me.
1) In your db admin, truck on down to the eav_attribute table. To get the numeric id of the Dynamic Pricing attribute run this sql:  
SELECT * FROM eav_attribute WHERE frontend_label = 'Dynamic Price';
*mine was 124, and that's what you'll see below

2) Now that we have our attribute_id let's query the db to return all products that have that attribute by running this sql statement: 
SELECT * FROM catalog_product_entity_int WHERE attribute_id = 124; 
( 124 being the attribute id you looked up. )

Here's how to change the status
To enable 'Dynamic Pricing' set the value to 0
To disable 'Dynamic Pricing' set the value to 1

--begin caps--
 <img width="690" alt="screen shot 2018-01-01 at 11 57 30 pm" src="https://user-images.githubusercontent.com/16979788/34475475-117ca998-ef52-11e7-86c2-026edfc99f34.png">
<img width="383" alt="screen shot 2018-01-02 at 12 15 53 am" src="https://user-images.githubusercontent.com/16979788/34475484-2cbb5bf0-ef52-11e7-8f53-5847354700b4.png">
![screen-shot-2018-01-01-at-11 56](https://user-images.githubusercontent.com/16979788/34475506-62ebce80-ef52-11e7-813e-0b44a1a6df00.jpg)

**Comment by bhargavsynoptek** [comment]
this is not working for me
