### ISSUE TITLE
2.1.8 : Cart Rules date is invalid format in French

### ISSUE THREAD

**Issue by LSERRE** [magento/magento2#10686]
### Preconditions

Magento CE 2.1.8
PHP 7.0.22
MySQL 5.6.35
French as admin language

### Steps to reproduce

1. Navigate to Marketing > Cart Rules
2. Select start date 28/08/17 with date picker
3. Select end date 28/08/17 with date picker

### Expected result

1. Date should be correct (In french format is dd/mm/yy)

### Actual result

1. Got error: Please enter a valid date.
![capture d ecran 2017-08-28 a 16 09 40](https://user-images.githubusercontent.com/6000768/29777192-6a296c84-8c0b-11e7-92be-ba4e80c45815.png)

**Comment by orlangur** [comment]
Looks like a duplicate of #10580 to me.

**Comment by magento-engcom-team** [comment]
Duplicate of #10005

**Comment by orlangur** [comment]
@magento-engcom-team please double-check issue number you referring to 😉

**Comment by magento-engcom-team** [comment]
Hi @LSERRE. Thank you for your report. 
The issue has been fixed in magento/magento2#11306 by @raumatbel in 2.3-develop branch
Related commit(s):
 - b237558168488b77309d69872bf2d517aa942d49

The fix will be available with the upcoming 2.3.0 release.
