### ISSUE TITLE
Double-commenting of license block in XML files

### ISSUE THREAD

**Issue by voleye** [magento/magento2#10680]
XML files has double-commenting of license block that does not has any sense.

### Preconditions
Magento 2.x

### Steps to reproduce
1. Go to, for example, https://github.com/magento/magento2/blob/develop/app/code/Magento/AdminNotification/view/adminhtml/layout/default.xml
2. See the license block

### Expected result
License block is located inside 
<img width="337" alt="screen shot 2017-08-28 at 2 58 46 pm" src="https://user-images.githubusercontent.com/2727670/29772471-a3d87e48-8c01-11e7-8409-89d4c77d404c.png">

### Actual result
License block is located inside 
<img width="351" alt="screen shot 2017-08-28 at 2 59 39 pm" src="https://user-images.githubusercontent.com/2727670/29772457-9b48c79c-8c01-11e7-9938-9493bc846ba5.png">

**Comment by orlangur** [comment]
Consistent license headers do have great sense in fact.

While most files are `*.php` and `*.js` where such syntax is natural for less frequent file types like `*.xml` or `*.less` there is no reason to scratch you head trying to guess the correct syntax. Asterisks are much more visible and thus you don't have to read the top of any files you open.

GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.
