### ISSUE TITLE
Product image roles randomly disappear

### ISSUE THREAD

**Issue by boxyman** [magento/magento2#10687]
After upgrading from Magento 2.1.7 to 2.1.8 we had problems with product image roles. We have experienced that some products that previously had product image role set to `base`, `small`, `thumbnail` didn't have it anymore. It seems that the image roles get's removed from random products over time. This weekend at we have at least identified 10 products that got images roles removed during the weekend.

### Preconditions
1. Magento 2.1.8
2. PHP 7
3. MySQL 5.7
4. Ubuntu 16.04
5. Nginx
6. Redis
7. Varnish
8. SSL (HTTPS)

### Steps to reproduce
1. Go to "Products" > "Catalog"
2. Choose a product
3. Go to "Images And Videos"
4. Click an image
5. Set "Role" to `base`, `small`, `thumbnail`

### Expected result
1. Product image roles should be set to `base`, `small`, `thumbnail` unless the user changes it.

### Actual result
1. Product image roles disappear randomly from some products from time to time.

### Preconditions
Create product with image and set role image: `base`, `small`, `thumbnail`
### Steps to reproduce
Save Product in backend controller like this:
```
$store = $this->storeManager->getStore(0);
$this->storeManager->setCurrentStore($store);
$product = $this->productRepository->getById($data['product_id'], true, $store->getId());
$this->productRepository->save($product);
```
### Expected result
Product image roles should be set to `base`, `small`, `thumbnail` unless the user changes it.
### Actual result
Product image does not have any roles

**Comment by kervin** [comment]
This is a big issue for us. Any news when this will be fixed?

**Comment by RomaKis** [comment]
@boxyman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
Please provide more details regarding your environment, or try to reproduce this
issue on a clean installation.

**Comment by kervin** [comment]
I think it's only when you save a product programmatically.

The problem that I found it when you set the current store to admin..

        // Set to Admin Store
        // When this is set, product images disappear
        // $store = $this->storeManager->getStore(0);
        // $this->storeManager->setCurrentStore($store->getCode());

**Comment by magento-engcom-team** [comment]
@kervin  Unfortunately, we could not reproduce the issue as you described it. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by kervin** [comment]
Just do the following on 2.1.8. If I do not set current store, it saves products to the default store view.. when I set the store, it breaks the images.

```

// This line is breaking images

$this->storeManager->setCurrentStore($store);

$product = $this->productRepository->getById($data['product_id'], true, $store->getId());

$this->productRepository->save($product);
```

**Comment by kervin** [comment]
I found a workaround, unset media_gallery, if you are not changing images.

```
$product->unsetData('media_gallery');
$this->productRepository->save($product);

```

**Comment by kervin** [comment]
The issue seems to be on configurable products

**Comment by tanghia** [comment]
I got the same issue with Magento 2.2.0. Some my customers have updated their websites from 2.1.8 to 2.2.0 and all custom extensions used $this->productRepository->save($product); will unset value of  image properties "base", "small" and "thumbnails" . We see placeholder images only!

$product->unsetData('media_gallery');
$this->productRepository->save($product);

Two lines of code are great to fix this issue, however, it can make a critical error on the catalog_product_view page.

1 exception(s):
Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /var/www/html/m220sampledata/vendor/magento/module-catalog/Block/Product/View/Gallery.php on line 114

This issue is the same with #10461 and it must be fixed quickly!

**Comment by jokeputs** [comment]
I have the same issue with Magento 2.1.9. In my installation it only happens when the product is saved in a cron task. If I run the same code using the cli tool the images keep their roles.

**Comment by magento-engcom-team** [comment]
@boxyman, thank you for your report.
We've created internal ticket(s) MAGETWO-83133 to track progress on the issue.

**Comment by boxyman** [comment]
@magento-engcom-team You are welcome. Great to know the the source of the issue from @kervin.

My very hackish temporary fix looks like this:

```
    public function connection()
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');

        return $resource->getConnection();
    }

    public function magento_add_product_image_roles()
    {
        $sql = "SELECT
            cpe.entity_id
        FROM
            catalog_product_entity AS cpe
        JOIN
            catalog_product_entity_int AS cpei
        ON
            cpei.entity_id = cpe.entity_id
        WHERE
            cpei.attribute_id = 99
        AND
            cpei.value = 4
        AND
            (
                SELECT
                    cpemg.attribute_id
                FROM
                    catalog_product_entity_media_gallery AS cpemg
                JOIN
                    catalog_product_entity_media_gallery_value_to_entity AS cpemgvte
                ON
                    cpemg.value_id = cpemgvte.value_id
                WHERE
                    cpemgvte.entity_id = cpe.entity_id
                GROUP BY
                    cpemg.attribute_id
            ) IS NOT NULL
        AND
            NOT EXISTS (
                SELECT
                    cpev.attribute_id
                FROM
                    catalog_product_entity_varchar AS cpev
                WHERE
                    cpev.entity_id = cpe.entity_id
                AND
                    cpev.attribute_id = 87
                AND
                    cpev.value != 'no_selection'
            )
        GROUP BY
            cpe.entity_id";

        $connection = $this->connection();
        $stmt = $connection->prepare($sql);
        $stmt->execute();

        $products = $stmt->fetchAll();

        foreach ($products AS $key => $item)
        {
            $product = $this->productRepository->getById($item['entity_id']);
            $token = $this->magento_rest_api_connection();
            $this->update_image_media_types($token, $product->getSku(), $product->getMediaGalleryImages()->getFirstItem()->getId());
        }
    }
```

**Comment by DaimPiek** [comment]
I'm having a similar issue on 2.1.10 (CE). I use a cron job to periodically import new product images. This works well when the product had no images before. But when images are updated the image roles disappear. 

I made sure the types on the GalleryEntry are correctly set. I encounter this issue through both CLI and crons.

**Edit**: I just found out what the issue was. Turns out you shouldn't use setFile on an existing GalleryEntry. When an entry is new the file string will be checked and replaced with a relative path. When an existing GalleryEntry is saved this does not happen resulting in the media attributes to be set with the absolute path, which is incorrect. 

For people still having issue, run the following query to find out if the media attributes are correctly set.
`SELECT * FROM bent.catalog_product_entity_varchar WHERE attribute_id IN (SELECT attribute_id FROM eav_attribute WHERE attribute_code IN ('small_image', 'thumbnail', 'small_image'));`

Values should be '/0/0/001.jpg' and not something like this: '/var/www/pub/media/catalog/product/download/75024/75024_001.jpg'.

**Comment by mariananassar** [comment]
I Has this problem, and my images didnt have role anymore.
There is a query to correct this? Someone did to correct this with query? to update all images to thumbnail and small image.

**Comment by robbertstevens** [comment]
The problem is caused when a third party module does a product save with the product repository, and doesn't unset `media_gallery`. Or you trigger a productrepository save without unsetting `media_gallery`.

**Comment by mcjwsk** [comment]
I have the same issue in Magento EE 2.2.2.

In addition, I don't need to use the edit mode and specify a store to reproduce this issue:
```php
<?php
$product = $this->productRepository->get($sku);
$this->productRepository->save($product);
```
and it results in:
```
mysql> select * from catalog_product_entity_varchar where row_id = 14 order by store_id;
+----------+--------------+----------+--------+------------------------------------------------+
| value_id | attribute_id | store_id | row_id | value                                          |
+----------+--------------+----------+--------+------------------------------------------------+
|    10901 |           73 |        0 |     14 | Produkt ABC                                    |
|    10902 |           84 |        0 |     14 | test                                           |
|    10903 |           86 |        0 |     14 | Produkt ABC                                    |
|    10909 |           87 |        0 |     14 | /2/1/21298950_1624752624242094_652571030_o.jpg |
|    10910 |           88 |        0 |     14 | /2/1/21298950_1624752624242094_652571030_o.jpg |
|    10911 |           89 |        0 |     14 | /2/1/21298950_1624752624242094_652571030_o.jpg |
|    10904 |          106 |        0 |     14 | container2                                     |
|    10905 |          124 |        0 |     14 | produkt-abc                                    |
|    10906 |          150 |        0 |     14 | 2                                              |
|    10907 |          151 |        0 |     14 | 2                                              |
|    10908 |          174 |        0 |     14 | 2                                              |
|    10912 |          175 |        0 |     14 | /2/1/21298950_1624752624242094_652571030_o.jpg |
|    10953 |           73 |        1 |     14 | Produkt ABC                                    |
|    10954 |           84 |        1 |     14 | test                                           |
|    10955 |           86 |        1 |     14 | Produkt ABC                                    |
|    10956 |           87 |        1 |     14 | no_selection                                   |
|    10957 |           88 |        1 |     14 | no_selection                                   |
|    10958 |           89 |        1 |     14 | no_selection                                   |
|    10959 |          106 |        1 |     14 | container2                                     |
|    10960 |          124 |        1 |     14 | produkt-abc                                    |
|    10962 |          151 |        1 |     14 | 2                                              |
|    10963 |          174 |        1 |     14 | 2                                              |
|    10964 |          175 |        1 |     14 | no_selection                                   |
+----------+--------------+----------+--------+------------------------------------------------+
```

(before this action I had rows for `store_id=0` only)

---

I'm pretty sure this issue is related to #8897

**Comment by stephansteiner** [comment]
Confirm on Magento 2.2.2 CE. It happens when updating a product over the REST api using
POST on /rest/all/V1/products, which did NOT happen in Magento 2.1.7.
In the REST POST request we do explicitly NOT set anything related to media gallery, but the returned json data shows that image roles has been deleted.

**Comment by capkafitz** [comment]
Method processMediaGallery() in ProductRepository.php (version 2.2.2 line 492): Every product save resets all media attributes. Problem is that key 'types' does not exists when using the function getMediaGallery('images').

`$this->getMediaGalleryProcessor()->clearMediaAttribute($product, array_keys($product->getMediaAttributes()));
        $images = $product->getMediaGallery('images');
        if ($images) {
            foreach ($images as $image) {
                if (!isset($image['removed']) && !empty($image['types'])) {
                    $this->getMediaGalleryProcessor()->setMediaAttribute($product, $image['types'], $image['file']);
                }
            }
        }`

**Comment by capkafitz** [comment]
Method processMediaGallery() in ProductRepository.php (version 2.2.2 line 492): Every product repository save() resets all media attributes. Problem is that key 'types' does not exists when using the function getMediaGallery('images').

```php
$this->getMediaGalleryProcessor()->clearMediaAttribute($product, array_keys($product->getMediaAttributes()));
$images = $product->getMediaGallery('images');
        if ($images) {
            foreach ($images as $image) {
                if (!isset($image['removed']) && !empty($image['types'])) {
                    $this->getMediaGalleryProcessor()->setMediaAttribute($product, $image['types'], $image['file']);
                }
            }
        }
```

**Comment by sunilit42** [comment]
I am working on this at #dmcdindia

**Comment by sunilit42** [comment]
@isavchuk-magento 

I have verified with Magento 2.2, it is working fine.

**Comment by arshadpkm** [comment]
@sunilit42   Have you tested on Magento 2.1.8

**Comment by Scarraban** [comment]
@sunilit42 Can you confirm what testing was done to confirm this as OK? I've just tested this on 2.2.3 and can confirm the existence of the issue outlined by @capkafitz.

Also confirmed no further fix applied in 2.2.4

**Comment by fireufo** [comment]
I came up with two temporary solution by myself, hope it will help someone: [Lost product image roles when save product by program](https://magento.stackexchange.com/a/227952/44237). 

If someone has better solution or the official fix the bug, please let me know :)

**Comment by Scarraban** [comment]
We've patched this for now by adding the following block into `vendor/magento/module-catalog/Model/ProductRepository.php`

```
        if($images) {
          $newImages = array();
          foreach ($images as $image) {
            $image['types'] = array();
            foreach(array_keys($product->getMediaAttributes()) as $attribute) {
              if($image['file'] == $product->getData($attribute)) {
                $image['types'][] = $attribute;
              }
            }
            $newImages[] = $image;
          }
          $images = $newImages;
        }
```

Before the `clearMediaAttribute()` method mentioned by @capkafitz - this essentially adds the missing 'types' keys that should be in the $images array anyway - and ensures they are restored after being initially cleared.

Don't think this is a permanent fix - as the `getMediaGallery()` should have 'types' set prior to this.

Regarding the replication steps - I think there's a key step missing, which is that the product needs to be saved initially with gallery entries, then saved without touching them:

# Preconditions
Magento 2.2.3
PHP 7
MySQL 5.7
Ubuntu 16.04
Nginx
Redis
Varnish
SSL (HTTPS)

# Reproduction steps:
## Preconditions
Create product with image and set role image: base, small, thumbnail

## Steps to reproduce
1. Save Product in backend controller like this:

```
$fileName = {INSERT_IMAGE_PATH_HERE}

$store = $this->storeManager->getStore(0);
$this->storeManager->setCurrentStore($store);
$product = $this->productRepository->getById($data['product_id'], true, $store->getId());
$product->addImageToMediaGallery($fileName, array('small_image', 'image', 'thumbnail'), false, false);
$this->productRepository->save($product);
```

2. Save it again, without changing the gallery:

```
$store = $this->storeManager->getStore(0);
$this->storeManager->setCurrentStore($store);
$product = $this->productRepository->getById($data['product_id'], true, $store->getId());
$this->productRepository->save($product);
```
## Expected result
Product image roles from step 1 should persist after step 2.

## Actual result
Product image does not have any roles

**Comment by kanasagraj** [comment]
I think its issue on Magento 2.2.3 or below version

**Open root/app/code/Magento/Catalog/Model/ProductRepository.php**

protected function processMediaGallery(ProductInterface $product, $mediaGalleryEntries)
{
**find : if (isset($entry['value_id']) // near line no : 499**
TO
**if (isset($entry['value_id']) && $entry['value_id'] != '') {**
}

I have make this patched and its working for me.( See : https://github.com/magento/magento2/issues/10461#issuecomment-399841160 )

**Comment by astragt** [comment]
Quick heads up for anyone who finds this issue because their image roles randomly disappears but you are not doing anything with the productRepository. 

Its enough that a Class that you are using i saving though the product repository to lose your image roles.

I saved tier prices through Magento\Catalog\Model\Product\ScopedTierPriceManagement and this is using the product repository so i lost my image roles. 

Tested in 2.2.3

**Comment by josefbehr** [comment]
We have a customer's shop, where image roles disappeared. Now we're trying to get them back, but none of the possible solutions here work, apparently. Magento version is 2.1.12. Anyone have any idea how to get the roles back?

**Comment by magento-engcom-team** [comment]
Hi @boxyman. Thank you for your report. 
The issue has been fixed in magento/magento2#15606 by @Scarraban in 2.2-develop branch
Related commit(s):
 - [a99e97e1ebbb3fd8b09e3a7236813831a76c7cef](https://github.com/magento/magento2/commit/a99e97e1ebbb3fd8b09e3a7236813831a76c7cef)

The fix will be available with the upcoming 2.2.7 release.

**Comment by magento-engcom-team** [comment]
Hi @boxyman. Thank you for your report. 
The issue has been fixed in magento/magento2#17554 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [1c74f5576011cd442dc086e52935c9fe68e7aa3e](https://github.com/magento/magento2/commit/1c74f5576011cd442dc086e52935c9fe68e7aa3e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by ishakhsuvarov** [comment]
Hi @boxyman. Thank you for your report. 
The issue has been fixed in magento/magento2#17553 by @eduard13 in 2.1-develop branch
Related commit(s):
 - [abb3c4aebc45a9fc42bea2fca7774067cda14921](https://github.com/magento/magento2/commit/abb3c4aebc45a9fc42bea2fca7774067cda14921)
 - [2be962d5ed75a9b838a1a9edc4d14bc659c8e496](https://github.com/magento/magento2/commit/2be962d5ed75a9b838a1a9edc4d14bc659c8e496)
 - [6a8fadfdeed5b37cd0bc3cc8b46503d18c76bcbb](https://github.com/magento/magento2/commit/6a8fadfdeed5b37cd0bc3cc8b46503d18c76bcbb)

The fix will be available with the upcoming 2.1.16 release.

**Comment by stijnkuppens** [comment]
The code fix is not present in 2.2.6, this looks still to be an issue. Any updates ?

**Comment by eduard13** [comment]
@skdude because the fix was provided in 2.2.7 (Release: 2.2.7).
Upgrade to2.2.7 or use a patch to apply the needed fix.

**Comment by merance2000** [comment]
I'm having this issue in 2.3.3 - how do we fix?

**Comment by markalston** [comment]
Also having this issue in 2.3.3.
I think the import function is wiping all the roles.  Images are there but all roles are cleared on import Add/Update

**Comment by merance2000** [comment]
Yes exactly what is happening for us too.

**Comment by SamJUK** [comment]
Had the same issue today with a client, easiest fix we found was to just reset the missing roles to the first image in the gallery. 

```php
<?php

ini_set('display_errors', 1);ini_set('display_startup_errors', 1);error_reporting(E_ALL);

use Magento\Framework\App\State;
use Magento\Framework\App\Bootstrap;
require 'app/bootstrap.php';

$bootstrap = Bootstrap::create(BP, $_SERVER);
$objectManager = $bootstrap->getObjectManager();
$state = $objectManager->get(State::class);
$state->setAreaCode('frontend');


$pri = $objectManager->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
$smi = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$smdl = $smi->getStores();
$stores = [0 => 'global'];
foreach ($smdl as $k => $v) {
	$stores[$k] = $v['code'];
}


foreach ($stores as $k => $v) {
	$smi->setCurrentStore($k);
	echo str_repeat('-', 20), PHP_EOL;
	echo "Processing {$k} ({$v})", PHP_EOL;
	echo str_repeat('-', 20), PHP_EOL;

	$collection = $objectManager->create(\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory::class)->create()->addAttributeToSelect('*');
	foreach ($collection as $product) {
		$objectManager->get("Magento\Catalog\Model\Product\Gallery\ReadHandler")->execute($product);
		$existingMediaGalleryEntries = $product->getMediaGalleryEntries();

		if (!is_iterable($existingMediaGalleryEntries) || count($existingMediaGalleryEntries) === 0) {
			continue;
		}

		$required_fields = ['image', 'small_image', 'thumbnail', 'swatch_image'];
		foreach ($existingMediaGalleryEntries as $key => $entry) {
			$required_fields = array_diff($required_fields, $entry['types']);

			if (count($required_fields) === 0) {
				continue 2;
			}
		}

		$slime = implode(' | ', $required_fields);
		echo "{$product->getSku()} :: $slime", PHP_EOL;

		$types = array_merge($required_fields, $existingMediaGalleryEntries[0]['types']);
		$existingMediaGalleryEntries[0]->setTypes($types);

		$product->setMediaGalleryEntries($existingMediaGalleryEntries);
		$pri->save($product);
	}
}
```

**Comment by tthierryEra** [comment]
Seems like it is still happening in 2.4.6 for me when I use 
- $this->productRepository->getById
- $product->setStoreId(0);
