### ISSUE TITLE
Meta description and keywords transform to html entities for non latin/cyrilic characters in category and product pages

### ISSUE THREAD

**Issue by fouli86** [magento/magento2#10682]
When setting up meta keywords and description in the categories and in every product, all non latin characters transform to html entities, but not the title.

### Preconditions
1. Magento CE 2.1.8
2. PHP 7.0.22
3. Server version: MySQL 5.6.35
4. el_GR language pack or any other non latin language

### Steps to reproduce
Choose and enable a non latin language pack, ie Greek
1. setup the meta keywords and description for a category and a product
2. view page source

### Expected result
All keywords appear as they should and category pages are "read" by google

### Actual result
All non latin words are html entities

I have double checked the data table entries, everything looks as it should.

Note: The meta title is shown correctly, but also everything works fine on the homepage.

**Comment by korostii** [comment]
For reference: this bug has been reported numerous times before.
Please see the following issues, for example: #5299, #4861, #2295
Still not fixed, it seems.

**Comment by magento-engcom-team** [comment]
@fouli86, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
Please provide more details regarding your environment, or try to reproduce this
issue on a clean installation.

**Comment by fouli86** [comment]
Hello,
Database Server:
    Server: Localhost via UNIX socket
    Server type: MySQL
    Server version: 5.6.35 - MySQL Community Server (GPL)
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)

Web Server:
     cpsrvd 11.64.0.39
    Database client version: libmysql - 5.1.73
    PHP extension: mysqli, curl, mbstring
    PHP version: 5.6.30

I am using the language pack found [here](https://crowdin.com/project/magento-2)
I can't think of other details to provide you. Please do ask me for anything more specific.  I haven't got the time yet to upgrade to the 2.1.9 version, in order to check if the problem still exists. I can send you my url in a private message or something, so that you can all better understand the issue.

Thanks in advance

**Comment by magento-engcom-team** [comment]
@fouli86, may you, please, describe "expected result" more clear

**Comment by fouli86** [comment]
Sure! Let me be more clear with the following print screens: 
Here is the Search Engine Optimization of a category on the backend
![image](https://user-images.githubusercontent.com/22245592/30660709-74066e5e-9e4a-11e7-9674-e80f58318766.png)

The expected result would be:
![image](https://user-images.githubusercontent.com/22245592/30660850-dfea2caa-9e4a-11e7-938a-db34650937a7.png)

But....the actual page source is:
![image](https://user-images.githubusercontent.com/22245592/30660975-3e7371b4-9e4b-11e7-88f8-99b65c6fd44e.png)

All words written in Greek are HTML entities, but note that the title is shown correctly (in greek characters). I have also noticed that whenever a category has no keywords and description, it uses correctly the keywords of my homepage.

I'm afraid I can't be more clear, but I really appreciate your help.

Thank you

**Comment by orlangur** [comment]
Assuming https://webmasters.stackexchange.com/questions/76522/are-html-encoded-symbols-allowed-in-meta-description and https://webmasters.stackexchange.com/questions/76211/meta-description-has-html-entities-will-google-show-the-real-character-or-the-e why is it a problem?

**Comment by hostep** [comment]
@orlangur: because it causes the html to be larger in filesize then if the characters are outputted just as is, in utf-8 format.

In case anyone is interested, the entity encoding happens on this line:
https://github.com/magento/magento2/blob/4b56264/lib/internal/Magento/Framework/View/Page/Config.php#L229

I think the call to `htmlentities` should get removed here, it's not the task of this class to already start encoding text. If there needs to be some encoding/escaping it should happen when outputting the html, so in a Block or in a phtml file.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83024

**Comment by magento-team** [comment]
Hi @fouli86. Thank you for your report. 
The issue has been fixed in magento/magento2#12955 by @dverkade in 2.3-develop branch
Related commit(s):
 - c49c52a08cb5d34e648ebf21da9d9235c14773ec

The fix will be available with the upcoming patch release.

**Comment by magento-team** [comment]
Hi @fouli86. Thank you for your report. 
The issue has been fixed in magento/magento2#12956 by @dverkade in 2.1-develop branch
Related commit(s):
 - 85db3a0b195857541cae8ceec99420e2f977a431
 - 66d4d4ef58633b2dd2f8df4f0dc08cecdaee9f01

The fix will be available with the upcoming patch release.
