### ISSUE TITLE
How i upgrade magento version

### ISSUE THREAD

**Issue by refaelgold** [magento/magento2#1069]
Hey , 
i try to do composer.phar update and all its up to date
i try to do pulling from the git and i get an error

did i do something wrong when i try to upgrade magneto 2?

i try to find an answer  in  the issues on this repo but i get no answer

Thanks,
Nir

**Comment by anupdugar** [comment]
@refaelgold Thanks for reporting the issue... 
What error do you get?

**Comment by joanhe** [comment]
@refaelgold Please let us know the error, so we can further assist you.

**Comment by refaelgold** [comment]
```
 [ErrorException]                                                                                                
  Target ./dev/tools/Magento/Tools/SampleData/Installer.php already exists (set extra.magento-force to override) 
```

and i cant use sample data installation 
when i use this command : 

```
php dev/tools/Magento/Tools/SampleData/install.php --admin_username=admin
```



i get 

```
exception 'ReflectionException' with message 'Class Magento\Framework\Store\StoreManagerInterface does not exist' in /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29
Stack trace:
#0 /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(29): ReflectionParameter->getClass()
#1 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Tools\\S...')
#2 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Tools\\S...')
#3 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#4 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#5 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'storeManager', 'Magento\\Tools\\S...')
#6 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#7 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#8 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#9 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'customerSetup', 'Magento\\Tools\\S...')
#10 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#11 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...', Array)
#12 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/SetupFactory.php(38): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Tools\\S...')
#13 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(82): Magento\Tools\SampleData\SetupFactory->create('Magento\\Tools\\S...')
#14 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/InstallerApp.php(96): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#15 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Tools\SampleData\InstallerApp->launch()
#16 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/install.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Tools\SampleData\InstallerApp))
#17 {main}

Next exception 'ReflectionException' with message 'Class Magento\Framework\Store\StoreManagerInterface does not exist' in /vagrant/data/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:37
Stack trace:
#0 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Tools\\S...')
#1 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Tools\\S...')
#2 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#3 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#4 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'storeManager', 'Magento\\Tools\\S...')
#5 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#6 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...')
#7 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tools\\S...')
#8 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Tools\\S...', NULL, 'customerSetup', 'Magento\\Tools\\S...')
#9 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Tools\\S...', Array, Array)
#10 /vagrant/data/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tools\\S...', Array)
#11 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/SetupFactory.php(38): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Tools\\S...')
#12 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(82): Magento\Tools\SampleData\SetupFactory->create('Magento\\Tools\\S...')
#13 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/InstallerApp.php(96): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#14 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Tools\SampleData\InstallerApp->launch()
#15 /vagrant/data/magento2/dev/tools/Magento/Tools/SampleData/install.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Tools\SampleData\InstallerApp))
```

**Comment by joanhe** [comment]
@refaelgold Thanks for reporting this problem. MAGETWO-34724 is created to internal tracking this issue. We will try to resolve this issue as soon as we can. In the mean time, please try this work around add extra section with *"magento-force": true* to composer.json file, it should look like this: 
```
   "extra": {
        "magento-force": true
    }
```

The problem regarding the sample data installation, it looks like the code is out of sync. Try to install the latest Magento and then install sample data.

**Comment by refaelgold** [comment]
Hey 
I using vagrant for magento 2
https://github.com/rgranadino/mage2_vagrant

i'm sure i download the most updated magento component by compare my composer.json to the original repo

i got magento 42.2.0-10 beta

i have this option https://github.com/tzyganu/m2-sample-data

but i want to do it in the right way. 

Also , i read a lot of issues with installing sample data in this repo and try alot of solution but nothing works 

this is my composer.json
'''
{
    "name": "magento/project-community-edition",
    "description": "Magento project (Community Edition)",
    "type": "project",
    "version": "0.42.0-beta10",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "php": "~5.5.0|~5.6.0",
        "zendframework/zend-stdlib": "2.3.1",
        "zendframework/zend-code": "2.3.1",
        "zendframework/zend-server": "2.3.1",
        "zendframework/zend-soap": "2.3.1",
        "zendframework/zend-uri": "2.3.1",
        "zendframework/zend-validator": "2.3.1",
        "zendframework/zend-console": "2.3.1",
        "zendframework/zend-modulemanager": "2.3.1",
        "zendframework/zend-mvc": "2.3.1",
        "zendframework/zend-text": "2.3.1",
        "zendframework/zend-eventmanager": "2.3.1",
        "zendframework/zend-view": "2.3.1",
        "zendframework/zend-servicemanager": "2.3.1",
        "zendframework/zend-json": "2.3.1",
        "zendframework/zend-config": "2.3.1",
        "zendframework/zend-form": "2.3.1",
        "zendframework/zend-di": "2.3.1",
        "zendframework/zend-serializer": "2.3.1",
        "zendframework/zend-log": "2.3.1",
        "zendframework/zend-http": "2.3.1",
        "magento/zendframework1": "1.12.10",
        "composer/composer": "1.0.0-alpha8",
        "monolog/monolog": "1.11.0",
        "tubalmartin/cssmin": "2.4.8-p4"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "lib-libxml": "*",
        "ext-ctype": "*",
        "ext-gd": "*",
        "ext-spl": "*",
        "ext-dom": "*",
        "ext-simplexml": "*",
        "ext-hash": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3",
        "magento/sample-data": "0.42.0-beta6",
        "magento/sample-data-media": "0.42.0-beta1"
    },
    "replace": {
        "magento/module-admin-notification": "self.version",
        "magento/module-authorization": "self.version",
        "magento/module-backend": "self.version",
        "magento/module-backup": "self.version",
        "magento/module-bundle": "self.version",
        "magento/module-captcha": "self.version",
        "magento/module-catalog": "self.version",
        "magento/module-catalog-import-export": "self.version",
        "magento/module-catalog-inventory": "self.version",
        "magento/module-catalog-rule": "self.version",
        "magento/module-catalog-search": "self.version",
        "magento/module-catalog-url-rewrite": "self.version",
        "magento/module-catalog-widget": "self.version",
        "magento/module-centinel": "self.version",
        "magento/module-checkout": "self.version",
        "magento/module-checkout-agreements": "self.version",
        "magento/module-cms": "self.version",
        "magento/module-cms-url-rewrite": "self.version",
        "magento/module-config": "self.version",
        "magento/module-configurable-import-export": "self.version",
        "magento/module-configurable-product": "self.version",
        "magento/module-contact": "self.version",
        "magento/module-cookie": "self.version",
        "magento/module-core": "self.version",
        "magento/module-cron": "self.version",
        "magento/module-currency-symbol": "self.version",
        "magento/module-customer": "self.version",
        "magento/module-customer-import-export": "self.version",
        "magento/module-design-editor": "self.version",
        "magento/module-developer": "self.version",
        "magento/module-dhl": "self.version",
        "magento/module-directory": "self.version",
        "magento/module-downloadable": "self.version",
        "magento/module-eav": "self.version",
        "magento/module-email": "self.version",
        "magento/module-fedex": "self.version",
        "magento/module-gift-message": "self.version",
        "magento/module-google-adwords": "self.version",
        "magento/module-google-analytics": "self.version",
        "magento/module-google-optimizer": "self.version",
        "magento/module-google-shopping": "self.version",
        "magento/module-grouped-import-export": "self.version",
        "magento/module-grouped-product": "self.version",
        "magento/module-import-export": "self.version",
        "magento/module-indexer": "self.version",
        "magento/module-integration": "self.version",
        "magento/module-layered-navigation": "self.version",
        "magento/module-log": "self.version",
        "magento/module-msrp": "self.version",
        "magento/module-multishipping": "self.version",
        "magento/module-newsletter": "self.version",
        "magento/module-offline-payments": "self.version",
        "magento/module-offline-shipping": "self.version",
        "magento/module-page-cache": "self.version",
        "magento/module-payment": "self.version",
        "magento/module-persistent": "self.version",
        "magento/module-product-alert": "self.version",
        "magento/module-quote": "self.version",
        "magento/module-reports": "self.version",
        "magento/module-require-js": "self.version",
        "magento/module-review": "self.version",
        "magento/module-rss": "self.version",
        "magento/module-rule": "self.version",
        "magento/module-sales": "self.version",
        "magento/module-sales-rule": "self.version",
        "magento/module-search": "self.version",
        "magento/module-sendfriend": "self.version",
        "magento/module-shipping": "self.version",
        "magento/module-sitemap": "self.version",
        "magento/module-store": "self.version",
        "magento/module-tax": "self.version",
        "magento/module-tax-import-export": "self.version",
        "magento/module-theme": "self.version",
        "magento/module-translation": "self.version",
        "magento/module-ui": "self.version",
        "magento/module-ups": "self.version",
        "magento/module-url-rewrite": "self.version",
        "magento/module-user": "self.version",
        "magento/module-usps": "self.version",
        "magento/module-variable": "self.version",
        "magento/module-version": "self.version",
        "magento/module-webapi": "self.version",
        "magento/module-weee": "self.version",
        "magento/module-widget": "self.version",
        "magento/module-wishlist": "self.version",
        "magento/theme-adminhtml-backend": "self.version",
        "magento/theme-frontend-blank": "self.version",
        "magento/theme-frontend-luma": "self.version",
        "magento/language-de_de": "self.version",
        "magento/language-en_us": "self.version",
        "magento/language-es_es": "self.version",
        "magento/language-fr_fr": "self.version",
        "magento/language-nl_nl": "self.version",
        "magento/language-pt_br": "self.version",
        "magento/language-zh_cn": "self.version",
        "magento/framework": "self.version",
        "oyejorge/less.php": "1.7.0",
        "trentrichardson/jquery-timepicker-addon": "1.4.3",
        "colinmollenhour/cache-backend-redis": "dev-master#193d377b7fb2e88595578b282fa01a62d1185abc",
        "colinmollenhour/credis": "dev-master#f07bbfd4117294f462f0fb19c49221d350bf396f",
        "linkorb/jsmin-php": "1.1.2",
        "phpseclib/phpseclib": "0.2.1",
        "components/jquery": "1.11.0",
        "blueimp/jquery-file-upload": "5.6.14",
        "components/jqueryui": "1.10.4",
        "twbs/bootstrap": "3.1.0",
        "tinymce/tinymce": "3.4.7"
    },
    "extra": {
        "magento-force": true,
        "component_paths": {
            "oyejorge/less.php": "lib/internal/Less",
            "trentrichardson/jquery-timepicker-addon": "lib/web/jquery/jquery-ui-timepicker-addon.js",
            "colinmollenhour/cache-backend-redis": "lib/internal/Cm/Cache/Backend/Redis.php",
            "colinmollenhour/credis": "lib/internal/Credis",
            "linkorb/jsmin-php": "lib/internal/JSMin",
            "phpseclib/phpseclib": "lib/internal/phpseclib",
            "components/jquery": [
                "lib/web/jquery.js",
                "lib/web/jquery/jquery.min.js",
                "lib/web/jquery/jquery-migrate.js",
                "lib/web/jquery/jquery-migrate.min.js"
            ],
            "blueimp/jquery-file-upload": "lib/web/jquery/fileUploader",
            "components/jqueryui": [
                "lib/web/jquery/jquery-ui.js",
                "lib/web/jquery/jquery-ui.min.js"
            ],
            "twbs/bootstrap": [
                "lib/web/jquery/jquery.tabs.js"
            ],
            "tinymce/tinymce": "lib/web/tiny_mce"
        }
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\ToolkitFramework\\": "dev/tools/performance-toolkit/framework/Magento/ToolkitFramework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/"
        }
    },
    "repositories": {
        "magento": {
            "type": "composer",
            "url": "http://packages.magento.com"
        }
    }
}
'''

**Comment by buskamuza** [comment]
@refaelgold , thanks for reporting it.
This is a bug in Magento Composer Installer user for installing packages.
We've already fixed it in our internal repository and the fix should be available in public one shortly. We'll update you as soon as it happens.

@snohe , internal tickets: MAGETWO-34551, MAGETWO-34212

**Comment by vpelipenko** [comment]
@refaelgold, related internal ticket are closed now and fixes are already pushed to public GitHub. Please, verify the issue on your instance with the latest code.
