### ISSUE TITLE
static blocks not loading 

### ISSUE THREAD

**Issue by bhagyarajallu** [magento/magento2#10690]
### Preconditions

1. Magento v2.1.3
2. PHP 7.0, MySQL 5.1

### Steps to reproduce

1. Go to Content -> Elements -> Blocks

### Expected result

1. the static blocks should load 

### Actual result

1. [Screenshot, logs]
the spinner keeps on progressing with out loading the content
the output of the browser console:
```
/pub/static/adminhtml/Magento/backend/en_US/jquery/jquery-migrate.min.js:6 JQMIGRATE: Logging is active
(index):1 Uncaught SyntaxError: Unexpected token < in JSON at position 42791
    at JSON.parse (<anonymous>)
    at getNodeData (/pub/static/adminhtml/Magento/backend/en_US/mage/apply/scripts.min.js:5)
    at Array.map (<anonymous>)
    at /pub/static/adminhtml/Magento/backend/en_US/mage/apply/scripts.min.js:6
    at Object.apply (/pub/static/adminhtml/Magento/backend/en_US/mage/apply/main.min.js:4)
    at HTMLDocument.bootstrap (/pub/static/adminhtml/Magento/backend/en_US/mage/backend/bootstrap.min.js:2)
    at fire (/pub/static/adminhtml/Magento/backend/en_US/jquery.min.js:212)
    at Object.add [as done] (/pub/static/adminhtml/Magento/backend/en_US/jquery.min.js:213)
    at jQuery.fn.init.jQuery.fn.ready (/pub/static/adminhtml/Magento/backend/en_US/jquery.min.js:222)
    at jQuery.fn.init (/pub/static/adminhtml/Magento/backend/en_US/jquery.min.js:197)
```
![capsture](https://user-images.githubusercontent.com/14735431/29804138-398b7606-8c9e-11e7-88d6-1dde51643ad3.PNG)

[debug.log.txt](https://github.com/magento/magento2/files/1270543/debug.log.txt)
[exception.log.txt](https://github.com/magento/magento2/files/1270544/exception.log.txt)

**Comment by xtremeperf** [comment]
Can you please check logs `var/log/exception.log` and `var/log/debug.log` and post the results and post the results for the entries at the time which this occurs?

Thanks,
Doug

**Comment by bhagyarajallu** [comment]
[exception and debug.zip](https://github.com/magento/magento2/files/1264040/exception.and.debug.zip)

hai thanks for the response here i attached the exception and debug log please check and help me

**Comment by xtremeperf** [comment]
Thank you.  I'm going to ask many questions at one time so we can reduce the amount of time with our replies.

Does this occur in all web browsers (chrome/edge/etc)?

Are any errors occuring on the front end of the web store?  Anything in the client browser console?

What are you using for backend and page cache?

Does this error happen in developer mode and with all cache types disabled & cache storage cleared?

When did this error start to occur?  Any installations/updates/etc. immediately before it started happening?


Thanks,
Doug

**Comment by bhagyarajallu** [comment]
yes it occurs in all browsers

no errors occurred on the front end

im using no plugin for page cache

no error doesn't happened in the developer mode

error started by a editing a contact us page block module of theme ,

the block was not saved correctly ,from that i cant see the contact us
block on front end of theme
remain works same

**Comment by TomashKhamlai** [comment]
@bhagyarajallu, please check if you are using [required version of MySQL](http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#database). I updated your issue, please, recheck.

**Comment by fabionoa** [comment]
Hello, do I have the same problem? Has anyone managed to solve it?

**Comment by magento-engcom-team** [comment]
@bhagyarajallu From the attached exception log it is clearly visible that you have third-party extensions/customizations installed on your store. This might be the cause of the issue. Please attempt to reproduce the issue with the clean Magento 2 install. If the issue persists please reopen this ticket.

Thank you.
