### ISSUE TITLE
magentoCE2.14 register page strange password strength notice

### ISSUE THREAD

**Issue by Boolem** [magento/magento2#10703]
magentoCE 2.1.4 stranger password strength message in register page
### Preconditions

1. ubuntu 14.04, php7, mysql5.6 , magento version ce-2.14

### Steps to reproduce

1.I n the register page, input a password likes:Cc-2017010 ,then I see the password strength message shows "Strong".
![selection_409](https://user-images.githubusercontent.com/31463841/29855094-16ebbd70-8d7c-11e7-8bf4-ff071f6c8e30.png)

2. Then,I change the password to 'Cc-20170109',the password strength turn to 'Medium'
![selection_410](https://user-images.githubusercontent.com/31463841/29855106-2a8312de-8d7c-11e7-9bc1-ab16a91a52b7.png)

### Expected result

1. The password 'Cc-20170109' strength  should be same or more larger than 'Cc-2017010'.

### Actual result

1. [Screenshot, logs]
 The password strength of 'Cc-20170109' is 'medium',its strength is lower than password 'Cc-2017010' which is 'strong'.
Does anyone know how the magento password strength checker work?Is this the bug?

**Comment by fooman** [comment]
The password strength meter is using this [project](https://github.com/dropbox/zxcvbn/).

My current guess would be that the second password  
Cc-2017010  
Cc-20170109  
gets marked down because it includes a valid way to describe a date (January 9th 2017) whereas the first one is only an incomplete date.

**Comment by magento-engcom-team** [comment]
@Boolem, thank you for your report.
We've created internal ticket(s) MAGETWO-78400 to track progress on the issue.

**Comment by vrann** [comment]
@fooman @rogyar thank you for details on this issue. It makes sense to close the issue.
