### ISSUE TITLE
Create attribute option via API for swatch attribute fails

### ISSUE THREAD

**Issue by bartlubbersen** [magento/magento2#10707]
### Preconditions
1. Magento 2.1.8
2. PHP7

### Steps to reproduce
1. Create a select attribute
2. Make this attribute use visual or text swatch
3. Try adding attribute options through the API via POST /V1/products/attributes/{attributeCode}/options

### Expected result
The attribute options should be added the same as without swatch options selected for attribute.

### Actual result
Although the API is not giving any errors and returns true with code 200, the option is not added to the attribute.

### Problem
The problem is due to the swatch module plugin EavAttribute, in this plugin the option value is overwritten by optionvisual or optiontext. This is because these are used for the tables in the back-end. However through the API it is only possible to enter a value for option. So the option you entered through the API is replaced by an empty value.

**Comment by bartlubbersen** [comment]
This issue seems to be the same as #10737

**Comment by magento-engcom-team** [comment]
@bartlubbersen thank you for your bug report.
We've created internal ticket MAGETWO-75336 to track progress on the issue

**Comment by gomencal** [comment]
I am working on it at #mm17es :)

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.1-develop and 2.2-develop branches
