### ISSUE TITLE
Upgraded from 2.1.7 to 2.1.8 No Payment Methods Working or Shipping Totals Showing

### ISSUE THREAD

**Issue by eCommerceGorilla** [magento/magento2#10713]
Upgraded a working Magento 2 store hosted on Nexcess. After upgrade from 2.1.7 to 2.1.8 no payment methods are returned (this includes COD, Check etc)

The shipping totals from USPS are no longer displayed. However, they are being returned just not populating the price knock out.

This was tested on an entirely vanilla installation on the same hosting platform with the exact same results.

No exception or system logs are being generated. No console errors for php or javascript either.

PHP Version 7.0.17

**Comment by orlangur** [comment]
How you think this can be reproduced & investigated by anyone else?

Am I understood you right that vanilla `2.1.8` installation on this platform does not show payment methods as well?

**Comment by eCommerceGorilla** [comment]
What specific information do you want to know? There are no error logs being generated, no exceptions, no javascript errors or php errors. I don't know what else I can provide but if you are specific about your requests I will strive to accommodate them.

This was a fully functional store on version 2.1.7 and after the upgrade to 2.1.8 it ceased to function in regards to checkout payment options and the inclusion of shipping prices.

Further to test that it wasn't an issue with the update I installed a vanilla 2.1.8 on the same server and it contained the exact same issues.

There are a number of open issues with version 2.1.8 no showing paypal methods, do these stores only have paypal as a checkout option?

**Comment by orlangur** [comment]
> I installed a vanilla 2.1.8 on the same server and it contained the exact same issues.

Thanks for clarification, it indicates the problem with the server. You need to look into web server logs or any other possibilities to investigate issue on your side.

> There are a number of open issues with version 2.1.8 no showing paypal methods, do these stores only have paypal as a checkout option?

Problem with PayPal methods affected only some stores, I believe it was mentioned in some of the reports that other methods work as before. It's worth mentioning that as payment methods are covered with functional tests (i.e. tests which involve Selenium and real browser) they cannot be broken in any release. Payment method may only be broken in some specific configuration not covered by test.

By the way, you mentioned the issue occurred after upgrade from 2.1.7 to 2.1.8. If you install vanilla 2.1.7 instance, does it work on the same server?

**Comment by eCommerceGorilla** [comment]
We located the issue on the server. It turns out that the USPS was tripping a modsec rule in 2.1.8 but not in 2.1.7. which was having an impact on the payment methods being returned.

We are reviewing and updating the modsec to prevent this from happening further.

**Comment by orlangur** [comment]
Glad to hear your problem is located! I was thinking of something like that reading your LiveHelperChat bug report :)
