### ISSUE TITLE
Magento 2.1.4 Frontend Session Lost After Log-in

### ISSUE THREAD

**Issue by Joker2099** [magento/magento2#10719]
When you log in to an account on the frontend and navigate to the home page by clicking on the logo from the account dashboard, the session/cookie is getting lost and it kicks you out from the account. While when you click on the category or product you can still see "Sign out" link.

I also noticed that if I continuously click on random pages category, product, etc it randomly logs me back in and shows "Sign out" link.

### Preconditions

1. Magento 2.1.4
2. PHP 7.0.15
3. MYSQL 5.6.35

### Steps to reproduce

1. Sign in on the frontend
2. Click on the logo to navigate to website's home page or category in the menu

### Expected result

1. Customer stays logged in the whole time

### Actual result

1. Session is lost, system kicks you out from the account (at least visually)

Please point me to a similar topic if it's a repeat.

**Comment by orlangur** [comment]
Do you have any extensions installed / templates customized? Is the same issue observed on Magento 2.1.8 for your environment?

**Comment by Joker2099** [comment]
The only extension I have is Mageplaza Social Log-in which in this case isn't being used to sign in. I'm signing in via regular Mage login/pass system.

I haven't tested 2.1.8 yet but will be doing that soon. I will post here once I get that done.

**Comment by orlangur** [comment]
Ok, thanks, even if it is not used in some scenario this extension could override some templates (could be checked with template path hints).

So, for the clean experiment it could be temporary disabled/uninstalled.

**Comment by Joker2099** [comment]
Here is an example
http://magento2-demo.nexcess.net/

Try signing in and click on the Luma logo.

**Comment by Joker2099** [comment]
I believe it was fixed in 2.1.6 or so. 
Since it doesn't happen in 2.1.6 http://magento2demo.firebearstudio.com

**Comment by orlangur** [comment]
```
Request URL:http://magento2-demo.nexcess.net/customer/section/load/?sections=cart%2Ccompare-products%2Ccustomer%2Cmessages&update_section_id=false&_=1504189863875
Request Method:GET
Status Code:500 Internal Server Error
```

Cannot work when there is HTTP error 500 :) Also, I see such error when login. Looks environment specific.

**Comment by Joker2099** [comment]
Interesting fact though. When I sign-in via Mageplaza's Social Log-in on frontend, I don't have this issue. Though, we can see that it is present in 2.1.4 on Nexcess' demo site without the extension installed.

**Comment by Joker2099** [comment]
Tested it on 2.1.8, no sign of the issue.
