### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by rorteg** [magento/magento2#1071]
My room is ok for all requirements, but is thrown an exception in check the installation:

File: vendor/composer/composer/src/Composer/Package/Version/VersionParser.php:370

Message: Could not parse version constraint 5.5.9-1ubuntu4.6: Invalid version string "5.5.9-1ubuntu4.6"

Stack Trace:

#0 /var/www/magento-develop-environment/magento-2x/magento2/vendor/composer/composer/src/Composer/Package/Version/VersionParser.php(237): Composer\Package\Version\VersionParser->parseConstraint('5.5.9-1ubuntu4....')
#1 /var/www/magento-develop-environment/magento-2x/magento2/setup/src/Magento/Setup/Controller/Environment.php(69): Composer\Package\Version\VersionParser->parseConstraints('5.5.9-1ubuntu4....')
#2 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Environment->phpVersionAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/magento-develop-environment/magento-2x/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/magento-develop-environment/magento-2x/magento2/setup/index.php(25): Zend\Mvc\Application->run()
#13 {main}

Thanks.

**Comment by rorteg** [comment]
This is due to the display of some versions of php contain the Linux distribution name being used.

**Comment by versedi** [comment]
Duplicated: https://github.com/magento/magento2/issues/1066

**Comment by snohe** [comment]
@rorteg, since this is a duplicate, we will go ahead and close this issue.  Please refer to #1066 for further updates.

**Comment by rorteg** [comment]
Ok, thanks @versedi and @snohe.
