### ISSUE TITLE
New pages created returns 404 when are viewed

### ISSUE THREAD

**Issue by iancumarian** [magento/magento2#10712]
### Preconditions

1. Have a site built with Magento CMS

### Steps to reproduce

1. Access Magento admin
2. Go to Content > Pages
3. Create a new page (press "Add new page" button)
4. After all the mandatory fields are filled (page title, Conent, SEO) save the page.
5. Go again to Content>Pages, look for the new page above, and from the right side column ("Action") select 'View'

### Expected result
The page should be displayed (with content and all other setting made when the page was created)

### Actual result
When trying to view the page 404 Not found is returned to the user. This a sever issue because makes impossible to the user to ad new pages to his site
1. [Screenshot, logs]

**Comment by TomashKhamlai** [comment]
Please add screenshots and logs that you mentioned. I followed your steps and got what you can see on the image below:
![screenshot](https://user-images.githubusercontent.com/11827230/29970831-ddef77e0-8ec1-11e7-9716-a22b9d7aae50.png)

**Comment by iancumarian** [comment]
I'm using this template for my site http://plazathemes.com/demo/colora/english1/, in your example i see there is the default Luma theme.
Here is the record of the issue, at the end is the 404 page as i designed for my site. 
http://recordit.co/878Q4YVTfw

**Comment by TomashKhamlai** [comment]
It looks like not a Magento bug. If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com) site as GitHub issue tracker is intended for technical issues only.
