### ISSUE TITLE
Weights for products can be set in pounds but not kilograms

### ISSUE THREAD

**Issue by Simon-Davies** [magento/magento2#10716]
Magento: 2.1.8
PHP: 7.0.15

Weights for products can be set in pounds but not kilograms. It would be good to have the option to be able to set them in kilograms aswell.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.

**Comment by hostep** [comment]
This is not a new feature request as the feature already exist in Magento :)

@Simon-Davies: You can configure Magento to use either pound or kilogram per storeview, see: Stores > Configuration > General > General > Locale Options > Weight Unit

But @orlangur is correct, GitHub isn't the place to ask these kind of questions.

**Comment by orlangur** [comment]
@hostep oh, thanks, I had some kind of déjà vu that I already saw it somewhere.
