### ISSUE TITLE
Subcategories not accessible from parent category on tablet

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#10724]
### Preconditions
Magento 2.1.8

### Steps to reproduce
1. Select a sub category from a parent category on a tablet. 

### Expected result
1. Drop down menu should stay open to access sub categories
2. Or site should convert to mobile version on tablets as does RWD theme on M1

### Actual result
1. If you try to open the menu you are simply navigated to the parent category page.

Issue only occurs on tablets. Desktop version is displayed when mobile version should be.

**Comment by magento-engcom-team** [comment]
@bondimedical3 , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.
