### ISSUE TITLE
Design Configuration Edit Page Isn't Working

### ISSUE THREAD

**Issue by catzpaw164** [magento/magento2#10720]
### Preconditions
Store configuration page is no longer available after flushing Magento cache after uploading logo to be used for transactional emails.

1. Magento 2.1.7

### Steps to reproduce
1.  On the Admin sidebar, tap Content. Then under Design, choose Configuration.
2.  Find the store view that you want to configure. Then in the Action column, click Edit.

### Expected result
1. Should see menu and options for configuring things like Transactional emails.

### Actual result

1. In Chrome the page displays the following error: This page isn't working. HTTP Error 500
    www.catzpawstore.com is currently unable to handle this request.

<img width="573" alt="screen shot 2017-08-30 at 5 22 38 pm" src="https://user-images.githubusercontent.com/31491198/29896523-553415bc-8dab-11e7-84c4-b72d87457f0e.png">

In Safari the window remains blank.

**Comment by xtremeperf** [comment]
Sounds like a file permissions issue.  Since it only happened after uploading the logo, I would check the permissions on that logo file, especially the owner & group.

Regards,
Doug

**Comment by orlangur** [comment]
HTTP Error 500 tells nothing about the problem. Try to check web server and Magento error logs.

**Comment by magento-engcom-team** [comment]
@catzpaw164 unfortunately we can not reproduce the issue.
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
