### ISSUE TITLE
Sometimes categories are not loading when editing product

### ISSUE THREAD

**Issue by Nathaniel-Meyer** [magento/magento2#10722]
Sometimes when adding or editing a product the Categories info isn't being loaded into the field.

When I run `php bin/magento indexer:reindex  ` it fixes it but then when I update the cache sometimes it works sometimes it doesn't. Found it doesn't after the front end has been loaded then load the back end again and field doesn't display correctly.

### Preconditions
ver:  2.1.7

### Steps to reproduce
1.  Click add or edit product and doesn't load the categories correctly 

### Expected result

1.  The categories should load correctly 

### Actual result
![screen shot 2017-08-31 at 1 02 17 pm](https://user-images.githubusercontent.com/9003600/29901701-8109178a-8e4d-11e7-8f2b-96f2128b85e0.png)

### Update 

vendor/magento/module-ui/view/base/web/templates/grid/filters/elements/ui-select.html

after line 119 i have added `<div data-bind="text: console.log(option)"></div>` and get this output 

### When working 
![screen shot 2017-08-31 at 2 34 00 pm](https://user-images.githubusercontent.com/9003600/29903736-765561fc-8e59-11e7-8f63-2ea02717af0b.png)

### When not working 
![screen shot 2017-08-31 at 2 48 48 pm](https://user-images.githubusercontent.com/9003600/29904152-8f5765ea-8e5b-11e7-9cd5-2a53f7c83ff8.png)

**Comment by RomaKis** [comment]
@natahanielmeyer , thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
Please provide more details regarding your environment, or try to reproduce this
issue on a clean installation.

**Comment by orlangur** [comment]
Similar to https://github.com/magento/magento2/issues/9956, according to "When not working" here the JS error should also be "label is not defined". There problem appeared only if you enable a particular third-party module. @natahanielmeyer do you have the same module installed maybe?

**Comment by Dynasto** [comment]
Another developer here, this problem occurs to me as well. Thanks for the tip with reindexing!

**Comment by magento-engcom-team** [comment]
@natahanielmeyer, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
