### ISSUE TITLE
Magento 2.1.6 Checkout show no payment method when click update button after refresh page it show all (payment & address)

### ISSUE THREAD

**Issue by lalittmohan** [magento/magento2#10727]
### Preconditions

1. i'm using Magento 2.1.6
2. Payment Method : PayUmoney, CCavenue,COD
3. Configurable products 

### Steps to reproduce

1. add to cart a item.
2. proceed go to checkout page 
3. select payment method
4. fill customer detail as guest or existing customer
5.click on update button

### Expected result

1. it should show address detail with payment method
![expected](https://user-images.githubusercontent.com/5228822/29916192-ac96e644-8e5b-11e7-8a21-1eecdba4e0b3.png)

### Actual result

1.it show no payment method
2. it show when refresh checkout page manually.

![payment issue](https://user-images.githubusercontent.com/5228822/29916150-8d929b58-8e5b-11e7-863e-69ef69b5b008.png)

**Comment by YevSent** [comment]
Hi, @lalittmohan, can you reproduce the same issue on Magento 2.1.8 with built-in payment methods?

**Comment by lalittmohan** [comment]
sure, let you know if issue happened again

**Comment by ihor-sviziev** [comment]
@lalittmohan please check browser developer console (f12), there should be some errors that caused such behavior. Please add them if they appear

**Comment by lalittmohan** [comment]
![issuecheckout](https://user-images.githubusercontent.com/5228822/29923205-490c8df2-8e76-11e7-9b42-89296e9869c0.png)

**Comment by lalittmohan** [comment]
![issuecheckout](https://user-images.githubusercontent.com/5228822/29923252-847b9342-8e76-11e7-98ce-55cc7ce45e67.png)

**Comment by YevSent** [comment]
I've checked the described flow on your https://www.beuor.com shop, seems, you are using custom checkout extension with custom payment methods. Also, have checked on the fresh installation of 2.1.8 with `Tax Calculation Based On` == `Billing Address` to trigger billing address update request, all works as expected.
Please, confirm if this issue reproducible on Magento installation without additional extensions?
