### ISSUE TITLE
Make error handling easier to extend

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#1072]
I currently have to do a plugin which replaces the Magento\Framework\App\Http->catchException() call, as plugins only work on public methods, and the protected handleDeveloperMode() directly sends the output. The current way I do this feels wrong, and I dont see another one which would work more modular, so I assume this should get improved.

priority for me: low

Context: I wrote a module which improves the display during errors https://github.com/Cotya/DebugModule

**Comment by ilol** [comment]
MAGETWO-34670

**Comment by choukalos** [comment]
Reassigned to Mark; who owns the exception handling epic that's related to this ask ( MAGETWO-30314 )

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Make-error-handling-easier-to-extend/idi-p/46620).
