### ISSUE TITLE
Can't import attribute option over API if option is 'visual swatch'

### ISSUE THREAD

**Issue by slavkodick** [magento/magento2#10737]
### Preconditions

1. Magento 2.1.8 

### Steps to reproduce

1. Import Attribute Option of type visual swatch (Color for example) over http request (API)
2. Code example:
{
        $option = $this->attrOptionFactory->create();
        $optionLabel = $this->attrOptionLabelFactory->create();

        $optionLabel->setStoreId(0);
        $optionLabel->setLabel('new_color');

        $option->setLabel('new_color');
        $option->setStoreLabels(array($optionLabel));
        
        $this->productAttributeOptionManagement->add('color', $option);
    }

### Expected result

1. New Attribute Option should be imported to backend 

### Actual result

1. New Atttribute Option does not get imported because there is no entry in eav_attribute_option_swatch table

### More info
Until Magento 2.1.7 the plugin did not trigger beforeSave function in swatches/Model/Plugin/EavAttribute and the Import data had not to match visual swatch data structure, it was imported
Since Magento 2.1.8 the function is renamed to beforeBeforeSave and the plugin triggers it,
so the Import data has to follow data structure of visual swatch, but since it is a API Import there is no entry in database and the new Option does not get imported

**Comment by magento-engcom-team** [comment]
We are closing this issue because we cannot reproduce this issue as described. If you have questions, please refer to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Comment by slavkodick** [comment]
It seems that's the same problem as #10707, could you leave the issue open until it's solved?

**Comment by orlangur** [comment]
@slavkodick why keep two issues for the same problem open?

**Comment by josephmcdermott** [comment]
What is the definition of 'fixed' here? With the latest Swatch module from `2.2-develop` we can import a new Swatch Option via the API method, however the required Admin value is empty: `Magento\Catalog\Api\ProductAttributeOptionManagementInterface::add`

I do not see anywhere in the `\Magento\Eav\Api\Data\AttributeOptionInterface` to append Swatch information?

For example:
```
{
    "option": {
        "label": "API Test Label",
        "value": "API Test Value",
        "sort_order": 0,
        "is_default": false,
        "store_labels": [
            {
                "store_id": 0,
                "label": "API Test Label Store 0"
            },
            {
                "store_id": 1,
                "label": "API Test Label Store 1"
            }
        ]
    }
}
```

Results in a half-populated Option:
![incomplete-swatch-option](https://user-images.githubusercontent.com/6955944/36391421-5a2a603c-159e-11e8-97bc-74ddd56fc600.jpg)

Am I missing something?

**Comment by durgagupta** [comment]
i am also facing same issue could not find node to add hex code or  image

url: http://{domain_name}/index.php/rest/V1/products/attributes/{attribute_code}/options
Method: POST
```
{
  "option": {
        "label": "default store label",
        "value": "46477",
        "sort_order": 0,
        "is_default": false,
        "store_labels": [
          {
            "store_id": 1,
            "label": "en store label"
          },
          {
            "store_id": 2,
            "label": "NL store label"
          },
          {
            "store_id": 3,
            "label": "DE store label"
          },
          {
            "store_id": 4,
            "label": "FR store label"
          }
        ]
      }
}

```

**Comment by orlangur** [comment]
Reopening for recheck by @magento-engcom-team.

**Comment by magento-engcom-team** [comment]
@slavkodick, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by EBotha1** [comment]
@magento-admin @magento-devops @magento-engcom-team I am facing the same issue. In Postman we are sending a soap request to create a new 'option' for a text/swatch attribute. 
Post Body:
`<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:def="XXX/soap/all?services=catalogProductAttributeOptionManagementV1" xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Body>
		<def:catalogProductAttributeOptionManagementV1AddRequest>
			<attributeCode>d_textswatch</attributeCode>
			<option>
				<sortOrder>0</sortOrder>
				<isDefault>false</isDefault>
				<label>HelloE472</label>
				<value/>
				<store_labels>
					<store_id>0</store_id>
					<label>HelloE472_0</label>
				</store_labels>
			</option>
		</def:catalogProductAttributeOptionManagementV1AddRequest>
	</soap:Body>
</soap:Envelope>`

With Magento 2.2.4 I am getting the error "Cannot save attribute %1". With Magento 2.2.0 I am getting response "true" but the option is not being created in Magento. See [here](https://github.com/magento/magento2/issues/16289)

**Comment by mhenkel1** [comment]
@magento-engcom-team Since you are unable to reproduce, please explain how you add an option with a hex code to an swatch attribute by using the rest api. YOU WILL NOT BE ABLE TO DO THIS, thats how you reproduce it. Next time please read the issue fully.

**Comment by shayzalman** [comment]
This is completely ridiculous!!
If the REST API is not supporting the creation of Visual Swatches with swatch options, you should write it down here!

**Comment by harperruss** [comment]
This has been reproduced on a vanilla 2.3.3 installation running the standard demo data/Luma theme:

**Steps to reproduce:**

1.  Create a new product attribute with a type of Visual Swatch
2.  POST a payload to **rest/V1/products/attributes/{attributecode}/options**

**Example Payload**
```
{
    "option": {
        "label": "Red",
        "is_default": "false",
        "sort_order": 0,
        "store_labels": [
            {
                "store_id": 1,
                "label": "Red"
            }
        ]
    }
}
```

3.  Check the contents of `eav_attribute_option_swatch` and observe a record is missing for the new attribute value
4.  Open the attribute in the admin and save which adds a record to `eav_attribute_option_swatch`

**Comment by duongnvk55** [comment]
Hi guys,
I tested this ticket on Magento Fresh 2.3 and found the problem of the issue. 
My solution: after saved option to attribute, we will need to get option_id and add to swatch attribute, like this : 
`private function saveSwatchValue(
        \Magento\Eav\Api\Data\AttributeOptionInterface $option,
        \Magento\Eav\Api\Data\AttributeInterface $attribute,
        string $optionLabel
    ){
        $optionId = $attribute->getSource()->getOptionId($optionLabel);
        if ($optionId) {
            $swatch['value'] = [$optionId => ''];
            $attribute->unsOption();
            $attribute->setSwatch($swatch);
            $attribute->save();
        } elseif (is_array($option->getStoreLabels())) {
            foreach ($option->getStoreLabels() as $label) {
                if ($optionId = $attribute->getSource()->getOptionId($label->getLabel())) {
                    $swatch['value'] = [$optionId => ''];
                    $attribute->unsOption();
                    $attribute->setSwatch($swatch);
                    $attribute->save();
                    break;
                }
            }
        }
    }`

**Comment by duongnvk55** [comment]
Hi guys,
I tested this ticket on Magento Fresh 2.3 and found the problem of the issue. 
My solution: after saved option to attribute, we will need to get option_id and add to swatch data, like this : 
1. Function add option to attribute

```
public function add($entityType, $attributeCode, $option)
    {
        if (empty($attributeCode)) {
            throw new InputException(__('The attribute code is empty. Enter the code and try again.'));
        }

        $attribute = $this->attributeRepository->get($entityType, $attributeCode);
        if (!$attribute->usesSource()) {
            throw new StateException(__('The "%1" attribute doesn\'t work with options.', $attributeCode));
        }

        $optionLabel = $option->getLabel();
        $optionId = $this->getOptionId($option);
        $options = [];
        $options['value'][$optionId][0] = $optionLabel;
        $options['order'][$optionId] = $option->getSortOrder();

        if (is_array($option->getStoreLabels())) {
            foreach ($option->getStoreLabels() as $label) {
                $options['value'][$optionId][$label->getStoreId()] = $label->getLabel();
            }
        }

        if ($option->getIsDefault()) {
            $attribute->setDefault([$optionId]);
        }

        $attribute->setOption($options);
        try {
            $this->resourceModel->save($attribute);
            if ($optionLabel && $attribute->getAttributeCode()) {
                $this->setOptionValue($option, $attribute, $optionLabel);
                if($this->swatchHelper->isSwatchAttribute($attribute)) {
                    $this->saveSwatchValue($option, $attribute, $optionLabel);
                }
            }
        } catch (\Exception $e) {
            throw new StateException(__('The "%1" attribute can\'t be saved.', $attributeCode));
        }

        return $this->getOptionId($option);
    }
```
2. function save option_id to swatch
```
private function saveSwatchValue(
        \Magento\Eav\Api\Data\AttributeOptionInterface $option,
        \Magento\Eav\Api\Data\AttributeInterface $attribute,
        string $optionLabel
    ){
        $optionId = $attribute->getSource()->getOptionId($optionLabel);
        if ($optionId) {
            $swatch['value'] = [$optionId => ''];
            $attribute->unsOption();
            $attribute->setSwatch($swatch);
            $attribute->save();
        } elseif (is_array($option->getStoreLabels())) {
            foreach ($option->getStoreLabels() as $label) {
                if ($optionId = $attribute->getSource()->getOptionId($label->getLabel())) {
                    $swatch['value'] = [$optionId => ''];
                    $attribute->unsOption();
                    $attribute->setSwatch($swatch);
                    $attribute->save();
                    break;
                }
            }
        }
    }
```

**Comment by engcom-Delta** [comment]
Hi @harperruss, thank you for your report. Unfortunately, I am not able to reproduce issue by steps you described on clean 2.4-develop.

**Manual testing scenario:**

- Create a new product attribute with a type of Visual Swatch.
![#10737issueSwathAdmin](https://user-images.githubusercontent.com/51681379/73652995-e5089000-4690-11ea-8f0a-e53356061c34.png)
![#10737issueSwatchDB](https://user-images.githubusercontent.com/51681379/73653002-e9cd4400-4690-11ea-8d73-a9879397472d.png) 
- POST a payload to rest/V1/products/attributes/{attributecode}/options
```
{
    "option": {
        "label": "red",
        "value": "#ff0000",
        "is_default": "false",
        "sort_order": 0,
        "store_labels": [
            {
                "store_id": 1,
                "label": "red default"
            }
        ]
    }
}
```

**Result:**
:heavy_check_mark: Color is added to Swatch on attribute edit page
![#10737issueResultAdmin](https://user-images.githubusercontent.com/51681379/73653261-7972f280-4691-11ea-912f-c70105b1f965.png)
![#10737issueResultDB](https://user-images.githubusercontent.com/51681379/73653267-7b3cb600-4691-11ea-8c93-1a0552b6bb6a.png)


Are you still facing this issue on the latest `2.4-develop` branch?

**Comment by harperruss** [comment]
@engcom-Delta If you don't send the "value" in the payload or try null or "" it will not create a record in eav_attribute_option_swatch.

We are using visual swatches but the image is coming from the swatch image attribute attached to the product not as a hex colour defined against the attribute:

{
    "option": {
        "label": "red",
        "is_default": "false",
        "sort_order": 0,
        "store_labels": [
            {
                "store_id": 1,
                "label": "red default"
            }
        ]
    }
}

Or

{
    "option": {
        "label": "red",
        "value": "",
        "is_default": "false",
        "sort_order": 0,
        "store_labels": [
            {
                "store_id": 1,
                "label": "red default"
            }
        ]
    }
}

Or

{
    "option": {
        "label": "red",
        "value": null,
        "is_default": "false",
        "sort_order": 0,
        "store_labels": [
            {
                "store_id": 1,
                "label": "red default"
            }
        ]
    }
}

**Comment by diazwatson** [comment]
@harperruss could reproduce the issue in `2.4-develop` branch?

**Comment by harperruss** [comment]
@diazwatson It looks like this has been fixed in 2.3.4

https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-4-open-source.html#swatches

**Comment by diazwatson** [comment]
@harperruss it looks like, although it does not mention the commit where this was fixed, so we cannot see what was the actual fix. Is it possible for you to test in 2.3.4?

**Comment by vincentteyssier** [comment]
@harperruss how do you attach the Swatch image to the option?
Do you need to pass the image path in value or the base64 image encoding?
I only manage to attach a color via the HEX value.

**Comment by harperruss** [comment]
@vincentteyssier No idea I'm afraid, it's not something I have needed to do

**Comment by vincentteyssier** [comment]
@harperruss if only they would have proper doc...

**Comment by diazwatson** [comment]
Guys I am closing this issue as it seems to be fixed. 
Please feel free to re open if you thing is needed.
