### ISSUE TITLE
Cybersource transaction type cannot be amended

### ISSUE THREAD

**Issue by TamasJozsefSzabo** [magento/magento2#10733]
### Preconditions

1. Magento 2.1.4
2. PHP 7.0.18
3. MySQL 5.6.33

### Steps to reproduce

1. Add product to cart 
2. Try to checkout
3. Connection refused as merchant does not allow subscriptions  to be created

### Expected result

1. Cybersource Module must allow the setting of transaction type
2. Transaction type must be "authorisation" instead of "create_subscription"
3. Payments are created as tokenised authorisation and NOT subscriptions
4. There must be the option to authorise and settle

### Actual result

1. Module creates subscriptions for every payment

**Comment by YevSent** [comment]
The public Github is only for CE version of Magento. To solve your problem, please, create a ticket via [EE support](https://account.magento.com/customer/account/login/), thanks, for your reporting.
