### ISSUE TITLE
Does not refresh shipping alternatives with MercadoEnvios

### ISSUE THREAD

**Issue by osrodolfo** [magento/magento2#10741]
### Preconditions

1. Magento ver. 2.1.7
2. Theme: VENUSTHEME

### Steps to reproduce

1. Add a product to cart
2. Go to checkout
3. Complete the fields one by one

### Expected result

1. The shipping alternatives(MercadoEnvios) should refresh when the fields are full

### Actual result

1. Does not refresh shipping alternatives
2. This shipping method is currently unavailable. - Must provide destination
![image](https://user-images.githubusercontent.com/14839677/29982203-1419d102-8f0e-11e7-9229-faae8ab5e67a.png)

**Comment by miguelbalparda** [comment]
@barbazul @fcapua-summa maybe you can help with this one? The issue probably belongs [here](https://github.com/mercadopago/cart-magento2).

**Comment by barbazul** [comment]
@mbalparda I haven't used MercadoEnvios in M2 yet so I can be of little help. Sorry

**Comment by barbazul** [comment]
@mbalparda I just noticed this is the M2 repo. Definitely should be moved to Mercadolibre repository.

**Comment by fooman** [comment]
@osrodolfo I'll close this issue here as this repository is for issue reports for Magento 2 only. Please take a look at the above link and report your issue there.
