### ISSUE TITLE
Terms and Conditions sort order if more than one

### ISSUE THREAD

**Issue by addison74** [magento/magento2#10746]
Create 3 Terms and Conditions for checkout process.  By default Magento is listing the terms one after other based on their ID's. 

As it is now the only way to re-position the terms is editing the database. Please allow this modification in Backend.

**Comment by miguelbalparda** [comment]
Hi @ADDISON74! This doesn't seem to be a bug. If you think this is a nice to have feature, feel free to open a thread in the official Magento forums. Also, I saw you opened other issues, please use the provided template.

**Comment by addison74** [comment]
It depends what you call a bug. In this case it is not normal to create Terms&Conditions and having no option changing their positions. For a normal user who uses only Backend it will be painful to edit the database. If you refer only to provided code by Magento Team it is not a bug, just a lack of functionality.

Thank you for pointing me to other places, but I will not report this for new feature. If anyone from Magento wants to hear what I reported this is the right place being achieved.
