### ISSUE TITLE
Links into [Find Partners & Extensions] section point to Magento Connect

### ISSUE THREAD

**Issue by addison74** [magento/magento2#10744]
Please visit in Backend [Find Partners & Extensions] section. Move your mouse over the links and check the URL's. All links point to Magento Connect which is wrong. When you click on [Visit Magento Marketplaces] button you should visit the Marketplace for Magento 2.

![marketplace](https://user-images.githubusercontent.com/8360474/29994458-756326dc-8fd8-11e7-8e9d-e09c0ce65f9e.jpg)

Magento Connect a resource for M1 extensions will be closed on September the 15th.

**Comment by vherasymenko** [comment]
@ADDISON74  thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by addison74** [comment]
Steps are already mentioned in my initial post. Here they are again:

1) Please visit in Magento 2.1.8 Backend [Find Partners & Extensions] section (see my image above).
2) Move your mouse over the links marked by red lines and check the URL's. 

ACTUAL RESULT
- All links point to Magento Connect (a Magento 1 resource) which is wrong because it closes on September the 15th.
- When you click on [Visit Magento Marketplaces] button you visit Magento Connect.

EXPECTED RESULT
- All links point to the new Marketplace.
- When you click on [Visit Magento Marketplaces] button you visit Marketplace website.

**Comment by korostii** [comment]
@ishakhsuvarov @naydav hey guys! 
Please excuse me for mentioning you directly, but this issue seems rather time-sensitive and I'm not sure whose responsibility this is.
Could you please take a look at this and maybe pass along to whomever appropriate if necessary?

I suspect that the old URL will have a redirect to the new marketplace installed anyway, but still: it's better to be safe than sorry.

**Comment by ishakhsuvarov** [comment]
Hey @korostii 
Looking for information regarding this one. I will update when I have details.
Thanks.

**Comment by ishakhsuvarov** [comment]
@korostii @ADDISON74 Some of the links mentioned already perform a 301 redirect, others will start redirecting on the September 15th so this should not be a major issue.
