### ISSUE TITLE
data migration magento 1.9.x to 2.1.3 - Exist customer can't login

### ISSUE THREAD

**Issue by ashvinim0003** [magento/magento2#10757]
#

### Preconditions

1. Apache
2. PHP 5.6

### Steps to reproduce

1.  Data migration from magento 1.9.x to magento 2.1.3
2.  Got error while importing customers ( error - Mage2CustomerEnttityText - Value cannot be blank)
3. All step completed

### Expected result

1. Sales , customer and products all data migrated to magento 2

### Actual result

1. All customer showing in admin after re-index.
2. Exist customer can't login even after password reset
3. Can't export all customers using  export tool
4. New customer login is working fine.
5. Found following error while exporting data from all customer section

1 exception(s):
Exception #0 (Exception): Notice: Undefined index:  in /public_html/beta/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php on line 135

Exception #0 (Exception): Notice: Undefined index:  in /public_html/beta/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php on line 135
#0 /public_html/beta/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php(135): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/...', 135, Array)
#1 /public_html/beta/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php(81): Magento\Customer\Ui\Component\DataProvider\Document->setWebsiteValue()
#2 /public_html/beta/vendor/magento/module-ui/Model/Export/MetadataProvider.php(159): Magento\Customer\Ui\Component\DataProvider\Document->getCustomAttribute('website_id')
#3 /public_html/beta/vendor/magento/module-ui/Model/Export/ConvertToCsv.php(84): Magento\Ui\Model\Export\MetadataProvider->getRowData(Object(Magento\Customer\Ui\Component\DataProvider\Document), Array, Array)
#4 /public_html/beta/vendor/magento/module-ui/Controller/Adminhtml/Export/GridToCsv.php(51): Magento\Ui\Model\Export\ConvertToCsv->getCsvFile()
#5 /public_html/beta/var/generation/Magento/Ui/Controller/Adminhtml/Export/GridToCsv/Interceptor.php(24): Magento\Ui\Controller\Adminhtml\Export\GridToCsv->execute()
#6 /public_html/beta/vendor/magento/framework/App/Action/Action.php(102): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->execute()
#7 /public_html/beta/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /public_html/beta/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /public_html/beta/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->___callParent('dispatch', Array)
#10 /public_html/beta/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor), Array, 'adminAuthentica...')
#11 /public_html/beta/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /public_html/beta/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /public_html/beta/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor), Array, 'adminMassaction...')
#14 /public_html/beta/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /public_html/beta/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /public_html/beta/var/generation/Magento/Ui/Controller/Adminhtml/Export/GridToCsv/Interceptor.php(39): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->___callPlugins('dispatch', Array, Array)
#17 /public_html/beta/vendor/magento/framework/App/FrontController.php(55): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /public_html/beta/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /public_html/beta/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#20 /public_html/beta/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#21 /public_html/beta/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /public_html/beta/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /public_html/beta/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /public_html/beta/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /public_html/beta/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#26 /public_html/beta/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#27 {main}

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by ashvinim0003** [comment]
Issue is fixed now. I have updated website_id,store_id for all customer using import tool in magento2.
@orlangur Thank you :)

**Comment by orlangur** [comment]
@ashvinimarwal glad to hear your problem is solved! And thank you for the recipe which worked in your case, it can be helpful to some googler.
