### ISSUE TITLE
 Product change error when saving gives = invalid input datetime format of value '10/10/+00201616'

### ISSUE THREAD

**Issue by kwindow** [magento/magento2#10756]
When trying to edit or add products I get the above error message on that product page when I click Save changes.

### Preconditions

1. Centos7 lamp   phph7   maria db
2. VPS 3gig ram 3 core  

### Steps to reproduce

1.  Open back office on store
2.  Open a  product or add a new product
3.  Click to save changes

### Expected result

1.  Product should save

### Actual result

1. Error as subject line in product page =  ' invalid input datetime format of value '10/10/+00201616''
 
![date time format error in products](https://user-images.githubusercontent.com/13122562/30002904-832d831e-90ac-11e7-8b64-59f0170b9018.jpg)
 nvalid input datetime format of value '10/10/+00201616'

I have cleared cache, tried different browsers, private brower etc I can't edit or add any products

**Comment by TomashKhamlai** [comment]
@kwindow, thank you for your report. Could you add additional information to **Preconditions** section about Magento and MariaDB versions?
**For example:** I am using Magento v2.1.8 and the output of `mysql -v` is
```
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
```

**Comment by kwindow** [comment]
Hi 


Thanks v much for your email,


I have magento 2.18 and have ‘fixed the issue’ by changing the locale to en-us from en-gb I gather other people have the same issue and I found this suggestion as a workaround.

 

Thanks  Kevin

**Comment by saivnct** [comment]
Hello, I got same issue after changing admin locale to vi_VN.
Could you show me how to  fix this issue. 
I'm using Magento-CE-2.1.9-2017-09-13-03-35-18
Thank you

<img width="1440" alt="screen shot 2017-10-26 at 22 12 05" src="https://user-images.githubusercontent.com/17584047/32061039-c221f90c-ba9a-11e7-807c-4c6e6e5ec88c.png">

**Comment by digvijay2017** [comment]
This issue still exists in Magento 2.2.1

**Comment by eTonki** [comment]
unfortunately there is still the problem,
how can they not notice it?

**Comment by TomashKhamlai** [comment]
Hello everyone! Not reproducible on 2.1.9 from Github without language pack

I cloned Magento from http://github.com/magento/magento2ce.git (branch 'tags/2.1.9') performed steps from the issue description and couldn't reproduce it. @saivnct, I changed locale to vi_VN, but there still nothing about this issue. You are probably using some language pack. Can you provide me a link to it?

There was a similar situation with language packs and the problem was in Magento, not in language pack, but it is hard to find the problem and debug it without a pack. We need proper steps to reproduce.

@digvijay2017, @eTonki, I will try later on 2.2.1. Can you tell something about your environment? Does it happen on VPS, shared hosting or local (vagrant, docker, native) environment? I would like to reproduce it.

**Comment by cs-media** [comment]
I'm also getting this error when saving a product. Only when the Interface Locale for the user account is set to United Kingdom.

My setup is Magento 2.2.1 (it was the same on 2.2.0), and not using composer. Running on shared hosting, centos 7.4, I've tried PHP (DSO) + mod_ruid2, suPHP and FPM/FastCGI. Also tried PHP v7.0.24 & v7.1.8. It's the same on all.

**Comment by eTonki** [comment]
@TomashKhamlai  
I do not remember if I'm using a language pack, it's been a long time, probably yes. If it can be useful, I can make screenshots on request. Let me know what you want to see (even with a private message).

**Comment by siliconalchemy** [comment]
Can anyone shed light on why this issue was closed, when it is clearly a major outstanding bug?

**Comment by TomashKhamlai** [comment]
### Preconditions:
Magento v2.1.10 installed

### Steps to reproduce:
1. Login to backend as admin
2. Go to **Account Settings**
3. Change **Interface Locale** to "English (United Kingdom)"
4. Create a Simple product and fill all the required fields
5. Click on datepicker and specify the current date in the **Set Product as New From** field
6. Click on datepicker and specify the future date in the **To** field
7. Save product

### Expected result:
Product is successfully saved

### Actual result:
error "Invalid input DateTime format of value 'dd/MM/+00yyyyYY'" appears, for example:
`Invalid input DateTime format of value '17/11/+00201717'`

**Comment by TomashKhamlai** [comment]
@kwindow, thank you for your report! Internal ticket [MAGETWO-84064](https://jira.corp.magento.com/browse/MAGETWO-84064) was created to address this issue.

**Comment by magento-engcom-team** [comment]
@kwindow, thank you for your report.
We've created internal ticket(s) MAGETWO-84064 to track progress on the issue.

**Comment by RWCC-LTD** [comment]
I had the same issue using a custom language pack for en_GB - I resolved this by changing the "interface Locale" under system> all users >**select user** from English (United Kingdom) to English (United States) 

This then resolved the issue and I can save dates in all forms from product special prices to custom date fields. This is a good workaround as when you deploy your site using en_gb it doesn't overwrite this admin setting

Hopefully this helps some people until a correct fix is put in place

**Comment by TomashKhamlai** [comment]
@sjhill-rwcc thank you for participating in the conversation. It is a good workaround while we are waiting for the fix.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
