### ISSUE TITLE
Cannot retrieve quote item from info_buyRequest in checkout_cart_add_product_complete event observer

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#10761]
Cannot retrieve quote item object from product info_buyRequest in 
observer for checkout_cart_add_product_complete event, if the product already exists in cart.

### Preconditions
1. An observer for checkout_cart_add_product_complete event.
2. Magento 2.1.x
3. PHP 7

### Steps to reproduce

1. Create an observer for checkout_cart_add_product_complete event.
2. Add a product to cart (quote item exists in info_buyRequest custom option)
3. Add the product to cart again
3. Try to get quote item from product's info_buyRequest custom option in observer created in point 1 => no quote item

### Expected result
1. Quote item should be available in product's info_buyRequest custom option, even if the product already exists in cart.

### Actual result
1. On subsequent add to cart, the info_buyRequest custom option is not properly initialized, so there is no quote item

I assume the problem lies in magento/module-quote/Model/Quote.php, in addProduct method. When the product is found in cart the custom options are not properly initialized:

            $item = $this->getItemByProduct($candidate);
            if (!$item) {
                $item = $this->itemProcessor->init($candidate, $request);
                //here the info_buyRequest contains the quote item 
                // Add only item that is not in quote already
                $this->addItem($item);
            }
            $items[] = $item;

I think this code should be moved from init method to prepare method in  magento/module-quote/Model/Quote/Item/Processor.php
`$item->setOptions($product->getCustomOptions());
            $item->setProduct($product);`

**Comment by boratek** [comment]
It is fixed in version 2.2.1
https://github.com/magento/magento2/blob/2.2.1-preview/app/code/Magento/Quote/Model/Quote.php

line 1623

**Comment by magento-engcom-team** [comment]
@theodorhanu thank you for your bug report.
We've created internal ticket MAGETWO-75333 to track progress on the issue

**Comment by ishakhsuvarov** [comment]
Hi @theodorhanu 
We are closing this issue for now, as the problem seems to be fixed in 2.2.1 onwards (refer to the comment above by @boratek).
Here is the updated link to the source:
https://github.com/magento/magento2/blob/321278b5027077b346e16ad4cac5407d65c918fd/app/code/Magento/Quote/Model/Quote.php#L1635

Thank you for collaboration
