### ISSUE TITLE
Admin Order Grid -> purschase date KO

### ISSUE THREAD

**Issue by zkliouel** [magento/magento2#10763]
hello,

we encouter an issue about purchase date that display wrong infos : 

In file : ./vendor/magento/module-sales/view/adminhtml/ui_component/sales_order_grid.xml
`<item name="dateFormat" xsi:type="string">MMM dd, YYYY, H:MM:SS A</item>`
display month instead of minute
it should be : 
` <item name="dateFormat" xsi:type="string">MMM dd, YYYY, H:mm:ss A</item>`

Regards

**Comment by TomashKhamlai** [comment]
Hello, @zkliouel! Thank you for your report. I checked with no success on Magento v2.1.8
**Preconditions:**
Magento v2.1.8 is installed
**Steps to reproduce:**
1. Go to Magento Root folder on your server.
2. Execute the command:
```
cat  ./vendor/magento/module-sales/view/adminhtml/ui_component/sales_order_grid.xml | grep -in '<item name="dateFormat" xsi:type="string">'
```
Result:
```
190:                    <item name="dateFormat" xsi:type="string">MMM dd, YYYY, H:mm:ss A</item>
```
Please use the issue reporting [guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by orlangur** [comment]
Was fixed in https://github.com/magento/magento2/commit/3a4fb597e380a66b561059b3d5f21509f46a9d30#diff-f13026afcc46259a8ef9e8bc19ccf79e

@zkliouel please make sure latest stable version (`2.1.8` in this case) is used prior to reporting a bug.
