### ISSUE TITLE
Delete Attribute Set is not Deleting  product url key in  url rewrite

### ISSUE THREAD

**Issue by pradeeprcs** [magento/magento2#10764]
### Preconditions

1.  Magento 2.1.7
2. With needed prerequisites.

### Steps to reproduce

1.  Create a new attribute set ex: testattset
2.  Create a product for the newly created attribute set (test as product so URL key also become test)
3.  Delete the newly created attribute set, in M2 soon after attribute set is deleted all related product of that attribute set also deleted that is test product also deleted 
4.  But when you try to create a product with the same name it will throw error "URL key for specified store already exists." because URL key of that product is not deleted 

### Expected result

1.  when attribute set is deleted  all the product of that attribute set and related URL key from URL rewrite should also be deleted and allow to create same product the second time also 

### Actual result

1. its throw error "URL key for specified store already exists."

**Comment by langowskiadam** [comment]
@langowskiadam

**Comment by magento-engcom-team** [comment]
@pradeeprcs thank you for your bug report.
We've created internal ticket MAGETWO-75301 to track progress on the issue

**Comment by denysbabenko** [comment]
I would like to work on this issue.

**Comment by sidolov** [comment]
Issue resolved in https://github.com/magento/magento2/pull/12167

**Comment by ishakhsuvarov** [comment]
Hi @pradeeprcs
We are closing this issue for now as the fix has been introduced in `2.2-develop` with Pull Request #12167
