### ISSUE TITLE
Error after pull

### ISSUE THREAD

**Issue by chrom** [magento/magento2#1077]
a:4:{i:0;s:67:"Class Magento\Backend\Model\Config\Backend\Encrypted does not exist";i:1;s:6430:"#0 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Backend...')
#1 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Backend...')
#2 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Backend...')
#3 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...', Array)
#4 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config/Data/ProcessorFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Backend...')
#5 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config/MetadataProcessor.php(85): Magento\Framework\App\Config\Data\ProcessorFactory->get('Magento\\Backend...')
#6 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config/Data.php(32): Magento\Framework\App\Config\MetadataProcessor->process(Array)
#7 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(97): Magento\Framework\App\Config\Data->__construct(Object(Magento\Framework\App\Config\MetadataProcessor), Array)
#8 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#9 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#10 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config/DataFactory.php(46): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#11 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config/ScopePool.php(88): Magento\Framework\App\Config\DataFactory->create(Array)
#12 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config.php(43): Magento\Framework\App\Config\ScopePool->getScope('default', NULL)
#13 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Request/Http.php(406): Magento\Framework\App\Config->getValue('web/secure/offl...', 'default')
#14 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/PageCache/Identifier.php(24): Magento\Framework\App\Request\Http->isSecure()
#15 /srv/www/htdocs/mage2/public/var/generation/Magento/Framework/App/PageCache/Identifier/Interceptor.php(43): Magento\Framework\App\PageCache\Identifier->__construct(Object(Magento\Framework\App\Request\Http))
#16 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(101): Magento\Framework\App\PageCache\Identifier\Interceptor->__construct(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Framework\Interception\PluginList\PluginList), Object(Magento\Framework\Interception\Chain\Chain), Object(Magento\Framework\App\Request\Http))
#17 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#18 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#19 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#20 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'identifier', 'Magento\\Framewo...')
#21 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#22 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#23 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#24 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'kernel', 'Magento\\PageCac...')
#25 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\PageCac...', Array, Array)
#26 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\PageCac...')
#27 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/Interception/PluginList/PluginList.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\PageCac...')
#28 /srv/www/htdocs/mage2/public/var/generation/Magento/Framework/App/FrontController/Interceptor.php(93): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Framewo...', 'front-controlle...')
#29 /srv/www/htdocs/mage2/public/var/generation/Magento/Framework/App/FrontController/Interceptor.php(119): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\Http->launch()
#32 /srv/www/htdocs/mage2/public/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#33 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}

**Comment by anupdugar** [comment]
@chrom Thanks for reporting the issue. 
Can you try clearing the contents of var/cache and var/generation?

**Comment by chrom** [comment]
Done. have new error:













a:4:{i:0;s:44:"Class Psr\Log\LoggerInterface does not exist";i:1;s:5335:"#0 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Store\\M...')
#1 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Store\\M...')
#2 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\M...', Array)
#3 /srv/www/htdocs/mage2/public/var/generation/Magento/Store/Model/Resource/Config/Collection/ScopedFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Store\\M...', Array)
#4 /srv/www/htdocs/mage2/public/app/code/Magento/Store/Model/Config/Reader/DefaultReader.php(53): Magento\Store\Model\Resource\Config\Collection\ScopedFactory->create(Array)
#5 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config/ScopePool.php(82): Magento\Store\Model\Config\Reader\DefaultReader->read()
#6 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Config.php(43): Magento\Framework\App\Config\ScopePool->getScope('default', NULL)
#7 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Request/Http.php(406): Magento\Framework\App\Config->getValue('web/secure/offl...', 'default')
#8 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/PageCache/Identifier.php(24): Magento\Framework\App\Request\Http->isSecure()
#9 /srv/www/htdocs/mage2/public/var/generation/Magento/Framework/App/PageCache/Identifier/Interceptor.php(43): Magento\Framework\App\PageCache\Identifier->__construct(Object(Magento\Framework\App\Request\Http))
#10 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(101): Magento\Framework\App\PageCache\Identifier\Interceptor->__construct(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Framework\Interception\PluginList\PluginList), Object(Magento\Framework\Interception\Chain\Chain), Object(Magento\Framework\App\Request\Http))
#11 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#12 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#13 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#14 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'identifier', 'Magento\\Framewo...')
#15 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#16 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#17 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#18 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'kernel', 'Magento\\PageCac...')
#19 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\PageCac...', Array, Array)
#20 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\PageCac...')
#21 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/Interception/PluginList/PluginList.php(234): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\PageCac...')
#22 /srv/www/htdocs/mage2/public/var/generation/Magento/Framework/App/FrontController/Interceptor.php(96): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Framewo...', 'front-controlle...')
#23 /srv/www/htdocs/mage2/public/var/generation/Magento/Framework/App/FrontController/Interceptor.php(122): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /srv/www/htdocs/mage2/public/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\Http->launch()
#26 /srv/www/htdocs/mage2/public/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#27 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}

**Comment by buskamuza** [comment]
@chrom , could you, please, clarify the use case? Does it happen on the new installation of Magento or is it after update to newer version?
If it's after update, did you run "composer install"?

**Comment by snohe** [comment]
@chrom, since we haven't heard back from you, we'll go ahead and close this issue.  Should you have any additional questions, please don't hesitate to open a new issue.
