### ISSUE TITLE
Unable to sort by store configuration default field when different to category's default sorting field

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10772]
One is unable to sort by store configuration default field when it differs from category default sort by setting. I found that the underlying issue lies within Magento\Catalog\Block\Product\ProductList::getWidgetOptionsJson() which uses the productListHelper to determine the 'orderDefault' setting, though that helper only returns the stores configuration value and doesn't take the default sorting field of the current category into account.

### Preconditions
1. Magento Version: 2.1.7
2. Make sure you have a category which has at least one product assigned to

### Steps to reproduce
1. In backend, go to Stores => Configuration => Catalog => Catalog
2. Make sure that within the tab "Storefront" the "Product Listing Sort By" is set to "Position". 
3. In backend, go to Products => Categories 
4. Go ahead and select a category to edit that has at least one product assigned to
5. Within "Display Settings" update the "Default Sort By" to be "Name" and save
6. In frontend, browse to the just changed category
7. Make sure that the default sorting is now by "Name"
8. Change that to sort by "Position"

### Expected result
1. The URL contains a query parameter which contains the desired sorting field "position"
2. The sorter select input displays "Position" as the current sorting field

### Actual result
1. The URL doesn't contain such a parameter.
2. The sorter select input displays "Name" as the current sorting field

**Comment by Linek** [comment]
@Linek

**Comment by magento-engcom-team** [comment]
@joachim-havloujian thank you for your bug report.
We've created internal ticket MAGETWO-75332 to track progress on the issue

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-75329

**Comment by larsroettig** [comment]
@okorshenko in which repo I can find the bugfix?  Than I can try to backport to 2.1.9

**Comment by okorshenko** [comment]
Hi @larsroettig here is a PR to backport: https://github.com/magento/magento2/pull/10937

**Comment by sunilit42** [comment]
Seems like it is fixed

**Comment by sunilit42** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@sunilit42 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sunilit42** [comment]
I have verified and its working fine with 2.2 branch

**Comment by sunilit42** [comment]
I have verified and its working fine with 2.2 branch

Proof :- https://www.screencast.com/t/ccogxeknw

**Comment by arshadpkm** [comment]
@sunilit42  Have you tested on Magento 2.1.7 ?
