### ISSUE TITLE
Custom options recreated every-time with edited options/values in Product form 

### ISSUE THREAD

**Issue by latypatil** [magento/magento2#10786]
If there are four custom options for xyz product and I will edit any 1 of them then it will recreate all four options newly for that product and deleted previous.

### Preconditions

1. Magento ver. 2.1.7
2. PHP 7.0.6, mysql  Ver 14.14

### Steps to reproduce

1. Add more than 1 custom options to product
2. Edit any option (add/remove values)
3. save the product

### Expected result

1. Custom options should be edited with previous option id in the table instead of creating new option id everytime

### Actual result

I changed one value for only 1 custom option but it create all of them again, please check below
1. [Screenshot, logs]
![customoptions_recreate](https://user-images.githubusercontent.com/31685324/30098363-4d015cfc-92ff-11e7-93b5-416af7a78875.png)
![customoptions](https://user-images.githubusercontent.com/31685324/30098364-4d0922f2-92ff-11e7-8e9a-5dff6e25fce3.png)

**Comment by astyczen** [comment]
@astyczen

**Comment by astyczen** [comment]
I checked on develop (2.3) and 2.2-develop branch and it is working as supposed. Checking on 2.1-develop branch.

**Comment by magento-engcom-team** [comment]
@latypatil, thank you for your report.
The issue is already fixed in 2.2.0
