### ISSUE TITLE
Tablerate calculation incorrect when removing products

### ISSUE THREAD

**Issue by bezigeboefjes** [magento/magento2#10781]
Tablerate is not calculated when removing products, with price rule.

I have configured tables rates: Weight vs. Destination. And I have a Cart price rule for free shipping above 45 euro.

- When a custom adds a product priced 30,-. -> Shipping 5 euro: Correct
- Then add a product for 20,-, -> Free shipping due to >45,- euro: Correct
- Remove one product, total cart below 45: Shipping: 3.95 euro: Wrong

Running Magento 2.1.7.

### Preconditions

1. Cart price rule: Condition: => 45 Action: Free shipping (free shipping above 45,- cart)
2. Table rate shipping: < 0.5kg : 3.95 euro ; > 0.5: 5.00 euro (Weight vs. Destination)

### Steps to reproduce

1. Add 1 product below 45 euro: shipping 5,-
2. Add another product, so total is > 45,-: Free shipping
3. Remove one product, total cart below 45,-: shipping 3.95

### Expected result

1. Shipping should be restored / recalculated to 5,- after removing products

### Actual result

1. Tablerate is not recalculated after removing products

Magento version 2.1.7

**Comment by magento-engcom-team** [comment]
@bezigeboefjes , thank you for your report.
The fix for this issue is already available on Magento 2.1.8 branch.
