### ISSUE TITLE
Unable to install magento 2.1.8 with modules which have Console commands

### ISSUE THREAD

**Issue by zhartaunik** [magento/magento2#10787]
Starting from Magento 2.1.8 unable to run setup:install without errors (Magento 2.1.7 is fine) when in folder app/code/... exist some extension which add console commands

### Preconditions
1. PHP 7.0.19
2. MySQL 5.7

### Steps to reproduce
1. Create (use existing) in folder app/code extension (adding module via composer most likely should help reproduce the issue) which has console commands.
2. Include into __construct e.g. this class **\Magento\Catalog\Model\Product\Gallery\GalleryManagement**
3. Run php bin/magento setup:install
(if you remove part of di.xml which refers to adding this console command setup will work properly)

### Expected result
1. Setup should work properly

### Actual result
1.  On 4th step you should see following issue:
 [Zend_Db_Statement_Exception]                                                                                                                                                  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.core_config_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config_data` AS `main_table` 

Working solution is to use factories. e.g. **\Magento\Catalog\Model\Product\Gallery\GalleryManagementFactory**

**Comment by larsroettig** [comment]
Hi @zhartaunik, I update also to 2.1.8 and I can not reproduce this issue. We have many modules with console commands and we install also over composer 

best regards 

Lars 

---------
Community Member - Community Engineering Team Magento

**Comment by mhauri** [comment]
We had the same issue with one of our modules. Try either to use the Interface `\Magento\Catalog\Api\ProductAttributeMediaGalleryManagementInterface` or the Factory `\Magento\Catalog\Model\Product\Gallery\GalleryManagementFactory`

**Comment by magento-engcom-team** [comment]
@zhartaunik , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.

**Comment by agata-maksymiuk** [comment]
For those who came here from google as me - solution:

1. I checked out first commit in my project repository (to back to pure Magento with no modules at all)
2. Ran install command
3. Checked back current commit, then enable module, upgrade and so on :)
