### ISSUE TITLE
Admin language interface change?

### ISSUE THREAD

**Issue by arvind2285** [magento/magento2#10788]
I can change admin language interface from Account Setting(admin)-> Interface Locale, but language doesn't change.
I am using Magento ver. 2.1.6 in my store.

Thanks,
Arvind

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
Hi @arvind2285 
Please make sure that you installed the language pack. Magento supports only en-US out-of-the -box.
Also, do not forget clean caches.

**Comment by magento-engcom-team** [comment]
Also, you can ask your questions here: https://community.magento.com/
