### ISSUE TITLE
CE2.18 PayPal All-in-One incorrectly marking Status as Complete

### ISSUE THREAD

**Issue by deckside** [magento/magento2#10798]
### Preconditions

After upgrading from CE2.17 to CE2.18 
When a new order is received and paid via PayPal All-in-One Payment Solution, the order has the Status "Complete". When it should be processing as we have not interacted with the order as yet.

The only changes made was the CE2.17 to CE2.18  upgrade

### Steps to reproduce
Upgrade for CE2.17 to CE2.18
As a customer place an order via the front end and pay via PayPal
View order in admin >Sales 

### Actual Result
Check Status and it is set as "COMPLETE"

### Expected result
As a customer place an order via the front end and pay via PayPal
View order in admin >Sales 
Check Status and it is should be set to "PROCESSING"

Additional Information:
If an order is received from eBay via M2E Pro and has been paid the status is correctly set as "PROCESSING"

**Comment by vherasymenko** [comment]
@deckside , thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by deckside** [comment]
Details have been updated

**Comment by deckside** [comment]
Update:
This seems to have fixed itself.

**Comment by magento-engcom-team** [comment]
thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
