### ISSUE TITLE
Is it possible to 'bulk' import customers with REST?

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1079]
I'm investigating Magento2 at the moment and I think the new service oriented architecture is awesome. But I have a question..

I managed to add a customer through the REST layer (/rest/V1/customers) with this json:
{
    "customer": {
      "firstname": "James",
      "lastname": "Page",
      "email": "jp@example.com"
    }
}

But we want to sync our data between a custom database and Magento. Is there a way to offer a bunch of customers? Like an array?

And the same for modified customers for example, is it possible to send an array (with ID's) which will cause an update for those customers?

Same question for products, probably much more important too..

**Comment by choukalos** [comment]
Hi @rklerck right now we only support single object calls for CRUD, and a multi object Search feature.  So to push customers & products in you'll need to loop.  If you want to read multiple objects from customer or product use the search feature.  In particular you can search on an updated_at time stamp to see differences ( say poll every 15 minutes ) and page through the results ( if there are a ton of returned objects ).  I haven't updated this in a while but check out the .md files they should point you in the right direction [link|https://github.com/choukalos/M2_Api_Example_Scripts]

customer search should be GET V1/customers/search and product search should be GET V1/products ; our API team will address those url inconsistencies in a couple weeks.

How many customers/products do you need to move?  How often would they update/change (% of catalog changing)?  Do you have a window when all the changes need to be made?

Thanks!

**Comment by alankent** [comment]
What may also be a useful technique in some cases is to develop your own module with a custom api. That is, it would not be much code to write a function that took an array of customer objects and called the insert one-at-a-time function. You could then decide what action your code wants to take on error for example.

This does not mean don't ask us - if something commonly wanted then we should add it. But a goal was also to make it easy for external parties to add their own APIs easily for custom use cases. Eg for syncing do you want to send an action and time stamp per customer instance as well?

**Comment by rklerck** [comment]
Are there any examples on how create a custom API?

I don't know the exact number yet, but I need to know all of our options before proceeding. A timestamp is not really necessary

**Comment by choukalos** [comment]
To create your own custom API you'd create a service then configure the service to be exposed as an external web api.  This isn't documented / we don't have examples at present but hope to release those shortly.  If you want to get started earlier you can look at the customer module.  Look in the API folder ( those are the services that are defined; dig around a little and you should find the classes that are created and which ones we inherit from to get the service framework features  ) then in the etc/webapi.xml file to see how that defined service is exposed as a web api.

**Comment by choukalos** [comment]
Closing question;  Note we're tracking this as a potential feature or an FTP file based API for very large transfers.
