### ISSUE TITLE
Category selection under Catalog price rules conditions section not saving data

### ISSUE THREAD

**Issue by robgt** [magento/magento2#10794]
### Preconditions

1.  Magento 2.1.6
2. PHP 7
3. MySQL Ver 14.14 Distrib 5.6.36-82.1, for Linux (x86_64) using  6.2

### Steps to reproduce

1. Edit a catalog price rule
2. Expand the conditions section
3. Tick some category boxes
4. Click save

### Expected result

1. Boxes that have been ticked, should remain ticked
2. Category ID number list above the category tree should be updated with additional category ID numbers

### Actual result

1. Admin reports that the rule has been saved
2. Inspecting the same rule shows no changes were made to the rule - no new ID numbers in the list, and no new boxes ticked in the category tree.

**Comment by magento-engcom-team** [comment]
@robgt , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.

**Comment by congaframe** [comment]
Hi, 
Can you please re-open this issue ? 
or at least give us the PR/commits that fixes this in 2.2 ? 
I seem to have the same issue in 2.1.5 - under the tab Action: 
"Apply the rule only to cart items matching the following conditions (leave blank for all items)."
All conditions are removed after saving.

**Comment by PierreLeMaguer** [comment]
This issue was fixed here : [https://github.com/magento/magento2/pull/10094](https://github.com/magento/magento2/pull/10094)
