### ISSUE TITLE
Shipping method radios have duplicate IDs on cart page

### ISSUE THREAD

**Issue by wsajosh** [magento/magento2#10795]
### Preconditions

1. Magento CE v2.1 installed

### Steps to reproduce
1. Can't reproduce using core Magento shipping carriers. Need two shipping carriers with different carrier codes but same method codes. 

E.g: UPS with GND and 1DA and UPS_1 with GND and 1DA

### Expected result
1. Should be able to select Ground from either carrier

### Actual result
1. Clicking on the first Ground

Issue would appear to lie in: vendor/magento/module-checkout/view/frontend/web/template/cart/shipping-rates.html

The id of the radio is being set to 's_method_' + method_code whereas which would for the above scenario would result in two radio elements both with the ID of "s_method_GND"

However, in the checkout/shipping.html file there's a check to see if there's other rates, and if there is the ID is set to 's_method_' + method.carrier_code + '_' + method.method_code which works correctly.

The fix would be to implement the same logic on the cart estimator

**Comment by orlangur** [comment]
Implementation approach looks good to me, are you interested in preparing a pull request maybe?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81830

**Comment by okorshenko** [comment]
Hi @wsajosh the issue has been fixed in 2.2-develop branch and will be available in 2.2.2 release

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81975

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81976
