### ISSUE TITLE
Scrolling X Axis, Menu items disappear out of viewport [NOT URGENT] just a design flaw

### ISSUE THREAD

**Issue by hudson1998x** [magento/magento2#10809]
### Preconditions

1.  Magento Version 2.1.8
2.  Chrome 60 on Windows 8.1 (Window width 961px and less, height irrelevant) 
3,  PHP 7

### Steps to reproduce

1.  Follow the instructions above really.

### Expected result

1. The Whole menu should scroll across the X axis

### Actual result

1. Only the background container of the menu moves , the links in the same position

**Comment by magento-engcom-team** [comment]
@hudson1998x  thank you for your bug report. We cannot reproduce this issue as described. 
Please provide the detailed steps we must follow to reproduce this issue.  Please give screenshot, that shows which exactly menu items disappear out of viewport

**Comment by hudson1998x** [comment]
The problem seems to have been fixed, it was due to file permissions stopping a JS file loading. causing errors on the page.

**Comment by magento-engcom-team** [comment]
@hudson1998x Thanks for the feedback.

**Comment by magento-engcom-team** [comment]
@hudson1998x, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
