### ISSUE TITLE
When canceling order with OrderService, the cancel method always saves the order and returns true, even if the order can not be canceled.

### ISSUE THREAD

**Issue by ekuusela** [magento/magento2#10803]
I'm assuming the cancel method in OrderService is supposed to return true only if the cancellation was a success. 

https://github.com/magento/magento2/blob/5973d671fae91b0cde83b43777fff34848880d82/app/code/Magento/Sales/Model/Service/OrderService.php#L87

But, since the cancel method in Order always returns the order itself, the service method ends up always saving and returning true as if the order was cancelled.

https://github.com/magento/magento2/blob/5973d671fae91b0cde83b43777fff34848880d82/app/code/Magento/Sales/Model/Order.php#L1112

This is confusing if not broken. The meaning of the boolean return value should be documented and if it is indeed meant as an indicator of successful cancelation, the service method should be fixed.

I'll include the boilerplate below to prevent this issue from getting auto-marked as not helpful.

### Preconditions
1. Fresh Magento 2 version (see links to functions in develop branch above)

### Steps to reproduce
1. Look at phpdoc in OrderService's cancel method and try to understand it's return value.

### Expected result
1. A clear understanding of the return value AND
2. Return value corresponding to reality, for example, true only if order was canceled.

### Actual result
1. Confusion. Looks like the return value might indicate cancelation success, but it does not.

**Comment by magento-engcom-team** [comment]
Hi @ekuusela 
Could you please create a Pull Request for this issue?

**Comment by freakphp** [comment]
@freakphp

**Comment by magento-engcom-team** [comment]
@ekuusela  thank you for your bug report.
We've created internal ticket MAGETWO-75370 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-75327

**Comment by strell** [comment]
I would like to work on this issue

**Comment by okorshenko** [comment]
@ekuusela thank you for your report. The issue is already fixed in 2.2-develop branch (PR: #11160 by @strell) and will be available in the Magento 2.2.2 release
