### ISSUE TITLE
USPS First-Class Package Service – Retail

### ISSUE THREAD

**Issue by joebusby** [magento/magento2#10800]
### Preconditions
Magento 2.1.8
On Debian 8 LXC container 4GB ram 6 cores PHP 7.0.10-1~dotdeb+8.1

### Steps to reproduce
Configure the USPS shipping method and add First-Class Mail Parcel to the selected list of enabled services.

### Expected result
Customer ordering 14 or less ounces of product should see a First Class Parcel option.

### Actual result
No option for First Class parcel, but the other shipping methods work. (maybe not priority international)

According to WebShopApps,  

http://blog.shipperhq.com/2017/09/usps-api-changes-sept-1st-2017/

USPS on September 1st 2017  has changed their ‘First-Class Mail Parcel” Service to “First-Class Package Service – Retail”.

The 'First-Class Mail Parcel" option is no longer appearing since the USPS name change and price increase.

Please provide a code change or help me understand where I went wrong to allow Magento2 to capture the new service instead of the old one so our customers don't pay double to get "Priority Mail" for no benefit to them.

Thanks for any help on this!

**Comment by YevSent** [comment]
Hi, @joebusby, thanks for reporting. This is known issue (internal ticket `MAGETWO-72305`) and now we are preparing PR to deliver the fix. Also, the fix will be available for Magento 2.1.9.

**Comment by YevSent** [comment]
Merged into `2.2-preview` branch. The internal ticket `MAGETWO-72306` for 2.1.9 release.
