### ISSUE TITLE
htaccess Options override

### ISSUE THREAD

**Issue by s3rj1k** [magento/magento2#10812]
In shared hosting environment 

`Options All -Indexes`

would render 500 error page because of high restrictions for Options override

we should use instead

`Options -Indexes`

**Comment by miguelbalparda** [comment]
It might be faster to create a PR with all the changes instead of waiting for these issues you just created to be processed.

**Comment by TomashKhamlai** [comment]
@s3rj1k, thank you for reporting this issue. Please use the issue reporting guidelines to report an issue. Include the steps required to reproduce, the actual result, and the expected result. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by magento-engcom-team** [comment]
@s3rj1k, thank you for your report.
We've created internal ticket(s) MAGETWO-80865 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @s3rj1k. Thank you for your report. 
The issue has been fixed in magento/magento2#12959 by @dverkade in 2.1-develop branch
Related commit(s):
 - 704960a6a1af41c95e9e1c90b11016426ab5d5b5

The fix will be available with the upcoming patch release.
