### ISSUE TITLE
Replace FollowSymLinks with SymLinksIfOwnerMatch

### ISSUE THREAD

**Issue by s3rj1k** [magento/magento2#10811]
In htaccess templates we should use more save from security view symlink command - `SymLinksIfOwnerMatch`

**Comment by avoelkl** [comment]
cc @piotrekkaminski

**Comment by TomashKhamlai** [comment]
@s3rj1k, thank you for your report.
Please use the issue reporting guidelines to report an issue. Include the steps required to reproduce, the actual result, and the expected result. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by magento-engcom-team** [comment]
@s3rj1k, thank you for your report.
We've created internal ticket(s) MAGETWO-80632 to track progress on the issue.

**Comment by sylvainraye** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @s3rj1k. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1287 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
