### ISSUE TITLE
Magento 2.1.0 reads wrong php.ini file

### ISSUE THREAD

**Issue by sky4git** [magento/magento2#10816]
I have searched & tried everything before submitting this issue. I am not sure now that this issue with Magento 2.1.0 or with my server. May be community will help.

### Preconditions
1.  Installed Magento 2.1.0

### Steps to reproduce
**1. Preface**
I have successfully upgraded php version to php 7.0 on my staging server. My local Magento 2.1.0 recognise the new PHP 7.0 version via phpinfo(); Please check the attached screenshot.
![image](https://user-images.githubusercontent.com/8438024/30192675-396248a8-948c-11e7-9133-26a62af246d1.png)

My command line shows the  same version with php -v
![image](https://user-images.githubusercontent.com/8438024/30192042-29e978fa-9488-11e7-9c66-3daaa294fb5b.png)

At this point we can assume that Magento is running on PHP 7.0 and Loaded configuration file is /**etc/php/7.0/apache2/php.ini**

**2. Web Setup Wizard** 
Please go up to **Readiness check** You will see in screenshot everything is ok and Memory limit is 770M
![image](https://user-images.githubusercontent.com/8438024/30192130-da3b6358-9488-11e7-94e1-d89fc128ebc4.png)

**3. The Issue**
My memory limit shown in **Readiness check** is coming from different php.ini(**/etc/php5/apache2/php.ini**) file which Magento is not using normally. 
![image](https://user-images.githubusercontent.com/8438024/30192411-f049174c-948a-11e7-8ba4-3cb4386da1eb.png)

### Expected result
1.  Web Setup Wizard  **Readiness check**  should show/read memory_limit from loaded php.ini configuration file (in my case /etc/php/7.0/apache2/php.ini) and display memory_limit 756M

### Actual result
1.  Web Setup Wizard  **Readiness check**  is showing/reading memory_limit from old php.ini configuration file (in my case /etc/php5/apache2/php.ini) and displays memory_limit 770M

If  anyone have came across this issue please help me to load the memory limit from the correct configuration file.  I am not sure its a bug in Magento 2.1.0 or some server level issue.

**Comment by klein0r** [comment]
This must be a server related / configuration issue since magento can't decide which php.ini / configuration file should be used.

**Comment by orlangur** [comment]
This is definitely not a Magento issue but server misconfiguration. Most likely some Apache configs where not changed accordingly within php5 -> php7 upgrade.

If you add `phpinfo();` call at the "Web Setup Wizard" you'll see wrong `php.ini` in the list of loaded configuration files.

**Comment by magento-engcom-team** [comment]
Thank you @orlangur for investigation of the issue. Your point is valid. Closing the issue as non-magento issue.

**Comment by sky4git** [comment]
Apparently, even on /setup (Web Setup wizard) url. `phpinfo()` shows the same php.ini file loaded
![image](https://user-images.githubusercontent.com/8438024/30254204-428506f2-96d8-11e7-94b3-156400f4eb68.png)

I have double checked the .htaccess file in root folder as well as in **/setup** folder. But, there is definitely no memory limit like 770M except in **/etc/php5/apache2/php.ini**

Also, I can confirm that php5 mode is disabled in Apache2.
![image](https://user-images.githubusercontent.com/8438024/30254267-1ce14360-96d9-11e7-9b9c-e9d10698acbf.png)

I have also tried updating memory limit in **/etc/php5/apache2/php.ini** 
![image](https://user-images.githubusercontent.com/8438024/30255745-2168608e-96e9-11e7-9130-302a4e788879.png)

Which is reflecting in setup wizard again
![image](https://user-images.githubusercontent.com/8438024/30255795-669a3ff6-96e9-11e7-97cf-cb4d5f6af9f7.png)

I think when MAGENTO_DIR/setup/src/Magento/Model/PhpReadinesscheck > checkMemoryLimit() reads 
memory_limit  `$currentMemoryLimit = ini_get('memory_limit');` It reads from wrong location.

**Comment by orlangur** [comment]
@sky4git try changing this value and investigate a bit more.

`$currentMemoryLimit = ini_get('memory_limit');` `ini_get` is a PHP builtin function, it just gets value from loaded `php.ini`, the one you see in `phpinfo`.

Try searching "memory_limit" on `phpinfo` and you'll see the same value displayed by Magento.

**Comment by sky4git** [comment]
See the following screenshot. Its definitely different. 
![image](https://user-images.githubusercontent.com/8438024/30261649-08ebfa7a-9711-11e7-973a-b48f7d85a936.png)

**Comment by orlangur** [comment]
In normal system setup changing memory limit is as simple as: http://devdocs.magento.com/guides/v2.1/install-gde/trouble/php/tshoot_php-set.html#trouble-php-memory.

As I said earlier, you need to call `phpinfo` right here: https://github.com/magento/magento2/blob/2.1/setup/src/Magento/Setup/Model/PhpReadinessCheck.php#L192

It looks like you have multiple `.ini` files overriding `memory_limit` value loaded. Various topics like https://drupal.stackexchange.com/questions/90090/increasing-php-memory-limit-possible-drupal-override end up like this after all.
