### ISSUE TITLE
Unable to import multiselect attributes with multiple values (import-export)

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#10819]
### Preconditions
1. Install Magento 2.1.8

### Steps to reproduce
1. Import categories with import models (import-export) and import an attribute with type multiselect
2. Set multiple values (separated with delimiter) e.g. available_sort_by = "price,name"

### Expected result
1. Both values are imported

### Actual result
1. It is not possible to import multiple values for a multiselect attribute due to the following code

vendor/magento/module-import-export/Model/Import/AbstractEntity.php:660 (isAttributeValid)

```
            case 'select':
            case 'multiselect':
                $valid = isset($attributeParams['options'][strtolower($rowData[$attributeCode])]);
                $message = self::ERROR_INVALID_ATTRIBUTE_OPTION;
                break;
```

A multiselect must be handled in a different way and not like a simple select (explode at a given seperator). Otherwise the value is not found in the option array and the attribute is marked as invalid.

**Comment by klein0r** [comment]
Sorry, just checked the 2.2 code and it seems like this issue has already been fixed.

https://github.com/magento/magento2/blob/2.2/app/code/Magento/ImportExport/Model/Import/AbstractEntity.php#L695

**Comment by xi-ao** [comment]
I still have an issue with multivalued attributes on products, and it seems to make sense when I look at https://github.com/magento/magento2/blob/f3f8975c3f48ad8d2a3221153bcce9f82a5b84b8/app/code/Magento/ImportExport/Model/Import/Entity/AbstractEntity.php#L656

**Edit:** nevermind, this method is overridden for products and uses a correct validator instead. My problem must be lying somewhere else.

**Comment by cenobitz** [comment]
> 
> 
> I still have an issue with multivalued attributes on products, and it seems to make sense when I look at
> 
> https://github.com/magento/magento2/blob/f3f8975c3f48ad8d2a3221153bcce9f82a5b84b8/app/code/Magento/ImportExport/Model/Import/Entity/AbstractEntity.php#L656
> 
> **Edit:** nevermind, this method is overridden for products and uses a correct validator instead. My problem must be lying somewhere else.

Has anyone managed to import CSV multiselect attributes to Magento 2.3/2.5? The funny thing is that when I export from Magento fully setuped product with attributes (multiselect) one or more no matter... and import the same file attributes are not imported. Also tried simple 2 columns CSV sku,additional_attributes without success. Am I blind?
