### ISSUE TITLE
Braintree integration

### ISSUE THREAD

**Issue by cckassis** [magento/magento2#10813]
Hi There,
I have recently installed Braintree as a payment gateway and I am currently testing it. When I ran a test transaction on the website (mosaicslab.com) a generic "server error" occurred when attempting to place the order. When I looked into the server logs for the account I did not see any transaction activity. I am not sure if this is a server issue, shopping cart issue or payment gateway issue. Currently, orders are being dropped.
Another issue I ran into when i integrated the payment gateway onto the website, the styling of the review page of checkout got completely messed up. The way it currently looks, i bet the page drop off is 100%.

Your help is highly appreciated. 
Thanks a lot,
Chad

**Comment by avoelkl** [comment]
Hi @cckassis,
Please follow the reporting guidelines when reporting issues here: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

Please add some more information such as:
* Preconditions (Magento Version, PHP Version, Environment,...)
* Steps to reproduce
* Actual and Expected result

Thanks!

**Comment by kervin** [comment]
I have the same issue.

It's this bug:

https://github.com/magento/magento2/issues/6929

**Comment by magento-engcom-team** [comment]
@cckassis Closing as duplicate of #6929 
Please reopen if you think this is a different issue.
