### ISSUE TITLE
Cannot add new columns to item grid in admin sales_order_view layout

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#10824]
I am trying to add a new column to item grid in admin sales/order/view .
The problem is that in the layout the default renderer does not have a **_name_** attribute, only the **_as_** attribute, thus not allowing to add new column content. Even though I can add new column headers to the layout, using `<referenceBlock name="order_items">` directive, I cannot add the column's content using the same aproach.
### Preconditions
1. Magento 2.1.x

### Steps to reproduce
1. Create sales_order_view.xml in custom module's adminhtml layouts folder
2. Add a column in order_items arguments:
```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="order_items">
            <arguments>
                <argument name="columns" xsi:type="array">
                    <item name="test_column" xsi:type="string" translate="true">Test Header</item>
                </argument>
            </arguments>
            <block class="Namespace\Vendor\Block\Adminhtml\Order\Items\Column\TestColumn" name="column_production_id" template="Namespace_Vendor::order/items/column/test_column.phtml" group="column" />
        </referenceBlock>
    </body>
</page>
```

### Expected result
1. Column content should be displayed according to test_column.phtml

### Actual result
1. Only column headers are added

There should be posibility to add cell renderer using `<referenceBlock name="default">` directive, like column addition.
The only solution I find is adding an afterGetColumns plugin to _Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer_, solutions which does not seem so elegant to me.

**Comment by hatimeria-artur-jewula** [comment]
I am working on it

**Comment by Zefiryn** [comment]
I am working on it

**Comment by magento-engcom-team** [comment]
@theodorhanu thank you for your bug report.
We've created internal ticket MAGETWO-75303 to track progress on the issue

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-75321

**Comment by hervebackstage** [comment]
I can give a go at this one

**Comment by hatimeria-artur-jewula** [comment]
It's already fixed and merged into develop branch

**Comment by okorshenko** [comment]
@hervebackstage  it would be great to backport this fix to 2.2-develop branch

**Comment by hatimeria-artur-jewula** [comment]
@hervebackstage you can also try to find all places with missing name and add test to make sure no new blocks like that are added.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80102

**Comment by okorshenko** [comment]
Hi @theodorhanu the issue has been fixed in #11076 and will be available in 2.2.1

**Comment by pptyasar** [comment]
How to make as first column in table @theodorhanu

**Comment by VadimLugovoy** [comment]
> How to make as first column in table @theodorhanu

Does it possible to set position of the adding custom column?

**Comment by theodorhanu** [comment]
It should be possible by adding an afterGetColumns plugin for these two classes 
_Magento\Sales\Block\Adminhtml\Order\View\Items_ and _Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer_ and reorder columns based on your needs.

In plugin you can add something like this (should be same for both plugins, only injected class  should be changed ):
Add this to _app/code/Vendor/Module/etc/adminhtml/di.xml_ file:
```
<type name="Magento\Sales\Block\Adminhtml\Order\View\Items">
        <plugin sortOrder="1" name="printqCoreItems" type="Vendor\Module\Plugin\Block\Adminhtml\Order\View\ItemsPlugin" />
    </type>
```

_file: app/code/Vendor/Module/Plugin/Block/Adminhtml/Order/View/ItemPlugin.php:_
```
<?php
/**
 * @author 		Theodor Flavian Hanu
 */
namespace Vendor\Module\Plugin\Block\Adminhtml\Order\View;

class ItemsPlugin
{
    public function afterGetColumns(\Magento\Sales\Block\Adminhtml\Order\View\Items $subject, $result) {
        
        $result = uasort($result, function($a, $b){
            //if($a matches condition) return -1;
            //if($b matches condition ) return 1;
            //otherwise keep original order
            return 0;
        });
        return $result;
    }
}
```
