### ISSUE TITLE
Payment fails for "virtual" product (or that with no weight) when there is no shipping address

### ISSUE THREAD

**Issue by timbaker1991** [magento/magento2#10825]
### Preconditions
1. Magento 2.1.7 (also tested on 2.1.8 but not as extensively)
2. PHP 7.0.7
3. Using Braintree to checkout (though it may not be limited to this, I've just been unable to test with anything else)
4. Have products with virtual weight 
5. Have customer with no default shipping or billing address (or checkout as guest with no address)
6. I have tested this with our own theme which is heavily customised and with the vanilla Luma theme

### Steps to reproduce
1. Add a virtual product - or a product with no weight - to the basket
2. Continue through to the checkout, if you are logged in make sure you do not have default addresses set up and do not enter a billing address
3. Attempt to pay using card details(1). I have attempted this with the Braintree module included in Magento

### Expected result
1. The payment should go through successfully without an address, or if it must be required form validation should be improved - or at the very least tell them an address is required

### Actual result

4. You receive the message "An error occured on the server. Please try to place the order again"

My Braintree account does not require any shipping information and speaking to them it does not get to that stage anyway. I debugged by putting a breakpoint on [savePaymentInformationAndPlaceOrder](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L83) and got an error telling me the address details we required. That sort of makes sense, but the error message needs to be improved to the user; and also the validation of the form should force them to enter a billing address if it is required (though, and I can't stress this enough, it should be configurable if billing address is required).

Where it becomes odd: 
5: Set a default billing address and the problem still happens
6: Set a default shipping address and the problem resolves. A default shipping address should not be needed to complete payment for a virtual product

Further notes:
(1) - PayPal integration explicitly gives you the option to not require a billing address and so works

There's obviously a lot of similar bug reports like this, and even if the error messages are made more explicit I think a lot of the immediate issues would be helped.
https://github.com/magento/magento2/issues/8488

**Comment by YevSent** [comment]
Hi, @timbaker1991, I've checked the flow on Magento 2.1.8 and the flow is not same as you described:

> Continue through to the checkout, if you are logged in make sure you do not have default addresses set up and *do not enter a billing address*

A customer cannot skip the billing address form with billing address if billing address wasn't set (justly for a guest and registered customer) and this form is always expanded, so the customer will see all required fields.
![braintree](https://user-images.githubusercontent.com/2736528/30263094-4105dd3e-96dc-11e7-9e95-f4c413cff1ff.png)

> it should be configurable if billing address is required

In most cases, a billing address is required, some exceptions like PayPal because the customer already assigned their payment card with all needed details to PayPal account.

> 5: Set a default billing address and the problem still happens

With billing address, an order was placed successfully for a virtual product without shipping.

> 6: Set a default shipping address and the problem resolves. A default shipping address should not be needed to complete payment for a virtual product

Checkout with a virtual product does not require a shipping address (checked with Braintree, Braintree PayPal, PayPal Payflow Pro on Magento 2.1.8).

**Comment by wildrness** [comment]
Same issue happening on our install, and help on this matter appreciated

**Comment by magento-engcom-team** [comment]
@timbaker1991, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by mangamuri** [comment]
We are having this issue in 2.1.5, we are calling  Order API , any help here is appreciated

**Comment by Kronmose** [comment]
We have the same issue.
