### ISSUE TITLE
Customizable Options only show frontend after resave product 

### ISSUE THREAD

**Issue by Dregolwd** [magento/magento2#10827]
After update from Magento 2.1.6 to 2.1.8, the customizable options are not shown in the frontend. 

### Preconditions
1. Magento 2.1.8
2. PHP 7.0.21

### Steps to reproduce
1. Add product in Magento 2.1.6
2. Add Customizable Options 
3. Upgrade to Magento 2.1.8

### Expected result
1. Show custom options in frontend

### Actual result
1. Display no custom options in frontend

Only after resaving the product the custom options are showing.

**Comment by Andrii-Deineha** [comment]
Hi @Dregolwd, Thanks for reporting this issue. Unfortunately, I could not reproduce the issue as you described it. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by magento-engcom-team** [comment]
@Dregolwd Unfortunately, I could not reproduce the issue as you described it.
Please provide more information if the issue exists

**Comment by magento-engcom-team** [comment]
@Dregolwd, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
