### ISSUE TITLE
How to install magento 2.1.3 theme

### ISSUE THREAD

**Issue by mataheri** [magento/magento2#10833]
I am new to magento 2.
Could you please tell me how to install magento 2.1.3 theme via composer or manually and what is the structure of a them for magento 2?

**Comment by ishakhsuvarov** [comment]
Hi @mataheri 
GitHub is intended for bug reports. Questions would be more suitable on the [Magento Community Forums](https://community.magento.com/) or [Magento Stack Exchange](https://magento.stackexchange.com/). Also please check out [Magento Developer Documentation](http://devdocs.magento.com/), answer you looking for may be there.

Thank you
