### ISSUE TITLE
MultiStore Price per website, Wrong price indexed for configurable products in magento 2 version 2.1.8

### ISSUE THREAD

**Issue by niko7869** [magento/magento2#10830]
![screen shot 2017-09-07 at 21 29 47](https://user-images.githubusercontent.com/31761373/30241767-a4f41946-9592-11e7-93d8-ad0fdc37a3dc.png)
![screen shot 2017-09-07 at 21 30 03](https://user-images.githubusercontent.com/31761373/30241768-a5261446-9592-11e7-8551-7403f8e12f92.png)

  This issue exists in Magento Enterprise Edition 2.1.8
I am facing this issue when we have set the base currency to "RUB" and our default display currency is "USD".
I have multi store view 

This issue happens only on the product detail page and not on the listing page. Listing page displays the price correctly.

I hope someone can help me and can give me a fix, sometimes i dont understand magento is ecommrece platform and they say they support multi currency but still they have os many errors and bug and so hard to manage

**Comment by rukrlf** [comment]
May be you can try this
https://github.com/magento/magento2/issues/10400

**Comment by niko7869** [comment]
@rukrlf  actually i not a deveoper so i dont know how to do it can maybe give me exact steps on how do it if u can ? please

**Comment by niko7869** [comment]
@rukrlf it didnt work i tired :(

**Comment by magento-engcom-team** [comment]
@niko7869 thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
