### ISSUE TITLE
Incorrect image in minicart for Configurable product

### ISSUE THREAD

**Issue by Kasoi-free** [magento/magento2#10839]
Image in minicart for Configurable product does not reflect the image for selected associated product.

### Preconditions
1. Magento 2.1.8 with sample data
2. PHP 7.0.12 and MySQL 5.6

### Steps to reproduce
1. Set the following setting
Stores - Configuration - Sales - Checkout - Shopping Cart - Configurable Product Image
To "Product thumbnail itself"
2. Find in Configurable product Catalog or set up one a with Thumbnail Image set, configure associated products and set images for them too.
3. Select all the options in Configurable product and add it to cart
4. Open the cart page and expand minicart

### Expected result
1. Product image in the minicart should match the image in the cart. This should be a thumbnail from the associated product

### Actual result
1. Thumbnail from parent Configurable product is being used instead: 
https://screen.amasty.com/1505136948690.jpg

**Comment by RomaKis** [comment]
@Kasoi-free, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
Please provide more details regarding your environment, or try to reproduce this
issue on a clean installation.

**Comment by Kasoi-free** [comment]
Must be a cache issue, can't reproduce it anymore. Should've checked that, sorry.
