### ISSUE TITLE
MySQL server has gone away.

### ISSUE THREAD

**Issue by MrDaar** [magento/magento2#10845]
### Preconditions
1. M2.2 (2.2.0-release-candidate)
2. EE (2.2.0-release-candidate)
3. B2B (1.0.0-release-candidate)
4. PHP 7.0.22
5. Apache/2.4.18
6. mysql Ver 14.14

Although this is a general issue on most versions I assume...

### Steps to reproduce
1. Just do some general development on your local, although does sometimes happen on the staging environment.
2. Often happens randomly when you reload a page

### Expected result
1. MySQL server does not go away.

### Actual result
1. MySQL server has gone away.

Have tried many adjustments to MySQL config, including, but not limited to:
```
key_buffer_size=256M
wait_timeout=6000
skip_name_resolve=1
max_allowed_packet=1024M
innodb_buffer_pool_size=512M
open-files-limit=7167
table_open_cache=300
```

**Comment by orlangur** [comment]
I don't think there is something in Magento code which can cause this.

Try some
https://dev.mysql.com/doc/refman/5.7/en/gone-away.html
https://stackoverflow.com/questions/6117098/hard-to-debug-mysql-server-has-gone-away
https://stackoverflow.com/questions/6179536/mysql-server-has-gone-away-how-do-i-debug-the-reason

**Comment by magento-engcom-team** [comment]
Closing as non-magento issue
