### ISSUE TITLE
Hot Seller Widget css Issue

### ISSUE THREAD

**Issue by hirenvasani** [magento/magento2#1084]
After Updating from beta 10 to beta 11, I am getting some issue in Hot Seller css? Any Quick Fix?

![magento_2_home_hot_seller_files](https://cloud.githubusercontent.com/assets/1134977/6557269/c0b8f4dc-c699-11e4-8339-af0eaefa4c84.png)

**Comment by villageseo** [comment]
Hi hirenvasani! 

Thank you for reporting this issue. 
Internal MAGETWO-34557 ticket has been raised.

**Comment by hirenvasani** [comment]
Fixed with Dev RC Beta 1

**Comment by vpelipenko** [comment]
Fixed. Closed.
