### ISSUE TITLE
Category getExtensionAttributes() does not create new extension attribute object

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#10847]
If you look at `\Magento\Catalog\Model\Category::getExtensionAttributes()` you'll see that it only returns it's parent method which in turn is a simple `getData()`-call:

    public function getExtensionAttributes()
    {
        return $this->_getExtensionAttributes();
    }

But if you look at `\Magento\Catalog\Model\Product::getExtensionAttributes()` you'll see that if creates a new extension attribute object on the fly:

    public function getExtensionAttributes()
    {
        $extensionAttributes = $this->_getExtensionAttributes();
        if (!$extensionAttributes) {
            return $this->extensionAttributesFactory->create('Magento\Catalog\Api\Data\ProductInterface');
        }
        return $extensionAttributes;
    }

Not having this functionality on the category model means that if we want to use extension attributes in any plugin, we always have to include the extension attribute factory and do the check on our own.

Is there a reason that this code is omitted in the Category model? Or is this a bug?

**Comment by orlangur** [comment]
Such behavior for `Product` model was introduced in https://github.com/magento/magento2/commit/0f0063045b50e1dafa260b97a1a00bf9fa92e74b#diff-d31bcdab992b8a290ce2d9ae7ed5bb62R2459 and I have no idea why. The newly created instance is not even stored inside, this is just a factory method.

> we always have to include the extension attribute factory and do the check on our own

Just like interface says - it can return instance or `null`. Do you see any problem with that?

**Comment by kanduvisla** [comment]
I was just thinking about the consistency between various Magento modules. As always, it depends on the implementation of the interface. But you have a valid point: if we rely on the interface only, then every functionality we build that depends on that interface should be aware that the method can also return `null`.

**Comment by orlangur** [comment]
I would rather remove such behavior from `Product` model to make it consistent with others, raised this question within maintainers group. It was introduced in scope of Staging EE feature implementation.

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.
We've created internal ticket(s) MAGETWO-75634 to track progress on the issue.

**Comment by apotdar** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by ishakhsuvarov** [comment]
Hi @apotdar 
Please accept the GitHub repository invitation so that we could assign this ticket to you.
Thank you.

**Comment by apotdar** [comment]
Invitation accepted.  Can you please assign this ticket to me.

Thank you :).

**Comment by apotdar** [comment]
Hello @ishakhsuvarov,

Can you please assign this ticket to me?  I have already accepted the invitation.

Thank you
Ashutosh Potdar

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
