### ISSUE TITLE
PayPal Express Checkout address fields error when guest checkout disabled

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#10841]
# Preconditions

- Magento 2.1.8
- Paypal Express Checkout Enabled
- Guest checkout disabled

# Steps to Reproduce

- Add a **virtual** Product to Cart
- Click 'Go TO Checkout' from mini-cart then choose 'Create an account' from authentication pop-up
- Fill required info to create account
- Choose PayPal on checkout it will redirect to PayPal to without taking billing address.
- Do required steps at PayPal and you will be redirected to 'Review Order' step with error “We can't place the order.”
 
# Actual Result
The actual error in the log is **"Please check the billing address information. Please enter the street. Please enter the city. Please enter the phone number. Please enter the zip/postal code."**

# Expected result

The order should be placed successfully.

**Comment by rav-redchamps** [comment]
hi @magento-engcom-team 

This is a critical issue as it belongs to check out. I can repeat it in Magento 2.2-RC as well. So possibly this will be shipped in M2.2 as well.

Please let me know if you need any help to repeat this.

**Comment by pboisvert** [comment]
@ravinders-121 can you provide more info around the steps used to complete checkout at PayPal?

Did you use the credit card method (guest checkout) option? In your PayPal Express Checkout > Advanced Settings are you set to allow guest checkout? Are you also set to not require Billing address?

The issue may be related that the Magento checkout tries to pull in Billing info (shipping as well) from PayPal as a means to speed up checkout, but can also be configured from to allow "Guest checkout" and also not to require billing address". Under those conditions there would be no billing address coming back from PayPal.

**Comment by magento-engcom-team** [comment]
@ravinders-121 , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.
