### ISSUE TITLE
Products not visible

### ISSUE THREAD

**Issue by MrDaar** [magento/magento2#10844]
### Preconditions
1. M2.2 (2.2.0-release-candidate)
2. EE (2.2.0-release-candidate)
3. B2B (1.0.0-release-candidate)
4. PHP 7.0.22
5. Apache/2.4.18
6. mysql Ver 14.14

### Steps to reproduce
1. Create a test category, just inside the root category, set all permissions to as open as possible
```
All Customer Groups > Allow > Allow > Allow
NOT LOGGED IN > Allow > Allow > Allow
```
2. Create a test product, in that test category
3. Reindex
4. Clear cache

### Expected result
1. The product is visible on frontend

### Actual result
1. The product is NOT visible on frontend

The menu item for the category appears in the main menu, which means the category is visible to the public.
My colleague was able to get a product to show, when it was added to the "shared catalog".
Do all products have to be in a "shared catalog"?

**Comment by orlangur** [comment]
Please make a screenshot of product fields. Essential ones are Stock, Visibility, Status.

**Comment by magento-engcom-team** [comment]
@MrDaar thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
