### ISSUE TITLE
Attribute Indexing ignores custom source model options

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#10840]
### Preconditions

1. Magento CE 2.1.x up to and including 2.1.8

### Steps to reproduce

1. Create a multi-select attribute with a source model
2. Set it to be used in layered navigation
3. Create >1 product with different values for this attribute and add to a category
4. Reindex
5. View frontend of category

### Expected result

1. There should be a filter displayed for the attribute with the relevant values and product counts

### Actual result

1. Filter not displayed

The reason that the filter is not displayed is that indexing ignores source models - it only works for non-source-model options.

Also note that this was raised a long time ago but accidentally closed as a non-bug: #417. There is also a fix attached here. It's not complex, and I've got it to work for 2.1.8.

**Comment by lbajsarowicz** [comment]
Which search engine do you use? ElasticSearch or MySQL? Which type of Reindex you use (did you notice the difference of "index on save" and "CLI reindex")?

**Comment by george-vlahakis** [comment]
I concur, the issue remains (Im testing on 2.1.7). Custom source model does not produce indexer results in catalog_product_index_eav table.
