### ISSUE TITLE
Gateway error: Unable to read response, or response is empty while trying to capture invoice online

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#10853]
Gateway error: Unable to read response, or response is empty while trying to capture invoice online.

### Preconditions

1. Magento v2.1.7

### Steps to reproduce

1.  Enable Authorize.net direct post payment method.
2.  Enter your sandbox account credentials. (API login id, transaction key, MD5 )
3.  Gateway URl: https://test.authorize.net/gateway/transact.dll
4. Transaction details URL: https://api2.authorize.net/xml/v1/request.api
5. Place order using authorize.net payment method from frontend.
6. Create invoice by selection Capture invoice online.
7. Submit Invoice

### Expected result

1.  Invoice created successfully.

### Actual result

1. Gateway error: Unable to read response, or response is empty

![image](https://user-images.githubusercontent.com/17869716/30322662-de89ffda-97d7-11e7-98b5-1bc5a7a0ca32.png)

**Comment by YevSent** [comment]
Hi, @routbiplab, please, enable debug mode for Authorize.net and provide transaction details from the `debug.log`, also if any error messages are present in `exception.log` or `system.log`, please, attach them.

**Comment by routbiplab** [comment]
Here is my debug.log and exception.log files.

[exception.txt](https://github.com/magento/magento2/files/1296027/exception.txt)

[debug.txt](https://github.com/magento/magento2/files/1296029/debug.txt)

**Comment by viktym** [comment]
Try to use https://apitest.authorize.net/xml/v1/request.api as transaction details URL for test requests

**Comment by magento-engcom-team** [comment]
@routbiplab thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by routbiplab** [comment]
Thanks for the info. Let me check with the URL if it works or not.
