### ISSUE TITLE
REST service with 'SearchCriteria' is of type GET

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1085]
I'm experimenting with the available REST services (for example 'rest/V1/products'), but in 'webapi.xml' it is routed as a GET service. But since a json request needs to be send to the service with the searchcriteria, it should by of type 'PUT', right?

It's for every service as far as I looked. Changed it to PUT and it works..

**Comment by anupdugar** [comment]
@rklerck Thanks for reporting the issue. As part of #889 all the search related routes were converted to GET. It seems some of the changes were overwritten. We will investigate further and let you know if its a bug.

**Comment by rklerck** [comment]
I'm reading the related bugs, and maybe I'm not seeing the possibility on how to send the searchcriteria with GET..

**Comment by anupdugar** [comment]
@rklerck We are still working on the documentation for our REST apis but a search sample would be something like:
GET /products?searchcriteria[filter_groups][0][filters][0][field]=sku&searchcriteria[filter_groups][0][filters][0][value]=<someSampleSku>&searchcriteria[filter_groups][0][filters][0][condition_type]=eq&searchcriteria[current_page]=1&searchcriteria[page_size]=1

**Comment by alankent** [comment]
GET vs PUT vs POST is one of those semi religious topics. 

This one was quite a good read http://stackoverflow.com/questions/978061/http-get-with-request-body. As you work your way down you start with doing a POST to and end point, with a slightly sheepish "oh well". Then later it says things like some proxies may not work. Then "elastic search encourages it". 

GET is semantically more correct as there are no side effects.

**Comment by rklerck** [comment]
Thanks for the explanation. I will close this issue than.
