### ISSUE TITLE
Duplicate default value discount_tax

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#10852]
### Preconditions

1. PHP 7.0
2. Magento 2.2
3. Mysql v10

### Steps to reproduce

1. Go to /Magento-2/vendor/magento/module-tax/etc/config.xml at line 23 is a duplicate tag entry for <discount_tax>

### Expected result

1. There should only be one discount_tax tag

### Actual result

1. If i want to override this default value i get an error.

**Comment by orlangur** [comment]
@leonhelmus thanks for bug report! Closing it in favor of https://github.com/magento/magento2/issues/11000 which contains more detailed steps and PR with bugfix.
