### ISSUE TITLE
Sync billing with shipping address on Admin Reorder and Admin Customer Create Order page does not work for Existing address selected

### ISSUE THREAD

**Issue by NoorulBhoelai** [magento/magento2#10856]
### Preconditions
- PHP 7.0.14
- Mysql 5.7.12
- Magento [2.1.5 - 2.1.6 - 2.1.7 - 2.1.8]
- Branch: Develop, Tag: 2.1.8, Commit Hash: 34fc8d8b034badc36ac9a91dca30e49538d09284

### Steps to reproduce
1. Please Go to Sales > Orders in Admin and continue to step 2, or Go to Customers > All customers and select Sample Customer "Veronica", then go to Create Order, continue to step 4.
2. Select Sample Data existing customer (Veronica)
3. Click Reorder on Order Detail Page
4. Please do NOT select "new address", instead use an "existing address"
5. Make sure the "Same as billing address" is checked.
6. Please change a random billing address Field.

### Expected result
- Shipping address should be updated.

### Actual result
- Shipping address is not updated with the change you made in the Billing Address form.

General Question:
@magento-engcom-team , is there a live Magento Demo environment so we can faster confirm if an issue can be acknowledged?

**Comment by korostii** [comment]
Well, these aren't official, yet they're commonly used:
http://magento2-demo.nexcess.net/
http://magento2demo.firebearstudio.com/

**Comment by NoorulBhoelai** [comment]
@korostii Thanks but checked those environments already, exception logs are displayed in the browser in http://magento2demo.firebearstudio.com/ so the issue cannot be reproduced. And http://magento2-demo.nexcess.net/ is only for frontend.

**Comment by magento-engcom-team** [comment]
@NoorulBhoelai thank you for your bug report.
We've created internal ticket MAGETWO-75218 to track progress on the issue.

**Comment by YevSent** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81680

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81680

**Comment by magento-team** [comment]
Hi @NoorulBhoelai. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1284 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by NoorulBhoelai** [comment]
Nice good job!
