### ISSUE TITLE
Media Gallery Scopes

### ISSUE THREAD

**Issue by vkublytskyi** [magento/magento2#10863]
## Terms and Concepts

*Warning!* This document uses simplified terms and concepts to explain products media gallery desired behavior and implementation.
For more accurate terms definition please check out [Magento Glossary](https://magento.github.io/glossary/).

**Scope** &mdash; set of data at Magento instance that may be accessible at the same time. Scopes are 4-level hierarchical structure and include global, websites, stores and store views.
Each level of scope has access to underlying layer's data and my redefine it as well as may introduce own data (e.g. store level has access to all data defined at website level plus own data).
Each level has own semantic meaning. In this document, we will consider only *global* and *store view* levels.

**Global Scope** &mdash; represents data itself. You may think about this scope as a place where all models are live.

**Store View** &mdash; represent data displaying options for a store front. Namely, store view defines what data from global scope will see a customer at your site and how it will see them.

Technically *Global Scope* is implemented as a *default store view* with `id=0`. *Default* store view also may be referenced as *Admin* store view.

Don't be confused! Magento 2 admin uses terms *Store* and *Store view* while in code *Store* is corresponding to *Store Group* and *Store View* to *Store*.
After installation, Magento 2 has *Default Store View* which usually have `id=1` and does not have any special meaning. When code refers to `\Magento\Store\Model\Store::DEFAULT_STORE_ID` it uses store view not visible in Admin panel and holding data of the Global scope.

**Product** &mdash; is a data of the things that are available for a customer to purchase. This is a model. As a result, products stored in the *Global* scope. You can not create a product that will exist in one store but will not exists in another. However, you may disable product for some website (product will exist on a website but will not be accessible by a customer).

**Media Gallery** &mdash; set of media resources related to a product. It's implemented as a product attribute. As for any model, data of media gallery must be stored on the global level.

**Media Gallery Entry** &mdash; is a media resource model (image or video). It must be stored on the global level as well. Meaningful are file path and media type properties.

In term of DDD Product is an Aggregation Root and holds Media Gallery that holds Media Gallery Entries. As this is the same aggregate all its parts are stored on the same (*Global*) level.

Product has **image, small image and thumbnail** attributes which define what images will be *displayed* to customer on store front at catalog and product pages. As this is data related to product displaying these options are store on the *store view* level. Image, small image and thumbnail attributes reference to media gallery entries by file path.

*Displaying* of *Media Gallery Entry* may be configured with options:
- alt text &mdash; sets a text that displayed if entry can not be loaded on store front.
- position &mdash; defines order of images on product page.
- disable &mdash; allows to hide gallery image on store front.

*Role* property displayed at *Media Gallery Entry* admin page, in fact, corresponds to Product attributes.

To summarize:
- Product, Product Media Gallery and Media Gallery Entry are models and stored on the global level.
- image, small image and thumbnail product attributes as well as alt text, position and disable gallery entry attributes define how product will be displayed on store front and managed on a store view level.

### Media Gallery management

Media Gallery may be managed on an admin product page under *Images and Videos* tab. Any change to a media gallery applied after product save. Admin product page uses scope switcher to define what scope should be used for persisting data. In the switcher **All store view** value correspond to the *default (admin) store view*,  which is equal to the global scope. Saving some value for *All store view* actually does not change value in all store views. Instead, value persisted in the *default store view* and this value may be used as fallback if it is missed for some store view.

<img width="308" src="https://user-images.githubusercontent.com/1295148/30323978-fd9dd852-97c7-11e7-9777-d13beeb2bc31.png">

Regardless of scope switcher value, some fields may be stored on more higher level of scopes hierarchy. Usually, this is reflected in UI.

<img width="110" src="https://user-images.githubusercontent.com/1295148/30324710-ab6e0964-97ca-11e7-86b6-583c42ad5c7f.png">

As was discussed previously *add* and *delete* operations always [should be] executed on the *global* level. Update operation may be performed on a store view level respecting product save scope switcher.

To prevent errors in media gallery management system does not allow to delete image if it has special role in store view another then current edit scope.

## Implementation details

Media Gallery uses 4 tables for data persisting:
1. `catalog_product_entity_media_gallery` &mdash; holds data of media gallery entries which are stored on the *global* level (model data).
1. `catalog_product_entity_media_gallery_value` &mdash; holds data of media gallery entries which are stored on a *store view* level (presentation data).
1. `catalog_product_entity_media_gallery_value_to_entity` &mdash; links media gallery entry to product on a *global* level.
1. `catalog_product_entity_media_gallery_value_video` &mdash; holds video specific data on a *store view* level.

Product image, small image and thumbnail attributes stored in `catalog_product_entity_varchar` table.

### Media gallery and Content Staging
Media gallery supports [Magento Content Staging](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/staging.html). As a result schema for Magento Open Source (CE) and for Magento Commerce (EE) with Staging enabled are different.
Schema without enabled Staging uses `entity_id` field for foreign key. Staging modifies schema and replace `entity_id` field with `row_id`. To use proper column name in PHP code `Magento\Framework\EntityManager\EntityMetadataInterface::getLinkField` should be used.

## Issues in current implementation

Current implementation has several issues that complicate understanding of desired behavior, leads to misunderstanding and bad user experience.

### UI of Media Gallery does not reflect in what scope data is persisted
<img width="530" src="https://user-images.githubusercontent.com/1295148/30326704-0c9336a4-97d2-11e7-8189-726f6d7384db.png">

<img width="530" src="https://user-images.githubusercontent.com/1295148/30326264-ac4d7c6a-97d0-11e7-87bb-bc8e2571d9f6.png">

On images above fields that should be stored at different scope levels displayed together and user can not determine what scope will be modified.

### New image may be stored not in the global scope

If gallery entry added not in *All Store Views* mode table `catalog_product_entity_media_gallery_value` does not contain record for `store_id=0`.
As a result fallback mechanism for other store views is broken.

### Missed possibility to use default store view options

To allow use default value provided by default scope product attributes uses *Use Default value* checkbox.

<img width="300" src="https://user-images.githubusercontent.com/1295148/30327215-f1a81588-97d3-11e7-95a2-77313167c774.png">

Media Gallery Entry attributes don't have same mechanism. As a result, image attributes always persisted in a scope defined by product scope switcher. That means, if product saved for some store view scope all media gallery attributes are copied from default store view even if there are no changes in images.

Duplication of image attributes on store view complicates gallery management:

1. Admin create a product (global scope)
2. Admin add images to product and set one as an *image*, *small image* and *thumbnail* (global scope)
3. Admin switch to some store view and edit any field not related to gallery (store view scope)
4. Admin save product. At this moment attributes for all images are copied from default (admin) store view to edited store view
5. Admin switch back to global scope
6. Admin can not properly manage gallery from global scope
  6.1 Admin edit image attributes but they are not reflected on store front as store view already has own copy of attributes
  6.2 Admin try to delete image with special role but system shows error message (edited scope has own information about image role so blocks image deletion)

## Required fixes (in order of severity)
1.  Provide possibility to use default value for Media Gallery Entry attributes (should be enabled by default).
2. Always persist new media gallery entry in default (admin) store view.
3. Add scope labels to UI for media gallery entries.

**Comment by torreytsui** [comment]
@vkublytskyi 

Could you please clarify how should REST API handle **absent** gallery entries on this endpoint?Should they all be flagged as `disabled`?

`PUT /V1/products/{sku}`

```
{
  "product": {
    "media_gallery_entries": [
      {
        "media_type": "image",
        "position": 1,
        "disabled": false,
        "types": [
          "image",
          "small_image",
          "thumbnail"
        ],
        "file": "A/W/AWESOME.jpg"
      }
    ],
    ...
  }
}
```

Given that this product originally has two gallery entries, namely `A/W/AWESOME.jpg` and `A/W/AWESOME-2.jpg`, I suppose, after this PUT request, the **absent** image `A/W/AWESOME-2.jpg` will be flagged as `disabled=true` on the store view.

**Comment by vkublytskyi** [comment]
@torreytsui If a product has `media_gallery_entries` array system should treat this as all available gallery entries. All other images should be deleted (so all store view will be affected by API request).

I would also mention that media gallery has own set of API endpoints that should be preferred over modifying media gallery through product modification.

In general, objects passed to Web API should not be modified based on current system state so implicit converting of `disabled` flag should be avoided.

**Comment by magento-engcom-team** [comment]
Hi @vkublytskyi. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/23

**Comment by LiamKarlMitchell** [comment]
Fix please.

**Comment by eraq** [comment]
Fix please....

**Comment by kushaljindal92** [comment]
This issue still exists on 2.4.6

**Comment by MatthijsBreed** [comment]
For people looking for a workaround preventing more data duplication

```php
<?php

namespace Vendor\ModuleName\Plugin\Magento\Catalog\Controller\Adminhtml;

use Magento\Catalog\Controller\Adminhtml\Product\Save as Subject;
use Magento\Framework\App\RequestInterface;

class Save
{
    public function __construct(
        protected RequestInterface $request,
    ) {
    }

    /**
     * @param Subject $subject
     * @return array
     *
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function beforeExecute(Subject $subject): array
    {
        if ($this->request->getParam('store', 0) != 0) {
            $postParams = $this->request->getPost();
            $postParams['use_default'] = [
                ...$postParams['use_default'],
                'media_gallery' => "1",
                'thumbnail' => "1",
                'small_image' => "1",
                'image' => "1",
            ];
            $this->request->setPost($postParams);
        }
        return [];
    }
}
```
Extra param values are strings, since `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` and `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper\AttributeFilter::prepareProductAttributes` do a strict type check to `'1'`

Note, this assumes that your admin scope is store_id 0 and that images and their roles should only be changed on that scope
