### ISSUE TITLE
field lengths differ across many tables

### ISSUE THREAD

**Issue by steros** [magento/magento2#10869]
### Preconditions
1. any Magento 2 version
2. have no telephone validation except than it's required

### Steps to reproduce
1. place an order
2. enter a very wide telephone number (+20 characters)
3. order 

### Expected result
1. the very long telephone number should appear in the database as the field is 255 characters long in sales_order_address

### Actual result
1. the telephone number gets cut off after 20 characters as the quote_order_address field is just set to 20 characters VARCHAR

### Fix
See #10868 
Raise the characters in quote_order_address to 255 VARCHAR as in sales_order_address

### Further comment

I found numerous field lengths to be different across many tables. Thus strings get cut off.
In my case the "telephone" was cut off as someone set it to be just 20 characters in the quote_address table despite it being 255 characters wide in the sales_order_address table.
There are many other fields differing.

Someone seriously needs to check this! Unfortunately I do not have enough knowledge about all the fields.

In my case our customers want to enter not one phone number but sometimes their landline and mobile phone number into the telephone field. The field is not validated against any format.

It seems this is across any version.

**Comment by southerncomputer** [comment]
Well you should have consistent field sizes - so reducing a 255 -> 20 is a no-go for backwards compatibility, why not propose a patch to fix what you've seen! I've had to manually address this as our ERP uses sql-server which is very unkind and does the right thing -faults the insert on size/truncation where-as mysql does the unthinkable and loses data quite happily!

**Comment by steros** [comment]
Hey,

I've already proposed a patch and there discussion has gone a bit further.
It seems this is actually a bug which needs to be addressed.

So I'm closing this.

**Comment by orlangur** [comment]
Here is what needs to be done: https://github.com/magento/magento2/pull/10868#issuecomment-329762150

Similar issue existed for multiple fields, first/middle/lastname were fixed before but telephone (AND MAYBE other fields, this needs to be checked) are still affected.

**Comment by magento-engcom-team** [comment]
@steros, thank you for your report.
We've created internal ticket(s) MAGETWO-80421 to track progress on the issue.

**Comment by rogyar** [comment]
I've addressed the issue in my PR (https://github.com/magento/magento2/pull/11286). Checked the issued fields and found that it makes sense to extend the following fields:
- telephone. Has been already discussed.
- fax. Same issue as with telephone
- region
- city

As for the region and city, there are some really long names  (https://en.wikipedia.org/wiki/List_of_long_place_names). So, it doesn't make sense to limit the length up to 50 or so.
According to this issue, there's no some reasonable limit for the telephone number length (however, it should not exceed 15-20 characters ideally). 
Thanks.

**Comment by maksek** [comment]
Hey @rogyar, should I assign the ticket on you?

**Comment by rogyar** [comment]
Hello @maksek. Sure, thank you.

**Comment by steros** [comment]
Thanks guys for working on this 👍

**Comment by dverkade** [comment]
I backported this issue to 2.2-develop branch and submitted a PR. This issue is still open for 2.1. In 2.1 the module database version is at 2.0.4. These changes are in version 2.0.7. Should the database changes in 2.0.5 and 2.0.6 be backported first in order to backport this issue to the 2.1-develop branch?

**Comment by magento-team** [comment]
Hi @steros. Thank you for your report. 
The issue has been fixed in magento/magento2#13015 by @dverkade in 2.2-develop branch
Related commit(s):
 - 6c16fcbc89fcdf285a346f38b6a5276cba20c9fc

The fix will be available with the upcoming patch release.
