### ISSUE TITLE
Email message containing non English character is displayed incorrectly on the receiver.

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1086]
Here is an example on Contact Us page.

[Input]
Name:  ひらがな
Email: a@a.com
Phone Number:
Comment: ABC 123  ひらがな

[Received email]
Name:  ã ²ã‚‰ã Œã ª
E-mail: a@a.com
Phone Number:
Comment: ABC 123  ã ²ã‚‰ã Œã ª

**Comment by ilol** [comment]
@adzminz,
Thank you for reporting this issue. 
Internal ticket has been created  (MAGETWO-34955)

**Comment by UdaySagar** [comment]
Hi @adzminz 

I have tried to reproduce the issue you have reported. But I didn't see any change in the characters. I got the same characters even in the email received. Can I know the service provider of the email you have used?

Also please let us know the locale you have used while installing magento. 

Thanks.

**Comment by adzminz** [comment]
Hi Uday,

I'm using Mandrill service, and my local setting is English (United States).

Thanks,

--- Original Message ---

**Comment by UdaySagar** [comment]
Thanks for the info Adzminz. Did you try giving email id of other service providers. For example gmail or yahoo? If not, please give it a shot and update me.

**Comment by adzminz** [comment]
Thank you for your suggestion.

I tried sending emails via Mandrill's smtp to gmail/hotmail and via gmail's smtp to gmail/hotmail, but got the same result. I also tried reinstalling Magento from scratch but no luck. However, sending by command line was fine.

[Command line]
Message:
![6](https://cloud.githubusercontent.com/assets/11070293/6619623/2837769a-c8fe-11e4-989c-00ad053801b3.png)
Mandrill received:
![2-2](https://cloud.githubusercontent.com/assets/11070293/6618980/8cdebcd4-c8f9-11e4-9ea7-f63b25e01aa8.PNG)
Gmail:
![7](https://cloud.githubusercontent.com/assets/11070293/6619721/bb58f318-c8fe-11e4-86da-50359ece38ac.PNG)


[Contact Us]
![3](https://cloud.githubusercontent.com/assets/11070293/6618997/ace7fc70-c8f9-11e4-95f0-a68db9d750c9.PNG)
Mandrill received:
![4](https://cloud.githubusercontent.com/assets/11070293/6619001/b05d7bc8-c8f9-11e4-8035-1781a768031d.PNG)
Gmail:
![5](https://cloud.githubusercontent.com/assets/11070293/6619040/09319f2c-c8fa-11e4-82f9-67212c5888d7.PNG)

**Comment by adzminz** [comment]
I tested this issue on Magento 1.9 with the same server and the same smtp configurations, and there was no problem with the non English character. All are displayed correctly.

**Comment by snohe** [comment]
@adzminz, this has been resolved in 0.74.0-beta1.  Thank you again for reporting this issue.  Should you encounter other issues or have suggestions for improvement, feel free to contact us! Thank you for using Magento!
