### ISSUE TITLE
Issue with Custom Theme in Magento 2.1.8

### ISSUE THREAD

**Issue by prakash2jcommerce** [magento/magento2#10867]
Hi Everyone,
I am using custom theme with Magento 2.1.8. I am facing any issue which I am sharing with you all, hope you will provide solution over it.

Them Hierarchy:
Parent Theme: Magento Luma
---Configured Theme: Base Theme
------Child 1 Theme: Layout2 Theme
------Child 2 Theme: Layout3 Theme 

I am using 3 different layout for 3 different type of Product Page, each Product Page Layout is running through separate theme. 
Layout 1 is running with base theme, which is working fine for me.

![layout 1](https://user-images.githubusercontent.com/18117994/30376304-59e4bb58-98a9-11e7-88ab-f4d8a57d4ba1.jpg)

Layout 2 & 3 are running via separate Child Theme i.e. via Layout2 Theme and Layout3 Theme resp.

**Issue:**
Layout 2 and 3 which needs to be run from the theme which is assigned to Product from Magento Backend (Custom Layout), but we are facing issue with Layout changes, which are not working from Child theme. Layout Changes are working from Configured Theme (Base Theme). Which we need to run it from Child Theme which is assigned.

 
**### Preconditions**
Magento version: 2.1.8. 

**### Expected result**
XML Changes for Layout 2 & Layout 3 should run via Custom Layout (Child Theme) assigned to Product via Magento Backend.

Hope issue is clear to everyone. please advice.

**Comment by magento-engcom-team** [comment]
@prakash2jcommerce, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
