### ISSUE TITLE
3D Secure Not in PayPal Payments Pro

### ISSUE THREAD

**Issue by rbur0425** [magento/magento2#10872]
In Magento 1.9.X, PayPal payments pro includes the 3D Secure validation if wanted. In Magento 2.1 and greater 3D Secure validation is only included for Braintree. This needs to be brought back in for PayPal Payments Pro.

Below is 1.9 where 3D Secure is an option for PayPal payments Pro
![1 9 3dsecure](https://user-images.githubusercontent.com/14355895/30384149-8d60d5d0-9871-11e7-8d2a-90fd0218f217.png)

Below is current 2.1 where it is under Braintree only
![braintree only](https://user-images.githubusercontent.com/14355895/30384213-af1fa944-9871-11e7-81a4-59d611594dd0.png)

**Comment by magento-engcom-team** [comment]
Hi @rbur0425 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento 2 Core technical issues only.

**Comment by magento-engcom-team** [comment]
@rbur0425 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
