### ISSUE TITLE
massDelete CMS Block not working (error 500)

### ISSUE THREAD

**Issue by nelero** [magento/magento2#10870]
Hi,
i'm using the latest stable 2.1.x version.
When i try to mass delete some cms blocks (1 or more checked), i receive an error 500 and blocks are not deleted.

But if i click individually on the block, access the detail page and click delete, the block is deleted as expected.

How can i fix this ?
thanks

**Comment by harshvardhanmalpani** [comment]
Duplicate of #8415 and #8418

**Comment by orlangur** [comment]
@harshvardhanmalpani yeah, thanks.

Issue seems to be fixed on `develop` but not backported to `2.1.x` yet. Anyone from Community can do it due to https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630.
