### ISSUE TITLE
After clicking the Next button in step four of the installation it takes very long to continue (So a loader animation is suggested), now the integrator thinks the process fails.

### ISSUE THREAD

**Issue by NoorulBhoelai** [magento/magento2#10874]
### Preconditions

PHP 7.0.14
Mysql 5.7.12
Magento [2.1.5 - 2.1.6 - 2.1.7 - 2.1.8]
Branch: Develop, Tag: 2.1.8, Commit Hash: 34fc8d8

### Steps to reproduce
Go to step 4 "Customize your store" in the installation process and click "Next"

### Expected result
- A loader animation

### Actual result
- No loader animation at all (Integrator gets confused and checks console logs)
- Step 5 page is loaded after 10 to 15 seconds, takes very long.

**Comment by magento-engcom-team** [comment]
@NoorulBhoelai, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
