### ISSUE TITLE
catalog price rule active or inactive issue

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#10880]
### Preconditions

1. Magento EE 2.1.3
2. PHP 7.0

### Steps to reproduce

1. Create catalog price rule and create one schedule update to make it active between some time period
2. Catalog rule will be active in that time period
3. Then in catalog rule prices are not displaying in frontend until and unless clear cache and reindex

### Expected result

1. Without reindex and clearing cache catalog rule prices should be displayed in Magento frontend

### Actual result

1. After clearing cache and reindex only catalog rule prices displaying in Magento frontend

**Comment by magento-engcom-team** [comment]
@i95devdivya thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal. 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
