### ISSUE TITLE
Magento 2 Rabbitmq consumers

### ISSUE THREAD

**Issue by karthi5053** [magento/magento2#10887]
We processing order updates from warehouse to magento.
Cron will Publish the message to rabbitmq queue.Each message contains order updates received from warehouse for one order.
we receive nearly 5k-6k shipment updates for orders from warehouse.

Consumers perform the following task for each messages consumed from queue:
Creating invoice, 
Capturing invoice, 
Creating shipment and 
sending invoice, shipment notification.

### Preconditions

1. Magento 2.1.4 EE cloud
2. Rabbitmq

### Steps to reproduce

1. Publish around 5k-6k messages to queue.
2. Monitor consumers during processing these messages.

### Expected result

1.

### Actual result

1.

We have monitored the process and takes takes about 13-15 hrs to process 5k-6k messages from queue.

Kindly check the following XML config:

queue.xml:
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/queue.xsd">
    <broker topic="shipment_update" type="amqp" exchange="magento">
        <queue consumer="shipment_update" name="order_updates_queue" handler="Model\ShipmentConsumer::processShipment" consumerInstance="Magento\Framework\MessageQueue\Consumer"/>
    </broker>
</config>`

communication.xml:
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Communication/etc/communication.xsd">
    <topic name="shipment_update" request="string" />
</config>`

Is it possible to have mulitple consumers for one queue, So that messages processes quick and consumes less time to complete all the messages from queue?

**Comment by choukalos** [comment]
You can run multiple consumers to process the Queue faster.  

FYI - details on how to run consumers for the Queue are embedded in the CLI help for the Queue commands.  Ie  bin/magento help queue:consumers:start  

Does that help?

**Comment by karthi5053** [comment]
@choukalos 
Thanks for your reply. Can you provide me a command so that we have 3 consumers for a queue, since i was not able to see an option to set no.of consumers from the help

root@461a7d07f5bb:/var/www/html# magento help queue:consumers:start
Usage:
 queue:consumers:start [--max-messages="..."] [--area-code="..."] consumer

Arguments:
 consumer              The name of the consumer to be started.

Options:
 --max-messages        The number of messages to be processed by the consumer before process termination. If not specified - terminate after processing all queued messages.
 --area-code           The preferred area (global, adminhtml, etc...) default is global.
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question

Help:
 This command starts MessageQueue consumer by its name.
 
 To start consumer which will process all queued messages and terminate execution:
 
       /var/www/html/bin/magento-php queue:consumers:start someConsumer
 
 To specify the number of messages which should be processed by consumer before its termination:
 
     /var/www/html/bin/magento-php queue:consumers:start someConsumer --max-messages=50
 
 To specify the preferred area:
 
     /var/www/html/bin/magento-php queue:consumers:start someConsumer --area-code='adminhtml'
root@461a7d07f5bb:/var/www/html# 


Thanks in advance.

**Comment by keharper** [comment]
@karthi5053 You should be able to run `magento queue:consumers:start <someConsumer>` multiple times concurrently in different terminals or by specifying `&` at the end of each command.

**Comment by magento-engcom-team** [comment]
@karthi5053, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by karthi5053** [comment]
Hi Guys,

I'm trying to implement job queue using db in magento 2.2.X version. Please find the attached XML's. 
However when i try to publish the message into the queue, im getting "Message queue topic \"%topic\" is not configured."

Please let me know what i'm doing wrong here. Going forward i may use rabbitmq as queue driver.



Communication.xml
===================

    <topic name="armstrong.order.create" request="string">
        <handler name="create.armstrong.order.handler" type="Model\Consumer\OrderConsumer" method="processMessage" />
    </topic>



queue_consumer.xml
=================


    <consumer name="armstrongOrderCreate" queue="armstrong_order_create_queue" connection="db" consumerInstance="Magento\Framework\MessageQueue\BatchConsumer" handler="MODEL\Armstrong\Consumer\OrderConsumer::processMessage"/>


queue_publisher.xml
================

    <publisher topic="armstrong.order.create">
        <connection name="db" exchange="magento-db" />
    </publisher>


queue_topology.xml
================

    <exchange name="magento-db" type="topic" connection="db">
        <binding id="defaultBinding" topic="armstrong.order.create" destinationType="queue" destination="armstrong_order_create_queue"/>
    </exchange>



Regards,
Karthi Kumar.
