### ISSUE TITLE
When selecting a payment method, the selected country is lost.

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#10886]
When I place an order and I enter a shipping address and go to the payment method, I notice that the country is lost. This issue has also been reported on [Stack Exchange](https://magento.stackexchange.com/questions/192723/magento-2-country-name-not-showing-in-billing-shipping-address-at-checkout).

**Edit:** On further investigation it seems that having disabled `full_page`-cache causes this issue.

### Preconditions

1. Magento 2.1.8

### Steps to reproduce

1. Disable the `full_page` cache.
2. Add a product to your cart and go to checkout > shipping > payment

### Expected result

The country should be visible in the address of the payment method.

### Actual result

The country is not filled in. Also, this will make the server give an error on our API request, because the mandatory countryId-field is not submitted to the server (or is left empty):

<img width="389" alt="screen shot 2017-09-14 at 2 42 55 pm" src="https://user-images.githubusercontent.com/346681/30430360-4628999c-995b-11e7-971c-7b54c099a1af.png">

This issue could be related to #10885

**Comment by kanduvisla** [comment]
I'm investigating this, and at the moment I tracked it down to `Magento_Customer/js/customer-data.js`. In this file, around line 189, the `init()`-method is called in the customerData object. The difference I can find out now is that the method:

    $.cookieStorage.get('private_content_version');

returns `null` in 2.1.8+ and a valid cookie in 2.1.7. It seems that the cookie is not set. I'm going to investigate this further.

**Comment by kanduvisla** [comment]
It turns out that the `private_content_version` cookie is set as soon as I add a product to the cart in 2.1.7, but not in 2.1.8+.

**Comment by kanduvisla** [comment]
Ok, it turns out that this cookie is set by `Magento\Framework\App\PageCache\Version()`. Seeing that it was set in the `PageCache`-namespace I started to wonder if this could be cache-related. On my local environment I had `full_page` cache disabled (for development purposes). Re-enabling it solved this issue for me.

But it still seems like a bug to me, especially since 2.1.7 was also running with `full_page` cache disabled. Can anyone else confirm this issue in Magento 2.1.8 and/or 2.1.9?

**Comment by kanduvisla** [comment]
Allright, I thought this was not an issue in 2.1.7, but it appears to be happening there as well, just didn't notice it before I guess... I'm editing the name of the issue to reflect this.

**Comment by vdmtrv** [comment]
I can also confirm that we are seeing the same behaviour on Magento 2.1.7

**Comment by okorshenko** [comment]
@kanduvisla thank you for the report.
The issue already fixed in 2.2.0
