### ISSUE TITLE
PayPal Credit Card Fields are missing on Checkout MCE 2.1.8

### ISSUE THREAD

**Issue by reihaan** [magento/magento2#10883]
### Steps to reproduce
I have setup a magento 2.1.8 and setup the payment as PayPal, I tried all the PayPal options only PayPal express checkout is working, however I need to take credit card details as well, but those are missing when I setup that payment system.

I tried all the options but all in vain!

### Preconditions

1.  Magento 2.1.8
2.  PHP 7

### Expected result

Should show the input fields for credit card, expiry date and CVV code.

### Actual result

Actual result is as follow: http://prntscr.com/gl09ds

**Comment by YevSent** [comment]
Hi, @reihaan, what PayPal payment method do you enabled (Payflow Pro, Payflow Link, etc.)? Also, please, check browser console error logs.

**Comment by reihaan** [comment]
Hi @joni-jones , Thanks for your reply.

The PayPal Express Checkout is working fine its redirecting to paypal and once payment is made it return back to website and order does get completed.

I have tried the following: 
- Website Payments Pro Hosted Solution
- Website Payments Standard

Here is the screenshot of browser console: http://prntscr.com/gldwcg
However I switched the luma theme but error still remains.

Didn't try the PayFlow and Braintree.

**Comment by YevSent** [comment]
Could you try to reproduce this issue on 2.1.9 version without any extensions and customizations?

**Comment by reihaan** [comment]
OK sure, I will do that and update you. 

Thanks

**Comment by reihaan** [comment]
I just tested on 2.1.9 and its working good. I can see the multiple payment options and seems to be working. So should I upgrade my magento to new version?  What is the best way to do it?

**Comment by YevSent** [comment]
You always should use the latest version is it possible. If you have installed Magento with composer, you need to specify the `2.1.9` instead `2.1.8`. For more details, please, see dev guide http://devdocs.magento.com/guides/v2.1/install-gde/bk-install-guide.html.

Closing this ticket as not a bug.

**Comment by reihaan** [comment]
I installed using Softacoulous, how can I update now? Can you please point me to the right direction?
I tried with composer, it did updated the libraries but backend is still same.

Thanks

**Comment by YevSent** [comment]
You need to run `setup:upgrade` CLI command after getting a new version of Magento.

For more details, please, contact with Softacoulous support, we do not provide such customization, Github only for the issues.

**Comment by reihaan** [comment]
Thanks, I will see how I can update it from here. Thanks again for you all support!

**Comment by reihaan** [comment]
Hi,

After updating Magento to 2.1.9 I still see the old Payment modules. What could be the issue?

Thanks
