### ISSUE TITLE
Redis password not used when trying to validate the connection during install.

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#10881]
I am using Magento 2 (2.1 and 2.2-rc23) in a container architecture platform proceeding automatic deployments.

Therefore, I have an already provisioned env.php file stating to use a password in order to connect to my Redis instance.

The first step of my deployment is to install Magento.

Here is the sample env.file (note the password to redis is properly set) : 

```
array(
	'cache_types' => array(
		'compiled_config' => 1
	) ,
	'session' => array(
		'save' => 'redis',
		'redis' => array(
			'host' => 'magento2-redis',
			'port' => '6379',
			'database' => '0',
			'password' => 'bVdTpAniegamcXKF'
		) ,
	) ,
	'cache' => array(
		'frontend' => array(
			'default' => array(
				'backend' => 'Cm_Cache_Backend_Redis',
				'backend_options' => array(
					'server' => 'magento2-redis',
					'port' => '6379',
					'database' => '1',
					'compress_data' => 0,
					'password' => 'bVdTpAniegamcXKF',
				) ,
			) ,
			'page_cache' => array(
				'backend' => 'Cm_Cache_Backend_Redis',
				'backend_options' => array(
					'server' => 'magento2-redis',
					'port' => '6379',
					'database' => '2',
					'compress_data' => 0,
					'password' => 'bVdTpAniegamcXKF',
				) ,
			) ,
		) ,
	) ,
	'db' => array(
		'connection' => array(
			'default' => array(
				'host' => 'galera',
				'dbname' => 'magento',
				'username' => 'user',
				'password' => '4d3KVsW6PpsD',
				'model' => 'mysql4',
				'engine' => 'innodb',
				'initStatements' => 'SET NAMES utf8;',
				'active' => '1',
			) ,
			'indexer' => array(
				'host' => 'galera',
				'dbname' => 'magento',
				'username' => 'user',
				'password' => '4d3KVsW6PpsD',
				'model' => 'mysql4',
				'engine' => 'innodb',
				'initStatements' => 'SET NAMES utf8;',
				'active' => '1',
			) ,
		) ,
	) ,
	'system' => array(
		'default' => array(
			'smile_elasticsuite_core_base_settings' => array(
				'es_client' => array(
					'servers' => 'magento2-elasticsearch:9200',
				) ,
			) ,
		) ,
	) ,
	'backend' => array(
		'frontName' => 'admin'
	) ,
)
```

### Preconditions

1. Magento 2.1 and 2.2-rc23
2. 

### Steps to reproduce

1. Having an already provisioned env file as above.
2. Run the command ``` php bin/magento setup:install                    --admin-firstname=Admin                 --admin-lastname=Smile                   --admin-email=myproject@smile.fr                         --admin-user=admin_smile                           --admin-password=Fe7vMUDU4437                   --backend-frontname=admin             --db-host=galera                          --db-name=magento                          --db-user=user                              --db-password=4d3KVsW6PpsD                      --base-url=http://mymagento.url                               --use-rewrites=1                                   --cleanup-database                                 --magento-init-params=MAGE_MODE=production```
3. 

### Expected result

1. Magento should install properly

### Actual result

1. Install fails : 

```
Invalid Redis configuration. Could not connect to Redis server.
```

For me, the problem is located here : https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Model/ConfigOptionsList/Cache.php#L169

This function does not read the password from the deploymentConfig !

Then the password is defaulted to null : https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/RedisConnectionValidator.php#L26

And it fails to test the Redis connection ....

**Comment by romainruaud** [comment]
A little update for this one : The Setup/Model/ConfigOptionsList/Cache.php is neither processing any "sentinel" related values.

This prevent a proper usage when using a Redis cluster with redis-sentinel as cache storage backend.

Regards

**Comment by magento-engcom-team** [comment]
@romainruaud, thank you for your report.
We've created internal ticket(s) MAGETWO-84608 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
I think that testing of this issue was not done properly so I removed labels.

**Comment by ghost** [comment]
According to Magento Devdocs on 2.3.0 you can setup redis this way:
```
php bin/magento setup:config:set --cache-backend=redis \
--cache-backend-redis-server=redis --cache-backend-redis-password=123123q --cache-backend-redis-db=0 \
--page-cache-redis-server=redis --page-cache-redis-password=123123q --page-cache-redis-db=1 --page-cache-redis-compress-data=0 \
--session-save-redis-host=redis --session-save-redis-password=123123q --session-save-redis-db=2 
```
Pay attention that `*-compress-data` is availably only in `compress-data`, and execuse me, I can not explain why - I'm just following the docs.

I got this as a result:
```
    'cache' => [
        'frontend' => [
            'default' => [
                'id_prefix' => '571_',
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => 'redis',
                    'database' => '0',
                    'port' => '6379',
                    'password' => '123123q'
                ]
            ],
            'page_cache' => [
                'id_prefix' => '571_',
                'backend_options' => [
                    'server' => 'redis',
                    'database' => '1',
                    'compress_data' => '0',
                    'password' => '123123q'
                ]
            ]
        ]
    ],
```
after Magento is uninstalled I tried this:
```
php bin/magento setup:install --admin-firstname=Admin --admin-lastname=Smile --admin-email=myproject@smile.fr --admin-user=admin_smile --admin-password=Fe7vMUDU4437 --backend-frontname=admin --db-host=127.0.0.1 --db-name=magentodev --db-user=root --base-url=http://magento-dev.loc --use-rewrites=1 --cleanup-database --magento-init-params=MAGE_MODE=production
```

As a result Magento was succesfully installed.
