### ISSUE TITLE
Magento 2.2.0-rc3.0 Temporary category tree index creation is very slow

### ISSUE THREAD

**Issue by PingusPepan** [magento/magento2#10896]
### Preconditions

1. Magento 2.2.0-rc3.0 (clean install)
2. PHP 7.0.13
3. MySQL: 10.0.20-MariaDB

### Steps to reproduce

1. 7000+ categories in multistore environment
2. Save product

### Expected result

1. Saves product reasonably quick

### Actual result

1. Takes 12 minutes to save the product

I have done some profiling and found out that there is a query ran 13 times. Each run takes about 30 seconds to complete.
It origins from `Magento\Catalog\Model\Indexer\Category\Product\AbstractAction` function `fillTempCategoryTreeIndex`
When I create the same temp table and run the query in SQL alone, it also takes 30s to run. This should be optimized. Why is it running when saving product in the first place? (Maybe run in only for categories which are selected, or category trees from selected websites). And why it runs 13 times?
I think there is probably another problem hidden in the saving process because when summed up, this query only takes about 6 minutes, so half of the whole process.

Is anybody else dealing with the same problem on 2.2.0?

**Comment by PingusPepan** [comment]
I have modified the `makeTempCategoryTreeIndex` function to reuse the created table and not create it again every time and total time to save product went down to 1 minute. That is also not so great but it is grades better than 12 minute wait.
Almost half of that minute is spent creating the temporary table. There needs to be a better way to handle this. Maybe create the table as permanent index which only updates when there are changes to the category structure, etc.

If anyone wants the changes I used, just comment here and I will post them. I have not done any tests on how this affects the data but I assume that there are not that many changes in the database that it would be needed to reload the table every time in current connection. This would probably also be solved by creating the index I talked about.

**Comment by PingusPepan** [comment]
I was able to get down to 7 seconds product save time with keeping the table as index and not recreating it every time.
I get where the 13 times repetition comes from. I have 13 stores set up and it is updating index for every store. Now most of the time comes from updating index for every store. It takes around 500ms to update for each store. 500ms * 13 = 6500ms. If there is a way to speed this up then the saving would be much faster.
With every new store this would only get worse so it is a problem that needs solution. Or am I the only one who has seen this many stores in production?

**Comment by ghost** [comment]
We are having the same issue, ~4k categories in multistore environment on 2.1.9, PHP 7.0.22, MySQL 5.7.19. It takes about 45 seconds to save product.

@PingusPepan Can you share your solution please?

**Comment by PingusPepan** [comment]
I do not have a production-ready solution. Only one good enough for testing because there is no automatic reindexing set up. I am also not sure if this works on 2.1.9 I have tested 2.2.0 only.
However there it is:
All changes are done in one file: `app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php`
You can try add this after line `protected $tempTreeIndexTableName;`:
```
/**
 * @var string[]
 */
protected $tempTreeIndexTableCache = [];
```
Then add this into function `makeTempCategoryTreeIndex` after `$temporaryName = ...`:
```
if (isset($this->tempTreeIndexTableCache[$temporaryName]) && $this->tempTreeIndexTableCache[$temporaryName] === true) {
    return $temporaryName;
}
```
And in the same function add this before `return $temporaryName;`: `$this->tempTreeIndexTableCache[$temporaryName] = true;`

This is just first step but this alone can help if you are using multistore. I have another level set up but that is completely not production ready because the index is not being recreated automatically so I am not sharing right now. Test the first step and see if it even can be applied for 2.1.9 I am not sure if the indexing process is the same between those two versions.

**Comment by PingusPepan** [comment]
@fizzlekettle how did it go? Any improvement?

**Comment by ghost** [comment]
@PingusPepan Sorry for late replay, we are investigating other issues as well.

One team member found out that this function is not executed if you enable indexing on schedule instead of indexing on save. This is good enough solution (for now) as products will be synced from another system instead of using Magento's admin panel.

**Comment by magento-engcom-team** [comment]
@PingusPepan, thank you for your report.
We've created internal ticket(s) MAGETWO-84593 to track progress on the issue.

**Comment by tobias-forkel** [comment]
I confirm that changing the index " Product Categories " to " Indexing On Schedule " in 2.1.2 will fix the issue temporarily. This way I could reduce the loading time from 30 to 1-2 seconds. Before the application was always waiting for this query.

> INSERT INTO `temp_catalog_category_tree_index_c9ee055b` (`parent_id`, `child_id`) SELECT `cc`.`entity_id` AS `parent_id`, `cc2`.`entity_id` AS `child_id` FROM `catalog_category_entity` AS `cc`
 INNER JOIN `catalog_category_entity` AS `cc2` ON cc2.path LIKE CONCAT(`cc`.`path`, '/%') ON DUPLICATE KEY UPDATE `parent_id` = VALUES(`parent_id`), `child_id` = VALUES(`child_id`)

Hope it helps someone.

**Comment by minikist** [comment]
Hello i see i have the same issue magento 2.2.2 

I saw in the database > process Lock time of 100s when it is data sending. (table insert of temp_catalog_category_tree_index_53a4b268) 
All other indexes are fine after tweaking the batchsizecalculator it take less then 5 min to run all indexers.

except this one and full catalogsearch. 
catalog take 30 hours 
this one never finished yet.  

i have the follow setup:
magento 2.2.2
website 1x
store and store view: 64x
simpel products 68.000x
advanced prducts 20x
attributes: 2000x
attributes sets 100x

Server specs:
24 threads
64g memory
with ssd 

i hope someone can help
thanks

**Comment by badi238** [comment]
I am stuck with same issue 
having 1.1 million products 
and 600+ categories 
Any solution about this issue ??
Getting this error 
ERROR 1146 (42S02): Table 'aeroshop_live.temp_catalog_category_tree_index_a8f211ee' doesn't exist
Adding new category or product is taking more than 30 minutes and some time 504 timeout..

**Comment by engcom-Bravo** [comment]
Hello @PingusPepan.
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
