### ISSUE TITLE
Disabled product is not removed from the flat index

### ISSUE THREAD

**Issue by fronke** [magento/magento2#10898]
### Preconditions
1. Magento 2.1.7, MySQL 5.7, PHP 7.0
2. Nginx Server

### Steps to reproduce
1. Enable Flat product index
2. Reindex the catalog
3. Disable a product from the back office (status attribute)
4. Check the catalog_product_flat_1 table

### Expected result
1. The row with the entity_id equals to the disabled product should be deleted from the table

### Actual result
1. The row with the entity_id equals to the disabled product is still in the table

As I understand, in Magento 1.x, there was a method doing this verification but it has been removed from Magento 2 (['updateProductStatus', 'Magento\Catalog\Model\Product\Status']).

**I don't understand if it's normal or not, but for me it's causing many more problems then.**

For example, when I'm getting a production collection in PHP, it's returning me only enabled products plus the disabled products which should have been removed from the flat index table. **So after iterating my product collection and saving them, their status is passed to Enabled (for those which were disable).** It's because the product collection SQL query in the flat catalog is assuming all product from this table are active **(SELECT 1 AS `status`, `e`.`entity_id`, `e`.`attribute_set_id` [...] FROM `catalog_product_flat_1` AS `e`;)**

**Comment by magento-engcom-team** [comment]
@fronke thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
