### ISSUE TITLE
Can't create product category with different settings for different stores using category repository

### ISSUE THREAD

**Issue by sergiynezbritskiy** [magento/magento2#10890]
So, I'm trying to create product category programmatically for several set of stores. The difference is in category name. I have  a few stores with different language, so I need category name 'Eyeglasses' inside english store, and Briller inside Norwegian store. And when I use \Magento\Catalog\Model\CategoryRepository to save the category it always saves category for current store ($this->storeManager->getStore()->getId()). When I simply call method \Magento\Catalog\Model\Category::save(), everything works. Any ideas what is wrong with code below and how to avoid using deprecated \Magento\Catalog\Model\Category::save() method ?
### Steps to reproduce
Here is my code
Constructor

 public function __construct(

        \Magento\Framework\Registry $registry,

        \Magento\Store\Model\ResourceModel\Website\CollectionFactory $websiteCollectionFactory,

        \Magento\Catalog\Model\CategoryFactory $categoryFactory,

        \Magento\Catalog\Model\CategoryRepository $categoryRepository,

        \Magento\Store\Model\ResourceModel\Store\CollectionFactory $storeCollectionFactory,

        \Magento\Framework\App\State $state

    )

    {

        $this->registry = $registry;

        $this->websiteCollectionFactory = $websiteCollectionFactory;

        $this->categoryFactory = $categoryFactory;

        $this->categoryRepository = $categoryRepository;

        $this->storeCollectionFactory = $storeCollectionFactory;

        try {

            $state->setAreaCode('adminhtml');

        } catch (\Exception $ignored) {

        }

    }

and actually my awesome method
 /*
     * Original version of this method receives next params,
     * but in order to simplify reproducing I put them inside method
     * @param string $key
     * @param array $data
     * @param int $order
     */
    private function createCategory()
    {
        $key = 'eyeglasses';
        $data = [
            'uk' => 'Eyeglasses',
            'no' => 'Briller',
            'se' => 'Glasögon',
            'dk' => 'Briller',
            'es' => 'Anteojos'
        ];
        $order = 1;

        //create category for Default Store
        $category = $this->categoryFactory->create();
         //default language is English
        $category->setName($data['uk']);
        $category->setIsActive(true);
        $category->setPosition($order);
        $category->setIncludeInMenu(true);
        $category->setStoreId(0);
        $category->setUrlKey($key);
        $category->setParentId(2);
        $this->categoryRepository->save($category);

        $stores = $this->storeCollectionFactory->create();
        //exclude admin store
        $stores->addFieldToFilter('store_id', ['gt' => 0]);

        /* @var \Magento\Store\Model\Store $store */
        $categoryId = $category->getEntityId();
        /* @var \Magento\Catalog\Model\Category $storeCategory */
        foreach ($stores as $store) {
            $code = $store->getCode();
            if (array_key_exists($code, $data)) {
                $storeId = $store->getStoreId();
                $storeCategory = $this->categoryRepository->get($categoryId, $storeId);
                //override category names for each store
                $storeCategory->setName($data[$code]);
                $storeCategory->setStoreId($storeId);
                 **this line does not work as expected data is always set to store with store_id 1 **
                //$this->categoryRepository->save($storeCategory);
                **this method is deprecated but works perfect **
                $storeCategory->save();
            }
        }
    }

when you look into method \Magento\Catalog\Model\CategoryRepository::save line 77, you will see that the first line of this method is `$storeId = (int)$this->storeManager->getStore()->getId();` and then line 88 ` $category = $this->get($category->getId(), $storeId);`. In my case $storeId is always 1, which refers to Norwegian store, so I'm always updating category for Norwegian store

### Expected result
Using \Magento\Catalog\Model\CategoryRepository::save() method should save category regarding to its storeId;
### Actual result
Category is always saving for current store returned by \Magento\Store\Model\StoreManagerInterface::getStore() method

**Comment by orlangur** [comment]
> `\Magento\Catalog\Model\CategoryRepository::save()` method should save category regarding to its storeId

Where do you see such behavior described in any `@api`-marked interface?

For example, you can use `\Magento\Store\Model\StoreManagerInterface::setCurrentStore`.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by avstudnitz** [comment]
I'd expect the category repository to be able to save category data for different store ids too, so in my opinion it's a bug that the default store view is set.

**Comment by mwr** [comment]
Had the same issue with the ProductRepository. You load a Product for a specific store_id, then make changes and then save it again. The result being the data written to the default store_id which is not what you would expect. Expected Result would be: the data is written to the product for the store_id that was passed with the product object.
It would be ok to have a fallback to the current store_id from the StoreManager if the product / category passed to the repository save does not have a store_id set.

**Comment by jalogut** [comment]
I think the solution is to emulate the store where you want to save the object. At least is what we do.

   ```
    private function saveProductInStore($product, $storeId)
    {
        /** @var \Magento\Store\Model\App\Emulation $this->emulation */
        $this->emulation
            ->startEnvironmentEmulation($storeId, \Magento\Framework\App\Area::AREA_ADMINHTML);
        $this->productRepository->save($product);
        $this->emulation->stopEnvironmentEmulation();
    }
   ```

**Comment by avstudnitz** [comment]
> I think the solution is to emulate the store

I'd say that's a workaround, but not a real solution. Helps for now, but many other developers will stumble over this.

**Comment by jalogut** [comment]
Well yes, with solution I meant workaround.
