### ISSUE TITLE
Address Attributes Show on Form Even When Is Visible set to "No"

### ISSUE THREAD

**Issue by rb124559** [magento/magento2#10907]
### Preconditions

1.   Magento EE 2.1.5
2. 

### Steps to reproduce

1.   Log into Admin Panel
2.   Set Visible on Store Front to "No" for street
3.   Enable Address Fields on Form
4.   Refresh Cache and go to Customer Registration Form and it is still displayed.
5.  If I mark the field as not required, but display on Frontend, the not required is ignored.
6.  The field disappears from the attributes grid.

### Expected result

1.   The field shouldn't be displayed or enforced based on the settings.

### Actual result

1. The field continues to be displayed

Looking at the database, it seems that the code is setting the value "is_visible" is getting set to "No" and there doesn't seem to be a value for "is_visible_on_frontend" like in Magento 1.

**Comment by pboisvert** [comment]
@rb124559 Enterprise customers have access to our support team through the My Account area. PLease file bugs there so they can be tracked against your account.
