### ISSUE TITLE
[2.2.0-rc3.0] Language switcher is broken when using multiple times

### ISSUE THREAD

**Issue by hostep** [magento/magento2#10908]
### Preconditions
1. PHP 7.0.22

### Steps to reproduce
1. Install Magento CE 2.2.0-rc3.0 using composer
2. Switch to developer mode
3. In the backend, make sure you have 2 storeviews (in my example: Dutch & English)
4. Reindex & flush caches
5. Load the frontend
6. Using the language switcher in the header, switch from the default storeview (Dutch in my example) to English, the url changes to: `https://example.com/?___store=en`
7. Using the language switcher in the header, switch again from English to Dutch, the url changes to: `https://example.com/?___store=en?___store=nl` and the shop crashes

### Expected result
1. The url should be `https://example.com/?___store=nl` and the shop shouldn't crash

### Actual result
1. The url is `https://example.com/?___store=en?___store=nl` and the shop crashes with the message:
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested store is not found

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested store is not found
#0 vendor/magento/module-store/Model/StoreManager.php(168): Magento\Store\Model\StoreRepository->get('en?___store=nl')
#1 vendor/magento/module-store/App/Action/Plugin/Context.php(85): Magento\Store\Model\StoreManager->getStore('en?___store=nl')
#2 vendor/magento/framework/Interception/Interceptor.php(121): Magento\Store\App\Action\Plugin\Context->beforeDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Magento\Framework\App\Request\Http))
#3 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#4 generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#5 vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#6 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#7 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#8 vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#9 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#14 vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#16 pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#17 {main}
```

### Discussion

This was only very recently broken, in commit: https://github.com/magento/magento2/commit/c3ea1f55aa21ca14796118128a302d4f4b139450, the changes in the file `lib/internal/Magento/Framework/App/Request/Http.php` cause this.

Also: please change this [typo](https://github.com/magento/magento2/blob/c3ea1f55aa21ca14796118128a302d4f4b139450/lib/internal/Magento/Framework/App/Request/Http.php#L175) from `removeRepitedSlashes` to `removeRepeatedSlashes`, so this method has the same name as in [Magento 2.1](https://github.com/magento/magento2/blob/a2f2893/lib/internal/Magento/Framework/App/Request/Http.php#L176)

### Possible solution

If we change [this line](https://github.com/magento/magento2/blob/c3ea1f55aa21ca14796118128a302d4f4b139450/app/code/Magento/Store/Model/Store.php#L1139) from:
```php
$requestString = $this->_url->escape(ltrim($this->_request->getRequestString(), '/'));
```
to:
```php
$requestString = $this->_url->escape(ltrim($this->_request->getOriginalPathInfo(), '/'));
```

It works again as expected, but I'm not sure yet if this is the correct solution.

**Comment by magento-engcom-team** [comment]
@hostep thank you for your bug report.
We've created internal ticket MAGETWO-75448 to track progress on the issue.

**Comment by vrootwoot** [comment]
Apparently the issue only occurs from the homepage, starting working on it.

**Comment by BlackIkeEagle** [comment]
@vrootwoot you still working on this? I have this issue too while I'm working on some other issue in the store switcher

**Comment by vrootwoot** [comment]
@BlackIkeEagle won't have the time to fix it.
 
Apparently correct way would be to add changes to getTargetStorePostData
in app/code/Magento/Store/Block/Switcher.php. 
And also change the entry points in the Switcher Block as well.

**Comment by LuisChaves** [comment]
In addition to changing the line of code suggested by hostep, to also remove "?___ store". Change line 228 "$store->getCurrentUrl(false)," to "$this->getUrl ('stores/store/switch' ), "from the file" module-store \ Block \ Switcher.php "

**Comment by selusi** [comment]
However, the bug is much more complex, because if you change the language on page of the product details or on a category page the app give a not found page, because does not translate the urlrewrite. 
In the previous version Magento 2.1.9 the switcher worked fine.

**Comment by selusi** [comment]
The @LuisChaves solution solves the problem definitively, but at this point the **getCurrentUrl** method in the **Store** class is absolutely useless.

I've deleted the getCurrentUrl () method from Magento \ Store \ Model \ Store and modified line 228 of the getTargetStorePostData function in Magento \ Store \ Block \ Switcher as follows:

```php
$this->getUrl('stores/store/switch',  ['_secure' => $this->_storeManager->getStore()->isCurrentlySecure()]),
```


Finally everything works well.

NOTE: I would like to point out another bug in the store module, which I found a solution to the following link: 
**Magento 2.2 fix Home Page error if store view is not defined** https://github.com/magento/magento2/issues/11453

**Comment by hostep** [comment]
@selusi: just FYI, you've changed the code back to how it was before commit https://github.com/magento/magento2/commit/508f1ef93558c40f96cc9524e6a205494f90a7ba, in this commit, they fixed the storeswitcher when you work with multiple domain names since it used to store the wrong store code in a cookie which has as a result that we ended up in an endless redirect from one domain name to the other.
It might be worth to test if it still works when switching stores with multiple domain names if you revert that line back to `$this->getUrl('stores/store/switch')`, but I have the feeling that the original problem will be back if you do this.

(unrelated, but this page might be worth checking out for formatting your comments on github a bit better: https://guides.github.com/features/mastering-markdown/, please check the 'code' tab in the Examples :wink:)

**Comment by selusi** [comment]
@hostep Thank you for the clarification. I apologize, because I did not read the commit https://github.com/magento/magento2/commit/508f1ef93558c40f96cc9524e6a205494f90a7ba you rightly mentioned. 
So everything is again in question, because your code solve only a part of issue.

**Comment by selusi** [comment]
To fix the duplicate query in the url It is possible to modify the vendor/magento/module-store/model/Store.php file ([Download the Complete Code](https://github.com/magento/magento2/files/1382403/Store.txt)):
So as I described in a comment on: 
## In magento 2.2 Changing language twice gives error [bug] https://github.com/magento/magento2/issues/11379

Howewer this solution does not solve the bug interly.

**Comment by thiagolima-bm** [comment]
@okobchenko PR #11337

**Comment by okorshenko** [comment]
the issue has been fixed and delivered to 2.2-develop branch. WIll be available with 2.2.2 release

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1285 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - ad6c0af7dddbe2855a336acd3fd55994851e6d26
 - 6d3d70a72f08cba36c3aef6b59eea8db40eb4071
 - 6b0c02c5fd00d7a4237c4e1fae40dc265e3e43c3
 - c8abb139f8006826989fe4231dabc21fd4a02fd0
 - c6a9b5f7b13554958b547f387637c4288eb60b0b
 - c867b81af936e01a3d8ba8baa7128de06a5b7cd5
 - 88a3ad00d3ca97da847531c86bf64055dc1d790b
 - d87e316a2d6ee55debe2e712359adba8cb70fdb2
 - c76b04c9acde117c1021270500c8ded6954f6f05
 - 5ae21099aaa19699525c798f9ac0ef10db47b311
 - 931133abf574f1db96450f11f5980ef359d32967
 - 4c927a0585f11921c5e422b7e4a15b787e6338bd
 - 060a8f9f2b08ed97b31667eb76cace1dc0e642be
 - 4da2a7d2657b0da67f8be43bffc85f04b5b7144e
 - 008ef5583892d73c04628f003a2ce3d97fe0ed72
 - d3642e88d26a9240a1a4d648d37d984a785672a9
 - d37ce089d56c230f5896d5d7e922bd928b3726e6
 - b22b232563359f9cbcbf09709e63a87be7e81446
 - 6c02a2d3a272e872d549881d91ed6d5235a33f77
 - f2ec2ea175469636acec0bf9f65f0601854f89a2

The fix will be available with the upcoming patch release.

**Comment by mariamghalleb** [comment]
@magento-engcom-team the link doesn't work ..

**Comment by MrDaar** [comment]
It's not good code, and it's not thoroughly tested, but here's a temp fix if you're currently experiencing this issue:
```
<type name="Magento\Store\Block\Switcher">
    <plugin name="Vendor_Module_Plugin_Magento_Store_Block_Switcher"
            type="Vendor\Module\Plugin\Magento\Store\Block\Switcher"
            sortOrder="0"
    />
</type>
```
```
<?php
namespace Vendor\Module\Plugin\Magento\Store\Block;

class Switcher
{
    /**
     * Returns target store post data
     *
     * @see https://github.com/magento/magento2/issues/10908
     * @param \Magento\Store\Block\Switcher $subject
     * @param string $postData
     * @return string
     */
    public function afterGetTargetStorePostData(
        \Magento\Store\Block\Switcher $subject,
        $postData
    ) {
        $data = json_decode($postData, true);

        if (empty($data['action'])) {
            return $postData;
        }

        if (substr_count($data['action'], '___store') < 2) {
            return $postData;
        }

        $data['action'] = preg_replace('/___store=(.*?)___store/', '___store', $data['action']);

        return json_encode($data);
    }
}
```
Let me know if it works for you.
