### ISSUE TITLE
Extending the Magento Topmenu in custom module doesn't work after 1.7

### ISSUE THREAD

**Issue by LeonHunterUk** [magento/magento2#10900]
### Preconditions

1. Magento 2 version 2.1.8, and 2.1.9
2. PHP 5.6

### Steps to reproduce

1. Install Magento 1.8 via composer and install using the web installer
2. Create a custom module in app/code. Set di.xml preference to use new Topmenu module. Create module to extend Topmenu and replace the function which renders the menu HTML. 

Code to extend:

namespace Mymodule\Topmenu\Plugin;

use \Magento\Framework\DataObject\IdentityInterface;
use \Magento\Framework\View\Element\Template;
use \Magento\Framework\Data\TreeFactory;
use \Magento\Framework\Data\Tree\Node;
use \Magento\Framework\Data\Tree\NodeFactory;

class Topmenu extends \Magento\Theme\Block\Html\Topmenu
{

### Expected result

1.  The topmenu should now produce the markup you have told it to in your new module

### Actual result

1. Fatal error: Call to a member function setOutermostClass() on null in /var/www/demo.co.uk/app/code/Mymodule/Topmenu/Plugin/Topmenu.php on line 36
2. It is like the Magento Topmenu is not being extended so the functions are not available in the custom module I am creating
3. This same technique works fine in 2.1.7 but stops working in later versions

**Comment by orlangur** [comment]
When you rely on class internal implementation and/or use inheritance to customize core behavior, which is not a recommended way, there is no surprise such fragile code may break with upgrade.

https://github.com/magento/magento2/commit/e32af8220551cf3d41932931051836ca6428c431#diff-454601ea9afd086413ac90923ae9ccaaR95

Your code should use `getMenu()` now instead of `$this->_menu` to work properly.

**Comment by LeonHunterUk** [comment]
Thanks, can you advise the recommended way to change the way Magento 2 renders the html for its top menu?

**Comment by orlangur** [comment]
The fact inheritance is strongly discouraged does not mean you can always avoid it, just that you should be prepared for consequences in such case.

Depending on the needed customization you could probably need only some plugins or observers for `TopMenu`, worst case is when you need to change the `_getHtml` internals. By the way, if it would be implemented nowadays, it would be `private`, not `protected`.

`TopMenu` is a known pain point for customization: https://github.com/magento/magento2/issues/2068 So there is no good enough recommendation for it yet. Some approaches possible (from most preferable to less preferable):

1) Avoid using it, if you understand recursion you can do a better implementation from scratch in no time
2) Just copy the whole class to your module, commit it and do necessary changes on top (no inherited functionality used). You can read more about such approach here https://ocramius.github.io/blog/when-to-declare-classes-final/ (scroll to "just copy the entire class body and commit it to my own code-base" comment, link does not work)
3) Redefine some inherited methods only, add the note in class PHPDoc that it should be checked after each upgrade or cover with automated test

**Comment by LeonHunterUk** [comment]
Thanks for your help!
