### ISSUE TITLE
installation via command line error

### ISSUE THREAD

**Issue by melaxon** [magento/magento2#1090]
tried to install magento with sample data like this:

 php -f index.php install --base_url=http://localhost.loc/magento2/ --backend_frontname=admin --db_host=localhost --db_name=magento2 --db_user=root --admin_firstname=Mage --admin_lastname=Bento --admin_emai=melaxon@bk.ru --admin_username=admin --admin_password=BraviA*58 --language=en_US --currency=USD --timezone=America/Chicago --use_sample_date=true

and received an error:

a:3:{i:0;s:38:"DOCUMENT_ROOT variable is unavailable.";i:1;s:881:"#0 /Users/yannislivasov/Sites/magento2/lib/internal/Magento/Framework/App/Http.php(181): Magento\Framework\App\SetupInfo->__construct(Array)
#1 /Users/yannislivasov/Sites/magento2/lib/internal/Magento/Framework/App/Http.php(210): Magento\Framework\App\Http->redirectToSetup(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#2 /Users/yannislivasov/Sites/magento2/lib/internal/Magento/Framework/App/Http.php(137): Magento\Framework\App\Http->handleBootstrapErrors(Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException))
#3 /Users/yannislivasov/Sites/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(250): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#4 /Users/yannislivasov/Sites/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#5 {main}";s:11:"script_name";s:9:"index.php";}

Magento\Framework\App\SetupInfo->__construct(Array) requires $server['DOCUMENT_ROOT'] which is not defined when running via terminal

**Comment by mazhalai** [comment]
Looks like you are installing using magento's root index.php. please update your install script to use setup/index.php or traverse to the setup folder and try the command again. Also, can you check your Apache configuration? Is it possible `DOCUMENT_ROOT` has not been set?

**Comment by melaxon** [comment]
>>Looks like you are installing using Magento's root index.php. Please update your install script to use setup/index.php or traverse to the setup folder and try the command again.

I will try this.

>>Also, can you check your Apache configuration? Is it possible DOCUMENT_ROOT has not been set?

$_SERVER['DOCUMENT_ROOT'] is not set and has no meaning when you run script via command line

**Comment by mazhalai** [comment]
> I will try this.

Please let us know if that worked.

> $_SERVER['DOCUMENT_ROOT'] is not set and has no meaning when you run script via command line

Yes, you are right it is not needed for command line, but you will need to set it eventually to get the website running.

**Comment by melaxon** [comment]
>> ...you will need to set it eventually to get the website running
of course I will. I thought it will be fixed in the next beta release.

**Comment by mazhalai** [comment]
@mexlon, there is nothing to be fixed, it is expected that install works from `setup` folder.
For more information:
http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli.html

**Comment by buskamuza** [comment]
@melaxon , you have this error with unset `$_SERVER['DOCUMENT_ROOT']` just because you were trying to run `<root>/index.php`, intended for Web use only, as a CLI. This script is used only as a web-site entry point, it's not used for CLI commands. Just try `php setup/index.php` for CLI commands and use installed Magento application as usual. You should not expect any issues related to `$_SERVER['DOCUMENT_ROOT']`
