### ISSUE TITLE
Please add option to avoid merging of cart on login of customer

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1091]
Please add option to avoid merging of cart on login of customer

Many customers just do not understand

Something like this
https://github.com/jacquesbh/jbh_cartmerge
http://stackoverflow.com/questions/5638173/how-do-i-stop-magento-merging-the-basket-on-login
http://www.blog.magepsycho.com/clear-abandoned-cart-items-during-login-in-magento/

**Comment by asemenenko** [comment]
Hi Seansan,

Based on what is requested i assume problem can be resolved in two ways:
1. Replace the old cart content with new "guest" cart.
2. Ask customer if he or she wants to merge or replace the previous items instead of just dropping those. 

Above can be controlled by a parameter.

/regards

**Comment by waynetheisinger** [comment]
:+1:  this is sorely needed - in our user tests the behaviour in  Magento1 ALWAYS annoys the tester

**Comment by asemenenko** [comment]
Hi Waynetheisinger,

It is better to run A/B testing on this in order to set proper default parameter value. QA/Tester is not the best source of decision :-)

/regards

**Comment by waynetheisinger** [comment]
I have just realised I misread your post but how I misread it is I think better than what you were in actual fact suggesting.

I thought you were saying that Magento 2 would now havethe concept of a guest cart and an account cart, and that when the customer checked out they would be presented with a choice. (wording would need to be better written but off the top of my head)

> You have items both in your present cart. But you also have items stored in a previous cart. Would you like to:
> 1. Continue with your present items
> 2. Merge your saved items into your present purchase

**Comment by waynetheisinger** [comment]
I think its always better give customers the power - however for store owners who want to dictate the behaviour, which decision favoured could also be set and locked in admin which would remove the customer's prompt and choice.

**Comment by asemenenko** [comment]
Thanks for a quick reply.

I suggest to have a parameter in system configuration, something like this:
[Shopping Cart]
Cart Action on Log-in = Automatically replace cart content/Ask customer

Default value for the parameter still needs to be defined.

In this case merchant can choose whether to just replace the cart without adding an extra step or ask the customer to make a decision.

**Comment by asemenenko** [comment]
Improvement is captured in the MAGETWO-20045

**Comment by seansan** [comment]
Euh don't forget the original request

Option 3: do not ask. And don't merge. 

Important!






Sent from my iPhone.

On 17 Mar 2015, at 11:03, Andrii Semenenko <notifications@github.com> wrote:

Thanks for a quick reply.

I suggest to have a parameter in system configuration, something like this:
[Shopping Cart]
Cart Action on Log-in = Automatically replace cart content/Ask customer

Default value for the parameter still needs to be defined.

In this case merchant can choose whether to just replace the cart without adding an extra step or ask the customer to make a decision.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Please-add-option-to-avoid-merging-of-cart-on-login-of-customer/idi-p/46610).

**Comment by seansan** [comment]
It was acknowledged ... and I dont believe in a FORUM being the proces and
method to store important feedback and sometimes even code suggestions ...
it will get lost, forgotten - the forum will be killed in 2018 or 2019 just
like the previous one. I never understood why one did not open a simple
uservoice account or JIRA account and log it there.
