### ISSUE TITLE
Magento 2.1.9 import a 319KB with 357 products svc file successfully, then failed to import a 456KB with 280 products svc file from admin. No error mesage showed up.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10912]
### Preconditions

1. Magento 2.1.9 CE
2. import products from backend

### Steps to reproduce

1. import first 357 products svc file successfuly
2. import second 280 products svc file without error message
3. there is still 357 products from the first svc file, no new products created from the second svc file

### Expected result

1. there should be 637 products, not the original 357 products.

### Actual result

1. [Screenshot, logs] no products imported by second svc products file.

**Comment by magento-engcom-team** [comment]
@adamshuy please add required information to issue description (not to the title)

**Comment by IlnitskiyArtem** [comment]
Hi @adamshuy. Please, provide more information about your case, I cannot reproduce it on 2.1.8 and 2.1.9. Can you confirm that all of the products you trying to import have different SKU? Do you use Add/Update or Replace as Import Behavior?

**Comment by ghost** [comment]
yes, all products have different skus, and it's Add/Update Import Behavior.  I am using WAMP as working environment.  Please let me know your working environment.   Your earliest attention will be much appreciated.

**Comment by orlangur** [comment]
Can you reproduce an issue using a supported operating system: http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html? Note that Windows is not in the list.

**Comment by magento-engcom-team** [comment]
Hi @ghost unfortunately, we can not reproduce the issue on 2.1.9, 2.2.0. Please, try your flow on clean magento installation and supported OS
