### ISSUE TITLE
Critical issue to manage the correct Date format in different locale interface

### ISSUE THREAD

**Issue by selusi** [magento/magento2#10910]
### Preconditions
1. Magento CE 2.1.9 with sample data installed
2. PHP 7.0.22
3. MySql 5.6.16

### Steps to reproduce
1. Set the Interface locale of current adim user on a Country which has date format different by m/d/y
2. Open the Edit Customer form on the backend panel 
3. Go to Account Information form
4. Modify Date of Birth
5. Save data

### Expected result
1. When you open the Account Information form, the date of birth should be the same as the saved date. 

### Actual result
1. The date of birth is set to the date of the current day also if in DB the date is correct.
2. When you save the data you are forced to reset the date of birth, otherwise the current date will be saved as the date of birth.

### Additional comments
I belive there is a bug in the initialization of the code that override datepicker in calendar.js. 
Surely it is a client-side bug, because if you change the date and save it, it is saved correctly.

**Comment by orlangur** [comment]
Thanks for the well-formed bug report! Such issue is already tracked as https://github.com/magento/magento2/issues/10580.
