### ISSUE TITLE
Sku => Entity_id relations are fetched inefficiently when inserting attributes values during product import

### ISSUE THREAD

**Issue by diwipl** [magento/magento2#10920]
Product import is not fetching relation between products sku and entity_id efficiently when inserting attributes data.
### Preconditions
1. Magento 2.1.9

### Steps to reproduce
1. Run import of products from sample csv

### Expected result
1. All relations are loaded using one query per bunch

### Actual result
1. Relations are loaded one by one (multiple times for multiple attributes types)
<img width="298" alt="screen shot 2017-09-17 at 13 35 00" src="https://user-images.githubusercontent.com/3406741/30520423-27ddb6d0-9bad-11e7-9ce6-4253213a97ae.png">

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @diwipl. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1287 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
