### ISSUE TITLE
Less Pre-Processing

### ISSUE THREAD

**Issue by JamesAnelay** [magento/magento2#1092]
So I am having an issue at the moment where it seems (and I may be wrong) that .less files are being processed SLOWLY client side. The page first loads with what seems to be no/very little css styling and then 6 seconds or so later the css jumps into action and the page beings to look ok.

Is this some sort of fallback so if Magento can't process the .less files for whatever reasons then it is done client side? It should all be done in Magento and save correct?

Screencast here : http://g.recordit.co/7imi9k07sJ.gif

Thanks.

**Comment by JamesAnelay** [comment]
Ok so it would appear that my problem would be because I have Developer Mode on it seems that sets compress to false and then all the files just stick to less files and are not preprocessed (untill later by the client).

        $options = ['relativeUrls' => false, 'compress' => $this->appState->getMode() !== State::MODE_DEVELOPER];

Mabey I just have a slow setup but developing with 'compress' off for me it's way too slow. In my humble option there should be an option to set less pre-processing on and off which isn't coupled with Developer Mode.

**Comment by godban** [comment]
Hey @JamesAnelay

You are completely right, client side Less preprocessing for Developer Mode will be optional in next releases.

**Comment by JamesAnelay** [comment]
@godban Perfect :) I closed the ticket because it was a bit of a mess/train of thought, but glad to see you understood and are planning it allready.
