### ISSUE TITLE
2.1.8 CE - Unable to set attribute set for new product

### ISSUE THREAD

**Issue by mozenpo** [magento/magento2#10938]
I have a clean install of Magento CE 2.1.8 and then imported my data from Magento 1.9. Now while I want to add new products on my old attribute sets which were created on M1, page is loading over and over and I get below message in chrome dev tool console.

Uncaught TypeError: Cannot read property 'length' of undefined
    at UiClass.getNewData (dynamic-rows-grid.js:180)
    at UiClass.initElements (dynamic-rows-grid.js:86)
    at setNested (objects.js:43)
    at Object.nested (objects.js:117)
    at UiClass.set (element.js:301)
    at updateValue (links.js:57)
    at Function.notifySubscribers (knockout.js:1103)
    at Function.observable.valueHasMutated (knockout.js:1300)
    at UiClass.observable [as recordData] (knockout.js:1285)
    at setNested (objects.js:43)
![untitled](https://user-images.githubusercontent.com/32037091/30521823-28715632-9bdb-11e7-9413-b1e20b0af7e2.png)

**Comment by cchamikara** [comment]
@mozenpo This is because with 2.1.x versions they have added new attribute group called "Bundle Items" group wrapped with "shipment_type" attribute and your custom attribute sets may not contain that group.

So what you have to do is , goto Store -> Attributes -> Attribute Sets and select your custom attribute -> Under the Groups -> Add New -> add new group call "Bundle Items" then drag and drop "shipment_type" to the Bundle Items group -> Save

**Comment by mozenpo** [comment]
@chamalC but i have done this for one of my attribute sets and it does not work. in details, i have added all new groups which there was not in my attribute set and now layout of my attribute set is same as a default attribute set in 2.1.8...
what should i do now?

**Comment by magento-engcom-team** [comment]
@mozenpo please provide more information in Steps to Reproduce. Please, add sample data to the issue that we can try

**Comment by nevillesmith** [comment]
Do you need the info and issue doc stated here to provide the steps for re-creation or does one email or IM you. We have a system going production and this is a snag that seems easily resolved but could very well be a bottleneck.

**Comment by mozenpo** [comment]
finally i have tried one more time and fortunately this issue solved! the layout of attribute set and each group container must be as same as the default one of M2.
