### ISSUE TITLE
Magic tool box install error 

### ISSUE THREAD

**Issue by sachinsachin** [magento/magento2#1093]
Installation

Fatal error: Class 'Mage' not found in C:\wamp\www\magento\magicslideshow\magictoolbox.installer.magento.class.php on line 155

**Comment by buskamuza** [comment]
@sachinsachin , hi once again.
Please, take into account that this GitHub resource is for **Magento 2** only.
As I understand you're trying to add this library to Magento 2 - https://www.magictoolbox.com/magiczoom/modules/magento/ According to its official page, it doesn't support Magento 2, so it's incompatible.

If you have any questions related to Magento 1, please, use Magento 1 resources, so you'll get answers more efficiently. See http://magento.com/help/overview

**Comment by maksek** [comment]
Hi @sachinsachin, it is pure Magento2 repository and we addressing only Magento 2 related questions, issues. Questions related to Magento 1 will not be addressed here. Please go to proposed sources for Magento 1.
