### ISSUE TITLE
cannot create new size that name is "0"

### ISSUE THREAD

**Issue by jerome-zhang** [magento/magento2#10942]
### Preconditions

1. Magento EE 2.1.8
2. php 5.6

### Steps to reproduce

1. go to BE admin
2. on left navigation, go to STORES > Attributes > Product
3. search by "Attribute Code" and go to “size”
4. under "Manage Swatch (Values of Your Attribute)" adding new size: "0"
5. click "Save and Continue Edit"

### Expected result

1. new size "0" saved to system

### Actual result

1. new size is not saved to system, it errors out: "Admin is a required field in the each row". Please see video: https://www.screencast.com/t/6cKL39ppM

**Comment by orlangur** [comment]
Thanks for the report, fix will be available in `2.1.10`, see https://github.com/magento/magento2/issues/10818#issuecomment-328049297 for details.

**Comment by jerome-zhang** [comment]
Thank you and what is the expected release date for 2.1.10?

**Comment by orlangur** [comment]
@jerome-zhang sorry, I don't have such information and it is not publicly available as far as I know. Taking into consideration it is just a regular patch release (previous such release was 2.1.8 with 2.1.9 reserved as a security release in advance) I assume 2.1.10 is going to be released in a month or two.

**Comment by mrpatrick** [comment]
This doesn't appear to be fixed - We are still seeing the issue in v2.2.3.  I also don't see any reference to the fix in the CHANGELOG.  Can't someone point me to where this was fixed?
