### ISSUE TITLE
Disappeared css from back and frontend

### ISSUE THREAD

**Issue by enrybisco** [magento/magento2#10949]
### Preconditions

1. php 7
2. Magento 2

### Steps to reproduce

1. In the main folder public_html and in commented out #followsymlink
2. In the folder pub/media in the htaccess file: deleted "All" from 1st line:  " Options  All-Indexes"
3. and commented out the line:  #    Options +SymLinksIfOwnerMatch
4.From SSH in Putty I have run: php bin/magento clean and indexer:index

### Expected result

1. Images of created products .png format should be visible

### Actual result

1. [Screenshot, logs]
No images(no hyperlink working) + no css both in the backend and frontend

**Comment by orlangur** [comment]
Will images and css work if you restore original `.htaccess`?

**Comment by enrybisco** [comment]
No I have tryed to restore the file in the folder pub/media in the htaccess file: readded "All" in1st line: " Options All-Indexes"
and taken off the comment from the line: # Options +SymLinksIfOwnerMatch
but nope it's not working

**Comment by orlangur** [comment]
Try to restore original `.htaccess` files by copying or `git reset` instead of editing and re-run all relevant command, like static content deploy, reindexing etc after that.

**Comment by enrybisco** [comment]
I have run the magento setup:static-content:deploy [<list of languages>] 
 because the language of the website (all folders it_IT were gone):
the situation now is that the backend is working but not the css in the frontend

**Comment by enrybisco** [comment]
... deploy it_IT

**Comment by orlangur** [comment]
Try switching to en_US as it_IT does not belong to this repo anyway.

What did you try to achieve by changing `.htaccess` by the way?

For the sake of clean bug report, please do a clean Magento 2 installation and perform necessary steps in order to reproduce a bug, then please put an updated version of steps into description.

**Comment by enrybisco** [comment]
The changes in the .htaccess are needed due to a configuration compatibility with our Apache server: in the previous Magento 1.9x .png files were not visible if this action was not performed.

Thank you
Enrico

**Comment by magento-engcom-team** [comment]
@enrybisco, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
