### ISSUE TITLE
Admin Product Atrribute date time picker is not appearing

### ISSUE THREAD

**Issue by nmohanan** [magento/magento2#10945]
### Preconditions

1. Magento version 2.1.6,2.1.7,2.1.8,2.1.9
2. Php 7.0.0

### Steps to reproduce

1. I have tried to build an date time picker in magento product attribute
2. Instead of date time field only date field is appearing,
3. Also i have tried jquery for datetime picker, it is also not rendering in the admin side
4. $eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'start_date',
            [
                'type'                    => 'datetime',
                'backend'                 => 'Magento\Catalog\Model\Attribute\Backend\Startdate',
                'frontend'                => '',
                'label'                   => 'start date',
                'note'                    => 'Add start date with 24 hours time format Ex: mm/dd/yyyy hh:mm:ss(05/01/2017 13:10:10)',
                'input'                   => 'date',
                'frontend_class'          => 'starting_date',
                'source'                  => '',
                'global'                  => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_STORE,
                'visible'                 => true,
                'required'                => false,
                'user_defined'            => true,
                'default'                 => '',
                'searchable'              => false,
                'filterable'              => false,
                'comparable'              => false,
                'visible_on_front'        => true,
                'used_in_product_listing' => true,
                'unique'                  => false,
                'apply_to'                => '',
                'is_used_in_grid'         => true,
                'is_visible_in_grid'      => true,
                'is_filterable_in_grid'   => true,
                'group'                   => 'Customattribute',
            ]
        );

### Expected result

1. Instead of date time picker only date field is coming, tried in 2.1.6,2.1.7,2.1.8,2.1.9

### Actual result

1.  Date time picker

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by nmohanan** [comment]
So Magento does not includes this functionality with the community edition?

**Comment by orlangur** [comment]
Both CE and EE in `Catalog Input Type for Store Owner` contain only "Date" option.

Thus to create Date and time input you need to do a proper customization (quite easy).

As your current attempt of customization is buggy
> 'input' => 'date',

and does not work, Stack Exchange can be used to get some assistance.

**Comment by nmohanan** [comment]
I have asked a question regarding this, but no reply from anyone of them, it is great if you could help me on this. https://magento.stackexchange.com/questions/193609/tried-to-implement-the-datetime-picker-magento2-but-only-date-is-coming
