### ISSUE TITLE
magento could not install on wamp

### ISSUE THREAD

**Issue by sachinsachin** [magento/magento2#1095]
Index of /magento

[ICO]	Name	Last modified	Size	Description
[PARENTDIR]	Parent Directory	 	-	 
[   ]	CHANGELOG.md	2015-03-16 06:11	16K	 
[   ]	CONTRIBUTING.md	2015-03-16 06:11	1.2K	 
[   ]	LICENSE	2015-03-16 06:11	1.0K	 
[   ]	PORTING_INFO	2015-03-16 06:11	1.6K	 
[DIR]	bin/	2015-03-17 01:38	-	 
[   ]	composer.json	2015-03-16 06:11	1.6K	 
[   ]	composer.lock	2015-03-16 06:11	42K	 
[DIR]	doc/	2015-03-17 01:38	-	 
[   ]	magento-1.9.1.0-2015..>	2015-03-16 22:04	33M	 
[   ]	phpunit.xml.dist	2015-03-16 06:11	898	 
[DIR]	res/	2015-03-17 01:38	-	 
[DIR]	src/	2015-03-17 01:38	-	 
[DIR]	tests/	2015-03-17 01:38	-	 
[DIR]	vendor/	2015-03-17 01:40	-	 
Apache/2.4.9 (Win64) PHP/5.5.12 Server at www.sagun.com Port 80

**Comment by hirenvasani** [comment]
What error are you getting?

**Comment by sachinsachin** [comment]
content not found

**Comment by mazhalai** [comment]
@sachinsachin How did you download Magento 2? Your folder structure looks significantly different than what is hosted [here](https://github.com/magento/magento2).  Please clear your folder and follow instructions posted here: http://devdocs.magento.com/guides/v1.0/install-gde/bk-install-guide.html

**Comment by sachinsachin** [comment]
no i have downloaded magento 1 but i could not install able to install magento 1 on wamp. please help me.

**Comment by maksek** [comment]
Issues is closed and locked. This is github for magento 2 only.

**Comment by tedpietrzak** [comment]
@sachinsachin - This forum is specifically for issues related to Magento 2.  If you are truly trying to install Magento 1, please refer to the "How To Get Started" section on https://www.magentocommerce.com/products/downloads/magento/ 

Please do not abuse access to our core development team.
