### ISSUE TITLE
Localized dates can't be used in backend forms, especially the product form (2.1.8 and 2.1.9)

### ISSUE THREAD

**Issue by wolef** [magento/magento2#10953]
If you'll save a date in product form (i.e. 'mark product as new') not the selected date is shown after reloading the form. No you'll see the current date.

There's an JS Error in the console.
Error creating Date object from string.  jquery-ui-timepicker-addon.js:2118:4

The bug is only available if you use a different language then en_US. In the database the chosen date is saved. The problem is just on rendering the date in the backend. But if you'll save the product again now the filled in current dates will be saved.
The problem is that you can't really pre-set date fields. The problem comes with 2.1.8 since you're starting using a localized date format in the fields.

### Preconditions

1.  Version 2.1.8 & 2.1.9
2. 

### Steps to reproduce

1. Use a different language and localisation in backend than en_US (here it's de_DE)
2. Save a product with filled in fields for mark as new.
3. After the pages reload there's just the current date.
4. If you'll save again no you have also the current date in the database

### Expected result

1. The chosen and saved date should be shown in the form 

### Actual result

1. [Screenshot, logs]

**Comment by orlangur** [comment]
Thanks for the bug report! Such issue is already tracked as https://github.com/magento/magento2/issues/10580.
