### ISSUE TITLE
Magento 2 Customer Object via API has no increment_id

### ISSUE THREAD

**Issue by staniag** [magento/magento2#10952]
### Preconditions
Current Magento build 2.1.9/2.2.0-rc30 php 7.0.22, mysql 5.7.19
### Steps to reproduce
Api GET on magento2host/rest/all/V1/customers/{id}
### Expected result
As result you get a JSON with customer data containing increment_id
<pre>
{
    "id": id,
    "increment_id": id,
    "group_id": id,
    […]
    "addresses": [
        {
            "id": id,
            "customer_id": id,
            […]
        }
    ],
   […]
}
</pre>
### Actual result
Increment_id is not in the result set
<pre>
{
    "id": id,
    "group_id": id,
    […]
    "addresses": [
        {
            "id": id,
            "customer_id": id,
            […]
        }
    ],
   […]
}
</pre>

### Additional information
We do have a solution for this issue and would like to make a pull request.

**Comment by orlangur** [comment]
What is the basis of expected result? I don't see `increment_id` mentioned in https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Api/Data/CustomerInterface.php

**Comment by staniag** [comment]
increment_id is not  EAV attribute, no sense to use it as extension attribute.
increment_id is in customer_entity table, but not in CustomerInterface.php
Many companies use increment_id field as customer id different needs such as billings and other.
It is logical to have it in Interface with getter and setter.

**Comment by orlangur** [comment]
Extension attributes have nothing to do with EAV.

Even in core some data, like `GiftMessage`, is populated using extension attributes mechanism: https://magento.stackexchange.com/a/121159

API interfaces cannot be expanded randomly to the needs of each particular merchant. If you need some additional data in your extension, just add it using plugins-interceptors.

GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.
