### ISSUE TITLE
skip test?????????

### ISSUE THREAD

**Issue by kiner00** [magento/magento2#10966]
https://github.com/magento/magento2/blob/479f137cf47f6907aa5061b36b183295387c0968/app/code/Magento/Catalog/Test/Unit/Model/ProductRepositoryTest.php#L149

**Comment by orlangur** [comment]
Please use the issue reporting [guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

Already addressed in https://github.com/magento/magento2/commit/015c75f61aac6e1c93d236481d595cc40d409c41.
