### ISSUE TITLE
2.1.9. System -> Integrations is empty / creating a new not possible

### ISSUE THREAD

**Issue by MirkoHuf** [magento/magento2#10960]
### Preconditions
Magento 2.1.9

### Steps to reproduce

1. update our magento 2 system to 2.1.9 yesterday - but now the web request still not working
2. try to create a new token under System -> Integrations
3. the page is empty - if I click an Add new integration the next page is still empty. Only a back and save button in the right top corner. If I click on save I got:
Notice: Undefined index: all_resources in /var/www/magento/vendor/magento/module-integration/Controller/Adminhtml/Integration.php on line 129

Any workaround for me to create a new authentication token for our webservice REST calls?

### Actual Result
Thanks in advance.
![2017-09-19_14h42_51](https://user-images.githubusercontent.com/7764831/30592874-dfdb0408-9d48-11e7-9698-bcb27f7d64e3.png)
![2017-09-19_14h42_05](https://user-images.githubusercontent.com/7764831/30592875-dff6a168-9d48-11e7-8996-8e3dae5a254c.png)

### Expected Result
existing and new integrations are rendered in the grid

**Comment by magento-engcom-team** [comment]
@MirkoHuf we updated the issue description

**Comment by magento-engcom-team** [comment]
Hello @MirkoHuf. Classically we were not able to reproduce Your issue. We took fresh instance of 2.1.9, we tried to install 2.0.0 (as we understood from Your description You had before) and upgrade it to 2.1.9 - integrations work. Maybe first You need to change the password as You are forced to by the system as we see from the appropriate message. If it doesn't help the issue could be caused by external functionality You use. Please specify which edition You use Community or Enterprise.

**Comment by MirkoHuf** [comment]
I use the Community Edition.
Changing Password doesn't help.
I had version 2.1.6 before (which I have right now because we are back to our previews snapshot)

**Comment by magento-engcom-team** [comment]
@MirkoHuf Did You made the upgrade by System -> Web Setup Wizard, or otherwise (if so, please specify how).

**Comment by MirkoHuf** [comment]
No, i choose the CLI:

su -s /bin/bash www-data
composer require magento/product-community-edition 2.1.9 --no-update
composer update
(as root) chmod a+rw -R /var/www/magento/pub/media/

rm -rf var/di var/generation 
php bin/magento cache:flush 
php bin/magento setup:upgrade 
php bin/magento setup:di:compile 
php bin/magento indexer:reindex

wrong?

**Comment by magento-engcom-team** [comment]
@MirkoHuf Couldn't there be any error message while updating, that You might have not noticed. Also when You try to do something with integrations in 2.1.9 open developer console (F12 for Chrome) and look if there is no any JS error or something like that. Anyway, please provide screenshots of it while loading those pages (Integrations, adding new integration, "Back").

**Comment by MirkoHuf** [comment]
One more - importand - information.
We have 2 systems - very similar. The only difference is, the development system runs on Apache, the productive system runs on nginx.

We have the problem on booth. 

There is no JS error or any other type of error message in the console.
![2017-09-20_20h38_07](https://user-images.githubusercontent.com/7764831/30661244-b21cb010-9e43-11e7-8d61-df5c40d962a2.png)

I also try to use the Web Setup Wizard to "reinstall the update" - results are attached.
![2017-09-20_20h41_30](https://user-images.githubusercontent.com/7764831/30661386-1dcc7994-9e44-11e7-8244-f133bc76a083.png)

![2017-09-20_20h42_23](https://user-images.githubusercontent.com/7764831/30661428-3c2430da-9e44-11e7-85f6-f59c9cbab8d1.png)

![2017-09-20_20h46_47](https://user-images.githubusercontent.com/7764831/30661605-d9f40f6a-9e44-11e7-89c3-b19af562ab34.png)

New Integration is still empty....

**Comment by MirkoHuf** [comment]
Additional information:
I go back on our test system to magento 2.1.6 via snapshot. And this time i use the Web Setup Wizard to start the upgrade from 2.1.6 to 2.1.9
Runs without error messages - but the new integration page is still empty.

**Comment by magento-engcom-team** [comment]
You sad that Changing Password doesn't help. But on the screenshot You provided on JS has no error the message about password change is still present. Are You sure we can eliminate this point from the possible reasons of issue occurrence?

**Comment by MirkoHuf** [comment]
I'm sure :-)
![2017-09-21_10h48_51](https://user-images.githubusercontent.com/7764831/30687083-875b66c4-9eba-11e7-849b-b001dcb166a8.png)

**Comment by benjamin-garnier** [comment]
Hello, I have some problems too when I upgraded from 2.1.2 to 2.1.9, I also chose CLI command

composer require magento/product-community-edition 2.1.9 --no-update
composer update
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex

The difference is that I DO have js errors sometimes on my website : 
![image](https://user-images.githubusercontent.com/26303086/30704145-0e6c5182-9ef2-11e7-9aee-b002023a47b6.png)

Is there anything in the 2.1.9 version that could result in not loading some jquery file ? It stops the page to be fully loaded due to thoses errors...

**Comment by magento-engcom-team** [comment]
Dear @MirkoHuf. We can't reproduce Your issue on fresh downloaded instance. Therefore the problem is most probably caused by some of Your third-party applications.

**Comment by magento-engcom-team** [comment]
@MirkoHuf, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by vjcspy** [comment]
Please reopen this issue. I'm have tested with magento 2 version 2.1.9, 2.2.0.

**Comment by DanielRuf** [comment]
@vjcspy are you sure that it is the exact same issue? Can you create a new issue and provide the needed steps to reproduce it?

**Comment by vjcspy** [comment]
@DanielRuf I've checked this issue. In my case, error occurs in file /vendor/magento/module-integration/Helper/Data.php at row 25. When some extension doesn't have resource title so it will throw error and magento doesn't render anything.
For anyone get this error, let changes app mode to "developer" to show exception.

**Comment by hema94** [comment]
Hi @DanielRuf Thank you for your response. I am new to magento2.1.13. Can you please say how to check which  "extension doesn't have resource title".

**Comment by DanielRuf** [comment]
> Can you create a new issue and provide the needed steps to reproduce it

We have new issue templates. Please open a new issue.
