### ISSUE TITLE
How to place order in magento 2 using REST API?

### ISSUE THREAD

**Issue by KITSup** [magento/magento2#10967]
### Preconditions

1.  I have using REST API for placing order in PHP coding. 
2. And then i have to set this to my android app.

### Steps to reproduce

1. And i have following the steps of
a.) create empty cart b.) add items c.) post billing address d.) post estimate shipping methods e.) get shipping info f.) get payment info g.) place order
2. But Shipping Address is not set in my backend and the shipping methods returning empty array [ ]. 
3. Shipping info is also returning empty array.
4. billing address is generating the ID but it is not saving in my backend but it posts my address details..

### Expected result

For Example:
1. Shipping Methods : 
[
    {
        "carrier_code": "flatrate",
        "method_code": "flatrate",
        "carrier_title": "Flat Rate",
        "method_title": "Fixed",
        "amount": 15,
        "base_amount": 15,
        "available": true,
        "error_message": "",
        "price_excl_tax": 15,
        "price_incl_tax": 15
    },
    {
        "carrier_code": "tablerate",
        "method_code": "bestway",
        "carrier_title": "Best Way",
        "method_title": "Table Rate",
        "amount": 5,
        "base_amount": 5,
        "available": true,
        "error_message": "",
        "price_excl_tax": 5,
        "price_incl_tax": 5
    }
]

### Actual result

1.
![image](https://user-images.githubusercontent.com/32120324/30630421-37fa22a8-9dfe-11e7-8f3e-458b04b33c0a.png)

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by KulwinderKohli** [comment]
Hi, I am getting the same issue. Do magento have any solution now?
