### ISSUE TITLE
support for PHP-PM ?

### ISSUE THREAD

**Issue by sinamiandashti** [magento/magento2#10964]
Hello Magento Team

As you can see there is a huge performance boost with newly php-pm package that is a good replace for regular php-fpm

does magento2 supports PHP-pm or what might happens if we use it on production

https://github.com/php-pm/php-pm

**Comment by magento-engcom-team** [comment]
@sinamiandashti please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
