### ISSUE TITLE
Consider credis library update to allow Redis Sentinel cluster usage

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#10962]
### Preconditions

1. Any version of Magento 2
2. 

This is not an issue which is causing bugs, so I will not describe scenario about how to reproduce it.

The fact is : I have a redis cluster running with redis-sentinel. I plan to use it as a cache and session storage. This is supported by the credis library and I want to test it. But actually, the version included in Magento's package is **1.6** version which is having errors. See my thread on stackexchange to have an example of error : https://magento.stackexchange.com/questions/193813/magento2-redis-sentinel-configuration/193816#193816

Is it possible to consider changing the dependency of magento/product-community-edition package to "^1.6" instead of the rigid "1.6" which is actually present ?

Best regards,

**Comment by orlangur** [comment]
There is no need to stay on `1.6` due to a known bug revealed recently, it will be upgraded in https://github.com/magento/magento2/issues/10524.
