### ISSUE TITLE
Problem creating new Store-View for Website with large Catalog >100K

### ISSUE THREAD

**Issue by samc2810** [magento/magento2#10973]
While creating a new Store for websites with a medium large number of products the webserver reaches the timeout after 5min. Although the new store is created the url-rewrites and most importantly the sales_sequence_meta/profile and the equence-tables are not created due to which one cannot place any order. is there anything that can be done. or how shouuld I continue with this?

Magento 2.1.7

**Comment by magento-engcom-team** [comment]
@samc2810 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
- [ ] Preconditions: Magento version
- [ ] Steps to reproduce
- [ ] Expected result
- [ ] Actual result

**Comment by Jeroenll** [comment]
Duplicate of #10315 although I missed the additional table creations. You have some files/references where this happens so I can take a look?

**Comment by samc2810** [comment]
@magento-engcom-team 
the same pre-requisites as #10315

**Comment by orlangur** [comment]
@JeroenVanLeusden @samc2810 yeah, thanks for pointing out, closing as duplicate.
