### ISSUE TITLE
Generate specific php  sources via commandline

### ISSUE THREAD

**Issue by QwertyZW** [magento/magento2#10971]
Add a cli sub command that generates specific factory/proxy/interceptor sources

An ide can go blank when it sees something like `use Magento\Sales\Api\OrderInterfaceFactory` and the generated file doesn't exist. It won't be able to infer the type created by the factory and it won't provide method autocompletion/suggestions 

One can write ide plguins that can the generation of said files when their resolution fails by invoking an external magento2 command that generates said file.

**Comment by orlangur** [comment]
This is not possible reliably, see https://magento.stackexchange.com/a/98916/40869 for details.

You can join https://github.com/enriquepiatti/Magicento/issues/219 discussion to figure out a possible implementation approach.

As to me the most promising way would be to expose developer/default mode on-demand PHP classes generation somehow (similar to the way `pub/static.php` is generating particular requested static files).
