### ISSUE TITLE
 Google PageSpeed Insights JS/CSS Blocking

### ISSUE THREAD

**Issue by dgitman** [magento/magento2#1098]
I'm not sure if this is the best place to bring up my concern. Google PageSpeed Insights is reporting the same JS/CSS blocking issues that represent in Magento 1. I'm hoping this can be addressed in Magento 2.

**Comment by villageseo** [comment]
Hi dgitman! 

Could you please clarify the question ? What specific JS/CSS blocking issues?  

Thank you,
Oleg

**Comment by godban** [comment]
Hi @dgitman 

Thank you for report. We already resolved this issue, prioritized styles and scripts order.
Styles will be processed ahead scripts.

**Comment by vpelipenko** [comment]
@dgitman, do you have any other concerns? can we close this issue?

**Comment by dgitman** [comment]
Feel free to close this issue. Thank you!
