### ISSUE TITLE
whentry to deleting block one or multipal that time i got this error

### ISSUE THREAD

**Issue by rab14191** [magento/magento2#10981]
Fatal error: Call to undefined method Magento\Cms\Model\ResourceModel\Block\Grid\Collection::_getAllIdsSelect() in C:\xampp\htdocs\rabworld\219\vendor\magento\module-cms\Model\ResourceModel\Block\Grid\Collection.php on line 97

magneto version:2.1.9
sql:Version information: 4.5.1, latest stable version: 4.7.4

**Comment by orlangur** [comment]
@rab14191 thanks for bug report!

Closing as duplicate of https://github.com/magento/magento2/issues/8415, the fix for this issue is already available on Magento 2.2.0 branch.
