### ISSUE TITLE
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10983]
Composer shows the message 'Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.' after running `composer install`.

### Preconditions
n/a

### Steps to reproduce
Run `composer install` after cloning the repo.

### Expected result
No warning.

### Actual result
Abandoned package warning.

### Fix
Replace the `package fabpot/php-cs-fixer` with `friendsofphp/php-cs-fixer`

**Comment by orlangur** [comment]
@schadom thanks for your report! Closing as duplicate of https://github.com/magento/magento2/issues/7310.
