### ISSUE TITLE
Not relevant logic in \Magento\Ui\Component\MassAction\Filter

### ISSUE THREAD

**Issue by naydav** [magento/magento2#10988]
### Preconditions
- Magento ver. 2.3.0-dev

### Steps to reproduce

*\Magento\Ui\Component\MassAction\Filter::getCollection*
The main goal of this class is obtaining entity ids from request for mass actions

### Expected result

- Contract without dependency on AbstractDb $collection
- Logic based on extra query is removed

### Actual result

- Parameter is AbstractDb $collection. But it is a redundant dependency. We need to provide ids, and for this action collection is not required.
Also, it is violation of SPR, LSP principles, and CQS
- In this way we have a double loading of the same date (entities ids). After performing
{code}$idsArray = $this->getFilterIds();{code} we already have entity ids (obtained from data provider). But we apply a new filter to a collection based on these ids. So we need to do one more query which is reloading existing data.

**Comment by naydav** [comment]
Internal ticked MAGETWO-75648

**Comment by magento-engcom-team** [comment]
@naydav, thank you for your report.
We've created internal ticket(s) MAGETWO-75648 to track progress on the issue.

**Comment by okorshenko** [comment]
Fixed in msi project
