### ISSUE TITLE
Magento 2 order creation from non-default store in admin fails

### ISSUE THREAD

**Issue by zack6849** [magento/magento2#10990]
### Preconditions

1. Magento 2.1.9
2. Multistore Environment

### Steps to reproduce

1.  View customer account
2. Create order for non-default store view

### Expected result

1.  Order is created

### Actual result

Order process starts, hits our payment processor, then comes back and says it can't find our cart.
![2017-09-21-143623_1917x928_scrot](https://user-images.githubusercontent.com/1343898/30712536-59917d30-9eda-11e7-9b21-0d8e777eeba9.png)

**Comment by YevSent** [comment]
Hi, @zack6849, I've tried to reproduce the described issue with different variations (another store view for the same or different store) the orders were placed successfully. Please, provide more details, like `exception.log` details.

**Comment by magento-engcom-team** [comment]
@zack6849, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
