### ISSUE TITLE
Change the setting `Add Store Code to Urls` from global setting to Store Name setting (1 lower in hierarchy)

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1099]
Change the setting `Add Store Code to Urls` from global setting to Store Name setting

Currrently the setting `Add Store Code to Urls` is a global setting. This should be changed to one level down: Store Name level. 

One should be able to run 2 brands like this

**Brand A**
`Add Store Code to Urls` = YES
nl site = brandA.com/nl
en site = brandA.com/en

**Brand B**
`Add Store Code to Urls` = NO
And different Base URL's
nl site = brandB.nl
en site = brandB.co.uk

Curerntly when `Add Store Code to Urls` = YES the /en, /de, /fr, /nl are added to all stores in a multistore setting. In this example brand A follows this model, but Brand B does not and has unique domains

Please change `Add Store Code to Urls` to Store Name level (instead of global setting). 

Some more explanation here: http://magento.stackexchange.com/questions/60686/multi-multistore-multiple-brands-multiple-languages-setting-store-view-code

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Change-the-setting-Add-Store-Code-to-Urls-from-global-setting-to/idi-p/45480).

**Comment by seansan** [comment]
this could be marked as a bug and thus fixed in github

**Comment by nikesh12** [comment]
Can I do it with website level.
