### ISSUE TITLE
Back in stock alert email not translatable

### ISSUE THREAD

**Issue by mike-happy** [magento/magento2#10997]
### Preconditions
1. Magento CE 2.1.9
2. Products are set up.
3. Stock is set up.
4. Magento2translations (nl_NL) language package is installed and enabled.

### Steps to reproduce
1. Set the stock of a product on 0 and out of stock in the admin.
2. Create a customer login in the frontend
3. Navigate to the product that is out of stock
4. Click on the link "Notify me when this product is in stock". ("Informeer mij wanneer dit product op voorraad is" in dutch)

### Expected result
1. Receive the email in Dutch, because the language package contains the right translations.

### Actual result
1. Receive the email in English.
<img width="576" alt="screen shot 2017-09-15 at 09 04 21" src="https://user-images.githubusercontent.com/13847902/30737104-a45e830c-9f85-11e7-8f49-dd7e389a4488.png">

The email is send through the cron, so it is only send at night. (Which makes debugging extra difficult)

The actual text is in magento/module-product-alert/view/frontend/templates/email/price.phtml

**Comment by Jeroenll** [comment]
Think cron translations are not loaded here, please check the fix in #8413. When having issues displaying the correct image in your email you can also check the fix in #10208.
