### ISSUE TITLE
Improve the Mage:app command and add variable for Store Name (the store, not only the store view)

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1100]
Improve the Mage:app command and add variable for Store Name (the store, not only the store view)

Currently Magento is started as follows `Mage::run($mageRunCode, $mageRunType);` where `$mageRunCode` is set by htaccess/nginx or in php. `$mageRunType` is almost always 'store' or empty. 

Maybe this code can be updated to something like this
`Mage::run($mageStoreName, $mageStoreView, $mageRunType);`

- $mageStoreName = Store Name
- $mageStoreView = Store View

**Situation**
Suppose we have two stores both Brand A and Brand B. The both have 1 domain and use `Add Store Code to Urls` to distinguish languages. Brand A is set-up as follows:
- brandA.com/nl
- brandA.com/en
- brandA.com/de

These stores are opened via the command `Mage::run` where `$mageRunCode` is NL, EN or DE respectively. 

The problem arises when one wants to open a second store Brand B and also follow the above multistore model. 
- brandB.com/nl
- brandB.com/en
- brandB.com/de

**Problem**
The problem is that this can not be done. The `$mageRunCode` NL, EN and DE are taken so Brand B would have to resort to something like /b_nl, /b_en and /b_de .... this is not ideal

There are a couple of solutions to allow for more than 1 brand like above when having `Add Store Code to Urls` set to YES
1. Add a `$mageStoreName` variable to start a Store Name first, then look for the Store View
2. Add a *new* parameter on Storeview level that is used for the setting `Add Store Code to Urls` (so it becomes something like `Add Language Code to Urls` or `Add Store Code Identifier to Urls`. This way the Store Code still needs to be unique. But the functionality that adds the `Store COde to URL's` does not use the StoreCode but somthing else .... like the Language Code .... or a new parameter as `Store Code Identifier` 

I hope this is clear. Should be a great win for flexibility and multistore environments

Some more information can be found here: http://magento.stackexchange.com/questions/60686/multi-multistore-multiple-brands-multiple-languages-setting-store-view-code

**Comment by maksek** [comment]
Hi @seansan, it is Magento 2 Github, and all issues must be related to Magento 2. Your issue content is about Magento 1. Please use proper resources for Magento 1.
