### ISSUE TITLE
Magento_Tax module has double discount_tax node in config.xml

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#11000]
The `config.xml` of the `Magento_Tax` module has a double node of `discount_tax`. This disallows other modules to override this configuration setting using their own `config.xml`.

### Preconditions

1. Magento 2.1.9 (and other versions probably as well)

### Steps to reproduce

Create a new module and add a `config.xml` with the following:

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <tax>
            <calculation>
                <discount_tax>1</discount_tax>
            </calculation>
        </tax>
    </default>
</config>

```

### Expected result

The configuration setting "Apply Customer Tax" in the admin should be set properly to "After Discount".

### Actual result

The following error is thrown:

    Magento\Framework\Exception\LocalizedException: 
    More than one node matching the query: /config/default/tax/calculation/discount_tax

I'll send a PR for this one

**Comment by orlangur** [comment]
Thanks for bug report! Yeah, all versions affected: https://github.com/magento/magento2/blob/develop/app/code/Magento/Tax/etc/config.xml#L19

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-75865
