### ISSUE TITLE
Admin OAuth Tokens never expire

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#11008]
### Preconditions

1. Magento 2.1 with cron running

### Steps to reproduce

1. Create an admin auth token
2. Keep using it.
3. Keeeeeep using it.

### Expected result

1. It will expire

### Actual result

1. Nope. Never expires.

This page (http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-token.html#admin-and-customer-access-tokens) specifies that there is an option in Configuration > Services > OAuth > Access Token Expiration for admin session expiration, but there is no such option. And there is no cron job to check.

Did this feature get finished?

**Comment by magento-engcom-team** [comment]
@maderlock, thank you for your report.
We checked it on 2.1.9. Looks like you missed something.
- The configuration, that specifies admin session expiration is located in: Stores -> Configuration -> Services -> OAuth -> Access Token Expiration -> Admin Token Lifetime (hours).
- Cron job is a class: Magento\Integration\Cron\CleanExpiredTokens::execute() which is configured in app/code/Magento/Integration/etc/crontab.xml.

**Comment by maderlock** [comment]
Embarrassing. I was accidentally looking at 2.1.7. Apologies for wasting your time.

**Comment by magento-engcom-team** [comment]
@maderlock, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by sangeetajain** [comment]
How to set Rest API oAuth token expire in minutes or seconds in admin. Currently it's showing hours and it will not accept like 0.5(for 30 minute etc) magento2. Any One know about this, please help me asap.
![hvUMl](https://user-images.githubusercontent.com/4272871/65574050-faa2d600-df89-11e9-8e88-5e8d4b7fcc2e.png)
