### ISSUE TITLE
Set-Cookie response header on static assets, during generation, when Magento is behind Varnish (non port 80)

### ISSUE THREAD

**Issue by antoinekociuba** [magento/magento2#11007]
When Magento, in developer mode, generates static assets on the fly, and when used port is not 80/443 (8080 with Varnish for example), we can see that a Set-Cookie PHPSESSID is returned, and so, session is lost... After the file is generated on pub/static directory, no more issue, and no more Set-Cookie response header.

When switching back to 80 port, after clearing static directory, I can't see this problematic header anymore neither, during file generation and after.

In order to bypass the issue, I can obviously run static:deploy command, but still, behavior with 8080 port should be same as 80 port, and static assets should never return any Set-Cookie response headers, and especially not a PHPSESSID cookie.

Nginx configuration is the one provided by default.
Same for the VCL, which was exported from the back office, without any modification.

### Preconditions
1. Magento Open Source (CE) 2.1.6 without sample data
2. PHP 7.0.17
3. Nginx 1.10.3
4. MySQL 5.7.17
5. Varnish 4.1.1
6. Ubuntu 16.04

### Steps to reproduce
1. Fresh Magento installation
2. Install Varnish exactly as described on the documentation
3. After Varnish is up and running, clear pub/static directory
4. Refresh any page, and check response header of any assets

### Expected result
1. No Set-Cookie PHPSESSID response header on assets

### Actual result
1. Presence of Set-Cookie PHPSESSID response header on assets

**Comment by magento-engcom-team** [comment]
@antoinekociuba, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
