### ISSUE TITLE
Magento 2 - Trying to install an amazon payment module and In web setup widzard I got this exception

### ISSUE THREAD

**Issue by rahulthakral38** [magento/magento2#11011]
I am trying to install amazon payment magento 2 extension and getting this issue while installation in web setup widzard. Can any one suggestion anything. Any help is appreciated.

Here is the error that I am facing.

Check Component Dependency We found conflicting component dependencies.

Command "update" failed: Loading composer repositories with package information Updating dependencies (including require-dev) Your requirements could not be resolved to an installable set of packages.

Problem 1 - The requested package amzn/amazon-pay-and-login-magento-2-module could not be found in any version, there may be a typo in the package name.

A typo in the package name -

The package is not available in a stable-enough version according to your minimum-stability setting see 
[Click here to view full error](
![component](https://user-images.githubusercontent.com/17290393/30770658-b1b4876c-a053-11e7-9d3b-f90c3769fd10.png)
![pasted file at september 22 2017 8-44 pm](https://user-images.githubusercontent.com/17290393/30770666-ccf2c610-a053-11e7-9b1a-4b827e2d9295.png)

https://i.stack.imgur.com/hLH6c.png)

**Comment by orlangur** [comment]
According to https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html#manual-composer-install-method the command should be
```
composer require amzn/amazon-payments-magento-2-plugin:^1.1.4
```

It worked for me.

Not sure why package is named `amzn/amazon-pay-and-login-magento-2-module` when you install via Web Wizard, extension developer should be contacted in such case according to my understanding.
