### ISSUE TITLE
Unable to save product changes on products that were imported

### ISSUE THREAD

**Issue by McDev814** [magento/magento2#11010]
#
We imported 2000 simple products to our website, though when we make changes to those products we get varying results of success. Some changes can be made and successfully applied, such as adding an attribute set and attribute values.  However, when that is done we lose the product image. If the product was imported as disabled, we are unable to enable it through the product page. When we change the title of the product and save it, the title of the product page will be correct but remains as the old title in the product grid and on the frontend. I know all of these issues could have their own issue reported, however they only occur on products that were added to the store through a csv import.

### Preconditions

1. Magento 2.1.9, single store mode, developer mode
2. PHP 7.0.22
3. MySQL 5.7
4. Apache 2.4
5. Ubuntu 16.04

### Steps to reproduce

1. Import products through a csv succesfully (products shown correctly everywhere w/in environment)
2. Make a change to the product (add an attribute set and attribute values; change the title; enable a disabled product)
3. Save the product and see a resulting message that the product has been successfully saved.

### Expected result

1. See the changes reflected correctly in the product grid, on the product page, and on the store frontend

### Actual result

1. Product title correct on product page, but not grid or frontend if the title was changed.
2. Product continues to be disabled, if trying to change from disabled to enabled
3. Product image lost if attribute set and attribute values added
4. system.log after product saved with any of the above changes

```PHP
[2017-09-22 20:30:48] main.INFO: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-09-22 20:30:48] main.INFO: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2017-09-22 20:30:48] main.INFO: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
```

**Comment by magento-engcom-team** [comment]
@McDev814, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
