### ISSUE TITLE
Magento 2 After  Upgrade from version 2.1.8  to 2.1.9 Theme Configurations are Missing

### ISSUE THREAD

**Issue by vishalpatel14** [magento/magento2#11012]
Dear Team,

After upgrade of Magneto From Version 2.1.8 to 2.1.9 Theme Selection Menu in Admin Section is missing.

### Preconditions
1. windows 7
2. Wamp Server 3.0.6
3. Php 5.6.25
4. Mysql 5.7.14
5. Apache 2.4.23

### Steps to reproduce
1. Windows command prompt upgrade Magneto from 2.1.8 to 2.1.9. After completion of successfully update. Theme Configurations are missing

### Expected result
Theme Package and Theme name should be available in admin configuration.

### Actual result

1.Theme Configurations are missing in admin panel have a look to attached below screenshot.
2.  
![report](https://user-images.githubusercontent.com/16519746/30772690-8631519e-a07e-11e7-9927-5f705f34aae8.jpg)

**Comment by orlangur** [comment]
Hi @vishalpatel14, this was changed much earlier than 2.1.8 actually, so, couldn't be caused by such upgrade.

See https://github.com/magento/magento2/issues/10269#issuecomment-316086522 to find out where such configuration is currently placed.

**Comment by vishalpatel14** [comment]
ok thanks got your point. Location changed.
