### ISSUE TITLE
Add setting to remove both URL parameters `__from_store` and `__store` in URI's from config setting in backend in multistore environment

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1101]
Add setting to remove both URL parameters `__from_store` and `__store` in URI's from config setting in backend in multistore environment. These parameters should be optional for a store owner to set. 

New config setting, `add __from_store  when switching stores` = YES/NO

New config setting, `add __store  when switching stores` = YES/NO

http://magento.stackexchange.com/questions/58376/multistore-removing-store-when-stores-on-different-domain

**Comment by maksek** [comment]
Hi @seansan, it is Magento 2 Github, and all issues must be related to Magento 2. Your issue content is about Magento 1. Please use proper resources for Magento 1.
