### ISSUE TITLE
SetCountryID() not displaying for customer or admin.

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#11018]
### Preconditions
1. Magento 2.1.7
2. PHP 7

### Steps to reproduce
1. Create an address by code
code : 

```
use Magento\Customer\Api\AddressRepositoryInterface;
use Magento\Customer\Api\Data\AddressInterface;
....
$this->_addressRepository = $addressRepository;
$this->_addresinterface = $addresinterface;
....
$address = $this->_addressRepository;
$addressarray = $this->_addresinterface;
$addressarray
                                    ->setCustomAttribute('exact_address_id', $contactaddress['ID'])
                                    ->setCustomerId($customerrep->getId())
                                    ->setFirstname($contact['firstname'])
                                    ->setLastname($contact['lastname'])
                                    ->setCountryId($contactaddress['Country'])
                                    ->setRegionId(0)
                                    ->setPostcode($contactaddress['Postcode'])
                                    ->setCity($contactaddress['City'])
                                    ->setTelephone($contact['account']['Phone'])
                                    ->setFax($contact['account']['Fax'])
                                    ->setCompany($contactaddress['AccountName'])
                                    ->setStreet(array($contactaddressstreet))
                                    ->setVatId($contact['account']['VATNumber']);

if ($contact['account']['AddressLine1'] == $contactaddress['AddressLine1']) {
                                    $addressarray->setIsDefaultBilling(true);
                                    $addressarray->setIsDefaultShipping(true);
                                } else {
                                    $addressarray->setIsDefaultBilling(false);
                                    $addressarray->setIsDefaultShipping(false);
                                }
                                try {
                                    $address->save($addressarray);
                                } catch (\Exception $e) {
                                    Zend_Debug::dump('Customer id : ' . $contact['ID'] . ' : Address : ' . $contactaddress['AddressLine1'] . ' : ' . $e->getMessage());
                                }
```

2. execute and check in the customer account and database if the addresses are created and if they have a value for CountryID in the `customer_address_entity` table

### Expected result
1.  Database has a Country ID set in the address table (for belgium 'BE')
2. Adminhtml and frontend uses the 'BE' to display 'Belgium' in the 'country' field at the customer account.

### Actual result
1. Database does have a County ID set in the `customer_address_entity` table under `country_id`
![image](https://user-images.githubusercontent.com/18028151/30784650-64754f66-a159-11e7-82c9-94be610e2241.png)

2. Customer address **does not** have the value selected in the backend or frontend 
![image](https://user-images.githubusercontent.com/18028151/30784660-7b505578-a159-11e7-9a2c-cffb82d65fa1.png)

**Note**

I'm pretty new to creating customers and addresses from API's within Magento 2 so if i'm doing something wrong my apologies. But i don't think that even if there was another way to add addresses that this one should have this as a result. Everything is working fine expect for this.

Stackexchange link : [https://magento.stackexchange.com/questions/194227/setcountry-does-not-reflect-in-backend/](url)

**Comment by magento-engcom-team** [comment]
Unfortunately, I could not reproduce the issue as you described it.
Maybe I don't have all code context, but You should save address as that do in \Magento\Customer\Controller\Address\FormPost::execute

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by versdivers** [comment]
Well i want to reopen this issue because. I don't get it.. You ask people to provide code and all the information needed to reproduce , you reproduce it and you have a different result. So obviously you did something else. 
But you do not provide any information on what you did so i can see if you did something different.

1+1 always equals 2.  No matter who does it. And the same is in coding. I need to know what you did differently.

Can you explain what you did , what value you gave within that field and what is showing in your backend. Did you try with the value 'BE'?  Which classes you used to save it and how you saved it.

Update: I missed the You should save address as that do in \Magento\Customer\Controller\Address\FormPost::execute

I will try to save it differently then. I will update if it works or not.

**Comment by versdivers** [comment]
A hidden space was within the import. My bad. This can be kept closed
