### ISSUE TITLE
magento2.1.9 can't add product 

### ISSUE THREAD

**Issue by zhudanlin** [magento/magento2#11013]
### Preconditions

1. Magento2.1.9
2. PHP-5.6 +Apache-2.4+mysql-5.6;my website:www.amavaporizer.com

### Steps to reproduce

1. Method 'getExtensionAttributes' must be overridden in the interfaces which extend 'Magento\Framework\Api\ExtensibleDataInterface'. Concrete return type must be specified. Please fix :\Magento\Catalog\Api\Data\ProductInterface
2. 
3. 

### Expected result

1. when i add product in the background,it said need fix "ProductInterface",and Can not register  new users, can not send me an email to me at the front desk

### Actual result

1. [Screenshot, logs]
![new](https://user-images.githubusercontent.com/32222687/30774097-034a20a8-a0b0-11e7-9a0e-5f514daf07f0.JPG)
![new2](https://user-images.githubusercontent.com/32222687/30774098-037616d6-a0b0-11e7-96e4-a4faeb74ed43.JPG)
![new3](https://user-images.githubusercontent.com/32222687/30774099-038380dc-a0b0-11e7-8158-a115ba3eb0bc.JPG)

**Comment by zhudanlin** [comment]
this problem was solved,it is linux environment build problem,Now i choose bitnami's lamp and magento,it is working good.

**Comment by zhudanlin** [comment]
hope Magento can open more message of linux environment build

**Comment by magento-engcom-team** [comment]
@zhudanlin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
