### ISSUE TITLE
Configurable product displays price zero (£0.00) - Disabled in stock simple

### ISSUE THREAD

**Issue by gwilliams01** [magento/magento2#11023]
### Preconditions
1. Clean installation of Magento CE 2.1.7

### Steps to reproduce
1. Create configurable product and associate two simple products
2. Configure first simple product - Enabled, qty 0, Out of Stock
3. Configure second simple product - Enabled, qty 1, In Stock
4. Check product displays correctly on frontend - i.e. In Stock
5. Configure system to not display Out of Stock products (config > catalog > inventory > stock options)
6. Disable second simple product (important step)

### Expected result
1. Configurable product should not display on frontend

### Actual result
1. Configurable product displays on frontend with price zero (£0.00), Out of Stock

![bug - config product zero price_1](https://user-images.githubusercontent.com/32200725/30802835-0908cdc6-a1e8-11e7-8476-b2628691221c.JPG)

I checked behaviour on Magento 1 (1.9.1.1) and this performs as expected (i.e. configurable product does not display).

**Comment by orlangur** [comment]
Did you assure that stock reindexing occurred?

**Comment by gwilliams01** [comment]
Yes, reindex was done.

**Comment by RomanKrut** [comment]
I can confirm the issue.

**Comment by joshdavenport** [comment]
Yup, currently pulling my hair out because of this one. Just deployed 2.1.8 this morning and this appeared! Seeing it in EE also but same version. I think it's possible this issue also happens when all of the associated simples are out of stock as well as when they're disabled.

**Comment by magento-engcom-team** [comment]
@gwilliams01, thank you for your report.
The issue is already fixed in 2.2.0

**Comment by magento-engcom-team** [comment]
Looks like the following commits were made to fix the issue: https://github.com/magento/magento2/commit/2a669078f54419a4756a4b86a037f5118cbfd16b https://github.com/magento/magento2/commit/1d0959d6d6afc423e32e40e832ef719bc657a517

**Comment by davoc** [comment]
This issue is affecting me on v2.2.0

**Comment by xarls** [comment]
I have the same problem in  Magento ver. 2.3.4

**Comment by Javiercc78** [comment]
I have been with the same error for a long time, very ugly on the frontend.

The configurable product displays a price of 0 until an option is not selected. After that the product shows its price normally
Magento ver. 2.3.4.
