### ISSUE TITLE
Add ability for bulk update product reviews to second store

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1102]
When one build up product reviews and a second store is opened. Then the product reviews are not enabled (selected from scope list) in the second store.  This can be done manually, review per review.

There should be a method to mass update product reviews to enable them in other store views.

Some more information here
http://magento.stackexchange.com/questions/55716/sql-to-make-product-reviews-available-in-other-store

**Comment by waynetheisinger** [comment]
:+1: we needed this just the other day

**Comment by tkacheva** [comment]
@seansan Good point! 
Added to the roadmap - MAGETWO-34738

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-ability-for-bulk-update-product-reviews-to-second-store/idi-p/47288).
