### ISSUE TITLE
Updating any date field in admin results in 'Invalid input datetime format'

### ISSUE THREAD

**Issue by stevenlavine** [magento/magento2#11027]
### Preconditions

1. Existing install of Magento 2.17 updated to 2.1.9
2. PHP 7.1.x
3. MySQL 5.7

### Steps to reproduce

1. Go to Products > Catalog
2. Edit a product
3. Set the new from and to dates

### Expected result

1. Product updates with the new values

### Actual result

1. Error Returned: Invalid input datetime format of value '25/09/2017'
![image](https://user-images.githubusercontent.com/910649/30811930-70bf2b36-a201-11e7-9402-8ae1b70a4afe.png)
![image](https://user-images.githubusercontent.com/910649/30811968-925390e8-a201-11e7-9d33-d7debab2782d.png)

The site is configured for UK locale and is a multi-site installation - another website, using the same version of Magneto using the default US configuration does not encounter this issue.

**Comment by orlangur** [comment]
@stevenlavine, thanks for bug report! This is already tracked as https://github.com/magento/magento2/issues/10580.
