### ISSUE TITLE
Magento 2 After Upgrade from version 2.1.8 to 2.1.9 cannot edit theme configurations

### ISSUE THREAD

**Issue by lhsatch** [magento/magento2#11021]
### Preconditions

1. Upgraded from magento 2.1.8 to 2.1.9, php 5.6
2. 

### Steps to reproduce

1. Log into the admin area
2. Goto Content ->Design->Configuration
3. Then select edit on the theme.

### Expected result

1. Theme Edit page appears

### Actual result

1. White screen appears, nothing is logged and no error message appears.

**Comment by orlangur** [comment]
Try turning on developer mode and uncommenting `ini_set('display_errors', 1);` in `app/bootstrap.php` to see an actual error instead of white screen.

**Comment by lhsatch** [comment]
I normally see all errors on the frontend with the settings you have suggested but it seems strange that there is nothing showing for this instance

**Comment by lhsatch** [comment]
I think it might be to do with the CheckThemeIsAssignedObserver in the magento theme observer. The function is returning false for isThemeAssignedToStore.

**Comment by magento-engcom-team** [comment]
Unfortunately, I could not reproduce the issue as you described it.
Remove all static content and clear your browser cache maybe help for You .

**Comment by lhsatch** [comment]
Could you try setting the theme at store view level.

**Comment by magento-engcom-team** [comment]
@lhsatch, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by lhsatch** [comment]
I have looked in the ChangeLog and there was an issue that was apparantly fixed:
    * Fixed an issue where a new custom theme added to the file system, was not accessible in Admin      [position 274:41]	
This is the issue i am having now. Also this page is the only one that seems to have the filters and pagination at the bottom of the page.
![design_config](https://user-images.githubusercontent.com/6516012/30962106-6540d5b6-a440-11e7-9443-8caf47338a49.jpg)
