### ISSUE TITLE
Checkout shipping method is preselected if only one rate available

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#11035]
reporting this again, already did in #10639 but got closed, this is a real bug in 2.1.* series

When you reach checkout and you have more than one rate available in shipping options and choose a rate that suits you , then change shipping country (or whatever affects rate availability)  that limits the rates to one option available (disabling the one chosen before) you end up with preselected rate that was not chosen by customer as a silent option .

### Preconditions

1. M 2.1.* (not tested in 2.2 but probably there as well) 

### Steps to reproduce

1. reach checkout (I'm using sample data configuration) 
2. default state is US providing two rate options (table rate and fixed) 
3. choose Table Rate 
4. change country to Uruguay (or any other country)  
5. rates are reloaded, fixed option is preselected , this was not customer choice
6. customer can place a order with options not agreed in clear manner

### Expected result

1. if rates are reloaded and customer manually made option is not available no rates should be selected to indicate the need of making this decision again. Merchant (or a bug in software) cant make that decision for the customer (monetary decision, customer preference etc) if the shipping option they use is not free

### Actual result

1. what happens is that if only one rate is available template has hardcorded option to select that option. 

`<input class="radio" type="radio" data-bind="attr: {
                                                    checked: $parent.rates().length == 1, .....>`

where 

`$parent.rates().length == 1` binding decides on frontend (without knowing if this option is ever selected or available in backend on order placement time) template that something should be selected if only one option is available

2. here's a screen recording http://quick.as/gVYZunk7a

**Comment by magento-engcom-team** [comment]
@speedupmate, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
