### ISSUE TITLE
Magento 2.1.8 - Mailchimp installation failed

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#11036]
### Preconditions

1. Magento CE 2.1.8
2. PHP version: 7.0
3. MailChimp for Magento mc-magento2-1.0.24
4. Locale AU

### Steps to reproduce

1. Download "MailChimp For Magento2" in ebizmarts
2. Install "MailChimp for Magento2" with Semi-manual installation
3. extract the contents in app/code/Ebizmarts/MailChimp
4. run - composer -vvv require ebizmarts/mailchimp-lib

### Expected result

1. Install MailChimp for Magento2 without any error

### Actual result

1. Installation failed error
screenshot
https://prnt.sc/gpojx8

**Comment by magento-engcom-team** [comment]
Hi @gilbertsohal 
This issue does not seem to be related to Magento but to the Mailchimp extension. Please report issues with third-party extensions directly to their vendors.

Thank you
