### ISSUE TITLE
CatalogSearch by Price doesn't shows products with upper price.

### ISSUE THREAD

**Issue by ed007m** [magento/magento2#11031]
### Preconditions

1. Magento CE 2.1.9 with sample data is installed.

### Steps to reproduce

1. Navigate to any category with products and set price filter(As example Woman->tops->Jackets).
2. Set price filter from $70 to $79.99.
3. Then filter results and change upper price for 77 in URL.

### Expected result

1. Products with price $77 should be visible.

### Actual result

1. 
![screenshot at sep 25 19-16-01](https://user-images.githubusercontent.com/6236299/30819331-0fcdb7f4-a227-11e7-86a0-7e553ca17016.png)

If change upper price for 77.01 all expected products are visible.
2.
![screenshot at sep 25 19-24-39](https://user-images.githubusercontent.com/6236299/30819442-5a38e002-a227-11e7-8186-646ed10adaed.png)

Why  in Magento\CatalogSearch\Model\Layer\Filter\Price:18 this CONST is present?
Magento subtracks this const from **toPrice**.
And here Magento\CatalogSearch\Model\Layer\Filter\Price:185 it happens again.

**Comment by magento-engcom-team** [comment]
Hi @ed007m 
Thank you for reporting this issue.

As of current Layered Navigation design – it is not intended to change filter prices in url, as only predefined values are supported. It is planned to improve this in future, however we can not provide any estimates yet.

**Comment by ed007m** [comment]
Point of this issue is not feature functionality but that current functionality not works as aspected. 
For example if I will create product with price $79.99 and than choose price filter $70 to $79.99
this product will not be visible. And my question is what means this logic here in 
```
Magento\CatalogSearch\Model\Layer\Filter\Price:18
Magento subtracks this const from toPrice.
And here Magento\CatalogSearch\Model\Layer\Filter\Price:185 it happens again.
```
I'm trying to create a pull request but needs some clarification from you.

**Comment by magento-engcom-team** [comment]
@ed007m, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by orlangur** [comment]
@ed007m there is nothing to fix here, functionality works as expected in fact.

With 70-80 in URL actual interval is 70.00 - 79.99 so that next interval may start from a whole number 80.

When you specify 70-77 the interval is 70.00 - 76.99.
