### ISSUE TITLE
Request for categories in Magento 2; pre-set category (layered) filter

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1103]
It should ne able to pre-select a layered navigation filter for a category: meaning, that when opening the category page, then a layered navigation filter is already applied

Suppose you sell shoes (configurable product)
and you have a category stating to show all shoes in size 10
you would then create a normal shoe category (select all shoe products)
then selected the (new setting) for a layered navigation pre-select filter for size 10
this way only shoes available in size 10 are shown

http://magento.stackexchange.com/questions/55191/magento-set-selected-filter-in-layered-navigation

**Comment by choukalos** [comment]
We've already got an internal epic for this item - https://jira.corp.x.com/browse/MAGETWO-27173 .

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Request-for-categories-in-Magento-2-pre-set-category-layered/idi-p/47285).
