### ISSUE TITLE
Images under a configurable product stop changing after updating the configurable product.

### ISSUE THREAD

**Issue by rmevans1** [magento/magento2#11033]
### Preconditions
1.  Magento 2.0.16
2.  Clean install

### Steps to reproduce
1. Create a visual swatch with images
2. Create a configurable product with that swatch.
3. Update configurable product

### Expected result
1. Images should continue to change after saving configurable product a second time.

### Actual result

1. Images stop changing.
2. The only way I have been able to solve this is to delete all the simple products under that product and start the simple products over

**Comment by rmevans1** [comment]
After further investigation it appears that when I click a swatch the gallery for the configurable product is being returned instead of the gallery for the product I want

**Comment by magento-engcom-team** [comment]
@rmevans1, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by rmevans1** [comment]
That's great that it is fine on 2.1.9. However, I am not using 2.1.9 I am using 2.0.16
