### ISSUE TITLE
Varnish Cache Issue

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#11039]
### Preconditions
1.  Magento 2.1.8 CE installed 
2.  Varnish 4 Installed and configured in Magento2 Admin
3.  Set Varnish Cache under Admin -> Stores -> Configuration -> Advanced ->System -> Full Page Cache 

### Steps to reproduce

1.  I have placed an order from the frontend.
2.  Order not showing under Admin -> Sales-> Orders.
3.  But in frontend order will be displayed in "My Account".
4. All the admin configurations not stored in first time save. It will be saved only after twice submitting to the configurations.

### Expected result

1.  Order should be displayed in Admin -> Sales -> Orders.

### Actual result

1. Order not showing under Admin -> Sales-> Orders.

**Comment by magento-engcom-team** [comment]
Hi @sasilinux
Did you apply varnish configuration (VCL) provided in Magento admin panel?

**Comment by sasilinux** [comment]
Yes. That's why the site is loading below 1 sec.

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by sasilinux** [comment]
Hi,

I have checked it even it magento 2.1.9. But still i am facing the issue.

Cache refresh also needs to be submitted two (or) three times.
