### ISSUE TITLE
catalog/seo_sitemap/category/ showing disabled categories

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1104]
Please check controller/route `catalog/seo_sitemap/category` in Magento 1.9.1 it is showing disabled categories. They should not be shown when disabled in store view

http://magento.stackexchange.com/questions/48931/catalog-seo-sitemap-category-showing-disabled-categories

**Comment by maksek** [comment]
Hi @seansan, it is Magento 2 Github, and all issues must be related to Magento 2. Your issue content is about Magento 1. Please use proper resources for Magento 1.
