### ISSUE TITLE
magento setup:upgrade prompts to run compilation, even in developer mode

### ISSUE THREAD

**Issue by schmengler** [magento/magento2#11044]
In developer mode, `setup:di:compile` is not necessary and should not be executed. The `setup:upgrade` command asks for it independent of the current mode, which is confusing and misleading, especially for developers new to the platform.

### Preconditions

1.  Any Magento version up to 2.2
2. Developer Mode

### Steps to reproduce

1. Run `bin/magento setup:upgrade`

### Expected result

1. Migrations are executed

### Actual result
1. Migrations are executed
2. The message `"Please re-run Magento compile command. Use the command "setup:di:compile"` appears

**Comment by magento-engcom-team** [comment]
@schmengler, thank you for your report.
We've created internal ticket(s) MAGETWO-80082 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @schmengler the issue has been fixed in 2.2.1 and will be available soon (#11050)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80228

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81618
