### ISSUE TITLE
Improvements for Mage2 closed too fast

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1105]
Hi, we logged three issues for improvement for Mage2. Yes - we added examples of how it now works in Magento. But ONLY to explain our reasoning and why we think it can be improved. Are these issues now closed just becuase the words "magento 1.9" were used in the body? 

Please verify these issues for reason (not for use of words) - isn't Mage2 an improved version of Mage1?

#1104 
#1101   
#1100 

Sorry for opening a call for this. But I really think one should look into these simple quick wins... and one major ...

**Comment by victorgugo** [comment]
@seansan , thank you for reporting that. Could you, please, verify this issue on latest Magento2 taken from github? We should know if this is really actual for Mage2

**Comment by seansan** [comment]
OK - I need to do a re-install first. Let me get back on this.

(to my knowledge none of this is implemented though)

**Comment by vpelipenko** [comment]
@seansan, do you have updates for us?

**Comment by seansan** [comment]
sorry not yet - but as I stated I think some are relevant - as is

**Comment by vpelipenko** [comment]
Ok, we are waiting for details.

**Comment by seansan** [comment]
is there a demo of latest version available somewhere online? (instead of
having to install myself)

**Comment by vpelipenko** [comment]
No, we don't provide any demo stores.

**Comment by seansan** [comment]
Would actually help with the community shooting in ideas and bugs 






Sent from my iPhone.

On 25 Mar 2015, at 17:28, Vladimir Pelipenko <notifications@github.com> wrote:

No, we don't provide any demo stores.

**Comment by vpelipenko** [comment]
Thank you for suggestion. We will think about it.

**Comment by vpelipenko** [comment]
@seansan, hi again. We are still waiting for updates from you. You promised to check described issues on Magento 2 instance. Did you have a chance to do it?

**Comment by vpelipenko** [comment]
@seansan, feel free to reopen if you have any updates.
