### ISSUE TITLE
Store Online/Offline Status with each Credit Memo

### ISSUE THREAD

**Issue by jason-neumann** [magento/magento2#1106]
Currently credit memos don't store if their transaction was done online or offline. This can make it hard to tell what's happened to an order if there are multiple credit memo's applied to it. I suggest adding a column to `sales_flat_creditmemo` called online_refund that's a tinyint and is set to 1 if the refund is done online. This could then be added to the Credit Memo's main grid and when viewing an order and would enable quick filtering to see just the online or offline refunds.

This has great benefits from the merchant standpoint because you can then easily reconcile refunds made through Paypal (or whoever your gateway is) and refunds made by cash or whatever other method.

I would be willing to submit a pull request for the feature if it's something Magento is interested in.

**Comment by asemenenko** [comment]
Hi Jason,

I have an additional question to you regarding usage of Sales -> Transactions grid that allows to filter online transactions. Basically you need to add some of the capabilities of that grid to the credit memo's grid. What if that Transactions grid will show an offline and online documents? Will it solve your problem?

/regards
Andrii

**Comment by asemenenko** [comment]
@jason-neumann is there an update for my question from your side?

**Comment by jason-neumann** [comment]
Sorry I lost track of this.
I don't think modifying Sales -> Transactions grid would help here. Or at least it would be more work than my original suggestion. The transactions grid does not contain any information about offline credit memos, and it shouldn't, in my opinion. Offline credit memos are ones that occur outside of the magento system and likely weren't processed through paypal. As far as I understand it, an offline credit memo is just to track external credits. So we would have to first add code to create transactions for offline credit memos.

If that was added then we'd still have to look at the fact that the transaction's grid doesn't display any information on the amount of the transaction (kind of odd to me, but it's in 1,000 other places so I've never really cared about it). So there is the extra work involved to add that to the grid along with if it was an online or offline transaction.

So all in all I think it would be better to add the data to credit memos and their grid. But in the end it's your call.

**Comment by asemenenko** [comment]
Improvement is now described and captured in MAGETWO-991

/regards

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Store-Online-Offline-Status-with-each-Credit-Memo/idi-p/46604).
