### ISSUE TITLE
Can't override widgets .phtml file

### ISSUE THREAD

**Issue by ci2014** [magento/magento2#11061]
Hello there, I experience a strange issue with Magento 2, while I am trying to override a widgets .phtml file. In this certain case it's the file "grid.phtml" of the Magento 2 module-catalog-widget.

While overriding the file by simply putting the grid.phtml file to the right path in a custom theme is working without any problems, trying to do that from a custom module is NOT working.

In the custom module I placed it to the following directory, which I assume, would be correct:

./app/code/vendor/modulename/view/frontend/templates/product/widget/content/grid.phtml

Because the path above isn't working, I tried all possible other paths as well, like placing it to the folder Magento_CatalogWidget inside my custom module, which is not working as well.

For comparison, here is the path to the original file:
./vendor/magento/module-catalogwwidget/view/frontend/templates/product/widget/content/grid.phtml

If you put it next to each other, you can see, that I used the correct path:

./app/code/vendor/modulename/view/frontend/templates/product/widget/content/grid.phtml
./vendor/magento/module-catalog-widget/view/frontend/templates/product/widget/content/grid.phtml

I checked the server for other grid.phtml files to check if there are any other modules, which are overriding grid.phtml, but it's not the case.

Of course I used a sequence to make sure that the file is loaded after the original module.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="vendor_modulename" setup_version="2.0.0">
        <sequence>
            <module name="Magento_Catalog" />
            <module name="Magento_Widget" />
            <module name="Magento_Rule" />
            <module name="Magento_CatalogWidget" />
        </sequence>
    </module>
</config>
```

Even the template hints still show the full path to the original file instead of the path of the custom file.

Any ideas?

### Preconditions

1. Magento Version: Magento CE 2.1.9

### Steps to reproduce

1. Place a custom grid.phtml to the above mentioned path in a custom module
2. Check your shop if you notice any changes.

### Expected result

1. I expect my custom grid.phtml to be used instead of the original one. 

### Actual result

1. I see the original grid.phtml file, there are no changes noticeable at all.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by ci2014** [comment]
@orlangur Thank you for the information. I thought it might be a bug. There are already conversations on StackOverflow about this certain case, which is not working.

**Comment by orlangur** [comment]
In such case feel free to report an issue referring to SO discussion, of course. I can reopen this issue if you wish so that you can add SO link to description.

Generally it is not hard to understand why some `.phtml` is not applied in certain conditions. Usually there is some underlying `setTemplate` called explicitly which makes template attribute in layout XML noneffective.
