### ISSUE TITLE
Magento 2.1.9 no filter results since update from 2.1.7 to 2.1.9

### ISSUE THREAD

**Issue by coderiekelt** [magento/magento2#11065]
### Preconditions

1.  PHP 5.6
2. MariaDB
3. Nginx (latest)
4. Magento 2.1.9

### Steps to reproduce

1. Add an attribute, follow the usual steps (filter with results, anchor the category etc.)
2. View the product list and select a filter
3. The filter will return no results

### Expected result

1. There should be an overview of all products matching the filter

### Actual result

1. The page simply says "No results found for your search query".

**Comment by mikehenze** [comment]
See fix here:
https://github.com/magento/magento2/commit/2c62aa376eeed447e632aedb42085c9d255520df

**Comment by magento-engcom-team** [comment]
@coderiekelt, thank you for your report.
The issue is already fixed in 2.2.0
