### ISSUE TITLE
Checkout error for login customers that's have not saved shipping or billing information

### ISSUE THREAD

**Issue by rizwan4317** [magento/magento2#11066]
**Preconditions**

Magento 2.1.7 - PHP7

**Steps to reproduce**

Login in with existing customer or new customer that have not save shipping or billing address(fine working with customers who save shipping/billing address or gust users)
Add products to cart
Progress to cart and on checkout 
**Expected result**

Checkout should successfully complete
**Actual result**

At the 'Reviews and Payments' step the cart throws an error when pressing 'Place Order':
'An error occurred on the server, please try to order again.'

On inspection its showing:
http://prntscr.com/gpx8eu
'Failed to load resource: the server responded with a status of 400 (Bad Request)'

http://www.mywebsite.com/rest/default/V1/carts/mine/payment-information

Debugging has given me this:

{message: "An error occurred on the server. Please try to place the order again.",…}
message
:
"An error occurred on the server. Please try to place the order again."
trace
:
"#0 /home/--/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(278, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#1 /home/--var/generation/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#2 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(278, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#3 /home/lefkothiki/public_html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#4 /home/--/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#5 /home/lefkothiki/public_html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /home/lefkothiki/public_html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /home/lefkothiki/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#8 /home/----/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}"

I'm seriously lost, have tried everything and cannot get this issue sorted. Please help

**Comment by magento-engcom-team** [comment]
@rizwan4317, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
