### ISSUE TITLE
unused use statement in CustomOptionPrice class

### ISSUE THREAD

**Issue by will-b** [magento/magento2#11079]
### Preconditions

1. Magento develop branch HEAD:0f71c20995421518176544204c79badcc8c42997

### Steps to reproduce

1. view app/code/Magento/Catalog/Pricing/Price/CustomOptionPrice.php

### Expected result

1. use statements should not be superfluous

### Actual result

1. Unused use statement for Magento\Catalog\Pricing\Price;

**Comment by orlangur** [comment]
Not an issue by itself as it does not have any noticeable negative impact. BTW, if you try to solve some issue not reported yet in PR, there is no need to create an issue, just describe everything in PR description.
