### ISSUE TITLE
Saving configurable product in command unsets required_options and has_options (but saving in backend doesn't)

### ISSUE THREAD

**Issue by josefbehr** [magento/magento2#11088]
### Preconditions
1. MAMP Pro 4, MySQL 5.7, PHP 7.0.18, Magento 2.1.7 to 2.1.9
2. Have a catalog with configurable products that have assigned simple products for variants

### Steps to reproduce
1. Make sure that the association between configurable and simple still exists in the backend or db (to be sure, do a "save" in the backend)
2. Check that in the database (catalog_product_entity) the fields "has_options" and "required_options" are set at the configurable product
3. Write a simple CLI command to load and re-save the configurable product, eg:
`
        $this->searchCriteriaBuilder->addFilter(...);
        $products = $this->productRepository->getList($this->searchCriteriaBuilder->create());
        foreach ($products->getItems() as $product) {
            $this->productRepository->save($product);
        }
`
This also occurs, if product is loaded/saved using resourceModel. Since the "required_options" seems not to be set at this point, I'd guess, the product is not fully loaded. Do I have to use a collection and explicitly include the fields? What if they are already unset?
edit: I also do a `$state->setArea('adminhtml');` before

### Expected result
1. I'd expect the product to keep these fields' values, as they are used to decide if options are to be shown (eg. items.phtml -> if ($product->getRequiredOptions()) { ... })

### Actual result
1. After saving, "required_options" and "has_options" for this product is set to zero. This results in options only being shown on the product's own page, but not in sliders, lists, etc. It seems as if the product could be added to the cart, but then an error occurs, as no option is chosen.
![screen shot 2017-09-27 at 13 38 39](https://user-images.githubusercontent.com/4368880/30911556-66256788-a389-11e7-85ac-0a29e4132b1f.png)

**Comment by magento-engcom-team** [comment]
@josefbehr, thank you for your report.
We've created internal ticket(s) MAGETWO-80212 to track progress on the issue.

**Comment by Nix-id** [comment]
This bug is still relevant.

**Comment by xpoback** [comment]
As a temporary fix for my script I had to add `$product->setCanSaveCustomOptions(true)` before saving the configurable product. 
Maybe this helps someone.

**Comment by sdzhepa** [comment]
Hello @josefbehr 

Could you please confirm is this issue still actual for `2.4-develop` or we can close it?

**Comment by engcom-Charlie** [comment]
Hello @josefbehr 
It is known issue https://github.com/magento/magento2/issues/25754
I am closing this issue as duplicate.

Thanks for your report!
