### ISSUE TITLE
Varnish Cache issue

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#11083]
**Preconditions**

Magento 2.1.9 CE installed
Varnish 4 Installed and configured in Magento2 Admin
Set Varnish Cache under Admin -> Stores -> Configuration -> Advanced ->System -> Full Page Cache

**Steps to reproduce**

I have placed an order from the frontend.
Order not showing under Admin -> Sales-> Orders.
But in frontend order will be displayed in "My Account".
All the admin configurations not stored in first time save. It will be saved only after twice submitting to the configurations.

**Expected result:**

Order should be displayed in Admin -> Sales -> Orders.
Cache Management -> Select All -> Refresh -> Submit. Cache type should be refreshed.

**Actual result**

Order not showing under Admin -> Sales-> Orders.
Cache Management -> Select All -> Refresh -> Submit. Cache type not been refreshed. But if i repeat it again, then it will reflect it in admin.

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
