### ISSUE TITLE
Magento 2 : Set Shipping method handling fee using observer

### ISSUE THREAD

**Issue by devqualwebs** [magento/magento2#11082]
I was using an observer method to change shipping method handling fee in **magento v1.7.0.2** .

 The same thing I've to do with **magento 2**. The way which is using in **magento 1.7** is like this -

    $quote = $observer->getQuote();
    $store = Mage::app()->getStore($quote->getStoreId());
    $store->setConfig("carriers/{$carrierCode}/handling_type", 'F'); #F - Fixed, P -  Percentage
    $store->setConfig("carriers/{$carrierCode}/handling_fee", 105); #105 is custom handling fee

and the method `setConfig($path, $value)` is defined in 

    app/code/core/Mage/Core/Model/Store.php

**=> File :**

    /**
     * Set config value for CURRENT model
     *
     * This value don't save in config
     *
     * @param string $path
     * @param mixed $value
     * @return Mage_Core_Model_Store
     */
    public function setConfig($path, $value)
    {
        if (isset($this->_configCache[$path])) {
            $this->_configCache[$path] = $value;
        }
        $fullPath = 'stores/' . $this->getCode() . '/' . $path;
        Mage::getConfig()->setNode($fullPath, $value);

        return $this;
    }

I am trying to search same method in magento 2 directory. But not getting.

Please help me to do this.

**Comment by magento-engcom-team** [comment]
@devqualwebs, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
