### ISSUE TITLE
Magento_Tax "postcode is a required field" when upgrading from 2.1.9 to 2.2

### ISSUE THREAD

**Issue by friimaind** [magento/magento2#11095]
### Preconditions
Magento 2.1.9 CE
PHP 7.0.22-0ubuntu0.17.04.1
MySQL 5.7.19-0ubuntu0.17.04.1

### Steps to reproduce
Upgrade Magento 2.1.9 to 2.2 CE with composer

> composer require magento/product-community-edition 2.2 --no-update
> composer update
> php -f bin/magento setup:upgrade

### Expected result
Magento 2.2 updated

### Actual result
php -f bin/magento setup:upgrade returns:

> ...
> Module 'Magento_Swatches':
> Module 'Magento_SwatchesLayeredNavigation':
> Module 'Magento_Tax':
> Upgrading data.. postcode is a required field.

**Comment by magento-engcom-team** [comment]
@friimaind, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by rmendoza3** [comment]
I am having the same issue. I am also trying to upgrade from 2.1.9 to 2.2.0. I run into a "postcode is a required field." error and the setup:upgrade dies. If I find anything out I will be sure to update it here.

**Comment by kervin** [comment]
Same issue. @magento-engcom-team, create a tax rule without postcode first, then setup:upgrade.. seems obvious.

Test properly before saying "Can not reproduce"!

**Comment by JoostWan** [comment]
Same issue here. To fix this check the table **tax_calculation_rate**. When the field tax_postcode is empty enter a * 

Then the upgrade will work.

**Comment by friimaind** [comment]
Thanks @JoostWan , according to my database this query fixed the issue:

> UPDATE tax_calculation_rate SET tax_postcode = '*' WHERE tax_postcode IS NULL

**Comment by jwohlfeil** [comment]
Same Problem here, JoostWan's and friimaind's tipps fixed it.

**Comment by lewisvoncken** [comment]
@magento-engcom-team 
I can reproduce the issue and it is only when you have existing rules with tax_postcode NULL. Maybe I will provide a fix for this issue.

**Comment by lewisvoncken** [comment]
@friimaind  I supplied a pull request for this issue.

**Comment by lewisvoncken** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
@friimaind, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by orlangur** [comment]
@magento-engcom-team did you try steps from https://github.com/magento/magento2/pull/11735? So basically you need to set `null` manually to mentioned field in database to recreate circumstances of bug report.

**Comment by orlangur** [comment]
@lewisvoncken I don't see this issue was ever eligible for #SQUASHTOBERFEST

**Comment by TomashKhamlai** [comment]
Reproduced

**Comment by lewisvoncken** [comment]
@TomashKhamlai I also could reproduce and I have provided a fix in pull request #11735

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82595

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available in 2.2.2 release

**Comment by magento-engcom-team** [comment]
@friimaind, thank you for your report.
The issue is already fixed in 2.2.2
