### ISSUE TITLE
Re Index Command Is Not Working (Clean Installation 2.2)

### ISSUE THREAD

**Issue by Yan-Studio-WEB** [magento/magento2#11097]
### Preconditions

1. After clean Installation I get Message: "One or more indexers are invalid. Make sure your Magento cron job is running".
I Tryed with Putty to Run The Reindex Command i get only error
2. PHP 7.1.9. Magento 2. 2.

### Steps to reproduce

1. Just Install the New Magento
2. Run with Putty ReIndex Command
3. 

### Expected result

1. Re index to work

### Actual result

1. Re-Index didn't Work

**Comment by magento-engcom-team** [comment]
@iWEBproject, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by Yan-Studio-WEB** [comment]
OK
Just read What i Get Fro Site Ground Technicians:

Hello Yan,

Thank you for contacting us.

I performed a few tests on my end as well and it looks like the Magento application you have installed is incomplete and/or corrupted, which results in the issue you are experiencing. In order to confirm that, I installed a new Magento version 2.1.9 in your account and managed to run the command without any issues as seen here:

Code:
nuovamod@ams15 [~/public_html/sgtest]# php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00

The application I installed is now deleted, however, since you have mentioned that the application you are using is brand new, then what I would like to suggest you is to simply install a new Magento from the Softaculous Apps Installer in your cPanel and the issue should be resolved. 

The reason why the Magento 2.2 is still not part of our Softaculous Apps Installer list is because everytime before we add a new application, we make sure that latest releases are stable and tested in-house first in order to avoid any issues and/or complications with the newly installed software. That being said, I will recommend to you to use Magento version 2.1.9 instead.

Please also note, that all of our servers are based on CentOS and not Ubuntu, and the current version of CentOS is 6.5. 

As for the MySQL version, it is the following:
mysql Ver 14.14 Distrib 5.6.36-82.1, for Linux (x86_64) using 6.0

Best Regards,

Preslav Kenanov
Technical Support Team
