### ISSUE TITLE
I can´t finish updated to Magento 2.2 due to this issue: tedivm/jshrink version

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#11096]
### Preconditions
Magento 2.1.9 CE
PHP 7.0.22-0ubuntu0.17.04.1
MySQL 5.7.19-0ubuntu0.17.04.1

### Steps to reproduce
Upgrade Magento 2.1.9 to 2.2 CE with composer

composer require magento/product-community-edition 2.2 --no-update
composer update
php -f bin/magento setup:upgrade
### Expected result

Magento 2.2 updated

### Actual result
I can´t finish updated to Magento 2.2 due to this issue:
 Installation request for tedivm/jshrink (locked at v1.0.1) -> satisfiable by tedivm/jshrink[v1.0.1].
    - magento/product-community-edition 2.2.0 requires tedivm/jshrink ~1.1.0 -> satisfiable by tedivm/jshrink[v1.1.0].
    - magento/product-community-edition 2.2.0 requires tedivm/jshrink ~1.1.0 -> satisfiable by tedivm/jshrink[v1.1.0].
    - Conclusion: don't install tedivm/jshrink v1.1.0
    - Installation request for magento/product-community-edition 2.2 -> satisfiable by magento/product-community-edition[2.2.0].

**Comment by orlangur** [comment]
> Installation request for tedivm/jshrink (locked at v1.0.1)

Well, why did you lock it? Do also

`composer require tedivm/jshrink ~1.1.0 --no-update`

And then `composer update`.

**Comment by storepeinture** [comment]
I get the same issue when upgrading from Magento 2.1.9 to 2.2.0:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: tedivm/jshrink[v1.1.0, v1.0.1].
    - Can only install one of: tedivm/jshrink[v1.1.0, v1.0.1].
    - Can only install one of: tedivm/jshrink[v1.1.0, v1.0.1].
    - magento/product-community-edition 2.2.0 requires tedivm/jshrink ~1.1.0 ->                                                                                                              satisfiable by tedivm/jshrink[v1.1.0].
    - Installation request for magento/product-community-edition 2.2.0 -> satisf                                                                                                             iable by magento/product-community-edition[2.2.0].
    - Installation request for tedivm/jshrink (locked at v1.0.1) -> satisfiable                                                                                                              by tedivm/jshrink[v1.0.1].
```

After following orlangurs advice:
`composer require tedivm/jshrink ~1.1.0 --no-update`
And then `composer update`.

I receive the error again.

Is there a way to upgrade all packages and dependencies at once? Or is that rather risky that things might not work well together afterwards?

**Comment by orlangur** [comment]
Please try `composer why-not tedivm/jshrink 1.1.0`. You can upgrade multiple packages but you cannot ignore constraint if some of them require older jshrink version.

**Comment by storepeinture** [comment]
Thank you! I ran  
`composer why-not tedivm/jshrink 1.1.0`
Composer Feedback
```
magento/magento2-base              2.1.9  requires  tedivm/jshrink (~1.0.1)
magento/product-community-edition  2.1.9  requires  tedivm/jshrink (~1.0.1)
```
So it looks like magento 2.1.9 doesn't let me upgrade to jshrink 1.1.0? But magento 2.2.0 requires it?

**Comment by orlangur** [comment]
Yes, but after `composer require magento/product-community-edition 2.2 --no-update` you normally shouldn't see `2.1.9` blocking update.

**Comment by salelsol** [comment]
Need help for fix this composer issue:

  Problem 1
    - Conclusion: don't install magento/product-community-edition 2.2.0
    - magento/framework 100.1.9 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.3 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.4 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.5 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.6 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.7 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.8 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.9 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.3 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.4 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.5 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.6 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.7 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.8 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.1.9 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.13 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.14 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.15 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.16 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.17 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.18 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.13 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.14 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.15 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.16 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.17 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - magento/framework 100.0.18 requires zendframework/zend-stdlib ~2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.13, 2.4.10, 2.4.11, 2.4.12, 2.4.6, 2.4.7, 2.4.8, 2.4.9].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.13].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.13].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.10].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.11].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.12].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.6].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.7].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.8].
    - Can only install one of: zendframework/zend-stdlib[2.7.7, 2.4.9].
    - magento/product-community-edition 2.2.0 requires zendframework/zend-stdlib ^2.7.7 -> satisfiable by zendframework/zend-stdlib[2.7.7].
    - Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].
    - magento2translations/language_es_es dev-master requires magento/framework ~100.0 -> satisfiable by magento/framework[100.1.9, 100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.2.0-rc20, 100.0.18].
    - magento2translations/language_es_es dev-master requires magento/framework ~100.0 -> satisfiable by magento/framework[100.1.9, 100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.2.0-rc20, 100.0.18].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc1].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc2].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc3].
    - Can only install one of: magento/framework[101.0.0, 100.1.0].
    - Can only install one of: magento/framework[101.0.0, 100.1.1].
    - Can only install one of: magento/framework[101.0.0, 100.1.2].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc1].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc2].
    - Can only install one of: magento/framework[101.0.0, 100.1.0-rc3].
    - Can only install one of: magento/framework[101.0.0, 100.1.0].
    - Can only install one of: magento/framework[101.0.0, 100.1.1].
    - Can only install one of: magento/framework[101.0.0, 100.1.2].
    - Can only install one of: magento/framework[101.0.0, 100.0.2].
    - Can only install one of: magento/framework[101.0.0, 100.0.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.6].
    - Can only install one of: magento/framework[101.0.0, 100.0.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.8].
    - Can only install one of: magento/framework[101.0.0, 100.0.9].
    - Can only install one of: magento/framework[101.0.0, 100.0.10].
    - Can only install one of: magento/framework[101.0.0, 100.0.11].
    - Can only install one of: magento/framework[101.0.0, 100.0.12].
    - Can only install one of: magento/framework[101.0.0, 100.2.0-rc20].
    - Can only install one of: magento/framework[101.0.0, 100.0.2].
    - Can only install one of: magento/framework[101.0.0, 100.0.3].
    - Can only install one of: magento/framework[101.0.0, 100.0.4].
    - Can only install one of: magento/framework[101.0.0, 100.0.5].
    - Can only install one of: magento/framework[101.0.0, 100.0.6].
    - Can only install one of: magento/framework[101.0.0, 100.0.7].
    - Can only install one of: magento/framework[101.0.0, 100.0.8].
    - Can only install one of: magento/framework[101.0.0, 100.0.9].
    - Can only install one of: magento/framework[101.0.0, 100.0.10].
    - Can only install one of: magento/framework[101.0.0, 100.0.11].
    - Can only install one of: magento/framework[101.0.0, 100.0.12].
    - Can only install one of: magento/framework[101.0.0, 100.2.0-rc20].
    - magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
    - Conclusion: don't install magento/framework 101.0.0
    - Installation request for magento2translations/language_es_es dev-master -> satisfiable by magento2translations/language_es_es[dev-master].

**Comment by orlangur** [comment]
@salelsol,
>  magento2translations/language_es_es dev-master requires magento/framework ~100.0

looks like it's your language pack causing the trouble. Try upgrading it together with `magento/product-community-edition` or replace with your local fork having other constraint allowing `101.x`. Note that relying on `dev-master` is never a good idea, packages needs to be tagged properly.

**Comment by salelsol** [comment]
Hi, any help with this issue:
 - The requested package magento2translations/language_es_es ~1.1.0 exists as magento2translations/language_es_es[2.0.2.x-dev, 2.0.7.x-dev, dev-Head, dev-master] but these are rejected by your constraint.

**Comment by storepeinture** [comment]
I solved the issue by deleting the package that was causing the issue - and then reinstalling it ...
Even though my provider had a package ready for Magento 2.2, for whatever reason it wasn't installing.

I simply deleted the package. But honestly, that's not how it should be done. But it seems there was no better workaround.

**Comment by orlangur** [comment]
> Even though my provider had a package ready for Magento 2.2, for whatever reason it wasn't installing.

@storepeinture this is just improper Composer usage. You need to update both this package and Magento at the same time.

**Comment by storepeinture** [comment]
Yes, orlangur, I know it is improper. But it wouldn't accept the package and Magento upgrade at the same time. Probably a bug or some other conflict which wasn't obvious to me or the magento developer which I hired to solve the issue.

**Comment by orlangur** [comment]
@storepeinture there is no bug and there is no something Magento can fix as far as I understood your issue.

```
composer require magento/product-community-edition 2.2 --no-update
composer update
php -f bin/magento setup:upgrade
```

After the first command you may require proper versions of all necessary third party packages. Otherwise Composer will treat them as locked at certain version and will try to upgrade Magento itself only.

Removal+reinstallation package as you did it is not bad as well, Composer will just find appropriate package version automatically.

**Comment by storepeinture** [comment]
Yes, I believe that the package provider has had some error in the declaration of his package version.
Because normally upgrade just works fine for me.

I also know now, that it's not an issue of magento. But I thought I keep posting how I found a workaround for anybody who will stumble across this issue.

**Comment by orlangur** [comment]
> some error in the declaration of his package version

Oh, yeah, I missed probability of this. If package constraints are incorrect it's a _really_ different painful story.

**Comment by brandontamm** [comment]
@orlangur - hi. I noticed you mentioned this is improper usage of composer. this is actually the exact recommended upgrade procedure by @magento-admin : https://devdocs.magento.com/guides/v2.1/comp-mgr/cli/cli-upgrade.html

Magento documentation is broken. They have you composer create-project which creates a project with multiple dependencies in it's composer.json .. since the instruct users to create project that way,  every user following Magento's Install Documentation WILL NOT be able to upgrade using their Upgrade Documentation

Does that make sense? composer require magento/product-community-edition:2.2.1 will always produce this result because within that json file there are other version constraints and dependencies and configuration contained within the json file that were not updated to the exact same as magento 2.2.1 composer.json file....

The CORRECT composer usage would be to create your own project and composer require magento as a dependency so the entire codebase (including composer.json) would be updated....

I cannot believe that Magento has not caught on to this "non-issue" yet after so many complaints...
