### ISSUE TITLE
Issues with .less files on initial installation

### ISSUE THREAD

**Issue by robjmills** [magento/magento2#1109]
On a clean installation of beta11, cloned from Github, i'm seeing a bunch of errors relating to .less files not existing, for example:

```
FileError: 'http://mage2.dev/pub/static/frontend/Magento/luma/en_US/Magento_Paypal/css/source/_module.less' wasn't found (404)
in styles-l.css on line 23, column 1:

22@import '../Magento_Multishipping/css/source/_module.less';
23@import '../Magento_Paypal/css/source/_module.less';
24@import '../Magento_Weee/css/source/_module.less';
```

I'm able to fix this by running:

```
php dev/tools/Magento/Tools/View/deploy.php
```

which I saw referenced elsewhere. not sure if this is a bug or an issue with my installation procedure.

**Comment by robjmills** [comment]
actually, trying this again and the fix doesn't seem to work now.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-34935. This issue is already fixed and will be available for community after next weekly update.

**Comment by vpelipenko** [comment]
@robjmills, this issue is already available in public repository. Please, check it again.

**Comment by robjmills** [comment]
Yep, all good now!

**Comment by vpelipenko** [comment]
Closed. @robjmills, if you have any other questions or know about some bugs, please, feel free to post new issues here.
