### ISSUE TITLE
Issue with model additon 

### ISSUE THREAD

**Issue by tblpraveen** [magento/magento2#11091]
I am new to magento and added module but ended up with an error 
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'name': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z0-9][a-zA-Z\d\-_\.]*'.
Line: 677

I cleard cache using magento cache:clean but no luck.

**Comment by tblpraveen** [comment]
I am new to magento and added module but ended up with an error
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'name': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z0-9][a-zA-Z\d-_.]*'.
Line: 677

I cleard cache using magento cache:clean but no luck.

**Comment by orlangur** [comment]
Error message is pretty clear. Fix any block references with empty name, like `<referenceBlock name=""`.

**Comment by magento-engcom-team** [comment]
@tblpraveen, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
