### ISSUE TITLE
Need Autocomplete Preview Feature for Site Search

### ISSUE THREAD

**Issue by choukalos** [magento/magento2#11104]
### Card
**As a** customer I want an autocomplete / preview of suggested search terms and top products displayed to me as I'm typing in my search query **so that** I can find what I want to buy faster.

### Notes / Details
- Top suggested products should display product name, short description,product picture, product price
- Admin should be able to configure # of suggested search terms (default 3) and suggested products (default 3)
- Should work well for tablets and mobiles
- Autocomplete/Preview results should be cached for performance.  
-- To keep effort low, cache can be managed by TTL configuration or manual purge action by admin

Coding Details / Pointers to Interfaces to use
- [Stackexchange Thread Where @paliarush provided insights on interfaces to use for autocomplete/preview](https://magento.stackexchange.com/questions/90209/magento2-advanced-searching-smartsearch/90607#90607)
- Should be easy to extend/customize.  Ie CMS search is another feature on our radar
- Rough Mockup of Preview Config:
<img width="295" alt="screen shot 2017-09-27 at 5 07 11 pm" src="https://user-images.githubusercontent.com/145978/30940392-90ff7364-a3a6-11e7-9a6a-58043fff1560.png">
- Rough Mockup of Autocomplete/Preview:
<img width="231" alt="screen shot 2017-09-27 at 5 07 04 pm" src="https://user-images.githubusercontent.com/145978/30940386-8cf78d10-a3a6-11e7-8610-e12640055175.png">

### Acceptance Criteria (AC)

1.  As customer types in search query they see top suggested search terms and top suggested products for the partially matched search query.
2.  A customer can select a suggested search terms or top suggested product and execute that search term query or go right to that product page.  They can also select all product results link.  Alternatively they can hit enter and execute their search query as they have entered it.
4.  An administrator can configure how many top suggested products and top suggested search terms to display
5.  Developed using public apis; adding appropriate public apis so feature can be easily customized or extended in the future

**Comment by magento-engcom-team** [comment]
Hi @choukalos. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/21
