### ISSUE TITLE
M2 2.1.9 : After migration, Reindex error - SQLSTATE[42000]: Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by meezin** [magento/magento2#11103]
### Preconditions

1. Magento CE 2.1.9 (PHP 7, **MySQL 5.6.37**) 
2. Magento CE 1.9.1.0 (PHP 7, **MySQL 5.6.37** )

They are on same server domain anyway

### Steps to reproduce

1. Migration from 1.9.1.0 to 2.1.9
2. After migration is done, reindex
3. Only index categories related with Product/Catalog doesn't work at all

### Expected result

1. It should be re-indexed without any error message 

### Actual result

1. [Screenshot, logs]

[devkbethos@01-sh-km238 public_html]$ **php bin/magento indexer:reindex**
**Design Config Grid index has been rebuilt successfully in 00:00:06
Customer Grid index has been rebuilt successfully in 00:00:24**
**_Category Products indexer process unknown error:_**
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax t                                                          o use near 'JOIN `catalog_product_entity_int` AS `cpss` ON cpss.entity_id = cp.entity_id AND' at line 4, query was: SELECT COUNT(*) as cnt FROM (SELECT 3 AS `category_id`, `cp`.`e                                                          ntity_id` AS `product_id`, IF(ccp.product_id IS NOT NULL, ccp.position, 0) AS `position`, IF(ccp.product_id IS NOT NULL, 1, 0) AS `is_parent`, 1 AS `store_id`, IFNULL(cpvs.value,                                                           cpvd.value) AS `visibility` FROM `catalog_product_entity` AS `cp`
 INNER JOIN `catalog_product_website` AS `cpw` ON cpw.product_id = cp.entity_id
 INNER JOIN `catalog_product_entity_int` AS `cpsd` ON cpsd.entity_id = cp.entity_id AND cpsd.store_id = 0 AND cpsd.attribute_id =
 LEFT JOIN `catalog_product_entity_int` AS `cpss` ON cpss.entity_id = cp.entity_id AND cpss.attribute_id = cpsd.attribute_id AND cpss.store_id = 1
 INNER JOIN `catalog_product_entity_int` AS `cpvd` ON cpvd.entity_id = cp.entity_id AND cpvd.store_id = 0 AND cpvd.attribute_id =
 LEFT JOIN `catalog_product_entity_int` AS `cpvs` ON cpvs.entity_id = cp.entity_id AND cpvs.attribute_id = cpvd.attribute_id  AND cpvs.store_id = 1
 LEFT JOIN `catalog_category_product` AS `ccp` ON ccp.product_id = cp.entity_id WHERE (cpw.website_id = '1') AND (IFNULL(cpss.value, cpsd.value) = 1) AND (IFNULL(cpvs.value, cpvd.                                                          value) IN (2, 3, 4)) GROUP BY `cp`.`entity_id`) AS `t`
**Product Categories indexer process unknown error:**
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax t                                                          o use near 'JOIN `catalog_product_entity_int` AS `cpss` ON cpss.entity_id = cp.entity_id AND' at line 4, query was: SELECT COUNT(*) as cnt FROM (SELECT 3 AS `category_id`, `cp`.`e                                                          ntity_id` AS `product_id`, IF(ccp.product_id IS NOT NULL, ccp.position, 0) AS `position`, IF(ccp.product_id IS NOT NULL, 1, 0) AS `is_parent`, 1 AS `store_id`, IFNULL(cpvs.value,                                                           cpvd.value) AS `visibility` FROM `catalog_product_entity` AS `cp`
 INNER JOIN `catalog_product_website` AS `cpw` ON cpw.product_id = cp.entity_id
 INNER JOIN `catalog_product_entity_int` AS `cpsd` ON cpsd.entity_id = cp.entity_id AND cpsd.store_id = 0 AND cpsd.attribute_id =
 LEFT JOIN `catalog_product_entity_int` AS `cpss` ON cpss.entity_id = cp.entity_id AND cpss.attribute_id = cpsd.attribute_id AND cpss.store_id = 1
 INNER JOIN `catalog_product_entity_int` AS `cpvd` ON cpvd.entity_id = cp.entity_id AND cpvd.store_id = 0 AND cpvd.attribute_id =
 LEFT JOIN `catalog_product_entity_int` AS `cpvs` ON cpvs.entity_id = cp.entity_id AND cpvs.attribute_id = cpvd.attribute_id  AND cpvs.store_id = 1
 LEFT JOIN `catalog_category_product` AS `ccp` ON ccp.product_id = cp.entity_id WHERE (cpw.website_id = '1') AND (IFNULL(cpss.value, cpsd.value) = 1) AND (IFNULL(cpvs.value, cpvd.                                                          value) IN (2, 3, 4)) GROUP BY `cp`.`entity_id`) AS `t`
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND tad_status.store_id = 0
 LEFT JOIN `catalog_product_entity` AS `tas_status` ' at line 9, query was: INSERT INTO `catalog_product_index_price_final_idx` SELECT `e`.`entity_id`, `cg`.`customer_group_id`, `                                                          cw`.`website_id`, IF(IFNULL(tas_tax_class_id.value_id, -1) > 0, tas_tax_class_id.value, tad_tax_class_id.value) AS `tax_class_id`, IFNULL((IF(IFNULL(tas_price.value_id, -1) > 0, t                                                          as_price.value, tad_price.value)), 0) AS `orig_price`, IFNULL((IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value)) <= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IF(IF NULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_                                                          to_date.value, tad_special_to_date.value)) >= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.valu                                                          e) < IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value), IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value), IF                                                          (IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value))), 0) AS `price`, IFNULL((IF(IF(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.val                                                          ue, tad_special_from_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value)) <= DATE(cwd.webs                                                          ite_date), 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_to_da                                                          te.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value)) >= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_p                                                          rice.value, tad_special_price.value) < IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value), IF(IFNULL(tas_special_price.value_id, -1) > 0, tas_special_price.v                                                          alue, tad_special_price.value), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value))), 0) AS `min_price`, IFNULL((IF(IF(IF(IFNULL(tas_special_from_date.value_                                                          id, -1) > 0, tas_special_from_date.value, tad_special_from_date.value) IS NULL, 1, IF(DATE(IF(IFNULL(tas_special_from_date.value_id, -1) > 0, tas_special_from_date.value, tad_spec                                                          ial_from_date.value)) <= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value) IS NULL,                                                           1, IF(DATE(IF(IFNULL(tas_special_to_date.value_id, -1) > 0, tas_special_to_date.value, tad_special_to_date.value)) >= DATE(cwd.website_date), 1, 0)) > 0 AND IF(IFNULL(tas_special_                                                          price.value_id, -1) > 0, tas_special_price.value, tad_special_price.value) < IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value), IF(IFNULL(tas_special_price.                                                          value_id, -1) > 0, tas_special_price.value, tad_special_price.value), IF(IFNULL(tas_price.value_id, -1) > 0, tas_price.value, tad_price.value))), 0) AS `max_price`, tp.min_price A                                                          S `tier_price`, tp.min_price AS `base_tier` FROM `catalog_product_entity` AS `e`
 CROSS JOIN `customer_group` AS `cg`
 CROSS JOIN `store_website` AS `cw`
 INNER JOIN `catalog_product_index_website` AS `cwd` ON cw.website_id = cwd.website_id
 INNER JOIN `store_group` AS `csg` ON csg.website_id = cw.website_id AND cw.default_group_id = csg.group_id
 INNER JOIN `store` AS `cs` ON csg.default_store_id = cs.store_id AND cs.store_id != 0
 INNER JOIN `catalog_product_website` AS `pw` ON pw.product_id = e.entity_id AND pw.website_id = cw.website_id
 LEFT JOIN `catalog_product_index_tier_price` AS `tp` ON tp.entity_id = e.entity_id AND tp.website_id = cw.website_id AND tp.customer_group_id = cg.customer_group_id
 INNER JOIN `catalog_product_entity` AS `tad_status` ON tad_status.entity_id = e.entity_id AND tad_status.attribute_id =  AND tad_status.store_id = 0
 LEFT JOIN `catalog_product_entity` AS `tas_status` ON tas_status.entity_id = e.entity_id AND tas_status.attribute_id =  AND tas_status.store_id = cs.store_id
 LEFT JOIN `catalog_product_entity` AS `tad_tax_class_id` ON tad_tax_class_id.entity_id = e.entity_id AND tad_tax_class_id.attribute_id =  AND tad_tax_class_id.store_id = 0
 LEFT JOIN `catalog_product_entity` AS `tas_tax_class_id` ON tas_tax_class_id.entity_id = e.entity_id AND tas_tax_class_id.attribute_id =  AND tas_tax_class_id.store_id = cs.store                                                          _id
 LEFT JOIN `catalog_product_entity` AS `tad_price` ON tad_price.entity_id = e.entity_id AND tad_price.attribute_id =  AND tad_price.store_id = 0
 LEFT JOIN `catalog_product_entity` AS `tas_price` ON tas_price.entity_id = e.entity_id AND tas_price.attribute_id =  AND tas_price.store_id = cs.store_id
 LEFT JOIN `catalog_product_entity` AS `tad_special_price` ON tad_special_price.entity_id = e.entity_id AND tad_special_price.attribute_id =  AND tad_special_price.store_id = 0
 LEFT JOIN `catalog_product_entity` AS `tas_special_price` ON tas_special_price.entity_id = e.entity_id AND tas_special_price.attribute_id =  AND tas_special_price.store_id = cs.s                                                          tore_id
 LEFT JOIN `catalog_product_entity` AS `tad_special_from_date` ON tad_special_from_date.entity_id = e.entity_id AND tad_special_from_date.attribute_id =  AND tad_special_from_date                                                          .store_id = 0
 LEFT JOIN `catalog_product_entity` AS `tas_special_from_date` ON tas_special_from_date.entity_id = e.entity_id AND tas_special_from_date.attribute_id =  AND tas_special_from_date.store_id = cs.store_id
 LEFT JOIN `catalog_product_entity` AS `tad_special_to_date` ON tad_special_to_date.entity_id = e.entity_id AND tad_special_to_date.attribute_id =  AND tad_special_to_date.store_i                                                          d = 0
 LEFT JOIN `catalog_product_entity` AS `tas_special_to_date` ON tas_special_to_date.entity_id = e.entity_id AND tas_special_to_date.attribute_id =  AND tas_special_to_date.store_i                                                          d = cs.store_id WHERE (e.type_id = 'simple') AND (IF(IFNULL(tas_status.value_id, -1) > 0, tas_status.value, tad_status.value)=1)
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JOIN `catalog_product_entity_int` AS `d2s` ON d2s.store_id = s.store_id AND d2s.' at line 5, query was: INSERT INTO `catalog_product_index_eav_idx` SELECT DISTINCT  `p                                                          id`.`entity_id`, `pid`.`attribute_id`, `pid`.`store_id`, IFNULL(pis.value, pid.value) AS `value`, `pid`.`entity_id` FROM (SELECT DISTINCT  `s`.`store_id`, `s`.`website_id`, `dd`.`                                                          attribute_id`, COALESCE(ds.value, dd.value) AS `value`, `cpe`.`entity_id` FROM `store` AS `s`
 LEFT JOIN `catalog_product_entity_int` AS `dd` ON dd.store_id = 0
 LEFT JOIN `catalog_product_entity_int` AS `ds` ON ds.store_id = s.store_id AND ds.attribute_id = dd.attribute_id AND ds.entity_id = dd.entity_id
 LEFT JOIN `catalog_product_entity_int` AS `d2d` ON d2d.store_id = 0 AND d2d.entity_id = dd.entity_id AND d2d.attribute_id =
 LEFT JOIN `catalog_product_entity_int` AS `d2s` ON d2s.store_id = s.store_id AND d2s.attribute_id = d2d.attribute_id AND d2s.entity_id = d2d.entity_id
 LEFT JOIN `catalog_product_entity` AS `cpe` ON cpe.entity_id = dd.entity_id WHERE (s.store_id != 0) AND ((ds.value IS NOT NULL OR dd.value IS NOT NULL)) AND (COALESCE(d2s.value,                                                           d2d.value) = 1)) AS `pid`
 LEFT JOIN `catalog_product_entity_int` AS `pis` ON pis.entity_id = pid.entity_id AND pis.attribute_id = pid.attribute_id AND pis.store_id = pid.store_id WHERE (pid.attribute_id I                                                          N('102', '107', '501', '513', '964', '1055', '1056', '1109')) AND (IFNULL(pis.value, pid.value) IS NOT NULL) AND (NOT(pis.value IS NULL AND pis.value_id IS NOT NULL))
Stock index has been rebuilt successfully in 00:00:04
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') and pp_default.store_id=0
 INNER JOIN `catalog_product_website` AS `product_we' at line 3, query was: SELECT `rp`.*, IFNULL(pp4.value, pp_default.value) AS `default_price` FROM `catalogrule_product` AS `rp                                                          `
 INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = rp.product_id
 INNER JOIN `catalog_product_entity` AS `pp_default` ON pp_default.entity_id=e.entity_id AND (pp_default.attribute_id=) and pp_default.store_id=0
 INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id=rp.product_id AND product_website.website_id = rp.website_id AND product_website.website_i                                                          d=4
 LEFT JOIN `catalog_product_entity` AS `pp4` ON pp4.entity_id=e.entity_id AND (pp4.attribute_id=) and pp4.store_id=8 ORDER BY `rp`.`website_id` ASC, `rp`.`customer_group_id` ASC,                                                           `rp`.`product_id` ASC, `rp`.`sort_order` ASC, `rp`.`rule_id` ASC

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') and pp_default.store_id=0
 INNER JOIN `catalog_product_website` AS `product_we' at line 3, query was: SELECT `rp`.*, IFNULL(pp4.value, pp_default.value) AS `default_price` FROM `catalogrule_product` AS `rp                                                          `
 INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = rp.product_id
 INNER JOIN `catalog_product_entity` AS `pp_default` ON pp_default.entity_id=e.entity_id AND (pp_default.attribute_id=) and pp_default.store_id=0
 INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id=rp.product_id AND product_website.website_id = rp.website_id AND product_website.website_i                                                          d=4
 LEFT JOIN `catalog_product_entity` AS `pp4` ON pp4.entity_id=e.entity_id AND (pp4.attribute_id=) and pp4.store_id=8 ORDER BY `rp`.`website_id` ASC, `rp`.`customer_group_id` ASC,                                                           `rp`.`product_id` ASC, `rp`.`sort_order` ASC, `rp`.`rule_id` ASC

**Catalog Search index has been rebuilt successfully in 00:08:43**

**Comment by magento-engcom-team** [comment]
Hi @meezin 
Looks like this issue is related to migration tool. Please file an issue report to the [migration repository](https://github.com/magento/data-migration-tool).
Thank you
