### ISSUE TITLE
example for calendar widget usage in knockoutjs template, to allow date and time selection?

### ISSUE THREAD

**Issue by rparsi-commer** [magento/magento2#11105]
The developer docs do not give concrete example of how to use the magento2 calendar widget.
I have searched this topic extensively, only found examples for the datepicker.
However in my case the user needs to be able to specify a date and time.
The observable for the value already exists.

### Preconditions
1. Magento 2 CE 2.1.7
2. PHP 7.1
3. In custom module create a knockoutjs template

In the html file (knockoutjs template) I want to have a single text field for date and time.

What do I put in the `data-bind`?
```
<input type="text" data-bind="value: getObservable('someDatetimeValue'), ...what goes here?" />
```

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
