### ISSUE TITLE
html editor

### ISSUE THREAD

**Issue by smartstoremx** [magento/magento2#11109]
![after update you get this](https://user-images.githubusercontent.com/30731883/30951969-acc182de-a3f3-11e7-8fed-68459f494ff0.jpg)
![writehtml](https://user-images.githubusercontent.com/30731883/30951970-acc235da-a3f3-11e7-90f9-236f8843a0ba.png)
![writehtml](https://user-images.githubusercontent.com/30731883/30951978-b31f3af4-a3f3-11e7-8c14-c20f464be8ce.png)
![after update you get this](https://user-images.githubusercontent.com/30731883/30951984-ba611efe-a3f3-11e7-837a-4feeafd1be90.jpg)

### Preconditions

Magento 2.2
1. Content - Blocks
2. 

### Steps to reproduce

1. Goto Content-Blocks
2. Edit my slider block using the html editor
3. Write many likes see the picture 1.  I am using this:
          <div data-src="{{view url='images/camera/slides/slide1.jpg'}}">
4. I press update
5. When I open to see the code this change to:
    a class="camera_caption_txt--btn" 
 href="http://localhost/s2/admin2/cms/wysiwyg/directive/___directive/e3tzdG9yZSB1cmw9J21lbi5odG1sJ319/key/60e2edd93d70c88b278b9281a60f6ee9a83b4c797978b796f7ab8960ee8637c7/">Shop now!</a></div>

![writehtml](https://user-images.githubusercontent.com/30731883/30951960-9fedfb50-a3f3-11e7-9c2b-9dcfc4c7f9ff.png)

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by smartstoremx** [comment]
Magento 2.1.9 works fine but in Magento 2.2 it fails when you update any html in the block area. I hope it helps.

**Comment by smartstoremx** [comment]
I expected my html do not change when I save it.

**Comment by renttek** [comment]
Hey,

It seems, that this conversion of directives to urls is intended.
(If this wouldn't be converted on save, then it had to be done on rendering, which may decreased performance of initial page delivery)

In <root>/lib/web/mage/adminhtml/wysiwyg/tiny_mce/setup.js:410 is a function/method "makeDirectiveUrl" which is converts all directives in html attributes.
This is triggered by "beforeSetContent" > "encodeContent" > "encodeDirectives" in the same file.

Beside this, is there a error when you try to save/update the content?
If yes, is there an explicit error message shown?

**Comment by PieterCappelle** [comment]
Hi, this is related to this issue https://github.com/magento/magento2/issues/10417 and fixed with my PR https://github.com/magento/magento2/pull/11048

**Comment by okorshenko** [comment]
@smartstoremx thank you for your report. The issue is already fixed in 2.2-develop branch (PR: #11048 by @PieterCappelle) and will be available in the Magento 2.2.2 release
