### ISSUE TITLE
Magento 2.2 upgrade issue

### ISSUE THREAD

**Issue by ghost** [magento/magento2#11107]
![issue](https://user-images.githubusercontent.com/17496183/30943883-76cb58b6-a3f4-11e7-8059-a47e0b1c3c5c.jpg)

### Preconditions

Magento 2.2
Php 7.0
Appache 2.4
Ubuntu 16
MySQL 5.7

1. 
2. 

### Steps to reproduce

1. composer require magento/product-community-edition 2.2 --no-update
2. composer update
3. php bin/magento setup:upgrade

### Expected result

1. complete upgrade

### Actual result

1. Running schema recurring...We can't find the role for the user you wanted.
2. In exeption.log:

[2017-09-28 00:02:16] main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magentodb.customer_group' doesn't exist, query was: SELECT COUNT(*) FROM `customer_group` AS `main_table` {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magentodb.customer_group' doesn't exist, query was: SELECT COUNT(*) FROM `customer_group` AS `main_table` at /var/www/html/vendor/magento/module-catalog/Model/Indexer/Product/Price/Action/Full.php:159, Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magentodb.customer_group' doesn't exist, query was: SELECT COUNT(*) FROM `customer_group` AS `main_table` at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magentodb.customer_group' doesn't exist at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"} []

**Comment by orlangur** [comment]
Well, error message is quite clear. Do you have `customer_group` table in fact?

**Comment by ghost** [comment]
Not table customer_group in my database

**Comment by orlangur** [comment]
Well, it should be there, I don't see this table was ever removed in `app/code/Magento/Customer/Setup`.

Try restoring database from your latest backup, check `customer_group` table is in place and perform an upgrade one more time.

**Comment by ghost** [comment]
Thank you but whent i launch tollback db process, i have this error:

SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint, query was: CREATE TABLE IF NOT EXISTS `customer_group` (
  `customer_group_id` smallint UNSIGNED NOT NULL auto_increment COMMENT 'Customer Group Id' ,
  `customer_group_code` varchar(32) NOT NULL COMMENT 'Customer Group Code' ,
  `tax_class_id` int UNSIGNED NOT NULL default '0' COMMENT 'Tax Class Id' ,
  PRIMARY KEY (`customer_group_id`)
) COMMENT='Customer Group' ENGINE=innodb charset=utf8 COLLATE=utf8_general_ci

**Comment by ghost** [comment]
![error](https://user-images.githubusercontent.com/17496183/30966142-2b1f16b4-a458-11e7-8283-279e545c8016.jpg)

**Comment by orlangur** [comment]
Not sure what it means. Can you maybe just import an SQL dump of previously working version?

**Comment by ghost** [comment]
yes but i have the same error with command 

sudo cat  var/backups/1506547954_db.sql|mysql -u root magentodb -p

Not easy lol

**Comment by orlangur** [comment]
Try https://stackoverflow.com/questions/15501673/how-to-temporarily-disable-a-foreign-key-constraint-in-mysql, I thought it was needed in Magento 1 only.

**Comment by ghost** [comment]
I have perform a fresh install of magento 2.2 and a fresh empty database.

After, all rollback work. I am on my previous version 2.1.9. I stop to try to update to 2.2. I have worrie to lose all.

All is ok. Thank you for your time.

**Comment by KarlComSe** [comment]
I've got the same issue. I used the web upgrade tool, and as it didn't work, the rollback. Unfortunately, the rollback didn't work, same error. 

Could it be related? https://github.com/magento/magento2/issues/9694 

The solution that worked for you, @achatpc was to make a fresh install and then rollback the backups? Please explain a bit more.

**Comment by arielmorry** [comment]
This error in M2.2 is coming from Magento Social Integration. When trying to update DB the code searches for the (integration) role and ACL but since you haven't setup Magento Social integration this user and role do not exist yet and thus throws an exception (/module-authorization/Model/Acl/AclRetriever.php:88)

So either set it up before using setup:upgrade OR as a workaround you can change:
magento/module-integration/Model/ConfigBasedIntegrationManager.php (processConfigBasedIntegrations method) around line 130

From:
`$originalResources = $this->aclRetriever->getAllowedResourcesByUser(
                        UserContextInterface::USER_TYPE_INTEGRATION,
                        $integration->getId()
                    );`

To:
`$originalResources = [];
                if ($integration->getStatus()) {
                    $originalResources = $this->aclRetriever->getAllowedResourcesByUser(
                        UserContextInterface::USER_TYPE_INTEGRATION,
                        $integration->getId()
                    );
                }`

(sorry, idk how to style the code in this editor)

**Comment by KarlComSe** [comment]
@arielmorry, your proposal seems to solve that specific issue. Thanks.

**Comment by ghost** [comment]
why is this issue closed ? Changing things on magento core does not resolve this?

**Comment by orlangur** [comment]
Hi @xhallix, as you can see this issue was closed by reporter. Please report a new one with exact steps to reproduce (feel free to take them from this issue) if you experience the same issue.

**Comment by sfblaauw** [comment]
+1

**Comment by nickygencs17** [comment]
+2

**Comment by justatom** [comment]
After edited my code with @arielmorry suggestion.
I still got the message "we can't find the role for the user you wanted"
Magento 2.2.2

**Comment by logicallimit** [comment]
I am also getting this error on CENTOS 7.4 when I try to run command 
> php bin/magento setup:upgrade

I get following message:
![cant-find-the-role](https://user-images.githubusercontent.com/7191368/37276772-bee8f7b6-2608-11e8-8cdf-32afc71e4722.png)

I am at Magento 2.2.2 CE. My site is currently hosted at some other host and I am planning it to migrate it to VPS from other host. I copied my current production code to the new host where i am testing the site. When I run upgrade command in my new VPS account, I get this error as shown in attached snapshot. Further, there is no error shown in exception.log . Only debug.log is being updated with some debug information.

I also have the table customer_group in my database. See snapshot below.
![image](https://user-images.githubusercontent.com/7191368/37277087-aff3e26a-2609-11e8-9bf7-efc9f5e02574.png)

Whats going wrong here. Any input on this? 

Thanks

**Comment by nickygencs17** [comment]
Disable the Shopial_Facebook module it is causing your error. 
`bin/magento module:uninstall Shopial_Facebook`

**Comment by Anantkprajapati** [comment]
Thank you i got same issue and after disable Shopial_Facebook module. its working fine

**Comment by earlelnar** [comment]
Thanks disabling  Shopial_Facebook module works great for me.

**Comment by PieterCappelle** [comment]
Can confirm this. This should be fixed...

**Comment by kazajhodo** [comment]
Worked for me as well. Seems trouble at every turn lately with Magento. Not fun.

**Comment by gclift** [comment]
Same here, disabled Shopial_Facebook and we were able to run the setup:upgrade command. We are running Magento CE 2.2.5.

**Comment by gulshan-streammarket** [comment]
Same issue here but i solved this by inserting a new record to table 'authorization_role'.
So executed below query to insert record

`INSERT INTO `<DB_NAME>`.`authorization_role` (`role_id`, `parent_id`, `tree_level`, `sort_order`, `role_type`, `user_id`, `user_type`, `role_name`) VALUES (NULL, '0', '1', '0', 'U', '7', '1', '17');`

Here 7 is the ID of integration. Every-time you run setup:upgrade you will find different integration ID.
