### ISSUE TITLE
2.2-develop: url_rewrite table out of sync with eav attribute url_key

### ISSUE THREAD

**Issue by QwertyZW** [magento/magento2#11102]
When the `url_rewrite` table goes out of sync with a given entity's `url_key` `Magento\CatalogUrlRewrite\Service\V1\StoreViewService::doesEntityHaveOverriddenUrlKeyForStore` Starts returing erroneous results, causing a bug where saving a SEO url on said entity (either programmatically or through the admin backend) would fail silently; The url_rewrite table would never get updated.

This happens because in
`Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator::generateForGlobalScope`
`isOverrideUrlsForStore()` would return `false` because `doesEntityHaveOverriddenUrlKeyForStore` erroneously returns true when a `url_rewrite` record wouldn't actually exist in said table(matching the entity, the store and the key). As a result `updateCategoryUrlForStore` would never get called and the `url_rewrite` table remains stale.

I see this on at least 3 branches
`2.2-develop`
`2.3-develop`
`develop`

**Comment by orlangur** [comment]
> When the `url_rewrite` table goes out of sync with a given entity's `url_key`

Please provide scenario how this can happen and format issue according to https://github.com/magento/magento2/blob/develop/.github/ISSUE_TEMPLATE.md

**Comment by QwertyZW** [comment]
@orlangur  the url_rewrite table was corrupted by an external module

**Comment by orlangur** [comment]
And? Such external module must be fixed then.

> because `doesEntityHaveOverriddenUrlKeyForStore` erroneously returns true when a `url_rewrite` record wouldn't actually exist 

It has nothing to do with `url_rewrite`, it checks EAV attributes table and it is absolutely correct.

Please provide a valid scenario and format issue accordingly. With current explanation it looks like there is nothing to fix in core.

**Comment by QwertyZW** [comment]
>It has nothing to do with url_rewrite, it checks EAV attributes table and it is absolutely correct.

Nope.

`doesEntityHaveOverriddenUrlAttributeForStore`  checks the EAV attributes table `doesEntityHaveOverriddenUrlKeyForStore` simply calls the former

I could have reported `doesEntityHaveOverriddenUrlAttributeForStore` as the root cause of the problem. But I know it is not, because it is absolutely correct. I'm pointing out that `doesEntityHaveOverriddenUrlKeyForStore` might not be

By scenario do you mean something that has to be done through the GUI? Because I can simply truncate `url_rewrite` to recreate what the broken module was doing.

In any case, magento2 was in a state where it reports that a product has been successfully saved when its url_rewrites did not take effect. I saw other parts of the code base that were made to be very defensive, and I figured this part of the code could use being a little more defensive too. 

>And? Such external module must be fixed then.

As a side note, if you'd like me to keep reporting issues as I come accross them, or contribute to magento2 in general, then please try to maintain a professional tone. I understand that not all the issues that I will report will be valid. Nor all the code that I will be contributing will be accepted. The reason why I did not follow the template is because I assumed that it's formatted exclusively for GUI recreatable bugs and not for general code issues.

**Comment by orlangur** [comment]
Scenario is anything you can do programmatically or via GUI. Issue template is mandatory, it is generic enough for any type of issue.

`url_rewrite` table must be always in sync with `url_key` entity attributes. If such integrity is broken it's pretty easy to meet collision in URL rewrites for such entities.

As I said before, buggy module needs to be fixed, database may be either restored from latest backup or you can try some URL Rewrite regenerator at your own risk.
