### ISSUE TITLE
Improvement: Add ability under credit memo to enter value for return to stock instead of checkmark

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1111]
Under order. Invoice. Then credit memo. 

Add ability under credit memo to enter value for return to stock instead of checkmark

Suppose one orders 4 and returns 1

You can refund 1
But not update qty with +1 
(Just yes or no for all)

**Comment by asemenenko** [comment]
@seansan 

I tested the refund feature and if you decided to create credit memo for 1 out of 10 ordered items then Magento adjust inventory by 1 item.

/regards

**Comment by seansan** [comment]
So with the checkmark "return to stock" it returns the QTY mentioned under
"Qty to Refund" back into stock

Situation 1 (return 1 , credit memo 1)
Maybe the description should be improved ... it now reads "Qty to Refund"
but should be "Qty to Refund *and return to stock*" or something like that
Or asterisk under the table to explain ..

But for situation 2 (return 1, credit memo 0)
In this situation where a customer want to exchange a product you return 1
item to stock. But do not credit memo. How is this handled?

Just trying to get it more clear

**Comment by asemenenko** [comment]
@seansan 
To create a return document separately there is a need to have a document that captures this action. For that we have an RMA functionality that is a part of EE.

/regards

**Comment by seansan** [comment]
And this will stay the same in Mage2?? As this is the community (github)
where we add code ... and because it is 2015 ... it might be an idea to
shift this functionality to ALL versions .... RMA is no feature anymore. It
is at the core of every online business ...

**Comment by asemenenko** [comment]
@seansan 

For now i can say that it is not a part of CE. If there will be an update on this - i'll update the issue.

/regards

**Comment by seansan** [comment]
OK, maybe I will open a new issue separately for this ... I think the
community shoulw maybe also speak its voice

**Comment by seansan** [comment]
Will this also become more important for MSI?
