### ISSUE TITLE
magento 2.2 after  update composer can't run Cli

### ISSUE THREAD

**Issue by tomnyson** [magento/magento2#11112]
### Preconditions

1. 
2. 

### Steps to reproduce

1. composer require magento/product-community-edition 2.2 --no-update
2. composer update
3.create file un_mask  in root folder with value 022
3. php bin/magento setup:upgrade

### Expected result

1. [InvalidArgumentException]
  Unable to unserialize value.

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/10257765/30955989-cd4427c0-a45f-11e7-8e02-60f57b43cb3f.png)

**Comment by orlangur** [comment]
> create file u_mask in root folder with value 022

Without such step there will be no error?

**Comment by ghost** [comment]
I have this problem as well. It happens without umask, adding a umask doesn't fix the problem for me.

**Comment by orlangur** [comment]
Do you have any third-party extensions or customizations?

Please check https://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes.html#database-data-format-changes in order to adopt your instance.

**Comment by ghost** [comment]
Thanks for pointing this out. This wasn't what was causing the issue, but this does effect some of my modules.

Solution for my problem was too simple, first run:
`php bin/magento cache:flush`

**Comment by orlangur** [comment]
Oh, this is always first thing to try :) @tomnyson did cache clearing maybe solves your issue as well? Otherwise please confirm the problem not comes from any third-party extension or custom implementation.

**Comment by tomnyson** [comment]
@orlangur  you right. I flushed cache for redis via
redis-cli flushall
my problem  resolved

**Comment by orlangur** [comment]
Ok, thanks for quick response, http://devdocs.magento.com/guides/v2.2/comp-mgr/cli/cli-upgrade.html#upgrade-cli-upgr currently covers only cache stored in file system, probably would be better to replace by `php bin/magento cache:flush`.
