### ISSUE TITLE
Magento 2.2.0 CLI commands not working on PHP 7.1.9

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#11125]
Preconditions

Magento v2.2.0
PHP 7.1.9

Steps to reproduce

1. Update source file with Magento 2.2.0
2. Install PHP 7.1.9 on server
3. Run Magento command to upgrade: php bin/magento setup:upgrade
4. Try other Magento commands: php bin/magento indexer:reindex, php bin/magento cache:flush

Expected Result:
1. System should start upgrading Magento 2.2.0
2. Indexer should reindex

Actual result
1. Nothing happens

![image](https://user-images.githubusercontent.com/8907629/30983763-f53c453c-a450-11e7-8e6a-0789f8b38159.png)

**Comment by orlangur** [comment]
Looks like an issue with your environment.

Try to enable `display_errors` https://github.com/magento/magento2/blob/2.2-develop/app/bootstrap.php#L11 to see what is actually happening.

**Comment by moElwan** [comment]
does other php commands ex.`php -v` gives you a result ?

**Comment by msawyers** [comment]
Thanks @orlangur. The environment was not displaying errors so I was unable to see what was the issue. 
By displaying the error I found issue and was able to fix. Thanks

**Comment by msawyers** [comment]
However upgrade failed with error message: 
Upgrading data.. Warning: SessionHandler::read(): open(tcp://localhost:11211/sess_32ed440814b6bdd8ec417334d5f28ee6, O_RDWR) failed: No such file or directory (2) in dev/vendor/magento/framework/Session/SaveHandler/Native.php on line 22

**Comment by msawyers** [comment]
Workaround at this link did not work: http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_session.html

**Comment by msawyers** [comment]
I did not configure to use memcache. What is cause of this error?

**Comment by msawyers** [comment]
Fixed by commenting out session.save.handler in  memcache.ini

**Comment by msawyers** [comment]
Thanks all

**Comment by msawyers** [comment]
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'ifconfig': The attribute 'ifconfig' is not allowed.
Line: 682

Can you assist with this issue as well?

**Comment by orlangur** [comment]
@msawyers see https://github.com/magento/magento2/issues/11116#issuecomment-332877310, layout declarations shall correspond to XSD schema - most likely such `ifconfig` worked only for `<block` declaration anyway.

Could you please close this issue and report a new one if you meet any Magento bug?
