### ISSUE TITLE
Magento 2.1.9 Configurable Sample Data Does not Install

### ISSUE THREAD

**Issue by rmevans1** [magento/magento2#11124]
### Preconditions

1.  Magento 2.1.9

### Steps to reproduce

1.  Run from magento root
2.  php bin/magento module:enable Magento_ConfigurableSampleData
3.  php bin/magento setup:upgrade

### Expected result

1.  Configurable Sample Data Should Install

### Actual result

1. Installation fails with message Area code not set: Area code must be set before starting a session. Area code is not set

Area code not set: Area code must be set before starting a session.
Exception trace:
 () at /var/www/magento20/vendor/magento/framework/Session/SessionManager.php:175
 Magento\Framework\Session\SessionManager->start() at /var/www/magento20/var/generation/Magento/Backend/Model/Auth/Session/Interceptor.php:167
 Magento\Backend\Model\Auth\Session\Interceptor->start() at /var/www/magento20/vendor/magento/framework/Session/SessionManager.php:130
 Magento\Framework\Session\SessionManager->__construct() at /var/www/magento20/vendor/magento/module-backend/Model/Auth/Session.php:97
 Magento\Backend\Model\Auth\Session->__construct() at /var/www/magento20/var/generation/Magento/Backend/Model/Auth/Session/Interceptor.php:14
 Magento\Backend\Model\Auth\Session\Interceptor->__construct() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:57
 Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:931
 Magento\Setup\Model\Installer->createSchemaDataHandler() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:1245
 Magento\Setup\Model\Installer->getSchemaDataHandler() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:841
 Magento\Setup\Model\Installer->handleDBSchemaData() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:796
 Magento\Setup\Model\Installer->installDataFixtures() at /var/www/magento20/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php:74
 Magento\Setup\Console\Command\UpgradeCommand->execute() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/www/magento20/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/magento20/bin/magento:23

Area Code is not set

Exception trace:
 () at /var/www/magento20/vendor/magento/framework/App/State.php:139
 Magento\Framework\App\State->getAreaCode() at /var/www/magento20/vendor/magento/framework/Session/SessionManager.php:173
 Magento\Framework\Session\SessionManager->start() at /var/www/magento20/var/generation/Magento/Backend/Model/Auth/Session/Interceptor.php:167
 Magento\Backend\Model\Auth\Session\Interceptor->start() at /var/www/magento20/vendor/magento/framework/Session/SessionManager.php:130
 Magento\Framework\Session\SessionManager->__construct() at /var/www/magento20/vendor/magento/module-backend/Model/Auth/Session.php:97
 Magento\Backend\Model\Auth\Session->__construct() at /var/www/magento20/var/generation/Magento/Backend/Model/Auth/Session/Interceptor.php:14
 Magento\Backend\Model\Auth\Session\Interceptor->__construct() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:71
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:126
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/magento20/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/magento20/vendor/magento/framework/ObjectManager/ObjectManager.php:57
 Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:931
 Magento\Setup\Model\Installer->createSchemaDataHandler() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:1245
 Magento\Setup\Model\Installer->getSchemaDataHandler() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:841
 Magento\Setup\Model\Installer->handleDBSchemaData() at /var/www/magento20/setup/src/Magento/Setup/Model/Installer.php:796
 Magento\Setup\Model\Installer->installDataFixtures() at /var/www/magento20/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php:74
 Magento\Setup\Console\Command\UpgradeCommand->execute() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/www/magento20/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /var/www/magento20/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/magento20/bin/magento:23

**Comment by magento-engcom-team** [comment]
@rmevans1, thank you for your report.
module "Magento_ConfigurableSampleData" depends on "Magento_CatalogSampleData" and "Magento_ProductLinksSampleData".
You can try to use the following steps:
1. php bin/magento module:enable Magento_CatalogSampleData Magento_ProductLinksSampleData Magento_ConfigurableSampleData
2. php bin/magento setup:upgrade

and please let us know, if any issues still occur.

**Comment by rmevans1** [comment]
Yes the error still occurs.

**Comment by magento-engcom-team** [comment]
@rmevans1 Thanks for the feedback.
Unfortunately, I could not reproduce the issue as you described it.
Steps I did:
1. Install Magento 2.1.9
2. Copy Magento2 Sample Data into root directory.
3. Link Sample Data ex: php -f magento2-sample-data/dev/tools/build-sample-data.php -- --command link --ce-source /path_to_root_magento_directory/ --exclude true
4. Enable modules: php bin/magento module:enable Magento_CatalogSampleData Magento_ProductLinksSampleData Magento_ConfigurableSampleData
5. php bin/magento setup:upgrade
No issues occur.

**Comment by magento-engcom-team** [comment]
Hi @rmevans1 we are closing the issue due to inactivity. If you would like to update the issue, please reopen the issue

**Comment by magento-engcom-team** [comment]
@rmevans1, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
