### ISSUE TITLE
Magento 2.2 installation stuck at 71%

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#11122]
hello~
I installed many times but still installation stuck at 71%...have some one can help me?please and thank you~
and if dont install SampleData.ver will be Installation is incomplete. 
and i using Web hosting so i cant use composer
 
Current PHP version:  7.1
allow_url_fopen On
date.timezone UTC
display_errors Off
error_reporting E_ALL
file_uploads On
include_path .:/opt/alt/php71/usr/share/pear
log_errors On
mail.force_extra_parameters no value
max_execution_time 18000
max_input_time -1
max_input_vars 8000
memory_limit 768M
open_basedir no value
post_max_size 128M
session.save_path /tmp
short_open_tag On
upload_max_filesize 1G

**Comment by dmanners** [comment]
Hi @rigu12, thank you for reporting this issue. There is a couple of bits of information that are needed to reproduce the issue before it can be processed. Have a look at the [guidelines for reporting issues](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). It would be good to know if there was anything in you log files that might help.

**Comment by bangnguyen47** [comment]
Hi @rigu12 
Can you show "max_execution_time" config?
Or you can install via command line: setup:install
eg:
```
php bin/magento setup:install --base-url=BASE_URL --backend-frontname=BACKEND_ADMIN --db-host=HOST --db-name=DB_NAME --db-user=DB_USER --db-password=DB_PASS --admin-firstname=ADMIN_FIRSTNAME --admin-lastname=ADMIN_LASTNAME --admin-email=ADMIN_EMAIL --admin-user=ADMIN_USER --admin-password=ADMIN_PASS
```

**Comment by magento-engcom-team** [comment]
@rigu12, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0
