### ISSUE TITLE
Discount code not working

### ISSUE THREAD

**Issue by rmevans1** [magento/magento2#11128]
### Preconditions

1.  Magento 2.1.9

### Steps to reproduce

1.  Create an attribute
2.  Create product with attribute
3.  Create coupon code with following setup
![discount](https://user-images.githubusercontent.com/466178/30990535-af38c7f8-a46f-11e7-9ac3-bdb79fe6c07f.png)

### Expected result

1. Discount should give 10% off

### Actual result

1. No discount given.
2. If I use any of the two sets of conditions separately it works. But if I put both sets of conditions together it doesn't

**Comment by magento-engcom-team** [comment]
@rmevans1, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
