### ISSUE TITLE
Class Psr\Log\LoggerInterface does not exist

### ISSUE THREAD

**Issue by groggu** [magento/magento2#1112]
After pull to existing magento2 instance, I'm getting the error 

a:4:{i:0;s:44:"Class Psr\Log\LoggerInterface does not exist";i:1;s:5201:"#0 /var/www/html/mage2/gcc/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConst
ructor('Magento\\Store\\M...')

**Comment by maksek** [comment]
Hi @groggu, please run composer install on root folder, and clean cache.

**Comment by groggu** [comment]
I ran composer update and now I get a report magento telling me -

a:4:{i:0;s:11961:"Please update your database: Run "php -f index.php update" from the Magento root/setup directory.
The following modules are outdated:
Magento_Core schema: current version - none, required version - 2.0.1
Magento_Core data: current version - none, required version - 2.0.1
(etc etc etc)

When I run the suggested update however, it bombs out with an exception trying to recreate the core_session table -

Zend_Db_Statement_Exception
 SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'core_session' already exists, query was: CREATE TABLE `core_session` (

Looks like I'll just have to scrap the db and reinstall?

**Comment by mazhalai** [comment]
@groggu Issue mentioned in your 2nd comment has been fixed in the latest release 0.74.0-beta1 (Dev RC)
For Internal tracking MAGETWO-35266.

**Comment by vpelipenko** [comment]
@groggu, did you have a chance to verify this issue again on your Magento instance? It was fixed in 0.74.0-beta1.

**Comment by groggu** [comment]
I have not had the time to upgrade the version of PHP on that server yet, so I can’t pull the latest code. Will try to get some extra non-project time allocated after Imagine.

Greg

**Comment by vpelipenko** [comment]
Ok. Thanks, we'll wait for update from you.

**Comment by vpelipenko** [comment]
Internal issue is fixed and closed. @groggu, if you still have the same problem on the latest version, please, let us know and also feel free to reopen this issue.

**Comment by baltechies** [comment]
Hi,
 I have downloaded and installed the magento 2.1.5 by downloading zip file from magento website. But I am facing same issue. 

Exception message: Class Psr\Logger\LoggerInterface does not exist

I did not run any command like "php -f index.php update". Is there a need to run any command for stable downloaded version as well?

**Comment by germaike** [comment]
Hi,

I got this error while running setup:di:compile to go to production mode.
Any solutions for this issue? I'm running a 2.1.7 instance.

**Comment by iambaljitdhanoa** [comment]
Hello
I got this error while running setup:di: compile to go to production mode

Class Psr\Logger\LoggerInterface does not exist 

We are using Magento 2.3 please let me know anybody have solutions
