### ISSUE TITLE
Product Repeat Isuue after filter on category listing page.

### ISSUE THREAD

**Issue by mayankzalavadia** [magento/magento2#11139]
Product Repeat Issues after apply price filter on category listing page. Same products display on next page. Also sometimes it gives me random products. 
### Preconditions

1. Magento 2.1.7
2. Magento 2.1.8
3. Magento 2.1.9
4. Magento 2.2.0

### Steps to reproduce

1. Install Magento with Sample Data.
2. Go to Man > Tops Category
3. Click on Price filter and try to filter which shows a maximum product.
4. Click on the second page on bottom pagination. use CLT + Click
5. Try 2 to 4 time with the same process. 

### Expected result

1. Product Should not be repeated on category page when we filter.

### Actual result

1. For your better understanding, I have attached a video in a zip file.

[Product_Repeat_Issue_After_Filter.mp4.zip](https://github.com/magento/magento2/files/1344362/Product_Repeat_Issue_After_Filter.mp4.zip)

**Comment by DeepPopat** [comment]
I have also faced the same issue in my two sites. But when I enable  `"Use Flat Catalog Product" = YES `then it shows me perfect result.

**Comment by mayankzalavadia** [comment]
Yes, I know about that. But I think is not the proper solution. It should be work when `"Use Flat Catalog Product" = NO`.

**Comment by magento-engcom-team** [comment]
@mayankzalavadia, thank you for your report.
We've created internal ticket(s) MAGETWO-80457 to track progress on the issue.

**Comment by mayankzalavadia** [comment]
I have a solution for this issue and I would like to work on this issues.

**Comment by mayankzalavadia** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80828

**Comment by okorshenko** [comment]
The issue has neeb fixed and delivered to 2.2-develop branch
