### ISSUE TITLE
Catch storage management cannot disabled????

### ISSUE THREAD

**Issue by sachinsachin** [magento/magento2#1113]
I want to disable all cache storage management in Magento but when trying using the Admin Panel Cache Management nothing is disabled.

Is there another way to disable the cache storage management besides the Admin panel?

**Comment by sachinsachin** [comment]
![img_20150320_192515](https://cloud.githubusercontent.com/assets/11334466/6752767/2c3142f0-cf37-11e4-800d-f52af63e7e38.jpg)
After select all... i go to disable option and click submit.. but these are not disabled.

**Comment by maksek** [comment]
@sachinsachin the screenshot for Magento 1. Do you have any questions for Magento2? IF not we are going to close the issue. 
Please stop post not related questions in the repository.
