### ISSUE TITLE
Layered Navigation Supports Multi-Select Within Field Group

### ISSUE THREAD

**Issue by choukalos** [magento/magento2#11130]
### Card
**As a** customer I can select multiple filters within a filter group **so that** I can more quickly filter my search results down for price or preferred colors or other such criteria to quickly find what I'm looking to purchase.

### Notes / Details
- For performance testing would suggest use of B2C medium profile; performant defined as no more then a 3% degradation
- Example of multi-select mockup
<img width="149" alt="screen shot 2017-09-28 at 4 35 08 pm" src="https://user-images.githubusercontent.com/145978/30991537-0ef2c5b8-a46b-11e7-80d6-705f7a6af6ba.png"> 

- Selections within filter groups are treated as an 'or' 
- If easier/improves performance # results per filter selection can be dropped (similar to Amazon behavior)

### Acceptance Criteria (AC)

1.  Layered navigation supports selecting multiple filters (treated as an or) within a filter group
2.  Performance of un-cached category pages & search results (initial render and filter action) and pages with this change should be optimized for performance

**Comment by magento-engcom-team** [comment]
Hi @choukalos. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/20
