### ISSUE TITLE
Hide Tax row from cart summary

### ISSUE THREAD

**Issue by jayachandrann** [magento/magento2#11135]
From Shopping cart & Check out pages, I want to hide Tax row printed with the tax calculations.

I only want to hide the calculated tax row from the entire website during checkout, while the tax will be shown in the invoice printed and sent to the customer during despatch of product.

Which means complete tax calculation should be working on the website, but the same should not be displayed to the customer on the frontend through out the checkout process.

How do I achieve this?

**Comment by dmanners** [comment]
Hi @jayachandran1974 GitHub is used for raising issues and providing code changes to Magento. If you are looking for assistance with coding I can highly recommend [Magento Stackexchange](https://magento.stackexchange.com/) or [the Magento Forums](https://community.magento.com). Both these portals should be a great place to start with coding questions.
