### ISSUE TITLE
Rest API return: Consumer is not authorized to access %resources

### ISSUE THREAD

**Issue by LuisFReis** [magento/magento2#11145]
I have a local installation of Magento 2 where everything is configured and all the API works fine

I'm doing an app for a client also with Magento 2
Done the same confugurations
And the site always returns
      Consumer is not authorized to access %resources
There is anyconfiguration in Magento that we need to configure?

If we give the Guest Access, everything works

We'checked the access keys and every are correct

We use 
ConsumerKey
ConsumerSecret
AccessToken
AccessTokenSecret

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. Also, googling observed error is usually helpful.

Seems like http://devdocs.magento.com/guides/v2.2/get-started/authentication/gs-authentication-token.html should help.
