### ISSUE TITLE
Errormessage when saving Catalog SEO settings for Category URL Suffix

### ISSUE THREAD

**Issue by Boumii** [magento/magento2#11142]
### Preconditions
Magento CE 2.1.9 / Ubuntu 16.04 / Apache 2.4.18 / MySQL Ver 14.14 Distrib 5.7.19 / PHP 7.0.22

### Steps to reproduce
1. Go to Shop->Configuration->Catalog->Catalog->Searchengineoptimisation
2. Remove Checkbox from Category-URL-Suffix
3. Change the default value ".html" to "" (empty)
4. Klick save Configuration

### Expected result
1. Saved Configuration, Category-URL shouldnt have a suffix anymore.

### Actual result
Error: Beim Speichern der Konfiguration ist ein Fehler aufgetreten. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'kontakt-1' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID', query was: UPDATE `mgt_url_rewrite` SET `request_path` = ? WHERE (`url_rewrite_id` = 1551)

### Other things
When using a trailing "/" as suffix, it works as aspected. Also other values seems to work, only "" (empty) didnt work.

We tried CE 2.2. but addons keeping us form updating live server, right now. But also on CE 2.2. on our dev-box we cannot change the category-URL-suffix to "" (empty).

**Comment by renttek** [comment]
Hi,

I just tried to reproduce this issue with the latest develop version, but can't really  get it to "crash".
Only way I could reproduce this, is when i create another entity (for example "cms-page") with the same url-key.
Is there any other entity with the url-key "kontakt-1" or "kontakt" for **the same store** in your database?

The error message shows, that the conflicting key is "URL_REWRITE_REQUEST_PATH_STORE_ID" which only checks the fields "request_path" and "store_id".

I will try to reproduce this on other versions tomorrow.

**Comment by magento-engcom-team** [comment]
@Boumii, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by joekersh** [comment]
For anyone getting this, you've probably got a CMS page or something with the same url key as one of the categories without the suffix.

For example, a CMS page called brands and a category called brands.html will cause the above error becuase once the suffix is gone they will be the same
