### ISSUE TITLE
magmi - updating configurable product and getting error

### ISSUE THREAD

**Issue by ayoung530** [magento/magento2#11149]
### Preconditions
Using Magento version 1.9.2.2
Using MAGMI v0.7.22
1.  I have existing configurable products linked to simple products
2.  These were uploaded in the past with no problem
3.  I used the attribute "simple_attribute_pricing"  to input prices for the simple products that would appear under that page "Associated Products" as a fixed step up in price.    an example of the original syntax is:      size::Medium:10;Large:20
4.  Now if i try and change this - lets say prices need to change - i now need the step-up in prices to be 15 and 25, and if i use the syntax:       size::Medium:15;Large:25        nothing happens - the original values of 10 and 20 are still there.   
5.  In addition i am getting an error in magmi when i try to upload just the configurable products.  the error message is  "Configurable Item processor v1.3.7a - No configurable attributes found for configurable sku: xxxxxxxxxxx cannot link simples."
6.  i am confused about what to do.  i dont need to relink any simples.  I just want to change something within the configurable item.

Any help whatsoever would be hugely appreciated.

**Comment by orlangur** [comment]
This is Magento 2 repository, not Magento 1.

Problems with MAGMI should be reported to MAGMI vendor anyway. Looks like https://understandinge.com/forum/all-things-coding/magmi-and-configurable-products/#p6342 is something you was looking for.
