### ISSUE TITLE
GA bug

### ISSUE THREAD

**Issue by Mackovey** [magento/magento2#1114]
![m1527](https://cloud.githubusercontent.com/assets/813985/6764158/204cdc6e-cfab-11e4-8f08-6e90474ca37c.png)

PHP/Magento interprets string `//www.google....` as comment

![m1525](https://cloud.githubusercontent.com/assets/813985/6764157/1aac0488-cfab-11e4-9e6f-cf6897d46124.png)

**Comment by vpelipenko** [comment]
Issue is acknowledged. Internal ticket MAGETWO-35392.

**Comment by vpelipenko** [comment]
@Mackovey, fix for this issue is already available. Please, check it again,
