### ISSUE TITLE
nginx.sample.conf missing heath_check.php?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#11157]
I've updated to 2.2, and regularly get the error below in my nginx error logs. I believe it's because health_check which is used in varnish config is not catered for in the nginx sample vhost configuration

### Preconditions
1. Magento 2.2.0
2. nginx 1.12.1
3. OS X 10.12.6

### Steps to reproduce
1. Update to Magento 2.2
2. View home page of site

### Expected result
1. No errors

### Actual result
nginx error log
1. 2017/09/30 10:42:59 [error] 7848#0: *115 open() "/usr/local/Cellar/nginx/1.12.1/html/pub/health_check.php" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /pub/health_check.php HTTP/1.1", host: "127.0.0.1"

**Comment by dmanners** [comment]
Thanks for this @craigcarnell I think it would make sense to add the health_check.php into the nginx.conf.sample file. Would you be interested in providing a PR for such a fix?

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release soon

**Comment by magento-team** [comment]
Hi @craigcarnell. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1284 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
