### ISSUE TITLE
Group Products not showing in Layered Navigation Results

### ISSUE THREAD

**Issue by palo** [magento/magento2#11159]
In front end, when selecting an attribute to filter, grouped products are not listed.
The Layered Navigation sidebar shows the right amount of products, but the listing in incomplete. 

In my store all products are grouped there are no visible simple products. All filterable attributes are showing in the sidebar. The product results amount in the sidebar is correct. Filtered result is showing the notice no matching products found.

## Preconditions

Magento 2.1.9 

## Steps to reproduce:
1. Create a grouped product containing products filterable by attribute.

## Expected result
1. The product is listed in filtered results matching child product attribute

## Actual result
1. Product not showing in filtered results although the count in sidebar is correct 
![capturar](https://user-images.githubusercontent.com/583644/31084958-ba75ad90-a78d-11e7-9140-e110b547ba43.JPG)
![capturar2](https://user-images.githubusercontent.com/583644/31084961-c0aa9518-a78d-11e7-8320-330aa0f30b94.JPG)

**Comment by magento-engcom-team** [comment]
@palo I cannot reproduce this issue. 
Run `php bin/magento index:reindex` may be help you

**Comment by palo** [comment]
@magento-engcom-team already tried that. Also: 

- Updated from 2.1.6 to 2.1.9.
- Created an exact copy in local machine. Disabled all third party extensions and changed to luma.
- Created new products for testing
- Changed stock management on and off 

I cant reproduce this issue in a fresh install. 
Nothing relevant in log.

We didnt notice when this issue started, maybe previous version update as this are the major changes in code in recent past.

How can i debug this?

**Comment by magento-engcom-team** [comment]
@palo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
