### ISSUE TITLE
Magento 2.2.0 Pages showing error: Data key is missing: code-entity

### ISSUE THREAD

**Issue by kfaer** [magento/magento2#11163]
Not able to create or edit any page only showing this message:

Data key is missing: code-entity

Magento 2.2.0

![image](https://user-images.githubusercontent.com/8407530/31048550-4fa0447a-a630-11e7-8a93-deabe2b47867.png)

**Comment by kfaer** [comment]
Is it known issue ?
any update
@magento-engcom-team

**Comment by magento-engcom-team** [comment]
Hi @kfaer 
This is not a known issue.
We have checked this page with the clean installation of `2.2.0` and did not get same result as you did.
<img width="1434" alt="screen shot 2017-10-01 at 12 55 23" src="https://user-images.githubusercontent.com/31669971/31053530-f7af2b00-a6a7-11e7-8125-ffe52f5f0594.png">
Please consider checking again with a clean install and file a report according to the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if the issue persists. 
Thank you

**Comment by raceves2005** [comment]
I have the Exact same problem and its driving me INSANE! i also have another problem, when i try to add new images on slider block it saves it as an External Source as listed below, the first line calling for external source is a new image, the "wysiwyg/vorsteiner-Slider.jpg" is prior to Magento 2.2, we already reset permissions. I was running magento 2.1.9, We are also getting many "There has been an processing your request" When i try to view a product, save a product, etc... but its not consistent.


![image](https://user-images.githubusercontent.com/29742107/31056788-9a772854-a68c-11e7-838a-8703aa5cdaa3.png)

**Comment by magento-engcom-team** [comment]
@raceves2005 
Unfortunately we can not help as long as we can not reproduce the issue on our side. 
Please follow the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and describe how your store is configured.

Thank you.

**Comment by heyepic** [comment]
Also have the same issue with creating pages after upgraded to 2.2.
`Data key is missing: code-entity`
When you click create page, that shows. Listing current pages works fine, but when adding, you come to page with just that.
![attach](https://user-images.githubusercontent.com/12517908/31059393-0a6ebebc-a6c7-11e7-98e8-24f698d565a0.jpg)

Did general post-upgraded steps including setting proper permissions.

**Preconditions**
Upgraded from 2.1.5 to 2.2.
Standard PHP7/MySQL running on CentOS.

**Steps to reproduce**
Load admin, go to pages, click Add page button.

If you click save and continue OR save page, it'll bounce me back to Orders in admin. Going back to pages, no page has been added, click add page, repeats. Editing existing pages yields the same issue.

Going into system.log, this line is added:
`[2017-10-01 21:48:34] main.CRITICAL: Data key is missing: code-entity [] []`

**Comment by kfaer** [comment]
**Preconditions**
Upgraded from 2.1.9 to 2.2.
Standard PHP7/MySQL running on Ubuntu 16.04.

**Steps to reproduce**
Load admin, go to pages, click Add page button.
@magento-engcom-team

**Comment by Sharlyll** [comment]
Experiencing the same issue. 

Error: Data key missing: code entity
When creating a New page or editing an exisiting one. 

Magento 2.2 Clean install
Running on standard PHP7/MYSQL
Shared server

**Comment by kfaer** [comment]
@antboiko It seems it is an issue with the new version 2.2.0, please advise.

**Comment by magento-engcom-team** [comment]
@Sharlyll 
> Magento 2.2 Clean install

What we have tried:
* Install `2.2.0 Open Source`
* Navigate to the admin area
* **Content** > **Pages** > **Add New Page**
* ✅ New Page Form is rendered

Please let us know if you have done any additional configuration on your store.

@kfaer It is hardly possible to advice when issue can not be replicated.

**Comment by heyepic** [comment]
If you'd like access to my server, I'd be happy to provide it.

There are also others with the same issue reporting on stackexchange and magento forums.

There was no other configuration on my end - simply used the web setup wizard to initiate the upgrade to 2.2 in the backend. Successfully completed, did permissions via SSH, and then couldn't create/edit pages. Unrelated, but I did have to give 777 to /generated due to admin errors.

**Comment by Sharlyll** [comment]
@magento-engcom-team  Except for putting in my store info in the settings, there is no extension installed nor is there any configurations.

**Comment by Tomasz-Silpion** [comment]
Issue seems to be repeatable on any Magento 2.2 store but requires all google/analytics core_config_data values set to be true (google/analytics/experiments).

Just check how it influences the:

Magento\GoogleOptimizer\Model\Plugin\Cms\Page\DataProvider class, afterPrepareMeta method $result['page_view_optimization']['arguments']['data']['disabled'] boolean.

**Comment by kfaer** [comment]
Yes google analytic is enabled not able to create new pages.

specifically the option: Enable Content Experiments

**Comment by magento-engcom-team** [comment]
@Tomasz-Silpion Thank you for the Pull Request.

**Comment by sarah-magentech** [comment]
Let's disable **Google Analytic** in the **SALES** tab, you will be able to edit page. For more information, please check this [blog post](https://www.magentech.com/case-studies/item/789-how-to-fix-magento-220-pages-showing-error) :)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80829

**Comment by magento-team** [comment]
Hi @kfaer. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1282 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
