### ISSUE TITLE
Incorrect use of implode()

### ISSUE THREAD

**Issue by Michal-sk** [magento/magento2#1116]
In `magento2/app/code/Magento/Tax/Setup/InstallData.php` on line `76` there is a wrong use of `implode()`

```php
'apply_to' => implode($taxSetup->getTaxableItems(), ',')
```

it should be `$glue, $pieces`.

**Comment by kandy** [comment]
> implode() can, for historical reasons, accept its parameters in either order. For consistency with explode(), however, it may be less confusing to use the documented order of arguments.
http://php.net/manual/en/function.implode.php

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-35411

**Comment by vpelipenko** [comment]
@Michal-sk, fix for this issue is available in public repository after recent update. Please, check it.
