### ISSUE TITLE
download counter not shwon

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#11177]
### Preconditions

1. M2 2.1.9
2. PHP 7.0.22

### Steps to reproduce

1. go to order
2. view the download product order
3. the download product is shown but not the counter

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

![image](https://user-images.githubusercontent.com/31250340/31069850-71d43e8c-a75e-11e7-9712-d4c65dd86408.png)

**Comment by Olek89** [comment]
in some products it is shown:
![image](https://user-images.githubusercontent.com/31250340/31069892-a7d7e79a-a75e-11e7-89fc-f672e18b188b.png)

**Comment by magento-engcom-team** [comment]
@Olek89, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by Olek89** [comment]
could it be a problem of configurable products?
