### ISSUE TITLE
Cart Sales Rule with negated condition over special_price does not work for products without a special price attribute

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#11178]
### Preconditions
1. magento 2.1.7
2. php 7.1.10
3. mariadb 10.1.24

### Steps to reproduce
0. setup vanilla 2.2 with demodata (or use a similar existing store)
1. enable the `special_pricee` for promo rule conditions: 
   1. Stores > Attributes > Product
   2. search for and edit `special_price`
   3. Storefront Properties: Use for Promo Rule Conditions: Yes
   4. save
2. create new cart sales rule:
   1. Marketing > Cart Price Rules
   2.  Add New Rule:
       1. Rule name = "Special Price Test"
       2. Website: select all
       3. Customer Groups: select all
       4. Coupon: "Specific Coupon"
       5. Coupon Code: "special"
       6. Actions: Discount Amount: "10"
       7. Actions: Apply the rule only to cart items matching the following conditions: "if **ALL** of these conditions are **FALSE**": "Special Price **greater than 0.01**"
       8. leave all other fields to their defaults and save
3. in the front end, add a product to the cart which does not have a special price. f.e. in the demodata: SKU `24-MB02`
4. "View and Edit Cart" > "Apply Discount Code": `special`

### Expected result
1. the coupon is accepted with the message `You used coupon code "special".`
2. a discount is applied

### Actual result
1. the coupon is not accepted with the message `The coupon code "special" is not valid.`
2. no discount is applied

the intention with the above mentioned sales rule is to exclude already discounted products from fruther discounting via a coupon code. an unrelated, similar cart price rule that gives already discounted products further discounts (i.e. "if **ALL** of these conditions are **TRUE**": "Special Price **greater than 1.00**") works just fine. this seems to indicate that the condition does not work due to the fact that an undiscounted product does not have the EAV attribute `special_price` at all, even tho that should be covered by the negated rule "... are FALSE".

**Comment by heldchen** [comment]
sorry, closing this ticket as it seems to be fixed in 2.2.0

**Comment by EvaldasDau** [comment]
Magento 2.2.1 here. Still doesn't work like described in your original post...

**Comment by heldchen** [comment]
agreed, does not work in 2.2.2 for **configurable** products. reopened.

**Comment by ktruehl** [comment]
This problem only occurs for associated products of configurable products. More specifically, the problem manifests itself in the rule validation mechanism. For configurable products both the associated and the parent product is handed to the `validate()` method in `Magento\Rule\Model\Condition\Product\AbstractProduct`. But for special prices the `special_price` attribute is not defined. So in `validate()` in `Magento\Rule\Model\Condition\AbstractCondition` the call `$model->getData($this->getAttribute())` will always return null for the parent product and thus validate to `false`. Thus price rule conditions using the `special_price` attribute will always validate to `false` for configurable products.

We have created a quickfix for this issue: [bugfix-GH11178-configurable_product_sales_rule_special_price_validation.2018-02-06.diff.zip](https://github.com/magento/magento2/files/1702785/bugfix-GH11178-configurable_product_sales_rule_special_price_validation.2018-02-06.diff.zip). It is only that, i.e. a quickfix. A more comprehensive fix would be to check `Magento\Rule\Model\Condition\Product\AbstractProduct::validate()` whether an attribute is defined at all for a specific product, and if not, to validate to `true`.

**Comment by magento-engcom-team** [comment]
@heldchen , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@heldchen, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by lano-vargas** [comment]
Same here version 2.2.2 
If I have 2 product in my cart one with special price a one without.

The coupon code discount is applying on both products when it should only be discounted for the product without special price!

thanks

**Comment by ayjods** [comment]
Same here version 2.2.5
If I have 2 product in my cart one with special price a one without.

The coupon code discount is applying on both products when it should only be discounted for the product without special price!

thanks
