### ISSUE TITLE
Problem with Minicart display when Onepage checkout is disabled

### ISSUE THREAD

**Issue by Kimmagento** [magento/magento2#11172]
Preconditions
1. Magento 2.1.9

Steps to reproduce
1. Go to Stores - Configuration - Sales- Checkout
2. First option on that page: Enable onepage checkout: set to 'NO'
3. Go to website and add 2 products to cart

Expected result
1. Regular minicart should show but without the 'proceed to checkout' button. 

Actual result
1. Minicart is sort of scrambled, impossible to read product names. See screenshot. 

![schermafbeelding 2017-10-01 om 18 35 47](https://user-images.githubusercontent.com/32435422/31056802-300a2538-a6d8-11e7-8636-d320d959adc2.png)
![schermafbeelding 2017-10-01 om 18 35 35](https://user-images.githubusercontent.com/32435422/31056803-300c8828-a6d8-11e7-8f50-b1df1b66b8c2.png)

**Comment by magento-engcom-team** [comment]
@Kimmagento, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
