### ISSUE TITLE
Quantity Condition not shown in Widget

### ISSUE THREAD

**Issue by joinso** [magento/magento2#11187]
### Preconditions:
1. Magento CE 2.2.0
2. PHP 7.1.7
3.- MySQL : Ver 14.14 Distrib 5.5.57, for Linux (x86_64) using readline 5.1

### Steps to reproduce:
1. In Content, in any page edit or add a new page.
2. Add a Widget of type "Catalog Product List".

### Actual result
1. In Conditions , "Quantity" Filter is not shown.

### Expected result
1. "Quantity" filter is shown

I try this in another site and server with same result.

Any idea, why "Quantity" dissapear?

Regards,
Jordi
JOINSO

**Comment by magento-engcom-team** [comment]
@joinso, thank you for your report.
We've created internal ticket(s) MAGETWO-80721 to track progress on the issue.

**Comment by alen9788** [comment]
We are not able to choose any specific products for any kind of widget option or any display at CE2.2



![choose](https://user-images.githubusercontent.com/20162144/32128980-45ea9846-bbb5-11e7-86d3-8679bcc9181a.jpg)

**Comment by mitalikundale** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@mitalikundale thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mitalikundale** [comment]
I cannot see the quantity filter on 2.3-develop branch.

**Comment by mitalikundale** [comment]
Hello, I have check this issue. The 'quantity_and_stock_status' attribute is added in 'excludedAttributes' in di.xml of CatalogWidget module. If we remove it from excluded attributes then it will show in condition on catalog product list widget. But this does not displaying the product list widget frontend.

Please verify from core magento team that why this attribute is excluded from widget conditions rule.

**Comment by magento-engcom-team** [comment]
@joinso, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
