### ISSUE TITLE
Installation issue at Module 'Magento_Search'.

### ISSUE THREAD

**Issue by rvpatel** [magento/magento2#1118]
When i have install magento2 at this step generate error again and again.

![Image of Yaktocat](http://s18.postimg.org/ml1a25xl5/error1.png)

**Comment by adzminz** [comment]
Have you tried dropping the existing database and create a new one?

**Comment by rvpatel** [comment]
I have drop a database and manage setup again so why display error table and view exist at Module 'Magento_Customer'

Module 'Magento_Customer':
Installing schema.. 
[ERROR] exception 'PDOException' with message 'SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'customer_entity' already exists'

Please fix how can we easy setup without any bug.

**Comment by buskamuza** [comment]
Hi @rvpatel , 
1. could you try to run `php setup/index.php uninstall` command from command line first and then try the installation again? If you don't want to use command line, do the following:
1.1. Drop the DB and create new empty one
1.2. Remove everything, except, `.htaccess` from `var` folder 
2. During installation, do you re-try it or go back between pages or refresh the page?

**Comment by vpelipenko** [comment]
@rvpatel, any news about this issue?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor. Issue is not reproduced internally.
