### ISSUE TITLE
M2.1.9 : Possible bug with FPT 'Include in Subtotal'

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#11188]
I guess it's a bug or I'm misunderstanding what the option is for, but: when I configure my FPT settings, it doesn't seem to make a difference if I set 'Include in Subtotal' to 'Yes' or 'No'.

I have a product that has FPT, but the subtotal in the cart row differs from that in the information block. For example:

<img width="451" alt="screen shot 2017-10-03 at 10 55 08 am" src="https://user-images.githubusercontent.com/346681/31117224-61f9d91a-a829-11e7-9420-868e1f1d1922.png">

As you can see, my subtotal in my cart is 4.62 with 0.20 FPT, but the information block shows 4.82 as subtotal. This is rather confusing as you might guess. I though I could fix this by setting the 'Include in Subtotal'-setting to 'No', but it still shows the same result. Even after updating or adding new products to the cart.

So is this a bug or am I not seeing something here?

### Preconditions

1. Magento 2.1.9

### Steps to reproduce

1. Create a product with FPT and add it to the cart
2. Catalog prices are including tax
3. All prices are set to display incl. tax
4. FPT display prices are set as excluding fpt, except for the cart.
5. Apply Tax to FPT is set to 'No'
6. Include in subtotal can be either set to 'Yes' or 'No'

### Expected result

1. When 'include in subtotal' is set to 'no' the FPT should not be calculated in the subtotal.

### Actual result

1. When 'include in subtotal' is set to 'no' the FPT is calculated in the subtotal.

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.9, 2.1.10, 2.2.1
