### ISSUE TITLE
Element 'script': This element is not expected after magento upgrade (when in developer mode)

### ISSUE THREAD

**Issue by katculbert** [magento/magento2#11194]
**Preconditions**
Git 2.14.1
Apache 2.4.27
Memcached 1.5.1
MySQL 5.7.19
OpenSSL 1.0.2l
PHP 7.0.23
phpMyAdmin 4.7.4
SQLite 3.7.15.1
Varnish 4.1.0

**Steps to reproduce**
Upgrade Magento 2.2.0 from Magento 2.1.9
Flush magento cache
Ensure magento is in developer mode
After upgrading, navigate to website 

**Expected result**
Website homepage should display (as per before upgrade)

**Actual result**
error page with the following
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'script': This element is not expected.
Line: 38

Anyone else having this problem and know how I can resolve it?

Thanks in advance!

**Comment by katculbert** [comment]
Here is a screenshot

<img width="1304" alt="screen shot 2017-10-03 at 14 33 40" src="https://user-images.githubusercontent.com/10037805/31127856-f2332572-a847-11e7-8632-208130009fbd.png">

**Comment by magento-engcom-team** [comment]
@katculbert This looks like a problem with one of the installed extensions. Please try with the clean Magento installation.

**Comment by katculbert** [comment]
Sorry - you want me to cleanly install magento or there is a way to clean my magento install? This was a production website as when I did it in test it worked fine.

**Comment by magento-engcom-team** [comment]
@katculbert We suggest trying with the clean magento installation without third-party extensions to ensure that error comes from the extension.

**Comment by katculbert** [comment]
I only have the one extension - MageFan Blog and I have updated that to be the latest which is compatible in theory with Magento 2.2. I can try a new install to see if I can escape this issue

**Comment by orlangur** [comment]
> Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'script': This element is not expected.

Looks like some of your layout XML does not pass XSD schema validation anymore. Just identify which one and fix it.

**Comment by katculbert** [comment]
Thank you for your help :) 

I tried to update the extension afterwards to resolve this. When this didn't work - i created a fresh install rolling back to previous backups (so to version 2.1.8) and this time updated the extension at the same time as upgrading magento (to v2.1.9) and it worked.

Shall try to upgrade to 2.2 another day when I'm less scared!!

**Comment by xpoback** [comment]
@orlangur @magento-engcom-team
There's no mention on[ this page ](http://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes.html) neither on [this page ](http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html) that any XSD schema has changed and it can have adverse effects.
So it would be good to still consider this an issue, even if this is a **documentation issue**

**Comment by orlangur** [comment]
@xpoback as far as we identified in previous similar bug reports XSD schema really didn't change (or didn't change much). Just somehow validation didn't work properly before.

Do agree that it would be nice to have some FAQ or recipes section in update guide. Documentation issues should be reported in https://github.com/magento/devdocs.
