### ISSUE TITLE
After upgrading magento 2.1.9 to magento 2.2.0, Admin Stores Developer not coming

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#11191]
### Preconditions
1.  Upgrade Magento 2.2.0 from Magento 2.1.9
2.  Flush magento cache

### Steps to reproduce

1. After upgrading, Stores->Configuration->Advanced
2. 
3. 

### Expected result

1. Advanced,Developer option should be available

### Actual result

1. Advanced, Developer options not available
![system](https://user-images.githubusercontent.com/16077771/31123452-a524b05a-a85d-11e7-8e0c-4f368f155d30.png)

**Comment by orlangur** [comment]
Please check https://magento.stackexchange.com/questions/195239/magento-2-2-0-missing-admin-developer-configuration. Developer section should only be available in developer mode.

**Comment by okorshenko** [comment]
Closing as non issue

**Comment by lingwooc** [comment]
Thanks for only making this only available in painfully slow mode for no good reason.

**Comment by timbaker1991** [comment]
This feels ill thought out - how do we choose what gets bundled or merged (due to dependencies we can only have one or the other - this applies in _production_ too)?

**Comment by romantomchak** [comment]
Hi @orlangur ,

if Magento disables the Developer section in the production mode, how can we enable/disable for example js bundling, because these configuration are working only in production mode (http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/js-bundling.html#enable-javascript-bundling)

**Comment by franciskim** [comment]
_no spamming, please_

**Comment by orlangur** [comment]
@romantomchak looks like this documentation was not updated for 2.2, you can edit it or file an issue in https://github.com/magento/devdocs.

**Comment by XianHain** [comment]
@xfrenette opened an issue in devdocs: https://github.com/magento/devdocs/issues/1691

**Comment by kanduvisla** [comment]
For those who are wondering how to enable JS bundling in production mode, it can still be done using CLI:

    php -f bin/magento config:set dev/js/enable_js_bundling 1
