### ISSUE TITLE
Menu Renderer

### ISSUE THREAD

**Issue by JamesAnelay** [magento/magento2#1119]
The option to use a template for the menu via a renderer has been removed. Whats the thinking behind this?

**Comment by JamesAnelay** [comment]
Looking at the history of the original file (Page/Block/Html/Topmenu.php) it looks like the base version for Magento2 whatever it was just didn't have this function in yet. Will this be added in later? (I can have a go via pull request if wanted)

**Comment by JamesAnelay** [comment]
Went ahead and created a pull request for this : https://github.com/magento/magento2/pull/1123

**Comment by maksek** [comment]
Hi @JamesAnelay, thanks for contribution. PR looks very promising, only left to make test work :+1:

**Comment by JamesAnelay** [comment]
@maksek it's passing now right? "The Travis CI build passed".

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-35532
