### ISSUE TITLE
Applying multiple tax rates in one tax rule

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#11192]
I have created 3 tax rates:
![admin_tax_zones_and_rates](https://user-images.githubusercontent.com/5052385/31124076-87a0b248-a84b-11e7-9530-c2935b581334.png)

... and assign all tax rates to one tax rule:
![admin_tax_rules_grid](https://user-images.githubusercontent.com/5052385/31124106-a4c7785c-a84b-11e7-81f0-4ef0befb2d4f.png)

![admin_tax_rule_details](https://user-images.githubusercontent.com/5052385/31124111-a9b37de8-a84b-11e7-949e-8dc38c14651b.png)

but only one tax rate from the rule is applied on the front:
![front_cart_details_totals](https://user-images.githubusercontent.com/5052385/31124141-c9c28962-a84b-11e7-9bb1-21be7e06b319.png)

I see the following code, that prevents applying other tax rates from the rule ([\Magento\Tax\Model\ResourceModel\Calculation::_calculateRate](https://github.com/magento/magento2/blob/e60d3a2d8ff3964510ecaa0f7617fa9e482236c4/app/code/Magento/Tax/Model/ResourceModel/Calculation.php#L4200):
```php
        $countedRates = count($rates);
        for ($i = 0; $i < $countedRates; $i++) {
            $rate = $rates[$i];
            ...
            while (isset($rates[$i + 1]) && $rates[$i + 1]['tax_calculation_rule_id'] == $rule) {
                $i++;
            }
            ...
        }
```

I expect that all rates from the rule will be applied one-by-one.

**Comment by orlangur** [comment]
Observed system behavior is correct. Looks like you need setup similar to: https://stackoverflow.com/questions/15833644/how-to-set-two-tax-class-on-single-product-in-magento/15855327#15855327

Just create multiple tax rules. Note that depending on priority applicable tax rules will be either compounded or summarized.

**Comment by flancer64** [comment]
OK, thanks.
