### ISSUE TITLE
Admin main menu possible issue in DEV RC

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1120]
There might be a possible issue with the new design for the admin menu in dev RC.  
If I add too many top level menu items I don't get to see the bottom ones.  
I know this is a bad practice and you should not have too many top level menu items, but for sure this will happen eventually for someone.  
I think a vertical scroll is needed in case there are a lot of menu items.  
I attached a screenshot to explain it better.  
Notice that "menu 6" is cut off and there are other menu items below that and I have no way of accessing them.

![Imgur](http://i.imgur.com/Cv1R2DR.png)

**Comment by godban** [comment]
Hey @tzyganu 

Yeah, for the moment it's fixed and overlaps if menu height is bigger than window. We are planning use smart scroll here in next releases.
Internal tickets MAGETWO-34905, MAGETWO-34476

How do you feel with new admin area design?

**Comment by tzyganu** [comment]
@godban As a developer used to the old magento style I'm not very fond of it, but I'll get over it :smile:   
but I'm trying to view it through the eyes of a user that sees this for the first time. If I look at it that way I kind of like it.

**Comment by tkacheva** [comment]
@tzyganu thank you for feedback and reporting the issues. New Magento Admin look&feel work is in progress and menu issues will be addressed soon

MAGETWO-34929

**Comment by tzyganu** [comment]
This looks like is fixed in 0.74.0-beta13. It may have been fixed earlier but I just noticed it by mistake. 
I will close the issue. Thanks for the fix.
