### ISSUE TITLE
USPS Priority Mail 1-Day Shipping String Change to Priority Mail

### ISSUE THREAD

**Issue by gx2g** [magento/magento2#11203]
My Customers are giving me hell over the USPS titles. They read "Priority Mail 1-Day" which is misleading. I'm trying to find a solution to change the title to "Priority Mail" removing the 1-Day. I've searched everywhere for a solution can you please help me. 

`<td class="col col-method" data-bind="text: method.method_title, attr: {'id': 'label_method_' + method.method_code + '_' + method.carrier_code}"></td>`

How can I overwrite this so we can lower the calls we are getting?

**Comment by pboisvert** [comment]
The "Issues" tab is for reports of code issues with Magento 2. Your question is a "how to" issues better suited to the [Magento Stack Exchange](https://magento.stackexchange.com/) forum or the [Magento Community forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2). Closing this item as it is not an issue report.
