### ISSUE TITLE
Checkout 'hangs' in paymentstep when  adblocker blocks Magento google-analytics javsascript file.

### ISSUE THREAD

**Issue by Cornoud** [magento/magento2#11208]
### Preconditions
Vanilla Magento instance (2.2.0)
Deployed sample data
GoogleAnalytics enabled
Use uBlock as addblocker

### Steps to reproduce
Add any product to the cart as a guest user
Proceed to the checkout
Fill address and customer data
Proceed to the payment step, payment will hang, loader keeps running

### Expected result 
customer can proceed checkout when blocking google.

### Actual Result
![2017-10-03_1410](https://user-images.githubusercontent.com/12034941/31164978-857bbf64-a8e9-11e7-8152-86bb18a662b8.png)

**Comment by magento-engcom-team** [comment]
@Cornoud, thank you for your report.
We've created internal ticket(s) MAGETWO-81631 to track progress on the issue.

**Comment by Sil-B** [comment]
We have the same issues with Magento 2.2.1

**Comment by lingwooc** [comment]
Related/duplicate of #12428

**Comment by heyepic** [comment]
Same issue.

**Comment by magento-engcom-team** [comment]
Hi @Cornoud 
We are closing this report now as duplicate of https://github.com/magento/magento2/issues/12428
Thank you for reporting
