### ISSUE TITLE
Magento api rest webservice

### ISSUE THREAD

**Issue by filipepiressemait** [magento/magento2#11202]
I'm trying to integrate magento api rest webservice.

I'm using magento 2.1.7.

I'm creating an integration and generate the keys, and localy all runs fine, but when i put it online the communication doesn't work.

It should returns stores information.

But it only returns:

 {"message":"Consumer is not authorized to access %resources","parameters":{"resources":"Magento_Backend::store"}}

**Comment by orlangur** [comment]
Hi @filipepiressemait, please check https://github.com/magento/magento2/issues/11145#issuecomment-333231759 and tell if it works.

**Comment by filipepiressemait** [comment]
It still doesn't work.

If i use the authentication method instead of integration with keys, it gives me the access token but when i make the request the answer is the same: Consumer is not authorized

**Comment by magento-engcom-team** [comment]
@filipepiressemait thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce (please provide all detailed information)
 - [ ] Expected result
 - [ ] Actual result

**Comment by filipepiressemait** [comment]
Magento version: 2.1.7
Make Api call with postman
Expect a list of stores
Actual result:
![oauth_error](https://user-images.githubusercontent.com/31819207/31337801-d6b30db0-acf4-11e7-96eb-59babcc0cc0b.PNG)

**Comment by magento-engcom-team** [comment]
Hi @filipepiressemait 
This is not a bug.
For resolve the issue you should set permissions for user Role in menu: System > Permissions > User Roles > "User role". 
In you case you can set access to "Store > Settings > All Stores":
http://prntscr.com/hiwubd

**Comment by guillermogallego** [comment]
Hi, 
Could you find the problem?
Is cpanel?
In perfect location, but in production nothing

I used versions 5.6, 7.0 and 7.1 of php, also versions 2.1.12 and 2.2.3 of Magento and any POST to the API with admin token I get the same message:

Consumer is not authorized to access% resources

**Comment by salehawal** [comment]
@magento-engcom-team i did give all the permissions to the user but still it is not working...

i came a across this page : https://devdocs.magento.com/guides/v2.3/rest/anonymous-api-security.html

i will try it
