### ISSUE TITLE
knockout.js debug version

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2#11212]
### Preconditions

1. every Magento 2 version

In ```lib/web/knockoutjs/knockout.js``` we have knockout.js version [3.3.0](https://github.com/knockout/knockout/releases/tag/v3.3.0) (quite old) and if you check you can see that we are using in production the `debug` release. Is there a reason for that?

- [knockout-3.3.0.debug.js](https://github.com/knockout/knockout/releases/download/v3.3.0/knockout-3.3.0.debug.js) 264KB (gzipped about 63KB)
- [knockout-3.3.0.js](https://github.com/knockout/knockout/releases/download/v3.3.0/knockout-3.3.0.js) 54.6 KB (gzipped about 20KB)

**Comment by magento-engcom-team** [comment]
@slackerzz please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
