### ISSUE TITLE
Magento2.2.0 Migration Column not found: 1054 Unknown column 'created_at' in 'field list'

### ISSUE THREAD

**Issue by AbdulKadir-Agoliya** [magento/magento2#11214]
I am attempting to migrate from 1.9.3.6 to 2.2.0 Opensource to opensource using the data migration tool.
using command : php bin/magento migrate:setting   /path-to/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml
 

1.  start migration setting and there is one error source docuement is 
     Source fields are not mapped. Document: core_website. Fields: mf_guid,created_at,updated_at
     i added   ignore field statement
            <xml>
             <ignore><field>core_website.mf_guid</field> </ignore>
             <ignore><field>core_website.updated_at</field></ignore>
            <ignore><field>core_website.created_at</field></ignore>
           </xml>
     in map-stores.xml

2.  php bin/magento migrate:setting -r /path-to/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml
 

### Expected result
1.error should remove 
2. migration process to next step or proceed further

### Actual result
1 .  [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'field list'

**Comment by magento-engcom-team** [comment]
@AbdulKadir-Agoliya please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only. Also you can report an issue to [migration tool](https://github.com/magento/data-migration-tool)
