### ISSUE TITLE
Admin order does not fill customer data due to unescaped street

### ISSUE THREAD

**Issue by jzahedieh** [magento/magento2#11216]
### Preconditions

1.  Magento EE 2.1.9
2. PHP 7.0.9

### Steps to reproduce

1. Create new test customer
2. Add default billing/shipping address with street address with quote i.e 101 rue d'andigne
3. Create order from customer view

### Expected result

1. All customers information against account is pulled into correct areas and previous order history is displayed on left hand side

### Actual result

1. Create order page is displayed as if its a new customer, no information pulled (e.g. store credit or addresses or order history)

![image](https://user-images.githubusercontent.com/2098908/31175998-327277d4-a909-11e7-8b86-b371223df1b9.png)

### Cause
https://github.com/magento/magento2/blob/2.1/app/code/Magento/Sales/Block/Adminhtml/Order/Create/Form.php#L173-L183

The following commit `MAGETWO-69073: Functional Improvements for Magento 2.1.7` https://github.com/magento/magento2/commit/a2f289363069605d0d9eb5e4fa7d6cb4198df485
escapes all the address fields but because the street is an array it doesn't get escaped:

![image](https://user-images.githubusercontent.com/2098908/31176192-e0f96e02-a909-11e7-9e62-644cf9660094.png)

Worryingly this commit doesn't exist in the 2.2 branch, I don't have a copy to test if this is a regression if the root cause has already been fixed in 2.2

### Workaround

I have created an after interceptor/plugin that decodes the result and escapes the street.

```
<?php

namespace Vendor\Adminhtml\Plugin\Sales\Block\Order\Create;


class Form
{

    /**
     * @var \Magento\Framework\Json\EncoderInterface
     */
    protected $jsonEncoder;
    /**
     * @var \Magento\Framework\Json\DecoderInterface
     */
    protected $jsonDecoder;

    public function __construct(
        \Magento\Framework\Json\EncoderInterface $jsonEncoder,
        \Magento\Framework\Json\DecoderInterface $jsonDecoder
    ) {
        $this->jsonEncoder = $jsonEncoder;
        $this->jsonDecoder = $jsonDecoder;
    }

    /**
     * Escape street
     *
     * @param \Magento\Sales\Block\Adminhtml\Order\Create\Form $subject
     * @param string $result
     * @return string
     */
    public function afterGetOrderDataJson(
        \Magento\Sales\Block\Adminhtml\Order\Create\Form $subject,
        $result
    ) {
        $data = $this->jsonDecoder->decode($result);

        if (isset($data['addresses']) && is_array($data['addresses'])) {
            foreach ($data['addresses'] as $id => $keys) {

                if (isset($keys['street']) && gettype($keys['street']) === 'string') {
                    $escapedValue = htmlspecialchars(
                        (string)$keys['street'],
                        ENT_QUOTES | ENT_SUBSTITUTE,
                        'UTF-8',
                        false
                    );
                    $data['addresses'][$id]['street'] = $escapedValue;
                }
            }
        }

        $result = $this->jsonEncoder->encode($data);

        return $result;
    }
}

```

**Comment by magento-engcom-team** [comment]
@jzahedieh, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
