### ISSUE TITLE
how to change the background header color in magento on wamp server??

### ISSUE THREAD

**Issue by sachinsachin** [magento/magento2#1122]
I want to change my website background header color on wamp server.

**Comment by villageseo** [comment]
Hi sachinsachin!

If your question about magento 2 theme customizing then you can try to update appropriate less variable @header__background-color in the file: \app\design\frontend\Magento\{theme_name}\Magento_Theme\web\css\source\_module.less

**Comment by sachinsachin** [comment]
ok now i want to launch my website on internet. Please tell me how i will
launch my webiste on internet?

**Comment by godban** [comment]
@sachinsachin hey there

Take a look on https://surge.sh/, this may be helpful for you. Few strings into cmd and you can "launch your website on internet"
