### ISSUE TITLE
Magento 2.1.9 Create Account Refreshes Page

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#11220]
### Preconditions

1. 2.1.9
2. PHP 7 / CentOS

### Steps to reproduce

1. Go to Create Account
2. Fill in valid data
3. Click Button to Create Account

### Expected result

1. Account created, email is sent to verify account?

### Actual result

1. Page refreshes. No errors in console log.

**Comment by manuelson** [comment]
Hello,
Can you detail if you use any template? Or if you have any console error ?
Thanks

**Comment by heyepic** [comment]
No console error I'm noticing: https://shop.precisionturbo.net/customer/account/create/
This theme: https://themeforest.net/item/orson-ultimate-magento-2-1-theme/16798772

Worked fine prior to 2.2 upgrade. Looks like the account creation wasn't really customized by the theme so nothing is sticking out to me. Thanks for responding.

**Comment by manuelson** [comment]
Request URL:https://shop.precisionturbo.net/customer/account/createpost/
Request Method:POST
**Status Code:302** 
Remote Address: {security reasons}.221:443

You modify the .htaccess or any directive from apache?

**Comment by heyepic** [comment]
No modifications to .htaccess or anything dealing with apache. Simply did the upgrade to 2.1.9 using the web setup wizard. User account registration worked fine on 2.1.5 (what it was on prior to upgrade).

Copy of .htaccess in root mag2 folder:
`# All explanations you could find in .htaccess.sample file
DirectoryIndex index.php
<IfModule mod_php5.c>
    php_value memory_limit 768M
    php_value max_execution_time 18000
    php_flag session.auto_start off
    php_flag suhosin.session.cryptua off
</IfModule>
<IfModule mod_php7.c>
    php_value memory_limit 768M
    php_value max_execution_time 18000
    php_flag session.auto_start off
    php_flag suhosin.session.cryptua off
</IfModule>
<IfModule mod_security.c>
    SecFilterEngine Off
    SecFilterScanPOST Off
</IfModule>
<IfModule mod_ssl.c>
    SSLOptions StdEnvVars
</IfModule>
<IfModule mod_rewrite.c>
    Options +FollowSymLinks
    RewriteEngine on
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteCond %{REQUEST_METHOD} ^TRAC[EK]
    RewriteRule .* - [L,R=405]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-l
    RewriteRule .* index.php [L]
</IfModule>
    AddDefaultCharset Off
    AddType 'text/html; charset=UTF-8' html
<IfModule mod_expires.c>
    ExpiresDefault "access plus 1 year"
    ExpiresByType text/html A0
    ExpiresByType text/plain A0
</IfModule>
    RedirectMatch 403 /\.git
    <Files composer.json>
        order allow,deny
        deny from all
    </Files>
    <Files composer.lock>
        order allow,deny
        deny from all
    </Files>
    <Files .gitignore>
        order allow,deny
        deny from all
    </Files>
    <Files .htaccess>
        order allow,deny
        deny from all
    </Files>
    <Files .htaccess.sample>
        order allow,deny
        deny from all
    </Files>
    <Files .php_cs>
        order allow,deny
        deny from all
    </Files>
    <Files .travis.yml>
        order allow,deny
        deny from all
    </Files>
    <Files CHANGELOG.md>
        order allow,deny
        deny from all
    </Files>
    <Files CONTRIBUTING.md>
        order allow,deny
        deny from all
    </Files>
    <Files COPYING.txt>
        order allow,deny
        deny from all
    </Files>
    <Files Gruntfile.js>
        order allow,deny
        deny from all
    </Files>
    <Files LICENSE.txt>
        order allow,deny
        deny from all
    </Files>
    <Files LICENSE_AFL.txt>
        order allow,deny
        deny from all
    </Files>
    <Files nginx.conf.sample>
        order allow,deny
        deny from all
    </Files>
    <Files package.json>
        order allow,deny
        deny from all
    </Files>
    <Files php.ini.sample>
        order allow,deny
        deny from all
    </Files>
    <Files README.md>
        order allow,deny
        deny from all
    </Files>
    <Files magento_umask>
        order allow,deny
        deny from all
    </Files>
ErrorDocument 404 /pub/errors/404.php
ErrorDocument 403 /pub/errors/404.php
<IfModule mod_headers.c>
    Header set X-UA-Compatible "IE=edge"
    <FilesMatch "\.(appcache|atom|bbaw|bmp|crx|css|cur|eot|f4[abpv]|flv|geojson|gif|htc|ico|jpe?g|js|json(ld)?|m4[av]|manifest|map|mp4|oex|og[agv]|opus|otf|pdf|png|rdf|rss|safariextz|svgz?|swf|topojson|tt[cf]|txt|vcard|vcf|vtt|webapp|web[mp]|webmanifest|woff2?|xloc|xml|xpi)$">
        Header unset X-UA-Compatible
    </FilesMatch>
</IfModule>`

Not sure if it matters, but I do have varnish cache configured for this store. Could that be holding onto old stuff? It's on a cron and should be updating...

**Comment by manuelson** [comment]
I'll check the issue. Keep in touch
Thanks

**Comment by manuelson** [comment]
I was checking your issue and I think the problem is the theme version. You need include in your register form this line:
`<input name="form_key" type="hidden" value="{the key value}">
`(Check Luma theme)

This input is included for security reasons and looks like now is required.
Check and tell me if it is work.

**Comment by manuelson** [comment]
I will check in your personal page this issue. I take your form_key from the cookies info and i modify by console the HTML to include the form_key. This is a result:

https://preview.ibb.co/isrz8w/Captura_de_pantalla_2017_10_05_a_las_17_48_19.png

Can you check my user in the backoffice

**Comment by heyepic** [comment]
Brilliant - works with:
`<input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">`

Thanks so much Manu!
