### ISSUE TITLE
Update 2.1.7 to 2.2.0 --> Indexing error

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#11228]
### Preconditions

1. Update from a 2.1.7 to 2.2.0 system via command line

### Steps to reproduce

1. Update from a 2.1.7 to 2.2.0 system via command line

### Expected result

1. The system reindexes without an error

### Actual result

1. The indexer shows this error message:

Catalog Search indexer process unknown error:
Decoding failed: Syntax error

**Comment by magento-engcom-team** [comment]
Hi @andidhouse 
Unfortunately, I could not reproduce the issue as you described it.
I try upgrade from 2.1.4 to 2.2.0 with sample data

**Comment by magento-engcom-team** [comment]
@andidhouse, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0

**Comment by andidhouse** [comment]
@magento-engcom-team thank you for testing.

Did you test an updated version as well from 2.1.7 to 2.2.0 or just the 2.2.0 version?
I think it is important to test and updated version right?

Thanks!

**Comment by hostep** [comment]
@andidhouse: if you can provide a simple reproducible case of how it fails it will help tremendously. Right now your report is too vague to make anything of it (I'd search your database for incorrectly [serialized](http://php.net/manual/en/function.serialize.php) or [json encoded](http://php.net/manual/en/function.json-encode.php) data, it sounds like a problem in that area).

And yes there are upgrade bugs in 2.2.0, but it would really help out with quickly fixing them if more info was available for those bugs about how they can be reproduced. There are simply too many different variations of setups of Magento out there, that they can't test them all unfortunately.

**Comment by orlangur** [comment]
Similar error was already reported and successfully solved by cache clearing.

Another possible reason is some custom serialized data in database, check https://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes.html#database-data-format-changes section.

**Comment by inetmaster** [comment]
Hi

I am also having the same error after upgrading the Magento from 2.1.9 to 2.2.0.  If it is a data inconsistency issue, how can we check that?

Regards
TD
