### ISSUE TITLE
Luma demo homepage has horizontal scrolling

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#11232]
### Preconditions
1. Magento 2.1.9 using the Luma theme (no customisations)

### Steps to reproduce
1. Ensure you have the sample data
2. Load the homepage on a mobile device
3. 

### Expected result
1. There should not be any horizontal scrolling

### Actual result
1. there is horizontal scrolling

![scrolling](https://user-images.githubusercontent.com/8895777/31188383-9bc448ac-a92c-11e7-811d-938affe51d89.gif)

**Comment by magento-engcom-team** [comment]
@BenSpace48, thank you for your report.
The issue is already fixed in 2.2.0
