### ISSUE TITLE
Can't close mobile search bar once typed

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#11231]
### Preconditions
1. Magento 2.1.9 using the Luma theme (no customisations)

### Steps to reproduce
1. Load the homepage on a mobile device
2. Tap on the search icon to access the search input
3. Start typing (but do not submit)
4. Now tap on the search icon again to close the search bar

Sometimes it will close, but if you open it again it will not close.

### Expected result
1. Search bar closes

### Actual result
1. Nothing, search bar stays open

Happens on iOS and Android devices using different browsers, it's because the `active` class is not removed.

I suspect this issue was introduced as a fix for https://github.com/magento/magento2/issues/4282

### GIF

Recorded on an iPhone 5s emulator running iOS 10.3 but can replicate it on real iPhone 7 running iOS 11 to (amongst other devices including Android).

![search](https://user-images.githubusercontent.com/8895777/31188081-baff9ee8-a92b-11e7-9829-4f79f1f58557.gif)

**Comment by magento-engcom-team** [comment]
@BenSpace48, thank you for your report.
We've created internal ticket(s) MAGETWO-81048 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48 
the issue has been fixed in 2.2.1 and will be available soon
https://github.com/magento/magento2/pull/11246

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81020

**Comment by magento-team** [comment]
Hi @BenSpace48. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1282 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
