### ISSUE TITLE
Backend automatically logs out when editing a page Magento 2.2.0

### ISSUE THREAD

**Issue by jorgediezprada** [magento/magento2#11239]
Any time I´m trying to edit anything on a page, I get log out from Magento. I cannot save anything. I cannot not even open the multimedia librery without been log out.

Preconditions

1. Magento 2.2.0
2. PHP 7.0.23
3. MySQL 5.6

Steps to reproduce

1. Log In >content > page > Home >edit
2. Content
3. Click on an image > edit img > multimedia library

 Expected result

1. Open Multimedia library > choose an image <> display an ima > save page

Actual result

1. logs out

**Comment by magento-engcom-team** [comment]
@jorgediezprada, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by jorgediezprada** [comment]
I can give you access to cpanel if you want. That way you will see the error.
