### ISSUE TITLE
After Enabling Varnish Cache unable to get customer session in product view page

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#11238]
### Preconditions
1. Enable Varnish Cache in Magento 2.2.0 

### Steps to reproduce

1.  After enabling varnish, I have checked the customersession to show wishlist link only if the customer is login.
2.  After Logged into the page, Still the content is not visible.
3. Once i put cacheable="false" in the block, then the content is visible.

### Expected result

1.  After logged in, the needed content should be visible

### Actual result

1. After logged in, the needed content not visible

**Comment by sasilinux** [comment]
After enabling cache, unable to get the customer data.

**Comment by sasilinux** [comment]
via js "Magento_Customer/js/customer-data". Unable to get the customer details. please have a look and provide the solution.

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
