### ISSUE TITLE
CartId is missing during checkout while select online payment

### ISSUE THREAD

**Issue by Prad2703** [magento/magento2#11241]
### Preconditions

1.  Magento 2.1.7, PHP version 5.6.4, Mysql

### Steps to reproduce

1. Login to the site https://www.craftnshop.com/customer/account/login/
2. Login Credentials 
Email: rajarshi.bhattacharjee@infoway.us
​Password: ​e!!ip$$is007
3. Add to cart any in stock product. 
4. Go for checkout
5. Select online payment method
6. Click on place Order Button

### Expected result

1.  It should redirect to the online payment gateway which is CCAVENUE

### Actual result

1. 
![ckddobpomgkffela](https://user-images.githubusercontent.com/29308276/31222963-846c566c-a9e6-11e7-8e61-d3eacf1dc6c1.png)

**Comment by Jeroenll** [comment]
Similar message as #9744, maybe related?

**Comment by Prad2703** [comment]
Dear Team,

This is not the similar issue. So please look after it.


​========================================​

Regards,

*Pradipta Sarkar* *Team Leader(Open Source), Production*
Infoway Technology Solution Limited
Module 301, 3rd Floor, 61/C G.T Road,
Serampore, WB - 712203, India.
------------------------------------------
IVR: 0.903.811.5400 | E: pradipta.sarkar@infoway.us <email@infoway.us>
www.itsl.net | www.infowaylive.com
​
​
​========================================​
​

**Comment by YevSent** [comment]
Magento does not provide support for custom payment integrations, please, confirm if this issue reproducible with built-in payment solutions.

**Comment by magento-engcom-team** [comment]
Hi @Prad2703 we closing the issue for now. If you can reproduce the issue on clean Magento installation, please, update this issue and reopen it. thank you

**Comment by samc2810** [comment]
I have a quick fix for this
I replaced
`            $customerQuote = $this->quoteRepository->getForCustomer($this->_customerSession->getCustomerId());`
in
`\Magento\Checkout\Model\Session::loadCustomerQuote`
with
`            $customerQuote = $this->quoteRepository->getActiveForCustomer($this->_customerSession->getCustomerId());`

ps. ofcourse do it the right way. override in di.xml ;)

**Comment by samc2810** [comment]
@magento-engcom-team 
heres how you can reproduce it:

1. Start off by clearing caches, browser caches etc
2. Register a new user and place an order with this user
3. Open a different browser
4. Go till checkout as guest
5. Enter the email of the previous user (do not close the 1. browser window)
6. Enter the correct password in checkout when you are asked

This is when I get this error each time M2.1.6

@Prad2703 
may be you can reopen it
