### ISSUE TITLE
Hardcoded attributes list in Type\Grouped::getAssociatedProducts() method

### ISSUE THREAD

**Issue by andkirby** [magento/magento2#11248]
### Preconditions
**Magento version:** 2.2.

### Steps to Reproduce
It looks like there are hardcoded attributes in simple products list of the grouped one.
`\Magento\GroupedProduct\Model\Product\Type\Grouped::getAssociatedProducts()`
```
->addAttributeToSelect(
    ['name', 'price', 'special_price', 'special_from_date', 'special_to_date', 'tax_class_id']
)
```

**Actual Result:** Child products of a *grouped* product have only mentioned attributes.

**Expected Result:** Child products of a *grouped* product have the same loaded attributes like it works for configurable or bundle product types.

#### Mentioned product types code samples
Code to fetch child/associated products of a *configurable* one:
```
$product->getTypeInstance()->getUsedProducts($product)
```
Code to fetch child/associated products of a *bundle* one:
```
$product->getTypeInstance()->getSelectionsCollection([], $product)
```

**Comment by orlangur** [comment]
You can easily customize `\Magento\GroupedProduct\Model\Product\Type\Grouped::getAssociatedProductCollection` as far as I see.

> Could you make it in the same way like it works for configurable or bundle ones?

Please clarify exact methods to look into to compare with grouped.

**Comment by andkirby** [comment]
Sure. And in this case I'll be pushed to implement the same method  `getAssociatedProducts()`.
I don't say there is no completely way to make it. It's just expected being flexible.

So, configurable one has following method:
```
$product->getTypeInstance()->getUsedProducts($product)
```
Bundle one this one:
```
$product->getTypeInstance()->getSelectionsCollection([], $product)
```

By the way, it would really good to have single API for those associated products.
Abstract class declared it, and only Grouped uses it.
```
\Magento\Catalog\Model\Product\Type\AbstractType::getAssociatedProducts()
```

**Comment by orlangur** [comment]
>  in this case I'll be pushed to implement the same method `getAssociatedProducts()`

Why? Just add attributes you need in customized `getAssociatedProductCollection` and use default implementation.

> single API for those associated products

I don't think it's a good idea as they are all different and have slightly different semantics. Inheritance from `\Magento\Catalog\Model\Product\Type\AbstractType` is misused for many of those custom methods, it would be better to have them as independent classes.

**Comment by andkirby** [comment]
> Just add attributes you need in customized getAssociatedProductCollection and use default implementation.

I can't do this in a module where I'm working in. It provides some feature which requires some base development. I just don't wan't to fetch all attributes or some particular ones.
Frankly speaking, I can move building this collection into a module, but it's not a good idea to make this module responsible for that.

> and use default implementation.

If you are talking about setting customized collection into `\Magento\GroupedProduct\Model\Product\Type\Grouped::getAssociatedProducts` - no way. `getAssociatedProductCollection` - it's always creating new instance.

>  it would be better to have them as independent classes.

Implementation - yes. But I'm talking about the interface.

**Comment by orlangur** [comment]
> I can't do this in a module where I'm working in. It provides some feature which requires some base development. I just don't wan't to fetch all attributes or some particular ones.
Frankly speaking, I can move building this collection into a module, but it's not a good idea to make this module responsible for that.

Still don't get it. There is no need to build collection in your module, just create an `after` plugin for `Magento\GroupedProduct\Model\Product\Type\Grouped::getAssociatedProductCollection` and add necessary attributes with `addAttributeToSelect`.

**Comment by andkirby** [comment]
I know how to make it right. It should be right from the box.

Adding a plugin will fix the issue. I suggest to fix it in core.

**Comment by orlangur** [comment]
> Adding a plugin will fix the issue. I suggest to fix it in core.

I don't see an issue here yet. Could you format description according to template so that actual/expected result is clear?

> And there is no simple way to change this list in code.

Plugin-interceptor is an easy way to change this list in code. I don't think it's worth moving to constructor so that it can be modified via `di.xml`.

**Comment by andkirby** [comment]
> Could you format description according to template so that actual/expected result is clear?

Sure. Updated it.

> Plugin-interceptor is an easy way to change this list in code.

Yeah, you are completely right. I just don't want to fix core code in my module.

The main purpose of this issue is to shape providing child products of *grouped* type in the same way like it works in other aggregating product types.

**Comment by magento-engcom-team** [comment]
@andkirby, thank you for your report.
We've created internal ticket(s) MAGETWO-83134 to track progress on the issue.

**Comment by andkirby** [comment]
Thank you, team!

**Comment by magento-engcom-team** [comment]
@andkirby, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
