### ISSUE TITLE
Shipping address not set. error in get shipping method rest api in magento2

### ISSUE THREAD

**Issue by lalitkumarjeengar** [magento/magento2#11244]
### Preconditions

1. Magento Version 2.1.5
2.  PHP 7.0
3. MySQL 

### Steps to reproduce

1.  Create Cart Using /rest/V1/customers/{Customer_id}/carts
2.  Add Item into Cart Using /rest/V1/carts/mine/items
3.  Add Billing Address Using /rest/V1/carts/{Cart_Id}/billing-address
4. Get Shipping Method Using rest/V1/carts/{Cart_Id}/shipping-methods/

### Expected result

1.  List of available shipping methods

### Actual result

1. {
    "message": "Shipping address not set.",
    "trace": "#0 [internal function]: Magento\\Quote\\Model\\ShippingMethodManagement->getList(66)\n#1 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)\n#2 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#3 /var/www/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#6 /var/www/html/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#7 {main}"
}

Please help me how can i solve this issue i am stuck from last 5 days and try to find solution but nothing.

**Comment by magento-engcom-team** [comment]
@lalitkumarjeengar As message suggests, try adding a shipping address.
For additional guidance you may refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
