### ISSUE TITLE
Saving category reseting its changes in category tree.

### ISSUE THREAD

**Issue by anton-vakulchyk** [magento/magento2#1124]
Steps to reproduce:
1. Go to Admin -> Products -> Categories.
2. Select an existing category in category tree.
3. Move category to to any different level.
4. Save category information.
Saving category will reset the changes due to the fact that input name="general[path]" is not updated.
![6mwytykh0l](https://cloud.githubusercontent.com/assets/1549445/6815251/ad692d50-d25d-11e4-8226-105539845c90.gif)

**Comment by kokoc** [comment]
@anton-vakulchyk Thank you for reporting the issue.

Internal reference - MAGETWO-35516

**Comment by kokoc** [comment]
@anton-vakulchyk Related pull request has been merged. Thank you for helping us make Magento better! Closing the issue.
