### ISSUE TITLE
Missing /var/di folder in Magento 2.2

### ISSUE THREAD

**Issue by sbwcws** [magento/magento2#11258]
I ran php bin/magento setup:di:compile

I am missing /var/di folder

**Comment by hostep** [comment]
Check your `generated/` directory, it has been moved over there in Magento 2.2

Please close this issue and next time, please discuss this over at https://magento.stackexchange.com/, Github isn't really meant for questions like these :)

**Comment by sbwcws** [comment]
Thanks & Sorry ...

**Comment by orlangur** [comment]
No problem, biggest surprises may be avoided if one get familiar with https://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes.html before upgrade 😉
