### ISSUE TITLE
APS package deinstallation with table prefixes purges whole database

### ISSUE THREAD

**Issue by elektrozitrone** [magento/magento2#11255]
This bug is about the packaging at:
https://dev.apsstandard.org/apps/1.2/www.magentocommerce.com/magento/Plesk/

I did not find a source repository of the APS package installation logic nor any issue tracker more fitting than this one. I guess the packaging was on behalf of magento.com but I wasn't able to evoke some response on https://magento.com/contact-us
Neither was I able to report this on plesk.com (they referred me to the former).

I discovered two problems with the APS package.

### Preconditions
install magento-2.1.0-22 package with table prefixes into a preexisting mysql database

### Bug1:
you can not install a 2nd installation with different table prefix to the same mysql database, because some constraint names are not prefixed and thus conflict

## Steps to reproduce
use APS package logic to uninstall magento

## Expected result
the tables created on installation are deleted

## Actual result
all tables (even unrelated) are deleted.
which may be a disastrous outcome

**Comment by magento-engcom-team** [comment]
@elektrozitrone, thank you for your report.
We've created internal ticket(s) MAGETWO-84712 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @elektrozitrone

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@elektrozitrone thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
