### ISSUE TITLE
Maento 2.1 don't switch language after switch by language picker

### ISSUE THREAD

**Issue by twain83** [magento/magento2#11251]
Site address: http://booking.dev-efresh.pl

I've got problem with language translations to english, polsih and gernam.

### Preconditions
Magento Running TemplateMonster Framework
1.  1 website, 1 store, 3 storeview (polish default, english, german)

### Steps to reproduce

1. Go to site http://booking.dev-efresh.pl
2. Change language pickerlanguage to another (default is english)

### Expected result

1. Magento should change language string after picker value has changed

### Actual result
1. Magento language switcher change language but translated string text doesn't change in phtml, cookie value has been changed to pl, en, de.

**Comment by mzeis** [comment]
Thanks for creating this issue!

I'm sorry but bugs in 3rd party themes are out of the scope for the Magento issue tracker. Please let us know if/how we can re-produce this problem in a fresh 2.1 installation without extensions and custom themes and I'll try to re-produce.
