### ISSUE TITLE
Unable to create product with same name as already existing via REST api: URL key for specified store already exists.

### ISSUE THREAD

**Issue by darinda** [magento/magento2#11266]
### Preconditions

1. Magento v2.2.0
2. PHP v7.0.20
3. MySQL v5.6.34

### Steps to reproduce

1. Create some product in admin interface or rest api or whatever

> `
"product": {
        "sku": "product-1-sku,
        "name": "Product Name",
        "attribute_set_id": 4,
        "price": 120,
        "status": 1,
        "visibility": 4,
        "type_id": simple
}

2. Try to create another product **with the same name** via REST api (POST http://MAGENTO/V1/products)

> `
"product": {
        "sku": "product-2-sku,
        "name": "Product Name",
        "attribute_set_id": 4,
        "price": 120,
        "status": 1,
        "visibility": 4,
        "type_id": simple
}

### Expected result

1. Product with same name is created

### Actual result

1. The product is not created, an exception is thrown: "URL key for specified store already exists."

Creating of a product with the same name product name (in the same website) fails because Magento will auto-create the url key resulting in a duplicate url key conflict.

There is no way to override the url key via REST Api to circumvent this problem. Magento should either create a non-duplicate url key (appending a suffix for example) like it did in Magento1 or at least allow setting the url key explicitly.

Currently the only way to circumvent the problem is creating the product with some other name (appending some id for example) for the generated url key to be unique and then issue another PUT request to rename the product back to the desired value.

**Comment by orlangur** [comment]
Hi @darinda, thanks for the well-formed report. Closing as a duplicate of https://github.com/magento/magento2/issues/8188#issuecomment-331110066.

> for the generated url key to be unique and then issue another PUT request to rename the product back to the desired value

Yeah, and another possible way could to to customize internal Magento behavior by implementing plugin-interceptor.

It is a known limitation that there is no way to interact directly with URL Rewrites in current API, some developers overcame this by creating a dedicated endpoint.

**Comment by demetrius143** [comment]
A work around is to send the url_key manually by adding the following node to the product node:
```
"custom_attributes": [
            {
                "attribute_code": "url_key",
                "value": "product-2-sku"
            }
]
```
Using the sku is an easy way to ensure you will never have a problem, although maybe not the best for SEO
In my opinion magento core SHOULD autogenerate the url key IF a duplicate is found just the same way it does in the admin area when creating a product
eg:
If url_key: product-name is taken then
try product-name-1
(in a while loop or something)

**Comment by orlangur** [comment]
@dknzdesign,

> In my opinion magento core SHOULD autogenerate the url key IF a duplicate is found just the same way it does in the admin area when creating a product

Not, it shouldn't and it was implemented this way intentionally so that merchant has full control over SEO (unlike in Magento 1 where URL Key could change during reindexing and impact SEO).
