### ISSUE TITLE
testCreateObjectManagerFactoryCouldBeOverridden unit test failing v2.1.9

### ISSUE THREAD

**Issue by tr33m4n** [magento/magento2#11268]
The test `Magento\Framework\App\Test\Unit\ObjectManagerFactoryTest::testCreateObjectManagerFactoryCouldBeOverridden` is failing due to the test expecting a `BadMethodCallException` when calling `$factory->create`.

As PHP can accept any number of arguments beyond what's defined within the function, this test will not pass

### Preconditions
1. Magento 2.1.9
2. PHP 7.0.14
3. PHPUnit 4.1.0

### Steps to reproduce
1. Run `php vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --filter="testCreateObjectManagerFactoryCouldBeOverridden"`

### Expected result
1. The test should pass with the expected exception `BadMethodCallException`

### Actual result
```sh
There was 1 failure:

1) Magento\Framework\App\Test\Unit\ObjectManagerFactoryTest::testCreateObjectManagerFactoryCouldBeOverridden
Failed asserting that exception of type "\BadMethodCallException" is thrown.
```

**Comment by orlangur** [comment]
Passes on my local and on CI. Maybe `var` folder is not writable in your case or something?

**Comment by tr33m4n** [comment]
@orlangur `var` folder is writable, I can see the test creates the required `_files` folder under `vendor/magento/framework/App/Test/Unit/`, so I doubt it's a permissions problem. What PHP/Magento/PHPUnit versions did you use to test?

**Comment by tr33m4n** [comment]
The expected exception `BadMethodCallException` is commonly used with

**Comment by orlangur** [comment]
I used your steps so it's `4.1.0` from `vendor`. Please debug your local env, looks like the issue is env-specific.

**Comment by tr33m4n** [comment]
@orlangur Most likely yep, or rather project/company specific as we all seem to hit the same error, I'll update when I know more

**Comment by magento-engcom-team** [comment]
Hi @tr33m4n we cannot reproduce the issue on our side. Closing the issue

**Comment by VincentMarmiesse** [comment]
Hello,

I have the same issue on a Magento 2.2.2.
My PHP version is 7.0.25 and PHPUnit is in version 6.2.4

```
$ php vendor/bin/phpunit --version                       
PHPUnit 6.2.4 by Sebastian Bergmann and contributors.
```

**Comment by tschirmer** [comment]
I've got the same issue on our build server when trying to run tests.

Magento 2.2.3
PHP 7.0.30
PHPUnit 6.2.4

**Comment by engcom-backlog-nickolas** [comment]
Hello @tr33m4n, thank you for your report. Unfortunately I wasn't able to reproduce this issue.
![peek 2018-08-10 09-57](https://user-images.githubusercontent.com/40755810/43944156-a66221e6-9c86-11e8-9981-764257a7c809.gif)
If you'd like to update it, please reopen the issue.

**Comment by borey88** [comment]
Hello,
I have reproduced issue. 

**Preconditions:**
Magento 2.2.3
PHP 7.0.22
PHPUnit 6.2.4

**Steps to reproduce:**
1) set production mode `php bin/magento deploy:mode:set production`
2) run `php bin/magento setup:upgrade`
3) run `php bin/magento setup:di:compile`
4) run unit tests `php bin/magento dev:tests:run unit`

If run test after step 2) (before setup:di:compile) - tests will be passed.

**Comment by orlangur** [comment]
Thanks @borey88!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98610`, `MAGETWO-98611` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
