### ISSUE TITLE
M2.2 Magento Social becoming reset by extensions

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#11265]
Whenever I install an extension the status of Magento Social changes from "Inactive" to "Reset"

### Preconditions
1.  Magento 2.2
2.  PHP 7.1.10

### Steps to reproduce
1.  Unzip extension with command "unzip"
2.  Issue command php bin/magento setup:upgrade
3.  Issue command php bin/magento cache:flush
4. Installed extension works as expected

### Expected result
1.  No errors should appear in Admin

### Actual result
1.  Magento Social changes from "Inactive" to "Reset" and error message is displayed - see screenshot

![integrations](https://user-images.githubusercontent.com/10808588/31266901-cea52714-aac1-11e7-8943-a8c682d9148f.jpg)

**Comment by orlangur** [comment]
Hi @bondimedical3, GitHub is intended for bug reports in Magento 2 core modules. I believe extension developer should be contacted in your case.

**Comment by bondimedical3** [comment]
I have contacted the extension developer and he does not know why this occurs.

**Comment by orlangur** [comment]
But he is the one who is supposed to solve any incompatibilities of his extension with 2.2, isn't it?

Only if investigation will show the problematic code in core, such bug report would be valid for this repo.

**Comment by bondimedical3** [comment]
This is occurring for all extensions?

**Comment by orlangur** [comment]
Have no idea. If similar problem would occur for few other extensions with integrations, it could indicate there is a problem on core side.

**Comment by bondimedical3** [comment]
That is what I am saying. I have installed 3 extensions and it has occured on all of them.

**Comment by orlangur** [comment]
Following link from message are you able to enable affected integrations back?

**Comment by bondimedical3** [comment]
Yes. But after a few days the message reappears.

**Comment by orlangur** [comment]
Ok, let's leave it open for now as I'm not aware how this feature is supposed to work.

**Comment by hollow020** [comment]
I observed the same behavior after updating from CE to EE by composer on clean 2.2.0.

**Comment by orlangur** [comment]
@bondimedical3 thanks for bug report! Closing in favor of https://github.com/magento/magento2/issues/11374 which contains some more details.
