### ISSUE TITLE
Site not open correctly

### ISSUE THREAD

**Issue by rratinov** [magento/magento2#11278]
### Preconditions

1. magento 2.1.8
2. php 7.0.14-1~dotdeb+8.1
3. MySQL - Ver 15.1 Distrib 10.0.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
4. apache - 2.4.10

### Steps to reproduce

1. Go to https://www.ecomarkt.nl/

### Expected result

1. You should visit the page https://prnt.sc/gu54at

### Actual result

1. But sometimes when my colleague use FF (http://prntscr.com/gudp2g) on Windows  - http://prntscr.com/gu2pne 

### Log file
a:4:{i:0;s:38:"No region found within the locale 'nl'";i:1;s:13300:"#0 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/zendframework1/library/Zend/Currency.php(106): Zend_Currency->setLocale('nl')
#1 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Currency.php(27): Zend_Currency->__construct(NULL, NULL)
#2 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Framework\Currency->__construct(Object(Magento\Framework\App\Cache\Proxy), NULL, NULL)
#3 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#4 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#5 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#6 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'currencyInterfa...', 'Magestore\\Affil...')
#7 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magestore\\Affil...', Array, Array)
#8 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magestore\\Affil...')
#9 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magestore\\Affil...')
#10 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magestore\\Affil...', NULL, 'helperConfig', 'Magestore\\Affil...')
#11 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magestore\\Affil...', Array, Array)
#12 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magestore\\Affil...', Array)
#13 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Event/ObserverFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Magestore\\Affil...', Array)
#14 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Event/Invoker/InvokerDefault.php(57): Magento\Framework\Event\ObserverFactory->create('Magestore\\Affil...')
#15 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#16 /home/ecomarkt/www/dev.ecomarkt.nl/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#17 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/App/Action/Action.php(91): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#18 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#20 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'contextPlugin')
#21 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'customer-app-ac...')
#24 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'storeCheck')
#27 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'weee-app-action...')
#30 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'tax-app-action-...')
#33 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /home/ecomarkt/www/dev.ecomarkt.nl/var/generation/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#40 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#43 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'searchautocompl...')
#46 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/mirasvit/module-search-autocomplete/src/SearchAutocomplete/Plugin/ResponsePlugin.php(156): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#47 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Mirasvit\SearchAutocomplete\Plugin\ResponsePlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#48 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#49 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#50 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#51 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#52 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#53 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#54 /home/ecomarkt/www/dev.ecomarkt.nl/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#55 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#56 /home/ecomarkt/www/dev.ecomarkt.nl/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#57 /home/ecomarkt/www/dev.ecomarkt.nl/index.php(42): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#58 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}

**Comment by orlangur** [comment]
Looks like the issue is browser-specific: https://www.magestore.com/magento-2-tutorial/fix-issue-no-region-found-within-locale-magento-2/

Not sure if it should be suppressed on Magento side somehow though.

**Comment by okorshenko** [comment]
Hi @rratinov we can not debug you site, please, provide detailed preconditions and steps to reproduce on clean Magento installation so that we can reproduce it on our side

**Comment by rratinov** [comment]
hi, @okorshenko . 
Thank you for your attention.

The only thing which I can provide - this is the version of FF (http://prntscr.com/gudp2g). 
I added all needful preconditions and steps to reproduce. So the problem that from the same PC site opened and not opened in different browsers. 

Unfortunately, that`s all.
I'm not sure if on clean Magento we will have the same, but I don't have the possibility to check it.

**Comment by orlangur** [comment]
@rratinov did you try steps from link I posted? Seems to be improper locale set in browser.

**Comment by rratinov** [comment]
@orlangur No, we thought it's not our case. but we will try it today. Thank you very much.

**Comment by attilai** [comment]
@orlangur Unfortunately, the proposed solution to the problem has already been applied by the vendor of the extension "Magestore" and doesn't solve the problem. https://goo.gl/mAEk2A

**Comment by orlangur** [comment]
@attilai I'm more interested in browser-specific fix attempt:

> Easily, you have to setup language for your browser. Example with google chrome: Setting → Language → Choose your language → Done

So, if it solves the problem we can get steps reproducible for core

1. Spoil browser configuration
2. Observe fatal error on site

**Comment by magento-engcom-team** [comment]
@rratinov  thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
