### ISSUE TITLE
Layered navigation issue with custom attribute set

### ISSUE THREAD

**Issue by syedsaleem086** [magento/magento2#11271]
Layered navigation is not working with custom attribute set

### Preconditions
1. Magento 2.1.7
2. PHP 7.0.22

### Steps to reproduce
1. create attribute and associate with default attribute set, now create product with this attribute set -> layered navigation will work
2. create attribute and associate with custom attribute set, now create product with this attribute set -> layered navigation will not work

### Expected result
Layered navigation should work on both the conditions with custom attribute set and default attribute set

### Actual result
Layered navigation is not working with custom attribute set but working with default attribute set

attached screenshots
![2017-10-06_17h27_03](https://user-images.githubusercontent.com/15724424/31279613-43fc4d44-aac7-11e7-9b59-b8f98acfe81d.png)
![2017-10-06_17h28_10](https://user-images.githubusercontent.com/15724424/31279610-43f7861a-aac7-11e7-9da6-3433316ec0c9.png)
![2017-10-06_17h29_13](https://user-images.githubusercontent.com/15724424/31279611-43f8df7e-aac7-11e7-9cac-ad081185f0b1.png)
![2017-10-06_17h37_43](https://user-images.githubusercontent.com/15724424/31279612-43f9bcf0-aac7-11e7-9233-514b010d79b4.png)

**Comment by magento-engcom-team** [comment]
@syedsaleem086, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
