### ISSUE TITLE
Zip downloads of 2.2.0 are php 7.0 only

### ISSUE THREAD

**Issue by fooman** [magento/magento2#11279]
Follow up on the discussion in #11264
### Preconditions

1. Magento 2.2.0

### Steps to reproduce

1. Head to https://magento.com/tech-resources/download
2. Download Magento 2.2.0 as a zip file
3. Notice php version compatibility of vendor/zendframework/zend-code/composer.json

### Expected result

1. Due to php version differences a composer install will choose a different version of zend-code based on the version of php. For php 7.0 zend-code 3.1.0 is the correct version, for php 7.1 zend-code 3.2.0 is the correct version. 

### Actual result

1. Currently only one download is offered which includes the php 7.0 compatible version. Either make this clear in the description that if you are using php 7.1 to use composer or provide a second zip file.

**Comment by piotrekkaminski** [comment]
@fooman hey, is there a workaround like running composer update after unpacking the zip file or changing something in the composer.json or .lock?

**Comment by maghamed** [comment]
Hey @fooman,  there should not be issues regarding compatibility of zend-code with php 7.1+

We've already discussed that with Ocramius 
https://twitter.com/iminyaylo/status/903215810101075968
https://github.com/zendframework/zend-code/issues/129

Here is an article about Doctrine which follows the same approach: http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

Make sure that you run 
`composer update`
on the same machine where you would like to deploy code. 
Currently, possible issues could occur if dev and production environments are different (dev has PHP 7.1 and production - PHP 7.0).

A common problem is people running a newer PHP version on their developer machines than on their production servers. In this case, running composer update on a developer machine (with PHP 7.1) might happily pull in an update that simply won’t work when deployed on a production machine running PHP 7.0.

To make sure this doesn’t happen to you, there are two choices:

- run composer update on a machine with the same PHP version that you use in production
- use the platform.config config setting in composer.json to override your local PHP version

**Comment by fooman** [comment]
@piotrekkaminski I haven't tested it yet but I am sure that a composer update would fix it - however that defeats the purpose of the zip download in my eyes (if this leads to the de-commissioning of the zip downloads and make every one use Composer from the outset that works for me).

@maghamed the issue is with the downloadable zip file offered by Magento [here](https://magento.com/tech-resources/download) - is that Magento has made a decision when preparing the zip file to go with php 7.0.

Again I'd be happy to see the downloadable zips removed and possibly replaced by a downloadable 1 line installer script (that does the right sequence of composer project create, etc) instead.

**Comment by magento-engcom-team** [comment]
Hi @fooman 
Thank you for the report. We are working right now to make it clear in the description. The Magento code won't be changed, so we are closing the issue.
