### ISSUE TITLE
Modal position when adding item to an order within admin

### ISSUE THREAD

**Issue by robjmills** [magento/magento2#1127]
Within the admin area, if you add a configuarable product to an order, and then press the configure button again, the modal box disappears off-screen. If you close it, and then open it again it appears in the correct position.

_Click configure_
![screen shot 2015-03-25 at 09 46 50](https://cloud.githubusercontent.com/assets/110251/6822021/6357e464-d2d4-11e4-88da-5907dc87fa4f.png)

_modal appears and shoots below fold_
![screen shot 2015-03-25 at 09 47 05](https://cloud.githubusercontent.com/assets/110251/6822023/662cfbf2-d2d4-11e4-9788-2f101d4d7d50.png)

_modal is there when you scroll down_
![screen shot 2015-03-25 at 09 48 00](https://cloud.githubusercontent.com/assets/110251/6822027/69f3af38-d2d4-11e4-88b8-45ef2de86246.png)

**Comment by vpelipenko** [comment]
@robjmills, we are trying to reproduce this issue locally and have a few questions. Do have any JS errors? Do you use the latest Magento version?

**Comment by robjmills** [comment]
Using Magento version 0.74.0-beta1

No JavaScript errors in the console. The modal does launch, but the position is incorrect. FWIW i'm using Chrome Version 41.0.2272.101 (64-bit) on OSX Yosemite.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-35456

**Comment by robjmills** [comment]
Just to confirm, I still have this bug in 0.74.0-beta2

**Comment by vpelipenko** [comment]
@robjmills, thanks for this update. Internal ticket is not fixed yet. We are going to work on it.

**Comment by sivaschenko** [comment]
@robjmills Are you still able to reproduce this issue?

**Comment by okorshenko** [comment]
Internal ticket MAGETWO-35456 is resolved and delivered to mainline. @robjmills please, reopen this issue if you still able to reproduce this issue.
