### ISSUE TITLE
Minimal price is calculated wrong when custom options is set.

### ISSUE THREAD

**Issue by Kronmose** [magento/magento2#11288]
### Preconditions
Base install with theme.
1.  PHP 5.6
2.  Magento 2.1.7

### Steps to reproduce
After creating a bundle product with necessary attributes etc. we have extra features you can add to the product however not required.

I have set the base price to 50 USD.
Then add ADD 3 custom options with extra fees or free..  
     Option 0: no custom option seleceted only base price.
     Option 1:  0 USD (free)
     Option 2: 10 USD
     Option 3: 30 USD

### Expected result
When visiting the product page as well as catalog page the price of the product should be
displayed as a price-range of 50 to 80 USD or as low as 50 USD depending on selection.
And the as configured price (shown on the product page) is set to 50 until you i.e. select option , 2 or 3

### Actual result
What really happens is
that the catalog page as well as product page displays a price-range of 60 to 80 USD ignoring the custom option which is free. and ignoring the fact that it is allowed to purchase the product at only base price.

**Comment by magento-engcom-team** [comment]
@Kronmose, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
What do you mean "base price"?

> I have set the base price to 50 USD.

If you mean price on main product, than that product should have option "Dynamic Price" = "False".
In this case Magento theme Luma don't show min and max price, shows only main price.
![screenshot_1](https://user-images.githubusercontent.com/31669971/31343420-43d9f89a-ad18-11e7-822b-25f871f07aa1.png)
