### ISSUE TITLE
Password Reset does not work in Magento 2.2.0 in Front- an Backend

### ISSUE THREAD

**Issue by Webroju** [magento/magento2#11287]
You can't reset your passwort in Magento 2.2.0, it does not work in front- and backend.

Server: NGINX, 
PHP:  7.0.9, 
Magento:  2.2.0 Fresh Install without sample data

### Steps to reproduce
1.  Install a new Magento 2.2.0 Version

Backend
2. Create a Backend user (e.g. the normal admin, that you have access to the backend) 
3. Login, Logout, 
4. use Password forgot function, type in your backend user email click "send" and the I get an error an no password email

Frontend
5. Create an account on frontend
6. logout, and use password forgot function
7. type in your email an click get new password and the I get an error an no password email

Actual result in error file
{"0":"Validate class not found from basename 'Magento\\Framework\\Validator\\EmailAddress'","1":"#0 ...
The rest is different depending on the front or back end.

**Comment by magento-engcom-team** [comment]
@Webroju, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by Webroju** [comment]
I found the answer here: https://github.com/magento/magento2/issues/10821
Maybe it helps someone.

**Comment by sangthieu** [comment]
I found some issue. Mage have "password_hash" in both attribute and table customer_entity. So When we reset new password_hash saved in table. but when customer login, password hash get from attribute.
After remove attribute attribute "password_hash", new "password_hash" not saved.
