### ISSUE TITLE
Magento2.2.0 :: Category Not Showing products in frontend after migration 

### ISSUE THREAD

**Issue by mritu19** [magento/magento2#11284]
Hi @magento-engcom-team

I am working on M2.2.0 and have successfully migrated M1.9.1.0 data. But Unfortunately I have the same Problem, I am not able to see any product under category. However, I am able to search the all migrated products and respected product detail page.

Preconditions

Magento 2.2.0

Steps to reproduce

Products assigned to category

Visit category page on front end

Expected result

See grid of all products in the category

Actual result
No any product is coming.

I have around 84.5K products and the product is configurable and simple.

Another Major problem is ::: Configurable product's price is missing. and catalog_product_price indexing is processing from last 2 days.

[Note: I have tried to save 2-3 products thereafter i am able to see those products in respected category in Frontend. but it is not feasible to save 84.5k Products manually again one by one.

I Have also followed several necessary steps which is suggested under community support (Like cache flush, reindexing, isRangingNeeded()->false). But still products is not coming.

Can you please help me regarding the same. Any solution ?

**Comment by mritu19** [comment]
Hi @orlangur  

Can you please help me regarding the above mentioned issue. Any solution ?

**Comment by JerVoo** [comment]
Sounds to me like the indexes haven't updated properly after you've migrated M1 to M2, because the catalog_product_product index has crashed.

Check your PHP error log to see what went wrong at the time the indexers ran, or try clearing the `var/locks` directory and run `php bin/magento indexer:reindex` to see if the error still persists.

**Comment by mritu19** [comment]
Hi @JerVoo 

Thanks for your reply.
I would like to share with you that our mode is  'MAGE_MODE' => 'default' and I have 5 root category which is mapped with 5 respective stores. However, To show the products in frontend, I have Re-mapped the all root category and inserted all root category into one store i.e under "Default Category". Still I am not able to see any product on category's product listing page.

As suggested, I have checked error log But there is no any  "locks" file/folder under "Var", Except one file "migration-tool-progress.lock".

I have many time reset and ran the "php bin/magento indexer:reindex" command. But every time our "catalog_product_price" indexer is remain in "processing mode". I have ran the "php bin/magento indexer:reindex" command for regularly 4 to 5 hours from last 3 days, without interrupting anything (that means during indexer run , I didn't try any process neither in admin nor in frontend).

Yes I have checked only Processlist (SHOW PROCESSLIST) under phpmyadmin. and every time I noticed that there is nothing is going to happen after doing reset and ran re-indexing.

Again, I am not able to see any product in Frontend. 

Can you please help me regarding the above mentioned issue. Any solution ?

**Comment by magento-engcom-team** [comment]
Hi @mritu19 
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by miteshdhaduk** [comment]
I have the same issue on category page after the migration process.

**Comment by Dhara-Shah-Doshi** [comment]
First of all, You need to run the below command after changes items/products:
1  **php bin/magento indexer:reindex**

If still nothing is products are missing or not showing on front-end, need to clear/flush cache:
php bin/magento cache:clean
php bin/magento cache:flush
