### ISSUE TITLE
Magento 2.2 - Cannot save imported products

### ISSUE THREAD

**Issue by robert-schmidt** [magento/magento2#11282]
### Preconditions

1. Magento 2.2
2. Apache2.4 + PHP 7.0.6
3. MariaDB 10.1.3

### Steps to reproduce
1. Go to System > Data Transfer > Import, select Products, click on "Download Sample File".
2. Delete last two rows from the file (shipment_type empty error otherwise).
3. Import the sample file.
4. Go to Catalog > Products, click on one of the imported products.
5. Try to save the product.

### Expected result
1. Product should be saved

### Actual result
`Parse error: syntax error, unexpected '?' in /var/www/public/vendor/zendframework/zend-code/src/Reflection/DocBlock/Tag/VarTag.php on line 69 `

`Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/public/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3864 in /var/www/public/vendor/magento/framework/App/ErrorHandler.php on line 61
`
`Exception: User Error: Some transactions have not been committed or rolled back in /var/www/public/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3864 in /var/www/public/vendor/magento/framework/App/ErrorHandler.php on line 61 `

<img width="1677" alt="screen shot 2017-10-07 at 09 07 22" src="https://user-images.githubusercontent.com/29276521/31305347-5e4a686a-ab40-11e7-8333-a858265f4567.png">

It happen first with an actual import of proper products (who wants to import the sample ones? I did it to make sure my file was not corrupt nor improper formatted and the issue is related to imported products). 

A product created using the admin panel can be saved just fine, it only happens with the imported ones. With every one that I tested.

Thanks.

**Comment by orlangur** [comment]
Oh, that was exactly what we are looking for in https://github.com/magento/magento2/issues/11264.

Could you please provide more details on the way you installed the Magento?

For example, it could happen if you use `composer.lock` generated on PHP 7.1 or did `composer update` with `--ignore-platform-reqs` switch.

**Comment by robert-schmidt** [comment]
You're right. I used composer to install magento and composer.lock was generated using php 7.1, which I use on the CL, but did't bother to make apache use it as well.

Do you have any idea on how to fix this?

Should I re-install magento?

Thanks!

Edit - I will try to use php7.1 in apache - I think that should solve the issue, from what I read on the other topic about nullable return types, introduced in 7.1.

**Comment by orlangur** [comment]
Yeah, you can switch Apache to PHP 7.1, also you can simply regenerate `composer.lock` on a platform with PHP 7.0 (there is no need to reinstall Magento I believe).

Closing as it does not seem to be a Magento issue. Thanks for quick response!
