### ISSUE TITLE
MAGENTO 2.2.x : Class Magento\Framework\Session\SaveHandler contains 1 abstract method 

### ISSUE THREAD

**Issue by phpworld** [magento/magento2#11283]
I FOUND AFTER FRESH INSTALLATION : 

Fatal error: Class Magento\Framework\Session\SaveHandler contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SessionHandlerInterface::) in E:\xampp\htdocs\jespertest\vendor\magento\framework\Session\SaveHandler.php on line 16

**Comment by orlangur** [comment]
Which method is not implemented? Note that XAMPP is not a valid environment and you may face with some oddities.

**Comment by mugua** [comment]
When I run : `php bin/magento setup:di:compile`, meet the same problem:
`Class Magento\Framework\Session\SaveHandler contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SessionHandlerInterface:: ) in *\vendor\magento\framework\Session\SaveHandler.php on line 16`
how to fix it?

**Comment by orlangur** [comment]
@mugua which method is not implemented?

**Comment by magento-engcom-team** [comment]
@mugua Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by orlangur** [comment]
@phpworld @mugua please provide additional details so that this issue can be investigated. Closing for now due to inactivity.

**Comment by magecomp** [comment]
Open this file 
vendor\magento\framework\Session\SaveHandlerInterface.php
Look for 
`interface SaveHandlerInterface extends \SessionHandlerInterface`

Replace it with
`interface SaveHandlerInterface extends \Zend_Session_SaveHandler_Interface`

Try and let us know.

**Comment by xsanza9** [comment]
Hello,

Maybe a  hint, We had this same exact problem after upgrading from PHP 7.1.25 to PHP 7.1.27
Magento version is 2.2.7

Thank you
