### ISSUE TITLE
Magento 2.2 Variant Products Shipping and Advanced Pricing issue

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#11294]
**Preconditions**

Base install with theme.

1. PHP 5.6
2. Magento 2.2

**Steps to reproduce**

- When adding a variant products the advanced pricing option is not shown in main product in admin side and special pricing is not showing in frontend.

- When adding the variant product in cart and going to checkout page no shipping method or customer detail form is visible. 

- Upon adding non variant product along with variant product in cart all the shipping methods and checkout form to add customer details is visible check screenshot 3.

![screenshot 31](https://user-images.githubusercontent.com/13229022/31312796-44e29788-ac19-11e7-9faa-e75e64491192.png)
![screenshot 32](https://user-images.githubusercontent.com/13229022/31312797-44e6c894-ac19-11e7-88e4-dd4d44507ce7.png)
![screenshot 33](https://user-images.githubusercontent.com/13229022/31312798-45028c5a-ac19-11e7-9006-60450127c09c.png)

**Expected result**

Advanced pricing option should appear in main product to add special price for the product, so it can appear in frontend.

Shipping methods and checkout form should be visible upon adding variant product on checkout page.

**Comment by magento-engcom-team** [comment]
@terrybakshi thank you for your report.
Advanced price is not available for main configurable product - only for his options (simple or virtual products.) Shipping methods are not available on checkout in case if options  of configurable product has no weight.

**Comment by magento-engcom-team** [comment]
@terrybakshi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0
