### ISSUE TITLE
The following requested cache types are not supported: 'compiled_config'.

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#11295]
`compiled_config` is the only subclass of `\Magento\Framework\Cache\Frontend\Decorator\TagScope` that does not appear in any `cache.xml` file. Thus the `bin/magento cache:...` commands do not know about it. You cannot flush or clean it, neither can you enable/disable the `compiled_config` cache. However it does appear in `app/etc/env.php` as seen in https://github.com/magento/magento2/issues/4556#issuecomment-220914066 and https://github.com/magento/magento2/issues/4853#issue-158346898 and https://github.com/magento/magento2/issues/5223#issuecomment-229924335 among others.

### Preconditions

1. Magento 2.1.9
2. Magento 2.2-develop

### Steps to reproduce

1. Run `bin/magento cache:enable compiled_config`

### Expected result

```
Changed cache status:
               compiled_config: 0 -> 1
Cleaned cache types:
compiled_config
```

### Actual result (2.1.9)

```

  [InvalidArgumentException]
  The following requested cache types are not supported: 'compiled_config'.
  Supported types: config, layout, block_html, collections, reflection, db_ddl, eav, customer_notification, translate, target_rule, full_page, config_integration, config_integration_api, config_webservice



cache:enable [--bootstrap="..."] [types1] ... [typesN]

```

### Actual result (2.2-develop)
```

  [InvalidArgumentException]
  The following requested cache types are not supported: 'compiled_config'.
  Supported types: config, layout, block_html, collections, reflection, db_ddl, eav, customer_notification, config_integration, config_integration_api, full_page, translate, config_webservice


cache:enable [--bootstrap BOOTSTRAP] [--] [<types>]...
```

**Comment by magento-engcom-team** [comment]
@ajpevers, thank you for your report.
We've created internal ticket(s) MAGETWO-81420 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@ajpevers, thank you for your report.
We've created internal ticket(s) MAGETWO-81420 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81276

**Comment by AntonEvers** [comment]
In M2.3.1:
```
bin/magento cache:enable compiled_config
Changed cache status:
               compiled_config: 0 -> 1
Cleaned cache types:
compiled_config
```
