### ISSUE TITLE
huge performance issue: db media storage fetches and saves each file when viewing files in admin

### ISSUE THREAD

**Issue by ludwig-gramberg** [magento/magento2#11304]
### Preconditions (*)

1. Magento 2.4-develop
2. Media Storage is Database (Stores->Configuration->Advanced->System->Storage Configuration for Media)

### Steps to reproduce (*)

this is a severe performance bottleneck, on each call to the controller listing the directory contents this happens:
1. admin controller gets called
2. Go to Content->Pages
3. Click Add New Page
4. Expand Content, click Insert/Edit Image
5. Select directory with images

### Expected result (*)
we need a better way to identify if files have changed: a checksum or filedate mechanism needs to be implemented. then a file should only be fetched and persisted if it is necessary.

### Actual result (*)
1. all files including their content(!) are being fetched from database (all files, could be gigabytes of data are now in memory and had to be transferred from the db)
2. all files from db are written to folder 

https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php#L287-L295

**Comment by magento-engcom-team** [comment]
@ludwig-gramberg, thank you for your report.
We've created internal ticket(s) MAGETWO-84234 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30345` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @ludwig-gramberg, can you confirm if this problem happens with the New Media Gallery?

Thanks.

**Comment by ludwig-gramberg** [comment]
> Hi @ludwig-gramberg, can you confirm if this problem happens with the New Media Gallery?
> 
> Thanks.

I gave up entirely on magento 2, so I can't help, sry

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
