### ISSUE TITLE
Frontend couldn't load in developer mode after Updating Magento 2.1.9 to 2.2.0

### ISSUE THREAD

**Issue by pgsutariya** [magento/magento2#11303]
I recently update my Magento v2.1.9 to Magento v2.2.0
And i found below kind of error loading frontend.
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'css': This element is not expected.
Line: 660

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'css': This element is not expected.
Line: 660

![](https://i.imgur.com/Y0XjyUS.png)

**Comment by orlangur** [comment]
Please check https://github.com/magento/magento2/issues/11194#issuecomment-333978626 for a solution.
