### ISSUE TITLE
Customer address hidden attributes visible on admin panel after upgrade to Magento 2.2.0

### ISSUE THREAD

**Issue by esimov** [magento/magento2#11301]
### Preconditions

1. Magento 2.2.0
2. PHP 7.1

### Steps to reproduce

After upgrading to Magento 2.2.0 some of the hidden custom attributes associated to customer_address became visible on magento customer address form in backend. Please see the snapshots below.

And here is the code section from the Upgrade script, how it was defined:
```php
$addressAttributes = [
    'is_company_address' => [
        'type' => 'int',
        'label' => 'Is Company Address',
        'input' => 'boolean',
        'required' => true,
        'visible' => false,
        'user_defined' => true,
        'default' => false,
        'system' => false,
        'position' => 100
    ],
    'company_id' => [
        'type' => 'int',
        'label' => 'Company Id',
        'input' => 'text',
        'required' => true,
        'visible' => false,
        'user_defined' => true,
        'default' => null,
        'system' => false,
        'position' => 110
    ]
];
```
You will observe, that `visible` is set to false. 

### Expected result

This is how it should look like:
![screenshot from 2017-10-09 11-28-20](https://user-images.githubusercontent.com/883386/31331273-58c71ca2-acea-11e7-899d-f11e10996fac.png)

### Actual result

![screenshot from 2017-10-09 11-28-11](https://user-images.githubusercontent.com/883386/31331247-487cf2fe-acea-11e7-9128-2bc3d4440dc9.png)

**Comment by galanis-a** [comment]
This is something you wrote? Because a i can't find this in the Magento 2 code.

**Comment by esimov** [comment]
Yes, i specified that these are custom attributes associated to the customer_address. The idea is that, before Magento 2.2.0 this worked as expected, so the custom attribute was not visible on backed.

**Comment by esimov** [comment]
Hi. Any news regarding this issue?

**Comment by magento-engcom-team** [comment]
@esimov, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.
Steps we did:
**With upgrade**:
1. Install latest 2.1.x, which is currently 2.1.9
2. Create custom module with install data which add new attributes(use code reference from **Steps To Reproduce**)
3. Upgrade to 2.2.0

**Without upgrade**:
1. Install 2.2.0
2.2. Create custom module with install data which add new attributes(use code reference from **Steps To Reproduce**)

**Result**: In both scenarios added attributes stay hidden on admin address form.

**Comment by esimov** [comment]
These are all the details I can provide. I have tested both upgrading from 2.1.8 & 2.1.9 to 2.2.0 on different environments, but i received the same result.

**Comment by magento-engcom-team** [comment]
@esimov, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
