### ISSUE TITLE
No specialprice showing on Customer Wishlist

### ISSUE THREAD

**Issue by AmannMax** [magento/magento2#11305]
### Preconditions

1. Magento 2.1.5 - 2.1.8 and new versions.

### Steps to reproduce

1. Setup special price for any product
2. Add this product to wishlist
3. go to wishlist section

### Expected result

1. It should display the special price.
### Actual result

1. Normalprice is shown.

![wishlist](https://user-images.githubusercontent.com/29060188/31335213-e07ceeea-acf1-11e7-8c52-0a593ed08801.PNG)

**Comment by magento-engcom-team** [comment]
@AmannMax, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by duckchip** [comment]
@magento-engcom-team could you provide the PR, or issue where this is fixed?

**Comment by CNanninga** [comment]
@magento-engcom-team - Any word?  Those of us still on 2.1 still need a patch for this.
