### ISSUE TITLE
Search Error Magento 2 - ValidationException - Not expected Element

### ISSUE THREAD

**Issue by AmaxUA** [magento/magento2#11312]
This issue is about an Search error I stumbled upon when setting up a Magento ver. 2.2.0 store.  When trying to search for any string in the default frontend, I get the below described result.

### Preconditions
1. Magento Version 2.2.0 -> fresh install, some extensions installed
2. PHP 7.0.22-1~dotdeb+8.1 (cli) ( NTS ), Apache Server, MySQL DB
3. Migrated Data from Magento 1 Store with LITExtension [http://litextension.com/](url) -> worked, but Order IDs could not be migrated

### Steps to reproduce
1. Any string typed into the default search field results in a white page with an error result
2. Import of many products, customers ect. into magento  2 from magento 1 

### Expected result
1. As usual, when using a search field, the fitting results should be displayed. 

### Actual result

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'update': This element is not expected. Expected is one of ( attribute, block, referenceBlock, referenceContainer, container, move, uiComponent ).
Line: 740

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'update': This element is not expected. Expected is one of ( attribute, block, referenceBlock, referenceContainer, container, move, uiComponent ).
Line: 740

``#0 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/var/www/share/...', '%message%\nLine:...')
#2 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#4 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/View/Model/Layout/Update/Validator.php(125): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<body>\n   <refe...')
#8 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Model\Layout\Merge->load()
#9 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Model\Layout\Merge\Interceptor->___callParent('load', Array)
#10 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Model\Layout\Merge\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/share/dev.shop.de/htdocs/generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php(195): Magento\Framework\View\Model\Layout\Merge\Interceptor->___callPlugins('load', Array, Array)
#12 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge\Interceptor->load()
#13 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#14 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#15 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#16 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/App/View.php(173): Magento\Framework\View\Page\Config->publicBuild()
#17 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#18 /var/www/share/dev.shop.de/htdocs/vendor/magento/module-catalog-search/Controller/Result/Index.php(91): Magento\Framework\App\View->loadLayout()
#19 /var/www/share/dev.shop.de/htdocs/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(24): Magento\CatalogSearch\Controller\Result\Index->execute()
#20 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/App/Action/Action.php(107): Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute()
#21 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#23 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/share/dev.shop.de/htdocs/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(39): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/App/FrontController.php(55): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#28 /var/www/share/dev.shop.de/htdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /var/www/share/dev.shop.de/htdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /var/www/share/dev.shop.de/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#34 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/share/dev.shop.de/htdocs/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#36 /var/www/share/dev.shop.de/htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#37 {main}``

I hope this is enough information, if some other file or information is needed please dont hesitate to ask.

**Comment by orlangur** [comment]
Please check https://github.com/magento/magento2/issues/11194#issuecomment-333978626 for a solution.

**Comment by Kipperlenny** [comment]
same search problem here...

**Comment by orlangur** [comment]
@Kipperlenny please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. Solution for all such XSD violations is similar to https://magento.stackexchange.com/a/199212/40869.
