### ISSUE TITLE
Varnish cache problem with mutli website

### ISSUE THREAD

**Issue by goutamgde** [magento/magento2#11313]
### Preconditions

Magento2.1.7
PHP Version 7.0.24
MySql version 5.6.32
CentOS 6.9 (Final)
Apache
varnishd (varnish-4.0.5 revision 07eff4c29)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2014 Varnish Software AS
### Steps to reproduce

1.  Create two websites "base" and "international", each one have one one store with store view, but have the same base url
2. Enable magento2 by default FPC
3. Configure varnish cache

### Expected result

1. Clear the magento cache and varnish cache.
2. Then suppose customer X request for home page of "base" website then it will show correct home page, and after that if customer Y request for "international" website home page then, it will also show the corresponding home page of "international" website.

### Actual result

After clearing the magento cache and varnish cache suppose customer X request for home page of "base" website then it shows correct home page, but after that if customer Y request for "international" website home page then, it shows "base" website home page. Same thing happen for other cacheable page also.

I switch the website based on user geo location. I have written the below website switching code in index.php

$adminurl = 'admin_xxx';
$params = $_SERVER;
$requested_complete_url = $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
if(!(strpos($requested_complete_url, $adminurl) !== false)){
    $country_code = "IN";

    if(isset($_SERVER["GEOIP_COUNTRY_CODE"]) && !empty($_SERVER["GEOIP_COUNTRY_CODE"])){
      if(!session_id()){
        session_start();
      }
      $_SESSION['COUNTRY_CODE'] = $_SERVER["GEOIP_COUNTRY_CODE"];
      $country_code = $_SERVER["GEOIP_COUNTRY_CODE"];
    }else{
      if(isset($_SESSION['COUNTRY_CODE']) && !empty($_SESSION['COUNTRY_CODE'])){
        $country_code = $_SESSION['COUNTRY_CODE'];
      }
    }

    if(strtoupper($country_code) != "IN"){
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'international'; 
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
    }else{
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'base'; 
        $params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
    }
}
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
/** @var \Magento\Framework\App\Http $app */
$app = $bootstrap->createApplication('Magento\Framework\App\Http');
$bootstrap->run($app);

Also, I observed that, for the page A (those are cacheable) even if request come for different website that same page A, then that request not go to the apache and response send from varnish server to client browser directly.

I want if page A of "base" website already stored in cache, but page A of "international" website till now not store in cache, then when one request come for page A of "international" website, then instead of response send from varnish one request will go to apache for the desire page and then response send to client. But, next time if same page request come for same website then it fetch from cache.

Therefore, I want to know where I need to write the what code so that the above problem will solve.

Or, is there any extra code need to be write in magento2_root_directory/var/varnish.vcl ?

Currently, I used the varnish.vcl what I got from magento2 admin.

Thanks in advance.

**Comment by southerncomputer** [comment]
https://inviqa.com/blog/how-full-page-cache-works-magento-2 

check out GETVARYSTRING and the resultant SHA1 to varnish @ https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/App/Http/Context.php

This is what tells varnish how to differentiate between normal not-logged in user, and say different storesite/different currency. You either need to bring your INTERNATIONAL into the SHA1 routine using your hack or set it in cookie (how the storesite does it) so it includes INTERNATIONAL in the SHA1 routine when present to cause cache segmentation.

**Comment by goutamgde** [comment]
Hi,
Thank you for your reply. I temporarily modify vendor/magento/framework/App/Http::getVaryString() function as below:
public function getVaryString()
    {
        \Magento\Framework\App\ObjectManager::getInstance()->get('\Psr\Log\LoggerInterface')->emergency('vary-string:' . implode(',', $this->data));
        $data = $this->getData();
        if (!empty($data)) {
            ksort($data);

\Magento\Framework\App\ObjectManager::getInstance()->get('\Psr\Log\LoggerInterface')->emergency('resultant sha1:' . sha1(serialize($data)));

            return sha1(serialize($data));
        }
        return null;
    }

Then in var/log/system.log I got output like below:

[2017-10-10 09:06:55] main.EMERGENCY: vary-string:theme_color_1,default,60710a24b04d17addbf679017e773e11,0,,INR [] []
[2017-10-10 09:06:55] main.EMERGENCY: resultant sha1:1097db911e5c33fc62b50a7191f3740a8709b37c [] []
[2017-10-10 09:06:56] main.EMERGENCY: vary-string:theme_color_1,default,60710a24b04d17addbf679017e773e11,0,,INR [] []
[2017-10-10 09:06:56] main.EMERGENCY: resultant sha1:1097db911e5c33fc62b50a7191f3740a8709b37c [] []
[2017-10-10 09:12:46] main.EMERGENCY: vary-string:theme_color_1,international_store_view,60710a24b04d17addbf679017e773e11,0,,GBP [] []
[2017-10-10 09:12:46] main.EMERGENCY: resultant sha1:b044bdd19fc6b3160a8d90ec745b48c51512081f [] []


But, when I closely observe the above log file outputs after accessing different pages from different geo location, I found that, for the page A (those are cacheable) even if request come form "international" website that same page A, then that request not go to the magento and response send from varnish server to client browser directly (if "base" website's page A already stored in varnish cache) and vice versa.

I am requesting you could you describe more about your below comment,
"You either need to bring your INTERNATIONAL into the SHA1 routine using your hack or set it in cookie (how the storesite does it) so it includes INTERNATIONAL in the SHA1 routine when present to cause cache segmentation."

**Comment by southerncomputer** [comment]
Are the users logged in? Have they received their cookie for X-MAGENTO-VARY?
clear your browser cache and cookies and try to map out each step.
1st visit -? do they get cookies? X-MAGENTO-VARY? when?
2nd Visit -? ditto
Change store - clear cookies/cache - repeat ?

**Comment by goutamgde** [comment]
I switch the website based on user geo location, not whether the user logged in or not.

My concept is simple, if any user try to access my website from inside India that user redirect to "base" website(which is default website) and if any user try to access my website from outside India that user redirect to "international" website. Both the website have same base URL. But have different display currency.

As we know apache, magento and varnish configuration works like below:
[CLIENT] ---> [APACHE] --> [VARNISH] ---> [MAGENTO CODE]

Here any one can reproduce the problem by following below steps:
Step1: Clear the magento and varnish cache.
Step2: One user from outside India try to access any cacheable page e.g. homepage then that user request goes to Apache -> Varnish->Magento (as till now that page not stored in cache). Then user receive response from Apache and user see "international" website.
Step3: Next time any other user try to access the previous page from inside India. Then now flow happen like below:

 **Request flow: Client browser -> Apache -> Varnish
 Response flow: Varnish -> Apache -> Client browser**

**No request goes to magento at all.**
So, the Indian user also force to see "international" website page instead of "base" website page.

Same thing happen for any other cacheable page also. That means, suppose page A first access happen for X website then in Y website customer also force to see X website page A instead of Y website page A. because that page A( irrespective of website X or Y ) already stored in varnish cache first.

In apache configuration file I write below code to detect user geo location

<IfModule !mod_maxminddb.c>
MaxMindDBEnable On
MaxMindDBFile COUNTRY_DB /usr/share/GeoIP/GeoLite2-Country.mmdb
MaxMindDBEnv COUNTRY_CODE COUNTRY_DB/country/iso_code
</IfModule>

And also I see in varnish log user location come correctly each time user visit my website. Here is the sample varnish log:
*   << BeReq    >> 262165    
-   Begin          bereq 262164 fetch
-   Timestamp      Start: 1507641938.646902 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /collections/stanford.html
-   BereqProtocol  HTTP/1.1
-   BereqHeader    Host: XXX.com
-   BereqHeader    Upgrade-Insecure-Requests: 1
-   BereqHeader    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.35
-   BereqHeader    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
-   BereqHeader    Referer: https://XXX.com/inks-and-refills.html
-   BereqHeader    Accept-Language: en-US,en;q=0.8
-   BereqHeader    Cookie: mage-translation-storage=%7B%7D; mage-translation-file-version=%7B%7D; mage-cache-storage=%7B%7D; mage-cache-storage-section-invalidation=%7B%7D; mage-cache-sessid=true; mage-messages=
-   BereqHeader    GEOIP_ADDR: 182.156.92.142
-   BereqHeader    GEOIP_CONTINENT_CODE: AS
-   BereqHeader    GEOIP_COUNTRY_CODE: IN
-   BereqHeader    GEOIP_COUNTRY_NAME: India
-   BereqHeader    X-Forwarded-Proto: https
-   BereqHeader    X-Forwarded-Host: XXX.com
-   BereqHeader    X-Forwarded-Server: XXX.com
-   BereqHeader    X-Forwarded-For: 182.156.92.142, 127.0.0.1, 127.0.0.1
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    X-Varnish: 262165
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   BackendClose   26 default(127.0.0.1,::1,8080) toolate
-   BackendClose   19 default(127.0.0.1,::1,8080) toolate
-   BackendClose   25 default(127.0.0.1,::1,8080) toolate
-   BackendClose   20 default(127.0.0.1,::1,8080) toolate
-   BackendClose   24 default(127.0.0.1,::1,8080) toolate
-   BackendClose   16 default(127.0.0.1,::1,8080) toolate
-   BackendOpen    16 default(127.0.0.1,::1,8080) 127.0.0.1 50799 
-   Backend        16 default default(127.0.0.1,::1,8080)
-   Timestamp      Bereq: 1507641938.647109 0.000207 0.000207
-   Timestamp      Beresp: 1507641939.826915 1.180014 1.179806
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Date: Tue, 10 Oct 2017 13:25:38 GMT
-   BerespHeader   Server: Apache
-   BerespHeader   Pragma: cache
-   BerespHeader   Cache-Control: max-age=86400, public, s-maxage=86400
-   BerespHeader   Expires: Wed, 11 Oct 2017 13:25:39 GMT
-   BerespHeader   X-Magento-Tags: catalog_category,catalog_category_3,catalog_category_4,catalog_category_5,catalog_category_6,catalog_category_7,store,cms_block,cms_block_footer_col_1,cms_block_footer_col_2,catalog_category_14,catalog_category_product_14,catalog_product_
-   BerespHeader   X-Content-Type-Options: nosniff
-   BerespHeader   X-XSS-Protection: 1; mode=block
-   BerespHeader   X-Frame-Options: SAMEORIGIN
-   BerespHeader   Set-Cookie: mage-cache-sessid=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
-   BerespHeader   Set-Cookie: PHPSESSID=20up39lvrhvdvbuivsortt2t92; expires=Tue, 10-Oct-2017 14:25:39 GMT; Max-Age=3600; path=/; domain=XXX.com; HttpOnly
-   BerespHeader   Set-Cookie: mage-messages=%5B%5D; expires=Wed, 10-Oct-2018 13:25:39 GMT; Max-Age=31536000; path=/
-   BerespHeader   Set-Cookie: X-Magento-Vary=1097db911e5c33fc62b50a7191f3740a8709b37c; path=/; secure; HttpOnly
-   BerespHeader   Transfer-Encoding: chunked
-   BerespHeader   Content-Type: text/html; charset=UTF-8
-   TTL            RFC 86400 -1 -1 1507641940 1507641940 1507641938 1507728339 86400
-   VCL_call       BACKEND_RESPONSE
-   BerespUnset    Set-Cookie: mage-cache-sessid=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
-   BerespUnset    Set-Cookie: PHPSESSID=20up39lvrhvdvbuivsortt2t92; expires=Tue, 10-Oct-2017 14:25:39 GMT; Max-Age=3600; path=/; domain=XXX.com; HttpOnly
-   BerespUnset    Set-Cookie: mage-messages=%5B%5D; expires=Wed, 10-Oct-2018 13:25:39 GMT; Max-Age=31536000; path=/
-   BerespUnset    Set-Cookie: X-Magento-Vary=1097db911e5c33fc62b50a7191f3740a8709b37c; path=/; secure; HttpOnly
-   BerespUnset    Pragma: cache
-   BerespHeader   Pragma: no-cache
-   BerespUnset    Expires: Wed, 11 Oct 2017 13:25:39 GMT
-   BerespHeader   Expires: -1
-   BerespUnset    Cache-Control: max-age=86400, public, s-maxage=86400
-   BerespHeader   Cache-Control: no-store, no-cache, must-revalidate, max-age=0
-   TTL            VCL 86400 60 0 1507641940
-   VCL_return     deliver
-   BerespHeader   Content-Encoding: gzip
-   Storage        malloc s0
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Date: Tue, 10 Oct 2017 13:25:38 GMT
-   ObjHeader      Server: Apache
-   ObjHeader      X-Magento-Tags: catalog_category,catalog_category_3,catalog_category_4,catalog_category_5,catalog_category_6,catalog_category_7,store,cms_block,cms_block_footer_col_1,cms_block_footer_col_2,catalog_category_14,catalog_category_product_14,catalog_product_
-   ObjHeader      X-Content-Type-Options: nosniff
-   ObjHeader      X-XSS-Protection: 1; mode=block
-   ObjHeader      X-Frame-Options: SAMEORIGIN
-   ObjHeader      Content-Type: text/html; charset=UTF-8
-   ObjHeader      Pragma: no-cache
-   ObjHeader      Expires: -1
-   ObjHeader      Cache-Control: no-store, no-cache, must-revalidate, max-age=0
-   ObjHeader      Content-Encoding: gzip
-   Fetch_Body     2 chunked -
-   Gzip           G F E 105168 13884 80 110992 111002
-   BackendReuse   16 default(127.0.0.1,::1,8080)
-   Timestamp      BerespBody: 1507641939.848744 1.201842 0.021829
-   Length         13884
-   BereqAcct      938 0 938 1297 105276 106573
-   End 


Now I want to know what code need to write in varnish configutaion file var/default.vcl , so that varnish can able to distinguish between "base" website page A and "international" website page "A" where both website share same base URL? And accordingly it send the request to magento or not for new page of a website.

Or what code need to write in magento or apache level so that I can solve this problem.

**Comment by southerncomputer** [comment]
https://serverfault.com/questions/547225/how-to-enable-geoip-on-magento-with-varnish-page-cache

you want to do the geo-ip in varnish so it can hash a cookie first!

**Comment by goutamgde** [comment]
As GEOIP_COUNTRY_CODE already appear in my varnish log, so I add below code in my varnish configuration  var/default.vcl and it works.

sub vcl_hash {
    if(req.http.GEOIP_COUNTRY_CODE){
       hash_data(req.http.GEOIP_COUNTRY_CODE);
    }
}

Thank you very much for your valuable help. Now you can close this issue.
