### ISSUE TITLE
Problems with Magento2 installed today, March 26, 2015

### ISSUE THREAD

**Issue by muralikrishnab** [magento/magento2#1131]
Installed from https://github.com/magento/magento2.git today, Mar 26 on CentOS - Apache 2.2/2.4 PHP 5.6 and MySQL 

After install homepage doesn't have any styles or images - http://joxi.ru/Vm6ko9ni7oWG2Z.

Same issue exist when i open admin panel.

Please assist.

**Comment by muralikrishnab** [comment]
RequireJS not connecting or loading Frontend file - so After install homepage doesn't have any styles or images --- WHAT TO DO NOW?

**Comment by Antiseptikk** [comment]
if you got 404, try to change your apache options with :

`Options Indexes FollowSymLinks MultiViews`

**Comment by grepdirect** [comment]
I have installed magento2  from github yesterday, and with php 5.5 and mysql 5.7. The installation is completed and my magento is perfectly work.
I'm on Debian wheezy
![2015-03-26 12_26_25-dashboard _ magento admin](https://cloud.githubusercontent.com/assets/11654924/6845309/75374e1a-d3b3-11e4-8831-bbaeeef17084.jpg)

**Comment by muralikrishnab** [comment]
That is great, grepdirect. In my case, I am on Apache 2.2 on CentOS. This is Apache problem really - not Magento2 installation problem.

**Comment by vpelipenko** [comment]
@Antiseptikk, do you still have this problem?

**Comment by muralikrishnab** [comment]
This is not Antiseptikk's problem. This is my problem. Yes. The problem is still there. I am looking at Apache configuration for answers.

**Comment by vpelipenko** [comment]
@muralikrishnab, oh... sorry for that :-). What happens if you try to get CSS directly from page source? You also should have write permissions for pub/static folder.

**Comment by muralikrishnab** [comment]
It is working now. Problem was with Apache configuration/ permissions and options etc. Hope that helps. Thanks all.

**Comment by vpelipenko** [comment]
Great, can we close this ticket?
