### ISSUE TITLE
Possible issue with custom module

### ISSUE THREAD

**Issue by Antiseptikk** [magento/magento2#1132]
I try to create a little module (just display Hello World) in dev RC and when I return on the home page I got this message:

`Setup version for module 'Magento_HelloWorld' is not specified`

Do you know how can I fix this ?
Thanks

**Comment by vpelipenko** [comment]
@Antiseptikk, your new module should have etc/module.xml file, where setup version should be specified.

**Comment by Antiseptikk** [comment]
@vpelipenko i have etc/module.xml with :
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd"> 
    <module name="Magento_HelloWorld" setup_version="2.0.0" />  
</config>
```
but i got the message

**Comment by vpelipenko** [comment]
Could you try to clear cache? Or just remove var/cache folder. It can help you.

**Comment by Antiseptikk** [comment]
@vpelipenko yes but it's not working

**Comment by maksek** [comment]
@Antiseptikk, it must work. But you also can try do next
``` 
php -f [you magento2 root]/setup/index.php update
```

**Comment by vpelipenko** [comment]
@Antiseptikk, please, take a look at our Developer Guide http://devdocs.magento.com/guides/v1.0/extension-dev-guide/create_module.html to make sure that you create module as described. I tried to do the same and it works for me.

**Comment by mzaroui** [comment]
I had the same problem and I fixed it using the command "php -f [you magento2 root]/setup/index.php update" thanks @maksek. 
In case of a new module this command will insert a new line in "setup_module" table with the setup_version sepcified in module.xml file

**Comment by SyedMuneebb** [comment]
Maybe you have missed any step in creating custom module. Here's a step by step guide: [Create Hello World module in Magento 2.](https://magenticians.com/create-module-in-magento-2/)
