### ISSUE TITLE
TinyMCE adds id after image url and break image path

### ISSUE THREAD

**Issue by rehoehle** [magento/magento2#11330]
### Preconditions
1. PHP 7.0.22
2. Magento 2.1.7

### Steps to reproduce

We could reproduce the problem now. I've added some screenshots with steps. 

The link after inserting the image looks like this: 

`<img src="{{media url="wysiwyg/media/171xxxxxx.JPG"}}id/3/" width="531" height="275" />`

so the "id/3/" is added after the src and break the url. If you delete it it's working again. Does anyone of you had that problem before?

### Edit: Screens to reproduce

![step 1](https://user-images.githubusercontent.com/223007/31382412-e376c438-adb7-11e7-965b-2b341fb2b020.png)
![step 2](https://user-images.githubusercontent.com/223007/31382413-e3b0e1d6-adb7-11e7-9b43-707a5a0f9538.png)
![step 3](https://user-images.githubusercontent.com/223007/31382414-e3d5b54c-adb7-11e7-9b0b-3174969a21ec.png)
![step 4](https://user-images.githubusercontent.com/223007/31382415-e4009cb2-adb7-11e7-85a5-a3a49f40c4f7.png)
![step 5](https://user-images.githubusercontent.com/223007/31382416-e42c6d6a-adb7-11e7-9ec7-4d1b200c308c.png)

**Comment by rehoehle** [comment]
@magento-engcom-team I've updated the complete steps and we could reproduce the problem.

**Comment by magento-engcom-team** [comment]
@rehoehle, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by rehoehle** [comment]
Thx. we will update to the latest version and try it.
