### ISSUE TITLE
Magento2.2.0 :: Child categories Product not coming in frontend and configurable price is not editable

### ISSUE THREAD

**Issue by mritu19** [magento/magento2#11339]
Hi @magento-engcom-team

I am working on M2.2.0 and have successfully migrated M1.9.1.0 data. But Unfortunately I have the same Problem, I am not able to see any product under category. However, I am able to search the all migrated products and respected product detail page.

Preconditions

Magento 2.2.0

**Steps to reproduce**

Products is already assigned to categories and subcategories (After data migration from M1).

check screenshot below ::

![all-category-and-products](https://user-images.githubusercontent.com/32297749/31387723-06bcf9e0-ade9-11e7-8f5c-dd1a5b35625b.PNG)

Also Configurable product price is displaying in  product Grid 

check screenshot below ::

![configurable-product-priceall](https://user-images.githubusercontent.com/32297749/31387483-3c1479ca-ade8-11e7-8337-60958225a149.PNG)

But that price is not coming when I open any configurable product and see the price. 
Check below

![configurable-product-price-not-editable](https://user-images.githubusercontent.com/32297749/31387577-83a99fae-ade8-11e7-8f7c-bdd7e5d62acc.PNG)

Visit category page on front end

**Expected result**

See grid of all products in the category

Actual result
No any product is coming.

I have around 84.5K products and the product is configurable and simple.

[Note: I have tried to save some products and have added "Default Category" under category mapping. thereafter i am able to see those products in respected category in Frontend. but it is not feasible to save 84.5k Products manually again one by one.

I Have also followed several necessary steps which is suggested under community support (Like cache flush, reindexing, isRangingNeeded()->false). But still products is not coming.

Can you please help me regarding the same. Any solution ?

**Comment by magento-engcom-team** [comment]
@mritu19, thank you for your report.
We've created internal ticket(s) MAGETWO-82395 to track progress on the issue.

**Comment by hallleron** [comment]
I also have this behaviour. Additionally some products lost ALL **upselling** products after upgrading from 2.19 to 2.2.0.

Other configurable products lost their simple products and the price changed to null WITHOUT having the price input field disabled (it is not greyed out).

I also did all necessary steps without any success. So basically the upgrade broke my entire product catalog.

Are there any news on this issue?

**Comment by magento-engcom-team** [comment]
@mritu19, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
