### ISSUE TITLE
Knockout.js getCountryNam() returning nothing

### ISSUE THREAD

**Issue by stevenlavine** [magento/magento2#11331]
### Preconditions

1. Magento 2.1.9
2. MySQL 5.7
3. PHP 7.x
4. Apache 2.4

### Steps to reproduce

1. Add product to basket
2. Go to checkout
3. Proceed as guest
4. Enter shipping address
5. Click Next

### Expected result

1. Ship to should show full address including country
2. Billing address (within payment method) should show country

### Actual result

1. No country displayed in address

![image](https://user-images.githubusercontent.com/910649/31380807-5d7116b6-adaa-11e7-899d-0aeb2349130d.png)

**Comment by magento-engcom-team** [comment]
@stevenlavine Unfortunately, I could not reproduce the issue as you described it.

**Comment by magento-engcom-team** [comment]
@stevenlavine, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
