### ISSUE TITLE
Admin url not found - Magento 2.2

### ISSUE THREAD

**Issue by K-Projects** [magento/magento2#11338]
After running the setup wizard for Magento 2.2, it's not possible to go to the admin login page.

Steps to reproduce
1. Download Magento 2.2 from github
2. Run composer install in root folder Magento project
3. Run setup wizard -> set admin url to "admin"
4. Go to the admin url (magento-project.com/admin)

Expected result
1. Show the login screen for the admin.

Actual result

![screen shot 2017-10-10 at 14 38 11](https://user-images.githubusercontent.com/28588493/31386905-c5ab1394-adc8-11e7-9a0a-c9b5b6ae6a7b.png)

**Comment by magento-engcom-team** [comment]
@K-Projects, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
