### ISSUE TITLE
Unable to run commands using SSH magento 2.2.0

### ISSUE THREAD

**Issue by Otatti** [magento/magento2#11340]
Hi everyone. I was using magento 2.1.8. My intention was to upgrade to 2.2.0 but i didnt want to update directly. So i upgraded to magento 2.1.9 through the admin set up first. The upgrade was smooth and fast. I then decided to go for 2.2.0 but the upgrade failed and thats where my problem began. I attemped a rollback but it didnt work. My site was now inaccesible from the front end and the admin. I got frustrated and eventually deleted my site. I then reinstalled it. The problem now is that i am unable to run commands through ssh.

### Preconditions
I am hosted on siteground shared hosting (startup plan).
 magento 2.2.0
1. 
2. 

### Steps to reproduce
After i deleted my site, i did a fresh install of 2.2.0 using softaculous. 

### Expected result
1. I expected to be able to work on my site

### Actual result
1. i got the 500 error message and left it for about 3 hours
2. after about 3 hours the website came up. the frontend and admin was loading
3. but when i tried to reindex my site, i got the following message:
Magento supports 7.0.2, 7.0.4, and 7.0.6 or later. Please read http://devdocs.magento.com/guides/v1.0/install-gde/system-requirements.htmlxxxxx@xxxxxx

**Comment by orlangur** [comment]
> but when i tried to reindex my site, i got the following message:
> Magento supports 7.0.2, 7.0.4, and 7.0.6 or later. Please read 

You need to upgrade PHP to version 7.0 or higher as PHP 5.x support was dropped in Magento 2.2.

**Comment by Otatti** [comment]
Thanks for your quick response. I am on a shared hosting plan and unable to upgrade the PHP version. However, Siteground provides a php version manager and I was able to change the PHP version of my magento root folder and sub folders. The problem is still there. unable to run commands through ssh.

**Comment by Otatti** [comment]
But if magento 2.2.0 only works on PHP 7 and above, why is the frontend and admin area of my website loading?

**Comment by orlangur** [comment]
I have no idea, probably due to upgrade fail your store is running in 2.1.9 semi-upgraded state now. Or your local env is using PHP7 for web server but PHP5 for CLI.

Anyway this seems to be a problem of your particular environment and not a Magento issue.

**Comment by Otatti** [comment]
So would you advise that I downgrade to a 2.1.9?

**Comment by orlangur** [comment]
If you cannot have PHP7 on your env - yes, there is no other option.

Otherwise check http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html carefully and then upgrade should not cause any troubles. Note that PHP5 is somewhat x2-3 times slower, so, it is a good idea to use PHP7 even if you stay on Magento 2.1.x.

**Comment by Otatti** [comment]
@orlangur Thanks. I think I have solved it. You were right. The server was using PHP5 for the CLI. I contacted the support team in siteground and they provided a solution. Would drop it here in case any newbie like me encounters such.

Normally, I use "php bin/magento indexer:reindex" for re-indexing in my root folder.
But now i have been advised to use this instead; /usr/local/php70/bin/php-cli bin/magento indexer:reindex. The "/usr/local/php70/bin/php-cli" command line directs the server to use PHP7

**Comment by orlangur** [comment]
Cool 👍 PHP version is an easiest part to spot, sometimes you have to find the divergence between extensions enabled, in such case `php -i` may be helpful or call `phpinfo();` if accessing Magento via web server.

**Comment by scholtz** [comment]
yet another magento bug not notifying user that he is using old PHP.. be aware that if you use PHP7.1 cli, and 7.0 in webserver, magento will be in unstable state without telling you.. (You can get white screen of death on unexpected places (php parse error)) and magento team does not think it is a bug :)

**Comment by orlangur** [comment]
> magento will be in unstable state without telling you..

This statement is wrong. Just use Composer properly, Magento cannot do it by itself.

**Comment by scholtz** [comment]
the statement is not wrong.. if you do clean install using composer on php7.1 cli, magento on php-fpm7.0 is in unstable way. and magento will not notify user. mr. orlangur tagged it as not a bug here https://github.com/magento/magento2/issues/11300 and here https://github.com/magento/magento2/issues/11264

**Comment by orlangur** [comment]
> if you do clean install using composer on php7.1 cli, magento on php-fpm7.0 is in unstable way

And if you try running under PHP 5.6, it will fail as well. There is nothing to discuss here, if you treat it as a bug - prepare a pull request for consideration, maybe I'm not seeing an obvious way to "fix" this.

**Comment by PauloBoaventura** [comment]
E como trocar via ssh?
Já que no meu painel troquei para 7.1, mas quando dei o comando: php -i
Disse que estava com = PHP Version => 5.4.16
