### ISSUE TITLE
Search term in admin grid column filter is replaced with unicode characters

### ISSUE THREAD

**Issue by mtpbold** [magento/magento2#11343]
Search term in admin grid column filter is replaced with unicode characters. This happens in attribute set and attribute grid.

### Preconditions

Magento 2.2
PHP 7.0
Mysql 5.7
Attributes (attribute sets) with numeric codes

### Steps to reproduce

Go to Attribute Set grid in Admin Panel and try to filter by name. Type one digit in the filter and change sorting direction.

### Expected result

Do not change searched value

### Actual result

Unicode characters are added as suffixes
![bug_grid](https://user-images.githubusercontent.com/30075291/31390360-f5d7c318-add3-11e7-9b70-6011b7a77f3e.png)

**Comment by magento-engcom-team** [comment]
@mtpbold, thank you for your report.
We've created internal ticket(s) MAGETWO-81460 to track progress on the issue.

**Comment by crissanclick** [comment]
¿Can I work on this issue? Thanks,

**Comment by tuyennn** [comment]
@magento-engcom-team any update on this bug?

**Comment by engcom-Delta** [comment]
@tuyennn Unfortunately, I am not able to reproduce issue by steps you described on 2.4-develop 
![#11343Issue](https://user-images.githubusercontent.com/51681379/71467586-0641ab00-27cc-11ea-8f05-a3e4b0735365.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
