### ISSUE TITLE
Magento 2.1.9 Indexer. Catalog Product Flat indexing Error

### ISSUE THREAD

**Issue by Tonop** [magento/magento2#11344]
### Preconditions

Magento: 2.1.9
PHP: 5.6.26
MySQL: 14.14 Distrib 5.7.15

### Steps to reproduce

1. php bin/magento indexer:reindex
2. 
3. 

### Expected result

1. No errors, 
2. Catalog Product Flat Data has been rebuild successfull

### Actual result

1. Catalog Product Flat Data error
2. Log:
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs, query was: CREATE TABLE IF NOT EXISTS `catalog_product_flat_1_tmp_indexer` (
  `entity_id` int UNSIGNED NOT NULL COMMENT 'Entity Id' ,
  `attribute_set_id` smallint UNSIGNED NOT NULL default '0' COMMENT 'Attribute Set ID' ,
  `type_id` varchar(32) NOT NULL default 'simple' COMMENT 'Type Id' ,
  `activity` varchar(255) NULL COMMENT 'activity column' ,
  `beams_amount` varchar(255) NULL COMMENT 'beams_amount' ,
  `category_gear` varchar(255) NULL COMMENT 'category_gear column' ,
  `climate` varchar(255) NULL COMMENT 'climate column' ,
  `collar` varchar(255) NULL COMMENT 'collar column' ,
  `color` int NULL COMMENT 'color column' ,
  `color_value` varchar(255) NULL COMMENT 'color column' ,
  `connection_type` int NULL COMMENT 'connection_type column' ,
  `connection_type_value` varchar(255) NULL COMMENT 'connection_type column' ,
  `connector_beam_number` int NULL COMMENT 'connector_beam_number column' ,
  `connector_beam_number_value` varchar(255) NULL COMMENT 'connector_beam_number column' ,
  `cost` decimal(12,4) NULL COMMENT 'cost' ,
  `created_at` timestamp NOT NULL COMMENT 'created_at' ,
  `description` longtext NULL COMMENT 'description' ,
  `eco_collection` smallint NULL COMMENT 'eco_collection column' ,
  `energy_consumption` int NULL COMMENT 'energy_consumption column' ,
  `energy_consumption_value` varchar(255) NULL COMMENT 'energy_consumption column' ,
  `erin_recommends` smallint NULL COMMENT 'erin_recommends column' ,
  `features_bags` varchar(255) NULL COMMENT 'features_bags column' ,
  `format` int NULL COMMENT 'format column' ,
  `format_value` varchar(255) NULL COMMENT 'format column' ,
  `form_factor` varchar(255) NULL COMMENT 'form_factor column' ,
  `frequency` int NULL COMMENT 'frequency column' ,
  `frequency_value` varchar(255) NULL COMMENT 'frequency column' ,
  `gender` varchar(255) NULL COMMENT 'gender column' ,
  `gift_message_available` smallint NULL COMMENT 'gift_message_available column' ,
  `has_options` smallint NOT NULL default '0' COMMENT 'has_options' ,
  `image` varchar(255) NULL COMMENT 'image' ,
  `image_label` varchar(255) NULL COMMENT 'image_label' ,
  `lifitime` varchar(255) NULL COMMENT 'lifitime column' ,
  `links_exist` int NULL COMMENT 'links_exist' ,
  `links_purchased_separately` int NULL COMMENT 'links_purchased_separately' ,
  `links_title` varchar(255) NULL COMMENT 'links_title' ,
  `maximum_output_voltage` varchar(255) NULL COMMENT 'maximum_output_voltage column' ,
  `msrp` decimal(12,4) NULL COMMENT 'msrp' ,
  `msrp_display_actual_price_type` text NULL COMMENT 'msrp_display_actual_price_type' ,
  `name` varchar(255) NULL COMMENT 'name' ,
  `new` smallint NULL COMMENT 'new column' ,
  `news_from_date` datetime NULL COMMENT 'news_from_date' ,
  `news_to_date` datetime NULL COMMENT 'news_to_date' ,
  `number_of_rooms` int NULL COMMENT 'number_of_rooms column' ,
  `number_of_rooms_value` varchar(255) NULL COMMENT 'number_of_rooms column' ,
  `pattern` varchar(255) NULL COMMENT 'pattern column' ,
  `performance_fabric` smallint NULL COMMENT 'performance_fabric column' ,
  `phase_number` int NULL COMMENT 'phase_number column' ,
  `phase_number_value` varchar(255) NULL COMMENT 'phase_number column' ,
  `price` decimal(12,4) NULL COMMENT 'price' ,
  `price_type` int NULL COMMENT 'price_type' ,
  `price_view` int NULL COMMENT 'Bundle Price View price_view column' ,
  `required_options` smallint UNSIGNED NOT NULL default '0' COMMENT 'required_options' ,
  `sale` smallint NULL COMMENT 'sale column' ,
  `sensor_feature` varchar(255) NULL COMMENT 'sensor_feature column' ,
  `sf_arm_reject` smallint NULL COMMENT 'sf_arm_reject column' ,
  `sf_driver` smallint NULL COMMENT 'sf_driver column' ,
  `sf_ir_transmittance` varchar(255) NULL COMMENT 'sf_ir_transmittance column' ,
  `sf_operation_mode` int NULL COMMENT 'sf_operation_mode column' ,
  `sf_operation_mode_value` varchar(255) NULL COMMENT 'sf_operation_mode column' ,
  `sf_rated_voltage` varchar(255) NULL COMMENT 'sf_rated_voltage column' ,
  `sf_technology` int NULL COMMENT 'sf_technology column' ,
  `sf_technology_value` varchar(255) NULL COMMENT 'sf_technology column' ,
  `sf_thickness` int NULL COMMENT 'sf_thickness column' ,
  `sf_thickness_value` varchar(255) NULL COMMENT 'sf_thickness column' ,
  `sf_tl_transmittance` varchar(255) NULL COMMENT 'sf_tl_transmittance column' ,
  `sf_total_obsturct` varchar(255) NULL COMMENT 'sf_total_obsturct column' ,
  `sf_type` int NULL COMMENT 'sf_type column' ,
  `sf_type_value` varchar(255) NULL COMMENT 'sf_type column' ,
  `sf_uv_transmittance` varchar(255) NULL COMMENT 'sf_uv_transmittance column' ,
  `sf_viewing_angel` int NULL COMMENT 'sf_viewing_angel column' ,
  `sf_viewing_angel_value` varchar(255) NULL COMMENT 'sf_viewing_angel column' ,
  `shell_delivery_form` int NULL COMMENT 'shell_delivery_form column' ,
  `shell_delivery_form_value` varchar(255) NULL COMMENT 'shell_delivery_form column' ,
  `shell_thickness` int NULL COMMENT 'shell_thickness column' ,
  `shell_thickness_value` varchar(255) NULL COMMENT 'shell_thickness column' ,
  `short_description` longtext NULL COMMENT 'short_description' ,
  `size` int NULL COMMENT 'size column' ,
  `size_value` varchar(255) NULL COMMENT 'size column' ,
  `sku` varchar(64) NULL COMMENT 'sku' ,
  `sku_type` int NULL COMMENT 'sku_type' ,
  `sleeve` varchar(255) NULL COMMENT 'sleeve column' ,
  `small_image` varchar(255) NULL COMMENT 'small_image' ,
  `small_image_label` varchar(255) NULL COMMENT 'small_image_label' ,
  `span` int NULL COMMENT 'span column' ,
  `span_value` varchar(255) NULL COMMENT 'span column' ,
  `special_from_date` datetime NULL COMMENT 'special_from_date' ,
  `special_price` decimal(12,4) NULL COMMENT 'special_price' ,
  `special_to_date` datetime NULL COMMENT 'special_to_date' ,
  `strap_bags` varchar(255) NULL COMMENT 'strap_bags column' ,
  `style_bags` varchar(255) NULL COMMENT 'style_bags column' ,
  `style_bottom` varchar(255) NULL COMMENT 'style_bottom column' ,
  `style_general` varchar(255) NULL COMMENT 'style_general column' ,
  `swatch_image` varchar(255) NULL COMMENT 'swatch_image' ,
  `tax_class_id` int UNSIGNED NULL COMMENT 'tax_class_id tax column' ,
  `technology` varchar(255) NULL COMMENT 'technology column' ,
  `thumbnail` varchar(255) NULL COMMENT 'thumbnail' ,
  `thumbnail_label` varchar(255) NULL COMMENT 'thumbnail_label' ,
  `timber_max_lenght` varchar(255) NULL COMMENT 'timber_max_lenght' ,
  `timber_min_lenght` varchar(255) NULL COMMENT 'timber_min_lenght' ,
  `timber_size` int NULL COMMENT 'timber_size column' ,
  `timber_size_value` varchar(255) NULL COMMENT 'timber_size column' ,
  `timber_type` int NULL COMMENT 'timber_type column' ,
  `timber_type_value` varchar(255) NULL COMMENT 'timber_type column' ,
  `translate_wifi_to` varchar(255) NULL COMMENT 'translate_wifi_to column' ,
  `translate_zwave_to` varchar(255) NULL COMMENT 'translate_zwave_to column' ,
  `tube_size` int NULL COMMENT 'tube_size column' ,
  `tube_size_value` varchar(255) NULL COMMENT 'tube_size column' ,
  `type_of_access_control` varchar(255) NULL COMMENT 'type_of_access_control column' ,
  `type_of_control` varchar(255) NULL COMMENT 'type_of_control column' ,
  `type_of_controller` varchar(255) NULL COMMENT 'type_of_controller column' ,
  `type_of_lighting_and_app` varchar(255) NULL COMMENT 'type_of_lighting_and_app column' ,
  `type_of_motor_control` varchar(255) NULL COMMENT 'type_of_motor_control column' ,
  `type_of_power_interface` varchar(255) NULL COMMENT 'type_of_power_interface column' ,
  `type_of_sensor` varchar(255) NULL COMMENT 'type_of_sensor column' ,
  `type_of_transformer` int NULL COMMENT 'type_of_transformer column' ,
  `type_of_transformer_value` varchar(255) NULL COMMENT 'type_of_transformer column' ,
  `type_of_wire_system` varchar(255) NULL COMMENT 'type_of_wire_system column' ,
  `updated_at` timestamp NOT NULL COMMENT 'updated_at' ,
  `url_key` varchar(255) NULL COMMENT 'url_key' ,
  `url_path` varchar(255) NULL COMMENT 'url_path' ,
  `videophone_features` varchar(255) NULL COMMENT 'videophone_features column' ,
  `visibility` smallint UNSIGNED NULL COMMENT 'Catalog Product Visibility visibility column' ,
  `volume` varchar(255) NULL COMMENT 'volume' ,
  `weight` decimal(12,4) NULL COMMENT 'weight' ,
  `weight_type` int NULL COMMENT 'weight_type' ,
  `width` int NULL COMMENT 'width column' ,
  `width_value` varchar(255) NULL COMMENT 'width column' ,
  `zw_automation_technology` int NULL COMMENT 'zw_automation_technology column' ,
  `zw_automation_technology_value` varchar(255) NULL COMMENT 'zw_automation_technology column' ,
  `zw_bulb_socket` int NULL COMMENT 'zw_bulb_socket column' ,
  `zw_bulb_socket_value` varchar(255) NULL COMMENT 'zw_bulb_socket column' ,
  `zw_color_temperature` varchar(255) NULL COMMENT 'zw_color_temperature column' ,
  `zw_light_beam_angel` int NULL COMMENT 'zw_light_beam_angel column' ,
  `zw_light_beam_angel_value` varchar(255) NULL COMMENT 'zw_light_beam_angel column' ,
  `zw_light_brightness` varchar(255) NULL COMMENT 'zw_light_brightness column' ,
  `zw_screen_size` int NULL COMMENT 'zw_screen_size column' ,
  `zw_screen_size_value` varchar(255) NULL COMMENT 'zw_screen_size column' ,
  `zw_signal_inputs` varchar(255) NULL COMMENT 'zw_signal_inputs column' ,
  `zw_signal_outputs` varchar(255) NULL COMMENT 'zw_signal_outputs column' ,
  `zw_touch_control_option` varchar(255) NULL COMMENT 'zw_touch_control_option column' ,
  `zw_type_of_thermostat` varchar(255) NULL COMMENT 'zw_type_of_thermostat column' ,
  `zw_video_codecs` varchar(255) NULL COMMENT 'zw_video_codecs column' ,
  `zw_zwave_device_type` int NULL COMMENT 'zw_zwave_device_type column' ,
  `zw_zwave_device_type_value` varchar(255) NULL COMMENT 'zw_zwave_device_type column' ,
  `zw_zwave_hardware_platform` int NULL COMMENT 'zw_zwave_hardware_platform column' ,
  `zw_zwave_hardware_platform_value` varchar(255) NULL COMMENT 'zw_zwave_hardware_platform column' ,
  `zw_zwave_library_type` int NULL COMMENT 'zw_zwave_library_type column' ,
  `zw_zwave_library_type_value` varchar(255) NULL COMMENT 'zw_zwave_library_type column' ,
  `zw_zwave_role_type` int NULL COMMENT 'zw_zwave_role_type column' ,
  `zw_zwave_role_type_value` varchar(255) NULL COMMENT 'zw_zwave_role_type column' ,
  PRIMARY KEY  (`entity_id`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_TYPE_ID` (`type_id`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_ATTRIBUTE_SET_ID` (`attribute_set_id`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_ENERGY_CONSUMPTION` (`energy_consumption`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_ENERGY_CONSUMPTION_VALUE` (`energy_consumption_value`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_NAME` (`name`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_NUMBER_OF_ROOMS` (`number_of_rooms`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_NUMBER_OF_ROOMS_VALUE` (`number_of_rooms_value`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_PRICE` (`price`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_SF_TECHNOLOGY` (`sf_technology`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_SF_TECHNOLOGY_VALUE` (`sf_technology_value`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_SF_THICKNESS` (`sf_thickness`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_SF_THICKNESS_VALUE` (`sf_thickness_value`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_TYPE_OF_TRANSFORMER` (`type_of_transformer`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_TYPE_OF_TRANSFORMER_VALUE` (`type_of_transformer_value`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_WIDTH` (`width`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_WIDTH_VALUE` (`width_value`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_ZW_LIGHT_BEAM_ANGEL` (`zw_light_beam_angel`),
  INDEX `CATALOG_PRODUCT_FLAT_1_TMP_INDEXER_ZW_LIGHT_BEAM_ANGEL_VALUE` (`zw_light_beam_angel_value`)
) COMMENT='Catalog Product Flat (Store 1)' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci
Category Flat Data index has been rebuilt successfully in 00:00:05

**Comment by orlangur** [comment]
There is nothing to fix here from Magento side, you need to setup MySQL properly for the needs of your particular store. Here is some insight: https://serverfault.com/questions/326836/issue-with-maximum-row-size-in-mysql/326870

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by Tonop** [comment]
There was no such errors in previous versions of Magento,

**Comment by orlangur** [comment]
This is not related to Magento version. I see a lot of attributes not belonging to core thus it is just a matter of time when row limit will be reached.

By the way, flat tables are not recommended for production as performance boost is negligible (not sure if this recommendation applicable to 2.1 or just to 2.2+).
