### ISSUE TITLE
Payment Failed Email not working as intended

### ISSUE THREAD

**Issue by ebaschiera** [magento/magento2#11347]
According to [documentation](http://docs.magento.com/m2/ce/user_guide/sales/checkout-payment-failed-emails.html), an email should be sent "if the payment method that is chosen during checkout fails to complete the transaction."

Looking at the code, the `sendPaymentFailedEmail()` method is called only in `Magento\Multishipping\Controller\Checkout\OverviewPost` class and in `Magento\Checkout\Controller\Onepage\SaveOrder` class.

I made a couple of tests and in my environment, trying a couple of different payment methods, Magento never run those controllers. So, even if the payment fails, the email notification is not sent.

This behaviour is very different from Magento 1, where the merchant receives effective notifications and can monitor checkout/payment problems.

### Preconditions

1. Magento CE 2.1.8
2. PHP 7.0.22-2+ubuntu16.04.1+deb.sury.org+4
3. MySQL 5.7.19-0ubuntu0.16.04.1

### Steps to reproduce

1. Enable Cybersource payment method (or any other that require configuration) without configuring it
2. Add a product to cart and proceed to checkout
2. select Cybersource and input fake credit card information
3. get the "An error occurred on the server. Please try to place the order again." error message at checkout

### Expected result

1. the merchant should receive a failed payment email notification

### Actual result

1. no emails are sent

**Comment by magento-engcom-team** [comment]
@ebaschiera, thank you for your report.
We've created internal ticket(s) MAGETWO-81571 to track progress on the issue.

**Comment by adrian-martinez-interactiv4** [comment]
I'm working on this

**Comment by gx2g** [comment]
please fix this, my company is having the same issue and we are live taking orders.

**Comment by okorshenko** [comment]
hi @gx2g feel free to join code review and testing of proposed solutions (see linked Pull Requests)
Please let us know if the proposed solution works for you
Thank you

**Comment by ebaschiera** [comment]
I confirm that https://github.com/magento/magento2/pull/11602 works fine.

**Comment by gx2g** [comment]
what do you mean it says on that page that the issue can be replicated in all version of magento 2 it seems. plus the solution is on hold until 2.2 pr?

**Comment by gx2g** [comment]
@ebaschiera @okobchenko  what files to I update I don't understand when look at the linked pull requests I am not seeing a solution to the problem can you guide me on what files I need to update or where I can copy and paste them into my site files. I don't see any solution I may not be understanding pull requests.

**Comment by ebaschiera** [comment]
@gx2g if you installed Magento with Composer, you can apply the PR as a patch into your Magento project. Please see this [link](https://punkt.de/en/blog/2017/patches-with-composer.html) for more information.
The patch from the PR would be this: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/11602.patch
You will have to rename the paths inside the patch to make it work with cweagans/composer-patches.

**Comment by digvijay2017** [comment]
@ebaschiera  I have tried to install the patch from the PR. But i am getting error : 
![magento2](https://user-images.githubusercontent.com/30342958/34980164-9e0c67f4-fac9-11e7-8012-04c4e9fbbcd7.png)

I think, there is some mistake in the patch file :  https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/11602.patch

Is someone else install the patch from the PR ?

**Comment by iivashchenko** [comment]
Pull request for M2.1 with MAGETWO-80324 ticket which resolves payment failed email issue has been merged recently: https://github.com/magento/magento2ce/pull/2118.

**Comment by ishakhsuvarov** [comment]
@ebaschiera I am closing this ticket for now as the fix seems to be delivered to the appropriate branches and will be released soon.

**Comment by victortodoran** [comment]
@ishakhsuvarov 2 months after, this is still not working. Yet the issue is closed. What's the strategy behind this?

**Comment by ebaschiera** [comment]
I agree. The fix did NOT reach the appropriate branches due to rejection.

**Comment by magento-engcom-team** [comment]
@ebaschiera Reopening. Thank you for pointing out.

**Comment by ebaschiera** [comment]
You're welcome. Please take a look at my [comment](https://github.com/magento/magento2/pull/11602#issuecomment-343848273) about rejection.
Thanks!

**Comment by adrian-martinez-interactiv4** [comment]
@ebaschiera @magento-engcom-team May I reopen related PR https://github.com/magento/magento2/pull/11602, as rejection reasons are being discussed?

**Comment by ebaschiera** [comment]
@adrian-martinez-interactiv4 yes please :+1:

**Comment by duckchip** [comment]
Is there any progress on this issue? :) thx!

**Comment by myselfgaurav** [comment]
i am still having issue in magento 2.2.6

**Comment by Technogeek2312** [comment]
there is the solution

**Comment by Technogeek2312** [comment]
[Kurl.zip](https://github.com/magento/magento2/files/3123512/Kurl.zip)
try this module, i hope the issue will get resolved. Its working. 
#11347 @adrian-martinez-interactiv4 @ebaschiera @magento-engcom-team  Kindly check this out

**Comment by magento-engcom-team** [comment]
Hi @ebaschiera. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.1-develop` branch(es).
Related commit(s):
 - [da8009e8473d28f101e40355b6bab3d49dc6d4fd](https://github.com/magento/magento2/commit/da8009e8473d28f101e40355b6bab3d49dc6d4fd)
 - [498901e239deecacdd8bfba77e80166edc8c4888](https://github.com/magento/magento2/commit/498901e239deecacdd8bfba77e80166edc8c4888)

**Comment by killday** [comment]
How come this fix is not in the 2.2
I'm facing the same problem.

**Comment by paul-gene** [comment]
This issue is still apparent in 2.3.3-p1. the latest PR, https://github.com/magento/magento2/pull/23106, was closed due to inactivity. Can we get it re-opened and fixed?

**Comment by gwharton** [comment]
I receive payment failed emails on 2.3.4

**Comment by paul-gene** [comment]
> I receive payment failed emails on 2.3.4

odd, because the fix is not in the 2.4-develop codebase https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php

**Comment by paul-gene** [comment]
> I receive payment failed emails on 2.3.4

Odd, the bug fix is not in 2.3.4, eg. https://github.com/magento/magento2/blob/2.3.4/app/code/Magento/Checkout/Model/PaymentInformationManagement.php

**Comment by gwharton** [comment]
I don't know why that is. I just reran a failed cc payment test and got the failure email.

**Comment by magent-harsh** [comment]
This issue is still apparent in 2.3.4. please provide solution for this bug.

**Comment by nadroj467** [comment]
Experiencing this issue in 2.3.5-p1 with native PayPal payments pro hosted

**Comment by grazianodimaio** [comment]
I'm having this issue on Magento 2.3.5-p1 with Adyen Credit Card payment gateway.
Anyone found a solution to this?

**Comment by gwharton** [comment]
I wonder if this is module specific. I got failure emails under Braintree but since switching to Stripe I haven't seen any.

**Comment by gwharton** [comment]
Just had a thought today. The payment failed, sitemap generation failed and currency update failed emails are all dispatched from the AREA_ADMINHTML, whereas all other emails are dispatched from the AREA_FRONTEND regardless of how they are triggered. This means if you have modified the stock email templates for these emails and included the standard headers and footers to make them look better, the email generation will fail, as the standard backend theme does not have any email.css and email-inline.css files at all. Any emails sent from ADMINHTML with the standard theme need to have no email.css or email-inline.css included. The default email templates are unstyled for this reason. You can ofcourse style them with the style box underneath the template if you include the relevant template_style | raw tag in the template.

Just brain dumping this here.

**Comment by magento-engcom-team** [comment]
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Comment by magento-engcom-team** [comment]
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc
