### ISSUE TITLE
Use VARCHAR const in custom table

### ISSUE THREAD

**Issue by enriquei4** [magento/magento2#11353]
### Preconditions
Magento ver. 2.2.0
PHP 7.0.24

### Steps to reproduce
If need to customize a table with  a new column using a VARCHAR attribute i cant use Table::TYPE_VARCHAR because it doesn't exist. 

I have to use TYPE_TEXT with 'length'  255

### Expected result
TYPE_VARCHAR constant definition at framework/DB/Ddl/Table.php

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

http://lmgtfy.com/?q=magento+2+varchar

**Comment by enriquei4** [comment]
I know that @orlangur , i create this issue because i thought that should be fixed Table.php adding the const of this issue.

**Comment by orlangur** [comment]
Nope, there is nothing to fix here, there are hundreds if not thousands `VARCHAR` columns created successfully in core.
