### ISSUE TITLE
Magento2 Demo Installation

### ISSUE THREAD

**Issue by chasteIT** [magento/magento2#1135]
Can we get a Magento2 demo of the frontend and admin (with sample data) that is updated?

This would enable many people who can’t install the platform to contribute feature requests and requests for improvements. There are many frontend developers and merchants who would have great suggestions for Magento2 development, and getting those requests sooner rather than later would help Magento2 developers prioritize items, combine similar projects, etc.

Also, I think the more technically capable among us would benefit from having a functioning install for comparison purposes.

Lastly, if this demo is updated regularly, it would be a great place to showcase Magento2 progress. That is, each update could list of changes like a simplified version of [Magento's release notes](http://www.magentocommerce.com/knowledge-base/entry/ce19-later-release-notes).

**Comment by snohe** [comment]
@dustinnordquist, thanks for your suggestion!  We'll be reviewing this and will let you know as soon as we have any updates.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento2-Demo-Installation/idi-p/45845).
