### ISSUE TITLE
Infinite redirect issue when switching to https 

### ISSUE THREAD

**Issue by scholtz** [magento/magento2#11350]
### Preconditions

1. Magento 2.2, Magento 2.3-dev
2. Any version of PHP
3. Webserver that supports Strict-Transport-Security

### Steps to reproduce
1. Install magento using only http
2. Set up HTTPS on webserver
3. Test webserver address
4. Go to magento administration

### Expected result
1. Magento login screen is displayed

### Actual result
1. Infinite redirect loop

It is because webserver redirects user to https version, and magento redirects user to http version.

I am aware of the fact that user can open it in other browser that does not have the https version cached yet, but I believe that Magento should not allow inifinite redirects. It is quite easy to check on server side if there is infinite redirect loop, by storing the address to session and on next redirect checking this address.. Even more you can make a counter, and show warning on third same redirect..

Also note that it might be wise not to redirect user to http if they already use https even if http is set as magento default by config.

**Comment by orlangur** [comment]
> It is because webserver redirects user to https version, and magento redirects user to http version.

Seems to be an incorrect server setup to me. Magento is not supposed to check if you configured server properly with some hacks.

**Comment by scholtz** [comment]
Let me opose.. The server is not set up incorrectly.. Use of http after Use of https is severe security issue!

**Comment by scholtz** [comment]
Also infinite redirect is huge magento flaw.. What if developer by mistake redirects user in a loop? Eshop owners will loose clients because they will not get any reasonable response from eshop?

**Comment by orlangur** [comment]
Just checked what https://www.google.com/search?q=Strict-Transport-Security&oq=Strict-Transport-Security&sourceid=chrome&ie=UTF-8 is.

> Install magento using only http

You shouldn't do this if you enabled such feature of your web server.

> Also infinite redirect is huge magento flaw.. 

In your scenario it is not caused by Magento. It is caused by incompatible web server setup.

> What if developer by mistake redirects user in a loop? 

There is internal counter disallowing more than 100 internal redirects. External redirects are out of control by Magento, just make an appropriate web server setup.

**Comment by scholtz** [comment]
i have made PR request.. hopefully there is someone else then  orlangur  to check it up

just to summarize what i found during fixing this issue..

the behavior of not transferring to http from https stream is already coded in the main url class, but magento administration only verifies 2 parameters.. if secure_is_forced parameter is checked, then the connection will be secured. When web/secure/use_in_adminhtml parameter is not set it will use http connection, and will lead to infinite redirect loop.

i have fixed this issue the way, that that if the setting web/secure/use_in_adminhtml is not set, the default behavior of the base url class is taken, so that when it is accessed by secure connection, it does not force user to use unsecure connection.

**Comment by Ctucker9233** [comment]
@scholtz I'm trying to understand this because web/secure/use_in_adminhtml is for the backend and won't affect the frontend. Why is it a good idea to use the frontend parameter to automatically set the backend parameter?

**Comment by orlangur** [comment]
@Ctucker9233 this is not about
> because web/secure/use_in_adminhtml is for the backend and won't affect the frontend

See "Install magento using only http". So both `web/secure/use_in_` are set to `No` and after that web server setup is changed in such a way that any HTTP is redirected to HTTPS. This does not lead to any security breach in fact and just require web server configuration to be changed properly.
