### ISSUE TITLE
Magento 2.2 : Indexer crashes 

### ISSUE THREAD

**Issue by thioz** [magento/magento2#11367]
### Preconditions

Magento 2.2 upgrade from 2.1 

While running ./bin/magento indexer:reindex I get the following error : 

PHP Fatal error:  Uncaught Error: Call to a member function ensureBatchSize() on null in vendor/magento/module-catalog/Model/Indexer/Category/Product/Action/Full.php:218

It seems the Magento\Framework\Indexer\BatchSizeManagementInterface does not get injected by the DI and also cannot be created by the ObjectManager

**Comment by magento-engcom-team** [comment]
@thioz, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0
