### ISSUE TITLE
Shopial Integration - wrong Immage path

### ISSUE THREAD

**Issue by afavata** [magento/magento2#11366]
**Refers to MAgento 2.2.0**

**### Preconditions**
Magento 2.2.0
PHP 7.0.22-0ubuntu0.16.04.1
Apache/2.4.18
MySQL 5.7.19

**### Steps to reproduce**
1. Go to Admin Marketing/Social/Connect to Facebook  
2. Follow step by step the configuration including the activation of the Extension Integration.
3. The configuration leads to the facebook fun page with a product grid. 

**### Expected result**
1.  Expected to see product grid populated with products and their images

**### Actual result**
1. Grid is populated with products but without any images

**### Cause**
Images link to a wrong path as directory "pub" is missed.

Actual  wrong path: 
http://www.website.xxx/media/catalog/product/t/a/product-image.jpg

Correct path should be: 
http://www.website.xxx/pub/media/catalog/product/t/a/product-image.jp

**### Workaround**
Workaround waiting issue is resolved is to create a permanent link in the website root with the following commands:
ln -s pub/media media
chmod 777 media

**Comment by orlangur** [comment]
Is this extension a part of core?

**Comment by afavata** [comment]
Yes, it is in 2.2.0

**Comment by orlangur** [comment]
Hm, ok, I cannot find related "social" or "facebook" occurrences in `/app/code/` of this repo though.

**Comment by YevSent** [comment]
@orlangur, Shopial it's a bundle extension. It is not located in Magento codebase repository but it is shipped during Magento installation.

**Comment by orlangur** [comment]
@joni-jones thanks for clarification! Is this repo a right place for bundle extensions bug reports? Is there a full list of extensions matching this repository somewhere then? (sorry, I didn't check if bundled extensions were mentioned in 2.2 release notes yet)

**Comment by magento-engcom-team** [comment]
@afavata, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
