### ISSUE TITLE
'General system exception happened' on import

### ISSUE THREAD

**Issue by Dkmafia** [magento/magento2#11373]
I save the CSV in UTF-8 format. Still get the error. 

### Preconditions

1. 
2. 
Import a CSV
### Steps to reproduce

1. 
2. 
3. 
Import successful 
### Expected result

1. 
Error: General system exception happened
### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
Hello @Dkmafia . Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by Dkmafia** [comment]
Thats really the problem... No error messages. I even cut the amount of products down to test them in small batches. I have no idea what to do.



________________________________

**Comment by magento-engcom-team** [comment]
@Dkmafia Thanks for reporting this issue. Closing as duplicate of [#6924](https://github.com/magento/magento2/issues/6924). #11363 for tracking progress

**Comment by alrururu** [comment]
I am getting same issue on import. There is no import items with errors actually showing in the report
General system exception happened
Additional data:
Invalid URL key

**Comment by alrururu** [comment]
https://i.imgur.com/fpnAjv4.png
