### ISSUE TITLE
Requested store is not found - while switching between store views

### ISSUE THREAD

**Issue by anil-suthar** [magento/magento2#11370]
I've installed Fresh Magento 2.2.0 (PHP version is 7.1.9) and created three store views. 
English, French and German and set locale and code (en_gb), (fr_fr) and (de_de) respectively.

Did reindex, flush/clear cache, deploy etc....

Now I've checked frontend and I can see a store switcher with three options. Default English was selected. It's correct.

**Steps to reproduce**
1. I switched to French view, It's working correct and URL after switching was : http://myhostname.com/?___store=fr_fr
2. Now again, I switched back to English, BUT it's showing ERROR : **Requested store is not found**
and URL after switching was : http://myhostname.com/?___store=fr_fr?___store=en_gb

**Expected result**

It should switch back to English OR any store view that's being selected

------------------------
I think, problem here is the generated URL while switching back. Check this URL http://myhostname.com/?___store=fr_fr?___store=en_gb 
Here if I remove **?___store=fr_fr** from URL, It's working fine

![issue](https://user-images.githubusercontent.com/3518141/31438638-85146f4a-aea6-11e7-8fa3-db01c141908d.png)

**Comment by orlangur** [comment]
@anil-suthar thanks for bug report! This problem is already tracked as https://github.com/magento/magento2/issues/10908.
