### ISSUE TITLE
[2.2.0 CE] bug between integration and shopialfb modules

### ISSUE THREAD

**Issue by spipu** [magento/magento2#11374]
During any setup:upgrade command, the integration account of the module shopialfb is reset.

### Preconditions
1. having afresh magento 2.2.0 environment
2. look at in the BO integration screen that the shopialFB accoung is "Inactive".

### Steps to reproduce
1. Launch the setup:upgrade command
2. look at in the BO integration screen that the shopialFB accoung is "Reset".
3. look at in the BO the warning message on the top of the page about "integration account"

### Expected result
1. the intregration account must not be reset

### Actual result
1. the intregration account have been reseted

The file./vendor/shopialfb/facebook-module/etc/integration.xml describe the integration account to manage.
The file ./vendor/magento/module-integration/Model/ConfigBasedIntegrationManager.php tests if there is a difference between the integration.xml file and the integration account in the database and recreate the integration account if there is a difference (for security reason).

The pb is that the acl "Magento_Backend::admin" is automatically added in database, so there is always a difference between the ACL asked by the xml file : 
Array
(
    [0] => Magento_Backend::store
    [1] => Magento_Backend::stores
    [2] => Magento_Backend::stores_settings
    [3] => Magento_Catalog::catalog
    [4] => Magento_Catalog::catalog_inventory
    [5] => Magento_Catalog::products
)
and the ACL already saved in the database:
Array
(
    [0] => Magento_Backend::admin
    [1] => Magento_Backend::store
    [2] => Magento_Backend::stores
    [3] => Magento_Backend::stores_settings
    [4] => Magento_Catalog::catalog
    [5] => Magento_Catalog::catalog_inventory
    [6] => Magento_Catalog::products
)
it can be found in the method Magento\Integration\Model\ConfigBasedIntegrationManager::hasDataChanged

=> At every setup:upgrade, it reset the shopialfb integration account.

**Comment by spipu** [comment]
The `Magento_Backend::admin` acl allows to use the BO, it is logical that magento add it if we do not ask for it.
The pb is that the test made [here](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Integration/Model/ConfigBasedIntegrationManager.php#L171) forgot to ignore the ACL diff if this diff is only that the `Magento_Backend::admin` acl is in the database and no in the new asked ACL.

**Comment by spipu** [comment]
The `Magento_Backend::admin` acl is missing because the following method doest not add it when it reads the integration.xml files

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Integration/Model/Config/Consolidated/Converter.php#L78

**Comment by bondimedical3** [comment]
Am experiencing the same issue. Only temporary fix I have been able to come up with is to disable the shopialfb module.

**Comment by stevekarwacki** [comment]
Can confirm this issue is still present in Magento 2.2.1 CE and EE

**Comment by magento-engcom-team** [comment]
@spipu, thank you for your report.
We've created internal ticket(s) MAGETWO-84727 to track progress on the issue.

**Comment by lracicot** [comment]
What's the status of this? I'm still having the problem with the default Magento 2.2.3 installation, a year later.

**Comment by gekamikh** [comment]
Any solutions? Same bug at 2.3.0. With my custom extension
