### ISSUE TITLE
Get failed due to "Fix data or replace with a valid value." while upgrade from 2.1.9 to 2.2

### ISSUE THREAD

**Issue by pankajpragma** [magento/magento2#11398]
### Preconditions

1.  PHP 7.0.24
2.  Ubantu
3. MySQL 5.X
4.  Product Catalog Count 200K

### Steps to reproduce

1.  Run composer require "magento/product-community-edition:2.2" --no-update
2.  composer update
3.  php bin/magento cache:clean
4.  php bin/magento setup:upgrade

### Expected result

1.  Version should get updated to 2.2

### Actual result

1.  Upgrading data.. Error converting field `additional_data` in table `catalog_eav_attribute` where `attribute_id`=73, 74, 75, 76, 77, 78, 780, 81, 82, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, , 114, 115, 116, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, , 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, , 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, , 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, , 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, , 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279 using Magento\Frwork\DB\DataConverter\SerializedToJson.

![2017-10-12_1643](https://user-images.githubusercontent.com/6120499/31494588-8b779404-af71-11e7-9cc0-b09f7b29328c.png)

**Comment by zajazdowicz** [comment]
same issue here

**Comment by magento-engcom-team** [comment]
@pankajpragma, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.1

**Comment by JVKeller** [comment]
@pankajpragma,

Were you able to resolve this? 

Apparently the data in the specified column is Null, so it can't be serialized.
