### ISSUE TITLE
Too many password reset requests even when disabled in settings

### ISSUE THREAD

**Issue by coleHafner** [magento/magento2#11409]
### Summary
When attempting to reset a customer's password via the admin, the system tells me 'Too many password reset requests' even when I have disabled the 'max wait time between password resets' in the store configuration settings.

### Preconditions
- Magento Open Source version 2.1.7
- Ubuntu version 14.04.5
- Nginx version 1.10.2
- PHP version 7.0.14
- Mysql version 14.14

### Steps to reproduce
- Login to the admin
- Go to Customers > All Customers
- Click to edit a customer and click 'Reset Password' from the options in the top
- This works the first time, but only then. Every subsequent request fails.

### Expected result
I should get a success message and I should receive a password reset email in my inbox.

### Actual result
I get an error 'Too many password reset requests. Please wait and try again or contact hello@example.com.' 

The settings @ Stores > Configuration > Customers > Customer Configuration > Password Options are:
Max Number of Password Reset Requests: 0
Max Time Between Password Reset Requests: 0

**Comment by magento-engcom-team** [comment]
@coleHafner, thank you for your report.
We've created internal ticket(s) MAGETWO-81873 to track progress on the issue.

**Comment by adrian-martinez-interactiv4** [comment]
Config path used when triggered password request from admin is `admin/security/min_time_between_password_reset_requests` instead of `customer/password/min_time_between_password_reset_requests`. I'll try to fix it.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82633

**Comment by ishakhsuvarov** [comment]
@coleHafner We are closing this ticket now as fixes are already delivered with the linked Pull Requests.
Thank you
