### ISSUE TITLE
installation success, attempt to go on to admin interface gives blank screen

### ISSUE THREAD

**Issue by wetken** [magento/magento2#11402]
### Preconditions

1. Centos centos-release-7-4.1708.el7.centos.x86_64 server with cPanel
2. Magento 2.2 new install prior to upgrade from 1.9, all pre-requisites met

### Steps to reproduce

1. create account in cPanel [<mysite>]
2. as root, cd /home/<mysite>/www [symlink to public_html]
3. tar -zxvf Magento-CE-2.2.0-2017-09-26-07-35-18.tar.gz
4. chown -R <mysite>.<mysite> *
5. create database, establish user with permissions
6. in Firefox http://www.<mysite>/setup
7. installation proceeds to completion, displays encryption key, link to admin interface

### Expected result

1.  click on admin interface should display backend

### Actual result

1. blank screen.
2. apache error log:
[12-Oct-2017 13:45:07 UTC] PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
[12-Oct-2017 13:45:08 UTC] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\Config\CacheInterface in /home/<mysite>/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /home/<mysite>/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /home/<mysite>/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /home/<mysite>/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cache', 'Magento\\Framewo...')
#3 /home/<mysite>/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Mage in /home/andycraftbeads/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

**Comment by magento-engcom-team** [comment]
@wetken, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.1

**Comment by magento-engcom-team** [comment]
@wetken, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.1
