### ISSUE TITLE
'Save Web Site' button and General drop down tab in store >> Configuration >> General is not responding in Magento 2 Admin panel

### ISSUE THREAD

**Issue by mhpsaa** [magento/magento2#11401]
The 'Save Web Site' button is not responding for creating multidomain in Magento 2 admin panel. 

![image](https://user-images.githubusercontent.com/32730259/31498862-b9b3a0b0-af80-11e7-8730-9e60f8c9566c.png)

Also the General tab for drop the configuration settings while configuring the Store.
![image](https://user-images.githubusercontent.com/32730259/31499060-49d8294a-af81-11e7-991e-26dc2385d4ab.png)

Please Help :(

**Comment by magento-engcom-team** [comment]
@mhpsaa, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
