### ISSUE TITLE
Tier price with minimum quantity 0

### ISSUE THREAD

**Issue by MattDelac** [magento/magento2#11415]
### Preconditions

1. Magento 2.1.9
2. 

### Steps to reproduce

1. Create a product XX
2. Create a customer group YY
3. Assign multiple customers to the customer group
4. Apply a tier price for XX with YY with a min_quantity = 0

### Expected result

1. The tier price should work as the MINIMUM quantity is 0 (thus there is no minimum)

### Actual result

1. The tier price appears on the product page but it is not applied when we add it into the basket

I will test with a minimum quantity = 1 but I simply do not understand why a minimum quantity = 0 does not work

Thank you and have a nice day

**Comment by Delta-40** [comment]
https://github.com/magento/magento2/pull/9266 - Its a known bug, and it should be corrected in the 2.2 update.

**Comment by MattDelac** [comment]
Ok sorry for the duplicate ...

**Comment by MattDelac** [comment]
Could it be possible to be corrected also in 2.1

**Comment by magento-engcom-team** [comment]
@MattDelac, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
