### ISSUE TITLE
Improves cms page options in the adminhtml configuration

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#11416]
This issue was originally raised in https://github.com/magento/magento2/pull/10426 by @hostep but unfortunately he cannot continue at the current time. The aim is to improve the admin usability for multiple store setups and the selection of cms pages in the store configuration.

### Preconditions
1. PHP 7.*
2. Magento 2.*

### Steps to reproduce

1. Login to the Magento Admin with a multiple store setup,
2. Create multiple CMS pages with the same name, e.g. a Home Page for each of your stores,
2. Visit the configuration settings for "Default Pages",
3. See multiple "Home Pages"

### Expected result

1. On the default store you will see only CMS pages attached to all store views and on a specific store you will see only CMS pages attached to that store.

![end-results-aim](https://user-images.githubusercontent.com/1572836/31534357-e25c07de-aff6-11e7-9159-96c11f3a48c0.png)

2. Result should us UI component see https://github.com/okorshenko/magento2/pull/4/files for an example build.

### Actual result

1. Hard to read simple drop down.

<img width="1345" alt="cms-before" src="https://user-images.githubusercontent.com/1572836/31534390-05d1b092-aff7-11e7-9e14-1d95b8b422fb.png">

**Comment by springerin** [comment]
i want to give it a try so please assign it to me

**Comment by magento-engcom-team** [comment]
@dmanners, thank you for your report.
We've created internal ticket(s) MAGETWO-84401 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @dmanners. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/18

**Comment by afirlejczyk** [comment]
Hi @magento-engcom-team @dmanners 
I could work on that.
