### ISSUE TITLE
Magento 2.2 product date attribute throwing error

### ISSUE THREAD

**Issue by yogendrabmishra** [magento/magento2#11414]
Installed Magento 2.2 CE fresh. Created one test product attribute with date type. Assigned attribute to default attribute set and tried to create new product 

### Preconditions
 WAMP on Windows7
1. Magento 2.2 CE
2. PHP 7.0.1
3. MySQL 5.7

### Steps to reproduce
1. Create product attribute with Date type and assign to default attribute set
2. Create new product and provide date value to new product
3. Save the product

### Expected result
1. Product should be created in admin panel.

### Actual result
1. DateTime::__construct(): Failed to parse time string (Invalid date) at position 0 (I): The timezone could not be found in the database
![product_create_error](https://user-images.githubusercontent.com/1279893/31530867-fca5b450-b000-11e7-9535-3dadf3f4d81b.jpg)
2. Error in expection.log : main.CRITICAL: DateTime::__construct(): Failed to parse time string (Invalid date) at position 0 (I): The timezone could not be found in the database {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (Invalid date) at position 0 (I): The timezone could not be found in the database at D:\\wamp\\www\\mage22cesampledata\\vendor\\magento\\framework\\Stdlib\\DateTime.php:57)"} []

**Comment by magento-engcom-team** [comment]
Hi @yogendrabmishra, thank you for your report. Magento dont support Windows and WAMP see this link http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

**Comment by magento-engcom-team** [comment]
@yogendrabmishra, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
