### ISSUE TITLE
Changing store view causes error - Requested store is not found

### ISSUE THREAD

**Issue by mageage** [magento/magento2#11419]
Magento CE 2.2.0 without sample data is installed.
After adding second store view in admin panel and change design configuration to:
- Default Store View: Magento Luma
- Second Store View: Magento Blank
In frontend while changing store views I'm getting URL like this:
- http://magento-2.2.dev:8888/?___store=second?___store=default
Which causes this error:
{"0":"Requested store is not found","1":"#0 /magento-2.2.dev\/vendor\/magento\/module-store\/Model\/StoreManager.php(168): Magento\\Store\\Model\\StoreRepository->get('second?___store...')\n#1 /magento-2.2.dev\/vendor\/magento\/module-store\/App\/Action\/Plugin\/Context.php(85): Magento\\Store\\Model\\StoreManager->getStore('second?___store...')\n#2 /magento-2.2.dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\Store\\App\\Action\\Plugin\\Context->beforeDispatch(Object(Magento\\Cms\\Controller\\Index\\Index\\Interceptor), Object(Magento\\Framework\\App\\Request\\Http))\n#3 /magento-2.2.dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#4 /magento-2.2.dev\/generated\/code\/Magento\/Cms\/Controller\/Index\/Index\/Interceptor.php(26): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->___callPlugins('dispatch', Array, Array)\n#5 /magento-2.2.dev\/vendor\/magento\/framework\/App\/FrontController.php(55): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#6 /magento-2.2.dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#7 /magento-2.2.dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#8 /magento-2.2.dev\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#9 /magento-2.2.dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#10 /magento-2.2.dev\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#11 /magento-2.2.dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#12 /magento-2.2.dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#13 /magento-2.2.dev\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#14 /magento-2.2.dev\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#15 /magento-2.2.dev\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#16 /magento-2.2.dev\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#17 {main}","url":"\/?___store=second?___store=default","script_name":"\/index.php"}

**Comment by orlangur** [comment]
@mageage  thanks for bug report! This problem is already tracked as https://github.com/magento/magento2/issues/10908.
