### ISSUE TITLE
Undefined offset error when upgrading CE 2.1.6 to CE 2.2.0

### ISSUE THREAD

**Issue by wangzhi0417** [magento/magento2#11412]
I was upgrading my magento from CE 2.1.6 to CE 2.2.0:

1) Navigate to my magento folder
2) Execute

```
composer require magento/product-community-edition 2.2.0 --no-update
composer update
```

3) Then 
`php bin/magento setup:upgrade`

I saw:

`Notice: Undefined offset: 1 in /var/www/html/vendor/magento/module-theme/Model/ResourceModel/Theme/Collection.php on line 137`

Can any help? Thanks.

**Comment by JodieA** [comment]
Same issue here as well.

**Comment by wangzhi0417** [comment]
I solved the problem by downgrade to 2.1.9

**Comment by amiddio** [comment]
Same issue here as well. 
I've upgrated CE 2.1.7 to CE 2.2.0.

**Comment by tomlutzenberger** [comment]
Can confirm after upgrade from CE 2.1.9 to 2.2.0

**Comment by kishanpatadia** [comment]
I have the same issue. I upgraded from CE 2.1.9 to 2.2.0

**Comment by cadoworld** [comment]
I have the same issue too. I upgraded from CE 2.1.9 to 2.2.0. Does someone have a solution ?

**Comment by skast96** [comment]
Have had the same issue removed it by: 
- adding to core_config_data
  - 414	default	0	design/theme/ua_regexp	{}
  - 415	store	1	design/theme/ua_regexp	{}
  - 72	default	0	design/theme/theme_id	 "your theme id" -> was NULL before no idea why ? 
clear all cache
bin/magento setup:upgrade

Hope this helps someone :smile:

**Comment by cadoworld** [comment]
did anyone else tried Skast96 solution. Did it work ?

**Comment by tomlutzenberger** [comment]
I'm honestly not sure what he explained 🤔 
Could you clarify, @skast96 ?

**Comment by cadoworld** [comment]
error solved - problem with phpcli must be 70 ... was 71
my website working fine now.

**Comment by kishanpatadia** [comment]
great

On Oct 17, 2017 12:06 AM, "cadoworld" <notifications@github.com> wrote:

error solved - problem with phpcli must be 70 ... was 71

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/magento/magento2/issues/11412#issuecomment-336987515>,
or mute the thread

**Comment by tomlutzenberger** [comment]
@cadoworld Mine was always running on 7.0 and still experience this error. Do you have special settings?

**Comment by skast96** [comment]
Okay sorry for my bad explanation, I hope this helps otherwise I should improve my English writing skills 💯. 

I added these lines to the table core_config_data because I have had a look on another magento2 instance of mine which is on Version 2.2.0, I saw that the theme_id of the default scope was the same id I have on the store scope. After this change another error popped up with the "design/theme/ua_regexp" which was not a valid JSON object before it was a:0:{} so I changed it to {}, because Magento was expecting an empty JSON object. For me, it was the easiest way to add these lines and to clear the cache afterward.

**Comment by davepullen** [comment]
I believe I have a solution for this. When I looked in core_config_data I found that the theme_id stored for scope_id 0 was set to "NULL". This appears to be how it was stored in previous versions. I looked at the theme table and got the ID of my adminhtml theme and set that in core_config_data for scope_id 0. Now I can run setup:upgrade again.

**Comment by daniamorris** [comment]
Thanks @davepullen your fix worked for me!

**Comment by magento-engcom-team** [comment]
@wangzhi0417, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0

**Comment by amiddio** [comment]
Thanks @davepullen your fix worked for me as well.

**Comment by oltseb** [comment]
@davepullen ,
thank for the solution! Can confirm that had the same, but now it is gone

**Comment by phanngochanh** [comment]
Thanks @davepullen, it's worked for me.

**Comment by AgentGod** [comment]
Same here.
The strange thing is, on the same server I have 3 magento 2 installs. On both of them didn't have any issue updating to 2.2 on the last one I had this issue.

**Comment by zexperto** [comment]
Thanks @davepullen ir solved my problem

**Comment by forwells** [comment]
Thank you @davepullen  it`s a real method to solute this problem

**Comment by flnative** [comment]
I have this same issue. But am  not following on how to fix. Can someone provide more detailed fix instructions along with a screen shot of where to edit the table (core_config_data)? Do I look in browse or structure or what? I have 1000s of lines in this table.

**Comment by Anantkprajapati** [comment]
Open database using phpmyadmin and find table name core_config_data
run this query like 

SELECT * FROM `core_config_data` WHERE `path` LIKE '%design/theme/theme_id%' 

you can get the some of the rows like 2 or 3. 
There will one value like http://prntscr.com/lfewjs 
There will NULL value and replace to theme id 

Thank you
