### ISSUE TITLE
"We can't find the quote item." error after updating item in cart (IE 11, Edge)

### ISSUE THREAD

**Issue by kfriend** [magento/magento2#11411]
This is a duplicate of https://github.com/magento/magento2/issues/7120, but that issue was closed, and the OP didn't provide enough detail to recreate.

### Preconditions
1. Observed on macOS 10.12 and Ubuntu 16.04.
2. Observed in Internet Explorer 11 and Edge. Was not able to recreate in Chrome.
3. Fresh install of Magento 2. The error appears in at least 2.1.8 and 2.1.9. Did not test other versions.
4. Install sample data.

### Steps to reproduce
1. Navigate to Women > Jackets > Stellar Solar Jacket (/stellar-solar-jacket.html).
2. Select size "S", color "Blue", then click "Add to Cart" button.
3. Click the mini cart icon, then "View and Edit Cart" link.
4. Click the pencil icon to edit the cart item.
5. Click size "S", color "Red", enter any quantity in Qty (if empty), then click the "Update Cart" button.
6. Upon next page visit, the "We can't find the quote item." error will appear.

### Expected result

1. No error and a success message.

### Actual result
1. "We can't find the quote item." error appears

### Additional notes
- It does appear that the cart item is updated, even with the error message.

![Error message screenshot](https://user-images.githubusercontent.com/634835/31523256-6b11ebba-af80-11e7-8f0d-5b12e96b6f26.png)

**Comment by kfriend** [comment]
Any status update on this?

**Comment by magento-engcom-team** [comment]
@kfriend, thank you for your report.
We've created internal ticket(s) MAGETWO-84174 to track progress on the issue.

**Comment by stacypob1** [comment]
Hi @magento-engcom-team and @kfriend I have seen this issue on both chrome, IE, and safari for the site in question, across devices and ISPs. I was able to capture the source code and errors for this happening in the product page, the cart, and a variation on chrome last week. Below I have shared view-only google docs that will allow you to see the code, screenshots of what the issue looks like, and the error that shows up on the page. I have highlighted the section of code that i *THINK* is the culprit, but please note I am not a coder, so the code below might not be the culprit. The google docs are like 70 pages each but I didn't want to leave anything out. :) 

**Product Page Error Code:** https://docs.google.com/document/d/1n_6_ilrpQFIb_g_4J9Vu-F3s0Jfm-pKDCDrc5P9_9ng/edit?usp=sharing

**Product Page red Error Code AND green OK:**
https://docs.google.com/document/d/1pc1wWeKKamBFE3oyAyTlBvPjdMrNibsFe-jAEHbYye4/edit?usp=sharing

**Cart Error Code:** https://docs.google.com/document/d/1wYjCbWgBVzcIsZdLy0MQPDuCou3CMr61Tztt0HFEslE/edit?usp=sharing

**No issue in the cart:** https://docs.google.com/document/d/1nvxdoOL-Q_HyoZ9qmYu_DDFmluzYSDLJYYfGLKVf-XU/edit?usp=sharing



.....Here is a snippet of what *i believe* is not working correctly (again, i stress that I am not saavy with code):
<div data-bind="scope: 'messages'">
    
    <div role="alert" data-bind="foreach: { data: cookieMessages, as: 'message' }" class="messages">
        <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }" class="message-error error message" data-ui-id="message-error">
            <div data-bind="html: message.text">We can't find the quote item.</div>
        </div>
    </div>
    
    
</div>

**Comment by stacypob1** [comment]
<div data-bind="scope: 'messages'">
   
 
    
<div role="alert" data-bind="foreach: { data: cookieMessages, as: 'message' }" class="messages">
      
  <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }" class="message-error error message" data-ui-id="message-error">
          
  <div data-bind="html: message.text">We can't find the quote item.</div>
        </div>
    </div>
    
   
 

</div>

**Comment by stacypob1** [comment]
@okorshenko @magento-admin @magento-engcom-team @magento-devops any updates? Why is this happening?

**Comment by suyash2025** [comment]
same issue we got in 2.1.7.
@magento-admin  Is it solved?

**Comment by HellgaM** [comment]
Looks like this repeats when you have the site opened in 2 browsers in the same time, please check https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/110656/

**Comment by Vital388** [comment]
@magento-admin 
This issue has already been fixed on 2.2.9 and 2.3

**Comment by folektoras** [comment]
@magento-engcom-team see previous comment. This is fixed.
