### ISSUE TITLE
Price sorting order should NOT consider out-of-stock or disabled child products for minimal price.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#11427]
Preconditions
2.1.9

Steps to reproduce

(1) Create a configurable product with below child products
     - color-blue, price: $20 , qty : 10, in-stock
     - color-red, price: $10   , qty : 10, out-of-stock
       
(2) Create a simple product with price $15.

Expected result
Sort order should be (2) and then (1).

Actual result
Sort order is (1) and then (2)

Even if the child product is out-of-stock it still considers its price while sorting

**Comment by yspeedwicked** [comment]
This also occurs for any custom attribute 

Preconditions
- 2.1.9
- Create new product attribute "discount" text-field
- Assign to attribute-set

Steps to reproduce

(1) Create a configurable product with below child products
- color-blue, disocunt: 20 , qty : 10, in-stock
- color-red, disocunt: 10 , qty : 10, out-of-stock

(2) Create a simple product with discount 15.

- Sort-by discount on product listing page

Expected result
Sort order should be (2) and then (1).

Actual result
Sort order is (1) and then (2)

Even if the child product is out-of-stock it still considers its discount while sorting

**Comment by arnoudhgz** [comment]
@magento-engcom-team any news on this issue?

**Comment by ghost** [comment]
@magento-engcom-team can you please share commit link ?

**Comment by nkarthickannan** [comment]
@magento-engcom-team 

Please share the commit link. It'll be helpful for us till Magneto releases 2.3 with this fix.

**Comment by andrewdaluz** [comment]
@magento-engcom-team can you please share commit link or a fix as alternative?

**Comment by brunoroeder** [comment]
@magento-engcom-team can you please share commit link or a fix as alternative?

**Comment by swayoleg** [comment]
@magento-engcom-team  can you please share commit link or a fix as alternative?

**Comment by itaymesh** [comment]
This is the relevant commit https://github.com/magento/magento2/commit/8c9f80bc6d2a2c83719b3eedbd519cbe73fcf168

You will need to add also some classes the above commit is relying on from other PRs.

Below is a complete patch tested on 2.2.3 (no guarantee it will work for you). 

Good luck. 

[Exclude_out_of_stock_products_from_configurable_index_final_price.patch.txt](https://github.com/magento/magento2/files/2111347/Exclude_out_of_stock_products_from_configurable_index_final_price.patch.txt)
