### ISSUE TITLE
magento 2.20 installation on server

### ISSUE THREAD

**Issue by zole011** [magento/magento2#11426]
Hi,
Magento can not even start the installation on a web server.
When we start the installation on the local server all goes well,
I've reviewed all the prerequisites on the folders and files and everything seems ok.
Since we do not have access to ssh on the server, we need to install the magento via the web interface.
We have also tried to start the installation directly from the setup but throw out the same error.
We even tried to transfer the cloned version of the installation from a local server, but again the same error without success.

We tried to install magento 2.21 vesrion,
Our web server is on apache and we have mariadb 10.2.8 with php 7.0.24

This is the error what we got...

Notice: Undefined property: DOMDocument::$documentElement in /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Config/Mapper/Dom.php on line 58

Notice: Trying to get property of non-object in /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Config/Mapper/Dom.php on line 58

Warning: Invalid argument supplied for foreach() in /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Config/Mapper/Dom.php on line 58

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Config\CacheInterface in /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace: #0 /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #1 /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #2 /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cache', 'Magento\\Framewo...') #3 /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgu in /home/xxx/public_html/xxx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

**Comment by ishakhsuvarov** [comment]
@zole011, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
