### ISSUE TITLE
How to save custom form in checkout?

### ISSUE THREAD

**Issue by lucasalcantara** [magento/magento2#11420]
this is just a question. 
I followed this tutorial http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_form.html and it is showing the fields as I expected. Now my question is after I have all the data how can I save it when the place order button is clicked? 

OBS: Sorry if this is not the right place to make this question but I've taken a look in all forums and I did not find the answer.

**Comment by ishakhsuvarov** [comment]
@lucasalcantara, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. As you already mentioned, the GitHub issue tracker is intended for Magento Core technical issues only.
