### ISSUE TITLE
Magento 2.2: Unable to change order top.links

### ISSUE THREAD

**Issue by lduivenvoorde-zz** [magento/magento2#11431]
### Preconditions

Magento 2.2
PHP 7.0

### Issue description
Since upgrading to Magento 2.2 I'm unable to change the order of the top.links since the introduction of the getSortOrder function in Link.php. The SortLinkInterface breaks any way to set the order of the top.links.

### Steps to reproduce

I have tried the following steps to move the top links in my default.xml file:

- Moving the link before or after another link:
`<move element="my-account-link" destination="top.links" after="register-link"/>`

- Setting the link order by adding an argument with setOrder number:
`<argument name="sortOrder" xsi:type="number">xxx</argument>`

### Expected result (screenshot from Magento 2.1)

![screen shot 2017-10-13 at 15 08 51](https://user-images.githubusercontent.com/32771154/31547654-7bee9d86-b028-11e7-9b11-2a588d7d1caa.png)

### Actual result (screenshot from Magento 2.2)

![screen shot 2017-10-13 at 15 08 32](https://user-images.githubusercontent.com/32771154/31547655-7c07d5a8-b028-11e7-9993-e93efa4d98ec.png)

Can somebody tell me if this is a bug in Magento 2.2 or is there another way to set the top.links order since the Magento 2.2 upgrade??

**Comment by magento-engcom-team** [comment]
@lduivenvoorde, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0

**Comment by vodanh109** [comment]
@magento-engcom-team 
I have same problem with @lduivenvoorde when trying add a new top.links. The new top.links cannot go to the first of the list, but can be the last of the list

**Comment by JananiKrishnan** [comment]
@magento-engcom-team, I also have the same problem as @lduivenvoorde

**Comment by arunkumar2687** [comment]
@magento-engcom-team I have the same issue in Magento 2.2.2 EE no response from Gold support too. I tried adding a my orders link to the top.links reference block and tried to move it before sign out by using "before" attribute. But it is not working at all

        <referenceBlock name="top.links">
            <block class="Magento\Framework\View\Element\Html\Link\Current" name="customer-account-navigation-orders-link-top" before="authorization-link">
                <arguments>
                    <argument name="path" xsi:type="string">sales/order/history</argument>
                    <argument name="label" xsi:type="string" translate="true">My Orders</argument>
                </arguments>
            </block>
        </referenceBlock>

**Comment by zennco** [comment]
@magento-engcom-team I have exactly the same issue as @lduivenvoorde on Magento 2.2.2

No matter what I try, the new links I added are not displayed before the **Sign In (authorization-link)** and **My Account (my-account-link)** links.
New links can positioned only before **Create an account** (register-link).

I am using a custom template that inherits from **theme-blank**.

All links are children of the **top.links** block

**Comment by arunkumar2687** [comment]
@zennco I Solved this by creating a custom container and moving all the element one by one inside the custom container. Hope this helps you. 
`	<referenceContainer name="header-wrapper">
			<container name="custom-header-account-wrapper" label="custom header account wrapper" as="custom-header-account-wrapper" after="minicart" htmlTag="ul" htmlClass="account_li wrapper">				
			</container> 
        </referenceContainer>
<move element="header" destination="custom-header-account-wrapper" before="-"/>
		<move element="my-account-link" destination="custom-header-account-wrapper" after="header"/>
		<move element="multiple-wish-list-link" destination="custom-header-account-wrapper" after="my-account-link"/>
		<move element="register-link" destination="custom-header-account-wrapper" after="-"/>
		<move element="authorization-link" destination="custom-header-account-wrapper" after="-"/>
		<move element="top-customer-account-orders-link" destination="custom-header-account-wrapper" after="multiple-wish-list-link"/>`

**Comment by zennco** [comment]
Thanks!
Was thinking to do the same.
Strange bug though... Maybe reopen the issue?

**Comment by arunkumar2687** [comment]
Sure!! It should be reopened.

**Comment by quyennd** [comment]
@arunkumar2687 
Which file do I need write?

**Comment by azamanaza** [comment]
Same issue. I can't reorder it.  Please reopen.

**Comment by luke-denton-aligent** [comment]
I have been fighting with the `top.links` container all morning, and have managed to track down the issue that is preventing the links from being ordered.

I found the issue lies in the class `Magento\Customer\Block\Account\Navigation`. The `getLinks()` function will, ahem, get the links added to the `top.links` container, and then proceed to parse them. The first step is to extract any links that implement the `SortLinkInterface` class. They get copied to a new array, and then unset from the initial array of links.
After looping all of the links, there are now 2 arrays: 1 with `SortLinkInterface` links, and the other with "regular" links.
These two arrays are then merged, with the `SortLInkInterface` array being the first parameter. This means that any link that implements that interface will be placed before any links that don't implement it, regardless of the `before`/`after` values in the XML.

The fix is to make sure that your Link class implements the interface, and also implements the required `getSortOrder()` function. Once these two changes are made, in the layout XML, a sortOrder attribute can be added to each new block that is added to `top.links`, which will control the order of the links. `before` and `after` attributes no longer required there.


```php
// app/code/Vendor/Theme/Block/Html/Link.php

namespace Vendor\Theme\Block\Html;

use Magento\Customer\Block\Account\SortLinkInterface;

class Link extends \Magento\Framework\View\Element\Html\Link implements SortLinkInterface {
  //...

  getSortOrder() {
    return $this->getData(self::SORT_ORDER);
  }

  //...
}
```

```xml
// app/design/frontend/Vendor/Module/Magento_Theme/layout/default.xml

<referenceBlock name="top.links">
  <block class="Vendor\Theme\Block\Html\Link" name="my.vendor.link">
    <arguments>
      <argument name="sortOrder" xsi:type="number">10></argument>
    </arguments>
  </block>
</referenceContainer>
```

In working through this, I've managed to come across a bug in the sorting of the links, which I've created a pull request for. The pull request doesn't "solve" this ticket, but it will solve an issue that will be faced once the directions above are followed https://github.com/magento/magento2/pull/14726

**Comment by PiscesThankIT** [comment]
try this
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="top.links">
            <block class="Magento\Customer\Block\Account\SortLink" name="my-order">
                <arguments>
                    <argument name="path" xsi:type="string">sales/order/history</argument>
                    <argument name="label" xsi:type="string" translate="true">My Orders</argument>
                    <argument name="sortOrder" xsi:type="number">70</argument>
                </arguments>
            </block>
        </referenceBlock>
    </body>
</page>
```


```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Magento\Customer\Block\Account;

/**
 * Class for sortable links.
 */
class SortLink extends \Magento\Framework\View\Element\Html\Link\Current implements SortLinkInterface
{
    /**
     * {@inheritdoc}
     */
    public function getSortOrder()
    {
        return $this->getData(self::SORT_ORDER);
    }
}
```

**Comment by J-Fricke** [comment]
@luke-denton-aligent has it, I was able to get sorting working by following the SortInterface implementation method as described here: https://magento.stackexchange.com/a/221932/48552 - This is a decent work around until the before/after functionality is fixed.

**Comment by TonyDeplanque** [comment]
Bug Magento appeared by this commit https://github.com/magento/magento2/commit/e6805881c65805e93cc78b44143301e3623d3689#diff-04752a6e01927a8ce9c83bb79733380a 

To fix him replace 
`return ($firstLink->getSortOrder() < $secondLink->getSortOrder()) ? 1 : -1;`
by
`return ($firstLink->getSortOrder() < $secondLink->getSortOrder()) ? -1 : 1;`

**Comment by ghost** [comment]
Hi @lduivenvoorde this issue has already fixed in 2.3-develop branch and will be available on 2.3.2 release.

**Comment by leoquijano** [comment]
@engcom-backlog-nazar , do you have a commit ID so we can apply the fix to the 2.2 line?

**Comment by Ctucker9233** [comment]
@leoquijano It may be possible to just go off what @TonyDeplanque commented and create the backport that way. Not sure though.

**Comment by leoquijano** [comment]
@Ctucker9233, I would hope to have an official version for the 2.2 line. That branch seems to be lacking backports and not everybody can upgrade to 2.3 just yet.

**Comment by Ctucker9233** [comment]
@engcom-backlog-nazar What are the commits for this?

**Comment by Januszpl** [comment]
@engcom-backlog-nazar where are the commits for this and how did you tested it works on 2.3.2 ?

**Comment by Januszpl** [comment]
@engcom-backlog-nazar where are the commits for this fix?

**Comment by hewgim** [comment]
Can this issue be reopened. This problem still seems to exist on Magento 2.3.5p1 (at least when inheriting from the blank theme) ?

**Comment by MageTime** [comment]
Surprisingly this problem is still present in Magento ver. 2.4.5-p1
