### ISSUE TITLE
Cannot access admin

### ISSUE THREAD

**Issue by alihalabyah** [magento/magento2#1143]
I'm using Magento `ver. 0.74.0-beta2` and `PHP 5.6.7` I've disabled the cache then logged out, now i can't acces the admin anymore, I've tried to remove the cache `var/cache` folder but with no luck

I even tried to use this https://github.com/netz98/n98-magerun2

```
/index.php/admin/admin/dashboard/index/key/ed47c3f3afceb541d6f8cc361790478f27785f3882b0c5706031bb050c5b59f7/
```

**Comment by grepdirect** [comment]
Hi, 
you've tried to clear the cache of your browser ?

**Comment by alihalabyah** [comment]
@grepdirect This was resolved, seems like a bug with the `Add store code in the Urls` option, once I've turned it off, the issue got resolved!

**Comment by joanhe** [comment]
@alihalabyah Thanks for reporting this problem. Internal ticket MAGETWO-35679 is created to investigate this issue.

**Comment by coldgreentea** [comment]
@alihalabyah When you accessed the admin, did you use the full url given in the OP? Including the large key at the end?

**Comment by alihalabyah** [comment]
@coldgreentea Yes, take a look at the previous comment above!

**Comment by daim2k5** [comment]
Fixed. If not please feel free to reopen the issue.
