### ISSUE TITLE
Magento 2.1.9 : unable to access to storage root in wysiwug popup

### ISSUE THREAD

**Issue by ghost** [magento/magento2#11441]
### Preconditions

1. Magento 2.1.9
2. Add image to block from admin 

### Steps to reproduce

1. Add image to block by wysiwyg files

### Expected result

1. Wysiwyg popup with storage root and all files

### Actual result

1. Wysiwyg popup = blank page
![image](https://user-images.githubusercontent.com/23117633/31567695-5797f760-b060-11e7-80b5-5921b6edad77.png)

Can you please help me to find a solution for this issue, i thing there is a problem with treeJson ajax.

**Comment by PieterCappelle** [comment]
Did you set the correct permissions? Must be file/folder permission issue.

**Comment by ghost** [comment]
The all permission are 777, but the problem still

**Comment by magento-engcom-team** [comment]
@agenceoneo, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by growsera** [comment]
so what is the solution ?! 
for magento 2.1.7 .. how can we solve it ??
@magento-engcom-team
