### ISSUE TITLE
Magento 2.2.0 layer navigation return no products when 2 filters selected.

### ISSUE THREAD

**Issue by gizmocn** [magento/magento2#11450]
### Preconditions
1.  Magento 2.2.0 only
2. PHP 7.0.22

### Steps to reproduce
1.  Install Magento 2.2.0 with sample data that download from https://magento.com/tech-resources/download
2.  Browser top menu Women->Top
3.  In left layer navigation, first select Size->XS(or Color->Blue), then select Pattern->Solid

### Expected result
1. Products with XS size and Solid pattern will be appeared.

### Actual result
But No products appear, and just show message "We can't find products matching the selection."

**Comment by ghost** [comment]
@gizmocn you are right we have followed the same steps to reproduce and we also face the same issues on our site. Thank you for submitted this issues. Please let us know if anyone finds the solutions for that.

**Comment by PieterCappelle** [comment]
Did you try to reindex?

**Comment by magento-engcom-team** [comment]
@gizmocn, thank you for your report.
We've created internal ticket(s) MAGETWO-82076 to track progress on the issue.

**Comment by j-plou** [comment]
Working on it at #mm17es

**Comment by BeatDirector** [comment]
Same issue after upgrading from 2.1.7 to 2.1.10.
Price filter working, category filter working, custom attributes filter NOT working.

**Comment by mikehenze** [comment]
Any news regarding this 2.2 bug?

**Comment by arnoudhgz** [comment]
@j-plou  did you make any progress? Are you still working on this?

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance

**Comment by eduard13** [comment]
Hi @gizmocn, I wasn't able to reproduce this issue on the latest Magento version.
![image](https://user-images.githubusercontent.com/15868188/121163728-b340a400-c857-11eb-9f70-40af4db21f52.png)

Please, feel free to reopen it if you're still able to reproduce it on the latest version.

Thank you.
