### ISSUE TITLE
Invoice PDF encoding issue.

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#1145]
I'm using Adobe Acrobat v11. Store currency is THB, Thai - Baht.

[Checkout Page]
![issue1](https://cloud.githubusercontent.com/assets/11070293/6884149/3d31c424-d60a-11e4-91cc-abc75645181c.PNG)

[PDF file]
![issue2](https://cloud.githubusercontent.com/assets/11070293/6884150/3ecf4d60-d60a-11e4-8e19-c6151e5c16c3.PNG)

**Comment by vpelipenko** [comment]
@adzminz, thank you for reporting this issue. 
Internal ticket: MAGETWO-35746

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Invoice-PDF-encoding-issue/idi-p/46596).
