### ISSUE TITLE
Magento 2.2.0 - Backup fails 

### ISSUE THREAD

**Issue by afavata** [magento/magento2#11454]
**### Preconditions**
**Magento 2.2.0**
PHP 7.0.22-0ubuntu0.16.04.1
Apache/2.4.18
MySQL 5.7.19

**### Steps to reproduce**
1. use shell a go to magento root directory. 
2. type: 
        `bin/magento setup:backup -vvv --code --media --db `
   to perform a complete backup

**### Expected result**
1. execute a complete beackup

**### Actual result**
1.  code backup is done correctly.
2. backup stops during media backup. See following complete logs:

```
root@server1:/var/www/site8085# bin/magento setup:backup -vvv --code --media --db
Enabling maintenance mode
Code backup is starting...
Code backup filename: 1507974760_filesystem_code.tgz (The archive can be uncompressed with 7-Zip on Windows systems)
Code backup path: /var/www/site8085/var/backups/1507974760_filesystem_code.tgz
[SUCCESS]: Code backup completed successfully.
Media backup is starting...
Warning: stat(): stat failed for /var/www/site8085/pub/media/media in /var/www/site8085/vendor/magento/framework/Archive/Tar.php on line 324
Disabling maintenance mode
root@server1:/var/www/site8085#
```

https://github.com/magento/magento2/pulls

**Comment by afavata** [comment]
sorry ... please close this issue....
in pub/media there was a wrong permanent link to media directory causing this issue.

Thanks

**Comment by dschwarzwalder** [comment]
@afavata how did you end up fixing the "wrong permanent link to media directory"? I am having the same issue of "Warning: stat(): stat failed for..." when trying to do a backup via ssh. The backup process within the Magento admin UI also does not work for system and media backups (assuming it is the same issue). Thank you in advance.

**Comment by ashan-r** [comment]
hi!

@afavata  What is the fix for this?

**Comment by afavata** [comment]
Sorry for my delayed reply.... I didn't see there was a request....

Anyway the resolution was by deleting the permanent link which was causing e recursive behaviour. Check whether in the root or in pub folder or other folder as well you have some permanent link and delete it.

Hope to have helped you
