### ISSUE TITLE
Table Rate Shipping method could not upload CSV file

### ISSUE THREAD

**Issue by adaemon** [magento/magento2#11468]
### Preconditions

1. Magento version CE 2.1.5

### Steps to reproduce

1. Login to admin panel go to Store -> Configuration -> Sales -> Shipping Methods
2. Expand Table Rates and Override the default options. Select Enabled as Yes
3. Condition: # of items vs Destination
4. Save the configuration 
5. Change Store view to "Main Website"
6. You could see Export and Import option
7. Click export button and get the CSV format
8. In the CSV edit values and reupload
9. Save the configuration

### Expected result

1. CSV file should be exported without any error. The shipping method should work in the frontend

### Actual result

1. Getting following error 
**Something went wrong while saving this configuration: Warning: array_key_exists(): The first argument should be either a string or an integer in /home/vntghome-alpha/store/vendor/magento/framework/Model/AbstractModel.php on line 351**

2. Shipping is enabled in the frontend, but is not calculating the shipping price as per the configuration in the CSV file

Note: attached txt is saved from CSV due to github restriction
<img width="1167" alt="magerror" src="https://user-images.githubusercontent.com/24820402/31586023-61f21ddc-b199-11e7-857b-236554d21431.png">

[tablerates.txt](https://github.com/magento/magento2/files/1385424/tablerates.txt)

**Comment by magento-engcom-team** [comment]
@adaemon, thank you for your report.
We've created internal ticket(s) MAGETWO-82067 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#35
