### ISSUE TITLE
In admin, url params may get url encoded more than once

### ISSUE THREAD

**Issue by adrian-martinez-interactiv4** [magento/magento2#11478]
In admin, url params may get url encoded more than once, when \Magento\Backend\Model\Url::getUrl() is called many times within the same request. This can mess up parameters like grid filters, and others. Related with #11343.

### Preconditions

Magento 2, develop branch
PHP 7.0

### Steps to reproduce
1. Use this [Gist](https://gist.github.com/adrian-martinez-interactiv4/d0f598faa682e8f915e966543e581391) to reproduce. Place the code at the root folder and execute it.

### Expected result
Current url is always the same, so the result should be the same :
<img width="1429" alt="captura de pantalla 2017-10-16 a las 2 11 34" src="https://user-images.githubusercontent.com/17545750/31590819-67e6d86c-b217-11e7-9792-93172140cd31.png">

### Actual result
Current url params gets url encoded each time method is called :
<img width="1440" alt="captura de pantalla 2017-10-16 a las 2 11 22" src="https://user-images.githubusercontent.com/17545750/31590820-6ec0adc0-b217-11e7-9a56-3974658ee9a9.png">

**Comment by magento-engcom-team** [comment]
@adrian-martinez-interactiv4, thank you for your report.
We've created internal ticket(s) MAGETWO-82031 to track progress on the issue.

**Comment by 4lexvav** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@4lexvav thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
@adrian-martinez-interactiv4, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
