### ISSUE TITLE
Race condition when placing 2 orders for product with stock of 1

### ISSUE THREAD

**Issue by FrankRuis** [magento/magento2#11488]
### Preconditions

1. Tested on Magento 2.1.8 and 2.2

### Steps to reproduce

1. Create a product with stock quantity set to 1
2. Add the product to your cart in 2 different checkout sessions
3. Simultaneously press the place order button in both checkout sessions

### Expected result

1. The order that is finished first successfully places the order
2. The order that is finished second gets an out of stock error

### Actual result

1. Both orders are placed successfully even though there is only 1 item available to ship

**Comment by magento-engcom-team** [comment]
@FrankRuis, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by FrankRuis** [comment]
@magento-engcom-team This might be due to our small development server, we are running an Amazon AWS ec2 t2.small instance, so it takes about 3 seconds after pressing the order button before it is processed. I don't know if everything is supposed to be totally atomic even with slower loading times, if that is not the case I'll try to fix this myself otherwise I'll try to find out why it is not working for me.

**Comment by mamreezaa** [comment]
@FrankRuis  
This blog might help you. 
https://belvg.com/blog/magento-2-oversell-fix.html

**Comment by FrankRuis** [comment]
Thanks, that's exactly what I need
