### ISSUE TITLE
Magento sample data issue

### ISSUE THREAD

**Issue by alihalabyah** [magento/magento2#1148]
I'm trying to install `magento/sample-data:0.74.0-beta2 ` by adding it as required using the following command:

```
magento/sample-data:0.74.0-beta2
```

But it's showing the follwoing error:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/sample-data 0.74.0-beta2 -> satisfiable by magento/sample-data[0.74.0-beta2].
    - magento/sample-data 0.74.0-beta2 requires magento/sample-data-fixtures 0.74.0-beta2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

While it's available here: http://packages.magento.com/#!/sample

Any thoughts?

**Comment by maksek** [comment]
Hi @alihalabyah, please follow the instructions - http://devdocs.magento.com/guides/v1.0//install-gde/install/sample-data.html, do not forget to add  `"minimum-stability": "beta"` into composer.json.

**Comment by alihalabyah** [comment]
@maksek thank you for your help, the `"minimum-stability": "beta"` was the problem!

**Comment by ankursachdeva11** [comment]
Hi @alihalabyah,
i have installed sample-data:1.0.0-beta but after installation no products coming on frontend but products are showing in admin section.
Filters are showing but products are not showing.
