### ISSUE TITLE
Visual Merchandiser show prices of out of stock simple products for the associated configurable product.

### ISSUE THREAD

**Issue by joost-florijn-kega** [magento/magento2#11484]
### Preconditions
1.  Magento 2.1.7 and up
2. PHP 7

### Steps to reproduce
1. Have a configurable product that is associated with a simple product which is out of stock on default website level (id: 0) and is in stock on website level.
2. Go to the visual merchandiser of the category where the configurable product is linked.
3. Look up the configurable product in the visual merchandiser Tile overview.

### Expected result
1. The configurable product with stock 0,00 and price 0,00.

### Actual result
1. The configurable product with stock 0,00 and price of the cheapest simple product.

Product's are linked to categories without notice of any website. The visual merchandiser shows to lowest price of in stock and active simples that are associated with the configurable. The stock check ignores the website scope so if a simple is in stock on the website level but out of stock on default level it should been ignored to determine the lowest price. This doesn't happen at the moment.

**Comment by magento-engcom-team** [comment]
@joost-florijn-kega , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @joost-florijn-kega. Thank you for your report. 
The issue has been fixed in magento/magento2#13632 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - 4a46800428223537c05e7b9fda2e60e86b4ad95f

The fix will be available with the upcoming 2.3.0 release.
