### ISSUE TITLE
Image CAPTCHA requires FT fonts support While Logging to Magento2 admin

### ISSUE THREAD

**Issue by ravisalamani** [magento/magento2#11483]
I am facing the issue mensioned in 

I installed a fresh copy of Magento2 Latest version (2.2.0) on my live site but when i try to login via admin panel it throws the below error
```
There has been an error processing your request

Image CAPTCHA requires FT fonts support
Error log record number: 318218135525
```

**Comment by orlangur** [comment]
Please check https://magento.stackexchange.com/questions/196527/image-captcha-requires-ft-fonts-support.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. Also, googling observed error is usually helpful.

**Comment by iftikharuddin** [comment]
I am facing the same issue the magento stack answer is not helping. He is saying to change php configure script but where is that and what file? is it config.ini or php.ini or what? I am using ngnix server

Thanks

**Comment by orlangur** [comment]
Well, what is configure command is a matter of googling as well.

In PHPInfo you can see something like 
```
Configure Command | './configure' '--prefix=/usr/local/Cellar/php70/7.0.20_12' '--localstatedir=/usr/local/var' '--sysconfdir=/usr/local/etc/php/7.0' '--with-config-file-path=/usr/local/etc/php/7.0' '--with-config-file-scan-dir=/usr/local/etc/php/7.0/conf.d' '--mandir=/usr/local/Cellar/php70/7.0.20_12/share/man' '--enable-bcmath' '--enable-calendar' '--enable-dba' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbregex' '--enable-mbstring' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--enable-zip' '--with-freetype-dir=/usr/local/opt/freetype' '--with-gd' '--with-gettext=/usr/local/opt/gettext' '--with-iconv-dir=/usr' '--with-icu-dir=/usr/local/opt/icu4c' '--with-jpeg-dir=/usr/local/opt/jpeg' '--with-kerberos=/usr' '--with-mhash' '--with-ndbm=/usr' '--with-png-dir=/usr/local/opt/libpng' '--with-xmlrpc' '--with-zlib=/usr' '--with-readline=/usr/local/opt/readline' '--without-gmp' '--without-snmp' '--with-libxml-dir=/usr/local/opt/libxml2' '--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc' '--with-unixODBC=/usr/local/opt/unixodbc' '--with-bz2=/usr' '--with-openssl=/usr/local/opt/openssl' '--enable-fpm' '--with-fpm-user=_www' '--with-fpm-group=_www' '--with-curl' '--with-xsl=/usr' '--with-ldap' '--with-ldap-sasl=/usr' '--with-mysql-sock=/tmp/mysql.sock' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--disable-opcache' '--enable-pcntl' '--without-pear' '--enable-dtrace' '--disable-phpdbg' '--enable-zend-signals'
-- | --
```

in the very top. This is a command which can be used to recompile PHP.

Note that in my case GD is used with freetype. GitHub is not a help desk, problems with your particular environment should be raised in [Magento Stack Exchange](https://magento.stackexchange.com) so that answers can be reused by others.

**Comment by iftikharuddin** [comment]
I solved it by adding **libfreetype.so** file in **user/lib64** directory (in my case it was **_root/lib64_**).
The **libfreetype.so** file should contain the following code

```
./configure --with-apxs2=/usr/bin/apxs --enable-bcmath --with-curl --with-gd \
--with-jpeg-dir=/usr/lib64/ --with-png-dir=/usr/lib64/ --with-freetype-dir=/usr/lib64/ \
--enable-intl --enable-mbstring --with-mcrypt --with-mhash --with-openssl \
--with-pdo-mysql --enable-soap --with-xsl --enable-zip --enable-opcache
```

**Note**: Don't forget to restart your server after adding the script.

**Comment by victortodoran** [comment]
@orlangur stay away from the internet when ur hungry.

**Comment by orlangur** [comment]
@victortodoran what's up, man? :) Was you able to solve a problem which led you here from Google?
