### ISSUE TITLE
How to add image url to Magento 2 Rest API “rest/V1/categories”?

### ISSUE THREAD

**Issue by abedzoubi26** [magento/magento2#11482]
in magento 2.1:

Categories Rest api "rest/V1/categories" returns data as follows

```
 {       
"id": 41,
          "parent_id": 3,
          "name": "Bakery",
          "is_active": true,
          "position": 4,
          "level": 2,
          "product_count": 0,
    "children_data": [],
}
```
how to modify it to return the category image and description ?

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by dimaportenko** [comment]
I've created a custom API endpoint for this purpose https://github.com/troublediehard/mma-customapi
