### ISSUE TITLE
LogicException: View file XML is indistinguishable

### ISSUE THREAD

**Issue by jcconde** [magento/magento2#11494]
### Preconditions

1. Ubuntu Trusty 14.04 LTS x64, created using puphpet
2. PHP-FPM
`PHP 7.0.24-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Sep 28 2017 16:33:02) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.24-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans`
3. NGINX version: nginx/1.12.1 
4. Magento CE 2.1.9 without sample data is installed.

### Steps to reproduce

1. Install magento 2.1.9 using the follow command
`bin/magento setup:install --base-url=http://testnewmag.com/ --db-host=192.168.1.113 --db-name=testnewmag219 --db-user=root --db-password=q1w2e3r4 --admin-firstname=YourFirstName --admin-lastname=YourLastName --admin-email=youremail@xxx.com --admin-user=admin --admin-password=q1w2e3r4 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1`
...
...
`[SUCCESS]: Magento installation complete.`
`[SUCCESS]: Magento Admin URI: /admin_z17k3x`
### Expected result

1. See the magento admin when I go to http://testnewmag219/admin_z17k3x

### Actual result

1. When I go to admin I get this
`There has been an error processing your request`
`Exception printing is disabled by default for security reasons.`
`Error log record number: 1309089369077`
2. Inside file 1309089369077
`a:4:{i:0;s:259:"View file '/var/www/marco/newmag219/vendor/magento/module-sales/view/frontend/layout/sales_order_print_renderers.xml' is indistinguishable from the file '/var/www/marco/newmag219/vendor/magento/module-sales/view/frontend/layout/sales_order_print_renderers.xml'.";i:1;s:11442:"#0 /var/www/marco/newmag219/vendor/magento/framework/View/Layout/File/Collector/Aggregated.php(88): Magento\Framework\View\File\FileList->add(Array)`
3. The error is thrown on `vendor/magento/framework/View/File/FileList.php` File, line 58

It just happens on NGINX

**Comment by fooman** [comment]
Would you mind clarifying your network/nginx setup. In the steps to reproduce you are using this url
http://testnewmag.com/
however when opening the admin you use
http://testnewmag219/admin_z17k3x

**Comment by jcconde** [comment]
Hi @fooman,

I found the issue, it isn't an issue of the magento.
I'm using MacOS High Sierra to create the virtual machine, so this SO uses the new APFS file system and it wasn't synchronizing very well the files, in my case I had XML files duplicated.

Here is a post about this issue https://github.com/hashicorp/vagrant/issues/8788

I think that you can close it.

**Comment by fooman** [comment]
Thanks for the update. Hope it gets resolved soon on the apple side.

**Comment by Lanot** [comment]
Had the same issue with MacOs High Sierra Version 10.13.1 (Centos 7 on Virtual Box).
The bug has been fixed in High Sierra Version 10.13.**2** (17C88).
