### ISSUE TITLE
PayPal payment method not appearing on checkout page

### ISSUE THREAD

**Issue by stevenlavine** [magento/magento2#11498]
### Preconditions

1. Magento 2.1.9
2. MySQL 5.7
3. PHP 7.x
4. Apache 2.4

### Steps to reproduce

1. Go to Stores > Configuration > Sales > Payment Method
2. Change Default Country to New Zealand
3. Select PayPal Website payments standard as a payment method
4. Enter valid PayPal API credentials
5. Select Bank Transfer as a payment method

### Expected result

1. PayPal payment method should appear on the checkout page
2. Bank Transfer should appear as a payment method on the checkout page

### Actual result

1. Only Bank transfer appears as a payment method

**Comment by gewaechshaus** [comment]
https://github.com/magento/magento2/issues/10499

**Comment by magento-engcom-team** [comment]
@stevenlavine, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by ricoliv** [comment]
We have the same problem as @stevenlavine
We upgraded from MCE 2.1.7 to 2.1.8 to 2.1.9

Preconditions

    Magento 2.1.9
    MySQL 5.7
    PHP 7.x
    Apache 2.4.18

Steps to reproduce

    Use plain vanilla Magento 2.1.7
    Go to Stores > Configuration > Sales > Payment Method
    Define your Merchant Country
    Select PayPal Express Checkout as a payment method
    Enter valid PayPal API credentials
    Select Bank Transfer as a payment method
    upgrade to 2.1.8
    upgrade to 2.1.9

Expected result

    PayPal payment method should appear on the checkout page
    Bank Transfer should appear as a payment method on the checkout page

Actual result

   PayPay payment appears in Shopping Cart only
  but when going to OnePageCheckoput, only  Bank transfer appears as a payment method

**Comment by gpcrocker** [comment]
We have the same problem as @stevenlavine
We upgraded from MCE 2.1.6 to 2.1.9

We currently have a temporary work around: https://github.com/magento/magento2/issues/10499#issuecomment-326583156

**Comment by gerben86** [comment]
I encounter the same issue in MCE 2.1.10. 
Workaround is to enable "Billing Agreements".

**Comment by oviliz** [comment]
This is still happening with 2.2.2 and 2.2.1 as pointed in https://github.com/magento/magento2/issues/10499, why is it closed?

**Comment by Sharlyll** [comment]
I am experiencing same issue with 2.2.2

**Comment by ismail-sallami** [comment]
I encountered the same issue after upgrading from 2.0.4 to 2.1.4.
I am using Paypal Plus plugin for Germany.
Before the upgrade it was working fine. After the upgrade I see only the cash method that I enabled, no PayPal iFrame at all.
I checked my PayPal Sandbox API calls and I can see the calls arriving fine.

**Comment by salehawal** [comment]
any solution here?

**Comment by oviliz** [comment]
@salehawal , I believe this must be fixed since 2.2.4.

**Comment by salehawal** [comment]
@oviliz just upgraded to 2.2.4, still payment method not showing

is it because the base currency ?

**Comment by matin73** [comment]
same issue on 2.2.5

**Comment by oviliz** [comment]
This is ridiculous if true... :(

**Comment by MarcusWolschon** [comment]
2.2.4 Changelog says:
_PayPal Express Checkout now appears as a payment option on the Checkout page when the PayPal buttons are available on the shopping cart page. Previously, PayPal did not appear as a payment method on the Checkout page when the billing agreement was disabled, although the PayPal buttons were still available on the shopping cart page._

Was the Checkbox for the billing agreement  set? (It has no help-text, so it could be mistaken for a payment option to have the customer pay by receiving a bill instead of instantly.)
