### ISSUE TITLE
Checkout Grand Total amount miscacluation

### ISSUE THREAD

**Issue by alexkaranda** [magento/magento2#1149]
Issue: Total amounts are calculated incorrectly.
Magento Version: 0.74.0-beta1

Steps to reproduce:
- add an item in cart with price: 10$
- Fill in billing address and click next button
- Fill in shipping address and click next button
- Back to billing step
- Click next button
- Back to billing step
- Click next button
- open DB tables to check amounts
-- DB tables are affected: tables quote, quote_address

Expected result: 
- Subtotal: 10$
- Grand Total: 10$

Actual result: 
- Subtotal: 10$
- Grand Total: 30$

There is also possible error with shopping cart, when we play with addresses and them go back to the shopping cart page.

If we start sharing total amount in the progress block, it might be injured as well. 

Potential reason to the issue are reset methods, which are not executed for some reasons.
$address->setSubtotal(0);
$address->setBaseSubtotal(0);

$address->setGrandTotal(0);
$address->setBaseGrandTotal(0);

**Comment by snohe** [comment]
@alexkaranda, thanks for submitting this issue.  I've created an internal ticket (MAGETWO-35676) so this can be looked into.
