### ISSUE TITLE
Product attribute - filterable (with results)

### ISSUE THREAD

**Issue by erikkubica** [magento/magento2#11508]
### Preconditions
1. Magento 2.1.9
2. PHP 5.6
3. MySQL 5.7

### Steps to reproduce
1. I have no idea

### Expected result
1. Color attribute to show up in layered navigation: when it has products and it's configured as "filterable (with results)"

### Actual result
For all attributes the config Filterable (with results) works as expected. In case of the color attribute, when i configure "Filterable (with results)" the attribute does not show up in layered navigation. If I switch to "Filterable (no results)" the color attribute shows up:
Black (3)
White (3)

If I understand correctly the difference between with and without results means, than the with results should work in my case, because if i use the filter, there are (3) results, and if there are no results it should not show up in layered navigation.

For some reason, in case of "with results" magento think's that I have no results and the attribute does not show up in the filter. In case of "no results" it's able to detect that I have 3 results for each color, which is correct.

There are 3 configurable products in that category, each product have both Black and White colors, each variant are in stock,.... So it should work with the "with results".

With each try i have re-generated DI, reindexed, re-deployed static content, etc...

How to reproduce?
I have really no idea. It worked correctly for a while, then yesterday I got bug report that only one of 2 colors is visible in filter, then when I re-saved product, reindexed, cleared cache,... it started to not to show up. (while other attributes worked/works as expected)

Then I have tried multiple settings (reindex, clear cache,...) for the attribute and i have ended up with "filterable no results" which is only one way allowing me to show color in navigation. 

Sorry that i cannot provide more detailed info. But this is kind of what i call "Magento magic"

**Comment by erikkubica** [comment]
@magento-engcom-team updated to hopefully meet G1

**Comment by magento-engcom-team** [comment]
@erikkubica, thank you for your report.
We've created internal ticket(s) MAGETWO-82438 to track progress on the issue.

**Comment by p-bystritsky** [comment]
The expected result seems not obvious. Need to discuss with product owner.

**Comment by erikkubica** [comment]
@p-bystritsky "Need to discuss with product owner." what does that mean?

**Comment by kozie** [comment]
We're experiencing the exact same problem.

Filterable options on which all products are available aren't visible with "Filterable (With Results)". Perhaps this seems logic because it won't actually filter anything but for UX this is pretty bad.

Now it seems that certain products aren't available because the options aren't shown. In our case it's about shoe sizes.

**Comment by sdzhepa** [comment]
Closed as fixed
related commit:
- https://github.com/magento/magento2/commit/573f74764a23877866ae7627fc43884164668899
