### ISSUE TITLE
Proceed to cart not working magento2

### ISSUE THREAD

**Issue by jpcsguru** [magento/magento2#11518]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

![error](https://user-images.githubusercontent.com/12822019/31671280-faae897a-b39c-11e7-84fe-e57806b5c2b3.png)
there is no link clickable in minicart

**Comment by mzeis** [comment]
Hi!

Thank you for reporting this. Please add information like the Magento version, how you installed Magento etc. as can be seen in the issue creation template. Then the team can try to reproduce. Also, does this problem exist without your custom theme?

**Comment by jpcsguru** [comment]
Hi,
    Magento 2.2 yes it does on luma same, installed package from web setup not composer

**Comment by alen9788** [comment]
Hi

Same issue here for the Magento 2.2

![cart](https://user-images.githubusercontent.com/20162144/31708388-6e3c285a-b421-11e7-8e3c-980a94352361.jpg)

**Comment by alen9788** [comment]
Please tell us when the next Magento version would be issued, such issue is so IMPORTANT related with the sales, so pls issue the next version to solve it ASAP or we have to restore to the M2.1.9

**Comment by jpcsguru** [comment]
website is useless like this you cannot buy annything

**Comment by mzeis** [comment]
@jpcsguru To make sure I understood you right:

By "installed package from web setup not composer", do you mean that you

* downloaded Magento as an archive (http://devdocs.magento.com/guides/v2.2/install-gde/prereq/zip_install.html) and then installed it using the Web Setup Wizard OR
* used Composer to get the code (http://devdocs.magento.com/guides/v2.2/install-gde/prereq/integrator_install.html) and then installed it using the Web Setup Wizard?

I'm asking this because I did the latter (fresh install, no update) and the minicart looks and works just fine:

![grafik](https://user-images.githubusercontent.com/371060/31731347-0c1eccf4-b435-11e7-87cb-7c04728fcf19.png)

**Comment by jpcsguru** [comment]
i can assure you we have no proceed to checkout button

**Comment by alen9788** [comment]
https://community.magento.com/t5/Technical-Issues/Minicart-JS-error-Magento2-2-2-0/td-p/76721


It is M2.2. bug, mentioned by many people, please solve it ASAP.

**Comment by jpcsguru** [comment]
run this commands has fixed for us  give it a go


php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy en_US en_GB
php bin/magento cache:flush

**Comment by alen9788** [comment]
we met with the error when run this command
php bin/magento setup:static-content:deploy en_US en_GB

Still think it is one bug for the M2.2

**Comment by mzeis** [comment]
@alen9788 I see that another person in the link you posted has this problem.

I just installed 2.2 again from scratch, switched to production mode, created a product and added it to the cart. The mini cart works fine for me.

I believe you that you have this problem and I totally understand you need this fixed asap. But we need to provide the core team with steps to reproduce it. You cannot fix something that you cannot reproduce. 

Please add more information on your environment, server config, exact steps you execute etc. and I will try tro re-produce again.

**Comment by alen9788** [comment]
@mzeis  We are waiting for the reply from our theme's developer, they are checking it.

**Comment by magento-engcom-team** [comment]
@jpcsguru, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@jpcsguru, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
