### ISSUE TITLE
date reverts in past after clicking out of product edit

### ISSUE THREAD

**Issue by apedicdev** [magento/magento2#11517]
Admin Product Grid Filter: Set Product as New from Date - Reverts to random date in past after clicking out of product edit

### Steps to reproduce
on admin go to products > catalog
in columns make sure you have 'set product as new from date' selected
in filters apply a date range in new from date
click into a product and save and close

### Expected result

1. inputted data in filter fields remains the same

### Actual result

1. inputted data in date fields changes to one in 2008

<img width="1843" alt="screen shot 2017-10-17 at 15 33 37" src="https://user-images.githubusercontent.com/7457290/31671096-0c88c5ee-b351-11e7-8a96-fc5b7d05dc87.png">

**Comment by magento-engcom-team** [comment]
@apedicdev, thank you for your report.
We've created internal ticket(s) MAGETWO-82116 to track progress on the issue.

**Comment by apedicdev** [comment]
this workaround in `date.js` fixed our case
`var dateRegexp='(0[1-9]|1[012])[- \\/.](0[1-9]|[12][0-9]|3[01])[- \\/.](19|20)\\d\\d';`
` if (value.match(dateRegexp)){
                        dateFormat='MM/DD/YYYY'; //checking for the right format in order to convert properly the date
                    }`

**Comment by magento-engcom-team** [comment]
Hi @apedicdev 

This issue is already fixed and is targeted to be delivered with the upcoming patch 2.2.6

For now you may use these commits as a reference: https://github.com/magento/magento2/search?q=MAGETWO-82116&unscoped_q=MAGETWO-82116&type=Commits

Thank you
