### ISSUE TITLE
Magento 2.2 Changing attribute sets clears attribute value

### ISSUE THREAD

**Issue by mzenner1** [magento/magento2#11516]
### Preconditions (*)

1.Magento 2.4-develop
2. Have two attribute sets (Default and Test Attribute set)

### Steps to reproduce (*)

1.Create attribute called Test Attribute ( Catalog Input Type for Store Owner=Dropdown)
2. In the default set, put the attribute in the main folder.
3. In the Test Attribute set, put the same attribute in a different folder(e.g, Content).
4. Create a product in the default attribute set and set the value of the attribute to "dog"
5. Click Save
6. Page reloads.
7. Change attribute set to Test Attribute set. 

### Expected result (*)

Attribute value is not changed

### Actual result (*)

The attribute moves to the other folder just fine, but the value of "dog" clears out.

**Original issue description:**
I have two attribute sets (Default and Test Attribute set).  I have an attribute called Test Attribute.  In the default set, I put the attribute in the main folder.  In the test attribute set, I put the same attribute in a different folder.

I create a product in the default attribute set and set the value of the attribute to "dog".  Save.  Page reloads, and I change to the other attribute set.  The attribute moves to the other folder just fine, but the value of "dog" clears out.

Is that an intentional behavior?

**Comment by orlangur** [comment]
Just a quick thought, without looking into current code.

I don't see any specific reason to do it that way, attribute can be uniquely distinguished by `attribute_code`. If I remember correctly in some 2.0 RCs, when it was possible to add custom attribute to any folder right from Product Edit page, this scenario worked fine.

Probably data is mapped not using `product[attribute_code]` but some two-dimensional `product[attribute_group][attribute_code]` data structure. I'd suggest you or anyone else to treat current behavior as a bug and try to fix it.

**Comment by magento-engcom-team** [comment]
@mzenner1, thank you for your report.
We've created internal ticket(s) MAGETWO-82631 to track progress on the issue.

**Comment by pemann** [comment]
Has this been fixed in 2.2.x?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30076` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ebanolopes** [comment]
Hello, guys. Me and @gabrielonbi developed a workaround for this. It's very simple. Do the modification on an existing module or [create a new one ](https://devdocs.magento.com/videos/fundamentals/create-a-new-module/).

Create the XML file with below content. This will make product form do not reload on attribute set change.

view/adminhtml/ui_component/product_form.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <settings>
        <reloadItem>false</reloadItem>
    </settings>
</form>
```

Now we'll create a mixin to add new behaviour to attribute set change.

view/adminhtml/requirejs-config.js

```javascript
var config = {
    config: {
        mixins: {
            'Magento_Catalog/js/components/attribute-set-select': {
                'Onbi_Core/js/attribute-set-select-mixin': true
            }
        }
    }
};
```

view/adminhtml/web/js/attribute-set-select-mixin.js

```javascript
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

define([
    'Magento_Ui/js/form/element/ui-select',
    'jquery',
    'mage/url'
], function (Select, $, url) {
    'use strict';

    return function(attributeSetSelect){
        return Select.extend({
            toggleOptionSelected: function (data) {
                var isSelected = this.isSelected(data.value);

                if (this.lastSelectable && data.hasOwnProperty(this.separator)) {
                    return this;
                }

                if (!this.multiple) {
                    if (!isSelected) {
                        this.value(data.value);
                    }
                    this.listVisible(false);
                } else {
                    if (!isSelected) { /*eslint no-lonely-if: 0*/
                        this.value.push(data.value);
                    } else {
                        this.value(_.without(this.value(), data.value));
                    }
                }

                window.location.href = window.location.origin + window.location.pathname + '?set=' + data.value;

                return this;
            }
        });
    };
});
```

And that's it. Basically we reload product page with the "set=[id]" parameter. Magento already has the rest of the code which make product form to load on attribute set sent on set parameter. User will have to save product yet to get the change saved to database, as it is on Magento default behaviour.

We've tested on Magento 2.3.2. Hope it helps.

@magento-engcom-team with a few more minor adjustments this can be a solution to be integrated to core. E.g. a confirmation message before reload page would be great to avoid loose data; but currently users are already loosing data if they do not pay attention for the wiped out input values.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
