### ISSUE TITLE
Some js files in Page and Block aren't be found

### ISSUE THREAD

**Issue by JesusTinoco** [magento/magento2#1152]
![screen shot 2015-03-30 at 23 19 00](https://cloud.githubusercontent.com/assets/2388836/6907049/36e5355e-d733-11e4-920b-f66eeefc93c6.png)

**Comment by alihalabyah** [comment]
@JesusTinoco Have you checked the read permission for the `pub` path?

**Comment by alihalabyah** [comment]
@JesusTinoco Another thing is that you need to have the rewrite module enabled, if it's enabled try to use a virtual host instead of the IP

**Comment by JesusTinoco** [comment]
Have read permissions and the rewrite module is enabled.

**Comment by JesusTinoco** [comment]
With PHP 5.5.22 doesn't work but with PHP 5.6.7 works... Any idea?

**Comment by vpelipenko** [comment]
@alihalabyah, do you have updates for us? Do you still have this issue?

**Comment by JesusTinoco** [comment]
Maybe, I don't know why but it only happens when I installed it on 80 port, in other ports works fine.

**Comment by JesusTinoco** [comment]
When I introduce in the base_url "http:my-ip:80/magento/" it doesn't work, but when I introduce "http:my-ip/magento/" it works.

**Comment by mazhalai** [comment]
@JesusTinoco Thank you for your update, we have created MAGETWO-35964 to investigate this issue.

**Comment by JesusTinoco** [comment]
@mazhalai For more information I have to say that when I install magento in other ports (81, 82, 83...) and I introduce in the base_url this port it works properly.

**Comment by muasir** [comment]
@JesusTinoco we can't reproduce this bug any more.  Can you verify that, it is still an issue for you.
