### ISSUE TITLE
Customizable Option Pricing

### ISSUE THREAD

**Issue by jdovan** [magento/magento2#11521]
When updating a product, the customizable option prices are not updated correctly if the price is greater than $999. 
Preconditions

    Magento 2.1.5
 

Steps to reproduce

    Edit a product with customizable option
    Set the price (over $999)
    Save the product
    Edit the product again. The price will have comma separators.
    Save the product again.
    Check the option's price. It will be $1 or $2

Expected result

    The price of the options should be saved correctly

Actual result

    The price of the option is truncated

**Comment by magento-engcom-team** [comment]
@jdovan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
