### ISSUE TITLE
Validation prevents form closing

### ISSUE THREAD

**Issue by scholtz** [magento/magento2#11528]
### Preconditions
1. Any version of PHP
2. Any version of Mysql
3. Any version of Magento

### Steps to reproduce
1. Go to admin
2. Go to catalog
3. Select product
4. Click advanced pricing
5. Click add customer group, do not fill any value
6. Try to close 

### Expected result
1. Form is closed 

### Actual result
1. Form does not close, validation issue is triggered
![scr01](https://user-images.githubusercontent.com/1223439/31687324-38253bdc-b389-11e7-9100-fbc235d89e4c.png)

Form close by X sign should not save the form nor trigger the validation

**Comment by magento-engcom-team** [comment]
@scholtz, thank you for your report.
We've created internal ticket(s) MAGETWO-82181 to track progress on the issue.

**Comment by luismiguelyangehuaman** [comment]
I am working on it at #mm17es

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to the 2.2-develop branch. Will be available with upcoming patch release
