### ISSUE TITLE
Notification messages not disappearing after being displayed

### ISSUE THREAD

**Issue by LilyBergonzatOld** [magento/magento2#11527]
### Preconditions
1. Ubuntu 16.04
2. nginx 1.10.3
3. PHP 7.0.20
4. MySQL 5.6.37
5. Magento Open Source version 2.2.0 without sample data

### Steps to reproduce
1. Install Magento
2. Create module
3. Create an observer for event "controller_action_predispatch"
4. Inject Magento\Framework\Message\ManagerInterface in that observer
5. Add a success message in the execute method:

```php
if (!$observer->getData('request')->isAjax()) {
    $this->messageManager->addSuccessMessage(__('Hello world!'));
}
```

### Expected result
1. The success message is saved in memory then displayed then deleted from memory. It is displayed once per frontend page load.

### Actual result
1. The success message are stacked, the number displayed equal to the amout of pages you loaded. It looks like they are never deleted from memory.

**Comment by magento-engcom-team** [comment]
@YannBergonzat, thank you for your report.
We've created internal ticket(s) MAGETWO-82165 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @YannBergonzat. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1111 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - d4ee3da0cf7c177ad896083abad16121a0e8bf3c
 - ac27be21178b536ac81af6023e95b65688463347
 - 01192e12bcf117f230bb3fa9e4b6e2c40a5afbdc

The fix will be available with the upcoming 2.2.4 release.

**Comment by saderra** [comment]
This issue has reemerged in 2.3.4

**Comment by duffner** [comment]
@saderra, I'm also getting reports of this same issue.  @magento-engcom-team, do you have any thoughts on this?

**Comment by marketingsignals** [comment]
We've got this in 2.3.4

**Comment by gaiterjones** [comment]
@saderra was this issue ever resolved for you?
