### ISSUE TITLE
 Values of Visual Swatch Attribute drop down is not work correct

### ISSUE THREAD

**Issue by Andrii-Deineha** [magento/magento2#11534]
### Preconditions
1. Magento 2.2.0 and 2.3.0 CE
2. MySQL 5.6.36
3. PHP 7.0.20

### Steps to reproduce
1. Go to Admin
2. Open Stores > Attributes > Product
3. Add New Attribute with Catalog Input Type for Store Owner: Visual Swatch
4. In Tab Manage Swatch (Values of Your Attribute) click Add Swatch button
5. Press to chose color or file
 

### Expected result
1. Drop down menu is show all items

### Actual result

1.
![visual_bug_0891280872](https://user-images.githubusercontent.com/27814119/31710103-b57e8dd6-b3fc-11e7-813c-0f8a25ba4160.png)

**Comment by magento-engcom-team** [comment]
@Andrii-Deineha, thank you for your report.
We've created internal ticket(s) MAGETWO-82172 to track progress on the issue.

**Comment by enriquei4** [comment]
Im working on this issue, could you assign me?

**Comment by okorshenko** [comment]
Hi @enriquei4 sure. Please accept the invitation

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82558

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82955

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release
