### ISSUE TITLE
Grouped products not associated on import

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#11535]
When importing grouped products, the simple products are imported but not associated with the group product.

Magento OS v2.2.0

Steps to reproduce:
1. Setup and export grouped product, including simple associated products.
2. Delete grouped product and simple products.
3. Wait for re-index. (+1 to restore re-index option from admin).
3. Import using the unmodified export file generated.

Expected result:
1. Grouped/simple products should be recreated as originally exported, with simple associated with group.

Actual result:
1. Group product and simple products are created, but simple are not associated with the grouped.

Have tried to import simple products only, wait for re-index then import grouped; still no association. Export CSV contains entry for _associated_skus_ set to "SKU1=1.0000,SKU2=1.0000", same as was exported.

**Comment by magento-engcom-team** [comment]
@adamlavery, thank you for your report.
We've created internal ticket(s) MAGETWO-82532 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#34
