### ISSUE TITLE
Can't setup Paypal pending status for new order

### ISSUE THREAD

**Issue by rackyan** [magento/magento2#11533]
### Preconditions

1. Magento 2.2.0
2. PHP 7.1.9
3. MySQL 5.7
4. Apache 2.4

### Steps to reproduce

1. Select payment method: Stores > Configuration > Sales > Payment Method > PayPal Express Checkout
2.  Go to Stores > Assign Order Status to State > Order Status: pending Paypal & Order States: pending

### Expected result

1. The order unpaid through Paypal can be viewed on sales order list.  

### Actual result

1. Now can't see any pending order via Paypal, just can view processing Paypal order
2. But other payment pending order can view with no problem.

**Comment by magento-engcom-team** [comment]
Hi @rackyan 
Thanks for reporting this issue. 
We cannot reproduce this issue as described.
If you want to show order with status "Pending PayPal" in customer account page, you should assign Order Status to State (as you describe in second step) with "Visible On Storefront" = true.
http://prntscr.com/gyyzrj.

**Comment by magento-engcom-team** [comment]
@rackyan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0

**Comment by rackyan** [comment]
@magento-engcom-team, thanks for your support. 
How the Paypal pending orders can be viewed on store backend, I've try coupld of times but can't find any record on backend. 
Thanks

**Comment by DEVJhonCortes** [comment]
Same problem here in Magento Open Source 2.4.1

When the user enters all the checkout data (Billing / Shipping), selects PayPal Express Checkout and clicks the go to pay button, this is redirected to PayPal, but Magento does not create an order in pending status.

As @rackyan mentions, only orders with processing state are displayed in the order grid.
