### ISSUE TITLE
Can not select Varnish as Full Page Cache

### ISSUE THREAD

**Issue by RogerKeulen** [magento/magento2#11538]
Hi there i want to change some settings under: Store -> System -> Advanced
But everything is grayed out (can change) except for "Storage Configuration for Media".

I want to use Varnish and i have to select that here. But i can't checkboxen and pull-down-lists are gray and not enabled.

### Preconditions
I'm using Magento ver. 2.2.0-rc23

### Steps to reproduce
1.  I have no idea, worked a couple of days ago...

### Expected result
1.  I expect to beable to change confiuration. Or get a HOOVER TEXT THAT WILL EXPLAIN WHY NOT !

### Actual result
No help, No hoover text, No mention in the documentation of installing Varnish. No help at all.

**Comment by RogerKeulen** [comment]
I have made a picture how it looks: (checkboxes are not checked and can't be, dropdownlist is disabled)
![mag2-settings](https://user-images.githubusercontent.com/14263822/31717529-96d4fcb6-b40c-11e7-8d1f-39912f8f681f.png)

**Comment by RogerKeulen** [comment]
Yes, finally i got some help ! Varnish configuration is dependend on all the other configuration in the same page. On that page is also currency that is disabled. So i think i have to change the disabled currency to exclude "dollars".

![mag2-settings-error](https://user-images.githubusercontent.com/14263822/31717739-6bf3b608-b40d-11e7-9c06-37356b54029f.png)

The reason why Dollars can't be handled by Magento 2.2 is a bit strange. I expect that some one should have tested this. But apperently not... Just like having disabled pull-down-lists with unchecked checkboxes.


Here is the list of installed currencies: (According to there manual, so we don't know for shure)
[test3048@dev006 mage]$ php bin/magento info:currency:list
+-------------------------------------------------+------+
| Currency                                        | Code |
+-------------------------------------------------+------+
| Afghan Afghani (1927-2002) (AFA)                | AFA  |
| Afghan Afghani (AFN)                            | AFN  |
| Albanian Lek (1946-1965) (ALK)                  | ALK  |
| Albanian Lek (ALL)                              | ALL  |
| Algerian Dinar (DZD)                            | DZD  |
| Andorran Peseta (ADP)                           | ADP  |
| Angolan Kwanza (1977-1991) (AOK)                | AOK  |
| Angolan Kwanza (AOA)                            | AOA  |
| Angolan New Kwanza (1990-2000) (AON)            | AON  |
| Angolan Readjusted Kwanza (1995-1999) (AOR)     | AOR  |
| Argentine Austral (ARA)                         | ARA  |
| Argentine Peso (1881-1970) (ARM)                | ARM  |
| Argentine Peso (1983-1985) (ARP)                | ARP  |
| Argentine Peso (ARS)                            | ARS  |
| Argentine Peso Ley (1970-1983) (ARL)            | ARL  |
| Armenian Dram (AMD)                             | AMD  |
| Aruban Florin (AWG)                             | AWG  |
| Australian Dollar (AUD)                         | AUD  |
| Austrian Schilling (ATS)                        | ATS  |
| Azerbaijani Manat (1993-2006) (AZM)             | AZM  |
| Azerbaijani Manat (AZN)                         | AZN  |
| Bahamian Dollar (BSD)                           | BSD  |
| Bahraini Dinar (BHD)                            | BHD  |
| Bangladeshi Taka (BDT)                          | BDT  |
| Barbadian Dollar (BBD)                          | BBD  |
| Belarusian New Ruble (1994-1999) (BYB)          | BYB  |
| Belarusian Ruble (BYR)                          | BYR  |
| Belgian Franc (BEF)                             | BEF  |
| Belgian Franc (convertible) (BEC)               | BEC  |
| Belgian Franc (financial) (BEL)                 | BEL  |
| Belize Dollar (BZD)                             | BZD  |
| Bermudan Dollar (BMD)                           | BMD  |
| Bhutanese Ngultrum (BTN)                        | BTN  |
| Bolivian Boliviano (1863-1963) (BOL)            | BOL  |
| Bolivian Boliviano (BOB)                        | BOB  |
| Bolivian Mvdol (BOV)                            | BOV  |
| Bolivian Peso (BOP)                             | BOP  |
| Bosnia-Herzegovina Convertible Mark (BAM)       | BAM  |
| Bosnia-Herzegovina Dinar (1992-1994) (BAD)      | BAD  |
| Bosnia-Herzegovina New Dinar (1994-1997) (BAN)  | BAN  |
| Botswanan Pula (BWP)                            | BWP  |
| Brazilian Cruzado (1986-1989) (BRC)             | BRC  |
| Brazilian Cruzeiro (1942-1967) (BRZ)            | BRZ  |
| Brazilian Cruzeiro (1990-1993) (BRE)            | BRE  |
| Brazilian Cruzeiro (1993-1994) (BRR)            | BRR  |
| Brazilian New Cruzado (1989-1990) (BRN)         | BRN  |
| Brazilian New Cruzeiro (1967-1986) (BRB)        | BRB  |
| Brazilian Real (BRL)                            | BRL  |
| British Pound Sterling (GBP)                    | GBP  |
| Brunei Dollar (BND)                             | BND  |
| Bulgarian Hard Lev (BGL)                        | BGL  |
| Bulgarian Lev (1879-1952) (BGO)                 | BGO  |
| Bulgarian Lev (BGN)                             | BGN  |
| Bulgarian Socialist Lev (BGM)                   | BGM  |
| Burmese Kyat (BUK)                              | BUK  |
| Burundian Franc (BIF)                           | BIF  |
| CFA Franc BCEAO (XOF)                           | XOF  |
| CFA Franc BEAC (XAF)                            | XAF  |
| CFP Franc (XPF)                                 | XPF  |
| Cambodian Riel (KHR)                            | KHR  |
| Canadian Dollar (CAD)                           | CAD  |
| Cape Verdean Escudo (CVE)                       | CVE  |
| Cayman Islands Dollar (KYD)                     | KYD  |
| Chilean Escudo (CLE)                            | CLE  |
| Chilean Peso (CLP)                              | CLP  |
| Chilean Unit of Account (UF) (CLF)              | CLF  |
| Chinese People’s Bank Dollar (CNX)              | CNX  |
| Chinese Yuan (CNY)                              | CNY  |
| Colombian Peso (COP)                            | COP  |
| Colombian Real Value Unit (COU)                 | COU  |
| Comorian Franc (KMF)                            | KMF  |
| Congolese Franc (CDF)                           | CDF  |
| Costa Rican Colón (CRC)                         | CRC  |
| Croatian Dinar (HRD)                            | HRD  |
| Croatian Kuna (HRK)                             | HRK  |
| Cuban Convertible Peso (CUC)                    | CUC  |
| Cuban Peso (CUP)                                | CUP  |
| Cypriot Pound (CYP)                             | CYP  |
| Czech Republic Koruna (CZK)                     | CZK  |
| Czechoslovak Hard Koruna (CSK)                  | CSK  |
| Danish Krone (DKK)                              | DKK  |
| Djiboutian Franc (DJF)                          | DJF  |
| Dominican Peso (DOP)                            | DOP  |
| _Dutch Guilder (NLG)_                             | NLG  |   
| East Caribbean Dollar (XCD)                     | XCD  |
| East German Mark (DDM)                          | DDM  |
| Ecuadorian Sucre (ECS)                          | ECS  |
| Ecuadorian Unit of Constant Value (ECV)         | ECV  |
| Egyptian Pound (EGP)                            | EGP  |
| Equatorial Guinean Ekwele (GQE)                 | GQE  |
| Eritrean Nakfa (ERN)                            | ERN  |
| Estonian Kroon (EEK)                            | EEK  |
| Ethiopian Birr (ETB)                            | ETB  |
| **Euro (EUR)**                                      | EUR  |     **<==== THIS ONE I WANT TO USE !**
| European Composite Unit (XBA)                   | XBA  |
| European Currency Unit (XEU)                    | XEU  |
| European Monetary Unit (XBB)                    | XBB  |
| European Unit of Account (XBC) (XBC)            | XBC  |
| European Unit of Account (XBD) (XBD)            | XBD  |
| Falkland Islands Pound (FKP)                    | FKP  |
| Fijian Dollar (FJD)                             | FJD  |
| Finnish Markka (FIM)                            | FIM  |
| French Franc (FRF)                              | FRF  |
| French Gold Franc (XFO)                         | XFO  |
| French UIC-Franc (XFU)                          | XFU  |
| Gambian Dalasi (GMD)                            | GMD  |
| Georgian Kupon Larit (GEK)                      | GEK  |
| Georgian Lari (GEL)                             | GEL  |
| German Mark (DEM)                               | DEM  |
| Ghanaian Cedi (1979-2007) (GHC)                 | GHC  |
| Ghanaian Cedi (GHS)                             | GHS  |
| Gibraltar Pound (GIP)                           | GIP  |
| Gold (XAU)                                      | XAU  |
| Greek Drachma (GRD)                             | GRD  |
| Guatemalan Quetzal (GTQ)                        | GTQ  |
| Guinea-Bissau Peso (GWP)                        | GWP  |
| Guinean Franc (GNF)                             | GNF  |
| Guinean Syli (GNS)                              | GNS  |
| Guyanaese Dollar (GYD)                          | GYD  |
| Haitian Gourde (HTG)                            | HTG  |
| Honduran Lempira (HNL)                          | HNL  |
| Hong Kong Dollar (HKD)                          | HKD  |
| Hungarian Forint (HUF)                          | HUF  |
| Icelandic Króna (1918-1981) (ISJ)               | ISJ  |
| Icelandic Króna (ISK)                           | ISK  |
| Indian Rupee (INR)                              | INR  |
| Indonesian Rupiah (IDR)                         | IDR  |
| Iranian Rial (IRR)                              | IRR  |
| Iraqi Dinar (IQD)                               | IQD  |
| Irish Pound (IEP)                               | IEP  |
| Israeli New Sheqel (ILS)                        | ILS  |
| Israeli Pound (ILP)                             | ILP  |
| Israeli Sheqel (1980-1985) (ILR)                | ILR  |
| Italian Lira (ITL)                              | ITL  |
| Jamaican Dollar (JMD)                           | JMD  |
| Japanese Yen (JPY)                              | JPY  |
| Jordanian Dinar (JOD)                           | JOD  |
| Kazakhstani Tenge (KZT)                         | KZT  |
| Kenyan Shilling (KES)                           | KES  |
| Kuwaiti Dinar (KWD)                             | KWD  |
| Kyrgystani Som (KGS)                            | KGS  |
| Laotian Kip (LAK)                               | LAK  |
| Latvian Lats (LVL)                              | LVL  |
| Latvian Ruble (LVR)                             | LVR  |
| Lebanese Pound (LBP)                            | LBP  |
| Lesotho Loti (LSL)                              | LSL  |
| Liberian Dollar (LRD)                           | LRD  |
| Libyan Dinar (LYD)                              | LYD  |
| Lithuanian Litas (LTL)                          | LTL  |
| Lithuanian Talonas (LTT)                        | LTT  |
| Luxembourg Financial Franc (LUL)                | LUL  |
| Luxembourgian Convertible Franc (LUC)           | LUC  |
| Luxembourgian Franc (LUF)                       | LUF  |
| Macanese Pataca (MOP)                           | MOP  |
| Macedonian Denar (1992-1993) (MKN)              | MKN  |
| Macedonian Denar (MKD)                          | MKD  |
| Malagasy Ariary (MGA)                           | MGA  |
| Malagasy Franc (MGF)                            | MGF  |
| Malawian Kwacha (MWK)                           | MWK  |
| Malaysian Ringgit (MYR)                         | MYR  |
| Maldivian Rufiyaa (MVR)                         | MVR  |
| Maldivian Rupee (MVP)                           | MVP  |
| Malian Franc (MLF)                              | MLF  |
| Maltese Lira (MTL)                              | MTL  |
| Maltese Pound (MTP)                             | MTP  |
| Mauritanian Ouguiya (MRO)                       | MRO  |
| Mauritian Rupee (MUR)                           | MUR  |
| Mexican Investment Unit (MXV)                   | MXV  |
| Mexican Peso (MXN)                              | MXN  |
| Mexican Silver Peso (1861-1992) (MXP)           | MXP  |
| Moldovan Cupon (MDC)                            | MDC  |
| Moldovan Leu (MDL)                              | MDL  |
| Monegasque Franc (MCF)                          | MCF  |
| Mongolian Tugrik (MNT)                          | MNT  |
| Moroccan Dirham (MAD)                           | MAD  |
| Moroccan Franc (MAF)                            | MAF  |
| Mozambican Escudo (MZE)                         | MZE  |
| Mozambican Metical (1980-2006) (MZM)            | MZM  |
| Mozambican Metical (MZN)                        | MZN  |
| Myanma Kyat (MMK)                               | MMK  |
| Namibian Dollar (NAD)                           | NAD  |
| Nepalese Rupee (NPR)                            | NPR  |
| Netherlands Antillean Guilder (ANG)             | ANG  |
| New Taiwan Dollar (TWD)                         | TWD  |
| New Zealand Dollar (NZD)                        | NZD  |
| Nicaraguan Córdoba (1988-1991) (NIC)            | NIC  |
| Nicaraguan Córdoba (NIO)                        | NIO  |
| Nigerian Naira (NGN)                            | NGN  |
| North Korean Won (KPW)                          | KPW  |
| Norwegian Krone (NOK)                           | NOK  |
| Omani Rial (OMR)                                | OMR  |
| Pakistani Rupee (PKR)                           | PKR  |
| Palladium (XPD)                                 | XPD  |
| Panamanian Balboa (PAB)                         | PAB  |
| Papua New Guinean Kina (PGK)                    | PGK  |
| Paraguayan Guarani (PYG)                        | PYG  |
| Peruvian Inti (PEI)                             | PEI  |
| Peruvian Nuevo Sol (PEN)                        | PEN  |
| Peruvian Sol (1863-1965) (PES)                  | PES  |
| Philippine Peso (PHP)                           | PHP  |
| Platinum (XPT)                                  | XPT  |
| Polish Zloty (1950-1995) (PLZ)                  | PLZ  |
| Polish Zloty (PLN)                              | PLN  |
| Portuguese Escudo (PTE)                         | PTE  |
| Portuguese Guinea Escudo (GWE)                  | GWE  |
| Qatari Rial (QAR)                               | QAR  |
| RINET Funds (XRE)                               | XRE  |
| Rhodesian Dollar (RHD)                          | RHD  |
| Romanian Leu (1952-2006) (ROL)                  | ROL  |
| Romanian Leu (RON)                              | RON  |
| Russian Ruble (1991-1998) (RUR)                 | RUR  |
| Russian Ruble (RUB)                             | RUB  |
| Rwandan Franc (RWF)                             | RWF  |
| Saint Helena Pound (SHP)                        | SHP  |
| Salvadoran Colón (SVC)                          | SVC  |
| Samoan Tala (WST)                               | WST  |
| Saudi Riyal (SAR)                               | SAR  |
| Serbian Dinar (2002-2006) (CSD)                 | CSD  |
| Serbian Dinar (RSD)                             | RSD  |
| Seychellois Rupee (SCR)                         | SCR  |
| Sierra Leonean Leone (SLL)                      | SLL  |
| Silver (XAG)                                    | XAG  |
| Singapore Dollar (SGD)                          | SGD  |
| Slovak Koruna (SKK)                             | SKK  |
| Slovenian Tolar (SIT)                           | SIT  |
| Solomon Islands Dollar (SBD)                    | SBD  |
| Somali Shilling (SOS)                           | SOS  |
| South African Rand (ZAR)                        | ZAR  |
| South African Rand (financial) (ZAL)            | ZAL  |
| South Korean Hwan (1953-1962) (KRH)             | KRH  |
| South Korean Won (1945-1953) (KRO)              | KRO  |
| South Korean Won (KRW)                          | KRW  |
| Soviet Rouble (SUR)                             | SUR  |
| Spanish Peseta (A account) (ESA)                | ESA  |
| Spanish Peseta (ESP)                            | ESP  |
| Spanish Peseta (convertible account) (ESB)      | ESB  |
| Special Drawing Rights (XDR)                    | XDR  |
| Sri Lankan Rupee (LKR)                          | LKR  |
| Sudanese Dinar (1992-2007) (SDD)                | SDD  |
| Sudanese Pound (1957-1998) (SDP)                | SDP  |
| Sudanese Pound (SDG)                            | SDG  |
| Surinamese Dollar (SRD)                         | SRD  |
| Surinamese Guilder (SRG)                        | SRG  |
| Swazi Lilangeni (SZL)                           | SZL  |
| Swedish Krona (SEK)                             | SEK  |
| Swiss Franc (CHF)                               | CHF  |
| Syrian Pound (SYP)                              | SYP  |
| São Tomé and Príncipe Dobra (STD)               | STD  |
| Tajikistani Ruble (TJR)                         | TJR  |
| Tajikistani Somoni (TJS)                        | TJS  |
| Tanzanian Shilling (TZS)                        | TZS  |
| Testing Currency Code (XTS)                     | XTS  |
| Thai Baht (THB)                                 | THB  |
| Timorese Escudo (TPE)                           | TPE  |
| Tongan Paʻanga (TOP)                            | TOP  |
| Trinidad and Tobago Dollar (TTD)                | TTD  |
| Tunisian Dinar (TND)                            | TND  |
| Turkish Lira (1922-2005) (TRL)                  | TRL  |
| Turkish Lira (TRY)                              | TRY  |
| Turkmenistani Manat (1993-2009) (TMM)           | TMM  |
| Turkmenistani Manat (TMT)                       | TMT  |
| US Dollar (Next day) (USN)                      | USN  |
| US Dollar (Same day) (USS)                      | USS  |
| **US Dollar (USD)**                                 | USD  |           **<==== YES, also installed !**
| Ugandan Shilling (1966-1987) (UGS)              | UGS  |
| Ugandan Shilling (UGX)                          | UGX  |
| Ukrainian Hryvnia (UAH)                         | UAH  |
| Ukrainian Karbovanets (UAK)                     | UAK  |
| United Arab Emirates Dirham (AED)               | AED  |
| Unknown Currency (XXX)                          | XXX  |
| Uruguayan Peso (1975-1993) (UYP)                | UYP  |
| Uruguayan Peso (Indexed Units) (UYI)            | UYI  |
| Uruguayan Peso (UYU)                            | UYU  |
| Uzbekistan Som (UZS)                            | UZS  |
| Vanuatu Vatu (VUV)                              | VUV  |
| Venezuelan Bolívar (1871-2008) (VEB)            | VEB  |
| Venezuelan Bolívar (VEF)                        | VEF  |
| Vietnamese Dong (1978-1985) (VNN)               | VNN  |
| Vietnamese Dong (VND)                           | VND  |
| WIR Euro (CHE)                                  | CHE  |
| WIR Franc (CHW)                                 | CHW  |
| Yemeni Dinar (YDD)                              | YDD  |
| Yemeni Rial (YER)                               | YER  |
| Yugoslavian Convertible Dinar (1990-1992) (YUN) | YUN  |
| Yugoslavian Hard Dinar (1966-1990) (YUD)        | YUD  |
| Yugoslavian New Dinar (1994-2002) (YUM)         | YUM  |
| Yugoslavian Reformed Dinar (1992-1993) (YUR)    | YUR  |
| Zairean New Zaire (1993-1998) (ZRN)             | ZRN  |
| Zairean Zaire (1971-1993) (ZRZ)                 | ZRZ  |
| Zambian Kwacha (ZMK)                            | ZMK  |
| Zimbabwean Dollar (1980-2008) (ZWD)             | ZWD  |
| Zimbabwean Dollar (2008) (ZWR)                  | ZWR  |
| Zimbabwean Dollar (2009) (ZWL)                  | ZWL  |
+-------------------------------------------------+------+

**Comment by RogerKeulen** [comment]
Solved the currency "on save" message.

`SELECT * FROM `core_config_data` WHERE `path` LIKE '%currency%'`

And just delete everything..... because why not.....

So, i can save now: 
![mag2-settings-error-ok](https://user-images.githubusercontent.com/14263822/31718578-c1bf0d14-b410-11e7-94c6-1d19d62fbe27.png)

Still did not solve any thing but i don't get confusing "trying to help" messages. That have notthing to do with checkboxes unchecked while pull-down boxes disabled.

**Comment by RogerKeulen** [comment]
According to the documentation (a `manual` with only things that works) your still allowed to hack the database Magento 1 style.

[Magento 2 DevDocs - Varnish](http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish-magento.html)

Here is there query to do this:
`mysql -u root -p -D magento -e "INSERT INTO core_config_data ( scope, scope_id, path, value ) VALUES ( 'default', '0', 'system/full_page_cache/caching_application', '2') ON DUPLICATE KEY UPDATE value = 2;"`

So, i looked in the DB and it is already on "2". (apperently this should be Varnish then)


Thus we can conclude:

**The settings i'm seeing in the backend don't have to reflect the `real` used settings at all.**

**Comment by magento-engcom-team** [comment]
@RogerKeulen, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by RogerKeulen** [comment]
No problem, i will upgrade to 2.20 as fast as possible. And do a re-install and backup my db this time after setup. Than i also can create a diff that i can't right now, so i don't know if it's core_config_data related.

**Comment by springerin** [comment]
Same here with version 2.2.3, I am going try to do it on a clean installation.
