### ISSUE TITLE
My Requisition Lists link and lists sometimes disappears from My Account top menu (Luma Theme) and "add to requisition list" dropdown options

### ISSUE THREAD

**Issue by boardwalki** [magento/magento2#11531]
### Preconditions

1. Magento EE v2.2, PHP 7.0.8
2. 

### Steps to reproduce

1. Login as sample user with sample data installed
2. View "Womens > Tops" category
3. Click on Stellar Solar Jacket

### Expected result

1. Link should always be present in dropdown menu when logged in.

### Actual result

1. My Requisition Lists menu option disappears. Also under "Add to Requisition List" under Add to Cart Button, existing requisition lists are missing and only option is to Create new Requisition list.

**Comment by magento-engcom-team** [comment]
@boardwalki , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by 0franco** [comment]
Any news?
