### ISSUE TITLE
Can't add item to cart from requisition list

### ISSUE THREAD

**Issue by boardwalki** [magento/magento2#11530]
### Preconditions

1. When trying to add item to cart from a Requisition List it says "Product that you are trying to add is not available." even though it is available. 
2. Magento 2.2 EE

### Steps to reproduce

1. View sample item SKU WS12 (Radiant Tee) and add item to a requisition list (XS, Orange).
2. View that requisition list then check the box for this item and click "add to cart"
3. 

### Expected result

1. Item should add to cart. If you view the item details page for SKU WS12 you can add the XS Orange option to cart, but if you try to add it from a requisition list it will not allow.

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@boardwalki, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
