### ISSUE TITLE
Sortable Requisition List Items

### ISSUE THREAD

**Issue by brian-labelle** [magento/magento2#11547]
As a customer, I would like to sort my wishlist or requisition list items individually so that I can can group products together and organize my lists

### Preconditions
1. Magento 2.2 w/B2B extension

### Expected result
1. While on a requisition list with more than one item
2. Dragging my items will change their order within the list
3. On drop, the item position will be saved via ajax
4. On refresh, my item positions will be preserved

**Comment by brian-labelle** [comment]
I've implemented this feature using https://github.com/RubaXa/Sortable

**Comment by magento-engcom-team** [comment]
Hi @brian-labelle. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/17
