### ISSUE TITLE
Cant Install Composer On Local MAMP Setup

### ISSUE THREAD

**Issue by webprostudio** [magento/magento2#1154]
I had a go at installing Magento 2 on my local MAMP setup and am getting hit with the following error message when trying to install composer:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-mcrypt * is missing from your system.
  Problem 2
    - The requested PHP extension ext-intl * is missing from your system.

The above PHP extensions have definitely been installed so can't understand why it can't detect them. Has anybody else experienced an issue like this one?

**Comment by alihalabyah** [comment]
@webprostudio You need to make sure that the PHP you installed/enabled these extensions on, is the same PHP being used by MAMP

**Comment by mbrinton01** [comment]
@alihalabyah this is probably the issue. If you have another PHP besides the Macports install, you need to make sure that you have installed the extensions properly.

You can see if your path to php is correct with ``which php`` - for the default install this should return ``/opt/local/bin/php``. Also view the PHP version with ``php -v`` and then run ``port installed php*`` to check which extensions are present.

**Comment by webprostudio** [comment]
Thank you both for your feedback. You are correct, Magento 2 seems to be using MAC php rather than MAMP. Is there a way that I can set which php Magento 2 uses?

I have mcrypt and all other extensions installed on my MAMP php but not my MAC.

**Comment by mbrinton01** [comment]
Did you follow the install steps on the Macports site, such as:  https://trac.macports.org/wiki/howto/MAMP?

You can also check your path with ``echo $PATH`` to see if the Mac PHP location is listed ahead of the Macports location.

**Comment by mbrinton01** [comment]
@webprostudio please let us know if you have been able to resolve your install issue.

**Comment by mbrinton01** [comment]
@webprostudio because we did not receive a response we are closing this issue. If you are still having trouble with your install, please reopen the issue and provide more explanation.

**Comment by webprostudio** [comment]
Apologies for the delay in getting back to you on this.I installed the missing extensions using macports and that resolved the issue. I now have issues with the version of MySQL that MAMP uses so am now looking to upgrade SQL to 5.6.

**Comment by mbrinton01** [comment]
Thank you for the update and glad to hear you resolved the composer issue.
