### ISSUE TITLE
Doc blocks matter for DI

### ISSUE THREAD

**Issue by andrewhowdencom** [magento/magento2#11545]
### Preconditions

1. Magento 2.2
2. PHP 7.0

Rest is irrelevant

### Steps to reproduce

1. Type hint a class incorrectly. For example, instead of `null` or the correct type, use `string` or `[]`. 
2. Use DI for that classes constructor injection.
3. Watch DI explode:

```
	__VENDOR__\__EXTENSION__\Model\ResourceModel\Job\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: string; File: 
/var/www/html/vendor/__VENDOR__/__EXTENSION__/Model/ResourceModel/Job/Grid/Collection.php

Total Errors Count: 1
```

Happened in two cases;

1. string|null (null was fine)
2. [], not array

### Expected result

1.  Unsure. Probably shouldn't pay attention to doc blocks.
2. Alternatively, mark the change here: http://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes.html

https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/Code/Reader/ArgumentsReader.php#L81
aaand here: https://github.com/zendframework/zend-code/blob/master/src/Reflection/ParameterReflection.php#L101
added here in 2.2: https://github.com/magento/magento2/commit/34cb6b6d214088219a35794678f74e78746b0c43

Unsure whether this *should* happen; only that it does, and I hadn't expected it to. If it should happen, please close this.

**Comment by andrewhowdencom** [comment]
cc @sidolov as the authorr

**Comment by orlangur** [comment]
I believe the main reason for PHPDoc to be taken into account is https://stackoverflow.com/questions/3840094/is-it-possible-to-specify-more-than-one-type-hint-for-a-parameter. If I remember correctly there is a recommendation in Setup Guide to not enable comments stripping in opcode cacher.

I wouldn't treat such change as backward-incompatible as developers are not supposed to create invalid PHPDocs in the first place.

If you have `Type1|Type2` declaration, pass `Type1` or `Type2` and it does not work - it's a bug. Otherwise everything seems fine, https://en.wikipedia.org/wiki/Fail-fast approach in action.

**Comment by pocallaghan** [comment]
Was there an actual change relating to this? It does indeed sound akin to "If you specify a type hint, it's going to break if you don't pass it that type". But if it never previously had a type hint (i.e. the DocBlocks weren't previously parsed, thus "type hints" are 'magically' appearing in lots of places they weren't previously), this definitely sounds like a BC break to me and thus should be included in the changes list.

**Comment by orlangur** [comment]
@pocallaghan you can check the commit from issue description. I don't see which item of http://devdocs.magento.com/guides/v2.1/contributor-guide/backward-compatible-development/index.html corresponds to this situation.

**Comment by andrewhowdencom** [comment]
As @pocallaghan pointed out, it's the silent introduction of new behaviour that I found most irritating. The public interface of (at least) constructor methods was just silently increased, and there's now ambiguity as to what to trust -- doc block hint or in typehint in the method signature?

I don't think BC breaks is a reasonable point from which to argue, as this is a new interface (akin to a new language feature) and thus cannot be established with BC.  Alternatively, either of these seem reasonable points to me: 

http://devdocs.magento.com/guides/v2.1/contributor-guide/backward-compatible-development/index.html
> Modifying the default values of optional arguments in public and protected methods 
> Adding parameters in public methods 

given that this change introduces the adherence to type hints it previously did not.

**Comment by orlangur** [comment]
> there's now ambiguity as to what to trust -- doc block hint or in typehint in the method signature?

Doc block must not contradict to typehint, you should trust both of them but you can specify only one type in typehint.

> Modifying the default values of optional arguments in public and protected methods
> Adding parameters in public methods

Not applicable.

> __VENDOR__\__EXTENSION__\Model\ResourceModel\Job\Grid\Collection
>		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: string; File: 
> /var/www/html/vendor/__VENDOR__/__EXTENSION__/Model/ResourceModel/Job/Grid/Collection.php

> Total Errors Count: 1

Seems to be a mistake in PHPDoc, in core there was `string` specified before in commit you mentioned:

```
-     * @param string|null $connection
+     * @param \Magento\Framework\DB\Adapter\AdapterInterface|string|null $connection
```

Do you have any examples of logically correct code with started to fail with upgrade?

**Comment by andrewhowdencom** [comment]
```
    /**
     * @param \Magento\Framework\Data\Collection\EntityFactoryInterface $entityFactory
     * @param \Psr\Log\LoggerInterface $logger
     * @param \Magento\Framework\Data\Collection\Db\FetchStrategyInterface $fetchStrategy
     * @param \Magento\Framework\Event\ManagerInterface $eventManager
     * @param \Magento\Store\Model\StoreManagerInterface $storeManager
     * @param string $mainTable
     * @param string $eventPrefix
     * @param string $eventObject
     * @param string $resourceModel
     * @param string $model
+     * @param null $connection
-     * @param string|null $connection
     * @param \Magento\Framework\Model\ResourceModel\Db\AbstractDb $resource
     *
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     */
    public function __construct(
        \Magento\Framework\Data\Collection\EntityFactoryInterface $entityFactory,
        \Psr\Log\LoggerInterface $logger,
        \Magento\Framework\Data\Collection\Db\FetchStrategyInterface $fetchStrategy,
        \Magento\Framework\Event\ManagerInterface $eventManager,
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        $mainTable,
        $eventPrefix,
        $eventObject,
        $resourceModel,
        $model = 'Magento\Framework\View\Element\UiComponent\DataProvider\Document',
        $connection = null,
        \Magento\Framework\Model\ResourceModel\Db\AbstractDb $resource = null
    ) {
        parent::__construct(
            $entityFactory,
            $logger,
            $fetchStrategy,
            $eventManager,
            $storeManager,
            $connection,
            $resource
        );

        $this->_eventPrefix = $eventPrefix;
        $this->_eventObject = $eventObject;
        $this->_init($model, $resourceModel);
        $this->setMainTable($mainTable);
    }
```

More generally, I think I'm happy leaving this here as is. I hadn't realised there was already some precedent for parsing doc blocks, and this change is thus not entirely unpredictable.

I think my pre-existing feelings about AOP might have clouded my judgement here. 

<3 for patience.

**Comment by orlangur** [comment]
Aha, it happened to me multiple times - autogenerated constructor signature :)

Thanks for your report, I wasn't aware Magento relies on PHPDoc that much (like Doctrine does) and that it is so strict about them.
