### ISSUE TITLE
Magento sets iso invalid language code in html header

### ISSUE THREAD

**Issue by v0gler** [magento/magento2#11540]
### Preconditions

1. Using Magento 2.1.8

### Steps to reproduce

1. Using magento with german language 

### Expected result

1. Html header of page should be `<html lang="de">`

### Actual result

1. Html header is `<html lang="de-DE">`

This comes from the code in the constructor of framework/View/Page/Config.php
`$this->setElementAttribute(
            self::ELEMENT_TYPE_HTML,
            self::HTML_ATTRIBUTE_LANG,
            str_replace('_', '-', $this->localeResolver->getLocale())
        );
`

"de-DE" is no valid iso language code. (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
If you are using word-breaks with hyphenation in css like: 

`word-break: break-word;
  hyphens: auto; 
`
You get the result that the hyphens aren't correctly set or no hyphens are set based on the wrong language code. With correct language code, in this case "de", hyphenation is working as expected with german language.

**Comment by magento-engcom-team** [comment]
@SirElectro, thank you for your report.
We've created internal ticket(s) MAGETWO-82274 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82431

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82664

**Comment by sidolov** [comment]
Hi @SirElectro. Thank you for your report. 
The issue has been fixed in magento/magento2#17212 by @mageprince in 2.1-develop branch
Related commit(s):
 - [6702cdce13957b10dbf29a4a00e17eba6f97c982](https://github.com/magento/magento2/commit/6702cdce13957b10dbf29a4a00e17eba6f97c982)

The fix will be available with the upcoming 2.1.15 release.
