### ISSUE TITLE
Systems --> Backup function is still faulty (has been for years)

### ISSUE THREAD

**Issue by ghost** [magento/magento2#11543]
I've been using Magento since version 1.7. As of today I have begun a new project using Magento 2.1.7.  I really love the new look and feel and efficiency. However I am still experiencing the failure of the Backup function in the admin panel.  Accessing it through the Systems tab, then clicking on Backups, it takes you to the screen where you can name and start a System Backup.  I have done this in order to preserve my Fresh Install.  However it never records that the backup was successful, neither does the system list the named Backup just attempted. I find that the Backup has indeed been successful. However, Magento is sending the Backup SQL to the /var directory on the root, and there seems to be a ~temp TAR file with the rest of the backup inside of the /var/backups directory.  However, it has the ~tmp prefix before the file name which leads me to believe that the Backup did not complete it's entire procedure.  This Backup failure I also replicated in a Magento 1.9 setup that I tested a few months back.  

### Preconditions
I am using Linux; Magento 2.1.7, PHP version 7.0 & MySQL version: 5.6.36-cll-lve
Database client version: libmysql - 5.1.73
PHP extension: mysqli  

### Steps to reproduce
1. Log into Magento 2.1.7 Admin Panel
2. Navigate to System tab (on left)
3. Click "Backups" under the Tools section
4. Click the "System" button to initiate a System back up
5. Enter a backup Name (do not check the "Please put store in maintenance mode", also do not check the "exclude media" checkboxes.
6. Click OK button and wait until backup is finished.
7. Refresh to see that nothing is recorded
8. Navigate to your hosting files on your root server and visit the /var directory to see the SQL of the recently attempted backup will be there with a number as the file name instead of the name you chose (also note that this SQL is not properly sent to the /var/backups folder)
9. Navigate to the /var/backups directory to see that a tar file has been generated with the same temporary number as the newly generated SQL, but this tar file is a temp file.

### Expected result
1. ALL backups that are initiated in the System-->Backups window of the admin panel should be listed there with the appropriate name that you gave and the appropriate saved parameters (saving only media or saved entire system, etc)  Also, the items should go to the /var/backups directory in the hosting files as expected. The expected result is that this function should work properly and execute a backup fully with it being listed and able to properly execute a rollback if necessary as well.

### Actual result

1. [Screenshot, logs] Instead nothing is listed after trying to perform a backup
![image](https://user-images.githubusercontent.com/32904244/31724939-1810a9ae-b3f1-11e7-8ff1-64a3ef71e193.png)

**Comment by magento-engcom-team** [comment]
@MyVisitReUP, thank you for your report.
We've created internal ticket(s) MAGETWO-82320 to track progress on the issue.

**Comment by osrecio** [comment]
Investigating

**Comment by osrecio** [comment]
I am working on it at #mm17es

**Comment by osrecio** [comment]
I can't reproduce this error with fresh `2.1-develop` branch, the problem described can be generated by a error with `stat()` function. Can be good if a `Exception` occurred delete the tmp file

**Comment by magento-engcom-team** [comment]
@MyVisitReUP, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
