### ISSUE TITLE
Can't change settings in backend configuration

### ISSUE THREAD

**Issue by RogerKeulen** [magento/magento2#11542]
Can't change settings in backend configuration for global scope.

### Preconditions
1. Magento ver. 2.2.0-rc23

### Steps to reproduce
1. Download Magento.
2. Install it and wait a couple of minutes.
3. Go to backend and try to change something on global scope.

### Expected result
1. I expect checkboxes that are enabled.

### Actual result
Can't un-check checkboxes there disabled. Can change setting, it's disabled.

![backend](https://user-images.githubusercontent.com/14263822/31723395-01eb50c4-b41f-11e7-9351-5d80451512ab.png)

**Comment by magento-engcom-team** [comment]
@RogerKeulen, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by leabaertschi** [comment]
I have the same issue with magento-2.2.2, I can't uncheck the `Use system value` checkboxes and when editing some value in other places and save the config, it just won't really change it, although I get the confirmation that it was saved. Have you figured out what your problem was?

EDIT: figured it out, it was because I dumped my config to `config.php`

**Comment by EugenOrosan** [comment]
@leahaense How did you fixed this ? I know it is because i dumped my config.php, but what should I do in order to have the fields editable again ?

**Comment by leabaertschi** [comment]
@EugenOrosan check this out: https://magento.stackexchange.com/questions/196912/appconfigdump-locks-everything-in-configuration, that helped me

**Comment by markdimi** [comment]
Isn't there a way to make all the fields editable again?

**Comment by leabaertschi** [comment]
in theory I would assume if you remove the configs from `app/etc/config.php` and then run `./bin/magento app:config:import` it should make them editable again. I haven't figured out what to remove exactly though, deleting the whole file is not working. You probably have to keep the first level of the config array and just assign empty arrays everywhere.

**Comment by markdimi** [comment]
You mean you tried removing the file and it didn't work? Maybe remove only
part of the file. The part with the admin settings.

Στις Πέμ, 24 Μαΐ 2018, 10:30 π.μ. ο χρήστης Lea Hänsenberger <
notifications@github.com> έγραψε:

**Comment by leabaertschi** [comment]
Exactly, remove only the config parts that you want to be editable again in the admin interface from the config file and then import that config with `./bin/magento app:config:import`

**Comment by markdimi** [comment]
Well I suppose I could use this method for now. :) Cheers

Στις Πέμ, 24 Μαΐ 2018, 12:26 μ.μ. ο χρήστης Lea Hänsenberger <
notifications@github.com> έγραψε:

**Comment by markdimi** [comment]
How could I pinpoint a setting from admin to the file? I am trying to
change a setting , say in stores, configuration, general, web, auto
redirect to base url.

Στις Πέμ, 24 Μαΐ 2018, 12:34 μ.μ. ο χρήστης Markos Dimijazz <
dimitsas.markos@gmail.com> έγραψε:

**Comment by leabaertschi** [comment]
I usually inspect the input element in the browser, from it's id and name you can usually derive the actual configuration path

**Comment by Rickertje** [comment]
I got a "Import failed: Unable to unserialize value, string is corrupted." running ./bin/magento app:config:import after changing the config.php. Any idea?

**Comment by leabaertschi** [comment]
check #11899

**Comment by markdimi** [comment]
I have another issue. I see that in stores - configuration, I have
translate inline for storefront to yes. Also on the app/etc/config file.
But no inline translation occurs. And I am thinking, what else might behave
like this? Also, is it adviced to make changes on another scope that is
editable? Say, main stores scope.

Στις Πέμ, 24 Μαΐ 2018, 2:38 μ.μ. ο χρήστης Lea Hänsenberger <
notifications@github.com> έγραψε:
