### ISSUE TITLE
Attribute Set not changing

### ISSUE THREAD

**Issue by imrandiligent** [magento/magento2#11557]
### Preconditions

1. Magento 2.1.9
2. PHP 4.7.0

### Steps to reproduce

1. As per your forum, i do all the changes
2. 
3. 

### Expected result

1.  When i am going add a product  by default in attribute set it comes default when i am going to change the attribute set its loading continuously not getting any result.

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@imrandiligent We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, and any other information needed to reproduce your issue.

**Comment by imrandiligent** [comment]
Preconditions

Magento ver. 2.1.9
PHP version: 4.7.0

Steps to reproduce

Create new Attribute Set (Stores > Attributes > Attribute Set) Suits
Create new Configurable Product (Products > Inventory > Catalog > Add Products > Configurable Product)
Select Custom Attribute Set (Suits)
ScreenShot
http://prntscr.com/g9kij6

Expected result

Create New Configurable Product with Custom Attribute set (Suits)

Actual result

After Select Custom Attribute Set (Suits) Page stuck on loading.
Screenshot
http://prntscr.com/g9kkat

Please guide me to remove these issue

**Comment by magento-engcom-team** [comment]
@imrandiligent, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
