### ISSUE TITLE
Admin orders account information showing guest for customer name

### ISSUE THREAD

**Issue by dbag1010101** [magento/magento2#11552]
Using magento v2.2.0. Through the api, i'm creating a guest cart and proceed to add items to the cart. I then log in a user and add the customer id to the cart and use the carts/mine api to put the modified cart. After checkout, the order shows up on the admin panel with the account information showing guest and no email. When you click on guest, it directs you to the correct customer account with the name and email address there.

### Preconditions

1. php v7.0
2. 

### Steps to reproduce

1. Add items to guest cart. proceed to assign cart to a logged in customer
2. Complete checkout process 
3. 

### Expected result

1. I would assume that the order page should show the account information of the account which placed the order without having to click on guest link

### Actual result

1. Customer Name: guest
2. Email: __blank__ <- doesn't say blank. There is nothing there

**Comment by orlangur** [comment]
> Through the api, i'm creating a guest cart and proceed to add items to the cart. I then log in a user and add the customer id to the cart

Why do you need such flow?

**Comment by magento-engcom-team** [comment]
@meeweed , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by dbag1010101** [comment]
> Why do you need such flow?

Well, basically, the flow would be for users which are not logged in while shopping and then log in at the checkout stage. I can try adding the items from one cart to the other.

**Comment by dbag1010101** [comment]
> We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

What information would be helpful. 
1. Basically. I create a guest cart. I then add items to that cart. 
2. User logs in and I append the customer id to the guest cart. logged in user now has guest cart assigned. 
3. logged in user proceeds to checkout and gets confirmation. 
4. Inside admin panel, the order shows account information as "Guest" as a hyper link and the other two columns are empty(ie. email has no value and Customer group isn't showing.

**Comment by dbag1010101** [comment]
![account_info](https://user-images.githubusercontent.com/28773115/31790317-f0acba4a-b4c9-11e7-947f-135b4158b47a.jpg)

As you can see, the Customer name (in blue) is a link. This link takes you to the actual customer account

**Comment by orlangur** [comment]
@meeweed, thanks for details

> 2. User logs in and I append the customer id to the guest cart. logged in user now has guest cart assigned.

Basically, I'm not sure such flow is supposed to work but I'm not familiar with this API implementation details. Maybe you should create non-guest cart with a separate request.

**Comment by dbag1010101** [comment]
Hello @orlangur 
> Basically, I'm not sure such flow is supposed to work but I'm not familiar with this API implementation details. Maybe you should create non-guest cart with a separate request.

thank you. I figured that doing that should be my next step.

**Comment by magento-engcom-team** [comment]
@meeweed, thank you for your report.
We've created internal ticket(s) MAGETWO-83339 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
The described flow is not valid. Please look at @orlangur  suggestion. Closing as non-issue

**Comment by dbag1010101** [comment]
I fixed it using the hack but honestly, this should work as I outlined. The hack @orlangur recommeded (and the one which I had already done) involves many queries for multiple items  in an asynchronous environment.
