### ISSUE TITLE
Store switching is occasionally not working

### ISSUE THREAD

**Issue by sigismund** [magento/magento2#11558]
### Preconditions

1. Magento 2.2
2. 3 different stores (sl, en, hr)

### Steps to reproduce

1. Enabled "Add Store Code to Urls"
2. (Not sure which other options could affect this behavior )

### Expected result

1. When changing language in dropdown, the website should change

### Actual result

1. If I try to switch from Slovenian product to English version of it, request is sent from `/sl/testing-example` to `/en/testing-example`(example). After that `/en/testing-example` redirects (302) back to `/sl/testing-example`. I tried changing slug of english product and in some cases I even got 404 response.

**Comment by magento-engcom-team** [comment]
@sigismund, thank you for your report.
We've created internal ticket(s) MAGETWO-82338 to track progress on the issue.

**Comment by thiagolima-bm** [comment]
PR #11337 should solve this problem @vkublytskyi

**Comment by vkublytskyi** [comment]
@thiagolima-bm, yes this issue already fixed and will be released with next 2.2.x patch release

**Comment by sigismund** [comment]
Is this supposed to be included in Magento 2.2.1?

**Comment by vkublytskyi** [comment]
@sigismund this fix will be released with Magento 2.2.2
