### ISSUE TITLE
Cachewall (xVarnish) Config

### ISSUE THREAD

**Issue by TenGauge** [magento/magento2#11570]
Does anyone know how to properly configure Cachewall xVarnish to work with Magento 2?  I have tried to split up the generated VCL file in to the proper local files supplied by Cachewall to generate its active VCL but I can not get X-Magento-Cache in to the header.  Varnish is working properly and serving the content, but from the backend rather than cache due to it not being passed the X-Magento-Cache control headers.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
