### ISSUE TITLE
Wishlist Add Event Miss Validation

### ISSUE THREAD

**Issue by SlavaYurthev** [magento/magento2#11571]
### Steps to reproduce
1.  Create Custom Form Of Product Add To Wishlist
2.  Call For This Form data-mage-init='{"addToWishList":{}}'

### Expected result
1. Submit Form If All Required Fields Are Set

### Actual result
1. Form will be submit at anyway

### Comment
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Wishlist/view/frontend/web/js/add-to-wishlist.js#L199-L227 
this is code part of issue, should have if(form.validation())

date-mage-init='{"validation":{}}' - ignored

**Comment by orlangur** [comment]
Which form fields are supposed to be validated in core when you press `'Add to Wish List'`?

**Comment by orlangur** [comment]
> `$(form).attr('action', action).submit();`

Form validation must be triggered by this code actually. There is no need to add some custom code like `if(form.validation())`.

**Comment by SlavaYurthev** [comment]
no, not core fields\forms, i have custom form with bundle options and needs use this script for the correctly form serialize, and for example fields with data-validate="{'some_rule':true}" are passed validation at the any way....

**Comment by orlangur** [comment]
There is nothing to fix here from core perspective if there are no fields in core which are supposed to be validated. You need to fix your own implementation instead.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
