### ISSUE TITLE
Can´t add products to Shopping cart afther upgrading from 2.1.9 to 2.2 CE

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#11575]
### Preconditions

1. Can´t add item to cart afther upgrading
2. Magento upgraded from 2.1.9 to 2.2 CE

### Steps to reproduce

1. We add a product to shopping cart

### Expected result

1. Item should add to cart

### Actual result

1. Shopping cart is empty

**Comment by magento-engcom-team** [comment]
@salelsol, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by salelsol** [comment]
I´m now upgrading from 2.1.9 to 2.2.1 and I´m same issue. When we add a product to shopping cart, cshopping cart is empty:
![cart_2_2_1](https://user-images.githubusercontent.com/16081377/32549448-c6220daa-c489-11e7-8bf6-0bd683939130.jpg)
