### ISSUE TITLE
'Change email' email outputs 'thanks, [store name]' twice

### ISSUE THREAD

**Issue by mattgreenfield** [magento/magento2#11579]
### Preconditions

Magento 2.1.7

### Steps to reproduce

1. As a logged in user, change your password and/or email address
2. View the email that is sent to you

### Expected result

The email is signed `thanks, [shop name]

### Actual result

 The email is signed off twice;
> Thanks, [Shop Name]
> Thank You, [Shop Name]!

This is because the default email footer already signs the email
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Email/view/frontend/email/footer.html#L17

And then the account emails do it again, and add that default footer.
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/view/frontend/email/change_email_and_password.html#L20
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/view/frontend/email/change_email.html#L20

If this is a confirmed issue, I am happy to make a pull request to remove the signature from from the Magento/Customer module.
For backwards compatibility? I'm not sure.

**Comment by magento-engcom-team** [comment]
@mattgreenfield, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
