### ISSUE TITLE
Custom product attribute in a search.

### ISSUE THREAD

**Issue by epolish** [magento/magento2#11573]
### Preconditions

1. PHP 5.6.31
2. Apache 2.4.26
3. MariaDB 10.1.25 - mariadb.org binary distribution
4. Magento CE 2.1.8 with installed sample data from archive.

### Steps to reproduce

1. Create product attribute programmatically (in InstallData.php) with this options
```
'type' => 'text',
'backend' => '',
'frontend' => '',
'label' => 'Keywords',
'input' => 'text',
'class' => '',
'source' => '',
'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
'visible' => true,
'required' => false,
'user_defined' => false,
'default' => '',
'searchable' => true,
'filterable' => false,
'comparable' => false,
'visible_on_front' => false,
'used_in_product_listing' => true,
'visible_in_advanced_search' => true,
'unique' => false,
'apply_to' => ''
```
2. Install your extension via setup:upgrade.
3. In some product, fill this attribute with some text.
4. Run indexer:reindex.
5. Try to use this text in frontend search.

### Expected result

1. The search result should return products with this, custom attribute (if it's not empty of course)

### Actual result

1. The search returned no results.
![search_result](https://user-images.githubusercontent.com/19210241/31807483-16cc5e3a-b577-11e7-8ff3-50f8e3930617.png)

**Comment by magento-engcom-team** [comment]
@epolish, thank you for your report. 
Looks like you filled attribute with "some text", but you were searching "sometext". So it is the reason why results are empty.

**Comment by epolish** [comment]
I also tried with "some text" - separately. And tried with single words...

**Comment by magento-engcom-team** [comment]
@epolish, we were not able to reproduce this issue by following the steps you provided. Here is our screenshot: 
![screenshot from 2017-10-20 15-58-16](https://user-images.githubusercontent.com/31669971/31822321-0b9b6c1a-b5b1-11e7-992a-89877c76ba20.png)

We tried it on 2.1.9, 2.2.0-rc3.0 and latest develop branches.
Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

**Comment by epolish** [comment]
Did you create this extension via custom module setup (not in admin interface)?

**Comment by epolish** [comment]
[Eleanorsoft.zip](https://github.com/magento/magento2/files/1405935/Eleanorsoft.zip)
Install this extension. And reproduce all next steps.

**Comment by magento-engcom-team** [comment]
@epolish, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by miro-kodet** [comment]
I just faced very similar issue and, actually, this really doesn't seem to be a bug. Magento searches text/varchar attributes as follows (shortened query):

`SELECT * FROM catalogsearch_fulltext_scope1 where MATCH (data_index) AGAINST ('+testtext' IN BOOLEAN MODE);`

and scores the result. I suppose the attribute is properly set (visible and searchable) and product is available, then, based on above mentioned MATCH is trying get any result based on attribute ID in search index. 

And as needle could be divided into multiple words, it tries to search each of them. But then you could reach MySQL/MariaDB limits as `innodb_ft_min_token_size` and/or `innodb_ft_min_token_size` might be set to higher value, then searched text (single word). In my case I had to reduce the to 1, restart MySQL server and rebuild indexes.

In @epolish case the "sometext" simply did not exist and "some text" single words could be shorter than above mentioned global variables.

Maybe it helps someone.

**Comment by amon81** [comment]
I've the same problem with other custom attribute field...
            ''type' => 'text',
            'backend' => '',
            'frontend' => '',
            'label' => 'Titolo, sottotitolo',
            'input' => 'text',
            'class' => '',
            'source' => '',
            'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
            'visible' => true,
            'required' => false,
            'user_defined' => false,
            'default' => '',
            'searchable' => true,
            'filterable' => false,
            'comparable' => false,
            'visible_on_front' => false,
            'used_in_product_listing' => true,
            'unique' => false,
            'apply_to' => '',
            "searchable" => true,
            'visible_in_advanced_search' => true


No result find in advanced search field... why??
