### ISSUE TITLE
Something went wrong with the subscription.

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2#1157]
When try registrer email newsletter subscription.

![01](https://cloud.githubusercontent.com/assets/2263217/6950324/7803f792-d890-11e4-9377-cd048bd968df.png)

Return this alert ...

Something went wrong with the subscription.

![02](https://cloud.githubusercontent.com/assets/2263217/6950328/832b8220-d890-11e4-90e5-9b36643d776e.png)

**Comment by kokoc** [comment]
@cerebrumbr thank you for reporting the issue. Internal reference: MAGETWO-36266

**Comment by vpelipenko** [comment]
Hi @cerebrumbr, we've fixed this issue and its fix is available in 0.74.0-beta8. Could you check it?

**Comment by cerebrumbr** [comment]
Hello @vpelipenko - Perfect now, good job.

**Comment by serajin** [comment]
Sorry to reopen this issue. I am on Community release 2.0.4, and I am receiving the same issue as this original post. Is there any new fix to this?

Below is an image of the error.
http://puu.sh/oxl0j/f27b68b5ca.png

**Comment by jonpwoolley** [comment]
I also am having the same issue on Community 2.0.5.

**Comment by bonsdawende** [comment]
Hi, How have you resolved this problem ? Please, I have this problem with Magento 2.0.7?

**Comment by abhijitbanik2016** [comment]
I installed Magento 2.1 in a domain www.craftallure.com

Then configured magento SMTP with following credential
Authentication method: Login
SSL type: SSL
Port: 465
SMTP Host: smtp.gmail.com	
Username: info@dotkiwis.com
Password: ************

Then after doing these steps but finding error:

Step 1: Open this URL: https://www.craftallure.com/

Step 2: Fill any email address in subscription form footer and click subscribe.

Step 3: Then this error will be visible in red error note. 
"Something went wrong with the subscription."


![image](https://cloud.githubusercontent.com/assets/20184139/21966548/7117b1ca-db9b-11e6-8dab-9afe648fa855.png)

Is there anyone got any proper update on it? 
If any update it will be great help.

`This is exception error message I copied here. It might can give some light

[2017-01-07 20:47:11] main.CRITICAL: Exception message: Could not open socket
Trace: #0 /home/craftallure/public_html/vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php(124): Magento\Newsletter\Model\Subscriber->subscribe('abhijitindesign...')
#1 /home/craftallure/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Newsletter\Controller\Subscriber\NewAction->execute()
#2 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', Array)
#4 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'contextPlugin')
#5 /home/craftallure/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#7 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'storeCheck')
#8 /home/craftallure/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'customer-app-ac...')
#11 /home/craftallure/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'tax-app-action-...')
#14 /home/craftallure/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Newslet...', 'dispatch', Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Array, 'weee-app-action...')
#17 /home/craftallure/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /home/craftallure/public_html/var/generation/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(26): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /home/craftallure/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#24 /home/craftallure/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#27 /home/craftallure/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#30 /home/craftallure/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/craftallure/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#33 /home/craftallure/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /home/craftallure/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /home/craftallure/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /home/craftallure/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /home/craftallure/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /home/craftallure/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))`

Any update will be highly helpful.
