### ISSUE TITLE
How to collaborate with the translation Portuguese/Brazil?

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2#1158]
How to collaborate with the translation Portuguese/Brazil?

**Comment by cerebrumbr** [comment]
Several terms are not translated in the package Portuguese/Brazil.

How can we help translating and provide for Magento 2 Github ?

**Comment by vpelipenko** [comment]
Thank you for clarification. We'll look at it and return with answer.

**Comment by maksek** [comment]
Hi @cerebrumbr, algorithm is easy, if you see some wrong translations or missed translations you can update/add the phrase into i18n files. For example - https://github.com/magento/magento2/tree/develop/app/code/Magento/Catalog/i18n here you can see pt_BR.csv, by editing second column or adding new line with data you can update translation. Then create new PR which we will review.

**Comment by piotrekkaminski** [comment]
Hey @cerebrumbr - we are working on using another system to provide translations. Github is not the best place for now. Please look for announcement soon.
