### ISSUE TITLE
Reference to wrong / non-existing class

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#11581]
### Preconditions

1. Magento version 2.2 (or previous)
2. 

### Steps to reproduce

1. In the method `Magento\Sales\Model\Order\Pdf\Invoice::getPdf` comment out the call to `$this->insertOrder(`
2. Go to the backend and print an invoice

### Expected result

1. I should see the invoice without the order details

### Actual result

1. I get a fatal error because the class `Zend_Pdf_Color_RGB` is not found in the `_drawHeader` method.  

### Additional info  
This happens because the actual class name is `Zend_Pdf_Color_Rgb` (lowercase g and b).  
The fact that it works is just an accident. It's because that's how the php autoloader works. The correct class name is referenced in a method called above the `_drawHeader` and the correct file is found. The second time the class is called the class is already loaded and since the class names are not case sensitive .... you get where this is going.  

Same goes for creditmemo and shipping print. I guess copy/paste.

**Comment by magento-engcom-team** [comment]
@tzyganu, thank you for your report.
We've created internal ticket(s) MAGETWO-82432 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82428

**Comment by keyurshah070** [comment]
@okorshenko @tzyganu  I don't understand why it is on TO-DO list If Marius already pushed his branch and its already merged label.

**Comment by okorshenko** [comment]
the issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82953
