### ISSUE TITLE
Cron install / remove via command messes up stderr 2>&1 entries

### ISSUE THREAD

**Issue by adrian-martinez-interactiv4** [magento/magento2#11586]
Installing or removing crontab via command adds 2>&1 repeatedly, even for crontab entries not related with Magento, if they match a regular expression. See details below.

### Preconditions
1. Magento2 develop branch
2. PHP 7.0.15

### Steps to reproduce
1. Set up a crontab entry like this one:
![captura de pantalla 2017-10-20 a las 19 28 45](https://user-images.githubusercontent.com/17545750/31834697-287af846-b5cf-11e7-92e3-bbef0e922366.png)
2. Run bin/magento cron:install
3. Check crontab via crontab -l
4. Run bin/magento cron:remove
5. Check crontab via crontab -l

### Expected result
1. Magento crontab gets installed, then removed and external crontab entry remains as it is

### Actual result
1. After installed, additional 2>&1 gets added:
![captura de pantalla 2017-10-20 a las 19 29 31](https://user-images.githubusercontent.com/17545750/31834812-9bd51d9e-b5cf-11e7-8d8d-eda2acc6ceb4.png)
2. After removed, also  additional 2>&1 gets added:
![captura de pantalla 2017-10-20 a las 19 30 04](https://user-images.githubusercontent.com/17545750/31834884-d1860944-b5cf-11e7-95ba-80d7448d011b.png)

This also applies to other Magento2 installations crontab entries:
![captura de pantalla 2017-10-20 a las 4 16 56](https://user-images.githubusercontent.com/17545750/31835013-4d2425ea-b5d0-11e7-9ebf-1750bdce2a82.png)

**Comment by magento-engcom-team** [comment]
@adrian-martinez-interactiv4, thank you for your report.
We've created internal ticket(s) MAGETWO-82533 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82461

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82463

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82462
