### ISSUE TITLE
Warning: The email and password is visible in front-end

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2#1159]
See image.

![captura de tela de 2015-04-01 17 16 08](https://cloud.githubusercontent.com/assets/2263217/6951745/e3d07e70-d893-11e4-8def-a0cb0fc6258b.png)

**Comment by vpelipenko** [comment]
@cerebrumbr, thank you for posting this issue. But how did you make it visible?

**Comment by alihalabyah** [comment]
@vpelipenko I think it's visible by default!

**Comment by Sanuch** [comment]
it looks like a feature of sample data

**Comment by cerebrumbr** [comment]
Yes, this feature of sample data.

**Comment by Sanuch** [comment]
Ok but do you think that this issue is bug?

**Comment by tkacheva** [comment]
We intentionally created customer account in sample data with some order history and wishlist created.  What you see on login page is the credentials to this demo account.

**Comment by vpelipenko** [comment]
@cerebrumbr, can we consider this issue resolved?

**Comment by cerebrumbr** [comment]
@vpelipenko - Yes.

**Comment by piotrekkaminski** [comment]
Reopening as this is very confusing. Sample data credentials should be documented but not shown on page. Internal ID MAGETWO-40315

**Comment by tkacheva** [comment]
@piotrekkaminski We have already scheduled the update regarding this issue

MAGETWO-38307
