### ISSUE TITLE
URL Rewrites vs multiple storeviews - a never ending battle

### ISSUE THREAD

**Issue by hostep** [magento/magento2#11615]
I'm pretty sure this has been reported before, but please excuse me if I didn't find the correct duplicate, since there are so many issues being reported around this. If there is an exact duplicate, please mark this issue as a duplicate and close it.
My hope is to provide a easy reproducible case which can easily be tested and maybe finally put this big issue a bit more in the spotlight.

### Preconditions

1. PHP 7.0.24
2. Both Magento 2.1.9 and 2.2.0 (the situation in 2.2.0 is slightly better then 2.1.9, but there are still problems)

### Steps to reproduce
1. Setup a Magento 2.1.9 and 2.2.0 installation separately and execute all the steps mentioned below on both of them
2. In the backend, go to Stores > Configuration > Catalog > Catalog > Search Engine Optimization and change the configuration 'Use Categories Path for Product URLs' to 'Yes'
3. In the backend, go to Stores > All Stores and make sure you have 2 storeviews, I'm using 'Dutch' and 'French' as examples here
4. In the backend, go to Catalog > Categories and create 2 subcategories with the following url keys in the default values and 2 storeview specific (don't check the 'Create Permanent Redirect for old URL' checkbox while doing so):

| Tree                     | Name     | Default | Dutch      | French     |
| ------------------------ | -------- | ------- | ---------- | ---------- |
| Default Category/Level 1 | Level 1  | level-1 | level-1-nl | level-1-fr |
| Default Category/Level 1/Level 2 | Level 2  | level-2 | level-2-nl | level-2-fr |

5. At this point, the url rewrites in the database table are correct, so no issues here
6. In the backend, go to Catalog > Products and create a new simple product. I named it 'Product 1'.  Assign it to the category 'Level 2', not on any category above it.
7. Check the `url_rewrite` table in the database, it is different in Magento 2.1.9 and 2.2.0, in 2.2.0 it is slightly better then in 2.1.9, but still not bug free

### Expected result
| request_path                         | target_path                          | store_id |
| ------------------------------------ | ------------------------------------ | -------- |
| level-1-nl.html                      | catalog/category/view/id/3           | 1        |
| level-1-nl/level-2-nl.html           | catalog/category/view/id/4           | 1        |
| level-1-fr.html                      | catalog/category/view/id/3           | 2        |
| level-1-fr/level-2-fr.html           | catalog/category/view/id/4           | 2        |
| product-1.html                       | catalog/product/view/id/1            | 1        |
| level-1-nl/level-2-nl/product-1.html | catalog/product/view/id/1/category/4 | 1        |
| level-1-nl/product-1.html            | catalog/product/view/id/1/category/3 | 1        |
| product-1.html                       | catalog/product/view/id/1            | 2        |
| level-1-fr/level-2-fr/product-1.html | catalog/product/view/id/1/category/4 | 2        |
| level-1-fr/product-1.html            | catalog/product/view/id/1/category/3 | 2        |

#### Magento 2.1.9
| request_path                         | target_path                          | store_id |
| ------------------------------------ | ------------------------------------ | -------- |
| level-1-nl.html                      | catalog/category/view/id/3           | 1        |
| level-1-nl/level-2-nl.html           | catalog/category/view/id/4           | 1        |
| level-1-fr.html                      | catalog/category/view/id/3           | 2        |
| level-1-fr/level-2-fr.html           | catalog/category/view/id/4           | 2        |
| product-1.html                       | catalog/product/view/id/1            | 1        |
| **level-1/level-2/product-1.html**   | catalog/product/view/id/1/category/4 | 1        |
| **level-1/product-1.html**           | catalog/product/view/id/1/category/3 | 1        |
| product-1.html                       | catalog/product/view/id/1            | 2        |
| **level-1/level-2/product-1.html**   | catalog/product/view/id/1/category/4 | 2        |
| **level-1/product-1.html**           | catalog/product/view/id/1/category/3 | 2        |

#### Magento 2.2.0
| request_path                         | target_path                          | store_id |
| ------------------------------------ | ------------------------------------ | -------- |
| level-1-nl.html                      | catalog/category/view/id/3           | 1        |
| level-1-nl/level-2-nl.html           | catalog/category/view/id/4           | 1        |
| level-1-fr.html                      | catalog/category/view/id/3           | 2        |
| level-1-fr/level-2-fr.html           | catalog/category/view/id/4           | 2        |
| product-1.html                       | catalog/product/view/id/1            | 1        |
| level-1-nl/level-2-nl/product-1.html | catalog/product/view/id/1/category/4 | 1        |
| **level-1/product-1.html**           | catalog/product/view/id/1/category/3 | 1        |
| product-1.html                       | catalog/product/view/id/1            | 2        |
| level-1-fr/level-2-fr/product-1.html | catalog/product/view/id/1/category/4 | 2        |
| **level-1/product-1.html**           | catalog/product/view/id/1/category/3 | 2        |

**Comment by orlangur** [comment]
> Assign it to the category 'Level 2', not on any category above it.

"Default Category/Level 1" has ID=3, right? Is problematic product actually available in this category? `Display Settings > Anchor` is set to `No`?

**Comment by hostep** [comment]
Correct. 'Level 1' is ID 3, 'Level 2' is ID 4.
Product is available in both 'Level 1' and 'Level 2' because Anchor is by default set to 'Yes'.

**Comment by orlangur** [comment]
Oh, sorry, I missed the "expected result" part :)

Category URL Key is received from global instead of store view scope, should be
`level-1/product-1.html` -> `level-1-nl/product-1.html`
`level-1/product-1.html` -> `level-1-fr/product-1.html`

**Comment by magento-engcom-team** [comment]
@hostep, thank you for your report.
We've created internal ticket(s) MAGETWO-82506 to track progress on the issue.

**Comment by slavvka** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#26784 by @hostep in 2.4-develop branch
Related commit(s):
 - [cb685d15b2b590bdb4d99a3d4ebe563037d0aa31](https://github.com/magento/magento2/commit/cb685d15b2b590bdb4d99a3d4ebe563037d0aa31)
 - [acb8642c44d1ecb60ad023c81f6541fa9ebae47d](https://github.com/magento/magento2/commit/acb8642c44d1ecb60ad023c81f6541fa9ebae47d)
 - [97258e1a9ce97ad32971731eceac8fee32f66b74](https://github.com/magento/magento2/commit/97258e1a9ce97ad32971731eceac8fee32f66b74)
 - [6cf26dc19e2f80f0c2da445443d0b48a1974fc77](https://github.com/magento/magento2/commit/6cf26dc19e2f80f0c2da445443d0b48a1974fc77)
 - [0b941218dcc86dcbd518f5400934e995ad1f2e3c](https://github.com/magento/magento2/commit/0b941218dcc86dcbd518f5400934e995ad1f2e3c)
 - [b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908](https://github.com/magento/magento2/commit/b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908)
 - [28fa34531f4c7cd4bcad46500ba027b9b58ff297](https://github.com/magento/magento2/commit/28fa34531f4c7cd4bcad46500ba027b9b58ff297)
 - [bf514b0b435a75f5688f56f8e9465af9bb3284c1](https://github.com/magento/magento2/commit/bf514b0b435a75f5688f56f8e9465af9bb3284c1)

The fix will be available with the upcoming 2.4.0 release.
