### ISSUE TITLE
New Products are not displaying when added in the frontend

### ISSUE THREAD

**Issue by rishabhchd19** [magento/magento2#11624]
### Preconditions

1. Magento 2.2.0 upgraded from 2.1.9, php 7

### Steps to reproduce

1. Add new products as Simple Product with weight Item has weight (blank). 320 items in 2.1.9, 390 items in 2.2.0.
2. Quantity: 9999, Price: Random, Content: Random, Website: Default
3. Category Added: By default for all the items, By Alphabets A-Z for all items, By Field mostly for all, By Package for few

### Expected result

1. The frontend must show all the new added product. In Magento 2.1.9, I added 320 products as Simple Products with weight blank and quantity 9999. When upgraded to 2.2.0, the items By default for all the items, By Alphabets A-Z for all items, By Field for all 320 items and 1 items were added in By package. Later when added 71 items to By Package, it doesn't reflect in the frontend. Frontend must show all 390 items but showing previous entries only i.e. 320 items and 1 item in By package, not new 70 items that added recently. 

### Actual result

1. [Screenshot, logs] The category showing all the added products but showing previous items at position 1 in 2.1.9 and recently added items in 2.2.0 at position 0. Items in position 1 are currently displaying, not items with position 0. 
![2017-10-22_1-18-33](https://user-images.githubusercontent.com/30948461/31855455-4d8fa4c4-b6c9-11e7-978d-59702ff31a11.jpg)
![2017-10-22_1-18-07](https://user-images.githubusercontent.com/30948461/31855456-4dc80c42-b6c9-11e7-98ff-3821f89adde4.jpg)
![2017-10-22_1-16-28](https://user-images.githubusercontent.com/30948461/31855457-4df977e6-b6c9-11e7-9e2b-bd716e132ad3.jpg)
![2017-10-22_1-15-24](https://user-images.githubusercontent.com/30948461/31855458-4e2d6e52-b6c9-11e7-8093-b9541c13aa74.jpg)
![2017-10-22_1-14-31](https://user-images.githubusercontent.com/30948461/31855459-4e632f10-b6c9-11e7-95a3-5319363fe2dc.jpg)

**Comment by rishabhchd19** [comment]
any update upon this?

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by rishabhchd19** [comment]
Issue is resolved now. Cron jobs were not running properly due to server upgrade and the catalog thus not updated.  Closing this issue now.

**Comment by benvansteenbergen** [comment]
If you wonder why products are not showing up, we've created a module displaying all conditions for a product to show up: https://github.com/Itonomy/magento2-product-visibillitygrid. Good luck!
