### ISSUE TITLE
Problem with the attribute color

### ISSUE THREAD

**Issue by iTea2** [magento/magento2#11627]
### Preconditions

1. Apache 2.4, MPM_Event, PHP7.1, MariaDB 10.2, OPCache
2. Virgin install Magento ver. 2.2.0

### Steps to reproduce

1. Click Men - Bottoms - Pants -> 12 items
2. Click Style - Leggings -> 4 items, 2 in green
3. Click Color - Green

### Expected result

1. 2 items found

### Actual result

1. 0 items found

There seems to be a problem with the attribute color.

**Comment by magento-engcom-team** [comment]
@iTea2, thank you for your report.
We've created internal ticket(s) MAGETWO-82498 to track progress on the issue.

**Comment by vrann** [comment]
#mm17es

**Comment by jmorenoons** [comment]
I am working on it at #mm17es

**Comment by wagento-bhavin** [comment]
I am working on this at #dmcdindia19

**Comment by wagento-bhavin** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wagento-bhavin. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wagento-bhavin, here is your [Magento instance](https://i-11627-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-11627-2-3-develop.instances.magento-community.engineering/admin](https://i-11627-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. Click Men - Bottoms - Pants -> 12 items
2. Click Style - Leggings -> 4 items, 2 in green
3. Click Color - Green

**Result**
2 items found
![Screenshot_31](https://user-images.githubusercontent.com/51681435/71407197-167a4e80-2643-11ea-9673-108937383212.png)
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
