### ISSUE TITLE
Problem with observer class not found

### ISSUE THREAD

**Issue by ad1rie1** [magento/magento2#11629]
### Preconditions

1. Magento 2.1.9
2. Php 7.0

### Steps to reproduce

Like your documentation i have created a module for redirect user. 
http://devdocs.magento.com/guides/v2.0/extension-dev-guide/events-and-observers.html

The directory is : 
**/app/code/Athena/RedirectToLanguage/etc/frontend/events.xml :** 
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name='controller_action_predispatch'>
                <observer
                        name='Athena_language_redirector'
                        instance='Athena\RedirectToLanguage\Observer\AthenaObserverRedirect'
                />
    </event>
</config>
```

**/app/code/Athena/RedirectToLanguage/Observer/AthenaObserverRedirect :**
```
<?php
namespace Athena\RedirectToLanguage\Observer;
use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;

class AthenaObserverRedirect implements ObserverInterface {
    protected $_responseFactory;
    protected $_url;

    public function __construct(

        \Magento\Framework\App\ResponseFactory $responseFactory,
        \Magento\Framework\UrlInterface $url
    ) {
        $this->_responseFactory = $responseFactory;
        $this->_url = $url;
    }

    public function execute(Observer $observer) {
            $category = $observer->getEvent()->getCategory();
            $lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
            $FRStoreUrl = "https://www.athena-computing.fr/fr";
            $EnRedirectUrl = "https://www.athena-computing.fr/en";
            switch ($lang){
                case "fr":
                 $this->_responseFactory->create()->setRedirect($FRStoreUrl)->sendResponse();
                    break;
                case "en":
                  $this->_responseFactory->create()->setRedirect($EnRedirectUrl)->sendResponse();
                    break;
                default:
                    $this->_responseFactory->create()->setRedirect($EnRedirectUrl)->sendResponse()
                    break;
    }
            $this->_responseFactory->create()->setRedirect($RedirectUrl)->sendResponse();
exit();

    }
}
```

**/app/code/Athena/RedirectToLanguage/registration.php:**
```
<?php
 
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'Athena_RedirectToLanguage',
    __DIR__
);
```

**/app/code/Athena/RedirectToLanguage/etc/module.xml:**

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Athena_RedirectToLanguage" setup_version="1.0.0">
    </module>
</config>
```

All the console php bin/magento setup:upgrade works fine, i see the new module. 
But when i go to the frontend, it's show an error about the observer class does not exist :(

### Expected result
1.  No error

### Actual result

1 exception(s):
Exception #0 (ReflectionException): Class Athena\RedirectToLanguage\Observer\AthenaObserverRedirect does not exist

Exception #0 (ReflectionException): Class Athena\RedirectToLanguage\Observer\AthenaObserverRedirect does not exist
#0 /var/www/html/athenacomputing/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Athena\\Redirect...')
#1 /var/www/html/athenacomputing/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Athena\\Redirect...')
#2 /var/www/html/athenacomputing/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Athena\\Redirect...')
#3 /var/www/html/athenacomputing/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Athena\\Redirect...')
#4 /var/www/html/athenacomputing/vendor/magento/framework/Event/ObserverFactory.php(33): Magento\Framework\ObjectManager\ObjectManager->get('Athena\\Redirect...')
#5 /var/www/html/athenacomputing/vendor/magento/framework/Event/Invoker/InvokerDefault.php(59): Magento\Framework\Event\ObserverFactory->get('Athena\\Redirect...')
#6 /var/www/html/athenacomputing/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#7 /var/www/html/athenacomputing/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#8 /var/www/html/athenacomputing/vendor/magento/framework/App/Action/Action.php(91): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#9 /var/www/html/athenacomputing/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by mhenkel1** [comment]
A solution would have been nice, same problem here. Please fix @orlangur

**Comment by orlangur** [comment]
@mhenkel1 is there some core bug behind?

**Comment by mhenkel1** [comment]
@orlangur Well, if you do it, like he did, like the devdocs tell you, you get this error. I am writing another module with an event observer and I get the same error.

**Comment by orlangur** [comment]
@mhenkel1 I see, thanks. Reopening, could you please attach your module?

**Comment by mhenkel1** [comment]
@orlangur This would be my module, as you can see its relatively simple... but it still is not working in a production environment.

**registration.php**
```
<?php
/**
 * @author Maurice Henkel maurice@neuesmarketing.de
 * @copyright (c) 2019. neuesMarketing KG
 */

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'NeuesMarketing_ConfigurableRedirect',
    __DIR__
);
```

**etc/module.xml**
```
<?xml version="1.0"?>
 
<!--
  ~ @author Maurice Henkel maurice@neuesmarketing.de
  ~ @copyright (c) 2019. neuesMarketing KG
  -->

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="NeuesMarketing_ConfigurableRedirect" setup_version="1.0.3">
        <sequence>
            <module name="Magento_ConfigurableProduct" />
        </sequence>
    </module>
</config>
```

**etc/frontend/events.xml**
```
<?xml version="1.0"?>
<!--
  ~ @author Maurice Henkel maurice@neuesmarketing.de
  ~ @copyright (c) 2019. neuesMarketing KG
  -->

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="controller_action_predispatch_catalog_product_view">
        <observer name="neuesmarketing_configurableredirect_products_observer_redirect" instance="NeuesMarketing\ConfigurableRedirect\Observer\Redirect"/>
    </event>
</config>
```

**Observer/Redirect.php**
```
<?php
/**
 * @author Maurice Henkel maurice@neuesmarketing.de
 * @copyright (c) 2019. neuesMarketing KG
 */

namespace NeuesMarketing\ConfigurableRedirect\Observer;

use Magento\Catalog\Model\ProductRepository;
use Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable;
use Magento\Framework\App\Response\Http;
use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Magento\Store\Model\StoreManagerInterface;

class Redirect implements ObserverInterface
{
    protected $_redirect;
    protected $_productTypeConfigurable;
    protected $_productRepository;
    protected $_storeManager;

    /**
     * Redirect constructor.
     *
     * @param \Magento\Framework\App\Response\Http                                       $redirect
     * @param \Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable $productTypeConfigurable
     * @param \Magento\Catalog\Model\ProductRepository                                   $productRepository
     * @param \Magento\Store\Model\StoreManagerInterface                                 $storeManager
     */
    public function __construct(
        Http $redirect,
        Configurable $productTypeConfigurable,
        ProductRepository $productRepository,
        StoreManagerInterface $storeManager
    ) {
        $this->_redirect = $redirect;
        $this->_productTypeConfigurable = $productTypeConfigurable;
        $this->_productRepository = $productRepository;
        $this->_storeManager = $storeManager;
    }

    /**
     * @param \Magento\Framework\Event\Observer $observer
     *
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function execute(Observer $observer)
    {
		// removed
    }
}
```

**Comment by mhenkel1** [comment]
@orlangur I found the solution to my problem. I had a typo in my psr-4 definition in my composer.json ...
Problem solved and issue can be closed, thanks for your quick responses tho ;)

**Comment by fdo36** [comment]
> @orlangur I found the solution to my problem. I had a typo in my psr-4 definition in my composer.json ...
> Problem solved and issue can be closed, thanks for your quick responses tho ;)

Can you provide information about how did you solve it?

**Comment by roshanphp** [comment]
a

**Comment by roshanphp** [comment]
asssssssssssssssssssssssssssss
