### ISSUE TITLE
Running script from cron returns this error after first line: SQLSTATE[40001]: Serialization failure: 1213 Deadlock...

### ISSUE THREAD

**Issue by tonymik** [magento/magento2#11638]
Magento ver. 1.9.1.0
PHP ver. 5.3.3

I created a script which I used to run from CRON MANAGER in PLESK.
The script updates existing products and creates new ones if there are any.
All went well until one day when it stopped working and stat returning this error:

`**Start update/import script
Updating product 102866, qty: 5, price: 210.23**
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction' in /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/vhosts/site-name/httpdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/vhosts/site-name/httpdocs/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `catalog...', Array)
#5 /var/www/vhosts/site-name/httpdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `catalog in /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction' in /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/vhosts/site-name/httpdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/vhosts/site-name/httpdocs/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `catalog...', Array)
#5 /var/www/vhosts/site-name/httpdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `catalog in /var/www/vhosts/site-name/httpdocs/lib/Zend/Db/Statement/Pdo.php on line 235`

If I start the process, it runs without any problems whatsoever. But if it is scheduled, it just stops. Is there some stupid thing I might have done that generates this error?
I forgot to mention that the script sometimes runs for an hour and then stops with same errors.
The script usually needs to run for 5-7 hours 'till completion.

**Comment by magento-engcom-team** [comment]
@tonymik, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento 2 issues only.
