### ISSUE TITLE
Problem when change less file in magento.

### ISSUE THREAD

**Issue by zivendesign** [magento/magento2#1163]
Hi Everybody,
I have trouble with magento less file:
When i'm change some thing in here: http://prntscr.com/6klkh5
If I want to see the change from me. I must delete css file from the folder: http://prntscr.com/6klkvn
This is really the bad. When i'm change many in the less file. each time i'm change i need delete css folder. This is causes discomfort to the developer when change something in less folder.
Please help me explain and have solution for develop faster.
Best Regards,
Ziven.

**Comment by villageseo** [comment]
Hi zivendesign! 

Thank you for the question. 

You can try to enable Client Side less compilation in Stores > Configuration > ADVANCED > Developer > Front-end development workflow. 

More can be found here: http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/css-topics/css-preprocess.html (the document is still updating). 

Also we have another front-end development workflow with node.js (grunt.js task runner). The documentation is in progress for now.

**Comment by vpelipenko** [comment]
@zivendesign, do you have any other questions?

**Comment by zivendesign** [comment]
Thanks @villageseo for answers. I'm got it. It's great.
@vpelipenko: Thanks. I have new question. I am looking for a Tool, which allow migrate data from Magento1 -> Magento2. Please let me know have or not for now.

**Comment by quynhvv** [comment]
@Ziven:
Yes, we are developing this tool and we public share this tool at
https://github.com/ubertheme/magento2_data_migration/releases
You can follow how to use this tool at
https://github.com/ubertheme/magento2_data_migration/blob/master/README.md
Thanks.


On Wed, Apr 8, 2015 at 4:31 PM, Ziven <notifications@github.com> wrote:

> Thanks @villageseo <https://github.com/villageseo> for answers. I'm got
> it. It's great.
> @vpelipenko <https://github.com/vpelipenko>: Thanks. I have new question.
> I am looking for a Tool, which allow migrate data from Magento1 ->
> Magento2. Please let me know have or not for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1163#issuecomment-90860577>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by ilol** [comment]
Hi @zivendesign ,
I am responsible for Magento Migration Tool at Magento 2 project. We are working on the data migration tool that allows to migrate data from the latest supported versions of Magento 1.x to Magento 2.0 and will be distributed out-of-the-box with Magento2. You can find more details by going to Magento 2 Dev RC webinar that we hosted recently https://vimeo.com/123755065.  
Also this toolkit will be available on our public github very soon. Please, go ahead and try it. In case of any questions or comments, please feel free to reach out to me.

The tool mentioned by @quynhvv has not been evaluated or approved for use and merchants should perform their own due diligence.

**Comment by zivendesign** [comment]
@ilol,
Thanks for answered. It's awesome.  I'm waiting it.

**Comment by vpelipenko** [comment]
@zivendesign, can we close this issue? or do you have another questions?

**Comment by sidolov** [comment]
Hi @zivendesign. Thank you for your report. 
The issue has been fixed in magento/magento2#16170 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [f53c620ec58f6854446369e935b9eede69eda60f](https://github.com/magento/magento2/commit/f53c620ec58f6854446369e935b9eede69eda60f)

The fix will be available with the upcoming 2.3.0 release.
