### ISSUE TITLE
locale bug

### ISSUE THREAD

**Issue by yzm629** [magento/magento2#1164]
No region found within the locale 'zh'
#0 /var/www/html/magento207402/vendor/magento/zendframework1/library/Zend/Currency.php(106): Zend_Currency->setLocale('zh_Ha')
#1 /var/www/html/magento207402/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(99): Zend_Currency->__construct('USD', 'zh_Ha')
#2 /var/www/html/magento207402/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /var/www/html/magento207402/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#4 /var/www/html/magento207402/lib/internal/Magento/Framework/CurrencyFactory.php(41): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /var/www/html/magento207402/lib/internal/Magento/Framework/Locale/Currency.php(75): Magento\Framework\CurrencyFactory->create(Array)
#6 /var/www/html/magento207402/app/code/Magento/Directory/Model/Currency.php(311): Magento\Framework\Locale\Currency->getCurrency('CNY')
#7 /var/www/html/magento207402/app/code/Magento/Directory/Model/Currency.php(289): Magento\Directory\Model\Currency->formatTxt(NULL, Array)
#8 /var/www/html/magento207402/app/code/Magento/Directory/Model/Currency.php(262): Magento\Directory\Model\Currency->formatPrecision(NULL, 2, Array, true, false)
#9 /var/www/html/magento207402/app/code/Magento/Backend/Block/Dashboard/Bar.php(66): Magento\Directory\Model\Currency->format(NULL)
#10 /var/www/html/magento207402/app/code/Magento/Backend/Block/Dashboard/Bar.php(50): Magento\Backend\Block\Dashboard\Bar->format(NULL)
#11 /var/www/html/magento207402/app/code/Magento/Backend/Block/Dashboard/Totals.php(90): Magento\Backend\Block\Dashboard\Bar->addTotal(Object(Magento\Framework\Phrase), NULL)
#12 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(244): Magento\Backend\Block\Dashboard\Totals->_prepareLayout()
#13 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout.php(690): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#14 /var/www/html/magento207402/var/generation/Magento/Framework/View/Layout/Interceptor.php(447): Magento\Framework\View\Layout->createBlock('Magento\\Backend...', 'dashboard.total...', Array)
#15 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(360): Magento\Framework\View\Layout\Interceptor->createBlock('Magento\\Backend...', 'dashboard.total...', Array)
#16 /var/www/html/magento207402/app/code/Magento/Backend/Block/Dashboard.php(30): Magento\Framework\View\Element\AbstractBlock->addChild('totals', 'Magento\\Backend...')
#17 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(244): Magento\Backend\Block\Dashboard->_prepareLayout()
#18 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(115): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#19 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#20 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout.php(317): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#21 /var/www/html/magento207402/var/generation/Magento/Framework/View/Layout/Interceptor.php(200): Magento\Framework\View\Layout->generateElements()
#22 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#23 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#24 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#25 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout.php(223): Magento\Framework\View\Layout\Builder->build()
#26 /var/www/html/magento207402/lib/internal/Magento/Framework/View/Layout.php(805): Magento\Framework\View\Layout->build()
#27 /var/www/html/magento207402/var/generation/Magento/Framework/View/Layout/Interceptor.php(512): Magento\Framework\View\Layout->getBlock('menu')
#28 /var/www/html/magento207402/app/code/Magento/Backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#29 /var/www/html/magento207402/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(122): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Backend...')
#30 /var/www/html/magento207402/app/code/Magento/Backend/Controller/Adminhtml/Dashboard/Index.php(35): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Backend...')
#31 /var/www/html/magento207402/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(122): Magento\Backend\Controller\Adminhtml\Dashboard\Index->execute()
#32 /var/www/html/magento207402/lib/internal/Magento/Framework/App/Action/Action.php(101): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->execute()
#33 /var/www/html/magento207402/app/code/Magento/Backend/App/AbstractAction.php(221): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#34 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/magento207402/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(56): call_user_func_array(Array, Array)
#36 /var/www/html/magento207402/lib/internal/Magento/Framework/Interception/Chain/Chain.php(65): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->___callParent('dispatch', Array)
#37 /var/www/html/magento207402/lib/internal/Magento/Framework/Interception/Chain/Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'adminAuthentica...')
#38 /var/www/html/magento207402/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(96): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#39 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /var/www/html/magento207402/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#41 /var/www/html/magento207402/lib/internal/Magento/Framework/Interception/Chain/Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'designLoader')
#42 /var/www/html/magento207402/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#43 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#44 /var/www/html/magento207402/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#45 /var/www/html/magento207402/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(95): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'adminMassaction...')
#46 /var/www/html/magento207402/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->Magento\Backend\Controller\Adminhtml\Dashboard\Index\{closure}(Object(Magento\Framework\App\Request\Http))
#47 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#48 /var/www/html/magento207402/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(100): call_user_func_array(Array, Array)
#49 /var/www/html/magento207402/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(137): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#50 /var/www/html/magento207402/lib/internal/Magento/Framework/App/FrontController.php(45): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#51 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#52 /var/www/html/magento207402/var/generation/Magento/Framework/App/FrontController/Interceptor.php(56): call_user_func_array(Array, Array)
#53 /var/www/html/magento207402/lib/internal/Magento/Framework/Interception/Chain/Chain.php(65): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#54 /var/www/html/magento207402/var/generation/Magento/Framework/App/FrontController/Interceptor.php(95): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#55 /var/www/html/magento207402/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(66): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}(Object(Magento\Framework\App\Request\Http))
#56 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#57 /var/www/html/magento207402/var/generation/Magento/Framework/App/FrontController/Interceptor.php(100): call_user_func_array(Array, Array)
#58 /var/www/html/magento207402/var/generation/Magento/Framework/App/FrontController/Interceptor.php(124): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#59 /var/www/html/magento207402/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#60 /var/www/html/magento207402/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\Http->launch()
#61 /var/www/html/magento207402/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#62 {main}

**Comment by joanhe** [comment]
@yzm629 Thanks for reporting the problem. Could you provide reproducible steps, we can investigate the cause?

**Comment by yzm629** [comment]
Select the "Interface Locale" to "Chinese (China) / Chinese (China)", the interface does not become Chinese in many places, has a corresponding translation, change account information of "Interface Locale" to "Chinese (China) / Chinese (China) ", then an error!

**Comment by yzm629** [comment]
Chinese support is not perfect!

**Comment by joanhe** [comment]
@yzm629 I logged in admin. I was able to select the "Interface Locale" to "Chinese (China) / Chinese (China)" without any error. Could you check out  the latest magento2 code and try again?

**Comment by yzm629** [comment]
Error may be my fault! 
But "Account Setting" can not select "Chinese (China) / Chinese (China)".
After saving accounts will change to "Afrikaans (Suid-Afrika) / 南非荷兰文 (南非)"

**Comment by mazhalai** [comment]
@yzm629 please specify versions of magento/apache/php so that we can investigate this error.

**Comment by vpelipenko** [comment]
@yzm629, it seems dev team has fixed this issues. Could you check it on the latest version?

**Comment by grasdaggel** [comment]
Sorry for digging this gem out, but when setting language to en_EN in database, theres another Error. Any ideas why? en_EN just should be fine?

**Comment by hostep** [comment]
@grasdaggel: because `EN` is not a valid ISO 3166-1 alpha-2 code for a country, you'll probably need `en_US` or `en_GB`, or some other country...
See https://www.iso.org/obp/ui/#search & https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by magento-engcom-team** [comment]
Hi @stevieyu. Thank you for your report. 
The issue has been fixed in magento/magento2#16164 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [25b364917705d6507bff2162cdee379a8eaa02bd](https://github.com/magento/magento2/commit/25b364917705d6507bff2162cdee379a8eaa02bd)
 - [6be8f8c0c18b4bee69e87b7c48c0253edcd88d07](https://github.com/magento/magento2/commit/6be8f8c0c18b4bee69e87b7c48c0253edcd88d07)
 - [a8178be70ebd502fb62ee210709b536524eea4ae](https://github.com/magento/magento2/commit/a8178be70ebd502fb62ee210709b536524eea4ae)

The fix will be available with the upcoming 2.3.0 release.
