### ISSUE TITLE
Product Use Default Value not selected when linking to non-default websites

### ISSUE THREAD

**Issue by Tjab** [magento/magento2#11648]
### Preconditions
1.  Magento ver. 2.1.5 (but I believe this to be an issue for every version)
2. Two websites, with two store views each
 - Website A - DEFAULT
   - Store View ASV1 - DEFAULT
   - Store View ASV2
 - Website B
   - Store View BSV1
   - Store View BSV2

### Steps to reproduce
1. Add a product via `POST /V1/products`
2. Add the product to Website A and B (or only B as A is default) via `POST /V1/products/{sku}/websites`
3. Update the product (change description) for all store views via `PUT /all/V1/products/{sku}`

### Expected result
1. The description has changed for the product in all four store views

### Actual result
1. The description has changed for the product in store view ASV2, BSV1 and BSV2

### What I think happens
When I add a product without linking it to a website, the checkbox 'Use Default Value' is selected for the store views ASV1 and ASV2, as these store views are part of the default website. This seems to be normal behaviour, I didn't specify which website to add my product to, so it's added to the default and the store views under that website use the information of the product from 'all store views'.

However, as soon as I add the product to a website (it doesn't matter if that's website A and B, or only B, as it's added to the default website anyhow), the product in store view ASV1 has the 'Use Default Value' deselected. As soon as you update the product, only the other three store views are updated, which is only logical since the checkbox is deselected.

### Crappy solution
I currently resolve this by updating the product twice:

`PUT /all/V1/products/{sku}`, which will update the all views that have 'Use Default Value' selected;
`PUT /V1/products/{sku}`, which will update the default store view, which doesn't have the 'Use Default Value` selected.

Of course this isn't perfect, as there's an extra call.

**Comment by magento-engcom-team** [comment]
@Tjab, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by Tjab** [comment]
@magento-engcom-team, thank you for your very fast reply!

ps: I cannot re-open my ticket as I'm not the one that closed it?

I'm wondering why it's not possible to reproduce this, so I've written down all my steps and included screenshots. Please note that this was tested on 2.1.5. I do however believe it's also the case with some customers of ours, who run newer versions.

#### POST to /V1/products/
```json
{
  "product": {
        "sku": "TEST_ISSUE",
        "name": "Testing my issue",
        "price": 10.00,
        "status": 1,
        "type_id": "simple",
        "attribute_set_id":4,
        "weight": 1
    }
}
```
#### Result in my shop
![image](https://user-images.githubusercontent.com/6023513/31990611-e259fbaa-b975-11e7-840d-d306d0626233.png)

##### Main Website
- Default Store View `Use Default Value` check boxes ticked
- Extra Store View Under Default `Use Default Value` check boxes ticked

#### POST to /V1/products/TEST_ISSUE/websites
```json
{
  "productWebsiteLink": {
        "sku": "TEST_ISSUE",
        "website_id": 2
    }
}
```

#### Result in my shop
![image](https://user-images.githubusercontent.com/6023513/31991717-b9ded300-b978-11e7-8fbd-9c7a22e0d283.png)

##### Main Website
- Default Store View some `Use Default Value` check boxes **NOT** ticked
- Extra Store View Under Default `Use Default Value` check boxes ticked

##### website2
- Storeview W2`Use Default Value` check boxes ticked

#### Problem
Notice the difference between the two screenshots. I've added it to `website_id = 2`, and some `Use Default Value` boxes are unchecked in the default store view.
