### ISSUE TITLE
Can't compile magento 2.2.0 sample data

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#11641]
I'm using magento 2.2.0 with sample data and it work fine. After i installed it, I try to compile code. But after compile code frontend show empty page and backend can't load.

Backend:
http://prntscr.com/h0u26p
Frontend:
http://prntscr.com/h0u2fg

I use Windows 8.1 Pro 64-bit and xampp 3.2.2. 
PHP version: 7.0.6
phpMyAdmin version: 4.5.1.
Please help.

Best regards,

DuongQuyet

**Comment by orlangur** [comment]
Can you reproduce an issue using a supported operating system: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html? Note that Windows is not in the list.

Also `localhost` domain may cause troubles with cookies in some browsers, try making some local alias like `magento.dev` or `something.com`.

**Comment by duongquyet** [comment]
Hi @orlangur , 
You mean i can't install magento 2.2 on Windows?

**Comment by orlangur** [comment]
Technically you can as there is no proper check during installation yet, like for incompatible PHP version. You shouldn't do it as it is not supported and in case of any Windows-specific problems you will be on your own.

**Comment by orlangur** [comment]
@duongquyet feel free to confirm at any moment if this issue is reproducible on a supported operating system. Closing for now due to inactivity.
