### ISSUE TITLE
Magento 2.2.0: Report ID: webapi-xxx; Message: Notice: Array to string conversion

### ISSUE THREAD

**Issue by henk-hypershop** [magento/magento2#11654]
### Preconditions

1. Magento 2.2.0
2. PHP 7.0
3. NGINX

### Steps to reproduce

1. Upgrade Magento 2.1.9 to 2.2.0 using composer
2. Login as existing customer with address
3. Add products to cart and checkout

### Expected result

1. Customer can checkout and place order

### Actual result

Customer cannot continue to payment. Log error is shown instead. No stack trace whatsoever.

Network tools log:
Rest API rest/default/V1/carts/mine/estimate-shipping-methods-by-address-id gives a 500.

Error log:
[2017-10-23 19:04:08] main.CRITICAL: Report ID: webapi-59ee3d28a9894; Message: Notice: Array to string conversion in /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2999 {"exception":"[object] (Exception(code: 0): Report ID: webapi-59ee3d28a9894; Message: Notice: Array to string conversion in /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2999 at /vendor/magento/framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Notice: Array to string conversion in /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2999 at /vendor/magento/framework/App/ErrorHandler.php:61)"} []

All was working great before upgrading to 2.2.0.

**Comment by henk-hypershop** [comment]
Found log in report/api. Found enough for fix.

**Comment by magento-engcom-team** [comment]
@henk-hypershop, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0

**Comment by webagil-kevin** [comment]
I have exactly the same problem.

**Comment by iamkerly** [comment]
Same here I have exactly the same problem any fixed of this?

**Comment by Tjitse-E** [comment]
@magento-engcom-team we've got the same issue, here. Also an upgraded Magento 2.1.9 to 2.2.1.

**Comment by fwolfst** [comment]
@magento-engcom-team Here, too. Also, a similar error (without the webapi-part) is logged sometimes when changing the countrie, I think.
@Tjitse-E , @iamkerly , @DogSports ... Do you have extensions installed? Do you have table rate shipping stuff configured?
@magento-engcom-team Is it possible to print more stacktraces in the log, to debug the issue further?

**Comment by rishabhrkrai** [comment]
I also have the same error message for the logged in users. When I more look into the issue, I found the URL **..../rest/default/V1/carts/mine/estimate-shipping-methods-by-address-id**  gives 500 error. But when I go to see the server log, nothing in it.

**Comment by iamkerly** [comment]
@fwolfst Yes were using Table Shipping Rate from Kahanit..

**Comment by ksz2013** [comment]
Hi,

Same issue when updating from 2.1.6 to 2.1.11.
When we try to checkout with existing address, but the address contains a manually enetered State/Province  -> For exampl United Kingdom as country and state specified manually -> the issue can be reproduced.
But when using an address where the region can be selected from predefined options from the dropdown such as for USA the issue cannot be reproduced.

Someone found a workaround for it?

Thanks
