### ISSUE TITLE
Bug with reset password functionality and restricted website

### ISSUE THREAD

**Issue by mjandrsn23** [magento/magento2#11656]
### Preconditions

1. Magento 2.1.7
2. 

### Steps to reproduce

1. Enable a restricted website
2. Send a password reset email or request a forgotten password
3. Click on link in email

### Expected result

1. Should be taken to the Set New password page

### Actual result

1. Redirected to login page

The issue is that Magento\WebsiteRestriction\Model\Restrictor line 141:
} elseif (!in_array($request->getFullActionName(), $allowedActionNames)) {

Compares the current action name to the list of allowed actions.  The list of allowed action are all lowercase, but the default email templates (vendor/magento/module-customer/view/frontend/email/password_new.html and others) generate the url as customer/account/createPassword.

Since the url isn't lowercase, the user is redirected to the login page

**Comment by peterjaap** [comment]
WebsiteRestriction is a Magento Commerce feature. I'm guessing you should submit this through the partner portal. This Github repo is for Magento Open Source only.

**Comment by magento-engcom-team** [comment]
@mjandrsn23 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@mjandrsn23, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
