### ISSUE TITLE
Instantiating block by layout with xsi:object argument

### ISSUE THREAD

**Issue by zbych** [magento/magento2#1166]
Getting following error:
Instance of Magento\Framework\Data\CollectionDataSourceInterface is expected, got Some\Backend\Class\Of\Model\Defined\ByMe instead.

I am not sure if it is intended, if it is, and it is within the rules of core functionality, then please cancel this issue and sorry for bothering. 
I am just not sure if blocks can accept only objects that inherits the Collection interface.

**Comment by vpelipenko** [comment]
@zbych, what should we do to reproduce this issue?

**Comment by orlangur** [comment]
There is no need to inherit from some collection class I believe, but `Some\Backend\Class\Of\Model\Defined\ByMe` must implement `Magento\Framework\Data\CollectionDataSourceInterface`.

**Comment by tzyganu** [comment]
@orlangur What's the purpose of the `CollectionDataSourceInterface` interface? It does not contain any methods at the moment.

**Comment by zbych** [comment]
@vpelipenko I prepared a simple module for you that reproduces this issue:
https://www.dropbox.com/s/gh9cuzp4jmcgmtn/verde_test.tar.gz?dl=0

See explanation in layout.
I hope it will help.

Thanks!

**Comment by vkorotun** [comment]
<virtualType name="layoutObjectArgumentInterpreter" type="Magento\Framework\View\Layout\Argument\Interpreter\Object">
        <arguments>
            <argument name="expectedClass" xsi:type="string">Magento\Framework\Data\CollectionDataSourceInterface</argument>
        </arguments>
    </virtualType>


<argument xsi:type="object" /> - имел хардкод проверку, что только интерфейс коллекции можно было инстанциировать.
на тот момент я принял решение не убирать проверку вообще, но ввести некий маркировочный интерфейс, чтобы разрешить объектам других типов тоже прокидываться через лаяут аргументы
[17:34:42] Vitaly (at Magento): а поскольку и тот и другой тип объектов нужен был гридам и формам, то дал имя интерфейсу по типу некоего дата соурса

**Comment by vkorotun** [comment]
There is an layout argument of object type (xsi:type="object") you can pass to blocks' constructors. It is configured in di.xml, like showed here:
<virtualType name="layoutObjectArgumentInterpreter" type="Magento\Framework\View\Layout\Argument\Interpreter\Object">
    <arguments>
        <argument name="expectedClass" xsi:type="string">Magento\Framework\Data\CollectionDataSourceInterface</argument>
    </arguments>
</virtualType>

Originally this type of argument was developed for Admin Widget Grids to allow passing Collections as an argument to Grid constructor and it had being restricted to "Magento\Framework\Data\Collection". After a while instead of that there was created an empty marking interface, so now you may pass some custom types of collections with more soft restriction - they all should implement this very CollectionDataSourceInterface.

I'd like to consider an ideas if we should remove any restriction for "object" argument type and allow passing any type of objects.

**Comment by zbych** [comment]
@vpelipenko FYI: Update of Verde/Test module. I made there a mistake, but issue still occurs. 
@vkorotun you are right. Sometimes there is a need to configure object from layout, to keep Block reusable. 
After searching for other occurrences of xsi:type="object" in Magento layouts I found only Backend blocks using Collections, so I assumed it as "rule". That's why I was just not sure if it is bug.

Thanks for considering for removing constraint for Collection in that place. 
I think that it should expand power of layout and blocks.

Thanks!

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-56369

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Instantiating-block-by-layout-with-xsi-object-argument/idi-p/46587).
