### ISSUE TITLE
Category not showing all products

### ISSUE THREAD

**Issue by caciobanita** [magento/magento2#11671]
Please reopen this, probleme not solved - https://github.com/magento/magento2/issues/9568
Magento 2.1.7 CE
Can you please help me regarding the same probleme. In my case only one category is afected.
After import i neeed to change tha name for that category and save.
Any solution ?

**Comment by magento-engcom-team** [comment]
@caciobanita, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by sky4git** [comment]
Please reopen the issue. It exists in Magento CE 2.1.0

Upon saving/updating product it does not appear in frontend. Especially, when we create new product, it wont appear on front-end.

I have tried clearing all the cache as well.

Only way to make it appear in category page is wither running indxer:reindex or saving the category directly.
