### ISSUE TITLE
Magento_Log: creating new record with wrong store_id every each refresh page for Adminhtml

### ISSUE THREAD

**Issue by zbych** [magento/magento2#1167]
Module Magento_Log
Area: Adminhtml
Issue: When in Adminhtml, every refresh page or entering any page causes creating a new entry in log_vistior with store_id=1 and last_url_id=0.
When on frontend, everything is allright.
It it is indended, sorry for confusion.

**Comment by mazhalai** [comment]
@zbych Thank you for reporting this issue, we have created ticket MAGETWO-35930 internally to investigate this.

**Comment by mazhalai** [comment]
Hello @zbych, in scope of other work, the Magento_Log module has been removed. There will be other functionality added in scope of story MAGETWO-39109. Hence, closing this ticket. Please feel free to open a new ticket if you still have issues.
