### ISSUE TITLE
Magento 2.2.0 error during cache clean via CLI command

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#11682]
### Preconditions

1. Magento v2.2.0
2. php version v7.0.24
3. mysql version Ver 14.14

### Steps to reproduce

1. Cache clean via CLI command : php bin/magento cache:clean

### Expected result

1.  It would clean all Magento cache with proper response

### Actual result

1. Magento supports 7.0.2, 7.0.4, and 7.0.6 or later. Please read http://devdocs.magento.com/guides/v1.0/install-gde/system-requirements.html
Screenshot has been attached:
![image](https://user-images.githubusercontent.com/17869716/31941017-d80cc6de-b8dd-11e7-9a65-17091f1d30c5.png)

**Comment by orlangur** [comment]
@routbiplab could you please execute `php -v` and show output here?

**Comment by routbiplab** [comment]
Sure. Here is the output for php -v:
![php-version](https://user-images.githubusercontent.com/17869716/32040443-6bbae3ae-ba4e-11e7-865b-dc6251a04a93.png)

The server that we are using is a multi-path PHP.

**Comment by orlangur** [comment]
As you can see, currently PHP5.6 is used in CLI which is not supported by Magento 2.2. You need to setup your server in such a way that PHP7 is used for both web server and CLI.

So observed error is correct system behavior.
