### ISSUE TITLE
Google mobile algorithm

### ISSUE THREAD

**Issue by alihalabyah** [magento/magento2#1168]
As mentioned in this article I think we should focus more on optimizing the page size and the No. of client side sources being loaded CSS, JS, etc. Not only the responsive design itself!

http://searchengineland.com/everything-need-know-googles-new-stance-mobile-216870

**Comment by godban** [comment]
Hello

@alihalabyah sure, agree with you. We are keep moving in this direction and have roadmap which include more mobile friendly improvements, size reducing, more optimized styles & scripts loading etc.

Maybe you want to highlight something special or something high priority for you?

**Comment by choukalos** [comment]
Assigning to @ilol for mobile product perspective and tagging @eleonova for UX/front-end perspective.

**Comment by vpelipenko** [comment]
@alihalabyah, do you have to highlight something in this work?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.
