### ISSUE TITLE
Using the search reloads the product details

### ISSUE THREAD

**Issue by sakiss** [magento/magento2#1169]
## Test instructions
1. Visit a configurable product (e.g. Hero Hoodie from sample data)
2. Try using the search module at the top.

## Result
After any keypress it reloads the product's page by triggering the ajax calls used to load the child products.

**Comment by alihalabyah** [comment]
@sakiss I was not able to reproduce the issue but i think what's going on is that the product image flashes after the page fully loaded, try to check the network traffic using your developer tools

**Comment by sakiss** [comment]
@alihalabyah It is in localohost.
Try to use the search within a product that has variations
![mage2](https://cloud.githubusercontent.com/assets/1838041/7135163/a3c3efd8-e2ac-11e4-931e-f69894dd3002.png)

**Comment by kokoc** [comment]
@sakiss Thank you for reporting the issue. 

We are unable to reproduce this issue. There are few ajax requests for search results, but the main page is not refreshed.

Could you please provide more details (browser, Magento version)?

**Comment by vpelipenko** [comment]
@sakiss, did you a have a chance to check the issue again on the latest versions?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor about 2 weeks.
