### ISSUE TITLE
Resending order email from admin (Multi-store)

### ISSUE THREAD

**Issue by srenon** [magento/magento2#11695]
### Preconditions

1. Magento 2.0-2.2 (CE/EE)

This issue is not that obvious in core Magento but does exist and become a bigger issue when using third party SMTP extension https://github.com/magepal/magento2-gmailsmtpapp (I.e https://github.com/magepal/magento2-gmailsmtpapp/issues/75 https://github.com/magepal/magento2-gmailsmtpapp/issues/49) or any code/plugin that needs to know the correct store or ScopeConfigInterface during code execution.

### Basic steps to reproduce (but this issue is much deeper and does affect other areas)

1. Create a multi-store environment
![image](https://user-images.githubusercontent.com/1415141/31944442-209fa374-b89a-11e7-99a4-c49c272c43f3.png)

2. Set different value in each store for the "port" (i.e 251 & 252)

![image](https://user-images.githubusercontent.com/1415141/31944947-ba93e12e-b89b-11e7-9259-b31a9feaee6a.png)

3. Place an order in each store
![image](https://user-images.githubusercontent.com/1415141/31945059-11a7412c-b89c-11e7-842c-a3d7f0d5018f.png)

4. Set a breakpoint in /app/code/Magento/Email/Model/Plugin/WindowsSmtpConfig.php

![image](https://user-images.githubusercontent.com/1415141/31945254-9b46dcc6-b89c-11e7-81e0-4cac137300b6.png)

5. Click "Send Email" from each store then check the value of ``$this->config->getValue(self::XML_SMTP_PORT)``

![image](https://user-images.githubusercontent.com/1415141/31945108-31ebf608-b89c-11e7-83a3-61f19754896b.png)

### Expected result

1. To get the correct value of the "port" number set in each store

### Actual result

1. The "port number" will be the same regardless of which store it is sent from.

In Magento1.x you use a combination of startEnvironmentEmulation() and setting the storeId to prevent this issue.

https://github.com/OpenMage/magento-mirror/blob/magento-1.7/app/code/core/Mage/Sales/Model/Order.php

    /**
     * Send email with order data
     *
     * @return Mage_Sales_Model_Order
     */
    public function sendNewOrderEmail()
    {
        $storeId = $this->getStore()->getId();
        if (!Mage::helper('sales')->canSendNewOrderEmail($storeId)) {
            return $this;
        }
        // Get the destination email addresses to send copies to
        $copyTo = $this->_getEmails(self::XML_PATH_EMAIL_COPY_TO);
        $copyMethod = Mage::getStoreConfig(self::XML_PATH_EMAIL_COPY_METHOD, $storeId);
        // Start store emulation process
        $appEmulation = Mage::getSingleton('core/app_emulation');
        $initialEnvironmentInfo = $appEmulation->startEnvironmentEmulation($storeId);

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php#L135

**Comment by orlangur** [comment]
Code snippet provided seems to be Windows-specific, do you face with any problems on a supported operating system?

UPD: oh, sorry, breakpoint is outside of condition. Disregard my question.

**Comment by srenon** [comment]
Just to clarify, the bigger issue is that you can not get the store scope (store id, etc), because it will always be the default regardless of what store you are resending the email from.

**Comment by magento-engcom-team** [comment]
@srenon, thank you for your report.
We've created internal ticket(s) MAGETWO-83361 to track progress on the issue.

**Comment by magefan** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@magefan thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
