### ISSUE TITLE
Can't compile magento 2.2.0

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#11698]
I'm using magento 2.2.0 with sample data and it work fine. I try to compile code, But after compile code frontend show empty page and backend can't load.

Backend:
https://prnt.sc/h1g889
Frontend:
https://prnt.sc/h1g8th

PHP version: 7.1.10
Server version: 10.1.28-MariaDB

Steps to reproduce
1. install magento 2.2.0 (sample data or not sample data)
2. disable cache of magento
3. run "php bin/magento setup:di:compile" in folder of your magento
4. try load your magento and you will see.

**Comment by avoelkl** [comment]
Hi @duongquyet,
Please update your issue according to the [issue reporing guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and use the[ issue template](https://github.com/magento/magento2/blob/2.2-develop/ISSUE_TEMPLATE.md) when reporting issues.

Thanks!

**Comment by orlangur** [comment]
@duongquyet blank screens does not contain any useful information for investigation. Enable `display_errors` or check logs to see what actually caused Fatal Error.

**Comment by duongquyet** [comment]
Hi,
@avoelkl I just did exactly what do you provide. What do you want me to do?

**Comment by avoelkl** [comment]
Just as @orlangur mentioned as well: There is no specific error message.
Please turn error reporting on and/or check your logs.

**Comment by magento-engcom-team** [comment]
@duongquyet, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@duongquyet, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
