### ISSUE TITLE
jQuery, Prototype and jQuery-migrate ... What the hell?

### ISSUE THREAD

**Issue by ahmadalfy** [magento/magento2#11701]
OK so I am facing a problem in a JavaScript plugin that am using all because jQuery is dispatching an update event that triggers Prototype. I don't really understand how on earth Magento is now version 2.2 and it still has Prototype. Why? Why not focusing on removing all the legacy code that no one wants to maintain any longer? Prototype is DEAD. Why do I have to carry its burden?

I am angry and this is a rant cause I am forced to develop on this piece of crap platform. I am fed up with the pace this project is moving on, it's becoming a pain to start my work every single day.

**Comment by ahmadalfy** [comment]
Yeah right, add the tag and close the issue

**Comment by orlangur** [comment]
Hi @ahmadalfy, `G1 Failed` label is added by a bot :)

All PrototypeJS-based code was removed from places where it really matters prior to 2.0 GA release. There are still some places in Admin UI using PrototypeJS and I'm not aware if there are any plans to get rid of them or they will disappear naturally during work on corresponding admin features.

Pull requests from Community are always welcomed, you can refactor some PrototypeJS occurrences in Admin UI and such improvements will be merged with a big pleasure.

GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.
