### ISSUE TITLE
Error installing the Magento software using the command line (v0.74.0-beta3)

### ISSUE THREAD

**Issue by JesusTinoco** [magento/magento2#1171]
When I install the Magento software using the command line I received this error:

Module 'Magento_Core':
Installing schema.. 

   The application has thrown an exception!

 Zend_Db_Statement_Exception
 SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'core_session' already exists, query was: CREATE TABLE `core_session` (
  `session_id` varchar(255) NOT NULL COMMENT 'Session Id' ,
  `session_expires` int UNSIGNED NOT NULL default '0' COMMENT 'Date of Session Expiration' ,
  `session_data` mediumblob NOT NULL COMMENT 'Session Data' ,
  PRIMARY KEY (`session_id`)
) COMMENT='Database Sessions Storage' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci

**Comment by buskamuza** [comment]
Hi @JesusTinoco , 
are you updating from an older Magento version? If yes, please, ensure that `var` folder is empty (except `.htaccess` file) before you start installation.

**Comment by JesusTinoco** [comment]
That was, it works now. Thanks @buskamuza .

**Comment by vpelipenko** [comment]
@JesusTinoco, can we close this issue?

**Comment by JesusTinoco** [comment]
Yes @vpelipenko
