### ISSUE TITLE
Unable to extend default.xml for admin theme

### ISSUE THREAD

**Issue by Mohinik11** [magento/magento2#11713]
Hi,

**Preconditions**

Magento 2.1.7
PHP 7.0.21

**Description**

I have created a custom admin theme which is working fine. Now I want to extend the default.xml file as I do not want some blocks on my page and want to remove them.
I created default.xml file at **app/design/adminhtml/My_vendor/My_theme/Magento_Backend/layout/default.xml**
having
`<referenceBlock name="footer" remove="true" />
`

**Expected result**

This should remove footer block.

**Actual result**

Changes have not been reflected.

Please help How can I extend default.xml from magento backend theme.

**Comment by magento-engcom-team** [comment]
@Mohinik11, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
