### ISSUE TITLE
Не отображается новый товар.

### ISSUE THREAD

**Issue by eiskpolimer** [magento/magento2#11714]
Не отображается новый товар. После добавление нового товара, на странице пишет 22 товара,а по факту отображается 21

**Comment by orlangur** [comment]
Please report issue in English providing all the details using https://github.com/magento/magento2/blob/2.2-develop/ISSUE_TEMPLATE.md template.

**Comment by eiskpolimer** [comment]
The new product is not displayed. After adding a new product, 22 products are written on the page, and 21
http://www.eiskpolimer.ru/rybovodstvo.html
![screenshot_4](https://user-images.githubusercontent.com/33082199/31993475-e61ce4cc-b985-11e7-9c8a-14a9155fadaf.jpg)
