### ISSUE TITLE
Mageno 2 not validation grand total with paid money.

### ISSUE THREAD

**Issue by rameshkrr** [magento/magento2#11712]
I am using magento 2 with payubizz payment integration module. I can tamper money using burp suite tool and buy a high priced product at any cost. This is a biggest security issue.

### Preconditions

1. Magento 2.1.7
2. php 7.1

### Steps to reproduce

  ```
 if ($paymentMethod->validateResponse($params)) {
                     if($paidprice != $finalPrice){
                        $this->messageManager->addErrorMessage(__('Payment failed. Please try again or choose a different payment method'));
                        $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/failure');
                     }
                     
                     else{
                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/success');
                $order = $this->getOrder();
                $payment = $order->getPayment();
                $paymentMethod->postProcessing($order, $payment, $params,$paidprice,$finalPrice);
            } 
            }
```
The piece of code for validation in response.php

### Expected result

1.  This should return failure page if paid money not equal to product value.

### Actual result
 1. Returning to success page even after tampering money.

**Comment by orlangur** [comment]
Please provide steps to reproduce on a clean Magento installation or refer to core code which you believe is problematic.

**Comment by rameshkrr** [comment]
I am using payubizz module. The error is with payubizz's response.php file.
[mage.zip](https://github.com/magento/magento2/files/1414383/mage.zip)
this is the module.

**Comment by orlangur** [comment]
Ok, so, original code looked as
```
if ($paymentMethod->validateResponse($params)) {

                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/success');
                $order = $this->getOrder();
                $payment = $order->getPayment();
                $paymentMethod->postProcessing($order, $payment, $params);
            } else {
                $this->messageManager->addErrorMessage(__('Payment failed. Please try again or choose a different payment method'));
                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/failure');
            }
```
and you suggested how it can be changed to avoid this issue in description.

How is that related to Magento core?

**Comment by rameshkrr** [comment]
`<?php

namespace PayUIndia\Payu\Controller\Standard;

class Response extends \PayUIndia\Payu\Controller\PayuAbstract {

    public function execute() {
        $returnUrl = $this->getCheckoutHelper()->getUrl('checkout');
      

        try {
            $paymentMethod = $this->getPaymentMethod();
            $params = $this->getRequest()->getParams();

            if ($paymentMethod->validateResponse($params)) {
                    
                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/success');
                $order = $this->getOrder();
                $payment = $order->getPayment();
                $paymentMethod->postProcessing($order, $payment, $params);
            } else {
                $this->messageManager->addErrorMessage(__('Payment failed. Please try again or choose a different payment method'));
                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/failure');
            }
        } catch (\Magento\Framework\Exception\LocalizedException $e) {
            $this->messageManager->addExceptionMessage($e, $e->getMessage());
        } catch (\Exception $e) {
            $this->messageManager->addExceptionMessage($e, __('We can\'t place the order.'));
        }

        $this->getResponse()->setRedirect($returnUrl);
    }

}
`

This is the full code

**Comment by orlangur** [comment]
Yeah, I copied snippet from archive you provided.

GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Open Source. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

Please provide exact steps. Bugs in third-party extensions are out of scope for this repository.

**Comment by rameshkrr** [comment]
Can you please help me personally. Small piece  of code will help me a lot
for appraisal. Thanks in advance.

**Comment by orlangur** [comment]
Not sure which piece of code you referring to...

**Comment by rameshkrr** [comment]
In response.php I need to validate paid amount with Order Amount.

```
<?php

namespace PayUIndia\Payu\Controller\Standard;

class Response extends \PayUIndia\Payu\Controller\PayuAbstract {

    public function execute() {
        $returnUrl = $this->getCheckoutHelper()->getUrl('checkout');
         $finalPrice = $this->getGrandTotal();
         $paidprice = $this->getBaseGrandTotal();

        try {
            $paymentMethod = $this->getPaymentMethod();
            $params = $this->getRequest()->getParams();
            
       //Fisrt If statement is my own validation but not working     
            if($finalPrice != $paidprice){
                 $this->messageManager->addErrorMessage(__('Payment failed. Please try again or choose a different payment method'));
                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/failure');
            }
//This is default 
            elseif ($paymentMethod->validateResponse($params)) {
                    
                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/success');
                $order = $this->getOrder();
                $payment = $order->getPayment();
                $paymentMethod->postProcessing($order, $payment, $params);
            } 
            
            
            else {
                $this->messageManager->addErrorMessage(__('Payment failed. Please try again or choose a different payment method'));
                $returnUrl = $this->getCheckoutHelper()->getUrl('checkout/onepage/failure');
            }
        } catch (\Magento\Framework\Exception\LocalizedException $e) {
            $this->messageManager->addExceptionMessage($e, $e->getMessage());
        } catch (\Exception $e) {
            $this->messageManager->addExceptionMessage($e, __('We can\'t place the order.'));
        }

        $this->getResponse()->setRedirect($returnUrl);
    }

}
```

I explained the changes in // comments in the codes.I hope you'll help

**Comment by orlangur** [comment]
I see...

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

Please add a link to question here after you post it. I don't have time to help you right now but will try to help you this weekend if the problem will not be solved within those 2-3 days.
