### ISSUE TITLE
After compile magento 2.2.0, Magento is corrupted

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#11711]
Preconditions

Magento 2.2.0
PHP version: 7.1.10
Magento Luma theme.

Steps to reproduce

Install magento 2.2.0 (sample data or not sample data)
Disable cache of magento
Run "php bin/magento setup:di:compile" in folder of your magento
Try load magento site

Expected result

Magento work fine after compile

Actual result

Backend can't load and frontend show empty

I don't install any themes or modules, just use default magento.

**Comment by magento-engcom-team** [comment]
@duongquyet, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@duongquyet, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by duongquyet** [comment]
Hi,
Did you turn off cache?
