### ISSUE TITLE
Magento 2 core files storage

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#11718]
Where are vendor/magento modules located in GitHub? How can I compare version changes?

**Comment by orlangur** [comment]
Modules are in `app/code/Magento`, framework is in `lib/internal/Magento`

Something like https://github.com/magento/magento2/compare/2.1.7...2.1.8

To see particular file changes https://github.com/magento/magento2/blob/2.1/app/code/Magento/Catalog/Model/Product.php you may check history picking a concrete tag - 2.1, 2.2.

I believe differences between Composer-based installation and the one from repo are described in documentation.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
