### ISSUE TITLE
Changing cache application to varnish hangs on save

### ISSUE THREAD

**Issue by bnugent** [magento/magento2#1172]
Version 0.74.0-beta3
Caching disabled

To reproduce:
Stores > Configuration > Advanced > System:
1. Under Full Page Cache, change Caching Application to Varnish Caching
2. Leave defaults for varnish
3. Click Save Config
4. Javascript wait spinner pops up and never completes whatever it's trying to do.

Expected behavior:
Config saves and I can export a VCL? Not really sure since this is new and haven't seen it work yet.

**Comment by mazhalai** [comment]
Thank you for reporting, we have created internal ticket MAGETWO-35782 to track this.

**Comment by vpelipenko** [comment]
hi @bnugent, this issue is fixed by internal dev team. Could you find time and verify it on the latest magento version?
