### ISSUE TITLE
Exported Excel with negative number can't be opened by MS Office

### ISSUE THREAD

**Issue by hauso** [magento/magento2#11729]
### Preconditions
XML excel generator class contain error causing file can't be opened by MS Office.
In Open Office is file opened without problem
1.  Magento 2.x version + MS Office XML handler

### Steps to reproduce
1. Generate some XML export with negative value (eg. quantity)
2. Try to open it with Office XML handler

### Expected result
1. Open export file

### Actual result
1. File do not open correctly and Office's error log is created containing information about incorrect value eg.:

XML ERROR in Table
REASON:	Bad Value
FILE:	C:\Tomas\products_20171025134557.xml
GROUP:	Cell
TAG:	Data
VALUE:	 -1

I tested Microsoft Office Professional Plus 2013 and OpenOffice Calc 4.1.3 only.
Open Office can open file without problem, MS Office do not open file and create error report.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82851

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82959

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82960
