### ISSUE TITLE
Data migration - "super product attributes configuration" price values for options VS actual product price

### ISSUE THREAD

**Issue by gritdigital-mibu** [magento/magento2#11733]
Hi there,

After migrating products from Magento CE 1.8.0.0 to CE 2.1.8 I've noticed a difference in the pricing.

![2017-10-25 16_06_34-cast iron gutter drop end socket 65mm outlet _ manage products _ catalog _ magen](https://user-images.githubusercontent.com/11611416/32007500-a34dd16c-b9a1-11e7-9f4a-3250072741da.png)

Magento 2 shows the prices as £21.80 and £24.44 but in Magento 1 they show as £21.80 and £28.94. 
I don't know which of the two should be considered the "true" price - can you please advise?

Kind regards,
Mike

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.
