### ISSUE TITLE
backend logs me out

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#11738]
Hello,

my Magento2 (2.2.0) in Version logs me sometimes out, if i filter something in products.
What could be the problem?
Is it an Serverproblem?
What i can check to resolve the problem?

Kind regards
olek

**Comment by magento-engcom-team** [comment]
@Olek89 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
