### ISSUE TITLE
Price in the frontend no change 

### ISSUE THREAD

**Issue by durabite** [magento/magento2#11741]
We have installed a Magento 2.1.7 

The system work fine, but if we want to change a price in the part of catalog the price no change, and if we go directly to the product page the price is good.

I hear the problem could be the cron job in version 1.X.X but in 2.X i dont could fine solution.

My site is baytu.mx you can go there a see yourself, for example if you search in the site "Logitech X50" the price is "499" but is you enter in the product display the correct price "599".

Please someone help me! Regards

**Comment by orlangur** [comment]
https://baytu.mx/bocina-bluetooth-logitech-x50-morado-con-naranja.html is showing same price as in list. You need to check all prices fields for this product and one incorrectly behaving in Admin UI.

If the issue will not become clear, create identical two products on a clean Magento installation with sample data.

**Comment by durabite** [comment]
Tanks @orlangur 

For example if you search in the search bar "Logitech X50" in the result page show the old price and in the product page show the new price

**Comment by magento-engcom-team** [comment]
@durabite, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@durabite, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by durabite** [comment]
I find the issue, my cronjob dont work!, my magento dont make the indexer and for this reason in the frontpage no show the actualization of the correct price, i still found the solution but i think i going for the right way.
