### ISSUE TITLE
Create model in custom module in magento2

### ISSUE THREAD

**Issue by viral177** [magento/magento2#1174]
i want to know how to display data in phtml file from database using custom model in magento2 for frontend,can you please give me proper solution?

**Comment by tzyganu** [comment]
@viral177  You can take a look at this [sample module](https://github.com/tzyganu/Magento2SampleModule/). I'm not sure it works on the latest Magento 2 version, but you can give it a try.

**Comment by vpelipenko** [comment]
@viral177, could you give us more details? Do you create new module or try to change something existing?
