### ISSUE TITLE
wysiwyg gives error 

### ISSUE THREAD

**Issue by IonutPerfectWeb** [magento/magento2#1175]
when clicking the wysiwyg button in add product it gives an alert "cannot read property save of undefined"

**Comment by kokoc** [comment]
Thank you for reporting the issue.

We can't reproduce this issue using provided steps. Could you please verify the issue on latest version and provide additional information (browser, 404's, Magento version)?

**Comment by vpelipenko** [comment]
Closed. Contributor doesn't answer more than 3 weeks.
