### ISSUE TITLE
SMS Extension integration

### ISSUE THREAD

**Issue by istagraphics** [magento/magento2#11756]
We are not able to install SMS extension in 2.0 version e-commerce site

### Preconditions

1. We are not able to install sms extension 
2. We are using Magento 2.0 

### Steps to reproduce

1. We tried to install extension but there is no error also
2. 
3. 

### Expected result

1.  Please install any suitable sms extension in our theme

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@istagraphics , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by orlangur** [comment]
@istagraphics which SMS extension are you referring to? This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.
