### ISSUE TITLE
Adding images to existing products does not show up 

### ISSUE THREAD

**Issue by IonutPerfectWeb** [magento/magento2#1176]
When adding a product, then editing it and adding an extra photo ( i had 1 picture then added one to be 2), the new images shows in product view (by customer) only for a second, then dissapears. if I add 2 photos from first time everything works

**Comment by kokoc** [comment]
Thank you for reporting the issue.

We can't reproduce this issue using provided steps. Could you please verify the issue on latest version and provide additional information (browser, 404's, Magento version)?

**Comment by vpelipenko** [comment]
Closed. We don't get answer from contributor and can't reproduce described issue.
