### ISSUE TITLE
Configurable product price update on mobile nav. 2.x

### ISSUE THREAD

**Issue by wolfuma** [magento/magento2#11763]
On product page of configurable products when select swatches, prices didn't update, stays at 'lowest price' but if i change the mobile view to desktop view, works great (on android chrome). That's the same on all mobile browser. 

### Preconditions
1. MAgento 2.1.8 on Gcloud instance by bitnami. tryed with 2.1.9 and 2.2 fresh install with same resutls
2. Varnish ssl trought appache 
3. Minify, bundled and merged ( i try different conf with identical issue)

### Steps to reproduce
1. Create a configurable product with visual swatches and diferent prices
2. Nav with mobile device (not emulated) to the product page and select options.
3. See the prices not updated

### Expected result

1. Price update acordingly to the options

### Actual result

1. Same price on all  options

PD: I try to disable theme (porto) and with same result

**Comment by wolfuma** [comment]
ITs a really bad issue on production site. Anyone have same issue? For note its on product page. Only with native android nav (chrome, opera, firefox or samsung native). On emulated mobile with chrome, works well. I don't know if acces with IOS nav

**Comment by wolfuma** [comment]
tryed with 2.1.9 and 2.2 with same results

**Comment by wolfuma** [comment]
@orlangur 

Can you check this issue please? I quote you because its issue realativetly same than https://github.com/magento/magento2/issues/11647   

If you acces with mobile navigation like chrome on android (not emulated). Price didn't update. I try with all of possible mix of bundling, minify, etc without succes. 

For exxample check this page https://wolfuma.com/xiaomi-mi6 if you select the two requiered swatches, price didnt update

I really apreciate any help

thanks in advance

**Comment by orlangur** [comment]
@wolfuma worked for me: https://prnt.sc/h4outs https://prnt.sc/h4ouir

**Comment by wolfuma** [comment]
@orlangur thanks for you check it but on desktop browser works great. Only not working on mobile devices like android or IOs browser. Please check with mobile browser and select two swatches

**Comment by magento-engcom-team** [comment]
Hi @wolfuma 
I can't reproduce it on version 2.1.10.
Tested on mobile devices with android Chrome and ios Safari.
https://youtu.be/0d_Igvm7mFY

**Comment by magento-engcom-team** [comment]
@wolfuma, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.10

**Comment by gesell** [comment]
Reopen please.

This issue has caused a wrong price on our store front. The customer bought for a very cheap price in our shop, lawyer included already. 

He used an Android Browser (Samsung Galaxy Note 10.1 GT-N8000). Issue appeared exactly as states above.

Please help for quickfix, our shop needs to be offline now.. the same customer is threatening to buy more.
