### ISSUE TITLE
API call /rest/all/V1/products/{sku} updates for too many websites?

### ISSUE THREAD

**Issue by Tjab** [magento/magento2#11769]
It's the question if the behaviour of the api call with `all` is working as intended, as it can go either way. What I expect, is that when I have a product linked to 5 websites of the 10 websites I have, and I update the product with `rest/all/V1/products/{sku}`, it will be updated for the websites it belongs to.

However, as soon as I do an update, it will be updated for all 10 websites, whether the product already belongs to that website or not.

### Preconditions
1. We're working with Magento 2.1.5
2. Magento 2 environment with multiple websites and store views

### Steps to reproduce
1. POST a product to `/rest/V1/products`
 - The product is added to the default website
2. PUT the product to `/rest/all/V1/products/{sku}`
 - The product is updated in the default website (good)
 - The product is added to all other websites (bad? I think so)

### Expected result
1. When updating a product to all, I'd expect it to only update for the websites it is attached to. However, I can see why this has been designed otherwise.

### Actual result
1. Product is updated on the default website, and added to all websites.

### Question
If this behaviour is intended, should I then get the websites the product is linked to, and do an update call to only those websites? This sounds as a lot of extra calls...

**Comment by orlangur** [comment]
Hi @Tjab, you are right, such issue is already known as https://github.com/magento/magento2/issues/11324.

Thanks for a well-formed bug report!

**Comment by Tjab** [comment]
Sorry for the duplication :'(

**Comment by orlangur** [comment]
Absolutely no problem, it would be not so easy to find :) Just that I remember I read similar bug report some time ago.
