### ISSUE TITLE
Accessing abandoned cart in backend shows error when order contains removed products

### ISSUE THREAD

**Issue by VonKavalier** [magento/magento2#11773]
ref : #8877 

Happens when viewing customers > edit customer > view "Manage Shopping Cart" at the backend

It happens because we changed the database and some datas weren't needed anymore, so some products weren't there in the new version. And of course, some abandoned carts didn't have some of the products back.

### Preconditions
1. Magento 2.1.6
2. PHP 7.1.10
3. MySQL 14.14 Distrib 5.7.20

### Steps to reproduce
I was only able to reproduce it locally using our production database, but you'll understand that I cannot share it with you. All that I can say is that deleting a product from the backend removes it well and cannot cause an error.

### Expected result

We should see the cart as usual, same as the majority of customers in the backend

### Actual result

We get the error:
`
Fatal error: Uncaught Error: Call to a member function canConfigure() on null in /home/dnd-von/Datas/projects/palmag/vendor/magento/module-advanced-checkout/Block/Adminhtml/Manage/Grid/Renderer/Product.php:31 Stack trace: #0 /home/dnd-von/Datas/projects/palmag/vendor/magento/module-backend/Block/Widget/Grid/Column.php(276): Magento\AdvancedCheckout\Block\Adminhtml\Manage\Grid\Renderer\Product->render(Object(Magento\Sales\Model\Order\Item)) #1 /home/dnd-von/Datas/projects/palmag/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/extended.phtml(194): Magento\Backend\Block\Widget\Grid\Column->getRowField(Object(Magento\Sales\Model\Order\Item)) #2 /home/dnd-von/Datas/projects/palmag/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/dnd-von/D...') #3 /home/dnd-von/Datas/projects/palmag/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\AdvancedCheckout\Block\Adminhtml\Manage\Accordion\Ordered), '/home/dnd-von/D...', Ar in /home/dnd-von/Datas/projects/palmag/vendor/magento/module-advanced-checkout/Block/Adminhtml/Manage/Grid/Renderer/Product.php on line 31
`

Here's what we get when clicking the 'Manage Shopping Cart' tab (only locally as a dev, the error message isn't shown in production) : 
![capture du 2017-10-26 15-31-38](https://user-images.githubusercontent.com/21989855/32055704-d365c190-ba62-11e7-9cf4-02cd1e34e138.png)

Do you have a temporary solution to provide ?

Thanks in advance.

**Comment by orlangur** [comment]
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.

**Comment by VonKavalier** [comment]
Hi !

Hum... I have to say that I didn't get your answer. Isn't it the proper place to talk about magento 2 issues, and therefore help the entire community with problems that might affect them?

I'm sorry I really don't understand what I need to do now :/

**Comment by orlangur** [comment]
> /vendor/magento/module-advanced-checkout/Block/Adminhtml/Manage/Grid/Renderer/Product.php:31

> clicking the 'Manage Shopping Cart' tab

This module is not a part of Magento Open Source (formerly Magento Community Edition). You need to visit Support portal or Partner portal.

**Comment by VonKavalier** [comment]
Got it, thanks
