### ISSUE TITLE
Got "Invalid input datetime format of value" after changing admin locale

### ISSUE THREAD

**Issue by saivnct** [magento/magento2#11777]
Hello, I got error after changing admin locale to vi_VN.
Could you show me how to fix this issue.
I'm using Magento-CE-2.1.9-2017-09-13-03-35-18
Thank you

<img width="1440" alt="screen shot 2017-10-26 at 22 12 05" src="https://user-images.githubusercontent.com/17584047/32061763-b9a81606-ba9c-11e7-8f61-4f1e1000ea31.png">

**Comment by orlangur** [comment]
Hi @saivnct, thanks for bug report, it is a known issue tracked as https://github.com/magento/magento2/issues/10580.
