### ISSUE TITLE
Beta 3 blank install

### ISSUE THREAD

**Issue by seabird** [magento/magento2#1177]
Hello all, just installed magento 2 via composer (so not GIT) and now have a completely themeless store. In the backend same problem and when I go to theme settings there is no save button available to change it.

**Comment by mazhalai** [comment]
@seabird thank you for reporting this issue. Can you please post the composer.json used?

**Comment by seabird** [comment]
I will try and reproduce the error (virtual machine so should be easy). The steps I took to fix the error:

php dev/tools/Magento/Tools/View/deploy.php

After everything compiles flush the system cache with this command:

php dev/shell/cache.php –flush

**Comment by seabird** [comment]
{
    "name": "magento/product-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "0.74.0-beta3",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "php": "~5.5.0|~5.6.0",
        "zendframework/zend-stdlib": "2.3.1",
        "zendframework/zend-code": "2.3.1",
        "zendframework/zend-server": "2.3.1",
        "zendframework/zend-soap": "2.3.1",
        "zendframework/zend-uri": "2.3.1",
        "zendframework/zend-validator": "2.3.1",
        "zendframework/zend-console": "2.3.1",
        "zendframework/zend-modulemanager": "2.3.1",
        "zendframework/zend-mvc": "2.3.1",
        "zendframework/zend-text": "2.3.1",
        "zendframework/zend-eventmanager": "2.3.1",
        "zendframework/zend-view": "2.3.1",
        "zendframework/zend-servicemanager": "2.3.1",
        "zendframework/zend-json": "2.3.1",
        "zendframework/zend-config": "2.3.1",
        "zendframework/zend-form": "2.3.1",
        "zendframework/zend-di": "2.3.1",
        "zendframework/zend-serializer": "2.3.1",
        "zendframework/zend-log": "2.3.1",
        "zendframework/zend-http": "2.3.1",
        "magento/zendframework1": "1.12.10",
        "composer/composer": "1.0.0-alpha8",
        "monolog/monolog": "1.11.0",
        "oyejorge/less.php": "1.7.0.3",
        "tubalmartin/cssmin": "2.4.8-p4",
        "magento/magento-composer-installer": "*",
        "magento/magento2-base": "0.74.0-beta3",
        "magento/module-admin-notification": "0.74.0-beta3",
        "magento/module-authorization": "0.74.0-beta3",
        "magento/module-backend": "0.74.0-beta3",
        "magento/module-backup": "0.74.0-beta3",
        "magento/module-bundle": "0.74.0-beta3",
        "magento/module-captcha": "0.74.0-beta3",
        "magento/module-catalog": "0.74.0-beta3",
        "magento/module-catalog-import-export": "0.74.0-beta3",
        "magento/module-catalog-inventory": "0.74.0-beta3",
        "magento/module-catalog-rule": "0.74.0-beta3",
        "magento/module-catalog-search": "0.74.0-beta3",
        "magento/module-catalog-url-rewrite": "0.74.0-beta3",
        "magento/module-catalog-widget": "0.74.0-beta3",
        "magento/module-centinel": "0.74.0-beta3",
        "magento/module-checkout": "0.74.0-beta3",
        "magento/module-checkout-agreements": "0.74.0-beta3",
        "magento/module-cms": "0.74.0-beta3",
        "magento/module-cms-url-rewrite": "0.74.0-beta3",
        "magento/module-config": "0.74.0-beta3",
        "magento/module-configurable-import-export": "0.74.0-beta3",
        "magento/module-configurable-product": "0.74.0-beta3",
        "magento/module-contact": "0.74.0-beta3",
        "magento/module-cookie": "0.74.0-beta3",
        "magento/module-cron": "0.74.0-beta3",
        "magento/module-currency-symbol": "0.74.0-beta3",
        "magento/module-customer": "0.74.0-beta3",
        "magento/module-customer-import-export": "0.74.0-beta3",
        "magento/module-design-editor": "0.74.0-beta3",
        "magento/module-developer": "0.74.0-beta3",
        "magento/module-dhl": "0.74.0-beta3",
        "magento/module-directory": "0.74.0-beta3",
        "magento/module-downloadable": "0.74.0-beta3",
        "magento/module-eav": "0.74.0-beta3",
        "magento/module-email": "0.74.0-beta3",
        "magento/module-fedex": "0.74.0-beta3",
        "magento/module-gift-message": "0.74.0-beta3",
        "magento/module-google-adwords": "0.74.0-beta3",
        "magento/module-google-analytics": "0.74.0-beta3",
        "magento/module-google-optimizer": "0.74.0-beta3",
        "magento/module-google-shopping": "0.74.0-beta3",
        "magento/module-grouped-import-export": "0.74.0-beta3",
        "magento/module-grouped-product": "0.74.0-beta3",
        "magento/module-import-export": "0.74.0-beta3",
        "magento/module-indexer": "0.74.0-beta3",
        "magento/module-integration": "0.74.0-beta3",
        "magento/module-layered-navigation": "0.74.0-beta3",
        "magento/module-log": "0.74.0-beta3",
        "magento/module-media-storage": "0.74.0-beta3",
        "magento/module-msrp": "0.74.0-beta3",
        "magento/module-multishipping": "0.74.0-beta3",
        "magento/module-newsletter": "0.74.0-beta3",
        "magento/module-offline-payments": "0.74.0-beta3",
        "magento/module-offline-shipping": "0.74.0-beta3",
        "magento/module-page-cache": "0.74.0-beta3",
        "magento/module-payment": "0.74.0-beta3",
        "magento/module-persistent": "0.74.0-beta3",
        "magento/module-product-alert": "0.74.0-beta3",
        "magento/module-quote": "0.74.0-beta3",
        "magento/module-reports": "0.74.0-beta3",
        "magento/module-require-js": "0.74.0-beta3",
        "magento/module-review": "0.74.0-beta3",
        "magento/module-rss": "0.74.0-beta3",
        "magento/module-rule": "0.74.0-beta3",
        "magento/module-sales": "0.74.0-beta3",
        "magento/module-sales-rule": "0.74.0-beta3",
        "magento/module-search": "0.74.0-beta3",
        "magento/module-sendfriend": "0.74.0-beta3",
        "magento/module-shipping": "0.74.0-beta3",
        "magento/module-sitemap": "0.74.0-beta3",
        "magento/module-store": "0.74.0-beta3",
        "magento/module-tax": "0.74.0-beta3",
        "magento/module-tax-import-export": "0.74.0-beta3",
        "magento/module-theme": "0.74.0-beta3",
        "magento/module-translation": "0.74.0-beta3",
        "magento/module-ui": "0.74.0-beta3",
        "magento/module-ups": "0.74.0-beta3",
        "magento/module-url-rewrite": "0.74.0-beta3",
        "magento/module-user": "0.74.0-beta3",
        "magento/module-usps": "0.74.0-beta3",
        "magento/module-variable": "0.74.0-beta3",
        "magento/module-version": "0.74.0-beta3",
        "magento/module-webapi": "0.74.0-beta3",
        "magento/module-weee": "0.74.0-beta3",
        "magento/module-widget": "0.74.0-beta3",
        "magento/module-wishlist": "0.74.0-beta3",
        "magento/theme-adminhtml-backend": "0.74.0-beta3",
        "magento/theme-frontend-blank": "0.74.0-beta3",
        "magento/theme-frontend-luma": "0.74.0-beta3",
        "magento/language-de_de": "0.74.0-beta3",
        "magento/language-en_us": "0.74.0-beta3",
        "magento/language-es_es": "0.74.0-beta3",
        "magento/language-fr_fr": "0.74.0-beta3",
        "magento/language-nl_nl": "0.74.0-beta3",
        "magento/language-pt_br": "0.74.0-beta3",
        "magento/language-zh_cn": "0.74.0-beta3",
        "magento/framework": "0.74.0-beta3"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.0.6",
        "lib-libxml": "*",
        "ext-ctype": "*",
        "ext-gd": "*",
        "ext-spl": "*",
        "ext-dom": "*",
        "ext-simplexml": "*",
        "ext-mcrypt": "*",
        "ext-hash": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\ToolkitFramework\\": "dev/tools/performance-toolkit/framework/Magento/ToolkitFramework/"
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.magento.com/"
        }
    ]
}

**Comment by mazhalai** [comment]
@seabird this composer.json is magento's root composer which assumes that you have already cloned the code base using git.  If you want to install the `project` using composer.json, please follow the thread [here](https://github.com/magento/magento2/issues/844#issuecomment-90890500). Also, please note after the process of downloading magento and its dependencies is complete, please run the CLI as described in  [Command line installation](http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli.html)

**Comment by vpelipenko** [comment]
@seabird, do you still face with this issue on the latest versions?

**Comment by seabird** [comment]
Havent tried it yet. Will let you know when I try. Had some other priorities on our shop.

**Comment by vpelipenko** [comment]
Thank you, waiting for update.

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.
