### ISSUE TITLE
Import configurable CSV products does not activate them

### ISSUE THREAD

**Issue by mnuhell** [magento/magento2#11776]
### Preconditions

1. Magento 2.1.7 
2. PHP VERSION 7.1

### Steps to reproduce

1. Donwload CSV configurable product created manually  
2. Create 2 configurable with him product simple
3. Import succesfully 

### Expected result

1. Created two products configured with their simple products

### Actual result

1. Not enabled Configurable Product
![captura de pantalla 2017-10-26 16 58 56](https://user-images.githubusercontent.com/558183/32060552-569dc286-ba6f-11e7-91b9-da028f89db77.png)

**Comment by magento-engcom-team** [comment]
Hello @mnuhell. Thank you, for your report. Do you mean that, when you create a configurable product without simple products (without configurations) and then you export it to a CSV file. You go back to the website, create configurations for that previously created product (you add a couple of simple products as configurations) and then you import previously created CSV file and then you expect it not remove the configurations (simple products) that we already created for that product. Is that what you mean? If not, we would appreciate more details, in order to help you. Thank you in advance!

**Comment by mnuhell** [comment]
More or less, I have a CSV with configurable products and their simple related products, when I import to Magento2, I import all simple products perfectly, with their images, product name and so on, but the configurable products are not activated, they are shown disabled , without img and without product name.

Attached CSV file, the file is imported perfectly. but the configurables do not activate them, so there is no relationship with the simple ones.

[import_bom.zip](https://github.com/magento/magento2/files/1419061/import_bom.zip)

Thanks.

**Comment by magento-engcom-team** [comment]
@mnuhell Unfortunately, I can't reproduce the issue with this file, I'm having an error while trying to upload it. Please provide a better one. Kind Regards.

**Comment by mnuhell** [comment]
@magento-engcom-team in the version 2.1.7 with this configuration work perfectly.

![captura de pantalla 2017-10-30 09 01 34](https://user-images.githubusercontent.com/558183/32160539-79b853cc-bd52-11e7-98c3-764f1b133c41.png)

Thanks.

**Comment by magento-engcom-team** [comment]
@mnuhell Just tried with a clean instance of 2.1.7, same can't reproduce. The file seems to be broken!  
![image](https://user-images.githubusercontent.com/31669971/32161580-c34de5b8-bd5e-11e7-82e3-87e3a7d49d33.png) Please provide a better file. Do you have any extra settings on your Magento?

**Comment by mnuhell** [comment]
Ok, that's because you have to change the `Field separator` with a `;`

**Comment by magento-engcom-team** [comment]
@mnuhell Oh, okay I see! But still, doesn't allow me to upload the file! 
![image](https://user-images.githubusercontent.com/31669971/32161878-cc987470-bd5f-11e7-9a9a-22a7c7af5b81.png)

**Comment by mnuhell** [comment]
these rows are configurable products, I do not know what may be happening now. :( I do not have any problems uploading file in my Magento install.

**Comment by mnuhell** [comment]
I get 2 days uploading the file without problems, and everything works, except the configurables that are not activated.

**Comment by magento-engcom-team** [comment]
@mnuhell Okay, and do you have any additional settings on your Magento? Like third parties extensions or specific settings in your admin panel?

**Comment by mnuhell** [comment]
Sorry, I have Attribute, color_watch for those products. that may be the error of rows 5, 10 and 19
![captura de pantalla 2017-10-30 10 03 04](https://user-images.githubusercontent.com/558183/32162529-a0a9943a-bd59-11e7-835b-80ab4af7cacc.png)

**Comment by magento-engcom-team** [comment]
@mnuhell Is that a visual swatch?

**Comment by mnuhell** [comment]
@magento-engcom-team Yes is visual watch

**Comment by magento-engcom-team** [comment]
I tried to create a color_watch attribute, still have an error. As much as I want to help, I probably won't be able to help you with this issue. I think the source of this problem is mixed websites (multi-stores) and mixed languages and other settings that you have in your Magento. 
![image](https://user-images.githubusercontent.com/31669971/32164101-1e4364c2-bd67-11e7-86d9-a2f3e091c0ec.png)

**Comment by mnuhell** [comment]
If you have in admin watch Blue and a the CSV have Azul is a problem?

I have English and Spanish store.
![captura de pantalla 2017-10-30 11 07 19](https://user-images.githubusercontent.com/558183/32165315-a452c242-bd62-11e7-9f49-f5bcc0a76f22.png)

**Comment by magento-engcom-team** [comment]
@mnuhell I tried the same settings still can't upload the file! I am sorry
[image](https://user-images.githubusercontent.com/31669971/32168236-6b515f50-bd74-11e7-98ab-a8283b9b9f99.png)
The error looks like this:  

> Value for 'color_watch' attribute contains incorrect value, see acceptable values on settings specified for Admin in row(s): 1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18

**Comment by magento-engcom-team** [comment]
@mnuhell, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
