### ISSUE TITLE
Magento 2.2.0 not working with php 5.6.30

### ISSUE THREAD

**Issue by luizpinheiro** [magento/magento2#11775]
### Preconditions

1. Server running on Ubuntu 14.04.5 LTS
2. Apache 2.4.x and 5.6.30-1+deb.sury.org~trusty+1

Magento tells:

> Magento supports PHP 7.0.2, 7.0.4, and 7.0.6 or later. Please read Magento System Requirements.

But in the docs they said that Magento supports php 5.6.x.

**Comment by orlangur** [comment]
I don't see PHP5.6 supported on http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html.

Please report issues in documentation to https://github.com/magento/devdocs/ repository.
