### ISSUE TITLE
Backend requests don't receive data

### ISSUE THREAD

**Issue by indefinitedevil** [magento/magento2#11778]
We've had a recurring issue with Magento 2.2.0 where (for some reason I don't understand) the "Attention: Something went wrong." message appears on every page.

We get the default message about a "technical error on the server" but there is nothing in any error log to indicate what might be going wrong, and nothing loads and no form entries work. Trying to submit a form 302s you back to the parent page.

However, I have discovered what is causing the above and I am rather perplexed by it.

The issue is that when an AJAX call is made, the parameters in POST/GET/REQUEST are not making it to the Magento system, and I don't understand why. There are no relevant log entries - it just seems that any backend request fails.

To be clear, when the admin makes a call to /admin/mui/index/render/ to get notifications, it sends several parameters (namespace, sorting[field], sorting[direction] and isAjax). When the action is executed in the PHP, the $_REQUEST array is empty.

It is not limited to just that one call - any backend request seems to be affected, and it is causing quite a few issues with even doing basic things like saving configuration changes.

It seems that forcing a condition Magento doesn't expect (fatal exception, or die()) puts it back to normal for a while, but it keeps recurring so there is a persistent issue, and fixing it for one AJAX call doesn't seem to fix it for others.

What I'm wondering is if someone has any clue what the issue might be (willing to accept it could be a misconfigured server) or whether I should be raising this as an issue in the repo. I've not found any sign anyone else is having the same issue which seems to suggest that it could be a localised issue but I have no idea what it could be.

I can't figure out if it is an issue with Magento, with the server, with something else entirely... it isn't consistent, but affects everyone who logs into the backend at some point or other.

### Preconditions

1. Magento Open Source 2.2.0
2. PHP 7.0.24
3. MariaDB 10.1.28
4. Apache 2.4.28
5. CentOS 7.4.1708

### Steps to reproduce

This is an inconsistent issue, so does not always occur, however when it does, the reproduction steps are very simple.
1. Login to Magento backend

### Expected result

1. Notifications displayed
2. Forms saved

### Actual result

1. Notifications will not load, instead get a "Attention: Something went wrong." message
2. Attempting to save any form takes you back to the parent page without having saved the data

There are no logs. Only viable screenshot is of the "Attention: Something went wrong." which is the default error message.

**Comment by orlangur** [comment]
I doubt this issue can be investigated without some debug on your side.

Please set developer mode, enable `display_errors` and maximum `error_reporting` then check suspicious requests in Network tab of browser Dev Tools.

**Comment by indefinitedevil** [comment]
Yeah... I've done that already. I've been investigating this for two weeks. I've been monitoring exactly what happens and debugging every way I can think of, which is how I know the issue is that request data isn't being received which results in a 302 back to the parent page (in most cases).

If I had debug information, I would have provided it rather than saying it doesn't leave logs or produce errors that are recorded.

We have hit upon the idea that it might be relating to the .htaccess authentication we're using to prevent outside services from accessing the site before it goes live. We're currently testing this theory, but if it is that, it's an odd thing to occur as we've never had an issue with htaccess authentication before.

**Comment by orlangur** [comment]
I see... Still you can see pretty clear what is sent to Web Server and what is actually received on PHP side.

If everything seems ok in Network tab of browser Dev Tools, you may try a lower level pocket sniffer like Wireshark (sometimes in the past I had to do it due to bugs in Firebug).

If all data is sent from browser side but not received by Magento server side, there is nothing Magento can do about it unfortunately :( You need to check every single piece of network infrastructure, like Apache, Varnish etc (why not switch to Nginx, for example?).

**Comment by indefinitedevil** [comment]
I've been using Fiddler. All POST data is verified in Fiddler, but none of it is received in the code.

Our server provider can't find any issue either, as that was already considered, and they suggested checking the code. We're in a bit of a loop here.

**Comment by orlangur** [comment]
Some quick googling:
https://stackoverflow.com/questions/6923643/php-settings-php-not-receiving-post-data
https://stackoverflow.com/questions/31766864/post-data-not-received-on-server-side
https://stackoverflow.com/questions/37129158/why-does-php-not-receive-post-data-sent-via-ajax
https://forums.phpfreaks.com/topic/176026-not-receiving-data-from-form-post/

Please just check if you tried all of these already.

1) When it starts to happen, it happens all the time or only for some requests?
2) Form data sent is always not big? (you see it in Fiddler or browser)
3) Is it vanilla Magento installation, slightly customized or customized a lot?
4) Did you upgrade from `2.1.x` or it is new?

Also, when it starts to happen, it may be worth to try playing with raw requests in Fiddler, figuring out consistent pattern and paying attention to things like HTTP headers.

**Comment by magento-engcom-team** [comment]
Hello @indefinitedevil. Such behavior used to happen sometimes when the admin user had the role with restricted access to resources. Could You, please tell us if Your admin user also has a restricted access. Thank You.

**Comment by indefinitedevil** [comment]
No restricted access.

What it seems like is that the htaccess authentication to stop the site being accessed early was the issue. When an IP whitelist was applied, the problem appears to have stopped and stayed stopped.

Which is curious as it didn't affect things all the time, which is what I would expect from an htaccess issue.
