### ISSUE TITLE
LayeredNavigation theme problems

### ISSUE THREAD

**Issue by ci2014** [magento/magento2#11782]
### Preconditions

1. Magento 2.2.0, but problem exists earlier as well 

### Steps to reproduce

1. Install Magento 2.x.x
2. Visit a category with child categories and filters
3. see the result

### Expected result

1. Should look like in demos, should be collapsible

### Actual result

1. Looks like the following and is not collapsible

![image](https://user-images.githubusercontent.com/8351245/32062468-e5c38d06-ba74-11e7-915f-98122d070198.png)

**Comment by orlangur** [comment]
Hi @ci2014 which theme are you using? Only Blank and Luma themes are bundled within Magento, respective vendors should be contacted in case of other themes.

**Comment by ci2014** [comment]
The problem exists in the Luma and in the Blank Theme.

Heres a part of the source code. It doesn't look like the LayeredNavigation module is taking any effect:

"&lt;div class="widget block block-static-block"&gt;
    &lt;div class="categories-menu"&gt;&lt;strong class="title"&gt;&lt;span&gt;Women's Deals&lt;/span&gt;&lt;/strong&gt;
&lt;ul class="items"&gt;
    &lt;li class="item"&gt;&lt;a href="/women/tops-women/hoodies-and-sweatshirts-women.html"&gt;Hoodies and Sweatshirts&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/women/tops-women/jackets-women.html"&gt;Jackets&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/women/tops-women/tees-women.html"&gt;Tees&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/women/tops-women/tanks-women.html"&gt;Bras &amp;amp; Tanks&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/women/bottoms-women/pants-women.html"&gt;Pants&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/women/bottoms-women/shorts-women.html"&gt;Shorts&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;

&lt;strong class="title"&gt;&lt;span&gt;Mens's Deals&lt;/span&gt;&lt;/strong&gt;
&lt;ul class="items"&gt;
    &lt;li class="item"&gt;&lt;a href="/men/tops-men/hoodies-and-sweatshirts-men.html"&gt;Hoodies and Sweatshirts&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/men/tops-men/jackets-men.html"&gt;Jackets&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/men/tops-men/tees-men.html"&gt;Tees&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/men/bottoms-men/pants-men.html"&gt;Pants&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/men/bottoms-men/shorts-men.html"&gt;Shorts&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;

&lt;strong class="title"&gt;&lt;span&gt;Gear Deals&lt;/span&gt;&lt;/strong&gt;
&lt;ul class="items"&gt;
    &lt;li class="item"&gt;&lt;a href="/gear/bags.html"&gt;Bags&lt;/a&gt;&lt;/li&gt;
    &lt;li class="item"&gt;&lt;a href="/gear/fitness-equipment.html"&gt;Fitness Equipment&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;&lt;/div&gt;"

**Comment by ci2014** [comment]
It should look like this in Luma:

![image](https://user-images.githubusercontent.com/8351245/32065155-34219a04-ba7c-11e7-9187-302409c06a06.png)

**Comment by orlangur** [comment]
You stripped domain from `<a href="/women/tops-women/tees-women.html">` before pasting?

Ok, I doubt vanilla Luma theme contains such bug, let's wait for verification.

**Comment by ci2014** [comment]
@orlangur I did. The domain contains a customers name, so I thought it's not in their interest.

Maybe it helps to tell, that I've installed Magento via composer.

**Comment by orlangur** [comment]
Ok, just wanted to assure it's not some links starting from root.

**Comment by ci2014** [comment]
Thank you. I will investigate on this.

Edit: My conjectures were wrong, but the real problem exists: https://github.com/magento/magento2/issues/2121
