### ISSUE TITLE
Update 0.74.0-beta2 to 0.74.0-beta3

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2#1178]
Page not found.

http://devdocs.magento.com/guides/v1.0/install-gde/install/install-composer-install

See images.

I run this command and not update to 0.74.0-beta3.

su www-data

composer install

![captura de tela de 2015-04-08 19 37 01](https://cloud.githubusercontent.com/assets/2263217/7056933/c948ff80-de26-11e4-8790-94adc901edde.png)

![captura de tela de 2015-04-08 19 38 45](https://cloud.githubusercontent.com/assets/2263217/7056938/e904f504-de26-11e4-9a9e-85d730c58b1d.png)

**Comment by benmarks** [comment]
@cerebrumbr Where were you finding that link (http://devdocs.magento.com/guides/v1.0/install-gde/install/install-composer-install)?

**Comment by mazhalai** [comment]
@cerebrumbr I think this is the page you are looking for: [Updating the Magento software](http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-install.html#instgde-install-magento-update)

**Comment by cerebrumbr** [comment]
Hello Ben,

I met you at the Meet Magento Brazil.

It was a great pleasure .

This link with error 404.

http://devdocs.magento.com/guides/v1.0/install-gde/install/install-composer-install

Is this link in the phrase "Running Composer to update dependencies"

http://devdocs.magento.com/guides/v1.0/install-gde/install/prepare-install.html

I try update with this tutorial.

http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-install.html#instgde-install-magento-update

See images and error attached when try update.

![captura de tela de 2015-04-09 19 38 51](https://cloud.githubusercontent.com/assets/2263217/7078566/9c7c2480-def0-11e4-994b-57909c88c89e.png)

![captura de tela de 2015-04-09 19 38 59](https://cloud.githubusercontent.com/assets/2263217/7078568/a1676f2c-def0-11e4-966b-8acfed105e95.png)

![captura de tela de 2015-04-09 19 39 34](https://cloud.githubusercontent.com/assets/2263217/7078574/a6b7deda-def0-11e4-9a49-a345e3b2d6da.png)

![captura de tela de 2015-04-09 19 45 01](https://cloud.githubusercontent.com/assets/2263217/7078601/f1b9b192-def0-11e4-9425-6451c050d016.png)

**Comment by Sanuch** [comment]
@cerebrumbr You miss one step from [Updating the Magento software](http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-install.html#instgde-install-magento-update). You should run command `php -f index.php update` from `setup` folder but not from root

**Comment by mazhalai** [comment]
@cerebrumbr did suggestion by @Sanuch solve your issue?
