### ISSUE TITLE
Category and products not loading after upgrade to 2.2.0

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#11781]
I've upgraded magento version from 2.1.4 to 2.2.0 via composer. It's upgraded successfully, but somehow frontend not showing categories and products. Also, at backend categories not showing Product, Design Tabs etc.

Please suggest what could be the wrong here.

**Comment by magento-engcom-team** [comment]
Hello @deepak-netwin. I was not able to reproduce your issue with default Magento settings. Do you have any additional settings on your Magento? And can you give us more of the exact steps on how to reproduce your issue, it would be appreciated, so we can have a better understanding of this issue in order to help you. Thank you in advance.

**Comment by deepak-netwin** [comment]
@magento-engcom-team Thanks for your reply.
There is no specific case. I just upgraded magento version from 2.1.4 to 2.2.0 via composer and face that issue when logged in at backend as well as frontend.

**Comment by ishakhsuvarov** [comment]
@deepak-netwin Unfortunately we can not help in any way unless we are able to reproduce the issue as well.
Please try with the clean Magento installation, to make sure that none of the third-party extensions are causing the issue.
Thank you.

**Comment by deepak-netwin** [comment]
@ishakhsuvarov I've disabled all custom and third party extensions, then deployed content for Magento_Backend theme. However it still showing this error https://www.screencast.com/t/0rrqSitLF on Manage Category page at backend and not loading the tabs after Content https://www.screencast.com/t/DU7ofI54s4

**Comment by magento-engcom-team** [comment]
@deepak-netwin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by aamirxia** [comment]
I moved the complete setup from one server to another server. 

Using magento 2.1.1 thats also my wish to upgrade the magento 2.2.2 with new purchased theme. 
After installing magento 2.2.2 on new server there was an error with system backup.
with database and media backup i have installed magento 2.2.2 but now
Getting issue during opening a categorized product "Unable to unserialize value."
![image](https://user-images.githubusercontent.com/36257117/35973291-afc2a1c2-0cf6-11e8-8453-0104e48a40d5.png)
Please advise It Will be highly appreciated
