### ISSUE TITLE
Rest issues with M2 and Nginx

### ISSUE THREAD

**Issue by bch80** [magento/magento2#11789]
### Preconditions

1. Magento 2.1.9, nginx/1.8.1, PHP 7.0.7-1~dotdeb+8.1

### Steps to reproduce

1. Install Magento 2
2. Working with Teapplix.com - it shall sync my products and orders, but the company is very unresponsive and not good / fast at solving problems.

### Expected result

1. Magento 2 should enable another software to access data via the API

### Actual result

1. 404

2017/10/26 11:51:54 [error] 4183#4183: *710748 open() "/var/www/html/domain.com/www.domain.com/pub/rest/V1/integration/admin/token" failed (2: No such file or directory), client: 64.71.137.40, server: www.domain.com, request: "POST /rest/V1/integration/admin/token HTTP/1.1", host: "www.domain.com"

I assume it has something to do with my nginx setup.
That's my file:

`limit_req_zone $binary_remote_addr zone=mylimit:10m rate=2r/s;

server {
        listen 80;
        server_name domain.com;
        return       301 http://www.domain.com$request_uri;
}

server {
	set $MAGE_ROOT /var/www/html/domain.com/www.domain.com;

	listen 80;
	#server_name domain.hammer-loesungen.de; 
	server_name www.domain.com;

	# Domain is here twice so server_name_in_redirect will favour the www
	#        root /var/www/html/domain.com/www.domain.com;

	#
	## Optional override of deployment mode. We recommend you use the
	## command 'bin/magento deploy:mode:set' to switch modes instead.
	##
	## set $MAGE_MODE default; # or production or developer
	##
	## If you set MAGE_MODE in server config, you must pass the variable into the
	## PHP entry point blocks, which are indicated below. You can pass
	## it in using:
	##
	## fastcgi_param  MAGE_MODE $MAGE_MODE;
	##
	## In production mode, you should uncomment the 'expires' directive in the /static/ location block

	root $MAGE_ROOT/pub;

	index index.php;
	autoindex off;
	charset UTF-8;
	error_page 404 403 = /errors/404.php;
	#add_header "X-UA-Compatible" "IE=Edge";

        access_log /var/log/nginx/domain.com_access.log;
        error_log /var/log/nginx/domain.com_error.log;

	location ~* ^/bridge2cart($|/) {
		root $MAGE_ROOT;
		# location ~ ^/bridge2cart/index.php {
		# fastcgi_pass   fastcgi_backend;
		fastcgi_pass   unix:/run/php/php7.0-fpm.sock;

		fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
		fastcgi_param  PHP_VALUE "memory_limit=768M \n max_execution_time=600";
		fastcgi_read_timeout 600s;
		fastcgi_connect_timeout 600s;

		fastcgi_index  index.php;
		fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
		include        fastcgi_params;
	}

	if ($http_user_agent ~* (360Spider|80legs.com|Abonti|AcoonBot|Acunetix|adbeat_bot|AddThis.com|adidxbot|ADmantX|AhrefsBot|AngloINFO|Antelope|Applebot|BaiduSpider|BeetleBot|billigerbot|binlar|bitlybot|BlackWidow|BLP_bbot|BoardReader|Bolt\ 0|BOT\ for\ JCE|Bot\ mailto\:craftbot@yahoo\.com|casper|CazoodleBot|CCBot|checkprivacy|ChinaClaw|chromeframe|Clerkbot|Cliqzbot|clshttp|CommonCrawler|comodo|CPython|crawler4j|Crawlera|CRAZYWEBCRAWLER|Curious|Curl|Custo|CWS_proxy|Default\ Browser\ 0|diavol|DigExt|Digincore|DIIbot|discobot|DISCo|DoCoMo|DotBot|Download\ Demon|DTS.Agent|EasouSpider|eCatch|ecxi|EirGrabber|Elmer|EmailCollector|EmailSiphon|EmailWolf|Exabot|ExaleadCloudView|ExpertSearchSpider|ExpertSearch|Express\ WebPictures|ExtractorPro|extract|EyeNetIE|Ezooms|F2S|FastSeek|feedfinder|FeedlyBot|FHscan|finbot|Flamingo_SearchEngine|FlappyBot|FlashGet|flicky|Flipboard|g00g1e|Genieo|genieo|GetRight|GetWeb\!|GigablastOpenSource|GozaikBot|Go\!Zilla|Go\-Ahead\-Got\-It|GrabNet|grab|Grafula|GrapeshotCrawler|GTB5|GT\:\:WWW|Guzzle|harvest|heritrix|HMView|HomePageBot|HTTP\:\:Lite|HTTrack|HubSpot|ia_archiver|icarus6|IDBot|id\-search|IlseBot|Image\ Stripper|Image\ Sucker|Indigonet|Indy\ Library|integromedb|InterGET|InternetSeer\.com|Internet\ Ninja|IRLbot|ISC\ Systems\ iRc\ Search\ 2\.1|jakarta|Java|JetCar|JobdiggerSpider|JOC\ Web\ Spider|Jooblebot|kanagawa|KINGSpider|kmccrew|larbin|LeechFTP|libwww|Lingewoud|LinkChecker|linkdexbot|LinksCrawler|LinksManager\.com_bot|linkwalker|LinqiaRSSBot|LivelapBot|ltx71|LubbersBot|lwp\-trivial|Mail.RU_Bot|masscan|Mass\ Downloader|maverick|Maxthon$|Mediatoolkitbot|MegaIndex|MegaIndex|megaindex|MFC_Tear_Sample|Microsoft\ URL\ Control|microsoft\.url|MIDown\ tool|miner|Missigua\ Locator|Mister\ PiX|mj12bot|Mozilla.*Indy|Mozilla.*NEWT|MSFrontPage|msnbot|Navroad|NearSite|NetAnts|netEstate|NetSpider|NetZIP|Net\ Vampire|NextGenSearchBot|nutch|Octopus|Offline\ Explorer|Offline\ Navigator|OpenindexSpider|OpenWebSpider|OrangeBot|Owlin|PageGrabber|PagesInventory|panopta|panscient\.com|Papa\ Foto|pavuk|pcBrowser|PECL\:\:HTTP|PeoplePal|Photon|PHPCrawl|planetwork|PleaseCrawl|PNAMAIN.EXE|PodcastPartyBot|prijsbest|proximic|psbot|purebot|pycurl|QuerySeekerSpider|R6_CommentReader|R6_FeedFetcher|RealDownload|ReGet|Riddler|Rippers\ 0|rogerbot|RSSingBot|rv\:1.9.1|RyzeCrawler|SafeSearch|SBIder|Scrapy|Scrapy|Screaming|SeaMonkey$|search.goo.ne.jp|SearchmetricsBot|search_robot|SemrushBot|Semrush|SentiBot|SEOkicks|SeznamBot|ShowyouBot|SightupBot|SISTRIX|sitecheck\.internetseer\.com|siteexplorer.info|SiteSnagger|skygrid|Slackbot|Slurp|SmartDownload|Snoopy|Sogou|Sosospider|spaumbot|Steeler|sucker|SuperBot|Superfeedr|SuperHTTP|SurdotlyBot|Surfbot|tAkeOut|Teleport\ Pro|TinEye-bot|TinEye|Toata\ dragostea\ mea\ pentru\ diavola|Toplistbot|trendictionbot|TurnitinBot|turnit|URI\:\:Fetch|urllib|Vagabondo|Vagabondo|vikspider|VoidEYE|VoilaBot|WBSearchBot|webalta|WebAuto|WebBandit|WebCollage|WebCopier|WebFetch|WebGo\ IS|WebLeacher|WebReaper|WebSauger|Website\ eXtractor|Website\ Quester|WebStripper|WebWhacker|WebZIP|Web\ Image\ Collector|Web\ Sucker|Wells\ Search\ II|WEP\ Search|WeSEE|Wget|Widow|WinInet|woobot|woopingbot|worldwebheritage.org|Wotbox|WPScan|WWWOFFLE|WWW\-Mechanize|Xaldon\ WebSpider|XoviBot|yacybot|YandexBot|Yandex|YisouSpider|zermelo|Zeus|zh-CN|ZmEu|ZumBot|ZyBorg) ) {
    return 410;
}

	location /rest/V1/ {
		limit_req zone=mylimit;
		#proxy_pass http://my_upstream;
	}

	# PHP entry point for setup application
	location ~* ^/setup($|/) {
		root $MAGE_ROOT;
		location ~ ^/setup/index.php {
			# fastcgi_pass   fastcgi_backend;
			fastcgi_pass   unix:/run/php/php7.0-fpm.sock;

			fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
			fastcgi_param  PHP_VALUE "memory_limit=768M \n max_execution_time=600";
			fastcgi_read_timeout 600s;
			fastcgi_connect_timeout 600s;

			fastcgi_index  index.php;
			fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			include        fastcgi_params;
		}

		location ~ ^/setup/(?!pub/). {
			deny all;
		}

		location ~ ^/setup/pub/ {
			add_header X-Frame-Options "SAMEORIGIN";
		}
	}

	# PHP entry point for update application
	location ~* ^/update($|/) {
		root $MAGE_ROOT;

		location ~ ^/update/index.php {
			fastcgi_split_path_info ^(/update/index.php)(/.+)$;
			# fastcgi_pass   fastcgi_backend;
			fastcgi_pass   unix:/run/php/php7.0-fpm.sock;
			fastcgi_index  index.php;
			fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			fastcgi_param  PATH_INFO        $fastcgi_path_info;
			include        fastcgi_params;
		}

		# Deny everything but index.php
		location ~ ^/update/(?!pub/). {
			deny all;
		}

		location ~ ^/update/pub/ {
			add_header X-Frame-Options "SAMEORIGIN";
		}
	}

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location /pub/ {
		location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
			deny all;
		}
		alias $MAGE_ROOT/pub/;
		add_header X-Frame-Options "SAMEORIGIN";
	}

	location /static/ {
		# Uncomment the following line in production mode
		expires max;

		# Remove signature of the static files that is used to overcome the browser cache
		location ~ ^/static/version {
			rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
		}

		location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
			add_header Cache-Control "public";
			add_header X-Frame-Options "SAMEORIGIN";
			expires +1y;

			if (!-f $request_filename) {
				rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
			}
		}
		location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
			add_header Cache-Control "no-store";
			add_header X-Frame-Options "SAMEORIGIN";
			expires    off;

			if (!-f $request_filename) {
			   rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
			}
		}
		if (!-f $request_filename) {
			rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
		}
		add_header X-Frame-Options "SAMEORIGIN";
	}

	location /media/ {
		try_files $uri $uri/ /get.php?$args;

		location ~ ^/media/theme_customization/.*\.xml {
			deny all;
		}

		location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
			add_header Cache-Control "public";
			add_header X-Frame-Options "SAMEORIGIN";
			expires +1y;
			try_files $uri $uri/ /get.php?$args;
		}
		location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
			add_header Cache-Control "no-store";
			add_header X-Frame-Options "SAMEORIGIN";
			expires    off;
			try_files $uri $uri/ /get.php?$args;
		}
		add_header X-Frame-Options "SAMEORIGIN";
	}

	location /media/customer/ {
		deny all;
	}

	location /media/downloadable/ {
		deny all;
	}

	location /media/import/ {
		deny all;
	}

	# PHP entry point for main application
	location ~ (index|get|static|report|404|503)\.php$ {
		try_files $uri =404;
		# fastcgi_pass   fastcgi_backend;
		fastcgi_pass   unix:/run/php/php7.0-fpm.sock;
		fastcgi_buffers 1024 4k;

		fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
		fastcgi_param  PHP_VALUE "memory_limit=768M \n max_execution_time=18000";
		fastcgi_read_timeout 600s;
		fastcgi_connect_timeout 600s;

		fastcgi_index  index.php;
		fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
		include        fastcgi_params;
	}

	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	gzip_min_length 1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	gzip_types
		text/plain
		text/css
		text/js
		text/xml
		text/javascript
		application/javascript
		application/x-javascript
		application/json
		application/xml
		application/xml+rss
		image/svg+xml;
	gzip_vary on;

	# Banned locations (only reached if the earlier PHP entry point regexes don't match)
	location ~* (\.php$|\.htaccess$|\.git) {
		deny all;
	}
}

server {
	set $MAGE_ROOT /var/www/html/domain.com/www.domain.com;

	listen 443 ssl;
	ssl on;
	# Combined keys:
	ssl_certificate /home/secuuser/ssl_certificate/domain.com.bundle.crt;
	# Private key:
	ssl_certificate_key /home/secuuser/ssl_certificate/domain.com.priv.key;
	#ssl_certificate /etc/ssl/cert_chain.crt;
	#ssl_certificate_key should be pointed to the Private Key that has been generated with the CSR code that you have used for activation of the certificate.
	#ssl_certificate_key /etc/ssl/*your_private_key*.key;

	#server_name domain.hammer-loesungen.de; 
	server_name www.domain.com;

	access_log /var/log/nginx/domain.com_access.log;
	error_log /var/log/nginx/domain.com_error.log;

	# Domain is here twice so server_name_in_redirect will favour the www
	#        root /var/www/html/domain.com/www.domain.com;

	#
	## Optional override of deployment mode. We recommend you use the
	## command 'bin/magento deploy:mode:set' to switch modes instead.
	##
	## set $MAGE_MODE default; # or production or developer
	##
	## If you set MAGE_MODE in server config, you must pass the variable into the
	## PHP entry point blocks, which are indicated below. You can pass
	## it in using:
	##
	## fastcgi_param  MAGE_MODE $MAGE_MODE;
	##
	## In production mode, you should uncomment the 'expires' directive in the /static/ location block

	root $MAGE_ROOT/pub;

	index index.php;
	autoindex off;
	charset UTF-8;
	error_page 404 403 = /errors/404.php;
	#add_header "X-UA-Compatible" "IE=Edge";

	location ~* ^/bridge2cart($|/) {
		root $MAGE_ROOT;
		# location ~ ^/bridge2cart/index.php {
		# fastcgi_pass   fastcgi_backend;
		fastcgi_pass   unix:/run/php/php7.0-fpm.sock;

		fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
		fastcgi_param  PHP_VALUE "memory_limit=768M \n max_execution_time=600";
		fastcgi_read_timeout 600s;
		fastcgi_connect_timeout 600s;

		fastcgi_index  index.php;
		fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
		include        fastcgi_params;
	}

if ($http_user_agent ~* (360Spider|80legs.com|Abonti|AcoonBot|Acunetix|adbeat_bot|AddThis.com|adidxbot|ADmantX|AhrefsBot|AngloINFO|Antelope|Applebot|BaiduSpider|BeetleBot|billigerbot|binlar|bitlybot|BlackWidow|BLP_bbot|BoardReader|Bolt\ 0|BOT\ for\ JCE|Bot\ mailto\:craftbot@yahoo\.com|casper|CazoodleBot|CCBot|checkprivacy|ChinaClaw|chromeframe|Clerkbot|Cliqzbot|clshttp|CommonCrawler|comodo|CPython|crawler4j|Crawlera|CRAZYWEBCRAWLER|Curious|Curl|Custo|CWS_proxy|Default\ Browser\ 0|diavol|DigExt|Digincore|DIIbot|discobot|DISCo|DoCoMo|DotBot|Download\ Demon|DTS.Agent|EasouSpider|eCatch|ecxi|EirGrabber|Elmer|EmailCollector|EmailSiphon|EmailWolf|Exabot|ExaleadCloudView|ExpertSearchSpider|ExpertSearch|Express\ WebPictures|ExtractorPro|extract|EyeNetIE|Ezooms|F2S|FastSeek|feedfinder|FeedlyBot|FHscan|finbot|Flamingo_SearchEngine|FlappyBot|FlashGet|flicky|Flipboard|g00g1e|Genieo|genieo|GetRight|GetWeb\!|GigablastOpenSource|GozaikBot|Go\!Zilla|Go\-Ahead\-Got\-It|GrabNet|grab|Grafula|GrapeshotCrawler|GTB5|GT\:\:WWW|Guzzle|harvest|heritrix|HMView|HomePageBot|HTTP\:\:Lite|HTTrack|HubSpot|ia_archiver|icarus6|IDBot|id\-search|IlseBot|Image\ Stripper|Image\ Sucker|Indigonet|Indy\ Library|integromedb|InterGET|InternetSeer\.com|Internet\ Ninja|IRLbot|ISC\ Systems\ iRc\ Search\ 2\.1|jakarta|Java|JetCar|JobdiggerSpider|JOC\ Web\ Spider|Jooblebot|kanagawa|KINGSpider|kmccrew|larbin|LeechFTP|libwww|Lingewoud|LinkChecker|linkdexbot|LinksCrawler|LinksManager\.com_bot|linkwalker|LinqiaRSSBot|LivelapBot|ltx71|LubbersBot|lwp\-trivial|Mail.RU_Bot|masscan|Mass\ Downloader|maverick|Maxthon$|Mediatoolkitbot|MegaIndex|MegaIndex|megaindex|MFC_Tear_Sample|Microsoft\ URL\ Control|microsoft\.url|MIDown\ tool|miner|Missigua\ Locator|Mister\ PiX|mj12bot|Mozilla.*Indy|Mozilla.*NEWT|MSFrontPage|msnbot|Navroad|NearSite|NetAnts|netEstate|NetSpider|NetZIP|Net\ Vampire|NextGenSearchBot|nutch|Octopus|Offline\ Explorer|Offline\ Navigator|OpenindexSpider|OpenWebSpider|OrangeBot|Owlin|PageGrabber|PagesInventory|panopta|panscient\.com|Papa\ Foto|pavuk|pcBrowser|PECL\:\:HTTP|PeoplePal|Photon|PHPCrawl|planetwork|PleaseCrawl|PNAMAIN.EXE|PodcastPartyBot|prijsbest|proximic|psbot|purebot|pycurl|QuerySeekerSpider|R6_CommentReader|R6_FeedFetcher|RealDownload|ReGet|Riddler|Rippers\ 0|rogerbot|RSSingBot|rv\:1.9.1|RyzeCrawler|SafeSearch|SBIder|Scrapy|Scrapy|Screaming|SeaMonkey$|search.goo.ne.jp|SearchmetricsBot|search_robot|SemrushBot|Semrush|SentiBot|SEOkicks|SeznamBot|ShowyouBot|SightupBot|SISTRIX|sitecheck\.internetseer\.com|siteexplorer.info|SiteSnagger|skygrid|Slackbot|Slurp|SmartDownload|Snoopy|Sogou|Sosospider|spaumbot|Steeler|sucker|SuperBot|Superfeedr|SuperHTTP|SurdotlyBot|Surfbot|tAkeOut|Teleport\ Pro|TinEye-bot|TinEye|Toata\ dragostea\ mea\ pentru\ diavola|Toplistbot|trendictionbot|TurnitinBot|turnit|URI\:\:Fetch|urllib|Vagabondo|Vagabondo|vikspider|VoidEYE|VoilaBot|WBSearchBot|webalta|WebAuto|WebBandit|WebCollage|WebCopier|WebFetch|WebGo\ IS|WebLeacher|WebReaper|WebSauger|Website\ eXtractor|Website\ Quester|WebStripper|WebWhacker|WebZIP|Web\ Image\ Collector|Web\ Sucker|Wells\ Search\ II|WEP\ Search|WeSEE|Wget|Widow|WinInet|woobot|woopingbot|worldwebheritage.org|Wotbox|WPScan|WWWOFFLE|WWW\-Mechanize|Xaldon\ WebSpider|XoviBot|yacybot|YandexBot|Yandex|YisouSpider|zermelo|Zeus|zh-CN|ZmEu|ZumBot|ZyBorg) ) {
    return 410;
}

	# PHP entry point for setup application
	location ~* ^/setup($|/) {
		root $MAGE_ROOT;
		location ~ ^/setup/index.php {
			# fastcgi_pass   fastcgi_backend;
			fastcgi_pass   unix:/run/php/php7.0-fpm.sock;

			fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
			fastcgi_param  PHP_VALUE "memory_limit=768M \n max_execution_time=600";
			fastcgi_read_timeout 600s;
			fastcgi_connect_timeout 600s;

			fastcgi_index  index.php;
			fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			include        fastcgi_params;
		}

		location ~ ^/setup/(?!pub/). {
			deny all;
		}

		location ~ ^/setup/pub/ {
			add_header X-Frame-Options "SAMEORIGIN";
		}
	}

	# PHP entry point for update application
	location ~* ^/update($|/) {
		root $MAGE_ROOT;

		location ~ ^/update/index.php {
			fastcgi_split_path_info ^(/update/index.php)(/.+)$;
			# fastcgi_pass   fastcgi_backend;
			fastcgi_pass   unix:/run/php/php7.0-fpm.sock;
			fastcgi_index  index.php;
			fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			fastcgi_param  PATH_INFO        $fastcgi_path_info;
			include        fastcgi_params;
		}

		# Deny everything but index.php
		location ~ ^/update/(?!pub/). {
			deny all;
		}

		location ~ ^/update/pub/ {
			add_header X-Frame-Options "SAMEORIGIN";
		}
	}

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location /pub/ {
		location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
			deny all;
		}
		alias $MAGE_ROOT/pub/;
		add_header X-Frame-Options "SAMEORIGIN";
	}

	location /static/ {
		# Uncomment the following line in production mode
		expires max;

		# Remove signature of the static files that is used to overcome the browser cache
		location ~ ^/static/version {
			rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
		}

		location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
			add_header Cache-Control "public";
			add_header X-Frame-Options "SAMEORIGIN";
			expires +1y;

			if (!-f $request_filename) {
				rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
			}
		}
		location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
			add_header Cache-Control "no-store";
			add_header X-Frame-Options "SAMEORIGIN";
			expires    off;

			if (!-f $request_filename) {
			   rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
			}
		}
		if (!-f $request_filename) {
			rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
		}
		add_header X-Frame-Options "SAMEORIGIN";
	}

	location /media/ {
		try_files $uri $uri/ /get.php?$args;

		location ~ ^/media/theme_customization/.*\.xml {
			deny all;
		}

		location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
			add_header Cache-Control "public";
			add_header X-Frame-Options "SAMEORIGIN";
			expires +1y;
			try_files $uri $uri/ /get.php?$args;
		}
		location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
			add_header Cache-Control "no-store";
			add_header X-Frame-Options "SAMEORIGIN";
			expires    off;
			try_files $uri $uri/ /get.php?$args;
		}
		add_header X-Frame-Options "SAMEORIGIN";
	}

	location /media/customer/ {
		deny all;
	}

	location /media/downloadable/ {
		deny all;
	}

	location /media/import/ {
		deny all;
	}

	# PHP entry point for main application
	location ~ (index|get|static|report|404|503)\.php$ {
		try_files $uri =404;
		# fastcgi_pass   fastcgi_backend;
		fastcgi_pass   unix:/run/php/php7.0-fpm.sock;
		fastcgi_buffers 1024 4k;

		fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
		fastcgi_param  PHP_VALUE "memory_limit=768M \n max_execution_time=18000";
		fastcgi_read_timeout 600s;
		fastcgi_connect_timeout 600s;

		fastcgi_index  index.php;
		fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
		include        fastcgi_params;
	}

	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	gzip_min_length 1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	gzip_types
		text/plain
		text/css
		text/js
		text/xml
		text/javascript
		application/javascript
		application/x-javascript
		application/json
		application/xml
		application/xml+rss
		image/svg+xml;
	gzip_vary on;

	# Banned locations (only reached if the earlier PHP entry point regexes don't match)
	#location ~* (\.php$|\.htaccess$|\.git) {
	#	deny all;
	#}
}
`

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
