### ISSUE TITLE
admin in the 14 inch notebook menu not fully displayed

### ISSUE THREAD

**Issue by yzm629** [magento/magento2#1179]
admin in the 14 inch notebook menu not fully displayed

**Comment by godban** [comment]
Hello @yzm629, thank you for report. This is the same issue with #1120
New Magento Admin look & feel work now is in progress and menu issues will be addressed soon.

Internal ticket MAGETWO-34929

**Comment by vpelipenko** [comment]
Closed as duplicate. @yzm629, please look for updates in #1120. We'll inform you when it is fixed.
