### ISSUE TITLE
Post-migration error on product view/edit

### ISSUE THREAD

**Issue by jphat** [magento/magento2#11791]
### Preconditions

1. Magento 2.2.0 
2. Ubuntu 16 + PHP 7.0 + MySQL

### Actual result

Coming from Magento 1.9.3.6 to 2.2.0, migration process went relatively well and the 2.2 site is up expect while viewing or trying to edit a product, I get the following error:

`1 exception(s): Exception #0 (InvalidArgumentException): Unable to unserialize value.`
`Exception #0 (InvalidArgumentException): Unable to unserialize value.`
`#0 /var/www/newstore/vendor/magento/module-catalog-inventory/Helper/Minsaleqty.php(113): Magento\Framework\Serialize\Serializer\Json->unserialize('a:0:{}')`
`#1 /var/www/newstore/vendor/magento/module-catalog-inventory/Helper/Minsaleqty.php(198): Magento\CatalogInventory\Helper\Minsaleqty->unserializeValue('a:0:{}')`
`#2 /var/www/newstore/vendor/magento/module-catalog-inventory/Model/Configuration.php(229): Magento\CatalogInventory\Helper\Minsaleqty->getConfigValue(0, '1')`
`#3 /var/www/newstore/vendor/magento/module-catalog-inventory/Model/Stock/Item.php(304): Magento\CatalogInventory\Model\Configuration->getMinSaleQty('1', 0)`
`#4 /var/www/newstore/vendor/magento/module-catalog/Block/Product/AbstractProduct.php(203): Magento\CatalogInventory\Model\Stock\Item->getMinSaleQty()`
`#5 /var/www/newstore/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(232): Magento\Catalog\Block\Product\AbstractProduct->getMinimalQty(Object(Magento\Catalog\Model\Product\Interceptor))`

it goes on for 90-some lines.

any help is appreciated

**Comment by renttek** [comment]
Did you use the migration tool?

The problem seems to be, that the values in the DB are serialized (http://php.net/manual/de/function.serialize.php) but Magento 2.2 expects those values to be JSON.

Here is the commit with the change: https://github.com/magento/magento2/commit/f4f7d8104d25cb55f12c6b2d5749045229034867

On upgrade to 2.2, the Catalog module should've converted those values to json, as seen in 
Magento/vendor/magento/module-catalog-inventory/Setup/UpgradeData.php Line 81

I also have to migrate a store the next days, so I'll take a look on this.

**Comment by BastienDurel** [comment]
Got this too, after a migration (with migration tool) from 1.7

**Comment by renttek** [comment]
Hey,
I tried the DMT (data migration tool) today and had kind of the same errors.
I created an issue in the DMT repo: https://github.com/magento/data-migration-tool/issues/401

I'll try to find some time the next days to create a fix for this in the DMT.

**Comment by orlangur** [comment]
@renttek thanks for filing an issue in appropriate repository.

**Comment by ultrazeus** [comment]
Is there a fix available for this problem? I am having the same after a migration (with migration tool) from 1.7).

**Comment by orlangur** [comment]
@julienvb please check an issue mentioned in https://github.com/magento/magento2/issues/11791#issuecomment-339971282 :)
