### ISSUE TITLE
Magento 2.1.9 - Refunding / Credit Memo Total Value is not updated

### ISSUE THREAD

**Issue by amenk** [magento/magento2#11798]
### Preconditions
1. Magneto 2.1.9
2. Order with Online Payment Created

### Steps to reproduce
1.  Select invoice
2. Choose quantity 0
3. Press update quantity
4. Enter Refund Adjustmenet 10,00 EUR

### Expected result
1. The credit memo total is updated

### Actual result
1. It is not updated, you have to refund blindly

Additional catch: 10,00 is interpreted as 10.00 so this is error prone

Additional catch: The entry fields are to narrow

**Comment by magento-engcom-team** [comment]
@amenk, thank you for your report.
We've created internal ticket(s) MAGETWO-82894 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @amenk. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1185 by @serhii-balko in 2.2-develop branch
Related commit(s):
 - 451f7b9f317db5a27d3d9c541cc3c1678cc169f5

The fix will be available with the upcoming 2.2.4 release.
