### ISSUE TITLE
Design configuration (2.2.0) does not save

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/magento2#11800]
**Preconditions**

1. Magento 2.2
2. After Migration From 1.9.3.2

**Steps to reproduce**

1. Login to Admin got to Content->Design -> Configration
2. Select Any Store and click edit action
3. Do any changes -> Click of Save 

**Expected result**

Changes should be saved and refresh page .

**Actual result**

> 404 error: Page not found. 

![issue](https://user-images.githubusercontent.com/32513730/32096785-1d569a3c-bb25-11e7-8bf0-1a071a5776f6.png)

**Comment by yogeshsyscraft** [comment]
@magento-engcom-team : What is Meaning of G! FAILED LABEL ..

**Comment by yogeshsyscraft** [comment]
@magento-engcom-team :: Please Check again now , and help me asap

**Comment by magento-engcom-team** [comment]
@yogeshsyscraft, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by yogeshsyscraft** [comment]
@magento-engcom-team  :  Thanks For your reply ,

This issue comes after migration From Magento 19.3.2 To Magento 2.2.0 , please suggest something , how to resolve ,

Thanks
Yogesh

**Comment by yogeshsyscraft** [comment]
when i debug , i found 

> Save .php 

Action is not Being Executed , i have tried to Test With 

> Die();   


but still page redirect to 404 , 

please suggest something ,

**Comment by yogeshsyscraft** [comment]
how will it solved  ? @magento-engcom-team

**Comment by ishakhsuvarov** [comment]
Hi @yogeshsyscraft 
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by yogeshsyscraft** [comment]
Hi @ishakhsuvarov  
i have raised issue there , but no one is responding .

**Comment by linomarmo** [comment]
I have the same problem in a new installation
I try to adding a external css and save but:
admin/theme/design_config/save/key/b29dcd46b9021d145703f58d039698bacf2cf1151b4fd104d3b87a8a8b1552df/
Show 404 page

**Comment by jleal-pnet** [comment]
Same error here in Magento 2.2.3

**Comment by Alexie77** [comment]
I have the same issue.
I installed Magento 2.2.4 yesterday.
And I can't save the changes to the configuration.
I get the msg:
"Something went wrong while saving this configuration: Area is already set"

See the attached screenshot.

![screen shot 05-21-18 at 04 41 pm](https://user-images.githubusercontent.com/39501661/40329048-514fe6d4-5d16-11e8-8ff7-98fb0d1da654.PNG)

**Comment by alirazabhatti** [comment]
i have the same issue can any one help?

**Comment by oleksiy-iwdagency** [comment]
I can reproduce it on 2.3.3 version too. But looks like it's not related to the Magento version. Maybe, it's server-side configuration/settings, because, I can reproduce it only on some servers for the same project. 
I noticed what I have 404 error when I try to insert js script in footer. A good example is an Olark chat. After some investigation, I found a small script that causes the issue when I try to save it in "Miscellaneous HTML":

`<script type="text/javascript">
function(){var src="";}
</script>`

We can rename the variable `src` to `src2` and it saved.
Or we can remove `type="text/javascript"` parameter from tag `script` and it saved too.

**Comment by realadityayadav** [comment]
https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Admin-Changing-Theme-Content-Design-Configuration-Help-Need/m-p/74196#M1681

This is related to the Mod Security module for someone who comes up hunting for solution.
