### ISSUE TITLE
cannot login to magento 2

### ISSUE THREAD

**Issue by neginparsa** [magento/magento2#1180]
I installed magento2 , I can see the home page, it does not have any theme but I can see some text
![capture](https://cloud.githubusercontent.com/assets/3474113/7060454/103717c4-de36-11e4-91eb-d9696cb56d28.PNG)
I had many problems installing magento 2 such as xdebug nesting levels during installation, rewrite module not completeley loaded though was there and etc

it's better in section PHP Extensions Check that are the modules to be ready for installation, add the mode_rewrite also to be checked 

I tried to use previous magento community versions and all of them on my pc had problem of not logging in and I have solved them by going to app/code/core/Mage/Core/Model/Session/Abstract/Varien.php and commenting out some lines 
which is not cool but solves the issue.

Now, I wanted to know what I can do to solve my problem.

**Comment by JesusTinoco** [comment]
Try to execute this command being inside the magento folder root.
`php -f dev/tools/Magento/Tools/View/deploy.php`

**Comment by mazhalai** [comment]
@neginparsa 
- Re mod_rewrite, is it possible you have 2 different php versions? It is a common issue that extensions are loaded for PHP in the command line, but not for the PHP version used by apache.
- We will note suggestion of adding a check for mod_rewrite.
- There is no `app/code/core/Mage/Core/Model/Session/Abstract/Varien.php` in Magento2. Please verify your code base.
- Did suggestion by @JesusTinoco solve your problem?

**Comment by neginparsa** [comment]
@JesusTinoco  I cannot execute although the path is correct and dev exists there
I did this : php -f dev\tools\Magento\Tools\View\deploy.php
because I am on windows and it should be backslash

.
ERROR: Cannot read contents from file "C:/wamp/www/magento2-develop/" Warning!fi
le_get_contents(C:/wamp/www/magento2-develop/): failed to open stream: No such f
ile or directory (Processing file 'js/row-builder.js' for area 'adminhtml', them
e 'Magento/backend', locale 'en_US', module 'Magento_Theme')
.
ERROR: Cannot read contents from file "C:/wamp/www/magento2-develop/" Warning!fi
le_get_contents(C:/wamp/www/magento2-develop/): failed to open stream: No such f
ile or directory (Processing file 'js/truncate.js' for area 'adminhtml', theme '
Magento/backend', locale 'en_US', module 'Magento_Theme')
................................................................................
...................................
ERROR: Cannot read contents from file "C:/wamp/www/magento2-develop/" Warning!fi
le_get_contents(C:/wamp/www/magento2-develop/): failed to open stream: No such f
ile or directory (Processing file 'js/add-to-wishlist.js' for area 'adminhtml',
theme 'Magento/backend', locale 'en_US', module 'Magento_Wishlist')
.
ERROR: Cannot read contents from file "C:/wamp/www/magento2-develop/" Warning!fi
le_get_contents(C:/wamp/www/magento2-develop/): failed to open stream: No such f
ile or directory (Processing file 'js/search.js' for area 'adminhtml', theme 'Ma
gento/backend', locale 'en_US', module 'Magento_Wishlist')

Maybe it is something with permissions I don't know
@mazhalai  I do not have two versions only one version of 

PHP 5.5.12 (cli) (built: Apr 30 2014 11:20:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

@mazhalai  as I said PREVIOUS versions not magento2 I solved this issue by that

**Comment by TapaniAla** [comment]
I have a similar messy frontpage but the reason is that fontend and adminhtml directories are missing from the pub directory. I don't know why they are missing but I assume that it is an issue with apache rewrites. Any suggestions how to fix this problem?

**Comment by minhluan259** [comment]
"I installed magento2 , I can see the home page, it does not have any theme but I can see some text"
==> I have a similar. (Xampp on windows)
Backend and frontend show some text.
http://www.awesomescreenshot.com/image/120729/57820bef607f7ac8b38b189191a6c2d3

**Comment by mazhalai** [comment]
@TapaniAla and @minhluan259 have you tried this solution in [Magento's troubleshooting guide](http://devdocs.magento.com/guides/v1.0/install-gde/trouble/tshoot_no-styles.html)

**Comment by TapaniAla** [comment]
I have already fixed this problem according to @JesusTinoco instructions. Please note that there will be a time out in deployer.php unless you increase the time_out setting from the default 30 seconds to something like 300 seconds.

**Comment by otoolec** [comment]
If you are still having this issue and are running on windows can you see if [disabling symlinks](http://magento.stackexchange.com/questions/63117/magento-2-problem-in-admin-login/64809#64809) fixes the problem for you?  Please report back if it did so we can prioritize a proper fix.

**Comment by snohe** [comment]
@neginparsa, checking in to see if @otoolec's advice worked for you.

**Comment by neginparsa** [comment]
I don't have any update unfortunately. you can close the task I will reopen
when I tried and if I had any issues.
Thank you.


Sincerely
Negin Nickparsa

**Comment by vpelipenko** [comment]
Closed. Please, reopen in case of updates.
