### ISSUE TITLE
M2.1.9 : Snapshot does not take extension attributes into account

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#11812]
When I set specific extension attributes for an object (invoice in my case), and I trigger a save, the `sales_order_invoice_safe_after` event is not dispatched. This is because `\Magento\Framework\Model\ResourceModel\Db\VersionControl\Snapshot::isModified()` does not take extension attributes into account.

Please not that I cannot use a repository `save()`/`get()`-plugin for this, because invoices are saved from the admin using database transactions (see `\Magento\Sales\Controller\Adminhtml\Order\Invoice\Save::execute()`). That's why I fall back the the events after loading and saving.

### Preconditions

1. Magento 2.1.9

### Steps to reproduce

1. Create extension attributes for the Invoice model
2. Add a hook to the `sales_order_invoice_safe_after`-event to process the extension attribute.
3. Load an invoice, set the extension attribute value, and save it using the repository

### Expected result

1. Logic to process extension attribute should be executed.

### Actual result

1. Logic is not executed.

In the scenario of the Invoice this is because the `isModified()`-method of it's resource model checks with the Snapshot class if the object is modified, whereas the regular resource model does this by checking `hasDataChanges()`, which can be overwritten.

I suppose that in my case I have to catch the events (because of the db transaction layer), ánd have to add a plugin for the `save()`-method of the repository, but this seems a bit like overhead. Plus: other models (that use snapshots) might have the same issue as well when extension attributes come into play.

**Comment by orlangur** [comment]
It's up to you how extension attributes are saved and loaded, see https://github.com/magento/magento2/issues/3941#issuecomment-218518451 for more details.

`isModified` shall not take extension attributes into account, you can customize `\Magento\Framework\Model\ResourceModel\Db\VersionControl\Metadata::getFields` if you need another logic.

> have to add a plugin for the `save()`-method of the repository

This is the recommended approach.
