### ISSUE TITLE
Currency Price filter is only using the base currency

### ISSUE THREAD

**Issue by teodoriu** [magento/magento2#11810]
### Preconditions

1. Magento 2.1.8
2. Apache 2.4
3. PHP 7.0.24
4. MySQL 5.7

### Steps to reproduce

1. Set base currency to RON
2. Set additional allowed currency: USD, EUR
3. Set product price in RON
4. Go to category, switch to USD currency and filter by price. 

### Expected result

1.  Products should be filtered by USD price

### Actual result

1. Products are filtered by RON price not by USD price 
![](https://i.imgur.com/mwKPbtS.png)

**Comment by magento-engcom-team** [comment]
@BTeodorWork, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by teodoriu** [comment]
Thanks.

Can you point me to the commit that fixed this?

**Comment by robinj** [comment]
@magento-engcom-team are you able to point out the commit? I am an EE user also experiencing this problem and would like to patch it

**Comment by teodoriu** [comment]
I updated to 2.2.1 and i have the same issue @magento-engcom-team
