### ISSUE TITLE
Backend product grid filter qty 0

### ISSUE THREAD

**Issue by rikwillems** [magento/magento2#11814]
I want to filter my products in the backend to show all products that have a quantity of 0.

### Steps to reproduce
Have a product with qty = 0
Set filter Quantity from: 0
Set filter Quantity to: 0

### Expected result
Filtered product to show the product with qty = 0

### Actual result
All products are shown.

**Comment by magento-engcom-team** [comment]
@rikwillems, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
