### ISSUE TITLE
Can we not remove prototype javascripts?

### ISSUE THREAD

**Issue by bhargavmehta** [magento/magento2#1181]
Hi,
I have a question . We are using prototype.js since magento's first build.
Now jquery is in stable state.
Can we not just remove prototype.js as it creates conflict many times with jquery.

**Comment by orlangur** [comment]
jQuery plays just fine with PrototypeJS using [jQuery.noConflict()](https://api.jquery.com/jquery.noconflict/).

PrototypeJS can be removed as soon as there will be no logic which rely on PrototypeJS. It's already true for storefront and there is no PrototypeJS there, but there are some places in admin area which require PrototypeJS yet.

**Comment by bhargavmehta** [comment]
So can we just simply use jQuery with $ in the front end?

**Comment by vpelipenko** [comment]
@bhargavmehta, yes, you can use jQuery for frontend now. Do you have another questions?

**Comment by villageseo** [comment]
Hi bhargavmehta,

Yes, jQuery works with $ through require.js structure like this: 
```
<script>
	require([
			"jquery"
		], function($) {
			var someVar = $('.someSelector'); // works fine
		});
</script>
```

**Comment by orlangur** [comment]
> So can we just simply use jQuery with $ in the front end?

No JavaScript code must be written in global scope. And for any JavaScript code wrapped with a closure external dependencies must be explicitly defined: https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/web/js/compare.js#L11

So both
```
<script>
    $('.someSelector').someMethodCall();
</script>
```

and
```
<script>
    jQuery('.someSelector').someMethodCall();
</script>
```

are not acceptable.

And for properly placed JavaScript code any name for `jQuery` variable could be used as shown by @villageseo.
