### ISSUE TITLE
Invoice aroundsave() plugin not working

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#11815]
I'm trying to adjust the way how an invoice is saved. Since its a good practice to use plugins this is the way how i want to do this.

### Preconditions
1.  Magento 2.2.0
2.  PHP 7.1.8

### Steps to reproduce
1.  Create module
2. Create etc/di.xml
```
 <?xml version="1.0"?>
<type name="Magento\Sales\Api\InvoiceRepositoryInterface">
        <plugin name="invoice_aroundsave" type="Vendor\Module\Plugin\InvoicePlugin" sortOrder="10"/>
    </type>
```
</config>

3.  Create Plugin/InvoicePlugin.php

```
namespace Vendor\Module\Plugin;
use Magento\Sales\Model;
class InvoicePlugin
{
    public function aroundsave(\Magento\Sales\Api\Data\InvoiceRepositoryInterface $subject, callable $proceed, Model\Order\Invoice $invoice)
    {

//Do stuff....

        $returnValue = $proceed($invoice);

        return $returnValue;
}

```
### Expected result
1.  Just do stuff

### Actual result
This is not doing anything. Its not even executing. I tried to put a var_dump in it to see if that gets triggered but just nothing. I did exactly the same with an Order and that works just fine. 

Not sure if i do something wrong. In that case my apologies for reporting this as a bug. But since Magento is so pinned to always use the same 'ways' to do things. This should not be an exception and you should be doing it the same way.

**Comment by orlangur** [comment]
Well, you cannot create plugin without debugging which methods of which classes are actually used in needed scenario.

Is `InvoiceRepository` involved in scenario you trying to customize? You can check it by putting `var_dump + die` into `save` method.

**Comment by versdivers** [comment]
Well the scenario is that Magento creates an invoice. Thats it. 
Every time that Magento generates an invoice no matter how. 

I did the following in the InvoiceRepository :
```
    public function save(\Magento\Sales\Api\Data\InvoiceInterface $entity)
    {
        var_dump('test');
        die('test');
        $this->metadata->getMapper()->save($entity);
        $this->registry[$entity->getEntityId()] = $entity;
        return $this->registry[$entity->getEntityId()];
    }
```

But this is not used for some weird reason. So when i create an order the OrderRepository is used. But when i create an Invoice the InvoiceRepository is not used? When does it get used? What does it used then? How can Magento Force so much structure and rules onto developers but not following its own logics (i like the structure and rules btw.). 

I mean if anyone can explain me what is used when an order is being saved but not the InvoiceRepository->save() that would be awesome. 

But when you set up a giant structure and you do not follow your own rules then this costs a lot of time and headaches for developers. You think you are doing something like you should to come to the conclusion that it one of the many exceptions and then you are stuck in a search party throughout Magento files trying to understand what is going on. 

My apologies for my rant. Its just frustrating. 

Anyone any idea which save to use? If i follow the button it should end up here but it appearently doesnt.

**Comment by versdivers** [comment]
After some more digging in Magento\Sales\Api\InvoiceRepositoryInterface if i change
`    public function save(\Magento\Sales\Api\Data\InvoiceInterface $entity);
`to
`    public function save();
`
then it gives an error on creating the invoice (not saving it)
`Fatal error: Declaration of Magento\Sales\Model\Order\InvoiceRepository::save(Magento\Sales\Api\Data\InvoiceInterface $entity) must be compatible with Magento\Sales\Api\InvoiceRepositoryInterface::save() in www/vendor/magento/module-sales/Model/Order/InvoiceRepository.php on line 18`

The error is normal BUT it does mean that this is used?

**Comment by orlangur** [comment]
> Well the scenario is that Magento creates an invoice

I meant execution flow from code perspective. Just set a breakpoint in needed controller and try step-by-step debugging with xdebug.

**Comment by versdivers** [comment]
I have been through the Controller of Magento/Controller/Adminhtml/Order/Invoice/Save

Is it possible that it doesn't invoke a save?

It does use 
`$invoice->register();
`
And the only thing it saves is

```
            $transactionSave = $this->_objectManager->create(
                \Magento\Framework\DB\Transaction::class
            )->addObject(
                $invoice
            )->addObject(
                $invoice->getOrder()
            );
            $shipment = false;
            if (!empty($data['do_shipment']) || (int)$invoice->getOrder()->getForcedShipmentWithInvoice()) {
                $shipment = $this->_prepareShipment($invoice);
                if ($shipment) {
                    $transactionSave->addObject($shipment);
                }
            }
            $transactionSave->save();
```



The only thing that i see is that it registers the invoice and invokes the event 
```
        $this->_eventManager->dispatch(
            'sales_order_invoice_register',
            [$this->_eventObject => $this, 'order' => $order]
        );
```

**Comment by orlangur** [comment]
I believe after multiple `addObject` they are saved in `$transactionSave->save();`. During debug try tracing into that method.

**Comment by versdivers** [comment]
@orlangur Well indeed this is the flow. But after a closer look Shipments use exactly the same way.
I'm wondering how i can determine that its in fact an invocie.

This whole process seems a bit odd.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by versdivers** [comment]
How is this a stack exchange problem? Nobody is going to know the answer to a subject that seems to be unresolvable. 

Everyone uses observers to have some custom code in the invoice but this should be possible with a plugin. Since the only Save action is within a class that uses Objects and is also used for shipments this seems to be not flexible at all. Invoices are an important part within Magento and even you don't have a descend solution for this.

So this is more of a problem then a question.

**Comment by orlangur** [comment]
This is purely customization problem. You can see that invoice is successfully updated with core logic and you need to find out using which invoice methods it is achieved.

When you find an appropriate method, you can easily implement a plugin for it.

**Comment by versdivers** [comment]
The function that you want to use here is the $invoice->register() for anyone who wants to know in the future.

@orlangur  i highly disagree. The whole Magento enterprise counts on the fact that Magento is used by developers for their customers. As a developer i disagree with the fact that an invoice is not saved but registered and afterwards saved within an object as this causes confusion and non flexibility issues.

I know how i can find where eventually this is triggered and make a plugin for that. But that is not my point. My point is how hard it is to find something in Magento that doesn't follow a certain structure as all the other items within that structure. Orders and Invoice should have the same structure in order to easily adjust them.

If we don't give this as feedback then they are not improving such things.

You Question label is just ignorant and i suggest your remove this as this is a request to change the workflow of an invoice/shipment to match the workflow of an order.

There is 100000+ ways to accomplish a goal within PHP but from the moment that you start forcing OOP then you should have those same rules applied to your own code.

**Comment by orlangur** [comment]
> invoice is not saved but registered and afterwards saved within an object as this causes confusion and non flexibility issues.

It is implemented this way to save multiple entities in one transaction, isn't it?

> this is a request to change the workflow

Your initial request was "how to perform a particular customization?", such request is still not a bug report but a feature request.

GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.
