### ISSUE TITLE
2.1.9 Item not added to the Wishlist if the user is not logged at the moment he click on the button to add it.

### ISSUE THREAD

**Issue by carloricci84** [magento/magento2#11825]
### Preconditions

1. Magento 2.1.9 installed

### Steps to reproduce

1. Create an user account.
2. Logout from the user account
3. Add a product to your Wishlist , you will get redirected to the login page
4. Login

### Expected result

1. You are redirected to the customer account Wishlist page and the product is added.

### Actual result

1. You are redirected to the customer account Wishlist page but the product **is not** added.

Looking at the bug fix "APPSEC-1755: Anti-CSRF form_key is not changed after login" here https://magento.com/security/patches/magento-2016-and-219-security-update , it seems that since the form key is now changed after the login, the form key used for the Wishlist in vendor/magento/module-wishlist/Controller/Index/Add.php does not validate at the beginning of the execute function.

```
public function execute()
{
    /** @var \Magento\Framework\Controller\Result\Redirect $resultRedirect */
    $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
    if (!$this->formKeyValidator->validate($this->getRequest())) {
        return $resultRedirect->setPath('*/');
    }
```

**Comment by magento-engcom-team** [comment]
@carloricci84, thank you for your report.
We've created internal ticket(s) MAGETWO-82985 to track progress on the issue.

**Comment by osrecio** [comment]
I am working on it at #mm17es

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.1-develop, 2.2-develop and 2.3-develop branches. Will be available with upcoming patch release

**Comment by thaddeusmt** [comment]
Are we sure this is fixed in 2.2.2? I am seeing this exact same bug. If you go through the login form, the form_key changes and when `module-wishlist/Controller/Index/Add.php::execute()` runs it fails at the `$this->formKeyValidator->validate($this->getRequest())` line, just as described.

**Comment by osrecio** [comment]
Hi @thaddeusmt I tested with branch `2.2-develop` with sample data and works fine. 

This issue will be added to `2.2.4`

**Comment by lalit-algoworks** [comment]
I am facing issue with magento 2.2.2 wishlist. Item are not added in wishlist if user logged out.
Here are the steps with sample data
Steps to reproduce.
1. Click on item when user is not logged in
![image](https://user-images.githubusercontent.com/4578739/34522326-164846aa-f0b8-11e7-8e80-ac1882fa79c5.png)
2. It redirect to login screen.
![image](https://user-images.githubusercontent.com/4578739/34522351-37c8eadc-f0b8-11e7-8cf8-b21a69e5e3d3.png)
3. After login it shows.
![image](https://user-images.githubusercontent.com/4578739/34522374-4be9338c-f0b8-11e7-8dbb-189725face86.png)

There is one more issue in wishlist.
If user have some item in their wishlist it should highlight on that item page/category page, but it not.
![image](https://user-images.githubusercontent.com/4578739/34522464-bc052a68-f0b8-11e7-8a9c-022411c8a555.png)
![image](https://user-images.githubusercontent.com/4578739/34522473-ca9da096-f0b8-11e7-9341-7284e3aacf6f.png)
![image](https://user-images.githubusercontent.com/4578739/34522481-d4a118ca-f0b8-11e7-888a-13f3bc02f888.png)

Please provide way to solve it.

**Comment by osrecio** [comment]
Hi @lalit-algoworks this issue will be fixed in `2.2.4 `

**Comment by thaddeusmt** [comment]
Magento support gave us a patch for 2.2.2, so perhaps it will be fixed in 2.2.3+

**Comment by sivajik34** [comment]
can you share me the patch

**Comment by thaddeusmt** [comment]
[magento_2.2.2_add-to-wishlist-login-register_patch.txt](https://github.com/magento/magento2/files/1617535/magento_2.2.2_add-to-wishlist-login-register_patch.txt)

**Comment by matheus0608** [comment]
not work, add item wishlist magento 2.3 Invalid Form Key,
