### ISSUE TITLE
magento 2 design_config save 404 error: Page not found

### ISSUE THREAD

**Issue by tipstops** [magento/magento2#11826]
I have a magento 2 multi store site. just migrated from M1.
after install theme, i wanted to change from design config. 
when i press save button, it shows a white page with "404 error: Page not found"

**Comment by tipstops** [comment]
i solved it

**Comment by yogeshsyscraft** [comment]
@tipstops  Can you please let me know how you solved it  ? as  i am facing same issue 

Thanks 
Yogesh

**Comment by magento-engcom-team** [comment]
Hi there. For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool.

**Comment by netseth** [comment]
This may be an issue with modsecurity.conf.

it has to do with the info in the theme header/footer input areas - if you have calls to javascript or some other stuff, modsecurity stops the post from getting through - 

change your modsecurity.conf file   From: SecRuleEngine On To: SecRuleEngine Off

**Comment by alirazabhatti** [comment]
> i solved it

please do let me know how you solve this issue ???

**Comment by MakoWish** [comment]
It appears to have been modsecurity for me as well. I disabled it, and I was able to save the page.
