### ISSUE TITLE
Error "attribute type not allowed" after upgrading to 2.2.0

### ISSUE THREAD

**Issue by ghost** [magento/magento2#11839]
Hello guys,

After my upgrade from 2.1.6 to 2.2.0, everything is working just fine in the backend. The problem is in the front end. I encounter the following problem: 

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'type': The attribute 'type' is not allowed.
Line: 768

Element 'block', attribute 'type': The attribute 'type' is not allowed.
Line: 776

Element 'block', attribute 'type': The attribute 'type' is not allowed.
Line: 783

Element 'block', attribute 'type': The attribute 'type' is not allowed.
Line: 816

Element 'block', attribute 'type': The attribute 'type' is not allowed.
Line: 821

Element 'block', attribute 'type': The attribute 'type' is not allowed.
Line: 832

Element 'block', attribute 'type': The attribute 'type' is not allowed.
Line: 837

What may be the cause for this? Tried to disable non-theme modules, changed to production mode with --skip-compilation (because if I try to change in the simple way, it throws me an error ... "non-zero").

**Comment by orlangur** [comment]
Hi @iulianemb, this is correct system behavior, you need to remove or refactor invalid `type` attributes as validator suggests.

Please check https://github.com/magento/magento2/issues/11116#issuecomment-332864555 for more details.

**Comment by ghost** [comment]
I understand. I'm new in Magento. Could give me a link which describes from where should I remove the invalid type attribute or other attributes or from where can I refactor it? 

Should I do it from /vendor/magento/framework/View/Layout/etc/elements.xsd, on line 313 where I have those lines declared in the above post?

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. After you post a question please add link here and I will answer shortly.

**Comment by ghost** [comment]
@orlangur, thanks for your support. I've posted it on Magento Stack Exchange. Here's the link: https://magento.stackexchange.com/questions/199151/magento-2-2-0-upgrade-error-attribute-type-is-not-allowed
