### ISSUE TITLE
Magento 2 "add to cart" not working for configurable for Magento 2.2.0

### ISSUE THREAD

**Issue by spotmarketing** [magento/magento2#11838]
We have several products we just developed into our store.  Configurable products will not allow "add to Cart" to work.  Other products that are not configurable work fine and the add to cart feature works.   

### Preconditions

1.  Magento 2.2.0 
2. 

### Steps to reproduce

1.   when you click on add to cart for products that are configurable the Add to cart will not work and comes up with a "We can't add this item to your shopping cart"
2.  When we click add to cart for non-configurable products it functions normally.
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

HI there,

The issue was not fixed or a solution was not given.

https://dev.spotmarketing.ca/curiosity130/3-month-subscription-ages-3-7.html

Please visit the above link. We are currently developing this site and all products that have a customizable feature added to them will not "add to cart" when you click on the "add to cart" button.

Below is a link to a simple product that does not have a customizable feature, and it functions normally.

https://dev.spotmarketing.ca/curiosity130/dress-up-and-drama.html

Please let me know what else is required for you to find a solution to this. We need to launch in the next couple days and this problem is holding us back.

Thanks for your attention to this.a

**Comment by magento-engcom-team** [comment]
@spotmarketing, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@spotmarketing, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by spotmarketing** [comment]
HI there,

The issue was not fixed or a solution was not given.

https://dev.spotmarketing.ca/curiosity130/3-month-subscription-ages-3-7.html

Please visit the above link.  We are currently developing this site and all products that have a customizable feature added to them will not "add to cart" when you click on the "add to cart" button.

Below is a link to a simple product that does not have a customizable feature, and it functions normally.  

https://dev.spotmarketing.ca/curiosity130/dress-up-and-drama.html

Please let me know what else is required for you to find a solution to this.  We need to launch in the next couple days and this problem is holding us back. 

Thanks for your attention to this.
