### ISSUE TITLE
7.1.10 Issue

### ISSUE THREAD

**Issue by SlavaYurthev** [magento/magento2#11831]
### Preconditions
1. PHP 7.1.10
2. Magento 2.2.0

### Steps to reproduce
1. Run php bin/magento ...any command...

### Actual result
1. Print: Magento supports 7.0.2, 7.0.4, and 7.0.6 or later. Please read http://devdocs.magento.com/guides/v1.0/install-gde/system-requirements.html

**Comment by SlavaYurthev** [comment]
Sorry, found issue.
PHP 5.6.31 (cli)

**Comment by orlangur** [comment]
@SlavaYurthev thanks for sorting this out pretty quickly, there were already similar bug reports when PHP version in CLI and Web differs.
