### ISSUE TITLE
Static content deployment is not working for custom developed theme - Magento 2.2.0

### ISSUE THREAD

**Issue by syedsaleem086** [magento/magento2#11864]
[app.tar.gz](https://github.com/magento/magento2/files/1425772/app.tar.gz)
Static content deploy is not working on staging environment for the custom developed a theme,
theme files not contain any files yet. Registered as a new theme. attached theme files for reference

It is working on windows machine
Windows machine configuration is PHP 7.1

### Preconditions
1. PHP Version 7.0.24
2. OS Linux

### Steps to reproduce

1. Install above shared theme files
2. Run php bin/magento setup:static-content:deploy -f
3. It throws this error (attached)
[error.txt](https://github.com/magento/magento2/files/1425788/error.txt)

### Expected result
completes deployment without error
1. 

### Actual result
Fails deployment
attached screenshot
![2017-10-30_08h01_26](https://user-images.githubusercontent.com/15724424/32152214-9a1347f8-bd48-11e7-94a0-fae5f5639259.png)

**Comment by duongquyet** [comment]
Hi,
You can try to change permission of folder pub to 777.

**Comment by syedsaleem086** [comment]
Hi @duongquyet 
I have given full permission

And tried running this command from root user too

**Comment by duongquyet** [comment]
Hi,
You can try this command line:
chmod -R 777 pub var

**Comment by syedsaleem086** [comment]
Hi @duongquyet 
I have run this command already

**Comment by syedsaleem086** [comment]
Hi @duongquyet 

Tried again but No Luck,
Same issue

**Comment by syedsaleem086** [comment]
Hi @duongquyet 
Attached snapshot for your reference
![2017-10-30_08h55_11](https://user-images.githubusercontent.com/15724424/32153415-6c981d8c-bd50-11e7-8f9e-8d21ce279871.png)

**Comment by syedsaleem086** [comment]
Hi 
Let me know progress on this please @magento-engcom-team

**Comment by magento-engcom-team** [comment]
@syedsaleem086, thank you for your report.
We've created internal ticket(s) MAGETWO-83997 to track progress on the issue.

**Comment by solwininfotech** [comment]
I am working on this at #dmcdindia

**Comment by solwininfotech** [comment]
@syedsaleem086

Hi,

I tried to reproduce the issue in “2.2-develop” with php version 7.0.30.
I have not faced any of issue once run Run php bin/magento setup:static-content:deploy -f 


Thanks,
![screenshot from 2018-05-19 16-05-46](https://user-images.githubusercontent.com/16253886/40267725-7edfa99c-5b7f-11e8-88b4-6d1b7d062c40.png)

**Comment by syedsaleem086** [comment]
Hi @solwininfotech 
Thanks for checking out this. The issue occurs at 97% completion of static-content deploy of the custom theme.

**Comment by magento-engcom-team** [comment]
Hi @syedsaleem086 
Unfortunately we can not provide any assistance with custom themes here. 
Thank you @solwininfotech for verification!

**Comment by vipslucky** [comment]
Hello

I am also facing same issue.
I have upgraded Magento2.1.7 to latest 2.2.6.
there was a custom theme in my site and after upgrade its started giving me error when i try to run static-content-deploy.
Please check attached files.

Thanks
![content_error](https://user-images.githubusercontent.com/45290914/48946712-9ae83280-ef54-11e8-9dac-488aac0ff5e4.png)
[content_error.txt](https://github.com/magento/magento2/files/2610902/content_error.txt)
