### ISSUE TITLE
Improve Errormessage 

### ISSUE THREAD

**Issue by brosenberger** [magento/magento2#11871]
### Preconditions

1. Misconfigured product update within UpgradeData-Script:
{code}
$eavSetup->addAttribute(\Magento\Catalog\Model\Product::ENTITY, 'pim_option_1', [
 ...
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_WEBSITE,
...
            ]);
{code}
2. 

### Steps to reproduce

1. Create a correct product import csv for a configurable product including some references within the configuration_variants column
2. go to admin-backend/system/import
3. choose products to import with above created import file
4. press validate data button

### Expected result

1. validation erros shows up with a more specific message like 'Attribute with code must be global and is not super in row(s)'
2. see https://magento.stackexchange.com/questions/139630/attribute-with-this-code-is-not-super-in-row-magento-2
### Actual result

1. validation error shows up with message: Attribute with this code is not super in row(s)

**Comment by orlangur** [comment]
> must be global and is not super in row(s)

Such message has no sense as every global select is considered to be super by design:
```
// save super attributes for simplier and quicker search in future
        if ('select' == $attrParams['type'] && 1 == $attrParams['is_global']) {
            $this->_superAttributes[$attrParams['code']] = $attrParams;
        }
```

However, check for `is_global` could be implemented as separate with separate error message.

**Comment by magento-engcom-team** [comment]
@brosenberger, thank you for your report.
We've created internal ticket(s) MAGETWO-84059 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#82
