### ISSUE TITLE
MCE 2.1.9 / Paypal Express -> "We can't place the order" with skip review step disabled

### ISSUE THREAD

**Issue by angelo983** [magento/magento2#11877]
### Preconditions

1. Magento 2.1.9
2. Configurable products
3. Skip review step disabled in Paypal Express options
4. Allow Guest payment (Credit card data without Paypal account)

### Steps to reproduce

1. Put a product (configurable product by color and size) in cart
2. Go to checkout and follow all steps
3. Choose Paypal Express as payment method

### Expected result

1. Landing to Paypal payment page

### Actual result

1. Landing to review order page with "We can't place the order" error message

Doing all the same steps, but with Skip review step enabled, it will land to the same review order page but without error message

**Comment by magento-engcom-team** [comment]
@angelo983 We cannot reproduce this issue as described. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by gewaechshaus** [comment]
@magento-engcom-team - this could be the case if the customer clicks directly on the paypal button within a product or the minicart in combination with multiple shipping methods. At this point the shipping fees aren't applied or calculated. If you don't send the shipping methods within the request to the paypal api (and if I remember right that didn't work as expected), the review step won't be skipped as the total needs to be recalculated after the customer did choose a shipping method. 

Greetings
Jan

**Comment by angelo983** [comment]
@gewaechshaus  you are right, if I set Allow Shipping to Multiple Addresses to NO and I set Skip Order Review Step to YES now, choosing Paypal now it lands directly to PayPal gateway page.
Anyway, @magento-engcom-team if review step can't be skipped when shipping to multiple addresses is enabled some options would have been disabled

**Comment by magento-engcom-team** [comment]
@angelo983, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by romeof1980** [comment]
what I see (2.4.7) is that if an error in the paypal gateway occur it will redirect to the order review page giving you the applicable error messages. 
this shouldn't be the case if the order review page is skipped: it should word like any other payment gateway.
it seems a minor case but simply if order review page is disabled is probably not styled because is thought to be "disabled".
If skip == yes paypal should never redirect to that page, not even in case of gateway errors or (more common) if the gateway refuses or block the transaction
