### ISSUE TITLE
Please enter a correct date on German Magento 2.2.0

### ISSUE THREAD

**Issue by alemMantik** [magento/magento2#11873]
When you would add an basketroule you cant there use the Datepicker.
If you do that then the error appears: "Please enter a correct date"

Something with the validation is here wrong.

Start and End-Date the same.
this problem is also be the catalogpriceroules

**Comment by orlangur** [comment]
Hi @alemMantik, thanks for bug report, it is a known issue tracked as https://github.com/magento/magento2/issues/10580.
