### ISSUE TITLE
The ESI blocks from Varnish appear to be filled incorrectly when switching stores using the selector

### ISSUE THREAD

**Issue by andrewhowdencom** [magento/magento2#11874]
#### Preconditions
1. 2.2.0
2. Varnish 5.0; default configuration with minor adjustments. Can paste if required.
3. PHP 7.0

#### Steps to reproduce
1. Create 2 Magento stores on the same URL, using the cookie to deilmit stores
2. Configure Varnish in front of that store, as specified in the documentation
3. Switch from one store to the other
4. Notice ESI blocks appear to be in the wrong language

Honestly, I'm not 100% sure this is a core bug. This is me writing it up early, as well as to dump from my brain to see if it's coheasive.

#### Expected result

1. ESI block comes from the correct store

#### Actual result

2. ESI block comes from the old store

My current thinking is running as follows:

1. Request hits Varnish. It fills it from the default store content, pushing an ESI request back for ESI content. That content is filled by the same scope - all good.
2. User selects a new store. *Key information*: Between 2.1.9 and 2.2, the store change behaviour switched from "post to an endpoint and redirect" to "post same page, and simply return the response". This was done here: https://github.com/magento/magento2/commit/508f1ef93558c40f96cc9524e6a205494f90a7ba.

The problem is, the ESI request is still using the "old" store information -- absent either the cookie (sent as part of the response and not part of the ESI request) or the query param (?__store=bork) the ESI is simply doing a dumb request to it's current context -- the old context. Accordingly, it fills the request with the old content, and the ESI block has the wrong language.

Interestingly, this bug is also in 2.1.9, and can be reproduced by setting the store through the query param (?__store=bork) but not setting a cookie. However, it was hidden in 2.1.9 as the changing of the store happened in two steps:

1. The post + redirect, which *correctly set the cookie*
2. Fulfilling the content request, with the correct cookie.

I'm currently unsure of a solution. Naively, I feel like I could just implement the old redirect URL once again -- but this is kind of a dirty solution.

**Comment by andrewhowdencom** [comment]
Whaat which part of G1 did I fail?

**Comment by andrewhowdencom** [comment]
Doing dirty frontend hacks to change the POST url in the JSON blob in the data attribute to the old `stores/store/switch` URL fixes it. That'll be my solution for now, for others who are interested. I can add a PR for this?

**Comment by andrewhowdencom** [comment]
```
From b5b9389fbb24fee1d894a1d39c47cadc741beeb6 Mon Sep 17 00:00:00 2001
From: Andrew Howden <hello@andrewhowden.com>
Date: Mon, 30 Oct 2017 14:26:10 +0100
Subject: [PATCH] __PROJECT_CODE__-326 __PROJECT_CODE__-361 fix (Magento): Resolve an issue in
 which ESI blocks are incorrect

Broadly, this issue is outlined here:

  https://github.com/magento/magento2/issues/11874

However, this commit will both explain the issue, as well as the design
decision to resolve it.

Currently, there is a bug in Magento when the query parameter is used to
modify the store, rather than setting the cookie, particularly with
Varnish and ESI enabled. The bug is that Varnish does not use the cookie
parameter for setting the store when fulfilling it's ESI requests,
instead deferring to the cookie or, when that's not set, falling back
to the default store.

To understand how this bug happens, we must examine how the request is
processed by the stack. Consider a request for the homepage

GET /?__store=foo_bar

This request follows the following workflow:

1. Get hit by NGINX. Terminate TLS, proxy to Varnish for fulfillment
2. Get processed by Varnish. Varnish matches the request, based on the
   full URL including the query param, and returns the correct, store
   specific response something like:

    HTTP/2 200

    ... (response)
    <esi:include src="/page_cache/esi/foo/bar/baz"/>
    ...

3. Varnish then process that response for ESI content. It then finds the
   ESI tags from above, creating new requests to fulfill them.
4. That new request is dispatched (and perhaps fulfilled) by Varnish -
   but without the query parameter. It is here where the bug happens.

   Varnish uses the query param (?__store) and the store cookie to determine
   the key against which to match the request. In absence of both this
   query param and the cookie, it falls back to the default store --
   populating the ESI block for the store specified in the query
   param mentioned before (__store=foo_bar) with the content from the
   default store.

   This leads to the page including ES content from the wrong store in
   its result.

The fix is to revert the previous behaviour of modifying the store
language via the POST at `/stores/store/switch` instead of the new
behaviour (making a POST request to / and returning the response,
skipping the redirect). This allows the cookie to be set as part of
the response to the POST request, after which it
will be correctly used by Varnish to fulfill its ESI payloads.
---
 app/code/__Project__/Base/Block/Switcher.php | 21 +++++++++++++++++++++
 1 file changed, 21 insertions(+)

diff --git a/app/code/__Project__/Base/Block/Switcher.php b/app/code/__Project__/Base/Block/Switcher.php
index e6b421c..8e1218d 100644
--- a/app/code/__Project__/Base/Block/Switcher.php
+++ b/app/code/__Project__/Base/Block/Switcher.php
@@ -86,4 +86,25 @@ class Switcher extends MagentoSwitcher
         }
         return $this->getData('raw_stores');
     }
+
+    /**
+     * Returns target store post data
+     *
+     * Modified to use the POST endpoint. This resolves issue:
+     *
+     * https://github.com/magento/magento2/issues/11874
+     *
+     * @param \Magento\Store\Model\Store $oStore
+     * @param array                      $aData
+     *
+     * @return string
+     */
+    public function getTargetStorePostData(\Magento\Store\Model\Store $oStore, $aData = [])
+    {
+        $aData[\Magento\Store\Api\StoreResolverInterface::PARAM_NAME] = $oStore->getCode();
+        return $this->_postDataHelper->getPostData(
+            $this->getUrl('stores/store/switch'),
+            $aData
+        );
+    }
 }
-- 
2.15.0.rc1
```

**Comment by andrewhowdencom** [comment]
Also adding the store cookie to the hash because Wednesday at 5pm with prod bugs. 

```
    # Split the cache content based on whether it's a different store, as indicated by the store language cookie
    if (req.http.cookie ~ "store=") {
        hash_data(regsub(req.http.cookie, "^.*?store=([^;]+);*.*$", "\1"));
    }
```

**Comment by magento-engcom-team** [comment]
Hi @andrewhowdencom 
Thanks for reporting this issue. 
Unfortunately, I could not reproduce the issue as you described it.
My steps are:
1. Magento 2.2.1 with Sample data
2. Configure Varnish in front of that store, as specified in the documentation
3. Create Second Store View
4. Edit category names in Top navigation menu for Second Store View (http://prntscr.com/hdqort)
5. Configure ESI: block 'catalog.topnav' already has ttl="3600"

Please provide more information for reproduce the issue without 3rd party modules.

**Comment by andrewhowdencom** [comment]
Hola @magento-engcom-team, 

Are you switching stores with the provided store view selector? The bug only happens on the first page load, after this selector is used. (see the commit notes)

**Comment by magento-engcom-team** [comment]
@andrewhowdencom, thank you for your report.
We've created internal ticket(s) MAGETWO-84394 to track progress on the issue.

**Comment by andrewhowdencom** [comment]
Heyaa, 

Thanks for following it up. Also, Happy thanks giving!

**Comment by magento-engcom-team** [comment]
@andrewhowdencom, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by Eddcapone** [comment]
Hello @andrewhowdencom , we also have this issue in 2.4.4-p12 (commerce). Can you reopen the issue?
