### ISSUE TITLE
Magento 2.1.9 Configurable::getUsedProducts returns a different array after product collections is cached

### ISSUE THREAD

**Issue by apedicdev** [magento/magento2#11880]
### Preconditions

Magento 2.1.9

`\Magento\ConfigurableProduct\Model\Product\Type\Configurable::getUsedProducts` returns a different array after product collection is cached. 

### Steps to reproduce

1. Load a configurable product
2. Observe the returned array `$usedProducts`
3. clean the collections cache (`bin/magento cache:clean collections`)
4. Reload the same configurable product
5. Observer again the returned array `$usedProducts`

### Expected result

1. The array `$usedProducts` should contain the same indexes->values where indexes are the product children ids.

### Actual result

Before cleaning the collections cache, the returned array is a simple array indexes->values where indexes are incremental. 
After cleaning the collections  cache, the returned array is an associative array where the indexes are the product children ids.

**Comment by magento-engcom-team** [comment]
@apedicdev, thank you for your report.
We've created internal ticket(s) MAGETWO-83395 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @apedicdev. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1287 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
