### ISSUE TITLE
"Requested store is not found" exception while deleting store view.

### ISSUE THREAD

**Issue by liangdefeng** [magento/magento2#11895]
When I was trying to delete store view from admin in Maento EE 2.2.0, exception throws.

### Preconditions

1. PHP 7.0.24
2. MySQL 5.7.19
3. Magento Commerce 2.2.0 with Sample Data.

### Steps to reproduce

1. Created website, store and store view as follow.
![image](https://user-images.githubusercontent.com/20069277/32214911-4ea97f6c-be5b-11e7-99ae-d2bc2056e346.png)
2. Open TestView2, delete it.

### Expected result

1. The store view is deleted successfully without any error.

### Actual result

1. Error page.
![image](https://user-images.githubusercontent.com/20069277/32215190-39dcb5e4-be5c-11e7-845e-bc8662b3aadb.png)

Content in 706417965114

{"0":"Requested store is not found","1":"#0 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-store\/Model\/StoreManager.php(167): Magento\\Store\\Model\\StoreRepository->getById('3')\n#1 \/var\/www\/html\/MagentoEE220Luma\/generated\/code\/Magento\/Store\/Model\/StoreManager\/Interceptor.php(76): Magento\\Store\\Model\\StoreManager->getStore('3')\n#2 \/var\/www\/html\/MagentoEE220Luma\/generated\/code\/Magento\/Store\/Model\/StoreManagerInterface\/Proxy.php(119): Magento\\Store\\Model\\StoreManager\\Interceptor->getStore('3')\n#3 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-store\/Model\/Resolver\/Store.php(29): Magento\\Store\\Model\\StoreManagerInterface\\Proxy->getStore('3')\n#4 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Config\/ScopeCodeResolver.php(49): Magento\\Store\\Model\\Resolver\\Store->getScope('3')\n#5 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-config\/App\/Config\/Source\/RuntimeConfigSource.php(86): Magento\\Framework\\App\\Config\\ScopeCodeResolver->resolve('stores', '3')\n#6 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-config\/App\/Config\/Source\/RuntimeConfigSource.php(62): Magento\\Config\\App\\Config\\Source\\RuntimeConfigSource->loadConfig()\n#7 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Config\/ConfigSourceAggregated.php(40): Magento\\Config\\App\\Config\\Source\\RuntimeConfigSource->get('')\n#8 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-config\/App\/Config\/Type\/System\/Reader.php(66): Magento\\Framework\\App\\Config\\ConfigSourceAggregated->get()\n#9 \/var\/www\/html\/MagentoEE220Luma\/generated\/code\/Magento\/Config\/App\/Config\/Type\/System\/Reader\/Proxy.php(95): Magento\\Config\\App\\Config\\Type\\System\\Reader->read()\n#10 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-config\/App\/Config\/Type\/System.php(191): Magento\\Config\\App\\Config\\Type\\System\\Reader\\Proxy->read()\n#11 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-config\/App\/Config\/Type\/System.php(152): Magento\\Config\\App\\Config\\Type\\System->loadDefaultScopeData('default')\n#12 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Config.php(131): Magento\\Config\\App\\Config\\Type\\System->get('default\/web\/sec...')\n#13 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Config.php(80): Magento\\Framework\\App\\Config->get('system', 'default\/web\/sec...')\n#14 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Config.php(93): Magento\\Framework\\App\\Config->getValue('web\/secure\/use_...', 'default', NULL)\n#15 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-backend\/Model\/Url.php(169): Magento\\Framework\\App\\Config->isSetFlag('web\/secure\/use_...')\n#16 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Url.php(479): Magento\\Backend\\Model\\Url->_isSecure()\n#17 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Url.php(753): Magento\\Framework\\Url->getBaseUrl(Array)\n#18 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Url.php(929): Magento\\Framework\\Url->getRouteUrl('adminhtml\/*\/edi...', Array)\n#19 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Url.php(873): Magento\\Framework\\Url->createUrl('adminhtml\/*\/edi...', Array)\n#20 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-backend\/Model\/Url.php(209): Magento\\Framework\\Url->getUrl('adminhtml\/*\/edi...', Array)\n#21 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Controller\/Result\/Redirect.php(91): Magento\\Backend\\Model\\Url->getUrl('adminhtml\/*\/edi...', Array)\n#22 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-backend\/Controller\/Adminhtml\/System\/Store\/DeleteStorePost.php(49): Magento\\Framework\\Controller\\Result\\Redirect->setPath('adminhtml\/*\/edi...', Array)\n#23 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Magento\\Backend\\Controller\\Adminhtml\\System\\Store\\DeleteStorePost->execute()\n#24 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#26 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Backend\\Controller\\Adminhtml\\System\\Store\\DeleteStorePost\\Interceptor->___callParent('dispatch', Array)\n#27 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(143): Magento\\Backend\\Controller\\Adminhtml\\System\\Store\\DeleteStorePost\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#28 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Backend\\Controller\\Adminhtml\\System\\Store\\DeleteStorePost\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#29 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Backend\\Controller\\Adminhtml\\System\\Store\\DeleteStorePost\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#30 \/var\/www\/html\/MagentoEE220Luma\/generated\/code\/Magento\/Backend\/Controller\/Adminhtml\/System\/Store\/DeleteStorePost\/Interceptor.php(26): Magento\\Backend\\Controller\\Adminhtml\\System\\Store\\DeleteStorePost\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#31 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/FrontController.php(55): Magento\\Backend\\Controller\\Adminhtml\\System\\Store\\DeleteStorePost\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#32 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#33 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#34 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#35 \/var\/www\/html\/MagentoEE220Luma\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#36 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#37 \/var\/www\/html\/MagentoEE220Luma\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#38 \/var\/www\/html\/MagentoEE220Luma\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#39 {main}","url":"\/admin\/admin\/system_store\/deleteStorePost\/key\/8bc52544ad2b8ecc81c552103ca04a5ac2147827d642cd74fcf653517b181e84\/","script_name":"\/index.php"}

**Comment by magento-engcom-team** [comment]
@liangdefeng, thank you for your report.
We've created internal ticket(s) MAGETWO-83051 to track progress on the issue.

**Comment by luismiguelyangehuaman** [comment]
I am working on it at #mm17es. :-D

**Comment by luismiguelyangehuaman** [comment]
I can't reproduced it

**Comment by ghost** [comment]
Ran into this issue also on 2.2.1.

**Comment by p-bystritsky** [comment]
Can not reproduce on 2.2-dev.

**Comment by remcovg89** [comment]
I'm experiencing the same issue in magento 2.2.1 after running `php bin/magento sampledata:remove `

**Comment by nelero** [comment]
hi, no news ?
just ran into this issue in 2.2.3.
after adding product attributes, or updating products with store view values

**Comment by siliconrockstar** [comment]
Still running into this on 2.2.5 :/

**Comment by jcconde** [comment]
The issue still on 2.2.5 :(

**Comment by CesarChris710** [comment]
2.2.5 when I create new product or edit it :(

**Comment by engcom-Alfa** [comment]
Hi @liangdefeng. Thank you for reporting.

We are not able to reproduce this issue on the fresh 2.4-develop instance.

**Manual testing scenario:**
1. Created website, store and store view as follow.
![websites](https://user-images.githubusercontent.com/51679138/71472134-925acf00-27da-11ea-8dab-d11dc18a4419.png)
2. Open TestView2, delete it.

**Actual Result:**
The store view is deleted successfully without any error.
![screen](https://user-images.githubusercontent.com/51679138/71472196-ccc46c00-27da-11ea-9364-43456a06711d.png)

**Comment by engcom-Alfa** [comment]
Hi @liangdefeng , I'm closing this PR now due to inactivity.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
