### ISSUE TITLE
No filters in facetedData after Upgrade 2.2

### ISSUE THREAD

**Issue by vonbyte** [magento/magento2#11893]
(vgl.: https://magento.stackexchange.com/questions/198621/no-filters-in-faceteddata-after-upgrade-2-2)
After Upgrade to 2.2 filters in faceted Data on Productcollections don't work anymore.
In Magento 2.1.* everything worked!

### Preconditions

1. Magento 2.2
2. PHP 7.0.24

### Steps to reproduce

1. Adding some filters to a product Collection
2. Get faceted data with filters: 
`$productCollectionWithAppliedFilters = $this->getLayer()->getProductCollection();`
` $data = $productCollectionWithAppliedFilters->getFacetedData($attribute->getAttributeCode());`
3. Var-Dumping the collection itself shows that the filters are actually applied!

### Expected result

1. $data should contain the correct filtered facetedData (as in Magento 2.1.*)

### Actual result

1. $data contains the unfiltered facetedData, getFacetedData ignores the applied filters completely

**Comment by vonbyte** [comment]
Any Updates on this?

**Comment by magento-engcom-team** [comment]
Hi @tazign 
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
