### ISSUE TITLE
password management missing in customer account creation admin side 

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1189]
i cloned repo ver. 0.74.0-beta4.when i trying to create customer from admin side there is no fields for customer password.

**Comment by ilol** [comment]
Hi @sivajik34, how do you think, is it secure to ask new password from admin staff?
Or better generate customer password and send it to customer? Or better to generate link for password reset and send to customer?

**Comment by sivajik34** [comment]
2nd and 3rd options are good.
