### ISSUE TITLE
Catalog product list widget not working with multiple sku

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#11897]
### Preconditions

1. Magento 2.18

### Steps to reproduce

1.  Added new catalog product list widget
2.  added all condition with multiple SKU

### Expected result

1. showing product with selected SKU on the page
![image](https://user-images.githubusercontent.com/2478037/32221595-1e7cde0a-be5c-11e7-9ba4-ab7c4c113841.png)

widget code as 
{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="10" template="product/widget/content/grid.phtml" conditions_encoded="a:2:[i:1;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Combine`;s:10:`aggregator`;s:3:`all`;s:5:`value`;s:1:`1`;s:9:`new_child`;s:0:``;]s:4:`1--1`;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Product`;s:9:`attribute`;s:3:`sku`;s:8:`operator`;s:2:`==`;s:5:`value`;s:16:`RS-1004, GI-1018`;]]"}}
### Actual result

1. it will not showing any product on the page and showing error as "We're sorry, an error has occurred while generating this email."

**Comment by magento-engcom-team** [comment]
@hemendraajmera, thank you for your report.
We've created internal ticket(s) MAGETWO-82816 to track progress on the issue.

**Comment by hemendraajmera** [comment]
Any temporary solution ??

**Comment by lionelalvarez** [comment]
I think the condition you are using is not the correct one, You can try use "is one of", if you want the specific sku to be in the defined list.

**Comment by hemendraajmera** [comment]
I have Already changed conditions to all or is one of, but not get the results

**Comment by jasonujmaalvis** [comment]
Not sure when this error was introduced. It works with multiple SKUs in M2 version 2.2.1 but it doesn't work in version 2.1.9

Would love to see an update on this

**Comment by sickao3** [comment]
Seems that on multiple Sku you should replace the operator `==` with `()` . 
You can find the operators here `Magento\Rule\Model\Condition\Sql\Builder` .
`    protected $_conditionOperatorMap = [
        '=='    => ':field = ?',
        '!='    => ':field <> ?',
        '>='    => ':field >= ?',
        '>'     => ':field > ?',
        '<='    => ':field <= ?',
        '<'     => ':field < ?',
        '{}'    => ':field IN (?)',
        '!{}'   => ':field NOT IN (?)',
        '()'    => ':field IN (?)',
        '!()'   => ':field NOT IN (?)',
    ];`

**Comment by magento-team** [comment]
Hi @hemendraajmera. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1050 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - 8d6234124c08699e1891c121266be61946306a9f
 - d5b596a1c832a7919438b8711a8a048b3a7129da

The fix will be available with the upcoming patch release.

**Comment by arunu** [comment]
The issue exists in Magento 2.3.2

**Comment by ACassiusD** [comment]
@arunu Yep, issue still existing on 2.3.2

**Comment by nikosgram** [comment]
Still exists on 2.3.3.

**Comment by E-Commerce-Team** [comment]
For me it fixed the error in 2.3.5

If you see something like this in your block:
`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`sku`,`operator`:`^[^]`,

Change it to 
`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`sku`,`operator`:`()`,

i hope it help somebody
