### ISSUE TITLE
Authorize.net Magento 2.1.9 An error occurred on the server. Please try to place the order again.

### ISSUE THREAD

**Issue by ttribeiro** [magento/magento2#11906]
After I setup the account and enabled Authorize.net payment method, I then filled out the API Login ID, Transaction Key, and Merchant MD5. I have confirmed with the client and Authorize.net that all of these fields are correct. 

 Regardless of if I'm in Test mode On or Test mode Off, I got the same error (see below):

"An error occurred on the server. Please try to place the order again."

I did however receive the Authorize.net email confirmation. And, I spoke with an Authorize.net Executive, and he confirmed that all orders were going through on his end with the correct signal (ex: credit card denied, credit card approved, etc.) But,  on the Magento end, we were getting the same code error every time. "An error occurred on the server. Please try to place the order again."

The  order is created. The credit card is charged. But, Magento will not finish the order. We do not get a success page. We only get the error listed above.

My debug.log file.

main.DEBUG: array (
  'request' => 
  array (
    'x_version' => '3.1',
    'x_delim_data' => 'FALSE',
    'x_relay_response' => 'TRUE',
    'x_test_request' => 'FALSE',
    'x_login' => '****',
    'x_method' => 'CC',
    'x_relay_url' => 'https://example.com/authorizenet/directpost_payment/response',
    'x_type' => 'AUTH_ONLY',
    'x_fp_sequence' => '156',
    'x_invoice_num' => '000000072',
    'x_amount' => 1.0,
    'x_currency_code' => 'USD',
    'x_tax' => '0.00',
    'x_freight' => '0.00',
    'x_first_name' => 'Costume First Name',
    'x_last_name' => 'Costume Last name ',
    'x_company' => 'Costume Full Name',
    'x_address' => '1234 Street Address',
    'x_city' => 'City',
    'x_state' => 'State',
    'x_zip' => '90708',
    'x_country' => '',
    'x_phone' => '0123456789',
    'x_fax' => '',
    'x_cust_id' => '',
    'x_customer_ip' => '::1',
    'x_customer_tax_id' => '',
    'x_email' => 'oem@oem.com',
    'x_email_customer' => '1',
    'x_merchant_email' => 'tr@oem.com',
    'x_po_num' => '',
    'x_fp_timestamp' => 1509440091,
    'x_fp_hash' => '70b6cb98620b5720867dd6c62d420c6f',
  ),

**Comment by YevSent** [comment]
Hi, @ThiagoR, for sandbox environment the `Test Mode` should be disabled (this test mode might be used only for production credentials). Also, do you use Authorize.net on the local environment? If yes, it will not work, Authorize.net requires "online" environment. If you already use it, please, open browser console log during place order process and provide a response from `transact.dll` request.

**Comment by ttribeiro** [comment]
This is what a got.

<TABLE Width="600"><TR><TD>The reporting of this transaction to the Merchant has timed out. An e-mail has been sent to the merchant informing them of the error. The following is the result of the attempt to charge your credit card. <BR><BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The referrer, relay response or receipt link URL is invalid. <BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<BR></TD></TR></TABLE>

**Comment by YevSent** [comment]
If you provided relay URL as `'x_relay_url' => 'https://example.com/authorizenet/directpost_payment/response',` it won't work.

**Comment by ttribeiro** [comment]
WHen I add the x_relay_url at Authorize.net >> Account >> Response/Receipt URLs >> Default Relay Response URL

I got the error

 `<script>
                    window.location="https://example.com/authorizenet/directpost_payment/redirect/x_invoice_num/000000135/success/0/error_msg/The%20transaction%20was%20declined%20because%20the%20response%20hash%20validation%20failed./controller_action_name/directpost_payment/is_secure/1/";
                </script>`

**Comment by YevSent** [comment]
You should not configure this URL in Authorize.net Account details, this URL will be added by Magento but it based on your application domain. That's why I said your application must use the online environment with the real domain name.

Also, please, check correct URLs for sandbox environment:
Gateway URL: https://test.authorize.net/gateway/transact.dll
Transaction Details URL: https://apitest.authorize.net/xml/v1/request.api

**Comment by magento-engcom-team** [comment]
@joni-jones thank you for support

**Comment by inkobject** [comment]
This is an old post, but I ran into this issue in 2.2.3.

The note above by Joni was one issue i fixed but that was only a part of my problem.

I was pulling my hair out, as I was also seeing the failed transaction appearing normally and successfuly in my authorize.net account waiting for capture or as captured depending on my back-end settings. The front end would throw an error.

Then I found some obscure forum post about Zend Cart mentioning in passing that the MD5 should be less than 20 characters. Mine was around 30. I shortened it to something absurd (like quack but not) and it worked. To be clear, I changed the MD5 to "quack" in both Authorize.net and and my magento install.

Then BOOM! everything worked.

I hope this helps someone.

**Comment by valuead** [comment]
@inkobject   you are one of the craziest mofo I found on this forum. This is exactly what and I and boom! Freaking all my day I was working on this pulling my hair from my ass. 
Thank you man! You are great. May G-d bless you, Sir.
BOOM! Mfaka you! BOOM

**Comment by PawanKumarN** [comment]
@inkobject  Where we need change can you explain little bit more
