### ISSUE TITLE
Inline translation error :: Contact US :: [Warning] Expected to start loader but did not find one in the dom (loader.js, line 210)

### ISSUE THREAD

**Issue by sitiodocanoamarelo** [magento/magento2#11904]
### Preconditions

1. Magento 2.2.0 in developer mode
2. 

### Steps to reproduce

1. Activate inline translation on admin
2. Try to change "Contact US" using inline tool

### Expected result

1. The message "Contact US" should be translated

### Actual result

1. The word "contact" is translated but not the word "US" which throws an error "[Warning] Expected to start loader but did not find one in the dom (loader.js, line 210)" in the console and does nothing.

**Comment by magento-engcom-team** [comment]
@sitiodocanoamarelo, thank you for your report.
We've created internal ticket(s) MAGETWO-83069 to track progress on the issue.

**Comment by victor-martinez87** [comment]
Can you assign this ticket to me please? #mm17es

**Comment by victor-martinez87** [comment]
Tested on Magento 2.2.1 No issue found, it's working as expected. 

<img width="561" alt="screen shot 2017-11-04 at 13 08 09" src="https://user-images.githubusercontent.com/24246899/32405217-67442906-c161-11e7-904c-078b45e65c23.png">
<img width="1151" alt="screen shot 2017-11-04 at 13 08 42" src="https://user-images.githubusercontent.com/24246899/32405218-675dc1a4-c161-11e7-8461-ca19a8f902b4.png">

**Comment by sitiodocanoamarelo** [comment]
Hi, 

I still see the "write us" below the "Contacta con nosotros" are you able to translate it as well ?
So should I upgrade to 2.2.1 and get this fixed ?

Thanks

**Comment by sitiodocanoamarelo** [comment]
Already done it, by cleaning cache several times and insisting on the inline translation.

**Comment by victor-martinez87** [comment]
Yes, you have to clear cache and full_page_cache after done the translations. Anyway I do recommend to use Magento translations in the code instead of inline-translations

<img width="1165" alt="screen shot 2017-11-04 at 16 50 52" src="https://user-images.githubusercontent.com/24246899/32406913-c1acbaba-c180-11e7-9e07-3061e69e2a6b.png">
