### ISSUE TITLE
installation error in  0.74.0-beta4

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1190]
======================================================================
   The application has thrown an exception!
======================================================================
 Zend_Db_Statement_Exception
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gift_message_id' in 'field list', query was: INSERT INTO `sales_order` (`state`, `status`, `coupon_code`, `protect_code`, `shipping_description`, `is_virtual`, `store_id`, `customer_id`, `base_discount_amount`, `base_discount_canceled`, `base_discount_invoiced`, `base_discount_refunded`, `base_grand_total`, `base_shipping_amount`, `base_shipping_canceled`, `base_shipping_invoiced`, `base_shipping_refunded`, `base_shipping_tax_amount`, `base_shipping_tax_refunded`, `base_subtotal`, `base_subtotal_canceled`, `base_subtotal_invoiced`, `base_subtotal_refunded`, `base_tax_amount`, `base_tax_canceled`, `base_tax_invoiced`, `base_tax_refunded`, `base_to_global_rate`, `base_to_order_rate`, `base_total_canceled`, `base_total_invoiced`, `base_total_invoiced_cost`, `base_total_offline_refunded`, `base_total_online_refunded`, `base_total_paid`, `base_total_qty_ordered`, `base_total_refunded`, `discount_amount`, `discount_canceled`, `discount_invoiced`, `discount_refunded`, `grand_total`, `shipping_amount`, `shipping_canceled`, `shipping_invoiced`, `shipping_refunded`, `shipping_tax_amount`, `shipping_tax_refunded`, `store_to_base_rate`, `store_to_order_rate`, `subtotal`, `subtotal_canceled`, `subtotal_invoiced`, `subtotal_refunded`, `tax_amount`, `tax_canceled`, `tax_invoiced`, `tax_refunded`, `total_canceled`, `total_invoiced`, `total_offline_refunded`, `total_online_refunded`, `total_paid`, `total_qty_ordered`, `total_refunded`, `can_ship_partially`, `can_ship_partially_item`, `customer_is_guest`, `customer_note_notify`, `billing_address_id`, `customer_group_id`, `edit_increment`, `email_sent`, `forced_shipment_with_invoice`, `payment_auth_expiration`, `quote_address_id`, `quote_id`, `shipping_address_id`, `adjustment_negative`, `adjustment_positive`, `base_adjustment_negative`, `base_adjustment_positive`, `base_shipping_discount_amount`, `base_subtotal_incl_tax`, `base_total_due`, `payment_authorization_amount`, `shipping_discount_amount`, `subtotal_incl_tax`, `total_due`, `weight`, `customer_dob`, `increment_id`, `applied_rule_ids`, `base_currency_code`, `customer_email`, `customer_firstname`, `customer_lastname`, `customer_middlename`, `customer_prefix`, `customer_suffix`, `customer_taxvat`, `discount_description`, `ext_customer_id`, `ext_order_id`, `global_currency_code`, `hold_before_state`, `hold_before_status`, `order_currency_code`, `original_increment_id`, `relation_child_id`, `relation_child_real_id`, `relation_parent_id`, `relation_parent_real_id`, `remote_ip`, `shipping_method`, `store_currency_code`, `store_name`, `x_forwarded_for`, `customer_note`, `updated_at`, `total_item_count`, `customer_gender`, `hidden_tax_amount`, `base_hidden_tax_amount`, `shipping_hidden_tax_amount`, `base_shipping_hidden_tax_amnt`, `hidden_tax_invoiced`, `base_hidden_tax_invoiced`, `hidden_tax_refunded`, `base_hidden_tax_refunded`, `shipping_incl_tax`, `base_shipping_incl_tax`, `gift_message_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
----------------------------------------------------------------------
/var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
#0 /var/www/html/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `sa...', Array)
#4 /var/www/html/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(427): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `sa...', Array)
#5 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `sa...', Array)
#6 /var/www/html/magento2/app/code/Magento/Sales/Model/Resource/EntityAbstract.php(237): Zend_Db_Adapter_Abstract->insert('sales_order', Array)
#7 /var/www/html/magento2/var/generation/Magento/Sales/Model/Resource/Order/Interceptor.php(148): Magento\Sales\Model\Resource\EntityAbstract->save(Object(Magento\Sales\Model\Order))
#8 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/OrderInterfacePersistor.php(146): Magento\Sales\Model\Resource\Order\Interceptor->save(Object(Magento\Sales\Model\Order))
#9 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/OrderInterfacePersistor.php(180): Magento\Sales\Api\Data\OrderInterfacePersistor->doPersist(1)
#10 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository.php(162): Magento\Sales\Api\Data\OrderInterfacePersistor->doPersistEntity(Object(Magento\Sales\Model\Order))
#11 [internal function]: Magento\Sales\Api\Data\Order\Repository->save(Object(Magento\Sales\Model\Order))
#12 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(56): call_user_func_array(Array, Array)
#13 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(65): Magento\Sales\Api\Data\Order\Repository\Interceptor->___callParent('save', Array)
#14 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(95): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Sales\A...', 'save', Object(Magento\Sales\Api\Data\Order\Repository\Interceptor), Array, 'save_gift_messa...')
#15 /var/www/html/magento2/app/code/Magento/GiftMessage/Model/Plugin/OrderSave.php(49): Magento\Sales\Api\Data\Order\Repository\Interceptor->Magento\Sales\Api\Data\Order\Repository\{closure}(Object(Magento\Sales\Model\Order))
#16 [internal function]: Magento\GiftMessage\Model\Plugin\OrderSave->aroundSave(Object(Magento\Sales\Api\Data\Order\Repository\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order))
#17 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(100): call_user_func_array(Array, Array)
#18 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(228): Magento\Sales\Api\Data\Order\Repository\Interceptor->___callPlugins('save', Array, Array)
#19 /var/www/html/magento2/app/code/Magento/Sales/Model/Service/OrderService.php(160): Magento\Sales\Api\Data\Order\Repository\Interceptor->save(Object(Magento\Sales\Model\Order))
#20 /var/www/html/magento2/app/code/Magento/Quote/Model/QuoteManagement.php(376): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order))
#21 /var/www/html/magento2/app/code/Magento/Quote/Model/QuoteManagement.php(280): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#22 /var/www/html/magento2/var/generation/Magento/Quote/Model/QuoteManagement/Interceptor.php(174): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote), Array)
#23 /var/www/html/magento2/app/code/Magento/Sales/Model/AdminOrder/Create.php(1855): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote), Array)
#24 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Module/Sales/Setup/Order/Processor.php(136): Magento\Sales\Model\AdminOrder\Create->createOrder()
#25 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Module/Sales/Setup/Order.php(77): Magento\Tools\SampleData\Module\Sales\Setup\Order\Processor->createOrder(Array)
#26 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Helper/PostInstaller.php(86): Magento\Tools\SampleData\Module\Sales\Setup\Order->run()
#27 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(89): Magento\Tools\SampleData\Helper\PostInstaller->run()
#28 /var/www/html/magento2/setup/src/Magento/Setup/Model/SampleData.php(76): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#29 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(1161): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\ConsoleLogger), 'admin')
#30 [internal function]: Magento\Setup\Model\Installer->installSampleData(Object(Zend\Stdlib\Parameters))
#31 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(293): call_user_func_array(Array, Array)
#32 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(360): Magento\Setup\Model\Installer->install(Object(Zend\Stdlib\Parameters))
#33 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\ConsoleController->installAction()
#34 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(344): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#35 [internal function]: Magento\Setup\Controller\ConsoleController->onDispatch(Object(Zend\Mvc\MvcEvent))
#36 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#37 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#38 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#39 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#40 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#41 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#42 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#43 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#44 /var/www/html/magento2/setup/index.php(25): Zend\Mvc\Application->run()
#45 {main}
======================================================================
   Previous Exception(s):
======================================================================
 PDOException
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gift_message_id' in 'field list'
----------------------------------------------------------------------
/var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
#0 /var/www/html/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `sa...', Array)
#4 /var/www/html/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(427): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `sa...', Array)
#5 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `sa...', Array)
#6 /var/www/html/magento2/app/code/Magento/Sales/Model/Resource/EntityAbstract.php(237): Zend_Db_Adapter_Abstract->insert('sales_order', Array)
#7 /var/www/html/magento2/var/generation/Magento/Sales/Model/Resource/Order/Interceptor.php(148): Magento\Sales\Model\Resource\EntityAbstract->save(Object(Magento\Sales\Model\Order))
#8 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/OrderInterfacePersistor.php(146): Magento\Sales\Model\Resource\Order\Interceptor->save(Object(Magento\Sales\Model\Order))
#9 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/OrderInterfacePersistor.php(180): Magento\Sales\Api\Data\OrderInterfacePersistor->doPersist(1)
#10 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository.php(162): Magento\Sales\Api\Data\OrderInterfacePersistor->doPersistEntity(Object(Magento\Sales\Model\Order))
#11 [internal function]: Magento\Sales\Api\Data\Order\Repository->save(Object(Magento\Sales\Model\Order))
#12 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(56): call_user_func_array(Array, Array)
#13 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(65): Magento\Sales\Api\Data\Order\Repository\Interceptor->___callParent('save', Array)
#14 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(95): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Sales\A...', 'save', Object(Magento\Sales\Api\Data\Order\Repository\Interceptor), Array, 'save_gift_messa...')
#15 /var/www/html/magento2/app/code/Magento/GiftMessage/Model/Plugin/OrderSave.php(49): Magento\Sales\Api\Data\Order\Repository\Interceptor->Magento\Sales\Api\Data\Order\Repository\{closure}(Object(Magento\Sales\Model\Order))
#16 [internal function]: Magento\GiftMessage\Model\Plugin\OrderSave->aroundSave(Object(Magento\Sales\Api\Data\Order\Repository\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order))
#17 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(100): call_user_func_array(Array, Array)
#18 /var/www/html/magento2/var/generation/Magento/Sales/Api/Data/Order/Repository/Interceptor.php(228): Magento\Sales\Api\Data\Order\Repository\Interceptor->___callPlugins('save', Array, Array)
#19 /var/www/html/magento2/app/code/Magento/Sales/Model/Service/OrderService.php(160): Magento\Sales\Api\Data\Order\Repository\Interceptor->save(Object(Magento\Sales\Model\Order))
#20 /var/www/html/magento2/app/code/Magento/Quote/Model/QuoteManagement.php(376): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order))
#21 /var/www/html/magento2/app/code/Magento/Quote/Model/QuoteManagement.php(280): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#22 /var/www/html/magento2/var/generation/Magento/Quote/Model/QuoteManagement/Interceptor.php(174): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote), Array)
#23 /var/www/html/magento2/app/code/Magento/Sales/Model/AdminOrder/Create.php(1855): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote), Array)
#24 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Module/Sales/Setup/Order/Processor.php(136): Magento\Sales\Model\AdminOrder\Create->createOrder()
#25 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Module/Sales/Setup/Order.php(77): Magento\Tools\SampleData\Module\Sales\Setup\Order\Processor->createOrder(Array)
#26 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Helper/PostInstaller.php(86): Magento\Tools\SampleData\Module\Sales\Setup\Order->run()
#27 /var/www/html/magento2/dev/tools/Magento/Tools/SampleData/Installer.php(89): Magento\Tools\SampleData\Helper\PostInstaller->run()
#28 /var/www/html/magento2/setup/src/Magento/Setup/Model/SampleData.php(76): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#29 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(1161): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\ConsoleLogger), 'admin')
#30 [internal function]: Magento\Setup\Model\Installer->installSampleData(Object(Zend\Stdlib\Parameters))
#31 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(293): call_user_func_array(Array, Array)
#32 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(360): Magento\Setup\Model\Installer->install(Object(Zend\Stdlib\Parameters))
#33 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\ConsoleController->installAction()
#34 /var/www/html/magento2/setup/src/Magento/Setup/Controller/ConsoleController.php(344): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#35 [internal function]: Magento\Setup\Controller\ConsoleController->onDispatch(Object(Zend\Mvc\MvcEvent))
#36 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#37 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#38 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#39 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#40 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#41 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#42 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#43 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#44 /var/www/html/magento2/setup/index.php(25): Zend\Mvc\Application->run()
#45 {main}

**Comment by mazhalai** [comment]
@sivajik34 can you please clear `cache` and `generation` folder within `var` and try again?

**Comment by sivajik34** [comment]
ya it is solved. thanks

**Comment by sidolov** [comment]
Hi @sivajik34. Thank you for your report. 
The issue has been fixed in magento/magento2#16153 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [2b8b9d57bc556639614dc27d8346b7743ab34dd1](https://github.com/magento/magento2/commit/2b8b9d57bc556639614dc27d8346b7743ab34dd1)

The fix will be available with the upcoming 2.3.0 release.
