### ISSUE TITLE
Meta title of CMS page is removed with content block

### ISSUE THREAD

**Issue by Triloworld** [magento/magento2#11907]
Right now developer can break site accidentally because body block is used to populate site header and other regions of cms page. This mix of context isn't need when there is **<head>** where can be properly init that part of site.

Preconditions
1. Magento 2.2
2. Working site
3. Homepage is set to CMS Page and have set page title "TEST"
4. Meta title of the page is visible in source code

### Steps to reproduce
1. Comment line 11:
> <block class="Magento\Cms\Block\Page" name="cms_page"/>
in file: 
> /vendor/magento/module-cms/view/frontend/layout/cms_page_view.xml
2. Refresh site.

### Expected result
1. Meta title stay the same. No change on `<head>` element even without any block element.

### Actual result
1. Meta title is empty

### More problems
1. Breadcrumbs dissapear because no crumbs

Solution partial:

File 
> /vendor/magento/module-cms/Block/Page.php

is executed with this block. Add second block to head with other name and same init class to run _renderLayout and logic behind it.  It's easy task and give separation of context. After added to cache, no change in perfomance.

Solution best:
Add special blocks to header tag for every handler. This can be used to reduce hit on some elements like _prepareLayout() and ensure that developer won't accidentally remove header part.
Nice way to separate context. In addition this type of block will be less time edited by someone.

**Comment by orlangur** [comment]
You are not supposed to remove this block from layout as all logic related to meta title and breadcrumbs populating is consolidated in it: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Cms/Block/Page.php

> Right now developer can break site accidentally

Any scenario starting like this is not valid. Any change developer make should be tested properly and it is always easy to break everything (like remove `content` container via XML and such).

**Comment by Triloworld** [comment]
Ok. I find how to do that in Magento 2. Adding
> display="false"

will hide content of body and won't remove meta data. 

Docs:
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_ref

Lastly, in other word if there is just one block of corresponding logic then removing it remove all additional information. Maybe there will be more generic way to implement meta data in head than block in xml but now there is nice solution. Thank you @orlangur for help.
