### ISSUE TITLE
Advanced Pricing - Group Price Add All for Groups

### ISSUE THREAD

**Issue by vizjerai** [magento/magento2#1191]
I noticed that there is an option to select a website for the group prices and it would be nice to be able to set a price for all groups. That way we can set a price differently on one site vs another one.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Advanced-Pricing-Group-Price-Add-All-for-Groups/idi-p/45841).
