### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by rpm68** [magento/magento2#11913]
### Preconditions

1. Magento 2.1.9
2. PHP 7
3. SQL - uknown
4. Linux based hosting

### Steps to reproduce

I installed Magento. It was working. Owner of this shop made some changes to Shop - currency and taxes and Magento stopped.

Opening main page of a site leads to this error:

Fatal error: Uncaught Error: Call to a member function getCode() on null in /home/users/OWNERNAME/public_html/magneto/vendor/magento/module-store/App/Action/Plugin/Context.php:98 Stack trace: #0 /home/users/OWNERNAME/public_html/magneto/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #1 /home/users/OWNERNAME/public_html/magneto/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'customer-app-ac...') #2 /home/users/OWNERNAME/public_html/magneto/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http)) #3 /home/users/OWNERNAME/public_html/magneto/ve in /home/users/OWNERNAME/public_html/magneto/vendor/magento/module-store/App/Action/Plugin/Context.php on line 98

### Expected result

Main page should load correctly

### Actual result

As above

**Comment by magento-engcom-team** [comment]
@rpm68 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detail about steps to reproduce. What changes were made?

**Comment by orlangur** [comment]
> aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor)

Looks like you have some incorrect around plugin.

**Comment by rpm68** [comment]
Hi,   I do not know what owner changed in configuration - and there is no chance to get know beacuse she is not IT specialist and do not remember.   After standard installation from hosting creator I added polish language pack from  github.com github.com  via command line mode.   Shop was working - at least main page was opening correctly.    Then Ania (owner) tried to change some settings to polish (tax) and next day in evening shop stopped to work.   She did not install anything - only clicked configuration options in backend.   Rafal 
                
              
               
                 
                  Dnia 1 listopada 2017 08:30 Magento Community Engineering &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   github.com @rpm68  , thank you for your report.  
We were not able to reproduce this issue by following the steps you provided. Please provide more detail about steps to reproduce. What changes were made?

**Comment by magento-engcom-team** [comment]
@rpm68 please provide full link  that you used for polish language pack from  github.com installation. We will try investigate the situation with the pack.

**Comment by rpm68** [comment]
I used this language package:    github.com github.com   I installed package via manual method by copying files to Magento directory and then issuing commands in bash (as described in documentation of package).   Magento answered with information that it did a lot and then brand new  fresh shop was working - empty but working.   R. 
                
              
               
                 
                  Dnia 8 listopada 2017 15:04 Magento Community Engineering &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   github.com @rpm68  please provide full link  that you used for polish language pack from  github.com installation. We will try investigate the situation with the pack.

**Comment by magento-engcom-team** [comment]
@rpm68  Look please at the result of search - [search]( https://github.com/search?utf8=%E2%9C%93&q=polish+pack&type=). There are many polish packs on github.com. Please clarify you comment above.

**Comment by rpm68** [comment]
I put a link to package previously. As I see Github does not like URL in mail response.   Once again:   https :// github.com / SnowdogApps / magento2-pl_pl   Or just plain name - Snowdog version of polish interface.   R.

**Comment by magento-engcom-team** [comment]
@rpm68, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by rpm68** [comment]
I can pack all sources of Magento and dump of db too and put it somewhere on the net. Then you will be able to look inside by yourself.

**Comment by rpm68** [comment]
Does someone look into closed tickets but with responses?

**Comment by DominicWatts** [comment]
I've got this error on a dev box after manually hacking `store_website` db table and setting multiple as `is_default` = 1
