### ISSUE TITLE
Error in monetary value Brazil

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2#1192]
See attache images.

Example value in Brazil = R$ 10.800,55 (monetary value valid)

Accepted only R$ 1080055.00 (monetary value invalid)

Presented in front-end R$1.080.055,00 (monetary value invalid)

![captura de tela de 2015-04-15 20 07 04](https://cloud.githubusercontent.com/assets/2263217/7171183/7d0a984c-e3ab-11e4-9f31-badf352e8a50.png)
![captura de tela de 2015-04-15 20 07 16](https://cloud.githubusercontent.com/assets/2263217/7171184/7d14664c-e3ab-11e4-8fb1-5889a5185178.png)
![captura de tela de 2015-04-15 20 07 43](https://cloud.githubusercontent.com/assets/2263217/7171185/7d14af26-e3ab-11e4-854f-7ae8316fca86.png)

**Comment by choukalos** [comment]
@cerebrumbr why isn't "Presented in front-end R$1.080.055,00 (monetary value invalid)" format valid?  I thought the format was #.###,## ( http://www.thefinancials.com/Default.aspx?SubSectionID=curformat )?  Can you provide more insight?

Thanks,
Chuck

**Comment by cerebrumbr** [comment]
@choukalos 

Hello,

Does not accept the value R$ 10.800,55 in registration of the product.

The value R$ 10.800,55 is converted to R$1.080.055,00

**Comment by choukalos** [comment]
Created Jira issue - MAGETWO-36706 as a bug; could be considered a feature request will wait to see what team determines.

**Comment by okorshenko** [comment]
@cerebrumbr ticket MAGETWO-36706 is closed and delivered to mainline. Please, see https://github.com/magento/magento2/commit/8cb21d61d5ab9aa167b3912f020ea5a78472a59a
Please, let up know if issue is still present.
