### ISSUE TITLE
Physically removing an installed module leads Magento to a broken state

### ISSUE THREAD

**Issue by korostii** [magento/magento2#11927]
### Preconditions
1. Magento 2.1.9 (have)
2. PHP 7.0.18

### Steps to reproduce

1. Place any module (let's call it "Bla_BlaBla", for example) to `app/code` and install it, make sure it's present inside `app/etc/config.php`
2. Physically delete the module folder from `app/code` (this step **must** be executed _before_ step 3)
3. run the `bin/magento module:disable Bla_BlaBla` command

### Expected result

1. Module is disabled successfully or even removed from `config.php` completely.

### Actual result

1. `Unknown module(s): 'Bla_BlaBla'`

### Additional information (use case)
In one of the typical workflows, `config.php` is being added to `.gitignore` and the developers on the team rely on the fact that the module should be enabled if it's present in `app/code` folder.
This workflow makes use of the following piece of undocumented functionality: `setup:upgrade` automatically enables modules which are not present in the `config.php` yet (see #9516 for details on that).

However, if a module then disappears, Magento is in a broken state.
Storefront will show a cryptic `Setup version for module 'Bla_blabla' is not specified` error message because the `etc/module.xml` is absent.
And even though `module:status` will show you this module on the list, running the `bin/magento module:disable Bla_blabla` command will produce an `Unknown module(s): Bla_blabla` error message, forcing you to remove it from `config.php` manually.

**Comment by orlangur** [comment]
http://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-uninstall-mods.html must be used to remove modules. There is no way to obtain essential module metadata when its folder is removed physically thus it is not possible to perform automatic cleanup.

**Comment by korostii** [comment]
Who said anything about uninstalling?
This isn't about rolling back DB or anything like that.

The issue is about temporarily disabling a module.

Consider this: you might have two branches in your VCS only one of which contains this module.
You jump between them but you don't wan't change the DB state.

> There is no way to obtain essential module metadata when its folder is removed physically thus it is not possible to perform automatic cleanup.

What kind of metadata would you need in order to disable (not uninstall) a module, besides the information already present in `config.php` ?
