### ISSUE TITLE
Tax issue in checkout/cart

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#11923]
### Preconditions

1. Magento 2.1.7, PHP 7.0.18, MySQL 5.x
2. Nginx sever

### Steps to reproduce

1. I have tax of 7.25% in California for the postcode 90001 to 96162. 
2. Set Tax calculation on Billing Address from **Store > Configuration > Sales > Tax**
3. Add a taxable product in the cart and go the cart page.
4. Select the California State and postcode is 92705 under **Estimate Shipping and Tax** section.
5. Shipping charge calculation is good, but the Tax is not shown there.

### Expected result

1. Tax is shown for the product under the Estimate Shipping and Tax section.

### Actual result

1. Tax is not shown there in the summary section in cart page.

**Comment by magento-engcom-team** [comment]
@RishabhRkRai, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@RishabhRkRai, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by rishabhrkrai** [comment]
I have Magento 2.1.7
