### ISSUE TITLE
Magento 2 & Apache 2 : Varnish cache not working

### ISSUE THREAD

**Issue by ghost** [magento/magento2#11921]
### Preconditions

1. Magento 2.1.9
2. Ubuntu 16.04
3. Apache 2.4 

### Steps to reproduce

1. Varnish is running
2. Ports in apache is listen 8080
3. Vhost port is 8080
4. The default.vcl is generated by Magento admin

### Expected result

1. Pages cached with Varnish
2. Response headers like : Cache-Control:varnish-v4

### Actual result

1. Cache-Control:max-age=0, must-revalidate, no-cache, no-store

**Comment by magento-engcom-team** [comment]
@agenceoneo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
Please check documentation http://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish.html

**Comment by magento-engcom-team** [comment]
@agenceoneo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
