### ISSUE TITLE
Composer does not load more 6 package

### ISSUE THREAD

**Issue by Torys87** [magento/magento2#11934]
Hello.
I have a problem with composer. Try to install magento 2 (or reinstall). Composer loads only 6 packages and stops every time.
https://content.screencast.com/users/Torys87/folders/Jing/media/33f9f1ae-bb3f-4f09-a9fe-5cd821a14b31/2017-11-01_1526.png

Does not matter downloading or load from cache.
Could anyone help with this problem?

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
