### ISSUE TITLE
Can we add another region column with ISO_3166-2 codes

### ISSUE THREAD

**Issue by joh-klein** [magento/magento2#1193]
The current region codes for Germany seem not to be widely known (a quick Google search didn't reveal a source for them). And some others seem to be impractical but most importantly will probably hinder exchanging addresses with other systems.
I could provide a PR with the current [data for regions from Wikipedia](http://en.wikipedia.org/wiki/ISO_3166-2) for these 13 countries (US, CA, DE, AT, CH, ES, FR, RO, FI, EE, LV, LT, BR). Right now I lean towards adding another column for backwards compatibility.

Quick link to relevant source code:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Directory/Setup/InstallData.php#L300

**Comment by joh-klein** [comment]
So, since I don't know what the label "PROD" stands for (looks like production, but I don't know what that would mean in this context)  … should I do the work, or is it not required?

**Comment by vpelipenko** [comment]
Hi @joh-klein, you can read more about labels here http://devdocs.magento.com/guides/v1.0/contributor-guide/CONTRIBUTING.html#labels. This label means that issue should be reviewed and accepted  by our Product Team.

**Comment by joh-klein** [comment]
Thanks! I just found it myself and deleted my original comment for rtfm reasons :)

**Comment by pboisvert** [comment]
@piotrekkaminski Piotr--would you be the right owner here?

**Comment by piotrekkaminski** [comment]
@pboisvert actually @antboiko as it is i18n issue. I've created internal issue MAGETWO-52665 to track this request.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Can-we-add-another-region-column-with-ISO-3166-2-codes/idi-p/46581).
