### ISSUE TITLE
"Email is not valid hostname.'gmail.com"' 

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [magento/magento2#11945]
### Preconditions

1. Magento version 2.1.7
2. Add a customer with an gmail address ending with .come like xxxxx@gmail.com
(We are making a rest api of our Magento 2 when we enter email id like xxxxx@gmail.com then we are getting that error - )

### Expected result

1. Getting errors - 
"Email is not valid hostname.'gmail.com"' looks liks a DNS hostname but we cannot match the TLD against known list.'gmail"' does not not look like a valid local network name."Email" is not a valid email address.

Is anyone is there how to resolve this ?

### Actual result

1. Customer Add Successfully

**Comment by magento-engcom-team** [comment]
@sumeetmobiwebtech Unfortunately, We could not reproduce the issue as you described it. Please provide data that you enter to the Api request's Body. 
Did you correctly say expected result, and the actual result? We understand correctly your Expected Result user from gmail address should not be created?

**Comment by sumeetmobiwebtech** [comment]
@magento-engcom-team thanks for your reply.We resolve the issue actually email was coming from mobile team with double quotes  and we were trying save email with double quotes that's why we are getting that problem.

Thanks again
