### ISSUE TITLE
Inline translation :: Create new account :: Unable to translate password strength 

### ISSUE THREAD

**Issue by sitiodocanoamarelo** [magento/magento2#11955]
### Preconditions

1. Magento CE 2.2.0
2. 

### Steps to reproduce

1. Backoffice: Activate inline translation
2. Frontoffice: Create a new account
3. Try to translate the password strength comment while inserting a new password.

### Expected result

1. Translate the different strings "no password", "weak", etc.

### Actual result

1. Only translates the "no password" comment, other comments such as "weak" point to the same "no password" translation

I noticed similarities with reported issue #5509 from two years ago but it's closed and I couldn't comment on it.

**Comment by magento-engcom-team** [comment]
@sitiodocanoamarelo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by sitiodocanoamarelo** [comment]
How I can I reopen the issue ?
I just added screenshots, as you can check "weak" or "very strong" both point to "no password" which was already translated...

![captura de ecra 2017-11-4 as 14 28 31](https://user-images.githubusercontent.com/33255208/32406242-cc4343ae-c16c-11e7-9ea0-a96ee20ca616.png)
![captura de ecra 2017-11-4 as 14 28 58](https://user-images.githubusercontent.com/33255208/32406244-d045c4d6-c16c-11e7-99b3-9c013edad504.png)
![captura de ecra 2017-11-4 as 14 29 11](https://user-images.githubusercontent.com/33255208/32406246-d314971e-c16c-11e7-85d4-0664c5b5047a.png)
![captura de ecra 2017-11-4 as 14 29 47](https://user-images.githubusercontent.com/33255208/32406247-d538de42-c16c-11e7-86d9-535014a92eee.png)
![captura de ecra 2017-11-4 as 14 29 57](https://user-images.githubusercontent.com/33255208/32406248-d7540ac6-c16c-11e7-8cca-7d479fbf8a3b.png)
