### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by dasy1234** [magento/magento2#11956]
While adding a new product in the Magento 2.2 single image added with the product details is not reflected in the front end. But if more than one image is uploaded then shows properly without any issue.

### Preconditions

1. Magento version 2.2
2. 

### Steps to reproduce

1. Add product from admin panel
2. Add all required details.
3. Add a single image.

### Expected result

1. Product detail page must show details along with the added image in the front end side.

### Actual result

1. Product detail without the image is reflected.

**Comment by magento-engcom-team** [comment]
@dasy1234, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@dasy1234, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
