### ISSUE TITLE
Password manager prevents to finish the checkout

### ISSUE THREAD

**Issue by michielgerritsen** [magento/magento2#11950]
When you have saved credentials in a password manager, ie Lastpass, then the "order" button does not work due to an error on the shipping step of the checkout.

### Preconditions

1. Magento 2.1.9 or 2.2.0
2. Lastpass Chrome extension installed, and a record for the current website created.

### Steps to reproduce
1. Make sure you have the Lastpass extension for Chrome installed, and a record added for the current website. IE: Add the login for the backend. The username must be an invalid email address.
2. Make sure Lastpass autofills your credentials.
3. Put a product in you basket, and go to the checkout.
4. Notice that the e-mail is autofilled with the username from Lastpass.
5. Fill in the required data.
6. Go to the next step.
7. Select a payment method and click "order".

### Expected result
1. The order is placed.

### Actual result
1. Nothing happens. There is no warning or any other indication that there is something is wrong. There is also no request to the server.
2. When you go back to the shipping address, you see that your email address is reset to the version in Lastpass. This happens the moment you switch from step 1 to step 2.

**Comment by magento-engcom-team** [comment]
@michielgerritsen, thank you for your report.
We've created internal ticket(s) MAGETWO-83248 to track progress on the issue.

**Comment by antbates91** [comment]
I can confirm this is still an issue in 2.2.8.

### Preconditions


1. Magento 2.2.8
2. Lastpass Firefox extension installed, and a record for the current website created.

### Steps to reproduce
1. Turn on extension and add log in for the backend. The username must be an invalid email address for example jh_anthony.
2. Make sure Lastpass autofills your credentials.
3. Put a product in your basket, and go to the checkout.
4. Notice that the e-mail is autofilled with the username from Lastpass.
5. Fill in the required data.
6. Go to the next step.
7. Select a payment method and click "order".

### Expected result
1. The order is placed.

### Actual result
1. Nothing happens. There is no warning or any other indication that there is something is wrong. There is also no request to the server.
2. When you go back to the shipping address, you see that your email address is reset to the version in Lastpass. This happens the moment you switch from step 1 to step 2.

**Comment by krzksz** [comment]
I've checked this issue and I am not able to reproduce it on Magento 2.3.x using the path you've given. The validation for email address is correctly triggered for me when I try to go to the payment step.

**Comment by krzksz** [comment]
Please let me know if you are able to reproduce the issue on 2.3.x so we can reopen it, otherwise it's just closed.

**Comment by siliconalchemy** [comment]
I can confirm this problem is still present in Magento 2.3.3.  @krzksz - the problem is not that the email address validation is faifling or blocking initially, it's that *after* you've gone to the next Review&Payment step, in the background LastPass seems to fill in an admin username into the email field of the Delivery - because the email field name is 'username'.  So now when you click 'Place Order' the email address verification fails.
This is difficult to prevent because LastPass completely ignores the autocomplete=off, but the real failure here is in Magento to not display any warning or error when the verification fails - this is catastrophically bad UX.

**Comment by krzksz** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [Magento instance](https://i-11950-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-11950-2-3-develop.instances.magento-community.engineering/admin](https://i-11950-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
@siliconalchemy I'm sorry but I still can't reproduce it, you need to provide me an exact path you are following. Mine is:

1. I have `admin`/`123123q` credentials added in lastpass for admin.
2. I add the product and go to the checkout.
3. I fill all the data in shipping address form.
4. I click on next button.
5. I keep billing and shipping address the same.
6. After clicking `Place Order` button, it is correctly placed.

Maybe it is a matter of browser?

**Comment by david8305** [comment]
I also have this problem. Magento 2.3.5-p1 and latest version of chrome.
@siliconalchemy's problem description seems to be accurate. When I disable lastpass auto fill the problem does not occur. Lastpass only fills password fields when you click on the extension.
