### ISSUE TITLE
Unable to save custom attribute value in billing and shipping

### ISSUE THREAD

**Issue by Krupaly2k-zz** [magento/magento2#11954]
### Preconditions

1. 2.1.6
2. 

### Steps to reproduce

1. Please send me complete extension if possible as I have tried everything but unable to save values in billing and shipping address. It is not showing custom attribute value in admin order as well 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@Krupaly2k , thank you for your report.
Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
Please, add the following information:
 - [ ] Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by Krupaly2k-zz** [comment]
Hi, 

I am using Magento 2.1.6 
Steps to reproduce: I have created 2 attributes and add fields in quote_address and sales_order_address but at the time of saving data in frontend it is not saving in DB and not reflecting in admin. 

Expected Result: It should save data

Please help me to resolve this issue

**Comment by ishakhsuvarov** [comment]
@Krupaly2k, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
