### ISSUE TITLE
Can't empty cart with minimum order amount enabled

### ISSUE THREAD

**Issue by angelo983** [magento/magento2#11969]
### Preconditions

1.  Magento 2.1.9

### Steps to reproduce

1. Enable Minimum Order Amount in Stores > Configuration > Sales
2. Set Minimum Amount to 0.01
3. Put something in cart and after try to empty cart

### Expected result

1. Cart is emptied

### Actual result

1. Error message "Minimum order amount is 0,01 €"
2. Cart is not emptied

[MinimumOrderAmount.log](https://github.com/magento/magento2/files/1438951/MinimumOrderAmount.log)

**Comment by magento-engcom-team** [comment]
@angelo983, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
