### ISSUE TITLE
Use fsWatch for development environment and updating css/html

### ISSUE THREAD

**Issue by kirmorozov** [magento/magento2#11964]
### Preconditions

1. We have development environment.
2. grunt watch is slow. 

### Steps to reproduce

1. Try using grunt watch ] 
2. you change 1 file  it trigger rebuild of 2-5 files.
3. 

### Expected result

1. It runs fast so I can go to browser and hit reload or css-reload

### Actual result

1. [Screenshot, logs]

**Comment by orlangur** [comment]
PR maybe?)

**Comment by kirmorozov** [comment]
Will add it as soon as I'll have something solid. As of now I have raw bash scripts.

**Comment by magento-engcom-team** [comment]
Hi @kirmorozov. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/16
