### ISSUE TITLE
How to reindex 10M products in Magento 2.2.0

### ISSUE THREAD

**Issue by shyang292** [magento/magento2#11967]
Hi, all. My magento 2 webiste has 10M products now. The indexer seems not working because it doesn't write any date to index table in database. Could anyone know the reason? Thanks a bunch.

Server configuration:
RAM: 120G    HardDisk: 200G
Bitnami Magento 2.2.0, PHP 7.0.18  & MySQL 5.7.18
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. reindexing succeed

### Actual result

1. when you check the indexer status, it always shows "Processing". But when I check the database, I found nothing was written into the index table. It seems the indexer stuck on some point. The memory and harddisk is not used up.

**Comment by kirmorozov** [comment]
Nice database,

I would think of using approach of Lazy Products.
1. Use Elasticsearch to index all the products directly from source.
2. Pull product into Magento database once requested.

This way you will have warm(requested) products in database and dont waste time on indexing.

**Comment by southerncomputer** [comment]
Since elasticsearch is nosql based, store attributes in elasticsearch instead of EAV, extend EAV attribute code to pull data from elasticsearch! Side load all product data into elasticsearch!

**Comment by magento-engcom-team** [comment]
Hi @shyang292 
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
