### ISSUE TITLE
Error installing the Magento software using the command line in windows (v0.74.0-beta3)

### ISSUE THREAD

**Issue by JesusTinoco** [magento/magento2#1196]
I'v received this error installing magento2 by command line in windows: 

[Progress: 181 / 265]
Module 'Magento_Customer':
Installing data.. PHP Fatal error:  Class 'IntlDateFormatter' not found in C:\path\to\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php on line 107

**Comment by vpelipenko** [comment]
@JesusTinoco, you should have PHP intl extension enabled.

**Comment by JesusTinoco** [comment]
Was that, thank you!

**Comment by mbrinton01** [comment]
Thanks @JesusTinoco, closing the issue.
