### ISSUE TITLE
Attribute update for 'tax class' does not apply to every storeview?

### ISSUE THREAD

**Issue by Yasp0** [magento/magento2#11966]
### Preconditions
1. Magento 2.1.9
2. Multiple store views
3. Have a default tax class for products

### Steps to reproduce
1. Go to Products > Catalog
2. Select a couple of products
3. Click on Actions > Update attributes
![image](https://user-images.githubusercontent.com/5689226/32337592-b05c6416-bff2-11e7-9953-c373c54d87dc.png)

4. In the new window scroll down to 'Tax Class', select the tax class and tick the 'Change' checkbox
![image](https://user-images.githubusercontent.com/5689226/32337509-7fec7a0a-bff2-11e7-8b83-52c492330df4.png)

5. Click on Save

### Expected result
1. That the selected and updated products have the same tax class for every store view. 

### Actual result
1. The products have the selected tax class for only one storeview, my default Dutch storeview. The product has no tax class in my other two storeviews (English and German).

My default storeview (Dutch) shows the correct Tax class:

![image](https://user-images.githubusercontent.com/5689226/32337660-ea1e36fc-bff2-11e7-82e4-dbb45ae18d7a.png)

When I filter on storeview English the products have no Tax class:

![image](https://user-images.githubusercontent.com/5689226/32337731-1631dac8-bff3-11e7-96c9-8cf67574cc49.png)

In the Configuration > Sales > Tax menu I have set the Default Tax Class for Product. I thought I could maybe set this per store view but that's not the case. I can only set if for the Default Config.

![image](https://user-images.githubusercontent.com/5689226/32338051-f5c42736-bff3-11e7-9fd5-1e5e9397c295.png)

**Comment by magento-engcom-team** [comment]
@Yasp0 Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by Yasp0** [comment]
I added some screenshots and more info.

**Comment by magento-engcom-team** [comment]
@Yasp0, thank you for your report.
We've created internal ticket(s) MAGETWO-83227 to track progress on the issue.

**Comment by pareshe** [comment]
But Tax Class attribute scope is "Website" and you have 2 store view.

**Comment by Yasp0** [comment]
@pareshe what do you mean? Do you mean in the Configuration menu?

**Comment by Yasp0** [comment]
I just found out that my products on the English storeview in the category show the prices including and excluding tax (like I want to). But on the product detail page it shows the price excluding tax.

**In the backend it says the product has no tax class.**
![image](https://user-images.githubusercontent.com/5689226/32536525-20dfd856-c45f-11e7-9eb7-616ef8bb896d.png)

**The product in the category view shows price incl and excl tax. This matches my settings in the configuration menu.**
![image](https://user-images.githubusercontent.com/5689226/32536590-65b0443e-c45f-11e7-9d3f-934ac7b8bc99.png)

**The product detail page shows the price excl. tax.**
![image](https://user-images.githubusercontent.com/5689226/32536668-a14da07c-c45f-11e7-998f-2484a552ebb4.png)

**The Dutch storeview shows the price incl and excl tax**
![image](https://user-images.githubusercontent.com/5689226/32536777-160a0eb4-c460-11e7-82ba-5ff92d580165.png)

**Comment by elburro1887** [comment]
I have just encountered the same issue. I also have two Store Views.
It seems that on every product, the the "Use Default Value" is disabled, which means that the tax class is set in the Store view, which is probably not a good way to do this?

Anyway, "Use Default Value" should always be enabled, unless explicitly set by the user.

Edit: this might be related to #10424

Edit2: I found a solution: https://github.com/magento/magento2/issues/10424#issuecomment-513176792

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**

1. Multiple store views
2. Have a default tax class for products
![Screenshot from 2019-12-26 12-04-31](https://user-images.githubusercontent.com/51681435/71471573-8f5edf00-27d8-11ea-874b-31fba8f5e0b6.png)

**Steps to reproduce:**

1. Go to Catalog > Products
2. Select a couple of products
3. Click on Actions > Update attributes
4. In the new window scroll down to 'Tax Class', select the tax class and tick the 'Change' checkbox
5. Click on Save
6. Run `bin/magento cron:run` (twice)
7. Refresh the page

**Result**
The selected and updated products have the same tax class for every store view.
![Screenshot from 2019-12-26 12-02-08](https://user-images.githubusercontent.com/51681435/71471426-1a8ba500-27d8-11ea-8115-4b481b44bcca.png)
![Screenshot from 2019-12-26 12-02-25](https://user-images.githubusercontent.com/51681435/71471434-1f505900-27d8-11ea-8a3a-89e78cbe28f5.png)
![Screenshot from 2019-12-26 12-02-36](https://user-images.githubusercontent.com/51681435/71471437-211a1c80-27d8-11ea-962f-d7aa8f92dca2.png)
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
