### ISSUE TITLE
[MAGETWO-2343] Import does not work for product Custom Option with type = File

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11978]
### Preconditions
1. Version 2.0

### Steps to reproduce
1. Open Backend - Manage Products
2. Create new Product with custom option type = File
3. Open Export and make Product export
4. Open created Product and remove File custom option
5. Open Import and make Product import with before exported file

### Actual result
Imported custom option with type = File is not imported

### Expected result
Imported custom option with type = File is imported

**Comment by magento-engcom-team** [comment]
@piotrekkaminski, thank you for your report.
The issue is already fixed in develop branch, 2.2.0
