### ISSUE TITLE
[MAGETWO-1556] Export: Unable to Filter Data by Attribute With Input Type Multiple Select

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11974]
When trying to filter data by attribute with input type = Multiple Select, no data is exported to csv file.

### Preconditions

There is a custom attribute created with input type Multiple Select, 3 options enabled ("Option 1", "Option 2", "Option 3").
There is a customer in the system created with custom attribute value = "Option 1" and "Option 2".
Version 2.0

### Steps to reproduce

1. Go to System-> Import/Export-> Export at backend
2. Select "Customers" entity type
3. Select "Magento 1.7 format"
4. In the grid for attribute from precondition select "Option 1" filter
5. Press "Continue" button

### Expected Result
The file was exported with customer from precondition

### Actual Result
1. File was not exported. 
2. The error message appears "There is no data for export"

### Note
The same situation with "Magento 2.0" Export format for all customer entity types

**Comment by magento-engcom-team** [comment]
@piotrekkaminski , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#33
