### ISSUE TITLE
After Migration from Magento 1.9.3.2 to Magento 2.2.0 Ajax stops working

### ISSUE THREAD

**Issue by KooTjoo** [magento/magento2#11970]
**Preconditions**
PHP 7.0.
CentOS Linux 7.4
Plesk Onyx Server
MySQL Mariadb 10.1 

Magento 2.2.0 Multistore setup

**Steps to Reproduce**
1. Clean Installation of M2.2.0
2. Added 1 product to test things
3. Ajax Cart and other Ajax Features (layered navigation) work as expected.
4. Reinstalled clean installation
5. Used Migration Tool to migrate form 1.9.3.2 to 2.2.0. No errors reported.

**Actual Result**
1. Products, Customers etc show up like they should
2. After migration all Ajax functionality stopped working

**Expected Result**
1. Ajax Cart working together with other Ajax Functionality

**Tried**
1. Reindex, Chache Clean, Comile, Deploy etc.
2. Checked and compared settings of clean installation and migrated site. No issues found

Also tested this on M2.1.9 but same result.

**Comment by magento-engcom-team** [comment]
Hi @KooTjoo 
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.
