### ISSUE TITLE
[MAGETWO-1552] Export: Attribute (Input Type Yes/No) Filter by 'No' Exports All Data

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11973]
If attribute with input type Yes/No filtered by "No", customers having attribute="Yes" are exported to csv file.

### Preconditions

1. There is a custom attribute created with input type Yes/No.
2. There is a customer in the system created with custom attribute value = "Yes".
3. Version 2.0

### Steps to reproduce

1. Go to System-> Import/Export-> Export at backend
2. Select "Customers" entity type
3. Select "Magento 1.7 format"
4. In the grid for attribute from precondition select "No" filter
5. Press "Continue" button

### Expected result

1. Customer from precondition is absent in exported csv file

### Actual result

1. The file was exported with customer from precondition

### Note
The same situation with "Magento 2.0" Export format for all customer entity types

**Comment by magento-engcom-team** [comment]
@piotrekkaminski , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**_The feature is not available for Magento Open Source._**

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#32
