### ISSUE TITLE
[MAGETWO-1543] Export - "Created At" filter works incorrect in the "entity Attributes" grid

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11971]
### Preconditions

1. Version 2.0
2. Several customers created on the current day

### Steps to reproduce

1. Go to System-> Import/Export-> Export at backend
2. Select "Customers" entity type
3. Select "Magento 1.7 format"
4. In the grid for "Created At" attribute select today date in the "From" and "To" filter
5. Press "Continue" button

### Expected result

1. The file was exported with customers from precondition

### Actual result

1. File was not exported. 
2. The error message appears "There is no data for export"

### Note:
The same situation with "Magento 2.0" Export format for all customer entity types
The same situation with "rp_token_created_at" attribute code

### For resolving this bug:
the "Time" should be output in a field with the date
or the possibility to choose the time should be absent in the calendar

**Comment by magento-engcom-team** [comment]
@piotrekkaminski, thank you for your report.
We've created internal ticket(s) MAGETWO-1543 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#31
