### ISSUE TITLE
[MAGETWO-2328] Import with Append Complex Data for product with custom options not transfer values of not default store view

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11976]
### Preconditions

1. Several store view exists in the system
2. The simple product is created with custom option 'Checkbox' and with two rows (Default Values)
for example:

title of rows|price
---|---
title1|10
title2|20

3. Change the title and prices for custom option for not default store view
for example:

title of rows|price
---|---
update_title1|100
update_title2|200
4. Make export for this product in _System-> Import/Export-> Export_
5. Delete the product from the system in _Catalog-> products_

### Steps to reproduce
1. Go to _System-> Import\Export->Import_
2. Select "Products" entity type
3. Select behavior "Append Complex Data"
4. Upload the .csv file from precondition 4
5. Go to _Catalog-> Manage Products_ - the product is appeared after Import
6. Open edit page of this product - in the "Custom Options" tab the option info displayed correctly for "Default Values"
7. Select the store view from precondition 3

### Actual Result
The titles and prices of rows have default values

### Expected Result
The titles and prices of rows have values from precondition 3

**Comment by magento-engcom-team** [comment]
@piotrekkaminski, thank you for your report.
We've created internal ticket(s) MAGETWO-2328 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#29
