### ISSUE TITLE
[MAGETWO-1545] Export: "Associate to Website" Attribute Filter by Admin Not Working Correctly

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11972]
With "Associate to Website" attribute filtered by "Admin", customers associated with another websites are exported to csv file.

### Preconditions

1. There is one customer in the system created from Main Website
2. Version 2.0

### Steps to reproduce

1. Go to System-> Import/Export-> Export at backend
2. Select "Customers" entity type
3. Select "Magento 1.7 format"
4. In the grid for "Associate to Website" attribute select "Admin" filter
5. Press "Continue" button

### Expected result

1. File was not exported. 
2. The error message appears "There is no data for export"

### Actual result

1. The file was exported with customer from precondition

### Note
The same situation with "Magento 2.0" Export format for all customer entity types

**Comment by magento-engcom-team** [comment]
@piotrekkaminski, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
