### ISSUE TITLE
Fields "Welcome Text" and "Copyright" can't be set as empty

### ISSUE THREAD

**Issue by SlavaYurthev** [magento/magento2#11984]
### Preconditions
1.  Magento 2.2.0

### Steps to reproduce
1. Fields for Theme Configuration (admin/theme/design_config/edit) "Welcome Text" and "Copyright" leave empty and save config

### Expected result
1. Fields will be empty

### Actual result
1. Fields are still use default config values "Default welcome msg!" and "Copyright © 2013-2017 Magento, Inc. All rights reserved."

**Comment by magento-engcom-team** [comment]
@SlavaYurthev, thank you for your report.
We've created internal ticket(s) MAGETWO-83225 to track progress on the issue.

**Comment by victor-martinez87** [comment]
Could you please assign this ticket to me? thanks #mmes

**Comment by vrann** [comment]
#mm17es

**Comment by victor-martinez87** [comment]
Tested on Magento 2.2.1 and it's working fine, you can delete it and it's  not showing. Please check the Magento fallback structure, maybe you are changing at "default" level and the "store" level it's overwriting your settings.

**Comment by i4rebecamartinez** [comment]
Could you please assign this ticket to me? thanks.

Even if it is not showing in the front, which is the correct behavior, when you leave the fields empty, and you edit de configuration for the second time, default value is showing in the form, because is retrieving website configuration instead of store configuration.

**Comment by vijay-wagento** [comment]
Not able to reproduce in Magento 2.2, verified at #dmcdindia

**Comment by jignesh-baldha** [comment]
Not able to reproduce issue in Magento 2.2.3 and 2.2.4

**Comment by magento-engcom-team** [comment]
Hi @SlavaYurthev 
We are closing this ticket now as multiple people already commented that it is not reproducible.
Thank you all for collaboration.
