### ISSUE TITLE
Unable to get credit type and expiry date details in payment in order API in Magento 2

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#11986]
### Preconditions

1. Magento v2.1.9

### Steps to reproduce

1. Place an order through Authorize.net payment method.
2. Use REST API to pull the order using : 
GET /V1/orders/{id} 

### Expected result

1. Should get credit card type and expiry date details in payment section in response packet

### Actual result

1. "payment": {
        "account_status": null,
        "additional_information": [
            "Credit Card Direct Post (Authorize.net)",
            "authorize"
        ],
        "amount_authorized": 80,
        "amount_ordered": 80,
        "base_amount_authorized": 80,
        "base_amount_ordered": 80,
        "base_shipping_amount": 10,
        "cc_avs_status": "Y",
        "cc_last4": "0:2:aX616u8qyPvsnOYMFKQuKQ1fDh1nVJRV:iteQ58aImCJw8XIylv1M1bFOZTNRXv7dB3NTg6lqA1s=",
        "entity_id": 16,
        "last_trans_id": "40008090735",
        "method": "authorizenet_directpost",
        "parent_id": 16,
        "shipping_amount": 10,
        "extension_attributes": []
    }

**Comment by magento-engcom-team** [comment]
@routbiplab, thank you for your report.
We've created internal ticket(s) MAGETWO-83316 to track progress on the issue.

**Comment by routbiplab** [comment]
Thank you!

**Comment by routbiplab** [comment]
Hi!

Any update ??

**Comment by routbiplab** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@routbiplab thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by routbiplab** [comment]
Authorize.net doesn't return credit card details(such as credit card type, expiry date etc.) to Magento that is why it doesn't store in database and hence it is not reflecting in API.
