### ISSUE TITLE
[MAGETWO-31739] Grouped product successfully exported without GroupedImportExport Module

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11983]
### Preconditions
Version 2.0

### Steps to reproduce

1.Delete GroopedImportExport Module before installation
2. Setup magento
3. Create several simple product
4. Create Grouped product
5. Go to System->Export
6. Perform Product Export
7. Check CSV file

### Actual result
file contain all product include grouped

### Expected result
grouped product should be absent in csv file

**Comment by magento-engcom-team** [comment]
@piotrekkaminski, thank you for your report.
We've created internal ticket(s) MAGETWO-83230 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#24
