### ISSUE TITLE
[MAGETWO-2575] Import products with "Append Complex Data" behavior works incorrect with empty not required values

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11980]
Import products with "Append Complex Data" behavior works incorrect with empty not required values

### Preconditions
1. The simple product is created with the next custom option:
- input type "Drop-down" _(for example)_, title "drop", is required "Yes", sort order "1"
-- row title "drop_title", price "$5.00", sku "12345", sort order "2"

2. The csv file exists with next data:
- input type "Drop-down", title "drop", is required "Yes", sort order " "
-- row title "drop_title", price " ", sku " ", sort order " "

### Steps to reproduce
1. Go to backend as admin
2. In _System-> Import/Export-> Import_ select "Products" entity type
3. Select "Append Complex Data" behavior
4. Upload the file from precondition 2
5. Press "Check Data" button - file is valid!
6. Press "Import" button - Import successfully done!
7. Go to _Catalog-> Manage Products_
8. Open product from precondition

### Actual Result
The values of _sort order_, _price_ and _sku_ are empty in "Custom Options" tab
- input type "Drop-down", title "drop", is required "Yes", sort order " "
-- row title "drop_title", price " ", sku " ", sort order " "

### Expected Result
All values should be as in precondition 1:
* input type "Drop-down", title "drop", is required "Yes", sort order "1"
** row title "drop_title", price "$5.00", sku "12345", sort order "2"

### Note
For the simple custom options the price was not cleared after import without value for price.
_For example:_ Field, Area, Date, Time, Date & Time

**Comment by koenner01** [comment]
possible duplicates https://github.com/magento/magento2/issues/10006, https://github.com/magento/magento2/issues/7468

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#26
