### ISSUE TITLE
Show 0 price for the out of stock product for configurable product

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#11987]
### Preconditions

1. Magento 2.1.8
2. 

### Steps to reproduce

1. Added configurable product 
2.  single product set out of stock
3. 

### Expected result

1. showing product price 

### Actual result

1. it showing 0 prices for the product and configurable attribute also not showing
![image](https://user-images.githubusercontent.com/2478037/32362413-291e7d20-c08f-11e7-9a4e-2317645244a1.png)

**Comment by magento-engcom-team** [comment]
@hemendraajmera, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
