### ISSUE TITLE
[MAGETWO-2975] Import of products erases product order in category setting

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11981]
Setting product position setting, exporting products, and reimporting products causes product position setting to be erased.

### Preconditions
1. Version 2.0

### STEPS TO REPRODUCE
1) Sign into admin panel
2) Create 4 test products
3) Add them all to test category
4) Go to Category settings and set positions for all 4 products
5) Export file
6) Look over exported CSV file - no column showing for category position
7) Import file - replace data
8) Look at category settings - note product order is erased

### Actual results
Random: 2 of the positions stay but one of them gets changed 
(See attached trunk category position settings after.png and trunk category position settings before.png).
![trunk category position settings before](https://user-images.githubusercontent.com/1714545/32350786-5cbdcbbe-bfe9-11e7-8f4e-c4abbba25726.png)
![trunk category position settings after](https://user-images.githubusercontent.com/1714545/32350793-5ff6f364-bfe9-11e7-84ce-9011078f8aae.png)

### EXPECTED RESULTS: 
Positions for products in categories should be retained from before import to after export.

**Comment by magento-engcom-team** [comment]
@piotrekkaminski, thank you for your report.
We've created internal ticket(s) MAGETWO-83239 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#25
