### ISSUE TITLE
[MAGETWO-3668] Custom options have been imported via mass action without selecting action

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11982]
### Preconditions
Product with some custom options has been created

### Steps to reproduce
1. Log in to backend
2. Go Catalog>Manage Products
3. Start create new product
4. Open Custom options tab
5. Click Import Options button
6. Select Product 1 in opened window with grid
7. Press Submit button without selecting action

### Expected result:
Error message appears, custom options have not been imported

### Actual result:
Custom options of Product#1 have been imported to Product #2

**Comment by magento-engcom-team** [comment]
@piotrekkaminski, thank you for your report.
We were not able to reproduce this issue by following the steps you provided due to changes in functionality of the later versions in that relation. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
