### ISSUE TITLE
Category image does not copy from catalog/tmp/category to catalog/category directory when saving category whilst using database storage method

### ISSUE THREAD

**Issue by minlare** [magento/magento2#11995]
### Preconditions

1. Magento 2.4-develop

### Steps to reproduce

1. Set media storage to database
2. Upload category image in admin section
3. Save the category

### Expected result

1. The image row in media_storage_file_storage table should have directory `catalog/category` and correct `directory_id`

### Actual result

1. The image row in media_storage_file_storage table has directory `catalog/tmp/category`

I believe the problem lies with the `directory_id` not being changed in method `Magento\MediaStorage\Model\ResourceModel\File\Storage\Database::copyFile`

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/MediaStorage/Model/ResourceModel/File/Storage/Database.php#L275

When I manually change the `directory_id` in `$data` from the `catalog/tmp/category` directory_id to the `catalog/category` directory_id before running the `$connection->insertOnDuplicate` method the file is correctly copied to another row with the correct data.

_As another note, should it not convert the existing row to simply change the `directory_id` and `directory` rather than copying to a new row..._

**Comment by magento-engcom-team** [comment]
@minlare, thank you for your report.
We've created internal ticket(s) MAGETWO-83243 to track progress on the issue.

**Comment by breg-13** [comment]
Hi there.
![image](https://user-images.githubusercontent.com/9048430/40424783-2b9e3ff0-5e9f-11e8-9115-95ef1160ceea.png)
Resolved problem with category image saving for me.
Really strange. Check that file exists by some path FIRST and only then copy it to checked path :)

**Comment by davidwindell** [comment]
@breg-13 why close if this is still outstanding?

**Comment by kvydiuk** [comment]
@davidwindell, sorry that was just mistake.

**Comment by vseager** [comment]
Do you know when this will be fixed? Nearly a year since this was raised now.

**Comment by engcom-Alfa** [comment]
Reproduced on the fresh 2.4-develop instance

**Actual Result:**
![screen](https://user-images.githubusercontent.com/51679138/71473825-6bec6200-27e1-11ea-9410-fe2321729ea5.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30084` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Vishrootways** [comment]
Getting the same issue in Magento 2.3.4 fresh installation. Any fix for this issue?

**Comment by GautierI** [comment]
I also have the issue with Magento 2.3.4

**Comment by reense** [comment]
This is also happening in our shops.

**Comment by GautierI** [comment]
There is a workaround for this issue. Click on the button "Select from gallery" instead of "upload".

**Comment by GautierI** [comment]
A fix for the issue : 

`diff --git a/Model/Category/Attribute/Backend/Image.php b/Model/Category/Attribute/Backend/Image.php
index 4880214..d17d94e 100644
--- a/Model/Category/Attribute/Backend/Image.php
+++ b/Model/Category/Attribute/Backend/Image.php
@@ -79,8 +79,8 @@ public function __construct(
      */
     private function getUploadedImageName($value)
     {
-        if (is_array($value) && isset($value[0]['name'])) {
-            return $value[0]['name'];
+        if (is_array($value) && isset($value[0]['file'])) {
+            return $value[0]['file'];
         }

         return '';
`

**Comment by reense** [comment]
@GautierI Thank you!

**Comment by GautierI** [comment]
I updated the patch. It was breaking on a second click on save on the catagory.

**Comment by lano-vargas** [comment]
Same issue here newly fresh installation in 2.3.5 at the moment!

**Comment by nayan88** [comment]
Issue coming in 2.3.5 after magento version upgrade also as well in fresh installation of 2.3.5

**Comment by sergey-solo** [comment]
@magento I'm working on this

**Comment by PsmIndia** [comment]
we are also facing same issue after upgrade magento 2.3.4 now i am not able upload/delete/edit product image ?

**Comment by andy17612** [comment]
Issue coming in 2.3.5-p1, every one can help? thank you~

**Comment by nadroj467** [comment]
Experiencing this issue in Magento 2.3.5-p1 does anyone have progress with a solution? Thanks

**Comment by sivaschenko** [comment]
Priority set to P2 as the issue apparently blocks using category images with a database storage

**Comment by sivaschenko** [comment]
@sergey-solo are you still working on this issue?
