### ISSUE TITLE
Magento 2 Store Code validation regex: doesn't support uppercase letters in store code

### ISSUE THREAD

**Issue by zack6849** [magento/magento2#11996]
### Preconditions

1. Magento v2.1.9 (Probably earlier versions as well) 

### Steps to reproduce

1.  Go to stores > all stores
2.  Create Store View
3.  Attempt to create a store code with uppercase letters

### Expected result

1.  It should work, or give an error message

### Actual result

1. You get an error message back saying 
> The store code may contain only letters (a-z), numbers (0-9) or underscore (_), and the first character must be a letter.

Now, this error message is totally acceptable, makes perfect sense, but it let's say, for example, your store code you tried was ACME_STORE1, it's only letters and numbers, and has an underscore, and the first character is a letter, by all accounts, this should work, as far as i'm aware.

Unless there's a reason the store code is lowercase only the regex here: 

https://github.com/magento/magento2/blob/fd715d7327b951ade78a76a99bb8f5981c4629e1/app/code/Magento/Store/Model/Store.php#L466 

should either be changed to `/^[A-z]+[A-z0-9_]*$/`, or the message should be changed to indicate that only lowercase letters are supported.

**Comment by magento-engcom-team** [comment]
@zack6849, thank you for your report.
We've created internal ticket(s) MAGETWO-83245 to track progress on the issue.

**Comment by manuelson** [comment]
I am working on it at #mm17es

**Comment by orlangur** [comment]
@zack6849 well, `ACME_STORE1` and especially `AcME_StOrE1` is simply ugly and leads to potential mistakes in character case. I don't see any valid reason for this to be changed. Of course every regexp in the system can be expanded and such change is pretty easy but at least it would be nice to have some community discussion to approve such kind of changes.

Another recent example is inconsistent and wrong vendor name allowed in class FQCN which didn't allow vendors with digits in some places which is obviously wrong and such change is obviously valuable.

**Comment by zack6849** [comment]
@orlangur to be honest, i feel it's a consistency issue, for example, order number prefixes.

Our store's order prefix for example, is MXS, eg: MXS-00000001 or something, when i'm creating a new store, the fact I can't put a uppercase store code is quite confusing, because it's uppercased in the order numbers automatically, for example

Another thing is, maybe you shouldn't allow uppercase, i'm not making a defense for that specifically, though i personally think it should be allowed either way, my main issue is that the error message doesn't state that, which leads to even further confusion

**Comment by orlangur** [comment]
@zack6849 thanks for the real world example. Maybe it would be good at least to not allow mix of upper/lower case but just changing error message is the best option :)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83277

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83276

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by attheCube** [comment]
Hi,
the behaviour described above should be changed, because of the following reasons:

One reason why it should be possible to use uppercase letters in store code, is to differentiate regions in store code. Especially for using it within url.
So you could use 'de_DE', 'de_AT', 'en_US' or 'en_UK' as store codes, which is very useful in my opinion.

To be RFC 4646 (https://tools.ietf.org/html/rfc4646) conform, there has to be the possibility to use hyphens for store codes, too.

Surely it would be possible to do something weird by having this possibility, but that lies in the responsibility of the projects lead.
