### ISSUE TITLE
Fix date of birthday validation issue

### ISSUE THREAD

**Issue by selusi** [magento/magento2#12004]
### Preconditions
1. PHP 7.0.22
2. Apache2
3. MySql5.6
4. Magento 2.2.0

### Steps to reproduce
1. In backend **Stores->Configuration->General->General->Locale options** set locale as **English (United States)**
2. In backend **Stores->Configuration->Customer->Customer configuration->Name and address options** set **Show Date of Birth** as optional or required
3. In frontend open the page to create a new account and compile all fields and insert a date of birthday in format **mm/dd/yyyy** 

### Expected result
1. Pass validation and create new account

### Actual result
1. Date of birthday doesn't pass validation because the format is wrong
2. To pass validation You have to insert date in **dd/mm/yyyy** format

### To fix the issue
The issue is a validation rule setted at line 212 of 
```php
vendor\magento\module-customer\Block\Widget\Dob.php
```
To fix the issue I have modified the method `getHtmlExtraParams()` to use the appropriate rule based on locale settings.
The original method
```php
    public function getHtmlExtraParams()
    {
        $extraParams = [
            "'validate-date-au':true"
        ];

        if ($this->isRequired()) {
            $extraParams[] = 'required:true';
        }

        $extraParams = implode(', ', $extraParams);

        return 'data-validate="{' . $extraParams . '}"';
    }
```

New modified method

```php
    public function getHtmlExtraParams()
    {
        /* NEW LINES */
        $firstDateLetter = substr(strtolower($this->getDateFormat()), 0, 1);
        if( $firstDateLetter == 'm'){
	    $rule = 'validate-date'; /* Rule for mm/dd/yyyy date format */
	} else{
	    $rule = 'validate-date-au'; /* Rule for dd/mm/yyyy date format */
	}
        /* END NEW LINES */
	$extraParams = [
            "'".$rule."':true" /* MODIFIED LINE */
        ];
      
        if ($this->isRequired()) {
            $extraParams[] = 'required:true';
        }

        $extraParams = implode(', ', $extraParams);

        return 'data-validate="{' . $extraParams . '}"';
    }
```

**Comment by valentinboyanov** [comment]
I am working on it at #mm17es

**Comment by valentinboyanov** [comment]
The current issue was solved by the fixed issue magento/magento2#11067.

**Comment by magento-engcom-team** [comment]
@selusi, thank you for your report.
We've created internal ticket(s) MAGETWO-83300 to track progress on the issue.

**Comment by okorshenko** [comment]
Fixed in 2.2-develop

**Comment by SundarAkula** [comment]
Hi there, Can you please help with DOB validation. I want to restrict the customer based on 18 years.

**Comment by Paksifules95** [comment]
> Hi there, Can you please help with DOB validation. I want to restrict the customer based on 18 years.

Hi SundarAkula, you have a solution to this problem?
