### ISSUE TITLE
Extra slash added to category URL

### ISSUE THREAD

**Issue by eh6design** [magento/magento2#12000]
I am getting an extra slash added to my category URLs. Both 'Product URL Suffix' and 'Category URL Suffix' options are empty. Have tried adding then removing and still I get the extra slash (with full cache clear and reindex done also

### Preconditions

1.  Magento 2.2.0
2.  PHP 7.0.22/MySQL 5.6.36

### Steps to reproduce

1. Remove .html from both Product URL Suffix and Category URL Suffix
2. Redindex/clear caches
3. Change a category url to something different
4. Clear cache and reindex
5. '//' appears at beginning of new category url 
![screenshot-2017-11-03-14 43 17](https://user-images.githubusercontent.com/20557309/32379675-18383f84-c0a6-11e7-896c-768b0bb7dc63.png)

### Expected result

1. There should only be one forward slash

### Actual result

1. Two are added instead

Any suggestions? I should note there is a solution [here](https://mage2.pro/t/topic/991/2) but this does not appear to work in 2.2.0

**Comment by eh6design** [comment]
Looks like an import issue when importing products from M1. Setting 'Category URL Suffix to '/' and renaming/saving the category seems to remove the issue. Will try reimporting with this in place.

**Comment by magento-engcom-team** [comment]
@eh6design We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue.

**Comment by magento-engcom-team** [comment]
@eh6design, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
