### ISSUE TITLE
i'm not getting default values (name & email) in contact form when i logged in.

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1200]
i'm not getting default values (name & email) in contact form when i logged in.

I think there is a problem with customer session.
Magento ver. 0.74.0-beta4

**Comment by vpelipenko** [comment]
@sivajik34, do you mean Contact Us form?

**Comment by sivajik34** [comment]
yes.i debugged some what.isloggedin function not working

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-37044

**Comment by kokoc** [comment]
@sivajik34 The fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?

**Comment by sivajik34** [comment]
its working fine.thank you
