### ISSUE TITLE
[Magento 2.2 ] Website Resctriction Login only - Can't create account from BO

### ISSUE THREAD

**Issue by widegento** [magento/magento2#12005]
### Preconditions

1. PHP 7.0.18
2. Apache 2.4
-- 
3. Magento 2.2 EE
4. B2B Modules

### Steps to reproduce

1.  In Store -> Configuration -> General -> WebsiteRestriction
2.  Put the restriction mode to : Private Sales - Login Only

### Expected result

1.  User won't be able to register
2.  User will only be able to login
3.  Account can be created from the backoffice so user will receive invitation

### Actual result

1.  I am not able to create an account from the backoffice

![image](https://user-images.githubusercontent.com/25622407/32383851-699bad62-c0b9-11e7-9275-f2377cc2f0b7.png)

This seems to be related to a new Plugin in websiteRestriction module.

Is this a normal behaviour ? If yes , how can we restrict the frontend to login only , but still create account in Backoffice ?

**Comment by magento-engcom-team** [comment]
Thank You for applying @widegento. The functionality You have mentioned above is not available in Community Edition versions of Magento. Therefore please address Your issue directly to Magento Support.
