### ISSUE TITLE
Cross-sell product placeholder image size issue

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12017]
In a cart page cross-sell product placeholder image size is too much small. Its size should be displayed same like Product listing page placeholder image. 

### Preconditions

1. Magento 2.1.9
2. Magento 2.2.0

### Steps to reproduce

1. Install Magento with sample data.
2. Set cross-sell for any product. And in one of that selected product remove product image from any product.
3. Go to front end and add to cart that product which you have set cross-sell products.
4. Go to cart page and check cross-sell products. And then check product which shows with the placeholder image. For more details attached screen short

### Expected result

1. Its size should be displayed same as Product listing page placeholder image.  

### Actual result

![placeholder image issue](https://user-images.githubusercontent.com/2203580/32406062-3b1175d8-c197-11e7-9508-1287131c47d3.png)

**Comment by ghost** [comment]
We have a solution for that. And we would link to work on this.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @emiprotech. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1286 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by VincentMarmiesse** [comment]
Hi @magento-team,
The PR link you provided leads to a 404, is it possible to have the PR so I can patch my M2.2.2?
Thanks.
