### ISSUE TITLE
"Please specify product option(s)." Message no hiding

### ISSUE THREAD

**Issue by oksana8119** [magento/magento2#12019]
After add product to cart (configurable or bundle) "Please specify product option(s)." Message no hiding.

### Preconditions

1. Magento 2.2
2. php 7.0.25

### Steps to reproduce

1. Go to Category page
2. Try to add from Quick add to cart block configurable or bundle product to cart
3. After click -> redirected to product page, and showing message "Please specify product option(s)."
4. Change options and add product to cart. Page is refreshed, and showing 2 messages 

- "Please specify product option(s)."
- "You added ... product to your shopping cart"
<img width="1209" alt="screenshot at nov 04 16-01-59" src="https://user-images.githubusercontent.com/19412916/32406491-c04c1500-c179-11e7-8ce8-b6792db742c4.png">

5. After added product to cart -> go to another page .
6. You still see message "Please specify product option(s)."
<img width="1213" alt="screenshot at nov 04 16-02-20" src="https://user-images.githubusercontent.com/19412916/32406493-d365bcfe-c179-11e7-81df-ddc02807dce6.png">

**Comment by magento-engcom-team** [comment]
@oksana8119, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by juroszed** [comment]
Sometimes get the same error on Magento 2.1.0 and 2.1.12

It looks like the error only comes first time a day adding a bundle product to cart. If I got the error it is not possibel to reproduce.
