### ISSUE TITLE
Updating product multiselect attribute saving the old values too

### ISSUE THREAD

**Issue by vinoth44** [magento/magento2#12026]
I have color as multiselect attribute in my catalog. When I create a product I select white and green as colors. Now I edit the product and unselect white, green and select Red. It works in backend but when I use layered navigation in frontend and choose products with white color it shows the product with only red color which had white and green earlier. When I checked catalog_product_entity_varchar table the old value still exist there. 

### Preconditions

1. PHP 7.0.22
2.  MYSQL 5.6.37 
3. Magento version 2.1.7

### Expected result

1. I was expecting the products with only white color in layered navigation. 

### Actual result

1. The result show products with only Red color which had white color earlier.

**Comment by magento-engcom-team** [comment]
@vinoth44, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@vinoth44, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
