### ISSUE TITLE
Magento 2 downloadable product URL link & Downloadable attachment does NOT work

### ISSUE THREAD

**Issue by Starfish777** [magento/magento2#12027]
Neither the Magento 2 downloadable URL link nor the Downloadable attachment work in Magento 2. I have included screenshots.  Even after purchase and invoicing order which then goes into customer account. The Downloadable links do not work and send an error message. Also when trying to upload a "Downloadable Product" file as an attachment. I also get a message saying "the file has not uploaded".

### Preconditions

This was installed by installatron (Magento version 2.2.0), althrough I have also replicated this same issue on a manual install of Magento 2.1.7 as well.   MySQL ver. 5.6.36-cll-lve, PHP 7 with the following settings:
![image](https://user-images.githubusercontent.com/13037090/32410611-5ca54450-c19b-11e7-928b-3aaa72898820.png)

### Steps to reproduce
1. Login to Admin and click on Catalog --> Product and start a new "Downloadable Product"
2. enter info and go to the bottom and click on Link in order to start a new link for the Downloadable Product.
3. Use the pulldown to choose "Upload a file"  (at this point it will give the message that no file could be uploaded) or enter a URL and save.
4. If you have entered a URL and the product is viewable. Attempt to purchase it as a customer (set the price at $0.00 so that you dont have to actually transact money.
5. After the purchase has been made, go back into the Admin and turn the now Pending sale into an Invoice.
6. Go back into the customer account and click on the now available download link and see that it gives an error message and the link does not work

### Expected result
1. The upload should upload the file attachment and make it available after purchase. Also the link should go where you have specified in the product details.

### Actual result

1. Nothing but errors

![downloadable-nodownloadfile](https://user-images.githubusercontent.com/13037090/32410661-e7ff1d22-c19c-11e7-940d-783bc83c816e.PNG)

![downloadablelinknotworking](https://user-images.githubusercontent.com/13037090/32410660-debb123e-c19c-11e7-8421-40a930292402.png)

**Comment by magento-engcom-team** [comment]
@Starfish777 Hi. We cannot reproduce the issue . This error can be caused by server permissions / configurations. It could simply be a permission issue so please ensure your web server user has full rights as per it's recommended in [devdocs](http://devdocs.magento.com/guides/v2.1/install-gde/prereq/file-system-perms.html) .

**Comment by magento-engcom-team** [comment]
@Starfish777, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
