### ISSUE TITLE
Minify Html doesn't process templates from Theme directory

### ISSUE THREAD

**Issue by d10nZ** [magento/magento2#12024]
### Preconditions
1. Magento 2.1.9
2. Custom Theme with custom templates (app/design/{area}/{Theme_Path}/templates/)
3. deploy-mode = production

### Steps to reproduce
1. Set Minify Html to "YES";
2. php bin/magento setup:static-content:deploy (in console);

For details please look at the question [here (magento.stackexchange.com)](https://magento.stackexchange.com/questions/199999/minify-html-doesnt-process-templates-from-theme-directory)

### Expected result
1. Please add capability to minify phtml-templates with paths "app/design/{area}/{Theme_Path}/templates/..." . Or forbid their usage.

### Actual result

1. Templates with paths "app/design/{area}/{Theme_Path}/templates/..." aren't being handled during "setup:static-content:deploy" process. In this case I mean minifying-subprocess.
2. Such templates aren't created in "var/view_preprocessed/html/..." directory

**Comment by magento-engcom-team** [comment]
@d10nZ, thank you for your report.
We've created internal ticket(s) MAGETWO-84399 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@d10nZ, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
