### ISSUE TITLE
Tax Report does not take into account credited taxes.

### ISSUE THREAD

**Issue by nikoelgatito** [magento/magento2#12029]
It seems that the Tax Report does not take into account the refunded taxes. Also when a credit memo is created, only the total tax_amount is calculated and stored in the database but no tax specific tax_amount is calculated or stored.

This means for example that if we sell a product which is taxed by 2 different taxes (5% + 10%), the credit memo tax_amount stored will only reflect the total 15% tax amount. This means that there would be no way to differentiate different tax rates/amounts from the total without having to do a reverse calculation.

I think that as there is a sales_order_tax and sales_order_tax_item tables, either the tax amounts stored in these tables should be adjusted once a credit memo has been created or there should be a sales_creditmemo_tax and sales_creditmemo_tax_item tables that stores the tax details for all credit memos.

This means that as the current Tax Report is built, it does not serve any purpose as we can't rely on its data to submit any valid tax declaration to the government. All accounting report should take into account both incoming and outgoing values in order to render reliable results.

### Preconditions
1. Any Magento version

### Steps to reproduce
1. Go in the Admin menu to [REPORTS] -> [Sales] -> [Tax]
2. Generate a report including order where a credit memo was created with tax.

### Expected result
1. The Tax Amount should reflect the total tax paid after any credit memo has been applied.

### Actual result
1. The Tax Amount only shows the initial transaction tax without taking into account any further adjustments.

**Comment by magento-engcom-team** [comment]
@nikoelgatito, thank you for your report.
We've created internal ticket(s) MAGETWO-83306 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@nikoelgatito, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
