### ISSUE TITLE
Downloadable Products "INVOICED" selection does not work

### ISSUE THREAD

**Issue by Starfish777** [magento/magento2#12028]
![image](https://user-images.githubusercontent.com/13037090/32410691-71766a92-c19d-11e7-936d-46083ba51ec1.png)

When you select Stores --> Configuration --> Catalog(Catalog)---> Downloadable Product Options the first option which is "Order item status to enable Downloads" has "Invoiced" chosen as a standard. But this does not work. When you create a Downloadable Product, and purchase it as a customer. You find that it automatically goes to "Pending" status. You have to come into the Admin to make the order an Invoice before the link (which does NOT work) is enabled.  After you go back as a customer and access your Downloadable products and try to click on the link, you will find another Magento bug wherein the link does not work (I have already documented that in another github report). However, this is about the Downloadable Product purchase not auto invoicing which would make it available immediately. 

### Preconditions
This was installed by installatron (Magento version 2.2.0), althrough I have also replicated this same issue on a manual install of Magento 2.1.7 as well. MySQL ver. 5.6.36-cll-lve, PHP 7 with the following settings:
image:

![image](https://user-images.githubusercontent.com/13037090/32410724-3dc761a0-c19e-11e7-8583-ac5dda7944d6.png)

### Steps to reproduce
1. Log into Admin panel and create a new Downloadable product for $0.00
2. Purchase the Downloadable Product as a customer
3. After purchase is complete you go to your account and click on "My Downloadable Products" to see your new Downloadable Product. You will see the the status is "Pending" even though a fresh install sets the Downloadable Product "Order Item Status to enable Downloads" to "Invoiced" the store forces it into Pending status which means that the admin has to manually go in and change each order into an invoice before the Download can be accessed by the customer. 

### Expected result
1. If the Downloadable Product would truly automatically get Invoiced upon purchase, the customer would have automatic access to it instead of having to wait for the Admin to invoice it. Also the Admin would not have to consume time needlessly going into every single Download order in order to invoice each one so that the Download Link would then become available.

### Actual result
(See Pending Downloadable link --- The "Available" link was manually invoiced)
![downloadablelinknotworking](https://user-images.githubusercontent.com/13037090/32410773-1e0cfa36-c19f-11e7-9b22-039970ec4e02.png)

**Comment by magento-engcom-team** [comment]
@Starfish777, thank you for your report.
If you need automatically get Invoiced upon purchase:

1. Go to  Stores > Configuration > Catalog(Catalog) > Downloadable Product Options and change to Order Item Status to Enable Downloads is Pending.

2. If product price for Downloadable Product is 0
Go to Stores > Sales > Payment Methods > Other  Payment Methods > Zero Subtotal Checkout
New Order Status > Choose Processing
Automatically Invoice All Items > Choose Yes
Thanks.

**Comment by magento-engcom-team** [comment]
@Starfish777, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by nickpiro** [comment]
This step:
If product price for Downloadable Product is 0
Go to Stores > Sales > Payment Methods > Other Payment Methods > Zero Subtotal Checkout
New Order Status > Choose Processing
Automatically Invoice All Items > Choose Yes

Doesn't work if you put real world orders through as $0 dollars sometimes, let's say for promotions etc that a sales rep would put an order in for $0. 

Invoicing an order immediately before being able to add shipping information to it is a big no no. 

Why was the functionality from previous versions of Magento 2 suddenly changed after 2.2.5?

I just updated to 2.2.8 from 2.2.5 and now suddenly, the Invoiced on Downloadable Orders is completely useless. Now you're saying you have to automatically switch ALL order types that are $0 dollars as well?

That sounds completely wrong and does not work for a lot of companies who use Magento for Sales reps putting orders through as well as customers.
