### ISSUE TITLE
OAuth Failed. oauth_problem=Consumer+key+has+expired

### ISSUE THREAD

**Issue by ajayak** [magento/magento2#12032]
Getting status as Unauthorized and description as oauth_problem=Consumer+key+has+expired when making Request to `oauth/token/request` to get oauth_token.

### Preconditions
1. Using Magento 2.2

### Steps to reproduce
1. Create an Integration. Name it "test" and enter the admin password
2. On the API tab, set Resource Access to All
3. Click save and then activate the service.
4. Copy Consumer Key and Consumer Secret to make the call to `oauth/token/request`.

### Expected result
I should get OK response with oauth_token in body

### Actual result
1. I get 
StatusCode: **Unauthorized**
Content: **"oauth_problem=Consumer+key+has+expired"**

Note: All the operations are done under 2 minutes. Full Request URI is http://local.magento/oauth/token/request

**Comment by orlangur** [comment]
Hi @ajayak, please check if https://github.com/magento/magento2/issues/10423#issuecomment-320083172 works in your case.

**Comment by ajayak** [comment]
Hi @orlangur,
I have already activated the integration but still getting this error.

**Comment by aohlrogge** [comment]
I am having this exact same problem.  I have increased the expiration and timeout in the Store Configuration, however no matter what they are set to I always get "oauth_problem=Consumer+key+has+expired"

**Comment by magento-engcom-team** [comment]
@ajayak, thank you for your report.
We've created internal ticket(s) MAGETWO-83526 to track progress on the issue.

**Comment by itsabe** [comment]
Also, I stumbled upon #12032 from back in Nov 2017, but have not seen any updates on it.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
