### ISSUE TITLE
Enable JS Bundling breaks admin dashboard slide out

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1203]
When you enable the JS Bundling feature, the admin "side" dashboard no longer opens which means you cannot turn it off again or use the admin at all

Seen in beta 4 and beta 5

**Comment by alankent** [comment]
!!!

**Comment by vpelipenko** [comment]
@craigcarnell, we've tried to reproduce this issue but without success. Maybe you need to clean caches. Could you provide more information for us? Do you see any JS errors?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor, issue can't be reproduced internally.

**Comment by ci2014** [comment]
Hello craig, thank you for referencing. I see the errors as mentioned in my issue:

http://magento/pub/static/version1450257641/adminhtml/Magento/backend/de_DE/requirejs/require.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://magento/pub/static/version1450257641/adminhtml/Magento/backend/de_DE/mage/requirejs/mixins.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by gagandeep-cueblocks** [comment]
Still facing this issue in magento 2.1.4
Steps :-
Enable production mode
Enable minification/merging of js. 
Run the magento Content deploy indexing cache clean etc.. scripts
