### ISSUE TITLE
Switching between grid view and list view does not work

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1204]
Initially I was on grid view, I clicked on list view. This did nothing until I refreshed the page. Then when I try to get back to grid, nothing happens

**Comment by kokoc** [comment]
@craigcarnell Thank you for reporting the issue. However, I can't reproduce this issue on latest code base (category listing page). Could you please provide more details (browser, page, version) and verify the issue on latest Magento?

**Comment by vpelipenko** [comment]
@craigcarnell, sorry for bothering, but did you have a chance to check this issue on the latest Magento 2 version?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.
