### ISSUE TITLE
Magento 2.1.7: swatchs not working

### ISSUE THREAD

**Issue by redfishstix** [magento/magento2#12046]
Hi,

Been working with 2.1.7 for a while now, finish all my site but suddendly, some swatchs aren't working.

Preconditions:
1. Magento 2.1.7 running the Claue template from themeforest
2. php 7.0.25
3. No varnish enabled.
4: Mysql ver 14.14

Steps to reproduce:
When accessing the product listing (IE: click on a category, the various products will be displayed. I have my swatchs shown there as I have the Visible on catalog Pages on Store Front active. ALL my swatchs work fine from there. If I click on the product and try to view swatchs, the image will swap to a random image that's not even related to the product.

Expected results:
Swatchs should be changing for the product image.

Actual Result:
Swatchs are not changing for the product and instead, showing a unrelated product image.

Troubleshooting, testing:
For some odd reason, if you run:
php bin/magento catalog:images:resize
This will fix the swatchs but if you add more, then it breaks again.

Also, i've tried doing:
Enabling Options "Visible on Catalog Pages on Storefront" and "Used in Product Listing" in the color attribute. It fixed it for some swatch, not others.

I haven't seen if this is a problem that is reccurent in another versions of Magento (or if they fixed it?).

Thanks for helping! :)

Marc,

**Comment by Mgrennes** [comment]
Hi there, what is G1 Failed? Do you need more info?

Thanks,

**Comment by redfishstix** [comment]
Updated ticket with more information.

**Comment by redfishstix** [comment]
With some research, and i'm not sure why I didn't see this before, but this was fixed in 2.1.9 but the last comment said it still doesn't work: https://github.com/magento/magento2/issues/9965

Can anyone comment on this please?

**Comment by redfishstix** [comment]
Hi, I can confirm that upgrading to 2.1.9 did not fix anything.

**Comment by redfishstix** [comment]
Well this is getting more bizarre. After re-creating another set of new configurable products with visual swatchs, it's still not working.

Now, if I go to older created configurable products with visual swatchs, if i click on those swatch, the NEW product shows up (only the main image will show up if click on the swatchs).

It doesn't make sense!

**Comment by redfishstix** [comment]
With some help, I was able to fix the last product that I added by disable the catalog product flat in configuration > catalog > catalog

All my other configurable product are still not working, except the last one I have configured.

**Comment by magento-engcom-team** [comment]
@Mgrennes, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
