### ISSUE TITLE
Magento 2.2 email variables not referencing to the html values

### ISSUE THREAD

**Issue by rustsol** [magento/magento2#12059]
It seems like the default bug of Magento that does not send actual customer address, it sending in variable format, reference to sales email address as following format:

**Billing Address Edit** **Email and admin panel order section format for address**
{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}{{depend firstname}}
{{/depend}} {{depend company}}{{var company}}
{{/depend}} {{if street1}}{{var street1}}
{{/if}} {{depend street2}}{{var street2}}
{{/depend}} {{depend street3}}{{var street3}}
{{/depend}} {{depend street4}}{{var street4}}
{{/depend}} {{if city}}{{var city}}, {{/if}}{{if region}}{{var region}}, {{/if}}{{if postcode}}{{var postcode}}{{/if}}
{{var country}}
{{depend telephone}}T: {{var telephone}}{{/depend}} {{depend fax}}
F: {{var fax}}{{/depend}} {{depend vat_id}}
VAT: {{var vat_id}}{{/depend}}

Tried to debug the issue, address in **customer data table** is fine and correct but in **sales_order_Address** table, it showing NULL values.

**Test Cases:**
1. When I made order using "**Money Order**" payment method its sending proper information in email and in admin panel under manager order section.
2. When i use "**PayPal**" as payment method to make an order it's sending email as above mentioned format and sames goes in admin panel under manage order section

Trying to get rid of this issue from last few days but didn't got any solution yet.

This is bug of Magento 2.2 i guess because its happening after upgrading from Magento 2.1.8 to Magento 2.2. Even its the same error in fresh Magento 2.2 installation.

Let me know if anyone facing same issue or have solutions for the same?

**Reference screenshot attached below:**

![customer_addres_issue _order_email_customerdashboar_via_paypal](https://user-images.githubusercontent.com/3087805/32444373-65cddb6c-c328-11e7-837e-401fe8e40656.png)

**Comment by bluvertigo** [comment]
I have the same issue with magento 2.2.0 and paypal standard

**Comment by magento-engcom-team** [comment]
@yogisfunda, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Try to reproduce this issue on fresh and clean installation without any third-party dependencies.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by rustsol** [comment]
I've already tested the same in fresh Magento installation with v 2.2 but it didn't worked. When i enable paypal express and payment method its sending transactional email in above mentioned format.

It is working fine with money order and payment methods.

It doesn't need to reproduce its already there, when you enable paypal express as your payment method you will see the odd format transactional email.

Expected results should be the format which human can understand, i mean in the general order email template with the order values and customer detail.

**Comment by magento-engcom-team** [comment]
@yogisfunda , We need more information about this issue in order to successfully investigate potential fixes. Please use our issue tracking template to format your description. Specify the exact steps you used, the expected result of your actions, and the actual results.

**Comment by rustsol** [comment]
I don't understand what else you need, it seems like you are not trying to understand the issue and just recommending me to formatting the issue and description. It's very simple and mentioned above multiple time. It seems like I've to work on this issue on my own to post solutions. Thanks for your support.

**Comment by magento-engcom-team** [comment]
@yogisfunda, thank you for your report.
We've created internal ticket(s) MAGETWO-85231 to track progress on the issue.

**Comment by rustsol** [comment]
Thanks, I'll continue to check this from my end too.

**Comment by harsh719** [comment]
I want to fix this issue please guide me @krishparekh

**Comment by harsh719** [comment]
![Magento Issue](https://user-images.githubusercontent.com/49854559/56485681-a5522c80-64f2-11e9-9a95-febf78615e5a.png)
See this image to get a better understanding.

Thanks.

**Comment by harsh719** [comment]
****Preconditions****

PHP 7.0.3
Mysql 5.6
Latest chrome browser
Magento environment: Production
JS / CSS minifcation and merging enabled.

**Steps to reproduce**

Go into any page with a wysiwyg editor possiblity ( e.g. product edit page ).
See that sometimes it does not appear
Try clicking "Show editor". Nothing happens.
If you click the "Show/Hide editor" and do F5 refresh the page, suddenly the WYSIWYG editor shows.

**Expected result**

When toggling between Show/Hide editor you should get the WYSIWYG editor.

**Actual result**

Editor not showing (randomly) . Sometimes it does, sometimes not. A browser refresh might do so the editor opens..

**Comment by engcom-Alfa** [comment]
Hi @yogisfunda, thank you for your report.

Unfortunately, we are not able to reproduce this issue on a fresh 2.4-develop instance following by your steps. Everything works correctly.

**Actual Result:**
![screen](https://user-images.githubusercontent.com/51679138/73739485-f87a3080-474e-11ea-92d8-dd5c7471b9d1.png)
Checked and with the "PayPal" payment method.
So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by yogisfunda** [comment]
Well, the issue was in 2.2 and I am sure it's solved in the latest 2.4... thanks for the fixes but I've already got this solved on Magento 2.2 in couple of days after posting the issue here. Anyways thanks for the notification.
