### ISSUE TITLE
Product relations get lost on Scheduled new update EE 2.1.9

### ISSUE THREAD

**Issue by vantrinhvp** [magento/magento2#12052]
### Preconditions
1. Magento EE 2.1.9
2. PHP 7.0.17

### Steps to reproduce

1. Open a configurable product in the Magento backend 
2. Click Scheduled new update 
3.  Change name and set time start date

### Expected result

1. Only change name product

### Actual result

1. product configuration is simple product and product relations get lost.

![screenshot_1](https://user-images.githubusercontent.com/17479593/32425764-13fdbf5e-c2e8-11e7-88b8-a28f225ea2ca.png)
2. Qty = 0 and Price = 0
![screenshot](https://user-images.githubusercontent.com/17479593/32431062-7c0b85ce-c304-11e7-8227-9fd34ef866d2.png)

**Comment by magento-engcom-team** [comment]
Thank You for applying @vantrinhvp. The functionality You have mentioned above (Schedule New Update) is not available in Community Edition versions of Magento. Therefore please address Your issue directly to Magento Support.
