### ISSUE TITLE
Table rates issue not showing in website or in the database

### ISSUE THREAD

**Issue by mstfash** [magento/magento2#12056]
Hey i use a fresh 2.1.6 mage installation.

I setup table rates as usual but frontend does not appear in the website at all only the fixed tare shows up. 
i imported a tablerate.csv with ~20rows and mage say no error while upload it.
and I get configurations has been updated message.

If i wanna export the csv i got a empty one.

So i checked the DB entry "shipping_tablerate" and this is also empty.

So there is a problem with import the csv without error
also I have tried a way to make all the values not rquired

Hope someone can help me

### Preconditions

1. Magento 2.1.6
2. Multi language website.
3. My website is: http://shop.3bont.com/

### Steps to reproduce

1. Set Different Shipping Methods fixed and table rates.

### Expected result

1. User finds 2 shipping methods to choose from fixed rate and table rates depending on the countries cities I have included which is btw (Egypt)

### Actual result

1. Only fixed rate is shown and the table rates never show up.

below is sample of my CSV file

<img width="343" alt="screen shot 2017-11-06 at 12 55 08 pm" src="https://user-images.githubusercontent.com/5751607/32438020-c62592fc-c2f1-11e7-985d-76bfda175c7a.png">

<img width="417" alt="screen shot 2017-11-06 at 12 56 43 pm" src="https://user-images.githubusercontent.com/5751607/32438086-fb92664a-c2f1-11e7-9cb1-010aaa2bc868.png">

<img width="1440" alt="screen shot 2017-11-06 at 12 49 02 pm" src="https://user-images.githubusercontent.com/5751607/32437734-ed77f0d0-c2f0-11e7-8f47-794f0b04c631.png">

<img width="1440" alt="screen shot 2017-11-06 at 12 48 59 pm" src="https://user-images.githubusercontent.com/5751607/32437735-ed9a8000-c2f0-11e7-8dab-da2010b97f92.png">

**Comment by magento-engcom-team** [comment]
@heavenchains, thank you for your report.
This is duplicate of [#11468](https://github.com/magento/magento2/issues/11468)

**Comment by ForAnythingWebmaster** [comment]
I am still getting the same error as well, and I have tried on version, 2.07, 2.1.0 as well as 2.1.10 (the latest version in the series and the duplicate #11468 does not appear to be the same issue because no error message is being thrown at all)

**Comment by Guy-Baillie** [comment]
I had the same issue. the only way I got around with it was with this extension.
https://marketplace.magento.com/webshopapps-module-matrixrate.html
