### ISSUE TITLE
Varnish VCL

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1205]
Where can I find the Varnish VCL?
Does it support hole punching? e.g. for basket
Is it multi-store and multi-currency compatible?

**Comment by rkratt007** [comment]
I'm not aware of Magento 2.0 having varnish support built in. You would need to integrate an extension from the older version of magento to work with magento 2.0

http://www.magentocommerce.com/magento-connect/turpentine-varnish-cache.html

**Comment by kandy** [comment]
Magento 2.0 have built in varnish support.
Config generation available at STORES > CONFIGURATION section ADVANCED > SYSTEM > Full Page Cache, Select Caching Application: varnish caching and in section Varnish Configuration available "Export VCL for Varnish 4" button.

**Comment by vpelipenko** [comment]
@craigcarnell, do you have another questions about Varnish support in Magento?

**Comment by craigcarnell** [comment]
@vpelipenko Yes - does it support hole punching and if it does, how do we use this in our own modules/themes (e.g. custom private/public TTLs etc)

**Comment by ontic** [comment]
@craigcarnell This blog post might shed some light.

https://alankent.wordpress.com/2014/12/09/magento-2-caching-overview/#comment-1116

**Comment by mazhalai** [comment]
@craigcarnell does above blog post answer your question?

**Comment by cscd98** [comment]
@mazhalai @vpelipenko 

From the link provided:

```
it is however important to realize that ESI in Magento 2 is not used for hole punching of cached pages
```

Could we look to add whole punching in the future?
