### ISSUE TITLE
My Account display only 9 orders in "My Orders"

### ISSUE THREAD

**Issue by pmoreno1980** [magento/magento2#12066]
### Preconditions
Magento 2.1.7
PHP 7.0
Mysql 5.7
Using Paypal & Cybersource for CC

### Steps to reproduce
1.  I logged in in My Account as Customer
2.  I clicked on "My Orders" to see all my orders history.

### Expected result
1.  See all orders until today under "my orders" 

### Actual result
1. I can see only 9 orders ( My Orders) but i can't see any order after 9/27/17 (i have a lot of orders after that date) (it's my test account as customer).

**Comment by magento-engcom-team** [comment]
@pmoreno1980, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
