### ISSUE TITLE
In-correct addres validation for PayPal message not shown ( A match of the Shipping Address.... )

### ISSUE THREAD

**Issue by archonkulis** [magento/magento2#12067]
### Preconditions

1. Magento version - 2.1.6 and 2.2.0
2. PHP 7.0
3. Mysql 5.6

### Steps to reproduce

1. Configure and Enable PayPal payment method - sandbox also works
2. Go to check-out, enter some address and input wrong post-code ( e.g. https://prnt.sc/h76cus - notice postcode is wrong )
3. Click on Continue To PayPal
4. Enter account details
5. Submit

### Expected result

1. After redirecting back from PayPal, you should see "PayPal gateway has rejected request. A match of the Shiping Address City, and Postal Code failed.... " error

### Actual result

1. Instead, after redirecting back, the message is not visible ( what's interesting is that it happens randomly - sometimes it's visible and sometimes not. Read my observations for more info ) , although the message is in the debug.log file.

### My observations

After long debugging, it seems that issue is because of 2 ajax calls. I'll explain two scenarious below.

1) When these 2 ajax requests happen in correct order, then the message is seen. Here is a screenshot of those 2 requests -> https://prnt.sc/h59g4t ( you can ignore comment in red ).

So, the first request is customer/section/load - in this request it gets all messages from session and removes them from the session.

Next, there is a gettoken - here it gets the token, parses it and adds error message to session.

Page reloads - all good, we have the message in the session.

2) Now, sometimes though, the message is not visible ( most of the time actually, like 90-95% ) and I noticed that in these cases those 2 ajax requests are done vice-versa. Here is the screenshot -> https://prnt.sc/h59gqt

As you can see, it first gets token, adds it to session.

Then, the customer/section/load - here it removes the message from session.

And after page load, there is no message to display.

Btw, when I'm talking about page load - after you get redirected from PayPal, it does some ajax calls and then automatically refreshes the page. Not sure, but I think in 2.2 version you have to set "Enable In-Context Checkout Experience" to No, but in 2.1.6 set to Yes for this page reload to happen. ( which is also weird actually )

Also, what I have noticed - if I return some data in customer/section/load imediately ( without giving Magento chance to parse some things, because it takes some time ), then in 99% of the time message is visible, because this request is finished first and then gettoken request can do it's thing. But, in the times when message is not visible, it seems that while customer/section/load is parsing, the gettoken request is fired without waiting for customer/section/load to finish and finishes before customer/section/load.

As a hotfix, I have added message to another message group, then in observer ( controller_action_predispatch_checkout_index_index ) I merged that message from another group to default group and removed from another message group. Obviously, this is just a hotfix ( just in case anyone else will look for a temporary solution or may direct you one some thoughts about the fix ).

Let me know if you have any questions.

Thanks.

**Comment by magento-engcom-team** [comment]
@archonkulis, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
