### ISSUE TITLE
Bundled product "Bundle items" pagination prevents reordering between pages

### ISSUE THREAD

**Issue by EdenCoder** [magento/magento2#12069]
Bundled product "Bundle items" pagination prevents reordering between pages

### Preconditions

1. Magento 2.2.0
2. PHP 7.1
3. MySQL 14.14

### Steps to reproduce

1. Fill up a bundled product's "Bundle items" to more than one page
2. Reorder a "Bundle item" from one page to the other

### Expected result

1. Should be able to reorder "Bundle item" between different pages

### Actual result

1. You can only reorder within the current page for bundle options

**Comment by magento-engcom-team** [comment]
@EdenCoder , thanks for you report.  DynamicGrid UI component (that is used for adding bundled product options) do not support sorting between pages.

**Comment by magento-engcom-team** [comment]
@EdenCoder, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by mverstraete** [comment]
This is not a "non-issue", I literally have a client right now asking me how they are supposed to reorder their bundle item options.   My only option right now is to renumber them manually in the database.  There should at least be an option to "show all" and/or change the number of items per page.

**Comment by magento-engcom-team** [comment]
Hi @EdenCoder. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/76
