### ISSUE TITLE
Products in cart report error when we have grouped or bundle product

### ISSUE THREAD

**Issue by mihaifaget** [magento/magento2#12079]
When viewing the report 'Products in cart' the report gives error if we have a bundle or a grouped product in cart. 

## Preconditions

Magento Version 2.1.9
## Steps to reproduce

Add a grouped or a bundle product to cart. Go to admin->Reports->Marketing->Products in cart and loop through pages or export to csv/excel.
## Expected result

Should see the Products in cart report or download csv/xml
## Actual result

Exception #0 (Exception): Notice: Undefined offset: [productId] in vendor/magento/module-reports/Model/ResourceModel/Quote/Item/Collection.php on line 222

**Comment by magento-engcom-team** [comment]
@mihaifaget, thank you for your report.
We've created internal ticket(s) MAGETWO-83435 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Hi @mihaifaget. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1287 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
