### ISSUE TITLE
Installation is incomplete. Check the console log for errors before trying again. 

### ISSUE THREAD

**Issue by jialuni** [magento/magento2#1207]
Hello,

I have this message during beta setup wizard (Installing... 68%) :

** Installation is incomplete. Check the console log for errors before trying again. **

### My env : 
Wampserver 2.5 on Windows 7 (ultra new install without particular configuration) with
Apache 2.4.9
PHP 5.5.12
Mysql 5.6.17

I tried :
- with a "develop" branch pull, then I tried cloning a "master" pull in an other directory.
- with or without optional module selection

=> In both case I made a "composer update" first, and all is OK during the first steps, and I have this message when afeter valisating the Step 6: Install (Installing... 68%).

- I clicked "Try again" many times, with same result

- Tried with "All user" write permission on all subdirectories.

- I've seen someone poste a near-similar issue here : https://github.com/magento/magento2/issues/815 xdebug was the problem :; I disabled it and it works now better (68% install instead of 65% : "install user configuration" step)

Maybe another required PHP library ? How can I debug ?

### Console log :
Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Theme':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_CatalogImportExport':

Module 'Magento_Indexer':

Module 'Magento_Cms':

Module 'Magento_Search':

Module 'Magento_Catalog':

Module 'Magento_Rule':

Module 'Magento_CatalogInventory':

Module 'Magento_Payment':

Module 'Magento_Quote':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_Widget':

Module 'Magento_Bundle':

Module 'Magento_Developer':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_SalesSequence':

Module 'Magento_Email':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GroupedProduct':

Module 'Magento_ImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_User':

Module 'Magento_Log':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Multishipping':

Module 'Magento_Newsletter':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Centinel':

Module 'Magento_ProductAlert':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_Rss':

Module 'Magento_GiftMessage':

Module 'Magento_CatalogSearch':

Module 'Magento_Shipping':

Module 'Magento_Tax':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Translation':

Module 'Magento_Ui':

Module 'Magento_UrlRewrite':

Module 'Magento_Integration':

Module 'Magento_Variable':

Module 'Magento_Wishlist':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Theme':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_CatalogImportExport':

Module 'Magento_Indexer':

Module 'Magento_Cms':

Module 'Magento_Search':

Module 'Magento_Catalog':

Module 'Magento_Rule':

Module 'Magento_CatalogInventory':

Module 'Magento_Payment':

Module 'Magento_Quote':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_Widget':

Module 'Magento_Bundle':

Module 'Magento_Developer':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_SalesSequence':

Module 'Magento_Email':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GroupedProduct':

Module 'Magento_ImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_User':

Module 'Magento_Log':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Multishipping':

Module 'Magento_Newsletter':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Centinel':

Module 'Magento_ProductAlert':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_Rss':

Module 'Magento_GiftMessage':

Module 'Magento_CatalogSearch':

Module 'Magento_Shipping':

Module 'Magento_Tax':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Translation':

Module 'Magento_Ui':

Module 'Magento_UrlRewrite':

Module 'Magento_Integration':

Module 'Magento_Variable':

Module 'Magento_Wishlist':

Installing user configuration...

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_Directory':
Installing data..

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Theme':
Installing data..

Module 'Magento_Eav':
Installing data..

Module 'Magento_Customer':
Installing data..

**Comment by mazhalai** [comment]
@jialuni Can you please clear `cache` and `generation` folders within the var directory, and try again?

**Comment by jialuni** [comment]
@mazhalai I tried, first time it write me some integrity constraint violation. SO I tried another time with deleting
- /var/cache/*
- /var/generation/*
- sql : Truncate table


And same result again

**Comment by jialuni** [comment]
I solved my problem doing a git checkout / drop DB again...

**Comment by mazhalai** [comment]
@jialuni Did you have an existing installation of magento?

**Comment by jialuni** [comment]
No I just installed today, directly after a git pull. But I had a bug with "xdebug" just before this one, and de generation/cache/db deletion didn't solve the problem

**Comment by mazhalai** [comment]
@jialuni can you please try `bin/magento setup:uninstall` on your command line and then try running the wizard.

**Comment by jialuni** [comment]
Now everything is ok, so the uninstall command will not match bug I guess. But can I suggest a bigfix ? Disable or enlarge the xdebug 100 max looping in the setup/.htaccess via an `ini_set('max_nesting_level', 0);` or specify it have to do it manually during install process. Because lot of people have xdebgmug installed - it comes by default on Wamp Server by example.
