### ISSUE TITLE
M2.2.0 Admin Grid column ordering/positioning not working when single store mode set On

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#12070]
### Preconditions
1. Magento 2.2.0, no special setup
2. Installed as defaults, just one store/website.

### Steps to reproduce
1. Set single store mode to no.
2. Clear Cache
3. TRUNCATE ui_bookmark table
4. Go to sales order grid
5. Move Status column close to start of table
6. Refresh Sales order grid
7. Sales order grid should be presented with the same column ordering with Status column close to start of table
8. Confirm in MYSQL ui_bookmark table that the "current" bookmark for sales order grid contains "positions" data
9. Change single store mode to yes
10. Clear Cache
11. TRUNCATE ui_bookmark table
12. Go to sales order grid
13. Move Status column close to start of table
14. Refresh Sales order grid
15. Sales order grid does not remember column ordering
16. Confirm in MYSQL ui_bookmark table that the "current" bookmark for sales order grid does not contain "positions" data

INITIAL FINDINGS

When Magento creates an admin grid, it calls 

`Magento_Ui/js/grid/listing.js::initElement($item)`

for each column in the grid.

This function calculates totalCount to be the total number of columns available to be added and currentCount to be the current number of columns added. currentCount increases as each column is added, until currentCount==totalCount at which point it triggers the call to enable and apply positioning data for the columns, as as far as it knows, all columns have now been added.

When single store mode is set to yes the "Purchase Point" column is hidden and cannot be selected, however the  value of totalCount in the above function still includes the Purchase Point column. When the columns are added to the grid, the purchase point column is skipped and we reach the situation that we never get to the point of currentCount==totalCount and the positioning calls are never called. We always fall 1 column short of triggering the positioning calls.

Effectively we have

Single Store mode = yes
Visible columns = 19
totalCount = 20
Columns added to grid = 19
Positioning is not triggered as currentCount never reaches totalCount 

Single Store mode = no
Visible columns = 20
totalCount = 20
Columns added to grid = 20
Positioning is triggered

**Comment by magento-engcom-team** [comment]
@gwharton, thank you for your report.
We've created internal ticket(s) MAGETWO-83353 to track progress on the issue.

**Comment by xmav** [comment]
Same for products grid.
(Websites column is not visible with Single Store mode = Yes)

**Comment by VirtusB** [comment]
This issue still persists

**Comment by VirtusB** [comment]
@gwharton Have you figured out a temporary fix?

**Comment by gwharton** [comment]
Nope, and it is annoying the heck out of me at the moment. Seems that column positioning doesnt work regardless of whether single store mode is on or off now. This seems a recent change in the latest version.

**Comment by pavelshulgabi** [comment]
I'm working on #cd-balance

**Comment by magento-engcom-team** [comment]
@pavelshulga thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by pavelshulgabi** [comment]
[PR created](https://github.com/magento/magento2/pull/17512)

**Comment by gwharton** [comment]
Note, this issue is fixed by PR's #17512 (2.2) and PR #18405 (2.3)

There is another issue related to column positioning which is #17691 which is still unresolved.

**Comment by sidolov** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#18405 by @gwharton in 2.3-develop branch
Related commit(s):
 - [ed1f6a5ae5700eadb512c9ba792f86be431277ad](https://github.com/magento/magento2/commit/ed1f6a5ae5700eadb512c9ba792f86be431277ad)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#18561 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [7fd27fe87cbdd38607efb89df6c94a71b3302558](https://github.com/magento/magento2/commit/7fd27fe87cbdd38607efb89df6c94a71b3302558)

The fix will be available with the upcoming 2.2.8 release.
