### ISSUE TITLE
Multiple issue No adding to mini cart and wont checkout

### ISSUE THREAD

**Issue by Rockfordgun** [magento/magento2#12071]
Hi there guys 

Hope you can help.
I have been browsing around here trying to sort out some issues i have with magento 2.2.x.
I have a fresh install only testing with one product and im getting hurdle after hurdle.

My first issue is for some reason my mini cart isnt showing me that there is anything in no number shows up and it looks empty but when i go to /checkout/cart/ theres my order.

https://github.com/magento/magento2/issues/7550
I have tried the fix from tomasinchoo
But it doesnt seem to fix the issue

My second issue is my checkout ill add the product it goes to the cart click on checkout and i get a blank page.

https://github.com/magento/magento2/pull/11958/files
I tried the code changes aswell on this link but this doesnt seem to resolve the issue

### Preconditions
Running magento 2.2.x 
I have a custom theme that has been giving me mayor issues. I did contact them but they only saying its magento

**Comment by RomanKrut** [comment]
@Rockfordgun Hi. Did you enabled some options on admin  or change any settings when you installed fresh instance?

**Comment by Rockfordgun** [comment]
Hi Krut i didnt make any changes on the besides currency and then filled in all the general details but thats it

**Comment by magento-engcom-team** [comment]
@Rockfordgun, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
