### ISSUE TITLE
Magento 2.1.4 and Authorize.net error: "Please enter a valid card number"

### ISSUE THREAD

**Issue by marilena6** [magento/magento2#12080]
I am using Magento 2.1.4 on Php 7.0.12 and I face the following issue:

![authorizenet-invalid](https://user-images.githubusercontent.com/10513470/32500160-718dba2c-c3cc-11e7-992d-504dff9217ac.jpg)

I have searched everywhere, found this issue mentioned but nor resolved.

Please someone give an update on this?

**Comment by magento-engcom-team** [comment]
@marilena6 Please install fresh Magento, and try to reproduce this issue again.

**Comment by magento-engcom-team** [comment]
@marilena6, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9
