### ISSUE TITLE
Table Rates - Import feature not working

### ISSUE THREAD

**Issue by nileshtighare** [magento/magento2#1208]
Hello Team,

I found issue while importing the tablerates.csv file. This issue is generated in WAMP environment.
Error shows: The file "C:/Windows/TEMP/D:/wamp/tmp/php7FC1.tmp" doesn't exist.

![magento2-import-tablerates-issue](https://cloud.githubusercontent.com/assets/11942954/7255200/6d52ca14-e865-11e4-9837-3f3a37b524f1.png)

Thanks,

**Comment by wonderfan** [comment]
It is specific for your environment

**Comment by rganin** [comment]
It`s an environment issue, yor upload_tmp_dir in php.ini is broken and seems concatenated with windows default temp directory.

**Comment by vpelipenko** [comment]
@wonderfan, could you verify your PHP settings?

**Comment by phpdevgeek** [comment]
@nileshtighare have you solve this issue ? Right now i am facing same issue.

**Comment by wonderfan** [comment]
I fixed it in my environment.

**Comment by phpdevgeek** [comment]
@wonderfan in which way you have solved the error ? Can you please share your answer

**Comment by mombrea** [comment]
For me, (Debian 8, PHP5-FPM, Nginx) the tmp path seemed to append the vhost upload_tmp_dir to the system default path - i.e. /tmp/var/www/site.com/tmp/. The solution was to remove the vhost defined upload_tmp_dir and restart php. The system default (/tmp) was then used successfully. I re-enabled the vhost specific upload_tmp_dir afterward as this problem only occurred on the table rate import for me.
