### ISSUE TITLE
Inactive Catalog Price Rules - Magento EE 2.1.7

### ISSUE THREAD

**Issue by trufla** [magento/magento2#12086]
After adding Catalog Price Rules, they are inactive. In order to make them active it is required to schedule an update and run indexer:reindex. The problem is the Rule is still not active unless we change value of field is_active to 1 manually in table catalogrule. 

During the debugging I discovered that Collection is generated based on condition SELECT `main_table`.* FROM `catalogrule` AS `main_table` WHERE (main_table.created_in <= '1509719287') AND (main_table.updated_in > '1509719287'), where 1509719287 is a created_in value of random record in table staging_update. Could anyone explain it to me why this value is chosen as current version?

### Preconditions

1. Magento 2.1.7 EE
2. PHP 7.0
3. MySQL 5.7

### Steps to reproduce

1. Create a Catalog Price Rule
2. Schedule an update in order to make it active
3. Run indexer:reindex

### Expected result

1. Catalog Price Rule works

### Actual result

1. Catalog Price Rule doesn't work unless we change the value of "is_active" field manually to "1".

**Comment by magento-engcom-team** [comment]
Thank You for applying @trufla . The functionality You have mentioned above (Schedule New Update) is not available in Community Edition versions of Magento. Therefore please address Your issue directly to Magento Support.
