### ISSUE TITLE
Images added to a page using Admin, disappear from Frontend after logging out of Admin.

### ISSUE THREAD

**Issue by The-Krang** [magento/magento2#12088]
Clean install of version 2.2.  I am using the Open Source version, that was installed using Softaculous.

On a Linux-based web host.

In the cPanel, 1H Software PHP version Manager shows PHP version 7.1.

phpMyAdmin Web Server PHP shows up as version: 5.6.30. I don't know how to upgrade that yet.

No theme chosen for the store.

The only external thing I have is a module installed and enabled. It only affects the Order Success Page/ success.phtml.

**Steps taken to produce the error:**
I created an "About Us" page using Admin.
I add images/pictures anywhere in the page using Admin.  I also tried this with a block I made.
I look at the page from the frontend, in a new tab or window, and see the images.
I log out of Admin.
I refresh the frontend tab/window.
The images are gone, leaving only their descriptions.

**Expected result:**
The expected result is for the images to still be in place on the frontend.

**A separate question:**
I don't know where else to ask this question, so I will ask it here.  A while ago, I posted a bug that I found https://github.com/magento/magento2/issues/11529 , and I posted a follow-up question on it but I haven't seen a reply yet.  I also posted it on Magento Stack Exchange here https://magento.stackexchange.com/questions/198687/customer-sign-in-button-not-working-anymore .  I really would like to know how to fix the Sign In button problem so that I can move on.
So, how do I fix it?
Thank you very much.

**Comment by magento-engcom-team** [comment]
@The-Krang, thank you for your report.
We've created internal ticket(s) MAGETWO-83753 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @The-Krang

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@The-Krang, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
