### ISSUE TITLE
Product csv import > fail on round brackets in image filename

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#12084]
### Preconditions
1. Magento 2.2.0
2. PHP 7.1.11
3. Ubuntu 14.04.5 LTS

### Steps to reproduce
1. Create a product csv file

sku | ...other required columns... | base_image
--- | --- | ---
12345 | ...... | myimages/image(1).jpg

2. Create an image file with round brackets under: var/import/myimages/image(1).jpg
3. Goto Magento Backend > System > Import > Product
4. Set the import behaviour according to your csv file
5. Select the csv file to import
6. Set images file directory to: var/import/
7. Press "Check Data"

### Expected result
1. Data validated successfully 

### Actual result
1. Error message: "Wrong URL/path used for attribute image in row(s):"

**Comment by magento-engcom-team** [comment]
@Detzler, thank you for your report.
We've created internal ticket(s) MAGETWO-83445 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @Detzler 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by Detzler** [comment]
Will it be merged into the 2.1-branch, too?

**Comment by Detzler** [comment]
@okorshenko ?
