### ISSUE TITLE
Administration Grid is truncated (style issue)

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#12098]
# Preconditions

Ubuntu, Standard LAMP (Apache, MySQL, ....)
Magento 2.2.0-dev
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper
HEAD -> develop

# Steps to reproduce

Go to the administration login page
Click on Sales > Invoice (menu)

# Expected result
Invoice grid in the standard dimensions

# Actual result
Invoice grid has been truncated!

![selezione_081](https://user-images.githubusercontent.com/1553035/32539326-5b9362ce-c469-11e7-97ef-95fe74f332e1.png)

**Comment by magento-engcom-team** [comment]
@shinesoftware, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
See
![invoices_0891277983](https://user-images.githubusercontent.com/31669971/32541893-aef5bc40-c479-11e7-9ab2-1e96e32e08d4.png)
Please check this problem in incognito mode in your browser.

**Comment by shinesoftware** [comment]
I have discovered that the problem is a css class at **.admin__data-grid-wrap**
If I disable the overflow-x all works as well.

![selezione_080](https://user-images.githubusercontent.com/1553035/32597844-2c8fdf00-c538-11e7-8d8e-44636213e4db.png)

**Comment by magento-engcom-team** [comment]
@shinesoftware, thank for your response. Could You please try to reproduce Your issue on a clear fresh Magento install?

**Comment by shinesoftware** [comment]
I have discovered the problem in a custom extension! I would like to share my experience for other magento users. 

In my case **there is a custom setting of a custom extension for the invoice listing grid**.

> app/code/Company/Dropbox/view/adminhtml/ui_component/sales_order_invoice_grid.xml

    <listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    
        <container name="listing_top">
            <massaction name="listing_massaction">
                <action name="send_dropbox">
                    <argument name="data" xsi:type="array">
                        <item name="config" xsi:type="array">
                            <item name="type" xsi:type="string">send_dropbox</item>
                            <item name="label" xsi:type="string" translate="true">Send to Dropbox</item>
                            <item name="url" xsi:type="url" path="dropbox/invoice"/>
                        </item>
                    </argument>
                </action>
            </massaction>
        </container>
    </listing>

I have solved in this way:

    <listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
        <listingToolbar name="listing_top">
            <massaction name="listing_massaction">
                <action name="send_dropbox">
                    <argument name="data" xsi:type="array">
                        <item name="config" xsi:type="array">
                            <item name="type" xsi:type="string">send_dropbox</item>
                            <item name="label" xsi:type="string" translate="true">Send to Dropbox</item>
                            <item name="url" xsi:type="url" path="dropbox/invoice"/>
                        </item>
                    </argument>
                </action>
            </massaction>
        </listingToolbar>
    </listing>


thanks for your help!

**Comment by magento-engcom-team** [comment]
@shinesoftware, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
