### ISSUE TITLE
Exception: Warning: array_replace_recursive(): recursion detected in vendor\magento\module-config\App\Config\Type\System.php on line 152

### ISSUE THREAD

**Issue by hirensutariya1** [magento/magento2#12097]
I have installed fresh magento2.2 and i try to configure youtube api key when i click on save config i got 
Exception: Warning: array_replace_recursive(): recursion detected in vendor\magento\module-config\App\Config\Type\System.php on line 152.
### Preconditions

Magento Version : 2.2.1
PHP Version : 7.0.4
SQL Version : 5.7.11

### Steps to reproduce
Change in configuration and save it

### Expected Result
Save successfully

### Actual Result
Exception: Warning: array_replace_recursive(): recursion detected in C:\wamp64\www\m22\vendor\magento\module-config\App\Config\Type\System.php on line 152 in C:\wamp64\www\m22\vendor\magento\framework\App\ErrorHandler.php:61 Stack trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'array_replace_r...', 'C:\\wamp64\\www\\m...', 152, Array) #1 C:\wamp64\www\m22\vendor\magento\module-config\App\Config\Type\System.php(152): array_replace_recursive(Array, Array) #2 C:\wamp64\www\m22\vendor\magento\framework\App\Config.php(131): Magento\Config\App\Config\Type\System->get('default/web/sec...') #3 C:\wamp64\www\m22\vendor\magento\framework\App\Config.php(80): Magento\Framework\App\Config->get('system', 'default/web/sec...') #4 C:\wamp64\www\m22\vendor\magento\framework\App\Config.php(93): Magento\Framework\App\Config->getValue('web/secure/use_...', 'default', NULL) #5 C:\wamp64\www\m22\vendor\magento\module-store\Model\HeaderProvider\Hsts.php(48): Magento\Framework\App\Config->isSetFlag('web/secure/use_...') #6 C:\wamp64\www\m22\vendor\magento\framework\App\Response\HeaderManager.php(41): Magento\Store\Model\HeaderProvider\Hsts->canApply() #7 C:\wamp64\www\m22\vendor\magento\framework\Interception\Interceptor.php(121): Magento\Framework\App\Response\HeaderManager->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor)) #8 C:\wamp64\www\m22\vendor\magento\framework\Interception\Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}() #9 C:\wamp64\www\m22\generated\code\Magento\Framework\App\Response\Http\Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array) #10 C:\wamp64\www\m22\vendor\magento\framework\App\Http.php(185): Magento\Framework\App\Response\Http\Interceptor->sendResponse() #11 C:\wamp64\www\m22\vendor\magento\framework\App\Http.php(156): Magento\Framework\App\Http->handleDeveloperMode(Object(Magento\Framework\App\Bootstrap), Object(Exception)) #12 C:\wamp64\www\m22\vendor\magento\framework\App\Bootstrap.php(261): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception)) #13 C:\wamp64\www\m22\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) #14 {main}

**Comment by magento-engcom-team** [comment]
@hirensutariya1, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by diazwatson** [comment]
Same issue here after upgrade to 2.2.1

**Comment by magento-engcom-team** [comment]
@hirensutariya1, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by MindaugasSV** [comment]
Same issue here after upgrade to 2.2.1

**Comment by MindaugasSV** [comment]
Temporary fix (**warning**: you are editing core files):
open file: /vendor/magento/module-config/App/Config/Type/System.php
replace **array_replace_recursive** to **@array_replace_recursive** in lines 152 and 158

**Comment by nobodypb** [comment]
I get also this error when I try to upgrade to 2.2.1
After `composer install` I execute `bin/magento setup:upgrade` and this error happens. 
As this has something to do with the store config, I tried removing diffrent entries in 'core_config_data'.
I figured out, that the error can be resolved by deleting all config datasets with scope set to 'websites'
`DELETE FROM core_config_data WHERE scope = 'websites';`
I have no idea why, but afterwards everything works fine.

**Comment by KevinMace** [comment]
We've encountered the same issue whilst upgrading from 2.1.10 to 2.2.1, during the setup:upgrade process.

``
Warning: array_replace_recursive(): recursion detected in /mnt/project/vendor/magento/module-config/App/Config/Type/System.php on line 158
``

This stopped the setup:upgrade process from completing, leaving the application in a broken state.

**Comment by barbazul** [comment]
Same error on a fresh install from Github repo.

@MindaugasSV 's fix makes the store "usable". Not sure of the potential side effects

**Comment by bydrei** [comment]
Don't do what @nobodypb did, that doesn't really fix the warning. It just prevents the code from going into the line where the warning is thrown.

Also this is just a warning, not really an error.

**Comment by jzahedieh** [comment]
I have also faced this issue whilst upgrading from 2.1.9 => 2.2.2

I have tracked down the cause to having entries in the `core_config_data` table where any entry of `websites` `scope` doesn't have any `default` value in in the first two parts of the `path`.

i.e this works correctly:

![image](https://user-images.githubusercontent.com/2098908/34297726-c33940f4-e711-11e7-8054-24b8f9ad5430.png)

As does:

![image](https://user-images.githubusercontent.com/2098908/34297756-ef10ce54-e711-11e7-943f-4e0494dbed73.png)

But the following triggers the issue:

![image](https://user-images.githubusercontent.com/2098908/34297782-0f8fea16-e712-11e7-9285-5e2dd67ae2c6.png)

![image](https://user-images.githubusercontent.com/2098908/34297801-2aea577e-e712-11e7-9def-423793de4874.png)

Here is the script I use for testing the issue, I just put it in the webroot:

    <?php
    use Magento\Framework\App\Bootstrap;

    require __DIR__ . '/app/bootstrap.php';
    $bootstrap = Bootstrap::create(BP, $_SERVER);
    error_reporting(E_ALL);
    ini_set('display_errors', 1);

    $obj = $bootstrap->getObjectManager();
    $state = $obj->get('Magento\Framework\App\State');
    $state->setAreaCode('frontend');

    /* @var $system \Magento\Config\App\Config\Type\System*/
    $system = $obj->get('Magento\Config\App\Config\Type\System');

    var_dump($system->get('default/z/y/x'));

I batch deleted website config entries until I could track down the actual ones that were causing issues, in our case they were redundant entries so we can just delete them, otherwise all you have to do is to create a default entry with a `NULL` value.

I was looking to try and create a query but I've not quite got there yet, I've split out the path values I just need a way of comparing the websites without defaults:

	SELECT 
	`config_id`, `scope`, `scope_id`, 
	substring_index(substring_index(`path`,'/',1), '/', -1) as path_1,
	substring_index(substring_index(`path`,'/',2), '/', -1) as path_2,
	substring_index(substring_index(`path`,'/',3), '/', -1) as path_3,
	`value`,
	count(*) as counter
	FROM `core_config_data`
	group by path_2, scope
	ORDER BY `config_id` DESC

**Comment by nobodypb** [comment]
@ferrazzuk deleting the config with the websites scope was never intended as a "fix" just to give a hint for tracking down the issue, like @jzahedieh finally did. Sorry for not making that clear. In my case I was able to workaround, because I could safely delete those entries. Therefore I had no reason for going further into it.

**Comment by danmentzer** [comment]
I got the same warning from upgrading from 2.2.0  to 2.2.2 via command line.
The warning comes up right when running php bin/magento setup:upgrade

**Comment by KevinMace** [comment]
The solution by @jzahedieh worked perfectly for me. I wrote a quick command line task to fix any entries missing a default value.

**Comment by zaheerbadi** [comment]
@KevinMace Can you please give us script to resolve this issue?
Thanks

**Comment by KevinMace** [comment]
@zaheerbadi I've just created this gist with my solution. It might not be the most elegant solution, however it did the job :) https://gist.github.com/KevinMace/214d46b3505739120a908b6be13c8fd1 

You'll need to add the console command to your di.xml

**Comment by zaheerbadi** [comment]
Thanks @KevinMace I have checked it in DB but all value is set to `null` still not working :(

**Comment by nobodypb** [comment]
Based on the findings of @jzahedieh I wrote a MySQL query, that should insert the missing default entries.
Don't forget to backup your 'core_config_data' table first.
```
INSERT INTO `core_config_data` (`scope`, `scope_id`, `path`, `value`)
	SELECT 'default', 0 , `path`, NULL
	FROM `core_config_data`
	WHERE `scope` <> 'default' AND substring_index(`path`,'/',2) NOT IN(
		SELECT DISTINCT
		substring_index(`path`,'/',2)
		FROM `core_config_data`
		WHERE `scope` = 'default')
	GROUP BY substring_index(`path`,'/',2)
```

I also want to add that although this only gives a warning, it creates major problems because it terminates the command `php bin/magento setup:upgrade`. Therefore it isn't possible to perform an complete upgrade.

**Comment by zaheerbadi** [comment]
@nobodypb Same issue nothing changed even after run the above query.

**Comment by nobodypb** [comment]
@zaheerbadi you could try to run the following query, which creates a default value for every existing path.
```
INSERT INTO `core_config_data` (`scope`, `scope_id`, `path`, `value`)
	SELECT 'default', 0 , `path`, NULL
	FROM `core_config_data`
	WHERE `scope` <> 'default' AND `path` NOT IN(
		SELECT DISTINCT `path`
		FROM `core_config_data`
		WHERE `scope` = 'default')
```

In my case the missing default entries started all with path `advanced/modules_disable_output/`.
I also managed to resolve this issue by saving the config at STORES>Configuration>Advanced->Advanced prior to updating.

If none of these solutions fixes the problem for you, the cause is probably another one. I that case my suggestion is to compare all keys of the two arrays that coudn't be merged. It seems like that warning occurs if there are keys in the second array, that don't exist in the first. Although this should be fine according to the manual.

**Comment by ozmuhsin** [comment]
FYI:
The issue happens if you run setup:di:compile out of the webroot i.e 

Steps:
1)$(which php) <webroot_path>/bin/magento setup:di:compile

Results: FAIL with warning

Result: PASS 
cd <webroot_path> && $(which php) ./bin/magento setup:di:compile

I hope this helps.

**Comment by jernejh** [comment]
I encoutered the issue when upgrading from 2.2.1 to 2.2.3. 

@MindaugasSV temporary fix allows php bin/magento setup:upgrade to finish successfully, and also allows changing the configuration of the store in the backend without getting the same error. But still, a more holistic (and safe?) solution to the problem would be neat.

**Comment by Rane2k** [comment]
Based on the work of @jzahedieh above we have created the following SQL:

```sql
SELECT 
	CONCAT(substring_index(substring_index(`path`,'/',1), '/', -1), '/', substring_index(substring_index(`path`,'/',2), '/', -1)) as possibly_affected_path 
FROM `core_config_data`
WHERE 
	scope = 'websites'
	AND CONCAT(substring_index(substring_index(`path`,'/',1), '/', -1),'/',substring_index(substring_index(`path`,'/',2), '/', -1)) 
	 NOT IN (
	 	SELECT CONCAT(substring_index(substring_index(`path`,'/',1), '/', -1), '/' ,substring_index(substring_index(`path`,'/',2), '/', -1)) as path12    
		FROM `core_config_data`    
		WHERE scope = 'default'    
		GROUP BY path12
	)
GROUP BY possibly_affected_path;
```

This identifies the affected config paths, you can then assemble the missing default values.

Just in case anyone runs into this issue.
(it´s not elegant but it helped us fix the problem)

**Comment by EliasKotlyar** [comment]
I can also reproduce this issue. Upgrading from 2.1 to latest 2.2.3.

Many thanks @Rane2k for his query!

**Comment by magento2dev** [comment]
I can also reproduce this issue on 2.2.3.

**Comment by brijeshjp2006** [comment]
if ($scopeType === 'default') {
            if (!isset($this->data[$scopeType])) {
                $this->data = @array_replace_recursive($this->loadDefaultScopeData($scopeType), $this->data);
            }
            return $this->getDataByPathParts($this->data[$scopeType], $pathParts);
        }
        $scopeId = array_shift($pathParts);
        if (!isset($this->data[$scopeType][$scopeId])) {
            $this->data = @array_replace_recursive($this->loadScopeData($scopeType, $scopeId), $this->data);
        }

**Comment by brijeshjp2006** [comment]
write @ before array_replace_recursive function and run setup:upgrade command.
It is working for me. after do all Research
Thanks,
Jugal Kishor

**Comment by brijeshjp2006** [comment]
line no 152 and 158 in vendor\magento\module-config\App\Config\Type\System.php

**Comment by romantomchak** [comment]
The same issue on 2.2.3. I even cannot install Magento from project which was created from scratch.

**Comment by fones** [comment]
Update from PHP 7.0.1 to 7.1.7 fixes the issue.

**Comment by lumnn** [comment]
I had similar issue on recent PHP (7.1.22) and Magento (2.2.6)

I've found out that using placeholders for env variables causes this warning to be triggered.

I had store configured in config.php and env variables setup like:

```
CONFIG__WEBSITES__MYSITE__UNSECURE__BASE_URL=http://mysite.magento2.test/
CONFIG__WEBSITES__MYSITE__SECURE__BASE_URL={{unsecure_base_url}}
```

Edit:
It appears that having any values in any env variable for a site causes this error to appear
