### ISSUE TITLE
Authorization.net response show  <H3>The following errors have occurred.</H3>(253) , not getting sucess message.

### ISSUE THREAD

**Issue by brijeshcody** [magento/magento2#12096]
Magento version 2.1.3

### Steps to reproduce

1.Order place via Authorization.net payment and Payment cut and order show in order history tab but transaction id and success message not getting..i get only below response in html mode.

transact.dll :response
<HTML><BODY><H3>The following errors have occurred.</H3>(253) Your order has been received. Thank you for your business!<BR></BODY></HTML>

Please Help me what is the issue or what's wrong?
Thanks in advance.

**Comment by magento-engcom-team** [comment]
@brijeshcody, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
Hi @brijeshcody please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
