### ISSUE TITLE
magento 2.1.9 Cart Line Items not showing in paypal page

### ISSUE THREAD

**Issue by amithlalalj** [magento/magento2#12094]
**Preconditions**
Mgento2.1.9
PHP Version 7.0.25

**Steps to reproduce**
Checkout With paypal pro(all in one solution)
The page will redirect to paypal account page there we can see the product details 
after successful payment the customer and merchant will receive an email from paypal which contail all detail about the purchace including the products details

**Expected result**
The paypal page should show the  product details like product name sku price color size(varients) etc
The payment conformation mail from paypal also contain the product details

**Actual result**
The paypal details page only shoing the product name price and total it is not shoing the products varients like sku,color,size
The conformation mail from paypal also not contain any detail about product it is only containthe payment amount 

Note:we have enable the Cart Line Items in magento backend

**Comment by magento-engcom-team** [comment]
@amithlalalj , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by amithlalalj** [comment]
**Magento Version :2.1.9**
On checkout with paypal pro(Paypal all in one) paypal details page not showing the product details in the cart the paypal only display the product name and price there is no product sku and products varients like color size which is shown in the mini cart
After placing an order with paypal the customer will receve an email from paypal which contain the order details in our case the payment details mail from paypal not containing any product details actually it should show the product details in mail 

We have enable the "Transfer Cart Line Items" athe the back end of magento

**Comment by YevSent** [comment]
@amithlalalj, this is expected behavior, Magento sends only item name, quantity and price.

Also, PayPal supports the limited list of product attributes (see https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/#deprecated-payment-details-item-type-fields), there are not separated fields for sku, color, etc.

**Comment by magento-engcom-team** [comment]
@userName, thank you for your report.

**Comment by magento-engcom-team** [comment]
@amithlalalj , thank you for your report.
We not able provide the expected behavior on the page PayPal.
