### ISSUE TITLE
[Update to 2.2.1] - Can not access website.

### ISSUE THREAD

**Issue by kienmba** [magento/magento2#12093]
### Preconditions

1. PHP 7.0.6
2. MySQL 5.0.12

### Steps to reproduce

1. composer require magento/product-community-edition 2.2.1 --no-update
2. composer update
3. rm -rf var/di var/generation
4. php bin/magento cache:flush
5. php bin/magento setup:upgrade
6. php bin/magento setup:di:compile
7. php bin/magento indexer:reindex
8. php bin/magento setup:static-content:deploy -f
==>> Done!

### Expected result

Website is working!

### Actual result

1. The frontend: 'Not show content'. Console: 'Uncaught ReferenceError: jQuery is not defined'
2. The backend: 'This page isn’t working'

**Comment by kienmba** [comment]
Look forward to a response or a solution from the community.
Thank you so much!

**Comment by magento-engcom-team** [comment]
@kientran175 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by kienmba** [comment]
@magento-engcom-team , thank you for reply.
I developed the theme, my current version is 2.2.0. I upgraded to 2.2.1 and had trouble getting backend and frontend without any content!
I upgraded with composer follow step have provided.

**Comment by ziiljuks** [comment]
For 2.2 you have to delete different folders.
I usually delete:

- var/page_cache
- var/cache 
- var/composer_home
- generated/code
- generated/metadata
- var/view_preprocessed

Maybe it helps.

**Comment by magento-engcom-team** [comment]
@kientran175, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
