### ISSUE TITLE
Compilation not generating factories declared in di.xml

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#12100]
Hello everybody, we are facing an issue related to compilation : 

Precondition is the following : 

- **Production mode** 
- **Read only /var/generation/ (or /generated) directory** (which is the official recommendation afaik).
- **Some factories declared only in di.xml**

It seems that Magento does **not** generated those factories since they are not used in any ```__construct()``` call but only defined in di and injected into some classes.

In fact this is happening in our [elasticsuite](http://github.com/smile-sa/elasticsuite) where we have something like a "meta factory" defined like this in di : 

```
<type name="Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory">
        <arguments>
            <argument name="factories" xsi:type="array">
                <item name="boolQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\BooleanFactory</item>
                <item name="filteredQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\FilteredFactory</item>
                <item name="nestedQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\NestedFactory</item>
                <item name="notQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\NotFactory</item>
                <item name="missingQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\MissingFactory</item>
                <item name="termQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\TermFactory</item>
                <item name="termsQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\TermsFactory</item>
                <item name="rangeQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\RangeFactory</item>
                <item name="matchQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\MatchFactory</item>
                <item name="commonQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\CommonFactory</item>
                <item name="multiMatchQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\MultiMatchFactory</item>
                <item name="functionScore" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\FunctionScoreFactory</item>
            </argument>
        </arguments>
    </type>
```

### Preconditions

1. Magento version 2.1 and 2.2
2. PHP 7.x

### Steps to reproduce

1. Declare some factories in DI (non existing factories, that should get generated)
2. Set production mode
3. Ensure /generated or /var/generation is read only
4. Navigate to the website

### Expected result

1. All is working properly 

### Actual result

1. It seems like Magento tries to generate the factory on the fly (so I'm sure it was not generated during compilation)
2. and throws an error like this : 

```
{"0":"The specified "/app/generated/code/Smile/ElasticsuiteCore/Search/Request/Query/BooleanFactory.php.13402" file could not be written Warning!file_put_contents(/app/generated/code/Smile/ElasticsuiteCore/Search/Request/Query/BooleanFactory.php.13402):
```

See our internal issue here for more details : https://github.com/Smile-SA/elasticsuite/issues/583

**Comment by magento-engcom-team** [comment]
@romainruaud, thank you for your report.
We've created internal ticket(s) MAGETWO-84200 to track progress on the issue.

**Comment by moloughlin** [comment]
For anyone else who stumbles upon this (still an issue in _at least_ 2.2.x); we were able to work around it by adding some additional hinting for the DI compilation process. E.g. from the example in the original issue:

```
<type name="Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory">
    <arguments>
        <argument name="factories" xsi:type="array">
            <item name="boolQuery" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\Query\BooleanFactory</item>
        </argument>
    </arguments>
</type>
```
Complement this with an additional type definition:
```
<type name="Smile\ElasticsuiteCore\Search\Request\Query\BooleanFactory" />
```

Though I don't see any reason why setup:di:compile couldn't traverse <arguments> nodes to determine which Factory classes need to be generated - will try to add a PR to address that in the near future unless someone beats me to it.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
