### ISSUE TITLE
Mview changelog tables are gone when they shouldn't be

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#12104]
### Preconditions

1. Magento 2.1.9 (maybe other versions as well)

### Steps to reproduce

1. Run `php bin/magento ind:show` 
2. If mode is update on save ('realtime'), run `php bin/magento ind:set-mode schedule`
3. Run `echo "show tables like '%_cl'" | mysql magentodatabasename`
4. `_cl` tables should exist for every indexer
5. Run `php bin/magento ind:set-mode realtime`
6. `_cl` tables should still exist
7. Run `php bin/magento ind:set-mode schedule` (you should see XXX was changed from 'Update on Save' to 'Update by Schedule')
8. Check _cl tables; they should still exist
9. Run `php bin/magento ind:set-mode schedule` again (you should see 'XXX has not been changed')

### Expected result

1. The _cl tables should never be removed once they exist; not even when you switch to realtime. Because when you switch to realtime and back to schedule, mview_state still has a version number which will be higher than the value in the _cl table (since that would be 0 for a new empty table).

### Actual result

1. Check _cl tables; they are now gone
2. Panic! My _cl tables are gone while indexer mode is on schedule!

**Comment by magento-engcom-team** [comment]
Hello @peterjaap. Thanks for reporting. We can not reproduce Your issue. No matter how tried the _cl tables permanently remained  there after they had been created. Your steps to reproduce are really clear. Seems there are some other crucial factors causing this issue. Could You please provide us some additional information You deem as some that could influence the issue.

**Comment by peterjaap** [comment]
@pascaladriaansen found a similar issue and found the culprit to be a Mirasvit extension, see here; https://github.com/magento/magento2/issues/5836#issuecomment-313318480

**Comment by peterjaap** [comment]
See also https://github.com/magento/magento2/issues/10204
