### ISSUE TITLE
Customer group pricing for grouped products not working sensibly

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#12114]
### Preconditions
1. Magento OS 2.2

### Steps to reproduce
1. Create additional customer group and assign customer to group.
2. Create a group product with two simple products
3. Using Advanced Pricing, assign different prices to the group for each simple, with quantity set to 1 (minimum allowed)
4. Login as customer and view grouped product.
5. Add product to cart.

### Expected result
1. At step 4, pricing should show as per group prices.
2. At step 5, product should be added to cart with group price.

### Actual result
1. At step 4, pricing shows as base price, not group price.
2. At step 5, item is added to cart with correct group price.

The issue is that group and tier pricing have been combined in M2. Was called Tier price in M2 but now is Customer Group price in M2.2. However, tier pricing requires a minimum quantity of 1. With a typical group product setup, with initial simple product quantity set to 0, it's not hitting the tier/group price when the group product is displayed, hence base price is shown instead of customers group price. Setting the default group product quantity to 1 shows the correct prices. However, this is not a solution. Instead of selecting products and quantity of each required, a customer must then set quantity to 0 for those not required, which is bad practice for any store.

Given tier/group pricing has been combined, one solution might be to allow an advanced price with quantity of 0 instead of 1. Thus triggering the group price (instead of tier price) when the grouped product is initially displayed with 0 quantity for each simple product.

**Comment by magento-engcom-team** [comment]
@adamlavery, thank you for your report.
We've created internal ticket(s) MAGETWO-83514 to track progress on the issue.

**Comment by meezin** [comment]
@adamlavery Hi, There. I have been struggling with this problem so i'm about to use front-end trick : To show price(standard price) as default and additionally, i will add the tier price for a customer group based on a customer logging in currently, and i will show standard price with text-decoration : line-through . I don't understand why Magento2 team merged this function with the tier price. I assume that there would be Magento shops which have shown a discount price with using group price function on M1 product detail page.

**Comment by adamlavery** [comment]
@meezin, Hi. Does this mean you're creating a module to fetch and display the group price? I can understand why tier and group pricing was combined as they are much the same thing. The issue is using a quantity of 1 to differentiate a base group price from tier prices.

As a test, I tried manually changing the quantity on a group price to 0 in the database, bypassing the admin restriction. This then displayed a correct tier price for a quantity of 0, alongside the base price. This suggests that M2 is hard-coded to use a quantity of 1 to decide it's a group rather than tier price and display appropriately. 

This further suggests that it should be possible to override this to use a 0 quantity as the determiner for a group vs tier price (which to my mind makes more sense). That would require a module override to allow 0 quantity on Advanced Pricing and detect 0 quantity as the group price when displaying.

At this stage, we're more focussed on extension and 3rd party integration testing to ensure the feasibility of M2 for the business. Once the full project gets the go-ahead, then if Magento haven't released a solution, this is something I will look to implement.

**Comment by adamlavery** [comment]
Of course, changing the group price determiner to 0 now would require the addition of a prices setting to avoid breaking existing installations where 1 determines the group price and works ok for simple products. This would default to 1 but could be changed to 0 for new installations to correctly handle Grouped Products.

**Comment by langstn** [comment]
@adamlavery or @magento-engcom-team Howdy! Any workaround or updated fix for this issue? This is the last of our bugs we're trying to squash before our launch. I'd be glad to contribute test cases if it would help.

**Comment by adamlavery** [comment]
Nothing from Magento. In our case, we want pricing tied to groups and store, hence we're using BSS Commerce Multi Store View Pricing module, which is working fine for our needs.

**Comment by isitnikov** [comment]
Will be fixed in scope of internal ticket MAGETWO-94916.

**Comment by ghost** [comment]
@isitnikov  can you share internet ticket link

**Comment by ghost** [comment]
any one have solution for this?

**Comment by chrisseamanunityonline** [comment]
@langstn @magento-engcom-team  Looking to kill the last of our bugs before launch, Also looking for a solution to this issue.

**Comment by adamlavery** [comment]
@magento-engcom-team have you fixed this? We recently upgraded from 2.2.3 to 2.2.5 and now tier pricing is behaving differently - and messed up our store prices! 

To get around this issue, we used MultiStore View Tier pricing from BSS Commerce. This allowed us to enter tier prices with a quantity of 0, resulting in the initial quantity on grouped products being 0. Now it's behaving completely differently.

So has this been fixed without telling anyone? There's no point in linking to internal tickets which the rest of us cannot see or follow!

**Comment by ghost** [comment]
@magento-engcom-team any update ?

**Comment by magento360** [comment]
@magento-engcom-team  can you provide solution asap. 
other similar issue #18577 
This issue is forcing us to migrate from magento.
looking forward response on the same.

**Comment by nicobatty** [comment]
@adamlavery I haven't tried on grouped products, but you maybe try my PR that fix the issue for simple and configurable products: #18784

**Comment by Dharmeshvaja91** [comment]
@adamlavery i am not able to reproduce the issue, it seems like already solved in 2.2.6
