### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by Obscurefrey** [magento/magento2#1211]
I have successfully installed magento 2, i m using windows 7, but now i m unable to login into the panel. it dont show wrong password , just jump back into the login page, pls help me out..

**Comment by vpelipenko** [comment]
Do you get some JS error or broken styles? We have similar issue here https://github.com/magento/magento2/issues/1180.

**Comment by Obscurefrey** [comment]
my page theme is perfectly fine.. there are no JS error or broken styles.. i just cant log into my panel..

**Comment by joanhe** [comment]
@Obscurefrey What browser do you use? Do you have localhost in your url?

**Comment by Obscurefrey** [comment]
i tried it with chrome, mozzila and internet explorer, and yes i have localhost or 127.0.0.1 in my url

**Comment by TapaniAla** [comment]
Currently Magento2 installation doesn't seem to  copy all files (like css) so you have to execute this command inside the magento folder root:  php -f dev/tools/Magento/Tools/View/deploy.php. This script has a time out issue so you have to increase set_timeout from the default 30 seconds to 300 seconds. Please verify from the apache2 error log that the script was run without problems.  Some further modifications are also needed but unfortunately I didn't write them down.

**Comment by joanhe** [comment]
@Obscurefrey Try to avoid using localhost or 127.0.0.1. Your issue looks like the same issue of #1180. Try TapanlAla's suggestion above. Please let us know if you still experience problem.

**Comment by Obscurefrey** [comment]
the problem is solved.. the issue is with antivirus.. plss turn off ur antivirus while installing magento 2..

**Comment by joanhe** [comment]
@Obscurefrey I am glad you got issue resolved. Thanks for letting us know.
