### ISSUE TITLE
Missing cascade into attribute set deletion

### ISSUE THREAD

**Issue by asrenzo** [magento/magento2#12110]
### Preconditions

1. Create a custom attributes set
2. Attach some products to this attributes set

### Steps to reproduce

1. Got to attributes set admin page
2. Delete your custom attributes set
3. Confirm you want to remove attached products also

### Expected result

1. Table url_rewrite should be cleaned from references to removed products
2. A new product named like an old one should be insertable via API or admin interface

### Actual result

1. Impossible to add a new product named like an old one because a request_path with the same value as computed already exists in table url_rewrite;

**Comment by magento-engcom-team** [comment]
@asrenzo, thank you for your report.
We've created internal ticket(s) MAGETWO-83507 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @asrenzo 
We are closing this ticket as fixes are already delivered with the linked PRs.

Thank you for collaboration.

**Comment by asrenzo** [comment]
Hi,
Sounds like this was not fixed in 2.1.x version.
Don't you plan to do it ?
Regards,
Laurent
