### ISSUE TITLE
Merge JS is counter-intuitive

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12126]
### Preconditions
1.  Magento 2 latest, or any really 

### Steps to reproduce
1. Start in developer mode
2. Enable JS merge, bundling, minification or some combination
3. Save Config
4. Note that no JS files were generated, ok
5. Deploy static files, still no JS
6. Deploy production mode
7. Now save the JS merging config page/settings
8. Suddenly merged JS files appear

### Expected result

I expected that when initially saving that option it would generate the files. And hope that static content deploy would generate them.

### Actual result
1.  Its not clear at all that in developer mode merged JS won't be generated
2. It appears that static content deploy does not generate merged JS files ?
3. If you enable production mode and don't save the config again, merged JS files may not be generated

To me this is a user flow problem, because someone would go in and save that configuration then never actually check for the merged files.

**Comment by magento-engcom-team** [comment]
@sylink, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
