### ISSUE TITLE
 We can't add this item to your shopping cart right now. Magento 2.2.1

### ISSUE THREAD

**Issue by omargits** [magento/magento2#12129]
Magento 2.2.1 fresh installation with composer and also with zip but having same issue. once you logged in you cant add to cart product. 

**We can't add this item to your shopping cart right now.**
from var/log here is information
[2017-11-09 07:01:51] main.CRITICAL: Validate class not found from basename 'Magento\Framework\Validator\EmailAddress' {"exception":"[object] (Zend_Validate_Exception(code: 0): Validate class not found from basename 'Magento\\Framework\\Validator\\EmailAddress' at /var/customers/webs/magento2/vendor/magento/zendframework1/library/Zend/Validate.php:244)"} []

### Preconditions

1. Magento 2.2.1
2. **PHP Version**
PHP 7.0.19 (cli) (built: May 15 2017 10:28:51) ( NTS )
**MYSQL**
Server version: 5.6.36

### Steps to reproduce

1. Logged in as customer
2. try to add product from product detail page
3. error produce 

### Expected result

1. must add to cart normally

### Actual result

1. [Screenshot, logs]
https://www.screencast.com/t/lffU7G5TM
[2017-11-09 07:01:51] main.CRITICAL: Validate class not found from basename 'Magento\Framework\Validator\EmailAddress' {"exception":"[object] (Zend_Validate_Exception(code: 0): Validate class not found from basename 'Magento\\Framework\\Validator\\EmailAddress' at /var/customers/webs/magento2/vendor/magento/zendframework1/library/Zend/Validate.php:244)"} []

**Comment by magento-engcom-team** [comment]
@omargits, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.1

**Comment by omargits** [comment]
I installed same version on second server it producing there also with same process. in google there are many links exist which also reporting this issue but that mostly for 2.2. one thing can you guide me so i can detail checking and shared with more detail with you

**Comment by fremeni** [comment]
Same problem here.

**Comment by eleongkind** [comment]
Same here

**Comment by webmasterpaula** [comment]
Same here. Magneto 2.2.2. Please help me.

**Comment by EmilyPepperman** [comment]
Same here with 1 product not all of them ... do you with the same problem also have MageWorx  extension called Advanced Product Options by chance?

**Comment by seanscott49** [comment]
Well, this is what worked for me. It was an issue with a Third Party Module. Update all of your modules. If it still persists, then disable them one by one until you figure out which one is causing the issue. For me, it was one of my Amasty Modules. Once I updated, all was good.

**Comment by bmzero** [comment]
I had this same issue on 2.2.5. It was related to an outdated Amasty extension. We weren't using it anyway, so a quick disable of the extension, recompile, and good to go.

**Comment by dribblecastle** [comment]
Which Amasty module @seanscott49 and @bmzero?  I have a few installed and run into this issue every few weeks out of the blue.

**Comment by bmzero** [comment]
> Which Amasty module @seanscott49 and @bmzero? I have a few installed and run into this issue every few weeks out of the blue.

It was actually Amasty Base, but related to Shipping Rules.

**Comment by dribblecastle** [comment]
Thanks for the quick response.  Do you recall if your problem was consistent with this error message or did it go away when you did a Flush of the Magento cache?  For me, it occurs at random and the cache flush fixes it.
