### ISSUE TITLE
Types are not getting selected When image POST call via rest API

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#12128]
Preconditions

Magento 2.2.1
Steps to reproduce

Making POST Call to /V1/products/{SKU}/media
with POST data:

{
  "entry": {
    "media_type": "image",
    "label": "test1",
    "position": 0,
    "disabled": 0,
    "types": [
      "thumbnail"
    ],
    "file": "test.gif",
    "content": {
      "base64_encoded_data": "Endcoded Data",
      "type": "image/gif",
      "name": "test.gif"
    }
  }
}

Expected result

It should select thumbnail role in magento2 product record.
Actual result
![image](https://user-images.githubusercontent.com/6079017/32592292-1e30da0c-c549-11e7-8b44-2de834869dd9.png)
Nothing is getting selected.

Please help.

**Comment by magento-engcom-team** [comment]
@ankursachdeva11 We can not reproduce your issue. We assume that you are using the wrong POST request. 
Here is our POST request test-magento.com/index.php/rest/all/V1/products/Test Product/media
with POST data:
{"entry":{
"media_type": "image",
"label": null,
"position": 1,
"disabled": 0,
"types":[
"image",
"small_image",
"thumbnail",
"swatch_image"
],
"file": "test.jpg",
  "content": {
      "base64EncodedData": "Endcoded Data",
      "type": "image/jpg",
      "name": "test.jpg"
    }
}
}
You need to use "all", "default" or other custom storeview in POST request for the roles(for image) to apply the selected storeview.

**Comment by ankursachdeva11** [comment]
Thanks
