### ISSUE TITLE
Error message for user with restricted user role

### ISSUE THREAD

**Issue by Ruslan05** [magento/magento2#12149]
### Preconditions

1. Magento 2.2.1 CE without sample data.
2. PHP 7.0, apache, mysql 5.7.

### Steps to reproduce

1. Login to Magento 2 admin panel.
2. Go to System -> User Roles and create one role with some restriction. For example restrict 'System' tab.
3. Assign one of the user to created role(with restriction) from 2 step.
4. Login with user which has restricted role. 

### Expected result

1.  No errors should be displayed. 

### Actual result

1. Error displayed on every page.
2. ![error](https://user-images.githubusercontent.com/8236853/32613275-21c84f5e-c573-11e7-8753-03040c56b65d.png)

**Comment by george-vlahakis** [comment]
It is a known bug which is fixed in 2.2. 
See https://github.com/magento/magento2/issues/11700
And https://github.com/magento/magento2/commit/4904b3d0f0e73d9a7452407c5162c2d55b04b049

**Comment by magento-engcom-team** [comment]
@Ruslan05, thank you for your report.
We've created internal ticket(s) MAGETWO-73031 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Closed as duplicate https://github.com/magento/magento2/issues/11700.
