### ISSUE TITLE
Cannot get customer custom address attribute from quote_address

### ISSUE THREAD

**Issue by Mulderua** [magento/magento2#12143]
### Preconditions
1. Magento EE 2.1.9

### Steps to reproduce
1. Create customer address custom attribute for example "my_attribute"
2. Create plugin for example Magento\Quote\Model\Quote\Address::afterGetAllItems
3. Try to get your custom attribute 

`public function afterGetAllItems(\Magento\Quote\Model\Quote\Address $subject, $items) {
        $myAttribute = $subject->getCustoMAttribute("my_attribute");
        return $items;
}
`

### Expected result
1. Get my_attribute value

### Actual result
1. Null

### Possible Solution

We have this method \Magento\Quote\Model\Quote\Address::importCustomerAddressData
With this code:
`
        $this->_objectCopyService->copyFieldsetToTarget(
            'customer_address',
            'to_quote_address',
            $this->addressMapper->toFlatArray($address),
            $this
        );
`
than we have observer that calls in method copyFieldsetToTarget thet lead to \Magento\CustomerCustomAttributes\Observer\AbstractObserver::_copyFieldset
and this perform if steatment:
`
if ($source instanceof \Magento\Framework\DataObject &&
            $target instanceof \Magento\Framework\DataObject
        )
`
That prevents copy custom address attribute to quote address.
So we can just change \Magento\Quote\Model\Quote\Address::importCustomerAddressData
by this code
`
$this->_objectCopyService->copyFieldsetToTarget(
            'customer_address',
            'to_quote_address',
            new DataObject($this->addressMapper->toFlatArray($address)),
            $this
        );
`
And It will fix issue.

**Comment by magento-engcom-team** [comment]
@Mulderua thank you for your report. 
Customer address attribute is not functionality of  Open Source Magento edition.
Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways: You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
