### ISSUE TITLE
The way to pass more than one attribute in api function

### ISSUE THREAD

**Issue by helmsmantest** [magento/magento2#12148]
### Preconditions
Magento version 2.2
PHP Version 7.1.4
MySql 10.1.22-MariaDB

### Steps to reproduce
I'm trying to implement my custom module which using custom api according to the guidlines: http://inchoo.net/magento-2/magento-2-custom-api/ (because I did not find oficial guidelines, please provide me with the link if you can).
My module: https://github.com/helmsmantest/Openc_GCApi
But there are no way to send more than one parameter in api function:
I'm testing using this code:
`$wsdlUrl = BASEURL.'index.php/soap/default?wsdl&services=opencGCApiGcapiapiStockV1';
$context = stream_context_create($opts);
	try {
		$request = new SoapClient($wsdlUrl, ['version' => SOAP_1_2, 'context' => $context]);
		} catch(Exception $e){
		var_dump($e);
	}
$result = $request->opencGCApiGcapiapiStockV1Update(array('productId' => 1, 
	'data' => array('qty' => 26, 'is_in_stock' => 1, 'manage_stock' =>1, 'use_config_manage_stock' => 1, 'use_config_backorders' => 1, 'backorders' => 1)));
	));
print_r($result); 
`
### Expected result
In the method it should be the following array in $data parameter: 'qty' => 26, 'is_in_stock' => 1, 'manage_stock' =>1, 'use_config_manage_stock' => 1, 'use_config_backorders' => 1, 'backorders' => 1
### Actual result
But whan I'm trying to log second attribute in my \Openc\GCApi\Api\GcapiapiStockInterface\GcapiapiStock::update($productId, $data)
I'm getting empty array.

**Comment by helmsmantest** [comment]
I'm using Magento 2.2

**Comment by magento-engcom-team** [comment]
Hi @helmsmantest 
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by helmsmantest** [comment]
Already done it https://magento.stackexchange.com/questions/200256/magento-2-api-can-not-send-2-params
People dont know how to do it((

**Comment by purplebolt** [comment]
Any luck with this?
