### ISSUE TITLE
How to reduce HTTP requests in magento2? 

### ISSUE THREAD

**Issue by epixeltechnologies** [magento/magento2#12140]
I have merged js and CSS with production mode. But still I can see many http requests js and css files. How can i reduce the http requests of js and css in magento2?

**Comment by magento-engcom-team** [comment]
@epixeltechnologies , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
