### ISSUE TITLE
Switching store views twice in a row produces incorrect URL

### ISSUE THREAD

**Issue by pfandrade** [magento/magento2#12158]
### Preconditions
The behaviour described below appears on both Magento 2.2.0 and 2.2.1.

### Steps to reproduce
1.  Add two different store views (codes en, pt for example)
2. Make sure you're _not_ using store codes in the URL
3. Open your website. It will open the default store view (assume en)
4. Switch to the pt store view. Verify that it works and that the url has "__store=pt" query arg.
5. Immediately switch back to en store view

### Expected result
1. Magento should switch to the en store view and there should be only one "__store=pt" query arg.

### Actual result
1. The URL generated is invalid ```https://<magento>/?___store=pt?___store=en``` and Magento outputs an error.

![magento_error](https://user-images.githubusercontent.com/867472/32628334-6ba98bc8-c58d-11e7-9e0e-f835c0520743.png)

**Comment by hostep** [comment]
Hi @pfandrade 

This is a duplicate of https://github.com/magento/magento2/issues/10908, which seems to already been fixed and fix should get delivered in Magento 2.2.2 (expected around the end of this year)

Feel free to close please :)

**Comment by pfandrade** [comment]
Closing as duplicate of #10908
