### ISSUE TITLE
how can we change the default theme in magento 2.0

### ISSUE THREAD

**Issue by Obscurefrey** [magento/magento2#1215]
i want to install some another theme in magento 2.0 .. guide me pls...

**Comment by pccomfrank** [comment]
Have you ever installed any current Magento 2, such as 0.74.0-beta5, 0.74.0-beta6, successfully? You made the home page working?

**Comment by Obscurefrey** [comment]
Yeah i successfully installed magento..
On Apr 26, 2015 6:30 PM, pccomfrank <notifications@github.com> wrote:Have you ever installed any current Magento 2, such as 0.74.0-beta5, 0.74.0-beta6, successfully? You made the home page working?

**Comment by pccomfrank** [comment]
What is the reversion of your Magento? Magento 2 or Magento 1? Magento 2 0.74.0-beta5 or Magento 2 0.74.0-beta6 ?

**Comment by vpelipenko** [comment]
@Obscurefrey, do you new Magento 2 theme and want to install it?

**Comment by pccomfrank** [comment]
Sorry, I do not new Magento 2 and I cannot install it.

**Comment by zanilee** [comment]
Hi, @Obscurefrey!
Here is the guide how you can change a theme in Magento 2: http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/themes/theme-apply.html#theme-apply-apply

**Comment by jcage88** [comment]
Hi there! As for me, I am using http://www.finestshops.com hosting for Magento. They provide all the service I need. Maybe, you should ask them for help too?

**Comment by vpelipenko** [comment]
@Obscurefrey, did you resolve your issue with link to guide provided by @zanilee?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor. @Obscurefrey, feel free to reopen this issue if it is not resolved for you.
