### ISSUE TITLE
Attention Something went wrong error is uninformative.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12152]
>

### Preconditions
1. Install M2

### Steps to reproduce
1. Could be anything, but cause some error in the backend to trigger this popup -
 "Attention

Something went wrong.
" 

### Expected result
1. Any useful or actionable information. 

### Actual result
Message is vague. So its on user to remember how they replicated issue, with no linked reporting information for a dev or other admin to check (correlate to error logs and so on).

Ideally it provides SOMETHING useful.

**Comment by magento-engcom-team** [comment]
@sylink, thank you for your report.
We've created internal ticket(s) MAGETWO-83658 to track progress on the issue.

**Comment by RomaKis** [comment]
Duplicate https://github.com/magento/magento2/issues/11700.

**Comment by sermagnus** [comment]
The error is due to the interruption of ajax calls originated from a quick change of page.

To solve it, the error callback must be interrupted also on xhr.readyState === 0

`function (xhr) {
            if (xhr.statusText === 'abort' || xhr.readyState === 0) {
                return;
            }
            ....[other code]...
}`

**File affected:**
- magento/magento2-base/lib/web/mage/backend/bootstrap.js [Line 77]
- magento/module-ui/view/base/web/js/grid/provider.js [Line 146]

**Comment by magento-engcom-team** [comment]
@ghost, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
