### ISSUE TITLE
Extension integrations - REST webservice

### ISSUE THREAD

**Issue by YasirDC** [magento/magento2#12160]
### Preconditions

1. Magento version 2.1.7
2. Have setup integration token (http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-token.html). 
3. API has access to All resources.
4. Integrations status: Active
5. User role: Admin

### Steps to reproduce
1.  Making call with Postman
2. Error message: "Consumer is not authorized to access %resources"
3. Seems that Magento is not applying permissions

### Expected result
1. Should return resources

### Actual result

![screen shot 2017-11-10 at 10 34 27 am](https://user-images.githubusercontent.com/16007324/32636817-5f5a7e12-c606-11e7-98e5-ea7c447266a8.png)

**Comment by magento-engcom-team** [comment]
@YasirDC, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
