### ISSUE TITLE
UPS Shipping not listed in REST

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [magento/magento2#12163]
UPS Shipping method not show/get using REST call from APP

`GET V1/carts/:cartId/shipping-methods`
`GET V1/carts/mime/shipping-methods`

this will show only some of shipping method but UPS will not show in front it will show perfectly.

### Preconditions

1. UPS module for Magento 2

### Steps to reproduce

1. `GET V1/carts/:cartId/shipping-methods` or `GET V1/carts/mime/shipping-methods`

### Expected result

1. List of Enable UPS Shipping method as Front
2. [
![checkout 1](https://user-images.githubusercontent.com/25686742/32643418-55c12dd8-c601-11e7-80b2-62d24b93ddc1.png)
](url)

### Actual result

1. `[
    {
        "carrier_code": "flatrate",
        "method_code": "flatrate",
        "carrier_title": "Flat Rate",
        "method_title": "USPS Fixed (7-10 Business Days)",
        "amount": 0,
        "base_amount": 0,
        "available": true,
        "error_message": "",
        "price_excl_tax": 0,
        "price_incl_tax": 0
    },
    {
        "carrier_code": "freeshipping",
        "method_code": "freeshipping",
        "carrier_title": "Free Shipping",
        "method_title": "Free (6-10 Business Days)",
        "amount": 0,
        "base_amount": 0,
        "available": true,
        "error_message": "",
        "price_excl_tax": 0,
        "price_incl_tax": 0
    }
]`

**Comment by magento-engcom-team** [comment]
@dodiya-divyarajsinh, thank you for your report.
We've created internal ticket(s) MAGETWO-83717 to track progress on the issue.
