### ISSUE TITLE
Images not working properly with wysiwyg editor in admin

### ISSUE THREAD

**Issue by Krupaly2k-zz** [magento/magento2#12175]
### Preconditions

1. Magento Version : 2.1.7
2. 

### Steps to reproduce

1.  When I am uploading image to product description from admin editor, after clearing cache php magento cache:clean the image shows not found after some time on same path.
2. 
3. 

### Expected result

1. Need to keep image as it is as I am cleaning cache not flush image cache

### Actual result

1. [Screenshot, logs]

Please help me to resolve this issue soon.

**Comment by magento-engcom-team** [comment]
@Krupaly2k, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
