### ISSUE TITLE
Customer account: tracking popup error with custom Carrier

### ISSUE THREAD

**Issue by catstantin** [magento/magento2#12177]
### Preconditions

Magento 2.1 

### Steps to reproduce
1. Register customer and place order
2. Create shipment with custom Carrier
3. On frontend: My account -> My orders -> View Order -> Order Shipments tab
4. Click on "Track this shipment" or "Track All Shipments" link

### Expected result
1. Popup with shipment information displayed

### Actual result
1.  Error occurred:

> Error: Call to a member function getTracking() on array in /magento2/vendor/magento/module-shipping/view/frontend/templates/tracking/details.phtml on line 22

**Comment by magento-engcom-team** [comment]
@catstantin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by oleksii-lisovyi** [comment]
@magento-engcom-team, looks like there is the same bug described [#8842](https://github.com/magento/magento2/issues/8842) and it can be reproduced there.
