### ISSUE TITLE
designing Issue

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#1217]
There is a design issue in language locale drop down button in the admin panel.This is the dropdown panel that comes  in the footer of admin panel used for the language selection for admin.

**Comment by vpelipenko** [comment]
@aishwaryacedcoss, what issue can you see there?

**Comment by aishwaryacedcoss** [comment]
Hello,
Please check this screenshot :-
http://awesomescreenshot.com/0284uzvw08
Hope it will clear my point.

**Comment by MomotenkoNatalia** [comment]
Hi @aishwaryacedcoss
Maybe you are using an old version of a browser, could you upgrade your browser and tell us if this issue is still reproduced

Thanks!

**Comment by aishwaryacedcoss** [comment]
Ok Sorry ,Yes its my browser problem.

**Comment by vpelipenko** [comment]
@aishwaryacedcoss, we are going to close this issue? Do you have any objections?

**Comment by aishwaryacedcoss** [comment]
No.
