### ISSUE TITLE
Deleting Attribute Set deleted products

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#12172]
### Preconditions
1.  PHP 7.0
2.  Magento 2.2.1

### Steps to reproduce
1.  Make a new attribute set
2.  Assign attribute set to product
3.  delete attribute set

### Expected result
1.  OR a message that products will be deleted OR just set Product to default attribute set.

### Actual result

The product gets deleted from the DB and everywhere. Its not just 'not accessible'  and i don't get why. This leaves so much space for errors. Even if i would want to delete an attribute set and i have 10000+ products the mistake is easily made to forget one to change from attribute set. Also its just not smart to delete the product when you delete its attribute set... A customer of mine just accidently deleted an attribute set and deleted over 1000+ products with it.

Sure we can reroll the DB but just saying how we can just avoid this by not deleting products when you delete its attribute set.

**Comment by magento-engcom-team** [comment]
Hello @versdivers. Thanks for reporting. Please clarify You mean there is no message at all telling that products will be deleted or there is such a message, but You wish it contained an option that allows not to delete belonging products but to reassign them to the default attribute set. Thank You.

**Comment by versdivers** [comment]
Well i was apparently wrong. There is a message that says : "You are about to delete all products in this attribute set. Are you sure you want to do that?". But still you should have the option to not delete the products. By default it should not delete the products even. It should be an option to delete the products but you need to check a checkbox, otherwise just give them the default or first attribute set that is available.

**Comment by versdivers** [comment]
But i guess this is not a bug then. Rather a really really dangerous thing to have.

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by orlangur** [comment]
> just set Product to default attribute set.

Such behavior would be more confusing and lead to data loss anyway. Merchant is supposed to read messages carefully before doing such dangerous operations.

**Comment by versdivers** [comment]
Losing your products attributes is way better then losing your products itself. I mean.. Attributes are not bound to attribute sets even. Attribute sets are just a collection of attributes so you don't even need to lose that data. But even if you did , what would  you prefer? Losing products or losing its attributes? Also Products are not bound to their attributes again... It makes no sense to delete things that are not dependent on eachother.

Compare it like this. Would it make sense to delete a customer if i would delete its address? No it would not. Just because the address is only a portion of the customers total. And this is no different.

**Comment by orlangur** [comment]
> Attributes are not bound to attribute sets even

This is not true. ALL product data is stored as attributes. Different attribute sets may contain totally different attributes thus when you switch attribute set incompatible attributes are lost.

Products must be deleted when you delete attribute set to preserve data integrity.

@versdivers what else could be improved here if there is already appropriate warning message?

**Comment by versdivers** [comment]
@orlangur You can perfectly set a new attribute set programmaticly without losing its information. I've even build a module that does exactly that. Even more so if you change the product attribute set on a product page itself it has no problems with converting that information.

I have a build a module that does this in Bulk with the action tools. No problems occur. So why would this not be possible to do when a attribute set is deleted? The attributes itself are not deleted , only the set around it. Products are build with attributes i agree but you are not deleting attributes. You are deleting the sets that group the attributes.

So far as i see the attributes are bounded to groups who are bounded to sets (eav_attribute_group?). But the attributes themself will keep existing if you delete the set. Therefor its perfectly possible to keep the values stored within the attribute if you use them or not. Even more so this way you can swap between attribute sets with the same attributes and keep the settings of the products.

This a lot less buggy. product->attribute->value -> bind to attribute (multiple) group(s) -> bind to attribute (multiple) set(s). You can only have an attribute 1x / product anyways so this does not provide any conflict at all.

Pro's 

1. Dynamic swapping attribute sets while remaining data
2. Dummy proof for the user
3. Would you create attribute sets by code its also dummy proof there (API's would be more dynamic)
4. On deleting the attribute you only remove that 1 attribute from all the attribute groups and attribute sets making them independandant from eachoter
5. Easy to keep your attribute sets clean if you stop using some (you don't need to check where its used and manually update those 1 by 1 to the default set or another set before you delete the attribute set which can be a really big task).

Cons

None as far as i see. I wouldn't see where this would cause a problem , i only see an improvement.


Current situation 

Lets say i have 2000 product within Attribute set 'X'.  Now i need to use a MYSQL query (not user friendly) to set all those to another attribute set. If i do not do it this way i can open 2000 products one by one saving a new attribute set risking skipping  some who get deleted which is hard to track down.
Hours of work and a lot of potential mistakes are not possible with the solution that i suggest in my opinion.

**Comment by okorshenko** [comment]
HI @versdivers 
We are closing this issue as feature request. Fill free submit your feature request here https://github.com/magento-engcom/community-features/issues/

**Comment by orlangur** [comment]
Hi @versdivers,

>  You can perfectly set a new attribute set programmaticly without losing its information

Via Admin UI as well, however, when there is no matching attribute in new attribute set value will be (and must be) lost.

> Therefor its perfectly possible to keep the values stored within the attribute if you use them or not

It breaks data integrity and keeps orphaned data in database.

I would recommend for your particular customized store to simply disable attribute set removal. I don't see what could be improved in core as there are already all necessary warning messages implemented.
