### ISSUE TITLE
After upgrade 2.1.9 -> 2.1.10: productgrid filters are not loaded/saved in database anymore

### ISSUE THREAD

**Issue by mfxts** [magento/magento2#12179]
### Preconditions
1. Magento 2.1.10 CE

### Steps to reproduce
1. Upgraded (via Composer) from Magento 2.1.9 CE to Magento 2.1.10 CE
2. In backend  -> products -> catalog: 
the filter dropdown list for the product grid is empty (except for the default entry), although multiple previously defined filters are still existing in the database table ui_bookmark.
3. Creating new filters and storing them seems somehow possible. They are visible in the dropdown even after relogging, but not if using another browser (chrome, firefox,...) with the same user. 
4. Checking the database table ui_bookmark: There are no new records for the new created filters.
5. Additional info: The tables in our Magento database all have a prefix, so the real table name is: ng2_ui_bookmark
6. Downgraded to 2.1.9 and everything was fine again: filters loaded/saved to the database.
7. Upgraded to 2.1.10 again and described misbehaviour again.

### Expected result
1. Same behaviour as in 2.1.9: Storing a filter results in a database entry in ui_bookmark and the filters get loaded for the user, independent of the used browser/system.

### Actual result
1. Filters are not loaded from and saved to the database (ui_bookmark)

**Comment by magento-engcom-team** [comment]
@mfxts, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.
