### ISSUE TITLE
2.2 upgrage to 2.2.1 issue

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#12174]
### Preconditions

1. in magento2.2
2. php7,1

### Steps to reproduce

1. I don't know why i in admin > setup upgradd >Update application is running ->will be show error upgrade. Did't suggest anything wrong?
2. i re-installed new 2.2.0 (no date) try to test, upgrade to 2.2.1. still have this problem in upgrade system

### Expected result

1. How to solve this issue?

### Actual result

1. Update application is not running

Error in Update!
Please refer to documentation Doc link to perform manual rollback.

To attempt automatic rollback, please click the "Rollback" button.

[Module 'Magento_******':
Running schema recurring...Source class "\SignifydAvsDefault" for "SignifydAvsDefaultMapper" generation does not exist.

[2017-11-10 11:19:32 UTC] Job "setup:upgrade {"command":"setup:upgrade"}" has been successfully completed
[2017-11-10 11:19:32 UTC] Job "setup:static:regenerate []" has started

[2017-11-10 11:19:32 UTC] Cleaning generated files...
[2017-11-10 11:19:32 UTC] Clearing cache...
[2017-11-10 11:20:12 UTC] Cleaning static view files
[2017-11-10 11:20:12 UTC] Job "setup:static:regenerate []" has been successfully completed
[2017-11-10 11:20:12 UTC] Job "setup:maintenance:disable []" has started
Disabled maintenance mode

[2017-11-10 11:20:12 UTC] Job "setup:maintenance:disable []" has been successfully completed

**Comment by amirhmoradi** [comment]
Same issue here. Tried to upgrade via cli, and I get this error:
`Source class "\SignifydAvsDefault" for "SignifydAvsDefaultMapper" generation does not exist.`

**Comment by andy17612** [comment]
@amirhmoradi 
if you fixed it,please tell me

**Comment by andy17612** [comment]
im still stop and error in @amirhmoradi 
[2017-11-11 08:36:19 UTC] Job "setup:maintenance:disable []" has been successfully completed

**Comment by andy17612** [comment]
i re-installed new 2.2.0 (no date) try to test, upgrade to 2.2.1. still have this issue in upgrade system @amirhmoradi

**Comment by evensis** [comment]
Delete generated folder.

**Comment by andy17612** [comment]
delete generated all folder ? @evensis

**Comment by evensis** [comment]
Yep, just take the entire thing out. Magento will regenerate it on compilation anyway.

**Comment by andy17612** [comment]
can't , i tryed in ftp delete the file. but the issuee still here.... @evensis 
is run command rm -rf generated/* delete or use ftp delete?

```
Module 'Shopial_******':
Nothing to import.

[2017-11-13 17:36:32 UTC] Job "setup:upgrade {"command":"setup:upgrade"}" has been successfully completed
[2017-11-13 17:36:32 UTC] Job "setup:static:regenerate []" has started

[2017-11-13 17:36:32 UTC] Cleaning generated files...
[2017-11-13 17:36:32 UTC] Clearing cache...
[2017-11-13 17:36:32 UTC] Cleaning static view files
[2017-11-13 17:36:32 UTC] Job "setup:static:regenerate []" has been successfully completed
[2017-11-13 17:36:32 UTC] Job "setup:maintenance:disable []" has started
Disabled maintenance mode

[2017-11-13 17:36:32 UTC] Job "setup:maintenance:disable []" has been successfully completed
```

**Comment by evensis** [comment]
rm -rf generated/

I wouldn't ftp delete anything in that folder, paint would dry faster.

Soon as I did that the issue went away for me and I could continue upgrading. I did however have a few problems, so personally created a new git repo, sucked composer in, did a fresh 2.2.1 install via composer and then copied and pasted the app folder from my other repo over the top. Turned out it was Capistrano on my dev server causing the problems however. :-|

Although, the snippet you copied in looks like a successful deploy?

**Comment by andy17612** [comment]
But system upgrade FAIL on last step: maintenance disable it's made a rollback loop.
I installed new 2.2.0(no data) test to upgrade 2.2.1...same issuee..i dont know why... @evensis

**Comment by evensis** [comment]
Install fresh 2.2.1 via composer, copy and paste app folder into it from your primary repo (don't copy core Magento stuff if you used flat manual archive), delete generated folder and then run upgrade. See how you get on then, beyond that, deleting the generated folder worked for me (and by looks of it based on the thumbs up on the post, a few of others too).

**Comment by andy17612** [comment]
but the sql data is 2.2, is work ? @evensis

**Comment by evensis** [comment]
Yes, it will automatically run schema upgrades.

**Comment by andy17612** [comment]
but if system upgrade FAIL on last step is no problem too? look like work..but the step made a rollback loop. @evensis

**Comment by evensis** [comment]
Keeps throwing this on the rollback error yes?

Running schema recurring...Source class "\SignifydAvsDefault" for "SignifydAvsDefaultMapper" generation does not exist.

Mostly as this has solved it for myself and 2 others, im wondering if you have something else happening now (provided you have completely deleted the generated folder of-course).

**Comment by andy17612** [comment]
Yes and...This issuee not only me ,i saw some people have this issuee too..FAIL on last step: maintenance disable. @evensis

**Comment by andy17612** [comment]
https://github.com/magento/magento2/issues/12216 @evensis

**Comment by evensis** [comment]
The maintenance step caused the failure? Going to be a permission problem if that is the case.

@rigu12, can you confirm that you are no longer seeing:

Running schema recurring...Source class "\SignifydAvsDefault" for "SignifydAvsDefaultMapper" generation does not exist.

**Comment by andy17612** [comment]
Waiting support resolve our issue @evensis 
my case look like them https://github.com/magento/magento2/issues/12216 , same problem 
![image](https://user-images.githubusercontent.com/32366935/32777166-1b0c1636-c970-11e7-810e-3127436d2d54.png)

**Comment by evensis** [comment]
Okay, your issue has changed since you posted this thread (as per description), you've solved the signifyd generation issue but seems you've now stumbled into something else unfortunately.

Continue the discussion in #12216 as its not relevant to this thread description anymore.

**Comment by magento-engcom-team** [comment]
@rigu12, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.1

**Comment by 911gt3rs** [comment]
> Error in Update! Please refer to documentation Doc link to perform manual rollback.  To attempt automatic rollback, please click the "Rollback"

I had the same problem, it came from CRON that was executed in ROOT rather than user !

![screenshot-2017-12-31 planifier une tache - plesk onyx 17 5 3](https://user-images.githubusercontent.com/33813714/34463399-f3a5eeae-ee5a-11e7-82a1-2abe48fed5bf.png)

If you use plesk, to configure CRON as a user you have to go here:

![screenshot-2017-12-31 sites web domaines - plesk onyx 17 5 3 1](https://user-images.githubusercontent.com/33813714/34463429-e2317df4-ee5b-11e7-83bf-a84910831335.png)
