### ISSUE TITLE
Gallery Full Page Image Gallery Wont Close on Mobile

### ISSUE THREAD

**Issue by p3kyle** [magento/magento2#12185]
### Preconditions

1. Magento 2.2.1 (also on Magento 2.2) on magemojo hosting
2. 

### Steps to reproduce

1. Go on any new Android or IOS device, go to a product page, open the image gallery of the item.  Try to click the upper right hand X and the gallery doesnt close.  You have to hit the back button on the browser to get out of it but when you do that, it takes you back to the product grid page.  It has been tested on iphone 6, 6s, pixel 2 xl, and galaxy 7.

### Expected result

1. It should close the gallery and you should remain on the product page

### Actual result

1. Nothing happens when you click the x button

**Comment by magento-engcom-team** [comment]
@p3kyle, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by NaciAkce** [comment]
@magento-engcom-team 
me too on Iphone 7. Maybe you have to test it on real devices

**Comment by jmonschke** [comment]
I was able to reproduce this issue when using the iOS simulator, but not while using the Chrome DevTools emulating the mobile browsers.

**Comment by alexcrz** [comment]
I'm having the same issue, on a Magento 2.2.1, can't close the product gallery on iPhone, but works fine on Windows Mobile or Android, any solution?

**Comment by s2892** [comment]
The same 
google chrome dev iOS is working 
iPhone 7 / iPad Air - not working (Safari and Chrome) 

Any Solution ?

**Comment by vipinroy** [comment]
The same issue for me also in Magento 2.2.1.
The gallery will close when you press Escape button.
But it will not close when you click the close button on the top right.
The issue exists in ipads only.

**Comment by The0h** [comment]
Same issue for me using Magento 2.2.2.
Problem occurs on iPhone 5s/6/6s/7 and on iPad mini.

Any solutions yet?

**Comment by Amadeco** [comment]
Same issue in Magento 2.2.2
Test with iPhone 6 device.
You can't reproduce this on a web browser.

**Comment by s2892** [comment]
any progress ?

**Comment by robertkent** [comment]
This is definitely a problem on 2.2.2 - on desktop in mobile mode is fine - but on simulators and real devices you can't tap the cross to close full screen gallery - users must refresh the page.

**Comment by silversil** [comment]
I have same issue, how it is possible that it isn’t fixed?!?

**Comment by wontroba666** [comment]
same on 2.2.6

**Comment by farazWebDev** [comment]
Fixed working partially only.
Still facing same issue, on v2.2.5 and v2.2.6 for:
_Safari browser working_ but **iOS app not working** (web view).
_Android Phone - Chrome browser working_ but **default browser not working**.

**---Update---**
Strange case, **removing iOS check from method stubEvent** ( \lib\web\fotorama\fotorama.js#L1220 ), **allowing it to work** with Android mobile (tested on HTC, SAMSUNG, XIAOMI) default browser, Mobile Mozilla browser and iOS App (tested on iPAD and iPHONE 6S - in web view):
```
function stubEvent($el, eventType) {
	var isIOS = /ip(ad|hone|od)/i.test(window.navigator.userAgent);

	if (eventType === 'touchend') {
	//if (isIOS && eventType === 'touchend') {
		$el.on('touchend', function(e){
			$DOCUMENT.trigger('mouseup', e);
		})
	}
	$el.on(eventType, function (e) {
		stopEvent(e, true);

		return false;
	});
}
```

**Comment by farazWebDev** [comment]
> Fixed working partially only.
> Still facing same issue, on v2.2.5 and v2.2.6 for:
> _Safari browser working_ but **iOS app not working** (web view).
> _Android Phone - Chrome browser working_ but **default browser not working**.

**---Update---**
Strange case, **removing iOS check from method stubEvent** ( \lib\web\fotorama\fotorama.js#L1220 ), **allowing it to work** with Android mobile (tested on HTC, SAMSUNG, XIAOMI) default browser, Mobile Mozilla browser and iOS App (tested on iPAD and iPHONE 6S - in web view):
```
function stubEvent($el, eventType) {
	var isIOS = /ip(ad|hone|od)/i.test(window.navigator.userAgent);

	if (eventType === 'touchend') {
	//if (isIOS && eventType === 'touchend') {
		$el.on('touchend', function(e){
			$DOCUMENT.trigger('mouseup', e);
		})
	}
	$el.on(eventType, function (e) {
		stopEvent(e, true);

		return false;
	});
}
```
