### ISSUE TITLE
Changing Shipping Address does NOT change Billing Address at Checkout

### ISSUE THREAD

**Issue by p3kyle** [magento/magento2#12184]
### Preconditions

1. magento 2.2.1 on magemojo servers

### Steps to reproduce

1. Go through the checkout, on the second page of checkout, click the pencil to edit the shipping address, make changes on the shipping address, go to the second page, the billing address doesnt change unless you uncheck the "My billing and shipping address are the same" and check it again.

![image](https://user-images.githubusercontent.com/33497207/32679562-72d7cb90-c62c-11e7-83e6-6c624f231c6f.png)

### Expected result

1. the address under the "My billing and shipping address are the same" but happens if you check and uncheck that box like the image below
![image](https://user-images.githubusercontent.com/33497207/32679594-8ca5e606-c62c-11e7-8bc3-2425e67263b7.png)

### Actual result

1. See above

**Comment by magento-engcom-team** [comment]
@p3kyle, thank you for your report.
We've created internal ticket(s) MAGETWO-83764 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Thank you for your report. This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this. Otherwise you may submit Pull Request with the suggested changes.

**Comment by twoatechguy** [comment]
Why is this correct behavior?  This also means that extensions which validate the shipping address won't change the billing address.

**Comment by giorgiabosello** [comment]
Any update on this? Someone managed to resolve it?
