### ISSUE TITLE
Custom attributes values not updated

### ISSUE THREAD

**Issue by danyvega1990** [magento/magento2#12186]
When I tried to update a custom attribute from an existing product using the save method in the ProductRepositoryInterface the code don't throw any errors but the attribute remains with the old data.
### Preconditions

1. Magento 2.1.8
2. PHP 7.0

### Steps to reproduce

* <?php
* namespace Vendor\Module\Cron;
* use Magento\Catalog\Api\ProductRepositoryInterface;
* use Magento\CatalogInventory\Api\StockRegistryInterface;
* class CronDownloadData
* {
*     protected $productRepository;
*    protected $stockRegistry;
*     public function __construct(
*         SunskyProductRepositoryInterface $repository,
*         DirectoryList $directoryList,
*         ProductRepositoryInterface $productRepository,
*         StockRegistryInterface $stockRegistry
*    ) {
*         $this->productRepository = $productRepository;
*         $this->stockRegistry = $stockRegistry;
*     }
* public function updateLocalProduct($modelObj){
*         try {
*             $local_product = $this->productRepository->get($modelObj->getItem_no());
*             $local_product->setCustomAttribute('description', 'Some description');
*             $this->productRepository->save($local_product);
*         } catch (\Exception $ex){
*             // nothing to do this time;
*         }
*     }
* }

### Expected result

1. The existing product shows the new description.

### Actual result

1. Description not update at all

**Comment by seanscott49** [comment]
Magento 2.2
PHP 7

I am having issues with Custom Options in Magento 2.2. When I do an option for Warranty with Values Standard Warranty at a 0 price and extended warranty at 149.99 as a required field with drop down box, it saves, but when I make a change again to the product and save, it triggers an error. 

Warning: array_filter() expects parameter 1 to be array, string given in /chroot/home/homedics/svago.com/html/vendor/magento/module-configurable-product/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Configurable.php on line 145

A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

**Comment by magento-engcom-team** [comment]
@danyvega1990, thank you for your report.
We've created internal ticket(s) MAGETWO-84169 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @danyvega1990. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#967 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - [a2ae375499a807f06a677d2e7c5a7ed7e130b0b8](https://github.com/magento/magento2/commit/a2ae375499a807f06a677d2e7c5a7ed7e130b0b8)
 - [64a516128431f85b7ae623461117b5c9308fea05](https://github.com/magento/magento2/commit/64a516128431f85b7ae623461117b5c9308fea05)

The fix will be available with the upcoming 2.2.5 release.
