### ISSUE TITLE
bin/magento exception handling

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#1219]
the form of this file does not follow the structure of for example `pub/index.php`

the `catch` for the `Autoload error` should only cover the require of the bootstrap, not the actual execution.

Also if we want to limit the exception printing, we should make this dependend on the developer mode, or an extra console flag (--debug?)

I did not create a PR for this, as the file is to little, and I dont have an Idea how the structure is planed yet.

**Comment by muasir** [comment]
This sounds more like a suggestion than bug.

**Comment by Flyingmana** [comment]
if you search two hours because it shows `autoload error` and it only was a "simple" xml error which is already got good described in the exception, then you see it more like a bug.

**Comment by piotrekkaminski** [comment]
@muasir Error handling is the basis for efficient work with Magento and having to spend hours to debug is no good. This is definitely a bug. Do we already have internal bug number for it?

**Comment by mazhalai** [comment]
@Flyingmana we have created MAGETWO-36632 to track this internally.

**Comment by mbrinton01** [comment]
This has been fixed and the application will now show the full stack of exceptions, so the user can find the original one.  Please re-open this issue if you have any questions.
