### ISSUE TITLE
Change image aspect ratio via Magento Catalog helper

### ISSUE THREAD

**Issue by popovdenis** [magento/magento2#12197]
The issue is related to another issue described in https://github.com/magento/magento2/issues/12196.
But in that case the same issue is in Magento Catalog helper: Magento\Catalog\Helper\Image.php

### Preconditions

1. Magento 2.1.6
2. php 7.0.2
3. mariadb 10

### Steps to reproduce

1. Navigate to design/frontend/theme/etc/view.xml
2. Find aspect_ratio parameter for product image
3. Set false as value

### Expected result

1. Image is stretched to the whole area on image

### Actual result

1. Nothing happened

**Comment by magento-engcom-team** [comment]
@popovdenis, thank you for your report.
The issue is already fixed in develop branch, 2.2.1
