### ISSUE TITLE
None of the left-panel menu buttons work.

### ISSUE THREAD

**Issue by webscot** [magento/magento2#12199]
### Preconditions

1. v. 2.2.1 php 7
2. 

### Steps to reproduce

1. Log into admin panel
2. Click left menu buttons (sales, catalog, customer, etc._
3. Nothing happens

### Expected result

1. Maybe a prompt to enter a new customer or product or a configuration window to change settings??!!

### Actual result

1. [Screenshot, logs]

**Comment by denchev** [comment]
Do you see any errors in JS console? Did you do a cache clean or are you using a developer mode? I am using 2.2.1, brand new installation with no additional modules and it all works fine.

**Comment by webscot** [comment]
Thank you for responding. This should now be closed. It turns out that a change that needed to be made was made by the server hosting company and they did not make the change in the static files. It's not Magento.

I will ask one other thing if possible...

I understand that many changes occurred from 1.9.x to 2.x. Can attributes or attribute sets be imported into 2.x from 1.9.x without issue?

**Comment by denchev** [comment]
I'm happy you are no longer having this issue.
As for your question you should read more about it here http://devdocs.magento.com/guides/v2.0/howdoi/migrate/migrate.html

**Comment by magento-engcom-team** [comment]
Hi @webscot
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by magento-engcom-team** [comment]
@webscot, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
