### ISSUE TITLE
General system exception happened - import products data

### ISSUE THREAD

**Issue by ali-uae** [magento/magento2#12198]
### Preconditions

1. magento 2.1.7
2. PHP Version 7.0.24

### Steps to reproduce

1.  try to import 3-4 products by exported csv
2. 
3. 

### Expected result

1.   show msg -- General system exception happened

### Actual result

1. [Screenshot, logs]
show message in admin -- General system exception happened

**Comment by magento-engcom-team** [comment]
@ali-uae, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by ali-uae** [comment]
I am using magento 2.1.7 CE and it show

show message in admin -- "General system exception happened"

**Comment by ali-uae** [comment]
is this require to upgrade magento 2.1.7 to latest version ??

**Comment by Ctucker9233** [comment]
@ali-uae That will always be recommended. But I know the solution to your problem. CSV files have to be UTF-8 encoded. If you use an editor like notebook++ this is easy to do and it will show you characters that are not allowed highlighted in black. Simply remove those and the file should import as expected.
