### ISSUE TITLE
After upgrade 2.1.8 -> 2.1.10 add new product fatal error

### ISSUE THREAD

**Issue by Dregolwd** [magento/magento2#12191]
Preconditions
1. Magento 2.1.10 CE
2. PHP 7.0.24

Steps to reproduce
1. Upgraded (via Composer) from Magento 2.1.8 CE to Magento 2.1.10 CE
2. In backend -> products -> catalog: add new product

Expected result
1. Add new product

Actual result
1. HTTP ERROR 500 white page. 

AH01071: Got error 'PHP message: PHP Fatal error:  Method Magento\\Ui\\TemplateEngine\\Xhtml\\Result::__toString() must not throw an exception, caught TypeError: Argument 2 passed to Magento\\ConfigurableProduct\\Model\\ResourceModel\\Attribute\\OptionSelectBuilder\\Interceptor::getSelect() must be of the type integer, null given, called in /public_html/vendor/magento/module-configurable-product/Model/AttributeOptionProvider.php on line 56 in /public_html/vendor/magento/module-ui/Component/Wrapper/UiComponent.php on line 0\n', referer: ******/*******/catalog/product/index/key/*****************************/

**Comment by magento-engcom-team** [comment]
@Dregolwd, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by sambalay** [comment]
I am having the same error. @Dregolwd how did you fix this?
after upgrading from 2.1.8 to 2.2.2

**Comment by adam-thenorthernfoundry** [comment]
I am also having this issue, seems to be related to the line 
$select = $this->optionSelectBuilder->getSelect($superAttribute, $productId, $scope);
in vendor/magento/module-configurable-product/Model/AttributeOptionProvider.php
