### ISSUE TITLE
Swagger (salesOrderRepositoryV1 GetOrder/{id}) don't have shipping details

### ISSUE THREAD

**Issue by Sharkozp** [magento/magento2#12208]
### Preconditions

1. We are using Magento EE 2.2.1 on our Cloud

### Steps to reproduce

1. We created via REST API and from frontend 2 orders with different billing and shipping addresses
2. It it visible in admin that order have 2 different addresses - billing and shipping.
3. But when you get this order via Swagger or Rest Client shipping address missed

### Expected result

1. Response must contain shipping details

### Actual result

1. Response from Swagger don't have shipping info:
`{
  "base_currency_code": "EUR",
  "base_discount_amount": 0,
  "base_grand_total": 12.99,
  "base_discount_tax_compensation_amount": 0,
  "base_shipping_amount": 5,
  "base_shipping_discount_amount": 0,
  "base_shipping_incl_tax": 5,
  "base_shipping_tax_amount": 0,
  "base_subtotal": 7.99,
  "base_subtotal_incl_tax": 7.99,
  "base_tax_amount": 0,
  "base_total_due": 12.99,
  "base_to_global_rate": 1,
  "base_to_order_rate": 1,
  "billing_address_id": 8,
  "created_at": "2017-11-13 10:52:14",
  "customer_email": "ody@pino-gmbh.de",
  "customer_group_id": 0,
  "customer_is_guest": 1,
  "customer_note_notify": 1,
  "discount_amount": 0,
  "email_sent": 1,
  "entity_id": 4,
  "global_currency_code": "EUR",
  "grand_total": 12.99,
  "discount_tax_compensation_amount": 0,
  "increment_id": "000000002",
  "is_virtual": 0,
  "order_currency_code": "EUR",
  "protect_code": "c3e1c0bbba6002db20a060e1eb2f3db6",
  "quote_id": 12,
  "remote_ip": "87.139.169.33",
  "shipping_amount": 5,
  "shipping_description": "Flat Rate - Fixed",
  "shipping_discount_amount": 0,
  "shipping_discount_tax_compensation_amount": 0,
  "shipping_incl_tax": 5,
  "shipping_tax_amount": 0,
  "state": "new",
  "status": "pending",
  "store_currency_code": "EUR",
  "store_id": 1,
  "store_name": "Main Website\nMain Website Store\n",
  "store_to_base_rate": 0,
  "store_to_order_rate": 0,
  "subtotal": 7.99,
  "subtotal_incl_tax": 7.99,
  "tax_amount": 0,
  "total_due": 12.99,
  "total_item_count": 1,
  "total_qty_ordered": 1,
  "updated_at": "2017-11-13 10:52:24",
  "weight": 0,
  "items": [
    {
      "amount_refunded": 0,
      "base_amount_refunded": 0,
      "base_discount_amount": 0,
      "base_discount_invoiced": 0,
      "base_discount_tax_compensation_amount": 0,
      "base_original_price": 7.99,
      "base_price": 7.99,
      "base_price_incl_tax": 7.99,
      "base_row_invoiced": 0,
      "base_row_total": 7.99,
      "base_row_total_incl_tax": 7.99,
      "base_tax_amount": 0,
      "base_tax_invoiced": 0,
      "created_at": "2017-11-13 10:52:14",
      "discount_amount": 0,
      "discount_invoiced": 0,
      "discount_percent": 0,
      "free_shipping": 0,
      "discount_tax_compensation_amount": 0,
      "is_qty_decimal": 0,
      "is_virtual": 0,
      "item_id": 8,
      "name": "Tape Lime",
      "no_discount": 0,
      "order_id": 4,
      "original_price": 7.99,
      "price": 7.99,
      "price_incl_tax": 7.99,
      "product_id": 2,
      "product_type": "simple",
      "qty_canceled": 0,
      "qty_invoiced": 0,
      "qty_ordered": 1,
      "qty_refunded": 0,
      "qty_returned": 0,
      "qty_shipped": 0,
      "quote_item_id": 8,
      "row_invoiced": 0,
      "row_total": 7.99,
      "row_total_incl_tax": 7.99,
      "row_weight": 0,
      "sku": "45026",
      "store_id": 1,
      "tax_amount": 0,
      "tax_invoiced": 0,
      "tax_percent": 0,
      "updated_at": "2017-11-13 10:52:14"
    }
  ],
  "billing_address": {
    "address_type": "billing",
    "city": "Hamb",
    "country_id": "CH",
    "email": "ody@pino-gmbh.de",
    "entity_id": 8,
    "firstname": "Test",
    "lastname": "Test",
    "parent_id": 4,
    "postcode": "09876",
    "region": "Aargau",
    "region_code": "AG",
    "region_id": 104,
    "street": [
      "Test"
    ],
    "telephone": "0987654321"
  },
  "payment": {
    "account_status": null,
    "additional_information": [
      "Check / Money order"
    ],
    "amount_ordered": 12.99,
    "base_amount_ordered": 12.99,
    "base_shipping_amount": 5,
    "cc_last4": null,
    "entity_id": 4,
    "method": "checkmo",
    "parent_id": 4,
    "shipping_amount": 5
  },
  "status_histories": []
}`

Admin panel:
![image](https://user-images.githubusercontent.com/3489232/32722880-af47889a-c86b-11e7-8d3e-59d28b89c894.png)

I am using this method for testing order:
![image](https://user-images.githubusercontent.com/3489232/32722930-e34943ae-c86b-11e7-861d-92acbcb3c374.png)

It is have description that it must have shipping details, but it is not have it.

**Comment by magento-engcom-team** [comment]
@Sharkozp, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
