### ISSUE TITLE
Code standard miss matches

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1220]
Hi,
In the developer doc (http://devdocs.magento.com/guides/v1.0/coding-standards/code-standard-php.html) you said to use PSR-1 & PSR-2 standards. In PSR-2 it said "Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.". But I found in your code you are using underscore prefix for some protected variables & for others you are not.
Is there a rule for this or you are just mixing these randomly ?
![image](https://cloud.githubusercontent.com/assets/3830093/7388933/102152f2-ee87-11e4-95bd-ac5c3f0d6574.png)

**Comment by orlangur** [comment]
Duplicate of #1155, please look into [my comment](https://github.com/magento/magento2/issues/1155#issuecomment-87995562).

**Comment by bgkavinga** [comment]
Is there any reason to mix both ? What should we use in our own modules ?

**Comment by orlangur** [comment]
@bgkavinga, there is no need to not follow PSR-2 recommendation in any aspect. So, there is no reason to use underscores in new modules, unless it is not possible to avoid this (like inheritance from class which still uses underscores).

The only reason there are a lot of classes still using underscores in variable/method names is that all of them were not updated yet, as such change would be [quite disruptive](https://github.com/magento/magento2/issues/1155#issuecomment-88104130).

**Comment by alankent** [comment]
+1  We want to eliminate leading underscores, but it is disruptive.  Someone in the community I think was going to look into a script to remove them all - not sure if they have had the time to work on it. (I cannot find it just now.)

**Comment by bgkavinga** [comment]
Ok, Thanks a lot. Closing this ticket.

**Comment by orlangur** [comment]
@alankent,I linked to that issue in my comment.
