### ISSUE TITLE
M2.1.9 : Cannot make all address fields required in customer address edit page (frontend)

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#12202]
I am trying to make all address fields required on the customer address page on the frontend using JavaScript validation, but it does not seem to work. I'm wondering if this is a bug or a feature (I think it tends to be a bug). ([related question about this topic on SE](https://magento.stackexchange.com/questions/200972/magento-2-how-to-make-all-address-fields-required-in-customer-address-edit-for))

### Preconditions

1. Magento 2.1.9

### Steps to reproduce

Edit the section in `Magento_Customer/templates/address/edit.phtml` (or overwrite it in a theme) that is responsible for rendering the additional address lines:

    <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++): ?>
        <div class="field additional required">
            <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>">
                <span><?php echo $block->escapeHtml(__('Street ' . $_i)) ?></span>
            </label>
            <div class="control">
                <input placeholder="<?php echo $block->escapeHtml(__('Street ' . $_i)) ?>"
                       type="text"
                       name="street[]"
                       value="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr($block->getStreetLine($_i+1)) ?>"
                       title="<?php  echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                       id="street_<?php /* @escapeNotVerified */ echo $_i+1 ?>"
                       class="input-text required-entry">
            </div>
        </div>
    <?php endfor; ?>

Note: the only thing I added is the `required-entry`-class.

### Expected result

1. Upon submitting the page should show the JavaScript validation message on all address fields

### Actual result

1. The page just submits, even when the additional address fields are empty.

**Comment by kanduvisla** [comment]
I think I found the source of this problem: if the name of the input field is an array, the validation is only done on the first element. For example:

    <div class="field foo required">
        <label class="label" for="foo"><span><?php echo $block->escapeHtml(__('foo')) ?></span></label>
        <div class="control">
            <input type="text" name="foo[]" value="" title="" class="input-text required-entry" id="foo">
            <input type="text" name="foo[]" value="" title="" class="input-text required-entry">
        </div>
    </div>

In this example, only the first input element gets an error, even though the second one also has a `required-entry` class.

**Comment by kanduvisla** [comment]
After realizing the problem, I found an answer on [Stack Exchange](https://magento.stackexchange.com/questions/154510/magento-2-how-to-make-validation-on-same-name-array-input).

Still, I would like to suggest to keep this issue open, since it does not seem like intended behavior to me.

**Comment by orlangur** [comment]
Input validator is only checking one element, isn't it? Or it validates first input, then tries to validate second - but skips it because it is already marked as validated?

**Comment by Triloworld** [comment]
Only first one is checked and mark valid or not. Second one is skipped.
This is done by: `!$.mage.isEmpty(value)` and 
`isEmpty: function (value) {
                return value === '' || value === undefined ||
                    value == null || value.length === 0 || /^\s+$/.test(value);
            },`

> /SHOP/vendor/magento/magento2-base/lib/web/mage/validation/validation.js

In Magento there is somewhere place where bind of validation occur. There need to be loop on each element with same name to validate and configurable approach. 
Maybe new validation rules, like "required-all-entry" ?

**Comment by kanduvisla** [comment]
I would not suggest a new validation rule. There are multiple validation rules and you don't want to create an `-all-`-variant for all of them. I think the problem lies in the current way how input elements are collected. It looks like they are collected by their `name`, using the `name`-attribute as the unique key, but clearly this will not work for names like `foo[]`.

**Comment by magento-engcom-team** [comment]
@kanduvisla, thank you for your report.
We've created internal ticket(s) MAGETWO-84245 to track progress on the issue.

**Comment by duckchip** [comment]
Any news of this issue? 

thx!

**Comment by nadeefit6** [comment]
Fix is merged to  2.2.4-develop branch.

**Comment by hostep** [comment]
@nadeefit6: great! Can you make a pull request of your branch towards the magento/magento2 repo (intead of your own fork), so someone from the Magento team can review and approve when the fix is working? Thanks! :)

Just a quick hint: it's better to create a new branch on your fork for every issue you work on, don't directly commit towards an already existing branch, it's not very well maintainable like that :)

**Comment by sdzhepa** [comment]
Is it still actual for the current `2.3-develop` or we can close it?

**Comment by hostep** [comment]
@sdzhepa: not tested yet, but I think https://github.com/magento/magento2/pull/15383 fixed it and that was delivered in Magento 2.3.3
Maybe @kanduvisla can confirm? It also fixed his very similar sounding issue https://github.com/magento/magento2/issues/8258

*Update*: it looks like https://github.com/magento/magento2/pull/15383 was partly reverted again in [MC-19684](https://github.com/magento/magento2/commit/c844e10037b4684525fb26f2b946119519731ce1) for some reason, so not sure if it is truly fixed in 2.3.3 ...

**Comment by engcom-Delta** [comment]
@hostep @sdzhepa I am able to reproduce issue on 2.3-develop.
[Case 1:](Magento_Customer/templates/address/edit.phtml)
Add `required-entry` class to additional address fields in `Magento_Customer/templates/address/edit.phtml` 
![#12202issue](https://user-images.githubusercontent.com/51681379/67750153-4cca9180-fa37-11e9-8623-859a1f005d23.png)

[Case 2:](Magento_Customer/templates/address/edit.phtml)
Create module with template file where name of the input field is an array
![#12202issue_2](https://user-images.githubusercontent.com/51681379/67750248-87342e80-fa37-11e9-9ad4-0e991d302faf.png)

![#12202issue_3](https://user-images.githubusercontent.com/51681379/67750255-8a2f1f00-fa37-11e9-97a7-1efd083d1353.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22197` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-25053` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by mateuszrusiecki** [comment]
why this fix wasn't added to magento 2.3? WTF o_O? are you so fucking lazy?

**Comment by miikEe13** [comment]
Even in the EE wasnt added :facepalm:
