### ISSUE TITLE
Product price auto rounding

### ISSUE THREAD

**Issue by DavaGordon** [magento/magento2#12210]
### Preconditions

1. Magento 2.2.0-rc23

### Steps to reproduce

1. Edit Price in admin to 5.65 and it is rounded up to 6, update to 5.45 and its rounded to 5 after save
2. Checkout prices are rounded up also

### Expected result

1. Show the right price that was entered not update it to a new price

### Actual result

1. The price was updated from £91.57 to £92.00 which basically makes the site impossible to use until its fixed, even if saved via the admin the issue still occurs

**Comment by magento-engcom-team** [comment]
@DavaGordon, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by DavaGordon** [comment]
Found the issue was due to the precision being automatically set to 2 and bootstrap.php being ignored changed it on server level to 14 and issue resolved

**Comment by liberteh** [comment]
I'm having this exact problem on a pretty fresh Magento CE 2.2.7 installation.
Add product, give price (<2.50 becomes 2.00, >2.50 becomes 3.00)

As far as I can tell, 2 is the precision we want. Adjusting this will just remove decimals. 
I have tried several rounding and pricing plugins in which you can enable or disable rounding, increase number after etc. 
None have given me a solution: be able to set a price between 01 and 99 after the decimal. It always rounds it after hitting the save button.
