### ISSUE TITLE
Creditmemo total is negative on a 100% discounted order

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#12218]
This scenario can occur when reward points are used as a discount instead of a payment method. (custom code required, but not for reproducing the issue).

### Preconditions

1. 2.2-develop

### Steps to reproduce

1. Create a discount rule that gives 100% discount on all order items
2. Refund the order, don't refund the shipping costs

### Expected result

1. The credit memo grand total total and row total should be 0

### Actual result

1. The credit memo grand total and row total is negative discount tax compensation amount

wrong:
![screen shot 2017-11-13 at 4 25 28 pm](https://user-images.githubusercontent.com/1489129/32733344-5046155e-c88f-11e7-96a9-9540a2fde1d5.png)

right:
![screen shot 2017-11-13 at 4 24 47 pm](https://user-images.githubusercontent.com/1489129/32733346-51a7f2dc-c88f-11e7-9ce4-785bd220c37e.png)

**Comment by magento-engcom-team** [comment]
@ajpevers, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by ebaschiera** [comment]
I got the same issue with a 94% discount on a whole cart. I am refunding also shipping cost.
Commmit https://github.com/ajpevers/magento2/commit/847d412f8f9e2abeba97ac3999f6a1fbdf3ae9f2 fixed my issue. Thanks!

**Comment by ebaschiera** [comment]
Sorry, I forgot to mention that I am on Magento EE 2.1.10.

**Comment by ihor-sviziev** [comment]
Hi @engcom-backlog-pb,
could you re-check this issue? we have request that this issue still reproducting in 2.2.
https://github.com/magento/magento2/pull/12219#issuecomment-393842726

**Comment by engcom-backlog-nickolas** [comment]
@AntonEvers, @ihor-sviziev I'm not able to reproduce this issue on current 2.2-develop
![peek 2018-08-10 14-32](https://user-images.githubusercontent.com/40755810/43955624-b5089fcc-9ca9-11e8-9c4e-a2ccc2147991.gif)

@AntonEvers, could you please correct my steps, or add more details?

**Comment by ihor-sviziev** [comment]
Maybe @elvinristi could also check if steps are correct?

**Comment by elvinristi** [comment]
@ihor-sviziev will try to find time to produce steps this week but my conditions were :

- tax 5%
- Coupon with Discount Amount: 99.9%

at that time was this replicated on M2.2.2 Commerce.

**Comment by engcom-backlog-nickolas** [comment]
@elvinristi, @ihor-sviziev I've tried to reproduce with tax 5% and coupon with discount amount 99.9%. Still cannot get actual result from steps to reproduce.
![peek 2018-08-15 14-23](https://user-images.githubusercontent.com/40755810/44146257-7bf75718-a097-11e8-804f-98e5dd6bbf7f.gif)

**Comment by elvinristi** [comment]
@ihor-sviziev , in short - couldn't replicate with latest 2.2.6-dev CE.

### Preconditions:
- use magento 2 sample data: 
  - https://github.com/magento/magento2-sample-data/tree/2.2-develop
- configre online payment, i.e. "Braintree"
  - https://docs.magento.com/m2/ce/user_guide/payment/braintree.html
  - Payment Action: Authorize and Capture
- Make sure tax is configured (using Magento's sample data where US - Michigan has tax configured)
- Create cart rule - coupon:SALE99 , discount 99.9%, Apply to Shipping Amount: No

### FRONTEND, as a guest
- CART : 
![](https://snaps.vaimo.com/elvin.risti/cart_21243E6A.png)
- SHIPPING
  - Country: US, Region: Michigan
![](https://snaps.vaimo.com/elvin.risti/checkout-shipping_21243EB9.png)
- PAYMENT (Online payment - Braintree sandbox, auhtorize and capture) c/c 4500600000000061
  -  ![](https://snaps.vaimo.com/elvin.risti/checkout-payment_21243EDF.png)
  - Testing cards: https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/php

### ADMIN
- new credit memo from the paid invoice:
![](https://snaps.vaimo.com/elvin.risti/new-credit-memo-dev_21244794.png)

**Issue couldn't be replicated with these settings.** Can't currently recall more details to conditions what could bring in this issue. Maybe this falls back to the payment method logic what's used.

I guess both these issues (#12218 and #12219 ) can be closed.

**Comment by dthivanka** [comment]
I was able to reproduce this issue in a Magento 2.3.4 instance with sample data. You need to have following tax calculation settings to reproduce this. 
![Screenshot from 2020-02-18 12-43-48](https://user-images.githubusercontent.com/820360/74737601-123a6e00-524d-11ea-845f-f8510b969ef7.png)

follow @elvinristi steps to reproduce. 

https://github.com/magento/magento2/pull/12219/commits fix the issue

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance
@dthivanka could you try to reproduce it on test instance?

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-12218-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-12218-2-4-develop.instances.magento-community.engineering/admin_8101](https://i-12218-2-4-develop.instances.magento-community.engineering/admin_8101)
Login: `40a74aa0` Password: `7ddd5db5252d`
Instance will be terminated in up to 3 hours.

**Comment by dthivanka** [comment]
@ihor-sviziev sure
@magento-engcom-team can I get a instance with sample data ?

**Comment by ihor-sviziev** [comment]
@dthivanka it's not supported, but you could generate small performance profile (test products, categories, etc) here: https://i-12218-2-4-develop.instances.magento-community.engineering/pub/testing/

**Comment by dthivanka** [comment]
@ihor-sviziev Can't replicate on magento 2.4-develop branch instance. May be it's fixed now on develop branch

**Comment by ihor-sviziev** [comment]
@dthivanka thank you for confirmation! In this case I'm closing this issue
