### ISSUE TITLE
Web setup updater error Magento CE 2.2 to 2.1 

### ISSUE THREAD

**Issue by gaboreszaki** [magento/magento2#12216]
Dear Devs.
I have an update problem with magento ce 2.2. can somebody help? 
magento web wizard -> **system upgrade FAIL on last step: maintenance disable** 
it's made a rollback loop

### Preconditions
1. Magento version: CE 2.2
2. PHP version: 7.0.22-0ubuntu0.16.04.1
3. Server version: Apache/2.4.18 (Ubuntu)

### Steps to reproduce
1. system upgrade
2. readiness check
3. backup
4. update

### Expected result
1. the updater finish without errors... 

### Actual result

>  Error in Update!
> Please refer to documentation Doc link to perform manual rollback.
> 
> To attempt automatic rollback, please click the "Rollback" button. 

so the updater is detect an error and it FORCE ME TO DO A ROLLBACK. 
The updater site lock me this page(probably safety reasons), but when i disable maintenance mode manually, the site is working fine.

> [2017-11-13 14:24:09 UTC] Job "setup:maintenance:disable []" has started
> 
> [2017-11-13 14:24:09 UTC] An error occurred while executing job "setup:maintenance:disable []": 
>
> **Could not complete setup:maintenance:disable []** successfully: Magento maintenance mode was not disabled. It can be disabled from the Magento Backend.

Full log:

> [2017-11-13 14:22:03 UTC] Job "setup:maintenance:enable []" has started
> Enabled maintenance mode
> 
> [2017-11-13 14:22:03 UTC] Job "setup:maintenance:enable []" has been successfully completed
> [2017-11-13 14:22:03 UTC] Job "setup:cache:disable []" has started
> There is nothing to change in cache status
> 
> [2017-11-13 14:22:03 UTC] Job "setup:cache:disable []" has been successfully completed
> [2017-11-13 15:23:01 CET] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.2.1"}]}" has been started
> [2017-11-13 15:23:01 CET] Starting composer update...
> [2017-11-13 15:23:02 CET] ./composer.json has been updated
> 
> [2017-11-13 15:23:21 CET] Loading composer repositories with package information
> Updating dependencies (including require-dev)
> - Removing colinmollenhour/credis (1.6)
> - Installing colinmollenhour/credis (1.8.2)
> Loading from cache
> 
> - Removing colinmollenhour/php-redis-session-abstract (v1.2.2)
> - Installing colinmollenhour/php-redis-session-abstract (v1.3.4)
> Loading from cache
> 
> - Removing magento/framework (101.0.0)
> - Installing magento/framework (101.0.1)
> Loading from cache
> 
> - Removing magento/theme-frontend-luma (100.2.0)
> - Installing magento/theme-frontend-luma (100.2.1)
> Loading from cache
> 
> - Removing magento/module-config (101.0.0)
> - Installing magento/module-config (101.0.1)
> Loading from cache
> 
> - Removing magento/module-deploy (100.2.0)
> - Installing magento/module-deploy (100.2.1)
> Loading from cache
> 
> - Removing magento/module-store (100.2.0)
> - Installing magento/module-store (100.2.1)
> Loading from cache
> 
> - Removing magento/module-backend (100.2.0)
> - Installing magento/module-backend (100.2.1)
> Loading from cache
> 
> - Removing magento/module-translation (100.2.0)
> - Installing magento/module-translation (100.2.1)
> Loading from cache
> 
> - Removing magento/module-ui (101.0.0)
> - Installing magento/module-ui (101.0.1)
> Loading from cache
> 
> - Removing magento/module-developer (100.2.0)
> - Installing magento/module-developer (100.2.1)
> Loading from cache
> 
> - Removing magento/module-catalog (102.0.0)
> - Installing magento/module-catalog (102.0.1)
> Loading from cache
> 
> - Removing magento/module-quote (101.0.0)
> - Installing magento/module-quote (101.0.1)
> Loading from cache
> 
> - Removing magento/module-catalog-inventory (100.2.0)
> - Installing magento/module-catalog-inventory (100.2.1)
> Loading from cache
> 
> - Removing magento/module-theme (100.2.0)
> - Installing magento/module-theme (100.2.1)
> Loading from cache
> 
> - Removing magento/module-url-rewrite (101.0.0)
> - Installing magento/module-url-rewrite (101.0.1)
> Loading from cache
> 
> - Removing magento/module-customer (101.0.0)
> - Installing magento/module-customer (101.0.1)
> Loading from cache
> 
> - Removing magento/module-tax (100.2.0)
> - Installing magento/module-tax (100.2.1)
> Loading from cache
> 
> - Removing magento/module-reports (100.2.0)
> - Installing magento/module-reports (100.2.1)
> Loading from cache
> 
> - Removing magento/module-catalog-rule (101.0.0)
> - Installing magento/module-catalog-rule (101.0.1)
> Loading from cache
> 
> - Removing magento/module-sales (101.0.0)
> - Installing magento/module-sales (101.0.1)
> Loading from cache
> 
> - Removing magento/module-shipping (100.2.0)
> - Installing magento/module-shipping (100.2.1)
> Loading from cache
> 
> - Removing magento/module-cms (102.0.0)
> - Installing magento/module-cms (102.0.1)
> Loading from cache
> 
> - Removing magento/module-checkout (100.2.0)
> - Installing magento/module-checkout (100.2.1)
> Loading from cache
> 
> - Removing magento/module-review (100.2.0)
> - Installing magento/module-review (100.2.1)
> Loading from cache
> 
> - Removing magento/module-catalog-url-rewrite (100.2.0)
> - Installing magento/module-catalog-url-rewrite (100.2.1)
> Loading from cache
> 
> - Removing magento/module-import-export (100.2.0)
> - Installing magento/module-import-export (100.2.1)
> Loading from cache
> 
> - Removing magento/module-catalog-import-export (100.2.0)
> - Installing magento/module-catalog-import-export (100.2.1)
> Loading from cache
> 
> - Removing magento/module-configurable-product (100.2.0)
> - Installing magento/module-configurable-product (100.2.1)
> Loading from cache
> 
> - Removing magento/module-swagger (100.2.0)
> - Installing magento/module-swagger (100.2.1)
> Loading from cache
> 
> - Removing magento/module-sitemap (100.2.0)
> - Installing magento/module-sitemap (100.2.1)
> Loading from cache
> 
> - Installing magento/module-signifyd (100.2.1)
> Loading from cache
> 
> - Removing magento/module-search (100.2.0)
> - Installing magento/module-search (100.2.1)
> Loading from cache
> 
> - Removing magento/module-catalog-search (100.2.0)
> - Installing magento/module-catalog-search (100.2.1)
> Loading from cache
> 
> - Removing magento/module-google-analytics (100.2.0)
> - Installing magento/module-google-analytics (100.2.1)
> Loading from cache
> 
> - Removing magento/module-bundle (100.2.0)
> - Installing magento/module-bundle (100.2.1)
> Loading from cache
> 
> - Removing magento/module-braintree (100.2.0)
> - Installing magento/module-braintree (100.2.1)
> Loading from cache
> 
> - Removing magento/module-advanced-pricing-import-export (100.2.0)
> - Installing magento/module-advanced-pricing-import-export (100.2.1)
> Loading from cache
> 
> - Removing magento/magento2-base (2.2.0)
> - Installing magento/magento2-base (2.2.1)
> Loading from cache
> 
> Writing lock file
> Generating autoload files
> 
> [2017-11-13 15:23:21 CET] Composer update completed successfully
> [2017-11-13 15:23:21 CET] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.2.1"}]}" has successfully completed
> [2017-11-13 14:24:03 UTC] Job "setup:upgrade []" has started
> Cache cleared successfully
> File system cleanup:
> /var/www/magento/generated/code/Composer
> /var/www/magento/generated/code/Magento
> /var/www/magento/generated/code/Symfony
> /var/www/magento/pub/static/adminhtml
> /var/www/magento/pub/static/deployed_version.txt
> /var/www/magento/var/view_preprocessed/pub
> Updating modules:
> Schema creation/updates:
> Module 'Magento_Store':
> Module 'Magento_AdvancedPricingImportExport':
> Module 'Magento_Directory':
> Module 'Magento_Theme':
> Module 'Magento_Backend':
> Module 'Magento_Backup':
> Module 'Magento_Eav':
> Module 'Magento_Customer':
> Module 'Magento_BundleImportExport':
> Module 'Magento_CacheInvalidate':
> Module 'Magento_AdminNotification':
> Module 'Magento_Indexer':
> Module 'Magento_CatalogImportExport':
> Module 'Magento_Cms':
> Module 'Magento_Rule':
> Module 'Magento_Catalog':
> Module 'Magento_Search':
> Module 'Magento_CatalogUrlRewrite':
> Module 'Magento_Widget':
> Module 'Magento_Quote':
> Module 'Magento_SalesSequence':
> Module 'Magento_Payment':
> Module 'Magento_CmsUrlRewrite':
> Module 'Magento_Config':
> Module 'Magento_ConfigurableImportExport':
> Module 'Magento_Msrp':
> Module 'Magento_CatalogInventory':
> Module 'Magento_Contact':
> Module 'Magento_Cookie':
> Module 'Magento_Cron':
> Module 'Magento_CurrencySymbol':
> Module 'Magento_Bundle':
> Module 'Magento_CustomerImportExport':
> Module 'Magento_Deploy':
> Module 'Magento_Developer':
> Module 'Magento_Dhl':
> Module 'Magento_Authorization':
> Module 'Magento_Downloadable':
> Module 'Magento_ImportExport':
> Module 'Magento_Sales':
> Module 'Magento_Email':
> Module 'Magento_User':
> Module 'Magento_Fedex':
> Module 'Magento_GiftMessage':
> Module 'Magento_Checkout':
> Module 'Magento_GoogleAnalytics':
> Module 'Magento_Ui':
> Module 'Magento_GroupedImportExport':
> Module 'Magento_GroupedProduct':
> Module 'Magento_DownloadableImportExport':
> Module 'Magento_CatalogRule':
> Module 'Magento_Security':
> Module 'Magento_LayeredNavigation':
> Module 'Magento_Marketplace':
> Module 'Magento_MediaStorage':
> Module 'Magento_ConfigurableProduct':
> Module 'Magento_Multishipping':
> Module 'Magento_NewRelicReporting':
> Module 'Magento_Newsletter':
> Module 'Magento_OfflinePayments':
> Module 'Magento_SalesRule':
> Module 'Magento_PageCache':
> Module 'Magento_Captcha':
> Module 'Magento_Vault':
> Module 'Magento_Persistent':
> Module 'Magento_ProductAlert':
> Module 'Magento_ProductVideo':
> Module 'Magento_CheckoutAgreements':
> Module 'Magento_Reports':
> Module 'Magento_RequireJs':
> Module 'Magento_Review':
> Module 'Magento_Robots':
> Module 'Magento_Rss':
> Module 'Magento_CatalogRuleConfigurable':
> Module 'Magento_Authorizenet':
> Module 'Magento_SalesInventory':
> Module 'Magento_OfflineShipping':
> Module 'Magento_ConfigurableProductSales':
> Module 'Magento_UrlRewrite':
> Module 'Magento_CatalogSearch':
> Module 'Magento_Integration':
> Module 'Magento_SendFriend':
> Module 'Magento_Shipping':
> Module 'Magento_Signifyd':
> Module 'Magento_Sitemap':
> Module 'Magento_Paypal':
> Module 'Magento_Swagger':
> Module 'Magento_Swatches':
> Module 'Magento_SwatchesLayeredNavigation':
> Module 'Magento_Tax':
> Module 'Magento_TaxImportExport':
> Module 'Magento_TestModuleDirectoryZipCodes':
> Module 'Magento_TestModuleSample':
> Module 'Magento_GoogleAdwords':
> Module 'Magento_Translation':
> Module 'Magento_GoogleOptimizer':
> Module 'Magento_Ups':
> Module 'Magento_SampleData':
> Module 'Magento_EncryptionKey':
> Module 'Magento_Usps':
> Module 'Magento_Variable':
> Module 'Magento_Braintree':
> Module 'Magento_Version':
> Module 'Magento_Webapi':
> Module 'Magento_WebapiSecurity':
> Module 'Magento_Weee':
> Module 'Magento_CatalogWidget':
> Module 'Magento_Wishlist':
> Schema post-updates:
> Module 'Magento_Store':
> Module 'Magento_AdvancedPricingImportExport':
> Module 'Magento_Directory':
> Module 'Magento_Theme':
> Module 'Magento_Backend':
> Module 'Magento_Backup':
> Module 'Magento_Eav':
> Module 'Magento_Customer':
> Module 'Magento_BundleImportExport':
> Module 'Magento_CacheInvalidate':
> Module 'Magento_AdminNotification':
> Module 'Magento_Indexer':
> Running schema recurring...
> Module 'Magento_CatalogImportExport':
> Module 'Magento_Cms':
> Module 'Magento_Rule':
> Module 'Magento_Catalog':
> Running schema recurring...
> Module 'Magento_Search':
> Module 'Magento_CatalogUrlRewrite':
> Running schema recurring...
> Module 'Magento_Widget':
> Module 'Magento_Quote':
> Module 'Magento_SalesSequence':
> Module 'Magento_Payment':
> Module 'Magento_CmsUrlRewrite':
> Module 'Magento_Config':
> Module 'Magento_ConfigurableImportExport':
> Module 'Magento_Msrp':
> Module 'Magento_CatalogInventory':
> Running schema recurring...
> Module 'Magento_Contact':
> Module 'Magento_Cookie':
> Module 'Magento_Cron':
> Module 'Magento_CurrencySymbol':
> Module 'Magento_Bundle':
> Running schema recurring...
> Module 'Magento_CustomerImportExport':
> Module 'Magento_Deploy':
> Module 'Magento_Developer':
> Module 'Magento_Dhl':
> Module 'Magento_Authorization':
> Module 'Magento_Downloadable':
> Module 'Magento_ImportExport':
> Module 'Magento_Sales':
> Module 'Magento_Email':
> Module 'Magento_User':
> Module 'Magento_Fedex':
> Module 'Magento_GiftMessage':
> Module 'Magento_Checkout':
> Module 'Magento_GoogleAnalytics':
> Module 'Magento_Ui':
> Module 'Magento_GroupedImportExport':
> Module 'Magento_GroupedProduct':
> Module 'Magento_DownloadableImportExport':
> Module 'Magento_CatalogRule':
> Module 'Magento_Security':
> Module 'Magento_LayeredNavigation':
> Module 'Magento_Marketplace':
> Module 'Magento_MediaStorage':
> Module 'Magento_ConfigurableProduct':
> Running schema recurring...
> Module 'Magento_Multishipping':
> Module 'Magento_NewRelicReporting':
> Module 'Magento_Newsletter':
> Module 'Magento_OfflinePayments':
> Module 'Magento_SalesRule':
> Module 'Magento_PageCache':
> Module 'Magento_Captcha':
> Module 'Magento_Vault':
> Module 'Magento_Persistent':
> Module 'Magento_ProductAlert':
> Running schema recurring...
> Module 'Magento_ProductVideo':
> Module 'Magento_CheckoutAgreements':
> Module 'Magento_Reports':
> Running schema recurring...
> Module 'Magento_RequireJs':
> Module 'Magento_Review':
> Module 'Magento_Robots':
> Module 'Magento_Rss':
> Module 'Magento_CatalogRuleConfigurable':
> Module 'Magento_Authorizenet':
> Module 'Magento_SalesInventory':
> Module 'Magento_OfflineShipping':
> Module 'Magento_ConfigurableProductSales':
> Module 'Magento_UrlRewrite':
> Module 'Magento_CatalogSearch':
> Module 'Magento_Integration':
> Running schema recurring...
> Module 'Magento_SendFriend':
> Module 'Magento_Shipping':
> Module 'Magento_Signifyd':
> Module 'Magento_Sitemap':
> Module 'Magento_Paypal':
> Module 'Magento_Swagger':
> Module 'Magento_Swatches':
> Module 'Magento_SwatchesLayeredNavigation':
> Module 'Magento_Tax':
> Module 'Magento_TaxImportExport':
> Module 'Magento_TestModuleDirectoryZipCodes':
> Module 'Magento_TestModuleSample':
> Module 'Magento_GoogleAdwords':
> Module 'Magento_Translation':
> Module 'Magento_GoogleOptimizer':
> Module 'Magento_Ups':
> Module 'Magento_SampleData':
> Module 'Magento_EncryptionKey':
> Module 'Magento_Usps':
> Module 'Magento_Variable':
> Module 'Magento_Braintree':
> Module 'Magento_Version':
> Module 'Magento_Webapi':
> Module 'Magento_WebapiSecurity':
> Module 'Magento_Weee':
> Running schema recurring...
> Module 'Magento_CatalogWidget':
> Module 'Magento_Wishlist':
> Running schema recurring...
> Data install/update:
> Module 'Magento_Store':
> Module 'Magento_AdvancedPricingImportExport':
> Module 'Magento_Directory':
> Module 'Magento_Theme':
> Module 'Magento_Backend':
> Module 'Magento_Backup':
> Module 'Magento_Eav':
> Module 'Magento_Customer':
> Module 'Magento_BundleImportExport':
> Module 'Magento_CacheInvalidate':
> Module 'Magento_AdminNotification':
> Module 'Magento_Indexer':
> Module 'Magento_CatalogImportExport':
> Module 'Magento_Cms':
> Module 'Magento_Rule':
> Module 'Magento_Catalog':
> Module 'Magento_Search':
> Module 'Magento_CatalogUrlRewrite':
> Module 'Magento_Widget':
> Module 'Magento_Quote':
> Module 'Magento_SalesSequence':
> Module 'Magento_Payment':
> Module 'Magento_CmsUrlRewrite':
> Module 'Magento_Config':
> Module 'Magento_ConfigurableImportExport':
> Module 'Magento_Msrp':
> Module 'Magento_CatalogInventory':
> Module 'Magento_Contact':
> Module 'Magento_Cookie':
> Module 'Magento_Cron':
> Module 'Magento_CurrencySymbol':
> Module 'Magento_Bundle':
> Module 'Magento_CustomerImportExport':
> Module 'Magento_Deploy':
> Module 'Magento_Developer':
> Module 'Magento_Dhl':
> Module 'Magento_Authorization':
> Module 'Magento_Downloadable':
> Module 'Magento_ImportExport':
> Module 'Magento_Sales':
> Module 'Magento_Email':
> Module 'Magento_User':
> Module 'Magento_Fedex':
> Module 'Magento_GiftMessage':
> Module 'Magento_Checkout':
> Module 'Magento_GoogleAnalytics':
> Module 'Magento_Ui':
> Module 'Magento_GroupedImportExport':
> Module 'Magento_GroupedProduct':
> Module 'Magento_DownloadableImportExport':
> Module 'Magento_CatalogRule':
> Module 'Magento_Security':
> Module 'Magento_LayeredNavigation':
> Module 'Magento_Marketplace':
> Module 'Magento_MediaStorage':
> Module 'Magento_ConfigurableProduct':
> Module 'Magento_Multishipping':
> Module 'Magento_NewRelicReporting':
> Module 'Magento_Newsletter':
> Module 'Magento_OfflinePayments':
> Module 'Magento_SalesRule':
> Module 'Magento_PageCache':
> Module 'Magento_Captcha':
> Module 'Magento_Vault':
> Module 'Magento_Persistent':
> Module 'Magento_ProductAlert':
> Module 'Magento_ProductVideo':
> Module 'Magento_CheckoutAgreements':
> Module 'Magento_Reports':
> Module 'Magento_RequireJs':
> Module 'Magento_Review':
> Module 'Magento_Robots':
> Module 'Magento_Rss':
> Module 'Magento_CatalogRuleConfigurable':
> Module 'Magento_Authorizenet':
> Module 'Magento_SalesInventory':
> Module 'Magento_OfflineShipping':
> Module 'Magento_ConfigurableProductSales':
> Module 'Magento_UrlRewrite':
> Module 'Magento_CatalogSearch':
> Module 'Magento_Integration':
> Module 'Magento_SendFriend':
> Module 'Magento_Shipping':
> Module 'Magento_Signifyd':
> Module 'Magento_Sitemap':
> Module 'Magento_Paypal':
> Module 'Magento_Swagger':
> Module 'Magento_Swatches':
> Module 'Magento_SwatchesLayeredNavigation':
> Module 'Magento_Tax':
> Module 'Magento_TaxImportExport':
> Module 'Magento_TestModuleDirectoryZipCodes':
> Module 'Magento_TestModuleSample':
> Module 'Magento_GoogleAdwords':
> Module 'Magento_Translation':
> Module 'Magento_GoogleOptimizer':
> Module 'Magento_Ups':
> Module 'Magento_SampleData':
> Module 'Magento_EncryptionKey':
> Module 'Magento_Usps':
> Module 'Magento_Variable':
> Module 'Magento_Braintree':
> Module 'Magento_Version':
> Module 'Magento_Webapi':
> Module 'Magento_WebapiSecurity':
> Module 'Magento_Weee':
> Module 'Magento_CatalogWidget':
> Module 'Magento_Wishlist':
> Data post-updates:
> Module 'Magento_Store':
> Module 'Magento_AdvancedPricingImportExport':
> Module 'Magento_Directory':
> Module 'Magento_Theme':
> Running data recurring...
> Module 'Magento_Backend':
> Module 'Magento_Backup':
> Module 'Magento_Eav':
> Module 'Magento_Customer':
> Module 'Magento_BundleImportExport':
> Module 'Magento_CacheInvalidate':
> Module 'Magento_AdminNotification':
> Module 'Magento_Indexer':
> Running data recurring...
> Module 'Magento_CatalogImportExport':
> Module 'Magento_Cms':
> Module 'Magento_Rule':
> Module 'Magento_Catalog':
> Module 'Magento_Search':
> Module 'Magento_CatalogUrlRewrite':
> Module 'Magento_Widget':
> Module 'Magento_Quote':
> Module 'Magento_SalesSequence':
> Running data recurring...
> Module 'Magento_Payment':
> Module 'Magento_CmsUrlRewrite':
> Module 'Magento_Config':
> Module 'Magento_ConfigurableImportExport':
> Module 'Magento_Msrp':
> Module 'Magento_CatalogInventory':
> Module 'Magento_Contact':
> Module 'Magento_Cookie':
> Module 'Magento_Cron':
> Module 'Magento_CurrencySymbol':
> Module 'Magento_Bundle':
> Module 'Magento_CustomerImportExport':
> Module 'Magento_Deploy':
> Module 'Magento_Developer':
> Module 'Magento_Dhl':
> Module 'Magento_Authorization':
> Module 'Magento_Downloadable':
> Module 'Magento_ImportExport':
> Module 'Magento_Sales':
> Module 'Magento_Email':
> Module 'Magento_User':
> Module 'Magento_Fedex':
> Module 'Magento_GiftMessage':
> Module 'Magento_Checkout':
> Module 'Magento_GoogleAnalytics':
> Module 'Magento_Ui':
> Module 'Magento_GroupedImportExport':
> Module 'Magento_GroupedProduct':
> Module 'Magento_DownloadableImportExport':
> Module 'Magento_CatalogRule':
> Module 'Magento_Security':
> Module 'Magento_LayeredNavigation':
> Module 'Magento_Marketplace':
> Module 'Magento_MediaStorage':
> Module 'Magento_ConfigurableProduct':
> Module 'Magento_Multishipping':
> Module 'Magento_NewRelicReporting':
> Module 'Magento_Newsletter':
> Module 'Magento_OfflinePayments':
> Module 'Magento_SalesRule':
> Module 'Magento_PageCache':
> Module 'Magento_Captcha':
> Module 'Magento_Vault':
> Module 'Magento_Persistent':
> Module 'Magento_ProductAlert':
> Module 'Magento_ProductVideo':
> Module 'Magento_CheckoutAgreements':
> Module 'Magento_Reports':
> Module 'Magento_RequireJs':
> Module 'Magento_Review':
> Module 'Magento_Robots':
> Module 'Magento_Rss':
> Module 'Magento_CatalogRuleConfigurable':
> Module 'Magento_Authorizenet':
> Module 'Magento_SalesInventory':
> Module 'Magento_OfflineShipping':
> Module 'Magento_ConfigurableProductSales':
> Module 'Magento_UrlRewrite':
> Module 'Magento_CatalogSearch':
> Module 'Magento_Integration':
> Module 'Magento_SendFriend':
> Module 'Magento_Shipping':
> Module 'Magento_Signifyd':
> Module 'Magento_Sitemap':
> Module 'Magento_Paypal':
> Module 'Magento_Swagger':
> Module 'Magento_Swatches':
> Module 'Magento_SwatchesLayeredNavigation':
> Module 'Magento_Tax':
> Module 'Magento_TaxImportExport':
> Module 'Magento_TestModuleDirectoryZipCodes':
> Module 'Magento_TestModuleSample':
> Module 'Magento_GoogleAdwords':
> Module 'Magento_Translation':
> Module 'Magento_GoogleOptimizer':
> Module 'Magento_Ups':
> Module 'Magento_SampleData':
> Module 'Magento_EncryptionKey':
> Module 'Magento_Usps':
> Module 'Magento_Variable':
> Module 'Magento_Braintree':
> Module 'Magento_Version':
> Module 'Magento_Webapi':
> Module 'Magento_WebapiSecurity':
> Module 'Magento_Weee':
> Module 'Magento_CatalogWidget':
> Module 'Magento_Wishlist':
> Nothing to import.
> 
> [2017-11-13 14:24:09 UTC] Job "setup:upgrade {"command":"setup:upgrade"}" has been successfully completed
> [2017-11-13 14:24:09 UTC] Job "setup:static:regenerate []" has started
> 
> [2017-11-13 14:24:09 UTC] Cleaning generated files...
> [2017-11-13 14:24:09 UTC] Clearing cache...
> [2017-11-13 14:24:09 UTC] Cleaning static view files
> [2017-11-13 14:24:09 UTC] Job "setup:static:regenerate []" has been successfully completed
> [2017-11-13 14:24:09 UTC] Job "setup:maintenance:disable []" has started
> 
> [2017-11-13 14:24:09 UTC] An error occurred while executing job "setup:maintenance:disable []": Could not complete setup:maintenance:disable [] successfully: Magento maintenance mode was not disabled. It can be disabled from the Magento Backend.
> [2017-11-13 15:25:01 CET] There was an error in previous Update attempt.

**Comment by andy17612** [comment]
I with you same issuee... system upgrade FAIL on last step: maintenance disable it's made a rollback loop.
I installed new 2.2.0(no data) test to upgrade 2.2.1...same issuee..i dont know why...

**Comment by ghost** [comment]
Same problem here. The Update to 2.2.1 is completed but now it hangs on the error with the rollback message. Any suggestions some one? Thank you.
![error update rollback message](https://user-images.githubusercontent.com/15247780/32776442-db6aa91c-c932-11e7-8467-d1cf75dbabec.png)

**Comment by evensis** [comment]
My first thought is permission problems, can you try:

http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

Let's rule this out first to help the core team.

**Comment by andy17612** [comment]
i tryed but same problem @evensis

**Comment by ghost** [comment]
@evensis Yes this has already been done. But it does not remove the error and rollback messages from the web setup page. Thanks for the help so far.

**Comment by evensis** [comment]
Hmm, are any errors being dropped in var/log/exceptions.log or the system.log? Is anything getting into your nginx/apache logs either? Also, any new entries in the var/report folder?

**Comment by andy17612** [comment]
No. no anything. did not prompt.... @evensis

**Comment by evensis** [comment]
Usual thing with nothing being output by Magento for an error, is something in an XML, but they are always a pain in the backside to dig out. 

Can one of you debug and step through to see what's going on?

Goto: Magento\Framework\Console\Cli and put a break point beginning of run() and see where it takes you.

Sometimes needs a little bit of digging rather than an off the shelf solution unfortunately. I can't reproduce your issue either which makes things difficult.

**Comment by andy17612** [comment]
same problem @evensis

**Comment by magento-engcom-team** [comment]
@gaboreszaki, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.1

**Comment by fabianus76** [comment]
Same problem here. 
It seems that the upgrade worked out fine (I do not have any issues since about one week after upgrade) but no more update or integration of pulugins is possible as the "rollback" message remains. 
Does anybody have an idea on how to get rid of this message?

Thanks a lot for any feebdack !

**Comment by ghost** [comment]
@fabianus76 Yes that is exactly  what is going on. No Error in the log everything works out fine but it still gives the error message. I hope some one finds a solution for this.

Thanks for the interest and sharing the this (the same) issue

**Comment by fabianus76** [comment]
@koopjesboom 
Solution: just had to delete/rename this file:    /var/.update_error.flag

**Comment by ghost** [comment]
@fabianus76  Very good, problem solved now! All the credits go to fabianus76 Thank you very much.

**Comment by andy17612** [comment]
i upgraded, but becoming very slowly, do you know why? or need run some command? thank you
@koopjesboom @fabianus76

**Comment by gaboreszaki** [comment]
@rigu12 
is there something in the logs? (magento_insallation_folder/var/log/error.log)
in my case, magento usually slow when a some module not working properly... 


@fabianus76 
Your solution not tested yet, but i will do it tomorrow

**Comment by andy17612** [comment]
@gaboreszaki 
var/log/ have no error.log file.
now look like turtle speed..i have optimized but still very very slowly

**Comment by andy17612** [comment]
But have debug.log, exception.log and system.log @gaboreszaki

**Comment by ghost** [comment]
If you are using Cpanel check the server information.
Sometimes this information could show you some information that helps.

In my case my swap was full (too small)

I asked hosting to look into this for me.
I will report back here.

![swap load](https://user-images.githubusercontent.com/15247780/33318973-08a069de-d43d-11e7-9482-14d9b624589e.png)

**Comment by andy17612** [comment]
@koopjesboom 
Yes I’m using cPanel .but I can not find this page , which button name,thankyou

**Comment by ghost** [comment]
@rigu12 

Hosting told me something was wrong with open processes which stayed open for too long or did not close. So the server was beaten up too much. That resulted in a very slow server.

The button/link on your request:


![button](https://user-images.githubusercontent.com/15247780/33328465-5b270358-d45a-11e7-95ce-c383f1c876c6.png)

 best regards Bram

**Comment by andy17612** [comment]
Hello
my server information have not show this. but How can i improve? @koopjesboom
Best regards!

**Comment by ghost** [comment]
@rigu12  Ask your hosting they can access things you can not access and they can see things you can not see. They can also run some tests.

You can test your website too, it will give you a insight in how your site preforms and gives advice what to do. [gtmetrix.com](https://gtmetrix.com/ ) or [tools.pindom.com](https://tools.pingdom.com/)
But see it not as perfect these tests but as a lead to enhance your speed.

Best regards Bram.
