### ISSUE TITLE
Issues With DHL & UPS Shipping methods

### ISSUE THREAD

**Issue by leoncito73** [magento/magento2#12211]
### Preconditions

1.  Magento CE 2.2.0 and 2.2.1
2. Php 7.0.25

### Steps to reproduce

1.  Admin: Stores>Configuration>Shipping Methods>DHL
![captura de pantalla 2017-11-13 a las 15 05 40](https://user-images.githubusercontent.com/31698668/32727337-dfd866a0-c884-11e7-8845-af86e87f9874.png)
This have the correct parameters gave to me in DHL after to sign a few contracts.

2. Admin: Stores>Configuration>Shipping Methods>UPS
![captura de pantalla 2017-11-13 a las 15 06 59](https://user-images.githubusercontent.com/31698668/32727209-6212060e-c884-11e7-8c6b-3237ebc93dfc.png)
This is standard parameters 

3. All products have weight, the shipping settings was fill up correctly (I prove the table rates and works)

### Expected result

1. To show the shipping methods with the prices 
2. Tables rate works 

### Actual result

1. [Screenshot, logs]
![captura de pantalla 2017-11-13 a las 15 13 46](https://user-images.githubusercontent.com/31698668/32727510-6d672d4e-c885-11e7-8b4a-1931a355ea1f.png)
![captura de pantalla 2017-11-13 a las 15 14 06](https://user-images.githubusercontent.com/31698668/32727522-7a0e56f8-c885-11e7-9f0d-743d6b1988d8.png)

**Comment by orlangur** [comment]
Please check shipping logs to find out what exactly was the response of DHL/UPS.

**Comment by leoncito73** [comment]
@orlangur Thanks for your answer. My apologise I'm not expert to Magento, where I can find the Shipping log?

**Comment by magento-engcom-team** [comment]
@leoncito73 We cannot reproduce this issue as described. Are the correctly set origin shipping address, Weight Unit to storeview? Is the user's delivery address correct (country and zip code)? Please add more Screenshots or logs, and any other information needed to reproduce your issue.

**Comment by leoncito73** [comment]
@magento-engcom-team 
In the follow image is the setup of my store about the Origin Shipping, address, weight unit and store info.
![github-info1](https://user-images.githubusercontent.com/31698668/32794777-7e44811e-c972-11e7-9c9d-b656a05048e2.jpg)
And in this image is the user info delivery address correct and the shipping result
![github-info2](https://user-images.githubusercontent.com/31698668/32794824-9b1b1690-c972-11e7-8e97-f7e9fbfdc19b.jpg)

PD: @orlangur ask me about the shipping log to find the response of DHL/UPS, but unfortunately I can't find this log, can you please tell me where to find it?

**Comment by orlangur** [comment]
@leoncito73 it is located in `var/log` of your Magento instance, not sure whether it's some separate `dhl.log` / `shipping.log` or just `support_debug.log` / `exception.log`.

**Comment by leoncito73** [comment]
@orlangur thanks for the info, I found only the exception.log (30mb of info) I did a "search by words" with, "UPS, DHL" with not any result, with "shipiment" have a lot of results, but i don't understand nothing, what I should search? 

This is a little part to the log file (but repeat a lot into it):
![captura de pantalla 2017-11-15 a las 15 04 45](https://user-images.githubusercontent.com/31698668/32837571-bc9e4464-ca16-11e7-875b-213add6715ed.png)

**Comment by orlangur** [comment]
@leoncito73 nice finding, such generic exception may lead to result you observe.

You need to find out why `sales_shipment` table is missing in your database, probably Magento reinstallation is needed.

**Comment by leoncito73** [comment]
@orlangur Thanks for the help, need to understand something if I reinstall Magento (previously make a backup) and use this backup to recover my job (is a bit too much) this will rewrite the new database, do I will have the same error again? or my old DB will rewrite only the affected tables?
and one more question, is any chance to find only the tables missing for the shipping and add only this?

**Comment by orlangur** [comment]
Yeah, with restored database it will be the same.

Options possible:
1) Do a clean Magento installation into another database and then copy missing tables into your one
2) Find modules corresponding to missing tables (Magento_Shipping?), remove corresponding lines from `setup_module` and run `setup:upgrade` which will reinstall those modules

**Comment by leoncito73** [comment]
@orlangur Thanks again.. I'll try one of this option and I'll comment the result.

**Comment by leoncito73** [comment]
@orlangur I did the procedure number one and I checked all, and I found this table sales_shipment but I have a prefix in all tables, could be this the problem? the module is looking for the table without prefix? 
look my tables:
![captura de pantalla 2017-11-15 a las 21 33 03](https://user-images.githubusercontent.com/31698668/32856303-16be89d2-ca4d-11e7-948f-2006d396338e.png)
If you can see the previous Attachment the code is searching xxx_magout.sale_shipment, but in realty, if I'm not wrong, should to search this xxx_magout.mgou_sale_shipment (with prefix)

PS:In the new installation of magento the database and the tables are exactly the same than original tables from the site

**Comment by leoncito73** [comment]
@orlangur I tried also just copy that tables from a new installation  of magento without prefix, and deleting the tables with prefix, but the result is the same, not working

I'll like to try the option 2, but I'm not sure what you want to say.
You want I find:
1 - The module what call to this tables, right? But how I know? If, I find this module or modules What I should do?
2 - In the setup_module What lines I have to remove?

Can you explain me with a little bit details? I'm new on this, and sometimes is hard to understand some obvious things
Thanks

PS: did you check my last comment? it is possible bring problems the prefix?

**Comment by leoncito73** [comment]
@orlangur @magento-engcom-team 
any idea?

**Comment by magento-engcom-team** [comment]
@leoncito73, thank you for your report.
We've created internal ticket(s) MAGETWO-84730 to track progress on the issue.

**Comment by leoncito73** [comment]
@magento-engcom-team thanks..

**Comment by pradeeprcs** [comment]
Hi All,

i also face a same issue when i  enable the ups method  only  that is 

1. select valid address and navigate to Payment block
2. go to home page 
3. go to checkout page again
4. in shipping step of checkout page , shipping  address is valid one  but it show error  

"This shipping method is currently unavailable. If you would like to ship using this shipping method, please contact us. "

after debug i come to know at the time of shipping rate calculation  region_id is not sending 

if i enable tablerate method it works fine because tablerate as validation rules for region id 

so if we modify the 
vendor\magento\module-ups\view\frontend\web\js\model\shipping-rates-validation-rules.js and in rules add a region also that is 
```

 getRules: function () {
            return {
                'postcode': {
                    'required': true
                },
                'country_id': {
                    'required': true
                },
                'region_id': {
                    'required': true
                },
                'region_id_input': {
                    'required': true
                }
            };
        }
```

write a mixins for vendor\magento\module-ups\view\frontend\web\js\model\shipping-rates-validation-rules.js and add region data as rules so when ever region was modifed data will also post 


write a mixins for vendor\magento\module-ups\view\frontend\web\js\model\shipping-rates-validation-rules.js and add region data as rules so when ever region was modifed data will also post 

@magento-engcom-team :- i am not sure when you modify the postcode why region id is sending empty , if we add region in validation rules then it will send proper region id , while posting the data why its not taking from form ?  hope that will solve the issue

**Comment by magento-engcom-team** [comment]
@leoncito73, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
