### ISSUE TITLE
PHP 7.0.25 - Magento 2.2 establish connection to mssql with sqlsrv_connect from apache2 but not from crontab.

### ISSUE THREAD

**Issue by king-themes** [magento/magento2#12212]
### Preconditions

1.  PHP 7.0.25
2. Magento 2.2.1
3. `public function getStocksFromERP() {`
	`set_time_limit(0);`
	`$connectionOptions = array(
		"Database" => ERPconnection::MSSQL_DATABASE,
		"Uid" => ERPconnection::MSSQL_USERNAME,
		"PWD" => ERPconnection::MSSQL_PASSWORD
	);`
	`$conn = sqlsrv_connect( ERPconnection::MSSQL_HOST, $connectionOptions );`
`}`

### Steps to reproduce

1. I load a custom module admin form and run the function by pressing a button.

### Expected result

1. Establish connection to mssql server.

### Actual result

1. Connection establishing.

# From magento crontab

### Preconditions

1.  PHP 7.0.25
2. Magento 2.2.1
3. `public function getStocksFromERP() {`
	`set_time_limit(0);`
	`$connectionOptions = array(
		"Database" => ERPconnection::MSSQL_DATABASE,
		"Uid" => ERPconnection::MSSQL_USERNAME,
		"PWD" => ERPconnection::MSSQL_PASSWORD
	);`
	`$conn = sqlsrv_connect( ERPconnection::MSSQL_HOST, $connectionOptions );`
`}`

### Steps to reproduce

1.  `<job name="ca_erp_stock_update" instance="Codearmada\Risterp\Model\Cron" method="cronUpdateInventory">`
		`<schedule>*/15 * * * *</schedule>`
	`</job>`
2. `public function cronUpdateInventory()`
	`{`
		`$this->_stockUpdate->getStocksFromERP();`
	`}`

### Expected result

1. After 15 min the function runs and establish connection to mssql server.

### Actual result

1. From cron_schedule table the function executed but not finished.

I did a lot of tests putting log messages before and after the order in question.
The conclusion is that when running from crontab, it does not recognize the sqlsrv_connect command.

**Comment by orlangur** [comment]
> The conclusion is that when running from crontab, it does not recognize the sqlsrv_connect command.

Even if this is true, how is that related to Magento? Looks like list of enabled extensions is different for you web and CLI version of PHP, whatever extension `sqlsrv_connect` function belongs to.

**Comment by king-themes** [comment]
# For Apache2
/etc/php/7.0/apache2/php.ini contains:
1. extension=sqlsrv.so
2. extension=pdo_sqlsrv.so

Also in  phpinfo.php we see:
1. sqlsrv > ExtensionVer > 4.3.0
2. pdo_sqlsrv > ExtensionVer > 4.3.0

# From crontab
For CLI
/etc/php/7.0/cli/php.ini contains:
1. extension=sqlsrv.so
2. extension=pdo_sqlsrv.so

Also when I run php [testsql.txt](https://github.com/magento/magento2/files/1467466/testsql.txt), connection is establishing.
See result: ![sqlsrv_image](https://user-images.githubusercontent.com/6034377/32734397-924b2f74-c89a-11e7-87b2-99afcd032453.jpg)

So outside magento the cli php7 runs the sqlsrv_connection function. But from magento crontab not.

**Comment by orlangur** [comment]
> From cron_schedule table the function executed but not finished.

Do you see any errors in logs? Please check script output with something like https://askubuntu.com/questions/309853/getting-output-from-a-cron-job-on-the-terminal also

**Comment by king-themes** [comment]
I modified the code as follows:

`$_logger->info( 'Before sqlsrv_connect' );`
`$_logger->info( phpversion() );`

		`$conn = sqlsrv_connect( ERPconnection::MSSQL_HOST, $connectionOptions );`

`$_logger->info( 'After sqlsrv_connect' );`

## Output from Apache2:
[2017-11-13 17:56:03] main.INFO: Before sqlsrv_connect [] []
[2017-11-13 17:56:03] main.INFO: 7.0.25-1~dotdeb+8.1 [] []
[2017-11-13 17:56:04] main.INFO: After sqlsrv_connect [] []
And the connection established.

## Output from crontab:
[2017-11-13 18:00:06] main.INFO: Before sqlsrv_connect [] []
[2017-11-13 18:00:06] main.INFO: 7.0.25-1~dotdeb+8.1 [] []
And of course the function started but never finished.

There are no other errors in logs.

**Comment by ghost** [comment]
@king-themes, Microsoft SQL Server is not officially supported. Please see [Magento 2 documentation](https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html).
