### ISSUE TITLE
magento 2.1.7 customer/account/create server not found

### ISSUE THREAD

**Issue by ArtesanoGifts** [magento/magento2#12228]
after successful importation of magento files from live server to local host everything were fine except when I tried to do customer sign up

### Preconditions

1. Magento 2.1.7
2. PHP 7.0.22
3. Base URL : http://127.0.1.1/luxmariae.test.devel/
4. Secure Base URL : https://127.0.1.1/luxmariae.test.devel/

### Steps to reproduce

1. Customer Sign up
2. 
3. 

### Expected result

1. Upon clicking Sign up, customer directed to customer/account/create page.

         "127.0.1.1/luxmariae.test.devel/customer/account/create"

### Actual result

directed to : luxmariae.test.devel/customer/account/create server not found

if I manually change the url to 127.0.1.1/luxmariae.test.devel/customer/account/create, it works

**Comment by magento-engcom-team** [comment]
@ArtesanoGifts, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
