### ISSUE TITLE
sku attribute save error

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1222]
i changed sku scope from global to website then i saved successfully.again i changed sku scope from website to global... i'm trying to save.but i'm getting following error.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribute_id' in 'where clause', query was: DELETE FROM `catalog_product_entity` WHERE (attribute_id = '70') AND (store_id IN(1, 2))

**Comment by vpelipenko** [comment]
@sivajik34, thank you fro posting this issue. We've created internal ticket for that: MAGETWO-37045.

**Comment by kokoc** [comment]
@sivajik34 The fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?

**Comment by sivajik34** [comment]
so sku scope should be global only.i mean observed we cant edit.its working fine.thank u.

**Comment by LSERRE** [comment]
It should be the same for category_ids.
