### ISSUE TITLE
Magento2 non used attributes shown in cart

### ISSUE THREAD

**Issue by matin73** [magento/magento2#12230]
### Preconditions
Magento 2.2.1
PGP 7.0.25
MYSQL 5.7

### Steps to reproduce
Add several attributes to default attribut set, for example color, size and material. Set "visible in cart" for attribute. Add configurable product and add only 1 attribut to child products, for example color. Go to shop and add a product to cart. In cart ALL attributes are visible for product.

### Expected result
Only added attribute of child product should be visible in cart.

On product view page for more information available attribute-products should be shown or nothing.

### Actual result
In cart ALL attributes are visible for product. Also attribtes are set to "not available" for configurable products - this also is wrong message. This should show all available colors or nothing.

Also attribtes are set to "not available" for configurable products - this also is wrong message. This should show all available colors or nothing.
![unbenannt-4](https://user-images.githubusercontent.com/3177275/32767379-6bedaf9a-c913-11e7-8da8-44ed7780b3e9.jpg)

**Comment by matin73** [comment]
... there is another issue with configurable products and attribute. added attribute is shown twice in cart - once for child (selcted) product with correct info of color (s. screenshot Farbe: gelb) and once for "master" product of configurable product with info "no" (s. screenshot Farbe: nein)
![unbenannt-5](https://user-images.githubusercontent.com/3177275/32767624-82077e90-c914-11e7-96ee-aa10379c44e3.jpg)

**Comment by magento-engcom-team** [comment]
@matin73 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by matin73** [comment]
We have added several attributes to default attribute-set, like "size, color, manufacturer, material ...". all these attributes have for storefront properties "Visible on Catalog Pages on Storefront" > yes and "Visible in checkout" -> yes. 

Then we created configurable product and choosed only 1 of these attributes for child products. for example for this kind of configurable product we only need color, but we do not need size oder material. 

Magento shows all attributes in cart. for example size and material is also shown in checkout, also if we did not set attribute to child product or "main" product. Magento shows for not setted attribtes "no". but this is wrong, because not setted attributes should not shown at all in cart.

and there is another issue concerning configurabel products in cart. magento shows for example color twice. once for selected child product with correct value (screenshot "Farbe: gelb") and a second time in next line magento shows same attribute once more with info "no" (screenshot Farbe: nein). I think second time for "farbe" is from main-configurable product. but showing this info is wrong.

second issue is on product detail page in tab "more information". there are also shown all attributes of attribute-set, also if attribtes are not set to products. messeage is "not available". but the attribute should not been shown at all.

**Comment by magento-engcom-team** [comment]
@matin73 , thank for your feedback. In clean installation in attribute product "Visible in checkout" is not present. 
![attr_0891280870](https://user-images.githubusercontent.com/31669971/32785080-40e1c82c-c959-11e7-9ea0-cf41a981ae4d.png)
Add more information about this

**Comment by matin73** [comment]
aah ... thanks. it is comming from firegento extension ... an how can i display attribute on checkout process??

**Comment by matin73** [comment]
my fault - magento is default showing correct attribute in checkout!

**Comment by ishakhsuvarov** [comment]
@matin73 Thanks for the update. Should we close the ticket now?

**Comment by matin73** [comment]
yes - thanks

**Comment by magento-engcom-team** [comment]
@matin73, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
