### ISSUE TITLE
New Cart Rule : Small styles issue because of styles-old.css

### ISSUE THREAD

**Issue by Triloworld** [magento/magento2#12231]
Text is cut because of left margin.

### Preconditions
1. Working Magento 2
2. Compiled default styled from backend

### Steps to reproduce
1. Have configured one website with name SHOP.NAME
2. Go to Marketing -> Cart Rules -> New Cart Rule
3. When page load go immediately (no input provided) to section "Store View Specific Labels" and unfold
4. Check if labels are on left and they are cut. Even more, they duplicate.

### Expected result
1. In one line with others item. After all, not cut.

### Actual result
1. Screen provided

![zrzut ekranu 2017-11-14 o 09 44 16](https://user-images.githubusercontent.com/2671726/32770573-6f8fbafa-c920-11e7-8343-65c9858ccea1.png)

In right section you can see "margin-left: 0". Comment to see how it is better. I think there is even duplicate show of name but more obvious is text being cut.
This is done by "styles-old.css".

**Comment by magento-engcom-team** [comment]
@Triloworld, thank you for your report.
We've created internal ticket(s) MAGETWO-83819 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @Triloworld. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1146 by @serhii-balko in 2.2-develop branch
Related commit(s):
 - cdff30d4fe148979269ec95fd51f00048f4289d7

The fix will be available with the upcoming patch release.
