### ISSUE TITLE
how i can get customer token for Braintree implementation 

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [magento/magento2#12238]
how i can get customer token for Braintree implementation  in magento 2 with REST API? because in magento 2 braintree payment need payment_me‌​thod_nonce and customer_token for payment using REST.

**Comment by magento-engcom-team** [comment]
@dodiya-divyarajsinh, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
And see this
http://devdocs.magento.com/guides/v2.1/payments-integrations/vault/payment-token.html
Thank you.
