### ISSUE TITLE
Upgrade to 2.2.1 from 2.1.10 Guest checkout not working anymore

### ISSUE THREAD

**Issue by feelinc** [magento/magento2#12232]
### Preconditions
1. PHP 7.0
2. Magento 2.2.1

### Steps to reproduce
1. Allow Guest Checkout enabled in admin.
2. Execute below CLI commands : 

```
rm -rf generated/metadata generated/code
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex
php bin/magento setup:static-content:deploy -f
```
3. Refresh cache from admin.
4. Try checkout as guest.

### Expected result
1. Able to see the checkout page.
2. Using PayPal able to continue the payment.

### Actual result
1. Login popup always appear after "Go to Checkout" or "Proceed to Checkout" button clicked.
2. PayPal popup automatically canceled and warning message login required appear.

**Comment by feelinc** [comment]
I'm very sorry, this is my mistake. The guest checkout working correctly.

**Comment by ifeltsweet** [comment]
@feelinc, I have the same problem as you described. How did you manage to fix it?
