### ISSUE TITLE
AddressExtensionInterface is not an interface

### ISSUE THREAD

**Issue by nathanmerrill** [magento/magento2#12245]
I'm generating a Swagger Schema for some classes of mine, and I wanted to use `\Magento\Customer\Api\Data\AddressInterface` as a parameter to one of my functions.

However, this causes Swagger to throw a 500 with the following error: `Notice: Undefined index: parameters in \/mnt\/c\/develop\/php\/mage2\/vendor\/magento\/module-webapi\/Model\/Rest\/Swagger\/Generator.php on line 704`

This is because `\Magento\Customer\Api\Data\AddressInterface` has a `setRegion()`, which takes a `\Magento\Customer\Api\Data\RegionInterface`, which has a `setExtensionAttributes()`, which takes a `\Magento\Customer\Api\Data\RegionExtensionInterface` which does not exist.

### Preconditions

1.  Magento version 2.2.0

### Steps to reproduce

1. Create an interface for Swagger WebAPI to use
2. Add a method that takes a `\Magento\Customer\Api\Data\AddressInterface`
3. Open the swagger page (at `http://your.site/swagger`)

### Expected result

1.  A 500 should not be thrown

### Actual result

1. A 500 is thrown with the error.  (A better message than "Undefined index: parameters" would also be fantastic, but that's not the scope of this issue)

**Comment by magento-engcom-team** [comment]
@nathanmerrill, thank you for your report.
We've created internal ticket(s) MAGETWO-84208 to track progress on the issue.

**Comment by okorshenko** [comment]
hi @nathanmerrill AddressExtensionInterface and \Magento\Customer\Api\Data\RegionExtensionInterface are autogenerated. All interfaces with *ExtensionInterface will be generated for your automatically. Try to execute `bin/magento setup:di:compile` and find these interfaces in `generated/code/Magento/Customer/Api/Data/RegionExtensionInterface.php`

Closing as non-issue
