### ISSUE TITLE
Product stock VS Filtered Navigation

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#12248]
**### Preconditions**
1.  PHP 7.0 +
2.  Magento 2.2.1

**### Steps to reproduce**
1.  Create 2 new attributes (multiple select)
2.  Set new attributes 'use in layered navigation navigation" to 'filterable with results'
3.  Fill in the attributes on 2 products
4. place those 2 products in a category and set that category 'is anchor' to yes
5. Put stock of one item to 'out of stock' and the other 'in stock'

**### Expected result**
1.  Or it should display all the attributes of both products in the layered navigation (where you set 'filterable with results') or it should display only 1 product (because the other is out of stock) in the layered navigation with its attributes

**### Actual result**
1.  It displays all the products price attribute but it only displays the other attributes of the one that is in stock.

**example with 3 products** 

2/3 out of stock screenshot 
![image](https://user-images.githubusercontent.com/18028151/32785461-e91ab2c2-c951-11e7-9dbc-7153f3c5a4a3.png)

1/3 out of stock screenshot
![image](https://user-images.githubusercontent.com/18028151/32785582-2de1e740-c952-11e7-8890-31c22d7483ab.png)

As you can see the 'Price' stayed the same. But all those new attributes showed up just because i putted the one with those attributes in stock. Also the one that remains out of stock has the same attributes filled in but its not counted for. You can see that 'advies verkoopprijs" also changed , this is an attribute that all 3 share.

So Price is not influenced by out of stock/ in stock but other attributes are..

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by versdivers** [comment]
What information do you want more then what i provided you? Can you show me a working example of this issue? Because i get the feeling that you guys like to quickly say its not reproducible just to not go trough the trouble to troubleshoot it descend . Out of stock Items are not shown in layered navigation except for the price.. Even a default installation has that.
