### ISSUE TITLE
Issue direct after create custom module

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#1224]
There is a problem right after the creation of custom module.As when we create the custom module 
only its module.xml in etc folder and run the url in the browser ,It throws  exception :-1 

Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. %1The following modules are outdated

and when I run this command it gives error to install pdo driver in the system .But I think I already have .

**Comment by mazhalai** [comment]
@aishwaryacedcoss can you please post the full errors. Thank you.

**Comment by vpelipenko** [comment]
Closed. There is no response from @aishwaryacedcoss.
