### ISSUE TITLE
Configure theme from CLI

### ISSUE THREAD

**Issue by joshuaadickerson** [magento/magento2#12254]
### Preconditions
1. Magento 2.2
2. 

### Steps to reproduce
1. Go to CLI and attempt
2. Attempt to configure the theme
3. Only option is to uninstsall

### Expected result
1. An option to set the default theme
2. An option to configure themes

### Actual result
1. N/A

**Comment by magento-engcom-team** [comment]
@joshuaadickerson please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this feature. The GitHub issue tracker is intended for Magento Core technical issues only.
