### ISSUE TITLE
Custom attributes do not show up in grouped products

### ISSUE THREAD

**Issue by pulaskiluke** [magento/magento2#12258]
### Preconditions

1. Magento CE 2.2.0
2. PHP 7.0

### Steps to reproduce

1. I created a bunch of custom attributes for simple products, and added them into the default attribute set.
2. I then created a bunch of simple products with those attributes
3. And then I grouped them together, and called the custom attributes from the grouped.html using:
        <thead>
        <tr>
        
            <?php if ($_product->isSaleable()): ?>
            <th class="col cat.no" scope="col"><?= /* @escapeNotVerified */ __('Cat. No.') ?></th>
            <th class="col size" scope="col"><?= /* @escapeNotVerified */ __('Size') ?></th>
	    <th class="col marker" scope="col"><?= /* @escapeNotVerified */ __('Marker') ?></th>
            <th class="col price" scope="col"><?= /* @escapeNotVerified */ __('Price') ?></th>
            <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            <?php endif; ?>
	
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
        <?php foreach ($_associatedProducts as $_item): ?>
        <tbody>
            <tr>
	       <?php if ($_product->isSaleable()): ?>
               <td><?php echo $this->escapeHtml($_item->getSKU()) ?></td>
               <td><?php echo $this->escapeHtml($_item->getSize()) ?></td>
               <td><?php echo $this->escapeHtml($_item->getMarker()) ?></td>
	       <td><?php echo $this->escapeHtml($_item->getPrice()) ?></td>	
           </tr>

### Expected result

1. I suppose to see a table with SKU, Size and Marker and Price.

### Actual result

1. I was only able to see SKU and Price which are system attributes but not the two attributes I created.

**Comment by pulaskiluke** [comment]
Refer to issue 11248: https://github.com/magento/magento2/issues/11248
Problem was solved by adding to the following file the following line at 211
vendor/magento/module-grouped-product/Model/Product/Type/Grouped.php 
At line 211 add the custom attributes you'd like to show, in my case it is:
            )->addAttributeToSelect(
                ['name', 'size', 'marker', 'price', 'special_price', 'special_from_date', 'special_to_date', 'tax_class_id']

**Comment by gouravsyscraft** [comment]
This is not working for me i define my attribute in vendor/magento/module-grouped-product/Model/Product/Type/Grouped.php on line no. 211., see below.

 )->addAttributeToSelect(
                ['name','custom_stock_status', 'price', 'special_price', 'special_from_date', 'special_to_date', 'tax_class_id']
            )
This is : custom_stock_status

and try to display on group product  vendor/magento/module-grouped-product/view/frontend/templates/product/view/type/grouped.phtml

like below. 

<?php echo $block->escapeHtml($_item->getCustomStockStatus()) ?>

But nothing is working please help me.

**Comment by CompactCodeEU** [comment]
The only thing that worked for me was 
`                    $product = $this->productRepository->get($product->getSku());
`

which is far from ideal of course as this will impact load times.
I do not get why if an attribute is set 'used in product listing' it is not used.
I can not retrieve it trough getData() nor getCustomAttribute(). 


Magento 2.2.4
We did not have this issue with Magento 2.2.1
