### ISSUE TITLE
Save and Duplicated product not working

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#12259]
**# Preconditions**

1. Magento ver. 2.2.1
2. PHP 7.0.25
3. MySQL 5.6

**# Steps to reproduce**

1. Go to admin > products > catalog
2. Choose any 
a product 
3. Click on Save & Duplicate
4. You're getting the messages Notice: Undefined offset: 0 in /home/software/public_html/vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php on line 124

**# Expected result**
Duplicated the product 

![saveand](https://user-images.githubusercontent.com/33385380/32816027-d6581ac0-c984-11e7-85d7-ac509b305b65.PNG)

**Comment by magento-engcom-team** [comment]
@testmagento2, thank you for your report.
We've created internal ticket(s) MAGETWO-83895 to track progress on the issue.

**Comment by RomaKis** [comment]
Duplicate of https://github.com/magento/magento2/issues/11532.

**Comment by magento-engcom-team** [comment]
Closed as duplicate of #11532.

**Comment by okorshenko** [comment]
Hi @testmagento2 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by lalitmalav** [comment]
configurable  products ......Save and Duplicated product not working??

do you have any  solution ??
