### ISSUE TITLE
Error when Run command grunt:exec  Magento 2.2.0 

### ISSUE THREAD

**Issue by yesman2104** [magento/magento2#12262]
### Steps to reproduce

1. Run theme on Magento 2.2.0 environment 
2. setup grunt , setup node_modules & add path theme in theme.js  .
3. Run grunt:exec 

### Expected result
 Appear error [InvalidArgumentException] >> Verify entered values of the argument and options. Unable to resolve the source file for 'frontend/Emthemes/laparis/en_US/css/styles-m.less'  

### Actual result

compiled css for theme 
1. [Screenshot, logs]
https://prnt.sc/han7jt]
https://prnt.sc/han8wg

**Comment by davidalger** [comment]
Closing as duplicate of #12271.

**Comment by riconeitzel** [comment]
see #12271 

I think I found the reason :-)
