### ISSUE TITLE
New theme does not show in "Stores > Configuration > Design" dropdown unless you first visit "CONTENT > Design > Themes"

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#1226]
**Recommended change**
My recommendation is to change the code so that a user can go directly to *Stores > Configuration > Design* and their new theme will automatically show in the "Design Theme" dropdown, _without_ having to visit *CONTENT > Design > Themes* first.

![configuration___settings___stores___magento_admin](https://cloud.githubusercontent.com/assets/129031/7442746/81f75b70-f0e3-11e4-94ca-c08c11b970a3.png)

**Steps to reproduce problem**

* Add new package and theme to `app/design/frontend/`.  For example, `app/design/frontend/Custom/theme1`. Add a `theme.xml` file to the `theme1` folder and add content like this:

```
    <theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Config/etc/theme.xsd">
        <title>Custom theme1</title>
        <parent>Magento/luma</parent>
        <media>
            <preview_image>media/preview.jpg</preview_image>
        </media>
    </theme>
```

* Go to *Stores > Configuration > Design* and look at the themes in the *Design Theme* dropdown. You will see that the "Custom theme1" theme does not show up.

* Open the *CONTENT > Design > Themes* page and then immediately navigate back to *Stores > Configuration > Design*. You will see that the "Custom theme1" value shows in the "Design Theme" dropdown. 

This process seems very unintuitive. While the [Theme documentation](http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/themes/theme-apply.html#theme-apply-apply) does tell the user to go to *CONTENT > Design > Themes* to _"make sure your theme appeared in the list of available themes"_, I am guessing that many developers will skip this step. It took me 15 minutes to figure out why my theme was not showing in the "Design Theme" dropdown, and then I finally realized that I skipped a step in the documentation.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-37454

**Comment by okorshenko** [comment]
@erikhansen Thank you for reporting.  Ticket MAGETWO-37454 is Closed and delivered to mainline. Please, see https://github.com/magento/magento2/commit/97061190e05ffc8d792c33b07febcb7173ad99ea
Please, let us know if you still have an issue

**Comment by erikhansen** [comment]
@okorshenko Thanks!
