### ISSUE TITLE
After upgrading from Magento 2.1.8 to Magento 2.2.0, Customer registration is not working

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#12264]
Preconditions

I am using Latest version of Magento 2.2.1
Steps to reproduce

While upgrade from Magento 2.1.8 to Magento 2.2.0 (Or) Magento 2.1.9 to Magento 2.2.1
Customer registration on Magento frontend is not working
For a fresh installation customer registration is working
Expected result

After upgrading from Magento 2.1.9 to Magento 2.2.1
Clicking the Create Account Button and filled all the required fields.
After filling all the required fields, I clicked submit but the page simply loads there is no response for new account creation or checking if the customer is already registered is not working.
But it is working in magento 2.2.1 fresh installation.
Actual result

After upgrading from Magento 2.1.9 to Magento 2.2.1
Customer registration page only show the create account page again, after submitting the registration.

**Comment by magento-engcom-team** [comment]
@sasilinux , Please, you do not need to create duplicates. You already created the same problem [#12260](https://github.com/magento/magento2/issues/12260)
