### ISSUE TITLE
Magento 2.2.1 Customer registration in frontend is not working

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#12260]
### Preconditions

1. I am using Latest version of Magento 2.2.1 

### Steps to reproduce

1. While upgrade from Magento 2.1.8 to Magento 2.2.0 (Or) Magento 2.1.9 to Magento 2.2.1
2.  Customer registration on Magento frontend is not working
3.  For a fresh installation customer registration is working

### Expected result

1.  After upgrading from Magento 2.1.9 to Magento 2.2.1
2.  Clicking the Create Account Button and filled all the required fields.
3.  After filling all the required fields, I clicked submit but the page simply loads there is no response for new account creation or checking if the customer is already registered is not working.
4. But it is working in magento 2.2.1 fresh installation.
### Actual result

1. After upgrading from Magento 2.1.9 to Magento 2.2.1
2. Customer registration page only show the create account page again, after submitting the registration.

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.10, 2.2.1

**Comment by sasilinux** [comment]
I already mentioned this, Fresh magento installation didn't have a problem in customer registration. Only While upgrading the old version to Magento 2.2.1. I got this issue.

**Comment by magento-engcom-team** [comment]
@sasilinux , We have taken the following steps:

1.  Instal Magento 2.1.8 and 2.1.9.
2.  Have made an upgrade to version 2.2.1.
Actual Result: User registration works well, no problems or errors detected.

Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by sasilinux** [comment]
Php 7.0.24 and Mysql 5.7 also vanish cache installed in my server.

**Comment by shivanisdev** [comment]
Got Solution
1. First check for form key in registration.php
ref: https://magento.stackexchange.com/questions/194828/magento-2-new-customer-account-form-not-working

2. If form key is already there , them it may be browser issue(I my case it was working in all browser except chrome). In that case 
If you are on localhost try to use 127.0.01 instead of localhost or your intranet IP in my case it was like(192.0.1.103/magento2)

3. If you are already on live site and have this issue try following:
ref: -
https://stackoverflow.com/questions/15491819/magento-admin-login-not-working-in-chrome-but-works-fine-for-firefox
 Hope it help
2nd solution worked for mw

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9, 2.1.10, 2.2.1

**Comment by davidroberto** [comment]
@sasilinux i had the exact same problem. 
Finally i found that some required fields was hided by the "info" css class (in which a "0" opacity was set). These fields was needed in order to validate the form, but as there were not displayed, the form couldn't be validated. 

So you just need to fix with css the "info" class in order to correctly display all the fields.

**Comment by JanisE** [comment]
For me, it was the form key thing (ird2bcet4cse's first point). The registration template was being overridden, so the form key did not magically appear in it after the upgrade.

**Comment by sasilinux** [comment]
Yes. It is a form key thing. In Magento 2.2.0 and above, they are validating form key. After solving the form key issue it is working fine.

**Comment by katiakweb** [comment]
Sasilinux, please, explain where I need to add or edit some code to fix that... I am a newbie! Thanks!

**Comment by sasilinux** [comment]
Magento_Customer/templates/form/register.phtml
Add the below line after form tag.
`<?= $block->getBlockHtml('formkey'); ?>`

**Comment by svbackend** [comment]
ird2bcet4cse's solution works for me (Registration doesn't work in chrome, but in firefox it's working fine, fresh install magento 2.2-develop latests version) Thanks.

**Comment by infowind** [comment]
Hi Sasilinux thanks for reply solution works fine in magento 2.2.5.

**Comment by Bhim-Prasad-Lamichhane** [comment]
when I upgraded to 2.4.7, when i want to register the customer, then  I get the following issue:
"There is already an account with this email address. If you are sure that it is your email address, click here to get your password and access your account."
How can I solve this? 
above Solutions didnot work for me..

**Comment by SNarayanasamy-augment** [comment]
> when I upgraded to 2.4.7, when i want to register the customer, then I get the following issue: "There is already an account with this email address. If you are sure that it is your email address, click here to get your password and access your account." How can I solve this? above Solutions didnot work for me..

The above solution is for older versions. I am not sure about version 2.4.7. Kindly try other options. Thanks!
