### ISSUE TITLE
Lock for running indexer does not work

### ISSUE THREAD

**Issue by vadimjustus** [magento/magento2#12266]
We have several regular jobs that trigger a full reindex at some time. A full reindex takes 10 to 15 minutes. In some cases reindexing is triggerd when another reindex is still in progress (long running reindex, manual reindex, saving products in the backend). When two reindex processes run in parallel, we experience the following mysql exceptions:

```
1213 Deadlock found when trying to get lock
1146 Table 'hhshop.catalog_product_flat_1_tmp_indexer'
```

**The first exception is easily to be reproduced:**
1. execute `bin/magento indexer:reindex` in a terminal session
2. execute `bin/magento indexer:reindex` in a another terminal session

**Log for reindex 1**
```
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:50
Product Flat Data index has been rebuilt successfully in 00:01:50
Category Flat Data index has been rebuilt successfully in 00:00:02
Category Products indexer process unknown error:
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 500 OFFSET 500 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
Product Categories index has been rebuilt successfully in 00:01:25
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '245273-0-1' for key 'PRIMARY', query was: INSERT INTO `catalog_product_index_price_idx` SELECT `catalog_product_index_price_final_idx`.`entity_id`, `catalog_product_index_price_final_idx`.`customer_group_id`, `catalog_product_index_price_final_idx`.`website_id`, `catalog_product_index_price_final_idx`.`tax_class_id`, `catalog_product_index_price_final_idx`.`orig_price` AS `price`, `catalog_product_index_price_final_idx`.`price` AS `final_price`, `catalog_product_index_price_final_idx`.`min_price`, `catalog_product_index_price_final_idx`.`max_price`, `catalog_product_index_price_final_idx`.`tier_price` FROM `catalog_product_index_price_final_idx`
Product EAV index has been rebuilt successfully in 00:01:43
Catalog Rule Product index has been rebuilt successfully in 00:00:09
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:01
Catalog Search index has been rebuilt successfully in 00:01:14
Product/Target Rule index has been rebuilt successfully in 00:00:00
Target Rule/Product index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:02
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
```

**Log for reindex 2**
```
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index is locked by another reindex process. Skipping.
Product Flat Data index has been rebuilt successfully in 00:01:53
Category Flat Data index has been rebuilt successfully in 00:00:05
Category Products indexer process unknown error:
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 5000 OFFSET 500 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
Product Categories indexer process unknown error:
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 15500 OFFSET 500 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
Product Price index has been rebuilt successfully in 00:01:42
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: DELETE FROM `catalog_product_index_eav_idx`
Catalog Rule Product index has been rebuilt successfully in 00:00:07
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:02
Catalog Search index has been rebuilt successfully in 00:01:27
Product/Target Rule index has been rebuilt successfully in 00:00:00
Target Rule/Product index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:02
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
```

After such errors we experience missing products, zero prices for configurable products and empty categories. I would expect the reindex command to skip reindex for a specific indexer, if this indexer is already in progress.

**Comment by idmistir** [comment]
@vadimjustus Did you solve this somehow?

**Comment by ulftietze** [comment]
Moin,

i developed a temporary fix for this (maybe), we just get "Lock wait timeout" Exceptions. Maybe you can solve your issue temporary here until a real fix is provided.

In \Magento\Indexer\Model\Indexer:

`
     const INDEXER_LOCK_KEY = "indexer_working_lock";
    /**
     * @throws \Exception
     */
    protected function lockState()
    {
        $return = $this->context->getResources()->getConnection()->query(
            'SELECT GET_LOCK (":indexerLock", 1)', ['indexerLock' => self::INDEXER_LOCK_KEY]
        )->fetch();

        if (in_array(0, $return)) {
            throw new \Exception("Already locked.");
        }

    }

    /**
     *
     */
    protected function releaseState()
    {
        $this->context->getResources()->getConnection()->query(
            'SELECT RELEASE_LOCK(":indexerLock")', ['indexerLock' => self::INDEXER_LOCK_KEY]
        );
    }

    /**
     * Regenerate full index
     *
     * @return void
     * @throws \Exception
     */
    public function reindexAll()
    {
        try {
            $this->lockState();
        } catch (\Exception $exy) {
            $this->releaseState();
            return;
        }
        if ($this->getState()->getStatus() != StateInterface::STATUS_WORKING) {
            $state = $this->getState();
            $state->setStatus(StateInterface::STATUS_WORKING);
            $state->save();
            if ($this->getView()->isEnabled()) {
                $this->getView()->suspend();
            }
            try {
                $this->getActionInstance()->executeFull();
                $state->setStatus(StateInterface::STATUS_VALID);
                $state->save();
                $this->getView()->resume();
            } catch (\Exception $exception) {
                $state->setStatus(StateInterface::STATUS_INVALID);
                $state->save();
                $this->getView()->resume();
                throw $exception;
            }
        }
        $this->releaseState();
    }
`

**Comment by hostep** [comment]
@vadimjustus: out of curiosity: why did you close this ticket? Have you found a solution?

We run against this problem as well, on the Magento Cloud environment with Magento 2.2.2, I can see the same error as you reported in the cron_schedule table. (but cronjobs on the Magento Cloud environment are very unstable at the moment, so that might be a cause of the problem).

**Comment by vadimjustus** [comment]
Hi @hostep, since this was an Magento Commerce project we were asked to open an issue inside the Magento Partner Portal... This end up in an own in-house solution (`TechDivision_IndexSuspender`). I'll figure out whether we could publish it open source - I'll keep you up to date...

**Comment by vadimjustus** [comment]
Hi @hostep, we've published our module `TechDivision_IndexSuspender` on GitHub now. I hope this is useful for you...
https://github.com/techdivision/indexsuspender

**Comment by hostep** [comment]
Awesome, thanks @vadimjustus! I'll check it out when I find some time.
