### ISSUE TITLE
Bug when domains mismatch

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#1227]
Latest commit from develop branch on OSX 10.9 with Apache 2.2 and PHP 5.5 with OPCache:

Following condition: `core_config_data` with scope `default`, path `web/unsecure/base_url` and value `http://mage2.dev/`.

Webserver is configured with domain `http://magento2.local/`. Calling `http://magento2.local/` via a browser results in: 

> ( ! ) Fatal error: Call to a member function getFieldValue() on a non-object in magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php on line 93

Fixing this gives me:

> ( ! ) Fatal error: Call to a member function getFieldValue() on a non-object in magento2/lib/internal/Magento/Framework/App/PageCache/Kernel.php on line 65

After short research: [getHeaders](https://github.com/magento/magento2/blob/develop/lib%2Finternal%2FMagento%2FFramework%2FHTTP%2FPhpEnvironment%2FResponse.php#L26) method returns false if value is non-existent ... 

Suggestion: Return an empty `HeaderInterface` which catches the calls in the two above locations alternatively check for `false` in the two above mentioned locations.

With this fix Magento2 tries to redirect to the domain stored in the `core_config_data` table. 

Of course better would be a domain mismatch error instead of silently redirecting to the configured domain. People perhaps won't notice and start editing on their production store but thinking they are on their local development machine 😂.

**Comment by mazhalai** [comment]
@SchumacherFM Thank you for reporting this issue. This has been fixed internally and should be available soon. Also, closing this in favor of #1212, which is a duplicate.
