### ISSUE TITLE
Backend/Frontend not loading 

### ISSUE THREAD

**Issue by nuriabio** [magento/magento2#12277]
I'm using Magento 2.1.9, PHP 7.0 through Cpanel

I was editing the section Stores/Configuration/Web and then when i saved and tried to log into the admin panel looks like the css doesn't load correctly on frontend and backend and also appears a 404 error message:
https://biodelia.com/
On the system.log appears the next error:

main.CRITICAL: Invalid template file: 'Magento_Reports::js/components.phtml' in module: '' block's name: 'reports_page_head_components' [] []

What should I do?
Thank you!

**Comment by Igloczek** [comment]
It's not a support forum, but a place for bug reports, which should follow guidelines for reporting them (the content of issue that you removed at the beginning).

Ask for help on Magento Stack Exchange - https://magento.stackexchange.com/

**Comment by magento-engcom-team** [comment]
@Igloczek thank your suggestion
