### ISSUE TITLE
JavaScript minification erroneously removes // from JavaScript strings

### ISSUE THREAD

**Issue by navarr** [magento/magento2#12286]
When the minifier encounters a // in the middle of JavaScript, even when in a string, the minification will ignore it and everything afterwards.

### Preconditions
1.  Magento 2

### Steps to reproduce. 
1. Apply [this patch](https://github.com/magento/magento2/commit/9363c066945a47b6d4e12c22b33bdc12a3e0356b.patch) 
2. Run test Magento\Framework\View\Test\Unit\Template\Html\MinifierTest::testMinify

### Expected result

The test finished successfully.

### Actual result

The test fails.

**Comment by magento-engcom-team** [comment]
@navarr, thank you for your report.
We've created internal ticket(s) MAGETWO-84212 to track progress on the issue.

**Comment by pemann** [comment]
Any news on this one?

**Comment by pemann** [comment]
Magento uses JShrink library to minify js files. That library version 1.3.0 has some problems with minifying. See: https://github.com/tedious/JShrink/issues/72
Magento should either change the library or provide fix for it.

**Comment by yosefkurniawan** [comment]
Try this workaround: https://github.com/magento/magento2/issues/5835#issuecomment-259474472
It works for me by adding the configuration directly to database (table `core_config_data`) to exclude the js.
The one with modifying the config.xml might work too, I did try that but didn't work for me.

**Comment by magento-engcom-team** [comment]
@navarr, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
