### ISSUE TITLE
not all categories present / no categories present when adding products

### ISSUE THREAD

**Issue by Frankhendriks** [magento/magento2#12282]
### Preconditions

1. Magento 2.1.8
2. PHP 7
3. Mysql 5.7

### Steps to reproduce

1. try to add a product
2. when pressing the category dropdown it shows either nothing or a half complete list.
3. also, when i try to edit categories, for some categories it processes and saves editing the Description, but for some categories it does not, it shows right in the admin panel, but old Description in the front-end.

### Expected result

1.  it should show a list of all present categories.

### Actual result

1. [Screenshot, logs]
![screenshot 134](https://user-images.githubusercontent.com/33691341/32838243-944afd3c-ca10-11e7-859b-db8d04bd2ba8.png)
![screenshot 135](https://user-images.githubusercontent.com/33691341/32838244-94656c58-ca10-11e7-85ac-d1a27a6f820b.png)

**Comment by magento-engcom-team** [comment]
@Frankhendriks, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by magento-engcom-team** [comment]
@Frankhendriks, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by Frankhendriks** [comment]
any idea what could be causing the problem then? 
I am having the same problem  in 2 seperate 2.1.18 installations

**Comment by magento-engcom-team** [comment]
@Frankhendriks, try to reproduce this issue on a clean installation or latest release.
Thank you
