### ISSUE TITLE
Overselling items in situations of high load and high concurrency on a singe item

### ISSUE THREAD

**Issue by googlygoo** [magento/magento2#12287]
### Preconditions
1. Error presents itself across all OS, MySQL and PHP versions
2. This issue has been present since Magento 1.4.1.1 as the same logic still applies here though in a slightly different format. 

### Steps to reproduce
1. Edit \Magento\CatalogInventory\Observer\ReindexQuoteInventoryObserver and add a sleep statement here to simulate possible slow payment gateway response. This is not needed but does help highlight the issue easier.
```php
    public function execute(EventObserver $observer)
    {
+       sleep(3)
        // Reindex quote ids
```
2. Setup a single product that is saleable and has some stock. The amount of stock does not mater but should be high enough so orders can be placed via a load test 
3. Place orders continuously for 4 seconds. At least 3 orders are needed and one order needs to be placed after 3 seconds.

### Expected result
1. The number or items sold over the test period should be the same and the amount decreased in the products stock

### Actual result
1. Depending on timing if is found that overselling can occur. This is not so visible unless you compare orders with the stock change.

### Further discussion/insight
n digging deeper as to why in the rarest of cases where where getting overselling I found that the issue sits with the following two events. 
```xml
<event name="sales_model_service_quote_submit_before">
    <observer name="inventory" instance="Magento\CatalogInventory\Observer\SubtractQuoteInventoryObserver"/>
</event>
<event name="sales_model_service_quote_submit_success">
    <observer name="inventory" instance="Magento\CatalogInventory\Observer\ReindexQuoteInventoryObserver"/>
</event>
```
Specifically with the fact that the `SubtractQuoteInventoryObserver` in turn calls StockManagementInterface::registerProductsSale which updates the stock in the database and returns a list of StockItem objects that are then used in `ReindexQuoteInventoryObserver`. Now in "normal" behaviour this works well but fails under high concurrency on a single item as you will see below.

The simplified process is as follows
- A transaction is started, 
- The rows are locked in the stock item table for the affect items
- Stock level is correct, if so continue
- A stock item object is created (keep this in mind)
- The row is updated
- The transaction is committed releasing the lock
- Finally the array of stock item objects it returned and passed later to our second observer.

So far everything is good, we lock the table to ensure no other process is running while we check stock and update on sale.

Now the next step, `ReindexQuoteInventoryObserver, skip past the re-indexing of the stock to the section `Reindex previously remembered item`. We now loop through the list of previously fetched stock items, perform a save and add the items to the list of products to perform a price index for. This second save is where all the issues creep in. 

Let me try explain how errors can happen. I have tried to simplify it to better explain myself but if something is unclear please ask in the comments. In my examples below I will starting with a stock total of 5 and each order will order 1 product. 

So in normal operation for a single product you will see db events as follows, 
**Order 1**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 5, After 4)
**Order 1**: Stock_Item save (qty = 4)
**Order 2**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 4, After 3)
**Order 2**: Stock_Item save (qty = 3)
**Order 3**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 3, After 2)
**Order 3**: Stock_Item save (qty = 2)
**Order 4**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 2, After 1)
**Order 4**: Stock_Item save (qty = 1)
**Order 5**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 1, After 0)
**Order 5**: Stock_Item save (qty = 0)

On the other side of the spectrum where you get all 5 orders places at the exactly the same time you could get this, where all the select for update could be in the db 'queue' (for a lack of a better term) before even the first Stock_Item save can run. Note that even though the order of events are different, the final result is still the same. The product is sold out.

**Order 1**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 5, After 4)
**Order 2**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 4, After 3)
**Order 3**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 3, After 2)
**Order 4**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 2, After 1)
**Order 5**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 1, After 0)
**Order 1**: Stock_Item save (qty = 4)
**Order 2**: Stock_Item save (qty = 3)
**Order 3**: Stock_Item save (qty = 2)
**Order 4**: Stock_Item save (qty = 1)
**Order 5**: Stock_Item save (qty = 0)

Now for the case where incorrect stock can be sold. This can happen if you take for example the case above and just one Stock  Item save gets in between the select for updates As follows.

**Order 1**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 5, After 4)
**Order 2**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 4, After 3)
**Order 3**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 3, After 2)
**Order 1**: Stock_Item save (qty = 4)
**Order 4**: Select for update (row lock), Updated, Commit (Unlock) (**Stock Before 4**, After 3)
**Order 5**: Select for update (row lock), Updated, Commit (Unlock) (Stock Before 3, After 2)
**Order 2**: Stock_Item save (qty = 3)
**Order 3**: Stock_Item save (qty = 2)
**Order 4**: Stock_Item save (qty = 3)
**Order 5**: Stock_Item save (qty = 2)

### Possible solution
Now I have gone and create a simple solution but I am struggling to write the unit test here to show the bug to prove that the following fix works. But the brief solution here is to make a similar function like 
```php
private function updateStoredData()
```
but public so that it can be called, here after the stock update is set. This way when the second save() is called the modified qty will be ignored and only the changed fields will be synced to the database.
```php
            if ($this->canSubtractQty($stockItem)) {
                $stockItem->setQty($stockItem->getQty() - $orderedQty);
+               $stockItem->resetStoredData();
            }
```

### Additional Links/References
[Magento Forum](https://community.magento.com/t5/Programming-Questions/Magento-1-9-0-1-misscalculates-inventory-when-under-heavy-load/m-p/4043)
[Magento Bug Tracking](https://magento.com/tech-resources/bug-tracking/issue/index/id/743)

### Similar issue's yet different solution provided
[Concurrent checkouts can lead to negative stock](#6363)
[Race condition when placing 2 orders for product with stock of 1](#11488)

**Comment by magento-engcom-team** [comment]
@googlygoo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
