### ISSUE TITLE
SOAP Services do not work as expected.

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#12299]
### Preconditions
Magento 2.1.7, php 7.0.22, MySQL 5.7
1. I've created code in order to fetch order information using SOAP Services. It is required by the customer to use SOAP services and REST is not allowed in this task.
2. Sample code (apiUser and ApiKey are defined):
```
$request = new SoapClient('http://magento2.dev/soap?wsdl=1&services=integrationAdminTokenServiceV1', array("soap_version" => SOAP_1_2));
$token = $request->integrationAdminTokenServiceV1CreateAdminAccessToken(array("username" => $apiUser, "password" => $apiKey));
// this works fine

$wsdlUrl = 'http://magento2.dev/soap?wsdl=1&services=salesOrderManagementV1';
$opts = array(
    'http'=>array(
        'header' => 'Authorization: Bearer' . json_decode($token->result)
    )
);
$context = stream_context_create($opts);
$soapClient = new SoapClient($wsdlUrl, ['version' => SOAP_1_2, 'context' => $context]);
$soapResponse = $soapClient->__getFunctions();
// this fails

```
### Steps to reproduce
1. Just run the code

### Expected result
1. Get list of all functions in salesOrderManagementV1. It works for fine for customerAccountManagementV1 service and some other services which require authorization token

### Actual result
1.  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://magento2.dev/index.php/soap?wsdl=1&services=salesOrderManagementV1' : failed to load external entity

**Comment by magento-engcom-team** [comment]
@qsolutions-pl, thank you for your report.
We've created internal ticket(s) MAGETWO-84288 to track progress on the issue.

**Comment by jakwinkler** [comment]
Any update on this? :-)

**Comment by magento-engcom-team** [comment]
@qsolutions-pl, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
