### ISSUE TITLE
Admin catalog pages do not load

### ISSUE THREAD

**Issue by ktindle** [magento/magento2#12295]
### Preconditions

1. Magento CE 2.2.1
2. PHP 7.0.22  MySQL 5.7.20 Apache 2.4.18 (Ubuntu 16.04.3)

### Steps to reproduce

1. Install from repo.magento.com using Composer
2. Run web setup
3. Log in to the admin backend and click Catalog | Products

### Expected result

1. You should get the page telling you there are no records found

### Actual result

1. You get 'error processing your request'

/var/report has:
{"0":"Class Magento\\Catalog\\Model\\ResourceModel\\Eav\\AttributeFactory does not exist in [Magento\\ConfigurableProduct\\Model\\Product\\Type\\Configurable\\Interceptor]","1":"#0 \/var\/www\/html\/m2\/vendor\/magento\/framework\/Code\/Generator\/Autoloader.php(35): Magento\\Framework\\Code\\Generator->generateClass('Magento\\\\Configu...')\n#1 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('Magento\\\\Configu...')\n#2 [internal function]: spl_autoload_call('Magento\\\\Configu...')\n

The autoloader is failing on the configurable product class.

**Comment by magento-engcom-team** [comment]
@ktindle, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.10, 2.2.1
