### ISSUE TITLE
Magento2 urls

### ISSUE THREAD

**Issue by grepdirect** [magento/magento2#1229]
Hi to all, 
After installation all urls in magento ( for example xxx.com/admin) return 404 error.
Mod_rewrite is enable
What does that mean? 
Thank you

**Comment by mazhalai** [comment]
@grepdirect Thank you for reporting this issue. Can you check your logs and post a more detailed error?

**Comment by grepdirect** [comment]
For solving i used a strange (for me) method, 
The git clone copy all magento in a directory called magento2.
i've put the magento2 directory as documentRoot in apache (2.2) and all works now.
Sorry but now i don't have logs anymore
@mazhalai thank u for reply

**Comment by mazhalai** [comment]
@grepdirect Glad it is working now.
