### ISSUE TITLE
A display issue of a grouped product whose associated product are under various conditions compared to M1

### ISSUE THREAD

**Issue by meezin** [magento/magento2#12290]
### Preconditions

1.  I migrated data from 1.9.1.0 to 2.1.9
2. There are multiple stores at Magento1
3.  I'm testing Magento2 right away before launching M2 
4. I set display out of stock product as NO in admin page on M2. 

### Steps to reproduce

1. For example, i have 3 multiple store called A,B,C on M2
2. Make a grouped product which has a associated products under various condition. (reference #3)
3. When a associated product are a member of only website B, it has quantity and is enabled, rest of them are disabled and are members of website A , you can see this error on A website frontend. 

### Expected result

1. The grouped product shouldn't be shown on A website because i set the display none about out-of-stock item. 

### Actual result

1. [Screenshot, logs]

[![enter image description here][2]][2]

    Fatal error: Uncaught Error: Call to a member function getPriceInfo() on null in /home/staging/public_html/vendor/magento/module-grouped-product/Pricing/Price/FinalPrice.php:34 
    Stack trace: 
    #0 /home/staging/public_html/vendor/magento/module-msrp/Helper/Data.php(167): Magento\GroupedProduct\Pricing\Price\FinalPrice->getValue() 
    #1 /home/staging/public_html/vendor/magento/module-msrp/Pricing/Price/MsrpPrice.php(101): Magento\Msrp\Helper\Data->isMinimalPriceLessMsrp(Object(Magento\Catalog\Model\Product\Interceptor)) 
    #2 /home/staging/public_html/vendor/magento/module-catalog/Pricing/Render/FinalPriceBox.php(124): Magento\Msrp\Pricing\Price\MsrpPrice->isMinimalPriceLessMsrp(Object(Magento\Catalog\Model\Product\Interceptor)) 
    #3 /home/staging/public_html/vendor/magento/module-catalog/Pricing/Render/FinalPriceBox.php(81): Magento\Catalog\Pricing\Render\FinalPriceBox->isMsrpPriceApplicable() 
    #4 /home/staging/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Catalog\Pricing\Render\FinalPriceBox->_toHt in /home/staging/public_html/vendor/magento/module-grouped-product/Pricing/Price/FinalPrice.php on line 34

On Magento1, When i set the a product configuration like this 

[![enter image description here][1]][1]

**We can't see a grouped product(e.g. KBSV-AZ) on a wh website** because associated products from wh are out of stock even associated product from another website (e.g. retail) are in-stock and have few quantity. 

It truly makes sense because i set the ***display out-of-stock product** as **NO***   on Magento1.

BTW on Magento2, it is saying a error message on same environment like this 

[![enter image description here][2]][2]

i can even see this product on frontend although we set display out-of-stock as No. I assume that this is a migrated Magento 2 and it followed M1 configuration perfectly. But this is not launching website and i put the base url for another website(retail) as fake url. So Does it affect this problem? 

What do you think about this root problem? Thank you

  [1]: https://i.stack.imgur.com/BMSpu.png
  [2]: https://i.stack.imgur.com/IhVDS.png

**Comment by magento-engcom-team** [comment]
Hi @meezin , thank you for your bug report.
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.
