### ISSUE TITLE
No search result when the SKU begins with Chinese character

### ISSUE THREAD

**Issue by gilles6** [magento/magento2#12297]
### Preconditions

1. Magento 2.2.1
2. PHP 7.1

### Steps to reproduce

1. Add a Chinese character at the begining of the SKU of a product, for instance "中MySKU" ;
2. In the search bar, try to find this product ;
3. The result is "product not found".

### Expected result

1. It should list the product.

### Actual result

1. The result is not listed

**Comment by magento-engcom-team** [comment]
@gvigner, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
