### ISSUE TITLE
Meta tags not being updated

### ISSUE THREAD

**Issue by gilles6** [magento/magento2#12306]
### Preconditions

1. Magento 2.2.1
2. PHP 7.1
3. MySQL 5.7

### Steps to reproduce

1. Edit any product ;
2. Change the **Meta Keywords** in **Search Engine Optimization** and Save ;
4. Open the product page in a browser ;
5. Check if the meta tag keyword has changed in the header (with Developer Tools).

### Expected result

1. The meta tag should be updated.

### Actual result

1. The meta tag is still the old one.

My Magento is in developer mode.
I removed the browser cache and executed the following commands:
```
cd /var/www/html/MAGENTO_FOLDER
rm -rf var/cache/* var/di/* var/generation/* var/page_cache/* var/view_preprocessed/* pub/static/frontend/*
php bin/magento cache:clean
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex
php bin/magento cron:run
```

Is this a bug or did I forget something ?

**Comment by magento-engcom-team** [comment]
@gvigner, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
