### ISSUE TITLE
PayPal Module

### ISSUE THREAD

**Issue by grepdirect** [magento/magento2#1230]
Hi, I would add Paypal module to magento2, can anyone show me the best way to do that?
Thank you.

**Comment by vpelipenko** [comment]
@grepdirect, are you going to add your own integration with Paypal? According to this https://github.com/magento/magento2/issues/1089#issuecomment-81134252 we will return native integrations to code base soon.

**Comment by grepdirect** [comment]
Will depends, :+1:  How much time to Beta release? :)

**Comment by benmarks** [comment]
:soon:

**Comment by choukalos** [comment]
You've got a couple of months before we drop Merchant Beta.

**Comment by vpelipenko** [comment]
Look like we can close this issue. As @choukalos said, PayPal module will be available during next few months. @grepdirect, do you have another questions?
