### ISSUE TITLE
Cannot add custom block in sales order email template through XML

### ISSUE THREAD

**Issue by henk-hypershop** [magento/magento2#12305]
### Preconditions

1. Magento 2.2.1
2. NGINX

### Steps to reproduce

1. Add layout update to sales_email_order_renderers.xml in refereneBlock 'sales.email.order.renderers in custom theme.
2. Resend order e-mail

### Expected result

1. Custom block will show below order items in e-mail template

### Actual result

1. Block will not show up.

Added the following in app/design/Vendor/Theme/Magento_Sales/layout/sales_email_order_renderers.xml

`<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Creditmemo Items List" design_abstraction="custom">
    <body>
        <referenceBlock name="sales.email.order.renderers">
            <block class="Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder" name="test" template="Magento_Sales::email/order/template.phtml"/>
        </referenceBlock>
    </body>
</page>
`

Nothing will show up. Including a template block also does not work.

**Comment by magento-engcom-team** [comment]
@henk-hypershop, thank you for your report.
We've created internal ticket(s) MAGETWO-84211 to track progress on the issue.

**Comment by nimitaemipro** [comment]
I would like to work on this issue #MM18IN .

**Comment by pareshpansuriya** [comment]
I'm working on this #MLAU18

**Comment by XxXgeoXxX** [comment]
Looks like you have the mistake in the path to your theme.
According to the description you use app/design/Vendor/Theme/Magento_Sales/layout/sales_email_order_renderers.xml
but the correct way must be
app/design/**frontend**/Vendor/Theme/Magento_Sales/layout/sales_email_order_renderers.xml
link to documentation https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-structure.html
