### ISSUE TITLE
 salesShipOrderV1 - Ship Date element?

### ISSUE THREAD

**Issue by JakeOB25** [magento/magento2#12313]
Hello. I am using the salesShipOrderV1 method to post shipping information to Magento2 from our fulfillment software.  I'm able to successfully create the shipment (along with carrier information and tracking numbers), however I can't find a way to indicate a shipment DATE in the post.  When the post is made, it uses the current date/time as the shipment date, which will not work in this situation.  Has anyone found success in doing this?  Thanks!

### Preconditions
1. Magento 2.1.9
2. post /V1/order/{orderId}/ship 

### Steps to reproduce
1. Post the following request to: http://_magento2host_/index.php/rest/V1/order/99999/ship

{
"items": [
{
"orderItemId": 417,
"qty": 1
}
],
"notify": true,
"tracks": [
{
"trackNumber": "1z9999999999999999",
"title": "UPS",
"carrierCode": "UPS"
}
]
}

### Expected result
I would like to be able to pass a shipment date ("createdAt", for example) that would record the shipment for a specific date/time.

### Actual result
The shipment date is recorded as the current date/time

Screenshot:
![ui_result](https://user-images.githubusercontent.com/20074662/32911227-8837434c-cad9-11e7-961e-4fa426abea1f.jpg)

**Comment by magento-engcom-team** [comment]
@JakeOB25 Thank you for your submission. 
according to Swagger its not possible to add creation date to shipping track information via API post call
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
