### ISSUE TITLE
Magento 2.2 Basic CSV Import Fails

### ISSUE THREAD

**Issue by thebeachtoday** [magento/magento2#12316]
Arch: Ubuntu 14.04.5 LTS,  PHP 7.0.25, MySQL 5.720, Magento 2.2.0

GUI: From back office, Settings - Import
Functional Actions: Attempt to import an extremely simple CSV file, created via notepad with UTF-8 encoding [i.e. just these two lines].  Verified no newline characters or extra spaces/tabs:

sku,product_type,attribute_set_code,name,price
1234,simple,Default,Test,10

Result: Would expect a simple import, but instead I get error "General system exception happened"
No lines are added to the logs files as a result; no reports.  Thus no more information to help troubleshoot.

**Comment by magento-engcom-team** [comment]
@thebeachtoday , Thank You for Your report.
In names and values of attributes not use spaces.

`sku,product_type,attribute_set_code,name,price`
`1234,simple,Default,Test,10`

**Comment by thebeachtoday** [comment]
Can anyone get any CSV imports working on 2.2?  I have a fresh install and
it won't import a basic CSV.  Not sure how this is expected behavior.  Why
have the import Link if the expected behavior is NOT to import.  I hope I'm
misinterpreting.

There are no spaces, tabs or newline indicators.  It's encoded with UTF-8.
  I'm sure I'm missing something very basic in settings or something, but
Googlingbthe error gives no solution. No logging to help either.  Is there
a way to turn on more verbose logging?  Other locations aside from normal
log files?

**Comment by magento-engcom-team** [comment]
@thebeachtoday, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by sadon** [comment]
Same issue with M2 EE 2.1.8 
can be resolved by adding column _attribute_set_code_ for each product

**Comment by Techiescot** [comment]
I have the same issue.  A clean install of 2.2 Trying to Import simple CSV throws up the error:

Validation Results 

No such entity.

can NOT be resolved by adding column attribute_set_code for each product as this is what I have

**Comment by thebeachtoday** [comment]
I switched to PrestaShop - literally 10 minutes to get set up and running.
Not as user-friendly from GUI perspective, but everything else about PS is
much, much better than Magento.  Long-term, much more savings as well

**Comment by gijsvb57** [comment]
Had to change the contents of the attribute_set_code column to the id of the attributeset to get the import working in magento CE 2.2.3.

Using the attribute set code in the column I get the message:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`hakpro`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DELETE), query was: INSERT INTO `catalog_product_entity` (`updated_at`,`attribute_set_id`,`entity_id`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `updated_at` = VALUES(`updated_at`), `attribute_set_id` = VALUES(`attribute_set_id`)
