### ISSUE TITLE
Orders fail to create when there are no sequence tables

### ISSUE THREAD

**Issue by 4DallasC** [magento/magento2#12318]
We've progressively updated Magento 2 through its versions and for a period there, Magento was not generating the sales_sequence tables for some of the stores. Now when one of those stores are selected as the default store view, saving orders now throw the error:-

Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES () 

Does anyone know of a work around to re-generate the sales_sequence tables? To to stop using the sales_sequence tables? 

1. Install Magento 2.1.6
2. Create a new store/store view.
3. upgrade to Magento 2.1.9
4. Change the default store view to the newly created store
5. Try adding an order

### Expected result
1. Order is created

### Actual result
Trace: #0 vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `` ...', Array)
#4 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `` ...', Array)
#5 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `` ...', Array)
#6 vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `` ...', Array)
#7 vendor/magento/module-sales-sequence/Model/Sequence.php(82): Zend_Db_Adapter_Abstract->insert(NULL, Array)
#8 app/code/Oscar/MultiStore/Plugin/QuoteGetReservedOrderId.php(30): Magento\SalesSequence\Model\Sequence->getNextValue()
#9 vendor/magento/framework/Interception/Interceptor.php(142): Oscar\MultiStore\Plugin\QuoteGetReservedOrderId->aroundGetReservedOrderId(Object(Magento\Quote\Model\ResourceModel\Quote\Interceptor), Object(Closure), Object(Magento\Quote\Model\Quote))
#10 var/generation/Magento/Quote/Model/ResourceModel/Quote/Interceptor.php(26): Magento\Quote\Model\ResourceModel\Quote\Interceptor->___callPlugins('getReservedOrde...', Array, Array)
#11 vendor/magento/module-quote/Model/Quote.php(2163): Magento\Quote\Model\ResourceModel\Quote\Interceptor->getReservedOrderId(Object(Magento\Quote\Model\Quote))
#12 vendor/magento/module-quote/Model/QuoteManagement.php(435): Magento\Quote\Model\Quote->reserveOrderId()
#13 vendor/magento/module-quote/Model/QuoteManagement.php(391): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#14 vendor/magento/module-sales/Model/AdminOrder/Create.php(1893): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote), Array)
#15 vendor/magento/module-sales/Controller/Adminhtml/Order/Create/Save.php(49): Magento\Sales\Model\AdminOrder\Create->createOrder()
#16 vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Create\Save->execute()
#17 vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#18 vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#19 vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callParent('dispatch', Array)
#20 vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Array, 'adminAuthentica...')
#21 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Array, 'adminMassaction...')
#24 vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 generation/Magento/Sales/Controller/Adminhtml/Order/Create/Save/Interceptor.php(26): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#27 vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#28 vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#29 vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#30 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#31 vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#34 vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#35 vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#36 index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#37 {main} [] []

**Comment by magento-engcom-team** [comment]
Hello @4DallasC , thank You for your report.
Please describe us in details this step :
"3. upgrade to Magento 2.1.9"

**Comment by southerncomputer** [comment]
go to mysql /phpmyadmin and check out sales_sequence_meta and sales_sequence_profile and make them jive manually! Easy stuff!

**Comment by wget** [comment]
We are able to reproduce the problem on Magento 2.1.8 CE. The problem seems to be linked [with this one](https://github.com/ubertheme/module-ubdatamigration/issues/7#issuecomment-202425765). While the records should be recreated automatically when we are migrating store views, this isn't the case in practice.
![screenshot_20171122_102213](https://user-images.githubusercontent.com/2997662/33119448-5f41d32c-cf6f-11e7-9831-fad87b8087e7.png)
We can see on the screenshots, the table records for store views 2 to 8 are missing.

Creating a new store view properly recreates the records, but the problem still persists
![capture d ecran 2017-11-21 a 21 35 42](https://user-images.githubusercontent.com/2997662/33119520-8b9ded2a-cf6f-11e7-86b3-0da7bd95388e.png)


.

**Comment by magento-engcom-team** [comment]
@4DallasC , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
Steps we did:
1. Install Magento 2.1.6
2. Create additional store and storeview.
3. Create simple product.
4. Upgrade Magento to 2.1.9
5. Navigate to storefront.
6. Change store to additional one.
7. Place order.
Result: Order placed successfully.

**Comment by 4DallasC** [comment]
Hello @magento-engcom-team 
you need to set the newly created store in 2.1.6 to be the default store before creating the order.
So change the default in the website to the new store, change the default store view in the store. Then navigate to the storefront and place an order.

You can double check that the newly created store doesn't have the sequence tables in the database. I think the event to create the sequence tables was removed in those versions around 2.1.3 - 2.1.6, but has made a return in 2.1.9.

**Comment by magento-engcom-team** [comment]
@4DallasC thanks for feedback. Unfortunately we still can not reproduce this issue.
New steps:
1. Install Magento 2.1.6
2. Create additional store and storeview.
3. Set newly created store as default.
4. Create simple product.
5. Upgrade Magento to 2.1.9
6. Navigate to storefront(additional store).
7. Place order.
Result: Order placed successfully.
Also we tried set additional store as default after upgrade to 2.1.9, and result is the same - order placed successfully.
Please add more information to steps. or try to reproduce this issue on clean installation. Looks like we still missing some important details.

**Comment by magento-engcom-team** [comment]
@4DallasC, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by wget** [comment]
Thanks for closing this ticket.

The problem was due to data coming from an outdated 1.5 installation for which the needed sales sequences records weren't available.

On my side, I have been able to fix the issue by adding the needed records to that table, [like described here](https://github.com/ubertheme/module-ubdatamigration/issues/7#issuecomment-202425765).

The SQL procedure I have developed is this one:
```
-- Needed in order for the MySQL/MariaDB client to execute the procedure in a
-- row rather than stop at the first END statement it finds.
delimiter //

-- Parameter are IN by default in MariaDB
create or replace procedure fix_sales_sequences(in p_store_id int)
begin

  -- Note: We are using user-defined variables
  select max(meta_id) into @last_meta_id
  from sales_sequence_meta;
  
  store_id_loop: loop
    
    -- sequence_order
    set @last_meta_id = @last_meta_id + 1;
    insert into sales_sequence_meta(meta_id, entity_type, store_id, sequence_table)
    values (@last_meta_id, 'order', p_store_id, concat('sequence_order_', p_store_id));
    
    set @sequence_order_create = concat('create table `sequence_order_', p_store_id, '` (
        `sequence_value` int(10) unsigned not null auto_increment,
         primary key (`sequence_value`)
    ) engine=innodb default charset=utf8 collate=utf8_unicode_ci;');
    prepare stmt from @sequence_order_create;
    execute stmt;
    deallocate prepare stmt;

    insert into sales_sequence_profile(profile_id, meta_id, start_value, step, max_value, warning_value, is_active)
    values(@last_meta_id, @last_meta_id, 1, 1, 4294967295, 4294967295, 1);

    -- sequence_invoice
    set @last_meta_id = @last_meta_id + 1;
    insert into sales_sequence_meta(meta_id, entity_type, store_id, sequence_table)
    values (@last_meta_id, 'invoice', p_store_id, concat('sequence_invoice_', p_store_id));
    
    set @sequence_invoice_create = concat('create table `sequence_invoice_', p_store_id, '` (
    `sequence_value` int(10) unsigned not null auto_increment,
    primary key (`sequence_value`)
    ) engine=innodb default charset=utf8 collate=utf8_unicode_ci;');
    prepare stmt from @sequence_invoice_create;
    execute stmt;
    deallocate prepare stmt;

    insert into sales_sequence_profile(profile_id, meta_id, start_value, step, max_value, warning_value, is_active)
    values(@last_meta_id, @last_meta_id, 1, 1, 4294967295, 4294967295, 1);
    
    -- sequence_creditmemo
    set @last_meta_id = @last_meta_id + 1;
    insert into sales_sequence_meta(meta_id, entity_type, store_id, sequence_table)
    values (@last_meta_id, 'creditmemo', p_store_id, concat('sequence_creditmemo_', p_store_id));
    
    set @sequence_creditmemo_create = concat('create table `sequence_creditmemo_', p_store_id, '` (
    `sequence_value` int(10) unsigned not null auto_increment,
    primary key (`sequence_value`)
    ) engine=innodb default charset=utf8 collate=utf8_unicode_ci;');
    prepare stmt from @sequence_creditmemo_create;
    execute stmt;
    deallocate prepare stmt;

    insert into sales_sequence_profile(profile_id, meta_id, start_value, step, max_value, warning_value, is_active)
    values(@last_meta_id, @last_meta_id, 1, 1, 4294967295, 4294967295, 1);
    
    -- sequence_shipment
    set @last_meta_id = @last_meta_id + 1;
    insert into sales_sequence_meta(meta_id, entity_type, store_id, sequence_table)
    values (@last_meta_id, 'shipment', p_store_id, concat('sequence_shipment_', p_store_id));

    set @sequence_shipment_create = concat('create table `sequence_shipment_', p_store_id, '` (
    `sequence_value` int(10) unsigned not null auto_increment,
    primary key (`sequence_value`)
    ) engine=innodb default charset=utf8 collate=utf8_unicode_ci;');
    prepare stmt from @sequence_shipment_create;
    execute stmt;
    deallocate prepare stmt;
    
    insert into sales_sequence_profile(profile_id, meta_id, start_value, step, max_value, warning_value, is_active)
    values(@last_meta_id, @last_meta_id, 1, 1, 4294967295, 4294967295, 1);

    
    set p_store_id = p_store_id + 1;
    if p_store_id < 10 then
    	iterate store_id_loop;
    end if;
    leave store_id_loop;
    
  end loop store_id_loop;
end; //

delimiter ;
```

Calling the procedure is done by the following call for example, where the parameter is the table number to start from:
```
call fix_sales_sequences(2);
```

**Comment by andrewhowdencom** [comment]
Hola all; 

These tables are created during the event dispatch:

```
$this->eventManager->dispatch('store_add', ['store' => $store]);
```

If you find them missing (or need to repair them), that's where you need to look!
