### ISSUE TITLE
Customizing the insert widget type 'Catalog Products List' template

### ISSUE THREAD

**Issue by jimmypinto** [magento/magento2#12315]
I'm adding the widget on a page by going ->Insert Widget ->Widget type-> Catalog Products List After adding the widget, I can see the template path as 'template="product/widget/content/grid.phtml"'. I'm trying to update this template but working on a wrong file I guess. What is the full path for the template file?

**Comment by magento-engcom-team** [comment]
Hello @jimmypinto. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
