### ISSUE TITLE
Meta Keywords in non-latin characters are not searchable

### ISSUE THREAD

**Issue by gilles6** [magento/magento2#12319]
### Preconditions

1. Magento 2.2.1
2. PHP 7.1

### Steps to reproduce

1. In the backend, make **Meta Keywords** searchable: `Stores` > `Attributes` > `Product` > **meta_keyword** > `Attribute Information` > `Storefront Properties` > `Use in Search` > **Yes**
<img width="615" alt="screen shot 2017-11-17 at 14 38 16" src="https://user-images.githubusercontent.com/612946/32933390-04d88958-cba5-11e7-8cca-38d14a691847.png">
<img width="1148" alt="screen shot 2017-11-17 at 14 39 58" src="https://user-images.githubusercontent.com/612946/32933503-3768e91c-cba5-11e7-97b5-b0a86b5658f5.png">
<img width="1075" alt="screen shot 2017-11-17 at 14 40 35" src="https://user-images.githubusercontent.com/612946/32933596-5fc91dbe-cba5-11e7-8525-e0fb57421b0f.png">

2. Open any product, add the following Chinese character "中" in `Search Engine Optimization` > `Meta Keywords` and **Save**
<img width="883" alt="screen shot 2017-11-17 at 14 43 54" src="https://user-images.githubusercontent.com/612946/32934005-0ddd0884-cba6-11e7-965c-2456ddf48bb5.png">

3. In the frontend with the search bar, look for the character "中".

### Expected result

1. It should display, at least, the product containing the Meta Keyword "中".

### Actual result

1. No result is found.

**Comment by magento-engcom-team** [comment]
@gvigner, thank you for your report.
We've created internal ticket(s) MAGETWO-84035 to track progress on the issue.

**Comment by gilles6** [comment]
Thank you for you reply.

The problem seems more general. I have created a new attribute with similar options to "Product Name", and its Chinese characters content is not searchable while content in latin characters can be searched.

**Comment by webzac** [comment]
Hello @magento-engcom-team and @devondahon 
Is there a solution to this problem please?
Thank's

**Comment by HirokazuNishi** [comment]
The easiest way is to use ElasticSearch. This issue is caused by MySQL's fulltext index. I tried to use MySQL5.7's "WITH PARSER ngram" option against fulltext search data table, but it caused serious deadlock issue due to long MySQL index updating time.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30082` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
