### ISSUE TITLE
User Interface issue - Admin - Configurable Product - New Attribute

### ISSUE THREAD

**Issue by rafatga** [magento/magento2#12327]
I was adding a new attribute to a configuration product and I notice that the modal content of New attribute is not correctly display forcing the user to scroll horizontally.

Magento ver. 2.1.9
Magento ver. 2.2.1 EE

### Steps to reproduce

1. Sign in Admin panel
2. Go to catalog product
3. Add a configurable product
4. Create configuration
5. Create new attribute

### Actual result

![screen shot 2017-11-14 at 8 59 19 am](https://user-images.githubusercontent.com/3813277/32945842-44079138-cb95-11e7-9c60-de1473dde684.png)
![screen shot 2017-11-14 at 9 06 30 am](https://user-images.githubusercontent.com/3813277/32945844-46607a6c-cb95-11e7-87d2-b614573e92ff.png)
![screen shot 2017-11-14 at 9 36 03 am](https://user-images.githubusercontent.com/3813277/32945846-4923f774-cb95-11e7-8696-cbaff6fc0cf0.png)
![screen shot 2017-11-14 at 9 36 20 am](https://user-images.githubusercontent.com/3813277/32945853-4bec39bc-cb95-11e7-86fa-55e70fce6ad8.png)

**Comment by magento-engcom-team** [comment]
@hi-rafa, thank you for your report.
We've created internal ticket(s) MAGETWO-84082 to track progress on the issue.

**Comment by dasharath-wagento** [comment]
@magento-engcom-team ,
I have verified issue in 2.2-develop branch and it was fixed. When adding a new attribute using configurable's child product. It displays correctly.
So issue did not exist in 2.2-develop branch.
