### ISSUE TITLE
Bug with CDATA in XML layout update

### ISSUE THREAD

**Issue by VegtMedia-Alex** [magento/magento2#12322]
When you enter the first time a xml with CDATA it works as expected. After saving the CDATA tag is gone. More information:

https://magento.stackexchange.com/questions/199377/cdata-removed-from-layout-update-xml-after-saving-cms-page-in-magento-2

Magento version 2.2.0

The CDATA tag is added in the database field, so it gets stripped when they view is outputting the code from the database.

It happens in this file:
/vendor/magento/module-ui/TemplateEngine/Xhtml/Result.php

<img width="997" alt="screen shot 2017-11-17 at 11 35 49" src="https://user-images.githubusercontent.com/3672692/32943160-7ec77f22-cb8b-11e7-87d0-ba45a5d0af7e.png">

**Comment by VegtMedia-Alex** [comment]
Just solved the issue:

`protected function wrapContent($content)
    {
        return '<script type="text/x-magento-init"><![CDATA['
        . '{"*": {"Magento_Ui/js/core/app": ' . str_replace(']]>', ']]]]><![CDATA[>', $content) . '}}'
        . ']]></script>';
    }`

Hopefully someone can create a PR for this

**Comment by magento-engcom-team** [comment]
@alexvandervegt, thank you for your report.
We've created internal ticket(s) MAGETWO-84221 to track progress on the issue.

**Comment by serhii-balko** [comment]
Hi @alexvandervegt 
I don't understand, why do you think that the replace like `str_replace(']]>', ']]]]><![CDATA[>', $content)` solve the issue?

**Comment by VegtMedia-Alex** [comment]
You can test it if you check my original comment about it.

**Comment by magento-team** [comment]
Hi @alexvandervegt. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1163 by @serhii-balko in 2.2-develop branch
Related commit(s):
 - 6b224456f66673ec9f88492cadb3c0b642069730

The fix will be available with the upcoming patch release.
