### ISSUE TITLE
Wrong prices in catalog list page and into the order administration page

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#12326]
## Preconditions

Ubuntu, Standard LAMP (Apache, MySQL, ....)
Magento 2.2.0-dev
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper
HEAD -> develop

## Steps to reproduce

Go to the administration login page
Click on Sales > Order (menu)

## Expected result

Correct price value with two decimal.

## Actual result

Wrong prices in some magento parts like the catalog list and into the order administration page.

here some screenshots:

![selezione_081](https://user-images.githubusercontent.com/1553035/32945122-81c8ab54-cb92-11e7-97f8-d65e2d1f861f.png)

![selezione_080](https://user-images.githubusercontent.com/1553035/32945130-85f448fa-cb92-11e7-8c17-418e21858cd6.png)

**Comment by shinesoftware** [comment]
I have solved adding in the bootstrap these lines:

> /* For data consistency between displaying (printing) and serialization a float number */
> ini_set('precision', 14);
> ini_set('serialize_precision', 14);

as suggested here https://github.com/magento/magento2/issues/8787

**Comment by magento-engcom-team** [comment]
@shinesoftware, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1
