### ISSUE TITLE
Unable to Identify Product type of item in Invoice json

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#12325]
### Preconditions

1. Magento 2.
2. Some Products.
3. Magento Integration activated.

### Steps to reproduce

1. Create an order.
2. Check order via API (http://[your Magento server]/rest/V1/orders/[order id]/) and you will get to know product_type of each item.
3. Create an invoice.
4. Check invoice via API (http://[your Magento server]/rest/V1/invoices/[invoice id]/) 

### Expected result

product_type should be populated with invoice API.

### Actual result

Unable to Identify Product type of item in Invoice JSON

**Comment by magento-engcom-team** [comment]
@ankursachdeva11, thank you for your report.
We've created internal ticket(s) MAGETWO-84216 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi All, we saw an attempt to fix this issue, but the code has not been delivered to mainline.
See gist: https://gist.github.com/magento-engcom-team/d24235a1e964e116784f5ebf7388d777

**Comment by magento-engcom-team** [comment]
@ankursachdeva11, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
