### ISSUE TITLE
di:compile issue on magento2.2.1 fresh installation

### ISSUE THREAD

**Issue by anuox** [magento/magento2#12339]
### Preconditions

1. 
2. 

### Steps to reproduce

1. I have installed Magento 2.2.1. And then changed the mode as Developer. 
2.  Set 777 permission and then I run the setup:upgrade
3. Then I run di:compile. I am getting an error. I can able to reproduce this issue

### Actual result

1. Fatal error:  Cannot use Magento\Framework\App\Helper\Context as Context because the name is already in use in /var/www/html/magento221/vendor/magento/module-customer/Model/AttributeChecker.php on line 11

How to fix this issue?

**Comment by anuox** [comment]
![di_compile](https://user-images.githubusercontent.com/33774801/32977843-bfdcd5cc-cc5b-11e7-99b8-cd963ee35df8.png)

**Comment by southerncomputer** [comment]
php bin/magento cache:clean
then see how to deploy to development or production!
http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-mode.html

**Comment by magento-engcom-team** [comment]
@anuox, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by virgillong** [comment]
getting error also 

Fatal error: Cannot use Magento\Framework\App\Helper\Context as Context because the name is already in use in D:\xampp\htdocs\swd2\vendor\magento\module-customer\Model\AttributeChecker.php on line 11

I can remove the use statement for Context and works fine.
