### ISSUE TITLE
do not displayed products in backend magento 2

### ISSUE THREAD

**Issue by Romanst84** [magento/magento2#12331]
Re-indexed

Cleaned the cache

Check the database

![screenshot_17](https://user-images.githubusercontent.com/33752251/32949851-ef919bae-cbac-11e7-9568-1d051e348266.png)

spinner working and working
Products do not displayed

**Comment by magento-engcom-team** [comment]
@Romanst84 We need more information about this issue in order to successfully investigate potential fixes. Please use our issue tracking template to format your description. Specify the exact steps you used, the expected result of your actions, and the actual results.

**Comment by Romanst84** [comment]
After completion of Data Migration in M2.2.1, I have flushed cache and run the re-indexing command. 

But still No any Data is coming under customers, products in admin Grid. Only ajax-loader spinning infinite.

![screenshot_17](https://user-images.githubusercontent.com/33752251/32951163-a74c5ee2-cbb1-11e7-8fed-7e9980598707.png)

Whot I am do:
update indexer_state set status = 'invalid' where status != 'valid'
php -f bin/magento indexer:reindex;

I can pick up a spinner on a browser product's editing page, I reset it and change the attribute
Created a new product

I have noticed that "404 not found for pub/static/version1507091218/adminhtml/Magento/backend/en_US/js-translation.json" file in console.

php7 bin/magento setup:static-content:deploy -f

bit it not helped

**Comment by Romanst84** [comment]
I tried to run the command
php -dmemory_limit=512M bin/magento indexer:reindex
Did not help

**Comment by southerncomputer** [comment]
php bin/magento deploy:mode:set development
rm -rf <your Magento install dir>/generated/metadata/* <your Magento install dir>/generated/code/*

then 

php bin/magento deploy:mode:set production
chown -R username:username *

replace username with the owner of the magento files or php-fpm user!

**Comment by Romanst84** [comment]
Thank you for the quick response.
I did everything as you wrote.

nammucom@uk-node01 [~/public_html/m2]# php7 bin/magento deploy:mode:set developer
Enabled developer mode.
nammucom@uk-node01 [~/public_html/m2]# rm -rf /generated/metadata/* /generated/code/*
nammucom@uk-node01 [~/public_html/m2]# php7 bin/magento deploy:mode:set production
Enabled maintenance mode
Config "dev/debug/debug_logging = 0" has been saved.
Starting compilation
Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 30.0 MiB%message% 0/7 [>---------------------------]   0% < 1 sec 30.0 MiBProxies                              code generation... 0/7 [>---------------------------]   0% < 1 sec 30.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 32.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 32.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 5 secs 134.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 5 secs 134.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 5 secs 134.0 MiB
Application code generator... 3/7 [============>---------------]  42% 5 secs 134.0 MiB
Application code generator... 4/7 [================>-----------]  57% 11 secs 156.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 11 secs 156.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 19 secs 172.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 19 secs 172.0 MiB
Area configuration aggregation... 6/7 [========================>---]  85% 25 secs 238.0 MiB
Interception cache generation... 6/7 [========================>---]  85% 25 secs 238.0 MiB
Interception cache generation... 7/7 [============================] 100% 28 secs 238.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content

Deploy using quick strategy
frontend/Magento/blank/es_ES            2088/2088           ============================ 100% %  9 secs
adminhtml/Magento/backend/es_ES         2046/2046           ============================ 100% %  9 secs
frontend/Magento/blank/es_ES            2088/2088           ============================ 100% %  9 secs
adminhtml/Magento/backend/es_ES         2046/2046           ============================ 100% %  9 secs
frontend/Magento/blank/en_US            2088/2088           ============================ 100% %  8 secs
frontend/Magento/luma/es_ES             2103/2103           ============================ 100% %  11 secs
frontend/Magento/blank/es_ES            2088/2088           ============================ 100% %  9 secs
adminhtml/Magento/backend/es_ES         2046/2046           ============================ 100% %  9 secs
frontend/Magento/blank/en_US            2088/2088           ============================ 100% %  8 secs
frontend/Magento/luma/es_ES             2103/2103           ============================ 100% %  11 secs
adminhtml/Magento/backend/en_US         2046/2046           ============================ 100% %  10 secs
frontend/Magento/luma/en_US             2103/2103           ============================ 100% %  11 secs

Execution time: 65.982934951782
Deployment of static content complete
Disabled maintenance mode
Enabled production mode.
nammucom@uk-node01 [~/public_html/m2]# chown -R username:username * 
nammucom@uk-node01 [~/public_html/m2]#

I replaced username with the owner of the magento files

Did not help

Before writing a command - rm -rf /generated/metadata/* /generated/code/*
I checked this folder generated/, it was empty

**Comment by southerncomputer** [comment]
You restart your php-fpm and varnish processes?

**Comment by Romanst84** [comment]
Thanks for the quick reply

After I did reindex and clean cache

php7 bin/magento indexer:reindex
php7 bin/magento cache:clean

Or I do not understand you correctly?

**Comment by southerncomputer** [comment]
service php-fpm restart
service varnish restart

after deploy / source changes!

**Comment by southerncomputer** [comment]
if doesn't work, check for javascript errors, if none go into mysql or phpmyadmin

use mage
truncate table ui_bookmark;

change mage to your db name!

**Comment by Romanst84** [comment]
Ok. Thank you. I will do what you wrote. Thank you.

**Comment by Romanst84** [comment]
Did not help

service php-fpm restart
service varnish restart

do not use the host

truncate table ui_bookmark and change mage to your db name

when I checked for javascript errors 

![screenshot_19](https://user-images.githubusercontent.com/33752251/33017447-0b06b89c-cdfb-11e7-8dd4-49e16e9a6fc4.png)

and go to the  "at XMLHttpRequest.xhr.onreadystatechange (text.js:115)"

![screenshot_20](https://user-images.githubusercontent.com/33752251/33017478-2dcaee48-cdfb-11e7-8dc1-cd2f5858ce71.png)

**Comment by ishakhsuvarov** [comment]
Hi @Romanst84 
Please use the appropriate repository to report issues related to the data migration tool: https://github.com/magento/data-migration-tool
Thank you
