### ISSUE TITLE
Magento 2.2 - category view page reloads twice

### ISSUE THREAD

**Issue by jigardhaduk** [magento/magento2#12338]
I need to override **Toolbar.php** file from _\Magento\Catalog\Block\Product\ProductList\Toolbar_ with custom sorting attribute and this has **left join** in code. 

### Preconditions

1. Fresh Magento 2.2
2. php 7.0.22

### Steps to reproduce

1. Create any custom attribute which has code with join query.
My custom code is,
   ```
         if ($this->getCurrentOrder() == 'stock') {
                 $this->_collection->getSelect()
                        ->joinLeft(
                                'cataloginventory_stock_item AS csi',
                                'e.entity_id = csi.product_id',
                                'csi.qty AS quantity'
                        )
                    ->group('e.entity_id')
                    ->order('quantity ' . $this->getCurrentDirectionReverse());
          }

OR

**Updated**
2. Install fresh Magento 2.2.x, override **Toolbar.php** file from **\Magento\Catalog\Block\Product\ProductList\**, echo test text and reload any category page (/gear/bags.html) 
**=> It will display test text twice.**

### Expected result
<!--- Tell us what should happen -->
1. Display result as selected sort option

### Actual result
<!--- Tell us what happens instead -->
1. When I select that custom attribute for sorting, it displays below error.
 `main.CRITICAL: You cannot define a correlation name 'csi' more than once`

<!--- (This may be platform independent comment) -->


Then I have just `echo` some text in **Toolbar function** and it displays twice. 
So I hope due to reloading twice, that issue occurs.

**Comment by jigardhaduk** [comment]
Hello,
Is there anyone to help?

**Comment by magento-engcom-team** [comment]
@jigardhaduk Thanks for reporting this issue. 
Unfortunately, we could not reproduce the issue as you described it. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by jigardhaduk** [comment]
@magento-engcom-team I have added the 2nd point in **Steps to reproduce** section.
There is no any extra code or anything else.

**Comment by jigardhaduk** [comment]
Hello again,
Is there anyone to help?

**To test, just do,**
Install fresh `Magento 2.2.x`, override **Toolbar.php** file from **\Magento\Catalog\Block\Product\ProductList**, echo test text and reload any category page (/gear/bags.html)
**=> It will display test text twice.**

**Comment by magento-engcom-team** [comment]
@jigardhaduk, thank you for your report.
We've created internal ticket(s) MAGETWO-84858 to track progress on the issue.

**Comment by jigardhaduk** [comment]
@magento-engcom-team, is there any update on this issue?

I am getting a problem due to double load category page.

**Comment by thejimu** [comment]
I'm having this same issue too, I tried using session variable as a workaround but find the custom sorted collection is not reliable. Any updates?

**Comment by magento-engcom-team** [comment]
@jigardhaduk, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
