### ISSUE TITLE
Wysiwig vs UTF-8

### ISSUE THREAD

**Issue by serzhik** [magento/magento2#12333]
### Preconditions
1. Magento 2.1.2

### Steps to reproduce
1. Go to "create new product" page
2. Set Description: "für"
3. Hide Editor

### Expected result
1. Description value: `<p>"für"</p>`

### Actual result
1. Decription value: `<p>"f&uuml;r"</p>`

**Comment by magento-engcom-team** [comment]
@Serzhik, thank you for your report.
The issue is already fixed in develop branch, 2.2.1
