### ISSUE TITLE
Wrong message when moving a category

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1233]
**Scenario.**
In `Products->Categories`. I'm trying to move some categories around in the tree. Source and destination not important. When moving the second category, the overlay message that should tell me that the operation might take a long time is wrong.  

**Steps to reproduce:**
 
 - Go to `Products->Categories`
 - Add some categories if there are none
 - Move one category in the tree.
 - In the modal box that appears click OK.
![modal](http://i.imgur.com/qlzaPUr.png)
 - If the move was successful there should be a success message above the name field ![success](http://i.imgur.com/Ni75gzI.png)
 - move a second category around (it can be the same one)

**Expected result.**
I should see the modal box again with the message "This operation can take a long time"

![expected](http://i.imgur.com/qlzaPUr.png)

**Actual result**
I see the modal box with the success message from the previous move.
![result](http://i.imgur.com/6j5idHy.png)

**Comment by kokoc** [comment]
@tzyganu Thank you for reporting the issue and for detailed explanation. Internal refenrence: MAGETWO-37064

**Comment by kokoc** [comment]
@tzyganu The fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?

**Comment by tzyganu** [comment]
@kokoc  it works nicely on beta10. Thank you for the fix.
