### ISSUE TITLE
Add new customer by Admin is not showing in customer grid

### ISSUE THREAD

**Issue by syedsaleem086** [magento/magento2#12346]
### Preconditions

1. Magento2.2.0
2. PHP 7.1
3. Windows Machine

### Steps to reproduce

1. Add new customer from admin (fill all details)
2. On saving it shows successfully saved, But it is not showing in customer grid
3. Creating once again shows customer email already exist

### Expected result

1. Added customer should show in customer grid

### Actual result

1. Added customer is not displaying in customer grid

Attached snapshot
![2017-11-19_08h49_53](https://user-images.githubusercontent.com/15724424/32987082-bd63cca0-cd06-11e7-9f61-d715ac6c687e.png)

**Comment by southerncomputer** [comment]
php bin/magento indexer:reindex customer_grid

check your indexer settings and crontab setup!

**Comment by syedsaleem086** [comment]
Hi @southerncomputer 

Indexing fixed the issue.
Thanks
