### ISSUE TITLE
JSTestDriver removal

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/magento2#12342]
Currently Magento is using 2 different sets of tools for the JavaScript Testing:
 * JSTestDriver, which is considered legacy and is not supported anymore by the core team.
 * [Jasmine](https://jasmine.github.io/2.0/introduction.html), which was introduced to replace JSTestDriver. All new JS tests are implemented using it and executed in multiple CI environments, including public Travis CI and Magento's in-house CICD infrastructure.

To remove legacy framework it is required to reimplement remaining tests using Jasmine, and completely remove JSTestDriver support afterwards.

Here is the list of the JS tests which require attention:
* [ ] [`JsTestDriver/testsuite/mage/accordion/accordion.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/accordion/accordion.js)
* [ ] [`JsTestDriver/testsuite/mage/collapsible/test-collapsible.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/collapsible/test-collapsible.js)
* [ ] [`JsTestDriver/testsuite/mage/dropdown/test-dropdown.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/dropdown/test-dropdown.js)
* [ ] [`JsTestDriver/testsuite/mage/form/form-test.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/form/form-test.js)
* [ ] [`JsTestDriver/testsuite/mage/menu/test-menu.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/menu/test-menu.js)
* [ ] [`JsTestDriver/testsuite/mage/translate/translate-test.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/translate/translate-test.js)
* [ ] [`JsTestDriver/testsuite/mage/translate_inline/translate-inline-test.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/translate_inline/translate-inline-test.js)
* [ ] [`JsTestDriver/testsuite/mage/validation/test-validation.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/validation/test-validation.js)
* [ ] [`JsTestDriver/testsuite/mage/decorate-test.js`](https://github.com/magento/magento2/blob/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/decorate-test.js)
* [ ] [`JsTestDriver/testsuite/mage/calendar/*`](https://github.com/magento/magento2/tree/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/calendar)
* [ ] [`JsTestDriver/testsuite/mage/loader/*`](https://github.com/magento/magento2/tree/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/loader)
* [ ] [`JsTestDriver/testsuite/mage/suggest/*`](https://github.com/magento/magento2/tree/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/suggest)
* [ ] [`JsTestDriver/testsuite/mage/tabs/*`](https://github.com/magento/magento2/tree/2.2-develop/dev/tests/js/JsTestDriver/testsuite/mage/tabs)

**Comment by KarlDeux** [comment]
I'd like to take this.

**Comment by magento-engcom-team** [comment]
Thank you for report. Development is in progress. See related PRs

**Comment by ishakhsuvarov** [comment]
Hi @ishakhsuvarov. Thank you for your report. 
The issue has been fixed in magento/magento2#12406 by @KarlDeux in 2.2-develop branch
Related commit(s):
 - 2abaf8c50a8a8b72b5c9045fb816dd5c3ec59ea5
 - 16916212d3815d33dcd601eb72d8408099a8c287
 - ea56695cb6b5e39f9dfd86302a4daa41f5dd31da
 - 126a1e30be2b23a03063935d9199725d770d84c2
 - b3fedbc6ed90ef99f1be17c6d77d2cb0ea50fa74
 - 0117f8648080ea88848e1614ffbc62cd38cb2f38
 - 3a907c2be5becbf42ae7cc14cc4d431f7e6a14e4
 - 821bdaaba4923fa4e6fdc4749ea5c625dcfd0fe0
 - 2846c785b9b9962dfaafd8fdbb81f9d2fe4851a5
 - f4712cdda55a88ebd2c455cdb7840dae31a3334a
 - f0a18772bae4a7197fcce729ed33dfa168301731
 - 5e785eb6e03bc8cb3440a482cbefdd2a53f27cec
 - 64bf208aea55998942fe2035a9679e1f470bed8d
 - 8595da68070577bea09a342f68711f90e059fe6a
 - 2adf9e8634b4336002d2bcc39e22ffe0387239d4
 - 9b28fe25ec7da23e5c1e75499e2984e3019289f2
 - 4127a8c6bc8b0a7fd4e071ea4f2ea42ee92d5622
 - 6366f83500d2a3645d0bc0577201fc655c952abd
 - c98720f551534b53f2e8f7b475aaac0473a43750
 - de225a907f56477b767eae81134154e0398a3bf0
 - 9f148224e7540d089e1d38a1d22be725ca5cfb27
 - ad90a47b36983f354fd2958279742809fc8e4886
 - 35a1acab9193c1e737af84916284469cc426da03
 - 36cfa4543bf839931458205c51cff65136d8e89c
 - b1b001ad66c3aabe44ba155bdc9c4e150c51dad1
 - b7164820f3e0dbca3d0d55bffe6b822d5ea54a56
 - c5a17220566dc39e803fd982c7a9f0cd9a3bc8d3
 - 40e6981e5a51bf3aeaf213cef49d37376070503c
 - 2fff734b30e7e310ae2a98f1bf0687b47edf6df4
 - e51080190831075f5ae8244a2cde8ad9562d55b0
 - a667b6374e0c8cb8c9fd4fdb5ccdc35cf0ff8967
 - 574daf5b7ad134e2a914cdf2f34a4e4b2aff0e35
 - faed0c5310faaf46f660c4003561154369742912
 - ac8aa21b1b227f15b425d0defae0fe478a29def5
 - fa69aa50f567e53b91b700316ca4909058cfe82d
 - 64f9c6d7d34abfaff72e006ab93fa46ba8335f2d

The fix will be available with the upcoming patch release.
