### ISSUE TITLE
Mysql.sock

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#12357]
### Preconditions

1. MAGENTO2.2
2. PHP.7.1

### Steps to reproduce

1. magento cron:run 2>&1 | grep -v "Ran jobs by schedule"

### Actual result

1. Can somebody help and let me know what problem,thank you!

### Expected result

1. [Zend_Db_Adapter_Exception]                                                                                
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)                                                                        
  [PDOException]                                                                                             
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)                                                                                                             
cron:run [--group GROUP] [--bootstrap BOOTSTRAP]

**Comment by magento-engcom-team** [comment]
@rigu12, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice about this issue.

**Comment by LiamKarlMitchell** [comment]
PHP looks at a different default path for the unix socket location...
setup:upgrade and possibly other areas do not use what I have configured in the etc/env config!

```
    'db' => [
        'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => 'localhost',
                'dbname' => '...',
                'username' => '...',
                'password' => '...',
                'unix_socket' => '/var/run/mysqld/mysqld.sock',
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8mb4;',
                'active' => '1'
            ]
        ]
    ],
```

It should use the unix_socket not the PHP default location of the socket.


https://stackoverflow.com/questions/36639014/got-error-while-installing-module-in-magento2-sqlstate-hy000-2000-no-such-f
ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock

Or configure php.ini to look for that as the socket.

pdo_mysql.default_socket = /var/run/mysqld/mysqld.sock
mysqli.default_socket = /var/run/mysqld/mysqld.sock
mysql.default_socket = /var/run/mysqld/mysqld.sock
