### ISSUE TITLE
Custom Objects and Custom Fields

### ISSUE THREAD

**Issue by bhagvank** [magento/magento2#1235]
hi all,

This is a missing feature for creating custom classes (objects) and custom Fields. There is an extension Custom Fields but on existing objects of classes.  

Dynamically from the admin panel, ability to create custom objects and custom fields.

Bhagvan Kommadi
Vice President, SyberPlace
skype: bhagvan.kommadi

**Comment by vpelipenko** [comment]
Hi @bhagvank, not sure that I understand what you suggest to do. Could you explain your issue with more details?

**Comment by bhagvank** [comment]
hi,

I have elaborated the requirement below:

Custom objects are new objects you create to store data. While you have several standard objects automatically included, you can also build custom objects to store any type of enterprise data relevant to the application. For example, if you’re building a recruiting app, you can create custom objects called Position and Candidate to track information on job openings and candidates, respectively.

Custom object fields store the data for your custom object records. Custom objects automatically include several standard fields. One can add other custom fields to custom objects based on the type of data you want to store. One can create custom relationship fields to associate your custom object with another object.


Bhagvan Kommadi
Vice President, SyberPlace
skype: bhagvan.kommadi

**Comment by tzyganu** [comment]
Having in the core something that actually creates files that should be versioned is not a good idea.  
All generated files should stay in the non versioned folders (var for example).  

but (to self advertise a bit), I started [a project like this](https://github.com/UltimateModuleCreator/Umc_Base). It's in an very early stage now but feel free to contribute with code and/or ideas.

**Comment by choukalos** [comment]
@vrann - Eugene your thoughts?  

My $0.02 - I think what your describing is in Magento 2 as a service contract that's setup as an extensible data object on another service.

**Comment by bhagvank** [comment]
hi tzyganu,

Thank you. I can contribute to  Umc Base. Please add me as a member.


Bhagvan Kommadi
Vice President, SyberPlace
Skype: bhagvan.kommadi

**Comment by tzyganu** [comment]
@bhagvank If you have some code, do pull requests and I will integrate it the module if it's OK.

**Comment by pboisvert** [comment]
Piotr--can you evaluate from the product side or assign to an architect for review of the suggestion?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Custom-Objects-and-Custom-Fields/idi-p/45833).
