### ISSUE TITLE
PHP 5.6.30 - Magento 2.1.9 "Attempt to load value of nonexistent EAV attribute '237' for entity type 'Magento\Catalog\Api\Data\ProductInterface'"

### ISSUE THREAD

**Issue by king-themes** [magento/magento2#12352]
The message "Attempt to load value of nonexistent EAV attribute '237' for entity type 'Magento\Catalog\Api\Data\ProductInterface'" appears every time I load a product that has the custom attribute with Id= 237. It is happening in storefront and in backend.

### Preconditions

1. Magento 2.1.9
2. Eshop with 1 storeview.

### Steps to reproduce

1. Create a custom attribute, dropdown with values 'disabled', 'enabled' and code=promot1.
2. Insert it in all attribute sets.
3. Go to a product in backend and make the promot1='enabled'.

### Expected result

1. In Catalog the product to appear with promot1=enabled.
2. In product edit page the promot1 dropdown to have the value 'enabled'.

### Actual result

1. In Catalog the product appears with promot1=enabled.
2. In product edit page the promot1 dropdown has NO value.
3. In system log I have the message: "Attempt to load value of nonexistent EAV attribute '237' for entity type 'Magento\Catalog\Api\Data\ProductInterface'"
4. The same message if I try to load the product in frontend.

**Comment by magento-engcom-team** [comment]
@king-themes , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by king-themes** [comment]
I try to reproduce the issue on a clean installation on a new development server. Everything works properly and as expected. Is there any suggestion why it is happening on my production server?

**Comment by king-themes** [comment]
I compared the tables between the two databases. I specify that the development server is working properly, while the production does not. I found differences only in the tables `catalog_product_index_eav_idx` and `catalog_product_index_eav_tmp`.

 Do anyone know what exactly is the table `catalog_product_index_eav_idx` and how could this difference be corrected?

**Comment by king-themes** [comment]
Finally I solved the problem by making a new installation on my production server. Apparently something went wrong in the previous installation.
