### ISSUE TITLE
Reopen Issue #10594 (Admin session timeout after 15 minutes)

### ISSUE THREAD

**Issue by storepeinture** [magento/magento2#12358]
Hello, is it possible to reopen issue #10594.

Description is all there, and it looks like we have found a solution which also works for others.
The issue exists obviously for multiple users.

So maybe this could be taken into consideration.
- Why are the values of some stores not written correctly into the system
- Maybe our solution helps to improve this session_lifetime functionality in future M2 updates

I have one further demand which could be taken into consideration:
Is it possible to **keep Admin Backend Session open for the complete session_lifetime** even when the browser is closed and reopened. It would be great to have at least the option to say YES or NO.

Right now, when I put my computer to sleep, I lose all open tabs and I have to re-login - no matter how long the session_lifetime is.
It would be great to have this feature in the future, because it's a real annoyance while developing the store in Admin Backend.

Thank you!

**Comment by magento-engcom-team** [comment]
@storepeinture , Thank you for your submission. The Magento 2 GitHub repository is used to capture code and documentation issues. Questions should be posted to a question and answer site, such as [Stack Exchange](https://magento.stackexchange.com/) and the [Magento Forums](https://community.magento.com/), where Magento community members can quickly provide recommendations and advice.
