### ISSUE TITLE
Unable to save shipping information. Please check input data. Magento 2.2.1

### ISSUE THREAD

**Issue by sbwcws** [magento/magento2#12367]
Magento 2.2.1
PHP 7.0.25
MySql 5.7
Nginx 1.10

Steps to reproduce
Adding Product to the cart filling out customer details information  clicking NEXT give the following error

Expected result
Minicart and checkout page should load up new page to enter credit card information.

Actual result
![capture](https://user-images.githubusercontent.com/7937555/33029793-81669b74-cde7-11e7-92c3-4316f11e7868.PNG)

`Failed to load resource: the server responded with a status of 400 ()`

`// Do send the request
// This may raise an exception which is actually
// handled in jQuery.ajax (so no try/catch here)
xhr.send( ( options.hasContent && options.data ) || null );`

**Comment by magento-engcom-team** [comment]
@sbwcws, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by plentyhappy** [comment]
We have the same issue.  Intermittent problem though...  On my "to do" list for developer to examine.  Will provide the proper format for this forum.  Don't know linux version, etc. except to say had problem on 2.1.8 and the problem still exists on 2.2.1

**Comment by Kronmose** [comment]
i have the exact same problem. but it only exists when one tries to purchase a product thats either virtual or downloadable.

Products with shipping does not give the same problem.

WE have magento 2.1.9

**Comment by QKChris** [comment]
Has anyone solved this problem?
