### ISSUE TITLE
Collapse all button in category tree doesn't always work

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1236]
**Steps to reproduce.**
 - Go to `Products->Categories` in the backend
 - Select a category for editing.
 - Click on the "Collapse all" link above the tree.

**Expected result**
The category tree should collapse and only the root category should remain visible

**Actual result**
Only the child categories of the selected category collapses. The rest remain opened.

**Note**
Everything works as expected when in "Add" mode. So when there is no category selected for editing everything is fine.

**Comment by kokoc** [comment]
@tzyganu Currently, only active category remains expanded. Other root categories and sub-categories will be collapsed.
Could you please provide some usefull use cases for  proposed behavior?

**Comment by tzyganu** [comment]
@kokoc I don't have a useful case. :smile: I just thought "Collapse All" means collapse ALL. If this works as intended feel free to close this issue.

**Comment by tanya-soroka** [comment]
Hello @tzyganu . Collapse all should not hide the selected category. So when you click collapse all the selected category and part (through the category) should be visible, other category structure should be collapsed. So I think that the use-cases provided by @kokoc  is correct one.

**Comment by tzyganu** [comment]
@tanya-soroka Thanks for the explanation.This means that this is a feature not a bug. :smile: . I will close this.
