### ISSUE TITLE
Magento 2.2 upgrade and now front end not showing online

### ISSUE THREAD

**Issue by direct-brand** [magento/magento2#12365]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@direct-brand Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
