### ISSUE TITLE
Something went wrong. New Admin User with Role.

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#12364]
### Preconditions

1. Magento 2.2.0
2. mysql  Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22 

### Steps to reproduce

1. Create a new admin user role with access to Sales, Catalog, and Customers

### Expected result

1. Login as this new Admin User and work with Sales, Catalog, and Customers.
2. Go to Sales->Orders

### Actual result

1. Here is the [result](http://joxi.ru/EA4Q6vbSwBRQMr)

I figured out that one of the resource_id in the table authorization_rule is not become allowed (_allow_). It requires Magento_AdminNotification::show_list resource_id which is deny in the database for this role. 
I looked here \Magento\Authorization\Model\ResourceModel\Rules::saveRel() to understand the issue in code. 

![salescatalogcustomer](https://user-images.githubusercontent.com/10618641/33024324-740ad2de-ce13-11e7-9408-7b5a87148ec9.jpg)

**Comment by magento-engcom-team** [comment]
@AleksLi, thank you for your report.
We've created internal ticket(s) MAGETWO-84206 to track progress on the issue.

**Comment by AleksLi** [comment]
Ok, @magento-engcom-team . Thanks a lot.

**Comment by hiren2615** [comment]
Hi @AleksLi 
I have tried in Magento ver. 2.2.4-dev but I could not reproduce any issue with role. Orders grid is working fine with this new user/role.
Have any extra information to reproduce the issue?

**Comment by AleksLi** [comment]
Hi @hiren-wagento, Did you allow Sales, Catalog, and Customers - these three resources for new admin user?

**Comment by hiren2615** [comment]
Hi @AleksLi 
Yes I have allowed all resources under Sales, Catalog, and Customers to new admin user. All the 3 grids working fine with this new user.

**Comment by AleksLi** [comment]
@hiren-wagento . I'll check that one more time with new magento 2.2.4 version and give you more info about that. It could be possible that this is not an issue anymore. I'll give you more information tomorrow. Is it good for you?

**Comment by hiren2615** [comment]
Hi @AleksLi , ok, no problem.

**Comment by AleksLi** [comment]
Hi @hiren-wagento . I can't see this bug anymore. I think we could **close** this issue
