### ISSUE TITLE
Something went wront alert after deploy static content in clean install M2.2.1

### ISSUE THREAD

**Issue by pablobae** [magento/magento2#12370]
### Preconditions

1. Centos 7 64
2. Magento 2.2.1 (clean install)
3. PHP 7.0.2
4. MariaDB 10.1.29
5. Httpd 2.4.6

### Steps to reproduce

1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .
2. find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \; && chmod u+x bin/magento
3. bin/magento setup:install --base-url=XXX --db-host=localhost --db-name=XXX --db-user=XXX --db-password=XXX  --admin-firstname=XXX --admin-lastname=XXX --admin-email=XXX --admin-user=XXX --admin-password=XXX  --currency=EUR --timezone=Europe/Madrid --use-rewrites=1
4. bin/magento setup:static-content:deploy -f
5.  bin/magento cache:clean
6. bin/magento cache:flush
7. login admin 

### Expected result
1. Backend navigation without errors

### Actual result
1. Backend randomly shows alert: Attention. Something went wront.

![issue-screen](https://user-images.githubusercontent.com/33727260/33062785-cbce8488-cea0-11e7-8b53-1ed51513abc9.jpg)

There is no other info related: var/log/system.log, var/log/debug.log and httpd error log don't show extra info.

**Comment by magento-engcom-team** [comment]
@pablobae, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.10, 2.2.1
