### ISSUE TITLE
"ScopeDefault" class returns 1 as id where 0 would be expected

### ISSUE THREAD

**Issue by wexo-team** [magento/magento2#12377]
`\Magento\Framework\App\ScopeDefault::getId()` returns `1` where I with my Magento 1 background would expect `0` to be the correct result.  
I have not seen this behavior trigger any bugs in the code so I would like to hear if anyone can confirm whatever the current implementation is correct or not.

https://github.com/magento/magento2/blob/8c7c70059f8809f3ca6e4eddd112c80d8f6b0820/lib/internal/Magento/Framework/App/ScopeDefault.php#L23-L31

### Steps to produce
```php
/** @var \Magento\Framework\App\ScopeDefault $scopeDefault */
$scopeDefault = \Magento\Framework\App\ObjectManager::getInstance()
    ->create(\Magento\Framework\App\ScopeInterface::class);

var_dump($scopeDefault->getId());
```

### Expected result
```
int(0)
```

### Actual result
```
int(1)
```

**Comment by magento-engcom-team** [comment]
Hello @wexo-team. The GitHub issue tracker is intended for technical issues only. Please refer to the Community Forums (https://community.magento.com) or the Magento Stack Exchange (http://magento.stackexchange.com/) site for technical and programming questions.

**Comment by wexo-team** [comment]
Thank for the info. I will continue my search for answers in the Community Forums
([refrence link](https://community.magento.com/t5/Programming-Questions/quot-ScopeDefault-quot-class-returns-1-as-id-where-0-would-be/m-p/80364))

**Comment by wexo-team** [comment]
Also posted to Stack Exchange ([link](https://magento.stackexchange.com/questions/202705/scopedefault-class-returns-1-as-id-but-should-it-not-be-0))
