### ISSUE TITLE
Regions list in Directory module for India

### ISSUE THREAD

**Issue by amansrivastava** [magento/magento2#12378]
States list is required in India for setting new tax (GST) implementation and for accuracy in shipping address.
This is list of regions need to be appended in InstallData in magento-directory module.
        $data = [
        ['IN','AN','Andaman and Nicobar Islands'],
        ['IN','AP','Andhra Pradesh'],
        ['IN','AR','Arunachal Pradesh'],['IN','AS','Assam
        '],['IN','BR','Bihar
        '],['IN','CH','Chandigarh
        '],['IN','CT','Chhattisgarh
        '],['IN','DN','Dadra and Nagar Haveli
        '],['IN','DD','Daman and Diu
        '],['IN','DL','Delhi
        '],['IN','GA','Goa
        '],['IN','GJ','Gujarat
        '],['IN','HR','Haryana
        '],['IN','HP','Himachal Pradesh
        '],['IN','JK','Jammu and Kashmir
        '],['IN','JH','Jharkhand
        '],['IN','KA','Karnataka
        '],['IN','KL','Kerala
        '],['IN','LD','Lakshadweep
        '],['IN','MP','Madhya Pradesh
        '],['IN','MH','Maharashtra
        '],['IN','MN','Manipur
        '],['IN','ML','Meghalaya
        '],['IN','MZ','Mizoram
        '],['IN','NL','Nagaland
        '],['IN','OR','Odisha
        '],['IN','PY','Puducherry
        '],['IN','PB','Punjab
        '],['IN','RJ','Rajasthan
        '],['IN','SK','Sikkim
        '],['IN','TN','Tamil Nadu
        '],['IN','TG','Telangana
        '],['IN','TR','Tripura
        '],['IN','UP','Uttar Pradesh
        '],['IN','UT','Uttarakhand
        '],['IN','WB','West Bengal']
        ];

Currently, it is a manual task and a must have requirement in stores running in India on Magento.
It will be very useful if it comes default.

### Preconditions

1. Magento 2
2. A Product created.

### Steps to reproduce

1. Add the Product do cart.
2. Go to Checkout.
3. Select India in Country drop-down menu.

### Expected result

State/Province should be mandatory drop-down field with appropriate values.

### Actual result

State/Province is not mandatory text field.

**Comment by magento-engcom-team** [comment]
@amansrivastava, thank you for your report.
We've created internal ticket(s) MAGETWO-84233 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @amansrivastava 
We are closing this issue now as the fix has been delivered with the commit https://github.com/magento/magento2/commit/3839c0fc45f270839dddd6fc6025876fc2cf13c3 and should be released with 2.2.4
Thank you.

**Comment by amansrivastava** [comment]
Hi @ishakhsuvarov. Thanks
