### ISSUE TITLE
Admin login always takes >30 sec when using Redis on 2.2.1

### ISSUE THREAD

**Issue by keithbentrup** [magento/magento2#12385]
### Preconditions

1. Magento 2.2.1
2. Redis for session management

### Steps to reproduce

1. Login to the admin

### Expected result

1. Login should be immediate

### Actual result

1. Login takes >30 secs due to a recent commit that causes a new session id to be generated during the request

The [regenerateId](https://github.com/magento/magento2/blob/8797e4da74cad7ab627a02135abafde219689c91/lib/internal/Magento/Framework/Session/SessionManager.php#L501) method was recently rewritten to generate a new session id when an admin logs into the admin dashboard. 
The change in the session id causes the [session read method](https://github.com/colinmollenhour/php-redis-session-abstract/blob/c436a0ec6d1059f1abbe7913010271ca019c1835/src/Cm/RedisSession/Handler.php#L401) of the redis session handling class to loop 60 times with a 500 ms sleep at the end of each loop before breaking out while it looks for the [locking pid](https://github.com/colinmollenhour/php-redis-session-abstract/blob/c436a0ec6d1059f1abbe7913010271ca019c1835/src/Cm/RedisSession/Handler.php#L425). This is because both `session_regenerate_id` and `session_start` increment the lock value 0->1->2 but only when the value is 1 will it break out otherwise it continues for `$tries` (60) with a 500 ms sleep between each one.

![image](https://user-images.githubusercontent.com/253579/33098966-2ab25b6e-cedd-11e7-851e-972fa28df515.png)
![image](https://user-images.githubusercontent.com/253579/33098980-3792e696-cedd-11e7-8a6e-c9f81e08d531.png)

**Comment by Tjitse-E** [comment]
@magento-engcom-team is this issue already fixed on the development branche? If yes, can you point me to the right commit?

**Comment by mslabko** [comment]
Hi @Tjitse-E, fix will be available in the nearest release. For now you can take it from 2.2-develop branch: https://github.com/magento/magento2/commit/aaa60b1b72bdc189b38492bd50b0ffb23101173e

**Comment by ishakhsuvarov** [comment]
@mslabko @Tjitse-E @keithbentrup Closing this ticket for now as fix is available in 2.2.2 and delivered with the linked commit.
Thank you for collaboration.

**Comment by tuyennn** [comment]
#12362

**Comment by cscd98** [comment]
@tuyennn @magento-engcom-team @mslabko is this fixed in 2.3.1?
