### ISSUE TITLE
Replace csv import Product type

### ISSUE THREAD

**Issue by pushpendra07** [magento/magento2#12388]
I tried to change product type through import product , replace option in csv.
Product got successfully imported and product type changed from virtual to simple. However, these products did not shown in frontend. In order to show product we need to just open product and click on save button. This shows product on frontend.
### Preconditions
1.  Magento 2.2.1
2. Php 7

### Steps to reproduce
1.  Create virtual products
2.  Export csv
3.  Change product type from virtual to simple and replace existing product through csv.

### Expected result
1. After successful import product should have shown on frontend. 

### Actual result
1. Products did not show until we manually go to products and save it

**Comment by magento-engcom-team** [comment]
@pushpendra07 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation
See screenshots
![virtual_create_0871280926](https://user-images.githubusercontent.com/31669971/33117901-c9ff1cb2-cf72-11e7-8919-8ed134102693.png)

![virtual_after_import_0841280929](https://user-images.githubusercontent.com/31669971/33117909-d2195ca0-cf72-11e7-9ec8-e2b0b1b39507.png)

![virtual_front_end_0921280931](https://user-images.githubusercontent.com/31669971/33117915-db43a81c-cf72-11e7-9cd6-caf3c0003049.png)

**Comment by pushpendra07** [comment]
Let me check again and update you back

**Comment by magento-engcom-team** [comment]
@pushpendra07 , yes of course. We wait response from you thank you.
