### ISSUE TITLE
Discard decimals for specified currencies

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#1239]
Magento1.x has serious issues of discarding decimals for some currencies (e.g. JPY, KRW, VND...).
These currencies don't use under decimal numbers for currency.
If merchants that hope to use these currencies, they have to use 3rd party extensions.

Is it possible to add some configurations for handling under decimal numbers of currency?

**Comment by choukalos** [comment]
See my comment for #1240 ; would be great if someone could consolidate the constant that controls # of digits for price and submit a PR.  That would enable 3rd party's to create extensions for specific countries.  Big challenge is around automated tests.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Discard-decimals-for-specified-currencies/idi-p/45470).
