### ISSUE TITLE
Build in Javascript translation doesn't work

### ISSUE THREAD

**Issue by twain83** [magento/magento2#12394]
### Steps to reproduce

1. Go to http://test-php.pl/customer/account/create/
2.  There are javascript comunicates in english instead in polish

### Expected result
I've got problem with default translation built in magento 2. 
A made static content deploy, file js-translation.json generated properly, 
but strings didn't translated. 
Site: test-php.pl Version magento 2.1

**Comment by magento-engcom-team** [comment]
@twain83, thank you for your report.
We've created internal ticket(s) MAGETWO-84353 to track progress on the issue.

**Comment by pareshpansuriya** [comment]
Hello @twain83 can you write which string is not translated.

**Comment by krzksz** [comment]
I'm closing this due to the inactivity and no clear reproduction path that can be check on clean Magento installation provided. Dear @twain83, please reopen the ticket and add this information if the problem still occurs on Magento 2.3.x.
