### ISSUE TITLE
Design configuration issue

### ISSUE THREAD

**Issue by aditiexpo** [magento/magento2#12392]
### Preconditions

1. Magento ver. 2.1.10
2. PHP version: 5.6.30, MySQL version: 4.7.3

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 
![screenshot-2017-11-22 default store view design content magento admin](https://user-images.githubusercontent.com/31617706/33123247-af69ee68-cf9f-11e7-82bc-b51742617864.png)

### Actual result

1. 
![theme_configuration_error](https://user-images.githubusercontent.com/31617706/33123207-926ac1d4-cf9f-11e7-81e4-da9133554814.png)

When i trying to open theme configuration i.e. Content -> Configuration. I got such error:
"There has been an error processing your request
The requested component ("settings") is not found. Before using, you must add the implementation.
Error log record number: 820661217142".

**Comment by magento-engcom-team** [comment]
@aditiexpo , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or check you Error log

![design1_0841280824](https://user-images.githubusercontent.com/31669971/33126070-c77aa2c2-cf8b-11e7-936e-f6165af0b199.png)
![design2_03451280901](https://user-images.githubusercontent.com/31669971/33126078-d111a6a0-cf8b-11e7-9d67-d749b9de81a6.png)

**Comment by aditiexpo** [comment]
Hii there,

I have issue on theme design configuration. Currently when i try to get the
settings for theme design configuration i am not able to get it. the page
shows an error. for that error i attached the report file in attachment
below.

![error](https://user-images.githubusercontent.com/31617706/33126933-5bf35e06-cfac-11e7-879a-1ab3420be1ff.png)


Thanks

**Comment by magento-engcom-team** [comment]
@aditiexpo , thanks for your response. Please check this problem on clean installation of Magento without custom modules.

**Comment by aditiexpo** [comment]
That will obviously work on the clean install without any custom module but
why would i go for the clean install when i already want to use the module
i have anyways. How can i fix this issue with these custom modules?

**Comment by ishakhsuvarov** [comment]
@aditiexpo We can not provide guidance for any kind of custom modules.
Please contact specific module's vendor for support.
Thank you

**Comment by Arcturpartner** [comment]
Perhaps you have a problem with folder/file rights: look if rights in this directory are [magento-root]/generated/code/Magento/Theme/Model/Design/ are like all other folder/file rights
