### ISSUE TITLE
Tax & decimal rounding method

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#1240]
Magento1.x only uses "round" for tax and decimal number method, but sometimes it causes wrong result.
Also some merchants use "floor" and "ceil" for discarding decimal numbers.

Is it possible to choose decimal discarding method via admin panel for M2?
If we do simply discard decimal numbers, converting currencies causes serious trouble.

For example, 99.99USD is 11,961.15JPY ( 1USD is 119.6235JPY ), but JPY does not use under decimal number. Then correct result is 11,961 JPY. 
If "round" is used for discarding method, sometimes converting result is not correct.

**Comment by yoavkutner** [comment]
+1

**Comment by choukalos** [comment]
Hey @HirokazuNishi in Magento 2 the rounding function should be consolidated for tax.  Should be fairly straight forward to do a plugin and replace that with floor or ceil or even bankers rounding to enable one to create country/taxation specific extension.

As far as choosing the # of decimal places there's a couple constants that really need to be consolidated + the automated test framework used by tax/pricing tests could use some attention to be adapted to changes in # of decimal places.  If you could do that and send in a PR that'd be awesome!  That would enable all sorts of community driven extensions around taxes/pricing.  

Thanks,
Chuck

**Comment by HirokazuNishi** [comment]
@choukalos Of course I'll try to make PR, but I just started to investigation about this issue on M2. so it takes long time.
I already released one extension to solve this issue on M1, but I had to rewrite many classes and had to execute many tests. If M2 aims to be real cross-border ecommerce platform, decimal & tax issues should be solved before stable release.

**Comment by choukalos** [comment]
@HirokazuNishi after you finish investigating please ping me if there are things we can do in core to make it easier to create customer tax extension.  One of our goals in the M2 tax engine was to make it easy to replace or customize.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Tax-amp-decimal-rounding-method/idi-p/45465).
