### ISSUE TITLE
Compatibility. Upgrade 2.1.9 to 2.1.10. Quote Address getExtensionAttributes returns array, AddressExtensionInterface|null expected.

### ISSUE THREAD

**Issue by ed007m** [magento/magento2#12417]
Hi, I found that after Magento Upgrade from 2.1.9 to 2.1.10 extension attributes for Magento\Quote\Model\Quote\Address stopped working for my website. After long investigation I discovered that it was caused through the core method estimateByExtendedAddress() (from \Magento\Quote\Model\ShippingMethodManagement) was changed.
was
```
    public function estimateByExtendedAddress($cartId, AddressInterface $address)
    {
    ...
        return $this->getShippingMethods($quote, $address->getData());
    }
```
becomes:
 ```
   public function estimateByExtendedAddress($cartId, AddressInterface $address)

    {

     ...
        return $this->getShippingMethods($quote, $address);

    }
```
In this case code 
`$address->getExtensionAttributes()` returns array instead of `\Magento\Quote\Api\Data\AddressExtensionInterface|null` and fatal error occurs
`Fatal Error: 'Uncaught Error: Call to a member function myExtensionAttributeName() on array.` 

So, I have a few questions:
1. Why this updated was not mentioned on [devdocs.release.notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.10CE.html).
2. What solution should be here? Because when use $address->getExtensionAttributes() in other code places it returns excepted object. I found that the same logic is for 2.2.0. For major release version. Why minor was also changed?
3. What is your policy for backward incompatible changes between minor releases?

**Comment by magento-engcom-team** [comment]
Hello @ed007m. The GitHub issue tracker is intended for technical issues only. Please refer to the Community Forums (https://community.magento.com) or the Magento Stack Exchange (http://magento.stackexchange.com/) site for technical questions. Thank You.
