### ISSUE TITLE
Magento 2.2.1: Switching Store View to another language in cart/checkout before checking out leads order being linked to wrong store view

### ISSUE THREAD

**Issue by jhruehl** [magento/magento2#12418]
If you have a Magento 2.2.1 store with at least two store views for different languages, changing the store view to another language just before checking out, can lead to the order being linked to the store view, in which the cart was filled. As a result the customer gets the order confirmation mail in another language than the one the checkout process was done in.

### Preconditions
1. Magento 2.2.1
2. PHP 7.0 and 7.1 (different local setups and different testservers)
3. MySQL 5.5.5-10.1.24-MariaDB

### Steps to reproduce
1. Have a store with at least two different store views for different languages.
2. While staying in one store view fill your cart with some items.
3. Either switch the store view to another language, directly open your cart and check out. Or go to your cart/checkout, switch the store view to another language there and directly checkout.

### Expected result
1. Order confimation mail is send in the language of the store view, in which the checkout process was done.

### Actual result
1. Order confimation mail is send in the language of the store view, in which the cart was filled.

### Comment
Another strange occurence is that, if one reorders an order in another store view than the original order was done in, the label 'weight' in the order confirmation mail is still translated in the language of the store view, in which the original order was made in.
![customer_order_mail_weight_label_in_wrong_language](https://user-images.githubusercontent.com/29142982/33181618-2a0d152e-d071-11e7-891e-a3ff2c837e8e.jpeg)

**Comment by magento-engcom-team** [comment]
@jhruehl, thank you for your report.
We've created internal ticket(s) MAGETWO-84462 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@jhruehl, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
