### ISSUE TITLE
Password Reset Link doesn't generate or duplicates the id / token query string

### ISSUE THREAD

**Issue by tonybrown85** [magento/magento2#12416]
### Preconditions

1. PHP Version 7.0.19
2. Linux cPanel VPS
3. Magento 2.2.1

### Steps to reproduce

1. Install fresh Magento 2.2.1 build
2. Create customer account
3. initialise password reset email.
4. Click on the link in the email
5. Password reset url either doesn't contain the id and token at all or duplicates the id and token query string over a dozen times in the url (resulting in an 500 internal server error)

### Expected result

1. Install fresh Magento 2.2.1 build
2. Create customer account
3. initialise password reset email.
4. Click on the link in the email
5. reset the password successfully on the website frontend with the id and token in the url string

### Actual result

1. Password reset url either doesn't contain the id and token at all or duplicates the id and token query string over a dozen times in the url (resulting in an 500 internal server error).

Any help to get this resolved would be really appreciated as no customers can reset their passwords which is a really critical component.

**Comment by magento-engcom-team** [comment]
@tonybrown85, We cannot reproduce this issue as described. Do you use a custom template or any custom extension for sending emails? Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by tonybrown85** [comment]
Yes my apologies for logging this ticket in haste. I've just identified that it's a 3rd party module causing this issue. I appreciate you taking a brief look at the issue and my apologies again! Regards, Tony
