### ISSUE TITLE
hide_from_product_page import not working Magento 2.1.8

### ISSUE THREAD

**Issue by Softagz** [magento/magento2#12429]
### Preconditions

1. Using the sample download "Products" Import and Uploaded the images (BASE, THUMB and SMALL)
2. Using the same import CSV for the field column in csv "hide_from_product_page" not to show the small,thumb (which are same values) to be displayed on PRODUCT PAGE
3. Manually from admin when we tick the box and export we can see the "hide_from_product_page" with image path but when we do the same with other product during import using the same column "hide_from_product_page" and similar way to put value for "hide_from_product_page" its doing nothing 

Export "Products"
![export-product](https://user-images.githubusercontent.com/33953824/33204192-c211c9f2-d128-11e7-88ac-ace406853e34.jpg)

Import "Products" does not work for 
871544200-2476 | /8/7/8715442002476_small.jpg

![import-product](https://user-images.githubusercontent.com/33953824/33204193-c2911f40-d128-11e7-837f-b5f39d4e7b7c.jpg)

**Comment by magento-engcom-team** [comment]
@Softagz, thank you for your report.
We've created internal ticket(s) MAGETWO-84496 to track progress on the issue.

**Comment by PieterCappelle** [comment]
Can you assign this to me? I’ll fix this. Can @magento-engcom-team also add the label import/export? Thanks!

**Comment by dmanners** [comment]
I think this has been fixed in the 2.2-develop branch with the PR https://github.com/magento/magento2/pull/11926

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#79
