### ISSUE TITLE
On select file in 'Customizable Options' on frontend, it zooms product image

### ISSUE THREAD

**Issue by dankhrapiyush** [magento/magento2#12427]
### Preconditions

1. Magento version: 2.2.1

### Steps to reproduce

1. Add 'Customizable Options' in product of type 'File'
2. Go to frontend, and try to upload a file
3. On select file, it zooms product image. Don't know why is it zooming product image?

### Expected result

1. It should not zoom product image on select file in customizable option

### Actual result

![2017-11-24_10-43-41](https://user-images.githubusercontent.com/1868477/33196448-2a8d9caa-d105-11e7-9af0-81f6f72ed47a.png)

**Comment by magento-engcom-team** [comment]
Hello @dankhrapiyush , thank You for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by dankhrapiyush** [comment]
### Preconditions
1. Magento version: 2.2.1
2. Browser: Firefox ver 57.0 (64-bit)
3. OS: Windows 10

### Actual result
1. I'm facing this issue in Firefox browser only. Not in Chrome and IE.
2. I checked and verified this issue on a fresh Magento.

**Comment by magento-engcom-team** [comment]
Hi @dankhrapiyush. Can you please reproduce the issue using a supported operating system: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html? Note that Windows is not in the list. Thank You.
