### ISSUE TITLE
eclipse pdt validator error

### ISSUE THREAD

**Issue by aoslee** [magento/magento2#1242]
hi,
  I import magento2 with eclipse pdt and get some errors. I read them and they are reals.
Description	Resource	Path	Location	Type
Start tag (<button>) not closed properly, expected '>'.	login_buttons.phtml	/magento2/app/code/Magento/Backend/view/adminhtml/templates/admin	line 8	HTML Problem
Start tag (<form>) not closed properly, expected '>'.	send.phtml	/magento2/app/code/Magento/Sendfriend/view/frontend/templates	line 44	HTML Problem
End tag (</span>) not closed properly, expected '>'.	items.phtml	/magento2/app/code/Magento/Shipping/view/frontend/templates	line 28	HTML Problem
Start tag (<div>) not closed properly, expected '>'.	node.html	/magento2/dev/tests/js/jasmine/assets/apply/templates	line 8	HTML Problem
Start tag (<div>) not closed properly, expected '>'.	selector.html	/magento2/dev/tests/js/jasmine/assets/script/templates	line 8	HTML Problem
syntax error, unexpected 'EOF'	short_echo.php	/magento2/dev/tests/static/testsuite/Magento/Test/Php/Exemplar/CodeStyleTest/phpcs/input/coding_style/demarcation	line 2	PHP Syntax Error

**Comment by mazhalai** [comment]
@aoslee Thank you for reporting! We have created ticket MAGETWO-37118 to track the first 3 and MAGETWO-37119 to track the last issue. However, issues related to `/magento2/dev/tests/js/jasmine` are not in our code base.

**Comment by vpelipenko** [comment]
@aoslee, this fix is available from 0.74.0-beta10. Did you have a chance to validate it on the newest code?
