### ISSUE TITLE
Annoying delayed notifications at admin area - that moves content down

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#12438]
Hi. This is not a bug, but annoying "feature". Screenshot: [http://prntscr.com/het06v](http://prntscr.com/het06v)
All M2 notification comes with delay 0.2-0.5s after page is loaded, it makes me crazy, when I like to click save, and the content goes down because of annoying notification is just showed on the page.
Please make it with better UX, increase Z-index with postion: fixed or just make it looking the same way as Magento 1 has.
This is total 1 thing makes me crazy, each page reload. this really hurts store UX and should be improved

Thanks

**Comment by magento-engcom-team** [comment]
@tomekjordan, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by tomekjordan** [comment]
Correct behavior, for Magento devs. Not for real admin panel users, where you make thousand operations daily. each page reaload shows content and now when you like to press any button or filter on grid, ant then boom, surprise -> 0.5s later notification appears and everything is moved down.

totally annoying in day to day activites. M1 was better with it - because notifications were not "ajaxed" and appeared right with page reload.

**Comment by southerncomputer** [comment]
if they would lighten up on the .js libs [merge bundling } the delay would go away, benchmark with chrome performance dev mode - all the backend ajax loading delays go from 2-3secs  to 0-1 secs! no joke!

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/14
