### ISSUE TITLE
Magento 2.2.1 Upgrade Issues

### ISSUE THREAD

**Issue by paragpadsumbiya** [magento/magento2#12433]
Magento 2.2.1 upgrade issue
Current version - Magento 2.1.10
Need to Update to version - Magento 2.2.1

### Preconditions

1. PHP 7.1
2. MySQL 5.6
3, Apache
4 Ubuntu 16.04 LTS

### Steps to reproduce

1. cp composer.json composer.json.bak
2. composer require magento/product-enterprise-edition 2.2.1 --no-update
3. composer update
4. rm -rf var/cache/* var/page_cache/* var/generation/*
5. php bin/magento setup:upgrade

### Expected result

1. Should be upgraded smoothly

### Actual result

Generate below errors while upgrading through terminal - command - php bin/magento setup:upgrade

Installing schema... Warning: PDOStatement::execute(): MySQL server has gone away in /var/www/html/nestle2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

This is because it takes so much time and exceeds time limit of My sql . So Magento should inform when user upgrade .

So i run "php bin/magento setup:upgrade" command again so below error is generated

"SQLSTATE[HY000]: General error: 1025 Error on rename of './nestle2/#sql-4682_6' to './dbname/catalog_product_bundle_option' (errno: 150 - Foreign key constraint is incorrectly formed)"

Below output got in terminal

Cache cleared successfully
File system cleanup:
/var/www/html/nestle2/generated/code/Composer
/var/www/html/nestle2/generated/code/Magento
/var/www/html/nestle2/generated/code/Symfony
The directory '/var/www/html/nestle2/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_Backend':
Module 'Magento_Eav':
Module 'Magento_Theme':
Module 'Magento_Customer':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Rule':
Module 'Magento_AdminNotification':
Module 'Magento_Search':
Module 'Magento_Amqp':
Module 'Magento_User':
Module 'Magento_Authorization':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Module 'Magento_Backup':
Module 'Magento_Catalog':
Module 'Magento_Quote':
Module 'Magento_CatalogInventory':
Module 'Magento_Bundle':
Module 'Magento_BundleImportExport':
Module 'Magento_BundleImportExportStaging':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_CacheInvalidate':
Module 'Magento_SalesSequence':
Module 'Magenest_Pin':
Module 'Magento_MediaStorage':
Module 'Magento_CatalogImportExport':
Module 'Magento_CatalogImportExportStaging':
Module 'Magento_Payment':
Module 'Magento_Ui':
Module 'Magento_CatalogSearch':
Module 'Magento_Sales':
Module 'Magento_Msrp':
Module 'Magento_SalesRule':
Module 'Magento_Checkout':
Module 'Magento_Downloadable':
Module 'Magento_GiftCard':
Module 'Magento_Staging':
Module 'Magento_Widget':
Module 'Magento_Vault':
Module 'Magento_CheckoutAgreements':
Module 'Magento_CheckoutStaging':
Module 'Magento_CmsStaging':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_ConfigurableProduct':
Module 'Magento_ConfigurableProductSales':
Module 'Magento_Wishlist':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_CustomAttributeManagement':
Module 'Magento_AdvancedCatalog':
Module 'Magento_CustomerBalance':
Module 'Magento_CustomerCustomAttributes':
Module 'Magento_CustomerFinance':
Module 'Magento_CustomerImportExport':
Module 'Magento_CatalogRule':
Module 'Magento_Cybersource':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_AdvancedCheckout':
Module 'Magento_ProductAlert':
Module 'Magento_ImportExport':
Module 'Magento_Reports':
Module 'Magento_AdvancedRule':
Module 'Magento_AdvancedSearch':
Module 'Magento_Email':
Module 'Magento_EncryptionKey':
Module 'Magento_Enterprise':
Module 'Magento_Eway':
Module 'Magento_Fedex':
Module 'Magento_TargetRule':
Module 'Magento_GiftCardAccount':
Module 'Magento_GiftCardImportExport':
Module 'Magento_Tax':
Module 'Magento_GiftMessage':
Module 'Magento_GiftMessageStaging':
Module 'Magento_Weee':
Module 'Magento_GiftWrapping':
Module 'Magento_GiftWrappingStaging':
Module 'Magento_GoogleAdwords':
Module 'Magento_GoogleAnalytics':
Module 'Magento_GoogleOptimizer':
Module 'Magento_GoogleOptimizerStaging':
Module 'Magento_PageCache':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_GroupedProductStaging':
Module 'Magento_DownloadableImportExport':
Module 'Magento_Captcha':
Module 'Magento_Security':
Module 'Magento_WebsiteRestriction':
Module 'Magento_LayeredNavigation':
Module 'Magento_LayeredNavigationStaging':
Module 'Magento_Logging':
Module 'Magento_Marketplace':
Module 'Magento_CatalogEvent':
Module 'Magento_MessageQueue':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_MsrpStaging':
Module 'Magento_MultipleWishlist':
Module 'Magento_Multishipping':
Module 'Magento_MysqlMq':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_OfflineShipping':
Module 'Magento_VersionsCms':
Module 'Magento_AdminGws':
Module 'Magento_PaymentStaging':
Module 'Magento_Paypal':
Module 'Magento_Persistent':
Module 'Magento_PersistentHistory':
Module 'Magento_PricePermissions':
Module 'Magento_GiftRegistry':
Module 'Magento_ProductVideo':
Module 'Magento_CatalogStaging':
Module 'Magento_PromotionPermissions':
Module 'Magento_Banner':
Module 'Magento_Reminder':
Module 'Magento_ConfigurableProductStaging':
Module 'Magento_RequireJs':
Module 'Magento_ResourceConnections':
Module 'Magento_Review':
Module 'Magento_ReviewStaging':
Module 'Magento_Reward':
Module 'Magento_RewardStaging':
Module 'Magento_Rma':
Module 'Magento_RmaStaging':
Module 'Magento_Robots':
Module 'Magento_Rss':
Module 'Magento_AdvancedSalesRule':
Module 'Magento_Authorizenet':
Module 'Magento_Signifyd':
Installing schema...
Module 'Magento_SalesInventory':
Module 'Magento_CustomerSegment':
Module 'Magento_SalesRuleStaging':
Module 'Magento_CatalogPermissions':
Upgrading schema..
Module 'Magento_UrlRewrite':
Module 'Magento_ScalableCheckout':
Module 'Magento_ScalableInventory':
Module 'Magento_ScalableOms':
Module 'Magento_ScheduledImportExport':
Module 'Magento_Elasticsearch':
Module 'Magento_SearchStaging':
Module 'Magento_Integration':
Upgrading schema..
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_SalesArchive':
Module 'Magento_Sitemap':
Module 'Magento_Solr':
Module 'Magento_CatalogInventoryStaging':
Module 'Magento_BannerCustomerSegment':
Module 'Magento_Support':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_GiftCardStaging':
Upgrading schema..
Module 'Magento_BundleStaging':
Upgrading schema.. SQLSTATE[HY000]: General error: 1025 Error on rename of './nestle2/#sql-4682_6' to './nestle2/mgep_catalog_product_bundle_option' (errno: 150 - Foreign key constraint is incorrectly formed)

This is generated while upgrading schema of 'Magento_BundleStaging' .

So i run below commands to solve temporary and move ahead with my upgradation
--> php bin/magento module:disable Magento_BundleStaging
--> php bin/magento cache:flush
--> php bin/magento setup:upgrade

after this i solved errors but i got some errors in like "rror converting field info in table magento_logging_event where log_id=2869 using Magento\Logging\Setup\ObjectConverter.
Fix data or replace with a valid value.
Failure reason: 'unserialize(): Error at offset 170 of 255 bytes'"

This error is generated due to our existing cache data in "magento_logging_event" table . So i set there info "{"general":null}" at log_id = 2869 and log_id = 2058 or whereever it generate errors.

And now again run command

--> php bin/magento setup:upgrade
After this i upgraded normally

**Comment by magento-engcom-team** [comment]
@paragpadsumbiya thank you for your report. 
Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
