### ISSUE TITLE
Object of class Magento\Customer\Model\Data\Region could not be converted to string

### ISSUE THREAD

**Issue by friimaind** [magento/magento2#12436]
### Preconditions
Magento 2.1.9 CE

### Summary
There are many issues closed with the same error: 
https://github.com/magento/magento2/issues/4187
https://github.com/magento/magento2/issues/4296
https://github.com/magento/magento2/issues/7387

On my magento installation I have italian customers who has "Italy" as shipping country. Italy does not have "region" information and this can cause the error.

### Steps to reproduce
As **ankitce** said here https://github.com/magento/magento2/issues/4187#issuecomment-255071297

1. Set a country as an allowed country which expects no 'region' information in the address structure. In my case "Italy"
2. Create a customer who belongs to the country specified in step 1.
3. Add some products in cart and go to checkout page.

You will see the webapi's error on top and the shipping method block will be empty

### Expected result
No errors, show shipping methods

### Actual result
Frontend:

![image](https://user-images.githubusercontent.com/16322003/33219502-c76d8552-d142-11e7-8f6d-e80e4ef6e23b.png)

On exception.log:

`Next Exception: Report ID: webapi-5a184a5953bce; Message: Recoverable Error: Object of class Magento\Custome/www.mywebsite.it/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2929 in /var/www/www.mywebsite.i:195`

### Workaround
Thanks to **DogSports** I edited Mysql.php file with this https://github.com/magento/magento2/issues/7387#issuecomment-263586330 and now it works but I'm not happy to have changed the core.

**Comment by magento-engcom-team** [comment]
@friimaind , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by friimaind** [comment]
@magento-engcom-team issue updated, thank you

**Comment by p-bystritsky** [comment]
@friimaind, thank you for update.
Unfortunately, we cannot reproduce this issue by the steps you provided. Can you please record a video?

**Comment by p-bystritsky** [comment]
@friimaind, thank you for update.
Unfortunately, we cannot reproduce this issue by the steps you provided. Could you please record a video?

**Comment by magento-engcom-team** [comment]
@friimaind, thank you for the update.
Unfortunately, we cannot reproduce this issue by the steps you provided. Could you please record a video?

**Comment by magento-engcom-team** [comment]
@friimaind, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by duckchip** [comment]
I was able to reproduce this issue on 2.1.11
![screen shot 2018-01-23 at 13 32 14](https://user-images.githubusercontent.com/9752966/35276005-03cab01e-0042-11e8-82fd-990a777f6363.png)

**Comment by LemaireVincent** [comment]
Hi, I could reproduce this (Magento Enterprise 2.2.2 with b2b extension 1.0.1)
It happens on 1st creation of the cart on a new customer (in my case in fact it's the very first customer that I create)
Create a new customer, add a product to cart : this exception occurs.

**Comment by kunzi** [comment]
For us this happens when creating a new customer account and adding a new address in customer's account page. If you create a new address at checkout the error does not appear. So the key for us at least is to add new address in via customer account to get the error. We have 2.2.3 installed.

**Comment by digikeijs** [comment]
@magento-engcom-team can you please create a proper commit and fix for this bug? Has been dragging on for so long. The issue is still present in magento 2.3 and will happen when you have a vat number in your address details. This fix actually solves the issue

vendor/magento/framework/DB/Adapter/Pdo/Mysql.php

as of line 3084 change to
                       ```
 case 'varchar':
			case 'mediumtext':
			case 'text':
			case 'longtext':
			if ($column['COLUMN_NAME'] == 'region' AND !is_string($value)) {
			$value = '';
				}
			$value  = (string)$value;
			if ($column['NULLABLE'] && $value == '') {
				$value = null;
				}
```

**Comment by digikeijs** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @digikeijs. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @digikeijs, here is your [Magento instance](https://i-12436-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-12436-2-3-0.instances.magento-community.engineering/admin](https://i-12436-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kestraly** [comment]
Some extensions cause this problem. 

Amasty Shipping Restriction causes this error for countries without selectable regions and certain rules.

Amasty/Shiprestriction/Model/Quote/ShippingMethodManagement.php

Changing line 40 from

`$address->getRegion(),`

to

` (!is_string($address->getRegion()))? '' : $address->getRegion(),`

resolved the issue for me (On their most recent version as of today)

**Comment by ouwfuc** [comment]
> Some extensions cause this problem.
> 
> Amasty Shipping Restriction causes this error for countries without selectable regions and certain rules.
> 
> Amasty/Shiprestriction/Model/Quote/ShippingMethodManagement.php
> 
> Changing line 40 and 66 from
> 
> `$address->getRegion(),`
> 
> to
> 
> ` (!is_string($address->getRegion()))? '' : $address->getRegion(),`
> 
> resolved the issue for me (On their most recent version as of today)

Hi @kestraly 

Thank you for your solution. It fixed it for me too!  Have you contacted Amasty about this issue?

**Comment by kestraly** [comment]
Naaa, they'd probably charge me for it.

**Comment by dharmesh-tukadiya** [comment]
Thanks @kestraly kestraly
