### ISSUE TITLE
I cannot add a content to Search Engine Robots

### ISSUE THREAD

**Issue by wd7080** [magento/magento2#12444]
### Preconditions

1. Magento ver. 2.2.1

### Steps to reproduce

1. Go to Content -> Configuration -> Search Engine Robots

### Expected result

1. Get the screen where you can add the rules you want.

### Actual result

1. It opens the "Search Engine Robots" screen but I cannot change it or add any rule as appears below. I wonder why?
![search engine](https://user-images.githubusercontent.com/33989344/33234544-3e19caf2-d1ee-11e7-8146-1abca6a1a296.png)

**Comment by thomvanderboon** [comment]
You cannot set it at the Storeview level, but you have to set it at the Website level

Solution is to change the scope from "Store View" to "Website"

Go to Content -> Configuration -> Select the Website (not the Storeview) -> Search Engine Robots

**Comment by wd7080** [comment]
From where to change the "Store View" to "Website"? See the picture below. I don't have this option under:
 Content -> Configuration
![i cannot see it](https://user-images.githubusercontent.com/33989344/33240662-6cdcc56a-d27f-11e7-8e9e-cfe17fe095dc.png)

**Comment by thomvanderboon** [comment]
You are one step to far

Select the first one 

![afbeelding](https://user-images.githubusercontent.com/16068454/33241873-fffb4fd2-d2cb-11e7-9c2c-771e7afc991f.png)

**Comment by wd7080** [comment]
Thanks! But I have only configured the default store view. I did not do anything else with the first two rows as appears below. I left them as is. Do I have to configure those as well?

![this is what i have](https://user-images.githubusercontent.com/33989344/33241940-94794ffe-d292-11e7-9ee3-70350e88f962.png)

**Comment by thomvanderboon** [comment]
Yes.... you can change the setting for the robots at either the global level (first) or website (second).... You don't need to configure anything else at this level.

**Comment by wd7080** [comment]
@thomvanderboon THANKS for the help!

**Comment by wd7080** [comment]
Just for me to learn more about this, when do I have to configure the other settings in the first two rows of HTML head, header, footer etc.. ? For example, if I add different logos to row # 1 and row # 2 what will happen and where will that appear?

**Comment by wd7080** [comment]
After adding the rule to the second row, I verified if it appears and I have visited my URL: https://www.domain.com/robots.txt

I did not see the rule I added which is:
```
User-agent: *
Allow: /

sitemap: http://domain.com/sitemap.xml
```
Below is what I saw:

![default](https://user-images.githubusercontent.com/33989344/33242208-d15e141e-d296-11e7-83a2-e2f265bd4e77.png)

**Comment by magento-engcom-team** [comment]
@wd7080 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by kirtinariya1** [comment]
@wd7080
Please follow below steps to change "Search Engine Robots" in Magento 2.2.3
Login to admin:
CONTENT >> Design >> Configuration >> Edit First row check his Scope: Default >>
Go to Search Engine Robots tab and change as per your requirement and click to "Save Configuration" 

Your issue has been Done.
Thanks you.
