### ISSUE TITLE
17track External Js cann't be supported

### ISSUE THREAD

**Issue by sandipdutt** [magento/magento2#12449]
### Preconditions

1. Magetno 2.1.9,
2. 17tracks external js

### Steps to reproduce

1. <script type="text/javascript" src="http://www.17track.net/externalcall.js"></script>
2. Uncaught Error: Mismatched anonymous define() module: function (){return g}()...
3. 

### Expected result

1.  I want to add external js in phtml or with in head section in layout file but when i add to file it showing error in console log. I want to solve this bug.

### Actual result

1. Uncaught Error: Mismatched anonymous define() module: function (){return g}()...

**Comment by magento-engcom-team** [comment]
@sandipdutt Thanks for reporting this issue. Can You please try to follow this documentation http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js-resources.html and let us know, if issue still occur?

**Comment by magento-engcom-team** [comment]
@sandipdutt Seems like the problem with this specific externalcall.js file and not Magento.
