### ISSUE TITLE
unable to save  product per website wise

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1245]
I have created 2 websites.
first website contain 2 store views.
second website contain 1 store view.
now i have added 1 product and assigned to both websites.
then i'm trying to edit  product from second website store view.when ever i'm trying to save "url key specified store already exists" error is coming.and not able to edit url key.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-36369

**Comment by vpelipenko** [comment]
@sivajik34, this issue was fixed in 0.74.0-beta14. Please, confirm, that the fix works for you.

**Comment by sivajik34** [comment]
yes its working fine.thank you
