### ISSUE TITLE
Include SQL wild cards by default when using 'like' in search criteria 

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#12456]
As a developer, I don't want to think about passing SQL wildcard characters when sending 'like' search criteria through a request to the Product API.

### Preconditions
1. Magento CE 2.2.1

### Steps to reproduce
1. Install Magento CE 2.2.1
2. Install provided sample data using `bin/magento sampledata:deploy`
3. Remove WebApi security authorization in Admin > Stores > Configuration > Services > Magento WebApi
4. Make request to: `http://[magento host]/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=red&searchCriteria[filter_groups][0][filters][0][condition_type]=like`

### Expected result
1. Products with sku that contains 'red' are returned in the response xml.

### Actual result
1. No products returned.

**Comment by orlangur** [comment]
> think about passing SQL wildcard characters when sending 'like' 

Well, you have to. Like condition has concrete semantics and you cannot ignore it.

I don't think implementation of like condition can be changed, that would be confusing, probably separate condition type, like "contains" could be implemented to achieve what you need.

**Comment by nbennett25** [comment]
thx @orlangur - clearly the 'like' condition has concrete semantics, but I would consider relying on an outside API consumer to understand and properly implement the 'like' wildcard characters in a request a weakness in the platform. I'll file another feature request to implement the 'contains' type.

**Comment by magento-engcom-team** [comment]
@nbennett25, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hi @nbennett25. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/13
