### ISSUE TITLE
.svg Image is not supported for cms page

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12451]
At the time of upload image every time facing an error "Disallowed file type." 

### Preconditions

1.Magento 2.2.1 Simple data

### Steps to reproduce

1. Login to Admin Backend with full admin rights 
2. Go to Content > Pages > Configuration 
3. Select any page for edit 
4. Go to content tab and insert image, select .svg image  

### Expected result

1. Image should be upload and should be displayed at the Media Storage     

### Actual result

Error message:- "Disallowed file type."
1. [Screenshot, logs]
![svg image error](https://user-images.githubusercontent.com/2203580/33267324-0aef2ab6-d39f-11e7-9485-2ea61fb151f4.png)

**Comment by orlangur** [comment]
This is intentional in order to disallow stored XSS vulnerability. See 2.1.9 release notes.

**Comment by denchev** [comment]
@orlangur In 2.1.9 Release notes there isn't a single mention why SVG is removed. 

http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.9CE.html

Also I personally don't think removing the SVG as supported format is the appropriate handle of XSS attacks. There has to be a way to keep SVGs and also eliminate potential XSS vulnerabilities.

**Comment by orlangur** [comment]
Hi @denchev,

> See Magento 2.0.16 and 2.1.9 Security Patches for a comprehensive discussion of these issues.

Pay attention to this link.

>  There has to be a way to keep SVGs and also eliminate potential XSS vulnerabilities.

Do not hesitate to propose a pull request with a better fix.
