### ISSUE TITLE
ACL permissions issue

### ISSUE THREAD

**Issue by ffrodoe** [magento/magento2#12452]
### Preconditions

1. Reproduced on clean magento 2.2.0

### Steps to reproduce

1. Create new user role with any group checked (for example "Catalog") except "System" group
2. Create user and assign him to the group from step 1
3. Login as the user from step 3

### Expected result
1. No errors

### Actual result
1. Error occors "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."
![error](https://user-images.githubusercontent.com/12183505/33270513-5f49bd38-d395-11e7-8d9a-d25104004f0e.jpg)

Seems Magento is trying to load /index.php/admin/mui/index/render/namespace=notification_area&sorting%5Bfield%5D=created_at&sorting%5Bdirection%5D=asc&isAjax=true 
but requested access to ACL resource Magento_AdminNotification::show_toolbar is denied.

**Comment by magento-engcom-team** [comment]
@ffrodoe, thank you for your report.
We've created internal ticket(s) MAGETWO-84206 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @ffrodoe 
We are closing this issue now as the fix has been delivered with the commit https://github.com/magento/magento2/commit/3839c0fc45f270839dddd6fc6025876fc2cf13c3 and should be released with 2.2.4
Thank you.
