### ISSUE TITLE
how to load product store wise?

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1246]
i think in ProductRepository class following function will load product store wise by given sku.but store_id not using any where.how to load product store wise?
Actually i want set product status website wise.
for example 1 product included in 2 websites.and i want set product status in first website enable.in second website disable.
public function get($sku, $editMode = false, $storeId = null, $forceReload = false)
    {
        $cacheKey = $this->getCacheKey(func_get_args());
        if (!isset($this->instances[$sku][$cacheKey]) || $forceReload) {
            $product = $this->productFactory->create();

            $productId = $this->resourceModel->getIdBySku($sku);
            if (!$productId) {
                throw new NoSuchEntityException(__('Requested product doesn\'t exist'));
            }
            if ($editMode) {
                $product->setData('_edit_mode', true);
            }
            $product->load($productId);
            $this->instances[$sku][$cacheKey] = $product;
            $this->instancesById[$product->getId()][$cacheKey] = $product;
        }
        return $this->instances[$sku][$cacheKey];
    }

**Comment by kokoc** [comment]
@sivajik34 You are right. `StoreId` parameter is ignored by `get` method. This behavior is definitely a bug. Appropriate item is created in backlog - MAGETWO-37275. Thank you for contacting us.

**Comment by kokoc** [comment]
@sivajik34 The fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?
