### ISSUE TITLE
Mobile menu becomes unclickable Magento 2

### ISSUE THREAD

**Issue by wd7080** [magento/magento2#12460]
### Preconditions

1. Magento 2.2.1
### Steps to reproduce

1. Store → Configuration → Catalog → Catalog
Under storefront set the following values:
- Allow products per page -> No
- Use Flat Catalog Category -> Yes
- Use Flat Catalog Product -> Yes
![flat category](https://user-images.githubusercontent.com/33989344/33289572-9eadc7ae-d385-11e7-9003-62b3236d9b9a.png)
2. Store → Configuration → Advanced → Developer
Under Javascript settings set the following values: 
- Merge JavaScript File -> Yes
- Merge JavaScript Bundling -> Yes
- Minify JavaScript File -> Yes
Under CSS Settings set the following values: 
- Merge CSS files -> Yes
- Minify CSS files -> Yes
![developer](https://user-images.githubusercontent.com/33989344/33289609-bbd46572-d385-11e7-8aec-941cd9ff412f.png)
3. Store → Configuration → Advanced → System
Under Full Page Cache set the following values:
Caching application -> Varnish Cache (recommended)
![full page cache](https://user-images.githubusercontent.com/33989344/33289545-8868f3e2-d385-11e7-9ade-a37d6c56bb0a.png)
### Expected result

1. Improve the loading speed of Magento 2

### Actual result

1. after applying the above, the menu on the mobile screens (iPhone) becomes unclickable and it becomes clickable only after changing Caching application FROM Varnish Cache (recommended) TO Built-in Cache.

**Comment by wd7080** [comment]
@magento-engcom-team Is there any update on this?

**Comment by wd7080** [comment]
Is the issue unclear? @magento-engcom-team

**Comment by magento-engcom-team** [comment]
@wd7080 thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce. Do you have SSL on in your configuration? Please provide screenshots of pages which are not working.

**Comment by wd7080** [comment]
I followed the steps above and I have the SSL on in my configuration.
Three Line Menu Navicon becomes unclickable. I can see it but when I click on it it does not open to show the menu items.
Varnish cache configuration is below:
![varnish](https://user-images.githubusercontent.com/33989344/33462214-f2a9ecde-d5fb-11e7-96e8-fca12b0e75c0.png)

**Comment by wd7080** [comment]
I followed the steps in this tutorial [https://magenticians.com/why-magento-2-is-slow/] except for:
1. Configure Memcached.
2. Content Delivery Network.

**Comment by magento-engcom-team** [comment]
@wd7080 
We consider your problem is caused by SSL. Look in this documentation -
http://devdocs.magento.com/guides/v2.1/config-guide/varnish/config-varnish.html#config-varnish-issues

**Comment by wd7080** [comment]
Thanks. I've disabled the Varnish Cache...

**Comment by wd7080** [comment]
You can close this ticket. This behaviour is due to the bug in the Varnish Cache.
