### ISSUE TITLE
Print layout broken in Firefox

### ISSUE THREAD

**Issue by Hocdoc** [magento/magento2#12464]
### Preconditions
1. Magento CE 2.1
2. Firefox 57 

### Steps to reproduce
1. Open a Magento Shop in Firefox, f.ex. http://magento2-demo.nexcess.net/
2. Print the Page (to PDF)

### Expected result

No almost-blank pages

### Actual result

Header and footer use an almost-blank page. So the user need to print 3 pages for the title page but only one page contains useful information. 

In Chrome the print layout is also unexpected, but it's better than in Firefox.

**Comment by magento-engcom-team** [comment]
@Hocdoc, thank you for your report.
We've created internal ticket(s) MAGETWO-84785 to track progress on the issue.

**Comment by gagan67commerce** [comment]
Please assign me this #MM18IN

**Comment by magento-engcom-team** [comment]
@gagan67commerce thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Delta** [comment]
@Hocdoc  @gagan67commerce Unfortunately, I am not able to reproduce issue you described on 2.4-develop
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
