### ISSUE TITLE
Inconsistent PayPal shipping address behavior during Shopping Cart PayPal checkout.

### ISSUE THREAD

**Issue by vtimonin** [magento/magento2#12472]
In general, Magento 2 allows changing the shipping address on PayPal page when PayPal checkout is started on Shopping Cart page. But if the processing quote has a valid shipping address (e.g. due to previously canceled or abandoned checkout process), then this shipping address is passed to PayPal and can't be changed on both PayPal page and Review Order page.

### Preconditions
1. A customer with default Magento shipping address.

### Steps to reproduce
1. Sign in
2. Add product to the cart.
3. Proceed to Checkout
4. Select Shipping Address and Shipping Methods
5. Click Next button
6. Cancel checkout, return to Shopping Cart
7. On Shopping Cart page press Check out with PayPal button
8. Log in to PayPal account
9. Try to change Ship to address

### Expected result
1. Shipping Address can be changed on PayPal page.
2. Shipping Address can be changed on Review Order page

### Actual result
1. Shipping Address can't be changed, “This is the address provided by XXX. You can change it on the XXX site.”
2. Shipping Address can't be changed on Review Order page (there is no such link).

It seems there are two approaches to fix this issue:
1. Don't pass information about shipping address if PayPal checkout is started from the Shopping Cart.
2. Pass this information but allow a customer to change Shiping Address on both PayPal and Review Order pages.

**Comment by magento-engcom-team** [comment]
@vtimonin, thank you for your report.
We've created internal ticket(s) MAGETWO-84799 to track progress on the issue.

**Comment by sshymko** [comment]
@magento-engcom-team 
Could you please share the idea of the intended fix.
Is it (1) or (2) suggested by @vtimonin above or something else?
We'd like to implement the workaround and would like it to be in line with the future core fix.

**Comment by sshymko** [comment]
@piotrekkaminski @maksek 
Could you please advice on the direction the fix should take.
We're on a standstill in implementing the workaround awaiting guidance of the core team.

**Comment by cdiacon** [comment]
@magento-engcom-team @sshymko any update guys on this issue, any workarounds available?

Thanks.

**Comment by sshymko** [comment]
@cdiacon 
We've implemented a workaround, but are still waiting for the core fix.

Our fix as a custom extension is below.

`app/code/Regent/PaypalFix/Plugin/Model/Express/Checkout.php`
```php
namespace Regent\PaypalFix\Plugin\Model\Express;

use Magento\Paypal\Model\Express\Checkout as Subject;

/**
 * @category Regent
 * @package Regent_PaypalFix
 */
class Checkout
{
    /**
     * @var \Magento\Quote\Model\Quote
     */
    protected $_quote;

    /**
     * Checkout constructor.
     * @param \Magento\Checkout\Model\Session $checkoutSession
     */
    public function __construct(
        \Magento\Checkout\Model\Session $checkoutSession
    ) {
        $this->_quote = $checkoutSession->getQuote();
    }

    /**
     * @param Subject $subject
     * @param string $returnUrl
     * @param string $cancelUrl
     * @param bool|null $button
     * @return array
     */
    public function beforeStart(
        Subject $subject,
        $returnUrl,
        $cancelUrl,
        $button = null
    ) {
        if ($button) {
            $quote = $this->_quote;
            $quote->removeAllAddresses();
            $quote->getExtensionAttributes()->setShippingAssignments(null);
        }
        return [$returnUrl, $cancelUrl, $button];
    }

    /**
     * @param Subject $subject
     * @param string $token
     * @return array
     */
    public function beforeReturnFromPaypal(
        Subject $subject,
        $token
    ) {
        $quote = $this->_quote;
        if (!$quote->getIsVirtual()) {
            $shippingAddress = $quote->getShippingAddress();
            if ($shippingAddress
                && $quote->getPayment()->getAdditionalInformation(Subject::PAYMENT_INFO_BUTTON) == 1
            ) {
                $shippingAddress->setCustomerAddressId(null);
            }
        }
        return [$token];
    }
}
```

`app/code/Regent/PaypalFix/etc/di.xml`
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Paypal\Model\Express\Checkout">
        <plugin name="regent_paypal_model_express_checkout"
                type="Regent\PaypalFix\Plugin\Model\Express\Checkout"
                sortOrder="10"/>
    </type>
</config>
```

**Comment by cdiacon** [comment]
@sshymko 

Thanks for sharing - will give a try to see if it solves the issue. U are the best!
