### ISSUE TITLE
Feature Request - Custom Totals Database Schema Improvement

### ISSUE THREAD

**Issue by fooman** [magento/magento2#1247]
Custom Totals are a great feature of Magento. I do believe we can improve their implementation and reduce overall complexity by keeping custom totals in separate dedicated database tables similar to how we store line items.

With the current structure to add a new custom total to cover base and order currency plus tax, at my last count, one has to add:

1.) 13 columns to table sales/order 
2.) 4 columns to sales/invoice
3.) 4 columns to sales/creditmemo

Not everyone gets this right including for example Enterprise custom totals:

    getData('base_' . $code)

vs.

    sales/order::gw_card_base_price_invoiced

I believe if we had the following tables

`sales/order_totals`
`sales/order_invoice_totals`
`sales/order_creditmemo_totals`

with the following columns:

    total_id
    parent_id
    code 
    amount 
    base_amount 
    tax_amount 
    base_tax_amount
    calculation_order 

and additionally for the `sales/order_totals` table 

    description 
    amount_invoiced 
    base_amount_invoiced 
    amount_refunded 
    base_amount_refunded 
    tax_amount_invoiced 
    base_tax_amount_invoiced  
    tax_amount_refunded  
    base_tax_amount_refunded  

this would help a lot with the aim to 
a.) remove duplication of efforts (every custom total shouldn't need to add all these columns)
b.) take away complexity of having to set up the database to reduce chances for errors 

Additionally to keep track of tax I think these should be linked through to the same table that we use to keep track of taxed items to allow for multiple taxes on the totals (and be able to reconstruct this later). If we don't link to the tax table we should at least add `tax_percentage`.

**Comment by barbazul** [comment]
+1

Current totals implementation y near to impossible to get right,  and there
is very little documentation on the subject.

Also, there is too much code duplication as most custom totals work more or
less the same

**Comment by choukalos** [comment]
@fooman @barbazul how would you like this to impact service contracts or do you want that?  If impact to service contracts should it just be passed through to the appropriate service contracts for get's but not puts/posts?

**Comment by fooman** [comment]
The service contracts on the order, invoice, creditmemo should remain the same I guess, ie `$order->getShippingAmount()` would still produce the same value. However I'd advocate for an addition to it:

    /**
     * Gets totals for the order.
     *
     * @return \Magento\Sales\Api\Data\OrderTotalInterface[] Array of totals.
     */
    public function getTotals();

**Comment by choukalos** [comment]
Created JIRA story - MAGETWO-37216.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-Custom-Totals-Database-Schema-Improvement/idi-p/47279).
