### ISSUE TITLE
Magento 2.1 Changing product order issue

### ISSUE THREAD

**Issue by winterk80** [magento/magento2#12484]
Magento 2.1.8 enterprise

Products > Categories > Products in Category

Multiple issues
1) Tile view > Change default sort to 200 per page, move something from page 2 or 3 to page 1, page sort collapses and goes back to 20 per page and page 1. Would expect to stay on the current page (2 or 3) and it to remain at 200 per page.

2) Tile view >  Remove a product on page 2 or 3  page sort collapses and goes back to 20 per page and page 1. Would expect to stay on the current page (2 or 3) and it to remain at 200 per page.

3) Also can you add the option to show all or 500 per page. It's cumbersome to edit when there are multiple pages, allowing more per page than 200 or a show all would remedy the issue. 

4) Should add ability to sort products with 0 qty to the bottom

**Comment by magento-engcom-team** [comment]
@winterk80, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
