### ISSUE TITLE
MOBILE : Vimeo or Youtube keeps closing on Full screen mode

### ISSUE THREAD

**Issue by joebordo** [magento/magento2#12489]
If you are in Full screen product gallery mode, and want to load a video from Vimeo or youtube, it opens the full screen then closes again.

Vimeo does not allow inline. So everything has to play fullscreen (it blocks).
Youtube does play inline, but if you go full screen (it also gets blocked).

### Preconditions
I use magento 2.2
Php 7.1

Android : Chrome Browser
Iphone : Safari Browser:

For some Reason Iphone Chrome browser seems to work. (weard)

### Steps to reproduce
For Vimeo
1. Add Vimeo video on one of your products.
2. On REAL mobile device, go to the product page, 
3. Click on image to go full screen
4. Choose video and play.
5. It opens and closes. 

For youtube:
Same steps as above, but when you play the youtube video click on full screen icon of youtube .

### Expected result
The video should play normally.

### Actual result
Video opens then closes. 

PS: USE REAL MOBILE DEVICES. On chrome developer tools it works fine.

**Comment by magento-engcom-team** [comment]
@joebordo, thank you for your report.
We've created internal ticket(s) MAGETWO-84798 to track progress on the issue.

**Comment by rohit-wagento** [comment]
I have checked in chrome and safari browser in real mobile device vimeo is playing on fullscreen and not blocking, and youtube is playing inline and on fullscreen nothing is blocking on my case, issue seems to be resolved on 2.2.4 dev

**Comment by JTessmer** [comment]
@rohit-wagento -- Do you know which change corrected the issue? We're experiencing this bug as well, and would like to apply a fix in production immediately without waiting for 2.2.4's release, if possible.

**Comment by magento-engcom-team** [comment]
@joebordo, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
