### ISSUE TITLE
500 error when resending order confirmation from backend

### ISSUE THREAD

**Issue by OscarMadia** [magento/magento2#12480]
A http 500 error occures in php/error.log after resending the order confirmation mail from an existing order in the back-end.

### Preconditions
1. Magento ver. 2.1.7 
2. PHP 7.0.24-1 (cli) (built: Sep 28 2017 21:34:20) ( NTS )
3. Zend Engine v3.0.0

### Steps to reproduce
1. in Admin Panel > Sales Orders > select order
2. [Send Email]
3. [yes] at confirmation question

### Expected result
1. receive order confirmation e-mail and see message 'You sent the order email.'

### Actual result
1. blank screen, on inspector/network we see 500 error
2. following error in php/error.log
PHP Fatal error:  Uncaught TypeError: IntlDateFormatter::__construct() expects parameter 2 to be integer, string given in /vendor/magento/framework/Stdlib/DateTime/Timezone.php:282
Stack trace:
#0 /vendor/magento/framework/Stdlib/DateTime/Timezone.php(282): IntlDateFormatter->__construct('en_US', 'dd-MM-yy', 'dd-MM-yy', 'Europe/Amsterda...', NULL, NULL)
#1 /vendor/magento/module-sales/Model/Order.php(1840): Magento\Framework\Stdlib\DateTime\Timezone->formatDateTime(Object(DateTime), 'dd-MM-yy', 'dd-MM-yy', NULL, 'Europe/Amsterda...')
#2 [internal function]: Magento\Sales\Model\Order->getCreatedAtFormatted('dd-MM-yy')
#3 /vendor/magento/framework/Filter/Template.php(343): call_user_func_array(Array, Array)
#4 /vendor/magento/framework/Stdlib/DateTime/Timezone.php on line 282

According to http://php.net/manual/en/class.intldateformatter.php  $datetype has to be an integer. In vendor/magento/module-sales/Model/Order.php:1840 it provides a string:
     /**
     * Get formatted order created date in store timezone
     *
     * @param   string $format date format type (short|medium|long|full)
     * @return  string
     */
    public function getCreatedAtFormatted($format)
    {
        return $this->timezone->formatDateTime(
            new \DateTime($this->getCreatedAt()),
            $format,
            $format,
            null,
            $this->timezone->getConfigTimezone('store', $this->getStore())
        );
    }

Kind regards,
Oscar Hilbelink,
Oscar@Madia.nl

**Comment by magento-engcom-team** [comment]
@OscarMadia thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by OscarMadia** [comment]
Hi,

We can close this report. Customer had used the following line in the transaction e-mail for order confirmation.
{{trans "%date" date=$order.getCreatedAtFormatted('dd-MM-yy')}}

Thanks.

**Comment by magento-engcom-team** [comment]
@OscarMadia, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by ishakhsuvarov** [comment]
@OscarMadia Thank you for the update!
