### ISSUE TITLE
Stock increases automatically

### ISSUE THREAD

**Issue by devendra-m** [magento/magento2#12483]
Stock increases automatically for some products randomly. 

### Preconditions
1. Magento ver. 2.1.7. 
2. PHP 7.0.26 (cli) (built: Nov 21 2017 14:36:41) ( NTS )

### Steps to reproduce
1. It happens randomly. Qty sometimes gets increased automatically sometimes not.
 
### Expected result
1. Qty should not increase when it is not updated manually from admin panel. 

### Actual result
1. Qty for product automatically increases after some time

**Comment by orlangur** [comment]
I really doubt this issue is reproducible with such steps. Can you track it a bit on your side maybe to understand the root cause?

**Comment by devendra-m** [comment]
Its difficult to reproduce this issue because it happens at random times. I tried to track but couldn't find the cause.

**Comment by hellekim** [comment]
I’ll add some additional info as I run the shop. 

Giving specific circumstancies is super hard as I’ve not been able figure out why this happens. 

Configurable products keep getting these all the time - the stock amount keeps rising, so in this case it can be the main product for t-shirt. I usually clean these every few weeks and some (usually more popular products) might have gone up from 0 to 60 - usually I got around 60-70 of these products.

Another issue is that occasionally the product’s stock value doesn’t update when it’s purchased. I might get 10 orders with 3-4 products in them and with only one of those products have not updated with -1 to stock value.

This second issue is by far the most frutrating as it causes dissapointments to my customers occasionally.

Thanks for reading.

**Comment by orlangur** [comment]
Looks somewhat opposite to https://github.com/magento/magento2/issues/6363, could be related.

**Comment by magento-engcom-team** [comment]
@devendra-m, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by Jeroenll** [comment]
You see any canceled orders with those products? If so, could also be related to https://github.com/magento/magento2/issues/9969

**Comment by hellekim** [comment]
@JeroenVanLeusden this is exactly what happens - thank you!

**Comment by plastiqman** [comment]
Hi there,
We have a similar problem @hellekim 
Preconditions
Magento ver. 2.1.9.
PHP 7.0.26
Some products do not discount the amount in same order. 
This errors happen in random way.
I have set a trigger in a catalog_inventory_stock_item to debugging and I can see that first discount the qty and immediately after insert the quantity again. (103)
http://vvcap.com/imoOdIWzlQ2
You can see all products in the order:
http://vvcap.com/0D2JJhsKH24
This product in other orders discount the stock. Therefore, it can not be the problem of the product.
Thanks.

**Comment by magento-engcom-team** [comment]
@devendra-m, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by vishalnyati** [comment]
@magento-engcom-team  We are also getting same issue in Magento 2.2.6 .  We did migration from Magento 1.9.2 .
We also observed cataloginventory_stock_item_save_after .. this event is getting hit multiple times in a second and qty is increasing automatically.
Looking for an solution. Its creating lots of problem.

**Comment by hellekim** [comment]
For us the issue was payment extension - everytime someone canceled the order the items were returned to stock twice. Payment extension was Paytrail.

**Comment by charleskj** [comment]
This is happening to us also.
Migrated from m1 to m2-2.2.6.
In our case, stock get incremented very frequently for some particular products.

**Comment by charleskj** [comment]
This is related to this issue : https://github.com/magento/magento2/issues/19230

Actually what happened is magento tries to cancel the expired orders in the past and put back the stock of cancelled item.
This job is throwing some error in middle, unfortunately it happened after stock get increased, but order status not updated to cancel.
So job will pick the same order again and again which result in increasing stock going on.

I turn off that cron job for quick fix.

![stock increase bug fix by charleskj pull request 251 yatnam fightclubstore](https://user-images.githubusercontent.com/3807333/52837069-51525280-3113-11e9-8b29-070ab2924a20.png)

**Comment by MarinaBonbonRose** [comment]
Hello, same problem for me. Migrated from m1.7 to m2-2.2.6. 
I'm not sure to turn off this cron, is there any other consequence ?
Any other solutions?

**Comment by kevintieman** [comment]
Same here. Happened at 2.2.7, upgraded to 2.3.1 still the same.
