### ISSUE TITLE
Will cron.sh/cron.php be standardized?

### ISSUE THREAD

**Issue by kojiromike** [magento/magento2#1248]
There are still two ways to trigger cron, just like Magento 1: cron.sh and cron.php. Does Magento still plan to keep both of these around for Magento 2? Alternatively, is there any thought to making cron.php consistent with the bin/magento CLI interface described in http://magento.com/blog/technical/magento-command-line-interface-cli?

If cron.sh is going to stay around I will submit a PR to simplify it, and I'd like to suggest Magento adopt [shellcheck](http://www.shellcheck.net/) and some shell style standards as part of its CICD processes.

(On a related note, is dev/tools/Magento/Tools/psr/phpcs_precommit_hook.sh actively being used? It's the only other shell script in the codebase.)

**Comment by orlangur** [comment]
> is dev/tools/Magento/Tools/psr/phpcs_precommit_hook.sh actively being used?

There is a better hook, with auto-correction, involving php-cs-fixer: https://github.com/magento/magento2/blob/develop/dev/tools/Magento/Tools/StaticReview/pre-commit

As soon as this new hook will be able to involve phpcs, the older one will be not needed anymore.

**Comment by mbrinton01** [comment]
@kojiromike cron.sh will be removed and migrated to the bin/magento CLI interface you linked to above. This work is currently in process so you do not need to make any changes to cron.sh.

I will also reply back on your second question shortly after some more research.

**Comment by mbrinton01** [comment]
Thank you @orlangur.  @kojiromike if you have any other questions about this please reply otherwise I will close out the issue shortly.

**Comment by kojiromike** [comment]
Nope, I'm all good.

**Comment by mbrinton01** [comment]
Thank you, closing issue.
