### ISSUE TITLE
 Entity with the same ID already Exists : Grouped vs Decimal attribute

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#12488]
You can find a lot of information here 
https://magento.stackexchange.com/questions/203324/layered-navigation-item-with-same-id-already-exists/203356?noredirect=1#comment282875_203356

Now what happends is when i have an attribute 'price' stored in the database table `catalog_product_index_eav_decimal` it generates a row with the same entity_id but with a different source_id for each child of a grouped product with their value. This looks like this

![image](https://user-images.githubusercontent.com/18028151/33392826-7aa286ec-d53d-11e7-9150-e72870e324e4.png)

When it filters with the layered navigation it uses the next SQL 

```
SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `stock_status_index`.`stock_status` AS `is_salable`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `name` FROM `eh_catalog_product_entity` AS `e`
 INNER JOIN `eh_catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='20'
 INNER JOIN `eh_catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = '1'
 INNER JOIN `eh_catalog_product_index_eav_decimal` AS `adviced_price_idx` ON adviced_price_idx.entity_id = e.entity_id AND adviced_price_idx.attribute_id = '170' AND adviced_price_idx.store_id = 1
 INNER JOIN `eh_search_tmp_5a1efe74359894_32938478` AS `search_result` ON e.entity_id = search_result.entity_id
 LEFT JOIN `eh_cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 LEFT JOIN `eh_catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '73') AND `at_name_default`.`store_id` = 0
 LEFT JOIN `eh_catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '73') AND (`at_name`.`store_id` = 1) WHERE (adviced_price_idx.value >= 0) AND (adviced_price_idx.value < 10) ORDER BY `name` ASC
 LIMIT 9
```
It selects entity_id but i see not a single check if it has different source_id's...

When i delete until 1 remains/store then the error dissapears

### Preconditions
1. Magento 2.2.1 
2. Server version: 5.6.37-82.2-log - Percona Server (GPL), Release 82.2, Revision d1eb51005df
3. PHP version: 7.0.25-1

### Steps to reproduce
1.  create grouped products and child products (link them)
2.  create new attribute with type 'price'
3.  fill in the price within grouped and child products
4. reindex
5. use your attribute in the layered navigation
6. filter with that attribute so it retrieves the product that you used

### Expected result
1. Just return search results

### Actual result
1.  See explanation on top. It shows the error ' Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "871" already exists'
So this attribute is not filterable..?

**Comment by versdivers** [comment]
BTW the solution should be that for that table OR you can have multiple entity_id's OR it filters by source ID OR the table should save the child product as entity_id and the parent as source_id (which would be an array since you can have multiple parents)

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by versdivers** [comment]
Can you try to manually put in the situation that i have in the database table like i have it and continue testing? Let me know if it is reproducible then. It should be. Or can you give me some kind of explenation how that table is generated? Why do i have multiple entity_id's ?

**Comment by magento-engcom-team** [comment]
@versdivers, unfortunately, we cannot give you an answer before we could reproduce this issue.

**Comment by versdivers** [comment]
Is it possible like i ask to manually put the same value in that table with a difference source id and try to filter with the filter navigation?

**Comment by versdivers** [comment]
Any update on this?

**Comment by magento-engcom-team** [comment]
Hi @versdivers thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by versdivers** [comment]
If i would tell you an elephant is black and i gave you a picture of it you do not believe its black until you can find one? I mean you can clearly see that you do not use 'source id' in your SQL query what so ever... but 'source id' is what represents the product. 'entity id' is just the grouped product so you should be able to have multiple entity id's since multiple lines are created with the same entity ID but with another source id. So the error just doesn't make sense.. Can you provide me any information or a dialog that we can invest this better instead of 'we are not able to reproduce this issue'.
