### ISSUE TITLE
Sitemap image links in MultiStore

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#12482]
### Preconditions

1. Magento 2.2.0
2. mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22

### Steps to reproduce

1. You should have multistore project.
2. Generate sitemap for your store by Merketing-> Site Map (default feature in magento 2)

### Expected result

1. I should get a sitemap with all urls like http://mystore.com/ 

### Actual result

1. But I've got http://defaultstore.com/ .

![screenshot from 2017-11-29 15-25-09](https://user-images.githubusercontent.com/10618641/33377611-cbe12a54-d51a-11e7-9a96-50b568c2cab0.png)

**Comment by magento-engcom-team** [comment]
@AleksLi, thank you for your report.
We've created internal ticket(s) MAGETWO-84731 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @AleksLi 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.
