### ISSUE TITLE
Stream handler can't be used in Io\File

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#12481]
The class `Magento\Framework\Filesystem\Io\File` contains some `stream*` functions and they all check if the `$_streamHandler` parameter is defined before doing anything.

My issue is that there is no function to initialize or set this `$_streamHandler` parameter so all the `stream*` function seem to be useless.

Is there a function missing? Or am I supposed to extend this class and initialize the `$_streamHandler` in my own class? If it's the case, why is it done like this?

**Comment by magento-engcom-team** [comment]
Hello @VincentMarmiesse. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
