### ISSUE TITLE
Admin URL

### ISSUE THREAD

**Issue by teknology** [magento/magento2#1249]
The admin url ,it appears, was developed to read from a local wamp server. It does not include the url used during installation. The issue was found when navigating to the admin panel and the css and js did not load.

Here's an example of an image trying load. 

My installation url is randwebsitedesign.com/~magetwo/ yet the url it's trying to load is 
img class="logo-img" src="http://localhost/pub/static/adminhtml/Magento/backend/en_US/images/magento-logo.svg" alt="Magento Admin Panel"

Note: I'm reviewing Magento 2 in a development server environment that has a control panel used in many production hosting companies.

**Comment by mazhalai** [comment]
@teknology did you install using CLI or Web Setup? If you used Web Setup, what url was shown on success page as `Magento Admin Address:`?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.

**Comment by mohsen9010** [comment]
I have the same problem , can not see any images
Magento Admin Address:
http://rayasys.ir/admin_92lfpz/
