### ISSUE TITLE
2.2.1 REST Product Custom Attributes cannot be updated on store level

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#12496]
When trying to save a value from custom_attributes to a specific store view, the original value from the default scope is taken and saved in the store scope.
(While this works correctly for attributes outside of the custom_attributes array - e.g "name")

### Preconditions

1. Magento 2.2.1
2. Product with value for meta_title (for example) in default scope is "original title"

### Steps to reproduce

1. REST PUT {{base_url}}/rest/{{store_code}}/V1/products/{{product_sku}}
```json
{
	"product": {
	    "attribute_set_id": 4,
	    "custom_attributes": [
	        {
	            "attribute_code": "meta_title",
	            "value": "translated title"
	        }
	    ]
	}
}
```

### Expected result

1. Meta Title in store scope and store {{store_code}} is "translated title"

### Actual result

1. Meta Title in store scope and store {{store_code}} is "original title"

**Comment by davidverholen** [comment]
@magento-engcom-team just tried to reproduce it and it seems it has already been fixed in 2.2-develop. Do you maybe have an idea, where?

**Comment by davidverholen** [comment]
actually I cannot reproduce this on a clean 2.2.1 either.
Let me investigate further steps to reproduce

**Comment by davidverholen** [comment]
nevermind, it's some weird side effect with a local plugin

**Comment by magento-engcom-team** [comment]
Hello @davidverholen. Anyway thanks for applying. While trying to reproduce Your issue we discovered that if the attribute_code in BODY is set to some wrong, not existing value, You will have get the response of 200 OK, just nothing will have been changed (a kind of incorrect behavior). So the issue could occur too if You accidentally sent an incorrect code value. Otherwise we've been not able to reproduce the issue.

**Comment by OleksandrZelenchuk** [comment]
It appears to still be and issue in 2.4.3-p1.
Did some investigation and apparently it only take place if you try to update value of attribute which does not have a store value yet. If you remove a check box to use default value in backend on store level and then save a product manually - next time you try to update attribute via rest call it will work.
