### ISSUE TITLE
After upgrading magento version 2.1.0 to 2.2.1 getting error unable to unserialize value

### ISSUE THREAD

**Issue by pradeepnew** [magento/magento2#12491]
I have tried to upgrade 2.1.0 to 2.2.1 version via composer upgrade.
Upgrade was successful but when i try to open website frontend, its showing "Unable to unserialize value" error.

**Preconditions**
Magento 2.2.1
PHP 7.0

**Steps to reproduce**
Upgrade 2.1.0 version to latest 2.2.1 via composer
run upgrade command and deploy command

**Expected result**
All fine but when we try to open website it throwing error Unable to unserialize value.

**Actual result**
`1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 /var/www/html/vendor/magento/module-widget/Helper/Conditions.php(59): Magento\Framework\Serialize\Serializer\Json->unserialize('a:2:[i:1;a:4:[s...')
#1 /var/www/html/vendor/magento/module-catalog-widget/Block/Product/ProductsList.php(259): Magento\Widget\Helper\Conditions->decode('a:2:[i:1;a:4:[s...')
#2 /var/www/html/vendor/magento/module-catalog-widget/Block/Product/ProductsList.php(236): Magento\CatalogWidget\Block\Product\ProductsList->getConditions()
#3 /var/www/html/generated/code/Magento/CatalogWidget/Block/Product/ProductsList/Interceptor.php(50): Magento\CatalogWidget\Block\Product\ProductsList->createCollection()
#4 /var/www/html/vendor/magento/module-catalog-widget/Block/Product/ProductsList.php(216): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->createCollection()
#5 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\CatalogWidget\Block\Product\ProductsList->_beforeToHtml()
#6 /var/www/html/generated/code/Magento/CatalogWidget/Block/Product/ProductsList/Interceptor.php(817): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->toHtml()
#8 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('71feee93b718ea1...')
#9 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('71feee93b718ea1...')
#10 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('71feee93b718ea1...')
#11 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('71feee93b718ea1...', true)
#12 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('71feee93b718ea1...')
#13 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#14 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#15 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#16 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#17 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#18 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main')
#19 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#20 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#21 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#22 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#23 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns')
#24 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#25 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#26 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#27 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#28 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content')
#29 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#30 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#31 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#32 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#33 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#34 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#35 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#36 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#37 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#38 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper.ou...')
#39 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper.ou...')
#40 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper.ou...')
#41 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper.ou...', true)
#42 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper.ou...')
#43 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#44 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#45 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#46 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#47 /var/www/html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#48 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#49 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#50 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#51 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#52 /var/www/html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#53 /var/www/html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#54 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#56 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#57 /var/www/html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#58 /var/www/html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /var/www/html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#60 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#61 {main}`

**Comment by magento-engcom-team** [comment]
@pradeepnew  , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by eCommerceGorilla** [comment]
If you disable your third party modules and then refresh your cache you should gain access back to the site. More than likely you have a module that have not been updated to run with the 2.2 serialization changes outlined http://devdocs.magento.com/guides/v2.2/release-notes/backward-incompatible-changes.html

**Comment by duongquyet** [comment]
Hi,
I have same problem. Did you fix it?

**Comment by magento-engcom-team** [comment]
@pradeepnew  thanks for the feedback. Unfortunately, we cannot reproduce this issue. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by daniloargentiero** [comment]
I had the same problem.
Flush your cache should be fix your problem, in my case:

redis-cli flushall

If this isn't enough, also truncate these tables:
- magento_logging_event (not recoverable)
- sales_invoice_grid
- sales_order_grid

After upgarade you can recover the tables' content:

1. Set this configuration: config/system/developer grid async -> enabled
2. Run the cron
1. Set this configuration: config/system/developer grid async -> previous value

I hope it works for you.

**Comment by magento-engcom-team** [comment]
@pradeepnew, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
