### ISSUE TITLE
Credit Memo Adjustment fee tax isn't calculated

### ISSUE THREAD

**Issue by violuke** [magento/magento2#12494]
Duplicate of #7937 which was wrongly closed before but is an serious bug from an accounting perspective. All details on that issue.

## Preconditions
Magento 2.1.2 - 2.1.10 (I believe 2.2.1 too but not tested)

## Steps to reproduce
Create a credit memo and add an adjustment refund / fee

## Expected result
Tax is recalculated

## Actual result
No difference in tax

**Comment by magento-engcom-team** [comment]
@violuke , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by violuke** [comment]
Thanks for the reply, but I don't see how any further information is needed. See #7937, it's all explained there. Thanks.

**Comment by magento-engcom-team** [comment]
@violuke Thanks for the feedback. Please provide preconditions and steps to reproduce here, even if they duplicate ones from previous issue.

**Comment by violuke** [comment]
Ok, I've updated the original message above. Thanks.

**Comment by magento-engcom-team** [comment]
@violuke, thank you for your report.
We've created internal ticket(s) MAGETWO-84801 to track progress on the issue.

**Comment by Echron** [comment]
Is there any progress on this issue? @violuke How did you deal with this issue?

**Comment by ACassiusD** [comment]
Any progress on this?

**Comment by LindenFR** [comment]
Any news or updates on this please ?

**Comment by sdzhepa** [comment]
Duplicate of #23938
