### ISSUE TITLE
EAV custom module with onlyone data type table

### ISSUE THREAD

**Issue by abdulbasitnawab** [magento/magento2#12492]
Hi
I created a custom module with one data type ie Text, So i had two table one with postfix _entity and the other with _entity_text. I followed the catalog_product structure and built a module. All the di.xml etc was configured and the module was saving for multiple storeviews. But while editing I found that if I change the storeview always it is showing data for default store "0". I compared all my settings with the catalot-product and it was all fine. Upon inspection I found that in vendor/magento/framework/EntityManager/Operation/Read/ReadAttributes.php 
followed by 
/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php
There is union of selects. As in my case i had only one table _entity_text so the order of the eav value for entity data was in reverse order ie first storeid value and then default value. So the storeid value for that entity was overwritten by the default "0" value. What I did to solve this is to make another table _entity_varchar and assign some of attributes as varchar. As I started using two eav tables _entity_text and _entity_varchar  it started showing the correct values in the edit form.
Can not I use only one data table or it is compulsory to use more then one data type tables or this is a bug in the system.

**Preconditions:**
Magento 2.1.7 With sample data
New custom module with eav structure is created and installed with only one data type _entity_text.

**Steps to reproduce**
Create a new custom module eav with only one data table (_entity_text)
Save data 
In the edit switch store view.

**Actual and Expected result**
Expected Result
Each text box should show the selected storeview data
Actual Result
In any store view the default store data is coming not the selected store data.

**Comment by magento-engcom-team** [comment]
@abdulbasitnawab, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@abdulbasitnawab , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@abdulbasitnawab, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
