### ISSUE TITLE
After adding custom price to product currency is not converting on cart page and checkout

### ISSUE THREAD

**Issue by vishalmangoitsolutions** [magento/magento2#12493]
### Preconditions

1. Magento 2.2

### Steps to reproduce

1. Followed following thread to add item in cart with custom price:
https://webkul.com/blog/magento2-set-custom-price-of-product/

### Expected result

1. item custom price, subtotal should convert to selected currency on cart page, minicart and checkout.

### Actual result

1. Currency symbol is changed but currency not converting.

I have tried to fix item price issue by replace line 430
$price = $this->getCustomPrice();
with
$price = $this->priceCurrency->convert($this->getCustomPrice(), $this->getStore());
in file
magento22/vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php
It is working fine too but subtotal doesn't change.

**Comment by magento-engcom-team** [comment]
@vishalmangoitsolutions, thank you for your report.
We've created internal ticket(s) MAGETWO-84805 to track progress on the issue.

**Comment by vishalmangoitsolutions** [comment]
Is there any update on the issue?

**Comment by popovdenis** [comment]
#mageconf

**Comment by popovdenis** [comment]
Hi @vishalmangoitsolutions,
custom price is using only in Admin area when we reorder or edit an order. In that case we can change price item and set a custom price. The currency would not be changed and stayed as it was when the order had been placed.

So, the provided way (https://webkul.com/blog/magento2-set-custom-price-of-product/) of using custom price is not correct. And that is why it doesn't work as it was expected.

**Comment by vishalmangoitsolutions** [comment]
Hello,

Thanks for acknowledge me.

So Is there any correct way to add product in cart with custom price in fly?

Regards

**Comment by ishakhsuvarov** [comment]
@popovdenis Thank you for your research. Closing the issue per your comment.
@vishalmangoitsolutions You may refer to the community forums or magento stackexchange for general advice or discussion.

Thanks.

**Comment by popovdenis** [comment]
@vishalmangoitsolutions, you can add special price.

**Comment by koushikch7** [comment]
@vishalmangoitsolutions  can you please give me how this as resolved? are you using a special price as mentioned by @popovdenis? your input will be helpful.
