### ISSUE TITLE
Admin controller redirects to frontend

### ISSUE THREAD

**Issue by apedicdev** [magento/magento2#12502]
### Preconditions

Magento 2.1.9
**Set a custom admin host (eg admin.website.com)**

### Steps to reproduce

1. create an admin controller redirecting to Referrer Url  

```
$redirectUrl = $this->_redirect->getRedirectUrl($this->getUrl('*'));
$this->getResponse()->setRedirect($redirectUrl);
```
2. test or debug the controller

### Expected result

1. the controller should redirect to the referrer admin url

### Actual result

1. the controller redirect to the frontend 

it seems `\Magento\Store\App\Response\Redirect` is not able to return the valid admin referrer url if it's different from the frontend base_url (eg: www.shop.com and admin.shop.com)

**Comment by orlangur** [comment]
Where do you see `\Magento\Store\App\Response\Redirect` is aware of admin? Is `$this->_storeManager->getStore()->getBaseUrl()` returning admin base URL when executed in context of admin controller?

**Comment by apedicdev** [comment]
@orlangur '`$this->_storeManager->getStore()->getBaseUrl()` returns the frontend url because I use a custom admin url. I have to specify the `storeId=0` to get the correct admin url

**Comment by orlangur** [comment]
> it seems `\Magento\Store\App\Response\Redirect` is not able to return the valid admin referrer url if it's different from the frontend base_url (eg: www.shop.com and admin.shop.com)

@apedicdev, where in `\Magento\Store\App\Response\Redirect` class do you see any logic related to admin URLs?

**Comment by apedicdev** [comment]
@orlangur I can't see any, but using xdebug this function is called:
```
/**
     * Check whether URL is internal
     *
     * @param string $url
     * @return bool
     */
    protected function _isUrlInternal($url)
    {
        if (strpos($url, 'http') !== false) {
            $directLinkType = \Magento\Framework\UrlInterface::URL_TYPE_DIRECT_LINK;
            $unsecureBaseUrl = $this->_storeManager->getStore()->getBaseUrl($directLinkType, false);
            $secureBaseUrl = $this->_storeManager->getStore()->getBaseUrl($directLinkType, true);
            return (strpos($url, $unsecureBaseUrl) === 0) || (strpos($url, $secureBaseUrl) === 0);
        }
        return false;
    }
```

So I guess the admin url is compared with base url which is different cause I use a custom host and it returns false. By consequence, the previous  method returns the base frontend url instead of the admin.

**Comment by orlangur** [comment]
> $this->_storeManager->getStore()->getBaseUrl() returns the frontend url because I use a custom admin url. I have to specify the storeId=0 to get the correct admin url

You mean something like `$this->_storeManager->getStore(0)->getBaseUrl()` works correctly only?

**Comment by apedicdev** [comment]
@orlangur yes it returns the correct base admin url.

**Comment by orlangur** [comment]
Well, as you can see from a lot of `$this->_storeManager->getStore()->` calls this class is not supposed to work with admin store. You can implement your own class similar to the `\Magento\Store\App\Response\Redirect` which will have different logic.

**Comment by apedicdev** [comment]
@orlangur it's exactly what I reported.` \Magento\Store\App\Response\Redirect `does not return the admin url from an admin controller context. I've to use as a workaround something it's not supposed to work with admin

**Comment by ask694** [comment]
Anyone please share the solution for this issue. Still this issue is coming on magento 2.3 and in magento 2.2   If i try to use a subdomain like admin.domain.com it gets redirected to my frontend like www.domain.com/admin/admin

**Comment by requix** [comment]
@ask694, for me it works only with filled Custom Admin Path. but you can use 'admin' value for this field. Tested on Magento 2.2.9

<img width="906" alt="Screenshot 2019-09-23 at 20 41 24" src="https://user-images.githubusercontent.com/5894713/65453090-cb358180-de42-11e9-8644-060ecec37bdc.png">

**Comment by ask694** [comment]
> @ask694, for me it works only with filled Custom Admin Path. but you can use 'admin' value for this field. Tested on Magento 2.2.9
> 
> <img alt="Screenshot 2019-09-23 at 20 41 24" width="906" src="https://user-images.githubusercontent.com/5894713/65453090-cb358180-de42-11e9-8644-060ecec37bdc.png">

Did you tried a custom domain url  / subdomain url for a admin panel?  I had already known custom admin path working good but problem is on custom admin url.

**Comment by requix** [comment]
@ask694, yes, works good for us .
we use https://admin.domain.com/custom_admin
in our case subdomain works only in combination with custom path (like on previous screenshot)

**Comment by ask694** [comment]
Hi, I had tried in Magento 2.3.1 Still  it getting redirected to base url.   I had set  https://admin.domain.com/customadminpath   but it is getting redirected to https://www.domain.com/customadminpath.  Why this happens for me?  i'm using memcache / varnish  also. But i had cleared the cache. still not working.

**Comment by oscarsanch** [comment]
in \Magento\Store\App\Response\Redirect
```
    /**
     * Check whether URL is internal
     *
     * @param string $url
     * @return bool
     */
    protected function _isUrlInternal($url)
    {
        if (strpos($url, 'http') !== false) {
            $directLinkType = \Magento\Framework\UrlInterface::URL_TYPE_DIRECT_LINK;
            $unsecureBaseUrl = $this->_storeManager->getStore()->getBaseUrl($directLinkType, false);
            $secureBaseUrl = $this->_storeManager->getStore()->getBaseUrl($directLinkType, true);
            return (strpos($url, (string) $unsecureBaseUrl) === 0) || (strpos($url, (string) $secureBaseUrl) === 0);
        }
        return false;
    }
```
need to change from:
`return (strpos($url, $unsecureBaseUrl) === 0) || (strpos($url, $secureBaseUrl) === 0);`
to:
`return (strpos($url, (string) $unsecureBaseUrl) === false) || (strpos($url, (string) $secureBaseUrl) === false);`

**Comment by engcom-Charlie** [comment]
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.

**Comment by GuiltyNL** [comment]
I think specifying the admin run code in the webservers config, could solve this issue too. Please see: https://github.com/magento/magento2/issues/12354#issuecomment-588998818

**Comment by GuiltyNL** [comment]
> it seems `\Magento\Store\App\Response\Redirect` is not able to return the valid admin referrer url if it's different from the frontend base_url (eg: [www.shop.com](http://www.shop.com) and admin.shop.com)

It is only able to do so when you pass the MAGE_RUN_CODE admin in Nginx or Apache. But that results in other unexpected beaviour like Magento searcing for product tables in Store 0 (and those don't exist) and other referral issues on the frontend (after adding products to a wishlist) and issues with incorrect links in certain emails that are mailed to customers (they receive backend links where it should be frontend links).

So adding the run code for admin will solve the issue that it is not able to find the redirect or referrer url, but breaks alot of other things.

If I use :

`use Magento\Framework\Controller\ResultFactory;`

With this for example:

```
$resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
$resultRedirect->setUrl($this->_redirect->getRefererUrl());
        return $resultRedirect;
```

It is only able to het the backend referrer url when I specify MAGE_RUN_CODE admin; in Nginx. 

When I does not do so, if will not be able to find it and it does a fall back to a base url wich is the url of store 1.

**Comment by GuiltyNL** [comment]
This PR seems to fix the issue:

https://github.com/magento/magento2/pull/25563/files

**Comment by denniskopitz** [comment]
In case this helps anyone else landing here, I believe the actual core issue is that admin controllers are not set to the admin store.  ie, when you getStore(), the default store is retrieved (ie frontend store).  The easy fix is to `$this->storeManager->setCurrentStore(0);` before you try 

```
$resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
$resultRedirect->setUrl($this->_redirect->getRefererUrl());

```

That will actually cause `$this->_redirect->getRefererUrl()` to return the correct url

Ofcourse, This bug only manifests when your store has a custom admin url set, which is why I think so few peeps have logged issues about it.

**Comment by denniskopitz** [comment]
I actually ended up putting a plugin in place because this issue was also affecting some third party modules.

```
<type name="Magento\Store\App\Response\Redirect">
        <plugin name="NAMESPACE_Redirect_Plugin" type="NAMESPACE\MODULE\Plugin\Response\Redirect" />
</type>
```

```
<?php
namespace NAMESPACE\MODULE\Plugin\Response;

use Magento\Framework\App\Area;
use Magento\Framework\App\State;
use Magento\Framework\Exception\LocalizedException;
use Magento\Store\Model\StoreManagerInterface;

class Redirect
{

    /**
     * @var StoreManagerInterface
     */
    private $storeManager;
    /**
     * @var State
     */
    private $state;

    public function __construct(
        StoreManagerInterface $storeManager,
        State $state
    )
    {
        $this->storeManager = $storeManager;
        $this->state = $state;
    }

    public function beforeGetRefererUrl(\Magento\Store\App\Response\Redirect $subject)
    {
        try {
            if ($this->state->getAreaCode() == Area::AREA_ADMINHTML) {
                $this->storeManager->setCurrentStore(0);
            }
        } catch (LocalizedException $e) {
        }
    }

}
```

**Comment by gwharton** [comment]
Still running into this in 2.4.5-p1 :)
