### ISSUE TITLE
Magento 2 0.74.0-beta8 installed successfully, but home page 404 not Found and admin page broken

### ISSUE THREAD

**Issue by pccomfrank** [magento/magento2#1250]
At first I  was trying to install the sample data. It won't be installed. Then I was trying to install it without sample data. I could be installed but the home page 404 error and the admin page broken.
The following are the log and screen shots.

Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema.. 

Module 'Magento_Directory':
Installing schema.. 

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Theme':
Installing schema.. Upgrading schema.. 

Module 'Magento_CacheInvalidate':

Module 'Magento_Eav':
Installing schema.. 

Module 'Magento_Customer':
Installing schema.. Upgrading schema.. 

Module 'Magento_CatalogImportExport':

Module 'Magento_Indexer':
Installing schema.. 

Module 'Magento_Cms':
Installing schema.. 

Module 'Magento_Search':
Installing schema.. 

Module 'Magento_Catalog':
Installing schema.. Upgrading schema.. 

Module 'Magento_Rule':

Module 'Magento_CatalogInventory':
Installing schema.. 

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreements':
Installing schema.. 

Module 'Magento_Quote':
Installing schema.. 

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':
Installing schema.. 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':
Installing schema.. 

Module 'Magento_Widget':
Installing schema.. 

Module 'Magento_Bundle':
Installing schema.. 

Module 'Magento_CustomerImportExport':

Module 'Magento_DesignEditor':
Installing schema.. 

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':
Installing schema.. 

Module 'Magento_Downloadable':
Installing schema.. 

Module 'Magento_SalesSequence':
Installing schema.. 

Module 'Magento_Email':
Installing schema.. 

Module 'Magento_Fedex':

Module 'Magento_Sales':
Installing schema.. Upgrading schema.. 

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':
Installing schema.. 

Module 'Magento_GoogleShopping':
Installing schema.. 

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_ImportExport':
Installing schema.. 

Module 'Magento_CatalogRule':
Installing schema.. 

Module 'Magento_User':
Installing schema.. 

Module 'Magento_LayeredNavigation':

Module 'Magento_Log':
Installing schema.. 

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':
Installing schema.. 

Module 'Magento_Multishipping':

Module 'Magento_Newsletter':
Installing schema.. 

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':
Installing schema.. 

Module 'Magento_PageCache':

Module 'Magento_Centinel':

Module 'Magento_Persistent':
Installing schema.. 

Module 'Magento_ProductAlert':
Installing schema.. 

Module 'Magento_Captcha':
Installing schema.. 

Module 'Magento_Reports':
Installing schema.. 

Module 'Magento_RequireJs':

Module 'Magento_Review':
Installing schema.. 

Module 'Magento_Rss':

Module 'Magento_CatalogWidget':

Module 'Magento_GoogleAdwords':

Module 'Magento_OfflineShipping':
Installing schema.. 

Module 'Magento_GiftMessage':
Installing schema.. 

Module 'Magento_CatalogSearch':
Installing schema.. 

Module 'Magento_Sendfriend':
Installing schema.. 

Module 'Magento_Shipping':

Module 'Magento_Sitemap':
Installing schema.. 

Module 'Magento_AdminNotification':
Installing schema.. 

Module 'Magento_Tax':
Installing schema.. 

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogUrlRewrite':
Installing schema.. 

Module 'Magento_Translation':
Installing schema.. 

Module 'Magento_Ui':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':
Installing schema.. 

Module 'Magento_Integration':
Installing schema.. 

Module 'Magento_Usps':

Module 'Magento_Variable':
Installing schema.. 

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_Weee':
Installing schema.. 

Module 'Magento_CurrencySymbol':

Module 'Magento_Wishlist':
Installing schema.. 

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Theme':

Module 'Magento_CacheInvalidate':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_CatalogImportExport':

Module 'Magento_Indexer':

Module 'Magento_Cms':

Module 'Magento_Search':

Module 'Magento_Catalog':

Module 'Magento_Rule':

Module 'Magento_CatalogInventory':

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Quote':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_Widget':

Module 'Magento_Bundle':

Module 'Magento_CustomerImportExport':

Module 'Magento_DesignEditor':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_SalesSequence':

Module 'Magento_Email':

Module 'Magento_Fedex':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':

Module 'Magento_GoogleShopping':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_ImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_User':

Module 'Magento_LayeredNavigation':

Module 'Magento_Log':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Multishipping':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Centinel':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_Captcha':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_Rss':

Module 'Magento_CatalogWidget':

Module 'Magento_GoogleAdwords':

Module 'Magento_OfflineShipping':

Module 'Magento_GiftMessage':

Module 'Magento_CatalogSearch':

Module 'Magento_Sendfriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_AdminNotification':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Translation':

Module 'Magento_Ui':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_Integration':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_Weee':

Module 'Magento_CurrencySymbol':

Module 'Magento_Wishlist':

Installing user configuration...

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_Directory':
Installing data.. 

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Theme':
Installing data.. 

Module 'Magento_CacheInvalidate':

Module 'Magento_Eav':
Installing data.. 

Module 'Magento_Customer':
Installing data.. 

Module 'Magento_CatalogImportExport':

Module 'Magento_Indexer':

Module 'Magento_Cms':
Installing data.. 

Module 'Magento_Search':

Module 'Magento_Catalog':
Installing data.. 

Module 'Magento_Rule':

Module 'Magento_CatalogInventory':
Installing data.. 

Module 'Magento_Payment':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Quote':
Installing data.. 

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':
Installing data.. 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':
Installing data.. 

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_Widget':
Installing data.. 

Module 'Magento_Bundle':
Installing data.. 

Module 'Magento_CustomerImportExport':

Module 'Magento_DesignEditor':

Module 'Magento_Developer':

Module 'Magento_Dhl':
Installing data.. 

Module 'Magento_Authorization':
Installing data.. 

Module 'Magento_Downloadable':
Installing data.. 

Module 'Magento_SalesSequence':
Installing data.. 

Module 'Magento_Email':

Module 'Magento_Fedex':
Installing data.. 

Module 'Magento_Sales':
Installing data.. 

Module 'Magento_Checkout':
Installing data.. 

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':

Module 'Magento_GoogleShopping':
Installing data.. 

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':
Installing data.. 

Module 'Magento_ImportExport':

Module 'Magento_CatalogRule':
Installing data.. 

Module 'Magento_User':

Module 'Magento_LayeredNavigation':

Module 'Magento_Log':
Installing data.. 

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':
Installing data.. 

Module 'Magento_Multishipping':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':
Installing data.. 

Module 'Magento_PageCache':

Module 'Magento_Centinel':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_Captcha':

Module 'Magento_Reports':
Installing data.. 

Module 'Magento_RequireJs':

Module 'Magento_Review':
Installing data.. 

Module 'Magento_Rss':

Module 'Magento_CatalogWidget':

Module 'Magento_GoogleAdwords':

Module 'Magento_OfflineShipping':

Module 'Magento_GiftMessage':
Installing data.. 

Module 'Magento_CatalogSearch':

Module 'Magento_Sendfriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_AdminNotification':

Module 'Magento_Tax':
Installing data.. 

Module 'Magento_TaxImportExport':

Module 'Magento_CatalogUrlRewrite':
Installing data.. 

Module 'Magento_Translation':

Module 'Magento_Ui':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_Integration':

Module 'Magento_Usps':
Installing data.. 

Module 'Magento_Variable':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_Weee':
Installing data.. 

Module 'Magento_CurrencySymbol':

Module 'Magento_Wishlist':

Installing admin user...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[view_files_fallback] => 1
[view_files_preprocessing] => 1
[collections] => 1
[db_ddl] => 1
[eav] => 1
[full_page] => 1
[translate] => 1
[config_integration] => 1
[config_integration_api] => 1
[config_webservice] => 1
)

Installing sample data:
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Area code is already set' in /usr/local/www/brg2tv5.cn/lib/internal/Magento/Framework/App/State.php:137
Stack trace:
#0 /usr/local/www/brg2tv5.cn/setup/src/Magento/Setup/Model/SampleData.php(66): Magento\Framework\App\State->setAreaCode('adminhtml')
#1 /usr/local/www/brg2tv5.cn/setup/src/Magento/Setup/Model/Installer.php(1123): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\WebLogger), 'pccom')
#2 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array)
#3 /usr/local/www/brg2tv5.cn/setup/src/Magento/Setup/Model/Installer.php(288): call_user_func_array(Array, Array)
#4 /usr/local/www/brg2tv5.cn/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#5 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /usr/local/www/brg2tv5.cn/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /usr/local/www/brg2tv5.cn/setup/index.php(26): Zend\Mvc\Application->run()
#16 {main}

 

 

 

 

 

 

root@mail:/usr/local/www/brg2tv5.cn/var/log # cat system.log
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []

**Comment by pccomfrank** [comment]
![image](https://cloud.githubusercontent.com/assets/4493796/7548459/4512c8a4-f5d7-11e4-9011-5c8e3bb27a00.png)

**Comment by pccomfrank** [comment]
![image](https://cloud.githubusercontent.com/assets/4493796/7548461/536f4b8e-f5d7-11e4-8aa8-89342e13c785.png)

**Comment by sivajik34** [comment]
once try : php -f dev/tools/Magento/Tools/View/deploy.php

**Comment by pccomfrank** [comment]
The two screen shots and the following log  are for the normal installation (no sample data), the first log is from the sample data installation.

root@mail:/usr/local/www/brg2tv5.cn/var/log # cat system.log
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-05-09 02:45:50] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []

**Comment by mazhalai** [comment]
@pccomfrank can you please try `bin/magento setup:uninstall` and try to install again?

**Comment by mariarti** [comment]
I have the same :+1: 
Installation is incomplete.
Check the console log for errors before trying again. 

Installing admin user...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[view_files_fallback] => 1
[view_files_preprocessing] => 1
[collections] => 1
[db_ddl] => 1
[eav] => 1
[full_page] => 1
[translate] => 1
[config_integration] => 1
[config_integration_api] => 1
[config_webservice] => 1
)


Installing sample data:
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Area code is already set' in /var/www/html/magento2/lib/internal/Magento/Framework/App/State.php:137
Stack trace:
#0 /var/www/html/magento2/setup/src/Magento/Setup/Model/SampleData.php(66): Magento\Framework\App\State->setAreaCode('adminhtml')
#1 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(1123): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\WebLogger), 'magento2')
#2 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array)
#3 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(288): call_user_func_array(Array, Array)
#4 /var/www/html/magento2/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#5 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/html/magento2/setup/index.php(26): Zend\Mvc\Application->run()
#16 {main}

I do it on fresh OS from scratch. Previous version (0.74.0-beta5) installation was without any issues.

**Comment by atrhacker** [comment]
this issue seems to be deeply linked with IIS webserver.
You 404 access to admin is simply a URL redirection issue, add http://url-of-magento/index.php/admin/ and you will see the admin logging page.
Do you have a IIS webserver ?
I'm encountering the same issue .

Basically after configuring composer etc.. the installations runs well. No error mentioned during the installation process etc..

However at the end when I try to access at the backend or the front store it display the page but no css or images files are loaded. When I looked in the missing ressources, basically I have 404 errors for all css & images files supposed to be located in the following folders

pub/static/frontend/*
pub/static/backend/*
Physically in my folder pub/static/ there is only the _requirejs folder and .htaccess file but no folder frontend and backend

I guess the folder frontend and backend are generated automatically because they are not by default in the initial clone of magento 2.0

So if anyone has got any ideas of where the problem could come from.

Additional information to consider: I have checked the permissions, the web server has full access (read and write) on every folders and file magento 2.0 root directory.

**Comment by Zatara7** [comment]
I was facing the same issue and I fixed it using the following: [I am using Ubuntu 14.04 and Apache 2.4.7]
After making sure I followed everything in detail here: http://devdocs.magento.com/guides/v2.0/install-gde/install/prepare-install.html
I had to go to my apache configuration (/etc/apache2/apache2.conf) and change this:
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride none
        Require all granted
</Directory>

To:

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

**Comment by xcomSteveJohnson** [comment]
We have a couple of things to help with this:

http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache.html#install-ubuntu-apache-rewrites

http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_no-styles.html

**Comment by piotrekkaminski** [comment]
@pccomfrank do you still have issue with it?

**Comment by aamnah** [comment]
@Zatara7 thank you! i was facing the same 404 issue and editing the virtual host file fixed it.

**Comment by boblaw** [comment]
@Zatara7 Thanks for your help.  For anyone installing Magento2 on Digital Ocean, this will be a big help.

**Comment by infoelliex** [comment]
Strange, the solution Bob (@Zatara7) doesn't work for me. I installed Magento2 twice at my digital ocean account w/o any errors but at the end I still got these not found problem? What else I can check? Thank you very much.  ~peter20201@gmail.com

**Comment by infoelliex** [comment]
Just contacted Digital Ocean about this issue, and they said they have built the Magento2 image on Ubuntu 14.4 here: 
https://www.digitalocean.com/community/tutorials/how-to-use-the-magento-one-click-install-image
~ peter

**Comment by girishyam** [comment]
Hi

I had the same issue. It got resolved once I activated rewrite_module on Apache.

Shyam
