### ISSUE TITLE
Using productRepository getList caches product without gallery images data

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#12500]
### Preconditions

1. Magento 2.2.x
2. PHP 7.0.14

### Steps to reproduce
1. Use code supplied in module 'ReachDigital_GetListIssue'.
[ReachDigital.zip](https://github.com/magento/magento2/files/1518274/ReachDigital.zip)
2. Add a configurable with visual swatch configured for the 'color' attribute. Add some simple products who have a media gallery and set visual swatch with option 'Update Product Preview Image' to Yes.
3. Go to the category page with the configurable and choose a swatch color.

### Expected result
1. I should see the media gallery image after choosing the visual swatch 

### Actual result
1. Error is shown and media gallery image is not updated.
<img width="1170" alt="getlist_issue" src="https://user-images.githubusercontent.com/17834386/33437386-0caa185c-d5e8-11e7-8475-7d042da887ef.png">

This happens because productRepository getList method is saving a cache version of the product without the media gallery information and a productRepository->getById() is being done to get the information for the gallery images.

**Comment by magento-engcom-team** [comment]
@PascalBrouwers, thank you for your report.
We've created internal ticket(s) MAGETWO-84857 to track progress on the issue.

**Comment by PascalBrouwers** [comment]
Updated the PR for 2.3-develop. Let's hope the tests will pass now.

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**
1. Use code supplied in module 'ReachDigital_GetListIssue'.
[ReachDigital.zip](https://github.com/magento/magento2/files/1518274/ReachDigital.zip)
2. Add a configurable with visual swatch configured for the 'color' attribute. Add some simple products who have a media gallery and set visual swatch with option 'Update Product Preview Image' to Yes.
3. Go to the category page with the configurable and choose a swatch color.

**Result**
The media gallery image is shown after choosing the visual swatch
![qqqqq](https://user-images.githubusercontent.com/51681435/71482594-25f8c380-280c-11ea-8bc3-37b97eb6013e.jpg)
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration
