### ISSUE TITLE
Cron job and memory error in magneto 2 

### ISSUE THREAD

**Issue by vamshikrushna** [magento/magento2#12505]
**Check Cron Scripts**
Cron script readiness check failed. Hide detail

Error from Updater Application Cron Script:

Found non-writable path(s):
/home/besthomeservices/public_html/var/.htaccess

For additional assistance, see cron scripts help.

**Check Component Dependency**
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information

[Composer\Downloader\TransportException] 
The "https://repo.magento.com/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0 
failed to open stream: no suitable wrapper could be found) 

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

For additional assistance, see component dependency help .

**PHP Settings Check ***
Your current PHP memory limit is 32M. Magento 2 requires it to be set to 756M or more. As a user with root privileges, edit your php.ini file to increase memory_limit. (The command php --ini tells you where it is located.) After that, restart your web server and try again.

For additional assistance, see PHP settings check help .

Please Help Out

**Comment by magento-engcom-team** [comment]
@vamshikrushna, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
