### ISSUE TITLE
[2.1.10] Mini-cart still shows items after checkout is complete.

### ISSUE THREAD

**Issue by aeu** [magento/magento2#12504]
After an order is placed and the user is presented the success page, the cart icon in the header still shows product count, and the minicart still has items in it.

This is has been reported here before, and has been marked as fixed, but I am still seeing this in 2.1.10.  (PHP 7, Centos 7, Apache, MariaDB).

This is reproducible 100% just by placing a test order.

![screen shot 2017-11-30 at 9 13 26 pm](https://user-images.githubusercontent.com/2225377/33465126-084259ba-d614-11e7-8089-4ed732d2bcbf.png)

**Comment by okorshenko** [comment]
Hi @aeu 
Please provide a link to the previous report and add detailed steps to reproduce and store configuration
Thank you

**Comment by aeu** [comment]
Hi @okorshenko 

Here's a few.  In the last link it was marked as fixed in 2.2.0 and 2.1.9 but I'm seeing it in 2.10.

2016 - https://github.com/magento/magento2/issues/4969
2016 - https://github.com/magento/magento2/pull/5807
Said that wasn't going to be in 2.1.8 - https://github.com/magento/magento2/pull/10050
Marked as merged - https://www.codacy.com/app/vrann/magento2/pullRequest?prid=733533
Marked as fixed - 2.2.0 and 2.1.9 - https://github.com/magento/magento2/issues/5621

To reproduce all you have to do is add a product to the cart, and step through normal checkout (I did pay by check).  Store config is M2 2.1.10 with the default Luma theme, running on CentOS 7.3 and PHP 7.

**Comment by d10nZ** [comment]
the bug is reproduced on 2.1.9
"detailed steps to reproduce" : just place order with PayPal Express (Sandbox mode is enough)
1. Login with existing Customer account;
2. Put any product into Shopping Cart;
3. Go to Checkout Page
....
4. choose PayPal ... enjoy the process

As a result: the success Page with not cleared Quote

![screenshot at 2017-12-02 02-12-06](https://user-images.githubusercontent.com/9153335/33505780-46f58d6a-d706-11e7-9285-72b62ba6c5c4.png)

**Comment by magento-engcom-team** [comment]
@aeu, thank you for your report.
We've created internal ticket(s) MAGETWO-84948 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@aeu, thank you for your report.
We've created internal ticket(s) MAGETWO-84948 to track progress on the issue.

**Comment by Styopchik** [comment]
reproduced on 2.2.1

**Comment by nitin-bc** [comment]
I am looking through this issue. #MM18IN

**Comment by magento-engcom-team** [comment]
@nitin-bc thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by nitin-bc** [comment]
I have checked the issue in 2.2 version. I can't reproduce this issue.

**Comment by simonmaass** [comment]
I am having the same issue in 2.2.3!

**Comment by ghost** [comment]
Online payments that were interrupted by error will have this behavior. The cart will keep the product. But after successful payment t5he cart is empty on 2.3.0
