### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Eav\Model\Entity\Attribute\Source\Config::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by sam110386** [magento/magento2#12503]
I am getting following error in mailchimp ecommerce module, while trying to run cron

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Eav\Model\Entity\Attribute\Source\Config::__construct() must be of the type array, null given, called in /var/develop/releases/20171130173131/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/develop/releases/20171130173131/app/code/Magento/Eav/Model/Entity/Attribute/Source/Config.php:26 Stack trace: #0 /var/develop/releases/20171130173131/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Eav\Model\Entity\Attribute\Source\Config->__construct(NULL) #1 /var/develop/releases/20171130173131/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Eav\\Mod...', Array) #2 /var/develop/releases/20171130173131/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Eav\\Mod...', Array) #3 /var/develop/releases/ in /var/develop/releases/20171130173131/app/code/Magento/Eav/Model/Entity/Attribute/Source/Config.php on line 26

![image](https://user-images.githubusercontent.com/16823364/33448386-ed775992-d62b-11e7-81a3-465a9f4b14a4.png)
Any help would be appreciated.
we are using Magento ver. 2.1.7

**Comment by okorshenko** [comment]
Please, provide detailed steps to reproduce. `simplecron.php` is not Magento endpoint

**Comment by sam110386** [comment]
okorshenko, i used this file just to hit the cron function of Ebizmarts\MailChimp\Cron\Ecommerce.php

**Comment by orlangur** [comment]
> I am getting following error in mailchimp ecommerce module, while trying to run cron

This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

**Comment by sam110386** [comment]
i fixed my issue after replacing following code in helper class Ebizmarts\MailChimp\Helper\Data.php at line # 297, 
```
try {
                 
           $options =$item->getSource()->getAllOptions();
                
                }
                catch(\Exception $e) {

                    $options = [];
                }
```

with 
```
try {
                  if($item->getFrontendInput()=='select'):
                    $options =$item->getSource()->getAllOptions();
                else:
                  $options = [];
                endif;
                }
                catch(\Exception $e) {

                    $options = [];
                }
```

**Comment by duckchip** [comment]
@sam110386  Could you make a pull request of your patch on https://github.com/mailchimp/mc-magento2 ?

Thx!
