### ISSUE TITLE
store view is disable in admin dashboard after theme installation

### ISSUE THREAD

**Issue by afnanm** [magento/magento2#12510]
Hello, 
After installation of theme, store view not appear on a product page in admin panel. I have two store view. I need a solution quickly, please. 
 Also, I don't know why the view of pages in dashboards as in the image. I must go down to see the content of the page and there is large space at the beginning of the page. 
I'm working on : 
Magento 2.1.9
PHP5.6 
you can see the image of a problem in this link: 
[https://magento.stackexchange.com/questions/203580/large-space-in-dashboard-of-magento-2-1-9](url)

is there a solution? any help? please. 

**Preconditions: Magento version**
1. Magento CE 2.1.9 without sample data is installed.
2. Porto theme installed

**Steps to reproduce**
1- downloade Magento CE 2.1.9.tar.bz2 from offical page: 
[https://magento.com/tech-resources/download](url)
2- create a folder in httpdocs called "site"; path as www.example.com/site
3- unzip from ssh 
4- install Magento 
5- upload files of a theme via FTP account by FILLZILLA
6- execute this command via SSH: /opt/plesk/php/5.6/bin/php bin/magento setup:upgrade 
7- execute this command via SSH: /opt/plesk/php/5.6/bin/php bin/magento setup:di:compile

**Actual and Expected result**
Expected result:
theme installed and admin dashboard working very well.
Actual result:
theme installed and store view bar in product page in admin dashboard is disable.

**Comment by magento-engcom-team** [comment]
@afnanm , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by afnanm** [comment]
@magento-engcom-team update is done

**Comment by magento-engcom-team** [comment]
@afnanm ,  thanks for your update. Please check this problem on clean installation of Magento.

**Comment by afnanm** [comment]
@magento-engcom-team how ?

**Comment by magento-engcom-team** [comment]
@afnanm , check this issue on blank or luma theme.

**Comment by afnanm** [comment]
@magento-engcom-team still i have this problem

**Comment by magento-engcom-team** [comment]
@afnanm , Please check this issue on vanilla installation without any extension, thanks.

**Comment by afnanm** [comment]
@magento-engcom-team  I install Magento in the main folder of httpdocs and in a sub folder. this problem only in sub folder which happen after theme installation

**Comment by magento-engcom-team** [comment]
@afnanm ,thanks for response. Please add more steps to reproduce for install M2 in subfolder and your paths.

**Comment by afnanm** [comment]
@magento-engcom-team I add steps to install Magento on subfolder.

**Comment by magento-engcom-team** [comment]
@afnanm , thank for update. We were not able to reproduce this issue on default Luma theme. Are you use Plesk web hosting?

**Comment by afnanm** [comment]
@magento-engcom-team yes

**Comment by magento-engcom-team** [comment]
@afnanm , thank for your response. We can not reproduce with regular console. We think this is problem with you Plesk console. Please contact Plesk vendor for support.
Thank you

**Comment by afnanm** [comment]
Php 5.6 and php7 are installed in the server. Is that cause this problem? And is there any way to add content of products for another store view?

**Comment by afnanm** [comment]
@magento-engcom-team i add some update.

**Comment by magento-engcom-team** [comment]
@afnanm , thank for update.
We don't think for problem with php, this not first problem with Plesk for we seen.
See devdocs
http://devdocs.magento.com/guides/v2.1/config-guide/multi-site/ms_websites.html

**Comment by afnanm** [comment]
@magento-engcom-team is there any solution to switch between languages for add contents and customize each site?

**Comment by magento-engcom-team** [comment]
@afnanm ,  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by afnanm** [comment]
@magento-engcom-team can I know why you refer this problem to Plesk consol? and as you see I add it to the Magento Stack Exchange site for advice or general discussion about this issue but no answers or advice.  I think this problem related to Magento Core technical issues.
