### ISSUE TITLE
Backend - Admin panel fatal Error - Only variables can be passed by reference in public_html/vendor/magento/module-backend/view/adminhtml/templates/system/search.phtml on line 43

### ISSUE THREAD

**Issue by RKBerkowits** [magento/magento2#12511]
Magento version - 2.1.7 PHP Version 7.0 

On ligin igf backend giving the error - Only variables can be passed by reference in /public_html/vendor/magento/module-backend/view/adminhtml/templates/system/search.phtml on line 43

After googling I found that asp_tag is causing the error but didnt know how to solve this

Please anyone know kindly help me.

**Comment by magento-engcom-team** [comment]
Hello @RKBerkowits. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
