### ISSUE TITLE
Impossible to set source model when create new attribute

### ISSUE THREAD

**Issue by OleksiiStepanov** [magento/magento2#12514]
Resource model always saves default source model independet of attribute data.
Thats why impossible to set source model when create new attribute.     

https://github.com/magento/magento2/blob/82caf48db2498d07f0f6c1ebee2ea134fbb8a79f/app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute.php#L184

## Preconditions
Magento 2.4-develop without sample data is installed.

## Steps to reproduce
Programaticly create attribute with frontend type select and custom source model via Magento\Catalog\Api\ProductAttributeRepositoryInterface::save()

## Actual result
Attribute created with default source model  \Magento\Eav\Model\Entity\Attribute\Source\Table

## Expected result
Attribute created with custom source model.

**Comment by magento-engcom-team** [comment]
@OleksiiStepanov, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by OleksiiStepanov** [comment]
update issue

**Comment by magento-engcom-team** [comment]
@OleksiiStepanov, thank you for your report.
We've created internal ticket(s) MAGETWO-84954 to track progress on the issue.

**Comment by OleksiiStepanov** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@OleksiiStepanov thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by leoquijano** [comment]
Hello @magento-engcom-team,

I also ran into this issue. I see that a fix for this issue has been applied to the ```2.2-develop``` line, but it doesn't seem to be applied to any specific release. I'm using ```2.2.6```, and the issue is present in the ```Magento\Catalog\Model\Product\Attribute\Repository``` class.

Are there plans to apply the commit 3d5d4b2aadf0141288162d88ff14b794afcc9abd to a future release?

Thanks.

**Comment by Ctucker9233** [comment]
@magento-engcom-team this fix still isn't merged into 2.2 as of version 2.2.7. When can we see it released?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30221` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
