### ISSUE TITLE
Incorrect currency format when using comma instead of dot

### ISSUE THREAD

**Issue by tonytrinh206** [magento/magento2#12527]
I am using comma to replace dot for decimal number on Magento 2.2.1
Everything is display correctly except to cart summary. However, it charges a correct amount at the checkout page. 

**Preconditions**
1. Magento 2.2.1
2. Store locale: Vietnam

**Steps to reproduce**
1. Adding a product to basket.
2. Go to My Cart page.

**Update** 1. Setup the default store with Australia locale by following this tutorial https://www.fontis.com.au/blog/how-to-set-up-a-magento2-store-for-australia
2. Add a second store view with Vietnam locale
3. Add products to store with AUD currency
5. Go to the frontend
6. Add products to cart and go to my cart page
7. Switch between 2 stores, the price in Vietnam will display incorrect decimal number

**Expected result**
The cart summary on the right needs to have the same currency format with product lines on the left. For example, $4,00

![screen shot 2017-12-03 at 10 49 45 pm](https://user-images.githubusercontent.com/2638148/33525141-af40199e-d87d-11e7-92d2-fc56f38cb07f.png)

**Actual result**
The cart displays summary without decimal numbers. 

![screen shot 2017-12-03 at 10 49 45 pm](https://user-images.githubusercontent.com/2638148/33525107-d170ad22-d87c-11e7-99b3-24e14bf96b6a.png)

**Comment by magento-engcom-team** [comment]
@tonytrinh206 thank you fro report
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce, especially the method you applied to change decimal symbol.

**Comment by tonytrinh206** [comment]
@magento-engcom-team 
1. Setup the default store with Australia locale by following this tutorial https://www.fontis.com.au/blog/how-to-set-up-a-magento2-store-for-australia
2. Add a second store view with Vietnam locale
3. Add products to store with AUD currency
5. Go to the frontend
6. Add products to cart and go to my cart page
7. Switch between 2 stores, the price in Vietnam will display incorrect decimal number

**Comment by tonytrinh206** [comment]
Hi @magento-engcom-team, I have tested it on 2.2.2 version and I get the same error. Could you please check?

1. Install Mangeto 2.2.1 or 2.2.2. Select Australia as Locale during the installation
2. Go to Store>Configuration>General change Default Country and Store Locale to Australia  
2. Add a new product in Australia currency
3. Create a new store and go to Store>Configuration>General change Default Country and Store Locale to Vietnam 
4. Config Tax for Australia

![screen shot 2017-12-19 at 12 34 29 am](https://user-images.githubusercontent.com/2638148/34108524-807e4bca-e454-11e7-8837-19d2344ef1c9.png)
![screen shot 2017-12-19 at 12 34 44 am](https://user-images.githubusercontent.com/2638148/34108528-828ef4b4-e454-11e7-9835-f6b9fbbe1a08.png)
![screen shot 2017-12-19 at 12 34 54 am](https://user-images.githubusercontent.com/2638148/34108532-840947e0-e454-11e7-8db7-4c96824724ec.png)

5. Go to the frontend, product page 
6. Switch between 2 stores
7. You will see the price decimal will be displayed correctly for a few seconds before switching into a wrong format. I think the problem coming from javascript file. 

Hope it helps, thank you.

**Comment by magento-engcom-team** [comment]
@tonytrinh206, thank you for your report.
We've created internal ticket(s) MAGETWO-86040 to track progress on the issue.

**Comment by jimmyhien** [comment]
https://github.com/magento/magento2/commit/fdac295cf29274d3dc663d93dcf0351a55fed92b#diff-cac395502ccc58a463d735c0fbff7cdd
Please take a look at these changes. I think it's the reason for this bug.

**Comment by tonytrinh206** [comment]
Thanks @jimmyhien, I have fixed the issue by changing the getPriceFormat function in lib/internal/Magento/Framework/Locale/Format.php file to

```
 public function getPriceFormat($localeCode = null, $currencyCode = null)
    {
        $localeCode = $localeCode ?: $this->_localeResolver->getLocale();
        if ($currencyCode) {
            $currency = $this->currencyFactory->create()->load($currencyCode);
        } else {
            $currency = $this->_scopeResolver->getScope()->getCurrentCurrency();
        }

        $formatter = new \NumberFormatter($localeCode, \NumberFormatter::CURRENCY);
        $format = $formatter->getPattern();
        $decimalSymbol = $formatter->getSymbol(\NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
        $groupSymbol = $formatter->getSymbol(\NumberFormatter::GROUPING_SEPARATOR_SYMBOL);
        $pos = strpos($format, ';');
        if ($pos !== false) {
            $format = substr($format, 0, $pos);
        }
        $format = preg_replace("/[^0\#\.,]/", '', $format);
        $totalPrecision = 0;
        $decimalPoint = strpos($format, $decimalSymbol);
        if ($decimalPoint !== false) {
            $totalPrecision = strlen($format) - (strrpos($format, $decimalSymbol) + 1);
        } else {
            $decimalPoint = strlen($format);
        }
        $requiredPrecision = $totalPrecision;
        $t = substr($format, $decimalPoint);
        $pos = strpos($t, '#');
        if ($pos !== false) {
            $requiredPrecision = strlen($t) - $pos - $totalPrecision;
        }

        if (strrpos($format, $groupSymbol) !== false) {
            $group = $decimalPoint - strrpos($format, $groupSymbol) - 1;
        } else {
            $group = strrpos($format, $decimalPoint);
        }
        $integerRequired = strpos($format, $decimalPoint) - strpos($format, '0');

        $result = [
            //TODO: change interface
            'pattern' => $currency->getOutputFormat(),
            'precision' => $totalPrecision,
            'requiredPrecision' => $requiredPrecision,
            'decimalSymbol' => $decimalSymbol,
            'groupSymbol' => $groupSymbol,
            'groupLength' => $group,
            'integerRequired' => $integerRequired,
        ];
        return $result;
    }
```

**Comment by mamunur34** [comment]
I could not find 
lib/internal/Magento/Framework/Locale/Format.php
file  in magento 2.2.0

**Comment by jimmyhien** [comment]
@mamunur34 You can find it in vendor/magento/framework folder.

**Comment by sohrobraja** [comment]
Hi @jimmyhien and @tonytrinh206 ,

I tried your edit for the getPriceFormat issue, however, I am still getting my prices on the cart/checkout summary sidebar formatted like so: $0,007 (instead of $7.00). I have a Japanese store and facing the same issue.

Did you do anything else to resolve this issue?

**Comment by pieal86** [comment]
same issue.. with multiple store. 
Product page also in cart page price getting divided by 100.
Any Proper Solution?

**Comment by mamunur34** [comment]
yes, I got my issue solved. I will share you. But will take some time. Now very busy with some social events here. I might do it Monday. would you please touch me on Monday? I can help you until you get the solution. 
@pieal86  @sohrobraja

**Comment by tonytrinh206** [comment]
@sohrobraja & @pieal86, 

I have changed Magento source code to solve the problem. 
Open file in vendor/magento/framework/Locale/Format.php

Line 93: You will see this function 

```
    public function getPriceFormat($localeCode = null, $currencyCode = null)
    {
        $localeCode = $localeCode ?: $this->_localeResolver->getLocale();
        if ($currencyCode) {
            $currency = $this->currencyFactory->create()->load($currencyCode);
        } else {
            $currency = $this->_scopeResolver->getScope()->getCurrentCurrency();
        }

        $formatter = new \NumberFormatter($localeCode, \NumberFormatter::CURRENCY);
        $format = $formatter->getPattern();

        /** HERE IS MY CODE ***/
        if($localeCode == "vi_VN")
            $format = "¤#.##0,00";
         /*** END CODE ***/

        $decimalSymbol = $formatter->getSymbol(\NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
        $groupSymbol = $formatter->getSymbol(\NumberFormatter::GROUPING_SEPARATOR_SYMBOL);

```
Basically, if the locale code = VN then just replace the dot with comma. 
@sohrobraja, you localeCode should be ja_JP, so you code should be 

```
 if($localeCode == "ja_JP")
            $format = "¤#.##0,00";
```

Remember to clear cache after edit the file.

**Comment by bbacika** [comment]
Dear All,
Need some help in similar topic. (sorry if isn't correct topic)
On my product page when  prices are 3 digits then one 0 appear as first digit. (with 4 digits works nice).

On admin site prices is without dot or comma, on all product page the same is correct with 3 digits.

Magento 2.2.5
single store en_Us, only prices are in local corrency (HUF -Ft)
Price on product page displayed correctly for a few seconds before switching into a wrong format

Thanks is advance

![allproduct_page](https://user-images.githubusercontent.com/44999695/48411630-5c779a00-e742-11e8-8670-f5be7056ab0b.png)
![product page_bad](https://user-images.githubusercontent.com/44999695/48411639-600b2100-e742-11e8-9124-c123aca38999.png)

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**
 1. Setup the default store with Australia locale by following this tutorial https://www.fontis.com.au/blog/how-to-set-up-a-magento2-store-for-australia
2. Add a second store view with Vietnam locale
3. Add products to store with AUD currency
5. Go to the frontend
6. Add products to cart and go to my cart page
7. Switch between 2 stores

**Result**
The cart summary on the right needs to have the same currency format with product lines on the left. 
![Selection_001](https://user-images.githubusercontent.com/51681435/71477871-1752e200-27f5-11ea-835a-66a4e01f7218.png)
More [info](https://github.com/magento-engcom/magento2ce/pull/1160#issuecomment-384699487).
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration

**Comment by blowfish-ltd** [comment]
this is not an issue with Magento , if you would like to use locales other than english and the price format is not as expected the you have to specify your format based on locale code.

file path vendor/magento/framework/Locale/Format.php
near the line 126 

        $decimalSymbol = $formatter->getSymbol(\NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
        $groupSymbol = $formatter->getSymbol(\NumberFormatter::GROUPING_SEPARATOR_SYMBOL);
          
      // custom code add here start
  if($localeCode == "ar_SA") {
          $decimalSymbol = '.';
          $groupSymbol = ',';
        }
    // custom code end here

i'am adding the locale price fix for Arabic language

price on product page before adding fix -
 ر.س.‏1٬111٫78

price after adding fix
ر.س.‏1,111.78


which ever locale you are using add the locale code in if condition and add your decimal value , it will work
