### ISSUE TITLE
Area code is already set 

### ISSUE THREAD

**Issue by milanstojanov** [magento/magento2#1252]
Hello!

While trying to install Magento 2 from the command line with the latest sample data (0.74.0-beta7), I got the following exception:

[Magento\Framework\Exception\LocalizedException]  
Area code is already set

This is happening at the end:

[Progress: 269 / 272]

**Comment by pierrefay** [comment]
same problem for me :

root@6ab132ba06fc:/var/www/magento2# php dev/tools/Magento/Tools/SampleData/install.php --admin_username=admin
exception 'Magento\Framework\Exception\LocalizedException' with message 'Area code is not set' in /var/www/magento2/lib/internal/Magento/Framework/App/State.php:154
Stack trace:
#0 /var/www/magento2/lib/internal/Magento/Framework/Session/SessionManager.php(173): Magento\Framework\App\State->getAreaCode()
#1 /var/www/magento2/lib/internal/Magento/Framework/Session/SessionManager.php(130): Magento\Framework\Session\SessionManager->start()
#2 /var/www/magento2/app/code/Magento/Backend/Model/Auth/Session.php(98): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))
#3 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(148): Magento\Backend\Model\Auth\Session->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State), Object(Magento\Framework\Acl\Builder\Proxy), Object(Magento\Backend\Model\Url), Object(Magento\Backend\App\Config))
#4 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Backend...', Array)
#5 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Backend...')
#6 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Backend...')
#7 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Backend...', NULL, 'session', 'Magento\Tools\S...')
#8 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Tools\S...', Array, Array)
#9 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Tools\S...')
#10 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Tools\S...')
#11 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Tools\S...', NULL, 'installer', 'Magento\Tools\S...')
#12 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Tools\S...', Array, Array)
#13 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Tools\S...', Array)
#14 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(220): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Tools\S...', Array)
#15 /var/www/magento2/dev/tools/Magento/Tools/SampleData/install.php(29): Magento\Framework\App\Bootstrap->createApplication('Magento\Tools\S...', Array)
#16 {main}

Next exception 'Magento\Framework\Exception\SessionException' with message 'Area code not set: Area code must be set before starting a session.' in /var/www/magento2/lib/internal/Magento/Framework/Session/SessionManager.php:175
Stack trace:
#0 /var/www/magento2/lib/internal/Magento/Framework/Session/SessionManager.php(130): Magento\Framework\Session\SessionManager->start()
#1 /var/www/magento2/app/code/Magento/Backend/Model/Auth/Session.php(98): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))
#2 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(148): Magento\Backend\Model\Auth\Session->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State), Object(Magento\Framework\Acl\Builder\Proxy), Object(Magento\Backend\Model\Url), Object(Magento\Backend\App\Config))
#3 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Backend...', Array)
#4 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Backend...')
#5 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Backend...')
#6 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Backend...', NULL, 'session', 'Magento\Tools\S...')
#7 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Tools\S...', Array, Array)
#8 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Tools\S...')
#9 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Tools\S...')
#10 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Tools\S...', NULL, 'installer', 'Magento\Tools\S...')
#11 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Tools\S...', Array, Array)
#12 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Tools\S...', Array)
#13 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(220): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Tools\S...', Array)
#14 /var/www/magento2/dev/tools/Magento/Tools/SampleData/install.php(29): Magento\Framework\App\Bootstrap->createApplication('Magento\Tools\S...', Array)
#15 {main}

**Comment by skukla** [comment]
Same for me.

**Comment by kokoc** [comment]
Thank you for reporting the issue. Internal reference: MAGETWO-37249

**Comment by pierrefay** [comment]
Thanks for the time passed on this issue. Which version should be installed to make the sample data works with the actual last magento2 version waiting the fix ?

**Comment by pierrefay** [comment]
@milanstojanov @kokoc my bad.

It works if you use :
/var/www/magento2/bin magento setup:upgrade
/var/www/magento2/bin magento sampledata:install admin

Instead of :
php dev/tools/Magento/Tools/SampleData/install.php --admin_username=admin

as written here, in the doc :
http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html#instgde-install-sample-enable-after

Thanks @MagentoDevDocs for the reply to @benmarks about the subject.

Pierre.

**Comment by kokoc** [comment]
@milanstojanov this issue is fixed in latest Magento version. Could you please verify it?

**Comment by milanstojanov** [comment]
Great, checking now...

It's on 70% almost half an hour - installing data for Magento_Catalog. I'll provide another update shortly.

**Comment by milanstojanov** [comment]
Hi again, unfortunately - I cannot confirm it's fixed. 

First, I should have immediately checked Apache logs - the error from above was triggered by:

```
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/magento2/lib/internal/Magento/Framework/Filesystem/Directory/Read.php on line 153, referer: http://mage2.dev/setup/
```

When I increased the value, it passed 70% but it threw an exception at 98%:

Installing customers:

```
[ERROR] exception 'Magento\Setup\SampleDataException' with message 'Error during sample data installation: Warning: fopen(): Filename cannot be empty in /var/www/magento2/app/code/Magento/SampleData/Helper/Csv/Reader.php on line 64' in /var/www/magento2/setup/src/Magento/Setup/Model/Installer.php:1117
Stack trace:
#0 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array)
#1 /var/www/magento2/setup/src/Magento/Setup/Model/Installer.php(298): call_user_func_array(Array, Array)
#2 /var/www/magento2/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#3 /var/www/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#4 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 /var/www/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 /var/www/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /var/www/magento2/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/magento2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#14 {main}
```

I haven't tried without installing sample data.

**Comment by piotrekkaminski** [comment]
@milanstojanov do you still have issues with it?
