### ISSUE TITLE
Layered Navigation failed to fetch Product Category

### ISSUE THREAD

**Issue by rishabhchd19** [magento/magento2#12525]
### Preconditions

1. Magento CE 2.2.1, Php 7.0x

### Steps to reproduce

1. Create 3 newly fresh 'Parent-Sub' Categories Under 'Default Category(Root)'.
2. Those 3  Parent subcategories will have further Sub Categories. 
3. Now populated each Parent Subcategories until 31x products. One of the Parent Sub Category will not be shown under Layered Navigation. But the missing Parent- Sub category is showing in MENU and nodes in SubMenu properly. 
4.Use Flat Catalog Category- NO ; Use Flat Catalog Product- NO.

### Expected result

1. On adding the products more than 300+ in Default Category>Parent-Sub Category>>Subcategory, all the Parent-Sub categories must be fetched and shown in Layered Navigation. By Alphabetical Category is missing in Layered Navigation but previously it was displaying when products were 299 added to it.

### Actual result

[Screenshot, logs]
![2017-12-03_1-05-28](https://user-images.githubusercontent.com/30948461/33519221-9be641da-d7c8-11e7-8eec-f38e7cc5b3d9.jpg)
![2017-12-03_1-04-05](https://user-images.githubusercontent.com/30948461/33519222-9c17b062-d7c8-11e7-88bd-74801042b68a.jpg)
![2017-12-03_1-02-59](https://user-images.githubusercontent.com/30948461/33519223-9c478e18-d7c8-11e7-9341-b6ab74640522.jpg)

**Comment by magento-engcom-team** [comment]
@rishabhchd19 hank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by rishabhchd19** [comment]
Hi. The website is [catalogue.yogdiagnostics.com](url) and here you can see that the Menu has 3 categories but the front page Layered Navigation fetching only 2. 
On Homepage, in Design>>Custom layout Update XML:
1. Attachment
[Homepage.txt](https://github.com/magento/magento2/files/1543503/Homepage.txt)

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
