### ISSUE TITLE
Magento 2 When we are try to update the custom attribute for the product then the default store price updated to other store

### ISSUE THREAD

**Issue by openwavecomputing** [magento/magento2#12536]
When we are try to update the custom attribute for the product then the default store price updated to other stores for the same products. 
We are working with pro-grammatically bulk product uploads. We are processing the data from CSV file. here we are working with single web site and multiple store view. eg: IND, USD.... etc. Our csv file keeps different price for different store view and this is done good. After that we are try to update a custom attribute value for all products with updated information. After couple of hours we noticed that default store price is automatically updated to others stores for all processed products. 
We also tested this with multiple times and it is repeating / reproducing each time. 

I'm not sure.
- This is happen only when we are try to update only custom attribute value.
- This is not happen when we are try to update custom attribute value as well as all store price.

### Preconditions

Magento 2
Some Products created
Config: Catalog > Price > Catalog Price Scope = "Website"

### Steps to reproduce
Please use below code to reproduce this.

public function updateProductStock($productId,$rawdata){
	try{
	$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
	$objectManager = $bootstrap->getObjectManager();
	$state = $objectManager->get('Magento\Framework\App\State');
	$state->setAreaCode('frontend');
	$_product = $this->_product->load($productId);
	$WebsiteIds	=	"";
	if($rawdata[18] !=""){ $WebsiteIds[]	=	12; }
	if($rawdata[19] !=""){ $WebsiteIds[]	=	13; }
	if($rawdata[20] !=""){ $WebsiteIds[]	=	1; }
	if($rawdata[21] !=""){ $WebsiteIds[]	=	14; }
	$WebsiteId[]	=	1;
	$_product->setWebsiteIds($WebsiteId);
	if($_product->save()){
			$productsizings	=	$rawdata[31];
			if($productsizings == 1){
				$productsizings		=	'one size';
			}
			if(in_array(strtolower($productsizings),$aproduct_sizing)){
				$aproduct_sizing_key	= array_search(strtolower($productsizings),$aproduct_sizing);
			}
			if(in_array(12,$WebsiteIds)){
				$objectManager->create('Magento\Catalog\Model\Product')
					->load($_product->getId())
					->setStoreId(12)
					->setProductSizing($aproduct_sizing_key)
					->save();
			}
			if(in_array(13,$WebsiteIds)){
			$objectManager->create('Magento\Catalog\Model\Product')
				->load($_product->getId())
				->setStoreId(13)
				->setProductSizing($aproduct_sizing_key)
				->save();
			}
			if(in_array(1,$WebsiteIds)){
			$objectManager->create('Magento\Catalog\Model\Product')
				->load($_product->getId())
				->setStoreId(1)
				->setProductSizing($aproduct_sizing_key)
				->save();
			}
			if(in_array(14,$WebsiteIds)){
			$objectManager->create('Magento\Catalog\Model\Product')
				->load($_product->getId())
				->setStoreId(14)
				->setProductSizing($aproduct_sizing_key)
				->save();
			}
			date_default_timezone_set("Asia/Kuala_Lumpur");
			$logger->info('product "'.$_product->getSku().'" updated successfully');
		}
		date_default_timezone_set("Asia/Kuala_Lumpur");
		$logger->info('product "'.$rawdata[39].'" updated successfully');
		// exit;
	}catch (\Exception $e) {
		$ologger->info($e->getMessage());
	}
}

### Expected result
This should update only mentioned attribute value not price

### Actual result
This will updating mentioned attribute value and also merging default store price to all store instead of different store price

Please try to give update on this asap..

Thanks

**Comment by openwavecomputing** [comment]
Hello Magento Team,

I found very simple code to re produce this issue.
Please try this with below code

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->create('Magento\Catalog\Model\Product')->load(// Some Product Id //);
$_product->setStatus(\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_DISABLED);
$_product->setStoreId(// Some Store ID //);
$_product->save();

Note:
Before run this make sure your magento have single web site and multiple store view.

**Comment by magento-engcom-team** [comment]
The issue can be reproduced only with config Catalog Price Scope = "Website"

**Comment by magento-engcom-team** [comment]
@openwavecomputing, thank you for your report.
We've created internal ticket(s) MAGETWO-85101 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@openwavecomputing, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
