### ISSUE TITLE
Restrict to store or website

### ISSUE THREAD

**Issue by Perfect-Web** [magento/magento2#1254]
Hey guys, can anyone tell me how can i restrict a user to only see certain stores/websites on admin ?

Thanks

**Comment by muasir** [comment]
Have you tried using the Magento1 way of doing it?  It should be similar

http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#store-operations/permissions-role-custom.html?Highlight=restrict admin

**Comment by Perfect-Web** [comment]
yes, but there is no way to restrict per store/website use ... or am i wrong ?

**Comment by kandy** [comment]
This is EE functionality

**Comment by ilol** [comment]
@Perfect-Web, could I close the ticket? Seems you got an answer. 
Thank you for your participation!

**Comment by Perfect-Web** [comment]
yes, thank you
