### ISSUE TITLE
500 error when selecting cache management page .

### ISSUE THREAD

**Issue by Scott4949** [magento/magento2#12542]
### Preconditions

1. 
2. Magento 2

### Steps to reproduce

1. login into Magento Admin
2. Select Systems 
3. Click "Cache Management

### Expected result

1. Cache Management Page should display

### Actual result

1. [Screenshot, logs]
 Unable to open the "cache management page". The link in the admin goes to a 500 error page.

**Comment by okorshenko** [comment]
Thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by jakwinkler** [comment]
You should check your remote server / local server for error logs. 500 is a server error, it might not be Magento 2 related at all.

**Comment by magento-engcom-team** [comment]
@Scott4949 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
See screenshot
![cache_management-iloveimg-cropped](https://user-images.githubusercontent.com/31669971/33597684-e1a3d4d0-d9a8-11e7-8f43-2c17cbf7906d.png)

**Comment by magento-engcom-team** [comment]
@Scott4949
When facing a 500 error the first thing you should do is search for your webserver error log. When running on apache it can mostly be found in one of these 2 locations:
/var/log/httpd/ -> centos, archlinux ...
/var/log/apache2/ -> debian, ubuntu ...

**Comment by magento-engcom-team** [comment]
@Scott4949, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
