### ISSUE TITLE
'Place Order' Button is not clickable at  Paypal Order Review Page Magento 2.2.1

### ISSUE THREAD

**Issue by digvijay2017** [magento/magento2#12546]
### Preconditions

1.  Install Magento 2.2.1 in  with php 7.0.2
2.  Using Paypal Express checkout payment method in test mode.

### Steps to reproduce

1.  Add item in the cart.
2.  Go to the checkout page.
3.  Add shipping, billing information and select the shipping method.
4. Now, select the Payment method : Paypal Express Checkout.
5. Now, You will be redirected to the Paypal website, Enter the paypal test login credentials and make the payment.
6. Now, you will redirect to your website at the Paypal order review page. 
7. Now, you see Place Order button, which is not clickable.

### Expected result

1.  Place Order button should be clickable and order will be placed. 

### Actual result

1. Place Order button is not working and new order is not creating.
![paypal](https://user-images.githubusercontent.com/30342958/33599172-5283a168-d9cb-11e7-8ab1-4b9503041f91.png)

**Comment by magento-engcom-team** [comment]
@digvijay2017 thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by digvijay2017** [comment]
@magento-engcom-team 

I have changed the theme and checked again the issue, then this issue did not occurs. I think, there is some problem in theme, so i am closing this issue.
