### ISSUE TITLE
Naming collision in Javascript ui registry (backend)

### ISSUE THREAD

**Issue by EliasZ** [magento/magento2#12555]
### Preconditions
Magento 2.2.1

### Steps to reproduce
Add a configurable attribute with attribute code set as "content", or any other name which exists as identifier on the product edit page (for example, "gallery", "review" ,"related").

Add it to the default attribute set

Edit a product.

### Expected result
1. You can properly edit/save the product and add configurations setting that attribute.

### Actual result
1. All kinds of Javascript issues arise when trying to save the product

This is because somehow most HTML elements end up in a registry and are then retrieved on various places. For example:

[Magento/ConfigurableProduct/view/adminhtml/web/js/variations/variations.js:365](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/variations/variations.js#L365)

So when using the name "content" for an attribute, instead of the "content" attribute input, it retrieves the "content" fieldset on the product edit page. This gives a variety of javascript errors such as `Element.disabled is not a function`.

Could not find where exactly the uiRegistry is filled, but wherever it is the names are not unique enough.

See for example someone else who encountered this problem: [Magento 2 - “Element.disabled is not a function” Attribute Error](https://magento.stackexchange.com/questions/202741/magento-2-element-disabled-is-not-a-function-attribute-error)

**Comment by magento-engcom-team** [comment]
@EliasZ, thank you for your report.
We've created internal ticket(s) MAGETWO-85179 to track progress on the issue.

**Comment by VladimirZaets** [comment]
@EliasZ Hi, the fix for this issue will be delivered to Magento 2.3 version. You can look the commit with a fix in PR https://github.com/magento/magento2/pull/12943.

**Comment by magento-team** [comment]
Hi @EliasZ. Thank you for your report. 
The issue has been fixed in magento/magento2#12945 by @VladimirZaets in 2.2-develop branch
Related commit(s):
 - 64a16891c6b8f3fb53b3fba448c13da62e8bcaa6

The fix will be available with the upcoming patch release.

**Comment by magento-team** [comment]
Hi @EliasZ. Thank you for your report. 
The issue has been fixed in magento/magento2#12943 by @VladimirZaets in 2.3-develop branch
Related commit(s):
 - 8580f45413bd417683558ea8bee93cac57e4740a

The fix will be available with the upcoming patch release.

**Comment by peterjaap** [comment]
Addition; this also happens for attribute named 'design'.

**Comment by templatetuners** [comment]
> Addition; this also happens for attribute named 'design'.

@peterjaap how did you fix this? I have created path to `app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/variations/` and copied the latest `variations.js` there, but still same problem.
