### ISSUE TITLE
"multiplewishlist" section source is not supported

### ISSUE THREAD

**Issue by ahmadalfy** [magento/magento2#12559]
I installed a brand new version of community edition, created a new blank theme not based on anything, open the homepage I get the following error: 

![image](https://user-images.githubusercontent.com/87611/33658909-0ff62bc4-da87-11e7-97e0-363468e47097.png)

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

The URL requested

```
http://localhost:8081/customer/section/load/?sections=cart%2Cdirectory-data%2Ccustomer%2Ccompare-products%2Clast-ordered-items%2Cwishlist%2Cmultiplewishlist%2Cpaypal-billing-agreement%2Cpslogin%2Creview%2Crecently_viewed_product%2Crecently_compared_product%2Cproduct_data_storage&update_section_id=false&_=1512558388805
```

### Preconditions
1. Magento ver 2.2.1
2. PHP ver 7.0

### Steps to reproduce

1. Installed a brand new version of community edition
2. Create a blank theme with no parent, use the content of `etc/view.xml` from the blank theme.
3. Open the homepage and check the console

**Comment by ahmadalfy** [comment]
Possible related issue
https://github.com/magento/magento2/issues/10660

**Comment by magento-engcom-team** [comment]
@ahmadalfy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please add more details to your description of the steps you followed when identifying this issue. Specify the exact steps you used, the expected result of your actions, and the actual results. Try making some local alias like `magento.dev `or `something.com`.

**Comment by southerncomputer** [comment]
multiple-wishlist is EE product unless you are using 3rd party multiple-wishlist add-on?

**Comment by ahmadalfy** [comment]
@southerncomputer I downloaded the community edition from the website and I didn't install any third party addons. This is just a start of a vanilla CE

**Comment by magento-engcom-team** [comment]
@ahmadalfy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
