### ISSUE TITLE
shipping address & billing address missing in print order

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1255]
I created account & ordered 1 item .then if i click print order in order view its not displaying shipping and billing address.
ver. 0.74.0-beta8

**Comment by sivaschenko** [comment]
Thank you for the report. Internal ticket: MAGETWO-37376

**Comment by vpelipenko** [comment]
@sivajik34, this issue is fixed and pushed to public repository. Please, check it.

**Comment by sivajik34** [comment]
thank you
