### ISSUE TITLE
Can't log in web setup wizard.

### ISSUE THREAD

**Issue by mieplazma** [magento/magento2#12554]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

![70](https://user-images.githubusercontent.com/32664867/33649230-da11b6c0-da7e-11e7-80e2-73e30c3000e3.JPG)

**Comment by magento-engcom-team** [comment]
@mieplazma , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
Also @mieplazma, please try to enter Your website url in another browser, f.e in Internet Explorer (not in the Edge) and tell us whether You it's been successful. Thank You.

**Comment by mieplazma** [comment]
Thank you. The problem is in the browser. Using chrome everything works!
