### ISSUE TITLE
Product image scrolling Does not work from "last to first" or "first to last" if number of images=2 on product Description page

### ISSUE THREAD

**Issue by skashish** [magento/magento2#12552]
### Preconditions

1. Magento 2.1.9
2. Php 7.1

### Steps to reproduce

1. Create a new product. 
2. Add 2 images for that product.
3. Open that product on website (Product detail Page)

### Expected result

When Image is changed using right/left arrow, It must be able to slide from last to first, as it happens when no. of product images > 2.

### Actual result

Can't scroll from last image to first image.
![screen shot 2017-12-05 at 7 52 54 pm](https://user-images.githubusercontent.com/16701869/33612074-81ea1cc2-d9f6-11e7-9ccf-5a9291db5609.png)

**Comment by magento-engcom-team** [comment]
@skashish, thank you for your report.
We've created internal ticket(s) MAGETWO-85087 to track progress on the issue.

**Comment by skashish** [comment]
@magento-engcom-team Is there a quick-fix for this till the time it gets fixed?

**Comment by popovdenis** [comment]
#mageconf

**Comment by popovdenis** [comment]
Hi @skashish, this issue is already fixed in 2.2 version.
Tested on 2.2-develop branch.
Used Safari and Chrome, iOS.

**Comment by ishakhsuvarov** [comment]
Closing per comment above by @popovdenis 
Please reopen if the issue persists.
Thanks for collaboration
