### ISSUE TITLE
Preference for a block does not use core template file

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#12562]
### Preconditions
I've added a custom methods to checkout success block. However I don't need to modify it's template file.

1. Magento 2.1.7
2. Checkout success page

### Steps to reproduce

1. Create a preference for frontend checkout success block
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Checkout\Block\Onepage\Success"
        type="Qsolutions\Checkout\Block\Onepage\Success" />
</config>
```

2. Checkout / make an order on frontend
3. Success block will be missing

### Expected result

1. Checkout page working as it should

### Actual result

1. Block is not visible on checkout page. 
System.log has an error:
main.CRITICAL: Invalid template file: 'success.phtml' in module: 'Qsolutions_Checkout' block's

**Comment by orlangur** [comment]
Hello @qsolutions-pl,

This is already fixed on 2.2.0 branch: https://github.com/magento/magento2/blame/2.2-develop/app/code/Magento/Checkout/view/frontend/layout/checkout_onepage_success.xml#L20

You can add similar layout declaration into you instance.

> I've added a custom methods to checkout success block. However I don't need to modify it's template file.

This is not the right way of customization by the way. Extending core classes should be avoided whenever possible, when you need custom methods - simply declare a custom block.
