### ISSUE TITLE
change billing address also changed shipping address issue

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1256]
i have registered & ordered with same address info (billing & shipping).now if i'm going to change only shipping address also its changed billing address viceversa.
ver. 0.74.0-beta8

**Comment by vpelipenko** [comment]
@sivajik34, probably it works as expected. Waiting for clarification from responsible PO @ilol.

**Comment by sivajik34** [comment]
ok.then fine.but 99% sure.it will be bug.my target is 100 bugs.

**Comment by vpelipenko** [comment]
@sivajik34, :+1:

**Comment by ilol** [comment]
Thanks for that concern, @sivajik34. It is expected behavior. Thank you for your intention to make Magento better!

**Comment by sivajik34** [comment]
wel come.so i'm closing the issue.
