### ISSUE TITLE
Google Survey Opt-In Code in success.phtml

### ISSUE THREAD

**Issue by MoschenBayern** [magento/magento2#12569]
### Preconditions

1. 
2. 

### Steps to reproduce

1. add the Google Survey Opt-In Code in /Magento_Checkout/templates/success.phtml
2. added code: 

<script src="https://apis.google.com/js/platform.js?onload=renderOptIn"
  async defer>
</script>

<script>
  window.renderOptIn = function() { 
    window.gapi.load('surveyoptin', function() {
      window.gapi.surveyoptin.render(
        {
          // REQUIRED
          "merchant_id": xxxxxxxxxx,
          "order_id": "<?php echo $orderData->getIncrementId() ?>",
          "email": "<?php echo $orderData->getCustomerEmail() ?>",
          "delivery_country": "<?php echo $orderData->getShippingAddress()->getCountryId() ?>",
          "estimated_delivery_date": "YYYY-MM-DD"

          // OPTIONAL
          "opt_in_style": "BOTTOM_LEFT_DIALOG"
        }); 
     });
  }
</script>

3.   clean cache, grunt clean, exec and less the new theme

### Expected result

1.  After Checkout the Google Survey Plugin should be shown

### Actual result

1. 1 exception(s):
Exception #0 (Exception): Notice: Undefined variable: orderData in /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/app/design/frontend/Magento/Moschen2017/Magento_Checkout/templates/success.phtml on line 43

Exception #0 (Exception): Notice: Undefined variable: order in /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/app/design/frontend/Magento/Moschen2017/Magento_Checkout/templates/success.phtml on line 43
#0 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/app/design/frontend/Magento/Moschen2017/Magento_Checkout/templates/success.phtml(43): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined varia...', '/var/www/vhosts...', 43, Array)
#1 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vhosts...')
#2 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage\Success\Interceptor), '/var/www/vhosts...', Array)
#3 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/vhosts...')
#4 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#5 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#6 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('checkout.succes...')
#7 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('checkout.succes...')
#8 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('checkout.succes...')
#9 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#10 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('content')
#11 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('content')
#12 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main')
#13 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('main')
#14 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main')
#15 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns')
#16 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#17 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('columns')
#18 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content')
#19 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#20 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main.content')
#21 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#22 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#23 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.wrapper')
#24 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#25 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('root')
#26 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout->renderElement('root')
#27 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#28 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#29 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#30 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/generated/code/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#31 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#32 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#33 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#34 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#35 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#36 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#37 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#38 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#39 /var/www/vhosts/moschen-bayern.de/entwicklung.moschen-bayern.de/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#40 {main}

Can anybody help me pls. I think there is a problem by loading the order-id, email, delivery-country etc

**Comment by nntoan** [comment]
I believe this is not Magento 2 problem. Please ask this on Magento StackExchange, GitHub is using to tracking bugs not for programming questions.

> app/design/frontend/Magento/Moschen2017/Magento_Checkout/templates/success.phtml

**Comment by magento-engcom-team** [comment]
@MoschenBayern , thank you for you report.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
