### ISSUE TITLE
2.2.1 product  Shows product which is 0 stock and out of stock

### ISSUE THREAD

**Issue by sennin32** [magento/magento2#12567]
Configurable Product shows products which is 0 stock and out of stock
Display Out of Stock Products set to NO
And front end shows in stock.
when trying to add it into cart, ask for buyer to select an option

The other issue if Simple Product.
Still in the list when it is out of stock.
Unless recompile hole system, or it still there.

### Preconditions
1. PHP7
2. Magento 2.2.1

### Expected result

1. out of stock not show, or show out of stock

### Actual result

1. show in stock for every thing

**Comment by magento-engcom-team** [comment]
Hello @sennin32. Thanks for reporting. Please specify whether You use one ore more than one attribute in Your configurable product configuration.

**Comment by sennin32** [comment]
Sure,
I use two configurations.
But the simple product got issue too.
Somebody mentioned swatch got similar problem as well several days ago.

**Comment by magento-engcom-team** [comment]
@sennin32, thank you for your report.
We've created internal ticket(s) MAGETWO-84037 to track progress on the issue.

**Comment by sennin32** [comment]
Seems I can not even find related records with product got this issue in table prefix_cataloginventory_stock_item.
I guess this is not right!?

**Comment by tomekjordan** [comment]
Its happeining also on 2.2.2 for simple products and for bundle with the same simple assigned to it. No matter if you Save product with >0 qty and change out of stock to in stock. Reindex doesn't help

**Comment by wolfuma** [comment]
Same here on all product variants...... Works on 2.1.9 and didnt work after update to 2.2.1. For note, the swatches dont work properly, price didnt update on some MOBILE bowsers

**Comment by mysil2** [comment]
Fixed in 2.2.4-preview branch: #12936 

From the latest comment a backport to 2.3 is planned.

**Comment by magento-engcom-team** [comment]
Hi @sennin32 
We are closing this issue now as fix has been delivered to the 2.2 with the PR #12936 by @Coderimus
