### ISSUE TITLE
Add group prices programaticaly - Could not Save Group Price error.

### ISSUE THREAD

**Issue by harrigo** [magento/magento2#12565]
I cannot seem to add group prices programaticaly and keep getting Could not Save Group Price error.

I am trying with below code:
\Magento\Catalog\Api\ScopedProductTierPriceManagementInterface $tierInterface
$this->tierInterface = $tierInterface;

$tierPrice = $this->tierPrice;
$tierPrice->setQty(floatval(1));
$tierPrice->setValue(floatval($price));
$tierPrice->setCustomerGroupId($groupId);
$this->tierInterface->add($productId,$tierPrice);

This works fine for some products but then fails on others with the error. They seem to fail on products that have already had the group price set previously however not on others. Removing the group price allows me to add it with above code but attempting to run it again does not update and throws error.

I am using Magento 2.2.1 on Ubuntu with PHP7.

Exception #0 (Magento\Framework\Exception\CouldNotSaveException): Could not save group price

Exception #0 (Magento\Framework\Exception\CouldNotSaveException): Could not save group price
#0 /var/www/mage2/public_html/app/code/Harrigo/ContractPricing/Controller/Adminhtml/Wishlistimport/Index.php(65): Magento\Catalog\Model\Product\ScopedTierPriceManagement->add('304', Object(Magento\Catalog\Model\Product\TierPrice))
#1 /var/www/mage2/public_html/generated/code/Harrigo/ContractPricing/Controller/Adminhtml/Wishlistimport/Index/Interceptor.php(24): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index->buildWishlist(Object(Magento\Wishlist\Model\Wishlist), '/tmp/phpHla6pU', '4')
#2 /var/www/mage2/public_html/app/code/Harrigo/ContractPricing/Controller/Adminhtml/Wishlistimport/Index.php(127): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor->buildWishlist(Object(Magento\Wishlist\Model\Wishlist), '/tmp/phpHla6pU', '4')
#3 /var/www/mage2/public_html/generated/code/Harrigo/ContractPricing/Controller/Adminhtml/Wishlistimport/Index/Interceptor.php(37): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index->execute()
#4 /var/www/mage2/public_html/vendor/magento/framework/App/Action/Action.php(107): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor->execute()
#5 /var/www/mage2/public_html/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/mage2/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/mage2/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor->___callParent('dispatch', Array)
#8 /var/www/mage2/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /var/www/mage2/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /var/www/mage2/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /var/www/mage2/public_html/generated/code/Harrigo/ContractPricing/Controller/Adminhtml/Wishlistimport/Index/Interceptor.php(52): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#12 /var/www/mage2/public_html/vendor/magento/framework/App/FrontController.php(55): Harrigo\ContractPricing\Controller\Adminhtml\Wishlistimport\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /var/www/mage2/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /var/www/mage2/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#15 /var/www/mage2/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/mage2/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#17 /var/www/mage2/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/mage2/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#19 /var/www/mage2/public_html/pub/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#20 {main}

**Comment by VivekShingala** [comment]
Hi @harrigo 

How did you fix it?
