### ISSUE TITLE
Free Shipping Shopping Cart Rule doesn't work with UPS 

### ISSUE THREAD

**Issue by pmoreno1980** [magento/magento2#12573]
### Preconditions
1. Magento 2.1.7
2. PHP 7.0
3. Mysql 5.7

### Steps to reproduce
1. Create Shopping Cart Rule for free shipping using UPS. 
          Apply=Percent of product price discount
          Apply to Shipping Amount=Yes
          Discard subsequent rules=Yes
          Free Shipping=For shipment with matching items
2. UPS setting
          Free Method=UPS Standard
3. Free Shipping Method=Disable
4. add a product to the cart and fill any zipcode and state

### Expected result
1.  Free Shipping Option on Shipping Options

### Actual result
1. regular UPS rates

**Comment by magento-engcom-team** [comment]
@pmoreno1980, thank you for your report.
We've created internal ticket(s) MAGETWO-85216 to track progress on the issue.

**Comment by erikhansen** [comment]
Based on my research, the free shipping functionality of Cart Price rules was only designed to work with the "Free Shipping" shipping method:

![magento admin-icyhz](https://user-images.githubusercontent.com/129031/34045841-5ca3033a-e170-11e7-81b1-913d1b629c16.png)

Take a look at the `\Magento\OfflineShipping\Model\Quote\Address\FreeShipping::isFreeShipping` method for details.

The live rate methods (UPS/USPS/FedEx/etc) have their own "free shipping" functionality, but it is completely unaffected by Cart Price Rules:

![magento admin showmecables com-drebs](https://user-images.githubusercontent.com/129031/34051249-73ec090c-e183-11e7-8376-33a3c4fd0028.png)

**Comment by RostislavS** [comment]
@erikhansen Thanks for your research. You are absolutely right. I also investigated all functionality related to Free Shipping option in Shopping Cart rule and Free Method of UPS. And so I thought to post the same answer as yours. But then I checked Magento 1 functionality and I found out that it has the expected functionality. So it appears that it is not a small issue but Magento 2 is missing a whole block of functionality related to Free Shipping.

**Comment by pmoreno1980** [comment]
The problem is if i activate the free shipping method this option will appear on the cart for all products, the shopping cart rule does not work for this. My goal is display the free shipping option only for some products.

**Comment by erikhansen** [comment]
@pmoreno1980 You'll need to configure a very high "Minimum Order Amount" value for the Free Shipping Method. See this screenshot for an example:

![2017121420-19-20_spend_50_or_more_-_shipping_is_free__promotions__marketing__magento_admin-7lxfb](https://user-images.githubusercontent.com/129031/34185012-c158481e-e4e8-11e7-91ed-96bf6d0ae79d.png)

Be aware that I was able to get that working with a 2.1.6 EE installation with sample data, but I could not get it working with a 2.1.9 or 2.1.10 site. I had to apply [this patch](https://gist.github.com/erikhansen/aeebf4d794aaf39b0beb50bbfaf297e9) to the `magento/module-offline-shipping` Composer package to get it working (not sure if this was the absolute best approach, but it fixed my issue).

Can you close this task since this is not a core bug?

**Comment by markalston** [comment]
@erikhansen Setting the Minimum order amount high doesn't fix the issue where you want free shipping only for matching items.   Currently (2.2.3) if the free shipping is either triggered for all items or none.  The existing choice "Free Shipping for matching items only" simply doesn't work as described.  

When the free shipping choice shows up in the shipping options it applies to the entire order.

What is needed is a way to make the items not calculate any shipping for ups/fedex/etc. but have the remaining (non-qualifying) items calculate shipping properly.

**Comment by markalston** [comment]
This issue is the same as #14206 and #10704 and still a problem in 2.2.3

**Comment by markalston** [comment]
Any movement on implementing my (or anyone else's) fixes on this?  My patch apparently fails some weight tests but I think that is because the tests are wrong (clearly they don't work correctly as the current free shipping implementation doesn't work).

**Comment by magento-engcom-team** [comment]
Hi @pmoreno1980 
This issue is already fixed and is expected to be patched with the upcoming 2.2.6 release.

For now, you may use the following commit as a reference: 83ecea76cd9d7394ef4b4985307068d4e3ff0d37

Thank you

**Comment by hackrat** [comment]
It seems not fixed in 2.2.6 also.
