### ISSUE TITLE
Checkout with new shipping method issue when code length exceeds 40 characters.

### ISSUE THREAD

**Issue by ankurvr** [magento/magento2#12575]
In ``quote_shipping_rate`` table's column ``code``'s allowed length is 255 but in ``quote_address`` table's column ``shipping_method``'s length is 40 only.
So when setting carrier and method in shipping method it combines both and saving in table ``quote_shipping_rate``.
So here if combined code length exceeds 40 character then loosing characters from index 41.
With this configuration i can reach checkout payment page. But after that i am getting "An error occurred on the server. Please try to place the order again".

### Preconditions

1. Magento Version : 2.1.6 (community-edition)
2. PHP : 7.0.24
3. MySQL : 5.7.19
4. Platform : MacOS High Sierra v10.13.1 (17B1003)

### Steps to reproduce

1. Add new shipping method [Reference for Creating New Shipping Method](https://webkul.com/blog/create-custom-shipping-method-in-magento2/)
2. Try checkout by selecting this shipping method
3. At Payment checkout step error will be triggered

### Expected result

1. It should place order successfully

### Suggested Solution
- Increase ``quote_address`` table's column ``shipping_method``'s length from 40 to 255 (It should be same as ``quote_shipping_rate`` table's column ``code``'s length 255)
- The error is not catchable so i am suggesting this update.

**Comment by magento-engcom-team** [comment]
@ankurvr , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
