### ISSUE TITLE
you have placed no orders 

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1257]
I registered  account and i placed 2 orders.then i'm going to my account->my orders.
if i click my orders its showing "you have placed no orders"
note:its showing only in nano seconds of time.then its showing grid perfectly.
please observe carefully for identifying issue.
browser:mozilla firefox
(ver. 0.74.0-beta8)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32709

**Comment by piotrekkaminski** [comment]
This issue is caused be extensive use of caching and will probably not be resolved for now.
