### ISSUE TITLE
Magento 2.2.1 - while saving product from admin getting error as Class Magento\ConfigurableProduct\Model\Product\VariationHandler does not exist

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#12570]
Preconditions

Previous version 2.2.1
PHP version 7.1.9

Steps to reproduce:

Update Associated Configurable product and save

Expected Result:

Product should save successfully

Actual result

Error message is received: Magento\ConfigurableProduct\Model\Product\VariationHandler does not exist

**Comment by magento-engcom-team** [comment]
@msawyers , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by d10nZ** [comment]
The bug is reproduced on Magento 2.1.10 (PHP Version 7.1.12)
Sample Data is installed

1. Admin Area -> Catalog -> Products -> Edit Product;
2. Product ID: 36 (SKU: 24-MG04, Name: Aim Analog Watch);
    url: admin/catalog/product/edit/id/36/set/11/type/simple/store/0
3. Advanced Inventory popup;
4. Change product Qty to 0 (zero); Click Done; Close Popup
5. Click Product "Save" button

**As a result Product have not been saved**

See attached screenshots:

![screenshot at 2017-12-09 00-46-20](https://user-images.githubusercontent.com/9153335/33784486-8124e69c-dc7a-11e7-931c-3b769f947027.png)

![screenshot at 2017-12-09 00-45-54](https://user-images.githubusercontent.com/9153335/33784479-79fea6f0-dc7a-11e7-9e3e-f1e83b62912f.png)

**Comment by BlackIkeEagle** [comment]
I think this is an issue with PHP 7.1.12, when running on PHP 7.0.26 you do not encounter this issue. There is an opcache issue in 7.1.12 and 7.2.0 which causes issues, see:
https://bugs.php.net/bug.php?id=74980
https://git.php.net/?p=php-src.git;a=commit;h=3df47c12f77a71f90778ec42e6892c828e702fb2

**Comment by BlackIkeEagle** [comment]
if you add

```php
if (function_exists('opcache_reset')) {
    opcache_reset();
}
```

To index.php the issue also dissapears

**Comment by msawyers** [comment]
Hi, ok thanks will try.

**Comment by msawyers** [comment]
Hi i added to index.php and issue still remains

![index](https://user-images.githubusercontent.com/8907629/33844148-67cf9b70-de6d-11e7-9177-69f3d704dee1.PNG)

**Comment by BlackIkeEagle** [comment]
@msawyers you should add it after the docblock, I should have been more clear, before any other code is run you should add the if

**Comment by vitormicillo** [comment]
I just ran into my terminal
`composer update`
I cleaned the cache and the static files my problem was solved

Magento 2.2.1, PHP 7.1

**Comment by BlackIkeEagle** [comment]
@vitormicillo It's very specific to PHP 7.1.12 and 7.2.0 with opcache enabled

**Comment by msawyers** [comment]
Many thanks @BlackIkeEagle, works like a charm.

**Comment by vitormicillo** [comment]
@BlackIkeEagle  what index.php you refer ?
what the location?

**Comment by BlackIkeEagle** [comment]
@vitormicillo depending on where your document root is, index.php in your root of your project file or pub/index.php

**Comment by Detzler** [comment]
it helped

https://github.com/magento/magento2/issues/12570#issuecomment-350510482

did it by:
`php -r "opcache_reset();"`

**Comment by emilshamloo** [comment]
@Detzler  did you run this code in SSH?

**Comment by emilshamloo** [comment]
Thanks @BlackIkeEagle 
I added your code into my index.php and it is working now.
`<?php
/**
 * Application entry point
 *
 * Example - run a particular store or website:
 * --------------------------------------------
 * require __DIR__ . '/app/bootstrap.php';
 * $params = $_SERVER;
 * $params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'website2';
 * $params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
 * $bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
 * \/** @var \Magento\Framework\App\Http $app *\/
 * $app = $bootstrap->createApplication(\Magento\Framework\App\Http::class);
 * $bootstrap->run($app);
 * --------------------------------------------
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
 if (function_exists('opcache_reset')) {
    opcache_reset();
}

try {
    require __DIR__ . '/app/bootstrap.php';
} catch (\Exception $e) {
    echo <<<HTML
<div style="font:12px/1.35em arial, helvetica, sans-serif;">
    <div style="margin:0 0 25px 0; border-bottom:1px solid #ccc;">
        <h3 style="margin:0;font-size:1.7em;font-weight:normal;text-transform:none;text-align:left;color:#2f2f2f;">
        Autoload error</h3>
    </div>
    <p>{$e->getMessage()}</p>
</div>
HTML;
    exit(1);
}

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
/** @var \Magento\Framework\App\Http $app */
$app = $bootstrap->createApplication(\Magento\Framework\App\Http::class);
$bootstrap->run($app);
`

**Comment by Detzler** [comment]
@emilshamloo, yes I ran it via ssh shell

@magento-engcom-team, shouldn't we integrate "opcache_reset" into "cache:clean stack"?
