### ISSUE TITLE
No such entity when add products

### ISSUE THREAD

**Issue by leoncito73** [magento/magento2#12588]
### Preconditions

1. Magento 2.2.1
2. PHP 7.0

### Steps to reproduce

1. Go to >Catalog > Products
2. Click 'Add product'
3. Fill all the required areas
4. Add image
5. Save or Save & Close

### Expected result

1.  Should save and add the product

### Actual result

1. Not save the product and return "No such Entity"
2. Logs : 2017-12-07 08:54:49] main.CRITICAL: Exception message: No such entity.
Trace: #0 /home/hostlema/outdooractiveshop.eu/vendor/magento/module-store/Model/Store.php(1028): Magento\Store\Model\GroupRepository->get('2')
3. Screenshots
- Reindex SS:
![captura-de-pantalla-2017-12-07-a-las-10 48 47](https://user-images.githubusercontent.com/31698668/33728493-45f3b58c-db83-11e7-9549-96b2a7e28820.jpg)
- Cronjobs
![captura de pantalla 2017-12-07 a las 11 01 34](https://user-images.githubusercontent.com/31698668/33728530-5bf9beda-db83-11e7-9de0-f0f66b9629f2.png)
- Stores
![captura de pantalla 2017-12-07 a las 19 19 20](https://user-images.githubusercontent.com/31698668/33728601-9abf51a2-db83-11e7-9ac4-10d92f4e85d4.png)
- Error Backend
![captura de pantalla 2017-12-06 a las 17 30 09](https://user-images.githubusercontent.com/31698668/33728618-a65f8e78-db83-11e7-92b1-c19273cd7513.png)
- error indexer back end
![captura de pantalla 2017-12-07 a las 11 05 24](https://user-images.githubusercontent.com/31698668/33728648-bee19202-db83-11e7-9e24-71ada1ab9ad1.png)

**Comment by magento-engcom-team** [comment]
@leoncito73 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by leoncito73** [comment]
@magento-engcom-team 
After searching I found one possible reason of this issue. But their solutions wan't work for me
Before this happen I had 3 stores (look attachment)
And after deleted one start the problem
I had to restore my site to my last point to fixed, but now I have the 3 stores again, and I'm afraid to delete one
So to reproduce
1 - 3 stores like in SS
2 - Delete one (in my case, default - german)
3 - Add some product
4 - Should be the error "no such entity"
![captura de pantalla 2017-12-14 a las 11 52 43](https://user-images.githubusercontent.com/31698668/33986438-3bd43d90-e0c6-11e7-906e-2c04ecc83b1b.png)
![captura de pantalla 2017-12-14 a las 11 53 26](https://user-images.githubusercontent.com/31698668/33986442-3f412a7e-e0c6-11e7-961d-208cba1c8a65.png)

**Comment by magento-engcom-team** [comment]
@leoncito73 ,thank for you update. We are not reproduce when delete default store. Please check this issue with vanilla installation without any extension if you have.

**Comment by leoncito73** [comment]
@magento-engcom-team 
I just finish to check in a vanilla installation without any extension and also me can't reproduce the issue.
So should be some extension or theme, correct?

**Comment by magento-engcom-team** [comment]
@leoncito73 , if in vanilla installation and default theme works without issue, yes problem in your custom extensions.

**Comment by magento-engcom-team** [comment]
@leoncito73 , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
