### ISSUE TITLE
Can't remove item description from wishlist

### ISSUE THREAD

**Issue by mazur-vlad** [magento/magento2#12582]
### Preconditions

1. Magento version 2.1.9
2. PHP 7.0.25

### Steps to reproduce

1. Login as customer
2. Add product to wishlist
3. Navigate to wishlist
4. Add any comment to item
5. Update wishlist
6. Remove comment from item
7. Update wishlist

### Expected result

1. Empty comment in item

### Actual result

1. Previous comment in item

**Comment by magento-engcom-team** [comment]
@MazurVlad, thank you for your report.
We've created internal ticket(s) MAGETWO-85188 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hu @MazurVlad 
We are closing this issue for now since the fix was delivered to `2.2-develop` and will be available with the next patch release

**Comment by mazur-vlad** [comment]
Hi @ishakhsuvarov,

Thanks!
