### ISSUE TITLE
bill-to-name & ship-to-name missing in orders grid in admin 

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1258]
i registered account in front end .and placed two orders.if i'm going to admin ->sales->orders.
bill-to-name & ship-to-name values missing
ver. 0.74.0-beta8

**Comment by sivaschenko** [comment]
Thank you for the report. Internal ticket: MAGETWO-37376

**Comment by vpelipenko** [comment]
@sivajik34, we've already fixed this issue. So fix is available in public repository. Please, check it.

**Comment by sivajik34** [comment]
thank you
