### ISSUE TITLE
after placing order with purchase order, magneto2.1.9 changes customer group to general

### ISSUE THREAD

**Issue by whereowareadmin** [magento/magento2#12589]
### Preconditions

1. I am using centos 7.4, php 7.0.2, mysql 5.6
2. 

### Steps to reproduce

1. create wholesaler customer group
2. create user and assign them wholesaler customer group
3. login with newly created user as wholesaler and place an order through purchase order

### Expected result

1. it should not change the customer group for that user back to general

### Actual result

1. it changes the customer group back to general

**Comment by magento-engcom-team** [comment]
@whereowareadmin, thank you for your report.
The issue is already fixed in 2.2.1
