### ISSUE TITLE
Not able to adjust loaded product attributes on wishlist

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#12599]
### Preconditions
1. Magento 2.1.8 EE
2. PHP 7.0.22-0ubuntu0.16.04.1
3. 10.0.31-MariaDB-0ubuntu0.16.04.2
4. nginx/1.10.3

### Steps to reproduce
1. I know that this is probably not an issue. But encountered some difficulties when tried to add an attribute to product on wishlist page. I wouldn't load attribute via source model to avoid performance issues. So would be great to have some flexible way to add product attributes via observer for example. Please take a look at my suggestion of implementation:

`module-wishlist/Model/ResourceModel/Item/Collection.php`
`_assignProducts method`

    protected function _assignProducts()
    {
        \Magento\Framework\Profiler::start(
            'WISHLIST:' . __METHOD__,
            ['group' => 'WISHLIST', 'method' => __METHOD__]
        );

        /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
        $productCollection = $this->_productCollectionFactory->create();

        if ($this->_productVisible) {
            $productCollection->setVisibility($this->_productVisibility->getVisibleInSiteIds());
        }

        $attributesToSelect = [
            'name',
            'visibility',
            'small_image',
            'thumbnail',
            'links_purchased_separately',
            'links_title',
        ];

        $this->_eventManager->dispatch(
            'wishlist_item_collection_products_before_load',
            [
                'product_collection'    => $productCollection,
                'attributes_to_select'  => &$attributesToSelect
            ]
        );

        $productCollection->addPriceData()
            ->addTaxPercents()
            ->addIdFilter($this->_productIds)
            ->addAttributeToSelect($attributesToSelect)
            ->addOptionsToResult()
            ->addUrlRewrite();

        if ($this->_productSalable) {
            $productCollection = $this->_adminhtmlSales->applySalableProductTypesFilter($productCollection);
        }

        $this->_eventManager->dispatch(
            'wishlist_item_collection_products_after_load',
            ['product_collection' => $productCollection]
        );

        $checkInStock = $this->_productInStock && !$this->stockConfiguration->isShowOutOfStock();

        foreach ($this as $item) {
            $product = $productCollection->getItemById($item->getProductId());
            if ($product) {
                if ($checkInStock && !$product->isInStock()) {
                    $this->removeItemByKey($item->getId());
                } else {
                    $product->setCustomOptions([]);
                    $item->setProduct($product);
                    $item->setProductName($product->getName());
                    $item->setName($product->getName());
                    $item->setPrice($product->getPrice());
                }
            } else {
                $item->isDeleted(true);
            }
        }

        \Magento\Framework\Profiler::stop('WISHLIST:' . __METHOD__);

        return $this;
    } 

### Expected result
1. Some kind of `wishlist_item_collection_products_before_load` from above example of code

### Actual result
1. Attributes which are loaded for product on load wishlist items collection are hardcoded

**Comment by benjamin-volle** [comment]
Hi,

You can add these lines to your di.xml file : 
`
    <preference for="Magento\Wishlist\Model\ResourceModel\Item\Collection" type="Project\Fix\Model\Magento\Wishlist\Model\ResourceModel\Item\Collection" />`

Then create a file named app/code/Project/Fix/Model/Magento/Wishlist/Model/ResourceModel/Item/Collection.php

and put this : 

`<?php

namespace Project\Fix\Model\Magento\Wishlist\Model\ResourceModel\Item;

class Collection extends \Magento\Wishlist\Model\ResourceModel\Item\Collection
{
    protected function _assignProducts()
    {
        \Magento\Framework\Profiler::start(
            'WISHLIST:' . __METHOD__,
            ['group' => 'WISHLIST', 'method' => __METHOD__]
        );

        /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
        $productCollection = $this->_productCollectionFactory->create();

        if ($this->_productVisible) {
            $productCollection->setVisibility($this->_productVisibility->getVisibleInSiteIds());
        }

        $productCollection->addPriceData()
            ->addTaxPercents()
            ->addIdFilter($this->_productIds)
            ->addAttributeToSelect($this->_wishlistConfig->getProductAttributes())
            ->addOptionsToResult()
            ->addUrlRewrite();

        if ($this->_productSalable) {
            $productCollection = $this->_adminhtmlSales->applySalableProductTypesFilter($productCollection);
        }

        $this->_eventManager->dispatch(
            'wishlist_item_collection_products_after_load',
            ['product_collection' => $productCollection]
        );

        $checkInStock = $this->_productInStock && !$this->stockConfiguration->isShowOutOfStock();

        foreach ($this as $item) {
            $product = $productCollection->getItemById($item->getProductId());
            if ($product) {
                if ($checkInStock && !$product->isInStock()) {
                    $this->removeItemByKey($item->getId());
                } else {
                    $product->setCustomOptions([]);
                    $item->setProduct($product);
                    $item->setProductName($product->getName());
                    $item->setName($product->getName());
                    $item->setPrice($product->getPrice());
                }
            } else {
                $item->isDeleted(true);
            }
        }

        \Magento\Framework\Profiler::stop('WISHLIST:' . __METHOD__);

        return $this;
    }
}`

The wishlist items will now include the attributes of file catalog_attributes.xml that you can add to each "etc" folder of your modules.

By the way, this issue have been resolved in 2.2 : https://github.com/magento/magento2/blob/2.2/app/code/Magento/Wishlist/Model/ResourceModel/Item/Collection.php

PS : sorry for the class code, i don't find any way to do this properly ...

Best,

**Comment by kvydiuk** [comment]
@synolia-bvo 
Thank you for your reply. Unfortunately preference for Collection class in my case is not a solution. But this is great news that issue is resolved in 2.2

Regards

**Comment by magento-engcom-team** [comment]
@breg-13, thank you for your report.
The issue is already fixed in 2.2.2
