### ISSUE TITLE
Magento 2 Bundle Size always 1MB. I want 100KB

### ISSUE THREAD

**Issue by joebordo** [magento/magento2#12593]
I want to have 100KB bundle size. When i put 100KB or 100kb instead of 1MB nothing happens. It's still 1MB.

### Preconditions
Magento 2.2.1
PHP 7.1

### Steps to reproduce
Set Bundle size in view.xml to 100KB
### Expected result
Bundled Size to be multiple 100KB files.
### Actual result
I get 1 big 1MB js bundled file.

**Comment by southerncomputer** [comment]
turn off merging

**Comment by magento-engcom-team** [comment]
@joebordo, thank you for your report.
We've created internal ticket(s) MAGETWO-85544 to track progress on the issue.

**Comment by p-bystritsky** [comment]
If you want to enable bundling with 100KB bundle size, you should:
1. Set Bundle size in view.xml to 100KB.
2. Enable JS bundling (`INSERT INTO core_config_data VALUES (NULL,'default',0,'dev/js/enable_js_bundling',1);`).
3. Disable (!) JS merging (`INSERT INTO core_config_data VALUES (NULL,'default',0,'dev/js/merge_files',0);`).
4. Flush cache.
5. Deploy static content (or switch to the production mode).
