### ISSUE TITLE
Swagger UI is out of date (version 3 is latest)

### ISSUE THREAD

**Issue by careys7** [magento/magento2#12595]
### Preconditions

1. Magento 2.x

### Steps to reproduce

1. Open /swagger route using browser

### Expected result

1. Swagger UI is using version 3

### Actual result

1. Swagger UI is using version 2

---

Is there any plans to upgrade swagger UI, or anything blocking this currently? See comment here: https://github.com/magento/magento2/pull/7446#issuecomment-350105915

**Comment by magento-engcom-team** [comment]
Hi @careys7. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/10
