### ISSUE TITLE
still pending status in orders grid in front end.

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1259]
i registered an account & placed and order.now status is pending.and i'm going to admin side.and created invoice for that .then i'm going to front end my account ->my orders grid.
still status showing pending in grid.
but its showing perfectly status is processing in order view page.
ver. 0.74.0-beta8
note: if i logout & login status updating in grid also

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32709

**Comment by vladimir-k** [comment]
Hi, @sivajik34. This bug has already been fixed. Please, let us know if you still have an issue. Thanks!
