### ISSUE TITLE
Swatches in 2.1.10 show associated text field

### ISSUE THREAD

**Issue by apsummers** [magento/magento2#12605]
Since upgrading to 2.1.10, swatches seem to show their associated text input on the frontend, which was previously hidden.

### Preconditions

1. Magento 2.1.10

### Steps to reproduce

1. Setup a configurable product with multiple color options

### Expected result

1. Product list view from 2.1.9

<img width="904" alt="screen shot 2017-12-08 at 1 30 56 pm" src="https://user-images.githubusercontent.com/1573349/33782984-6a8bfff6-dc20-11e7-8381-8a85dbed844b.png">

### Actual result

1. Product list view from 2.1.10

<img width="903" alt="screen shot 2017-12-08 at 1 58 20 pm" src="https://user-images.githubusercontent.com/1573349/33782996-758077b6-dc20-11e7-8cb9-f849acc3ad02.png">

Products with multiple color choices (e.g. a primary and secondary color) will show two text boxes, etc.

**Comment by magento-engcom-team** [comment]
@apsummers , We were not able to reproduce this issue by following the steps you provided. Please try to reproduce this issue on a clean installation.

**Comment by AndrewPenry** [comment]
I had a similar issue. It is not part of the core, it is part of your theme. What happened is that the styling for those fields was moved out of the JS and into the CSS. Your theme probably contains app/design/frontend/[Vendor]/[Theme]/Magento_Swatches/web/css/swatches.css

Add:
`
.swatch-input {
    left: -1000px;
    position: absolute;
    visibility: hidden;
}
`

This is the css that was added to swatch.css in commit https://github.com/magento/magento2/commit/cd6c087ec68b7fa4e4435488c7fe316625115182

**Comment by apsummers** [comment]
@AndrewPenry thank you for pointing out that commit! I had already dug into `swatch-renderer.js` but still saw the inline style--turns out I hadn't updated the sources for our Docker host volume, so while the app was using the 2.1.10 sources, I was still seeing the 2.1.9 sources in my editor. Couldn't fathom why the source had an inline style but the rendered HTML did not. Closing, and thanks again!
