### ISSUE TITLE
Is there a PR/Patch available for wishlist issue resolved in #11305

### ISSUE THREAD

**Issue by rossmc** [magento/magento2#12600]
@magento-engcom-team could you provide the PR/patch for #11305 which says it's fixed in 2.2, it's still not working in 2.1.10 

**Preconditions**
Magento 2.10.

**Steps to reproduce**
- Setup special price for any product
- Add this product to wishlist
- go to wishlist section

**Expected result**
- It should display the special price.

**Actual result**
- Normalprice is shown.

**Comment by ishakhsuvarov** [comment]
@rossmc Unfortunately we do not have information regarding the commits which fixed this issue

**Comment by magento-engcom-team** [comment]
Hello @rossmc. Thanks for applying. Unfortunately the appropriate commits have not been found, but ver. 2.2.1 has already been released, what You already may know. By that we do not mean that we recommend or suggest You to upgrade Your store, it's up to You to decide. We just want to be sure that You are aware of it.
