### ISSUE TITLE
Verbiage Update Required: Product Image Watermark size Validation Message

### ISSUE THREAD

**Issue by msarm** [magento/magento2#12613]
### Preconditions
1. Navigate to Admin Content module to edit Product Image Watermark.

### Steps to reproduce
1. Enter Product Image Watermark Image Size as 200X300 
2. Displays Validation Message: This value does not follow the specified format (for example, 200X300). 

### Expected result

1. The system expects the image size defined in 200x300 format as said in on-screen example format. But the validation message is misleading which has uppercase X instead lowercase x.

### Actual result

1. Validation Message Screenshot
![image](https://user-images.githubusercontent.com/1042633/33806382-6a7a898a-dd95-11e7-8de9-a95377a90126.png)

**Comment by magento-engcom-team** [comment]
@msarm, thank you for your report.
We've created internal ticket(s) MAGETWO-85270 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @msarm 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.
