### ISSUE TITLE
Magento 2.2.1 default cron settings causes server CPU and memory overload

### ISSUE THREAD

**Issue by calvintwr** [magento/magento2#12614]
### Preconditions

1. Magento 2.2.1
2. PHP 7

### Steps to reproduce

1. Set up cron settings as per the Magento official documentation: http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-cron.html

### Expected result

1. Everything should work fine.

### Actual result

1. The new cron fires before the old one can complete. Since each cron job takes longer than 1 minute to complete (no idea why it takes so long), crons will start to overload the server.

ps aux|grep php output:

> root@greyandsanders:/var/www/html/magento# ps aux|grep php
> www-data  4255  0.0  0.0   4460   796 ?        Ss   03:15   0:00 /bin/sh -c /usr/bin/php /var/www/html/magento/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/magento/var/log/magento.cron.log
> www-data  4256 34.3  6.6 396744 136636 ?       S    03:15   2:15 /usr/bin/php /var/www/html/magento/bin/magento cron:run
> www-data  4291  0.0  0.0   4460   796 ?        Ss   03:16   0:00 /bin/sh -c /usr/bin/php /var/www/html/magento/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/magento/var/log/magento.cron.log
> www-data  4294 30.6  6.6 396744 136452 ?       S    03:16   1:42 /usr/bin/php /var/www/html/magento/bin/magento cron:run
> www-data  4319  0.0  0.0   4460   772 ?        Ss   03:17   0:00 /bin/sh -c /usr/bin/php /var/www/html/magento/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/magento/var/log/magento.cron.log
> www-data  4321 28.9  6.6 396740 136516 ?       S    03:17   1:19 /usr/bin/php /var/www/html/magento/bin/magento cron:run
> www-data  4328  0.0  0.0   4460   788 ?        Ss   03:18   0:00 /bin/sh -c /usr/bin/php /var/www/html/magento/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/magento/var/log/magento.cron.log
> www-data  4329 26.3  6.5 396740 134588 ?       S    03:18   0:56 /usr/bin/php /var/www/html/magento/bin/magento cron:run
> www-data  4338  0.0  0.0   4460   792 ?        Ss   03:19   0:00 /bin/sh -c /usr/bin/php /var/www/html/magento/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/magento/var/log/magento.cron.log
> www-data  4339 25.5  6.5 396744 133252 ?       S    03:19   0:39 /usr/bin/php /var/www/html/magento/bin/magento cron:run
> www-data  4344  0.0  0.0   4460   768 ?        Ss   03:20   0:00 /bin/sh -c /usr/bin/php /var/www/html/magento/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/magento/var/log/magento.cron.log
> www-data  4345 28.2  6.5 396744 134112 ?       S    03:20   0:26 /usr/bin/php /var/www/html/magento/bin/magento cron:run
> www-data  4353  0.0  0.0   4460   688 ?        Ss   03:21   0:00 /bin/sh -c /usr/bin/php /var/www/html/magento/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/html/magento/var/log/magento.cron.log
> www-data  4354 38.0  6.5 396744 133244 ?       S    03:21   0:12 /usr/bin/php /var/www/html/magento/bin/magento cron:run
> root      4371  0.0  0.1  14344  2088 pts/0    S+   03:21   0:00 grep --color=auto php

**Comment by magento-engcom-team** [comment]
@calvintwr Thank you for your report! This issue is already addressed in internal ticket MAGETWO-83782 We are closing this issue as a duplicate of https://github.com/magento/magento2/issues/11002

**Comment by vipin12117** [comment]
This was never fixed. Still facing issues in 2.2.6 version.

**Comment by shivanisdev** [comment]
Getting the same issue in 2.2.6

**Comment by vipin12117** [comment]
Only solution to change cron timing 1 minute to 15 minutes.

**Comment by pkavanaghjr** [comment]
@vipin12117 Where do you go to change the cron timing?

**Comment by vipin12117** [comment]
You should change cron timing in crontab in Linux.

**Comment by djixas** [comment]
Why is magento v2 such hot garbage in everything it does?

**Comment by gianisimone** [comment]
Magento 2.3 and the issue is still there. Cron jobs saturates the resources of the hosting and the website suffers from memory leaks. I think I will never use Magento again.

**Comment by elfinger** [comment]
I tried Magento 1.9.4 years ago and it was a nightmare to install and configure. I recently got an e-commerce project and started analyzing Magento 2.3.2. Wow, what a horribly, bug-ridden hot mess of crap! First you go through the installation process and it supposedly finishes successfully. You access the admin page and css and js files don’t load. Same on the front end. And you realize this has been reported years ago and never fixed. So then you have to go to the command line interface over and over again. Oh, and if your database is confiugred to enforce GTID, Magento will FAIL. the list goes on and on.

**Comment by vipin12117** [comment]
This is not Magento issues. Please enable Apache rewrite module. Your problems will fix.
