### ISSUE TITLE
MEDIA URL net::ERR_ABORTED when sample data is installed

### ISSUE THREAD

**Issue by gerrybarron** [magento/magento2#12618]
I installed a fresh magento2.1.8 on our staging server without sample data and then when I searched for how to install sample data I just follow this instruction http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-sample-data-composer.html
But after finished installing the sample data there's an error for the media url then i tried to check the other issuer regarding this but non of them works for me. https://github.com/magento/magento2/issues/2816

### Preconditions

1. Magento 2.1.8
2. PHP 7.0.22-0ubuntu0.16.04.1
3. MYSQL Ver 14.14 Distrib 5.7.20
4. OS Ubuntu Server 16.04

### Steps to reproduce

1. I follow the guide for installing sample data : http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-sample-data-composer.html
2. Run bin/magento sampledata:deploy
3. After installing the sample data I ran the setup:upgrade and setup:di:compile
4.Then I clean and flush the cache using this command cache:clean and cache:flush

### Expected result

1. Successful installation of Sample Data and without an error

### Actual result

1. I encountered an error
![image](https://user-images.githubusercontent.com/15038452/33815707-76f6fa3e-de6e-11e7-8311-4fff9fc105b4.png)

**Comment by magento-engcom-team** [comment]
Hello @gerrybarron. Thanks for reporting. Currently we are not able to reproduce Your issue. Please answer some questions about it. 1. After installation of Magento had You changed the mode before installing sample data (from deafault)? 2. After installation of Magento had You made any changes Your instance at all (created new product, customer, changed configuration settings, whatever...)) before installing sample data?
Also below we describe the steps we made to reproduce Your issue. Please read them and tell us what we've missed or done unlike You have it done. So here we go:
1. In CLI  composer create-project --repository=https://repo.magento.com magento/project-community-edition=2.1.8 .
2. In browser entered our Magento website's url and got to websetup page.
3. Installed our Magento instance via websetup and entered admin page.
4. In CLI indexer:reindex; cache:flush.
5. sampledata:deploy; setup:upgrade; setup:di:compile.
6. cache:clean and cache:flush.

**Comment by gerrybarron** [comment]
Sorry for the late reply.
1. I didn't change anything on the mode it's still on default mode
2. Nope I didn't do that either its a fresh install of magento 2.1.8
I tried to reinstall the Magento 2.1.8 and install sample data and I have the same result

In the number 1 I didn't do that I have a zip file of Magento 2.1.8.

This is what i did.
1. I unzip the Magento-CE-2.1.8-2017-08-08-04-18-25.zip to staging folder
2. Created a database name "staging"
3. I open the browser and proceed to web setup and install the Magento
4. After installing I run the command for the composer to install sample data
`bin/magento sampledata:deploy`
5. After finish installing the sample data I run this commands
   5.1 `bin/magento setup:upgrade`
   5.2 `bin/magento setup:di:compile`
   5.3 `bin/magento indexer:reindex`
   5.4 `bin/magento cache:clean`
   5.5 `bin/magento cache:flush`
   5.6 I change the permission `chmod 777 staging -R`
   5.7 I change the owner `chown www-data:www-data staging -R`

**Comment by magento-engcom-team** [comment]
Thank You @gerrybarron. Please specify what browser You use.

**Comment by gerrybarron** [comment]
I use google chrome.

**Comment by magento-engcom-team** [comment]
Thank You @gerrybarron. Now also please specify us on what pages You get this error.

**Comment by gerrybarron** [comment]
At home page

**Comment by magento-engcom-team** [comment]
Unfortunately @gerrybarron, we are not able to reproduce Your issue. It seems to be caused by some environmental settings. Please try to find the answer on the sites like [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/). If you'd like to update the issue, please reopen it. Thank You.

**Comment by magento-engcom-team** [comment]
@gerrybarron, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
