### ISSUE TITLE
Incorrect Shipping charge when Discount Coupon applied

### ISSUE THREAD

**Issue by VignaS** [magento/magento2#12622]
### Preconditions
1. Magento Version: ================ Magento 2 2.1.5
2.  We are using table rate method for shipping, below are the value range,  
> rate $6.99 for orders up to $12.99  
> rate $5.99 for orders above $13 and up to $25.98  
> rate $4.99 for orders above $26 and up to $35.98  
> free shipping above $35 (using sales rule)   
3. When the subtotal is $19.98 , we have shipping rate as $5.99, that is correct. On applying a discount of $9 , the amount will be reduced to $10.98 and now the shipping rate should be changed as $6.99(as $10.98 is below $12.99 - 1st rate) but still we could see the shipping rate as $5.99(second rate).  
4.We did some analysis and found, shipping amount is calculating before applying discount(subtotal) and not for the amount after applying discount(SubtotalWithDiscount).
--
### Steps to reproduce
1. Add few products to cart and make the subtotal to reach around $19. 
2. apply discount code 'TEST', this will give -$9.99 as discount amount

### Expected result
1.  As per the table rate method for shipping provided above, As the subtotal is less than $10, the shipping amount should be $6.99

### Actual result
1. But the shipping amount calculated is $5.99

We did some analysis and found, shipping amount is calculating before applying discount(subtotal) and not for the amount after applying discount(SubtotalWithDiscount).

Is any other facing the same issue , if so please provide us the solution .

**Comment by magento-engcom-team** [comment]
Hello @VignaS. Thanks for reporting. Does Your magento instance really shows another subtotal after applying the discount code? Please, notice we ask about the very "Subtotal" and not the "Total".

**Comment by VignaS** [comment]
Thanks for your response,

No Subtotal remains same only the total is changing after applying discount
 For Example
 Subtotal   $15
 Shipping . $5.99
 total.     $20.99

On applying discount (TEST) > reduce's $9.99
  Subtotal   $15
  Discount  -$9.99
  Shipping   $5.99
  total.     $11

  Please refer the screen shot. We need the shipping amount as $6($15-$9.99 = $5.01)
![screen shot 2017-12-12 at 2 55 50 pm](https://user-images.githubusercontent.com/29374353/33877106-5dccc31a-df4d-11e7-9ae7-cec7a18954b8.png)

**Comment by magento-engcom-team** [comment]
@VignaS, please notice that Table Rate shipping method according to the official magento documentation is applied to Subtotal and not to the Total. If You still need another behavior You may try to achieve it f. e. via Catalog Price Rule, or Tier Pricing with Customer Groups.

For more information please visit http://docs.magento.com/m2/ce/user_guide/shipping/shipping-table-rate.html

**Comment by magento-engcom-team** [comment]
@VignaS, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by sambalay** [comment]
Hi,

we are also having the same issue. we are doing free shipping over 50$.

In checkout shipping step , customer is selecting 0.00 (free shipping) since it is above 50$

In payment section , they are applying promo code where subtotal is below 50$ but shipping charge still shows 0.00

They should be charged 8.12 ground shipping charge.

![capture-discount](https://user-images.githubusercontent.com/30907888/33946442-ce8426a0-dfef-11e7-9b24-02a2b5658ea2.PNG)

**Comment by mjoraid** [comment]
> Hi,
> 
> we are also having the same issue. we are doing free shipping over 50$.
> 
> In checkout shipping step , customer is selecting 0.00 (free shipping) since it is above 50$
> 
> In payment section , they are applying promo code where subtotal is below 50$ but shipping charge still shows 0.00
> 
> They should be charged 8.12 ground shipping charge.
> 
> ![capture-discount](https://user-images.githubusercontent.com/30907888/33946442-ce8426a0-dfef-11e7-9b24-02a2b5658ea2.PNG)
@sambalay hey, did yo manage by any chance to find a fix for this?
