### ISSUE TITLE
DHL Shipping Method not currently available - no log file

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12623]
**Preconditions**
1 ) Magento Version:2.2.0 
     PHP Version:7.1
     using nginx web server

**Steps to reproduce**
1) setup DHL configuration form backend 
2) enable DHL shipping method 
3) set Debug Yes
4)If User Enter Wrong address or anything went wrong with DHL web service at that time error log are not printed into var/log/debug.log file

**Expected result**
If DHL web service return any error at that time if debug is set Yes then Error log must be printed to  var/log/debug.log file

**Actual Result**
When debug is set Yes form admin configuration at that time debug log must be written into debug.log file

I have set 0644 file permission for var/log/debug.log  

Is any other facing the same issue , if so please provide us the solution .

**Comment by avoelkl** [comment]
Hi @navinbhudiya, thanks for your report.
The verification of your issue description failed. The minimum required information is not provided (Preconditions - for example PHP & MySQL version, etc., Actual Result).
Please update your description according to the issue template: [https://github.com/magento/magento2/issues/new](https://github.com/magento/magento2/issues/new)

You might add some more information like:
- Is your error/system/debug log working at all? Which file permissions are set?

Thanks!

**Comment by gwharton** [comment]
I had the same issue with getting any of the shipping modules to log debug.

The only way round it for me was to add the following line to core_config table in SQL

```
MariaDB [dev_magento]> SELECT * FROM `core_config_data` WHERE `config_id` = 1194;
+-----------+----------+----------+-------------------------+-------+
| config_id | scope    | scope_id | path                    | value |
+-----------+----------+----------+-------------------------+-------+
|      1194 | websites |        1 | dev/debug/debug_logging | 1     |
+-----------+----------+----------+-------------------------+-------+
1 row in set (0.00 sec)
```
and then flush config cache.

**Comment by ghost** [comment]
@avoelkl  i have updated information as per your suggestion

**Comment by magento-engcom-team** [comment]
@navinbhudiya, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Alfa** [comment]
Hi @navinbhudiya. Thank you for your report.

If DHL web service returns any error at that time if debug is set Yes, all error logs printed to /var/log/**shipping.log** file.

**Actual Result:**
![tessst](https://user-images.githubusercontent.com/51679138/72348674-91370680-36e3-11ea-921a-e32cc60575c4.png)
So we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
