### ISSUE TITLE
customer account information not loading in admin

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1262]
i created account in front end side.then i login to admin and customers grid.and if i click edit button..still its loading..
browser:mozilla,linux mint
ram:2gb
ver. 0.74.0-beta8
note: may be this issue wont occur in other systems ,browsers.
i have not checked properly.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-35721

**Comment by sivajik34** [comment]
after deleting pub/static/_requirejs/adminhtml
its working fine
