### ISSUE TITLE
Cannot fetch default Theme

### ISSUE THREAD

**Issue by shavounet** [magento/magento2#12638]
This is mostly a technical issue. While using `Magento\Framework\View\Config::getViewConfig` without theme parameter, it doesn't match properly the default theme.

* it tries to fetch Theme data here
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/View/Config.php#L59
* then this method uses `Magento\Theme\Model\View\Design::getConfigurationDesignTheme` to fetch a *numerical* ID
* and finally there is a call to `\Magento\Framework\View\Design\Theme\ThemeProviderInterface::getThemeByFullPath` with something like "frontend/4", that can't be resolved

I'm not certain about the fix

* either `\Magento\Framework\View\Design\Theme\ThemeProviderInterface::getThemeByFullPath` should be able to fetch the correct theme (the information is here, and the risk for a mismatch is really small... unless a theme has a numerical name, which should be forbidden)
* or update `\Magento\Framework\View\Asset\Repository::updateDesignParams` to be more clever (but maybe this bug could occur elsewhere...)

Tested on Magento 2.1.10 CE / PHP 7

**Comment by shavounet** [comment]
To test this easily, call `\Magento\Framework\View\Config::getViewConfig` anywhere in your code, and inspect the result. It should contain all image configuration defined in the theme's `view.xml`

My test case: 
```php
$result = $this->viewConfig->getViewConfig(['area'  => 'frontend']);
```

Note that it works fine with 
```php
$result = $this->viewConfig->getViewConfig(['area'  => 'frontend', 'theme' => 'Vendor/my_theme']);
```

**Comment by magento-engcom-team** [comment]
@shavounet, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by py4762013** [comment]
Magento\Framework\View\Asset\Repository

  |   | +    public function updateDesignParams(array &$params)
  |   | +    {
  |   | +        // Set area
  |   | +        if (empty($params['area'])) {
  |   | +            $params['area'] = $this->getDefaultParameter('area');
  |   | +        }
  |   | +
  |   | +        // Set themeModel
  |   | +        $theme = null;
  |   | +        $area = $params['area'];
  |   | +        if (!empty($params['themeId'])) {
  |   | +            $theme = $params['themeId'];
  |   | +        } elseif (isset($params['theme'])) {
  |   | +            $theme = $params['theme'];
  |   | +        } elseif (empty($params['themeModel']) && $area !== $this->getDefaultParameter('area')) {
  |   | +            $theme = $this->design->getConfigurationDesignTheme($area);
  |   | +        }
  |   | +
  |   | +        if ($theme) {
  |   | +            if (is_numeric($theme)){
  |   | +                $params['themeModel'] = $this->getThemeProvider()->getThemeById($theme);
  |   | +            }else{
  |   | +                $params['themeModel'] = $this->getThemeProvider()->getThemeByFullPath($area . '/' . $theme);
  |   | +            }
  |   | +            if (!$params['themeModel']) {
  |   | +                throw new \UnexpectedValueException("Could not find theme '$theme' for area '$area'");
  |   | +            }
  |   | +        } elseif (empty($params['themeModel'])) {
  |   | +            $params['themeModel'] = $this->getDefaultParameter('themeModel');
  |   | +        }
  |   | +
  |   | +        // Set module
  |   | +        if (!array_key_exists('module', $params)) {
  |   | +            $params['module'] = false;
  |   | +        }
  |   | +
  |   | +        // Set locale
  |   | +        if (empty($params['locale'])) {
  |   | +            $params['locale'] = $this->getDefaultParameter('locale');
  |   | +        }
  |   | +        return $this;
  |   | +    }

**Comment by yekyo** [comment]
fixed    Magento\Framework\View\Asset\Repository  

 ```
   public function updateDesignParams(array &$params)
    {
        // Set area
        if (empty($params['area'])) {
            $params['area'] = $this->getDefaultParameter('area');
        }

        // Set themeModel
        $theme = null;
        $area = $params['area'];
        if (!empty($params['themeId'])) {
            $theme = $params['themeId'];
        } elseif (isset($params['theme'])) {
            $theme = $params['theme'];
        } elseif (empty($params['themeModel']) && $area !== $this->getDefaultParameter('area')) {
            $theme = $this->design->getConfigurationDesignTheme($area);
        }

        if ($theme) {
            if (is_numeric($theme)){
                $params['themeModel'] = $this->getThemeProvider()->getThemeById($theme);
            }else{
                $params['themeModel'] = $this->getThemeProvider()->getThemeByFullPath($area . '/' . $theme);
            }
            if (!$params['themeModel']) {
                throw new \UnexpectedValueException("Could not find theme '$theme' for area '$area'");
            }
        } elseif (empty($params['themeModel'])) {
            $params['themeModel'] = $this->getDefaultParameter('themeModel');
        }

        // Set module
        if (!array_key_exists('module', $params)) {
            $params['module'] = false;
        }

        // Set locale
        if (empty($params['locale'])) {
            $params['locale'] = $this->getDefaultParameter('locale');
        }
        return $this;
    }
```

**Comment by engcom-Delta** [comment]
Hi @shavounet thank you for your report. I am not able to reproduce issue on  2.4-develop

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
