### ISSUE TITLE
"We don't have as many "product name" as you requested." not showing in mini cart

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1263]
i have a product quantity 10.and i added 5 quantity to cart.now i want to update quantity 5 to 45 in mini cart (in header).
at that time its total updating properly.but i'm expecting it should show following error.
"We don't have as many "product name" as you requested."
and i checked that its going to "http://localhost/magento2/index.php/checkout/sidebar/updateItemQty/"

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-37252

**Comment by tanya-soroka** [comment]
@sivajik34 Please check also if you enable Backorder.  if it's enabled that this message won't be display for you.

**Comment by vpelipenko** [comment]
@tanya-soroka, is it expected behavior? @sivajik34, did you have a chance to reproduce this issue with enabled backorders?

**Comment by vpelipenko** [comment]
@sivajik34, issue is fixed and available from 0.74.0-beta13.

**Comment by sivajik34** [comment]
thank you
