### ISSUE TITLE
Magento2 community is too slow with 56 thousand products

### ISSUE THREAD

**Issue by sakjha10** [magento/magento2#12635]
### Preconditions

1. Using Magento 2.2 version, Ngnix server, RDS database
2. PHP 7.1, latest mysql

### Steps to reproduce

1. Slow and 502 issue if the products are more than 55 thousand
2. After disabling all the products and reindexing the store, the website starts working fine.

### Expected result

1. Expect website will work smoothly

**Comment by sakjha10** [comment]
How many products Magento community supports?

**Comment by orlangur** [comment]
@sakjha10 hundreds of thousands actually: https://github.com/magento/magento2/blob/2.2-develop/setup/performance-toolkit/profiles/ce/extra_large.xml#L14

Try to perform a profiling of your particular instance or fix environment setup.

**Comment by magento-engcom-team** [comment]
Hi @orlangur thank you for investigation.
