### ISSUE TITLE
Magento 2.1.8 - PHP Parse error on console command deploy

### ISSUE THREAD

**Issue by hieunc09** [magento/magento2#12645]
### Preconditions

1. Magento 2.1.8
2. 

### Steps to reproduce

1. After composer install
2. Update config.php and env.php file to connect with database
3. Typing : php bin/magento

### Expected result

1. PHP Parse error:  parse error in ../vendor/magento/magento-cloud-configuration/src/Magento/MagentoCloud/Console/Command/Deploy.php on line 518

### Actual result

1. ![deploy](https://user-images.githubusercontent.com/20764820/33874001-c0e6338a-df4f-11e7-814e-f9ef7fe38eb9.png)

Please advise it!

**Comment by orlangur** [comment]
Looks like a mistake in `MagentoCloud` module. Such syntax is only supported in PHP 7.1.

You can either use PHP 7.1 or replace this logic with equivalent `isset($array['key']) ? $array['key'] : []`.

**Comment by mrkhoa99** [comment]
PHP 7 syntax.
http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

**Comment by mrkhoa99** [comment]
@orlangur I think it's PHP 7 syntax. Not only PHP 7.1?

**Comment by orlangur** [comment]
@mrkhoa99, oh, you are right, I mixed it up with nullable types https://github.com/magento-engcom/msi/wiki/PHP-7-Syntax-usage-for-Magento-Contribution

Still, Magento 2.1.8 should support PHP 5.6 and looks like this is the case. Unless `composer.json` of `MagentoCloud` module explicitly states it is only for PHP7+.

**Comment by magento-engcom-team** [comment]
@hieunc09 thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
