### ISSUE TITLE
url_key is empty by product import even if not wanted

### ISSUE THREAD

**Issue by benjamin-volle** [magento/magento2#12641]
url_redirect value is overrrided by each product import, even if it is not wanted

### Preconditions
1. Tested on Magento 2.2

### Steps to reproduce
1. Add some products to your instance
2. Change url_key for one of them
3. Import a file (append behavior) with only two columns : sku,price (including the previous product)

### Expected result
1. Prce is updated, url_key is not changed

### Actual result
1. Price is updated, but url_key is empty

The problem is that url_key is always generated by import, because of this addition : 
https://github.com/magento/magento2/commit/ebc946a7672a3160d1fd0fd79fbb9a518b286a3c

In the past (before 2.2, the url_key value was stripped by the function : 
\Magento\CatalogImportExport\Model\Import\Product\Type\AbstractType::clearEmptyData

But now, since there was a modification from "empty" to "!isset", the '' (empty) value is not stripped.

**Comment by magento-engcom-team** [comment]
@synolia-bvo, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by benjamin-volle** [comment]
Well, I'm a little bit suprised by your answer.

I don't understand why any product import replaces the "url_key" of the imported products by an empty value, even if the column "url_key" is not in the imported file.

To fix this, I replaced the line : 

`if (!$attrParams['is_static'] && empty($rowData[$attrCode])) {`
by 
`if (!$attrParams['is_static'] && (!isset($rowData[$attrCode]) || $rowData[$attrCode] === '')) {`

in the \Magento\CatalogImportExport\Model\Import\Product\Type\AbstractType::clearEmptyData function.

**Comment by magento-engcom-team** [comment]
@synolia-bvo, We are sorry for that reply - it concerned another reporter's issue. We posted it here accidentally. Now we've been trying to reproduce Your's one and we'll be back with the answer as soon as possible.

**Comment by magento-engcom-team** [comment]
Hello again @synolia-bvo. For unknown reason the rows from the commit you refer to (ebc946a) are no more present in release version of 2.2.0 and as far as we tested in 2.2.1 either. Could You please specify what is the exact release name of the version You use (f. e. 2.2.0-rc13). Thank You.

**Comment by benjamin-volle** [comment]
The main problem is the row 
`$rowData[self::URL_KEY] = $this->getUrlKey($rowData); `
and it is still present in last 2.2 : https://github.com/magento/magento2/blob/2.2/app/code/Magento/CatalogImportExport/Model/Import/Product.php , line 1589

(The deleted "if" has been transfered to the "clearEmptyData" function)

**Comment by magento-engcom-team** [comment]
Yes @synolia-bvo, we confirm it. But not going deeply into details lets assume that in this context the code peace we are talking about does not cause the issue. At least we've been not able to reproduce it on neither of the versions we've tested including the very one You provided us with in the Last comment. Could You please try to reproduce it on a freshly installed branch. Thank You.

**Comment by benjamin-volle** [comment]
Yes excuse me, the problem is only in branch 2.2-develop : 

https://github.com/magento/magento2/tree/2.2-develop 

which is the only one where the "empty" of the \Magento\CatalogImportExport\Model\Import\Product\Type\AbstractType::clearEmptyData function has been replaced by "!isset".

To summarize : 
Either we cannot import a "0" value (this is why empty has been replaced by "!isset")
Or the url_key is empty by each import

**Comment by magento-engcom-team** [comment]
@synolia-bvo, thank you for your report.
The issue is already fixed in 2.2.1

**Comment by sylvainraye** [comment]
@magento-engcom-team fixed in 2.2.1 but reappeared in latest releases (2.2.4, 2.3) => https://github.com/magento/magento2/issues/14478 cause of https://github.com/magento/magento2/issues/12083

**Comment by peterjaap** [comment]
I think this is now fixed in 2.2-develop (staged for 2.2.8 release) here; https://github.com/magento/magento2/pull/17882
