### ISSUE TITLE
Images showing 1 below another in slider on homepage, slider effect is not showing

### ISSUE THREAD

**Issue by parag2jcommerce** [magento/magento2#12646]
![2017-12-12_13-54_home page](https://user-images.githubusercontent.com/34369132/33874256-27b50a52-df44-11e7-93b1-f8c3180643a1.jpg)
Images showing 1 below another in my slider. Effects are not working in slider. All setup are fine and code is also arranged properly.
After creating slider when I preview it from backend, then also the images are showing one below another, as showin in below screenshot--
![2017-12-12_14-04_preview slider template](https://user-images.githubusercontent.com/34369132/33874670-8ba4f620-df45-11e7-8f03-1a4012c55072.jpg)

Please help me out in this issue

Regards
Parag

**Comment by okorshenko** [comment]
Hi @parag2jcommerce  Thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by parag2jcommerce** [comment]
Preconditions: Magento ver. 2.1.9

Steps to reproduce: 
1. Unzip bannerslider
2. php bin/magento setup:upgrade
3. chmod -R 777 pub var/

 Expected result: 
To show the effects with images on pages, slider should work with its animation.

Actual result:
Backend screenshot-
![2017-12-12_14-04_preview slider template](https://user-images.githubusercontent.com/34369132/33875299-da10c706-df47-11e7-9bf8-cac9cac4df9c.jpg)

Frontend Screenshot-
![2017-12-12_13-54_home page](https://user-images.githubusercontent.com/34369132/33875331-f584c51e-df47-11e7-8922-40e00ea6d1b0.jpg)

**Comment by ishakhsuvarov** [comment]
@parag2jcommerce Could you please give more information regarding this step?
> 1. Unzip bannerslider

What is `bannerslider`?

**Comment by parag2jcommerce** [comment]
BannerSlider is extension of slider.
After extracting zip folder of bannerslider, i run upgrade command,
then all the setting came into dashboard and I setup Banner and sliders too.
Also I call that on Home by passing its ID ,
It is displaying on home page but not proper, You are able to see screenshot how it looks like...

**Comment by ishakhsuvarov** [comment]
@parag2jcommerce We can not provide support for any third-party extensions or customizations. 
Please contact extension vendor in order to get support.
