### ISSUE TITLE
add all to cart button click 404 error wishlist 

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1264]
i added product with quantiy 3 to cart.then i moved to wishlist.then i click add all to cart button ..its giving following error.
http://localhost/magento2/index.php/page_cache/block/allcart/wishlist_id/3/form_key/Tp4s5RbE7h6N38eQ/?qty[2]=3

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-36469

**Comment by vpelipenko** [comment]
hi @sivajik34, internal ticket is closed with resolution "Cannot Reproduce". It can mean that this issue was fixed in scope of another ticket. Please, verify the issue on the latest code base and let us know if you still face with it.

**Comment by sivajik34** [comment]
yes.its working fine.thank you
