### ISSUE TITLE
Search doesn't work properly

### ISSUE THREAD

**Issue by gianiaco** [magento/magento2#12657]
Search bar in frontend doesn't work like that in backend. 
The searched word must be initial part of the whole word.
In the backend search bar there isn't this problem 

### Preconditions
1.  Magento 2.2.1
2.  Php 7.0.2
3.  mysql 5.7

### Steps to reproduce

1. Create a product with name 'Samsung 55" UE55MU6200'
2. Type '55MU62' in search bar
3. Press ENTER

### Expected result

1. I found the product

### Actual result

1. No results

**Comment by magento-engcom-team** [comment]
@gianiaco, thank you for your report.
We've created internal ticket(s) MAGETWO-85598 to track progress on the issue.

**Comment by p-bystritsky** [comment]
This is an expected behavior, so issue should be treated as feature request.

**Comment by dimaperedriy** [comment]
#mageconf

**Comment by dimaperedriy** [comment]
It is not a bug.. It is a performance improvement regarding to mysql index working (Search engine processing with B-tree)
