### ISSUE TITLE
Magento 2 - “All Customers” admin page loads blank with no data or page structure

### ISSUE THREAD

**Issue by innocinema** [magento/magento2#12651]
I am able to do a clean Magento 1.7.0.2 to 2.2 data migration install with no 3rd party modules. I have verified customer data seems to have migrated successfully, including in the customer_grid_flat table.

When I log into the Magento 2 admin and click on the "All Customers" page, it loads as a completely blank / empty page with no data or structure at all. I have verified the `<body></body>` tag is empty. So this seems to be more than just a data issue, something is messing up the actual load of the page structure as well.

Other forums state that not having customer_grid_flat data seems to be a common reindexing issue. I have verified that is not the case here. There is definitely data in the customer_grid_flat table.I am not able to produce any log of an error as the page does "load" a successful blank / empty page. Because of this, I am blind at what to do next to troubleshoot this problem.

**### Preconditions**
1.  This is the next error after a Magento 1.7.0.2 to 2.2.0 data migration run.
2. PHP version: 7.0.20

**### Steps to reproduce**
1. Clean Magento 2.2.0 install with no data, no 3rd party modules installed, and verified for stablity BEFORE data migration run.
2. Run of the data-migration-tool for opensource to opensource for 1.7.0.2 to 2.2.0. There are some customizations and error fixes to the migration-tool files. Non of which "seems" to be customer data related. I can provide these changes if needed. The run is done successfully with no errors but a few warnings related to sales order data _(different issue, "likely" unrelated to this customer data issue)_.
3. After the data-migration is complete, I run the following commands in effort to reset the environment the best I can.
`php bin/magento setup:upgrade`
`php bin/magento setup:di:compile`
`php bin/magento -f setup:static-content:deploy`
`php bin/magento update magento.indexer_state set status='invalid' where status ='working'`
`php bin/magento update magento.indexer_state set status='invalid' where status ='valid'`
`php bin/magento indexer:reindex`
`php bin/magento cache:clean`
`php bin/magento cache:flush`
4. I have verified that all customer data is correctly migrated in the database tables, including indexed properly in the customer_grid_flat table.

**### Expected result**
1. Log into Magento 2.2 admin successfully
2. Correctly load the page and view all customer data when clicking on _"Customers" > "All Customers"_ admin links.

**### Actual result**
1. I am able to log in to Magento 2.2 Admin successfully.
2. When clicking on _"Customers" > "All Customers"_, no page is loaded at all. There are no error logs created from what I can see. I inspected the page to see what code was generated and all I saw was below empty HTML Tags.
`<html>`
`  <head></head>`
`  <body>`
`  </body>`
`</html>`

**Comment by magento-engcom-team** [comment]
Hi @innocinema 
Please use the data-migration-tool repository for migration-related issues: https://github.com/magento/data-migration-tool
Thank you
