### ISSUE TITLE
SandBox Authorized .net

### ISSUE THREAD

**Issue by william-hiko** [magento/magento2#12654]
### Preconditions

1. Magento 2.1.9 CE
2. PHP 7.0 
3. MySQL 5.6 

### Steps to reproduce

1. I folowed this article to link magento2 with sandbox.authorized.net (https://www.codealist.net/magento-2-x-configure-authorize-net/)
2. everything looks good and i could place order and i could also see it on the sandbox account but when i successfully placed the order.i went to var/log and i see error in the system.log

### Expected result

1. i expected to see the payment details on the order but i only see this 
![image](https://user-images.githubusercontent.com/34488641/33903378-349994d4-df46-11e7-8a76-279ea9df3988.png)

### Actual result

[2017-12-12 18:44:06] main.CRITICAL: Magento\Framework\Exception\LocalizedException: Unable to get transaction details. Try again later. in /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-authorizenet/Model/TransactionService.php:135
Stack trace:
#0 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-authorizenet/Model/TransactionService.php(85): Magento\Authorizenet\Model\TransactionService->loadTransactionDetails(Object(Magento\Authorizenet\Model\Directpost), '40008969960')
#1 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-authorizenet/Model/Directpost.php(769): Magento\Authorizenet\Model\TransactionService->getTransactionDetails(Object(Magento\Authorizenet\Model\Directpost), '40008969960')
#2 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-authorizenet/Model/Directpost.php(706): Magento\Authorizenet\Model\Directpost->addStatusComment(Object(Magento\Sales\Model\Order\Payment\Interceptor))
#3 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-authorizenet/Model/Directpost.php(583): Magento\Authorizenet\Model\Directpost->processOrder(Object(Magento\Sales\Model\Order))
#4 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-authorizenet/Controller/Directpost/Payment.php(90): Magento\Authorizenet\Model\Directpost->process(Array)
#5 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-authorizenet/Controller/Directpost/Payment/Response.php(19): Magento\Authorizenet\Controller\Directpost\Payment->_responseAction('frontend')
#6 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/var/generation/Magento/Authorizenet/Controller/Directpost/Payment/Response/Interceptor.php(24): Magento\Authorizenet\Controller\Directpost\Payment\Response->execute()
#7 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor->execute()
#8 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor->___callParent('dispatch', Array)
#10 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Authori...', 'dispatch', Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Array, 'contextPlugin')
#11 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Authori...', 'dispatch', Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Array, 'customer-app-ac...')
#14 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Authori...', 'dispatch', Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Array, 'storeCheck')
#17 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Authori...', 'dispatch', Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Array, 'weee-app-action...')
#20 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Authori...', 'dispatch', Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Array, 'tax-app-action-...')
#23 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/var/generation/Magento/Authorizenet/Controller/Directpost/Payment/Response/Interceptor.php(39): Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Authorizenet\Controller\Directpost\Payment\Response\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#29 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#30 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#33 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#36 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#39 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#42 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#44 /mnt/data/home/128812.cloudwaysapps.com/pbpnhpdtpp/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#45 {main} [] []

**Comment by YevSent** [comment]
Hi, @william-hiko, did you enabled `Transaction API` in the Authorize.net account? Also, the sandbox URL for the transaction API should be configured as `https://apitest.authorize.net/xml/v1/request.api `.

**Comment by william-hiko** [comment]
Many Thanks @joni-jones, the Transaction Details URL was missed in the article for this i could not get the details
