### ISSUE TITLE
Checkout: Whitespace in front of coupon code causes "Coupon code is not valid"

### ISSUE THREAD

**Issue by AndrewPenry** [magento/magento2#12656]
### Preconditions

1. Magento 2.1.10 with Sample Data
2. PHP Version 7.0.22

### Steps to reproduce

1. Open checkout page and complete up to Payment step
2. Fill in a coupon code with leading whitespace, like " H20"
3. Click "Apply Discount"

### Expected result

1. The Discount should be applied

### Actual result

1. "Coupon code is not valid"
2. In the logs: PUT /rest/default/V1/guest-carts/64610d8402c5f9e919929442220967ca/coupons/%20H20 HTTP/1.1

Note that whitespace after the coupon code is not being encoded in the PUT string, so the coupon works with trailing whitespace, just not with leading whitespace.

**Comment by magento-engcom-team** [comment]
@AndrewPenry, thank you for your report.
We've created internal ticket(s) MAGETWO-85582 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @AndrewPenry 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.
