### ISSUE TITLE
Please help - Readiness check - ERROR - (was no problem before)

### ISSUE THREAD

**Issue by kbuje** [magento/magento2#12658]
I have installed magento 2.21 on a webhotel

I have installed a payment extension and nothing else. I used the extension manager. 
- then worked on the site. 

Now when I try to install anything or to update magneto i get stranded on the readiness check
This was now an issue before. Before it passed the readiness test. 

this error comes up:
"Error from Updater Application Cron Script:
Found non-writable path(s):
../public_html/magento2/app/design/adminhtml/Magento"

I have looked in the folder it ask.. I have the magento2/app/design/adminhtml/
But I have no subfolder nor file called Magento (the folder /adminhtml/ is empty)

I dont understand why this error was not there before and now it is?
I could use some advice in how to get pass it so I can install extensions and upgrade again?

Please help !

**Comment by magento-engcom-team** [comment]
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
