### ISSUE TITLE
Braintree/PayPal Exceptions

### ISSUE THREAD

**Issue by cbend** [magento/magento2#12653]
Payment gateways like Braintree and PayPal should be throwing exceptions that are instances of \Magento\Framework\Exception\PaymentException, but they are not.

### Preconditions
1. Affects all versions of Magento 2

### Expected result
1. Braintree/PayPal will throw PaymentException (or exceptions extending PaymentException) for error handling purposes.

### Actual result
1. Braintree and PayPal throw Exception, LocalizedException, etc.

**Comment by YevSent** [comment]
Hi, @cbend, Braintree, PayPal Braintree and PayPal PayflowPro based on [Magento Payment Gateway](http://devdocs.magento.com/guides/v2.2/payments-integrations/payment-gateway/payment-gateway-intro.html) and throw `\Magento\Payment\Gateway\Command\CommandException`. So, this is expected behavior.

I'm closing this ticket as not an issue.

**Comment by cbend** [comment]
Hi @joni-jones,

I am referring to Braintree errors like **throw new Exception('No available payment tokens')**, which can be found in `\Magento\Braintree\Gateway\Command\GetPaymentNonceCommand::execute`.

Thanks

**Comment by YevSent** [comment]
This exception more for developers but not for customers because on that step it's extraordinary situation.

**Comment by cbend** [comment]
@joni-jones ,

Here are some better examples:

`\Magento\Payment\Model\Method\Adapter->validate()`

```
public function validate()
    {
        try {
            $validator = $this->getValidatorPool()->get('global');
        } catch (\Exception $e) {
            return $this;
        }
 
        $result = $validator->validate(
            ['payment' => $this->getInfoInstance(), 'storeId' => $this->getStore()]
        );
 
        if (!$result->isValid()) {
            throw new LocalizedException(
                __(implode("\n", $result->getFailsDescription()))
            );
        }
 
        return $this;
    }
```
`\Magento\Braintree\Gateway\Command\GetPaymentNonceCommand::execute`

```
if (!$result->isValid()) {
            throw new Exception(__(implode("\n", $result->getFailsDescription())));
        }
```

`Magento\Paypal\Model\Payflow\Service\Response\Validator\ResponseValidator`
` throw new LocalizedException(__('Transaction has been declined'));`

**Comment by YevSent** [comment]
> try {
$validator = $this->getValidatorPool()->get('global');
        } catch (\Exception $e) {
            return $this;
        }

Not a payment exception, but infrastructure. This validation is not used by Payment Gateway but is used by Quote and Sales modules.

> throw new LocalizedException(
                __(implode("\n", $result->getFailsDescription()))
            );

Does not relate to Payment Gateway infrastructure and could be processed by Quote and Sales modules.
Both previous exceptions do not relate to Braintree and PayPal.

> throw new Exception(__(implode("\n", $result->getFailsDescription())));

Must not be shown for a customer and will be just logged.

> Magento\Paypal\Model\Payflow\Service\Response\Validator\ResponseValidator
throw new LocalizedException(__('Transaction has been declined'));

Will be caught by PayflowPro Gateway commands, without commands doesn't make sense.
