### ISSUE TITLE
Invalid parameter configuration provided for $block argument upon no ACL permissions to the block

### ISSUE THREAD

**Issue by Tomasz-Silpion** [magento/magento2#12660]
### Preconditions

1. Reproduced on clean magento 2.2.0, 2.2.1 and 2.2.2 (current develop branch)

### Steps to reproduce

1. Create new admin user role with customer tab permissions only
2. Assign new admin user to the role
3. Login as the user
4. Try to create new customer

![acl](https://user-images.githubusercontent.com/5328659/33915118-e9a2d024-dfa1-11e7-914c-647febb5293b.png)

### Expected result

1. New customer form is shown

### Actual result

1. Invalid parameter configuration provided for $block argument of Magento\\Ui\\Component\\HtmlContent" exception is thrown

customer_form.xml addons restricted to selected ACL  permissions such as Newsletter/view/base/ui_component/customer_form.xml prevent htmlContent block from being created causing boolean passed to Magento\Ui\Component\HtmlContent constructor which demands block to be an instance of BlockInterface

**Comment by magento-engcom-team** [comment]
@Tomasz-Silpion, thank you for your report.
We've created internal ticket(s) MAGETWO-85576 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @Tomasz-Silpion 
We are closing this issue now as the fix has been delivered with the commit 3839c0f and should be released with 2.2.4
Thank you.
