### ISSUE TITLE
Custom Customer Fields not saving when caches off

### ISSUE THREAD

**Issue by leedave** [magento/magento2#12664]
When using custom attributes in customers, the save mechanism in adminhtml can only save custom attributes if the Magento caches are active. Otherwise the fields will be deleted if existing. 

### Preconditions
1. Detected on Magento 2.1.3 using Apache 2.4.6, PHP 7 and MySQL 5.6.29
2. All Magento caches are deactivated
3. Customer fields have been extended by personal code or 3rd party extensions

### Steps to reproduce
1. Log into adminhtml
2. Disable all caches
3. Edit a customer, add data to custom attributes
4. Save customer

### Expected result
1.  Data in custom fields should be updated in database tables customer_entity_* and customer_grid_flat

### Actual result
1. New data is not saved, existing data is deleted from the DB

**Comment by magento-engcom-team** [comment]
@leedave thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by leedave** [comment]
@magento-engcom-team 
There seems to be some misunderstanding here. My Report is based on Magento Open Source, not Magento Commerce/Enterprise Edition. It is also not a support enquiry, I'm not asking for help, I'm supplying you a bug report, so you can decide if you'd want to fix this in future.
