### ISSUE TITLE
Add a 'Default Product Listing Sort Direction' field to the categories

### ISSUE THREAD

**Issue by hostep** [magento/magento2#1266]
Hi

Right now (0.74.0-beta8) you can choose a default sort attribute per category in the backend using the 'Default Product Listing Sort By' field.
But you can't determine what the default direction should be. I believe currently the default one is always ascending.
But sometimes a store owner wants the default sorting direction to be descending.

So our suggestion is to add a 'Default Product Listing Sort Direction' field to the categories where you can choose 'ascending' or 'descending'.
(If I remember correctly, you can do it using a 'Custom Layout Update', but that's not very user friendly)

Thanks!

**Comment by katmoon** [comment]
Hi,

Smart sorting in catalog is a Magento Enterprise feature.
So I'm closing this issue since nothing will be done regarding this issue in CE. Feel free to reopen the issue if you still have any questions.

Thanks, Kateryna.
