### ISSUE TITLE
Readme.md update

### ISSUE THREAD

**Issue by 4quaternion** [magento/magento2#12676]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by 4quaternion** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@4quaternion Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by 4quaternion** [comment]
#mageconf

**Comment by 4quaternion** [comment]
#mageconf

**Comment by 4quaternion** [comment]
#mageconf

**Comment by 4quaternion** [comment]
#mageconf

**Comment by 4quaternion** [comment]
#mageconf

**Comment by 4quaternion** [comment]
#mageconf

**Comment by ishakhsuvarov** [comment]
Test #mageconf

**Comment by ishakhsuvarov** [comment]
Test #mageconf

**Comment by 4quaternion** [comment]
#mageconf

**Comment by magento-team** [comment]
@4quaternion thank you for joining. Please accept team invitation [here]() and self-assign the issue.

**Comment by ishakhsuvarov** [comment]
#mageconf

**Comment by magento-team** [comment]
@4quaternion thank you for joining. Please accept team invitation [here]() and self-assign the issue.

**Comment by 4quaternion** [comment]
#mageconf

**Comment by magento-team** [comment]
@4quaternion thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by 4quaternion** [comment]
#mageconf

**Comment by magento-team** [comment]
@4quaternion thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by 4quaternion** [comment]
#mageconf

**Comment by magento-team** [comment]
@4quaternion thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ishakhsuvarov** [comment]
#mageconf
