### ISSUE TITLE
Magento 2.2.0 - Klaviyo Integration Issue

### ISSUE THREAD

**Issue by ProofMaker** [magento/magento2#12670]
The Magento 2 store seems to be integrated correctly: both API keys are in, Klaviyo extension is installed, sync is active - "Started Checkout" metric is showing activity.
But when I try to display products in cart using dynamic variables - it just shows empty space in place of products: no image, no text.
Please contact me directly.

Preconditions
1. Chrome 63.0.3239.84 (Official Build) (64-bit)
2. Magento 2.2.0
3. Klaviyo Extension Installed
4. Public & Private API keys ready
5. Integration seems to be working - purchases are constantly shown in Klaviyo
6. Store website - Contact me

Steps to reproduce (Klaviyo)
1. I create a new email in Klaviyo based on the "Started Checkout" Magento 2 trigger (metric)
2. I use the dynamic variables, seen in Klaviyo's email Preview mode, with and without Repeat block feature, - like {{ event.Items.0.Name }}, {{ event.Items.0.Product.Images.0.URL }} (or {{ Item.Product.Images.0.URL }} if using Repeat feature with "item" alias for event.Items)
3. I Preview the email

Expected result
1. Customer's cart content is shown (image, name, price, quantity)

Actual result
1. Nothing is shown in place of the cart content (https://www.screencast.com/t/QPGuU3Oa3B)

(Can it be connected to the store' transition process from Shopify to Magento 2? Why no data is actually sent to Klaviyo?)

**Comment by magento-engcom-team** [comment]
Hi @ProofMaker please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
