### ISSUE TITLE
Plugin idea useless?

### ISSUE THREAD

**Issue by Michal-sk** [magento/magento2#1267]
I am starting to do more and more in M2. Loving and hoping to utilizes the concept of the Plugin system, is started to do some stuff. But after some time im starting to see more and more the limitation of the protected and private methods... Most methods is would like to use the Plugin for are protected which makes the whole concept useless.

Am i the only one facing this issue?

**Comment by alankent** [comment]
Could you give an example or two of methods you would like to use plugins on?

**Comment by Michal-sk** [comment]
Ok, so for example. Just before i wrote this issue i wanted to add a Tab on the User / Edit page. Looking trough the code and seeing: ```\Magento\User\Block\User\Edit\Tabs::_beforeToHtml```. Would be great if we could just do ```afterBeforeToHtml``` and we would be done. Custom Tab added.

This is just an example which just happend, but in the past couple of days i've had this more and more.

**Comment by kandy** [comment]
Problem that you describe is not problem of plugin, it is classical issue of code composition. Tabs component combines two responsibilities: tabs rendering and tabs management. If do splitting of responsibilities then problems with the plug-ins will not be.

But if you wants add tab now, you can use: 
 - layout to add tab (proper way)
 - plugin on `\Magento\User\Block\User\Edit\Tabs::assign` method

**Comment by Michal-sk** [comment]
Thanks for the reply. I will look in to it.
