### ISSUE TITLE
Shipping Price after discount

### ISSUE THREAD

**Issue by sambalay** [magento/magento2#12682]
Hi,
magento version - 2.1.8 we are doing free shipping over 50$.

In checkout shipping step , customer is selecting 0.00 (free shipping) since it is above 50$

In payment section , they are applying promo code where subtotal is below 50$ but shipping charge still shows 0.00

They should be charged 8.12 ground shipping charge.

![capture-discount](https://user-images.githubusercontent.com/30907888/33946442-ce8426a0-dfef-11e7-9b24-02a2b5658ea2.PNG)

**Comment by okorshenko** [comment]
Thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by sambalay** [comment]
First enable free shipping method with minimum order amount as 50$

Then add products to cart for example subtotal is 60

Then proceed to checkout 

Enter shipping info and select FREE shipping method (since it is above 50$)

Then Apply Coupon 20% OFF - which brings down subtotal below 50$

But Shipping method is still shows FREE, it should calculate on subtotal after discount

Expected result - it should change to Ground Shipping or any other shipping method or they should go back and select method again.

**Comment by magento-engcom-team** [comment]
Thank You @sambalay. You are right: shipping methods must be bound to the Cart's Subtotal. And in fact it is. Notice, please, that in the case You described above, after the coupon has been applied the Subtotal remains the same - 60. It is the Total that is changed to 50$. So You need to adjust Your Free Shipping Amount or rebate price rules considering that. You may try to use condition combinations in Your cart price rule, apply several cart price rules or try something with catalog price rules to achieve the result that will suit You.

**Comment by magento-engcom-team** [comment]
@sambalay, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
