### ISSUE TITLE
Magento 2.2.2 update gives error 500

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#12683]
After I updated from Magento 2.2.1 to 2.2.2 my Website is not working any longer. Its giving internal server error 500.

**Preconditions**

Magento 2.2.2
PHP 7.0.

**Steps to reproduce**

Go to admin and load web setup wizard to upgrade magento 2.2

**Expected result**

Website should load without any errors

 **Actual result**
![error](https://user-images.githubusercontent.com/13229022/33963513-43fecdc2-e0a9-11e7-9399-68e4de85640a.jpg)

**Comment by terrybakshi** [comment]
![3e90a57b1eaa793f26ca80a35a393ef6363800d00059bdf0f7 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/13229022/33977112-69f1a060-e0ed-11e7-9ee3-cc2f27aa41fe.png)

**Comment by tonybrown85** [comment]
@magento-engcom-team I'm experiencing the same issue when upgrading from 2.2.1 to 2.2.2. 500 Internal Server Error. Renaming the .htaccess file will then allow the page to load but all the file assets 500 anyway. Any help to get this resolved asap would be greatly appreciated as we need to upgrade to the latest version for all the fixes and enhancements. Thanks, Tony

**Comment by webazad** [comment]
Facing same problem

**Comment by bvboas** [comment]
I had the same problem.

The issue was with apache. It did not have the module "mod_version" installed. 

Also, you might want to replace 

```
############################################
## adjust memory limit
    php_value memory_limit 756M
    php_value max_execution_time 18000

############################################
## disable automatic session start
## before autoload was initialized

    php_flag session.auto_start off

############################################
## enable resulting html compression

    #php_flag zlib.output_compression on

###########################################
## disable user agent verification to not break multiple image upload

    php_flag suhosin.session.cryptua off

```


with

```
<IfModule mod_php5.c>
############################################
## adjust memory limit
    php_value memory_limit 756M
    php_value max_execution_time 18000

############################################
## disable automatic session start
## before autoload was initialized

    php_flag session.auto_start off

############################################
## enable resulting html compression

    #php_flag zlib.output_compression on

###########################################
## disable user agent verification to not break multiple image upload

    php_flag suhosin.session.cryptua off
</IfModule>
```

**Comment by magento-engcom-team** [comment]
@terrybakshi , thank for you report. 
When facing a 500 error the first thing you should do is search for your webserver error log. When running on apache it can mostly be found in one of these 2 locations:
/var/log/httpd/ -> centos, archlinux ...
/var/log/apache2/ -> debian, ubuntu ...

**Comment by tonybrown85** [comment]
Thank you @bvboas I will give that a try. Much appreciated!

**Comment by terrybakshi** [comment]
was able to fix the issue by turning on the module "mod_version" on apache no more error 500 while update or on checkout page so far

**Comment by magento-engcom-team** [comment]
@terrybakshi , thanks for you update.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by Almusamim** [comment]
@bvboas thanks.. I uncommented mod_version and it works now :) 
Took me few hours to solve this :/

**Comment by gino-g** [comment]
unfortunately, I don't have have access to apache module on my hosting and I can't change or enable mod_version.
Hoe can i resolve it?

**Comment by bvboas** [comment]
@gino-g edit the .htaccess file and find the code similar to (there are multiple instances):

```

    <Files auth.json>
        <IfVersion < 2.4>
            order allow,deny
            deny from all
        </IfVersion>
        <IfVersion >= 2.4>
            Require all denied
        </IfVersion>
    </Files>
```

If your apache version is equal or greater to 2.4, leave these lines:

```
    <Files auth.json>
            Require all denied
    </Files>
```
If your apache version is lower than 2.4, leave these lines:

```
    <Files auth.json>
            order allow,deny
            deny from all
    </Files>
```

**Comment by gino-g** [comment]
@bvboas 
Hi,
Thank you for a quick response but unfortunately for me, even after removing the section 1
   <Files auth.json>
            Require all denied
    </Files>
(my apache is 2.4.3-25) it did not work.

Changed my php to 7.1, even that did not help.
My upgrade was smooth and I can still execute all SSH commands but i wonder what went so wrong?

Any help getting it up would really mean a lot ..
Thank you again.

**Comment by gino-g** [comment]
Hi,
I tried generating the same error on my localhost by commenting mod_version and I was not able to get the same 500 Internal server Error.
So, I am really not sure it is this one thing which is holding back the webpage..

Can someone guide me?

**Comment by paginasweb** [comment]
you are the boss, mod_version was the issue , thanks

**Comment by Jamesyahugh** [comment]
cPanel Solution
![cPanel Solution](https://image.ibb.co/nstxq7/Capture.png)

**Comment by Ctucker9233** [comment]
This still exists on 2.2.4...I can't find mod_version and I'm hosted with siteground. Any advice?

**Comment by Ctucker9233** [comment]
@magento-engcom-team This is still an issue. I checked with my hosting service and they tell me that the server is configured correctly.

**Comment by terrybakshi** [comment]
To Enable Apache or PHP Modules Using EasyApache
Log in to WHM as the 'root' user.
In the Find box type easy.
Click EasyApache (Apache Update).
Leave default, and then click the gear icon (Customize Profile).
Leave default, and then click Next Step.
Click Exhaustive Options List.
Click the name of the Apache or PHP module, and then click Save and build.

**Comment by Karanp13** [comment]
Please try to remove unnecessary data from .htaccess, You will defensively solved.

**Comment by ghost** [comment]
@terrybakshi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by binamandiri** [comment]
> 
> 
> I had the same problem.
> 
> The issue was with apache. It did not have the module "mod_version" installed.
> 
> Also, you might want to replace
> 
> ```
> ############################################
> ## adjust memory limit
>     php_value memory_limit 756M
>     php_value max_execution_time 18000
> 
> ############################################
> ## disable automatic session start
> ## before autoload was initialized
> 
>     php_flag session.auto_start off
> 
> ############################################
> ## enable resulting html compression
> 
>     #php_flag zlib.output_compression on
> 
> ###########################################
> ## disable user agent verification to not break multiple image upload
> 
>     php_flag suhosin.session.cryptua off
> ```
> 
> with
> 
> ```
> <IfModule mod_php5.c>
> ############################################
> ## adjust memory limit
>     php_value memory_limit 756M
>     php_value max_execution_time 18000
> 
> ############################################
> ## disable automatic session start
> ## before autoload was initialized
> 
>     php_flag session.auto_start off
> 
> ############################################
> ## enable resulting html compression
> 
>     #php_flag zlib.output_compression on
> 
> ###########################################
> ## disable user agent verification to not break multiple image upload
> 
>     php_flag suhosin.session.cryptua off
> </IfModule>
> ```

this is works, thanks you

**Comment by imranbashirseo** [comment]
hi
i am facing error on magento 2 for installation on my vps my mod_version is also enable which i enable through WHM but when i am renaming my htaccess on my vps installation running but css and other settings nothing showing as pr theme however this theme is working fine on my localhost

i am sharing my htaccess which is on live anyone can help me plz?
[htaccess(1).zip](https://github.com/magento/magento2/files/3909870/htaccess.1.zip)
