### ISSUE TITLE
dist front: search is broken 

### ISSUE THREAD

**Issue by maboiteaspam** [magento/magento2#1268]
Using option
``` Use in search results layered navigation``` : Yes

The dis front provided will bug when hit ``` /index.php/catalogsearch/result/?d=+test ```

Respond,
```Fatal error: Call to member function getValues on non Object....``` IE missing assertion.

BTW, this error happened really often until now.

**Comment by kokoc** [comment]
@maboiteaspam Thank you for reporting the issue. Internal reference: MAGETWO-37363

**Comment by kokoc** [comment]
@maboiteaspam The fix now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?

**Comment by maboiteaspam** [comment]
we switched back to magento 1. We was facing too many problems and difficulties with this new version. Let see in few betas.

**Comment by alankent** [comment]
If you were considering going live, absolutely the recommendation is to stick with Magento 1 for now. Magento 2 won't be GA until Q4. The product is under going active development. Magento 1 is going to be around for many years to come.
