### ISSUE TITLE
Hi, I think that there might be a problem with my Magento.2.1.3 site. When I try to save any alterations to a product nothing happens. I don't an error message, just click and it does nothing. When I try to import new stock it says this message 'Please make sure attribute "style" is not empty. in row(s): 1,2', but I can't see this attribute in any sample import. Also we've had no sale on the site since the 8th of December. Our hosting team have had a look into it and although they think something strange is happening they can't see anything wrong from the control panel end. Does anyone know what might be going wrong.

### ISSUE THREAD

**Issue by bevtew** [magento/magento2#12689]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by okorshenko** [comment]
We are closing this issue. 
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, create an issue with description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result
