### ISSUE TITLE
Cart Price Rule for configurable products

### ISSUE THREAD

**Issue by bmisyura** [magento/magento2#12697]
### Preconditions

Install Magento from 2.2.-develop branch

 ### Steps to reproduce

 - Create two configurable products with children SKU-A, SKU-B
 - Create Cart Price Rule with type _Specific Coupon_
 - Go to Actions tab and set discount 70%
 - Setup Apply the rule only to cart items matching the following conditions (leave blank for all items).
        - If ALL  of these conditions are TRUE :
        - SKU  is not one of  SKU-A
 - Go to frontend and add two created configurable products into the cart
 - Apply coupon code

### Expected result

 - Discount is applied only on 1 item.

### Actual result

 - Discount is applied to both items

**Comment by vadim4err** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@vadim4err thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by vadim4err** [comment]
Cannot reproduce the bug. After applying coupon code. The coupon code "xxx" is not valid. Coupon code set to empty in _validateCouponCode() in Magento/Quote/Model/Quote/TotalsCollector.php

**Comment by guillaumecochard** [comment]
Hi, I reproduce the issue on magento 2.2.3 do you know if I can apply a fix for it ? Thanks !
