### ISSUE TITLE
Magento 1.9.2 Paypal mobile issue

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#12691]
### Preconditions

1. Magento 1.9.2.1
2. PHP Version 5.6.32 
3. all mobile device (Android / IOS ) 

### Steps to reproduce

1.  Add products to cart in mobile, and pay via paypal button (using default magento paypal module )
2.  In mobile when I have tried to checkout its asking me to open paypal via paypal app
3. This is not asking for other sites

### Expected result

4.  I need to open paypal in any mobile browser not in paypal app 

### Actual result

1. mobile when I have tried to checkout its asking me to open paypal via paypal app
2. How to prevent Mobile context box (Open with paypal option)
3. [Screenshot, logs]
![screenshot_20171214 123353 png png image 1080 x 1920 pixels scaled 51](https://user-images.githubusercontent.com/6543606/33982658-452d3048-e0d7-11e7-80d2-cde26a1d9743.png)

**Comment by magento-engcom-team** [comment]
@aasim110 , thank for you report. Check please for this issue is still actual for latest 2.1.x or 2.2 release.
