### ISSUE TITLE
Magento

### ISSUE THREAD

**Issue by swarishna** [magento/magento2#12693]
All admin menu link don't work and have a strange icons. Why? I can't do anything

**Comment by magento-engcom-team** [comment]
@swarishna Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by swarishna** [comment]
How to integrate the new theme?

**Comment by magento-engcom-team** [comment]
@swarishna please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
