### ISSUE TITLE
magento dashboard revenue ,shipping ,qty,tax all are 0.

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1269]
I have orders (some are completed,progress,pending).But in dashboard its showing revenue ,shipping ,qty,tax all are 0.

**Comment by kokoc** [comment]
@sivajik34 Thank you for reporting the issue. Internal reference: MAGETWO-37325

**Comment by kokoc** [comment]
@sivajik34 The fix is now available in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2! Could you please verify the issue?
