### ISSUE TITLE
Unable to save "State is Required for" multiselect with all options unchecked

### ISSUE THREAD

**Issue by bmisyura** [magento/magento2#12703]
### Preconditions

1. Install Magento from 2.2-develop or 2.3-develop branch

### Steps to reproduce

1. Go to Store>Configuration>General>State Options
2. In the 'State is Required for' list make sure no options are selected
3. Save configuration

### Expected result

1. Last checked options still selected

### Actual result

1. No options should be selected

**Comment by Sorbog** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@Sorbog thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Delta** [comment]
@bmisyura @Sorbog Unfortunately, I am not able to reproduce issue by steps you described on 2.4-develop
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
