### ISSUE TITLE
PayPal Billing/Shipping missing on Virtual orders

### ISSUE THREAD

**Issue by josephmcdermott** [magento/magento2#12707]
This is a new ticket to re-open https://github.com/magento/magento2/issues/5873 since that ticket has been closed when there is still a major issue. Here are my consolidated comments from the previous ticket:

This is very easy to replicate with a clean Magento:

- install Magento 2.2.0 with sample data (or 2.2.1, but I happened to try with 2.2.0)
- add sandbox paypal credentials in the admin panel
- purchase product ID 51 (downloadable) using PayPal Express
- note that the order has no billing or shipping address data saved
- also note that when viewing the order in the admin panel, the billing address appears as the address template rather than the customer's address (which was not captured). This is the same in the printed invoice and in the customer account area.

I've been doing a bit of debugging of this, and I'm not actually sure its a bug per se. The fact that the billing address appears as {{depend prefix}}{{var prefix}} is a symptom of the issue for Magento to resolve, however the actual issue is perhaps that PayPal does not require, nor does it request, a billing address to complete an order.

The shipping and billing addresses associated to the quote are both empty during checkout with PayPal express, and you will notice that with other payment methods such as CheckMo you are asked for your billing address on the payment step, however with PayPal you are not asked any billing information. For virtual orders there is also no requirement for a shipping address, so neither are captured.

It's a bit annoying as we are left with a situation where we have zero address information about a customer for invoicing purposes, but perhaps this is by design...

Can @magento-engcom-team team comment on that? Was this a decision made by PayPal to restrict customer billing/shipping information visibility?

**Comment by giacmir** [comment]
I have the same issue. Every purchase of virtual quotes with paypal print the address template instead of the address information in admin order view page.

**Comment by aeu** [comment]
I am seeing this issue as well.  I believe that it is by design, as it appears that when the product is Virtual, Magento does not capture any address information (because there is no product to ship).  

Superficially this seems like a good idea, but as @josephmcdermott pointed out, this leaves us in a situation where we have no address information for billing / invoicing purposes.

**Comment by ghost** [comment]
I am seeing this issue for my virtual products everytime. How i can fix that?

Magento 2.2

![Image](https://i.imgur.com/Ki5flDw.png)

**Comment by digitalredefined** [comment]
Out of curiosity - are these stores configured as stand alone stores?  I'm currently migrating a handful of stores for a client and the only one I've ran into this with is set up as stand alone.

**Comment by czettnersandor** [comment]
Same problem here. This looks like a javascript bug as the address form is not showing at all when I fill the billing address and then refresh the page or apply a discount.

**Comment by magento-engcom-team** [comment]
**Steps to reproduce this issue:**

1. Configure PayPal Express.
2. Create downloadeble product.
3. Create customer without billing or shipping address and login in.
4. Add downloadable product to cart.
5. Proceed to checkout.
6. Choose PayPal Expres payment method.
7. Place order.
8. Open created order in backend.

**Actual result:** The billing address wrong appears as {{depend prefix}}{{var prefix}}.

**Comment by magento-engcom-team** [comment]
@josephmcdermott, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mikeschommer** [comment]
We are seeing same results even with Require Customer's Billing Address = Yes and PayPal billing address feature enabled in our merchant account. The only way we are able to get a billing address in there is if the customer clicks the "update" button before continuing the PayPal Checkout. 

![1](https://user-images.githubusercontent.com/756836/39627548-4699dcb8-4f74-11e8-990c-248cb120c9e5.png)

**Comment by hackronshins** [comment]
Is this bug fixed yet, Still I am also facing this issue for paypal orders in back-end on billing information it is displaying prefix variables as template.
**Replication steps:**
1. Add product to the cart
2. Proceed to checkout
3. Using Paypal express payment method
4. Place the order
5. Lets check in backend in admin
6. Open Sales -> Orders
7. Open recent order with order id
8. See the billing information

**Magento Version 2.3.1
Payment Method Paypal express (Card payment).**

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-12707-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-12707-2-4-develop.instances.magento-community.engineering/admin_9743](https://i-12707-2-4-develop.instances.magento-community.engineering/admin_9743)
Login: `824624c5` Password: `62b095d82f50`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-12707-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-12707-2-3-5-p1.instances.magento-community.engineering/admin_0cc5](https://i-12707-2-3-5-p1.instances.magento-community.engineering/admin_0cc5)
Login: `3f5dd38a` Password: `2f94e78cc687`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
@hackronshins , I'm not able to reproduce issue by steps you described on clean 2.4-develop. 
Was checked cases with virtual and downloadable products
**Manual testing scenario:**
1. Create two products ( Virtual and downloadable ) 
![1](https://user-images.githubusercontent.com/51681379/96835435-3f7a9400-144c-11eb-85ab-a0501416fe58.png)
2. Set up PayPal Express checkout 
3. Navigate to storefront as a guest
4. Place order with virtual product using PayPal Express checkout 
5. Login as a customer 
6. Place order with downloadable product using PayPal Express checkout 
**Result:**
- :heavy_check_mark: Billing information is displayed in My account->My Orders on storefront
![2](https://user-images.githubusercontent.com/51681379/96835833-c7609e00-144c-11eb-8389-89456fb3d4d1.png)

- :heavy_check_mark: Bill-to Name is present for orders with Virtual and Downloadable products in admin panel
![3](https://user-images.githubusercontent.com/51681379/96835994-0858b280-144d-11eb-8af5-9fd61e262893.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
