### ISSUE TITLE
Magento order grid not updated after API status updates

### ISSUE THREAD

**Issue by bmisyura** [magento/magento2#12701]
With Asynchronous Grid Indexing status updates to an order via the Magento 2.2 APIs are not reflected in the order grid.

### Preconditions

 
Install Magento from 2.2.-develop branch

### Steps to reproduce

1. Enable Asynchronous Indexing in Stores > Configuration > Advanced > Developer > Grid Settings
2. Create a new order
3. Add status update via API call, e.g., 

> /rest/V1/orders/{orderId}/comments
 {
"statusHistory": {
"comment": "Updating status",
"is_customer_notified": 0,
"is_visible_on_front": 0,
"status": "processing"
}
}
 

4. Go to Sales > Orders and search for the order from the grid - take note of the status
5. Open the order and compare the status with the status from the grid

### Expected result

Order statuses in the grid and on its edit page are different.

### Actual result

The statuses should be the same.

**Comment by eugene-shramko** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@eugene-shramko thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by eugene-shramko** [comment]
Hey @bmisyura,
The issue is not reproduced on Magento 2.2 (2.2-develop branch).
Could you please confirm the issue still exists?

**Comment by alena-marchenko** [comment]
Confirmed, the issue is not reproducible on 2.2-develop branch.

**Comment by samzhou2** [comment]
reproduced on 2.2.4
