### ISSUE TITLE
Ajax loader hangs when creating product with custom Attribute Set

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12709]
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Create new Attribute Set based on Default
- create new group "inventory"
- move attributes "price", "quantity_and_stock_status" to "inventory" group
3.  Save new attribute set 

### Steps to reproduce
1. Login to Admin
2. Go to Catalog > Products
3. Click **Add Product** button
4. Switch to attribute set created in preconditions

### Expected result
Product page is loaded, there is ability to fill in product data.

### Actual result
The ajax loader keeps spinning. There is no ability to fill in product data.

**Comment by michael1986** [comment]
#mageconf

**Comment by torvik23** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@michael1986 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
@torvik23 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ghost** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@sergeysikachev thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by EviNoita** [comment]
#mageconf

**Comment by EviNoita** [comment]
**Product solution:** is forbidden to move price, sku and name to other groups for attribute sets. 
**Need fix:** prohibit the move of these attributes to another group, and display an error message.

**Comment by briscoda** [comment]
Would like to work on this one.
