### ISSUE TITLE
url_path not updated in category save in multi view store when url_key same as default url_key

### ISSUE THREAD

**Issue by george-vlahakis** [magento/magento2#12718]
When changing/setting a category url_key on save the url_path is updated to match the change. However, and I will try to make this as clear as possible ...

If you are changing the category url_key in a store view which is **not** "all" and the value of the url_key matches the value set under the "all" store view then the url_path entry is not updated.

Scenario:
A store with two store views (english, french).

**With store view = "All store views" (id:0)**
  Create a category under root named "**Test**" and set it's url_key = "**test**".
**Switch to store view = "English" (id:1)**
  Set the category's url_key = "**test2**" 
  (Up to here expected behavior, the url_path for this store view is set to "**test2**")

_Staying in store view = "English"_
  Set the category's url_key = "**test**" (matching the "all" store view value)
  Break: url_path is not changed to "test" and remains "**test2**" !

### Preconditions
1. Magento 2.2.0
2. MySQL 5.6.35
3. PHP 7.1.8

### Steps to reproduce
_Described above_

### Expected result
1. The url_path should be updated regardless on if the "all" view has the same value as the value being set in this view.

### Actual result
1. url_path remains unchanged breaking all url_rewrites and sub-categories

Screens of the results in db after playing about with category (4270):

Store 0 respects the change:
![image](https://user-images.githubusercontent.com/13225297/34007959-6ec7912a-e10c-11e7-80e7-303fa20ffb65.png)

Store 1 ignores the change when setting value same as store 0:
![image](https://user-images.githubusercontent.com/13225297/34007985-8a005d32-e10c-11e7-8209-241474745f00.png)

**Comment by magento-engcom-team** [comment]
@georgios-2317, thank you for your report.
We've created internal ticket(s) MAGETWO-85710 to track progress on the issue.

**Comment by iop** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@iop thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by okorshenko** [comment]
@iop thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by george-vlahakis** [comment]
Thank you for confirming guys.

For anyone else out there facing the same issue, the only work-around I can see is to give a temporary url_key for store:0, go ahead and change store:1 url_key and then go back to store:0 with the old url_key (matching store:1)

**Comment by george-vlahakis** [comment]
Please also note that the bug reported within effects functionality of "Use Default Value" as well. I have reported a separate bug for "Use Default Value" fields which effects the whole system (null versus missing value in db).

If @iop can figure this out as well would be great given they closely related.

**Comment by hostep** [comment]
Confirmed, we also see this issue happening on a Magento 2.1.11 installation.
The workaround mentioned above works, but is annoying to have to perform if you have a lot of categories and storeviews which exhibit this problem.

Would be great if this issue could get a somewhat higher priority if possible. Thanks! :)

**Comment by igorwulff** [comment]
Hi @chohanbhagchand is there any progress on this issue? It is causing quite some issues with our client projects.

**Comment by BarnyShergold** [comment]
Please keep me updated too @chohanbhagchand - it's been 5 months since you assigned this - how is it progressing?

**Comment by nwtben** [comment]
is this still an issue in 2.4.x?

**Comment by hostep** [comment]
I've just tested this on a clean Magento 2.3.6 and 2.4.1 installation and the issue no longer occurs. No idea when and how it got fixed.

Issue can be closed I believe.

**Comment by sdzhepa** [comment]
Thank you @hostep
