### ISSUE TITLE
Import doesn't allow to set default value per store view (dropdown fields)

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12716]
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Two store views are created (english and chinese)
3. Products are imported from attached file 
[import_productsoftwostoresdata.csv.zip](https://github.com/magento/magento2/files/1560048/import_productsoftwostoresdata.csv.zip)

### Steps to reproduce
1. Log in to Admin
2. Go to Catalog > Products
3. Open product name4
4. Go to Advanced Settings > Auto Settings
5. Check Visibility field - it has value Catalog 
6. Switch store view to english or chinese

### Expected result
Field Visibility should have the same value as on Default store: Catalog

### Actual result
Field Visibility has value: Catalog, Search

Import file has empty value for this option per store views and it should be copied from default store.
The same issue with all dropdown fields (see also fields **Display Product Options In** in Design section )

**Comment by madbounce** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@madbounce thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by piotrekkaminski** [comment]
The issue was moved to https://github.com/magento-engcom/import-export-improvements/issues/91
