### ISSUE TITLE
Category return empty in magento2.2.1 after installing new theme.

### ISSUE THREAD

**Issue by Jawahar1994** [magento/magento2#12728]
### Preconditions

1. 
2. 

### Steps to reproduce

1. Call to a member function getTree() on null in C:\wamp64\www\magento3\vendor\magento\module-catalog\Plugin\Block\Topmenu.php on line 102

### Expected result

1.i want all category in the navigation menu.

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
