### ISSUE TITLE
Unable to translate strings using javascript dictionary

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12722]
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Default or Developer mode
3. 2 custom Store Views created and enabled
4. All indexers are valid
5. Different locales are set for each Store View, for example:
- **Ukrainian (Ukraine)** for the 1st custom Store View
- **French (France)** for the 2nd custom Store View 
- Leave **English (United States)** on Default Config level to be extended as a locale for Default Store View
6. Magento Cache is flushed if there is a need
7. Product visible for all Store Views is created
8. Put attached CSV files to Magento root folder
[source_fr_FR.csv.zip](https://github.com/magento/magento2/files/1560709/source_fr_FR.csv.zip)
[source_uk_UA.csv.zip](https://github.com/magento/magento2/files/1560711/source_uk_UA.csv.zip)
9. Run following in console:
- bin/magento i18n:pack --mode=replace -d source_uk_UA.csv uk_UA
- bin/magento i18n:pack --mode=replace -d source_fr_FR.csv fr_FR
- bin/magento setup:static-content:deploy en_US uk_UA fr_FR -f
- bin/magento setup:di:compile
- bin/magento deploy:mode:set production -s

### Steps to reproduce
1. Go to Storefront
2. Switch to Storeview with French locale
3. Open product page
4. Click **Ajouter au panier** to add the product to cart

### Expected result
Button changes to **Ajout...** while the ajax request is processing 
When the ajax requests is finished, the button changes to **Ajouté**
After a bit of time, the button changes back to **Ajouter au panier**

### Actual result
Default string **Adding...** appears instead of **Ajout...** 
Default string **Added** appears instead of **Ajouté**

**Comment by Tomasz-Silpion** [comment]
See https://github.com/magento/magento2/issues/8508 (I managed to resolve similar issue there with code left in comments) and https://github.com/magento/magento2/issues/10673

I believe it's already described as MAGETOTWO-72301 and there's already fix for the problem developed in https://github.com/magento/magento2/commit/fc34d7bf5afce2db5f6019dcb5c259e1178fb3dc

**Comment by andrewbess** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@andrewbess thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by okorshenko** [comment]
Hi @andrewbess please accept the invite https://github.com/orgs/magento/invitation

**Comment by andrewbess** [comment]
This bug is not reproduced following this steps.
But the system has another bug with translations.
It is a wrong translated string(s) for "fr_FR" locale.

Expected result:
Button changes to "En cours d'ajout..." while the ajax request is processing
When the ajax requests is finished, the button changes to "Produit ajouté"
After a bit of time, the button changes back to "Ajouter au panier"

Actual result:
Wrong translated string "Ajouter vos mots clés :" appears instead of "Produit ajouté"
Translated strings for "uk_UA" locale are correct.

Screenshots:
https://ibb.co/iemXem
https://ibb.co/e0QfX6

**Comment by ishakhsuvarov** [comment]
Closing this issue per comment above.
Ticket for updated translation issue: https://github.com/magento/magento2/issues/12782

**Comment by ishakhsuvarov** [comment]
@andrewbess Thank you for verifying the issue
