### ISSUE TITLE
in dashboard Last Orders items quantity showing wrong some times

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1272]
I have ordered configurable product with qty 1.but its showing as 2 dashboard Last Orders items quantity.is it right or bug?

**Comment by kokoc** [comment]
@sivajik34 Thank you for reporting the issue. Internal reference: MAGETWO-37398

Related issue: #1273

**Comment by vpelipenko** [comment]
@ sivajik34, fixed and available in 1.0.0-beta. Please, check the issue on this latest version.

**Comment by sivajik34** [comment]
thank you.its working fine
