### ISSUE TITLE
No action buttons in "View and Edit Cart" for configurable product

### ISSUE THREAD

**Issue by sandervall** [magento/magento2#12724]
### Preconditions
Magento 2.2.2
Linux, Apache

### Steps to reproduce
1. Add a configurable product to your shopping cart
2. Go to View ans Edit Cart page (/checkout/cart/)
3. Try to find Edit and Remove action links next to the configurable product

### Expected result
1.  You should be able to Edit or Remove the product

### Actual result
1. I have 2 configurable products in my cart and 1 virtual product.
The "View and Edit Cart" page displays action links only for the virtual product.
I manually added  log lines to \Magento\Framework\View\Element\AbstractBlock.php to the method getChildBlock around $layout->getBlock($name); (line 483) so it looks like this:

    public function getChildBlock($alias)
    {
        $layout = $this->getLayout();
        if (!$layout) {
            return false;
        }
	$this->_logger->info("Trying to get childName for ".$this->getNameInLayout(). " and with alias ".$alias);
        $name = $layout->getChildName($this->getNameInLayout(), $alias);
	$this->_logger->info("Got name ".$name);
        if ($name) {
            return $layout->getBlock($name);
        }
	$this->_logger->info("No block with name ".$name. " and with alias ".$alias);
        return false;
    }

The log output when opening the View and Edit Cart page is:
![33948535-c2dc277c-e02f-11e7-8d0b-46b89c4f70f4](https://user-images.githubusercontent.com/34515754/34022932-e76adc0c-e14a-11e7-9c8a-aeb962426554.jpg)

main.INFO: Trying to get childName for checkout.cart.form and with alias renderer.list [] []
main.INFO: Got name checkout.cart.item.renderers [] []
main.INFO: Trying to get childName for checkout.cart.item.renderers and with alias virtual [] []
main.INFO: Got name checkout.cart.item.renderers.virtual [] []
main.INFO: Trying to get childName for checkout.cart.item.renderers.virtual and with alias actions [] []
main.INFO: Got name checkout.cart.item.renderers.virtual.actions [] []
main.INFO: Trying to get childName for checkout.cart.form and with alias renderer.list [] []
main.INFO: Got name checkout.cart.item.renderers [] []
main.INFO: Trying to get childName for checkout.cart.item.renderers and with alias virtual [] []
main.INFO: Got name checkout.cart.item.renderers.virtual [] []
main.INFO: Trying to get childName for checkout.cart.item.renderers.virtual and with alias actions [] []
main.INFO: Got name checkout.cart.item.renderers.virtual.actions [] []
main.INFO: Trying to get childName for checkout.cart.form and with alias renderer.list [] []
main.INFO: Got name checkout.cart.item.renderers [] []
main.INFO: Trying to get childName for checkout.cart.item.renderers and with alias configurable [] []
main.INFO: Got name checkout.cart.item.renderers.configurable [] []
main.INFO: Trying to get childName for checkout.cart.item.renderers.configurable and with alias actions [] []
main.INFO: Got name  [] []
main.INFO: No block with name  and with alias actions [] []

The result is that the action button section in vendor/magento/module-checkout/view/frontend/templates/cart/item/default.phtml will not get any content.

**Comment by magento-engcom-team** [comment]
@sandervall Thanks for your report. We tried to reproduce it on the clean instance of Magento. And everything works fine. Could you please try to reproduce it on the clean instance of Magento? Or can you please clarify some steps in order for us to reproduce the issue. Thank you.
![7a92fdc6df29be36d8197e74c6f769a9affbeebde6761a6147 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/31669971/34034318-9e41c888-e186-11e7-9320-ea80cea85b66.png)

**Comment by sandervall** [comment]
Hi,

Tried a vanilla install and it's true - works in vanilla. So I started to add 3rd party modules to my vanilla and found out that Mageplaza GiftCard module overrides the default Configurable product renderer. Its config is in attachment.
![giftcard](https://user-images.githubusercontent.com/34515754/34044669-9162b2f8-e1ae-11e7-81e4-d118eb47090b.jpg)


This config removes the action buttons from the configurable product. Can you point me to the right direction how the config should look like (I guess the as="mpgiftcard" alias is the villain)

**Comment by magento-engcom-team** [comment]
@sandervall , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
