### ISSUE TITLE
Advance inventory values switch to original values in backend

### ISSUE THREAD

**Issue by sky4git** [magento/magento2#12725]
### Preconditions
1. Magento CE 2.2.2 
2. PHP 7.0

### Steps to reproduce
1. In product edit screen go to **Advanced inventory** 
2. Change the value of Maximum Qty Allowed in Shopping Cart (untick Use Config Settings)
![image](https://user-images.githubusercontent.com/8438024/34023060-f5b19264-e196-11e7-843a-e55cea226fc8.png)
3 Save the product. 

### Expected result
1.  Open the **Advanced inventory** for the product again new values should be visible.

### Actual result
1. Opening **Advanced inventory** again and it revert backs to default values.
![image](https://user-images.githubusercontent.com/8438024/34023135-520c3d66-e197-11e7-9f80-8ab12db12b77.png)
2: My changes are reflected in front-end though. 

I am not sure that it is a Magento's core bug or not, but I tried clearing all cache and re-indexing everything.

**Comment by magento-engcom-team** [comment]
Hello @sky4git. Currently we are not able to reproduce Your issue. Would You please try to reproduce it on a freshly installed, clear instance of Magento 2.2.2 CE. Thank You.

**Comment by sky4git** [comment]
# Update
You were right, its not happening on fresh installation. 

upon more research I found out, third party extension **Amasty_Rolepermisison** is responsible for it. 

Please close the issue.
