### ISSUE TITLE
Can't Close Pop-up Photo in Product View - Ipad Real

### ISSUE THREAD

**Issue by zin-mi** [magento/magento2#12726]
Hi Everyone,
I have to try to DEV Magento.  But I have the problem in Ipad Real with Photo Popup in Product view.
Magento Version is Magento CE 2.1.x  or above.
### Steps to reproduce

1.  Go to one product in Magento Details
2.  Click on Main Photo
3. Try to close but it not working. https://www.dropbox.com/s/snszgct78vefwzc/2017-12-15_10-49-10.png?dl=0
Please note this issue only problem on Ipad Real (I test in Ipad 3)

Please help me suggest to resolve this issue.
Best Regards,
Ziven.

**Comment by rafaelcalero** [comment]
This error is happening to me in 2 of my installations of magento 2.2.1.
It **does't only happen on iPads.**

You can **reproduce on any touch device or in Firefox enabling touch simulation** (Desktop mobile-development tool):

![problem-touch-magento2](https://user-images.githubusercontent.com/11404715/34054554-d36d6630-e1cb-11e7-8922-ce20f25a97cc.jpg)

**Comment by magento-engcom-team** [comment]
@zivendesign, thank you for your report.
We've created internal ticket(s) MAGETWO-86041 to track progress on the issue.

**Comment by amitsiliguri** [comment]
![t2](https://user-images.githubusercontent.com/39370641/40268265-e82137b0-5b87-11e8-840d-7b29d900579e.jpg)
before closing
![t1](https://user-images.githubusercontent.com/39370641/40268268-f20b8302-5b87-11e8-88d3-22f30939042d.jpg)
after closing
![t3](https://user-images.githubusercontent.com/39370641/40268272-fad4906e-5b87-11e8-9717-e553f19361d7.jpg)
same in case of Firefox enabling touch simulation
Easily close the pop-up image in all 3 cases.

**Comment by praveen1248** [comment]
Hi
This error is happening to me in 2 of my installations of magento 2.1.3.
It does't only happen on iPads and iPhones..

**Comment by folektoras** [comment]
@magento-engcom-team this does not seem to be an issue anymore. Tested on 2.3-develop brancfh on an iPad 3 Xcode Emulator
