### ISSUE TITLE
Customer section is not updated after cancelling subscription for newsletters

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12720]
### Preconditions
1. Magento is installed from 2.2-develop branch

### Steps to reproduce
1. Go to Storefront as a guest
2. Subscribe for news letters as not logged in customer
3. Login to Admin
4. Go to Marketing > Communications > Newsletter Templates
5. Create new Template
6. Run Cron Twice from console (bin/magento cron:run)
7. Check your email (The link will be similar to http://127.0.0.1:8000/newsletter/subscriber/unsubscribe/id/1/code/m6yqhnuabiyk962uqjaaecuu7cuvdm2y/)
8. Click unsubscribe link. 

### Expected result
You are redirected to Storefront, "You unsubscribed" message appears

### Actual result
You are redirected to Storefront, "You unsubscribed" message does not appear

**Comment by vasylmalanka** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@vasylmalanka thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by osrecio** [comment]
@alena-marchenko I think this problem occurs also in `2.3-develop` branch, the problem is related, according to my researches,  with FPC.
