### ISSUE TITLE
extra line item for configurable product in order view page.

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1273]
I have added 1 simple product & 1 configurable product to cart.and placed an order.
now in order view page total 3 line items are there.
first line item:config product price 0
second line item:config product item
third:simple

**Comment by kokoc** [comment]
@sivajik34 Thank you for reporting the issue. Internal reference: MAGETWO-37397

Related issue: #1272

**Comment by sivaschenko** [comment]
@sivajik34 Are you still able to reproduce this issue?

**Comment by okorshenko** [comment]
@sivajik34 ,  Please, let us know if you still have an issue
