### ISSUE TITLE
Cron Group-ID not considered during schedule cleanup

### ISSUE THREAD

**Issue by a-dite** [magento/magento2#12740]
In the following you can see a snippet from **\Magento\Cron\Observer\ProcessCronQueueObserver::_cleanup()** (Magento 2.1.10) . Different configurations from cron_group.xml are read (history_cleanup_every, history_success_lifetime, history_failure_lifetime) and considered in the code logic. The problem is, that the cleanup is executed, based on this configuration values, for cron_schedule entries of all groups, not only for those from the current group (method paramenter $groupId).  So if one has different configurations for success/failure lifetimes for cron groups in a project, the smallest values will win. I guess such a behavior is not wanted, as Magento offers the feature of separately configuring each cron group.

```php
/**
 * @var \Magento\Cron\Model\ResourceModel\Schedule\Collection $history
 */
$history = $this->_scheduleFactory->create()->getCollection()->addFieldToFilter(
    'status',
    ['in' => [Schedule::STATUS_SUCCESS, Schedule::STATUS_MISSED, Schedule::STATUS_ERROR]]
)->load();

$historySuccess = (int)$this->_scopeConfig->getValue(
    'system/cron/' . $groupId . '/' . self::XML_PATH_HISTORY_SUCCESS,
    \Magento\Store\Model\ScopeInterface::SCOPE_STORE
);
$historyFailure = (int)$this->_scopeConfig->getValue(
    'system/cron/' . $groupId . '/' . self::XML_PATH_HISTORY_FAILURE,
    \Magento\Store\Model\ScopeInterface::SCOPE_STORE
);
$historyLifetimes = [
    Schedule::STATUS_SUCCESS => $historySuccess * self::SECONDS_IN_MINUTE,
    Schedule::STATUS_MISSED => $historyFailure * self::SECONDS_IN_MINUTE,
    Schedule::STATUS_ERROR => $historyFailure * self::SECONDS_IN_MINUTE,
];

$now = $this->timezone->scopeTimeStamp();
/** @var Schedule $record */
foreach ($history as $record) {
    $checkTime = $record->getExecutedAt() ? strtotime($record->getExecutedAt()) :
        strtotime($record->getScheduledAt()) + $scheduleLifetime;
    if ($checkTime < $now - $historyLifetimes[$record->getStatus()]) {
        $record->delete();
    }
}
```

### Preconditions

1. PHP7
2. Magento 2.1.10

### Steps to reproduce

1. Run the different cron groups via separate cron job via **php bin/magento cron:run --group=...**, groups should have different configurations for history_failure_lifetime or history_success_lifetime

### Expected result

1. Cleanup should consider the configurations separately for jobs of each group

### Actual result

1. Cleanup of the group with smallest value for lifetime is considered

**Comment by magento-engcom-team** [comment]
@a-dite, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by kandy** [comment]
Looks like fixed in https://github.com/magento/magento2/pull/12497

**Comment by magento-engcom-team** [comment]
@a-dite, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
