### ISSUE TITLE
Magento 2.1.9 + PHP 7.0 memcache session storage = slow login/checkout

### ISSUE THREAD

**Issue by AlexisEvo** [magento/magento2#12742]
### Preconditions
1. Magento version 2.1.9 (or newer)
2. PHP 7.0 (or newer)
3. Unofficial pecl-memcache extension (from https://github.com/websupport-sk/pecl-memcache/ -- there is no official release of memcache for PHP 7.0)

### Steps to reproduce
1. Install Magento 2.1.9+ on PHP 7.0 with the memcache (not memcached) extension
2. Configure Magento to use memcache (not memcached) for session storage
3. Attempt to login (frontend or backend) or checkout

### Expected result
1. Page should load within 1-2 seconds

### Actual result
1. Magento stalls for 15 seconds (memcache.lock_timeout) when trying to regenerate the session ID in Magento::Framework::Session->regenerateId();

This was broken in 2.1.9 due to changes to the regenerate session ID code in Magento. You may understandably want to blame the memcache extension for this (as the code works in file storage, and with the memcached (with a D) extension). However, since Magento 2.2.0+ requires PHP 7.0, I feel that Magento should refuse to use the 'memcache' extension or throw an error/warning about this bug until it is fixed upstream.

**Comment by engcom-backlog-nickolas** [comment]
Hello @AlexisEvo, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by AlexisEvo** [comment]
This issue was fixed in 2.2.3 I believe, related to #12385 #12362 #14973. Closing out.
