### ISSUE TITLE
Email invoice to buyer has wrong grand total

### ISSUE THREAD

**Issue by congaframe** [magento/magento2#12750]
Grand total adds tax twice to the calculation if price / subtotal is included tax

### Preconditions
Magento 2.1.5
PHP 7.0.22
Enable Price included Tax everywhere. 

### Steps to reproduce

1. Order and pay for a product priced £22.99 ( included 20% tax) + £8 shipping (included VAT)
2. Check order and invoice email
3. Check order and invoice in Customer Account page

### Expected result

1. Grand total in Invoice should be £30.99

### Actual result

1. Grand Total adds Tax twice  = Subtotal (included Tax) + Shipping + Tax 
Therefore email sent to customer with incorrect Grand Total too 

Here is the Order details with correct calculation: 
<img width="912" alt="screen shot 2017-12-15 at 13 55 01" src="https://user-images.githubusercontent.com/12997841/34045566-5ccac9a2-e1a1-11e7-814d-441a707746b5.png">

Here is invoice detail with wrong Grand Total
<img width="907" alt="screen shot 2017-12-15 at 13 55 11" src="https://user-images.githubusercontent.com/12997841/34045575-65b7feb8-e1a1-11e7-97c0-ada48ebf327b.png">

**Comment by congaframe** [comment]
I found where the issue is, it was a Stripe module that we were using, passing wrong price when it generates invoices and email.

**Comment by danilkrasnorudskyi** [comment]
> I found where the issue is, it was a Stripe module that we were using, passing wrong price when it generates invoices and email.

Hello, could you help me with issue in stripe module, because I have probably the same issue.
