### ISSUE TITLE
Got 'The page isn't redirecting properly' after disable all cache options

### ISSUE THREAD

**Issue by needmoretoday** [magento/magento2#1275]
I am  a magneto extension developer. After I disabled all cache options in admin panel -> cache storage management edit page like I usually do with Magento development. Got Blank page with 'The page isn't redirecting properly' error message.
And I did search on how I turn on cache in table. Could not get it. 
My local system enviroment:
php 5.6.7
mysql 5.6

**Comment by mazhalai** [comment]
@needmoretoday if you have access to command line, you can run `php dev/shell/cache.php --set=1`

**Comment by mazhalai** [comment]
@needmoretoday "The page isn't redirecting properly'" is possibly a Firefox issue with cookies/headers/server configuration. Please see thread here: https://support.mozilla.org/en-US/questions/985967 and http://kb.mozillazine.org/The_page_is_not_redirecting_properly

**Comment by needmoretoday** [comment]
Thank you for your suggestion. i ran the command "php dev/shell/cache.php --set=1" to turned on cache. But seems the issue still there. I went back to check var/log/system.log, Saw error message that table 'customer_visitor'  expects 'customer_id' not 'visitor_id'.  i had manually alter 'customer_visitor' table.
Now I can load front page, but still got error after I login with admin panel.
Here is error message in var/log/system.log now:
2015-05-13 15:55:36] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and '' respectively. [] []
I am in branch 'develop', and do 'git pull' every day.

**Comment by mazhalai** [comment]
{{var/log/system.log}}  are not relevant. Are there any errors in  {{var/log/exception.log}} ?

**Comment by needmoretoday** [comment]
I checked, no error in var/log/exception.log

**Comment by piotrekkaminski** [comment]
@needmoretoday do you still have this issue? please check the latest version and reopen if required.
