### ISSUE TITLE
products not saving in admin

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1277]
products are not able to save.continuously please wait message...

browser:mozilla
os:ubuntu 14.04

**Comment by kokoc** [comment]
@sivajik34 Thank you for reporting the issue. However, we are unable to reproduce the issue using mozilla browser. Could you please verify the issue one more time and provide additional information:
Magento version, errors in log files, 404 pages, some specific steps to reproduce

**Comment by sivajik34** [comment]
after deleting pub/static/_requirejs/adminhtml
its working fine

**Comment by dinesh829269** [comment]
I resolved the issue . It was all permission issue

Use these steps to adjust how Magento modifies the default permissions for files:
Edit vendor/magento/framework/Filesystem/DriverInterface.php:
line 20, change:
const WRITEABLE_DIRECTORY_MODE = 0770;
To:
const WRITEABLE_DIRECTORY_MODE = 0755;

Line 25, change:
const WRITEABLE_FILE_MODE = 0660;
To
const WRITEABLE_FILE_MODE = 0644;

Through magento Admin panel , Clear your cache.

DO ssh login to your server set /var and /pub folder permission to 755. 

Make sure you have the correct permission set to these folders /var and /pub

Thats it it solved my problem.
