### ISSUE TITLE
Dropdown attribute options not saving

### ISSUE THREAD

**Issue by emmo1210** [magento/magento2#12772]
### Preconditions
1.New 2.2.1 Installation [Ubuntu 16.04, Apache 2.4.18, php 7.1.12, mysql 5.7.20] 
2. No products added yet, no modules.
3. Trying to add dropdown attribute options.

### Steps to reproduce
1. Add new attribute - dropdown type. Fill in default label value eg Grade.
2. Select 'Add option', fill in Admin value eg 304 or eg Aluminium 
3. Save attribute

### Expected result
1. The options would be saved to the attribute

### Actual result
1. The attribute is saving but the **options are not saving**. When save is pressed I am redirected to all product attributes page as normal. When I select the new attribute the options have not been saved so the system currently cant be used for configurable products I believe.

**Comment by emmo1210** [comment]
Sorry, I believe my issue may have been due to an uninstalled swatch module which seems to have fixed it.

**Comment by JiyaadDolly** [comment]
> Sorry, I believe my issue may have been due to an uninstalled swatch module which seems to have fixed it.

@emmo1210 How did you fix this? i have the same issue on Magento 2.3.4 commerce B2B
