### ISSUE TITLE
Wrong translated strings in the javascript dictionary.

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#12782]
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Default or Developer mode
3. 2 custom Store Views created and enabled
4. All indexers are valid
5. Different locales are set for each Store View, for example:
- **Ukrainian (Ukraine)** for the 1st custom Store View
- **French (France)** for the 2nd custom Store View 
- Leave **English (United States)** on Default Config level to be extended as a locale for Default Store View
6. Magento Cache is flushed if there is a need
7. Product visible for all Store Views is created
8. Put attached CSV files to Magento root folder
[source_fr_FR.csv.zip](https://github.com/magento/magento2/files/1560709/source_fr_FR.csv.zip)
[source_uk_UA.csv.zip](https://github.com/magento/magento2/files/1560711/source_uk_UA.csv.zip)
9. Run following in console:
- bin/magento i18n:pack --mode=replace -d source_uk_UA.csv uk_UA
- bin/magento i18n:pack --mode=replace -d source_fr_FR.csv fr_FR
- bin/magento setup:static-content:deploy en_US uk_UA fr_FR -f
- bin/magento setup:di:compile
- bin/magento deploy:mode:set production -s

### Steps to reproduce
1. Go to Storefront
2. Switch to Storeview with French locale
3. Open product page
4. Click **Ajouter au panier** to add the product to cart

### Expected result
Button changes to **En cours d'ajout...** while the ajax request is processing 
When the ajax requests is finished, the button changes to **Produit ajouté**
After a bit of time, the button changes back to **Ajouter au panier**

### Actual result
Wrong translated string **Ajouter vos mots clés :** (from one of the modules **"Magento_Newsletter"**, **"Magento_Email"**, **"Magento_MultipleWishlist"**) appears instead of **Produit ajouté**

Screenshots:
https://ibb.co/iemXem

**Comment by magento-engcom-team** [comment]
@andrewbess, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by andrewbess** [comment]
There are wrong translations.
File for locale fr_FR has different translations for same strings.
You need to use another language pack.
Please [look this](https://community.magento.com/t5/French/Magento-2-french-language-pack/td-p/32917) topic on Magento Forums.
I think it should be closed.
