### ISSUE TITLE
Gift card apply on cart page doesn't affects totals because of cache

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#12781]
### Preconditions
1. nginx/1.10.3 (Ubuntu)
2. PHP 7.0.22-0ubuntu0.16.04.1
3. 10.0.31-MariaDB
4. Magento EE 2.1.8

### Steps to reproduce
1. Add product to cart
2. Go to checkout/cart/index
3. Wait until shipping rates will be estimated (they cached after estimation). They are estimated because of new address so no additional actions required
4. Apply GiftCard

### Expected result
1. GiftCard totals displayed in summary sidebar

### Actual result
1. GiftCard totals doesn't displayed in summary sidebar

**Comment by magento-engcom-team** [comment]
@breg-13 , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
