### ISSUE TITLE
Allow gift message set on product level is ignored on PDP

### ISSUE THREAD

**Issue by danilavasenin** [magento/magento2#12780]
### Preconditions
Magento 2.1.7, Magento 2.1.8

### Steps to reproduce
1. Create product of type Giftcard
2. Set Allow Message to No on product level
3. Open created product on storefront

### Expected result
Gift message input is hidden

### Actual result
Gift message input is visible

The attribute code that is responsible for allow/disallow gift message on product level is `allow_message` that is not visible in grid, however, method 

`\Magento\GiftCard\Block\Catalog\Product\View\Type\Giftcard::isMessageAvailable()`
calls `$product->getGiftMessageAvailable()` which returns value of `gift_message_available` attribute

**Comment by magento-engcom-team** [comment]
@danilavasenin, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
