### ISSUE TITLE
responsiveness issue

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1278]
i think team still working on responsive in admin side.just for remainder all order ,invoice view pages not properly aligned.you can close this issue it is still in progress.
browser:mozilla
ubuntu 14.04

**Comment by sivajik34** [comment]
![order](https://cloud.githubusercontent.com/assets/7636894/7608332/18ec333e-f986-11e4-949f-06781934071d.png)

**Comment by godban** [comment]
Hello @sivajik34 

Thank you for reporting issue. You are right, we are refreshing admin look and feel. Order page styles was changed with latest release.
We can't reproduce that issue. It seems that cache in your browser is deprecated. Please try to clean up it.

**Comment by sivajik34** [comment]
i cleared all cookies and all in browser.still responsive issues are there in admin side.

**Comment by villageseo** [comment]
Hi @sivajik34, 

May be recompiling *.less files will help, could you try to remove /pub/static/adminhtml folder ? 
And what about other tabs (Shipments/Credit Memos), all right with them?

**Comment by sivajik34** [comment]
now its fine(Magento ver. 0.74.0-beta9).
