### ISSUE TITLE
related products not able to add to cart 

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1279]
![related products](https://cloud.githubusercontent.com/assets/7636894/7608950/d595f998-f98b-11e4-975a-416efd833fdf.png)

there is no check boxes for related products .i think this is theme issue.

**Comment by vpelipenko** [comment]
@sivajik34, could you provide Magento version? Do you use sample data?

**Comment by sivajik34** [comment]
ver. 0.74.0-beta8. with sample data

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30468

**Comment by kokoc** [comment]
@sivajik34 the issue is fixed in latest Magento version. Could you please verify it?

**Comment by sivajik34** [comment]
still issue existed in merchant beta

**Comment by victor-v-rad** [comment]
The issue appears when all related products are composite (Configurable, Bundle ...) or have required options. It will be fixed.

**Comment by vpelipenko** [comment]
@sivajik34, it is fixed and available in public Github. Could you check the fix?

**Comment by sivajik34** [comment]
thank you.its working fine.
