### ISSUE TITLE
Minimum Advertised Price is not working in 2.2.1 Open Source version after migrating from 1.9.1.0

### ISSUE THREAD

**Issue by webdev498** [magento/magento2#12796]
### Preconditions

1. Magento 2.2.1
2. Migrated from 1.9.1.0 using Magento Migration tool

### Steps to reproduce

1. Enable MAP in Stores>>Sales>>Sales>>Minimum Advertised Prices. Leave other options as 'Use system value'.
2. Set a value for MSRP > Price and select 'In Cart' for Display Actual Price.

### Expected result

1. Price on frontend is hidden and only shown 'In Cart' or for the login users

### Actual result
The price is shown as the followings:
1. [Screenshot, logs] Front-end
![111](https://user-images.githubusercontent.com/23560824/34122591-e1e33768-e3e1-11e7-91fd-263beab8d9a3.png)
2.  Admin backend
![222](https://user-images.githubusercontent.com/23560824/34122592-e21f5d92-e3e1-11e7-9b55-bb95b9a8fea4.png)

---  Product Detail Page ----
![333](https://user-images.githubusercontent.com/23560824/34122727-3bce5212-e3e2-11e7-9c89-b1ec2ef493f1.png)

![4444](https://user-images.githubusercontent.com/23560824/34122728-3c04110e-e3e2-11e7-84ce-fc52dbb64f91.png)

**Comment by magento-engcom-team** [comment]
@webdev498 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided on fresh installation of Magento 2.2.2. 
For migration related issues please use the repository: https://github.com/magento/data-migration-tool
