### ISSUE TITLE
I can't upload save product images in multiply website

### ISSUE THREAD

**Issue by subhashbodana** [magento/magento2#12798]
### Preconditions

1. I am using Magento 2.2.2, and I have create 5-7 multi-site, But I am not able to save product images.
2. 
![screenshot 3](https://user-images.githubusercontent.com/34674527/34146345-a45f8502-e4bf-11e7-8bf0-c524b41623c0.png)

After Save product, We can't see here product images.

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@subhashbodana thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@subhashbodana please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
