### ISSUE TITLE
[2.1.10] No order confirmation email after paying with PayPal Express

### ISSUE THREAD

**Issue by aeu** [magento/magento2#12792]
### Issue
We are (and have been) experiencing persistent problems with customers not getting order confirmation emails after paying with PayPal Express.   Store admin is getting notification from PayPal, and funds are processed, but no notification from the Magento store.  This is causing customers to place orders multiple times, and/or cancel their orders completely, which is obviously unacceptable.

We have seen these in every release of Magento 2 we have used since October, up to and including our current implementation which is 2.1.10.

### Preconditions
Dedicated server, 
Magento 2.1.10.  
CentOS 7.3.  
PHP 7.  
MariaDB.  
Double Redis (session and cache).  
Images on a CDN.

### Notes
After having spent more hours than I care to count poring through debug log files trying to find a cause, I have to admit that I'm pretty much at the same level of frustration expressed in this thread about the same issue (https://github.com/magento/magento2/issues/10464) whose resolution was the issue being closed and marked as fixed in 2.1.9.

To reiterate the comments of @andidhouse in that other thread - this is core functionality that really should be prioritized, and is 100% a Magento issue.  We build e-commerce stores on several platforms, and PayPal has literally zero issues on any of the other platforms we support.

If provided, I would be happy to install code with extended logging to help diagnose this issue.  From what I have seen Exception and Debug logs look fine, I can't see any difference between transactions that work and transactions that don't.

### Steps to reproduce
This is not reproducible, and appears to be random.  The only thing I can think of is that we left Asynchronous Send in it's default state (disabled) so perhaps there is some race condition there.  We recently enabled Asynchronous Send but haven't had any flawed PayPal orders come in since, so we cannot tell if this made a difference or not.

### Expected result
1. Customers should consistently get order confirmation emails

### Actual result
1. Customers randomly do not get order confirmation emails

### Misc
This may or may not be related, but we are also seeing customer addresses not being populated after orders for Virtual Products are complete.   At first I thought this was by design (since there is no product to ship no address is needed) but I also saw this issue (https://github.com/magento/magento2/issues/12707) which seems to indicate otherwise.

**Comment by orlangur** [comment]
Hi @aeu, 

> Steps to reproduce
> This is not reproducible, and appears to be random

How you think it can be fixed without a proper debug on your side? It was already tested on a clean installation a bunch of times, even with screencast recorded during testing.

Did you perform a load testing of your store to check the suggestion about race condition?

It's a bit strange to have setting you mentioned disabled in prod as it is described in http://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_perf-optimize.html#stores---configuration---sales---sales-emails

**Comment by aeu** [comment]
Hi @orlangur ,

> How you think it can be fixed without a proper debug on your side? It was already tested on a clean installation a bunch of times, even with screencast recorded during testing.

I'm sure it must be frustrating for you to get reports of bugs for things you have tested, but the issue assuredly exists.  This is quite surprising to me as well, especially since I have never had a single problem in multiple stores in many years with PayPal on Magento 1.

In my experience these sort of random non-reproducible bugs are extremely difficult to find, which is why I said I would be happy to install any modified or debug code you may have with extended logging to help diagnose this issue.

I am also happy to provide exception & debug logs from the server for review, I have found no discernible difference between successful and failed transactions.  If you have anything in particular that you think I can look for please let me know so I can examine and report back.

> Did you perform a load testing of your store to check the suggestion about race condition?

We do not suspect it to be load related - the server receives under 1k users and 2-3 orders per day and it's on a dedicated server which is more than adequate.  My initial suspicion was that it may be caused if there was a slow response from PayPal - i.e. if the store has to send email but it hasn't heard back from PayPal yet - but I do not know for sure because I have not digged into the code deeply enough yet.

> It's a bit strange to have setting you mentioned disabled in prod 

Thank you very much for this link, this was very good information.  The default setting of the store is not consistent with the guidelines in your link, it would be good to change the default.

It would also be good to update the documentation for the sales emails (http://docs.magento.com/m2/ce/user_guide/configuration/sales/sales-emails.html)  to reflect this, as they did not mention which was the preferred setting.    Would it be helpful if I would fill out the review for comment on that page and mention this?

**Comment by orlangur** [comment]
> We do not suspect it to be load related - the server receives under 1k users and 2-3 orders per day and it's on a dedicated server which is more than adequate

Sure thing, I was not saying issue is related to performance just that with load test we can try to reproduce similar situation with race condition.

However, with 2-3 confirmation emails supposed to be sent per day by Magento it is unlikely to happen due to customer collision as to me.

If there are no traces in Magento or server logs, it could be related to some flaw in email infrastructure.

**Comment by ladle3000** [comment]
I'm facing the same on 2.2 using the braintree paypal method.  Braintree credit card orders fire off emails fine, but customers pay with paypal and no email is fired.  Even in backend on order screen the paypal ones say order email confirmation NOT sent...

**Comment by tgrantmartin** [comment]
I too appear to be having this issue with paypal payments via braintree on 2.2.2

**Comment by ladle3000** [comment]
Yeah, the team wants some drawn out replication, but it's pretty straight
forward.

**Comment by ladle3000** [comment]
@tgrantmartin ours comes back periodically if we truncate the cron_schedule table. Something is getting clogged there.

**Comment by aeu** [comment]
Hi @orlangur 

> If there are no traces in Magento or server logs, it could be related to some flaw in email infrastructure.

That was my first thought too, but we also noticed the following:

1. We have had zero email confirmation issues using the integrated Authorized module
2. We switched to a third party PayPal module, and haven't seen the issue since.

**Comment by aeu** [comment]
Hi @snoroozi and @tgrantmartin - we switched to a 3rd party PayPal extension and have had absolutely zero issues since.  I don't know what the rules are here as far as mentioning extensions by name, but my email address is in my profile, I'll be happy to send you a link.

**Comment by magento-engcom-team** [comment]
Hi @aeu. Thank you for your report. 
The issue has been fixed in magento/magento2#13898 by @pmclain in 2.2-develop branch
Related commit(s):
 - [975137b58353bcef780e34e679fe8b115f98fe34](https://github.com/magento/magento2/commit/975137b58353bcef780e34e679fe8b115f98fe34)
 - [aec7af9c3b0ebf733d9c94fc3f34696e4cd87769](https://github.com/magento/magento2/commit/aec7af9c3b0ebf733d9c94fc3f34696e4cd87769)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @aeu. Thank you for your report. 
The issue has been fixed in magento/magento2#14225 by @dimonovp in 2.3-develop branch
Related commit(s):
 - [413b8981388d8a356db0f02ec096c91c388ae44e](https://github.com/magento/magento2/commit/413b8981388d8a356db0f02ec096c91c388ae44e)
 - [2b64618e4cc35ab27d142f4f84a17d99cc3b17dd](https://github.com/magento/magento2/commit/2b64618e4cc35ab27d142f4f84a17d99cc3b17dd)

The fix will be available with the upcoming 2.3.0 release.
