### ISSUE TITLE
Config and basics for all shipping: Ability to enable/disable for frontend of backend specifically

### ISSUE THREAD

**Issue by seansan** [magento/magento2#128]
Config and basics for all shipping: Ability to enable/disable for frontend of backend specifically

Ability to enable/disable shipping method on frontend and/or backend or both

Usecase: we want to enable free shipping or pickup only in the backend (for the admin to use, not the customers)

http://inchoo.net/ecommerce/magento/magento-frontend/how-to-hide-shipping-method-on-magento-frontend-but-leave-it-on-in-admin-area/comment-page-1/#comment-32564

For some of you, this might come as a surprise, but Magento does not support ?disabling? the shipping method on frontend but leaving it on in admin area. OK, thats not 100% correct since you can do some sort of a ?tweak config? that would enable this effect. The thing is that although Magento supports ?global/website/store? configs, shipping methods are turned on/off on a global and website level. On store level you can simply edit the title of a shipping method plus few other things, but usually you cannot enable/disable shipping method on a store level.

Now, imagine a case you only have one website defined in your Magento system, if you go to the admin ?Sales > Orders? and click ?Create New Order? button then the first next screen you see is the ?please select a customer? grid where you choose a customer for which you want to create an order.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-23681
