### ISSUE TITLE
Error during saving of crontab: "-":1: bad minute errors in crontab file, can't install

### ISSUE THREAD

**Issue by pmjcreations** [magento/magento2#12809]
### Preconditions

1. Installed version Magento Open Source 2.2.2
2. I am running all commands (installation, setup, cleaning, deploying etc.) with the same user login credentials via CLI

### Steps to reproduce

1. Tried to setup Cron as described here http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-cron.html
2. Tried command `php bin/magento cron:install` with and without `--force`

### Expected result

1. Running `php bin/magento cron:install` will finish the process and ready to run
2. When running `crontab -l` should see 

```
#~ MAGENTO START
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento cron:run 2>&1 | grep -v Ran jobs by schedule >> /var/www/html/magento2/var/log/magento.cron.log
* * * * * /usr/bin/php /var/www/html/magento2/update/cron.php >> /var/www/html/magento2/var/log/update.cron.log
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento setup:cron:run >> /var/www/html/magento2/var/log/setup.cron.log
#~ MAGENTO END
```

### Actual result

1. Running `php bin/magento cron:install` using Normal Shell access gives `Error during saving of crontab: "-":1: bad minute errors in crontab file, can't install`
2. Running `php bin/magento cron:install` using Jailed Shell access gives `Crontab has been generated and saved`
3. Command `crontab -l` throws `SHELL="/usr/local/cpanel/bin/jailshell"`

**Comment by camdixon** [comment]
I have been unable to reproduce this issue on a Ubuntu 16.04 box.

Running ```php bin/magento cron:install``` gives ```Crontab has been generated and saved``` as does the ```--force``` option.

I also used my same CLI credentials used to install, setup, and for cleaning.  Shell is /bin/bash.

**Comment by JustBeYou** [comment]
What's the current content of the crontab configuration?

**Comment by pmjcreations** [comment]
I have removed all previously configured cron jobs because I thought that might not be using. Then I tried `php bin/magento cron:install`. This could be the reason.

I have fixed this, and my `crontab -l` content is below.

```
#~ MAGENTO START 85bae43fa59b0aa6e41cf2b5d0314c1e
SHELL="/usr/local/cpanel/bin/jailshell"
* * * * * /opt/cpanel/ea-php70/root/usr/bin/php /home/threadly/public_html/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/threadly/public_html/var/log/magento.cron.log

SHELL="/usr/local/cpanel/bin/jailshell"
* * * * * /opt/cpanel/ea-php70/root/usr/bin/php /home/threadly/public_html/update/cron.php >> /home/threadly/public_html/var/log/update.cron.log

SHELL="/usr/local/cpanel/bin/jailshell"
* * * * * /opt/cpanel/ea-php70/root/usr/bin/php /home/threadly/public_html/bin/magento setup:cron:run >> /home/threadly/public_html/var/log/setup.cron.log

#~ MAGENTO END 85bae43fa59b0aa6e41cf2b5d0314c1e
```

Now let me ask you a related question, do you think `SHELL="/usr/local/cpanel/bin/jailshell"` in between is an expected line?

If Yes, then this issue is resolved and right to close.

**Comment by magento-engcom-team** [comment]
@pmjcreations , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
