### ISSUE TITLE
Magento 2.1.10 Upgrade product saving gives error when custom options are imported

### ISSUE THREAD

**Issue by anujeetphj** [magento/magento2#12803]
**Preconditions**
Previous version
Magento 2.1.3
Upgraded to version
Magento 2.1.10

**Using below commands**
composer require magento/product-community-edition 2.1.10 --no-update
composer update

rm -rf <Magento install dir>/var/cache/*
rm -rf <Magento install dir>/var/page_cache/*
rm -rf <Magento install dir>/var/generation/*

php bin/magento setup:upgrade
php bin/magento indexer:reindex

**Steps to Reproduce**
1. Created a new product of type virtual with some custom options.
1. Created another product of type virtual and imported custom options from product 1 to this one.

**Expected Result**
Product gets saved without any error

**Actual result**
Error while saving product
'No such entity'

![magento-error](https://user-images.githubusercontent.com/18703895/34155856-f3db9dac-e4e0-11e7-9ec2-c45cab155657.png)

I am not able to figure out what is the actual problem because it was working fine before in Magento 2.1.3 version. Is there anything wrong I did during upgrading?

**Comment by magento-engcom-team** [comment]
@anujeetphj, thank you for your report.
We've created internal ticket(s) MAGETWO-85905 to track progress on the issue.

**Comment by p-bystritsky** [comment]
Issue is already fixed in 2.2-develop.

**Comment by p-bystritsky** [comment]
Issue already fixedin 2.2-develop.

**Comment by WilXP** [comment]
@p-bystritsky Hey there, can you please point me to the code in 2.2 where this is fixed? I need to fix this in 2.1 .

**Comment by SohaSalem** [comment]
Hey I need to fix this in version 2.1.7 without upgrading the version 
Thanks
