### ISSUE TITLE
Product listing page caches the messages

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1280]
When I add/remove product from/to compare list in product listing page it displays the relevant message s. But it stays in the cache for ever. It does not get cleared once I refresh the page. It caches the entire view port including the message block.
![selection_022](https://cloud.githubusercontent.com/assets/3830093/7626154/cef954fa-fa20-11e4-88bd-5c86b7474285.png)

**Comment by kokoc** [comment]
@bgkavinga Thank you for reporting the issue. Internal reference: MAGETWO-37505

**Comment by kokoc** [comment]
@bgkavinga the team has processed this ticket. Code changes have just been deployed in version 0.74.0-beta10. Thank you for your contribution! Could you please verify the fix?

**Comment by bgkavinga** [comment]
@kokoc It does not add product to compare list once I click on the add to compare link.

**Comment by bgkavinga** [comment]
@kokoc It does not show messages anywhere. But it displays entire message queue in cart page. Check the following screen shot.
even the mini cart does not get updated.
![image](https://cloud.githubusercontent.com/assets/3830093/7877076/c4c0fb4a-05f2-11e5-96a0-8b72832d9b9f.png)

**Comment by bgkavinga** [comment]
issue is mostly fixed. But after a checkout it does not update the mini cart. Check the below screen shot.
![image](https://cloud.githubusercontent.com/assets/3830093/8033003/85c42e4a-0df8-11e5-90d6-78f831f09e57.png)

**Comment by vpelipenko** [comment]
@bgkavinga, do you still have the issue with not updated mini-cart?

**Comment by kamote** [comment]
issue still exist in 2.0.5
