### ISSUE TITLE
Crontab.php recreate

### ISSUE THREAD

**Issue by Rockfordgun** [magento/magento2#12814]
Im running magento 2.2.0.
Im having issues with my cron jobs.
I had a look at the logs and i have endless errors with my crontab.php file. 
Where can i recreate or download the crontab.php file?

**Comment by magento-engcom-team** [comment]
@Rockfordgun please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
