### ISSUE TITLE
Unable to load paypal express checkout window

### ISSUE THREAD

**Issue by gouravsyscraft** [magento/magento2#12815]
### Preconditions

1. Setup paypal express checkout.
2. This is dev url (http://dev1.photomart.co.uk)with non https.
3. All other module working fine

### Steps to reproduce

1. Add item into (http://dev1.photomart.co.uk) cart
2. Choose payment method as paypal express checkout.
3. Click continue with accept terms condition then paypal window not loading only page loading? why?

### Expected result

1.  As same process i am doing on my local system means with xampp window machine its working fine but when i setup this on server with (http://dev1.photomart.co.uk) then its not working why?

### Actual result

1. Paypal window able to load when you choose paypment method (Paypal express checkout)from checkout page

**Comment by gouravsyscraft** [comment]
I am frustrating with this issue, please help me some one why paypal express checkout window not loading?

**Comment by magento-engcom-team** [comment]
@gouravsyscraft, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
