### ISSUE TITLE
An error occurred on the server. Please try to place the order again

### ISSUE THREAD

**Issue by gh-darvishani** [magento/magento2#12818]
centos server
magento 2.1
 error "An error occurred on the server. Please try to place the order again"

Hi
i get this error on checkout and after same try and debug i found this function 

`    public function savePaymentInformationAndPlaceOrder(
        $cartId,
        $email,
        \Magento\Quote\Api\Data\PaymentInterface $paymentMethod,
        \Magento\Quote\Api\Data\AddressInterface $billingAddress = null
    ) {
        $this->savePaymentInformation($cartId, $email, $paymentMethod, $billingAddress);

        try {
            $orderId = $this->cartManagement->placeOrder($cartId);
        } catch (\Exception $e) {
//            var_dump($e->getMessage());
            throw new CouldNotSaveException(
                __('An error occurred on the server. Please try to place the order again. errors =  %1',$e->getMessage()),
                $e
            );
        }
        return $orderId;
    }`
and message tell me the city and county and name ... are required 
i check billing address by var_dump and i see all required data 
and now i do'n know how i can fix this issue and i think it is a magento bug

**Comment by gh-darvishani** [comment]
after 3 days ...

**Comment by samanaveen** [comment]
please check
https://magento.stackexchange.com/questions/149546/magento-2-an-error-occurred-on-the-server-please-try-to-place-the-order-again
