### ISSUE TITLE
Magento success/error message showing on every page.

### ISSUE THREAD

**Issue by ashvinim0003** [magento/magento2#12811]
### Preconditions

1. Installed Magento ver. 2.1.8 from git
2. Uploaded simple products
3. Cache is disable

### Steps to reproduce

1. Create an account and login
2.  add any simple product to the cart.
3. again add the same or any product in the cart
4. visit any page like the checkout page

### Expected result

1. success message will show one time and it will be removed after page reloads or on the checkout page.
2. It will show only the latest message.

### Actual result

1. It is showing multiple success message and duplicate also.
![ripple bath mat](https://user-images.githubusercontent.com/5154042/34171051-04e30b12-e513-11e7-904d-f6a8be493681.png)
2. Message is still showing after reload page.
3. Same old message is showing on cart page
![shopping cart 2](https://user-images.githubusercontent.com/5154042/34171060-0baabc9c-e513-11e7-8339-18d2ea4551c9.png)

**Comment by magento-engcom-team** [comment]
@ashvinimarwal, thank you for your report.
The issue is already fixed in 2.2.2

**Comment by ashvinim0003** [comment]
@magento-engcom-team  Thank you for the response.
Due to some issues, I can't update my Magento.

It would be really appreciable if you can share any patch to fix this issue in Magento 2.1.8
Kind Regards

**Comment by ashvinim0003** [comment]
@magento-engcom-team  waiting for your response.

**Comment by amiyoghoshstar** [comment]
Still occurring in magento .2.4.1

**Comment by usman786cs** [comment]
Any solution for this issue here?
I'm having it appearing add to cart message shopping cart and checkout pages.
