### ISSUE TITLE
ACL resource tree shows 2 checkboxes (kind of)

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1281]
**Version**
Magento2-0.74.0-beta8

**Steps to reproduce**

 - Log in the backend
 - go to system->user roles
 - click on Add role
 - go to the Role resources tab

**Expected result**

 - A tree structure with the ACL resources should be displayed. 
 - Each resource name should have a checkbox beside it.
 - Clicking on the checkbox should check it and the parent nodes in the tree

**Actual result**

 - A tree structure with the ACL resources is displayed. 
 - Each resource name has 2 checkboxes beside it. Well...one checkbox and one image that looks like a checkbox  
   ![2-checkboxes](http://i.imgur.com/MuiMbf9.png)
 - Clinking on the actual checkbox (the one on the left) only checks that specific checkbox.  
   ![checkbox-click](http://i.imgur.com/ZTOozno.png)
 - Clicking on the image (on the right) selects the specific checkbox and the ones for the parent nodes (expected behavior)  
  ![click-image](http://i.imgur.com/qMJ8bR7.png)

In my opinion this can should be solved just by hiding the real checkbox and displaying only the image that looks like a checkbox.

**Note**  
The same thing happens for System->Integrations->Add Integration->API.  
I'm almost sure that if one gets fixed, the other will be be fixed as well. no need to open 2 issues for this.

**Comment by MomotenkoNatalia** [comment]
@tzyganu  Thank you, for your contribution. This issue is confirmed and related ticket has been added to the backlog (MAGETWO-37567).

**Comment by vpelipenko** [comment]
@tzyganu, this issue is fixed and already available on public github. Did you a chance to verify it on the latest version?

**Comment by tzyganu** [comment]
@vpelipenko It works nicely on 0.74.0-beta11. Thank you for the fast fix.
