### ISSUE TITLE
Cross sell number of product list

### ISSUE THREAD

**Issue by ttribeiro** [magento/magento2#12813]
Where can I update the cross sell number of product on the list?

Magento 2.1.9 CE

**Comment by thiagolima-bm** [comment]
This kind of question must be asked on the stackoverflow

**Comment by magento-engcom-team** [comment]
Hello, @ThiagoR. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
