### ISSUE TITLE
how to install the magento admin panel?

### ISSUE THREAD

**Issue by swarishna** [magento/magento2#12822]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@swarishna, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
