### ISSUE TITLE
Address duplicate issue when we register the user after guest user checkout

### ISSUE THREAD

**Issue by pushpendra07** [magento/magento2#12827]
The customer address is duplicating when we create user account after the guest checkout process.

**Preconditions**

**Version: Magento 2.2.1**

**Steps to reproduce**

Add an item to the cart as a guest user.
Provide user details and press "Checkout" button.
Don't forget to check the checkbox "My billing and shipping address are the same" while selecting the payment method.
Place the order.
It will redirect to success page.
Create an account for that user using "Create Account" button from that page .
Activate your account.
Sign in to your account using the credentials.
Again add an item to the cart and checkout.
During the time you can see the address is duplicating.
**Expected result**

It will show only one address because I entered a single address and checked that address should use as both shipping and billing address.

**Actual result**

But here the address is showing two times.

![image](https://user-images.githubusercontent.com/8010768/34206988-9f38c058-e5ae-11e7-918a-c6f63bddb541.png)

This issue already mention at [8350](https://github.com/magento/magento2/issues/8350)

**Comment by magento-engcom-team** [comment]
@pushpendra07, thank you for your report.
We've created internal ticket(s) MAGETWO-85874 to track progress on the issue.

**Comment by pushpendra07** [comment]
Hello @magento-engcom-team , Any updates on this.

**Comment by dharmendra-wagento** [comment]
@magento-engcom-team,
I have verified issue in 2.2-develop branch and it was fixed. On guest checkout, create account from success page previously it was saving address of registered account in address book, but now it is not saving address of registered account in customer address.
So issue did not exist in 2.2-develop branch.

**Comment by okorshenko** [comment]
Hi @dharmendra-wagento thank you for your investigation. Closing the issue

**Comment by Satishshaw97** [comment]
hi @dharmendra-wagento , could you please share the solution link here , I am using magento 2.1.7 and facing the same issue.
