### ISSUE TITLE
Wrong annotation in _toOptionArray - magento/framework/Data/Collection/AbstractDb.php

### ISSUE THREAD

**Issue by BrocksiNet** [magento/magento2#12820]
The annotation for **valueField** should be _**@param null|string $valueField**_ at the moment php phan thorws this as an error. And i think phan is right.

**See here:**
**src/vendor/magento/framework/Data/Collection/AbstractDb.php**
```
    /**
     * Overridden to use _idFieldName by default.
     *
     * @param null $valueField
     * @param string $labelField
     * @param array $additional
     * @return array
     */
    protected function _toOptionArray($valueField = null, $labelField = 'name', $additional = [])
    {
        if ($valueField === null) {
            $valueField = $this->getIdFieldName();
        }
        return parent::_toOptionArray($valueField, $labelField, $additional);
    }
```

**Comment by magento-engcom-team** [comment]
@bjoern-flagbit, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@bjoern-flagbit Looks like the issue was fixed in the commit https://github.com/magento/magento2/commit/67b5fe71f23d32c96c0c9992b8adf2f378cd2a58 by @sanjay-wagento 

Thank you for collaboration!
