### ISSUE TITLE
Configurable options(Text swatch) type does not order on the basis of the sort order provided

### ISSUE THREAD

**Issue by sinharitu** [magento/magento2#12825]
1. Create an attribute with the 'Catalog Input type' as Text Swatch.
2. Add Values to the attribute.
3. Add this attribute to the product and check the values displayed.
4. It should be displayed as per the sort order defined.

Actual:
Not displayed as per the sort order.
Link to the video to reproduce: 
[https://drive.google.com/open?id=1Fx8gFcZu0RL0NnyXdEKdT96pVpdzXwnu](url)

**Comment by magento-engcom-team** [comment]
@sinharitu, thank you for your report.
We've created internal ticket(s) MAGETWO-85865 to track progress on the issue.

**Comment by karangar** [comment]
please assign me #MM18IN

**Comment by magento-engcom-team** [comment]
@karangar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by folektoras** [comment]
@magento-engcom-team this issue does not seem to be reproducible anymore on magento 2.3-develop.

[SEE SCREENCAST](https://drive.google.com/file/d/1-Y8J5EQJaqVm2v9g_p1nSL06LWI7AFhB/view)
