### ISSUE TITLE
Field required backend order creation

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#12836]
When you have 2 websites example1.com and example2.com and you have the next setup : 
Default config -> Customer Configuration  -> VAT required -> Optional
Example1 -> Customer Configuration -> Vat Required -> Required
Example2 -> Customer Configuration -> Vat Required -> Not required

**note :** Example 1 is default website so the adminhtml is always example1.com/adminurl

Then because you are on example1.com/adminurl while you are creating the order it will take the value of Example1 even if your order is ment for Example2. Which results that it doesn't matter for which website you are making the order in the adminhtml it will always demand a VAT (not tested on other settings but i think it will do the same)

### Preconditions
1.  PHP 7+
2.  Magento 2.2.1

### Steps to reproduce
1.  Create 2 websites like mentioned above
2.  Set default config VAT to optional like mentioned above
3.  Set  Example 1 and 2 VAT requirement like mentioned above
4. Try to make an order in the backend for Example 2.

### Expected result
1. Vat is not required since we are making an order for a website that doesn't require VAT

### Actual result
1. Vat is required and you can not create an order for that website

Dumping the website id 
![image](https://user-images.githubusercontent.com/18028151/34236100-190435a6-e5f6-11e7-8f1e-ab5314e6584f.png)

Showing the website id from the customer where the order is made for and that tax/vat is required
![image](https://user-images.githubusercontent.com/18028151/34236203-8b4c8ec4-e5f6-11e7-9ee5-67d0936b9d0e.png)

Showing the table where the customer attribute value is not required (attribute 17 = taxvat)
![image](https://user-images.githubusercontent.com/18028151/34236152-5854e4bc-e5f6-11e7-92b5-f9a68c4b5749.png)

Showing that ID 17 is indeed taxvat
![image](https://user-images.githubusercontent.com/18028151/34236164-68651520-e5f6-11e7-8fef-3e41f36c8a11.png)

**Note :** Same for the store front!!

**Comment by versdivers** [comment]
I noticed the same in the storefront while creating an account. The VAT field is not showing during account creation but if you submit it will give the error that it actually is required so you can not continue. This because for some reason the validator takes the default config as a requirement. Having the default config on 'optional' fixes it but it should not be an issue like this

**Comment by versdivers** [comment]
I deleted my answer and i will update this with a modules code very soon

**Comment by versdivers** [comment]
Here is the temporary fix. You can add whatever you want in Form.php

https://gist.github.com/versdivers/f5680bb8712878a62ad2f07a055567a1

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.
We've created internal ticket(s) MAGETWO-85925 to track progress on the issue.

**Comment by Hexmage** [comment]
This seems to be at least partially related to the backend URL. 

> Default config base url: example1.org
> Website 1 Baseurl: use default
> Website 2 Baseurl: example2.org
> 
> Default config -> Customer Configuration -> VAT required -> Not Required
> Website 1 -> Customer Configuration -> Vat Required -> Required
> Website 2 -> Customer Configuration -> Vat Required -> use default

In the above situation taxvat is always required in the backend.

> Default config baseurl: example2.org
> Website 1 Baseurl: example1.org
> Website 2 Baseurl: use default
> 
> Default config -> Customer Configuration -> VAT required -> Not Required
> Website 1 -> Customer Configuration -> Vat Required -> Required
> Website 2 -> Customer Configuration -> Vat Required -> use default

In the above situation taxvat is not required in the backend.

**Comment by versdivers** [comment]
This is getting frustrating. Im trying to set up a B2B and B2C website and its just not possible to have 1 website set to use taxvat and the other one not. not in the store front and not in the backend.

If i save Website 1 then website 2 gets the same requirement and visa versa

**Comment by Hexmage** [comment]
@versdivers If you want to workaround the store front issue, you should disable Eav cache.

**Comment by versdivers** [comment]
How is that a workaround if you have a store with 5000 products

**Comment by Hexmage** [comment]
@versdivers I never claimed it was fast.

The other thing you could try is in Magento\Customer\etc\di.xml 
Change
```
<preference for="Magento\Customer\Api\CustomerMetadataInterface"
                type="Magento\Customer\Model\Metadata\CustomerCachedMetadata" />
```
To
```
<preference for="Magento\Customer\Api\CustomerMetadataInterface"
                type="Magento\Customer\Model\Metadata\CustomerMetadata" />
```
This causes the CustomerMetadata to not be cached.

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by DeLuuk** [comment]
This problem is still there, anyone know a fix?
