### ISSUE TITLE
Custom Theme default.xml not working in 2.2

### ISSUE THREAD

**Issue by swleighton** [magento/magento2#12830]
### Preconditions
1. Magento 2.2
2. PHP 7.0.25

### Steps to reproduce
1. Downloaded Magento 2.2
2. Copied existing theme into _/app/design/frontend/_ so that the default.xml file is located at
_/app/design/frontend/ VENDOR/THEME_NAME/Magento_Theme/layout/_
3. Set theme in admin

### Expected result
1. The cart/menu move as per the layout blocks in the file

### Actual result
1. No changes from default.xml are being included 

`<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
      <referenceContainer name="header.container">
        <block class="Magento\Cms\Block\Block" name="header.delivery" before="-">
          <arguments>
              <argument name="block_id" xsi:type="string">header.delivery.banner</argument>
          </arguments>
        </block>
      </referenceContainer>
      <referenceContainer name="header-wrapper">
            <container name="social.header" htmlClass="social-icon-links social-icon-links--header" before="top.search" htmlTag="div">
                <block class="Magento\Framework\View\Element\Template" name="social.links1" before="-" template="Magento_Theme::social-links.phtml">
                </block>
            </container>
        </referenceContainer>

        <referenceContainer name="header.panel">
            <block class="Magento\Framework\View\Element\Html\Links" name="header.links">
                <arguments>
                    <argument name="css_class" xsi:type="string">header links</argument>
                </arguments>
                <block class="Magento\Customer\Block\Account\Customer" name="customer" template="Magento_Customer::account/customer.phtml" before="-"/>
                <block class="Magento\Customer\Block\Account\AuthorizationLink" name="authorization-link-login" template="Magento_Customer::account/link/authorization.phtml">
                    <arguments>
                        <argument name="sortOrder" xsi:type="number">10</argument>
                    </arguments>
                </block>
            </block>

        </referenceContainer>
        <referenceBlock name="logo">
            <arguments>
                <argument name="logo_img_width" xsi:type="number">250</argument>
                <argument name="logo_img_height" xsi:type="number">151</argument>
            </arguments>
        </referenceBlock>
        <referenceContainer name="footer">
            <block class="Magento\Store\Block\Switcher" name="store_switcher" as="store_switcher" after="footer_links" template="Magento_Store::switch/stores.phtml"/>
            <block class="Magento\Cms\Block\Block" name="footer.contact" after="footer.links">
              <arguments>
                  <argument name="block_id" xsi:type="string">footer.contact.details</argument>
              </arguments>
            </block>
            <container name="social.footer" htmlClass="social-icon-links social-icon-links--footer" htmlTag="div" after="footer.contact">
                <block class="Magento\Framework\View\Element\Template" name="social.links2" before="-" template="Magento_Theme::social-links.phtml">
                </block>
            </container>
            <block class="Magento\Cms\Block\Block" name="paymentcards.block" after="social.footer">
              <arguments>
                  <argument name="block_id" xsi:type="string">paymentcards.image</argument>
              </arguments>
            </block>
        </referenceContainer>
        <referenceBlock name="catalog.topnav">
                  <block class="IBD\NavigationLink\Block\Links\Link" name="newpage" after="-">
                    <arguments>
                      <argument name="label" xsi:type="string" translate="false">Contact Us</argument>
                      <argument name="path" xsi:type="string" translate="false">contact</argument>
                      <argument name="listcss" xsi:type="string">level0</argument>
                      <argument name="css" xsi:type="string">new-test level-top</argument>
                    </arguments>
                  </block>
            </referenceBlock>
            <referenceBlock name="footer_links">
              <block class="Magento\Framework\View\Element\Html\Link\Current" name="delivery-and-returns-link" before="contact-us-link">
                  <arguments>
                      <argument name="label" xsi:type="string" translate="true">Delivery and Returns</argument>
                      <argument name="path" xsi:type="string">delivery-and-returns</argument>
                  </arguments>
              </block>
            </referenceBlock>
            <referenceContainer name="store.menu">
              <container name="social.menuitem" htmlClass="social-icon-links social-icon-links--footer" htmlTag="div" after="catalog.topnav">
                  <block class="Magento\Framework\View\Element\Template" name="social.links3" template="Magento_Theme::social-links.phtml">
                  </block>
              </container>
            </referenceContainer>

        <referenceBlock name="search-term-popular-link" remove="true"/>
        <referenceBlock name="catalog-search-advanced-link" remove="true"/>
        <referenceBlock name="report.bugs" remove="true"/>
        <move element="copyright" destination="before.body.end"/>
        <move element="navigation.sections" destination="header-wrapper" />

        <referenceBlock name="product.info.review" remove="true" />
        <referenceBlock name="reviews.tab" remove="true" />

        <referenceBlock name="catalog.compare.sidebar" remove="true"/>
        <referenceBlock name="catalog.compare.link" remove="true"/>
        <referenceBlock name="item.addto.compare" remove="true" />

        <move element="top.search" destination="header.panel" before="header.links"/>
<move element="minicart" destination="header.panel" after="top.search"/>
<move element="social.header" destination="header.panel" before="top.search"/>
    </body>
</page>`

**Comment by Triloworld** [comment]
There is error in your file. Replace all existing blocks and container with reference. Make sure you have parent theme configured correctly

**Comment by swleighton** [comment]
Removed most of the file to only leave the block that inserts a new item into the menu. The file is still failing to load


`
<referenceBlock name="catalog.topnav">
         <block class="IBD\NavigationLink\Block\Links\Link" name="newpage" after="-">
           <arguments>
             <argument name="label" xsi:type="string" translate="false">Contact Us</argument>
             <argument name="path" xsi:type="string" translate="false">contact</argument>
             <argument name="listcss" xsi:type="string">level0</argument>
             <argument name="css" xsi:type="string">new-test level-top</argument>
           </arguments>
         </block>
     </referenceBlock>
`

**Comment by swleighton** [comment]
`
<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
      <referenceBlock name="catalog.topnav">
         <block class="IBD\NavigationLink\Block\Links\Link" name="newpage" after="-">
           <arguments>
             <argument name="label" xsi:type="string" translate="false">Contact Us</argument>
             <argument name="path" xsi:type="string" translate="false">contact</argument>
             <argument name="listcss" xsi:type="string">level0</argument>
             <argument name="css" xsi:type="string">new-test level-top</argument>
           </arguments>
         </block>
     </referenceBlock>
   </body>
</page>
`

**Comment by swleighton** [comment]
I fixed this by changing the "Type" field in the theme table for my theme back from 1 to 0.

**Comment by JMLucas96** [comment]
@swleighton solution not working for me... 
I have 
`httpdocs/app/design/frontend/Alothemes/digitalworld4/Magento_Theme/layout/default_head_blocks.xml`
`<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
	<body>
		<referenceBlock name="head.additional">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
			
			
			
			 
			<css src="Magiccart_Magicmenu::css/magicmenu.css" />
			
			<css src="font/fontawesome/css/font-awesome.min.css" />
			<css src="font/pe-icon-stroke/css/pe-icon-7-stroke.css" />
			<css src="font/webfont/css/simple-line-icons.css" />
			<css src="font/flaticon/css/flaticon.css" />
			
			<css src="bootstrap/css/bootstrap.min.css"/>

			<css src="css/styles.css" />
			<css src="css/print.css" media="print" />
			<css src="css/responsive.css" />
			
			<css src="css/kendo/kendo.common.min.css" />
			<css src="css/kendo/kendo.custom.css" />
			<css src="css/kendo/kendo.default.min.css" />
			<css src="css/meu.css" />
			<css src="css/sprite_menu.css"/>
			<link src="js/compsaonline.js"/>
			<link src="js/analytics_compsaonline.js"/>
		</referenceBlock>
	</body>
</page>
`
And `css/meu.css` in `httpdocs/app/design/frontend/Alothemes/digitalworld4/web/css/meu.css` but not added on frontend.
No error reported also.

**Comment by swleighton** [comment]
@magento give me 2.3.3 instance with ee
