### ISSUE TITLE
overriding htmlClass doesn't work for every Container

### ISSUE THREAD

**Issue by emmathepossum** [magento/magento2#12832]
### Preconditions

1. Magento 2.2.1
2. PHP 7.1

### Steps to reproduce

1. Create Custom Theme
2. create `Magento_Theme/layout/default.xml`
3. insert `<referenceContainer name="product.info.media" htmlClass="custom-product-media-class"/>`

### Expected result

1. CSS class of `product.info.media` Container should change

### Actual result

1. CSS class doesn't change. `<div class="product media">`

Same problem with `product.info.price` and `product.info.main`.
Other Containers work fine, like `<referenceContainer name="footer-container" htmlClass="footer"/>`.

Changing the htmlClass in the original source file however works.
`vendor/magento/module-catalog/view/frontend/layout/catalog_product_view.xml`
```xml
<container name="product.info.media" htmlTag="div" htmlClass="product media" after="product.info.main">
```

**Comment by ipascual** [comment]
+1

**Comment by magento-engcom-team** [comment]
Hi @dwirt 
Thank you for your report.
This seems to be correct Magento behavior.
Such behavior related with the ordering layout files processing.
See: http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/layout-overview.html#layout_processing and http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/layout-extend.html

For extend/rewrite `product.info.media` container you should do it in `<any_module>/layout/catalog_product_view.xml`

**Comment by magento-engcom-team** [comment]
@dwirt, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
