### ISSUE TITLE
Magento 2 Multiple discount with percent of product price discount calculation issue

### ISSUE THREAD

**Issue by mageprince** [magento/magento2#12837]
### Preconditions
1. Magento 2.2.2
2. PHP Version 7.0.22

### Steps to reproduce

**1. Create new cart price rules with the following configuration**

**Rule 1:**
```
Rule Name: 10% Fix Discount
Coupon: No Coupon
Conditions: Apply for all product
Action: 
    Apply: Percent of product price discount
    Discount Amount: 10

```
**Rule 2:**
```
Rule Name: 5% Fix Discount
Coupon: No Coupon
Conditions: Apply for all product
Action: 
    Apply: Percent of product price discount
    Discount Amount: 5
```

**2. Add product to cart with has price = $45**

### Expected result

    Total discount applied $6.75
    First Rule(10% of product price) Discount: (45*10) / 100 = 4.5
    Second Rule(5% of product price) Discount: (45*5) / 100 = 2.25
    Total Discount = 2.25 + 4.5 = 6.75

### Actual result
    Total discount applied $6.53
     
![shopping cart](https://user-images.githubusercontent.com/24751863/34245017-16c8dfbe-e64e-11e7-993f-3af0dce98db0.png)

**Comment by magento-engcom-team** [comment]
@mageprince, thank you for your report.
We've created internal ticket(s) MAGETWO-85918 to track progress on the issue.

**Comment by ddevallan** [comment]
But this is not the right behavior ?

In Magento 1 is discount over discount, not discount over the original item price.

**Comment by viral-wagento** [comment]
@mageprince 
As per Magento Behavior - it is working correct. Please find below.

```
First Rule(10% of product price) Discount: (45*10) / 100 = 4.5
Therefore, Subtotal = (45-4.5) = 40.5
Second Rule(5% of product price) Discount: (40.5*5) / 100 = 2.025

Total Discount = 2.025 + 4.5 = 6.525 = 6.53

```
@alnmaiafernandes  Yes, correct.

**Comment by mageprince** [comment]
@viral-wagento and @alnmaiafernandes 
Yes, I know this is default Magento behavior but this is wrong. Magento core team should change this behavior.

**Comment by devqualwebs** [comment]
Is there any way to do it? Even I'm trying to achieve the same behavior.

**Comment by devqualwebs** [comment]
@mageprince @magento-engcom-team @viral-wagento How can I modify this behavior?

**Comment by nattapon-central** [comment]
@mageprince , @magento-engcom-team 
How are you guys going to fix this issue? I believe the expected result described in this ticket is not expectation for everyone. The company I am working for has to use the percentage discount based on the item price with its prior discount.
How about implement this in new Action type?

**Comment by engcom-Alfa** [comment]
Hi @mageprince. Thank you for your reporting.

Currently, it is default Magento behavior.
```
First Rule(10% of product price) Discount: (45*10) / 100 = 4.5
Therefore, Subtotal = (45-4.5) = 40.5
Second Rule(5% of product price) Discount: (40.5*5) / 100 = 2.025

Total Discount = 2.025 + 4.5 = 6.525 = 6.53
```
**Actual Result:**
![screen](https://user-images.githubusercontent.com/51679138/71512488-14acc700-289f-11ea-807a-85d317a2ea47.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
 Thank you for collaboration.
