### ISSUE TITLE
Magento 2 ! Multistore Not Setup with different Domains

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/magento2#12839]
### Preconditions

1. Using Magento 2.2 in nexcess Server 
2. Creating Multi Store with Different URL 

### Steps to reproduce

1. Create Website , Store and Store View 
2. Assign Base URL of new domain in base URL for both Secure and non secure   From admin ,
3. also Change to yes This Option  "Add Store Code to Urls" created url .
4. when try to access my new store with domain , see error 

### Expected result

1. My new Store Should Load and 

### Actual result

1. i got this error 
![error](https://user-images.githubusercontent.com/32513730/34245559-5ebacd8a-e650-11e7-9d71-e94aa50a7b0f.png)

please help urgent 
Thanks

**Comment by magento-engcom-team** [comment]
@yogeshsyscraft, thank you for your report.
We've created internal ticket(s) MAGETWO-86000 to track progress on the issue.

**Comment by chiragp-wagento** [comment]
Hi @yogeshsyscraft ,

Can you please provide detailed steps to re-produce this issue as we cannot disable assigned store view from admin side. This seems like you have directly changed the value of is_active to 0 in store table. If yes then please change that value to 1.

Kindly advice.

**Comment by osrecio** [comment]
This ticket is closed due to inactivity. 
If it continues to happen or has a contribution, feel free to re-open it.

Thank you
