### ISSUE TITLE
Mass Action On Single Item In Filtered List

### ISSUE THREAD

**Issue by Jimgitsit** [magento/magento2#12834]
If a filter produces a single item in a list and then a mass action is performed on that item, there is no 'selected' property in the POST.

### Preconditions
M2 v2.1.10
In my case I am using a custom grid built by a third party and a custom mass action built by myself. I have not tested this with other grids.

### Steps to reproduce
- Filter a list so that only one result is returned.
- Check the item
- Select a mass action

### Expected result
The POST data should have a 'selected' property which should be an array of the 1 item selected.

### Actual result
'selected' property is absent.

Note that if the list filter produces more than one result but only one item is checked the 'selected' property is there in the POST. It's only absent when there is one filtered result.

I have yet to find a workaround to this issue.

**Comment by magento-engcom-team** [comment]
@Jimgitsit , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by juansumma** [comment]
I can reproduce this exactly as described in version 2.2.1 but only using a custom module
