### ISSUE TITLE
order tracking link redirected to dashboard in admin

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1284]
![sales1](https://cloud.githubusercontent.com/assets/7636894/7666799/fb05d5ce-fc0e-11e4-95c0-c201b31a20ee.png)
![sales2](https://cloud.githubusercontent.com/assets/7636894/7666800/ffc0eeb4-fc0e-11e4-9971-8f910b5a1b35.png)

**Comment by sivajik34** [comment]
steps to reproduce:
1. account created in front end.
2.order placed
3.added tracking number with custom value (carrier)
version:
Magento ver. 0.74.0-beta9

**Comment by sivaschenko** [comment]
Thank you for reporting this issue. Internal ticket number MAGETWO-38301

**Comment by vpelipenko** [comment]
@sivajik34, this issue is already fixed and available in public repository. Please, check it again on the latest version.
