### ISSUE TITLE
Facebook Shop and Marketplace Support

### ISSUE THREAD

**Issue by dakira** [magento/magento2#12858]
It would be great if Magento had out-of-the-box support for Facebook sales channels. It seems some discussion on this has already been going on between Facebook and Magento (see https://github.com/facebookincubator/facebook-for-magento/issues/24).

**Comment by magento-engcom-team** [comment]
@dakira please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
