### ISSUE TITLE
Magento 2.2.0 - Out of memory - CRON might be the problem - Help

### ISSUE THREAD

**Issue by johnny-longneck** [magento/magento2#12863]
### Preconditions

1. PHP7
2. Nginx
3. Varnish
4. Magento 2.2.0

### Steps to reproduce

1. Configure cron tab
2. Adjust swap file size
### Expected result

1. Magento 2 Shop running properly.

### Actual result

1. Shop crashes while working in the backend

![htop](https://user-images.githubusercontent.com/25068173/34309551-e55d41bc-e752-11e7-9561-6ddaaf0c516e.png)

I was wondering why my shop runs out of memory all the time. Recently I adjusted the swap file size to 4G. Still running out of memory. Htop shows several cron jobs listed. 

Is that normal? What is wrong there? Please help.

**Comment by johnny-longneck** [comment]
The cron_schedule table was pretty full.
Cleaned it with "TRUNCATE TABLE cron_schedule"

Now the memory usage is back to normal

**Comment by giacmir** [comment]
This should probably be reopened since the cron_schedule full can be a symptom of an issue.

It happened to two my instances having separate database machine. It never happened when the database is on the same server.

**Comment by johnny-longneck** [comment]
@giacmir in my two production sites, db and webserver are on the same machine.
The issue is known and already fixed in 2.2.6. I can confirm this.

**Comment by giacmir** [comment]
It happened to me yesterday on a 2.2.6.

@johnny-longneck can you please provide the issue where this is tracked? I couldn't find it.

**Comment by johnny-longneck** [comment]
Did you change the settings on the backend in the system cron configuration? That was the case for me first. I had set all settings back to "use default config" after upgrade to 2.2.6.

**Comment by giacmir** [comment]
Duplicate of #11002
