### ISSUE TITLE
Re-indexing error

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1286]
Hi,
I am getting following error when re indexing. v0.74.0-beta9
![image](https://cloud.githubusercontent.com/assets/3830093/7668841/c6371092-fc6d-11e4-84ac-d9698b4db593.png)

**Comment by quynhvv** [comment]
Hi guys,

How to re-index all data in Magento 2 0.74.0 - beta 9? 
The Indexer was removed in Magento 2 0.74.0 beta 9 in folder path /dev/shell/...
I can not re-index data of Magento 2 by command line now.
Best Regards.

**Comment by quynhvv** [comment]
I have take this error too. Please check it.

On Sun, May 17, 2015 at 9:53 AM, B G Kavinga <notifications@github.com>
wrote:

> Hi,
> I am getting following error when re indexing. v0.74.0-beta9
> [image: image]
> <https://cloud.githubusercontent.com/assets/3830093/7668841/c6371092-fc6d-11e4-84ac-d9698b4db593.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1286>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by bgkavinga** [comment]
I can not see any products in listing pages. It seems to be using catalogsearch_fulltext search which fills the catalogsearch_fulltext table to display product in listing pages.
@quynhvv 
`` php -f bin/magento indexer:reindex  ``  check `` php -f bin/magento list `` for list of available commands

**Comment by mazhalai** [comment]
hello @bgkavinga and @quynhvv thank you for reporting this issue. We are tracking this issue internally with ticket MAGETWO-37400. Please watch this thread for when the fix is available.

**Comment by bgkavinga** [comment]
Hi,
This issue is no longer exists in 0.74.0-beta10. But I am getting following error
``Product Categories index has been rebuilt successfully in 00:00:00
Class Magento\Catalog\Model\Product\Attribute\Backend\Startdate does not exist``
Anyway it complete the indexing process successfully

**Comment by bgkavinga** [comment]
I have resolved above mentioned issue by replacing Startdate with Datetime in eav_attribute
