### ISSUE TITLE
Can't Disable Advanced Reporting

### ISSUE THREAD

**Issue by nfourteen** [magento/magento2#12866]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. After a fresh install of version 2.2.2, a system message was received that Synchronization Failed with Magento Business Intelligence (I don't remember the exact message).
2. To prevent further synchronization error messages, go to `Stores > Configuration > General > Advanced Reporting` and change **Advanced Reporting Service** to Disable
3. Press **Save Config**

### Expected result

1. The advanced reporting capabilities should be disabled.

### Actual result

1. The following weird error message is received: `Please select a vertical.`
2. The advanced reporting capabilities revert back to being enabled.

### Reason and Proposed Solutions

The error is thrown from `Magento\Analytics\Model\Config\Backend\Vertical::beforeSave()` method because I did not select an **Industry** under **Industry Data**. That defaults to `--Please Select--` and is an empty value, so `beforeSave()` behaves as it should.

Since the **Advanced Reporting** needs an external account and service, it should default to Disable on new installs. However, if it was Magento's intention to have it enabled for all new installs, then 1) the logic should be changed so an empty value for the **Industry** can be provided when **Advanced Reporting Service** is set to Disable and **Save Config** is pressed or 2) a more detailed error message should be displayed so merchants understand that an **Industry** must be provided, even to Disable the **Advanced Reporting Service**.

**Comment by PieterCappelle** [comment]
Hi @nfourteen, could you create PR? Thanks!

**Comment by nfourteen** [comment]
Hi @PieterCappelle, I just submitted the [pull request](https://github.com/magento/magento2/pull/12879).

**Comment by magento-engcom-team** [comment]
@nfourteen, thank you for your report.
We've created internal ticket(s) MAGETWO-86006 to track progress on the issue.

**Comment by tony-sar** [comment]
Select Disable and also select Industry data and click on save it should save . I think vertical message relate to the industry data

**Comment by jzahedieh** [comment]
![image](https://user-images.githubusercontent.com/2098908/34492460-93f09c8a-efdf-11e7-8ad3-b666b18fa054.png)

And even when you disable it the message shows in the dashboard, this is in really bad taste Magento, promoting 3rd party services on the homepage of the admin interface without being able to disable it!

All you need to do is add `ifconfig="analytics/general/enabled"` to `vendor/magento/module-analytics/view/adminhtml/layout/adminhtml_dashboard_index.xml`

**Comment by adamlavery** [comment]
Agree with the sentiment here. New features like this should be by default disabled.

**Comment by fwolfst** [comment]
Nobody is scared that this is a sign that the developers are in need (the waving flag on the sinking ship)? ;) But fully agree. Especially together with https://github.com/magento/magento2/issues/12828 where this actually drives away users customers. Anyways, thanks for the PR @nfourteen

**Comment by gfxguru** [comment]
New features disabled by default. That's a joke right? This is another attempt to reach an audience. They've been doing it for years and I'm tired of it.

**Comment by AgentGod** [comment]
I think there should be option to totally disable such external services, dotMailer is the other one

**Comment by lano-vargas** [comment]
Totally nonsense! Some sort of dictation?  2.2.2 having this client does not like.

**Comment by ob7** [comment]
2.2.6 - still an issue

**Comment by ask694** [comment]
Any solution for this issue?  I had just disable the Magento_Analytics  by  the below command,

php bin/magento module:disable Magento_Analytics

and php bin/magento setup:di:compile

now no more error notifications from Business Intelligence.

**Comment by ghost** [comment]
Is this module taking data from stores regardless if you have a paid BI account at all ?

**Comment by mikelevy300** [comment]
I'd also really like to know if data from my stores is being sent to BI without an account.  There's all kinds of privacy implications if data is being sent to Magento 1) without any kind of notification to admin users and 2) without the ability to disable it without error.  If data is being shipped, I'd like to know what is being shipped b/c again, privacy issues.

**Comment by Flipmediaco** [comment]
Magento 2.2.6

Attempting to disable Advanced Reporting...

Save Config "Advanced Reporting Service" to "Disable" Returns "You saved the configuration." but select option "Advanced Reporting Service" remains "Enable"

Reviewing configuration in mysql "core_config_data" the item path "analytics/subscription/enabled" shows value "0" after configuration saved with  "Advanced Reporting Service" set to "Disable".

The display of "Advanced Reporting Service" is not correctly reflecting the "Disable" status.

**Comment by slavvka** [comment]
Duplicate of #15259

**Comment by pintwatch** [comment]
I just hid it in the css. In my case it was the file 

/pub/static/adminhtml/Magento/backend/en_US/css/styles.css

from

.dashboard-advanced-reports {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  border-color: #e3e3e3;
  border-style: solid;
  border-width: 1px 0;
  margin-bottom: 3rem;
  padding: 2.5rem 0;
}

to

.dashboard-advanced-reports {
	display: none;
}

**Comment by patrickpeng2091** [comment]
jzahedieh

edit:  vendor/magento/module-analytics/view/adminhtml/layout/adminhtml_dashboard_index.xml

`<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceContainer name="content">
            <block ifconfig="analytics/general/enabled" template="Magento_Analytics::dashboard/section.phtml"
                   class="Magento\Backend\Block\Template"
                   name="analytics_service_external_link"
                   before="-"/>
        </referenceContainer>
    </body>
</page>`
