### ISSUE TITLE
Config values gets wiped when using depend along with AbstractFieldArray type frontend model

### ISSUE THREAD

**Issue by Floddy** [magento/magento2#12869]
### Preconditions
1. Magento 2.2 installation

### Steps to reproduce
1. Open app/code/Magento/Braintree/etc/adminhtml/system.xml
2. In the `<field id="countrycreditcard">` node, add:
`<depends>
    <field id="allowspecific">1</field>
</depends>`
3. Save, clear cache etc
4. Go to admin / stores/configuration/sales/payment methods/braintree/configure/country specific settings
5. Change the 'Payment from Applicable Countries' setting to 'Specific Countries' to show the 'Country Specific Credit Card Types' settings
6. Add settings to 'Country Specific Credit Card Types' and save
7. Change the 'Payment from Applicable Countries' setting to 'All Allowed Countries'
8. Save

### Expected result
1. The config data for 'Country Specific Credit Card Types' should be intact

### Actual result
1. The config data for 'Country Specific Credit Card Types' is wiped

Yes, the steps above is a modification, but it's the easiest way to reproduce what happens if you use it in a 3rd party module, or if it would be used in core. I am not sure this is considered to be a bug, since it's not used in core, but for us, when we developed a module which has a setting with a 'grid' in the config similar to the Braintree 'Country Specific Credit Card Types' settings, that is dependent on another config setting, this poses as a problem.

The cause of it all is that this hidden input field is used to wipe the config data when you remove all values:
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Config/view/adminhtml/templates/system/config/form/field/array.phtml#L39

For some reason unknown to me, the hidden input isn't set as disabled when the 'depend' is false, but all other inputs for the config value are:
https://github.com/magento/magento2/blob/2.2-develop/lib/web/mage/adminhtml/form.js#L531

This results in only the hidden input being posted, wiping the other config data for the field.

**Comment by magento-engcom-team** [comment]
@Floddy, thank you for your report.
We've created internal ticket(s) MAGETWO-86231 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@Floddy, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
