### ISSUE TITLE
Magento 2 the slected image for each SKU doesn't display in frontend. When I as a customer choose the color the image set to the particular color doesn't display   

### ISSUE THREAD

**Issue by Rezababa** [magento/magento2#12874]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@Rezababa , thank you for your report.
Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result
