### ISSUE TITLE
Clicking on product (Edit option) from ADMIN is throwing a FATAL ERROR: Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given

### ISSUE THREAD

**Issue by mrkkd2013** [magento/magento2#12870]
**After data Migration to 2.2.1 from 1.9**

## Clicking on product (Edit option) from ADMIN is throwing a -----"FATAL ERROR:"

 **Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given....."**

## Preconditions

1) we migrated our project from 1.9 to 2.2.1 using data migration tool.
2) Magento 2.2.1, PHP 7.1.9, MYSQL 5.7.19
3) Cleared/clean the CACHE and run the INDEXING also.
4) Logged to ADMIN section.

## Steps to reproduce

1) Go to ADMIN
2) Navigate from Catalog --> Products 
3)  click on the displayed Products. It redirects to Product Edit page and throws the below error:-

## Actual Result

`Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php on line 212 and defined in C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php:164 Stack trace: #0 C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php(212): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('mailchimp_sync_...', NULL) #1 C:\wamp64\www\xyz\vendor\magento\module-ui\Component\Form\Field.php(84): Magento\Framework\View\Element\UiComponentFactory->create('mailchimp_sync_...', 'datetime', Array) #2 C:\wamp64\www\xyz\vendor\magento\framework\View\Layout\Generator\UiComponent.php(159): Magento\Ui\Component\Form\Field->prepare() #3 C:\wamp64\www\xyz\vendor\magento\framework\View\Layout\Generator\UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiCompon in C:\wamp64\www\xyz\vendor\magento\framework\View\Element\UiComponentFactory.php on line 164
`

## Expected Result

**- should redirect to a product details Edit page and there should not be any error.**

**Can someone please help to fix this**
**Thanks in advance**

**Comment by mrkkd2013** [comment]
@magento-engcom-team Can you please help us?

**Comment by Jimmyballantyne** [comment]
Hi, I might be able to help as I had the same issue on a module and the dev fixed it by adding a definition.map.xml to Vendor\Module\view\base\ui_component\etc\

```
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_definition.map.xsd">
    <component name="YourComponent" include="abstractSettings"/>
</components>
```

Hope this helps!

**Comment by magento-engcom-team** [comment]
Hi @mrkkd2013 
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by jdprasadv** [comment]
I am also facing the same issue, I am unable to fix it, I have created own module on RMA, But I am unable to find and fix it. Please help me

Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in C:\xampp\htdocs\magento_2_project\lib\internal\Magento\Framework\View\Element\UiComponentFactory.php on line 206 and defined in C:\xampp\htdocs\magento_2_project\lib\internal\Magento\Framework\View\Element\UiComponentFactory.php:172 Stack trace: #0 C:\xampp\htdocs\magento_2_project\lib\internal\Magento\Framework\View\Element\UiComponentFactory.php(206): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('xelits_prorepla...', NULL) #1 C:\xampp\htdocs\magento_2_project\lib\internal\Magento\Framework\View\Layout\Generator\UiComponent.php(135): Magento\Framework\View\Element\UiComponentFactory->create('xelits_prorepla...', NULL, Array) #2 C:\xampp\htdocs\magento_2_project\lib\internal\Magento\Framework\View\Layout\Generator\UiComponent.php(97): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framewor in C:\xampp\htdocs\magento_2_project\lib\internal\Magento\Framework\View\Element\UiComponentFactory.php on line 172

**Comment by ankit-root** [comment]
Migrate 1.9.0.1 to 2.2.6 but I am also facing the same issue and unable to fix it. anyone, please help me

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/html/magentofirst/vendor/magento/framework/View/Element/UiComponentFactory.php on line 220 and defined in /var/www/html/magentofirst/vendor/magento/framework/View/Element/UiComponentFactory.php:172
Stack trace:
#0 /var/www/html/magentofirst/vendor/magento/framework/View/Element/UiComponentFactory.php(220): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('file_upload', NULL)
#1 /var/www/html/magentofirst/vendor/magento/module-ui/Component/Form/Field.php(84): Magento\Framework\View\Element\UiComponentFactory->create('file_upload', 'jvs_file', Array)
#2 /var/www/html/magentofirst/vendor/magento/framework/View/Layout/Generator/UiComponent.php(159): Magento\Ui\Component\Form\Field->prepare()
#3 /var/www/html/magentofirst/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Mag" while reading response header from upstream, client: 43.240.9.243, server: ehp2.localhost, request: "GET /ehplabsc_admin/catalog/product/edit/id/23/key/714f95a41933eaa486a0828f44fa72fc5c1729fe61c02c581632a089ca0aebbd/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "ehp2.localhost", referrer: "ehp2.localhost/ehplabsc_admin/catalog/product/index/key/fcd9e04fccd17cb990ed27d36020e535d83a0074fbe946ea11d3497dd037fa02/"
2019/02/13 14:34:51 [error] 12926#12926: *4696 access forbidden by rule, client: 127.0.0.1, server: ehp2.localhost, request: "POST /app/etc/config.php HTTP/1.1", host: "ehp2.localhost"

**Comment by sheshagiricorra** [comment]
I am also facing the same issue, anyone has the fix for this ?

2019/10/16 11:28:56 [error] 9318#0: *4254 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/deploy/current/vendor/magento/framework/View/Element/UiComponentFactory.php on line 222 and defined in /var/www/deploy/current/vendor/magento/framework/View/Element/UiComponentFactory.php:174
Stack trace:
#0 /var/www/deploy/current/vendor/magento/framework/View/Element/UiComponentFactory.php(222): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('folio_schedule_...', NULL)
#1 /var/www/deploy/current/vendor/magento/module-ui/Component/Form/Field.php(85): Magento\Framework\View\Element\UiComponentFactory->create('folio_schedule_...', 'datetime', Array)
#2 /var/www/deploy/current/vendor/magento/framework/View/Layout/Generator/UiComponent.php(164): Magento\Ui\Component\Form\Field->prepare()
#3 /var/www/deploy/current/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento" while reading response header from upstream, client: 14.143.1.74, server: _, request: "GET /admin_6

**Comment by palomaEcommistry** [comment]
Any update on this?

**Comment by mobweb** [comment]
To anyone finding this via Google, have a look at this issue: https://github.com/magento/data-migration-tool/issues/436

Basically you have to check your error message for some entity attribute that is shown, such as "mailchimp_sync_delta" in my case. What you then want to do is either delete this attribute manually from the EAV table in Magento 2 or use your "eav-attribute-groups.xml" file to exclude this attribute from being migrated to Magento 2.

**Comment by githubnguyendang** [comment]
help me : 
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in C:\xampp\htdocs\airpodsrep\wp-content\plugins\cf7-google-sheets-connector\lib\src\Google\Service\Resource.php:297 Stack trace: #0 C:\xampp\htdocs\airpodsrep\wp-content\plugins\cf7-google-sheets-connector\lib\src\Google\Service\Resource.php(297): implode(Array, '&') #1 C:\xampp\htdocs\airpodsrep\wp-content\plugins\cf7-google-sheets-connector\lib\src\Google\Service\Resource.php(190): Google_Service_Resource->createRequestUri('v4/spreadsheets...', Array) #2 C:\xampp\htdocs\airpodsrep\wp-content\plugins\cf7-google-sheets-connector\lib\vendor\google\apiclient-services\src\Google\Service\Sheets\Resource\SpreadsheetsValues.php(65): Google_Service_Resource->call('append', Array, 'Google_Service_...') #3 C:\xampp\htdocs\airpodsrep\wp-content\plugins\cf7-google-sheets-connector\lib\google-sheets.php(179): Google_Service_Sheets_Resource_SpreadsheetsValues->append('1dk2KPRT-falHWm...', 'airpods', Object(Google_Service_Sheets_ValueRange), Array) #4 C:\xampp\htdocs\airpodsrep\wp-content\plugins\cf7-google-sheets-connector\includes\class-gs-service.php(247): cf7gsc_googlesheet->add_row(Array) #5 C:\xampp\htdocs\airpodsrep\wp-includes\class-wp-hook.php(287): Gs_Connector_Service->cf7_save_to_google_sheets(Object(WPCF7_ContactForm)) #6 C:\xampp\htdocs\airpodsrep\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #7 C:\xampp\htdocs\airpodsrep\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #8 C:\xampp\htdocs\airpodsrep\wp-content\plugins\contact-form-7\includes\submission.php(91): do_action('wpcf7_mail_sent', Object(WPCF7_ContactForm)) #9 C:\xampp\htdocs\airpodsrep\wp-content\plugins\contact-form-7\includes\submission.php(24): WPCF7_Submission->proceed() #10 C:\xampp\htdocs\airpodsrep\wp-content\plugins\contact-form-7\includes\contact-form.php(763): WPCF7_Submission::get_instance(Object(WPCF7_ContactForm), Array) #11 C:\xampp\htdocs\airpodsrep\wp-content\plugins\contact-form-7\includes\controller.php(14): WPCF7_ContactForm->submit() #12 C:\xampp\htdocs\airpodsrep\wp-includes\class-wp-hook.php(285): wpcf7_control_init() #13 C:\xampp\htdocs\airpodsrep\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #14 C:\xampp\htdocs\airpodsrep\wp-includes\plugin.php(551): WP_Hook->do_action(Array) #15 C:\xampp\htdocs\airpodsrep\wp-includes\class-wp.php(388): do_action_ref_array('parse_request', Array) #16 C:\xampp\htdocs\airpodsrep\wp-includes\class-wp.php(745): WP->parse_request('') #17 C:\xampp\htdocs\airpodsrep\wp-includes\functions.php(1291): WP->main('') #18 C:\xampp\htdocs\airpodsrep\wp-blog-header.php(16): wp() #19 C:\xampp\htdocs\airpodsrep\index.php(17): require('C:\\xampp\\htdocs...') #20 {main} thrown in C:\xampp\htdocs\airpodsrep\wp-content\plugins\cf7-google-sheets-connector\lib\src\Google\Service\Resource.php on line 297
There has been a critical error on this website.

Learn more about debugging in WordPress.
