### ISSUE TITLE
Multiple newsletter confirmation emails sent

### ISSUE THREAD

**Issue by nfourteen** [magento/magento2#12876]
### Preconditions
1. Magento 2.2.1
2. Php 7.0

### Steps to reproduce
1. Change configuration under `Stores > Configuration > Customers > Newsletter > Subscription Options > Need to Confirm` to Yes
2. Sign up for Newsletter on frontend as a guest
3. Follow confirmation link in email
4. Create an account and check **Sign Up for Newsletter** within the form and use the same email as in **Step 2**

### Expected result

There are a couple different results that I'll leave to the Magento core team:

1. If someone signed up for a Newsletter subscription as a guest, have confirmed that subscription, and then create an account with the same email—then the Magento application could update the **Newsletter Subscribers** with the customer data and **leave the status as Subscribed**, thus no **Need to Confirm** email is sent since they've already confirmed they wanted to receive the newsletter.
2. The Magento application could change the guest email status to `STATUS_UNCONFIRMED`, update the guest email with the customer data, and send the **Need to Confirm** email for the new account.

### Actual result

1. Three **Need to Confirm** emails are received.

### Reason

The first two emails are received because of the `\Magento\Newsletter\Model\Plugin\CustomerPlugin::afterSave()` method. When `\Magento\Customer\Controller\Account\CreatePost::execute()` is called a new customer account is created on `line 313` with `\Magento\Customer\Model\AccountManagement::createAccount()`. The `createAccount()` method calls `createAccountWithPasswordHash()` whereby the customer is **saved** on `line 748` and then that same method calls `$this->changeResetPasswordLinkToken()` on `line 775`, which again **saves** the customer on `line 1242`. Thus these two customer saves trigger the `afterSave()` method calls on the `CustomerPlugin`, which updates the subscription and sends the two emails.

The third and final email is received within the `Magento\Customer\Controller\Account\CreatePost::execute()` method on `line 317` when the `is_subscribed` param is retrieved from the form data within the request and the `if` conditional equals `true` because of **Step 4** above.

**Comment by magento-engcom-team** [comment]
@nfourteen, thank you for your report.
We've created internal ticket(s) MAGETWO-85994 to track progress on the issue.

**Comment by matthiashamacher** [comment]
Hello,
We have a similar issue with the newsletter.
When the customer wants a new password (Forgot Your Password?) and when he changes his password after clicking the link in the reset E-Mail, he must confirm the newsletter another time. The confirmed newsletter subscriptions were unsubscripted.
A workaround for this is to deactivate the function "Need to Confirm".

**Comment by serhii-balko** [comment]
Hi @matthiashama 
My pull request may be fix it.

**Comment by matthiashamacher** [comment]
Hi @serhii-balko 
Are you still work on it? Or where do I find your pull request?

**Comment by serhii-balko** [comment]
Yes, it will be merged after a while
https://github.com/magento-engcom/magento2ce/pull/1139

**Comment by torhoehn** [comment]
@serhii-balko You created a pull request to a private repository. You should create your pull request for this public repository and inside of your PR you should mention this issue. So it'll be linked automatically.

**Comment by magento-team** [comment]
Hi @nfourteen. Thank you for your report. 
The issue has been fixed in magento/magento2#13044 by @torhoehn in 2.2-develop branch
Related commit(s):
 - 9ab75baec089c4a327a0c3b082f0aaedfbfb15ad
 - 93453a811e7cc5fb128fe7abd96233d47e010d4f

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @nfourteen. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1351 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 70dd5a3fa17e1ee1cdfaf7f0defd9276989ebbd0
 - 54bc3a1dca861e11e46e12f5a15578e0cb7ceb6d
 - 3debd3f87e27e23949b81cb2d7e881b5a269608c
 - 72c496566bf0d2ff1ced0401514faa5cbaccc0f8
 - e60ecdfeabe8b8839cf52fd5ba7fefcbb0b9bdc3
 - 8703b3da3dbe28f71c1daeaba08bbe44887f0733
 - bd88ed8cc4e1f98b791bd7ca8bed45c29b276ee1
 - 1c70b18a339fddf8a51a476a5a251aabef951350
 - 5fd7481d2cf8b298369837508a16a23ab4f49850
 - 7c615065b36cdafa95d752a891c09dd4ab1a4dfa
 - 2653b8ae55625637a6836d305451e292f881bd6a
 - 917a03f89f98454cb2ecde524dc8557d7fdcc135
 - eca73d0abd1ca6e110c364ef380adab86ab3cc1a
 - 26f3109842ce89096a49b9c122af0bae6b672ba2
 - c223484a75e38fdcece09d4586342528f06c6383
 - 3b90ad71d791ba9cf8e81cc204fd306f41473a18
 - ad317c25039de70c1a976e1139c57730899eb114
 - 53e721ccc06f1ade05132690715575bd7d47d6b7
 - 6114120c0a921b342871448dfb6c47bf34a65cdc
 - 63b483925c18304a32441f66b0db8a9c70995c73

The fix will be available with the upcoming 2.3.0 release.

**Comment by dayfinder** [comment]
Always stay up to date when MageExchange releases new modules, updates to our current modules, exclusive offers only for our current subscribers and so much more! MageExchange hates spam as much as you do so you never have to worry about being flooded with emails! We also respect our customer's privacy and therefore we will never sell your information to anyone. Click Here [magento 2 disable newsletter confirmation email](https://www.mageexchange.com/disable-newsletter-sign-up-emails-magento-2)

**Comment by dayfinder** [comment]
On Linux OS or Ubuntu derived machines, using sh will throw an error as sh is supposed to be used only with purely POSIX compliant scripts and Magento scripts are not 100% POSIX compliant. Instead, on Ubuntu and derived OSes such as Linux Mint, you should use this [magento   2 disable newsletter confirmation email
](https://www.mageexchange.com/disable-newsletter-sign-up-emails-magento-2)
