### ISSUE TITLE
_isUrlInternal function modification 

### ISSUE THREAD

**Issue by tejasvyas1988** [magento/magento2#12883]
I am getting the issue with the redirection with multi-website.
I am on multiwebsite and I am trying to redirect the URL from admin using the above code
return $this->_redirect($this->_redirect->getRefererUrl());

 _isUrlInternal function is creating the issue with that.
As in my code, store is changed and due to that _isUrlInternal  is always redirecting me to second website home page due to _isUrlInternal  function condition.

Can't we modify the _isUrlInternal  function definition so that it can understand the admin URL as well?

**Comment by magento-engcom-team** [comment]
@tejasvyas1988 thank you for your report, 
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
