### ISSUE TITLE
session_start(): Cannot send session cache limiter - headers already sent

### ISSUE THREAD

**Issue by akbaradeeb** [magento/magento2#12880]
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /public_html/vendor/zendframework/zend-http/src/PhpEnvironment/Response.php:114) in /public_html/vendor/magento/framework/Session/SessionManager.php on line 189

### Preconditions
Magento - 2.2.1
PHP - 7.0.22
Apache - 2.4.29
Mysql - 10.2.8-MariaDB
Redis Server Version - 4.0.1
Varnish Version -V

### Steps to reproduce
Browse the website. It will create report in /var/report and log in /var/log/exception.log

### Expected result
The website will run normaly

### Actual result
The website will run normaly but it create number of report file and some time it will show error reporting page

**Comment by akbaradeeb** [comment]
Hi 
I cpanel aws stats there were 72% 500 error.

**Comment by akbaradeeb** [comment]
@magento-engcom-team 

Please revert me. 

Full error are following

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at \/home\/everstyle\/public_html\/vendor\/zendframework\/zend-http\/src\/PhpEnvironment\/Response.php:114) in \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Session\/SessionManager.php on line 189","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'session_start()...', '\/home\/everstyle...', 189, Array)\n#1 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Session\/SessionManager.php(189): session_start()\n#2 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\Session\\SessionManager->start()\n#3 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Session\\Generic\\Interceptor->___callParent('start', Array)\n#4 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\Session\\Generic\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#5 \/home\/everstyle\/public_html\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(52): Magento\\Framework\\Session\\Generic\\Interceptor->___callPlugins('start', Array, Array)\n#6 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Session\/SessionManager.php(130): Magento\\Framework\\Session\\Generic\\Interceptor->start()\n#7 \/home\/everstyle\/public_html\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(14): Magento\\Framework\\Session\\SessionManager->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n#8 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Magento\\Framework\\Session\\Generic\\Interceptor->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State))\n#9 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#10 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#11 \/home\/everstyle\/public_html\/generated\/code\/Magento\/Framework\/Session\/Generic\/Proxy.php(84): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#12 \/home\/everstyle\/public_html\/generated\/code\/Magento\/Framework\/Session\/Generic\/Proxy.php(207): Magento\\Framework\\Session\\Generic\\Proxy->_getSubject()\n#13 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Url.php(981): Magento\\Framework\\Session\\Generic\\Proxy->getSessionIdForHost('http:\/\/everstyl...')\n#14 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Url.php(949): Magento\\Framework\\Url->_prepareSessionUrl('http:\/\/everstyl...')\n#15 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Url.php(876): Magento\\Framework\\Url->createUrl('mui\/index\/rende...', Array)\n#16 \/home\/everstyle\/public_html\/vendor\/magento\/module-ui\/Config\/Argument\/Parser\/Url.php(52): Magento\\Framework\\Url->getUrl('mui\/index\/rende...', Array)\n#17 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Data\/Argument\/Interpreter\/Composite.php(61): Magento\\Ui\\Config\\Argument\\Parser\\Url->evaluate(Array)\n#18 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Data\/Argument\/Interpreter\/ArrayType.php(44): Magento\\Framework\\Data\\Argument\\Interpreter\\Composite->evaluate(Array)\n#19 \/home\/everstyle\/public_html\/generated\/code\/Magento\/Framework\/Data\/Argument\/InterpreterInterface\/Proxy.php(95): Magento\\Framework\\Data\\Argument\\Interpreter\\ArrayType->evaluate(Array)\n#20 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Data\/Argument\/Interpreter\/Composite.php(61): Magento\\Framework\\Data\\Argument\\InterpreterInterface\\Proxy->evaluate(Array)\n#21 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Data\/Argument\/Interpreter\/ArrayType.php(44): Magento\\Framework\\Data\\Argument\\Interpreter\\Composite->evaluate(Array)\n#22 \/home\/everstyle\/public_html\/generated\/code\/Magento\/Framework\/Data\/Argument\/InterpreterInterface\/Proxy.php(95): Magento\\Framework\\Data\\Argument\\Interpreter\\ArrayType->evaluate(Array)\n#23 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Data\/Argument\/Interpreter\/Composite.php(61): Magento\\Framework\\Data\\Argument\\InterpreterInterface\\Proxy->evaluate(Array)\n#24 \/home\/everstyle\/public_html\/vendor\/magento\/module-ui\/Config\/Reader\/Definition\/Data.php(147): Magento\\Framework\\Data\\Argument\\Interpreter\\Composite->evaluate(Array)\n#25 \/home\/everstyle\/public_html\/vendor\/magento\/module-ui\/Config\/Reader\/Definition\/Data.php(102): Magento\\Ui\\Config\\Reader\\Definition\\Data->evaluateComponentArguments(Array)\n#26 \/home\/everstyle\/public_html\/vendor\/magento\/module-ui\/Config\/Reader\/Definition\/Data.php(81): Magento\\Ui\\Config\\Reader\\Definition\\Data->initData()\n#27 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Magento\\Ui\\Config\\Reader\\Definition\\Data->__construct(Object(Magento\\Ui\\Config\\Reader\\DefinitionFactory), Object(Magento\\Framework\\App\\Cache\\Type\\Config), Object(Magento\\Framework\\Serialize\\Serializer\\Json), Object(Magento\\Framework\\Data\\Argument\\Interpreter\\Composite))\n#28 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Ui\\\\Conf...', Array)\n#29 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Ui\\\\Conf...')\n#30 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(144): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Ui\\\\Conf...')\n#31 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'definitionData', 'Magento\\\\Framewo...')\n#32 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#33 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#34 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#35 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(144): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#36 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'uiComponentFact...', 'Magento\\\\Framewo...')\n#37 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#38 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#39 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#40 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(180): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#41 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(156): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->parseArray(Array)\n#42 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, NULL, NULL, 'generators', 'Magento\\\\Framewo...')\n#43 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#44 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#45 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#46 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(144): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#47 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'generatorPool', 'Magento\\\\Framewo...')\n#48 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#49 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#50 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#51 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(144): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#52 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'layout', 'Magento\\\\Framewo...')\n#53 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#54 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#55 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#56 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(144): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#57 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'templateContext', 'Mirasvit\\\\CacheW...')\n#58 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Mirasvit\\\\CacheW...', Array, Array)\n#59 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Mirasvit\\\\CacheW...', Array, Array)\n#60 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Mirasvit\\\\CacheW...')\n#61 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(144): Magento\\Framework\\ObjectManager\\ObjectManager->get('Mirasvit\\\\CacheW...')\n#62 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(230): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Mirasvit\\\\CacheW...', NULL, 'debugService', 'Mirasvit\\\\CacheW...')\n#63 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Mirasvit\\\\CacheW...', Array, Array)\n#64 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Mirasvit\\\\CacheW...', Array, Array)\n#65 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Mirasvit\\\\CacheW...')\n#66 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php(250): Magento\\Framework\\ObjectManager\\ObjectManager->get('Mirasvit\\\\CacheW...')\n#67 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(133): Magento\\Framework\\Interception\\PluginList\\PluginList->getPlugin('Magento\\\\PageCac...', 'cache-warmer-de...')\n#68 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#69 \/home\/everstyle\/public_html\/generated\/code\/Magento\/PageCache\/Model\/App\/FrontController\/BuiltinPlugin\/Interceptor.php(26): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin\\Interceptor->___callPlugins('aroundDispatch', Array, NULL)\n#70 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin\\Interceptor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#71 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#72 \/home\/everstyle\/public_html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#73 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#74 \/home\/everstyle\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#75 \/home\/everstyle\/public_html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#76 {main}","url":"\/\/customer\/section\/load\/?_=1515757243745","script_name":"\/index.php"}

**Comment by ghost** [comment]
@akbaradeeb, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
