### ISSUE TITLE
Magento 2.2.2 setup:install fails on missing argument scopetype of Magento\Framework\Module\Output\Config

### ISSUE THREAD

**Issue by linden2015** [magento/magento2#12890]
### Preconditions

1. MySQL: 14.14 Distrib 5.7.20, for Linux (x86_64)
2. PHP: 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce

1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition:2.2.2 ./`
2. copy `app/etc/env.php` from `2.1.10` installation, and change database names
3. Mysql: `create database magento_2_2_2`
4. ```php bin/magento setup:install \
    --backend-frontname "admin" \
    --db-host "localhost" \
    --db-name "magento_2_2_2" \
    --db-user "root" \
    --admin-firstname "admin" \
    --admin-lastname "admin" \
    --admin-email "admin@admin.com" \
    --admin-user "admin" \
    --admin-password "mypassword123" \
    --base-url "https://magento-2-2-2-main.mycompany.com/" \
    --base-url-secure "https://magento-2-2-2-main.mycompany.com/" \
    --language "en_US" \
    --currency "EUR" \
    --timezone "Europe/Amsterdam" \
    --session-save "db" \
    --use-secure "1" \
    --use-secure-admin "1" \
    --admin-use-security-key "1" \
    --use-rewrites "1" \

    ```

### Expected result
<!--- Tell us what should happen -->
1. No errors

### Actual result
<!--- Tell us what happens instead -->
1. Error: `[Progress: 177 / 797] Module 'Magento_GoogleTagManager': [BadMethodCallException] Missing required argument $scopeType of Magento\Framework\Module\Output\Config.`

<!--- (This may be platform independent comment) -->

**Comment by linden2015** [comment]
* When using `--db-password` the error did not occur.
* In Magento 2.1.10 it was possible to use a blank password (`--db-password ""`)
* In Magento 2.2.2 it is not possible to use a blank password, and the only solution is to create a mysql user with a non-blank password

**Comment by magento-engcom-team** [comment]
@linden2015 thank you for your report. 

The Module 'Magento_GoogleTagManager' is not present in version Magento Open Source.

Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways: You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by kirkmadera** [comment]
We ran into issues like this when using our existing app/etc/env.php with Redis caches configured reinstalling into a new database. When we disabled the GoogleTagManager module, we ran into failure after failure in other modules.

Try deleting your app/etc/env.php before running the install command. You should also drop and recreate your db.

**Comment by geerlingguy** [comment]
@kirkmadera - We had the exact same issue; I moved the `app/etc/env.php` file to `app/etc/env.php.bak` before the install, then moved it back post install, and it seemed to work okay then.
