### ISSUE TITLE
Customer account navigation block container doesn't have a "name" or "as" attribute (fix included)

### ISSUE THREAD

**Issue by Lez-2** [magento/magento2#12892]
### Preconditions
Magento 2.2.0

### Steps to reproduce
1. Open the Customer account link e.g. http://domain.com/customer/account while logged in and you can see through any browser debugger that the html surrounding the customer navigation menu is:
```
<div class="block account-nav">
    <div class="title account-nav-title">
        <strong></strong>
    </div>
<div id="account-nav" class="content account-nav-content">
...
</div>
```
The title is always empty, but it is expected.
And you can't add the title because the containing block of the customer account navigation, which is located in .../vendor/magento/module-customer/view/frontend/layout/customer_account.xml, doesn't have a "name" or "as" attribute which is used to reference the block.

### Expected result
1. the customer_account.xml located in .../vendor/magento/module-customer/view/frontend/layout/ should have the block named something like "customer-account-navigation-containter" (with or without a default title argument):
```
<block class="Magento\Framework\View\Element\Template" name="customer-account-navigation-container" template="Magento_Theme::html/collapsible.phtml" before="-">
    <arguments>
        <argument name="block_css" xsi:type="string">account-nav</argument>
	<argument name="title" xsi:type="string" translate="true">Account menu</argument>
    </arguments>
    <block class="Magento\Customer\Block\Account\Navigation" name="customer_account_navigation" before="-">
...
```

### Actual result
1. The current customer_account.xml doesn't have a name or as attribute for the collapsible template container of the menu: 
```
<block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/collapsible.phtml" before="-">
    <arguments>
        <argument name="block_css" xsi:type="string">account-nav</argument>
    </arguments>
    <block class="Magento\Customer\Block\Account\Navigation" name="customer_account_navigation" before="-">
...
```

**Comment by devamitbera** [comment]
#mm18in

**Comment by Lez-2** [comment]
Seems this issue already has a fix in M 2.2.2

```
<referenceContainer name="sidebar.main">
            <block class="Magento\Framework\View\Element\Template" name="sidebar.main.account_nav" template="Magento_Theme::html/collapsible.phtml" before="-">
                <arguments>
                    <argument name="block_css" xsi:type="string">account-nav</argument>
                </arguments>
                <block class="Magento\Customer\Block\Account\Navigation" name="customer_account_navigation" before="-">
```

**Comment by ishakhsuvarov** [comment]
@Lez-2 Closing this issue, as solution is delivered to 2.2
Thank you

**Comment by devamitbera** [comment]
@ishakhsuvarov ,thanks
