### ISSUE TITLE
routeIdType doesn't allow numbers

### ISSUE THREAD

**Issue by mzeis** [magento/magento2#1290]
When defining a route in `etc/frontend/routes.xml`:

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/App/etc/routes.xsd">
        <router id="standard">
            <route id="mzeis_test123" frontName="test123">
                <module name="Mzeis_Test123" />
            </route>
        </router>
    </config>

The XSD doesn't allow to use numbers in the `id` attribute of the `route` node, see [routes.xsd](https://github.com/magento/magento2/blob/1a490f5be0c3ff2ae26c9ae7fe1610865cf9dec4/lib/internal/Magento/Framework/App/etc/routes.xsd#L95) and [routes_merged.xsd](https://github.com/magento/magento2/blob/1a490f5be0c3ff2ae26c9ae7fe1610865cf9dec4/lib/internal/Magento/Framework/App/etc/routes_merged.xsd#L95).

Is there a reason for doing that? Given that numbers are valid in the module names as well as `routerIdType` and I expect developers to use the name of the module for the route id in many cases I'd suggest to allow numbers (or better: the same pattern as for the module name).

**Comment by anupdugar** [comment]
Thanks for reporting the issue @mzeis.
Yes, it makes sense to allow numbers for route id attribute. I have created an issue to track this : MAGETWO-37855

**Comment by cmuench** [comment]
:+1:  We need numbers to. Our prefix starts with "n98".

**Comment by vpelipenko** [comment]
@mzeis, internal ticket is closed and resolved, so fix is on public github. Are you OK with these changes?

**Comment by mzeis** [comment]
Didn't test but the code change looks good, thanks.
