### ISSUE TITLE
Missing getter and setters for shipping address

### ISSUE THREAD

**Issue by FreekVandeursen** [magento/magento2#12903]
Magento\Sales\Api\Data\OrderInterface has no function definitions for getShippingAddress and setShippingAddress, although those functions do exist in Magento\Sales\Model\Order class.

I don't know if those functions were intentionally omitted from the interface, but it seems logical to have them in the interface as well.

I could make a pull request to fix this, but I assume this would be considered a non backward compatible change?

**Comment by ishakhsuvarov** [comment]
Hi @FreekVandeursen 
Please take a look at the `\Magento\Sales\Api\Data\ShippingAssignmentInterface` which is an extension attribute for the `OrderInterface`.
It is expected to contain the shipping address for the order.

**Comment by FreekVandeursen** [comment]
I did find that one @ishakhsuvarov , but wouldn't it still make sense to have the Model\Order class in sync with the OrderInterface? The implementing class does have a getter and setter for the shipping address after all.

**Comment by ishakhsuvarov** [comment]
It was removed before the 2.0 release to theoretically allow support for multiple addresses. Old method was not suitable for it.

**Comment by FreekVandeursen** [comment]
That does seem to make sense :)
Thanks for the explanation

**Comment by ishakhsuvarov** [comment]
@FreekVandeursen By the way, same applies to the Quote APIs.
Thanks.
