### ISSUE TITLE
Preference in the wrong di.xml file

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1291]
This line from the `di.xml` file of the `Magento_Catalog` module 

    <preference for="Magento\Framework\Pricing\PriceCurrencyInterface" type="Magento\Directory\Model\PriceCurrency" />

should be moved to the `Magento_Directory` module. 
Having it like it is now forces a dependency that's not needed.

[EDIT]  
While on the subject I found this line

    <preference for="Magento\Authorization\Model\UserContextInterface" type="Magento\Authorization\Model\CompositeUserContext"/>

in 3 different places `Magento/Quote/etc/di.xml`, `Magento/Webapi/etc/webapi_rest/di.xml` and  `Magento/Webapi/etc/webapi_soap/di.xml`. Shouldn't this be moved to the `Magento_Authorization` module?  

This issue is based on what I understood so far about the `di.xml` files. if I have it wrong please let me know.

**Comment by anupdugar** [comment]
@tzyganu Thanks for pointing out the discrepancies. We have created an issue to investigate and fix it - MAGETWO-37820.

**Comment by tzyganu** [comment]
@anupdugar Should I add other discrepancies I find in here, or open separate issues for each module? I found an other one in `Magento_Eav` module that should be moved to `Catalog`.

**Comment by anupdugar** [comment]
@tzyganu Feel free to add it here and i will create separate issues if needed.

**Comment by tzyganu** [comment]
@anupdugar 
In the `di.xml` for the `Eav` module there is this:

    <type name="Magento\Eav\Model\EavCustomAttributeTypeLocator">
        <arguments>
            <argument name="serviceEntityTypeMap" xsi:type="array">
                <item name="Magento\Catalog\Api\Data\ProductInterface" xsi:type="const">Magento\Catalog\Api\Data\ProductAttributeInterface::ENTITY_TYPE_CODE</item>
            </argument>
            <argument name="serviceBackendModelDataInterfaceMap" xsi:type="array">
                <item name="Magento\Catalog\Api\Data\ProductInterface" xsi:type="array">
                    <item name="Magento\Catalog\Model\Product\Attribute\Backend\Media" xsi:type="string">Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryInterface</item>
                </item>
            </argument>
        </arguments>
    </type>

I think it should contain only

    <type name="Magento\Eav\Model\EavCustomAttributeTypeLocator">
        <arguments>
            <argument name="serviceEntityTypeMap" xsi:type="array" />
           <argument name="serviceBackendModelDataInterfaceMap" xsi:type="array" />
        </arguments>
    </type>

the rest should be moved to the catalog module.

Also the `Magento\Eav\Model\Entity\Setup\PropertyMapper` class depends on the `Magento\Catalog\Model\Resource\Eav\Attribute` class for this line 

    'is_global' => $this->_getValue($input, 'global', Attribute::SCOPE_GLOBAL)

In theory I should be able to remove the catalog module but the 2 dependencies mentioned above make it impossible. And they can be overcome easily.

**Comment by anupdugar** [comment]
@tzyganu That makes sense. Will add these to the internal ticket. Re-prioritized so that the dependency issues can be cleaned up earlier.

**Comment by daim2k5** [comment]
Fixed. If not please feel free to reopen the issue.
