### ISSUE TITLE
Web Setup Wizard issue When session storage  is  memcached

### ISSUE THREAD

**Issue by hirale** [magento/magento2#12913]
### Preconditions

Magento 2.2.2
PHP 7.0
mysql 5.6
memcached 

### Steps to reproduce
1. in app/etc/env.php . changed session storage
'session' => 
  array (
    'save' => 'memcached',
    'save_path' => '127.0.0.1:11211',
  ),
2. open web setup from backend.

### Expected result
it should open setup page

### Actual result

1. when open Web Setup Wizard ,it returns HTTP 500 ,url is "domain.com/setup/"
![20171228234547](https://user-images.githubusercontent.com/22028058/34425091-4644edec-ec29-11e7-9224-a870fbe7a9c7.png)

**Comment by magento-engcom-team** [comment]
thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by hirale** [comment]
### Preconditions


Magento 2.2.2
PHP 7.1.12
mysql 5.6
memcached 

### Steps to reproduce
1. in app/etc/env.php . changed session storage
'session' => 
  array (
    'save' => 'memcached',
    'save_path' => '127.0.0.1:11211',
  ),
2. open web setup from backend.

### Expected result
it should open extension setup page

### Actual result

1. when open Web Setup Wizard ,it returns

Fatal error: Uncaught Exception: Warning: SessionHandler::read(): open(127.0.0.1:11211/sess_6v3psl48nq5d5q2b06aavv9hpq, O_RDWR) failed: No such file or directory (2) in /home/app/public_html/vendor/magento/framework/Session/SaveHandler/Native.php on line 22 in /home/app/public_html/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'SessionHandler:...', '/home/app...', 22, Array) #1 /home/app/public_html/vendor/magento/framework/Session/SaveHandler/Native.php(22): SessionHandler->read('6v3psl48nq5d5q2...') #2 /home/app/public_html/vendor/magento/framework/Session/SaveHandler.php(93): Magento\Framework\Session\SaveHandler\Native->read('6v3psl48nq5d5q2...') #3 [internal function]: Magento\Framework\Session\SaveHandler->read('6v3psl48nq5d5q2...') #4 /home/app/public_html/vendor/mag in /home/app/public_html/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by hirale** [comment]
I got memcached session default prefix "memc.sess." in phpinfo.
But in the error it tried to read session with prefix sess_

**Comment by Jonatasmz** [comment]
same here!

**Comment by grago** [comment]
I am experiencing the same error. Here's my output:

`Fatal error:  Uncaught Exception: Warning: SessionHandler::read(): open(127.0.0.1:11211/sess_vt91spfvab5k7fmvehqtf1c3f5, O_RDWR) failed: No such file or directory (2) in /var/www/html/vendor/magento/framework/Session/SaveHandler/Native.php on line 22 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61\nStack trace:\n#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'SessionHandler:...', '/var/www/html/v...', 22, Array)\n#1 /var/www/html/vendor/magento/framework/Session/SaveHandler/Native.php(22): SessionHandler->read('vt91spfvab5k7fm...')\n#2 /var/www/html/vendor/magento/framework/Session/SaveHandler.php(93): Magento\\Framework\\Session\\SaveHandler\\Native->read('vt91spfvab5k7fm...')\n#3 [internal function]: Magento\\Framework\\Session\\SaveHandler->read('vt91spfvab5k7fm...')\n#4 /var/www/html/vendor/magento/framework/Session/SessionManager.php(189): session_start()\n#5 /var/www/html/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(167): Magento\\Framework\\Session\\SessionManager->start in /var/www/html/vendor/magento/framework/App/ErrorHandler.php on line 61`

**Comment by engcom-backlog-nickolas** [comment]
Hello @Naturegreen, thank you for your report. This issue already has been fixed in 2.2.5 - which is current release version.
