### ISSUE TITLE
Tiered pricing and quantity Increments do not work with decimal inventory

### ISSUE THREAD

**Issue by duffner** [magento/magento2#12914]
### Preconditions

1. Magento 2.2.2
2. PHP 7.0
3. MySQL 5.6 

### Steps to reproduce

**Tiered Pricing Issue:**
1. Create Simple Product 
2. Set Inventory to 100
3. Set "Qty Uses Decimals" in Advanced Inventory to "Yes"
3. Set Base Price to 3.99
4. Open Advanced Pricing tab 
5. Set a Tiered Price for Qty of .5 and price of 2.99 
6. Save 

**Quantity increment issue:**
1. Open Advanced Inventory 
2. Set "Enable Qty Increments" to "Yes" 
3. Set "Qty Increments" to ".5" 
4. Save 

### Expected result

1.  During each of the above scenarios, the product should save and allow tiered pricing and qty increments to work with decimal-based inventory

### Actual result

1. Product does not save, admin user is given error stating "Please enter a valid number" 

<img width="1184" alt="screen shot 2017-12-28 at 8 57 43 pm" src="https://user-images.githubusercontent.com/7387019/34428580-ff7278fe-ec13-11e7-8309-bf3be093d88b.png">
<img width="1005" alt="screen shot 2017-12-28 at 9 00 18 pm" src="https://user-images.githubusercontent.com/7387019/34428581-ff84407a-ec13-11e7-9803-1882d4dc5b39.png">

This feature works as expected in Magento 1 EE, and is the basis for many of our customers who sell by .5, .25 lb increments but inventory by the 1lb of product.  This prevents a customer from selling .25 lbs for $3.00 but selling 1lb for $10.00 as tiered pricing does not allow decimals.  Additionally, since many customers sell in quantity increments under 1, a user should not be able to order .001 lbs as it's too little to measure.

**Comment by duffner** [comment]
For reference, an Enterprise Support ticket was also filed: Ticket #03228956

**Comment by magento-engcom-team** [comment]
@duffner, thank you for your report.
We've created internal ticket(s) MAGETWO-86164 to track progress on the issue.

**Comment by duffner** [comment]
AdditIonal note: This same issue also affects bundle product options.  If you add a simple product that allows decimal inventory to a bundle product’s bundle options the same “please enter a valid number in this field” error appears.

**Comment by vasilii-b** [comment]
Hi!
@duffner , I'm on my way of fixing this.

During issue solving I also found that after saving the product with _Qty Decimals_ enabled, _Qty Increments_ and _Tier Price Quantity_ are integer numbers. This will be fixed as well.

@magento-engcom-team, could you please assign the issue to me ?


Thanks & Cheers!

**Comment by duffner** [comment]
@vasilii-b, awesome!  I appreciate your quick response! 👍

**Comment by duffner** [comment]
@vasilii-b, it also appears that your noted issue with integer vs decimal numbers affects the front-end in the same way, e.g. mini cart and checkout

**Comment by vasilii-b** [comment]
Thanks for letting me know, @duffner

**Comment by duffner** [comment]
@vasilii-b , is there a commit relating to the January 2018 milestone?  I'd be glad to test as well

**Comment by vasilii-b** [comment]
@duffner I'm preparing the PR for tomorrow.

**Comment by duffner** [comment]
When will this be released?

**Comment by duffner** [comment]
@okorshenko, do we know what release version this issue will be corrected in?

**Comment by Crossmotion** [comment]
Any news on the release date for this yet?

**Comment by alexbogias** [comment]
Any news on this @vasilii-b?

**Comment by vasilii-b** [comment]
@alexbogias working on the PR travis issues... I believe in the next month it's gonna be merged for sure.

**Comment by alexbogias** [comment]
Thanks for letting us now @vasilii-b

**Comment by thatguynz** [comment]
Any update as to which release this resolution is likely to appear in?  I'm interested as it resolves an issue I raised some time ago that was incorrectly reclassified as a "feature request"..

https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/Product-Bundle-Items-can-t-have-a-decimal-default-quantity/idi-p/73599

Cheers.

**Comment by anshgreensoft** [comment]
this is resolved or not ??

**Comment by duffner** [comment]
This is not resolved

**Comment by KatPham0304** [comment]
Thank you @engcom-backlog-nazar! Any update on fixing this issue, and if not is there a special code that we can add to temporarily fix this?

**Comment by duffner** [comment]
@magento-engcom-team, unfortunately, I left the Magento Partner I was at, but Magento EE support has a fix for this that they've shared with me previously, however, I no longer have access and I'm hoping they can provide this to the community!

**Comment by KatPham0304** [comment]
@duffner Thank you very much for the reply. Could you provide us with contact info of Magento EE? This issue seems to be left here forever with no udpates :( . 

Or do you think we could apply another approach? Will the new Magento version work with this feature?

**Comment by duffner** [comment]
@KatPham0304, unfortunately, Magento EE support is private.  I was hoping that be referencing Magento Eng team they would look up this ticket and share.

**Comment by duffner** [comment]
@vasilii-b, this was fixed via the EE support team I believe, but I don't know if this fix ever made it back to the community. 

Has any progress been made here?   This is blocking a merchant who sells be weight from migrating from m1 to m2.

**Comment by vinaysaini05** [comment]
Has any solution been found yet?

**Comment by duffner** [comment]
I just pulled Magento 2.3 vanilla and this is still an issue.  The issue with decimal based inventory now works on the front-end for standard pricing, but the second case of my original issue still exists.  

It appears that the issue maybe now just validation related on the inputs within the Admin, but the following use case which exists as a feature in m1 does not work almost 3 years later!!!! 

Enter the following values into the product 

Base Price 10.00
Advanced Pricing 
Qty .5 ----> Discount "Percentage " value 10%
Qty .75 ----> Discount "Percentage " value 25%
Qty 1 -----> Discount "Percentage " value 50%

<img width="1062" alt="screen shot 2018-12-07 at 6 04 08 pm" src="https://user-images.githubusercontent.com/7387019/49678574-d3a30400-fa4a-11e8-8e08-b26aeb153547.png">

Then Save the product 


Review Advanced Pricing: And the following result is displayed. 
Qty 0 ----> Discount "Percentage " value 25% (error displayed) 
Qty 1 -----> Discount "Percentage " value 50%

<img width="993" alt="screen shot 2018-12-07 at 6 07 19 pm" src="https://user-images.githubusercontent.com/7387019/49678611-1533af00-fa4b-11e8-8a8b-0069653dada2.png">

Tiered pricing with decimals does not save.

**Comment by duffner** [comment]
Once this is corrected, the tiered pricing "Buy .5 and save 10%" will likely not work as well.  Any business that sells by weight in decimal quantities cannot leverage Magento.  This was a Magento feature in m1 for almost 10 years!  Let's not let it die in m2.  

@magento-engcom-team, @vasilii-b it would be great to know what's going to happen here!  

Thank you, 

Robert

**Comment by thatguynz** [comment]
I assume that now this issue is unassigned we are unlikely to see a resolution any time soon?  It sounded so promising for a while but regrettably it is still a showstopper for me to be able to migrate my web shop across to Magento.  If I had any clue about coding I'd have a go myself but that isn't where my skills lie unfortunately..

**Comment by vasilii-b** [comment]
@thatguynz there is actually a pull request #13359 to fix it, but as you can see from its history its not going to be merged - we are kindly forced to cover with tests...

**Comment by thatguynz** [comment]
So in a nutshell - at this stage nothing is likely to happen with it until someone else picks it up which would seem to be fairly unlikely?

**Comment by duffner** [comment]
@vasilii-b, these types of things make it so frustrating to like Magento.  This is a blatantly missing feature and Magento is more focused about Unit Tests than missing/broken functionality.  Not your fault at all, but every ticket I've created seems to go this same way.  At some point, why should the community care?    

@magento-engcom-team , is this the plan?

**Comment by thatguynz** [comment]
I assume there has been no further development here?  Seems that Magento is a beautiful platform if you're selling widgets that are dealt with in Integers but as soon as a Decimal requirement exists, it falls down badly..

**Comment by duffner** [comment]
@magento-engcom-team, Do we have any updates here?

**Comment by gotanasro3** [comment]
Do we have any updates here?

**Comment by engcom-Alfa** [comment]
Hi, @duffner. Thank you for your reporting.

We are not able to reproduce this issue on the fresh 2.4-develop instance. Everything works well.
So we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. 
Thank you for collaboration.
