### ISSUE TITLE
Warning: Illegal offset type in isset or empty in /var/www/html/unicorn-magento/vendor/magento/module-ui/Config/Reader/Definition/Data.php on line 126

### ISSUE THREAD

**Issue by NagamaniNaresh** [magento/magento2#12916]
I have upgraded my store from M2.1.4 to M2.2.1, Upgradation was successful, once after that i can't able to edit products from admin. I am getting error message.

### Preconditions
1. Magento v. 2.2.1
2. PHP 7.1.12
3. nginx/1.10.3 (Ubuntu)

### Steps to reproduce
1. Upgrade Magento from older version to M2.2.1
2. Log in to admin
3. Edit any Product

### Expected result
1. It should allow us to edit the product.

### Actual result
1. Warning: Illegal offset type in isset or empty in /var/www/html/unicorn-magento/vendor/magento/module-ui/Config/Reader/Definition/Data.php on line 126

![local unicorn com admin catalog product edit id 2](https://user-images.githubusercontent.com/10627199/34430665-62d92734-ec8d-11e7-9fae-c0b7e511ef46.png)

**Comment by magento-engcom-team** [comment]
@NagamaniNaresh , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by NagamaniNaresh** [comment]
Thanks @magento-engcom-team. Sorry, It was due to the Third party module which i have used, so I am closing the issue.

**Comment by OZZlE** [comment]
@NagamaniNaresh which third party module? I'm having the same issue :(

**Comment by reinisziedins** [comment]
@NagamaniNaresh Naw really, drop the beans, man.

**Comment by hayatbiralem** [comment]
Hi guys,

I had the same problem and I just fixed by deleting some sequence definitions in my own custom extensions' module.xml

It seems we should pay more attention to that sequence/dependency definitions.

**Comment by arpitavshah** [comment]
You can also check the custom attribute which is getting used to create configurable product. I had issue in the custom attribute and deleting the custom attribute and recreating it resolved my issue
