### ISSUE TITLE
We are blocked from our Webbuilder EVATO

### ISSUE THREAD

**Issue by FernandVdd** [magento/magento2#12925]
### Preconditions
Magento 2.1.10 // We pay to be a GITHUB member... // Please read this. Thank you in advance. // We don't find solution...

We've ordered, with EVATO (Bornem) in Belgium, on the 22nd of June 2016, a new website to synchronize online our products, clients, offers, orders and invoices in our ERP system. 

After more than 1000 e-mails further (about the problems in Magento2 --> because of their inexperience )  on the 22nd of NOVEMBER 2017 (YES, MORE THAN 15 months later) they said that everything was finished. After a check we note that some things, that we had in our PAID order (25000€uro excl VAT) , are not delivered. 

Because we complained and threatened with a lawsuit, they blocked us. We cannot syncronize products.  When we synchronize a product, the message we receive is 'no subscription available'. 
When we did the order they did'nt talk about any subscription fee. Only about a 'keeping alive' contract. Because of the high amount to build our website we did'nt want to take this. We said 'When there's a problem and you have to resolve this, we will pay for it'.

Now they refer to their general conditions  (they send them us on the 2nd of August 2016. Remember our order on 22/6/2016) that we have to pay a monthly fee for synchronizing. After checking, we are their first MAGENTO2 client....

Is this a normal procedure in the world of MAGENTO2 ? They promised us so much. Now this is a heavy disguise and a (to) long story to tell ...

We want a solution outside the court but they don't answer our phone calls or e-mails anymore. We cannot work on a normal way with our website and and suffer loss of sales.

On the 2nd of January 2018 we will start a trial trough the court and I think that this is a war without winners.

Is there somebody that can help us or has experience with this kind of things?
Can you give also your opinion about this new website?

HELP!!!

### Expected result

1. Can we find somebody to help us?
send an e-mail to fernand@verlichting.be
Company: Verlichting.be
Website: https://verlichting.be/
Thank you very much in advance!!!

Fernand Vandendriessche
General MAnager of Verlichting.be BVBA

**Comment by southerncomputer** [comment]
Yes seen a lot of folks dipping their feet into M2 when they thought they were proficient in M1 - that fails.

Not sure why because M2 is not much different than M1 really!

**Comment by magento-engcom-team** [comment]
@FernandVdd  thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by FernandVdd** [comment]
Dear,

Thank you for your information.
Can you please cancel also the monthly fee?

Best regards,

Fernand
www.verlichting.be





Van: Magento Community Engineering [mailto:notifications@github.com]
Verzonden: woensdag 3 januari 2018 7:13
Aan: magento/magento2 <magento2@noreply.github.com>
CC: Fernand VERLICHTING.BE <Fernand@verlichting.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [magento/magento2] We are blocked from our Webbuilder EVATO (#12925)


@FernandVdd<https://github.com/fernandvdd> thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal.

GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
