### ISSUE TITLE
Composer Install Outputing 

### ISSUE THREAD

**Issue by nomuprive** [magento/magento2#12926]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by nomuprive** [comment]
Hi. 

When I run the command, "composer install" I get the error that my PHP verion 5.6.32 does not meet Zend framework requirements. However, I'm not running PHP version 5.6.32  I'm running PHP 7.1. I also tried running PHP version 7 but still it keeps giving the same error. Please check screenshot here: http://prntscr.com/htxnm1

Thanks!

**Comment by avoelkl** [comment]
Hi @williambize,
what is the output of `php -v` when you run it on the command line?
It is also possible that you run a different PHP version for CLI and via webserver. Please check your configuration settings. Compare the output of `php -v` with a phpinfo() ran via browser. If the version differs and you are running this on the server of a hosting provider, contact them for more information.
If it's your local setup, check and fix your settings.

Edit:
It seems this is a problem of your PHP setup and not a Magento problem.

**Comment by nomuprive** [comment]
@avoelkl  thanks for the support!

From what I'm seeing, and I just checked my server WHM/cPanel settings and can confirm that PHP 7.1 is selected. And when I ran the command, "php -v" via SSH it showing that my php version is 7.1.12. Then when I ran the command, "composer install" again it gives the same error and showing my php version is 5.6. Please check screenshot here: http://prntscr.com/huad36

Thanks!

**Comment by fooman** [comment]
composer install will install what is currently locked in the composer.lock file. It seems the composer.lock file was created on php 5.6. Please delete the composer.lock file and rerun the composer install command.

**Comment by nomuprive** [comment]
@fooman Thanks for the help.

What is the right command line to remove the "composer.lock" file? I have tried using `composer remove composer.lock` but it's giving error.

Thanks!

**Comment by fooman** [comment]
@williambize please use `rm composer.lock` to delete the file.

**Comment by nomuprive** [comment]
@fooman Thanks for the help! Unfortunately when I ran the given command `rm composer.lock` it gave error. Please check screenshot here: http://prntscr.com/hvt15c . At this point I would like to completely remove composer from the server and start all over again. Any suggestions?

**Comment by fooman** [comment]
@williambize re-installing composer would not help. It currently sounds like you might need to hire someone to help you with the installation.

Best of luck.
