### ISSUE TITLE
Admin menu with 1 submenu item does not show the subitem.

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1292]
**Version**
Magento2-0.74.0-beta9

**Steps to reproduce**  
I'm creating my own extension for learning purposes and this should add a new menu item in the backend with a single submenu item.  

This is the code from my module's `adminhtml/menu.xml`

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../Magento/Backend/etc/menu.xsd">
        <menu>
            <add id="Sample_News::news" title="News" module="Sample_News" sortOrder="63" resource="Sample_News::news"/>
            <add id="Sample_News::author" title="Authors" module="Sample_News" sortOrder="10" action="sample_news/author" resource="Sample_News::author" parent="Sample_News::news"/>
        </menu>
    </config>

**Expected result**
I should see my menu item in the backend and when clicking on it I should see a submenu with 1 item
![expected](http://i.imgur.com/ybtFmNm.png)

**Actual result**  
I see my main menu, but when clicking it there is just an empty submenu
![result](http://i.imgur.com/1i3b2wk.png)

**Note**
The problem does not appear if I add a second submenu item to my main menu item.  

**Posible fix**

I noticed that if I change the in method `Magento\Backend\Block\Menu::renderNavigation`  this line

    if (count($menu) > 1 || $level != 1) {

to this

    if (count($menu) > 0 || $level != 1) {

my menu appears as expected.

**Comment by anupdugar** [comment]
@tzyganu Thanks for reporting this bug. I have created an issue MAGETWO-37904 to track and get it fixed.

**Comment by vpelipenko** [comment]
@tzyganu, the fix is available from 0.74.0-beta13. Could you check it on the latest version?

**Comment by tzyganu** [comment]
@vpelipenko It seams to work fine now. Thanks for the quick fix.
