### ISSUE TITLE
Store code issue with magento 2.2.2

### ISSUE THREAD

**Issue by coexksa** [magento/magento2#12933]
I've issue with store code URL, Although i changed option "Add Store Code to Urls" = yes but still getting store code pulse " ?___from_store" when i switch between 2 stores. kindly your support. 

https://coexksa.com/en/?___from_store=ar
https://coexksa.com/ar/?___from_store=en

**Comment by coexksa** [comment]
Dear Gents , 
Kindly update

**Comment by magento-engcom-team** [comment]
@coexksa, thank you for your report.
We've created internal ticket(s) MAGETWO-86234 to track progress on the issue.

**Comment by coexksa** [comment]
@magento-engcom-team
Could  you provide me  solution In current version?

**Comment by p-bystritsky** [comment]
@coexksa, thank you for report, but this is not a bug. Magento needs this param to get correct rewrites.

**Comment by coexksa** [comment]
I didn’t get what you mean. If it’s not bug so what is it ?

**Comment by coexksa** [comment]
@p-bystritsky I didn’t get what you said. If it’s not a bug so what is it ?

**Comment by p-bystritsky** [comment]
@coexksa this is a correct logic. You can find use of this param [here](https://github.com/magento/magento2/blob/a39e37f1e50bbbd6acffe363b28b2eb289e5b80a/app/code/Magento/UrlRewrite/Controller/Router.php#L82)

**Comment by coexksa** [comment]
@p-bystritsky could you please tell me which line i've to change? also provide me correct code to let my website take code value only and ignore switching rewrite statement "  ?___from_store " ??

**Comment by p-bystritsky** [comment]
@coexksa, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for technical issues only.
