### ISSUE TITLE
Installing over existing database

### ISSUE THREAD

**Issue by sakiss** [magento/magento2#1293]
Hi

I am trying to re-install magento over an existing database.
The installation goes until 98% and then i am getting an error:

*[ERROR] exception 'Magento\Framework\Exception\State\InputMismatchException' with message 'Customer with the same email already exists in associated website.' in /var/www/html/magento2/app/code/Magento/Customer/Model/AccountManagement.php:516*

Though my database has only 1 user (me) with another username/email. I tried with several different usernames/emails and still the same.
I can see that the user is added to the table *admin_user* but the error is coming.

**Comment by anupdugar** [comment]
@sakiss Thank you for reporting the issue.
Are you following the re-install steps from - http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-uninstall.html#instgde-install-magento-reinstall ?

**Comment by anupdugar** [comment]
@sakiss Can you confirm if you are also installing the sample data?

**Comment by sakiss** [comment]
Yes i do. Can this affect it?

**Comment by anupdugar** [comment]
@sakiss Thanks for confirming. Currently we have few known issues and a discussion underway around re-installing sample data from the Setup Wizard or from command line without an uninstall. I have created an issue MAGETWO-37854 to track this issue. Thanks again for reporting it.

**Comment by rganin** [comment]
@sakiss, did you install the same Magento version/revision or a new version over DB that was installed with one of previous versions?

**Comment by sakiss** [comment]
The database was from magenton 2 beta-2. The installation was beta 7

**Comment by kokoc** [comment]
@sakiss this issue is fixed in latest Magento build. Could you please verify it?

**Comment by jipsyjith** [comment]
can you please verify the version of both installer and sample data?

**Comment by pengting** [comment]
![e120150723134302](https://cloud.githubusercontent.com/assets/4326820/8843851/c8fddc0e-3140-11e5-9703-006800b9493c.png)

what shou i do?

**Comment by quynhvv** [comment]
The first you should run shell command in your webroot folder: php
bin/magento setup:uninstall
And then install Magento again.




On Thu, Jul 23, 2015 at 12:44 PM, Patrick Peng <notifications@github.com>
wrote:

> [image: e120150723134302]
> <https://cloud.githubusercontent.com/assets/4326820/8843851/c8fddc0e-3140-11e5-9703-006800b9493c.png>
>
> what shou i do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1293#issuecomment-123979102>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by pengting** [comment]
Installation to 98 percent, stopped ！

**Comment by quynhvv** [comment]
Hi guys,
Do you install magento via ssh command line or Magento installation wizard?

if you are using the Magento installation wizard:
- The first you should run shell command in your webroot folder: php
bin/magento setup:uninstall
- The second you should close the current browser.
- And open your browser then install Magento via Magento install wizard
again.

Hope this help.

On Thu, Jul 23, 2015 at 1:37 PM, Patrick Peng <notifications@github.com>
wrote:

> Installation to 98 percent, stopped ！
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1293#issuecomment-123996025>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by pengting** [comment]
![m14](https://cloud.githubusercontent.com/assets/4326820/8845259/00000e52-3150-11e5-82d3-0ec900f64798.png)

**Comment by pengting** [comment]
In the var directory, I see a file
sample-data-state.flag
![m15](https://cloud.githubusercontent.com/assets/4326820/8845308/6e77d5f4-3150-11e5-8264-4918c72a40d8.png)

**Comment by quynhvv** [comment]
I see it's installing and nothing warning/errors from your screenshots.
Yes, that is flag to detect the Data Sample was using to install.

On Thu, Jul 23, 2015 at 2:36 PM, Patrick Peng <notifications@github.com>
wrote:

> In the var directory, I see a file
> sample-data-state.flag
> [image: m15]
> <https://cloud.githubusercontent.com/assets/4326820/8845308/6e77d5f4-3150-11e5-8264-4918c72a40d8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1293#issuecomment-124005908>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by pengting** [comment]
I waited a long time, but remained at 98 percent, about 1 hour。

**Comment by buskamuza** [comment]
@pengting , do you have xDebug enabled? If yes, could you try disable it?

**Comment by alankent** [comment]
See also https://alankent.wordpress.com/2015/07/16/the-dreaded-70-and-98-magento-2-install-pauses-quick-note/ for a way to check if still doing more work at 98%. 1 hr is long, but it does slow down a lot at 98%

**Comment by pengting** [comment]
Thanks all
Wait a little bit longer, but still successfully installed.

**Comment by chapagain** [comment]
Yes, it took around 1 hour to install sample data. Stuck at 98% while installing configurable products. I counted the dots at the end and that step completed after 150 dots (as @alankent 's note said). 

It seems a serious bug while installing sample data. I am using Magento2 version `1.0.0-beta`.

**Comment by vladimir-k** [comment]
Hi everyone,
Magento Team made some improvements in Sample Data including performance and errors processing. Now all these changes are available on **develop** branch of magento2-sample-data repository. Please, pay attention: it can be installed with magento2 **develop** version only.
We would really appreciate your feedback!

**Comment by Vinai** [comment]
Hi @vladimir-k , trying to test the changes in the sample data.
To add the develop branch as a requirement, I've done the following in the Magento install:
1. `git checkout develop`
2. `git pull origin develop`
3. Set `minimum-stability` to `dev` in the Magento `composer.json` file.
4. `composer require magento/sample-data:dev-develop`

Expected result: installation of the sample data package, dev branch.
Actual result: `The requested package magento/sample-data could not be found in any version`

Can you please give some tips on the right way to install the **develop** branch of the sample data?

**Comment by quynhvv** [comment]
Hi Vinai Kopp,

There isn't a sample data with dev-develop version come from Magento.
You can see this at : http://packages.magento.com/

Regards,


On Wed, Oct 14, 2015 at 2:00 PM, Vinai Kopp <notifications@github.com>
wrote:

> Hi @vladimir-k <https://github.com/vladimir-k> , trying to test the
> changes in the sample data.
> To add the develop branch as a requirement, I've done the following in the
> Magento install:
> 1. git checkout develop
> 2. git pull origin develop
> 3. Set minimum-stability to dev in the Magento composer.json file.
> 4. composer require magento/sample-data:dev-develop
>
> Expected result: installation of the sample data package, dev branch.
> Actual result: The requested package magento/sample-data could not be
> found in any version
>
> Can you please give some tips on the right way to install the *develop*
> branch of the sample data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1293#issuecomment-147956897>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by daim2k5** [comment]
I had the same issues this morning. The solution is:

https://maxyek.wordpress.com/2015/09/15/magento-2-branches-composer-packages-and-sample-data/

At the bottom "...In order to provide sample data for developers, who are using develop branch and latest code via github, we have opened sample date code and published in into github sample data repo. In Readme.MD file there is complete instruction how to install sample data ..."

1. Checkout repo branch develop
2. Follow the Instracutions from https://github.com/magento/magento2-sample-data/blob/master/README.md
3. Install (run setup) Magento2

**Comment by Vinai** [comment]
@quynhvv The `dev-` prefix tells composer to use look for a branch name with whatever comes after the `dev-` prefix. So `dev-develop` tells composer to use the `develop` branch instead of a tagged version (see https://getcomposer.org/doc/02-libraries.md#branches)

**Comment by daim2k5** [comment]
"Don't install it using composer, just run the cli command"

**Comment by orlangur** [comment]
@Vinai, as there is no `dev-master` release on http://packages.magento.com/#magento/sample-data, the only way to obtain sample data from `dev-develop` branch is to specify its repository explicitly in `composer.json`: http://vvv.tobiassjosten.net/php/have-composer-use-development-branches/

I see `dev-master` release available for Magento packages on Packagist though: https://packagist.org/packages/magento/community-edition. With sample data package available on https://packagist.org/packages/magento/ your problem would disappear.

**Comment by Vinai** [comment]
Arg! Not using composer - wouldn't have guessed, and was in too much of a rush to read the blog post! Thanks @daim2k5, just goes to show it is good to take time to read the links you post I guess.
