### ISSUE TITLE
Error occurs while saving already saved category in magento 2.2.1

### ISSUE THREAD

**Issue by Mohd-Salman** [magento/magento2#12934]
I have installed a fresh magento 2.2.1 after that i have migrated data from magento version 1.7 to magento 2.2.1 using data migration tool.   After migration when i save category which already migrated it shows some error.
"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later. "
Please provide me a proper solotion.
### Preconditions

1. Magento 2.2.1
2. PHP 7.0.22
3. MYSQL :   Ver 15.1 Distrib 10.0.32-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by magento-engcom-team** [comment]
Hi @Mohd-Salman  For migration-related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.
