### ISSUE TITLE
Google Analytics code is not conform the new gtag.js method.

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#12941]
The current way on how Google Analytics is implemented is by using the `i,s,o,g,r,a,m` / `analytics.js`-method. But the new implementation of Google Analytics now wants you to use the `gtag.js`-way of including GA:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-79159807-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXXX-X');
</script>
```

### Preconditions

Checked in latest develop branch of Magento 2.2

### Steps to reproduce

Enable GA.

### Expected result

Embed GA using `gtag.js`

### Actual result

It's embedded using `analytics.js`-way (well, there is a UI component now for it).

**Comment by magento-engcom-team** [comment]
@kanduvisla Thank you for your report. Seems like it's a feature request based on that https://support.google.com/analytics/answer/7538414#analyticsjs. The Magento 2 GitHub repository is used to capture code and documentation issues. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by kanduvisla** [comment]
@magento-engcom-team : I'd like to argue if this is a feature request or not. The implementation method of GA has changed an the Magento codebase is not reflecting this. It's not like I'm asking for a new feature. I'm simply saying that the current implementation is no longer the correct way and it will be deprecated in the future (like with the legacy `ga.js`-code).

**Comment by stevensagaar** [comment]
Yes Magento 2 doesn't have new GTAG implementation but there are extensions out there which can be downloaded, here is the first extension I found on Google [Magento 2 gtag.js module](https://www.scommerce-mage.com/magento2-gtag-js.html)
