### ISSUE TITLE
Multiple Products in one Cart magento 2.1.10 REST Api

### ISSUE THREAD

**Issue by shozibrasool** [magento/magento2#12940]
### Preconditions
1. I am using magento 2.1.10
2. I am trying to place an order with multiple products in one cart

### Steps to reproduce
1. i am sending POST request and its not working, i am hitting url "www.sample.com/index.php/rest/V1/guest-carts/c62700b7e525b82c0e96607e11ec0942/items"
2. i am send multiple products in body of post request
{ "cartItem": [
  { "quote_id": "c62700b7e525b82c0e96607e11ec0942","sku": "8246549-Black-40", "qty":1 },
  { "quote_id": "c62700b7e525b82c0e96607e11ec0942","sku": "8544501-Brown-43", "qty":1 },
  { "quote_id": "c62700b7e525b82c0e96607e11ec0942","sku": "8516031-Black-44", "qty":1 }
 ]
}

### Expected result
1. It should return cart's information with its all products

### Actual result

1. "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-5a4b216497333"

**Comment by shozibrasool** [comment]
@magento-engcom-team... is there any help for me?

**Comment by magento-engcom-team** [comment]
@shozibrasool  thank you for your report,
Please provide us the content of that log file (webapi-5a4b216497333).

**Comment by shozibrasool** [comment]
@magento-engcom-team this the error in log file... 
Message: Property "0" does not have corresponding setter in class "Magento\Quote\Api\Data\CartItemInterface". in /var/www/vhosts/example.pk/httpdocs/vendor/magento/framework/Webapi/ErrorProcessor.php

**Comment by magento-engcom-team** [comment]
You can't add a lot of products at per time. Only one product. [Magento REST API documentation](http://devdocs.magento.com/swagger/#/) >> quoteGuestCartItemRepositoryV1 >> POST /V1/guest-carts/{cartId}/items

> Implementation Notes
Add/update the specified cart item.
