### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in C:\wamp64\www\maze2.2.2\vendor\magento\module-catalog-inventory\Helper\Minsaleqty.php on line 182

### ISSUE THREAD

**Issue by mrkkd2013** [magento/magento2#12944]
## Clicking on product (Edit option) from ADMIN is throwing a -----

Warning: Invalid argument supplied for foreach() in C:\wamp64\www\maze2.2.2\vendor\magento\module-catalog-inventory\Helper\Minsaleqty.php on line 182

## Preconditions

1) Magento 2.2.1, PHP 7.1.9, MYSQL 5.7.19
2) Cleared/clean the CACHE and run the INDEXING also.
3) Logged to ADMIN section.

## Steps to reproduce

1) Go to ADMIN
2) Navigate from Catalog --> Products 
3)  click on the EDIT on one of the displayed Products. It redirects to Product Edit page and throws the below warning:-

## Actual Result

Warning: Invalid argument supplied for foreach() in C:\wamp64\www\maze2.2.2\vendor\magento\module-catalog-inventory\Helper\Minsaleqty.php on line 182

## Expected Result

**- should redirect to a product details Edit page and there should not be any error./warning**

**Comment by magento-engcom-team** [comment]
@mrkkd2013 Thanks for your report. We need more steps/information about your configuration to reproduce this issue. Please try to reproduce it on the clean instance of Magento (without any 3'd party modules), thank you.

**Comment by mrkkd2013** [comment]
@magento-engcom-team  Initially I got "Unable to unserialize value" on the browser then i referred to https://magento.stackexchange.com/questions/194010/magento-2-2-unable-to-unserialize-value and made changes in  /vendor/magento/framework/Serialize/Serializer/Json.php. Then I got the Warning: Invalid argument supplied for foreach() in C:\wamp64\www\maze2.2.2\vendor\magento\module-catalog-inventory\Helper\Minsaleqty.php on line 182

**Comment by magento-engcom-team** [comment]
@mrkkd2013 Based on the information you provided seems like it's a 3'rd party code problem and not Magento. This GitHub repository is used to capture code and documentation issues. Please refer to the [Community Forums](https://community.magento.com)
