### ISSUE TITLE
Add Gitter.im Badge/Chat Room to facilitate community communication.

### ISSUE THREAD

**Issue by JamesAnelay** [magento/magento2#1294]
Would you consider adding a Magento https://gitter.im/ button to the Magento2 Github Readme and setting up a Magento gitter chatroom for community members to talk to one another about Magento2 specific issues/projects.

**Comment by benmarks** [comment]
Hmmm. Looks promising. Definitely something we'll consider.

**Comment by vpelipenko** [comment]
Button is added to README.md.

**Comment by JamesAnelay** [comment]
:+1:
