### ISSUE TITLE
Upgrade to 2.2.2: CMS Homepage 404

### ISSUE THREAD

**Issue by LSERRE** [magento/magento2#12950]
### Preconditions
1. Magento 2.2.2

### Steps to reproduce
1. Configure a CMS Page as Default Page in configuration Panel with Magento 2.2.1
2. Upgrade to Magento 2.2.2
3. Go to Homepage

### Expected result
1.  Display CMS Homepage

### Actual result
1. 404 Error

I tried save stores/configurations/general/web/default pages values again.
The CMS page is now displayed as frontpage but it is not considered as real homepage: 

- cms_index_index.xml layout is not loaded
- Widgets associated to CMS Homepage are not displayed

Someone has the same issue and posted on stackoverflow:

https://magento.stackexchange.com/questions/206520/404-on-homepage-magento-2-2-2/207789#207789

**Comment by magento-engcom-team** [comment]
@LSERRE thank you for your report. Unfortunately, we weren't able to reproduce the issue. It works fine for us. The steps we used: 

1. Create a CMS page (_Content->Pages->Add new Page_)
2. Then set up this page as a home page (_Stores->Configuration->General->Web->Default Pages ->CMS Home Page->Choose the page that you created earlier_)
3. Upgrade your Magento to 2.2.2 (we used composer for that)
4. Run _php bin/magento setup:upgrade_ 
5. Open the homepage and you should see the CMS static page.

Please let us know if we missed anything, or if you used another way. Thank you

**Comment by LSERRE** [comment]
Thanks for your test. Well maybe this is because I created the Homepage with and older version then. But I still have the issue and some others has it too (see my link).

**Comment by magento-engcom-team** [comment]
@LSERRE We tried to reproduce it on the clean instance of Magento, and we could not reproduce it. We tried updating 2.2.0->2.2.2 and 2.2.1-> 2.2.2 both ways worked fine. Seems like it's a problem with your Magento instance or seems like you might have 3'rd party code, that causes the problem.  Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by juharintanen** [comment]
I had the exact same thing.
And as Vitaliy Novakivskiy wrote in that Stack Exchange link

> You can check DB table url_rewrite and found row cotains request_path='' (empty).It helped me in solving the problem.

My url_rewrite table did have an empty request_path row for some reason. I deleted it and everything worked again.

**Comment by LSERRE** [comment]
Hi,

Yes I ended up as the same way. Thanks for your answer.

**Comment by peterjaap** [comment]
+1

**Comment by loekderooij** [comment]
+1, thanks @juharintanen

**Comment by adam2211** [comment]
I was getting 404 for every new cms page I create.  I was able to resolve this issue by deleting the URL redirect from the database using the following:

`DELETE FROM `url_rewrite`
WHERE (`entity_type` = 'cms-page');`

**Comment by digvijay2017** [comment]
I have also noticed this issue while upgraded Magento 2.2.1 to 2.2.2.  But there is no any empty request_path row in url_rewrite table. This is a serious issue and how can @magento-engcom-team  close this issue?

**Comment by sam110386** [comment]
i m facing same issue after upgrade to 2.3.1, i checked "url_rewrite" DB table and there is no empty request_path record

**Comment by crysix** [comment]
We also have that issue after upgrade to 2.3.1. But it's a little more strange. If we have a 404 one the homepage and clear the hole cache (FPC enabled), everything is working. But after some time running (without changing anything) it will change to 404 again. So only cache clearing will fix it currently, and that is no solution.

We now switched to Redis as cache backend, but there we have the same problem. So it looks like the cache backend type doesn't matter.

Our url_rewrite table has no empty rows and we didn't had that error prior 2.3.1

**Comment by crysix** [comment]
There is alredy a fix for this here #21299

**Comment by ghost** [comment]
We have same issue on magento 2.3.1 with homepage on clean install with Luma Sample data.

**Comment by ghost** [comment]
> There is alredy a fix for this here #21299

This does not resolve the issue. We can provide a live site to demonstrate the patch fails. 

https://luma.awsamistacx.com

A fresh install of 2.3.1 using aMiSTACX on AWS, and then load sample data should not result in 404 on the homepage after X time; certainly tied into FPC as others have stated. 

We can fix this by flushing FPC/Redis, but that is not a solution. Again as others have stated. 

Really would be fantastic should someone take this bug seriously.

**Comment by mikimobile** [comment]
We have actually the same issue as yours right now @crysix 
Have you been able to solve it ?

**Comment by adam2211** [comment]
@mikimobile 
I was getting 404 for every new cms page I create. I was able to resolve this issue by deleting the URL redirect from the database using the following:

DELETE FROM url_rewrite WHERE (entity_type = 'cms-page');

**Comment by crysix** [comment]
@mikimobile Yes, I resolved it as described here #21299

**Comment by mikimobile** [comment]
Thanks Christian.
