### ISSUE TITLE
Magento2 0.74.0-beta9 succeccfully installed but sample-data installation failed

### ISSUE THREAD

**Issue by mrRonyTran** [magento/magento2#1295]
Hi, Magento2 developers!
I have successfully installed Magento 2 0.74-beta9 but sample-data installation failed.
"Installing configurable products:
..................................................
Fatal error: Maximum execution time of 3600 seconds exceeded in D:\projects\xamp
p\htdocs\magentov2\magento2\lib\internal\Magento\Framework\Object.php on line 50
1"

My php.ini
"
; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time=18000

; Maximum amount of time each script may spend parsing request data. It's a good
; idea to limit this time on productions servers in order to eliminate unexpectedly
; long running scripts.
; Note: This directive is hardcoded to -1 for the CLI SAPI
; Default Value: -1 (Unlimited)
; Development Value: 60 (60 seconds)
; Production Value: 60 (60 seconds)
; http://php.net/max-input-time
max_input_time=-1

; Maximum input variable nesting level
; http://php.net/max-input-nesting-level
;max_input_nesting_level = 64

; How many GET/POST/COOKIE input variables may be accepted
; max_input_vars = 1000

; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit=1024M
"

Please help me.
Thanks.

**Comment by mrRonyTran** [comment]
I fixed the issue but after sample data successfully installed, my homepage doesn't show content.
Magento2 0.74.0-beta9
"magento/sample-data": "~0.74.0-beta8"

![magento2](https://cloud.githubusercontent.com/assets/3252322/7744617/26b83e82-ffcf-11e4-8af5-55936b1b120e.png)

**Comment by kokoc** [comment]
@mrRonyTran Thank you for reporting the issue. However we are unable to reproduce this issue. Seems like the sample data installation process was interrupted. Could you please provide additional information from error.log file?

**Comment by mrRonyTran** [comment]
@kokoc I'm sorry, I have removed log file. I've installed multiple times but getting this error 
"Fatal error: Maximum execution time of 3600 seconds exceeded in D:\projects\xamp
p\htdocs\magentov2\magento2\lib\internal\Magento\Framework\Object.php on line 50
1"
My php.ini
; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time=18000

I don't know why, pls help me.
Thks

**Comment by kokoc** [comment]
Your `php.ini` is configured properly. Could you place `<?php phpinfo();` code somewhere in document root directory and check that web server uses correct `php.ini` file and settings are correct?

Please note: .htaccess files could override these values

**Comment by kokoc** [comment]
We found a source the issue. It's located in Magento\SampleData\Model\Installer:78. You can remove this line as temporary workaround.

Internal task is created: MAGETWO-37970

**Comment by mrRonyTran** [comment]
@kokoc Ok, thanks, I will try again.

**Comment by mrRonyTran** [comment]
@kokoc Hi, after change line 78 in ``` Magento\SampleData\Model\Installer ``` to ``` set_time_limit(36000); ```, it is OK. Thank you for your helps.

**Comment by vpelipenko** [comment]
@mrRonyTran, internal ticket is fixed and closed. Please, verify the fix and let us know your opinion.
