### ISSUE TITLE
Undeclared dependency magento/zendframework1 by magento/framework

### ISSUE THREAD

**Issue by linden2015** [magento/magento2#12967]
### Preconditions

1. Magento 2.1.10 OR Magento 2.2.2
  
### Steps to reproduce

1. Go to `vendor/magento/framework/DB/Adapter/Pdo/Mysql.php` line 3026
2. Note that `\Zend_Db_Select` is used
3. Note that `magento/zendframework1` contains that class
4. Go to `vendor/magento/framework/composer.json`
5. Note that `magento/zendframework1` isn't declared

### Expected result

1. `vendor/magento/framework/composer.json` should declare a dependency containing `\Zend_Db_Select`

### Actual result

1. `vendor/magento/framework/composer.json` declares no dependency containing `\Zend_Db_Select`
2. This causes packages depending on `magento/framework` to fail execution

**Comment by ihor-sviziev** [comment]
@linden2015 could you create PR that adds missing dependency? It will be merged much faster than someone else will fix it.

Example of adding missing dependency to framework: https://github.com/magento/magento2/pull/12768

**Comment by magento-engcom-team** [comment]
@linden2015, thank you for your report.
We've created internal ticket(s) MAGETWO-86346 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @linden2015. Thank you for your report. 
The issue has been fixed in magento/magento2#12990 by @ihor-sviziev in 2.2-develop branch
Related commit(s):
 - df2c8fdafb387b0e7817cba73b5c9cd1634ea6f2

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
Hi @linden2015. Thank you for your report. 
The issue has been fixed in magento/magento2#12991 by @ihor-sviziev in 2.1-develop branch
Related commit(s):
 - a6b9571a25c08634ff32cbd533888e3b5cbf9643

The fix will be available with the upcoming patch release.

**Comment by magento-team** [comment]
Hi @linden2015. Thank you for your report. 
The issue has been fixed in magento/magento2#12992 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - 326d1a04850055ff3acd75edd131d51d636fdeff

The fix will be available with the upcoming patch release.
