### ISSUE TITLE
Magento 2.1.10 export product Category wise not working

### ISSUE THREAD

**Issue by karangar** [magento/magento2#12966]
Magento 2.1.10 into Export functionality is not working filter by category_ids.
But in Magento 2.2.1 into works correctly.

### Preconditions

1. Magento 2.1.10 with sample data

### Steps to reproduce

1. Go to System -> Data Transfer -> Export
2. Select Entity Type = Products and Export File Format = CSV
3. Attribute Code "category_ids"  Filter By category id as "6"

### Expected result

1. Only those products exports, which Category id is 6 

### Actual result
1. Export all Products

**Comment by magento-engcom-team** [comment]
@karangar, thank you for your report.
The issue is already fixed in 2.2.2
