### ISSUE TITLE
Issue upgrading to Latest Magento 2 

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#12973]
### Preconditions

1. Magento 2.1.9 > Upgrading to Latest
2. PHP 7.0.26 / CentOS
3. MySQL 5.6.38 / Apache 2.4.29

### Steps to reproduce

1. composer update  / setup:upgrade

### Expected result

1. Upgrade to latest magento 2

### Actual result

1. Upgrading schema.. Warning: PDOStatement::execute(): MySQL server has gone away in /home/user/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

`Cache cleared successfully
File system cleanup:
/home/shopdevprecision/public_html/generated/code/Composer
/home/shopdevprecision/public_html/generated/code/MGS
/home/shopdevprecision/public_html/generated/code/Magento
/home/shopdevprecision/public_html/generated/code/Symfony
The directory '/home/shopdevprecision/public_html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
Module 'MGS_Blog':
Module 'MGS_Brand':
Module 'MGS_Core':
Module 'MGS_Mmegamenu':
Module 'MGS_Mpanel':
Module 'MGS_Portfolio':
Module 'MGS_Promobanners':
Module 'Magento_Store':
Module 'MGS_StoreLocator':
Module 'MGS_Testimonial':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Eav':
Module 'Magento_Authorization':
Module 'Magento_Backup':
Module 'Magento_Theme':
Module 'Magento_Customer':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_AdminNotification':
Module 'Magento_Indexer':
Module 'Magento_CatalogImportExport':
Module 'Magento_Cms':
Module 'Magento_Rule':
Module 'Magento_Catalog':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_SalesSequence':
Module 'Magento_Payment':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_CatalogInventory':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Sales':
Upgrading schema.. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopdevp_m2.m2sales_invoice_g                                                                                         rid' doesn't exist, query was: DESCRIBE `m2sales_invoice_grid`
[root@host public_html]# composer update
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Generating autoload files
[root@host public_html]# php -d memory_limit=-1 bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/home/user/public_html/generated/code/Composer
/home/user/public_html/generated/code/MGS
/home/user/public_html/generated/code/Magento
/home/user/public_html/generated/code/Symfony
The directory '/home/user/public_html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
Module 'MGS_Blog':
Module 'MGS_Brand':
Module 'MGS_Core':
Module 'MGS_Mmegamenu':
Module 'MGS_Mpanel':
Module 'MGS_Portfolio':
Module 'MGS_Promobanners':
Module 'Magento_Store':
Upgrading schema..
Module 'MGS_StoreLocator':
Module 'MGS_Testimonial':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Eav':
Upgrading schema..
Module 'Magento_Authorization':
Module 'Magento_Backup':
Module 'Magento_Theme':
Module 'Magento_Customer':
Upgrading schema..
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_AdminNotification':
Module 'Magento_Indexer':
Module 'Magento_CatalogImportExport':
Module 'Magento_Cms':
Upgrading schema..
Module 'Magento_Rule':
Module 'Magento_Catalog':
Upgrading schema..
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Upgrading schema..
Module 'Magento_SalesSequence':
Module 'Magento_Payment':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_Msrp':
Module 'Magento_CatalogInventory':
Upgrading schema..
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Sales':
Upgrading schema.. Warning: PDOStatement::execute(): MySQL server has gone away in /home/user/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228
`

**Comment by magento-engcom-team** [comment]
@heyepic  thank you for your report.
  Please try to do upgrade clean installation 2.1.9 to the latest version and tell us the result.
  It is preferred that before the upgrade some products, categories etc. will have been generated.

**Comment by orlangur** [comment]
Hi @heyepic,

> MySQL server has gone away

This clearly indicates your MySQL configuration needs to be adjusted, there is nothing to fix from Magento side here.

**Comment by heyepic** [comment]
I actually found out after lots of tweaking it was a giftcard extension causing my issue.

Thanks for the quick responses nonetheless guys. Keep up the good work.
