### ISSUE TITLE
Cannot add Multiple buttons in admin grid in Magento  version2.1.9

### ISSUE THREAD

**Issue by aathil-ali** [magento/magento2#12971]
### Preconditions

Error happends  when creating multiple buttons in admin grid 
1.Magento version 2.1.9 ,PHP 7.02

### Steps to reproduce
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">sales_order_grid.sales_order_grid_data_source</item>
            <item name="deps" xsi:type="string">sales_order_grid.sales_order_grid_data_source</item>
        </item>
        <item name="spinner" xsi:type="string">sales_order_columns</item>

        <item name="buttons" xsi:type="array" >
            <item name="csv" xsi:type="array">
                <item name="name" xsi:type="string">csv</item>
                <item name="label" xsi:type="string" translate="true">Process : CSV</item>
                <item name="class" xsi:type="string">primary</item>
                <item name="url" xsi:type="string">url..</item>
            </item>
        </item>
        <item name="buttons" xi:type="array" >
            <item name="scan" xsi:type="array">
                <item name="name" xsi:type="string">scan</item>
                <item name="label" xsi:type="string" translate="true">Process : Scan</item>
                <item name="class" xsi:type="string">primary</item>
                <item name="url" xsi:type="string">url..</item>
            </item>
        </item> 
    </argument>

### Actual result

1. [Screenshot, logs]
Exception #0 (Magento\Framework\Exception\LocalizedException): Element 'item': Duplicate key-sequence ['buttons'] in key identity-constraint 'configurableArgumentItemName'.
Line: 18

Exception #0 (Magento\Framework\Exception\LocalizedException): Element 'item': Duplicate key-sequence ['buttons'] in key identity-constraint 'configurableArgumentItemName'.
Line: 18

**Comment by dmanners** [comment]
I do not think this is a bug but actually a miss-configuration of your code. Buttons is an array so the code should look as follows.

```
<argument name="data" xsi:type="array">
    <item name="js_config" xsi:type="array">
        <item name="provider" xsi:type="string">sales_order_grid.sales_order_grid_data_source</item>
        <item name="deps" xsi:type="string">sales_order_grid.sales_order_grid_data_source</item>
    </item>
    <item name="spinner" xsi:type="string">sales_order_columns</item>

    <item name="buttons" xsi:type="array" >
        <item name="csv" xsi:type="array">
            <item name="name" xsi:type="string">csv</item>
            <item name="label" xsi:type="string" translate="true">Process : CSV</item>
            <item name="class" xsi:type="string">primary</item>
            <item name="url" xsi:type="string">url..</item>
        </item>
        <item name="scan" xsi:type="array">
            <item name="name" xsi:type="string">scan</item>
            <item name="label" xsi:type="string" translate="true">Process : Scan</item>
            <item name="class" xsi:type="string">primary</item>
            <item name="url" xsi:type="string">url..</item>
        </item>
    </item> 
</argument>
```

**Comment by aathil-ali** [comment]
Thanks David Manners, Issue has been solved for me
