### ISSUE TITLE
Estimate Shipping and Tax with Country dropdown option not auto selected current country of store.

### ISSUE THREAD

**Issue by RakeshJesadiya** [magento/magento2#12972]
Magento Version 2.2.2 with sample data installed.

I have magento 2.2.2 Instance with Multiple Store and Store view with each store view has own default country from 

> Stores -> Configuration -> Saudi Arabia Store View -> General -> Default Country -> Kuwait.

Second store with Default country is US and its default Store.

> Stores -> Configuration -> Saudi Arabia Store View -> General -> Default Country -> United States.

Now in front end when i visit Default store(US) and add product to cart, Redirect to cart page and check Estimated Shipping and Tax section from summary block show default country as United States and its perfect for default store with default country is selected.

Issue arise when i visit Kuwait store, Add any product to cart, Go to cart page  and check Estimated Shipping and Tax section from summary block show default country as United States instead of Kuwait in Cart page only.

if i goes to checkout page at that time they will display Kuwait as Selected country for Kuwait store.

How to set auto selected country for Kuwait store in Cart page in Estimate Shipping and Tax Country Dropdown?

Is it bug or functionality?

Thanks.

**Comment by magento-engcom-team** [comment]
@RakeshJesadiya Thanks for your report. Seems like it's a normal behavior, please check out [this answer](https://magento.stackexchange.com/a/124350) we hope it will help you solve the problem. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
