### ISSUE TITLE
Decimal quantities in an Invoice and Credit Memo

### ISSUE THREAD

**Issue by alexlitvinenko** [magento/magento2#12986]
Magento allows to enter decimal number in a product quantity (Advanced Inventory -> Qty Uses Decimals = Yes).  For example: 4.5 lbs.
Magento allows to buy product and specify decimal number with fractional part (e.g. 4.5).
Magento erase fractional part from product quantity  during an invoice creation.
Magento incorrectly calculates subtotal for decimal quantities with fractional part during credit memo creation and correctly calculates tax and discount.

### Preconditions
1. Magento ver. 2.2.0
2. Order example: ![image](https://user-images.githubusercontent.com/5246563/34563496-89cc3d40-f15b-11e7-9954-31586ed16592.png)

### Steps to reproduce for an Invoice
1. Create sales order with a product with a decimal quantity (must include fractional part);
2. Being on the sales order view page,  press "Invoice" button;
3. Check that "Qty to Invoice" = 20 but must be 20.5;
4. Enter 20.5 and press "Update Qty's" button ->  Fractional part was erased.

### Steps to reproduce for a Credit Memo
1. Create an Invoice;
2. Being on the sales order view page,  press "Credit Memo" button;
3. Populate "Qty to Refund" with decimal with fractional part;
4. Press "Update Qty's" button -> Subtotal was calculated for quantity=10.

### Expected result for an Invoice
1. I can invoice decimal number of products.

### Actual result for an Invoice
1. Fractional part was erased.

### Expected result for a Credit Memo
1. Subtotal should be 10.5 * 680 / 20 = 357
2. Row Total should be 357 + 17.14 - 71.4 = 302.74

### Actual result for a Credit Memo
1. ![image](https://user-images.githubusercontent.com/5246563/34564352-fc1019be-f15e-11e7-9893-a339c9ec3951.png)

**Comment by hayatbiralem** [comment]
I have the same problem.
I hope you can help as soon as possible.
Thanks.

**Comment by hackrat** [comment]
#mm18in

**Comment by magento-engcom-team** [comment]
@hackrat thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by hackrat** [comment]
@alexlitvinenko , I have checked for order with fraction qty 21.5 and I am able to Invoice and even creditmemo using fraction qty 21.5
![invoice_fraction_qty](https://user-images.githubusercontent.com/8564722/34648074-b77b3048-f3b8-11e7-8d78-4f94e33c7dd5.png)
![creditmemo_fraction_qty](https://user-images.githubusercontent.com/8564722/34648073-b733ceba-f3b8-11e7-81c7-ae8e17707922.png)

**Comment by alexlitvinenko** [comment]
@hackrat, try to reproduce it on a clean magento instance (with sample data) with default settings.

**Comment by KarlDeux** [comment]
@alexlitvinenko I was not able to reproduce the Invoice part ~~but I was indeed able to reproduce the RMA's. It will appear as discounted but won't have any impact into the line value~~.

<img width="756" alt="evidence2" src="https://user-images.githubusercontent.com/5971780/35220313-28c89bd2-ff76-11e7-8c9c-83fa7b8ab54f.png">

Can you please verify if the invoice issue is still happening on latest 2.2-develop ?

**Comment by KarlDeux** [comment]
@alexlitvinenko ~~forget what I said.~~ I cannot reproduce the credit memo issue either :( can you please confirm if your issue is fully fixed with latest 2.2-develop ?

**Comment by alexlitvinenko** [comment]
@KarlDeux I cannot reproduce the issue in magento 2.2-develop.

**Comment by KarlDeux** [comment]
@magento-engcom-team this looks already fixed in 2.2-develop.

**Comment by magento-engcom-team** [comment]
@alexlitvinenko, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by pitangaweb** [comment]
I'm having the same issue here on Magento 2.2.2.

**Comment by hayatbiralem** [comment]
There is the same problem in 2.2.3.

**Comment by Top-CMS** [comment]
same problem in 2.2.3

**Comment by hayatbiralem** [comment]
Hi everyone,

I had to solve this problem for my client immediatelly so I wrote a custom module for this. You can install it via composer.

Source files is in [here](https://bitbucket.org/irmdigital/decimalqtyinvoicefix).

Real problem is that somehow `getIsQtyDecimal` function in `Magento\Sales\Model\Service\InvoiceService` always return `false`, I don't know why. 

When I just preference `Magento\Sales\Model\Service\InvoiceService` class and I modified `prepareInvoice` function and check decimal quantities manually. That solved the problem.

Credit Memos just fine in Magento 2.2.3 so I didn't worried about that.

I hope this module will be helped someone :)

**Comment by Top-CMS** [comment]
Hi hayatbiralem,

Thanks for creating this module....this fixed it for me on Magento 2.2.3.

You're my hero for today!

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia

**Comment by sanjay-wagento** [comment]
@magento-engcom-team , I cannot reproduce the issue in the latest 2.2-develop branch (Magento ver. 2.2.6-dev)

**Comment by vkublytskyi** [comment]
@sanjay-wagento Thank you for verifying this bug report

**Comment by Jilco** [comment]
Bug is back in 2.3.3! Never had the problem and after upgrade it's there....

**Comment by Jilco** [comment]
Any solutions yet?

**Comment by shamoon** [comment]
Magento you're kind of the worst. @Jilco Not the same bug but same effect, fix is here: https://github.com/magento/magento2/pull/23943 (fix submitted Aug 8, still not released...)

**Comment by Jilco** [comment]
@nikonratm yes i found that already and changed it in Magento core, and it solved the problem

**Comment by mobeen-sarwar** [comment]
Here I'm facing the same problem in 2.4.1.

Any suggestions, please?
