### ISSUE TITLE
Magento 2.2.2 - Sometime we are getting an issue with shipping methods

### ISSUE THREAD

**Issue by ashokdubariya** [magento/magento2#12983]
We have upgraded Magneto version from 2.1.9 to 2.2.2 and some times we are getting below error on checkout pages.
`Sorry, no quotes are available for this order at this time`

We have checked log files and we are getting below error in exception.log file.
`Message: Property "CheckoutFields" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressExtensionInterface". {"exception":"[object] (Exception(code: 0): Report ID: webapi-5a4cd1eb234b1; Message: Property \"CheckoutFields\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\AddressExtensionInterface\". at /home/gatsbyla/public_html/vendor/magento/framework/Webapi/ErrorProcessor.php:205, LogicException(code: 0): Property \"CheckoutFields\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\AddressExtensionInterface\". at /home/gatsbyla/public_html/vendor/magento/framework/Reflection/NameFinder.php:100)"} []`

### Preconditions
1. Magento version 2.2.2
2. PHP Version 7.1.12

### Steps to reproduce
1. Add any product in cart
2. Click on proceed to checkout button
3. Enter billing and shipping information

### Expected result
1. When customer will enter his / her billing and shipping information then shipping method should be show.

### Actual result
We not getting shipping method issue continuously but some times we are getting an error `Sorry, no quotes are available for this order at this time` on checkout pages.

Can you please let us know any solution for this?

Thanks & Regards

**Comment by riprod** [comment]
Mine just started doing this as of 9pm EST last night. Nothing changed, nothing installed. Was working fine until then

**Comment by orlangur** [comment]
Hi @ashokdubariya, just grepped for `Checkout.*Fields` all over the `2.2-develop` and I don't see such fields used in core.

Looks like some of your extensions trying to use such extension attribute without a proper declaration in `extension_attributes.xml`.

**Comment by riprod** [comment]
I was having the same issue with this error in the logs 

[2018-01-04 14:52:00] main.CRITICAL: Report ID: webapi-5a4e3f90be327; Message: Property "CheckoutFields" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressExtensionInterface". {"exception":"[object] (Exception(code: 0): Report ID: webapi-5a4e3f90be327; Message: Property \"CheckoutFields\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\AddressExtensionInterface\". at /home/engel/engelcoolers_html/vendor/magento/framework/Webapi/ErrorProcessor.php:205, LogicException(code: 0): Property \"CheckoutFields\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\AddressExtensionInterface\". at /home/engel/engelcoolers_html/vendor/magento/framework/Reflection/NameFinder.php:100)"} []

I found the extension Temando_Shipping had been installed. This contained the phrase "CheckoutFields". I did not install this and don't know where it came from. However after disabling it and clearing all caches and redeploying the static content. It is working again.

Now to figure out where this came from ??

**Comment by orlangur** [comment]
@riprod thanks for checking! Simply disable this module for now if you're not using its functionality. Probably a builtin module if you didn't install it explicitly, asked in Slack.

This issue could be related to/duplicate of https://github.com/magento/magento2/issues/12921

**Comment by fwolfst** [comment]
For completeness (extending @orlangur s answer), on the shell `bin/magento module:disable Temando_Shipping` does the job. While you are there, after an update to 2.2.2 you might also want to disable Dotdigitalgroup_Email as this prevents customers with uorigin/adblocker to checkout.

**Comment by indefinitedevil** [comment]
Where Temando_Shipping came from: "Magento Shipping (powered by Temando)" http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.2CE.html

However, we are still getting this issue on M2.2.2EE with Temando_Shipping disabled having flushed the cache, cleared the generated files, cleared the view_preprocessed files, and cleared the static content.

**Comment by bedroomathletics** [comment]
After enabling Temando just to see what it is about, I have disabled it, but now all my shipping options don't show at all now.

Major errors, what could be the issues?

**Comment by lingwooc** [comment]
@bedroomathletics Try setup:upgrade, setup:di:compile, setup:static-content:deploy xx_xx if you've not already. Otherwise it keeps trying to call bits of temando which aren't there.

**Comment by bedroomathletics** [comment]
Thanks for the advice - where do I do this to?

**Comment by bedroomathletics** [comment]
I done this through SSH but still not fixed the issue unfortunately.

**Comment by magento-engcom-team** [comment]
@ashokdubariya ,thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation without any third party code if you have.

**Comment by magento-engcom-team** [comment]
@ashokdubariya, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by pravalitera** [comment]
I'm facing about the same issue, after a 2.1.7 to 2.2.2 migration. Disabling module, emptying cache etc, does not work.

The difference is that my shipping method are always displayed. It's on validation that i have the _"Property "CheckoutFields" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressExtensionInterface_" message

If anyone has a clue...

**Comment by TristanCICT** [comment]
@magento-engcom-team How can this be correct behavior? 
1: I can't copy the reference for the errog-log because the message disappears as soon as I click it
2: Multiple shipping methods are enabled, none are visible (even tho settings are checked; tried multiple methods and enabled some.)
3: I can't check out at all, because there is no shipping method. 

So please, I would like to know how all of this is correct behavior?

**Comment by TristanCICT** [comment]
I've found a way to work around:

1: Disable: Temando_Shipping
2: In shell: bin/magento setup:upgrade && bin/magento setup:di:compile && bin/magento setup:static-content:deploy nl_NL en_US && bin/magento cache:flush
3: Disable OSC in backend
4: flush cache
5: reload page
6: Enable OSC in backend
7: flush cache en reload page

Also I disabled Flat Rate and Table Rates as shipping methods and enabled Free Shipping, as this is a development environment. 

Maybe I added some steps that are unnecessary, but this is exactly what I did to be able to complete an order.

**Comment by ferret-e** [comment]
The same, workaround does not help.

**Comment by fluential** [comment]
@magento-engcom-team  Let's face it the Temando module is buggy, I have exactly same issue happening but unfortunately I don't have a reliable way to reproduce. The only way to fix it is to disable it. Can you make sure to track this bug internally and perhaps more details will be provided soon?

**Comment by adamlavery** [comment]
I found this after spending a day investigating why we lost ability to checkout due this same issue. But disabling the module and flushing Magento to death does not resolve it. Even tried deleting generated, var/cache & var/page_cache, re-enabling module and then disabling again with --clear-static-content. Still nothing.

Most definitely repeatable - we cannot now checkout on our site as we can't get any shipping quotes. Nothing related in exception, system or debug logs. Just no shipping and no clue why. I've now just got Flat Rate enabled. Worked fine before 2.2.2, but now nothing. I even tried switching to Luma theme to rule out theme issues, still no shipping methods.

Yes, we have other modules installed - who doesn't! - but with Magento not logging anything or giving any kind of reason for finding no shipping options, it's impossible to say what's going on.

And this is correct behaviour?

**Comment by fluential** [comment]
@adamlavery I've had similar issues and setting production mode usually produces correct results, much more often than deploying static content
```
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento deploy:mode:set production
```

**Comment by pravalitera** [comment]
@adamlavery for 2.2 migration, i had to rewrite a lot of things, and update all my modules to their last versions. And even with that, still a lot of things, in layouts etc. 

That's how i solved my problem.

The truth is that 2.0 and 2.1 are really not "polished/finished". It's just crazy how much time i lost looking for how things works, how to change it etc. And they change things with "minor" versions...

2.3 will also bring a lot a changes if i read well... We're all gonnnaaa diiiiiee

**Comment by adamlavery** [comment]
Oh @fluential, if only it were that simple! I don't yet know if it's related to Temando, but thanks to someone else posting on [StackExchange](https://magento.stackexchange.com/questions/167894/magento-2-shipping-method-not-working-sorry-no-quotes-are-available-for-this), I found a JS kludge. Adding the following to billing-address.js at line 56 fixes it:

```
    addressOptions.push(newAddressOption);

    // No shipping fix
    if (_.isEmpty(countryData())) {
    	countryData(customerData.reload(['directory-data'], false));
    }
    // end fix
```

I'm going to do some browser-side debugging today to see why this fixes it.

@pravalitera true that even 2.2 is not polished/finished, but it should at least be stable! I fear for the future of Magento if every new release introduces more store-breaking issues than it fixes.

**Comment by adamlavery** [comment]
Could @magento_encom_team investigate this further? Why does this patch to a core JS file fix the issue? What needs to change in the core to address this permanently?

**Comment by iget-esoares** [comment]
> Oh @fluential, if only it were that simple! I don't yet know if it's related to Temando, but thanks to someone else posting on [StackExchange](https://magento.stackexchange.com/questions/167894/magento-2-shipping-method-not-working-sorry-no-quotes-are-available-for-this), I found a JS kludge. Adding the following to billing-address.js at line 56 fixes it:
> 
> ```
>     addressOptions.push(newAddressOption);
> 
>     // No shipping fix
>     if (_.isEmpty(countryData())) {
>     	countryData(customerData.reload(['directory-data'], false));
>     }
>     // end fix
> ```
> I'm going to do some browser-side debugging today to see why this fixes it.
> 
> @pravalitera true that even 2.2 is not polished/finished, but it should at least be stable! I fear for the future of Magento if every new release introduces more store-breaking issues than it fixes.

Any suggestion on how to do it without changing root files? I'm trying to do it thought a mixin, but unable to find how, since this code is not inside the component.

**Comment by iget-esoares** [comment]
This issue is happening here when user doesn't preview the shipping costs on cart. Not sure why. it works on my local env, but not on production.
