### ISSUE TITLE
 I managed to make an api call without token. why?

### ISSUE THREAD

**Issue by hosnas** [magento/magento2#12988]
### Preconditions

1. Magento Version: 2.2.2

### Steps to reproduce

Hello

I just successfully did the following api without needing a token. I am really surprised now. Is it a security issue?

```
curl --request POST \
  --url http://magento.xxxx.com/index.php/rest/V1/customers \
  --header 'content-type: application/json' \
  --data '{"customer" : {"email" : "user3@example.com","firstname" : "John","lastname" : "Doe","storeId" : 1,"websiteId": 1},"password" : "Demo1234"}'
```

### Expected result

1. Ask for providing a token

### Actual result

`{"id":4,"group_id":1,"created_at":"2018-01-04 13:28:16","updated_at":"2018-01-04 13:28:16","created_in":"Default Store View","email":"user4@example.com","firstname":"John","lastname":"Doe","store_id":1,"website_id":1,"addresses":[],"disable_auto_group_change":0}`

I tested this code on two places. 1- my computer, 2- a random digital ocean server

**Comment by orlangur** [comment]
Hi @hosnas,

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

http://devdocs.magento.com/guides/v2.2/rest/anonymous-api-security.html can give some insight.

Also, please check https://github.com/magento/magento2#reporting-security-issues on how security issues are supposed to be reported.

Thanks for contacting us!
