### ISSUE TITLE
Magento 2.2.2 update product attribute option via SOAP WEB API doesn't work and return false

### ISSUE THREAD

**Issue by Nicelabsrl** [magento/magento2#12981]
### Preconditions

1.  Magento 2.2.2

### Steps to reproduce

1. Make following SOAP request for update an attribute option:
`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><catalogProductAttributeOptionManagementV1AddRequest xmlns="mydomain.com/admin/soap/all?services=catalogAttributeSetRepositoryV1%2CcatalogAttributeSetManagementV1%2CcatalogProductAttributeManagementV1%2CcatalogProductAttributeGroupRepositoryV1%2CcatalogProductAttributeOptionManagementV1%2CcatalogProductAttributeTypesListV1%2CcatalogProductAttributeRepositoryV1"><attributeCode xmlns="">attributo_19</attributeCode><option xmlns=""><label>opt-335</label><value>3451</value><sortOrder>0</sortOrder><isDefault>false</isDefault><storeLabels><item><storeId>2</storeId><label>Airplanes</label></item><item><storeId>4</storeId><label>Airplanes</label></item><item><storeId>1</storeId><label>Aerei</label></item><item><storeId>3</storeId><label>Aerei</label></item></storeLabels></option></catalogProductAttributeOptionManagementV1AddRequest></s:Body></s:Envelope>`

### Expected result

1. Updated option

### Actual result

1. This answer and the option not updated 
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="mydomain.com/admin/soap/all?services=catalogAttributeSetRepositoryV1%2CcatalogAttributeSetManagementV1%2CcatalogProductAttributeManagementV1%2CcatalogProductAttributeGroupRepositoryV1%2CcatalogProductAttributeOptionManagementV1%2CcatalogProductAttributeTypesListV1%2CcatalogProductAttributeRepositoryV1"><SOAP-ENV:Body><ns1:catalogProductAttributeOptionManagementV1AddResponse><result>false</result></ns1:catalogProductAttributeOptionManagementV1AddResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

The same request works correctly in Magento 2.1.10

**Comment by koenner01** [comment]
We had the same problem and this pull request fixed the issue for us https://github.com/magento/magento2/pull/12036

Also note that you have to sent all store_labels everytime (otherwise you will be clearing and replacing the existing ones)

**Comment by Nicelabsrl** [comment]
Thanks @koenner01 but it's not the same problem.
I know that I have to sent all store_labels everytime.
There are no problems for inserting a new option, but when I try to update an option the request always returns false and the update doesn't work.
Everything worked in Magento 2.1.10

**Comment by koenner01** [comment]
try removing 

`<label>opt-335</label> `

Some weird check is being done in the code to see if that label matches with anything that already exists (and if so, false will be returned).
Also it doesn't really add anything extra as you are already providing the full store_labels and the attribute option value

**Comment by Nicelabsrl** [comment]
I can't remove the entire tag 
`<label>opt-335</label>`
from request, but if I use in request:
`<label></label>` 
the response is true and the option contains all labels for storeviews whitout admin label.
This induce an error in the backend when save the attribute, because the admin label is required.
In this case the request should have returned false whit error.

**Comment by koenner01** [comment]
You should pass the admin value through the store_labels node by adding a value for store_id 0

**Comment by Nicelabsrl** [comment]
Great @koenner01, It works!

Thanks!

**Comment by magento-engcom-team** [comment]
This issue is fixed by the [pull request 12036](https://github.com/magento/magento2/pull/12036)

**Comment by EBotha1** [comment]
@Nicelabsrl what does your XML look like now? I have a similar issue but I am not sure how to implement the change @koenner01 suggested.
