### ISSUE TITLE
Unclear description of "Uses per Customer" setting

### ISSUE THREAD

**Issue by JanisE** [magento/magento2#12984]
Option "Uses per Customer" has an explanation "Usage limit enforced for logged in customers only.".

So what about guests? Can they apply the rule indefinitely, or can they not apply the rule at all?
It somehow seems to make no sense if they can do it indefinitely, as then registered customers are at a disadvantage (normally, it's the opposite) or can simply log out to make an order and enjoy the benefits of the rule anyway.

So, does it mean that setting "Uses per Customer" to anything >0 disables the usage of the rule to guests? If so, it should probably be explicitly visible somehow, as it may conflict with "Customer Groups" setting.

Maybe "The rule will not be applied to guests (guests will not be able to use coupons), if this is set." instead of "Usage limit enforced for logged in customers only.".

### Preconditions
1.  Magento 2.2

### Steps to reproduce
1. Open Admin -> Marketing -> Cart Price Rules
2. Click on any rule to open its settings.

### Expected result
1. An option "Uses per Customer" is listed with an explanation "The rule will not be applied to guests (guests will not be able to use coupons), if this is set."
    -  This is just a suggested solution. Maybe another message. Maybe another kind of solution entirely.

### Actual result
1. An option "Uses per Customer" is listed with an explanation "Usage limit enforced for logged in customers only."
2. It does not clearly explain what happens for the users that are not logged in.
    - What about guests? Can they apply the rule indefinitely, or can they not apply the rule at all?

**Comment by orlangur** [comment]
Hi @JanisE,

> option "Uses per Customer" is listed with an explanation "Usage limit enforced for logged in customers only."

Where do you see unclarity here? "Usage limit enforced for logged in customers only." means limit is not enforced for guests. If it really works this way, I don't see any problem here.

**Comment by magento-engcom-team** [comment]
@JanisE, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
