### ISSUE TITLE
API default value issue on variadic param

### ISSUE THREAD

**Issue by mveldhuizen** [magento/magento2#12980]
### Preconditions
1. Magento version 2.2.1
2. PHP7.0

### Steps to reproduce
1. Added a new webapi call trough the webapi.xml
2. Defined a Interface with a variadic param
3. Calling the soap wsdl list

### Actual result
Internal error: Failed to retrieve the default value

### Posible solution
In the ClassReflector the default parameters are checked. When a parameter is variadic it is also given as optional. But the parameter does not have a defaultValue. Line 95 should check if the parameter is not variadic (isVariadic()) or does have a default param (isDefaultValueAvailable())

**Comment by magento-engcom-team** [comment]
@mveldhuizen, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@mveldhuizen, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
