### ISSUE TITLE
Cron job and Abandoned message in Magento 2

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#12989]
### Preconditions

1. linux centos7
2. magento 2.2.2
3. php71

### Steps to reproduce

1. 2.2.0 upgrade to 2.2.2
2. getting Package sjparkinson/static-review is abandoned
3. cron job is not running

### Expected result

1. fix it, install Package sjparkinson/static-review, and then can running cron job

### Actual result

1. 
> composer update
> 
> Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
> 
> Loading composer repositories with package information
> 
> Updating dependencies (including require-dev)
> 
> Nothing to install or update
> 
> Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
> 
> Generating autoload file

2.
> php bin/magento cron:run
> 
> [RuntimeException]
> Source class "\SignifydAvsDefault" for "SignifydAvsDefaultMapper" generatio
> n does not exist.

**Comment by magento-engcom-team** [comment]
@rigu12 We tried to update 2.2.0->2.2.2 using composer and it worked fine for us. In order for us to reproduce this issue, please clarify more steps and provide more details on how did you update your Magento, and is there any 3'rd party code that you use?

**Comment by andy17612** [comment]
Hi @magento-engcom-team 

I just using composer to upgraded to 2.2.2 , no any 3'rd party code.
now i running this command,
```
composer global require phpro/grumphp
composer global update phpro/grumphp
```
and then run again : composer update
getting this now. 

>  composer update
> Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> 
>   [Composer\Downloader\TransportException]
>   Invalid credentials for 'https://repo.magento.com/packages.json', aborting.
> 
> update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...


my composer.json

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.2.0",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.2.2",
        "composer/composer": "@alpha"
    },
    "require-dev": {
        "phpunit/phpunit": "~6.2.0",
        "squizlabs/php_codesniffer": "3.0.1",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.5.0",
        "friendsofphp/php-cs-fixer": "~2.1.1",
        "lusitanian/oauth": "~0.8.10",
        "sebastian/phpcpd": "2.0.4"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

**Comment by magento-engcom-team** [comment]
@rigu12 Unfortianly, we can't reproduce the problem on the clean instance of Magento seems like it's a problem with **phpro/grumphp** and not Magento itself. Also please look more into using this instead: http://devdocs.magento.com/guides/v2.1/coding-standards/code-standard-sniffers.html Magento already includes Code quality tools. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Thank you

**Comment by andy17612** [comment]
> cron job is run now
> [root@public_html]# php bin/magento cron:run
> Ran jobs by schedule.

but problem 1 still 

> composer update
> Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
> Generating autoload files

how can i fix it,thank you!

**Comment by orlangur** [comment]
Hi @rigu12,

> Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.

This is not a problem and you shouldn't install another package unless you understand what you're doing.

Please pay attention to

> Do not run Composer as root/super user! See https://getcomposer.org/root for details

which is much more important.

**Comment by webtipster** [comment]
So leave magento json file with sjparkinson/static-review? 

Having same problem with client running Centos 7 / Php 7.026 / MySQL 5.6.38 / Apache 2.4.29.

As OP said, anytime composer is used for example setup:upgrade it spits out:
`Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Writing lock file
Generating autoload files`

Looked up sjparkinson/static-review and it's called from Magento 2.2 package. GitHub for sjparkinson shows that it is abandoned and author points to phpro/grumphp. 

Leave as is or?

**Comment by andy17612** [comment]
hello @orlangur ,
Sorry, i don't know , beacuse i from 2.2.0 upgraded to 2.2.2, but getting this issue. 
My server is Linux, Apache 2.4.29 ,Centos 7, PHP 7.1.12 , MySQL 5.6.38

**Comment by andy17612** [comment]
Hello @webtipster ,
I'm using server is Linux, Apache 2.4.29 ,Centos 7, PHP 7.1.12 , MySQL 5.6.38.
&
Yes. this still
> Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead. Writing lock file Generating autoload files 

So how can i fix it...very distressed......

**Comment by orlangur** [comment]
@webtipster not leave as is but remove or replace with alternative in some of the next releases. Package abandoning is not controlled by Magento and sometimes happens.

@rigu12 
> So how can i fix it...very distressed......

There is nothing to "fix" here as there is no problem. You can simply remove this package from your `composer.json` as it is a dev dependency (wrongly moved out of `require-dev` section).

**Comment by webtipster** [comment]
@orlangur Thank you! 

So which would be the correct course of action, don't see any dependencies listed. 

Should I run command `composer remove sjparkinson/static-review` or is it better to open composer.json, remove "sjparkinson/static-review": "~4.1", from the require section. 

Then running `composer require phpro/grumphp` followed by
 `php bin/magento setup:upgrade`
 `php bin/magento setup:static-content:deploy`?

Recommendations?

**Comment by orlangur** [comment]
@webtipster you don't really need a replacement for this abandoned package (unless you use some of the grumphp functionality by yourself).

> Should I run command composer remove sjparkinson/static-review or is it better to open composer.json, remove "sjparkinson/static-review": "~4.1", from the require section.

Better run command, but both actions lead to the same result.

Final version:
```
composer remove sjparkinson/static-review
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
```

**Comment by orlangur** [comment]
@rigu12 looks like your real problem was

> php bin/magento cron:run
[RuntimeException]
Source class "\SignifydAvsDefault" for "SignifydAvsDefaultMapper" generation does not exist.

which is solvable by finding which code trying to access missing class or adding such class.

Another issue you reported is not an error but rather a warning, I'll address it by a pull request this weekend. Closing this issue for now, thanks for your attention even to minor details, appreciate this.

**Comment by webtipster** [comment]
@orlangur Excellent, that's what I thought. Thank you for clearing that up! Cheers!

**Comment by sl02** [comment]
My understanding is that sjparkinson/static-review is a dev dependency not needed for production.

I too get the error when upgrading from 2.2.1 -> 2.2.2:
`Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
`

As suggested by @orlangur , I tried removing the package
`composer remove sjparkinson/static-review`

But when I do I get
`sjparkinson/static-review is not required in your composer.json and has not been removed
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
`

Is this a message that should/can simply be ignored and the dependency will be removed in future Magento updates?

Thanks.

**Comment by orlangur** [comment]
@sl02,

> My understanding is that sjparkinson/static-review is a dev dependency not needed for production.

Yeah, it was a mistake, I even commented on this in some issues in this repository. Was moved out of `require-dev` as a quick fix for unrelated issue.

> sjparkinson/static-review is not required in your composer.json and has not been removed 

It means that you already removed it (either manually or with command).

**Comment by andy17612** [comment]
Hi @orlangur 
before i ran this command , let me cant from 2.2.2 to 2.2.3 now, how can i fix it. thank you
composer remove sjparkinson/static-review
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

getting this now 
[InvalidArgumentException] Could not find package magento/product-community-edition in a version match ing 2.2.3

**Comment by Oscar-Wagento** [comment]
HI i got this problem also... but when i try to eliminate it it appears sjparkinson/static-review is not required in your composer.json and has not been removed
Please HELP!! :(

**Comment by PeRoland** [comment]
hi
i have the same error. 
Magento 2.2.3
magento2-gmail-smtp-app 1.5.1
composer version 2.5

if i test the  config, i gut the error: 
```
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /.../vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206 
```
but the test email is delivered.
in the store, no email is deliverd. in the system.log of magento i can find the same error as mentioned above...
do you have an idea how to solve it?
thx!
