### ISSUE TITLE
Install magento 2.0 successfully but  backend getting error

### ISSUE THREAD

**Issue by tungmpo** [magento/magento2#1299]
Hi, 
I have setup magento 2.0 successfully but when i login on backend. i can't  click on anything. there are many bugs on console relate to js  
![magento2_error](https://cloud.githubusercontent.com/assets/12389930/7787075/d4dd2510-0220-11e5-9dbe-e0767daae85b.png)
Anyone can help me.  thank a lots!

**Comment by quynhvv** [comment]
@Nguyen Danh Tung:

The seem you are using wamp server?
You can try update the needed PHP setttings at
PATH_TO_YOUR_WEBROOT_FOLDER/magento2/php.ini.sample

and if you use the wamp server you need to add more bellow configs to your
php.ini:
[xdebug]
xdebug.remote_enable = on
xdebug.profiler_enable = off
xdebug.profiler_enable_trigger = off
xdebug.profiler_output_name = cachegrind.out.%t.%p
xdebug.profiler_output_dir = "c:/wamp/tmp"
xdebug.show_local_vars=0
*xdebug.max_nesting_level = 300*

Hope this help.


On Sun, May 24, 2015 at 2:27 PM, Nguyen Danh Tung <notifications@github.com>
wrote:

> Hi,
> I have setup magento 2.0 successfully but when i login on backend. i can't
> click on anything. there are many bugs on console relate to js
>
> [image: magento2_error]
> <https://cloud.githubusercontent.com/assets/12389930/7787075/d4dd2510-0220-11e5-9dbe-e0767daae85b.png>
> Anyone can help me. thank a lots!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1299>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by jialuni** [comment]
I have the same (unresolved) problem, since I updated my project recently to 0.740.beta10, with the resources in /pubs/ : 404 errors


When I try to request http:<my_project>/pub, it return me the index page without CSS
When I try to request http:<my_project>/pub/<some existing file of folders> : blank content.

But all files are physically when they need to be, in the correct path. 

Seems that something on the server / the .htaccess block the outputs of everyting located in /pub/. I have the standard mage2.htaccess on the project root, but i'm very average for server administration.

**Comment by jamescowie** [comment]
Hello I am having the same issues in Beta 10. Looking at the issue it seems that on install when the pub assets are created then it is creating the symlink incorrectly.

`magento-icon.svg -> /var/www/app/design/adminhtml/Magento/backend/web/images/magento-icon.svg`

The path should be: 
`/var/www/magento2/app/design/adminhtml/Magento/backend/web/images/magento-icon.svg` 

Notice that the `magento2` folder is missing from the generated command. If you check the origin file of the symlink to see if it exists of not I have a feeling we are suffering from the same issue. I have not yet looked into the generator code to see why it is omitting a directory from smylink to locale folder.

**Comment by jamescowie** [comment]
If you error is the same as mine and the path to the symlinks is wrong what I had to do was remove ( delete ) pub/static/frontend && adminhtml and then via the new cli run `php bin/magento setup:static-content:deploy` 

I think this was because I have been using this code base for some time and upgrading / moving VM's

**Comment by mazhalai** [comment]
@tungmpo Thank you for reporting this issue. Have you tried suggestions from @quynhvv @jialuni and @jamescowie? Please let us know if you are still having issues.

**Comment by tungmpo** [comment]
Hi, 
I have fixed it.  this is my solution 

**************************************Fix Erorr can't load js and css in back end***********************************

1. enable "developer" mode (add SetEnv MAGE_MODE developer in root .htaccess file)
2. remove everything, except .htaccess file from pub/static folder
3. open the web-site
4. find one of non-loaded jquery resources and open it in the browser

If any exception happens during processing of this resource, the error should be displayed on step 4.
If not, please, look at pub/static folder - it should contain only .htaccess file.


Open up app/etc/di.xml and find the virtualType name="developerMaterialization" section. In that section you'll find an item name="view_preprocessed" that needs to be modified or deleted. You can modify it by changing the contents from Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink to Magento\Framework\App\View\Asset\MaterializationStrategy\Copy

Delete the files under pub/static to get rid of any existing symlinks. You may want to be careful not to delete the .htaccess file.

**Comment by vpiyappan** [comment]
Hi Tungmpo,

Your Steps resolved my admin link not working issue. 

Thank you for your information.

Best Regards,
Iyappan Perumal

**Comment by snohe** [comment]
@tungmpo, thank you for updating us with your steps to resolve this issue.  Should you encounter additional issues, please don't hesitate to submit a new GitHub issue.

**Comment by tungmpo** [comment]
Hello,

Do you know how to call static block at template file   in magento 2 ?

Thanks
Regards
Tung Mpo

**Comment by quynhvv** [comment]
Please research at
http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/bk-frontend-dev-guide.html

Good luck.

On Thu, Jul 16, 2015 at 10:21 AM, Nguyen Danh Tung <notifications@github.com
> wrote:

> Hello,
>
> Do you know how to call static block at template file in magento 2 ?
>
> Thanks
> Regards
> Tung Mpo
>
> On Wed, Jul 15, 2015 at 2:25 AM, Sheila Nohe <notifications@github.com>
> wrote:
>
> > @tungmpo <https://github.com/tungmpo>, thank you for updating us with
> > your steps to resolve this issue. Should you encounter additional issues,
> > please don't hesitate to submit a new GitHub issue.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/magento/magento2/issues/1299#issuecomment-121348202
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1299#issuecomment-121815412>.
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by stAn47** [comment]
this is my first try of magento and i am running apache24 + php-fpm (5.5) in chroot on a live enviroment. 

php file paths are always seen from within the chroot (/web/magento), i.e. they are not the same as seen from apache service (/srv/www/site_home_chroot/web/magento). 

upon the first visit of magento, it created many symlinks in /pub/static which do not point to the proper directory as saw by apache (it just ignored any chroot or php being on a different server) 

ideally it would be nice if any symlinks that needs to be used, would be relative to the file location and not to the root folder (which is not known from php). All modern Linux distros should support relative symlinks. 

best regards, stan

**Comment by mitul69** [comment]
Just Open the 

MAGENTO_ROOT/app/etc/di.xml

and replace below code form line number 574

`<item name="view_preprocessed" xsi:type="object">Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink</item>`

**TO**

`<item name="view_preprocessed" xsi:type="object">Magento\Framework\App\View\Asset\MaterializationStrategy\Copy</item>`

**Comment by 0x1ad2** [comment]
Fixed it by running 
`
php bin/magento setup:static-content:deploy
` 
on the command line

credits: http://magento.stackexchange.com/a/48896

**Comment by akshayjindallab** [comment]
Hi,

@tbondois: Have you checked that you are running the command prompt as an administrator.

**Comment by mitul69** [comment]
Yes i have logged in with the root user in terminal

On Thursday 25 February 2016, Akshay Jindal <notifications@github.com>
wrote:

> Hi,
>
> @tbondois <https://github.com/tbondois>: Have you checked that you are
> running the command prompt as an administrator.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1299#issuecomment-188709631>.
>


-- 
*Regards, *


*Mitul Patelpatelmit69@gmail.com <patelmit69@gmail.com>9724757428*

**Comment by mazhalai** [comment]
@mitul69 @akshayjindallab @0x1ad2 please avoid commenting on closed issues. Please create a new one.

**Comment by FayKay** [comment]
Hey,
the solution  tungmpo provided works like a charm !!!! Thank you 
But i am seem to experience an other issue with the cron job.
I get an error that says :One or more indexers are invalid. Make sure your Magento cron job is running.
Since i am new to magento can somebody provide me with a step by step guide of how to fix this ?
I am trying 2 days and still nothing.
I don't understand how to run a cron job on a localhost.
I read all magento instructions but there are for more advanced level.

Thank you in advance!

**Comment by ghost** [comment]
You must have a total of three cron jobs as [this topic](http://devdocs.magento.com/guides/v2.0/install-gde/install/post-install-config.html#post-install-cron) explains. The one you're missing is this one:

*/1 \* \* \* \* [path-to-binary] -c [ini-file-path] [your Magento install dir]/bin/magento cron:run [>> [log-file]&]

Note that the cron job must run as your [Magento file system owner](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html)

**Comment by SyedMuneebb** [comment]
Maybe you have missed any step or you are not fulfilling its requirements. You can check this simple guide to install Magento 2 on localhost: [Install Magento 2 on Localhost](https://magenticians.com/install-magento-2-on-localhost-using-xampp/)

**Comment by udemethegrtman** [comment]
I have the same issue, in magento 2.18 CE and this is the question on stack exchange. https://goo.gl/nZusVW

**Comment by soyelvalentin** [comment]
@0x1ad2 
 running commad

php bin/magento setup:static-content:deploy

credits: http://magento.stackexchange.com/a/48896
