### ISSUE TITLE
Meta Description now too short

### ISSUE THREAD

**Issue by DREC69** [magento/magento2#12996]
An issue raised a while back, finally resolved in Sept '17 has now been made redundant.

The issue was meta descriptions allow 255 characters, and this should be truncated since search engines didn't allow so many.

As of Nov '17, Google will report meta descriptions over 300 characters.

So Magento's now cutting short this useful form of CTA for its clients.

Having had it reduced, can we see it enlarged?!

**Comment by chickenland** [comment]
Looking at https://moz.com/blog/how-long-should-your-meta-description-be-2018 I'm guessing this would need to either remove the limit, or set it to around 350?

**Comment by DREC69** [comment]
300 is the limit Moz and the likes are suggesting (it might be truncated beyond that). 255 is definitely restrictive in terms of effective copy, given others will have more for CTR rates.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Meta-Description-now-too-short/idi-p/84512).
