### ISSUE TITLE
Posting Product Link Removes Image Types

### ISSUE THREAD

**Issue by abancroft0** [magento/magento2#12999]
### Preconditions

1. Magento 2.2.1
2. Json API

### Steps to reproduce

1. Existing Grouped Product
2. Existing Simple Product with image that has values for "types" (base, thumbnail, etc.)
3. Post to rest/all/V1/products/{simple sku}/links 

{
  "items": [
    {
      "sku": "grouped_sku",
      "link_type": "associated",
      "linked_product_sku": "simple_sku",
      "linked_product_type": "simple",
      "position": 1,
      "extension_attributes": {
        "qty": 0
      }
    }
  ]
}

### Expected result

1. Grouped product link is created and simple product is left unchanged otherwise

### Actual result

1. Grouped product link gets created properly, but simple product image types are removed:
GET rest/all/V1/products/{simple_sku}/media before POST to /link:
[
    {
        "id": 1323,
        "media_type": "image",
        "label": "Image",
        "position": 1,
        "disabled": false,
        "types": [
            "image",
            "small_image",
            "thumbnail"
        ],
        "file": "/3/1/315mp100005710.jpg"
    }
]
After:
[
    {
        "id": 1323,
        "media_type": "image",
        "label": "Image",
        "position": 1,
        "disabled": false,
        "types": [],
        "file": "/3/1/315mp100005710.jpg"
    }
]

**Comment by magento-engcom-team** [comment]
@abancroft0  thank you for your report,
Please try to do request "PUT" and tell us what result you get:

**URL**: http://{host}/rest/V1/products/grouped_sku/links

**BODY:** 
{
  "entity": {
    "sku": "grouped_sku",
    "link_type": "associated",
    "linked_product_sku": "simple_sku",
    "linked_product_type": "simple",
    "position": 1,
    "extension_attributes": {
      "qty": 0
    }
  }
}

**Comment by Lycanite** [comment]
I'm having a similar issue with: http://{host}/rest/V1/configurable-products/{sku}/child
Calling that to associate a child product with a configurable product removes all assigned image types from the configurable product such as thumbnail.

**Comment by abancroft0** [comment]
@magento-engcom-team the response is "true" both when the product link exists and when it doesn't. In both cases, the link is created/updated and the media image types are **not** modified.

**Comment by magento-engcom-team** [comment]
@abancroft0 so your issue is resolved. Do we understand you right?

**Comment by abancroft0** [comment]
@magento-engcom-team Yes, you have provided me with a work around to this issue by using "PUT" and the grouped sku, instead of "POST" and the simple sku.

**Comment by ragboyjr** [comment]
@Lycanite I've been experiencing the same issue as you. I'm fortunate that I can get around it my specific situation by just re-adding the images to the configurable product after I link the children. But there is definitely some bug with this.

**Comment by Lycanite** [comment]
@ragboyjr It looks like it has been fixed but the fix hasn't been released yet, I manually copied over change from this commit: https://github.com/magento/magento2/commit/4afdd8bf99d4b38a5494f82e5c0efc1260e21afb
It's in vendor/magento/module-catalog/ just replace the ProductRepository and add the new MediaGalleryProcessor class to its relative directory and it all seems to now work perfectly.

**Comment by ragboyjr** [comment]
dude, you rock, thank you so much @Lycanite .
