### ISSUE TITLE
I see my double products

### ISSUE THREAD

**Issue by Toregam** [magento/magento2#12995]
### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. I go to my website -> Select brand
2. I see all my product whit brand selected
3. Select attribute

### Expected result

1.  I see only products with attribute that i seleceted

### Actual result

1. I see products whit attribute i selected but it is double!!!

**Comment by orlangur** [comment]
> I go to my website -> Select brand

Is this core functionality or some custom extension?

**Comment by Toregam** [comment]
I use the TEMPLATEMONSTER

**Comment by orlangur** [comment]
Respective extension developer should be contacted then. Thanks for the quick response.
