### ISSUE TITLE
All icons are gone and admin panel isn't working

### ISSUE THREAD

**Issue by RalphyRalpph** [magento/magento2#12997]
### Preconditions

1. Magento 2.2.2.

### Steps to reproduce

1. In front page, "Luma" is gone
2. When try to log into admin "Magento" logo is gone
3. All other icons into admin panel are gone
4. It is loading first admin page all the time
5. No button is working in admin panel

### Expected result

1. Admin panel should work correctly

### Actual result

![magento](https://user-images.githubusercontent.com/30825517/34580043-17824b4c-f194-11e7-8104-f868e19dfcd9.png)
![magento1](https://user-images.githubusercontent.com/30825517/34580048-1bce2f4a-f194-11e7-8b5d-517735aff73b.png)

**Comment by magento-engcom-team** [comment]
@RalphyRalpph Thanks for your report, Please clarify steps to reproduce, in order for us to be able to reproduce on the clan instance of Magento. Also, let us know if you are using any 3'rd party code?

**Comment by RalphyRalpph** [comment]
1. I uploaded Magento 2.2.2 on my server using  Softaculous
2. I tried to open admin panel
3. It looks like in the pictures

My service provider has cPanel. That is it - I'm not using anything more.

**Comment by magento-engcom-team** [comment]
@RalphyRalpph The GitHub issue tracker is intended for technical issues only. Please refer to Softaculous support for this. Also, you can ask a question about this on the  [Community Forums](https://community.magento.com) or on the [Magento Stack Exchange](http://magento.stackexchange.com/). Thank you.

**Comment by Ctucker9233** [comment]
@magento-engcom-team @RalphyRalpph I've had the same problem. I had to revert to 2.1.x.
