### ISSUE TITLE
custom tab implementation in admin product page not working on magento 2.2

### ISSUE THREAD

**Issue by istitutoculturaitaliana** [magento/magento2#13013]
Hello, a simple implementation to add add a custom tab like the following in the edit product admin page

https://webkul.com/blog/add-tab-product-page-magento-admin/

is not working on magento 2.2 (while it works on magento 2.1.9)
On debug, the execution of the xml layout stops after the constructor of Block file
thank you

**Comment by Erchiragdodia** [comment]
@istitutoculturaitaliana 

Follow this link http://www.codextblog.com/magento-2/how-to-create-custom-tab-in-magento-2/ its working.

Please use UI component and modifier to create a new tab.

**Comment by istitutoculturaitaliana** [comment]
thank you Erchiragdodia,

    I've checked it and it works.

However there are some issues, like

I cannot set the order of tab

(through "sortOrder")

and I don't know if there will be issues

relating to it a phtml file.

 

What about the following solution ?


https://webkul.com/blog/add-tab-product-page-magento-admin/

 

It seems straightforward and it reflects my own

implementation.

What path do you suggest to debug it ?

(ie. files of magento framework entitled to

parse the xml layout)

 

thank you

Thomas

 

 


 

Sent: Sunday, January 07, 2018 at 12:16 PM

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by radhikagarg03** [comment]
Lodu hai sab

**Comment by Erchiragdodia** [comment]
@radhikagarg03 please don't use abusive words
