### ISSUE TITLE
Where can I get Magento_SampleData module

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#1302]
Hi,

in the latest develop branch `\Magento\Setup\Model\Installer` the following code can be found:

```php
if (!empty($request[InstallCommand::INPUT_KEY_USE_SAMPLE_DATA]) && $this->sampleData->isDeployed()) {
    $script[] = ['Installing sample data:', 'installSampleData', [$request]];
}
```

The `\Magento\Setup\Model\SampleData::isDeployed()` method checks it a module `Magento\SampleData` is present.

```php
public function isDeployed()
{
    return file_exists($this->directoryList->getPath(DirectoryList::MODULES) . self::PATH);
}
```
If I read that correctly, a sample data module needs to exist at *app/code/Magento/SampleData*.
However, installing the sample data via composer by using

```bash
% composer config repositories.magento composer http://packages.magento.com
% composer require magento/sample-data:0.74.0-beta9
% composer update
```
installs *dev/tools/Magento/Tools/SampleData*, which is not a regular Magento 2 module, plus, of course it's not in the *app/code* branch.  

I've been busy with non-Magnto2 work for a while and probably missed this change in how to install the sample data. But I can't see a more recent version on http://packages.magento.com, and the [sample data installation instructions](http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html) show no change either.
Can you please shed some light on where to get the Magento_SampleData module? Thanks!

**Comment by buskamuza** [comment]
Hi @Vinai,
Currently the SampleData module is not published yet, so unfortunately installation of sample data is skipped during installation. Until the module is published, script from dev/tools can be used after magento installation to install sample data. The sample data module should be available soon.

**Comment by Vinai** [comment]
Thanks @buskamuza!

**Comment by buskamuza** [comment]
@Vinai , FYI, Sample Data module is available now. If you use `magento/sample-data` of version `0.74.0-beta10`, you should be able to install Sample Data during Magento installation.

**Comment by Vinai** [comment]
Thanks!
