### ISSUE TITLE
From pipeline deployment to the old way

### ISSUE THREAD

**Issue by gbaims** [magento/magento2#13022]
I've been trying to use the new pipeline deployment since the first 2.2 release candidate. Unfortunately, I have a few projects where it's been difficult to use the new config.php with all the configurations.

Is there a way to import all configurations to database and stop using the config.php to manage application specific configuration? Maybe some way to create a backup for the database with all configuration built in?

**Comment by magento-engcom-team** [comment]
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
