### ISSUE TITLE
After Migration Category not showing Product.

### ISSUE THREAD

**Issue by mayankzalavadia** [magento/magento2#13028]
After Migration Category not showing Product.

After successfully migration with Magento 2.2.2 from Magento 1.8.0.0 data. Unfortunately, I have a Problem, I am not able to see any product under the category. Also not able to search the all migrated products as well.

I have traced out this Issue and what I find is this issue is related to placeholder images. Category products are not displayed after migration just because of placeholder images. 

### Preconditions

1. Magento 2.1.9
2. Magento 2.2.0
2. Magento 2.2.2

### Steps to reproduce

1. Install fresh Magento without sample data.
2. Migrate with fresh Magento.
3. Reindex Magento.
4. Go to any category page and you see products is not showing.

### Expected result

1. After successfully migration Product should be displayed on product page.

### Actual result

1. Category not showing Product.

**Comment by mayankzalavadia** [comment]
#mm18in I would like to work on this issue.

**Comment by magento-engcom-team** [comment]
@mayankzalavadia thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mayankzalavadia** [comment]
To resolve this issues I have put the placeholder images on **pub/media/catalog/product/placeholder/** and open the category page after refresh cache and all the category products are displayed.

**Comment by orlangur** [comment]
@dmanners @magento-engcom-team problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository, isn't it?

**Comment by magento-engcom-team** [comment]
Hi @mayankzalavadia,
For migration-related issues please use the correct repository:
  [https://github.com/magento/data-migration-tool](https://github.com/magento/data-migration-tool)
Thank you.

**Comment by aliomattux** [comment]
I disagree that this should be a migration issue because the issue can be reproduced by not having a valid file link for the image placeholder. When this problem happens there is no error in webserver, or magento logs. There should be an exception in the log that indicates the reason for the failure of the products to load, and is a bug in the software because the condition that causes the problem is not handled and causes total loss of category products.

**Comment by orlangur** [comment]
@aliomattux feel free to report a new issue if you able to reproduce it on a clean Magento 2 installation.
