### ISSUE TITLE
Improve error message around console CLI for installing

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#1303]
When using the new CLI to install magento and there is an already existing `app/etc/config.php` then the error message returned makes no sense. 

```
Autoload error: Key collision! The following keys occur in multiple config files:
backend
db
```

Perhaps this is an edge case but it might be good to check if the file exists before generating some errors ?

**Comment by Vinai** [comment]
Ran into that, too. Simply adding the file name that contains the duplicates to the error message already would help a good deal.

For anybody who endy up here via google: remove the app/etc/config.php and app/etc/env.php before reinstall

**Comment by mazhalai** [comment]
@jamescowie and @Vinai Thank you for your feedback. We have created internal ticket MAGETWO-37941 to come up with a solution.

**Comment by xcomSteveJohnson** [comment]
FWIW, you can also use the workaround here: http://devdocs.magento.com/guides/v1.0/release-notes/changes_074-beta10.html#rn-074b10-changes

**Comment by mazhalai** [comment]
@jamescowie @Vinai This issue has been resolved. Closing ticket.
