### ISSUE TITLE
Redis cache fallback?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#13047]
Rather than crashing Magento, it would be nice if redis cache had an option to fall back to var/cache etc. when redis has died.

### Preconditions
1. Magento 2.2.2
2. PHP 7.1
3. Redis 3.2.8

### Steps to reproduce
1. Redis server to crash

### Expected result
1. Magento should fall back to it's own cache, not crash.

### Actual result
1. 
```
Warning: Redis::connect(): connect() failed: Connection refused in vendor/colinmollenhour/credis/Client.php on line 444

Warning: Redis::connect(): connect() failed: Connection refused in vendor/colinmollenhour/credis/Client.php on line 444

Fatal error: Uncaught CredisException: Connection to Redis 127.0.0.1:6379 failed after 2 failures. in /vendor/colinmollenhour/credis/Client.php:463 Stack trace: #0 /vendor/colinmollenhour/credis/Client.php(459): Credis_Client->connect() #1 /vendor/colinmollenhour/credis/Client.php(792): Credis_Client->connect() #2/vendor/colinmollenhour/credis/Client.php(619): Credis_Client->__call('select', Array) #3 /vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(359): Credis_Client-/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(238): Cm_Cache_Backend_Redis->_applyClientOptions(Object(Credis_Client)) #5 /vendor/ in /vendor/colinmollenhour/credis/Client.php on line 463
```

**Comment by chickenland** [comment]
Wouldn't this cause an issue whereby REDIS dies, sessions start getting stored in var/cache, REDIS comes back up and wipes everyone's baskets as their session doesn't exist anymore? (as Magento hits REDIS instead of the filesystem). I guess there could/should be some migration between the two?

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell 
Unfortunately we are closing this ticket now, as Github issue tracker is intended only for core Magento technical issues. Please refer to the [Community Forums](https://community.magento.com/) to submit a feature request or use [magento/community-features](https://github.com/magento/community-features/issues) repository to describe your idea.

Thank you for collaboration
