### ISSUE TITLE
Is PHP-XSL a requirement for Magento now ? 

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#1304]
Testing the new Beta and CLI I get class not found for XLST lib unless I install `php-xsl` is this now a required dependency on magento ? If so I will update the dev documentation around this.

**Comment by orlangur** [comment]
Yes, however it is currently missing in [composer.json](https://github.com/magento/magento2/blob/develop/composer.json).

**Comment by mazhalai** [comment]
@jamescowie Thank you for reporting this issue. We are aware of this issue and are working on it in ticket MAGETWO-37766.

**Comment by piotrekkaminski** [comment]
This issue should be fixed now.
