### ISSUE TITLE
Attribute Input fields to small when using many multistores

### ISSUE THREAD

**Issue by miguel-fcmoto** [magento/magento2#13053]
Hi together,

we have many multi stores in our new magento shop. When we want to add content into the attribute value fields it is very complicate because there is not enough space to see more then 3 characters. This is because the fields are to small. All fields are added in horicontal. Is it possible to add the fields in vertical. I saw it last time in another shop system. They place the default value left site in a column and put the several fields for the multistore in a second column in vertical. 

**Here the example i mean:**
![attr-values](https://user-images.githubusercontent.com/20454811/34668971-e2d40898-f46f-11e7-88b7-748be610601f.jpg)

**Here like it is in our shop actually:**
![attr-magento-current](https://user-images.githubusercontent.com/20454811/34669044-3ae7628c-f470-11e7-8381-ee12aa70b083.jpg)

Thanks in advanced for your support!

**Comment by magento-engcom-team** [comment]
@fcmoto, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ishakhsuvarov** [comment]
Similar issue reports for reference:
* #14107
* #14094

**Comment by miguel-fcmoto** [comment]
hi @ishakhsuvarov, do you already have a feedback for me regarding the above issue? It is really complicate to handle the colors and other values for several store views.

Best to do it in a 2 column matrix like you can see in my screenshot above.

Thanks for your info

**Comment by engcom-Delta** [comment]
@fcmoto thank you for your report. I am not able to reproduce issue on  2.4-develop 
![#13053issue](https://user-images.githubusercontent.com/51681379/71580604-0dd5bc80-2b0a-11ea-95f8-7a2339690175.png)

![#13053issue2](https://user-images.githubusercontent.com/51681379/71580608-11694380-2b0a-11ea-8075-df16ecc5f7d3.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by miguel-fcmoto** [comment]
Hi, 
the more store views you have, the smaller and more confusing the input fields become. And if you then want to add a color e.g. "black/white"green" you can only see the first letters of it. It is a usability issue. See my first screenshot how it is done by another shop system. Isnt it possible to do it like this?
Thanks for your feedback
