### ISSUE TITLE
Cart and checkout broke after upgrade to 2.2.2

### ISSUE THREAD

**Issue by deadlyw1re** [magento/magento2#13059]
### Preconditions

1.  Magento version 2.2.2

### Steps to reproduce

1. Update from 2.1.7 to 2.2.2

### Expected result

1. Normal cart and checkout

### Actual result

1. White page on checkout and almost white page on cart

### Cart
![cart](https://user-images.githubusercontent.com/23723417/34674181-39f7cb7c-f485-11e7-8802-5007b2aa77a0.PNG)

### Checkout
```
           1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'ifconfig': The attribute 'ifconfig' is not allowed.
Line: 2136

Element 'item': This element is not expected.
Line: 2424


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'ifconfig': The attribute 'ifconfig' is not allowed.
Line: 2136

Element 'item': This element is not expected.
Line: 2424
```

**Comment by bydrei** [comment]
@deadlyw1re that is not a bug. Since the 2.2.* they added strict validation to XML, the exception say's that the node attribute "ifconfig" you are using in referenceBlock is not allowed, so really what you need to do is remove that invalid attribute.

Also ifconfig works on block creation and not when referencing it.

**Comment by deadlyw1re** [comment]
@ferrazzuk Thank you, that solves the cart problem and the 2 exceptions on the elements referenceBlock.

**Comment by orlangur** [comment]
Hi @deadlyw1re, thanks for report, however this is correct system behavior. See https://github.com/magento/magento2/issues/11194#issuecomment-333978626 for more details.
