### ISSUE TITLE
Not able to override Block \Magento\Directory\Block\Data with following method getCountryHtmlSelect()

### ISSUE THREAD

**Issue by allamsettiramesh** [magento/magento2#13056]
I am trying to override Block `\Magento\Directory\Block\Data` with following method `getCountryHtmlSelect()` with following script. but it's not executing 

di.xml :

  `<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Directory\Block\Data" type="Magenticians\Modulecontact\Block\Data" />
</config>`

Block File:
 
`<?php
namespace Magenticians\Modulecontact\Block;
use Magento\Framework\View\Element\Template;
class Data extends \Magento\Directory\Block\Data{

    public function getCountryHtmlSelect($defValue = null, $name = 'country_id', $id = 'country', $title = 'Country')
    {
        exit;
    }
    public function test(){
        exit;
    }

}`

**Comment by bydrei** [comment]
@allamsettiramesh have you cleared di and appropriate caches? Also if you're using magento  > 2.2.* you will need to clear the generated folder. Also instead of overriding the full class, you could use a plugin.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by allamsettiramesh** [comment]
orlangur..May i know why should closed this issue.

**Comment by orlangur** [comment]
@allamsettiramesh, surely, please read my comment https://github.com/magento/magento2/issues/13056#issuecomment-356112476

**Comment by allamsettiramesh** [comment]
Actually, I am overriding Block class according Magento 2 standards but it's not effecting and i override couple of block classes successfully

**Comment by nati08** [comment]
@allamsettiramesh Hi, did you find a solution for this?
