### ISSUE TITLE
Sample data problem...

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#1305]
I have installed sample data through a command :- 
composer config repositories.magento composer http://packages.magento.com
then after its generate autoload files ,
After that to run the installer I have run : 
php dev/tools/Magento/Tools/SampleData/install.php --admin_username=username

In this command it gives:-
Usage: php -f install.php -- --admin_user= [--modules=] [--bootstrap=]
--admin_user - store's admin username. Required for installation.
[--modules] - install sample data for a module(s)
[--bootstrap] - add or override parameters of the bootstrap

I don't know what command I have to run for installing  the sample data ..

**Comment by mazhalai** [comment]
@aishwaryacedcoss, what version of magento are you using?

**Comment by voleye** [comment]
You need to run command:
php dev/tools/Magento/Tools/SampleData/install.php --admin_username=<username>

where <username> - correct admin user name in your store

**Comment by mazhalai** [comment]
@aishwaryacedcoss I just noticed, your command has `--admin_username` but usage shows `--admin_user`. Please make this correction and try again.

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.
