### ISSUE TITLE
Visibility changes in Magento\Catalog?

### ISSUE THREAD

**Issue by luckyduck** [magento/magento2#13067]
It seems that the visibility of certain methods was changed somewhere along the line in recent Magento 2.x releases. One example:

Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\AdvancedPricing

This broke a major part of our code, because for example the method customizeTierPrice() cannot be called in a subclass any longer. 

Was this intentional? Did this happen by mistake?

The problem for me: a collegue build a tier price customization around those methods. For example the class AdvancedPricing is extended by one model. 

IS such a breaking change really required?

**Comment by orlangur** [comment]
From https://github.com/magento/magento2/commit/967ee1a0ce5af580afcc48369466dbd0fd65734d it does not look like a really necessary change.

Generally extending core classes is highly discouraged.

**Comment by luckyduck** [comment]
Thank you very much for your response!

> Generally extending core classes is highly discouraged.

But, isn't this the whole point when you rewrite/extend/change nearly any functionally in magento? Just for clarification: where should we draw the line. Any good guidelines what to extend and what not?

**Comment by luckyduck** [comment]
I see, composition over inheritance. Nevermind. But still, the private methods can't be used in that case.

**Comment by magento-engcom-team** [comment]
@luckyduck, thank you for your report.
We've created internal ticket(s) MAGETWO-86493 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @luckyduck 
According to http://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html#2-class-design
`2.7. All non-public properties and methods SHOULD be private.`

Protected methods located in non-abstract classes should be private.
You can use form modifiers to change the form metadata. Inheritance is not required in this case
