### ISSUE TITLE
proposal: global search extend

### ISSUE THREAD

**Issue by chrom** [magento/magento2#1306]
extend global product search through search the pages of the blog (CMS page)

**Comment by choukalos** [comment]
Hi @chrom ; it's on our roadmap for post 2.0 release.  We'll add CMS to search results.  Internal Epic - MAGETWO-11439

**Comment by chrom** [comment]
where is i can see magento 2 road map?

**Comment by Wojton** [comment]
Magento 2 is looking for in cms?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/proposal-global-search-extend/idi-p/47267).
