### ISSUE TITLE
How is Magento in 2018?

### ISSUE THREAD

**Issue by dapdx** [magento/magento2#13078]
This might be against the rules on this forum, but hoping someone can give me an update on how Magento 2 is performing these days. I was using mid last year, but had to ditch it as it was just too buggy and each release seemed to just totally mess up our stores. Our clients got pissed, and we had to go back to 1.9

Anyway, how are the newer releases? Is this ok for a production environment now? Is it looking more stable? Do we still have issues with configurable products? Overwritten .htaccess files? How are the updates via the admin interface?

Thank you!

**Comment by magento-engcom-team** [comment]
@dapdx The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by BB-000** [comment]
🤮

**Comment by cscd98** [comment]
@dapdx It's still shockingly bad I'm afraid..

**Comment by dapdx** [comment]
@craigcarnell Completely agree, we were trying again with it for a couple stores with 2.3 and it's still garbage. Plugin installation is a confusing mess, basic features became headaches or didn't function, and it's just inconsistent. We went back to 1.9.3 again. I was hoping after Adobe picked it up they might get it together, but I guess not.
