### ISSUE TITLE
Issues trying to install extensions on Magento 2

### ISSUE THREAD

**Issue by executekcouk** [magento/magento2#13079]
### Preconditions

1. MAgento 2.1.7 - PHP version 7.0
2. http://nimb.ws/Tkt3fh - shows this issue when trying to add in new installation on our dev environment even though the website is fully working and all other elements work.

Errors exactly as it appears and the issue is no versions are mentioned:

Check Cron Scripts
Cron script readiness check failed. Hide detail

Error from Setup Application Cron Script:
Cron job has not been configured yet
Other checks will fail as a result (PHP version, PHP settings, and PHP extensions)

Error from Updater Application Cron Script:
Cron job has not been configured yet

For additional assistance, see cron scripts help.

Check Component Dependency
We found conflicting component dependencies. Hide detail

For additional assistance, see component dependency help .

Need Help?

PHP Documentation
PHP Version Check
Your PHP version is . The required PHP version is . Show detail

PHP Settings Check *
For additional assistance, see PHP settings check help .

Need Help?

PHP Extension Help
PHP Extensions Check
missing PHP extensions. Hide detail

The best way to resolve this is to install the correct missing extensions. The exact fix depends on our server, your host, and other system variables. 
Our PHP extension help can get you started.

For additional assistance, contact your hosting provider.

* - In some cases, you might have two PHP configuration files: one for the PHP command line and for the web server. If so, make the change in both php.ini files. For details, see the php.ini reference.

### Steps to reproduce

1. Perform readiness check on magento admin to upgrade mag version or something?
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@executekcouk  thank you for your report
Please provide details about how is configured the file "Cron Scripts" in your case?

**Comment by executekcouk** [comment]
Thanks for the response @magento-engcom-team - Not a developer myself so not sure if this is what you are referring to: http://nimb.ws/7qSdAj

It was set up by a developer i paid to do the website who now has done a runner!

**Comment by magento-engcom-team** [comment]
@executekcouk,
And what extension do you want to install?

**Comment by executekcouk** [comment]
This occurs for anything i try to install via magento. In this instance it was a reindexing extension from magento marketplace.

**Comment by magento-engcom-team** [comment]
@executekcouk,
And have you tried to follow the recommendations (instructions) given under each item that didn't pass the required validation (marked with cross in the circle)

**Comment by executekcouk** [comment]
the problem is each problem is not clear. For example the php version is incorrect but it doesn't state which version is required for instance, so not sure what exactly we need to do here?

**Comment by magento-engcom-team** [comment]
@executekcouk
As we see you need instructions how to cope with "cron jobs" set up and maybe with something else (but at first with "cron job". If to cope with issues in the order they emerge all the following issues may get resolved by themselves). The GitHub issue tracker is intended for Magento Core technical issues only. So please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
