### ISSUE TITLE
sjparkinson/static-review is abandoned

### ISSUE THREAD

**Issue by sl02** [magento/magento2#13077]
### Preconditions
1. Magento 2.2.1

### Steps to reproduce
Upgrade to Magento 2.2.2 via composer:
1. composer require magento/product-community-edition 2.2.2 --no-update
2. composer update

### Expected result
Completion of composer update command without errors

### Actual result
Get error:
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.

![ss](https://user-images.githubusercontent.com/22160597/34726359-bf71e138-f521-11e7-8eae-a50405655345.png)

**Comment by magento-engcom-team** [comment]
@sl02 Thanks for your report. We are Closing this issue because it is a [duplicate](https://github.com/magento/magento2/issues/12989)
