### ISSUE TITLE
Category Banner Image Can't Upload

### ISSUE THREAD

**Issue by ronnie48** [magento/magento2#13074]
Category Image Can't Upload

A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

**Preconditions**

1. Magento 2.2.2
2. PHP 7.1

**Steps to reproduce**

1. Navigate to admin > catalog > category.
2. Select any category.
3. Click on content and upload Category banner image.
4. Click on save.

**Expected result**

1. Category banner image need to upload.

**Actual result**

1. A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

![large 1](https://user-images.githubusercontent.com/24474925/34721826-5bab42fe-f56a-11e7-949e-07a8e64d4813.png)

**Comment by magento-engcom-team** [comment]
@ronnie48 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![cat_image_0891280985](https://user-images.githubusercontent.com/31669971/34723266-9f801184-f552-11e7-8a37-2b43f19cb656.png)

**Comment by ronnie48** [comment]
@magento-engcom-team thanks for your feedback.

As i know this issue is created on my server and same thing is works in another magento setup and also works fine in localhost.

Is there anything related to server side?

**Comment by magento-engcom-team** [comment]
@ronnie48 , thanks for you update. If in local environment works without problem, yes issue is related to for server

**Comment by ronnie48** [comment]
@magento-engcom-team , 

I am getting 406 error in validate call, so what could be the issue? Issue seems on server but I am not able to figure it out so can you please let me know what could be the issue? is there any specific requirements for category image upload? 

Issue of permission or something? Product image upload are working fine.

https://www.awesomescreenshot.com/image/3089483/5d71adf55651dc6bf42fe8a71695cf33

![screenshot from 2018-01-09 12-21-24](https://user-images.githubusercontent.com/24474925/34759888-9bf930fc-f603-11e7-8043-cb7c4dcc262c.png)
