### ISSUE TITLE
Admin Global Search for Products not working correctly

### ISSUE THREAD

**Issue by thaddeusmt** [magento/magento2#13080]
### Preconditions

1. Magento 2.2.2
2. Log in as Admin
3. Make sure admin global search is enabled and products are indexed

### Steps to reproduce

1. Type part of a product name in Global search at top of Admin pages
2. In auto-complete, click on `"search term" in Products` option, where "search term" is your search, well, search terms
3. The Product grid will load with the "?search=search%20term" query parameter on the URL
4. The search terms are not added to the grid query - all products are shown (or any previous filters still active from your last session filtering the product grid)

### Expected result

1. On the Product grid page there should be an active "keywords" filter, like on the other content grids when you do a global search (Pages, Orders, etc)
2. The filter ususally says: (X) Active filters:	Keyword: search terms
3. The products grid should be filtered by the "search term" keywords

### Actual result

1. The filter saying: "(X) Active filters:	Keyword: search terms" is not present
2. Products are not filtered by keywords

**Comment by magento-engcom-team** [comment]
Hi @thaddeusmt 
Thank you for reporting. Looks like this report duplicates https://github.com/magento/magento2/issues/7861 
Closing.
