### ISSUE TITLE
Call to undefined method Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend::getAllOptions() 

### ISSUE THREAD

**Issue by Ralfi18** [magento/magento2#13098]
Hello!

When migrating to Magento 2 (from magento 1.9.3) using Data Migration Tool, in the Admin/Customers i get this Error: 

![screenshot-2018-1-10 http denta loc](https://user-images.githubusercontent.com/15306968/34777666-b607d550-f623-11e7-9ebd-b925ac880f70.png)

Call to undefined method Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend::getAllOptions() 

Fatal error: Uncaught Error: Call to undefined method Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend::getAllOptions() in /var/www/denta.loc/generated/code/Magento/Eav/Model/Entity/Attribute/Backend/ArrayBackend/Interceptor.php:36 Stack trace: #0 /var/www/denta.loc/vendor/magento/module-customer/Model/AttributeMetadataConverter.php(68): Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend\Interceptor->getAllOptions() #1 /var/www/denta.loc/vendor/magento/module-customer/Model/Metadata/CustomerMetadata.php(77): Magento\Customer\Model\AttributeMetadataConverter->createMetadataAttribute(Object(Magento\Customer\Model\Attribute)) #2 /var/www/denta.loc/vendor/magento/module-customer/Model/Metadata/CustomerMetadata.php(109): Magento\Customer\Model\Metadata\CustomerMetadata->getAttributeMetadata('default_blog_ca...') #3 /var/www/denta.loc/vendor/magento/module-customer/Model/Metadata/CachedMetadata.php(85): Magento\Customer\Model\Metadata\CustomerMetadata->getAllAttributesMetadata() #4 /var/www/denta.loc/vendor/magento/ in /var/www/denta.loc/generated/code/Magento/Eav/Model/Entity/Attribute/Backend/ArrayBackend/Interceptor.php on line 36

I found a fix adding the method  getAllOptions which returns an empty array. Have any one encounter the same issue ( the db tables are populated  ) and if so how did you fix it.  Tank you!

**Comment by magento-engcom-team** [comment]
@Ralfi18 For migration-related issues please use the correct repository: 
https://github.com/magento/data-migration-tool 
Thank you.
