### ISSUE TITLE
Custom Error Page settings

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#13094]
### Preconditions

Ubuntu, Standard LAMP (Apache, MySQL, ....)
Magento ver. 2.1.9 - Clean setup by command line
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper

### Magento Store Configuration

The configuration of the magento store is standard. A fresh install of the 2.1.9 with luma theme.
I need to customize the error page where appear this message:

> Exception #0 (Exception): Unable to proceed: the maintenance mode is enabled. 

I have set the custom template in shop/pub/errors/custom and set the shop/pub/errors/local.xml with skin parameter to custom but I continue to see the error message in a white page.

### Expected result

Magento must use the template skin selected in the local.xml file

### Actual result

The template skin is not used.

thanks

**Comment by sunil-gcet** [comment]
Hello shinesoftware, can you confirm the changes done in local.xml file here so we can have a look ?

**Comment by shinesoftware** [comment]
Hi @sunil-gcet yes of course.

    <?xml version="1.0"?>
    
    <config>
        <skin>custom</skin>
        <report>
            
            <action>print</action>
            
            <subject>Store Debug Information</subject>
            
            <email_address></email_address>
            
            <trash>leave</trash>
        </report>
    </config>

![magento-error-custom](https://user-images.githubusercontent.com/1553035/34774428-92a7f856-f60f-11e7-9766-c08895ac6c98.png)

**Comment by sunil-gcet** [comment]
Thanks shinesoftware,

I just tried to reproduce the same error on one of our installation and following are the results : 

![err](https://user-images.githubusercontent.com/11224869/34774645-2295556e-f636-11e7-9788-bb82857c73ab.png)

Above are the screenshot of local.xml and template inside new folder name custom, i have change text to Custom Temporarily Unavailable

![err2](https://user-images.githubusercontent.com/11224869/34774738-83b0469c-f636-11e7-8939-cce84c9a3e7e.png)

You can see the desired result here for sometime : http://52.9.224.177/magento4/

Its working as it should.

**Comment by shinesoftware** [comment]
hi again,

maybe I have understood the issue. When I execute by shell:

> n98-magerun2.phar deploy:mode:set production

the maintenance mode is enabled and the error is not a 503 like in your magento but the error code is 500.

![selezione_098](https://user-images.githubusercontent.com/1553035/34775119-4f9d90cc-f612-11e7-9d77-8e93a4afb927.png)

In the error.log there is not any error message neither in the php error log.

**Comment by sunil-gcet** [comment]
Great to hear, but more to help if you look at vendor/magento/framework/App/Http.php method catchException and handleDeveloperMode

So you can see that in the case of developer mode it is supposed to send 500 response code not 503, but in production mode it gives 503

Hope it helps

**Comment by shinesoftware** [comment]
So, I don't understand why it replies with a 500 error code in production mode.

**Comment by Ctucker9233** [comment]
@shinesoftware 500 error codes have to do with the server and not the Magento installation. There may be memory limits exceeded or timeouts.

**Comment by tuyennn** [comment]
@shinesoftware What was you archived? I have the same problem with 2.1.9 while my custom theme cannot be applied to the maintenance mode, this fell back to the default theme
