### ISSUE TITLE
No locale for Swedish (Finland)

### ISSUE THREAD

**Issue by ghost** [magento/magento2#13095]
### Preconditions
1. Magento 2.1.10

### Steps to reproduce
1. Go to Stores > Configuration > General > General > Locale Options > Locale

### Expected result
1. Option found for Swedish (Finland)

### Actual result
1. No option found for Swedish (Finland)

**Comment by magento-engcom-team** [comment]
@rasmuswikman, thank you for your report.
We've created internal ticket(s) MAGETWO-86566 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @rasmuswikman. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1207 by @nmalevanec in 2.2-develop branch
Related commit(s):
 - ecaa2c01e1d4c57b86a95404b61046db6ae2d580

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.4 verification instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 verification instance for you

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](http://34.228.235.121/i-13095-2-2-4/).
Admin access: [http://34.228.235.121/i-13095-2-2-4//admin](http://34.228.235.121/i-13095-2-2-4//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
![configuration settings stores magento admin](https://user-images.githubusercontent.com/7325075/48378722-2f21e200-e697-11e8-8994-ff1c19c43d2a.png)
