### ISSUE TITLE
issue in magento 2 url rewrite management

### ISSUE THREAD

**Issue by sakti-do** [magento/magento2#13092]
### Preconditions

1. Need to create a rewrite url for a particular category.
2. Need to redirect it to external link

### Steps to reproduce

1. got url rewrite under admin marketing tab
2. create a new url rewrite for a category as custom
3. put "catalog/category/view/id/215/" in request path
4. put "external link to target path and save

### Expected result

1. it should redirect to that given external link

### Actual result

1. it's redirecting to that category page only

**Comment by orlangur** [comment]
@sakti-do does it redirect to external link when you enter URL containing "catalog/category/view/id/215/"?

**Comment by sakti-do** [comment]
@orlangur no, it doesn't work, it's working, if its an internal link.

**Comment by magento-engcom-team** [comment]
@sakti-do Thanks for your report. We tried to reproduce your issue on the clean instance of Magento and external redirections worked fine. Please make reindex and flush your Magento cache, that should help. And please let us know if it helped you thank you.

**Comment by sakti-do** [comment]
@magento-engcom-team , Thanks for your reply, I tried that, but it didn't work. Even I tried with dev mode, but didn't get any luck. Finally, I have managed that using .htaccess

**Comment by magento-engcom-team** [comment]
@sakti-do Thanks for clarifying that, also please let us know if the problem is solved for you. Thank you.

**Comment by sakti-do** [comment]
@magento-engcom-team Using URL rewrite, it's not working. That's why, i have managed that using .htaccess

**Comment by sakti-do** [comment]
@magento-engcom-team URL rewrite is having some issue (Magento 2.1.7). I found another type of issue like,
1. I created a custom url rewrite with **about-mp**
2. then created a category (**about-mp**) and tried to save it and it was showing some error **URL key for specified store already exists.**
3. then i went to URL rewrite management and deleted those already created links with **about-mp.html**
4. again came back to category and tried to save aging but still getting the error message  **URL key for specified store already exists.**

**But, If i'm installing a fresh Magento and trying the same thing then its working fine.
Can you please tell me what could be the issue.**

**Comment by magento-engcom-team** [comment]
@sakti-do , thanks for you update please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@sakti-do, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
