### ISSUE TITLE
installation incomplete ..50%

### ISSUE THREAD

**Issue by sooryakumar** [magento/magento2#13107]
Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Config':

Module 'Magento_Backend':

Module 'Magento_Theme':

Module 'Magento_Eav':

Module 'Magento_Backup':

Module 'Magento_Customer':

Module 'Magento_AdminNotification':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':

Module 'Magento_Cms':

Module 'Magento_Security':

Module 'Magento_CatalogImportExport':

Module 'Magento_Rule':

Module 'Magento_Cron':

Module 'Magento_Catalog':

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Payment':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_User':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_CatalogInventory':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Newsletter':

Module 'Magento_CurrencySymbol':

Module 'Magento_Sales':

Module 'Magento_Integration':

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_Bundle':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_InstantPurchase':

Module 'Magento_Analytics':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Reports':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Vault':

Module 'Magento_Paypal':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_CheckoutAgreements':

Module 'Magento_QuoteAnalytics':

Module 'Magento_ReleaseNotification':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_Shipping':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Captcha':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_ConfigurableProductSales':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_Wishlist':

Module 'Magento_Signifyd':

Module 'Magento_Sitemap':

Module 'Magento_Authorizenet':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_GoogleAdwords':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SampleData':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':

Module 'Magento_CatalogWidget':

Module 'Dotdigitalgroup_Email':

Module 'Magento_WishlistAnalytics':

Module 'Shopial_Facebook':

Module 'Temando_Shipping':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Config':

Module 'Magento_Backend':

Module 'Magento_Theme':

Module 'Magento_Eav':

Module 'Magento_Backup':

Module 'Magento_Customer':

Module 'Magento_AdminNotification':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_Cms':

Module 'Magento_Security':

Module 'Magento_CatalogImportExport':

Module 'Magento_Rule':

Module 'Magento_Cron':
Running schema recurring...

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_Widget':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Payment':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_User':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Newsletter':

Module 'Magento_CurrencySymbol':

Module 'Magento_Sales':

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_InstantPurchase':

Module 'Magento_Analytics':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Vault':

Module 'Magento_Paypal':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_ProductVideo':

Module 'Magento_CheckoutAgreements':

Module 'Magento_QuoteAnalytics':

Module 'Magento_ReleaseNotification':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_Shipping':

Module 'Magento_ReviewAnalytics':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Captcha':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_ConfigurableProductSales':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_SendFriend':

Module 'Magento_Wishlist':
Running schema recurring...

Module 'Magento_Signifyd':

Module 'Magento_Sitemap':

Module 'Magento_Authorizenet':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_GoogleAdwords':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SampleData':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_CatalogWidget':

Module 'Dotdigitalgroup_Email':
Running schema recurring...

Module 'Magento_WishlistAnalytics':

Module 'Shopial_Facebook':

Module 'Temando_Shipping':

Installing user configuration...

Enabling caches:
Current status:
Array ( [config] => 1 [layout] => 1 [block_html] => 1 [collections] => 1 [reflection] => 1 [db_ddl] => 1 [eav] => 1 [customer_notification] => 1 [config_integration] => 1 [config_integration_api] => 1 [full_page] => 1 [translate] => 1 [config_webservice] => 1 ) 

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_Directory':
Installing data... 
[ERROR] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'PRIMARY' in C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\wamp\www\Magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `di...', Array) #5 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `di...', Array) #6 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `di...', Array) #7 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(2005): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `di...', Array) #8 C:\wamp\www\Magento\vendor\magento\module-directory\Setup\InstallData.php(294): Magento\Framework\DB\Adapter\Pdo\Mysql->insertArray('directory_count...', Array, Array) #9 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(867): Magento\Directory\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #10 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(791): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #11 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #12 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(342): call_user_func_array(Array, Array) #13 C:\wamp\www\Magento\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #14 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #16 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #17 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #18 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #19 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #21 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #22 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #23 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #24 C:\wamp\www\Magento\setup\index.php(35): Zend\Mvc\Application->run() #25 {main} Next Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'PRIMARY', query was: INSERT INTO `directory_country` (`country_id`,`iso2_code`,`iso3_code`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?) in C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:235 Stack trace: #0 C:\wamp\www\Magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array) #1 C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 C:\wamp\www\Magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `di...', Array) #4 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `di...', Array) #5 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `di...', Array) #6 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(2005): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `di...', Array) #7 C:\wamp\www\Magento\vendor\magento\module-directory\Setup\InstallData.php(294): Magento\Framework\DB\Adapter\Pdo\Mysql->insertArray('directory_count...', Array, Array) #8 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(867): Magento\Directory\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #9 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(791): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #10 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #11 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(342): call_user_func_array(Array, Array) #12 C:\wamp\www\Magento\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #13 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #14 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #15 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #16 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #17 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #18 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #19 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #20 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #21 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #22 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #23 C:\wamp\www\Magento\setup\index.php(35): Zend\Mvc\Application->run() #24 {main} Next Magento\Framework\DB\Adapter\DuplicateException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 'PRIMARY', query was: INSERT INTO `directory_country` (`country_id`,`iso2_code`,`iso3_code`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?) in C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php:555 Stack trace: #0 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `di...', Array) #1 C:\wamp\www\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(2005): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `di...', Array) #2 C:\wamp\www\Magento\vendor\magento\module-directory\Setup\InstallData.php(294): Magento\Framework\DB\Adapter\Pdo\Mysql->insertArray('directory_count...', Array, Array) #3 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(867): Magento\Directory\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #4 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(791): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #5 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #6 C:\wamp\www\Magento\setup\src\Magento\Setup\Model\Installer.php(342): call_user_func_array(Array, Array) #7 C:\wamp\www\Magento\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #8 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #10 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #11 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #12 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #13 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #15 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #16 C:\wamp\www\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #17 C:\wamp\www\Magento\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #18 C:\wamp\www\Magento\setup\index.php(35): Zend\Mvc\Application->run() #19 {main}

**Comment by magento-engcom-team** [comment]
thank you for your report.
Unfortunately we can not reproduce the issue

**Comment by deepakagarwal2608** [comment]
I also got the same issue...how to solve it
