### ISSUE TITLE
Upgraded M2 2.2.1 to 2.2.2 - 'System' Issues

### ISSUE THREAD

**Issue by bedroomathletics** [magento/magento2#13100]
Hi Guys,

Hope you can help - I am unable to add a new integration in the system admin interface. My hosts have said this is an issue with an upgrade to Magento 2.2.2 so putting it here...

### Preconditions
1. Magento Version 2.2.2
2. Community Edition
3. PHP Version 7

### Steps to reproduce
1. Log in to admin
2. 'System'
3. Under 'Extensions', click 'Integrations'

### Expected result
1. 'Add New Integration' should be visible

### Actual result
1. No button to create action

**(This also happens for; 'System > Import', 'System > Export', 'System > Import and Export Tax Rates', 'System > Import History', 'System > Backups' and 'System > Notifications'.**

See issue here; 
http://recordit.co/jvNOXY4zf4

**Comment by magento-engcom-team** [comment]
@bedroomathletics Thanks for your report. We tried updating from 2.2.1 to 2.2.2 and we weren't able to reproduce the issue, please try to reproduce on the clean instance of magneto without any of the 3'rd party code, and let us know if you can still reproduce it, thank you.

**Comment by bedroomathletics** [comment]
Thanks for the update on this. This is practically a clean install - the only extension(s) we installed at this point were M2E Pro and then the Claue Magento theme? 

Thanks.

**Comment by magento-engcom-team** [comment]
@bedroomathletics We weren't able to reproduce on the clean instance of Magento, seems like it's a problem with the M2E Pro. Or another 3'rd party code. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Also, you can try to direct this problem to your extension support website.
