### ISSUE TITLE
Development Errors Result in Too Many Redirects

### ISSUE THREAD

**Issue by astorm** [magento/magento2#1310]
When an error/uncaught-exception occurs Magento 2, with developer mode on, the current system behavior is to redirect the user to the home page, and then the home page will display the error/exception message.

This often creates a "too many redirects" problem 

The "too many redirects" problem happens if

- There's an error during Magento's homepage loading

- There's an error with/in an observer for an event that fires on every page

There are myriad ways this can and will crop up during regular development, but the easiest way to **reproduce the problem** is

0. Configure your system so developer mode is on

1. Open the `app/code/Magento/PageCache/etc/events.xml` file

2. Find the `Magento\PageCache\Model\Observer\RegisterFormKeyFromCookie` text

3. Temporarily simulate a mis-configuration by changing this to `Magento\PageCache\Model\Observer\RegisterFormKeyFromCookiee`

4. Clear your configuration cache

5. Reload any page in the system

**Expected Behavior**: The browser displays the text, along with a Stack Trace

> Class Magento\PageCache\Model\Observer\RegisterFormKeyFromCookiee does not exist [] []

**Actual Behavior**: Browser gets caught in a redirect loop, resulting in a "This webpage has a redirect loop" error

![screen shot 2015-05-26 at 6 38 19 pm](https://cloud.githubusercontent.com/assets/184372/7826980/6d96b404-03d6-11e5-81d9-84d91d0381c0.png)

While error handling is a complex problem, at minimum it's reasonable for a developer/programmer  to expect their PHP error be displayed on the screen when developer mode is enabled. With error handling being such a multifaceted thing that touches many different aspects of the system, this sort of change is probably best handled by the core and/or development leadership team.  If not coded by them directly "the right" solution ultimately needs to come from a central authority.   

While this is also undesired behavior for **non** developer mode, the issue has not been researched there, and if present may require a different solution in that context.

**Comment by mazhalai** [comment]
@astorm thank you for reporting this issue. We have created ticket MAGETWO-37969 to investigate this issue.

**Comment by antonkril** [comment]
I saw this behavior confuse all developers new to M2 on hackathon. So I think it should be high priority.

**Comment by piotrekkaminski** [comment]
Fully agree - needs to be fixed

**Comment by vpelipenko** [comment]
@astorm, fix is already available on here on public GitHub. Are you OK with provided changes?
