### ISSUE TITLE
Checkout takes 30-60 seconds to complete when products above 50k and stock indexer set to update on save

### ISSUE THREAD

**Issue by djfordz** [magento/magento2#13103]
After submitting final order review to capture payment, checkout takes 30-60 seconds to complete when very large number of products exist and cataloginventory_stock is set to update on Save. We believe this is due to the amount of products being indexed at the time of payment capture to update stock. If said indexer is set to update on schedule the time is reduced by 800%

### Preconditions

1. Magento 2.2.0
2. PHP 7.0.27
3. Aurora DB
4. CentOS 7 with Objfs on containers

### Steps to reproduce

1. Have a store with 50,000+ products
2. set cataloginventory_stock indexer to update on save
3. checkout normally
4. the time it takes to checkout is 30-60 seconds

![database call](http://i.imgur.com/PfEQspQ.png)

### Expected result

1. the checkout time should be at least below 10 seconds

### Actual result

1. [Screenshot, logs]
checkout time is 30-80 seconds
![database](http://i.imgur.com/PfEQspQ.png)

**Comment by ihor-sviziev** [comment]
@djfordz reindex is really slow process, so it's better to execute it in async way, using "update on schedule" mode. So it's not an issue

**Comment by djfordz** [comment]
@ihor-sviziev

Noted

**Comment by djfordz** [comment]
@ihor-sviziev

Actually, after further pondering, I do believe this to be an issue, as it shouldn't reindex entire product base on checkout, just the products that are purchased.

I believe this to be a bug, and I don't believe this was an issue in previous versions.

**Comment by orlangur** [comment]
>  very large number of products exist and cataloginventory_stock is set to **update on Save**

I don't remember such setting ever recommended for production.

**Comment by djfordz** [comment]
I will close this as noted. Thanks for the explanation.

**Comment by ghost** [comment]
The more interesting question is whty the indexer running affects the checkout at all. Is it running in the same thread during checkout ?

**Comment by ihor-sviziev** [comment]
Php actually works in single thread by default. 
In case with "update by schedule" mode - it just adds some record to queue and finalizing checkout, while in "update on save" - it does needed changes just in time of placing order, not in the background

**Comment by chickenland** [comment]
I feel like the issue has been side-stepped here - why is Magento trying to reindex all products instead of just the products that have been purchased?  If it's just adding them to a queue instead of doing it during the checkout, then it's still a problem, no?

**Comment by orlangur** [comment]
@chickenland 

> why is Magento trying to reindex all products instead of just the products that have been purchased?

I doubt it actually works this way.

**Comment by djfordz** [comment]
As an aside, I found out the store I was working on had customized the indexing process. I did not dig into it fully and am currently not on the project so I cannot answer fully any questions here. From what I see in Magento Core code, only the items in the checkout get indexed. Again, I haven't delved too deep which is why this is closed.
