### ISSUE TITLE
Magento CE 2.2.2 -  Set Product as New From (Invalid input datetime format) Locale AU

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#13112]
### Preconditions

1. Magento CE 2.2.2
2. PHP version: 7.0
3. Locale AU

### Steps to reproduce

Set Locale AU
1. Stores > Configuration >General > General > Locale Options
Set Default Country to Australia and Locale to AU
Step 1 Screenshot
https://prnt.sc/ggek4e

2. Admin > Account Settings > My Account > Account Information
Set Interface Locale to English Australia
Step 2 Screenshot
https://prnt.sc/ggelkj

3. Stores > Configuration >Catalog > Catalog >Date & Time Custom Options
Use JavaScript Calendar to Yes and Date Fields Order to dd/mm/yyyy
Step 3 Screenshot
https://prnt.sc/hyqrpk

3. Date format working fine on frontend (dd/mm/yyyy)
Step 4 Screenshot
https://prnt.sc/hyqs9a

4) Configurable Product Set Product as New From
Set Product as New From as dd/mm/yyyy format
Step 5 Screenshot
https://prnt.sc/hyqu91

### Expected result

1.  Configurable Product Set Product as New From Save without error with dd/mm/yyyy format

Screenshot 1
https://prnt.sc/hyqv39

### Actual result

1. Configurable Product Set Product as New From throw error with dd/mm/yyyy format
Screenshot 1
https://prnt.sc/hyquvj

**Comment by gilbertsohal** [comment]
@magento-engcom-team 

Could you please guide me what to do?

**Comment by magento-engcom-team** [comment]
@gilbertsohal, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by gilbertsohal** [comment]
@magento-engcom-team 

Have you solved this issue in 2.2.3?

**Comment by ioweb-gr** [comment]
@gilbertsohal  I'm on a 2.2.3 installation and it's still occurring for me.

**Comment by ioweb-gr** [comment]
Any news on this one?

**Comment by orlangur** [comment]
Such issue definitely shouldn't require more than a year to be fixed. Triggering re-check.

**Comment by VasylShvorak** [comment]
Issue isn't reproduced by described steps on clean 2.3-develop
