### ISSUE TITLE
Multiple Custom option product save issues. Get error "Invalid Form Key. Please refresh the page.".

### ISSUE THREAD

**Issue by ghost** [magento/magento2#13114]
Edit product and add Customizable Options for that, For the multiple option(More than 55), it fires the error message"Invalid Form Key. Please refresh the page."

### Preconditions

1. Magento v2.2.2 sample_data 

### Steps to reproduce

1.  Install Magento v 2.2.2 with sample_data
2. Edit any simple product Catalog -> Product  
3. Add customizable options (I tried with 55 customizable options)

### Expected result

1. Admin can add multiple(More than 55) customizable options 

### Actual result

1.Admin can't add multiple(More than 55) customizable options 

 [I attached the video file]

[custom_option_Invalid_Form_Key.webm.zip](https://github.com/magento/magento2/files/1621587/custom_option_Invalid_Form_Key.webm.zip)

**Comment by magento-engcom-team** [comment]
@emiprotech, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
Hello @magento-engcom-team,
Any update on this issue?

**Comment by VictorTkachenko81** [comment]
You can try increase [max-input-vars](http://php.net/manual/en/info.configuration.php#ini.max-input-vars) value in php.ini

**Comment by haalmaguer** [comment]
Is this already solved?

**Comment by haalmaguer** [comment]
max-input-vars is not working either. I'm using magento2.2 trying to setup a configurable product with more than 3k combinations . @magento-engcom-team  any news?

**Comment by sorinspanu** [comment]
I am also interested in a solution for this issue.

**Comment by ghost** [comment]
I am also getting same issue while saving the product on Magento v2.3.1 EE. 

Product doesn't have any custom options added to it.

Need update on the issue.

**Comment by fairport** [comment]
Magento ver. 2.3.1 CE
Getting this error trying to set up a configurable product with 9 colors & 7 sizes. 
But changing max input vars solved the issue

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30124` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rostyslav-hymon** [comment]
The issue caused by the limit in php variable "max_input_vars" and can be
resolved through increment it. For example current issue is fixing by adding
the line in node <IfModule mod_php7.c> in .htaccess:
php_value max_input_vars=10000

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. 

Thank you for your report and collaboration!

The issue was fixed by Magento team.
