### ISSUE TITLE
Add support to Docker, Docker-compose and kubernetes charts

### ISSUE THREAD

**Issue by hossam-fares** [magento/magento2#13115]
It would be great to have an official containers ecosystem support

**Comment by ihor-sviziev** [comment]
@hossam-fares we're using Magento with docker and docker compose. What would you like to have/see?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-support-to-Docker-Docker-compose-and-kubernetes-charts/idi-p/84510).

**Comment by johnson2677** [comment]
Feature request from hossam-fares, posted on GitHub Jan 10, 2018
It would be great to have an official containers ecosystem support
If anyone wants to learn [Kubernetes Training](https://www.kbstraining.com/kubernetes-training.html) Course, please feel free to ping me.
Thanks & Regards,
