### ISSUE TITLE
when saving product in admin 

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1311]
{"error":true,"html_message":"<div class=\"messages\"><div class=\"message message-error error\"><div data-ui-id=\"messages-message-error\" >Class Magento\\Catalog\\Model\\Product\\Attribute\\Backend\\Startdate does not exist<\/div><\/div><\/div>"}

Magento ver. 0.74.0-beta10

**Comment by mazhalai** [comment]
Thank you for reporting the error @sivajik34. It looks like this is similar to #1300

**Comment by sivajik34** [comment]
yes.but this is from admin interface.

**Comment by mazhalai** [comment]
Yes, but the cause is the same: `Magento\Catalog\Model\Product\Attribute\Backend\Startdate` was renamed to `Magento\Catalog\Model\Attribute\Backend\Startdate`

**Comment by kokoc** [comment]
@sivajik34 Thank you for reporting the issue. The team has processed this ticket. Code changes have just been deployed in version 0.74.0-beta11. Could you please verify the issue?

**Comment by sivajik34** [comment]
working fine.thanks
