### ISSUE TITLE
Designe is gone!

### ISSUE THREAD

**Issue by emilshamloo** [magento/magento2#13127]
### Preconditions

1. Magento 2.2.2, sample product is installed, new theme is installed,

### Expected result

1. Login to back-end, under Store /Configuration/ General, I expect to see "Design" tab .

### Actual result
 I should see the tab " Design", but it is not there!
![image](https://user-images.githubusercontent.com/2904897/34824587-7073aa12-f6cf-11e7-8d36-f1c37c5e9b16.png)

**Comment by magento-engcom-team** [comment]
@emilshamloo Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by ihor-sviziev** [comment]
It was moved. Details: http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-apply.html

**Comment by orlangur** [comment]
Hi @emilshamloo, thanks for your report, it was raised before many times, please check https://github.com/magento/magento2/issues/10269#issuecomment-316086522 for example.
