### ISSUE TITLE
MDVA-275 code is not present in Magento 2.1-develop - 2.3-develop

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#13120]
Emails from admin being sent out using default config’s email, not the specific store email

### Preconditions

1.  2.1-develop
2. 2.2-develop
3. 2.3-develop

### Steps to reproduce

1. Set store's email addresses different on store level than on default level
2. Send a credit memo email or re-send an order email

### Expected result

1. From email address is the address that is configured in the store from which the order is placed

### Actual result

1. From email address is the address that is configured in the default config

https://github.com/magento/magento2/commit/9fc059bc5b5432cadfd2f1cfa3cc2516e607e068 did not make it to the 2.1+ branches. It is only present in branch 2.0.

**Comment by orlangur** [comment]
Oh, nice finding 👍 Wondering if we can analyze git log automatically/semiautomatically to find all missing fixes.

**Comment by magento-engcom-team** [comment]
@ajpevers, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Bravo** [comment]
Hello @AntonEvers 
On Magento 2.4-develop, the Credit Memo email sender is the email 
![custom_email_store](https://user-images.githubusercontent.com/51680745/71576537-a1eb5800-2af9-11ea-8203-bbae6a5234ce.png)
Here is a screenshot from the mail client where you can see that the mail sender is the one configured in Store view
![credit_memo_email1](https://user-images.githubusercontent.com/51680745/71577047-5cc82580-2afb-11ea-86cf-b98decaa91d3.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.
