### ISSUE TITLE
Configurable products without TAX, child with TAX or reverse

### ISSUE THREAD

**Issue by wolfuma** [magento/magento2#13122]
### Preconditions

1. Magento 2.2.1
2. Enable Tax zone and tax class

### Steps to reproduce

1. Add configurable product with different child products (Fe: Colour, storage, etc)
2. Enable taxable goods on configurable product
3. Create child products with different attributes.
4. Put tax class to NONE on any child product
5. Put TAX class to TAXABLE GOODS on any other child product
=> If its configurable without TAX and child with TAX still the same<=

### Expected result

1. Price with TAX on child product with 'TAXABLE GOODS' enabled, price without TAX on child product with TAX to 'None'

### Actual result

1. Child product have same TAX CLASS than configurable product, ignoring the child TAX conf.

**Comment by ghost** [comment]
@wolfuma, thank you for your report.
This is an expected behavior.
