### ISSUE TITLE
No folder  /pub/static/frontend and  /pub/static/backend after installation

### ISSUE THREAD

**Issue by atrhacker** [magento/magento2#1312]
Hello Magento Early Adopters,

I'm having this weird error and I did not suceed to find the origin. First of all I would like to say that I succeeded to perform some installation of Magento 2 on a windows os with a xampp server before.

I'm now trying to install a magento instance on Windows Server with IIS

Basically after configuring composer etc.. the installations runs well. No error mentioned during the installation process etc.. No exceptio and nothing particular in the installation logs.

However at the end when I try to access at the backend or the front store it display the page but no css or images files are loaded. When I looked in the missing ressources, basically I have 404 errors for all css & images files supposed to be located in the following folders

pub/static/frontend/*
pub/static/backend/*

Physically in my folder pub/static/ there is only the _requirejs folder and .htaccess file but no folder frontend and backend

I guess the folder frontend and backend are generated automatically because they are not by default in the initial clone of magento 2.0

So if anyone has got any ideas of where the problem could come from.
I already tryed to uninstall and reinstall and no improvements.

Additional information to consider: I have checked the permissions, the web server has full access (read and write) on every folders and file magento 2.0 root directory.

Have a great day,

Anselme

**Comment by buskamuza** [comment]
Hi @atrhacker ,

you're right - the files for `pub/static` folder should be generated automatically.
But to do this, the Magento application requires Apache's `mod_rewrite` or alternative solution.
We officially do not support IIS, but you can look at https://github.com/magento/magento2/issues/626 , it has a link to Stackoverflow with explanation of how to transform `mod_rewrite` directives to IIS analogue. The `mod_rewrite` directives are located in `pub/static/.htaccess` file.

Another solution is to run Magento CLI command for generation of static files: `./bin/magento setup:static-content:deploy` - it will make necessary files appear in `pub/static` folder. You should re-run the tool every time static view files change (manually or due to installation of new theme/module).

**Comment by atrhacker** [comment]
Hello Olga, thank you very much for your inputs.
Running the CLI command seems to have worked perfectly so far.(altough it was very long)
I completely understand that you don't provide at moment IIS support.

The thing that I don't understand is that the previous version of magento required as well mod_rewrite and I did not have any issues with an installation on IIS sever. Url rewriting were working perfectly without any customization.

I would be as well very much interested if you have any documentation regarding this new cache system for design contents, as in the future I will probably integrate some themes.

Thanks anyway for all your efforts magento team, keep on going, looking forward for the release candidate.

Best, 
Anselme

**Comment by buskamuza** [comment]
I'd suggest these articles:
- http://devdocs.magento.com/guides/v1.0/config-guide/cli/config-cli-subcommands-static-view.html - some information about the command
- http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/bk-frontend-dev-guide.html - documentation section for front-end developers

**Comment by vpelipenko** [comment]
@atrhacker, do you still have any questions?

**Comment by atrhacker** [comment]
hello @vpelipenko 
Just one 
Do you think magento 2 will be IIS compatible in the release candidate version ?
Otheerwise I'm good,

Thanks for your concern and have a great day,

Anselme

**Comment by alankent** [comment]
There are no plans to officially test compatibility with IIS, but if you try and encounter problems you are free to report them. If easy to fix there is no reason not to.
