### ISSUE TITLE
Product view page design is broken, when theme is set using Store Design Schedule

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#13129]
### Preconditions

1. Install Magento ver. 2.2.X with sample data
2. Install (or create) any additional theme

### Steps to reproduce

1. Go to admin panel, open **Content -> Configuration** grid, and set native **Magento Luma** theme for the whole store
2. Open **Content -> Schedule** grid and set additional theme for specific store view to display at the current moment
3. Override related products template for additional theme (for example, copy file _app/code/Magento/Catalog/view/frontend/templates/product/list/items.phtml_ to 
_/app/design/frontend/<additional_theme_vendor>/<additional_theme_name>/Magento_Catalog/templates/product/list/items.phtml_ and add some custom HTML code to that template
4. Set up related products for some product
5. Go to frontend of the store view with additonal theme set up 
6. Open page of the product from the step 4

### Expected result

1. Related products block is displayed with all customizations, specified in the overridden template (_/app/design/frontend/<additional_theme_vendor>/<additional_theme_name>/Magento_Catalog/templates/product/list/items.phtml_)

### Actual result

1. Related products block is using original template, no custom HTML displayed

Issue is connected to the **"product_viewed_counter"** block. All blocks, situated before **"product_viewed_counter"**, are displayed according to the applied additional theme. But all blocks, situated after **"product_viewed_counter"** blocks, are displayed according to the default theme - i. e., **Magento Luma**. As a result, product page design is broken
Please, note: **"product_viewed_counter"** block retrieves current product data, and during processing that data, the current theme is set to the default one, but after no actions to set current theme instead default is performed. See _Magento\Catalog\Block\Ui\ProductViewCounter::getCurrentProductData()_:
`$this->productRenderCollectorComposite
            ->collect($product, $productRender);`

and _Magento\Catalog\Ui\DataProvider\Product\Listing\Collector\Image::emulateImageCreating()_:
`$this->design->setDefaultDesignTheme();`

Temporary solution for the described issue - is to move **"product_viewed_counter"** block to the bottom of the product view page, for example:
`<move element="product_viewed_counter" destination="before.body.end" after="-"/>`

**Comment by Drupalgaga** [comment]
I got the exactly same problem after upgrade to 2.2.2.

**Comment by magento-engcom-team** [comment]
@avgust1111, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@avgust1111, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
