### ISSUE TITLE
Exception log is missing backtrace

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/magento2#13128]
### Preconditions

1. Magento version 2.2.x

### Steps to reproduce

1. Create any exception in the site
2. Open var/log/exception.log

### Expected result

1. We expect the exception error detail is there with FULL debug backtrace

### Actual result

1. We only get the exception error message without the backtrace so it is impossible to identifier where the issue start.

**Comment by magento-engcom-team** [comment]
@onlinebizsoft Thanks for your report. With such steps, no exceptions will be logged into exception.log, but into report.log Please provide more detailed steps in order for us to reproduce the actual issue.

**Comment by onlinebizsoft** [comment]
@magento-engcom-team well this is correct with every exception. And in my exception log file, we only get something like this

[2018-01-11 09:29:22] main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\\Catalog\\Model\\Product\\Interceptor) with the same ID \"1986\" already exists. at /home/led/domain.com/vendor/magento/framework/Data/Collection.php:404)"} []
[2018-01-11 09:30:27] main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\\Catalog\\Model\\Product\\Interceptor) with the same ID \"1986\" already exists. at /home/led/domain.com/vendor/magento/framework/Data/Collection.php:404)"} []
[2018-01-11 09:42:29] main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\\Catalog\\Model\\Product\\Interceptor) with the same ID \"1986\" already exists. at /home/led/domain.com/vendor/magento/framework/Data/Collection.php:404)"} []

So you can see there is no backtrace
(I expect a backtrace like this
Exception #0 (Exception): Item (Magento/CatalogInventory/Model/Stock/Status/Interceptor) with the same ID "98" already exists.
#0 lib/internal/Magento/Framework/Data/AbstractSearchResult.php(233): Magento/Framework/Data/AbstractSearchResult->addItem(Object(Magento/CatalogInventory/Model/Stock/Status/Interceptor))
#1 lib/internal/Magento/Framework/Data/AbstractSearchResult.php(102): Magento/Framework/Data/AbstractSearchResult->load()
#2 app/code/Magento/CatalogInventoryConfigurableProduct/Plugin/GetInStockAttributeOptionsPlugin.php(62): Magento/Framework/Data/AbstractSearchResult->getItems()
#3 lib/internal/Magento/Framework/Interception/Interceptor.php(146): Magento/CatalogInventoryConfigurableProduct/Plugin/GetInStockAttributeOptionsPlugin->afterGetAttributeOptions(Object(Magento/ConfigurableProduct/Model/AttributeOptionProvider/Interceptor), Array, Object(Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor), '128')
..........
..............)

It looks like a change in Magento 2.2.x

**Comment by magento-engcom-team** [comment]
@onlinebizsoft Seems like it's a Feature Request and not a core issue. Feel free to make a pull request for this. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)). Thank you

**Comment by onlinebizsoft** [comment]
@magento-engcom-team very strange, look like you are intended to close issues than listening from community. I had to make many research and testes before reporting this to you but you take it very fast.

And I'm seeing many other cases which is true to many people (including me) and you just close them :)
https://github.com/magento/magento2/issues/12097

**Comment by lbajsarowicz** [comment]
@onlinebizsoft please submit Feature Request instead just like @magento-engcom-team mentioned.

**Comment by hostep** [comment]
I don't think it's a feature request because I can confirm that backtraces were logged in the `exception.log` file in Magento 2.1.x shops. In 2.2.x and 2.3.x shops this no longer seems to happen.
So either this was changed on purpose or either it was broken due to a bug.

Can somebody else confirm this and does somebody else know what happened here?
We should probably re-open this ticket?

**Comment by daiduongvo18** [comment]
Hello @magento-engcom-team

The backtrace was removed since this commit https://github.com/magento/magento2/commit/c0b8d6d6164f8b5e348d8f86e5dff518745f838d. It intends to "preserve compatibility with Exception messages. and support PSR-3 context standard." (http://www.php-fig.org/psr/psr-3/#context).

This change moves the exception detail to the context. However, it doesn't log the full backtrace because the $includeStacktraces property of the class LineFormatter class is not set by default. (https://github.com/Seldaek/monolog/blob/1.26.0/src/Monolog/Formatter/LineFormatter.php#L31).

Currently, Magento doesn't have any option to enable the $includeStacktraces.

Please enable it or implement a config to enable it. **The full backtrack is necessary since it drives developer to the root cause.**

**Comment by MJTheOne** [comment]
Sometimes it really baffles me how broken Magento 2 is.. Everything I keep running into is an already existing issue for many people with no real solutions
Thx @daiduongvo18 !

**Comment by lbajsarowicz** [comment]
@daiduongvo18 I really appreciate your investigation. 
How about contributing your code change to Magento?

**Comment by daiduongvo18** [comment]
@lbajsarowicz Sure. I'll work on it when I have time. Currently I'm busy.

**Comment by david-garcia-garcia** [comment]
One more addition to the composer patches... this is for **magento/framework**.

`diff --git a/Logger/Handler/Base.php b/Logger/Handler/Base.php
index 4c136fd..4b73e61 100644
--- a/Logger/Handler/Base.php
+++ b/Logger/Handler/Base.php
@@ -50,8 +50,9 @@ class Base extends StreamHandler
             $filePath ? $filePath . $this->fileName : BP . DIRECTORY_SEPARATOR . $this->fileName,
             $this->loggerType
         );
-
-        $this->setFormatter(new LineFormatter(null, null, true));
+        $formatter = new LineFormatter(null, null, true);
+        $formatter->includeStacktraces(true);
+        $this->setFormatter($formatter);
     }
 
     /**
`

**Comment by onlinebizsoft** [comment]
@hostep @daiduongvo18 @magento-engcom-team since this https://github.com/magento/magento2/issues/36054 was accepted as an issue and got fixed so I think this one should be opened and confirmed?

**Comment by onlinebizsoft** [comment]
@magento-engcom-team can you verify and re-open?
