### ISSUE TITLE
Multiple Configurable product Attribute and its Option not saving programatically

### ISSUE THREAD

**Issue by mritu19** [magento/magento2#13131]
Hi,

I am working on M2.2.0 and I am writing the script to import product from CSV file. For the same, I have written the code to add/create the Simple Product as well as Configurable product and have successfully able to create both products.
 But I am not able to add multiple attribute (color and material )  and its options in configurable product. I am able to add only one attribute options in configurable product. I want to add both attribute (color and material ) attribute and its option in configurable product so that i can associate all simple product which has created by both attribute (color and material ) options.

Here 'color' attribute options : white,yellow,pink and
 'material' attribute options : 14k,18k,platinum

 My code is below

**Preconditions**
Magento 2.2.0

**Steps to reproduce**
##############################

error_reporting(E_ALL);
ini_set('display_errors', 1);
use Magento\Framework\App\Bootstrap;
try{
    require __DIR__ . '/app/bootstrap.php'; 
	 $bootstrap = Bootstrap::create(BP, $_SERVER);
    $obj = $bootstrap->getObjectManager();
	 $state = $obj->get('\Magento\Framework\App\State');
		$state->setAreaCode('adminhtml'); 
		
$configattr =array('color','material');
		$result = array();
	foreach($configattr as $key=>$attr) {	
		$eavConfig = $obj->get('Magento\Eav\Model\Config');
		$attribute = $eavConfig->getAttribute('catalog_product', $attr);
		$options = $attribute->getOptions();	
		array_shift($options); //remove the first option which is empty

		$attributeValues = [];

		foreach ($options as $option) {
			$attributeValues[] = [
				'label' => $option->getLabel(),
				'attribute_id' => $attribute->getId(),
				'value_index' => $option->getValue(),
			];
		}
		$configurableAttributesData = [
		[
			'attribute_id' => $attribute->getId(),
			'code' => $attribute->getAttributeCode(),
			'label' => $attribute->getStoreLabel(),
			'position' => '0',
			'values' => $attributeValues,
		],
	];
	
	$result[$attribute->getId()]= $configurableAttributesData;
	}
	$associatedProductIds=array(75468,75471,92281,92283,92284);
$product = $obj->create('\Magento\Catalog\Model\Product');

foreach($result as $configattrdata){
	$productRepository = $obj->get('\Magento\Catalog\Api\ProductRepositoryInterface');
	
		$optionsFactory = $obj->create('\Magento\ConfigurableProduct\Helper\Product\Options\Factory');
		
		$configurableOptions = $optionsFactory->create($configattrdata);
		$extensionConfigurableAttributes = $product->getExtensionAttributes();
		$extensionConfigurableAttributes->setConfigurableProductOptions($configurableOptions);
		$extensionConfigurableAttributes->setConfigurableProductLinks($associatedProductIds);
		$product->setExtensionAttributes($extensionConfigurableAttributes);

		$product->setTypeId('configurable')
		->setAttributeSetId(14) //attributeSetId =14 Or 9
		->setWebsiteIds([1])
		->setName('Confignewfcolor')
		->setSku('5thConfigcolor')
		->setVisibility(1)
		->setStatus(1)
		->setStockData(['use_config_manage_stock' => 1, 'is_in_stock' => 1]);
		
	try{
		$productRepository->save($product);
	}catch(Exception $e){
		echo 'catch='.$e->getMessage();
	}	
}
?>
################################

**Expected result**

Both (color and material ) attribute and its option value should be add in configurable product. So that I can Associate the all simple Product which is created with same attribute's options.

Can you please help me regarding the same. Any solution ?

**Comment by magento-engcom-team** [comment]
@mritu19 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
