### ISSUE TITLE
Invalid date when I tried to save Catalog Price Rule with French locale in version 2.2.2.

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#13139]
### Preconditions

1. Magento 2.2.2
2. mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22

### Steps to reproduce

1. Change admin language to French
2. Go to Marketing->Catalog Price Rules and a create New one.
3. In the Date Range choose [date like this](http://joxi.ru/vAWXyZeu109KGr)

### Expected result

1. Save this rule without errors.

### Actual result

1. I have an error because of the [wrong date](http://joxi.ru/vAWXyZeu109KGr)

It is the similar to [#9743](https://github.com/magento/magento2/issues/9743)

**Comment by sunil-gcet** [comment]
Hello @magento-engcom-team  i would like to take a look on this issue., can you please send the invitation

**Comment by sunil-gcet** [comment]
Hi @AleksLi i think i am close on finding the issue, i have replicated it on a fresh install of v2.2.2, although i think the issue is not due to locale but its due to the datepicker fields.

When i investigated i saw the date values to post are like 20/01/+00201818 instead of 20/01/2018 and thus the validation fails on vendor/magento/module-rule/Model/AbstractModel.php:399

I am moving to find the datepicker problem now, will let you know in sometime

**Comment by sunil-gcet** [comment]
on further investigation it seems that the error is coming only on the date formats having year format like "yyyy", which are set from vendor/magento/zendframework1/library/Zend/Locale/Data/ folder for each teritory and language

So 
M/d/yy working correctly
dd/MM/yyyy : not working
dd/MM/yy : working correctly

@magento-engcom-team can you let us know if we are correct in above findings ?

also will this date format issue will be covered in next release ?

**Comment by AleksLi** [comment]
Hi @sunil-gcet. I'm happy to hear that you are close to fixing this. 
Keep me in the loop.

**Comment by magento-engcom-team** [comment]
@AleksLi, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by attheCube** [comment]
@magento-engcom-team
I got the same problem after updating from 2.1.3 to 2.1.10 for german admin language.
Datepicker is formatting like dd.mm.yyyy and js-validation refuses.

**Comment by attheCube** [comment]
@magento-engcom-team
I got the same problem after updating from 2.1.3 to 2.1.10 for german admin language.
Datepicker is formatting like dd.mm.yyyy and js-validation refuses.

**Comment by Detzler** [comment]
> Datepicker is formatting like dd.mm.yyyy and js-validation refuses.

I agree - got the same issue

**Comment by sedax90** [comment]
Same problem with italian language

**Comment by Aza-an** [comment]
Same Issue for English(United Kingdom)

**Comment by sedax90** [comment]
no update for 2.2.5?

**Comment by weblips** [comment]
Same Issue for en_AU (2.2.5)

**Comment by codercv** [comment]
Same for en_GB (2.2.5)

**Comment by engcom-Bravo** [comment]
Hello @AleksLi 
On Magento 2.4-develop, a proper error message appears - "_The end date must be greater than the start date_" 
![date_error](https://user-images.githubusercontent.com/51680745/71581270-18458580-2b0d-11ea-9555-7bc913b7cf23.png)
So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.
