### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1313]
In product list page,search result page clicking products giving 404 error.

**Comment by sivajik34** [comment]
i have done reindex and deleted cache & full page cache also.
➜  bin git:(develop) ✗ php magento indexer:reindex
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Class Magento\Catalog\Model\Product\Attribute\Backend\Startdate does not exist
Product EAV index has been rebuilt successfully in 00:00:06
Stock index has been rebuilt successfully in 00:00:01
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:08

**Comment by mazhalai** [comment]
This is also identical to #1300

**Comment by kokoc** [comment]
@sivajik34 Thank you for reporting the issue. The team has processed this ticket. Code changes have just been deployed in version 0.74.0-beta11. Could you please verify the issue?

**Comment by sivajik34** [comment]
working fine.
