### ISSUE TITLE
Magento 2.2.1 Readiness Check, Cron Scripts, Cloudways

### ISSUE THREAD

**Issue by worla** [magento/magento2#13135]
I have installed Magento 2.2.1 on my Cloudways server. While trying to install an extension in the extension manager. This is what I get

Cron script readiness check failed.

Error from Setup Application Cron Script: Cron job has not been configured yet

### Preconditions

Cloudways automatic installer, Magento 2.2.1 with Varnish

1.  Magento 2.2.1, PHP 7.0,  MySQL 5.6

### Steps to reproduce

1.  Log in to cloudways platform account
2.  Create an a Magento 2.2.1 Application with Varnish. 
3. Go to your admin panel of your application
4. System >> Tools >> Web Setup Wizard
5. Extension Manager, Install an Extension and Check Readiness  

### Expected result

1.  Everything was supposed to be succesful

### Actual result

1. 
![error](https://user-images.githubusercontent.com/8648008/34826992-985deb04-f6d0-11e7-99a6-4e082a0f28e1.png)

**Comment by fooman** [comment]
@worla this issue seems specific to the set up of the cloudways environment. I suggest logging a support issue with them to get your Magento instance set up correctly.

**Comment by worla** [comment]
@fooman , Thank you
