### ISSUE TITLE
Product import with unicode category names

### ISSUE THREAD

**Issue by aref-lazrek** [magento/magento2#13148]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Import a csv file with products containing unicode categories (arabic)
2. File checking is valid

### Expected result
1. Import successful

### Actual result

1. Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`**`.`catalog_category_product`, CONSTRAINT `CAT_CTGR_PRD_CTGR_ID_CAT_CTGR_ENTT_ENTT_ID` FOREIGN KEY (`category_id`) REFERENCES `catalog_category_entity` (`entity_id`) ON DELETE CASCAD), query was: INSERT INTO `catalog_category_product` 

So the problem is that categories are in unicode language (arabic) as now I have translated the categories name to english (about 100) then doing another translate to arabic..
I know that the issue is related to url key which cant be unicode 
For improvments I suggest that there is way to provide the category url or add it in two languages

**Comment by engcom-backlog-nickolas** [comment]
Hello @aref-lazrek, thank you for your report. GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
