### ISSUE TITLE
Missing Billing Address Info via Paypal Express Checkout

### ISSUE THREAD

**Issue by Joedel-Esco** [magento/magento2#13149]
I've been running Magento 2.2.2 CE on RHEL with apache 2.4.6

Missing Billing Address using Paypal Express Checkout ( Production ) this issue is similar with #5873

**Preconditions**
1. RHEL 7.4
2. Magento version 2.2.2 CE ( no Data )
3. PHP 7.1.13
4. Mysql 15.1 Distrib 10.1.30 - MariaDB

**Steps to reproduce**
1. Create a Freshly install Magento 2.2.2 ( No Data )
2. Configure Paypal Express Checkout in Admin Panel
3. Add a Test Product (without a Weight) For checkout purposes
4. Go thru the whole order process until successful payment.
5. Magento Email to customer ( No Billing Address )
6. Check magento Sales -> Order ( Order has No Billing Address )

### Expected result
1. Billing Address is supposed to be added when a user is currently logged in. I also did try to add the billing before checking out added the right details on the billing but still no avail.

### Actual result
1. Blank Billing Address in Admin Panel
![billing info admin panel](https://user-images.githubusercontent.com/34368214/34862341-f016d430-f7a4-11e7-85a4-5ba968270aa2.PNG)

**Comment by Joedel-Esco** [comment]
![email missing billing info](https://user-images.githubusercontent.com/34368214/34863778-221ff89c-f7ac-11e7-94fc-1f518585e77c.PNG)

here is a screenshot of magento automated email from orders. still the billing details is blank/missing

**Comment by magewallet** [comment]
I am not able to understand why there is no fix inside the 2.2.2 version yet. This is a major bug. Please help us to resolve this.

**Comment by heyepic** [comment]
This is also happening to me - definitely a bug.

**Comment by s-hajir** [comment]
Happened also to me. Magento is very unstable. I am using it in production environment and I'm facing new bugs like this everyday. Now moving to a custom solution, can't trust magento 2 anymore

**Comment by heyepic** [comment]
@magento-engcom-team Just making sure you guys see this. There was more bug reports about this but this is the only one I believe is still open. If you want any logs from anyone, we can all help.

**Comment by magewallet** [comment]
Any update on this issue. I dont believe that no one is reacting on this #5873 and #13149 two tickets. We are really say that its very big issue that stop merchant from using Magento 2.2.2. So please if possible give us some update on the same.

Otherwise how we can convince our client to use Magento 2. 

Please help!

**Comment by klein0r** [comment]
Just got the same issue... Getting the {{ }} directives in the backend, in customer mails and in order details in the frontend (customer account). Not that nice...

**Comment by cationstudio** [comment]
bump
I have the same issue using Magento 2.2.3

**Comment by simonmaass** [comment]
me 2

**Comment by klein0r** [comment]
My current workaround:

Ask the customer for the billing address during registration process. No guest orders possible...

app/design/frontend/MKleine/academy/Magento_Customer/layout/customer_account_create.xml
```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="customer_form_register">
            <arguments>
                <argument name="show_address_fields" xsi:type="boolean">true</argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```

**Comment by magewallet** [comment]
Hello

This issue has been fixed in latest release 2.2.4.
I confirmed in my website today.

Thanks to Magento Team.

**Comment by crantron** [comment]
@magewallet do you mind linking the commit for this fix?

**Comment by bordeo** [comment]
Anyone know what commit fixes this problem?

**Comment by catstantin** [comment]
Anyone know what commit fixes this problem?

**Comment by resolvr** [comment]
@catstantin using another System.

**Comment by djuro** [comment]
What would be the commit please?

**Comment by ghost** [comment]
Hi @Joedel-Esco I'm closing this issue on @magewallet comment, that already fixed

**Comment by aniruddh-capital** [comment]
I had the same issue on 2.3 but not related to the migration 
here is the solution which worked for me for anyone still having this issue on 2.3
replace this file /vendor/magento/module-paypal/Model/Express/Checkout.php
with latest of magento version 2.2.4

the update is in this function
_setExportedAddressData

and as its a bug in core file you're fine to replace the core file

**Comment by hackronshins** [comment]
Hi, My recent upgrade is 2.3.1 as magento moves we are upgrading one by one, But we are having an issue which is on Paypal orders we are getting variable prefixes in billing address as email template format. Is there any fix to relates t its.
I tried all above solutions who got fixed, In database also I checked it is perfect. But why it is not fixed yet. We didn't touched anything in code. 
Please help me to get a best solution for this.

![13](https://user-images.githubusercontent.com/23425297/59678466-2293d800-91ea-11e9-8172-e23744ef8b54.PNG)

Please check my attachment

**Comment by lfritsche** [comment]
I'm facing a similar issue 
![image](https://user-images.githubusercontent.com/15127451/61388182-c3dc7f80-a8b7-11e9-803b-71e6e6fd1674.png)
Billing address with two default values, but not the shipping address values.

In my case Paypal disables the possibility to provide a different invoice address during checkout. The checkbox to provide a different billing address get's removed if selecting Paypal. But instead of using the shipment address the fields are transmitted empty.

@aniruddh-capital  The original method in 2.2.4 checked for the country:
![image](https://user-images.githubusercontent.com/15127451/61388433-33526f00-a8b8-11e9-81ff-4ee8be7ef952.png)
If the country is predefined this rule would handle the address as valid although only the country was set - not the full billing address due to default values set (eg. if only one country is available).

Currently using Magento 2.2.8

**Comment by kledy** [comment]
It seems to me that the problem with the incomplete address in Magento 2.3.5 still exists. Does anyone have a solution for it?

**Comment by monak83** [comment]
problem exists yet on Magento 2.3.6. Any ideas to solve?
![paypal_issue](https://user-images.githubusercontent.com/8915414/100331318-4c048600-2fd0-11eb-93cd-36f0feec740f.jpg)

**Comment by fleischanderl** [comment]
@ghost we got the same issue on 2.3.5. Any updates?

**Comment by aaronhuang1** [comment]
same issue on 2.4.1

**Comment by mebbopakko** [comment]
Issue confirmed by two clients with different versions, 2.3.4 and 2.4.3

**Comment by andihuber** [comment]
Can confirm issue in 2.4.4

**Comment by pauldonnelly** [comment]
Can also confirm issue in 2.4.6-p3

**Comment by scottbolasevich** [comment]
seeing this on 2.4.7-p1

**Comment by LuisFRosas** [comment]
the problem persists, can anyone reopen that ticket?
