### ISSUE TITLE
Magento 2.1.5 Payment error

### ISSUE THREAD

**Issue by Anmer** [magento/magento2#13142]
I've Magento 2.1.5 running on LEMP
Braintree,stripe and Ingenico works finally but our locally developed payment won't be able to work what can be causing error ?

### Preconditions
1. Magento 2.1.5
2. Login to magento account with address information are full

### Steps to reproduce

1. add an item to cart
2. proceed to checkout
3. Choose the payment method
4. Place order
5. 3D verification page

### Expected result
1. success purchase page

### Actual result 
1. Error page:
`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please check the billing address information. Please enter the first name. Please enter the last name. Please enter the phone number. Please enter the country.

Exception #0 (Magento\Framework\Exception\LocalizedException): Please check the billing address information. Please enter the first name. Please enter the last name. Please enter the phone number. Please enter the country.
#0 /var/www/magento/vendor/magento/module-quote/Model/QuoteManagement.php(427): Magento\Quote\Model\QuoteValidator->validateBeforeSubmit(Object(Magento\Quote\Model\Quote))
#1 /var/www/magento/vendor/magento/module-quote/Model/QuoteManagement.php(391): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#2 /var/www/magento/vendor/magento/module-quote/Model/QuoteManagement.php(349): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote))
#3 /var/www/magento/app/code/PTR/TrPayment/Controller/Payment/Return3D.php(145): Magento\Quote\Model\QuoteManagement->placeOrder('741')
#4 /var/www/magento/var/generation/PTR/TrPayment/Controller/Payment/Return3D/Interceptor.php(24): PTR\TrPayment\Controller\Payment\Return3D->execute()
#5 /var/www/magento/vendor/magento/framework/App/Action/Action.php(102): PTR\TrPayment\Controller\Payment\Return3D\Interceptor->execute()
#6 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): PTR\TrPayment\Controller\Payment\Return3D\Interceptor->___callParent('dispatch', Array)
#8 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('PTR\\TrPayment\\Con...', 'dispatch', Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Array, 'contextPlugin')
#9 /var/www/magento/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('PTR\\TrPayment\\Con...', 'dispatch', Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Array, 'customer-app-ac...')
#12 /var/www/magento/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('PTR\\TrPayment\\Con...', 'dispatch', Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Array, 'storeCheck')
#15 /var/www/magento/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('PTR\\TrPayment\\Con...', 'dispatch', Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Array, 'weee-app-action...')
#18 /var/www/magento/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('PTR\\TrPayment\\Con...', 'dispatch', Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Array, 'tax-app-action-...')
#21 /var/www/magento/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): PTR\TrPayment\Controller\Payment\Return3D\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(PTR\TrPayment\Controller\Payment\Return3D\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/magento/var/generation/PTR/TrPayment/Controller/Payment/Return3D/Interceptor.php(39): PTR\TrPayment\Controller\Payment\Return3D\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /var/www/magento/vendor/magento/framework/App/FrontController.php(55): PTR\TrPayment\Controller\Payment\Return3D\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#27 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#28 /var/www/magento/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#31 /var/www/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#34 /var/www/magento/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#37 /var/www/magento/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#40 /var/www/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#42 /var/www/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#43 {main}`

**Comment by Anmer** [comment]
Hundreds of tries have been done and many professionals got a look at the issue and debug with no result,  before posting here.

**Comment by sunil-gcet** [comment]
Hello @magento-engcom-team i would like to take a look at this issue
@Anmer can you send the module so i can install it on my server and test it there ? also test credentials if needed.

**Comment by Anmer** [comment]
@sunil-gcet Thanks for interest I sent credentials to your email address, hope you can find issue origin, so if it's module related we can close this this issue but if it's a bug to escalate the issue with more details.

**Comment by Anmer** [comment]
it's been one week with no response from @sunil-gcet so if anybody interested in this I can send test credentials and modules for debugging issue, module used to work with earlier versions of Magento.

**Comment by magento-engcom-team** [comment]
@Anmer please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
