### ISSUE TITLE
2.2.2 - Duplicating bundle product options between products via CSV forces 'Out Of Stock' status.

### ISSUE THREAD

**Issue by MattUnity** [magento/magento2#13158]
This appears to be completely regardless of inventory or stock management status. 

Trying to duplicate bundle options from a source product, to a destination product, via CSV Import/Export results in the destination product being forced into an 'Out Of Stock' status that I can't find a way to rectify, despite the bundle and all product options having a quantity and having their stock status set correctly. 

Tested on a control / vanilla 2.2.2 installation.

### Preconditions
1. Magento 2.2.2
2. PHP 7.0.27

### Steps to reproduce
1. Create one or more simple products, setting them to 'In Stock' and assigning them a quantity.
2. Create a Bundle product containing these simple products as product options, in any configuration. (Referred to as the source bundle)
3. Create a Bundle product without any associated product options. (Referred to as the destination bundle).
4. Perform a product export (CSV, Products, no skipped attributes, no field enclosure)
5. Find the 'bundle_values' cell relating to the source bundle, and copy these values to the cell relating to the destination bundle.
6. Save CSV and perform a Products import with this CSV.
7. On successful import, reindex and clear cache.

### Expected result
1. Both the source and destination bundles should show as in stock, and have exactly the same bundle configuration options.

### Actual result
1. The destination bundle appears as out of stock, despite both the bundle and the simple products being configured as in stock.

**Comment by magento-engcom-team** [comment]
@MattUnity thank you for your report,
> The destination bundle appears as out of stock, despite both the bundle and the simple products being configured as in stock.

Do you mean in backend bundle product has stock status "In Stock" but on the storefront, it isn't displayed?

**Comment by MattUnity** [comment]
That's correct - The bundle itself is flagged as In Stock in back end, and all the corresponding simple product options are all In Stock, but the product itself on front end will not display as anything other than Out Of Stock and refuse to work.

I've tested this on both a 2.1.6 vanilla and 2.2.2 vanilla installation and can confirm it only occurs on 2.2, 2.1 appears to work perfectly fine.

**Comment by magento-engcom-team** [comment]
@MattUnity, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by JesseEnd** [comment]
I am having this same problem with already existing and unchanged products after upgrading from 2.1 to 2.2, no duplicating or importing/exporting involved, but I found a temporary fix and posted it in this similar issue - https://github.com/magento/magento2/issues/12330#issuecomment-381041637

**Comment by engcom-Bravo** [comment]
Hello @MattUnity 
We can not reproduce this issue on Magento 2.4-develop 
In the exported CSV file, we have copied the "bundle_values" cell of the relating bundle, to the "bundle_values" cell of the destination bundle, and performed successful Import.
Both Bundle Products are "In Stock" in Admin and is Store View. 

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.
