### ISSUE TITLE
I have to click twice to toggle a custom option. 

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1315]
**Version:**
Magento 2-0.74.0-beta10

**Browser:**
FF 38.0.1
The issue does not reproduce on Chrome 43.0 or IE 10 (you made me open IE. I hope you're happy).

**Steps to reproduce**
 - Login the admin panel
 - Go to Products->Catalog
 - Click on Add Product
 - In the product add form, click on the tab Custom Options and wait for the ajax call to finish
 - Click on "Add Option" 
 - Click on the arrow  pointing up, near "New Option" title, to toggle the option

**Expected Result**
 - The option box should collapse.

**Actual result**
 - The option box is not collapsed
 - Clicking a second time collapses it.
 - From this point forward click behaves as expected

**Additional info**
 - The problem does not reproduce for any other option added after clicking the toggle button for one option.

**Even more info**
 - The first click on the toggle button logs something in the console
 - for the second click and after nothing else gets logded.

See below a screenshot of how it looks before any toggle click. (console state is important)
![no-clicks](http://i.imgur.com/cJt4I1W.png).  
Now after first toggle click (check console log also) 
![one click](http://i.imgur.com/HwZHJ4s.png)  
And after the second toggle click, the one that actually toggles the option.  
![2clicks](http://i.imgur.com/fgUppFt.png)

**Comment by mazhalai** [comment]
Hello @tzyganu, thank you for reporting this issue. We have created MAGETWO-38026 to track this fix.

**Comment by vpelipenko** [comment]
@tzyganu, internal ticket is closed, it means that issue can't be reproduced. Please, verify it again on the latest code base and let us know results. Thank you.

**Comment by tzyganu** [comment]
@vpelipenko Sorry for the late response. I confirm that this does not reproduce on beta-1.0.0. 
Thanks for the fix.
