### ISSUE TITLE
Listing block cannot be overridden for search results page

### ISSUE THREAD

**Issue by prateekkarki** [magento/magento2#13152]
### Preconditions
Magento 2.2.x
php 7.1

### Steps to reproduce
1. Create a module
2. Add di.xml to update preferences for Magento\Catalog\Block\Product\ListProduct and add a new class to use for the class
3. Add the new class and extend it with Magento\Catalog\Block\Product\ListProduct
4. Use a method from the new class in Magento_Catalog/templates/product/list.phtml

### Expected result
1. Every instance of  Magento\Catalog\Block\Product\ListProduct gets overridden with the new class 

### Actual result
1. This works in every instance except for search results page
2. Search results page still looks for Magento\Catalog\Block\Product\ListProduct and not the new class
![screenshot_6](https://user-images.githubusercontent.com/8191488/34872272-73d7f37c-f7b8-11e7-9eef-a19b2f51bce5.png)

**Comment by magento-engcom-team** [comment]
@prateekkarki, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by prateekkarki** [comment]
@magento-engcom-team Hi, Is there any way I could track the progress on this issue, or estimate the days in which this issue might be resolved?

**Comment by prateekkarki** [comment]
@magento-engcom-team Hi, Is there any way I could track the progress on this issue, or estimate the days in which this issue might be resolved?

**Comment by prateekkarki** [comment]
@magento-engcom-team Is there any workaround for this?

**Comment by Reilu** [comment]
@prateekkarki @magento-engcom-team A fix or workaround for this would be great, I just finished up adding a way to use additional review block templates in the listing, only to find this issue in the search results. Perhaps a plugin? I am trying to dig in and find something.

**Comment by Reilu** [comment]
@prateekkarki in my case it seems an around plugin worked for me. I was trying to use custom templates for the reviews summary other than the default and short versions which were already overridden, so I made one for the \Magento\Review\Block\Product\ReviewRenderer. Hopefully a plugin helps find a solution relative to your needs in the interim.

**Comment by prateekkarki** [comment]
@Reilu Thanks for the workaround, I'll try to work that out. Cheers

**Comment by jacobsenj** [comment]
A fix would be appreciated

**Comment by ZieClaw** [comment]
This is probably because its using a virtual block, so the class name is diffrent?
`<block class="Magento\CatalogSearch\Block\SearchResult\ListProduct" name="search_result_list" template="Magento_Catalog::product/list.phtml">`

Which is defined in etc/frontend/di.xml: 
`<virtualType name="Magento\CatalogSearch\Block\SearchResult\ListProduct" type="Magento\Catalog\Block\Product\ListProduct">`

So I added a preference for this virtual block class and it started working.
Why did you take this approach though? I can only see it giving problems and no gains besides 'cleaner'  but more confusing code.

**Comment by prateekkarki** [comment]
@ZieClaw Oh, I get it now, so that's what was going on. Checking the layout and di in catalog-search module made it all clear. 
I had to take this approach because I needed to display some computed data on each product template. So I overrode the class and added a new method to it which I would use in the list.phtml to get desired output. 
This still is an issue for Magento though cause in such cases, the new virtual type should be created by the overridden class and that's how they should fix this issue.
Thanks for your clarification and workaround. Kudos.

**Comment by ZieClaw** [comment]
@prateekkarki 
I think you misunderstood, I meant why did they even implement 'virtual blocks' they don't really seem to add much besides confusion like what has happened here. Why would you want blocks to have fake names, as you can see it will only allow for even more bugs and confusion.

I had to make two add to cart buttons so I had to edit some parts of this block too.

**Comment by prateekkarki** [comment]
@ZieClaw 
I think they implemented that here to change the `catalogLayer` argument to `Magento\Catalog\Model\Layer\Search` cause layered navigations are different in search pages and in listing pages. But I get your point though there were better ways to implement it.

**Comment by TMMeilleur** [comment]
> This is probably because its using a virtual block, so the class name is diffrent?
> `<block class="Magento\CatalogSearch\Block\SearchResult\ListProduct" name="search_result_list" template="Magento_Catalog::product/list.phtml">`
> 
> Which is defined in etc/frontend/di.xml:
> `<virtualType name="Magento\CatalogSearch\Block\SearchResult\ListProduct" type="Magento\Catalog\Block\Product\ListProduct">`
> 
> So I added a preference for this virtual block class and it started working.
> Why did you take this approach though? I can only see it giving problems and no gains besides 'cleaner' but more confusing code.
@ZieClaw 
Hello, even with this workaround my advanced search result page doesn't display correctly. Is there any news about the issue? Thanks.

**Comment by jakwinkler** [comment]
Any update on this? :-)

**Comment by aario** [comment]
Bump! Any updates?

**Comment by aario** [comment]
Maybe this is the reason and solution:
https://stackoverflow.com/a/55650113/9602691
