### ISSUE TITLE
Credit Card auto cancellation

### ISSUE THREAD

**Issue by shahar-bch87** [magento/magento2#13150]
Preconditions
2.1.5

Steps to reproduce
Customer order using Credit Card as payment

Actual result
order got canceled without doing anything.
![screen shot 2018-01-12 at 4 05 54 pm](https://user-images.githubusercontent.com/13197694/34865140-8c7b677a-f7b2-11e7-87b8-438b0a236f12.png)

**Comment by magento-engcom-team** [comment]
@shahar-bch87 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@shahar-bch87, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
