### ISSUE TITLE
[Magentov2 on HHVM 3.7.0] - Zend_Validate_Exception | encoding not supported

### ISSUE THREAD

**Issue by 7php** [magento/magento2#1316]
Hi I'm trying to install (vanilla) M2 on hhvm. The installation process is via commandline, I get the following error:

**[Zend_Validate_Exception]  Given encoding not supported on this OS**

This happens precisely in the file: **magento2/vendor/magento/zendframework1/library/Zend/Validate/StringLength.php**

inside the function **setEncoding($encoding = null)**

I did a print of **$encoding**, when the error is thrown, the value of **$encoding** is **UTF-8**

Any hints?

**Comment by mazhalai** [comment]
@7php Thank you for reporting this issue. Can you please let us know what version of magento2 did you try? Also what specific OS are you on?

**Comment by 7php** [comment]
Hey there!
Magento version: **0.74.0-beta9**
OS version: **Ubuntu 14.04.2 LTS, Trusty Tahr**

**Comment by mazhalai** [comment]
Thank you @7php. We have created ticket MAGETWO-38055 to try and reproduce this issue. 
Also couple more questions:
- what is the version of php?
- what is the `default_charset` in your `php.ini` file?

**Comment by mazhalai** [comment]
@7php Looks like this issue is related to HHVM, please see this ticket https://github.com/facebook/hhvm/issues/3558

**Comment by 7php** [comment]
@mazhalai 
1) I have already specified in my title that I'm using HHVM 3.7.0 - So PHP version does not apply
2) About the relevance with the ticket you mentioned, I'm not so sure this is the cure

**Comment by mazhalai** [comment]
@7php Thank you for clarifying! The original exception occurs [here](https://github.com/zendframework/zf1/blob/master/library/Zend/Validate/StringLength.php#L212) If you notice, `set_ini` is being called on line [208](https://github.com/zendframework/zf1/blob/master/library/Zend/Validate/StringLength.php#L208), which is what issue https://github.com/facebook/hhvm/issues/3558 is about. Also, can you check what value you get for the PHP_VERSION_ID constant?

**Comment by vpelipenko** [comment]
@7php, we are still waiting for update from you.

**Comment by snohe** [comment]
@7php, since we have not heard back from you, we will go ahead and close this issue for now.  In case you have any new information, please do submit a new issue.  Thank you for using Magento 2!
