### ISSUE TITLE
Custom address attributes with "Show on Storefront" set to "No" still show in checkout

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#13168]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Create a custom customer address attribute
2. Set "Show on Storefront" to "No"
3. Select all forms in "Forms to Use In"
4. Register a customer
5. In the backend, fill the value of the custom attribute with "This should be hidden"
6. Add a product to your cart, go to checkout, login
7. Proceed to the shipping address page

### Expected result

1. My address should be shown without the custom attribute value

### Actual result

1. "This should be hidden" is rendered under the address
<img width="879" alt="screen shot 2018-01-14 at 12 22 46" src="https://user-images.githubusercontent.com/1489129/34913389-c55affe6-f925-11e7-9066-455f8fa67ed9.png">

**Comment by magento-engcom-team** [comment]
@ajpevers , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@ajpevers, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
