### ISSUE TITLE
Android Checkout Performance

### ISSUE THREAD

**Issue by jaume-solis** [magento/magento2#13164]
### Preconditions

Magento version 2.2.1
PHP 7
10.1.26-MariaDB-0+deb9u1
Debian 9.1

### Steps to reproduce

1. Start Website on Android Mobile like Huawei P10
2. Add to cart a product
3. Go to Checkout

### Expected result

1. Load Checkout like Desktop and Iphone, on these devices, knockout checkout appears on 1 second aprox.

### Actual result

PHP page loads on correct time, but knockout checkout time is over 10 seconds later.

**Comment by ghost** [comment]
@jaume-solis, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
