### ISSUE TITLE
Installer resets admin password

### ISSUE THREAD

**Issue by ju5t** [magento/magento2#13166]
### Preconditions

We're running Magento2 in a Docker container. We try to verify if we're connecting to an existing installation with `bin/magento setup:db:status` but for reasons beyond my knowledge this fails. It returns `No information is available: the Magento application is not installed.`. I assume this doesn't actually connect to the database but verifies it through a local file. I'm not a Magento guru so I might be wrong here.

Although it would be awesome if we could speed up the provisioning of new containers it's not much of a concern for us. What we didn't expect though was Magento2 to reset the admin's password.

The command we use to install Magento is:

```
INSTALL_CMD="$MAGENTO_CMD setup:install --base-url="$URI" --admin-firstname="$ADMIN_FIRSTNAME" --admin-lastname="$ADMIN_LASTNAME" \
          --admin-email="$ADMIN_EMAIL" --admin-user="$ADMIN_USERNAME" \
          --admin-password="$ADMIN_PASSWORD" --language="$LANGUAGE" --currency="$CURRENCY" \
          --timezone="$TIMEZONE" --use-rewrites=1"
```

All variables are replaced with their corresponding values. 

`setup:config:set` runs before `setup:db:status` following the prerequisites mentioned in [install-cli-subcommands-db-status](http://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-subcommands-db-status.html).

I understand that this may in fact be a feature. In that case I would very much like to understand what would be recommended from Magento's point of view to verify if an installation is active or not when provisioning additional servers (be it in Docker, VMs or hardware). I'm aware of my lack of knowledge in the Magento2 area.

Our environment:
* Docker
* PHP 7.0.23
* Apache 2.4
* Magento 2.2.2, but 2.2.1 had the same problem

### Steps to reproduce
1. Run the installer.
2. Change the password of the first admin user.
3. Run the installer again.

### Expected result
1. No password changes.

### Actual result
1. The password of the admin user is changed.

**Comment by ju5t** [comment]
I have spent the better part of the day debugging what's going on. I found that for the deployment to work consistently I need to include both `app/etc/env.php` and `app/etc/config.php` in source control. This means I can now work around the issue where the admin's password is changed but it's not perfect. 

You could argue that once the application is installed there is no need to test for it being installed again. You just add both files to source control and make sure `setup:upgrade` runs if required. But we have temporary test/staging environments that are automatically provisioned through CI for specific branches. In those cases we need to run the installer and initialise the database as if it were a new installation.

Here is where it starts to get tricky. I'll explain in as much detail as I can what it is that we do.

In order to work around the installer changing the admin password (on production..) I have added the `install` array to `app/etc/env.php`. This file now looks like this:

```
<?php
return array(
  'install' => array('date' => 'Tue, 21 Nov 2017 15:06:38 +0000',),
);
```

Once a new container/server starts it roughly follows the process below:

1. Run `setup:config:set`
2. Check `setup:db:status`: run the installer if it says *not installed* or *none*
3. Run `setup:upgrade`, `setup:di:compile` and `setup:static-content:deploy`

If I leave out `install` from the array in `app/etc/env.php` it will always run the installer as `setup:db:status` will give back that it hasn't been installed.

If I add `install` in the array the installer will run only when it finds *none* in the output. This will work in most cases but it cannot handle new modules. New modules will match *none* and we have told it to run the installer if it does. Now we could make this check more thorough and check or count the number of times *none* was found in the output of `setup:db:status`. Perhaps that's the best solution in our case but I'm wondering how other Magento2 admins handle this.

What can we improve?

**Comment by orlangur** [comment]
Hi @ju5t,

I'm not quite sure I understood the problem correctly

> **Steps to reproduce**
> Run the installer.
> Change the password of the first admin user.
> Run the installer again.

After installer is run again does admin user password match `--admin-password="$ADMIN_PASSWORD"` specified via CLI?

**Comment by ju5t** [comment]
@orlangur yes. And perhaps that is to be expected or in fact a feature, but as the installer made no other changes I didn't see it coming.

**Comment by orlangur** [comment]
It would be pretty strange behavior if installer would ignore `--admin-password="$ADMIN_PASSWORD"` passed via CLI.

So, installer here does what it is supposed to do. if you want to preserve password for some admin user, simply use another admin user account in CLI, probably you can even disable such account.

**Comment by ju5t** [comment]
I found it confusing but perhaps that's my misunderstanding of `--cleanup-database` in this context. With that in mind I don't agree with the conclusion but it's no problem for us right now.

We have a workaround that stops the installer from running in case a custom check finds Magento to be installed already.
