### ISSUE TITLE
how to switch website on storefront header

### ISSUE THREAD

**Issue by benyang2015** [magento/magento2#13175]
### Preconditions

1. magento 2.2.2
2. php7.1.8,mysql5.8

### Steps to reproduce

1. add the block to the vendor/magento/module-theme/view/frontend/layout/default.xml 
<block class="Magento\Framework\View\Element\Template" name="header-website" template="Magento_Theme:html/website.phtml" />
2. on the  Magento\Framework\View\Element\Template.php
add the function 
public function getWebsites() {
    $this->_storeManager->getWebsites();
}

3. on the website.phtml

![image](https://user-images.githubusercontent.com/15188607/34937156-bf8d8760-fa1e-11e7-9908-f93815139db0.png)

4.clear cache,
5.on the storefront,no display the websit dropdown

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@benyang2015 Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by magento-engcom-team** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment]
@benyang2015, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
