### ISSUE TITLE
Magento EE 2.2 PHPUNIT not installed

### ISSUE THREAD

**Issue by weynhamz** [magento/magento2#13176]
Fresh installed Magento EE 2.2, no vendor/bin/phpunit exists after `composer install`. 

### Preconditions

1. Magento EE 2.2
2. With Composer

### Steps to reproduce

1. composer install

### Expected result

1. vendor/bin/phpunit exists

### Actual result

1. No vendor/bin/phpunit exits

Tried run `composer require phpunit/phpunit` manually, shows below error:

> Using version ^6.5 for phpunit/phpunit
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install phpunit/phpunit 6.5.5
>     - Conclusion: don't install phpunit/phpunit 6.5.4
>     - Conclusion: don't install phpunit/phpunit 6.5.3
>     - Conclusion: don't install phpunit/phpunit 6.5.2
>     - Conclusion: don't install phpunit/phpunit 6.5.1
>     - phpunit/phpunit 6.5.0 conflicts with zendframework/zend-session[2.8.3].
>     - phpunit/phpunit 6.5.0 conflicts with zendframework/zend-session[2.8.3].
>     - phpunit/phpunit 6.5.0 conflicts with zendframework/zend-session[2.8.3].
>     - Installation request for phpunit/phpunit ^6.5 -> satisfiable by phpunit/phpunit[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
>     - Installation request for zendframework/zend-session (locked at 2.8.3) -> satisfiable by zendframework/zend-session[2.8.3].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

Looks like zend-session clearly states conflicts with phpunit-6.5, https://packagist.org/packages/zendframework/zend-session.

**Comment by bydrei** [comment]
PHPUnit is under vendor/phpunit not vendor/bin/phpunit

**Comment by weynhamz** [comment]
Yes, I am aware of that, I means the binary symlink, but also, vendor/phpunit is not there too. It is not installed due to conflict with zend-ssion.

**Comment by weynhamz** [comment]
If I manually require a lower version 6.4.4, it installed,  but some tests failed to run.

**Comment by bydrei** [comment]
@weynhamz magento uses an older version, thats why the tests fails. Magento currently uses `"phpunit/phpunit": "4.1.0"` which is obsolete but thats what they use :/

**Comment by magento-engcom-team** [comment]
@weynhamz , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@weynhamz, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
