### ISSUE TITLE
{"message":"Request does not match any route."}

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1318]
i'm using following syntax : 
curl -X POST http://localhost/magento2/index.php/rest/V1/createAccount:customers -H  "Authorization: Bearer uvdhea5fwq2yu4w2lvm9o2q8u30hnq76" -H "Content-Type:application/json" -d '{
    "customers": {
        "customer": {
            "email": "user@example.com",  
            "firstname": "John",
            "lastname": "Doe"
        },
        "addresses": [
            {
                "defaultShipping": true,
                "defaultBilling": true,
                "firstname": "John",
                "lastname": "Doe",
                "region": {
                    "regionCode": "CA",
                    "region": "California",
                    "regionId": 12
                },
                "postcode": "90001",
                "street": ["Zoe Ave"],
                "city": "Los Angeles",
                "telephone": "555-000-00-00",
                "countryId": "US"
            }
        ]
    }
}' 

can you give idea where i'm wrong

**Comment by alankent** [comment]
The route implies the vert/URL did not match. In the webapi.xml file when you see :foo it means that URL segment is mapped to an argument called foo - you don't type it in verbatim. Looking at https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/etc/webapi.xml#L119 I think you should be doing a POST to /V1/customers (I am on iPad, no laptop handy, so I have not tried it to verify - just firing a quick response off).

**Comment by sivajik34** [comment]
curl -X POST http://localhost/magento2/index.php/rest/V1/createAccount -H  "Authorization: Bearer uvdhea5fwq2yu4w2lvm9o2q8u30hnq76" -H "Content-Type:application/json" -d '{
    "customers": {
        "customer": {
            "email": "user@example.com",  
            "firstname": "John",
            "lastname": "Doe"
        },
        "addresses": [
            {
                "defaultShipping": true,
                "defaultBilling": true,
                "firstname": "John",
                "lastname": "Doe",
                "region": {
                    "regionCode": "CA",
                    "region": "California",
                    "regionId": 12
                },
                "postcode": "90001",
                "street": ["Zoe Ave"],
                "city": "Los Angeles",
                "telephone": "555-000-00-00",
                "countryId": "US"
            }
        ]
    }
}' 
still 404 error.

**Comment by sivajik34** [comment]
working fine with:
curl -X POST localhost/magento2/index.php/rest/V1/customers/ -H  "Authorization: Bearer uvdhea5fwq2yu4w2lvm9o2q8u30hnq76" -H "Content-Type:application/json" -d '{
    
        "customer": {
            "email": "user34@example.com",  
            "firstname": "John",
            "lastname": "Doe"
        },
        "addresses": [
            {
                "defaultShipping": true,
                "defaultBilling": true,
                "firstname": "John",
                "lastname": "Doe",
                "region": {
                    "regionCode": "CA",
                    "region": "California",
                    "regionId": 12
                },
                "postcode": "90001",
                "street": ["Zoe Ave"],
                "city": "Los Angeles",
                "telephone": "555-000-00-00",
                "countryId": "US"
            }
        ]
    
}
