### ISSUE TITLE
Authorize.net Payment Merchant Timeout Errors

### ISSUE THREAD

**Issue by ananth-iyer** [magento/magento2#13183]
### Preconditions

1. Tested on Magento 2.1.0 CE & Magento 2.2.2 CE

### Steps to reproduce

1. Setup a sandbox account with authorize.net
2. Try to place an order using test credit card data

### Expected result

1. Should place the order successfully.

### Actual result

1. Transaction request post params: x_version:3.1
x_delim_data:FALSE
x_relay_response:TRUE
x_test_request:TRUE
x_login:73dKDJkco
x_method:CC
x_relay_url:http://somedomain.com/authorizenet/directpost_payment/response
x_type:AUTH_ONLY
x_fp_sequence:39
x_invoice_num:000000027
x_amount:64
x_currency_code:USD
x_tax:0.00
x_freight:5.00
x_first_name:Greg
x_last_name:Peterson
x_company:
x_address:10090 patterson
x_city:caledonia
x_state:Michigan
x_zip:49316
x_country:US
x_phone:6166166166
x_fax:
x_cust_id:
x_customer_ip:88.202.226.17
x_customer_tax_id:
x_email:something@xxxxxxx.com
x_email_customer:0
x_merchant_email:
x_ship_to_first_name:Greg
x_ship_to_last_name:Peterson
x_ship_to_company:
x_ship_to_address:10090 patterson
x_ship_to_city:caledonia
x_ship_to_state:Michigan
x_ship_to_zip:49316
x_ship_to_country:US
x_po_num:
x_fp_timestamp:1516019478
x_fp_hash:924909bede8f8faa9c766aa806f3a1a0
controller_action_name:directpost_payment
is_secure:
x_exp_date:02/20
x_card_num:4012888888881881

2. Here is the output : `<HTML><BODY><TABLE Width="600"><TR><TD>The reporting of this transaction to the Merchant has timed out. An e-mail has been sent to the merchant informing them of the error. The following is the result of the attempt to charge your credit card. <BR><BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This transaction has been approved.<BR><P>It is advisable for you to contact the merchant to verify that you will receive the product or service.<BR></TD></TR></TABLE></BODY></HTML>`

**Comment by YevSent** [comment]
Hi, @Ananth747, your sandbox configuration is invalid.
The `test mode` option should be `false` for sandbox accounts, it used only for production accounts.
Also, please, check if your Authorize.net URLs configured correctly:
Gateway URL: https://test.authorize.net/gateway/transact.dll 
Transaction Details URL: https://apitest.authorize.net/xml/v1/request.api

**Comment by ananth-iyer** [comment]
Hi, @Joni-jones, as you said I have changed `test mode` option to `false` then changed Gateway URL and Transaction Details URL to test URLs.

After that, we tested on development website and got below message from test transact.dll URL:

> An unanticipated error occurred while processing this request. Please click your browser's Back button to return to the previous page.

Please let me know how to solve the above issue.

**Comment by YevSent** [comment]
At first, you need to check `debug.log` and `exception.log` in Magento, also, please, check transaction status on Authorize.net side. Seems like something is not configured properly.

**Comment by ananth-iyer** [comment]
I got it working on the live website because it is HTTPS Enabled.

But I got news that DPM is Deprecated by Authorize.Net. So will Magento 2 team find any replacement for it? REF Link: [https://developer.authorize.net/api/upgrade_guide/#sim](https://developer.authorize.net/api/upgrade_guide/#sim)

**Comment by YevSent** [comment]
There are will be new integration based on Authorize.net Accept.js, unfortunately, I can't provide more details, like when it will be available and which features will be included.

**Comment by pankajpragma** [comment]
@Ananth747 Did you get any solution to an issue? I am facing the same issue in live mode.

**Comment by ananth-iyer** [comment]
@pankajpragma I'm using ParadoxLabs Authnet.Net CIM extension which solved this issue and gives extras features for admin & customer.

**Comment by Wadekone** [comment]
Can someone please advise if the Magento's 2.2.3 EE Authorize.net built in implementation works at all at the moment? 
Or one should use some alternative extension like the one from ParadoxLab, or else?
Thanks,
Vad
