### ISSUE TITLE
percentage code not correctly working

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#13186]
Hello Community,

i have the magento 2 installed and now problems in the rabattcodes and the taxes.
I have simply 20% rabatt code, but still the summery is not corectly.
why it is so?

![image](https://user-images.githubusercontent.com/31250340/34958186-0a4bff40-fa31-11e7-81a6-6747b949f7aa.png)

**Comment by magento-engcom-team** [comment]
@Olek89 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [X] Preconditions: Magento version
 - [X] Steps to reproduce
 - [X] Expected result
 - [X] Actual result

**Comment by ruthgeridema** [comment]
Hi @Olek89 ,
Please check your tax settings on your shop. It's not a Magento 2 bug.
You get 20% discount of the price excluding TAX (Mwst.) at the moment, not from the price including TAX.

99,95/1,19 (price excluding TAX) = 83,99
20% of 83,99 = 16,80

**Please check in your Admin:**
Stores > Configuration > Sales > Tax > Calculation Settings > Apply Discount On Prices.
I believe it states 'Excluding tax' at the moment (Ohne Mwst.) 
Please change it to (Inklusiv Mwst.), and let me know if it helps.

**Comment by Olek89** [comment]
Hello ruther92,

thank you very much, that`s working.

**Comment by magento-engcom-team** [comment]
@Olek89, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by ruthgeridema** [comment]
No problem! @Olek89
