### ISSUE TITLE
jquery-cookie.js not found (Error 404)

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1319]
PHP: ```5.6.9```
Magento: ```0.74.0-beta11```
Web Service: ```nginx```

I already run ```php bin/magento setup:static-content:deploy```

![1](https://cloud.githubusercontent.com/assets/11070293/7896697/7459fd78-06ec-11e5-969b-83a51203937f.PNG)

I also got errors below while deploying static contents.
>=== frontend -> Magento/blank -> en_US ===
................................................................................................................................................................................................................................................................................................................................................The "/var/www/html/magento2/" file doesn't exist or not a file (Processing file 'images/select-bg.svg' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.............The "/var/www/html/magento2/" file doesn't exist or not a file (Processing file 'fonts/selection.json' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/html/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.eot' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/html/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.ttf' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/html/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.svg' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/html/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.woff2' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/html/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.woff' for area 'frontend', theme 'Magento/blank', locale 'en_US')
................................................................................................................................................................

**Comment by FagnerMartinsBrack** [comment]
I suggest upgrading to [js-cookie](https://github.com/js-cookie/js-cookie/releases) when possible, check [here](https://github.com/carhartl/jquery-cookie/tree/d72bb07e29962330db61aae1eda07f6312419840#important).

**Comment by mazhalai** [comment]
@adzminz thank you for reporting this issue. Can you please tell us what is your [mode of magento](http://devdocs.magento.com/guides/v1.0/config-guide/config/magento-mode.html)? 

We have created MAGETWO-37911 to track this issue.

**Comment by adzminz** [comment]
@mazhalai production mode.

**Comment by SamTay** [comment]
@adzminz From the issue referenced above (#1360) a temporary workaround has been found: copy the ``jquery.cookie.js`` to a file called ``jquery-cookie.js``.

I totally missed that the browser was trying to access the the file with the hyphen. Good catch @vortex-mike.

**Comment by vortex-mike** [comment]
you may need to have both files for it to work... it's being called differently in different places

**Comment by adzminz** [comment]
@SamTay @vortex-mike Thank you!

**Comment by vpelipenko** [comment]
Fix is available from 0.74.0-beta15. Please, check the issue on this version.

**Comment by adzminz** [comment]
Thank you.

**Comment by archetypeworks** [comment]
how can I change file name jquery-cookie.js insted jquery.cookie.js in magento 2 (CE)
can you please explain setp by step.

I have changed here bellow but till now jquery.cookie.js  called insted jquery-cookie.js and given 404 error.

<magento root>\dev\tests\js\JsTestDriver\jsTestDriverOrder.php (1 hit)
    Line 18:     '/lib/web/jquery/jquery.cookie.js',
  <magento root>\dev\tests\js\JsTestDriver\testsuite\lib\storage\index.html (1 hit)
    Line 19:     <script src="../../../pub/lib/jquery/jquery.cookie.js"></script>
  <magento root>\pub\static\adminhtml\Magento\backend\en_US\js\bundle\bundle0.js (1 hit)
    Line 3:         'jsbuild':{"Magento_Variable/variables.js":"/**\n \* Copyright \u00c2\u00a9 2016 Magento. All rights reserved.\n \* See COPYING.txt for license details.\n */\ndefine([\n    'jquery',\n    'mage/translate',\n    'Magento_Ui/js/modal/modal',\n    'jquery/ui',\n    'prototype',\n], function(jQuery, $t){\n\nwindow.Variables = {\n    textareaElementId: null,\n    variablesContent: null,\n    dialogWindow: null,\n    dialogWindowId: 'variables-chooser',\n    overlayShowEffectOptions: null,\n    overlayHideEffectOptions: null,\n    insertFunction: 'Variables.insertVariable',\n    init: function(textareaElementId, insertFunction) {\n        if ($(textareaElementId)) {\n            this.textareaElementId = textareaElementId;\n        }\n        if (insertFunction) {\n            this.insertFunction = insertFunction;\n        }\n    },\n\n    resetData: function() {\n        this.variablesContent = null;\n        this.dialogWindow = null;\n    },\n\n    openVariableChooser: function(variables) {\n ...
  <magento root>\pub\static\frontend\Magento\blank\en_US\js\bundle\bundle0.js (1 hit)
    Line 8:         'jsbuild':{"Magento_Ui/js/view/messages.js":"/**\n \* Copyright \u00c2\u00a9 2016 Magento. All rights reserved.\n \* See COPYING.txt for license details.\n _/\ndefine([\n    'ko',\n    'jquery',\n    'uiComponent',\n    '../model/messageList'\n], function (ko, $, Component, globalMessages) {\n    'use strict';\n\n    return Component.extend({\n        defaults: {\n            template: 'Magento_Ui/messages',\n            selector: '[data-role=checkout-messages]',\n            isHidden: false,\n            listens: {\n                isHidden: 'onHiddenChange'\n            }\n        },\n\n        initialize: function (config, messageContainer) {\n            this._super()\n                .initObservable();\n\n            this.messageContainer = messageContainer || config.messageContainer || globalMessages;\n\n            return this;\n        },\n\n        initObservable: function () {\n            this._super()\n                .observe('isHidden');\n\n            return this;\n        ...
  <magento root>\pub\static\frontend\Magento\luma\en_US\js\bundle\bundle0.js (1 hit)
    Line 8:         'jsbuild':{"Magento_Ui/js/view/messages.js":"/_*\n \* Copyright \u00c2\u00a9 2016 Magento. All rights reserved.\n \* See COPYING.txt for license details.\n */\ndefine([\n    'ko',\n    'jquery',\n    'uiComponent',\n    '../model/messageList'\n], function (ko, $, Component, globalMessages) {\n    'use strict';\n\n    return Component.extend({\n        defaults: {\n            template: 'Magento_Ui/messages',\n            selector: '[data-role=checkout-messages]',\n            isHidden: false,\n            listens: {\n                isHidden: 'onHiddenChange'\n            }\n        },\n\n        initialize: function (config, messageContainer) {\n            this._super()\n                .initObservable();\n\n            this.messageContainer = messageContainer || config.messageContainer || globalMessages;\n\n            return this;\n        },\n\n        initObservable: function () {\n            this._super()\n                .observe('isHidden');\n\n            return this;\n        ...
  <magento root>\vendor\magento\magento2-base\dev\tests\js\JsTestDriver\jsTestDriverOrder.php (1 hit)
    Line 18:     '/lib/web/jquery/jquery.cookie.js',
  <magento root>\vendor\magento\magento2-base\dev\tests\js\JsTestDriver\testsuite\lib\storage\index.html (1 hit)
    Line 19:     <script src="../../../pub/lib/jquery/jquery.cookie.js"></script>

**Comment by dazimax** [comment]
You could fix this issue by follow up below steps,

  1) Set deploy mode to production - **php magento deploy:mode:set production**
       (js and css minification will works with production mode.If you are in developer mode with code minified above issues will show up as I experienced it. Also verify using echo the print_r($_SERVER) in index.php that production mode is set before load the website)

  2) Clear all the caches setup in server
        **/etc/init.d/nginx restart**  
        **/etc/init.d/php5.6-fpm restart**
        **/etc/init.d/varnish restart**

  3) Clear the browser cache and view it in incognito mode. That's it! 

Cheers!
