### ISSUE TITLE
Https not working for images, css

### ISSUE THREAD

**Issue by owenhaynes** [magento/magento2#1320]
I don't think the secure URLS work for the media like css, javascript etc. unless I have configured it wrongly. using the default provided theme.

All use the http link

**Comment by Alessandro77** [comment]
+1

**Comment by alankent** [comment]
There is internal design going on around HTTPS at the moment. Eg have easy full site in HTTPS and full site in HTTP. Any suggestions on combinations of HTTP and HTTPS and why would be interesting inputs to the discussion. Eg is all HTTP and all HTTPS enough? If not, why?
