### ISSUE TITLE
In magento 2.2.2 Url Options issue

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#13205]
### Preconditions

1. magento 2.2.2
2. php71

### Steps to reproduce

1. Setting Url Options > 
2. Add Store Code to Urls > YES
3. When i changing other language store the `?___from_store=` is showing.

### Expected result

1. Fix and Remove http://exsample.com/en/ ?___from_store=fr
2. http://exsample.com/fr/ > http://exsample.com/en/

### Actual result

1. http://exsample.com/fr/
2. http://exsample.com/en/?___from_store=fr

**Comment by magento-engcom-team** [comment]
@rigu12, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by andy17612** [comment]
Have a solution now? @magento-engcom-team Thank you

**Comment by jakubderdziak** [comment]
Hello @andy17612 
I tried to resolve it - proposed solution is in PR linked to this issue. Please verify if it works for you.

@magento-engcom-team can you verify if it's acceptable solution?

**Comment by Leone** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leone. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leone, here is your [Magento instance](https://i-13205-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-13205-2-4-develop.instances.magento-community.engineering/admin](https://i-13205-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Leone** [comment]
This issue is not reproducible on 2.4-develop branch.
