### ISSUE TITLE
Wysiwyg editor fails on IE11

### ISSUE THREAD

**Issue by mihaifaget** [magento/magento2#13209]
Install a clean magento. I am using 2.1.9 but the same thing happens in 2.2.2 and will happen on any version that still uses tinyMce 3.4.7

## Preconditions

Magento Version 2.*
## Steps to reproduce

Go to magento backend and edit any wysiwyg field using IE11. Select a text and click the link button. Or just click the wysiwyg html button.
## Expected result

Inserted link should be attached to selected text or I can see the html source of the wysiwyg content
## Actual result

Selected text gets deselected when click link button. Html source is empty when clicking html button

**Comment by magento-engcom-team** [comment]
@mihaifaget, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by krzksz** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [Magento instance](https://i-13209-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-13209-2-3-develop.instances.magento-community.engineering/admin](https://i-13209-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @mihaifaget. Thank you for your report. 
The issue has been fixed in magento/magento2#25693 by @krzksz in 2.3-develop branch
Related commit(s):
 - [ddb9acb6aab086844306e637c38e01b1433de583](https://github.com/magento/magento2/commit/ddb9acb6aab086844306e637c38e01b1433de583)

The fix will be available with the upcoming 2.3.5 release.
