### ISSUE TITLE
Currency symbol not appearing in arabic store view

### ISSUE THREAD

**Issue by aref-lazrek** [magento/magento2#13207]
### Preconditions

1. PHP 7.1
2. Magento 2.2.2

### Steps to reproduce

1. Created second store view with Arabic locale
2. Set the currency as SAR (saudi arabia riyal)

### Expected result

1. Currency symbol appear on arabic store view

### Actual result

1. Currency symbol is appearing in english store view but in arabic it's missing
![arabic_currency_symbol](https://user-images.githubusercontent.com/51680745/71588025-a844f880-2b28-11ea-9477-6fdc4b629af8.png)

I've seen many discussion where they edited vendor/magento/zendframework1/library/Zend/Locale/Data/ar_SA.xml and removed numbers tag and its child tags, I've tried that and it's working

**Comment by magento-engcom-team** [comment]
@aref-lazrek, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ashvinim0003** [comment]
Hi @aref-lazrek  

Copy the currency and numbers block from en.xml and paste it into the ar_SA.xml
it will work.

**Comment by mahmoudissmail** [comment]
Hi @aref-lazrek ,

Update `ar_SA.xml` like below:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Copyright © 1991-2013 Unicode, Inc.
CLDR data files are interpreted according to the LDML specification (http://unicode.org/reports/tr35/)
For terms of use, see http://www.unicode.org/copyright.html
-->
<ldml>
    <identity>
        <version number="$Revision: 9287 $"/>
        <generation date="$Date: 2013-08-28 21:32:04 -0500 (Wed, 28 Aug 2013) $"/>
        <language type="ar"/>
        <territory type="SA"/>
    </identity>
    <dates>
        <calendars>
            <calendar type="islamic">
                <dateTimeFormats>
                    <availableFormats>
                        <dateFormatItem id="Md" draft="contributed">M/d</dateFormatItem>
                        <dateFormatItem id="MEd" draft="contributed">E, M/d</dateFormatItem>
                        <dateFormatItem id="MMMd" draft="contributed">MMM d</dateFormatItem>
                        <dateFormatItem id="MMMEd" draft="contributed">E, MMM d</dateFormatItem>
                    </availableFormats>
                </dateTimeFormats>
            </calendar>
        </calendars>
    </dates>
    <numbers>
        <symbols numberSystem="latn">
            <decimal>.</decimal>
            <group>,</group>
            <list>;</list>
            <percentSign>%</percentSign>
            <plusSign>+</plusSign>
            <minusSign>-</minusSign>
            <exponential>E</exponential>
            <superscriptingExponent>×</superscriptingExponent>
            <perMille>‰</perMille>
            <infinity>∞</infinity>
            <nan>NaN</nan>
        </symbols>
        <decimalFormats numberSystem="latn">
            <decimalFormatLength>
                <decimalFormat>
                    <pattern>#,##0.###</pattern>
                </decimalFormat>
            </decimalFormatLength>
        </decimalFormats>
        <currencyFormats numberSystem="latn">
            <currencyFormatLength>
                <currencyFormat type="standard">
                    <pattern>¤#,##0.00</pattern>
                </currencyFormat>
                <currencyFormat type="accounting">
                    <pattern>¤#,##0.00;(¤#,##0.00)</pattern>
                </currencyFormat>
            </currencyFormatLength>
            <unitPattern count="one">{0} {1}</unitPattern>
            <unitPattern count="other">{0} {1}</unitPattern>
        </currencyFormats>
        <currencies>
            <currency type="USD">
                <displayName>US Dollar</displayName>
                <displayName count="one">US dollar</displayName>
                <displayName count="other">US dollars</displayName>
                <symbol>$</symbol>
            </currency>
        </currencies>
    </numbers>
</ldml>
```

**Comment by sumeetmobiwebtech** [comment]
@magento-engcom-team 
"Currency symbol appear on arabic store view" - Is this issue resolved or still pending ?

**Comment by ashvinim0003** [comment]
Hi @sumeetmobiwebtech 

Copy the currency and numbers block from en.xml and paste it into the ar_SA.xml
it will work.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mattsulony** [comment]
Reproduced on 2.3.xReproduced on 2.3.x

**Comment by RonakParmar** [comment]
Hello there,
Is there any solution for this issue? I am using Magento 2.3 and able to reproduce this issue.

**Comment by codetheatres** [comment]
Hi, I am using Magento 2.3 and I can see its working. I have one website and 2 stores viz main store, arab store and two store view viz main website store view and arab store view. I have selected locale as Arabic Kuwait. I can see the below result in frontend.
![AS](https://user-images.githubusercontent.com/46475317/56214567-c42c6b00-607b-11e9-9c4c-51140c1f8ccc.png)

**Comment by codetheatres** [comment]
Hi, I am using Magento 2.3 and I can see its working. I have one website and 2 stores viz main store, arab store and two store view viz main website store view and arab store view. I have selected locale as Arabic Kuwait. I can see the below result in frontend.
![AS](https://user-images.githubusercontent.com/46475317/56214745-11a8d800-607c-11e9-89e0-395a526400de.png)

**Comment by PascalBrouwers** [comment]
Can the CLDR not be updated for the zendframework1 library?

**Comment by ghost** [comment]
@magento i am working on it.

**Comment by ghost** [comment]
Remove numbers tag and its child tags from /lib/Zend/Locale/Data/ar_SA.xml
it will show ” ر.س.” as default currency symbol for Saudi riyal.
