### ISSUE TITLE
Updating category with /rest/V1/categories/ID does not update level

### ISSUE THREAD

**Issue by Dieudon** [magento/magento2#13211]
When using the Magento 2 rest API for updating categories it will update all options except the **level** of the category.

### Preconditions
Magento version 2.1.10
PHP 7.0.22
Mysql 5.7.20

### Steps to reproduce
Perform call to  **/rest/V1/categories/8893** where 8893 is the ID of the category we want to update.
With in the body the following data where both **level** and **position** have been changed:

```
{
 "category": {
   "id": 8893,
   "level": 3,
   "position": 5
   }
}
```

### Expected result
We expect the following repsonse from the call:
```
{
   "id": 8893,
   "parent_id": 2,
   "name": "TOOLS",
   "is_active": true,
   "position": 5,
   "level": 3,
   "children": ....
```

### Actual result
We got the following repsonse from the call:
```
{
   "id": 8893,
   "parent_id": 2,
   "name": "TOOLS",
   "is_active": true,
   "position": 5,
   "level": 2,
   "children": ....
```
So the position of the category has changed but the level stays the same.

**Comment by magento-engcom-team** [comment]
@Dieudon, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by routbiplab** [comment]
Hello @Dieudon,

The level will remain the same until and unless you add a new subcategory. Hence to move any category under any category please follow the below the request body:
`{
 "category": {
 	"parent_id":11,
   "id": 41,
   "path": "1/2/11/41",
   "level": 3,
   "position": 2
   }
}`
