### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Alessandro77** [magento/magento2#1321]
In Frontend and Admin pages. Version beta11.
requirejs-config.js:356  // Uncaught ReferenceError: require is not defined

**Comment by vpelipenko** [comment]
@Alessandro77, do you get this error every time when try to open some pages?

**Comment by Alessandro77** [comment]
Yes, admin and frontend, but only in xampp.
Using LAMP on ubuntu, it's all right.

**Comment by vpelipenko** [comment]
@Alessandro77, could you provide a content of requirejs-config.js file, or even a few lines of code around 356 line.

**Comment by Alessandro77** [comment]
sure - Line 351 / 378

------------------------------
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

var config = {
    map: {
        '*': {
            recentlyViewedProducts: 'Magento_Reports/js/recently-viewed'
        }
    }
};
require.config(config);
})();
(function() {
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

var config = {
    map: {
        '*': {
            giftOptions:    'Magento_GiftMessage/gift-options',
            extraOptions:   'Magento_GiftMessage/extra-options'
        }
    }
};
-----------------------

file located in /pub/static/_requirejs/frontend/Magento/luma/en_US/requirejs-config.js

**Comment by anton-huz** [comment]
Existence of file `requirejs-config.js` under `/pub/static/_requirejs/...` is expected behavior.
- [ ] Also you should have in markup something like:

``` html
<script  type="text/javascript"  src="http:// ... /static/frontend/Magento/luma/en_US/requirejs/require.js"></script>
<script  type="text/javascript"  src="http:// ... /static/_requirejs/frontend/Magento/luma/en_US/requirejs-config.js"></script>
```
- [ ] Also both files should be accessible when you directly request them in browser.

If both checkboxes could be checked on your environment - you will have expected behavior without JavaScript error _`require is not defined`_ . Otherwise please post issue what you have.

**Comment by Alessandro77** [comment]
Yes, but folder /pub/static/frontend/Magento/luma/en_US/requirejs/  is empty

**Comment by guz-anton** [comment]
> folder /pub/static/frontend/Magento/luma/en_US/requirejs/ is empty

Amm... It should contain files from `libv/web/requirejs` folder. Or links on it. So:
 - Is there any other file or link under `folder /pub/static/frontend/Magento/luma/en_US/` ?
 - Do you setup any custom `MAGE_MODE` variable?
 - Does you server have free space on partition where Magento installed?
 - Does whole path `pub/static/frontend/Magento/luma/en_US/requirejs/` writable for web-server user?

**Comment by Alessandro77** [comment]
No files, only empty dirs

--css
--fonts
³   --opensans
³       --bold
³       --light
³       --regular
³       --semibold
--images
--jquery
--js
--mage
--Magento_Theme
--requirejs

-----------------------------------
no
yes
yes

Same problem by reinstalling everything, but only in XAMPP . Using Ubuntu LAMP all it's ok !

**Comment by vpelipenko** [comment]
@Alessandro77, probably it is something with Apache/mod_rewrite configuration in XAMPP. I also use it locally on Windows and it is work for me with latest Magento. As possible way you can try to compare Apace configuration in XAMPP and on Ubuntu and analyze differences.

**Comment by Alessandro77** [comment]
Thanks vpelipenko, I have not customized any files in Xampp , perhaps there is a link to the best practice for magento setup?

**Comment by vpelipenko** [comment]
@Alessandro77, you can find more information here http://devdocs.magento.com/guides/v1.0/install-gde/system-requirements.html.

**Comment by kasalgado** [comment]
Hello,
I know, it is a old post but I experience same problem after to install Magento 2.3. Folder /pub/static/frontend/Magento/luma/en_US/requirejs/ is empty.  As before the problem happens only with xampp on Windows 10. Vs. 2.2 works fine. Was found a solution for this problem?
Regards.

**Comment by DanielRuf** [comment]
Windows is not officially supported. Please open a new issue with all relevant details.

**Comment by kasalgado** [comment]
I tried following solution. It seems to work:
https://stackoverflow.com/questions/53551878/blank-admin-page-on-magento-2-3-0-ce-in-localhost

**Comment by kschipulring** [comment]
> Windows is not officially supported. Please open a new issue with all relevant details.

Wow!  This is extremely unprofessional on the part of the Magento development team.  LIKE 98% of developers do local development on their WINDOWS computers / laptops with localhost, just to see basic changes.

This is outrageous.  Virtually every other known PHP application works right out of the box on a Windows box, including old Magento.

Every day, I develop for a PHP application based on Laravel which works on Nginx and Apache, just fine.

Well I guess that Magento (really, Adobe) wants to keep losing more business to Shopify and WooCommerce (which installs fast and works anyplace).
