### ISSUE TITLE
Full page cache problem in magento 2

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#13219]
https://github.com/magento/magento2/issues/6624
https://github.com/magento/magento2/issues/6392

As the two above told issues are closed that's why I am posting this .

I am using magento 2.1.8. I my custom theme app\design\frontend\Sample\theme-frontend-shop\Magento_Catalog\templates\product\view\form.phtml I have  done

`
$quoteId = $objectManager->get('Magento\Checkout\Model\Session')->getQuoteId(); 
$currentItemCount=0;
if(!empty($quoteId)){   
	$cartItems = $objectManager->get('\Magento\Checkout\Model\Session')->getQuote()->getAllVisibleItems();
	$itemsIds = array();
	foreach ($cartItems as $cartItem) {
	    $itemsIds[] = $cartItem->getProduct()->getId();
	}

    $currentItemCount = count($itemsIds);

}

echo  $currentItemCount;
`

and in my app\design\frontend\Sample\theme-frontend-shop\Magento_Catalog\layout\catalog_product_view.xml I have added 
`<referenceBlock name="product.info.addtocart" class="Magento\Checkout\Block\Cart" before="-" template="Blumeidealnew_shop::product/view/form.phtml" cacheable="false" />`

But this is not working properly when full page cache is enabled.

Need help to fix this issue.

**Comment by OZZlE** [comment]
You should never user ObjectManager in M2 unless you are writing a Symfany a lá `php bin/magento` script..

**Comment by BabliDey** [comment]
Then how can I get cart item count from a custom theme html page?

**Comment by OZZlE** [comment]
You could use a Controller and put the class in the constructor, or if it's a normal theme just in the block class contructor you are using

**Comment by magento-engcom-team** [comment]
@BabliDey please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
