### ISSUE TITLE
di:compile causes Fatal error for magento1 classes

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#1322]
I have modules with classes for magento1 and 2, 
in last beta release they cause the following error during `setup:di:compile`

```
Fatal error: Class 'Mage_Core_Helper_Abstract' not found in /srv/magento_beta_full/app/code/Cotya/Elasticgento/Model/m1/Data.php on line 38
```

It did work before thx to this patch: https://github.com/magento/magento2/pull/986
and seemed to stop after the move to the new magento cli script.

**Comment by mazhalai** [comment]
@Flyingmana the old `compiler.php` is not the same as `setup:di:compile`. Please try ` setup:di:compile-multi-tenant`

**Comment by vpelipenko** [comment]
@Flyingmana, did you try solution provided by @mazhalai?
