### ISSUE TITLE
Magento\Sales\Api\Data\OrderPaymentInterface is missing a setter for 'additional_information' data

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#13222]
When trying to run a payed order through a \Magento\Framework\Webapi\ServiceOutputProcessor it will fail because the 'additional_information' data has no corresponding setter defined in the interface.

### Preconditions
1. PHP7
2. CE 2.2.2

### Steps to reproduce
1. Create a payed order
2. Try to process the order with a \Magento\Framework\Webapi\ServiceOutputProcessor: 

```php
$serviceOutputProcessor->process(
            $order,
            'Magento\Sales\Api\OrderRepositoryInterface',
            'get'
        );
```

### Expected result
1. You get don't get any errors

### Actual result
1. Exception is thrown:

`Property "AdditionalInformation" does not have corresponding setter in class "Magento\Sales\Api\Data\OrderPaymentInterface". `

The ServiceOutputProcessor tries to serialize the order object based on the (api) interfaces. When it reaches the serialization of the Payment object in the order the processor will fail when the object has data for 'additional_information' (normally this contains the payment method name).

The Magento\Sales\Api\Data\OrderPaymentInterface should contain a setAdditionalInformation function definition which will be implemented by the setAdditionalInformation function defined in Magento\Payment\Model\InfoInterface

**Comment by koenner01** [comment]
The \Magento\Sales\Model\Order\Payment\Info class however does have that setter implemented (and the order payment extends this class)

**Comment by magento-engcom-team** [comment]
@koenner01, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@koenner01, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by hostep** [comment]
A new attempt at fixing this is happening in https://github.com/magento/magento2/pull/26748
