### ISSUE TITLE
City is required by FedEx Freight in Cart Estimation

### ISSUE THREAD

**Issue by Mistrb** [magento/magento2#13239]
When using FedEx freight, it is required to pass the City in addition to State and zipcode in order to get a freight estimate. M1 supported this by having a "City" field in the "ESTIMATE SHIPPING AND TAX" area in the cart. This field is no longer available.  

### Preconditions
Magento 2.1.10

### Expected result
A shipping quote from Fedex

### Actual result
Carrier requires City, which is missing.

**Comment by magento-engcom-team** [comment]
@Mistrb  thank you for your report
Please tell us which country, city and zip code is used in your case.

**Comment by Mistrb** [comment]
USA
Pennsylvania
18914

or any USA state and zip for that matter. Fedex requires City to provide a Freight quote in the USA.

**Comment by magento-engcom-team** [comment]
Hello @Mistrb. As we see City is not required here. Zip code is enough. (see our screen shot). So please tell us if we are wrong and if so then where. Thank You.
![fedex](https://user-images.githubusercontent.com/31669971/35622723-8541786c-0691-11e8-8037-bf54563f39cf.png)
