### ISSUE TITLE
[2.3.x][REST] required configurable attributes should not be required value in configurable product

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#13234]
### Preconditions
1. Magento 2.3.x CE & EE 
1. API Integration in place

### Steps to reproduce
1. Create a custom required, global product attribute that can be used for configurations (e.g. select)
1. Create one or more simple products with different values for the attribute
1. Create a configurable product over the rest api and leave the required attribute empty
(I think the API point is only important for reproducing since creating the product in the backend would most likely lead to have the default value / first value in select for the attribute submitted)

### Expected result
1. The created attribute should not be required for the configurable product when it is used for configurations

### Actual result
1. We get "message": "The \"test\" attribute value is empty. Set the attribute and try again."
With empty value for attribute:
!https://user-images.githubusercontent.com/51680850/65122539-e7c45a80-d9f9-11e9-90ad-5045f9b9b177.png!
Without attribute(same response):
!https://user-images.githubusercontent.com/51680850/65122708-4f7aa580-d9fa-11e9-8dca-03c21ec9d8f0.png!

Current Workaround is to set the attribute to not required

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/2-2-2-REST-required-configurable-attributes-should-not-be/idi-p/86410).

**Comment by davidverholen** [comment]
@serhii-balko @piotrekkaminski  may I ask why this was marked as a feature request?

it is clearly a bug since you have to set a value for a required attribute on a configurable product when this attribute is used for configurations, which does not make any sense. the configurable attributes should be excluded from validation for configurable products (or even better, they should be forced to be empty)

**Comment by davidverholen** [comment]
hello anyone? @magento-engcom-team maybe? Waiting it out is not a solution :P

**Comment by nadeefit6** [comment]
Can i pick this issue?

**Comment by social-assassin** [comment]
@piotrekkaminski Why was this closed? Not a feature request, I'm having the same issue.

**Comment by NiklasBr** [comment]
@piotrekkaminski this is obviously not a feature request.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20223` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
