### ISSUE TITLE
Cart Does not contain item

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#13241]
### Preconditions

1. Installed magento 2.1.8 community version.
2. installed some 3rd party modules like custom checkout field, Heidelpay, multiflatrate, Google analytics, Blog and trusted shop.
3. Installed custom theme for designing

### Steps to reproduce

1. Adding a product in cart and do not checkout
2. After a long time when cart is empty trying to add a product in my cart again
3. 

### Expected result

1.  Success message for adding product in cart

### Actual result

1. Product is adding to cart but not getting product successfully added to cart rather an error message cart 312 does not contain item 627
2. [Screenshot, logs]
<img src="https://user-images.githubusercontent.com/24405051/35085122-30686966-fc4d-11e7-88f7-564ad2dfe867.png"/>

Probably this is coming due to cache. But do not know how to fix this.

**Comment by magento-engcom-team** [comment]
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).  We will need some steps to reproduce in order for us to help you with that problem, thank you.

**Comment by BabliDey** [comment]
Hello @magento-engcom-team I have updated my post in proper way. Have a look now.

**Comment by magento-engcom-team** [comment]
@BabliDey Thanks for your report, unfortunately, we can't reproduce the issue with a clean instance of Magento. We would recommend you trying to clear your cache, the problem might be there, but it looks like it's a 3'rd party code that is a problem, try to figure out which one of them causing the problem, by running one of them at a time.  If the problem won't be solved,  please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Thank you

**Comment by magento-engcom-team** [comment]
@BabliDey, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
