### ISSUE TITLE
Magento 2 Product Collection API with price filter

### ISSUE THREAD

**Issue by avinashsamala** [magento/magento2#13249]
Hi Team,

I am getting issue with Magento 2 Rest API for product collection with price fileter. Please check below link,

https://magento.stackexchange.com/questions/204704/magento-2-filter-products-by-price-from-rest-api

thanks,

**Comment by magento-engcom-team** [comment]
@avinashsamala  thank you for your report,
Please tell us the exact version you use.

**Comment by gometoo** [comment]
@magento-engcom-team thanks for replay.

We are using Magento 2.2.1 Version

thanks,

**Comment by avinashsamala** [comment]
@magento-engcom-team thanks for replay.
 
we are using Magento 2.2.1 version

thanks,

**Comment by magento-engcom-team** [comment]
@avinashsamala, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@avinashsamala, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
