### ISSUE TITLE
installation requiments

### ISSUE THREAD

**Issue by Chriscxa** [magento/magento2#1325]
Everytime composer tells me my php is outdated. 5.4.39. 
But i use 5.5.23 ???

**Comment by Chriscxa** [comment]
changed in composer.json to my version. and before webinstall in composer.lock too
After that all works great

**Comment by buskamuza** [comment]
@Chriscxa , are you sure that you have only one PHP (5.5.23) installed?
Does "php -v" show "5.5.23"?
It may be that you have multiple versions installed and Composer somehow uses wrong one. It's better to fix the environment to be sure that Composer also checks all other env requirements (e.g., required php extensions).
