### ISSUE TITLE
Page layout doesn't override layout chosen inside admin

### ISSUE THREAD

**Issue by minimit** [magento/magento2#13256]
When you set a page layout in the cms pages like cms_index_index.xml or cms_page_view.xml, it doesn't override the one choosen inside magento2 admin.

Can we have a way to force this layout inside the xml?

### Preconditions
1. Magento version: 2.2

### Steps to reproduce
Inside Magento_Theme/layout/cms_index_index.xml
```
<?xml version="1.0"?>
<!--
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="fullcolumn" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">

    <body>
        <referenceContainer name="main">
            <block class="Magento\Framework\View\Element\Template" name="cms.index" template="Magento_Theme::html/cms/index.phtml" after="-"/>
        </referenceContainer>
    </body>

</page>
```

### Expected result
`layout="fullcolumn"` should override the layout chosen inside magento2 admin.

### Actual result
Layout chosen inside magento2 admin gets applied.

**Comment by magento-engcom-team** [comment]
Hi @minimit 
This is not a bug.
The layout  CMS page can be declared in files CMS page Design>Layout.
You can declare new layout in magento2/app/code/Magento/Theme/view/frontend/layouts.xml and than select it in CMS page Design>Layout

**Comment by magento-engcom-team** [comment]
@minimit, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by minimit** [comment]
I think it would be better to give control over the layout to the developers if they specify a layout in the page, otherwise the layout in the page becomes irrilevant (Design>Layout get precedence and it's always something).
