### ISSUE TITLE
Special price magento2

### ISSUE THREAD

**Issue by Golfu68** [magento/magento2#13259]
### Preconditions

1. 
2. 

### Steps to reproduce

1. when a article have differend sizes, the special price shows onely when you choos a size?
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]
![driver 2](https://user-images.githubusercontent.com/17296952/35098600-2a5857d6-fc55-11e7-800c-6e77b8fdbbab.jpg)

![driver 1](https://user-images.githubusercontent.com/17296952/35098597-27a6b30c-fc55-11e7-9893-fb62ad480b1c.jpg)

**Comment by magento-engcom-team** [comment]
@Golfu68 Thanks for your report.  In order for us to reproduce this issue, please provide more details or steps. Thank you

**Comment by Golfu68** [comment]
Shoe
Size 40-41-42-43
Pirce 100.00
Special price 89.00
As above the special price is onel viewed when you select a size

**Comment by Golfu68** [comment]
Sorry
The normal price is not shows up until you select a size.

**Comment by magento-engcom-team** [comment]
@Golfu68, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia

**Comment by sanjay-wagento** [comment]
@magento-engcom-team , I reviewed in latest branch 2.2-develop and by default configurable product display As low as $30.00 ($30.00 is special price).
So I think it is working correctly. Let me know if you want to change the behavior of the configurable product.

**Comment by magento-engcom-team** [comment]
@sanjay-wagento Thank you for researching. Indeed, it seems to be a correct behavior.
We are closing the ticket now.
