### ISSUE TITLE
Magento SalesArchive can not finish the recurring upgrade script when there are many rows in the archives

### ISSUE THREAD

**Issue by linden2015** [magento/magento2#13265]
### Preconditions
1. OS: Ubuntu 16.04.3 LTS 64-bit
2. PHP: 7.0.22-0
3. MySQL: 14.14 Distrib 5.7.20
4. Magento: 2.2.2
5. Magento configuration:
```
Stores > Configuration > Sales > Orders, Invoices, Shipments, Credit Memos Archiving
    * Enable archiving: yes
    * Archive Orders Purchased: 180
    * Order Statuses to be Archived:
        * Pending
	* Partially Shipped
	* Complete
	* Closed
	* Cancelled
	* Processing Failed (Docdata)
	* On Hold
```
6. Database:
```
sales_creditmemo_grid
    0 rows
sales_invoice_grid
    0 rows
sales_order_grid
    1 row
sales_shipment_grid
    0 rows

magento_sales_creditmemo_grid_archive
    9752 rows
magento_sales_invoice_grid_archive
    439497 rows
magento_sales_order_grid_archive
    729561 rows
magento_sales_shipment_grid_archive
    455930 rows
```

### Steps to reproduce
1. Run `php bin/magento setup:upgrade`

### Expected result
1. Completed upgrade

### Actual result
1. Upgrade is not completed
2. Error:
```
Module 'Magento_SalesArchive':
Running schema recurring...Warning: PDOStatement::execute(): MySQL server has gone away in /var/www/html/client-1/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228
```

**Comment by magento-engcom-team** [comment]
@linden2015, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
