### ISSUE TITLE
After updating products from code, thumbnails are not showing in catalog and on backend

### ISSUE THREAD

**Issue by erikkubica** [magento/magento2#13262]
### Preconditions
1. M2 v2.2.1
2. Mysql 5.7
3. PHP 7
4. Ubuntu

### Steps to reproduce
1. Updated product stock and price using this code: https://pastebin.com/eytSENau
2. Cleared cache, reindexed
3. Thumbnails missing in product listing (category page) and in admin area too. Images on product_view page are visible and correct, images in product edit page in admin are also visible and correct.
4. Tried to re-size images from command line, reindex, refresh cache.
5. Still not visible

### Expected result
1. Images should be generated / loaded / recognized

### Actual result
1. Thumbnails on product listings are placeholders.

Color swatches and other images works, just the thumbnails not on product listings.

Any idea what can be the issue? It worked until i did not updated the products form code.

**Comment by magento-engcom-team** [comment]
@erikkubica The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment]
@erikkubica, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by erikkubica** [comment]
@magento-engcom-team Hi, i would like. But since after

```
$productRepository = $objectManager->get( '\Magento\Catalog\Model\ProductRepository' );
$product           = $productRepository->getById( $product->getId() );

$product->setName( $item->Nazov->__toString() );
$product->setPrice( floatval( $item->KonecnaCena->__toString() ) );
$product->setSpecialPrice(null); // Reset special price

$product->setStockData(['qty' => $_stock_qty, 'is_in_stock' => true]);
$product->setQuantityAndStockStatus(['qty' => $_stock_qty, 'is_in_stock' => true]);

$productRepository->save($product);
```

Thumbnails stop working, it seems like a magento bug since i am not even updating image related data..... which should be here. If it's correct Magento behavior, then it should be documented somewhere. But I was unable to find any "working" solution, and at the most of the solutions, it was a confirmed bug in M2 v2.1.6

**Comment by magento-engcom-team** [comment]
@erikkubica, thanks for clarifying that. 
We've acknowledged the issue and added to our backlog.

**Comment by erikkubica** [comment]
@magento-engcom-team Seem like using $product->save(); instead of $productRepository->save($product); does not cause the issue.

**Comment by toddhainsworth** [comment]
Hi @magento-engcom-team @erikkubica,

Do either of you have an update on a fix to the ProductRepository? I believe we're experiencing the same issue after an upgrade to 2.2.3 and are currently trying to debug it.

Thanks

**Comment by erikkubica** [comment]
Hey @toddhainsworth , **IF** I remember correctly the problem was with store_id of thumbnails after changing single store to multi store or vice versa. The same problem happened with setting tax_class from import. for some reason magento struggles with saving data to the correct store in some cases. But i am not 100% sure

**Comment by toddhainsworth** [comment]
Thanks @erikkubica - hmm sounds plausible, appreciate the details! :smile: 
I'll provide some more information if I find anything worthwhile :hand:

**Comment by peterlembke** [comment]
Hi @erikkubica , do you have the media attributes intact? If not then this can help:
```
    protected function saveProduct($product, $setMediaGalleryToNull = true)
    {
        if ($setMediaGalleryToNull) {
            $product->setData('media_gallery', null); // Then we do not lose the media attributes,
            // bug https://github.com/magento/magento2/issues/10687
        }

        $this->_productRepository->save($product);
    }
```

**Comment by engcom-Delta** [comment]
@erikkubica @toddhainsworth  Unfortunately, I am not able to reproduce issue by steps you described on clean 2.4-develop
**Steps to reproduce:**
```
        $productRepository = ObjectManager::getInstance()->get(ProductRepository::class);
        $product           = $productRepository->getById( '1' );
        $product->setName('Test Prod');
        $product->setPrice( '500' );
        $product->setSpecialPrice(null); // Reset special price
        $productRepository->save($product);    
```
**Actual result:**
:heavy_check_mark: Image roles is not changed after updating products from code

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
