### ISSUE TITLE
Missing dependency in Catalog Module

### ISSUE THREAD

**Issue by fooman** [magento/magento2#13271]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. notice the use of \Symfony\Component\Console\Command\Command under app/code/Magento/Catalog/Console/Command/

### Expected result

1. app/code/Magento/Catalog/composer.json should include symfony/console

### Actual result

1. Symfony Console is stated in the require section

**Comment by orlangur** [comment]
I'm not aware of any modules not dependent on Magento Framework at the moment, so, it's enough to have such dependency specified in https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/composer.json.

**Comment by fooman** [comment]
@orlangur you are right the current 2.2 framework has it so it's okay
