### ISSUE TITLE
Unable to Reset Password on Magento.com

### ISSUE THREAD

**Issue by sreesoftwares** [magento/magento2#13277]
Dear Magento Developer,

I had to try Reset Megento Account Password. But Automatically Expired Link After press submit Button or Enter Key. And Account Blocked after some attempt so Kindly Fix Error.

Note: My Login Mail is Gmail
![reset-password-error](https://user-images.githubusercontent.com/20135219/35152742-966779b2-fd49-11e7-8d18-d5890161550d.png)

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by ishakhsuvarov** [comment]
Hi @sreethamil 
This repository is intended for the Magento 2 CE technical issues only and does not relate to the `magento.com` and it's services.
Please contact `magento.com` support directly.

**Comment by sreesoftwares** [comment]
I had to raise the complaint at Magento Support team via Contact form but But not reply or error fix.

**Comment by ishakhsuvarov** [comment]
@sreethamil Unfortunately there are no account management services associated with Github, therefore we can not help you with this problem.
