### ISSUE TITLE
Magento 2 Module : Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by yogeshsyscraft** [magento/magento2#13273]
### Preconditions

1.  Create New Custom Extension .
2.   Upload Extension for Technical Review on Market Place . 

### Steps to reproduce

1.   Complete Business Review 
2.  After That  Submit for Technical Review 

### Expected result

1.  Extension should be approve in technical review 

### Actual result

> Environment: Operating System - Centos 7, PHP Version - 5.6.31, Magento Platform - 2.0.17 CE
Command:
composer require syscraftonline/module-themesettings:100.0.3'
Installation issue:
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for syscraftonline/module-themesettings 100.0.3 -> satisfiable by syscraftonline/module-themesettings[100.0.3].
- Conclusion: remove magento/framework 100.0.19
- Conclusion: don't install magento/framework 100.0.19
- syscraftonline/module-themesettings 100.0.3 requires magento/framework 100.1.* -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 100.1.10, 100.1.11].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc1].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc2].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc3].
- Can only install one of: magento/framework[100.0.19, 100.1.0].
- Can only install one of: magento/framework[100.0.19, 100.1.1].
- Can only install one of: magento/framework[100.0.19, 100.1.2].
- Can only install one of: magento/framework[100.0.19, 100.1.3].
- Can only install one of: magento/framework[100.0.19, 100.1.4].
- Can only install one of: magento/framework[100.0.19, 100.1.5].
- Can only install one of: magento/framework[100.0.19, 100.1.6].
- Can only install one of: magento/framework[100.0.19, 100.1.7].
- Can only install one of: magento/framework[100.0.19, 100.1.8].
- Can only install one of: magento/framework[100.0.19, 100.1.9].
- Can only install one of: magento/framework[100.0.19, 100.1.10].
- Can only install one of: magento/framework[100.0.19, 100.1.11].
- Installation request for magento/framework (locked at 100.0.19) -> satisfiable by magento/framework[100.0.19].

Installation failed, reverting ./composer.json to its original content.
[Pipeline] }
[Pipeline] // stage
[Pipeline] sh
[DockerOperationsPHP56Magento20CE] Running shell script
+ echo Failure
Failure   
Show less

Environment: Operating System - Centos 7, PHP Version - 7.0.21, Magento Platform - 2.0.17 CE Varnish, Sampla Data
Command:
composer require syscraftonline/module-themesettings:100.0.3'
Installation issue:
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for syscraftonline/module-themesettings 100.0.3 -> satisfiable by syscraftonline/module-themesettings[100.0.3].
- Conclusion: remove magento/framework 100.0.19
- Conclusion: don't install magento/framework 100.0.19
- syscraftonline/module-themesettings 100.0.3 requires magento/framework 100.1.* -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 100.1.10, 100.1.11].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc1].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc2].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc3].
- Can only install one of: magento/framework[100.0.19, 100.1.0].
- Can only install one of: magento/framework[100.0.19, 100.1.1].
- Can only install one of: magento/framework[100.0.19, 100.1.2].
- Can only install one of: magento/framework[100.0.19, 100.1.3].
- Can only install one of: magento/framework[100.0.19, 100.1.4].
- Can only install one of: magento/framework[100.0.19, 100.1.5].
- Can only install one of: magento/framework[100.0.19, 100.1.6].
- Can only install one of: magento/framework[100.0.19, 100.1.7].
- Can only install one of: magento/framework[100.0.19, 100.1.8].
- Can only install one of: magento/framework[100.0.19, 100.1.9].
- Can only install one of: magento/framework[100.0.19, 100.1.10].
- Can only install one of: magento/framework[100.0.19, 100.1.11].
- Installation request for magento/framework (locked at 100.0.19) -> satisfiable by magento/framework[100.0.19].

Installation failed, reverting ./composer.json to its original content.
[Pipeline] }
[Pipeline] // stage
[Pipeline] sh
[DockerOperationsPHP70Magento20CEVarnish] Running shell script
+ echo Failure
Failure   
Show less

Environment: Operating System - Centos 7, PHP Version - 5.5.38, Magento Platform - 2.0.17 CE
Command:
composer require syscraftonline/module-themesettings:100.0.3'
Installation issue:
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- magento/framework 100.1.0-rc3 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (5.5.38) does not satisfy that requirement.
- Installation request for syscraftonline/module-themesettings 100.0.3 -> satisfiable by syscraftonline/module-themesettings[100.0.3].
- Conclusion: remove magento/framework 100.0.19
- Conclusion: don't install magento/framework 100.0.19
- syscraftonline/module-themesettings 100.0.3 requires magento/framework 100.1.* -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 100.1.10, 100.1.11].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc1].
- Can only install one of: magento/framework[100.0.19, 100.1.0-rc2].
- Installation request for magento/framework (locked at 100.0.19) -> satisfiable by magento/framework[100.0.19].

Installation failed, reverting ./composer.json to its original content.
[Pipeline] }
[Pipeline] // stage
[Pipeline] sh
[DockerOperationsPHP55Magento20CE] Running shell script
+ echo Failure
Failure   
Show less

Environment: Operating System - , PHP Version - , Magento Platform -

**Comment by magento-engcom-team** [comment]
@yogeshsyscraft, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@yogeshsyscraft, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
