### ISSUE TITLE
Catalog Search not searching based on Full text base. ie. it doesn't give exact result on searching product name 

### ISSUE THREAD

**Issue by priti-rathee** [magento/magento2#13275]
### Preconditions

1. magento version 2.2.2
2. php version 7.0.24
3. mysql 5.7

### Steps to reproduce

1. Enter product name in top search bar and search
Extra info:-
1. Dropdown show correct count for options.
 2. Select exact product name(its count is showing 1 in drop down) and search.

### Expected result

1. Product with searched product name only should appear. 

### Actual result

1. many other product appears with the searched product.

![screenshot from 2018-01-19 18-19-26](https://user-images.githubusercontent.com/33680940/35151727-77ad65c6-fd45-11e7-906a-c46da71054c1.png)
![screenshot from 2018-01-19 18-18-54](https://user-images.githubusercontent.com/33680940/35151731-7b334c2e-fd45-11e7-91e3-833583b7b1ac.png)

 [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@priti-rathee  thank you for your report,
This is an expected Magento behavior. The search result will include all the products which names contain at least one of the words belonging to the search string.
If you want to achieve another search result you have to allow some other search engine like f. e. Elastic Search or Solr.

**Comment by magento-engcom-team** [comment]
@priti-rathee, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
