### ISSUE TITLE
Cannot order email

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#13276]
Send Email not working from order view.

**Preconditions**
1. PHP 7.0.22
2. Magento 2.1.10

**Steps to reproduce**
1. Place an order with one bundle and one configurable product
2. Go to back-end, view details of newly created order
3. Click on **Send Email**

**Expected result**
1. Order email should be sent

**Actual result**
1. Broken page is rendered and the error below is thrown in error_log file

[Fri Jan 19 13:16:19.661484 2018] [proxy_fcgi:error] [pid 12612] [client 178.149.168.202:36168] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Bundle\\Model\\Product\\Type::getConfigurableAttributeCollection() in /var/www/vhosts/host/httpdocs/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:52\nStack trace:\n#0 /var/www/vhosts/host/httpdocs/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 /var/www/vhosts/host/httpdocs/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\\ConfigurableProduct\\Model\\Product\\ReadHandler->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#2 /var/www/vhosts/host/httpdocs/vendor/magento/framework/EntityManager/Operation/Read.php(117): Magento\\Framework\\EntityManager\\Operation\\Read\\ReadExtensions->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor...\n', referer: https://www.host.com/admin/sales/order/view/order_id/84657/key/62f556f7b1bbd4b15a382dfcde253f771a0c81dc95cd5e9e15c47695afe5d8f1/

**Comment by magento-engcom-team** [comment]
@kerlama, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by dtfdigital** [comment]
Note we have a similar issue with the same method when attempting to ship certain orders.

[Wed Oct 17 09:24:52.370927 2018] [proxy_fcgi:error] [pid 9251] [client 127.0.0.1:37728] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\Product\\Type\\Simple\\Interceptor::getConfigurableAttributeCollection() in /home/public_html/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:52\nStack trace:\n#0 /home/public_html/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 /home/public_html/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\\ConfigurableProduct\\Model\\Product\\ReadHandler->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#2 /home/public_html/vendor/magento/framework/EntityManager/Operation/Read.php(112): Magento\\Framework\\EntityManager\\Operation\\Read\\ReadExtensions->execute(Object(M...\n', referer: https://host.co.uk/adminurl/admin/order_shipment/new/order_id/11111/

**Comment by arunelangovan** [comment]
@kerlama @dpdesignthatfits  Did you of you guys fixed the issue? I am having the same issue, but one change is i cannot go to cart or checkout at all.

**Comment by dtfdigital** [comment]
We have been unable to ship most of these orders, occasionally they will work when trying them again. If it helps, these products are from a Migration from 1.9. As best as I can tell, this happens on orders where the user has purchased a configurable product. From what I can see in the logic in the Loader.php the script is attempting to grab the selected configurable options, but in our case it's the simple product that has been loaded by magento, which then triggers the fatal error.  I'd considered writing some code to skip over this section, or grab the parent product and then run the magento code but was hoping for an official solution first.

**Comment by kerlama** [comment]
Hi,
yes, its a migration from m1.

I managed to overcome this by extending Magento\Catalog\Model\Product\Type\Simple

by adding dummy function

`public function getConfigurableAttributeCollection(\Magento\Catalog\Model\Product $product)
    {
        return [];
    }`

From that point, no errors were generated.

**Comment by dtfdigital** [comment]
@kerlama Do you have a copy of the module/extension you created that you could share? It would save us a ton of time.

**Comment by ankit-root** [comment]
I have faced the same issue on Magento 2.2.6 before we have migration from M1 to M2

When I added Configurable products on the cart then added Simple product on the cart will facing error 

 PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Bundle\\Model\\Product\\Type::getConfigurableAttributeCollection() in /var/www/html/magentothird/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:53\nStack trace:\n#0 /var/www/html/magentothird/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 /var/www/html/magentothird/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\\ConfigurableProduct\\Model\\Product\\ReadHandler->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#2 /var/www/html/magentothird/vendor/magento/framework/EntityManager/Operation/Read.php(112): Magento\\Framework\\EntityManager\\Operation\\Read\\ReadExtensions->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#3 /var/www/html/magentothird/vendor/magento/framework/EntityManager/EntityManager.php(70): Magento\\Framework\\Ent in /var/www/html/magentothird/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php on line 53, referer: http://ehp2.root.com/ehp-configurable.html

but when we added Simple product on the cart then added Configurable product on the cart after working fine
