### ISSUE TITLE
invalid website id error

### ISSUE THREAD

**Issue by Perfect-Web** [magento/magento2#1327]
I get this when i try to run the setup:upgrade command from cli
```php
  [Magento\Framework\Exception\State\InitException]  
  Invalid website id/code requested.

**Comment by buskamuza** [comment]
@Perfect-Web , do you have custom upgrades? Or does it happen during upgrade from one to another version of Magento? If yes, what are "from" and "to" versions?

**Comment by IonutPerfectWeb** [comment]
@buskamuza Happened when updating from beta8 - beta10.

**Comment by IonutPerfectWeb** [comment]
This was fixed by deleting inexistent websites from store_group table, now have the #1137 problem..

**Comment by vpelipenko** [comment]
@Perfect-Web, can we close this issue?

**Comment by IonutPerfectWeb** [comment]
@vpelipenko Yes, the solution was posted:) Thanks
