### ISSUE TITLE
Stock is not updating on placing order in multi-website store

### ISSUE THREAD

**Issue by 29sunil** [magento/magento2#13287]
Hello Concern Person,

Our Website is developed in magento 2.0.7 . We are running three websites i.e main Website, US Website and Canada website. 

We are facing problem in US Website and Canada website.
Problem: Quantity of product is not decreasing when user places order on US Website or Canada Website. Please provide us solution. 
We are in great pain.

**Comment by anant-svc** [comment]
@29sunil  You are using very old version of magento, so I suggest you to upgrade to latest Magento version.

**Comment by magento-engcom-team** [comment]
@29sunil  thank you for your report
Please try to reproduce this issue on the clean installation ver 2.2.2 and tell us the result.

**Comment by 29sunil** [comment]
Hello,

We have resolve it by removing  website id from stock.php file. 
File path :vendor/magento/module-catalog-inventory/Model/ResourceModel
We have removed website id from two functions in stock.php file
 public function lockProductsStock
public function correctItemsQty

We create new folder in app code with this module.
Thanks

**Comment by 29sunil** [comment]
Fresh magento install is not good solutions for us.

**Comment by 29sunil** [comment]
Hello,

We have resolve it by removing website id from stock.php file.
File path :vendor/magento/module-catalog-inventory/Model/ResourceModel
We have removed website id from two functions in stock.php file
public function lockProductsStock
public function correctItemsQty

We create new folder in app code with this module.
Thanks

**Comment by magento-engcom-team** [comment]
Thank You @29sunil. By fresh Magento install we did't mean that You have to start Your shop form zero. We meant that You try to install a clear instance and try to reproduce the issue on it with the similar sites structure and other data as You have on Your real instance and then tell us the result.  Your solution does not seem to be reliable for the future if You have changed the code. So if You are afraid to update Your shop to the latest version we recommend that You consult on Your solution with programmers on forums such as  [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2).

**Comment by magento-engcom-team** [comment]
@29sunil, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
