### ISSUE TITLE
Wrong Tier price on Category Page, Search Result Page and Product Listing Widget

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#13282]
### Preconditions

1. Magento version 2.2.2
2. PHP version 7.0.22
3. MySQL version 5.7.20
4. OS Ubuntu 16.04

### Steps to reproduce

1. Set "Display Product Prices In Catalog" to "Including Tax" in Stores->Settings->Configuration->Sales->Tax->"Price Display Settings".
2. Set "Catalog Prices" to "Excluding Tax" in Stores->Settings->Configuration->Sales->Tax->"Calculation Settings".
2. Set tier price for any product.
3. Set Product as "Taxable goods".
4. Set Tax Rule in such a way that tax will be apply and visible on Catalog pages.
5. Go to Category page, Search Result page or any page that contain Product Listing Widget.

### Expected result

1. "As low as" price on Category pages, Search Result pages and Product Listing Widget is the lowest from tier prices + tax.

### Actual result

1. "As low as" price on Category pages, Search Result page and Product Listing Widget is wrong.
For example : 
Tax rate is 10%.
Tier price set up in administrator panel is $30.
![admin_tier_price](https://user-images.githubusercontent.com/22025597/35160714-450da4f2-fd3e-11e7-8dda-9994b2cde44a.png)
"As low as" price with tax should be $33 but is $36.30.
![tier_price_category_page](https://user-images.githubusercontent.com/22025597/35160715-47f12694-fd3e-11e7-9b48-01e347070bc4.png)
2. On Product Details page tier prices are proper.
![tier_price_pdp](https://user-images.githubusercontent.com/22025597/35160758-663a4748-fd3e-11e7-8555-ba924a0f9356.png)

**Comment by magento-engcom-team** [comment]
@LordHansolo, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by zipnfc** [comment]
We have experienced this on 2.2.5 - is there any work around identified with this apart from not displaying prices including tax.

**Comment by Hoszi** [comment]
Is there any progress, any bugfix for this?

**Comment by Hoszi** [comment]
I think I found a solution:
in \Magento\Catalog\Pricing\Price\MinimalTierPriceCalculator

    public function getAmount(SaleableInterface $saleableItem)
    {
        $value = $this->getValue($saleableItem);
        return $value === null
            ? null
            : $this->calculator->getAmount($value, $saleableItem);
    }

Add 3rd parameter to $this->calculator->getAmount($value, $saleableItem, **['weee', 'weee_tax', 'tax']**)

**Comment by zipnfc** [comment]
That fix works for me - perfect - you are a genius! Hopefully this will end up in a next release as it seems quite a key fix to me if you are in a country with VAT and the fact that Google Merchant needs your price to include VAT.  Many thanks that is brilliant

**Comment by sanvarjat** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@sanvarjat thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Delta** [comment]
@LordHansolo @zipnfc  Thank you for your reports, I am not able to reproduce issue by steps you described on 2.4-develop
![image](https://user-images.githubusercontent.com/51681379/71615885-27374100-2bbc-11ea-81ac-b65b96234727.png)

![image](https://user-images.githubusercontent.com/51681379/71615889-2f8f7c00-2bbc-11ea-8fad-96337cab7312.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by zeshanrahman** [comment]
![image](https://user-images.githubusercontent.com/15862232/74422573-d54d3080-4e74-11ea-980f-3507c25d04e2.png)
magento 2 how can we show tier price with tax on listing page
