### ISSUE TITLE
Tmp images never cleaned

### ISSUE THREAD

**Issue by andrii-dymov** [magento/magento2#13289]
### Preconditions
Magento 2.2-develop

### Steps to reproduce
1. Edit category
2. Add category image
3. Change category image without saving the category
4. Save category

### Expected result
All temporary images should be removed from pub/media/catalog/tmp/category

### Actual result
Only last image is moved out from tmp, all previous unsaved images are kept in tmp forever

**Comment by andrii-dymov** [comment]
The solution might be to keep temporary file paths in the session and clean all them when session is ended.
For example:
Add new class with `addFile` and `clean` methods, inject it into `Backend/Model/Session/AdminConfig.php`.

  `addFile($session, $path)` - save full file path into the session
  `clean($session)` - delete all added files

Add `watchTmpFile` method to the `Backend\Model\Session`.
Use it whenever we want a file to be automatically removed after the session ends, i.e. in the `Catalog/Model/ImageUploader.php` when we create a temp file.
Call `clean` method in the session destroy method.

I'd make a pull request, but mentioned classes are marked as API and I'm not sure if it's OK to make such changes.

**Comment by orlangur** [comment]
Expected result is unreasonable.

Such operations can take pretty long time and thus should not be performed in synchronous mode, there is no suitable asynchronous mechanism currently where logic of images cleanup could be embedded. (as per discussion on one of the Magento meetups).

Thoughts? Cc: @maghamed

**Comment by andrii-dymov** [comment]
Proposed solution deletes only images, which were created during one user session. We can also remove from watching images, which where saved and moved to another folder. So there must not be a lot of files to delete at once. Afaik, there is only cron jobs for asynchronous things in the community Magento.

**Comment by vasilii-b** [comment]
Adding my 5 cents here.
Theoretically, right after you installed magento 2 (or migrate from magento 1) your `pub/media/catalog/tmp/category` is empty. And at the time you're reproducing steps described in the issue there can't be too  much files to affect the performance that much.
I also believe that there may be implemented a new CLI command to clean-up this folder.

What do you think about this idea ?

**Comment by andrii-dymov** [comment]
ImageUploader is convenient to use by third parties for uploading images to their folders. CLI must know somehow about all that files. My point is that all such files are created during the admin session and we can remember files, which must be deleted, and clean them later. There are usually zero to few files during one session, as they are created only if user changed his mind after he uploaded an image. And we don't need to scan folders, we have all full paths. Deleting them on session destroy is not a problem imho. Using CLI for this little problem is pretty awkward. Users must not care about tmp files.

**Comment by ishakhsuvarov** [comment]
> Deleting them on session destroy is not a problem imho.

I agree with @orlangur here, removal of images, specially when user changed his mind multiple time, can cause visible delays in the responsiveness, thus creating another problem.
My assumption would be that CLI shouldn't care too much about those images, granted that the most of directory contents is a result of an error.

**Comment by andrii-dymov** [comment]
Let's then make image component responsive for additional asynchronous request to delete old image when the new one is successfully uploaded. The request may be lost or never sent, but in normal conditions we'll keep tmp folders clean and expected result appears to be reasonable :)

**Comment by orlangur** [comment]
> My point is that all such files are created during the admin session and we can remember files, which must be deleted, and clean them later. 

This looks pretty unreliable. We must take into account that admin session may simply disappear at any moment.

So, any cleanup mechanism must be able to delete all orphaned images, not just ones introduced in scope of particular session.

My main concern here is - what is a real-world problem raised here? In real shop it is not a problem to simply remove `pub/media/catalog/tmp` whenever it is too huge and merchant knows that catalog filling is finished.

**Comment by andrii-dymov** [comment]
I can imagine only one situation when session may disappear - if another user deletes the user's account. Otherwise session destroy must be processed on logout or the next login.

In real shop there are third party extensions with the same image component and images being saved with the same model, but with another directories:

`<virtualType name="ThirdPartyUploader" type="Magento\Catalog\Model\ImageUploader">`
        `<arguments>`
            `<argument name="baseTmpPath" xsi:type="string">third/party/tmp</argument>`
            `<argument name="basePath" xsi:type="string">third/party</argument>`
            `...`
        `</arguments>`
`</virtualType>`

Merchant can't know that there are orphaned images in the media folder. And he makes multiple copies of them in backup. Magento must care about such files, not merchant or even third parties.

**Comment by orlangur** [comment]
> My main concern here is - what is a real-world problem raised here?

@awarche, I don't see an answer to this question.

> Otherwise session destroy must be processed on logout or the next login.

This would be even more complicated mechanism. Next login may never occur. Session data is not necessarily saved in persistent storage, it can be memcached or redis.

> third party extensions with the same image component and images being saved with the same model, but with another directories

... and we cannot clear such images by core code as it may be undesired for a particular extension. I don't see any reason to create more that one `tmp` folder for images.

**Comment by andrii-dymov** [comment]
> @awarche, I don't see an answer to this question.

I don't get you. Do you argue that current behavior is acceptable?

> ... and we cannot clear such images by core code as it may be undesired for a particular extension. I don't see any reason to create more that one tmp folder for images.

... I definitely expect to not care about tmp files, created by the standard image component, in my extensions. And of course, images for my entities must not be in catalog/tmp/category

**Comment by andrii-dymov** [comment]
> This would be even more complicated mechanism. Next login may never occur. Session data is not necessarily saved in persistent storage, it can be memcached or redis.

I wonder if people really use cache for admin pages. Anyway, I want to stop discussion about using session, you are welcome to give a better solutions. As I said, frontend can keep track of tmp files and send asynchronous requests when required.

**Comment by orlangur** [comment]
> frontend can keep track of tmp files and send asynchronous requests when required.

This simply does not work in some cases as already stated.

>  I don't see an answer to this question.
>> Do you argue that current behavior is acceptable?

I don't see any bugs produced by current behavior and I'm asking you to give insight on real-world problems caused by current behavior.

Dedicated CLI command/some Admin UI button "flush tmp images" probably makes sense but only if there is a real problem affecting real stores. If it's quite an uncommon scenario, `rm -rf pub/media/catalog/tmp` performed at suitable moment should do the trick.

**Comment by andrii-dymov** [comment]
> This simply does not work in some cases as already stated.

It's better than just keep accumulating orphaned images and multiplying them in backups.
And it's better to have zero to few images during the lifetime, than in a single session.

> I don't see any bugs produced by current behavior and I'm asking you to give insight on real-world problems caused by current behavior.

I never said we have something critical here. But it does not mean we can leave it as is. As extension developer, I'd like to use Magento components and existing backend logic with simple xml configuration. But that logic must take care about edge cases, as any good software does. I'm not a merchant, who has already a "real-life" problem and asks for a solution or explanation. And I can't just do `rm -rf` or make such recommendations to the merchant. Any merchant will say you that your software sucks. But if we reduce the possibility of this case from common to very rare and can explain why it's not reasonable to fully resolve it - clients will be happy. If no one came and punched you for this, that does not mean that there are no people, who silently hate you for their time spent on things like `rm -rf`;)

**Comment by magento-engcom-team** [comment]
@awarche, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
@awarche it only makes sense to spend efforts on fixing issues really affecting merchant or developer experience.

Quoting myself,
> Dedicated CLI command/some Admin UI button "flush tmp images" probably makes sense

should be enough, there is no other reliable implementation approach mentioned in this thread yet.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by orlangur** [comment]
No information provided about the impact of this issue in real world.

**Comment by angelflo** [comment]
This problem seems still not solve in Magento 2.2.10, can you confirm ?
