### ISSUE TITLE
Gift card products fail to generate gift card accounts

### ISSUE THREAD

**Issue by popovdenis** [magento/magento2#13281]
### Preconditions

1. Navigate to Admin > Stores > Configuration > Sales > Gift Cards.
2. On Gift Card General Settings set **Yes** for **Generate Gift Card Account when Order Item is**.

### Steps to reproduce

1. Logged in Customer or Guest
2. Gift card product added to to cart (gift card product is only in card)
3. Proceed to checkout
4. Fill out shipping information
5. Select Credit Card Direct Post (Authorize.net) Payment Method
6. Fill out Authorize.net test card
7. Place Order

### Expected result

1. Order has been placed successfully.

### Actual result

1. DB exception on saving value to **sales_order_item** DB table because **order_id** column is absent.

Partly, I've found solution to set order to item on default option:

_vendor/magento/module-gift-card/Observer/GenerateGiftCardAccounts.php:175_

I has allowed to place order successfully. But maybe there is could be another solution.

**Comment by orlangur** [comment]
This is not a part of Magento Open Source, isn't it?

**Comment by popovdenis** [comment]
Yes, it's Magento EE. I didn't check it on CE.

**Comment by magento-engcom-team** [comment]
@popovdenis thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@popovdenis, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
