### ISSUE TITLE
Save button is disable in configurable products 

### ISSUE THREAD

**Issue by afnanm** [magento/magento2#13290]
### Preconditions
1. Magento CE 2.1.9 without sample data is installed.
2. Porto theme installed.
3. SEO extenstion
4- odoo connector. 

### Steps to reproduce
1- downloade Magento CE 2.1.9.tar.bz2 from offical page:
https://magento.com/tech-resources/download
2- create a folder in httpdocs called "site"; path as www.example.com/site
3- unzip from ssh
4- install Magento
5- upload files of a theme via FTP account by FILLZILLA
6- execute this command via SSH: /opt/plesk/php/5.6/bin/php bin/magento setup:upgrade
7- execute this command via SSH: /opt/plesk/php/5.6/bin/php bin/magento setup:di:compile

### Expected result
1.  change store view
2. add details in another language
3. press Save button 
4. all change saved. 

### Actual result
1.  change store view
2. add details in another language
3. press Save button 
4. all change not saved because Save button not active or disable

**Comment by afnanm** [comment]
@magento-engcom-team please, is there a solution? deadline of project is after two days

**Comment by afnanm** [comment]
@magento-engcom-team

**Comment by magento-engcom-team** [comment]
@afnanm please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@afnanm, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
