### ISSUE TITLE
Backup missing pub/static.php file

### ISSUE THREAD

**Issue by fluential** [magento/magento2#13298]
When restoring from backup created using `bin/magento setup:backup --code`
following files are being ignored / missing:
```
pub/static.php
pub/static/.htpasswd
```
This is apparently a desired behaviour for backup task "excluding var and pub/static directories" via http://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-backup.html

It seems though that above mentioned files files are crucial for the static content to work correctly when in default or developer mode. These missing files are never generated during static content deployment so they should be included in the backup, similar to other files from `pub/` directory.

### Preconditions
1. Magento CE 2.2.2
2. PHP-FPM 7.0.27
3. MySQL 5.7.20
4. Nginx 1.12.1

### Steps to reproduce
1. Create archive using `bin/magento setup:backup --code`
2. Untar archive into a third party location
3. Verify file list differences between
```
/tmp/original/pub/:
cron.php
errors
get.php
health_check.php
index.php
media
opt
static.php

/tmp/restored/pub/:
cron.php
errors
get.php
health_check.php
index.php
media
opt
```

following files are missing:
```
pub/static.php
```
### Expected result
Following files needed in the backup:
```
cron.php
errors
get.php
health_check.php
index.php
media
opt
static.php
```
Stop ignoring following files when creating backup:
```
pub/static.php
```

### Actual result
Following files got actually included in the backup:
```
cron.php
errors
get.php
health_check.php
index.php
media
opt
```
Thi is easy to reproduce on cli

**Comment by magento-engcom-team** [comment]
@fluential, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29646` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
