### ISSUE TITLE
Not able to add class name to body using layout xml update for category

### ISSUE THREAD

**Issue by sakti-do** [magento/magento2#13306]
**While adding class to body using xml layout in category, its not being saved**
### Preconditions

1.  I was trying to add class name of body using xml layout update for a category but it was not savnig and thronging some error. 
2.  Magento 2.1.7, PHP 5.6, MySQL 5.0

### Steps to reproduce

1. Login to admin panel
2. go to category 
3. put value for  "Layout Update XML" :  <body><attribute name="class" value="application-page"/></body>
4. Try to save this
### Expected result

1. It should save

### Actual result

1. Error Message: Please correct the XML data and try again. Element 'body': This element is not expected. Expected is one of ( referenceContainer, container, update, move ). Line: 1 
2. 
![category-issue](https://user-images.githubusercontent.com/31617992/35208506-e05f0f40-ff6e-11e7-861d-c82efef3613b.png)

**Comment by magento-engcom-team** [comment]
@sakti-do, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
