### ISSUE TITLE
Magento 2.2.2 - Bundle product options not deleted properly - Js issue

### ISSUE THREAD

**Issue by harithasdckap** [magento/magento2#13307]
Hi all,
I have installed the new version of Magento 2.2.2 and created a bundle product with more than 30 options. While deleting one of the options from the first page, the bundle options of the second page are getting deleted. Checking the console for errors, Got the js issue in Magento_Bundle/js/components/bundle-dynamic-rows.js

### Preconditions

```
1. Ubuntu 16.04 LTS
2. PHP Version 7.0.26
3. MySql Version 5.7.20-0ubuntu0.16.04.1
```

### Steps to reproduce

```
1. Create a bundle product with more options to get pagination.
2. Select the First page of bundle options.
3. Delete any one of the bundle options.

```
### Expected result

`1. Bundle options to be deleted`

### Actual result

![before deleting options](https://user-images.githubusercontent.com/26427561/35208984-0b84da22-ff71-11e7-84cb-abc3d3dcd1a8.png)

![after deleting options](https://user-images.githubusercontent.com/26427561/35208992-130a3148-ff71-11e7-9f40-9d578e24347f.png)

Kindly guide me to fix the issue
Thanks

**Comment by magento-engcom-team** [comment]
@harithasdckap, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by nemesis-back** [comment]
@magento-engcom-team please assign to me

**Comment by riccardougolini** [comment]
take a look here @harithasdckap
https://github.com/magento/magento2/issues/13421

**Comment by mageprashant** [comment]
Hi @magento-engcom-team
Same issue here with Magento 2.2.6 version - https://www.screencast.com/t/XVpEB42MGixU

Please, any update?

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**
1. Create a bundle product with more options to get pagination.
2. Select the First page of bundle options.
3. Delete any one of the bundle options.

**Result**
Bundle options is deleted. No errors. 
![Screenshot_39](https://user-images.githubusercontent.com/51681435/71513167-e1b80280-28a1-11ea-8964-d2daeb0c616a.png)
![Screenshot_40](https://user-images.githubusercontent.com/51681435/71513173-e8df1080-28a1-11ea-8535-4c5a29b7eb83.png)

**Note**
If a Configurable product will be saved without options it will change the type to a simple product.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by sylvainraye** [comment]
Hi @mageprashant 

Did you resolved your issue ? We face the same one on Magento 2.4 with product bundle having a lots of options and selections into it. 

Thank you for your feedback

**Comment by raoulguillermo** [comment]
Hi @mageprashant 

I'm also having this issue with bundled products. It seems that after 20 options things go wrong.
When deleting an option on the 2nd page of options. At first it just removes the bottom one. 
Then after saving the entire bundle product the 2nd page and all pages after that are deleted. 

Please advise

**Comment by GeKVe** [comment]
We also have this issue - note that this is for BUNDLE products, not configurable, like @engcom-Echo tried to reproduce with. In our case, the reason is not caused by options hidden by pagination. We have this issue even without reaching pagination on the items - but only in some bundles containing a lot of options & items. Haven't managed to pinpoint the reason for why this is happening, but have a hunch it has something to do with a race condition between shuffeling options/items and automatic re-inits or re-renders on changes via `this.source.set` currently debugging in the bundle-dynamic-rows.js extension from module_bundle.
