### ISSUE TITLE
Wrong number of products in sidebar on payment step with configurable products.

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#13313]
I can't find anything like that, so I think I should create this issue.

### Preconditions

1. Magento 2.2.2
2. mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22

### Steps to reproduce

1. You should have a couple of configurable products available for buying.
2. Add a couple of products to [cart (more than one)](http://joxi.ru/KAxnj9MfMPG5qm) and go to payment method

### Expected result

1. I should see [appropriate number](http://joxi.ru/gmv87gVFLPGoaA) of products on sidebar
<img width="913" alt="chaussemouton-b2c_checkout-page_order-sum-up" src="https://user-images.githubusercontent.com/10618641/35264840-ed421424-0026-11e8-857b-b5e100b8764a.PNG">

### Actual result

1. I get the wrong number of [products on sidebar](http://joxi.ru/p27Wo7Eio1d152)

**Comment by arnoudhgz** [comment]
@AleksLi the images of the sidebar are not working. Can you update them?

**Comment by AleksLi** [comment]
@arnoudhgz. Sorry for that. Of course. I will.

**Comment by AleksLi** [comment]
@arnoudhgz here you go.

**Comment by magento-engcom-team** [comment]
@AleksLi thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![ordersummary](https://user-images.githubusercontent.com/31669971/35857947-8cdc7cca-0b32-11e8-8091-42151e9997d0.png)

**Comment by AleksLi** [comment]
@magento-engcom-team Please try to reproduce this bug properly. You should add a couple of products (as you point on screenshot) with QTY more then one.
I'll attach screenshot one more time
![35264840-ed421424-0026-11e8-857b-b5e100b8764a](https://user-images.githubusercontent.com/10618641/35860030-21675014-0b4b-11e8-99cd-8d37cc1b1b11.PNG)

**Comment by magento-engcom-team** [comment]
@ AleksLi thank you for your report.
This behavior is expected. "... items in Cart" means a quantity of the positions in the cart and not the sum of each positions quantity.

![expectedresult](https://user-images.githubusercontent.com/31669971/35918007-281de0d6-0c08-11e8-936d-615ccbeb35ea.png)

**Comment by magento-engcom-team** [comment]
@AleksLi, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by AleksLi** [comment]
@magento-engcom-team . 
Ok. Thank you for updating this issue. So, we could close this one.
