### ISSUE TITLE
Unable to add video in product 

### ISSUE THREAD

**Issue by techybirds** [magento/magento2#13312]
### Preconditions

1. magento version 2.2.1
2. php version 7.1.13

### Steps to reproduce

1. when i try to create product simple or any product
2. add new product click on "add video"  
3. 

### Expected result

1. video should can add

### Actual result

1. [Screenshot, logs]
add new video window in not open.
i had also check using inspect element that other dialog like new attribute and all that all make but there is not <aside > for new  video

Unable to add video in any product

**Comment by magento-engcom-team** [comment]
@techybirds Thanks for your report, please clarify what do you use to upload the video? (what platform). Also please let us know if you are able to reproduce this issue on the clean instance of Magento. Thank you

**Comment by techybirds** [comment]
when i click on add video button then poup not open

**Comment by magento-engcom-team** [comment]
@techybirds We are not able to reproduce this issue, please try to reproduce this issue on the clean instance of Magento, and let us know if you will have the same issue. Thank you

**Comment by techybirds** [comment]
It is working in fresh magento but not working in my current live site running.
So i get error in var log 
The element 'gallery' already has a child with alias 'content' {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The element 'gallery' already has a child with alias 'content at vendor/magento/framework/Data/Structure.php

how can i solve this?

**Comment by magento-engcom-team** [comment]
@techybirds The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment]
@techybirds, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
