### ISSUE TITLE
Catalog price rules do not invalidate existing cache while becoming valid.

### ISSUE THREAD

**Issue by TimQSO** [magento/magento2#13325]
When we setup a catalog price rule with a from and to date, the cache is not invalidated when the catalog price rule becomes active. Cache needs to be flushed manually to see the effect of the catalog price rule.

**Preconditions**
1. Magento 2.2.7, 2.4-develop
2. PHP 7.1; 7.2 | Ubuntu 16.04 LTS | Nginx 1.15.8
3. MySQL 5.7.25
4. Redis 4.0.2

**Steps to reproduce**
1. Create a catalog price rule with for example 20% discount for products in a certain category
2. Make the price rule valid for a date in the future
3. Make sure the category and the products that will become valid for this price rule are cached (just) before the rule becomes valid
4. When the price rule becomes valid on the selected 'from' date, check the prices of that category
5. Prices in the category grid are still the normal prices, also prices on the PDP are still the normal prices
6. Place a product in your cart, and check the cart price. You will see that the discount of the rule in the cart is succesfully applied
7. Flush Magento Cache or Reindex manually
8. Recheck category and / or PDP, you will see that the catalog price rule now is visible

**Expected result**
When the catalog price rule becomes valid on the 'from' date, the prices on the grid and the PDP should be updated automatically according to the discount of the catalog price rule. Without manual inteference like flushing cache of reindexing manually.

**Actual result**
The updated prices according to the price rule are not updated / visible in the category or PDP. Manual flush of cache or reindexing manually is needed.

Note: the same unexpected behaviour occurs when the 'to' date of the catalog price rule has expired. The prices are not changed back to the normal prices unless the cache is flushed.
[video](https://youtu.be/K8EPXUIaVgQ)

**Comment by stephan-cream** [comment]
This is indeed an issue.
When the cronjob "catalogrule_apply_all" is run it invalidates the indexer.
However when the indexer "catalogrule_rule" is run it does not invalidate / clear the cache.
Furthermore i found an unused method _invalidateCache in the class Magento\CatalogRule\Model\Rule.

**Comment by magento-engcom-team** [comment]
Hi @GuiltyNL
Thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
New prices shows after run reindex.
See [video](https://youtu.be/K8EPXUIaVgQ)

**Comment by TimQSO** [comment]
Ok, but you **manually** start a reindex? Before manually starting the reindex your prices were not updated either?

So you did reproduce it, as I saw in your video. The new prices did not pop up, you ran the cron several times without success and you needed to run the indexer manually from the command line to let the catalog price rule work?

Am I missing it?

**Comment by magento-engcom-team** [comment]
Yes, this can be bug, but you should correct the description

**Comment by TimQSO** [comment]
Done.

**Comment by magento-engcom-team** [comment]
@GuiltyNL, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by TimQSO** [comment]
Any updates on this one?

**Comment by gody01** [comment]
The same issue here.
It looks like there is missing scheduled process to invalidate product related pages, when date rule should become active.

**Comment by TimQSO** [comment]
This bug is causing severe issues, is no one working on this one?

**Comment by TimQSO** [comment]
I cannot understand that nobody is working on this issue.

As catalog price rules can't be used since the introduction of Magento 2.

**Comment by peterjaap** [comment]
@magento-engcom-team @miguelbalparda @osrecio could somebody give this an issue some much-needed attention?

**Comment by TimQSO** [comment]
I can't be difficult to solve. 

It is a important core feature of M2 that can't be used now.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30655` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by TimQSO** [comment]
I can also confirm that this is still happening on 2.3.3. It would be nice to be able to use Catalog prices rules. My ticket is almost two years old now. ;)

**Comment by antoninobonumore** [comment]
@GuiltyNL is this still an issue on 2.3.4 ?

**Comment by TimQSO** [comment]
I think so @antoninobonumore  as they just confirmed it is still an issue in 2.4-develop too.

**Comment by engcom-Kilo** [comment]
Hello, @GuiltyNL 
Thanks for your report.
I'm not able to reproduce this issue on latest 2.4-develop. Looks like it has been fixed in https://github.com/magento/magento2/commit/fc6c7f1aeadf83e7e6083e387b4a82c8a1cacbea

**Comment by magento-engcom-team** [comment]
Hi @GuiltyNL, @engcom-Kilo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-30655` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
