### ISSUE TITLE
No "use default value" checkbox for custom category attributes

### ISSUE THREAD

**Issue by kevincream** [magento/magento2#13329]
### Preconditions
PHP 7.0.25
MariaDB 10.1.29
Magento versions: v2.2.0 & v2.2.2

### Steps to reproduce
1. Add a custom category attribute via ui_components with the following code:
```
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="general">
        <field name="deal_skus">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="sortOrder" xsi:type="number">110</item>
                    <item name="dataType" xsi:type="string">string</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="label" xsi:type="string" translate="true">Daily Deal SKUs</item>
                    <item name="required" xsi:type="boolean">false</item>
                </item>
            </argument>
        </field>
    </fieldset>
</form>

```
2. Edit a category in the admin on the store view scope

### Expected result
1. Checkbox appears with "use default value".
2. Default value can be used.

### Actual result
1. No checkbox appears and the storeview value is alway used, even when empty.

**Comment by max-atkins** [comment]
I'm getting this too. Have you used an InstallData file?
I have this set: 'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_STORE
but still don't see checkbox

**Comment by jakoblundsted** [comment]
Im having the same issues. Adding a custom attribute with the same as above.

**Comment by max-atkins** [comment]
I've posted an issue with some more detail here: https://github.com/magento/magento2/issues/13440

**Comment by magento-engcom-team** [comment]
Close on duplicate #13440

**Comment by magento-engcom-team** [comment]
@kevincream, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by akssaiyad** [comment]
>> Set to check Use default Value for Product in magento 2.

```
DELETE FROM `catalog_product_entity_text` where store_id = 1;
DELETE FROM `catalog_product_entity_datetime` where store_id = 1;
DELETE FROM `catalog_product_entity_decimal` where store_id = 1;
DELETE FROM `catalog_product_entity_int` where store_id = 1;
DELETE FROM `catalog_product_entity_varchar` where store_id = 1;
```

>> Set to check Use default Value for Category in magento 2.

```
DELETE FROM `catalog_category_entity_text` where store_id = 1;
DELETE FROM `catalog_category_entity_datetime` where store_id = 1;
DELETE FROM `catalog_category_entity_decimal` where store_id = 1;
DELETE FROM `catalog_category_entity_int` where store_id = 1;
DELETE FROM `catalog_category_entity_varchar` where store_id = 1;
```

Note : In above SQl query store_id 1 is ID of store. kindly you need to check store Id for all store-views in admin and run the above code for each store-views saperately.
