### ISSUE TITLE
Deployment failed: composer.json and composer.lock files should be placed outside the htdocs directory

### ISSUE THREAD

**Issue by muckee** [magento/magento2#13322]
When cloning CE and deploying on Gandi servers, following their own instructions, the process is aborted with the error mentioned in the title.

### Preconditions

1. Magento 2.2.1 CE
2. PHP7.1
3. MySQL 5.6
4. Gandi.net servers - simple hosting instance
5. Local machine is ubuntu 16.04 x64

### Steps to reproduce

1. Following directions from gandi.net [here](https://wiki.gandi.net/en/tutorials/simple/php/magento2) and [here](https://wiki.gandi.net/en/simple/git#clone_a_repository).
2. Enter following commands:
3. `$ cd ~`
4. `$ mkdir [VHOST_NAME]`
5. `$ cd [VHOST_NAME]`
6. `$ git remote add gandi git+ssh://[USER_ID]@git.[SERVER].gpaas.net/[VHOST_NAME].git`
7. `$ composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition htdocs`
8. `$ git add .`
9. `$ git commit -m 'Install Magento 2'`
10. `$ git push gandi master`
11. `$ ssh [USER_ID]@git.[SERVER].gpaas.net deploy [VHOST_NAME].git`

### Expected result

1. 'Build complete' message should be seen in terminal.

### Actual result

1. Completed up to step 10 of 'Steps to reproduce' successfully. 
2. Step 11 fails with error message: `composer.json and composer.lock files should be placed outside the htdocs directory`.

**Comment by muckee** [comment]
The only workaround I have established for this is to manually add the files and run the composer installation inside the htdocs folder of the hosting instance, then pull from the server to my local repository. I had to add a `.gitignore` file to the local repository which excludes the `composer.json` and `composer.lock` files from commits in order to avoid future errors.

**Comment by katiakweb** [comment]
Same problem here... Following the post...

**Comment by muckee** [comment]
Katiakweb sorry this was my fault, forgot to close the issue. You just have to install magento into your server root, or another private location on your server, then create a symlink from htdocs to magento's pub folder.

I've seen that some people can't set up their server using symlink, so there could still be an issue, but it worked for me.

**Comment by katiakweb** [comment]
Thank you, Joshua, I already did that. Is working now. Thanks for answer!
