### ISSUE TITLE
Fatal error: Nesting level too deep 

### ISSUE THREAD

**Issue by mamsincl** [magento/magento2#13336]
That will be a little problematic, because the error happening in a custom product importer - the main reason for raising this issue if anybody else will facing with the same this could provide some starting point

During saving configurable product, got a
> Fatal error: Nesting level too deep - recursive dependency? in /_routeToMagento_/vendor/magento/framework/Model/AbstractModel.php on line 440
 
the related configurable product is part of a batch (~240/335); non of any previous or later products have the issue - also the product itself does not contains any more data as others (honestly contains less, also no gallery for the product). I only set data to default store view.

Anyway, changing not equal (_!=_) comparison operators to not identical (_!==_) in the related file solved the problem and was able to save the product

### Preconditions

1. Magento 2.1.9
2. server cpsrvd 11.68.0.27
3. php v5.6.33
4. db:  10.0.33-MariaDB

### Steps to reproduce

1. N/A (Custom importer/API connection)

### Expected result

1. Configurable product successfully saved

### Actual result

1. Fatal error: Nesting level too deep - recursive dependency? in /_routeToMagento_/vendor/magento/framework/Model/AbstractModel.php on line 440

If necessary I can list what I set in the product before trying to save, also if I'll have enough time will check what could cause the problem

**Comment by magento-engcom-team** [comment]
@mamsincl, please refer to the Community Forums or the Magento Stack Exchange site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
