### ISSUE TITLE
Setup:di:compile issue

### ISSUE THREAD

**Issue by ianmuge** [magento/magento2#13332]
When we compile the codebase it breaks and throws exceptions on the backend interface and the command line fails to show other options only showing the image below
![image](https://user-images.githubusercontent.com/13362741/35282588-e28f8e40-0066-11e8-9c0a-2fb393eb133a.png)

### Preconditions

1. Magento 2.1.6 Enterprise Edition
2.  php 7.0.22 with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.1.0 (), Copyright (c) 2002-2017, by ionCube Ltd.
    with Zend OPcache v7.0.22, Copyright (c) 1999-2017, by Zend Technologies
3. Redis server v=3.2.8 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=e10c036759257ada
4. mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

### Steps to reproduce

1. go to Magento root
2. php bin/magento setup:upgrade
3. php bin/magento deploy:mode:set developer
4. php bin/magento s:d:c 
5. php bin/magento s:s:d -j 1 
6. php bin/magento deploy:mode:set production -s
7. push code to frontend servers

### Expected result

1. Code compilation (s:d:c) completes successfully

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/13362741/35282397-6cce43b8-0066-11e8-8c83-80ee20cfa151.png)

 a number of front end servers on DMZ, backend on internal network, Redis for caching and session management

**Comment by ruthgeridema** [comment]
Guess it's a problem with a plugin which isn't well defined in Di.xml

**Comment by ianmuge** [comment]
My main issue is that it is throwing that error on one environment and not in the others and at times it compiles successfully

**Comment by ianmuge** [comment]
We found a work around, Create another env.php file that uses db/files during compilation, run di:compile then replace the env.php file again with one that uses Redis and push your code to the frontend

![image](https://user-images.githubusercontent.com/13362741/36115374-f62bc922-1043-11e8-96c6-ab80015620fa.png)
