### ISSUE TITLE
Autoload error: An abstract factory could not create an instance of

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2#1333]
If executable this commands ...

php bin/magento maintenance:status && php bin/magento module:status && php bin/magento setup:db:status && php bin/magento setup:upgrade

php -f bin/magento module:enable Magento_Hello

Generate this error ...

Autoload error: An abstract factory could not create an instance of magentosetupconsolecommandconfigsetcommand(alias: Magento\Setup\Console\Command\ConfigSetCommand).

![captura de tela de 2015-06-02 22 47 30](https://cloud.githubusercontent.com/assets/2263217/7951081/60c276ca-0979-11e5-8880-aa847cb012bd.png)

**Comment by mazhalai** [comment]
Hello @cerebrumbr, combination of Zend and Magento's error handler hides the original error. Please try this [temporary fix](https://github.com/magento/magento2/pull/1323) provided by @Flyingmana to see what the exact error is.

**Comment by MaxSavich** [comment]
Internal ticket: MAGETWO-40189

**Comment by mazhalai** [comment]
@cerebrumbr This has been fixed in scope of another ticket. Can you please verify?

**Comment by piotrekkaminski** [comment]
Closing as no response from issue author

**Comment by flancer64** [comment]
"Encrypted" error message is still got on CLI errors:

    Autoload error: An abstract factory could not create an instance of magentosetupconsolecommandconfigsetcommand

I have disabled error masking in ./bin/magento (as discribed in @Flyingmana [fix](https://github.com/magento/magento2/pull/1323)) and have got an actual error message that pointed me to a reason of the my problem.
