### ISSUE TITLE
Error when trying to disable Asynchronous indexing in grid setting

### ISSUE THREAD

**Issue by erikkubica** [magento/magento2#13347]
### Preconditions

1. PHP 7
2. Magento 2.2.1
3. MariaDB

### Steps to reproduce

1. In developer mode, try to disable Asynchronous indexing in Grid settings (Store config -> Advanced -> Developer)

### Expected result

1. The Asynchronous indexing is disabled

### Actual result

1. "Something went wrong while saving this configuration: SQLSTATE[42S02]: Base table or view not found: 1146 Table '[mydatabasename].sales_order' doesn't exist, query was: SELECT `sales_order`.`entity_id` FROM `sales_order` LEFT JOIN `sales_order_grid` ON sales_order.entity_id = sales_order_grid.entity_id WHERE (sales_order_grid.entity_id IS NULL)"

Problem occured when I have noticed, that new orders (shipments and invoices also) are not appearing in admin grid. So I googled and found out that there is a bug with the asyn. indexing, so I went to turn it off, but I cannot turn it off.

FAQ
Q: Did you tried to clear cache? Recompile, flush, static deploy,... reindex....?
A: Yes

**Comment by erikkubica** [comment]
Some weird thing happened. I was trying to debug the code, i went to Magento\Sales\Model\ResourceModel\Provider\UpdatedIdListProvider->getIds  and placed a 

```
var_dump($mainTableName);
var_dump($gridTableName);
die;
```

The dump did not worked but magento is not showing the error again and the async indexing is now disabled. So I have restored the UpdatedIdListProvider to the original state and the "bug" is gone.

**Comment by magento-engcom-team** [comment]
@erikkubica , thank you for your report.
Asynchronous indexing is disabled by default configuration, we can enable or disable this indexing on vanilla installation, please check this issue without any extension if you have.

**Comment by erikkubica** [comment]
@magento-engcom-team I cannot reproduce it anymore, as I have mentioned in previous comment, so for now the issue should be closed, if it will happen again, then i will try to provide more information.

**Comment by magento-engcom-team** [comment]
@erikkubica, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
