### ISSUE TITLE
Blank page on forget password for admin

### ISSUE THREAD

**Issue by priti-rathee** [magento/magento2#13349]
### Preconditions

1. magento version 2.2.2
2. php version 7.0.24
3. Migrated from 1.9.0.1 
 
### Steps to reproduce

1. click on forget password for admin panel
2. a link will be sent on email to reset admin password
3. click on the link received on email for resetting password 
### Expected result

1. a page to set new password should appear with input boxes for new password and confirm new password.

### Actual result

1. a page appears with a form with magento logo only. 
![screenshot from 2018-01-24 16-47-22](https://user-images.githubusercontent.com/33680940/35329841-3e64e22c-0127-11e8-869f-d4d9c49d843e.png)

[Screenshot, logs]

**Comment by yogeshsyscraft** [comment]
Hi ,

Can you please open console of browser By pressing "F12" KEY . it will show accurate error .


Thanks

**Comment by priti-rathee** [comment]
I don't see any error in consol.
![screenshot from 2018-01-25 11-43-11](https://user-images.githubusercontent.com/33680940/35373581-202d9d46-01c5-11e8-9bd8-c5ca0d755ada.png)

**Comment by yogeshsyscraft** [comment]
can you recompile your code and after compile use Deploy cmd and than flush cache and try in private window .

**Comment by priti-rathee** [comment]
Yes, there are some issues I can see now. But I don't think that have created this issue.
I am attaching the screen-shot for your reference. Please refer.
![screenshot from 2018-01-25 11-57-27](https://user-images.githubusercontent.com/33680940/35374124-93515c0c-01c7-11e8-96f2-151a216c09ca.png)

**Comment by yogeshsyscraft** [comment]
have you done recompilation and deploy ??

**Comment by priti-rathee** [comment]
yes I recompiled, deployed and flushed cache  then only I was able to see these errors

**Comment by yogeshsyscraft** [comment]
Use this cmd to create new admin user for now . and let me know if new user is created or not with this cmd

> bin/magento admin:user:create --admin-user="admin" --admin-password="123123q" --admin-email="admin@example.com" --admin-firstname="Admin" --admin-lastname="Admin"

**Comment by priti-rathee** [comment]
Yes using this I am able to create new user, also I have already reset my password through database. But I need to resolve this issue as my client can't reset password through database.

**Comment by magento-engcom-team** [comment]
@priti-rathee Thanks for your report. We tried reproducing this issue on the clean instance of Magento, and we weren't able to reproduce it. Please let us know if you are using any 3'rd party code or extensions and please try to reproduce the issue on the clean instance. Thank you

**Comment by yogeshsyscraft** [comment]
@priti-rathee  have you done migration from older version , or you have developed this from scratch in magento 2.2.2 .

**Comment by priti-rathee** [comment]
I have migrated data and settings from 1.9.0.1 version and functionality wise we have customized by our own on this version (2.2.2).

**Comment by yogeshsyscraft** [comment]
i need to check this issue on your website , can you share details here  syscraft.yogesh@gmail.com ?

**Comment by magento-engcom-team** [comment]
@priti-rathee Seems like it's a migration-related issue, please refer to this repository: https://github.com/magento/data-migration-tool 
Thank you.

**Comment by magento-engcom-team** [comment]
@priti-rathee, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
