### ISSUE TITLE
No REST API endpoint for payment-information for specific cart id

### ISSUE THREAD

**Issue by archonkulis** [magento/magento2#13358]
### Preconditions
1. Magento 2.1.6

### Steps to reproduce
1. Successfully do all the steps from http://devdocs.magento.com/guides/v2.1/get-started/order-tutorial/order-create-order.html until the last 7 step and with using `/carts/:cartId/...` endpoints everywhere instead of e.g. `/carts/mine/..`.

For cart creation through API, use: `/customers/:customerId/carts` and then use this cart id.

List of using cart id in the endpoints:

```
/carts/:cartId/items/
/carts/:cartId/estimate-shipping-methods
/carts/:cartId/shipping-information
```

The specific data that you send doesn't matter as long as you get to that 7th step and assign items, shipping methods, and shipping information to specific cart id like in examples above.

2. At the 7th step try to create an order.

### Expected result
1. The possibility to create an order for specific cart id.

### Actual result

1. There is no such endpoint like `/carts/:cartId/payment-information`. Therefore, I don't see any possibility to create an order using the steps above. At least, it's not mentioned in the documentation.

There are all the Checkout API methods listed in documentation:

```
* POST   /V1/guest-carts/:cartId/shipping-information
POST   /V1/carts/mine/shipping-information
POST   /V1/carts/:cartId/shipping-information
POST   /V1/carts/:cartId/totals-information
POST   /V1/guest-carts/:cartId/totals-information
POST   /V1/carts/mine/totals-information
POST   /V1/guest-carts/:cartId/payment-information
GET    /V1/guest-carts/:cartId/payment-information
POST   /V1/carts/mine/payment-information
GET    /V1/carts/mine/payment-information
POST   /V1/guest-carts/:cartId/set-payment-information
POST   /V1/carts/mine/set-payment-information
```
( http://devdocs.magento.com/guides/v2.1/rest/list.html )

Please provide me with the endpoint that I can use to create an order for specific cart id or some alternative.

**Comment by archonkulis** [comment]
I thought I will be able to switch from `:cartId` to `mine`, but I also can't initialize empty cart for the admin token:

1) Get admin token: `/integration/admin/token`
2) Token received successfully
3) Create empty cart: `/carts/mine`
4) Result: `{"message":"%fieldName is a required field.","parameters":{"fieldName":"customerId"}`

What on earth?

**Comment by morzzz007** [comment]
Hey, we have been experimenting with this awful api too, and this issue can be found easily with google, so here is what we did:

The endpoint mentioned in the "tutorial" does two things: sets the billing address and sets the payment method, but thanks to the horrible design of the API, you can do these separately.

1: You can set the billing address posting the `/index.php/rest/V1/carts/${cartId}/shipping-information` endpoint the following payload:

```
payload: {
  addressInformation: {
    shipping_address: {
      region: 'New York',
      region_id: 43,
      region_code: 'NY',
      country_id: 'US',
      street: ['123 Oak Ave'],
      postcode: '10577',
      city: 'Purchase',
      firstname: 'Jane',
      lastname: 'Doe',
      email: 'jdoe@example.com',
      telephone: '512-555-1111'
    },
    billing_address: {
      region: 'New York',
      region_id: 43,
      region_code: 'NY',
      country_id: 'US',
      street: ['123 Oak Ave'],
      postcode: '10577',
      city: 'Purchase',
      firstname: 'Jane',
      lastname: 'Doe',
      email: 'jdoe@example.com',
      telephone: '512-555-1111'
    },
    shipping_carrier_code: 'tablerate',
    shipping_method_code: 'bestway'
  }
}
```

2: You can get the `orderId` by doing a PUT request to `/index.php/rest/V1/carts/${cartId}/order` with the paymentMethod in the payload

```
paymentMethod: {
  method: 'checkmo'
}
```

I hope it helps anybody googling this issue!

**Comment by mshoaibqureshi** [comment]
In magento 2.3.0 I experience the same issue.
and here using POST request to  `/rest/V1/carts/${cartId}/order`  gives 
```
{
    "message": "Request does not match any route.",
    "trace": null
}
```
and PUT request to  `/rest/V1/carts/${cartId}/order`  yields to 
```

{
    "message": "The consumer isn't authorized to access %resources.",
    "parameters": {
        "resources": "Magento_Cart::manage"
    },
    "trace": "#0 /var/www/html/dirname/vendor/magento/module-webapi/Controller/Rest/RequestValidator.php(68): Magento\\Webapi\\Controller\\Rest\\RequestValidator->checkPermissions()\n#1 /var/www/html/dirname/vendor/magento/module-webapi/ ...
```

Is there any other solution?
