### ISSUE TITLE
"Something is Wrong" from Account Create Form Submission

### ISSUE THREAD

**Issue by ctroyp** [magento/magento2#13365]
### Preconditions

1. Magento 2.2.1 (tag unknown)
2. PHP 7.1
3. MySQL 5.6
4. Varnish Cache 5.2
5. GoDaddy VPS

### Steps to reproduce

1. From home page, click 'Create An Account' link and fill out details.  Use unused email on site.
2. Either check or uncheck newsletter.
3. Click 'Create And Account'.

### Expected result

1. Account successfully gets created.

### Actual result

1. Returns to empty Create Account form with error: "Something is wrong"

I have searched all of the en_US.csv files and lots of the relevant code, but cannot find the text "Something is Wrong"  Please understand that this it the verbatim message and it is not "Something Went Wrong...".

**Comment by magento-engcom-team** [comment]
@ctroyp, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation without any extension for latest release.

**Comment by ctroyp** [comment]
Are you aware of any area (file) that has the text "Something is Wrong"?  This may help me to troubleshoot within my specific environment.  I will also try to remove extensions and themes.

**Comment by ctroyp** [comment]
Solved: I found that Google Invisible Captcha was inadvertently enabled.  Thank you!

**Comment by magento-engcom-team** [comment]
@ctroyp, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
