### ISSUE TITLE
Magento 2.2.2 Credit Memo javascript error - (index):653 Uncaught ReferenceError: enableElements is not defined

### ISSUE THREAD

**Issue by ralbin** [magento/magento2#13369]
### Preconditions

1. Magento Cloud and self hosted
2. Version 2.2.2

### Steps to reproduce

1.  Log into Magento admin
2. Find an order you can create a credit memo on
3. When you load the new credit memo page, the navigation will not work
4. Using the Inspect element and viewing the console you will see the jquery error
![magento-bug-credit-memo](https://user-images.githubusercontent.com/11746350/35404144-8affb080-01c7-11e8-883b-17b9871407a9.png)
In the console you can see this uncaught error
Uncaught ReferenceError: enableElements is not defined
    at toggleCustomerBalanceRefundAmount ((index):764)
    at HTMLDocument.<anonymous> ((index):769)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at ready (jquery.js:3582)

### Expected result

1. Remove the dependency that is causing this
please take a look there \vendor\magento\theme-adminhtml-backend\etc\view.xml
<item type="file">Lib::mage/adminhtml/tools.js</item>is excluded in 50 row
but `enableElements` is determined there. If I enabled this lib, error would disappear

### Actual result

1. Error shows up

This has been validated in 2 different Magento installs both running version 2.2.2.  1 was a Magento cloud environment,  and the other was hosted at Rackspace.

**Comment by ralbin** [comment]
This may not be a core issue.  Even though I found it on 2 different sites, they both have some of the same integrations and are not isolated from one another.  I also tested this on a basically vanilla M2 site and that did not show the same errors.  This does not appear to be a bug after all.

**Comment by molsm** [comment]
Got same error. Not tested on vanilla M2 site. Will update after any findings
