### ISSUE TITLE
Adopt Queue Interop\Enqueue

### ISSUE THREAD

**Issue by makasim** [magento/magento2#13360]
Having Queue Interop\Enqueue  on board brings Magento to the next level. Contact me on Skype (maksim_ka2) or send an email to kotlyar.maksim@gmail.com to discuss possible ways of integration.

Features:

* Improves performance
* Provides higher fault tolerance
* Decouple monolith 
* Integration with other services via a message bus. 

* [Feature rich](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/quick_tour.md).

* Adopts [queue interoperable](https://github.com/queue-interop/queue-interop) interfaces (inspired by [Java JMS](https://docs.oracle.com/javaee/7/api/javax/jms/package-summary.html)).
* Battle-tested. Used in production.
* Supported  transports 
    * [AMQP(s)](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/amqp.md) based on [PHP AMQP extension](https://github.com/pdezwart/php-amqp). 
    * [AMQP](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/amqp_bunny.md) based on [bunny](https://github.com/jakubkulhan/bunny). 
    * [AMQP(s)](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/amqp_lib.md) based on [php-amqplib](https://github.com/php-amqplib/php-amqplib). 
    * [Beanstalk](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/pheanstalk.md).
    * [STOMP](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/stomp.md)
    * [Amazon SQS](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/sqs.md)
    * [Google PubSub](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/gps.md)
    * [Kafka](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/kafka.md)
    * [Redis](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/redis.md)
    * [Gearman](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/gearman.md)
    * [Doctrine DBAL](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/dbal.md)
    * [Filesystem](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/filesystem.md)
    * [Null](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/transport/null.md).
* [Symfony bundle](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/bundle/quick_tour.md)
* [Magento1 extension](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/magento/quick_tour.md)
* [Laravel extension](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/laravel/quick_tour.md)
* [Yii2. Amqp driver](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/yii/amqp_driver.md)
* [Message bus](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/quick_tour.md#client) support.
* [RPC over MQ](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/quick_tour.md#remote-procedure-call-rpc) support.
* Temporary queues support.
* Well designed, decoupled and reusable components.
* Carefully tested (unit & functional).
* For more visit [quick tour](https://github.com/php-enqueue/enqueue-dev/tree/master/docs/quick_tour.md).

**Comment by magento-engcom-team** [comment]
@makasim, thank you for your report.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
