### ISSUE TITLE
Catalog price rule save is too slow

### ISSUE THREAD

**Issue by udovicic** [magento/magento2#13378]
### Preconditions

1. Have a large enough data set
2. Set indexing mode to `Reindex on schedule`

### Steps to reproduce

1. Go to admin and create new catalog price rule that has condition based on category
2. Hit save

### Expected result

1. New catalog price rule should be saved within reasonable time

### Actual result

1. Request times out

### Details

There are actually more than one thing wrong here:
1) Function [after save](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/CatalogRule/Model/Rule.php#L520-L523) of `Magento\CatalogRule\Model\Rule` walks through collection of products and triggers the reindex, regardless of indexing setting. It may do nothing, but the fact that it does go over the data set makes this action really slow. Plus, depending on third party integrations, it may trigger unwanted sync at this point. And I know that what third party extensions do is not under your control, just pointing out that something is triggered and that is not supposed to happen at this time.

2) They way it fetches the affected products is wrong. Function [getMatchingProductIds](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/CatalogRule/Model/Rule.php#L289-L321) will not scope the collection by category. And if that is your only condition, you will get whole catalog, even though the rule will affect only two products in that category. With the large enough set, code will end up checking potentially hundreds of thousands of products instead of just one category.

Combining these two, you get additional actions triggered where not necessary, on a data set that is too large in the first place hence the transaction timing out. I have observed this on just 140k products in the catalog.

**Comment by magento-engcom-team** [comment]
@udovicic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mslabko** [comment]
Hi @udovicic ,
We have introduced a new mechanism of matching products for indexation catalog rule products which significantly decrease time of indexation: https://github.com/magento/magento2/commit/8b36f39e432399ba06439928f0f0637798c35fbe

And issue with permanent indexation during save new catalog rule was fixed by @chrom in https://github.com/chrom/magento2/commit/8ef13ffdb69b2ec14633d83a5bb9bea83e46ec4f

Fill free to reopen the issue if you still have any issue with re-indexation time.

**Comment by udovicic** [comment]
Hi @mslabko ,

Thanks for the update. Though you should probably tell that to the core team, as I was just updated on EE support, that this is still being worked on, and there is no ETA on completion.
