### ISSUE TITLE
Display out-of-stock products last in category pages

### ISSUE THREAD

**Issue by bansavage** [magento/magento2#13371]
I would like to display **out-of-stock products at the end of my category pages**. This option does not exist in neither the system configuration nor store configuration. There is also no effective way of programmatically accomplishing this task. 

Also, please note that **this issue has been documented since _November 2016_** **and has still not been resolved.** This has been and is continuing to be a major issue. ([https://github.com/magento/magento2/issues/7589](url)) 

### Preconditions

1. Magento 2.1.7
2. Apache Webserver
3. PHP 7.0

### Steps to reproduce

1. Create a catalog with both in-stock AND out-of-stock products
2. View a category page and attempt to display the out of stock products at the end of the category page

### Expected result

1. Out-of-stock products are displayed at the end of category pages.

### Actual result

1.  In-stock and out-of-stock products are mixed together. Out-of-stock products are not solely at the end of the category page. And in-stock products are not solely at the beggining of the category page

**Comment by magento-engcom-team** [comment]
@bansavage, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Display-out-of-stock-products-last-in-category-pages/idi-p/86408).
