### ISSUE TITLE
magento setup:di:compile fail

### ISSUE THREAD

**Issue by gaoyong06** [magento/magento2#13379]
1. Magento version: 2.2
2. Steps to reproduce:
    
I installed Magento on my computer and added a new module and then magento source code and new modules are submitted to the company's git
And mysql magento database dump into sql file

Now ready to deploy the code to the company's server

Log in to the company's server first from the git reference to the code down from the company
Put two files on my computer
magento_root / app / etc / config.php
magento_root / app / etc / env.php
Copy to the company's server

And in the company's server to modify the config.php mysql connection information (host, user, passwd)
Then the sql file into the company server mysql

Then the company's server to perform:
composer install
php bin / magento setup: upgrade
php bin / magento setup: di: compile

3. Expected result :  setup:di:compile command run complete
4. Actual result：setup:di:compile command Throw error

when i ran command 
php bin/magento setup:di:compile

Will report the following error

![0e37f3c8-e634-4cba-a5d8-1dc7aaa6d7cb](https://user-images.githubusercontent.com/1861256/35431613-1b5363e8-02b8-11e8-9e89-4f64e41ae65b.png)

 Magento\Checkout\Api\Data\PaymentDetailsInterface::getExtensionAttributes() is original source code.I didn't modify it

Where I made a mistake？？？

**Comment by magento-engcom-team** [comment]
@gaoyong06 , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by gaoyong06** [comment]
@magento-engcom-team  Thank you. It has been modified.

**Comment by magento-engcom-team** [comment]
@gaoyong06 , thank for you update. Please check this issue on vanilla installation without any extension

**Comment by gaoyong06** [comment]
@magento-engcom-team  how to check? 😀

**Comment by magento-engcom-team** [comment]
@gaoyong06 , http://devdocs.magento.com/guides/v2.2/install-gde/bk-install-guide.html

**Comment by gaoyong06** [comment]
@magento-engcom-team 

Have seen before, will not help to solve the above problems

**Comment by magento-engcom-team** [comment]
@gaoyong06, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@gaoyong06 , thanks for you update, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
