### ISSUE TITLE
Problem With Symlinks When Linking a Module Directory Out of Magento Root Directory

### ISSUE THREAD

**Issue by tiagosampaio** [magento/magento2#13375]
### Preconditions

1. Magento 2.0.x, 2.1.x and 2.2.x.
2. PHP 1.7.x
3. MySQL 5.6

### Steps to reproduce

1. Create a module with a template file out of the Magento's root directory.
2. Link the module though a symbolic link into Magento.
3. When the Magento tries to render the template file it gives us an exception.

### Expected result

1. Magento must gives an exception telling that the template file is not valid.

### Actual result

1. [Screenshot, logs]
[Magento2_error.log](https://github.com/magento/magento2/files/1666241/Magento2_error.log)

**Comment by magento-engcom-team** [comment]
@tiagosampaio, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
Issue is invalid, see https://github.com/magento/magento2/pull/13376#issuecomment-431146311 for more details.
