### ISSUE TITLE
Timeout between NGINX and PHP-FPM using Magento Community

### ISSUE THREAD

**Issue by gde-pictime** [magento/magento2#13391]
The site we are running with magento experience a lot of timeout between NGINX and PHP FPM. 
The error message in the NGINX error log is "upstream time out (110: Connection timed out) while reading response header from upstream".
The server is not really loaded. The load average is 5 for 12CPUs. 

### Preconditions

1. Magento Community 2.1.4
2. PHP-FPM 7.0.14
3. NGINX 1.10.2 release 1.el7
4. CentOS 7

### Steps to reproduce

1. I don't really have steps to reproduce. It happens under server load. The query load is very low. Less than 15 query per seconds

### Expected result

1. No time out, or mush less.

**Comment by TimQSO** [comment]
This is not a Magento issue, so it does not belong here. Change your upstream to a socket or reverse to IP. And test again.

**Comment by gde-pictime** [comment]
Hello,

After quite long investigations, we found that it was an issue with too mush I/O on the disks when we activated the cache block. 

Sorry for posting here, we were in panic because it happened in production and our customer could not record any more orders.
