### ISSUE TITLE
Cannot Create Customer Attribute without Selecting a "Forms to Use In" Option

### ISSUE THREAD

**Issue by KernelKorn** [magento/magento2#13395]
### Preconditions

1. Magento 2.2.0
2. PHP 7.1.13

### Steps to reproduce

1. Create a new Customer Attribute 
2. Do not select a 'Forms to Use In' option
3. Try to save the Attribute

### Expected result

1. Should be able to save Customer Attribute

### Actual result

1. Fatal error is given:
![screenshot 2018-01-26 13 48 13](https://user-images.githubusercontent.com/3968658/35455356-937226c0-029f-11e8-9634-2038016fbeda.png)

From vendor/magento/module-customer-custom-attributes/Controller/Adminhtml/Customer/Attribute/Save.php:

```php
 if ($attributeId) {
                $attributeObject->load($attributeId);
                if ($attributeObject->getEntityTypeId() != $this->_getEntityType()->getId()) {
                    $this->messageManager->addError(__('You cannot edit this attribute.'));
                    $this->_getSession()->addAttributeData($data);
                    $resultRedirect->setPath('adminhtml/*/');
                    return $resultRedirect;
                }

                $data['attribute_code'] = $attributeObject->getAttributeCode();
                $data['is_user_defined'] = $attributeObject->getIsUserDefined();
                $data['frontend_input'] = $attributeObject->getFrontendInput();
                $data['is_user_defined'] = $attributeObject->getIsUserDefined();
                $data['is_system'] = $attributeObject->getIsSystem();
                if (isset($data['used_in_forms']) && is_array($data['used_in_forms'])) {
                    $data['used_in_forms'][] = 'adminhtml_customer';
                }
            } else {
                $data['backend_model'] = $this->helperData->getAttributeBackendModelByInputType(
                    $data['frontend_input']
                );
                $data['source_model'] = $this->helperData->getAttributeSourceModelByInputType($data['frontend_input']);
                $data['backend_type'] = $this->helperData->getAttributeBackendTypeByInputType($data['frontend_input']);
                $data['is_user_defined'] = 1;
                $data['is_system'] = 0;

                // add set and group info
                $data['attribute_set_id'] = $this->_getEntityType()->getDefaultAttributeSetId();
                /** @var $attrSet \Magento\Eav\Model\Entity\Attribute\Set */
                $attrSet = $this->_attrSetFactory->create();
                $data['attribute_group_id'] = $attrSet->getDefaultGroupId($data['attribute_set_id']);
                $data['used_in_forms'][] = 'adminhtml_customer';
            }
```

If there is no `attributeId` there is no `isset` or `is_array` check for `$data['used_in_forms']` so if you are creating a new attribute and do not select `Forms to Use In` you will get a fatal error. 

I believe we need something like:

```php
if (isset($data['used_in_forms']) && is_array($data['used_in_forms'])) {
    $data['used_in_forms'][] = 'adminhtml_customer';
} else {
   $data['used_in_forms'] = array('adminhtml_customer');
}
```

**Comment by magento-engcom-team** [comment]
@KernelKorn , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@KernelKorn, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
