### ISSUE TITLE
Can not finish setup:update

### ISSUE THREAD

**Issue by SKovbel** [magento/magento2#1339]
![m1867](https://cloud.githubusercontent.com/assets/813985/7989763/7fa24a76-0af4-11e5-8bd7-3559c7bdbf12.png)

**Comment by mazhalai** [comment]
@Mackovey thank you for reporting this issue. Can you please try again after clearing your `var` directory? Also, what was your previous version and what version are you upgrading to?

**Comment by Mackovey** [comment]
It is migration from beta 10 to beta11.

Tried again, clearing directory /var doesn't give any effects. Errors still present

**Comment by MaxSavich** [comment]
It looks like the issue cause is the same https://github.com/magento/magento2/issues/1405
Internal ticket MAGETWO-37862

**Comment by buskamuza** [comment]
Hi @Mackovey , unfortunately, there were schema changes in beta11 that do not allow upgrade from earlier versions. You may re-install the application, if you want to upgrade to the newer version. See details at http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-uninstall.html#instgde-install-magento-updatebeta11
If you want to use latest version `1.0.0-beta` in future, better to install it now, as it also has backwards incompatible changes and you won't be able to upgrade to this or newer version.

You can use `./bin/magento setup:uninstall` for easy uninstall.
Sorry for inconvenience.

**Comment by piotrekkaminski** [comment]
Closing as no comments from the original author.
