### ISSUE TITLE
After migrate not showng the products on frontend in 2.2.2 magento version

### ISSUE THREAD

**Issue by Sandy7022** [magento/magento2#13404]
I have migrated the data from magento version 1.9.3.7 to version 2.2.2, all data migrated successfully but products not showing under categories and catalog page list , if access the single products then it working fine.
I have done all cache,reindex,complile and other commnads but not get the success. Please help me how can I fix.

Thanks

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.
