### ISSUE TITLE
Catalog Price Rule not working when using SKU is not

### ISSUE THREAD

**Issue by jsawhitepixel** [magento/magento2#13419]
### Preconditions
1. Magento 2.1.6

### Steps to reproduce
1. Create new catalog price rule with the following settings:

If ALL of these conditions are TRUE :
SKU **is not** SOME_SKU
set 40 % discount

(SOME_SKU is a configurable product)

### Expected result
1. All products should receive 40% discount except SOME_SKU

### Actual result
1. SOME_SKU also receives 40% discount

**Comment by magento-engcom-team** [comment]
@jsawhitepixel, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jsawhitepixel** [comment]
After further investigation it looks like the configurable product is in fact excluded from the rule. 

But as the prices of configurable products are calculated based on its child products, which are not excluded in the rule, the discount will be applied.

I would however expect that a rule added to a configurable product, should be added to its child products as well.

**Comment by shaandg** [comment]
"I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@shaandg thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by shaandg** [comment]
This issue is **not reproduced** in Magento 2.2.x.
**_If you want to apply in a single simple sku of a configurable product, then you need to choose the configurable product sku with the simple product sku and it will work._**

**Comment by magento-engcom-team** [comment]
Hi @jsawhitepixel 
Thank you for your report. This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this. Otherwise you may submit Pull Request with the suggested changes.
