### ISSUE TITLE
Reindexing of catalogsearch_fulltext take almost 30 hours

### ISSUE THREAD

**Issue by minikist** [magento/magento2#13412]
### Preconditions

**Server setup:**
Apache 2.4.29
Centos 7 
PHP 7.1.10
MySQL 10.2.12-MariaDB
Varnish 5.2.1
Nginx 1.12.2

**Server specs:**
24 threads
64g memory
with ssd

**magento 2.2.2 setup:**
website 1x
store and store view: 64x
simpel products 68.000x
advanced prducts 20x
attributes: 2000x
attributes sets 100x
 

### Steps to reproduce

1. setup as above and update to magento 2.2.2 run reindex for catalogsearch_fulltext. 
2. 
3. 

### Expected result

1. Reindex of catalogsearch_fulltext should be done in less then hour.
The other indexers take less then 10 minutes after tweaking the batchsizecaclulator.

### Actual result

1. take 1300 sec each store. so total of 23 hours

**Comment by AirmanAJK** [comment]
Just a suggestion (not a solution), but have you considered limiting which attributes are searchable? It sounds like excluding ones you don't really care about could actually save quite a bit of time if you're currently including them. For example, we don't even include the long description in our index since the short description is adequate and has all the relevant terms.

**Comment by jesusfreak3** [comment]
I am experiencing similar issues at PHP 7.0 Magento 2.2.2, MySQL 5.7.  Indexing is taking hours, when they used to take minutes.  Because of this I am getting deadlocks and other annoying situations.

**Comment by magento-engcom-team** [comment]
@minikist, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mslabko** [comment]
Hi @minikist , in [2.2-develop ](https://github.com/magento/magento2/commit/124d8fed8161ea762d683461e6008ffdd40e265d) available parallelization mechanism for catalog search indexer which allow to run indexation per store in forked process.

For run in 4 parallel processes, you can use the following command:
`MAGE_INDEXER_THREADS_COUNT=4 php -f bin/magento indexer:reindex catalogsearch_fulltext`

**Comment by orbitrod** [comment]
@minikist did you try @mslabko's suggestion to index catalogsearch_fulltext with his 4 parallel process command?  Did it work?
