### ISSUE TITLE
Option Save unique images per attribute for each SKU - does not display previously inserted images

### ISSUE THREAD

**Issue by danijelkusic** [magento/magento2#13418]
Preconditions
When I create a configurable product and upload images for each attribute (Save unique images per attribute for each SKU) and save.
When I return, I do not see the image I previously inserted. All is empty
![m2 2 2](https://user-images.githubusercontent.com/35351307/35535646-82958a98-0544-11e8-9f50-3dfc12a685e2.jpg)

Magento 2.2.2
PHP 7.1.13
SQL 5.5.32
System Linux

**Comment by magento-engcom-team** [comment]
@danijelkusic, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by danijelkusic** [comment]
No. With these bonds...

I have two attributes. When I choose the first attribute and enter all the photos (Step 1), then I select another attribute and enter the remaining photos (Step 2), and when I return to the first attribute, all those photos from the first attribute disappear and if i were to save in that case, only images from another attribute (Step 2) would be saved.

![magento](https://user-images.githubusercontent.com/35351307/35709540-4bd47be2-07b3-11e8-8eb0-c13e94d22395.jpg)

**Comment by magento-engcom-team** [comment]
@danijelkusic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@danijelkusic, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
