### ISSUE TITLE
Delete one value from Select type custom option and it's deleted all other custom option values which are bottom of that custom option.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#13425]
We are facing problem on custom option, when we have more then 1 select type custom options for a product, if we delete a value from one select type custom option, all the values from other custom options are getting deleted which are bottom of that custom options.

### Preconditions

1. Magento Version 2.2.X
2. Multiple Custom options with type (Dropdown, multiple select, Radio Button, Check Box)

### Steps to reproduce

1.  Create a new product or edit existing product Add multiple Custom options having the type (Dropdown, multiple select, Radio Button, CheckBox)
2.  Save the Product
3. Open the product, delete one value from first select type custom option.
4. save the product
5. Check all other custom options values are deleted which are bottom of that custom options.
6. We have attached video. So, please check that for more information.
[Custom_Option_value_Delete.zip](https://github.com/magento/magento2/files/1677232/Custom_Option_value_Delete.zip)

### Expected result

1. It should delete only that option value and save all the options without being recreated and having all the option values there.

### Actual result

1. Deletes all the options values which are bottom of that custom options.

**Comment by magento-engcom-team** [comment]
@emiprotech, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mayankzalavadia** [comment]
I have a solution for this issue. Tomorrow I'll create a pull request.

**Comment by ihor-sviziev** [comment]
This issue was fixed in 2.2-develop branch with following commits https://github.com/magento/magento2/commit/ff422002cd2d977c3b10ac512c557f58e1cba5c6 + https://github.com/magento/magento2/commit/aa7da3084d17f27b4f44c8b816a1ffa4c3666682 and already available in release 2.2.4.

**Comment by ihor-sviziev** [comment]
This issue was also fixed in commit https://github.com/magento/magento2/commit/14a4df89ab6aebec1a669ecf99aac50a8a07e553 in 2.3-develop branch and will be available in upcoming 2.3 release.
