### ISSUE TITLE
getStatusLabel in OrderInterface

### ISSUE THREAD

**Issue by Jimgitsit** [magento/magento2#13420]
Please add the function getStatusLabel in Magento\Sales\Api\Data\OrderInterface.

Magento\Sales\Api\OrderRepositoryInterface::get returns an OrderInterface.
$order = $this->orderRepository->get($orderId);

The only way to get the status label from there is to load the order as in:
$this->orderFactory->create()->loadByIncrementId($order->getIncrementId())->getStatusLabel()

**Comment by magento-engcom-team** [comment]
@Jimgitsit, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by Jimgitsit** [comment]
This was meant as an enhancement request, not a bug report. Every other property of an order can be obtained from the OrderInterface. Why not statusLabel?

**Comment by magento-engcom-team** [comment]
Hi @Jimgitsit 
> The only way to get the status label from there is to load the order as in:
> $this->orderFactory->create()->loadByIncrementId($order->getIncrementId())->getStatusLabel()

Looks like there is more suitable way of resolving order status label from order:
`\Magento\Sales\Model\Order\Config::getStatusLabel` takes status code as a parameter and returns status label. Status code itself is present in `OrderInterface`.

This indeed seems to be a desired Magento behavior and not a bug.
Closing the ticket as the GitHub issue tracker is intended for Magento Core technical issues only.
