### ISSUE TITLE
All bundle Items can't be removed from bundle product, but no error returned

### ISSUE THREAD

**Issue by Stepa4man** [magento/magento2#13421]
After creating bundle product and adding some items there - it's impossible to remove all items and option.
The case there is that you can't remove last option from product - bundle product can't exist without options, It's ok, but why no error returned?

### Preconditions
1. Apache2, MySQL5.7, Ubuntu 16.04
2. Magento CE 2.2.2

### Steps to reproduce
1. Create bundle product
2. Add option and assign couple products there
3. Try to remove all products from last option
4. Try to remove last option completely (it should be last existing option)

### Expected result
1. Returning error that is impossible to save bundle product without options

### Actual result
1. Product successfully saved - no errors

**Comment by magento-engcom-team** [comment]
@Stepa4man, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by vasylmalanka** [comment]
After a discussion with Magento community developer, I found this issue meaningless - a customer should have an ability to save a bundle product without bundle options. It will not be visible in the catalog without options anyway. Also, there are a lot of fixtures already written with bundle product saving without options.

**Comment by serzhik** [comment]
@vasylmalanka can you show notice, that bundle product don't have options?

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. Create bundle product
2. Try to remove all products 
3. Click on Save
4. Enter price and quantity
5. Click on Save

**Result**
Product successfully saved - no errors
![Screenshot_42](https://user-images.githubusercontent.com/51681435/71513673-fb5a4980-28a3-11ea-9787-5047ac46a544.png)

**Note**
If a Configurable product will be saved without options it will change the type to a simple product.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by bertterheide** [comment]
I'm running Magento 2.4.2-p1 and I ran into this issue today. It seems to be caused by `Magento\Bundle\Model\Product\SaveHandler::execute`. This method does not run when the bundle product options are empty. Removing the ` || empty($bundleProductOptions)` check fixes the issue. Could you please remove this check?
