### ISSUE TITLE
 magento-composer-installer : Cleanup code?

### ISSUE THREAD

**Issue by tobi-pb** [magento/magento2#1343]
Hey Guys,

I take look into your fork of magento-composer-installer and there a some not supported functions, unused code and so on. It is quite hard to extend or improve this. 

(I was planning to make symlink deploy strategy working with magento2)

Could I cleanup this and make a pull request? Or is still somebody else working on this?
Would be bad to do the job and nobody accept pull request :)

Thanks for feedback,

Tobi

**Comment by Vinai** [comment]
Cross reference to issue #1206 which will hopefully render the Magento Composer Installer moot.

**Comment by tanya-soroka** [comment]
Hello @tobi-pb 
It is really good idea, and we will appreciate your help and contribution.
Please submit a pull request with your clean up code, so we will review and can merge it to the Magento repository.

**Comment by tobi-pb** [comment]
Oh sorry, i didn't read this notification. I would write a little concept and start working after discussing it :-)
