### ISSUE TITLE
[500] Internal Server Error after upgrade magento from 2.1.11 to 2.2.2

### ISSUE THREAD

**Issue by Sylvesterx1** [magento/magento2#13431]
### Prec
1. Upgrade magento 2.1.11 to 2.2.2 via Composer
2.  System Debian 9. 

### Steps to reproduce

1. Update magento SSH to 2.2.2 via command line:
```
composer require magento/product-community-edition 2.2.2 --no-update
composer update
rm -rf var/cache/*
rm -rf var/page_cache/*
rm -rf var/generation/*
bin/magento setup:upgrade
bin/magento cache:clean
bin/magento cache:flush
```

### Expected result

1.  The update has been successful, my magento version is now  2.2.2 - OK

### Actual result

1. Now that I'm viewing my page I see a error code:

```
[500] Internal Server Error : Wewnętrzny błąd serwera
--
  | Wewnętrzny błąd serwera (np. zawieszenie programu CGI) lub błąd konfiguracji. Proszę skontaktować się z administratorem webmaster@brandswearxv.nazwa.pl i poinformować go o czasie pojawienia się błędu wraz z podaniem innych informacji, które mogły być przyczyną błędu.
  |  
  | The server encountered an internal error or misconfiguration and was unable to complete your request. Please contact the server administratorwebmaster@brandswearxv.nazwa.pl and inform them of the time the error occured and anything you might have done that may have caused the error.
```
LOGS:
`[2018-01-30 17:54:27] main.CRITICAL: Asymmetric transaction rollback. {"exception":"[object] (Exception(code: 0): Asymmetric transaction rollback. at /home/brandswearxv/ftp/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:316)"} []`

**Comment by RahulBhut21** [comment]
solutions:
(1)reinstall magento because of database not setup well.
(2)rename root folder's .htaccess file. then restart apache and execute the project.

**Comment by Sylvesterx1** [comment]
Rahul, thanks. I rename htaccess file and now all works!
