### ISSUE TITLE
Checkout new step with mixin does not allow billing address to be filled

### ISSUE THREAD

**Issue by natsoman** [magento/magento2#13442]
### Preconditions
Magento version 2.1.7
PHP version 7.0.10
Used browser: Google Chrome

### Steps to reproduce
Follow this documentation to add a new step at the beginning of the checkout: http://devdocs.magento.com/guides/v2.1/howdoi/checkout/checkout_new_step.html
Also, I created mixins for payment and shipping steps.

### Expected result
A new step is added before "Shipping Address". At the final step "Review and Payment" billing address should be checked and filled.

### Actual result
At the final step "Review and Payment" billing address is unchecked and empty.
![billing-address](https://user-images.githubusercontent.com/22493050/35616616-7cd76f00-067e-11e8-83f9-6e3842ada1f8.png)

Billing address work as expected if i don't use mixin.

**Comment by magento-engcom-team** [comment]
@natsoGR, thank you for your report.
This issue already fixed in 2.2.2 version.
