### ISSUE TITLE
Add 'Attribute Id' to grid "Product Attributes"?

### ISSUE THREAD

**Issue by SKovbel** [magento/magento2#1344]
Small question, could you add column 'Attribute Id' to grid "Product Attributes" in backend?

Column very useful for production site, its support and developing
when you want to sort attributes by last created or separate by new and system, sync,.
Alphabetic sorting by code not the same.

Sometimes also lacks `Attribute Set Id` from "Product Templates" :)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-Attribute-Id-to-grid-quot-Product-Attributes-quot/idi-p/45458).
