### ISSUE TITLE
Magento requests a wrong file for the jQuery in the administration page

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#13458]
### Preconditions

Ubuntu, Standard LAMP (Apache, MySQL, ....)
Magento ver. 2.1.9 - Clean setup by command line
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper

### Magento Store Configuration

The configuration of the magento store is standard. A fresh install of the 2.1.9 with luma theme.

## Bug Issue 

When I try to login in the administration panel the jQuery is not loaded. Checking the URL I have seen that Magento requires: 

     /shop/pub/static/version1517477534/adminhtml/Magento/backend/en_US/jquery/jquery-ui-1.9.2.js

but the request is rewritten in:

    /shop/pub/static.php?resource=adminhtml/Magento/backend/it_IT/jquery/jquery-ui-1.9.js

Pay attention about the file name. 

- /jquery-ui-1.9.2.js (this is requested)
- /jquery-ui-1.9.js (but it looking for this one)

### Expected result

Magento must request the right jQuery file shop/lib/web/jquery/jquery-ui-1.9.2.js in the static directory

### Actual result

Wrong file is loaded.

thanks

![selezione_111](https://user-images.githubusercontent.com/1553035/35676642-c64c2bf2-074c-11e8-8815-66915cb62114.png)

**Comment by orlangur** [comment]
Closing as duplicate in favor of https://github.com/magento/magento2/issues/13518 which passed G1.
