### ISSUE TITLE
Bundled product selection id's can overwrite each other, causing selections to go missing

### ISSUE THREAD

**Issue by ryanpalmerweb** [magento/magento2#13457]
### Preconditions
1. Magento 2.2.2
2. PHP version 7.0.22 (shouldn't affect this bug)

### Steps to reproduce
1. Create a fresh installation of Magento without any sample data or previous use.
2. Create 4 simple products - their configuration is not important but must be enabled/in stock.
It is essential that these products are the first added to the new installation, or the bug will not be reproduced using the following instructions
3. Begin creating a bundled product :-
a) Create a set of bundled options with the "checkbox" type, add the first 3 simple products as options with a default quantity of 1 and "is default" ticked for each one
b) Create a set of bundled options with the "dropdown" type, add the fourth simple product as an option with a default quantity of 1.
4. Save the bundled product
5. Visit the product page on the front end.
6. Check all of the boxes, and then select the first product from the dropdown.
7. Add to cart

### Expected result
1. A cart item should appear with 4 bundled items - 3 from the checkboxes and 1 from the dropdown

![screen shot 2018-02-01 at 11 25 41](https://user-images.githubusercontent.com/7669058/35676248-fdc04eb0-0742-11e8-9362-7d99f10c1852.png)

### Actual result
1. The cart will be missing one of the items that were in the checkboxes

![screen shot 2018-02-01 at 11 26 30](https://user-images.githubusercontent.com/7669058/35676251-fe26a17e-0742-11e8-9370-16e7b0da2f69.png)

### What happened?
The function multiToFlatArray in vendor/magento/module-bundle/Model/Product/Type.php flattens all of the options into an array, so that a flat list of product IDs has essentially been created

There is a risk of array keys clashing and being overwritten, as the function does not check to see if an array key has been used before overwriting it, and merges multiple arrays which have different methods of sequencing the keys.

This is far more likely to occur in a fresh installation because the IDs started at "1" for both the overall options, and the items which are part of the checkbox options.

I created a temporary patch for this but am unsure of the knock-on consequences of this implementation

Original code : 
```
    private function multiToFlatArray(array $array)
    {
        $flatArray = [];
        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $flatArray = array_merge($flatArray, $this->multiToFlatArray($value));
            } else {
                $flatArray[$key] = $value;
            }
        }

        return $flatArray;
    }
```

This patch avoids the issue
```
    private function multiToFlatArray(array $array)
    {
        $flatArray = [];
        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $flatArray = array_merge($flatArray, $this->multiToFlatArray($value));
            } else {
                if(!array_key_exists($key,$flatArray)) {
                    $flatArray[$key] = $value;
                } else {
                    //Add a new key to the array to avoid overwrite
                    $max = max(array_keys($flatArray));
                    $flatArray[$max+1] = $value;
                }
            }
        }

        return $flatArray;
    }
```

**Comment by magento-engcom-team** [comment]
@ryanpalmerweb, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ryanpalmerweb** [comment]
For anyone reading this, my suggested fix has knock-on pricing issues so don't use it.

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**
**Steps to reproduce:**

1. Create a fresh installation of Magento without any sample data or previous use.
2. Create 4 simple products - their configuration is not important but must be enabled/in stock.
    It is essential that these products are the first added to the new installation, or the bug will not be reproduced using the following instructions
3. Begin creating a bundled product :-
    a) Create a set of bundled options with the "checkbox" type, add the first 3 simple products as options with a default quantity of 1 and "is default" ticked for each one
    b) Create a set of bundled options with the "dropdown" type, add the fourth simple product as an option with a default quantity of 1.
4. Save the bundled product
5. Visit the product page on the front end.
6. Check all of the boxes, and then select the first product from the dropdown.
7. Add to cart

**Result**
A cart item is appear with 4 bundled items - 3 from the checkboxes and 1 from the drop-down
![Screenshot_43](https://user-images.githubusercontent.com/51681435/71573919-d9083c00-2aee-11ea-80c8-7f29e93499a8.png)

**Note**
The code below is missing from the `vendor/magento/module-bundle/Model/Product/Type.php` 
(In 2.3.3 and 2.4 too)
```
    private function multiToFlatArray(array $array)
    {
        $flatArray = [];
        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $flatArray = array_merge($flatArray, $this->multiToFlatArray($value));
            } else {
                $flatArray[$key] = $value;
            }
        }

        return $flatArray;
    }
```
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
