### ISSUE TITLE
Uncaught ReferenceError: Unable to process binding "if: function (){return 

### ISSUE THREAD

**Issue by ricatt** [magento/magento2#13451]
I am currently using Apache 2, PHP 7.2 and Magento 2.2.2. My js-installation is on version 4.2.6 and I am sitting on the latest Elementary OS.
While trying to edit a product through the admin-site, I get this issue from time to time:

I have seen other people having similar issues, albeit not with the label.

```
VM34516 knockout.js:3012 Uncaught ReferenceError: Unable to process binding "if: function (){return label }"
Message: label is not defined
    at if (eval at createBindingsStringEvaluator (VM34516 knockout.js:2624), <anonymous>:3:55)
    at ko.computed.disposeWhenNodeIsRemoved (VM34516 knockout.js:3989)
    at evaluateImmediate (VM34516 knockout.js:1737)
    at Object.ko.computed.ko.dependentObservable (VM34516 knockout.js:1946)
    at init (VM34516 knockout.js:3988)
    at VM34516 knockout.js:2989
    at Object.ignore (VM34516 knockout.js:1249)
    at VM34516 knockout.js:2988
    at Object.arrayForEach (VM34516 knockout.js:151)
    at applyBindingsToNodeInternal (VM34516 knockout.js:2974)
```

**Comment by orlangur** [comment]
> PHP 7.2

Is this information correct?

**Comment by ricatt** [comment]
Sorry, was a bit of a typo.
PHP 7.1.13, to be more precise.

**Comment by cralls** [comment]
Seeing the same issue here, was there ever a solution for this?

**Comment by Rutvee123** [comment]
i also have same issue..Has anyone found the solution?

**Comment by nghitrum** [comment]
I have the same issue when I go to Admin -> Catalog --> Categories. @ricatt Did you manage to fix this bug?

**Comment by ghost** [comment]
![Screenshot from 2019-06-12 10-07-33](https://user-images.githubusercontent.com/24873505/59323913-55296680-8cfa-11e9-99b8-d6638ce0969d.png)
This error occurs while editing product, Please help!!.

**Comment by BergMedia** [comment]
Please search for an form field in your xml config files that not define the label.
In your situation look in the /vendor/magento/module-catalog/view/ui_component/ folder in the right xml file. And keep in Mind if there any thirdparty extension that overwrite the ui_compoment?
 
Example:
 ` <field name="excel_import">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="dataType" xsi:type="string">string</item>
                    <item name="source" xsi:type="string">xxx_xxx_import_form_data_source</item>
                 </item>
            </argument>
        </field>`

Search for Missing item "label"
          `<item name="label" xsi:type="string" translate="true">Excel File</item>`

I hope, it will be help to find the failure

**Comment by karlsminton** [comment]
In addition to this, also check that the fieldset has it's labels set correctly

**Comment by maheshwaran-1343** [comment]
> 

Is the issue fixed?. If so , please share the details
