### ISSUE TITLE
magento2 CE 2.2.1 can not find facebook oper graph meta:og tags in products page head 

### ISSUE THREAD

**Issue by CandyChristina** [magento/magento2#13454]
### Preconditions

1. Apache: httpd-2.4.29
2. MySQL: mysql-5.6.38
3. PHP: php-7.0.26
4. magento CE 2.2.1

### Steps to reproduce

1. the facebook open graph tags, such as meta property="og:image" was missing
2. the blocks "head.additional" seem to be override or remove, but i can not find what make it.
3. what configuration should i start to check and solve this problem ?  

### Expected result

1.  the facebook open graph tags, such as meta property="og:image" should appear in the product page head section

### Actual result

1.  the facebook open graph tags, such as meta property="og:image"  was missing, whatever what i do ....

thank you, guys

**Comment by orlangur** [comment]
Hi @CandyChristina, am I understand you right that you observe such undesired behavior on a customized Magento instance and not a clean Magento installation?

**Comment by CandyChristina** [comment]
thank you for attention, i found and solved it finally.....
in order to remove the compare.sidebar, i place this code in "vendor/magento/module-catalog/view/frontend/layout/default.xml"
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="catalog.compare.sidebar" remove="true"/>
    </body>
</page>

it case all head section was empty .......including the facebook open graph tags ....
after i remove the customized code, the facebook open graph tags appeared again !
thank you and have a nice weekend

**Comment by CandyChristina** [comment]
following customized to remove the compare.sidebar 
**<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="catalog.compare.sidebar" remove="true"/>
    </body>
</page>**

**Comment by CandyChristina** [comment]
following customized to remove the compare.sidebar
> <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
>     <body>
>         <referenceBlock name="catalog.compare.sidebar" remove="true"/>
>     </body>
> </page>

**Comment by CandyChristina** [comment]
why i can paste the customized code here ?
-------<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ----------xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"------>
-----    <body>
----        <referenceBlock name="catalog.compare.sidebar" remove="true"/>
---    </body>
----</page>

**Comment by orlangur** [comment]
@CandyChristina please check https://guides.github.com/features/mastering-markdown/, the Code section.

```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ----------xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"
```
