### ISSUE TITLE
Upgrading magento 2.1.11 to 2.2.2 Issue

### ISSUE THREAD

**Issue by jayanta88** [magento/magento2#13456]
**Steps I did:**
composer require magento/product-community-edition 2.2.2 --no-update
composer update

**Results:**
Problem 1
    - magento/module-wishlist-sample-data 100.1.0 requires magento/module-wishlist 100.1.* -> satisfiable by magento/module-wishlist[100.1.7, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6].
    - magento/module-wishlist-sample-data 100.1.0 requires magento/module-wishlist 100.1.* -> satisfiable by magento/module-wishlist[100.1.7, 100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.7].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.0-rc1].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.0-rc2].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.0-rc3].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.0].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.1].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.2].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.3].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.4].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.5].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.6].
    - Can only install one of: magento/module-wishlist[101.0.1, 100.1.7].
    - magento/product-community-edition 2.2.2 requires magento/module-wishlist 101.0.1 -> satisfiable by magento/module-wishlist[101.0.1].
    - Installation request for magento/product-community-edition 2.2.2 -> satisfiable by magento/product-community-edition[2.2.2].
    - Installation request for magento/module-wishlist-sample-data 100.1.0 -> satisfiable by magento/module-wishlist-sample-data[100.1.0].

Please let me know if I missed anything.

**Comment by orlangur** [comment]
You need to upgrade sample packages together with main package as described in documentation: http://devdocs.magento.com/guides/v2.0/comp-mgr/cli/cli-rc1-samp.html

Please check https://magento.stackexchange.com/a/201240 for more details.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. Also, googling observed error is usually helpful.

**Comment by jayanta88** [comment]
Thanks for your reply. I'll follow it sure.
