### ISSUE TITLE
 doctrine/instantiator forcing use of PHP 7.1

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#13461]
M2 should be able to run with PHP 7.0. However doctrine/instantiator is included in M2 core distribution and this now requires PHP 7.1. So in effect M2 sites must now use PHP 7.1 and the system requirements are no longer valid. This is causing issues with other modules that need 7.0. 

Is there simple way to go back to an earlier doctrine/instantiator version that worked with 7.0?

**Comment by magento-engcom-team** [comment]
Hello @adamlavery.  The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Thank You.

**Comment by magento-engcom-team** [comment]
@adamlavery, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by adamlavery** [comment]
Well I'd say this is a technical issue. If M2 is to support PHP 7.0 then all constituent components that it includes in the core must support 7.0 too. This means Magento should not be using doctrine/instantiator v1.0.3+ as this restricted support to 7.1 only.

As you're using composer to manage dependencies, then surely the composer config should ensure compatibility with the PHP versions that you state are supported at http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html. 

No?

**Comment by alberts-s** [comment]
I'd also say that this is a technical issue which must be resolved in Magento 2 composer requirements.
As it currently stands:
- Magento core modules require php ~5.6.5|7.0.2|7.0.4|~7.0.6
- Doctrine which is included by Magento requires  php ^7.1

The requirements are impossible to fulfil, this is not a matter of local configuration.

**Comment by hostep** [comment]
I don't believe this is an issue. When installing Magento with PHP 7.0, you'll get `doctrine/instantiator` version 1.0.5 which has [no requirements](https://github.com/doctrine/instantiator/blob/1.0.5/composer.json) on PHP 7.1 or higher.
The [requirement](https://github.com/doctrine/instantiator/blob/1.1.0/composer.json) was only changed in version 1.1.0. In theory, when installing Magento with PHP 7.1, you'll get version 1.1.0 (untested)

So this isn't an actual issue as far as I can see, but please, enlighten me when I'm mistaken here.
