### ISSUE TITLE
OAuth documentation should be updated (oauth_consumer_key_secret vs oauth_consumer_secret in post field)

### ISSUE THREAD

**Issue by nenad82** [magento/magento2#13467]
### Preconditions

Magento ver. 2.2.0
 

### Steps to reproduce

on integration activation Magento sends post request,

### Expected result

oauth consumer key secret should be in oauth_consumer_key_secret post field (as stated [here](http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html#activate))

### Actual result

oauth consumer key secret is in post field named oauth_consumer_secret (in php example is ok, though)

**Comment by magento-engcom-team** [comment]
@nenad82, thank you for your report.
We've acknowledged the issue and added to our backlog.
