### ISSUE TITLE
Magento backend style is broken 

### ISSUE THREAD

**Issue by ahmadalkaid** [magento/magento2#1346]
Hi Guys,
After install magento2 in my server, It really went good. But after I login to my Admin panel the style seems not working and the buttons is disabled . Here is a screen shoot ...    
![magento admin 2015-06-07 16-49-22](https://cloud.githubusercontent.com/assets/9692159/8024245/c4b921dc-0d35-11e5-804d-07077aeb0248.png)

**Comment by godban** [comment]
Hello @ahmadalkaid

Look like cache issue. Please try to clean up browser cache.

**Comment by ahmadalkaid** [comment]
Hi @godban 
Thanks for you replay, but is this the new look for Magento2. Indeed the buttons issue it was solved, but the style still as it is, so is that's how  Magento2 going to look like ??

**Comment by villageseo** [comment]
Hi @ahmadalkaid 

Did you try to clean /var and /pub/static folders also?

**Comment by ahmadalkaid** [comment]
Hi @villageseo,
Yes I did, and it worked, But is there any issue with the style ??

**Comment by villageseo** [comment]
Hi @ahmadalkaid, 

Current dashboard view: 
![dashboard](https://cloud.githubusercontent.com/assets/2562553/8160494/ceb24378-1378-11e5-97d1-31841f3709c9.jpg)

I don`t see any issue with the style. Could you explain please your concerns?  

Kind Regards, 
Oleg

**Comment by ahmadalkaid** [comment]
Hi @villageseo 
Thank you that solve my concerns.
Best,
-kaid

**Comment by vpelipenko** [comment]
@ahmadalkaid, can we close this issue?
