### ISSUE TITLE
setup:install fails with empty database

### ISSUE THREAD

**Issue by kassner** [magento/magento2#1347]
Hi,

The command `bin/magento setup:install` fails when running integration tests directly with `phpunit -c dev/tests/integration`:

    PHP Fatal error:  Cannot instantiate interface Magento\Framework\Config\CacheInterface in /var/www/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php on line 75

This should work running directly from PHPUnit instead of `bin/magento dev:tests:run integration`? Because the latter does not allow to specify which tests I want to run.

I'm using 0.74.0-beta12 and the dev:tests:run is working as expected, but running from PHPUnit works only after I ran the entire suite at least once.

Thanks!

**Comment by mazhalai** [comment]
@kassner We are unable to reproduce this problem. Can you tell us steps to reproduce it? Can you try  again after deleting the `dev/tests/integration/tmp` folder.

**Comment by kassner** [comment]
@mazhalai can you try using [this Dockerfile](https://gist.github.com/kassner/31cc4bddc6c8791b0f9e)?

After build, just cd to `/var/www/magento2-0.74.0-beta12` and run `vendor/bin/phpunit -c dev/tests/integration/`

**Comment by mazhalai** [comment]
@kassner why are you stopping mysqld `service mysql stop`? https://gist.github.com/kassner/31cc4bddc6c8791b0f9e#file-magento-install-sh-L14

**Comment by kassner** [comment]
@mazhalai

This file is used only for build the Docker image. I've added a readme with steps to reproduce.

**Comment by mazhalai** [comment]
Thank you @kassner. We have created ticket MAGETWO-38482 to fix this issue.

**Comment by vpelipenko** [comment]
@kassner, this issue is fixed and available in 0.74.0-beta14. Please, confirm, that it works for you.

**Comment by kassner** [comment]
@vpelipenko looks good now, thank you!
