### ISSUE TITLE
Navigation menu does not show up in home page, but does in Login page.

### ISSUE THREAD

**Issue by SahakTadevosyan** [magento/magento2#13475]
### Preconditions

1.  Version: Magento 2.2.2
2.  Using the luma theme 

### Steps to reproduce

1. Updated Magneto 2.1.10 to 2.2.2
2.  run setup:update and static:content-deploy
3. Admin panel works fine
4. Navigated to frontend
### Expected result

1.  Navigation to work in every page 

### Actual result

 ![image](https://user-images.githubusercontent.com/21958031/35740407-2579e31a-084e-11e8-9b8c-2a8ffdc4d67a.png)

in home page there is no navigation.

![image](https://user-images.githubusercontent.com/21958031/35740473-5dac67da-084e-11e8-8e1c-0ae5cf6343a4.png)

 in customer login page navigation exists.

**Comment by SahakTadevosyan** [comment]
if anyone has encountered with this issue, please try to help me. It is urgent

**Comment by magento-engcom-team** [comment]
Hello @SahakTadevosyan. Thanks for reporting. Unfortunately we can not reproduce Your issue. Could You please answer us several questions. So:
1. Did You  install Your 2.1.10 version via composer or from GitHub?
2. If it was via composer had You changed and updated Your composer.json file before You fulfilled setup:upgrade and the later commands?

**Comment by SahakTadevosyan** [comment]
Hallo @magento-engcom-team  thank you for your response.
1. There was installed the MGS theme here I changed it to luma and updated via composer.
2. no I did not change the composer file.

**Comment by magento-engcom-team** [comment]
Ok. Then please try to fulfill the following.
1. in Your 2.1.10 project find the file called "composer.json". There You are supposed to see something like "..."require": {
        "magento/product-community-edition": "2.1.10", .....". Here You should change 2.1.10 to 2.2.2 (to the version You want to upgrade).
2. Run "composer update" command.
3. Run "php bin/magento setup:upgrade". 
4. If necessary or for any case it shouldn't harm run "php bin/magento setup:di:compile" and then "php bin/magento setup:static-content:deploy".

**Comment by SahakTadevosyan** [comment]
I have already done this steps my magento version is 2.2.2 my problem is that the navigation menu does not show up in home page and some other pages but for example it shows in login or sign up page.

**Comment by SahakTadevosyan** [comment]
@magento-engcom-team any other idea where can I find the issue ?

**Comment by magento-engcom-team** [comment]
Please @SahakTadevosyan, clarify You changed the theme before upgrade from 2.1.10 to 2.2.2 or after?

**Comment by SahakTadevosyan** [comment]
@magento-engcom-team When my version was 2.1.10 I changed the them to default and disabled all the modules related to the theme. With the luma theme the menu disappeared. So I decided to update the magneto to 2.2.2 but the error is stile there.

**Comment by magento-engcom-team** [comment]
You see @SahakTadevosyan obviously the issue relates to the third party extensions as on the clear instance of Magento 2.1.10 it is not reproducible. So we recommend You to refer to those extensions developers. Additionally we do not suggest You anything but we'd like You to know that many times module disabling is not enough to really stop it from working. Often themes templates keep rendering further, causing wrong results, and so the modules have to be deleted physically and not just disabled. But please consider once more we do not urge You or suggest You to do that. The best You can do is to look for an advice from those modules developers.

**Comment by magento-engcom-team** [comment]
@SahakTadevosyan, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by krisdante** [comment]
I can reproduce this. This is strange.
When I go via Varnish it works, when I access web server directly, navbar is missing. 
I am using pure luma. Magento 2.2.5.

**Comment by siliconrockstar** [comment]
Same issue on fresh install of 2.2.6. No varnish in play.

**Comment by LiamKarlMitchell** [comment]
Fresh install of 2.2.5 no main menu.
Developer mode and static-content-deployed -f.

**Comment by seattletechworks** [comment]
I also experienced this issue recently with Magento 2.3.2 using Luma theme.

This is a duplicate issue, please refer to https://github.com/magento/magento2/issues/3421

It occurs when Varnish is enabled.

**Comment by livecandy** [comment]
Maybe your "Full Page Cache" choosed "Varnish Cache (Recommended)".
I change it to "Built-in Cache" and fixed this issue, you can try it.

STORES->Configuration->ADVANCED->System->Full Page Cache->Caching Application (choose "Built-in Cache")
