### ISSUE TITLE
Good afternoon, after i configure my store to show the paths to debug, the combo with options about which store configure, that combo doesnt apperar again, what could happen?

### ISSUE THREAD

**Issue by MaiconUnzer** [magento/magento2#13488]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by orlangur** [comment]
Hello @MaiconUnzer, GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
