### ISSUE TITLE
Error: magento/product-community-edition 2.2.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.

### ISSUE THREAD

**Issue by ahmedzainsalem** [magento/magento2#13483]
### Preconditions
Magento CLI version 2.1.2
PHP PHP 7.0.27
MySQL Ver 14.14

### Steps to reproduce

1. Edit composer.json "magento/product-community-edition": from "2.2" to "2.2.0"
2. composer update
 

### Actual result

Problem 1
    - Installation request for magento/product-community-edition 2.2 -> satisfiable by magento/product-community-edition[2.2.0].
    - magento/product-community-edition 2.2.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.

**Comment by orlangur** [comment]
@ahmedzainsalem, so? You need to install and enable `gd` extension as defined in https://github.com/magento/magento2/blob/2.2-develop/composer.json#L57.

**Comment by ahmedzainsalem** [comment]
@orlangur thank you for your replay, This fix worked for me.

**Comment by orlangur** [comment]
Glad to hear, @ahmedzainsalem! Basically that's how Composer is supposed to work telling which necessary components are missing in your environment.
