### ISSUE TITLE
Method getUrl in Magento\Catalog\Model\Product\Attribute\Frontend returns image url with double slash

### ISSUE THREAD

**Issue by igortregub** [magento/magento2#13497]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Try to get product image via method getUrl from class Magento\Catalog\Model\Product\Attribute\Frontend

### Expected result

1. returns image url without double slash 

### Actual result

1. will be returned image with double slash
![screen shot 2018-02-05 at 12 37 04 pm 2018-02-05 13-25-55](https://user-images.githubusercontent.com/6198012/35802297-3a4f3098-0a78-11e8-9532-6ee31c7a1d22.png)

I think it happens because images have in method getUrl variable $image image path starts from slash.
I here is sample how issue could be fixed: https://github.com/magento/magento2/pull/13498

**Comment by magento-engcom-team** [comment]
@igortregub, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ihor-sviziev** [comment]
Hi @igortregub. Thank you for your report.
The issue has been fixed in https://github.com/magento/magento2/pull/13498 by @igortregub in 2.2-develop branch

Related commit(s):
- 220ad974a2f440c428a15c87a861483b83a23154

The fix will be available with the upcoming 2.2.4 release.
