### ISSUE TITLE
Magento2 does not respect translate value of the pdf.xml

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#13496]
Magento version 2.2.2

In [vendor/magento/module-sales/etc/pdf.xsd](https://github.com/magento/magento2/blob/607763e65989bdbadc26b1b4019065765f3d6b46/app/code/Magento/Sales/etc/pdf.xsd#L85) following schema has been defined for total's Title: 

```
   <xs:complexType name="totalTitleType">
        <xs:simpleContent>
            <xs:extension base="nonEmptyString">
                <xs:attribute name="translate" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
```

As we can see in above XML, "translate" is accepted as a boolean value by Magento. So it should be able to accept true/false. 

Now, in pdf.xml when the code is as below

```
    <total name="my_custom_total">
            <title translate="false">My Custom Total</title>
            <source_field>my_custom_total</source_field>
            <font_size>7</font_size>
            <display_zero>true</display_zero>
            <sort_order>100</sort_order>
     </total>
```

It should not  translate the title which is "My Custom Total" because the translate attribute has been set to false here. But, in this case it will anyway translate my string based on the translation available in the i18n CSV file corresponding to order's store. This should not happen. Ideally, if and when translate is set to false, it should not translate my string. The problem is in [\Magento\Sales\Model\Order\Pdf\Total\DefaultTotal::getTotalsForDisplay](https://github.com/magento/magento2/blob/607763e65989bdbadc26b1b4019065765f3d6b46/app/code/Magento/Sales/Model/Order/Pdf/Total/DefaultTotal.php#L72): 
`$title = __($this->getTitle());`

This forcefully translates the string and bypasses the translate attribute's value.

So when the expected output in PDF for an Arabic store should be 

My Custom Value: AED 230.00

The actual output is:
translated string:AED 230.00

which is incorrect.

I get the same result for when translate=true, translate=false and when there is no translate attribute set. So basically magento is simply ignoring the translate attribute's value and forcefully translating the string. This issue can be reproduced in all Community versions of magento2 with any OS.

**Comment by orlangur** [comment]
Hi @parekhreena, please check comments to https://magento.stackexchange.com/a/180352/40869 in order to understand how translation is supposed to work.

`translate="false"` only means phrase will not be collected. If you don't want "My Custom Value" to be actually translated, don't specify "translated string" different from "My Custom Value".
