### ISSUE TITLE
Adding numeric value for custom attribute

### ISSUE THREAD

**Issue by fmineo** [magento/magento2#13499]
# Preconditions
1. Magento CE 2.2.2

# Steps to reproduce
![schermata 2018-02-05 alle 13 18 03](https://user-images.githubusercontent.com/5881339/35804206-0fcadcc4-0a77-11e8-8a22-9f0bb6ae49e3.png)

# Expected result
I created a simple function to add a value (if not exist) and return the id or simply return the id if the value exist.

# Actual result
If `$myBrand = array('brandNameAsText')` work without problem.
If `$myBrand = array('1234')` don't work, I got Fatal Error:
![schermata 2018-02-05 alle 13 27 16](https://user-images.githubusercontent.com/5881339/35804487-5c40ff24-0a78-11e8-8ea8-d09e5c85a122.png)

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

Are you able to reproduce this issue by creating 1234 attribute option via Admin UI?

**Comment by fmineo** [comment]
No, via Admin UI there is no issue.

**Comment by orlangur** [comment]
Ok, then such question is out of scope for the GitHub. Also, you can learn from Admin UI logic how to write a working implementation.
