### ISSUE TITLE
MySQL built-in keyword "key" using as field name

### ISSUE THREAD

**Issue by syamvilakudy** [magento/magento2#1349]
app/code/Magento/Integration/Setup/InstallSchema.php

In Oath_Consumer table using MySQL built-in keyword "key" as field name

http://dev.mysql.com/doc/refman/5.0/en/keywords.html

**Comment by vpelipenko** [comment]
Does it produce any errors for you?

**Comment by syamvilakudy** [comment]
In App, doesn't have any errors. But in the custom development with Custom Queries occurs errors

For example "Where key = '<String>' " will occurs error

"Where `key` = '<String>' " works

**Comment by orlangur** [comment]
> For example "Where key = '<String>' " will occurs error
> "Where \`key\` = '<String>' " works

Field names must be escaped with `quoteIdentifier`, in such case first situation will be not possible.

**Comment by piotrekkaminski** [comment]
If this is a problem for others, please reopen the issue.
