### ISSUE TITLE
Sample for CE 2.2.2 failed through composer

### ISSUE THREAD

**Issue by sathyashrayan** [magento/magento2#13491]
php version:PHP 7.1.13
server Apache 2
magento: 2.2.2
Step for Composer install sample data

php bin/magento sampledata:deploy
php bin/magento setup:upgrade

I get the attached error. 
![screenshot from 2018-02-05 12-36-43](https://user-images.githubusercontent.com/4995301/35792216-f0e52620-0a71-11e8-91ff-7e2be76cb09f.png)

I cleared var/cache/* and var/generated/* 

getting the same error.
![screenshot from 2018-02-05 12-36-43](https://user-images.githubusercontent.com/4995301/35792205-e205c33a-0a71-11e8-8613-9308c7ca0cb0.png)

After composer update and install the sample data command above also throws the same error

Any suggestions?

**Comment by sergei-sss** [comment]
Try it:
https://stackoverflow.com/questions/35129901/magento-2-area-code-not-set-after-adding-sample-data?answertab=active#tab-top

**Comment by sathyashrayan** [comment]
@sergei-sss Thanks for that link and it works
