### ISSUE TITLE
Address information, billing address shows mess code like " ]][[[[;/..\][[{{}}}/..<<>>" 

### ISSUE THREAD

**Issue by lidiawang** [magento/magento2#13508]
[

### Preconditions

1. [](url)
2. Meganto version I am using 2.22

### Steps to reproduce

1.  when I got order from customer, after they paid by paypal or card is shows pressing but Address information, billing address shows mess code like " ]][[[[;/..\][[{{}}}/..<<>>" 
2. 
3. 

### Expected result

1.  it shoud showing customer address, telephone number ect......

### Actual result

1. [Screenshot, [[[logs]]()]()]()
instead od showing customer address and telepohon is shows mess code like "

![image](https://user-images.githubusercontent.com/35614931/35834615-9b5dee66-0aa4-11e8-92f4-10c90c174e5a.png)
[
![image](https://user-images.githubusercontent.com/35614931/35834624-a427b61c-0aa4-11e8-90a8-79eb28efc3b8.png)
](url)

**Comment by testmagento2** [comment]
Having the same issue only with downloadable products, when customer paid with paypal.

**Comment by magento-engcom-team** [comment]
@lidiawang, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by lidiawang** [comment]
Please help?[
![image](https://user-images.githubusercontent.com/35614931/35895997-0a48530a-0b88-11e8-874b-8a153b9b6fc6.png)
](url)

**Comment by lidiawang** [comment]
[
![image](https://user-images.githubusercontent.com/35614931/35896027-35232000-0b88-11e8-9d45-8391d57b4e3d.png)
](url)

**Comment by nallias** [comment]
Have a look at https://github.com/magento/magento2/issues/12707 this is an active topic

**Comment by hackronshins** [comment]
Is this bug fixed yet? Still I am also facing this issue for paypal orders in back-end on billing information it is displaying prefix variables as template.

**Replication steps:**

1. Add product to the cart
2. Proceed to checkout
3. Using Paypal express payment method
4. Place the order
5. Lets check in backend in admin
6. Open Sales -> Orders
7. Open recent order with order id
8. See the billing information

Magento Version **2.3.1**
Payment Method **Paypal express (Card payment).**

**Comment by engcom-Echo** [comment]
Hello All

This issue is duplicate of [#12707](https://github.com/magento/magento2/issues/12707) so I am closing it.
