### ISSUE TITLE
Static file path rewrite issue

### ISSUE THREAD

**Issue by EmeryEx** [magento/magento2#13518]
### Preconditions

1. Magento version 2.1.9
2. PHP 7.0.27
3. MySQL Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
4. Apache/2.4.6 (CentOS)
5. CentOS Linux release 7.4.1708 (Core)

### Steps to reproduce

1. Using HTTPS, login to the admin
2. Clear static files cache

### Expected result

1. The sidebar menu should work still

### Actual result

1. Console error: 
![console-bug](https://user-images.githubusercontent.com/3971657/35868058-19f7e660-0b21-11e8-82c7-012e379e55d1.PNG)
2. After trying to open js file in a new tab: 
    Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/jquery/jquery-ui-1.js'
    #0 /var/www/html/vendor/magento/framework/App/StaticResource.php(97): 
    Magento\Framework\View\Asset\File->getSourceFile()
    #1 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): 
    Magento\Framework\App\StaticResource->launch()
    #2 /var/www/html/pub/static.php(13): Magento\Framework\App\Bootstrap-
    \>run(Object(Magento\Framework\App\StaticResource))
    #3 {main}
3. Internally, it seems to be clipping the `.9.2` from the file name "jquery-ui-1.9.2.js" -> "jquery-ui-1.js"
4. If i put the js file it is looking for into the pub/static directory manually, everything works. But that just gets removed when static files are flushed.

**Comment by magento-engcom-team** [comment]
Hello @MarshallHouse! Thank you for reporting the issue. We want to know some details about this issue:
1) Does it happen only in production mode? You can check the mode issuing the command from the Magento root-folder: `php bin/magento deploy:mode:show`
2) Is mod_rewrite enabled on your server? You can check with `httpd -M | grep rewrite`
3) Have you set the proper permissions before going to Setup Wizard? [Documentation](http://devdocs.magento.com/guides/v2.2/install-gde/prereq/file-system-perms.html#perms-set-two-users)
4) Could you provide the output of `ls -alt pub/static` executed from Magento root-folder? (We want to know permissions on this folder and check that .htaccess is still there)
5) Could it be that there were some rewrite conditions or redirect rules for forcing the usage of https over http somewhere inside your virtual host configuration file or general httpd conf file?

We can not reproduce this issue on the 2.1-develop, 2.2-develop and 2.3-develop branches. You can try to solve this problem in the next way:
1) Make sure that you are in Magento root-folder. Check your current location directory with `pwd` command. If you are in the folder where Magento was installed then remove everything from static contents folder with command `rm -rf pub/static/*`
2) Perform static content generation.
`php bin/magento setup:static-content:deploy`

We can try to reproduce on 2.1.9 but we need your answers.

**Comment by magento-engcom-team** [comment]
Hi @MarshallHouse
We are closing this issue now due to inactivity. Please feel free to reopen if you would like to continue discussion.
