### ISSUE TITLE
[Question] Custom Cart Price Actions

### ISSUE THREAD

**Issue by OwenMelbz** [magento/magento2#13515]
Hi,

Is it possible to add custom actions for coupon codes?

e.g You're on the cart page and have been provided with a coupon code, when you enter the coupon code it adds x1 Burger to your basket.

or You enter a coupon code which hits an external API triggering a webhook to start a process.

Basically we'd like to trigger a custom class/method when this type of coupon is redeemed, rather than the default ones.

Is this supported and/or possible?

Thanks

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
