### ISSUE TITLE
Magento 2.2.2 Multi Select Attribute doesn't save when related products are attached

### ISSUE THREAD

**Issue by magefan** [magento/magento2#13520]
### Preconditions
1. Magento 2.2.2
2. PHP 7.0.23 
3. Browser Chrome 64 on Linux

### Steps to reproduce

1. Add Multi Select Attribute to Product
2. Choose some options to that multi-select and save the product
4. Add related products and save
5. Try to change options in multi-select and save

### Expected result
1.  The options should have changed

### Actual result
1. After the save and page refresh the options stay the same

The same issue had @AgentGod  https://github.com/magento/magento2/issues/4822#issuecomment-337902010 and the @duckchip https://github.com/magento/magento2/issues/4822#issuecomment-340372570 solution helps but this just a temporary solution.

**Comment by magefan** [comment]
Our quick fix was to move this line of code 
`$product = $this->setProductLinks($product);`

to the beginning of the function `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper::initializeFromData(\Magento\Catalog\Model\Product $product, array $productData)
`

**Comment by magento-engcom-team** [comment]
@magefan, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jajaramos** [comment]
#MLAU18

can't reproduce on Magento 2.2.2

**Comment by ctadlock** [comment]
I have this exact issue on Magento 2.2.3. I have a product with several multi-select attributes, everything works well. If I add an up-sell product, I am then unable to modify any of the multi-select attributes.

**Comment by ctadlock** [comment]
@jajaramos Please re-open this issue; @cherednichenkoa is working on a fix (https://github.com/magento/magento2/pull/14125)

**Comment by A-1A** [comment]
I Found Solution after R&D On Magento database.
Login In your phpmyadmin
Go to your website database 
Open "eav_attribute" table
Find Your multiselect "attribute_id"
Edit Row
If "backend_model" Column blank then paste this **Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend**
And Also Please check this
https://magento.stackexchange.com/questions/224621/warning-array-filter-expects-parameter-1-to-be-array/230444#230444

**Comment by DanBeckett** [comment]
Recently (Magento 2.3.3) experienced the same issue with a Multi-select attribute created via the Attribute editor in the dashboard. In **eav_attribute** found that the **source_model** was NULL, updating this to **Magento\Eav\Model\Entity\Attribute\Source\Table** fixed the issue for me.
