### ISSUE TITLE
Yes/No Attributes toggle value when page is clicked in product edit mode

### ISSUE THREAD

**Issue by walrus28** [magento/magento2#13522]
### Preconditions
1. Magento 2.1.9

### Steps to reproduce
1. Create a new attribute, test. For "Catalog Input Type for Store Owner", select "Yes/No".
2. Add test to an attribute set, testSet. 
3. Create new product. Use the testSet attribute set. 
4. While the product is open in edit mode, click on the label or the white space to the left of the label of the attribute test. 

### Expected result
1. Nothing.

### Actual result
1. The test attribute value toggles. (if it was yes, it changes to no; if it was no, it changes to yes).

**Comment by magento-engcom-team** [comment]
@walrus28, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jajaramos** [comment]
Hi @walrus28,

I've checked this on a fresh Magento 2.2.2 installation and it doesn't seem to be a bug, it's the default behaviour for all Yes/No elements. You can observe the same behaviour if you click on the "Enable Product" label in the product edit page and it will toggle the form field value from Yes to No. 

Same behaviour on Magento 2.1.8.

#MLAU18

**Comment by walrus28** [comment]
This is a bug. 

The fact that it has persisted for multiple versions is insufficient to classify it as a non-issue. 
As can be seen from other gitHub posts, the reality is that in Magento, many bugs live on through many versions before being addressed.

What makes this behavior a bug is that it produces completely unexpected results with negative consequences to the user.

When on the product edit page in Magento, there is no indication whatsoever that clicking on the whitespace of the page will produce any result. On most parts of the page, this expectation proves correct: click on whitespace, nothing happens. However, if one happens to click to the left of a true/false attribute, there is an unexpected result, and the value of that attribute is changed. 

When a user is entering products, he or she does not expect anything to happen when clicking on the whitespace of the page. Therefore, he or she may do so without reservation, clicking between windows for example. If the user clicks on a place on the whitespace of the page that just so happens to be to the left of a true/false attribute, the value will change. Hopefully, the user notices and while irritated, can change the value back. Unfortunately, since the user was not expecting anything to happen, he or she may not have noticed that the value changed. In this case the bug lead to an error in product data. 

This bug produces unexpected results that lead to frustration & data entry errors. 
This bug report should be re-opened.
