### ISSUE TITLE
Slow performance when moved the products from sub stores to main store

### ISSUE THREAD

**Issue by nuwaus** [magento/magento2#13525]
I have a Magento 2 multi-store with 65 sub stores and have more than 60000 products all combined and have a big catalog menu.
And recently I have moved all those products from every store to the main store,
And now I'm experiencing the site is very slow and often get Error 500 HTTP error.

### Preconditions
Magento version: 2.2.2
PHP version: PHP 7.1.10
Varnish enabled
Sphinx 2.2.11

### Steps to reproduce
Have more than 60000 products in sub stores and later move all of them into the main store.

### Expected result
Have all products in the main store with catalog menu

### Actual result
Slow server performance
Error 500 HTTP issue

**Comment by karangar** [comment]
Have you done the indexing process?
If yes, then check it your attribute set.
Because I have more than 33K products it's working correctly.Before i have 80K products and also it was working.

**Comment by nuwaus** [comment]
This issue was fixed, It was causing 3rd party module, disable it and rung the complete indexer resolved the issue.
