### ISSUE TITLE
2.2.2 - Cart price rule scheduled updates don't trigger

### ISSUE THREAD

**Issue by TerribleDeveloper** [magento/magento2#13524]
### Preconditions

**Magento Version:** 2.2.2
**PHP Version:** 7.0.27
**MySQL Version:** 5.6.34 
**Web Server:** Apache 2.4.6

### Steps to reproduce

**Step 1 - Create new cart price rule**

1. Set name, set active to no, select all websites/customer groups, set "No Coupon", leave Uses per customer and Priority blank.
2. Create Product attribute combination, and match category ID.
3. In Actions tab, set apply to shipping amount to true, and free shipping to For shipments with matching items

**Step 2 - Create new cart price rule**

1. Click Schedule New Update
2. Set name, start, and end date
3. Under Rule Information tab, set active to Yes
4. Save Rule and wait for proper time

### Expected result

1. At time set in Step 2 above, shipping for the selected category should show up as a free option. 2. When viewing scheduled updates on the backend, an indicator should show where the cart rule is active within the schedule.

### Actual result

1. Free shipping isn't an option within checkout
2. No indication of if the scheduled update is active or not, "Active" is still set to No

### Additional Information

- No changes set in the scheduled update take effect
- When switched to active and saved, the free shipping option does show up as it should
- Tested assuming both server and local time, same result
- Created rule with active enabled initially, with scheduled update set to disable, stays active
- Database is storing start and end times in 'created_in' and 'updated_in' respectively. "Active" values are correct, so entries seem to be created properly

**Comment by magento-engcom-team** [comment]
Hello @TerribleDeveloper. It seems You use Enterprise Edition or as it is now used to be called Commercial Edition. If so please contact Magento Support directly.

**Comment by magento-engcom-team** [comment]
@TerribleDeveloper, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by TerribleDeveloper** [comment]
It's not working. How is it a non-issue.

**Comment by abbasalibutt** [comment]
@TerribleDeveloper I am also facing the same issue. Have you found it's solution?

**Comment by 0x15f** [comment]
Facing the same issue on 2.2.7 EE
