### ISSUE TITLE
Weird Cryptographer test on array string conversion

### ISSUE THREAD

**Issue by nicobatty** [magento/magento2#13531]
Considering the test sending an array to the encode method:
https://github.com/magento/magento2/blob/6790f9a01cb48cf30c376c07a97d9d17b1854b70/app/code/Magento/Analytics/Test/Unit/Model/CryptographerTest.php#L175-L182

And this code:
https://github.com/magento/magento2/blob/6790f9a01cb48cf30c376c07a97d9d17b1854b70/app/code/Magento/Analytics/Model/Cryptographer.php#L56-L60

This try catch seems weird to me, because an array type cast to string in PHP results in a string "Array" and send back a notice.

How do this test even return as a success?

From the PHP doc: http://php.net/manual/en/language.types.string.php
> Arrays are always converted to the string "Array"

This code should probably be replaced with a `is_scalar` condition check.

**Comment by magento-engcom-team** [comment]
@nicobatty, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by peterjaap** [comment]
I'd suggest just checking for an array first. An object might have a `__toString()` method defined which might cast it to a valid serializable string. Casting a resource to a string would throw an exception, so we'll have all bases covered.

```php
    public function encode($source)
    {
        if (is_array($source)) {
            throw new LocalizedException(__('Input data must be string or convertible into string.'));
        } else if (!is_string($source)) {
            try {
                $source = (string)$source;
            } catch (\Exception $e) {
                throw new LocalizedException(__('Input data must be string or convertible into string.'));
            }
        } elseif (!$source) {
            throw new LocalizedException(__('Input data must be non-empty string.'));
        }
```

This makes the test pass. (how on earth could this broken test be released anyway?)

**Comment by engcom-Delta** [comment]
@peterjaap thanks for investigation, you are right. Function `testEncodeNotValidSource` runs twice and check data from `encodeNotValidSourceDataProvider` to appropriate exception. 

![#13531issue](https://user-images.githubusercontent.com/51681379/71657474-a8234380-2d48-11ea-8f5c-bca935be0a44.gif)

Closed as non-issue
