### ISSUE TITLE
Magento composer

### ISSUE THREAD

**Issue by jonatanrdsantos** [magento/magento2#13542]
This is more a question that an error issue. 

I'm trying to use Magento modules only by composer, using this [documentation](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install_ce.html).

The composer project name is `"name": "magento/project-community-edition",`.
But when you go to the [github project](https://github.com/magento/magento2-community-edition), you see this message `[DEPRECATED]`.

And when you go to the [download page](https://magento.com/tech-resources/download). you download the same depracated project.

I do not understand why is deprecated, whats is the plan of **Magento Team** to solve this confusing documentation?

Don't get me wrong, i'm not judging, but look at the [Laravel documentation](https://laravel.com/docs/5.5), is so simple, easy.

What if I want to update to the version 2.3? What I need to do?

Bests.

**Comment by magento-engcom-team** [comment]
Hello @joridos. Thanks for applying, but the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment]
@joridos, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
