### ISSUE TITLE
Reorder functionality is adding disabled products to cart

### ISSUE THREAD

**Issue by pgsutariya** [magento/magento2#13540]
Magento adds products that have been disabled to the cart.

### Preconditions

1. Magento 2.2.2 CE
2. Customer account created

### Steps to reproduce

1. Place Order in Magento for a product
2. Disable the product in the admin panel
3. Log into the My Account section, open the order details for the previously placed order and click "reorder"
4. Disabled item gets added to the cart

### Expected result

1. Error message should appear and item should not be added to the cart

### Actual result

1. Item is added to the cart

**Comment by neeta-wagento** [comment]
Hello @pgsutariya 
I just tried to test and reproduce it. 

Followed below steps
Place Order in Magento for a product
Disable the product in the admin panel
Log into the My Account section, open the order details for the previously placed order and I can not see 
"Reorder" link If any of my product in order is no more available

See my screenshots below. Can you please give me some more information where/how this is not working? 
![order-000000004](https://user-images.githubusercontent.com/33098216/35916835-c74ef928-0c31-11e8-9385-925f560b6567.png)

Thanks!

**Comment by pgsutariya** [comment]
@neeta-wagento 
you need to change some file of sales order.

**/magento222/vendor/magento/module-sales/view/frontend/templates/order/recent.phtml**

copy this file in

**/magento222/app/design/frontend/[Vendor]/[Theme]/Magento_Sales/templates/order/recent.phtml**

Line Number: 48 to 55
Replace with blow code or only remove if condition
```php
<a href="#" data-post='<?php echo $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))?>' class="action order">
    <span><?= __('Reorder') ?></span>
</a>
```

**/magento222/vendor/magento/module-sales/view/frontend/templates/order/history.phtml**

copy this file in

**/magento222/app/design/frontend/[Vendor]/[Theme]/Magento_Sales/templates/order/history.phtml**

Line Number: 44 to 51
Replace with blow code or only remove if condition
```php
<a href="#" data-post='<?php echo $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))?>' class="action order">
    <span><?= __('Reorder') ?></span>
</a>
```

**/magento222/vendor/magento/module-sales/view/frontend/templates/order/info/buttons.phtml**

copy this file in

**/magento222/app/design/frontend/[Vendor]/[Theme]/Magento_Sales/templates/order/info/buttons.phtml**

Line Number: 12 to 19
Replace with blow code or only remove if condition
```php
<a href="#" data-post='<?php echo $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))?>' class="action order">
    <span><?= __('Reorder') ?></span>
</a>
```



Using this change you can easily view "Reorder" link.

**Comment by pgsutariya** [comment]
@neeta-wagento
Currently, i fixed this issue by overriding reorder Controller but it quick fix not proper solution.

**Comment by magento-engcom-team** [comment]
@pgsutariya, thank you for your report.
Unfortunately, we can not reproduce this issue with described steps.
Steps we did:
1. Create custom theme with modified .../order/recent.phtml, .../order/history.phtml, .../order/info/buttons.phtml in a way, that reorder button shows up always.
2. Create simple product.
3. Register customer.
4. Place order with created product as registered customer.
5. Disable product via admin interface.
6. Navigate to storefront customer account.
7. Press reorder from "Account Dashboard" > "Recent Orders".
Result : "Product that you are trying to add is not available." message appear, no products added to cart.
8. Press reorder from "My orders" tab.
Same result: "Product that you are trying to add is not available." message appear, no products added to cart.

Please provide additional information, or steps to reproduce. Or correct our steps, in case they are not correct.

**Comment by pgsutariya** [comment]
@magento-engcom-team you did right.
But little thing you forget. you need to add multiple product for e.g. you have to add product1 and product 2 in the cart and the place order.

After placing order you can disable or delete product1 or one of the ordered product.
And then click on reorder button.

**Expected result**
Error message should appear on cart page and enabled product must be added in the cart

**Actual result**
"Product that you are trying to add is not available." message appear, no products added to cart."

**Comment by magento-engcom-team** [comment]
@pgsutariya , thanks for feedback. Unfortunately we weren't able to reproduce this issue even with multiple products in cart. As soon, as one of the product become disabled or deleted, we received "Product that you are trying to add is not available." message and no products were added to cart.

**Comment by pgsutariya** [comment]
@magento-engcom-team, thanks for reply.
as you mention, you added multiple product to order and the disable or delete one of them, and reorder it. you received "Product that you are trying to add is not available." message and no products were added to cart.

but my issue is that
what about that product which is enable and instock.

If one of them are disable then that not added to cart but other on need to add in to cart.

for e.g. if p1 and p2 are order item.
p1 is disabled
we reorder that order
then p2 must be added in to cart and p1 is not added into cart with message.

in default magento it's not work like that if one of order item is disable or out of stock then rest are not added to cart.

**Comment by magento-engcom-team** [comment]
@pgsutariya Thanks for reply. Please create additional issue, which describe problematic behaviour from your last comment. 
We close this issue, as initially described behaviour is expected one.
