### ISSUE TITLE
Including Tax and Excluding Tax price display not working on ConfigurableProducts

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#13555]
### Preconditions

1. Debian 8
2. Apache 2.4, MySQL 5.7,PHP 7
5. Magento 2.1.8

### Steps to reproduce

1. Set prices in the catalogue to excluding tax
2. under stores->configurations -> price display settings
3. set Display product prices in Catalog to -> Including and Excluding Tax.
4.Load the configurable product on the front end.
5.The price shows both as Excluding Tax when the page loads but works correctly after a configuration is chosen. 

### Expected result

1. The configurable product should display both Inc and Ex. Vat prices correctly on the product page when it is loaded.

### Actual result

1. It displays Ex.Vat price on the frontend.

![image](https://user-images.githubusercontent.com/19605497/35968617-59557f24-0cbc-11e8-88f8-b4c034d879d4.png)

Works when the configuration is chosen, which is misleading customers.
![image](https://user-images.githubusercontent.com/19605497/35968662-7ad75a00-0cbc-11e8-9856-cbcca9477859.png)

Settings at the backend 
![image](https://user-images.githubusercontent.com/19605497/35968763-adf9891c-0cbc-11e8-866b-5484f6409c4f.png)
![image](https://user-images.githubusercontent.com/19605497/35968785-bbdaa110-0cbc-11e8-9761-f6f1a93a3a99.png)

Is there any quick fix around to fix this issue?.
As this has become a big complaint from our customers.

**Comment by magento-engcom-team** [comment]
Hello @nmallepally. Thanks for reporting. Currently we have been not able to reproduce Your issue. The video with the steps we've made is attached here. So please watch it and tell us what we've done not like You. Also please would You try to reproduce this issue on a clear instance of Magento.

**Comment by nmallepally** [comment]
Hi @magento-engcom-team 

I cannot see any video attachment here?.

**Comment by magento-engcom-team** [comment]
Sorry @nmallepally, here it is.
[TaxPrice.zip](https://github.com/magento/magento2/files/1707511/TaxPrice.zip)

**Comment by nmallepally** [comment]
Hi @magento-engcom-team 
Thanks for the video.

From the video, it looks like everything is right, but we have updated our Magento store from 2.1.6 to 2.1.8, after the fresh install of 2.1.6. that's the only difference.
The error also happens to be on the first load, As you see below screenshots when I load the page and pause it on the debugger, it shows correctly like below on loading:
![on load correct](https://user-images.githubusercontent.com/19605497/35981940-720dd05a-0ce6-11e8-85ad-5fb8f5616945.PNG)

But when the images finish loading on to the configurable product page.
that is where the actual issue comes up, it will change to Ex.vat like below:

![image](https://user-images.githubusercontent.com/19605497/35981995-92155fee-0ce6-11e8-850b-62aa2f1a995a.png)

Note: It does not happen on simple products, only on configurable products.
It works again when I set the catalogue price setting to include tax. 
![image](https://user-images.githubusercontent.com/19605497/35982094-d75ea70e-0ce6-11e8-98ed-204b915116f3.png)
It shows up correct value, displaying the tax on to the product page:
On Load correct:
![image](https://user-images.githubusercontent.com/19605497/35982227-2ba912ea-0ce7-11e8-9d79-b2af9f7118c1.png)

After Load also correct:
![image](https://user-images.githubusercontent.com/19605497/35982257-3de817e4-0ce7-11e8-8233-2a0f6c7412e8.png)

It just does not work on exclude tax setting for catalogue prices - > as the products in the catalogue have ex.vat price.

**Comment by nmallepally** [comment]
Also, another thing which I found was, when I stop the page load and see debugger for remaining scripts to be loaded.
From the scripts pending which have to finish loading is fotorama js.
Once fotorama js is loaded completely - > inline with images loading completely- thats when the error comes, the value changes back to Ex.Vat value in place of Inc.Vat.
![image](https://user-images.githubusercontent.com/19605497/35983270-99a81898-0ce9-11e8-911a-855382113964.png)

Below are also the element source before and after load:
Before fotorama loads:
![before load](https://user-images.githubusercontent.com/19605497/35983433-ef565912-0ce9-11e8-8f0e-2017b236e6ea.PNG)

After fotorama loads:
![after load element](https://user-images.githubusercontent.com/19605497/35983449-fa1edc02-0ce9-11e8-9a1d-3a2ad3b6e6e4.PNG)

**Comment by magento-engcom-team** [comment]
Thank You @nmallepally. But under clear instance of Magento we meant not simply an instance free from any products, customers etc., but also free from any third party modules, themes and the like. It should be an instance that has just been installed from the official Magento site. Because as we see You use some custom theme which is neither Luma, nor Blank. So would You retry please.

**Comment by nmallepally** [comment]
Hi @magento-engcom-team 

I have tested it on plain Magento after our discussion, I can still able to reproduce the issue.
please see attachments below:
![on plain Magento 2 1 8](https://user-images.githubusercontent.com/19605497/36090575-c5f740f8-0fd8-11e8-9648-ea158a21321c.PNG)

![image](https://user-images.githubusercontent.com/19605497/36090587-d6188d52-0fd8-11e8-955f-19f4d2c52051.png)

**Comment by magento-engcom-team** [comment]
Ok, @nmallepally. Unfortunately in many cases custom modules and themes (especially themes) continue to work in some aspects even after having been disabled. Only the physical deletion makes them stop working. So sorry for being tiresome, but please confirm You did not just disable custom modules, themes You have but installed a totally fresh instance of Magento with database filled with only the default data. Thank You.

**Comment by nmallepally** [comment]
Hi @magento-engcom-team 

Yes, it works on the new installation of Magento 2.
I have deleted one of the modules which are related to configurable product and it is working.(ayasoftware-simple product pricing) - i will report the bug to them, thanks.

Thank you for the quick responses to resolve the issue.

**Comment by magento-engcom-team** [comment]
@nmallepally, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
