### ISSUE TITLE
2.1 to 2.2 Catalog upgrade data script taking an extremely long time to complete

### ISSUE THREAD

**Issue by zolat** [magento/magento2#13553]
We are upgrading a website from Magento 2.1 to 2.2 and finding that a setup script added to the Catalog module is taking a very long time to run. So far the script has been running for 4.5 hours and is looking to be around 15% complete.

### Preconditions
1. Have a Magento 2 instance running on version 2.1.x
2. Have many products/websites/stores. For us, this is 179817 products that are shared over 7 websites.

### Steps to reproduce

1. Upgrade to Magento 2.2
2. Run `bin/magento setup:upgrade`

### Expected result

1. The Magento 2 instance is upgraded within a reasonable amount of time.

### Actual result

1. Magento takes days to update.

It is the setup script and related code from this commit that is causing the issue: 
https://github.com/magento/magento2/commit/ed25f988c85051bfb026661915776248cc0dbba1

**Comment by orlangur** [comment]
Hi @zolat, do you see where in ed25f98 upgrade script is performing unnecessary operations?

**Comment by zolat** [comment]
Hi @orlangur the issue is occurring at `vendor/magento/module-catalog/Setup/UpgradeData.php:392` (Magento V 2.2.2), where the script looks to be updating nearly every single catalog attribute value. It is made extra slow by the fact that it is operating in batches of 100, but I'm not sure if increasing the batch size would be enough to get it running at a reasonable rate.

**Comment by zolat** [comment]
Update: i have rewritten to use a batch size of 100 000 instead of the 100 that it was set to, and it is looking like it should complete within 1-2 hours. Hard to say what an appropriate size for general use would be, but it 100 is definitely too low.

edit: make that 3 to 4 hours, but still beats days...

**Comment by orlangur** [comment]
Another similar report: https://github.com/magento/magento2/issues/13611 Contains another idea on performance improvement also.

**Comment by ferrazzuk** [comment]
@orlangur we were thinking of using rabbitMQ to mimic some sort of threading with a few hundreds of consumers so that the upgrade completes in less time LOL .. but I think it might be possible to add more filtering to the first select query so less rows are processed.

**Comment by magento-engcom-team** [comment]
@zolat , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce: how did you do the update, parameter of your server or try to reproduce this issue on a clean installation

**Comment by mcyrulik** [comment]
Our update from 2.1.10 to 2.2.4 has so far taken over three hours on just the Magento_Catalog module data upgrade. 

We have 1 store, and ~140,000 products. We don't have that many attributes that it needs to go through, but this feels like it should not take THIS long to accomplish a task like this.

**Comment by orlangur** [comment]
>  on just the `Magento_Catalog` module data upgrade

Other modules upgrades are negligible compared to Catalog anyway in this update.

**Comment by artskeem** [comment]
Has there been any solution for this problem - I'm having the same issue with ~680,585 overhead :/

**Comment by farhadfrz** [comment]
I don't know if this is related or I should make a new issue, but we have the same issue while upgrading Magento_Quote and Magento_Sales. It took almost one day to upgrade our staging page!

**Comment by ttmuangkeo** [comment]
I, too am having issues with upgrading (2.2.2 to 2.2.5). 

Except for me, I am getting a max_execution_timeout of 300 seconds when I run
php bin/magento setup:upgrade. 

I am using Cloudways and they said anything in .htaccess will not be used. To make changes would be in their PHP-FPM Settings. I added the following values below.  

I restarted my server and looked into my phpinfo() and see that everything has been increased with the values below.

php_value [post_max_size] = 3000M
php_value [upload_max_filesize] = 3000M
php_value[memory_limit] = 3000M
php_value[max_execution_time] = 259200
php_value[max_input_time] = 259200
php_value[session.gc_maxlifetime] = 1200

**Comment by kornblumenapotheke** [comment]
Same problem here: 2.2.2 => 2.2.5
Would be nice to get any feedback from system how much has been processed so far...

Leaving Computer now for some ice cream, I suppose it takes hours to convert my 50K products...

**Comment by jobingeorgek** [comment]
@zolat @farhadfrz I am also getting the issue with Magento_Quote and Magento_Sales, we have 400000 rows in sales table, its taking hours to complete the upgrade from 2.1 to 2.2. Did you get any solution to resolve the issue?

**Comment by ghost** [comment]
We were not able to reproduce this issue. We'we tried two scenarios:
1. Upgrading Magento 2.1.14 with sample data to Magento 2.2.5.
2. Upgrading Magento 2.1.14 with 200000 simple products (generated by performance toolkit) and 7 websites to Magento 2.2.5.
Can anyone provide clarified Steps to Reproduce?

**Comment by magento-engcom-team** [comment]
@magento-engcom-team Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95099` were created

**Comment by rahulgspann** [comment]
> Our update from 2.1.10 to 2.2.4 has so far taken over three hours on just the Magento_Catalog module data upgrade.
> 
> We have 1 store, and ~140,000 products. We don't have that many attributes that it needs to go through, but this feels like it should not take THIS long to accomplish a task like this.

Any solution you found?

**Comment by rahulgspann** [comment]
> Update: i have rewritten to use a batch size of 100 000 instead of the 100 that it was set to, and it is looking like it should complete within 1-2 hours. Hard to say what an appropriate size for general use would be, but it 100 is definitely too low.
> 
> edit: make that 3 to 4 hours, but still beats days...

can you let me know where to update the limit params?

**Comment by rahulanand77** [comment]
Step to increase limit of this query from "100" to your requirement is:

1) Open the core file "Magento\Framework\DB\Query\Generator.php"
2) Search for function "generate". It has a param "$batchSize" with default value "100". 

Increase it to "100,000" or as per your requirements to speed up the setup: upgrade.

**Comment by magento-engcom-team** [comment]
Hi @zolat. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.2-develop` branch(es).
Related commit(s):
 - [332425f395811a159b986509854ae8e5bf9bfc59](https://github.com/magento/magento2/commit/332425f395811a159b986509854ae8e5bf9bfc59)

The fix will be available with the upcoming `2.2.10` release.

**Comment by engcom-Charlie** [comment]
Hello @zolat 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
