### ISSUE TITLE
Tier price wrong when article is put in cart

### ISSUE THREAD

**Issue by damien-lechopier** [magento/magento2#13557]
Tier price is not working when a logged customer put product in cart
The cart/checkout take base price instead of tier price

### Preconditions
Magento v2.2.2 
PHP 7.0
Magento theme : moza
All caches are disabled

### Steps to reproduce
Create a simple product
Put base price and use "special price" to put different prices for you different customers group (at least 3 fixed prices (quantity 1) for 3 different groups)

### Expected result
When a customer is logged, he can see base price and tier price on product page.
When product is put in cart, tier price is taken

### Actual result
Tier price display good on product page but when I put article in my cart, the price displayed is base price instead of tier price
I note that the customer group id in session is lose when I put my product in cart.
When I display session data for the session after cart, it take the default group id for my customer.

![screenshot_1](https://user-images.githubusercontent.com/17142667/35970202-cbc7e724-0cc9-11e8-9bea-44452bec8e68.jpg)

**Comment by magento-engcom-team** [comment]
@damien-lechopier , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation and default theme(luma or blank).
![simple_in_cart_0921280988](https://user-images.githubusercontent.com/31669971/35972426-73c75ee0-0cda-11e8-8705-57b79bad630c.png)

**Comment by damien-lechopier** [comment]
@magento-engcom-team  

I don't know which more details infos I can provide to you.
I've also reproduced this bug with default theme Luma.
My first installation was on Magento v2.2.1, I upgraded it in December 2017.

Do you want me to send the URL of my online Magento (in private) to reproduce this in live mode.

**Comment by damien-lechopier** [comment]
I found the solution to my problem. It might help other people.
In customer sheet in back office, you have to check the checkbox "Disable auto group changement based on TVA" (Sorry for traduction)

You can close this ticket, thanks for your help.

**Comment by magento-engcom-team** [comment]
@damien-lechopier , thanks for you update.

**Comment by magento-engcom-team** [comment]
@damien-lechopier, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
