### ISSUE TITLE
Email Templates Preview should not come with sidebar Admin Menu

### ISSUE THREAD

**Issue by lalittmohan** [magento/magento2#13554]
### Preconditions

1. Install Magento 2.1.9 , Magento 2.1.10 with sample data
2. Load default template for orders,invoice .. etc or Create new email templates.

### Steps to reproduce

1. Open email templates in admin Marketing->communications->email templates.
2. Preview any of templates.

### Expected result

1. Preview should come without sidebar admin Panel menu. 

### Actual result

1. 
![email-preview](https://user-images.githubusercontent.com/5228822/35958875-1243a2c0-0cc9-11e8-8dcb-0079c3e3b82f.png)

**Comment by magento-engcom-team** [comment]
@lalittmohan, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jayankaghosh** [comment]
I am working on this at #dmcdindia

**Comment by jayankaghosh** [comment]
Cannot duplicate in 2.3.x

**Comment by Karlasa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [Magento instance](https://i-13554-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-13554-2-3-develop.instances.magento-community.engineering/admin](https://i-13554-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Karlasa** [comment]
Will close this issue because can't be reproduced in current 2.3-develop branch
