### ISSUE TITLE
[Question] To ResultInterface or not ResultInterface...

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#1355]
I'm confused by a comment in the `\Magento\Framework\App\Http::launch()` method.

```php
// TODO: Temporary solution till all controllers are returned not ResultInterface (MAGETWO-28359)
```
Note the "not" in that sentence.

From this comment it seems as if returning the Result Page from an action controllers `execute()` method is not recommended, but instead the response object should be returned. However, looking at the core code it seems as if using the result page should be used.

Please tell me, what is the right thing to use? 

1. `\Magento\Framework\Controller\ResultInterface` (e.g. `\Magento\Framework\View\Result\Page`)
or
2. `\Magento\Framework\App\Response\HttpInterface` (e.g. `\Magento\Framework\Webapi\Response`)

For reference, here a larger excerpt from the `App\Http::launch()` method:
```php
        /** @var \Magento\Framework\App\FrontControllerInterface $frontController */
        $frontController = $this->_objectManager->get(\Magento\Framework\App\FrontControllerInterface::class);
        $result = $frontController->dispatch($this->_request);
        // TODO: Temporary solution till all controllers are returned not ResultInterface (MAGETWO-28359)
        if ($result instanceof ResultInterface) {
            $this->registry->register('use_page_cache_plugin', true, true);
            $result->renderResult($this->_response);
        } elseif ($result instanceof HttpInterface) {
            $this->_response = $result;
        } else {
            throw new \InvalidArgumentException('Invalid return type');
        }
```

**Comment by paliarush** [comment]
@Vinai , thank you for pointing to this issue. As you mentioned, "not" is put here incorrectly and will be fixed.

In the future all action controllers are expected to return `\Magento\Framework\Controller\ResultInterface`, so this is a recommended usage.

**Comment by Vinai** [comment]
Thank you for clarifying @paliarush! On that note, would you be open for a PR with a Text response type (similar to json or raw) which defaults to a text/plain content type? It's main purpose would be for easy test controllers during development.
Or would you prefer to keep out code that would probably only be useful during development?

**Comment by paliarush** [comment]
Please consider using `\Magento\Framework\Controller\Result\Raw` to return plain text, it should suffice for testing purposes (not sure what your testing use case is though).

Please also note, that it is discouraged to add any code, which will be used for development purposes only, to core framework.

**Comment by Vinai** [comment]
The testing purpose is to add a controller and dump some text to the screen easily. Afterwards that controller is removed again. 
This is a scenario I use a lot during development and also in trainings.
When using the Raw result implementation, it always requires specifying the text/plain content type so newlines and spaces can be used to format the output.
```php
        /** @var Raw $result */
        $result = $this->resultFactory->create(ResultFactory::TYPE_RAW);
        $result->setHeader('content-type', 'text/plain');
        $result->setContents($content);
        return $result;
```
It's not a big thing, it just would be more convenient to have a text/plain result object available. However, if you don't want it - no problem. Thats why I'm asking.

**Comment by paliarush** [comment]
@Vinai , thanks for clarification of your use case. Since proposed new class adds a value during development process only, we cannot add it to the core framework.

Thank you for proposing improvements to the Magento 2.

**Comment by Vinai** [comment]
Thanks!
