### ISSUE TITLE
'initialize' function of cc-form.js is not executing on billing address update while checkout.

### ISSUE THREAD

**Issue by melavankimanjunath** [magento/magento2#13562]
recently I am upgraded my custom payment module wit 2.1 CE to 2.2.2 EE
I am calling ajax function in 'initialize' method which need to update payment type on update of billing address.
```
initialize: function () {
    this._super();
    this.selectedCCType(null);
    this.filtercardajax();
 }
```
this function is executing in CE-2.1 on everytime when customer update there billing address while checkout before place order button click, but on EE-2.2.2 this function executing only once on page load, not on billing address change.

**Comment by orlangur** [comment]
Hi @melavankimanjunath 

> but on EE-2.2.2 this function executing only once on page load, not on billing address change

Why you think it should be executed each time? Is this method marked as `@api`?

**Comment by melavankimanjunath** [comment]
@orlangur 
because, its executing each time in CE-2.1
And I am calling a custom function with that call.

**Comment by orlangur** [comment]
@melavankimanjunath I'm asking from the business logic perspective, not from the perspective of your particular customization. There is no guarantee that internal implementation will be preserved between 2.1 and 2.2 thus there is a high probability you need to fix your customization to make it workable again under 2.2.

**Comment by magento-engcom-team** [comment]
@melavankimanjunath , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@melavankimanjunath, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
