### ISSUE TITLE
I can not acces  magento admin panel in magento 2.

### ISSUE THREAD

**Issue by Rinakl** [magento/magento2#13572]
### Preconditions

1. Magento e-commerce 
2. Magento 2.2.1

### Steps to reproduce

1. In Magento admin->Design->configuration->Advanced->Admin->Admin base url
2. In Use custom admin url  I set as YES
3. In custom admin url I have wriiten path that i need to set as admin url
![admin](https://user-images.githubusercontent.com/34139324/35995108-6ac08bfe-0ce0-11e8-9b3e-5f7a13abdb8d.PNG)
### Expected result

1. It shows Different layout of admin side where I can't access anything.

### Actual result

1. 
![admin changed](https://user-images.githubusercontent.com/34139324/35995103-678376e0-0ce0-11e8-9f44-bb9690033de9.PNG)

**Comment by RahulBhut21** [comment]
check server logs for error.
Thank you.

**Comment by rafalcao** [comment]
Try run these steps: 

1. php -d memory_limit=1G MAGE_ROOT/bin/magento setup:static-content:deploy en_US
2. chmod -R 777 MAGE_ROOT/

**Comment by magento-engcom-team** [comment]
@Rinakl , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by Rinakl** [comment]
Thank you for your reply.
It works perfect.

**Comment by magento-engcom-team** [comment]
@Rinakl, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
