### ISSUE TITLE
Less compilation

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#1357]
Hello

When running `grunt watch` or `grunt less` it is generating all the files under `en_US` folder. Having checked the store configuration it is set correctly to `en_GB` and I cant find any configuration that this would require changing in.. 

When loading resources via the webbrowser I can see requests are being made to the `en_GB` folder but I cant reliably get grunt to compile into this location.

```
Running "less:luma" (less) task
File pub/static/frontend/Magento/luma/en_US/css/styles-m.css created: 223.33 kB → 386.88 kB
File pub/static/frontend/Magento/luma/en_US/css/styles-l.css created: 60.83 kB → 104.28 kB

Running "less:backend" (less) task
File pub/static/adminhtml/Magento/backend/en_US/css/styles-old.css created: 176.09 kB → 288.25 kB
File pub/static/adminhtml/Magento/backend/en_US/css/styles.css created: 205.45 kB → 339.75 kB
```

**Comment by villageseo** [comment]
Hi @jamescowie 

For configuration you can try to change the locale property for the appropriate theme ('blank'/'luma') in the file: \dev\tools\grunt\configs\themes.js

Hope it will help. 

Kind Regards,
Oleg

**Comment by vpelipenko** [comment]
@jamescowie, is your issue resolved?
