### ISSUE TITLE
ReferenceError: initializeFieldsetDataByDefault is not defined Magento 2.2.2 Upgrade from Magento 2.0.7

### ISSUE THREAD

**Issue by sanjayjethva** [magento/magento2#13578]
I have upgraded website from Magento 2.0.7 to Magento 2.2.2 but i am unable to load category and products in admin. Its just loading half.
Please see below screenshot for product and category.
https://prnt.sc/iby5fv and https://prnt.sc/ic79if

### Preconditions

1. Magento 2.2.2
2. Standard LAMP environment - PHP 7.1 - MySQL 5.6

### Steps to reproduce

1. Upgrade to Magento 2.2.2 from Magento 2.0.7

### Expected result

1. It must load completely with all info but just loading half.

### Actual result

1. https://prnt.sc/iby5fv and https://prnt.sc/ic79if
2. I am facing error in console
`ReferenceError: initializeFieldsetDataByDefault is not defined`
3. Facing error in Exception log file
`main.CRITICAL: The element 'gallery' already has a child with alias 'content' {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The element 'gallery' already has a child with alias 'content' at /var/www/vhosts/httpdocs/vendor/magento/framework/Data/Structure.php:611)"} []`

**Comment by orlangur** [comment]
> ReferenceError: initializeFieldsetDataByDefault is not defined

Could you please provide full stack trace of this error? Error in exception log seems unrelated

**Comment by sanjayjethva** [comment]
Hi @orlangur ,
ReferenceError: initializeFieldsetDataByDefault is not defined [Learn More] knockout.js%20line%202624%20%3E%20Function:3:62

Thanks

**Comment by cypher909** [comment]
I solved this issue in chrome by opening the inspector, going to the Application tab, and clearing all the site data. Then logged back in and the issue was gone.

**Comment by sanjayjethva** [comment]
Hello @cypher909,
Thanks for your reply.
Yes, my problem get resolved by clearing all the site data.

Thanks
