### ISSUE TITLE
widget category list view not good showing

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#13589]
### Preconditions
Magento ver. 2.2.1
PHP 7.0.25
MySQL 5.6

### Steps to reproduce

1. Insert widget to content --> **category product list** --> Number of Products to Display for example I want 5 and save.

2. Insert widget to content --> **category new product list** --> choosing category and Number of Products to Display for example I want 5 and save.
### Expected result

1. Display 5 products in one line.

2. Display 5 new product in one line.

### Actual result
1. Its only display 4 products in one line and under is the fifth product.

2. Display all 5 new product in one line no issue.

![5 in page](https://user-images.githubusercontent.com/33385380/36039450-7f206ff0-0d90-11e8-9c9c-e90bb9f25faf.PNG)

**Comment by magento-engcom-team** [comment]
@testmagento2, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by RetroModernDev** [comment]
I'm working on it.

**Comment by RetroModernDev** [comment]
@testmagento2  I tested this in Magento 2.2.4-dev and I could not replicate this error. 

<img width="1064" alt="zrzut ekranu 2018-03-14 o 09 58 58" src="https://user-images.githubusercontent.com/11998249/37392448-7ea19eee-276e-11e8-9d1c-cf55a2ef5076.png">

**Comment by ghost** [comment]
Hi @testmagento2 thank you for you report, this issue has already fixed in 2.3-develop branch and available on 2.3.1 release.
