### ISSUE TITLE
Issue in language translation

### ISSUE THREAD

**Issue by Asifjalil99** [magento/magento2#13599]
i am trying to translate magento 2.2 to other languages in magento, all the steps are working fine and translate correctly but few minor changes did not change, I need your help friends.

when i try to translate the popup Newsletter heading its not translating to any language while other things are changed in popup box (the news letter comes from text box of magento admin panel).

close button on news letter popup needs to change.

when 1 item in cart are added its not translating but when 2 items or more are added its translated.

delete item in cart is translated while edit item in cart is not translated.

need to translate All Category headings some of my coding is also attached please check and give me a idea is there anything wrong in the code? thanks 

![category and cart picture](https://user-images.githubusercontent.com/35948773/36065214-8ac33e62-0eb9-11e8-9db1-b004d7606c6c.jpg)
![popup changes](https://user-images.githubusercontent.com/35948773/36065215-8c3ebf3c-0eb9-11e8-8dc3-0ff5e0727547.jpg)
![code](https://user-images.githubusercontent.com/35948773/36065218-8ecf0202-0eb9-11e8-81c9-c2f767158d55.png)

**Comment by Asifjalil99** [comment]
any one please urgent help need .. :(

**Comment by orlangur** [comment]
https://github.com/magento/magento2/pull/13528 may be helpful in your case.

**Comment by Asifjalil99** [comment]
@orlangur i already check this but what the meaning of this point.
"Clean Magento installation with a translation file translating the string "Item in Cart" from Magento_Checkout."

**Comment by orlangur** [comment]
@Asifjalil99 it means literally what you already have in description of this issue: there is a custom translation for "Item in Cart", in your case "test item".

So, to summarize, there could still be some places in Magento which are not translatable, you need to check `2.2-develop` to find out whether particular place is already fixed and then backport, if there is still no fix, you need to debug and fix such place by yourself (ideally, providing a PR to this repo so that everybody benefits from it).

**Comment by Asifjalil99** [comment]
@orlangur thanks for your support i already fix it by my self the problem is coming from js-translation.josn file once again thanks for the support. :)

**Comment by orlangur** [comment]
@Asifjalil99 please correct if I'm wrong, it looks like https://github.com/magento/magento2/pull/13471 + https://github.com/magento/magento2/pull/13528 should fix the issue you mentioned completely.

I propose to close this issue for now and reopen it in case additional non-translatable cases will be found.

**Comment by Asifjalil99** [comment]
My issue is not related to like #13471 + #13528 , i just simple add "Item in Cart" in js-translation.josn file manually and its work for me you can close this issue
Thanks for your support.

**Comment by orlangur** [comment]
Thanks!

> simple add "Item in Cart" in js-translation.josn file manually and its work for me

Yeah, and those issues are about such phrase pickep up correctly by phrase collector.

**Comment by Asifjalil99** [comment]
yeah i see lot of people face this kind of issue and i will do another post with full method soon so the issue will be solve :)

**Comment by atolodas** [comment]
Work for me:
Add to: /vendor/magento/module-translation/etc/di.xml
in line ~ 68 
`<item name="translate_args" xsi:type="string"><![CDATA[~translate args\=("|'|"')([^\'].*?)('"|'|")~]]></item>`

Then empty the pub/static/frontend folder and run
and if lang LT 
`php bin/magento setup:upgrade;
php bin/magento setup:di:compile;
php bin/magento setup:static-content:deploy lt_LT;
php bin/magento cache:flush;`

Demo:  [https://mg2.bandom.info](url)
