### ISSUE TITLE
Checkout page is blank

### ISSUE THREAD

**Issue by neetu-mittal** [magento/magento2#13598]
### Steps to reproduce

1.  Install Magento 2.2.0 working fine
2.  after few days run composer which make updates in magento basics
3. Now add to cart working fine
4. but go to cart page, show errors
5. checkout page blank only show logo

### Expected result

1.  proper cart page with totals 
2. checkout page with all data to proceed to payment

### Actual result

1.  
![image](https://user-images.githubusercontent.com/8451427/36062273-a419b06a-0e8e-11e8-80a4-dd5b02e3b995.png)
2. 
![image](https://user-images.githubusercontent.com/8451427/36062280-fb44cb04-0e8e-11e8-8709-af869faa36df.png)

tried all 
again composer update, theme update, setup upgrade, setup compile but noting help

**Comment by magento-engcom-team** [comment]
@neetugoyal , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by neetu-mittal** [comment]
You can check on my site(http://petceutics2.testpad.com.au/), I am not as good in magneto. I have no other developer, done by only read online documentation.  If hire a developer, takes a lot of time and have not enough time. so if anyone can help me its best to me. Thanks in advance. 

one thing that can be issue acc. to me, is that, **data for shipping method not come properly**.

**Comment by koenner01** [comment]
@neetugoyal, do you have any third party modules installed that influence the checkout (i.e custom payment providers, custom shipping providers, etc.) ? If yes, can you try turning them off and see if it fixes anything (you can disable them by running 'php bin/magento module:disable Custom_Module')

You are also running some custom theme which is influencing the checkout quite hard

**Comment by neetu-mittal** [comment]
Did not install any custom module for checkout, but using paid theme uultimo, 
Thanks, I try with disable other modules like Algolia search, maybe somehow checkout effected by these.

**Comment by neetu-mittal** [comment]
Thanks, find issue problem with EWay Payment plugin

**Comment by magento-engcom-team** [comment]
@neetugoyal, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
