### ISSUE TITLE
Customizable Options is not showing on frontend 2.2.2

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#13591]
### Preconditions

1. Import catalog from Magento 1.x to 2.2.2

### Steps to reproduce

1. Visit product with custom options on front-end.

### Expected result

1. Visitor can choose custom options if they exist. 

### Actual result

1. Give options to customer to choose if product has them.

If you visit the product in the backend and then just click "Save", this fixes it. The problem is we have have almost 3,000 products. Is there a way to bulk do this fast?

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.
