### ISSUE TITLE
how to disable qty button from frontend?

### ISSUE THREAD

**Issue by lidiawang** [magento/magento2#13603]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

[
![image](https://user-images.githubusercontent.com/35614931/36069507-32a3ee16-0eb9-11e8-986f-30e4bae9c6a8.png)
](url)

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
