### ISSUE TITLE
Left menu in the fresh Magento 2.2.2 install not working

### ISSUE THREAD

**Issue by AF4Q** [magento/magento2#13601]
I have just did a fresh install of Magento 2.2.2 on a CentOS 7 server running centminmod with PHP 7.1.13 and the left menu in the admin panel is not working. Clicking on the any menu item does nothing.

### Preconditions
1. Magento 2.2.2
2. PHP 7.1.13
3. CentOS 7
4. CentMinMod

### Steps to reproduce
1. Do a fresh Magento 2.2.2 install.
2. Open the admin panel.

### Expected result
1. Clicking on the left menu should open the menu.

### Actual result
1. Nothing happens.
2. Below is a screenshot of errors in the console which I think might be leading to this issue:
<img width="1511" alt="screen shot 2018-02-10 at 11 35 58 pm" src="https://user-images.githubusercontent.com/8633652/36065590-bf62abbc-0ebe-11e8-985a-471e7f26e0f1.png">

**Comment by magento-engcom-team** [comment]
@AF4Q, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
