### ISSUE TITLE
Url key:  was already generated for an item with the SKU

### ISSUE THREAD

**Issue by sergiopera** [magento/magento2#13604]
Hello i get this problem while trying to import via CSV, full message is:

### Message error
Url key: '******' was already generated for an item with the SKU:'*******'. You need to specify the unique URL key manually in rows: 2, 3, 5

Magento version 2.2

### Steps to reproduce
1. Import via CSV 2 products with same same name (URL_KEY blank) 
2. SEO url activated

### Expected result
1. Don't get error, automatically create a URL that doesn't affect SEO

### Actual result
1. 
![image](https://user-images.githubusercontent.com/35791291/36073670-22fc396e-0f13-11e8-8435-7838cc9aedc8.png)

**Comment by orlangur** [comment]
Error message is pretty clear. You actually need to specify the unique URL key manually in specified rows.

> 2 products with same same name (URL_KEY blank)

I don't see any logic in having different products with the same name.

**Comment by sergiopera** [comment]
In a store with 1200 SKU there are repeteated names of products.. For example: 
Solar power bank 10800mah... more if you work with OEM products

**Comment by orlangur** [comment]
Hm, interesting. Those products then belong to different stores?

Unlike Magento 1, in Magento 2 merchant got full control over SEO management, there is no random change of numeric suffix anymore like product-name-1, product-name-2.

As far as I can see from your screenshot merchant should only make like 15-20 decisions about which URL key will product with the same name have. If there were like 100-1000 collisions, I would recommend to implement a one-time script which preprocesses CSV (reads current data and generates URL keys according to needed rules for products with collision).

**Comment by sergiopera** [comment]
No, same store… There are many OEM products that looks similar but are different companies so i can’t put as grouped or configurable

Saludos.

Sergio Damián Pera.

De: Vlad Veselov
Enviado: lunes, 12 de febrero de 2018 8:07 a. m.
Para: magento/magento2
CC: sergiopera; Author
Asunto: Re: [magento/magento2] Url key: was already generated for an itemwith the SKU (#13604)

Hm, interesting. Those products then belong to different stores?
Unlike Magento 1, in Magento 2 merchant got full control over SEO management, there is no random change of numeric suffix anymore like product-name-1, product-name-2.
As far as I can see from your screenshot merchant should only make like 15-20 decisions about which URL key will product with the same name have. If there were like 100-1000 collisions, I would recommend to implement a one-time script which preprocesses CSV (reads current data and generates URL keys according to needed rules for products with collision).

**Comment by nedge2k** [comment]
This is an issue for me too. For example, in automotive products, a "water pump belt" for one engine can be completely different to another engine. I generally have my URL structure as "domain.tld/engine-name/part-category/part-name/". Surely a product belonging to a different category should automatically makes it unique?

**Comment by orlangur** [comment]
@nedge2k as far as I remember, from URL Rewrites perspective there will be no error for "water pump belt" URL Key autogenerated in different categories. Probably there is stricter check during import which mandates any URL Key to be generated only once to avoid heavy check for URL Key uniqueness in every store.

**Comment by lracicot** [comment]
I have the same issue. We have to import CSV data daily and we have over 100k products from many different suppliers, some have the same name and it causes OP's issue.

**Comment by niners52** [comment]
Same issue

**Comment by Longgutou** [comment]
1.  set 'visibility' as 'Not Visible Individually' while trying to import via CSV .
2.  update attribute 'Visibility' at adminhtml page.

Hope it helps.

**Comment by mesnitu** [comment]
Same issue on 2.3.1. Makes it completely impossible to update products via csv even if the url_key is not in the file.

**Comment by mvaisberg** [comment]
someone find any solution here, beside add url_key on the import file

**Comment by iversa** [comment]
I'm dealing with the same issue. I have over 30,000 SKU and there are products in different categories with the same name

**Comment by neobiz** [comment]
Hello,
Same issue in Magento 2.2.6. Have you found a solution ? I have only 6 products for my tests with unique and different SKU / url_key.

**Comment by mvaisberg** [comment]
You have to change every url key in your CSV to be unique.

**Comment by neobiz** [comment]
Every url key in my CSV is already unique. That's why I don't understand the issue.

**Comment by mvaisberg** [comment]
but maybe some of those url-key are already on the Database in another
product.

When i put the unique url in the CSV and compared with the already products
that i have in the DB it works.

**Comment by Jeeva-Rathinam** [comment]
Did anyone found an answer?
