### ISSUE TITLE
Error loading jquery-storageapi and jquery-cookie

### ISSUE THREAD

**Issue by vpietri** [magento/magento2#1360]
Hi,

Magento: 0.74.0-beta12 (Ubuntu: Firefox 31 or Chromium 36)
On each page of the frontend there is two errors from requirejs which cannot load 2 libraries

![errorjs](https://cloud.githubusercontent.com/assets/8598479/8125610/606f40fc-10e7-11e5-85c9-41255a5991c9.png)

**Comment by vortex-mike** [comment]
This seems to be related to/the same issue as https://github.com/magento/magento2/issues/1319

It looks as though parts of the code are expecting jquery-cookies.js and others are looking for jquery.cookies.js... the only way I was able to get it to work was to create 2 files one with "-" and one with "." and now it works just fine and I am not getting an error. This is not an ideal solution. Can the Magento team please take a look at these and make sure the JS files are being called concistently so we aren't getting 404 errors trying to load scripts?

**Comment by vpietri** [comment]
Yep it's a working workaround.

**Comment by vpelipenko** [comment]
@vpietri, it was fixed in https://github.com/magento/magento2/pull/1378. Could you check it again?

**Comment by vpietri** [comment]
It's fixed, thanks.

**Comment by dazimax** [comment]
You could fix this issue by follow up below steps,

  1) Set deploy mode to production - **php magento deploy:mode:set production**
       (js and css minification will works with production mode.If you are in developer mode with code minified above issues will show up as I experienced it. Also verify using echo the print_r($_SERVER) in index.php that production mode is set before load the website)

  2) Clear all the caches setup in server
        **/etc/init.d/nginx restart**  
        **/etc/init.d/php5.6-fpm restart**
        **/etc/init.d/varnish restart**

  3) Clear the browser cache and view it in incognito mode. That's it! 

Cheers!
