### ISSUE TITLE
facebook integration with Magento2

### ISSUE THREAD

**Issue by emilshamloo** [magento/magento2#13605]
I try to integrate my Magento2 to facebook.
I am following this guide:
http://docs.magento.com/m2/ce/user_guide/marketing/social-connect-to-facebook.html
When I try to activate "Magento social", 
The integration ask for approve for accessing to my API, and I allow it,
Then I get this error:
"bool(false) string(294) "Authorization: OAuth oauth_consumer_key=r6ya61ggdhrvaoyh8qy5ebrrjxkgyi4x,oauth_nonce=7b424d41e8d28e0a4044d3c765626489,oauth_signature_method=HMAC-SHA1,oauth_timestamp=1518361997,oauth_version=1.0,oauth_verifier=hjoj21pw2oye8btfwcsbsq2upjs716oq,oauth_signature=msfMQimZA%2BMBwJJin%2F1klDctiyA%3D""

I am expecting "success" message, but I do not get it.
I have made a film, you can see on youtube:
https://youtu.be/4M957wZLbpM

**Comment by magento-engcom-team** [comment]
Hello @emilshamloo and thank you for submission!

We've got different results while we were trying to reproduce this issue. At this time collecting information from our internal resources.
We understand that **expected result** looks like this:
![expected](https://user-images.githubusercontent.com/31669971/36105879-690eeb66-101e-11e8-94b7-c7fc64ff7247.png)
and the **actual result** looks like this:
![actual](https://user-images.githubusercontent.com/31669971/36106017-d4476700-101e-11e8-8a91-00404e3d256a.png)

And we want to acquire some additional information from you. Please give us the answers to these questions:
1) What version of Magento application are you using?
2) Is your Magento installed on a local server or on a public server?
3) How did you manage to deploy Magento and Facebook Social plugin? (git + git, composer + marketplace, other)

And thanks for the video! :+1:

**Comment by emilshamloo** [comment]
1. Magento version:     2.2.2
    2. My site  is in the public server
    3. How did you manage to deploy Magento and Facebook Social plugin? (git + git, composer + marketplace, other)
 I installed my magento from Softaclause, and as I told before I am following this document. http://docs.magento.com/m2/ce/user_guide/marketing/social-connect-to-facebook.html

**Comment by magento-engcom-team** [comment]
Hi @emilshamloo 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please use "Contact Seller" button [on this page](https://marketplace.magento.com/shopialfb-facebook-module.html) to report issue with the extension.

**Comment by stephenbori** [comment]
Hello @emilshamloo - I am receiving exactly the same issue. Did you ever find a fix for this?
