### ISSUE TITLE
Magento auto cancel credit card payment in status notes of order

### ISSUE THREAD

**Issue by shahar-bch87** [magento/magento2#13608]
### Preconditions
Magento 2.1.5
PHP 7
Mysql 5.6

### Steps to reproduce
 On Production Site
1. Place an order frontend using creditcard payment
2. Payment filtered in AsiaPay Dashboard (Electronic Payment Service)
3. Order process in magento backend if payment is valid
4. Order can not be processed
5. Magento backend order status = 'waiting authorization' but the Notes for the order inside the order detail page = 'Cancelled'

On Development Site
1. Place an order frontend using creditcard payment
2. Payment filtered in AsiaPay Dashboard (Electronic Payment Service)
3. Order process in magento backend if payment is valid

### Expected result

1. Order status will only change once the order is either got cancelled or proceed to process

### Actual result

In Production Site some orders got cancelled in order detail page in magento backend but error cannot be reproduce in development because there was no error being returned.

PS: we migrated from magento 1 to magento 2 no such issue was encountered in magento 1

![screen shot 2018-02-12 at 3 06 02 pm](https://user-images.githubusercontent.com/13197694/36086330-a572ca9a-1006-11e8-830f-1ec3135756d8.png)

**Comment by magento-engcom-team** [comment]
@shahar-bch87, 
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
