### ISSUE TITLE
Checkout: Fatal error: Uncaught Error: Call to a member function getItemVirtualQty() on null

### ISSUE THREAD

**Issue by ahmedzainsalem** [magento/magento2#13606]
**Preconditions**
Magento   version 2.1.2
PHP   7.0.27
 
**Steps to reproduce**

I've added MSP_CashOnDelivery module in Magento2 with composer

composer require msp/cashondelivery
composer update
php bin/magento module:enable MSP_CashOnDelivery
php bin/magento setup:upgrade
php bin/magento cache:flush

 
**Actual result**

After completing the download process

i logged into the backend page
-Go to Stores > Configuration > Sales > Payment Methods > Cash On Delivery
-Enabled > YES
-download msp_cashondelivery.csv file
-Change the CSV file and upload using the "browse" button and Save
-Go home page and choose a product then go to the page
-And when entering the page of checkout,I did not find anything that was white
-click view source , i found that error

Fatal error: Uncaught Error: Call to a member function getItemVirtualQty() on null in /home/tshirtfa/public_html/vendor/msp/cashondelivery/Model/Payment.php:43
  | Stack trace:
  | #0 /home/tshirtfa/public_html/vendor/magento/module-payment/Helper/Data.php(140): MSP\CashOnDelivery\Model\Payment->isAvailable(NULL)
  | #1 /home/tshirtfa/public_html/vendor/magento/module-vault/Model/Ui/VaultConfigProvider.php(84): Magento\Payment\Helper\Data->getStoreMethods('1')
  | #2 /home/tshirtfa/public_html/vendor/magento/module-vault/Model/Ui/VaultConfigProvider.php(60): Magento\Vault\Model\Ui\VaultConfigProvider->getVaultPaymentMethodList()
  | #3 /home/tshirtfa/public_html/vendor/magento/module-checkout/Model/CompositeConfigProvider.php(32): Magento\Vault\Model\Ui\VaultConfigProvider->getConfig()
  | #4 /home/tshirtfa/public_html/vendor/magento/module-checkout/Block/Cart/Shipping.php(54): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
  | #5 /home/tshirtfa/public_html/vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml(28): in /home/tshirtfa/public_html/vendor/msp/cashondelivery/Model/Payment.php on line 43

**Comment by orlangur** [comment]
Hello @ahmedzainsalem. This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.
