### ISSUE TITLE
2.2.2 setup upgrade takes almost a week to complete

### ISSUE THREAD

**Issue by bydrei** [magento/magento2#13611]
Upgrading from 2.1.9 to 2.2.2 takes almost a week on a website with tens of millions of records for the following tables:

```
catalog_category_entity_datetime
catalog_category_entity_decimal
catalog_category_entity_int
catalog_category_entity_text
catalog_category_entity_varchar
catalog_product_entity_datetime
catalog_product_entity_decimal
catalog_product_entity_int
catalog_product_entity_text
catalog_product_entity_varchar
```

### Preconditions

1. Magento 2.1.9 upgrading to 2.2.2
2. PHP 7.0.27
3. MySQL
4. Have millions of rows in total for the above tables.

### Steps to reproduce

1. Upgrade to 2.2.2
2. Once you do a setup:upgrade it just stays there for ever.

### Expected result

1. setup:upgrade shouldn't take that long

### Actual result

1. Setup:upgrade takes almost a week to upgrade

### The actual issue
Debugged through the code and the issue starts here
/vendor/magento/module-catalog/Setup/UpgradeData.php line 393
```
if (version_compare($context->getVersion(), '2.2.2') < 0) {
     $this->upgradeWebsiteAttributes->upgrade($setup);
}
```
You have do this query when fetchAttributeValues is called
```
SELECT `cpei`.*, `st`.`website_id` FROM `catalog_category_entity_datetime` AS `cpei`
 INNER JOIN `catalog_eav_attribute` AS `cea` ON cpei.attribute_id = cea.attribute_id
 INNER JOIN `store` AS `st` ON st.store_id = cpei.store_id WHERE (cea.is_global = 2) AND (cpei.store_id <> 0) AND (`cpei`.`value_id` > 0) ORDER BY `cpei`.`value_id` ASC
 LIMIT 100
```
Then you have an insert which looks like this in executeInsertions() in /vendor/magento/module-catalog/Setup/UpgradeWebsiteAttributes.php
```
INSERT INTO 
            catalog_product_entity_decimal(attribute_id, store_id, row_id, `value`)
            VALUES 
            (:attribute_id0,:store_id0,:entity_id0,:value0)
            ON duplicate KEY UPDATE `value` = VALUES(`value`)
```
Wouldn't it be possible to add more filtering to the first select query and include only key values that do not match, so that the insert query goes through less rows?

**Comment by orlangur** [comment]
Thanks @ferrazzuk, closing this issue as a duplicate, let's consolidate our efforts in earlier report.
