### ISSUE TITLE
Performance on Language\Dictionary::getDictionary can be improved 

### ISSUE THREAD

**Issue by larsroettig** [magento/magento2#13617]
### Preconditions
1.  PHP 7.0 - Magento 2.1  EE or CE

### Steps to reproduce
1.  Call a Category Page with xProf

### Expected result
1.  Magento\Framework\App\Language\Dictionary::getDictionary call only 1. time 

### Actual result
1.  Magento\Framework\App\Language\Dictionary::getDictionary call only 3. time cost 80ms if the  site not in FPC if use AWS with NFS Share 500ms on ever cache no match 

<img width="1401" alt="xhprof__hierarchical_profiler_report_und__mysql_5_7_17__hallhuber_magento2" src="https://user-images.githubusercontent.com/5289370/36103690-5d86fd6e-1010-11e8-8e51-58d3d8ad2eda.png">

**Comment by magento-engcom-team** [comment]
@larsroettig, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

**Comment by larsroettig** [comment]
Hi @magento-engcom-team okay, i try this on a blank 2.3dev  and write you an update on the two following business days.

**Comment by magento-engcom-team** [comment]
@larsroettig, any updates? We should close this issue as inactive.
