### ISSUE TITLE
CMS Pages/Blocks and Products not loading in backend

### ISSUE THREAD

**Issue by acejakk** [magento/magento2#13610]
### Preconditions
1. Magento 2.2.2
2. PHP 7.1.13
3. CentOS 7
4. Nginx

### Steps to reproduce
1. Do a fresh Magento 2.2.2 install.
2. Open the admin panel.

### Expected result
1. Clicking on Pages, Blocks or Products should display the corresponding content

### Actual result
1. Pages show the spinning wheel but no content is loaded. No error log whatsoever. No console error in the inspector aswell.

Currently in developer mode, I am working normally in Windows 10 and hosts file changed to the server IP, locally.
After pointing the domain to this server and trying to access it, everything except these section work as intended. 
Mind you that if I still change the hosts file to the server IP, all sections show up as intended.

**Comment by orlangur** [comment]
>  No error log whatsoever. No console error in the inspector aswell.

This is pretty strange. In network tab, do you see all files successfully loaded (JS/HTML)?

**Comment by acejakk** [comment]
Yes, all of them. All minify options are also off. 
Everything in the frontend works as intended. 
It is indeed pretty strange since all I need to do is change my hosts file to point to the server ip and it works, which leads me to belive it could be server related, although I don't know how.
I even checked if it could be a memory issue, but everything is according to Magento 2 specifications. 
My main issue here is that I am unable to undestand how I could debug this particular problem. 
I looked for similar posts/issues but there are none with aswers to them.

**Comment by acejakk** [comment]
I started looking into server problems regarding this issue and found out that PageSpeed for Nginx was causing this issue ( All minify, etc., options on magento2 are disabled ).
Disabling it solved my issue. 
I wonder if I can replicate this issue with my exact server configuration on the cleanest magento 2.2.2 installation and PageSpeed for Nginx on, since I also have Magento 1.9 running on the server with no issues whatsoever regarding this particular module.

**Comment by magento-engcom-team** [comment]
@acejakk, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
