### ISSUE TITLE
Magento webinstaller stops at 70%

### ISSUE THREAD

**Issue by thimmey** [magento/magento2#1361]
Hello, 

I try to install magento Version 0.74.0-beta12 and followed the faq for doing so on a fresh mysql database without any previous installation. (cloning the github repository, composer install, running weburl)

unfortunately the installation stops at 70% with Module 'Magento_Catalog':
Installing data.. 

Any ideas what i can do? I also tried installing magento through commandn line, but I dont get anything except the message "X-Powered-By: PHP/5.5.21 Content-type: text/html"

**Comment by andrewtch** [comment]
Same issue here, but o be more precise it is a FK error:

```
[ERROR] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'' in 
```
and
```
Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY', query was: INSERT INTO `catalog_product_link_type` (`link_type_id`, `code`) VALUES (?, ?)' in 
```

**Comment by andrewtch** [comment]
Also, by cleaning up everything another error popped up:

```
Installing customers:
[ERROR] exception 'Exception' with message 'Warning: fopen(): Filename cannot be empty in /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Helper/Csv/Reader.php on line 64' in /Users/andrejscirkovs/Documents/web/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:59
```

**Comment by mazhalai** [comment]
@thimmey @andrewtch do you have previous installations of magento? Can you try `bin/magento setup:uninstall` before installing?

**Comment by andrewtch** [comment]
It stops at 70% first time with and wo sample data; second time works and _without_ sample data install completes.
If I try to import sample data (both during install and after install), data version beta-12, it ends with ``fopen(): Filename cannot be empty`` error, console and Web.

Everything, of course, is being tested with clean database, edge ``develop`` and wiping magento dir.

**Comment by thimmey** [comment]
@mazhalai there is no previous isntallation. clean folders and db

**Comment by giklou** [comment]
Same problem here, I tried to install the Versions 0.74.0-beta12 and 0.74.0-beta13 without success

**Comment by xcomSteveJohnson** [comment]
I expect you've seen this but just in case:
Install sample data before installing Magento: http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html#instgde-install-sample-enable-before

Install sample data after you install Magento: http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html#instgde-install-sample-enable-after

**Comment by andrewtch** [comment]
Both.

"Install before" - dies on 70%, on retry, halts on 97%.
"Install after" - on fopen error.

**Comment by xcomSteveJohnson** [comment]
I wonder if there are common factors. What web server are @andrewtch, @thimmey and @giklou using? PHP version? MySQL version? OS?

**Comment by andrewtch** [comment]
fopen() error renders both on console and web installs, so I suppose it is a fixture issue.

php - latest brewed 5.6, on 10.10 osx, 5.6 mysql.

**Comment by thimmey** [comment]
Php 5.5.21 mysql 5.6. Os i don't know yet. Im not able to restart the installation, it say then service unavailable.

**Comment by giklou** [comment]
PHP 5.5.9-1ubuntu4.9
OS mysql 5.6.19-0ubuntu0.14.04.1
Ubuntu 14.04.2 LTS
@xcomSteveJohnson

**Comment by xcomSteveJohnson** [comment]
The other obvious thing to check is the version of the sample data module. Check to make sure that the version in composer.json is at least magento/sample-data:0.74.0-beta10. Versions earlier than that had known issues but IIRC it manifested when it was installing Orders, not Catalog.

**Comment by craigcarnell** [comment]
I have the same issue, clean install

**Comment by andrewtch** [comment]
@xcomSteveJohnson , beta12 as mentioned above. self.verion also tried.

**Comment by thimmey** [comment]
@xcomSteveJohnson my composer.json file doesnt contain any sample-data entry.

**Comment by thimmey** [comment]
And if you look the github composer.json there is also no sample-data entry.

**Comment by thimmey** [comment]
Anything new?

**Comment by buskamuza** [comment]
Hi all, let's clarify what we have now. Looks like, there are several people with the same issue. So I have few questions for each of you (to ensure that we wave same issues or maybe they are different):
1. Does it happen for Web Installer only? Or it also stops for CLI installer?
2. If the same issue is present for CLI installer, please, provide full command you used and output (at least last ~20 lines).
3. Could you, please, provide `php -i` output?
4. If there is an error with `fopen()`, could you, please, enable xDebug and run the installation again to see, if it will show back trace for the error?
5. Just in case, maybe someone has this issue on Vagrant or Docker? We could try same image to debug.

**Comment by andrewtch** [comment]
Olga,

1. Both
2. Standard install as pec documentation
3. https://gist.github.com/andrewtch/b5f8e1f97f23e1e6dfe0
4. I can provide a trace:
```
➜  magento2 git:(develop) ✗ bin/magento  sampledata:install admin -v
Installing theme:
.
Installing customers:


                                                                                                                                                           
  [Exception]                                                                                                                                              
  Warning: fopen(): Filename cannot be empty in /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Helper/Csv/Reader.php on line 64  
                                                                                                                                                           


Exception trace:
 () at /Users/andrejscirkovs/Documents/web/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:59
 Magento\Framework\App\ErrorHandler->handler() at n/a:n/a
 fopen() at /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Helper/Csv/Reader.php:64
 Magento\SampleData\Helper\Csv\Reader->load() at /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Helper/Csv/Reader.php:78
 Magento\SampleData\Helper\Csv\Reader->reload() at /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Helper/Csv/Reader.php:180
 Magento\SampleData\Helper\Csv\Reader->rewind() at /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Module/Customer/Setup/Customer.php:127
 Magento\SampleData\Module\Customer\Setup\Customer->run() at /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Module/Customer/Setup.php:36
 Magento\SampleData\Module\Customer\Setup->run() at /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Model/Installer.php:95
 Magento\SampleData\Model\Installer->run() at /Users/andrejscirkovs/Documents/web/magento2/setup/src/Magento/Setup/Model/SampleData.php:80
 Magento\Setup\Model\SampleData->install() at /Users/andrejscirkovs/Documents/web/magento2/app/code/Magento/SampleData/Console/Command/SampleDataInstallCommand.php:102
 Magento\SampleData\Console\Command\SampleDataInstallCommand->execute() at /Users/andrejscirkovs/Documents/web/magento2/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Users/andrejscirkovs/Documents/web/magento2/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /Users/andrejscirkovs/Documents/web/magento2/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/andrejscirkovs/Documents/web/magento2/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/andrejscirkovs/Documents/web/magento2/bin/magento:12


sampledata:install [--modules MODULES] [--bootstrap BOOTSTRAP] [--] <admin-user>
```
5. Sorry, no ( local osx install, stock apache 2.4

**Comment by andrewtch** [comment]
However, it's not a clean install but the error is the same.

**Comment by buskamuza** [comment]
Thanks, @andrewtch .
Why I usually ask about exact command - because sometimes it may have a mistake (e.g., typo) or maybe there is some outdated documentation, which we missed, but you still follow. So it's always better to rely only on 100% facts.

Basing on your output, could you, please, check permissions for Magento files? As I understand, in the case you provided output for, this file is not readable `app/code/Magento/SampleData/fixtures/Customer/customer_profile.csv`. Could you, please, check, if the user you run the command can read it?

Another question: what happens when CLI installer stops, if you don't use sample data during installation?

**Comment by buskamuza** [comment]
Could you also try to disable opcache and see if it helps?

I'd also suggest to increase memory_limit to, at least, 768M. We override  the value in `.htaccess` for web requests, but your CLI still uses value from php.ini.

**Comment by thimmey** [comment]
@buskamuza 

The error occurs with webinstaller. When I try installing magento through commandn line, I dont get anything except the message "X-Powered-By: PHP/5.5.21 Content-type: text/html". 

phpinfo -> https://gist.github.com/thimmey/b895c34faf99ce223edf

**Comment by gordonknoppe** [comment]
I experienced this issue as well, installer stopped at 70% during Magento_Catalog install.  My problem in the php error_log was max_execution_time (default: 30 sec) on OOTB Ubuntu 14.04.  I noticed you raise the max_execution_time via .htaccess for the main app but not in setup/.htaccess.  I added the same PHP configuration settings to setup/.htaccess and flushed database for a clean install and it proceeded through fine. 

If the application is supposed to manage all of it's php configuration via .htaccess (something I wouldn't expect a production grade environment to do) then I think the setup/.htaccess would need to be updated as well.

**Comment by thimmey** [comment]
@buskamuza Whats going on with this problem? Any progress?
@gordonknoppe i copied also the .htacess file and replaced the one under setup. unfortunately it didnt helped.

**Comment by mazhalai** [comment]
@thimmey 
> When I try installing magento through commandn line, I dont get anything except the message "X-Powered-By: PHP/5.5.21 Content-type: text/html".

Looks like you are trying the old CLI command, did you try `bin/magento setup:install`? More details [here](http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-install.html)

**Comment by buskamuza** [comment]
@thimmey , looks like you use PHP CGI instead of PHP CLI for command line
```
Server API	CGI/FastCGI
```

Please, ensure that you use correct PHP, so `Server API` should be `Command Line Interface`.

Does `./bin/magento` now should only this line `X-Powered-By: PHP/5.5.21 Content-type: text/html`? Nothing else?

**Comment by thimmey** [comment]
@mazhalai @buskamuza 
Both commands show only that line "X-Powered-By: PHP/5.5.21 Content-type: text/html"

How can I check if it uses cgi? Actually the PHP CLI is installed.

However, the web installer should also work and not stop at 70% with nothing...

**Comment by buskamuza** [comment]
@thimmey , in `php -i` there is `Server API`. In your case it shows `CGI/FastCGI`.
Also because your PHP is CGI, you see everything displayed as HTML even for command line tools.

bq. However, the web installer should also work and not stop at 70% with nothing...
You are right. We are trying to understand why it stops in your case. It usually takes some time at that moment, but then goes on. Did you try [the solution](https://github.com/magento/magento2/issues/1361#issuecomment-113487683) from @gordonknoppe ?

**Comment by buskamuza** [comment]
@thimmey , could you also check your Apache error logs right after you tried installation via Setup Wizard? Maybe there are some errors there that can help us to find the cause of the issue.

**Comment by dfediuk** [comment]
My quick and dirty fix for «fopen(): Filename cannot be empty» when installing with sample data: https://mage2.pro/t/topic/13

**Comment by buskamuza** [comment]
Internal ticket MAGETWO-40412

@dfediuk , thanks for the investigation! We'll review it and see how we can fix it in the core.

**Comment by vnagara** [comment]
I have the same error: stops on 70% and in logs:
~~~
   ......
   Module 'Magento_Catalog':
   Installing data.. 
~~~
How I can view the logs of ongoing processes? Or trace log?
Thanks.

**Comment by buskamuza** [comment]
@vnagara , all messages should be displayed in the console log. We'll check why in some cases the messages do not appear there.

**Comment by vnagara** [comment]
I have installed it by console command 
~~~
     bin/magento setup:install --db-name=magento2 --db-password= ....
~~~
So I guess it is broken by "max_execution_time". As on grep command I didn't find redefinition of it in setup action.

**Comment by vnagara** [comment]
And really I would prefer to install magento by console as I have more powerful configurations for CLI.
I mean if final stage of web installing will generate the proper console command and it is enough.

**Comment by dougkm** [comment]
@buskamuza - Has this issue been resolved?

**Comment by vnagara** [comment]
@buskamuza For me it has been resolved. Some one show me good command to clean up all caches. It's resolved this stopping. Don't remember exact but smth lile: rm cache/* (here should be list of temporary dirs).

**Comment by buskamuza** [comment]
`rm var/*` can be helpful.

**Comment by xcomSteveJohnson** [comment]
@vnagara You can also look at a general reference: http://devdocs.magento.com/guides/v2.0/howdoi/php/php_clear-dirs.html

**Comment by daim2k5** [comment]
Fixed. If not please feel free to reopen the issue.
