### ISSUE TITLE
Duplicate urls- Seo purpose

### ISSUE THREAD

**Issue by priti-rathee** [magento/magento2#13626]
### Preconditions

1. Magento 2.2.2
2. Php 7.0.24

### Steps to reproduce

1. Hit link www.xxxx.com/contact/ -> contact page appears
2. Hit link www.xxxx.com/contact -> again contact page appears

### Expected result

1. only one url should work and the other should redirect automatically to other
i.e., either with slash or without slash . 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@priti-rathee, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
There is no bug in current behavior, this issue can be treated as a feature request though.

Another possible option is using rel=canonical, so, such new introduced behavior should be configurable instead of just 301 redirects.

**Comment by priti-rathee** [comment]
I tried it in layout file but it din't work. Please tell me where i went wrong.
I tried adding below code in default.xml as well as contact_index_index.xml file.

      <link rel="canonical" src="contact" src_type="url"/>
</head>
Please tell me the correct way to add it.

**Comment by yumicom** [comment]
same issue

**Comment by Alex-Sy** [comment]
@magento I'm working on it

**Comment by Alex-Sy** [comment]
This is not a bug. If redirects are needed, use the server settings.
