### ISSUE TITLE
issue with products in a cart magento 2.2 backend,please help

### ISSUE THREAD

**Issue by primzonltd** [magento/magento2#13622]
**I am having an issue with products in a cart. I am using magento 2.2 as a backend and I get an error which in the admin panel. If I go to Reports and then click products in cart, it leads me to an error page.**
1 exception(s):
Exception #0 (Exception): Notice: Undefined offset: 107 in /home/primzonc/public_html/vendor/magento/module-reports/Model/ResourceModel/Quote/Item/Collection.php on line 223

Exception #0 (Exception): Notice: Undefined offset: 107 in /home/primzonc/public_html/vendor/magento/module-reports/Model/ResourceModel/Quote/Item/Collection.php on line 223
#0 /home/primzonc/public_html/vendor/magento/module-reports/Model/ResourceModel/Quote/Item/Collection.php(223): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/home/primzonc/...', 223, Array)
#1 /home/primzonc/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(588): Magento\Reports\Model\ResourceModel\Quote\Item\Collection->_afterLoad()
#2 /home/primzonc/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(559): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#3 /home/primzonc/public_html/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(480): Magento\Framework\Data\Collection\AbstractDb->load()
#4 /home/primzonc/public_html/vendor/magento/module-reports/Block/Adminhtml/Shopcart/Product/Grid.php(63): Magento\Backend\Block\Widget\Grid\Extended->_prepareCollection()
#5 /home/primzonc/public_html/vendor/magento/module-backend/Block/Widget/Grid.php(403): Magento\Reports\Block\Adminhtml\Shopcart\Product\Grid->_prepareCollection()
#6 /home/primzonc/public_html/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(507): Magento\Backend\Block\Widget\Grid->_prepareGrid()
#7 /home/primzonc/public_html/vendor/magento/module-backend/Block/Widget/Grid.php(468): Magento\Backend\Block\Widget\Grid\Extended->_prepareGrid()
#8 /home/primzonc/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Backend\Block\Widget\Grid->_beforeToHtml()
#9 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('adminhtml_shopc...')
#11 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml_shopc...')
#12 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml_shopc...')
#13 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml_shopc...', true)
#14 /home/primzonc/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml_shopc...', true)
#15 /home/primzonc/public_html/vendor/magento/module-backend/Block/Widget/Grid/Container.php(119): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid')
#16 /home/primzonc/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/container.phtml(13): Magento\Backend\Block\Widget\Grid\Container->getGridHtml()
#17 /home/primzonc/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/primzonc/...')
#18 /home/primzonc/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Reports\Block\Adminhtml\Shopcart\Product), '/home/primzonc/...', Array)
#19 /home/primzonc/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/home/primzonc/...')
#20 /home/primzonc/public_html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#21 /home/primzonc/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#22 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('adminhtml\\shopc...')
#24 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml\\shopc...')
#25 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml\\shopc...')
#26 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml\\shopc...', true)
#27 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml\\shopc...')
#28 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#29 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#30 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#31 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#32 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#33 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#34 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#35 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#36 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#37 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#38 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#39 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#40 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#41 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#42 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#43 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#44 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#45 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#46 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#47 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#48 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#49 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#50 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#51 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#52 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#53 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#54 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#55 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#56 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#57 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#58 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#59 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#60 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#61 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#62 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#63 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#64 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#65 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#66 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#67 /home/primzonc/public_html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#68 /home/primzonc/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#69 /home/primzonc/public_html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#70 /home/primzonc/public_html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /home/primzonc/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /home/primzonc/public_html/vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 /home/primzonc/public_html/vendor/magento/module-reports/Controller/Adminhtml/Report/Shopcart/Product.php(27): Magento\Framework\App\View->renderLayout()
#74 /home/primzonc/public_html/vendor/magento/framework/App/Action/Action.php(107): Magento\Reports\Controller\Adminhtml\Report\Shopcart\Product->execute()
#75 /home/primzonc/public_html/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#76 /home/primzonc/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#77 /home/primzonc/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Reports\Controller\Adminhtml\Report\Shopcart\Product\Interceptor->___callParent('dispatch', Array)
#78 /home/primzonc/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Reports\Controller\Adminhtml\Report\Shopcart\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#79 /home/primzonc/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Reports\Controller\Adminhtml\Report\Shopcart\Product\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#80 /home/primzonc/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Reports\Controller\Adminhtml\Report\Shopcart\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#81 /home/primzonc/public_html/generated/code/Magento/Reports/Controller/Adminhtml/Report/Shopcart/Product/Interceptor.php(26): Magento\Reports\Controller\Adminhtml\Report\Shopcart\Product\Interceptor->___callPlugins('dispatch', Array, NULL)
#82 /home/primzonc/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Reports\Controller\Adminhtml\Report\Shopcart\Product\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#83 /home/primzonc/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#84 /home/primzonc/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#85 /home/primzonc/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#86 /home/primzonc/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#87 /home/primzonc/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#88 /home/primzonc/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#89 /home/primzonc/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#90 {main}

**Comment by magento-engcom-team** [comment]
@primzonltd, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by primzonltd** [comment]
Hi Thanks for getting back to me.
Magento ver. 2.2.0 
Well I don't know why its on this installation I tested the same version on different domain where it has no issue. Admin panel > Reports and >Products in Cart.
Expeted result it should show the products in cart if there are any incomplete purchases but its not  showing the the error page as shown above.
Actual result should be  normal products in cart page with or without any products.

I made the copy of this site as well and the error remains  on the duplicate site as well.

**Comment by magento-engcom-team** [comment]
@primzonltd Unfortunately we are unable to provide any assistance unless issue is reproducible with the described steps on our side.
Please attempt this flow on the latest version without any extensions enabled. If the issue persists please update bug report with all the required information and reopen.
Thank you for collaboration.

**Comment by ajayjaiswalweb** [comment]
Hi @primzonltd ,

I am facing exact same issue. Can you please let me know did you get the solution of this issue?

Magento ver. 2.2.0

1 exception(s):
Exception #0 (Exception): Notice: Undefined offset: 5 in /Nufoot/nufoot-com/public_html/vendor/magento/module-reports/Model/ResourceModel/Quote/Item/Collection.php on line 223

Exception #0 (Exception): Notice: Undefined offset: 5 in /Nufoot/nufoot-com/public_html/vendor/magento/module-reports/Model/ResourceModel/Quote/Item/Collection.php on line 223
#0 /Nufoot/nufoot-com/public_html/vendor/magento/module-reports/Model/ResourceModel/Quote/Item/Collection.php(223): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/Nufoot/nufoot-...', 223, Array)

**Comment by primzonltd** [comment]
Hi @ajayjaiswalweb ajayjaiswalweb ,
Solution to this issue is 
Magento 2.1 and 2.2. In the following thread of GitHub a user has created a patch which resolves the issue.
> https://github.com/magento/magento2/issues/8724
The patch can be found at this link:
> https://github.com/Radosav/Radosav_ReportFix

How to install
1. Unzip the files and copy them in your Magento document root while overwriting if necessary.
2. Run the following commands in your Magento document root:

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy -f
php bin/magento setup:di:compile
php bin/magento cache:clean
php bin/magento cache:flush

Once all of the above commands have went through without issues, the module should be active. If that is not the case, you can run "php bin/magento module:status" which will provide you with a list of enabled and disabled modules. If the module is disabled, you will need to run the following:

php bin/magento module:enable MODULENAME

Where "MODULENAME" is replaced with the name of the actual module as listed by the previous command.

Please keep in mind that we advise ALWAYS generating a backup of your website's files and database before making any such changes to ensure that the website can be restored in case anything goes wrong.
