### ISSUE TITLE
Order Last Increment id 

### ISSUE THREAD

**Issue by vasudevsundar** [magento/magento2#13624]
I need to set last increment id. I changed in eav_entity_store to set order id. Even though i modified, but not changing Order Increment Id. It starts from 0000001,0000002 , i need as 10000540, 10000541. Give me a suggestion to changes this in magento 2.2.x

**Comment by magento-engcom-team** [comment]
@vasudevsundar, thank you for your report.
This seems to be correct Magento behavior, but this behavior will be changed soon. We have some information here #11702.
This pull request is merged and going to be delivered to Magento 2.2.4.
Don't want to wait? Create a patch from PR and apply to your system. Do it at your own risk or ask someone for help.

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Check [this question on Forum]( https://magento.stackexchange.com/questions/101341/magento-2-what-is-the-correct-way-to-change-default-order-id)
