### ISSUE TITLE
The admin interface locale is not "sticky" and reverts to en_US

### ISSUE THREAD

**Issue by hillzzz** [magento/magento2#1362]
If you change the interface Locale setting in the Admin interface at the bottom of the page it works for one session but if you leave/close the admin interface and come back later the locale setting is forgotten and has to be re-set

**Comment by Vinai** [comment]
BTW, the same is true for Magento 1 so it might be expected behavior.
Workaround: changing the default scope locale in the store config also switches the admin panel locale permanently.

**Comment by piotrekkaminski** [comment]
@hillzzz did you try changing the locale in your account settings? I think there is an option for that and it should be persistent.

**Comment by hillzzz** [comment]
Hi I did change the locale and it did not make a difference however this is now rather out of date and so i will try again on the latest version.
Hillary
07919 488425
zen71001@zen.co.uk
