### ISSUE TITLE
Overriding class not working

### ISSUE THREAD

**Issue by jackengine** [magento/magento2#13628]
### Preconditions
1. PHP 7.0.10
2. MySQL 5.7.14
3. Magento 2.1.10

### Steps to reproduce
1. Fresh Install
2. Add Configurable Product with Customizable option  [Checkbox as Selectable option] 
3. Create module that overrides functionality \Magento\Catalog\Block\Product\View\Options\Type\Select
4. Visit item page on frontend.

### Expected result
1. Should show Checkboxes of Cutomizable options

### Actual result
1. Only Configuration options are shown.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

Overriding a whole class works just fine in fact and is enforced with automated tests. Probably you didn't clear cache or something.

**Comment by jackengine** [comment]
No worry. Issue is with magento 2.1.10 ,With magento 2.2.x  overriding  select class works fine (I checked 2.2.0). However it is still there with Magento 2.1.10 with clean install.

**Comment by orlangur** [comment]
Is it hardcoded somewhere so that DI preference does not work?
