### ISSUE TITLE
installing magento 2.2.2 via composer get an error

### ISSUE THREAD

**Issue by dariolongo** [magento/magento2#13637]
Hi,

installing magento 2.2.2 via composer get an error

### Preconditions

1.  magento 2.2.2
2. php 7.1.14
3. apache 2.4.27
4. mysql 5.7.20
5. ubuntu 17.10 (server)

### Steps to reproduce

1. I've created a new user and added it to web server group.
`magento_user : magento_user www-data`
2. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`
in the default /var/www/html directory and with magento_user

### Expected result

1. install magento

### Actual result

1.
```
 Installing magento/project-comunity-edition (2.2.2)
     -  Installing magento/project-comunity-edition (2.2.2): Downloading (100%)
Downloading (100%)
Downloading (100%)

[RuntimeException]
Could not delete ./:
```

Did someone fix this?
Thanks?

**Comment by magento-engcom-team** [comment]
@dariolongo thank you for your report
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by dariolongo** [comment]
Ok, thanks.

For anyone who stumbles in this problem:
from sudo:
mkdir magento
chmod 777 magento
chown magento_user:magento_user magento
then, from magento_user:
composer ecc... works!
By

**Comment by magento-engcom-team** [comment]
@dariolongo, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by EzraCharles** [comment]
I just run the same command "composer create-project –repository-url=https://repo.magento.com/ magento/project-community-edition ." with sudo and it worked for me.
