### ISSUE TITLE
Cart is not working because of an incorrect path

### ISSUE THREAD

**Issue by Opticcenter** [magento/magento2#1363]
in file customer-data.js

`/pub/static/frontend/Magento/blank/en_US/Magento_Customer/js`

change line 11 
 `    'jquery/jquery-cookie' `

to
`    'jquery/jquery.cookie' `

**Comment by guz-anton** [comment]
Thanks for pointing. I've created internal issue MAGETWO-38732.

**Comment by vpelipenko** [comment]
@Opticcenter, this issue is resolved and available from beta15. Could you verify it and let us know if it is still reproducible for you?
