### ISSUE TITLE
"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

### ISSUE THREAD

**Issue by mariamghalleb** [magento/magento2#13644]
## Preconditions:
Magento 2.2.1 
Php 7.0.27

## Steps to reproduce: 
I'm wanted to give the website a password so i edited .htaccess with these lines: 
```
AuthType Basic
AuthName "For admins only."
AuthUserFile /home/mypath/public_html/.htpd
Require valid-user
```
## Expected Result:
Only access the website with a password. 

## Actual Result: 
The password worked but i started recieving this alert every time  i login in the back office.

> "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

with this error in console: 

> GET https://dev4.wetag.ca/admin_l610t/admin/noroute/index/key/b7269d71b0801bbae9777c2d8b9e6ea4e40c3d633d412201b7f7c0a945821/ 404 (Not Found)

with the error in jquery.js: 
```
// handled in jQuery.ajax (so no try/catch here)
xhr.send( ( options.hasContent && options.data ) || null );
```
And in networks it says: 

> JavaScript may be disabled in your browser. To use this website you must first enable JavaScript in your browser.

The JavaScript is enabled in my browser or any other browser that I used, any way to fix this? 
Thank you

**Comment by magento-engcom-team** [comment]
@mariamghalleb thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add also information from logs for analysis.

**Comment by magento-engcom-team** [comment]
@mariamghalleb, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@mariamghalleb thank you for your report.
In this case please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
