### ISSUE TITLE
Magento 2  display Out-of-stock products on left navigation of the category page

### ISSUE THREAD

**Issue by bhagyashri-indusa** [magento/magento2#13648]
Magento 2  display Out-of-stock products on left navigation of the category page

### Preconditions
Magento Version: 2.1.5 CE
PHP: 7.0.14
Database: MySQL 5.6
OS: CentOS 7
Caching: Varnish Cache and OPcache

### Steps to reproduce

Magento Settings
Show out of Stock Products: Yes
quantity_and_stock_status  attribute: 
Use in Layered Navigation : Filterable(With Results)
Use in Search Results Layered Navigation : Yes
Manage Options : In Stock and Out of Stock
Error: Category page Out Of Stock option  is not visible on left navigation

### Expected result

1.  Category page Out Of Stock option  should be t visible on left navigation

### Actual result

1. Category page Out Of Stock  is not visible 
![leftnavigation](https://user-images.githubusercontent.com/34030628/36197464-ccdc919e-1199-11e8-8d51-4042aa1bfb67.png)

**Comment by magento-engcom-team** [comment]
@bhagyashri-indusa, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by chirag-wagento** [comment]
I am working on this at #dmcdindia

**Comment by chirag-wagento** [comment]
I have follow above step but I can't see **quantity stock** in left layered navigation.

**Comment by lewis-dan** [comment]
I am working on this at #dmcdindia
I am Using Magento 2.2 follow the steps, however,Quantity Stock never visible like this. On the Left Layered Navigation, only Category and Product Attribute will be visible by default. If you want to add Quantity (In Stock and Out Of Stock) we need to follow custom option.

**Comment by therouv** [comment]
@magento-engcom-team give me 2.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @therouv. Thank you for your request.\nUnfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by therouv** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @therouv. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @therouv, here is your [Magento instance](https://i-13648-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-13648-2-2-develop.engcom.dev.magento.com/admin](https://i-13648-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by therouv** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @therouv. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @therouv, here is your [Magento instance](https://i-13648-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-13648-2-3-develop.engcom.dev.magento.com/admin](https://i-13648-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by therouv** [comment]
Issue is not reproducible on vanilla 2.2-develop and 2.3-develop since the attribute is generally not shown anymore.

![tc_1_config](https://user-images.githubusercontent.com/393419/41500415-05c785de-7191-11e8-90eb-8f4efa3e6c1f.jpg)

![tc_1](https://user-images.githubusercontent.com/393419/41500401-d2f2d816-7190-11e8-92a9-45339883fe58.jpg)
