### ISSUE TITLE
Payment issue with paypal and other payment options 

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#13647]
**Preconditions**

M 2.2.2

**Step to reproduce**

1.  Add an item to cart

2.  Checkout as a guest fill all details on checkout page

3. Select shipping and click next to payment page

4. Select Payment method paypal or stripe

5. Paypal express checkout popup screen load and after couple of seconds just vanishes without any errors.

**Expected result**

When clicked on payment method the Paypal popup should load to fill in your account details to continue payment.

**Actual result**

Paypal express checkout popup screen load and after couple of seconds just vanishes without any errors.

Stripe Popup keeps loading but never loads.

![screenshot 49](https://user-images.githubusercontent.com/13229022/36196470-f1b45468-11c4-11e8-942f-9092f079ed9d.png)
![screenshot_1](https://user-images.githubusercontent.com/13229022/36196471-f1ed0e98-11c4-11e8-9705-5b1c13776715.png)

**Comment by magento-engcom-team** [comment]
@terrybakshi , 
thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation without third party code.

![paypal-](https://user-images.githubusercontent.com/31669971/36211302-88e640ce-11a9-11e8-90f7-3d34725fba6f.png)

**Comment by terrybakshi** [comment]
even after setting up the paypal to Website Payments Standard i am getting this error (We can't initialize Express Checkout.) Your can further check the issue on www.toydeals.com.au
![paypal payment issue](https://user-images.githubusercontent.com/13229022/36239882-52e1c09e-1261-11e8-924c-98cc5e68c25d.png)

**Comment by magento-engcom-team** [comment]
@terrybakshi , Payment standart is work correct on fresh installiation,  please check this issue on fresh installiation

**Comment by terrybakshi** [comment]
Thanks for reply but that's not the good response as how many times we need to do fresh installs, to rectify and fix the issues, when will we be able to have a good reliable and stable version in Magento 2.

**Comment by terrybakshi** [comment]
I have tried even after installing a new fresh magento 2.2.2 and still facing same issue where paypal payment method, first time it will work but after clearing cache the popup will appear and disappear without any errors when setting up standard payment method in setting it just gives error (we can't initialize express checkout) so i am definate it is not working can anyone help

**Comment by magento-engcom-team** [comment]
@terrybakshi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
