### ISSUE TITLE
Table rate issue

### ISSUE THREAD

**Issue by 5mehulhelp5** [magento/magento2#1364]
Hello i hope you are fine but i have some problem in table rate 
is there any why where table rate shipping will apply on taxed subtotal (tax including subtotal).

so can we make some admin interface where user choose like apply tax on tax included or tax excluded subtotal.

Thanks Please let me know if you need some more info.

**Comment by choukalos** [comment]
Hello @5mehulhelp5 you can control how shipping is taxed in the Stores/Configuration/Sales/Tax menu.  In particular you can set at the website level if shipping prices include or exclude tax.  You can also set a tax class for shipping which can be associated with a tax rule/rates to handle how much to tax shipping by, etc.

**Comment by 5mehulhelp5** [comment]
Hello @choukalos thanks for replay but i think you miss the point i am taking about the condition of table rate shipping.

like i have a sub total 135$ including tax but excluding tax it's 119$ and in the checkout i am just displaying the subtotal including tax
so at checkout i can only see 135$ including tax

now in my shipping rate i have condition like this if 0 to 120 subtotal then shipping price is 2$ and above 120$ shipping price is 5$

so when i select that table rate shipping method it's show me a shipping cost $2 but my check out has $135 which is a tax including price so it should display a 5$ instead of $2

subtotal: 135$ including tax
shipping: $2 but condition is 120<  $2 and 120> $5.

Thanks But please let me know if you still need any detail from my side.

**Comment by choukalos** [comment]
Switching assignee to Illia; this is more shipping logic related then Tax related.  

@ilol - it seems like we only calculate the threshold based on subtotal excluding tax for shipping table rates.  Perhaps we should adjust the algorithm so if you have shipping prices including tax that it calculates them off the subtotal include tax amount?  Do we have VAT merchants who expect the current behavior - i.e. subtotal excluding tax for shipping rate breakpoints?  I'd think we wouldn't want to introduce another configuration option so really boils down to what's commonly expected for this.

**Comment by ilol** [comment]
@5mehulhelp5 please, explain the nature of tax. As mentioned @choukalos , if they use VAT, the including VAT to final price of order is natural. Do customer expect that the final price = price incl. tax?
You could tune your rules and get expected result. Or do you use the same rule for international shipping and internal shipping? Please, clarify the initial conditions. Thank you

**Comment by 5mehulhelp5** [comment]
as @choukalos  describe above it's not related about tax but it's more regarding shipping price calculation method.

because if user only display a tax including final price in total section then shipping price should display according to that.

but in my case it's taking a tax excluding price for get the shipping price.

Thanks Please let me know if you still have a problem to understand this.
i will explain in more detail.

**Comment by wsakaren** [comment]
There are 2 requirements, 1 is to tax based on tax exclusive, the other tax inclusive. There are similar requirements around discounts. Extensions typically handle these, if you go switching it to the other way then its going to cause issues for thousands of people. I'd suggest you leave as is and let the extensions do their work. There are only a few scenarios when need tax incl prices, tends to be stores where they sell a mix of taxable and non-taxable goods, which is quite rare. Otherwise people can work it out (may be clunky but can do).

**Comment by ilol** [comment]
@wsakaren, thank you for answer. Really the question is quite controversial. I would leave it temporary as is. I am investigating the option with additional conditions for table rate

**Comment by andidhouse** [comment]
hi there,
is this solved somehow? 
we in Germany also calculate ALL prices INKL. tax - so it is really confusing to us.

Is there now a way to calculate shipping on subtotal incl. tax via table rates?

Many thanks!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Table-rate-issue/idi-p/45449).
