### ISSUE TITLE
how to get store currency from rest api?

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1365]
I'm able to get product information from rest call.but unable to find out any call related to store currency information.

**Comment by choukalos** [comment]
Hi @sivajik34 this has been noted as a story bug that needs to be addressed.  We did add this information to sales & quote apis.  We've decided instead to create a store service to provide this information.  It'll be available before GA.  Ticket:  MAGETWO-38989

**Comment by mazhalai** [comment]
@sivajik34 This issue has been resolved. Closing ticket.

**Comment by Sharmilasrini95** [comment]
Hi @sivajik34 

Have you  got the fix?

**Comment by agrohs** [comment]
What is the endpoint for it??

**Comment by rimom** [comment]
> What is the endpoint for it??

<host>/rest/<store>/V1/directory/currency
