### ISSUE TITLE
magento 2 setup:static-content:deploy memory error

### ISSUE THREAD

**Issue by mdinfo007** [magento/magento2#13650]
Hi,

I am trying to install quick setup of theme also did but css and js is not loading so i run command.
php bin/magento setup:static-content:deploy -f 
but every time getting error like memory error
is there any solution?

Thanks

**Comment by RahulBhut21** [comment]
You can pass memory limit parameter.
`php -dmemory_limit=5G bin/magento setup:static-content:deploy`

**Comment by mdinfo007** [comment]
ohk i got it but now i am getting error for execution time.what should i do for this?

**Comment by gfxguru** [comment]
Increase your memory and execution time in your php config. but it doesn't
fix the issue. I had these issues years ago with Magento 2 and still
wondering why I'm wasting my time with this platform.

**Comment by orlangur** [comment]
@gfxguru Magento cannot fix your PHP configuration. Recommended settings are sufficient for builtin Luma theme and languages, in case of heavy customization you'll need to adjust configuration values.

**Comment by orlangur** [comment]
Closing in favor of https://github.com/magento/magento2/issues/13656. @mdinfo007, please do not produce additional issues for the same topic.

**Comment by mdinfo007** [comment]
ohk but i didn't get my solution is there any solution for execution time error?

**Comment by congson95dev** [comment]
In my case, even using ` php -dmemory_limit=5G bin/magento setup:static-content:deploy`, its still appear that issue `out of memory` @@.
