### ISSUE TITLE
Best sellers sort and auto move out of stock products to the bottom

### ISSUE THREAD

**Issue by winterk80** [magento/magento2#13669]
I would like to submit a feature request. Problem exists in 2.1.7+ and also 2.2.2

1) Magento lacks proper inventory management of out of stock products. Out of stock products should automatically move to the bottom of the product listing page and then automatically move back up to the top when they come back in stock. This should be independent of the visual merchandiser position for the product. This should be a global move out of stocks products to bottom of product listing option.  

2) Magento should also allow for sorting sort order by bestsellers in the visual merchandiser clients. It is very cumbersome how it is currently. Bestsellers should be based upon number of orders that the item exists in not based upon quantity in each order. This is because if you have an item that is typically ordered in multiples it will throw off the bestseller ranking.  

3) Additionally showing 90 day sales for each product while visually merchandising would be very very powerful for merchandisers. 

4) Being able to sort by user defined product attributes when adding products in visual merchandiser would be extremely helpful. For example we have a user-defined variable for discontinued. We would like to filter those products out when adding products to categories so they don't get accidentally added

**Comment by winterk80** [comment]
Magento 2.1.7 and Megento 2.2.2

**Comment by magento-engcom-team** [comment]
@winterk80, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hi @winterk80 Thank you for reporting.

Unfortunately we are closing this ticket now, as Github issue tracker is intended only for core Magento technical issues. Please refer to the [Community Forums](https://community.magento.com/) to submit a feature request or use [magento/community-features](https://github.com/magento/community-features/issues) repository to describe your idea.

Thank you for collaboration!
