### ISSUE TITLE
Add Simple Product from admin

### ISSUE THREAD

**Issue by bhavin88** [magento/magento2#1366]
![url_key](https://cloud.githubusercontent.com/assets/12870148/8149203/c4bd1d84-12d8-11e5-9dcb-48e0d81122d4.png)
Hello,

I have try to add simple product from admin. I have added product details and hit on save button then it give errors : URL key for specified store already exists.

**Comment by ishakhsuvarov** [comment]
Hi,
Could you please provide some additional information regarding this issue? Is it a fresh Magento installation? Did you change something in configuration or using a stock config?
This would greatly help us to reproduce this case and find a best solution.

**Comment by orlangur** [comment]
Looks like there is a `test` category present in the system too? When autogenerated URL key already exists in store, merchant should go to `Search Engine Optimization` tab and enter another value manually.

**Comment by kokoc** [comment]
@bhavin88 Could you please try solution provided by @orlangur?

**Comment by bhavin88** [comment]
Yes, you are right test category present in the system.

**Comment by bhavin88** [comment]
I have now just change my product name test to test product and now it is working fine.
