### ISSUE TITLE
Can not be translated to another language

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#13666]
### Preconditions

1.  Magento 2.2.2

### Steps to reproduce

1.  Reset password
2. Reset password email message 
**Problem that message can not translated to another language.**
`If you requested this change, set a new password here:`
3.  domain/customer/account/createpassword/
4. Set a new password
**Problem that message can not translated to another language.**
`Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.`

### Expected result

1.  Translating to other languages

Reset password email message
> If you requested this change, set a new password here:

Set a new password
> Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored. 

**Tested** 
Using translate .csv file and translate inline tool. Doesn't work.

**Comment by Asifjalil99** [comment]
Manually put your text "Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored." in js.translate.json and then call it from .csv file.
some time translate words is not store or recall from js.translate.json file 
as i mention above edit the json file then run these commends from SSH, rename the name of the language to your .csv file name e.g  lt_LT to ru_RU etc

find . -name js-translation.json -exec rm -rf {} \;
php bin/magento setup:static-content:deploy en_US -f
php bin/magento setup:static-content:deploy lt_LT -f
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush

**Comment by Userr017** [comment]
Where is correct js-translation.json file? I have translated using language .csv file, message `"Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.","second language"`

**Comment by Asifjalil99** [comment]
you can type it like this 
"Your text","2nd language",module,Magento_Customer 
where "Customer" is the name of module so in your case check  the name of module and call it.

**Comment by magento-engcom-team** [comment]
Hello @Userr017. Thanks for reporting. Please tell us what locale You use.

**Comment by Userr017** [comment]
@magento-engcom-team 
Local is fi_FI. 

I fixed these problems. Language package was a mistake. 
I change `"Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored."` to this `"Minimum length of this field must be equal or greater than %1 symbols. Leading and trailing spaces will be ignored."`

**Comment by magento-engcom-team** [comment]
@Userr017, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
