### ISSUE TITLE
UI component grid works incorrect

### ISSUE THREAD

**Issue by RomaKis** [magento/magento2#13660]
UI component grid selecting elements works incorrect.

### Preconditions
1. Fresh M2 version 2.2 installation.
2. Three simple product "Simple 1", "Simple 2" and "Simple 3" are created.

### Steps to reproduce
1. Go to creation of new Bundle product.
2. Open Bundle Items tab -> press "Add option" -> "Add Products to Option"
3.  Choose "Simple 1" -> press "Add selected product"
4. Click on "Add Products to Option" again -> Choose "Simple 2"
5. Check checkbox where you can select\deselect all element.

### Expected result
1. Checkbox should have option "Select All"

### Actual result
1. Checkbox has option "Deselect All"
![screenshot from 2018-02-14 17-16-14](https://user-images.githubusercontent.com/17450979/36211703-ab0edcc8-11aa-11e8-887a-79a5bf101ef5.png)
![screenshot from 2018-02-14 17-16-25](https://user-images.githubusercontent.com/17450979/36211704-ab2d4906-11aa-11e8-8657-b89f11a3e825.png)

**Comment by magento-engcom-team** [comment]
@RomaKis, thank you for your report.
We've acknowledged the issue and added to our backlog.
