### ISSUE TITLE
« Use default value » unchecked when collapsible not collapsed in admin

### ISSUE THREAD

**Issue by real34** [magento/magento2#13665]
Related https://github.com/magento/magento2/issues/8897 https://github.com/magento/magento2/issues/12881

### Preconditions
1. Tested on the latest `2.2-develop` branch to date 
2. PHP 7.0.13

### Steps to reproduce
1. In multi-store mode
2. Create a new category
3. Edit this new category in store view mode
4. Save without changing anything or collapsing any panel

### Expected result
1. No data changed

### Actual result
All « Use default value » checkboxes in collapsible panels are checked, and related attributes have store values in EAV values tables.

Video illustrating the bug: https://www.useloom.com/share/f3bc6a2c290647ac902f00a6c76dcb12

Note: the values displayed are `var_dump($categoryPostData['use_default']); die;` in https://github.com/magento/magento2/blob/dcd0dbcd670aae172fb0582c1d725d3d69abd063/app/code/Magento/Catalog/Controller/Adminhtml/Category/Save.php#L130

---

This issue is also present on the product edit page. Video: https://www.useloom.com/share/b500d0236e7940caae4d6630617cd151

It has been mentioned in a more global thread at https://github.com/magento/magento2/issues/12881#issuecomment-361883152 but I think it is critical enough to deserve its own issue ;)

Only « Use default value » checkbox seems to be concerned (e.g « Use Config Settings » is not, and configuration scopes not either). Video: https://www.useloom.com/share/f2360ecd978549ce977ad2fc95396e6a

**Comment by magento-engcom-team** [comment]
@real34, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by koenner01** [comment]
We can confirm this issue (and had also reported it on the support cloud already)

**Comment by royandre** [comment]
We can also confirm this bug. Also we must point out this is such a major flaw in a very basic and heavily used feature that we have for the reason of this and other similar bugs decided to put on hold _all_ multi-site M2 installations until further.

**Comment by kega-jira** [comment]
We can confirm this issue, also already reported it in the Magento support system

**Comment by real34** [comment]
Any ideas about where to start digging?

**Comment by engcom-Delta** [comment]
@real34 thank you for your report. I am not able to reproduce issue by steps you described on 2.4-develop

![#13665issue](https://user-images.githubusercontent.com/51681379/71660837-f1799000-2d54-11ea-837c-0fe5c412112c.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
