### ISSUE TITLE
String class name issue for php7

### ISSUE THREAD

**Issue by sidealice** [magento/magento2#1367]
Fatal error: Cannot use 'String' as class name as it is reserved in lib/internal/Magento/Framework/Data/Argument/Interpreter/String.php on line 14

**Comment by alankent** [comment]
Yes, there are a few similar class named we hit when we tried php 7 as well. Good news was there were not many that needed to be renamed to get php to work. (I don't recall where that got to on the backlog.)

**Comment by orlangur** [comment]
PHP7 is not supported yet: https://github.com/magento/magento2/blob/develop/composer.json#L11

There are more reserved words which needs to be considered: http://php.net/manual/en/reserved.other-reserved-words.php The most frequently used in code base is `object` I believe.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-37817

**Comment by dccampbell** [comment]
Just for reference, a quick scan for classes w/ newly reserved words as names:

    app\code\Magento\Backend\Model\Resource\Translate\String.php
    app\code\Magento\CatalogImportExport\Model\Import\Proxy\Product\Resource.php
    app\code\Magento\Eav\Model\Entity\Increment\Numeric.php
    app\code\Magento\Translation\Model\Resource\String.php
    app\code\Magento\Translation\Model\String.php
    dev\tests\functional\lib\Magento\Mtf\Util\Generate\Repository\Resource.php
    lib\internal\Magento\Framework\Acl\Loader\Resource.php
    lib\internal\Magento\Framework\Acl\Resource.php
    lib\internal\Magento\Framework\Data\Argument\Interpreter\Object.php
    lib\internal\Magento\Framework\Data\Argument\Interpreter\String.php
    lib\internal\Magento\Framework\DB\Logger\Null.php
    lib\internal\Magento\Framework\Filter\Object.php
    lib\internal\Magento\Framework\Flag\Resource.php
    lib\internal\Magento\Framework\Module\Resource.php
    lib\internal\Magento\Framework\Object.php
    lib\internal\Magento\Framework\Search\Request\Filter\Bool.php
    lib\internal\Magento\Framework\Search\Request\Query\Bool.php
    lib\internal\Magento\Framework\Validator\Float.php
    lib\internal\Magento\Framework\Validator\Int.php
    lib\internal\Magento\Framework\Validator\Object.php
    lib\internal\Magento\Framework\Validator\Test\Unit\Test\Int.php
    lib\internal\Magento\Framework\Validator\Test\Unit\Test\True.php
    lib\internal\Magento\Framework\View\Layout\Argument\Interpreter\Object.php

**Comment by craigcarnell** [comment]
@vpelipenko Any chance you will also be fixing Magento 1.9?

```
A minor incompatibility has to be fixed before using Magento with PHP 7.

You have to modify the file app/code/core/Mage/Core/Model/Layout.php on line 555:

Modify the line so it looks like this:

$this->getBlock($callback[0])->{$callback[1]}();
```
Source - http://afilina.com/magento-1-9-on-php7/

Also I am unable to login to /admin

**Comment by vpelipenko** [comment]
@craigcarnell, probably yes, but I don't know when.

**Comment by vpelipenko** [comment]
Adaptation of code to PHP7 was done and all changes are available in develop branch. Please, try this. If you have any question or face with new issues, please, let us know.

**Comment by dccampbell** [comment]
I just tried the latest develop code on the rasmus/php7dev Vagrant box and still got the same error as in the OP of this issue.

Also, composer.json currently only allows PHP 5.5.x and 5.6.x.

**Comment by orlangur** [comment]
@dccampbell, there is no `String` class in `develop` anymore, it was renamed to `StringUtils`: https://github.com/magento/magento2/tree/develop/lib/internal/Magento/Framework/Data/Argument/Interpreter

**Comment by dccampbell** [comment]
Finally got a box setup. Install went fine but when I hit any page I get:
`==> default: Fatal error: Uncaught ErrorException: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/www/magento2/var/session/) in /var/www/magento2/lib/internal/Magento/Framework/Session/SessionManager.php:139`

Not sure if my environment (Debian8 guest on Win7 host), or PHP7-related. Session folder permissions are 777.

**Comment by dccampbell** [comment]
In case this helps anybody w/ testing, I've made my Vagrant setup available: 
https://github.com/dccampbell/php7dev-magento2

Tested smooth on Ubuntu14 and Win7 hosts. So far no issues to report, though I'm holding out for a new sample data version that's usable with the current develop branch to really test it hard.

**Comment by craigcarnell** [comment]
@vpelipenko 

I created an issue on Magento 1 bug tracker..

http://www.magentocommerce.com/bug-tracking/issue/index/id/994

Since the search feature does not work.. I'm not sure if anyone else appeared to report it.

Also the whole system is susceptible for XSS by placing javascript in the comments section.. just so you know.

**Comment by davidc-abt** [comment]
No issues so far on the new PHP7 RC, although still waiting on sample data support to make a more thorough pass.

**Comment by dccampbell** [comment]
No issues so far on the new PHP7 RC, although still waiting on sample data support to make a more thorough pass.

**Comment by piotrekkaminski** [comment]
@dccampbell it works for us now. Please reopen the ticket if you still have this problem.

**Comment by mc388** [comment]
When is this available for the merchant beta?

**Comment by markoshust** [comment]
I'm assuming this is all ready in https://github.com/magento/magento2/releases/tag/1.0.0-beta4

**Comment by dccampbell** [comment]
Of note, as of 1.0.0-beta4 the composer.json is still restricted to PHP ~5.5.0|~5.6.0.

**Comment by mc388** [comment]
I'm using the merchant beta and PHP 7 is not working

**Comment by markoshust** [comment]
the merchant beta tag is an older snapshot -- you'll need to use the `1.0.0-beta4` branch/tag.
