### ISSUE TITLE
Tax is based on Shipping origin (and shouldn't)

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#13674]
Hello,

### Preconditions
1. Magento 2.2.2

### Steps to reproduce
1. Create a FR website, store and store view (just rename the default one)
2. Create an US website, store and store view
3. Go to Stores > Configuration > General > Currency setup for the FR website and set everything to EUR
4. Go to Stores > Configuration > General > Currency setup for the US website and set everything to US
5. Set Catalog Price Scope to website in Stores > Configuration > Catalog > Catalog > Price
6. In Stores > Configuration > Sales > Tax, set all configurations to including tax
7. In Stores > Configuration > Sales > Tax > Default Tax Destination Calculation, set a random address in France for the FR website and a random address in the US for the US website
8. In Stores > Configuration > Sales > Shipping settings, set Origin to a random address in France
9. Go to Stores > Tax zones and rates and add a new tax rate of 20% for France
10. Go to Stores > Tax zones and rates and add a new tax rate of 0% for US (* as Zip code)
11. Go to Stores > Tax rules, add a new tax rule and select the two previously created tax rates
12. Create a simple product and set its price to 50 on FR website and 50 to US website
13. Go on the product page in front on FR and US websites

### Expected result
1. The price should be 50 on US website and 50 on FR website with respectively 0 and 20% tax.

### Actual result
1. The price is 50 on FR website but 41.67 on US website

It works if on US website I set the Shipping Origin to a random US address but it's not what I want and IMO it should not depend on this configuration because the tax calculation is based on the shipping address.

**Comment by magento-engcom-team** [comment]
Hello @VincentMarmiesse. Thanks for reporting. Now lets look what happens to the product on the US website for two cases separately. 
Case 1: Default Tax Destination Calculation = USA and Shipping Origin = France.
Case 1: Default Tax Destination Calculation = USA and Shipping Origin = USA.

**So Case 1**. The product has a price of 50$ including tax whatever it is. And the tax in France which is the place where the product, so to say, comes from (France is the product's Shipping Origin) is equal to 20%. So this product has a pure, excluding tax, price equal to 41.67$ (50$ - 20%). As the tax is imposed on it as in US (Default Tax Destination Calculation is set to USA), where it is equal to 0%, the price of the product the customer will buy it at is equal precisely to those 41.67$.

**Now Case2**. The product has a price of 50$ including tax whatever it is. And the tax in USA which is the place where the product, so to say, comes from (USA is the product's Shipping Origin) is equal to 0%. So this product has a pure, excluding tax, price equal to 50$ (50$ - 0%). As the tax is imposed on it as in US (Default Tax Destination Calculation is set to USA), where it is equal to 0%, the price of the product the customer will buy it at is equal precisely to those 50$.

Would that explanation suite You?

**Comment by VincentMarmiesse** [comment]
Hello @magento-engcom-team,

You described exactly what happens yes, my issue concerns the first case.

Why does the product have a 20% tax if it's shipped to the US? Magento should calculate tax this way IMO (but maybe I'm wrong):

- Product price is $50
- Product price is set to including tax in config
- Product price in front should be $50 no matter the destination, shipping or anything else
- Product tax should be 20% if shipped to France, 0% if shipping to the US

So we should have in the checkout totals something like:

Total | Shipping to the US | Shipping to France
------ | ------------------------- | -------------------------
Excluding tax | 50 | 41.67
Tax | 0 | 8.33
Grand total | 50 | 50

What do you think about it?

**Comment by VincentMarmiesse** [comment]
After some tests and asking to the french community, setting `CrossBorderTradeEnabled` (`tax/calculation/cross_border_trade_enabled`) to Yes has solved my issue.

Can you confirm it's what I was supposed to do?

**Comment by magento-engcom-team** [comment]
Please @VincentMarmiesse consider these two:
http://docs.magento.com/m2/ce/user_guide/shipping/point-of-origin.html and
http://docs.magento.com/m2/ce/user_guide/Search.html#search-Cross-Border Trade. Does they answer Your question?

**Comment by VincentMarmiesse** [comment]
Hello @magento-engcom-team,

Yes it was exactly what I needed.

Thank you!

**Comment by magento-engcom-team** [comment]
@VincentMarmiesse, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
