### ISSUE TITLE
Installation navigation bar goes circle

### ISSUE THREAD

**Issue by eralaz** [magento/magento2#13676]
### Preconditions

1.  Magento 2.2.2 open source(community edition)
2. Download via composer. Using composer-create command.

### Steps to reproduce
1. Download Magento 2 open source
2. Open Web Setup Wizard page
3. Being on readiness check step 1 click button back
4. You'll get to install step directly

### Expected result
1.  As I understand the installation bar must be left to right oriented only.
2. Click back button being on the first step lead must do nothing.

### Actual result
1.
<img width="1100" alt="screen shot 2018-02-15 at 1 38 43 pm" src="https://user-images.githubusercontent.com/4068905/36255042-0feee2fe-1256-11e8-97e7-6d72efe9852b.png">
2. Click back button
3. 
<img width="1184" alt="screen shot 2018-02-15 at 1 43 00 pm" src="https://user-images.githubusercontent.com/4068905/36255072-2ef84db6-1256-11e8-83de-5d9b22fec9e8.png">

**Comment by magento-engcom-team** [comment]
@larylaz, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by yogeshsuhagiya** [comment]
#14309 Disable "Back" button on the first step of the setup

**Comment by eralaz** [comment]
Great! And the main issue is on what progress?
