### ISSUE TITLE
Change the Base Url causes the admin lose its CSS style

### ISSUE THREAD

**Issue by vshijiav** [magento/magento2#13684]
After I change my website url to a new one
The admin CSS style lost....
And when I check the source code 
the CSS file were all point to the localhost

<link  rel="stylesheet" type="text/css"  media="all" href="http://localhost/pub/static/version1518723545/adminhtml/Magento/backend/en_US/extjs/resources/css/ext-all.css" />
--
  | <link  rel="stylesheet" type="text/css"  media="all" href="http://localhost/pub/static/version1518723545/adminhtml/Magento/backend/en_US/extjs/resources/css/ytheme-magento.css" />
  | <link  rel="stylesheet" type="text/css"  media="all" href="http://localhost/pub/static/version1518723545/adminhtml/Magento/backend/en_US/jquery/jstree/themes/default/style.css" />

I`ve tried many ways to fix this
change the permission, change the di.xml, etc. running several command try to rebuild everything...
Nothing happend

Anyone with ideas?

Im on a local ubuntu 1604 server
running magento 2.1.10

**Comment by magento-engcom-team** [comment]
@vshijiav  thank you for your report,
Please try to run the following commands:
```
php bin/magento cache:clean
php bin/magento setup:static-content:deploy
```

**Comment by vshijiav** [comment]
Hello, I tried those command already
It does not work
I`m on magento 2.1.10
The CSS style in admin still point to the localhost
Is there any file/database I can modify manually to set the path?

**Comment by magento-engcom-team** [comment]
@vshijiav, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by btwq** [comment]
I'm working on this #MLAU18

**Comment by magento-engcom-team** [comment]
@vshijiav, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by rashigoyal14** [comment]
Hi All,
Hope you are doing well.I have also came crossed this issue and is solved now.
Changes I did :
Just go to database and open table core_config_data.There will be two entries of web/secure/base_url & web/unsecure/base_url . Just change the url to your default url i.e. http://127.0.0.1/magento/ and your problem will be solved.

And for changing base url please r & d with new tutorial.

Thanks
