### ISSUE TITLE
Mini cart Magento 2.2.2 (Non English Front End)

### ISSUE THREAD

**Issue by ldopierala** [magento/magento2#13683]
### Preconditions
1. Magento 2.2.2
2. Php 7.0.27
3. Nginx
4. Luma Theme
5. No plugin or module except mage plage translation
6. Front End non US (french)

### Steps to reproduce
1. Add an item to purchase
2. Mini cart sho 1 item
3. Click on Mini cart 

### Expected result
1. The button is blue and the link (Proceed check out not clickable and no text)

Whith Chrome client I have this error 👍 Uncaught ReferenceError: Unable to process binding "if: function (){return getCartParam('summary_count') }"
Message: Unable to process binding "if: function (){return getCartParam('possible_onepage_checkout') }"
Message: Unable to process binding "click: function (){return closeMinicart() }"
Message: closeMinicart is not defined
    at click (eval at createBindingsStringEvaluator (knockout.js:2624), <anonymous>:4:87)
    at newValueAccessor (knockout.js:3839)
    at init (knockout.js:3849)
    at init (knockout.js:3842)
    at knockout.js:2989
    at Object.ignore (knockout.js:1249)
    at knockout.js:2988
    at Object.arrayForEach (knockout.js:151)
    at applyBindingsToNodeInternal (knockout.js:2974)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:2854)
![mini cart](https://user-images.githubusercontent.com/2504537/36262728-8bf8510c-1268-11e8-96e3-9690802c1bbe.JPG)

When I switch Front End to English it's working !!!!

js-translation.json  have proceed checkout

### Actual result
1. [Screenshot, logs]

Any trick to resolve it ? A beer for the guy's who found any trick

**Comment by ghost** [comment]
@ldopierala, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
