### ISSUE TITLE
AdminGWS. Install schema breaks magento installation

### ISSUE THREAD

**Issue by zhartaunik** [magento/magento2#13696]
Environment does not matter.

To reproduce this issue you simply need to run magento installation (I did it from console) with existing config.php file, which have modules order.

As result I faced with such issue:
```
[Progress: 35 / 1002]
Module 'Magento_AdminGws':
Installing schema... 
                                                                                                                                                   
  [Zend_Db_Statement_Exception]                                                                                                                    
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.authorization_role' doesn't exist, query was: DESCRIBE `authorization_role`  
                                                                                                   
  [PDOException]                                                                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.authorization_role' doesn't exist  
```
It happen because **Magento_AdminGws** is trying to ALTER TABLE `authorization_role`
This table is creating by the module **Magento_Authorization**
But module **Magento_AdminGws** does not depend on **Magento_Authorization**

To fix, please simply add it in **module.xml**

```
    <module name="Magento_AdminGws" setup_version="2.0.0">
        <sequence>
            <module name="Magento_Sales"/>
            <module name="Magento_User"/>
            <module name="Magento_Authorization" />
        </sequence>
    </module>
```

**Comment by orlangur** [comment]
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.

**Comment by dY00Yb** [comment]
Hi,

Same issue : 

`[Zend_Db_Statement_Exception]                                                                                                                    
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'caudalie.authorization_role' doesn't exist, query was: DESCRIBE authorization_role  \n                                                                                                                                                   
Exception trace:\n () at /var/www/caudalie/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
 Zend_Db_Statement_Pdo->_execute() at /var/www/caudalie/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:93
 Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->_execute() at /var/www/caudalie/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
 Zend_Db_Statement->execute() at /var/www/caudalie/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
 Zend_Db_Adapter_Abstract->query() at /var/www/caudalie/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
 Zend_Db_Adapter_Pdo_Abstract->query() at /var/www/caudalie/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:517
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_query() at /var/www/caudalie/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:580
 Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->query() at /var/www/caudalie/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php:171
 Zend_Db_Adapter_Pdo_Mysql->describeTable() at /var/www/caudalie/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:1608
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->describeTable() at /var/www/caudalie/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:905
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->tableColumnExists() at /var/www/caudalie/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:930
Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->addColumn() at /var/www/caudalie/vendor/magento/module-admin-gws/Setup/InstallSchema.php:56
 Magento\\AdminGws\\Setup\\InstallSchema->install() at /var/www/caudalie/setup/src/Magento/Setup/Model/Installer.php:867\n Magento\\Setup\\Model\\Installer->handleDBSchemaData() at /var/www/caudalie/setup/src/Magento/Setup/Model/Installer.php:775
 Magento\\Setup\\Model\\Installer->installSchema() at n/a:n/a\n call_user_func_array() at /var/www/caudalie/setup/src/Magento/Setup/Model/Installer.php:342
Magento\\Setup\\Model\\Installer->install() at /var/www/caudalie/setup/src/Magento/Setup/Console/Command/InstallCommand.php:146
 Magento\\Setup\\Console\\Command\\InstallCommand->execute() at /var/www/caudalie/vendor/symfony/console/Command/Command.php:241
Symfony\\Component\\Console\\Command\\Command->run() at /var/www/caudalie/vendor/symfony/console/Application.php:843
Symfony\\Component\\Console\\Application->doRunCommand() at /var/www/caudalie/vendor/symfony/console/Application.php:193
 Symfony\\Component\\Console\\Application->doRun() at /var/www/caudalie/vendor/magento/framework/Console/Cli.php:104
 Magento\\Framework\\Console\\Cli->doRun() at /var/www/caudalie/vendor/symfony/console/Application.php:117
 Symfony\\Component\\Console\\Application->run() at /var/www/caudalie/bin/magento:23`

Is there a fix planned ?

**Comment by orlangur** [comment]
@dY00Yb nothing has changed, you need to contact support.
