### ISSUE TITLE
Magento admin panel not loading properly

### ISSUE THREAD

**Issue by vpiyappan** [magento/magento2#1369]
After installing Magento 2 the Css and Js files are not loading properly, due to that issue the page design looks bad. Even the Sales, Customer etc links are not clickable.

**Comment by eskaliert** [comment]
I also experience this issue in BACKEND. The links on the left (from SALES to SYSTEM) don't work. DASHBOARD on the left + NOTIFICATIONS + MY ACCOUNT works fine.

**Comment by halk** [comment]
I had to remove `theme-adminhtml-backend`, `theme-frontend-blank` and `theme-frontend-luma` in vendor and run `composer install` again to get it working. This fixed the styles.

However left menus do still not work (even after deploying static files).

**Comment by vpiyappan** [comment]
Hi Guys,

If you are tried installing Magento 2 in windows Machine.

Please follow the steps which resolve the issue for me.

1. Remove everything, except .htaccess file from pub/static folder

2. Open up app/etc/di.xml find the path “Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink” and replace to “Magento\Framework\App\View\Asset\MaterializationStrategy\Copy”

Now you refresh the page it will display proper links.

**Comment by joanhe** [comment]
Thanks for reporting this issue. The internal issue MAGETWO-39652 has been created to track the progress.

**Comment by piotrekkaminski** [comment]
We couldn't reproduce this issue.

**Comment by cucoriedka** [comment]
vpiyappan, Thank you for your solution to the problem! It works great! :)

**Comment by JsKsathiya** [comment]
Thanks It's working @vpiyappan

**Comment by ghkroshnal** [comment]
Hi guys, implementing  solution by 'vpiyappan' front page seems ok but the back end has not stopeed loadng, so what I see in the backend is a loading sign only. I am using xampp 3.2.2 any help into this?
