### ISSUE TITLE
Issue with Paypal pro payment method checkout.

### ISSUE THREAD

**Issue by trushangsuthartri** [magento/magento2#13703]
**Issue Description**

	I have facing issue on Paypal pro payment transaction in magento 2, I have configure with sandbox credentials with all details.
	Payment transaction was approved from paypal response but somehow process is stop on pilot-payflowlink.paypal.com request.

	Can anyone help me with this?

**Preconditions**
	- Magento 2.1.8 CE
	- Magento_Paypal Module 

**Steps to reproduce**
	1) Add product to cart.
          2) Go to checkout page
	3) Checkout with paypal pro payment method.
	
**Expected result**
	- Order will place with paypal pro payment method and redirect to store success page.

**Actual result**
	- It will stop process and show error on console
		Refused to display 'https://pilot-payflowlink.paypal.com/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Additional information**

	- Magento 2 Env.php file setting
		/app/etc/env.php
			'x-frame-options' => 'SAMEORIGIN',

	- Checkout Page : https://goo.gl/vUQT9V
	- Paypal Request Response : https://goo.gl/KVWeAE
	- Magento 2 admin Setting : https://goo.gl/HxMxTT
	- Paypal Merchant Setting : https://goo.gl/jgAwG2

	- Debug Log :

		[2018-02-17 08:02:39] main.DEBUG: array (
		  'request' => 
		  array (
		    'user' => '****',
		    'vendor' => 'tricoredev',
		    'partner' => 'PayPal',
		    'pwd' => '****',
		    'verbosity' => 'HIGH',
		    'BUTTONSOURCE' => 'Magento_Cart_Community',
		    'tender' => 'C',
		    'trxtype' => 'A',
		    'amt' => 0,
		    'currency' => 'USD',
		    'createsecuretoken' => 'Y',
		    'securetokenid' => '8b76b7d92a0154056b218f3328bf0c9b',
		    'returnurl' => /paypal/transparent/response/',
		    'errorurl' => '/paypal/transparent/response/',
		    'cancelurl' => '/paypal/transparent/cancel/',
		    'disablereceipt' => 'TRUE',
		    'silenttran' => 'TRUE',
		    'firstname' => 'Wholesale ',
		    'lastname' => 'Test User',
		    'street' => 'Clothing Store',
		    'city' => 'Melbourne',
		    'state' => NULL,
		    'zip' => '3031',
		    'country' => 'AU',
		    'email' => 'customer_email@gmail.com',
		    'shiptofirstname' => 'Wholesale ',
		    'shiptolastname' => 'Test User',
		    'shiptostreet' => 'Clothing Store',
		    'shiptocity' => 'Melbourne',
		    'shiptostate' => NULL,
		    'shiptozip' => '3031',
		    'shiptocountry' => 'AU',
		  ),
		  'result' => 
		  array (
		    'result' => '0',
		    'respmsg' => 'Approved',
		    'securetoken' => '1rkC8ek4hOUi4x97OhOZE8wwN',
		    'securetokenid' => '8b76b7d92a0154056b218f3328bf0c9b',
		    'result_code' => '0',
		  ),
		) {"is_exception":false} []

**Comment by developerjoe** [comment]
We had the same issue hitting the pilot URL last week. I tested this today and everything is working fine. Are you still experiencing the issue?

**Comment by Denisof** [comment]
@developerjoe I had the issue last week as well. After your message I rechecked and it seems to be working now.

**Comment by trushangsuthartri** [comment]
@developerjoe Yes, now paypal working without any error.

**Comment by magento-engcom-team** [comment]
@trushangsuthartri, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by ghost** [comment]
Magento Version **2.2.3**

Hi guys, I've this same issue but using: **Paypal All-in-one Payment Solutions > Payment Advanced.**
The error says:


> Uncaught DOMException: Blocked a frame with origin "https://pilot-payflowlink.paypal.com" from accessing a cross-origin frame.
> --

**And also continues with:** 

> VM1877 pflPayments.js:80 Frame with URL 'https://pilot-payflowlink.paypal.com/?SECURETOKEN=xxxxxxxxxxxxxx&SECURETOKENID=xxxxxxxxxxxxxxxx&MODE=TEST' attempted to navigate its top-level window with URL 'https://site.com/onestepcheckout/'. Navigating the top-level window from a cross-origin iframe will soon require that the iframe has received a user gesture. See https://www.chromestatus.com/features/5851021045661696. 

I think I'll need to allow paypal as a trusted origin... or there's another way to deal with this?

Thanks
