### ISSUE TITLE
Magento creating URL with double html -  html.html

### ISSUE THREAD

**Issue by saphaljha** [magento/magento2#13705]
### Preconditions

1. Migrated data from Magento 1.9.3.4 to 2.2.1
2. Multiwebsite Magento

### Steps to reproduce

1. First done the migration
2. Create a new sub-category of any category and add some products into that.
3. Now change parent category of that subcategory using drag and from (From admin).
4. Now check the issue in **Marketing** > **SEO and Search** > **URL Re Writes** 
5. Find request path "html.html"

### Expected result

1. It should show the postfix only **.html**

### Actual result

1. It is showing html.html in URL
Screenshot of issue : https://www.awesomescreenshot.com/image/3180076/4a87a2023beae3148c12a3b30460e5f2

Looking forward to hearing back for solution.

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by dnesdeveloper** [comment]
any solution?
