### ISSUE TITLE
Some script result in 404 page error after saving

### ISSUE THREAD

**Issue by sl02** [magento/magento2#13701]
Reference issue #6248.

### Preconditions
1.  Fresh installation of Magento 2.2.2

### Steps to reproduce
1. Go to Content > Configuration > Edit storeview
2. Add script (provided below) either to Html Header > Script & Style Sheets or to Footer > Misceleanous html (both result in same error).

#### Script
(note that I edited to remove identifiable information):
`<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(e){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var e=this.createElement("script");n&&(this.domain=n),e.id="js-iframe-async",e.src="https://assets.zendesk.com/embeddable_framework/main.js",this.t=+new Date,this.zendeskHost="TEST",this.zEQueue=a,this.body.appendChild(e)},o.write('<body onload="document._l();">'),o.close()}();
/*]]>*/</script>`

#### Note:
Some scripts work fine, but others result in a 404 page error (see screenshot). Incidentally, like issue #6248, we are also seeing this error with the Zendesk Chat script. I am still reporting the issue because this exact script is currently used in a Magento 1.9 installation (added in the same way) and it works perfectly, so the script seems ok.

### Expected result
1.  Admin page should be saved successfully and script added to header / footer.

### Actual result
1. 404 page error
![image](https://user-images.githubusercontent.com/22160597/36336943-23a1ac68-135b-11e8-82f3-4db0f7b6b5b8.png)

**Comment by magento-engcom-team** [comment]
@sl02 thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.
![script](https://user-images.githubusercontent.com/31669971/36370266-60551b84-1556-11e8-9a02-7e5fa6be3d2e.png)

**Comment by sl02** [comment]
Hello Magento Team, 
Have a look at this screen capture video that I made:

https://screencast-o-matic.com/watch/cFnqIKoNBw

Again, this is a fresh Magento 2.2.2 installation.
As you can see, I can save a simple "Hello World" script, but when trying to save the Zopim script, I get a 404 error. The Zopim script must be fine because it is currently in use on a Magento 1.9.

Something about the Zopim script triggers the error....

Thanks.

**Comment by sl02** [comment]
This issue has been resolved and can be closed.
For reference, the issue was with ModSecurity; seems like the default settings with the hosting company did not like the Zendesk script. If you are having this issue, check with your hosting company.
