### ISSUE TITLE
EAV Attribute Repository linking to catalog_eav_attribute

### ISSUE THREAD

**Issue by kdemanuele-cw** [magento/magento2#1370]
When creating an EAV entity one can specify an `additional_attribute_table`. However in the class `Magento\Eav\Model\AttributeRepository` the `getList()` function is not adding the specified table, if any, but always linking to `catalog_eav_attribute`.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-39456

**Comment by vpelipenko** [comment]
@kdemanuele-cw, issue is fixed and available in 1.0.0-beta. Please, check the fix.
