### ISSUE TITLE
Parent menu not shown when there's only 1 submenu in admin panel

### ISSUE THREAD

**Issue by rafatga** [magento/magento2#13707]
### Preconditions
1. Magento EE 2.2.1 & Magento EE 2.2.2

### Steps to reproduce

1. Create a module
2. Create a new file menu.xml in folder adminhtml
3. Create new menu like this
`

     <add id="Footballexperience_Base::base" 
            title="FExperience" 
            module="Footballexperience_Base" 
            sortOrder="20" 
            resource="Magento_Customer::customer"/>

        <add id="Footballexperience_Base::manage_stadiums"
             title="Manage Stadiums"
             module="Footballexperience_Base"
             sortOrder="10"
             parent="Footballexperience_Base::base"
             resource="Footballexperience_Base::manage_stadiums"
        />

        <add id="Footballexperience_Base::stadiums"
             title="Stadiums"
             module="Footballexperience_Base"
             sortOrder="10"
             resource="Footballexperience_Base::stadiums"
             parent="Footballexperience_Base::manage_stadiums"
             action="febase/stadium/grid"
        />

`

### Repository test
https://github.com/hi-rafa/magento2test221

### Expected result
When you click the new menu added you should see inside a submenu like this
Manage Stadiums -> Stadiums

<img width="1178" alt="screen shot 2018-02-17 at 5 33 42 pm" src="https://user-images.githubusercontent.com/3813277/36343287-a17887ce-140a-11e8-8918-4271e2d00b62.png">

### Actual result
What you actually see is only the menu Stadiums unless you add more than one submenu.

<img width="1180" alt="screen shot 2018-02-17 at 5 23 19 pm" src="https://user-images.githubusercontent.com/3813277/36343302-b8adac9e-140a-11e8-945b-811b4537a189.png">

### Additional information
If you add 2 submenus it will work

<img width="1180" alt="screen shot 2018-02-17 at 5 20 45 pm" src="https://user-images.githubusercontent.com/3813277/36343303-c464ad26-140a-11e8-8a0d-297558cc7e2a.png">

**Comment by magento-engcom-team** [comment]
@hi-rafa, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by nadeefit6** [comment]
This works fine in Magento Community Version 2.2.1

**Comment by AnthonyCicchelli** [comment]
Can confirm this  is till open on 2.2.3. Any idea what is causing the issue at least?

**Comment by meghapd** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@meghapd thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by SubrataBauri** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @SubrataBauri. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @SubrataBauri, here is your [Magento instance](https://i-13707-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-13707-2-2-develop.engcom.dev.magento.com/admin](https://i-13707-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by saurabh-parekh** [comment]
This same issue is coming in magento community edition 2.2.4

**Comment by sergiynezbritskiy** [comment]
Actually this looks like a feature. Please check this
https://github.com/magento/magento2/commit/d91e96b529e70dcec55d3b5336b471791dc42d54

**Comment by sergiynezbritskiy** [comment]
#kiev-cd

**Comment by magento-engcom-team** [comment]
@sergeynezbritskiy thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sergiynezbritskiy** [comment]
#kiev-cd

**Comment by magento-engcom-team** [comment]
@sergeynezbritskiy thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sergiynezbritskiy** [comment]
@hi-rafa This is actually a feature. This behavior and was added by this commit https://github.com/magento/magento2/commit/d91e96b529e70dcec55d3b5336b471791dc42d54, please check.
so I'm closing this issue

**Comment by karthik32cse** [comment]
@sergeynezbritskiy This issue still persists in Magento EE 2.3. 
Have you fixed this in Magento EE 2.3 or still I have to apply this patch?
Please give your inputs. Thanks in advance.

**Comment by sergiynezbritskiy** [comment]
> @sergeynezbritskiy This issue still persists in Magento EE 2.3.
> Have you fixed this in Magento EE 2.3 or still I have to apply this patch?
> Please give your inputs. Thanks in advance.

@karthik32cse it is not a bug, but feature. so nothing to fix here. Please check the commit from magento core team https://github.com/magento/magento2/commit/d91e96b529e70dcec55d3b5336b471791dc42d54
If you really need this to be fixed, you can try to override those styles

**Comment by milindsingh** [comment]
@magento give me an instance

**Comment by milindsingh** [comment]
@magento I am working on this

**Comment by milindsingh** [comment]
Thanks @sergeynezbritskiy but it still fails if you create a new admin user, and not assign all resource for a menu item.

For example, in Reports section, if you dont add a section resource like "Sales", all  group heading becomes display:none.

**Comment by sergeynezbritskiy** [comment]
@milindsingh so what is the expected behavior here ?
all group heading becomes display:none not because you didn't add the resource to admin role, but because your admin user has only one or less available items in this group.
As far as I see from [that ](https://github.com/magento/magento2/commit/d91e96b529e70dcec55d3b5336b471791dc42d54#diff-f89229301d01ad1813cf1db5f715dfe80b3f560f92ee48e7883837e146634582R451) comment, this was the idea. 
If this is not what you want, just override the styles within your theme. Does this make sense for you ?
