### ISSUE TITLE
v2.2.2 - Adminhtml - Locales Other Than en_US - Static Content Not Deployed

### ISSUE THREAD

**Issue by nikoelgatito** [magento/magento2#13712]
The issue is pretty easy to replicate, as long as you are running Magento version 2.2.2 in production mode and are accessing the backend with a user account with an `Interface Locale` other than `en_US` that wasn't installed. It seems that the backend static file deployment does not generate the backend static files for each user's locale and only generates the en_US version. The backend static file deployment procedure should retrieve a list of all locales used by the different backend users and deploy the static content for each of them by default.

### Preconditions

1. PHP 7.0 with PHP-FPM
2. MariaDB 10.1
3. Magento 2.2.2

### Steps to reproduce [Updated]

1. Install an earlier **Magento 2.1.X** version
2. Create a backend user with a (not installed) locale different then `en_US`
3. Upgrade to **Magento 2.2.2**
4. Set mode to production
5. Deploy static content `php bin/magento setup:static-content:deploy`
6. Log in the backend with that user

_A simpler way to reproduce the issue would be to manually change the locale for the user in the `admin_user` database table to a locale that isn't installed, directly in Magento 2.2.2._

### Expected result

1. All static files are successfully loaded

### Actual result

1. The static files are not loaded, even the logo on the admin login page isn't

### Temporary fix
Manually updating all admin user accounts in the database to set the `interface_local` to `en_US` (default) **SQL Query:**
`UPDATE `[PREFIX_]admin_user` SET interface_locale='en_US';`

**WARNING: This will revert all account's locale to the default en_US.**

**Comment by magento-engcom-team** [comment]
Hello @nikoelgatito> Thanks for reporting. Currently we are not able to reproduce Your issue. Seems we have missed some details. Tell us please this: before You started to create a backend user had You previously installed the whole package of that other locale or You had just chosen any locale other than en_US while creating the user?

**Comment by nikoelgatito** [comment]
Hi @magento-engcom-team,

Thank you for your quick response.

Actually, the locale that was selected for the admin user is not even installed in the `app/i18n` folder.

From memory, in previous Magento versions 2.1.X the admin user config section was letting the user chose any languages, which is where we had changed it to a different English than en_US. Now since 2.2.X the locale dropdown only allows us to select the default en_US version, most probably because no other language pack has been installed. It seems that in earlier 2.1.X Magento versions, the backend static files were requested from en_US as a fallback when the currently set locale wasn't available. We probably never noticed that the en_US files were loaded instead as it was set to en_CA which is similar English.

Now it seems that reproducing this issue in Magento 2.2.2 out of the box isn't possible as the dropdown doesn't allow to select other locale that aren't installed anymore. To reproduce the issue it seems that we should first install a previous Magento version, 2.1.X, then configure the admin user with a different (not installed) locale and then upgrade to Magento 2.2.2 and set it to production following the same _Steps to reproduce_ above. _An easier way to reproduce the issue would be to manually change the locale for the user in the `admin_user` database table to a locale that isn't installed._

This admin user was created a while ago, it most probably was created and configured on earliest 2.1.X versions. This means that every store having a user already configured to use a different locale on an earlier 2.1.X version where this specific locale isn't installed, that is upgrading to 2.2.X, will have static content issues in the backend for that user.

**This seems to be a related issue:**
[https://github.com/magento/magento2/issues/3127](https://github.com/magento/magento2/issues/3127)
In this issue, the user reports that changing the locale while in production mode, the backend can't get the static files as of course they were not generated in the previous deployment. 
Then, as it was reported on an earlier Magento version, other users' experiences are that when they select a different locale then en_US, Magento still falls back to the en_US locale most probably because the other locale had not been installed. It seems to be the opposite behavior.


Setting a fall back to the default en_US locale for the store base url when an other locale **is set but not installed and deployed** seems to be the right solution in all cases to prevent breaking the admin interface when wrong locale is being used or when the locale has been changed on production without the new static files being generated.

**It would also be very helpful to show a warning in a case where the fall back is used as follow:**
_The {{locale}} locale isn't available and en_US is used by default. Please make sure that the {{locale}} locale is installed and deployed._

**Comment by btwq** [comment]
Working on this #MLAU18

**Comment by btwq** [comment]
Not able to replicate. 

As a test, as per user's instructions: 

- Installed 2.1.11. 
- Changed user locale to en_IE
- Upgraded to 2.2.2
- Set to production mode
- pub/static/adminhtml/Magento/backend compiles the required locale folders, in addition to "en_US". In this case, "en_IE" folder exists

**Comment by nikoelgatito** [comment]
@btwq Thank you for trying to reproduce this issue.

This store actually never made it to 2.1.11, I should have been more specific. It was on the earlier 2.1.7 before being upgraded to 2.2.2 therefore I can't pinpoint on exactly which version a change affected the static content.

There was no issue on the 2.1.7 version and as soon as we switched to 2.2.2 this issue appeared in production mode.

Do not hesitate to ask if you have any questions that could help reproducing the issue.

**Comment by btwq** [comment]
HI @nikoelgatito it might be worthwhile to try on a vanilla install and exclude custom modules that may not be compatible post-upgrade to 2.2.2. 

If this is in fact an issue it would be related to 2.2.2. However at this stage I can see setup:static-content:deploy is working properly for both frontend and adminhtml.

**Comment by magento-engcom-team** [comment]
@nikoelgatito, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
