### ISSUE TITLE
Fix testExecuteAjaxRequestException

### ISSUE THREAD

**Issue by peteraba** [magento/magento2#13711]
### Preconditions
Unsure. Feel free to ask questions.

PHP: PHP 7.1.14
Magento: Magento CLI version 2.2.2
MySQL: insignificant
Web Server: inignificant

### Steps to reproduce
Run `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --filter testExecuteAjaxRequestException`

### Expected result
No errors.

### Actual result
```
PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 2.75 minutes, Memory: 302.00MB

There was 1 error:

1) Magento\Ui\Test\Unit\Controller\Adminhtml\Index\RenderTest::testExecuteAjaxRequestException
Error: Call to undefined function Magento\Ui\Controller\Adminhtml\Index\_()

/home/peter/src/github.com/peteraba/magento2-tetobox/app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php:91
/home/peter/src/github.com/peteraba/magento2-tetobox/app/code/Magento/Ui/Controller/Adminhtml/AbstractAction.php:62
/home/peter/src/github.com/peteraba/magento2-tetobox/app/code/Magento/Ui/Test/Unit/Controller/Adminhtml/Index/RenderTest.php:226

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by magento-engcom-team** [comment]
@peteraba , thank you for your report. We cannot reproduce this issue on clean 2.2.2 CE version. Please provide about your environment, where you install M2

**Comment by magento-engcom-team** [comment]
@peteraba, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
