### ISSUE TITLE
Unable to send email Magento 2.2

### ISSUE THREAD

**Issue by DarlingTheEmojiPillow** [magento/magento2#13715]
Hi,

I have been having issues with Magento 2.2 when sending emails (Sign-up email or newsletter emails).

I have enabled email communications in STORES > CONFIGURATION > ADVANCED > SYSTEM and entered the host (darlingstore.net) and the port (465). I don't know why this is happening I am using PHP 7.0 and apache on Cpanel, I used softaculous to install Magento 2.2, maybe since i installed it using softaculous that's why?

I have attached my system.log file and exception.log file.
[update.log](https://github.com/magento/magento2/files/1734433/update.log)
[system.log](https://github.com/magento/magento2/files/1734434/system.log)
[setup.cron.log](https://github.com/magento/magento2/files/1734435/setup.cron.log)
[exception.log](https://github.com/magento/magento2/files/1734436/exception.log)
[debug.log](https://github.com/magento/magento2/files/1734437/debug.log)

If you need more info just ask me!

**Comment by orlangur** [comment]
> [2018-02-18 02:00:20] main.CRITICAL: Exception message: Notice: Undefined index: COC123! in /home/darlpsou/darlingstore.net/vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php on line 127
Trace: #0 /home/darlpsou/darlingstore.net/vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php(127): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/darlpsou/...', 127, Array)
#1 /home/darlpsou/darlingstore.net/vendor/dotmailer/dotmailer-magento2-extension/Model/Mail/Transport.php(18): Zend_Mail_Transport_Smtp->__construct(NULL, Array)
#2 /home/darlpsou/darlingstore.net/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Dotdigitalgroup\Email\Model\Mail\Transport->__construct(NULL, Array)
#3 /home/darlpsou/darlingstore.net/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Dotdigitalgroup...', Array)

This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

> [2018-02-17 10:58:58] main.CRITICAL: Unable to send mail.  {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail.  at /home/darlpsou/darlingstore.net/vendor/magento/module-email/Model/Transport.php:104, Zend_Mail_Transport_Exception(code: 0): Unable to send mail.  at /home/darlpsou/darlingstore.net/vendor/magento/zendframework1/library/Zend/Mail/Transport/Sendmail.php:111)"} []

This looks like server misconfiguration but needs to be debugged on your side anyway.

**Comment by hostep** [comment]
@orlangur: dotmailer is part of core Magento 2.2.2 now ;) (even though it's full of bugs and features which don't make sense to be included in such a module, but whatever)

But you can leave it closed, it does indeed sound more like a server misconfiguration, I'd advise @DarlingTheEmojiPillow to first try it out with a simple php script which calls the `mail` function to see if that is working or not.

**Comment by orlangur** [comment]
@hostep, oh, thanks for pointing that out, I'll need to check full list of builtin extensions. Was aware only of social and shipping ones yet.
