### ISSUE TITLE
Paypal Checkout Issue

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#13721]
**Preconditions**

M 2.2.2

**Step to reproduce**

1. Put Paypal in Live Mode Not Sandbox 

2. Add an item to cart

3. Checkout as a guest fill all details on checkout page

4. Select shipping and click next to payment page

5. Select Payment method paypal or stripe

6. First time the paypal express or standard checkout will work

7. After Clearing Cache Paypal express checkout popup screen will load and after couple of seconds just vanishes without any errors.
8. After Clearing Cache Paypal standard checkout will produce an error we can't initialize express checkout.

**Expected result**

When clicked on payment method the Paypal popup should load to fill in your account details to continue payment.
If Paypal standard method is set, it should redirect to paypal website to make the payment.

**Actual result**

After Clearing Paypal express checkout popup screen load and after couple of seconds just vanishes without any errors.

After Clearing Cache Paypal standard checkout will produce an error we can't initialize express checkout.

Once you put paypal to sandbox method everything works fine in sandbox.

![paypal payment issue](https://user-images.githubusercontent.com/13229022/36364355-da244b38-1597-11e8-985e-6c906431b772.png)

**Comment by KM-HM** [comment]
Magento: 2.1.11
PHP: 7.0.28-0ubuntu0.16.04.1
OS: Ubuntu 16.04.4 LTS

**Preconditions**
Magento Version 2.1.11 Community Version
PayPal Express Checkout Live Mode
**Steps to reproduce**
Add any product to cart
Go to checkout payment page
Choose PayPal
Click Pay with PayPal
Redirect to empty cart error message: "We can't initialize Express Checkout."

Same issues on 2.1.11. From what I can tell this will not happen on all quotes.
This happening on a live site and is quite hard to test.

`system.log:18866:[2018-03-19 14:50:41] main.CRITICAL: Exception message: We can't initialize Express Checkout.
system.log-18867-Trace: #0 [REMOVED/]vendor/magento/module-paypal/Controller/Express/AbstractExpress/ReturnAction.php(31): Magento\Paypal\Controller\Express\AbstractExpress->_initCheckout()
system.log-18868-#1 [REMOVED/]vendor/magento/framework/App/Action/Action.php(102): Magento\Paypal\Controller\Express\AbstractExpress\ReturnAction->execute()
system.log-18869-#2 [REMOVED/]vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
system.log-18870-#3 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Paypal\Controller\Express\ReturnAction\Interceptor->___callParent('dispatch', Array)
system.log-18871-#4 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Array, 'contextPlugin')
system.log-18872-#5 [REMOVED/]vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18873-#6 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18874-#7 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Array, 'customer-app-ac...')
system.log-18875-#8 [REMOVED/]vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18876-#9 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18877-#10 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Array, 'storeCheck')
system.log-18878-#11 [REMOVED/]vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18879-#12 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18880-#13 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Array, 'weee-app-action...')
system.log-18881-#14 [REMOVED/]vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18882-#15 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18883-#16 [REMOVED/]vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Array, 'tax-app-action-...')
system.log-18884-#17 [REMOVED/]vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Paypal\Controller\Express\ReturnAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18885-#18 [REMOVED/]vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Express\ReturnAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18886-#19 [REMOVED/]var/generation/Magento/Paypal/Controller/Express/ReturnAction/Interceptor.php(26): Magento\Paypal\Controller\Express\ReturnAction\Interceptor->___callPlugins('dispatch', Array, Array)
system.log-18887-#20 [REMOVED/]vendor/magento/framework/App/FrontController.php(55): Magento\Paypal\Controller\Express\ReturnAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
system.log-18888-#21 [REMOVED/]vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
system.log-18889-#22 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
system.log-18890-#23 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
system.log-18891-#24 [REMOVED/]vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18892-#25 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18893-#26 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
system.log-18894-#27 [REMOVED/]vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18895-#28 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18896-#29 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
system.log-18897-#30 [REMOVED/]vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18898-#31 [REMOVED/]vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18899-#32 [REMOVED/]vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
system.log-18900-#33 [REMOVED/]vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
system.log-18901-#34 [REMOVED/]vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
system.log-18902-#35 [REMOVED/]var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
system.log-18903-#36 [REMOVED/]vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
system.log-18904-#37 [REMOVED/]vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
system.log-18905-#38 [REMOVED/]pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
system.log-18906-#39 {main} [] []
`

In /vendor/magento/module-paypal/Controller/Express/AbstractExpress.php
`if (!$quote->hasItems() || $quote->getHasError()) {
            $this->getResponse()->setStatusHeader(403, '1.1', 'Forbidden');
            throw new \Magento\Framework\Exception\LocalizedException(__('We can\'t initialize Express Checkout.'));
        }`

$qoute seems to exist in my case, as I can not see any undefined errors in my PHP error log.
This leaves only two things $quote has no items or $quote has errors. I will add some logging to the Shop.

**Comment by terrybakshi** [comment]
ok have you used minify Js, Css, HTML and any caching technology, like cloudflare or anything else.

**Comment by vberthet** [comment]
I got a similar problem : 

[2018-06-27 07:42:15] main.CRITICAL: Exception message: Impossible d’initialiser Express Checkout.
Trace: #0 /home/.../releases/14/vendor/magento/module-paypal/Controller/Express/GetToken.php(126): Magento\Paypal\Controller\Express\AbstractExpress->_initCheckout()
#1 /home/.../releases/14/vendor/magento/module-paypal/Controller/Express/AbstractExpress/Start.php(24): Magento\Paypal\Controller\Express\GetToken->getToken()
#2 /home/.../releases/14/vendor/magento/framework/App/Action/Action.php(107): Magento\Paypal\Controller\Express\AbstractExpress\Start->execute()
#3 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Paypal\Controller\Express\Start\Interceptor->___callParent('dispatch', Array)
#5 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Paypal\Controller\Express\Start\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /home/.../releases/14/generated/code/Magento/Paypal/Controller/Express/Start/Interceptor.php(26): Magento\Paypal\Controller\Express\Start\Interceptor->___callPlugins('dispatch', Array, Array)
#7 /home/.../releases/14/vendor/magento/framework/App/FrontController.php(55): Magento\Paypal\Controller\Express\Start\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#10 /home/.../releases/14/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /home/.../releases/14/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /home/.../releases/14/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#16 /home/.../releases/14/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#18 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#19 /home/.../releases/14/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#20 /home/.../releases/14/generated/code/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#21 /home/.../releases/14/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#22 /home/.../releases/14/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#23 {main} [] []

Step to reproduce : 
 - Place an order using Paypal Express checkout (That one works !)
 - Then place a second order (That one failed, i got ""We can't initialize Express Checkout." and cart is cleared) 

If your clear browser cache and try again it'll works. 

Apparently Quote is cleared before reaching Magento\Paypal\Controller\Express->_initCheckout():136

it's seems that paypal module clear user quote before sending him to paypal gateway. Which i think is a terrible idea. Try to go back using your browser navigation when on paypal gateway (Your cart has vanished....)

**Comment by vberthet** [comment]
Probably caused by https://github.com/magento/magento2/issues/12390
If a custom POST request is made during checkout then paypal module fail with the described error.

**Comment by magento-engcom-team** [comment]
@terrybakshi @vberthet Thanks for finding duplicate. Please continue tracking under #12390
