### ISSUE TITLE
Images are getting duplicated via Rest API.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#13723]
### Preconditions

1. All Magento Version
2. Instance with 2 website

### Steps to reproduce

1. Call Magento 2 Rest API: [storeview1]/V1/products/[SKU]/media with image payload
2. Call Magento 2 Rest API: [storeview2]/V1/products/[SKU]/media with same image payload

### Expected result

1. The image should be imported one time.

### Actual result

1. Two images got imported in Product and showing twice in the frontend.

**Comment by vicabitu** [comment]
I have the same problem using the same endpoint.

**Comment by magento-engcom-team** [comment]
@ankursachdeva11, thank you for your report.
This seems to be correct Magento behavior. If you use POST request then a new created gallery entry, you can use PUT request for update gallery entry. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
