### ISSUE TITLE
Product admin form field "Categories" is cached for all stores

### ISSUE THREAD

**Issue by andrii-dymov** [magento/magento2#13726]
### Preconditions
Magento 2.2.2

### Steps to reproduce
1. Create multiple stores with different root categories
2. Add user role with access to one of the stores
3. Login and try to add new product. Check available options in Content->Categories
4. Re login as super admin and try to add new product. Check available options in Content->Categories

### Expected result
Super admin can see all available categories

### Actual result
Categories for the previous user are cached

### Code insights
Categories options are loaded from cache in `getCategoriesTree` method without specifying the store id:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Categories.php

**Comment by magento-engcom-team** [comment]
@awarche , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@awarche, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
