### ISSUE TITLE
Uncaught TypeError: Cannot read property 'updateItemQtyUrl' of undefined

### ISSUE THREAD

**Issue by pramodhanu** [magento/magento2#13725]
Preconditions :
Magento version - 2.1.3
PHP - 5.6

Steps to reproduce :
i have getting error.when i have uploaded one module in my magento 2 store.but i have remove my module and use new theme - Fastest -Ellyana theme .i have changes theme but not solve this error 
- Uncaught TypeError: Cannot read property 'updateItemQtyUrl' of undefined

### Expected result

1. Show mini cart on home page right sidebar and also show mini cart on bottom area

### Actual result

/**
* Copyright © 2015 Magento. All rights reserved.
* See COPYING.txt for license details.
*/
define([
	'uiComponent',
	'Magento_Customer/js/customer-data',
	'jquery',
	'ko',
	'codazonSidebar',
	'Magento_Ui/js/modal/modal'
], function (Component, customerData, $, ko) {
	'use strict';
	var sidebarCart = $('[data-block="footer_minicart"]');
	var addToCartCalls = 0;
	var sidebarInitialized = false;

	function initSidebar() {
		if (sidebarCart.data('mageSidebar')) {
			sidebarCart.codazonSidebar('update');
		}
		sidebarCart.trigger('contentUpdated');
		if (sidebarInitialized) {
			return false;
		}
		sidebarInitialized = true;
		sidebarCart.codazonSidebar({
			"targetElement": "#footer-mini-cart",
			"url": {
				//"checkout": window.checkout.checkoutUrl,
				"update": window.checkout.updateItemQtyUrl,
				"remove": window.checkout.removeItemUrl,
				"loginUrl": window.checkout.customerLoginUrl,
				"isRedirectRequired": window.checkout.isRedirectRequired
			},
			"button": {
				"checkout": "#footer-cart-btn-checkout",
				"remove": ".item a.action.delete",
				"close": ""
			},
			"minicart": {
				"list": "",
				"content": "",
				"qty": "",
				"subtotal": ""
			},
			"item": {
				"qty": "input.cart-item-qty",
				"button": "button.update-cart-item"
			},
			"confirmMessage": $.mage.__(
				'Are you sure you would like to remove this item from the shopping cart?'
			)
		});
	}

	return Component.extend({
		ajaxcart: ko.observable({}),
		crosssell: ko.observable({}),
		addedItem: ko.observable({}),
		cartSidebar: ko.observable({summary_count: false}),
		toggleFooterSidebar: function(){
			$('#footer-cart-trigger').toggleClass('active');
			$('#footer-mini-cart').slideToggle(300);	
		},
		initSidebar: initSidebar,
		initialize: function () {
			var self = this;
			this._super();
			this.addedItem({success:false});
			this.cartSidebar = customerData.get('cart');
			window.addedItem = self.addedItem;
			window.ajaxcart = self.ajaxcart;
			window.crosssell = self.crosssell;
			window.cartSidebar = self.cartSidebar;
			$('#cart-footer').show();
			initSidebar();
			this.cartSidebar.subscribe(function () {
				addToCartCalls--;
				sidebarInitialized = false;				
				initSidebar();
			}, this);
			$('[data-block="minicart"]').on('contentLoading', function(event) {
				addToCartCalls++;				
			});
			var $ajaxPopup = $('#ajax-cart-container');
			/*$ajaxPopup.modal({
			innerScroll: true,
			trigger: '.tocart',
			wrapperClass: 'ajaxcart-modal',
			buttons: [],
			opened: function(){
			window.addedItem({success:false});
			},
			closed: function(){
			}	
			});*/
		},

	});
});

this is error code on top

**Comment by magento-engcom-team** [comment]
@pramodhanu, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@pramodhanu please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@pramodhanu, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
