### ISSUE TITLE
Remove Magento Social from the installation by default

### ISSUE THREAD

**Issue by ju5t** [magento/magento2#13730]
### Preconditions
1. Docker
2. Magento 2.2.1

### Steps to reproduce
1. Recreate the Docker container

### Expected result
1. We expect the application to run as it did before.

### Actual result
1. One or more integrations have been reset because of a change to their xml configs.

We run Magento2 entirely from containers. Our platform is based on Docker (Swarm). Every time a container is recreated we get the alert at the top of the screen that says `One or more integrations have been reset because of a change to their xml configs.`. You can't dismiss it. The alert is triggered by Magento Social, something we didn't install nor use.

Composer is installing all dependencies within our Docker image. Magento Social isn't part of it. Yet is it still installed. Could this be disabled by default on new installations and how can we get rid of the alerts it's triggering at the moment?

**Comment by koenner01** [comment]
Are you sure you aren't using a custom module called Magento_Social because the base code does not contain any module with any reference to this.

**Comment by ju5t** [comment]
It's a dependency of magento/product-community-edition, at least in 2.2.1. We're using Composer to manage all Composer packages in our Docker image.

It includes `"shopialfb/facebook-module": "2.0.0"`. I know we can disable it but I don't want to include it at all.

**Comment by t-richards** [comment]
@ju5t You can completely prevent the download and installation of `shopialfb/facebook-module` by specifying that your project "[replaces](https://getcomposer.org/doc/04-schema.md#replace)" it. In your project's `composer.json`,

```json
"replace": {
    "shopialfb/facebook-module": "*"
},
```

Then, update your dependencies.

```sh-session
$ composer update
[...]
Package operations: 0 installs, 0 updates, 1 removal
  - Removing shopialfb/facebook-module (2.2.1)
Removing Shopialfb/FacebookModule
```

After the package has been removed, you may wish to perform manual cleanup tasks like...

- Running `$ bin/magento setup:upgrade` to apply changes to `app/etc/config.php`
- Removing the corresponding row from the `integrations` table
- Removing the module entry from the `setup_module` table

**Comment by magento-engcom-team** [comment]
@ju5t, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by UranusCEO** [comment]
Still there for 2.2.5. Any roadmap to remove it?

**Comment by pmsteil** [comment]
Looks like "Magento Social" was removed in [v2.2.6](https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.6CE.html)
