### ISSUE TITLE
Magento 2.2.1 to 2.2.2

### ISSUE THREAD

**Issue by Cl0ne0fG0d** [magento/magento2#13739]
### Preconditions

1. PHP 7.0.27
2. MariaDB 10.2.13

### Steps to reproduce

1. System -> Web Setup Wizard
2. System Upgrade -> everything check okay
3. start updating and after while Failed

### Expected result

1. no log about issue just show rollback 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@Cl0ne0fG0d , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@Cl0ne0fG0d, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
