### ISSUE TITLE
\Magento\Framework\Phrase\Renderer\Placeholder::render() can't handle more than 9 placeholders

### ISSUE THREAD

**Issue by riconeitzel** [magento/magento2#1374]
Using the code fragment

```
<?= 
__(
    '%1<br>%2<br>%3<br>%4<br>%5<br>%6<br>%7<br>%8<br>%9<br>%10',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'
); 
?>
```

in a phtml file will result in the following **wrong** output:

```
one
two
three
four
five
six
seven
eight
nine
one0
```

because Placeholder Renderer uses _str_replace_ which replaces %10 in the first place.

__Question:__ What exactly was wrong with the old sprintf rendering?!

**Comment by joshdifabio** [comment]
We can fix this easily by reversing the ordering of the items in the `str_replace` call and replacing the higher-numbered items first. I'll submit a PR.

**Comment by riconeitzel** [comment]
@joshdifabio yeah but that just "covers" the problem that str_replace might not be the right piece of PHP for that task? What happened to sprintf here?

**Comment by joshdifabio** [comment]
Well, I'm not part of Magento but I'll try to guess the reasons.

The interface of this method is quite different to that of `sprintf`: This method supports named and numbered arguments and implicitly treats all arguments as strings, whereas `sprintf` only supports numbered arguments and requires clients to define the type of each argument, which makes numbered arguments quite cumbersome to use.

With Magento's current approach:

```php
__('An %foo can look like %bar', ['foo' => 'input', 'bar' => 'this'])
```

`sprintf` style:

```php
__('An %s can look like %s', ['input', 'this'])
```

With Magento's current approach:

```php
__('This %1 contains %2 of %3 so %4 numbered %5 is %6', ['sentence', 'lots', 'words', 'a', 'approach', 'helpful'])
```

`sprintf` style:

```php
__('This %1$s contains %2$s of %3$s so %4$s numbered %5$s is %6$s', ['sentence', 'lots', 'words', 'a', 'approach', 'helpful'])
```

I suppose Magento only wish to support simple string replacements and therefore they opted for a smaller and more focused interface than what `sprintf` provides.

**Comment by riconeitzel** [comment]
Thanks for taking the time to think about that @joshdifabio :-) :+1:
