### ISSUE TITLE
Crash on attempting to add new Integration

### ISSUE THREAD

**Issue by Gloweye** [magento/magento2#13743]
### Preconditions

1. Magento version 2.1.10

### Steps to reproduce

1. I added a new integration to get an API key (System -> Integrations -> Add new Integration)
2. I noticed a spelling error, so I changed the name of the integration 
3. At attempting to save the integration, an error occured
4. In an attempt to fix the situation and start anew, I removed the integration (name was not changed)
5. At attempting to create a new integration, I get an error log.

### Expected result

1. I expected to be able to create a new integration 

### Actual result

The following exception (upper stack part):

Exception #0 (Exception): Notice: Undefined index: all_resources in /home/deonet/domains/deonet.com/public_html/vendor/magento/module-integration/Controller/Adminhtml/Integration.php on line 129
#0 /home/deonet/domains/deonet.com/public_html/vendor/magento/module-integration/Controller/Adminhtml/Integration.php(129): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/deonet/do...', 129, Array)
#1 /home/deonet/domains/deonet.com/public_html/vendor/magento/module-integration/Controller/Adminhtml/Integration/NewAction.php(18): Magento\Integration\Controller\Adminhtml\Integration->restoreResourceAndSaveToRegistry()
#2 /home/deonet/domains/deonet.com/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Integration\Controller\Adminhtml\Integration\NewAction->execute()

I am suspecting this to be independent of platform, because of the stateful nature of the bug.

**Comment by Gloweye** [comment]
In an unrelated issue, one of my colleagues discarded the complete static cache under /var/ and it's relatives.

This seems to have fixed this issue as a side effect. I'd still consider it a bug, so I'm leaving it up here to process at your discretion.

**Comment by magento-engcom-team** [comment]
@Gloweye, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@Gloweye The issue is already fixed in `2.2.2` and `2.3-dev`.
Please reopen if you need any further assistance with this.

**Comment by Ctucker9233** [comment]
@magento-engcom-team What are the related commits for this issue?

**Comment by indefinitedevil** [comment]
@magento-engcom-team Have just reproduced this error message on Magento Commerce Cloud 2.2.6 when trying to edit an existing integration.
