### ISSUE TITLE
Something went wrong while saving file When trying to upload image for customer attribute in Matgento 2.2.1

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#13745]
### Preconditions
Install Magento 2.2.1 form magento.com 

1. Magento Ver. 2.2.1
2. PHP 7.0.9 , Apache 2.4.23 (Stable)

### Steps to reproduce

1. Prepare InstallData.php for create customer attribute.
2. Login to admin, Edit existing customer, You can find your attribute there, Tried to upload image for that attribute from admin.
3. While image is uploading error popoup there with "Something went wrong while saving file".

### Expected result

1. It has to be successfully upload file and let me save customer.

### Actual result

1. File is being uploaded to pub/media/customer/, But error pop up is there with same as bug title.
2. Can't able to upload file for created customer attribute.

**Comment by VZeroCool** [comment]
Any update or fix in this issue ? It seems to be still present in M2 CE 2.2.1. It has to be fixed in earlier version in M2 as per i read in git issues.

**Comment by VZeroCool** [comment]
Hello Community, Any update on this i still can reproduce this issue in Magento 2.2.2 CE as well.

**Comment by magento-engcom-team** [comment]
VZeroCool, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please update the steps required to reproduce.

**Comment by VZeroCool** [comment]
I can also reproduce this issue in Magento 2.2.3 CE as well.

**Comment by magento-engcom-team** [comment]
@VZeroCool Please check exception log, it may contain more information.
Additionally, steps to reproduce do not indicate a specific way to add the attribute in question, please clarify that.
Thanks!

**Comment by devenkuswa** [comment]
I would like to reopen it. Facing same issue on Magento 2.2.2 .
I commented    //unset($result['path']); and its working but please let me know why do we need to unset it.
/vendor/magento/module-customer/Model/FileProcessor.php

public function saveTemporaryFile($fileId)
    {
        /** @var \Magento\MediaStorage\Model\File\Uploader $uploader */
        $uploader = $this->uploaderFactory->create(['fileId' => $fileId]);
        $uploader->setFilesDispersion(false);
        $uploader->setFilenamesCaseSensitivity(false);
        $uploader->setAllowRenameFiles(true);
        $uploader->setAllowedExtensions($this->allowedExtensions);

        $path = $this->mediaDirectory->getAbsolutePath(
            $this->entityTypeCode . '/' . self::TMP_DIR
        );

        $result = $uploader->save($path);
        //unset($result['path']);
        if (!$result) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('File can not be saved to the destination folder.')
            );
        }

        return $result;
    }

**Comment by gobyweb2** [comment]
Something went wrong while saving the new password.
