### ISSUE TITLE
String "SKU" in phtml-template gets not translated 

### ISSUE THREAD

**Issue by bytes-max** [magento/magento2#13753]
### Preconditions

1. have magento 2.1.11 installed
2. have a customer with at least one order

### Steps to reproduce

1. click on the order in the customers dashboard
2. check the headings
3. 

### Expected result

1. as defined in language csvs SKU should be translated to "Artikelnummer" or similiar

### Actual result

1. SKU gets not translated, its still "SKU"

Also, this string can't be translated with inline translation, even if its defined in `./vendor/magento/module-sales/view/frontend/templates/order/items.phtml`.

**Comment by magento-engcom-team** [comment]
@nopenopenope, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by AngelBS** [comment]
#MageTitansMX

**Comment by AngelBS** [comment]
It works as expected!
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by bytes-max** [comment]
Hi @AngelBS, could you elaborate in which version you've checked it, as it seems that it were reproduceable on at least 3 minor versions of Magento.

**Comment by AngelBS** [comment]
Hi @nopenopenope thanks for replying.
We tried to reproduce the problem on v2.2.3 and v2.2.4-dev, and it works as expected, let me know if you need more information about this issue

**Comment by vrann** [comment]
per @AngelBS closing the issue

**Comment by bytes-max** [comment]
As Magento 2.1.x is the only version of Magento that is still working with PHP > 7, please try to fix this error in this version of Magento 2 as well. Not all customers can use PHP7 currently.
