### ISSUE TITLE
error when changing store name in magento 2 admin

### ISSUE THREAD

**Issue by Sharlyll** [magento/magento2#13754]
### Preconditions
1. Magento 2.2 clean install
2. PHP 7 & MySQL

### Steps to reproduce

1. go to magento 2 admin --> store --> all store
2.  attempt to change the default 'Main Website' and 'Main Website Store' to another name

### Expected result

1. name change should be accepted without errors

### Actual result

1. error message is displayed instead. 
2. name change is not accepted.
3. error log doesn't say anything.
please see images.

![screen shot 2018-02-20 at 19 25 39](https://user-images.githubusercontent.com/22851271/36439749-7b29b002-1676-11e8-99f0-6dd7937fa515.png)
![screen shot 2018-02-20 at 19 29 11](https://user-images.githubusercontent.com/22851271/36439757-80ccbcfc-1676-11e8-9a25-205ee97cc697.png)

**Comment by jajaramos** [comment]
Hi @Sharlyll,

I could not reproduce on Magento 2.2.2 using the steps provided, see screenshot below:
<img width="1130" alt="screen shot 2018-02-21 at 3 49 22 pm" src="https://user-images.githubusercontent.com/14193499/36463552-d1a5b4b4-171e-11e8-876b-3d6eb60612c8.png">

#MLAU18
