### ISSUE TITLE
Not working in Chrome & Firefox browser but working in IE & Safari browser

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#13755]
### Preconditions

1. Magento 2.2.2
2. Php71
3. Cloudflare SSL (https)

### Steps to reproduce

1. When i in GENERAL > Web > Base URL/Secure Base URL changed http://www.domain.com/ to https://www.domain.com/
2. php bin/magento cache:flush / php bin/magento cache:clean
3. Cleared Chrome and Firefox Browser all cookies.
4. Restarted Server Services & Apache Web Server & MySQL Server ALL...

### Expected result

1. Fix it

### Actual result

1. Some functions are not working in Chrome and Firefox Browser but working in IE & Safari Browser.
2. Like this function  : Catatlog > Products > Configurations products > Create configurations (Not working in Chrome and Firefox Browser)

**Comment by osseonews** [comment]
We had the same problem on 2.2.2. When we changed to a secure URL, many functions ceased to function normally in chrome and firefox.

**Comment by ghost** [comment]
Hi @rigu12 I cannot reproduce you scenario, see attachments,  If you'd like to update it, please reopen the issue.
![frame-site](https://user-images.githubusercontent.com/40756439/43448797-7d327f54-94b7-11e8-87f7-c8678bc7650a.gif)
