### ISSUE TITLE
Cannot create Category with specific ID using REST API

### ISSUE THREAD

**Issue by jwilliamson1098** [magento/magento2#13767]
Using Magento 2 REST API. Trying to produce a category with a specific ID I get the error: " No such entity with %fieldName = %fieldValue\",\"parameters\":{\"fieldName\":\"id\",\"fieldValue\":3}"

I'm using a POST to /rest/V1/categories with the JSON below.

If I drop the "id" then a category is created but with an auto generated ID. The Swagger documentation says "id" is allowed, but optional.

Following through the Magento code identified in the trace, this appears to be because Magento appears to try and load details of a current category if ID has been specified. This makes sense for a PUT but not for a POST.

In: 
/vendor/magento/module-catalog/Model/CategoryRepository.php

in: 
public function save(\Magento\Catalog\Api\Data\CategoryInterface $category)
   .
    .
     .
        if ($category->getId()) {
            $metadata = $this->getMetadataPool()->getMetadata(
                CategoryInterface::class
            );

            $category = $this->get($category->getId(), $storeId);     
. 
.
.

The "get" function throws an exception as the category doesn't exist (as this is a POST).

I believe the functionality should be to create a new category with the specified ID, perhaps throwing an exception if it was creating a category that already existed with that ID.

### Preconditions
1. Using Magento Commerce for B2B 2.2 and the REST API

### Steps to reproduce
1. Using: /rest/V1/categories
2. This is after sending (as a POST):
{
  "category": {
    "id": 56,
    "name": "40% Off",
    "is_active": false
  }
}

### Expected result
1. Category created with ID:56

### Actual result
1. No such entity with %fieldName = %fieldValue\",\"parameters\":{\"fieldName\":\"id\",\"fieldValue\":3}
2. Simplified Stack output for reference:
19/02/2018 23:00:29 :       :   {"message":"No such entity with %fieldName = %fieldValue","parameters":{"fieldName":"id","fieldValue":56},"trace":"#0 /var/www/html/magento/vendor/magento/module-catalog/Model/CategoryRepository.php(141): Magento\Framework\Exception\NoSuchEntityException::singleField('id', 56)\n#1 /var/www/html/magento/vendor/magento/module-catalog/Model/CategoryRepository.php(88): Magento\Catalog\Model\CategoryRepository->get(56, 0)\n#2 [internal function]: Magento\Catalog\Model\CategoryRepository->save(Object(Magento\Catalog\Model\Category\Interceptor))\n#3 /var/www/html/magento/vendor/magento/module-webapi/Controller/Rest.php(330): call_user_func_array(Array, Array)\n#4 /var/www/html/magento/vendor/magento/module-webapi/Controller/Rest.php(239): Magento\Webapi\Controller\Rest->processApiRequest()

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098 
Unfortunately creation of entities with predefined id's is not supported at the moment. In this case ID may only be used for the entity update.
You may find additional references on the subject here: 
* [[DevBlog] Entity ID Allocation Schemes](https://community.magento.com/t5/Magento-DevBlog/Entity-ID-Allocation-Schemes/ba-p/68316)
* [[MSI] The first step towards pre generated IDs.](https://github.com/magento-engcom/msi/wiki/The-first-step-towards-pre-generated-IDs.-And-how-this-will-improve-your-Integration-tests)

**Comment by jyotitechwin** [comment]
if we can't add any category with id then what is purpose of rest API?
