### ISSUE TITLE
Import custom option for multi store view

### ISSUE THREAD

**Issue by QKChris** [magento/magento2#13774]
### Preconditions

1. Magento 2.4-develop
2. Multi-language store

### Steps to reproduce

1. Store admin, translate the custom options of product A for English store view and French store view and save.
![p1](https://user-images.githubusercontent.com/35945089/36488917-9c0fc3e4-175f-11e8-9207-690472d316cf.png)
![p2](https://user-images.githubusercontent.com/35945089/36488923-a0c7ce40-175f-11e8-87e6-4c4ec707183c.png)

2. In default store view, create new product B, in Customizable Options, click "Import Options" and select product A, import and save.
![p3](https://user-images.githubusercontent.com/35945089/36488941-b2ff40f2-175f-11e8-9994-724bfd69eff5.png)
![p4](https://user-images.githubusercontent.com/35945089/36488949-b6cd836a-175f-11e8-8c6e-2f9a19aae8b4.png)

### Expected result

1. The options' title and value should be in different languages as I translated for product A, English value in English store view, French value in French store.

### Actual result

1. All title and value be covered by default value.
![p6](https://user-images.githubusercontent.com/35945089/36488977-cd312418-175f-11e8-838a-d5627cfaff1a.png)

**Comment by magento-engcom-team** [comment]
@QKChris, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by QKChris** [comment]
@magento-engcom-team Hello, can you tell me the approximate time of the problem be solved?

**Comment by saravananvelu** [comment]
Working on #dmcindia

**Comment by facetimer** [comment]
i have this issue with magento 2.2.6 ..
What can i do to resolve this issue ?
Thank you

**Comment by facetimer** [comment]
> @QKChris, thank you for your report.
> We've acknowledged the issue and added to our backlog.

Any news..?
THX

**Comment by facetimer** [comment]
I am looking for a solution.

Any news about that ?

Thank you

**Comment by facetimer** [comment]
Really strange that nobody encounter the same issue!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30195` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sathishkumarContus** [comment]
@magento-engcom-team , Any update on this issues. We are still facing this problem on Magento version 2.3.2

**Comment by magento-engcom-team** [comment]
Hi @QKChris. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-30195` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
