### ISSUE TITLE
Broken State of Forms to Use In of custom customer attribute after saved in backend

### ISSUE THREAD

**Issue by peter-hoecherl-zz** [magento/magento2#13781]
### Preconditions
Magento ver. 2.1.11
 
### Steps to reproduce
1. Navigate to the Customer Attribute Edit form (Stores >> Attributes >> Customer)
1. Add a new custom customer attribute with **no** value selected in _Forms to Use In_
1. Set _Show on Storefront_ to **Yes**
1. Save the attribute
1. Navigate into a customer edit form in the backend
1. Change the value of the newly created attribute
1. Save the customer form by pressing "Save and Continue Edit"
1. Expect to see the changed value of the attribute
1. Navigate back to the Customer Attribute Edit form (Stores >> Attributes >> Customer)
1. Select the newly created attribute
1. Save the attribute (no changes required)
1. Now go back to the customer edit form
1. Change the value of the newly created attribute
1. Save the customer form by pressing "Save and Continue Edit"

### Expected result
1. Expect to see the changed value of the attribute

### Actual result
1. No changes have been applied to the attribute's value

**Comment by magento-engcom-team** [comment]
Hello @peter-hoecherl. Customer attribute functionality is absent in official Community Edition (Open Source) versions of Magento. It is supplied only with Enterprise Edition versions. So please address Your issue directly to Magento Support. Thank You.

**Comment by magento-engcom-team** [comment]
@peter-hoecherl, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
