### ISSUE TITLE
Searchable date attribute breaks search when using ElasticSearch

### ISSUE THREAD

**Issue by siimm** [magento/magento2#13790]
### Preconditions

1. Magento EE 2.2.2 with sample data installed.
2. ElasticSearch v2.4.6
3. PHP 7.0.22

### Steps to reproduce

1. Navigate to Stores > Attributes > Product
2. Find any attribute of type "date", for an example news_from_date
3. In Storefront tab, set property "Use in search" to Yes
4. Save attribute
5. Try search on Frontend

### Expected result

1. Keyword should return results (with demo dataset, use keyword "Jacket")

### Actual result

1. No search results with any keyword
2. Errors in logs:
`==> var/log/support_report.log <==
[2018-02-22 13:32:16] report.CRITICAL: illegal_argument_exception: Invalid format: "jacket" [] []
`
`
==> var/log/system.log <==
[2018-02-22 13:32:16] report.CRITICAL: illegal_argument_exception: Invalid format: "jacket" [] []
`
3. Fragment of log from Elasticsearch side from the same error (different query string):
`elasticsearch.log.2018-02-06-   at org.elasticsearch.search.SearchService.parseSource(SearchService.java:873)
elasticsearch.log.2018-02-06-   at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
elasticsearch.log.2018-02-06-   at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
elasticsearch.log.2018-02-06-   at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
elasticsearch.log.2018-02-06-   at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
elasticsearch.log.2018-02-06-   at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
elasticsearch.log.2018-02-06-   at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
elasticsearch.log.2018-02-06-   at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
elasticsearch.log.2018-02-06-   at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
elasticsearch.log.2018-02-06-   at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
elasticsearch.log.2018-02-06-   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
elasticsearch.log.2018-02-06-   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
elasticsearch.log.2018-02-06-   at java.lang.Thread.run(Thread.java:748)
elasticsearch.log.2018-02-06-Caused by: java.lang.IllegalArgumentException: Invalid format: "SPÄNNBAND 4\-PACK 300KG/300CM1"
elasticsearch.log.2018-02-06:   at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
elasticsearch.log.2018-02-06-   at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.mapper.core.DateFieldMapper$DateFieldType.parseValue(DateFieldMapper.java:362)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.mapper.core.DateFieldMapper$DateFieldType.indexedValueForSearch(DateFieldMapper.java:386)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.mapper.MappedFieldType.createTerm(MappedFieldType.java:461)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.mapper.MappedFieldType.termQuery(MappedFieldType.java:465)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.search.MatchQuery.termQuery(MatchQuery.java:210)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.search.MatchQuery.termQuery(MatchQuery.java:205)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:165)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.MatchQueryParser.parse(MatchQueryParser.java:168)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:120)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:120)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:324)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:224)
elasticsearch.log.2018-02-06-   at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:219)
elasticsearch.log.2018-02-06-   at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
elasticsearch.log.2018-02-06-   at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)`
### General background:
It seems that if attribute is mapped as date to Elasticsearch, then Elasticsearch expects to receive a proper formatted date as the search keyword as well. When receiving a normal search string, it finds that this is not properly formatted for date and throws and exception. Actually this also happens with integers.

Workaround has been to wrap \Magento\Elasticsearch\Model\Adapter\FieldType::getFieldType() to plugin which will only return type string or float, as it seems those types the search is able to handle.

**Comment by magento-engcom-team** [comment]
Hello @siimm. The ElasticSearch functionality belongs only to EE versions. So please address Your issue directly to Magento Support. Thank You.

**Comment by magento-engcom-team** [comment]
@siimm, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
