### ISSUE TITLE
Magento 2.2 Migration Tool XML Error on Delta

### ISSUE THREAD

**Issue by osseonews** [magento/magento2#13800]
### Preconditions

Magento 2.2, PHP 7.0.27, Apache, Database client version: libmysql - 5.5.45-37.4

### Steps to reproduce

1.  Migrating from Magento 1.9.2.1 to Magento 2.2 using Magento Data Migration Tool

2.  Migration works smoothly.

3.  Upon an attempt to migrate changes using bin/magento migrate:delta [-r|--reset] {<path to config.xml>} an XML error is thrown, "XML file invalid"

4. Running the XML thru a validation tool, displays the following error on the config.xsd file
"Error - Line 89, 40: org.xml.sax.SAXParseException; lineNumber: 89; columnNumber: 40; cos-nonambig: map_file and WC[##any] (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles."

We have never touched or modified the the config.XSD file in any manner. This error only occurred upon an attempt to to migrate using the delta command, the original migration went smoothly without any errors.

### Expected result
Changes should be migrated.

### Actual result
No changes are migrated as the XML files are no executed due the error described above.

**Comment by magento-engcom-team** [comment]
Hi @osseonews. For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.
