### ISSUE TITLE
The "--base_url" option does not exist.   

### ISSUE THREAD

**Issue by mariarti** [magento/magento2#1380]
I try to install the Magento software from the command line
php bin/magento setup:install --base_url=http://example2.com/ --backend_frontname=admin --db_host=localhost --db_name=magento2 --db_user=magento2 --db_password=123456 --admin_firstname=Darth --admin_lastname=Vader --admin_email=admin@example.com --admin_user=admin --admin_password=123456 --language=en_US --currency=EUR --timezone=Europe/Amsterdam --use_sample_data

                                           
  [RuntimeException]                       
  The "--base_url" option does not exist.  

Previous installation by the same command was successful  

What's wrong ?

**Comment by kassner** [comment]
Underscores were replaced by hyphens, use `--base-url` and `--admin-email` and so on.

**Comment by mariarti** [comment]
Thanks, you right. (it changed)

**Comment by dannymichel** [comment]
The "--db-pass" option does not exist.

**Comment by eddielau** [comment]
'--db-pass' has been renamed to '--db-password'. You can use '-h' to see a list of available options.
