### ISSUE TITLE
Functional tests failing on menu item select

### ISSUE THREAD

**Issue by kdemanuele-cw** [magento/magento2#1381]
When running the functional tests with selenium the tests are failing when trying to locate the XPath
`.//li[@role="menu-item" and a[span="System"]]/div[@class="submenu"]`. The reason for the test to fail is that the menu overlap is shown which changes the class to "submenu _overlap". The correct XPath should be `.//li[@role="menu-item" and a[span="System"]]/div[@class="submenu _overlap"]` or `.//li[@role\"menu-item" and a[span="System"]]/div[contains(@class, "submenu")]`. The file to be updated is `dev/tests/functional/tests/app/Magento/Backend/Test/Block/Menu.php`

**Comment by lanken** [comment]
Thanks for reporting, test \Magento\Backend\Test\TestCase\NavigateMenuTest  has been fixed. Changes will be available with the next GitHub publication.

**Comment by vpelipenko** [comment]
Internal ticket: MTA-2210

**Comment by vpelipenko** [comment]
@kdemanuele-cw, changes are in public repository. Please, check the issue again.
