### ISSUE TITLE
Checkout preselects country even if no default country is set

### ISSUE THREAD

**Issue by bigbywolf-uk** [magento/magento2#13824]
### Preconditions
1. Magento 2.2.2
2. PHP 7.0.25

### Steps to reproduce
1. Go to Stores->Configuration->General->General
2. Set Default Country to first option: "--Please Select--"
3. Save and then flush the cache
4. Go to frontend and add a product to shopping cart
5. Proceed to Checkout

### Expected result
1. No shipping method listed as no default country is set

### Actual result
1. Shipping method does show up

**Comment by magento-engcom-team** [comment]
@Munszu , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@Munszu, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
