### ISSUE TITLE
layout referenceBlock no longer allows class to be set

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#13829]
### Preconditions

1. Magento >= 2.2.0

### Steps to reproduce

1. Add a layout xml file in a module or design
2. Add a line that refers to a core block and changes the block class e.g.
```<referenceBlock name="product.info" class="MyModule\Block\SpecialConfigurable">...```

### Expected result

1. This should change the block class used for this block in the handle referenced by the layout file e.g. just for certain product types

### Actual result

1. An error is thrown during static compilation or at load time if in developer mode:
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed.
Line: 1469

I have tried using a di.xml update, but I cannot make that conditional on the layout handle. What I need is... the functionality of specifying the block class!

Here is the commit in #11116 which I think got lost as it was after the rest of the ticket was marked as "non-issue". It explains my situation very well:

> This change has removed a very useful part of referenceBlock that I have used a lot in my modules.

> If I need to change the Block class of a Block, ideally I would create a preference in di.xml. But this is not always practical, for example Magento\Catalog\Block\Product\View is used for loads of different Blocks and I do not necessarily want to change Magento\Catalog\Block\Product\View for every Block that uses it.

> Currently (< 2.2) I achieve this by doing:

    <referenceBlock class="Custom\ModuleBlock\Product\View" name="a-block-im-changing"/>

> In 2.2.* this is now not possible. It can be made to work again by adding the following line after line 315 in vendor/magento/framework/View/Layout/etc/elements.xsd

    <xs:attribute type="xs:string" name="class" use="optional"/>

> Does anyone have any suggestions on how to achieve what I've been doing in 2.2 ? If not, I will probably hack the core to continue working the way I have been.

> The fact it starts working again after only adding that line into elements.xsd makes me think this feature is meant to exist but has been forgotten about when elements.xsd was changed in 2.2

**Comment by magento-engcom-team** [comment]
@maderlock, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by LiamKarlMitchell** [comment]
How to change class of a layout block to over-ride content on it with your own?

```
In 2.2.* this is now not possible. It can be made to work again by adding the following line after line 315 in vendor/magento/framework/View/Layout/etc/elements.xsd

<xs:attribute type="xs:string" name="class" use="optional"/>
```

The solution appears to be to remove the block then re-add it with your own class and template.

See: https://magento.stackexchange.com/questions/178836/how-to-change-the-class-type-and-template-of-a-block-in-magento2-with-layoutxml

Appropriately named view/layout/something.xml
```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
<body>
  <referenceBlock name="block_name" remove="true"/>  
  <referenceContainer name=some.container.name">
  <block class="Your\Module\Block\Something\View" name="block_name" as="aliasname" template="Your_Module::something/something/view/something.phtml"/>
  </referenceContainer>
</body>
</page>
```

Why can't we have class as optional?
```<xs:attribute type="xs:string" name="class" use="optional"/>```
in vendor/magento/framework/View/Layout/etc/elements.xsd

Can plugins modify this elements.xsd ? so that we don't have to modify core?

This is a bug?

**Comment by L3P3** [comment]
Just closing this without providing any explaination seems a very rude move to me. Removing this "feature" without providing any good reasons seems pretty much a slap in the faces of users wanting to keep using it.

**Comment by xpoback** [comment]
> Just closing this without providing any explaination seems a very rude move to me. Removing this "feature" without providing any good reasons seems pretty much a slap in the faces of users wanting to keep using it.

It's Magento, that's the way they do it.

**Comment by LiamKarlMitchell** [comment]
I'm used to it...

**Comment by Alainvdz99** [comment]
I dont know if this helps but they added the class attribute back in October 2018 with this commit https://github.com/magento/magento2/commit/ea894480d45be5a976a14a1a61410a1669166d3f.
