### ISSUE TITLE
magento setup:install --base-url="http://{{base_url}}/" should be valid

### ISSUE THREAD

**Issue by keithbentrup** [magento/magento2#1382]
I should be able to not specify the url during installation and simply use the {{base_url}} value, so that it'll work with whichever host/ip and port that I later choose.

**Comment by vancoz** [comment]
Hi @keithbentrup, thank you for reporting. I think this is more change request than bug and needs PO input.

**Comment by MuhSartaj** [comment]
Hi @keithbentrup I can be done from admin section . I know the solution , for what you looking for .

Allow me to fix this task .

**Comment by buskamuza** [comment]
Hi @keithbentrup ,

could you, please, clarify what means "so that it'll work with whichever host/ip and port that I later choose."?

`{{base_url}}` placeholder is used in the Magento Admin Panel to reference to Base URL, which is the `--base-url` option for.

**Comment by MuhSartaj** [comment]
Hi,

In magemto you can change base url from database . find  table
core_config_data and find  base url into table . when you will find there
you can change .

or

https://kb.magenting.com/content/10/9/en/change-magento-base-url.html

**Comment by keithbentrup** [comment]
In the admin, "{{base_url}}" is a valid option, so I should be able to specify that value during the installation.

There are scenarios where I want to scale the number of m2 instances and this requirement of providing a static host:port combination beforehand unnecessarily limits that ability.

For example, linux containers technology like Docker will randomly assign a port, so if I want to spin up 5 instances simultaneously on the same host, this one requirement blocks me from doing that. If {{base_url}} was allowed, it would work.

**Comment by buskamuza** [comment]
Hi @keithbentrup , `{{base_url}}` placeholder can NOT be used in "Base URL" field in the Admin Panel. You can use this placeholder in all other fields, which works as a reference to the "Base URL" field. This option in the CLI is the same as the field in Admin Panel.

You should determine the host/port in your script and use that value in the command instead of hard-coded value.

**Comment by keithbentrup** [comment]
I'm not sure what you mean by "can NOT". I put the {{base_url}} in the "Base URL" field in the Admin Pane. It accepts it. I flush the cache, clear var/, and "{{base_url}}" works. Have you tried it?

Regardless, there is a need for it. We used it extensively in many dev & QA scenarios on magento 1.14.

![admin](https://cloud.githubusercontent.com/assets/253579/8235773/dbe16de0-15b1-11e5-924f-eeb66a949af6.jpg)

**Comment by buskamuza** [comment]
@keithbentrup , you're right. Sorry for the confusion.
I created an internal ticket to fix the CLI MAGETWO-38974. Thanks for reporting it.

**Comment by mbrinton01** [comment]
Included in 1.0.0-beta

**Comment by tkn98** [comment]
Just FYI: If you set the base_url config setting to "{{base_url}}" alone, it creates invalid recursion and crashes magento.
