### ISSUE TITLE
Configurable variation labels being ignored by the product page

### ISSUE THREAD

**Issue by shires-boy** [magento/magento2#13821]
This is a reproduction of closed issue 6615 on a more up to date EE release.

### Preconditions
1. Magento  EE 2.2.0  
2. PHP 7.1.11-1 
3. MariaDB 10.0.31 
4. Ubuntu 16.04.2

### Steps to reproduce
1. On the product csv import file include column configurable_variation_labels with a value colour_option=Fabric colour on the configurable product row
2. Load catalogue in and re-index and refresh cache
3. View product page

### Expected result

1. The swatch selection on the product page should be narrated "Fabric Colour"

### Actual result

1. The swatch selection on the product page is narrated "Colour Option" (Attribute name text)

![image](https://user-images.githubusercontent.com/22196042/36589179-5e8274f8-1882-11e8-81a5-d4cdac1c5b14.png)

**Comment by magento-engcom-team** [comment]
@shires-boy, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Helllo @shires-boy. The functionality You are talking about is available only in EE versions. Please address Your issue directly to Magento Support. Thank You.

**Comment by shires-boy** [comment]
It is not only available on EE versions, this was working on CE 2.0.9 but upgrading to 2.1.0 and 2.1.1 meant this facility is lost see log item 6615.

However I will log this again with support
