### ISSUE TITLE
Reset Password is not working 

### ISSUE THREAD

**Issue by msliman** [magento/magento2#13839]
I have a  bug, which is customerId and token are always empty. I print them in public function execute() in file vendor/magento/module-customer/Controller/Account/CreatePassword.php. more details are here

https://magento.stackexchange.com/questions/212210/your-password-reset-link-has-expired-magento-2
https://magento.stackexchange.com/questions/212340/reset-password-problem-magento-2

I am working on Magento 2.1.7 - PHP 7 - Amazon Server

Kindly advice.

**Comment by magento-engcom-team** [comment]
@msliman thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@msliman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by magento-engcom-team** [comment]
@msliman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by magento-engcom-team** [comment]
@msliman, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by zgetro** [comment]
@msliman I could manage to find the issue and resolve quick patch. 
**, strictly speaking,** this is not the solution, but you can use this patch while @magento-engcom-team  will resolve this issue.

https://magento.stackexchange.com/questions/212210/your-password-reset-link-has-expired-magento-2#answer-241235

**Hint** 
@magento-engcom-team ~~it could be an issue with magento2 use [urlencode](http://php.net/manual/en/function.urlencode.php)  function. but maybe forget to use [urldecode](http://www.php.net/manual/en/function.urldecode.php) while accessing request.~~

sorry my bad! :bowtie:
it is used [htmlspecialchars()](http://us1.php.net/manual/en/function.htmlspecialchars.php) to avoid html in url all you need to do is decode while you access querystring object [htmlspecialchars-decode](http://us1.php.net/manual/en/function.htmlspecialchars-decode.php)
