### ISSUE TITLE
ssl certificate installation breaks links and css files

### ISSUE THREAD

**Issue by eladnm** [magento/magento2#13836]
i have installed ssl certificate and since than css files are not loading and links inside website return 404 
i have spent over 10 hours to resolve this issue without any success
please assist!!
website: [https://www.deals4u.co.il](https://www.deals4u.co.il)
check erros

### Preconditions

1.  magento 2, apache 2, letsencrypt , ubuntu 16.04
2. 

### Steps to reproduce
1. ssl installation
2.  premssions?
3. 

### Expected result

1.  css files load 
2. links inside website working
### Actual result

1. css files not loading, all links are broken inside website and return 404

link to discussion on magento forum [https://community.magento.com/t5/Technical-Issues/magento-CSS-files-not-loading-with-https-url/td-p/88089](https://community.magento.com/t5/Technical-Issues/magento-CSS-files-not-loading-with-https-url/td-p/88089)

**Comment by ArjenMiedema** [comment]
I just checked the homepage and it seems to load perfectly fine here. Is this still an issue? And if so, can you provide us with what you did so far?

**Comment by magento-engcom-team** [comment]
@eladnm, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@eladnm, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
