### ISSUE TITLE
Log in to the admin panel to develop mode an error

### ISSUE THREAD

**Issue by Opticcenter** [magento/magento2#1383]
mode develop an error before log in to the admin panel

`Warning: Magento\Framework\View\Element\Html\Calendar::_toHtml(): Cannot load resource element 'fields' in /var/www/magento2/lib/internal/Magento/Framework/View/Element/Html/Calendar.php on line 92
#0 /var/www/magento2/lib/internal/Magento/Framework/View/Element/Html/Calendar.php(92): Magento\Framework\App\ErrorHandler->handler(2, 'Magento\\Framewo...', '/var/www/magent...', 92, Array)
#1 /var/www/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(652): Magento\Framework\View\Element\Html\Calendar->_toHtml()
#2 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(521): Magento\Framework\View\Element\AbstractBlock->toHtml()
#3 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(497): Magento\Framework\View\Layout->_renderBlock('head.calendar')
#4 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(307): Magento\Framework\View\Layout->renderNonCachedElement('head.calendar')
#5 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('head.calendar')
#6 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(294): Magento\Framework\View\Layout->renderElement('head.calendar', true)
#7 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('head.calendar')
#8 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
#9 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(307): Magento\Framework\View\Layout->renderNonCachedElement('after.body.star...')
#10 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('after.body.star...')
#11 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(294): Magento\Framework\View\Layout->renderElement('after.body.star...', true)
#12 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('after.body.star...')
#13 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('backend.page')
#14 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(307): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#15 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#16 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(294): Magento\Framework\View\Layout->renderElement('backend.page', true)
#17 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#18 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('root')
#19 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(307): Magento\Framework\View\Layout->renderNonCachedElement('root')
#20 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#21 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(294): Magento\Framework\View\Layout->renderElement('root', true)
#22 /var/www/magento2/lib/internal/Magento/Framework/View/Layout.php(917): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#23 /var/www/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(593): Magento\Framework\View\Layout->getOutput()
#24 /var/www/magento2/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#25 /var/www/magento2/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#26 /var/www/magento2/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(294): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#27 /var/www/magento2/lib/internal/Magento/Framework/App/Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#28 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#29 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#30 {main}`

**Comment by dsikkema** [comment]
@Opticcenter can you share what version of magento you are using? Also, what method of installation did you use, and did you have any issues during installation?

If you have recently updated your code base (by pulling the latest Magento version, for instance), it is necessary to clear the var directory. Please let me know if that helps the issue.

**Comment by shivanigv** [comment]
I am getting the following error when I am in:
1. Developer mode
2. Open the admin panel page
3. Magento version 2.4-develop {updated Magento root folder code today i.e Dec 29th '20}

1 exception(s):
Exception #0 (Exception): Warning: Magento\Framework\View\Element\Html\Calendar::_toHtml(): Cannot load resource element '0' in /Applications/MAMP/htdocs/masalapalatte/app/code/Masalapalatte/Framework/View/Element/Html/Calendar.php on line 114

Exception #0 (Exception): Warning: Magento\Framework\View\Element\Html\Calendar::_toHtml(): Cannot load resource element '0' in /Applications/MAMP/htdocs/masalapalatte/app/code/Masalapalatte/Framework/View/Element/Html/Calendar.php on line 114
<pre>#1 Magento\Framework\View\Element\Html\Calendar->_toHtml() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:1111]
#2 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:1115]
#3 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:675]
#4 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [lib/internal/Magento/Framework/View/Layout.php:578]
#5 Magento\Framework\View\Layout->_renderBlock('head.calendar') called at [lib/internal/Magento/Framework/View/Layout.php:555]
#6 Magento\Framework\View\Layout->renderNonCachedElement('head.calendar') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#7 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('head.calendar') called at [lib/internal/Magento/Framework/View/Layout.php:510]
#8 Magento\Framework\View\Layout->renderElement('head.calendar', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#9 Magento\Framework\View\Layout\Interceptor->renderElement('head.calendar', false) called at [lib/internal/Magento/Framework/View/Layout.php:606]
#10 Magento\Framework\View\Layout->_renderContainer('after.body.start', false) called at [lib/internal/Magento/Framework/View/Layout.php:557]
#11 Magento\Framework\View\Layout->renderNonCachedElement('after.body.start') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#12 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('after.body.start') called at [lib/internal/Magento/Framework/View/Layout.php:510]
#13 Magento\Framework\View\Layout->renderElement('after.body.start', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#14 Magento\Framework\View\Layout\Interceptor->renderElement('after.body.start', false) called at [lib/internal/Magento/Framework/View/Layout.php:606]
#15 Magento\Framework\View\Layout->_renderContainer('root', false) called at [lib/internal/Magento/Framework/View/Layout.php:557]
#16 Magento\Framework\View\Layout->renderNonCachedElement('root') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#17 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root') called at [lib/internal/Magento/Framework/View/Layout.php:510]
#18 Magento\Framework\View\Layout->renderElement('root', true) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#19 Magento\Framework\View\Layout\Interceptor->renderElement('root') called at [lib/internal/Magento/Framework/View/Layout.php:975]
#20 Magento\Framework\View\Layout->getOutput() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:347]
#21 Magento\Framework\View\Layout\Interceptor->getOutput() called at [lib/internal/Magento/Framework/View/Result/Page.php:258]
#22 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#0000000017c8a6370000000048e83042#) called at [lib/internal/Magento/Framework/View/Result/Layout.php:171]
#23 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000017c8a6370000000048e83042#) called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:23]
#24 Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000017c8a6370000000048e83042#) called at [lib/internal/Magento/Framework/App/Http.php:120]
#25 Magento\Framework\App\Http->launch() called at [lib/internal/Magento/Framework/App/Bootstrap.php:264]
#26 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000017c8a6350000000048e83042#) called at [index.php:44]
</pre>

**Comment by fietserwin** [comment]
@shivanigv: I guess you should have opened a new issue. But as other people might also arrive here when searching on the error message: I was able to solve it by changing lines 114 and 115 to:
```
    $this->assign('am', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers'][0]));
    $this->assign('pm', $this->encoder->encode($localeData['calendar']['gregorian']['AmPmMarkers'][1]));
```
i.e. removing the quotes around 0 and 1. (on Magento 2.4.2 on Windows with intl ICU version 66.1).
