### ISSUE TITLE
Magento2 Date Problem

### ISSUE THREAD

**Issue by pankti16** [magento/magento2#13842]
Once "Set Product as New From" and "Set Product as New To" value is set, at the time of adding product can not be changed. The problem is I can not update this two attributes and they always shows current(todays) date I try to edit product.

Preconditions:
1. Magento 2.1.6
2. PHP 7.0
3. MySQL 5.7

Steps to Reproduce
1. Set showTime and showTimepicker to false in jquery-ui-timepicker-addon.js, calendar-test.js and calendar.js files
2. Set showsTime to false in datepicker.js file
3. Under Catalog->product->Select any Product
4. Values of "Set Product as New From" and "Set Product as New To" are current date.
5. After trying to change this values, it can't be updated.

Expected Result
1. When I visit under Catalog->product->Select any Product, it should show me values set to "Set Product as New From" and "Set Product as New To".
2. It should be able to update value of "Set Product as New From" and "Set Product as New To".

Actual Result
1. When I visit under Catalog->product->Select any Product, it is showing me current date as values set to "Set Product as New From" and "Set Product as New To".
2. I am unable to update values of "Set Product as New From" and "Set Product as New To".

**Comment by magento-engcom-team** [comment]
@Pankti16  thank you for your report
Unfortunately, we can't reproduce this issue.
Please try to reproduce this issue on the clean installation (clear, fresh, without any custom themes, third-party extensions, etc.) ver 2.2.2 and tell us the result.

**Comment by pankti16** [comment]
I can't reproduce the issue on the clean installation in magento 2.2.2. But in my current site, it is giving me Error creating Date object from string in jquery-ui-timepicker-addon.js at 2118:4 in my console.
I am unable to understand why it is so and when I inspected my admin product date field, it showed value="Invalid Date". It would be so kind of you to help me detect the problem if possible.

Thanks

**Comment by magento-engcom-team** [comment]
@ thank you for your reply,
In this case, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@Pankti16, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by pankti16** [comment]
okay.
Thanks
