### ISSUE TITLE
Shipping Method section not refreshing on checkout when address info change. Flat Rate disabled

### ISSUE THREAD

**Issue by pratikrgandhi** [magento/magento2#13845]
On the checkout page, shipping method section does not update when flat rate shipping method disabled from the admin configuration.

### Preconditions
1. Magento 2.2
2. PHP 7.0.x
3. MySql 5.6

### Steps to reproduce
1. Disable Flat Rate from the Admin area.
2. Flush the Cache.
3. Go to Frontend
4. Add a product to cart
5. Go to checkout
6. Try changing postcode or country

### Expected result
1. It should be refresh shipping method section.

### Actual result
1. Shipping method section not reloading. https://www.screencast.com/t/pb3dJ9gOLy

**Comment by magento-engcom-team** [comment]
@pratikrgandhi , thank you for your report.
Why you think this section is must reload with ajax if not enable any shipping methods?

**Comment by pratikrgandhi** [comment]
@magento-engcom-team 

we already setup table rate based on country Id and post code.

Hope it will help you.

**Comment by magento-engcom-team** [comment]
@pratikrgandhi, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sunilit42** [comment]
@pratikrgandhi 
seems like working in latest version

**Comment by pratikrgandhi** [comment]
@sunilit42 

Not solved yet for unsecured URL.
It just stopped to regenerate session id for secure checkout

**Comment by dhaval-dev** [comment]
is there any update here?

**Comment by krzksz** [comment]
This issue is no longer reproducible on `2.4-develop` branch:
![ezgif-4-1b1e83bbf121](https://user-images.githubusercontent.com/829189/70831675-7b3bda80-1df3-11ea-957d-bd521a8efe26.gif)
