### ISSUE TITLE
module-shared-catalog is missing in the newest version

### ISSUE THREAD

**Issue by pmyszkier** [magento/magento2#13841]
In Extension Manager I have 1 extension not installed: magento/module-shared-catalog

**Preconditions:**
magento 2.2.1, Apache/2.4.28 (Unix) , PHP 7.0.16 (cli), osx, local server

**Steps to reproduce:**
Go to Admin Panel to Check Component Dependency

**Expected result:**
module installed and showing in composer.json

**Actual result:**
When I try to instal it (v.100.0.2), I have warning:

> **Check Component Dependency**
> We found conflicting component dependencies. Hide detail
> 
> Command "update" failed: Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for magento/module-shared-catalog 100.0.2 -> satisfiable by magento/module-shared-catalog[100.0.2].
> - magento/module-shared-catalog 100.0.2 requires magento/module-advanced-checkout 100.2.* -> no matching package found.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
> see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
> 
> For additional assistance, see component dependency help .

But also magento/module-advanced-checkout is missing

**Comment by magento-engcom-team** [comment]
@pmyszkier thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
