### ISSUE TITLE
please suggest proper steps to solve the error

### ISSUE THREAD

**Issue by Drashtii** [magento/magento2#13853]
Error:1
Add code below to a template file.
$this->getLayout()->createBlock("Magestore\Bannerslider\Block\SliderItem")->setSliderId(your_slider_id)->toHtml();

Error:2
You can put a slider on a cms page. Below is an example which we put a slider with slider_id is your_slider_id on a cms page.
{{block class="Magestore\Bannerslider\Block\SliderItem" name="bannerslider.slidercustom" slider_id="your_slider_id"}}

Error:3
Please copy and paste the code below on one of xml layout files where you want to show the banner. Please replace the your_slider_id variable with your own slider Id.
<block class="Magestore\Bannerslider\Block\SliderItem">
  <action method="setSliderId">
    <argument name="sliderId" xsi:type="string">your_slider_id</argument>
  </action>
</block>

**Comment by Drashtii** [comment]
please help to solve this

**Comment by magento-engcom-team** [comment]
@Drashtii Looks like you are experiencing issues with some code unrelated to the Magento core. Please contact extension vendor for the support. 
Alternatively you may refer to the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
