### ISSUE TITLE
Misleading interface for stockItemCriteria

### ISSUE THREAD

**Issue by nithinsag** [magento/magento2#13858]
### Preconditions

1.  Magento 2.1.9

### Expected result

        \Magento\CatalogInventory\Api\StockItemRepositoryInterface $stockRepository

        \Magento\CatalogInventory\Api\StockItemCriteriaInterfaceFactory $criteriaFactory,
   
1. ` $stockItemCriteria->setProductsFilter($products);`  where `$products` is an array of productids should retrun stockItems for all the products.
. 

### Actual result

1. The returned result only returns stockItem for only one of the products

This is already reported and closed [here](https://github.com/magento/magento2/issues/4328)

**Comment by MrDaar** [comment]
I can confirm this issue in enterprise 2.2.0

**Comment by ghost** [comment]
@diadara, thank you for your report.
This issue is already fixed.
![default](https://user-images.githubusercontent.com/40756187/43573143-be3717ba-9649-11e8-93c5-1441c4c1ea6e.png)
