### ISSUE TITLE
Magento 2.2.2 - Separate Customer reviews and Review form (Uncaught SyntaxError: Unexpected token u in JSON at position 0)

### ISSUE THREAD

**Issue by Vikram0811** [magento/magento2#13859]
I am trying to separate customer reviews under `Review` tab and `Review` form under new `Add your review` tab. In my custom theme's `/app/design/frontend/[vendor]/[theme]/Magento_Catalog/layout/catalog_product_view.xml` using below code

```
<referenceBlock name="product.review.form" remove="true" />   
    	<referenceBlock name="product.info.details">
    	<block class="Magento\Review\Block\Form" name="custom.product.review.tab" group="detailed_info">
    			<arguments>
    				<argument translate="true" name="title" xsi:type="string">Add Your Review</argument>
    			</arguments>
    	</block>
    </referenceBlock>
```

This works but it gives JS error and does not display `Recently Viewed Products` block as well as `Username` on header. Below is the exception

`Uncaught SyntaxError: Unexpected token u in JSON at position 0`

If I remove this code, everything works as expected, but then I can not add new review tab. I even tried with below code but not luck

 ```
   <move element="product.review.form" destination="product.info.details" />
    <referenceBlock name="product.review.form" group="detailed_info">
    	<arguments>
    		<argument translate="true" name="title" xsi:type="string">Add Your Review</argument>
    	</arguments>
    </referenceBlock>
```

How do I resolve this?

**Comment by Vikram0811** [comment]
@magento-engcom-team any update on this issue ?

**Comment by magento-engcom-team** [comment]
Hi @Vikram0811 
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@Vikram0811, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
