### ISSUE TITLE
Currency Switch Exhausts Memory

### ISSUE THREAD

**Issue by himanshug-eh** [magento/magento2#13867]
### Preconditions
1. Magento 2.2.2
2. PHP 7.1
3. MariaDB 10.0
4. Apache 2.4.27
5. OS: Ubuntu 16.04
6. Kernel: 4.4.0-87-generic
7. PHP memory limit is set to 756MB

### Steps to reproduce
1. Open any product (Simple or Configurable)
2. Add the product to cart
3. Change currency from top bar

### Expected result
1. Currency should change

### Actual result
1. Website crashes with white page due to memory exhaustion
```
[Tue Feb 27 15:03:25.826501 2018] [proxy_fcgi:error] [pid 21321:tid 139848732063488] [client 10.58.109.5:38058] AH01071: Got error 'PHP message: PHP Fatal error:  Allowed
 memory size of 792723456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/magento/framework/Event/Manager.php on line 63\n', referer: https://mywebsite.com
```

However, if currency is changed with empty shopping cart, currency gets changed without problem.

**Comment by magento-engcom-team** [comment]
@himanshu-garg, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation of latest release.

**Comment by himanshug-eh** [comment]
Thanks for supporting.  What I found is that it is because of code in a plugin that is causing it exhaust memory.  Sorry for the trouble.
