### ISSUE TITLE
How to change the cache address of a picture to a real address？

### ISSUE THREAD

**Issue by robert-damon** [magento/magento2#13879]
Through the background to upload product images, will generate "media / catalog / product / cache / f9c7fbe9b524c081a3ccf800cbd963eb / j / u / junyong04_21.jpg", the real path is "media / catalog / product / j / u / junyong04_21.jpg", I now hope Close this one picture cache, what should I do? , I am using magento2.2.2

I hope to change the method below to read "value" directly from catalog_product_entity_media_gallery to be the image path，How do I need to change?
magento2\vendor\magento\module-catalog\Model\View\Asset\Placeholder.php
   /**
     * {@inheritdoc}
     */
    public function getUrl()
    {

        if ($this->getFilePath() !== null) {
            $result = $this->context->getBaseUrl() . '/' . $this->getModule() . '/' . $this->getFilePath();
        } else {
            $result = $this->assetRepo->getUrl("Magento_Catalog::images/product/placeholder/{$this->type}.jpg");
        }

        return $result;
    }

**Comment by magento-engcom-team** [comment]
Hello @Robert-Damon. Your issue is more appropriate for the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) than this forum. Please refer there. Thank You.

**Comment by magento-engcom-team** [comment]
@Robert-Damon, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
