### ISSUE TITLE
Invalid scope or scope id

### ISSUE THREAD

**Issue by Heunsig** [magento/magento2#13875]
### Preconditions

1. Magento 2.2.1
2. PHP 7.1
3. MySQL 5.6.36-cll-lve - MySQL Community Server (GPL)
   UTF-8 Unicode (utf8)

### Steps to reproduce

1. I bought Business Premium Hosting on Godaddy, so I automatically installed Magento 2.2.1 through installation tool that Godaddy provides.
2.  After installing Magento 2, I logged in and tried to change a logo from basic Magento logo to my logo (Content > Configuration > Edit > Header tab > Logo image).
3.  However, Magento 2 alerted "Invalid scope or scope id" error message.

### Expected result

1. I want to change the logo.

### Actual result

1. <a href="https://imgur.com/NO5DTLa"><img src="https://i.imgur.com/NO5DTLa.jpg" title="source: imgur.com" /></a>

**Comment by magento-engcom-team** [comment]
@Heunsig  thank you for your report.
  Unfortunately, we can't reproduce this issue.
  We tried to reproduce this issue on the clean installation (clear, fresh, without any custom themes, third-party extensions, etc.) ver 2.2.3. (See images below)

  Please provide us more information on how you did it step by step.

![1](https://user-images.githubusercontent.com/31669971/36787561-772cdba2-1c82-11e8-8b47-488e38b3d619.png)
![2](https://user-images.githubusercontent.com/31669971/36787566-7af1a470-1c82-11e8-9ef6-fbd48015578a.png)

**Comment by Heunsig** [comment]
Actually, I didn't do anything.
Just I installed Magento 2.2.3 through installation tool that Godaddy has provided and then I tried to change a logo like your snapshots. 

I do nothing.

**Comment by magento-engcom-team** [comment]
Hello @Heunsig,
In this case, you need to contact support Godaddy to resolve this issue.

**Comment by magento-engcom-team** [comment]
@Heunsig, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by Heunsig** [comment]
omg... I already asked them. However, they said that problem was not their part because they just lent a hosting service, and they told me to ask Magento. 
Also, already I've tried reinstalling and changing a logo over 5 times, but it didn't work well.
