### ISSUE TITLE
Attribute not saving new values in 2.1.12

### ISSUE THREAD

**Issue by rouralberto** [magento/magento2#13876]
### Preconditions
1. Magento 2.1.12
2. PHP 7.0.27
3. MySQL 5.7.21

#### PHP setup
- `memory_limit=1024M`
- `max_execution_time=18000`
- `max_input_time=6000`
- `post_max_size=128M`
- `upload_max_filesize=32M`

### Steps to reproduce
1. Open Attribute with type swatch in admin
2. Add a new swatch
3. Save Attribute

### Expected result
1. I save Attribute and I get "You saved the product attribute" message
2. The new swatch is ready to use

### Actual result
1. I save Attribute and I got "You saved the product attribute" message
2. The new swatch is not saved

#### NOTES
The attribute has already 249 swatches.

**Comment by magento-engcom-team** [comment]
@roura356a, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by rouralberto** [comment]
This can be fixed increasing `max_input_vars` to a higher number. But maybe deserves a better look about the approach, as is not very scalable. When you save an attribute it resubmits the whole list again instead of only the ones changed/added.

**Comment by magento-engcom-team** [comment]
@roura356a, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
