### ISSUE TITLE
Magento 2.2.3 backend welcome message

### ISSUE THREAD

**Issue by mamsincl** [magento/magento2#13870]
### Preconditions

1. fresh M2 OS 2.2.3
2. PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
3. mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

### Steps to reproduce

1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <dir>
2. install via web interface
3. login to backend

### Expected result

1. Modal of slides: what is new in current version (2.2.3)

### Actual result

1. Modal of slides: what is new in Magento 2.2.2

**Comment by okorshenko** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@mamsincl, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by JDavidVR** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@JDavidVR thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by JDavidVR** [comment]
I figured out that this isseu doesn't make sense, I mean the ui component info was updated to 2.2.3 but probably this will be released in 2.2.4 in that case this should be contemplate the next release instead current.

**Comment by vrann** [comment]
This issue should be fixed during the packaging rather in the code. Code is always behind the actual version by the moment of release. Packaging tool should update the version when package is published to the composer repo

**Comment by hostep** [comment]
Wasn't this message meant for highlighting the important new features of Magento 2.2 (which were only shipped in 2.2.2, but whatever), maybe just change it to `Magento 2.2` instead of the latest actual version?

**Comment by vrann** [comment]
@hostep investigating how was it get updated before and why didn't it work this time. That's more of a question to the internal 2.2.3-develop branch than the 2.2-develop

This block is supposed to list out all improvements in the patch release, so cannot be 2.2 only
