### ISSUE TITLE
Customer not being able to download newer version of downloadable product

### ISSUE THREAD

**Issue by KooTjoo** [magento/magento2#13883]
### Preconditions
1. Magento 2.2.3 
2. PHP 7.1

### Steps to reproduce
1. A customer purchases a downloadable product
2. The store owner uploads a new version (a new file) for that product.
3. The store owner reindexs the system and refreshes cache.
4. The customer downloads product again

### Expected result
1. The system sends an email to notify customers of the updated product.
2. Customers are able to download the latest version.

### Actual result
1. No email sent to customers
2. An old version still existed.
3. Customers can't download the lastest versio

What I would like to do is show customers list of versions avaliable and when I have added new version this appears on top of list. If this is not possible then I would like the order to be updated to latest version.

**Comment by orlangur** [comment]
Hi @KooTjoo,

> The system sends an email to notify customers of the updated product.

What is the base for such expectation? Is it documented somewhere?

**Comment by KooTjoo** [comment]
Thought this would be great feature, but leave that. How can I make the customer be able to retrive updated file for download. Is Magento capable of doing that?

**Comment by orlangur** [comment]
I'm not sure downloadable product is supposed to be used that way. You prepare file for distribution first and then you publish it as a downloadable product.

> store owner uploads a new version (a new file) for that product

Could you provide more information on such use case?

**Comment by KooTjoo** [comment]
Let's say I sell Magento Extensions with free upgrades. If a new version of an extesnion becomes available how do my customers download that new version? Just updating in the product itself doesn't do this.

**Comment by magento-engcom-team** [comment]
@KooTjoo, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by carlosmirandadiaz** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@carlosmirandadiaz thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by KarlDeux** [comment]
Hi,

Are we sure that we want this as a default feature? 
To me this implies quite a lot cases.

Why would I want my users to have the latest version of a product that they didn't purchase? 
I see that in most cases it would make sense but it might be cases were you don't want your customers to update their version without charges while you want new purchases to have the latest one.

How shall this be managed? Should we create an historical management of the files linked to a product and insert a flag that allows you to chose whether the customer can only download one specific version or always the latest one? 

This actually has legal implications, let's say that a customer bought a piece of software that is intended to work until one specific version of OS and with an update you break that specific support. Legally speaking, you customer should be able to download the specific versions that he actually bought, right? 

Maybe this is the proper time to bring this into the table.

Cheers,
Carlos.

**Comment by magento-engcom-team** [comment]
@KooTjoo Thank you for reporting

Unfortunately we are closing this ticket now, as Github issue tracker is intended only for core Magento technical issues. Please refer to the [Community Forums](https://community.magento.com/) to submit a feature request or use [magento/community-features](https://github.com/magento/community-features/issues) repository to describe your idea.

@KarlDeux Thank you for your time and research on the matter.

Thank you for collaboration!
