### ISSUE TITLE
Duplicate messages when add to newsletter.

### ISSUE THREAD

**Issue by pawcioma** [magento/magento2#13880]
### Preconditions
1. Magento 2.1.7
2. Mysql  5.6.38-83.0
3. PHP 7.0.26

### Steps to reproduce
1. In main page make subscribe to newsletter.
2. Repeat step one second time without refresh page.

After I click subscribe page is reload. After load page I click again subscribe and message is duplicate. It is hard to reproduce when we don't have in main page widgets with product list.

### Expected result
1. When I subscribe to newsletter I should have one information. I should not have that many message how many times I click subscribes newsletter.

### Actual result
1. I have that many messages how many times I subsribes newsletter.

**Comment by orlangur** [comment]
What is observed behavior currently when you subscribe to newsletter, visit some other pages and then subscribe again?

**Comment by pawcioma** [comment]
When I visit other page and click subscribe again all works fine. Problem is when I click subscribe and when page load with message "Thank you for your subscription." I click again subscribe. Now on page I got 2x message and when I click again subscribe i got 3x message.

**Comment by orlangur** [comment]
> When I visit other page and click subscribe again all works fine

Do you a "Thank you for your subscription." message again on other pages? This is expected behavior that until you see such session messages on some page they will be gathered and then displayed all at once.

**Comment by magento-engcom-team** [comment]
@pawcioma , thank you for your report. This is expected behavior for 2.1.x versions.

**Comment by magento-engcom-team** [comment]
@pawcioma, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by pawcioma** [comment]
@orlandur 
Do you a "Thank you for your subscription." message again on other pages? This is expected behavior that until you see such session messages on some page they will be gathered and then displayed all at once.

You not understand me because the same message display many times.
Flow is:
1. I write my email in subsribe form. I did it on main page.
2. I click subscribe.
3. Now we got POST request to /newsletter/subscriber/new/. 
4. Next step is redirect to referer page.(it is main page)
5. I see message "Thank you for your subscription.".
6. I see message "Thank you for your subscription.", but I write my email again to subscribe form.
7. I click again subscribe.
8. POST REquest again
9 redirect to referer.
10. Now I see two the same message "Thank you for your subscription.". I should see only one.

It's look like in step 5 session message does not clean. It does not always occur. it usually occurs when we had in "main page" product filters widgets.

**Comment by orlangur** [comment]
> It's look like in step 5 session message does not clean. It does not always occur. it usually occurs when we had in "main page" product filters widgets.

Session message is cleaned in normal circumstances.

Closing as subscribing multiple times does not sound as a realistic scenario.

Feel free to provide additional information if you manage to reproduce this issue reliably on a clean Magento installation. It could be worth fixing as session messages in other scenarios may be affected.
