### ISSUE TITLE
Error while sending registration email to customer in Magento 2.2.3 CE

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#13888]
Getting error while creating new customer programatically with Lattest Magento 2.2.3

### Preconditions

1.  Magento 2.2.3 CE, PHP - 7.0.9 

### Steps to reproduce

1. Create custom script to create new customer and try to send default registration mail.

### Expected result

1.  Customer has to created successfully and send mail to given email address.

### Actual result

1. Getting below errors.
Warning: Missing argument 3 for Dotdigitalgroup\Email\Plugin\CustomerPlugin::aroundSendNewAccountEmail(), called in C:\xampp\htdocs\mage2sample\vendor\magento\framework\Interception\Interceptor.php on line 135 and defined in C:\xampp\htdocs\mage2sample\vendor\dotmailer\dotmailer-magento2-extension\Plugin\CustomerPlugin.php on line 34
2. If error occurs than it customer no need to create but customer created successfully.

**Comment by adeelq** [comment]
@VZeroCool i'm unable to replicate issue described above. Can you please in detailed describe steps to reproduce this. I was able to create customer on frontend, backend and using a custom script.

**Comment by VZeroCool** [comment]
@adeelq , I have created custom script to create customer at magento root.
As you said i am also able to create customer at both side but sendEmail throwing exception while Magento triying to send email to customer.

**Comment by VZeroCool** [comment]
Here is my custom script to create customer.

`<?php
    
	use Magento\Framework\App\Bootstrap;
	include('app/bootstrap.php');
	
	$bootstrap = Bootstrap::create(BP, $_SERVER);
	$objectManager = $bootstrap->getObjectManager();

	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

	$state = $objectManager->get('\Magento\Framework\App\State');

	$state->setAreaCode('frontend');

	// Customer Factory to Create Customer

	$customerFactory = $objectManager->get('\Magento\Customer\Model\CustomerFactory');

	$websiteId = $storeManager->getWebsite()->getWebsiteId();

    try{
		/**** Instantiate customer and set the customer inforamtion **/

		$customer = $customerFactory->create();

		$customer->setWebsiteId($websiteId);

		$customer->setEmail('phplazycoder@gmail.com');

		$customer->setFirstname('zero');

		$customer->setLastname('cool');

		$customer->setPassword('123456789');

		$customer->save();
		
		/********Send email to customer********/
		$customer->sendNewAccountEmail();
		
		/******** See the customer Id*****/

		echo 'Create customer successfully'.$customer->getId();
		
    }catch(Exception $e){
		echo $e->getMessage();
    }

?>`

**Comment by adeelq** [comment]
@VZeroCool can you please clarify this sentence "If error occurs than it customer no need to create but customer created successfully." It does not make sense. I thought you mean cannot create customer.

**Comment by adeelq** [comment]
@VZeroCool I'm able to replicate this. We are working on resolving this issue in dotmailer side.

**Comment by VZeroCool** [comment]
@adeelq , If there is exception from dot Mailer than Customer shouldn't be create, but currently customer is created at both frontend and backend as well.  This is Bug.

**Comment by adeelq** [comment]
@VZeroCool This has been fixed in our latest internal release and will be in next Magento release. Here is the commit to the fix https://github.com/dotmailer/dotmailer-magento2-extension/commit/124cf86e48cef7dac04f2b859365e9757d2b7b63
