### ISSUE TITLE
Magento 2.2.2 don't change backend's language 

### ISSUE THREAD

**Issue by SeaLuke** [magento/magento2#13895]
Ciao a tutti! I followed the procedure to change the language but it did not change; 
I talked to my provider and there are no problems with the server.
I attach you a screenshot.
Many tanks
![ss01](https://user-images.githubusercontent.com/36933112/36808136-b9ec8dec-1cc4-11e8-8a27-bfe2c6a3942e.jpg)
![ss2](https://user-images.githubusercontent.com/36933112/36808138-ba1e1aec-1cc4-11e8-9fde-5a7e0a7ec0b0.jpg)
![ss3](https://user-images.githubusercontent.com/36933112/36808141-ba4c1d66-1cc4-11e8-97c3-351d4ceb45a5.jpg)

**Comment by magento-engcom-team** [comment]
Hello @SeaLuke. Thanks for reporting. Tell us please have You installed any Italian language pack on Your Magento Instance?

**Comment by SeaLuke** [comment]
Ciao amici, I installed "magento-2-italian-language-pack-master.zip" into a public directory and I unpacked it like a screenshot 3, then i went to my account to change language and after i clean the chache. I've followed this guide: - (https://magento.stackexchange.com/questions/113847/magento-2-how-do-i-change-the-locale-of-admin-backend ) - https://www.mageplaza.com/magento-2-italian-language-pack.html but it doesn't work. Maybe I make a mistake, o forse no ed è la versione ad essere fallata. Grazie

**Comment by magento-engcom-team** [comment]
Ok, @SeaLuke, Could You please try to install the language pack via composer in CLI using theses commands:
```
composer require mageplaza/magento-2-italian-language-pack:dev-master
php bin/magento setup:static-content:deploy it_IT
php bin/magento cache:clean
php bin/magento cache:flush
```
The 2-nd command - `php bin/magento setup:static-content:deploy it_IT` may ask for -f flag, so You will need to run it like `php bin/magento setup:static-content:deploy it_IT -f`. Then everything should work like here:
![italian](https://user-images.githubusercontent.com/31669971/36844148-3e19f196-1d5a-11e8-812b-5137c10aa696.png)

**Comment by SeaLuke** [comment]
you can close the post because the problem is that I use a smartphone (I live in mountains, no adsl, no fiber) to connect I can not use the ssh protocol and therefore I can not add strings. thank you and greetings. Magento the best CMS for all sea's user !!! thanks

**Comment by magento-engcom-team** [comment]
@SeaLuke, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
