### ISSUE TITLE
Overriding default paths in app/etc/env.php?

### ISSUE THREAD

**Issue by james-hickman-arc** [magento/magento2#1390]
I see that replacing the static data structure in app/etc/env.php with dynamic code can dynamically change the database connection parameters but is it possible to also change the default file system paths using the configuration array? Undocumented fields that can be passed in that way? Full documentation about what can be modified here would be really useful.

I am attempting to implement a multi-database multi-tenant configuration with minimal or no modification to core Magento 2 files. Looks like replacing the installer generated app/etc/env.php with something more dynamic is the right way to go.

**Comment by kschroeder** [comment]
Multi-tenancy would seem to make more sense (to me, at least) by building a database adapter that understands multi-tenancy.  Logic should probably not be placed in a configuration file.  I wasn't part of the discussion, but my gut says that the reason why this is a PHP file and not an XML file, as in M1, is soley so an opcache can keep it in RAM.  Can't speak for the core team but that would be my impression.  As such logic in env.php should probably be static.

**Comment by james-hickman-arc** [comment]
Thanks for the feedback. So the recommended solution would be overriding the data access classes with derived classes that implement the multi-tenant database connection logic? So the same would be the recommended solution to the file system access classes?

**Comment by kschroeder** [comment]
Without knowing anything about what you're trying it would probably be done using the DI configuration and setting a preference for your classes over the core ones with your classes extending the core classes.

**Comment by james-hickman-arc** [comment]
Thanks kschroeder. That's the thought process I am pursuing ... but there are a lot of layers of abstraction before the database connection actually happens. I'm guessing that extending the AbstractDB class is at least the starting point.

My goal is fairly simple, have a unique database and file system context for tenants. I see that with this approach multiple domains will need to map to the same context so that Magento's multi-store system can still be used by tenants who are fully isolated from each other.

**Comment by kschroeder** [comment]
AbstractDb probably wouldn't work since resource classes would be directly extending that class.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
