### ISSUE TITLE
Magento2.1.5 admin sales order report not showing correctly

### ISSUE THREAD

**Issue by openwavecomputing** [magento/magento2#13908]
### Preconditions

1. Magento2 Version 2.1.5
2. Make 10 orders with complete or canceled status.

### Steps to reproduce

1. Make 10 orders with complete or canceled status.
2. After admin Login Please go  Reports -> Sales -> Orders
3. Use Filter option status as 'any' with any date range.

### Expected result

1. It should show 10 records and all status report with complete and canceled orders total.

### Actual result

1. [Screenshot, logs]
But We are getting only complete order status report only. and also we tries the filter status option as 'canceled'. it also shows same result. Please help me how to fix this problem. actually our site has launched in live server and we faced as urgent one.

**Comment by magento-engcom-team** [comment]
@openwavecomputing, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@openwavecomputing The issue is already fixed in `2.2` and `2.3-dev`.
Closing ticket for now. Please reopen if you need any further assistance with this.

**Comment by Ctucker9233** [comment]
@magento-engcom-team What are the related commits for this issue?
