### ISSUE TITLE
Magento does not flush caches after full reindex

### ISSUE THREAD

**Issue by melnickforever** [magento/magento2#13919]
Preconditions

    Magento 2.1.11
    PHP 7.0.20
    MySQL 5.6.35

### Steps to reproduce
When We run php bin/magento indexer:reindex indexer_name

\Magento\Indexer\Model\Indexer::reindexAll 
For invalid caches cron run 
\Magento\Indexer\Model\Indexer::reindexAll
1) We set cach tegs in \Magento\CatalogInventory\Model\Indexer\Stock::executeFull for object model\indexer\stock
2) We save indexer status . After save magento dispatch "clean_cache_by_tags" for object Model\indexer\state
\Magento\Framework\Model\AbstractModel::afterSave
3) This action will trigger \Magento\CacheInvalidate\Observer\InvalidateVarnishObserver::execute for object Model\indexer\state
4) We did not have any tags for object for object Model\indexer\state

$this->getTagResolver()->getTags($object); line 57 works not correct. 

### Expected result
FPC should be flushed for product and categories.

### Actual result

FPC not flushed for products and categories

**Comment by orlangur** [comment]
>  We run php bin/magento indexer:reindex indexer_name

Please provide exact steps. Do you run full reindex?

For example, stock reindex definitely should not flush ALL categories and products.

**Comment by melnickforever** [comment]
Thanks for a quick answer 
From bash console : php bin/magento indexer:reindex cataloginventory_stock
Will not flush any cache

**Comment by magento-engcom-team** [comment]
Hi @melnickforever 
This is not a bug.
Only "catalog_category_product" and "catalog_product_category" indexes will flush the FPC.

**Comment by magento-engcom-team** [comment]
@melnickforever, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
