### ISSUE TITLE
Incorrect "Special Price" filter behavior

### ISSUE THREAD

**Issue by orozcodiaz** [magento/magento2#13910]
### Preconditions
Linux 2.6.32-642.6.2.el6.x86_64
Magento Open Source 2.2.2, PHP 7.0.28, mysql  Ver 14.14 Distrib 5.6.32-78.1

### Steps to reproduce
1. Go to Admin - Catalog - Inventory - Products
2. On the top of the grid select Columns - Attribute - Special Price. Mark checkbox "Filter"
3. Enter special price as "0" or "0.00". If you will enter some other non-numeric, non-zero value then it will work normal.

### Expected result
Grid with products with special price equals zero

### Actual result
All the products

Screenshot:
<img width="1570" alt="screenshot 2018-03-01 09 22 06" src="https://user-images.githubusercontent.com/24477165/36849585-6b54abce-1d32-11e8-85b5-447a4dcb4c01.png">

**Comment by magento-engcom-team** [comment]
@oroskodias, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by MarioHdpz** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@MarioHdpz thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sunilit42** [comment]
http://imagizer.imageshack.com/img922/4011/Q72vLf.png

I checked with 2.2 and it is working fine.
