### ISSUE TITLE
Filename Collisions with downloadable products

### ISSUE THREAD

**Issue by superdav42** [magento/magento2#13915]
### Preconditions

1. Magento 2.4
### Steps to reproduce

1. Create a downloadable product and add a downloadable link and upload a file for the link with a filename on the local system like 'book.pdf'
2. Create a different downloadable produdt and add a downloadable link and upload a different file with the same name on the local system like 'book.pdf'
3. Each book.pdf is a different file with different contents possibly located on different places on the users computer when it is uploaded but has the same filename.

### Expected result

1. Each downloadable product will have a different file associated with it.

### Actual result

1. The last uploaded file replaces the existing file. So both downloadable products are associated with the same file. 

The problem is the uploader does not check to see if there is an existing file at the location it is trying to upload a file to but overrides it making the unexpected result. The media uploader doesn't seem to have this problem only downloadable product links and probably samples too.

**Comment by magento-engcom-team** [comment]
@superdav42, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by faguilarp87** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@faguilarp87 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by superdav42** [comment]
Tracked the problem down to https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Downloadable/Helper/File.php#L134 needs to send absolute path to \Magento\MediaStorage\Model\File\Uploader::getNewFileName

**Comment by vrann** [comment]
@superdav42 have you seen PR #13932 -- is that what you have in mind?

**Comment by vrann** [comment]
@faguilarp87 please write me to eulika@magento.com in regards to contribution day participation.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30153` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by superdav42** [comment]
Please don't close this until it's fixed.
