### ISSUE TITLE
Images can't be uploaded using WYSIWYG if media directory is a symlink

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#13929]
As of 2.2.3, it's not possible to upload images via the WYSIWYG if the media directory is a symlink. This is due to this [new file](https://github.com/magento/magento2/blob/2.2.3/lib/internal/Magento/Framework/App/Filesystem/DirectoryResolver.php#L42).

### Preconditions
1. Install Magento 2.2.3
2. Ensure that the media directory is a symlink. For example, the `pub/media` directory should be a symlink that points somewhere else.

### Steps to reproduce
1. Edit a CMS Block and click "Insert Image". 
2. Try to upload an image.

### Expected result
1. The image should upload successfully.

### Actual result
1. You'll get an error like this: 
    ```
    Directory /var/www/prod/releases/20180228212716/pub/media/wysiwyg is not under storage root path.
    ```
    ![magento admin-xazv0](https://user-images.githubusercontent.com/129031/36911995-f52c824e-1e0a-11e8-8083-d71cfee2291f.jpg)

## Workaround

UPDATE: As of [Magento 2.2.5 / 2.3.0](https://github.com/magento/magento2/blob/2.2.5/lib/internal/Magento/Framework/App/Filesystem/DirectoryResolver.php#L38..L58), this issue has been fixed and you shouldn't apply the patch below or else you'll break the functionality.

We've temporarily fixed this by changing [this line](https://github.com/magento/magento2/blob/2.2.3/lib/internal/Magento/Framework/App/Filesystem/DirectoryResolver.php#L42) from this:
```
$realPath = realpath($path);
$root = $this->directoryList->getPath($directoryConfig);
```

to this (note the addition of the `realpath` function call):
```
$realPath = realpath($path);
// BEGIN EDIT
/**
 * Since media directory is a symlink, need to run both paths through realpath in order for the comparison to
 * work.
 * The proper fix for this should involve a STORE > Configuration setting where an admin can choose whether to
 * allow symlinked directories.
 */
$root = realpath($this->directoryList->getPath($directoryConfig));
// END EDIT
```

**Comment by magento-engcom-team** [comment]
@erikhansen, thank you for your report.
The issue is already fixed in 2.3.0
But we will consider to backport the fix to patch releases

**Comment by barryvdh** [comment]
Thank you, this is an important issue for us also. Is there a patch available for 2.2.3?

**Comment by hostep** [comment]
@magento-engcom-team: can you point us to the commit where this is fixed in 2.3-develop? I have the feeling that we will run into the same problems due to the way how we deploy to the servers.

**Comment by kanduvisla** [comment]
I can confirm this behavior as well in 2.1.12. Can the backport also be considered for 2.1.x?

**Comment by mikelevy300** [comment]
I'm having the same issue on 2.1.12.

**Comment by JosephMaxwell** [comment]
Just ran into this issue, too. Here is the code I used to fix it (temporarily):

## etc/di.xml

```
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Framework\App\Filesystem\DirectoryResolver"
                type="\ModuleVendor\ModuleName\App\Filesystem\DirectoryResolver"/>
</config>
```

## Override/App/Filesystem/DirectoryResolver.php

```
<?php
declare(strict_types=1);

/**
 * TODO: temporary override until patch or Magento 2.3 is released.
 * https://github.com/magento/magento2/issues/13929
 */
namespace ModuleVendor\ModuleName\Override\App\Filesystem;

use Magento\Framework\App\Filesystem\DirectoryList;

/**
 * Magento directories resolver.
 */
class DirectoryResolver
{
    /**
     * @var DirectoryList
     */
    private $directoryList;

    /**
     * @param DirectoryList $directoryList
     */
    public function __construct(DirectoryList $directoryList)
    {
        $this->directoryList = $directoryList;
    }

    /**
     * Validate path.
     *
     * Gets real path for directory provided in parameters and compares it with specified root directory.
     * Will return TRUE if real path of provided value contains root directory path and FALSE if not.
     * Throws the \Magento\Framework\Exception\FileSystemException in case when directory path is absent
     * in Directories configuration.
     *
     * @param string $path
     * @param string $directoryConfig
     * @return bool
     * @throws \Magento\Framework\Exception\FileSystemException
     */
    public function validatePath($path, $directoryConfig = DirectoryList::MEDIA)
    {
        $realPath = realpath($path);
        // BEGIN EDIT by @erikhansen
        /**
         * Since media directory is a symlink, need to run both paths through realpath in order for the comparison to
         * work.
         * The proper fix for this should involve a STORE > Configuration setting where an admin can choose whether to
         * allow symlinked directories.
         */
        $root = realpath($this->directoryList->getPath($directoryConfig));
        // END EDIT

        return strpos($realPath, $root) === 0;
    }
}
```

**Comment by yanncharlou** [comment]
@JosephMaxwell there's a typo in namespace in etc/di.xml
You should add \Override\
```
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Framework\App\Filesystem\DirectoryResolver"
                type="\ModuleVendor\ModuleName\Override\App\Filesystem\DirectoryResolver"/>
</config>

```

**Comment by osrecio** [comment]
I solved with [cweagans/composer-patches](https://github.com/cweagans/composer-patches). 
I created a patch (for Magento Composer projects):
name: `13929_2.2.3_directory_resolver_composer_v1.patch`
```
Index: magento/vendor/magento/framework/App/Filesystem/DirectoryResolver.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- magento/vendor/magento/framework/App/Filesystem/DirectoryResolver.php	(date 1521531005000)
+++ magento/vendor/magento/framework/App/Filesystem/DirectoryResolver.php	(date 1521561205000)
@@ -39,7 +39,7 @@
     public function validatePath($path, $directoryConfig = DirectoryList::MEDIA)
     {
         $realPath = realpath($path);
-        $root = $this->directoryList->getPath($directoryConfig);
+        $root = realpath($this->directoryList->getPath($directoryConfig));
         
         return strpos($realPath, $root) === 0;
     }
```

**Comment by andrewhowdencom** [comment]
This presumably broke as part of the security patches (there's a bunch of stuff associated with path disclosures and RCEs in the 2.2.3 release). Anyone got any idea *why* this change was made? (so we don't set about reintroducing it with third party fixes)

**Comment by piotrekkaminski** [comment]
@magento-engcom-team 
>The issue is already fixed in 2.3.0
According to your previous comment it is fixed. I don't see it being fixed. Can you point out to commit/Jira issue with the fix?

**Comment by andrewhowdencom** [comment]
Obligatory: https://github.com/sitewards/magento2-fix13929

**Comment by mikewhitby** [comment]
I'm working on it #distributed-cd

**Comment by erikhansen** [comment]
@andrewhowdencom - For the record, I much prefer to fix core issues like this using the [cweagans/composer-patches](https://github.com/cweagans/composer-patches) approach that @osrecio [mentioned above](https://github.com/magento/magento2/issues/13929#issuecomment-374865576) rather than using a preference. The reason for this is that if the underlying code changes in a future version of Magento (which is likely in this situation), the `composer install` will fail to complete which will alert you to the fact that the patch needs to be removed or changed to work with the latest code. This is assuming that you have the `composer-exit-on-patch-failure` option set to `true`.

**Comment by andrewhowdencom** [comment]
> @andrewhowdencom - For the record, I much prefer to fix core issues like this using the cweagans/composer-patches approach that @osrecio mentioned above rather than using a preference

Yah that seems reasonable ^^ I packaged it as an extension for easy distribution so it hooks into our existing mechanisms for discovery by our team internally (namely, satis / bitbucket). I could further restrict it to the specific version of Magento (actually @mzeis spotted that) but it's a dirty temporary fix until core addresses it -- I hadn't put too much thought into managing it long term.

**Comment by p-bystritsky** [comment]
Issue is reproducible on 2.3-develop branch.

**Comment by vseager** [comment]
Able to reproduce on 2.1.12

**Comment by magento-engcom-team** [comment]
@erikhansen, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by okorshenko** [comment]
Hi @erikhansen. Thank you for your report. 
The issue has been fixed in magento/magento2#14353 by @mikewhitby in 2.3-develop branch
Related commit(s):
 - [a866bb50e3447365f17c3c41e5d4b1c90e59582b](https://github.com/magento/magento2/commit/a866bb50e3447365f17c3c41e5d4b1c90e59582b)

The fix will be available with the upcoming 2.3.0 release.

**Comment by gnysek** [comment]
On Windows this may be because `\Magento\Framework\Filesystem\Directory\Read::setPath` replaces `\` to `/`, while in other places `realpath()` again returns `\` in path (as this is windows default). Lot of functions which does `strpos` later breaks because of this (like eg. `\Magento\Framework\App\Filesystem\DirectoryResolver::validatePath`).

**Comment by digvijay2017** [comment]
Hi Guy's,
I have applied the above solution and now i am able to create the new directory. But now i am not able to delete the directory. Is someone else facing this problem after applying the above solution. I have created the directory 'Testing' and now i am trying to delete this, but nothing happening and  i'm not getting any error. 
![screenshot from 2018-05-28 13-58-04](https://user-images.githubusercontent.com/30342958/40605345-c082c558-627f-11e8-8d35-f2c15a1679da.png)

I am using Magento 2.2.3. Well, i'm noticed this issue in Magento 2.1.12 and 2.2.1 as well.

**Comment by ipascual** [comment]
Applying @osrecio patch:

**1. Install composer-patches**
`composer require cweagans/composer-patches`

**2. Save patch file**
patches/13929_2.2.3_directory_resolver_composer_v1.patch
```
--- /vendor/magento/framework/App/Filesystem/DirectoryResolver.php	2018-02-21 01:25:30.000000000 +0000
+++ /vendor/magento/framework/App/Filesystem/DirectoryResolver.php	2018-06-02 17:04:53.000000000 +0000
@@ -39,7 +39,7 @@
     public function validatePath($path, $directoryConfig = DirectoryList::MEDIA)
     {
         $realPath = realpath($path);
-        $root = $this->directoryList->getPath($directoryConfig);
+        $root = realpath($this->directoryList->getPath($directoryConfig));
         
         return strpos($realPath, $root) === 0;
     }
```

**3. Modify composer.json**
```
    "extra": {
        "magento-force": "override",
        "patches": {
            "magento/framework": {
                "Issue #13929: Images can't be uploaded using WYSIWYG if media directory is a symlink": "./patches/13929_2.2.3_directory_resolver_composer_v1.patch"
            }
        }
    }
```

**4. Patch it!**
`composer install`

**Comment by WengerMa** [comment]
Issue is reproducible in 2.2.4 tag as well.

**Comment by n0kit31** [comment]
Issue is reproducible in 2.2.4 tag as well.

**Comment by lisovyievhenii** [comment]
#kiev-cd

**Comment by magento-engcom-team** [comment]
@lisovyievhenii thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by clemblanco** [comment]
Is this fixed for 2.2.4 yet?

**Comment by MidnightDesign** [comment]
@clementblanco It's fixed in 2.2.5.

**Comment by mikehenze** [comment]
Still have this problem on 2.2.5

**Comment by tuyennn** [comment]
Same this problem on 2.1.14

**Comment by aKalisch** [comment]
@magento-engcom-team i have the same issue as @digvijay2017.

File: Magento\Cms\Model\Wysiwyg\Images\Storage
```
    /**
     * Is path under storage root directory
     *
     * @param string $path
     * @return void
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _validatePath($path)
    {
        $root = $this->_sanitizePath($this->_cmsWysiwygImages->getStorageRoot());
        if ($root == $path) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('We can\'t delete root directory %1 right now.', $path)
            );
        }
        if (strpos($path, $root) !== 0) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('Directory %1 is not under storage root path.', $path)
            );
        }
    }
```

**Comment by maximbaibakov** [comment]
Just tested this on 2.2-develop branch and it has been fixed there already.
Tested this on 2.2.5 and it has been fixed there.

There is a commit for a reference: https://github.com/magento/magento2/commit/a6afb598e57ec11df51396ef2acadf4ec996da30

If someone still experience the issue, please provide more details

**Comment by TehJackal** [comment]
I've just recently installed 2.2.5 in the past week after this was closed 9 days ago.

I am still experiencing the issue with image uploads.

**Comment by maximbaibakov** [comment]
Hi @TehJackal 

Could you please explain what is your setup?
What error do you see?
What is your symlink path?

Regards,
Maxim

**Comment by TehJackal** [comment]
I'm not sure what you mean by Symlink path, as I'm still fairly new to using and working with Magento 2

That being said when I try to upload a simple Jpg file, it does a refresh icon and then gives me this.

![image](https://user-images.githubusercontent.com/10318138/44382182-fb914a80-a4e1-11e8-9fef-89aedfb9649e.png)

**Comment by hostep** [comment]
@TehJackal: that's a completely different error then what is discussed in this thread and has indeed nothing to do with symlinks. You might find a solution in the following thread though: https://github.com/magento/magento2/issues/16531 (try installing the php extension 'fileinfo')

**Comment by Neusta-Hartwig** [comment]
We've just installed 2.2.6, and the issue ist still there.

The fix mentioned above does not work in Magento 2.2.6. :(

**Comment by ChrHartwig** [comment]
This error is [fixed in 2.2.5](https://github.com/magento/magento2/blob/2.2.5/lib/internal/Magento/Framework/App/Filesystem/DirectoryResolver.php#L38..L58)

**Comment by tushhan** [comment]
Hi, This problem occurs on Magento 2.3.4 as well.

1- File validation fails if upload an image
2- Sub folders shows an error as below.

---
Fatal error: Uncaught Error: Call to undefined function mime_content_type() in
.....
/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php on line 362
----


![Screenshot 2020-04-20 at 17 42 39](https://user-images.githubusercontent.com/746774/79777417-21ae6400-832f-11ea-87c0-36344169e2b8.png)

**Comment by hostep** [comment]
@tushhan: you need the `fileinfo` php extension, I already mentioned it above 😉 
Good luck!

Strictly speaking, it's a bug in Magento however, there is [a suggestion](https://github.com/magento/magento2/pull/24455#issuecomment-530907778) to fix it, but might take a while until somebody picks it up.

**Comment by antonfries** [comment]
We got this error in 2.3.7-p1 in a very big project. The fix was to increase/deactive the max_session_size in admin. The cause was, that the current_path-variable couldn't be saved persistently in the session-object for the upload to work.

**Comment by pisarkov** [comment]
Fixed by increasing session size values (Configuration -> System -> Security).
![image](https://user-images.githubusercontent.com/39527698/133275214-c327df68-eb9d-44fd-b2a0-fe5cc8099952.png)

**Comment by marcelloinfoweb** [comment]
@pisarkov, It didn't work for me.

Magento 2.4.3

**Comment by hafizmuzamal** [comment]
@marcelloinfoweb what is the exact issue you are facing right now?

**Comment by marcelloinfoweb** [comment]
> @marcelloinfoweb qual é o problema exato que você está enfrentando agora?

![Error_delete-image](https://user-images.githubusercontent.com/2093128/137138581-5832d3e1-b812-4f9d-adbd-851d4cc774ff.gif)
![Error_insert-image](https://user-images.githubusercontent.com/2093128/137138620-72eb339a-f63c-4ab3-9ef4-3c8068139916.gif)

**Comment by focus97** [comment]
Getting same issue as @marcelloinfoweb 

@marcelloinfoweb - were you able to find a fix?
