### ISSUE TITLE
catalogsearch_fulltext indexer never gets invalidated 

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#13927]
When all indexers are in *Update by Schedule* mode, 'catalogsearch_fulltext' index never gets invalidated and will be never re-indexed by cron ("indexer_reindex_all_invalid" job).

### Preconditions

1. Magento 2.1.9 CE
2. PHP 7.0.22
3. 10.0.33-MariaDB
4. Create some products with enable and disable status

### Steps to reproduce

1. Log in to Admin
2. Go to System > Index Management
3. Set all indexers to *Update by Schedule* mode through Magento admin
4. Enable disabled product
5. Wait until cron will run "indexer_reindex_all_invalid" job

### Expected result

1. Product appears on catalogsearch-result-index page
2. Product shown on front-end

### Actual result

1. Product DOESN'T appears on catalogsearch-result-index page
2. Prodduct dont show on front-end

**Comment by kvydiuk** [comment]
I think issue in Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin class
_reindexRow_ and _reindexList_ methods checks indexer mode and re-index it only indexer mode != "Update By Schedule". Otherwise seems indexer should be invalidated here.

**Comment by magento-engcom-team** [comment]
@breg-13, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by kvydiuk** [comment]
@magento-engcom-team, thanks!

**Comment by rparsi** [comment]
@magento-engcom-team Updates please, has this been fixed and if so please include link to commit or pull request

**Comment by Ctucker9233** [comment]
@magento-engcom-team We would love to see a fix. It's getting close to being a year old.

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**
    Create some products with enable and disable status

**Steps to reproduce:**

1. Log in to Admin
2. Go to System > Index Management
3. Set all indexers to Update by Schedule mode through Magento admin
4. Enable disabled product
5. Wait until cron will run "indexer_reindex_all_invalid" job

**Result**
1. Product appears on catalogsearch-result-index page
2. Product shown on front-end
![Screenshot_46](https://user-images.githubusercontent.com/51681435/71575722-c4c83d00-2af6-11ea-9493-c67a4515c309.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
