### ISSUE TITLE
B2B - Missing arrow in permissions management tree

### ISSUE THREAD

**Issue by Selven99** [magento/magento2#13928]
### Preconditions

1. Have Magento 2 Commerce 2.2.2 or 2.2.3 (tested on both)
2. Have extension-b2b installed by composer (at least 1.0.2, also tested with 1.0.3 that's needed for Magento 2.2.3)

### Steps to reproduce

1. Go to backend System > Permissions > User Roles
2. Add or edit an existing role
3. Click on "Role Resources" tab in left panel

### Expected result

1. Tree is displayed correctly

### Actual result

1. Tree is broken, the arrows to roll/unroll are missing !!
2. If we know where they are we can click in the void anyway and it works... Only image seems to be missing

![selection_009](https://user-images.githubusercontent.com/11805144/36911698-9d3a359c-1e44-11e8-950e-6150c6941568.png)

Note: there is no error in our debug console... It's strange.
If we remove extension-b2b from composer.json and update, tree is OK.
=> A module present in extension-b2b package cause this issue! (if it can help :+1: )

Thanks for your help :)

**Comment by magento-engcom-team** [comment]
@Selven99 , 
thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@Selven99, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
