### ISSUE TITLE
Fix USPS Priority Mail to United Kingdom

### ISSUE THREAD

**Issue by DKoctopus** [magento/magento2#13921]
### Preconditions

1. Magento 2.1.8 (fresh install, no customizations)
PHP 7.0.20
MySQL 5.6.35

### Steps to reproduce

Enable USPS shipping method, add credentials, live mode, select "Priority Mail International" in allowed methods
Add product (configurable, if it matters) to cart, begin checkout, add international shipping address

### Expected result
Priority Mail International" shipping method should be offered

### Actual result
Priority Mail International" is not offered

**Comment by magento-engcom-team** [comment]
@DKoctopus, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by vrann** [comment]
#MageTitansMX18

**Comment by magento-engcom-team** [comment]
@vrann thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by vrann** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@DKoctopus, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@DKoctopus The issue is already fixed in 2.2.
Closing ticket for now. Please reopen if you need any further assistance with this.

**Comment by Ctucker9233** [comment]
@magento-engcom-team What are the commits for this issue?
