### ISSUE TITLE
Could you add TYPE_VARCHAR

### ISSUE THREAD

**Issue by SKovbel** [magento/magento2#1392]
Could you add new type
       \Magento\Framework\DB\Ddl\Table::TYPE_VARCHAR

**Comment by orlangur** [comment]
`TYPE_TEXT` is used for this:
https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L1685
https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2277

**Comment by Mackovey** [comment]
So is `varchar` type deprecated in Magento2?
Or what the reason why i must use `text` instead of `varchar`

**Comment by nevvermind** [comment]
@Mackovey - have you clicked the links? `varchar` wil be used if the specified col length is `<= 255`.

**Comment by orlangur** [comment]
> So is `varchar` type deprecated in Magento2?

No, just one `TYPE_TEXT` constant is used to represent all following types:
```
            case 'tinytext':
            case 'char':
            case 'varchar':
            case 'text':
            case 'mediumtext':
            case 'longtext':
                return Table::TYPE_TEXT;
```
and the most suitable type of the DB engine will be used automatically.

**Comment by Mackovey** [comment]
>> No, just one TYPE_TEXT constant is used to represent all following types:

ok, understood, thanx

**Comment by vpelipenko** [comment]
@Mackovey, can we close this issue?

**Comment by Mackovey** [comment]
You can.

![3013](https://cloud.githubusercontent.com/assets/813985/8287739/61925542-191a-11e5-89e3-ec9fc6b144a1.png)

**Comment by orlangur** [comment]
Ok, now I understood you request.

https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2277 seems to be from ages when `VARCHAR` could not be longer than 255 characters.

After reading [this thread](http://stackoverflow.com/a/2023513) I'm not sure whether there is a practical reason to have `VARCHAR` column longer than 255 characters:
> Both VARCHAR and BLOB/TEXT are stored inline with other columns if the value on a given row fits in the page size

Thoughts?

**Comment by akaplya** [comment]
The reason to keep varchar size less than 256 symbols -- give an ability to create index for single varchar field. http://dev.mysql.com/doc/refman/5.6/en/column-count-limit.html
