### ISSUE TITLE
When cache is enabled getting the previous order Id in payment step instead of latest one

### ISSUE THREAD

**Issue by vinaysikarwar** [magento/magento2#13939]
### Preconditions

1.  When placing an order at payment step in my custom payment when calling ajax request to get the last order id after creating the order it returning the previous order id instead of current order which placing
2. This works fine when cache is disabled
3. when again submit the ajax request it shows current order id from   \Magento\Checkout\Model\Session getLastRealOrder method. which is current. but first time it shows the previous one.

### Steps to reproduce

1. Enable the cache
2. you need to use the $this->_checkoutSession->getLastRealOrder(); when submitting the payment place order button via ajax
3. In controller you will see first no order id then in second time you will see the previous order id and third time the second one. So first time never it shows the current real order id when cache is enabled 

### Expected result

1.  It should get a current real order id

### Actual result

1. It is showing the previous order id

**Comment by vinaysikarwar** [comment]
This is almost similar issue like described here https://github.com/magento/magento2/issues/6425

but did not get any solution to this

**Comment by anant-svc** [comment]
@vinaysikarwar 
What is declared in $this->_checkoutSession?

**Comment by vinaysikarwar** [comment]
\Magento\Checkout\Model\Session

**Comment by anant-svc** [comment]
@vinaysikarwar 
It seems your ajax is called before order is placed. So you get cached real order id on second try.

**Comment by vinaysikarwar** [comment]
Order already created using the payment method js
placeOrder = placeOrderAction(this.getData(), false, this.messageContainer);
and getting the order id

**Comment by anant-svc** [comment]
@vinaysikarwar 
Initialize \Magento\Checkout\Model\Session class using Object Manager

Note: We can initialize Session and Cookie class using Object Manager.

**Comment by vinaysikarwar** [comment]
Already did that. But same issue when caching enabled. Disabling the cache working fine

**Comment by anant-svc** [comment]
@vinaysikarwar 
Check below file must call before your ajax in cache, log the time and check which is called first.

/vendor/magento/module-checkout/Model/Type/Onepage.php Line **739**
In above file LastRealOrderId is saved to session. You can also check what is saved in session after place order.

**Comment by vinaysikarwar** [comment]
Actually I was doing something wrong. I was not adding my ajax when order successfully created and id is returned.

`$.when(placeOrder).fail(function () {
	self.isPlaceOrderActionAllowed(true);
}).done( function(order_id) {
	// write your custom code here
});`
