### ISSUE TITLE
beta 13 to beta 14: setup:upgrade

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1394]
Autoload error:An abstract factory could not create an instance of magentosetupconsolecommandmoduleuninstallcommand(alias: Magento\Setup\Console\Command\ModuleUninstallCommand).

**Comment by vancoz** [comment]
Hello @sivajik34, 

could you please run composer update and clean up var/cache and var/generation?

Thank you

**Comment by sivajik34** [comment]
thanks.
