### ISSUE TITLE
Fatal error: Class 'IntlDateFormatter' not found in C:\xampp\htdocs\mhd\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php on line 111

### ISSUE THREAD

**Issue by mohanadly89** [magento/magento2#13941]
i moved magento 2 from server to localhost in xampp

when opening the url i get this error .

note : 
1-changed database secure url and unsecure url 
2-enabled extension=php_intl.dll
2-changed app\etc\env  file with database name and database user and password
3-deleted the files in var\cache .

and still the getting the error

Fatal error: Class 'IntlDateFormatter' not found in C:\xampp\htdocs\mhd\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php on line 111

**Comment by magento-engcom-team** [comment]
@mohanadly89, thank you for your report.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by crypto-demigod** [comment]
@mohanadly89, I'm Yutaka Yoshida.
Happy new year!
Please accept my contact on skype.
My skype mail is sherlock0105@outlook.com
