### ISSUE TITLE
Track not saved during shipment creation through API

### ISSUE THREAD

**Issue by siimm** [magento/magento2#13954]
### Preconditions

1. Magento CE 2.2.3 with sample data installed (Also same in CE 2.2.2)
2. PHP 7.0.22

### Steps to reproduce

1. Create an order with one item
2. Use Magento REST API to create a shipment (POST <magento install url>rest/V1/shipment/)
Request body:
`{
"entity":{
  "order_id":3,
  "items": [
    {
      "order_item_id": 3,
      "qty": 1
    }
  ],
 "comments": [
      {
        "is_customer_notified": 1,
        "comment" : "this is a comment for order #3"
      }
    ],
  "tracks": [
    {
    "track_number": "2Y-987651110",
    "title": "United Parcel Service",
    "carrier_code": "ups",
    "order_id":3,
    "extension_attributes" : {}
    }
  ]
}
}`
Request with better formatting as a gist: https://gist.github.com/siimm/d4f2f6644e0d1255cbe4339bb42084e2

### Expected result

1. A shipment is created with a comment added and tracking attached

### Actual result

1. Shipment is created with comment added but without any tracking number attached

### General background:
Upon saving the shipment relations in Magento\Sales\Model\ResourceModel\Order\Shipment\Relation::processRelation()
$object->getTracksCollection() is consulted, while during the API request $object->setTracks() is used and it is not set as a collection

As a solution getTracks() should also be processed in Relation class, or the tacks should be added using addTarck() method on Shipping model (which initialises the collection of tracks)

**Comment by magento-engcom-team** [comment]
@siimm, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by arijit-de93** [comment]
I am working on this at #dmcdindia

**Comment by michaelbakertup** [comment]
Does anyone know if this is fixed in 2.2.6 ?

**Comment by mirkocesaro** [comment]
> Does anyone know if this is fixed in 2.2.6 ?

@michaelbakertup the issue is still there

**Comment by mam08ixo** [comment]
AFAIK the preferred endpoint for creating shipments is `POST /V1/order/{orderId}/ship`.

**Comment by engcom-Alfa** [comment]
Hi @siimm. 
We are not able to reproduce this issue on fresh 2.4-develop instance. Everything works correctly.

**Manual testing scenario:**
1. Create an order with one item ("order_id":1, order_item_id": 1) for ex.;
2. Use Magento REST API to create a shipment (POST rest/V1/shipment/)
Request body:
`{ "entity":{ "order_id":3, "items": [ { "order_item_id": 3, "qty": 1 } ], "comments": [ { "is_customer_notified": 1, "comment" : "this is a comment for order #3" } ], "tracks": [ { "track_number": "2Y-987651110", "title": "United Parcel Service", "carrier_code": "ups", "order_id":3, "extension_attributes" : {} } ] } }`

**Actual Result:**
![screen](https://user-images.githubusercontent.com/51679138/71727795-113bb180-2e44-11ea-88d8-5dfbccc9f732.png)

A shipment is created with a comment added and tracking attached
![screen2](https://user-images.githubusercontent.com/51679138/71727947-7beced00-2e44-11ea-8010-1692c9001b17.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
