### ISSUE TITLE
Cache issue with configurable products related to currency-conversions

### ISSUE THREAD

**Issue by evgk** [magento/magento2#13950]
Issue to PR #13894 

### Preconditions
Latest fresh Magento version.

### Steps to reproduce
Steps to reproduce the problem on a fresh Magento installation:
1. Set Magento to use the following currency setup:
- Base currency - USD
- Default display currency - USD
- Allowed currencies - Czech Republic Koruna, Danish Krone, US Dollar
2. Stores -> Currency rates should be set to the following:
USD/CZK rate: 20.8110
USD/DKK rate: 6.0967
3. Create configurable product with 1 product attached to it.
Set the price on the attached virtual product to $1 USD.
Make configurable product visible in frontend.
4. Make sure block cache is enabled and visit frontend(during my test, all caches were enabled). 
Then do the following sequence of actions(the order is important):
- Visit configurable product - you should see the default price of $1.
Select the only available option in the select box(since only 1 product was added).
Price does not change - it should still be $1.
- Now, select DKK in the currency-select box. The price should change to 6.10.
If you select the only product-option available, the price should stay the same(6.10)
- Now, select CZK. The price should change to 20.81. Then select the only available product-option.
The price will change to 6.10, which is incorrect.

### Expected result
The price should still be 20.81

### Actual result
The price changes to the cached value of 6.10, cache is not unique since both DKK & CZK currencies don't have a currency-symbol. Suggested PR fixes that.

**Comment by magento-engcom-team** [comment]
@evgk, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by krzksz** [comment]
Closing this as mentioned PR was merged: https://github.com/magento/magento2/pull/13894
