### ISSUE TITLE
unlimited brands

### ISSUE THREAD

**Issue by sultan619** [magento/magento2#13953]
i got a magento 2 store and im using codazon extension and i wanted to add my brands and its more than 500 brand .. and i started to add them to the attributs it wont add more than 166 brand
i looked up for a solution and i found no option that help me do what i needed to do in the first place .

**Comment by magento-engcom-team** [comment]
Hi @sultan619 
May be t is an duplicate on #11985?

**Comment by sultan619** [comment]
hi

**Comment by orlangur** [comment]
Hi @sultan619, this GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.
