### ISSUE TITLE
\Magento\Sales\Model\Order\Status has no repository.

### ISSUE THREAD

**Issue by kshaa** [magento/magento2#13958]
### Preconditions
1. I want to create a new order status in an upgrade script.

### Steps to reproduce
1. Try to find a repository class for \Magento\Sales\Model\Order\Status anywhere in M2's codebase 
2. Fail trying.

I know that models should be created and fetched through repositories (service contracts) and the model load methods are deprecated. How should one proceed if the deprecated method is the only choice, just ignore the deprecation? Is the order status model planned to be updated to include a repository for ease of use?

**Comment by magento-engcom-team** [comment]
@kshaa, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
> I know that models should be created and fetched through repositories (service contracts)

This is not true. Check https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/EntityManager/EntityManager.php#L19 for more details.

**Comment by davidbrandastic** [comment]
@orlangur  while that may be the case, service contract patterns are the recommended method for development according to the Dev Docs.

Class Hierarchy:
- Status extends \Magento\Sales\Model\AbstractModel
- AbstractModel extends AbstractExtensibleModel
-  AbstractExtensibleModel extends AbstractModel implements
    \Magento\Framework\Api\CustomAttributesDataInterface


```/**
     * Save object data
     *
     * @return $this
     * @throws \Exception
     *
     * @deprecated 100.1.0 because entities must not be responsible for their own persistence.
     * Service contracts should persist entities. Use resource model "save" to implement
     * service contract persistence operations.
     */
 ```

 ``` 
/**
     * Load object data
     *
     * @param integer $modelId
     * @param null|string $field
     * @return $this
     * @deprecated 100.1.0 because entities must not be responsible for their own loading.
     * Service contracts should persist entities. Use resource model "load" or collections to implement
     * service contract model loading operations.
     */ 
```

At that point you have to ignore the deprecation or start working directly with the SQL adapter, which isn't any better.

http://devdocs.magento.com/guides/v2.2/extension-dev-guide/service-contracts/service-contracts.html
http://devdocs.magento.com/guides/v2.2/extension-dev-guide/service-contracts/design-patterns.html
http://devdocs.magento.com/guides/v2.2/extension-dev-guide/searching-with-repositories.html

**Comment by orlangur** [comment]
@davidbrandastic, you can still use resource model for this entity

```
protected function _construct()
    {
        $this->_init(\Magento\Sales\Model\ResourceModel\Order\Status::class);
    }
```

in comment you quoted

> Use **resource model "load"** or collections to implement
    * service contract model loading operations.

**Comment by orlangur** [comment]
@kshaa, 

> How should one proceed if the deprecated method is the only choice, just ignore the deprecation? Is the order status model planned to be updated to include a repository for ease of use?

just check PHPDocs for deprecated methods

```
  * @deprecated 100.1.0 because entities must not be responsible for their own loading.
    * Service contracts should persist entities. Use resource model "load" or collections to implement
    * service contract model loading operations.
```

and follow this recommendation.
