### ISSUE TITLE
Magento 2 - OAuth Problem = Consumer Key Has Expired

### ISSUE THREAD

**Issue by itsabe** [magento/magento2#13961]
### Preconditions
1. Magento Version 2.4
2. Set up and activated API Integration with full access

### Steps to reproduce
1. Create integrations
2. Make POST call to `/oauth/token/request`

### Expected result
1. Get request token

### Actual result
1. oauth_problem=Consumer+key+has+expired

![image](https://user-images.githubusercontent.com/15145911/36991851-fd4c4cb6-2076-11e8-8263-2a50d0fa1922.png)

I tried it with two different integrations, both are activated, and both return the same response of "consumer key has expired"

**Comment by magento-engcom-team** [comment]
Hello @itsabe. Thanks for reporting. Please confirm us that You have everything OK with those settings in Your Magento Backend: Stores->Configuration->Servises->OAuth->Consumer Settings section.

**Comment by itsabe** [comment]
![image](https://user-images.githubusercontent.com/15145911/37036082-9b146776-211c-11e8-8db1-513605fdd095.png)

Yes, everything looks okay.

**Comment by magento-engcom-team** [comment]
@itsabe, then please confirm that Expiration period of 300 sec. for Consumer Settings was enough for You, so that Consumer key/secret You got while creating (activating) the integration was not yet expired when You sent  /oauth/token/request. Thank You.

**Comment by itsabe** [comment]
@magento-engcom-team yes, it is enough. I even just created another integration, and send a POST to /oauth/token/request and got the same response of consumer key has expired. This was all done within 2 minutes.

**Comment by itsabe** [comment]
Also, I stumbled upon #12032 from back in Nov 2017, but have not seen any updates on it.

**Comment by magento-engcom-team** [comment]
@itsabe , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by itsabe** [comment]
Is there any work around? Or am I unable to connect to the API?

**Comment by itsabe** [comment]
I found the source of my issue. Upon creating the integration and activating it, I get a consumer key, consumer secret, access token, and access token secret. So, technically, I can just skip the "Get Access Token" step of the authentication. I was able to successfully make API calls with the provided access token.

If I created the integration with an Identity link URL, then the access token and access token secret is not supplied. And when I made a request to /oauth/token/request, I got the access token and secret as a response. 

If this was the intended process, then my apologies for misinterpreting the documentation.

**Comment by Lapinou42** [comment]
Hello guys, 

I have exactly the same issue on Magento 2.2.3. Many hours trying to understand what's wrong.

**Comment by itsabe** [comment]
@Lapinou42 Are you still experiencing the issue? When you create the integration and activate it through Magento backend, you can use the access token they provide you to make the API calls.

**Comment by Lapinou42** [comment]
Yes, I do. 

Actually, I want to create an integration to use with my Android / iOS application using OAuth1.0a.
I tried in Postman and I have the same issue.

I want to generate an access token by user, so simply use Consumer Key, Consumer Secret, RequestTokenUrl and AccessTokenUrl should be enough to generate an access token.

Maybe I'm wrong. I don't know.

**Comment by itsabe** [comment]
@Lapinou42 When you create the integration on Magento backend (System > Integrations), do you enter a Identity link URL? If you have that field filled in, then you should be able to get the access token by making a request to /oauth/token/request.

**Comment by Lapinou42** [comment]
@itsabe No. I didn't ! I'll try that and let you know if something wrong ;)

Thank you :)

**Comment by maniramav** [comment]
@itsabe I tried with Identity link URL, still having same issue.

Then I changed **Store > Settings > Configuration > Services > OAuth > Consumer Settings > Expiration Period** to **1000000000000**
![capture1](https://user-images.githubusercontent.com/11077689/39813139-28bc8ea4-5387-11e8-9164-671b8e442c65.JPG)

Now I am getting the result as
`oauth_problem=Invalid+signature`
![capture2](https://user-images.githubusercontent.com/11077689/39813210-7372c18e-5387-11e8-9eab-c39595a5760f.JPG)

**Comment by itsabe** [comment]
@maniram1804 what if you unchecked the "Add empty parameters to signature" option?

**Comment by maniramav** [comment]
@itsabe still same result.

**Comment by DanielRuf** [comment]
Did already someone do some bisecting here?

Is this an actual regression (did it work before?) or is it just with the new feature and it is not properly integrated in the code?

**Comment by mohammedsalem** [comment]
is there any updates here? 
facing the same problem

**Comment by Lapinou42** [comment]
Nope. Stopped using Magento.

**Comment by michaelhofer** [comment]
Same issue here with Magento 2.2.3. Are there any news on this?

**Comment by deepakgupta28** [comment]
Hi, 

Anyone Help me to suggest REST API Authentication using oauth 1

I am using OAuth based authentication,

But Its Showing

{“message”:”Consumer is not authorized to access %resources”,”parameters”:{“resources”:”Magento_Customer::customer”}

I am getting above errror, Please try to resolve it

Please resolve it I am using Magento 2.2.3 version, using below code to authenticate it

**Comment by scottw-finao** [comment]
Same issue with 2.2.4

**Comment by artszko** [comment]
@magento-engcom-team any updates on this?

**Comment by ghost** [comment]
Same issue with 2.2.6

**Comment by haiwera-silk-cd** [comment]
The issue still exists, is there any PR or patch for it? a whole year has been elapsed

**Comment by scottw-finao** [comment]
Our solution was to drop magento entirely

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30108` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
This issue was closed without any info written. Please check if it still actual

**Comment by ihor-sviziev** [comment]
@sdzhepa this looks really important issue, there was discussion in `#appdesign` channel in Slack https://magentocommeng.slack.com/archives/CBSL1DF8B/p1588761675119500.
Could you confirm this issue and set the correct prio / severity?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30108` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @ihor-sviziev 

It seems @KiuNguyen  closed this issue by mistake.
I have reopened internal Jira ticket and link with this issue again

**Comment by qsolutions-pl** [comment]
@sdzhepa basicall there are multiple issues here, first findings shows that "updated_at" field values are 0000-00-00 00:00:00 in on of oauth tables.

**Comment by PiotrSiejczuk** [comment]
@sdzhepa: Mistakes happen, to everyone...

Although this shows an issue in the process. What actions you guys at CORE are planning to take to mitigate this? Such flow should not happen in the first place and it looks like it can happen in future for any other tickets (yes also to VALID tickets and issues)...

**Comment by lenaorobei** [comment]
@PiotrKorzeniec95, it was addressed recently. We limited write access to the Magento 2 repository, so it should prevent unintentional issues closing.

**Comment by lenaorobei** [comment]
@magento give me test instance

**Comment by lenaorobei** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, here is your [Magento instance](https://i-13961-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-13961-2-4-develop.instances.magento-community.engineering/admin_1ab9](https://i-13961-2-4-develop.instances.magento-community.engineering/admin_1ab9)
Login: `1370780a` Password: `cc2a7135725d`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
> @PiotrKorzeniec95, it was addressed recently. We limited write access to the Magento 2 repository, so it should prevent unintentional issues closing.

I can confirm, we contributors can not close any issues or PRs anymore so we have to ping someone from the maintainer teams.

**Comment by lenaorobei** [comment]
I'm unable to reproduce this isse. 

There are two possible scenarios for using OAuth for Magento integrations.

### Access allowed resources by using generated keys

New integration can be created using the described steps. 
<img width="1198" alt="Screen Shot 2020-05-06 at 12 21 31 PM" src="https://user-images.githubusercontent.com/17548019/81208262-658ea380-8f94-11ea-98ac-07274f8bddaf.png">
<img width="1267" alt="Screen Shot 2020-05-06 at 12 21 51 PM" src="https://user-images.githubusercontent.com/17548019/81208265-66bfd080-8f94-11ea-91c0-1d9898f42913.png">
<img width="1271" alt="Screen Shot 2020-05-06 at 12 22 11 PM" src="https://user-images.githubusercontent.com/17548019/81208272-68899400-8f94-11ea-8e7f-72b4ed73a801.png">
Test instance from https://github.com/magento/magento2/issues/13961#issuecomment-624732511 can be used to check that.

### OAuth-based authentication - [DevDocs](https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-oauth.html)
This approach requires to follow the instruction from DevDocs. `Callback URL` and `Identity link` URL should be specified in order to ask for a request token.

Example demo script with OAuth client can be found here https://gist.github.com/paliarush/4c2bfa81ebef57305ba4

⚠️ If the isse is not clear message, please feel free to update the issue description and expected result.

**Comment by PiotrSiejczuk** [comment]
@lenaorobei I guess your the comment was for me? :)

The issue was actually encountered by a colleague of mine from different SI (I am just a Messager here :)). @qsolutions-pl  maybe you can give some more inputs for Lena?

**Comment by qsolutions-pl** [comment]
I'm currently debugging this on my end, 2.3.5 version, will send an update once I finish

**Comment by qsolutions-pl** [comment]
@lenaorobei @ihor-sviziev 
so basically this feature is a little bit buggy, currently testing on 2.3.2 (current live site) and 2.3.5 
Here is my step by step:
1) created integration
2) authorized the application (using the prepared scripts from this URL   https://gist.github.com/paliarush/4c2bfa81ebef57305ba4 with some fixes ;))
3) using consumer and access key pairs 
I am able to:
- get product details 
- get customer details 

So... basically I cannot replicate the issue today, even though yesterday it was clear :( In my humble opinion the documentation needs to be updated how `oauth_signature` is calculated in order to be able to use applications like PostMan (or any other soapUI) so you can prepare `oauth_signature` required for authentication.

From looks of it, yesterday (and reported problem on github) comes from not clear instructions 
in dev docs. Here is what I've done a day ago:
- created an integration, send "Activate" request to dummy URL which only recorded send params. 
- Magento did "Authorize" this application even though it didn't get any callback from remote app, information in the database was **not** update 
![image](https://user-images.githubusercontent.com/4256191/81304253-1a9c8b00-907d-11ea-8726-c6355ea9dfa2.png)

So here is (I belive so) the **REAL** issue with this:
1) create new integration
2) leave `CallBack URL` and `Identity link URL` empty
3) save the integration (magento will generate `access token` and `access token secret`)
4) Authorize the appliaction

after you "**Authorize**" it in backend, field updated_at in database remains empty 
![image](https://user-images.githubusercontent.com/4256191/81304891-f8573d00-907d-11ea-8633-8a2e51440f86.png)
and that is causing issues with key validation `consumer key has expired`

I think Magento should not authorize an application without endpoints and without checks for callback, or a "self-authorization" needs to be fixed on code level to specify "updated_at" with right value.

There is a second issue with this,

**Comment by PiotrSiejczuk** [comment]
@lenaorobei seems the issue is still there and valid. More details were provided. Is there a chance you can check internally the situation? Thank you in advance!

**Comment by lenaorobei** [comment]
@qsolutions-pl @PiotrSiejczuk
Thank you for reporting. We will triage this issue with product organization and prioritize.
Hopefully you are able to use OAuth-based authentication following DevDocs with non-empty `Callback URL` and `Identity link` values.

**Comment by xmav** [comment]
DevDocs updated with examples on when to use different authorization methods: https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication.html#web-api-clients-and-authentication-methods

**Comment by lylesback2** [comment]
This is still present in Magento 2.3.5 and Magento 2.3.6.

More than 2.5 years of a known bug and it isn't fixed.

**Comment by ihor-sviziev** [comment]
Hi @lylesback2,
The issue was already solved by updating the docs:
https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication.html#web-api-clients-and-authentication-methods

**Comment by ringwood-dsg** [comment]
Seems this issue is present in 2.4 as well.

**Comment by ihor-sviziev** [comment]
Hi @ringwood-dsg,

According to https://github.com/magento/magento2/issues/13961#issuecomment-658230648 the issue was already solved by updating the docs:
https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication.html#web-api-clients-and-authentication-methods

**Comment by phpandrew** [comment]
> Seems this issue is present in 2.4 as well.

You are likely generating the key/secret and using that to try and authorize.

The flow of Magento is different from other marketplaces.

Under the store admin > System > Integrations > Add New Authorization
You need to setup the identify and callback URLs to get the consumer key/secret. 
Callback URl will be called first, authorize the user on your platform, store the posted credentials (key, secret, verifier, and store url.) you get from this and return HTTP 200 success.

The identify URI will be called next, use the credentials you captured to send a request to store_url.com/oauth/token/request
and in the same script, get your second access token and secret by posting to store_url.com/oauth/token/access

Hope this helps. Let me know if you want me to provide PHP example code.

**Comment by ringwood-dsg** [comment]
> > Seems this issue is present in 2.4 as well.
> 
> You are likely generating the key/secret and using that to try and authorize.
> 
> The flow of Magento is different from other marketplaces.
> 
> Under the store admin > System > Integrations > Add New Authorization
> You need to setup the identify and callback URLs to get the consumer key/secret.
> Callback URl will be called first, authorize the user on your platform, store the posted credentials (key, secret, verifier, and store url.) you get from this and return HTTP 200 success.
> 
> The identify URI will be called next, use the credentials you captured to send a request to store_url.com/oauth/token/request
> and in the same script, get your second access token and secret by posting to store_url.com/oauth/token/access
> 
> Hope this helps. Let me know if you want me to provide PHP example code.

Thank you for clearing this up for me. I find your explanation regarding the sequence of events a lot helpful than the official manual, to be quite honest. We're integrating our .NET application with Magento, but what I am unsure of is the parameters being passed to the Callback URL? I see the manual references it like this:

- store_base_url 
- oauth_verifier
- oauth_consumer_key
- oauth_consumer_secret

Am I correct in saying that when our callback URL is being called, that the parameters will be **named exactly** as they are referenced above? 

-

**Comment by phpandrew** [comment]
> > > Seems this issue is present in 2.4 as well.
> > 
> > 
> > You are likely generating the key/secret and using that to try and authorize.
> > The flow of Magento is different from other marketplaces.
> > Under the store admin > System > Integrations > Add New Authorization
> > You need to setup the identify and callback URLs to get the consumer key/secret.
> > Callback URl will be called first, authorize the user on your platform, store the posted credentials (key, secret, verifier, and store url.) you get from this and return HTTP 200 success.
> > The identify URI will be called next, use the credentials you captured to send a request to store_url.com/oauth/token/request
> > and in the same script, get your second access token and secret by posting to store_url.com/oauth/token/access
> > Hope this helps. Let me know if you want me to provide PHP example code.
> 
> Thank you for clearing this up for me. I find your explanation regarding the sequence of events a lot helpful than the official manual, to be quite honest. We're integrating our .NET application with Magento, but what I am unsure of is the parameters being passed to the Callback URL? I see the manual references it like this:
> 
> * store_base_url
> * oauth_verifier
> * oauth_consumer_key
> * oauth_consumer_secret
> 
> Am I correct in saying that when our callback URL is being called, that the parameters will be **named exactly** as they are referenced above?

Yes, those variables will be posted exactly as that to the callback link.
No data is posted to the indentify URL, that you will need to pull the session data / from the DB and POST that back to the magento store to the oauth/token/request, then make another POST request to the oauth/token/access url

**Comment by ringwood-dsg** [comment]
> > > > Seems this issue is present in 2.4 as well.
> > > 
> > > 
> > > You are likely generating the key/secret and using that to try and authorize.
> > > The flow of Magento is different from other marketplaces.
> > > Under the store admin > System > Integrations > Add New Authorization
> > > You need to setup the identify and callback URLs to get the consumer key/secret.
> > > Callback URl will be called first, authorize the user on your platform, store the posted credentials (key, secret, verifier, and store url.) you get from this and return HTTP 200 success.
> > > The identify URI will be called next, use the credentials you captured to send a request to store_url.com/oauth/token/request
> > > and in the same script, get your second access token and secret by posting to store_url.com/oauth/token/access
> > > Hope this helps. Let me know if you want me to provide PHP example code.
> > 
> > 
> > Thank you for clearing this up for me. I find your explanation regarding the sequence of events a lot helpful than the official manual, to be quite honest. We're integrating our .NET application with Magento, but what I am unsure of is the parameters being passed to the Callback URL? I see the manual references it like this:
> > 
> > * store_base_url
> > * oauth_verifier
> > * oauth_consumer_key
> > * oauth_consumer_secret
> > 
> > Am I correct in saying that when our callback URL is being called, that the parameters will be **named exactly** as they are referenced above?
> 
> Yes, those variables will be posted exactly as that to the callback link.
> No data is posted to the indentify URL, that you will need to pull the session data / from the DB and POST that back to the magento store to the oauth/token/request, then make another POST request to the oauth/token/access url

Thank you so much for taking the time to assist me here. I'll continue on from here and get our integration completed using your instructions. You are definitely the Magento King and my hero!

**Comment by lbajsarowicz** [comment]
I'm encountering the issues described in this Bug Report, but problem seems to be a little bit more complex:

When I'm calling simple endpoints, everything works more-less correct:
![image](https://user-images.githubusercontent.com/1639941/126291843-9dae8183-7747-4580-aa99-23caf2a21326.png)

However, the same keys used to fetch the Invoices ends up with "The signature is invalid"
![image](https://user-images.githubusercontent.com/1639941/126292067-123a3fc9-62bb-45ab-981d-71b5d52f354b.png)

But it works completely fine if you don't use SearchCriteria:
![image](https://user-images.githubusercontent.com/1639941/126292234-16ec1419-171e-484e-874a-44304b1ef617.png)

Looks like there's some mess around calculating request signature 👎🏻

**Comment by DEHAINI** [comment]
> secret

can u please gie me a clear example? i have the same issue and i can not resolve it

**Comment by shenoyaditya11** [comment]
> I found the source of my issue. Upon creating the integration and activating it, I get a consumer key, consumer secret, access token, and access token secret. So, technically, I can just skip the "Get Access Token" step of the authentication. I was able to successfully make API calls with the provided access token.
> 
> If I created the integration with an Identity link URL, then the access token and access token secret is not supplied. And when I made a request to /oauth/token/request, I got the access token and secret as a response.
> 
> If this was the intended process, then my apologies for misinterpreting the documentation.

I tried creating Integration with the Identity link, it still creates access token and token secret on activation. and before activation if I try to hit /oauth/token/request, it throws Consumer+key+expired, how to fix this issue, please help.

**Comment by qsolutions-pl** [comment]
Look at my comment here: https://github.com/magento/magento2/issues/13961#issuecomment-625284593

**Comment by jmwill86** [comment]
It's been almost 6 years since this was created, it's been marked as closed even though the issue was never actually resolved. The lack of care Magento have for their codebase is second to none.

I'd normally be happy to try and help fix things like this, but if you can't be bothered after 6 years, why should I.

**Comment by vidyasagarmukkavili-gw** [comment]
### This issue needs to be opened up again

Based on what I am seeing, there are no two steps in Magento 2 oAuth. It seems like it just simply spits out the access token and presents it in the admin rather than letting you go through the flow with something like postman. 

If you hit the endpoint `/oauth/token/request` with **consumer key** and **consumer secrett**, ideally you would expect the response to include the request key but that is not what happens and you end up with a response which says `oauth_problem=Consumer+key+has+expired`. 

So you are left with your only option which is to use the access key that has been provided in the admin. So there is no 2-legged OAuth handshake occurring here.
