### ISSUE TITLE
Products are not shown in category right after import

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1396]
Magento: ```0.74.0-beta14``` ```Default mode```
All caches are disabled.

Expected result is to see imported products shown in category page (frontend) right after successful import. In my testing, I have to toggle each product status from **Product Online** to **Product Offline** and save then toggle it back to **Product Online** again in order the product to be visible.

![capture](https://cloud.githubusercontent.com/assets/11070293/8268121/44043c8e-17a3-11e5-8101-2705fba013ee.PNG)

**Comment by kokoc** [comment]
@adzminz thank you for reporting the issue. You can use `./bin/magento indexer:reindex` CLI command as temporary workaround for this issue. Internal ticket: MAGETWO-39139

**Comment by adzminz** [comment]
Thank you, @kokoc.

**Comment by vpelipenko** [comment]
@adzminz, this issue is fixed. Could your check it? We want to be sure that it works for you.
