### ISSUE TITLE
Admin: While product which has images deleted. It's not deleting from Folder.

### ISSUE THREAD

**Issue by robert-damon** [magento/magento2#13964]
Preconditions
I'm using Magento 2 CE Version 2.1.1
Steps to reproduce
Go to Admin -> Products -> Catalog
When Product has image & if you delete from listing.
It will not delete product images from Folder.
Expected result
When product is deleted, It should delete all product images from Folder as well.
Actual result
Currently it's not deleting product Images.
Due to Image Not Deleted, there will be lots of space on server will be used.

What do I need to do?

**Comment by magento-engcom-team** [comment]
@Robert-Damon, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
> there will be lots of space on server will be used

This is not true.

I'm not sure images should really be deleted as you may re-import products using such images later.

**Comment by Ctucker9233** [comment]
@orlangur I've experienced the same issue as @Robert-Damon and while it doesn't take a lot of space it definitely uses space that could be used otherwise. If products are deleted, it must be assumed that said products will never be used again, hence the images should be removed to conserve server space.

**Comment by gelanivishal** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@vgelani thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @Robert-Damon @Ctucker9233 
On the other hand, if somebody is using this as described by @orlangur (expect that images will remain) they will have much harder time customizing it to stop images removal. 
In your case there are multitude of ways to remove unused files when you need.

Closing, as not a bug.
