### ISSUE TITLE
Price Filter in Layered Nav does not reflect Catalog Price Rule

### ISSUE THREAD

**Issue by cbend** [magento/magento2#13968]
### Preconditions

1. Magento version 2.1.11
2. Default layered navigation (no extensions)

### Steps to reproduce

1. Add products to category
2. Setup Catalog Price Rule for category
3. Make sure price is filterable (included in layered navigation)

### Expected result

1. Price filter uses sale price from Catalog Price Rule

### Actual result

1. Price filter uses original price
![image](https://user-images.githubusercontent.com/25639152/37038647-5c79f51a-2123-11e8-9e6f-72c28054857a.png)

### Product Admin
![image](https://user-images.githubusercontent.com/25639152/37038679-72296e40-2123-11e8-8a06-b6927d6e2cd0.png)

### Catalog Price Rule
![image](https://user-images.githubusercontent.com/25639152/37038711-8a414b42-2123-11e8-9d27-fbe9d74f4a7d.png)

**Comment by magento-engcom-team** [comment]
@cbend, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dhorytskyi** [comment]
Was fixed in
#https://github.com/magento/magento2/commit/56859b0c84cc41d03617800c930b937a12711e2f
