### ISSUE TITLE
Category image not display after upgrade from magento 1.9.2 to magento 2.2.1

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#13967]
After upgrade with the magento 2.2.1

When I see the category images in the back end side its fine but in the front end side its not displayed after uploaded same image again in the back end side and save the category. then,

**actual result**
but in the front end its display the category image URL like this  -> /pub/media/catalog/category//p/l/plotterpapier_afmetingen_1.jpg

and in the back end side it display 
/pub/media/catalog/category/plotterpapier_afmetingen.jpg

**expected result in the frontend side**
/pub/media/catalog/category/plotterpapier_afmetingen.jpg

Also I have checked in the pub/media/catalog/category folder there is resized folder generated but in the front end why this URL I got - /pub/media/catalog/category//p/l/plotterpapier_afmetingen_1.jpg

Please have a look.

I also run the catalog:images:resize command but that not helped

**Comment by magento-engcom-team** [comment]
Hi @jigar48. For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.
