### ISSUE TITLE
can't add product width customOptions type="file"

### ISSUE THREAD

**Issue by mrzaizai2233** [magento/magento2#13963]
### Preconditions
1. Magento 2.2.2
2. PHP 7.0.27
### Steps to reproduce

1. in admin a create a Customizable Options type File with file extentions png then i save product
2. frontend i chose product i have created then chose image type png for custome options and click Add to cart

### Expected result

1. The product should add to cart 

### Actual result

1.When i click add product to cart with custom type file i got a error:
Cannot read contents from file "C:/Users/Truong Tuan Dat/AppData/Local/Temp/C:/xampp/tmp/phpE67C.tmp" Warning!file_get_contents(C:/Users/Truong Tuan Dat/AppData/Local/Temp/C:/xampp/tmp/phpE67C.tmp): failed to open stream: Invalid argument
![image](https://user-images.githubusercontent.com/19775746/37015757-99639978-213b-11e8-947b-a848d4a51381.png)

**Comment by magento-engcom-team** [comment]
Hello @mrzaizai2233. Thanks for reporting. Please specify what operation system You have.

**Comment by mrzaizai2233** [comment]
i am running magento on:
1, Xampp v3.2.2
2, Appache 2.4
when running magento on wamp 3.1.0 64bit:
1, PHP 7.0.23
 2, Apache 2.4.27
3, Mysql 5.7.19
i had same error

**Comment by magento-engcom-team** [comment]
But  @mrzaizai2233 Your server itself runs on windows? (As we can conclude from using wamp).

**Comment by mrzaizai2233** [comment]
i am using win 7 to install wamp and xampp

**Comment by magento-engcom-team** [comment]
@mrzaizai2233, unlike Magento 1, Magento 2 does not support Windows OS (please see the documentation: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html). We were not successful trying to reproduce Your issue with Magento instance running on the supported operating system. Please reopen the issue if You are able to reproduce it using the supported operating system.

**Comment by mrzaizai2233** [comment]
i have just started with m2 , m2 not support  Windows OS but why can i still install m2 and development module ?  :dagger: :dagger: 
and can this issue fixed when i install m2 on linux or other OS ?
