### ISSUE TITLE
Why download keeps failing from magento official repository? 

### ISSUE THREAD

**Issue by jvood** [magento/magento2#13970]
### Preconditions

1. Trying to download Full Release with Sample Data using official repository https://magento.com/tech-resources/download

### Steps to reproduce
1. Go to https://magento.com/tech-resources/download
2. Select any format and click "Download" button

### Expected result
1. "Magento Open Source 2.2.3..tar.gz" file must be downloaded.

### Actual result
1. Download process keeps failing. 

Watch video: https://www.useloom.com/share/7ef185f167b2481fa9cb0e6f5d76e1b8

**Comment by magento-engcom-team** [comment]
Hello @jvood. Here is our video that demonstrates that downloading does not stuck at the step You have shown us in Your video. 
[download.zip](https://github.com/magento/magento2/files/1788068/download.zip)
Further, after filling out all the required forms the download successfully starts.
We use Chrome on Windows 10 currently accessing the site from Ukraine. So it is most likely that there are some problems at Your side.  As the GitHub issue tracker is intended for technical issues only please try to refer to some appropriate forums f.e. the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. to resolve Your issue. Thank You.
