### ISSUE TITLE
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### ISSUE THREAD

**Issue by bentintoshape** [magento/magento2#13978]
Every time I try to generate a xml product feed I get this error message

"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

Well, I tried later, and later and later.  Same error message

We are on Magento 2.2.2 and have the Mirasvit Advanced Product Feed installed.

**Comment by orlangur** [comment]
Hi @bentintoshape, this GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.
