### ISSUE TITLE
Fulltext search does not work with multiselect attribute option values 

### ISSUE THREAD

**Issue by superdav42** [magento/magento2#13972]
### Description
Create a custom product attribute with the multiselect input type. Create several options. Make the attribute searchable and shown in advanced search.
Create product with the attribute and select several values.

### Preconditions
1. Occurs with Magento 2.2.3 and any 2.2.x

### Steps to reproduce
1. From Admin, Go to _Stores - Attribute Product_. Click **Add New Product**
2. From **Catalog Input Type for Store Owner** select  **Multiple Select**
3. Add several Options under **Manage Options(Values of Your Attribute)**
4. From left ATTRIBUTE INFORMATION select Storefront Properties
5. Select **Use in Search** - _Yes_, **Visible in Advanced Search** - _Yes_. **Save Attribute**
![search](https://user-images.githubusercontent.com/51680745/71809168-2d279900-3078-11ea-948e-7b56f014f697.png)
6. Go to _Catalog - Products_ and **Add Product**
7. Click **Add Attribute** and add the previously created attribute
8. Under **Attributes** select all available options (use ctrl key) and **Save** the product 
9. Open Storefront, click **Advanced Search** 
![advanced](https://user-images.githubusercontent.com/51680745/71809789-7d532b00-3079-11ea-871a-4a5423b6c2f9.png)
10. Select an Option or several options from **Custom Product Attribute** and click **Search**
![cpa search](https://user-images.githubusercontent.com/51680745/71809993-f5b9ec00-3079-11ea-9fc0-9bca043f4335.png)

### Expected result
1. Searching by label name should be possible in the quick search or advanced search to find the associated product.

### Actual result

1. Nothing is found
![search_result](https://user-images.githubusercontent.com/51680745/71810058-239f3080-307a-11ea-85fd-d985180396a1.png)

I just opened this issue because my PR to fix it hasn't got any attention yet. https://github.com/magento/magento2/pull/13001

**Comment by magento-engcom-team** [comment]
@superdav42, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by nkajic** [comment]
This is documentation problem. 

Multiselect attributes needs to have "Visible in Advanced Search" flag checked in addition to "Use in Search" and "Search Weight" mentioned in documentation. 

After this do reindex.

Please see implementation on https://github.com/magento/magento2/blob/18dcf17c3435ae172d4b4d169c9287320b33ea38/app/code/Magento/CatalogSearch/Model/ResourceModel/Engine.php#L95

**Comment by ghost** [comment]
@nkajic how can I add these options to my attribute that I am creating programmatically? and where is the official documentation on attribute options?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30223` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by matthew99** [comment]
If it is any help this is my experience.
I use Mirasvit Elasticsearch module. In Mirasvit I can add a search index for any attribute (in my case 'writers'), which is a great feature.

My experience:
**Only first value of multiselect could be found by advanced search and layered nav**.
There is difference between /catalogsearch/results, advanced search and layered nav.

In my case I made an multi select attribute 'writers' (values writer1, writer2, writer3) .
Product 'Book1' has writer1, writer2, writer3 set in the write multiselect attribute.

When I search for 'writ' in the search box, the Miravit search autocomplete neatly lists the 3 writers and the book in seperate blocks. Clicking on any writer leads to advanced search &author=x, which means no results - EXCEPT for the first value (writer1).

If I search for 'writ' and hit enter (/calalogsearch/results/) it lists Book1 and the 3 writers. However, in the layered nav only writer1 is found. Mirasvit overrides this catalog/search but lists all three writers here as well. Clicking same result (-> advanced search only works for first writer).

If I pick advanced search:
Advanced searching on writer 2 or 3 does not list my book.
Advanced searching on writer 1 list my book.

If I click on the category with Book1 in it, in the layered navigation only Writer1 is listed - again, first value.
