### ISSUE TITLE
Magento 2.2.3 issue with paypal and term and condition

### ISSUE THREAD

**Issue by robysalv** [magento/magento2#13985]
### Preconditions

1. MAgento  version 2.3
2. Check term and condition

### Steps to reproduce

1.  agreements box checked 
2. Proceed to the paypal payment
3. 

### Expected result

1. impossibe to proceed payment with paypal  I have error
" Accept Tems and Condition before payment with paypal " but I have agrrement box checked

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@robysalv, thank you for your report.
The issue is already fixed in 2.2-develop, 2.3.0, 2.1.12

**Comment by robysalv** [comment]
Hi 
I have installed version Magento 2.2.3 and there is same issue.

Regards
Roberto
