### ISSUE TITLE
Product Collection addTaxPercents doesn't work

### ISSUE THREAD

**Issue by Pigau** [magento/magento2#13998]
### Preconditions

1. Magento 2.1.9 and 2.1.12
2. PHP 5.6

### Steps to reproduce

1. Create a product collection
2. Use addTaxPercent
3. Try to get tax percent on product

```php
$collection = $this->productCollectionFactory->create();
$collection->addTaxPercents();
$product = $collection->getFirstItem();
$taxRate = $product->getTaxPercent();
```

### Expected result

1.  $taxRate should contain the tax rate of the product

### Actual result

1.  $taxRate is empty

In `Magento/Catalog/Model/ResourceModel/Product/Collection.php`,
the method `addTaxPercents` only set the value of `_addTaxPercents` flag to true.
This flag in only used in `requireTaxPercent` method which in not used any where.
Am I missing something ?

**Comment by magento-engcom-team** [comment]
@Pigau, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by AnshuMishra17** [comment]
This doesn't seems to be a bug because `addTaxPercents()` function just set the flag `$this->_addTaxPercents` to `true`.
Tax Rates are calculated for quote items and not for products. A product becomes a quote item when it is added to the cart (quote) and during this process tax rate is added to the individual quote item.
Tax Percents can be fetched for quote items and not for products.

**Comment by magento-engcom-team** [comment]
@Pigau, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
