### ISSUE TITLE
Cache invalidates after a while also when product or category edit is done.

### ISSUE THREAD

**Issue by KooTjoo** [magento/magento2#13996]
### Preconditions

1. Magento 2.2.3 
2. PHP 7.1
3. Plesk with Varnish 4.0 Docker
4. Running in Developer Mode (but also tested in Production)

### Steps to reproduce
1. Activate Varnish or use Internal Page cache (result the same). 
2. Warm the Cache
3. Check if CMS Pages, Category Pages and Product Pages are warmed.

### Expected result
1.  Cached pages shoukd stay warmed at least for few hours/a day depending on TTL that has been set.
2. Weh editing a product or category cache should not get flushed.

### Actual result
1. After edit (product, category) all cache is gone.
2. After little while at about 30 minutes cache is invalidated.

I have tried all kinds of solutions but no luck.

Can this be a setup issue? Or is there a proper way to check this. When cache is there site is super fast.

**Comment by misha-kotov** [comment]
> Expected Result: When editing a product or category cache should not get flushed.

This is not the case. According to our [Varnish documentation](http://devdocs.magento.com/guides/v2.2/config-guide/varnish/use-varnish-cache.html): 
The following actions can result in a Varnish purge:
- Maintaining a store (for example, adding or editing categories, prices, products, and promotional pricing rules). Varnish is purged automatically when you perform any of these tasks.

**Comment by KooTjoo** [comment]
@misha-kotov but this is strange, why not only recreate cache for product that has been edited, and why flush all te cache? If I edit a product my cms pages also get flushed. Really strange behavior that makes Magento almost unusable. I didn't have this with Magento 1.

**Comment by KooTjoo** [comment]
Isn't there a good way to troubleshoot these cache issues. We see a lot of people complaining about it. How do I disable all triggers that flush the cache to see if cach then persists.

**Comment by magento-engcom-team** [comment]
@KooTjoo, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hi @KooTjoo. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/66

**Comment by rparsi-boxycharm** [comment]
@misha-kotov Hi, in my project we're using magento 2.3.3. We're seeing this strange issue:
Submitting a product review triggers varnish cache purge.

Why does this happen and where in magento code is this logic?
