### ISSUE TITLE
Product Import - Failing to import correct SKU from CSV

### ISSUE THREAD

**Issue by michelve** [magento/magento2#13999]
Installed magento version: 2.2.3

### Steps to reproduce
1. Importing products using a csv file
sample csv
`sku,name,description,weight,visibility,is_in_stock,price,condition,product_type,categories,attribute_set_code,product_websites,qty,url_key,additional_attributes,base_image,small_image,thumbnail_image,additional_images
CT12EN001853094,Odd-Eyes Pendulum Dragon - CT12-EN001 - Platinum Secret Rare - Limited Edition,"<p class=""description""><b>Card Rules</b>: <br><b>Passcode</b>: 16178681<br><b>Set</b>: 2015 Mega-Tin<br><b>ATK/DEF</b>: 2500/2000<br><b>Card Number</b>: CT12-EN001<br><b>Monster Type</b>: Dragon<br><b>Rarity</b>: Platinum Secret Rare<br><b>Attribute</b>: Dark<br><b>Card Text</b>: Pendulum EffectYou can reduce the battle damage you take from an attack involving a Pendulum Monster you control to 0. During your End Phase: You can destroy this card, and if you do add 1 Pendulum Monster with 1500 or less ATK from your Deck to your hand. You can only use each Pendulum Effect of ""Odd-Eyes Pendulum Dragon"" once per turn.Monster EffectIf this card battles an opponent's monster, any battle damage this card inflicts to your opponent is doubled.<br><b>Level</b>: 7<br><b>Card Type</b>: Pendulum Effect Monster<br><b>Name</b>: Odd-Eyes Pendulum Dragon<br><b>Edition</b>: Limited<br><b>CUSTOM LABEL</b>: <br><b>Pendulum Scale</b>: 7<br></p>Extra Info<p class=""description""><em>No description for this product.</em></p>",0.0069444,"Catalog, Search",1,1,Near Mint,simple,Default Category/Yu-Gi-Oh! Singles/Promo Single Cards/2015 Mega Tin Exclusives,Default,base,65,odd-eyes-pendulum-dragon-ct12-en001-platinum-secret-rare-limited-edition-ct12-en001-853094,"card_rules=,passcode=16178681,set=2015 Mega-Tin,atk_def=2500/2000,card_number=CT12-EN001,monster_type=Dragon,rarity=Platinum Secret Rare,attribute=Dark,card_text=Pendulum EffectYou can reduce the battle damage you take from an attack involving a Pendulum Monster you control to 0. During your End Phase: You can destroy this card, and if you do, add 1 Pendulum Monster with 1500 or less ATK from your Deck to your hand. You can only use each Pendulum Effect of ""Odd-Eyes Pendulum Dragon"" once per turn.Monster EffectIf this card battles an opponent's monster, any battle damage this card inflicts to your opponent is doubled.,Level=7,card_type=Pendulum Effect Monster,card_name=Odd-Eyes Pendulum Dragon,edition=Limited,custom_label=,pendulum_scale=7,condition=Near Mint,SKU=CT12-EN001",assets/OddEyesPendulumDragon-CT12-EN-PlScR-LE.png,assets/OddEyesPendulumDragon-CT12-EN-PlScR-LE.png,assets/OddEyesPendulumDragon-CT12-EN-PlScR-LE.png,assets/OddEyesPendulumDragon-CT12-EN-PlScR-LE.png`

2. where sku is CT12EN001853094
3. after import sku becomes CT12-EN001

### Expected result
![expected](https://user-images.githubusercontent.com/4137743/37098890-0aa29e70-21ed-11e8-954f-2cb38ec4fd4d.png)
shows correct sku

### Actual result
![result](https://user-images.githubusercontent.com/4137743/37098675-796eaffc-21ec-11e8-90ed-6e2f4798ee76.png)
sku is trimemd

**Comment by michelve** [comment]
Update: even when i enter a product sku it gets switch to the sku on the title.

**Comment by magento-engcom-team** [comment]
@michelve , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dthivanka** [comment]
@michelve @magento-engcom-team 
This is not a issue in Magento import export. In your import CSV there is another attribute as 
SKU=CT12-EN001 in additional_attributes column. Import export process replaces your original SKU with it. You need to remove it from additional_attributes column. 

Maybe Magento can throw an validation error in this scenario.

**Comment by alexandrosk** [comment]
@dthivanka I agree this is not an issue.

**Comment by sdzhepa** [comment]
Hello @michelve 

As we can see from https://github.com/magento/magento2/issues/13999#issuecomment-389071826 and https://github.com/magento/magento2/issues/13999#issuecomment-425121477 this is not an issue.
It is related to CSV data file preparation

This ticket can be closed.
Please, feel free to reopen or create a new one with additional details/instructions if issue still exists or was not fully fixed

Thank you for feedback and collaboration
