### ISSUE TITLE
Display Messages on other pages simultaneously

### ISSUE THREAD

**Issue by raviozainfo** [magento/magento2#13997]
### Preconditions
1. Magento ver. 2.1.6
2. PHP ver. 7.0.27
3. MySql ver.5.6.39

### Steps to reproduce
1. Open Product edit page and any other grid or other page like Low stock Report in different Tabs.
2. Edit product with any options or click on 'Save' button after ajax effect done.(At a time of page refresh)
3. Refresh Stock Report page (other page that you opened). you can See the message on Top 'You saved the product.'

### Expected result
1. Need to Display this success message only on that page don't effect on any other pages.

### Actual result

1. Display success or any other  messages (based on session) on all Pages. 
Edit Product and Refresh other tab page at time of refresh

![screenshot--2018 03 07-18-27-28](https://user-images.githubusercontent.com/34629055/37093568-ca220734-2235-11e8-9865-bf7d849b37a6.png)

After Refreshing other page Message come here

![screenshot-192 168 0 5-2018 03 07-18-25-14](https://user-images.githubusercontent.com/34629055/37093600-e95851c6-2235-11e8-8583-be1b8a0fe743.png)

**Comment by magento-engcom-team** [comment]
@raviozainfo , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by raviozainfo** [comment]
Hi, I have also try in Magento ver. 2.2.2.
You need to refresh another page (suppose  in example - Low stock report) -  page at a same time of product page reload (After ajax effect done). Try in same browser and different Tabs.

**Comment by magento-engcom-team** [comment]
@raviozainfo , thanks for you update but we not  reproduce this issue.
![product_page](https://user-images.githubusercontent.com/31669971/37212263-38a714ba-23b7-11e8-8b5b-37c8bee3800a.png)

![product_save](https://user-images.githubusercontent.com/31669971/37212279-420771bc-23b7-11e8-9d8b-9020d3c801e1.png)

![product_low](https://user-images.githubusercontent.com/31669971/37212303-54cfb5ca-23b7-11e8-9dab-5ce3af1db214.png)

Message is not duplicated on another page after refresh.

**Comment by magento-engcom-team** [comment]
@raviozainfo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
