### ISSUE TITLE
PayPal PLUS integration

### ISSUE THREAD

**Issue by mgns** [magento/magento2#1400]
PayPal offers a "new" service called PayPal PLUS, that combines multiple payment solutions. Nothing can be found about integration into Magento. So far only OXID supports this service [https://www.paypal-viewpoints.com/paypal-plus-integration].

Integration guidelines can be found here:
https://www.paypalobjects.com/webstatic/de_DE/downloads/PayPal-PLUS-IntegrationGuide.pdf

**Comment by asemenenko** [comment]
Hi @mgns 

We keeping an eye on a new PayPal offerings, including PayPal Plus.

/regards
