### ISSUE TITLE
When grid filter is applied filter icon need to show different way if any filter is applied.

### ISSUE THREAD

**Issue by himanshu8dev** [magento/magento2#14004]
Recently i have stuck in one problem which is ui point of view need to imporvement. 

Problem :+1: 
I have applied filter in my grid around two week ago & today i need to check that grid log. but i don't find any records due to that filter. so i have checked into tables values, re-rewrite ui_component grid xml. because i forgot that my grid filter is applied since two weeks ago. after spending too much time i ask my colleague and we found that filter already applied with some other text. so there is not any indicator in filter icon that is filter is being used or not.

this is not in general issue but i think it should be implement for user point of view.

**Comment by magento-engcom-team** [comment]
Hi @himanshu8 
Thank you for your reporting.
Can you describe steps to reproduce the issue?

**Comment by himanshu8dev** [comment]
• Go to any listing(Grid)page which have filter option enable.
• now applied any filter.
• refresh the page
• on both time filter icon is shown same.
• there is not any indicator which is show that filter is applied so here user can be confused if they visit after 1 or 2 weeks.

**Comment by magento-engcom-team** [comment]
@himanshu8 we can not reproduce this issue.
Tell me, please, which magento version do you use and which grid do you mean?
Thanks

**Comment by himanshu8dev** [comment]
![gridfilter](https://user-images.githubusercontent.com/8557306/37240520-789c1d7a-2472-11e8-9a65-c5007fec28d2.PNG)

Please check this screenshot. 
on grid page ay kind of filter is applied then filter icon must be indicate by icon or color that filter is applied.

**Comment by magento-engcom-team** [comment]
Hi @himanshu8 
If you have applied grid filter in admin than you can show row status filter:
![screenshot_1](https://user-images.githubusercontent.com/31669971/37273600-ffe9538a-25e2-11e8-8c13-66ee72ce91b3.png)

**Comment by magento-engcom-team** [comment]
@himanshu8 If the issue is not actual close it please

**Comment by himanshu8dev** [comment]
Ya it's there!, Thank so you for your time.
Really appreciated!!.

**Comment by magento-engcom-team** [comment]
@himanshu8, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
