### ISSUE TITLE
Address not showing after upgrade from Magento EE 2.1.8 > Magento 2.2.2

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#14008]
**Preconditions**
PHP 7.0.20
MYSQL 5.7
Magento 2.1.8 . Magento 2.2.2

**Steps to reproduce**
Upgrade from Magento 2.1.8 to Magento 2.2.2
Go to Sales > Order  > View or any other place where Customer Address is shown

**Expected result**
**Actual Results**

See print-screens. I've attached working behavior in 2.18 and result in 2.2.2

I must mention that I have done a data-migration from 1.12.0.2 to 2.1.8 .
There is no output in web console or in var/log
I've seen related issues. Have not found a fix to work for me.

![order-view-issues](https://user-images.githubusercontent.com/25669334/37152744-085e03d8-22e3-11e8-92c9-0a9d3a00fa15.png)
![order-view-success](https://user-images.githubusercontent.com/25669334/37152745-0880454c-22e3-11e8-857a-97fac07df434.png)

**Comment by victortodoran** [comment]
I managed to fix this by upgrading to Magento 2.2.2 first and re-runing the migration. As we are still in development, this was possible. If we would've gone live though I think we would've had a real problem on our hands.

**Comment by magento-engcom-team** [comment]
@victortodoran, thank you for report. However, problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.
