### ISSUE TITLE
I can't upload image and create directory in admin pages. 

### ISSUE THREAD

**Issue by shater1990** [magento/magento2#14002]
### Preconditions

1. Magento 2.2.3
2. MySQL 5.7
3. Bitnami
4. php 7.0.27
5. Google cloud server

### Steps to reproduce

1.  Click  Add Block in Content->block page
2.  Insert Image on content edit window.
3. Create directory or upload image

### Expected result

After setup magento 2.2.3 by bitnami in goolgecloud server, I installed magento 2.2 sample data follow this url(http://devdocs.magento.com/guides/v2.2/install-gde/install/sample-data-after-clone.html)
And I did set some permission of var, root folder and files.
After this time, I had this problem.
1. I have this message
    Directory "/opt/bitnami/apps/magento/htdocs/pub/media/wysiwyg/homesilder" cannot be created Warning!mkdir(): Permission denied
2. Destination folder is not writable or does not exists.

### Actual result

1. 
![image](https://user-images.githubusercontent.com/36569777/37130944-4a70bc76-22c9-11e8-994e-dedce055ef6b.png)
2.
![image](https://user-images.githubusercontent.com/36569777/37130967-72c5f31c-22c9-11e8-9a1b-a42b9298b4c6.png)
3. And I can't see image files
![image](https://user-images.githubusercontent.com/36569777/37130992-934392ac-22c9-11e8-82f1-64fa75670dc5.png)

Please help me

**Comment by magento-engcom-team** [comment]
@shater1990 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
![img_block1](https://user-images.githubusercontent.com/31669971/37210844-c26fa96e-23b2-11e8-8dba-610b81dfba41.png)

![img_block2](https://user-images.githubusercontent.com/31669971/37210858-cb1127aa-23b2-11e8-8a18-45cf1a5e1803.png)

**Comment by shater1990** [comment]
Hello. Thanks for your response.
After setup magento 2.2.3 by bitnami in goolgecloud server, I installed magento 2.2 sample data  follow this url(http://devdocs.magento.com/guides/v2.2/install-gde/install/sample-data-after-clone.html)
And I did set some permission of var, root folder and files. 
After this time, I had this problem.
Please help me.

**Comment by magento-engcom-team** [comment]
@shater1990 , thanks for your update. We cannot reproduce the issue with sample data too.
![img_block_sample_data](https://user-images.githubusercontent.com/31669971/37281010-33b1ce44-25f8-11e8-9322-df466857f13d.png)

![img_block_sample_data2](https://user-images.githubusercontent.com/31669971/37281020-3ad06d3e-25f8-11e8-8b7b-ebdcc5d4c418.png)

We think you issue is related for you server configurations and permission.

**Comment by shater1990** [comment]
Hello. 
I did set permission about var and pub folder. 
![image](https://user-images.githubusercontent.com/36569777/37281578-e1c1cc8c-2634-11e8-8ffa-925a1d79fa6f.png)
![image](https://user-images.githubusercontent.com/36569777/37281617-0249480e-2635-11e8-9f00-b7bd7d7e74ab.png)

But it don't work. my server configurations is default.

So I did update some code of di.xml and App/Filesystem/DirectoryResolver.php  follow this url (https://github.com/magento/magento2/issues/13929)
But it don't work too. 

![image](https://user-images.githubusercontent.com/36569777/37281778-882dd8c2-2635-11e8-8a5f-616c50ebdb48.png)
Please help me again.

**Comment by magento-engcom-team** [comment]
@shater1990, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
