### ISSUE TITLE
Export data from grid not adding custom rendered data magento2

### ISSUE THREAD

**Issue by balwant20** [magento/magento2#14014]
*Preconditions:*
1. Magento 2.1.7
2. With needed prerequisites.

*Steps to reproduce*
1. login to admin panel.
2. Go to order grid panel, and click on export button to export details in CSV format.

*Expected result*
1. in CSV, my custom columns(which i got from prepareDataSource function) values should be displayed as in sales order  grid.

*Actual result*
1. Not displaying and value in my custom columns of CSV. 
2. it just gives a blank value.
exporting not adding the values which are rendered by prepareDataSource function(ui/component/listing classes).

*Here is my code:*
1. PHP file
public function prepareDataSource(array $dataSource)
    {
		try {
			$ok_to_ship='';
			if (isset($dataSource['data']['items'])) {
				foreach ($dataSource['data']['items'] as & $item) 
				{
					$id     = $item['entity_id'];
					$order  = $this->_orderRepository->get($id);
					$status = $order->getStatus();
					
					if($order->hasInvoices() ||$status == 'ok_to_ship' || $status == 'complete') {
						$ok_to_ship='Yes';
					}
					else if($status == 'cancel_to_ship')
					{
						$ok_to_ship='Cancel';
					}
					else /* if($status == 'not_ok_to_ship') */ 
					{
					    $ok_to_ship='No';
					}
					$item['ok_to_ship']=$ok_to_ship;
				}
				
			}
		} catch (\Exception $e) {
			
		}
			
        return $dataSource;
        
    }
2. XML file
<column name="ok_to_ship" class="Angara\Easypay\Ui\Component\Listing\Columns\OkToShip">
			<argument name="data" xsi:type="array">
				<item name="config" xsi:type="array">
					<item name="visible" xsi:type="boolean">true</item>
					<item name="sortable" xsi:type="boolean">false</item>
					<item name="label" xsi:type="string" translate="true">OK TO SHIP</item>
					<item name="sortOrder" xsi:type="number">45</item>
				</item>
			</argument>
</column>

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

> in CSV, my custom columns(which i got from `prepareDataSource` function) values should be displayed as in sales order grid.

Such expectation is wrong. You need to implement customization in order to make it work this way.
