### ISSUE TITLE
Cannot install : Module 'Magento_Customer': Integrity constraint violation

### ISSUE THREAD

**Issue by flakerimi** [magento/magento2#1401]
I tried with web and cli, both stops there at 69%

Module 'Magento_Customer':
Installing data.. 
[ERROR] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'' in /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `cu...', Array)
#5 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(431): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `cu...', Array)
#6 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(486): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `cu...', Array)
#7 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `cu...', Array)
#8 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1759): Zend_Db_Adapter_Abstract->insert('customer_group', Array)
#9 /Users/flakerimi/Sites/magento2/app/code/Magento/Customer/Setup/InstallData.php(51): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('customer_group', Array)
#10 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Model/Installer.php(761): Magento\Customer\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#11 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Model/Installer.php(709): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#12 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#13 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Model/Installer.php(298): call_user_func_array(Array, Array)
#14 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#15 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#22 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#23 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /Users/flakerimi/Sites/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#26 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY', query was: INSERT INTO `customer_group` (`customer_group_id`, `customer_group_code`, `tax_class_id`) VALUES (?, ?, ?)' in /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `cu...', Array)
#4 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(431): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `cu...', Array)
#5 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(486): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `cu...', Array)
#6 /Users/flakerimi/Sites/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `cu...', Array)
#7 /Users/flakerimi/Sites/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1759): Zend_Db_Adapter_Abstract->insert('customer_group', Array)
#8 /Users/flakerimi/Sites/magento2/app/code/Magento/Customer/Setup/InstallData.php(51): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('customer_group', Array)
#9 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Model/Installer.php(761): Magento\Customer\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#10 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Model/Installer.php(709): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#11 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#12 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Model/Installer.php(298): call_user_func_array(Array, Array)
#13 /Users/flakerimi/Sites/magento2/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#14 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /Users/flakerimi/Sites/magento2/vendor/zendframework/zend-mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /Users/flakerimi/Sites/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#25 {main}

**Comment by rganin** [comment]
Issue should have been fixed in version 0.74.0-beta15.

**Comment by vpelipenko** [comment]
@flakerimi, could you verify this issue on the latest Magento version?

**Comment by flakerimi** [comment]
It is fixed, good job.
