### ISSUE TITLE
2.2 - Admin will not create shipment from the invoice create screen if credit card was used

### ISSUE THREAD

**Issue by mzenner1** [magento/magento2#14012]
I'm using Magento 2.2.3 and seeing an issue where if an order was made with a credit card (authorize.net), when I go to the admin to create an invoice and check the "Create Shipment" box it will have a success message, create the invoice properly, but no shipment will be created.  

This only happens if a credit card is used.  If I make another order using Purchase Order as the payment type, the shipment will be created successfully via the invoice creation screen.
### Precondition
Magento 2.2.x or 2.3.x 
### Steps to reproduce
1. Enable authorize.net
2. Purchase a product with a credit card
3. Go to the admin->sales->orders section
4. Invoice the order
5. Check the "Create Shipment" button
6. Submit the invoice

### Expected result

1. Both an invoice AND a shipment should have been created

### Actual result
1. Only an invoice gets created, the shipment does not

I am seeing this error in the exception log at the time of invoice creation

[2018-03-08 13:55:30] main.CRITICAL: Unable to get transaction details. Try again later. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Unable to get transaction details. Try again later. at /vendor/magento/module-authorizenet/Model/TransactionService.php:135)"} []

**Comment by magento-engcom-team** [comment]
@mzenner1 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![order_a](https://user-images.githubusercontent.com/31669971/37276056-6c91cf0c-25e9-11e8-8753-b83267b93a5d.png)

**Comment by mzenner1** [comment]
I am able to replicate this on a blank 2.2.3 install.  I see the success message in your screenshot above.  I too am getting that same success message (that both items were created).  However, if you actually go to Sales->Shipments, was that shipment really created?  For me it is not.

**Comment by magento-engcom-team** [comment]
@mzenner1, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vishalverma279. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vishalverma279, here is your [Magento instance](https://i-14012-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14012-2-3-develop.instances.magento-community.engineering/admin](https://i-14012-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @mzenner1. Thank you for your report. 
The issue has been fixed in magento/magento2#24494 by @vishalverma279 in 2.3-develop branch
Related commit(s):
 - [529e19d3e5a25c28acfd5f37799cc9558617e624](https://github.com/magento/magento2/commit/529e19d3e5a25c28acfd5f37799cc9558617e624)

The fix will be available with the upcoming 2.3.4 release.
