### ISSUE TITLE
installing theme but does nor work

### ISSUE THREAD

**Issue by dorian90** [magento/magento2#14023]
Hi
I'm trying to install a theme

. On their website it says that it is compatible with 2.2 and I have magento 2.2.3 will it work? Siden jeg har installeret det er det 50% er bare installert. Jeg har gjort som foreskrevet ved å laste opp dokumentene / filene i mappen for filhåndtering, men det ser ikke ut som dette: / Have I done something wrong?
I have taken "freego-theme-magento-2.2.patch" and put it in the "freego theme" folder, then you have taken "freego theme" and transferred the file through file manager to magento folders and subfolders. I have sent a zip file with files on Google Drive

Your installation instructions
Overview Installation
Installation ProcessInstallation Process
1) Unzip files in your Magento root directory. It does with it all the files I have attached
2) Run under command Instead, it does it through file manager
- Open a terminal
- Run command "bin / magento setup: upgrade" in magento root directory
3) Choose FreeGo Theme I do too
- Go to 'Stores -> Configuration -> General -> Design -> Design Theme -> Select Solwin FreeGo' theme.
- Save configuration and Clear Cache.
4) Configure FreeGo Theme It is not in Magento
- Go to 'Theme cpanel -> Configuration'
- Select all other options like header, footer, product list / watch page, contact us according to your requirements.
- Save configuration and Clear Cache.
Link to Theme as it should look

http://magedemo.solwininfotech.com/magento2/freego/theme/

Link to installation
https://www.solwininfotech.com/product/magento-2-themes/freego-responsive-theme-magento-2/

Link to my page:

http: //draw.nu

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.
