### ISSUE TITLE
Magento 2. Data Migration creates new attributes sets for default magento attribute sets

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#14027]
**Preconditions**
PHP 7.0.20
MYSQL 5.7
Magento 1.12.0.2 EE >data-migration> Magento 2.2.2 || Magento 2.18 CE

**Steps to reproduce**
Migrate data using data-migration-tool for above mentioned versions 

**Expected result**

Attribute set with given attribute_set_id,entity_type_id, attribute_set_name combination(from source) to map to existing destination attribute_set.
To be more explicit I expect that default Magento 1 attribute_sets to simply map to default Magento 2 attribute sets and not duplicate.

**Actual Result**
Default Magento attribute_sets are duplicated and Magento 1 attribute sets take the existing Magento 2 attribute_set_ids.

I'm not sure if this a bug or a feature.
If this is a feature what is the reason behind it?
What am I supposed to do with the duplicated attribute_sets
Migration_Default attribute sets take Magento 2 default attribute set ids so removing them is not an option as Magento 2 hardcodes attribute_set_ids in core code.

![export](https://user-images.githubusercontent.com/25669334/37207387-6e075ed8-23a5-11e8-903e-c9509ed072f1.png)

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.
