### ISSUE TITLE
oAuth in magento 2

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#1402]
Hello,

So I started to look at adding oAuth implementations into Magento 2 using twitter ..... Thankfully I found that you are using `"lusitanian/oauth": "~0.3"` so I feel this is a good choice supports both V1 and V2. However in composer Magento have this under the `require-dev` meaning in theory this is a project dependency that will never make it into production. Is there a reason for having this only required for dev or can this be moved into the global `require` block ? Or should oAuth not be opinionated within Magento 2 and therefore its used for some testing on M2 and a reason for never being on production.

**Comment by anupdugar** [comment]
@jamescowie Thanks for rcomment.
lusitanian/oauth is primarily used as an Oauth client to verify Magento's Oauth 1.0a server implementation and REST API request signing. The only usages for now are the functional tests for REST APIs using this library to make authenticated requests - hence the require-dev.
Here's the usage as a client for Oauth 1 handshake  : https://gist.github.com/anupdugar/2870f28a5c108cc43df9
Definitely, if there is a need for an Oauth client outside tests, it can be included as a required dependency.
Hope this helps. Let us know if you have further questions.

**Comment by snohe** [comment]
@jamescowie, since we haven't heard back from you regarding this question, we'll go ahead and close this.  In case you do have any questions, please don't hesitate to let us know.
