### ISSUE TITLE
Magento 2.2.3 backend catalog was missing

### ISSUE THREAD

**Issue by evodus** [magento/magento2#14036]
### Preconditions

1. Magento 2.2.3
2. php 7.1
3. MariaDB 10.2.13

### Steps to reproduce

1. Fresh install with composer (using this docs http://devdocs.magento.com/guides/v2.2/install-gde/prereq/integrator_install_ce.html)
2. cron:install, cron:run

### Expected result

1.  at the admin page Stores -> Configuration -> Catalog -> catalog - not have any settings

### Actual result

1. ![screen shot 2018-03-09 at 17 23 24](https://user-images.githubusercontent.com/36575297/37214746-9cdecb1a-23be-11e8-98bc-5cf519888471.png)

**Comment by magento-engcom-team** [comment]
@evodus, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.
