### ISSUE TITLE
Cart rules with only free shipping are not registered as used.

### ISSUE THREAD

**Issue by bydrei** [magento/magento2#14039]
Lets assume we create bulk coupon cart rules coupon codes with no price discount and only use it to get the customer free shipping. 
Also lets assume this has been fixed https://github.com/magento/magento2/commit/6637cde86f1d9ed63dbf968e0e42d3b431117075 ... The customer will be able to use the coupon for free shipping but it will not register in magento as used.

### Preconditions

1. Magento 2.1.12
2. PHP 7.0.27
3. MySQL 5.7.21

### Steps to reproduce

**Rule Information**
1. Create new price cart rule
2. Set coupon to`auto`
3. Set uses per customer to `1`
4. Priority to `0`

**Actions**
1. Set Apply `Percent of product price discount`
2. Set Maximum Qty Discount is applied to `0`
3. Set Discount Qty Step (Buy X) to `0`
4. Set Apply to Shipping Amount to `yes`
5. Set  Discard subsequent rules to `yes`
6. Set Free Shipping to `For matching items only`

**Manage Coupon Codes**
1. Generate 1 coupon code
2. Use it

### Expected result

1. Coupon code should appear to the customer as it is being used.
2. After successfully checkout coupon should be set as used.

### Actual result

1. Coupon is not shown to the customer as being used.
2. After checkout it is not set as used in the backend.

If you do however set the discount amount to greater than 0, all the above will work.

**Comment by magento-engcom-team** [comment]
@ferrazzuk, thank you for your report.
The issue is already fixed in 2.2.3, 2.3.0

**Comment by bydrei** [comment]
@magento-engcom-team can you point me to the fix? So I can apply to the current version we have.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Please provide the commits that fix this issue.
