### ISSUE TITLE
Admin menu "sticks" on Dashboard, even when other options are chosen

### ISSUE THREAD

**Issue by specshack** [magento/magento2#1403]
This is best shown with a picture:

![clip_2](https://cloud.githubusercontent.com/assets/5779763/8310453/9b726a9c-1995-11e5-838a-e67fcdc97715.png)

This photo shows the Products detail after that option was selected, but the Dashboard option shows that it is still selected.

Other examples:

![clip_1](https://cloud.githubusercontent.com/assets/5779763/8310553/4bc9ef14-1996-11e5-8e34-c80dcfee0e81.png)

**Comment by villageseo** [comment]
Hi @specshack

I'm trying to reproduce the case. Could you give please some steps to reproduce.

For now I can't get the issue. Please see my screenshot.

![dashboard](https://cloud.githubusercontent.com/assets/2562553/8311874/fecd5fc4-19e1-11e5-9647-025b972b0680.jpg)
 
Kind Regards,
Oleg

**Comment by specshack** [comment]
It happens immediately upon logging into the admin area. The dashboard opens as expected. All other area can be opened but the menu pointer sticks on dashboard as shown on the screenshots I provided. I did not see this issue in previous 

Dave
Specshack.com

**Comment by buskamuza** [comment]
@specshack , what version of Magento do you use? Did it happen right after installation?
Do you see any JS errors in the browser console?

**Comment by specshack** [comment]
Using current version, beta14. I noticed it right after installation, and it has also persisted through several reboots too. No JS error in the browser console. (No errors of any kind actually)

**Comment by buskamuza** [comment]
@specshack , thanks for the info.
1. Could you, please, provide phpinfo? Can't find if you've already posted it in some other ticket.
2. Do you have same URLs for the web-site and static view files? Or any other custom settings in Magento configuration?
3. Did you try cleaning cookies and any other browser data?
