### ISSUE TITLE
You need to choose options for your item.

### ISSUE THREAD

**Issue by sudaifhaider** [magento/magento2#14046]
unable to add the product to cart with customizable options

Preconditions
choose phone model upload file and add to cart

it should get added to the cart
file should get upload
Steps to reproduce
Create a configurable product with dropdown option for phone model.
in Customizable option, choose file in option type, and required and price type as fixed save the product.

Expected result
should get added to cart
Actual result
when added to the cart it gives "You need to choose options for your item"

I am using Magento version 2.2.3

**Comment by magento-engcom-team** [comment]
@sudaifhaider , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![config_choose](https://user-images.githubusercontent.com/31669971/37340332-7548035e-26c6-11e8-926c-9737181e6bda.png)

![conf_add](https://user-images.githubusercontent.com/31669971/37340387-9be1fc04-26c6-11e8-8383-2929a96df10d.png)

![conf_in_cart](https://user-images.githubusercontent.com/31669971/37340348-803c9338-26c6-11e8-9a7d-9e78d707aafa.png)

**Comment by sudaifhaider** [comment]
Is there any settings required as I believe I am on version 2.2.3 the latest one. 
I am facing this issue with all my products with apparels size swatches also. Please let me know if any product attribute or any other part needs some different settings.

Thanks in advance.

**Comment by magento-engcom-team** [comment]
@sudaifhaider , thanks for your response and please check this issue on clean installation without any third party modules or extensions if you have. Screenshots or logs helps too.

**Comment by sudaifhaider** [comment]
Thanks for your response. Now I am getting some different error.

I created one simple product added customizable options.
1. file
2. radio buttons.

But while uploading file and adding the product i get below error:
Cannot read contents from file "/tmp/opt/bitnami/php/tmp/phpycj8my" Warning!file_get_contents(/tmp/opt/bitnami/php/tmp/phpycj8my): failed to open stream: No such file or directory
below is the screenshot.

![image](https://user-images.githubusercontent.com/24977341/37559620-1c9e10cc-2a4f-11e8-87df-50df4a974d76.png)

**Comment by magento-engcom-team** [comment]
@sudaifhaider , thanks for your update. We not reproduced this issue on fresh installation. Please tried to reproduced on fresh installation without any third party code.

**Comment by jonasemde** [comment]
@magento-engcom-team : We experience the same issue on configurable products on a blank magento luma system.

**Given:**
- Fresh Magento 2.2.2 or 2.2.3 installation
- Added product attribute "Size" as a "Text Swatch" with three options S, L, XL
- Add attribute options for colors: black, white
- Add a configurable product with size/color variants for S-black, L-black, XL-black, S-white, L-white, XL-white
- Activate all variants and set the stock to 100 except the white XL this variant is set to stock 0 and is out of stock

**Expected result:**
- The none available variant white-XL should be disabled and not selectable

**Current result:**
- The none available variant white-XL is selectable and is not disabled
- After selection and clicking on the "Add to cart"-button the message: "You need to choose options for your item." appears

**Animation:**
![marz-29-2018 13-08-57](https://user-images.githubusercontent.com/5083193/38087290-e158b35c-3357-11e8-91ce-94140a4339da.gif)

**Comment by magento-engcom-team** [comment]
@jonasemde , thanks for you report. This is problem is already fixed on 2.3.0

![conf_text_swatch](https://user-images.githubusercontent.com/31669971/38136518-a6421396-3427-11e8-92a9-9383a08e0791.png)

**Comment by magento-engcom-team** [comment]
@sudaifhaider, thank you for your report.
The issue is already fixed in 2.3.0
But we will consider to backport the fix to patch releases

**Comment by sl02** [comment]
+1 for patching 2.2
Will not be in a position to update to 2.3 for quite some time still...

**Comment by pablobae** [comment]
Waiting for patching 2.2..

**Comment by drbservices** [comment]
Hi, can somebody please include a link to the commit for the fix in 2.3.0?
Thank you very much

**Comment by webalexstudio** [comment]
Is there any info about patch of this problem for 2.2.x versions ?

**Comment by drbservices** [comment]
Any update please? this is really a big issue, not possible to add products to basket, 
would really appreciate some help here, especially that this was already fixed - just its impossible to find the relevant commit without some guideance
Many Thanks

**Comment by pilr** [comment]
looking for patch as well for 2.2.x versions

**Comment by pilr** [comment]
I also have the same issue. always got "You need to choose options for your item." when adding configurable products to cart. Im sure i have select all required options. 

Magento ver. 2.2.4

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @sudaifhaider  The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by drbservices** [comment]
@engcom-backlog-nazar Thank you very much for the update on this one, but can you please send a link to the commit that fixes this issue on 2.3 release branch? Just so we can implement the fix on our production environment while the 2.3 is not officially released?

**Comment by ghost** [comment]
@sudaifhaider this was fixed by the core team, so i'm not able to share with commit.
