### ISSUE TITLE
Catalog - Product list - Toolbar action block override not working

### ISSUE THREAD

**Issue by cshaw-inviqa** [magento/magento2#1404]
Hi,

Trying to override the layout on the category page and remove the pagination controls. However the "remove" option does not work here and the example of setting the grid to all doesn't seem to work either. I have the correct xml file in the correct module folder in my theme as other items are working in that file. The block below just redirects the page back to the homepage for some reason.

```
<referenceBlock name="product_list_toolbar">
            <action method="addPagerLimit" translate="label">
                <argument name="mode" xsi:type="string">grid</argument>
                <argument name="limit" xsi:type="string">all</argument>
                <argument name="label" xsi:type="string">All</argument>
            </action>
        </referenceBlock>
```

**Comment by kokoc** [comment]
@cshaw-inviqa the following xml works for me:

```xml
<remove name="product_list_toolbar_pager" />
<referenceBlock name="product_list_toolbar">
    <action method="setDefaultGridPerPage">
        <argument name="limit" xsi:type="string">all</argument>
    </action>
</referenceBlock>
```

There are few additional things to note:
* Store->Settings->Catalog->Catalog-> Frontend->Allow All Products per Page add support of "all" option
* Please cleanup page cache, layout and configuration caches after the changes

Could you please verify the solution?

**Comment by cshaw-inviqa** [comment]
Yep, that works great! Thanks.

**Comment by cshaw-inviqa** [comment]
Actually this doesn't work. Copied the above xml and set the config in the admin. Also cleaned cache and cookies and still get this appearing.

![screen shot 2015-06-24 at 14 19 57](https://cloud.githubusercontent.com/assets/4057241/8330828/2068b558-1a7c-11e5-9b10-f942dd22bd92.png)

**Comment by kokoc** [comment]
Do you want to remove only pager related controls, but still have sorting controls on the page?

**Comment by mbrinton01** [comment]
@cshaw-inviqa do you have an update on this issue?

**Comment by vladimir-k** [comment]
Since we haven't heard back from you, we'll proceed with closing this issue. If in case you do have any updates, feel free to reach out to us by submitting a new issue

**Comment by razvanbalosin** [comment]
Hi, is there any way we can remove the `show per page` dropdown only via xml?

**Comment by christian-walker** [comment]
Did we ever find a fix to moving the toolbar?
