### ISSUE TITLE
When "Sign Static Files" is set to "Yes", site breaks and static content not loading

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#14040]
### Preconditions
1. Magento 2.2.3 (Developer Mode) Magento Luma theme with not customization
2. CentOS Linux 7.4.1708 (Core)
3. PHP 7.0.28 FastCGI Application served by Apache
4. Plesk Onyx 17.5.3 Update #43
5. Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 core(s))
6. mysql  Ver 15.1 Distrib 10.1.29-MariaDB

### Steps to reproduce
1. Backup files and database from initial Magento 2 site (Developer Mode) setup on subdomain
2. Deploy an identical copy of the site to the main domain
3. Make relevant changes for new site in terms of database details and in core_config_data ec. (https://magento.stackexchange.com/questions/127333/how-to-migrate-magento-2-0-x-from-one-server-to-another)
4. Check frontend and backend of Magento 2 site and no styling is applied and site is broken with many errors in the console of missing pub/static files etc.
5. Clear static content etc. var/view_preprocessed and pub/static folders
6. Enable maintenance mode and deploy static content by force: php bin/magento setup:static-content:deploy -f
6. Reindex etc.
7. Flush and clean cache (Even though Cache is disabled - cache:status -> All 0)
8. Check again and the site is still broken
9. Looked for a solution after searching google and followed this: https://stackoverflow.com/questions/42759196/magento-2-cant-find-css-and-js-files
**Note:** Not the edit of .htaccess file adding "RewriteBase /pub/static/ # <- Add This" but actually changing the dev/static/sign to 0 in core_config_data through edititng the table as could not access the backend admin due to no styling.
10. After changing the value of sign static content, the frontend and admin of Magento 2 show as normal and no errors in console etc. until for example a module is installed and there are errors in the console about pub/static/ files like right now:
![2018-03-10_125734](https://user-images.githubusercontent.com/17181901/37242525-e3bf4768-2462-11e8-8911-37bf35a45f33.png)
11. When I enable static sign content again via Admin backend or the database the site breaks and does not fix even after clearing cache, deleting relevant static folders and redeploying static content etc. 
12. Sometimes there are errors in the console as some files are missing randomly when making some changes in admin for a page or a product and even when redeploying static content, the files are not generated in pub/static folder

### Expected result
1. Backup files and database from initial Magento 2 site (Developer Mode) setup on subdomain
2. Deploy an identical copy of the site to the main domain
3. Make relevant changes for new site in terms of database details and in core_config_data etc. (https://magento.stackexchange.com/questions/127333/how-to-migrate-magento-2-0-x-from-one-server-to-another)
4. Check frontend and backend of Magento 2 site and all looks as normal with CSS and JS etc loading and pub/static content are deployed on demand when in the developer mode

### Actual result
1. Frontend and backend of Magento 2 site and no styling is applied and site is broken with many errors in the console of missing pub/static files etc. The static content are missing. Only solved if sign static content is disabled but even then pub/static files have errors when new changes are made or modules are installed etc.
2. Currently, at frontend there is the following error in console and the above errors as per "Steps to reproduce 10. Screenshot": 
![2018-03-10_052818](https://user-images.githubusercontent.com/17181901/37238710-075b0962-2424-11e8-9dc4-9ac608cfa14f.png)
3. No errors in system or exception logs about this
4. Also Redeployed static content with no succes, even specifically for backend and frontend: 
a) php bin/magento setup:static-content:deploy -f --theme Magento/backend en_US
b) php bin/magento setup:static-content:deploy -f --theme Magento/luma en_US

Any sort of help would be greatly appreciated in advance.

Thank you.

**Comment by GlobalOutsourcing** [comment]
Resolved by removing everything from Plesk admin --> Websites & Domains --> "Your Magento 2 Domain" --> Apache & nginx Settings for "Your Magento 2 Domain" --> Additional Apache directives & 
Additional nginx directives.

Thanks.

**Comment by kamorana** [comment]
We are experiencing the same issue (static content signing enabled) on 2.3.3. Anyone else having the same issues after re-deploying?
