### ISSUE TITLE
Getting group id from customer session returns wrong data type.

### ISSUE THREAD

**Issue by bydrei** [magento/magento2#14055]
If you get the customer from the session and then get the group id, the group id is returned as a string. The return type for that function specifies it should be of type int but it is returning as a string.

### Preconditions

1. Magento 2.1.12
2. PHP 7.0.27
3. MySQL 5.7.21

### Steps to reproduce

```
$customer = $this->customerSession->getCustomer();
$groupId  = $customer->getGroupId();
```

### Expected result

`$groupId` should be of type int and not a string.

### Actual result

`$groupId` is returned as a string instead of an int as the function phpDoc specifies.

```
/**
     * Retrieve customer group identifier
     *
     * @return int
     */
    public function getGroupId()
    {
        if (!$this->hasData('group_id')) {
            $storeId = $this->getStoreId() ? $this->getStoreId() : $this->_storeManager->getStore()->getId();
            $groupId = $this->_scopeConfig->getValue(
                GroupManagement::XML_PATH_DEFAULT_ID,
                ScopeInterface::SCOPE_STORE,
                $storeId
            );
            $this->setData('group_id', $groupId);
        }
        return $this->getData('group_id');
    }
```

**Comment by magento-engcom-team** [comment]
@ferrazzuk, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
This issue is not valid, see https://github.com/magento/magento2/pull/10519#issuecomment-322029527 for more details.

> The return type for that function specifies it should be of type int but it is returning as a string.

Numeric strings are defined as `int` all over the codebase in fact.
