### ISSUE TITLE
[FEATURE] Add CLI command to dump the sitemap

### ISSUE THREAD

**Issue by cedricziel** [magento/magento2#14053]
Currently, there's a cronjob that is run on a schedule. Since we deploy our site through deployer, the root directory content is reset on basically every deployment cycle.

So this now needs manual actions in the form of someone logging into the backend and clicking the "generate" button on the sitemap entries.

So in essence there should be a CLI command to dump the registered sitemaps to disk.

### Preconditions

No bug, so no preconditions.

### Steps to reproduce

No bug so no steps.

### Expected result

1. a CLI command should exist to dump the sitemaps

### Actual result

1. no such command is available

**Comment by magento-engcom-team** [comment]
Hi @cedricziel. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/67
