### ISSUE TITLE
Missing minified scripts on production mode (404 error)

### ISSUE THREAD

**Issue by fuunnx** [magento/magento2#14058]
Hi, I've developped a custom theme based on luma for a customer with various plugins etc. and everything works really fine in `developer mode`.

But when I switch to `production mode` it breaks because some unrelated third-party minified scripts are missing:
![capture d ecran 2018-03-12 a 14 44 20](https://user-images.githubusercontent.com/5963805/37287299-cce7f0d2-2604-11e8-9297-9780155c7eb5.png)

Of course I've try to empty the cache, set the right permissions (`find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod u+w {} \; && chmod u+x bin/magento`), deploy static content (`bin/magento setup:static-content:deploy fr_FR en_US`)

But in `production mode` the `static` repository is still missing the corresponding scripts (`ls -la pub/static/frontend/Sanosan/default/fr_FR/`) :
![capture d ecran 2018-03-12 a 14 46 38](https://user-images.githubusercontent.com/5963805/37287442-1e4e6e4c-2605-11e8-8a92-2ea7f79feb9b.png)

I've been looking through the internet various times without success so I open this issue…

### Preconditions
php v7.1.13
server debian/linux

### Steps to reproduce
1. `bin/magento deploy:mode:set production` with default language set to fr_FR 
2. load the `checkout` page

(no bug in `developer` mode !)

### Expected result
No bug, every script loads fine

### Actual result
404 errors for `.min.js` scripts
![capture d ecran 2018-03-12 a 14 43 48](https://user-images.githubusercontent.com/5963805/37287302-d0d38350-2604-11e8-9c69-340c5ae7f827.png)
Loader is infinite and prevents access to the screen !

Thanks

**Comment by magento-engcom-team** [comment]
Hi @fuunnx 
We can not reproduce it with any Magento theme.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@fuunnx, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
