### ISSUE TITLE
Configurable Product Type resource model 'getChildrenIds' method incorrect return format.

### ISSUE THREAD

**Issue by kshaa** [magento/magento2#14061]
### Preconditions
1. Want to batch get simple product ids from configurable product ids 
2. Magento version 2.4-develop

### Steps to reproduce
1. Inject class \Magento\ConfigurableProduct\Model\ResourceModel\Product\Type
2. Apply array of multiple configurable id's to method getChildrenIds 

### Expected result
1. Returns array, matching configurable ids to arrays of simple ids 
// Start of edit
2. Expecting array to have such structure: [
    "parent id" => ["child id"]
]
// End of edit

### Actual result
1. Returns array [0 => [
    "child id" => "child id"
]]

**Comment by kshaa** [comment]
Possible solution is to replace the getChildrenIds method as such:
Original
```
    public function getChildrenIds($parentId, $required = true)
    {
        $select = $this->getConnection()->select()->from(
            ['l' => $this->getMainTable()],
            ['product_id', 'parent_id']
        )->join(
            ['p' => $this->getTable('catalog_product_entity')],
            'p.' . $this->getProductEntityLinkField() . ' = l.parent_id',
            []
        )->join(
            ['e' => $this->getTable('catalog_product_entity')],
            'e.entity_id = l.product_id AND e.required_options = 0',
            []
        )->where(
            'p.entity_id IN (?)',
            $parentId
        );

        $childrenIds = [0 => []];
        foreach ($this->getConnection()->fetchAll($select) as $row) {
            $childrenIds[0][$row['product_id']] = $row['product_id'];
        }

        return $childrenIds;
    }
```

Changed
```
    public function getChildrenIds($parentId, $required = true)
    {
        $select = $this->getConnection()->select()->from(
            ['l' => $this->getMainTable()],
            ['product_id', 'parent_id']
        )->join(
            ['p' => $this->getTable('catalog_product_entity')],
            'p.' . $this->getProductEntityLinkField() . ' = l.parent_id',
            []
        )->join(
            ['e' => $this->getTable('catalog_product_entity')],
            'e.entity_id = l.product_id AND e.required_options = 0',
            []
        )->where(
            'p.entity_id IN (?)',
            $parentId
        );

        $childrenIds = [];
        foreach ($this->getConnection()->fetchAll($select) as $row) {
            $childrenIds[$row['parent_id']][] = $row['product_id'];
        }

        return $childrenIds;
    }
```

**Comment by magento-engcom-team** [comment]
@kshaa, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30486` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
