### ISSUE TITLE
Layer Text disappearing

### ISSUE THREAD

**Issue by nbmwebdev** [magento/magento2#14064]
When I try to edit default layer text from a default slider on Magetique template from Template Monster, and save, the layer text disappear, but the edit is not visible in my FrontPage, even when the default text is still there...

**Comment by magento-engcom-team** [comment]
@nbmwebdev, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
