### ISSUE TITLE
on fa_IR Persian Locale product price input has extra character results in validation error for input number

### ISSUE THREAD

**Issue by woshka** [magento/magento2#14067]
product price input has extra character results in validation error for input number on Persian language

Hello,
after changing the locale to fa_IR which means farsi_IRAN and in other words Persian language
there has been a bug on the backend product page
when creating a product it is fine but after modifying a product there if we don't touch the price input box it will return an error that the 
 
 
Spoiler
 however there is a number in there
after digging a lot I found out that there is an extra character added before the number which is 8206 and which means a left to right character identifier 
‎
Symbol Name:Html Entity:Hex CodeSmiley Very Happyecimal Code:Unicode Group:
Left-To-Right Mark
&lrm;
&#x200e;
&#8206;
General Punctuation
 
Which the price input box does not need it
a work arround for this is to override the validation method to check if it has a rtl identifier and trim it but I wanted to know how to prevent this character to be added to the price field

rules.js on line 540 validate the input but since it has an extra NAN character for javascript it thinks it is not a valid positive number and when it passes it to utils.js for parsnumber function it fails

### Preconditions

1. magento 2.1.12
2. magento 2.1.3
2. magento 2.1.2
installed without sampled data on php 5.6.34

php -v
PHP 5.6.34 (cli) (built: Mar  9 2018 22:42:55)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.1.1, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Suhosin v0.9.38, Copyright (c) 2007-2015, by SektionEins GmbH
httpd -v

Server version: Apache/2.2.34 (Unix)
Server built:   Mar  9 2018 22:37:04
Cpanel::Easy::Apache v3.36.1 rev9999

### Steps to reproduce

1. Go to _admin - Account Settings(admin)_ in the top right
2. Change **Interface Locate** to _Persian_ and **Save Account**
![interface_locate_Persian](https://user-images.githubusercontent.com/51680745/71811617-d9b84980-307d-11ea-9196-7bc0228c84a8.png)

3. Edit any existing product without editing the **Price** field. Click **Save**

### Expected result

1. save the product without any issues

### Actual result

The price field validation doesn't pass, an error message appears
1. https://jvdeh29369.i.lithium.com/t5/image/serverpage/image-id/7076iCCB436599BF5C5A4/image-size/large?v=1.0&px=999

**Comment by magento-engcom-team** [comment]
@woshka, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by woshka** [comment]
was this fixed on the latest 2.1.18 release?

**Comment by woshka** [comment]
How About is this issue?

**Comment by woshka** [comment]
@magento-engcom-team 
any updates to fix this issue?
when is it estimated due to be fixed?
Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30225` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by a-mahmoudieh** [comment]
I have same issue on 2.3.6
Please guide me

**Comment by a-mahmoudieh** [comment]
Hi
I solved it,
Please contact via WhatsApp:
+989122137655

**Comment by a-mahmoudieh** [comment]
این مشکل حل شد
در صورت تمایل به دریافت راه حل لطفل از طریق شماره زیر در تلگرام یا واتساپ تماس بگیرید
09122137655

**Comment by engcom-Delta** [comment]
Hi @woshka ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce :** 

1. Install fa_IR Persian Language pack.
2. Go to admin - Account Settings(admin) in the top right
3. Change Interface Locate to Persian and Save Account
![image](https://github.com/user-attachments/assets/3452b733-ff12-491d-9343-f1879b867d99)
4.  Edit any existing product without editing the Price field. Click Save
![image](https://github.com/user-attachments/assets/4ac24d88-2680-4fe1-823a-81e893b47be6)
![image](https://github.com/user-attachments/assets/7da3e536-5005-4de4-b578-f7d6991d878f)

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.
Thanks.
