### ISSUE TITLE
Error when locale is changed to fa_IR

### ISSUE THREAD

**Issue by woshka** [magento/magento2#14068]
Error on Backend when the magento is converted to fa_IR Locale
Please fix this issue on 2.1.x since we have too many magento websites on themes designed for 2.1
there is a hotfix but I do not believe is the correct way in this url

https://github.com/magento/magento2/issues/3541

### Preconditions

1. Magento 2.1.12
2. Magento 2.1.3
3. Centos 6.9
4. Cpanel 

php -v
PHP 5.6.34 (cli) (built: Mar  9 2018 22:42:55)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.1.1, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Suhosin v0.9.38, Copyright (c) 2007-2015, by SektionEins GmbH
httpd -v

Server version: Apache/2.2.34 (Unix)
Server built:   Mar  9 2018 22:37:04
Cpanel::Easy::Apache v3.36.1 rev9999

### Steps to reproduce

1. Change the Locale to fa_IR
2. Clear all caches or set on development mode 

### Expected result

1. login in to the admin page of magento 

### Actual result

1.
1 exception(s):
Exception #0 (Exception): Recoverable Error: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given, called in /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/AbstractBlock.php on line 659 and defined in /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/Html/Calendar.php on line 75

Exception #0 (Exception): Recoverable Error: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given, called in /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/AbstractBlock.php on line 659 and defined in /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/Html/Calendar.php on line 75
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/home/magento2f...', 75, Array)
#1 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/Html/Calendar.php(75): iterator_to_array(NULL)
#2 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Html\Calendar->_toHtml()
#3 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#4 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('head.calendar')
#5 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('head.calendar')
#6 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('head.calendar')
#7 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('head.calendar', true)
#8 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('head.calendar')
#9 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
#10 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('after.body.star...')
#11 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('after.body.star...')
#12 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('after.body.star...', true)
#13 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('after.body.star...')
#14 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#15 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#16 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#17 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#18 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#19 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#20 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#21 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#22 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#23 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#24 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#25 /home/magento2farsi/demo2.magento2farsi.com/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#26 {main}

**Comment by magento-engcom-team** [comment]
@woshka, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release. In addition, identify any other information needed to reproduce your issue.

**Comment by woshka** [comment]
Hello,
What is your testing envirenment for reproducing this issue?
I have installed many clean installation more than 10 on diffrent servers all running on a centos 6.X and reproduced the same issue

according to this 
https://github.com/magento/magento2/issues/3541
it seems that there is no issue on Ubuntu libicu 52.1

"Seem that problem occur when run magento 2 on Centos with Iibicu version 50.1.2. My ubuntu server installed libicu 52.1 working fine."

for having the very the same envirement do the bellow instructions or maybe the centos always have this result of error,
This is the very common build since dominant of the websites are hosted on Cpanel on a Centos Server

Please do the following,
install clean Centos minimal 
http://mirror.muvhost.com/centos/6.9/isos/x86_64/CentOS-6.9-x86_64-minimal.iso

create an empty file for enabling easyapache 3 on cpanel after installation
touch /etc/install_legacy_ea3_instead_of_ea4

install Cpanel
cd /home && curl -o latest -L https://securedownloads.cpanel.net/latest && sh latest
after that compile using this build
you can save this build in this directory and rebuild or manually enable the build on EasyApache 3 profile
I have uploaded the file in here
http://ziifile.com/xpz1m4w72lz4.html

/var/cpanel/easy/apache/profile
--- 
"Apache": 
  "optmods": 
    "Access": 0
    "Actions": 0
    "Alias": 0
    "Asis": 0
    "AuthAnon": 0
    "AuthDB": 0
    "AuthDBM": 0
    "AuthDigest": 0
    "AuthLDAP": 0
    "AuthnAlias": 0
    "AuthnAnon": 0
    "AuthnDBD": 0
    "AuthnDBM": 0
    "AuthnDefault": 0
    "AuthnzLDAP": 0
    "AuthzDBM": 0
    "AuthzHost": 0
    "AuthzOwner": 0
    "Autoindex": 0
    "Bucketeer": 0
    "Cache": 0
    "CaseFilter": 0
    "CaseFilterIn": 0
    "CernMeta": 0
    "CharsetLite": 0
    "DAVFs": 0
    "DAVLock": 0
    "DBD": 1
    "DIR": 0
    "Dav": 0
    "Deflate": 1
    "DiskCache": 0
    "Distcache": 0
    "Dumpio": 0
    "Echo": 0
    "Env": 0
    "Expires": 1
    "ExtFilter": 0
    "Fastcgi": 1
    "FileCache": 0
    "Fileprotect": 1
    "Headers": 1
    "Ident": 0
    "Imagemap": 0
    "LDAP": 0
    "LogAgent": 0
    "LogConfig": 0
    "LogForensic": 0
    "LogReferer": 0
    "MPMEvent": 1
    "MPMItk": 0
    "MPMLeader": 0
    "MPMPerchild": 0
    "MPMPrefork": 0
    "MPMThreadpool": 0
    "MPMWorker": 0
    "MemCache": 1
    "Mime": 0
    "MimeMagic": 0
    "MmapStatic": 0
    "Negotiation": 0
    "OptionalFnExport": 0
    "OptionalFnImport": 0
    "OptionalHookExport": 0
    "OptionalHookImport": 0
    "PHPAsUser": 1
    "Proxy": 1
    "RaiseFDSetsize": 0
    "RaiseHardServerLimit": 0
    "Rewrite": 1
    "Setenvif": 0
    "SlowRestartPatch": 1
    "Speling": 0
    "Status": 0
    "SymlinkProtection": 0
    "UniqueId": 1
    "Userdir": 0
    "Usertrack": 0
    "Version": 0
    "VhostAlias": 0
    "Watchdog": 0
  "version": '2_2'
"Cpanel::Easy::EAccelerator": 0
"Cpanel::Easy::IonCube5": 1
"Cpanel::Easy::IonCubeLoader": 0
"Cpanel::Easy::ModBandwidth": 0
"Cpanel::Easy::ModJk": 0
"Cpanel::Easy::ModJk5": 0
"Cpanel::Easy::ModMono": 0
"Cpanel::Easy::ModMono2": 0
"Cpanel::Easy::ModPerl": 0
"Cpanel::Easy::ModQos": 0
"Cpanel::Easy::ModRuid2": 0
"Cpanel::Easy::ModSec": 0
"Cpanel::Easy::PHP5": 1
"Cpanel::Easy::PHP5::3_29": 0
"Cpanel::Easy::PHP5::4_45": 0
"Cpanel::Easy::PHP5::5_38": 0
"Cpanel::Easy::PHP5::6_34": 1
"Cpanel::Easy::PHP5::Bcmath": 1
"Cpanel::Easy::PHP5::Bz2": 1
"Cpanel::Easy::PHP5::CGI": 0
"Cpanel::Easy::PHP5::Calendar": 1
"Cpanel::Easy::PHP5::Curl": 0
"Cpanel::Easy::PHP5::CurlSSL": 1
"Cpanel::Easy::PHP5::Curlwrappers": 0
"Cpanel::Easy::PHP5::DBX": 0
"Cpanel::Easy::PHP5::Dbase": 0
"Cpanel::Easy::PHP5::DiscardPath": 0
"Cpanel::Easy::PHP5::Enchant": 1
"Cpanel::Easy::PHP5::Exif": 1
"Cpanel::Easy::PHP5::Expat": 0
"Cpanel::Easy::PHP5::FTP": 1
"Cpanel::Easy::PHP5::Fastcgi": 0
"Cpanel::Easy::PHP5::FileInfo": 1
"Cpanel::Easy::PHP5::ForceCGIRedirect": 0
"Cpanel::Easy::PHP5::GD": 1
"Cpanel::Easy::PHP5::Gettext": 1
"Cpanel::Easy::PHP5::HardPHP": 0
"Cpanel::Easy::PHP5::Iconv": 0
"Cpanel::Easy::PHP5::Imap": 1
"Cpanel::Easy::PHP5::Intl": 1
"Cpanel::Easy::PHP5::Java": 0
"Cpanel::Easy::PHP5::MM": 0
"Cpanel::Easy::PHP5::MagicQuotes": 1
"Cpanel::Easy::PHP5::MailHeaders": 1
"Cpanel::Easy::PHP5::Mbregex": 0
"Cpanel::Easy::PHP5::Mbstring": 1
"Cpanel::Easy::PHP5::Mcrypt": 1
"Cpanel::Easy::PHP5::MemoryLimit": 0
"Cpanel::Easy::PHP5::Mhash": 0
"Cpanel::Easy::PHP5::MimeMagic": 0
"Cpanel::Easy::PHP5::Mysql": 1
"Cpanel::Easy::PHP5::MysqlOfSystem": 0
"Cpanel::Easy::PHP5::Mysqli": 1
"Cpanel::Easy::PHP5::Opcache": 1
"Cpanel::Easy::PHP5::Openssl": 1
"Cpanel::Easy::PHP5::PDO": 1
"Cpanel::Easy::PHP5::PDOMySQL": 1
"Cpanel::Easy::PHP5::POSIX": 0
"Cpanel::Easy::PHP5::Pear": 0
"Cpanel::Easy::PHP5::Pgsql": 1
"Cpanel::Easy::PHP5::Phar": 0
"Cpanel::Easy::PHP5::Pspell": 0
"Cpanel::Easy::PHP5::SNMP": 0
"Cpanel::Easy::PHP5::SOAP": 1
"Cpanel::Easy::PHP5::SQLite3": 0
"Cpanel::Easy::PHP5::SafeMode": 0
"Cpanel::Easy::PHP5::SafePHPCGI": 0
"Cpanel::Easy::PHP5::SilenceDeprecatedPatch": 0
"Cpanel::Easy::PHP5::Sockets": 1
"Cpanel::Easy::PHP5::SysTimezone": 0
"Cpanel::Easy::PHP5::TTF": 1
"Cpanel::Easy::PHP5::Tidy": 1
"Cpanel::Easy::PHP5::Versioning": 0
"Cpanel::Easy::PHP5::Wddx": 1
"Cpanel::Easy::PHP5::WithoutIconv": 0
"Cpanel::Easy::PHP5::XSL": 1
"Cpanel::Easy::PHP5::XmlRPC": 1
"Cpanel::Easy::PHP5::ZendMultibyte": 0
"Cpanel::Easy::PHP5::Zip": 1
"Cpanel::Easy::PHP5::Zlib": 1
"Cpanel::Easy::PHP5::cPPHPOpts": 0
"Cpanel::Easy::PHPSuHosin": 1
"Cpanel::Easy::SourceGuardian": 1
"Cpanel::Easy::Tomcat::7_0": 0
"Cpanel::Easy::Xcache": 0
"Cpanel::Easy::Zendopt": 1
"_meta": 
  "name": 'Basic Apache 2.2 (1)'
  "note": 'You should only use this profile if you require Apache 2.2. This profile includes the basic modules that you need to run a minimal web server. We recommend that you use this profile if your previous build with Apache 2.2 failed.'
  "revision": 'qYY_2R0Ns1NxT12VRD023sZCQAAKsVo1Yv6jyHi2dexP7o_rtjRijSgSH_EG7b6i'


After that install a fresh magento 2.1 and you will encounter the Error after changing the locale

Thanks

**Comment by orlangur** [comment]
@woshka could you please dump the contents of `$daysData` in https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/View/Element/Html/Calendar.php#L70?

**Comment by orlangur** [comment]
So probably `$localeData['calendar']['gregorian']['dayNames']` is empty in your case, as you mentioned in other issue persian calendar. Probably some `$localeData['calendar']['persian']` contains this data.

**Comment by woshka** [comment]
I am on mobile right now and I will provide you the requested file
gowever it is a clean install that I have done this hunderd of times and got the same result issue

**Comment by woshka** [comment]
like I said have a clean installation and the contents are the same
./vendor/magento/framework/View/Element/Html/Calendar.php on line 70
`        // get days names
        $daysData = $localeData['calendar']['gregorian']['dayNames'];
        $this->assign(
            'days',
            [
                'wide' => $this->encoder->encode(array_values(iterator_to_array($daysData['format']['wide']))),
                'abbreviated' => $this->encoder->encode(
                    array_values(iterator_to_array($daysData['format']['abbreviated']))
                ),
            ]
        );
`

**Comment by orlangur** [comment]
@woshka not the source code but the contents of variable. With `var_export` or something.

It is much easier than trying to reproduce exactly the same locale configuration.

**Comment by woshka** [comment]
I added this code to export but the error seems to be before this code execution and have the same error
[http://demo2.magento2farsi.com/admin_7vcue1/](url)
user: admin
pass: 123123qq

        // get days names
        $daysData = $localeData['calendar']['gregorian']['dayNames'];
        echo var_export($daysData);
exit();

**Comment by orlangur** [comment]
Try dumping `$localeData['calendar']` then.

**Comment by woshka** [comment]
`  protected function _toHtml()
    {



        $localeData = (new DataBundle())->get($this->_localeResolver->getLocale());

 echo var_export($localeData['calendar']);
exit();


//$localeData = (new DataBundle())->get('en_US');

        // get days names
        $daysData = $localeData['calendar']['gregorian']['dayNames'];

        $this->assign(
            'days',
            [
                'wide' => $this->encoder->encode(array_values(iterator_to_array($daysData['format']['wide']))),
                'abbreviated' => $this->encoder->encode(
                    array_values(iterator_to_array($daysData['format']['abbreviated']))
                ),
            ]
        );
`



> 1 exception(s):
Exception #0 (Exception): Notice: Undefined variable: localeData in /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/Html/Calendar.php on line 68

Exception #0 (Exception): Notice: Undefined variable: localeData in /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/Html/Calendar.php on line 68
#0 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/Html/Calendar.php(68): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined varia...', '/home/magento2f...', 68, Array)
#1 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Html\Calendar->_toHtml()
#2 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#3 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('head.calendar')
#4 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('head.calendar')
#5 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('head.calendar')
#6 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('head.calendar', true)
#7 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('head.calendar')
#8 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
#9 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('after.body.star...')
#10 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('after.body.star...')
#11 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('after.body.star...', true)
#12 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('after.body.star...')
#13 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#14 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#15 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#16 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#17 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#18 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#19 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#20 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#21 /home/magento2farsi/demo2.magento2farsi.com/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#22 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#23 /home/magento2farsi/demo2.magento2farsi.com/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#24 /home/magento2farsi/demo2.magento2farsi.com/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#25 {main}

**Comment by orlangur** [comment]
@woshka,

`$localeData = (new DataBundle())->get($this->_localeResolver->getLocale());`

`$localeData` cannot be undefined after this.

You can even `var_export` the whole `(new DataBundle())->get($this->_localeResolver->getLocale())` to see what is returned.

**Comment by woshka** [comment]
there is something stated the issue in the code of magento too

`        /**
         * Month names in abbreviated format values was added to ICU Data tables
         * starting ICU library version 52.1. For some OS, like CentOS, default
         * installation version of ICU library is 50.1.2, which not contain
         * 'abbreviated' key, and that may cause a PHP fatal error when passing
         * as an argument of function 'iterator_to_array'. This issue affects
         * locales like ja_JP, ko_KR etc.
         *
         * @see http://source.icu-project.org/repos/icu/tags/release-50-1-2/icu4c/source/data/locales/ja.txt
         * @see http://source.icu-project.org/repos/icu/tags/release-52-1/icu4c/source/data/locales/ja.txt
         * @var \ResourceBundle $monthsData
         */
`

**Comment by woshka** [comment]
I installed on other account and chnged to fa_IR and used 
 ./magento setup:di:compile
and
./magento indexer:reindex
./magento cache:clean

and the same issue on admin panel

`1 exception(s):
Exception #0 (Exception): Recoverable Error: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given, called in /home/mahtoo/public_html/vendor/magento/framework/View/Element/AbstractBlock.php on line 659 and defined in /home/mahtoo/public_html/vendor/magento/framework/View/Element/Html/Calendar.php on line 74

Exception #0 (Exception): Recoverable Error: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given, called in /home/mahtoo/public_html/vendor/magento/framework/View/Element/AbstractBlock.php on line 659 and defined in /home/mahtoo/public_html/vendor/magento/framework/View/Element/Html/Calendar.php on line 74
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/home/mahtoo/pu...', 74, Array)
#1 /home/mahtoo/public_html/vendor/magento/framework/View/Element/Html/Calendar.php(74): iterator_to_array(NULL)
#2 /home/mahtoo/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Html\Calendar->_toHtml()
#3 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#4 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('head.calendar')
#5 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('head.calendar')
#6 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('head.calendar')
#7 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
#8 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('after.body.star...')
#9 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('after.body.star...')
#10 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#11 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('root')
#12 /home/mahtoo/public_html/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout->renderElement('root')
#13 /home/mahtoo/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(37): Magento\Framework\View\Layout->getOutput()
#14 /home/mahtoo/public_html/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#15 /home/mahtoo/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#16 /home/mahtoo/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#17 /home/mahtoo/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#18 /home/mahtoo/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#19 /home/mahtoo/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#20 {main}`
















```

[mahtoo@box1 bin]$ rpm -qa | grep icu
libicu-4.2.1-14.el6.x86_64
libicu-devel-4.2.1-14.el6.x86_64
easy-libicu-devel-4.0.1-2.x86_64
easy-libicu-4.0.1-2.x86_64
icu-4.2.1-14.el6.x86_64
easy-libicu-doc-4.0.1-2.x86_64
easy-icu-4.0.1-2.x86_64

```




there is a temporary solution on this URL
https://github.com/magento/magento2/issues/3541

A temporary solution:Go to this file: vendor/magento/framework/View/Element/Html/Calendar.php line ~65Replace:$localeData = (new DataBundle())->get($this->_localeResolver->getLocale());With:$localeData = (new DataBundle())->get('en_US');
--





A temporary solution:Go to this file: vendor/magento/framework/View/Element/Html/Calendar.php line ~65Replace:$localeData = (new DataBundle())->get($this->_localeResolver->getLocale());With:$localeData = (new DataBundle())->get('en_US');
--

What is the problem that this temporary fix, fixes the problem?

Thanks

**Comment by woshka** [comment]
@orlangur 

```

$localeData = (new DataBundle())->get($this->_localeResolver->getLocale());
var_export(new DataBundle())->get($this->_localeResolver->getLocale());
exit();

```

the export result is this

Magento\Framework\Locale\Bundle\DataBundle::__set_state(array( 'path' => 'ICUDATA', ))

**Comment by woshka** [comment]
@magento-admin @magento-engcom-team @dimonovp 
Please Take a look at this issue and let me know how to fix it
the fa_IR xml file seems to be not complete but I completed with the shamsi information but still I have the issue
I uploaded those files for you to help you to fix this issue
[zendframework1.zip](https://github.com/magento/magento2/files/1994486/zendframework1.zip)

**Comment by ghost** [comment]
@woshka, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by sjgdk** [comment]
This issue is not solved.

`vendor/magento/framework/View/ElementHtml/Calendar.php` line 75 caused the same error.

**Comment by surao101** [comment]
Same problem when setting locale to Chinese (Taiwan)

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in vendor/magento/framework/View/Element/Html/Calendar.php:75
