### ISSUE TITLE
Any cli comands are not working

### ISSUE THREAD

**Issue by nnnx** [magento/magento2#1407]
```
c:\nginx\html\bin>php magento --list
Autoload error: An abstract factory could not create an instance of magentosetupconsolecommandmoduleuninstallcommand(alias: Magento\Setup\Console\Command\Mod
uleUninstallCommand).
```

**Comment by Vinai** [comment]
I had a similar issue yesterday which I also tracked down and solved with the solution listed for the sample data problem issue in https://github.com/magento/magento2/issues/1398#issuecomment-114016718. Maybe it also solves the problem for you.

**Comment by bartdelvauxx** [comment]
I had exact the same issue a few days ago. It was caused because I had done the installation with a "composer-install --no-dev" command. 

When installing the composer dependencies with the command "composer install" it worked again.

**Comment by nevvermind** [comment]
I  use the PR change from https://github.com/magento/magento2/pull/1323.

**Comment by vancoz** [comment]
Hello @nnnx could you please try solution described in this issue https://github.com/magento/magento2/issues/1394 ?

Thank you

**Comment by nnnx** [comment]
@vancoz
doesn't work for me:
![54b92d8e7d](https://cloud.githubusercontent.com/assets/7686446/8370890/b699f530-1bf0-11e5-9bfa-99ba1add7c72.jpg)

**Comment by xcomSteveJohnson** [comment]
@nnnx This indicates some general failure. I've seen it before and solved it by reinstalling. You can also try deleting var/generation and var/cache, doing composer update, and trying again. Another alternative to reinstalling is magento setup:upgrade.

In order:

a) rm -rf var/generation var/cache
b) composer update
c) try again
d) git pull origin
e) magento setup:upgrade
f) composer update
g) try again
