### ISSUE TITLE
Can't download magento from site

### ISSUE THREAD

**Issue by PixelT** [magento/magento2#14075]
I cannot download magento from https://magento.com/tech-resources/download
I select format, click download, login to my account and after that I have infinite loading...

There is an error in console on xhr request:
```
403 | xhr | jquery-1.9.1.min.js:5
```

**Comment by magento-engcom-team** [comment]
@PixelT , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
