### ISSUE TITLE
Checkout not showing shipping step after switching product weight from 0 to something else

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#14076]
### Preconditions

PHP Version: 7.0.28
Magento 2.2.2
Debian 8 server
Luma theme
Developer / Production mode

### Steps to reproduce

1. Create a configurable product with a few variations (PRODUCT-1). 
2. Leave weight field to 0
3. Add PRODUCT-1 to cart as a guest
4. Go to checkout as a guest
5. You can see that shipping step is missing.
6. Log in as admin on another browser and change PRODUCT-1 weight to 1kg
7. Go back to your window at checkout step and refresh page.
8. Shipping step still not appears.

### Expected result
1. The shipping step  and the payment/review step should show up for the guest

### Actual result
1. Only payment/review step appears

Doing the following **doesn't** solve the issue. 
- Cache clearing
- Reindexing
- Static content re-deploy

Doing the following fixes the issue.
- Remove products from cart until cart is empty
- Readd product to cart
- Revisit checkout

**Comment by orlangur** [comment]
> Leave weight field to 0

This will produce virtual product I believe and thus there is no shipping required.

**Comment by ioweb-gr** [comment]
Yes exactly it will produce virtual product and shipping is not required. However if that product is added to the cart while weight is 0 and the admin changes the weight to 1kg because he realizes he made a mistake. The user's cart stays stuck on a state where shipping doesn't show until the user empties the cart. The issue is the cart is not updated correctly and it's not reflected in the checkout when the weight changes. Hope I was able to clarify this point a little better.

**Comment by magento-engcom-team** [comment]
@ioweb-gr, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
We do:
1. Create a configurable product with a few variations with weight = 0 (This item has no weight).
2. Add created product to cart as a guest
3. Go to checkout as a guest
4. You can see that shipping step is missing. - (the product is virtual, that no shipping required.)
5. Log in as admin on another browser and change product weight to 1kg (This item has weight).
6. Go back to your window at checkout step and refresh page.

**Actual result**: The Shipping step and the Review & Payments step show up for the guest.

**Comment by ioweb-gr** [comment]
I'll try and make a fresh install this weekend to see if it persists for my setup and get back with more info.

**Comment by ioweb-gr** [comment]
After further troubleshooting it was a usage error on my part. Just changing the configurable product from "This product has no weight" to "this product has weight" isn't enough. You need to do it on all simple product variations as well in order to see the changes on the checkout because the simple products are the ones that actually get added to the cart.  

Thanks for checking it out and helping me further troubleshoot the issue.

**Comment by magento-engcom-team** [comment]
@ioweb-gr, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by Anju2006** [comment]
Im facing a slight variant issue. The cart has 75% configurable products and adding them to cart directs to a shipping address page which provides an update button which isn't the page when I am adding a non-configurable product to the cart.  One shows shipping method but for non-configurable, It goes directly with just showing shipping method (preferred) 

Pls help!
