### ISSUE TITLE
price with inclusive tax

### ISSUE THREAD

**Issue by payaltpss** [magento/magento2#14073]
can we show price in left filter inclusive tax? as we add price in back-end exclusive tax. and show on front-end inclusive tax. So when we select price result is different. Its so confusing.. Please Help.. I don't want to rework on adding price

**Comment by magento-engcom-team** [comment]
@payaltpss, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by orlangur** [comment]
Hi @payaltpss, GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
