### ISSUE TITLE
[FEATURE]Rial currency must not have .00 at the end

### ISSUE THREAD

**Issue by woshka** [magento/magento2#14070]
Persian Rial Currency does not have .00 at the end meaning that for example 21.00 is not applicable
the rial currency is such 34000 Rial
5400Rial

there is a comma delimiter that is arbitrary for any thousand 
for example 34,000
5,400
9,360,764
but there shoudn't be .00 at the end since  does not have any value
### Preconditions

1. magento 2.3.x
2. magento 2.2.x
3. magento 2.1.x
4. magento 2.0.x

### Steps to reproduce

1. on admin go to catalogue
2. on frontend on prices secton
3. 

### Expected result

1. a pricing such as 34,000 or 5,400

### Actual result

1. there is .00 at the end of all prices such as 34,000.00 which the .00 must be omitted

**Comment by HirokazuNishi** [comment]
It's same in JPY (and maybe same for TWD, IDR, VND and KRW)

**Comment by orlangur** [comment]
And `HUF`: https://github.com/magento/magento2/issues/10954#issuecomment-350783072

Not sure if discarding decimal described in https://github.com/magento/magento2/issues/1240 is the right method for every such currency.

**Comment by woshka** [comment]
changing this behavior for just only some currencies 
some people has modified the core to remove the .00 decimal at the end of prices but it is not a good idea and having a conditional to just only for some currencies or having this as an option in the backend would be a great Idea

**Comment by orlangur** [comment]
@woshka I believe you didn't understand my point :)

I'm saying that the way rounding should work for JPY may be not applicable for some other similar currencies like HUF or IRR.

So this could be not a problem just with displaying prices but also how you calculate taxes.

**Comment by woshka** [comment]
@orlangur 
I am not familiar with the JPY currency system
however if there are differences for any countries currencies there should be a configurable change at the installation level which can not be reverted for a specific store
or at least make changes just only on the view when a specific currency is enabled
after all having .00 omitted at least on the view is essential for IRR currency

**Comment by woshka** [comment]
Is there any plan to add this feature
Thanks

**Comment by woshka** [comment]
@orlangur @magento-engcom-team  @HirokazuNishi 
I've found an extenssion that do this
but it would be wise to have magento team itself to develop an option to change the decimal digits
https://github.com/lillik/magento2-price-decimal

**Comment by magento-engcom-team** [comment]
Hi @woshka. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/69
