### ISSUE TITLE
magento Table Rate Shipping csv Region/State

### ISSUE THREAD

**Issue by emilshamloo** [magento/magento2#14078]
I work with Magento 2.2.2
And I am trying to add different prices for differnt cities in my country.

I have only 2 shipping rates! One for my City and another for rest of my country, Norway.
Can I add the name of my City, “Oslo” in the “Region/State” and “*” for rest of the country?
Like this?
“Country”	“Region/State”	“Zip/Postal Code”	“Order Subtotal (and above)”	“Shipping Price”
NOR	Oslo	*	0	120
NOR	*	*	0	240

Regards

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. 

AFAIR, `*` will still match Oslo.
