### ISSUE TITLE
Avoid getShippingRates().subscribe to be called twice

### ISSUE THREAD

**Issue by maximehuran** [magento/magento2#14081]
JS functions which subscribe to `shippingService.getShippingRates()` are called twice

### Preconditions
1. Actual for 2.3-develop

### Steps to reproduce
1. Add console.log() in `app/code/Magento/Checkout/view/frontend/web/js/view/cart/totals.js` between l.24 and l.25
1. Add product to cart;
2. Go to Shopping Cart;
3. Show console and when total is loaded, the log is shown twice

### Expected result
1. The function must be called once

### Actual result
1. The function is called twice

A clue to resolve this problem is to remove in the file `app/code/Magento/Checkout/view/frontend/web/js/model/shipping-service.js`, the line `shippingRates.valueHasMutated()` (l.24), because the l.23 already call the subscribed functions.

**Comment by orlangur** [comment]
Observed behavior is correct.

Suggested change won't work in case rates array structure is the same with different contents.

See https://forums.asp.net/t/2056128.aspx?What+is+the+use+of+valueHasMutated+in+Knockout+js and https://stackoverflow.com/questions/13316034/knockoutjs-calling-valuehasmutated-too-often?noredirect=1&lq=1 for more details.

**Comment by maximehuran** [comment]
I have only one problematic case if I remove the line. It is when I push an element directly in my array 
```
this.shippingRates().push(myCustomShippingRate);
```

With that and without the `shippingRates.valueHasMutated()`, my subscribers are not notified.
But, I'm a good developper, so when I change an element in my array, I set it in my object after : 

```
this.shippingRates().push(myCustomShippingRate);
shippingService.setShippingRates(this.shippingRates());
```

My test is made inside the `app/code/Magento/Checkout/view/frontend/web/js/view/cart/shipping-rates.js` in order to be able to manually add a shippingRate.

**Comment by orlangur** [comment]
With consecutive calls to `shippingService.setShippingRates(data);` will subscribers be notified in case only one element of array is changed?

**Comment by maximehuran** [comment]
I don't know excatly what you mean but if I do : 
```
this.shippingRates().push(duplicated);
shippingService.setShippingRates(this.shippingRates());
shippingService.setShippingRates(this.shippingRates());
shippingService.setShippingRates(this.shippingRates());
```

My subscribers are called 3 times with my new array element inside : 
![image](https://user-images.githubusercontent.com/11380627/37353533-d2e8018a-26df-11e8-988a-15d224596155.png)
2 elements before
3 elements after (displayed 3 times)

**Comment by orlangur** [comment]
@maximehuran the same amount of elements but change some of them I mean.

**Comment by maximehuran** [comment]
I can easily change the carrier_code of an element and set it just after : 
```
this.shippingRates()[0].carrier_code = 'hello';
shippingService.setShippingRates(this.shippingRates());
```

Log after change : 
![image](https://user-images.githubusercontent.com/11380627/37390609-f2287172-2768-11e8-8d00-99b16754c0ae.png)

**Comment by orlangur** [comment]
> 3 elements after (displayed 3 times)

Sorry, missed this earlier. As we assume `shippingService.setShippingRates` should always be used and not just direct modifications of previously set array, it is safe to remove this line.

Could you prepare a pull request against `2.2-develop` branch please?

**Comment by magento-engcom-team** [comment]
@maximehuran, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dmanners** [comment]
Hi @maximehuran was this issue fixed with the pull request https://github.com/magento/magento2/pull/14314 I see a comment on you pull request linking to this one.

**Comment by orlangur** [comment]
@dmanners did you read comments in PR? It seems to be reverted afterwards.

**Comment by dmanners** [comment]
Hi @orlangur nope I did not ready all the comments at the end. GitHub does not do a great job of showing reverted PRs that have not been reverted via github itself

**Comment by orlangur** [comment]
@dmanners yep, just fyi, I didn't even check whether it was really reverted.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30132` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
