### ISSUE TITLE
Error command cli  setup:static-content:deploy

### ISSUE THREAD

**Issue by Opticcenter** [magento/magento2#1408]
bin/magento setup:static-content:deploy

`=== frontend -> Magento/blank -> en_US ===
................................................................................................................................................................................................................................................................................................................................................................The "/var/www/magento2/" file doesn't exist or not a file (Processing file 'images/select-bg.svg' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/magento2/" file doesn't exist or not a file (Processing file 'fonts/selection.json' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.woff' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.eot' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.woff2' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.ttf' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.The "/var/www/magento2/" file doesn't exist or not a file (Processing file 'fonts/Luma-Icons.svg' for area 'frontend', theme 'Magento/blank', locale 'en_US')
.....................................................................................................................................................................`

**Comment by mazhalai** [comment]
@Opticcenter Thank you for reporting! We are working on this issue : MAGETWO-38561

**Comment by piotrekkaminski** [comment]
This should be closed already.

**Comment by leonmex** [comment]
This error still happen in the version 2.1.5 when you include new theme with the fonts from luma theme
