### ISSUE TITLE
Exception #0 (Exception): Warning: SessionHandler::read():  Unable to clear session lock record in        /var/www/magento/vendor/magento/framework/Session/SaveHandler/Native.php on line 22

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#14082]
**Env:**
PHP 7.0.20
Magento 2.2.2 Commerce
Memcached:1.4.35

**Steps to Reproduce**
Install Magento 2.2.2
Configure to use memcached as specified in dev docs
Try to access admin area

**Expected result:**
After login access admin area

**Actual result:**
`Exception #0 (Exception): Warning: SessionHandler::read():  Unable to clear session lock record in        /var/www/magento/vendor/magento/framework/Session/SaveHandler/Native.php on line 22`

Section of env.php
```

'session' =>
  array (
    'save' => 'memcached',
    'save_path' => 'memcached:11211',
  )
```
Section of php.ini

`session.save_handler = memcached`

Please ask for any other details

**Comment by Asifjalil99** [comment]
you need to code like this where memcached_port is your port number you can check it from cpanel 

'session' => [
array (
  'save' => 'memcached',
  'save_path' => '127.0.0.1:memcached_port',
)
],
