### ISSUE TITLE
Report on Products in Carts 

### ISSUE THREAD

**Issue by vince1222** [magento/magento2#14092]
### Preconditions

1. Magento 2.18
2. PHP 7.0.23

### Steps to reproduce

1. Login Admin Dashboard
2. Reports >Under Marketing >Products in Cart
3.

### Expected result

1.  View All customer cart .

### Actual result

1. empty data, Nothings display on the window
![23](https://user-images.githubusercontent.com/824697/37382656-deeb7e0e-277e-11e8-953a-75a725effde5.PNG)

**Comment by magento-engcom-team** [comment]
@vince1222 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![product_add_front](https://user-images.githubusercontent.com/31669971/37392963-67928178-2778-11e8-9285-1de47537330e.png)

![product_in_cart_admin](https://user-images.githubusercontent.com/31669971/37392980-7313ef8c-2778-11e8-9ef6-e9b379a194a9.png)

**Comment by magento-engcom-team** [comment]
@vince1222, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
