### ISSUE TITLE
Payment methods do not show on multi shipping checkout

### ISSUE THREAD

**Issue by baskuis** [magento/magento2#14090]
### Preconditions
1.  https://stackoverflow.com/questions/49264867/payment-methods-are-not-showing-up-on-multi-shipping
2. Payment options are showing fine: /default/checkout/#payment
3. Payment options are not showing up: /multishipping/checkout/billing/
4. Upon clicking: 'Go to Review Your Order' - the following message is displayed: We can't complete your order because you don't have a payment method set up.
5. The console does not show any errors.
6. This happens in magento community: 2.2.2
7. PHP version 7.1

### Steps to reproduce
1. Payment options are showing fine: /default/checkout/#payment
2. Payment options are not showing up: /multishipping/checkout/billing/
3. Upon clicking: 'Go to Review Your Order' - the following message is displayed: We can't complete your order because you don't have a payment method set up.
4. The console does not show any errors.
5. This happens in magento community: 2.2.2

### Expected result

1. Would expect the payment options to be displayed and functional

### Actual result
1. Payment options are not displayed as explained above

On latest Chrome (OSX) - server nginx/ubuntu/16.4

**Comment by orlangur** [comment]
@baskuis which payment methods did you enable? Looks like none of them supports multishipping.

**Comment by magento-engcom-team** [comment]
Hi @baskuis 
Thank you for report.
Please note the previous comment and tell if it helped you.

**Comment by ishakhsuvarov** [comment]
@baskuis Multiple address checkout currently does not support most of the online payment methods

**Comment by baskuis** [comment]
Thanks @orlangur - could you let me know which payment methods support multi-shipping? I have creditcard (authorize.net) and paypal express and direct enabled currently.

**Comment by magento-engcom-team** [comment]
@baskuis Payment methods with 
`<allow_multiple_address>1</allow_multiple_address>` in `payment.xml` are supposed to be available for multishipping.

**Comment by armstrongedward** [comment]
<allow_multiple_address>1</allow_multiple_address> tried the code not able to achieved it, any other way to do that

**Comment by armstrongedward** [comment]
let me know which payment methods support multi-shipping? I have EBS and paypal express and direct enabled currently.

**Comment by YevSent** [comment]
@baskuis, @ArmstrongEdwardraj Magento Multishipping doesn't support built-in online payment methods.

To make custom payment integration available for Multishipping you need to add
```xml
<payment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Payment:etc/payment.xsd">
    <methods>
        <method name="payment_code">
            <allow_multiple_address>1</allow_multiple_address>
        </method>
    </methods>
</payment>
```
to `payment.xml` file in your payment module. Also, `payment_code` should be the payment method code for your integration.
To make integration usable, you might need to add custom js components for payment form.
If you want to add Braintree, PayPal, Authorize.net or other built-in integrations to Multishipping, they won't work without customizations. It's not enough to add them to `payment.xml`.

Starting from Magento 2.2.4 release, Cybersource payment integration will be available for Multishipping.
Also, we improved Multishipping components to simplify integration with online payment solutions.

**Comment by baskuis** [comment]
Hi @joni-jones, having luck .. some luck after upgrading to 2.2.4 and adding a payment.xml in our payment module.

Currently the issue I'm facing is that after payment method:
(*) Credit Card
     We'll ask for your payment details before you place an order.

However payment details are never prompted for - and order are placed upon clicking 'Go To Review Your Order' -> 'Place Order'

Seems like we missing an interstitial page - and looked through the sample payment gateway: https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway but I'm not able to find a pattern to apply here for multiple shipping addresses payment.

Would you be able to point us to an example of sorts? Thanks again for your help thus far - making progress. :-)

**Comment by baskuis** [comment]
@ArmstrongEdwardraj - have you had luck getting your payment module working with multiple shipping addresses?

**Comment by testmagento2** [comment]
I don't get why Magento not giving a solution for Payment methods on multi shipping addresses, for credit card.

**Comment by orlangur** [comment]
@testmagento2 what do you mean? Such support should be implemented for each payment method separately.

**Comment by cdbessig** [comment]
@orlangur if magento wants to compete, it should ensure that modules baked into core function with other core components.  To provide a module that doesn't work with other core features and then point to module developers or payment vendors to fix it, that's weak and not something merchants want to hear.

**Comment by orlangur** [comment]
@cdbessig I understand that. So?
