### ISSUE TITLE
Magento 2.2.2 Warning: Invalid argument supplied for foreach() in /var/www/html/brasi-magento2/vendor/magento/module-catalog-widget/Block/Product/ProductsList.php on line 262

### ISSUE THREAD

**Issue by adil26** [magento/magento2#14097]
Hello Guys,
I have upgraded magento version from 2.1.7 to 2.2.2.

When I go to category page this issue occur:
Warning: Invalid argument supplied for foreach() in /var/www/html/brasi-magento2/vendor/magento/module-catalog-widget/Block/Product/ProductsList.php on line 262

**Comment by paragpadsumbiya** [comment]
@adil26 thank you for your report.
Please use the issue reporting guidelines to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:

 Preconditions: Magento version
 Steps to reproduce
 Expected result
 Actual result

**Comment by magento-engcom-team** [comment]
@adil26, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by saphaljha** [comment]
Try to disable full page cache.

**Comment by joshuabromero** [comment]
I also ran into this issue. It seems to come from the following method on line 252:

```
protected function getConditions()
    {
        $conditions = $this->getData('conditions_encoded')
            ? $this->getData('conditions_encoded')
            : $this->getData('conditions');

        if ($conditions) {
            $conditions = $this->conditionsHelper->decode($conditions);
        }

        foreach ($conditions as $key => $condition) {
            if (!empty($condition['attribute'])
                && in_array($condition['attribute'], ['special_from_date', 'special_to_date'])
            ) {
                $conditions[$key]['value'] = date('Y-m-d H:i:s', strtotime($condition['value']));
            }
        }

        $this->rule->loadPost(['conditions' => $conditions]);
        return $this->rule->getConditions();
    }
```

The problem occurs if the `$conditions` variable is null. The `foreach` statement needs to be included in the `if` statement above it, otherwise you get the invalid argument error.

**Comment by viperet** [comment]
Had this issue after upgrade to 2.2, by adding an empty condition to ProductList:
```
    echo $this->getLayout()
        ->createBlock("Magento\CatalogWidget\Block\Product\ProductsList")
        ->setDisplayType("all_products")
        ->setProductsCount("999")
        ->setTemplate("Magento_Theme::html/grid.phtml")
        ->addColumnCountLayoutDepend('1column', 6)
        ->setConditionsEncoded("^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^]^]") 
        // ^ added this line
        ->toHtml();
```

**Comment by sean-breeden** [comment]
Not sure why this was closed. This is still an issue in 2.2.x
