### ISSUE TITLE
Issues during installation

### ISSUE THREAD

**Issue by graemelambert** [magento/magento2#1409]
I had to make a few tweaks to get Magento 2 to install on my server, here is a list of them:

nginx.conf.sample:

    root $MAGE_ROOT/pub;
    changed to
    root $MAGE_ROOT;

    location /static/ {
    changed to
    location /pub/static/ {

    all rewrites to /static.php changed to /pub/static.php

    all locations for /media/* changed to /pub/media/*

I started getting 500 Internal Server Error at 70% of the installation so I read the php.ini.sample which advised changing the max_execution_time to 18000 (5 hours?!) which resolved that issue but I then started to get a gateway timeout at 100% - the installation completed in the console but didn't get to the completion page.  So I changed default_socket_timeout and mysql.connect_timeout from 60 to 600 and that resolved that problem; not sure which one was the culprit.

Finally, I chose to have both frontend and backend secure but all of my static content wasn't loading on the frontend as it was trying to load it from http:// rather than https://.  The cause of this was "Secure Base URL for Static View Files" and "Secure Base URL for User Media Files" were not populated in the Stores -> General -> Web area so I changed them to be {{secure_base_url}}pub/static/ and {{secure_base_url}}pub/media/ respectively.

As I've had to do this installation quite a few times to get it to work, each time I've had to drop the database and create it again; it would be good if the installation script did that for you if it recognised that you were trying to continue with the installation after a previous attempt.

Hope this feedback helps.

**Comment by xcomSteveJohnson** [comment]
magento setup:uninstall will drop and re create the database, or there is an optional --cleanup-database flag for magento setup:install that will do it also.

Thanks for the nginx info, it will come in handy.

**Comment by graemelambert** [comment]
I didn't know that, but I was using the web interface to do the install if that helps.

**Comment by xcomSteveJohnson** [comment]
I see. The web interface doesn't have those options but if you don't mind using the CLI, magento setup:uninstall does what you want. (Or you can use MySQL.) FWIW, to re create the DB, check out http://bit.ly/1GCDMG5
