### ISSUE TITLE
Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed after upgrade version from Magento 2.1.7 to 2.2.2

### ISSUE THREAD

**Issue by adil26** [magento/magento2#14093]
Hello guys,

After my upgrade from 2.1.7 to 2.2.2, I had fetching this error. The problem is in the front end. I encounter the following problem:

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed.
Line: 720

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed.
Line: 720

**Comment by magento-engcom-team** [comment]
@adil26, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by orlangur** [comment]
@adil26 you need to fix invalid layout XML so that it corresponds to XSD schema, please check https://github.com/magento/magento2/issues/13829 or other similar issues for details.

**Comment by magento-engcom-team** [comment]
@adil26, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
