### ISSUE TITLE
Varnish configuration prevents caching of any FrontController content

### ISSUE THREAD

**Issue by hamdrew** [magento/magento2#14103]
### Preconditions
1. Magento 2.2.2
2. Varnish 4.0.5

### Steps to reproduce

1. Configure Varnish as detailed in the [Varnish Config Guide](http://devdocs.magento.com/guides/v2.2/config-guide/varnish/config-varnish.html)
1. When configuring Varnish, ensure you are using a fresh export of VCL
1. Magento is set to developer mode
1. Open Developer Tools in your favorite browser to inspect response headers
1. Run the`varnishlog` command on your Varnish server.
1. Run `magento cache:clean` to ensure the Varnish cache has been purged.

### Expected result

1. Visit a frontend page, such as the store homepage. Varnish should MISS. (Inspect Varnish logs and X-Magento-Cache-Debug header in response)
1. Refresh the page.  Varnish should HIT

Note: This was the behavior we saw with an older VCL from Magento 2.1

### Actual result

1. Varnish continually MISSes on any content served by the FrontController controller.

### Technical Analysis

I believe I know the reason for this behavior.  There was a change to the suggested VCL configuration that will tell Varnish the page is uncacheable if the back-end response's **Cache-Control** header's value has *no-cache* or *no-store* in it.  See 9da1f6ff1647610224bd0f55b0207a9c538cadef for when this change occurred.

On [line 53 of Magento\Framework\App\FrontController](https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/App/FrontController.php#L53), "no cache" headers are set.  From my understanding, this is done to ALL content that goes through this controller.  The original intention of this was to tell the user's browser to not cache locally. However, now it's telling Varnish not to cache!

**Comment by hamdrew** [comment]
I'm closing this as I haven't fully tested, and my theory is incorrect.

**Comment by manelio** [comment]
Now I have the same theory. What way were you wrong?

In `Magento\Framework\App\FrontController` there's a call to `$this->response->setNoCacheHeaders(),` in the block

```
$actionInstance = $router->match($request);
if ($actionInstance) {
    $request->setDispatched(true);
    $this->response->setNoCacheHeaders();
```

that calls to `$this->setHeader('cache-control', 'no-store, no-cache, must-revalidate, max-age=0', true);`.

And in the generated vcl there's this fragment:

```
   if (beresp.ttl <= 0s ||
       beresp.http.Surrogate-control ~ "no-store" ||
       (!beresp.http.Surrogate-Control &&
       beresp.http.Cache-Control ~ "no-cache|no-store") ||
       beresp.http.Vary == "*") {
       # Mark as Hit-For-Pass for the next 2 minutes
        set beresp.ttl = 120s;
        set beresp.uncacheable = true;
    }
```

It looks like there's no chance for a page to be cached.

Thanks!

**Comment by gecon** [comment]
Also on the same, I see Varnish continually MISSes.

What seems working (not extensively tested):

```
if (beresp.ttl <= 0s ||
        beresp.http.Surrogate-control ~ "no-store" ||
        !beresp.http.Surrogate-Control || beresp.http.Vary == "*") {
        # Mark as Hit-For-Pass for the next 2 minutes
        set beresp.ttl = 120s;
        set beresp.uncacheable = true;
}
```

**Comment by webloft** [comment]
This issue is still top referenced in Google and confusing, so let's clarify it:

Varnish:
- TTL is determined by `max-age` directive in `cache-control` header for `beresp.ttl`

Magento:
- `setNoCacheHeaders()` is called every time on the front controller, it sets `max-age` directive to 0 and all directives to not cache the page by proxies:

`cache-control: no-store, no-cache, must-revalidate, max-age=0`

- If a page is cachable the page cache module will call `setPublicHeaders()` which will overwrite the `cache-control` header and sets `max-age` directive again, default is 86400:

`cache-control: public, max-age=86400, s-maxage=86400`

A common cause for non-cachable pages are layout blocks with attribute `cacheable="false"` or code modifications on a block model which controls cache parameter.
