### ISSUE TITLE
Front controller reached 100 router match iterations Issue

### ISSUE THREAD

**Issue by balwant20** [magento/magento2#14102]
I couldn't resolve this issue.

i am using Magento 2.1.7

this  issue occurs when i disabled products in admin backend, visit the product page on the frontend (see a Front controller reached 100 router match iterations) ..

Steps to reproduce
1. Disable product / page in the backend.
2. Visit product/page in frontend .
3. get  Front controller reached 100 router match iterations

**Comment by magento-engcom-team** [comment]
@balwant20, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by balwant20** [comment]
@magento-engcom-team  which version you produced this error?
i am talking about Magento 2.1.7

**Comment by magento-engcom-team** [comment]
@balwant20, we try to reproduce this issue on 2.1.7
Steps:
1. Create simple product s1.
2. Navigate to storefront http://magento-domain/s1.html
3. Navigate to admin .
4. Disable product s1.
5. Save product.
6. Navigate to storefront http://magento-domain/s1.html
404 Not Found page shows up.
Please correct our steps, in case they are wrong, or try to reproduce this issue on clean installation.

**Comment by balwant20** [comment]
thanks for your support @magento-engcom-team 
Happy Coding..!!!

**Comment by ishakhsuvarov** [comment]
@balwant20 Per your comment I assume that ticket may be closed now.
Please reopen if the issue persists and provide clear steps to reproduce on the latest Magento version.
Thank you.

**Comment by magento-engcom-team** [comment]
@balwant20, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](https://i-14102-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14102-2-3-develop.instances.magento-community.engineering/admin](https://i-14102-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
