### ISSUE TITLE
Password strength calculation issue while reset the password. 

### ISSUE THREAD

**Issue by Sathishkumar8731** [magento/magento2#14116]
### Preconditions

1.  Magento 2.2.2
2. 

### Steps to reproduce

1.  Remove the Newsletter Subscriber block in default.xml on Theme module
2. Now, Go to login page and give forgot password
3. After getting email notification for password reset, click on it
4. You will be redirected to domainname/customer/account/createpassword/
5. Now you can find the issue that Password strength calculation will not work and throw error in console. 

### Expected result

1.  In console, below error message is showing
password-strength-indicator.js:78 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at $.(anonymous function).(anonymous function)._calculateStrength

### Actual result

1. Need to know the reason why you are  email value is checking for password strength validation.

**Comment by magento-engcom-team** [comment]
@Sathishkumar8731 , thank you for your report. Please add more detail information about first step (Remove the Newsletter Subscriber block). On folder app/code/Magento/Theme/view/frontend/layout/default.xml this block is absent.

**Comment by Sathishkumar8731** [comment]
Hi Team,

**To disable the Newsletter Subscriber.**

1) Go to the file path: vendor/magento/module-newsletter/view/frontend/layout/default.xml

2) Add the below code in <body> of default.xml file.

referenceBlock name="form.subscribe" remove="true"

3) Run all the commands, then check whether "Newsletter subscriber Email field" is remove on Footer.

**To  go the password reset page** 

4) Now, Go to login page and give forgot password

5) After getting email notification for password reset, click on it

6) You will be redirected to domainname/customer/account/createpassword/

7) Now you can find the issue that Password strength calculation will not work and throw error in console.

**Comment by magento-engcom-team** [comment]
@Sathishkumar8731, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by tprocter-ldg** [comment]
This error also happens on the '/customer/account/create' page with the Newsletter Subscriber block still enabled. 

Magento 2.2.0

**Comment by rainashikha** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@rainashikha thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by solwininfotech** [comment]
I am working on this at #dmcdindia

**Comment by solwininfotech** [comment]
@Sathishkumar8731 

Hi,

We have reproduced the issue in Magento 2.2.3 we found the issue.

Again we try to reproduce the issue in “2.2-develop”, we are not able to reproduce the issue.
Looks like its already fixed in magneto “2.2-develop”.

Thanks

**Comment by dankhrapiyush** [comment]
Hi @Sathishkumar8731 
This is actually a duplicate of [#13429](https://github.com/magento/magento2/issues/13429) and it has been fixed by @serhii-balko in 2.3-develop branch.

Related commit(s):
 - [99b32cf0595a1a8c0ef309d150c7ee350c5e2c83](https://github.com/magento/magento2/commit/99b32cf0595a1a8c0ef309d150c7ee350c5e2c83)
 - [fd5e0b5532b56451cadcc03353bae2ff54838fcc](https://github.com/magento/magento2/commit/fd5e0b5532b56451cadcc03353bae2ff54838fcc)

**Comment by JulianBour** [comment]
#mhlej18

**Comment by magento-engcom-team** [comment]
@JulianBour thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by LuckAlexander** [comment]
#mhlej18

**Comment by magento-engcom-team** [comment]
@LuckAlexander thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ghost** [comment]
#mmi18

**Comment by ZhukValentina** [comment]
#squashtoberfest

**Comment by magento-engcom-team** [comment]
@ZhukValentina thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by swnsma** [comment]
Can not reproduce.
Look like issue already fixed.
Please re-open and provide steps to reproduce.
