### ISSUE TITLE
No error message shown when purchase qty mismatch the 'Qty Increments' setup

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1411]
Expected result is to see an error message shown up when the purchase quantity mismatch the 'Qty Increments' configuration. It works as expected for updating cart, except for adding to cart.

```0.74.0-beta14``` ```Default mode```

**Update Cart Btn:**
![2](https://cloud.githubusercontent.com/assets/11070293/8356726/34d903ca-1b81-11e5-8a37-edf72a17962e.PNG)
![4](https://cloud.githubusercontent.com/assets/11070293/8357027/eab4f7fc-1b82-11e5-8e62-dd743c68694c.PNG)

**Add to Cart Btn - No error:**
![5](https://cloud.githubusercontent.com/assets/11070293/8357130/6db8ca84-1b83-11e5-8df8-c32be69894c3.PNG)

**Add to Cart (Group Product) - No error:**
![6](https://cloud.githubusercontent.com/assets/11070293/8357637/2e5a8c1c-1b86-11e5-9d0e-c8f0a963acf8.PNG)

**Advance Inventory configurations:**
![3](https://cloud.githubusercontent.com/assets/11070293/8356643/c76887e8-1b80-11e5-9229-41e6d91049ef.PNG)

**Comment by kokoc** [comment]
@adzminz Thank you for reporting the issue. We will fix the problem and get back to you once we have the working code. Internal reference: MAGETWO-39475

**Comment by vpelipenko** [comment]
@adzminz, fix is available in 1.0.0-beta. Please, check the fuxand let us know if it works for you.

**Comment by adzminz** [comment]
@vpelipenko, it's working fine. Thank you.
