### ISSUE TITLE
Update category name via API REST

### ISSUE THREAD

**Issue by cpjeanpaul** [magento/magento2#14119]
### Preconditions

1. Magento 2.1.10

### Steps to reproduce

1. CREATE a Category via API REST
2. UPDATE the name of the same category via API REST

### Expected result

1. show the new name of the category in the store menu
2. show the new name of the category in category tree (backoffice)

### Actual result

1. The updated name is displayed by GET via API REST
2. The updated name is displayed in the store menu
3. THE UPDATED NAME IS NOT DISPLAYED in category tree (backoffice). It keeps old name.

**Comment by AaronKaa** [comment]
This could be related to #14080

**Comment by magento-engcom-team** [comment]
@cpjeanpaul, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Steps to reproduce**

1. CREATE a Category via API REST **POST /V1/categories**
> {
  "category": {
    "name": "CAT",
    "is_active": true
  }
}

2. UPDATE the name of the same category via API REST **PUT /V1/categories/3**
> {
      "category": {
    "name": "CATnew",
    "is_active": true
  }
}

**Comment by mrodespin** [comment]
I think this is not an issue is just a documentation problem.

If you don't specify any store code the API will update the data in the same store that you are using in the API, in a regular magento installation, it means store code 1 or default.

This means that de admin store will keep the older information about the category. If you want to change the information in the admin too is necessary to use the following endpoint.

rest/**all**/V1/categories/:id/

The bold param is the store code.

- **All** for update the category in all stores
- **Storecodeview** for update the category only in that store view

It happens the same in product API update logic.

**Comment by mrodespin** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@mrodespin thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.
