### ISSUE TITLE
PHP short echo is an anti-pattern and should be removed

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/magento2#14111]
The PHP short echo used widely in PHTML templates cannot be commented out easily:

```
<?= //$block->getChildHtml('will_not_work') ?>

<?= /*$block->getChildHtml('will_not_work')*/ ?>
```

You must star comment the entire declaration, which is tedious:

```
<?php /*
<?= $block->getChildHtml('will_work') ?>
*/ ?>
```

And also breaks another necessary commenting use case:

```
<?php /*
I should be commented out, and I am.

<?php /*
<?= $block->getChildHtml('will_work') ?>
*/ ?>

I should be commented out, but I won't be.
*/ ?>
```

The PHP short echo should have been considered an anti-pattern because it restricts commenting, which is a hallmark of good code.

The standard echo is far more flexible and barely more verbose:

```
<?php //echo $block->getChildHtml('will_work') ?>

<?php /*echo $block->getChildHtml('will_work')*/ ?>

<?php /*
I should be commented out, and I am.

<?php //echo $block->getChildHtml('will_work') ?>

I should be commented out, and I am.
*/ ?>

**Comment by brendanfalkowski** [comment]
Found a workaround. Closing.

Reference: https://twitter.com/mostlymagic/status/974154073736753152

```
<?//= $block->getChildHtml('will_work') ?>
```

**Comment by brendanfalkowski** [comment]
Actually that's not a viable workaround because most servers disable short tags (but apparently not short echo.

**Comment by Igloczek** [comment]
It's part of PSR-1 and shouldn't be considered as a anti-pattern.
https://www.php-fig.org/psr/psr-1/

**Comment by ishakhsuvarov** [comment]
@brendanfalkowski Thank you for reporting.
This is intentionally implemented this way. You may use https://github.com/magento/magento2/pull/1563 for reference and more information.

Closing as non-issue

**Comment by brendanfalkowski** [comment]
I guess the PSR people never comment out code.

Seems like a valid need but ¯\_(ツ)_/¯
