### ISSUE TITLE
remove all @deprecated code or provide better guidance

### ISSUE THREAD

**Issue by fooman** [magento/magento2#1413]
So far not all mentions of @deprecated have an internal ticket assigned (at least in the code comments). The below are the results of my search:

https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product/Type/Price.php#L553

https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product/Type/Price.php#L567

https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogSearch/Model/Resource/Search/Collection.php#L14

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Block/Address/Renderer/DefaultRenderer.php#L98

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Block/Address/Renderer/RendererInterface.php#L41

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Address.php#L122

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Customer.php#L364

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Customer.php#L807

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Customer.php#L1280

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Session.php#L205

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Session.php#L245

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Session.php#L273

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Address/AbstractAddress.php#L448

https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Address/AbstractAddress.php#L487

https://github.com/magento/magento2/blob/develop/app/code/Magento/Theme/Model/View/Design.php#L109

Some methods have guidance on what the new approach should be - however not all have this and it would be great to include better guidance for all of them what to use instead (if they are not removed in the very near term).

**Comment by Vinai** [comment]
:+1:

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-39438

**Comment by piotrekkaminski** [comment]
Ticket is closed. deprecated either removed or alternative method documented.
