### ISSUE TITLE
extension attributes on StoreInterface object not set

### ISSUE THREAD

**Issue by EliasZ** [magento/magento2#14135]
### Preconditions
Magento 2.2.3

### Steps to reproduce
Add an extension attribute for `StoreInterface`:

    <extension_attributes for="Magento\Store\Api\Data\StoreInterface">
        <attribute code="some_attribute" type="integer" />
    </extension_attributes>

Add this column to the `store` table with an update/upgrade/install script.

### Expected result
Whenever retrieving a `StoreInterface` object, `some_attribute` should be available through `[implementation of StoreInterface]->getExtensionAttributes()`.

### Actual result
It is not. Instead, it is only available through `->getData('some_attribute')`. I added a `StoreRepository` plugin which does add it to the extension attributes on `afterGet`, but turns out I would need to do this for each and every possible way `StoreInterface` objects can be retrieved.

The interfaces and implementations (for example `Magento\Store\Api\Data\StoreExtension`) are properly generated, but it is never filled with `setCustomAttributes`. `setCustomAttributes` on `Magento\Store\Model\Store` is never called.

**Comment by ishakhsuvarov** [comment]
Hi @EliasZ 
Thank you for reporting.

The described Actual Result is the correct Magento behavior. It is also documented in [developer documentation](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.html) that a set of plugins should be implemented in order to support an extension attribute.

You may find some additional information with examples on how this is implemented in Multi Source Inventory project: https://github.com/magento-engcom/msi/wiki/SourceItem-Entity-Extension#adding-new-data-interface-representing-allocated-space

**Comment by EliasZ** [comment]
@ishakhsuvarov Thank you for your answer. I would have expected this to work out of the box for primitive types like integers, strings and such. Only when you add a complex type you need to populate it yourself.

When using the method suggested, there is no instance of `StoreExtensionInterface` injected by core Magento meaning we should add this ourselves for each `AbstractExtensibleModel` which may or may not have a pre-populated `\Magento\Framework\Api\ExtensionAttributesInterface`? With a `afterGetExtensionAttributes` plugin as the documentation suggests...

Seems counter productive?

**Comment by ishakhsuvarov** [comment]
> When using the method suggested, there is no instance of `StoreExtensionInterface` injected by core 

In this case you may use auto generated `StoreExtensionInterface` to create one.
You may use `afterGetExtensionAttributes` plugin as documentation suggests or check if it's already exists when attempting to set data to the extension.

**Comment by ishakhsuvarov** [comment]
Unfortunately I have to close this issue as Github issue tracker is intended to be used only for Magento 2 core technical issues.
If you are looking for the discussion on the subject https://magento.stackexchange.com/ may be a more suitable place.

Thank you.

**Comment by EliasZ** [comment]
@ishakhsuvarov Alright, seems like a weird design decision to make extensions responsible of handling the injection of  `ExtensionAttributesInterface` on `AbstractExtensibleModel`. Would make more sense to include it by default so we do not always require an extra interceptor to make sure it is there.
