### ISSUE TITLE
Pagination is not working Properly when category product collection in list page

### ISSUE THREAD

**Issue by aathil-ali** [magento/magento2#14133]
### Preconditions

1. Magento 1.9.3.2
2. PHP 7.022 ,Mysql 5.7

### Steps to reproduce

 $todayStartOfDayDate  = Mage::app()->getLocale()->date()
            ->setTime('00:00:00')
            ->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);

        //special to date
        $todayEndOfDayDate  = Mage::app()->getLocale()->date()
            ->setTime('23:59:59')
            ->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);

        $_productCollection = Mage::getModel('catalog/category')->load('241')->getProductCollection()->addAttributeToSort('created_at', 'DESC');
        //filter special from date
        $_productCollection->addAttributeToFilter('special_from_date', array(
                                                                            'date' => true, 'to' => $todayEndOfDayDate)
                                                                            );
        //filter special to date
        $_productCollection->addAttributeToFilter('special_to_date', array('or'=> array(
                                                                    0 => array('date' => true, 'from' => $todayStartOfDayDate),
                                                                    1 => array('is' => new Zend_Db_Expr('null')))
                                    
                                                                    ), 'left');

### Expected result

1. Do not Load all products in one page

### Actual result

1. [S
![shot1](https://user-images.githubusercontent.com/22939033/37512273-a8dae0e8-2927-11e8-9aa6-3f873230f8d9.png)
creenshot, logs]

**Comment by magento-engcom-team** [comment]
Hi @aliaathil 
Thank you for reporting. 

The GitHub issue tracker is intended for Magento 2 Core technical issues only.
Please refer to the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
