### ISSUE TITLE
Magento 2.2.3 widget_form_element_dependence textarea required

### ISSUE THREAD

**Issue by pjw345** [magento/magento2#14148]
If you have a form that has a widget_form_element_dependence and one of the fields is a textarea field that is required in one of the sets, it doesn't ignore the required field if it's currently not in the active list of fields

### Preconditions

1.  Magento 2.2.3
2. PHP 7.0.28

### Steps to reproduce

1. Create a Form with a widget_form_element_dependence
2. Form has for example a select and various text fields and a textarea
3. The text fields and text area are Required input

### Expected result

1. The dropdown toggles which fields are active and which fields are hidden
2. If the text fields that are Required are not part of the current active selection they are not required and hence ignored. 

### Actual result

1. If a textarea field is Required and is not part of the current active selection it is not ignored, in fact flagging a hidden error message.

$token = $fieldset->addField('token', 'textarea', array(
            'name' => 'token',
            'label' => __('Token'),
            'title' => __('Token'),
            'class' => 'input-text',
            'required' => true,
            'value' => $this->getCredentials(\Company\Integration\Model\Channel::ebayAuthToken)
        ));

**Comment by ghost** [comment]
Hi @pjw345 , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@pjw345, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
