### ISSUE TITLE
Request for some additional functionality

### ISSUE THREAD

**Issue by 5mehulhelp5** [magento/magento2#1414]
Hello i think if we can add google rich snippet in magento 2 then it would be great for magento user.

Thanks

**Comment by adzminz** [comment]
#233

**Comment by ilol** [comment]
@5mehulhelp5, agree with closing this request since the suggested feature is within #233 ?

**Comment by 5mehulhelp5** [comment]
ok thanks you can close now this ticket no problem.

Thank you very Much.
