### ISSUE TITLE
Unable to Save Simple Simple Product after Converting it to Configurable and Back to Simple again .

### ISSUE THREAD

**Issue by nmalevanec** [magento/magento2#14141]
### Preconditions
1. Magento 2.2.3

### Steps to reproduce
1.  Navigate to admin.
2. Start creating simple product.
3. Add name, sku and price(double check price is entered)
4. Open "Configurations" tab.
5. Press "Create Configurations" button.
6. Go through process and generate some configurations.
7. After configurations have been generated, remove all products from "Current Variations" grid, so product become simple again.
8. Press Save button.

### Expected result
1. Product saved as simple product.

### Actual result
1. Unable to save product. "The value of attribute "price" must be set" message appear. 
Field price is disabled.

**Comment by magento-engcom-team** [comment]
@nmalevanec 
We've acknowledged the issue and added to our backlog.
