### ISSUE TITLE
Change product position under category doesn't works

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#14159]
### Preconditions

1. Magento 2.1.8
2. PHP 7
3. nginx
4. mysq
5. varnish 

### Steps to reproduce

1. Login to admin panel 
2. Set all indexers in "Update By Schedule" mode
3. Go to category with already assigned products
4. Change product position

### Expected result

1. Product position is changed on category view page on FE

### Actual result

1. Product position is not changed on category view page on FE

Seems catalog_category_product_index never gets invalidated when it in "Update By Schedule" mode.
Seems problem here:
![image](https://user-images.githubusercontent.com/9048430/37554592-cbab01ea-29e3-11e8-8e11-477e3f5dbcdd.png)

**Comment by kvydiuk** [comment]
Also seems this issue causes all indexers (catalogsearch_fulltext, catalog_product_price_indexer, etc)

**Comment by magento-engcom-team** [comment]
@breg-13 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release(for 2.1.x is 2.1.12).

**Comment by kvydiuk** [comment]
@magento-engcom-team , thanks! But seems i figured out what was the problem. Please close this ticket

**Comment by magento-engcom-team** [comment]
@breg-13 Thank you for the update. Closing.
