### ISSUE TITLE
2.2.3 CE: error on tax rates step for setup:perf:generate-fixtures

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#14155]
### Preconditions
1. Magento  2.2.3 CE (clear composer installation)
2. PHP 7.1.15-1, mysql  Ver 15.1 Distrib 10.2.13-MariaDB

### Steps to reproduce
1.  try generate extra-large set from setup:perf:generate-fixtures

### Expected result
1. Data will be successfuly generated

### Actual result
1. Error on "Generating tax rates..." step.
https://drive.google.com/file/d/1QMrCHu9godNmwKv89aXAGMXxksyVugVn/view?usp=sharing

**Comment by ishakhsuvarov** [comment]
Hi @sergei-sss 
Thank you for reporting.
We have tried to reproduce with the clean installation and it didn't fail.

Are you attempting to generate entities on a clean database or does it have some data already? Did you use the store while generating? Maybe some cron jobs?

Also, we advise to do all performance-related tasks (including generation) with xdebug extension disabled.

**Comment by sergei-sss** [comment]
Ok, I will try generate again without xdebug.

**Comment by ishakhsuvarov** [comment]
@sergei-sss Thanks. You may also try to launch generation process again, it is supposed to continue where it stopped.

**Comment by sergei-sss** [comment]
I suppose the problem was in the temporary installed sample data on the test host.
`bin/magento sampledata:deploy`
`bin/magento sampledata:remove`

Without this commands on the new magento installation the tax rates generation was successfully completed (with enabled xdebug).
It seems, the magento doesn't fully clean sample data. You can check it and mark it as a bug or close this ticket.

**Comment by kandy** [comment]
Performance toolkit has been developed to run on clean Magento so I close tickets as irrelevant
