### ISSUE TITLE
Cannot Import Products with Default Import Tool

### ISSUE THREAD

**Issue by pblicharz** [magento/magento2#14163]
I am having a problem with product import feature on magento 2.2.2. When I import properly configured file, I get no such entity.

please see: https://www.screencast.com/t/CoVrtxpmW

Could you please assist?

Magento 2.2.2
PHP 7.0
New Instal
Theme from Template Monster #62000

### Steps to reproduce
1. please see: https://www.screencast.com/t/CoVrtxpmW

### Expected result
1. Usually the import will check for data errors, return a value with error on particular lines, then allow import. 

### Actual result
1. please see: https://www.screencast.com/t/CoVrtxpmW

**Comment by ghost** [comment]
@pblicharz, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit the issue and reopen it.
