### ISSUE TITLE
Braintree online refund issue

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#14175]
### Preconditions

1. Magento 2.1.8
2. nginx/1.10.3
3. 10.0.34-MariaDB
4. PHP 7.0.22

### Steps to reproduce

1. Create two websites
2. Set two different Braintree account credentials for different websites
3. Place order with Braintree payment method in website that is not default
4. Go to order in admin panel
5. Select "Invoices" tab
6. Press "View" invoice
7. Go to "Credit Memo"
8. Press "Refund"

### Expected result

1. Successful message is displayed and refund is processed in Braintree

### Actual result

1. Error is appears

Investigation showed for me that credentials for default store is initializes while performing refund request to Braintree. But order and invoice actually relates to not default (another) website.

**Comment by magento-engcom-team** [comment]
@breg-13  , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

**Comment by YevSent** [comment]
@breg-13, this issue was fixed in Magento 2.1.11 (internal ticket `MAGETWO-71185`). http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.11CE.html#payment-methods

**Comment by kvydiuk** [comment]
@joni-jones, thanks!
