### ISSUE TITLE
Items in minicart are not cleared after successful placing an order

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1418]
```0.74.0-beta15``` ```Default mode```

![1](https://cloud.githubusercontent.com/assets/11070293/8390395/1ef64004-1cbc-11e5-87ff-c4d9780d89b5.PNG)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-37603. Issue is already fixed by internal team and will be available on public GitHub soon.

**Comment by vpelipenko** [comment]
Closed. @adzminz, if you still have it reproduced, please, feel free to reopen this issue.

**Comment by CNanninga** [comment]
I have still seen this exhibited in 2.0.9.
