### ISSUE TITLE
create a partial shipment

### ISSUE THREAD

**Issue by shweta1234567** [magento/magento2#14197]
HI All,

I Want to create a partial shipment using rest API can someone help to find the JSON by which I can create the partial shipment.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by shweta1234567** [comment]
Hello 

Still I am waiting the solution can you please help me to find the solution.

**Comment by shweta1234567** [comment]
Hello,

Still, I am waiting for the solution can you please help me to find the solution.
