### ISSUE TITLE
Category URL rewrite generation does not set nested categories reliably

### ISSUE THREAD

**Issue by allisonlawrencels** [magento/magento2#14202]
### Preconditions

1. Magento version 2.2.3

### Steps to reproduce

1. Create a category structure with categories to at least 3 levels (Root > Cat level 1 > Cat level 2 > Cat level 3). Create the level 2 AFTER the level 3, so its database ID is higher.
2. Change the URL of the Level 1 category, uncheck "Create Permanent Redirect for old URL" (it is easier to see the results this way)
3. See resulting URL rewrites. Some contain the original Level 1 category path, and some contain the new path.

### Expected result

1. All children categories should be updated with the new URL path.

### Actual Result 
2. Cat level 3 URL path not updated.

### Solution
The Magento\CatalogUrlRewrite\Model\Category\ChildrenCategoriesProvider::getChildren() function should be updated to include a sort by level:

```
    public function getChildren(Category $category, $recursive = false)
    {
        return $category->isObjectNew() ? [] : $category->getResourceCollection()
            ->addAttributeToSelect('url_path')
            ->addAttributeToSelect('url_key')
            ->addAttributeToSelect('name')
+            ->setOrder('level', 'asc')
            ->addIdFilter($this->getChildrenIds($category, $recursive));
    }
```

**Comment by ghost** [comment]
@allisonlawrencels, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by madbounce** [comment]
Hey @allisonlawrencels, basically not clear how we can create Level 3 before Level 2 and get needed 
structure that you provided. 
Currently I checked current flow on Magento branch 2.3-develop and issue not reproduced (all url rewrites was regenerated according to url that was set for Cat Level 1).

Closed for now.
