### ISSUE TITLE
Product Order without position doesnt change direction

### ISSUE THREAD

**Issue by jonathan-martz** [magento/magento2#14226]
### Preconditions
Magento 2.2.2
http://demoshops.splendid-internet.de/magento/magento2d/gear/bags.html

### Steps to reproduce
![v1-backend](https://user-images.githubusercontent.com/20771653/37702986-88b844c4-2cf4-11e8-8f00-80b62eaf8152.png)

![vs1-before](https://user-images.githubusercontent.com/20771653/37702994-8e895104-2cf4-11e8-985a-360fca3ba68e.png)

1. Change Direction

![v1-after](https://user-images.githubusercontent.com/20771653/37703020-927ee076-2cf4-11e8-811f-048a67c0b889.png)

### Expected result
Before there are the products:
9. Fusion Backpack
8. Impulse Duffle
7. Voyage Yoga Bag
6. Compete Track Tote
5. Savvy Shoulder Tote
4. Endeavor Daytrip Backpack
3. Driven Backpack
2. Overnight Duffle
1. Push it Messenger Bag

### Actual result
1. Push it Messenger Bag
2. Overnight Duffle
3. Driven Backpack
4. Endeavor Daytrip Backpack
5. Savvy Shoulder Tote
6. Compete Track Tote
7. Voyage Yoga Bag
8. Impulse Duffle
9. Fusion Backpack

**Comment by orlangur** [comment]
@jonathan-martz please provide more details. When all products have the same position value observed behavior for inverted position sorting is correct.

**Comment by jonathan-martz** [comment]
As User i would expect that the Order changes when i change the direction or he will think that something isnt working, because he clicks and nothing changed.

**Comment by orlangur** [comment]
This is misconfiguration by merchant and needs to be solved on Admin UI side.

When order of products is essential, different values for position should be set. Otherwise any order in any sorting direction is acceptable.
