### ISSUE TITLE
Magento\Email\Model\Template\Filter Comment vs Code

### ISSUE THREAD

**Issue by fooman** [magento/magento2#1423]
The comment here 
https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/Template/Filter.php#L171 states

    Doesn't set anything intentionally

vs the actual code

    public function setUseSessionInUrl($flag)
    {
        $this->_useSessionInUrl = $flag;
        return $this;
    }

so either the comment needs to be corrected or `$this->_useSessionInUrl = $flag;` removed.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-39430

**Comment by okorshenko** [comment]
@fooman, thank you for reporting the issue. Internal ticket: MAGETWO-39430 has been closed and merged to develop branch. Please, let us know if you still have an issue
