### ISSUE TITLE
Security Vulnerability in jQuery UI 1.10.4

### ISSUE THREAD

**Issue by joshuaadickerson** [magento/magento2#14238]
https://snyk.io/vuln/npm:jquery-ui#lh@1.10.4

### Preconditions

1. Magento 2.2.3

### Steps to reproduce

1. Compare the jQuery UI version with the link above

### Expected result

1. Upgrade to a newer version of jQuery UI

### Actual result

1. It's a security vulnerability

**Comment by orlangur** [comment]
Hi @joshuaadickerson, please check https://github.com/magento/magento2#reporting-security-issues on reporting security issues.

**Comment by AykutCevik** [comment]
Hello @orlangur you have referenced to a link but until now the issue isn't resolved in the latest Magento 2.2.5 version. Does it mean that no one fixed that so far? Also the jQuery version itself is now outdated and contains vulnerabilities.

**Comment by orlangur** [comment]
@AykutCevik vulnerability in jQuery UI by itself does not mean Magento is vulnerable. Security issues shall neither be reported nor discussed in GitHub.
