### ISSUE TITLE
Security Vulnerability in jQuery 1.12.4

### ISSUE THREAD

**Issue by joshuaadickerson** [magento/magento2#14239]
https://snyk.io/vuln/npm:jquery#lh@1.12.4

### Preconditions
1. Magento 2.2.3 

### Steps to reproduce

1. Go to the link above

### Expected result

1. Upgrade jQuery to a newer version

### Actual result

1. It's a security vulnerability

**Comment by orlangur** [comment]
Hi @joshuaadickerson, please check https://github.com/magento/magento2#reporting-security-issues on reporting security issues.
