### ISSUE TITLE
Category image upload error

### ISSUE THREAD

**Issue by gawpo50** [magento/magento2#14243]
### Preconditions
Category images not being uploaded and saved...gives the error -> A technical problem with the server generated an error.

Magento 2.2.3....PHP 7.026 

### Steps to reproduce
1. Logon to admin backend 
2. Go to Catalog->Categories
3. Click the upload button for category image
4. Click on Save......
5. Get error -> A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### Expected result

1. Image should upload and be visible on store page and no errors produced

### Actual result

1. Get this error.....
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.
![category](https://user-images.githubusercontent.com/37498213/37761377-6d373302-2e09-11e8-99cd-13d968b9d054.jpg)
![cat-error](https://user-images.githubusercontent.com/37498213/37761380-6f887882-2e09-11e8-9988-b2867a86059e.jpg)

**Comment by magento-engcom-team** [comment]
@gawpo50, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release. The problem happen with some images or with all?

**Comment by gawpo50** [comment]
Only happens with the category images, logo and fav icon images. Product images and all other image use works ok.

**Comment by magento-engcom-team** [comment]
@gawpo50, We were not able to reproduce this issue by following the steps you provided. Please try to reproduce this issue on a clean installation without any third-party dependencies.

**Comment by gawpo50** [comment]
The problem has been solved. Cause of original problem was the hosting platform I was using. After transitioning back to a shared host platform....all errors disappeared and site now works properly. Thanks for all the ideas and help from everybody.

**Comment by magento-engcom-team** [comment]
@gawpo50, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by travis5491811** [comment]
@gawpo50 

How did you move the store to a new host? Did you backup your magneto directory, backup the DB and deploy to new host or just start building again on new host? Did you have any log data that pointed to your error? Did the new host have all the same magento dependencies? Same OS? Just seems strange and now i'm having this same error but in the site where watermark image upload is.

> The problem has been solved. Cause of original problem was the hosting platform I was using. After transitioning back to a shared host platform....all errors disappeared and site now works properly. Thanks for all the ideas and help from everybody.
