### ISSUE TITLE
Not Visible Custom Address Attributes Showing on Checkout

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14257]
### Preconditions
2.2.x

### Steps to reproduce
1. Create Custom Customer Address attribute with "Show on frontend" = NO
2. Create customer -> add any address to the account
3. In Magento admin go to edit customer page and add value to a custom attribute
4. Login to frontend
5. add a product to cart and go to checkout

### Expected result
Customer address block should not display not visible attribute

### Actual result
Attribute value displayed in Shipping address

*NOTES:*
Is issue reproducible in the customer's dumps: Yes
Is issue reproducible in clean reported Magento Version: Yes
Is issue reproducible in the latest available release: Yes

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs
