### ISSUE TITLE
Product URL rewrites get deleted after import products without category column

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14251]
### Preconditions
2.1.8, 2.2.2, 2.2.5

### Steps to reproduce
1. Create product *prod1* and assign it to category *cat1*
2. Prepare file for import (you can export products via Admin panel)
3. Delete "*categories*" column from file
4. See table url_rewrites in DB. Notice that product *prod1* has several URL rewrites. For request paths: *cat1/prod1* and *prod1*
5. Go to Admin panel -> System -> Data transfer -> Import
6. Set Entity type = *Products*, Import Behavior = *Add/Update*, Select File to Import
7. Click *Check Data* button and after *Import* button
8. You will see message "Import successfully done"
9. See table url_rewrites in DB. Notice that URL rewrite *cat1/prod1 was deleted* from table

### Expected result
The rows mustn't be deleted from url_rewrite table for prod1

### Actual result
Some rows get deleted from url_rewrite table for prod1

*NOTES:*
Generated from MAGETWO-87618

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs

**Comment by henk-hypershop** [comment]
What is the status for this issue? We experience this on every import.
