### ISSUE TITLE
When two fixed price gift cards of different values are added to the cart, they appear in the cart with the same value as the first gift card

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14254]
### Preconditions
2.2.x

### Steps to reproduce
1. From the admin, go to Catalog > Products, click Add Product > Gift Card
2. Fill out all of the required fields
3. Next to Amount, click Add Amount and enter $100 and click Save
4. Repeat steps 1-3 but with a the Amount $150.
5. From the customer view, add the $100 gift card to the cart and then add  the $150 gift card to the cart
6. Click the cart icon and click View and Edit Cart

### Expected result
The cart shows two gift cards, 1 for $100 and 1 for $150 

### Actual result
When you first click on the cart icon, both items are listed as $100. After clicking on View and Edit Cart, you see that Price and Subtotal will show $100 for both products. The product name for the $150 product will be correct. 

*NOTES:*
Is issue reproducible in Magento Version: 2.1.10, 2.2.2, 2.2.3
Is issue reproducible in Trunk:
Is issue reproducible in the customer's install: Yes

*Original ticket:*
MAGETWO-88284

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs
