### ISSUE TITLE
Issue with Newsletter subscriptions

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14256]
### Preconditions
2.2.x

### Steps to reproduce
1. Install clean Magento 2.2.2
2. Create 1 Website with 2 store views
3. On storefront in default store view, scroll down to foot and subscribe to newsletter
4. Scroll up to top and change store view to second store view
5. Create a customer account in storeview2 with the same email address
6. In Admin, open the customer account and click on Newsletter in left column
7. Observe that customer account is already subscribed to newsletter
8. Unsubscribe the from newsletter and click Save
9. Again click on Newsletter in customer account and subscribe to newsletter
10. In MySQL, check database for records and behaviour
11. Again click on Newsletter in customer account and subscribe to newsletter
12. In MySQL, check database for records and behaviour
13. Again click on Newsletter in customer account and subscribe to newsletter
14. In MySQL, check database for records and behaviour

### Expected result
There should only be one newsletter subscription per email address.

### Actual result
When having more than one store view, you can end up with a new record in newsletter_subscriber every time you enable the newsletter in the front or backoffice.
 
*NOTES:*
Original ticket: MAGETWO-88736
Is issue reproducible in Magento Version: Yes
If issue reproducible on the latest Magento Version: Yes
Is issue reproducible in the customer's install: N/A
Is Issue reproducible in Sparta with merchant dumps: N/A

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs
