### ISSUE TITLE
Custom Options are corruputed when saving product to a different website

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14253]
*ISSUE:*
When adding another site to a product with customizable options, the options get corrupted. Sometimes by splitting into multiple options or duplicating an option.

### Preconditions
2.2.1, 2.2.2, 2.2.5
Is issue reproducible in Magento Version: 2.2.1, 2.2.2
Is issue reproducible in Trunk:
Is issue reproducible in the customer's install: Y

Precondition: Create deployment with multiple websites.

Split Option Case
1 From admin, go to CATALOG > Products
2 Click Add Product
3 Fill in the required fields
4 Under Customizable Options click Add Option
5 Enter an Option Title and under Option Type choose Radio Buttons
6 Below that click Add Value and enter a Title and a Price
7 Repeat step 6 two more times with different values (see RadtioButtonBefore.png)
<img width="915" alt="radiooptionbefore" src="https://user-images.githubusercontent.com/35498570/37771056-1253b0f2-2ddf-11e8-80c1-8a82688dfb82.PNG">

8 Click Save
9 While still editing the product, under Product in Websites, select the second website and Save, copying data from Default Values
10 Look at the Customizable Options

Duplicate Option Case
1 From admin, go to CATALOG > Products
2 Click Add Product
3 Fill in the required fields
4 Under Customizable Options click Add Option
5 Enter an Option Title and under Option Type choose Text > Field (see TextFieldBefore.png)
<img width="903" alt="textfieldbefore" src="https://user-images.githubusercontent.com/35498570/37771034-f97557d4-2dde-11e8-93c7-cf0dfce8aebf.PNG">
6 Click Save
7 While still editing the product, under Product in Websites, select the second website and Save, copying data from Default Values
8 Look at the Customizable Options

*EXPECTED RESULTS:*
Customizable options should be configured the same after saving the second website and before saving.

*ACTUAL RESULTS:*
In the Split Options Case, there are now two sets of options, the top one with one of the values and the bottom with two of the values. (see RadioButtonAfter.png)
In the Duplicate Option Case, there are now two sets of the same option (see TextFieldAfter.png)
<img width="900" alt="textfieldafter" src="https://user-images.githubusercontent.com/35498570/37771027-f349c1ba-2dde-11e8-9792-c254feeaf98a.PNG">

*ORIGINAL SF DESCRIPTION*:
On a multi store environment, if you create a product and add a custom option and save, go back into the product and add it to another website and re-save, the custom options will be corrupted.

Steps to Reproduce:
1) Create two websites, each with one store and store view.
2) Create a product with a radio button style custom option, with 3 values, with a title value of Gold, Silver and Bronze respectively.
3) Save the product.
4) Re-enter the product and add it to another website.
5) Re-save the product.
6) On re-entering the product you now find two custom options, the first with a value of Silver and Bronze and the second with a value of Gold.

I have also tried this with Text field custom options, and the custom option is duplicated.

No special environment is needed. I could re-produce this behaviour with a fresh install of this Magento version and by just adding one product via the Magento Admin.

*Original ticket:*
MAGETWO-87721

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs
