### ISSUE TITLE
Product "Use Default Value" checkbox for an attributes are unchecked for the new website scope

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14259]
### Preconditions
2.2.x

### Steps to reproduce
1. Create second website (you should have 2 websites)
2. Create new product, assign it only to first website and save
3. Go to "Product in Websites" tab and assign this product to second website (select "Copy Data from Default Values")
4. Save product 
5. Change product scope to second website and check attributes(Product name, Tax class, Visibility etc)

### Expected result
"Use Default Value" checkboxes should be checked

### Actual result

"Use Default Value" checkboxes for an attributes are unchecked

*Original ticket*:
MAGETWO-73638

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs
