### ISSUE TITLE
Magento theme debug cannot found

### ISSUE THREAD

**Issue by sakiss** [magento/magento2#1425]
Hi

I am following the doc
http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/themes/debug-theme.html

to debug the theme but cannot find that section
ver. 0.74.0-beta9
![shot](https://cloud.githubusercontent.com/assets/1838041/8412874/7788662c-1e95-11e5-9fa9-6ca0f480998a.png)

**Comment by kandy** [comment]
Configuration is available only on store level scope

**Comment by sakiss** [comment]
Can you become more specific to what should i do?

**Comment by naspar** [comment]
Hi sakiss,
try to change the "StoreView" on top-left from "Default Config" to "Main Website" and see if the option appears. 

Let me know how you get on.

**Comment by vpelipenko** [comment]
@sakiss, did you find mentioned configuration section?

**Comment by sakiss** [comment]
Changing store view (top left corner) did the trick
Thank you all!
