### ISSUE TITLE
Tier price not applied instantly after logging in Shopping Cart

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14255]
### Preconditions
2.2.x

### Steps to reproduce
1. Create customer group "TEST"
2. Crete Customer and assign it to TEST group
3. Create Product with tire price for Test group
4. Open frontend as guest user
5. Add product to cart
6. Click "Sign In " and Login as Customer from step 2
7. Observe product prices
 
### Expected result
main section and summary should display tier price

### Actual result
 the main section displays the regular price
 "Summary" block shows the tier price and after several seconds refreshed to tier price

*NOTES:*
Original ticket MAGETWO-88641
Is issue reproducible in the customer's dumps: Yes
Is issue reproducible in clean reported Magento Version: Yes
Is issue reproducible in the latest available release: Yes

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs
