### ISSUE TITLE
MAGE_PROFILER and Error in javascript customer-data.js

### ISSUE THREAD

**Issue by vpietri** [magento/magento2#1426]
Hi,

On Magento version: 0.74.0-beta15 there is a javascript error on customer-data.js.

The response is a text response and the test is on a json.

TypeError: jqXHR.responseJSON is undefined

![screenshot at 20-55-34](https://cloud.githubusercontent.com/assets/8598479/8415774/7f0e2858-1ea1-11e5-86ef-308613f723d6.png)

**Comment by vpietri** [comment]
This error comes only with MAGE_PROFILER enabled.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-39576

**Comment by daim2k5** [comment]
fixed. If not please feel free to reopen the issue
