### ISSUE TITLE
Bundled SKUs are being assembled based on the product ID number

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14262]
### Preconditions
Bundle product SKUs are being assembled in the order of the associated (selected) product ID numbers in ascending order instead of the order in which the option is added to the bundle product.

2.2.2, 2.2.5

### Steps to reproduce
1. Go to Products > Catalog > SKU: 24-WG080 bundle Items
2. Notice the options added to the product and the order in which they are placed
3. Go to frontend > the product SKU: 24-WG080 > Customize and Add to Cart
4. Select a product for each option. 
5. Proceed to checkout > place order
6. Go to Sales > Orders > the new order > Items Ordered
7. Notice the SKU of the product order does not have the SKUs of the select products in the bundle sorted in the order of the options set from the previous step. 

### Expected result
Bundle product SKU should be built based on the order of the options set in the bundle product

### Actual result
Bundle product SKU is built based on the order of the product ID of the product options set in the bundle product

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs
