### ISSUE TITLE
Can't edit or remove multiple wishlist if title contains apostrophe mark

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14260]
### Preconditions
2.2.x

### Steps to reproduce
1. Enable multiple wishlist
2. Register customer on storefront
3. Open wishlist section in My Account
4. Add new wishlist with title that contains apostrophe mark (e.g "test's")
5. Save wishlist
6. Try to edit or remove wishlist

### Expected result
 Wishlist can be edited or removed

### Actual result
Nothing happens when rename or remove wishlist

*Original ticket*:
MAGETWO-74160

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Magento Open Source, isn't it?

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.
