### ISSUE TITLE
Customer address attribute value is not saving in Magento 2.2.3

### ISSUE THREAD

**Issue by Puru2016** [magento/magento2#14279]
### Preconditions

1. Magento 2.2.3

### Steps to reproduce

1.  Create a module using [silksoftware](http://www.silksoftware.com/magento-module-creator/magento2x.php)
2.  code of  CustomerSetup.php file:-

`namespace Company\CustomAttribute\Setup;`

`use Magento\Eav\Model\Config;`

`use Magento\Eav\Model\Entity\Setup\Context;`
`use Magento\Eav\Setup\EavSetup;`
`use Magento\Framework\App\CacheInterface;`
`use Magento\Framework\Setup\ModuleDataSetupInterface;`
`use Magento\Eav\Model\ResourceModel\Entity\Attribute\Group\CollectionFactory;`

`class CustomerSetup extends EavSetup {`

	protected $eavConfig;

	public function __construct(
		ModuleDataSetupInterface $setup,
		Context $context,
		CacheInterface $cache,
		CollectionFactory $attrGroupCollectionFactory,
		Config $eavConfig
		) {
		$this -> eavConfig = $eavConfig;
		parent :: __construct($setup, $context, $cache, $attrGroupCollectionFactory);
	} 

	public function installAttributes($customerSetup) {
		$this -> installCustomerAttributes($customerSetup);
		$this -> installCustomerAddressAttributes($customerSetup);
	} 

	public function installCustomerAttributes($customerSetup) {
			
	} 

	public function installCustomerAddressAttributes($customerSetup) {
			
		$customerSetup->addAttribute('customer_address',
			'mobile_number',
			[
				'label' => 'Mobile Number',
				'system' => 0,
				'user_defined' => true,
				'position' => 140,
				'sort_order' =>140,
				'visible' =>  true,
				'default_value' => '',
				'note' => 'Mobile Number',
				'type' => 'varchar',
				'input' => 'text',
				'required' => false,
			]
			);

		$customerSetup->getEavConfig()->getAttribute('customer_address', 'mobile_number')
			->setData('is_user_defined',1)
			->setData('default_value','')
			->setData('used_in_forms', ['adminhtml_customer_address', 'customer_register_address', 'customer_address_edit'])
			->save();				
	} 

	public function getEavConfig() {
		return $this -> eavConfig;
	}  } 

3. Code of InstallData.php
`	

namespace Company\CustomAttribute\Setup;

	use Magento\Eav\Setup\EavSetup;
	use Magento\Eav\Setup\EavSetupFactory;
	use Magento\Framework\Setup\InstallDataInterface;
	use Magento\Framework\Setup\ModuleContextInterface;
	use Magento\Framework\Setup\ModuleDataSetupInterface;
	 
	class InstallData implements InstallDataInterface
	{
		private $eavSetupFactory;	 
		
		public function __construct(EavSetupFactory $eavSetupFactory)
		{
			$this->eavSetupFactory = $eavSetupFactory;
		}
	 
		public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
		{
			/** @var EavSetup $eavSetup */
			$eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
			if (version_compare($context->getVersion(), '1.0.0') < 0){

					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$customerSetup = $objectManager->create('Dotsquares\CustomAttribute\Setup\CustomerSetup');
					$customerSetup->installAttributes($customerSetup);

					

			}

		}
	}

### Expected result

1. Attribute should be created in customer address section in Magento admin.

### Actual result

1.  Attribute created in customer address section in Magento admin but value not saved.

**Comment by orlangur** [comment]
Hi @Puru2016, did you have a chance to track down why the value is not saving?

**Comment by Puru2016** [comment]
Not able to find the cause of this issue as I am using the same script in magento 2.1.10, and it's working fine.

**Comment by magento-engcom-team** [comment]
@Puru2016 , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
