### ISSUE TITLE
Magento 2 configurable products sale label & old price not showing

### ISSUE THREAD

**Issue by kfaer** [magento/magento2#14278]
Magento 2.2.2 old prices (crossed out) & sale label do not show up again:

on catalog grid view
on product detail page
We use configurable products.

Magento 2.2.2
PHP 7

Expectations was that both special and old regular prices would be shown.

Any ideas how to fix this? Thank you,

Preconditions
Magento 2.2.2, PHP 7
Create configurable products

Expected Result
Regular and special prices of products displayed correctly

Actual Result
Old prices & Sale label do not show up anymore

**Comment by kfaer** [comment]
@aredridel @jaywilliams @alepane21 @ivannpaz

**Comment by kfaer** [comment]
any update please???

**Comment by magento-engcom-team** [comment]
@kfaer , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the steps required to reproduce. Please try to reproduce this issue on a clean installation without any third-party dependencies.

**Comment by ladle3000** [comment]
I can confirm the same, except that it does show once an option is selected...

**Comment by mpawate** [comment]
This function is not working with 2.2.3 also.

**Comment by devhelp37** [comment]
Just installed new Magento 2.2.3 and I also got exactly same issue. Kindly rectify this as this is a core functionality. Just now I found this issue already raised after I raised the exact same issue #15043 . I have explained all the detailed steps to recreate the issue.

**Comment by jstoel** [comment]
I am on v2.2.0 and am having the same issue. Is there any updates on this? This used to work in older versions.

**Comment by AaronKaa** [comment]
We're just about to go live on 2.2.4 with the same behaviour, its a bit of a show stopper as we have a clothes store where 70% of our products have variations, is there any kind of update for this @magento-engcom-team ?

**Comment by ghost** [comment]
Duplicate of #15043

**Comment by darren-halo** [comment]
Yes, see the solution on #15043. worked in 2.2.5
