### ISSUE TITLE
M2.2.3 - multistore category layered nav counts are wrong

### ISSUE THREAD

**Issue by pixiemediaweb** [magento/magento2#14272]
In a Magento 2.2.3 site with multiple websites, each with a single store view.  They share a common navigation structure but each site has a different sub set of products.  In store A (main/default store) there are 60 products in category A, distributed between 5 subcategories.  This works correctly and shows the sub categories and counts accurately.   

Store B only has 4 of those products available, but the category layered filter shows the same count and available sub categories as store A.  Clicking the category filter provides a 404 as the products aren't available for store B.
 
### Preconditions
Magento 2.2.3
Nginx
Maria DB
PHP 7

### Steps to reproduce
N/A

### Expected result
Category layered navigation should only show the counts and sub categories relevant to the current store.

### Actual result
The default counts and data is shown.

**Comment by pixiemediaweb** [comment]
worth noting, the attribute filters and toolbar totals are all correct. It's only the category filter which has an issue

**Comment by pixiemediaweb** [comment]
I've traced this through. 

Here's where the issue occurs;

/vendor/magento/module-catalog/Model/ResourceModel/Category.php

Function: public function getProductCount($category)

The method checks the table catalog_category_product which has no concept of stores.  I've modified the function to use the catalog_category_product_index table instead.  There may be knock on effects, but would like to have M-Team feedback please.

New method;

    public function getProductCount($category)
        {
            $productTable = $this->_resource->getTableName('catalog_category_product_index');
            $storeId = $category->getStoreId();
            $select = $this->getConnection()->select()->from(
                ['main_table' => $productTable],
                [new \Zend_Db_Expr('COUNT(main_table.product_id)')]
            )->where(
                'main_table.category_id = :category_id and main_table.store_id = '.$storeId
            );

        $bind = ['category_id' => (int)$category->getId()];
        $counts = $this->getConnection()->fetchOne($select, $bind);

        return intval($counts);
    }

**Comment by magento-engcom-team** [comment]
Hello @pixiemediaweb. Thanks for reporting. Currently we've been not able to reproduce Your issue. Probably there is something we've missed. So we had 2 websites with the following structure:
![sites](https://user-images.githubusercontent.com/31669971/37828223-0ce56ca4-2ea3-11e8-8b44-75061cbcac05.png)
Then we created Category A with 5 subcategories each of them having two products:
![categories](https://user-images.githubusercontent.com/31669971/37828302-6314e1ae-2ea3-11e8-8b04-a9602b428e3d.png)
All the products belonged to the Main site and only four of them (A1S1 in A1 category, A4S2 in A4 category and both A5S1 as well as A5S2 in A5 category) belonged to the Additional site.
So on the Main site we've got this:
![main](https://user-images.githubusercontent.com/31669971/37828945-d7219162-2ea5-11e8-916c-8c86d7be552e.png)
And on the Additional - this:
![additional](https://user-images.githubusercontent.com/31669971/37829012-11e5d11e-2ea6-11e8-86a8-bb3627acd18d.png)
So please tell us what the essential thing we've been missing. Also please try to reproduce the issue on a clear freshly installed instance of Magento.

**Comment by pixiemediaweb** [comment]
The only difference I can think of is that the products on our client's instance have been created initially with a spreadsheet import, and then with API calls.  Presume you created your products manually in admin?

**Comment by pixiemediaweb** [comment]
and can you tell me at what point a store filter is applied to the category collection?

**Comment by magento-engcom-team** [comment]
> and can you tell me at what point a store filter is applied to the category collection?

@pixiemediaweb, we just entered the wanted site then entered that "A" category page,  and the filters had already been there if You mean this. Or You mean something else?

**Comment by pixiemediaweb** [comment]
thanks for the reply, I mean where in the code does the store filter get applied to the category filter ?  The method I found and modified in my third post certainly didnt take multi-store into account and I couldn't spot the products/categories attempt to get filtered out further along the process.

**Comment by indefinitedevil** [comment]
We're experiencing a similar issue where out of stock products are included in the filter counts even though they're not included in the product lists.

Steps to reproduce:
- Ensure "Display Out of Stock Products" is off
- Have a sub-category which contains at least two products, at least one of which is out of stock
- Go to the parent category for the subcategory
- The count for the subcategory in the filter will be wrong

![image](https://user-images.githubusercontent.com/23464386/42175587-d5b10f0c-7e1d-11e8-9568-311aced8ba84.png)
In the image here, the current category contains one in-stock product which is in all of the child categories. The Tees category contains a second product which is out of stock. This second product is correctly not shown in the product list, but is counted in the filter, which is clearly incorrect.

This screenshot comes from a Magento 2.2.1 Open Source installation, but we have also seen exactly the same issue on Magento 2.2.4 Commerce Cloud.

**Comment by ghost** [comment]
@pixiemediaweb, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
