### ISSUE TITLE
Mini cart product price is not refreshing when user switch the store from one store to another

### ISSUE THREAD

**Issue by openwavecomputing** [magento/magento2#14280]
### Preconditions

1. Magento2 version 2.1.5
2. Mini cart not refreshing when user switch the store and its keep the previous store price after store switched. We are working on store based website and Wrong pricing displaying on the mini cart when user switch the store from one store to another store. The product having different price for different store. for our example we will take two stores and name it like Store-A and Store-B here we have one product called Prod-A. Now add Prod-A from Store-A and then clear the browser cache and then change the store to Store-B now see mini cart not refreshed it is still keep the previous store price.

### Steps to reproduce

1. Login the site with valid user
2. Select the Store-A and then add the Prod-A to cart
3. Sign out the user
4. Clear the browser cache
5. Change the store from Store-A to Store-B
6. Now again login the same user
7. Check the mini cart it still keep the previous store price 

### Expected result

1. When user switch the store then the mini cart price should refresh as per the store  

### Actual result

1. Mini cart not refreshing

**Comment by magento-engcom-team** [comment]
@openwavecomputing , thank you for your report.
The fix for this issue is already available in the develop branch 2.2-develop

**Comment by ghost** [comment]
@openwavecomputing, "Price" attribute has "Global" scope, so it cannot be changed between the Stores in Magento clean installation.
