### ISSUE TITLE
CUSTOMER REGISTRATION IS NOT WORKING 

### ISSUE THREAD

**Issue by phpworld** [magento/magento2#14286]
I am useing MAGENTO 2.2.2 VERSION FRESH INSTALLATION 

THAT CUSTOMER REGISTRATION NOT WORKING 

MY BROWSER IS  GOOGLE CHROME 

THNAKS

**Comment by magento-engcom-team** [comment]
@phpworld , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by amon81** [comment]
#14295

**Comment by ishakhsuvarov** [comment]
@phpworld Closing this issue in favor of #14295
