### ISSUE TITLE
API REST product images, Label in one website and roles in other

### ISSUE THREAD

**Issue by guillermogallego** [magento/magento2#14287]
### Preconditions
Magento 2.2.3
Php 7.1
Centos 7 with CPANEL
I configure 3 Websites and theirs views

### Steps to reproduce

1) Create a product with API REST for websites id 1 and 3

`Array
(
    [sku] => DS-100-101
    [name] => Daale Swim Bañador Bizarre Training
    [attribute_set_id] => 9
    [status] => 1
    [visibility] => 4
    [type_id] => configurable
    [media_gallery_entries] => Array
        (
            [0] => Array
                (
                    [media_type] => image
                    [label] => Daale Swim Bañador Bizarre Training - 0
                    [disabled] => 
                    [position] => 1
                    [types] => Array
                        (
                            [0] => "image"
                            [1] => "small_image"
                            [2] => "thumbnail"
                            [3] => "swatch_image"
                            [4] => "_media_image"
                        )
                    [content] => Array
                        (
                            [type] => image/jpeg
                            [name] => daale-swim-banador-bizarre-training.jpg
                            [base64_encoded_data] => Base 64 data 
                        )
                )
            [3] => Array
                (
                    [media_type] => image
                    [label] => Daale Swim Bañador Bizarre Training - 3
                    [disabled] => 
                    [position] => 4
                    [types] => Array()
                    [content] => Array
                        (
                            [type] => image/jpeg
                            [name] => daale-swim-banador-bizarre-training.jpg
                            [base64_encoded_data] => Base 64 data 
                        )
                )
        )
    [extension_attributes] => Array
        (
            [stock_item] => Array
                (
                    [is_in_stock] => 1
                )
            [website_ids] => Array
                (
                    [0] => 1
                    [1] => 2
                )
        )

    [custom_attributes] => Array
        (
            [0] => Array
                (
                    [attribute_code] => description
                    [value] => ""
                )
            [1] => Array
                (
                    [attribute_code] => meta_description 
                    [value] => ""
                )
            [2] => Array
                (
                    [attribute_code] => meta_title
                    [value] => Daale Swim Bañador Bizarre Training
                )
        )
)
`

2) Inside the product detail in the admin I look the images

![captura de pantalla de 2018-03-26 17-13-09](https://user-images.githubusercontent.com/4039022/37915092-fd418d6e-3118-11e8-8725-88b3a7fd893c.png)

3) On the same page, I change the view to another website

![captura de pantalla de 2018-03-26 17-15-38](https://user-images.githubusercontent.com/4039022/37915302-7d433a8a-3119-11e8-8d59-4740c00a0878.png)

4) Again I look the images

![captura de pantalla de 2018-03-26 17-18-26](https://user-images.githubusercontent.com/4039022/37915407-be17a0aa-3119-11e8-8923-a07ffdc4bcad.png)

### Expected result
The roles of primary images assigned to all stores views
The label of images assigned to all stores views
The thumbnail for the product list assigned to all stores views (without filters)

### Actual result
Roles of primary image are assigned to only one store view or website
Label of images are assigned to only one store view or website (different to the above)
Only show thumbnail image in the list when filter for one store view (the view have assigned the roles)

![captura de pantalla de 2018-03-23 13-02-00](https://user-images.githubusercontent.com/4039022/37828154-6d76cb3e-2e9a-11e8-96fc-c343708ed5a4.png)
![captura de pantalla de 2018-03-23 13-01-25](https://user-images.githubusercontent.com/4039022/37828157-717116c2-2e9a-11e8-80db-63fc8f101662.png)

**Comment by magento-engcom-team** [comment]
@guillermogallego, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by d0ky** [comment]
I'm experiecing the same problem and I may add one more boring issue related and similar to the issue [#6259](https://github.com/magento/magento2/issues/6259) .

While I work on the backend, trying to fix issue in image order data I expect that working on all store views will modify image order on all store views, but switching the view to a specific one I find a different image order, I've gone through a search in catalog configuration for image order scope without any luck, any hint on this? Is it a know issue as well?

**Comment by sebastianamaro** [comment]
Hi!

Any update on when this issue is going to be fixed? 
I have the same problem on 2.1.3

**Comment by guillermogallego** [comment]
Hi!

The bug was solved for the next versions

**Comment by sebastianamaro** [comment]
So the fix is not going to be backported to 2.1.3? Only 2.2 and forward?

**Comment by riconeitzel** [comment]
So, this is still an issue in 2.3.5?

**Comment by engcom-Alfa** [comment]
Hi @guillermogallego . Thank you for your report!

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.
It seems that the problem has already been solved.

**Manual testing scenario:**

Create a product with API REST for websites id 1 and 2

```xml
{
  "product": {
    "sku": "DS-100-101",
    "name": "Daale Swim Bañador Bizarre Training",
    "attribute_set_id": 4,
    "price": 1,
    "status": 1,
    "visibility": 4,
    "type_id": "configurable",
    "extension_attributes": {
      "website_ids": [
        1,
        2
      ],
      "stock_item": {
        "qty": 20,
        "is_in_stock": true
      }
      },
"media_gallery_entries": [
      {
        "media_type": "image",
        "label": "Daale Swim Bañador Bizarre Training - 0",
        "position": 1,
        "disabled": false,
        "types": [
          "image",
          "small_image",
"thumbnail",
"swatch_image"
        ],
        "content": {
          "base64_encoded_data": "string",
          "type": "image/jpeg",
          "name": "daale-swim-banador-bizarre-training.jpg"
        }
      },
{
        "media_type": "image",
        "label": "Daale Swim Bañador Bizarre Traininfgfgg - 0",
        "position": 4,
        "disabled": false,
        "content": {
          "base64_encoded_data": "string",
          "type": "image/jpeg",
          "name": "daale-swim-bgggganador-bizarre-training.jpg"
        }
      }
    ],
    "custom_attributes": [
      {
        "attribute_code": "description",
        "value": "test1"
      },
      {
        "attribute_code": "meta_description",
        "value": "test2"
      },
      {
        "attribute_code": "meta_title",
        "value": "Daale Swim Bañador Bizarre Training"
      }
]
  },
  "saveOptions": true
}
```
**Actual Result:**

1. The roles of primary images assigned to all stores views - :heavy_check_mark: 
2. The label of images assigned to all stores views - :heavy_check_mark: 
![Peek 2021-01-08 12-36](https://user-images.githubusercontent.com/51679138/104005891-6ffdde80-51ae-11eb-8d70-309ad51ef809.gif)

3. The thumbnail for the product list assigned to all stores views (without filters)

![Screenshot from 2021-01-08 12-29-07](https://user-images.githubusercontent.com/51679138/104005961-81df8180-51ae-11eb-9712-2682ed570389.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
