### ISSUE TITLE
Since MagentoCE2.1.11, after swithing store view, ___store=xx is added to url. Breaks 'back' functionality.

### ISSUE THREAD

**Issue by bobemoe** [magento/magento2#14294]
### Preconditions
PHP 7.0.27-1-dotdeb+8.1 (cli) ( NTS )
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-1-dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

nginx version: nginx/1.12.2

Linux 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

mysql  Ver 15.1 Distrib 10.0.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Steps to reproduce
1. Clean install of magento2.1.12 using composer. 
2. Admin->Stores->Add Store View (name: test, code: test, enabled)
3. Fontend use store switcher to change store view to 'test' store. Notice that ?___store=test is added to the URL.
4. Navigate to another page (e.g. terms)
5. Click 'Back' in the browser

### Expected result
The previous page is displayed

### Actual result
Firefox complains "Expired Document"

### Notes
I've tested this with the different version of magento. It seems that before 2.1.11 the ?___store= was not added to the URL and switching was handled, i guess, purely by POST/session/cookie. 
Since 2.1.11 the ?___store= is added upon switching and going back to any page that has that in the URL causes this issue.

**Comment by magento-engcom-team** [comment]
@bobemoe , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @bobemoe. Thank you for your report. 
The issue has been fixed in magento/magento2#15961 by @Mobecls in 2.3-develop branch
Related commit(s):
 - [3feda05339677a30590230745619db035781752d](https://github.com/magento/magento2/commit/3feda05339677a30590230745619db035781752d)

The fix will be available with the upcoming 2.3.1 release.
