### ISSUE TITLE
sales rule condition - shipping method redirects to dashboard with 404 error 

### ISSUE THREAD

**Issue by PiroozMB** [magento/magento2#14291]
migrated my magento 1.9.3.0 to magento 2.2.3 (and once migrated it to 2.1.9). 
I go to Marketing->catalog price rules->add new rule. in the condition section when i choose "shipping method" then it shows temporarily a message saying "won't take long" and then redirects to this link: http://blahblah/blahblah/sales_rule/index/index/key/ec804cf3ecd049ff913d524e390f134c0e2245ed96226c573761460df08ca6ec/ 
saying: 

Magento Admin
404 Error
Page not found.
This happend on both magento versions (2.2.3),(2.1.9)
I checked my error log on magento 2.2.3 and see no errors related this issue. 

the only error i'm seeing is:
[2018-03-23 16:21:12] main.INFO: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header.inner.right' and 'header' respectively. [] []

Checked error log report on magento 2.1.9 and see one error related this issue as:
a:4:{i:0;s:132:"Notice: Array to string conversion in /var/www/magento2/vendor/magento/module-shipping/Model/Config/Source/Allmethods.php on line 61";i:1;s:5638:"#0 /var/www/magento2/vendor/magento/module-shipping/Model/Config/Source/Allmethods.php(61): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/var/www/magent...', 61, Array)
#1 /var/www/magento2/vendor/magento/module-sales-rule/Model/Rule/Condition/Address.php(145): Magento\Shipping\Model\Config\Source\Allmethods->toOptionArray()
#2 /var/www/magento2/vendor/magento/module-rule/Model/Condition/AbstractCondition.php(621): Magento\SalesRule\Model\Rule\Condition\Address->getValueSelectOptions()
#3 /var/www/magento2/vendor/magento/module-rule/Model/Condition/AbstractCondition.php(646): Magento\Rule\Model\Condition\AbstractCondition->getValueElement()
#4 /var/www/magento2/vendor/magento/module-rule/Model/Condition/AbstractCondition.php(474): Magento\Rule\Model\Condition\AbstractCondition->getValueElementHtml()
#5 /var/www/magento2/vendor/magento/module-rule/Model/Condition/AbstractCondition.php(485): Magento\Rule\Model\Condition\AbstractCondition->asHtml()
#6 /var/www/magento2/vendor/magento/module-sales-rule/Controller/Adminhtml/Promo/Quote/NewConditionHtml.php(41): Magento\Rule\Model\Condition\AbstractCondition->asHtmlRecursive()
#7 /var/www/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml->execute()
#8 /var/www/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor->___callParent('dispatch', Array)
#11 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\SalesRu...', 'dispatch', Object(Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor), Array, 'adminAuthentica...')
#12 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\SalesRu...', 'dispatch', Object(Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor), Array, 'adminMassaction...')
#15 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/magento2/var/generation/Magento/SalesRule/Controller/Adminhtml/Promo/Quote/NewConditionHtml/Interceptor.php(26): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor->___callPlugins('dispatch', Array, Array)
#18 /var/www/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#21 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#22 /var/www/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /var/www/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /var/www/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#27 /var/www/magento2/pub/index.php(85): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#28 {main}";s:3:"url";s:209:"/blahblah/sales_rule/promo_quote/newConditionHtml/form/sales_rule_formrule_conditions_fieldset_/form_namespace/sales_rule_form/key/e6b37c280067c4113b2427707bd4d8f4dac4b293a6a7835678e5b134f056f973/?isAjax=true";s:11:"script_name";s:10:"/index.php";}

Any idea how to sove this bug?
Thanks

**Comment by magento-engcom-team** [comment]
Hi @PiroozMB. For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool.

Thank you.

**Comment by PiroozMB** [comment]
Never mind. I got it solved myself. had to add this : if (!empty($carrierCode) && !empty($methodCode) && !empty($methodTitle)) {
and put it after : 
foreach ($carrierMethods as $methodCode => $methodTitle) {
to check if it's not empty.

**Comment by santibm** [comment]
Hi, 

We recently had this issue, in our case it was a problem with ModSecurity rules: 

`--786c900b-B--
POST /administrator/catalog_rule/promo_catalog/newConditionHtml/form/catalog_rule_formrule_conditions_fieldset_/form_namespace/catalog_rule_form/key/6c6b5f50af5277a66476d8357acbacf52e62011a3c99ab6f3d66dc2e02cc2f5d/?isAjax=true HTTP/1.0`

`--786c900b-H--
Message: Warning. detected SQLi using libinjection with fingerprint '1c' [file "/usr/local/apache/modsecurity-owasp-latest/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "68"] [id "942100"] [rev "1"] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: 1c found within ARGS:id: 1--1"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"]`

We ended up adding the exclude rules to ModSecurity configuration:

`<IfModule mod_security2.c>
SecRuleEngine On
SecRuleRemoveById 942100
SecRuleRemoveById 950004
SecRuleRemoveById 300016
</IfModule>`

**Comment by thangasujithas** [comment]
> Never mind. I got it solved myself. had to add this : if (!empty($carrierCode) && !empty($methodCode) && !empty($methodTitle)) {
> and put it after :
> foreach ($carrierMethods as $methodCode => $methodTitle) {
> to check if it's not empty.

hi, where you have addded these lines.. can you please tell

**Comment by PiroozMB** [comment]
@thangasujithas hi i think it was here:  Magento\Shipping\Model\Config\Source\Allmethods
