### ISSUE TITLE
Customer registration and login doesn't work with Browser Chrome

### ISSUE THREAD

**Issue by amon81** [magento/magento2#14295]
### Preconditions

1. Ubuntu as OS
2. Server Web is Apache 2 and PHP 7.0
3. I've try saving session in DB and files mode (the mode not change the result)
4. TimeZone is set to Europe/Rome in the php.ini configuration file and in magento config.
5. Frontend and backend site under HTTPS protocol

### Steps to reproduce

1. New installation via composer of Magento 2.2.3 Community
2. After the installation with success. With browser Chrome (Version 65.0.3325.18) is impossible to create new customer and sign in via frontend side. Admin side the login function works fine.
3. With other browser like Firefox there are no problems, via frontend, to create customers or in the login function.

### Expected result

1. Chrome after the form login is submit have to enter in personal page of the user but now remain in the login page.

### Actual result

1. Remain in the same page after clear the form.
![untitled](https://user-images.githubusercontent.com/5999462/37846862-45efbbc2-2ecf-11e8-80eb-efa1986e7be1.png)

**Comment by jonathanKingston** [comment]
I couldn't reproduce this, @amon81 were you creating the account then signing out, and logging in again?

**Comment by amon81** [comment]
I've the local website under virtual host with domain like HTTPS://commerce 
I have frontend and backend site under HTTPS protocol...

**Comment by ishakhsuvarov** [comment]
@amon81 Please check browser console errors, error logs on the server, etc.
This flow is covered with different kind of automated tests and unlikely to be broken out of the box.

**Comment by amon81** [comment]
@ishakhsuvarov I've seen that cookies are dated like 1969 and the browser think that are old sessions.... No errors in console..
Of course I've cleaned the cookies and the caches...

**Comment by orlangur** [comment]
@amon81,

> I've the local website under virtual host with domain like HTTPS://commerce

Try to use normal domain name, see https://github.com/magento/magento2/issues/13423#issuecomment-362248464 for more details.

Would be nice to disallow domain name without a period on during installation though. Are you interested in implementing such an improvement maybe?

**Comment by amon81** [comment]
@orlangur wow , thanks
