### ISSUE TITLE
Old error - when you can't login to the backend

### ISSUE THREAD

**Issue by SKovbel** [magento/magento2#1430]
I've got the old error - when you can't login to the backend. 
User & Passwod are correct (when enter incorrect data system noticed me that your usr/pwd are incorrect or user is disabled). Tried login on 2 computers and 4 browsers.
Server has real domain and run under varnish. 
Test version of site works fine (everything different, linux, apache, php, mysql).
Error has appeared after last upgrade.

What should i do to enter backend?

![3056](https://cloud.githubusercontent.com/assets/813985/8437309/e3550154-1f66-11e5-87c1-6b33b777c098.png)

p.s.
Has Magento2 something like that?

```php
$cookieParams = array(           
    'lifetime' => $cookie->getLifetime(),           
    'path'     => $cookie->getPath(),           
    //'domain'   => $cookie->getConfigDomain()           
    //'secure'   => $cookie->isSecure(),           
    //'httponly' => $cookie->getHttponly()       
);```

**Comment by Mackovey** [comment]
Problem disappeared after removed params 

![3060](https://cloud.githubusercontent.com/assets/813985/8451036/a4a60b92-1fe8-11e5-8ce7-
7eea7083c92f.png)

When change params back to `erroneous values` - error did not appear

**Comment by joanhe** [comment]
Thanks for reporting this issue. Internal ticket MAGETWO-39657 is created.

**Comment by piotrekkaminski** [comment]
We are unable to reproduce this error.
