### ISSUE TITLE
Doesn't work sorting in the search list.

### ISSUE THREAD

**Issue by Mulderua** [magento/magento2#1432]
When I find some products and try sort it by name for example, happeneds nothing.

**Comment by Mulderua** [comment]
Steps to reproduce:
1. Use search word 'car' in my case.
2. Click on set ascending/descending button.
3. List didn't change.

**Comment by kokoc** [comment]
@Mulderua thank you for reporting the issue. Internal reference: MAGETWO-39604

**Comment by choukalos** [comment]
Bug in behavior (currently) but it should be noted we plan on removing and always sorting by relevance the search landing page results ( MAGETWO-35967 ).

**Comment by piotrekkaminski** [comment]
Reopened  MAGETWO-39604

**Comment by vladimir-k** [comment]
Hi, @Mulderua 
Fix has been delivered. Feel free to reopen the issue if the problem still reproduces. Thank you for your feedback!

**Comment by Mulderua** [comment]
Hi, @vladimir-k ! 
Thank you for feedback.

**Comment by javariahazoor** [comment]
can anybody send me a solution filters are not working in search list
http://porto.shop.dev.luqon.net/catalogsearch/result/?q=penna
