### ISSUE TITLE
Enable rating by default

### ISSUE THREAD

**Issue by vernard** [magento/magento2#1433]
Currently, reviews do not have ratings. I found out that the ratings are not added on the store views.

Is this intentional? So that ratings are disabled by default?

Or is it not recommended to query store views on `InstallData.php` script?

**Comment by tkacheva** [comment]
@vernard Review rating is not commonly used in Magento thus in off by default. Do you have issues enabling it?

**Comment by vernard** [comment]
This might have ben an issue on the beta. I just checked on current version and everything works fine. It is enabled now and works fine by default.

Closing issue.
