### ISSUE TITLE
Fatal error: Class 'Magento\Framework\HTTP\Client_Curl' not found

### ISSUE THREAD

**Issue by bvdooren** [magento/magento2#1435]
```
$client  = Client::getInstance( 'curl' ); 
```
generates wrong class path on line 37 in class Magento\Framework\HTTP\Client.

Changing this line from this

```
$class = __CLASS__ . "_" . str_replace(' ', '/', ucwords(str_replace('_', ' ', $frontend)));
```

to this 

```
$class = __CLASS__ . "\\" . str_replace(' ', '/', ucwords(str_replace('_', ' ', $frontend)));
```

seems to fix it.

**Comment by joanhe** [comment]
Thanks for reporting this issue. Internal ticket MAGETWO-39658 is created.

**Comment by okorshenko** [comment]
@bvdooren, thank you for reporting the issue. Internal ticket: MAGETWO-39658 has been closed and merged to develop branch.  Please, let us know if you still have an issue
