### ISSUE TITLE
Export products action does not see the store views differences. 

### ISSUE THREAD

**Issue by vdubyna** [magento/magento2#14367]
### Preconditions
1. Magento 2.2.3

### Steps to reproduce
1. Set different product names per store view 
2. Export products

### Expected result

1. In the file we should see all names per store 

### Actual result
1. There is only default name in the file

The issue is caused by mistake in the source code 
https://github.com/magento/magento2/blob/2.2.3/app/code/Magento/CatalogImportExport/Model/Export/Product.php

See the screen:
http://take.ms/3b4zD

**Comment by orlangur** [comment]
Hi @vdubyna, you can refer to particular lines of code like this: https://github.com/magento/magento2/blob/2.2.3/app/code/Magento/CatalogImportExport/Model/Export/Product.php#L935

Could you please post a pull request? It is possible even via GitHub UI and much more convenient to discuss a code change than an issue.

**Comment by vdubyna** [comment]
I’ve opened pull request https://github.com/magento/magento2/pull/14372 to
2.2.4-preview

-- 
Volodymyr Dubyna
Sent with Airmail

On March 26, 2018 at 17:10:33, Vlad Veselov (notifications@github.com)
wrote:

Hi @vdubyna <https://github.com/vdubyna>, you can refer to particular lines
of code like this:
https://github.com/magento/magento2/blob/2.2.3/app/code/Magento/CatalogImportExport/Model/Export/Product.php#L935

Could you please post a pull request? It is possible even via GitHub UI and
much more convenient to discuss a code change than an issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/magento/magento2/issues/14367#issuecomment-376179094>,
or mute the thread

**Comment by magento-engcom-team** [comment]
@vdubyna, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ishakhsuvarov** [comment]
Closing per reporters comment here: https://github.com/magento/magento2/pull/14372#issuecomment-377272633
Fix should be delivered in the next patch release.
