### ISSUE TITLE
Knockout JS One page checkout templates cannot be overridden.

### ISSUE THREAD

**Issue by Zaylril** [magento/magento2#1436]
Hey,

When trying to override the one page checkout templates defined in app/code/Magento/Checkout/view/frontend/web/template/authentication.phtml for example

When copying the file and modifying it and placing in app/design/mypackage/mytheme/Magento_Checkout/web/template/authentication.phtml

The file changes are not picked up and the template is not overridden. Changing the original file reflects my changes (so is not cache)

Is this expected behaviour and i'm placing it in the wrong location or a bug?

This is on beta15.

Thanks

**Comment by alankent** [comment]
I think GitHub munged the path for the theme - did you really use app/design///Magent_Checkout? If I understand, you are creating a theme (themes go under app/design). What was the theme name, and did you enable the theme? My guess is you created it without enabling it in Admin pages. Themes present do not automatically turn on - so you can switch between themes (e.g. Summer, Thanksgiving, Winter, Christmas, etc)

**Comment by Zaylril** [comment]
Hey sorry yep Github messed up my path name at first. However no this isn't a brand new theme, this is a custom one I've been working on for a while. It is definitely working for other fallbacks. It is just the location of some of the templates in the Checkout module are in a different location to the rest i.e 

app/code/Magento/Checkout/view/frontend/web/template/

and not

app/code/Magento/Checkout/view/frontend/templates

Where the other templates are stored

**Comment by alankent** [comment]
(I am officially on leave at present overseas, so I will let someone else check the exact paths. I know the directory structure of modules and themes is different, but I don't recall the structures off the top of my head.)

**Comment by jamescowie** [comment]
+ 1

**Comment by sidolov** [comment]
Hi Richard, your path to template is correct, but i see that template extension is .phtml (must be .html)

For example, template overriding for checkout shipping step: 

Put your template to **your_theme_path/Magento_Checkout/web/template/shipping.html**
**Note**: extension for template file must be .html **NOT** .phtml

And after that remove cached files from **/pub/static** folder.

**Comment by Zaylril** [comment]
@sidolov Tried this now and it works as expected, thanks!

**Comment by vpelipenko** [comment]
Closed. Issue is resolved. @Zaylril, thank you for contacting us.

**Comment by jwittorf** [comment]
I was so glad stumbling over this issue, I'm trying the exact thing in Magento 2.1.1, trying to edit `\vendor\magento\module-checkout\view\frontend\web\template\authentication.html`

I copied the file to `\app\design\frontend\Package\Theme\Magento_Checkout\web\template\authentication.html` and made my changes.

Then I ran the `setup:static-content:deploy` and got the file copied to `\pub\static\frontend\Package\Theme\de_DE\Magento_Checkout\template\authentication.html`, my changes are shown in the file (add a class to the `<button />`)

I cleaned and flushed the caches but I'm still not seeing the added class in the frontend. Has anything changed in the meantime? I thought I've done everything right as written above.

**Comment by wozniakm** [comment]
+1

**Comment by mrkhoa99** [comment]
@jwittorf you tried to clear your Browser Cache? You should disable your Browser Cache or use different browser.

**Comment by wozniakm** [comment]
@mrkhoa99 the problem was caused by browser cache, if you are using Google Chrome simply disable caching in developer tools (probably other browsers has the same functionality)

**Comment by jwittorf** [comment]
Browser caching indeed, thanks for the heads up.

**Comment by rixitpatel13** [comment]
Hi, I got the things but what I am not getting is that How can I apply any custom onchange function for the zip code field on onepage checkout !

because what HTML is displaying, its generating by Knockout JS !

so, please tell me how can I do that !

Thanks in advance !
