### ISSUE TITLE
Circular module dependencies

### ISSUE THREAD

**Issue by joshdifabio** [magento/magento2#1439]
There are a number of circular module dependencies in Magento 2; e.g., `Mage_Quote` depends on `Mage_Sales`, which itself depends on `Mage_Quote`. Presumably these circular dependencies are known and are intended to be resolved eventually?

**Comment by alankent** [comment]
Yes. There are a lot, but less than there used to be.  We have invested in selected areas, but know we have not fixed them all yet. For example, Customer depends on Wishlist, making Wishlist mandatory. Wishlist instead should inject itself into Customer, making Wishlist optional.

Each such dependency takes time to remove. It was less noticable in Magento 1 as you start with all the modules. But we are trying to make unwanted modules optional, so every removal of such a dependency makes it easier to have a slimmer site for functionality you don't want.

**Comment by joshdifabio** [comment]
Thanks for clarifying! Keep up the good work.

I'll let you decide whether or not to close this ticket, I don't mind either way.
