### ISSUE TITLE
Product status changed for all store_views while saving product per store_view

### ISSUE THREAD

**Issue by anil-suthar** [magento/magento2#14390]
### Preconditions

1. Magento 2.2.2 OR 2.2.3
2. Multiple Store views

### Steps to reproduce

1. Create multiple store_views. Check sample image below
![stores settings stores magento admin ap diving](https://user-images.githubusercontent.com/3518141/37965271-1f4b0998-31e2-11e8-89b0-290c3c23f2b6.png)

2. Now go to Edit product > Switch to English store > Disable Product Status (uncheck Use Default Value) > Save
3. Again go to Edit SAME product > Switch to German store > Enable Product Status (uncheck Use Default Value) > Save
4. Switch to English store > Check Product Status > It'll be shown as Enable, while it should remain Disable
### Expected result

1. At step # 4 above, Product Status should remain Disable
2. Should be able to set Product Status per Store_Views
### Actual result
1. Can't keep different Product Statuses per Store Views
2. Product Status is overwritten every time I save product per Store View

**Comment by magento-engcom-team** [comment]
@anil-suthar, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mzeis** [comment]
Hi @kandy, as you mentioned [potential problems](https://github.com/magento/magento2/pull/14579#issuecomment-379240952) when allowing store-view level product status changes: should this issue be closed or what would be the suggested fix for this issue?

**Comment by kandy** [comment]
@mzeis, I believe we should close this issue because the implementation of this requires major changes in business logic and can cause performance issues

**Comment by mzeis** [comment]
Thanks @kandy for clarifying. @anil-suthar thank you very much for reporting this issue. Please understand that we have to close the issue at this time for the mentioned reasons.
