### ISSUE TITLE
dynamicRows "pageSize" settings improperly fetched as string from UiComponent declaration in XML

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#14394]
### Preconditions

1. Magento 2.2.2
2. PHP & MySQL are irrelevant

### Steps to reproduce

1. Create a new ```dynamicRows``` ui component in XML (mine is based on an external data provider, but this is irrelevant for the bug).
2. Specify a "pageSize" via the ```<argument>``` or ```<settings>``` directive (I include both in my example, but none is effective): 

```
            <dynamicRows
                    name="query_ids"
                    sortOrder="200"
                    component="Magento_Ui/js/dynamic-rows/dynamic-rows-grid"
                    template="ui/dynamic-rows/templates/grid"
            >
                <argument name="data" xsi:type="array">
                    <item name="config" xsi:type="array">
                        <item name="columnsHeaderAfterRender" xsi:type="boolean">true</item>
                        <item name="deleteButtonLabel" xsi:type="string" translate="true">Remove</item>
                        <item name="dataProvider" xsi:type="string">search_term_listing</item>
                        <item name="pageSize" xsi:type="number">10</item>
                        <item name="map" xsi:type="array">
                            <item name="id" xsi:type="string">query_id</item>
                            <item name="query_text" xsi:type="string">query_text</item>
                            <item name="is_spellchecked" xsi:type="string">is_spellchecked</item>
                        </item>
                    </item>
                </argument>
                <settings>
                    <addButton>false</addButton>
                    <defaultRecord>false</defaultRecord>
                    <columnsHeader>false</columnsHeader>
                    <recordTemplate>record</recordTemplate>
                    <dataScope>query_ids</dataScope>
                    <additionalClasses>
                        <class name="admin__field-wide">true</class>
                    </additionalClasses>
                    <dndConfig>
                        <param name="enabled" xsi:type="boolean">false</param>
                    </dndConfig>
                    <links>
                        <link name="insertData">${ $.provider }:${ $.dataProvider }</link>
                    </links>
                    <pageSize>10</pageSize>
                </settings>
```

3. Add more items than your page size, to be able to navigate through pages
4. Navigate to page 2

### Expected result

1. Page 2 is displayed properly 

### Actual result

1. Spinner remains displayed.

After digging, I found that this is due to the fact that the pageSize is never parsed as an integer.

Logging the component in the console give me : 

```
...
pageSize : "10"
...
```

If I set arbitrary the pageSize to 10 (as an integer value) in the dynamic-rows.js file, this is working properly, so imho this is clearly a casting problem.

That is quite confusing because when using the ```<argument>``` syntax, I am able to specify ```xsi:type="number"``` for the pageSize, but this does not enforce any casting when building the component.

Same thing occurs when using ```<settings>```, the XSD is stating that ```pageSize``` must be an integer, but this is handled as a string value when initializing the component.

Moreover, this is not the first time I see configuration values for Ui Components are not properly parsed to their due type. (this occurs often with integers or booleans).

**Comment by ghost** [comment]
Hi @romainruaud The fix for this issue has already been fixed in 2.3-develop branch
