### ISSUE TITLE
REST API Carts item-list is missing product_id

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#14391]
### Preconditions

1. Magento v2.2.2

### Steps to reproduce

1. Add items to your shopping cart.
2. Do a search for carts in the API. /V1/carts/search?searchCriteria[pageSize]=1
3. Look at the items in the cart.

### Expected result

1. I expect to see product_id next to sku, name, price, etc.

### Actual result

1. There is no product_id.

I need the product_id because that's what we're referencing in an integration with an external system.

In Magento\Quote\Model\Quote\Item I do see it calling 'setProductId', but the function is not defined for the interface. It seems like an oversight.

**Comment by magento-engcom-team** [comment]
@fvschie thank you for your report. Absence of product id in quote item is correct behavior. If you want to add it, you may create pull request.

**Comment by magento-engcom-team** [comment]
@fvschie, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by fvschie** [comment]
I disagree with your assessment. The code actually calls a setter for the property productId in \Magento\Quote\Model\Quote\Item, which is not implemented, and seems to not be needed for anything else.

It seems like an oversight.

EDIT: I'll consider a pull request. On my local test machine, it's a trivial fix.

**Comment by PaulBoss** [comment]
So a method setProductId is called but does nothing and this is intended behaviour and even labelled as a "non-issue"? That is really disappointing.
