### ISSUE TITLE
Insert product images on multiple websites problem

### ISSUE THREAD

**Issue by guillermogallego** [magento/magento2#14413]
I have created a script to insert images into products, the images are inserted correctly but the labels and roles do not do it for all websites, only for the default website

### Preconditions
Magento 2.2.3
Php 7.1
Centos 7 with CPANEL
I configure 3 Websites and theirs views

### Steps to reproduce
`
use Magento\Framework\App\Bootstrap;

include('../app/bootstrap.php');

// Get all premium products
$pps = $db->query_array("SELECT id_producto, sku FROM productos_has_tienda");

// Magento bootstrap
$bootstrap = Bootstrap::create(BP, $_SERVER);
$objectManager = $bootstrap->getObjectManager();
$state = $objectManager->get('Magento\Framework\App\State');
$state->setAreaCode('frontend');

// Product repository object
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');

// mediaGalleryProcessor
$mediaGalleryProcessor = $objectManager->get('Magento\Catalog\Model\Product\Gallery\Processor');

// Image content object
$imageContent = $objectManager->get('\Magento\Framework\Api\Data\ImageContentInterfaceFactory');

// Image processor
$imageProcessor = $objectManager->get('Magento\Framework\Api\ImageProcessorInterface');

// Get all products to import
$pps = $db->query_array("SELECT id_producto, sku FROM productos_has_tienda");

// for each product to import
foreach ($pps as $p){

  $product = $productRepository->get($p['sku']);

  echo $product->getName()."\n";
  echo "Insert images...\n";

  $images = $db->query_array("
    SELECT s3_name 
    FROM productos_imagen 
    WHERE id_producto = ".$p['id_producto']." 
    ORDER BY id_imagen ASC
  ");

  $ci = 0;
  foreach ($images as $i){
    $newEntry = array();
    $newEntry['disabled'] = false;
    $newEntry['label'] = $product->getName();
    $newEntry['position'] = $ci;
    $newEntry['media_type'] = "image";
    ($ci == 0) ? $newEntry['types'] = ['image', 'small_image', 'thumbnail'] : $newEntry['types'] = [];

    $contentDataObject = $imageContent->create()
      ->setName(getFriedly($product->getName()).".jpg")
      ->setBase64EncodedData(base64_encode(file_get_contents("http://cdns3.amazonaws.com/i/".$i['s3_name']."G")))
      ->setType("image/jpeg");

    $newEntry['content'] = $contentDataObject;

    /** @var ImageContentInterface $contentDataObject */
    $contentDataObject = $newEntry['content'];

    /** @var \Magento\Catalog\Model\Product\Media\Config $mediaConfig */
    $mediaConfig = $product->getMediaConfig();
    $mediaTmpPath = $mediaConfig->getBaseTmpMediaPath();
    $relativeFilePath = $imageProcessor->processImageContent($mediaTmpPath, $contentDataObject);
    $tmpFilePath = $mediaConfig->getTmpMediaShortUrl($relativeFilePath);

    $imageFileUri = $mediaGalleryProcessor->addImage(
      $product,
      $tmpFilePath,
      $newEntry['types'],
      true,
      $newEntry['disabled']
    );

    // Update additional fields that are still empty after addImage call
    $mediaGalleryProcessor->updateImage(
       $product,
       $imageFileUri,
       [
         'label' => $newEntry['label'],
         'position' => $newEntry['position'],
         'disabled' => $newEntry['disabled'],
         'media_type' => $newEntry['media_type'],
       ]
    );

    $ci++;
  }
  $product->save();
}
`

### Expected result
Insert images with labels and roles in all websites

### Actual result
Only in the default website the images have label and roles

**Comment by guillermogallego** [comment]
I think this problem is related to my other entry https://github.com/magento/magento2/issues/14287

**Comment by magento-engcom-team** [comment]
@guillermogallego, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by riconeitzel** [comment]
so, this is still an issue?
