### ISSUE TITLE
Class Pelago\Emogrifier does not exist

### ISSUE THREAD

**Issue by vinhtrau** [magento/magento2#1441]
Class Pelago\Emogrifier does not exist
#0 /var/www/magento2/htdocs/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Widget\\...')
#1 /var/www/magento2/htdocs/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(73): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Widget\\...')
#2 /var/www/magento2/htdocs/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Widget\\...')
#3 /var/www/magento2/htdocs/app/code/Magento/Cms/Model/Template/FilterProvider.php(58): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Widget\\...')
#4 /var/www/magento2/htdocs/app/code/Magento/Cms/Model/Template/FilterProvider.php(82): Magento\Cms\Model\Template\FilterProvider->_getFilterInstance('Magento\\Widget\\...')
#5 /var/www/magento2/htdocs/app/code/Magento/Cms/Block/Page.php(156): Magento\Cms\Model\Template\FilterProvider->getPageFilter()
#6 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(652): Magento\Cms\Block\Page->_toHtml()
#7 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(521): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(497): Magento\Framework\View\Layout->_renderBlock('cms_page')
#9 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cms_page')
#10 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cms_page')
#11 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cms_page', true)
#12 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('cms_page')
#13 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('content')
#14 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#15 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#16 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#17 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#18 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('main')
#19 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#20 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#21 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#22 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#23 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('columns')
#24 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#25 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#26 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#27 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#28 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('main.content')
#29 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#30 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#31 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#32 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#33 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#34 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#35 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#36 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#37 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#38 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(499): Magento\Framework\View\Layout->_renderContainer('root')
#39 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#40 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#41 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#42 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Layout.php(917): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#43 [internal function]: Magento\Framework\View\Layout->getOutput()
#44 /var/www/magento2/htdocs/lib/internal/Magento/Framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#45 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#46 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#47 /var/www/magento2/htdocs/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#48 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#49 /var/www/magento2/htdocs/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#50 /var/www/magento2/htdocs/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#51 /var/www/magento2/htdocs/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#52 /var/www/magento2/htdocs/app/code/Magento/PageCache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#53 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#54 /var/www/magento2/htdocs/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#55 /var/www/magento2/htdocs/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#56 /var/www/magento2/htdocs/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#57 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#58 /var/www/magento2/htdocs/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#59 /var/www/magento2/htdocs/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#60 /var/www/magento2/htdocs/lib/internal/Magento/Framework/App/Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#61 /var/www/magento2/htdocs/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#62 /var/www/magento2/htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#63 {main}

**Comment by akaplya** [comment]
Hi, please follow the installation instruction https://github.com/magento/magento2#step-3-install-and-verify-the-installation
Run composer install/update at application root directory

**Comment by jamescowie** [comment]
Hello @vinhtrau 

This package is loaded via composer's autoloader that is located in `vendor` directory. When composer runs it creates several autoload classes that can be used within a project so that your project in theory contains only logic specific to your domain and with the use of composers vendor directory additional packages can be isolated away and required in as and when. When there was a change in Magento 2 recently it seems that these new package(s) were added but people ( Myself included ) did not run `composer update / install` to ensure we had all the required dependencies to get the project running. 

If you run `composer update` then you should see the composer command line runner showing installing x y and z and if you are using SCM the you will notice that there is a update to composer.lock file that holds the exact reference to that version that has been installed. 

This solves one of my personal headaches of installing packages into the `lib` folder and having to maintain massive projects over time, I like to keep my projects SCM project code only or as much as possible and compose the project together using composer or other tools. Node has NPM etc.

Hope this helps.

**Comment by vinhtrau** [comment]
Thanks all, I fixed by run "compose update".

**Comment by vpelipenko** [comment]
@vinhtrau. Closed as resolved. Feel free to open issues here if you have any questions or faced with problems.

**Comment by brunoribas68** [comment]
Stop working again

In CssInlinerPlugin.php line 18:

  Call to undefined method Pelago\Emogrifier::disableInvisibleNodeRemoval()


Script php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
