### ISSUE TITLE
Braintree Apple Pay Transaction Error - Invalid Card Type Index

### ISSUE THREAD

**Issue by DGTLLee** [magento/magento2#14425]
I have followed the Braintree Apple Pay Sandbox mode set up at [https://developers.braintreepayments.com/guides/apple-pay/configuration/javascript/v3](url) and have successfully received a payment nonce and submitted the order to the guest checkout:

```
{
    "cartId": "********",
    "form_key": "*******",
    "billingAddress": {
        "countryId": "US",
        "regionId": "12",
        "regionCode": "CA",
        "region": "California",
        "street": [
            "1 Main"
        ],
        "telephone": "555-555-5555",
        "postcode": "90067",
        "city": "Sometown",
        "firstname": "asdf",
        "lastname": "qwer",
        "saveInAddressBook": null
    },
    "paymentMethod": {
        "method": "braintree",
        "additional_data": {
            "payment_method_nonce": "***********"
        }
    },
    "email": "qwer@asdf.com"
}
```

It processes on the Braintree side and begins the process in Magento but I get : 

```
"An error occurred on the server. Please try to place the order again.", 
"trace":"#0 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder..." 
```

When I dig a little deeper, it appears that the Transaction response has two payment type attributes - "applePay" and "creditCard". For example

            [creditCard] => Array
                (
                    [token] => ******
                    [bin] => 
                    [last4] => 
                    [cardType] => 
                    [expirationMonth] => 
                    [expirationYear] => 
                    [customerLocation] => 
                    [cardholderName] => 
                    [imageUrl] => https://assets.braintreegateway.com/payment_method_logo/unknown.png?environment=sandbox
                    [prepaid] => Unknown
                    [healthcare] => Unknown
                    [debit] => Unknown
                    [durbinRegulated] => Unknown
                    [commercial] => Unknown
                    [payroll] => Unknown
                    [issuingBank] => Unknown
                    [countryOfIssuance] => Unknown
                    [productId] => Unknown
                    [uniqueNumberIdentifier] => 
                    [venmoSdk] => 
                )

            [applePay] => Array
                (
                    [token] => ******
                    [cardType] => Apple Pay - Visa
                    [last4] => 1881
                    [expirationMonth] => 05
                    [expirationYear] => 2018
                    [cardholderName] => Visa Apple Pay Cardholder
                    [imageUrl] => https://assets.braintreegateway.com/payment_method_logo/apple_pay.png?environment=sandbox
                    [paymentInstrumentName] => Visa 0492
                    [sourceDescription] => Visa 0492
                )

Even though creditCard contains no real information it is still passed through the system because /vendor/braintree/braintree_php/lib/Braintree/Transaction.php is a series of "if(isset())" statements.

```
 if (isset($transactionAttribs['applePay'])) {
            $this->_set('applePayCardDetails',
                new Transaction\ApplePayCardDetails(
                    $transactionAttribs['applePay']
                )
            );
        }
...

    if (isset($transactionAttribs['creditCard'])) {
            $this->_set('creditCardDetails',
                new Transaction\CreditCardDetails(
                    $transactionAttribs['creditCard']
                )
            );
        }
```

So since, the creditCard object is filled with "Unknown" and empty values it causes the error on line 91 of /vendor/magento/module-braintree/Gateway/Response/CardDetailsHandler.php because of an "unknown index". This is because it is trying to get the index of the empty type passed from the creditCard Transaction array in "$mapper[$replaced]" : 

```
private function getCreditCardType($type)
    {
        $replaced = str_replace(' ', '-', strtolower($type));
        $mapper = $this->config->getCctypesMapper();

        return $mapper[$replaced];
    }
```
This seems to be where the error is thrown which stops the payment from being saved.

### Preconditions

1. Magento 2.1.9
2. Braintree JS - client.min.js 3.4 and apple-pay.min.js v3.4

### Steps to reproduce

1. Submit Order
2. Obtain Apple Paypal nonce
3. Send customer payment information to guest checkout

### Expected result

1. Successful checkout

### Actual result

1. Receive "An error occurred on the server. Please try to place the order again.", 
"trace":"#0 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder..."

**Comment by YevSent** [comment]
Hi, @DGTLLee, the current implementation of Braintree integration based on Braintree JS SDK V2 and doesn't support Apple Pay feature.

Closed, as not a bug.

**Comment by bvboas** [comment]
@joni-jones,

Sorry but this is a Bug. 

Even if Magento does not support Apple Pay, there is not reason why a proper cardType availability is put in place and an exception thrown

```php
if(!isset($mapper[$replaced])){
    throw new \Exception('Payment type %1 not available', $type);//Or something like this...
}
```
