### ISSUE TITLE
Running 'log:clean' through cli results in an error: 'Area code not set'

### ISSUE THREAD

**Issue by hostep** [magento/magento2#1442]
Hi

I'm using 0.74.0-beta16.

When I run the following command, it throws errors:

```
➜ php bin/magento log:clean

  [Magento\Framework\Exception\SessionException]
  Area code not set: Area code must be set before starting a session.

  [Magento\Framework\Exception\LocalizedException]
  Area code is not set

log:clean [--days="..."]
```

This is probably related to https://github.com/magento/magento2/issues/1405

**Comment by mazhalai** [comment]
@hostep thank you for reporting this issue, we have created ticket MAGETWO-39841 to track this issue.

**Comment by piotrekkaminski** [comment]
This issue should be fixed already.
