### ISSUE TITLE
Custom Attribute Product - Checkout Page - Shipping Module - ObjectManager Instance

### ISSUE THREAD

**Issue by mageuser** [magento/magento2#14427]
Magento 2.2.3

im trying to get custom attribute from product, i've make 3 news attributes (width, height, length). I want get it to quote shipping value.
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$items = $cart->getQuote()->getAllVisibleItems();

foreach($items as $item){
$width = $item->getData('width');
//NOT WORKING
}
```

**Comment by magento-engcom-team** [comment]
@kauansoft  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
