### ISSUE TITLE
Mistake with loading an order in Invoice model

### ISSUE THREAD

**Issue by springimport** [magento/magento2#14424]
### Preconditions
I try to get an extension attributes from Order using the Invoice model.

### Steps to reproduce
Use [getOrder()](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Invoice.php#L239) in Ivoice model.

### Expected result
Invoice getOrder() uses orderRepository ([Shipment](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Shipment.php#L204) as an example).

### Actual result
Invoice getOrder() uses orderFactory.

PHP 7.1. Magento 2.2.3.

**Comment by orlangur** [comment]
@springimport there is no mistake here, just don't mix legacy models with new approach sticked to repositories.

You are not supposed to get order with extension attributes like `$invoice->getOrder()`, such approach violates Law of Demeter. Simply obtain order model via order repository.

**Comment by springimport** [comment]
@orlangur Ok, what should I to do?
```php
$this->orderRepository->get($invoice->getOrderid());
```

**Comment by orlangur** [comment]
@springimport yep, code like this should do the trick.
