### ISSUE TITLE
Issue with Multi-currency in bundle product

### ISSUE THREAD

**Issue by ragun91** [magento/magento2#14420]
We are facing an issue with adding bundle product to cart by switching the store currencies. Amount get twice in child product. Please share us the solution for the below scenario.

### Preconditions

1.OS : Ubuntu 16.04
2.PHP version : 7.0.28
3.Magento version : 2.2.3
4.Browser : Crome
5.Currency Enable : USD, EURO
6.Mysql  Ver : 14.14

### Steps to reproduce

Product cost in USD will be 100 and EURO will be 80.80
a) Now a customer click add to cart for a bundle product with store currency as EURO with one quantity and the product is added to cart with mini-cart updated successfully with price EURO 80.80.
b) Customer switch the currency to USD and check the mini-cart now the amount will be USD 100.
c) Customer again add a quantity of bundled product to cart, now the mini-cart is getting changed to USD 400 instead of USD 200.

![shopping cart](https://user-images.githubusercontent.com/5187339/38032331-ff9cb16c-32ba-11e8-9eb5-1e7729dcbd28.png)
![000000001 orders operations sales magento admin](https://user-images.githubusercontent.com/5187339/38032338-04b8d720-32bb-11e8-8c36-3a0209d448a4.png)

### Expected result

1. We need to get subtotal as 200 with two QTY

### Actual result

1. We get subtotal 400 with two QTY.

**Comment by magento-engcom-team** [comment]
Hello @ragun91, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Aswathy1993** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@Aswathy1993 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**
Product cost in USD will be 114.33 and EURO will be 80.80
a) Now a customer click add to cart for a bundle product with store currency as EURO with one quantity and the product is added to cart with mini-cart updated successfully with price EURO 80.80.
b) Customer switch the currency to USD and check the mini-cart now the amount will be USD 114.33.
c) Customer again add a quantity of bundled product to cart.

**Result**
The subtotal is 228.66 with two QTY
![Screenshot_49](https://user-images.githubusercontent.com/51681435/71588575-a9772500-2b2a-11ea-96ab-3083c60b158b.png)
![Screenshot_50](https://user-images.githubusercontent.com/51681435/71588567-a0865380-2b2a-11ea-8ba8-5ab3ae758158.png)
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
