### ISSUE TITLE
How Can I I want to create Kurdish (ku_IQ)  New language in magento 2 admin panel Locale Options?

### ISSUE THREAD

**Issue by matinict** [magento/magento2#14431]
How Can I I want to create Kurdish (ku_IQ)  New language in magento 2 admin panel Locale Options?

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
Hello @matinict. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical and programming questions.

Thank You.

**Comment by matinict** [comment]
Magento Global Framwork Why Not exist Kurdish Language? And also No proper & clear official documentation add new language 

I am trying die hard but nothing got yet https://magento.stackexchange.com/questions/220119/how-can-i-add-new-language-in-magento-2-admin-panel-locale-options
