### ISSUE TITLE
Install extension successful and then make it disappear from admin setting without disabling it to run it in background

### ISSUE THREAD

**Issue by HeliumRaccoon** [magento/magento2#14432]
Install extension successful and then make it disappear from admin setting without disabling it to run it in background

### Steps to reproduce

1. Install any extension successful 
2. do not disable the extension from admin 
3. remove it module XML file
4. extension setting will disappear from admin
5. extension setting will disappear module list
### Expected result
1. so it will still run like background app without any notice
2. If any adversary can install any malicious extension in Magento it will run like a magic without any notice 
3. bingo

**Comment by magento-engcom-team** [comment]
@HeliumRaccoon ,please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
