### ISSUE TITLE
Getting an error "Mismatched anonymous define() module: function ($)" While using Other Js

### ISSUE THREAD

**Issue by Sathishkumar8731** [magento/magento2#14441]
In Magento 2.2.2

Whenever, we are trying to use any third party jQuery Plugin we are getting below error message

Mismatched anonymous define() module: function ($). 

Especially, when we try to use the Timepickers and datetime pickers Js. 

We also defined the js in require-config.js file. But we are still facing issue.

Here are the some of JS plugins

https://xdsoft.net/jqplugins/datetimepicker/
http://timepicker.co/

**Comment by magento-engcom-team** [comment]
Hi @Sathishkumar8731 Thank you for reporting
Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks
