### ISSUE TITLE
Limited validation for coupon codes

### ISSUE THREAD

**Issue by bydrei** [magento/magento2#14442]
Validation for coupon codes is very limited. I'm trying to validate coupon codes by checking if that coupon code is valid for the store being used at and display an error message to the customer.

After some digging in the core code. I see there is a table called `salesrule_website` which stores coupon code id's and their associated websites. However this does not work as expected, if you create a coupon code and assign to one website it will still add the other website not select to the database. Further more magento seem to only use this table to store data. It doesn't do anything else like modifying, delete or even retrieve.

I see there is a virtual type declaration in the SalesRule module di.xml, but the class `Magento\SalesRule\Model\ResourceModel\Rule\AssociatedEntityMap` doesn't exist, also in `\Magento\SalesRule\Model\ResourceModel\Rule` there is a function called `getAssociatedEntitiesMap` which I guess would return the information I need but this doesn't work for the above reason and is not really extendible because the method is private.

```
<virtualType name="Magento\SalesRule\Model\ResourceModel\Rule\AssociatedEntityMap" type="Magento\Framework\DataObject">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="website" xsi:type="array">
                    <item name="associations_table" xsi:type="string">salesrule_website</item>
                    <item name="rule_id_field" xsi:type="string">rule_id</item>
                    <item name="entity_id_field" xsi:type="string">website_id</item>
                </item>
                <item name="customer_group" xsi:type="array">
                    <item name="associations_table" xsi:type="string">salesrule_customer_group</item>
                    <item name="rule_id_field" xsi:type="string">rule_id</item>
                    <item name="entity_id_field" xsi:type="string">customer_group_id</item>
                </item>
            </argument>
        </arguments>
    </virtualType>
```

The way coupon codes are being validated is by checking if the customer address has a coupon code set against it.

### Preconditions

1. Magento EE 2.1.12
2. PHP 7.0.27
3. Have multiple website views.

### Steps to reproduce

1. Create new coupon assign it to a website.

### Expected result

1. Creating a new coupon will add only the selected website to `salesrule_website` table.
2. This should also update if I decide to change website in the coupon configuration.

### Actual result

1. All stores get added

By the way here's my current work around. Create a custom function and use the resource connection to build this query.

```
SELECT `rule_coupons`.`code` 
	FROM `salesrule` AS `main_table`
 		INNER JOIN `salesrule_website` AS `website` ON website.website_id IN ('1') AND main_table.row_id = website.row_id
 		INNER JOIN `salesrule_customer_group` AS `customer_group_ids` ON main_table.row_id = customer_group_ids.row_id AND customer_group_ids.customer_group_id = 0
 		LEFT JOIN `salesrule_coupon` AS `rule_coupons` ON main_table.rule_id = rule_coupons.rule_id AND main_table.coupon_type != 1
 		WHERE rule_coupons.code = "andreferraz1"
```

**Comment by magento-engcom-team** [comment]
@ferrazzuk, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.3, 2.3.0-dev, 2.1.12
