### ISSUE TITLE
Magento 2.0.18 Installation,  Readiness Check errors

### ISSUE THREAD

**Issue by Mbouali963** [magento/magento2#14447]
I'm trying to install Magento 2.0.18 on my server and I got stuck at the first step in the Readiness Check,
it keeps returning "Server failed to respond. Please try again."

and below is a screenshot of the actual results : 
![screencapture-olfactive-net-boutique-olfactive-setup-2018-03-29-16_05_21](https://user-images.githubusercontent.com/8673371/38096705-7330df08-336b-11e8-880d-433238208504.png)

what could be the reason ? and how can I solve that

**Comment by magento-engcom-team** [comment]
Hi @Kepra 
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
