### ISSUE TITLE
[2.2.3EE] Custom modules in app/code are not scanned

### ISSUE THREAD

**Issue by tmoreau** [magento/magento2#14446]
Modules in app/code are not scanned

### Preconditions
1. Magento 2.2.3EE, PHP 7.1.15
2. CLI installation
3. Successfull installation

### Steps to reproduce
1. setup simple module (Alger/Skeleton or MagePlaza/HelloWorld) (following strictly the direcotry structure and the example files provided)
2. run magento setup:upgrade or magento module:enable <modulename>

### Expected result
1. Module is seen/recognized
2. app/etc/config.php is updated with the module's name

### Actual result
1. nothing
setting inotifywait on app/code shows no action done on that path, while vendor/ is scanned

**Comment by ghost** [comment]
HI @tmoreau thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
