### ISSUE TITLE
PayPal in the UK

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1444]
Hi,

On Magento 1.xx there was a separate module for PayPal in the UK. Is this also in development for Magento2 or it not required and they existing module in beta16 works in the UK?

**Comment by vpelipenko** [comment]
@craigcarnell, yes. PayPal module can be used for UK.

**Comment by vpelipenko** [comment]
Do you have another questions?

**Comment by craigcarnell** [comment]
@vpelipenko No thanks!
