### ISSUE TITLE
Open developer on windows 7 is failed ---Magento2.2

### ISSUE THREAD

**Issue by forwells** [magento/magento2#14458]
ps : I just want open developer mode on windows 7
### Preconditions

1. Magento2.2.2
2. php7.0.28
3. mysql5.7
4. on Windows 7
### Steps to reproduce

1. in the cmd.exe and magento CLI dir  (<install_dir>/bin/)
2. to execute php magento deploy:mode:set developer
3. to visit the home page

### Expected result

everything about magento2.2 is worked well

### Actual result

1. [Screenshot, logs]
![pro](https://user-images.githubusercontent.com/32950945/38128882-1cd3fac2-342f-11e8-8321-c8f82fce00e4.png)

2.but it is tell me the "block" is not allow

**Comment by forwells** [comment]
I try to update env.php , change MAGE_MODE 'default'=>'developer', but this method don't tell me any error,why ?, just fell I'm fooli

**Comment by forwells** [comment]
After repeated opening and closing, I found that opening the developer mode in env.php still causes the above problem.

**Comment by magento-engcom-team** [comment]
@Low-config , Can you reproduce an issue using a supported operating system: [Magento 2.2.x technology stack requirements](http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html)? 
Note that Windows is not in the list.

**Comment by forwells** [comment]
@magento-engcom-team Thank you for attension this issue
At present, I have a project on Ubuntu 16.04, but after I started developer mode, the same problems occurred like windows.

**Comment by forwells** [comment]
Preconditions
   Magento2.2.2
   php7.0.28
   mysql5.7
   on Ubuntu16.04
   server : nginx 1.10
Steps to reproduce
in the cmd.exe and magento CLI dir (<install_dir>/bin/)
to execute php magento deploy:mode:set developer
to visit the home page
Expected result
everything about magento2.2 is worked well

Actual result
![pro](https://user-images.githubusercontent.com/32950945/38130455-c22a4322-3435-11e8-9dc6-7b9e1052a3c8.png)

both are the same

**Comment by magento-engcom-team** [comment]
@Low-config , We were not able to reproduce this issue by following the steps you provided. Please add more details to your description of the steps you followed when identifying this issue, and any other information needed to reproduce your issue. Do you use any extensions or themes or third-party custom code? Please try to redroduce this issue in a clean instalation.

**Comment by ishakhsuvarov** [comment]
Hi @Low-config 
Thank you for reporting.

First line of the error report suggests that you have an invalid layout somewhere. Try disabling/inspecting all of the extensions and customizations applied to your installation or try with the clean installation instead.

**Comment by forwells** [comment]
@magento-engcom-team Thank you , I will try!~

**Comment by franciskim** [comment]
@Low-config might be a long shot but you could try this: [My ‘Fix All’ One Liner Command for Magento 2](https://franciskim.co/my-fix-all-one-liner-command-for-magento-2/)

**Comment by moElwan** [comment]
Are you upgrading from other version or it's a fresh installation?
looks like layout issue

**Comment by forwells** [comment]
@Mohamed-Elwan yes, I am freshly installed, and the issue just occuring when I turn on developer mode~
and the problem still exists until now~

I see , but I try it before,and the way is not worked

**Comment by forwells** [comment]
I printed $xml in _initDom($xml) in Magento\Framework\Config\Dom.php
An exception started from the layout tag, but I don't know why
![1](https://user-images.githubusercontent.com/32950945/38724066-ad6dbf1c-3f35-11e8-9170-c6b05a675eaf.png)

**Comment by forwells** [comment]
@magento-engcom-team Yes.I determined where the problem lies，Is really a problem with a third-party plugin
