### ISSUE TITLE
lastInsertId returns 0 when PK is not AI

### ISSUE THREAD

**Issue by daancart2quote** [magento/magento2#1445]
It is about this snippet of code in: `\Magento\Framework\Model\Resource\Db\AbstractDb::save`
```
if ($this->_isPkAutoIncrement) {
    unset($bind[$this->getIdFieldName()]);
}
$this->_getWriteAdapter()->insert($this->getMainTable(), $bind);

$object->setId($this->_getWriteAdapter()->lastInsertId($this->getMainTable()));
```

If `$this->_isPkAutoIncrement` is false, the id set in the database isn't generated, and therefore, `lastInsertId` returns `0`. 
Because that translates to `SELECT LAST_INSERT_ID();` and that function returns only generated ID's.

I guess a way to solve this would be to replace the line:
```
$object->setId($this->_getWriteAdapter()->lastInsertId($this->getMainTable()));
```
for:
```
if ($this->_isPkAutoIncrement) {
    $object->setId($this->_getWriteAdapter()->lastInsertId($this->getMainTable()));
}
```
That way the already correct Id on `$object` isn't overwritten by `0` if the PK is not AI.

**Comment by vpelipenko** [comment]
@daancart2quote, thank you for pointing this issue. It will be processed in internal ticket: https://jira.corp.x.com/browse/MAGETWO-39769.

**Comment by daim2k5** [comment]
fixed. If not please feel free to reopen the issue
