### ISSUE TITLE
Custom customer attributes don't show in admin unless they're configured to show on frontend

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#14456]
Custom customer attributes don't show in admin unless they're configured to show on either "Customer Registration" or "Customer Account Edit" forms. This is incorrect, as a custom customer attribute should always show in the admin customer create/edit forms.

### Preconditions
1. Install Magento 2.2.3 Commerce with sample data

### Steps to reproduce
1. Create a customer attribute using settings like this:
![magento admin-7yrfv](https://user-images.githubusercontent.com/129031/38112437-86b9ee92-3367-11e8-83de-e46f3d82f232.jpg)
    1. Note: I'm giving steps to reproduce this on Commerce, but this issue also exists for customer attributes created via upgrade scripts on Open Source, thus why I'm creating this issue on Github rather than submitting a support ticket.
2. Go to create a new customer: CUSTOMERS > All Customers > Add New Customer

### Expected result
1. The "Test Attribute" attribute should show:
![magento admin-h2fjc](https://user-images.githubusercontent.com/129031/38112814-b362902e-3368-11e8-9f75-f11a5b9dab54.jpg)

### Actual result
1. The "Test Attribute" attribute does not show: 
![magento admin-tkue6](https://user-images.githubusercontent.com/129031/38113020-5685fdcc-3369-11e8-8dae-2b282c9df7e3.jpg)
    1. If you edit the attribute again and select either "Customer Account Edit" or "Customer Registration" from the list, you'll see the attribute. 
![magento admin showmecables com-cmv60](https://user-images.githubusercontent.com/129031/38112995-3c6e3814-3369-11e8-84b4-e7b808991683.jpg)

This is a regression in Magento 2.2.x. It's due to [this code](https://github.com/magento/magento2/blob/2.2.3/app/code/Magento/Customer/Model/Customer/DataProvider.php#L389) checking for `customer_account_edit` and `customer_account_create`.

**Comment by erikhansen** [comment]
I needed an immediate workaround for this, so I applied [this patch](https://github.com/magento/magento2/files/1862029/github-issue-14456-show-customer-attributes-in-admin.patch.zip) to the `magento/module-customer` Composer package using [cweagans/composer-patches](https://github.com/cweagans/composer-patches). This is obviously not the correct solution, but it's a sufficient workaround in the short term.

**Comment by magento-engcom-team** [comment]
Hello @erikhansen. This issue is actual for Commerce Edition only - this functionality is not available in Open Source Edition. So please address it directly to Magento Support. Thank You.

**Comment by erikhansen** [comment]
@magento-engcom-team This issue is actually also reproducible in Open Source, as I alluded to in my "Steps to reproduce" section. If you look at [this Open Source-based article](https://www.mageplaza.com/magento-2-module-development/magento-2-add-customer-attribute-programmatically.html#step-3-create-custom-attribute) you'll see that when you create custom customer attributes, you have to specify the "Used in forms" value just like when you create it in the admin:

![09-05-11 magento 2 add customer attribute programmatically - devdocs mageplaza-ed77e](https://user-images.githubusercontent.com/129031/38140530-bd9c2f28-33f9-11e8-82c5-8ef727effeb6.jpg)

I'm reopening this issue since this issue is affecting Open Source.

**Comment by torhoehn** [comment]
I'm having the same problem with custom customer attributes.

**Comment by duckchip** [comment]
same problem here in Magento 2.2.3 Open Source

**Comment by intelsteel** [comment]
Same issue here. custom attributes are not available in customer account. Please provide us solution

**Comment by duckchip** [comment]
@magento-engcom-team  Can you please reopen this issue as it's reproducible on the community edition?

**Comment by ghost** [comment]
@erikhansen, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by maderlock** [comment]
This ticket has been oddly quiet for a long time given the severity of it. Any progress?

**Comment by erfanimani** [comment]
Wow.. just spent an entire afternoon wondering why my attribute wouldn't show up :'(

Interestingly enough, it did show up when trying to edit the customer row inline in the admin grid. Also, 2.1.11 doesn't "seem" to have this issue (don't recall having come across this issue on a store running 2.1.11).

Thanks for the patch @erikhansen

**Comment by tdgroot** [comment]
I'm not proud of saying it, but apparently you can work around it by setting `user_defined` to false: [DataProvider.php#341](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/Model/Customer/DataProvider.php#L341).

**Comment by sdzhepa** [comment]
Hello @erikhansen @tdgroot @erfanimani @maderlock 

Thank you for contribution and collaboration!

The corresponding internal ticket `MAGETWO-93521` was fixed and closed by Magento team

Please see details in the next commit(s):
- 0e81013

**Comment by mihaimatei** [comment]
Should probably be labeled as Fixed in 2.2.9. ( Reference: https://github.com/magento/magento2/blame/0a1a283cd6a0cf4b98a051867f90150c9490fcec/app/code/Magento/Customer/Model/Customer/DataProvider.php#L384 )
