### ISSUE TITLE
grunt exec:<theme> fails to create symlinks with @import statements

### ISSUE THREAD

**Issue by ghost** [magento/magento2#14459]
For some reason symlinking does not work when you start the file with `@import` statements.

When I comment out the below lines the symlinks are created and grunt watch works.

```
/*
@import url('https://use.fontawesome.com/releases/v5.0.8/css/all.css');
@import url('https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i');
*/
```

### Preconditions
1. Magento 2.2.3
2. PHP 7.0.27
3. MySQL 5.7.21
4. macOS 10.13.3

### Steps to reproduce
1. Create a module with custom LESS in "/view/frontend/web/css/source/_module.less"
2. Add an `@import` statement in top of file
3. Run grunt exec:luma

### Expected result
_module.less is symlinked to theme

### Actual result
_module.less is copied

**Comment by ghost** [comment]
Hi @rasmuswikman Symlink is not created, and a copy of the processed file is published to pub/static instead, if the source file differs from the processed one. One of the reasons of this difference might be the usage of the @import directive without file extension in the source file. See The @import directive usage for more details.
 https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/css-preprocess.html

**Comment by riconeitzel** [comment]
If anyone comes here because one or more *.less files are copies instead of symlinks and grunt watch doesn't watch these files:

See here: https://magento.stackexchange.com/a/310705/5988
