### ISSUE TITLE
Git upgrade and custom theme

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#1446]
Hello, 

Im looking at a interesting issue, I have been following the beta's recently and working on the same code base to develop modules / themes. During this time I have been updating my composer.json file with the incremental updates to Magento and updating the version number. 

One strange thing that happens each time a new version is released is that my custom theme gets deleted..

**Comment by buskamuza** [comment]
Hi @jamescowie , 
could you, please, clarify the steps you take to update Magento? In the title you mention "git", but in the description you say about "composer".

**Comment by jamescowie** [comment]
Hi @buskamuza the steps I take are: 

1) Edit composer.json file updating the version number for Magento: 
  ` "magento/product-community-edition": "0.74.0-beta16"` Here I updated to beta version 16 from 15

2) Then from the command line I run `composer update` to get the new package versions 

3) Finally I run `git status` to see what the difference has been code wise and I can see that the theme I have created under `app/design/frontend/James` is marked for deletion. Now there is the argument that this theme _should_ be installed via composer however this theme serves no purpose being in its own package so its committed to my mainline repository. 

Having a quick look at the code it seems that when the composer post-update/install hooks kicks in it manipulates the entire `app/design` folder causing it to be removed and re copied over from the `vendor` folder but this is as far as I have gotten. Not sure if you have any thoughts our if you can replicate it. 

Id say this is not a critical bug as I can easily restore the files and its more noticeable because versions are being released more frequently however it is annoying :). Let me know how you progress and what I can do to help.

**Comment by buskamuza** [comment]
Thanks, @jamescowie .
Good finding! I've created an internal ticket for it - MAGETWO-39785.
> Id say this is not a critical bug

I'd say it's critical... So we'll fix it ASAP.

**Comment by jamescowie** [comment]
Thanks @buskamuza Reason I say not urgent is that its easy to run `git checkout app/design/frontent/James` but I am also happy that you are looking at working on this. 

I have tracked the bug down into the composer hooks now I have a feeling that perhaps one of the theme comoser.json mappings is being a little over excited with its folder paths hence the large delete and re apply. Is it worth me spending any more time on fixing this or would this be classed as an internal ticket ?

**Comment by buskamuza** [comment]
Thanks for so deep investigation, @jamescowie !
You're right about the cause. It's an easy fix for us and impossible fix for you :) due to the way how we publish composer packages. So don't worry, we'll fix it internally and let you know, when the fix will be public.

**Comment by piotrekkaminski** [comment]
The issue was fixed.
