### ISSUE TITLE
[Product Flat Reindex] 501'st product will never be updated

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#14462]
### Preconditions

1. Magento CE/EE (2.2.3 or 2.1.12) with Sample Data.
2. Enabled Flat Tables (BO -> Stores -> Configuration -> Catalog -> Catalog -> Storefront -> Use Flat Catalog Product).
3. Indexer set to 'UPDATE BY SCHEDULE' mode (BO -> System -> Index Management).
4. Initial reindex was done and flats already created.

### Steps to reproduce

1. Update any 500 products (Should be added 500 unique product ids into table 'catalog_product_flat_cl'). E.G.
`update catalog_product_entity_varchar set value = value where attribute_id = 73 and entity_id in (select entity_id from catalog_product_entity) and entity_id != 8  limit 500;`
2.  Update one more product with special price. E.G. product id is 8. 
` SET @special_price = 10; SET @product_id = 8; SET @attribute_code = 'special_price'; INSERT INTO catalog_product_entity_decimal (attribute_id, store_id, entity_id, VALUE) SELECT attribute_id, 0 AS store_id, @product_id, @special_price AS special_price FROM eav_attribute WHERE attribute_code = @attribute_code ON DUPLICATE KEY UPDATE VALUE = @special_price;
` 
3. Run cron manually (twice!). E.G. php bin/magento cron:run
4.  Go To Frontend -> Gears -> Bags.
5. Find product with id №8 (Product Name - Voyage Yoga Bag)

### Expected result

1. Product special price was applied.

### Actual result

1. Product special price was not applied.

### Additional information
I will share my research results.
1. Magento has batch size for flat reindex \Magento\Catalog\Helper\Product\Flat\Indexer::BATCH_SIZE
2. For each batch iteration will called method \Magento\Catalog\Model\Indexer\Product\Flat\TableBuilder::build
3. In method from point #2 will be created temporary table and filled with data from the batch.
4. Due to field \Magento\Catalog\Model\Indexer\Product\Flat\TableBuilder::$_isExecuted, temporary table will be filled only once for the products from the first batch.

Solution could be in re-filling temporary table for each batch.

**Comment by convenient** [comment]
Is this the same issue as #10616 ?

>The 500+ products will NOT be able to update against flat tables and remain the old values, or
for new products, not exist at all.

**Comment by swnsma** [comment]
Exactly!
Thanks!

Unfortunately we noticed 40% degradation of performance (tested on 2000 products) after implementation of the same fix as in PR #10616.
Does there are any info will be #10616 ported to 2.1 or 2.2 ? (If yes, then when?)

**Comment by convenient** [comment]
Haha I would expect a performance decrease when there are more than 500 products as its now actually trying to index them rather than ignoring them. But still not great is it.

**Comment by ghost** [comment]
Hi @swnsma, thank you for you report,  the fix for this issue has already in 2.2-develop & 2.3-develop branch
