### ISSUE TITLE
Product Import: Please make sure attribute "url_key" is not empty. 

### ISSUE THREAD

**Issue by duffner** [magento/magento2#14478]
### Preconditions

1. Magento 2.2.3 
2. Import headers as below. 

`sku,url_key,color,shape,shop_by_finish,tile_material,tile_size2,categories,name,description,short_description,weight,price,meta_title,meta_keywords,meta_description,qty,base_image,base_image_label,small_image,small_image_label,thumbnail_image,thumbnail_image_label,attribute_set_code,product_type,product_websites,product_online,tax_class_name,visibility
`
### Steps to reproduce

1. Create .csv import with column url_key empty for each row in .csv 
2. All other validations pass
3. Press Check data, it gives the error: Please make sure attribute "url_key" is not empty. 

### Expected result

1.  url_key is not a required column according to documentation.  This should pass validation and a url key should be created programmatically if not defined upon import.  

### Actual result

1. Can't create products without specifying url_key 

I'm guessing it was broken by this ticket: https://github.com/magento/magento2/issues/12641  
This was URL key being generated by the import even the column wasn't defined, which is what I'm expecting as well.   My guess is that the column url_key should be specified but empty for new products.

**Comment by koenner01** [comment]
As a temporary solution you could use \Magento\Framework\Filter\FilterManager which contains a function translitUrl() where you can pass the product name to 'generate' the url_key

**Comment by sylvainraye** [comment]
Problem is still there and annoying on Magento 2.2.4.

It's also related to this fix https://github.com/magento/magento2/issues/12083 which break the fact that `url_key` can be set to '' (empty string) via the class `vendor/magento/module-catalog-import-export/Model/Import/Product.php:1563` => `$rowData[self::URL_KEY] = $this->getUrlKey($rowData);`.

@koenner01 doing that means that you overwrite existing url_key which is not always expected

**Comment by ghost** [comment]
Hi @duffner hank you for your report.
The issue is already fixed in 2.2-develop branch
