### ISSUE TITLE
magento woking slow after installation

### ISSUE THREAD

**Issue by amit0505** [magento/magento2#14475]
magento woking slow after installation it take processing countinue 4-5 hours .
how i can fix this issue.

**Comment by magento-engcom-team** [comment]
Hi @amit0505 Thank you for reporting.
Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks
