### ISSUE TITLE
Hello, when i register new customer on magento 2 , it gives error We can\'t save the customer, how to solve 

### ISSUE THREAD

**Issue by deepshik** [magento/magento2#14488]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by ghost** [comment]
@deepshik, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
