### ISSUE TITLE
Keep getting "invalid date" message when trying to add voucher in marketing despite date(s) being valid

### ISSUE THREAD

**Issue by 47Things** [magento/magento2#14483]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/37965430/38167905-e2efab9a-3536-11e8-8641-f051690c224a.png)

**Comment by ghost** [comment]
@47Things, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
