### ISSUE TITLE
Customer export not work with custom attribute

### ISSUE THREAD

**Issue by nans** [magento/magento2#14495]
### Preconditions

Version 2.0.18:
php 5.6 & 7.0;
Mysql Ver 14.14 Distrib 5.1.73;

Version 2.1.12:
php 5.6 & 7.0;
Mysql Ver 14.14 Distrib 5.1.73;

Version 2.2.3:
php 7.0 & 7.1;
Mysql Ver 14.14 Distrib 5.1.73;

Version 2.3.0-dev:
php 7.0 & 7.1;
Mysql Ver 14.14 Distrib 5.1.73;

### Steps to reproduce

1. Create customer custom attribute with type int [like there](https://github.com/nans/MagentoBug/blob/master/Setup/InstallData.php) 
2. Add field to customer grid by [customer_listing.xml](https://github.com/nans/MagentoBug/blob/master/view/adminhtml/ui_component/customer_listing.xml)
3. Create customers (2 or more) with new attributes (check table customer_entity_int on records);
4. Try to export
4.1 Do not check customer ids checkboxes and press on button Export -> CSV -> Export
Actual result: bug
Expected result: csv file with data
4.2 Select some customers and press on button Export -> CSV -> Export
Actual result: bug
Expected result: csv file with data
4.3 Choose all customers and press on button Export -> CSV -> Export
Actual result: csv file with data;
Expected result: csv file with data

### Bug reports
[ver. 2.0.18](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.0.18.txt)  
[ver. 2.1.12](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.1.12.txt)  
[ver. 2.2.3](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.2.3.html)  
[ver. 2.3.0-dev](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.3.0-dev.html)

**Comment by ghost** [comment]
@nans, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by joachimVT** [comment]
**Working on magento 2.2.7**
This issue should be reopened I am having the exact same erorr as @nans  after adding extra fields to customer grid by adding customer_listing.xml 

When Choosing all customers and press on button Export -> CSV -> Export
Actual result: csv file with data;
Expected result: csv file with data

When you don't check any checkbox it gives the following issue:

![Schermafbeelding 2019-06-20 om 17 27 24](https://user-images.githubusercontent.com/1216688/59861325-e47cec80-9380-11e9-9e0f-d5cd08f58edc.png)

**Comment by engcom-Charlie** [comment]
Hello @nans !
I can not reproduce your issue. The GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

**Comment by daiduongvo18** [comment]
I can reproduce the issue on **Magento 2.4.1** as @nans mentioned.

Steps to reproduce:
1. Add new customer attribute whose code is `varchar_attribute`, Input Type => Text Field, Add to Column Options => Yes, Use in Filter Options => Yes.
2. Define the `varchar_attribute` in the `customer_listing.xml` as in this sample module 
[TestCompany.zip](https://github.com/magento/magento2/files/7161076/TestCompany.zip)

3. Flush cache and reindex `customer_grid` in order to create the `varchar_attribute` in the table `customer_grid_flat`.
4. Export the customer data at the Customer listing page.

**Expected result:** 
Can download the CSV file.

**Actual result:**
```
TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /app/vendor/magento/framework/View/Element/UiComponentFactory.php on line 235 and defined in /app/vendor/magento/framework/View/Element/UiComponentFactory.php:183 Stack trace: #0 /app/vendor/magento/framework/View/Element/UiComponentFactory.php(235): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('varchar_attribu...', NULL) #1 /app/vendor/magento/module-ui/Component/Listing/Columns/Column.php(78): Magento\Framework\View\Element\UiComponentFactory->create('varchar_attribu...', 'varchar', Array) #2 /app/app/code/TestCompany/TestModule/UiComponent/Listing/VarcharAttribute.php(16): Magento\Ui\Component\Listing\Columns\Column->prepare() #3 /app/vendor/magento/module-ui/Component/MassAction/Filter.php(190): TestCompany\TestModule\UiComponent\Listing\VarcharAttribute->prepare() #4 /app/vendor/magento/module-ui/Component/MassAction/Filter.php(188): Magento\Ui\Component\MassAction\Filter->prepareComponent(Object(TestCompany\TestModule\UiComponent\Listing\VarcharAttribute)) #5 /app/vendor/magento/module-ui/Component/MassAction/Filter.php(188): Magento\Ui\Component\MassAction\Filter->prepareComponent(Object(Magento\Customer\Ui\Component\Listing\Columns)) #6 /app/vendor/magento/module-ui/Component/MassAction/Filter.php(213): Magento\Ui\Component\MassAction\Filter->prepareComponent(Object(Magento\Ui\Component\Listing)) #7 /app/vendor/magento/module-ui/Component/MassAction/Filter.php(131): Magento\Ui\Component\MassAction\Filter->getDataProvider() #8 /app/vendor/magento/module-ui/Model/Export/ConvertToCsv.php(72): Magento\Ui\Component\MassAction\Filter->applySelectionOnTargetProvider() #9 /app/vendor/magento/module-ui/Controller/Adminhtml/Export/GridToCsv.php(70): Magento\Ui\Model\Export\ConvertToCsv->getCsvFile() #10 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Ui\Controller\Adminhtml\Export\GridToCsv->execute() #11 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->___callParent('execute', Array) #12 /app/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->Magento\Framework\Interception\{closure}() #13 /app/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor), Object(Closure)) #14 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->Magento\Framework\Interception\{closure}() #15 /app/generated/code/Magento/Ui/Controller/Adminhtml/Export/GridToCsv/Interceptor.php(23): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->___callPlugins('execute', Array, Array) #16 /app/vendor/magento/framework/App/Action/Action.php(111): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->execute() #17 /app/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #18 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) #19 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->___callParent('dispatch', Array) #20 /app/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #21 /app/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #22 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #23 /app/generated/code/Magento/Ui/Controller/Adminhtml/Export/GridToCsv/Interceptor.php(32): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->___callPlugins('dispatch', Array, Array) #24 /app/vendor/magento/framework/App/FrontController.php(186): Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #25 /app/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Ui\Controller\Adminhtml\Export\GridToCsv\Interceptor)) #26 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #27 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #28 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #29 /app/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) #30 /app/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #31 /app/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #32 /app/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #33 /app/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #34 {main}
```
![ksnip_20210914-173406](https://user-images.githubusercontent.com/4049365/133242564-be31fea7-87c6-4301-aa4a-cbd6502add72.png)

**Root cause:**

The root cause is the code at the line https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Ui/Component/Listing/Columns.php#L161. It is getting the dataType from the backend type of the attribute while in this line https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Ui/Component/ColumnFactory.php#L74 it is create new column with dataType from the frontend input of the attribute. In my case, a component is added for the `varchar_attribute` with the `dataType=varchar`. `varchar` is not a valid UI component type.

I think dataType of the component should be frontend input because frontend input exists in the component types in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Ui/view/base/ui_component/etc/definition.xml.

Although we need custom code to reproduce the issue, the root cause belongs to Magento Core.

**Comment by evolbug** [comment]
This is still an issue in Magento 2.4.3-p1, please reopen

**Comment by amenk** [comment]
Still an issue in 2.4.4-p2, I submitted a PR #36663
