### ISSUE TITLE
SALES Orders and REPOERTS Orders Export order data is inconsistent

### ISSUE THREAD

**Issue by ghost** [magento/magento2#14500]
Magento ver. 2.1.9

### Preconditions

1. Two different operating places in the background.
2. Choose the same time (one day) for testing.
3. The output is different.
4. the SALES Orders data same as my database query result. this is SALES Orders 

### Steps to reproduce

1. 
![1522733785 1](https://user-images.githubusercontent.com/26874371/38234401-60b97e3c-3750-11e8-9546-57164ab89ba2.jpg)

2. 
![1522733700 1](https://user-images.githubusercontent.com/26874371/38234409-66a5060e-3750-11e8-8181-d38fd8c5df4d.jpg)

3. 
![1522734446 1](https://user-images.githubusercontent.com/26874371/38234414-6938b9e2-3750-11e8-9f09-a6eee078ee23.png)

4.
![1522739531 1](https://user-images.githubusercontent.com/26874371/38234777-735342ac-3751-11e8-811c-715e6fd1fcd9.jpg)

### Expected result

1. Actually the order quantity should be the same.
### Actual result

1.The order number is different now.
2. As in the fourth picture, if I don't click on the show report button first, the export is no data.

**Comment by ghost** [comment]
hi @n1cehua1991 which  version you tested ?

**Comment by ghost** [comment]
Magento ver. 2.1.9

**Comment by ghost** [comment]
@n1cehua1991  the fix for this issue has already been in  2.2.5 release

**Comment by ghost** [comment]
@engcom-backlog-nazar  Do I have to do a version upgrade？

**Comment by ghost** [comment]
@n1cehua1991  Yes sure.

**Comment by suresh9416** [comment]
Hi, im having same issue in magento 2.4.5-p4
