### ISSUE TITLE
Saving configuration invalidates Page Cache

### ISSUE THREAD

**Issue by blindmancs** [magento/magento2#1450]
Hey everyone,

I'm trying to get our module ported to Magento 2. Everything is nice and smooth so far, however just after I created a helper to access the configuration, I bumped into a new issue when I want to change any configuration in M2:

"One or more of the Cache Types are invalidated: Page Cache. Please go to Cache Management and refresh cache types." (config is saved correctly, it's just that you have to redo cache)

I'm really unsure what's the source of this; I removed the module in question but the issue still exists.

Thanks in advance, if you have any ideas what could be causing this.
(logs empty. the notification has a layout issue, and that gets a main.critical flag, but nothing else comes up.)

**Comment by eddielau** [comment]
Hi. This is an expected behavior when configuration is saved.
