### ISSUE TITLE
Unable to unserialize value

### ISSUE THREAD

**Issue by erichagz** [magento/magento2#14518]
### Preconditions

1. AWS EC2 C4-Large, Ubuntu 16.04.4 LTS, PHP 7.0.28-0ubuntu0.16.04.1
2. Magento 2.2.2
3. Also using AWS Redis for page caching. Following directions on https://devdocs.magento.com/guides/v2.2/config-guide/redis/redis-pg-cache.html

### Steps to reproduce

1. I think it's when editing products, but I really have no idea what this error even is

### Expected result

1. No idea 

### Actual result

1. [2018-04-03 18:22:38] main.CRITICAL: Unable to unserialize value. {"exception":"[object] (InvalidArgumentException(code: 0): Unable to unserialize value. at /var/www/bluewave2/vendor/magento/framework/Serialize/Serializer/Json.php:39)"} []

**Comment by rishabhrkrai** [comment]
I also get this error after Upgrading Magento to 2.2.4 from 2.1.7. In previous Magneto installation it works fine.

**Comment by ghost** [comment]
@erichagz , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result
