### ISSUE TITLE
Checkout fails when using fresh install + sample data

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1451]
See attached screenshot, just receive timeouts when trying to place a test order. Even on failure, loader just keeps spinning with no timeout/resolution to client.

![screen shot 2015-07-07 at 4 29 57 pm](https://cloud.githubusercontent.com/assets/437029/8556524/930234b0-24c5-11e5-865d-357b08287785.png)

Magento ver. 0.74.0-beta16

**Comment by markoshust** [comment]
Also note that the order was correctly saved in backend. Seems that I'm just not getting a success response returned to allow the UI to continue to the order success screen.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-39876

**Comment by markoshust** [comment]
Just wanted to check in if you were able to replicate this (noticed this was set to `acknowledged` so assuming you have). I'm still receiving this error, 504 gateway timeout after 1 minute.

![screen shot 2015-08-31 at 12 47 35 am](https://cloud.githubusercontent.com/assets/437029/9572230/273222b0-4f7a-11e5-9262-38c27afcc3ef.png)

**Comment by markoshust** [comment]
I believe this could also potentially be related: same thing is happening when registering for an account.

![screen shot 2015-08-31 at 12 51 39 am](https://cloud.githubusercontent.com/assets/437029/9572243/9691e97e-4f7a-11e5-8d51-e1de9be31812.png)

![screen shot 2015-08-31 at 12 52 04 am](https://cloud.githubusercontent.com/assets/437029/9572244/9af6db00-4f7a-11e5-96cc-6488fa052085.png)

**Comment by okorshenko** [comment]
@markoshust Thank you for reporting. Currently we can't reproduce this issue. 
Some details:
CE: cbf24e37edfc941013cb152a4e13132f67f3d39e
SD: https://github.com/magento/magento2-sample-data/commit/e9eeaa069db29b9e747bbb4539bb5cd9b8374ef6

### Installation:

To deploy sample data from repository, use:
 - Clone the sample data repository. For example, git clone https://github.com/magento/magento2-sample-data.git
 - Link the sample data repository with your Magento CE repository as follows: php -f <sample-data-root>/dev/tools/build-sample-data.php -- --ce-source="path/to/magento/ce/edition"

To install Magento instance with sample data use:

```
#!/usr/bin/env bash
/usr/local/bin/php /Users/okorshenko/www/magento2-public/bin/magento setup:install \
--backend-frontname="backend" \
--db-host="localhost" \
--db-name="magento-public" \
--db-user="magento" \
--db-password="123123q" \
--base-url="http://public.dev" \
--admin-user="admin" \
--admin-password="123123q" \
--admin-email="admin@exmaple.com" \
--admin-firstname="John" \
--admin-lastname="Doe" \
--admin-use-security-key=0 \
--session-save='db' \
--use-rewrites='1' \
--key='374549282625' \
--use-sample-data \
--cleanup-database;
```

Please, let us know if you still have an issue

**Comment by markoshust** [comment]
I think this was related to my previous build not properly generating static assets correctly from node (grunt refresh). I fixed this with an updated version of node (4.x).
