### ISSUE TITLE
 Regarding Issue found on Tax Zones and Rates Grid

### ISSUE THREAD

**Issue by ankit1388** [magento/magento2#14511]
Tax Zones and Rates Grid 
---------------------------------------------------------
1.  I go to admin panel and open tax zones & rates  grid in default magento setup.
When i filter using state/region column then it gives sql error.
that says region_name not found. so please check this issue.
Php version :   PHP 7.0.29
magento version : magento2.2.2, magento2.2.3

### Steps to reproduce

1. Go to admin.
2. then Go to Store->Tax zones & Rates 
3. Search state/region like "calif"
4. you get an mysql error 

### Expected result
Filtering results should be show.

### Actual result
1. 
![screenissue](https://user-images.githubusercontent.com/38037501/38250267-f261202c-376b-11e8-9c44-7f84cb4001d8.png)

**Comment by ghost** [comment]
@ankit1388  thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
