### ISSUE TITLE
Missing "Customer Groups" management

### ISSUE THREAD

**Issue by giulianoriccio** [magento/magento2#14515]
### Preconditions
Magento CE 2.1.12
PHP 7.0
MariaDB 10.1.22

### Steps to reproduce
1. Access Admin dashboard
2. Open stores menu

### Expected result
1. The Customer Groups link should be visible under "Other settings"

### Actual result
1. The Customer Groups link is not visible [image](https://i.imgur.com/DIrIhX6.png)

The link is not visible and even if I paste the url in the browser it redirects me to the dashboard.

**Comment by giulianoriccio** [comment]
I feel stupid, but it's under "Customers".

Some tutorials showed it under "Other settings" but I guess that it has been moved.

**Comment by lewisvoncken** [comment]
@giulianoriccio you don't have to feel stupid, this is a change that I have provided in this pull request https://github.com/magento/magento2/pull/11677
