### ISSUE TITLE
Hi,I've met an error about locale format symbol when i run unit tests

### ISSUE THREAD

**Issue by haiwera-silk-cd** [magento/magento2#14523]
**Preconditions**

1. php7.1.14,mysql 5.7,osx 11.13.3
2. Magento 2.2.5-dev

**Steps to reproduce**
run commands in terminal below
magento dev:tests:run unit

**Expected result**
pass

**Actual result**
Magento\Framework\Locale\Test\Unit\FormatTest::testGetPriceFormat with data set #2 ('de_CH', array('.', '''))
Failed asserting that actual size 1 matches expected size 2.

i got the symbol is  " ’" not "'" 
i don't know which is right

**Comment by ghost** [comment]
@haiwera-silk-cd, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
