### ISSUE TITLE
PayPal Payflow Server No Response

### ISSUE THREAD

**Issue by erichagz** [magento/magento2#14520]
### Preconditions

1. AWS EC2 C4-Large, Ubuntu 16.04.4 LTS, PHP 7.0.28-0ubuntu0.16.04.1
2. Magento 2.2.2
3. Also using AWS Redis for page caching. Following directions on https://devdocs.magento.com/guides/v2.2/config-guide/redis/redis-pg-cache.html

### Steps to reproduce

1. Checkout
2. Use Credit Card
3. 

### Expected result

1. Success!

### Actual result

1. "Server non-response error"

[2018-04-03 17:12:31] main.CRITICAL: PayPal gateway errors: Declined: 10486-This transaction couldn't be completed. Please redirect your customer to PayPal.. {"exception":"[object] (Exception(code: 0): PayPal gateway errors: Declined: 10486-This transaction couldn't be completed. Please redirect your customer to PayPal.. at (myfilelocaton)/vendor/magento/module-paypal/Model/Api/PayflowNvp.php:645)"} []

**Comment by YevSent** [comment]
@erichagz, seems like this is not Magento issue.

At first, according to [PayPal NVP API documentation](https://developer.paypal.com/docs/classic/api/errors/) - `10486` relates to PayPal Express Checkout but in described steps, you are using Credit Card.

Also, [this error](https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/) has multiple reasons:

- The billing address associated with the financial instrument could not be confirmed.
- The transaction exceeds the card limit.
- The transaction was denied by the card issuer.

**Comment by erichagz** [comment]
Ok. I get the "Declined" errors in my e-mail, but I wasn't sure why Magento was logging it into the exception.log file. I really can't figure out how to reproduce, but I have had several customers complain about a server error

**Comment by magento-engcom-team** [comment]
@erichagz Unfortunately we can not provide much help with issues which can not be reproduced. 
Closing this report for now. Please reopen if you come up with more details.

Thank you
