### ISSUE TITLE
Backport #14436 (Fix HTML tags in meta description) to 2.2+

### ISSUE THREAD

**Issue by davidwindell** [magento/magento2#14529]
Please can one of the team port the change in #14436 to v2.2+

**Comment by larsroettig** [comment]
Hi @davidwindell this ticket is not vaild G1 faild 👎 pls use the template from the core team.




### Preconditions


1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by davidwindell** [comment]
@larsroettig there are no Preconditions, Steps to reproduce or Expected results when backporting
