### ISSUE TITLE
Create the Partial shipment

### ISSUE THREAD

**Issue by shweta1234567** [magento/magento2#14531]
I am using the Magento 2.

I am creating the shipment Using rest api with follwowing End Point.
Url:-https://hostname/rest/default/V1/order/orderid/ship

I also want to create the partial shipment but I am enable to create please someone help me to find out the solution.

here is my JSON format.
{
"items":
	[
		{
			
			"order_item_id":14627,
			"qty":1
			
		}
	],
		"notify":true,
		"appendComment":false,
		"tracks":
		[
			{
				"track_number":"012356",
				"title":"",
				"carrier_code":"fedex"
				
			}
		]
	
}

Response:-\
{
    "message": "Shipment Document Validation Error(s):\nYou can't create a shipment without products.",
    "trace": "#0 [internal function]: Magento\\Sales\\Model\\ShipOrder->execute(66, Array, true, false, NULL, Array, Array, NULL)\n#1 /var/www/vhosts/scarpa/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)\n#2 /var/www/vhosts/scarpa/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#3 /var/www/vhosts/scarpa/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 /var/www/vhosts/scarpa/vendor/magento/framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 /var/www/vhosts/scarpa/vendor/magento/framework/App/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#6 /var/www/vhosts/scarpa/pub/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#7 {main}"
}

**Comment by engcom-backlog-nickolas** [comment]
Hello @shweta1234567, thank you for your report. I cannot reproduce this issue.
![peek 2018-07-26 10-24](https://user-images.githubusercontent.com/40755810/43247705-2ff571b2-90be-11e8-883a-a2757efd9719.gif)

If you'd like to update it, please reopen the issue.
