### ISSUE TITLE
Notice Error : Array to String Conversion 

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#14534]
Trying to add Multi Select input to Sales Rule form At admin.

### Preconditions

1. Magento Ver. 2.2.3 CE, PHP 7.0.9 

### Steps to reproduce

1. Create sales_rule_form.xml to add custom Multiselect field to sales rule form.
2. Create plugin to save that field's value to DB.
3. Use afterexecute method to save field.

### Expected result

1. Field has to save successfully to DB and success message needs to display with You Saved Rule.

### Actual result

1. Values saved to DB but error message is there with exception Something went wrong while saving the rule data. Please review the error log.

**Comment by bydrei** [comment]
@VZeroCool can you share the code you used in `sales_rule_form.xml`?

**Comment by VZeroCool** [comment]
`<fieldset name="exclude_brands">
	    <argument name="data" xsi:type="array">
	        <item name="config" xsi:type="array">
	            <item name="label" xsi:type="string" translate="true">Exclude Brands</item>
	            <item name="collapsible" xsi:type="boolean">true</item>
	            <item name="sortOrder" xsi:type="number">15</item>
	        </item>
	    </argument>
        <field name="start_date" formElement="date">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="source" xsi:type="string">sales_rule</item>
                </item>
            </argument>
            <settings>
            	<validation>
                    <rule name="validate-date" xsi:type="boolean">true</rule>
                </validation>
	           <dataType>text</dataType>
                <label translate="true">Start Date</label>
                <visible>true</visible>
                <dataScope>start_date</dataScope>
            </settings>
        </field>
        <field name="end_date" formElement="date">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="source" xsi:type="string">sales_rule</item>
                    
                 </item>
            </argument>
            <settings>
                <validation>
                    <rule name="validate-date" xsi:type="boolean">true</rule>
                </validation>
                <dataType>text</dataType>
                <label translate="true">End Date</label>
                <visible>true</visible>
                <dataScope>end_date</dataScope>
            </settings>
        </field>
        <field name="brand_ids" formElement="select">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="source" xsi:type="string">sales_rule</item>
                </item>
            </argument>
            <settings>
                <validation>
                    <rule name="validate-brands" xsi:type="boolean">true</rule>
                </validation>
                <dataType>varchar</dataType>
                <label translate="true">Brand List</label>
                <dataScope>brand_ids</dataScope>
            </settings>
             <formElements>
		        <select>
		            <settings>
		                <options class="Vivek\ShopAsGroup\Block\SalesRule\BrandList"/>
		                
		            </settings>
		        </select>
	    	</formElements>
        </field>
    </fieldset>`

**Comment by VZeroCool** [comment]
di.xml

`<type name="Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save">
		<plugin name="save_brands" type="Vivek\ShopAsGroup\Model\Plugin\brands" sortOrder="1"/>
	</type>`

File : Vendor/Module/Model/Plugin/Brands.php

              `public function afterexecute(\Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save 
               $save,$result)
                {
    	
		echo "<pre>";
		/*
		print_r($_POST);
		
		exit;*/
		
		$ruleId =  $save->getRequest()->getParam('rule_id'); 
		/*echo $save->getRequest()->getParam('start_date').'<br>';
		echo $save->getRequest()->getParam('end_date');
		exit;*/
		$brandIds = implode(',',$save->getRequest()->getParam('brand_ids'));
		
		$salesRuleData =  $this->salesRule->load($ruleId);
		
		$salesRuleData->setStartDate($save->getRequest()->getParam('start_date'));
		$salesRuleData->setEndDate($save->getRequest()->getParam('end_date'));
		$salesRuleData->setBrandIds($brandIds);
		$salesRuleData->save();			
		
		 $CustomRedirectionUrl = $this->_url->getUrl('*/*/');
		 $this->_responseFactory->create()->setRedirect($CustomRedirectionUrl)->sendResponse();
		 exit();
	}`

**Comment by VZeroCool** [comment]
@ferrazzuk , Check now I've updated code.

**Comment by VZeroCool** [comment]
<field name="start_date" formElement="date">
			<argument name="data" xsi:type="array">
				<item name="config" xsi:type="array">
					<item name="source" xsi:type="string">sales_rule</item>
				</item>
			</argument>
			<settings>
				<validation>
					<rule name="validate-date" xsi:type="boolean">true</rule>
				</validation>
				<dataType>text</dataType>
				<label translate="true">Start Date</label>
				<visible>true</visible>
				<dataScope>start_date</dataScope>
			</settings>
		</field>
		<field name="end_date" formElement="date">
			<argument name="data" xsi:type="array">
				<item name="config" xsi:type="array">
					<item name="source" xsi:type="string">sales_rule</item>
                    
				</item>
			</argument>
			<settings>
				<validation>
					<rule name="validate-date" xsi:type="boolean">true</rule>
				</validation>
				<dataType>text</dataType>
				<label translate="true">End Date</label>
				<visible>true</visible>
				<dataScope>end_date</dataScope>
			</settings>
		</field>
		<field name="brand_ids" formElement="select">
			<argument name="data" xsi:type="array">
				<item name="config" xsi:type="array">
					<item name="source" xsi:type="string">sales_rule</item>
				</item>
			</argument>
			<settings>
				<validation>
					<rule name="validate-brands" xsi:type="boolean">true</rule>
				</validation>
				<dataType>varchar</dataType>
				<label translate="true">Brand List</label>
				<dataScope>brand_ids</dataScope>
			</settings>
			<formElements>
				<select>
					<settings>
						<options class="Vivek\ShopAsGroup\Block\SalesRule\BrandList"/>
		                
					</settings>
				</select>
			</formElements>
		</field>
