### ISSUE TITLE
One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by liqunxiong** [magento/magento2#14545]
### Preconditions

1. Magento ver. 2.2.3
2. 

### Steps to reproduce

1. php bin/magento indexer:reindex customer_grid.
2. 
3. 

### Expected result

1. Customer Grid indexe has been rebuilt successfully

### Actual result

1. [Screenshot, logs]
Customer Grid indexer process unknown error:
Warning: SessionHandler::read(): open(/var/cpanel/php/sessions/ea-php70/sess_84uavjuhato0otc1m1991te116, O_RDWR) failed: Read-only file system (30) in /home4/jollyflo/public_html/vendor/magento/framework/Session/SaveHandler/Native.php on line 22

**Comment by TomashKhamlai** [comment]
It looks like you have troubles with permissions. Use this [Set ownership and permissions for the shared group](http://devdocs.magento.com/guides/v2.2/install-gde/prereq/file-system-perms.html#perms-set-two-users)

**Comment by ghost** [comment]
Issue related to file system permissions.
