### ISSUE TITLE
REST API for layered navigation

### ISSUE THREAD

**Issue by nkarthickannan** [magento/magento2#14543]
### Preconditions

1. Magento 2.2.3
2. PHP 7.1
3. MySQL 5.6
4. OS - Ubuntu 16.04

### Steps to reproduce
1. Use **GET /V1/products-render-info** REST API call to get the list of products based on the search criteria, currency, store and the pagination settings (/rest/V1/products-render-info?searchCriteria=[]&storeId=1&currencyCode=1)
2. It returns the list of products but not the filters section

### Expected result
1. Expecting the REST API to get the filters details

### Actual result
1. To build an Android application (for example), we are able to get the list of products but there is no provision to get the filters details

**Comment by magento-engcom-team** [comment]
Hi @karthickannan. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/84
