### ISSUE TITLE
Magento 2.2.3 - 504 Gateway Timeout

### ISSUE THREAD

**Issue by sabarivenkat** [magento/magento2#14551]
Preconditions
1. Magento 2.2.3 
2. Varnish cache (varnish-4.1.1)
3. Nginx/1.10.3 (Ubuntu)

Steps to reproduce
1. Stores -> Configuration -> Customer -> Customers configuration -> Address templates
2. Save the configuration

Expected result
1.  Success message should come.

Actual result
1. After some time I am getting 504 gateway. But my changes are saved in the db.

Comments:
I have increased my php time out configuration as well as varnish timeout (between_bytes_timeout = 600s). I am still getting the same error. This happens only in the admin section. I have checked with my server support team and confirmed that there is no problem in the server side. 

![screenshot_504_error](https://user-images.githubusercontent.com/35493233/38352838-18496206-38d2-11e8-8867-ab912abddaa7.png)

**Comment by orlangur** [comment]
@sabarivenkat you need to find out in logs (webserver/php-fpm) what went wrong. 504 HTTP code by itself IMO does not give any information for investigation on our side.

**Comment by sabarivenkat** [comment]
@orlangur I have checked the webserver/php-fpm log in my server. There is no error log. But the error was created in Nginix error log file /var/log/nginix/error.log. It's shown in the attached screenshot. Also I found that after saving the configuration it is redirected to  "http://127.0.0.1:80/admin" (this is varnish port), instead "https://example.com/admin" (I have enabled secure url for admin). I don't know exactly what is the problem. Might be issue with the combination of varnish, https and nginix. Please help us to fix this.

![menu_001](https://user-images.githubusercontent.com/35493233/38738115-e620889e-3f4e-11e8-8e59-734acc18ddd7.png)

**Comment by ghost** [comment]
@sabarivenkat, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
