### ISSUE TITLE
Scheduled cron is not running from cpanel

### ISSUE THREAD

**Issue by agavshinde** [magento/magento2#14565]
We have scheduled cron as per following settings on Cpanel:

*/1 *  *  * 	*  /usr/local/bin/php <root path>/bin/magento cron:run >> <root path>/var/log/magento.cron.log 	
*/1 *  *  * 	*  /usr/local/bin/php <root path>/update/cron.php 	
*/1 *  *  * 	*  /usr/local/bin/php <root path>/bin/magento setup:cron:run

Above scheduled cron jobs are not running automatically. But when we run those commands manually from terminal it will run properly. 

### Preconditions

1.  Magento version 2.0.7
2.  PHP 7.0
3. MySQL 5.6

### Steps to reproduce

1.  Create custom module
2.  Create custom crontab.xml
3.  Create cron class with method 
4. Set it will run everyminute
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
    <group id="default">
    	<job name="customcron" instance="Alw\Customcron\Cron\Customcron" method="execute">
    		<schedule>*/1 * * * *</schedule>
		</job>
		
	</group>
	
</config>

### Expected result

1.  It should run through cpanel

### Actual result

1. [Screenshot, logs]

**Comment by ghost** [comment]
Hello @agavshinde , thank you for your report. Unfortunately magento 2.0.x no longer supported https://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.18CE.html.
To maintain the performance and security of your site, we advise you to upgrade to the latest version of Magento Open Source.
