### ISSUE TITLE
The getComments method on a Shipment model often returns a collection instead of an array of ShipmentInterfaces.

### ISSUE THREAD

**Issue by chris-huffman** [magento/magento2#14563]
When the `\Magento\Sales\Model\Order\Shipment::getComments` method is called in an API call, an exception occurs. ('Uncaught Error: Call to a member function addItem() on null'). This is happening because the return type specified is `\Magento\Sales\Api\Data\ShipmentCommentInterface[]`. However, this method often returns a collection (`\Magento\Sales\Model\ResourceModel\Order\Shipment\Comment\Collection`). This issue is similar to the one in this [github issue](https://github.com/magento/magento2/issues/13180). (And is in fact referenced in the issue). Additionally, the method `\Magento\Sales\Model\Order\Shipment::getCommentsCollection` calls the `getComments` method looking for a collection. Once the `getComments` method is fixed to return an array of interfaces, the  `getCommentsCollection` will need to be fixed in order to return a collection type (otherwise an additional error occurs).

This behavior can be seen in admin, but will not result in any exceptions. When these methods are called through the `\Magento\Framework\Webapi\ServiceOutputProcessor`, these methods will cause an exception.

### Preconditions

1. PHP 7
2. Magento 2.1.12

### Steps to reproduce

1. In admin, place an order.
2. Create a shipment for the order, with at least one comment.
3. View the shipment, and debug the methods mentioned.

### Expected result

1. The `\Magento\Sales\Model\Order\Shipment::getComments` method should return `\Magento\Sales\Api\Data\ShipmentCommentInterface[]`.
2. The `\Magento\Sales\Model\Order\Shipment::getCommentsCollection` method should return `\Magento\Sales\Model\ResourceModel\Order\Shipment\Comment\Collection`.

### Actual result

1. `getComments` returns a `\Magento\Sales\Model\ResourceModel\Order\Shipment\Comment\Collection` which doesn't throw an error unless being sent through the `\Magento\Framework\Webapi\ServiceOutputProcessor`.

**Comment by koenner01** [comment]
I also encountered this problem https://github.com/magento/magento2/issues/13180

We temporarily 'fixed' it in our logic with:

```
$invoiceComments = $invoice->getComments();
if (!is_array($invoiceComments)) {
    if (get_class($invoiceComments) === 'Magento\Sales\Model\ResourceModel\Order\Invoice\Comment\Collection') {
        $invoiceComments = $invoiceComments->getItems();
    }
}
$invoice->setComments($invoiceComments);
```

**Comment by levhryhoriev** [comment]
Hello @magento-engcom-team!
I am not sure how to assign issue here on myself, but I already Implemented PR for it https://github.com/magento/magento2/pull/16248

**Comment by phoenix128** [comment]
No problem @c4boomb ,
I assigned to myself so none else will pick this up for the moment. I'm also processing your PR.

Thank you very much for your contribution, your help is very appreciated.
