### ISSUE TITLE
Reduce amount of javascript

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#14564]
I am trying to figure out how to make m2 usable with a "normal" internet connection in 2018.
Coming from m1 I was quite shocked about the insane(!) overhead m2 is creating in terms of requests and file count (especially javascript).
I am currently setting up a new project and so far the shop is very bare. I am building a new template based on foundation 6. Except for the foundation framework nothing has been added to the site. The amount of files being loaded on every request is just out of this world. Living and developing in germany learned over the years that a store's homepage that exceeds 1-1.5 MB is a serious performance issue. Of course also the amount of requests per page load should be as low as possible.

So I did everything the internet says about how to improve m2's performance:
- http/2
- production mode
- use flat catalog (category & product)
- all caches activated
- JS/CSS minification
- JS bundling off
- gzip

On my store's simple homepage m2 is currently loading 124(!) Javascript files. I know http/2 is supposed to make this quick and stuff. But with all optimizations activated the page only becomes usable once all files are loaded. The time between the first byte that arrives at the browser and the page being ready varies between 4 and 6 seconds. And this is on my local development server! 

From a user's perspective this feels very "hacky". I see the page but it is still unresponsive. Why should I annoy valuable customers this way? Good example for this behaviour: the minicart. It won't even show up before the js stuff is loaded. This even happens when all the files are already cached in the browser. In the browser's console I see how it is requesting file by file. It won't load them if cached but still it has to go through all the files to check their status which takes time.

I tried activating the JS bundling which actually made the page respond faster after the initial load. But still the first request takes a long time before the bundled JS (1+ MB) is done loading. But "the internet" recommends to disable this feature anyway. 

Coming from magento 1 I feel like I was frozen for the last 20 years. And I was used to he fact that I had to live with prototype and it's overhead.

I see there are A LOT of jquery ui files being loaded. First one's I stumble into are the timepicker and moment.js. All being loaded on the homepage. What for? As far as I can see my store will not need these features at all.

Is there a way to reduce all these files to a reasonable amount? Or is all this somehow required and I just Don't know this?

How can it be achieved that the page is actually responsive the moment it appears in the browser?

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by mage-dave** [comment]
@OvalMedia I am having the same issues have you found any solution? We only use simple products and don't have swatches yet configurable, bundled and swatch scripts load on pages that don't even need them.
