### ISSUE TITLE
Path of directory pub is incorrect...please help!

### ISSUE THREAD

**Issue by silvert298** [magento/magento2#1456]
I installed magento 2.0 on folder `localhost/magento21` however when I login to my admin panel I've got some `js error`sas follow:

> "NetworkError: 404 Not Found - localhost.com/magento20/pub/static/adminhtml/Magento/backend/en_US/js/theme.js" theme.js 
> "NetworkError: 404 Not Found - localhost.com/magento20/pub/static/adminhtml/Magento/backend/en_US/mage/backend/bootstrap.js" bootstrap.js "NetworkError: 404 Not Found - localhost.com/magento20/pub/static/adminhtml/Magento/backend/en_US/jquery.js" jquery.js 
> "NetworkError: 404 Not Found - localhost.com/magento20/pub/static/adminhtml/Magento/backend/en_US/Magento_Catalog/catalog

Somebody please can tell me how to solve this issue!

![enter image description here][1]

  [1]: http://i.stack.imgur.com/uGn6i.png

**Comment by roshimon** [comment]
I think the problem is with the path. Try reinstalling it and name the magento installation folder as magento2, which will be lot easy :)

**Comment by roshimon** [comment]
Sorry even I am getting that error. You used develop or master branch ? try using master branch.

**Comment by jamescowie** [comment]
Have you tried running the static file generation ? You can run

`./bin/magento setup:static-content:deploy` this will create the pub folders with all the requires assets for the stores, 

If this doesnt work or produces errors paste them back here and we can look more.

**Comment by mazhalai** [comment]
@roshimon in the screenshot shown, your website is `localhost.com/magento20/` but the static files being accessed are `localhost.com/magento21/`.  Can you please clean browser cache and also Magento's cache in the `var/cache` and `var/page_cache` folder and try again.

**Comment by roshimon** [comment]
Mazhalai for me installation worked fine but the admin panel features don't
seem to work. Except Admin dashboard, others are pretty much freezed.

**Comment by mazhalai** [comment]
@roshimon what exactly doesn't work? Can you give more details or screenshots?

**Comment by roshimon** [comment]
Sure :)

**Comment by roshimon** [comment]
https://hello.firefox.com/TwUrlNTrXHs

**Comment by roshimon** [comment]
Screenshots of my Magento 2 Frontend and Backend.

**Comment by roshimon** [comment]
Did you see it ?

**Comment by roshimon** [comment]
![magento2backend](https://cloud.githubusercontent.com/assets/5530839/8577195/9531af04-25c4-11e5-878f-334e2b089026.png)
![magento2frontend](https://cloud.githubusercontent.com/assets/5530839/8577200/9c894500-25c4-11e5-9f98-4c4278d4cb50.png)

**Comment by roshimon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- roshi

Confirm that you know roshi: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=FFrJnTKt&amp;invitationId=6025916684857020417&amp;trk=eml-guest-invite-cta&amp;trkEmail=eml-invite_guest-null-2-null-null-%7Ei0sit0%7Eic08ffbk%7E6g


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-i0sit0-ic08ffbk-6g&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQE-1eO42ywXCwAAAU6BbVx6vmKKZ0-YtAC8XnfNh1IVHnNTDVAXy7n3EuafOHkH3ug_dIPeNEVRpXBIRFgTjaPCyqsFCgfSOOQeVsnOYZigXruHfDFgahQgXWkzsGJYZHmj5a3NRtGlVFye1lJ02HjbQBNJ3ZctZamCgxpzCdDuTHuHt-34NBN4FzaaKYVZVhxO&amp;eid=-i0sit0-ic08ffbk-6g Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-i0sit0-ic08ffbk-6g&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by roshimon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- roshi

Confirm that you know roshi: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=iKjPXlU2&amp;invitationId=6025916685368721408&amp;trk=eml-guest-invite-cta&amp;trkEmail=eml-invite_guest-null-2-null-null-%7Euh05es%7Eic08ffez%7E8


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-uh05es-ic08ffez-8&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQHcTTEIWSByXwAAAU6BbYy5LBhbVJxDEe235UhyREWeBddRgujKs5Sfb0DNjaPjIR7Jd8bRM1nci_TAWutuOUcyowXwEx2P8256ElvoHZ5X7Opub1E6L77l5jlPlhOCvIbUUgVVvpIHGtZPn4wtcvTjMMOyL7UbhZeFVIk0Q14ilzUM4-HzVdgkoC4SHMGqNRHF&amp;eid=-uh05es-ic08ffez-8 Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-uh05es-ic08ffez-8&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by buskamuza** [comment]
Hi @roshimon , could you provide errors from browser console? What resources are not loaded?

Thanks.

**Comment by roshimon** [comment]
Hai friends. I need your help in magento :)

**Comment by roshimon** [comment]
roshi mon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0TcjgMcz0TdjwQe3oScjARcz0Sfkh9rCZFt65QqnpKqipQiRhKiD96hzRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4CoP8JtmVLsSYRoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=

View roshi mon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3gMdzkRd30ScjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCtD1KfngCoP8JtmVLsSYRoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9j4MpCkRejkMpmcVdz5xczBBc3gNdm8Ncj4Mc30Mc30MpCcOej0Qc39AczwOpm8RdjcRcmhAdzkNczsMc35ye6gOcjANc64OpztBoCgTp3gSd3kMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zsNd30Oc3sRe3gUdzoNejkOc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCoP8JtmVLsSYRoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1zcyRRrCZPrPlzqiQMt6BPc6AJfmhFpipGt5FhhDkTkz4JsmdFcCtRkmAPhDkOij94l34QqlwUj5pBcnheh65Jr6R9j6Z3ukh8p3tcjAhCgQRqmkhaemR1q6Bei7h7hll2rj4Rl6B9bm9ftn1fsPdykQVpmB1Hm48Vm49mlRZztS4Ju5dvkP8RdmAVhlFjh6RmgQVBjR5Ddk5FjlFKtAhUm6cOgRtmp4FSl7sQtThRt5Z4cSR7d3h9ilZIgAwNrQx9p5d9uz0RhBsSlk51gk5cqBBTe71Mm5Z7hl51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCoP8JtmVLsSYRoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6025916703559421952_500&amp;markAsRead=This email was intended for magento/magento2. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CoP8JtmVLsSYRoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by roshimon** [comment]
roshi mon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Uc3gNczsUdzcRe3oScjARcz0Sfkh9rCZFt65QqnpKqioOlmNok6FbqjRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4Crz8JdnxLsSYRoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=

View roshi mon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3gMdzkRd30ScjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCtD1KfngCrz8JdnxLsSYRoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9j4MpCkRejkMpmcVdz5xczBAczBCd68Ncj4Mc30Mc30MpCcOejsTpmhAp6hxpjxAoCpzc65Aej0Mcj8NoPwMemgNcjwVoPoRpzgRe6gTp3gSd3kMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwMd34OdPwScPkUdzoNejkOc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCrz8JdnxLsSYRoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1KcyQRu6ZPrPlzqiRPpjkMq7kJfmhFpipbpC4JiDcSoA5Sdm8Se6BjpQcMt7BPlT0Muz13rPh5qOR9liRJh6URlkVei4VWrTdTdR1chPBDiiREekBfe4ljjRwRrARRkkRbekxzu7xFiDEUm5tInQhBqRFqpRByhnAUdDxIkQd5dnlbrlhycBtkoBpFi2RVe5h2ckhEs3pWiB9hpRplsP1WoSJylDESslFlkn1QrDFhtzhQlmBnm6oVjP1WhSxoe7BhcmBRtP0RhBsSlk51gl5ajktVp3djk6hxhB51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCrz8JdnxLsSYRoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6025916704117268480_500&amp;markAsRead=This email was intended for magento/magento2. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Crz8JdnxLsSYRoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by roshimon** [comment]
roshi mon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=3sNd30Oc3sRe3gUdzoNejkOc3oZh4BKrSBQonhFtCVF9Dhbl6VasAp6fnBBiShBsC5EsOpQu6lQnThMpmdzojRPt2pLsClEfmQCcPRFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCpnhFtCV9pSlipn9Mfm4CsPcJdmNHdCVDoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=

View roshi mon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=d30SdjkQc3oNfkh9sClyrmlJ9DhUpnhvpmNFpCZOs3RPt2pLsClEfmQCd3RFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCtD1KfngCsPcJdmNHdCVDoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kNc6pBdjARc6lzejoNoj8Vpj0Qcjlycj4Nc30Mc30Mc6pzczAMd30Op38UcClydjkPdj5Ap3oRcj8Tc30NozxAcz4Vcj1xcCoTpm9AdSgQdzgRc312cylVr71BszRIqm5JpioMdz0MczRAqioTcjgMcz0TdjwQe3oScjARcz0SfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCt7xBt5ZytndKtiQSbm9RsSVRbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZpSVFqSdxsDgCrSZDfngCsPcJdmNHdCVDoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=7cPbjlIqPpKpSdFbj1QqncMqiQZp6BB9AVebk55uCwOrTARclx5kR5mm399r65qtRFKrD9FoktqpB9VjRsUil5Nr58Jjz5BgCVngRBxc7pVkl1Sr6ZghSdEq5hpc6NEkkNid4EVl4VJgPt7gktye44VemFFoAUSs6IUqjhaqBBGp6QQt4oMhChEs4JepAlQgAl9i71cl3pydSRhdP5LpRBBhndBqBkJgPtEnQN5lTFVd55fkjBliC9zpAtnjj5QrAB5cmF5cPBHejplgk51gmZNoB9ibm5VqR57kk4Zp6BLr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCsPcJdmNHdCVDoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6025916703559421952_500&amp;markAsRead=This email was intended for magento/magento2. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CsPcJdmNHdCVDoSAJc7hFsP1FbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703559421952_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by roshimon** [comment]
roshi mon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=3wMd34OdPwScPkUdzoNejkOc3oZh4BKrSBQonhFtCVF9z9lr5xgqAJFfnBBiShBsC5EsOpQu6lQnThMpmdzojRPt2pLsClEfmQCcPRFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCpnhFtCV9pSlipn9Mfm4CtPoJd6NHdCVDoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=

View roshi mon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=d30SdjkQc3oNfkh9sClyrmlJ9DhUpnhvpmNFpCZOs3RPt2pLsClEfmQCd3RFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCtD1KfngCtPoJd6NHdCVDoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kNc6pBdjARc6lzejoNoj8Vp38Vpzhycj4Nc30Mc30Mc6pzczATdSlAp6hAomkUp69CoP1xp3AMc34OcmcUc3BAcj4UemcSdmoQdjxAdSgQdzgRc312cylVr71BszRIqm5JpioMdz0MczRAqioUc3gNczsUdzcRe3oScjARcz0SfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCt7xBt5ZytndKtiQSbm9RsSVRbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZpSVFqSdxsDgCrSZDfngCtPoJd6NHdCVDoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=7sSbjhIqPpKpSdFbndBdj1EtiQZp6BB9ztIiAZhrAZlskl6c6MJl6pTd4pol6dhi6J1sBlitSFUrPphkB9jkD1BgBdSrCtykm5QlnwVrP8NkDBdq4UTtQ4Puj1osTBFemFEumxijBlBdT8SbkREsBpHe3cMsnh1rB1nk6F6pmEJrB0UijdjuklKpD8NlTBDuANaujldqPdlnQ5is4d9p4t5tj18tClGqlpymn4Tel0RkAFCi75jm5B1omtmi3BInQMSl5lAnQhIejplgk51pQRRlkx8r3lTrSx5kk4Zp6BLr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCtPoJd6NHdCVDoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6025916704117268480_500&amp;markAsRead=This email was intended for magento/magento2. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CtPoJd6NHdCVDoSAJsSkRc6xRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916704117268480_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by daim2k5** [comment]
Please feel free to reopen the issue i closed i now because you didn't answered

**Comment by roshimon** [comment]
Thank you @buskamuza :+1:
