### ISSUE TITLE
normalizeDate() and convertToMomentFormat() in misc.js is the same

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#14568]
I'm not sure, but seems that normalizeDate() and convertToMomentFormat() in misc.js is the same and one of them should be deleted.

Both of them convert Intl date format to moment.js format. normalizeDate() seems more correct.

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by krzksz** [comment]
Closing as per comment: https://github.com/magento/magento2/pull/25544#issuecomment-558353493
