### ISSUE TITLE
Adding new page shows 'Something went wrong while saving the page'

### ISSUE THREAD

**Issue by saadjawaid123** [magento/magento2#14578]
Hi, Im trying to add new page in magento 2.1.2. And once I press save, it shows me 'Something went wrong while saving the page' after page reload. Please help

**Comment by magento-engcom-team** [comment]
Hi @saadjawaid123 
Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks
