### ISSUE TITLE
Magento rewriting return annotations in Block Interceptor

### ISSUE THREAD

**Issue by molovo** [magento/magento2#14574]
### Preconditions
* Magento version: Magento CE 2.2.3
* PHP version: `7.1.15-1`

### Steps to reproduce
1. Add a block with a nullable return annotation
    ```php
    /**
     * @return DesignerInterface|null
     */
    public function getDesigner(): ?DesignerInterface {
        ...
    }
    ```
2. Run `bin/magento setup:di:compile`

### Expected result
1. The code should remain as I wrote it.

### Actual result
1. The generated Interceptor class removes the nullable part of the annotation, resulting in a fatal error when null is returned.
    ```php
    public function getDesigner(): DesignerInterface {
        ...
    }
    ```

As a side note, this *terrifies* me, because it makes me wonder what other changes Magento is making to my code that I don't know about...

**Comment by ghost** [comment]
Hi @molovo  can you provide more information ?

**Comment by molovo** [comment]
@engcom-backlog-nazar what other information do you need?

**Comment by ghost** [comment]
@molovo Steps to reproduce. write more information.

**Comment by molovo** [comment]
@engcom-backlog-nazar All the steps to reproduce are already included in the issue description

**Comment by ghost** [comment]
@molovo  this is duplicate for this -> https://github.com/magento/magento2/issues/15505

**Comment by molovo** [comment]
@engcom-backlog-nazar It does appear to be, yes. Thanks
