### ISSUE TITLE
Magento 2 edit customer information get 302 response error and user logout

### ISSUE THREAD

**Issue by ashokrathorecdn** [magento/magento2#14570]
I have facing an issue when I tried to update user information in magento 2.2

Sometimes I get successful message if I update user information (Like email, first name, last name etc from profile section). Please find attached screen shot for success message (success-edit-post.png).

Sometime it get failed and user auto logout. I have checked the response and found that it gives 302 error in browser console. Please find attached screen shot for error message (edit-post-userinfo-error-.png).

Can anyone help for this random issue. thanks

![edit-post-userinfo-error-](https://user-images.githubusercontent.com/32710442/38407492-4c7a66fe-3997-11e8-98d9-033e28409ea3.png)

![success-edit-post](https://user-images.githubusercontent.com/32710442/38407489-46e4471e-3997-11e8-82aa-1cafaeb07651.png)

**Comment by Akki8388** [comment]
Hello Hi got same issue i create one file type customer attribute but when i edit it give same error

**Comment by honeygarg** [comment]
I have also get the same problem.

**Comment by ghost** [comment]
@ashokrathorecdn, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
