### ISSUE TITLE
shipping address line 1 and 2 nuked when leaving checkout and coming back in again

### ISSUE THREAD

**Issue by tristanisginger** [magento/magento2#14577]
### Preconditions
magento 2.2.14, php 7.0 fresh install with sample data

### Steps to reproduce
exit the checkout on billing page to continue shopping
checkout again

### Expected result
your full address to be there

### Actual result
address lines 1 and 2 gone

![image](https://user-images.githubusercontent.com/25447128/38415677-2ff6a18a-398a-11e8-9126-de6e01c069d4.png)

**Comment by ghost** [comment]
Hi @tristanisginger the fix for this issue has already on 2.2-develop branch
