### ISSUE TITLE
Implement toggle navigation as layout blocks

### ISSUE THREAD

**Issue by melvyn-sopacua** [magento/magento2#14584]
### Preconditions
Magento 2.2.3, os, php version irrelevant.

### Steps to reproduce

1. The "Toggle navigation" button is implemented in the [logo.phtml](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Theme/view/frontend/templates/html/header/logo.phtml#L14) template. This line has hard-coded classes and HTML layout.
2. When moving the block it's unexpected (and in my case unwanted) to have this moved as well.

### Expected result
1. This can easily be implemented as a layout block in XML, so that it can be moved/removed independent of the logo.

### Actual result
1. Moving the logo moves the toggle navigation button, which is a POLA violation: There is no semantic relation between the logo and the toggle navigation button - this is one of layout convenience and therefore belongs in layout instructions.
2. The template now needs to be overridden if one wants to modify or remove the HTML generated for the toggle button. Something as simple as moving a block is now a 2-step process.

**Comment by orlangur** [comment]
https://github.com/magento/magento2/blame/2.1-develop/app/code/Magento/Theme/view/frontend/templates/html/header/logo.phtml#L14

It was there for years and does not seem to cause any issues.

> The template now needs to be overridden if one wants to modify or remove the HTML generated for the toggle button. Something as simple as moving a block is now a 2-step process.

In your customization you'll need to have two templates, while in proposed implementation everyone in core would have such two templates. It seems to me that having separate block in layout for every tiny block of HTML like

```
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
```

is a bit an overkill. As to me such separation makes sense in case it is a common customization scenario.

**Comment by magento-engcom-team** [comment]
Closing, per @orlangur comment.

Thanks for collaboration.
