### ISSUE TITLE
Cannot use Vault Payment for Virtual Quotes

### ISSUE THREAD

**Issue by pmclain** [magento/magento2#14587]
Customers are unable to checkout using Vault payment methods when a quote contains only virtual items. After selecting a Vault payment method and clicking "Place Order" the following error message is returned:
> Please check the billing address information. firstname is a required field. lastname is a required field. street is a required field. city is a required field. telephone is a required field. postcode is a required field. countryId is a required field.

### Preconditions
1. Magento v2.2.3
2. Braintree Credit Card Payments with Vault enabled. The issue is reproducible for any payment methods utilizing the Magento_Vault.

### Steps to reproduce
1. Login as customer without default billing address
2. Complete purchase with Braintree payment method opting to store card for later use
3. Create new cart containing only virtual products
4. Proceed to checkout
5. Select Braintree Vault payment method

### Expected result
1. Virtual carts should provide an ability for users to select/input a billing address for the cart.

### Actual result
1. The place order attempt fails because no billing address is set.
<img width="852" alt="screen shot 2018-04-07 at 2 24 00 pm" src="https://user-images.githubusercontent.com/12674247/38458842-8b78cbf0-3a70-11e8-84f5-db758d8efacf.png">

**Comment by engcom-backlog-nickolas** [comment]
Hello @pmclain, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by pmclain** [comment]
It looks like this is fixed in 2.3-develop by https://github.com/magento/magento2/commit/06c69e361b283911fb2c2db4da04f81226749a9e#diff-196317c892bea622f5a7170c724afdd7
