### ISSUE TITLE
Translation Custom Variables

### ISSUE THREAD

**Issue by raymond62** [magento/magento2#14588]
CustomVar is in my opinion not as efficient as it could be.

### Preconditions
1. Latest Magento 2.3., PHP 7.0, MySql 5.6

### Steps to reproduce
1. Go to "System -> Custom Variables" and create new

### Expected result
1. "Variable Code" should only be editable in "All Store View"
2. "Variable Name" should be editable for each "Store View" and also usable as translation.
e.g.: 
Variable Code: company_owner
Variable Name: Owner (en store), Eigentumer (de Store), Eigenaar (nl Store)
Variable Value: My Name
{{CustomVarName code="company_owner"}}: {{CustomVar code="company_owner"}}

### Actual result
1. "Variable Code" is editable in all Store views and change the default value
2. "Variable Name" is editable in all Store views and change the default value
3. Usable is only {{CustomVar code="company_owner"}} and i have to use {{trans "Owner"}} additionally

In suggested way i only have to edit one form (System -> Custom Variables).
Now i additionally have to make translations on other places.

**Comment by ghost** [comment]
Hi @raymond62 , thank you for your report. GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
