### ISSUE TITLE
Something went wrong while saving this configuration: Warning: array_keys() expects parameter 1 to be array, string given in /vendor/magento/module-config/Model/Config/Backend/Translate.php on line 35

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#14589]
### Preconditions
1 . Magento 2.2.3
2 . PHP 7.1
3. MysQL 5.7
4. Apache 2.4

### Steps to reproduce
1. Installed fresh Magneto
2. Data migration without errors or warning from 1.9.3.3

### Expected result
1. Save configuration without any error

### Actual result
1. [Screenshot, http://d.meat.no/DOwKYT]
2. Something went wrong while saving this configuration: Warning: array_keys() expects parameter 1 to be array, string given in vendor/magento/module-config/Model/Config/Backend/Translate.php on line 35

**Comment by oefterdal** [comment]
Was a row in core_config_data that had followed from Magento 1.9.3.3, I deleted it and is now working.

**Comment by chrom** [comment]
Have the same issue
http://prntscr.com/l0wdb2

**Comment by PhenomAmd** [comment]
excuse me but what line i mean some others arent that smart as you and we have same issue

**Comment by oefterdal** [comment]
@PhenomAmd in config_data table you should find the row that has this path 

`dev/translate_inline/invalid_caches`

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Config/Model/Config/Backend/Translate.php
