### ISSUE TITLE
A default billing address is not added to user

### ISSUE THREAD

**Issue by tristanisginger** [magento/magento2#14595]
### Preconditions
1. Magento 2.2.14, PHP 7.0, Fresh install with sample data

### Steps to reproduce
1. Create new user account (with any addresses saved)
2. add a product to basket & checkout
3. fill in address details and submit
4. on checkout page press submit

### Expected result

A default billing address should be added to the user

### Actual result

A default billing address is not added to the user
![image](https://user-images.githubusercontent.com/25447128/38487625-c0b528d6-3bd8-11e8-95d5-82bf23465e7b.png)

**Comment by ghost** [comment]
hi @tristanisginger thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by yuliantoadi** [comment]
I am working on this #mm18id

**Comment by magento-engcom-team** [comment]
@yuliantoadi thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by slavvka** [comment]
Hey @jeroenschipper Looks like you mistakenly created your PR https://github.com/jeroenschipper/magento2/pull/1 to your repo instead of magento ones

**Comment by ghost** [comment]
Hi @tristanisginger thank you for you report, this issue was retested and we can confirm that this already fixed in 2.3-develop branch and will be available on 2.3.1 release.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-14595-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14595-2-3-develop.instances.magento-community.engineering/admin](https://i-14595-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
