### ISSUE TITLE
Newsletter Template is not sending to Subscribed user emails

### ISSUE THREAD

**Issue by kikinbenshakib** [magento/magento2#14590]
I have facing problem to send Newsletter Template email to Subscribed user emails
. I don't know why it's happening with my Magento 1.9.x.

Could you please check the images below and give me an update how can I resolve it?

![screenshot from 2018-04-09 01-44-04](https://user-images.githubusercontent.com/22374102/38471826-7194053c-3b98-11e8-88cd-7d6aa0b3ccb0.png)

**Comment by magento-engcom-team** [comment]
Hi @kikinbenshakib Thank you for reporting.
Unfortunately this github issue tracker only relates to Magento 2 and not Magento 1.
Closing.
