### ISSUE TITLE
Magento Setup Tool - Step 2

### ISSUE THREAD

**Issue by elliothagerty** [magento/magento2#1459]
Using the web interface to install magento 2, I can't get past "Step 2: Add a Database". I enter all the info, click on next, and nothing happens!?

**Comment by elliothagerty** [comment]
P.S. I think i'm getting the "Unknown Database Server Host." error.

**Comment by roshimon** [comment]
Try installing it again. Give the correct database credentials.

**Comment by elliothagerty** [comment]
Installing the whole of Magento 2 again? Sorry, not sure what part you mean. Thanks.

**Comment by roshimon** [comment]
Try installing in on different browsers. For example try it on Mozilla Firefox .

**Comment by ark99** [comment]
If any of your entered information is not correct, you should see appropriate error message in pinkish box displayed  giving idea as to what may be the issue. 

Do you see any such message displayed ?

**Comment by ark99** [comment]
Can you please share the magento version number? You will find that info in the first few lines in "composer.json" file which is located in the apache root directory.

sample line would look like this: "version": "0.74.0-beta16",

Also if you could post your php.ini file contents?

**Comment by xcomSteveJohnson** [comment]
@elliothagerty Did you verify the database is running and that the host and port are correct? Is the DB server reachable from your Magento 2 server? Are they on different hosts?

**Comment by elliothagerty** [comment]
@ark99 I haven't had a pinkish box or anything pop up telling me whats wrong, soon as I hit the 'Next' button nothing happens, no errors, no loading!! I'm hosting the database on localhost.

@ark99 The Magento version number is "Version 0.74.0-beta16"

**Comment by mazhalai** [comment]
@elliothagerty What browser are you using? In both chrome and FF, you can view developer console. Do you see any errors in that?

**Comment by elliothagerty** [comment]
@mazhalai I'm using chrome, there is no errors being logged to the console at all.

**Comment by mazhalai** [comment]
Can you please try clearing your browser cache, delete contents of `var/cache` and `var/generation` and try again? Can you check your php and apache logs. Any errors in there? Also, did you check if your database is running as expected as mentioned by @xcomSteveJohnson above?

**Comment by elliothagerty** [comment]
@mazhalai I've cleared the browser cache, also tried it in incognito mode and nothing changed. 

Thanks for reminding me about the PHP error log. It seems I was using the wrong version of PHP although I was adamant this was not the case!!

Thanks for the help guys, always the simple things :)

**Comment by mazhalai** [comment]
@elliothagerty thank you for reporting the issue! Glad you figured it out!

**Comment by elliothagerty** [comment]
@mazhalai I am now not able to install on step 6, I'm getting the following error on 1%:
"Installing schema.. 
[ERROR] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'' in /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `st...', Array)
#5 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `st...', Array)
#6 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(488): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `st...', Array)
#7 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `st...', Array)
#8 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1761): Zend_Db_Adapter_Abstract->insert('store_website', Array)
#9 /Users/elliotmacbook/Sites/Hagerty/magento2/app/code/Magento/Store/Setup/InstallSchema.php(236): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('store_website', Array)
#10 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Model/Installer.php(761): Magento\Store\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#11 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Model/Installer.php(695): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#12 [internal function]: Magento\Setup\Model\Installer->installSchema()
#13 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Model/Installer.php(298): call_user_func_array(Array, Array)
#14 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#15 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#22 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#23 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#26 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY', query was: INSERT INTO `store_website` (`website_id`, `code`, `name`, `sort_order`, `default_group_id`, `is_default`) VALUES (?, ?, ?, ?, ?, ?)' in /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `st...', Array)
#4 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `st...', Array)
#5 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(488): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `st...', Array)
#6 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `st...', Array)
#7 /Users/elliotmacbook/Sites/Hagerty/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1761): Zend_Db_Adapter_Abstract->insert('store_website', Array)
#8 /Users/elliotmacbook/Sites/Hagerty/magento2/app/code/Magento/Store/Setup/InstallSchema.php(236): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('store_website', Array)
#9 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Model/Installer.php(761): Magento\Store\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#10 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Model/Installer.php(695): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#11 [internal function]: Magento\Setup\Model\Installer->installSchema()
#12 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Model/Installer.php(298): call_user_func_array(Array, Array)
#13 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#14 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /Users/elliotmacbook/Sites/Hagerty/magento2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /Users/elliotmacbook/Sites/Hagerty/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#25 {main}"

**Comment by mazhalai** [comment]
Do you have a previous installation? Did you install earlier with sample data? Looks like you have existing data in the database. You can either clean your db, or run `bin/magento setup:uninstall` and run web set up again.

**Comment by elliothagerty** [comment]
@mazhalai that managed to solve the problem. But now It is getting stuck on 71% during the installation. I stops when installing 'Magento_Catalog' and hangs. No errors that i can see. Thanks.

**Comment by xcomSteveJohnson** [comment]
Have you tried a command-line installation? 

http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-install.html

**Comment by buskamuza** [comment]
@elliothagerty , it takes some time on that step. Do you terminate the process after some time?
Do you have any errors in the server logs? What's memory limit for PHP? Do you have xDebug enabled?

**Comment by seabird** [comment]
@mazhalai I tried this but it re-installed the sample data again. How can I re-install without the sample data to import my database? (without doing a completely clean install)

**Comment by mazhalai** [comment]
Please try CLI http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-install.html

**Comment by seabird** [comment]
@mazhalai ok, did a completely clean install and dumped the database. Next tried the data-migration tool. Similar error:  [PDOException]  
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'association-2' for key 'SEARCH_QUERY_QUERY_TEXT_STORE_ID'

**Comment by mazhalai** [comment]
@seabird that is an issue for the [data-migration-tool](https://github.com/magento/data-migration-tool-ce). Please post this issue there.
