### ISSUE TITLE
Securety Scan PDF error no pages found when opening.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#14598]
Security scan PDF Error

### Preconditions

1.  If the PDF downloaded from the security scan page is opened it says error no pages found.
Wondering if i am the only one using this tool and having this error.

### Steps to reproduce

1. Open the pdf 

### Expected result
1. Error no pages found when opening the downloaded pdf 

### Actual result
1. The pdf wont open.

**Comment by orlangur** [comment]
@koopjesboom could you please provide more detailed steps? Are referring to some standalone service like https://magento.stackexchange.com/questions/198524/magento-security-scan-not-able-to-verify-site?

This repository is intended for bug reports in Magento Open Source exclusively.

**Comment by ghost** [comment]
Best,

Well I am and maybe a lot of users with me are unable to read security reports from Magento's security scan which should be available to keep people informed about the security of there magento environment. However, the only way to address this issue is here. Look at the bottom right in admin/back end and click on it. It redirects to GitHub. And on the security scan page itself where no issues can be reported. I can not address issues else ware because i cant find the information where to address such matter.

So if you could provide me the information to address such issues i will go there,

Thank you for the reply

**Comment by ghost** [comment]
Problem is solved. Don't know how, it works again.
