### ISSUE TITLE
Purchase Order and Zero subtotal checkout

### ISSUE THREAD

**Issue by springimport** [magento/magento2#14605]
### Preconditions
Magneto 2.2.3.
PHP 7.1.

### Steps to reproduce
1. Add product with 0 price to cart.
2. Try to buy using purchase order method.

### Expected result
1. Place order.

### Actual result
```
The requested Payment Method is not available.
```

I think problem with zeroTotalValidator in [PaymentMethodManagement](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Quote/Model/PaymentMethodManagement.php#L79).

```php
public function isApplicable(MethodInterface $paymentMethod, Quote $quote)
{
    return !($quote->getBaseGrandTotal() < 0.0001 && $paymentMethod->getCode() != 'free');
}
```

In Purchase Order in Admin Configuration we have a **Minimum Order Total** field. But magento ignore it and allows 0.00 total only for **free** payment method.

**Comment by ghost** [comment]
HI @springimport i cannot reproduce this on 2.2-develop branch

**Comment by kingshukdeb** [comment]
I could still see this in 2.3.2

![image](https://user-images.githubusercontent.com/4508615/142809333-366a6762-d70f-4831-8020-21f7b6104763.png)

**Comment by wmtkc** [comment]
I was hung up on this issue for a while. The correct way to handle a zero-total checkout with a purchase order is to set your purchase order method's Minimum Order Total (at Stores > Configuration > Sales > Payment Methods > Purchase Order) as `0.01`. That way, when a zero-total checkout is encountered, it will switch methods to Zero Subtotal Checkout, which will be handled properly by the zero-total validator check mentioned above.

If you are using a payment restriction plugin on your site, you may have to allow the Zero Subtotal Checkout method in your payment restrictions rule if you haven't already.

**Comment by xtremevision** [comment]
This is still present in 2.3.7-p4. Surely there's a better fix for this that would be payment method agnostic? For example, the PayPal Express module doesn't have a Minimum Order Amount field...
