### ISSUE TITLE
Magento Security Team ruined my back-end

### ISSUE THREAD

**Issue by andresromerolnl** [magento/magento2#14604]
### Preconditions

1. Change Admin Base URL, taking into consideration Magento Security Team's tips to protect our store.
2. 

### Steps to reproduce

1. Navigate to Stores > Configuration > Advanced > Admin > Admin Base URL
2. Change URL
3. Hit Save

### Expected result

1. New URL to access admin.

### Actual result

1. All CSS styles in backend lost, admin base URL didn't change. Admin works, but it's all in plain text! Tried to return the configuration back to how it was (default admin base URL), nothing happens when I save the settings, please help!

**Comment by xtremeperf** [comment]
Did you flush caches after changing the configuration?

There is lot of information in the Magento 2 DevDocs and much more can be found using a Google search regarding this topic.  I think some of it would help you complete your task,  Good luck!

**Comment by andresromerolnl** [comment]
Hi! I just tried doing it manually (FTP) deleting contents of var/cache folder, and now what happens is that neither the "new" url work, nor the original one. The "new" sends me to a 404 error page, the old one, just loads a blank page, it does load the <title> and favicon, but nothing else. And another thing, if i check the inspector, it seems to be trying to load resources from the "new" url. I checked the env.php file and it shows the original admin url.

I hope someone can help please!
![captura de pantalla 2018-04-10 a la s 10 10 15](https://user-images.githubusercontent.com/38218020/38565618-6a83dd2a-3ca7-11e8-8fe6-7ece337a895b.jpg)

**Comment by andresromerolnl** [comment]
UPDATE: So we cleared cache again, and admin is back on original URL, but still all messed up with no styles, and once inside I can't change setting or anything back (like the buttons don't work)... If you see attached screenshot, it's trying to load stuff from the "new" _incorrect_ URL... I wanted the URL to be ../admin_magento_ecommerce/ 

I really don't know what else to do, please help somebody, I'm losing sales opportunities as I write... ;(
![captura de pantalla 2018-04-10 a la s 10 31 46](https://user-images.githubusercontent.com/38218020/38566984-a3dc0f04-3caa-11e8-88e6-5a0f59cfe169.jpg)

**Comment by andresromerolnl** [comment]
**!SOLVED!**

So, a very kind person from the Magento security team helped me with this issue. Turns out something was wrong with the blog entry, they are correcting that... So to fix the issue the easiest way, is to go into your phpmyadmin and change the values of some lines where that "new" admin url I had chosen was wrongly inserted into, leaving only your public store html, and that should fix the issue. Thank you magento security team you rock !
