### ISSUE TITLE
Design Configuration is blank

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#14600]
### Preconditions
1. Magento 2.2.3 
2. PHP 7.1
3. Mysql 5.7 

### Steps to reproduce
1. Content
2. Design
3. Configuration

### Expected result
See configuration for theme

### Actual result
Page is blank : 
I only see: We couldn't find any records.

No trace of any related errors in log files either.

**Comment by oefterdal** [comment]
I also tried to do this, without any result: 

1. magento indexer:info
2. magento indexer:status
3. magento indexer:reset design_config_grid
4. magento indexer:reset
5. magento indexer:reindex
6. magento cache:clean
7. magento cache:flush

**Comment by oefterdal** [comment]
The indexer was just really slow, working now.

**Comment by effettidesigns** [comment]
Same issue, @oefterdal did you solved in some way?

**Comment by oefterdal** [comment]
@effettidesigns I just had to reindex

**Comment by effettidesigns** [comment]
@oefterdal what it means? can you please explain this to me? Thanks

**Comment by effettidesigns** [comment]
Ok I ran the reindex command through the Terminal 
`php bin/magento indexer:reindex`
but my issue is not resolved I can't even create pages, categories or products.
