### ISSUE TITLE
Products Moving to Unwanted Categories Automatically

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#14601]
### Preconditions

1.  I use nginx with varnish and redis
2.  Magento 2.2 php7.0 

### Steps to reproduce

1.  Sorry, but it's going to have to be ambiguous.  It seems this issue happens after the indexes are run automatically sometimes.  I will find product in categories they have not been assigned to.  Remove them, save, reindex.  And then a couple days later they will appear back in the same unwanted category.
2.   The only connection I can see is that in the admin, after doing a full reindex from ssh, even though ssh shows all indexes as processed, the timestamps on Product Categories and Catalog Product Rule do not change timestamps in admin, which makes me think the bug is somewhere in there.
3. I migrated from 1.9.2.4 a couple months ago and have seen this weird behavior from the start, but it is especially bad when products get moved to a sale category when they are not supposed to be.

### Expected result

1.  Products should not move categories on their own.

### Actual result

1. [Screenshot, logs] Products move categories on their own.

I have tried removing all catalog price rules and reindexing, but it doesn't fix the issue.  Further, I am a little skeptical of how the migration tool handled some of the attribute sets, and wonder if this is somehow connected to that as well.

**Comment by RishiMagento** [comment]
We are facing a similar issue.
Magento version: Enterprise 1.13
PHP version: 5.4.45

Any updates/patch/quick fixes on this?

Thanks!

**Comment by ladle3000** [comment]
Ours ended up being related to webgility unify module that was updating our
inventory from our quickbooks system.  Do you use that module?

**Comment by ghost** [comment]
@snoroozi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please try to reproduce this issue on a clean Magento installation without any custom modules. If you'd like to update it, please reopen the issue.
