### ISSUE TITLE
Installation Error in Command Line and Setup Wizard

### ISSUE THREAD

**Issue by hsuastegui** [magento/magento2#1460]
In 0.74.0-beta16 when trying to do a fresh installation via the command line or the setup wizard it throws an error:

Autoload error: Strict Notice: Declaration of Magento\Framework\App\Resource\Proxy::getTableName() should be compatible with Magento\Framework\App\Resource::getTableName($modelEntity, $connectionName = self::DEFAULT_READ_RESOURCE) in var/generation/Magento/Framework/App/Resource/Proxy.php on line 137

**Comment by mazhalai** [comment]
@hsuastegui what version of magento? Also, please try again after clearing generated classes in the `var/generation` folder.

**Comment by hsuastegui** [comment]
Thanks @mazhalai! it was solved removing the var/generation folder also it is important to remove the app/etc/config.php and app/etc/env.php to do a fresh install

**Comment by roshimon** [comment]
Great.
