### ISSUE TITLE
Out of stock or low quantity notification

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#14603]
Main important feature in magento 2 is missing where admin can be notified about products low Quantity or Out of stock notification, where system send an automated email to notify admin of the low Quantity and Out of stock of the product.

**Comment by magento-engcom-team** [comment]
@terrybakshi please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by sunilit42** [comment]
@terrybakshi 
https://github.com/sunilit42/lowstocknotification
i created one small module so it will help you
