### ISSUE TITLE
Warning store address has not been set under Store Information.

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#14606]
### Preconditions
1. Magento 2.2.3
2. PHP 7.1
3. Apache 2.4
4. Mysql 5.7

### Steps to reproduce
1. Log in to admin, and notification is displayed 

### Expected result
1. No notification

### Actual result
1. Warning store address has not been set under Store Information.
Store(s) affected: Admin(Admin)

Click here to go to General Configuration and change your settings.

This information is set under Store Information.

**Comment by oefterdal** [comment]
I still haven't figured out of this issue.

**Comment by ghost** [comment]
@oefterdal, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by palomaEcommistry** [comment]
@oefterdal did you get any solution ?

**Comment by oefterdal** [comment]
@palomaEcommistry i reinstalled Magento and the error was gone.

**Comment by medigeek** [comment]
FYI, in case you get this error, you need to setup your store's information:

> Login to your Magento 2 backend
> On the **Admin** sidebar, click on **Stores**. Then under **Settings**, choose **Configuration**.
>  In the panel on the left under **General**, choose **General**.
> Expand the Store Information section and fill in your store's information

source:  https://www.mageplaza.com/kb/how-setup-store-information-magento-2.html
