### ISSUE TITLE
 minicart & checkout translating problem

### ISSUE THREAD

**Issue by MidoAhmed** [magento/magento2#14619]
Hi, i'am using magento 2 to create a ecommerce website, so and my site should be in frensh and english language, i start translating all content all was fine, all strings were translated except the minicart & checkout, so after some googling i found that's a bug in magento 2 so someone can give me idea or solution here plz

### Preconditions

1. Magento ver. 2.1.3
2.Theme: Venustheme/blackstore

### Actual result
 
![capture](https://user-images.githubusercontent.com/21027357/38559689-9ae971d6-3ccb-11e8-8a5b-f0d78190a0e6.PNG)

i selected english language all strings translated fine expect minicart

**Comment by rstylenl** [comment]
update to 2.2.3. It's fixed threre!

**Comment by magento-engcom-team** [comment]
Hi @MidoAhmed Thank you for reporting.
We are now closing this ticket per comment above by @rstylenl
