### ISSUE TITLE
Content Design Configuration is showing no records

### ISSUE THREAD

**Issue by raymond62** [magento/magento2#14616]
After editing a Design Configuration and try to save it, i got an Error 500
Since there i get the message "We couldn't find any records." in the Design Configuration.
The records in the database are still there, shops and backofffice are working fine except that area.

### Preconditions
1. Latest Magento 2.2.3., PHP 7.0, MySql 5.6

### Steps to reproduce
1. Go to "Content -> Design -> Configuration" 

### Expected result
1. The shops to configure that are listed at "Stores -> Settings -> All Stores"

### Actual result
1. [Screenshot, logs]
![grafik](https://user-images.githubusercontent.com/29265078/38556607-8c2970ca-3cca-11e8-8bf0-7ff84826ff99.png)

**Comment by raymond62** [comment]
This article helped me to restore:

https://magento.stackexchange.com/questions/153234/content-design-config-shows-no-records-on-fresh-2-1-3-install

But it should not happen anyway i think, so a review of code might be usefull.

**Comment by ghost** [comment]
Hi @raymond62 can you provide more information ? I cannot reproduce by yours scenarios steps

**Comment by raymond62** [comment]
No, i'm sorry, it occured exacty as discribed and my solution was as mentioned.

**Comment by ghost** [comment]
@raymond62 Can you reproduce this on clean magento install ?

**Comment by raymond62** [comment]
No, this issue did not appear again. Think internet connection or some script got a break. If nobody else get this problem, it will not be that important. Thanks

**Comment by ghost** [comment]
@raymond62  thank you for your report.  we are closing this issue
