### ISSUE TITLE
Cart Items are not deleted after success checkout

### ISSUE THREAD

**Issue by vinhtrau** [magento/magento2#1461]
Is this new feature or is a bug?
<img width="1322" alt="screen shot 2015-07-09 at 09 56 14" src="https://cloud.githubusercontent.com/assets/5369193/8587039/f3c98d32-2620-11e5-8651-f305c40f692b.png">

**Comment by Zaylril** [comment]
Just to add to this ticket. There is also a bug where things appear in the mini basket (and you don't complete the order) but when you go to the checkout it says your cart is empty, even though it still has items in your mini basket.

**Comment by vpelipenko** [comment]
Duplicate of https://github.com/magento/magento2/issues/1418. Internal ticket: MAGETWO-37603

**Comment by vpelipenko** [comment]
Closed. #1418 is fixed and closed. @vinhtrau, please, verify it on the latest version.

**Comment by mukdam** [comment]
Hello,
I create custom order programmatic. But mini-cart have item

**Comment by grasdaggel** [comment]
Same here, the problem still exists.

**Comment by mukdam** [comment]
Please follow 
http://magento.stackexchange.com/questions/100615/magento-2-how-can-refresh-minicart-cache-after-clear-cart-session-and-place-orde

**Comment by grasdaggel** [comment]
Dear @mukdam, please elaborate this fix. Its not very clear how to apply this.

**Comment by jvhost** [comment]
FYI, commit 9093ce9c2f5a4ba8c60ef0dd0769e620b4ce6f18 wasn't carried over to 2.1.7 CE .. after changing the 2 files manually it worked perfectly.

FYI # 2: I'm able to get away with just changing module-checkout/view/frontend/templates/success.phtml - just need the following lines before the final div:

    <script>
        require([
            'Magento_Customer/js/customer-data'
            ], function (customerData) {
            var sections = ['cart'];
            customerData.invalidate(sections);
        });
    </script>

**Comment by Ctucker9233** [comment]
@magento-engcom-team This fix doesn't appear to be included in 2.2. Does it need to be ported?

**Comment by ghost** [comment]
Hi @vinhtrau this already ported to 2.2-develop, issue not reproducible on 2.2-branch
