### ISSUE TITLE
Products in cart not displaying 

### ISSUE THREAD

**Issue by Arthi22** [magento/magento2#14612]
![screenshot 320](https://user-images.githubusercontent.com/34380528/38547855-c7621058-3ce2-11e8-9161-a1a14b7ba3c1.png)

### Preconditions
Magento ver. 2.1.8

### Steps to reproduce
Reports - > Products in cart is not displaying anything.

### Expected result
Products in cart should display

### Actual result

1. Just displaying empty page with footer..

**Comment by magento-engcom-team** [comment]
Hi @Arthi22 
Please try one of the following:
* Check if issue is still reproducible with the latest version
* Check and post exception log here

Thanks!

**Comment by Arthi22** [comment]
Sorry, Im not expert in magento2. Im very begining level. How to update the
latest version magento. The store  running magento 2.1.7

**Comment by Arthi22** [comment]
Sorry, Im not expert in magento2. Im very begining level. How to update the latest version magento. The store  running magento 2.1.7

**Comment by magento-engcom-team** [comment]
Hi @Arthi22 
Please refer to Developer documentation on the subject http://devdocs.magento.com/guides/v2.1/comp-mgr/cli/cli-upgrade.html

**Comment by Arthi22** [comment]
Noted. Meantime kindly advise , products displaying only in ascending
order. Please visit link
https://balloonconnexion.com/balloon-products/bubble-balloons.html
Products not displaying in the descending order. How to solve this.

**Comment by magento-engcom-team** [comment]
Hi @Arthi22 
We are closing the ticket now as it seems that issue is solved.
Please note that we can not provide any help with websites linked.
