### ISSUE TITLE
resource access issue

### ISSUE THREAD

**Issue by neetusn** [magento/magento2#14628]
How do I reset administrator Role permissions through phpmyadmin 

### Actual result

1. [Screenshot, logs]

![image](https://user-images.githubusercontent.com/31565497/38591022-54bc5962-3d52-11e8-9489-eaa3a85e0163.png)

**Comment by magento-engcom-team** [comment]
@neetusn please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
