### ISSUE TITLE
Catalog-on-Demand Integration fails to authenticate (oAuth, Magento 2.1.8)

### ISSUE THREAD

**Issue by magolovanov** [magento/magento2#14625]
### Preconditions
1.  Magento CE 2.1.8 installation

### Steps to reproduce
1. Under System / Integrations, attempt to activate the Catalog-on-Demand integration (https://www.catalog-on-demand.com/print-catalog-pages-from-magento-content#how-to-import-from-magento2)

### Expected result
1. Callback script executes (oAuth client makes getRequestToken and then getAccessToken requests to eventually obtain access token / acces token secret)

2. Proceeding window opens

### Actual result
1.Whatever authorization type (http://php.net/manual/ru/oauth.construct.php#120509, scroll down to authorization type enums) and request method (GET, POST) we set for OAuth instance / getRequestToken call / getAccessToken call, server (Magento 2) response is an error

["body_recv"]=>  string(211) "oauth_problem=oauth_consumer_key+is+a+required+field%2C+oauth_signature+is+a+required+field%2C+oauth_signature_method+is+a+required+field%2C+oauth_nonce+is+a+required+field%2C+oauth_timestamp+is+a+required+field"

2. Next authorizartion steps fail due to this.The integration does not authenticate and remains disabled

**Comment by magento-engcom-team** [comment]
Hi @magolovanov 
Unfortunately we can not provide assistance with issues related to third-party services. Please contact integration vendor to get support.

**Comment by magolovanov** [comment]
Hello

we are the vendor. Our integration follows the guidelines at http://devdocs.magento.com/guides/v2.1//get-started/authentication/gs-authentication-oauth.html. Here is the callback script code:

`<?php

<...>

$data['mageUrl'] = $_POST['store_base_url'];

$data['consumerKey'] = $_POST['oauth_consumer_key'];

$data['consumerSecret'] = $_POST['oauth_consumer_secret'];

$data['verifier'] = $_POST['oauth_verifier'];

$requestTokenRequestUrl = $data['mageUrl'] . 'oauth/token/request';

$accessTokenRequestUrl = $data['mageUrl'] . 'oauth/token/access';

// Instantiate the OAuth client

$oauthClient = new OAuth($data['consumerKey'], $data['consumerSecret']);

$oauthClient->enableDebug();

<...>

try {

  // Fetch a request token and redirect to the magento site for authorization

  $requestTokenResponse = $oauthClient->getRequestToken($requestTokenRequestUrl, null, "POST");

  // Fetch an access token

  $oauthClient->setToken($requestTokenResponse['oauth_token'], $requestTokenResponse['oauth_token_secret']);

  $accessTokenResponse = $oauthClient->getAccessTokenResponse($accessTokenRequestUrl, null, $data['verifier'], "POST");

  <...>

} catch (Exception $e) {

  // for Magento 2.1.8, getRequestToken fails with the exception

  <...>

}
`
This callback script has worked well for us with Magento installations up to and including 2.1.5. It fails with the exception for our counterpart having Magento 2.1.8:

`["body_recv"]=> string(211) "oauth_problem=oauth_consumer_key+is+a+required+field%2C+oauth_signature+is+a+required+field%2C+oauth_signature_method+is+a+required+field%2C+oauth_nonce+is+a+required+field%2C+oauth_timestamp+is+a+required+field"`

- whatever authorization type and and request method we set in our callback script.

Similar issue posted earlier and not resolved: https://github.com/magento/magento2/issues/11821
