### ISSUE TITLE
SOAP API Does not send product updates to multisite 

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#14626]
Using SOAP API does not work when sending product updates to second Website.

For testing purpose I am using Postman: https://www.getpostman.com/apps   

2 Website under the same installation.
website 1 url = test.com  (default)
website 2 url = test.co.uk (second website) 
### Preconditions
1- Fresh Install Magento2.2.2.
2- Create second Website, second wesbite store and second store view an save, you should have something similar:
```
Default Config
  Main Website
    Main Website Store
       Default Store View
  Second Website
    Second Website Store
       Second Store View
```
3- go to store->configuration change store view to Second Website 
4- in store->configuration->web->baseUrls=> base Url Enter second website url and  base Link url  and do the same for baseUrls(secure).
5- in store->configuration change store view to Second Store view repeat step 4  
6- Create a simple product
7- Goto Sytem->integration and Add New Integration
8- Grab your Access Token.

### Steps to reproduce
Get Postman or any other soap testing platform and do the following:
1-Choose in the drop down POST and enter the url= **http://test.com/soap/second_store_view_code?services=catalogProductRepositoryV1**
2- Add Authorization type: Bearer Token and add Access token you just grabed.
3- Add Body  Raw and Enter your XML REQUEST:

`<?xml version="1.0" encoding="UTF-8"?>
     <soap:Envelope xmlns:def="http://test.com/soap/second_store_view_code? 
     services=catalogProductRepositoryV1" xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
        <soap:Body>
           <def:catalogProductRepositoryV1SaveRequest> 
              <product>
                 <sku>1234567890</sku> 
                 <price>99.99</price>
              </product>
          </def:catalogProductRepositoryV1SaveRequest>
      </soap:Body>
 </soap:Envelope>`

### Expected result
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:ns1="http://test.com/soap/second_store_view_code?services=catalogProductRepositoryV1">
    <env:Body>
        <ns1:catalogProductRepositoryV1SaveResponse>
            <result>
                <id>1234</id>
                <sku>1234567890</sku>
                <name>Test-product</name>
                <attributeSetId>2</attributeSetId>
                <price>99.99</price>
                <status>1</status>
                <visibility>1</visibility>
                <typeId>simple</typeId>
                <createdAt>##########</createdAt>
                <updatedAt>##########</updatedAt>
                <extensionAttributes>
                    <websiteIds>
                        <item>1</item>
                        <item>2</item>
                    </websiteIds>
                    <stockItem>
                        <itemId>12345</itemId>
                        <productId>123456</productId>
                        <stockId>1</stockId>
                        <qty/>
                        <isInStock>false</isInStock>
                        <isQtyDecimal>false</isQtyDecimal>
                        <showDefaultNotificationMessage>false</showDefaultNotificationMessage>
                        <useConfigMinQty>true</useConfigMinQty>
                        <minQty>0</minQty>
                        <useConfigMinSaleQty>1</useConfigMinSaleQty>
                        <minSaleQty>1</minSaleQty>
                        <useConfigMaxSaleQty>true</useConfigMaxSaleQty>
                        <maxSaleQty>10000</maxSaleQty>
                        <useConfigBackorders>true</useConfigBackorders>
                        <backorders>0</backorders>
                        <useConfigNotifyStockQty>true</useConfigNotifyStockQty>
                        <notifyStockQty>1</notifyStockQty>
                        <useConfigQtyIncrements>true</useConfigQtyIncrements>
                        <qtyIncrements>0</qtyIncrements>
                        <useConfigEnableQtyInc>true</useConfigEnableQtyInc>
                        <enableQtyIncrements>false</enableQtyIncrements>
                        <useConfigManageStock>true</useConfigManageStock>
                        <manageStock>true</manageStock>
                        <lowStockDate>2018-04-10 20:02:03</lowStockDate>
                        <isDecimalDivided>false</isDecimalDivided>
                        <stockStatusChangedAuto>1</stockStatusChangedAuto>
                    </stockItem>
                </extensionAttributes>
                <productLinks/>
                <options/>
                <mediaGalleryEntries/>
                <tierPrices/>
                <customAttributes>
                    <item>
                        <attributeCode>category_ids</attributeCode>
                        <value/>
                    </item>
                    <item>
                        <attributeCode>options_container</attributeCode>
                        <value>container2</value>
                    </item>
                    <item>
                        <attributeCode>required_options</attributeCode>
                        <value>0</value>
                    </item>
                    <item>
                        <attributeCode>has_options</attributeCode>
                        <value>0</value>
                    </item>
                    <item>
                        <attributeCode>url_key</attributeCode>
                        <value>test-product</value>
                    </item>
                    <item>
                        <attributeCode>tax_class_id</attributeCode>
                        <value>2</value>
                    </item>
                    <item>
                        <attributeCode>size</attributeCode>
                        <value>1036</value>
                    </item>
                    <item>
                        <attributeCode>color</attributeCode>
                        <value>1076</value>
                    </item>
                </customAttributes>
            </result>
        </ns1:catalogProductRepositoryV1SaveResponse>
    </env:Body>
</env:Envelope>
```
### Actual result
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
    <env:Body>
        <env:Fault>
            <env:Code>
                <env:Value>rpc:ProcedureNotPresent</env:Value>
            </env:Code>
            <env:Reason>
                <env:Text>Procedure not present</env:Text>
            </env:Reason>
        </env:Fault>
    </env:Body>
</env:Envelope>
```
Screen shoot for ref:

![screen shot 2018-04-10 at 21 10 39](https://user-images.githubusercontent.com/3495481/38581082-a5bc8584-3d03-11e8-9803-cfd800dce10d.png)

Thanks.

**Comment by lano-vargas** [comment]
@magento-engcom-team  Have you guys had a chance to test this ?

Is this a bug ? or the default behaviour ?

Thanks.

**Comment by lano-vargas** [comment]
knock knock is there anybody out there to confirm something, anything please!

Thanks.

**Comment by Darvex** [comment]
@lano-vargas I've experienced similar issue. Could you try adding `custom_store_view_code` to both URL you're sending POST data to, and also to the Envelope tag, after the host? So the URL ends up looking like ` http://test.com/second_store_view_code/soap/second_store_view_code?services=catalogProductRepositoryV1`.

This resolved the similar issue I had, maybe it'll help you too

**Comment by lano-vargas** [comment]
@Darvex  it didn't work for me, however the second_store_view_code only exist in the second website which is **http://test.co.uk** and changing the **xmlns:ns1** url works in the xml call only I've changed the main url like so:
`<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:ns1="http://test.co.uk/soap/second_store_view_code?services=catalogProductRepositoryV1">......`

But the Question still remains and shouldn't all stores view from a multisite be available on http://test.com as well?

**Comment by engcom-backlog-nickolas** [comment]
Hello @lano-vargas, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Hoszi** [comment]
@lano-vargas 
Try to use https instead of http

**Comment by qsolutions-pl** [comment]
Didn't work, same issue.

**Comment by ManishaVasani** [comment]
> knock knock is there anybody out there to confirm something, anything please!
> 
> Thanks.

Yes, Facing Same issue

**Comment by JRomeoSalazar** [comment]
Hi @lano-vargas @ManishaVasani please try to add /admin before /soap in the XML Envelope but no in the URL.

So, the URL would be:

https://magento.test**/soap**/all?services=catalogProductRepositoryV1

And the Envelope would be:

```
soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:all="https://magento.test**/admin**/soap/all?services=catalogProductRepositoryV1%2CsalesOrderRepositoryV1%2CsalesOrderManagementV1">
   <soap:Header/>
   <soap:Body>
      <all:catalogProductRepositoryV1GetListRequest>
      ...
```

This way I've been able to fix the Procedure not present error:

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="https://trangoworld.levelstage.com/admin/soap/all?services=catalogProductRepositoryV1%2CsalesOrderRepositoryV1%2CsalesOrderManagementV1">
    <env:Body>
        <ns1:catalogProductRepositoryV1GetListResponse>
            <result>
                <items>
                    <item>
                        <id>16</id>
                        <sku>24-UG07</sku>
                        <name>Dual Handle Cardio Ball</name>
                        ...
```

I hope this helps.

**Comment by JoostWan** [comment]
@JRomeoSalazar Same problem over here. Tested it with your version but still same issue.
