### ISSUE TITLE
Private Variables & Functions in app/code/Magento/Eav/Setup/EavSetup.php

### ISSUE THREAD

**Issue by SRaromicon** [magento/magento2#14639]
### Preconditions

1. Magento 2.2+

### Steps to reproduce

1. Try to create an own Setup Class by extending app/code/Magento/Eav/Setup/EavSetup.php

### Expected result

1. All functions and variables could be extended

### Actual result

1. Private Functions and Variables are not accessable, without any reason.

Would be awesome to use app/code/Magento/Eav/Setup/EavSetup.php as Blueprint for own Setup Classes, where you can change any function and variable from EavSetup. So you can implement your own way to setup Attributes, without writing tons of code.

**Comment by ghost** [comment]
hi @SRaromicon GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
