### ISSUE TITLE
How to get coupon code discounted price for bundle items in magento2

### ISSUE THREAD

**Issue by mtkumar82** [magento/magento2#14643]
I have magento2 installed and I created a coupon code under promotion section. I need to send the discount price for each product individually in my payment getway. I am using code like  
<code> $amount = ($item->getPrice() - ($item->getDiscountAmount() / $qty)) * $qty;</code>
for getting price after discount. This code working fine for simple products. But when I am checking it for bundle products, <code>$item->getDiscountAmount()</code>  Its always giving me Null value for bundle items. I did lot of google and still no help. Anyone here please help me to get ride of this issue.

Thanks in advance.

**Comment by mtkumar82** [comment]
May I know the meaning of G1 Failed Label plz? Any issue with my question?

**Comment by magento-engcom-team** [comment]
@mtkumar82 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
