### ISSUE TITLE
Varnish cache based on user agents

### ISSUE THREAD

**Issue by venkivenkatesh** [magento/magento2#14644]
Preconditions
Magento 2.2.2
Varnish enabled

Steps to reproduce
Based on php snippet code which detects device based on user agents,i am printing "IN Desktop" in desktop & "In mobile"
in mobile device.

But once the page is cached,it is printing the "IN Desktop" both in desktop & mobile 

Expected result

"In Desktop" should be printed in desktop & "In mobile" should be provided in mobile

Is there any possibility to generate different caches based on the user agents

**Comment by magento-engcom-team** [comment]
@venkivenkatesh please refer to the [Magento Stack Exchange](https://magento.stackexchange.com/) or the [Community Forums](https://community.magento.com/) for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magefan** [comment]
@venkivenkatesh , have you found a solution?

**Comment by venkivenkatesh** [comment]
Yes By tweaking varnish default.vcl file

**Comment by magefan** [comment]
@venkivenkatesh is there any way you could share the solution?

**Comment by venkivenkatesh** [comment]
Please follow this link:

https://stackoverflow.com/questions/49775906/magento-2-varnish-cache-based-on-user-agents
