### ISSUE TITLE
SourceMap generation for JS

### ISSUE THREAD

**Issue by kirmorozov** [magento/magento2#14646]
### Preconditions

1. Debugging JS in production is hard.
2. SourceMaps allow to debug in production even with minified/uglified js.

### Steps to reproduce

1. Produce error in JS
2. Build JS in production mode
3. Trigger js error in Chrome

### Expected result

1. I expect Chrome to pull source-map from server and provide me exact place like code was never minified.

### Actual result

1.  It shows you some problem at line 1.

**Comment by magento-engcom-team** [comment]
Hi @kirmorozov 
This issue seems to duplicate #9011
We are going to close this ticket now, please continue tracking under that reference.

Thanks

**Comment by kirmorozov** [comment]
@magento-engcom-team This is sourcemaps for all minified javascript.

**Comment by orlangur** [comment]
@kirmorozov GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
