### ISSUE TITLE
[2.1.12] PDF Invoice doesn't show cart price rule coupon code name

### ISSUE THREAD

**Issue by aeu** [magento/magento2#14645]
If a discount code is used, the generated PDF invoice totals box does not contain the name of the discount used.  The sales email however, does.  I have attached screenshots of totals box of both the sales confirmation email and the and PDF invoice, showing the issue.

### Preconditions
1. Magento version 2.1.12.  Centos 7.4.  PHP7.  MariaDB 10.1.32 

### Steps to reproduce
1. Clean slate Magento, with one product
2. Create a cart price rule with a coupon code to apply a discount
3. Place order (I used pay by check)

### Expected result
1.  The PDF invoice and sales order confirmation email are consistent.

### Actual result
1. The discount code is not shown in the totals column.  
2. The order of items is inconsistent (Subtotal, Discount, Shipping & Handling, Grand Total vs. Subtotal, Shipping & Handling, Discount, Grand Total).

PDF Invoice:

![00-pdf](https://user-images.githubusercontent.com/2225377/38623035-a133259e-3d72-11e8-81bd-74a6c40337aa.png)

Email: 

![00-email](https://user-images.githubusercontent.com/2225377/38623526-decc1234-3d73-11e8-963d-8697a765fdc5.png)

**Comment by ghost** [comment]
@aeu, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by nkajic** [comment]
Hi to all, I have tested this on 2.3-develop now and can confirm that it works or have beed fixed in 2.3-developer branch.

**Comment by anujwebkul** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul, here is your [Magento instance](https://i-14645-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14645-2-3-develop.instances.magento-community.engineering/admin](https://i-14645-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by anujwebkul** [comment]
It's working fine with the 2.3-develop branch.

**Comment by magento-engcom-team** [comment]
@aeu, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
