### ISSUE TITLE
free shipping coupon does not works

### ISSUE THREAD

**Issue by aaureli-alp** [magento/magento2#14657]
### Preconditions

1. I followed all the instructions as to create a free shipping coupon but when I enable the free-shipping-method, in the checkout is always displayed 'free shipping' as shipping method thought I haven't inserted the coupon code.
2. Magento ver. 2.2.2 EE

### Steps to reproduce

1. enable free-shipping from store>configuration>sales>shipping methods
2. enable free-shipping in the carrier (DHL)
3. create a cart-price rule like 'free-shipping' with specific coupon codes

### Expected result

1. Free shipping option should be displayed only after that the customer inserts the related free-shipping coupon code

### Actual result

1.  Free shipping is always displayed

**Comment by ghost** [comment]
@aaureli-alp, thank you for your report. This is not a bug.
Free shipping is always displayed because you enable it in store>configuration>sales>shipping methods.
