### ISSUE TITLE
REST API Product Media DELETE V1/products/SKU/media/ID does not work

### ISSUE THREAD

**Issue by SchnackSchnick** [magento/magento2#14651]
### Preconditions

1. Magento 2 2.2.3
2. Magento 2 2.2.3 Bitnami Image

### Steps to reproduce

1.  Create a new product manually, name it newpicture, fill out SKU and Stock
2. Upload one image into this SKU
3. GET HOST/rest/V1/products/newpicture/media and check ID
4. DELETE HOSTrest/V1/products/newpicture/media/10 <--actuall ID
5. Check Response Body: true

### Expected result

1. Check again GET HOST/rest/V1/products/newpicture/media should be empty

### Actual result

1. [ { "id": 10, "media_type": "image", "label": null,  "position": 1,  "disabled": false,  "types": [],"file": "/1/_/1_1.jpg" }]

**Comment by SchnackSchnick** [comment]
As soon I use 

DELETE HOST/rest/all/V1/products/newpicture/media/10

/ALL/ <-difference

It works 

This is confusing i did not found /all/ in any example what does it mean?

Working with swagger and all those informations is ok, but several detals are missing. for example in the MEDIA API there is no list of MIME types to use. So image/jpg does not work but image/jpeg does work.
Easy to find if tehre would be more examples or better reallive example the example are all with empty data like "string" and 0.

**Comment by ghost** [comment]
Hi @SchnackSchnick the all->  means all store example -> DELETE HOST/rest/store_code/V1/products/newpicture/media/10
