### ISSUE TITLE
File upload in system configuration

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#14656]
### Preconditions

1. Magento 2.1.7, php 7.0, MySQL 5.7

### Steps to reproduce

1. Create a simple module with a system configurable section (ACL & system.xml)
2. Add a new system field, type "file":
```
<field id="custom_file_upload" translate="label" type="file" sortOrder="6" showInDefault="1" showInWebsite="1" >
                    <label>Upload CSV file</label>
                    <comment>You need to upload a CSV file first in order to import files</comment>
                </field>
```

### Expected result

1. system value should only store value: upload_dir/file_name
2. File should be uploaded

### Actual result

1. File is not uploaded to the server
2. System value after save has all file info, not just the file name, like this: `Task1.pdf,application/pdf,/tmp/phptQ1hKw,0,221125
`
3. System value keeps getting updated with new value, but its adding new file info it to old value, not replacing it:
`Task1.pdf,application/pdf,/tmp/phptQ1hKw,0,221125,ksabat-cv.pdf,application/pdf,/tmp/phptuVmSK,0,217213` - this is how value looks like second file import
4. User should be able to remove the file / clear settings, it does no work now for FILE type

**Comment by jakwinkler** [comment]
Quick note:
adding a node in system.xml file 
`<backend_model>Magento\Config\Model\Config\Backend\File</backend_model>`
to a field solves a problem but I think that a type="file" should set the backend_model to proper one.

**Comment by ghost** [comment]
Hi @qsolutions-pl   backend_model. It is used to handle the process of uploading the file: setting the upload directory.
