### ISSUE TITLE
setup:static-content:deploy fails with 3rd party (Codazon) theme

### ISSUE THREAD

**Issue by chakravarthykalyan90** [magento/magento2#14659]
We tried upgrading our Magento from 2.1.7 to 2.1.12 which has Codazon theme installed already. After upgrade static content deploy is resulting in errors.

### Preconditions

1. Environment Magento 2.1.7, PHP 7.0, Ubuntu

### Steps to reproduce
1. Upgrade Magento 2.1.7 ( Codazon theme installed ) to 2.1.12
2. Run static content deploy command

### Expected result

1. Static content deploy should run without any errors

### Actual result

1. Static content deploy has errors

`Compilation from source: /var/www/html/project/app/design/frontend/Codazon/fastest/outdoor/web/css/email.less

Compilation from source:
frontend/Codazon/fastest_outdoor/en_US/css/email.less
Unable to get content for 'frontend/Codazon/fastest_outdoor/en_US/Magento_Bundle/css/source/_email.less'

......

Compilation from source: /var/www/html/project/app/design/frontend/Codazon/fastest/outdoor/web/css/email-inline.less

Compilation from source:
frontend/Codazon/fastest_outdoor/en_US/css/email-inline.less
Unable to get content for 'frontend/Codazon/fastest_outdoor/en_US/Magento_Bundle/css/source/_email.less'

......................

Compilation from source: /var/www/html/project/app/design/frontend/Codazon/fastest/outdoor/web/css/styles-l.less

Compilation from source:
frontend/Codazon/fastest_outdoor/en_US/css/styles-l.less
Unable to get content for 'frontend/Codazon/fastest_outdoor/en_US/Codazon_AjaxLayeredNav/css/source/_module.less'

......

Compilation from source: /var/www/html/project/app/design/frontend/Codazon/fastest/outdoor/web/css/styles-m.less

Compilation from source:
frontend/Codazon/fastest_outdoor/en_US/css/styles-m.less
Unable to get content for 'frontend/Codazon/fastest_outdoor/en_US/Codazon_AjaxLayeredNav/css/source/_module.less'`

**Comment by magento-engcom-team** [comment]
Hi @chakravarthykalyan90 
Unfortunately we can not provide any assistance for issues caused by third-party extensions.
Please contact extension vendor's support directly.
Thank you.
