### ISSUE TITLE
Consider dropping mcrypt dependency

### ISSUE THREAD

**Issue by kabel** [magento/magento2#1466]
The mcrypt php extension and the underlying libmcrypt are unmaintained and there is a strong effort to remove them from the PHP core. [[1]] [[2]]

This would be a good opportunity to port any password or data encryption to the better maintained openssl or password extensions.

[1]: http://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt
[2]: http://thefsb.tumblr.com/post/110639027905/custodians-of-php-vote-to-keep-a-crypto-lib

**Comment by pronto2000** [comment]
Pretty much every payment method there uses Mcrypt. I don't think there's a way to get rid of it that easily.

**Comment by kabel** [comment]
I'm fairly certain there isn't anything the Magento app is doing with mcrypt that couldn't be trivially ported to openssl.

**Comment by piotrekkaminski** [comment]
We are aware of that, internal ticket MAGETWO-39838. As this is not scheduled yet, if someone wants to contribute the change as a pull request, we would appreciate that.

Do you have any recommendation which library should be used instead?
If this is not PHP core functionality, it should be:
- actively supported and stable
- best if compatible/endorsed by Zend Framework/Symfony

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Consider-dropping-mcrypt-dependency/idi-p/46568).
