### ISSUE TITLE
Customer Configuration - myurl.com/@custom - Error 404

### ISSUE THREAD

**Issue by mageuser** [magento/magento2#14671]
Magento 2.2.3

Cant change customer configuration anymore, its redirect to a 404 url -> mysite.com/@custom, doesn't matter which section i change, all configs from Customer configuration redirect to /@custom and does not save changes.

**Comment by mageuser** [comment]
Anyone from Magento Staff can check my site? Thanks.

**Comment by magento-engcom-team** [comment]
@kauansoft thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by mageuser** [comment]
@magento-engcom-team 

Panel: CWP7pro
Magento 2.2.3
Nginx + Varnish + Redis
Apache version: Apache/2.4.29
PHP version: 7.1.9
MySQL version: 10.1.31-MariaDB 

I've comment (line 49) throw exception on : public_html\/vendor\/magento\/module-customer\/Model\/AddressRegistry.php.

This error was going on since first week (on a fresh installation). It happens for logged users only. (i've reported here).

Because this file was reporting:
No such entity with addressId = 1","1" for no reason.

Production mode.
I've used setup decompile.
I'm running magento cron.

I've changed domain using n98 (ex: domain.com to domain.com.br).

Commands that I used:
rm -rf var/page_cache var/cache var/composer_home var/generation var/di var/view_preprocessed
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy -f
php bin/magento setup:static-content:deploy pt_BR -f
php bin/magento setup:upgrade
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
find /home/admin/public_html/ -type d -exec chmod 755 {} \;
find /home/admin/public_html/ -type f -exec chmod 644 {} \;
chown -R admin:admin /home/admin/public_html/
php bin/magento cache:flush

Active Modules:
Magento_Store
Magento_Directory
Inchoo_Shipping
Magento_Eav
Magento_Backend
Magento_AdvancedPricingImportExport
Magento_Config
Magento_Authorization
Magento_Theme
Magento_Customer
Magento_Backup
Magento_AdminNotification
Magento_Indexer
Magento_BundleImportExport
Magento_CacheInvalidate
Magento_Cms
Magento_Catalog
Magento_Security
Magento_CatalogImportExport
Magento_Quote
Magento_Cron
Magento_Msrp
Magento_Search
Magento_CatalogUrlRewrite
Magento_Rule
Magento_SalesSequence
Magento_Payment
Magefan_Blog
Magento_CmsUrlRewrite
Magento_User
Magento_ConfigurableImportExport
Magento_CatalogRule
Magento_CatalogInventory
Magento_Contact
Magento_Cookie
Magento_Widget
Magento_CurrencySymbol
Magento_Sales
Magento_Integration
Magento_CustomerImportExport
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_Checkout
Magento_Downloadable
Magento_ImportExport
Experius_AddressLines
Magento_Email
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_GroupedImportExport
Magento_GroupedProduct
Magento_DownloadableImportExport
Magento_Bundle
Magento_InstantPurchase
Magento_Analytics
Magento_LayeredNavigation
Magento_Marketplace
Magento_MediaStorage
Magento_ConfigurableProduct
Magento_Multishipping
Magento_NewRelicReporting
Magento_Reports
Magento_OfflinePayments
Magento_SalesRule
Magento_PageCache
Magento_Authorizenet
Magento_Vault
Magento_Persistent
Magento_ProductAlert
Magento_ProductVideo
Magento_Paypal
Magento_QuoteAnalytics
Magento_ReleaseNotification
Magento_Review
Magento_RequireJs
Magento_Shipping
Magento_ReviewAnalytics
Magento_Robots
Magento_Rss
Magento_CatalogWidget
Magento_CheckoutAgreements
Magento_SalesAnalytics
Magento_SalesInventory
Magento_OfflineShipping
Magento_CatalogRuleConfigurable
Magento_UrlRewrite
Magento_CatalogSearch
Magento_CustomerAnalytics
Magento_SendFriend
Magento_Newsletter
Magento_Signifyd
Magento_Sitemap
Magento_Captcha
Magento_Swagger
Magento_Swatches
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxImportExport
Magento_ConfigurableProductSales
Magento_Translation
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_CatalogAnalytics
Magento_Usps
Magento_Variable
Magento_Braintree
Magento_Version
Magento_Webapi
Magento_WebapiSecurity
Magento_Weee
Magento_Wishlist
Dotdigitalgroup_Email
Magento_WishlistAnalytics
Mageplaza_Core
Mageplaza_Smtp
Meigee_Barbour
Meigee_CategoriesEnhanced
Meigee_Instagram
Meigee_ProductWidget
Moip_Magento2
Paulmillband_AdminProductsToCategory
Rubic_CleanCheckout
Shopial_Facebook
Temando_Shipping
Tigren_Ajaxsuite
Tigren_Ajaxcart
Tigren_Core

I can share server/magento access.

Magento was working fine with all modules, its just broken recently.

**Comment by mageuser** [comment]
@magento-engcom-team 
Im getting 302 Moved Temporarily on this post:
myurl.com/admin/system_config/save/section/customer/key/cb2194ed93bdd8aaa4b71343bd2ed20411f6c57df2478da0bb0ed840d989cfb1/

**Comment by magento-engcom-team** [comment]
@kauansoft 
Thank you for the updated information. Unfortunately, it is mostly server configuration, but not clear steps to reproduce the issue. 
Additionally, commenting out error handling may cause any kind of side-effects, It is not suggested to do that.
