### ISSUE TITLE
Missing css files `styles-l.css` and `styles-m.css`

### ISSUE THREAD

**Issue by vernard** [magento/magento2#1467]
I installed Magento2 (version 0.74.0-beta16) via web interface. After the installation and going in the frontend, page is broken on frontend (no css), but everything is fine on admin panel.

**Comment by MomotenkoNatalia** [comment]
Thanks for reporting this issue. We will try to solve it as soon as possible.
Internal reference: MAGETWO-39676

**Comment by dfediuk** [comment]
How to fix «styles-l.css» and «styles-m.css» not loading bug in Magento 2.0 0.74.0-beta16: https://mage2.pro/t/topic/18

**Comment by vernard** [comment]
@dfediuk I can confirm that it worked after the fix you have provided.

**Comment by vpelipenko** [comment]
This issue was resolved and available here in GitHub. Please, verify it on the latest 1.0.0-beta version.

**Comment by dfediuk** [comment]
Yes, it is resolved.
