### ISSUE TITLE
Sorting Bundle Products in a catagory does not work correctly

### ISSUE THREAD

**Issue by densen45** [magento/magento2#14682]
### Preconditions

Magento 2.2.3

### Steps to reproduce

1. Create several Bundle Products
2. Create a category
3. Add several Bundle Products to this category
4. Enable product listing sort by price for the category
5. Go to the category on frontend
6. Choose sorting by price (ascending or descending)

### Expected result

The Bundle Products are being listed sorted by their minimum price values.

### Actual result

The Bundle Products are being listed in an arbitrary order.

Notice: Sometimes it seems to work, but this is random. Delete and add some Bundles to the category and you may be able to break the sorting.

This feature works fine for Simple Products.

**Comment by ghost** [comment]
@densen45, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by densen45** [comment]
@engcom-backlog-pb thank you for your efforts! You are right, we can not reproduce this issue on a clean 2.2.3 installation.

However, do you have any idea what might be the cause for this issue? Just to push us in the right direction ...

**Comment by ghost** [comment]
@densen45, maybe the problem is caused by some custom module. Anyway, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
