### ISSUE TITLE
Bundled jQuery fails PCI compliance scan

### ISSUE THREAD

**Issue by nahall** [magento/magento2#14694]
### Preconditions
1. Magento 2.2.3.

### Steps to reproduce
1. PCI compliance scan.

### Expected result
1. PCI compliance scan should pass.

### Actual result
1. PCI compliance scan fails.

The currently bundled version of jquery fails our PCI compliance vendor's scans as of January 23rd. They have added a security check for jquery due to the vulnerabilities CVE 2015-9251 and CVE 2016-10707 and now require at least jQuery 3.0.0 in order to be found compliant. Many other Magento sites will be found not compliant this quarter as they come up to their quarterly scans unless jQuery is upgraded to 3.x.

**Comment by kirmorozov** [comment]
Same as https://github.com/magento/magento2/issues/15156
You can patch the core to be compatible with jQuery 3.x. Effort was dedicated here: https://github.com/magento/magento2/issues/13685

**Comment by magento-engcom-team** [comment]
Hi @nahall 
Closing this ticket as duplicate of #15156. Please continue tracking under that reference.
