### ISSUE TITLE
Shipping data not saved after cache flushed until first visit to checkout maded

### ISSUE THREAD

**Issue by caww** [magento/magento2#14697]
Our website (wine store) is
https://winesellersdirect.com.au/

### Preconditions
1. Magento 2 CE (2.2.3 ver)
2. mysql 5.6
3. php 7.0.26
4. Apache Version | 2.4.33
5. Ultimo theme 2.7.1

### Steps to reproduce
1. Change any product or page -- not important
2. Flush cache in admin of magento 2
3. Go to front as visitor (not logged)
4. Add any product to cart
5. Go to checkout
6. Enter shipping / billing data
7. go to next (to payment method selection section)
8. Here you are! issue appears! --- in payment section shpping / billing data lost ---- not saved.
Because when i just entered shipping / billing data then clicked NEXT and system double reloaded page in payment section!!! this moment is very important !!! 
Because in second time all is working fine

It means system start working properly only after first visit (cache recreated in this moment after last flush)

Due this issue exist - i must to emulate buy process every time when i clear / flsuh the cache in magento 2

### Expected result

1. I sure that system must to re-create cache by yourself after every flush as minimum in checkout process - to prevent customers from worry about why data lost and from repeat this process of checkout again.

### Actual result

1. [Screenshot, logs]
![cache11](https://user-images.githubusercontent.com/7277051/38762473-115457a2-3f95-11e8-98a6-511b45da410e.png)

**Comment by ghost** [comment]
Hi @caww I cannot reproduce by you scenario, we close this issue, if you'd like to update this issue please reopen the issue
![frame-12d](https://user-images.githubusercontent.com/40756439/43313543-ff477502-9198-11e8-869c-2ef09922b313.gif)
