### ISSUE TITLE
Magento 1.9.2.4 -> 2.2.3 - url rewrites stopped working for imported products only after migration using magento migration tool

### ISSUE THREAD

**Issue by caww** [magento/magento2#14698]
Our website (wine store) is
https://winesellersdirect.com.au/

I created my issue long time ago here
https://github.com/magento/data-migration-tool/issues/462
But still no answer
only info about ticket MAGETWO-87957
Please help

### Preconditions
1. Magento 2 CE (2.2.3 ver)
2. mysql 5.6
3. php 7.0.26
4. Apache Version | 2.4.33
5. Ultimo theme 2.7.1

### Steps to reproduce

1. Take magento 1.9.2.4
2. Take data migration tool
3. Take magento 2.2.3
4. migrate 1.9.2.4 to 2.2.3
5.  change URL in any from imported product to new  (if you create NEW product (not imported) and change url to NEW there - all will be fine!!! issue with imported products only)
6. save and flush cache and reindex

### Expected result
1. new url must working
2. url rewrites rules must be updated

### Actual result
1. Absolulety nothing changed / happend with url rewrites
2. new url is not working at all because redirection rules not updated!

**Comment by magento-engcom-team** [comment]
Hi @caww 
Unfortunately, we can not keep another duplicate report here. Please continue tracking this issue under magento/data-migration-tool#462
