### ISSUE TITLE
Tables rates not loaded in checkout if only enabled for website

### ISSUE THREAD

**Issue by jokeputs** [magento/magento2#14690]
### Preconditions
1. Magento 2.2.2

### Steps to reproduce
1. Have a Magento 2.2.2 installation with at least 2 websites.
2. In the admin panel go to Stores -> Configuration -> Sales -> Shipping method -> Table Rates. Set **Enable** to **No** for the default configuration and save the configuration.
3. Change the Store View to one of the websites. For the tables rates set **Enable** to **Yes** and configure your tables rates. You could use the rates for the US which are in the Magento sample data:
```
Country,Region/State,"Zip/Postal Code","Order Subtotal (and above)","Shipping Price"
USA,*,*,0.0000,15.0000
USA,*,*,50.0000,10.0000
USA,*,*,100.0000,5.0000
USA,AK,*,0.0000,20.0000
USA,AK,*,50.0000,15.0000
USA,AK,*,100.0000,10.0000
USA,HI,*,0.0000,20.0000
USA,HI,*,50.0000,15.0000
USA,HI,*,100.0000,10.0000
```
4. Save the configuration.
5. As a guest, visit the website with the configured tables rates, add an item to your cart and proceed to the checkout.

### Expected result
1. When, as a guest, I change my shipping country the US and my state to Alaska, the available shipping methods are reloaded. I can see the shipping cost for the shipping method table rates.

### Actual result
1. I do not get a shipping cost for the shipping method table rates.

Some other things I've noticed:
- If I fill in my shipping address and reload the checkout, the shipping cost is calculated.
- The javascript validation files for the table rates are not loaded in the checkout (e.g. Magento_OfflineShipping/js/model/shipping-rates-validation-rules/tablerate.js)

**Comment by engcom-backlog-nickolas** [comment]
Hello @jokeputs, thank you for your report. Unfortunately I wasn't able to reproduce this issue.
![peek 2018-08-15 17-02](https://user-images.githubusercontent.com/40755810/44152103-3d795ade-a0ad-11e8-850a-2b6ebb24ec64.gif)

If you'd like to update it, please reopen the issue.
