### ISSUE TITLE
Err :   The configuration parameter "componentType" is a required for "tier_price" component.

### ISSUE THREAD

**Issue by ChandrakantDevani** [magento/magento2#14701]
**Issue**
Please help me to solve it, i have upgrade magento 2.1.5 to 2.2.3 give me the error only Configurable Product in admin panel 
### Preconditions

1. Magento 2.2.3
2. Mysql 5.6
3. PHP 7.0.2

### Steps to reproduce

1. Upgrade Magento Version 2.1.5 to 2.2.3
2. Give this Error "The configuration parameter "componentType" is a required for "tier_price" component."
3. Go to Product into Configurable Product edit or create a new product

### Expected result

1. Display edit or create product same as a simple product in admin

### Actual result

![firefox_screenshot_2018-04-14t09-29-40 892z](https://user-images.githubusercontent.com/28138615/38766779-85d70408-3ff4-11e8-8b3c-36643776091c.png)

**Comment by magento-engcom-team** [comment]
Hi @ChandrakantDevani Thank you for reporting.
Please try one of the following:
* Attempt to remove extensions which do not support 2.2 yet, most likely one of them is causing an error.
* Take a look at the exceptions log to figure out which customization exactly is causing the issue.

Thank you

**Comment by ChandrakantDevani** [comment]
Hey, Thank you for support. I got it bug this problem in extension. thanks
i am close this issue
