### ISSUE TITLE
Install via composer package magento/extension-b2b

### ISSUE THREAD

**Issue by webds** [magento/magento2#14709]
Hello.
I have error.
Install via composer package magento/extension-b2b

Magento v2.2.3
[InvalidArgumentException]
Could not find a matching version of package magento/extension-b2b. Check t
he package spelling, your version constraint and that the package is availa
ble in a stability which matches your minimum-stability (stable).

**Comment by magento-engcom-team** [comment]
Hi @webds thank you for your report. Please follow these guidelines for proper tracking of your issue: 

You can report Commerce and B2B related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

Additionally, please take a look at the B2B extension installation guide: http://devdocs.magento.com/guides/v2.2/comp-mgr/install-extensions/b2b-installation.html

**Comment by kazimnoorani** [comment]
I have got a solution which worked for me.

1. If you get an error when trying to install the B2B module for a local instance of Magento Commerce (for example: `[InvalidArgumentException] Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).`), you need to create an `auth.json` file in the Magento root directory and add the following code, using the actual values of your `public_key` and `private_key` for `username` and `password`:

2. Create `auth.json` file like 
````
{
   "http-basic": {
      "repo.magento.com": {
         "username": "<public_key>",
         "password": "<private_key>"
      }
   }
}
````

3. Execute `composer require magento/extension-b2b=^1.0`

4. Execute `composer update`

5. Run Magento commands
````
bin/magento setup:upgrade

bin/magento setup:di:compile

bin/magento setup:static-content:deploy -f

bin/magento cache:clean
````

**Comment by mediadiv** [comment]
I have the same problem with the B2B installation:
Get following message:
 composer require magento/extension-b2b


  [InvalidArgumentException] Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is
   available in a stability which matches your minimum-stability (stable).


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...



Magento ver. 2.3.2
PHP 7.2

I have do all the steps for the installation:


    Create auth.json file like

{
   "http-basic": {
      "repo.magento.com": {
         "username": "<public_key>",
         "password": "<private_key>"
      }
   }
}

    Execute composer require magento/extension-b2b=^1.0

    Execute composer update

    Run Magento commands

bin/magento setup:upgrade

bin/magento setup:di:compile

bin/magento setup:static-content:deploy -f

bin/magento cache:clean


And the Privat and public-keys are working correct.

Is it possible to download this extensions direct for install it not via composer?

**Comment by Anjalikumari987** [comment]
Please give solution of this error if anyone knows.
 [InvalidArgumentException] Could not find a matching version of package magento/extension-b2b. Check the package spelling, your version constraint and that the package is
available in a stability which matches your minimum-stability (alpha).
