### ISSUE TITLE
Root / Sub Category does not add in Magento 2.0.17

### ISSUE THREAD

**Issue by shaikhmasud147** [magento/magento2#14717]
Root / Sub Category does not add in Magento 2.0.17.
Got the error below:

![screenshot from 2018-04-16 18-33-07](https://user-images.githubusercontent.com/21688214/38810621-f526eaec-41a4-11e8-9e11-2f44abf8a8fe.png)

**Comment by magento-engcom-team** [comment]
Hi @shaikhmasud147 
Unfortunately we do not track issues related only to Magento 2.0.x in this github issue tracker. Please try newer versions.
We are closing this ticket now, please reopen if issue persists.
