### ISSUE TITLE
Free Shipping Method issue in magento 2.1.7

### ISSUE THREAD

**Issue by dev2233** [magento/magento2#14722]
I enable free shipping method in magento 2.1.7 with minimum order amount of $100 but when i add some item in cart having price less then the minimum order amount of $100 then also free shipping method apply on it. this issue solved in magento 2.1.8 but i don't want to upgrade it from 2.1.7 to magento 2.1.8

### Preconditions
Magento version is 2.1.7

### Steps to reproduce
1. Enable Free Shipping Method by set minimum order amount ($100 etc.)
2. Add product to cart and cart total should be less than $100.

### Expected result
1.  Don't show free shipping method or hide free shipping method if order amount is less then the minimum order amount.

### Actual result
1. Still showing free shipping method if order amount is less then the minimum order amount($100)

**Comment by ghost** [comment]
@dev2233, thank you for your report.
Version 2.1.7 is deprecated. We cannot resolve your problem without updating your Magento instance.
