### ISSUE TITLE
when you sort orders etc by date the page hangs with a message ""something went wrong" and you cannot access orders even if you log out and then login

### ISSUE THREAD

**Issue by garimasingh-jasco** [magento/magento2#14723]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
Hi @garimasingh-jasco 
Looks like you have opened this ticket by mistake. Please open a new one and provide correct information if you would like to report an issue.
Thanks.
