### ISSUE TITLE
Add README section with recommended steps when pulling down latest code base.

### ISSUE THREAD

**Issue by mpchadwick** [magento/magento2#1472]
I've fetched the latest code twice since I originally forked Magento 2 and each time I merge in the latest from upstream/develop I'm unclear what steps I need to take to get the things running again.

This time I started out with rm -rf var (Magento 1.X style) but got errors. I then did composer update. Still got errors. Finally I ran php bin/magento setup:upgrade which I was only able to remember from looking through the bash_history from from the last time I merged in upstream. Things seem to be running OK for me now. 

I suggest adding a section to the README that outlines the steps you need to take each time you fetch the latest codebase to get things running. I'd be happy to contribute a PR for that, but on the other hand I'm still not clear on what those steps actually are...

**Comment by jamescowie** [comment]
Hi @mpchadwick Good point on the steps required, The steps I am taking may not be the "official" steps but currently its working for me without too much overhead.

I started the project by running `composer create-project --stability=beta --no-install magento/project-community-edition magento2` this created me a new folder called magento2 with a composer.json file in there relating to the latest beta.

When a new release is made I edit my composer.json and increment the version number 

```
10     "require": {
11         "magento/product-community-edition": "0.74.0-beta16"
12     },
```

So if beta 17 was out I would say `"0.74.0-beta17"` then I run `composer update` to ensure my code base has the latest updates from magento. 

Next it depends on what changes have been made to the code base. If there are schema updates I then run `./bin/magento setup:upgrade` being honest I have run this each time as a update inherently includes schema changes. 

Finally for good measure a clear of the cache and we have an updated system.

**Comment by mpchadwick** [comment]
In playing around with Magento 2 this afternoon I've also had to learn about these things the hard way

https://github.com/magento/magento2/issues/1277
https://github.com/magento/magento2/issues/1473

As mentioned above would be nice to have a section in the README about pulling in the latest code. For now I've done all of the following, although not sure what was and wasn't necessary...

rm -rf var/
composer dump-autoload
composer update
php bin/magento setup:upgrade
grunt refresh
rm -rf pub/static/_requirejs/adminhtml <-- Not sure if I need to rm -rf all of pub?

**Comment by Vinai** [comment]
My case is a little different from @jamescowie, I want to track the develop branch directly so I can easily create my own branches etc. After the initial clone of the magento/magento2 repository, I update with the following little shell script. I simply pass the version of the sample data I want installed as an argument, e.g. `../bin/pull-develop.sh 0.74.0-beta16`
Probably you can use that to adjust your process where needed.

```bash
#!/bin/bash

[ ! -d app ] && echo "Execute script from m2 root directory" && exit 2

# Revert me messing with project requirements, then pull in updates
git checkout composer.json 
git pull origin develop

rm -rf var/generation/*
rm -rf var/cache/*
# Make sure sample data is reinstalled and composer-installer hook is executed
[ -e app/code/Magento/SampleData ] && rm -r app/code/Magento/SampleData
[ -e vendor/magento/module-sample-data ] && rm -r vendor/magento/module-sample-data

# Set up composer, add sample data and update requirements.
composer config repositories.magento composer http://packages.magento.com
composer require magento/sample-data:$1 --dev --no-update
composer update

php -d"memory_limit=512M" -f bin/magento setup:install \
    --db-host=localhost \
    --db-name=magento_m2 \
    --db-user=m2 \
    --db-password=xxx \
    --backend-frontname=admin \
    --admin-user=admin \
    --admin-password=password123 \
    --admin-email=admin@example.com \
    --admin-firstname=Admin \
    --admin-lastname=Admin \
    --base-url=http://m2.dev/ \
    --language=en_US \
    --currency=USD \
    --use-rewrites=1 \
    --use-secure=0 \
    --use-secure-admin=0 \
    --cleanup-database \
    --use-sample-data

```

**Comment by xcomSteveJohnson** [comment]
Would you mind giving me feedback on this: http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-uninstall.html#instgde-install-magento-update

It's missing clearning the var directories but otherwise, would it work for you?

**Comment by daim2k5** [comment]
I think the documentation is now better thats we i close this ticket. If i missed something please feel free to reopen this issue.
