### ISSUE TITLE
Failure to designate order IDs when registering with an email already used.

### ISSUE THREAD

**Issue by kaalar** [magento/magento2#14729]
### Preconditions
1. Magento version: 2.1.4 (tested on multiple sites)
2. PHP Version: PHP 7.0.16-1~dotdeb+8.1 (cli) ( NTS )

### Steps to reproduce
1. Place an order as a guest user with example@email.com
2. Wait until the order is complete.
3. Make another order by registering with the same email as the previous one (example@email.com)

### Expected result

1. The last order is successfully completed and the new account is designated.

### Actual result

1. The orders exchange ids and an accounting error occurred.
Example:
![magento-2-issue-guest-to-custommer](https://user-images.githubusercontent.com/16648289/38854696-a1567518-4221-11e8-9465-d647f0aa70ed.PNG)

As you can see in the previous image, the order ID of January 29 is higher than the order id of April 10. Clearly when we check with our warehouse we realize that the id of the order has been exchanged between orders.

If you need any reference or log warn and I upload more data. And many thanks in advance.

**Comment by ghost** [comment]
@kaalar, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
