### ISSUE TITLE
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### ISSUE THREAD

**Issue by reillo** [magento/magento2#14725]
### Preconditions

1. Magento 2 community Edition (v2.2.2.0)
2. PHP 7.0
3. MySQL 5.6 

### Steps to reproduce

1. Login to admin
2. Redirected to Admin Account Details
3. message "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." keeps displaying
4. unable to navigate to any pages as it will redirect back to account page

### Expected result

1. Able to navigate to magento admin pages

### Actual result

1. [Screenshot, logs]

![screen shot 2018-04-17 at 10 52 16 am](https://user-images.githubusercontent.com/6128004/38846139-5cd65bea-422d-11e8-8ec9-df21b52d5401.jpg)

![screen shot 2018-04-17 at 10 52 05 am](https://user-images.githubusercontent.com/6128004/38846137-57afa504-422d-11e8-9f1d-11811b94d730.jpg)

![screen shot 2018-04-17 at 10 51 19 am](https://user-images.githubusercontent.com/6128004/38846115-368db140-422d-11e8-857b-45179b72e7cb.jpg)

![screen shot 2018-04-17 at 10 46 39 am](https://user-images.githubusercontent.com/6128004/38846104-26be7592-422d-11e8-8213-8e7681a70cbb.jpg)

I'm not sure how to replicate this issue as this is random. This is recurrent and we can temporarily fix from CLI (i.e clearing indexes and Caches).

**Comment by lano-vargas** [comment]
@reillo check this out https://github.com/magento/magento2/issues/10071

**Comment by ghost** [comment]
@reillo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by kazimnoorani8704** [comment]
**SOLVED**

Please try this things. Visit below link.
https://tutes.club/solved-magento-2-error-a-technical-problem-with-the-server-created-an-error-try-again-to-continue-what-you-were-doing-if-the-problem-persists-try-again-later/
