### ISSUE TITLE
Unable to Place Order using admin

### ISSUE THREAD

**Issue by visahardik** [magento/magento2#14728]
When I am trying to place order using admin panel its doesn't work
### Preconditions

1. Magento 2.2.0

### Steps to reproduce

1. Login to Admin panel
2. Sales > Order > Create Order > Select Customer 
3. Add product to cart
4. fill required information including payment and shipping method.
5. Click Submit Order

### Expected result

1. It should create new order.

### Actual result

1.  After clicking submit order nothing to see. no any console error.

After debugging i see in vendor/magento/module-sales/view/adminhtml/web/order/create/scripts.js line number 1170 `jQuery('#edit_form').triggerHandler('save');` not trigger

**Comment by ghost** [comment]
@visahardik, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
