### ISSUE TITLE
Get "unable to unserialize value" error on all queries

### ISSUE THREAD

**Issue by leonvisscher** [magento/magento2#14734]
### Preconditions
1. Clean Magento 2.3-develop branch install
2. Tried with PHP 7.1.16 and PHP 7.0.x
3. Nginx webserver on docker env.

### Steps to reproduce
1. Send any valid GraphQL query to http://magentostore/graphql
Headers:
'Content-Type': application/json
'Accept': application/json

### Expected result
1. Data as result

### Actual result

`{
    "errors": [
        {
            "debugMessage": "Unable to unserialize value.",
            "message": "Internal server error",
            "category": "internal",
            "trace": [
                {
                    "file": "/data/my-site/magento/app/code/Magento/GraphQl/Controller/GraphQl.php",
                    "line": 102,
                    "call": "Magento\\Framework\\Serialize\\Serializer\\Json::unserialize('{\n    products(search: \" \"){\n        total_count\n\t}\n}')"
                },
                {
                    "file": "/data/my-site/magento/lib/internal/Magento/Framework/Interception/Interceptor.php",
                    "line": 58,
                    "call": "Magento\\GraphQl\\Controller\\GraphQl::dispatch(instance of Magento\\Framework\\App\\Request\\Http)"
                },
                {
                    "file": "/data/my-site/magento/lib/internal/Magento/Framework/Interception/Interceptor.php",
                    "line": 138,
                    "call": "Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::___callParent('dispatch', array(1))"
                },
                {
                    "file": "/data/my-site/magento/lib/internal/Magento/Framework/Interception/Interceptor.php",
                    "line": 153,
                    "call": "Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::Magento\\Framework\\Interception\\{closure}(instance of Magento\\Framework\\App\\Request\\Http)"
                },
                {
                    "file": "/data/my-site/magento/generated/code/Magento/GraphQl/Controller/GraphQl/Interceptor.php",
                    "line": 26,
                    "call": "Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::___callPlugins('dispatch', array(1), array(1))"
                },
                {
                    "file": "/data/my-site/magento/lib/internal/Magento/Framework/App/Http.php",
                    "line": 135,
                    "call": "Magento\\GraphQl\\Controller\\GraphQl\\Interceptor::dispatch(instance of Magento\\Framework\\App\\Request\\Http)"
                },
                {
                    "file": "/data/my-site/magento/generated/code/Magento/Framework/App/Http/Interceptor.php",
                    "line": 24,
                    "call": "Magento\\Framework\\App\\Http::launch()"
                },
                {
                    "file": "/data/my-site/magento/lib/internal/Magento/Framework/App/Bootstrap.php",
                    "line": 256,
                    "call": "Magento\\Framework\\App\\Http\\Interceptor::launch()"
                },
                {
                    "file": "/data/my-site/magento/pub/index.php",
                    "line": 37,
                    "call": "Magento\\Framework\\App\\Bootstrap::run(instance of Magento\\Framework\\App\\Http\\Interceptor)"
                }
            ]
        }
    ]
}`

**Comment by jissereitsma** [comment]
@leon0v Could you comment on how you solved this?

**Comment by leonvisscher** [comment]
Hi @jissereitsma, apoligies for the late reply. The bug was in the way i composed the query. I don't have the originial faulty code anymore, but this is how I compose the query now in my JS and this works fine. This is the body I sent in my API fetch:


```
JSON.stringify({
                query: `
                {
                    products(filter: {url_key: {eq: "` + product + `"}}) {
                        items {
                            id
                            name
                            type_id
                            price {
                                regularPrice {
                                    amount {
                                        value
                                        currency
                                    }
                                }
                            }
                            image
                            description
                        }
                    }
                }
            `.trim()
```

**Comment by jissereitsma** [comment]
Cool. I also bumped into the same issue and also got it down to a faulty JSON code - I should have mentioned it from the start. But I found it nice to have us come to this openly in this issue, even though it is closed - so others might google it. Thanks so much for the update!

**Comment by kayintveen** [comment]
This issue also appears on React-Apollo preflight requests being empty and thus giving a unserialize error. Maybe not as related but found this topic researching my issue. 

In order to fix that I needed to patch for a quick fix.
/vendor/magento/module-graph-ql/Controller/GraphQl.php

```
$data = $this->jsonSerializer->unserialize($request->getContent());
````
to
```
$content = ($request->getContent() === '') ? '{}' : $request->getContent();
$data = $this->jsonSerializer->unserialize($content);
````
