### ISSUE TITLE
Admin Menu Hover Not Working

### ISSUE THREAD

**Issue by mpchadwick** [magento/magento2#1473]
Maybe this is just me, but when I hover of the menu items in the admin the sub menu does not appear.

**Comment by jamescowie** [comment]
Do you have any errors in the browser console ? Sounds like there is some JS error happening if you are using chrome look at the dev tools and console and if there are errors please post them here, Firefox has firebug if you are using that.

**Comment by mpchadwick** [comment]
Yeah, I'm in Chrome... d'oh how did I miss these 

![image](https://cloud.githubusercontent.com/assets/4132322/8635064/428b22a2-27e1-11e5-9281-e490b209101c.png)

**Comment by mpchadwick** [comment]
Deleting the previous comment (which was mistakenly showing the front end).

Nothing in the console in Chrome...

![image](https://cloud.githubusercontent.com/assets/4132322/8635074/b18c04dc-27e1-11e5-82b9-88eda78d5387.png)

**Comment by mpchadwick** [comment]
Nevermind. Ran grunt and working now.

**Comment by jrosell** [comment]
Same issue here. Finally i found it was caused by some extensions. For exemple I can reproduce the problem using https://chrome.google.com/webstore/detail/see/dkihcccbkkakkbpikjmpnbamkgbjfdcn
