### ISSUE TITLE
Filter by price range in layered navigation returns invalid result

### ISSUE THREAD

**Issue by pusachev** [magento/magento2#14733]
### Preconditions
**Platform**:  magento CE 2.2.0 
**Serverside**: php7.0, Mysql 5.7

### Steps to reproduce
1. Go to product list page
2. Filter product by price range like 20 - 100 (we need one product with price $100)
3. In result set we don't have product with price 100

### Expected result
1.  List of products includes items with price from $20 to $100

### Actual result
1.In result set we don't have product with price $100

I found strange code:
`['from' => $from, 'to' =>  empty($to) || $from == $to ? $to : $to - self::PRICE_DELTA]`
[see more](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/CatalogSearch/Model/Layer/Filter/Price.php#L140 )

Unfortunately code snippet's logic isn't clear for me. I don't understand why your developers take away price delta from '**$to**' price range. Is it required for other cases? Should I override this functionality to get proper results after filtration (see Expected results) or this will be fixed at next releases of Magento 2 CE.

**Comment by etessari** [comment]
Currently facing the same issue, I don't really understand the logic behind this snippet considering that the "from" parameter is not modified.

**Comment by ghost** [comment]
Hi @pusachev  the fix for this issue already has been avaible on 2.2-develop branch

**Comment by pusachev** [comment]
Hi, @engcom-backlog-nazar could you please provide me link to fix?
