### ISSUE TITLE
Add Products Manually Configuration Button Issue

### ISSUE THREAD

**Issue by wajahatbashir** [magento/magento2#14749]
Add Products Manually Button in configuration is not working properly.

I already create simple products in my admin catalog, but in during configurable product when i configure simple product then i'm facing trouble. Add Products Manually Button is not showing. when i create new simple product from configure > attribute and then select attribute and after finish this long process complete then (Add Products Manually Button) is showing and then i can select my own simple products. Please help me regarding about this issue. i'm wasting too much time due to this long process.

Please check below screenshot.

### Preconditions
I'm using Magento 2.1.2. and i have 1000+ configurable products in my store.

![screenshot_1](https://user-images.githubusercontent.com/11786908/38915768-f80e8de4-42f5-11e8-8628-d513313f821b.jpg)

**Comment by engcom-backlog-nickolas** [comment]
Hello @wajahatbashir, thank you for your report. GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
