### ISSUE TITLE
An error occurred on the server. Please try to place the order again.

### ISSUE THREAD

**Issue by jnrbo** [magento/magento2#14740]
I'm trying to test a module that I develop and I'm getting this error when i try to place the order. It isn't throwed by any of my code and I can not find out where is coming from.  Any tips?

- Magento 2.2.2
- Running on Docker
- Develop mod enabled

**payment-information** response:

`{"message":"An error occurred on the server. Please try to place the order again.","trace":"#0 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('85c243b2en01a48...', 'myemail@hotmail.c...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#1 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callParent('savePaymentInfo...', Array)\n#2 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}('85c243b2en01a48...', 'myemail@hotmail.c...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#3 \/var\/www\/html\/generated\/code\/Magento\/Checkout\/Model\/GuestPaymentInformationManagement\/Interceptor.php(26): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)\n#4 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder('85c243b2en01a48...', 'myemail@hotmail.c...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n#5 \/var\/www\/html\/app\/code\/Magento\/Webapi\/Controller\/Rest.php(330): call_user_func_array(Array, Array)\n#6 \/var\/www\/html\/app\/code\/Magento\/Webapi\/Controller\/Rest.php(239): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#7 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#9 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/html\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(39): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#11 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/html\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#13 \/var\/www\/html\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#14 \/var\/www\/html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#15 {main}"}`

**Comment by magento-engcom-team** [comment]
@jnrbo please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
