### ISSUE TITLE
unserialize issue when Adding Product list catalogue widget.

### ISSUE THREAD

**Issue by NerminPh** [magento/magento2#14745]
Tried to insert catalog products list widget to my website with the following condition:
Price is greater than 100 but it gives me the following error.

**Preconditions**
2.1.8 Community
PHP 7.0.28-1

**Steps to reproduce**
Go to content > pages > insert widget > catalog products list widget > add condition price more than 100 > save 

**Expected result**
In front page Product listing which has price more than 100

**Actual result**
Error filtering template: Notice: unserialize(): Error at offset 298 of 326 bytes in /.../public_html/vendor/magento/module-widget/Helper/Conditions.php on line 34

**Comment by NerminPh** [comment]
Any Advice

**Comment by ghost** [comment]
Hi @NerminPh  thank you for you report, We've acknowledged the issue and added to our backlog.
On 2.2-develop and 2.3-develop branch i have another error type like ->Error filtering template: Unknown condition operator; but only with operator "greater than".

**Comment by semajeg** [comment]
#mmuk2019

**Comment by magento-engcom-team** [comment]
@semajeg thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by semajeg** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @semajeg. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @semajeg, here is your [Magento instance](https://i-14745-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14745-2-3-develop.instances.magento-community.engineering/admin](https://i-14745-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by semajeg** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @semajeg. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @semajeg, here is your [Magento instance](https://i-14745-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-14745-2-2-develop.instances.magento-community.engineering/admin](https://i-14745-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by semajeg** [comment]
Hi,

I'm unable to reproduce this issue on the latest 2.2-develop & 2.3-develop branches. Here's the steps I took:

1. In admin,go to Content > Pages
2. Choose a page to edit (I took Homepage)
3. In the content wysiwyg, choose "insert widget"
4. Choose "Catalog Product List Widget"
5. In widget options > conditions, add a condition for the product attribute "price" with the condition being "greater than" and value being 100
6. Save the widget
7.Save the page
8. Access page on frontend (cache disable)

No error occurred and the widget displayed the expected products. This was done in a local instance of 2.3-develop and also the 2.3-develop and 2.2-develop instances provided by the bots above.

It looks like the class in question has gone under reconstruction in previous releases, so it's likely this was fixed as a by-product of that.

If anyone reproduces this issue in any other manner, then feel free to re-open with more information
