### ISSUE TITLE
zxcvbn.min.js is viewed in Security scan as a thread

### ISSUE THREAD

**Issue by Grohotun** [magento/magento2#14746]
**CE 2.2.3**

I've enabled password strenght on frontend & ran security scan.
And got this:

**Magento Compromise Injection**

_Your site is compromised with injected JavaScript. (226)
The malicious code signature(s) has been found in resources:
https://XXXXX.ru/static/version1523985877/frontend/YYYYY/ZZZZ/ru_RU/Magento_Customer/js/zxcvbn.min.js_

If I disable password strenght - security scan passes well.

Is it a bug or feature?

**Comment by MarioHdpz** [comment]
Exactly same thing is happening to us.

**Comment by Triloworld** [comment]
Pleas provide what Password Manager did show that error message?
It is used to catch all weak passwords (check frequency_lists array) and some other feedback as "Use a few words, avoid common phrases", "No need for symbols, digits, or uppercase letters"
https://github.com/dropbox/zxcvbn/

**Comment by DanielRuf** [comment]
Which tool did you use to do this audit? This clearly sounds like a false positive.

**Comment by Grohotun** [comment]
@DanielRuf I'm using Magento Security Scan tool in magento.com

**Comment by DanielRuf** [comment]
@Grohotun can you provide a link to this? Or do you mean magereport.com? magereport is not provided by Magento but a hosting provider which created this some years ago.

**Comment by pocallaghan** [comment]
The Magento Security Scanner is https://account.magento.com/scanner/index/dashboard/.

**Comment by DanielRuf** [comment]
Try to compare the file with the original from a fresh setup or the release zip using a diff tool.

Also, without seeing the content we can not say what the cause is.

**Comment by jbaig** [comment]
It is actually just the file from the Magento/Customer module.  Here is a sample after being bundled and minified.
[zxsample.txt](https://github.com/magento/magento2/files/1996235/zxsample.txt)

**Comment by DanielRuf** [comment]
Oh wow, most of the code is a list of publicly available passwords. I guess some of them trigger a security warning as the scan may look for specific words.

But this is just what I think.

**Comment by VladimirZaets** [comment]
Hi @Grohotun. The zxcvbn.js is the library for password strength estimation that developed by Dropbox.

Sometimes security scanners detect libraries that are also responsible for security as not-secure.
In the current case, the zxcvbn.js library is verified and don't introduce any security issues.

[zxcvbn Github repository](https://github.com/dropbox/zxcvbn/)
[Read more about zxcvbn](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/)
