### ISSUE TITLE
Why use fixed code for typeMapping in \Magento\Framework\EntityManager\TypeResolver ?

### ISSUE THREAD

**Issue by tudn9x** [magento/magento2#14748]
Hi I have a question, I found some fixed code in this file and I don't understand why you guy do it. Could you please explain it?
Does anyone know?

```    
private $typeMapping = [
        \Magento\SalesRule\Model\Rule::class => \Magento\SalesRule\Api\Data\RuleInterface::class,
        \Magento\SalesRule\Model\Rule\Interceptor::class => \Magento\SalesRule\Api\Data\RuleInterface::class,
        \Magento\SalesRule\Model\Rule\Proxy::class => \Magento\SalesRule\Api\Data\RuleInterface::class
    ];
```

**Comment by magento-engcom-team** [comment]
@htmyheart please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
