### ISSUE TITLE
Show taxvat on email/pdf order - M2

### ISSUE THREAD

**Issue by mageuser** [magento/magento2#14758]
Magento 2.2.3

How can i show taxvat on emails/pdf orders.

In Stores>Configuration>Customers>Customer Configuration>Address Templates>HTML AND PDF

Im trying it:

    {{depend taxvat}}VAT: {{var taxvat}}{{/depend}}

But VAT doesn't appear.

**Comment by magento-engcom-team** [comment]
@kauansoft please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
