### ISSUE TITLE
Configurable Product Dropdown not working as expected

### ISSUE THREAD

**Issue by melwinVincent** [magento/magento2#14762]
### Preconditions
Magento version 2.2.3
PHP 7.0.29

### Steps to reproduce
Added a custom attribute = color_2 and I selected dropdown for the input type
clicked add option and added 3 colors
Scope is set to Global and unique value to Yes

I added 3 different color images to the product and everything seems working fine. 
Now choose a color, I expected the selection automatically changes, instead what happens is that, the selected color gets added to the slider.

### Expected result
![image](https://user-images.githubusercontent.com/12426903/38978423-6888e2c2-43c8-11e8-8770-eaaccbdb3508.png)

### Actual result
But when I choose an option an additional image comes in the slider.

![image](https://user-images.githubusercontent.com/12426903/38978433-71723c12-43c8-11e8-8836-950624ac104b.png)

**Comment by melwinVincent** [comment]
Any update on this issue?
I have checked many updates, All of them have the same issue

**Comment by melwinVincent** [comment]
Dear Magento Team.
Please support.

**Comment by ghost** [comment]
@melwinVincent, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.  Seems like you have added all your images to parent product in addition to children. If you'd like to update it, please reopen the issue.
