### ISSUE TITLE
Error create customer in process create order from admin backend

### ISSUE THREAD

**Issue by Moulbac** [magento/magento2#14766]
### Preconditions

Magento 2.1.10

### Steps to reproduce

1. Login to admin panel
2. Sales > Order > Create Order > Create new customer

### Expected result

1. It should display custome create order

### Actual result

After clicking submit nothing happen and the error below is displayed in the error console javascript

1. [Console error]
TypeError: $(...) is null[En savoir plus]
scripts.js:118:13
setCustomerId
https://rec.democratikdesign.com/pub/static/version1523958685/adminhtml/Magento/backend/fr_FR/Magento_Sales/order/create/scripts.js:118:13
onclick
https://rec.democratikdesign.com/admin/sales/order_create/index/key/498c8ec77df02e727698d4e4d302b084c2d98043ca86a5235354a644e7f3886f/:1:1

**Comment by ghost** [comment]
@Moulbac, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
