### ISSUE TITLE
Braintree payment gateway Stored Card issue with multiwebsite when order created from Admin

### ISSUE THREAD

**Issue by yogeshkarodiya** [magento/magento2#14768]
### **Preconditions**
Checking with Magento2.2.0
This issue is only with Admin Order.
For multi-website setup. Configuration of Brain tree payment gateway on website level . 

### **Steps to reproduce**
Configure website 1 with payment action authorize and capture. 
Configure website2 with payment action Authorize only.

### **Expected result**
It should take value of payment action as per configuration 

**### Actual result**
Website level configuration working well when I am placing order with website1 for both new card as well as stored cards.

But when I am placing order into website2 with braintree stored its not getting payment action field value from website2 configuration instead taking from website1.

**Comment by ajaykumar03** [comment]
Facing same issue with multi- website  setup when order placed from admin for second website the payment action as configured on second website same payment action  should be considered.When order placed on second website from admin with saved/new card.

**Comment by YevSent** [comment]
@yogeshkarodiya, this is known issue and fixed in 2.2.2 Magento release (also, the fix released in 2.1.11). Please, see release notes for [2.2.2](http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.2CE.html#payment-methods) release.
