### ISSUE TITLE
Invalid Document

### ISSUE THREAD

**Issue by rafaelcentric** [magento/magento2#14776]
The site is down. Error 500
After running php bin/magento setup:upgrade this is my error

Invalid Document
Element 'preference', attribute 'type': [facet 'pattern'] The value 'community\e-ready-import\Adminhtml\Import\Download' is not accepted by the pattern '(\\?[a-zA-Z-ÿ][a-zA-Z0-9-ÿ]*)(\\[a-zA-Z-ÿ][a-zA-Z0-9-ÿ]*)*'.
Line: 175

Element 'preference', attribute 'type': 'community\e-ready-import\Adminhtml\Import\Download' is not a valid value of the atomic type 'phpClassName'.
Line: 175

I already delete the directory e-ready-import but I am still getting the same error.

### Preconditions

1. Magento 2.2.3
2. PHP 7
3. MySQL Ver 14.14 Distrib 5.7.21

### Steps to reproduce

1. I install this https://github.com/ibnab/tut-magento2-import
2. Run php bin/magento setup:upgrade

### Expected result

1. A new option will appear in Settings > Import Entity dropdown.

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
Hi @rafaelcentric 
Unfortunately we can not provide any assistance with issues caused by third-party customizations. Please report the issue directly to the extension vendor.

Thanks

**Comment by rafaelcentric** [comment]
That's what I thought too ^_^ thank you for responding though. I already did report the issue, I was just hoping that someone from  the magento community would have some suggestions as to why this is happening. Thanks.
