### ISSUE TITLE
Cart totals api error

### ISSUE THREAD

**Issue by igoreus-barmaleus** [magento/magento2#14773]
The issue on the cart page. API to extract cart totals fails. If quote address extension attribute isn't empty then it causes error.

### Preconditions

1. Magento 2.2.3
2. 

### Steps to reproduce

1. Add "Endurance Watch" product to the cart (the sample data should be installed).
2. Open Developer Tools
3. Check XHR requests under Network tab
4. You can see 500 error for the totals request

### Expected result

1. Valid JSON object

### Actual result

1. [Screenshot, logs]

Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\Quote\Model\Cart\Totals::setExtensionAttributes() 
must be an instance of Magento\Quote\Api\Data\TotalsExtensionInterface, instance of Magento\Quote\Api\Data\AddressExtension given, 
called in /var/www/magento22/vendor/magento/framework/Api/DataObjectHelper.php on line 125 and defined in 
/var/www/magento22/vendor/magento/module-quote/Model/Cart/Totals.php:592 Stack trace: #0 /var/www/magento22/vendor/magento/framework/Api/DataObjectHelper.php(125)…on)) 
#1 /var/www/magento22/vendor/magento/framework/Api/DataObjectHelper.php(85): Magento\Framework\Api\DataObjectHelper->_setDataValues(Object(Magento\Quote\Model\Cart\Totals), Array, 
'Magento\\Quote\\A...') #2 /var/www/magento22/vendor/magento/module-quote/Model/Cart/CartTotalRepository.php(103): 
Magento\Framework\Api\DataObjectHelper->populateWithArray(Object(Magento\Quote\Model\Cart\Totals), Array, 'Magento\\Quote\\A' in '/var/www/magento22/vendor/magento/module-quote/Model/Cart/Totals.php' 
on line 592

**Comment by igoreus-barmaleus** [comment]
One important note. This error can occur for other functions.  Magento\Framework\Api\DataObjectHelper::populateWithArray method copies extension attributes of incompatible types.

**Comment by ghost** [comment]
Hi @igoreus-barmaleus I cannot reproduce by yours scenario steps
![selection_033](https://user-images.githubusercontent.com/40756439/43077027-e8a5c310-8e8e-11e8-91fd-c75fce62fafb.png)
