### ISSUE TITLE
Magento2 : Fatal error when we set minimum order amount

### ISSUE THREAD

**Issue by divyakrishnashetty** [magento/magento2#14777]
### Preconditions

1. Magento ver. 2.1.7
2. Developer mode is enabled
3. In app/bootstrap.php i have enabled the error message display(Cause i was getting HTTP 500 error)

### Steps to reproduce
1. System>Configuration>Sales>Sales>Minimum Order Amount>Enable and specify the amount and description message
2. Login 
3. Try to add product to cart/update any item in your cart(which is greater than the minimum cart/order specified amount)
4. I will not be able to reach checkout cart page/Product will not get add to my cart due to an fatal error.

### Expected result
1. We should get error message in cart page which we specified in admin and product should get add/update for my cart.

### Actual result
We have recieved the Fatal error and product will not get add to cart/update my cart(due to fatal error).
Uncaught TypeError: Argument 1 passed to Magento\Framework\Exception\InputException::__construct() must be an instance of Magento\Framework\Phrase, string given .....
 the file vendor\magento\module-quote\Model\ShippingAddressManagement.php **line#121** which throw the exception message is causing the issue.
 **throw new InputException($this->getMinimumAmountErrorMessage()->getMessage());**

the code should be like as below to the expected result.
        **throw new InputException(_($this->getMinimumAmountErrorMessage()->getMessage()));**

**Comment by divyakrishnashetty** [comment]
I am able to reproduce the issue in Magento ver. 2.1.5 as well.

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me 2.2-develop verification instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento instance for you

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me 2.2-develop verification instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on 2.2-develop verification instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on 2.2-develop verification instance for you

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me 2.2-develop verification instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on 2.2-develop verification instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on 2.2-develop verification instance for you

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me 2.2-develop verification instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me 2.2-develop verification instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov, here is your [Magento instance](http://i-14777.engcom.dev.magento.com).
Admin access: [http://i-14777.engcom.dev.magento.com/admin](http://i-14777.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov, here is your [Magento instance](http://i-14777.engcom.dev.magento.com).
Admin access: [http://i-14777.engcom.dev.magento.com/admin](http://i-14777.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`Instance will be terminated in up to 3 hours.

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me 2.2-develop verification instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov, here is your [Magento instance](http://i-14777.engcom.dev.magento.com).
Admin access: [http://i-14777.engcom.dev.magento.com/admin](http://i-14777.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](http://i-14777-2-2-develop.engcom.dev.magento.com).
Admin access: [http://i-14777-2-2-develop.engcom.dev.magento.com/admin](http://i-14777-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](http://i-14777-2-3-develop.engcom.dev.magento.com).
Admin access: [http://i-14777-2-3-develop.engcom.dev.magento.com/admin](http://i-14777-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by neeta-wagento** [comment]
I have checked this issue in #dmcdindia
I have verified and its working fine in 2.2-develop branch

Please refer below screenshot 
![screenshot-2018-5-19 shopping cart 1](https://user-images.githubusercontent.com/33098216/40267447-01cd75f6-5b7a-11e8-99a9-7a5fbad6a3b2.png)

**Comment by magento-engcom-team** [comment]
@neeta-wagento thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by lewis-dan** [comment]
I am working on this at #dmcdindia

**Comment by lewis-dan** [comment]
I am using Magento Community 2.2 and did not get any Fatal error - 

![image](https://user-images.githubusercontent.com/34798405/40267583-003694a4-5b2d-11e8-9180-e9b661bb573f.png)

**Comment by magento-engcom-team** [comment]
Hi @divyakrishnashetty Looks like the issue is not reproducible anymore in 2.2
@lewis-dan @neeta-wagento Thank you for your research.
Closing ticket for now. Please reopen if you are still experiencing trouble.
