### ISSUE TITLE
Programmatically removing a product attribute does not clear attribute from all tables

### ISSUE THREAD

**Issue by NA-Dev** [magento/magento2#14792]
### Preconditions

- Magento CE 2.2.3
- Running locally on MacOS using Valet, php@7.1, Mysql 5.7.21

### Steps to reproduce

1. addAttribute programmatically in InstallData.php
2. check eav_attribute and catalog_eav_attribute tables to see new attributes created
3. removeAttribute programmatically in UpgradeData.php
4. check eav_attribute and catalog_eav_attribute tables

### Expected result

1. rows should be removed from both eav_attribute and catalog_eav_attribute tables

### Actual result

1. rows only removed from eav_attribute table

Note: This only occurs if I wrap the removeAttribute code in "$setup->startSetup()" and "$setup->endSetup()". If I remove those from the UpgradeData.php file, rows are removed from all tables as expected. Not sure if this is expected behavior or a bug? I cannot find any documentation about what startSetup does, and when I should/should not use it.

```
<?php

namespace Company\AddProductAttribute\Setup;

use Magento\Eav\Setup\EavSetup;
use Magento\Eav\Setup\EavSetupFactory;
use Magento\Framework\Setup\UpgradeDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class UpgradeData implements UpgradeDataInterface
{
    private $eavSetupFactory;

    public function __construct(EavSetupFactory $eavSetupFactory)
    {
        $this->eavSetupFactory = $eavSetupFactory;
    }

    public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $setup->startSetup();
        if (version_compare($context->getVersion(), '0.0.2', '<')) {

            $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
            $eavSetup->removeAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'sample_attribute_1'
            );
        }
        $setup->endSetup();
    }
}
```

**Comment by orlangur** [comment]
Hi @NA-Dev, you shouldn't use `startSetup`/`endSetup` normally, please check https://community.magento.com/t5/Magento-DevBlog/Mysterious-startSetup-and-endSetup-Methods/ba-p/68483 for more details.

> rows should be removed from both eav_attribute and catalog_eav_attribute tables

So, obviously if you disable foreign keys check cascading won't occur and related data will not be removed from `catalog_eav_attribute`.
