### ISSUE TITLE
not able to add items to cart (beta 16)

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1479]
a:4:{i:0;s:191:"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage2.quote_id_mask' doesn't exist, query was: SELECT `quote_id_mask`.* FROM `quote_id_mask` WHERE (`quote_id_mask`.`quote_id`='15')";i:1;s:13589:"#0 /var/www/html/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `quote_i...', Array)
#4 /var/www/html/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `quote_i...', Array)
#5 /var/www/html/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(488): Magento\Framework\DB\Adapter\Pdo\Mysql->_query(Object(Magento\Framework\DB\Select), Array)
#6 /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(756): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /var/www/html/magento2/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(363): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\Framework\DB\Select))
#8 /var/www/html/magento2/lib/internal/Magento/Framework/Model/AbstractModel.php(518): Magento\Framework\Model\Resource\Db\AbstractDb->load(Object(Magento\Quote\Model\QuoteIdMask), '15', 'quote_id')
#9 /var/www/html/magento2/app/code/Magento/Checkout/Model/Session.php(259): Magento\Framework\Model\AbstractModel->load('15', 'quote_id')
#10 /var/www/html/magento2/app/code/Magento/Checkout/Model/Cart.php(205): Magento\Checkout\Model\Session->getQuote()
#11 /var/www/html/magento2/var/generation/Magento/Checkout/Model/Cart/Interceptor.php(76): Magento\Checkout\Model\Cart->getQuote()
#12 /var/www/html/magento2/app/code/Magento/Multishipping/Controller/Checkout/Plugin.php(33): Magento\Checkout\Model\Cart\Interceptor->getQuote()
#13 [internal function]: Magento\Multishipping\Controller\Checkout\Plugin->beforeExecute(Object(Magento\Checkout\Controller\Cart\Add\Interceptor))
#14 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(122): call_user_func_array(Array, Array)
#15 /var/www/html/magento2/var/generation/Magento/Checkout/Controller/Cart/Add/Interceptor.php(26): Magento\Checkout\Controller\Cart\Add\Interceptor->___callPlugins('execute', Array, Array)
#16 /var/www/html/magento2/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Checkout\Controller\Cart\Add\Interceptor->execute()
#17 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#19 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Checkout\Controller\Cart\Add\Interceptor->___callParent('dispatch', Array)
#20 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'designLoader')
#21 /var/www/html/magento2/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#24 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'storeCheck')
#25 /var/www/html/magento2/app/code/Magento/Store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#28 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'contextPlugin')
#29 /var/www/html/magento2/app/code/Magento/Store/App/Action/Plugin/Context.php(82): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#32 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'catalog-app-act...')
#33 /var/www/html/magento2/app/code/Magento/Catalog/Model/App/Action/ContextPlugin.php(78): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#34 [internal function]: Magento\Catalog\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#36 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'customer-app-ac...')
#37 /var/www/html/magento2/app/code/Magento/Customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#38 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#40 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'weee-app-action...')
#41 /var/www/html/magento2/app/code/Magento/Weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#42 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#44 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'tax-app-action-...')
#45 /var/www/html/magento2/app/code/Magento/Tax/Model/App/Action/ContextPlugin.php(91): Magento\Checkout\Controller\Cart\Add\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#46 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#47 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#48 /var/www/html/magento2/var/generation/Magento/Checkout/Controller/Cart/Add/Interceptor.php(39): Magento\Checkout\Controller\Cart\Add\Interceptor->___callPlugins('dispatch', Array, Array)
#49 /var/www/html/magento2/lib/internal/Magento/Framework/App/FrontController.php(45): Magento\Checkout\Controller\Cart\Add\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#50 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#51 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#52 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#53 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#54 /var/www/html/magento2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#55 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#56 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#57 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#58 /var/www/html/magento2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#59 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#60 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#61 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#62 /var/www/html/magento2/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#63 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#64 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#65 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#66 /var/www/html/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#67 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#68 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#69 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#70 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#71 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#72 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#73 {main}";s:3:"url";s:152:"/magento2/index.php/checkout/cart/add/uenc/aHR0cDovLzE5Mi4xNjguMTAuMTM3L21hZ2VudG8yL2luZGV4LnBocC9hamF4LWZ1bGwtemlwLXN3ZWF0c2hpcnQuaHRtbA,,/product/244/";s:11:"script_name";s:19:"/magento2/index.php";}

**Comment by vpelipenko** [comment]
@sivajik34, do you use clear installation or upgraded from old versions? If it is not new installation, probably you need to run 'bin/magento setup:upgrade'.

**Comment by sivajik34** [comment]
hi @vpelipenko, upgraded from old version.i already run 'bin/magento setup:upgrade'.

**Comment by antonkril** [comment]
You will have to do reinstall. That table was added in install script, not upgrade script

**Comment by vpelipenko** [comment]
@sivajik34, did reinstall help you?

**Comment by sivajik34** [comment]
yes.installed merchant beta.working fine.thank you
