### ISSUE TITLE
Magento 22.3 : Does Not See Payment From Client

### ISSUE THREAD

**Issue by Sylvesterx1** [magento/magento2#14796]
### Preconditions

1.  Magento 2.2.3
**Payment module:**
- dotpay module: github.com/dotpay/magento2-payment 
- payu module: github.com/PayU/plugin_magento_2 

### Steps to reproduce

1. When customer selects the online payment option in advance and make a payment (I see payment in the payment system that has been made correctly) then magento can not see of this payment.

### Actual result

1. the order appears as "unpaid":
![image](https://user-images.githubusercontent.com/35328055/39083751-20e62b52-456a-11e8-8605-3a3072bede62.png)

**Comment by orlangur** [comment]
Hi @Sylvesterx1,

> dotpay module: github.com/dotpay/magento2-payment
> payu module: github.com/PayU/plugin_magento_2

Can you observe this error without third-party modules installed?

**Comment by Sylvesterx1** [comment]
Hi @orlangur 
I only use these two payment companies to accept payments in our store.

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.
