### ISSUE TITLE
Please specify product option(s) on adding a bundle product to cart

### ISSUE THREAD

**Issue by juroszed** [magento/magento2#14809]
### Preconditions

1. Magento 2.1.0 and 2.1.12
2. PHP 2.0.8
3. MySQL 5.6.31

From time to time I get an error message like "Please specify product option(s)" on adding a bundle product to cart. It looks like this error comes day by day only the first time trying to add the product to cart. I did not found a way to reproduce this error. But I get it on two different machines with different product portfolio (Magento sample Shop and a Live system).

![fehler](https://user-images.githubusercontent.com/33448166/39115676-b7c05a4c-46e2-11e8-8b0f-80ecda32a64a.png)

**Comment by ghost** [comment]
@juroszed, thank you for your report.
Unfortunately, we cannot investigate the issue without unambiguous steps to reproduce.
