### ISSUE TITLE
Magento2 Search catalog and order by product name not working

### ISSUE THREAD

**Issue by sun948534670** [magento/magento2#14802]
### Preconditions

1. Magento CLI version 2.1.13-dev

### Steps to reproduce

1. Search for some product
2. Select the product name sort criteria

### Expected result

1. Product list is sorted by product name

### Actual result

1. Product list is sorted by product name

Is there a 2.1 patch package for this question? If yes, can you provide a link? Thanks!

**Comment by sun948534670** [comment]
Has anyone encountered the same situation?

**Comment by ghost** [comment]
@sun948534670, thank you for your report.
This issue is already fixed in Magento 2.2

**Comment by simonrl** [comment]
@engcom-backlog-pb can you please link the commits for a backport?

**Comment by nishantbkw** [comment]
Can I get commits to fix this issue in my 2.1 version? upgrade version is not feasible for now. 
please link the commits?
