### ISSUE TITLE
Magento still assumes that modules reside in app/code directory

### ISSUE THREAD

**Issue by joshdifabio** [magento/magento2#1481]
There are a number of places in the Magento 2 code base which still assume that modules reside in the `app/code` directory. As a result, the module registrar which was implemented in #1206 isn't yet usable.

As people are beginning to experiment with the module registrar and are finding that it doesn't work as expected I think we should work out what needs fixing. I would like to use this ticket to maintain a list of the issues which still need to be resolved so that a number of us can tackle these issues together without duplicating effort.

- [ ] [`Magento\Framework\Module\Dir\Reader::getConfigurationFiles()`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/Dir/Reader.php#L75) and [`getComposerJsonFiles()`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/Dir/Reader.php#L93)
- [ ] [`Magento\Framework\Module\Dir\Reader::getActionFiles()`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/Dir/Reader.php#L111)
- [ ] Consider implications of [`Magento\Framework\Module\Dir\Reader::setModuleDir()`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/Dir/Reader.php#L152) and [`getModuleDir()`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/Dir/Reader.php#L136)
- [ ] Eliminating relative paths for XML schematic references (using URNs?) is another one. Relative paths a pain when the module moves.

This list is far from complete. I'll add more items to the list as time allows, and I invite others to contribute.

**Comment by alankent** [comment]
Eliminating relative paths for XML schematic references (using URNs?) is another one. Relative paths a pain when the module moves.

**Comment by joshdifabio** [comment]
> Eliminating relative paths for XML schematic references (using URNs?) is another one. Relative paths a pain when the module moves.

Great point, thanks.

**Comment by Vinai** [comment]
@alankent Do you really think that is such an issue?
I thought the dev would simply use the path depending on how she would want the extension to be installed. Example

Module residing in vendor/:
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
```

Module residing in app/code/:
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
```

So modules could not be moved from one location to another without changes. But from what I understood that isn't the goal of this PR. Right?

**Comment by joshdifabio** [comment]
@Vinai I think it's a big grey. What if `Magento\Framework` moves to `vendor`? Essentially, that could never be done without a BC break as doing so would (soft) break all existing module implementations due to the broken XSD references. And without allowing `Magento\Framework` to reside in `vendor`, it can't be used as a dependency without using Magento Composer installer. What do you think?

**Comment by Vinai** [comment]
True, I dind't think of that. If the location if the XSD changes it is a (soft) BC break. I don't think I can understand all the consequences. From my (limited) perspective I would like to see `Magento\Framework` move to `vendor/`.
On another note, maybe the XSD files could be moved into the separate packages containing only the interfaces which Alan spoke about somewhere.
Besides the origin moving, I don't see an issue for third parties using relative paths to the XSD files.
But to be honest, decoupling the physical location of the XSD from the URI is probably a good idea.

**Comment by davidalger** [comment]
@joshdifabio What would really help here is to create an example module which leverages the different aspects of the architecture. Write unit tests for it, and run them with the module in both locations. They should break in one location or the other if the framework isn't using the registry properly. 

Another (long-term) option would be to find the integration tests which verify the functionality of these core pieces of the framework and alter them so they apply to multiple module location scenarios.

**Comment by Vinai** [comment]
@joshdifabio I think in the "todo" list you missed the class name `Reader` after the namespace `Magento\Framework\Module\Dir`, right?

**Comment by joshdifabio** [comment]
> @joshdifabio I think in the "todo" list you missed the class name Reader after the namespace Magento\Framework\Module\Dir, right?

Good spot!

**Comment by Vinai** [comment]
The issue seems to be that `\Magento\Framework\Filesystem\Driver\File::getRelativePath()` is not fully implemented.

```php
    /**
     * Retrieves relative path
     *
     * @param string $basePath
     * @param string $path
     * @return string
     */
    public function getRelativePath($basePath, $path = null)
    {
        $path = $this->fixSeparator($path);
        if (strpos($path, $basePath) === 0 || $basePath == $path . '/') {
            $result = substr($path, strlen($basePath));
        } else {
            $result = $path;
        }
        return $result;
    }
```

If `$path` is not within the `$basePath` it simply returns the `$path` as it is, not the relative path.
This causes the later code to fail. From what I can see, once this is fixed all the methods you listed above should "just work". I'll have a go at it soon.

**Comment by joshdifabio** [comment]
I'm going to take a look at [`Framework\App\Router\ActionList`](https://github.com/magento/magento2/blob/master/lib/internal/Magento/Framework/App/Router/ActionList.php) and the related functionality some time soon unless someone is already looking at it? @vrann @Vinai 

At present, it is assumed that file paths relative to the module directory map directly to class names (e.g., `app\code\Magento\Catalog\Controller\Category\View.php` is assumed to contain `Magento\Catalog\Controller\Category\View`), but this will not work for modules located in vendor. If someone is already looking at this then please let me know.

**Comment by Flyingmana** [comment]
I think the `Eliminating relative paths for XML schematic references` can be delayed, maybe even ignored for the Beta phase.

For example PHPStorm allows aliasing relative paths, so the schema is found, even if the xml is placed on a complete different place.

**Comment by alankent** [comment]
"PHPStorm allows aliasing relative paths, so the schema is found, even if the xml is placed on a complete different place"... Cool!  However, won't it still be a problem for Magento to validate schemas? Or are the relative paths going to be fixed so that is not a problem?  If we can defer the work, fine with me!

**Comment by Flyingmana** [comment]
I had no problem with schema validation or missing schemas for the `module.xml`.
It worked as it would in `app/code/`.  
So I assume it does not resolve the schemas from the location of the xml. 

Just tested it, magento does not even use the path of the namespace location, it seems it just sets some internally on load of the files.

**Comment by Vinai** [comment]
Magento only uses the path returned by the `Magento\Framework\Config\SchemaLocatorInterface` for the config reader instance for validation.

**Comment by Flyingmana** [comment]
As I see all the Issues mentioned initially here are solved now
