### ISSUE TITLE
User login doesn't retain last quote currency selection

### ISSUE THREAD

**Issue by markshust** [magento/magento2#14826]
If a user logs in, the currency format of the previous session/cart is not applied to the user's session, but is overridden with the site's current currency selection.

### Preconditions
1. Magento version 2.2.3

### Steps to reproduce
1. Admin > Stores > Configuration > General > Currency Setup > Set allowed currencies to Euro and US Dollar. Set Base Currency and Default Display Currency to US Dollar.
2. Clear caches
3. On frontend, login to a customer account
4. Change currency format from USD to EUR
5. Logout
6. Change currency format to USD.
7. Login to user account.

### Expected result
1. The currency format of the user's last session (database value: `quote.quote_currency` of `EUR`) is applied.
2. The currency format is switched to EUR.

### Actual result
1. The currency format of the user's last session (database value: `quote.quote_currency` of `EUR`) is not applied on user login.
2. The currency format of the user's last session (database value: `quote.quote_currency` of `EUR`) is overridden by the current session's currency format (`USD`).

**Comment by ghost** [comment]
Hi @markoshust  this is duplicat for -> https://github.com/magento/magento2/issues/14825

**Comment by markshust** [comment]
@engcom-backlog-nazar i'm not entirely sure this is a dupe of #14825

#14825 - deals with how currency persists after user logout
#14826 - deals with how currency updates after user login

if this ticket is re-closed, i'd at least recommend adding the testing criteria above and expected/actual results to #14825 as this is a different situation to test against.

**Comment by ghost** [comment]
@markoshust  maybe just add expected/actual result to  ->_https://github.com/magento/magento2/issues/14825 , its very similar issue, and have one problem.

**Comment by ghost** [comment]
Hi @markoshust Added  testing criteria to https://github.com/magento/magento2/issues/14825 
in this case  are identical
