### ISSUE TITLE
Checkout not working on IE10 using Magento 2.2.3

### ISSUE THREAD

**Issue by brvm** [magento/magento2#14828]
### Preconditions

1. Magento 2.2.3
2. PHP 7.0
3. MySQL 5.5.3
4. Internet Explorer 10 on Windows 7, 8 and 8.1

### Steps to reproduce

1.  Clean installation of Magento 2.2.3
2. Deploy sample data / Add product manually
3. Go through checkout steps
4. Accept terms and conditions
5. Place order

### Expected result

1. The order should be placed succesfully

### Actual result

1. The terms and conditions can't be verified

![screen shot 2018-04-24 at 08 46 34](https://user-images.githubusercontent.com/19427937/39170490-0c6c02bc-479c-11e8-947f-95679ea385cf.png)

2. POST gets error 400

![screen shot 2018-04-24 at 08 48 30](https://user-images.githubusercontent.com/19427937/39170564-505db9a2-479c-11e8-8547-986bb68f3cda.png)

3. The response body:

`{"cartId":"10","billingAddress":{"customerAddressId":"1","countryId":"EN","regionCode":null,"region":null,"customerId":"1","street":["Street 11"],"telephone":"1112345678","postcode":"1111 XX","city":"Somewhere","firstname":"John","lastname":"Doe","extensionAttributes":{"checkoutFields":{}},"saveInAddressBook":null},"paymentMethod":{"method":"checkmo","po_number":null,"additional_data":null}}`

**Comment by magento-engcom-team** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team, here is your [Magento instance](http://i-14828-2-2-develop.engcom.dev.magento.com).
Admin access: [http://i-14828-2-2-develop.engcom.dev.magento.com/admin](http://i-14828-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bramulous** [comment]
@magento-engcom-team FYI, I was able to reproduce the issue on your instance.

**Comment by magento-engcom-team** [comment]
@bramulous Looks like it is really IE10 specific, as we attempted with IE11 and it seemed to work

**Comment by brvm** [comment]
@magento-engcom-team Yes, it works in IE11. But unfortunately not in IE10. I used your instance and it too did not work. Is this due to IE10 itself or a bug within Magento 2.2.3 not working properly with IE10?

**Comment by brvm** [comment]
Ah, I see here that Magento 2 does not officially support IE10: http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements_browsers.html
By any chance, did you encounter what the cause of the problem was?

**Comment by magento-engcom-team** [comment]
@bramulous Unfortunately no clue what causes the problem.

**Comment by brvm** [comment]
@magento-engcom-team okay, thank you for the information and effort!

**Comment by magento-engcom-team** [comment]
@bramulous Looks like we can close this issue now. 
Thank you for collaboration.

**Comment by lewis-chilton** [comment]
ticket #14830 (Chrome NOT IE) was merged into this one. I'm replicating the issue now in Chrome.
Can you re-open this bug?
