### ISSUE TITLE
While adding Bundle items for bundle product, doesn't show all products for selection

### ISSUE THREAD

**Issue by NiteshKuyate** [magento/magento2#14827]
### Preconditions

1. Magento Community 2.1.5

### Steps to reproduce

1. Create bundle product using magento admin.
2. Fill required product information
3. Under Bundle items section: Add Option > Add Products to Option

### Expected result

1. Show all simple and enabled products for selection. 

### Actual result

1. Not showing all simple and enabled products for selection

> NOTE: Tried for both options required Yes and required No

Products count: 5130
Simple Products: 5129
Visibility(Catalog, Search): 5129
Status(Enabled): 5129

When trying to add options for bundle product, 4135 products showing.

**Comment by NiteshKuyate** [comment]
@magento-engcom-team any updates?

**Comment by NiteshKuyate** [comment]
any updates?

**Comment by ghost** [comment]
Hi @NiteshKuyate I cannot reproduce by your scenario steps. In clean magento install
![frame-03d](https://user-images.githubusercontent.com/40756439/43136158-7653b778-8f50-11e8-985f-c5bfef0304ec.gif)
