### ISSUE TITLE
Magento 2.2.2 truncanting IPV6 for orders

### ISSUE THREAD

**Issue by luismaldonado91** [magento/magento2#14823]
### Preconditions

1.  Magento 2.2.2
2.  PHP 7.0.13

### Steps to reproduce

1.  Watch for orders placed from IPv6 clients
2. If you match the IPv6 from the order to a IPv6 validator, you right away noticed that it's truncated to 32 chars, rendering the IP invalid for the order.

### Expected result

1.  Correct IPv6 IP format

### Actual result

1.  32 char truncated IPv6

As for now i've modified the column remote_ip for sales_order and quote tables from VARCHAR(32) to VARCHAR(64).  Also i've modified x_forwarded_for from VARCHAR(32) to VARCHAR(64) from table sales_order

I think it's imperative a db schema change for this paramter. For me it's causing that the native signifyd extension dont' post orders to console because of the IPv6 truncation.

**Comment by magento-engcom-team** [comment]
Hi @luismaldonado91 
This report seems to duplicate https://github.com/magento/magento2/issues/10395
Please continue tracking under that reference.

Thank you for collaboration

**Comment by luismaldonado91** [comment]
Thanks for the clarification. I think this is kind of critical and it' has been of your knowledge since August 2017. At least for fraud protection with signifyd is critical.
