### ISSUE TITLE
Shipping price precision

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#14838]
Can not have a gross shipping price of 45.00 EUR when entered shipping price as net price.

### Preconditions

1. Magento 2.2.3
2. PHP 7.1
3. 19% tax on shipping

### Steps to reproduce

1. Set up a shipping table rate of net 37.815126050420168 EUR (45gross / 1,19tax)
2. Set config: Sales > Tax > Calculation Settings > Shipping Prices > Excluding Tax
3. Trigger the shipping calculation at the cart page

### Expected result

1.  Should see the 45 EUR shipping gross price in the totals block on the cart page

### Actual result

1. Shipping price is 45.01 EUR

It's just impossible to enter any net value at the table rate to achieve a gross shipping price of 45 EUR

**Comment by ghost** [comment]
Hi @Detzler  this is duplicate for this -> https://github.com/magento/magento2/issues/15852
