### ISSUE TITLE
Related products, crossell and upsell are partially displayed  in backend .

### ISSUE THREAD

**Issue by andreicurduman** [magento/magento2#14832]
Preconditions
Magento 2.2.3
PHP 7.0.20

Steps to reproduce
Upgrade from Magento 2.1.8 to Magento 2.2.3
Flush the cache storage and reindexing .
Check the frontend and backend

Expected result
Related, crossell and upsell products should come in the frontend of product page and backend of product edit page

Actual result
The update related products are showing in the frontend .But only a part of related, crossell and upsell products are showing in the backend.

**Comment by robbertstevens** [comment]
The reason for this is probably you used the same sorting value for multiple products. 

When you have the following
```
product -> sort order
one -> 1
two -> 1
three -> 1
four -> 2
```

it wil only show one, two and four. See issue 13720

**Comment by ghost** [comment]
Hi @andreicurduman this is duplicate for this ->https://github.com/magento/magento2/issues/13720 
 If you'd like to update it, please reopen the issue.
