### ISSUE TITLE
Terms and Conditions - Checkout validation broken

### ISSUE THREAD

**Issue by jamie-selesti** [magento/magento2#14830]
I have enabled terms & conditions on the checkout and even when the customer checks the checkbox an validation error comes back and states "Please agree to all the terms and conditions before placing the order."

### Preconditions

1. Magneto 2.2.3
2. PHP 7.1
3. Chrome 66.0.3359.117

### Steps to reproduce

1. Enable terms & conditions
2. Add a terms & condition
3. Try to place an order

### Expected result

1. Allow the user to place the order

### Actual result

1. Validation error states ""Please agree to all the terms and conditions before placing the order." as per the screenshot even though the checkbox is checked
![fullscreen_24_04_2018__09_53](https://user-images.githubusercontent.com/1398649/39176743-711b77f2-47a5-11e8-80db-ce23490b81b1.png)

**Comment by magento-engcom-team** [comment]
Hi @jamie-selesti 
This seems to be the same issue as reported in https://github.com/magento/magento2/issues/14828
Please continue tracking under that reference.

Thanks

**Comment by jamie-selesti** [comment]
Could we reopen this as, the connected issue you refer to is relating to IE10 I am using the latest version of chrome 66.0.3359.117 @magento-engcom-team
