### ISSUE TITLE
php include used to render sub templates. Why not XML layout here?

### ISSUE THREAD

**Issue by chris-pook** [magento/magento2#14831]
It is not clear why the XML layout is not being used here. Using PHP include like this breaks extensibility.

https://github.com/magento/magento2/blob/199272b233fb1f2a927e87cd6869011993f05a73/app/code/Magento/Catalog/view/frontend/templates/product/list/toolbar.phtml#L20-L32

**Comment by magento-engcom-team** [comment]
@chris-pook please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
