### ISSUE TITLE
admin external extjs.com requests

### ISSUE THREAD

**Issue by nyov** [magento/magento2#1483]
The tree structures (category views) depend on external extjs.com ressources,

I don't really like advertising the shop admin location to any external parties (by referrer),
or depending on external ressources for a working admin in general.

Would be nice if this could be made to use local/offline ressources.

![extjsdependency](https://cloud.githubusercontent.com/assets/438293/8676320/4e9e4a98-2a38-11e5-998c-f079baa0a174.jpg)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-40308

**Comment by guz-anton** [comment]
Hi nyov,
We have already delivered fix. You can check it and close issue in case it's all right.

**Comment by nyov** [comment]
Thanks!
