### ISSUE TITLE
Invoice pdf > incorrect net/gross shipping price in shipping-charges-text

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#14848]
Inside the shipping-charges-text the shipping price does not respect the tax display type.

shipping-charges-text: 
https://github.com/magento/magento2/blob/2.2.3/app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php#L561

### Preconditions

1. Magento 2.2.3
2. PHP7.1

### Steps to reproduce

1. Set up a shipping table rate of 6.50
2. Set config: Sales > Tax > Calculation Settings > Shipping Prices > Excluding Tax
3. Set config: Sales > Tax > Calculation Settings > Display Shipping Prices/Amount > Including Tax
4. Get sure you have a tax enabled for shipping (in my case it's 19%)

### Expected result

1. The shipping-charges-text should be "Total Shipping Charges 6.50".

### Actual result

1. The shipping-charges-text should be "Total Shipping Charges 5.84". The tax should be included in the price as configured at Sales > Tax > Calculation Settings.

**Comment by engcom-backlog-nazar** [comment]
Hi @Detzler thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
Hi @Detzler  this is dublicate for https://github.com/magento/magento2/issues/15852
