### ISSUE TITLE
cannot add product in cart with registered users

### ISSUE THREAD

**Issue by nikidexa** [magento/magento2#14852]
I'm trying to add some product to cart like registered user, but cannot. If Im trying like a guest there are no problems. The issue is only with registered users.
I tried to change theme, but I have the same issue...
Some one can help me? thanks

**Preconditions**
magento 2.2.2 

 **Steps to reproduce**
With registered users try to add product in cart, but cannot

**Expected result**
Add any product to cart without and procede with normal checkout

**Actual result**
Cannot add product in cart with registered users, but with guest I can.
message: "At the moment is not possible add product in cart"

**Comment by magento-engcom-team** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team, here is your [Magento instance](http://i-14852-2-2-3.engcom.dev.magento.com).
Admin access: [http://i-14852-2-2-3.engcom.dev.magento.com/admin](http://i-14852-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team, here is your [Magento instance](https://i-14852-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-14852-2-2-3.engcom.dev.magento.com/admin](https://i-14852-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @nikidexa Thank you for reporting.
We have attempted to reproduce the issue you have described on a clean installation. "Add to Cart" for registered customer seems to be working fine. Please check your customizations and extensions.

---

<img width="500" alt="screen shot 2018-04-26 at 10 54 49" src="https://user-images.githubusercontent.com/31669971/39293190-e52aec3a-4940-11e8-8e7f-45a593f16ad6.png">

---

<img width="500" alt="screen shot 2018-04-26 at 10 54 34" src="https://user-images.githubusercontent.com/31669971/39293189-e510442a-4940-11e8-9a4b-88ff26205492.png">

**Comment by nikidexa** [comment]
Thanks for the answers....
from the log files:
_Exception message: Validate class not found from basename 'Magento\Framework\Validator\EmailAddress'_ 

Any suggest?

**Comment by magento-engcom-team** [comment]
@nikidexa Please provide clear steps to reproduce the issue

**Comment by nikidexa** [comment]
Solved: I found this ...
![soluzione_errore_aggiunta_prodotti_carrello_utenti_registrati](https://user-images.githubusercontent.com/38526353/39566680-b01cf354-4ebc-11e8-89a4-a409ea072be1.png)
