### ISSUE TITLE
Shipping Progress Dates are wrong for Tracking Popup

### ISSUE THREAD

**Issue by jcolas15** [magento/magento2#14856]
We are experiencing an issue with the Tracking popup.  With our carrier being fedex and tracking a shipment and looking at the progress details, the dates of each progress step are off by 1 day.  It seems as though the problem has to do with Magento trying to convert the UTC Date without a time and converting that to the locale date time.  
`vendor/magento/module-shipping/Block/Tracking/Popup.php:79`
`formatDeliveryDate creates a date object in UTC instead of the current locale`

### Preconditions

1.  Magento 2.2.3 CE
2. 

### Steps to reproduce

1. Place an order and fulfill the order with a valid tracking number with tracking information (we used fedex)
2. Go to customer/account and Click My Orders.  
3.  Track the shipment of the order with the shipment details.

### Expected result

1. The Dates should be correct in the shipping progress section

### Actual result

1. The Dates are off by 1 day.  The dates in Magento are being calculated in UTC before converting it to the correct locale when the date object should be created in the current locale in `vendor/magento/module-shipping/Block/Tracking/Popup.php:82`
2. 
<img width="781" alt="screen shot 2018-04-25 at 4 06 25 pm" src="https://user-images.githubusercontent.com/11393085/39272978-22b15b82-48a3-11e8-81c1-ecb00bb37bdb.png">
3.
<img width="781" alt="screen shot 2018-04-25 at 4 06 25 pm" src="https://user-images.githubusercontent.com/11393085/39273021-464b96c0-48a3-11e8-9ec6-b7fb3a885362.png">

**Comment by bzellers** [comment]
I'm seeing this bug in EE 2.1.12 too.

**Comment by trucatchtraps** [comment]
I am experiencing this as well on Magento 2.2.3

**Comment by jeffmowens** [comment]
Confirmed bug on 2.2.3.  Previous to 2.2.3, it was over 24 hours, but with 2.2.3 it's now exactly 24 hours off.

Also, the Delivered On declaration is present and showing a date in the future (when the package was not yet delivered).

**Comment by AdminLinenStore** [comment]
experience the same issue on 2.2.1

**Comment by jeffmowens** [comment]
Magento issued us a patch to fix this problem.  We've moved on to 2.2.5

**Comment by trucatchtraps** [comment]
So instead of fixing the issue, they just removed all the progress updates within the popup? Attached are screenshots of the same Order from Magento 2.2.3 and 2.2.5. 
Magento 2.2.3
![m2 2 3](https://user-images.githubusercontent.com/16922585/44548681-09aabb00-a6dc-11e8-9add-45a36c13e0d3.png)
Magento 2.2.5
![m2 2 5](https://user-images.githubusercontent.com/16922585/44548682-0a435180-a6dc-11e8-97d8-7e8b6067b5b7.png)

**Comment by ghost** [comment]
Hi @jcolas15 the fix for this issue has already on 2.2-develop branch.

**Comment by sarfarazbheda** [comment]
> Hi @jcolas15 the fix for this issue has already on 2.2-develop branch.

Can you please add reference commit id here?

We are still facing this issue on Magento 2.2.5 EE.

Thanks

**Comment by sarfarazbheda** [comment]
Any updates?

**Comment by ray-moncada** [comment]
We are using CE 2.2.5 and are experiencing this issue. Can anyone point to the correction?
