### ISSUE TITLE
Issue with updating pelago/emogrifier to v2.0.0

### ISSUE THREAD

**Issue by malikt** [magento/magento2#14859]
I was facing the well known email css issue, https://github.com/magento/magento2/issues/4737
The fix was to update the pelago/emogrifier to 2.0.0, when i placed the following line in composer.json
"pelago/emogrifier": "2.0.0"
and ran the composer update command, it failed with an error.

### Preconditions

1. Magento v2.1.9
2. PHP 7.0.13
3. MySQL 5.6.34
4. nginx

### Steps to reproduce

1. edit the composer.json
2. place the "pelago/emogrifier": "2.0.0" under "require-dev"
3. run the composer update command

### Expected result

1. It should update the pelago/emogrifier version to 2.0.0
2. The css exception on emails should go off.
### Actual result

It returns following exception:

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - magento/product-community-edition 2.1.9 requires pelago/emogrifier 0.1.1 -> satisfiable by pelago/emogrifier[v0.1.1] but these conflict with your requirements or minimum-stability.
    - magento/product-community-edition 2.1.9 requires pelago/emogrifier 0.1.1 -> satisfiable by pelago/emogrifier[v0.1.1] but these conflict with your requirements or minimum-stability.
    - Installation request for magento/product-community-edition 2.1.9 -> satisfiable by magento/product-community-edition[2.1.9].
![image](https://user-images.githubusercontent.com/24920883/39286472-8df19b8e-4937-11e8-96f0-b685a714bf68.png)

**Comment by malikt** [comment]
before i do something silly and break the site, want to confirm if its ok to edit the composer.lock and update the version of emogrifier in it too? and will it fix the issue?

**Comment by Karlasa** [comment]
@malikt i would suggest to edit LESS file for that specific issue. 
from file: Magento_Sales\web\css\source\_email.less 
remove all ">" symbols and you should be good to go :)

**Comment by magento-engcom-team** [comment]
Hi @malikt Thank you for reporting.
Magento 2.2 already depends on `pelago/emogrifier` 2.0.0. This change was not ported to Magento 2.1 release.
> if its ok to edit the composer.lock

`composer.lock` is not intended to be edited manually.
Closing, as issue is fixed in 2.2

**Comment by malikt** [comment]
hi Karlasa,
vendor/magent/module-sales/view/frontend/web/ has so such file.

**Comment by malikt** [comment]
@magento-engcom-team  so what is the fix for Mage 2.1.x?

**Comment by mattkrupnik** [comment]
@malikt just add this to the composer require `"pelago/emogrifier": "2.0.0 as 1.2.0"` then run composer update `pelago/emogifier` and it solved problem.

https://github.com/magento/magento2/issues/4737#issuecomment-390585673

**Comment by malikt** [comment]
sure, will give it a try.
The ticket should be closed because i wont be complaining even if the mentioned fix failed,  as i had  rewritten the email's related css by removing all the conflicting attributes and its working already.
Thanks anyways :)
