### ISSUE TITLE
Unable to follow the standard block class recommendation

### ISSUE THREAD

**Issue by zennco** [magento/magento2#14858]
The classes **\Magento\Backend\Block\Template** and **\Magento\Framework\View\Element\Template** documentation recommends against extending. 
Avoid extending this class.
 * If you need custom presentation logic in your blocks, use this class as block, and declare
 * custom view models in block arguments in layout handle file.

Then an example follows :
` <block name="my.block" class="Magento\Backend\Block\Template" template="My_Module::template.phtml" >
    <arguments>
        <argument name="viewModel" xsi:type="object">My\Module\ViewModel\Custom</argument
    </arguments>
</block>`

Also, followed hints at https://community.magento.com/t5/Magento-2-x-Programming/Usage-of-viewModel-in-Blocks/m-p/71042#M2495

However, the argument "viewModel"  is not retrieved in phtml when calling `$block->getViewModel()`.
Managed to get the argument "viewModel" by using `$block->getData('viewModel')`.
Yet,  `$block->getViewModel()` works only if the argument name is changed to "view_model", like in Magento2 devdocs at http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.html 
>  for getting the value of `<argument name="some_string">` the method name is `getSomeString()`

### Preconditions

1. Magento 2.2.3
2. PHP 7.1
3. MySQL 5.7

### Steps to reproduce

1. Add a new block in layout file 
`<block name="content.filter" class="Magento\Framework\View\Element\Template" template="Namespace_Blog::content_filter.phtml">
                <arguments>
                    <argument name="viewModel" xsi:type="object">Namespace\Blog\ViewModel\ContentFilter</argument>
                </arguments>
            </block>`
2. Create a the "Namespace\Blog\ViewModel\ContentFilter" class
3. Create the phtml file "content_filter.phtml"
4. In phtml the argument "viewModel' using `$block->getViewModel()`

### Expected result

Block argument should be retrieved

### Actual result

NULL argument

**Comment by phoenix128** [comment]
You should name it `view_model` in your layout XML file and call it with `getViewModel` from your template.
There was probably a typo in the first link you provided.

```
...
<block name="my-block" template="My_Module::test.phtml">
  <arguments>
    <argument name="view_model" xsi:type="object">My\Vendor\ViewModel\Test</argument>
  </arguments>
</block>
...
```

And in `test.phtml`:
```
$viewModel = $block->getViewModel();
```


But keep in mind that `view_model` is just a conventional name for a block argument. You can potentially use any name you like there or inject multiple view models if needed.

The following example is also working:

```
...
<block name="my-block" template="My_Module::test.phtml">
  <arguments>
    <argument name="some_name" xsi:type="object">My\Vendor\ViewModel\Test</argument>
  </arguments>
</block>
...
```

And in `test.phtml`:
```
$viewModel = $block->getSomeName();
```

**NOTE:** Of course, using a conventional name `view_model` is recommended to make it more readable to other developers.

**Comment by phoenix128** [comment]
Closed due to inactivity.
