### ISSUE TITLE
Image Not Display on Cart page

### ISSUE THREAD

**Issue by nit-it** [magento/magento2#14865]
We Added configurable product in cart , But image not displayed if Parent product has no Images. 

### Preconditions
1. Magento 2.2.3
2. Create Configurable product.

### Steps to reproduce
1. Create Configurable product.
2. Add Images for all child products 
3. Do not Add images for parent products.
4. Add that product in cart page.

### Expected result
1. Display images of Child product  on cart page. if child product has no images then display images of parent product .

### Actual result

![shopping cart](https://user-images.githubusercontent.com/34954682/39300104-39838bd0-4968-11e8-8804-33de002bd716.png)

**Comment by phoenix128** [comment]
I was not able to reproduce this in 2.2.x .
What is your setting for `Stores -> Configuration -> Sales -> Checkout -> Shopping Cart -> Configurable Product Image` ?

**Comment by nit-it** [comment]
I change "Configurable Product Image" , Now it is working.  Thank you So much..
