### ISSUE TITLE
Custom Customer attribute with input type date is not saved in database Magento2.2.2

### ISSUE THREAD

**Issue by syedsaleem086** [magento/magento2#14879]
### Preconditions
1. Magento2.2.2
2. PHP 7.0.29

### Steps to reproduce
1. Create 3 different customer custom attribute with input type date, int, varchar
2. Go to the backend and try to save some data to created attribute

### Expected result
All attributes should save

### Actual result
 Attributes which have input type int, varchar will get saved. But attribute which has input type date won't save and no error message even

**Comment by magento-engcom-team** [comment]
Hi @syedsaleem086 Thank you for reporting.
Please clarify the first point: 
> Create 3 different customer custom attribute with input type date, int, varchar

How did you create the customer attributes in question?

**Comment by syedsaleem086** [comment]
HI @magento-engcom-team 

Here is the code snippet


        $customerSetup->addAttribute(Customer::ENTITY, 'abn_acn', [
            'label' => 'ABN or ACN (Australia Only)',
            'input' => null,
            'required' => false,
            'sort_order' => 120,
            'visible' => false,
            'user_defined' => true,
            'position' => 1000,
            'system' => false,
            'is_used_in_grid' => true,
            'type' => 'varchar',
        ]);

        $attribute = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'abn_acn')
            ->addData([
                'attribute_set_id' => $attributeSetId,
                'attribute_group_id' => $attributeGroupId,
                'used_in_forms' => ['adminhtml_customer', 'customer_account_create'],
            ]);

        $attribute->save();

        $customerSetup->addAttribute(Customer::ENTITY, 'commenced_business', [
            'type' => 'static',
            'label' => 'Date Commenced Business',
            'input' => 'date',
            'frontend' => \Magento\Eav\Model\Entity\Attribute\Frontend\Datetime::class,
            'backend' => \Magento\Eav\Model\Entity\Attribute\Backend\Datetime::class,
            'required' => false,
            'sort_order' => 120,
            'visible' => false,
            'system' => false,
            'input_filter' => 'date',
            'validate_rules' => '{"input_validation":"date"}',
            'position' => 1000,
        ]);

        $attribute = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'commenced_business')
            ->addData([
                'attribute_set_id' => $attributeSetId,
                'attribute_group_id' => $attributeGroupId,
                'used_in_forms' => ['adminhtml_customer', 'customer_account_create'],
            ]);

        $attribute->save();

        $customerSetup->addAttribute(Customer::ENTITY, 'payment_terms', [
            'label' => 'Payment Terms',
            'input' => null,
            'required' => false,
            'sort_order' => 120,
            'visible' => false,
            'user_defined' => true,
            'position' => 1000,
            'system' => false,
            'is_used_in_grid' => true,
            'type' => 'int',
        ]);

        $attribute = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'payment_terms')
            ->addData([
                'attribute_set_id' => $attributeSetId,
                'attribute_group_id' => $attributeGroupId,
                'used_in_forms' => ['adminhtml_customer', 'customer_account_create'],
            ]);

        $attribute->save();

abn_acn -> Working
commenced_business -> Not working 
payment_terms -> Working

**Comment by syedsaleem086** [comment]
Hi @magento-engcom-team 
Please let me know above detail is enough or not. Please respond

**Comment by syedsaleem086** [comment]
Hi @magento-engcom-team 
Any update?

**Comment by kkrieger85** [comment]
@syedsaleem086 I tried to add your example attributes via install script. In my 2.2.6-dev vanilla magento abn_acn and payment_terms was visible in backend. (Customer-Tab, add new customer).

commenced_business was not shown at all - but was added to database.

Is commenced_business shown in your backend?

**Comment by kkrieger85** [comment]
To reproduce you can make this field visible in backend with extending `Magento/Customer/view/base/ui_component/customer_form.xml` You could use this snippet 

```
        <field name="commenced_business" formElement="date">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="source" xsi:type="string">customer</item>
                </item>
            </argument>
            <settings>
                <validation>
                    <rule name="validate-date" xsi:type="boolean">true</rule>
                </validation>
                <dataType>text</dataType>
                <visible>true</visible>
            </settings>
        </field>
```

I can now reproduce this behavior in magento 2.2.6-dev

**Comment by kkrieger85** [comment]
You could use following files to reproduce this issue: https://gist.github.com/kkrieger85/a00bb91ef9171d06c04c49ef46e779d8

**Comment by syedsaleem086** [comment]
Hi, @kkrieger85 
Is commenced_business shown in your backend?
Yes, It is showing.

**Comment by kkrieger85** [comment]
@syedsaleem086 but it wasn't shown with default. You had to update ui_component. This was an information that was not in your issue description.

**Comment by novikor** [comment]
#kiev-cd

**Comment by magento-engcom-team** [comment]
@novikor thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by novikor** [comment]
Hi, @syedsaleem086 .

### Research results:

Well, **it is not a bug**: you have created the attribute 'commenced_business' with type 'static'. Static attributes are attributes which are stored in an entity table, - in our case, 'customer_entity'.

To solve the problem, you should add a 'commenced_business' column to 'customer_entity', - see 'dob' attribute creation as example: https://github.com/magento/magento2/blob/1795f67500287244e4a2443cd51ee29fd5f4a77a/app/code/Magento/Customer/Setup/CustomerSetup.php#L232,
https://github.com/magento/magento2/blob/1795f67500287244e4a2443cd51ee29fd5f4a77a/app/code/Magento/Customer/Setup/InstallSchema.php#L129

You can use the following UpgradeSchema script to solve the issue:
```php
class UpgradeSchema implements UpgradeSchemaInterface
{

    /**
     * @param \Magento\Framework\Setup\SchemaSetupInterface   $setup
     * @param \Magento\Framework\Setup\ModuleContextInterface $context
     */
    public function upgrade(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
        $installer = $setup;
        $installer->startSetup();

        $setup->getConnection()->addColumn(
            $setup->getTable('customer_entity'),
            'commenced_business',
            [
                'type'     => \Magento\Framework\DB\Ddl\Table::TYPE_DATE,
                'nullable' => true,
                'comment'  => 'Date Commenced Business',
            ]
        );

        $installer->endSetup();
    }
}
```

Please contact us if issue is not solved.

**Comment by syedsaleem086** [comment]
@novikor It is working thanks :)

**Comment by akssaiyad** [comment]
Customer Registration Custom attribute value create in admin and save

**1. Text Field**

**2. Drop Down Field**

**3. Date Field**

**Using** `UpgradeSchema.php`

    <?php
    
    namespace {CompanyName}\{ModuleName}\Setup;
    
    use Magento\Customer\Model\Customer;
    use Magento\Customer\Setup\CustomerSetup;
    /* irrelevant */
    #use Magento\Framework\Setup\UpgradeSchemaInterface;
    use Magento\Framework\Setup\InstallSchemaInterface;
    use Magento\Framework\Setup\ModuleContextInterface;
    /* irrelevant */
    #use Magento\Framework\Setup\SchemaSetupInterface;
    /* add this */
    use Magento\Framework\Setup\UpgradeDataInterface;
    use Magento\Framework\Setup\ModuleDataSetupInterface;
    
    class UpgradeData implements  UpgradeDataInterface
    {
        private $customerSetupFactory;
    
        public function __construct(\Magento\Customer\Setup\CustomerSetupFactory $customerSetupFactory)
        {
            $this->customerSetupFactory = $customerSetupFactory;
        }
        public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
        {
            if (version_compare($context->getVersion(), '1.0.1', '<')) 
            {
                // For Text field
                $customerSetup->addAttribute(
                        \Magento\Customer\Model\Customer::ENTITY,
                        'attribute_title',                    
                        [
                            'type' => 'text',
                            'input' => 'text',
                            'label' => 'Attribute Title',
                            'required' => false,
                            'visible' => true,
                            'user_defined' => false,
                            'sort_order' => 1000,
                            'position' => 1000,
                            'system' => 0,
                        ]
                    );
                $attribute_title = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'attribute_title')
                    ->addData(
                        ['used_in_forms' => ['adminhtml_customer']
                    ]);
    
                $attribute_title->save();
    
                //Add field Drop Down for Yes/No
                $customerSetup->addAttribute(
                        \Magento\Customer\Model\Customer::ENTITY,
                        'is_attribute',                    
                        [
                            'type' => 'int',
                            'input' => 'select',
                            'label' => 'Is Attribute',
                            'frontend' => '',
                            'default' => '1',
                            'class' => '',
                            'source' => 'Magento\Eav\Model\Entity\Attribute\Source\Boolean',
                            'backend' => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
                            'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                            'required' => false,
                            'visible' => true,
                            'user_defined' => false,
                            'sort_order' => 1000,
                            'position' => 1000,
                            'system' => 0,
                        ]
                    );
                $is_attribute = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'is_attribute')
                    ->addData(
                        ['used_in_forms' => ['adminhtml_customer']
                    ]);
    
                $is_attribute->save();
    
                // For Date And Time field
                $customerSetup->addAttribute(
                    \Magento\Customer\Model\Customer::ENTITY,
                    'custom_date',                    
                    [
                        'label' => 'Custom Date',
                        'type' => 'datetime',
                        'input' => 'date',
                        'frontend' => 'Magento\Eav\Model\Entity\Attribute\Frontend\Datetime',
                        'backend' => 'Magento\Eav\Model\Entity\Attribute\Backend\Datetime',
                        'validate_rules' => '{"input_validation":"date"}',
                        'user_defined' => false,
                        'required' => false,
                        'visible' => true,
                        'searchable' => false,
                        'filterable' => false,
                        'comparable' => false,
                        'visible_on_front' => false,
                        'sort_order' => 1000,
                        'position' => 1000,
                        'system' => 0,
                    ]
                );
                $custom_date = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'custom_date')
                    ->addData(
                        ['used_in_forms' => ['adminhtml_customer']
                    ]);
                    // more used_in_forms ['adminhtml_checkout','adminhtml_customer','adminhtml_customer_address','customer_account_edit','customer_address_edit','customer_register_address']
                $commenced_business->save();
            }
        }
    }
