### ISSUE TITLE
Authentication using telephone instead of email

### ISSUE THREAD

**Issue by igor-imaginemage** [magento/magento2#14877]
Hi, I am thinking in add the feature to use telephone number instead of email on Magento 2.

Mobile phones are everywhere and and in some countries people are using more their numbers to associate in some services instead of an email address.

My idea is offer both type of authentication on Magento 2 (email or sms) and also send the transactional emails using SMS messages to these customers. The admin user can customize the sms templates like it happens on transactional emails.

To send the messages we can offer a ready integration with a 3rd party service like Twilio or MessageMedia.

I was working on that in a custom extension, it's working good but my idea is incorporate that on Magento core.

Thanks.

**Comment by magento-engcom-team** [comment]
Hi @igor-imaginemage 
Thank you for the suggestion. As this github issue tracker is only intended for Magento Core technical issues we would suggest submitting a feature request to https://github.com/magento/community-features/issues

Thanks for collaboration
