### ISSUE TITLE
Magento 2.2 RESTful API response error caused by plugin interceptor

### ISSUE THREAD

**Issue by YuanXiong** [magento/magento2#14878]
### Preconditions

1. Magento 2.2.2(and Magento 2.1.x)
2. Fresh install(optional)
3. Add a new module with a plugin interceptor(before, after or around) to "Magento\Customer\Api\CustomerRepositoryInterface". 

Add the plugin to the di.xml: 
/CompanyName/PackageName/etc/di.xml
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Customer\Api\CustomerRepositoryInterface">
        <plugin name="companyname_packagename_customer_save" type="CompanyName\PackageName\Plugin\CustomerRepositoryPlugin"  sortOrder="9999" />
    </type>
</config>
```
Create a plugin. The content does not matter. You can even try with an empty file.
/CompanyName/PackageName/Plugin/CustomerRepositoryPlugin
```php
<?php
namespace CompanyName\PackageName\Plugin;
class CustomerRepositoryPlugin{}
?> 
```
4. Run command "magento setup:upgrade"
5. Clean cache
6. Create a user with name="user@gmail.com" and password="abcd@1234"

### Steps to reproduce

1. Request customer token:
curl -X POST "http://localhost/index.php/rest/V1/integration/customer/token"      -H "Content-Type:application/json"      -d '{"username":"user@gmail.com", "password":"abcd@1234"}'
2. Get customer information using the token
curl -X GET "http://localhost/index.php/rest/V1/customers/me"      -H 'Content-Type:application/json' -H 'Authorization: Bearer [the token]'

### Expected result

1. 0pqplrg9fc7me1f1qv0dqbmxc45n4arr 
(a token string)
2. Customer information

### Actual result

1. 
0pqplrg9fc7me1f1qv0dqbmxc45n4arr 
(a token string with lots of blank characters and a new line)
2. Error
 {"message":"Consumer is not authorized to access %resources","parameters":{"resources":"self"}}

### Other Information

We can trim the token here to remove the paddings. However, we have to release a new app and ask all users to download.

We can run command "magento setup:di:compile" to solve the problem. However, next time when we run "magento setup:upgrade", the problem comes back again.

We add plugins to other public functions. Each of the called function will add a new line of padding in front of the related API response. The plugin can be empty.

The API response type can be JSON, string, integer or exception. You can run CURL with -D option to check the content length.

**Comment by phoenix128** [comment]
I was unable to reproduce this in 2.2 or 2.1 .
I think your problem is most likely related to the closing PHP tag in your plugin repository code:

```
<?php
namespace CompanyName\PackageName\Plugin;
class CustomerRepositoryPlugin{}
?> 
```

When dealing with PHP classes you should never close the PHP tag, otherwise extra spaces could be added to your output.

Change it to:

```
<?php
namespace CompanyName\PackageName\Plugin;
class CustomerRepositoryPlugin{}
```

**Comment by YuanXiong** [comment]
@phoenix128 
It works. I really appreciate your help and will check all my code for the closing issue.
The issue will be closed.
