### ISSUE TITLE
Warning Found in Exception log

### ISSUE THREAD

**Issue by aathil-ali** [magento/magento2#14871]
I have overided checkout_cart_item_renderers.xml
I got exception says " Magento\Framework\Exception\LocalizedException: The element
'checkout.cart.item.renderers' already has a child with alias 'virtual' in
/var/www/html/tristar/vendor/magento/framework/Data/Structure.php:611
Stack trace:
#0 /var/www/html/tristar/vendor/magento/framework/Data/Structure.php(319):
Magento\Framework\Data\Structure->_insertChild('checkout.cart.i...',
'checkout.cart.i...', NULL, 'virtual')
"
------------------------------------------------------------------------------------------------------------------------------------------
code
`<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="checkout.cart.item.renderers">
            <block class="Magento\Checkout\Block\Cart\Item\Renderer" as="virtual" template="cart/item/default.phtml">
                <block class="Magento\Checkout\Block\Cart\Item\Renderer\Actions" name="checkout.cart.item.renderers.virtual.actions" as="actions">
                    <block class="Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit" name="checkout.cart.item.renderers.virtual.actions.edit" template="Magento_Checkout::cart/item/renderer/actions/edit.phtml"/>
                    <block class="Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove" name="checkout.cart.item.renderers.virtual.actions.remove" template="Magento_Checkout::cart/item/renderer/actions/remove.phtml"/>
                </block>
            </block>
        </referenceBlock>
    </body>
</page>

`
![xml](https://user-images.githubusercontent.com/22939033/39309147-ed05316a-4984-11e8-9673-bf1c62d47f05.png)

**Comment by magento-engcom-team** [comment]
@aliaathil please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
