### ISSUE TITLE
Content section: can't set Page in website -> store view

### ISSUE THREAD

**Issue by MCfra** [magento/magento2#14887]
In the beckend Content section, I can't edit the 'Page in websites' settings;
The 'Store view' field is not visible, and checking page with browser page inspector, I find an error:
the requested file

/pub/static/[version]/adminhtml/Magento/backend/it_IT/Magento_Ui/templates/form/element/multiselect.html is missing, it generate a 404 error.

Checking via ftp on the server this file is not present, where can I find it?

### Preconditions

1. Magento Version 2
2. site hosted on siteground
3. PHP version 5.3.26
4. MySQL version 5.6.36-82.1

### Steps to reproduce

1. simply go to Content -> Page in websites

### Expected result

1. get the form to edit data

### Actual result

1. the filed is not present

![image](https://user-images.githubusercontent.com/38791495/39372731-858cc31a-4a45-11e8-9505-379ba4af7dcc.png)

**Comment by thiagolima-bm** [comment]
@MCfra PHP version 5.3.26 is supported, please check the system requirements here:
https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

**Comment by MCfra** [comment]
@thiagolima-bm first of all thankyou for your support;
the system requirements are ok, he problem seems to be the missing file 

/pub/static/[version]/adminhtml/Magento/backend/it_IT/Magento_Ui/templates/form/element/multiselect.html

I can't find it on server and I don't know where can I get it

**Comment by MCfra** [comment]
SOLUTION - I took the missing file from a fresh local installation on my pc and moved to the right location on the remote server.
