### ISSUE TITLE
Magento 2.2.1 Web Setup Wizard problems - {{menuState.title}}

### ISSUE THREAD

**Issue by antheny916** [magento/magento2#14880]
Hello! I'm new here and would like to see if you guys can help me out with this issue!

### Preconditions
1. Magento 2.2.1

![error1](https://user-images.githubusercontent.com/38775647/39344290-6c1618d2-4996-11e8-9143-545837260452.png)

![error2](https://user-images.githubusercontent.com/38775647/39344296-70f3d010-4996-11e8-8c1d-fd81c658b6ec.png)

### Steps to reproduce
1. Sign into admin panel.
2. go to System > tools > web setup wizard.
3. You get a "1" icon with the text {{menuState.t...
4. Click on the "1" icon and you get 404 error: Page not found.

### Expected result
1.  It should be a page with Component Manager, System upgrade, & System Config icons

### Actual result
1. You get a "1" icon with the text {{menuState.t...
2. Click on the "1" icon and you get 404 error: Page not found.

Any suggestions? I'm completely puzzled on this.....Thanks to all!

**Comment by magento-engcom-team** [comment]
@antheny916 
thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version

**Comment by ghost** [comment]
Hi @antheny916  I cannot reproduce by you scenario, maybe problem in some custom module, we close this issue, if you'd like to update this issue please reopen the issue
![selection_041](https://user-images.githubusercontent.com/40756439/43312737-cea7d57e-9196-11e8-9638-58f619be5e50.png)
