### ISSUE TITLE
Magento 2.2.3: Checkout page Summary Sidebar not update the total 【UPDATE】

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#14888]
### Preconditions

1. magento 2.2.3
2. php71

### Steps to reproduce

1. go to cart xxx.com/checkout/cart/
2. estimate shipping and tax > showing subtotal andthen becoming 0 
2. estimate shipping and tax > change the shipping methods > subtatal , shipping total , grand total are not update in Summary Sidebar

### Expected result

1. fit it, please help,thank you
### Actual result

1. subtatal , shipping total , grand total are not update in Summary Sidebar

I have one solution, but not really help. 
`/module-checkout/view/frontend/web/js/view/summary/shipping.js`

Have to define 'Magento_Checkout/js/model/cart/estimate-service' and pass dependency estimateService into function.

Comment out this line var price = this.totals().shipping_amount; under function getValue: function() and add following two lines after that.

```
var shippingMethod = quote.shippingMethod();
var price = shippingMethod.amount;
```

**Comment by ghost** [comment]
@rigu12, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
