### ISSUE TITLE
Can't display resource list when create custom role in backend

### ISSUE THREAD

**Issue by blankapham** [magento/magento2#1488]
When I create a custom role for user in backend, I can' select any resource after I select resource access is "Custom". Can you help me?
Thanks,

**Comment by joanhe** [comment]
@blankapham I cannot reproduce this issue. Could you provide more detailed steps on how to reproduce this problem?

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.

**Comment by blankapham** [comment]
@vpelipenko Hi,
This is the error of beta version 0.74.0. Thanks
