### ISSUE TITLE
Product Attributes for Bundle Products cannot be changed or saved

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#14890]
### Preconditions

1.  Magento 2.2.3
2.  PHP 7.0.29 
3. MySql  Ver 15.1 Distrib 10.1.32-MariaDB,

### Prerequisites 
1. Make sure you have an Attribute Set that has Product Attributes that are used in the Layered Navigation.

### Steps to reproduce

1. Create a  Bundle Product
2. Change the Attribute Set to a set that has Product Attributes that are used in the Layered Navigation.
3. Fill out required fields and basic information for product.
4. Create 1 Bundle Option and add product to it.
5. Set initial values for Product Attributes that are used in the Layered Navigation.
6. Click Save.
7. Page should refresh and reload the newly created product for editing.
8. Change the values of the Product Attributes that are used in the Layered Navigation, to something else.
9. Click Save.
10. Page should refresh and reload the same product for editing.

### Expected result

1.  You should be able to see the new values set for the Product Attributes.

### Actual result

1. The values for the Product Attributes are unchanged and are still set to the original values set during initial creation of the product.

### Workaround
1. During initial creation of the Bundle Product, **DO NOT CREATE BUNDLE OPTIONS**.
2. After the Bundle Product has been created and saved. Then create and fill your bundle options.
3. Now you will be able to change and save Product Attributes that are used in the Layered Navigation.

**Comment by phoenix128** [comment]
Does it happen on a fresh installation? I was unable to reproduce it on 2.2.x and in 2.3.x .

**Comment by orbitrod** [comment]
Yes I tested it on a fresh installation and was able to reproduce the error.

**Comment by ghost** [comment]
Hi @orbitrod the fix for this issue has available in 2.2-develop branch

**Comment by orbitrod** [comment]
Do you know what the commit is for the fix?
