### ISSUE TITLE
Russia is eligible PayPal merchant country but absent in Magento 2.0 "Merchant Country" dropdown

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1489]
https://www.paypal.com/ru/webapps/mpp/merchant

**Comment by asemenenko** [comment]
Hi @dfediuk I've created an issue MAGETWO-40299. We will update you once it get fixed by the team.

Thanks!

**Comment by piotrekkaminski** [comment]
This issue is resolved and should be published soon. 
@asemenenko tagging you to make sure the PayPal integration uses latest list.
