### ISSUE TITLE
CSS is not loading. - Magento 2.2

### ISSUE THREAD

**Issue by Karanp13** [magento/magento2#14900]
I have installed the Magento 2.2 version. Theme is not load. CSS and JS issue.

**Comment by robhuijben** [comment]
@Karanp13 Please report your issue according to the guidelines you can see here: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by magento-engcom-team** [comment]
Hi @Karanp13 Thank you for reporting.
Closing this issue now due to inactivity.
