### ISSUE TITLE
Coupon Codes from different Cart Sales Rules don't stack with each other

### ISSUE THREAD

**Issue by sergio-giganti** [magento/magento2#14929]
Good morning,
In Mag 2.2, I saved two sales rules with "fixed amount discount for the whole cart" and auto-generated coupon (generation provided through REST API calls) and applying the second coupon code overwrite the first one instead of stack with it.
Both rules have "Discard subsequent rules" set to no and priority set to 0.

How can I fix this? Am I doing something wrong?
Thank you for your support.

![image](https://user-images.githubusercontent.com/33863717/39370622-b0125326-4a3f-11e8-8e13-2f51bb89859c.png)
![image](https://user-images.githubusercontent.com/33863717/39370629-b496b284-4a3f-11e8-9cef-dbace6ffc5cf.png)

**Comment by magento-engcom-team** [comment]
Hi @sergio-giganti Thank you for reporting.

This is a correct behavior for a default Magento installation. Multiple coupons per shopping cart are not supported by default.

Thanks
