### ISSUE TITLE
Replace current editor with CKeditor

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1492]
Hello everyone, I was trying version 1.0 beta and I noticed that it is still the old editor of Magento 1.

I think that the best solution for ecommerce in 2015 is to be able to use a much more advanced editor and also known by various types of users who normally use a website (Copywriter, customers, etc ...).

CKEditor can use and create many different plugins, which allow all supporters to be able to create new plugin fully integrated into Magento same.

**Comment by tkacheva** [comment]
@CRYX2 thank you for your input! We have such plans in our roadmap - MAGETWO-36447

**Comment by dfediuk** [comment]
May be it would be interesting for somebody, I have done another TinyMCE replacement: with Markdown Editor: https://mage2.pro/t/160

**Comment by MarioSteinitz** [comment]
We created a Magento 2 extension replacing TinyMCE with latest version of CKEditor. It allows conditionally replacing all TinyMCE instances and also adding CKEditor to any BE textarea of choice.

The extension is in alpha version. Doing field tests right now and creating Advanced Content Filter definitions. It's supposed to being released by mid of July this year.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Replace-current-editor-with-CKeditor/idi-p/46556).
