### ISSUE TITLE
Category set to display static block only includes columns columns main on page

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#14931]
### Preconditions
Magento 2.1.7

### Steps to reproduce
1. Create a category
2. Update Design->Layout set to="1 column"
3. Set Display Settings->Display Mode->Static Block Only
4. Set Display Settings->Anchor-> set to="No"
5. Create configurable product and create/add simple product variations e.g colour/size at least one.
6. Navigate to magento category url should see nothing.

### Expected result
the columns div to be remove 

### Actual result
the column div still lingering 

![image](https://user-images.githubusercontent.com/40755810/43316183-13a81436-91a1-11e8-88d8-c76da69fa116.png)

**Comment by engcom-backlog-nickolas** [comment]
Hello @lano-vargas, thank you for your report. Unfortunately I wasn't able to reproduce this issue.
![peek 2018-07-27 11-48](https://user-images.githubusercontent.com/40755810/43311286-ab0ad11a-9192-11e8-925d-fa4fb99fe0f7.gif)
If you'd like to update it, please reopen the issue.

**Comment by lano-vargas** [comment]
@engcom-backlog-nickolas  thanks for the video.

you are missing the point it's not the sidebar filter div. its' the column div.

Before:
<img width="1341" alt="screen shot 2018-07-27 at 10 41 05" src="https://user-images.githubusercontent.com/3495481/43314420-c5106a00-918a-11e8-9cfc-63de25699ced.png">


After:
<img width="1789" alt="screen shot 2018-07-27 at 10 44 26" src="https://user-images.githubusercontent.com/3495481/43314432-cdfc2898-918a-11e8-9a1f-e984643c9f5c.png">

Right Click inspect element the div `columns` still there.

**Comment by engcom-backlog-nickolas** [comment]
@lano-vargas thanks for feedback.
We've acknowledged the issue and added to our backlog.

**Comment by yosefkurniawan** [comment]
hi, I think this is not a bug. Even in all other pages that use 1column layout also have the div `columns`.
homepage:
<img width="1440" alt="homepage" src="https://user-images.githubusercontent.com/6382194/43697682-01ff6910-9970-11e8-816d-6c62ef555017.png">

product page:
<img width="1440" alt="product page" src="https://user-images.githubusercontent.com/6382194/43697684-02319e08-9970-11e8-8131-1680aae663af.png">

**Comment by magento-engcom-team** [comment]
@lano-vargas, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
