### ISSUE TITLE
GTM + Cookie restriction mode may block the checkout

### ISSUE THREAD

**Issue by shavounet** [magento/magento2#14938]
### Preconditions
1. Reproduced on a Magento 2.2 EE with a custom theme based on luma

### Steps to reproduce
1. Enabled Cookie restriction mode (`bin/magento config:set web/cookie/cookie_restriction	1`) & cleanup cache
    * the cookie banner should now display in FO
2. With a clean profile (private navigation for example) do ***not*** clic on "OK" in this cookie banner
3. try to checkout anything

### Expected result
1. checkout should be fine

### Actual result
1. when validating the shipping page, the checkout is now blocked in an intermediate, empty, state
2. the error `TypeError: window.dataLayer is undefined` is displayed in JS console

While doing some analysis, I found that the dataLayer object is not created here `vendor/magento/module-google-tag-manager/view/frontend/web/js/google-tag-manager.js:40` if the banner has not be checked. Later in the code `window.dataLayer.push` is directly called and fail.

For now I've only wrapped those calls in conditions, but maybe it should be catched earlier. In attachments, you will find the patches I intend to test and use on `magento/google-tag-manager` module.
* [patch on Magento_GoogleTagManager/js/action/checkout](https://github.com/magento/magento2/files/1967840/mg_cookie.txt)
* [patch on Magento_GoogleTagManager/js/action/product-details](https://github.com/magento/magento2/files/1967841/mg_cookie2.txt)

**Comment by EliasKotlyar** [comment]
I can reproduce this issue on M2.2.4 EE. Many thanks for that patch!

**Comment by ghost** [comment]
Hi @shavounet , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
