### ISSUE TITLE
We Coun't find any records

### ISSUE THREAD

**Issue by testiwm007** [magento/magento2#14934]
We getting this error on configuration, orders and catalog

**Comment by magento-engcom-team** [comment]
@testiwm007 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

Please reopen or create a new issue with the required information.
Thank you
