### ISSUE TITLE
Fourth level of categories not working

### ISSUE THREAD

**Issue by mwaheed92** [magento/magento2#14930]
Hello Magento team,

I noticed that 4th level of categories (sub-sub-sub categories) is not working when switching between store views (Eng <-> Arabic) views in my case

### Preconditions
1. Magento 2.2.2
2. PHP 7.0.29

### Steps to reproduce
For example: I have "All Department" -> "Medical" -> "Anesthesia" -> "Ventilators"
and these are the links of them

1) http://megatronic.com.eg/222/all.html
2) http://megatronic.com.eg/222/all/medicals.html
3) http://megatronic.com.eg/222/all/medicals/anesthesia.html
4) http://megatronic.com.eg/222/all/medicals/anesthesia/ventilators.html

Link #4 is not working when switch it to the other store view and vise versa

### Expected result
When switching store view from link #4, it should be the same link but with different view

### Actual result
Whoops, our bad...
The page you requested was not found, and we have a fine guess why.

Note: I also tried this on pure Magento 2.2.2 and 2.2.3 versions without installing the claue theme and still the problem exists

Regards,

**Comment by phoenix128** [comment]
Unable to reproduce in 2.2 or 2.3 .

I checked your URLs and your store is redirecting with a 301 code from a well formatted URL (e.g.: http://megatronic.com.eg/222/all/medicals/anesthesia.html?___store=eg&___from_store=gb) to a wrong one cutting the last part (http://megatronic.com.eg/222/all/medicals/anesthesia).

Seems like a problem with a server side configuration or a 3rd party extension.

**Comment by mwaheed92** [comment]
Hi phoenix128,

all/medicals/anesthesia.html is working well
The problem in the fourth level all/medicals/anesthesia/ventilators.html

I also tried to install a new pure Magento 2.2.3 version without any 3rd party extensions and the problem is exist.

**Comment by phoenix128** [comment]
What about server side configuration?

**Comment by mwaheed92** [comment]
If you mean back-end side (admin panel)
there is no special configurations just creating the tree of categories. do you mean something else?

**Comment by mwaheed92** [comment]
@phoenix128 another example

This is a new magento version with sample data 2.2.3
I have just created some sub-categories

open: https://megatronic.com.eg/test/x/y/z/a.html
and switch to Arabic language

**Comment by mwaheed92** [comment]
you can also check that the configurations are normal

https://megatronic.com.eg/test/adminbw
user: bwmagento
pass: abcd1234

**Comment by ghost** [comment]
@mwaheed92, thank you for your report.
This issue is already fixed in the latest Magento release. Please update your instance.

**Comment by mwaheed92** [comment]
@engcom-backlog-pb thank you for your notice
Is there a patch to apply to fix the problem instead of updating to the latest version?

**Comment by magento-engcom-team** [comment]
@mwaheed92 Most likely 2.2.5 patch should do it.

Closing this ticket now. Thank you for collaboration.
