### ISSUE TITLE
Attribute 'setup_version' is missing for module error when defined as optional

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1493]
Using the defined module.xml when creating a module:

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
        <module name="Foo_Bar" />
    </config>

Leads to this error: `Attribute 'setup_version' is missing for module`

However as defined by `lib/internal/Magento/Framework/Module/etc/module.xsd`, this is an optional field:
`<xs:attribute name="setup_version" type="setupVersion" use="optional" />`

**Comment by joanhe** [comment]
Thanks for reporting this issue. Internal issue MAGETWO-40320 is created.

**Comment by dsikkema** [comment]
Hi @markoshust! Again, thanks for the report, we're tracking it. I just wanted to mention how we're planning to fix this: setup_version will become a required attribute, to reflect the fact that it really is required.

**Comment by mazhalai** [comment]
@markoshust This issue has been fixed in 2.0.0, hence closing this issue.

**Comment by carlos-reynosa** [comment]
And also what would be some possible issues if someone is using declarative scheme but the setup_version was not included? I ask because i feel like i'm getting some data issues and i think it might be related to this. Missing tables and such.
