### ISSUE TITLE
Admin theme broken (1.0.0 beta)

### ISSUE THREAD

**Issue by unirgy** [magento/magento2#1494]
Please see this screenshot: http://screencast.com/t/LZARMTHj

**Comment by maksek** [comment]
It looks like css preprocessor is not compile theme. can you try to remove pub/static/ content and try again?

**Comment by vpelipenko** [comment]
@unirgy, the same issue was posted here https://github.com/magento/magento2/issues/1484. You can find there details how it can be fixed.

**Comment by ilol** [comment]
@unirgy if you don`t have concerns I am closing the issue. Thank you.
