### ISSUE TITLE
2.2.4 web installation is not working

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#14947]
Hi. Tried to install latest M 2.2.4 but web installator is not working. I unpacked ZIP as usual, and type domain.com or domain.com/setup

It gives error with info:
"Autoload error
Vendor autoload is not found. Please run 'composer install' under application root directory."

Hope somebody could fix 2.2.4 installation ZIP

**Comment by VZeroCool** [comment]
Connect to your web-server via Shell, Than Go to root directory of Your Magento Installation.

Than execute `composer install`.

It will install composer and update dependencies. Than run setup again.

**Comment by tomekjordan** [comment]
I choose web installer to install it via web. 

if I like to use composer I would install it via composer. Many hostings doesn't support composer and you need root rights

**Comment by hostep** [comment]
@tomekjordan: just out of curiosity, did this work in 2.2.3 and older versions? Or has this never worked?

And a small hint: you can simply put the `composer.phar` file on the server and then just call that one instead of a globally installed composer binary, works perfectly fine in my experience :)

**Comment by tomekjordan** [comment]
Web installer worked in 2.2.2 and 2.2.3. Its purpose is to install Magento from scratch with Chrome or other browser. Of course I could use composer. but I dont like web installer right know - just for quick tests on test hosting. So the easy way is Web Installer - if it doesnt work - its just a bug

ps. your hints are not working- Somebody could have no access to SSH console

**Comment by hostep** [comment]
Ok gotcha. So sounds like a new bug indeed than.

(Regarding hosting: I would look for a different hosting then, it's highly beneficial to have ssh access for Magento installations in my opinion, I didn't even know that in 2018 there are still hosting companies not providing ssh access, that's kind of a standard feature now)

**Comment by tomekjordan** [comment]
@hostep I clearly said - that the problem is with Magento Web installer. This is the case.
Not my hosting or my choice. I have 3 different hostings. all with root access.
Bug is raised - because web installer is not working - no matter I have SSH or NOT. Web installer should work. and thats a case.

**Comment by hostep** [comment]
Yes, I understood you, please re-read the first sentence of my previous post, I'm only trying to help here :)

**Comment by tomekjordan** [comment]
@hostep its a bug tracking forum..... not a community for advices.... or HOW-TO guides

**Comment by DanielRuf** [comment]
Hm, could we do some bisecting (git bisect) here to narrow the commit down which introduced this regression?

**Comment by seppoviuh** [comment]
I had this issue also today, the installation was stuck on 0%.
I believe the issue is related to Klarna extension and not supported PHP version.
When I tried composer install I got the following error,
![screenshot 2018-05-08 09 58 15](https://user-images.githubusercontent.com/39083752/39748861-895b54ce-52b1-11e8-8ead-2b42449d1aba.png)
Once I updated my PHP version to the latest the webinstaller run without any issues.

**Comment by tomekjordan** [comment]
I use PHP 7.1.11 so its not the same problem

**Comment by ghost** [comment]
@tomekjordan, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
