### ISSUE TITLE
The values of the "Modified At" column in CMS pages' grid are wrong.

### ISSUE THREAD

**Issue by vnaz** [magento/magento2#14948]
### Preconditions

1. Magento 2.2.3
2. PHP 7.0

### Steps to reproduce

1. Modify CMS page, save it and back to the grid.

### Actual Result
1. In the grid you will see modified date did not change

### Expected result

1. Modified date column should show the date of the last modification.

**Comment by jchesko** [comment]
We are also seeing this issue.

**Comment by julienanquetil** [comment]
Hi,
the issue has been fixed in magento/magento2#12636 by @osrecio in 2.2.4
Related commit(s):
https://github.com/magento/magento2/commit/22f454dd020719686c558a36d67df6dc13506c3f

**Comment by ghost** [comment]
@vnaz, thank you for your report.
This issue is already fixed.
