### ISSUE TITLE
No Option to Exit Enlarged Images on Mobile Devices (Developer Mode)

### ISSUE THREAD

**Issue by uandiweb** [magento/magento2#14943]
### Preconditions
1. PHP 7.1.6
2. Magento 2.2.3 (Developer Mode) with Luma Theme: 

### Steps to reproduce
1. Make sure Magento is in Developer Mode
2. Visit any product page using iPhone
3. Click on the main image to enlarge it
4. Try to exit the image

### Expected result
1. Exit image & see the product details

### Actual result
1. You can't exit the image & see the product details

**Since clicking on images is done by most users, there must be a solution even for developer mode. Every site needs to be in Developer mode every now & then, and users not being able to exit images is a big issue.**

**Comment by ghost** [comment]
Hi @uandiweb I cannot reproduce by your scenario steps.If you'd like to update it, please reopen the issue.
