### ISSUE TITLE
Validate class not found from basename 'StringLength'

### ISSUE THREAD

**Issue by nikidexa** [magento/magento2#14954]
Hi, I try to save something in users configuration, but cannot. 
From backend: Shop->Configuration->Users ->Users Configuration
If I try to change anything in this page, magento show me this message:
> Error during save configuration :Validate class not found from basename 'StringLength'

so is impossible to save and change anything....

**Preconditions**
magento 2.2.2

**Steps to reproduce**
Try to save User Configuration, but cannot

**Expected result**
Save User configuration with success

**Actual result**
Try to save user configuartion and activate Captcha for Contact us, but cannot... Definetly if I try to save anything in User Configuration I cannot and Magento show this message 

> Error during save configuration :Validate class not found from basename 'StringLength'

**Comment by nikidexa** [comment]
no solution?? no one facing this issue?

**Comment by ghost** [comment]
Hi @nikidexa i cannot reproduce your's scenario steps, see attachments,
If you'd like to update it, please reopen the issue.
![frame-08d](https://user-images.githubusercontent.com/40756439/43194693-afe26c26-900b-11e8-89ed-ac9ac7e4ed29.gif)

**Comment by emadha** [comment]
Do you run Litespeed?

**Comment by ghost** [comment]
@emadha The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by emadha** [comment]
@engcom-backlog-nazar the problem he's facing in my case was running Litespeed, causing this error, switching back to Apache made Magento run smoothly, i think it's how Litespeed runs php, i still didn't investigate that, but switching back to apache for now solved the issue.

I'll come back with a detailed solution later.

**Comment by ghost** [comment]
@emadha ok, thank you.
