### ISSUE TITLE
Catalog Price Rules “Apply Rule” button not showing

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#14956]
### Preconditions

1. Magento CE 2.2.2
2. 

### Steps to reproduce

1. We have tried to create catalog rules with category condition and it's not working. Also, we are unable to see Apply Rule button.

3. 

### Expected result

1. 
![image](https://user-images.githubusercontent.com/6079017/39570679-b37cd04e-4ee6-11e8-8ac3-3e8768240b39.png)

### Actual result

![image](https://user-images.githubusercontent.com/6079017/39570671-abd4c4be-4ee6-11e8-8615-9fb7ea642554.png)

**Comment by ghost** [comment]
Hi @ankursachdeva11 i cannot reproduce your's scenario steps, see attachments,
If you'd like to update it, please reopen the issue.
![frame-08d](https://user-images.githubusercontent.com/40756439/43193827-ab05605c-9009-11e8-9296-32df79e42aea.gif)
