### ISSUE TITLE
Google Analytics conversions not recording 2.2.4

### ISSUE THREAD

**Issue by tstamplis** [magento/magento2#14951]
# **Preconditions**
Magento 2.2.4
PHP 7.1
Cpanel Server

# **Steps to reproduce**
Production Mode
Google API information filled out in stores/configuration
Add product to cart, checkout

**# Expected result**
Conversion is recorded in Google Analytics

# **Actual result**
Conversion is not recorded in Google Analytics

Analytics page views is corrected in 2.2.4, however, conversions are not being recorded.  If inspecting via Google Chrome, there is nothing between Start and End tags for Google analytics on success page (no code is shown).

**Comment by Damianbv** [comment]
Same issue here, upgraded from 2.2.2 to 2.2.4:
![632a92da864a8f92dd2b53da5ae42120](https://user-images.githubusercontent.com/815721/39998648-0ac0ea72-5787-11e8-9799-c781eed2b4b2.png)

**Comment by amelojunior** [comment]
Same issue here with upgrade from 2.2.3 to 2.2.4

**Comment by manohar-prabhu** [comment]
We are also facing same issue, upgrade from 2.2.3 to 2.2.4

**Comment by wescey** [comment]
Same here, facing on 2.2.2 & 2.2.3.

Google API information filled out in stores/configuration. Performing a purchase, result = no conversion is tracked at all.

**Comment by anvaruk** [comment]
same problem , since upgrade to 2.2.4, 
google analytics tracks everything except transactions

here is the code I have at /checkout/onepage/success/ page

```
<!-- BEGIN GOOGLE ANALYTICS CODE --><script type="text/x-magento-init">
--
  | {
  | "*": {
  | "Magento_GoogleAnalytics/js/google-analytics": {
  | "isCookieRestrictionModeEnabled": 0,
  | "currentWebsite": 1,
  | "cookieName": "user_allowed_save_cookie",
  | "ordersTrackingData": [],
  | "pageTrackingData": {"optPageUrl":"","isAnonymizedIpActive":null,"accountId":"UA-xxxxxx"}        }
  | }
  | }</script><!-- END GOOGLE ANALYTICS CODE -->
```

**Comment by hostep** [comment]
Hi guys

Can someone confirm if applying the fix from this PR fixes the issue: https://github.com/magento/magento2/pull/15765 ?

They mentioned in another thread that this fix is going to be included in 2.2.6 (so not yet in 2.2.5).

**Comment by sashas777** [comment]
Hi guys,

I made bugfix based on a solution at #15765 and it seems works for our store. It is only for the version 2.2.4 with the assumption that it would be fixed in the newest release. If it won't be then I will update composer dependencies. 

Feel free to use it it would help your stores: https://github.com/sashas777/magento224-issue14951

GA log before: https://www.screencast.com/t/0RM1srfB8cL
GA log after: https://www.screencast.com/t/W2vVErEya

**Comment by wescey** [comment]
magento/module-google-analytics/view/frontend/web/js/google-analytics.js:56 

Replace with if (config.ordersTrackingData.hasOwnProperty('currency')) { instead of checking the lenght of a javascript Object.

**Comment by jbokhari** [comment]
Same issue after impromptu update from 2.2.3 -> 2.2.4. The patch by @sashas777 is working for me (Much appreciation 👍 )

**Comment by ghost** [comment]
Hi Guys, will this issue fixed in upgrade v2.2.6 ? thanks.

**Comment by stephenbori** [comment]
@magento-admin  - Can we confirm if this will be fixed in 2.2.5 / 2.2.6

**Comment by ghost** [comment]
@tstamplis, thank you for your report.
We were not able to reproduce this issue on Magento 2.2.5 by following the steps you provided. 
![image](https://user-images.githubusercontent.com/40756187/44986301-eb6e7600-af8b-11e8-9b51-fd3e615c1980.png)


Please provide more detailed steps to reproduce.

**Comment by magento-engcom-team** [comment]
@tstamplis Fix should now be available with recent 2.2.6 release. Please check commits from https://github.com/magento/magento2/pull/15765 for reference.

Please feel free to reopen if the issue persists with 2.2.6.

Thank you.

**Comment by ghost** [comment]
Hi @tstamplis will do, thanks!

**Comment by asadyar** [comment]
Just tested this on Magento 2.2.6 (a composer upgrade from 2.2.5) Conversion tracking is working now. Thanks Magento

**Comment by royandre** [comment]
We made a patch for this, attached.

[ga_order_tracking_fix.patch.txt](https://github.com/magento/magento2/files/2455894/ga_order_tracking_fix.patch.txt)

**Comment by nickpiro** [comment]
Any patch for 2.2.5?!
