### ISSUE TITLE
Issue when purchase with authorize.net redirect to empty cart page

### ISSUE THREAD

**Issue by buituanbg** [magento/magento2#14953]
**Preconditions**
I used Magento community version 1.9.3.0 then I upgraded to M2 2.1.7 and then I upgraded to 2.2.3 now I am using version 2.2.3 
1. Server used Varnish and Redis, PHP7.0 MySql 5.6
The extension for payment I use Authorize.Net CIM of Paradox Lab

**Steps to reproduce**
1. I can purchase good on M2 2.1.7 w/o any issues and used Authorize.Net CIM of Paradox Lab
2. After I Upgraded to 2.2.3 version and purchase by Authorize.Net CIM of Paradox Lab I got the issue 

**Expected result**
1. After complete purchase by credit card order is saved in back-end and it must be go to success page

**Actual result**
1. It went to empty cart page
Order saved in back-end after click to purchase but it redirect to empty cart page instead success page. If correct flow it must be go to success page.
I had debug and it seems all session is clear that is reason it went to empty card page.
Please help me check if this is new bug

**Comment by graffxdesign** [comment]
Same issue, following.

**Comment by buituanbg** [comment]
Hi @graffxdesign 
My issue it related to redis cache. I disable redis it work properly so I switch from redis to memcache to fix this issue. Let me know if it not working.

**Comment by ghost** [comment]
Hi @buituanbg thank you for report, I'm closing this issue as GitHub issue tracker is intended for Magento core functionality and components issues only.
If you'd like to update it, please reopen the issue.
