### ISSUE TITLE
\Magento\TestFramework\Application always generates 10 Sequence tables of each kind. 

### ISSUE THREAD

**Issue by p-bystritsky** [magento/magento2#14959]
### Preconditions

1. Magento 2

### Steps to reproduce

1. Start any integration test.
2. Observe integration test database before it was cleared.

### Expected result
1. sequence_creditmemo_N, sequence_invoice_N, sequence_order_N, sequence_rma_item_N, sequence_shipment_N tables are created for each store created in tests.

### Actual result

1. sequence_creditmemo_N, sequence_invoice_N, sequence_order_N, sequence_rma_item_N, sequence_shipment_N tables are automaticaly created in \Magento\TestFramework\Application only for Stores with id from 0 to 9. If some Store have id greater when 9, no such Sequence tables are generated for this Store.

**Comment by ghost** [comment]
@p-bystritsky, thank you for your report.
We've acknowledged the issue and added to our backlog.
