### ISSUE TITLE
I can not save any configurations from the admin panel

### ISSUE THREAD

**Issue by vicabitu** [magento/magento2#14965]
### Preconditions
1. Magento CE 2.2.1
2. Ubuntu server 16.4
3. PHP 7.0
4. Apache 2

### Steps to reproduce
1. Save settings from admin panel
2. Flush and clean cache memory
3. [YouTube video of the error](https://www.youtube.com/watch?v=0E6TDEvcFbE&feature=youtu.be)

### Expected result
1. settings saved

### Actual result
1. No settings are saved
2. No logs are written
3. Not any message error

**Comment by ghost** [comment]
@vicabitu, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
