### ISSUE TITLE
Cannot change order of customizable option values between pages

### ISSUE THREAD

**Issue by bastc** [magento/magento2#14969]
### Preconditions
1. Magento 2.2.4
2. PHP 7.1

### Steps to reproduce
1. Add a customizable option to a product
2. Add more than 20 values so a second "page" of values is created
3. Create 21st value
4. Try to change the order of the 21st value

### Expected result
1. I expect to be able to drag the 21st value to any position

### Actual result
1. The 21st value cannot be dragged outside its own "page" of values.

**Comment by ghost** [comment]
Hi @bastc you need to click for next page, then again to first page, so after that you able to drag & drop elements

**Comment by bastc** [comment]
Hi @engcom-backlog-nazar, thanks for your reply. Your suggestion still doesn't allow me to drag an element from the second to the first page. I can only drag & drop the values from the second page to a different position inside the second page.

**Comment by ghost** [comment]
Hi @bastc  This is duplicate for https://github.com/magento/magento2/issues/15219
