### ISSUE TITLE
Magento 2 Upgrade Error :: Class Not Found -> Composer\Semver\VersionParser

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [magento/magento2#14962]
I am try to upgrade 2.0.0 to 2.1.7.

As regard installation guide 6th step getting stuck.

Fatal error: Class 'Composer\Semver\VersionParser' not found in C:\wamp\www\gta\ vendor\composer\composer\src\Composer\Package\Version\VersionParser.php on line 17

How can i solve this error.

**Comment by magento-engcom-team** [comment]
@Jeeva-Rathinam Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks

**Comment by Jeeva-Rathinam** [comment]
@magento-engcom-team Thank you for your response, the issue solved.
