### ISSUE TITLE
Attribute values for Configs converting quotes to html entities in frontend

### ISSUE THREAD

**Issue by ranjithtsims** [magento/magento2#14979]
Hi All,
Recently we upgraded the site from 2.1.9 to 2.1.12. After the upgrade the configurable attribute values appear to be converting the quotes to &quot; (HTML Entities). Anybody knows a fix for this?

Thank you

**Comment by magento-engcom-team** [comment]
@ranjithtsims Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks
