### ISSUE TITLE
DUPLICATE of #14968 Theme switching error message in 2.2.4 `Area is already set`

### ISSUE THREAD

**Issue by sferreira-nicopu** [magento/magento2#14974]
### Preconditions

1.  We are on Magento Cloud Pro and found issue on Version 2.2.4
2. 

### Steps to reproduce

1.  In Content >> Design >> Configuration >> Apply a different theme or just try saving
2. 
3. 

### Expected result

1. SAVE Theme

### Actual result

1. [Screenshot, logs]
![snip20180503_97](https://user-images.githubusercontent.com/26257562/39595895-c8e6d8f6-4ede-11e8-9bc1-f8892565694a.png)

**Comment by sferreira-nicopu** [comment]
`BUG`

`RELEASE 2.2.4 BUGGY`

`REVERTED TO 2.2.3`

`RELEASE 2.2.3 NO PROBLEM ON THIS ASPECT`

**Comment by hostep** [comment]
Hi @sferreira-nicopu: I'm closing this since it's a duplicate of https://github.com/magento/magento2/issues/14968, hope that's ok for you?

**Comment by sferreira-nicopu** [comment]
Sure will follow #14968 then Thx
