### ISSUE TITLE
Slow loading of admin products listing in admin 2.1.x and 2.2.x

### ISSUE THREAD

**Issue by winterk80** [magento/magento2#14970]
**Preconditions**
Affects 2.1.x and 2.2.3

**Steps to Reproduce**
Add 3000 or more products. 
Add custom options to each product. 
Admin > Catalog > Products
Remove all filters
Set 100 or 200 products per page
Sort by ID or sort by SKU

**Expected result**
Loads list in 1-2 seconds. 

**Actual result**
Takes approximately 6-10 seconds to load products list

**Comment by ghost** [comment]
@winterk80, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![1](https://user-images.githubusercontent.com/40756187/42889379-f7a1e32e-8ab2-11e8-89fe-26f399eed109.gif)

**Comment by winterk80** [comment]
Reason you are not seeing this is your products do not have custom options. When the majority of products have custom options the dramatic slowdown occurs. It gets progressively worse the more custom options and products with custom options you add. Please retry with a dataset of products all with custom options.

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/40756187/43119979-423a2000-8f21-11e8-97f5-a95f8c2524eb.gif)
