### ISSUE TITLE
New Commands to Assist with GDPR Compliance

### ISSUE THREAD

**Issue by brobie** [magento/magento2#14981]
I've been thinking about writing some bin/magento commands to assist with GDPR.  Below I have some thoughts and pseudo code to express my idea would would like some feedback or affirmation that this would be useful to eventually live within the core.

## Project Goals
The goal of this project is to provide two functions that will assist a merchant while complying with GDPR.  

- Allow customer data to be easily found and exported in a human and computer readable format.
- Allow a customer's PII data to be anonymized. This would leave the records intact for reporting purposes, but remove all identifiable information.

## Development Goals
Allow for developers to easily add new entities and fields to export or anonymize.

## Proposed Commands
- bin/magento gdpr:customer:export johndoe@example.com
- bin/magento gdpr:customer:anon johndoe@example.com

## Example di.xml Entries
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Gdpr\Model\EntityList">
        <arguments>
            <argument name="entityList" xsi:type="array">
                <item name="customer" xsi:type="array">
                    <item name="class" xsi:type="string">Magento\Gdpr\Entity\Customer</item>
                </item>
 		<item name="customeraddress" xsi:type="array">
                    <item name="class" xsi:type="string">Magento\Gdpr\Entity\CustomerAddress</item>
                </item>
            </argument>
        </arguments>
    </type>
</config>
```

## Proposed Class & Interface Types

- Magento_Gdpr_Console_Command_GdprExport
- Magento_Gdpr_Console_Command_GdprAnon
- Magento_Gdpr_Model_EntityList
- Magento_Gdpr_Entity_Interface
- Magento_Gdpr_Entity_Customer
- Magento_Gdpr_Entity_CustomerAddress
- Magento_Gdpr_Entity_*

## Example Interface & Implementation
```
interface Gdpr_Entity_Interface {
	public function getEntityFields(int $id);
	public function anonymizeEntityFields(int $id, string $hash);
}

class Gdpr_Entity_Customer implements Gdpr_Entity_Interface {
	protected $fields [
		'field1',
		'field2'
	]

	public function getEntityFields(int $id){
		Use DI injected repository to load the object by the id
		Loop through the fields and pull the data out
		return the data as an array
	}
	public function anonymizeEntityFields(int $id, string $hash) {
		Use DI injected repository to load the object by the id
		Loop through the fields and set the value of the fields to the hash string
		save the object/data
	}
}

class Gdpr_Entity_List {
	public function buildEntityData($id) {
		loop through the entities
		get the fields and store them in a single array
		format the array
		return the formatted data
	}
	public function anonymizeCustomer($id) {
		create a hash out of the customer's email address
		loop through the entities
		call the anonymizeEntityFields
		return this->buildEntityData();
	}

}

class Magento_Gdpr_Console_Command_GdprExport extends Command {
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        Get the injected list class
        Call the $listClass->buildEntityData()
        Flush the output
    }

}
```

**Comment by clivewalkden** [comment]
Don't we want to keep sales order information regarding a customer as that is a legitimate reason for tax purposes? 

I can see the need to anonymise guest data and potentially newsletter signups, but you also need to keep a record of the date the consent was given (and withdrawn), the consent message that the user agreed to. The data could then be removed at a later date subject to the companies data retention period.

Just my understanding of the GDPR situation as it relates to Magento.

Any one have other thoughts?

**Comment by sprankhub** [comment]
I like the idea of `gdpr:customer:export`. However, it may be good to have that accessible via the admin interface. I, as a developer, would hate if all my clients ask me to export customer data of certain customers. Merchants should be able to do that in the admin area on their own.

I still do not think that anonymizing data is okay. I guess data retention for tax reasons is more important than anonymization. Future will tell how courts decide about that...

**Comment by lingwooc** [comment]
Just for your reference there is a semi abandoned module that attempts to comply with gdpr. https://github.com/AdFabConnect/magento2gdpr

It doesn't encrypt the customer information although it claims to. Perhaps magento should do this by default for gdpr?

**Comment by FreekVandeursen** [comment]
The key point will be necessity. It will be up to the merchant to prove that there is a valid reason for retaining customer data (e.g. tax reasons). But even those reasons might not extend to infinite data retention. For example, is tax reasons still a valid reason to retain customer data 10 years after the date of sale?

That said, it will be difficult to create a "one solution fits all" module in Magento. Though some handy tools as suggested here, like gathering all customer data, and a framework for anonymizing, could prove very useful.

**Comment by cscd98** [comment]
Would like to see Magento tackle this also

**Comment by orlangur** [comment]
Feature suggestion looks pretty nice to me 👍 

Small notes:
1) We should not forget about modularity, besides `Magento_Gpdr`/`Magento\Framework\Gpdr` there should be `Magento_CustomerGpdr` etc
2) What is PII and what is not is better to be defined in declarative manner (something similar to what we define as private data)

GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
