### ISSUE TITLE
Why is flat catalog not enabled by default?

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#14985]
Hello,

I wanted to make a PR but there may be a reason.

I was wondering why the flat catalog for products and categories is not enabled by default? By experience, almost every stores enable this feature and the only cases I saw where it was disabled were very specific.

Is there a reason to not enable it by default?

Thanks!

**Comment by kandy** [comment]
Hi @VincentMarmiesse 
First of all flat index has limitation due to MySql: only 64 attributes can be added to the index
Second - we do not see significant improvement on catalog  with flat indexer
