### ISSUE TITLE
Visibility changes when attribute is not loaded in Product Collection

### ISSUE THREAD

**Issue by julian-van-drielen** [magento/magento2#14986]
### Preconditions
1. PHP 7.0.27
2. Magento CE 2.2.3
3. 10.1.31-MariaDB MariaDB Server

### Steps to reproduce
1. In a cron create a product collection using the factory.
2. Add some filters to load products desired for the functionality.
3. Set a attribute value and save the product

### Expected result
1. Visibility attribute of the product should stay the same even though it is not loaded using the addAttributeToSelect function

### Actual result
1. Visibility changed back to default value (VISIBILITY_BOTH / 4)

Doesn't work as expected:
```
$productCollection = $this->productCollectionFactory->create();
$productCollection->addFieldToFilter('news_to_date', ['notnull' => true]);
$productCollection->addFieldToFilter('news_to_date', ['lt' => $today]);
```

Does work as expected:
```
$productCollection = $this->productCollectionFactory->create();
$productCollection->addFieldToFilter('news_to_date', ['notnull' => true]);
$productCollection->addFieldToFilter('news_to_date', ['lt' => $today]);
$productCollection->addAttributeToSelect('visibility');
```

**Comment by ghost** [comment]
Duplicate of #15187

**Comment by janssensjelle** [comment]
Not duplicate of #15187 - this seems to be a different issue.

The issue here is that it saves the product with the default value if it was not selected. While the only thing that should be changed is the modified product attribute.

**Comment by RonakParmar** [comment]
Do we have any solution of this issue? 

we are also experiencing same kind of issue in Magento EE 2.4.5-p7 setup.  The visibility of product is getting changed automatically from "Catalog, Search" to "Not Visible Individually". 

Can anyone help to check this issue?
