### ISSUE TITLE
Error after update 2.2.3 to 2.2.4

### ISSUE THREAD

**Issue by josecoelho509** [magento/magento2#14980]
Can anyone help me because I'm not finding the solution. I have Magento 2.2.3 and yesterday I updated to 2.2.4, by composer and after updating both the admin and the front appears the 404 error. Can anyone give me a hint? Thank you

**Comment by edthomas1** [comment]
I have similar issues with my website. It was an automatic update from 2.2.3 to 2.2.4 now the front page appears the 404 error with ERR_TOO_MANY_REDIRECTS.>. Any suggestions?

**Comment by josecoelho509** [comment]
not yet unresolved

**Comment by magento-engcom-team** [comment]
@josecoelho509 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by EmilyPepperman** [comment]
Here is a fix for you... I had the same issue 
Fix for homepage URL if 404
DELETE from url_rewrite where target_path = 'catalog/category/view/id/1'
the end number in the above needs to be your main storview id number, in my case it was # 1.

then 
php7 bin/magento cache:clean
php7 bin/magento cache:enable

**Comment by magento-engcom-team** [comment]
@EmilyPepperman Thank you for your help.
@josecoelho509 Closing this ticket for now due to inactivity. Steps mentioned above would help most likely.

**Comment by edthomas1** [comment]
No these  steps never worked. The issue is not fixed, do you have other workaround?

Thanks
