### ISSUE TITLE
Abandoned cart emails are not sending the second time.

### ISSUE THREAD

**Issue by abhilashv** [magento/magento2#14983]
### Preconditions

1. Magento Enterprise 2.2.3

### Steps to reproduce

1. Create an abandoned cart rule in Market->Email reminders.
2. Abandon a cart with an user.
3. Abandoned cart email will be sent to the user with the details of the items
4. Add new products with the same user and abandon the cart again.
5. The user is not getting the abandoned cart mail the second time.

### Expected result

1. Every time an user abandons a cart, he should receive an email. This is working only once for an use account.

### Actual result

1. Abandoned cart mail is sent for an user the first time he abandons the cart. This is not happening the second time.

**Comment by engcom-backlog-nickolas** [comment]
@abhilashv, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
