### ISSUE TITLE
Could not proceed to checkout as guest (2.2.4)

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#14991]
### Preconditions
1. Magento 2.2.4
2. PHP 7.0.28

### Steps to reproduce
1. Go to admin
2. Enable "Allow guest checkout" under Store > Configuration > Sales > Checkout > Checkout Options
3. Flush the cache
4. Go to front-end as guest
5. Add something to cart
6. Click on PROCEED TO CHECKOUT from both mini cart or cart page

### Expected result
1. As guest checkout is allowed, it should not show popup but redirect to checkout page

### Actual result
2. Popup is shown

![screenshot_22](https://user-images.githubusercontent.com/4161312/39621521-56c93dde-4f8f-11e8-8cfc-a15c2346d262.png)

On 2.2.3 this was not the case.

**Comment by kerlama** [comment]
Hi,

any updates on this one , can someone reproduce this ?

Ivan

**Comment by RahulKachhadia** [comment]
@kerlama @magento-engcom-team I was able to replicate this on 2.2.4 during manual testing.

**Comment by hostep** [comment]
I cannot reproduce this following the steps from @kerlama on a clean 2.2.4 install. I don't see a popup and I'm redirected to the checkout.

@kerlama: can you try to reproduce this as well on a clean 2.2.4 without any customisations (no custom modules, no custom themes)? If you can find a way to reproduce, please let us know the exact steps. (Perhaps its another configuration setting which you didn't mention)

Thanks!

**Comment by kerlama** [comment]
Will try and let you know.

**Comment by kerlama** [comment]
Hi,
on clean installation it is working and somehow started to work on previous one too.

Ivan

**Comment by mitcht** [comment]
For anyone else who comes by, re-try using incognito mode and see if the problem goes away.  I had some persistent cookies between deployments that caused some issues.
