### ISSUE TITLE
"Start accepting payments via PayPal!" link goes to a 404

### ISSUE THREAD

**Issue by navarr** [magento/magento2#14998]
### Preconditions

1. Magento 2.2.5 installed

### Steps to reproduce

1. Login to admin panel
1. In sidebar, go to Stores->Configuration
2. In configuration, go to Sales->Payment Methods
3. Under "Recommended Solutions" click the "Configure" button for PayPal Express Checkout
4. Under Required PayPal Settings->Express Checkout, click the "Start accepting payments via PayPal!" link (located underneath "Email associated with paypal merchant account")

### Expected result

1. I am taken to a friendly page that helps me setup PayPal

### Actual result

1. I am taken to https://magento.com/paypal/overview via https://www.magentocommerce.com/paypal which results in a 404 error.

**Comment by ghost** [comment]
Hi @navarr i cannot reproduce, see attachments
![frame-03d](https://user-images.githubusercontent.com/40756439/43132221-bddbf9dc-8f43-11e8-9c83-b5b9d98eef4d.gif)

**Comment by navarr** [comment]
Instead of showing a 404 it looks like the Magento website just redirects to the homepage.

Should I revise the ticket?  The expected result still does not meet the actual result

@engcom-backlog-nazar

**Comment by ghost** [comment]
@navarr  No. its not a bug. click on ->  https://magento.com/paypal/overview  and  you  redirec to home page.
