### ISSUE TITLE
Class Pepperjam\\Network\\Model\\Config\\Source\\CommissioningCategory does not exist

### ISSUE THREAD

**Issue by oehTie** [magento/magento2#14996]
Magento 2.2.3, when adding a product i get the famous page: There has been an error processing your request. When looking up the log file i get this:

{"0":"Class Pepperjam\\Network\\Model\\Config\\Source\\CommissioningCategory does not exist","1":"#0 \/home\/username\/public_html\/vendor\/magento\/framework\/Code\/Reader\/ClassReader.php(19): ReflectionClass->__construct('Pepperjam\\\\Netwo...')\n#1 \/home\/username\/public_html\/vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php(44): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor('Pepperjam\\\\Netwo...')\n#2 \/home\/username\/public_html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(100): Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters('Pepperjam\\\\Netwo...')\n#3 \/home\/username\/public_html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Pepperjam\\\\Netwo...', Array)\n#4 \/home\/username\/public_html\/vendor\/magento\/framework\/Validator\/UniversalFactory.php(36): Magento\\Framework\\ObjectManager\\ObjectManager->create('Pepperjam\\\\Netwo...', Array)\n#5 \/home\/username\/public_html\/vendor\/magento\/module-eav\/Model\/Entity\/Attribute\/AbstractAttribute.php(590): Magento\\Framework\\Validator\\UniversalFactory->create('Pepperjam\\\\Netwo...')\n#6 \/home\/username\/public_html\/vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php(595): Magento\\Eav\\Model\\Entity\\Attribute\\AbstractAttribute->getSource()\n#7 \/home\/username\/public_html\/vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php(358): Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->setupAttributeMeta(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), 'product-details', 8)\n#8 \/home\/username\/public_html\/vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php(331): Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->getContainerChildren(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), 'product-details', 8)\n#9 \/home\/username\/public_html\/vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php(306): Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->addContainerChildren(Array, Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), 'product-details', 8)\n#10 \/home\/username\/public_html\/vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Eav.php(266): Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->getAttributesMeta(Array, 'product-details')\n#11 \/home\/username\/public_html\/vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/ProductDataProvider.php(73): Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Eav->modifyMeta(Array)\n#12 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php(302): Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\ProductDataProvider->getMeta()\n#13 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php(208): Magento\\Framework\\View\\Element\\UiComponentFactory->mergeMetadata('product_form', Array, false)\n#14 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(135): Magento\\Framework\\View\\Element\\UiComponentFactory->create('product_form', NULL, Array)\n#15 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(97): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->generateComponent(Object(Magento\\Framework\\View\\Layout\\Data\\Structure), 'product_form', Array, Object(Magento\\Framework\\View\\Layout\\Interceptor))\n#16 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php(80): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->process(Object(Magento\\Framework\\View\\Layout\\Reader\\Context), Object(Magento\\Framework\\View\\Layout\\Generator\\Context))\n#17 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout.php(344): Magento\\Framework\\View\\Layout\\GeneratorPool->process(Object(Magento\\Framework\\View\\Layout\\Reader\\Context), Object(Magento\\Framework\\View\\Layout\\Generator\\Context))\n#18 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout\/Builder.php(129): Magento\\Framework\\View\\Layout->generateElements()\n#19 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Page\/Builder.php(55): Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks()\n#20 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout\/Builder.php(65): Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks()\n#21 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout.php(254): Magento\\Framework\\View\\Layout\\Builder->build()\n#22 \/home\/username\/public_html\/vendor\/magento\/framework\/View\/Layout.php(875): Magento\\Framework\\View\\Layout->build()\n#23 \/home\/username\/public_html\/vendor\/magento\/module-backend\/Model\/View\/Result\/Page.php(26): Magento\\Framework\\View\\Layout->getBlock('menu')\n#24 \/home\/username\/public_html\/vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Product\/NewAction.php(71): Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu('Magento_Catalog...')\n#25 \/home\/username\/public_html\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction->execute()\n#26 \/home\/username\/public_html\/vendor\/magento\/module-backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#27 \/home\/username\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#28 \/home\/username\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->___callParent('dispatch', Array)\n#29 \/home\/username\/public_html\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(143): Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#30 \/home\/username\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#31 \/home\/username\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#32 \/home\/username\/public_html\/generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/NewAction\/Interceptor.php(26): Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#33 \/home\/username\/public_html\/vendor\/magento\/framework\/App\/FrontController.php(55): Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#34 \/home\/username\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#35 \/home\/username\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#36 \/home\/username\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#37 \/home\/username\/public_html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#38 \/home\/username\/public_html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#39 \/home\/username\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#40 \/home\/username\/public_html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#41 {main}","url":"\/admin_secret\/catalog\/product\/new\/set\/4\/type\/simple\/key\/cd0947d7dc5853c7a97670c91f3b3c7774a85cf4675e8f8d8cba2862536e7c15\/","script_name":"\/index.php"}

any clue how to fix this? 

regards,

Theo

**Comment by ishakhsuvarov** [comment]
Hi @oehTie 
Looks like the issue is caused by one of the installed extensions. Please contact vendor directly for support. We can only look into issues related to Magento 2 core.

**Comment by oehTie** [comment]
I thought so too at first... but when i look at extensions.... there is no pepperjam thing.....

**Comment by ishakhsuvarov** [comment]
@oehTie Any code with `Pepperjam` namespace is not included into magento core as well.
