### ISSUE TITLE
[2.2.4] Gallery theme variables being ignored

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#15009]
(Some) Variables set in the theme's view.xml for the gallery widget appear to be ignored in 2.2.4 (This may also affect other variables, I don't know)

### Preconditions
1. Magento 2.2.4 installed from git
2. No modules
3. Single website, theme set to luma

### Steps to reproduce
1. Create product and assign product image, ensuring you set the AltText for the image
2. View product on frontend

### Expected result
1. as the luma theme sets the variable gallery/caption to false the AltText should not be displayed on the gallery widget.

### Actual result
1. The product image has the AltText displayed at the bottom.

This is new behaviour in 2.2.4. 2.2.3 did not do this.

I also have some other third party code that throws a wobbler, when it looks for the variable gallery/fullscreen/navarrows which it says does not exist, even though it is also declared in lumas view.xml

**Comment by gwharton** [comment]
Debugging from within magento/framework/Config/view.php

```
    [vars] => Array
        (
            [Magento_Catalog] => Array
                (
                    [gallery] => Array
                        (
                            [nav] => thumbs
                            [loop] => 1
                            [keyboard] => 1
                            [arrows] => 1
                            [caption] => 
                            [allowfullscreen] => 1
                            [navdir] => horizontal
                            [navarrows] => 1
                            [navtype] => slides
                            [transition] => Array
                                (
                                    [effect] => slide
                                    [duration] => 500
                                )

                            [fullscreen] => Array
                                (
                                    [nav] => thumbs
                                    [loop] => 1
                                    [arrows] => 1
                                    [caption] => 
                                    [navdir] => horizontal
                                    [navtype] => slides
                                    [transition] => Array
                                        (
                                            [effect] => slide
                                            [duration] => 500
                                        )

                                    [navarrows] => 
                                )

                        )
                 )
          )

```
Notice that both Caption and Navarrows are empty, even though in the theme file

```
        <var name="gallery">
            <var name="nav">thumbs</var> <!-- Gallery navigation style (false/thumbs/dots) -->
            <var name="loop">true</var> <!-- Gallery navigation loop (true/false) -->
            <var name="keyboard">true</var> <!-- Turn on/off keyboard arrows navigation (true/false) -->
            <var name="arrows">true</var> <!-- Turn on/off arrows on the sides preview (true/false) -->
            <var name="caption">false</var> <!-- Display alt text as image title (true/false) -->
            <var name="allowfullscreen">true</var> <!-- Turn on/off fullscreen (true/false) -->
            <var name="navdir">horizontal</var> <!-- Sliding direction of thumbnails (horizontal/vertical) -->
            <var name="navarrows">true</var> <!-- Turn on/off on the thumbs navigation sides arrows(true/false) -->
            <var name="navtype">slides</var> <!-- Sliding type of thumbnails (slides/thumbs) -->
            <var name="transition">
                <var name="effect">slide</var> <!-- Sets transition effect for slides changing (slide/crossfade/dissolve) -->
                <var name="duration">500</var> <!-- Sets transition duration in ms -->
            </var>
            <var name="fullscreen">
                <var name="nav">thumbs</var> <!-- Fullscreen navigation style (false/thumbs/dots) -->
                <var name="loop">true</var> <!-- Fullscreen navigation loop (true/false/null) -->
                <var name="arrows">true</var> <!-- Turn on/off arrows on the sides preview in fullscreen (true/false/null) -->
                <var name="caption">false</var> <!-- Display alt text as image title in fullscreen(true/false) -->
                <var name="navdir">horizontal</var> <!--Sliding direction of thumbnails in fullscreen(horizontal/vertical)  -->
                <var name="navarrows">false</var> <!-- Turn on/off on the thumbs navigation sides arrows(true/false) -->
                <var name="navtype">slides</var> <!-- Sliding type of thumbnails (slides/thumbs) -->
                <var name="transition">
                    <var name="effect">slide</var> <!-- Sets transition effect for slides changing (slide/crossfade/dissolve) -->
                    <var name="duration">500</var> <!-- Sets transition duration in ms -->
                </var>
            </var>
        </var>

```

It would appear that any item set to false, is not being read properly.

**Comment by gwharton** [comment]
And here is the culprit

https://github.com/magento/magento2/commit/ccc35c24de7b27d5e3cd4e42bdbfd57f8ce6de9d#diff-79786eac5b88f578b5d99c9ca046d4af

Broken during fix applied for #12285

**Comment by gwharton** [comment]
Should be aware that the changes applied in #12285 were only applied to 2.2-develop and not 2.3-develop. Therefore 2.3-develop continues to use the strings "true" and "false" for boolean config variables and therefore does not require this fix.

Update : I have created forwardports of the 12285 fix into 2.3 so they stay in sync

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#15022 by @gwharton in 2.3-develop branch
Related commit(s):
 - [163d4cc63d19c3a3bd94697dd02c0d96696df799](https://github.com/magento/magento2/commit/163d4cc63d19c3a3bd94697dd02c0d96696df799)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#15020 by @gwharton in 2.2-develop branch
Related commit(s):
 - [8ef039ec281a7fc6af014b42fc69a9d77e4bf277](https://github.com/magento/magento2/commit/8ef039ec281a7fc6af014b42fc69a9d77e4bf277)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#16594 by @gwharton in 2.2-develop branch
Related commit(s):
 - [a012c45166619554619691b996d4474ed6278bfb](https://github.com/magento/magento2/commit/a012c45166619554619691b996d4474ed6278bfb)

The fix will be available with the upcoming 2.2.7 release.

**Comment by leoquijano** [comment]
Hi @sidolov ,

It seems that the fix wasn't included in the 2.2.7 or the 2.2.8 releases. Can this be included in a future 2.2.x release?

**Comment by gwharton** [comment]
Take a look at 2.2-develop. The whole gallery json code has been reworked and should be much improved in next release.

**Comment by leoquijano** [comment]
Thanks @gwharton. I'm just wondering if the patch is going to be included in an official release. Since it's a bug, I think it can be included in 2.2.9 or 2.2.10, right?

**Comment by gwharton** [comment]
Check out #18443. Already merged into 2.2-develop. Will be in 2.2.9. It rewrites all the code causing these issues.

**Comment by leoquijano** [comment]
I see!

Looking into it. This is very helpful. Thanks!

**Comment by choleaoum** [comment]
I'm currently running 2.3.4 (Bitnami w/ Smartwave's Porto Theme) and this issue appears to still be happening. It's a fresh install.
