### ISSUE TITLE
User can not configure or set theme from admin side

### ISSUE THREAD

**Issue by ghost** [magento/magento2#15008]
I create the custom theme and try to configure with Magento v 2.2.4 but I can not set my theme.

### Preconditions

1.Magento 2.2.4 with sample data 

### Steps to reproduce

1. Install Magento v 2.2.4 with sample data 
2. Go to admin side **Content > Configuration**
3. Edit the default store view 
4. From **" Applied Theme"** chouse custom theme or luma theme 
5. The user can not save the theme 

### Expected result

1. The user can set his/her custom theme 

### Actual result

Discplay error message 

> Something went wrong while saving this configuration: Area is already set

1. [Screenshot, logs]

![theme_set_error](https://user-images.githubusercontent.com/2203580/39663289-2c04b36c-508e-11e8-8762-34374a5390d6.png)

**Comment by mail4sheik** [comment]
+1

**Comment by hostep** [comment]
@emiprotech: thanks for the report, but it has already been reported a couple of times before, so I'm closing this in favor of https://github.com/magento/magento2/issues/14968. If you don't agree, please let me know.

**Comment by tejasshyani** [comment]
Facing same issue.. :(

**Comment by faniuta** [comment]
same issue in ver 2.2.5

**Comment by jimuld** [comment]
+1
