### ISSUE TITLE
Magento 2.2.4 Product page image not loading after upgrade

### ISSUE THREAD

**Issue by PeterDab** [magento/magento2#15007]
Upgrade Magento 2.2.3 to Magento 2.2.4 and product image on Product page failing to load

Magento version 2.2.4
PHP 7.0.27
MySQL 5.0.12

Opened product page
Image failing to load
![screenshot_20180505_213722](https://user-images.githubusercontent.com/7949699/39662909-c3ecc0ac-50ac-11e8-8990-9b2534a3d879.png)

**Comment by gwharton** [comment]
open up the firefox developer console. This behaviour is normally due to some javascript failing to initialise.

**Comment by gwharton** [comment]
I had this after upgrading to 2.2.4. It was a third party module that was trying to access the gallery/fullscreen/navarrows option which was failing, resulting in it outputting badly formatted javascript for the gallery widget.

In my case, the problem was related to #15009

**Comment by PeterDab** [comment]
Thanks, looks like my issue is probably is related to third party extension. I have notified the authors so hopefully should have solution shortly.
![screenshot_20180506_000606](https://user-images.githubusercontent.com/7949699/39664512-a1986aea-50c7-11e8-9192-e23749a4a155.png)

**Comment by gwharton** [comment]
Yes, the Swissup Lightbox Pro module is the module that I had the issue with. Their support is aware of the issue and will issue you with a temporary fix until their next release.

**Comment by gwharton** [comment]
Although the root cause of this issue is #15009, it is related to code in a third party module, hence closed.
