### ISSUE TITLE
cookies issue in merchant beta

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1500]
a:4:{i:0;s:71:"Unable to send the cookie. Maximum number of cookies would be exceeded.";i:1;s:1451:"#0 /var/www/html/magento2/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php(272): Magento\Framework\Stdlib\Cookie\PhpCookieManager->checkAbilityToSendCookie('X-Magento-Vary', '')
#1 /var/www/html/magento2/lib/internal/Magento/Framework/App/Response/Http.php(83): Magento\Framework\Stdlib\Cookie\PhpCookieManager->deleteCookie('X-Magento-Vary', Object(Magento\Framework\Stdlib\Cookie\CookieMetadata))
#2 /var/www/html/magento2/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(37): Magento\Framework\App\Response\Http->sendVary()
#3 /var/www/html/magento2/app/code/Magento/PageCache/Model/App/Response/HttpPlugin.php(22): Magento\Framework\App\Response\Http\Interceptor->sendVary()
#4 [internal function]: Magento\PageCache\Model\App\Response\HttpPlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#5 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(122): call_user_func_array(Array, Array)
#6 /var/www/html/magento2/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#7 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Response\Http\Interceptor->sendResponse()
#8 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}";s:3:"url";s:45:"/magento2/index.php/promotions/pants-all.html";s:11:"script_name";s:19:"/magento2/index.php";}

**Comment by sivajik34** [comment]
once i deleted browser cookies..its working fine.sorry.

**Comment by rhoerr** [comment]
I've experienced the same error on multiple occasions. I think there's clearly an issue here--the system should never get itself into a state where cookies have to be deleted.

Looks like something is creating a whole bunch of m2e_bn_* cookies, not clear what or why.

**Comment by rjung-guidance** [comment]
I wonder if the browser could be a factor?  I ran into the same problem today while using Safari 8.0.7, and I've seen some discussion about Safari having a bug where cookies do not get deleted properly...?

**Comment by rjung-guidance** [comment]
I put in some logging statements into checkAbilityToSendCookie(), then triggered the error.  Here is what I got:

rjung [5:16 PM]5:16
$name = X-Magento-Vary
$value = 
$_COOKIE = Array
(
   [form_key] => MXKIufMdsRuCIVNx
   [PHPSESSID] => 7is7gk92o0drp9u5of3m0nobj6
   [mage-cache-sessid] => true
   [mage-cache-storage] => {}
   [mage-cache-storage-section-invalidation] => {}
   [message_box_display] => 1
   [__unam] => 6ccb56c-14eae2230e7-76583c6e-62
   [__utma] => 196003514.420996769.1437509046.1438734904.1438808049.15
   [__utmc] => 196003514
   [__utmz] => 196003514.1437522712.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
   [_ga] => GA1.2.420996769.1437509046
   [calltrk_landing] => http://gry2.dev.guidance.com/
   [calltrk_referrer] => direct
   [cid6456bid] => 00170000023D1AB8-B
   [GSIDmVglfQzS5MB1] => 88a98ab3-42e0-480b-9221-c22b871f0e15
   [GSIDODxqBTmWZaOU] => 4ab1c25a-723f-4c92-8b3e-dfed6b031bbd
   [ltkmodal-suppression-b4f526aa-eb26-4e4d-850b-da3fcfd79fe0] => Fri Sep 04 2015 12:00:00 GMT-0700 (PDT)
   [ltkmodal-suppression-c42c001c-8a1c-4ef1-86ef-1dc3bade6efa] => Wed Aug 19 2015 18:02:33 GMT-0700 (PDT)
   [MM_GUID] => cc2de97e-0caa-1609-2b58-3b6e4c473e29
   [MM_UUID] => 2B4A6CDE-07DD-4DB8-8E4D-95246E0DEE32
   [STSD745428] => 0
   [STSD757424] => 0
   [STSID745428] => ab06bcf6-08d0-4bdf-92ab-279741cd71b1
   [STSID757424] => fd3592a7-d38d-4845-94a9-36f7aaadbcfa
)

rjung [5:19 PM]
Hitting the site with a different browser (that doesn't have the problem) gives me this:

rjung [5:19 PM]
$name = X-Magento-Vary
$value = 
$_COOKIE = Array
(
   [_ga] => GA1.2.1295140289.1438035155
   [cid6456bid] => 001800000229828E-9
   [SESS3e9e66fd0e16ace98e59ea3c9fa21406] => jq755PIZXXolcf1Y_swcuyMdLprevY0BwmtuaeBK8Gk
   [__utma] => 196003514.1295140289.1438035155.1438644177.1438720594.2
   [__utmz] => 196003514.1438644177.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
   [form_key] => zqNp7jLqgPHWEJjU
)

**Comment by piotrekkaminski** [comment]
@sivajik34 can you still reproduce this error on the latest version?

**Comment by lijithmg** [comment]
I do replicated this issue today.

**Comment by dougkm** [comment]
@tkacheva - Please take a look at this issue

**Comment by tkacheva** [comment]
MAGETWO-44630

**Comment by dsikkema** [comment]
Has anyone seen this issue in browsers other than safari?

@rjung-guidance if you upgrade to safari 9, do you see the issue?

**Comment by rjung-guidance** [comment]
I am experiencing this problem with Safari 9.0.1.

I do not know if it occurs with other browsers, but I believe the issue is related to having multiple subdomains in a development environment (project1.mycompany.com<http://project1.mycompany.com>, project2.mycompany.com<http://project1.mycompany.com>, etc.).

-------
Robert Jung, Technical Lead
310 754 3121 direct | 310 754 4000 main
[http://www.guidance.com/sites/default/files/guidance_email_logo.png]
4134 Del Rey Avenue
Marina del Rey, CA 90292
guidance.com<http://guidance.com> | @guidance

On Oct 30, 2015, at 11:31 AM, dsikkema <notifications@github.com<mailto:notifications@github.com>> wrote:


Has anyone seen this issue in browsers other than safari?

@rjung-guidance<https://github.com/rjung-guidance> if you upgrade to safari 9, do you see the issue?

**Comment by dsikkema** [comment]
Thanks, @rjung-guidance. Can you tell me if the string "magento.com" appears in the urls of your development domains? I'm noticing that many of the cookies being reported are set by magento.com, which is a site that I'm sure most people in the magento community frequent, and so domains ending in "magento.com" are picking up cookies from what looks like the same domain.

**Comment by dsikkema** [comment]
Open question to everyone who has experienced the issue: does the domain for your magento instance end in "magento.com", and can you please post the cookies that are set by checking the value $_COOKIE array in \Magento\Framework\Stdlib\Cookie\PhpCookieManager::checkAbilityToSendCookie, or by using developer mode in the browser to show all cookies that are set for that domain?

**Comment by rjung-guidance** [comment]
No, none of my development domains use the string "magento.com<http://magento.com>" anywhere.

-------
Robert Jung, Technical Lead
310 754 3121 direct | 310 754 4000 main
[http://www.guidance.com/sites/default/files/guidance_email_logo.png]
4134 Del Rey Avenue
Marina del Rey, CA 90292
guidance.com<http://guidance.com> | @guidance

On Oct 30, 2015, at 12:00 PM, dsikkema <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, @rjung-guidance<https://github.com/rjung-guidance>. Can you tell me if the string "magento.com<http://magento.com>" appears in the urls of your development domains? I'm noticing that many of the cookies being reported are set by magento.com<http://magento.com>, which is a site that I'm sure most people in the magento community frequent, and so domains ending in "magento.com<http://magento.com>" are picking up cookies from what looks like the same domain.

**Comment by dsikkema** [comment]
Ok, in that case I think you're right about this: "I believe the issue is related to having multiple subdomains in a development environment."

I'm seeing a lot of cookies in your $_COOKIES array that I don't think are set by magento. For example:
 * cid6456bid
 * __utma

I think the main domain is setting them. If you're development environment is "project1.mycompany.com", can you check "mycompany.com" to see if they are setting cookies for all subdomains under "*.*mycompany.com"?

**Comment by samm-git** [comment]
WTF, why do we have that at all?

```
    /**#@+
     * Constants for Cookie manager.
     * RFC 2109 - Page 15
     * http://www.ietf.org/rfc/rfc2109.txt
     */
    const MAX_NUM_COOKIES = 20;
    const MAX_COOKIE_SIZE = 4096;
    const EXPIRE_NOW_TIME = 1;
    const EXPIRE_AT_END_OF_SESSION_TIME = 0;
    /**#@-*/
```

Could you please read rfc once again? This is NOT strict limit!
```
6.3  Implementation Limits

   Practical user agent implementations have limits on the number and
   size of cookies that they can store.  In general, user agents' cookie
   support should have no fixed limits.  They should strive to store as
   many frequently-used cookies as possible.  Furthermore, general-use
   user agents should provide each of the following minimum capabilities
   individually, although not necessarily simultaneously:

      * at least 300 cookies

      * at least 4096 bytes per cookie (as measured by the size of the
        characters that comprise the cookie non-terminal in the syntax
        description of the Set-Cookie header)

      * ***at least*** 20 cookies per unique host or domain name
```

**Comment by samm-git** [comment]
jfyi, it is lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php

**Comment by samm-git** [comment]
Same is valid for 4096 length check. *at least*, not maximum!

**Comment by gordonknoppe** [comment]
Public tool which can help define sane minimums for modern browsers: http://browsercookielimits.squawky.net/

**Comment by samm-git** [comment]
Also RFC 2109 is obsoleted in 2011, see http://www.rfc-editor.org/info/rfc2109. Valid one is rfc6265 which sets ***at least 50 cookies per domain*** requirement. So in fact Magento violates RFC here.

**Comment by dfediuk** [comment]
I agree the limit should be increased [up to `50`](https://mage2.pro/t/84/2).

**Comment by gordonknoppe** [comment]
This has been done in both merchant_beta and GA.  Issue can be closed.

**Comment by dmitrii-fediuk** [comment]
Yes, it is fixed in the current release: https://github.com/magento/magento2/blob/2.0.0/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php#L29

**Comment by dmitrii-fediuk** [comment]
It was fixed 5 days ago but became available yesterday: https://github.com/magento/magento2/commit/c945dbe42e5947e29fb977fd44300730e5c46bb7#diff-69abf748a729353f99cd623615fecd9d
