### ISSUE TITLE
Tax price wrong in magento 2.1.1

### ISSUE THREAD

**Issue by 2base** [magento/magento2#15006]
### Preconditions

1. Magento 2.1.1

### Steps to reproduce

1. Create a product with price £100 (including tax)
2. Add a Tax rate/rule which applies 10% tax to the product
3. Set [Stores > Configuration > Sales > Tax > Calculation Settings > Catalog Prices] to "Including Tax"
4. Set [Stores > Configuration > Sales > Tax > Price Display Settings > Display Product Prices In Catalog] to "Including Tax"
5.Refresh caches

### Expected result
1. Subtotal	₹100
  Shipping (Shipping Rate - Postal Charge)	₹60
  Tax	 ₹10
  Order Total Incl. Tax	₹160
  Order Total Excl. Tax	₹150

### Actual result
1. Subtotal	₹100
   Shipping (Shipping Rate - Postal Charge)	₹60
   Tax	₹9
   Order Total Incl. Tax	₹160
   Order Total Excl. Tax	₹151

![shopping cart](https://user-images.githubusercontent.com/34031224/39661696-a854c8e6-5073-11e8-80f3-b763bd28a84b.png)
![configuration settings stores magento admin](https://user-images.githubusercontent.com/34031224/39661712-e28b610a-5073-11e8-9089-a5568e5af8e6.png)

**Comment by tomekjordan** [comment]
Try to Tax Calculation Method Based On > change to Row Total and you will different results

**Comment by 2base** [comment]
@tomekjordan, Thank you so much for the help.

It's working fine!!

**Comment by ghost** [comment]
Hi @2base  colse issue by @tomekjordan  comment.
