### ISSUE TITLE
Print FedEx Request XML Magento 2

### ISSUE THREAD

**Issue by salerpsan** [magento/magento2#15004]
I need to print the FedEx XML request to check what are the values  Magento 2 is posting to the carrier.
Anybody know how can I do it?
Thank you!

**Comment by magento-engcom-team** [comment]
@salerpsan 
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
