### ISSUE TITLE
Memory fragmentation in Rule Indexer (and proposal)

### ISSUE THREAD

**Issue by george-vlahakis** [magento/magento2#15005]
We have 20.000 products and 500 catalog rules. We found that running the Rules Indexer was taking a considerable time but most of all was reaching up to **8G** memory consumption to try and complete the task.

Put simply, it was killing us.

Running through various parts of the code trying to identify if it is a code issue (or otherwise) we found that:

In vendor/magento/module-catalog-rule/Model/Rule.php the call to collect validated attributes was loading an instance with 20.000 values in the array and not releasing it. Quite likely an issue with PHP (see version below) but we did try other versions for sanity.

Even after forcing GC and so forth, PHP continued to hold memory in each iteration.

Not sure if you can call it a bug cause the code does not actually do anything wrong from what we can see but definitely an improvement for all of us trying to run Magento with reasonable RAM specifications.

```
    /**
     * Get array of product ids which are matched by rule
     *
     * @return array
     */
    public function getMatchingProductIds()
    {
        if ($this->_productIds === null) {
            $this->_productIds = [];
            $this->setCollectedAttributes([]);
            if ($this->getWebsiteIds()) {
                /** @var $productCollection \Magento\Catalog\Model\ResourceModel\Product\Collection */
                $productCollection = $this->_productCollectionFactory->create();
                $productCollection->addWebsiteFilter($this->getWebsiteIds());
                if ($this->_productsFilter) {
                    $productCollection->addIdFilter($this->_productsFilter);
                }
                $this->getConditions()->collectValidatedAttributes($productCollection); // <<-HERE

                $this->_resourceIterator->walk(
                    $productCollection->getSelect(),
                    [[$this, 'callbackValidateProduct']],
                    [
                        'attributes' => $this->getCollectedAttributes(),
                        'product' => $this->_productFactory->create()
                    ]
                );
            }
        }

        return $this->_productIds;
    }
```

**Proposal**

In order to solve the problem we actually found that forcibly setting the _conditions member to null after each iteration kept the memory at bay and now can run (still rather slow) the whole process with PHP not exceeding 150Mb!

In vendor/magento/module-catalog-rule/Model/Rule.php:
```
    /** Force memory release? */
    public function clear()
    {
        $this->_productIds = null;
        $this->_productsFilter = null;
        $this->_resourceIterator = null;
        $this->_conditions= null;
    }
```

In vendor/magento/module-catalog-rule/Model/Indexer/IndexBuilder.php

```
    /**
     * Full reindex Template method
     *
     * @return void
     */
    protected function doReindexFull()
    {
        $this->connection->truncateTable(
            $this->getTable($this->activeTableSwitcher->getAdditionalTableName('catalogrule_product'))
        );
        $this->connection->truncateTable(
            $this->getTable($this->activeTableSwitcher->getAdditionalTableName('catalogrule_product_price'))
        );

        foreach ($this->getAllRules() as $rule) {
            $this->reindexRuleProduct->execute($rule, $this->batchCount, true);
            $rule->clean();  // <-- HERE
        }

        $this->reindexRuleProductPrice->execute($this->batchCount, null, true);
        $this->reindexRuleGroupWebsite->execute(true);

        $this->activeTableSwitcher->switchTable(
            $this->connection,
            [
                $this->getTable('catalogrule_product'),
                $this->getTable('catalogrule_product_price'),
                $this->getTable('catalogrule_group_website')
            ]
        );
    }
```

### Preconditions
1. Magento 2.2.0
2. PHP 7.0.27 (tried also 7.1.12)
3. Ubuntu 16

### Steps to reproduce
1. Using Magento 2 Performance Toolkit, generate 20000 Simple Products and 500 Catalog Rules.
2. Reindex catalogrule_rule

### Expected result
1. Reasonable memory consumption

### Actual result
1. Unacceptable memory consumption

We have seen this in various parts where PHP is failing to clean up for itself and hope that you can point us to a more stable version, but given there is a workaround to get reasonable memory usage, feel that some form of consideration (and confirmation) of the problem would be in place.

At least so that we dont go completely mad.

**Comment by thiagolima-bm** [comment]
@georgios-2317 Are you going to create a PR for this?

**Comment by george-vlahakis** [comment]
@thiagolima-bm I am not sure of the procedures behind making a PR to be honest. Would love to help but will need guidance here. Sharing of our local changes was to show how we went around it but usually Magento team is rather strict in terms of what actually goes into the repo.

Again, if the team feels it is fine happy to make a PR

**Comment by thiagolima-bm** [comment]
@georgios-2317 
First of all, you need to fork the Magento repository.

Then, in your local environment, you should create a branch off of "2.3-develop" or any other branch you seem it applies.

For this issue, I would do this:

`git checkout -b issue#15005 upstream/2.3-develop`

work on the changes

`git add  (files to be committed)`
`git commit -m "Memory fragmentation in Rule Indexer (and proposal) #15005"`
`git push origin issue#15005`

After that, you can go to your forked repository here on GitHub and follow the steps:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by ghost** [comment]
@georgios-2317, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by george-vlahakis** [comment]
Hello @engcom-backlog-pb , thank you for responding but I feel I have given as much info as I can possibly give to allow you to replicate. If you have specific questions fire away, but I cannot guess what you mean by detailed instructions. I believe I mentioned 400+ rules running on 20.000+ products will whilst processing will cause memory to keep growing in each pass (and each pass stores 20K product ids at minimum in a memory array which for some reason php is not releasing even though the loop instantiates a new version). Tried garbage collection with no luck.

**Comment by ghost** [comment]
@georgios-2317 I have only near 300 Mb max memory consumption when reindexing with 20000 simple products and 500 Catalog Rules.

**Comment by george-vlahakis** [comment]
What can I say @engcom-backlog-pb ... that was definitely not the case in 4 setups I had trying this out. I think I gave all versions related here. 

As an observation 300Mb is rather low if you are indeed running the rules indexers because at very minimum each rule will load all product ids into memory and parse them and quickly go to the next rule. So I am guessing you should at very minimum be seeing RAM consumption grow at each iteration of a catalog rule being processed. 

If you wish to know more about the rules themselves, I can say that they are all discounts % based on product category (is-in)

Hope it helps.

**Comment by ghost** [comment]
@georgios-2317, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mslabko** [comment]
@georgios-2317 , we have optimized catalog rule indexation, which will be available in 2.2.6 release. Can you please check this commit for your case?
https://github.com/magento/magento2/commit/8b36f39e432399ba06439928f0f0637798c35fbe

**Comment by george-vlahakis** [comment]
> @georgios-2317 , we have optimized catalog rule indexation, which will be available in 2.2.6 release. Can you please check this commit for your case?
> [8b36f39](https://github.com/magento/magento2/commit/8b36f39e432399ba06439928f0f0637798c35fbe)

Thank you @mslabko .. will do with first opportunity (cant promise it will be soon as I see there's a few changes there we need to check for compatibility)

**Comment by sdzhepa** [comment]
Hello @georgios-2317 

Any updates after applying 8b36f39 ?
Probably the issue is already fixed and we can close this ticket

**Comment by ihor-sviziev** [comment]
Hi @george-vlahakis,
Unfortunately, we didn't get any response from your for more than 1 year.
I'm closing this issues as not relevant anymore. If this issue still reproducing for you - please just put some comment here or cre
