### ISSUE TITLE
Issue with url_rewrite

### ISSUE THREAD

**Issue by vlad-brosolutions** [magento/magento2#15029]
Hi There!

I want to clear url_rewrite table and regenerate products and categories urls :)
And I got issue exactly like this https://github.com/magento/magento2/issues/11102

So seems I cant delete old rows in table and this looks very strange, cause I do not uderstand what for I need to store billions of unneeded rows in db??
Maybe there exist some best practice how to work with(regenerate) url rewrites and somebody could point me to a good article?

Thank you,
Vlad.

**Comment by magento-engcom-team** [comment]
@vlad-brosolutions 
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
