### ISSUE TITLE
Incorrect stock status for bundles

### ISSUE THREAD

**Issue by ipsperoteck** [magento/magento2#15036]
### Preconditions

1. Magento ver. 2.1.9

### Steps to reproduce

1. Create a bundle according to the official docs - http://docs.magento.com/m2/ce/user_guide/catalog/product-create-bundle.html 
2. Set "Qty" = "0" for all simple products inside the bundle
3. Set "Backorders" = "Allow Qty Below 0" for all simple products inside the bundle
4. Set "Stock Status" = "In Stock" for all simple products inside the bundle
5. Set "Stock Status" = "In Stock" for the bundle

### Expected result

1. The bundle should be available for ordering on a storefront

### Actual result

1. The bundle is shown as "Out of Stock" on a storefront

**Comment by ghost** [comment]
Hi @ipsperoteck The fix for this issue has already in 2.2-develop branch
