### ISSUE TITLE
Typo / unneccessary string in billing input elements?

### ISSUE THREAD

**Issue by blindmancs** [magento/magento2#1504]
Before the new checkout came in, all billing checkout elements had the name of
billingAddress[*name*]
However right now an extra bit dropped in for all elements.
For example,
billingAddresscheckmo[postcode]
Is this intentional or a typo?

**Comment by vpelipenko** [comment]
Hi @blindmancs, it is not a type. It was done intentional. Do you have another questions?

**Comment by blindmancs** [comment]
Thanks, that's all then.
I just wanted to keep an eye on this for module development / update purposes.
