### ISSUE TITLE
Email template subjects in foreign language become question marks when saved

### ISSUE THREAD

**Issue by jsdupuis** [magento/magento2#15049]
### Preconditions
1. Magento 2.2.4 (upgraded from Magento 2.1.12 successfully)

### Steps to reproduce
1. Go to Marketing -> Email Templates
2. Edit any template
3. Put Thai characters in the subject line like "{{trans "ยืนยันคำสั่งซื้อหมายเลข #%increment_id" increment_id=$order.getIncrementId()}}"
4. Save

### Expected result
1. Thai characters are readable (we had no problems in 2.1.12)

### Actual result
1. {{trans "??????????????????????? #%increment_id" increment_id=$order.getIncrementId()}}

After upgrading to 2.2.4, we lost all our Thai subject lines. We are forced to put them in English for the time being.

**Comment by galanis-a** [comment]
This issue is also reproduced in Magento 2.2.3 with greek characters.

**Comment by thanasisgalanis** [comment]
I confirm this issue too, in 2.2.3.

**Comment by thanasisgalanis** [comment]
Before change any record from Marketing -> Email Templates, the records in the database is ok, but in the grid all subject's characters that are note latin (i.e. Greek letters) appear as the issue "Actual result".
After change any record, this record saved as the issue "Actual result" in the database too.
This is also true for the characters out of {{trans  }}
(i.e. "ΑΒΓΔΕ{{trans ΑΒΓΔΕ}}" --> "?????{{trans ?????}}")

**Comment by magento2pl** [comment]
same in 2.2.5

**Comment by ghost** [comment]
Hi @jsdupuis  the fix for this issue has already been in 2.2-develop branch
![selection_021](https://user-images.githubusercontent.com/40756439/42559429-bd4098da-84fc-11e8-921d-7d00979cdb3f.png)

**Comment by isitnikov** [comment]
Issue doesn't related to Magento code. Can be reproduced even on the 2.2-develop, if you enable Dotmailer extension.

**INFO:**
Caused by *vendor/dotmailer/dotmailer-magento2-extension/Plugin/TemplatePlugin.php*
LINES: 103-105
```
...
                    if ($field == 'template_subject') {
                        $result = utf8_decode($result);
                    }
...
```

**Comment by ameshca** [comment]
Any solution got for this issue? this issue is still present in 2.2.6
