### ISSUE TITLE
Export of all entries stopped work after update to 2.2.4

### ISSUE THREAD

**Issue by caww** [magento/magento2#15046]
### Preconditions

PHP 7.1
Magento 2.2.4

### Steps to reproduce

Export of all entries of the list is STOPPED working totally
Go to any grid and try to export all (if more than page of course) I have 1800
If exporting a current page - export is working fine

### Expected result
Export for all entries must gave CSV file

### Actual result

error Exception #0 (Exception): Notice: Undefined offset: 0

**Comment by ghost** [comment]
@caww, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
