### ISSUE TITLE
M2C 2.2.3 Configurable product - special price does not display on Category page and Product page

### ISSUE THREAD

**Issue by devhelp37** [magento/magento2#15043]
### Preconditions

1.  Magento version 2.2.3. 
2.  Php - 7.1.16

### Steps to reproduce

1.  Add product as usual and set the special price for the product.
2.  Add variations for size by adding under size attribute (Custom created size attribute)
3.  Create the product listing.
4.  Once product is created, flush all the cache and check listing. Listing is successfully created with all the variations. 
5.  Under Category page, cant see special price and original price together. It directly shows only special price. When we click on the product, it goes to the product page. Before clicking any attribute, it still shows only special price directly but does not show any original price. Once click any size attribute, can see both original size and also special price in product page only.Category page never displays original price at all.

### Expected result

1.  Special price should be shown along with Original price in category page and also product page before clicking on any attributes.

### Actual result

1. Directly special price is shown everywhere on category page and also product page.

**Comment by engcom-backlog-nickolas** [comment]
Hello @devhelp37, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by PaulWMF** [comment]
Is there any update on this @engcom-backlog-nickolas ? We are experiencing this issue on a current M2C 2.2.3 build and need it solved before launch.

**Comment by engcom-backlog-nickolas** [comment]
Hello @PaulWMF, as configurable product price depends on price of it's children and configurable itself has no own price, it should not have it's own special price too. 
So, currently there is a bug when you converting simple product with special price to configurable, Special price remains on configurable product, which leads to confusion on category page, where you see configurable special price instead of option price  and on PDP, where you can see both: configurable special price and option price. Which, for instance, never happen in case you create configurable product from the beginning without conversion.
Therefore, when it will be fixed, there will be no ability to see both: special and option price on category page in vanilla magento. And it's correct behaviour.
If You want to see both prices on category page with configurable product, it would be better to implement custom solution, or try to find some 3d-party extensions which may provide such functionality.

Best regards!

**Comment by PaulWMF** [comment]
@engcom-backlog-nickolas we fixed this by:

Overriding `vendor/magento/module-configurable-product/view/base/templates/product/price/final_price.phtml`

1. Removed the condition to check is product isn't in a list

From: 
```PHP
<?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
```

To: 
```PHP
<?php if ($block->hasSpecialPrice()): ?>
```

2. Removed 'no-display' class from regular price span

From:
```PHP
<span class="old-price sly-old-price no-display">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
```

To: 
```PHP
<span class="old-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
```

**Comment by terrybakshi** [comment]
@engcom-backlog-nickolas Can you please explain, why do we have to keep using third party extensions for every basic thing, if this is the case, better leave magento as is and tell people it all depends now on third party extensions to complete everything you need in magento. Also issue relating the special pricing in configurable products is important if you have Google product feed extension as special pricing has been set in the product feed extension to display that pricing in google.

**Comment by darren-halo** [comment]
#9322 worked for me in 2.2.5

**Comment by shashankaugurs** [comment]
> @engcom-backlog-nickolas we fixed this by:
> 
> Overriding `vendor/magento/module-configurable-product/view/base/templates/product/price/final_price.phtml`
> 
> 1. Removed the condition to check is product isn't in a list
> 
> From:
> 
> ```
> <?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
> ```
> 
> To:
> 
> ```
> <?php if ($block->hasSpecialPrice()): ?>
> ```
> 
> 1. Removed 'no-display' class from regular price span
> 
> From:
> 
> ```
> <span class="old-price sly-old-price no-display">
>         <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
>             'display_label'     => __('Regular Price'),
>             'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
>             'price_type'        => 'oldPrice',
>             'include_container' => true,
>             'skip_adjustments'  => true
>         ]); ?>
>     </span>
> ```
> 
> To:
> 
> ```
> <span class="old-price">
>             <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
>                 'display_label'     => __('Regular Price'),
>                 'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
>                 'price_type'        => 'oldPrice',
>                 'include_container' => true,
>                 'skip_adjustments'  => true
>             ]); ?>
>         </span>
> ```

After doing this, old and special prices are shown but on changing the attributes like size or color the price doesn't update.
How to do that?

**Comment by sondrekjellmann** [comment]
> > @engcom-backlog-nickolas we fixed this by:
> > Overriding `vendor/magento/module-configurable-product/view/base/templates/product/price/final_price.phtml`
> > 
> > 1. Removed the condition to check is product isn't in a list
> > 
> > From:
> > ```
> > <?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
> > ```
> > To:
> > ```
> > <?php if ($block->hasSpecialPrice()): ?>
> > ```
> > 
> > 1. Removed 'no-display' class from regular price span
> > 
> > From:
> > ```
> > <span class="old-price sly-old-price no-display">
> >         <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
> >             'display_label'     => __('Regular Price'),
> >             'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
> >             'price_type'        => 'oldPrice',
> >             'include_container' => true,
> >             'skip_adjustments'  => true
> >         ]); ?>
> >     </span>
> > ```
> > To:
> > ```
> > <span class="old-price">
> >             <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
> >                 'display_label'     => __('Regular Price'),
> >                 'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
> >                 'price_type'        => 'oldPrice',
> >                 'include_container' => true,
> >                 'skip_adjustments'  => true
> >             ]); ?>
> >         </span>
> > ```
> 
> After doing this, old and special prices are shown but on changing the attributes like size or color the price doesn't update.
> How to do that?

Did you find a solution?

**Comment by shashankaugurs** [comment]
Yes I had found the solution.
I had managed this by overriding the template in active theme.

app\design\frontend\<Vendor_Name>\<Theme_Name>\Magento_Swatches\templates\product\listing\renderer.phtml

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */ ?>
<div class="swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId() ?>"></div>
<script>
    require(
        ["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer", "Magento_Swatches/js/catalog-add-to-cart"],
        function ($) {
            $('.swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId() ?>').SwatchRenderer({
                selectorProduct: '.product-item-details',
                onlySwatches: true,
                enableControlLabel: false,
                numberToShow: <?php /* @escapeNotVerified */ echo $block->getNumberSwatchesPerProduct(); ?>,
                jsonConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
                jsonSwatchConfig: <?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
                mediaCallback: '<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>'
            });
        });

    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?php echo $block->escapeHtml($block->getProduct()->getId())?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
    });
</script>

**Comment by simonmaass** [comment]
will this get fixed?

**Comment by Volleyb** [comment]
>  product with special price to configurable, Special price remains on configurable product, which leads to confusion on category page, where you see configurable special price instead of option price and on PDP, where you can see both: configurable special price and option price. Which, for instance, never happen in case you create configurable product from the beginning without conversion.
> Therefore, when it will be fixed, there will be no ability to see both: special and option price on category page in vanilla magento. And it's correct behaviour.
> If You want to see both prices on category page with configurable product, it would be better to implement custom solution, or try to find some 3d-party extensions which may provide such functionality.
> 
> Best regards!

Again so many Extensions! Surely this is a basic function! Configurative doesn't mean a price difference! In my case none of my products have a price difference but I want to show they are below RRP!!!!!  come on! Frustrating!

**Comment by 052b-dev** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
@052b-dev thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Charlie** [comment]
Hello @devhelp37 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by not-art** [comment]
@engcom-Charlie 

This bug is 100% reproducible on 2.3.2, 2.3.3, and 2.3.3-p1. Not only is it reproducible, but @052b-dev fixed this bug for you. Read the commit up the thread a little bit:

https://github.com/magento/magento2/issues/15043#ref-commit-b7b4b23

I just applied that bug fix to my repo and it fixed the issue.

Please re-open this ticket and accept the commit that was made to fix this:

https://github.com/magento/magento2/issues/15043#ref-commit-b7b4b23

**Comment by amenk** [comment]
> we fixed this by:
> 
> Overriding `vendor/magento/module-configurable-product/view/base/templates/product/price/final_price.phtml`
> 
> 1. Removed the condition to check is product isn't in a list

I believe this has a huge performance impact,

`\Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox::hasSpecialPrice` loops through all simple products - there is a reason this is not being done on the product list.

The best solution we found so far is this approach: https://magento.stackexchange.com/a/322012/81
