### ISSUE TITLE
Checkout with Multiple Addresses, click update qty & addresses, come back to Shopping cart and Summary section shows $0.00

### ISSUE THREAD

**Issue by Bhavik-kumar** [magento/magento2#15048]
### Preconditions

1. Magento 2.1.7 or 2.1.13
2. php 7
3. Make sure customer should have added multiple address in to address book.
4. Multi-shipping is enable

### Steps to reproduce

1. Add more than 1 qty or product in to cart (make sure new/fresh quote/cart should be generated )
2. Do user login  and go to cart
3. select multiple shipping address
4.  select different addresses & click Update qty & addresses
5. Later click back to shopping cart
6. Verify summary section in shopping cart

### Expected result

1. Cart summary total display zero, summary shows $0.00 (see attachment)

### Actual result

1. Cart summary should not be zero

![image](https://user-images.githubusercontent.com/7893647/39739044-76bb0c74-52ac-11e8-9a93-a9e2d2b88bd0.png)

**Comment by Bhavik-kumar** [comment]
Any Update ?

**Comment by Bhavik-kumar** [comment]
@magento-engcom-team : Hi team,
I am waiting your response.

**Comment by Bhavik-kumar** [comment]
any update?

**Comment by Bhavik-kumar** [comment]
@magento-engcom-team : HI Team 
I am waiting your replay.

**Comment by ghost** [comment]
Hi @Bhavik-kumar the fix for this issue has already in 2.2-develop branch

**Comment by ermohanlal** [comment]
**Fix this issue use this**
Make this directory and use it
app/design/frontend/theme_vendor/currnet_theme/Magento_Tax/web/js/view/checkout/summary/grand-total.js	


define([
    'Magento_Checkout/js/view/summary/abstract-total',
    'Magento_Checkout/js/model/quote',
    'Magento_Catalog/js/price-utils',
    'Magento_Checkout/js/model/totals',
	'Magento_Checkout/js/model/cart/totals-processor/default',
	'Magento_Checkout/js/model/cart/cache'
], function (Component, quote, priceUtils, totals, defaultTotal, cartCache) {
    'use strict';
 var set_total = false;
    return Component.extend({
        defaults: {
            isFullTaxSummaryDisplayed: window.checkoutConfig.isFullTaxSummaryDisplayed || false,
            template: 'Magento_Tax/checkout/summary/grand-total'
        },
        totals: quote.getTotals(),
        isTaxDisplayedInGrandTotal: window.checkoutConfig.includeTaxInGrandTotal || false,

        /**
         * @return {*}
         */
        isDisplayed: function () {
            return this.isFullMode();
        },

        /**
         * @return {*|String}
         */
        getValue: function () {
            var price = 0;

            if (this.totals()) {
                price = totals.getSegment('grand_total').value;
            }

            return this.getFormattedPrice(price);
        },

        /**
         * @return {*|String}
         */
        getBaseValue: function () {
            var price = 0;

            if (this.totals()) {
                price = this.totals()['base_grand_total'];
            }

            return priceUtils.formatPrice(price, quote.getBasePriceFormat());
        },

        /**
         * @return {*}
         */
        getGrandTotalExclTax: function () {
			if(set_total == false)
			{
				cartCache.set('totals',null);
				defaultTotal.estimateTotals();
				set_total = true;
			}
			 var total = this.totals();			
            if (!total) {
                return 0;
            }
            return this.getFormattedPrice(total['grand_total']);
        },

        /**
         * @return {Boolean}
         */
        isBaseGrandTotalDisplayNeeded: function () {
            var total = this.totals();

            if (!total) {
                return false;
            }

            return total['base_currency_code'] != total['quote_currency_code']; //eslint-disable-line eqeqeq
        }
    });
});
