### ISSUE TITLE
CE 2.2.X Configurable product with 1 Attribute - Display Out of Stock Products

### ISSUE THREAD

**Issue by kinhcan** [magento/magento2#15047]
### Preconditions

1. Magento CE 2.2.X
2. Apache 2.4.27
3. PHP 7.0.22

### Steps to reproduce

1. Install Magento 2.2.X CE Sample Data
2. Admin > Stores > Configuration > Catalog > Inventory > Stock Options > Display Out of Stock Products = Yes.
3. CLI php bin/magento indexer:reindex
4. Admin > Products > Catalog > Create configurable product with 1 attribute. Set either Quantity = 0 or Stock Status = Out of Stock.

### Expected result

1. Frontend product should display with all Simple products part of Configurable product and should display with class disabled (red strike through) for out of stock .

### Actual result

1. Frontend product not displayed all.

**Comment by sduif** [comment]
We have the same issue with simple products that are shown in a dropdown attribute. "Display out of stock products" = yes, but they do not appear in the dropdown on a configurable product detail page.

Even after reindexing/clearing cache.

**Comment by jeffb1a5** [comment]
still a problem in CE 2.2.4

**Comment by sduif** [comment]
**Edit:** _The following is for <= 2.2.4. This has since been changed in 2.2.5_

The cause seems to be `Magento\ConfigurableProduct\Plugin\Model\ResourceModel\Attribute\InStockOptionSelectBuilder` which always adds a stock status filter without regard to the "Show out of Stock Products" setting.

I personally fixed it with a custom module **di.xml** though I doubt that this is always the right solution since this for example doesn't check if backorders are allowed for a specific attribute . Maybe someone else has a more prominent solution? 
```
<type name="Magento\ConfigurableProduct\Model\ResourceModel\Attribute\OptionSelectBuilderInterface">
        <plugin name="Magento_ConfigurableProduct_Plugin_Model_ResourceModel_Attribute_InStockOptionSelectBuilder" disabled="true"/>
        <plugin name="attribute_option_select_builder_instock_fix" type="Vendor\MyModule\Plugin\Magento\ConfigurableProduct\Attribute\InStockOptionSelectBuilder" />
</type>
```
**Vendor\MyModule\Plugin\Magento\ConfigurableProduct\Attribute\InStockOptionSelectBuilder.php**

```
<?php

namespace Vendor\MyModule\Plugin\Magento\ConfigurableProduct\Attribute;

use Magento\CatalogInventory\Model\ResourceModel\Stock\Status;
use Magento\ConfigurableProduct\Model\ResourceModel\Attribute\OptionSelectBuilderInterface;
use Magento\Framework\DB\Select;
use Magento\Framework\App\Config\ScopeConfigInterface;

class InStockOptionSelectBuilder
{
    private $stockStatusResource;
    private $scopeConfig;
    
    public function __construct(
        Status $stockStatusResource,
        ScopeConfigInterface $scopeConfig
    )
    {
        $this->stockStatusResource = $stockStatusResource;
        $this->scopeConfig = $scopeConfig;
    }

    public function afterGetSelect(OptionSelectBuilderInterface $subject, Select $select)
    {
        if (!$this->scopeConfig->getValue(\Magento\CatalogInventory\Model\Configuration::XML_PATH_SHOW_OUT_OF_STOCK, \Magento\Store\Model\ScopeInterface::SCOPE_STORE)) {
            $select->joinInner(
                ['stock' => $this->stockStatusResource->getMainTable()],
                'stock.product_id = entity.entity_id',
                []
            )->where(
                'stock.stock_status = ?',
                \Magento\CatalogInventory\Model\Stock\Status::STATUS_IN_STOCK
            );
        }        
        
        return $select;
    }
}
```

**Comment by ghost** [comment]
@kinhcan this is dublicate to -> https://github.com/magento/magento2/issues/10454

**Comment by congson95dev** [comment]
@sduif i've follow your instruction, but it doesn't work on magento 2.2.5

**Comment by sduif** [comment]
Correct, unfortunately there have been various changes in 2.2.5 that break the suggested fix. I've updated my comment to reflect this. I'm affraid I do not have an alternative fix at this time.

**Comment by congson95dev** [comment]
@sduif thanks you, i've searching for this issue all day long and find a lot of code and suggestion, but none of them work so far.

**Comment by lamasfoker** [comment]
The bug is still present, please reopen the issue.

**Comment by toby-pondr** [comment]
I don't believe this to be a bug. It's more just how they've decided to handle this logic. 

That said, I would like an option to show sold out sizes on items with just one attribute.

**Comment by diamondavocado** [comment]
> 
> 
> @kinhcan this is dublicate to -> #10454

This is not a duplicate of that issue. That issue was closed because they didn't try reproducing it correctly. They tried on a product with more than one configurable attributes. They need to try on a product with **only a single configurable attribute** -- as the very title of this issue says!

I can't be the only one thinking this is absolute madness.

I truly do hate Magento.

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-15047-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-15047-2-4-develop.instances.magento-community.engineering/admin_4385](https://i-15047-2-4-develop.instances.magento-community.engineering/admin_4385)
Login: `f5a9c1e7` Password: `1902a5ba424d`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
Re-opening because of https://github.com/magento/magento2/issues/27368

**Comment by ihor-sviziev** [comment]
Hi @kinhcan @diamondavocado,
I just created configurable product with single attribute on test instance: https://i-15047-2-4-develop.instances.magento-community.engineering/ .

On category page configurable product is shown:
![image](https://user-images.githubusercontent.com/1873745/77294058-38d84280-6cec-11ea-8b10-53c4c6de79c7.png)

On product page:
![image](https://user-images.githubusercontent.com/1873745/77294268-a2585100-6cec-11ea-82a8-f35f4205d3e5.png)

But when I enabled one single product - it started to show "in stock" and it started showing drop-down with attribute selection:
![image](https://user-images.githubusercontent.com/1873745/77295136-0deeee00-6cee-11ea-96ab-d2adbef6c92f.png)


As for me it works as expected. Do you agree?

**Comment by ihor-sviziev** [comment]
Hi @kinhcan,
I'm closing this issue as we weren't able to reproduce the issue and didn't get any answer https://github.com/magento/magento2/issues/15047#issuecomment-602444182 or additional info during long period of time.

**Comment by joshdavenport** [comment]
@ihor-sviziev OP was referring to swatches so I don't think your replication was too relevant I'm afraid. OP didn't make that entirely clear as it's not in the title or the description, however their reference to a red strike ("should display with class disabled (red strike through) for out of stock") tells us this is the case.

Your reproduction seems to only check relating to configurable dropdown and beyond that, only that the dropdown appears when there is at least one configuration available. Not sure if only one option appears in the dropdown in your reproduction when there is only one attribute configured by - if both appear with one marked out of stock, then it is entirely irrelevant. If only one appears in the dropdown, it is partially relevant.

The following is absolutely (in 2.2/2.3/2.4) and is definitely happening with swatches:

* If there are 2 colours configured and both are in stock, two swatches show. **Good behaviour** ✅ 
* If one is out stock, only one swatch shows, the other is not rendered at all. **Bad behaviour** ❌ 
* If there are 2 attributes configured by (e.g. colour and size) and one of the configurations is out of stock, the relevant swatch is rendered, but is crossed out. **Good behaviour** ✅ 

Also see https://github.com/magento/magento2/issues/30046

**Comment by ihor-sviziev** [comment]
Thx for the additional info. I reopened this issue

**Comment by joshdavenport** [comment]
Having just now reproduced this in a 2.4-develop instance over in #30046 I am also going to put this reproduction proof here too, as there seems to be many fronts to this and right now it's not clear which one is best served as the authoritative issue. Hopefully its useful for whoever looks at this issue:

![](https://user-images.githubusercontent.com/757828/99723032-85596500-2aa9-11eb-8308-4109c9f2fe5b.png)

**Comment by engcom-Delta** [comment]
@ihor-sviziev @joshdavenport I'm not able to reproduce issue by [steps](https://github.com/magento/magento2/issues/15047#issue-321016708) on clean 2.4-develop
**Result:**
:heavy_check_mark: The red swatch (out of stock) is crossed out.
![image](https://user-images.githubusercontent.com/51681379/101770971-e9dc7280-3af1-11eb-80b8-75d00cc42fed.png)

And according [comment](https://github.com/magento/magento2/issues/15047#issuecomment-730633908) we have same result on 2.4-develop as on the latest image: if configurable product has 1 attribute(swatch) and one of the variations is out of stock, then it rendered on frontend as cross out swatch
 
Could we closed this issue or there is additional steps that were missed?

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@ihor-sviziev @joshdavenport I'm not able to reproduce issue by [steps](https://github.com/magento/magento2/issues/15047#issue-321016708) on clean 2.4-develop
**Result:**
:heavy_check_mark: The red swatch (out of stock) is crossed out.
![image](https://user-images.githubusercontent.com/51681379/101770971-e9dc7280-3af1-11eb-80b8-75d00cc42fed.png)

And according [comment](https://github.com/magento/magento2/issues/15047#issuecomment-730633908) we have same result on 2.4-develop as on the latest image: if configurable product has 1 attribute(swatch) and one of the variations is out of stock, then it rendered on frontend as cross out swatch
 
Could we closed this issue or there are additional steps that were missed?

**Comment by joshdavenport** [comment]
Well, this looks positive. I was definitely seeing this issue in mid/late November in the instance made [here](https://github.com/magento/magento2/issues/30046#issuecomment-730624706) but in this instance you made today it does look to be working as intended. I'm guessing a change has been made in 2.4-develop in the last few weeks that has addressed this issue. If this is for real, very excited for this as it's been an ongoing saga in a current build.

**Comment by joshdavenport** [comment]
Just to further corroborate this, I also followed my original steps from November in that instance and found that the swatches are indeed correctly showing now:

![image](https://user-images.githubusercontent.com/757828/101819100-b3681d00-3b1c-11eb-96f8-e1ef7fbfc2bf.png)

Would be very interested to learn what commit(s) addressed this.

**Comment by ihor-sviziev** [comment]
Hi @kinhcan,
Thx for confirmation. I'm closing this issue as not relevant anymore.

Unfortunately, I don't have information on which exactly changes fixed it.

**Comment by lbajsarowicz** [comment]
🤯  Glad the issue is sorted, but... definitely I'd love to know which Commit fixes that or what Quality Patch offers the fix.

**Comment by lbajsarowicz** [comment]
@magento give me test instance

**Comment by lbajsarowicz** [comment]
@magento give me 2.4-develop instance

**Comment by lbajsarowicz** [comment]
1. Settings
    ![image](https://user-images.githubusercontent.com/1639941/125167443-e355cc80-e1a0-11eb-8cfb-41560945def2.png)
2. Product
   ![image](https://user-images.githubusercontent.com/1639941/125167462-f5d00600-e1a0-11eb-89cc-f7ade5e96c71.png)
3. Result
    ![image](https://user-images.githubusercontent.com/1639941/125167475-0da78a00-e1a1-11eb-8652-9f2df08f26ff.png)

Comments?

**Comment by ihor-sviziev** [comment]
Reopened since we have a report that issue still reproducing on the 2.4-develop branch

**Comment by mrtuvn** [comment]
Lukas have you tested in latest code ?

**Comment by lbajsarowicz** [comment]
@mrtuvn I used the test instance that Magento built. 
![image](https://user-images.githubusercontent.com/1639941/125186366-5b1c0980-e22a-11eb-991d-1453c4659c85.png)

**Comment by lamasfoker** [comment]
@mrtuvn you have to test with a product with only 1 configurable attribute.

**Comment by mrtuvn** [comment]
![config-1attr](https://user-images.githubusercontent.com/1908873/125382654-42455c80-e3c0-11eb-9a8e-48c2dcfbda50.png)
here is for configurable with 1 attribute swatch

**Comment by lamasfoker** [comment]
Thanks @mrtuvn for check it out, I think te issue can finally been closed now 🎉

**Comment by ihor-sviziev** [comment]
@lbajsarowicz, could you provide more info on how you reproduced it? Thank you!

**Comment by lbajsarowicz** [comment]
Ignore it. We fixed that locally on the project.

**Comment by engcom-November** [comment]
Thanks for your update @mrtuvn. Closing the ticket as the issue is resolved.
