### ISSUE TITLE
Email of orders comment notifications stopped work after update to 2.2.4

### ISSUE THREAD

**Issue by caww** [magento/magento2#15045]
### Preconditions

PHP 7.1
Magento 2.2.3 updated to 2.2.4

### Steps to reproduce

Enter to ANY order in view and try to enter any comment in very bottom and checkbox NOTIFY must be checked

### Expected result

Email must go to customer with comment

### Actual result

Error 5.7.1 --- JS alert

**Comment by winterk80** [comment]
FYI we have the same issue in 2.2.3. Email of orders comments don't work. Can you confirm that this worked in your 2.2.3?

**Comment by caww** [comment]
Confirmed --- I rollback to 2.2.3 and Emails notifications in order comment working again.

**Comment by sashas777** [comment]
Cannot repeat using 2.2-develop branch with the latest commit 029d0e6d80b9d50596f942415946197f1a1a67f9

Steps:
1. Magento + SampleData installed from GitHub (deploy mode: default, cache enabled)
2.  New Order created from admin panel
3. Added order comment with checked "Notify Customer by Email"
4.  Emails comes into inbox (Ubuntu+Postifx+Gmail mapping)

Video: https://www.screencast.com/t/3Q6KwlPGvu

**Comment by caww** [comment]
Forgot to say that i used SMTP

**Comment by sashas777** [comment]
@caww 

Just checked the same behavior at the Magento 2.2.4 release from composer. I got the email.

What SMTP do you use?  Is it extension? What settings you use?

**Comment by caww** [comment]
I never use phpmail or sendmail server services which is not secury -- i used SSL connecton to third party secured server

Also as comment to be sure my connection with email server is working:
In same time in 2.2.4 version i can go into contacts and there is email sending is working fine

**Comment by caww** [comment]
I used
MagePal SMTP Configuration (Gmail/Google/AWS/Office360 etc)
Configuration is fine because test mail is coming into my emailbox
Also as i said earlier in other places email is working for example when i send info using contact form

**Comment by caww** [comment]
Also as yoi know 5.7.1 error appears only if smtp connection fails with wrong password or name
it means issue is definely related to smtp sending part of magento or maybe not fresh module from MagePal

**Comment by sashas777** [comment]
@caww 

Just tried with the extension: https://github.com/magepal/magento2-gmail-smtp-app (v.2.5.2)

Using Gmail SMTP still works.

Seems that it isn't related to the Magento. It maybe issue with SMTP credentials/service/extension.

**Comment by sashas777** [comment]
@caww 

Can you try to update module from MagePal and see if it helps, please?

**Comment by caww** [comment]
I used fresh 2.1.0 i checked version
of course i did not used last update -- which says 24 days ago - i did not updated
I am sorry i afraid i can not test again because i use 2.2.3 and dont want to update to have no problems 

Because when i updated from 2.2.2 to 2.2.3 my module for Shipping comments from infobeans is also stopped working
In this time when i updated from 2.2.3 to 2.2.4 --- smtp is stopped working

I think magento developers needs to keep main structure to be more compatible with extensions 
:)
I do not go with update to 2.2.4 i will wait some months while others will report issues and team will fix it in next releases

**Comment by sashas777** [comment]
@caww 

- Please confirm you use Magento 2.2.4 and what is the extension version you use?
- What is the SMTP service option (Gmail/Google/AWS/Office360 etc) you use? 
- Do you use Varnish or Magento cache? 
- What deploy mode you use? (php bin/magento deploy:mode:show) 
- Maybe you can add the screenshot with the error you see? 


If you have any additional information which can help to repeat issue - please add it.

**Comment by ghost** [comment]
@caww, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
