### ISSUE TITLE
Duplicated products not appear in the front-end however it is enabled

### ISSUE THREAD

**Issue by Saad34ML** [magento/magento2#15055]
Hello,

In Magento 2 version 2.2.3 when choose "save and duplicate" from the top right corner button and then make some edits in the new duplicated product and make sure it is enabled and then click "save", the product not appear in the front end (the product list in the category page) however when i write it's ULR in the browser it open well (the page of the product)

Thanks!

**Comment by magento-engcom-team** [comment]
@Saad34ML Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks
