### ISSUE TITLE
Shopping Cart error in Magento 2.2.4

### ISSUE THREAD

**Issue by ritschi72** [magento/magento2#15052]
Preconditions

Magento 2.2.4 (upgraded from Magento 2.2.3 successfully)

Steps to reproduce

Go to configurable product in Frontend and add it to Shopping Cart  (e.g. 1 x T-Shirt in Size L and colour white )
In the same product, add another one (e.g. 1 x T-Shirt in Size M and colour red) to Shopping Cart
   
Expected result

There are two products (1 x T-Shirt in size L and colour white and 1 x T-Shirt in size M and colour red) 
in Mini-Shopping Cart and normal Shopping Cart

Actual result

By adding 1 x T-Shirt (L, white) everything is ok. 
But if I add a second T-Shirt (M, red) within the same product, in the shopping carts is shown 1 x T-Shirt in L, white and 2 x T-Shirts in M, red, although I only added one product each. 
The strange thing is, that if I refresh the site between adding the two T-Shirts, everything is shown correctly. 
That means:
Adding first T-Shirt (L, white) to cart -> ok -> refresh the product site in frontend-> adding second T-Shirt (M, red) to cart -> everything is ok.

Can somebody reproduce this error?

Thanks a lot for your help!
Best regards

Linda

**Comment by mattkrupnik** [comment]
Hi,

I have this same error.

Regards
Matt

**Comment by dudzio12** [comment]
I've just reproduced this error too...

**Comment by ritschi72** [comment]
Any updates on that?

**Comment by keithbentrup** [comment]
I believe this PR: https://github.com/amzn/amazon-payments-magento-2-plugin/pull/227 will fix the issue. In my testing on 2.2.4, the Amazon module would always bind the submit event even when the [original Magento widget](https://github.com/magento/magento2/blob/44502ffb7f44afdcf02e3c2b95acb8538402d6dc/app/code/Magento/Catalog/view/frontend/web/js/catalog-add-to-cart.js#L30) that it was overriding would not, so I simply added the condition back.

Incidentally, you may also see [this "Back" link issue](https://github.com/amzn/amazon-payments-magento-2-plugin/issues/222) with the installed Amazon module

**Comment by ritschi72** [comment]
Thanks for your answer, I had a look at the magento2/app/code/Magento/Catalog/view/frontend/web/js/catalog-add-to-cart.js , but there is already the code as you proposed ...

**Comment by keithbentrup** [comment]
@ritschi72 You're misunderstanding. I'm saying you should be looking at the catalog-add-to-cart.js in the Amazon module included in 2.2.4.

**Comment by ritschi72** [comment]
Thanks a lot for your quick response, I had a look at the catalog-add-to-cart.js in the Amazon module and made the changes and it works! Thanks a lot!

**Comment by keithbentrup** [comment]
@ritschi72 Please leave this issue open until it's fully resolved, so that others can more easily find it (the default filter excludes closed), and that it's handled by the Magento team.

**Comment by joebusby** [comment]
I made the code changes, recompiled / cleared all caches and the problem persisted.  Eventually I changed from production mode to developer mode and back to production mode and that did the trick.  Thanks for posting a solution, it was a big help.

**Comment by magento-engcom-team** [comment]
Hi @ritschi72 
Closing this issue, as it relates to a bundled extension and not core itself. Please refer to links in the comments above for more references.
