### ISSUE TITLE
Request - please remove old version tags

### ISSUE THREAD

**Issue by fooman** [magento/magento2#1505]
Unfortunately the github repository still contains tags from before you started semantic versioning. Anyone with no prior knowledge would assume that 2.0.0.0-dev30 is newer than 1.0.0-beta. As does github ordering these releases earlier:

![screenshot-github com 2015-07-17 13-03-23](https://cloud.githubusercontent.com/assets/455508/8740684/f028d89a-2ca1-11e5-98bf-f559e1f1a372.png)

I currently can't think of anything that would rely on the old tags that would be meaningful.

**Comment by Flyingmana** [comment]
:+1:

**Comment by vpelipenko** [comment]
Old tags were removed, thank you for valuable suggestion.

**Comment by fooman** [comment]
Thanks for actioning this so quick!
