### ISSUE TITLE
Duplicated products not appear in the front-end however it is enabled

### ISSUE THREAD

**Issue by Saad34ML** [magento/magento2#15057]
### Preconditions

1. when choose "save and duplicate" from the top right corner button and then make some edits in the new duplicated product and make sure it is enabled and then click "save", the product not appear in the front end (the product list in the category page) however when i write it's ULR in the browser it open well (the page of the product)
2. Magento 2 version 2.2.3

### Steps to reproduce

1. Duplicated products not appear in the front-end
2. It open well only when typing the URL (slug)
3. 

### Expected result

1. should show all the enabled ploducts

### Actual result

1. show only the product which are created from scratch, not the ones which duplicated from old products and edited

**Comment by rogyar** [comment]
Try checking QTY of the duplicated product. It might be simply out of stock

**Comment by engcom-backlog-nickolas** [comment]
Hello @Saad34ML, thank you for your report. As rogyar correctly pointed out, duplicated product is created without quantity specified and with "Out of Stock" status.

![peek 2018-07-17 11-19](https://user-images.githubusercontent.com/40755810/42804948-16a86f82-89b3-11e8-9f4c-5b8049612c4f.gif)

If you'd like to update this issue, please feel free to reopen it.
