### ISSUE TITLE
Rollback Failure after migration

### ISSUE THREAD

**Issue by Zaman-Fu** [magento/magento2#15054]
After settings and data migration from 1.9.1.1 CE to 2.2.3 CE, a database backup was taken. All attempts to roll back to that particular database state are met with  a "Cannot execute multiple queries" error.

### Preconditions

1.  Using Xampp 3.2.2 ,Apache 2.4, PHP version: 7.1.7, 10.1.25-MariaDB ,Magento 2.2.3 CE

### Steps to reproduce

1. settings and data migration from 1.9.1.1 CE to 2.2.3 CE
2. Creation of a db backup via CLI command setup:backup
3. use of CLI command setup:backup

### Expected result

 Successful rollback to specified database state

### Actual result

"Cannot execute multiple queries" notification in the command line. backup just stops.

**Comment by engcom-backlog-nickolas** [comment]
Hello @Nanondorf, thank you for report. However, problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.
