### ISSUE TITLE
Magento not sending Authorize.net x_description field

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#15065]
### Preconditions

1. Magento Version 2.2.2
2. PHP 7.0.29
3. MySql 5.7.21

### Steps to reproduce

1. Place order using Authorize.net (Credit Card)

### Expected result

1.  Authorize.net request contains an x_description field

### Actual result

1. Authorize.net request does not contain an x_description field

**Comment by engcom-backlog-nickolas** [comment]
Hello @nbennett25, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mateuszkwik** [comment]
mateuszkwik #mm19pl

**Comment by magento-engcom-team** [comment]
@mateuszkwik thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by nbennett25** [comment]
Any updates here @mateuszkwik?

**Comment by ihor-sviziev** [comment]
Hi @nbennett25 ,
According to following announcement this extension was already removed from 2.4 version:
https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445

All future collaboration related to this extension should be on Marketplace using "Contacts" or "Bug reports" related to this extension.

I'm closing this issue.
