### ISSUE TITLE
For 2.2.3,Can't add the products and edit the products.

### ISSUE THREAD

**Issue by kingboyno1** [magento/magento2#15061]
When I trying to add the products,It's will show the below information,Can't add any Simple and Configurable products

Preconditions

Magento 2.2.3 Add products
PHP 7.0.28
Glame theme

# **Steps to reproduce**
Want to add the products

E.g Add one catalogue,I'm want to upload the products in the catalogue.
But when click " Add products" No matter Simple or configurable products.
# **Expected result**
Update the products to the website:

# **Expected result:**

Fatal error: Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 371 and defined in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:321 Stack trace: #0 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(371): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataElement(Array, 'configurableExi...', NULL, false) #1 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #2 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #3 /home/justuniq/public_html/vendor/magento/framework/ in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 321

**Comment by magento-engcom-team** [comment]
Hi @kingboyno1 
Unfortunately steps to reproduce are not clear enough to find out what exactly causes the issue.
Please update the report with more details and reopen. 
Thank you.
