### ISSUE TITLE
Products -> Actions -> Update Attributes does not work when products are selected with "Select All"

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1506]
"Products -> Actions -> Update Attributes" works only when products have been selected one-by-one by clicking checkboxes, but does not work when selected all the products with "Select All".

**Comment by kokoc** [comment]
@dfediuk thank you for reporting the issue. Internal reference: MAGETWO-40073

**Comment by vladimir-k** [comment]
@dfediuk, this issue is fixed and delivered (internal reference: MAGETWO-42939). Could you please verify the fix?

**Comment by dfediuk** [comment]
Yes, it works now.
