### ISSUE TITLE
Error message when a file is not writable

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1507]
In the method `Magento\Framework\Filesystem\Io\File::write()` there are these error messages:  
1. for when the file is not writable: 'File <file name here> don't writeable'
2. for when the folder is not writable: 'Folder <folder name here> don't writeable'.

 > Wow. Very English, many grammar.

The error messages should be changed to make sense.

**Comment by joanhe** [comment]
@tzyganu Thanks for reporting this issue. Internal ticket MAGETWO-40374 is created for this.

**Comment by tzyganu** [comment]
This looks like is fixed now. Thanks.
