### ISSUE TITLE
bin/magento directory not found in installation

### ISSUE THREAD

**Issue by bastianhilton** [magento/magento2#15088]
### Preconditions

1.  Magento 2.2.3 Community Edition on Windows 10 as of May 2018
2.  Php, 5.6 and Latest Bitnami MySQL version. 

### Steps to reproduce

1.  Downloaded Bitnami Module Magento

### Expected result

1.  Magento Directory should have bin folder but doesn't, many tutorials show that there should be a bin/magento folder however it doesn't exists.

### Actual result

1. [Screenshot, logs]

**Comment by DanielRuf** [comment]
I guess it is a wrong setup on Bitnamis side.

The webinstaller and composer package should both include the bin directory.

**Comment by DanielRuf** [comment]
https://docs.bitnami.com/installer/apps/magento/

At least they use some bin/magento-cli in httpdocs.

**Comment by ghost** [comment]
@bastianhilton, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by DanielRuf** [comment]
> @DanielRuf, please refer to the Community Forums or the Magento Stack Exchange site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

The issue was not opened by me ;-)
