### ISSUE TITLE
JS Error when click 'Go to Checkout' button

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1508]
1.0.0 Beta 1

This issue doesn't appear on minicart button.

![capture](https://cloud.githubusercontent.com/assets/11070293/8747910/1fd1a3a0-2cc1-11e5-9f0d-8b0d7297c50a.JPG)

**Comment by markoshust** [comment]
Related error clicking checkout on cart page. beta-1.0.0 with new sample data.
![screen shot 2015-07-20 at 9 48 18 am](https://cloud.githubusercontent.com/assets/437029/8777206/8adca38e-2ec4-11e5-87d9-30f71ffc2095.png)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-40559

**Comment by vpelipenko** [comment]
@adzminz, issue is fixed. Please, check it and let us know results.
