### ISSUE TITLE
USPS Print Shipping Labels API outdated.

### ISSUE THREAD

**Issue by crantron** [magento/magento2#15084]
### Preconditions
1. Use USPS for shipping

### Steps to reproduce
1. Ship order 
2. Create a Package

### Expected result
1.  Create a Shipping label

### Actual result

![email](https://user-images.githubusercontent.com/3859969/39777301-0c4eb6c2-52b8-11e8-89ca-8d653658e79c.png)
![usps](https://user-images.githubusercontent.com/3859969/39777302-0c68ed9e-52b8-11e8-9838-5089061f8def.jpg)

**Comment by mehh** [comment]
Can confirm we're also having this issue as well.  Looks like USPS changed their API recently.

**Comment by louisnorthmore** [comment]
Same issue. Is there going to be a solution for their new label API moving forward?

**Comment by ghost** [comment]
@crantron, thank you for your report.
The fix for this issue is already available in latest Magento releases. Please update your Magento instance.
