### ISSUE TITLE
Magento 2 - OAuth Problem = oauth_consumer_key+is+a+required+field

### ISSUE THREAD

**Issue by maniramav** [magento/magento2#15098]
### **Preconditions**

1. Magento Version 2.2.4
2. Set up and activated API Integration with full access

###  **Steps to reproduce**

1. Create integrations
2. Make POST call to /oauth/token/request

### **Expected result**

1. Get request token

### **Actual result**
`oauth_problem=oauth_consumer_key+is+a+required+field%2C+oauth_signature+is+a+required+field%2C+oauth_signature_method+is+a+required+field%2C+oauth_nonce+is+a+required+field%2C+oauth_timestamp+is+a+required+field`

![capture](https://user-images.githubusercontent.com/11077689/39811854-43284620-5382-11e8-8e6d-035eaa716bc8.JPG)

**Comment by ghost** [comment]
HI @maniram1804  
You must include these request parameters in the Authorization header in the call: oauth_consumer_key ->
oauth_signature_method ->
oauth_signature->
oauth_nonce->
oauth_timestamp->
oauth_version 

The response contains these fields:
oauth_token. The token to be used when requesting an access token.
oauth_token_secret. A secret value that establishes ownership of the token.
