### ISSUE TITLE
Create customer from backend 'steals' address other customer on 1.0.0-beta + 1.0.0-beta sample data

### ISSUE THREAD

**Issue by wigman** [magento/magento2#1511]
Created a new customer in backend. Only one customer existed beforehand: "Veronica Costello" from the 1.0.0 beta sample data.

Inserted only account information (names, email, gender) and saved customer associated to the Admin website.
Reopened the customer, switched website to "Main website", saved.

Now the newly created customer inherited all address data from Veronica Costello, leaving Veronica without address info.

Tested this twice. First time installed demo data after installation, second time including demo data in primary setup.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-40472

**Comment by vladimir-k** [comment]
@wigman, internal ticket is closed and delivered. Please, let us know if you still have an issue. Thank you!
