### ISSUE TITLE
Fix urlResolver query to support relative path

### ISSUE THREAD

**Issue by DrewML** [magento/magento2#15112]
### Steps to replicate
1. Using the urlResolver query, send a valid URL for the `url` field, and include a leading `/`
2. Note `null` as the response for `urlResolver`

### Expected Behavior
The query returns the same result for the route that it would if the leading `/` was not present

### Current Behavior
`null` is returned in the response payload for `urlResolver`

### Justification
The `urlResolver` query is an API with the sole purpose of assisting the browser. In the browser, any way that we obtain a pathname (location.pathname, aTag.pathname, etc) will always have a leading `/`

### Preconditions

1. `2.3-develop`

### Steps to reproduce

1. Send the following query to `/graphql`:
	```graphql
	{
	  urlResolver(url: "/") {
		canonical_url
	    id
	    type
	  }
	}

	``` 
2. Note the following response body:
	```json
	{
	  "data": {
	    "urlResolver": null
	  }
	}
	```

### Expected result

1. Response body should include the same information that you'd get when querying `url: "home"`, which is a page of type `CMS_PAGE`.

### Actual result

Received Payload:
```json
{
  "data": {
    "urlResolver": null
  }
}
```

### Duplicate Issues:
https://github.com/magento/graphql-ce/issues/9

**Comment by DrewML** [comment]
@paliarush should I close this out in favor of https://github.com/magento/graphql-ce/issues/9?

**Comment by huykon** [comment]
I have same issue with Magento version 2.3.3. Could anyone have solution to resolve it?
