### ISSUE TITLE
Upgrade Magento 2.2.3 to 2.2.4 breaks Warning: Uncaught Exception: Warning: require(setup/config/application.config.php): failed to open stream: No such file or directory in vendor/magento/framework/Console/Cli.php on line 70

### ISSUE THREAD

**Issue by slawek-mazur** [magento/magento2#15114]
I'm testing an upgrade from Magento 2.2.3 to 2.2.4 and when i do a php bin/magento setup:upgrade it breaks the upgrade with this warning:
Warning: Uncaught Exception: Warning: require(/setup/config/application.config.php): failed to open stream: No such file or directory in /vendor/magento/framework/Console/Cli.php on line 70 in /vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
<i>#</i>0 `/vendor/magento/framework/Console/Cli.php(70): Magento\Framework\App\ErrorHandler->handler(2, 'require(/...', 70, Array)`
<i>#</i>1 `/vendor/magento/framework/Console/Cli.php(70): require()`
<i>#</i>2 `/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')`
<i>#</i>3 `{main}
  thrown in /vendor/magento/framework/App/ErrorHandler.php on line 61`

### Preconditions
1. Magento 2.2.3 to 2.2.4
2. PHP 7.1.13

### Steps to reproduce
1. composer require magento/product-community-edition 2.2.4 --no-update
2. composer update --ignore-platform-reqs
3. rm -fr pub/static/* var/cache/* var/composer_home var/generation var/page_cache var/view_preprocessed
4. bin/magento setup:upgrade

### Expected result

Finishing the php bin/magento setup:upgrade

### Actual result
bin/magento setup:upgrade breaks with Warning: Uncaught Exception: Warning: require(/setup/config/application.config.php): failed to open stream: No such file or directory in /vendor/magento/framework/Console/Cli.php on line 70 in /vendor/magento/framework/App/ErrorHandler.php:61

By looking at which files got changed it's clear that `application.config.php` was removed (greyed out on the screen below)

![image](https://user-images.githubusercontent.com/9823973/39827590-ae1a2ddc-53b8-11e8-96a7-7eb60ffcad2c.png)

**Comment by engcom-backlog-nickolas** [comment]
Hello @slawek-mazur, thank you for your report. I cannot reproduce this issue
![peek 2018-07-24 09-26](https://user-images.githubusercontent.com/40755810/43120894-6eef9ba4-8f24-11e8-9ab4-ba0b94e8aa25.gif)
If you'd like to update it, please reopen the issue.

**Comment by dverkade** [comment]
Hi,

Same issue here with doing a deployment to the test environment. See full deployment log in the file attached:
[pipelineLog-929.txt](https://github.com/magento/magento2/files/4152222/pipelineLog-929.txt)

**Comment by hostep** [comment]
@dverkade: this probably happens because some files failed to be copied from the `vendor/magento/magento2-base` directory to the root directory. If you are able to figure out why that happens, you might be able to solve your issue. I'm assuming that this one file won't be the only one which is missing in the root directory?

Unfortunately the magento-composer-installer plugin is not doing the necessary checks and is not reporting anything useful when an error occurs like that.
More info over here: https://github.com/magento/magento2/issues/10292#issuecomment-467163720

**Comment by dverkade** [comment]
@hostep Up on further research I discovered my coworker removed the "extra.magento-force" option from our root composer.json. This has been to cause of our issue.

**Comment by vphat28** [comment]
this is caused by removing the setup folder from the root installation folder

**Comment by 4DallasC** [comment]
If there are any files existing in the magento root directory that match the extra>map section in vendor/magento/magento2-base/composer.json, then it will stop the files after it from been copied during the composer install and do so without give an error.

**Comment by andrewdaluz** [comment]
@JoostWan just saved my day. All the mapped files/folders from that composer.json list are required for the deployment on adobe cloud. I've then added the following files to the repository and everything worked like a charm:
`pub/errors pub/get.php pub/cron.php pub/.user.ini pub/.htaccess pub/index.php pub/health_check.php lib/.htaccess pub/media/.htaccess   pub/media/customer/.htaccess  pub/media/downloadable/.htaccess pub/media/theme_customization/.htaccess pub/opt/magento/var/resource_config.json pub/static/.htaccess pub/static.php var/.htaccess  vendor/.htaccess`

**Comment by niclashoyer** [comment]
I used the following command to manually copy any files from `magento2-base/composer.json`  `map`-section to the magento root directory:

```bash
cat vendor/magento/magento2-base/composer.json | jq '.extra.map[][1]' | xargs -n1 -I'{}' bash -c 'echo -n "{}"; if [ -d "vendor/magento/magento2-base/{}" ]; then echo -n "/"; fi; echo' | xargs -n1 -I'{}' rsync -a --delete 'vendor/magento/magento2-base/{}' '{}'
```
