### ISSUE TITLE
Upgrade Magento 2.2.3 to 2.2.4 breaks Warning: Division by zero in /vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 41

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#15110]
I'm testing an upgrade from Magento 2.2.3 to 2.2.4 and when i do a php bin/magento setup:upgrade it breaks the upgrade with this warning:
Warning: Division by zero in /vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 41

### Preconditions

Magento 2.2.3 to 2.2.4
PHP 7.1

### Steps to reproduce

1.  php bin/composer require magento/product-community-edition 2.2.4 --no-update
2.  php bin/composer update
3. rm -rf generated/code* generated/metadata* var/view_preprocessed/*; rm -R pub/static/*;
4. php bin/magento cache:flush
5. php bin/magento setup:upgrade

### Expected result

1.  Finishing the php bin/magento setup:upgrade 

### Actual result

1. php bin/magento setup:upgrade breaks with Warning: Division by zero in /vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 41

**Comment by galanis-a** [comment]
Just run on this problem on Magento 2.2.0 when removing items from cart any solutions?

**Comment by Jilco** [comment]
After a new attempt after one day it did go wel, i still don't know the root cause....


________________________________
Van: Antonis Galanis <notifications@github.com>
Verzonden: dinsdag 3 juli 2018 11:09
Aan: magento/magento2
CC: Jilco; Author
Onderwerp: Re: [magento/magento2] Upgrade Magento 2.2.3 to 2.2.4 breaks Warning: Division by zero in /vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 41 (#15110)


Just run on this problem on Magento 2.2.0 any solutions?

**Comment by engcom-backlog-nickolas** [comment]
Hello @Jilco, thank you for your report. I cannot reproduce this issue.
![peek 2018-07-24 09-26](https://user-images.githubusercontent.com/40755810/43121112-4a45df9c-8f25-11e8-8dbc-b6f31b25f90b.gif)
If you'd like to update it, please reopen the issue.
