### ISSUE TITLE
Date format garbled in view report when interface locale set to Chinese

### ISSUE THREAD

**Issue by ray2095** [magento/magento2#15126]
### Preconditions

1. Magento ver. 2.2.3
2. PHP Version 7.0.28

### Steps to reproduce

1. Login to admin panel.
2. Go into "Account Setting" page and set "Interface Locale" to "中文(台灣)" and "Save Account".
3. Choice "REPORTS" > "Views" from left side menu.
4. Input date range in the Filter Datepicker and then click "Show Report" button.

### Expected result

1. It was supposed to be an ordinary "Viewd" report.

### Actual result

1. The Date Format in the "Interval" colume garbled...
![image](https://user-images.githubusercontent.com/39153311/39862142-73d2bdf2-5475-11e8-8874-8de4d3d0da8a.png)

**Comment by ghost** [comment]
Hi @ray2095 the fix for this issue has already been in 2.2-develop branch.
