### ISSUE TITLE
Magento 2.2.4 Categories became 4.4 Not Found After Reindex

### ISSUE THREAD

**Issue by mariamghalleb** [magento/magento2#15120]
### Preconditions

1. Magento 2.2.4
2. Php 7.0.3

### Steps to reproduce

1. I add a Product 
2. I reindex;  Php bin/Magento indexer:reindex
3. I go to frond end and find out that all categories became 404 Not Found
4. I clear the cache, flush it, setup:upgrade, setup:di:compile, deploy, nothing works.

### Expected result

1. Categories work as usual

### Actual result

1. [Screenshot, logs] Categories = 404 not found

This never happend when i was on 2.2.3, since I upgraded to 2.2.4 this reproduced 4 times. 

Every time it happens, I create a new categorie, move a product from an old category to the new one created and somehow the other categories start to work again.

**Comment by ghost** [comment]
@mariamghalleb, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
