### ISSUE TITLE
[2.2.4] New session created every minute by the cron process

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#15122]
@LifeAsBook I have updated the bug description to meet the bug reporting guidelines in order to get this issue progressed.

Every minute a new session is created by the cron process. I'm pretty sure it shouldn't be doing this.

### Preconditions
1. Stock Magento 2.2.4
2. PHP
3. Cron setup to run every minute
4. Sessions set to "file"

### Steps to reproduce
1. Nothing

### Expected result
1. With no webserver activity, noone browsing the front end, there should be no sessions created.

### Actual result
1. Every minute a new session file is created.

The content of my session files is.

`_session_validator_data|a:4:{s:11:"remote_addr";s:0:"";s:8:"http_via";s:0:"";s:20:"http_x_forwarded_for";s:0:"";s:15:"http_user_agent";s:0:"";}default|a:0:{}customer_admin|a:0:{}`

### Possibly related
Every time after running bin/magento indexer:reindex also a session file was generated...

**Comment by gwharton** [comment]
@LifeAsBook I think I know what you mean, as I am seeing something similar. If I look in /var/lib/php/sessions

I see a session file created every second with the following contents.

`_session_validator_data|a:4:{s:11:"remote_addr";s:0:"";s:8:"http_via";s:0:"";s:20:"http_x_forwarded_for";s:0:"";s:15:"http_user_agent";s:0:"";}default|a:0:{}customer_admin|a:0:{}`

My install is 2.2.3

I see other valid sessions in there for normal users using the website, but they are interspaced with these empty session files every 1 second.

Do you not have a cron job to clear old sessions? That takes care of them for me so I'm not too concerned.

**Comment by LifeAsBook** [comment]
@gwharton no,i mean that  the cron will be create sesssion every minutes.this is bug

**Comment by LifeAsBook** [comment]
`  <job name="sales_send_order_emails" instance="SalesOrderSendEmailsCron" method="execute">
            <schedule>* * * * *</schedule>
        </job>
        <job name="sales_send_order_invoice_emails" instance="SalesInvoiceSendEmailsCron" method="execute">
            <schedule>* * * * *</schedule>
        </job>
        <job name="sales_send_order_shipment_emails" instance="SalesShipmentSendEmailsCron" method="execute">
            <schedule>* * * * *</schedule>
        </job>
        <job name="sales_send_order_creditmemo_emails" instance="SalesCreditmemoSendEmailsCron" method="execute">
            <schedule>* * * * *</schedule>
        </job>
`
i find this cron job  will be create session every minutes

**Comment by gwharton** [comment]
@LifeAsBook How have you determined that it is those jobs that are creating the sessions?

**Comment by gwharton** [comment]
Yesterday at around 20:00 I increased the session lifetime in php.ini from 30 minutes to 1 day. It certainly looks like I have something creating sessions on a regular basis. Funnily enough, around 4-5 sessions per minute.

![image](https://user-images.githubusercontent.com/30697781/40019632-af93f5d2-57b7-11e8-9d0f-5c0e15f258c8.png)

Last week I noticed that I had accidentally set session storage to database for my production website, and without any session clearing going on in the database, my session table was up to half a million rows.

**Comment by LifeAsBook** [comment]
yes ,this is bug. because the magento crontab job create sesssion every minutes.

**Comment by gwharton** [comment]
I have done some debug on the cron process, and in my test installation I have one cronjob that result in a new session being created every time it is run. It is

"Magento\Catalog\Cron\DeleteOutdatedPriceValues.php"

From what I can see in the stack trace, 
```
Magento\Catalog\Cron\DeleteOutdatedPriceValues.php 
->
Magento\Catalog\Helper\Data
->
Magento\Tax\Model\TaxCalculation
->
Magento\Tax\Model\Calculation
->
Magento\Cart\Model\Session
->
Magento\Framework\Session\Generic
```

**Comment by sindrepm** [comment]
I am seeing this as well. Is it a confirmed bug or should it be doing this? I don't really see any reason why cron should be creating sessions.

**Comment by ghost** [comment]
Hi @LifeAsBook I cannot reproduce your scenario, in my case i have no sessions created, only 1 for admin which i created when i login in, see attachments If you'd like to update it, please reopen the issue.
![frame 23d](https://user-images.githubusercontent.com/40756439/43320049-c934938e-91af-11e8-9071-26a97d3e50d7.gif)

**Comment by ghost** [comment]
@LifeAsBook 
![selection_043](https://user-images.githubusercontent.com/40756439/43320643-d1226380-91b1-11e8-9974-5c0be4c630d8.png)

**Comment by gwharton** [comment]
@engcom-backlog-nazar you tested this on 2.3, it was raised on 2.2

I have just deployed 2.2.5 from git, created the cronjob

![screenshot 3](https://user-images.githubusercontent.com/30697781/43321129-d64dd5c4-91a2-11e8-8837-ca680c3ea11b.png)

4 minutes since enabling cron job, 4 sessions created. I've not even touched the front/backend via browser.

**Comment by ghost** [comment]
@gwharton can you please provide more information to reproduce? it problem in your environment, can you provide a video ?
![selection_044](https://user-images.githubusercontent.com/40756439/43321462-9a3193ca-91b4-11e8-94d1-68bc0b336e3b.png)

**Comment by ghost** [comment]
@gwharton Give me a screenshot by run cron every 1 minute, so we have a 10 minute cron run, end we must have 10 session file

**Comment by ghost** [comment]
@gwharton 
![selection_045](https://user-images.githubusercontent.com/40756439/43321909-e8c073fc-91b5-11e8-8c3b-5a054b3ecc70.png)

**Comment by gwharton** [comment]
Here is a video of the deployment and the first 5 minutes of sessions being created. See attached for a copy of my deployment script [recreate-dev1.txt](https://github.com/magento/magento2/files/2235857/recreate-dev1.txt)

https://youtu.be/P3jSkPn8r4c

This is a bog standard Ubuntu 17.10 install.

And after 20 minutes or so

![screenshot 4](https://user-images.githubusercontent.com/30697781/43323494-b81665f6-91a9-11e8-832c-e67bfdb9bac4.png)

**Comment by ghost** [comment]
@gwharton problem in your environment its not cron create a session, try install magento , manual locally, i think 99% you cannot  reproduce this.

**Comment by ghost** [comment]
@gwharton  i still have no created session. also try  ->https://devdocs.magento.com/guides/v2.2/config-guide/sessions.html

**Comment by gwharton** [comment]
I've deployed a number of times, 100% reproducable, @sindrepm and @LifeAsBook are also seeing it. Its been doing it 100% on all my installations for the last few versions on magento. Can't pinpoint when it started. Not sure what you want me to try from the devdocs, i'm just deploying from scratch and not configuring anything!

**Comment by ghost** [comment]
@gwharton Just try deploy manual on you computer, only locally.

**Comment by gwharton** [comment]
I've just deployed it onto another freshly deployed Ubuntu 17.10 machine with no webserver configured. Same result. Session created every minute.

**Comment by hostep** [comment]
@engcom-backlog-nazar: I can also reproduce this on my local environment:
- MacOS 10.13.6
- PHP 7.0.31 (via Homebrew)

Steps to reproduce:
1. Install Magento 2.2.5 using composer & using `bin/magento setup:install ...`
2. Every minute, ran `bin/magento cron:run`
3. Saw a new file getting generated in `var/session/` every minute matching the timestamp when the cron ran.

Never opened a browser while doing this.

Possibly related: every time after running `bin/magento indexer:reindex` also a session file was generated...

**Comment by hubertinio** [comment]
During save Indexer\Model\Indexer\State is executing event "model_save_before"
Later things looks like below:

    Magento\AdminGws\Observer\ValidateModelSaveBefore __constructor( Magento\AdminGws\Observer\RolePermissionAssigner )
    Magento\AdminGws\Observer\RolePermissionAssigner __constructor( Magento\Backend\Model\Auth\Session )
    Magento\Backend\Model\Auth\Session::registerSaveHandler() - there is set "session_set_save_handler"
    Magento\Backend\Model\Auth\Session::write()

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by bohdan-harniuk** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by bohdan-harniuk** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by bohdan-harniuk** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by bohdan-harniuk** [comment]
That issue is not reproducible on 2.2.9/2.3.6. Reproduced only on 2.2.4. We should close this issue.

**Comment by coderimus** [comment]
Hello @bohdan-harniuk 
Thank you for your investigation and detail report on a call. Good to have such a quick reaction to the P1 issue. Really helpful! 👍 

I close this issue.
