### ISSUE TITLE
Single store mode category conflicts

### ISSUE THREAD

**Issue by BNStudio** [magento/magento2#15125]
We have an instance of Magento 2 store (2.2.2 now), in Single Store Mode.

In catalog_category_entity_* tables we have rows with store_id 0 and 1 for the same category. In some cases there are different values for the same attribute_id. We think that admin saves data for store_id 0, but the frontend reads it from store_id 1. Is it possible?

**Comment by magento-engcom-team** [comment]
@BNStudio please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
