### ISSUE TITLE
1.0.0-beta, no way to set password for customer after placing order

### ISSUE THREAD

**Issue by wigman** [magento/magento2#1512]
After placing an order the customer has the option to click a button to create an account in a 'one-click' action.

The customer then receives an signup email that says:
Password: "Password you set when creating account".

So there's no way to login, except for requesting a forgotten password link.

Tested in default theme.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-40511

**Comment by sivaschenko** [comment]
@wigman Fix for this issue is delivered to `develop` branch

**Comment by wigman** [comment]
@sivaschenko Thanks Sergey!

**Comment by okorshenko** [comment]
@wigman , Please, let us know if you still have an issue
