### ISSUE TITLE
Single store mode category conflicts

### ISSUE THREAD

**Issue by BNStudio** [magento/magento2#15130]
### Preconditions

1.  Magento 2.2.2 CE
2.  PHP 7.0
3. Single Store Mode

### Steps to reproduce

1. Editing category (eg. disable or include in menu set No)

### Expected result

1.  Category hide from menu

### Actual result

1. Category is visible

We can see in database that catalog_category_entity_int table has 0 and 1 store_id rows for the same attribute_id - entity_id pair. When we save the category from the admin panel, store_id 0 is modifying, but our frontend works from store_id 1. Is it possible?

**Comment by rohit-wagento** [comment]
I am working on this at #dmcdindia

**Comment by rohit-wagento** [comment]
I have enabled : store >> configuration >> general >> single store mode >> yes

and then from products >> categories >> edit one category >> marked include in navigation menu set : No

then cleared the cache

and i can't able to see categories in frontend, then i set yes for category then i able to see category
on frontend.
it working fine for me on 2.2-develop

**Comment by lewis-dan** [comment]
I am working on this at #dmcdindia”

**Comment by lewis-dan** [comment]
Hi,

Please follow the following steps:

Catalog > Select any Category > Change Category (Enable Disable/ Include in Menu) > Save

Clear Cache - ReIndex

Reload Frontend - Expected Result "Category hide from menu"

If you found any discrepancy, Please let us know.

Thanks,
Dan

**Comment by magento-engcom-team** [comment]
@lewis-dan @rohit-wagento Thank you for research.
@BNStudio  We are closing the issue now, as it was most likely related to indexer not being executed.
Thanks

**Comment by paul-blundell** [comment]
I am still seeing this issue on Magento 2.2.5. Even after clearing cache and reindexing.

You can see in the database table catalog_category_entity_int it has updated for store_id = 0 but not for store_id = 1. If I remove all values where store_id = 1 then it works.

**Comment by paul-blundell** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell, here is your [Magento instance](https://i-15130-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-15130-2-2-5.engcom.dev.magento.com/admin](https://i-15130-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by paul-blundell** [comment]
I have reproduced this issue on the above clean instance. 
I believe this issue occurs when you previously had multiple stores.

1. Make sure single-store mode is No
2. Create a new store view
3. Create a new category
4. Edit the category name for the new store view, unticking the use Default Value box.
5. Switch to the default store view and edit the category name, unticking the use Default Value box.
6. Switch to the All Store Views and set the category name to something different.
7. Frontend is correctly showing the default store view name.
8. Delete the second store view.
9. Enable single store mode.
10. Category name changes now have no effect on the frontend. Stuck on the name set on step 5.
