### ISSUE TITLE
Save & duplicate product and save other url key

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#15132]
### Preconditions

1.  Magento 2.2.4
2. PHP 7.0
3. Mysql 5.6.30

### Steps to reproduce

1.  Create duplicate product
2.  Change Url Key
3. Click Save

### Expected result

1.  Save other url key for product

### Actual result

1. Error: 

```
`The value specified in the URL Key field would generate a URL that already exists.`
`To resolve this conflict, you can either change the value of the URL Key field (located in the Search Engine Optimization section) to a unique value, or change the Request Path fields in all locations listed below:`
```

Default store view - all works but other two store-view it doesn't work.

**Comment by sunilit42** [comment]
Hi @Userr017 

I checked the same scenario and it is working fine.

Maybe you added the same key that exists in DB, can you please check it?

**Comment by andrewsurrey** [comment]
This is still an issue. 
my issue is along side: 4096.
if the product doesd duplicate ok, there's no way to change the url anymore. 
even if create redirects is unchecked and a totally random unused url provided it give the error above.

result is being stuck with a duplicated product we can't update the url for.

**Comment by StarDev-it** [comment]
Hi all,
I'm found the some problem.
In do {} while() block, the catched exception was wrong, and there is a problem in resource data duplication.
See my patch here: https://github.com/magento/magento2/issues/12412#issuecomment-490464413
