### ISSUE TITLE
1.0.0-beta Missing js files on Product View page in Luna theme

### ISSUE THREAD

**Issue by wigman** [magento/magento2#1513]
Version 1.0.0-beta - Luma theme - Demo data 1.0.0-beta

On http://[magentodomain.com]/eos-v-neck-hoodie.html (product view page) I'm missing 2 js files.
Javascript functionalities in Media gallery do not work + no configurable options are being loaded.

Missing files:
http://[magentodomain.com]/static/frontend/Magento/luma/en_US/handlebars.js
http:///[magentodomain.com]/static/frontend/Magento/luma/en_US/jquery/template.js

**Comment by kokoc** [comment]
@wigman thank you for contacting us.
Unfortunately, I can't reproduce your issue. Could you please provide additional information:
* What application mode(`default`|`developer`|`production`) do you use?
* Did you upgrade from previous Magento versions? If yes, could you please try to remove pub/static/frontend/* files?
