### ISSUE TITLE
Broke html if the attributes such as product name, meta description contents html tags and/or special chars.

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#1514]
There is no renderer for a product name, meta_description, etc...
https://www.dropbox.com/s/q6404m8emobz5rm/1.PNG?dl=0
https://www.dropbox.com/s/5p5hh9mhdzpptrp/2.PNG?dl=0
https://www.dropbox.com/s/gp3uba30r78lwdm/3.PNG?dl=0
luma / Magento ver. 0.74.0-beta16 + official Sample Data

**Comment by orlangur** [comment]
Consistent solution needs to be considered together with #1497.

I personally tend to:
* escape HTML entities in product name when it occurs in meta tag
* strip HTML entities in product description, as this is a WYSIWYG-enabled field

**Comment by dougkm** [comment]
@vpelipenko - Is there an internal Jira ticket for this issue?

**Comment by Krapulat** [comment]
I have the same problem. Is there a fix for this?

**Comment by vzabaznov** [comment]
@sergei-sss @Krapulat bug was fixed and delivered to develop branch
