### ISSUE TITLE
language change to fa_IR not take effect

### ISSUE THREAD

**Issue by woshka** [magento/magento2#15150]
when going to store > configuration
and change language to Persian which is fa_IR
it will not take effect
only take effect if the user go to the account setting and change the Language to persian
### Preconditions

1. install magento 2.1.13
2. install Persian language fa_IR.csv file from Mage Plaza

### Steps to reproduce

1. changing language globally
2. 
3. 

### Expected result

1. language changes to Persian which will not

### Actual result

1. [Screenshot, logs]
the language will remain in english unless we change it for each user account setting

**Comment by ananth-iyer** [comment]
@woshka Did you changed the `Locale` in `Store > Configuration > General` page? Please check on all `Store View` also.

**Comment by woshka** [comment]
Yes I tested it on atleast 10 installation
it is not taking effect and the languages will remain in English although the language CSV file is installed
only the user configuration change locale for persian will take effect

Thanks

**Comment by ananth-iyer** [comment]
Where is the CSV file? Theme or Language Pack

**Comment by woshka** [comment]
installing this 
https://www.mageplaza.com/magento-2-persian-language-pack.html
on /app/i18nt/magepelaza/fa_ir/fa_IR.csv

**Comment by ananth-iyer** [comment]
change /app/**i18nt**/magepelaza/fa_ir/fa_IR.csv

to /app/**i18n**/magepelaza/fa_ir/fa_IR.csv

**Comment by woshka** [comment]
I had a typo in my report in here
the correct is /app/i18n/magepelaza/fa_ir/fa_IR.csv
please install a clean installation
install mageplaza farsi 
change the language in store>configuration to persian
it will not take effect
only changing per user account or change the hard coded in php file locale will take effect

**Comment by ananth-iyer** [comment]
Did you run `setup:static-content:deploy` command?
Before running delete `pub/static/frontend` & `pub/static/adminhtml` directory
then check fa_IR directory in `pub/static/frontend/Your/theme/`

**Comment by woshka** [comment]
@Ananth747 
some translations of magento 2 core complete package modification have changed the Dateformat.php for this reason to make changes hard coded to take effect
[DateFormat.zip](https://github.com/magento/magento2/files/1994516/DateFormat.zip)

I have run those commands to create static files, Di complie deleting of files but none of them worked out, the only way was to change it for each user profile, not globally

**Comment by ananth-iyer** [comment]
I tried to reproduce your issue on local Magento 2.1 and its showing Persian translations for guest users & register customers. I used `magepelaza/fa_ir` language pack. Without changing `DateFormat.php`.

**Comment by woshka** [comment]
@Ananth747 
could you please try admin too
admin is not being translated

**Comment by woshka** [comment]
there is also a training for this
https://amasty.com/knowledge-base/change-default-language-in-magento-2.html
it is also stated to change the language in admin per user and it is not set globaly in admin panel

**Comment by bahramdavoodi** [comment]
@woshka 
maybe you did somethings false. it's working fine with Persian language.
i had translated all stings. when you need persian language you can send a email to : info@magonex.com

![screen shot 2018-05-12 at 04 23 52](https://user-images.githubusercontent.com/18647834/39952666-66fc79d8-559c-11e8-8c25-3e11af11fd39.png)

**Comment by ananth-iyer** [comment]
Please close this issue as there is no issue in Magento code.

**Comment by engcom-backlog-nickolas** [comment]
@woshka, thanks you for your report. Unfortunately I cannot reproduce this issue by described steps too. 
If you'd like to update it, please reopen the issue.
