### ISSUE TITLE
Export / Import csv file validation errors - magento default import/export sucks since 2008!

### ISSUE THREAD

**Issue by magenx** [magento/magento2#15153]
### Preconditions
1. Magento 2.2.3 create many different products.
2. Reindex / clear cache.

### Steps to reproduce
1. Export products with defaullt export settings.
2. Delete all products.
3. Import all products with default import settings as is.
4. Import into the same shop or any different shop.

### Expected result
1. Products must be imported as is.

### Actual result
1. Import fails because of many different validation errors.
2. Duplicate url keys error.
3. Fields not properly parsed.

Do you really think that this is normal for e-commerce software, created since 2008, more than 10 years do not have reliable/robust export - import functions ?????

**Comment by dmanners** [comment]
Hi @magenx we appreciate your concern on the matter and we are trying to improve the import/export processes as we speak.

We are running two projects with the help of the community.

1. [Import/Export improvements](https://github.com/magento-engcom/import-export-improvements): The aim of this project is improve what is currently in place with the import/export features in Magento2.
2. [BulkAPI](https://github.com/magento-engcom/bulk-api): though this project is not specific to import/export one of the aims is to rebuild the import/export functionality on top of the new bulk api operations.

If you have the desire and time to help out with these projects please let us know.
