### ISSUE TITLE
The CAPTCHA block isn't displayed while checking out as guest with Magento 2.2.4

### ISSUE THREAD

**Issue by Alex1844** [magento/magento2#15164]
### Preconditions

1. Clean Magento 2.2.4 installed with Onepage Checkout enabled

### Steps to reproduce

1. In admin, select Store-Configuration-Customers-Customer Configuration and enable captcha for Guest checkout

<img width="1180" alt="screen shot 2018-05-11 at 5 54 12 pm" src="https://user-images.githubusercontent.com/39203655/39948562-94215346-5544-11e8-828a-c269caf11986.png">

2. Go to the store, add item and click on purchase without creating an account or login.

### Expected result

1. Captcha should be displayed for guest checkout

### Actual result

1. No captcha is displayed. All other forms (login etc) show captcha correctly

**Comment by anant-svc** [comment]
Did you flush cache before checking?
From here: `System` > `Cache Management` > click `Flush Cache` button

**Comment by Alex1844** [comment]
Yes, I have

**Comment by kaushik-chavda** [comment]
@magento-engcom-team please assign to me

**Comment by anant-svc** [comment]
@Alex1844  Can you point out where you expected the captcha on checkout page? using screenshot

**Comment by anant-svc** [comment]
Please check Checkout as Guest captcha here:
![m2_15164_issue](https://user-images.githubusercontent.com/5195107/40012666-f994aada-57c8-11e8-8871-9f6de75a6738.png)

**Comment by Alex1844** [comment]
I expect it when checking out as a guest, someone who is not a registered customer at all.

![captchacapture](https://user-images.githubusercontent.com/39203655/40023719-fc723350-5799-11e8-8277-6d33b16f4887.JPG)

**Comment by popatkaran** [comment]
@Alex1844  This is not an Issue as customer is not registering an account here or getting login.
#dmcdindia

**Comment by anant-svc** [comment]
Hello @magento-engcom-team I think there is no issue in magento core regarding Checkout as Guest. I mentioned the screenshot also.
So I request you to close this issue.

**Comment by Alex1844** [comment]
What does it mean "there is no issue"?

There is an option to enable captcha on the guest checkout. If the feature is not available then remove it, do not leave it in the options and say there is no issue.

There is the same feature in Open Cart since forever and it works just fine

**Comment by anant-svc** [comment]
Checkout as Guest means if customer's email is registered on Magento store. Because visitors are not registered customer.

**Comment by Alex1844** [comment]
That makes no sense. Registered user is not a guest. Why would a registered user want to checkout signed out?
Most people want to checkout without having to register an account.

**Comment by anant-svc** [comment]
Thats your own business logic. But in ours customers mostly are registered and if not they get registered themself. We don't have to enable - Checkout as Guest captcha. Its very rare case that we have to enable it.

Its like Customer login captcha but here registered customer don't want to visit login page then refresh or visit checkout page just because he/she was not logged in to Magento store. Saves customer's time and increase revenue.

Although you can implement for your Magento store projects.

**Comment by anant-svc** [comment]
It seems that there are few registered customers in your Magento 2 store and you get frustrated.

But in our client's Magento 2 store there mostly registered customers. Be cool!

**Comment by anant-svc** [comment]
It seems that there are few registered customers in your Magento 2 store and you get frustrated.

But in our client's Magento 2 store there mostly registered customers. Be cool!

**Comment by vivekaris** [comment]
@Alex1844 i am also facing this issue. it may be issue in Magento 2.2.4.

**Comment by ghost** [comment]
@Alex1844, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by santhoshnsscoe** [comment]
@anant-svc you need to change the text "Check Out as Guest" to "Checkout Login". It is confusing, as we think that captcha will come in guest checkout page. But, actually you have implemented it on checkout login only.

If Checkout as guest captcha also there, it would be great.

Is there any feature to add captcha in payment pages also. Like captcha on credit card form and cash on delivery.

**Comment by ananth-iyer** [comment]
@santhoshnsscoe Yes the "Checkout as Guest" phrase is confusing and misunderstood. Will think of an exact meaningful phrase soon. I didn't implement this captcha feature on checkout.

Secondly, to add captcha in payment pages like Credit card form you need to override their templates into your module or theme and add captcha code there. You need to check if captcha code is correct on "Place order" button click also. And its possible to captcha in payment forms.

**Comment by oscarsanch** [comment]
@magento I'm working on it

**Comment by sdzhepa** [comment]
It seems this issue is not actual anymore.
Title was renamed in Admin
![2020-11-06_14-21-26](https://user-images.githubusercontent.com/3409584/98411307-6c799a00-203b-11eb-8d66-98c31646b0b7.jpg)

![2020-11-06_14-21-45](https://user-images.githubusercontent.com/3409584/98411325-73a0a800-203b-11eb-89d4-7e5eacd70053.jpg)
