### ISSUE TITLE
configurable products prices values are not displaying accurately in magento 2.1 after migration

### ISSUE THREAD

**Issue by rajwiner** [magento/magento2#15170]
I have done migration for our site from magento 1.8 to magento 2.1. But after migration configurable products prices values are not displaying accurately. Please tell me how can i solve this problem. How can correct all products display prices accurately. Please help to solve this problem.

**Comment by magento-engcom-team** [comment]
@rajwiner please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
