### ISSUE TITLE
Amazon Logs 404 error Magento 2.2.4

### ISSUE THREAD

**Issue by jignesh-baldha** [magento/magento2#15188]
### Preconditions
1. Magento Version 2.2.4
2. PHP Version 7.0.30
3. MySQL version 5.7.22
4. Apache/2.4.18 (Ubuntu)

### Steps to reproduce
1. I've installed latest Magento ver 2.2.4
2. When I click on below Amazon log menu it shows 404 error
- System > Amazon Logs > Client
- System > Amazon Logs > IPN

### Expected result
1. It should show Amazon Client and IPN logs.

### Actual result

1. ![2018_05_14_amazon_client_log](https://user-images.githubusercontent.com/24771248/39983990-423473ee-5777-11e8-9cc9-40beec4bde54.png)
2. ![2018_05_14_amazon_ipn_log](https://user-images.githubusercontent.com/24771248/39983999-4c94f8c2-5777-11e8-8627-c3aa5c6c87c4.png)

**Comment by hostep** [comment]
Confirmed on a cleanly installed Magento 2.2.4 installation (it's good to see the QA departement of Magento is doing such a great job of testing new modules)

**Comment by prayagr** [comment]
Hello everyone, we are aware of this issue and will address it in the next release. The 404 only occurs when there are no relevant logs present. Please follow the issue here: https://github.com/amzn/amazon-payments-magento-2-plugin/issues/178

**Comment by Ctucker9233** [comment]
Same issue here. Any idea what version this will be fixed in?

**Comment by magento-engcom-team** [comment]
@jignesh-baldha @Ctucker9233 
Closing, as relates to https://github.com/amzn/amazon-payments-magento-2-plugin/issues/178
