### ISSUE TITLE
Upgrade Magento version without extra bundled extensions

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#15189]
I want to upgrade from v2.2.1 to 2.2.4 and my php version is 7.0.12
Since the 2.2.4 version comes prebundled with klarna/* modules which require php "^5.6|~7.0.13|~7.1.0"
I would like to not include those modules in my upgrade. 

There should be a method to specify an unnecessary modules

.

### Preconditions
1. php 7.0.12
2. community edition 2.2.1

### Steps to reproduce
1. composer require magento/product-community-edition 2.2.4 --no-update
2. composer update

### Expected result
1. possibility to exclude extra unnecessary modules from update

### Actual result
1. installation stops at module klarna/core php requirements
![magento upgrade](https://user-images.githubusercontent.com/20812705/39985186-731526d6-5766-11e8-8538-9cd23f37cfa8.png)

**Comment by hostep** [comment]
All Magento modules will require at least PHP 7.0.13 in a future version (possibly 2.2.5?), see this commit for more info why: https://github.com/magento/magento2/commit/55657e12abfe3681022ed1e545cbdbb01cba712a

I'd recommend you to upgrade your PHP version (if possible) to at least 7.0.13
After that the upgrade should go fine.

But I can understand your frustration with all these new "Core Bundled Extensions" (that's the official name of these things) being included in Magento. We simple just install them and then disable the ones we don't need (basically all of them :))

**Comment by theodorhanu** [comment]
Thanks for clarifying the PHP version upgrade part. I upgraded it to 7.1

As for the bundled extensions, I still find the default inclusion in "core pack" unnecessary and inappropriate.
