### ISSUE TITLE
magento 2 install error

### ISSUE THREAD

**Issue by AbedOmari** [magento/magento2#15181]
I'm installation magento 2 on windows 10 using xampp server but facing this error
Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...
![magento](https://user-images.githubusercontent.com/26723838/39966708-37f0103c-56b9-11e8-8615-d32454e3a531.PNG)

**Comment by magento-engcom-team** [comment]
@AbedOmari Unfortunately this report does not contain enough information to reproduce the issue. Please see devdocs section on Web installation on devdocs: https://devdocs.magento.com/guides/v2.2/install-gde/install/web/install-web_6-install.html
Please format issue according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen. 
Thanks.
