### ISSUE TITLE
Unable to register new Commands when module is loaded via vendor

### ISSUE THREAD

**Issue by jamescowie** [magento/magento2#1519]
Hello,

I am experimenting with loading modules via the vendor folder, I can register my module successfully ( E.g. when I run `./bin/magento setup:upgrade` I can see that my module is present in the list ) However when I try to add a custom command to the magento cli there is no new command.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\Console\CommandList">
        <arguments>
            <argument name="commands" xsi:type="array">
                <item name="builderCommand" xsi:type="object">MageCasts\ModuleBuilder\Command\Builder</item>
            </argument>
        </arguments>
    </type>
</config>
``` 

```php
<?php
namespace MageCasts\ModuleBuilder\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Command\Command;
/**
 * Class Builder
 * @package MageCasts\ModuleCreator\Command
 */
class Builder extends Command
{
    /** @var \MageCasts\ModuleBuilder\Model\ModuleBuilder $moduleBuilder */
    private $moduleBuilder;
    /**
     * @param \MageCasts\ModuleBuilder\Model\ModuleBuilder $moduleBuilder
     */
    public function __construct(\MageCasts\ModuleBuilder\Model\ModuleBuilder $moduleBuilder)
    {
        $this->moduleBuilder = $moduleBuilder;
        parent::__construct();
    }
    /**
     * Configure the correct options for the console command
     */
    protected function configure()
    {
        $this->setName('magecasts:module-builder');
        $this->setDescription('Build a magento 2 module from the command line');
        $this->addArgument(
            'name',
            InputArgument::REQUIRED,
            'Please enter the name of your module'
        );
        parent::configure();
    }
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $moduleName = $input->getArgument('name');
        $buildModule = $this->moduleBuilder->createModuleDirectory($moduleName);
        $output->writeln($buildModule);
    }
}
```

When I use the module type of magento2-module and it is loaded via `app/code/MageCasts/ModuleBuilder` then the CLI command is present. So perhaps there is a reference to the XML files that is not working under this implementation.

**Comment by fooman** [comment]
Did you try with Vinai's patch included https://github.com/magento/magento2/pull/1490?

**Comment by jamescowie** [comment]
Interesting, I have not tried the patch in @Vinai 's. However I have also found another potential issue to how the modules work from vendor now.

```
"autoload": {
    "psr-4": {
      "Jcowie\\Demo\\": "src/Jcowie/Demo"
    },
    "files": [ "bootstrap.php" ]
  }
```

So I have created a composer.json file with the above contents for my autoloader of the module and this also tells composer that it should register `bootstrap.php` with composer to register more messages ( In this case register my module with Magento ). However the problem comes around in 2 parts. If I now install PHPSpec, Behat or PHPUnit I am unable to run these from anywhere where magento is not installed. So trying to test these modules in isolation is not possible. 

It also means that modules are never installable in any other location other than magento. ( Having truly portable extensions is a far edge case ) 

To provide some more context, I have created a folder outside of Magento that contains my modules src directory where I also wanted to created tests / specs. Problem being that bootstrap contains `Magento\Framework\Module\Registrar::registerModule` and throws a fatal error that class is not found... 

Now a temporary solution I have found to get this working is: 

```
{
  "name": "Jcowie/Demo",
  "require": {
    "symfony/yaml": "2.*",
    "symfony/filesystem": "~2",
    "composer/composer": "1.0.0-alpha10"
  },
  "require-dev": {
    "phpspec/phpspec": "2.2",
    "bossa/phpspec2-expect": "1.0.3",
    "magento/magento2ce": "1.0.0-beta"
  },
  "autoload": {
    "psr-4": {
      "Jcowie\\Demo\\": "src/Jcowie/Demo"
    },
    "files": [ "bootstrap.php" ]
  },
  "autoload-dev": {
    "psr-4": {
      "Magento\\" : "vendor/magento/magento2ce/app/code/",
      "Magento\\Framework\\": "vendor/magento/magento2ce/lib/internal/"
    }
  },
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/magento/magento2"
    }
  ]
}
```

However here I am relying on autoloading magento again in the module. This will also be passed into the main composer autoloader when converged with Magento.. 

Does this make sense what I am trying to achieve and the currently implemented workaround ?

**Comment by Vinai** [comment]
On a side note, I really dislike the name `bootstrap.php` for the composer autoloader callback.
That said, you raise an interesting topic. I agree that requiring a workaround is pretty hackish. At the moment I don't have an answer either. This should be addressed.

**Comment by joshdifabio** [comment]
> Problem being that bootstrap contains `Magento\Framework\Module\Registrar::registerModule` and throws a fatal error that class is not found...

I'd suggest this:

```php
use Magento\Framework\Module\Registrar;

if (class_exists(Registrar::class)) {
    Registrar::registerModule(...);
}
```

**Comment by piotrekkaminski** [comment]
There are significant changes in this area coming from an update for loading Magento from vendor directory that will be published soon.

**Comment by daim2k5** [comment]
@jamescowie i think in the RC is a fix included. If not please free to reopen the issue
