### ISSUE TITLE
Updating Special price thought ProductRepository via API m2.2 EE does not save right value.

### ISSUE THREAD

**Issue by nei** [magento/magento2#15199]
I am trying to update special_from_date/special_to_date/special_price on Magento ver. 2.2.3 EE via API on the same product update endpoint.

I see it is now part of the catalog Staging module and there are specific endpoints for this. but for what I've seen on the code it was supposed to work using observers on the product which I assume I should be able to pass via product update.

What I've done:
I wonder if there is a way to set this on the /v1/products/{sku} as extension attributes.

I've tried to set this on my Product update: 
```
                 "sku": "SKUU",
		"name": "NAME OF MY PRODUCT",
		"status": 1,
		"visibility": 4,
		"price": 1,
		"type_id": "simple",
		"weight": "0.27",
		"extension_attributes": {
			"stock_item": {
				"stock_id": 1,
				"qty": 86,
				"is_in_stock": false,
				"manage_stock": false,
				"use_config_manage_stock": false
			}
		},
		"custom_attributes": [
			{"attribute_code": "special_from_date","value": "2018-07-01 10:00:00"},
			{"attribute_code": "special_to_date","value": "2018-09-15 11:00:00"},
			{ "attribute_code": "special_price", "value": 3 }]
...
```
But then, when I query /rest/V1/products/special-price-information I get this:
```
[
    {
        "price": 3,
        "store_id": 0,
        "sku": "SKUU",
        "price_from": "1970-01-01 00:00:01",
        "price_to": "2038-01-19 03:14:07"
    }
]
```
the dates are completely wrong. This generate an issue on the product edit page where I cannot save the product anymore due to this error message: 
```
Make sure the To Date is later than or the same as the From Date.
```
### Preconditions
1. Magento ver. 2.2.3 EE

### Steps to reproduce
1. Create a product via API passing special_from_date, special_to_date, special_price 
2. Query the special price via /rest/V1/products/special-price-information
3. Check the values

### Expected result
1. After creating the product, I would expect to see the correct dates on the special-price-information response.

### Actual result
1. Special price was not set properly.

**Comment by engcom-backlog-nickolas** [comment]
Hello @nei, thank you for your report. Unfortunately I couldn't reproduce this issue on 2.2.3 Community Edition.
![peek 2018-07-12 16-37](https://user-images.githubusercontent.com/40755810/42636617-e6afaf44-85f1-11e8-9388-88d967290539.gif)
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by joaolisboa** [comment]
I also have a similar issue. I can update the dates through the API, but it's impossible to update a product through the admin when the special_price is set. This happens in Enterprise version because Magento has removed these fields from the admin, which causes the update to fail when submitting the form I'm guessing. I've opened a ticket with Magento themselves, escalated to the developers and I'm kind of tired of having no answer yet for something that is so critical.

I don't understand how something like this was even considered. The fields were removed in EE in favour of using the scheduled changes, but nothing was done to the API as a replacement, which causes this 'conflit'. We set special prices through API, and when we have products in promo, it's impossible to update them while they have an active special_price, it always returns the same error as above 'Make sure the To Date is later than or the same as the From Date.'.

**Comment by roshanyadav89** [comment]
> I also have a similar issue. I can update the dates through the API, but it's impossible to update a product through the admin when the special_price is set. This happens in Enterprise version because Magento has removed these fields from the admin, which causes the update to fail when submitting the form I'm guessing. I've opened a ticket with Magento themselves, escalated to the developers and I'm kind of tired of having no answer yet for something that is so critical.
> 
> I don't understand how something like this was even considered. The fields were removed in EE in favour of using the scheduled changes, but nothing was done to the API as a replacement, which causes this 'conflit'. We set special prices through API, and when we have products in promo, it's impossible to update them while they have an active special_price, it always returns the same error as above 'Make sure the To Date is later than or the same as the From Date.'.

I am also facing same issue on EE 2.3.3

**Comment by roshanyadav89** [comment]
Hi All,

as per your document price_to is optional in API but it's not optional it's necessary on Magento 2 EE 2.3.3

https://devdocs.magento.com/guides/v2.3/rest/modules/catalog-pricing.html

I am facing some serious issues related to adding/set a special price of the same product / SKU with multiple stores using API.

The same issue exists from the backend also.
++++++++++++++++++

Tried adding store_code in an API same issue exists.
For Example:

Kuwait Store:
POST /rest/kw_en/V1/products/special-price
{
"prices": [
{
"price": 55.24,
"store_id": 14,
"price_from": "2021-01-06 15:01:40",
"price_to": "2021-05-16 23:59:59",
"sku": "xyz"
}
]
}
++++++++++++++++++++++
UAE Store:
POST /rest/ae_en/V1/products/special-price
{
"prices": [
{
"price": 59.54,
"store_id": 16,
"price_from": "2021-01-06 15:01:40",
"price_to": "2021-05-16 23:59:59",
"sku": "xyz"
}
]
}
++++++++++++++++++++++
3 ) Saudi Arabia Store:
POST /rest/sa_en/V1/products/special-price
{
"prices": [
{
"price": 81.51,
"store_id": 18,
"price_from": "2021-01-06 15:01:40",
"price_to": "2021-05-16 23:45:54",
"sku": "xyz"
}
]
}
++++++++++++++++++++++++++
No luck same issue exists from both ways APIs as well as backend.
Please have a look as soon as possible.

**Comment by roshanyadav89** [comment]
https://github.com/magento/devdocs/issues/8504
