### ISSUE TITLE
unable to  send and receive emails from Magento2 site 

### ISSUE THREAD

**Issue by Rakeshsivagouni** [magento/magento2#15195]
I have tried to install Magento 2.2.3 on AWS ec2 instance. magento site is working normally but I am unable to receive emails from Magento to reset the password for my admin account. I have installed mageplaza but I'm unable to find mazeplaza icon on my Magento site admin dashboard still I am facing issues with email sending option both customer and admin accounts.

**Comment by popatkaran** [comment]
@Rakeshsivagouni 

I have also faced issue with Mageplaza extension, try to check with Magepal extension.
PS: first try to check with simple php mails are working on your server or not.

**Comment by magento-engcom-team** [comment]
@Rakeshsivagouni please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
