### ISSUE TITLE
Getting issue for Item price on Cart and Checkout page for lo_LA locale

### ISSUE THREAD

**Issue by ghost** [magento/magento2#15191]
I have a Magento with 2 store views, one is for en_US locale and other is for lo_LA locale. I created a new product and added it to the cart, everything works similar as it should, except Item price on Cart Summary for Cart and Checkout page.

### Preconditions
1. Magento version 2.2
2. 2 Store Views with different locale : en_US and lo_LA

### Steps to reproduce
1. Create a new product and add to cart.
2. On cart page, change Store view from en_US locale to lo_LA locale.

### Expected result
1. Subtotal Price should be similar in Cart Summary and Items Subtotal.

### Actual result
1. Different Subtotal Price appearing on Cart Page for Cart Summary and Item's Subtotal. Please check screenshots.

![en_us cart page](https://user-images.githubusercontent.com/39259107/39985717-1d55ccde-577d-11e8-87af-8bcba58e5ef2.png)
![lo_la cart page](https://user-images.githubusercontent.com/39259107/39985718-1dae9404-577d-11e8-8454-61fd16507324.png)

**Comment by sunilit42** [comment]
@ManishGangola-Webkul 

I checked with that locale and it is working fine.

Are you using any custom module?

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-15191-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-15191-2-3-develop.instances.magento-community.engineering/admin](https://i-15191-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
