### ISSUE TITLE
magento

### ISSUE THREAD

**Issue by pythondevshiv** [magento/magento2#15193]
I'm installation magento 2 (Magento-CE-2.0.2) on local server i mean on cpanel but facing this error, i did everything according to magento 2 installation requirement but at the end i don't know how to solve this error.

Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

**Comment by DanielRuf** [comment]
Which exact error?

**Comment by magento-engcom-team** [comment]
Hi @pythondevshiv 
We are closing this now due to inactivity. Please update description and reopen if issue persists.
