### ISSUE TITLE
Saving Category always sets default store: bug in store manager.

### ISSUE THREAD

**Issue by wintermute-84** [magento/magento2#15215]
### Preconditions
Magento 2.2.4

### Steps to reproduce
Saving/creating category programmatically
1. Try setting store using:
`$this->category->setStoreId(0); `
2. Try setting store using: 
`$this->storeManager->setCurrentStore(0);`
3. Use Category Repository to save the object.

### Expected result
Category data should be stored under provided store, not default store.

### Actual result
`$this->category->setStoreId(0); ` doesn't work because Magento\Catalog\Model\Repository::save() always overwrites store on the object: `$existingData['store_id'] = $storeId;`

`$this->storeManager->setCurrentStore(0);` doesn't work, because Magento\Store\Model\StoreManager::getStore() has this line: `if (null == $this->currentStoreId) {`
that resolves to true when $this->currentStoreId = 0
Why === is not used?

So now the only way to set admin store is to use `$this->storeManager->setCurrentStore('admin');`
Which should not be the case, since later store manager expecting storeId to be string or numeric.

**Comment by hostep** [comment]
@wintermute-84: just out of curiosity I checked the line you were referencing, but it looks fine to me, you didn't accidentally change it yourself while debugging perhaps?
See: https://github.com/magento/magento2/blob/2.2.4/app/code/Magento/Store/Model/StoreManager.php#L155

**Comment by Aerue** [comment]
I just come accross this problem.
The CategoryFactory just should use the storeId passed in before calling storeManager to get the storeId.

Temporary fixed that by doing the following

    $categoryProto = $this->categoryFactory->create();
    $categoryProto->setParentId(2);
    $categoryProto->setIsActive(false);
    $categoryProto->setName('Admin name');
    $this->storeManager->setCurrentStore(0); // Store admin id
    $categoryProto = $this->categoryRepository->save($categoryProto);

    $categoryFr = $this->categoryRepository->get($categoryProto->getEntityId(), 1);
    $this->storeManager->setCurrentStore(1); // Store fr id
    $categoryFr->setName('Fr name');
    $this->categoryRepository->save($categoryFr);

**Comment by wintermute-84** [comment]
actually === is not an issue. We had a faulty patch that did that, so my bad. 
But the store overwrite is still there.

**Comment by ghost** [comment]
@wintermute-84, thank you for your report.
This is an intended behavior. Method "setStoreId" is absent in CategoryInterface, so you should not expect it to work. Please use "setCurrentStore" method of StoreManagerInterface.

**Comment by LucianMihalache** [comment]
Why is this still not fixed?
There is a problem when you want to send/sync categories on some site via api.
The store used is only the default store, but if I have multiple stores? Thats imposible.
Let's say that I have a single store only. When I update the category via api, the backend does not see the changes because the admin is on store view 0, while my default store view (the frontend) is 1...
This is again wrong.

**Comment by kirtinariya1** [comment]
Still issue reproduce in Magento 2.3.1 while importing categories.

**Comment by schmengler** [comment]
> This is an intended behavior. Method "setStoreId" is absent in CategoryInterface, so you should not expect it to work. Please use "setCurrentStore" method of StoreManagerInterface.

I'd be interested to see an example in the core. It is 2020 and there is **not a single occurence** of `CategoryRepository::save()` in the core, except in tests. The admin controller even uses the deprecated `$category->save()` method.

Setting a "current store" global state to manage scoped entities sounds like a bad idea and apparently @magento-engcom-team agrees, otherwise you would use it yourself.

**Comment by WebKenth** [comment]
![image](https://user-images.githubusercontent.com/13419123/107348488-5b6f7780-6ac7-11eb-9aa5-e1ac654e8486.png)
Why is this a thing?

A closed Issue that is reproducible with a core bug alot of activity, yet just closed?

**Comment by rintoug** [comment]
> I just come accross this problem. The CategoryFactory just should use the storeId passed in before calling storeManager to get the storeId.
> 
> Temporary fixed that by doing the following
> 
> ```
> $categoryProto = $this->categoryFactory->create();
> $categoryProto->setParentId(2);
> $categoryProto->setIsActive(false);
> $categoryProto->setName('Admin name');
> $this->storeManager->setCurrentStore(0); // Store admin id
> $categoryProto = $this->categoryRepository->save($categoryProto);
> 
> $categoryFr = $this->categoryRepository->get($categoryProto->getEntityId(), 1);
> $this->storeManager->setCurrentStore(1); // Store fr id
> $categoryFr->setName('Fr name');
> $this->categoryRepository->save($categoryFr);
> ```

While saving a category this process is still relevant in 2.4.6. We have to set the current store, to get it saved for a particular store.
