### ISSUE TITLE
You did not sign in correctly or your account is temporarily disabled

### ISSUE THREAD

**Issue by tizzyguy87** [magento/magento2#15214]
We are using Magento 2.2 community edition as headless commerce (exposed as rest APIs), My SQL on AWS. I am facing issue in our application.

When customers exceeds Max password limits, even customer resets password login is not working.

I have gone through blogs they told me couple of things. Below are few suggestions.

1. unlock user from command. Everywhere I found command to unlock admin user but not customer. So I didn't do this. Eg command : php bin/magento admin:user:unlock ADMINUSERNAME2. 
3. Delete oauth_token_request_log table This table is already empty. Nothing to delete. 
5. delete /var/cache - no luck even after deleting cache folder

Apart from above suggestion i did below things too. Still no luck.

1. Delete entries for customer in password_reset_request_event (even though customer is able to reset password)
2. Set failure_num to 0, first_failure to NULL

Please help me in resolving this issue as this is happening in production.

FYI - Though I have set lock expiry time, lock_expires is never getting updated. So I have changed configuration to never lock a user. Still issue is there.

**Comment by magento-engcom-team** [comment]
Hi @tizzyguy87 
Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks

**Comment by amanmehndiratta25** [comment]
I'm facing the same error may i know that where to run the commands ?

**Comment by lunch22result** [comment]
You can try to create new admin account and use that account to reset password of your existing account
`bin/magento admin:user:create --admin-firstname="magentip" --admin-lastname="demo" --admin-email=magentip@gmail.com --admin-user=magentip --admin-password=Qwe@123456
`
Reference source: [](https://magentip.com/how-to-fix-you-did-not-sign-in-correctly-or-your-account-is-temporarily-disabled-in-magento-2/)
