### ISSUE TITLE
Contact Us Page two times same value of `ID` attribute value for email field

### ISSUE THREAD

**Issue by cnviradiya** [magento/magento2#15217]
### Preconditions

1. Magento Version is 2.2.0 and after installation complete upgrade sample data
2. Php Version is 7.1.8
3. MySQL version is 4.7.0
4. Operating System Window 10Pro
5. Screen Resolution is 1920 x 1080

### Steps to reproduce

1. Go to the contact us page
2. Open inspect element in chrome, It will automatic display the duplicate attribute value of email field
3. Contact us fields email input contain `id='email'` & newsletter form also contain email input contain `id='email'`

### Expected result

1. On the single page `id` attribute will be always unique. So, It would be unique either contact us form input email field or either newsletter email input filed `id` attribute value

### Actual result

1. ![contact_page_duplicate_id field_value_15_05_2018](https://user-images.githubusercontent.com/9442993/40048743-9920540a-5850-11e8-85a0-677b6f4a0b1a.png)

**Comment by Karlasa** [comment]
As show in error, its conflict between email and username field, not with newsletter block. 
It's in conflict with popup login form username field 
Seems like it's old issue and allready fixed in current version. You should update to newer version.
dublicate of  #12712
