### ISSUE TITLE
products not showing on category page.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#1521]
I have imported the sample-data:1.0.0-beta into the magento2 setup but after the proper import and upgrade, on category page no products are showing. Please let me know how this issue can be fixed.

Here are the screen shots.

![image](https://cloud.githubusercontent.com/assets/6079017/8775614/8c87eb60-2f07-11e5-833a-270f48d5790c.png)

![image](https://cloud.githubusercontent.com/assets/6079017/8775623/9e8945a2-2f07-11e5-98e8-c3cf32dde090.png)

Here is the test repo url : https://github.com/ankursachdeva11/magento2_test

Please help me.

**Comment by rganin** [comment]
Did you run reindex after importing?
`php -f bin/magento indexer:reindex` - for full reindex
Also add `php -f bin/magento cron:run` to your crontab, it executes reindex tasks by schedule if they are required.

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor.

**Comment by kartikasodariya17** [comment]
I have used new theme and when i create new product then it's not display on category page also i have do it indexing and cleaning the cache. can you please suggest me how can i resolve the issue ?

**Comment by gecko00790** [comment]
I am having the same issue, but only some of my categories are not displaying a list of the products. already ran full reindex. using Magento 2.1.2

**Comment by santhoshnsscoe** [comment]
I am having the same issue, but only some of my categories are not displaying a list of the products. already ran full reindex. using Magento 2.1.2
