### ISSUE TITLE
Refactor docblock for variables

### ISSUE THREAD

**Issue by springimport** [magento/magento2#15225]
### Preconditions
Docblocks in code like this:
```php
/** @var \Magento\Sales\Model\Order $order */
```

### Expected result
I think it will be more correct:
```php
/** @var \Magento\Sales\Api\Data\OrderInterface $order */
```

Magento CE 2.2.3.

**Comment by magento-engcom-team** [comment]
Hi @springimport 
This is a perfectly valid suggestion and already covered by [Magento 2 Technical Guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html) for all new code added to the core. 
Unfortunately, as of now, fixing all of the existing occurrences is not a top priority. We may or may not revisit this in the future.

Thanks. Closing, there is no clear action point for now.
