### ISSUE TITLE
Suggestion to replace platform comment to information block in issue template

### ISSUE THREAD

**Issue by springimport** [magento/magento2#15226]
I suggest to add Q&A block to issue template with information about magento 2 version, php version, etc.
Good example is [Yii2 issue template](https://github.com/yiisoft/yii2/issues/new).
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |
```

```<!--- (This may be platform independent comment) -->``` can be replaced by new block.

Example for magento:

-----------------

### Preconditions
1. Step 1.

### Steps to reproduce
1. Info.

### Expected result
1. Expected result.

### Actual result
1. Actual result.

### Additional info

| Q                | A
| ---------------- | ---
| Magento version      | CE 2.2.4
| PHP version      | PHP 7.1 x64
| Operating system | Ubuntu 18.04

**Comment by ghost** [comment]
@springimport, this GitHub issue tracker is intended for Magento Core technical issues only.
