### ISSUE TITLE
Magento 2.2.3 Multisite - Category Is anchor Save error

### ISSUE THREAD

**Issue by sneha-sukumaran** [magento/magento2#15223]
### Preconditions
1. PHP 7.1
2. Migrated form Magento 1.7 to Magento 2.2.4
3. Multi-currency and Multilingual site

### Steps to reproduce
1. Migrate multi-currency and multilingual site from Magento 1.7 to Magento 2.2.3
2. Goto an existing Category and try to change Is anchor from Yes to No
3. Click on save

### Expected result
1. Category Is Anchor should be saved to No

### Actual result
1. The categoryis not Saving and getting an error
2.Warning: ltrim() expects parameter 1 to be string, array given in /home/bbfarm/tcs/vendor/magento/module-catalog/Model/Category/FileInfo.php on line 102

![screenshot 48](https://user-images.githubusercontent.com/20576611/40061780-527205f4-5877-11e8-81ca-d91ca7f8db3e.png)

**Comment by popatkaran** [comment]
@sneha-sukumaran 

Have you tried reindexing after migration?

**Comment by sneha-sukumaran** [comment]
Yes i did. But no change

**Comment by popatkaran** [comment]
@sneha-sukumaran 
This function is checking files, do you have any file attribute to migrate? have you check category images on proper path? This might cause an issue.

**Comment by engcom-backlog-nickolas** [comment]
Hello @sneha-sukumaran, thank you for your report. I cannot reproduce this issue on clean 2.2.4 magento installation. Please use https://github.com/magento/data-migration-tool/issues to report issues related to migration from magento 1.x to 2.x.

**Comment by zeshanrahman** [comment]
any solution related to above issue same issue i am facing
