### ISSUE TITLE
Post code missing from checkout on merchant beta.

### ISSUE THREAD

**Issue by miguelbalparda** [magento/magento2#1522]
While trying to place an order in a fresh Magento2 I noticed the post code field is missing. No modules, no changes, fresh installation from the official GitHub repo.

![nopost](https://cloud.githubusercontent.com/assets/3997682/8777855/cb579818-2eb7-11e5-998f-1a446cc13626.png)
![rsz_post](https://cloud.githubusercontent.com/assets/3997682/8777854/cb571abe-2eb7-11e5-9cbe-15d5c8aab45a.png)

**Comment by miguelbalparda** [comment]
Steps to replicate: 
- Add Stellar Solar Jacket. 
- Go to cart, use the shipping widget. I entered California - USA - 90210. Calculate shipping. 
- Go to checkout and fill the required info. No post code field in there.
- Go to payment and try to place the order.

**Comment by piotrekkaminski** [comment]
@miguelbalparda do you still have this issue?

**Comment by miguelbalparda** [comment]
Not while using mobile, I will check desktop as seen as I can get a computer.

**Comment by daim2k5** [comment]
@miguelbalparda do you still have this issue?

**Comment by miguelbalparda** [comment]
No, I was not able to replicate this on http://magento2-demo.nexcess.net but the preselected shipping rate has no effect on the checkout since I have to fill everything again and select a shipping method.

**Comment by miguelbalparda** [comment]
After doing steps 1-3 I get

![car](https://cloud.githubusercontent.com/assets/3997682/10948097/9b4a6bbc-830a-11e5-9a69-a1b16f658a9e.png)

![checkou](https://cloud.githubusercontent.com/assets/3997682/10948082/88923400-830a-11e5-8945-c638d8f6a362.png)

**Comment by miguelbalparda** [comment]
After filling everything in the checkout screen I was able to place an order.
