### ISSUE TITLE
Cart Price Rule: Action tab condition category table is not working 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#15241]
We are facing problem on action condition. At the time to apply the rule for the specific category.  the category select table is not working. 
### Preconditions

1. Magento Version 2.2.4 with sample data 
 

### Steps to reproduce

1. Create cart price rule 
2. From Action tab select category option to apply the condition and open category select table.
3. Category table will not open 

### Expected result

1. Category table open and the user can select the category for applying the rule 

### Actual result
1. Category table shows the empty result 

1. [Screenshot, logs]
[Category_Select_issue.mp4.zip](https://github.com/magento/magento2/files/2007608/Category_Select_issue.mp4.zip)

**Comment by sunilit42** [comment]
@emiprotech 
Have you upgraded magento?

If yes then may be that issue, can you please try with new rule.

**Comment by ghost** [comment]
Hello @sunilit42 
No, This is my fresh Magento v224. 
I checked this issue in both fresh Magento and upgraded and I face this issue in both of Magento.

**Comment by hostep** [comment]
Hi @emiprotech 

I'm going to close this issue as it duplicates https://github.com/magento/magento2/issues/15121, which already got fixed in https://github.com/magento/magento2/pull/15265 and the fix should get included in Magento 2.2.5
