### ISSUE TITLE
Possiblity to add  dev , lib , setup, update folders to .gitignore

### ISSUE THREAD

**Issue by jigneshthummar** [magento/magento2#15243]
Not sure if my request is valid or not

but some of above folders (i am sure about dev) are being updated by composer , shouldn' t it be excluded from versioning ? in that case?

**Comment by magento-engcom-team** [comment]
@jigneshthummar please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
