### ISSUE TITLE
Possible issue in the category resource model _saveAttributeValue method

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#15248]
### Preconditions
1. Magento 2.2.3 with sample data
Default state:

- The config setting "Enable Single-Store Mode" is disabled
- Identical Store View - 'Default Store View' (store_id = 1)

### Steps to reproduce
1. You can successfully save some category attribute from admin area for store_id = 1 using Store Switcher.
2. Try execute it programmatically:
```php
$attributeCode = 'meta_title';
$categoryData = [
    'store_id' => 1,
    'meta_title' => 'test',
    'entity_id' => {any correct value},
    'id' => {any correct value}
];

//$this->categoryResource is  \Magento\Catalog\Model\ResourceModel\Category
$this->categoryResource->saveAttribute($categoryData, $attributeCode);
```

### Expected result
1. Category attribute will be saved for store_id = 1 as well as via the admin panel)

### Actual result
1. Category Attribute will be saved for store_id = 0

### Possible reason

Here is the fragment of \Magento\Eav\Model\Entity\Attribute\AbstractAttribute\AbstractResource::_saveAttributeValue()
```php
       /**
         * If we work in single store mode all values should be saved just
         * for default store id
         * In this case we clear all not default values
         */
        $entityIdField = $this->getLinkField();
        if ($this->_storeManager->hasSingleStore()) {
```

In the comment you wrote about `single store mode(!)` - which uses config setting value in the `isSingleStoreMode` method, and afterwards you’ve approximately been using the incorrect  `hasSingleStore` method based only on the stores qty, not taking into account your config setting.

P.S. See also `\Magento\Catalog\Model\ResourceModel\Product\Action::_saveAttributeValue(...)`

**Comment by engcom-backlog-nickolas** [comment]
Hello @sergei-sss, thank you for your report.
We've acknowledged the issue and added to our backlog.
