### ISSUE TITLE
Magento2 + Magento/blank + Magento/luma + broken styles

### ISSUE THREAD

**Issue by klierik** [magento/magento2#1525]
Good day.

1) Install Magento2
2) Install Sample Data via command line
3) Build LESS->CSS for Magento/blank and Magento/luma
```
vagrant@magento2-vagrant:/vagrant/httpdocs/bin$ php magento dev:css:deploy less css/styles-l --locale="en_US" --area="frontend" --theme="Magento/blank"
Gathering css/styles-l.less sources.
Successfully processed LESS and/or SASS files
vagrant@magento2-vagrant:/vagrant/httpdocs/bin$ php magento dev:css:deploy less css/styles-l --locale="en_US" --area="frontend" --theme="Magento/luma"
Gathering css/styles-l.less sources.
Successfully processed LESS and/or SASS files
```
4) Refresh caches in Admin panel
* Flush Magento Cache
* Flush JavaScript/CSS Cache
* Select all cache types and Refresh it

Then reboot server (vagrant) just in case but i have problem with styles:
![Magento 2 Sample data broken styles example](https://api.monosnap.com/rpc/file/download?id=VfwnzevMFBYmox1xFsmsh05Q738OKv)

Full step-by-step you can find here: https://github.com/klierik/magento2-vagrant

May be i make something wrong?

**Comment by godban** [comment]
Hello @klierik,

Looks like styles-m.css not processed. I can suggest delete pub/static and recompile styles. If it wouldn't help, please take a look to exceptions log and provide more info.

**Comment by klierik** [comment]
```
vagrant@magento2-vagrant:/vagrant/httpdocs$ ls -la pub/static
total 4
drwxrwxr-x 1 vagrant www-data  204 Jul 20 16:51 .
drwxrwxr-x 1 vagrant www-data  374 Jul 20 15:02 ..
-rw-rw-r-- 1 vagrant www-data 3247 Jul 20 15:02 .htaccess
drwxrwxr-x 1 vagrant www-data  136 Jul 20 16:50 _requirejs
drwxrwxr-x 1 vagrant www-data  102 Jul 20 16:50 adminhtml
drwxrwxr-x 1 vagrant www-data  102 Jul 20 16:51 frontend
vagrant@magento2-vagrant:/vagrant/httpdocs$ rm -rf pub/static/*
vagrant@magento2-vagrant:/vagrant/httpdocs$ cd bin/
vagrant@magento2-vagrant:/vagrant/httpdocs/bin$ php magento dev:css:deploy less css/styles-l --locale="en_US" --area="frontend" --theme="Magento/blank"
Gathering css/styles-l.less sources.
Successfully processed LESS and/or SASS files
vagrant@magento2-vagrant:/vagrant/httpdocs/bin$ php magento dev:css:deploy less css/styles-l --locale="en_US" --area="frontend" --theme="Magento/luma"
Gathering css/styles-l.less sources.
Successfully processed LESS and/or SASS files
vagrant@magento2-vagrant:/vagrant/httpdocs/bin$ ls -la ../pub/static
total 4
drwxrwxr-x 1 vagrant www-data  136 Jul 21 13:23 .
drwxrwxr-x 1 vagrant www-data  374 Jul 20 15:02 ..
-rw-rw-r-- 1 vagrant www-data 3247 Jul 20 15:02 .htaccess
drwxrwxr-x 1 vagrant www-data  102 Jul 21 13:23 frontend
```

then re-build cache:
```
vagrant@magento2-vagrant:/vagrant/httpdocs/bin$ ls -la ../pub/static
total 4
drwxrwxr-x 1 vagrant www-data  204 Jul 21 13:25 .
drwxrwxr-x 1 vagrant www-data  374 Jul 20 15:02 ..
-rw-rw-r-- 1 vagrant www-data 3247 Jul 20 15:02 .htaccess
drwxrwxr-x 1 vagrant www-data  102 Jul 21 13:24 _requirejs
drwxrwxr-x 1 vagrant www-data  102 Jul 21 13:25 adminhtml
drwxrwxr-x 1 vagrant www-data  102 Jul 21 13:23 frontend
```
now it is much better: http://take.ms/kvFtk

But, can u tell me please, why i need remove folders `pub/static/*` manually?

**Comment by godban** [comment]
@klierik good question, in my opinion you shouldn't, but for the moment there is no such functionality.
You can create feature request for that and it may appear soon if there is no cons from architects side.

**Comment by alankent** [comment]
It's a good area for review. We have been working towards separating what a developer should be doing vs a merchant in the admin panel. Some files are not "cache" - they are generated. There may be a few rough edges to work through still.  Thanks for the feedback.

**Comment by ghost** [comment]
He tried to access luma by logging in as a client and the page only refreshes and sends me to the same place, nor does it register clients
