### ISSUE TITLE
DESCRIPTION: ONLY TWO CHARACTERS

### ISSUE THREAD

**Issue by sestebandelaf** [magento/magento2#15266]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by dmanners** [comment]
Hi @sestebandelaf I am going to close this issue as there is not enough information for us to validate or proceed with this issue. Please feel free to reopen this issue with more information such as a description of the issue and steps to reproduce.

Thank you.
