### ISSUE TITLE
RuntimeException: Source class "\customerAddress" for "customerAddressMapper" generation does not exist

### ISSUE THREAD

**Issue by shreelathags** [magento/magento2#15277]
I am new to magento development. I have installed Magento 2.2.4 enterprise edition, plus my private package.
I have a custom table and a REST api which returns rows from that table. This API works fine when I tested from postman.
I created a webapi testcase to test the new API. When I try to execute this test, I get this error:
RuntimeException: Source class "\customerAddress" for "customerAddressMapper" generation does not exist.

Preconditions
1. Magento 2.2.4 enterprise edition
2. PHP 7.0.30

Steps to reproduce
1. Private package with a REST API and webapi testcase
2. cd dev/tests/api-functional directory and issue ../../../vendor/bin/phpunit command

Expected result
Test should pass

Actual result
`RuntimeException: Source class "\customerAddress" for "customerAddressMapper" generation does not exist.

/projects/magento2_code/vendor/magento/framework/Code/Generator.php:185
/projects/magento2_code/vendor/magento/framework/Code/Generator.php:112
/projects/magento2_code/vendor/magento/framework/Code/Generator/Autoloader.php:35
/projects/magento2_code/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/projects/magento2_code/vendor/magento/framework/Interception/PluginList/PluginList.php:146
/projects/magento2_code/vendor/magento/framework/Interception/PluginList/PluginList.php:317
/projects/magento2_code/vendor/magento/framework/Interception/PluginList/PluginList.php:266
/projects/magento2_code/generated/code/Magento/TestFramework/Store/StoreManager/Interceptor.php:74
/projects/magento2_code/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:58
/projects/magento2_code/vendor/magento/magento2-base/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:291
/projects/magento2_code/vendor/magento/magento2-base/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/projects/magento2_code/vendor/my package/Test/MyPackageTest.php:17`

Line 17 is:
$item = $this->_webApiCall($serviceInfo);
Please note that my code has nothing to do with customerAddress and customerAddressMapper.

**Comment by shreelathags** [comment]
Not seeing this issue anymore. No changes made to the code.

**Comment by zhartaunik** [comment]
Had same issue with other preconditions. It happened during setup:upgrade. And further during opening magento in browser. Cleaning generated folder and redeploy fixed that.
