### ISSUE TITLE
Old categories are not removed at CSV import

### ISSUE THREAD

**Issue by kamilmaliszewski** [magento/magento2#15273]
### Preconditions

1. Magento 2.2.3
2. PHP 7.1
3. MySQL ver 14.14 Distrib 5.7.21

### Steps to reproduce

1. Add one product with SKU "Test" and "categories" = "category A" (via CSV import or Admin Panel)
2. Prepare an update CSV with single product -> SKU "Test" and "categories" = "Category B"
3. Go to import module
4. Choose "Add/Update" option and select prepared CSV
5. Import it

### Expected result

1. Category A will be removed from "Test" product
2. Category B will be assigned to "Test" product
3. Finally "Test" product will have only one category -> "Category B"

### Actual result

1. Product "Test" is assigned to "Category A" and "Category B", so both instead new one
2. "Category A" is not removed from this product.

P.S I know that for "Replace" old categories will be removed, but I don't want to do "Replace", becuase the ID will be replaced by new one. I want to have the same ID for updated product.

P.S 2: The same issue is for Images added via CSV import

**Comment by orlangur** [comment]
> Choose "Add/Update" option and select prepared CSV

Well, add/update should definitely not remove previously assigned categories.

**Comment by kamilmaliszewski** [comment]
@orlangur "Add/Update" means:
- Add product when SKU not exist
- Update product when SKU exist
So "Add/Update" is just info that new product will be created if SKU doesn't exist, it is not behavior for categories or images (the same case)... If SKU exist I have "Update" action, not "Add"

If you thnik that:
> add/update should definitely not remove previously assigned categories.

Pleaes tell me how can I remove old category from product via CSV import. "Replace" will change the ID of products, so it is not solution. 

Edit -> https://magento.stackexchange.com/questions/129974/functionality-of-add-update-replace-delete-clarity-needed Here the 1-st answer show the behavior of import for people who don't have knowledge about it. Generally: 
- "Update" action should be fixed about above issue or "Replace" should be changed to not removed a products

**Comment by ghost** [comment]
@kamilmaliszewski, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ankit-sf** [comment]
Any update on this issue?

**Comment by iRabi** [comment]
Yes, finding same issue in 2.2.5.

**Comment by duckchip** [comment]
what's the status of this issue?

**Comment by VincentMarmiesse** [comment]
Hi,
Any news on this issue?
Still happening in 2.3.1.

**Comment by DeanJMorgan** [comment]
> Hi,
> Any news on this issue?
> Still happening in 2.3.1.

I'd also like an update as this is something that I could do with being fixed.

**Comment by VincentMarmiesse** [comment]
FYI, PR #18898 fixed the issue for me

**Comment by navneetkumar-pim-webkul** [comment]
the same issue occurred in the REST API.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-15273-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-15273-2-3-develop.instances.magento-community.engineering/admin](https://i-15273-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce this issue on magento vanilla instance. issue exist in 2.3-develop branch

**Comment by bigbadbaz** [comment]
> ### Preconditions
> 1. Magento 2.2.3
> 2. PHP 7.1
> 3. MySQL ver 14.14 Distrib 5.7.21
> 
> ### Steps to reproduce
> 1. Add one product with SKU "Test" and "categories" = "category A" (via CSV import or Admin Panel)
> 2. Prepare an update CSV with single product -> SKU "Test" and "categories" = "Category B"
> 3. Go to import module
> 4. Choose "Add/Update" option and select prepared CSV
> 5. Import it
> 
> ### Expected result
> 1. Category A will be removed from "Test" product
> 2. Category B will be assigned to "Test" product
> 3. Finally "Test" product will have only one category -> "Category B"
> 
> ### Actual result
> 1. Product "Test" is assigned to "Category A" and "Category B", so both instead new one
> 2. "Category A" is not removed from this product.
> 
> P.S I know that for "Replace" old categories will be removed, but I don't want to do "Replace", becuase the ID will be replaced by new one. I want to have the same ID for updated product.
> 
> P.S 2: The same issue is for Images added via CSV import

Did you find a way of removing old categories during CSV import? I'm trying to do it with configurable products that have a lot of configurable options and a lot of categories, so I really don't want to remove old categories at the expense of losing the configurations, eg by creating a new product. Your help much appreciated.

**Comment by danielleharvey** [comment]
@bigbadbaz  did you figure it out? I cannot seem to find a way to do it.

**Comment by bigbadbaz** [comment]
> @bigbadbaz did you figure it out? I cannot seem to find a way to do it.

Only by getting this extension. You can create category groups and assign and remove categories at the same time.

https://magefan.com/magento-2-dynamic-categories

**Comment by pearcemichal** [comment]
the way I would expect it to work would be by putting __EMPTY__VALUE__ in the category column to remove the previously assigned data. 

however, when I tried this it just created a new category called __EMPTY__VALUE__ and assigned it to the product

Am I correct in thinking this is the intended behavior?
