### ISSUE TITLE
How to add the multiple option_value for single option_id like

### ISSUE THREAD

**Issue by vtulse** [magento/magento2#15281]
I'm, using this for adding  the item into magneto cart form REST API
How to add the multiple option_value for single option_id like
{
 	"option_id" : "44",
 	"option_value" :"41, 42, 43"
 }

Here is whole json for add to cart
{
 "cartItem": {
 "sku": "PLBMUS",
 "qty": "1",
 "quote_id": "b99ee719aa5eab2e51370faa1550710f",
 "product_option": {
 "extension_attributes": {
 "custom_options": [
 {
 "option_id": "5",
 "option_value": "Test 5 engrave"
 },
 {
 "option_id": "4",
 "option_value": "Test 5 engrave1"
 },
 {
 "option_id": "3",
 "option_value": "Test 5 engrave2"
 },
 {
 "option_id": "2",
 "option_value": "Test 5 engrave3"
 },
 {
 "option_id": "1",
 "option_value": "1"
 },
	{
 	"option_id" : "44",
 	"option_value" :"41"

 }

 ]
 }
 }
 }
}

**Comment by magento-engcom-team** [comment]
@vtulse please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
