### ISSUE TITLE
Remind Email Template from admin sending incorrect store link

### ISSUE THREAD

**Issue by jcolas15** [magento/magento2#15286]
We are experiencing an issue with using the 'Reset Password' Button when viewing a customer in the admin panel with a Magento installation with multiple stores. The correct store is not being set when generating the link (customer/account/createPassword) to be sent to the customer in an email.  Specifically in `vendor/magento/module-customer/Model/EmailNotification.php:298`, the defaultStoreId is never set as the 2nd parameter, so on `vendor/magento/module-customer/Model/EmailNotification.php:285`, the defaultstoreId is always set to the first store ID in the list via the `reset` function in php.  So if the `$storeIds` are fetched in this order  "2,4,1,3", storeID 2 will be used as the store url.  But the storeID which the customer exists in should be used.

### Preconditions
1. Magento 2.2.3 EE
2. Have a Magento installation with multiple stores 

### Steps to reproduce
1. Create multiple stores ( 4 for example) with all separate domains
2. Create a customer in store 3
3. In the admin panel, open up the customer information in Admin -> Customers
4. Click the 'Reset Password' Button

### Expected result

1. The Link the customer receives in the email for 'Set a New Password' should link to the url of the store the customer is registered in.  (in our example it should be www.store3.test/customer/account/createPassword/?id=308783&token=41dccbfdb9fa544cb43d7762c27f076a

### Actual result

1. Depending on the ordering Magento fetches the store collection in `vendor/magento/module-store/Model/Website.php:415`, the default storeID being set to generate the url is the first item in the list of storeIds fetched `(vendor/magento/module-customer/Model/EmailNotification.php:285)`.  So the link could be www.store2.test/customer/account/createPassword/?id=308783&token=41dccbfdb9fa544cb43d7762c27f076a depending on the ordering in the list of storeIds
![screen shot 2018-05-17 at 12 46 27 pm](https://user-images.githubusercontent.com/11393085/40194549-6aaa8754-59d0-11e8-9cc9-ce9a4a841f55.png)

**Comment by phoenix128** [comment]
Hello @jcolas15 ,
you should open this to EE support since you have an EE version.

Community version `2.2.6` is not affected by this bug. I suggest you both to update your Magento version and to ask at EE support.
