### ISSUE TITLE
Integration test fails with base 2.2.4 

### ISSUE THREAD

**Issue by tschirmer** [magento/magento2#15295]
### Preconditions
1. Magento 2.2.4
2. PHP 7.0.30
3. PHPUnit 6.2.4
4. MySQL 5.6.10
5. Ubuntu 17.10.1

### Steps to reproduce
1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition /magento2
2. Go into the integration directory 

`ec2-user@ip-10-6-0-4:/$ cd /magento2/dev/tests/integration`

3. Create tmp database in mysql
4. Create etc/install-config-mysql.php

```
<?php

return [
    'db-host' => '{{db-host}}',
    'db-user' => '{{db-user}}',
    'db-password' => '{{db-password}}',
    'db-name' => '{{db-temp-schema}}',
    'db-prefix' => '',
    'backend-frontname' => 'backend',
    'admin-user' => \Magento\TestFramework\Bootstrap::ADMIN_NAME,
    'admin-password' => \Magento\TestFramework\Bootstrap::ADMIN_PASSWORD,
    'admin-email' => \Magento\TestFramework\Bootstrap::ADMIN_EMAIL,
    'admin-firstname' => \Magento\TestFramework\Bootstrap::ADMIN_FIRSTNAME,
    'admin-lastname' => \Magento\TestFramework\Bootstrap::ADMIN_LASTNAME,
];

```

5. Run: `ec2-user@ip-10-6-0-4:/magento2/dev/tests/integration$ ../../../vendor/bin/phpunit -c phpunit.xml testsuite/Magento/Catalog/Block/Adminhtml/Product/Edit/JsTest.php `   

### Expected result
Test should pass

### Actual result

```

PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 1.38 minutes, Memory: 44.00MB

There was 1 failure:

1) Magento\Catalog\Block\Adminhtml\Product\Edit\JsTest::testGetAllRatesByProductClassJson
Invalid quantity of rates for tax classes.
Failed asserting that actual size 10 matches expected size 4.

/magento2/dev/tests/integration/testsuite/Magento/Catalog/Block/Adminhtml/Product/Edit/JsTest.php:43

FAILURES!
Tests: 1, Assertions: 2, Failures: 1.

=== Memory Usage System Stats ===
Memory usage (OS):      133.20M (302.72% of 44.00M reported by PHP)
Estimated memory leak:  89.20M (66.97% of used memory)

```

**Comment by orlangur** [comment]
> Invalid quantity of rates for tax classes.
> Failed asserting that actual size 10 matches expected size 4.

Are those added by some bundled extensions?

**Comment by tschirmer** [comment]
We're Magento developers of 7years, so have 4 custom extensions but they don't interact with the core tax classes. They are independent database tables and grids for some custom data storage.

**Comment by ghost** [comment]
@tschirmer,  thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please try to reproduce this issue on a clean installation. If you'd like to update it, please reopen the issue.
