### ISSUE TITLE
Area code is not set while setup:upgrade

### ISSUE THREAD

**Issue by RanzigeMilch** [magento/magento2#1529]
Hi all,

i tried to "update" to 1.0.0 beta today.
After an uninstall i tried to upgrade magento via cli (bin/magento setup:upgrade)
The update stops at "Magento_CatalogSearch" with the exception:

[Magento\Framework\Exception\SessionException]
  Area code not set: Area code must be set before starting a session.

  [Magento\Framework\Exception\LocalizedException]
  Area code is not set

setup:upgrade [--magento-init-params="..."]
![upgrade_area](https://cloud.githubusercontent.com/assets/2386998/8805542/17931fd4-2fd2-11e5-9f30-d5adf506e226.png)

what can i do?

**Comment by xcomSteveJohnson** [comment]
The changes in Merchant Beta require you to uninstall and reinstall: http://devdocs.magento.com/guides/v1.0/release-notes/changes_1.0.0-beta.html#1.0.0-beta-changes-schema

**Comment by RanzigeMilch** [comment]
Yes and i get the exception at point 3 "Upgrade the Magento 2 codebase and database."

**Comment by xcomSteveJohnson** [comment]
Did you do step 8 there?

rm -rf var/generation/* var/cache/*

**Comment by RanzigeMilch** [comment]
Well the exception occurs at step 7.. but yes i tried that.. doesnt help

**Comment by RanzigeMilch** [comment]
I started again from the beginning (uninstall...) and i got a fatal error at the module "Magento_Indexer" first.
![setup_indexer](https://cloud.githubusercontent.com/assets/2386998/8821837/f1113f8c-3060-11e5-8251-be6c2ed9c120.png)

When i start the upgrade progress again the indexer installtion is working, but i run into the same problem (Exception at CatalogSearch) again..

**Comment by xcomSteveJohnson** [comment]
Our apologies for how difficult this has become. Yesterday I fixed the upgrade instrux here: http://devdocs.magento.com/guides/v2.0/release-notes/changes_1.0.0-beta.html#1.0.0-beta-changes-schema

The change is to step 3. Basically, you start with uninstall but no do NOT run setup:upgrade. Instead, update the code, composer update, install again.

**Comment by alexhlynskyy** [comment]
fuck you

**Comment by rumbdev** [comment]
[AREA-CODE-NOT-SET-EXCEPTION.tar.gz](https://github.com/magento/magento2/files/891463/AREA-CODE-NOT-SET-EXCEPTION.tar.gz)
I've got the same issue trying to upgrade from 2.1.2 to 2.1.4 (wit sample data).
tried the solution detailed here: http://stackoverflow.com/questions/35129901/magento-2-area-code-not-set-after-adding-sample-data
with no avail.
working on it since a few hours but so far I'm quite stuck....

thanks,
romeo

attached the exception trace

**Comment by rumbdev** [comment]
updating it because it turned out to be related to a third-party module.

thanks a lot to circlesix for pointing out the simplest solution here: http://magento.stackexchange.com/questions/132940/area-code-not-set

cheers!
