### ISSUE TITLE
upgraded from 2.2.3 to 2.2.4 and Sendgrid no longer sending tranactional emails

### ISSUE THREAD

**Issue by Rich07082** [magento/magento2#15306]
### Preconditions

1. magento 2.2.4
2. php 7.1
3.debian
Sendgrid(version 1.0.3)

### Steps to reproduce
Transactional emails were being sent when test orders were placed under 2.2.3 but after upgrading to 2.2.4 no longer being sent.

I can send email through the Sendgrid(version 1.0.3) admin extension and you can email from a product page(email friend).

Received the following error.

{"errors":[{"message":"Invalid type. Expected: object, given: array.","field":"from","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.from"}]

Rich

**Comment by rishabhchd19** [comment]
This is the problem with the extension I believe. The same problem I am getting when EADESGN Invoice Generator Extension is ENABLED. On Disabling the extension, Transactional Mails starts functioning well.

**Comment by gwharton** [comment]
Be aware there is a potential new bug in 2.2.4 where the from address in transactional emails is not getting set for some people. #14952 Could be related.

**Comment by magento-engcom-team** [comment]
Hi @Rich07082 
Unfortunately this github issue tracker is only intended for Magento 2 core technical issues. We can not track tickets related to third-party extensions. Please contact extension vendor regarding this issue.

Thanks
