### ISSUE TITLE
Rest API - Customer access to Orders

### ISSUE THREAD

**Issue by johngrogg** [magento/magento2#1530]
Are there any plans to add access to Orders when authenticated by a customer? Perhaps on something like `GET /V1/orders/mine`, similar to `GET /V1/carts/mine`?

That seems to be one of the few remaining missing end-points for the purposes of a full shopping experience (you can already manage account info through `GET /V1/customers/me`, but you can't access order data currently).

**Comment by choukalos** [comment]
Added to internal ticket MAGETWO-40080

**Comment by choukalos** [comment]
re-assigning to Mark.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rest-API-Customer-access-to-Orders/idi-p/46552).
