### ISSUE TITLE
Shopping cart price rule not working correctly

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#15307]
### Preconditions

1. I'm using magento 2.2.1
2. In our store 5 website setup and more then 80K products

### Steps to reproduce

1. I have created cart rule for free shipping, in my cart rule I have added multiple condition for different brands
2. check this screen-shot fore more information about multiple condition
Screenshot : https://prnt.sc/jjhw1s

![vpmrhf3zqvavz_nerypkhg](https://user-images.githubusercontent.com/6543606/40233900-5dbea258-5ac2-11e8-821e-e261d07bbe39.png)

3. Its working fine with single brand but not working with multiple.

### Expected result

1. Rule should work for all brands and its products

### Actual result

1. Rule is working for only one brand product and not working all brand which was added in rule condition.

**Comment by popatkaran** [comment]
@aasim110  Please provide information like how you want to setup the rule. For me cart rules are working well.
If your rule is like

- If an item is FOUND  in the cart with ANY  of these conditions true: 
    Brand is X
    Brand is not A
    Brand is not B
    Brand is not C

customer will get free shipping if in cart items of any brand. You need to change conditions to ALL if you want to provide free shipping for Brand X only.
 #dmcdindia

**Comment by aasim110** [comment]
@popatkaran my rule is like following

Subtotal equals or greater then 150
If an item is FOUND in the cart with ANY of these conditions true:
Brand is not X
Brand is not A
Brand is not B
Brand is not C

it is working fine if I use single brand,  but not working for multiple brand. 
Any Idea ?

**Comment by popatkaran** [comment]
@aasim110 

Could you please share that with these conditions which brand product is there in cart? And what should be the result according to you?

**Comment by aasim110** [comment]
@popatkaran 
Suppose X brand's product in my cart and its price is 200 so as per my rule Free Shipping can't apply on this product. but some how it was applied. 
And if I remove other brands from the rule it is working fine and I can see 10$ shipping price in my cart.
get it ?

**Comment by popatkaran** [comment]
@aasim110 
Here your condition is "If an item is FOUND in the cart with ANY of these conditions true:" which means OR conditions with that rules. Please try with ALL instead of ANY.

**Comment by aasim110** [comment]
@popatkaran Yes All option work for me.
Thanks for the help (y)

**Comment by popatkaran** [comment]
@aasim110  Thank you for closing ticket.
