### ISSUE TITLE
Rest API - Add Categories to GET /V1/products/:sku

### ISSUE THREAD

**Issue by johngrogg** [magento/magento2#1531]
It would be super useful to have the Categories assigned to a product be added to the returned data (similar to how `extension_attributes` are available). Even better if you could filter based on them as well via `searchCriteria`.

**Comment by BingQiangChen** [comment]
good!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rest-API-Add-Categories-to-GET-V1-products-sku/idi-p/45435).
