### ISSUE TITLE
a:4:{i:0;s:50:"Attribute with attributeCode "131" does not exist.";i:1;s:8901:"#0 F:\magento2\app\code\Magento\Catalog\Model\Product\Attribute\Repository.php(87): Magento\Eav\Model\AttributeRepository->get('catalog_product', '131')

### ISSUE THREAD

**Issue by zhaoxiong123** [magento/magento2#1532]
i added a product attribute,then,i go to product list,the error found!

**Comment by kandy** [comment]
@zhaoxiong123, which version do you use? We can't reproduce this issue internally. Could you provide more details? Ideally, step-by-step instruction.

**Comment by zhaoxiong123** [comment]
the problem is solved . thanks . i download the lastest version.

**Comment by zhaoxiong123** [comment]
@kandy  the problem is solved . thanks . i download the lastest version.
