### ISSUE TITLE
Invoice created via API not registered as Invoice in Magento

### ISSUE THREAD

**Issue by arijit-de93** [magento/magento2#15328]
### Preconditions

1. Magento 2.2.4
2. Magento 2.4-develop
2. PHP 7.4
3. MySQL 8
4. Ubuntu

### Steps to reproduce

1. Create a payload like the following:- 
    {
"entity": {
"orderId": 2,
"storeId": 1,
"billingAddressId": 1,
"shippingAddressId": 1,
"totalQty": "1",
"items": [
{
"orderItemId": 2,
"productId": 1,
"sku": "Nokia 1508",
"name": "Nokia 1508",
"qty": "1",
"price": "1599.00",
"row_total": "1599.00"
}
]
}
}
2. Endpoint :- http://dev-arijit.magento.com/contribution-day/arijit/magento2/rest/all/V1/invoices/
3. HTTP method - POST

### Expected result

1. An invoice should be created and must be registered against the order and also the order status should move to processing.

### Actual result

1. API shows Invoice created, but when checking in admin, it shows the Invoice, but the order status is not changed and also Order still giving the option to create an invoice.
![reponse](https://user-images.githubusercontent.com/16597334/40248742-8495fa1c-5aee-11e8-918d-5e3763b96382.PNG)

![admin](https://user-images.githubusercontent.com/16597334/40248721-753e2aee-5aee-11e8-8d99-e5833ac6aacf.PNG)

**Comment by engcom-backlog-nickolas** [comment]
Hello @arijit-de, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jignesh26** [comment]
Hello @arijit-de ,
 I have checked and found that issue is reproduced into magneto 2.3. 
However you can use the below way to create the invoice. It will return the invoice ID and you can load the invoice by that id as well. 

Please check this code for reference. 

$requestUrl =$magentoURL.'index.php/rest/all/V1/invoices/';
 
 $invoiceData = [
 'capture' => true,
 'notify' => true
 ];

**Comment by zsebacher-integritystl** [comment]
Has this ever been fixed? This issue is over a year old and creating an invoice from the api should work out of the box. The lack of responsiveness from the magento team is just absolutely mind blowing.

**Comment by sdzhepa** [comment]
Should be re-verified and confirmed on the latest `2.4-develop`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40828` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment]
Hi, @arijit-de93 Currently "/V1/invoices/"-endpoint use only to create the entity. 
May be, achieve the goal you described, it is better to use another endpoint - "/V1/order/{orderId}/invoice".

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
