### ISSUE TITLE
Wrong Home CMS Page?

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#1536]
luma / Magento ver. 0.74.0-beta16 + official Sample Data (cache disabled).

I've created second CMS page with identifier = "home" and title = "Home 2"
http://awesomescreenshot.com/0cf53689f8
I didn't change my default CMS Home Page - but I see content of "Home 2" CMS page by default.
when I open it by URLs as:
{base_url} 
{base_url}/home

http://prntscr.com/7vn8s5
http://prntscr.com/7vn7uo

P.S. I can't create more pages with identifier 'home' - I see "URL key for specified store already exists" warning. But I can delete the "Home 2" page and recreate it without error.
Sorry for my English.

**Comment by mazhalai** [comment]
@sergei-sss Thank you for reporting this issue. We have created ticket MAGETWO-40683 to investigate.

**Comment by piotrekkaminski** [comment]
This should be fixed now.
