### ISSUE TITLE
Admin page menu has no edit icons/actions

### ISSUE THREAD

**Issue by RanzigeMilch** [magento/magento2#1538]
in the page view (admin panel) i dont have any edit icons. When i click on a page row i get the following error:
	
actions.js (Zeile 151, Spalte 16)
TypeError: action is undefined

if (!action.href && !action.callback) {...

Whats wrong?

**Comment by mazhalai** [comment]
@RanzigeMilch Thank you for reporting this issue, can you please provide more details so that we can reproduce this?

**Comment by RanzigeMilch** [comment]
what kind of information? im on developer branch. (1.0.0 beta)
I get the same problem in the block view (adminhtml).
I can create a block, but after that the action column is empty and the row is not clickable because of the error in the actions.js

**Comment by vpelipenko** [comment]
Could you provide screen copy where we can see JS errors?

**Comment by piotrekkaminski** [comment]
@RanzigeMilch any update on this one?
