### ISSUE TITLE
Magento2 admin menu panel doesn't work

### ISSUE THREAD

**Issue by robjus** [magento/magento2#15389]
SALES
CATALOG
CUSTOMERS
MARKETING
CONTENT
REPORTS
STORES
 None of these links work! Im on Windows 10 64bit xampp

**Comment by bap14** [comment]
This isn't the place to get support, it's for reporting bugs.  If you'd like support, I can recommend magento.stackexchange.com

This sounds like you don't have the static elements compiled / deployed yet, or your store isn't in development mode so the files aren't being generated.  I'm willing to bet if you open the developer console in the browser you'll see a bunch of errors related to not being able to download javascript files.

Turn developer mode on: `bin/magento deploy:mode:set developer`, or do a static-content deployment: `bin/magento setup:static-content:deploy`

For information about deployment modes, see: https://devdocs.magento.com/guides/v2.2/config-guide/bootstrap/magento-modes.html

**Comment by magento-engcom-team** [comment]
Hi @smartwebme 
Closing this ticket now per comment above.
