### ISSUE TITLE
Export to CSV/XML not working in Custom Grid using Listing UI Component

### ISSUE THREAD

**Issue by jayankaghosh** [magento/magento2#15384]
Export to CSV/XML not working in Custom Grid using Listing UI Component

### Preconditions
1. PHP 7.1 with MySQL 5.7
2. Apache 2.0 Server setup on localhost

### Steps to reproduce
1.  Install Magento 2.2.2 with Sample Data
2. Create a custom module and one Adminhtml Grid inside it using UI Components
3. Use a custom data provider class which extends `\Magento\Ui\DataProvider\AbstractDataProvider`
4. Try to Export the grid to either CSV or XML

### Expected result
1. A CSV/XML file should get downloaded

### Actual result
1. Error shows up saying `call to a member function setCurrentPage on null`

### P.S
Upon further investigation I've discovered that it's because the `getCsvFile` method of the `Magento\Ui\Model\Export\ConvertToCsv` class calls `$dataProvider->getSearchCriteria()->setCurrentPage($i)` on line 75. And the `getSearchCriteria` method of the `AbstractDataProvider` class currently has a comment saying "//TODO: Technical dept, should be implemented as part of SearchAPI support for Catalog Grids" and returns null

**Comment by jayankaghosh** [comment]
Any updates on this?

**Comment by ghost** [comment]
Hi @jayankaghosh i cannot reproduce by you scenario see attachments
![frame-02d](https://user-images.githubusercontent.com/40756439/43254534-421e1418-90d0-11e8-9923-0f648c42c413.gif)

**Comment by hugodeaguiar** [comment]
@jayankaghosh Hello,

Did you solve the problem? I have the same scenario here.
Thank you.

**Comment by jayankaghosh** [comment]
@hugodeaguiar No, I ended up creating a custom logic to convert my grid to CSV/XML

**Comment by amici-infotech** [comment]
We have exact same issue , does anyone has solution ?

**Comment by vajyothi** [comment]
@amici-infotech You can simply extend your custom data provider with Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider, which is using the Search API. The following APIs are available in Ui DataProvider

Magento\Framework\Api\FilterBuilder
Magento\Framework\Api\Search\ReportingInterface
Magento\Framework\Api\Search\SearchCriteria
Magento\Framework\Api\Search\SearchCriteriaBuilder
Magento\Framework\Api\Search\SearchResultInterface
