### ISSUE TITLE
Sample Data Installation Issue

### ISSUE THREAD

**Issue by TRMMarketing** [magento/magento2#1539]
Attempted to install sample data on an clear magento 2 1.0 beta following: http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data.html#instgde-prereq-sample-intro

When I run bin/magento setup:upgrade I am encountering the following errors:

  [Zend_Db_Adapter_Exception]                       
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by mazhalai** [comment]
@TRMMarketing Thank you for reporting this issue. Can you please verify if the database connection is correct in `app\etc\env.php` and if your database is running fine.

**Comment by TRMMarketing** [comment]
It is correct. To test I setup an entirely new install as well and walk through the steps described again and received the exact same error. This was a brand new installation that was fully functional.

**Comment by xcomSteveJohnson** [comment]
If Magento was installed first, did you use these steps: http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data.html#instgde-install-sample-enable-after

The only other obvious thing is that I updated that page yesterday to update this command:

composer require magento/sample-data:~1.0.0-beta

Before, it was using an older 0.74-beta15 version.

**Comment by TRMMarketing** [comment]
Followed the sample data after installation data. 

It appears this error is occurring whenever the bin/magento setup:upgrade is run as I just ran this to test a sample module as well and the same issue arose.

**Comment by okiii** [comment]
I can confirm, I've had the exact same issues.

**Comment by buskamuza** [comment]
Similar to https://github.com/magento/magento2/issues/1569
Hi @TRMMarketing , please, take a look at https://github.com/magento/magento2/issues/1569#issuecomment-125243090 and let us know if it helps.

**Comment by TRMMarketing** [comment]
@buskamuza Thanks that link provided a solution.
