### ISSUE TITLE
"Multiple Select" product attributes do not render HTML tags on the storefront view

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#15393]
Error on Product Page. More Information tab.

### Preconditions
1. Magento 2.2.4

### Steps to reproduce
I recently update from Magento 2.2.3 to Magento 2.2.4, and then found this error.
On product page, there is an error.

### Expected result
 Full product page without error. The links on "More Information" tab is clickable. And then after click browser will load and go to the page on link.

### Actual result
The links are broken. Not clickable, but to be a plain text. The screenshots is.
![error product more 1](https://user-images.githubusercontent.com/5201127/40279628-dc85b014-5c6f-11e8-830c-ee3a9043cc56.png)

[image]https://www.imageupload.co.uk/images/2018/05/18/Errorproductmore1.png[/image]

**Comment by jurpro** [comment]
Hello. Anyone help? It is more then 1 weeks nobody answer.

Thank you

**Comment by Karlasa** [comment]
@jurpro  Could you check your attribute settings under STORES -> Atrributes -> Product -> [your attribute] ->  Storefront Properties -> Allow HTML Tags on Storefront -> Should be set to "Yes"
Im sure it's not bug but just configuration issue :) 

Cheers,

**Comment by jurpro** [comment]
@Karlasa Thank you for reply.
But nothing happend. It works on Magento 2.2.3 but now on Magento 2.2.4 it mess. Just be a plain text not html tags.
here the screenshots for backend and frontend.

![music-error-1](https://user-images.githubusercontent.com/5201127/40720477-1524d246-6441-11e8-87b0-d3f59f99644e.png)
![music-error-2](https://user-images.githubusercontent.com/5201127/40720480-16f4180c-6441-11e8-902a-b628f8c836a6.png)

**Comment by magento-engcom-team** [comment]
More details on report: https://github.com/magento/magento2/issues/15612

**Comment by simonjanguapa** [comment]
#mm18nl

**Comment by simonjanguapa** [comment]
@jurpro it's a corebug. Fixed it in this [request](https://github.com/magento/magento2/pull/15687).

**Comment by jurpro** [comment]
Thank you so much team. It works. 

Hope, next update this fix will be include. 

thank you.

**Comment by kedarjoyner** [comment]
@jurpro If possible, I would recommend changing the title of this issue with keywords more specific to the problem. I was experiencing the same issue, but this did not display in the search results when looking for similar issues. Regardless, thank you for reporting this problem too!

**Comment by ghost** [comment]
@kedarjoyner done.

**Comment by magento-engcom-team** [comment]
Hi @jurpro. Thank you for your report. 
The issue has been fixed in magento/magento2#15687 by @simonjanguapa in 2.2-develop branch
Related commit(s):
 - [a49618ada2a310601cdf1568bca28170d70bcfc5](https://github.com/magento/magento2/commit/a49618ada2a310601cdf1568bca28170d70bcfc5)
 - [28159a37d1b63e69a72e7cd21022bde533721cc6](https://github.com/magento/magento2/commit/28159a37d1b63e69a72e7cd21022bde533721cc6)
 - [edb35169ddf49d5b7cb7f0798021a4c945c537fd](https://github.com/magento/magento2/commit/edb35169ddf49d5b7cb7f0798021a4c945c537fd)

The fix will be available with the upcoming 2.2.6 release.
