### ISSUE TITLE
Customer edit  section in admin showing error

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#15408]
### Preconditions

1. magento 2.1.8
2. php 7.0.26

### Steps to reproduce

1. Tried to migrate data from magento  1.9.2.3 to magento 2.1.8 with ubertheme datamigration. 
2. When going to customer edit section getting error "The requested component ("label") is not found. Before using, you must add the implementation.";

### Expected result

1. 

### Actual result

1. [1627835954.txt](https://github.com/magento/magento2/files/2022525/1627835954.txt)
2.
![error_report](https://user-images.githubusercontent.com/24405051/40308057-defcb9f4-5cfc-11e8-9eb4-9083c598be0b.png)

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

Problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository but it looks like you are using another tool.

**Comment by BabliDey** [comment]
Hello orlangur, I also use that data magratopn tool but migration does not migrated any data after running migration command.
