### ISSUE TITLE
Magento 2.1 : Not calling custom block on checkout page for filling credit card details into input fields of IFrame using functional testing framework (FTF).

### ISSUE THREAD

**Issue by akpra88** [magento/magento2#15405]

**Comment by magento-engcom-team** [comment]
Hi @akpra88 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result and then reopen the ticket. We are closing it for now.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

You may update description and reopen ticket. Thanks.
