### ISSUE TITLE
Custom Payment Plugin Causing Fatal Error on order Save

### ISSUE THREAD

**Issue by techwithrajat** [magento/magento2#15406]
### Preconditions

1.  Magento Version 2.2.4
2.  PHP Version 7.1

### Steps to reproduce

We have developed a custom payment plugin for accepting payment. Everything is working fine but when we are changing the order state and saving it it is causing the below error. Apart from this everything is working fine in the functionality :

**Error**

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Paypal\Model\Adminhtml\Express\Interceptor::isOrderAuthorizationAllowed() must be an instance of Magento\Sales\Model\Order\Payment, null given, called in /var/www/****/public_html/vendor/magento/module-paypal/Plugin/OrderCanInvoice.php on line 41 and defined in /var/www/****/public_html/generated/code/Magento/Paypal/Model/Adminhtml/Express/Interceptor.php:33 Stack trace: #0 /var/www/****/public_html/vendor/magento/module-paypal/Plugin/OrderCanInvoice.php(41): Magento\Paypal\Model\Adminhtml\Express\Interceptor->isOrderAuthorizationAllowed(NULL) #1 /var/www/****/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Paypal\Plugin\OrderCanInvoice->afterCanInvoice(Object(Magento\Sales\Model\Order\Interceptor), false) #2 /var/www/****/public_html/vendor/magento/framework/Interception/Interceptor.php(153) in /var/www/****/public_html/generated/code/Magento/Paypal/Model/Adminhtml/Express/Interceptor.php on line 33

**Snippet of Function Call** 

http://prntscr.com/jkmcr4

**Comment by lchemwolo** [comment]
Hello, did you find a solution for this? I am experiencing the same issue.

**Comment by techwithrajat** [comment]
Not till now ... we are still struggling with this issue... Did not get a solution... Kindly let us know if you find any solutions for this.

**Comment by kervin** [comment]
Any luck with this? Same issue here, i've updated from 2.1.8 to 2.2.4

**Comment by lchemwolo** [comment]
After I modified some lines of code the error disappeared. Looking back, it appears that when the $order->save() stage is attempting an order object that is not yet properly instantiated, that error occurs (saving an order object that does not exist). I think in my case I changed the line

$orderId = $this->orderRepository->get($this->checkoutSession->getLastOrderId()); (which I was using yet I had not injected \Magento\Sales\Model\OrderRepository)

to 

$orderId = $this->checkoutSession->getLastOrderId();

 I was wondering why it would throw errors in Paypal classes yet i was not doing anything related to PayPal.

**Comment by kervin** [comment]
I've changed the following line instead and it seems to work.

Magento\Paypal\Model\Adminhtml\Express.php
From:
`    public function isOrderAuthorizationAllowed(Payment $payment): bool
`
to

    public function isOrderAuthorizationAllowed(Payment $payment)

**Comment by techwithrajat** [comment]
@kervin we are getting this error when we changed it according to your specification. Also, there is no such file in our version which you mentioned. we changed in file which we have and got below error.

PHP Fatal error:  Declaration of Magento\\Paypal\\Model\\Adminhtml\\Express\\Interceptor::isOrderAuthorizationAllowed(Magento\\Sales\\Model\\Order\\Payment $payment) must be compatible with Magento\\Paypal\\Model\\Adminhtml\\Express::isOrderAuthorizationAllowed(Magento\\Sales\\Model\\Order\\Payment $payment): bool in /var/www//public_html/generated/code/Magento/Paypal/Model/Adminhtml/Express/Interceptor.php on line 7

**Comment by kervin** [comment]
On which version are you?

Just change method isOrderAuthorizationAllowed in Magento\Paypal\Model\Adminhtml\Express

Remove the ":bool" part. Be extra careful if you use Paypal Express. I am not using it and I have not tested. This is just to allow the checkout.

**Comment by techwithrajat** [comment]
@kervin version is 2.2.4 community edition ("magento/product-community-edition": "2.2.4")

we are also not using Paypal Express.

**Comment by kervin** [comment]
Did you try this fix? By removing the ":bool" part?

**Comment by techwithrajat** [comment]
Yes , it gave below error... 

PHP Fatal error: Declaration of Magento\Paypal\Model\Adminhtml\Express\Interceptor::isOrderAuthorizationAllowed(Magento\Sales\Model\Order\Payment $payment) must be compatible with Magento\Paypal\Model\Adminhtml\Express::isOrderAuthorizationAllowed(Magento\Sales\Model\Order\Payment $payment): bool in /var/www//public_html/generated/code/Magento/Paypal/Model/Adminhtml/Express/Interceptor.php on line 7

**Comment by kervin** [comment]
You must modify this one

Magento\Paypal\Model\Adminhtml\Express::isOrderAuthorizationAllowed

and remove the ":bool"

**Comment by ghost** [comment]
@enrajatjain, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
