### ISSUE TITLE
Magento 2 reorder not working (error on line 153 at column 39: Entity 'nbsp' not defined)

### ISSUE THREAD

**Issue by VladSuciu76** [magento/magento2#15401]
Hello,

In Magento 2.2.1, when I press the "Reorder" button in admin panel, it gives the error: 
This page contains the following errors:
error on line 153 at column 39: Entity 'nbsp' not defined
Below is a rendering of the page up to the first error.
<img width="1264" alt="screen shot 2018-05-21 at 11 32 35 am" src="https://user-images.githubusercontent.com/12977160/40298193-f4fe27f4-5cea-11e8-9fab-3251f4c43e8b.png">

Do we have a known solution for this issue?
Thank you

**Comment by magento-engcom-team** [comment]
Hi @VladSuciu76 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result and then reopen the ticket. We are closing it for now.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result
