### ISSUE TITLE
Dupilcate address in checkout

### ISSUE THREAD

**Issue by tristanisginger** [magento/magento2#15403]
### Preconditions

Magento 2.2.14, php 7.1
Vanilla fresh install with sample data

### Steps to reproduce
1. Place an Order as a guest.
2. On "Thank you for your purchase!" create an Account.
3. As User, created in step 3, add any Product to Cart and proceed to Checkout.

### Expected result
1. only one address should be available for shipping

### Actual result

1. the same address is repeated

**Comment by tristanisginger** [comment]
similar to this:
https://github.com/magento/magento2/issues/8350

**Comment by ghost** [comment]
@tristanisginger, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @tristanisginger 
This issue does not seem to be reproducible anymore with 2.2.5. Please reopen if it's incorrect.

Thank you

**Comment by davinanaya** [comment]
This still happening with 2.2.6

**Comment by sanganb** [comment]
Duplicate address in Checkout shipping address:

Reproduce:

1. GO to checkout as logged in user
2. Its shows already saved shipping address (OR add shipping address in customer my account)
3. CLick Add new Address button 
4. Add address same as already exists in site
5. which is allowed to create new address

Expected Result:
When add new address same as existing which should set existing and select for shipping.

![image](https://user-images.githubusercontent.com/73931635/109202069-93193780-77c8-11eb-9f71-d6d28dcce622.png)
