### ISSUE TITLE
Export and Import products with multiple select attributes

### ISSUE THREAD

**Issue by jeffbritts** [magento/magento2#1540]
It doesn't appear that multiple select attributes are being exported with a product.

If I create an attribute as a Multiple Select (Color), then give it values (Red,Blue,Green), create a product and export, that attribute is not included in the additional_attributes column.

On Import, I would assume there would need to be some delimiter (other than comma) to separate the values (size=L,color=Red|Blue|Green)

**Comment by kandy** [comment]
Internal ticket: https://jira.corp.x.com/browse/MAGETWO-41484

**Comment by kokoc** [comment]
@jeffbritts thank you for reporting the issue. We will fix the problem and get back to you once we have the working code.

**Comment by piotrekkaminski** [comment]
It should be fixed now and available on github already or soon.
