### ISSUE TITLE
Magento\Sales resource could not access by customer token

### ISSUE THREAD

**Issue by gnanasekaranl** [magento/magento2#15415]
Return order details in REST API Magento-2.2 get below error when tried to access using customer token, But it is working with admin token in **salesOrderRepositoryV1**

vendor_name/module_name/model/EmcOrderRepository.php

 public function get($id)
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $order = $objectManager->create('Magento\Sales\Api\Data\OrderInterface')->load($id);
        $data = $order->getData();   
        return $data;
     }

And also I tried in many ways, But the result is same as Authorization error,

{
  "message": "No such entity with %fieldName = %fieldValue",
  "parameters": {
    "fieldName": "orderId",
    "fieldValue": "2"
  },
  "trace": "#0 /var/www/html/projectname/vendor/magento/module-sales/Model/ResourceModel/Order/Plugin/Authorization.php(45): Magento\\Framework\\Exception\\NoSuchEntityException::singleField('orderId', '2')\n#1 .............

**Comment by engcom-backlog-nickolas** [comment]
Hello, @gnanasekaranl, thank you for your report. I'm not quite sure I fully understand issue you've described. 
So, I did the next:
Created TestRepository with endpoint V1/my-orders/:id with resource - self, which use OrderInterface to get specified order data. And I can successfully get all order data using customer token.

![peek 2018-07-16 15-55](https://user-images.githubusercontent.com/40755810/42759700-8ea4ded8-8910-11e8-95c2-869b97ac979d.gif)

If you'd like to update this issue, please reopen it.
