### ISSUE TITLE
Customer name not displayed on some transactional emails

### ISSUE THREAD

**Issue by nadeefit6** [magento/magento2#15417]
Customer name is not displayed on transaction mails. 
It’s displayed as “%naam”.
Followings are the email templates which are incorrect for Guests.
1. New Order for Guest
2. New Invoice for Guest
3. New Credit Memo for Guest
4. New Shipment for Guest 
5. Forgot Password
6. New Account Confirmation Key
7. New Account Confirmed 

Following are the email templates which are incorrect for registered users.
Credit Memo and Invoice,Shipment

### Preconditions
1. Magento ver. 2.2.3
2. Sample data installed

### Steps to reproduce
1. Checkout as guest and complete an order
2. Check the order confirmation email
3. Can be reproduced in all other above mentioned email templates

### Expected result
1. Customer name should be displayed in the email as filled in the checkout.

### Actual result
1. Customer name is displayed as “%naam” in order conformation email

**Comment by nadeefit6** [comment]
This can be fixed by changing the template variable in all email templates with the above issue.
Can I continue with the issue?

**Comment by hitesh-wagento** [comment]
@nadeefit6 I have tested  above transnational emails in **Magento ver. 2.2.6-dev** and  **Magento ver. 2.2.4** it's working fine.

**Comment by nadeefit6** [comment]
may be its magento version 2.2.3 bug

**Comment by ghost** [comment]
Hi @nadeefit6  The fix for this issue is already available in the 2.2-develop branch.

**Comment by denvit** [comment]
> Hi @nadeefit6 The fix for this issue is already available in the 2.2-develop branch.

Can you link the issue at least?
