### ISSUE TITLE
catalog_product_option foreign key may be wrong?

### ISSUE THREAD

**Issue by indefinitedevil** [magento/magento2#15410]
If you wipe out the product tables without also wiping out sequence_product, SQL conflict errors are generated when you create a product with custom options.

The reason for this is that the catalog_product_option table uses catalog_product_entity.row_id as a foreign key reference, not catalog_product_entity.entity_id. If you've truncated catalog_product_entity, the row_id will start over from 1, but the entity_id starts at X where X is the current value of sequence_product.

If I'm correct in my thought process, the foreign key on catalog_product_option should be linked to catalog_product_entity.entity_id not row_id

### Preconditions

1. Magento EE 2.2.4
2. PHP 7.1, MariaDB 10

### Steps to reproduce

1. Wipe product tables (except sequence_product and associated)
2. Create product with custom option

Script used to wipe product tables:
> TRUNCATE TABLE `cataloginventory_stock_item`;
> TRUNCATE TABLE `cataloginventory_stock_status`;
> TRUNCATE TABLE `cataloginventory_stock_status_idx`;
> TRUNCATE TABLE `cataloginventory_stock_status_tmp`;
> TRUNCATE TABLE `catalog_category_product`;
> TRUNCATE TABLE `catalog_category_product_index`;
> TRUNCATE TABLE `catalog_category_product_index_tmp`;
> TRUNCATE TABLE `catalog_compare_item`;
> TRUNCATE TABLE `catalog_product_bundle_option`;
> TRUNCATE TABLE `catalog_product_bundle_option_value`;
> TRUNCATE TABLE `catalog_product_bundle_price_index`;
> TRUNCATE TABLE `catalog_product_bundle_selection`;
> TRUNCATE TABLE `catalog_product_bundle_selection_price`;
> TRUNCATE TABLE `catalog_product_bundle_stock_index`;
> TRUNCATE TABLE `catalog_product_entity`;
> TRUNCATE TABLE `catalog_product_entity_datetime`;
> TRUNCATE TABLE `catalog_product_entity_decimal`;
> TRUNCATE TABLE `catalog_product_entity_gallery`;
> TRUNCATE TABLE `catalog_product_entity_int`;
> TRUNCATE TABLE `catalog_product_entity_media_gallery`;
> TRUNCATE TABLE `catalog_product_entity_media_gallery_value`;
> TRUNCATE TABLE `catalog_product_entity_media_gallery_value_to_entity`;
> TRUNCATE TABLE `catalog_product_entity_media_gallery_value_video`;
> TRUNCATE TABLE `catalog_product_entity_text`;
> TRUNCATE TABLE `catalog_product_entity_tier_price`;
> TRUNCATE TABLE `catalog_product_entity_varchar`;
> TRUNCATE TABLE `catalog_product_index_eav`;
> TRUNCATE TABLE `catalog_product_index_eav_decimal`;
> TRUNCATE TABLE `catalog_product_index_eav_decimal_idx`;
> TRUNCATE TABLE `catalog_product_index_eav_decimal_tmp`;
> TRUNCATE TABLE `catalog_product_index_eav_idx`;
> TRUNCATE TABLE `catalog_product_index_eav_tmp`;
> TRUNCATE TABLE `catalog_product_index_price`;
> TRUNCATE TABLE `catalog_product_index_price_bundle_idx`;
> TRUNCATE TABLE `catalog_product_index_price_bundle_opt_idx`;
> TRUNCATE TABLE `catalog_product_index_price_bundle_opt_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_bundle_sel_idx`;
> TRUNCATE TABLE `catalog_product_index_price_bundle_sel_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_bundle_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_cfg_opt_agr_idx`;
> TRUNCATE TABLE `catalog_product_index_price_cfg_opt_agr_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_cfg_opt_idx`;
> TRUNCATE TABLE `catalog_product_index_price_cfg_opt_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_downlod_idx`;
> TRUNCATE TABLE `catalog_product_index_price_downlod_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_final_idx`;
> TRUNCATE TABLE `catalog_product_index_price_final_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_idx`;
> TRUNCATE TABLE `catalog_product_index_price_opt_agr_idx`;
> TRUNCATE TABLE `catalog_product_index_price_opt_agr_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_opt_idx`;
> TRUNCATE TABLE `catalog_product_index_price_opt_tmp`;
> TRUNCATE TABLE `catalog_product_index_price_tmp`;
> TRUNCATE TABLE `catalog_product_index_tier_price`;
> TRUNCATE TABLE `catalog_product_index_website`;
> TRUNCATE TABLE `catalog_product_link`;
> TRUNCATE TABLE `catalog_product_link_attribute_decimal`;
> TRUNCATE TABLE `catalog_product_link_attribute_int`;
> TRUNCATE TABLE `catalog_product_link_attribute_varchar`;
> TRUNCATE TABLE `catalog_product_option`;
> TRUNCATE TABLE `catalog_product_option_price`;
> TRUNCATE TABLE `catalog_product_option_title`;
> TRUNCATE TABLE `catalog_product_option_type_price`;
> TRUNCATE TABLE `catalog_product_option_type_title`;
> TRUNCATE TABLE `catalog_product_option_type_value`;
> TRUNCATE TABLE `catalog_product_relation`;
> TRUNCATE TABLE `catalog_product_super_attribute`;
> TRUNCATE TABLE `catalog_product_super_attribute_label`;
> TRUNCATE TABLE `catalog_product_super_link`;
> TRUNCATE TABLE `catalog_product_website`;
> TRUNCATE TABLE `catalog_url_rewrite_product_category`;
> TRUNCATE TABLE `downloadable_link`;
> TRUNCATE TABLE `downloadable_link_price`;
> TRUNCATE TABLE `downloadable_link_purchased`;
> TRUNCATE TABLE `downloadable_link_purchased_item`;
> TRUNCATE TABLE `downloadable_link_title`;
> TRUNCATE TABLE `downloadable_sample`;
> TRUNCATE TABLE `downloadable_sample_title`;
> TRUNCATE TABLE `product_alert_price`;
> TRUNCATE TABLE `product_alert_stock`;
> TRUNCATE TABLE `report_compared_product_index`;
> TRUNCATE TABLE `report_viewed_product_aggregated_daily`;
> TRUNCATE TABLE `report_viewed_product_aggregated_monthly`;
> TRUNCATE TABLE `report_viewed_product_aggregated_yearly`;
> TRUNCATE TABLE `report_viewed_product_index`;

### Expected result

1. No SQL error

### Actual result

1. Foreign key SQL error will be displayed
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`main`.`catalog_product_option`, CONSTRAINT `CATALOG_PRODUCT_OPTION_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ROW_ID` FOREIGN KEY (`product_id`) REFERENCES `catalog_product_entity` (`row_), query was: INSERT INTO `catalog_product_option` (`product_id`, `type`, `is_require`, `sort_order`) VALUES (?, ?, ?, ?)

**Comment by mrkhoa99** [comment]
For this kind of issue, we should ask on https://magento.stackexchange.com/.
In your case, need to add:

> SET foreign_key_checks = 0;
> 
> // Your table
> 
> SET foreign_key_checks = 1;

Try again then.

**Comment by indefinitedevil** [comment]
Okay, so I don't think you understand.

After running the above script to wipe out the product tables, the creation of products with custom options became impossible because of a Magento error.

The script was run with foreign_key_checks off. Foreign key checks are *NOT* the issue.

The SQL error occurs in MAGENTO backend, not when running the SQL script.

After clearing the product tables using the above kind of script, you are unable to add products with custom options because the product entity_id comes from sequence_product and does not correlate with row_id any more.

With sequence_product and so on also removed, the custom options can be added.

What I am questioning is whether this is a design fault in the table structures.

**Comment by indefinitedevil** [comment]
See also this StackExchange question: https://magento.stackexchange.com/a/186393/35344

**Comment by engcom-backlog-nickolas** [comment]
@indefinitedevil, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by indefinitedevil** [comment]
@engcom-backlog-nickolas Are you saying that because *we* experienced this issue on Commerce, that it thus cannot exist on Open Source?

**Comment by engcom-backlog-nickolas** [comment]
@indefinitedevil, I cannot reproduce this issue on CE version.

> After clearing the product tables using the above kind of script, you are unable to add products with custom options because the product entity_id comes from sequence_product and does not correlate with row_id any more.

row_id introduced by Staging module, which is enterprise module.
