### ISSUE TITLE
Extending catalog search with custom results not working.

### ISSUE THREAD

**Issue by ajayshukla** [magento/magento2#15428]
I am trying to extend the magento catalog search so that I can get the results from external source and then show the results. I am able to show the results but not able to change the facets data by extending the layer class. Can anyone guide me how can I override the whole products collections for search result page and set the results, pagination, sort and facets accordingly.

Thanks

**Comment by ajayshukla** [comment]
Anyone has got reply, please let me know your thoughts.

**Comment by magento-engcom-team** [comment]
Hi @ajayshukla 
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
