### ISSUE TITLE
To attempt automatic rollback, please click the "Rollback" button

### ISSUE THREAD

**Issue by zezooo2** [magento/magento2#15429]
when i install any extensions(setting,web setup wizard,extension manager ,Extensions
Ready to Install,when i try to install any one) i see that ,any help?
![q2untitled](https://user-images.githubusercontent.com/39524625/40365884-f9035658-5dd5-11e8-8a84-b222b80ae9ff.jpg)

**Comment by zezooo2** [comment]
any help or suggestion

**Comment by magento-engcom-team** [comment]
Hi @zezooo2 
Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks
