### ISSUE TITLE
Distance based Shipping price in magento 2

### ISSUE THREAD

**Issue by nic02381** [magento/magento2#15425]
I need to show the shipping price dynamically based on the customer's pin code. I have a product's pin code now I need customer's pin code. So I can fetch the distance between this and get a difference price.

Preconditions
1. I am using Magento 2.2 CE
2. I am using xampp server on my local machine

Steps to reproduce
1. I create a custom shipping module
2. Fill all required fields from the backend
3. static price is showing correct on cart and checkout page

Expected result
1. When customer enter his pin code, I need to get the pin code on my custom shipping Carrier Model.
2. So, I can fetch the price with the pic code difference.

Actual result
1. I am not able to find the way to get customer's pin code on my custom shipping Carrier Model.

Here is my Carrier Model code: 

namespace Custom\Shipping\Model\Carrier;
 
use Magento\Quote\Model\Quote\Address\RateRequest;
use Magento\Shipping\Model\Rate\Result;
 
class Example extends \Magento\Shipping\Model\Carrier\AbstractCarrier implements
    \Magento\Shipping\Model\Carrier\CarrierInterface
{
    /**
     * @var string
     */
    protected $_code = 'example';

    /**
     * @param \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig
     * @param \Magento\Quote\Model\Quote\Address\RateResult\ErrorFactory $rateErrorFactory
     * @param \Psr\Log\LoggerInterface $logger
     * @param \Magento\Shipping\Model\Rate\ResultFactory $rateResultFactory
     * @param \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory $rateMethodFactory
     * @param array $data
     */

    public function __construct(
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Quote\Model\Quote\Address\RateResult\ErrorFactory $rateErrorFactory,
        \Psr\Log\LoggerInterface $logger,
        \Magento\Shipping\Model\Rate\ResultFactory $rateResultFactory,
        \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory $rateMethodFactory,
        array $data = []
    ) {
        $this->_rateResultFactory = $rateResultFactory;
        $this->_rateMethodFactory = $rateMethodFactory;
        parent::__construct($scopeConfig, $rateErrorFactory, $logger, $data);
    }
 
    /**
     * @return array
     */
    public function getAllowedMethods()
    {
        return [$this->_code => $this->getConfigData('name')];
    }
 
    /**
     * @param RateRequest $request
     * @return bool|Result
     */
    public function collectRates(RateRequest $request)
    {
        if (!$this->getConfigFlag('active')) {
            return false;
        }
        
        /** @var \Magento\Shipping\Model\Rate\Result $result */
        $result = $this->_rateResultFactory->create();
 
        /** @var \Magento\Quote\Model\Quote\Address\RateResult\Method $method */
        $method = $this->_rateMethodFactory->create();
 
        $method->setCarrier('example');
        $method->setCarrierTitle($this->getConfigData('title'));
 
        $method->setMethod('example');
        $method->setMethodTitle($this->getConfigData('name'));
 
        /*you can fetch shipping price from different sources over some APIs, we used price from config.xml - xml node price*/

        $amount = $this->getConfigData('price');
 
        $method->setPrice($amount);
        $method->setCost($amount);
 
        $result->append($method);
 
        return $result;
    }
}

**Comment by nic02381** [comment]
@magento-engcom-team Why you added Failed for this.

**Comment by nic02381** [comment]
@magento-engcom-team what happened?

**Comment by nic02381** [comment]
Does anyone have idea about this?

**Comment by nic02381** [comment]
I got a solution for this. Just leave.

**Comment by hansoncitra** [comment]
hey @nic02381 if you dont mind, can you please tell me how you solve this? I am stuck on this part too. Thank you in advance.
