### ISSUE TITLE
Tier price is not applying if product has special price

### ISSUE THREAD

**Issue by ghost** [magento/magento2#15426]
Tier price(Pricetype Discount Only) is not applying if product has special price

### Preconditions
1. Magento CE 2.2.4 without sample data is installed.
2.Create Simple product.

### Steps to reproduce
1. Set Special price to product
2. Add Tier Price with type(Discount) i.e for 3 Qty-->5% and 5 Qty-->10% 

### Expected result
1. Product price should Decrease to that product after Adding 3 or 5 Qty to cart
2.Tier price information should display on product page 

### Actual result
1. Tier Price will not show on front-end or price not decrease by adding 3 Qty to cart
but after removing special price it shows on front-end and price will decrease after add to cart.
So,problem is when,we assign special price and tierprice(only with discount) togather

**Comment by BezV8** [comment]
Just out of interest, why was this issue closed? I have noticed a similar issue and was not sure whether it is a bug or the intended behaviour.

**Comment by ghost** [comment]
If tier prices less than or equal to special price, you can display both special price and tier prices. Other wise only special price will display.
