### ISSUE TITLE
Not update shipping method in cart page

### ISSUE THREAD

**Issue by nicoloHevelop** [magento/magento2#15423]
Hi,

in the cart page, when i change the destination country, the rest call: /V1/guest-carts/:cartId/estimate-shipping-methods does not start and the shipping methods will not update with the correct destination country.

I've checked the amasty module configuration, but they are the same.

How ca i fix this issue?

**Comment by magento-engcom-team** [comment]
Hi @nicoloHevelop 
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
