### ISSUE TITLE
magentoDataFixture should use phpunit.xml <includePath />

### ISSUE THREAD

**Issue by josephmcdermott** [magento/magento2#15432]
The M2 integration test framework is 'almost' really good in terms of fixtures, however it appears to be locked to only Magento fixtures and does not allow third party vendors to create their own.

### Preconditions
1. Create a custom integration test in a third party extension.

### Steps to reproduce
1. Attempt to configure your own fixture, somewhere other than `dev/tests/integration/testsuite`.
2. For example `@magentoDataFixture My/Extension/_files/my_fixture.php`
3. Add a corresponding path to `<includePath/>` in phpunix.xml file.

### Expected / Actual result
The following line 130 hard codes the include path to `dev/tests/integration/testsuite`:
https://github.com/magento/magento2/blob/c24ad1e7af6bfb59bfe91fc424cbea243d05060f/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php#L130

As a result it is impossible to use fixture files anywhere other than the Magento core ones added to folder `dev/tests/integration/testsuite`.

**Comment by orlangur** [comment]
@josephmcdermott there is not bug here though, for now all integration tests are supposed to be placed in `dev/tests/integration`. I was one of the influencers to bring `Vendor\Module\Test\Unit` approach into life, before that unit tests were placed in `dev/tests/unit` as well.

As to me would be really nice to support all tests in a modular way residing in `Vendor\Module\Test\Integration`, `Vendor\Module\Test\Functional` and so on. Are you maybe interested in preparing necessary changes related to integration tests as one or more pull requests?

**Comment by josephmcdermott** [comment]
Hi @orlangur, thanks for the rapid response!

I agree its not a bug, its more of an _issue_. For my understanding, how would an extension developer get his tests in to `dev/tests/integration`? Are you meant to manually copy them there for each project, or is there some approach I am missing to automatically have them mapped over?

Once I have the full understanding of how it should work now, I can start looking at a PR to make it more modular.

**Comment by orlangur** [comment]
@josephmcdermott no way for extension developer yet just like prior to necessary refactoring it was not possible for unit tests. Only core tests and tests for custom implementation placed in `app/code` are supported by integration tests framework currently.

**Comment by josephmcdermott** [comment]
OK cool, thanks for the information. Can you provide a link to the PR for Unit Test changes for my reference, if it happens to all be in one place, no problem if not.

**Comment by orlangur** [comment]
Hi @josephmcdermott, here are the changes from ancient times related to unit tests: https://github.com/magento/magento2/commit/e9a6f52d082d3a955b1a19d07df58e6d1f53e7e1#diff-842b5002744a47500b1081259d4b2822, https://github.com/magento/magento2/commit/d74ea1050bbd165638ec59890c036c06dcbb975e#diff-842b5002744a47500b1081259d4b2822

I'm closing this issue as GitHub is intended exclusively for bug reports, feel free to propose any pull requests improving the situation or create a ticket in https://github.com/magento/community-features/issues repository if you think it is necessary.
