### ISSUE TITLE
Can't delete/edit product image on some migrated products.

### ISSUE THREAD

**Issue by zestbeauty** [magento/magento2#15437]
When we try to delete or edit the product image on a product that has been migrated and save, nothing changes.

### Preconditions
1. Magento 2.2.3
2. PHP 7.0
3. Migration from Magento 1.9.1.0
4. All folder permissions are correct

### Steps to reproduce
1. Open an imported product.
2. Delete the product image
3. Save the Product

### Expected result
1. Product image should be deleted

### Actual result
1. Magento saves the product with now errors and displays message that changes have been saved.
2. Go to the product image settings and the image is still there.

This issue does not happen on new created products, only migrated products.

It also does not happen on all migrated products.

**Comment by ghost** [comment]
Hi @zestbeauty i cannot reproduce by your's scenarios steps, can you provide more information

**Comment by ghost** [comment]
Hi @zestbeauty  thank you for your report. I cannot reproduce this issue on clean 2.2.3 magento installation. Please use https://github.com/magento/data-migration-tool/issues to report issues related to migration from magento 1.x to 2.x.
