### ISSUE TITLE
Can't add a hyperlink in contact form email template

### ISSUE THREAD

**Issue by jigardhaduk** [magento/magento2#15447]
### Preconditions

1. Magento 2.1.13
2. php 7.0.22

### Steps to reproduce

1. Create a new email template for contact by the backend.
**Marketing -> Communication -> Email Template**
2. Click on **New Template** button
3. Load **Contact Form** in **Template** dropdown
4. Add hyperlink in **Template Content**

### Expected result

1. A hyperlink should display in the email preview

### Actual result

A hyperlink display as plain text.

1. First try
![email-preview](https://user-images.githubusercontent.com/15403998/40409222-c72e08a0-5e87-11e8-900c-d751e466debc.png)

2. Second try
![email-preview-2](https://user-images.githubusercontent.com/15403998/40409280-f2c80da8-5e87-11e8-8132-381b0caca8c6.png)

**Comment by amittiwari024** [comment]
@jigardhaduk you should remove ' ' from the code then you are able to see link correctly.
 eg: `{{ <a href="#">Your text</a> }}`

**Comment by jigardhaduk** [comment]
@amittiwari024 Still display in plain text.
Please check following screen-shot.

![as-per-amit](https://user-images.githubusercontent.com/15403998/40464024-38e68586-5f36-11e8-93c1-bd4d80f09650.png)

**Comment by jigardhaduk** [comment]
Is there anyone to check this?

**Comment by jigardhaduk** [comment]
Hello @magento-engcom-team 
Would you please take a look at it?

**Comment by dasharath-wagento** [comment]
Hi @jigardhaduk ,
you can add hyperlink this way in template.
`<span>
  {{trans '<a href="%example">Example</a>' example='www.example.com' | raw }}
<span>`

**Comment by jigardhaduk** [comment]
As per @dasharath-wagento , still it displays in Plain Text.
![email-preview](https://user-images.githubusercontent.com/15403998/40906478-81edd9e8-67fe-11e8-988f-3b50bbf4fcf9.png)

**Comment by engcom-backlog-nickolas** [comment]
@jigardhaduk, thank you for your report. For hyperlink you may use something like:
{{trans 'Here goes test link <a href="www.example.com">example</a>' |raw}}
![peek 2018-07-12 13-24](https://user-images.githubusercontent.com/40755810/42627709-7b0bfc90-85d6-11e8-90d4-d2b1627cb783.gif)

**Comment by jigardhaduk** [comment]
as per @engcom-backlog-nickolas 

Please check,
https://streamable.com/692vs

**Comment by engcom-backlog-nickolas** [comment]
@jigardhaduk, thanks for feedback. Could you please provide more details? 
For instance, I don't see "Convert to Plain Text" button on your video. So, probably it's enabled on your instance by default?

**Comment by jigardhaduk** [comment]
I have set up the fresh M 2.1.13 without sample data and I am creating a new contact email template to add my custom link.

**Comment by jigardhaduk** [comment]
Hello @engcom-backlog-nickolas 
Is there any update?

**Comment by engcom-backlog-nickolas** [comment]
Hello @jigardhaduk, I've tried several instances with different versions, and still cannot reproduce described issue. The only way, I could receive the same result as on your video is press "Convert To Plain Text"button, and only after this enter the link.
![screenshot_1](https://user-images.githubusercontent.com/40755810/42800062-d9855dc8-89a2-11e8-9e02-56038b852522.png)
Could you please add more details? Cause on clean instances everything works fine.
