### ISSUE TITLE
"Out of memory crash" on "Cart Price Rules" setting based on category condition 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#15448]
### Preconditions

1. Magento 2.2.4
2. PHP 7.1.12

### Steps to reproduce

1. In CMS, click Marketing -> Promotions -> Cart Price Rules -> Add New Rule
2. In Conditions, click Add button(the "+" symbol) select "Product attribute combination"
3. Click the new "+" button, select "Condition" in the "Please choose a condition to add" dropdown
4. Click "...", then click the "Open Chooser" icon

### Expected result

1. Category checkbox tree should appear 

### Actual result

1. The browser freezes and will crash or display a js debug console with message "Paused before potential out-of-memory crash" in 10-40 seconds. 
![cart_rules_issue01](https://user-images.githubusercontent.com/39549798/40410773-e2fdc28a-5eb1-11e8-83b3-9d3e4517a888.png)
![cart_rules_issue02](https://user-images.githubusercontent.com/39549798/40410780-e8a6d2a8-5eb1-11e8-9282-a0d4c0941e0b.png)

**Comment by hostep** [comment]
Hi @yuchen2019 

I'm going to close this issue as it duplicates https://github.com/magento/magento2/issues/15121, which already got fixed in https://github.com/magento/magento2/pull/15265 and the fix should get included in Magento 2.2.5
