### ISSUE TITLE
After 2.3.0-alpha upgrade  'Zend\Mvc\Controller\LazyControllerAbstractFactory' not found

### ISSUE THREAD

**Issue by fooman** [magento/magento2#15441]
### Preconditions
1. install Magento 2.2

### Steps to reproduce

1. composer config minimum-stability alpha
2. composer require magento/product-community-edition:2.3.0-alpha --no-update 
(also copy updated require-dev dependencies)
3. composer update
4. bin/magento setup:upgrade

### Expected result

1. Upgrade should run

### Actual result

1.
```
php -dlog_errors_max_len=0 -f bin/magento
PHP Fatal error:  Uncaught Error: Class 'Zend\Mvc\Controller\LazyControllerAbstractFactory' not found in /var/www/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:314
Stack trace:
#0 /var/www/vendor/zendframework/zend-servicemanager/src/Config.php(137): Zend\ServiceManager\ServiceManager->addAbstractFactory('Zend\\Mvc\\Contro...')
#1 /var/www/vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php(225): Zend\ServiceManager\Config->configureServiceManager(Object(Zend\Mvc\Controller\ControllerManager))
#2 [internal function]: Zend\ModuleManager\Listener\ServiceListener->onLoadModulesPost(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent))
#4 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('loadModules.pos...', Object(Zend\ModuleManager\ModuleEvent))
#5 /var/www/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(129): Zend\EventManager\EventManager->triggerEvent(Object(Zend\ModuleManager\ModuleEvent))
#6 /var/www/setup/src/Magento/Setup/Application.php(35): Zend\ModuleManager\ModuleManager->loadModules()
#7 /var/www/vendor/magento/framework/Console/Cli.php(71): Magento\Setup\Application->bootstrap(Array)
#8 /var/www/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#9 {main}
  thrown in /var/www/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 314
```

The issue can be fixed by manually editing `composer.json` autoload section to
```
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
```
and then run `composer dumpautoload`.

However overall I think we should strive to not have to make any changes to the `composer.json` file during an upgrade beyond the version number bump of `magento/product-community-edition`. 

After the initial `composer create-project magento/project-community-edition` the root `composer.json` file essentially is out of Magento's control and ideally everything we need to pull in/want to change should happen via `magento/product-community-edition`

In this particular case I do not understand why this 1 file gets such special treatment and gets added under setup/src. Better options in my mind would be:
1. Upgrade zend-mvc to include this wanted file
2. Provide the file and autoload information via a separate module

**Comment by buskamuza** [comment]
Hi @fooman , please run https://github.com/magento/magento2/blob/2.3-develop/dev/tools/UpgradeScripts/pre_composer_update_2.3.php before `composer update` during upgrade process.
We know about this issue and are working on the docs and blog post on this (not ready yet).
Sorry for the confusion.

**Comment by engcom-backlog-nickolas** [comment]
Hello @fooman, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by kirkmadera** [comment]
I received this error when attempting to run this script because my composer json had numerically indexed repositories without keys.

    Fatal error: Uncaught TypeError: strtolower() expects parameter 1 to be string, integer given in /var/www/myproject/pre_composer_update_2.3.php:151
    Stack trace:
    #0 /var/www/myproject/pre_composer_update_2.3.php(151): strtolower(0)
    #1 {main}
   thrown in /var/www/myproject/pre_composer_update_2.3.php on line 151


Should update the script to consider this as this will be pretty common.

**Comment by ronniereid** [comment]
I also received this error. What is the workaround?

Thanks in advance.

> I received this error when attempting to run this script because my composer json had numerically indexed repositories without keys.
... 
> Should update the script to consider this as this will be pretty common.

**Comment by kirkmadera** [comment]
The fix was to edit my composer.json and replace the numerically indexed repositories array with a string indexed one.

**Comment by fooman** [comment]
2.3.0 was released with these changes included. See https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html for detailed upgrade instructions.

**Comment by bangermeier** [comment]
Is there a similar script for cloud?
