### ISSUE TITLE
Category custom sorting - returns an incorrect value of items

### ISSUE THREAD

**Issue by jigardhaduk** [magento/magento2#15446]
Custom catalog sorting return an incorrect value

### Preconditions

1. Fresh Magento 2.2.3
2. php 7.0.22

### Steps to reproduce

1. I have added a custom sort order of Best Seller. Like:

            $this->_collection->getSelect()
                        ->joinLeft(
                                'sales_order_item',
                                'e.entity_id = sales_order_item.product_id',
                                'SUM(sales_order_item.qty_ordered) AS ordered_qty'
                            )
                ->group('e.entity_id')
                ->order('ordered_qty  desc');
### Expected result

1. The total size of product and display products must same.

### Actual result

1. The total size of product and display products are not same.
![custom-sort](https://user-images.githubusercontent.com/15403998/40408800-5b94bd6a-5e86-11e8-916a-4d612c3c1e56.png)

**Comment by jigardhaduk** [comment]
Is there anyone to check this?

**Comment by jigardhaduk** [comment]
Hello @magento-engcom-team 
Would you please take a look at it?

**Comment by jigardhaduk** [comment]
Hello @magento-engcom-tea
Would you please take a look at it?

**Comment by ghost** [comment]
Hi @jigardhaduk i  cannot reproduce this on 2.2-develop branch

**Comment by ghost** [comment]
Hi @jigardhaduk , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@jigardhaduk, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
