### ISSUE TITLE
What does Adobe's Aquisition of Magento mean for Open Source

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#15440]
I know. This isn't the place for questions, but since it pertains to development I thought I would try. What will Adobe's acquisition of Magento mean for the future of Magento CE? Is it going to continue being Open Source or will it be folded into the Enterprise version? I need to know what to tell my client.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines-->

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by gcampedelli** [comment]
https://twitter.com/mjasay/status/998930665805496321

![image](https://user-images.githubusercontent.com/7084395/40419705-89c4ebd0-5e5c-11e8-8763-607b903650e4.png)

**Comment by gcampedelli** [comment]
But I think we should ask Adobe a commitment on that!!

**Comment by ADVANCEDSPORTVE** [comment]
WHAT???!!! I fail to see why Magento keeps changing hands! i suspect if Adobe gets Magento, CE may be terminated .. i just got that feeling ...

**Comment by Ctucker9233** [comment]
@ADVANCEDSPORTVE It seems to be a done deal. I genuinely hope it stays open source.

**Comment by osrecio** [comment]
I will close this Issue, this channel is to report technical problems with framework
The right place can be a [Magento Forums](http://community.magento.com/).

Thanks
