### ISSUE TITLE
Error Export products's csv

### ISSUE THREAD

**Issue by Toregam** [magento/magento2#15455]
### Preconditions

1. Magento version: 2.1.7
2. Reindex / clear cache.

### Steps to reproduce

1. go to System/Export
2. Select: Products
3. Select: CSV

### Expected result

1. Download the csv containing all the products.

### Actual result

1.Error: Correct the value of the recorded data.
1. [Screenshot, logs]
![immagine](https://user-images.githubusercontent.com/32936901/40416612-fdbe76d4-5e7d-11e8-965d-271f40fbc943.png)

**Comment by Toregam** [comment]
Can you help me??

**Comment by ghost** [comment]
@Toregam, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
