### ISSUE TITLE
Buttons under dashboard section not responding to click event

### ISSUE THREAD

**Issue by asimbyazid** [magento/magento2#15456]
I was working on typography section, after I changed the header styling, I realized the SAVE CONFIG button is not working. the later on I found out all the sections are not responding to click event

### Preconditions

1.  Magento 2.2.3
2.  PHP version 7.0

### Steps to reproduce

1. login to magento admin page
2. click on any section 
3. 

### Expected result

1. Toggle drawer

### Actual result

1. [Screenshot, logs]

**Comment by ghost** [comment]
@asimbyazid, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
