### ISSUE TITLE
Sales emails are sent from a strange email

### ISSUE THREAD

**Issue by staywithabhi** [magento/magento2#15458]
I am using magento 2.2.4 on go daddy VPS.I have configured the store email addresses properly and also select in sales->sales emails.
Whenever an order is placed customer recieves order confirmation mail in spam folder which is due to strange email send address(Email From).
I am not using any custom SMTP extension this is a fresh magento installed

### Preconditions

1. magento 2.2.4
2. Server goDaddy-VPS

### Steps to reproduce

1.Set up store email adresses
2.Select Email sender in store->configuration->sales->sales emails
3. Order confirmation mail is sent from a very strange email address
4. Places an order on magento 2.2.4
5.check order mail **mail from** address

### Expected result

1. Sales emails must be sent from store email address which is selected for sales order

### Actual result
Emails are sent from very strange (from) email address

1. [Screenshot
![abhishek vortexglobal in](https://user-images.githubusercontent.com/12792172/40418610-75b4afa6-5ea0-11e8-8989-0249dfe2b73e.png)
]

**Comment by hostep** [comment]
Hi @staywithabhi 

I think this is a duplicate of https://github.com/magento/magento2/issues/14952
If you agree, can you close this issue?

Thanks! :)

**Comment by staywithabhi** [comment]
Hi @hostep ,
Thanks for solution,yeah it seems this issue is duplicate.
