### ISSUE TITLE
Visual Issue "vertex tax classes"

### ISSUE THREAD

**Issue by SamB-GB** [magento/magento2#15463]
Having started setting up a new Magento 2.2.4 the TAX calculations where off for shipping but I wasn't able to fix the issue. I searched Google and lots of places where pointing to setting the correct tax Class for shipping but I wasn't able to find this setting UNTIL I found it in Stores > Configuration > Sales > Tax > Vertex Tax Classes

Changing these settings changed the calculation despite the fact I am not using Vertex so you may want to re-word that back to Tax Classes

### Preconditions

1. M2 (2.2.4)
2. PHP 7.1

### Actual result

1. Without these settings enabled the tax calculation was wrong. In particular with the shipping tax but I didn't touch these settings at first as it appeared to be for the Vertex module only.

<img width="1335" alt="screen shot 2018-05-23 at 16 42 49" src="https://user-images.githubusercontent.com/15860857/40435348-620db76a-5ea8-11e8-94bb-1aade4eef6d5.png">

**Comment by hostep** [comment]
I have to agree with @SamB-GB here.

That Vertex module completely overwrites 3 default Magento system config fields and blatantly puts their own branding on top of it. Wth? Did someone from Magento actually review this module before this got included by default???

System config fields it overwrites:
- tax/classes/shipping_tax_class
- tax/classes/default_product_tax_class
- tax/classes/default_customer_tax_class

**Comment by elvinristi** [comment]
FYI if you are using `composer.json` then just exclude the module if you don't need or use the service, i.e. after "require-dev" section

```
    "replace": {
        "dotmailer/dotmailer-magento2-extension": "*",
        "amzn/amazon-pay-and-login-magento-2-module": "*",
        "klarna/module-core": "*",
        "klarna/module-kp": "*",
        "klarna/module-ordermanagement": "*",
        "shopialfb/facebook-module": "*",
        "temando/module-shipping-m2": "*",
        "vertex/module-tax": "*",
        "magento/module-signifyd": "*"
    },
```

This will remove after `composer update` those.

But I agree that some strange modules have been included in `vanilla` version.

**Comment by EliasKotlyar** [comment]
@elvinristi : Thanks for your trick to avoid having these modules. I just wanted to add, that the "Vertex" Module is not compatible with PHP7.0.

Refer here for details:
https://github.com/magento/magento2/issues/12180#issuecomment-372574834

**Comment by navarr** [comment]
Hi, thanks for this report!

This is something we overlooked when we moved from a standalone module to a bundled extension.

We have this in our backlog now and you should expect it fixed in Vertex Tax Links for Magento 2, v2.1.10 and above, which we plan to have included in Magento 2.2.6

Internal Ticket VRTX-334

**Comment by magento-engcom-team** [comment]
@SamB-GB Unfortunately, we are closing this ticket, as it does not relate to the code published in the `magento2` repository.

**Comment by elvinristi** [comment]
@magento-engcom-team , why you have then included in your package **vertex/module-tax** if you haven't even tested this and don't take responsibility to make sure that code gets fixed and release ASAP correct one and we need instead come up hacks to remove the module?

**Comment by domeglic** [comment]
@elvinristi thanks for the composer solution, that really helps. This is already the 4th non-magento module that contains critical bugs.  
It looks like from now on any new 3rd party modules I see during update will be immediately deactivated in our shops.

**Comment by mariamghalleb** [comment]
I've been having this issue, can anyone confirm its vertex tax module related? 
And is there any way to fix it? please.. 
![capture3](https://user-images.githubusercontent.com/28814080/46745618-14cea000-ccb6-11e8-84ff-811f9eced770.PNG)

**Comment by navarr** [comment]
@mariamghalleb Can you confirm that the composer package `vertex/sdk` is installed?  If so, can you please run `bin/magento setup:di:compile -vvv` and copy the error output here?

This is an error I've not seen before.  Please also include information such as your version of PHP, the version of vertex/module-tax installed (check vendor/vertex/module-tax/composer.json) and the version of Magento installed
