### ISSUE TITLE
the bug about when i change local language 

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1547]
the bug about when i change local language  use chinese in "zh_Hans_CN"   but the zh_CN.csv file is not used .   i think the zh_CN.csv is default of all chineses  when zh_Hans_CN.csv  does not exist

**Comment by vpelipenko** [comment]
@LifeAsBook, it is not true. If you want to use zh_Hans_CN you should have zh_Hans_CN.csv. There is no fallback to zh_CN.

**Comment by LifeAsBook** [comment]
@vpelipenko,  all Magento modules have default zh_CN.csv  but  not to use in anywhere

**Comment by vpelipenko** [comment]
It will be used if you set zh_CN locale for your store.

**Comment by LifeAsBook** [comment]
@vpelipenko i mean is the backend manager Interface Locale have no  zh_CN .   only have zh_Hans_CN,zh_Hant_HK,zh_Hant_TW
![23](https://cloud.githubusercontent.com/assets/10986726/8897608/cbe36652-344a-11e5-99e1-b6eba6a8239b.jpg)

**Comment by LifeAsBook** [comment]
@vpelipenko hi

**Comment by vpelipenko** [comment]
@LifeAsBook, I see, thank you for pointing this. It looks like a bug.

**Comment by piotrekkaminski** [comment]
It should be fixed now.
