### ISSUE TITLE
Too many password reset requests. Please wait and try again or contact ...

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#15483]
Magneto 2 is limited to a maximum of one password reset request, even when the setting is set higher in the backend. Similar to issue [#11409](https://github.com/magento/magento2/issues/11409), but still present on 2.2.1

### Preconditions

1. Magento 2.2.1

### Steps to reproduce

1. Login to Admin Panel.
2. Select customer from Customers -> All Customers
3. Click reset password link and on page refresh click link again.

### Expected result

1. Magento should allow as many reset password attempts as are set in Stores -> Configuration -> Customers -> Customer Configuration -> Password Options

### Actual result

1. First password reset attempt is accepted from either Frontend or Admin Panel.
2. Subsequent password reset attempts display the message "Too many password reset requests. Please wait and try again or contact ..." regardless of settings.

**Comment by phoenix128** [comment]
Unable to reproduce in 2.1, 2.2 and 2.3 .
Please check you are not having an issue with a misconfiguration of `Min Time Between Password Reset Requests` parameter. You are probably trying to send multiple requests within the minimum required interval.

**Comment by BezV8** [comment]
The `Min Time Between Password Reset Requests` parameter is currently set to 0, which according to the helptext on the backend should disable the time interval entirely.

**Comment by phoenix128** [comment]
Hello @BezV8 ,
still unable to reproduce it, even with `Min Time Between Password Reset Requests` = `0`.

Since it is not a global parameter, please make sure this setting is correctly configured in your store specific view.

**Comment by phoenix128** [comment]
@BezV8 , this PR should fix it https://github.com/magento/magento2/pull/11434 .

**Comment by magento-engcom-team** [comment]
Hi @BezV8 
Please try if it's reproducible with the clean 2.2.5 install.

**Comment by BezV8** [comment]
@phoenix128 Apologies for the delay in replying to this, I didn't get the email notification of a new comment. I'll try installing a fresh 2.2.5 site and report back on the fix.

**Comment by BezV8** [comment]
I can confirm that this is now fixed on a fresh install of 2.2.5
