### ISSUE TITLE
When link to simple product my configurable product lose image roles. 

### ISSUE THREAD

**Issue by gitgiangalbe** [magento/magento2#15481]
### Preconditions

1.  PHP Version 7.1.14
2.  Magento Version 2.2.0 on Linux Fedora
3.  5.7.21 - MySQL Community Server (GPL) 
4.  Using Magento 2 REST API 

### Steps to reproduce

1.  Create Configurable Product
2.  Create multiple Simple product
3.  Assing/Link relative Simple product to Configurable (using "/rest/V1/configurable-products/" + ConfigSku + "/child" " )

### Expected result

1.  Configurable product mantain his image role, so i can see image in product listing on magento web store front end.

### Actual result

1. Configurable product lose image roles
2. I notice Configurable product after link simple by REST API change his "<attribute_code>image</attribute_code>"  to value "no_selection" . But trying to change same attribute manually Config product lose Variation.

**Comment by navneetkumar-pim-webkul** [comment]
I am facing the Same Issue.
when I am trying to link association using REST API. Configurable product loses Image Roles.

**Comment by gitgiangalbe** [comment]
only way to solve issue is to update Magento to 2.2.4.
Since i updated solved my problems. Unfortunately there isn't different solution.

**Comment by ghost** [comment]
@gitgiangalbe, thank you for your report.
As the problem is solved after updating Magento, we are closing this issue. If you'd like to update it, please reopen the issue.
