### ISSUE TITLE
Requested Store not found while applying new theme after updating magento 1.9 to 2.1.7

### ISSUE THREAD

**Issue by daniyal154** [magento/magento2#15484]
After I had migrated my website from magento 1.9 to magento 2.1, Everything is working fine except for a few bugs

## # **Preconditions**

- Magento 2.1.7

## Steps to reproduce

- Open Cli

- Open Admin Panel and go to content->configuration->edit

- Apply New Theme

## Expected result

- My Theme should have been changed

## Actual result

- When i try to change the Theme i get the ERROR

**Requested store is not found**

**Comment by engcom-backlog-nickolas** [comment]
Hello @daniyal154, thank you for your report. As I cannot reproduce this issue on clean magento 2.1.7 installation, could you please report this issue here: https://github.com/magento/data-migration-tool/issues
