### ISSUE TITLE
Custom image roles not saving on multiple images for product

### ISSUE THREAD

**Issue by joshporter** [magento/magento2#1548]
I am currently unable to have more than one custom image role/attribute for different images. 

Steps to replicate:
* Add 2 product attributes with 'Catalog Input Type for Store Owner' set to 'Media Image' (I created Desktop Image and Mobile Image).
* Add more than 2 images to a product
* Select 'Desktop Image' role on one image
* Go to a different image and select 'Desktop Image' for this image

The result will be that only one image can have a role, is this meant to be the case? It seems like a bug, if multiple images cannot have the same roles i.e 2 images which have a Desktop Image role, and another 2 images with a Mobile Image role.

**Comment by kokoc** [comment]
@joshporter thank you for reporting the issue. Internal reference: ECGIN-48

**Comment by tanya-soroka** [comment]
Hello @joshporter 
Thank you for our request.

Magento 2 supports logic of the unique type per image. Means product should have:
*  one small image (used for the product images in listings on category and search results pages, and to display the product images needed for sections such as for Up-sells, Cross-sells, and the New Products List)
* one thumbnail  (appear in the thumbnail gallery, shopping cart, and in some blocks such as Related Items; backend grids)
* one based (the main image on the product detail page) 
* one custom1 (depend on your customization)
* image which doesn't have any types ( appear on the product / category page as additional images)

It also can be combination: 1 image which is assigned to all or few types. 

I hope this inrfomaiton can help you.

If you need additional logic, I will recommend to create a new customization or use extension ( it is open area fro the 3d party developers).
