### ISSUE TITLE
Allow shipping method usage in RMA but not in checkout

### ISSUE THREAD

**Issue by tim-bezhashvyly** [magento/magento2#15493]
Currently it is not possible to use shipping method for RMA without enabling it for checkout.

### Preconditions
1. Magento 2.2.3

### Steps to reproduce
1. Enable shipping method for RMA bit not for checkout
2. Go to authorised return request and click on "Create Shipping Label" button

### Expected result
1. The enabled method is available for returns

### Actual result
1. The enabled method does not show up

**Comment by ghost** [comment]
@tim-bezhashvyly ,  thank you for your report. RMA is releteted for Magento EE version.Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
