### ISSUE TITLE
We're sorry, an error has occurred while generating this email.

### ISSUE THREAD

**Issue by pengting** [magento/magento2#1549]
![1](https://cloud.githubusercontent.com/assets/4326820/8852127/fb136a70-3185-11e5-9a04-d1fa499bcb82.png)

After importing the demo data,the installation was successful。
Display “We're sorry, an error has occurred while generating this email.”

**Comment by pengting** [comment]
view exception.log
![2](https://cloud.githubusercontent.com/assets/4326820/8852301/ee7b6b04-3186-11e5-9016-8cc87842a614.png)

**Comment by ahmadalkaid** [comment]
Hi Guys,

I have the same issue. So please could you give us an answer.
Thanks

**Comment by pengting** [comment]
@ahmadalkaid  hello
installing sendmail can solve this problem.

**Comment by kokoc** [comment]
@pengting @ahmadalkaid thank you for reporting the issue. Internal reference: MAGETWO-40944

**Comment by CoreyCole** [comment]
Hey guys, I have sendmail installed but I'm still getting the same "We're sorry..." error. Does it need to be configured beyond the default `sudo apt-get install sendmail` installation?

**Comment by kokoc** [comment]
This issue is fixed and delivered. Could you please verify a fix?

**Comment by MrGekko** [comment]
I still have this error

**Comment by lijithmg** [comment]
Installing the sendmail solved the issue for me.

**Comment by danielc1234** [comment]
Sendmail did not resolve this issue for me.

**Comment by rolandurban** [comment]
sudo chmod -R 777 pub/ solves the problem for me.
see http://jingigirl.blogspot.de/2015/08/install-sample-data-magneto.html

**Comment by piotrekkaminski** [comment]
If someone still have this issue, please reopen the report.

**Comment by Quotacious** [comment]
I experienced this on a fresh install of Magento 2.0 CE final.  I tried installing sendmail, error persisted, did the chmod, same thing. Only when I re-ran the sample data install did the error went away.  Seems like it's just a matter of the install instructions/requirement check being updated.

**Comment by ghost** [comment]
Try going to various products and categories and making sure you can add something to the cart. If it's a permission issue, it will manifest then. Otherwise, you should not see this message, even if you do not have a mail server.

**Comment by ramsampathi** [comment]
How to Installing the sendmail? Because i got same issue

**Comment by rohan-mishra-sf** [comment]
Installed sendmail, but no change. If i add a product myself in a new category i created, then that product displays. However sample products which were imported do not display.

**Comment by kramskov** [comment]
Update page cache after all.

**Comment by j1nx3d** [comment]
I received the same error when use `$this->_objectManager` on a Custom Model. 
I instantiate the `ObjectManagerInterface `on the construct, something like this:

```
use Magento\Framework\ObjectManagerInterface;
class MyHelper extends AbstrctHelper{
    protected $_objectManager;
    public function __construct(Context $context,
            ObjectManagerInterface $objectManager){
            parent::__construct($context);
            $this->_objectManager = $objectManager;
    }
}
```

This solves my issue **We're sorry, an error has occurred while generating this email**, I don't know if is ok to do it like this. 

FYI:
I'm using a fresh Magento 2.1 Installation by composer, nginx 1.10.1 and php fpm 7.0.6

**Comment by webspeaks** [comment]
This error is quite misleading. In my case an error in MySql query was causing this.
You should enable developer mode the get the exact error. 
`php ./bin/magento deploy:mode:set developer`

**Comment by chapagain** [comment]
In my case it was missing `php-gd` extension on my machine.

This was on my exception log (`magento_root/var/log/exception.log`):

> main.CRITICAL: exception 'Exception' with message 'Required PHP extension 'gd' was not loaded.' in /var/www/html/magento2/vendor/magento/framework/Image/Adapter/Gd2.php:620

Solved by installing php-gd library on my Ubuntu machine with the following command:

`sudo apt-get install php-gd`

If you want to install for php5.6 then you may run:

`sudo apt-get install php5.6-gd`

**Comment by hakabe** [comment]
php bin/magento setup:static-content:deploy

**Comment by BrewCurious** [comment]
Unless I'm mistaken, the error(s) that you are receiving are not going to be solved by installing sendmail. By default, the system tries to send an email to the administrator of the website when any error(s) occur instead of displaying them on the site. If you don't have sendmail set up properly, the process generates the "We're sorry, an error has occurred while generating this email." error. You can either set up sendmail with a valid email address to have the underlying error(s) sent to you or you can put the site into developer mode and the error should display on the page and not attempt to send email.

**Comment by treestonemedia** [comment]
Still getting this error - only in production mode

**Comment by skMagentoguru** [comment]
Guys if you want to resolve the issue then see this http://www.vwebx.com hope soo you will find the positive results.
Thankyou,

**Comment by KareemSultann** [comment]
Guys, I still have this issue please can anyone help me?

**Comment by KareemSultann** [comment]
OMG, Solved this is the steps
1- enable developer mode using command line php bin/magento deploy:mode:set developer
2- clear cache using command line php bin/magento cache:flush
3- reload the frontend page
4- after reloading the page the message will change to
Error filtering template: Unable to write file into directory \C:/xampp/htdocs/Magento/pub/media/catalog/product\cache\f073062f50e48eb0f0998593e568d857/m/b. Access forbidden.
5- follow this link
https://magento.stackexchange.com/questions/170376/magento-2-unable-to-write-file-into-directory-access-forbidden
6- clear cache
7- reload the fronend page again
8- if you see another message after enabling developer mode you can search for it
hope this help you guys

**Comment by robintlt** [comment]
@kemoz0 thank you.. it worked perfectly.

**Comment by satendrat** [comment]
Thanks, this is the best solutons.
