### ISSUE TITLE
Breadcrumb not showing

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#15509]
### Preconditions

1. Magento 2.2.4, PHP 7.X, MySQL 5.6
2. Nginx Server

### Steps to reproduce

1. Upgrade Magento version from 2.1.7 to 2.2.4
2. Run all the Magento command after upgrade

### Expected result

1. On product page, breadcrumb is showing.

### Actual result

1. Breadcrumb is not showing on product page.

**Comment by phoenix128** [comment]
Unable to reproduce the issue on 2.1, 2.2 and 2.3 . Can you please provide more details?
Does it work with the default Luma theme?

**Comment by mropanen** [comment]
At least sometimes this seems to depend on where you come to the product page from.
If entering through category page, breadcrumb is shown.
If entering from search, breadcrumb is not shown.

**Comment by pniel-cohen** [comment]
Do you have a custom top-menu?
-- if so, that might explain... you may try my workaround from [here](https://magento.stackexchange.com/questions/227232/magento2-breadcrumbs-disappeared-from-product-page-after-upgrading-to-2-2-4).

**Comment by rishabhrkrai** [comment]
@phoenix128 I upgrade my magento version from 2.1.7 to 2.2.4.  I have porto theme but breadcrumb was working on earlier magento version.

@pini-girit I have Magento's default top menu. Just styling some this from the admin category section

**Comment by pniel-cohen** [comment]
Did you try upgrading your theme after the Magento upgrade? (maybe they made the necessary adjustments for 2.2.4). Also - You may still try my workaround to see if it's working for you.

**Comment by phoenix128** [comment]
This seems to be a theme issue. Please check if it is working with the default Magento Luma theme.

**Comment by robkor** [comment]
I'm using 2.2.4 and didn't have this problem on 2.2.3. The breadcrumbs are missing on the productpage. The category page is still showing the breadcrumb, but when selecting a product, the product page is missing the breadcrumb. I'm using Porto and checked that when using Luma the breadcrumb is still missing.

@pini-girit I've noticed your workaround, but can you explain more about how to implement this?

**Comment by pniel-cohen** [comment]
@robkor, You need to build a simple module & extend \Magento\Theme\Block\Html\Breadcrumbs, you don't need di.xml, just create a Block class & paste the first code snippet (you'll need to adjust the names...). After that, you'll have to override app/design/frontend/Vendor/Theme/Magento_Catalog/templates/product/breadcrumbs.phtml by copying it to your theme app/design/frontend/Vendor/Theme/Magento_Catalog/templates/product/breadcrumbs.phtml (easier) or by layout.xml if you like & replace it's contents with the second code snippet.

**Comment by michaelDWarnick** [comment]
@pini-girit Thanks for providing a fix... to clarify for anyone who needs it.

(fyi, i am using the Porto theme on Magento 2.2.4)

Step 1. Find and open file: app/code/Smartwave/Porto/Block/Template.php ("/Smartwave/Porto/" are my specific theme folders)

At the bottom, and just before the closing ?> tag, i added snippet 1 from @pini-girit 's post [here](https://magento.stackexchange.com/questions/227232/magento2-breadcrumbs-disappeared-from-product-page-after-upgrading-to-2-2-4)

Save the page.

Step 2. Create a new file named breadcrumbs.phtml inside my theme's folder which in my case is my child-theme's folder. As in: app/design/frontend/Smartwave/porto_child/Magento_Catalog/templates/product/breadcrumbs.phtml

Inside my new breadcrumbs.phtml file I copied and pasted the code from snippet 2 from @pini-girit post.

Save the page. Refresh the front end.

Voila! it works!

**Comment by versdivers** [comment]
Know that since the update the product page has its own breadcrumbs :

`vendor/magento/module-catalog/view/frontend/templates/product/breadcrumbs.phtml`

**Comment by ghost** [comment]
@RishabhRkRai, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![peek 2018-07-09 16-33](https://user-images.githubusercontent.com/40756187/42453722-484a4894-8396-11e8-8bf6-694d83973642.gif)

**Comment by snowcore** [comment]
Basically, this is related to the new way of generating breadcrumbs: https://magento.stackexchange.com/questions/227232/magento2-breadcrumbs-disappeared-from-product-page-after-upgrading-to-2-2-4

**Comment by marsboul2d** [comment]
> @pini-girit Thanks for providing a fix... to clarify for anyone who needs it.
> 
> (fyi, i am using the Porto theme on Magento 2.2.4)
> 
> Step 1. Find and open file: app/code/Smartwave/Porto/Block/Template.php ("/Smartwave/Porto/" are my specific theme folders)
> 
> At the bottom, and just before the closing ?> tag, i added snippet 1 from @pini-girit 's post [here](https://magento.stackexchange.com/questions/227232/magento2-breadcrumbs-disappeared-from-product-page-after-upgrading-to-2-2-4)
> 
> Save the page.
> 
> Step 2. Create a new file named breadcrumbs.phtml inside my theme's folder which in my case is my child-theme's folder. As in: app/design/frontend/Smartwave/porto_child/Magento_Catalog/templates/product/breadcrumbs.phtml
> 
> Inside my new breadcrumbs.phtml file I copied and pasted the code from snippet 2 from @pini-girit post.
> 
> Save the page. Refresh the front end.
> 
> Voila! it works!

Hi @michaelDWarnick !

Thanks for your solution, it's working but I have a compilation error with it : 

```
[ReflectionException]
  Class \Smartwave\Porto\Block\Vendor\Module\Block\Html\Breadcrumbs does not exist
```
Did I do something wrong ? Did you change anything when you paste the code from @pini-girit ?
