### ISSUE TITLE
REST API no longer working properly

### ISSUE THREAD

**Issue by msptrooper911** [magento/magento2#15508]
I use a google script that pulls information from my magento 2 and it was working on all prior versions including 2.2.3 until I updated to 2.2.4. The line of code that seems to be failing now is maybe UrlFetchApp.fetch("http://WEBSITE/rest/default/V1/orders/?searchCriteria", plusOptions).

### Preconditions

1. magento 2.2.4
2. php7

### Steps to reproduce

1. install magento 2.2.4
2. create API integration
3. create google script pulling information over REST API

### Expected result

1. should download information from the store

### Actual result

1. gives any error TypeError: Cannot read property "length" from undefined. This is the same error that exists when I use an invalid API key but the key is correct and worked prior.

**Comment by yaroslav-zenin** [comment]
try `UrlFetchApp.fetch("http://WEBSITE/rest/default/V1/orders/?searchCriteria=[]", plusOptions)`

**Comment by msptrooper911** [comment]
thank you. adding the = [ ] fixed the issue!
