### ISSUE TITLE
Magento Installation Error on Mac OS 10.7 Lion with php 5.5, MySQL 5.6

### ISSUE THREAD

**Issue by Galch24** [magento/magento2#1550]
Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':
Installing schema..
[ERROR] exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause' in /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('CREATE TABLE IF...', Array)
#5 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('CREATE TABLE IF...', Array)
#6 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(488): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('CREATE TABLE IF...', Array)
#7 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1974): Magento\Framework\DB\Adapter\Pdo\Mysql->query('CREATE TABLE IF...')
#8 /Users/Galina/Sites/magento2.lan/app/code/Magento/Eav/Setup/InstallSchema.php(217): Magento\Framework\DB\Adapter\Pdo\Mysql->createTable(Object(Magento\Framework\DB\Ddl\Table))
#9 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Model/Installer.php(761): Magento\Eav\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#10 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Model/Installer.php(695): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#11 [internal function]: Magento\Setup\Model\Installer->installSchema()
#12 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Model/Installer.php(298): call_user_func_array(Array, Array)
#13 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#14 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /Users/Galina/Sites/magento2.lan/setup/index.php(31): Zend\Mvc\Application->run()
#25 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause, query was: CREATE TABLE IF NOT EXISTS `eav_entity` (
`entity_id` int UNSIGNED NOT NULL auto_increment COMMENT 'Entity Id' ,
`entity_type_id` smallint UNSIGNED NOT NULL default '0' COMMENT 'Entity Type Id' ,
`attribute_set_id` smallint UNSIGNED NOT NULL default '0' COMMENT 'Attribute Set Id' ,
`increment_id` varchar(50) NULL default NULL COMMENT 'Increment Id' ,
`parent_id` int UNSIGNED NOT NULL default '0' COMMENT 'Parent Id' ,
`store_id` smallint UNSIGNED NOT NULL default '0' COMMENT 'Store Id' ,
`created_at` timestamp NOT NULL default CURRENT_TIMESTAMP COMMENT 'Created At' ,
`updated_at` timestamp NOT NULL default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At' ,
`is_active` smallint UNSIGNED NOT NULL default '1' COMMENT 'Defines Is Entity Active' ,
PRIMARY KEY (`entity_id`),
INDEX `EAV_ENTITY_ENTITY_TYPE_ID` (`entity_type_id`),
INDEX `EAV_ENTITY_STORE_ID` (`store_id`),
CONSTRAINT `EAV_ENTITY_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID` FOREIGN KEY (`entity_type_id`) REFERENCES `eav_entity_type` (`entity_type_id`) ON DELETE CASCADE,
CONSTRAINT `EAV_ENTITY_STORE_ID_STORE_STORE_ID` FOREIGN KEY (`store_id`) REFERENCES `store` (`store_id`) ON DELETE CASCADE
) COMMENT='Eav Entity' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci' in /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /Users/Galina/Sites/magento2.lan/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('CREATE TABLE IF...', Array)
#4 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('CREATE TABLE IF...', Array)
#5 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(488): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('CREATE TABLE IF...', Array)
#6 /Users/Galina/Sites/magento2.lan/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1974): Magento\Framework\DB\Adapter\Pdo\Mysql->query('CREATE TABLE IF...')
#7 /Users/Galina/Sites/magento2.lan/app/code/Magento/Eav/Setup/InstallSchema.php(217): Magento\Framework\DB\Adapter\Pdo\Mysql->createTable(Object(Magento\Framework\DB\Ddl\Table))
#8 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Model/Installer.php(761): Magento\Eav\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#9 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Model/Installer.php(695): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#10 [internal function]: Magento\Setup\Model\Installer->installSchema()
#11 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Model/Installer.php(298): call_user_func_array(Array, Array)
#12 /Users/Galina/Sites/magento2.lan/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#13 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#14 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#19 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#20 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#21 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /Users/Galina/Sites/magento2.lan/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /Users/Galina/Sites/magento2.lan/setup/index.php(31): Zend\Mvc\Application->run()
#24 {main}

================================================

I tried install with Sample data and without it. The same errors comes out.

My system:
Mac OS 10.7 Lion.

<code>
$ httpd -v </code>
Server version: Apache/2.2.26 (Unix)
Server built:   Dec 15 2013 18:33:29

<code>$ mysql -u root -p</code>
Server version: 5.6.2-m5 MySQL Community Server (GPL)

<code>$ php -v</code>
PHP 5.5.27 (cli) (built: Jul 10 2015 23:02:22) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

I use clean MySQL, PHP, Apache installed with this manual http://coolestguidesontheplanet.com/how-to-install-php-mysql-apache-on-os-x-10-6/ 

So, I have errors that seems to be because of low version of MySQL. But  I already updated MySQL and PHP to max possible for Mac OS 10.7 Lion.  

Firstly I was tried install Magento on MAMP 3.0.7 with php 5.6, mySql 5.6. But it caused the same errors with the same step (module). So, I decided repeat all  steps on cleared MySQL, PHP, Apache. However, this has no effect

What else I can do to recognize whats wrong with my installation of Magento?

**Comment by mazhalai** [comment]
@Galch24 thank you for reporting this issue. MAMP 3.0.7 has MySQL version of 5.5.38, according to the documentation [here](https://www.mamp.info/en/documentation/).   MAMP doesn't yet support MySQL 5.6. and Magento is not compatible with MySQL version 5.5. It is possible you have 2 instances of MySQL, one through MAMP and one on your Mac OS.

**Comment by Galch24** [comment]
Thank you for the answer. But I don't use MAMP.  I completely uninstalled MAMP and tried to use clean MySQL 5.6 (just from the box), PHP 5.5 and Apache 2.x. 

I figured out that my "Client API version"  is different from my version MySQL http://joxi.ru/52aQgDbi54zW20 
phpMyAdmin show MySQL 5.6 and Database client version: libmysql - mysqlnd 5.0.11-dev   
Maybe that's the reason of my bug with installation magento?  So, can you give me the hint where that libmysql can be updated? How can I find the path where that library placed?

**Comment by mazhalai** [comment]
Thank you for clarifying, but "Client API version" doesn't have to be same as MySQL. Can you verify the following:
- version of Magento, check `<your magento root folder>/composer.json` file
- your database is clean
- clean contents of `var` folder or run `bin/magento setup:uninstall` to clean up previous installations.
- are you still getting the same error as above or is it a different error?

**Comment by Galch24** [comment]
1) Magento version = 1.0.0-beta
2) My database is clean. Absolutely.
3)  /var folder is clean.   There is just on .htaccess file

Every time I tried to install Magento I started from begining with manual http://devdocs.magento.com/guides/v2.0/install-gde/install/prepare-install.html  

1. get clone
2. composer install
3. set the permissions
4. using Setup Wizard

And every time my database was clean. And /var folder was in initialize state just after cloning.

I think there is some system problem. Maybe it related with mac 10.7 Lion.   But I have no idea how to discover it. 
So question is How to diagnose this problem?

**Comment by Galch24** [comment]
And I repeat all this action one more time. I have the same errors with the same step and module.

**Comment by hostep** [comment]
@Galch24: have you tried searching for the error? Because when I search on it, the first result is this:
http://stackoverflow.com/a/17498167/145829

It says you need at least MySQL 5.6.5, and since you are using 5.6.2, it isn't working.

@mazhalai: maybe the documentation needs to be updated to mention MySQL should be at least version 5.6.5?

**Comment by xcomSteveJohnson** [comment]
Investigating; asked Products to make the call.

**Comment by sshrewz** [comment]
@Galch24 is this issue still pertinent for you for 2.0.0 or 2.0.1?

**Comment by sshrewz** [comment]
@Galch24, since we have not heard from you, we'll go ahead and close this issue.  In case you encounter any other issues, feel free to reopen.
