### ISSUE TITLE
Magento2 not syncing to ShipStation suddenly

### ISSUE THREAD

**Issue by melyancey** [magento/magento2#15518]
### Preconditions

1.  Magento 2.2.3 & ShipStation on web 
2. 

### Steps to reproduce

1.  ShipStation gave us an error log this morning as to why Magento store was not connecting and updating Ship Station

 05/25/2018 08:11 am myancey
    An error occurred attempting to update orders: <!doctype html> <html xmlns="http://www.w3.org/1999/xhtml" > <head> <title>There has been an error processing your request</title> <base href="https://www.americanflags.com:443/errors/default/" /> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <meta name="robots" content="*"/> <link rel="stylesheet" href="css/styles.css" type="text/css" /> <link rel="icon" href="images/favicon.ico" type="image/x-icon" / 
05/25/2018 08:10 am myancey
    An error occurred attempting to update orders: <!doctype html> <html xmlns="http://www.w3.org/1999/xhtml" > <head> <title>There has been an error processing your request</title> <base href="https://www.americanflags.com:443/errors/default/" /> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <meta name="robots" content="*"/> <link rel="stylesheet" href="css/styles.css" type="text/css" /> <link rel="icon" href="images/favicon.ico" type="image/x-icon" / 
05/25/2018 07:45 am Shipstation
    An error occurred attempting to update orders: <!doctype html> <html xmlns="http://www.w3.org/1999/xhtml" > <head> <title>There has been an error processing your request</title> <base href="https://www.americanflags.com:443/errors/default/" /> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <meta name="robots" content="*"/> <link rel="stylesheet" href="css/styles.css" type="text/css" /> <link rel="icon" href="images/favicon.ico" type="image/x-icon" / 
(I can only go so far in error log, so bottom is probably cut off)

### Expected result

1. magento store should sync with ShipStation and new orders should appear
2. not sure if any of our data will transfer back to magento is we ship in ShipStation, needs to be resolved ASAP

### Actual result

1. [Screenshot, logs]

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-15518-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-15518-2-2-4.engcom.dev.magento.com/admin](https://i-15518-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
Hi @melyancey could you please demonstrate this behavior on the test instance https://i-15518-2-2-4.engcom.dev.magento.com/admin  ?

**Comment by melyancey** [comment]
Hello,

 

I’m not sure what you mean by this. I can log into the instance you created but it doesn’t have any orders and isn’t connected to ShipStation. 

Besides a few hours ago it suddenly started working again.  Although on one of computers/logins the orders in question lost all items in them in Magento. But not on the other two people’s login

 

                

If you have any questions, please feel free to contact me. 

Thank you for contacting AmericanFlags.com!

 

Best regards,

Melanie Yancey

Customer Service Representative

AmericanFlags.com

"Because your flag is your heart unfurled!"

5008 Veterans Memorial Highway

Holbrook, NY 11741

 

p: 631-750-9471 ext. 12

f: 631-750-9472

**Comment by melyancey** [comment]
Magento2 and ShipStation suddenly started syncing again around 1130am EST.
