### ISSUE TITLE
Old Dev Docs URLs in Search Engine

### ISSUE THREAD

**Issue by astorm** [magento/magento2#1552]
Today I was searching for some Magento 2 information -- and Google returned a result with the following URL

http://devdocs.magento.com/guides/v1.0/config-guide/config/plugins.html

However, this URL returned a 404.  If the old versions of docs aren't going to stick around, there old URLs should redirect (`301`, permanent) to the current equivalent document, or an appropriate page if the old URLs are going away.

**Comment by astorm** [comment]
Derp, wrong repository.

**Comment by alankent** [comment]
I think this is a side effect of the site rebuild a day or so ago. Google has not updated its indexes with the changes yet, so search is bringing up the old pages. Hopefully Google will be updated soon.
