### ISSUE TITLE
Error on isntalling Magento v1.0.0-beta

### ISSUE THREAD

**Issue by vnagara** [magento/magento2#1553]
Magento 2 v1.0.0-beta from Wed Jul 15 18:38:43 2015 +0300.
After successful composer install. Got exception onindex.php in root directory:

exception 'ReflectionException' with message 'Class Magento\Framework\ObjectManager does not exist' in ..../magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:29.

Full list at: https://gist.github.com/vnagara/a881a2785cea76559959

**Comment by xcomSteveJohnson** [comment]
Try clearing directories under var, such as:

rm -rf var/cache/* var/generation/* var/page_cache/*

**Comment by vnagara** [comment]
@xcomSteveJohnson thx, seems it has solved, at least error disappeared. Full installation I will perform tomorrow and announce results.

**Comment by vnagara** [comment]
This bug has been resolved. And appeared another #1361 :(.
