### ISSUE TITLE
The product suddenly disappeared on the frontend. (We can not find products matching the selection. )

### ISSUE THREAD

**Issue by loibv5989** [magento/magento2#15530]
Dear magento team.

PHP 7.0.27-0 + deb9u1
Mysql Ver 14.14 Distrib 5.7.21-20
nginx version: nginx / 1.10.3
Magento version 2.2.2, 2.2.3

My site it regularly disappears product on the entrance. When I watch it say we can not find the product matching the selection.

I have to reset the index with: bin / magento indexer: reindex. Then the product is displayed.

I've lost quite a bit of time finding out about this on the way to forums like stackoverflow, magento.stackexchange.com but that does not work.

Is there any specific solution to this problem?. please help.

**Comment by loibv5989** [comment]
Can anybody help me fix it?

**Comment by magento-engcom-team** [comment]
Hi @denda888 
Unfortunately information in the report is insufficient to verify the issue. 
Please update the report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen the thicket.

Thanks
