### ISSUE TITLE
Implement a serious debug toolbar

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1554]
Having a good debugging tool it is fundamental for a good project development. Currently the best tool of all pph framework is definitely the debug toolbar Symfony2.
It would be nice to have a tool with similar functionality already built into Magento, would greatly simplify the work to each developer.

![screen shot 2012-04-13 at 4 39 20 pm](https://cloud.githubusercontent.com/assets/5001801/8872714/dc9a7320-31ff-11e5-8ff3-6ea6175eed0b.png)

**Comment by mzeis** [comment]
This would definitely by a good addition.

**Comment by Flyingmana** [comment]
I would vote for using the symfony (or zend, I think they have one, too) toolbar as base

**Comment by alankent** [comment]
Z-Ray has a Magento 1 toolbar and will probably have a Magento 2 toolbar too. I am wondering whether this is best done as an extension? What is reason for making part of core? Or a hackathon project? (Curious to hear different opinions.)

**Comment by mzeis** [comment]
If I remember correctly, you only get Z-Ray with Zend Server, right? That would rule it out for us pretty much.

In my opinion it should be part of the core to support integrators (dev toolbars can speed up development quite a bit because you don't have to insert debug code / trace for the same reasons again and again).

If there will not be a developer toolbar in the core, for sure there will be several implementations by the community again. I'd like to see a joined effort, be it inside or outside the core.

**Comment by CRYX2** [comment]
Drupal 8 has a module who integrate perfectly Symfony2 profiler (https://www.drupal.org/project/webprofiler). I do not think it's too expensive to incorporate in magento if we think of the enormous benefits that would bring.

**Comment by alankent** [comment]
An interesting question to me is whether "we" need to do a better job to coordinate larger community projects vs just wait for the core team to get to it. Peripheral projects like this feel more community friendly. How many community members would be be interested in helping this one? Is the job then more to work out a framework to help community members to collaborate? Eg define some best practices for teams to work together (working groups). To me this clearly should be a separate module so it's optional, but it makes sense having just one with lots of people contributing.

**Comment by wojtekn** [comment]
If you decide to include toolbar in core, maybe just build a base which provides foundation. Then extension developers could extend it and add new toolbar features. Core toolbar could include debug features which already exist in core (enabling/disabling profiler, hints, inline translation, displaying profiler output etc.) and more could be added by community.

**Comment by roman204** [comment]
Good idea @wojtekn, and are the core developers not also missing such a feature ? So many things in Magento2 are inspired by the community... but a "core" developer toolbar not :-(

**Comment by vpietri** [comment]
In order to discover Magento2 I've made a simple developer toolbar https://github.com/vpietri/magento2-developer-quickdevbar . Let me know how can I improve it.

**Comment by pboisvert** [comment]
@piotrekkaminski Piotr can you take this one for dev experience?

**Comment by piotrekkaminski** [comment]
This is not currently a priority since external projects exist that seems to be tackling this issue:
- https://github.com/vpietri/magento2-developer-quickdevbar
- http://store.pulsestorm.net/products/commerce-bug-3
