### ISSUE TITLE
GiftMessage - duplicate category

### ISSUE THREAD

**Issue by nja78** [magento/magento2#1555]
In core extension GiftMessage in view folder are 2 folders:
"Cart" and "cart". 
On windows machines is unable to clone/unpack project without loosing files.

https://github.com/magento/magento2/tree/develop/app/code/Magento/GiftMessage/view/frontend/templates

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-40737

**Comment by vpelipenko** [comment]
@nja78, issue is fixed and available in develop branch. Please, check it.

**Comment by nja78** [comment]
Thank you. Only one folder left.
