### ISSUE TITLE
COOKIES WERE IDENTIFIED WITHOUT SECURE OR HTTP ONLY FLAG SET

### ISSUE THREAD

**Issue by rajatkar104** [magento/magento2#15556]
In Magento 2, I have configured the required configuration related to the cookie but in some of the  URLs the cookie is not secure or HTTP only flag not set. Please find the URLs yourdomainname.com/sales/order/history the secure cookie is not set. 

Please look into this ASAP.

**Comment by magento-engcom-team** [comment]
@rajatkar104 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

We are closing this ticket now. Please reopen if you wish to update description.
