### ISSUE TITLE
Magento Iphone/Ipad- Product detail page not loading on click of product link or image 

### ISSUE THREAD

**Issue by Sachin-Suresh** [magento/magento2#15553]
### Preconditions

1. Using Magento 1.14 EE 
2. On click of product link/image, product detail page not working in Phone

### Steps to reproduce

1. For instance, if the user is on Home Page and clicks the product image (from any category section), then the page reloads, and user lands on Homepage

2. If user is on Product Listing page and then clicks on product name/image then also the page reloads and user lands on Product Listing page

After referring through some of the posts, i tried below ways to solve this:

1) "check .htaccess" file for "Rewrite Base" option, it should be either commented out or it should have the relative path if your site is inside subfolders"

Not sure which option to check for, below is the partial code of my htaccess file from the root folder.

   ```
 ############################################
    ## make HTTPS env vars available for CGI mode

    SSLOptions StdEnvVars

   </IfModule>

   <IfModule mod_rewrite.c>

   ############################################
   ## enable rewrites

    Options +FollowSymLinks
    RewriteEngine on

    ############################################
## you can put here your magento root folder
## path relative to web root

    #RewriteBase /magento/

############################################


############################################
## redirect for mobile user agents

#RewriteCond %{REQUEST_URI} !^/mobiledirectoryhere/.*$
#RewriteCond %{HTTP_USER_AGENT} "android|blackberry|ipad|iphone|ipod|iemobile|opera mobile|palmos|webos|googlebot-mobile" [NC]
#RewriteRule ^(.*)$ /mobiledirectoryhere/ [L,R=302]
############################################
```

2) Cleared All indexes and cache. And full permission for var folder.

3) Where else could i have missed anything

Im trying on this for 2 days, anybody can suggest on this?

**Comment by magento-engcom-team** [comment]
Hi @Sachin-Suresh 
Unfortunately, this github issue tracker is only related to Magento 2.
Closing, since issue described for magento 1.
