### ISSUE TITLE
Cannot save the customer

### ISSUE THREAD

**Issue by AnnaGashenko** [magento/magento2#15550]
I try to registration on https://u.magento.com/
Fill out the registration form and get error "Cannot save the customer"
And I got in console 
[DOM] Found 2 elements with non-unique id #cn35249_00: (More info: https://goo.gl/9p2vKq)

![magento](https://user-images.githubusercontent.com/17450710/40599739-5c6b7394-6257-11e8-89d8-7b9820cb02ec.jpg)

**Comment by magento-engcom-team** [comment]
Hi @AnnaGashenko 
Unfortunately the github issue tracker is only intended for Magento 2 technical issues. We can not provide any guidance here for other Magento resources.

Thanks
