### ISSUE TITLE
Configurable product price (tax) not applying as per tax class of simple (child) product

### ISSUE THREAD

**Issue by sandipansaha** [magento/magento2#15567]
### Preconditions

1. Magento Community 2.2.2
2. PHP 7.0.30
3. MySql 5.7.22
4. Apache2

### Steps to reproduce

1. Create a configurable product, which has two simple (child) products.
2. Configurable product is set as taxable with 20% tax setup.
3. First simple product is set as taxable with 20% tax setup.
4. Second simple product is set as no tax i.e. 0% tax.
5. Add second product through configurable options to cart.

### Expected result

1. 0% tax should be applied for the second simple product.

### Actual result

1. Tax of 20% is being applied in cart for the second simple product.

**Comment by sandipansaha** [comment]
For the time being who is having this issue and looking for a workaround I have built a module to change the Magento behaviour according to our requirement.

You can check the answer below -

https://magento.stackexchange.com/questions/228276/how-can-i-allow-a-configurable-product-price-tax-to-apply-as-per-tax-class-of/228277#228277

**Comment by magento-engcom-team** [comment]
Hi @sandipansaha 
This looks like a correct Magento behavior. 
We are closing this report now, as you have been able to find a workaround.

Thanks

**Comment by tomekjordan** [comment]
@magento-engcom-team this is not correct behavior. 
Tax rate should be taken from child product.
OR the best way
Store admin should have option on main product:
- use main product tax rate
- inherit tax rate from child product
