### ISSUE TITLE
Getting error when edit the configurable product on Magento 2.2.4 after migration

### ISSUE THREAD

**Issue by srinivasnovamodule** [magento/magento2#15569]
Hi There,

Last week we have migrated the data from Magento 1 (Version 1.9.3.0) to Magento 2.2.4. After completion of migration all configurable products edit section is getting an error as below.

**1 exception(s):
Exception #0 (Exception): Warning: Illegal offset type in isset or empty in /var/www/vhosts/mysite.com/vendor/magento/module-ui/Config/Reader/Definition/Data.php on line 126

Exception #0 (Exception): Warning: Illegal offset type in isset or empty in /var/www/vhosts/mysite.com/vendor/magento/module-ui/Config/Reader/Definition/Data.php on line 126
#0 /var/www/vhosts/mysite.com/vendor/magento/module-ui/Config/Reader/Definition/Data.php(126): Magento\Framework\App\ErrorHandler->handler(2, 'Illegal offset ...', '/var/www/vhosts...', 126, Array)
#1 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Element/UiComponentFactory.php(390): Magento\Ui\Config\Reader\Definition\Data->get(Array)
#2 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Element/UiComponentFactory.php(404): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#3 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Element/UiComponentFactory.php(313): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#4 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Element/UiComponentFactory.php(216): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#5 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout/Generator/UiComponent.php(135): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#6 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout/Generator/UiComponent.php(97): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#7 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#9 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout->generateElements()
#10 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#13 /var/www/vhosts/mysite.com/vendor/magento/framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#14 /var/www/vhosts/mysite.com/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout->getBlock('menu')
#15 /var/www/vhosts/mysite.com/vendor/magento/module-catalog/Controller/Adminhtml/Product/Edit.php(69): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#16 /var/www/vhosts/mysite.com/vendor/magento/framework/App/Action/Action.php(107): Magento\Catalog\Controller\Adminhtml\Product\Edit->execute()
#17 /var/www/vhosts/mysite.com/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/vhosts/mysite.com/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/vhosts/mysite.com/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callParent('dispatch', Array)
#20 /var/www/vhosts/mysite.com/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/www/vhosts/mysite.com/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/www/vhosts/mysite.com/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/vhosts/mysite.com/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(26): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callPlugins('dispatch', Array, NULL)
#24 /var/www/vhosts/mysite.com/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/vhosts/mysite.com/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/vhosts/mysite.com/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#27 /var/www/vhosts/mysite.com/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/vhosts/mysite.com/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /var/www/vhosts/mysite.com/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/vhosts/mysite.com/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#31 /var/www/vhosts/mysite.com/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))**

### Preconditions
Magento 2 version: 2.2.4
PHP version: 7.1.17
Mysql: Maria DB 10
Apache

### Expected result
We should able to edit configurable product after the migration but getting error instead. But it is working with simple products.

### Actual result
![screenshot_3](https://user-images.githubusercontent.com/34563507/40657870-f7703ee6-6366-11e8-8168-34f348463e52.png)

Colud you please help on this as I am trying to fix this issue since last week but not yet fixed?
Please advice or suggest on this issue.

Thanks

**Comment by srinivasnovamodule** [comment]
Hey @magento-engcom-team please have a look into this issue and advice or suggest as we have golive plan.

Thanks

**Comment by EliasKotlyar** [comment]
There is some issue in one of your config files(xml-files). You should debug this down and find it out. I suppose thats a 3rd party module.

**Comment by ravikasarla** [comment]
Hi @EliasKotlyar thanks for the update.

I have disabled all the 3rd party modules and tested. Still getting the issue. Any other solutions?

Thanks

**Comment by srinivasnovamodule** [comment]
Hi @EliasKotlyar thanks for the update.

I have disabled all the 3rd party modules and tested. Still getting the issue. Any other solutions?

Thanks

**Comment by EliasKotlyar** [comment]
Then you have to debug it. I see no other solution for that.

**Comment by srinivasnovamodule** [comment]
Hi @magento-engcom-team, can you please look into this and advice asap. We have go-live plan, please suggest.

**Comment by srinivasnovamodule** [comment]
Hi,

Please, anyone, help on this issue as I am unable to fix this issue since last week. Please, someone help on this.

Thanks

**Comment by bendesignsweb** [comment]
@srinivasnovamodule  have you tried creating a new configurable product from the Magento admin panel and seeing if it's editable? If it allows you to create a new one and edit it, it would suggest some problem with the data migration. You'd then be able to compare your new accessible product against your migrated products in MySQL and look for any odd looking data.

**Comment by srinivasnovamodule** [comment]
@bendesignsweb Thanks for replying on this.

I have tried to create a new configurable product and it is giving the same error. I am not able to create new conf prod also. Please, advice or suggestion.

![screenshot_6](https://user-images.githubusercontent.com/34563507/40782642-9a3623ba-64fd-11e8-95c7-d44c24735740.png)

Thanks

**Comment by bendesignsweb** [comment]
@srinivasnovamodule Unfortunately I'm no expert, I can replicate the error by passing an Array to the get function in data.php I've also tried dumping the value of the key when editing a configurable product and it's always a string so not sure why your particular install is passing an array. You should try some debugging, I don't think there's a lot more I can say without seeing the install. - Sorry!

**Comment by magento-engcom-team** [comment]
@srinivasnovamodule Unfortunately we can not provide any assistance with migration related issues here. Please report to magento/data-migration-tool repository instead.

Thank you.

**Comment by hayatbiralem** [comment]
Hi guys,

I had the same problem and I just fixed by deleting some sequence definitions in my own custom extensions' module.xml

It seems we should pay more attention to that sequence/dependency definitions.
