### ISSUE TITLE
Error 503: Service Unavailable

### ISSUE THREAD

**Issue by CoreyCole** [magento/magento2#1557]
My Magento store was working fine yesterday, but when I logged in today I'm only getting a page reading:

>Service Temporarily Unavailable
>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Same page for the admin panel.

As I read in this [stackoverflow post](http://stackoverflow.com/questions/8102777/service-temporarily-unavailable-magento) the issue used to be solved by deleting a **maintenance.flag** file and possibly also deleting the cache and session folders, but I can't find a **maintenance.flag** file and deleting the *var/cache* folder didn't solve the issue.

I'm running the webstore on a virtualbox ubuntu apache2 server.

Any help would be greatly appreciated.

**Comment by mazhalai** [comment]
@CoreyCole Thank you for reporting this issue, however the flag file is `.maintenance.flag` not `maintenance.flag`, note the extra dot at the beginning. Alternatively you can disable maintenance mode with CLI `bin/magento maintenance:disable`

**Comment by CoreyCole** [comment]
Thanks! I found the file it was in <code>var/</code> not docroot like it used to be. Deleting it did the trick.

**Comment by Jeffery718** [comment]
I can't find the maintenance.flag file by my windows platform.

**Comment by mazhalai** [comment]
@Jeffery-Li Please open a new issue and refrain from commenting on closed issues. Re maintenance.flag, it has a `.` in the beginning, and perhaps it is hidden by default in windows?

**Comment by magenx** [comment]
it is hidden by default on every system, even with ftp client users can not see it.
i think you have to use normal file.

**Comment by nomuprive** [comment]
Hi. I'm having the same kind of problem but, my error message is a little different. I'm not sure is it's a file permission problem. Below is the error message:

"There has been an error processing your request
Unable to retrieve deployment version of static files from the file system."
