### ISSUE TITLE
4 out of 6 recent orders didn't go through, frontend checkout just "spins"

### ISSUE THREAD

**Issue by melyancey** [magento/magento2#15582]
### Preconditions

1. Magento 2.2.4
2. Firefox for frontend, firefox and Chrome for backend

### Steps to reproduce

1. filled out order checkout on front end
2. get to part where it says "place order", click it and the busy circle comes up and spins and spins and it never gives an order number
3. but it's intermittent, now 6 out of 8 recent orders

### Expected result

1. the confirmation page that gives you your order number should appear

### Actual result

1. nothing, the page ghosts out and the busy circle spins

**Comment by melyancey** [comment]
we see that PayPal is attempting to charge them because we have $0.00 transactions for them, which is why we know that they didn't go though to Magento properly

**Comment by melyancey** [comment]
upon further testing, we know that one of the orders that didn't go through was because the credit card was declined, but 1) there was no error message shown on screen and 2) it still just spinning on a ghosted check out page, it is hanging up our computer

**Comment by magento-engcom-team** [comment]
@melyancey This looks like related to https://github.com/magento/magento2/issues/15586
Closing in favor of the other ticket.
