### ISSUE TITLE
Magento Admin Side of Site extremely slow, customer side also slow

### ISSUE THREAD

**Issue by melyancey** [magento/magento2#15581]
### Preconditions

1. Magento v 2.2.4
2. Chrome and Firefox are both being used to access both the backend and the frontend

### Steps to reproduce

1. we say reload the page and it takes over 7 minutes every time
2. 
3. 

### Expected result

1. it should reload

### Actual result

1. [Screenshots, logs or description]

**Comment by DanielRuf** [comment]
Did you enable the production mode and run the deploy command for the static content?

**Comment by melyancey** [comment]
I'm not sure, I 'm checking with other on staff

**Comment by melyancey** [comment]
No, I'm sorry.  We do not know how to do that.  Can you explain please?

**Comment by DanielRuf** [comment]
See the following links

https://devdocs.magento.com/guides/v2.2/howdoi/install/mode-switch.html
https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-mode.html
https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.html
https://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_deploy.html

https://magento.stackexchange.com is better for general questions.

**Comment by melyancey** [comment]
thank you,  I have forwarded this info to our developer

**Comment by magento-engcom-team** [comment]
@melyancey Closing this ticket per your comment above.
