### ISSUE TITLE
for 1 of our admins, the products sold no longer show in the order in Magento - for other 2 admins, they see them

### ISSUE THREAD

**Issue by melyancey** [magento/magento2#15587]
### Preconditions

1. Magento 2.2.4
2. Firefox and Chrome

### Steps to reproduce

1. we have not changed user roles
2. we have not changed users
3. but one of our admins no longer sees products sold in the order in magento, just the total.  
4. the invoice has the products for her, but not the order
5.  for our other 2 admins, nothing changed and we can see products in the order

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by ghost** [comment]
@melyancey, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
