### ISSUE TITLE
Mass action dropdowns in new UI grids (Sales, Products, etc.) don't support scrolling

### ISSUE THREAD

**Issue by ikk0** [magento/magento2#1558]
Version: 1.0.0-beta

We need to add a lot actions to the Sales > Orders actions dropdown. However, it doesn't limit the number of actions shown at the same time, but the dropdown just gets longer and longer. I would highly suggest to add scrolling support - as many developers will add mass actions there. Example: 

![image](https://cloud.githubusercontent.com/assets/5671344/8876647/3f6ca4f2-3221-11e5-896f-6147e51cecbf.png)

**Comment by godban** [comment]
Hello @ikk0, 

Good catch, thank you for reporting this issue. Will fix that asap. Internal ticket MAGETWO-40738

**Comment by ikk0** [comment]
@godban: You guys rock! Having M2 on Github with direct developer contact is such a HUGE improvement compared to the M1 days.. :)

**Comment by vpelipenko** [comment]
@ikk0, issue is fixed and already available in develop branch. Please, check the fix and let us know your opinion.

**Comment by ikk0** [comment]
Just tested it, looks good. Thank you!
