### ISSUE TITLE
Magento 2.2.4 Demo Product Display Disclaimer Doesn't Disappear After Configuration for Live Production

### ISSUE THREAD

**Issue by Olive777** [magento/magento2#15589]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @Olive777 
Unfortunately we can not provide any assistance with issue reports not following guidelines.
If you wish to proceed – please update description with clear information and reopen.

Thank you
