### ISSUE TITLE
Incorrect currency code in Orders grid

### ISSUE THREAD

**Issue by etcik1** [magento/magento2#15599]
### Preconditions
1. Magento 2.2
2. Having two websites with two store views (e.g website1 with stores store1 and store2 and website2 with stores store3 and store4)
3. Currencies are configured on website level

### Steps to reproduce

1. Order products in store1 with currency A
2. Order products in store4 with currency B
3. Open orders Grid in Admin

### Expected result
1. Correct Currency code in Grand Total (base) and Grand Total (Purchased)

### Actual result

1. Currency code A (default), Totals themselves have correct numeric value

**Comment by therouv** [comment]
Hi @etcik1 thank your for raising this issue. I tried to reproduce this issue but it seems to be no bug but a configuration error on your store.

In the system configuration in the currency setup group you can specify a "base currency" for the website. If you forget to change this setting on website level to currency B as well, then Magento will always use the base currency for display in the Magento backend.

Attached you'll see two screenshots of my configuration where your described issue does not appear.

![website1](https://user-images.githubusercontent.com/393419/41499816-587238f6-7187-11e8-9f65-c7a34a9cc6d8.jpg)

![website2](https://user-images.githubusercontent.com/393419/41499815-585169fa-7187-11e8-8d65-1d681ba559be.jpg)

**Comment by therouv** [comment]
#mhlej18

**Comment by etcik1** [comment]
Hello @therouv 

Here is screencast of our configurations and outcome: https://monosnap.com/file/jutJLdnwj65p6Di93tGYnDEviMm3XK

As You can see, Currency code in orders grid is AED, in both cases.

**Comment by vishal13061993** [comment]
Facing same issue.
Please check the following screenshots:
For KSA: https://prnt.sc/u9no4r
For UAE: https://prnt.sc/u9nn8x

Now orders grid for KSA orders: https://prnt.sc/u9nlkm
@magento-engcom-team please reopen this issue
