### ISSUE TITLE
Products > Catalog "Change status" mass action is broken

### ISSUE THREAD

**Issue by ikk0** [magento/magento2#1559]
Version: 1.0.0-beta

Selecting it will simply redirect you to the grid again, showing the error message "Bad value was supplied".

Expected behavior: A second dropdown should be shown with the status to change the product to.

**Comment by ikk0** [comment]
Did you assign an internal ticket to this? Just want to make sure it's not missed. IMHO this is an important bug, as right now there is no ability to add "additional" sub-dropdowns (like "Enabled" or "Disabled", in M1, that shows up if you select "Change Status") for massactions using the new UI grids, and this seems to be the problem on the "Catalog" grid here as well. Sorry for following up.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-41377

**Comment by vladimir-k** [comment]
@ikk0, internal ticket is fixed and already available in develop branch. Please, check the fix, and if something doesn't work for you, feel free to reopen this issue. Thank you for collaboration!
