### ISSUE TITLE
Problem with registerProductsSale() on checkout

### ISSUE THREAD

**Issue by milenishte** [magento/magento2#15597]
### Preconditions

1. Magento CE 2.2.4 
2. PHP >= 7.0 with error_reporting(E_ALL)
2. Having products with inventory

### Steps to reproduce

1. Order products with inventory
2. Enter shipping and billing information
3. Place order 

### Expected result
1. Successful order

### Actual result
1. A Javascript error is trown to the browser:
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 3772 of the JSON data[Learn More]
error-processor.js:28:25

2. because the POST request to /rest/default/V1/carts/mine/payment-information throws the following exception:
"An error occurred on the server. Please try to place the order again."
...
<b>Fatal error</b>:  Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3866 in /var/www/public_html/vendor/magento/framework/App/ErrorHandler.php:61

3. because of this exception (shown in var/log/exception.log)
main.CRITICAL: Notice: Undefined index: product_id in /var/www/public_html/vendor/magento/module-catalog-inventory/Model/StockManagement.php on line 103

The function registerProductsSale()  calls lockProductsStock(), defined in vendor/magento/module-catalog-inventory/Model/ResourceModel/Stock.php

It expect $lockedItems elements to contain the items type_id, product_id and qty, but lockProductsStock returns only type_id.

It seems that if the notices are disabled, the order will be placed, but the inventory of the items won't be reduced accordingly.

**Comment by QueenLinux** [comment]
I'm also currently having this issue, except for the first step. My error starts with a bad POST request, the rest is the same.
![screen shot 2018-06-05 at 11 26 06 am](https://user-images.githubusercontent.com/18219280/40989437-62bc38e8-68b3-11e8-92b7-19835c478ef8.png)
![screen shot 2018-06-05 at 11 26 21 am](https://user-images.githubusercontent.com/18219280/40989438-62cfc688-68b3-11e8-9622-92e07582ec9f.png)

**Comment by semajeg** [comment]
@milenishte How did you create your products? I'm facing the same issue with 2.2.4 but have pinned the cause down to bad product data in the cataloginventory_stock_item table.

In the cataloginventory_stock_item table. The "website_id" column is set to "1" for products that cannot be ordered and face the issue. Changing it to 0 fixes the issue.

Also if you create a product manually through admin, then inspect the cataloginventory_stock_item table, you'll see that the new product has the website_id of 0 and can be ordered without issue.

In my case I'm talking to a 3rd party to get them to fix their module to import the data correctly.

(see also #15868)

**Comment by ghost** [comment]
@milenishte, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
