### ISSUE TITLE
Deleting product custom option from quote gives error in product page

### ISSUE THREAD

**Issue by shakthivelp** [magento/magento2#15593]
Deleting product custom option from quote gives error in product page. It Looks like that it may be fixed in issue(Quote breaks if custom option deleted #6627).

But i need to know what are those files. I am using magento 2.1.7 i need that fix for my magento.

Preconditions

    Magento CE 2.1.*
    A product with a custom option

Steps to reproduce

    Add the product to the cart,  with a value for the custom option
    remove the custom option programatically or directly from table(quote_item_option)
    It give error in product detail page

Expected result

    The customers quote is updated with the options removed from the quote item and the customer can continue as normal

Actual result

    An error is thrown (Fatal error: Uncaught Error: Call to a member function getValue() on null in /var/www/html/joineryt_nover/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php on line 811)

**Comment by ghost** [comment]
Hi @shakthivelp the fix for this issue has already fixed  in 2.2-develop branch.
