### ISSUE TITLE
Cannot reinstall on same server, gets stuck at 70%

### ISSUE THREAD

**Issue by Schoeny1** [magento/magento2#1560]
I had a successfull install through the web and site was fine.  I had to change the URL of the site and ran into some trouble so I decided to do a fresh install again.  Here were my steps:
1) Deleted Magento root folder
2) Deleted Database
3) Setup new blank Database
4) Cloned the magento repository again 
5) Ran composer install
6) Began web install

Right at the beginning of the install I see the message saying "Installation incomplete check console log for details."  Within a second however the install resumes automatically and gets to 70% at Module 'Magento_Catalog':
Installing data.. 

And it never completes.

Any ideas?

**Comment by alankent** [comment]
Did it fail with an error? The installer pauses at 70% then even longer at 98%. https://alankent.wordpress.com/2015/07/16/the-dreaded-70-and-98-magento-2-install-pauses-quick-note/ - someone said it took them an hour to load. Probably depends on hardware and config settings

**Comment by Schoeny1** [comment]
Interesting article.  I will try again today and will keep an eye on the progress dots.

**Comment by Schoeny1** [comment]
I tried a few times in a browser and the progress dots never changed, it was always two.  so I tried installing through the command line and it worked just fine.

**Comment by alankent** [comment]
Interesting. If possible, can you work out if there is a different php.ini file being loaded when you use the command line vs when you use the web installer. If so, are there different settings in the two files? I am mainly thinking of memory limits. The underlying code is the same - so curious what is making it behave differently.

**Comment by okiii** [comment]
@alankent yes PHP uses different settings when using CLI. To avoid memory limits and execution timeout use the -d flag:
````
php -d memory_limit=-1 -d max_execution_time=-1 ./bin/magento setup:install <YOUR SETTINGS>
````

**Comment by alankent** [comment]
Are they the only differences - the command line? Any other php.ini setting differences?  Or do you think its just because you set the expiry time longer?  The fact that you got it to work one way and fail the other gives me hope we can spot a setting which is causing a problem. Maybe we need to change a php.ini setting for the web installer to work well with sample data.

**Comment by okiii** [comment]
It's definitely something to do with the Magento 2 setup app because setting the memory limit and max execution time via the cgi settings still cause the installer to fail.

**Comment by Schoeny1** [comment]
I agree with okii, it is something with the Magento 2 setup via the browser.  It seems to crash at that point with no errors being shown.  The odd thing is that the first time I installed it on this server it ran fine.  I was thinking that it had to do with something being cached somewhere.  I was even thinking maybe composer cached something locally from the first install and that reinstalling composer might clear that out somehow.  I didn't go that deep into debugging it though since I was able to install via command line.

**Comment by amitvig22** [comment]
I have the same problem, i am running the web install and it just gets stuck at 70%. Do we have a solution yet?

**Comment by Schoeny1** [comment]
Amit, did you try the command line install yet?  I also had a PHP memory limit error while adding the sample data after the install through command line.  I wonder if that is what was causing the web install to fail.

**Comment by amitvig22** [comment]
I am trying the command line install as we speak

**Comment by ark99** [comment]
@Schoeny1  @okiii  @amitvig22 or anyone else facing this "hung web install" issue...Can you please share more information on the system, configuration and environment? 

1. System configuration(cpus, ram, disk space etc )
2. OS version
3. Memory
4. MySQL version
5. phpinfo() output
6. The web browser you used and its version?
7. apache version
8. apache config file - httpd.conf
9. The console log in this instance is not providing more details. But can you share your apache log? I wonder if it has any useful information in regards to this issue.
10. Next time if you are trying web install, if you can monitor the system cpu/memory usage through "top" command.

**Comment by ArniXXX** [comment]
You need in php.ini file check mysql.connect_timeout = -1

**Comment by piotrekkaminski** [comment]
Please reopen if you still have this issue.
