### ISSUE TITLE
add to cart be pending

### ISSUE THREAD

**Issue by nvtho** [magento/magento2#15618]
I had add to cart but it not update mini cart, i see button only "pending"
Who can help me?
Thanks!

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @nvtho 
Unfortunately it is barely possible to help without all of the required information like Preconditions, Steps to Reproduce, Expected and Actual result.
We are closing this ticket now. Please reopen when all all information is in place.
Thank you
