### ISSUE TITLE
Can't install on step 6 Magento 2.2.4

### ISSUE THREAD

**Issue by PiedPip3r** [magento/magento2#15613]
Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

![untitled](https://user-images.githubusercontent.com/39789184/40764729-fa16b172-645e-11e8-8994-15bccc9b015d.png)

**Comment by magento-engcom-team** [comment]
Hi @PiedPip3r 
Unfortunately this report does not contain enough information to reproduce the issue. Please see devdocs section on Web installation on devdocs: https://devdocs.magento.com/guides/v2.2/install-gde/install/web/install-web_6-install.html
Please format issue according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen. 
Thanks.
