### ISSUE TITLE
Advanced Catalog Search for Price

### ISSUE THREAD

**Issue by kamal9484** [magento/magento2#15617]
**Description**
Advanced catalog search is  not working correct for product price filter. For Ex: Let i have a configurable product, having 2 children one has price 100$ and second has price 300$. then set filter range from 200$ to 400$, the result showing is 0. but according to the rule result should be 1.

**Preconditions**
Php 7.0, Magento 2.2.x

**Steps to reproduce**
1. Open Advanced Search result page
2. Apply filter for price range

**Expected Result**
According to the description result should be one product.

**Actual Result**
Showing 0 result

![price of children in admin](https://user-images.githubusercontent.com/38132077/40765720-0332a506-64cb-11e8-977d-efdf91ccbf4d.png)
![result](https://user-images.githubusercontent.com/38132077/40765722-03833688-64cb-11e8-8bde-68cdbe968107.png)

**Comment by ghost** [comment]
Hi @kamal9484  thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
