### ISSUE TITLE
Magento 2.2.4 Atribute html tags broke only show plain text

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#15612]
### Preconditions
Magento 2.2.4 Fresh installation and upgrade from 2.2.3

### Steps to reproduce
I wrote this problem here but no answers. Link: https://github.com/magento/magento2/issues/15393

And I found. For Magento 2.2.4 there are many diffrent structure on "Vendor -> Magento Catalog" for Product section. Many files add and diffrent from 2.2.3 and below.

### Expected result
On Magento 2.2.3 and below, for attribute with html tags working properly. And look nice. Screenshot below.

![atribut-error-04](https://user-images.githubusercontent.com/5201127/40760408-e347c8de-64c0-11e8-85d2-3909a6beb010.jpg)

### Actual result
On Magento 2.2.4 Attribute product become a plain text without HTML tags even it set to YES on admin backend menu. 
After I search in Magento 2.2.4 files, there are many different with add more files. I only know there are Breadcumb facility add more specific. I dont know what else add.

Here screenshot for error using Magento Luma.
![atribut-error-05](https://user-images.githubusercontent.com/5201127/40760547-78139d58-64c1-11e8-9ced-a250ea0dc70b.jpg)

And here additional files for Magento 2.2.4 that doesn't exist in Magento 2.2.3 and below. This is I only know. There are 1 files add in Product View. And add 1 folder in Module-catalog for named "ViewModel" Product with 1 file in it.

![atribut-error-01](https://user-images.githubusercontent.com/5201127/40760594-a5dfd18e-64c1-11e8-8c25-f3cc6dc5eac2.jpg)

![atribut-error-02](https://user-images.githubusercontent.com/5201127/40760600-ab6ab4e8-64c1-11e8-8c53-f436dd5e3d85.jpg)

![atribut-error-03](https://user-images.githubusercontent.com/5201127/40760606-b09ae3ca-64c1-11e8-968b-5f3d611520f2.jpg)

I wish there is any solution for this attribute with HTML tags error.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @jurpro 
Please avoid creating duplicate issues as it only creates clutter in a backlog, not speeding up the process.

We are now closing this in favor of #15393
