### ISSUE TITLE
Reindex when used_in_grid column in true for custom attribute for customer

### ISSUE THREAD

**Issue by vasudevsundar** [magento/magento2#15622]
@magento-engcom-team 

Preconditions
Magento version 2.2.3
Mysql 57
PHP 7.0

Steps to reproduce
See file:
lib/internal/Magento/Framework/Indexer/Handler/AttributeHandler.php
Your file has bug at line:
$source->addAttributeToSelect($fieldInfo['origin'], 'left');
Method addAttributeToSelect not found.

Need to display custom attribute in customer grid.

If i use used_in_grid = true gretting error. but it works fine in old version (Magento2.1.x)

**Comment by magento-engcom-team** [comment]
Hi @vasudevsundar 
Unfortunately the information provided is insufficient to verify the issue. 
Please format report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen.
