### ISSUE TITLE
Quote REST API reserved_order_id is 0 if prefix set - quoteCartRepositoryV1

### ISSUE THREAD

**Issue by bendesignsweb** [magento/magento2#15625]
Hello, 

When using the REST api **/rest/all/V1/carts/search** if you have a prefix set then the **reserved_order_id** returns 0 as it's returning an integer when it should be a string. If you don't have a prefix set then reserved_order_id is filled out correctly with the order number.

### Preconditions
1. Magento 2.2.2
2. PHP 7.0.21
3. Set an order prefix in the database - I used a guide by Classy Llama 
`UPDATE `sales_sequence_profile` SET `prefix` = 'CL-' WHERE `meta_id` = 5;`

### Steps to reproduce
1. Set the prefix up.
2. Place an order and confirm prefix is applied.
3. Call api /rest/all/V1/carts/search - I used search criteria of: searchCriteria[filter_groups][0][filters][0][field]=reserved_order_id&searchCriteria[filter_groups][0][filters][0][condition_type]=notnull
4. Dump response.

### Expected result
1. reserved_order_id should have the order number including prefix in it.

### Actual result
1. reserved_order_id is int 0

**Comment by ghost** [comment]
Hi @bendesignsweb thank you for you report, the fix for this issue has already in 2.2-develop and 2.3-develop branch
