### ISSUE TITLE
Attribute Options can't get reloaded, after adding new option

### ISSUE THREAD

**Issue by SRaromicon** [magento/magento2#15630]
### Preconditions
1. PHP 7.1
2. Magento 2.2.4

### Steps to reproduce
1. Create a Script for adding new options on Select Attributes.
```php
    protected function getSelectAttributeValue($value, $attribute)
    {
        $value = trim($value);

        if ($value == '') {
            return null;
        }
        $optionId = $attribute->getSource()->getOptionId($value);

        if ($optionId) {
            return $optionId;
        }

        $option = [
            'attribute_id' => $attribute->getId(),
            'values' => [0 => trim($value)]
        ];
        /** @var $this->eavSetup Magento\Eav\Setup\EavSetup */
        $this->eavSetup->addAttributeOption($option);
        return $attribute->getSource()->getOptionId($value);
    }
```
2. Try to get option id for newly added value
3. Try to load Attribute. Jump to step Number 2.

### Expected result

1. $attribute->getSource()->getOptionId() should return new value
or
2. All Options for Attribute can be reloaded by some function.

### Actual result

1. It's not possible to get the newly added Option Id / value from Database. I have also tried to reload the attribute with different functions (load, loadByCode, get from Repository). The new Option is not included in getAllOptions().

In my opinion getAllOptions() from Magento\Eav\Model\Entity\Attribute\Source\Table should get a third parameter called $reload, to reload the options, when needed. So you just had to add a line like: ```$attribute->getSource()->getAllOptions(null,null,true)``` to reload the options manually.

**Comment by engcom-backlog-nickolas** [comment]
Hello @SRaromicon, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by umarusaf902** [comment]
In order to get all the options including the last added follow below code. In my case I needed to change the sort order of the options in ascending.

> public function updateOptions($formattedCode)
>     {
>         try {
>             /**
>              * Magento\Catalog\Model\ResourceModel\Eav\AttributeFactory $attribute
>              */
>             $attribute = $this->eavAttributeFactory->create();
>             $attribute = $attribute->loadByCode(\Magento\Catalog\Model\Product::ENTITY, $formattedCode);
>             $options = $attribute->getOptions();
>             $labels = [];
>             foreach ($options as $index => $option) {
>                 if (!empty($option->getValue())) {
>                     $labels[$option->getValue()] = $option->getLabel();
>                 } else {
>                     unset($options[$index]);
>                 }
>             }
>             asort($labels);
>             foreach ($options as &$option) {
>                 $sortOrder = array_search($option->getValue(), array_keys($labels));
>                 $option->setSortOrder($sortOrder);
>             }
>             $attribute->setOptions($options);
>             $this->productAttributeRepository->save($attribute);
>         } catch (\Exception $e) {
>             $this->logger->debug($e->getMessage());
>         }
>     }
