### ISSUE TITLE
(Home Page and index.php )  using both the www & non-www domain variations

### ISSUE THREAD

**Issue by ghost** [magento/magento2#15639]
### Preconditions

1. originally Bitnami Magento 2.2.3-3 AFTER upgrade to 2.2.4
2. 

### Steps to reproduce

1. site is configured to run as www
2. 
3. 

### Expected result
all pages to show www
1. [Screenshots, logs or description]

### Actual result
Website (Home Page only) is indexed in Google using both the www & non-www domain variations
https://example.com AND https://www.example.com/home 
1. [Screenshots, logs or description]

**Comment by DanielRuf** [comment]
How did you configure it? With .htaccess and 301 redirects?

**Comment by ghost** [comment]
sudo /opt/bitnami/apps/magento/bnconfig --machine_hostname www.example.com

**Comment by DanielRuf** [comment]
We do not know what this does. I guess this creates a .htaccess? If so please share the mod_rewrite and vhost settings with us.

Normally you should set the right domain / url in the store settings.

**Comment by ghost** [comment]
![untitled](https://user-images.githubusercontent.com/33468278/40869313-2bc4b710-665c-11e8-86de-d44166caea55.png)
<details>

**Comment by ghost** [comment]
# httpd-app.conf
 "unix:/opt/bitnami/php/var/run/magento.sock|fcgi://magento-fpm" timeout=300> <Directory "/opt/bitnami/apps/magento/htdocs"> Options -MultiViews AllowOverride None Order allow,deny Allow from all = 2.3> Require all granted SetHandler "proxy:fcgi://magento-fpm" ModPagespeedDisallow "*" Include "/opt/bitnami/apps/magento/conf/banner.conf" Include "/opt/bitnami/apps/magento/conf/htaccess.conf"

**Comment by DanielRuf** [comment]
Please use code blocks (```) for better readability.

**Comment by ghost** [comment]
I apologize for the inconvenience caused

**Comment by DanielRuf** [comment]
Can you edit your comments to use the HTML5 details tag?

**Comment by ghost** [comment]
pardon my ignorance, not a programmer and legally blonde

**Comment by DanielRuf** [comment]
Unfortunately the files seem to be on one line. Can you replace the parts with the multiline versions?

**Comment by DanielRuf** [comment]
Or I invest some (more) time to try to format them as this is currently not readable for us.

**Comment by ghost** [comment]
[httpd-prefix.txt](https://github.com/magento/magento2/files/2097780/httpd-prefix.txt)
[htaccess.txt](https://github.com/magento/magento2/files/2097781/htaccess.txt)

**Comment by DanielRuf** [comment]
Well, these are the default configs. You have to configure your server config (htaccess) to use the www / non www version by default and add the needed redirect. It's probably also in the config but just with a `#` and disabled by default.

**Comment by ghost** [comment]
https://community.bitnami.com/t/home-page-and-index-php-using-both-the-www-non-www-domain-variations/58331

**Comment by DanielRuf** [comment]
Normally it is done like this:
https://github.com/DanielRuf/daniel-ruf.de/blob/master/.htaccess#L18-L19
