### ISSUE TITLE
Request for ability to add new cart rule action - type cart id

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1564]
Request for ability to add new cart rule action - type cart id

Now it is not possible to give a discount on the FIRST item only

For instance we have a deal: the first T-shirt with 50% off ... (as a try out)

If the cart ID can be used in a rule action then this is possible

Concrete: please add cart id as a new rule type

![image](https://cloud.githubusercontent.com/assets/652395/8889384/3a594188-32d9-11e5-8e08-dab560a18022.png)

**Comment by mbrinton01** [comment]
Hello @seansan, thank you for your question.  I'm not sure I understand fully from your description. Can you clarify what you are trying to do? 

Would you like to give a discount on the first product that is added to the cart in a session?
Would you like to give a discount to a customer on the first time they purchase a particular product?

Also can you explain how cart ID would be useful in these scenarios? It doesn't seem to apply to the order that items are placed in the cart.

**Comment by seansan** [comment]
>> Would you like to give a discount on the first product that is added to the cart in a session?

Yes

.... Or The 3rd or the 10th

And I wasnt referring to cart id. But rather the id of the item in the cart. Where the lowest number id is probably the first product added 

I hope this clarifies it

**Comment by mbrinton01** [comment]
Thank you, I think I understand now what you are asking to do. Can you provide the business reason why you need this feature? Is it because you want to be able to offer a trial product to customers that is discounted? Or do you want to provide a discount on the first product when they buy more than one?

**Comment by seansan** [comment]
>> Is it because you want to be able to offer a trial product to customers
that is discounted?

In Fashion it is very normal to give a discount based on qty of items (like
the first product, or the 3rd)
Secondly when introducing new clothing you would want a step-in variant. So
we offer our clients 50% the first product they try.
(hoping that they will come back). Also even when they buy 3 at once or
even 6. We still offer the first product with 50% off.

>> Or do you want to provide a discount on the first product when they buy
more than one?
No this is not then intention. But it does happen they obtain a 50% for the
first product discount code (again). This is why we enabled the usage of
the specific coupon to use it twice. Often the first order is 1 shirt with
50% discount. The second 6 shirts with the first shirt with 50% discount.
After that they are fans --- and returnign customers (and dont use the code
anymore)

**Comment by mbrinton01** [comment]
Is the add to cart *order* important, or just that the customer get a discount? For example, as a customer if I am offered a 50% discount on the first item I add to the cart when I buy >1 item, I will add an expensive item to the cart first, followed by a cheap item.

It sounds like you just want the ability to:
* Choose a discount that is either a fixed amount or percentage
* Apply it to only one product in the cart
* When the cart contains a total quantity >1 across all products in the cart
* With the ability to decide which product it applies to - examples could be: order added to cart, most expensive, least expensive, etc.

Is that correct?  Also, does [this page](http://magento.stackexchange.com/questions/30326/apply-discount-to-only-1-item-in-the-cart-via-shopping-cart-price-rules) describe the same feature you are requesting, or is your request different?

**Comment by seansan** [comment]
>> Is the add to cart *order* important, or just that the customer get a
discount? For example, as a customer if I am offered a 50% discount on the
first item I add to the cart when I buy >1 item, I will add an expensive
item to the cart first, followed by a cheap item

Using conditions you set the scope the first item discount applies to.
Often is only 1 type of product. But yes if the above were the case then
the customer could do that. But that's fine. See it more as a method to
plut at least 1 item in cart (if qty >1 then how great is that: it worked)

>> It sounds like you just want the ability to:

   - YES Choose a discount that is either a fixed amount or percentage
   - YES Apply it to only one product in the cart
   - YES - ONLY FIRST OR SECOND ETC When the cart contains a total quantity
   >1 across all products in the cart
   - MOST AND LEAST SOUNDS AS AN IMPROVEMENT BUT YES With the ability to
   decide which product it applies to - examples could be: order added to
   cart, most expensive, least expensive, etc.

>> Is that correct? Also, does this page
<http://magento.stackexchange.com/questions/30326/apply-discount-to-only-1-item-in-the-cart-via-shopping-cart-price-rules>
describe
the same feature you are requesting, or is your request different?
YES

**Comment by mbrinton01** [comment]
Updated internal owner for this issue

**Comment by tkacheva** [comment]
Added to promotion backlog. internal ticket MAGETWO-40831

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Request-for-ability-to-add-new-cart-rule-action-type-cart-id/idi-p/47253).
