### ISSUE TITLE
TODO: use correct Exception class SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6024' for key 'PRIMARY', query was: INSERT INTO `sequence_product` (`sequence_value`) VALUES (?)

### ISSUE THREAD

**Issue by winds1983** [magento/magento2#15642]
When we add below code to fix multiselect save issue:
vendor/magento/module-catalog/etc/di.xml
`
<type name="Magento\Catalog\Model\Product">
        <arguments>
            <argument name="resource" xsi:type="object" shared="false">Magento\Catalog\Model\ResourceModel\Product</argument>
        </arguments>
    </type>
`
Multiselect issue is fixed, but new error was happenned:
TODO: use correct Exception class SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6024' for key 'PRIMARY', query was: INSERT INTO `sequence_product` (`sequence_value`) VALUES (?)

### Preconditions
Add below code to vendor/magento/module-catalog/etc/di.xml
`
<type name="Magento\Catalog\Model\Product">
        <arguments>
            <argument name="resource" xsi:type="object" shared="false">Magento\Catalog\Model\ResourceModel\Product</argument>
        </arguments>
    </type>
`

### Expected result
Throw error after click save button

### Actual result
TODO: use correct Exception class SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6024' for key 'PRIMARY', query was: INSERT INTO `sequence_product` (`sequence_value`) VALUES (?)

**Comment by magento-engcom-team** [comment]
Hi @winds1983 
We can not help with issues caused by editing files from `vendor`. You may try discussing it at [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/)

Thanks
