### ISSUE TITLE
Magento 2 varnish port 8080 issue

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#15653]
How solve this problem because magento 2.2.4 system.log can see error?

`main.CRITICAL: Unable to connect to localhost:8080 . Error #0: stream_socket_client(): unable to connect to localhost:8080 (Connection refused)`

This mean varnish port 8080 and varnish doesn't work?

**Comment by magento-engcom-team** [comment]
Hi @Userr017 
Unfortunately we can not provide any assistance with issue reports which do not follow recommended convention. 
Please update description with clear preconditions, steps to reproduce and actual/expected result and reopen if the issue persists.
Thanks.
