### ISSUE TITLE
StoreManager returns admin store by default while creating customer and resetting password

### ISSUE THREAD

**Issue by tizzyguy87** [magento/magento2#15664]
### Preconditions
1. Initially used Magento 2.2.0 CE
2. Upgraded to Magento 2.2.4 CE
3. PHP version 7

### Steps to reproduce
1. Upgraded to Magento version 2.2.4 from 2.2.0
2. Created customer from admin console
3. Triggered reset password for newly created customer
4. Customer receives email.
5. When tries to set password with reset link, getting below response from reset password API - 
```js
{"message":"No such entity with %fieldName = %fieldValue, %field2Name = %field2Value","parameters":{"fieldName":"email","fieldValue":"someuser@somedomain.com","field2Name":"websiteId","field2Value":"0"}}
```

### Expected result

1. Customer should be able to reset password

### Actual result

1. Getting response from reset password API as below
```js
{"message":"No such entity with %fieldName = %fieldValue, %field2Name = %field2Value","parameters":{"fieldName":"email","fieldValue":"someuser@somedomain.com","field2Name":"websiteId","field2Value":"0"}}
```

2. Admin store id and websiteId (which is 0) are used instead of Default store and it's id (which is 1) 

**Please note below details** :

1. customer_entity has store_id as 1 for customers 
2. retrieveByEmail method in CustomerRegistry.php has logic to get store from storemanager. This is returning 0 which is admin store but I need default store

**Comment by tizzyguy87** [comment]
Hi Magento team,

Can you please give ETA for this issue? This is blocker for us. Please suggest if there is any workaround till we get actual fix.

**Comment by tizzyguy87** [comment]
Team,

I found this issue in Magento 2.2.5 as well. Am I supposed to do anything to set my store as default store?

It was working perfectly fine in Magento 2.2.0. But not working in 2.2.4 and 2.2.5 as well.

**Comment by ghost** [comment]
@ tizzyguy87, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

**Comment by tizzyguy87** [comment]
1. Install Magento 2.2.0
2. Use default store. No need of multiple stores.
3. Import Products, create customers.
4. Create customers from admin console, trigger welcome mail and password reset mails.
5. Reset password from link given in email. Login using new password. Login works perfectly.
6. Place couple of orders.
7. Store is set as default store for customers, orders.
8. order sequence number is incremented in sequence_order_1
9. Upgrade Magento to 2.2.5 from Setup Wizard
10. Fix all the issues during migration.
11. Try to login with old customers. For new customers try to reset password.
12. Login not working. Password reset also not working. This is because magento returns store id as 0 instead of 1. So customer is not found for that email in storeid = 0
13. Did workaround to continue with login. In CustomerRegistry.php, retrieveByEmail method has logic to get websiteid. hard coded this to 1. Hence I am able to continue with login for existing customers.
14. Continue to add products to cart and place orders.
15. Order placed successfully with store id=0

**Comment by tizzyguy87** [comment]
#16953 is created for the same. I will close any one based on your inputs.

**Comment by ghost** [comment]
@tizzyguy87, closing this as a duplicate.
