### ISSUE TITLE
composer install  ,PHP extension ext-xsl * is missing from your system.

### ISSUE THREAD

**Issue by pengting** [magento/magento2#1566]
![m1](https://cloud.githubusercontent.com/assets/4326820/8891966/fac2c9a2-3370-11e5-8773-332b298a0ad3.png)

PHP.net
http://php.net/manual/en/xsl.installation.php
PHP 5 includes the XSL extension by default and can be enabled by adding the argument --with-xsl[=DIR] to your configure line (DIR being the libxslt installation directory).

How do I install this extension ?

**Comment by mazhalai** [comment]
@pengting what OS are you using?

**Comment by xcomSteveJohnson** [comment]
For example, Ubuntu 14: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-php56-install-ubuntu

**Comment by pengting** [comment]
centos 7

**Comment by Flyingmana** [comment]
should be solved by http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-centos.html

Its probably the `php-xml` package for yum, which brings this extension (mentioned in https://www.centos.org/forums/viewtopic.php?t=19250 )
But it could also be `php-xsl` as in ubuntu.

But in any case, it should be possible to install via the package manager of your OS, means `yum` for centos.

**Comment by piotrekkaminski** [comment]
@pengting is it resolved? Please reopen if you still have issues with it.
