### ISSUE TITLE
LinkManagement cannot be properly overridden

### ISSUE THREAD

**Issue by j0um** [magento/magento2#15663]
Properties and function of the class (Magento\ConfigurableProduct\Model) LinkManagement are all private instead of protected which makes it impossible to properly extend the class to add useful function like "addChildren" (multiple skus at once) and/or "setChildren" (remove old associations if any and add new ones).

### Expected result
LinkManagement functions should be overridable as they are the official way of doing things.

### Actual result
Code duplication is required to extend the class.

**Comment by magento-engcom-team** [comment]
Hi @j0um
According to section `2.6` of [Technical Guidelines](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html) this is a desired behavior. Try redesigning your code to use composition.

**Comment by j0um** [comment]
Thank you.
