### ISSUE TITLE
No clicks are working on Dashboard Page.

### ISSUE THREAD

**Issue by rishabh58** [magento/magento2#15662]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by rishabh58** [comment]
Also frotend website opening soo slow.

**Comment by magento-engcom-team** [comment]
@rishabh58 Unfortunately we can not provide any assistance for empty issue reports. 
Please update description and reopen if issue persists.
