### ISSUE TITLE
why we shouldn’t create abstract factory for CustomerFactory,ProductFactory etc?

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1567]
<?php
namespace Magento\Framework\ObjectManager\Code\Generator;

abstract class AbstractFactory 
{
    /**
     * Object Manager instance
     *
     * @var \Magento\Framework\ObjectManagerInterface
     */
    protected $_objectManager = null;

    /**
     * Instance name to create
     *
     * @var string
     */
    protected $_instanceName = null;

    /**
     * Create class instance with specified parameters
     *
     * @param array $data
     * @return \Magento\Catalog\Model\Product
     */
    public function create(array $data = array())
    {
        return $this->_objectManager->create($this->_instanceName, $data);
    }
}

    <?php
    namespace Magento\Catalog\Model;
    use Magento\Framework\ObjectManager\Code\Generator\AbstractFactory;
    /**
     * Factory class for @see \Magento\Catalog\Model\Product
     */
    class ProductFactory extends AbstractFactory
    {

        public function __construct(\Magento\Framework\ObjectManagerInterface $objectManager, $instanceName = '\\Magento\\Catalog\\Model\\Product')
        {

            $this->_objectManager = $objectManager;
            $this->_instanceName = $instanceName;
        }

    }

For example in ProductRepository class constructor  i want to pass AbstractFactory type instead of ProductFactory.

**Comment by vrann** [comment]
Abstract factory has vague typization: potentially it can construct everything and you never know what is constructed in particular invokation if you don't know the context. It makes harder to understand the code and to track dependencies between classes.

Besides, it can construct things you never wish to construct in the ProductRepository, for example Blocks. But using interface segregation principle, interface is supposed to provide just those functionality which client uses. 

The downside is that client needs to depend on more Factory classes, if it needs to construct more objects. Luckily, generated factories are light weight and does not have complex dependencies. So this is just a question of writing more lines of code. Hopefully clarity of the code should outweigh this concern.

**Comment by sivajik34** [comment]
thank you for your response & in-depth explanation.
