### ISSUE TITLE
getGrandTotal() returning shipping cost without discount

### ISSUE THREAD

**Issue by treii28** [magento/magento2#15673]
### Preconditions
Created a discount (in this case 100% off including 100% off shipping cost) as cart price rule

### Steps to reproduce
Create rule above
Applied discount code to cart

### Expected result
$0.00 total

1. [Screenshots, logs or description]

### Actual result
$0.30 (tax on cost of shipping)

We are trying to give certain customers that are going to review our website a 100% discount on single products when they give us feedback and help promote our website. The problem is that when they checkout, they are still getting charged for tax on shipping. (using taxjar)

They are looking into the issue as well, but in the process of doing some debugging, I was checking some things out myself. When I retrieve the quote using the ship-to address I am getting back the shipping cost even though the product cost is not included. 

e.g.:
 the product total was $250
 shipping is $5

without the discount code, $quote->getGrandTotal() returns $270.30 (product+shipping * 1.06 tax)

With the discount code entered it is returning $5 (not applying the discount to shipping). As a result, when taxjar is trying to calculate the tax, it ends up spitting out $0.30 ($5 * 1.06) so the total in the cart ends up spitting out $0.30 instead of $0.00

(NOTE: I'm not familiar with the quote in it's entirety so while I do not think 'getGrandTotal' is what's being used by taxjar to calculate the tax, I do assume that something is keeping the $5 in there at some other level in the grand-total calculation that they are also using which is returning the shipping without applying the discount to it)

**Comment by treii28** [comment]
Doing more testing here, this may be what it's supposed to be doing at that point. I've also opened a ticket with the taxjar folks to try to see if they aren't utilizing the getShippingDiscountAmount() function as it appears that while shipping has the value, there is also an equal value returned by the former.  It still does seem odd that it would return the 'grandtotal' applying the product discount but not the shipping discount. So I'm still trying to figure out the solution to my problem and just where the problem lay, so this still may be an issue - hopefully someone more learned than I can check.
[https://github.com/taxjar/taxjar-magento2-extension/issues/26](url)

But it still seems highly curious as when the coupon code is omitted, it not only returns the product amount, product tax amount, shipping amount but shipping tax amount in the total. (what I would expect) Meanwhile without it, all I'm getting is the shipping amount, no tax, no shipping tax.

**Comment by ghost** [comment]
@treii28, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
