### ISSUE TITLE
Magento Version show Unknown

### ISSUE THREAD

**Issue by Sujeet84190** [magento/magento2#15681]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by dmanners** [comment]
Hi @Sujeet84190 to help us reproduce the issue could you please fill in the steps on how to reproduce and well as expected and actual results.

**Comment by hostep** [comment]
@Sujeet84190: you might want to follow ticket https://github.com/magento/magento2/issues/22445, this one seems to have much more info (but it doesn't really sound like a bug in Magento, but more like a user error or an environmental issue).
