### ISSUE TITLE
Allowed memory size of 2097152 bytes exhausted (tried to allocate 20480 bytes) in vendor\zendframework\zend-eventmanager\src\Event.php on line 107

### ISSUE THREAD

**Issue by VijaySankhat** [magento/magento2#15684]
### Preconditions

1.  Magento 2.2.2
2. Window 10 [64 bit]
3. PHP Version 7.1.16

### Expected result

1. php bin/magento indexer:reindex [Should re-index ]
2. php bin/magento cache:clean  [Should clear cache ]
3. php bin/magento setup:upgrade [Should upgrade setup]

### Actual result

1. 
![error_screenshot](https://user-images.githubusercontent.com/9927047/40872949-fe737e22-6674-11e8-8eb4-cc625d35e9d8.png)

I am not able to trigger any command getting an error 

> Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 20480 bytes) in E:\xampp\htdocs\magento2\git\immamoda2\vendor\zendframework\zend-eventmanager\src\Event.php on line 107

Also tried increasing memory from php.ini but failed. blank screen at front and admin

**Comment by DanielRuf** [comment]
Did you restart PHP and the server? Also you can apply the memory setting to the php command on your console.

**Comment by VijaySankhat** [comment]
Thanks @DanielRuf, yes I did it, even restarted my PC twice. and to increase the memory i tried 

> php -d memory_limit=5G bin/magento setup:di:compile

**Comment by hostep** [comment]
@VijaySankhat : can you run `php --ini` and look at the file mentioned in `Loaded Configuration File`, it will tell you which ini file is used when php is executed over the cli, if you increase the `memory_limit` setting in that particular file, it should work.
There is no need for restarting anything when manipulating configuration files for the php cli, it will be read every single time you execute something with the php binary ;)

Btw: this isn't really a bug report against Magento itself, it's how you have configured your environment, so I'm closing this. Next time, it's best to discuss something like this on https://community.magento.com/ or https://magento.stackexchange.com/

Thanks and good luck! :)

**Comment by VijaySankhat** [comment]
thanks  @hostep, sorry to post my issue here, now onward I will use given link to report my issue.

**Comment by valuead** [comment]
solution? memory increase in php.ini doesn't work I have 4gb set 
magento cron:run
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/magento2/vendor/symfony/console/Application.php on line 710

**Comment by DanielRuf** [comment]
> solution? memory increase in php.ini doesn't work I have 4gb set
> magento cron:run
> PHP Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/magento2/vendor/symfony/console/Application.php on line 710

Make sure to increase it for the CLI and the normal PHP module.
Check your server settings.

**Comment by valuead** [comment]
Your post sounded like make sure you wash your hands before you’re eating … response about nothing . sorry this is how it make me feel

**Comment by DanielRuf** [comment]
Well, the CLI PHP is a different one.

**Comment by Modoperator** [comment]
I think valuead is correct. There is a 2GB memory_limit arbitrarily being set on PHP. I have magento 2.2.5 running in a Ubuntu/Trusty VM. I have both cli/php.ini and apache2/php.ini set with memory_limit = 4GB, the size of the VM.  In CLI php --ini shows path to cli/php.ini, on frontend phpinfo() shows path to apache2/php.ini.  But unless I put ini_set('memory_limit','-1'); in index.php or run magento cli commands with -d memory_limit=-1 I get the 'Allowed memory size of 2097152 bytes exhausted' message.   VM is running PHP7.1, all other versions of PHP have been removed.  It seems like somewhere memory_limit is being capped at 2GB but I can't figure out where.  Also running in developer mode, which might be why front end is requiring so much memory, but I am still baffled as to where this memory_limit value it is being set.

**Comment by waqasaps2** [comment]
You have to change it in your CLI.

Write `php --ini` to get your loaded configuration ini file.
example:  /etc/php/7.2/cli/php.ini

write: nano php bin/magento  /etc/php/7.2/cli/php.ini
to open the file. i hope you know how NANO editor works 

search for memory_limit and change it to 2G

Note: I use ubuntu CMD in windows, also you have to be in magento root directory when using these commands.

**Comment by fabianus76** [comment]
> 2097152 bytes

Hi Modoperator, 2097152 bytes are not 2GB but 2MB !

But yet, you helped me out: 
I had set 
memory_limit = 2GB
but this dosn't work, it has to be 
memory_limit = 2048M

**Comment by gcampedelli** [comment]
I have the same problem. Apache logs show same message but for different files. I increased memory_limit using both 1G and 1024M and always, no matter the number I declare in that it tries to allocate 20480 bytes. If I increase memory limit in php, htaccess, user.ini, php.ini I still get it tries to allocate 20480 bytes but the number of allowed memory size in the error is different. So I'm in the dark with this error.

**Comment by DanielRuf** [comment]
Hi @gcampedelli,

Did you try to provide these for the CLI?
Can you show the exact command that you have tried?

**Comment by gcampedelli** [comment]
Everything was normal until yesterday. I didn't try Magento2 commands, I just checked the logs. It is showing from time to time in Apache logs. 
[Tue Aug 20 01:11:11.188844 2019] [:error] [pid 3232] [client 127.0.0.1:58978] PHP Fatal error:  Allowed memory size of 792723456 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/magento2/vendor/magento/module-catalog/Model/ResourceModel/AbstractResource.php on line 51, referer: https://site.com.br/
[Tue Aug 20 01:11:11.204185 2019] [:error] [pid 3232] [client 127.0.0.1:58978] PHP Fatal error:  Allowed memory size of 792723456 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/magento2/vendor/magento/framework/Session/SessionManager.php on line 139, referer: https://site.com.br/
[Tue Aug 20 01:11:11.213798 2019] [:error] [pid 3232] [client 127.0.0.1:58978] PHP Fatal error:  Allowed memory size of 792723456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0, referer: https://site.com.br/
[Tue Aug 20 01:11:11.219007 2019] [:error] [pid 3232] [client 127.0.0.1:58978] PHP Fatal error:  Allowed memory size of 792723456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0, referer: https://site.com.br/
[Tue Aug 20 01:11:47.620604 2019] [:error] [pid 3390] [client 127.0.0.1:59690] PHP Fatal error:  Allowed memory size of 792723456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/magento/framework/Api/ExtensionAttributesFactory.php on line 52, referer: https://site.com.br/

I changed memory_limit to 1024M in following files:
/etc/php/7.0/cli/php.ini
/etc/php/7.0/apache2/php.ini
/etc/php/7.0/fpm/php.ini
And in .user.ini  and .htaccess in magento root and pub folder
But still I get in exception logs many exhausting erros collinmollehour memory exhausting in apache and this error in exception.log. 

So I increased and then:
[Wed Aug 21 15:00:46.230354 2019] [:error] [pid 19345] [client 127.0.0.1:51254] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/colinmollenhour/credis/Client.php on line 619, referer: https://mysite.com.br/
[Wed Aug 21 15:00:47.872580 2019] [:error] [pid 19400] [client 127.0.0.1:51366] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/magento/framework/Model/ResourceModel/Db/VersionControl/Snapshot.php on line 46, referer: https://mysite.com.br/
[Wed Aug 21 15:00:47.883098 2019] [:error] [pid 19400] [client 127.0.0.1:51366] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/magento/framework/App/DeploymentConfig.php on line 172, referer: https://mysite.com.br/
[Wed Aug 21 15:02:01.503390 2019] [:error] [pid 19245] [client 127.0.0.1:51950] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 291, referer: https://mysute.com.br/
[Wed Aug 21 15:02:01.513226 2019] [:error] [pid 19245] [client 127.0.0.1:51950] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/magento/framework/App/DeploymentConfig.php on line 172, referer: https://lojakaramello.com.br/
[Wed Aug 21 15:02:01.696442 2019] [:error] [pid 19383] [client 127.0.0.1:51958] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/magento/framework/Model/AbstractModel.php on line 355, referer: https://mysite.com.br/
[Wed Aug 21 15:02:01.706472 2019] [:error] [pid 19383] [client 127.0.0.1:51958] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/magento2/vendor/magento/framework/App/DeploymentConfig.php on line 172, referer: https://mysite.com.br/

When I get this error server crashs. 
[2019-08-19 21:59:05] main.CRITICAL: Warning: substr() expects parameter 1 to be string, object given in /var/www/html/magento2/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php on line 1188 {"exception":"[object] (Exception(code: 0): Warning: substr() expects parameter 1 to be string, object given in /var/www/html/magento2/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php on line 1188 at /var/www/html/magento2/vendor/magento/framework/App/ErrorHandler.php:61)"} []

I don't know what to do.

**Comment by hostep** [comment]
@gcampedelli, the important number in the error is the one in bold:

- PHP Fatal error: Allowed memory size of **1073741824** bytes exhausted (tried to allocate 20480 bytes)

This is the one you configured (1024MB == 1073741824 bytes), so that means your change actually did something!

But the error message also means that 1024M is not enough, you can try to increase it even further and see if that start working.
But it can also mean that there is some kind of memory leak in the code which is running or some code might not be written efficiently enough in that it will use too much memory.

**Comment by DanielRuf** [comment]
Please try it with 2GB as others did. 1GB is often not enough.

**Comment by gcampedelli** [comment]
@hostep and @DanielRuf Thank you for both answers. I changed memory_limit to 2048 on those files. I will see what happens and let you know.

**Comment by macleash90** [comment]
> @hostep and @DanielRuf Thank you for both answers. I changed memory_limit to 2048 on those files. I will see what happens and let you know.

What happened? Did it work? Facing same problem. Increased memory_limit to 4GB but still not working

**Comment by gcampedelli** [comment]
Hi, I had to identify one of modules which was causing the issue and I uninstalled it and fixed permissions because it was causing update.log file in var/log folder to increase without limits. Then it was solved.

**Comment by hubertus2017** [comment]
Hello,
i have the same problem

PHP Fatal error:  Allowed memory size of 6442450944 bytes exhausted (tried to allocate 20480 bytes) in xxxx/public_html/vendor/magento/module-store/Model/StoreRepository.php on line 112

Whatever memory limit is set, it give me this error in magento 2.4.4
