### ISSUE TITLE
Request to add ability to manage currency decimals

### ISSUE THREAD

**Issue by robert198222** [magento/magento2#1568]
Magento 1.x always shows all currencies with two decimals on frontend, but weaker currencies doesn't use decimals and there is no way to change this setting through admin in 1.x. Therefore I'm asking to add ability in admin to change how many decimals each currency should display on frontend.

**Comment by choukalos** [comment]
Dup of #1240 ; #1240 refers to both control of # of decimal places and rounding strategy.  I marked #1240 as up for grabs to the community as rounding function and # of decimal places constant should be fairly consolidated in the code by now;  Seems like an appropriate PR to add this configuration.  Big work item would be fleshing out the automated test cases to ensure proper function with the various permutations of # digits of precision and rounding strategies.  I'd appreciate any help we can get from the community on this.
