### ISSUE TITLE
GraphQL + Elasticsearch Not Working Due To "Out Of Range Int"

### ISSUE THREAD

**Issue by mpchadwick** [magento/magento2#15697]
### Preconditions

- Running 2.3-develop at 166dd6103544e7f98c272822f613b64dda700c24
- Elasticsearch v2.3.3 installed via Homebrew on Mac OS 10.13.4

### Steps to reproduce

Run the following...

```
{
    products(
      search: "Product"
      pageSize: 20
    )
    {
        total_count
        items {
          name
          sku
          price {
            regularPrice {
              amount {
                value
                currency
              }
            }
          }
        }
        page_info {
          page_size
          current_page
        }
      }
}
```

### Expected result

Product results are returned.

### Actual result

The following error

Numeric value (9223372036854775807) out of range of int

---

Issue seems to be due to the `size` parameter

```
"Elasticsearch\\Connections\\Connection::performRequest('GET', '/magento2-3-develop_product_1/document/_search', array(0), '{\"from\":0,\"size\":9223372036854775807,\"fields\":[\"_id\",\"_score\"],\"query\":{\"bool\":{\"should\":[{\"match\":{\"sku\":{\"query\":\"Product\",\"boost\":2}}},{\"match\":{\"_all\":{\"query\":\"Product\",\"boost\":2}}},{\"match\":{\"name\":{\"query\":\"Product\",\"boost\":6}}},{\"match\":{\"description\":{\"query\":\"Product\",\"boost\":2}}},{\"match\":{\"short_description\":{\"query\":\"Product\",\"boost\":2}}},{\"match\":{\"manufacturer\":{\"query\":\"Product\",\"boost\":2}}},{\"match\":{\"color\":{\"query\":\"Product\",\"boost\":2}}},{\"match\":{\"status_value\":{\"query\":\"Product\",\"boost\":2}}},{\"match\":{\"tax_class_id_value\":{\"query\":\"Product\",\"boost\":2}}}],\"minimum_should_match\":1}},\"aggregations\":{\"category_bucket\":{\"terms\":{\"field\":\"category_ids\"}}}}', array(1), instance of Elasticsearch\\Transport)"
```

I was able to track down that this is happening [here](https://github.com/magento/magento2/blob/943e2cdd0785a0aa0afd98364450860929171601/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/Search.php#L82)

This happens AFTER the page size setting which happens [here](https://github.com/magento/magento2/blob/943e2cdd0785a0aa0afd98364450860929171601/app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php#L91) forcing it to always be `PHP_INT_MAX`.

**Comment by mpchadwick** [comment]
Based on the comment I think it just needs to be a really big number, but probably doesn't need to be `PHP_INT_MAX` as I don't think there are any Magento stores with _that_ many products....

**Comment by mpchadwick** [comment]
A few more findings today

- Elasticsearch's maximum integer value is a 32-bit integer (https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)
- Even if you decrease the `setPageSize` call in `Magento\CatalogGraphQl\Model\Resolver\Products\Query\Search ` to 2147483647 you'll next get the following error... `{\"error\":{\"root_cause\":[{\"type\":\"query_phase_execution_exception\",\"reason\":\"Result window is too large, from + size must be less than or equal to: [10000] but was [2147483647]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter`

I'm not sure exactly what the "workaround" was intended to do, but probably needs to be re-thought.

**Comment by magento-engcom-team** [comment]
Hi @mpchadwick 
It would be best to open up a ticket at https://github.com/magento/graphql-ce as there are more people related to GraphQL tracking that project.

**Comment by ghost** [comment]
@mpchadwick, thank you for your report. 
This GitHub issue tracker is intended for Magento Community Edition technical issues only, so it's not recommended to create Elasticsearch-related issues here.
