### ISSUE TITLE
Errors on setup:upgrade

### ISSUE THREAD

**Issue by eCommerceGorilla** [magento/magento2#1569]
Spent the day getting Magento 2 setup and running. Installations went smooth and could navigate and use the stores front and back. However, whenever I run bin/magento setup:upgrade I am receiving the following errors:
[Zend_Db_Adapter_Exception]                       
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    
 [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory

I have tried this on both a local AMPPS testing environment and a remote nexcess SIP with the Magento 2 requirements and the error persists in both environments. I located another poster with this error however they were attempting to install sample data which I was not.

Is there something I am missing or is this a platform bug at this point?

**Comment by buskamuza** [comment]
Hi @eCommerceGorilla , as i can see such issue may be caused by incorrect settings for mysql.sock in PHP configuration. See https://github.com/magento/magento2/issues/737#issuecomment-62801577

Could you try to fix it and let us know if it helps? Probably, you'll have different path for the sock file.

**Comment by eCommerceGorilla** [comment]
Sorry for the delay but didn't have time to dig into this further until the weekend. The issue was indeed an issue with two php settings being used locally. For the remote server it turned out to be two installs of php, one for the web user and one when run via shell.

Incase someone else runs into this and needs to troubleshoot it. In your shell run php -i  and reference the path to your php configuration. On the server upload a php file with phpinfo() and check that the setting "Loaded Configuration File " matches that retrieved via php -i

**Comment by parekhreena** [comment]
@eCommerceGorilla  - i checked with php -i and phpinfo(). Both values of loaded configuration file are different. What should i do to resolve this ?

**Comment by rimkutea** [comment]
Good day, it could be my issue as well. I run a "pho -i" and got "Loaded Configuration File => /etc/php.ini". Where could I search the "On the server upload a php file with phpinfo()"? On the root folder could not see it...
