### ISSUE TITLE
Filtered Product Catalog page Select All -> Delete deletes all products

### ISSUE THREAD

**Issue by brendonk666** [magento/magento2#1571]
When on the Products->Catalog page and filtering by SKU, for example, with table only showing a small set of products, picking 'Select All' from the dropdown and then 'Delete' under actions causes ALL products in store to be deleted, not just the small set of products shown in table.

- All browsers
- Magento ver. 1.0.0-beta

**Comment by kumabotz** [comment]
Verified that happen too.

**Comment by kokoc** [comment]
@brendonk666 thank you for reporting the issue. Internal reference: MAGETWO-40932

**Comment by piotrekkaminski** [comment]
This should be closed now.
