### ISSUE TITLE
Can not access Magento 2 extension manager

### ISSUE THREAD

**Issue by allumanatu** [magento/magento2#15712]
### General

* Magento version: 2.2.4
* PHP version: 7.0

### Issue description

Unfortunately, I can not access the marketplace via Magento 2 Extension Manager, so accordingly I can not download my plugins I bought.

### Steps to reproduce

1. Open the Magento 2 Extension Manager
2. Type your public and private key inside
3. Submit the data

### Expected result

I should be able to see and to download my magento marketplace products.

### Actual result

The following error  is shown in a red panel above the public and private key form.

`Command "show" failed: Failed to clone the git@github.com:firegento/firegento-magesetup2.git repository, try running in interactive mode so that you can enter your GitHub credentials [RuntimeException] Failed to execute git clone --mirror 'git@github.com:firegento/firegento-magesetup2.git' '/var/www/html/var/composer_home/cache/vcs/git-github.com-firegento-firegento-magesetup2.git/' show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>]`

**Comment by magento-engcom-team** [comment]
Hi @allumanatu 
Looks like your issue is related to git credentials for `firegento/firegento-magesetup2`. Please try with the clean Magento installation and reopen if issue persists.
