### ISSUE TITLE
Sample data issue open

### ISSUE THREAD

**Issue by CoreyCole** [magento/magento2#1572]
Hey guys, there's been an [issue](https://github.com/magento/magento2-samples/issues/37) open for a week in the `magento2-samples` repository. Has anyone been able to successfully install the `sample-bundle-all` package?

**Comment by mazhalai** [comment]
Thank you @CoreyCole for reporting this issue. We have created ticket MAGETWO-40809 to investigate

**Comment by mazhalai** [comment]
@CoreyCole do you still have this problem in 2.0.0?

**Comment by sshrewz** [comment]
@CoreyCole since we have not heard from you for quite some time, we'll go ahead and close this issue.  Feel free to reach out to us if you encounter any issues by submitting a new issue.
