### ISSUE TITLE
Bot still able to create accounts with captcha enabled - Mail.RU_Bot/Img/2.0;

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#15735]
Issue Description
Bot still able to create customer accounts with captcha enabled - Mail.RU_Bot/Img/2.0;

Magento version 2.2.1

**Comment by magento-engcom-team** [comment]
Hi @msawyers 
Unfortunately this this information is insufficient to verify the issue. 
Please update report according to [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and reopen.
