### ISSUE TITLE
How to add new sales order grid in magento 2.1.6

### ISSUE THREAD

**Issue by vishalsri** [magento/magento2#15733]
Hey, there i m using magento 2.1.6 and i want to add some fields to the sales order filters and grid .

for that i code to add filters and grid in sales order table but unfortunately its working on thr magento 2.1.4 but didnt work in magento 2.1.6. Please help me out to do that for my client.

Thanks You ,

Vishal srivastava

**Comment by magento-engcom-team** [comment]
@vishalsri please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
