### ISSUE TITLE
Required attribute not available during process to create associated simple/virtual products to configurable parent

### ISSUE THREAD

**Issue by JamesAllwood** [magento/magento2#15743]
If an attribute is set as "is required", then during the quick creation of simple/virtual products via the "create configurations" options, the admin user should be able to quickly assign those values as they can for "quantity" and "weight".

In M1, this was certainly the case and we'd used this for attributes like "barcode". In M2, this isn't available, and this means that each simple product created via the the "create configurations" option needs to be individually edited after creation to add the missing required attributes

### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Create new attribute, and set value for option "Is Required" to "Yes" 
2. Assign new attribute to attribute set
3. Create new configurable product, choosing the attribute set from the previous step
4. Choose "Create Configuration"
5. Fill out the selected options (choose attributes/s, values, price, quantity, images)
6. Click "Generate Products"

### Expected result

User is presented with newly created simple/virtual products with editable boxes for 

- Name 
- SKU 
- Price
- QTY 
- Weight 
- New attribute (set to be required)

<img width="2445" alt="screen shot 2018-06-04 at 09 34 49 copy" src="https://user-images.githubusercontent.com/5270957/40907168-e16abe14-67da-11e8-95db-0b318547218e.png">

### Actual result

User is presented with newly created simple/virtual products with editable boxes for 

- Name 
- SKU 
- Price
- QTY 
- Weight 

<img width="2445" alt="screen shot 2018-06-04 at 09 34 49" src="https://user-images.githubusercontent.com/5270957/40907079-95bb4326-67da-11e8-8add-270437d770b9.png">

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.

> needs to be individually edited after creation to add the missing required attributes

You can use Update Attributes feature also.

**Comment by JamesAllwood** [comment]
@orlangur - you can't use the update attributes feature, as my example for barcode, they would be unique. As mentioned, it's a valuable feature of M1, so I'd personally still classify it as a bug that it's not available.

**Comment by orlangur** [comment]
This could be a feature in M1 but still a missing feature in M2, requiring bigger efforts than just a bugfix.
