### ISSUE TITLE
Module version number handling and checking suggestion

### ISSUE THREAD

**Issue by nagno** [magento/magento2#1576]
Hi,

I have a recommendation on how the module version numbers could be checked. At the moment there is a strict version checking. So if I have module `Namespace_Module` in my database with `schema_version = 1.1.0` and `data_version = 1.1.0` however my module is at the moment on version `1.0.0` in the `module.xml` file, Mage2 will complain about it and I have to manually downgrade the version number in the database.
This situation is happening quite often, when you are working with a VCS in a multiple branch environment (e.g. you have multiple team members working on different features and you are changing between them) and usually with different modules. This could render a local database completely inconsistent on a short run. 
The solution could be to enable non-backward compatibility breaking version number changes. This can be easily found out via the version numbers with semantic versioning. Even if you add an admin interface configurable option would be a great help.

E.g.:

| Module version | Schema version | Data version | Expected result |
| --- | --- | --- | --- |
| 1.0.0 | 1.1.0 | 1.1.0 | no warning message, because it is a non-BC breaking change |
| 1.1.0 | 1.1.0 | 1.1.0 | no warning message, because it is the same version |
| 1.2.0 | 1.1.0 | 1.1.0 | warning message, because it is a real upgrade |
| 1.0.0 | 2.0.0 | 2.0.0 | warning message, because it is a BC breaking change |

What do you think about it?

**Comment by buskamuza** [comment]
Hi @nagno , thanks for the valuable suggestion. We'll review how the developer workflow can be simplified in this case.
Internal ticket MAGETWO-40802.

**Comment by antonkril** [comment]
Working with the same database on different codebases can be very tricky.

That said, the current solution is to switch to declarative schemas. When we implement it, it should solve the problem.

Closing this issue since we will not be implementing the proposed solution.
