### ISSUE TITLE
Cannot overwrite Magento_Payment::info/instructions.phtml

### ISSUE THREAD

**Issue by sebfie** [magento/magento2#15761]
Hello,

I have an issue trying to overwrite Magento_Payment::info/instructions.phtml template on my theme. It never uses my template but always the vendor one.

### Preconditions

1. Magento 2.2.3
2. PHP 7.1.12

### Steps to reproduce

1. Create a frontend theme
2. Create file : `Magento_Payment/templates/info/instructions.phtml`in the theme
3. Create an order using a payment with instruction (example bank transfer) and add instructions on it
3. Create an order using frontend with this payment
4. Check order email sended, your template is not used

In fact I debugged a lot : 
It starts here : 

1. https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Sales/Model/Order/Email/Sender/OrderSender.php#L129 => We generate the payment part, of the email, in fact the first template is : `info/instructions.phtml`
2. We arrive here : https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/View/FileSystem.php#L117
3. We go deep into : `$this->_assetRepo->updateDesignParams($params);`. At this step, $params is : 
```
$params = array(
  "module" => "Magento_Payment",
  "area" => "frontend"
)
```
4. We go in 
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/View/Asset/Repository.php#L130
5. Then : https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/View/Asset/Repository.php#L145
6. This line : `$theme = $this->design->getConfigurationDesignTheme($area);` return the id of the theme instead of the FullPath, so next line we do : 
7. `$params['themeModel'] = $this->getThemeProvider()->getThemeByFullPath($area . '/' . $theme);` looking for example for a theme with theme_path `frontend/5`
8. Fail, fallback to vendor module views

### Expected result

1. Use my theme template file

### Actual result

1. Use vendor template file

**Comment by sebfie** [comment]
Related to #12638

**Comment by engcom-backlog-nickolas** [comment]
Hello @sebfie, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sebfie** [comment]
Thank you

**Comment by Bartlomiejsz** [comment]
Fixed in https://github.com/magento/magento2/commit/d3e32b4e5db80f7c04734f63cfeec83155613222#diff-5538e85fc1e008b1baa2324ff25ac673
