### ISSUE TITLE
Ability to add additional phtml to each shipping method

### ISSUE THREAD

**Issue by toonvd** [magento/magento2#1577]
This was not possible in Magento 1 for shipping methods but was for payment methods. This makes shipping extension creators override phtmls every time. Could it be usefull to make sure we can do this in Magento 2?

To be clear, I want shipping method - custom template file, shipping method - custom template file (not required to add one tough)

**Comment by jeroenvermeulen** [comment]
+1

**Comment by wsakaren** [comment]
shipping method or shipping carrier? They are different things. Shipping Carriers, yes totally.

**Comment by alankent** [comment]
A really useful technique is to propose example code of exactly how you would like it. It makes it concrete, more likely to be what you need, others can review publicly as well, etc. Don't spend too much time, optional, but it does help keep things moving along. We of course will review and make sure it fits in with the overall story.

**Comment by toonvd** [comment]
@alankent good idea, will have to dive in Mage2 again then ^^

**Comment by pronto2000** [comment]
+1 here as well -- thing is that around here most popular delivery method is parcel point delivery; while choosing delivery method one chooses a parcel point and picks it up from there (I think Amazon recently launched something like that as well). Traditional carriers may offer it as an additional shipping method.

To achieve it I added  dropdown to the payment method list phtml file fully knowing that whoever does something like in another extension there going to be conflict. Having an extra phtml block similar to saved CC would make this problem go away.

**Comment by sandermangel** [comment]
+1 from me too!

**Comment by janssensjelle** [comment]
+1

**Comment by janbuelens** [comment]
+1

**Comment by jokeputs** [comment]
+1

**Comment by jensvandorpe** [comment]
+1

**Comment by vpelipenko** [comment]
Guys, let's summarize. @toonvd, are you going to provide some examples?

**Comment by septembrium** [comment]
+1

**Comment by toonvd** [comment]
@vpelipenko ok, I will do it in Mage 1 code (how I would do it):
Shipping method phtml (changes marked by start custom changes):
```php
<?php $_sole = count($_shippingRateGroups) == 1;
foreach ($_shippingRateGroups as $code => $_rates): ?>
    <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
    <dd>
        <ul>
            <?php $_sole = $_sole && count($_rates) == 1;
            foreach ($_rates as $_rate): ?>
                <?php $shippingCodePrice[] = "'" . $_rate->getCode() . "':" . (float)$_rate->getPrice(); ?>
                <li>
                    <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages">
                            <li class="error-msg">
                                <ul>
                                    <li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li>
                                </ul>
                            </li>
                        </ul>
                    <?php else: ?>
                        <?php if ($_sole) : ?>
                            <span class="no-display"><input name="shipping_method" type="radio"
                                                            value="<?php echo $_rate->getCode() ?>"
                                                            id="s_method_<?php echo $_rate->getCode() ?>"
                                                            checked="checked"/></span>
                        <?php else: ?>
                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>"
                               id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?>
                               class="radio"/>

                        <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                            <script type="text/javascript">
                                //<![CDATA[
                                lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                //]]>
                            </script>
                        <?php endif; ?>

                        <?php endif; ?>
                        <label
                            for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                        </label>
                    <?php endif ?>
                   // start custom changes
                    <?php if ($html = $this->getShippingMethodFormHtml($_rate->getCode())): ?>
                        <span>
                          <?php echo $html; ?>
                     </span>
                    <?php endif; ?>
                  // end custom changes
                </li>
            <?php endforeach; ?>
        </ul>
    </dd>
<?php endforeach; ?>
```
Block:
```php
    public function getShippingMethodFormHtml($rateCode)
    {
         return $this->getChildHtml('shipping.method.' . rateCode);
    }
```

**Comment by toonvd** [comment]
![Image of Stackoverflow](http://i.stack.imgur.com/hmIVT.png)

Payment method equivalent

**Comment by toonvd** [comment]
@vpelipenko clear enough? or do you need more examples? (not used to doing this stuff :) )

**Comment by pronto2000** [comment]
Actually this is an improvement I'd LOVE to see backported to Magento 1 as well.

**Comment by ilol** [comment]
I put the improvement into our backlog. Will keep you inform with this task.
Tracking id is MAGETWO-41144

**Comment by toonvd** [comment]
awesome, thank you @ilol !

**Comment by toonvd** [comment]
@ilol any news on this? Cliënts will want to start porting shipping extension to Mage 2 soon.

**Comment by toonvd** [comment]
@asemenenko What is the status on this one? If I were to create a pullrequest myself, would it make the next release? This is very important for companies that build shipping methods to ensure higher quality.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Ability-to-add-additional-phtml-to-each-shipping-method/idi-p/46520).
