### ISSUE TITLE
Magento: can't capture the "sales_order_place_before" event 

### ISSUE THREAD

**Issue by lucbaojang** [magento/magento2#1581]
I created this files to capture  "sales_order_place_before" event but I can't. I also tried with other events and them worked for me.

- /Mycompany/Modulename/app/etc/frontend/events.xml

![2015-07-29_18-01-41](https://cloud.githubusercontent.com/assets/13554212/8956006/f2f07802-361b-11e5-937f-a5353572c254.png)

-  /Mycompany/Modulename/app/Model/Observer.php

**Comment by blankapham** [comment]
Having same problems. Does anyone help me?
Thanks,

**Comment by trungha89** [comment]
i have same issue. Can someone help me please?

**Comment by vpelipenko** [comment]
We will work on this. Internal ticket: https://jira.corp.x.com/browse/MAGETWO-40857.

**Comment by lucbaojang** [comment]
@vpelipenko : thank you but I cannot access your page :(

**Comment by vpelipenko** [comment]
Sorry, it is only for internal usage.

**Comment by rganin** [comment]
Checkout (specially order placing request) is processed via Magento's REST API since latest releases. 
Add your `events.xml` file with observers to `webapi_rest` area by moving
/Mycompany/Modulename/app/etc/frontend/events.xml
to
/Mycompany/Modulename/app/etc/webapi_rest/events.xml

**Comment by lucbaojang** [comment]
@rganin thank you so much, It worked for me :+1:

**Comment by blankapham** [comment]
@rganin Thank you for sharing. It is very useful for me. :)

**Comment by vpelipenko** [comment]
@lucbaojang, can we close this issue?

**Comment by lucbaojang** [comment]
@vpelipenko yes. please close it. Thank you again :)

**Comment by kartikasodariya17** [comment]
Can you please give me both files one is events,xml and Observer.php ? So it will help for me .
Thanks

**Comment by pradeep2949** [comment]
Thanks a lot @rganin it solves the problem

**Comment by ankushx** [comment]
my event is still not invoking sales_order_save_before even in global events,webapi_rest ,,,
