### ISSUE TITLE
1.0.0-beta install error

### ISSUE THREAD

**Issue by yzm629** [magento/magento2#1582]
![default](https://cloud.githubusercontent.com/assets/8325201/8964385/e52aad82-3657-11e5-9e27-2ae052c3e18b.JPG)

**Comment by markoshust** [comment]
You may want to post more info on operating system, php version, etc. so this can be diagnosed

**Comment by dfediuk** [comment]
This is well known bug. 
Magento mangles some csv file names and then can not find the files.
The solution is here: https://mage2.pro/t/topic/13

**Comment by yzm629** [comment]
ubuntu 15.04  php5.6

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [technical issues forum](https://community.magento.com/t5/Technical-Issues/bd-p/magento-2-technical-issues) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by dfediuk** [comment]
But this is a bug.

**Comment by daim2k5** [comment]
Not anymore. Is fixed.
