### ISSUE TITLE
Can't use input type in query

### ISSUE THREAD

**Issue by PiotrSzlagura** [magento/magento2#15827]
### Preconditions

1. Magento version: 2.3
2. PHP: 7.1.18
3. Server: nginx, version: 1.12.2

### Steps to reproduce

1. Create empty Magento 2.3 instance
2. Install sample data from repo
3. Using graphql client/plugin of your choice (tested on many of them, always with the same result) send POST request to http://[your Magento instance]/index.php/graphql
```graphql
query GetProductsQuery($page: Int, $filterInput: ProductFilterInput){
  products(
    pageSize: 10
    currentPage: $page
    filter: $filterInput
    sort: {}
  ) {
    items {
    	name
    }
  }
}
```
with variables:
```json
{
  "page": 1,
  "price": {
    "gt": "10"
  }
}
```

### Expected result

1. Query should return filtered products list, since `ProductFilterInput` is an input type, according to scheme

### Actual result

1. Received following error:
```
Variable "$filterInput" cannot be non-input type "ProductFilterInput".
Variable "$filterInput" of type "ProductFilterInput" used in position expecting type "ProductFilterInput".
```

I've tested this approach on clean GraphQL installation and it worked without any problem.

**Comment by zetlen** [comment]
I ran into this too! The types called "Input" in our schema are not implemented as actual GraphQL input types in the current build.

**Workaround**: Build the filter input shape inside the query, and use only primitives as variables.

```graphql
query GetProductsQuery($page: Int, $minPrice: String){
  products(
    pageSize: 10
    currentPage: $page
    filter: {
      price: {
        gt: $minPrice
      }
    }
    sort: {}
  ) {
    items {
    	name
    }
  }
}
```

with variables:

```json
{
  "page": 1,
  "price": {
    "gt": "10"
  }
}
```

This is a real bug and not a style issue, because without an actual input type, the filter conditions are not actually configurable--they're hardcoded into the query. I'm sure that wasn't the intention.

**Comment by ghost** [comment]
@PiotrSzlagura, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by misha-kotov** [comment]
This issue is a duplicate of https://github.com/magento/graphql-ce/issues/93 - we will be tracking progress over there in the GraphQL project.
