### ISSUE TITLE
Ability to delete or cancel a shipment

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1584]
This doesn't exist in M1 but I believe it should be in M2. There are times when shipments are created by accident, or the customer calls to cancel their order. In those circumstances the shipment should be able to be deleted or canceled.

**Comment by asemenenko** [comment]
Thanks! We have it captured in MAGETWO-991

**Comment by markshust** [comment]
@asemenenko is this being handled internally? i'm a bit confused on the internal ticket numbers, i wasn't sure if these were still being resolved or if everything is now handled on github.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Ability-to-delete-or-cancel-a-shipment/idi-p/47249).
