### ISSUE TITLE
2.2.4 Product text swatch displays admin swatch value instead of store value

### ISSUE THREAD

**Issue by pixiemediaweb** [magento/magento2#15849]
### Preconditions
Magento 2.2.4
Usual Magento stack; php7, nginx, mariadb

### Steps to reproduce
Both sites have text swatch attributes for configurable product options which always used to show the correct store specific labels.

After upgrade to Magento 2.2.4 text swatches are not showing the correct store value. Instead they display the admin default version in all store views.

Confirmed on 2 installations: 1 site upgraded from 2.2.3, 1 upgraded from 2.1.10.  

### Actual result
Since upgrading to 2.2.4, the visible label of the swatch shows the admin value, not the store view version.  When you hover the swatch, the correct value is shown in the tooltip

### Expected result
screen shots below.  

Site 1 - only single store, but the store label is being ignored in display, and honoured in tooltip:
![bug_site_1](https://user-images.githubusercontent.com/6330277/40975945-70dea9fe-68c4-11e8-861c-fc08656b160b.png)
![bug_site_1a](https://user-images.githubusercontent.com/6330277/40975951-765d2eaa-68c4-11e8-9b4a-a840a96c953b.png)

Site 2 - multi store.  Same result - admin value is being shown in the swatch, and the correct store label is shown in the tool tip
![bug_site_2](https://user-images.githubusercontent.com/6330277/40975963-859dd07c-68c4-11e8-840e-18892852e7f9.png)
![bug_site_2a](https://user-images.githubusercontent.com/6330277/40975966-87cfdb4c-68c4-11e8-8334-d2aae00857c0.png)

**Comment by pixiemediaweb** [comment]
Resolved by replacing /vendor/magento/module-swatches/ with the version from 2.2.3.  Not ideal, but we don't have time to scrutinise every line of code right now.  Definitely a problem in the 2.2.4 release of that module fellas. 

Here is a copy of the 2.2.3 release for anyone else that has this issue https://github.com/pixiemediaweb/module-swatches/tree/master

**Comment by engcom-backlog-nickolas** [comment]
Hello @pixiemediaweb, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by kmddevdani** [comment]
https://github.com/magento/magento2/pull/15960 fixes it for me; I am on Magento 2.2.5.

**Comment by TomashKhamlai** [comment]
@kmddevdani, after applying this fix attributes loose the possibility to switch the attributes type. For example text swatch will not change to visual swatch on product page after changing the type from admin panel. Could you check this?

**Comment by ovidiucaramida** [comment]
There is a module that can help you a lot when creating/editing products with swatches by showing you the colors and images in the product edit form

https://marketplace.magento.com/webpanda-product-form-swatches.html

**Comment by engcom-Bravo** [comment]
Hello @pixiemediaweb 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
