### ISSUE TITLE
show product name in product page

### ISSUE THREAD

**Issue by nikidexa** [magento/magento2#15844]
Hi, I just want to show product name in product page, on the top, above product image

Preconditions
magento 2.2.2
Luma theme

Steps to reproduce
Want to show product  name in product page

Expected result
See product name in product page on top, above product image

Actual result
Dont see anything at the moment, just product name in breadcrumbs 

This is what I want
![schermata-2018-06-05-alle-12 52 49](https://user-images.githubusercontent.com/38526353/40971991-93b3c25c-68bf-11e8-9038-2f066117f42a.jpg)

Thanks

**Comment by nikidexa** [comment]
Solved, by myself so can close this issue!

**Comment by routbiplab** [comment]
It's because of the theme that you using. Try changing the product view template.
