### ISSUE TITLE
[Question] join on product and custom eav attribute

### ISSUE THREAD

**Issue by Shotman** [magento/magento2#15851]
Hello,
I've created a multiselect custom eav attribute for a product everything is working fine but I'd like to get the data of each associated eav attribute inside the product object all in 1 request. 

Right now it's what i'm doing but if I have 500 products I have to do 500 requests to get the eav attributes data
```
$product = $this->productRepository->getById($id);
        $attr = $product->getCustomAttribute("Flags");
        $flagContent = [];
        if ($attr && $attrValues = $attr->getValue()) {
            $flag = $this->flagsCollectionFactory->create();
            $flagContentObject = $flag->addFieldToFilter("flags_id", explode(",", $attrValues))->toArray();
            if ($flagContentObject["items"]) {
                $flagContent = $flagContentObject["items"];
            }
        }
        return $flagContent;
```
Is there anyway to make this more efficient without going in pure SQL or in the getConnection method ?

Thanks

**Comment by magento-engcom-team** [comment]
@Shotman please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
