### ISSUE TITLE
2.2.3 Please explain why the Display Shipping Prices depends on Catalog Prices?

### ISSUE THREAD

**Issue by Daisy288** [magento/magento2#15852]
### Preconditions
   Magento version: 2.2.3
   - Create tax class and tax rate & tax rule for shipping 
   - Create a tax rule for shipping origin (with tax rate = 8.25%)
   - Enable some shipping methods, for example: Flat Rate (type = Per item) has price = 5$

### Steps to reproduce
1. Set the Catalog Prices field = Excluding Tax
2. Set the [Shipping Prices] field = Including Tax
3. Set the [Display Shipping Prices] field = Excluding Tax
4. At the frontend -> Add a product to cart -> go to the shopping cart page, observe and check the shipping price 

### Expected result
The shipping prices (excluding tax) = 4.62$ ((5$ - 8.25%)
### Actual result
The shipping prices (excluding tax) = 5$ -> 
http://prntscr.com/jr5n41
http://prntscr.com/jr5mjg
Shipping price is only correct when I set the [Catalog Prices] field to Including Tax.

**Comment by ghost** [comment]
Hi @Daisy288 This issue has already been fixed in 2.2-develop branch

**Comment by ghost** [comment]
- "Flate Rate" shipping method is enabled and has default price = 5.00 (Store > Configuration > Sales > Shipping Method tab Flat Rate)
- Tax Rule based on new specific tax rate is created (Stores > Tax Rules)
- Tax Rate configuration
- Tax Identifier = New Tax Rate
- Zip/Post Code = *
- State = *
- Country = United States
- Rate Percent = 20
- Simple Product is created
- Tax has next configuration: (Store > Configuration > Sales > Tax)
- Tax Class for Shipping = Taxsble Goods (Tab: Tax Classes)
- Display Shipping Amount = Excluding Tax (Tab: Shopping Cart Display Settings)
- Shipping Prices = Including Tax (Tab: Calculation Settings)
- Catalog Prices = EXCLUDING TAX (Tab: Calculation Settings)
- STEPS:
- 
- Go to Storefront
- Add Simple product to Shopping Cart
- Go to Shopping Cart page
- Click to Estimate Shipping and Tax for expanding section
- Fill Country = United States

**Comment by Daisy288** [comment]
@engcom-backlog-nazar Thank you for your reply
