### ISSUE TITLE
Readiness check passes with PHP 5.5, but adding DB requires 5.6

### ISSUE THREAD

**Issue by unirgy** [magento/magento2#1585]
PHP Version Check
Your PHP version is correct (5.5.9-1ubuntu4.11).

Step 2: Add a Database
Sorry, but we support MySQL version 5.6.0 or later.

**Comment by mazhalai** [comment]
Hi @unirgy PHP version is not the same as MySQL version

**Comment by unirgy** [comment]
Ah thanks, going too quickly!

**Comment by unirgy** [comment]
is there a specific incompatibility with Mysql 5.5?

**Comment by mazhalai** [comment]
Yes, Magento 2  is incompatible with MySql 5.5.

**Comment by ramseyjiang** [comment]
Hi Mazhalai, do you know when Magento 2 can be compatible with Mysql 5.6?
I have the same problem when I install Magento.
The notice is "Sorry, but we support MySQL version 5.6.0 or later."

**Comment by mazhalai** [comment]
@ramseyjiang please avoid commenting on closed issues. What is your version of Mysql? It will NOT be compatible with MySQL 5.5 you need 5.6 or higher.
