### ISSUE TITLE
add search cancel button again?

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15869]
Currently the search cancel button is removed and this was also done in normalize.css but was later changed.

See https://github.com/necolas/normalize.css/issues/685

Should we also add it for better UX?

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.

**Comment by DanielRuf** [comment]
Well, in general it is a bug ;-)

I'll create a PR then.
