### ISSUE TITLE
2.2.4 EE Unable to change themes of stores

### ISSUE THREAD

**Issue by silvanaguilar** [magento/magento2#15873]
On Magento 2.2.4 EE I'm not able to apply different themes on different stores.

**Preconditions**
1. Win 10, Mac Sierra or Ubuntu 18.04 (tested on all of them)
2. Magento 2.2.4
3. Docker 18.03.1, PHP 7.1.13

**Steps to reproduce**
1. Go to the administrator
2. Create one more store under Stores/All Stores in order to have the "Default Store View" and "Second Store View".
3. Go to Content/Design/Configuration and apply the Magento Blank theme to the first store and Luma to the second one
4. Now, go to Store/Configuration -> General/Web -> Url Options and select **YES** on the Add Store Code to Urls option (so at the end of the domain the code of the store will be added)
5. Go to the frontend and visit both stores. 
ie: my first store url is **_magento2.test/default_** and my second url is **_magento2.test/second_**

**Expected result**
6. Default Store View should display Blank theme
7. Second Store View should display Luma Theme

**Actual result**
8. Both stores are displaying Blank theme

![2a-stores](https://user-images.githubusercontent.com/2109774/41003033-f8e17b20-68eb-11e8-8839-636ffde301b3.JPG)
![2b-website-code](https://user-images.githubusercontent.com/2109774/41003034-f905b1de-68eb-11e8-98f5-97656d42e8d4.JPG)
![3-design-conf](https://user-images.githubusercontent.com/2109774/41003036-f93138a4-68eb-11e8-916d-54386b16210b.JPG)
![4-store-code-to-urls](https://user-images.githubusercontent.com/2109774/41003037-f9564478-68eb-11e8-9987-5ec45e11b829.JPG)
![8a-second-website](https://user-images.githubusercontent.com/2109774/41003038-f97f6b82-68eb-11e8-886f-288df4c5aaaa.png)
![8b-default-website](https://user-images.githubusercontent.com/2109774/41003039-f9a40564-68eb-11e8-8689-1ad2745da97f.png)

**Comment by DanielRuf** [comment]
Did you clear all Magento caches and deploy the static content?

**Comment by silvanaguilar** [comment]
Yes, I absolutely did both

**Comment by hostep** [comment]
@silvanaguilar: this is a know bug in 2.2.4, it was reported before, if you use multiple websites, the configuration fallback no longer works properly. See these other tickets: https://github.com/magento/magento2/issues/15205, https://github.com/magento/magento2/issues/15245

The [release notes for 2.2.4](https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.4EE.html) were updated yesterday and this warning was added:
> Known issue
> Customers have reported the following behavior after upgrading to Magento 2.2.4 in deployments that span multiple websites:
> 
> Magento multi-store installations do not use the store view-specific values from the store configuration settings if these settings have different values than the global default configuration settings. Instead, Magento uses the default configuration for all store views. GitHub-15205, GitHub-15245
> 
> We do not recommend upgrading to Magento 2.2.4 if you deploy across multiple websites. Note that this problem is not triggered if you have only a single website with multiple stores or store views.

**Comment by fmarangi** [comment]
The problem was introduced in c18e36b804fb3c86caa39d9976ce5db7497001a7, the session configuration object is initialized too early, before the pathinfo is processed. The fix is really simple and involves using a proxy, I'm currently working on a PR for it.

**Comment by hostep** [comment]
Let's quote from [the PR](https://github.com/magento/magento2/pull/15929) to provide info when this issue will be fixed:
> fix will be available in 2.2.5 release, the changes were delivered to 2.2.5 release line in the separate internal pull request
