### ISSUE TITLE
Layered navigation does not appear in search result page

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1587]
Layered navigation does not appear in the search result page. Is there any back end setting to enable this ?
![image](https://cloud.githubusercontent.com/assets/3830093/8979902/8ce78550-36ca-11e5-8e8b-85d86101a626.png)

**Comment by kandy** [comment]
If you need show layered navigation for some attribute then please enable it in backend. Go to stores > attributes > product, find and open needed attribute (for example price) and on tab "Storefront Properties" configure "Use in Search Results Layered Navigation" - Yes

**Comment by bgkavinga** [comment]
Thanks @kandy

**Comment by SatishDubariya** [comment]
This does not work if i will use search  result page layout 1 column. Is it possible to have layered navigation while using 1 column in search page.
