### ISSUE TITLE
Ui component grid in date range filter does not populate correctly after reloading the page

### ISSUE THREAD

**Issue by ronak2ram** [magento/magento2#15883]
On Magento CE 2.2.4. Ui component grid in date range filter does not populate correctly after reloading the page. There is an issue with date format.

**Preconditions**
1. Ubuntu 18.04
2. Magento CE 2.2.4
3. PHP 7.1.13

**Steps to reproduce**
1. Go to the administrator
2. Go to the SALES > Orders page
3. Click on Filters and filter Purchase Date 
From - 06/01/2018  
To - 06/05/2018 
Than apply filter.
4. Just reload the page and check populated filter value Like - Purchase Date: 01/20/2006 - 05/20/2006

**Expected Result**
1. Purchase Date: 06/01/2018 - 06/05/2018

**Actual Result**
1. Purchase Date: 01/20/2006 - 05/20/2006

**Additional Note**
1. This happens on any admin grid that uses a date range for filtering, not only the sales order grid.

----- 
**Appling Filter**
![screenshot](https://user-images.githubusercontent.com/11473750/41022282-a8b5d0d8-6986-11e8-8264-e2de2ca286f5.png)

**After reload page**
![screenshot2](https://user-images.githubusercontent.com/11473750/41022858-69607e22-6988-11e8-95a3-dc1670302f2c.png)

**Comment by ronak2ram** [comment]
@magento-engcom-team

Hello Team,

How soon my bug gets resolved? as I have generated this bug since long. Is there anything that I need to do to make this possible sooner?

Regards
Ronak

**Comment by ghost** [comment]
hi @ronak2ram  seems like duplicate-> https://github.com/magento/magento2/issues/16507
