### ISSUE TITLE
Create Product Configurations :: Apply unique quantity by attribute to each SKU when attribute combination

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#1588]
I was testing Product Configurations when I noticed something that is not logical.
I will try explaining this with an example.
I am creating an configurable product T-shirt in 3 colors and 3 sizes. So I'm working with the attributes general_size and color.
I have the possibility to Apply unique quantity by attribute to each SKU:
However I need to choose "color" or "size" before I can enter a value (qty) for each sku.
This is not logical because I should be able to configure that I have only 1 color Black, XS size, and 10 color Black Medium sizes, for example. Now whatever I enter in the value qty boxes for either color and size, the only value that are registered are those for size....

When replicating this issue It will become clear to anyone that it is impossible to set a qty for a specifiek color/siz
![2015-07-30_15h35_47](https://cloud.githubusercontent.com/assets/13572447/8984308/06a3aa4e-36d1-11e5-83df-9f99dd9e703a.png)
![2015-07-30_15h35_53](https://cloud.githubusercontent.com/assets/13572447/8984310/09ca1d98-36d1-11e5-9cac-7537e2e11e2a.png)
![2015-07-30_15h36_05](https://cloud.githubusercontent.com/assets/13572447/8984311/0b4c1f18-36d1-11e5-8fcc-6b33d5dc4843.png)

e combination

**Comment by tanya-soroka** [comment]
Hello @SidneyBilliet, thank you for you question. 

Let me try to explain each of the proposed options in the Bulk setup. 
* Apply single QTY to each SKU. Provides ability to specify one / same QTY, which will be used for each generated variation. 
* Apply unique QTY by attribute to each SKU. Provides ability to specify QTY per attribute value. Example, customer is going to sell T-Shires with 3 different colors (yellow, red, blue) and 2 different sizes (M and S). Customer would like to specify 3 QTY to each blue T-shirts, 5 for red and 7 for yellow. As a results, customer will ahve
** T-Shirt blue S -> QTY =3
** T-Shirts blue M -> QTY=3
** T-Shirt red S -> QTY =5
** T-Shirt red M -> QTY =5 and etc.
* Skip Qty for now. Provides ability to specify different QTY per each variation in the main grid. This option should covered your use-case. 

Please tell me if you have more questions.

**Comment by SidneyBilliet** [comment]
Hello,

This explanation only covers the fact to add quantity IF all quantities are equal per size/color.
What If you have same example: 3 different colors(yellow, red, blue), two sizes (S,M) and you would want to specify:

Red:

-          Small: QTY = 1

-          Medium: QTY = 5
Yellow:

-          Small: QTY=2

-          Medium: QTY=6
Blue:

-          Small: QTY=3

-          Medium: QTY=6

I believe this is not possible with the current configuration wizard, correct?

Kind regards,

Sidney Billiet
eCommerce Project Manager, Studio Emma

+32 (0)51 610026
http: //www.studioemma.com
sidney@studioemma.eu<mailto:sidney@studioemma.eu>

Ten Briele 10 bus 8
8200 Sint-Michiels, Belgium
[cid:E41B1043-7D64-4CB9-9A63-893C64CBC0B1]  [middle_solution_specialist]

**Comment by tanya-soroka** [comment]
@SidneyBilliet it is possible, but on in the Wizard. 
You need to select Skip option on the wizard and add these different values on the generated configurations grid. The QTY will be editable.

**Comment by piotrekkaminski** [comment]
Closing as no response from original author.
