### ISSUE TITLE
One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by cmx43** [magento/magento2#15881]
Good day.

I installed magento 2.2.4 through cpanel - softaculous. 

it appears a new message that says "One or more indexers are invalid. Make sure your Magento cron job is running." I've saw several video tutorials and even read some forums or articles, but the solutions presented are for manually installed magento. I dont even have files in my pc of magento. The thing is I dont know anything of programming stuff, please if you could explain me step by step it would be great!

**Comment by magento-engcom-team** [comment]
@cmx43 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
