### ISSUE TITLE
Image management ::  once "hide from product page" is ticked and saved, It will not save when I untick the box

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#1589]
How to reproduce:
1. add a product
2. add an image
3. Save
4. click Image management
5. Click the image to open a window with "base, small, thumbnail" config
5. tick the "Hide from product page box
6. close the window that opened
7.save
8. click Image management again
9. Click the image to open a window with "base, small, thumbnail" config
10. UNtick the "Hide from product page box
11. close the window that opened
12. save
13. Click the image to open a window with "base, small, thumbnail" config again
14. notice that the "hide from product page" box IS STILL TICKED

I am unable to change this setting as of now...

**Comment by kokoc** [comment]
@SidneyBilliet thank you for reporting the issue. We will fix the problem and get back to you once we have the working code. Internal reference: MAGETWO-40940

**Comment by piotrekkaminski** [comment]
This should be fixed now.
