### ISSUE TITLE
Missing "Add Root Category" and "Add Subcategory" Buttons

### ISSUE THREAD

**Issue by Kesquom** [magento/magento2#15900]
### Preconditions
Magento 2.2.3
PHP 7.1.13

### Steps to reproduce
Go to Catalog -> Categories
### Expected result
Ability to add categories.

### Actual result
The Buttons for creating categories and subcategories went both missing at some point. I disabled every single extension besides the Magento defaults. Switching store views doesn't help, setting permissions doesn't help. The store is in an early development stage, no changes to the code base were made.

**Comment by kisroman** [comment]
@Kesquom, sound very strange :) 
By the way fresh install of Magento 2  has this buttons in any way.

**Comment by Kesquom** [comment]
Very strange indeed, however I'm not the only one. Over on stackexchange there is someone else with this issue. 

https://magento.stackexchange.com/questions/220465/magento-2-add-subcategory-button-not-showing-in-catalog-categories

I have no idea when the buttons disappeared or what action triggered it.

**Comment by lewis-dan** [comment]
@Kesquom, tried to replicate the same, however, did not get any error. You can flush Cache and run  setup:upgrade, I believe it will solve the issue.

**Comment by visahardik** [comment]
Same issue, I am facing tried to resolve by debbuging in `Magento\Catalog\Block\Adminhtml\Category\Tree::_prepareLayout()` you will get `false` in first if codition some time. you will get more idea in this file.

May be it will help you to resolve your problem 
Thanks

**Comment by ghost** [comment]
@Kesquom, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by surinderkaur01** [comment]
This issue is appearing if all admin access will not provided. category and subcategory button working only if admin access is there for admin user, if custom access will provide then these buttons will not show.
