### ISSUE TITLE
Customer segments not working in cart price rule when placing order from admin

### ISSUE THREAD

**Issue by RanjitBShinde** [magento/magento2#15904]
When we are using customer segment in cart price rule and placing order from admin the cart rule is not applying to that order. The same cart rule is working fine from frontend for same customer.

Magento version : EE 2.1.9

Steps to replicate issue 
1. Create customer segment
2. create cart price rule with customer segment
3. Place order from magento admin and check discount applied

Code Assumption 

vendor/magento/module-customer-segment/Model/Customer.php::getCurrentCustomerSegmentIds() not handled for admin customer session.

**Comment by magento-engcom-team** [comment]
@rambashinde thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by RanjitBShinde** [comment]
@magento-engcom-team Thanks for the reply. I will report this issue in Support portal.
