### ISSUE TITLE
Can a block be cached for period of time?

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1591]
Hi,

Is it possible to cache a block for period of time, for example, it expires every 15 minutes? I would like to display a block on sidebar for all pages and to avoid performance issue as the information inside the block doesn't change frequently.

Is there an xml parameter available to do that?
``` 
<referenceContainer name="sidebar.additional">
    <block class="xxx" before="-" name="xxx" template="xxx.phtml" cacheable="true"/>
</referenceContainer>
```

Thanks,

**Comment by rganin** [comment]
Yes. A "ttl" attribute designed for setting cache lifetime for a block in seconds. 
```
<referenceContainer name="sidebar.additional">
    <block class="xxx" before="-" name="xxx" template="xxx.phtml" cacheable="true" ttl="900"/>
</referenceContainer>
```
See sample in app/code/Magento/Doc/view/doc/layout/default.xml

**Comment by adzminz** [comment]
Thank you for your help, rganin. :+1: 
I tried searching an example from base before but didn't found any of them. I must have looked over them.

**Comment by Jakhotiya** [comment]
You can find an example in file vendor/magento/module-theme/view/frontend/layout/default.xml
```
 <block class="Magento\Framework\View\Element\Template" name="store.menu" group="navigation-sections" template="Magento_Theme::html/container.phtml">
                    <arguments>
                        <argument name="title" translate="true" xsi:type="string">Menu</argument>
                    </arguments>
                    <block class="Magento\Theme\Block\Html\Topmenu" name="catalog.topnav" template="html/topmenu.phtml" ttl="3600" before="-"/>
                </block>
```

**Comment by jarnail1004** [comment]
@rganin  I try this "ttl" but it didnt work.  I want to uncached BLOCK on product page and I try to use this TTL by setting to minimum time but its doent work. i am using maqgento 2.1.8

**Comment by agoeurysky** [comment]
hi @jarnail1004 , I try this "ttl" attribute with a "60" value to have 1 minute for the cache lifetime, but it didn't work, like you. Do you have some information about it ?

**Comment by jarnail1004** [comment]
@agoeurysky , this works only if you are using Varnish cache.
