### ISSUE TITLE
Default Store Configuration Conflict

### ISSUE THREAD

**Issue by vetalkab** [magento/magento2#1592]
**Description:** 
It is impossible to switch to default (set in Magento admin) Store View on frontend when MAGE_RUN_CODE is set to another Store View in .htaccess or index.php. 

**Steps to reproduce:**
There are 3 Store Views which belong to one Store and one Website:
store1 - is set as default in Magento admin
store2
store3 - is set as default in index.php

> $params = $_SERVER;
> $params['MAGE_RUN_CODE'] = 'store3';
> $params['MAGE_RUN_TYPE'] = 'store';
> $bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);

Go to frontend. As default opens store3. We can successfully switch to store2, we can not switch to store1, it redirect to store3.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-43620

**Comment by mengbo123456** [comment]
****
![image](https://user-images.githubusercontent.com/29748690/27775937-3ecb6b04-5fd9-11e7-8a21-452e861139a6.png)

**Comment by magento-engcom-team** [comment]
@vetalkab, thank you for your report.
The issue is already fixed in 2.2.0
