### ISSUE TITLE
Json encode for extension attributes 

### ISSUE THREAD

**Issue by adlime** [magento/magento2#15928]
I have done extend other module by using extension_attributes.xml, additional table in database that has attribute value and using plugins added information to the model object. 

Now I trying to output value of that attribute to json for adminhtml form, but some method in framework do not transform ‌NameSpace\Module\Api\Data\PostExtension object to array but return empty array.

That is place where my object transform to empty arrray
[https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/TemplateEngine/Xhtml/Result.php:84
](url)
```
‌NameSpace\Module\Api\Data\PostExtension::__set_state(array(
   '_data' => 
  array (
    'is_popular' => '1',
  ),
))
```

Perhaps problem is in the json_encode function that can't transform object rightly.

**Comment by magento-engcom-team** [comment]
@adlime Closing in favor of #15959 as it has more details on the problem. Please continue tracking there.
