### ISSUE TITLE
Configurations Section Expanded By Default on Edit Product Page in Admin

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#15938]
### Preconditions

1.  Magento Version 2.2.3

On the edit product page in the admin, the Configurations Section Expanded By Default.  Is there any special reason why this is necessary?  How can this behavior be changed, so it is no longer expanded by default?

**Comment by engcom-backlog-nickolas** [comment]
Hello @orbitrod. Yes it's intended behaviour. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
