### ISSUE TITLE
customer_register_success event doesn't have a `getCustomer()` method.

### ISSUE THREAD

**Issue by yamenarahman** [magento/magento2#15934]
Magento: 2.2.4
PHP: 7.2

As customer_login event which is associated with `Magento/Customer/Model/Session.php` there is a `getCustomer()` method that returns customer details. However the Customer_register_success event which is associated with `Magento/Customer/Controller/Account/CreatePost.php` there is no `getCustomer()` or `getCustomerId`.

So how to get customer data after registration event ?

**Comment by engcom-backlog-nickolas** [comment]
Hello @yamenarahman, thank you for your report. Unfortunately I cannot reproduce this issue by provided details.
![peek 2018-07-09 13-55](https://user-images.githubusercontent.com/40755810/42446646-b978cdcc-837f-11e8-80fa-75e74b067e74.gif)
Could you please correct steps I did, or provide more details?

**Comment by yamenarahman** [comment]
It seems like the issue is solved! maybe it's my misunderstanding or code syntax.
Thanks for illustration.
