### ISSUE TITLE
Rich Snippets Error missing and required field "price" for Group products

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#1593]
I checked the rich snippet from https://developers.google.com/structured-data/testing-tool/
The first error came from the group product itself and the others came from related group products on the bottom of the page.

![schema-checker](https://cloud.githubusercontent.com/assets/11070293/9003769/178cc01e-379b-11e5-8e5b-e16697f40330.png)

**Comment by godban** [comment]
Hello @adzminz,
Verified, price is missing. Thanks a lot for finding this issue. We added it to our internal ticket   MAGETWO-40793, which will extend Magento microdata and fix this problem.

**Comment by magento-engcom-team** [comment]
Hi @Pakkapao the issue has been fixed in https://github.com/magento/magento2/commit/16c0741fb1d2c7ef07e93f135e80e726f7596724
Thank you for your report
