### ISSUE TITLE
Error facing when new product created in Magento 2.0.17

### ISSUE THREAD

**Issue by shaikhmasud147** [magento/magento2#15930]
Error facing when new product created

Product save successfully but the facing the error message below

![test _ products _ inventory _ products _ Magento admin](https://user-images.githubusercontent.com/21688214/41097083-674bbf2e-6a74-11e8-87c1-28486e76682b.png)

Can you explain what happened??

**Comment by magento-engcom-team** [comment]
Hi @shaikhmasud147 
Please update the issue report to include clear details on the problem, which can be reproduces with a clean installation of Magento. We are closing this ticket now, please reopen when it's updated.
