### ISSUE TITLE
Unable to add product attributes to template via mobile

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#1594]
Hi,

This is a feature request to have alternative method for adding attributes to the product template. Currently, the only way to add them is drag&drop which we couldn't do it via mobile.

I have an idea showing list of available groups when long press attributes.

![2015-07-31 18 50 35](https://cloud.githubusercontent.com/assets/11070293/9006771/6161bfe0-37b5-11e5-8b5e-c5e9919f7aae.png)

**Comment by tkacheva** [comment]
Admin Panel is not optimized for mobile for now. We do have plans to make Admin touch ready MAGETWO-39801

**Comment by pboisvert** [comment]
Is this a mobile use case or a touch use case? re you editing product attributes via a smart phone or tablet in a mobile context or is this a touch enabled laptop (or large tablet) context?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unable-to-add-product-attributes-to-template-via-mobile/idi-p/46516).
