### ISSUE TITLE
 Cron script readiness check failed. Found non-writable path(s): [magento_dir]/bin/magento [magento_dir]/setup/html

### ISSUE THREAD

**Issue by muckee** [magento/magento2#15957]
When attempting to perform a readiness check via the system update utility in the backend, I receive the following error:

Check Cron Scripts
Cron script readiness check failed.
Error from Updater Application Cron Script:
Found non-writable path(s):
[magento_dir]/bin/magento
[magento_dir]/setup/html

I have attempted to properly set permissions again, to no avail.

I can see in `var/log/update.log` that the filepaths to both of these directories contain whitespace, both at the beginning of the filepath and following the `[magento_dir]` directory, before the trailing forward slash. I'm not sure if this is the source of the issue, or something to do with the formatting of log files.

I have confirmed, though, that the symlink at `[magento_dir]/setup/html` is broken.
When I issue the command `ls [magento_dir]/setup/html`, then I recieve the following error `ls: cannot access 'setup/html': Too many levels of symbolic links`.

### Preconditions
1. Magento 2.2.3 installed via composer using Redis for all cache storage, running in Developer mode.
2. Ubuntu 16.04
3. Apache 2.4
4. MySQL 5.7.22
5. PHP 7.1
6. Varnish Cache with nginx for SSL termination running on a separate server.
7. Permissions set for a post-installation developer environment as per magento documentation.
8. Ownership has been assigned to the `www-data` group in order to retain proper permissions on upgrade/deployment etc.
9. Magento user has been added to the `www-data` group.

### Steps to reproduce
1. Access Magento System Upgrade utility via admin panel.
2. Perform readiness check.

### Expected result
1. Readiness check successful.

### Actual result
1. Received 'Cron script readiness check failed' error during 'Check Cron Scripts' test.

**Comment by muckee** [comment]
Following the steps described in [this issue](https://github.com/magento/magento2/issues/14423), the error for the path [magento_dir]/bin/magento has disappeared, however the error for path [magento_dir]/setup/html still occurs.

**Comment by anthr76** [comment]
I'm having this same issue

**Comment by muckee** [comment]
It seems incredibly common and caused by all kinds of different things, from what I've read, though I haven't found any reports of exactly the same error message. Are you having problems with the `setup/html` symlink as well?

I have added this issue as a question to the [magento stackexchange](https://magento.stackexchange.com/questions/229241/magento-2-2-web-setup-wizard-cron-script-readiness-check-failed-found-non-wri). My question contains links to solutions for other errors with the Cron readiness check, but not this one. Hopefully at least one of us can get it working!

**Comment by muckee** [comment]
The issue is also mentioned [here](https://github.com/magento/magento2/issues/12915), albeit with  errors about different paths.

**Comment by ghost** [comment]
@JoshuaFlood , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
