### ISSUE TITLE
POST a new image media for a product doesn't save roles properly

### ISSUE THREAD

**Issue by bibiseb** [magento/magento2#15956]
### Preconditions

1. Magento 2.2.6-dev
2. PHP 7.0.7

### Steps to reproduce

POST V1/products/{sku}/media

```
{
    "entry" : {
    	"media_type" : "image",
    	"position" : 1,
    	"disabled" : false,
    	"types" : ["image", "small_image", "thumbnail"],
    	"content" : {
    		"base64_encoded_data" : "/9j/4AAQSkZJRgABAQEAYABgAAD//gA7Q1...",
    		"type" : "image/jpeg",
    		"name" : "myimage.jpg"
    	}
    }
}
```

### Expected result

1. In the product administration the image should have these roles: Base, Small, Thumbnail

### Actual result

1. The image has no role

**Comment by engcom-backlog-nickolas** [comment]
Hello @bibiseb, thank you for your report. Unfortunately I cannot reproduce this issue.

![peek 2018-08-02 14-03](https://user-images.githubusercontent.com/40755810/43579951-71090b16-965c-11e8-87e6-7d2429e8af97.gif)

If you'd like to update it, please reopen the issue.

**Comment by bibiseb** [comment]
Hello,

Same issue on **Magento ver. 2.2.4**

In fact the roles are saved on the first store view but not globally. Do I do something wrong ?
