### ISSUE TITLE
Magento checkout issue

### ISSUE THREAD

**Issue by sid09N** [magento/magento2#15951]
checkout loader keeps loading not stop in magento 2.2.2. After clicking on proceed to chekout it just keep loading.
<img width="868" alt="forum" src="https://user-images.githubusercontent.com/40055620/41146192-32c944f4-6b20-11e8-8a0e-61bff4022ef4.PNG">
<img width="919" alt="forum2" src="https://user-images.githubusercontent.com/40055620/41146199-384f7aba-6b20-11e8-85ff-b64a3d1d9034.PNG">

**Comment by magento-engcom-team** [comment]
Hi @sid09N 
Unfortunately current issue description does not provide enough information to reproduce the issue on a clean Magento installation. Please update the ticket with clear and detailed steps to reproduce and reopen. We are closing this item for now.
