### ISSUE TITLE
Text Swatches does not use storeview content after upgrade to Version 2.2.4

### ISSUE THREAD

**Issue by glwstor** [magento/magento2#15952]
Visuall Text Swatches doesn´t use the store view content at a multi store view Magento after upgrading from Version 2.2.3 to 2.2.4
### Preconditions
Magento 2.2.2 without sample data
    Apache 2.4.27
    PHP 7.1

### Steps to reproduce
product attribute - > visual text swatch -> two attributes -> english and e.g. german translation
configurable product -> visual text swatch
german store view -> english visual text swatch

### Expected result
german store view -> german visual text swatch
![german-german](https://user-images.githubusercontent.com/16683372/41147933-f2b3d04a-6b07-11e8-960e-6e49cc5517f1.jpg)

### Actual result
german store view -> english or admin visual text swatch
![german-english](https://user-images.githubusercontent.com/16683372/41148071-5424d20c-6b08-11e8-9b31-11ebaef863a4.jpg)

**Comment by glwstor** [comment]
This issue was also found from other people.
Please have a look at the following link: https://github.com/pixiemediaweb/module-swatches

**Comment by ghost** [comment]
Hi @glwstor thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
duplicate -> https://github.com/magento/magento2/issues/15849
