### ISSUE TITLE
Magento2 CSV product import qty and is_in_stock not working correct

### ISSUE THREAD

**Issue by matin73** [magento/magento2#15950]
### Preconditions
1.  PHP 7.0.6
2. Magento CE 2.2.4
3. MYSql 5.6.35

### Steps to reproduce
1. Create an CSV file for import products
2. Set Quantity (field qty) to f.E. 99 and is_in_stock to 0 (we want to have quantity for product but set out of stock)
3. import CSV

### Expected result
1. Product should have quantity 99 and "Out of Stock"

### Actual result
1. Product has quantity but is "In Stock"

**Comment by saravananvelu** [comment]
@magento-engcom-team  I am working on this.

**Comment by ghost** [comment]
Hi @saravananvelu  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by p-bystritsky** [comment]
Created PRs for 2.2 and 2.3.

**Comment by magento-engcom-team** [comment]
Hi @matin73. Thank you for your report. 
The issue has been fixed in magento/magento2#20177 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - [4ec34a2b5948fd0356e6f6d239793336d94c60d6](https://github.com/magento/magento2/commit/4ec34a2b5948fd0356e6f6d239793336d94c60d6)

The fix will be available with the upcoming 2.2.8 release.

**Comment by obukhow** [comment]
This fix caused another bug.

### Steps to reproduce

1. Create product with positive qty in stock and stock status "In stock"
2. Create an CSV file for import products
3. Set Quantity (field qty) to 0
4. import CSV

### Expected result

Product should have quantity 0 and status "Out of Stock"

### Actual result

Product has zero quantity but is "In Stock"

The case worked properly before this issue fix.

**Comment by alexishughes** [comment]
Is this new? modify existing product to qty=0 is_in_stock=1 price=£499 via CSV upload and no fields are modified. This is a problem as we have quite a few back-order items which are available for sale but have zero qty. It used to work.
