### ISSUE TITLE
There is no event in: AbstractBlock::toHtml() to capture block html after it has been added:

### ISSUE THREAD

**Issue by paras89** [magento/magento2#1595]
Like in Magento1 we can observe event 'core_block_abstract_to_html_after', there doesn't seem to be an event fired in Magento 2. There is an event fired before:  view_block_abstract_to_html_before 
but none after.

Also the toHtml() function has a comment saying: "This method should not be overridden." While the function is declared as public. Why not set it to Private?

See here: https://github.com/magento/magento2/blob/0.42.0-beta10/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L622][1]

**Comment by OZZlE** [comment]
@paras89 I tried to plugin afterToHtml and after_ToHtml() on product listing but that seems to break it.. how did you solve this?
