### ISSUE TITLE
product url will not be set at product detail page after saving

### ISSUE THREAD

**Issue by glwstor** [magento/magento2#15953]
We are using a multi store view shop with version 2.2.3.
All products has set a seo friendly url, but magento shows a lot of them only with catalog/product/view/id...
At the sitemap we see the ugly urls after generation like https://www.xxxxxxxxx.de/catalog/product/view/id/473

Even if we made an update of the url at the product detail page, the url will still be the same.
The only way to set a new url is to select the checkbox at the product page "SEO" -> URL key ->"use default value" ->save  at a "store view" to activate the rewrite. After this it is possible to change the url in proper way.

### Preconditions
    Magento 2.2.3 without sample data
    Apache 2.4.27
    PHP 7.1

### Steps to reproduce
product with a seo unfriedly url like /catalog/product/view/id/473
store view e.g. german -> product -> SEO -> url key "some-item-xxx" -> save

### Expected result
new url https://xxxxxxx.de/some-item-xxx at the frontend and sitemap

### Actual result
new url https://xxxxxxx.de/catalog/product/view/id/473 at the frontend and sitemap

**Comment by glwstor** [comment]
This problem occur, when an item is not assigned to a category

**Comment by ghost** [comment]
Hi @glwstor  The fix for this issue is already available in the 2.2-develop branch.
