### ISSUE TITLE
M2.2.4 : Extension attributes of quote models are not properly encoded to the frontend

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#15959]
When I add extension attributes to a quote, they are not properly encoded to the frontend.

### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Create extension attributes for a quote object
2. Populate it with something
3. Check `window.checkoutConfig.quoteData.extension_attributes` on the checkout page.

For example:

    <extension_attributes for="Magento\Quote\Api\Data\CartInterface">
        <attribute code="order_reference_customer" type="string">
            <join reference_table="sales_order_reference" join_on_field="entity_id" reference_field="quote_id">
                <field>customer_reference</field>
            </join>
        </attribute>
    </extension_attributes>

In plugin / interceptor for `Magento\Quote\Api\CartRepositoryInterface`:

    /**
     * @param CartRepositoryInterface $subject
     * @param CartInterface $quote
     * @return CartInterface
     */
    public function afterGet(CartRepositoryInterface $subject, CartInterface $quote)
    {
        $quote->getExtensionAttributes()->setOrderReferenceCustomer('foo');
        return $quote;
    }

I've tested if the intercepter worked by good old `var_dump` and `die`. The extension attribute is populated and it is present in the quote on the checkout page.

### Expected result

`window.checkoutConfig.quoteData.extension_attributes` should be populated with the extension attributes.

### Actual result

Instead it is an empty object `{}`.

My guesses of what might cause this:

- `Magento\Checkout\Model\DefaultConfigProvider::getQuoteData()` : Here there is a method called `$quote->toArray()`, but it does not serialize the extension attributes (these are still objects, and not plain data). or:
- `Magento\Checkout\Block\Onepage::getSerializedCheckoutConfig()` : This does a simple `json_encode()` on the data provided by the `DefaultConfigProvider`. My guess is that it ignores objects.

Possibly related to #15928

**Comment by kanduvisla** [comment]
For people running into this issue, I wrote a quick fix that can be used in a plugin for `Magento\Checkout\Model\DefaultConfigProvider`:

    /**
     * @param \Magento\Checkout\Model\DefaultConfigProvider $subject
     * @param array $result
     * @return array
     */
    public function afterGetConfig(\Magento\Checkout\Model\DefaultConfigProvider $subject, array $result)
    {
        /** @var CartExtension $extensionAttributes */
        $extensionAttributes = $result['quoteData']['extension_attributes'] ?? null;

        if ($extensionAttributes instanceof CartExtension) {
            $data = [];
            foreach ($extensionAttributes->__toArray() as $key => $value) {
                if (is_string($value)) {
                    $data[$key] = $value;
                }
            }
            $result['quoteData']['extension_attributes'] = $data;
        }

        return $result;
    }

The underlying problem I guess, is that even though the `__toArray()`-method of the extension attributes object serializes it, sometimes it's value is not a string, but an object. In that case, no extension attributes are outputted to the json format.

**Comment by engcom-backlog-nickolas** [comment]
Hello @kanduvisla, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
The issue has been fixed in magento/magento2#24771 by @skylineop in 2.3-develop branch
Related commit(s):
 - [2826f74772af2091e8b5262d06beac7b79eaa700](https://github.com/magento/magento2/commit/2826f74772af2091e8b5262d06beac7b79eaa700)
 - [e8180399433fcd7489bebf63af9186071d323106](https://github.com/magento/magento2/commit/e8180399433fcd7489bebf63af9186071d323106)
 - [0c7844eefcf76acdcefeea778fb7b9f273df396a](https://github.com/magento/magento2/commit/0c7844eefcf76acdcefeea778fb7b9f273df396a)

The fix will be available with the upcoming 2.3.5 release.
