### ISSUE TITLE
Errors and Wartings after optimize magento tables

### ISSUE THREAD

**Issue by springimport** [magento/magento2#15962]
### Preconditions
Optimize tables in magento 2.2.3.

### Steps to reproduce
Optimize tables.

### Expected result
Tables have been optimized.

### Actual result
Errors and warnings for some tables.
Examples:

> Incorrect default value for updated_at in quote_address.

> Incorrect datetime value: '0000-00-00 00:00:00'

**Comment by ghost** [comment]
@springimport, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
