### ISSUE TITLE
Country selection when creating a new customer is not working

### ISSUE THREAD

**Issue by Tassoschrono** [magento/magento2#15966]
When creating a new customer the Country selection field drop down menu doesn't show anything.

![drop menu field not working](https://user-images.githubusercontent.com/40072483/41176751-3d342c72-6b27-11e8-8005-ff0f8582a8b5.JPG)

**Comment by magento-engcom-team** [comment]
Hi @Tassoschrono 
Unfortunately this information is not sufficient to reproduce the issue. Please update this issue report with a clear steps to reproduce. We are closing this ticket now, please reopen when it's updated.
