### ISSUE TITLE
Unable to log into my magento backend

### ISSUE THREAD

**Issue by gawpo50** [magento/magento2#15969]
### Preconditions

1. Magento 2.2.4 running on a GoDaddy Hosted Linux Platform with PHP 7.1
2. Site running perfectly up till last night and has done so since it was setup.
3. As of this morning, myself & customers cannot log on
4. Getting the following two different errors. 
    Exception printing is disabled by default for security reasons.
    Failed to set ini option "session.save_handler" to value "files". 

### Steps to reproduce

1. Attempt to log into your account or access the admin side of magento produces this error now...
    Failed to set ini option "session.save_handler" to value "files". 
2. I have renamed the local.xml.sample file to local.xml, which then gave me the second of the two errors listed above
3. I have manually cleared the var/cache form within CPanel
4. Error above still persists, cannot access the backend to my site at all

### Expected result

1. I should be able to as I normally could, log into my magento backend and do things. I'm totally locked out

### Actual result

1. Result I'm getting...this error
    Failed to set ini option "session.save_handler" to value "files". 
    Cannot find anything to help me fix this error so I can get my site working again.

2. I have checked in the php.ini file for session.save_handler.....actual code below:
    session.save_handler = files
    session.save_path = "/opt/alt/php70/var/lib/php/session"
    session.auto_start = 0

As far as I can tell, this is correct.   

Help required please.

**Comment by SaintLuticriss** [comment]
I too am running Magento 2.2.4 on a GoDaddy Hosted Linux Platform with PHP 7.1 .
I updated my "_/vendor/magento/framework/Session/_**SessionManager.php**" file with the hotfix code provided by tiagosempai and got this new error:

> Exception #0 (InvalidArgumentException): Failed to set ini option "session.cookie_lifetime" to value "3600". Function _mcrypt_module_close()_ is deprecated.
> #0  /home/user/public_html/vendor/magento/framework/Session/SessionManager.php(184): Magento\Framework\Session\SessionManager->initIniOptions() ...

I even flushed the cache via CLI command "_php bin/magento cache:flush_"  and reindexed with "_php bin/magento indexer:reindex_", but received the same error.

**Comment by gawpo50** [comment]
all working now...this issue can be closed

**Comment by ladle3000** [comment]
What the hell, post a solutions, don't just close....
