### ISSUE TITLE
Provide a FactoryInterface

### ISSUE THREAD

**Issue by Swahjak** [magento/magento2#15973]
### Preconditions

1. Create a custom factory

### Steps to reproduce

1. Magento changes the way factories are implemented

### Expected result

1. I get errors about my factories not applying the correct interface methods

### Actual result

1. My code breaks without a warning

In my opinion there is no reason for auto generating factories at all. If factories are required they could be easily achieved with a default factory class and a simple configuration (see below). But considering the current situation I guess it's to late to change this. I would like to suggest introducing an ```FactoryInterface``` which all auto generated Factories implement. This way there is a "contract" for the Factory which can catch errors in an early development stage more easily.

```php
/**
 * Class FactoryInterface
 */
interface FactoryInterface
{
    /**
     * @param null $data
     */
    public function create($data = null);
}

```
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <virtualType name="sampleFactory" type="Magento\Core\Model\Factory">
        <arguments>
            <argument name="objectManager" xsi:type="object">Magento\Framework\ObjectManagerInterfacer</argument>
            <argument name="className" xsi:type="string">Magento\Core\Model\Sample</argument>
        </arguments>
    </virtualType>
    <type name="Magento\Core\Model\SampleRepository">
        <arguments>
            <argument name="factory" xsi:type="object">sampleFactory</argument>
        </arguments>
    </type>
</config>
```

```php
/**
 * Class Factor
 */
class Factory
{
    /**
     * @var \Magento\Framework\ObjectManagerInterface
     */
    protected $objectManager;

    /**
     * @var string
     */
    protected $modelClassName;

    /**
     * @param \Magento\Framework\ObjectManagerInterface $objectManager
     */
    public function __construct(
        \Magento\Framework\ObjectManagerInterface $objectManager,
        string $modelClassName
    )
    {
        $this->objectManager = $objectManager;
        $this->modelClassName = $modelClassName;
    }

    /**
     * Create model
     *
     * @param array $data
     * @return object
     */
    public function create($data = null)
    {
        return $this->objectManager->create($this->modelClassName, $data);
    }
}
```

**Comment by engcom-backlog-nickolas** [comment]
@Swahjak, thank you for your report. GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
