### ISSUE TITLE
Since Magento 2.2.1, certain variables in the configuration get resolved to their actual value

### ISSUE THREAD

**Issue by hostep** [magento/magento2#15972]
Before Magento 2.2.1 (2.2.0 and 2.1.x), when you entered a variable in the configuration like `{{unsecure_base_url}}`. Magento still rendered that value as entered in the configuration field. But since Magento 2.2.1, the variable gets resolved to the actual value. And if you save that particular configuration again, it will overwrite the value in the database with the actual current value instead of still storing the variable.

After git bisecting, I've identified the commit https://github.com/magento/magento2/commit/86d46ce0bdeca61ade5c1063edcb70367f17b2a5 to have introduced the problem, more specifically, the changes in the file `app/code/Magento/Config/Block/System/Config/Form.php` are responsible for this problem. I also see that part of the above commit was reverted again in 6c9a8b258446950e2bd8b41844c529a7be67f335, but it wasn't fully restored to how it used to be.

/cc @viktym: since you were involved in those commits, you might have an idea of what we need to do to fix this issue? Thanks!

### Preconditions
1. PHP 7.1.18

### Steps to reproduce
1. Setup a clean Magento 2.2.1 installation (or 2.2.4 or 2.3-develop, tested with commit 33393e23a3b)
2. In the backend configuration go to: General > Web > Base URLs & Base URLs (Secure)
3. Enter `{{unsecure_base_url}}media/` in "Base URL for User Media Files" and `{{secure_base_url}}media/` in "Secure Base URL for User Media Files"
4. Save Config
5. Look at those two fields you just edited

### Expected result
1. "Base URL for User Media Files" should contain: `{{unsecure_base_url}}media/`
2. "Secure Base URL for User Media Files" should contain: `{{secure_base_url}}media/`
3. In the database, the values are still at `{{unsecure_base_url}}media/` & `{{secure_base_url}}media/`
4. Resaving the configuration and looking at the database again, values are still at `{{unsecure_base_url}}media/` & `{{secure_base_url}}media/`

### Actual result
1. "Base URL for User Media Files" contains: `http://example.com/media/`
2. "Secure Base URL for User Media Files" contains: `https://example.com/media/`
3. In the database, the values are still at `{{unsecure_base_url}}media/` & `{{secure_base_url}}media/`
4. Resaving the configuration and looking at the database again, the values have been replaced with `http://example.com/media/` & `https://example.com/media/`

**Comment by PascalBrouwers** [comment]
What's even worse in a multistore setup is if correct it by entering manually `{{unsecure_base_url}}media/` for "Base URL for User Media Files" in the global scope, but have entered a different "Base URL" in the website scope and have "Base URL" still set to "Use Website" on the store scope. The base url for the media files will still be resolved to the url of the global scope!

E.g.
global base url: mystore.com
website base url: mystore.nl
store base url: Use Website
Media urls on mystore.nl are resolved as mystore.com

**Comment by ghost** [comment]
HI @hostep  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#18067 by @hostep in 2.3-develop branch
Related commit(s):
 - [a8f17290363aa157eb1ec77984b3df2201a97ea9](https://github.com/magento/magento2/commit/a8f17290363aa157eb1ec77984b3df2201a97ea9)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#22140 by @hostep in 2.2-develop branch
Related commit(s):
 - [0b0fc92a7e650dec0c94d56e01f7106304a4f67c](https://github.com/magento/magento2/commit/0b0fc92a7e650dec0c94d56e01f7106304a4f67c)

The fix will be available with the upcoming 2.2.9 release.
