### ISSUE TITLE
[Question] Can Order/AbstractMassAction::massAction be made public?

### ISSUE THREAD

**Issue by fooman** [magento/magento2#1597]
Is there any reason why this method 
https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Order/AbstractMassAction.php#L70
needs to be protected? 

If not I'll supply a PR to change it to public to allow plugins to change the massaction outcomes.

**Comment by akaplya** [comment]
I believe we will move this logic outside controller, it's allow to use this service method outside controller and simplify massaction. is this solution suitable for your needs?

**Comment by fooman** [comment]
Sounds great to me. Wil wait and see your progress in this area.

**Comment by maksek** [comment]
Controllers were refactored since time the issue was logged. So no valid anymore, unless @fooman thinks differently, i am closing this ticket.
