### ISSUE TITLE
Create New Integration Key Broken (was working up until recently)

### ISSUE THREAD

**Issue by webcrew-au** [magento/magento2#15977]
### Preconditions
1.  Magento 2.1.6
2.  PHP Version => 7.0.30
3. "composer update" for latest patches

### Steps to reproduce
1.  Create a new Integration (System - > Integrations -> "Add New Integration")
2.  Give integration a "Name"
3.  Choose API access permissions
4.  Enter Password
5.  Choose "Save & Activate"  

### Expected result
1. Integration successfully created with all four keys and tokens
- Consumer Key
- Consumer Secret
- Access Token
- Access Token Secret

### Actual result
1. Integration created BUT with only 2 Consumer keys and no token strings
- Consumer Key
- Consumer Secret
![image](https://user-images.githubusercontent.com/24984106/41198404-eca8e76e-6cbd-11e8-8ebc-23ee88bc24f4.png)

2. Error Message - "A token with consumer ID 12 does not exist"
![image](https://user-images.githubusercontent.com/24984106/41198403-e3083f66-6cbd-11e8-9ce1-6c4be4a32ddb.png)

3. The created Integration is displayed as In Active. Further attempts to Activate display as successful but status does not change.

### Further Information

1. Database contains valid oauth_token record
![image](https://user-images.githubusercontent.com/24984106/41198452-fc475ef6-6cbf-11e8-818b-ac3415a0b1e5.png)
2. Database contains valid oauth_consumer record
![image](https://user-images.githubusercontent.com/24984106/41198460-2082e89e-6cc0-11e8-9493-859942e56d37.png)

**Comment by webcrew-au** [comment]
Hi - Just wondering if anyone has any ideas here???

**Comment by ghost** [comment]
@webcrew-au, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
