### ISSUE TITLE
Product Add / Edit : Advance Settings : Custom Options : Import Options

### ISSUE THREAD

**Issue by smitendra** [magento/magento2#1598]
Hello sir, When I try to click on "Import" button at "Product Add / Edit : Advance Settings : Custom Options : Import Options". It opens a popup, but the popup opens with full hight and the list of products is shown at the bottom of popup. So if the product list is less, so I get full white screen in popup.

**Comment by kokoc** [comment]
@smitendra thank you for contacting us. Seems like I can't reproduce this issue. Got the following picture:
![](http://i.imgur.com/crGLDgP.png)


Could you please provide some screenshots, browser version and information from console?

**Comment by vpelipenko** [comment]
@smitendra, feel free to reopen, if it can be reproduced for you.
