### ISSUE TITLE
Curious composer error

### ISSUE THREAD

**Issue by jonnybradley** [magento/magento2#1599]
Hi Magento people!

I work on an unrelated Open Source project (http://tiki.org) and we run a composer repository using Satis which seems to have stopped working. The error message we're seeing is
```
Scanning packages

  [RuntimeException]
  Could not load package magento/community-edition in https://packagist.org: [UnexpectedValueException] Could not parse version constraint ~2.3 <2.7: Invalid version string "~2.3 <2.7"

  [UnexpectedValueException]
  Could not parse version constraint ~2.3 <2.7: Invalid version string "~2.3 <2.7"
```

After some digging i think i have found the commit that introduced this in case that helps: https://github.com/magento/magento2/commit/548487f7ba70bad4fa32d24b2f9d1d8fba19323a#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L39

Could this be related? And is that really an invalid version string? If so, why has this not caused problems elsewhere?

My thanks in advance,

jonny Bradley

**Comment by kojiromike** [comment]
It's probably worth pointing out that fixing this in a way that would guarantee Satis wouldn't hit it might require changing git history. If you run Satis with `--skip-errors` does it sidestep the issue, or do you hit composer/satis#223?

**Comment by Flyingmana** [comment]
at least it is a valid version constraint https://getcomposer.org/doc/articles/versions.md#tilde

do you use the most recent composer release with your satis?
Anyway, would be a bug in satis, not in magento, so it makes sense you open there an issue, too.

**Comment by jonnybradley** [comment]
Thanks for the replies, i think it was a combination of our satis and/or composer install being out of date and some broken URLs in satis.json which we have now fixed. Sorry to have wasted your time - the (clever) guy that set satis up for us a while ago wasn't around so we were a bit lost for a while there!

Thanks again, sorry to have bothered you and we'll look into the --skip-errors option for the future.
