### ISSUE TITLE
extraneous margin in forms

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15998]
### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. open a form with multiple fields eg the registration form
2. check the margins between fields and field wrappers

### Expected result

1. there should not be any margins on the last fields / field

### Actual result

1. there are still margins on the first field in a fields wrapper

Solution:

```ess
  .fieldset > .fields:last-child > .field {
    .lib-css(margin-bottom, 0px);
  }
```

**Comment by ghost** [comment]
hi @DanielRuf  The fix for this issue is already available in the 2.2-develop branch.

**Comment by DanielRuf** [comment]
@engcom-backlog-nazar which PR / commit fixed it? =)

**Comment by ghost** [comment]
@DanielRuf I cant find the PR/commit but on 2.2-develop branch, the margin set to your solution :)

**Comment by DanielRuf** [comment]
I just need the file in the current develop branch so I can see in the history and blame view which commit applied the change so I can refer to it and close the issue =)

**Comment by ghost** [comment]
here -> https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/luma/web/css/source/_forms.less
 last child set to margin bottom 0px; or it may be like .lib-css(margin-bottom, 0px); ? :)

**Comment by DanielRuf** [comment]
> :last-child > .field

There we would need the margin removal. I guess I'll create a screenshot of the issue to be more clear.

**Comment by ghost** [comment]
@DanielRuf  Hi i understand you, the block of margin-bottom:0px; need to be removed, they do not be a 0px; ?

**Comment by DanielRuf** [comment]
> @DanielRuf Hi i understand you, the block of margin-bottom:0px; need to be removed, they do not be a 0px; ?

No, `.fieldset > .fields:last-child > .field {` needs `margin-bottom: 0px;` which is currently not the cause or I missed something.

**Comment by ghost** [comment]
But you says Expected result ->  there should not be any margins on the **last** fields / field,  and then actual result ->  there are still margins on the **first** field in a fields wrapper. which first or last field ?

**Comment by DanielRuf** [comment]
I will prepare a screenshot then, the code for the selector `.fieldset > .fields:last-child > .field` is needed in general.

**Comment by ghost** [comment]
In my generated files in pub/static/frontend/Magento/blank/en_US/css/style-m.css have -> .fieldset > .fields > .field:last-child {
  margin-bottom: 0;
}

**Comment by DanielRuf** [comment]
I'll check it then.

@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
@DanielRuf We are aware of the fact, that it's 20 days since your request now, but, unfortunately, we can not create an instance without indicating which version you wish to use.

Thanks for collaboration.

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-15998-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-15998-2-2-develop.engcom.dev.magento.com/admin](https://i-15998-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @DanielRuf did you check on test instance ?

**Comment by DanielRuf** [comment]
Not yet, will try to do so today.

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-15998-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-15998-2-2-develop.engcom.dev.magento.com/admin](https://i-15998-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
Seems it is ok now and finally fixed.
