### ISSUE TITLE
Problem with Attribute Sets on import

### ISSUE THREAD

**Issue by Zarina2222** [magento/magento2#15994]
### Preconditions

1. Magento 2.2.4
2. MySQL 5.7.22-0ubuntu0.16.04.1 - (Ubuntu)
3. PHP 7.0.30-0ubuntu0.16.04.1
4. Upgraded from Magento 2.1.2

### Steps to reproduce

1.  Import product using CSV, product's attribute_set_code = 7085 (7085 is name of the attribute set, id is 50)

### Expected result

1. Import succeed 
2. Everything works and import can be done again

### Actual result

1. Import succeed at first time
2. Can't access product page on admin-panel
3. Details tab disappears on product page
4. For some reason, in catalog_product_entity -table, attribute_set_id is now 7085, not 50
5. Can't import again, validation failed
6. If I change attribute_set_id manually back to 50 on database, import and everything else works again, but after import attribute_set_id is again 7085

**Comment by Zarina2222** [comment]
Still having this problem.

**Comment by ghost** [comment]
@Juigeli, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
