### ISSUE TITLE
Fullscreen gallery does not open on mobile devices

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#15992]
### Preconditions

1. Magento 2.2.4
2. PHP 7.0.14
3. MySQL 5.7.17

### Steps to reproduce

1. Install Magento 2.2.4 with Sample Data
2. Open any product detail page with a product that has multiple images on a mobile device (the problem only occurs on some Android devices: Samsung S9, Samsung A3, Sony Xperia Z5)
3. Tap on the image to open fullscreen gallery

### Expected result

1. Fullscreen gallery should open

### Actual result

1. Gallery swipes to the next images. Fullscreen gallery only opens randomly.

**Comment by ghost** [comment]
HI @torhoehn which web browsers you used ? i cannot reproduce by your scenarios steps.

**Comment by torhoehn** [comment]
@engcom-backlog-nazar We tested with Chrome 67 on Android 7.1.1 and can still reproduce this issue.

**Comment by ghost** [comment]
@torhoehn  thank you for your report.
We've acknowledged the issue and added to our backlog.
