### ISSUE TITLE
inconsistent Account Dashboard / My Account title

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#16003]
### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Go to /customer/account/
2. Check the text in the collapsible nav on the left
3. Go to /sales/order/history/
4. Check the text of the account in the collapsible nav on the left

### Expected result

1. it should read "My Account"

### Actual result

1. it reads "Account Dashboard"

**Comment by hitesh-wagento** [comment]
@DanielRuf please See #16009

**Comment by magento-engcom-team** [comment]
@DanielRuf 
Closing, as it seems like you have already fixed it. Thank you.
