### ISSUE TITLE
Payment entity isn't saving

### ISSUE THREAD

**Issue by springimport** [magento/magento2#16014]
### Preconditions
1. Attempt to update the amount of payments.
2. Magento 2.2.3, php 7.1 x64.

### Steps to reproduce
1. Get current order from custom model; set new amount; save.
```php
$payment = $this->getOrder()->getPayment();
$payment->setShippingAmount(123);
$payment->save();
```
OR
```php
$payment = $this->getOrder()->getPayment();
$payment->save();
$payment->setShippingAmount(123);
$payment->save();
```

### Expected result
1. Payment shipping amount is updated.

### Actual result
1. Payment shipping amount isn't updated.
-------------
### Working solution (hack)
```php
$payment = $this->getOrder()->getPayment();
$payment->setShippingAmount(null);
$payment->setShippingAmount(123);
$payment->save();
```

### Problem
Using this:
[\Magento\Framework\Model\ResourceModel\Db\VersionControl\AbstractDb](https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/Model/ResourceModel/Db/VersionControl/AbstractDb.php)
```php
protected function isModified(\Magento\Framework\Model\AbstractModel $object)
{
    return $this->entitySnapshot->isModified($object);
}
```
[\Magento\Framework\Model\ResourceModel\Db\VersionControl\Snapshot](https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/Model/ResourceModel/Db/VersionControl/Snapshot.php)
```php
public function isModified(\Magento\Framework\DataObject $entity)
{
    // ...
}
```
instead of:
[\Magento\Framework\Model\ResourceModel\Db\AbstractDb](https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php)
```php
protected function isModified(\Magento\Framework\Model\AbstractModel $object)
{
    return $object->hasDataChanges();
}
```

**Comment by ghost** [comment]
@springimport, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
