### ISSUE TITLE
Active menu item does not always match last visited category

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#16018]
### Preconditions

1. install Magento 2.2.4 CE
2. PHP 7.1
3. Luma Theme
4. Sample Dataset installed

### Steps to reproduce

1. Make sure the block cache is activate.
2. Flush the caches (`cache:flush`).
3. In the frontend visit the home page.
4. Scroll down and, under hotsellers, click on "Push It Messenger Bag".
5. Breadcrumbs on the product page are "Home > Push It Messenger Bag", which is correct.
6. Now visit the category "Gear -> Bags".
7. Click on "Push It Messenger Bag".

### Expected result

1. Breadcrumbs should be "Home > Gear > Bags > Push It Messenger Bag".

### Actual result

1. Breadcrumbs are "Home > Push It Messenger Bag".

### Debugging results
The menu HTML is cached in the block cache. Therefore the active item is also cached. Now the breadcrumbs JS component gets the breadcrumbs from the menu by looking for the active item. Since there is still no active item in the menu on the second visit of the product detail page, the breadcrumbs also do not reflect the last visited category.

**Comment by ghost** [comment]
Hello @ktruehl The fix for this issue is already available in the 2.2-develop branch
thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sashas777** [comment]
@engcom-backlog-nazar  Can you provide link for commit where it has been fixed, please?

**Comment by ghost** [comment]
@sashas777 I can't find the commit, but also i cannot reproduce this on 2.2-develop branch.

**Comment by sashas777** [comment]
@engcom-backlog-nazar  I run into this issue at the 2.2.4 Magento Cloud.
Any advice where to see code changes what fix it?

Thanks

**Comment by ghost** [comment]
Hi @sashas777  No have no idea where find this commit,  but have no this issue on clean 2.2-dev instance
