### ISSUE TITLE
CMS Page router 

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1601]
In Magento/Cms/etc/frontend/di.xml there is a router for CMS pages. But it does not get invoked since the CMS page requests are get handled by UrlRewrite router under Magento/UrlRewrite/etc/frontend/di.xml.
I also tried removing this CMS router and it worked fine. Is there any reason why this router in place ?

**Comment by buskamuza** [comment]
Hi @bgkavinga , 
Cms and UrlRewrite are different modules. Cms module must provide some default behavior, and UrlRewrite module extends it to more advanced level. Theoretically, if UrlRewrite module could be disabled, everything should continue working w/o it.

**Comment by bgkavinga** [comment]
OK. Thanks
