### ISSUE TITLE
Discoutn for payment method

### ISSUE THREAD

**Issue by nikidexa** [magento/magento2#16016]
Hi, I need to add a new cart rule: If you pay with bank transfer apply a 2% discount .
In Magento 2.1 was possible, but Im suing Magento 2.2.2 
Any suggests?

### Preconditions
1. Magento 2.2.2
2. Luma theme

### Steps to reproduce
1. Apply a new cart rule
2. Apply a discount for payment method
3. If you pay with bank transfer apply a 2% discount 

### Expected result
1.If you pay with bank transfer apply a 2% discount 

### Actual result
1. Cannot apply this rule... payment method is not in the list in magento 2.2.2

**Comment by ghost** [comment]
@nikidexa , thank you for your report.
"Payment method" Cart Price Rule condition is removed in actual Magento 2 versions.

**Comment by riorubiarjo703** [comment]
@engcom-backlog-pb I believe that "payment method" still needed as rule condition. In my case, I use it, I added "payment method" back. But I can't see that ajax is working while condition is fullfilled. #mm18id

**Comment by steffen-wirth** [comment]
@engcom-backlog-pb i also need this as a rule condition - what was the reason for removing it? It is also visible in 2.3 documentation of price rules

**Comment by rommelfreddy** [comment]
@engcom-backlog-pb i need this too. is it planed to be added again?

**Comment by efiiskandar** [comment]
Why is this rule condition removed? Will this be added again?

**Comment by mauricehermans** [comment]
@engcom-backlog-pb any news on this?

**Comment by johnny-longneck** [comment]
I am also looking for this feature. Any news?

**Comment by mauricehermans** [comment]
Nope ☺

Van: johnny-longneck <notifications@github.com>
Beantwoorden - Aan: magento/magento2 <reply@reply.github.com>
Datum: donderdag 1 augustus 2019 om 14:52
Aan: magento/magento2 <magento2@noreply.github.com>
CC: Maurice Hermans | Nutrition Company <maurice@nutritioncompany.nl>, Comment <comment@noreply.github.com>
Onderwerp: Re: [magento/magento2] Discoutn for payment method (#16016)


I am also looking for this feature. Any news?

**Comment by rommelfreddy** [comment]
Have a look at this repository. this will fix that.
https://github.com/MagestyApps/magento2-fix-discount-rules
I use this also for a customer of mine. it works pretty fine.

maybe someone wants to create a pull request with the code from MagestyApps (please get in contact with them)
