### ISSUE TITLE
Magento Setup: the page isn't redirecting properly

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16013]
### Preconditions

1. Linux Mint 18 Sarah (local)
2. Linux CentOS Linux release 7.5.1804 (dev)
3. Firefox 60.0.2 (64-bit)
4. Apache 2.4.18
5. PHP 7.1.17

### Steps to reproduce

1. Download Magento-CE-2.2.4-2018-05-01-09-28-45
2. extract to target directory
3. `$ sudo find . -type f -exec chmod 644 {} \;`
4. `$ sudo find . -type d -exec chmod 755 {} \;`
5. `$ sudo chmod -R 777 var/`
6. `$ sudo chmod -R 777 generated/`
7. Go to mage2.local site and get error:

`The page isn't redirecting properly`

### Expected result

I should be able to run through the setup installer

### Actual result

`The page isn't redirecting properly`

**Comment by ananth-iyer** [comment]
@TreyTaylor1997 
Please try below link:
http://mage2.local/index.php

If above link works then apache **mod_rewrite** module is disabled in your local.

**Comment by ghost** [comment]
@Ananth747 

It didn't work - and mod_rewrite is enabled in my local

**Comment by Ananth747** [comment]
Then I can't give expected solution by texting here and end up waste your time unless you have any open option to help you out.

Please share the screenshot the issue here.

**Comment by Ananth747** [comment]
Please share the screenshot the issue here.

**Comment by ananth-iyer** [comment]
Please share the screenshot of the issue here.

**Comment by ghost** [comment]
![error](https://user-images.githubusercontent.com/8513738/41337516-52da11b8-6ee7-11e8-9678-e3e106088e9f.png)

error attached

**Comment by ananth-iyer** [comment]
Change the website url to magelocal.com because in url after last dot it must be maximum 3 letters.

**Comment by ghost** [comment]
@Ananth747 that can't be true, or how else would .co.uk magento sites work? it can't all just be .com and if so this is a huge design flaw that must be fixed.. .local is the standard for a localhost website.. why would anyone have .com for a localhost website?

**Comment by ananth-iyer** [comment]
Hi, please try using only **.com** or **.co** and setup separate domain in your local, using:
- Without Magento 2 files
- Just index.php - with echo "hello world"; (without .htaccess file)
Q1. Do you see "hello world" in your browser?
- Add Magento 2's .htaccess files in this directory (without complete Magento 2 files)
- Now test with index.php then test without index.php
Q2 Do you see "hello world" in 1st & 2nd test case?

This will help us understand what actually apache server doing.

**Comment by ghost** [comment]
@Ananth747 

Q1: Yes, I have a whole ton of localhost websites all using .local and working, using symfony4, to wordpress to OOP-based code with bespoke frameworks.

Q2: yes it works with and without the .htaccess

**Comment by ghost** [comment]
can confirm domain is no issue:

![image](https://user-images.githubusercontent.com/8513738/41467007-a005b422-709c-11e8-8188-efe70334b898.png)

**Comment by ghost** [comment]
Hey,

any progress on this? :)

Thanks,

**Comment by ghost** [comment]
Would it help if I post my vhost / htaccess conf files?

**Comment by ananth-iyer** [comment]
Can you check Network tab in Firefox? Do you see http to https or https to http redirects?
Rename `.htaccess` in **magento root** & **setup** directory & check what happens?

Check it in Private Windows of Firefox.

Also check all required php modules are enabled or not:
https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html#required-php-extensions
Using below you can check enabled php modules:
`php -m`

**Comment by ghost** [comment]
Hey,

Checked in tab, nothing is redirecting from http -> https (or vice versa)
Renamed .htacess -> no success

I've already checked - and all are there

**Comment by ghost** [comment]
Hey,

any more on this?

Thanks,

**Comment by ghost** [comment]
@TreyTaylor1997, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by ghost** [comment]
@engcom-backlog-pb  which it is - the core issue is that base install of Magento version doesn't work in Linux Mint.

**Comment by ghost** [comment]
@TreyTaylor1997 it is obvious you have misconfigured server. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice.

**Comment by ghost** [comment]
@engcom-backlog-pb I followed the documentation on Magento 2 site - so I'm not sure where it goes wrong?

**Comment by ananth-iyer** [comment]
@TreyTaylor1997 It is right the server configuration is missing something that needs to find out. Can we have remote desktop to resolve it?

**Comment by ghost** [comment]
@Ananth747 indeed - but how can I debug? I've checked modules - all installed, I've set up my vhost so it works with PHP-FPM, checked all the server conf and everything seems ok .. and unfortunately not as it's an internal CentOS server - so no pub access - can post conf files if requested?

**Comment by ananth-iyer** [comment]
@TreyTaylor1997 
Please check & fix the problem from below link:
https://stackoverflow.com/questions/25520212/this-webpage-has-a-redirect-loop-in-magento

**Comment by ghost** [comment]
@Ananth747 that's not applicable to me, it doesn't get passed setup, it has no core_config_data to read from ..

**Comment by ghost** [comment]
@Ananth747 @engcom-backlog-pb 

I just succesfully installed Magento2 using command line - and everything else works, just the /setup url had the error - so doesn't look to be fully server conf issue, rather than a /setup path issue..

**Comment by MedusaDelft** [comment]
I do have the same issue when trying to get the login page.
Logged in (admin) 7 days ago perfectly (shop in development) and now I try again and get the error 'The page isn't redirecting properly'. This is not the first time.
Last time, only a full reinstall did the trick, but that is not an option now.

Magento 2.2.6 / PHP 7.1 / Apache / Ubuntu

Seems to be a FireFox problem (63.0.1) as Chrome does not have this problem. Strange.

**Comment by almr** [comment]
Hello Everyone,

I’m getting same redirecting issue on second level categories.
Did anyone get this resolved?
Magento Version: 2.2.7

Thanks!

**Comment by njecom** [comment]
I fixed this issue on my local fresh magento 2 installation by manually entry in the 'core_config_data' table 
web/cookie/cookie_doman = domain.local 
Hope it help someone. 
Thanks

**Comment by abukatar** [comment]
Found here https://devdocs.magento.com/guides/v2.4/install-gde/composer.html#install-magento
For Magento 2.4 you **must** use the command line to install it.
