### ISSUE TITLE
Design Configuration Not Saving showing 404 page on sub-directory

### ISSUE THREAD

**Issue by sara-sadika** [magento/magento2#16025]
## Preconditions
1. Magento 2.2.4
2. PHP 7
3. Sub-directory setup

## Steps to reproduce
1. Setup sub-directory magento 2 mine site/buy/
2. Install a supported theme for Magento 2. I have install novetty theme
3. Update theme using ssh access and putty
4. Trying to change the theme from Design Configuration section 
5. Showing 404 page from root site.

## Details
I have install magento 2.2.4 on my site sub-directory. Every thing was properly installed and worked. But when I install a new theme, its was setup properly. I try to change the from the default one to new theme its showing 404 page. Example are given. Could you please help me fix it. 

![1](https://user-images.githubusercontent.com/40179168/41247271-55cda5b0-6dcf-11e8-9c49-c6c89e96123d.png)
![2](https://user-images.githubusercontent.com/40179168/41247270-558c0f56-6dcf-11e8-94f9-6ec9ef69e618.png)

**Comment by ghost** [comment]
@sara-sadika, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
