### ISSUE TITLE
After installing new Theme Front-end goes blank white with no error being displayed.

### ISSUE THREAD

**Issue by mestadev** [magento/magento2#16040]
I am working in Magento in my localhost using wamp installed in ubuntu OS. I was working with default theme luma. I have done all the basic changes in it while working in default theme Luma and all was working fine as expected. But when I installed a theme it shows me a blank page with white background that has no errors or message displayed. Please help me with the issue. I am using Magento 2.2.4 with PHP 7.1 and mysql 14.14 ubuntu 18.04<!---

**Comment by magento-engcom-team** [comment]
Hi @mestadev 
Unfortunately we can not provide any guidance with the issues which we can not reproduce. Please update issue report to include more details and reopen of the issue persist. Closing this ticket for now.
