### ISSUE TITLE
Theme type(s) keep resetting to TYPE_VIRTUAL (1)

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#16049]
### Preconditions

1. Magento 2.2.4
2. PHP 7.1.18
3. MySQL 5.7.22

### Steps to reproduce
1. In the theme table, there is a column called type. This relates to ThemeInterface::TYPE_VIRTUAL (1), TYPE_PHYSICAL (0)
2. After viewing the front end of the website, the values keep changing to TYPE_VIRTUAL (1)
3. Previously they were set as TYPE_PHYSICAL (0) during database conversion from Magento 1
4. All our themes exist in app/design/frontend/(vendor name)/(theme)
5. An example of theme definition:
```
<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>xyz</title> <!-- your theme's name -->
    <parent>Magento/blank</parent> <!-- the parent theme, in case your theme inherits from an existing theme -->
    <media>
        <preview_image>media/preview.jpg</preview_image> <!-- the path to your theme's preview image -->
    </media>
</theme>
```

### Expected result
1. type field to stay at 0 (TYPE_PHYSICAL)

### Actual result
1. type field changes to 1 (TYPE_VIRTUAL). This causes our header and footer to not display.

This is a major bug for us.

**Comment by Jakhotiya** [comment]
A theme is converted to virtual theme when a "theme record" EXISTS in the database but theme files are not found in app/design/frontend/VendorName/theme. So this can happen if you have a migrated database from m1. You set up an m2 instance with it and request a page before having your theme files in place. In any scenario where DB records exist but files aren't in place (or in some situations not readable) a theme will be converted to Virtual theme.

**Comment by cscd98** [comment]
@Jakhotiya The theme files are in place before setup, before migration from m1.

How can I debug this issue?

**Comment by engcom-backlog-nickolas** [comment]
@craigcarnell, thank you for report. However, problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by cscd98** [comment]
@Jakhotiya This isn't a data migration issue. If you have 2 different magento installations pointing at the same database (in our case a front end website, and a business internal website), it will set your themes to type virtual as they don't exist in the other repository.
