### ISSUE TITLE
Cannot validate class for a custom attribute when create a product in back-end

### ISSUE THREAD

**Issue by lucbaojang** [magento/magento2#1604]
I created a custom attribute with the input type for products in the back-end, and add new class for it. It called "validate-custom-attribute".

I also add this javascript codes but when I save product, it is still passed. 

How can I validate it?

Validation.add("validate-custom-attribute", "Input not correct", function(v) {
                               parten=/^(\d\.{0,1},{0,1})+$/;
                                return (parten.test($("gift_dropdown").value));
                            });

**Comment by kokoc** [comment]
@lucbaojang thank you for contacting us.

* First of all you need to declare a validator. Please use `lib/web/mage/validation.js` as example.
* Then, specify validator in `data-validate` attribute. Example: `data-validate="{required:true,'validate-greater-than-zero':true}"`

**Comment by lucbaojang** [comment]
@kokoc: amazing! Thank you very much. You can close it now.

**Comment by alankent** [comment]
Sorry, by "amazing" were you referring to @kokoc or the capability?  ;-)
