### ISSUE TITLE
Unable to see config menu items on smaller screen size

### ISSUE THREAD

**Issue by rob3000** [magento/magento2#1605]
On a smaller screen sizes I'm unable to see some of the admin menu items such as the `Indexer` and `backup setup wizard`.
![screenshot from 2015-08-03 16 20 37](https://cloud.githubusercontent.com/assets/4905586/9033637/9f9410a4-39fb-11e5-827a-655060b9140b.png)

Screen Resolution: 1366 x 768
Branch: Develop & Master

**Comment by guz-anton** [comment]
Yes, we already have reported and fixed issue MAGETWO-40279 in internal tracker.
I can notice here when it will be delivered.

**Comment by guz-anton** [comment]
Hi Mr. Shepherd,
We have delivered fix. You can checkout out and close issue in case all is done.
