### ISSUE TITLE
GraphQL sample queries from devdocs not working on default installation

### ISSUE THREAD

**Issue by RMcLeod79** [magento/magento2#16060]
### Preconditions

1. Install 2.3-develop branch
2. Install 2.3-develop branch of sample data

### Steps to reproduce

1. Copy a sample query from the devdocs https://devdocs.magento.com/guides/v2.3/graphql/search-pagination.html
2. Get an admin authorization token by posting an admin username and password in JSON format to https://i-16060-2-3-develop.engcom.dev.magento.com/index.php/rest/V1/integration/admin/token
3. Post the query as JSON to https://i-16060-2-3-develop.engcom.dev.magento.com/graphql in the headers of the request set Authorization to Bearer + the token you generated and set Store to default.

### Expected result

1. Receive a JSON response with data that matches the query you made

### Actual result

1. Receive a JSON message containing an error.
```
{
    "errors": [
        {
            "message": "Internal server error",
            "category": "internal"
        }
    ]
}
```
2. Error logged in var/log/exception.log
```
[2018-06-12 11:46:10] main.CRITICAL: Report ID: graph-ql-5b1fb282a4a82; Message: Unable to unserialize value. {"exception":"[object] (Exception(code: 0): Report ID: graph-ql-5b1fb282a4a82; Message: Unable to unserialize value. at /Users/richard/Sites/magento2/lib/internal/Magento/Framework/GraphQl/Exception/ExceptionFormatter.php:59, InvalidArgumentException(code: 0): Unable to unserialize value. at /Users/richard/Sites/magento2/lib/internal/Magento/Framework/Serialize/Serializer/Json.php:39)"}
```

**Comment by RMcLeod79** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @RMcLeod79. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @RMcLeod79, here is your [Magento instance](https://i-16060-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16060-2-3-develop.engcom.dev.magento.com/admin](https://i-16060-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by RMcLeod79** [comment]
The problem seemed to be with the app I was using to send the query Postman. Worked fine when using the chromeiQL plugin for Chrome.
