### ISSUE TITLE
Calculate discount before tax.

### ISSUE THREAD

**Issue by Edward-Nguyen** [magento/magento2#1606]
Hi every body,

I'm creating a module which help me add a discount price on cart but I don't know how I can calculate discount before tax.
Ie: Original price of a product is $100, tax is 20%, so grand total is $120
If I add a discount is $50, tax will be $10 then grand total is $60.
Any one help me!

Thank you!

**Comment by blankapham** [comment]
@vpelipenko can you help me? I have a problem same with @vermilion0012.
I want to recalculate tax when add a custom discount before tax. 
Thanks,

**Comment by Edward-Nguyen** [comment]
Hi blankapham,

I have found a pretty solution.
You can set discount amout for quote address item ($item->setDiscountAmount($amout)).
Then tax will be apply after minus discount amout. 
Hope it is useful for you.

Thanks

**Comment by Edward-Nguyen** [comment]
I did it but I will cause an error for invoice.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
