### ISSUE TITLE
Need to add a dynamic url generated script tag into head

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#1607]
Need to add a dynamic url generated script tag from code and add them into head part of whole website.
Please help me how to do that into magento2.

**Comment by vpelipenko** [comment]
@ankursachdeva11, what is dynamic url generated script tag? Do you want to have script tag with different sources depend on some conditions?

**Comment by ankursachdeva11** [comment]
@vpelipenko, i have to add script tag whose url will be created according to the values given in system configuration.

**Comment by sivaschenko** [comment]
@ankursachdeva11, could you please provide more details/requirements according to mentioned functionality. Maybe an example?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
