### ISSUE TITLE
Why is country_id sortOrder hard coded with an override in module-checkout???

### ISSUE THREAD

**Issue by treii28** [magento/magento2#16078]
Magento CE v2.2.2

In the vendor code for module-checkout hard-code overrides the country_id sortOrder. I just wasted 3 hours trying to figure out how to get the country to show up (properly and in a way that makes logical sense) above the region_id since the region option list is dependent upon the country selected. So why is this hard-code over-ridden??? Not only does the default order confuse customers, but it doesn't make any sense. Then to find out this is hard coded?  (i.e. you cannot change the order by modifying the value in customer_eav_attribute table sortOrder for the country_id field)

vendor/magento/module-checkout/view/frontend/layout/checkout_index_index.xml

    225                                                                     <item name="country_id" xsi:type="array">
    226                                                                         <item name="sortOrder" xsi:type="string">115</item>
    227                                                                     </item>

**Comment by ghost** [comment]
@treii28, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
