### ISSUE TITLE
Unable to read response, or response is empty when "Save product", "Save product & duplicate" and "Save and close"

### ISSUE THREAD

**Issue by lundco** [magento/magento2#16088]
When im trying to save a product, it returns an error. The product itself is saved, but i cant duplicate it. It says 

> Unable to read response, or response is empty

In my exception.log it gives this:

> main.CRITICAL: Unable to read response, or response is empty {"exception":"[object] (Zend_Http_Client_Exception(code: 0): Unable to read response, or response is empty at /var/www/clients/client1/web1/web/vendor/magento/zendframework1/library/Zend/Http/Client.php:1093)"} []

Have no idea why this problem has come. The shop has worked until now.

### Preconditions
Magento version: 2.2.3
Nginx server
PHP7

### Steps to reproduce
1. Save product

### Expected result
Expect it to only show "You saved the product.". And if it was Duplicate it should create a new product, and if it is close it should return to product listing.

### Actual result
When pushing any of the Save options, it always reuturns to the product page in admin, giving this error:
<img width="1384" alt="screen shot 2018-06-13 at 11 30 43" src="https://user-images.githubusercontent.com/31758297/41342782-5c5f5b88-6efd-11e8-86ca-090f5c0d330c.png">

**Comment by ghost** [comment]
@lundco, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
