### ISSUE TITLE
Problem with module dependencies on setup scripts

### ISSUE THREAD

**Issue by mlopes** [magento/magento2#1608]
Hi,

I'm having the following issue:

There's a composer installed 3rd party module which sets up some data from its `InstallData` setup script. I have a local module that is trying to act on the data set by the 3rd party extension, from  my extension's `UpgradeData` setup script.

On my extension's `etc/module.xml` file I have the following code:

```
<module name="My_Extension" setup_version="1.3.0">
    <sequence>
       <module name="ThirdParty_Extension"></module>
    </sequence>
</module>
```

But my setup script fails, because it's running before the 3rd party's extension, and therefore the data still doesn't exist. Is there a way to make my extension setup script run after the 3rd party's one?

Thanks,
Marco Lopes

**Comment by buskamuza** [comment]
@mlopes , looks like you do everything correctly. We created an internal ticket to investigate why this issue may exist - MAGETWO-41057

**Comment by buskamuza** [comment]
@mlopes , could you solve the issue?

**Comment by mlopes** [comment]
I stopped being able to reproduce it at some point, so I think it got solved somehow.
