### ISSUE TITLE
Error while creating new product

### ISSUE THREAD

**Issue by sambalay** [magento/magento2#16095]
### Preconditions

1. magento 2.2.2

### Steps to reproduce

1. catalog ->. products -> add new product

### Expected result

1. Should show the fields for add new product

### Actual result

1. SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_value.value' in 'field list', query was: SELECT `entity`.`sku`, `product_entity`.`entity_id` AS `product_id`, `attribute`.`attribute_code`, `entity_value`.`value` AS `value_index`, `attribute_label`.`value` AS `super_attribute_label`, IFNULL(option_value.value, default_option_value.value) AS `option_title`, `default_option_value`.`value` AS `default_title` FROM `newlu_catalog_product_super_attribute` AS `super_attribute` INNER JOIN `newlu_catalog_product_entity` AS `product_entity` ON product_entity.entity_id = super_attribute.product_id INNER JOIN `newlu_catalog_product_super_link` AS `product_link` ON product_link.parent_id = super_attribute.product_id INNER JOIN `newlu_eav_attribute` AS `attribute` ON attribute.attribute_id = super_attribute.attribute_id INNER JOIN `newlu_catalog_product_entity` AS `entity` ON entity.entity_id = product_link.product_id INNER JOIN `newlu_catalog_product_entity` AS `entity_value` ON entity_value.attribute_id = super_attribute.attribute_id AND entity_value.store_id = 0 AND entity_value.entity_id = entity.entity_id LEFT JOIN `newlu_catalog_product_super_attribute_label` AS `attribute_label` ON super_attribute.product_super_attribute_id = attribute_label.product_super_attribute_id AND attribute_label.store_id = 0 LEFT JOIN `newlu_eav_attribute_option_value` AS `option_value` ON option_value.option_id = entity_value.value AND option_value.store_id = 2 LEFT JOIN `newlu_eav_attribute_option_value` AS `default_option_value` ON default_option_value.option_id = entity_value.value AND default_option_value.store_id = 0 WHERE (super_attribute.product_id = 130) AND (attribute.attribute_id = '')

**Comment by Leandry** [comment]
Could not reproduce on clean magento 2.2.2 instance

**Comment by UnDeAdYeTii** [comment]
Reproducible on my system.

Why is it referencing a column that doesn't exist though?

**Comment by rushko** [comment]
Check if there's '.' (period sign) in front of the attribute option: something like '.1 size'.  Removing the period fixed the problem for me.

**Comment by yohanespradono** [comment]
I am getting this issue too after upgrading from 2.1.9 to 2.2.7
