### ISSUE TITLE
Search second half of SKU doesn't return article

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#16092]
### Preconditions

1. Magento 2.1.11
2. Attribute SKU has search priority 10

### Steps to reproduce

1. Search for 00XYZ works (SKU 00XYZ)
2. Search for only XYZ doens't find this article, but user often search without the 00 at the beginning of the SKU

### Expected result

1. Article should be found with search for XYZ too

### Actual result

1. No article found

**Comment by ghost** [comment]
@flipflap, thank you for your report.
Unfortunately, this is not a bug, this is a feature of the search realization in Magento 2. We cannot change it because it will break compatibility with some supported databases.
