### ISSUE TITLE
Admin login fail if store code in url enabled

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#1609]
Magento2 / 1.0.0 (+ Sample Data)
I've created second Store View, set "Add Store Code To URL" in "General/Web" Section,
and now I can't login to the admin area. No message, no error (developer mode enable / cache disable / cookies were cleaned) - Current URL is http://m202.local/admin/admin/system_config/edit/section/web/key/9f952380b1ef6dd2b30b69fdc4d8672d972fdc3b076c700a0b88abd8892dff0d/ and i view login form only: http://prntscr.com/80ciq2
P.S. Firebug show no errors.

**Comment by monkeysee** [comment]
Looks like same issue as #1143

**Comment by piotrekkaminski** [comment]
internal ticket: MAGETWO-35679

**Comment by sshrewz** [comment]
MAGETWO-35679 has been fixed.  Feel free to reach out to us if you encounter further issues.
