### ISSUE TITLE
On Product Save tab heading should be highlighted with an error icon. 

### ISSUE THREAD

**Issue by santoshsupport3** [magento/magento2#16109]
### Preconditions

1.  Magento 2.2.3 , PHP 7.0.30 , MYSQL 5.7.18 
2. 

### Steps to reproduce

1.  On Saving New or Existing Product If Tab has Required Fields On Save Tab Is not being highlighted with error Icon.
2. 
3. 

### Expected result

1. The tab heading should be highlighted with an error icon. So one can know in which tab the problem resides. 
![should be the result on validation error](https://user-images.githubusercontent.com/40258575/41394865-77dbc454-6fa3-11e8-8d31-b70528e2aacc.png)

### Actual result

1. Nothing happens to the tab heading but fields show the validation errors.
![screenshot-2018-6-14 new product products inventory catalog magento admin](https://user-images.githubusercontent.com/40258575/41394689-d4dd338c-6fa2-11e8-8e92-ec7d140aa72a.png)

![screenshot-2018-6-14 new product products inventory catalog magento admin](https://user-images.githubusercontent.com/40258575/41394936-bfa66834-6fa3-11e8-8afb-4d96e4f32e43.png)

**Comment by ghost** [comment]
Hi @santoshsupport3  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @santoshsupport3 

While trying to fix the issue we were unable to reproduce it with 2.2.5 anymore. Please reopen if problem still persists for you.

Thanks
