### ISSUE TITLE
Magento 2.2.4 :menu is not showing

### ISSUE THREAD

**Issue by Patelcc** [magento/magento2#16107]
I was found that issue related to **Varnish Cache** 

If we select **Store -> Configuration -> Advanced -> System -> Full page cache -> Caching Application** Set to **Varnish Cache** then menu are not appear in home page other then appear on all pages . 

see below attached screen-shoot

![megamenu](https://user-images.githubusercontent.com/40203855/41290357-44d3291a-6e6a-11e8-8531-163244829e77.png)

But on other all pages it's appear.

![login-menu](https://user-images.githubusercontent.com/40203855/41394895-48f4c570-6fc9-11e8-9909-644874c4c032.png)

I checked and found that JS is not showing in inspect element on home page, so reason for this menu is not displaying.

in inspect element on home page showing like this
`<esi:include src="http://127.0.0.1/rb-ee/page_cache/block/esi/blocks/%5B%22catalog.topnav%22%5D/handles/WyJkZWZhdWx0IiwiY21zX2luZGV4X2luZGV4IiwiY21zX3BhZ2VfdmlldyJd/"></esi:include>`

Also If we disable full page cache from admin then menu is displaying perfectly, this problem is occurred because code(Layout) are not **Cacheable**  due to some inappropriate reason.

Don't say that it is occurred because **Varnish Cache** is not integrated in  local environment , if it is valid reason then all other pages also don't appear menu.

**Comment by ishakhsuvarov** [comment]
Hi @Patelcc 

Yes, this may happen if you enable varnish in configuration but not run it on the environment you are testing on. 
`<esi:include>` is only processed by Varnish cache server, and not magento.

**Comment by ishakhsuvarov** [comment]
> Don't say that it is occurred because Varnish Cache is not integrated in local environment , if it is valid reason then all other pages also don't appear menu.

Menu would appear, in your case, only on the pages which are not cacheable, like Customer Login, Customer Dashboard, etc.

**Comment by magento-engcom-team** [comment]
@Patelcc 
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by Patelcc** [comment]
@ishakhsuvarov Yes i know `<esi:include>` is only processed by Varnish cache server, and not magento but magneto give default setting to select Varnish cache and also Magento Cloud Enterprise Edition need to must compatible with varnish cache.

**Comment by TheTangro** [comment]
@magento-engcom-team Problem is caused by the bug in Magento_Reviews (\Magento\Review\Block\Product\View\ListView::_prepareLayout). The code written in the given method depends on the Registry item. This method is called whenever the block is rendered or not; when the Registry item is missing, it causes an error when esi tags are not processed. Error persist on last github magento version

**Comment by Franciscof-Serfe** [comment]
Hi @Patelcc
  I am running with the same error. QuickFixed by removing ttl="3600" from the Topmenu block of the layout path:

/vendor/magento/module-theme/view/frontend/layout/default.xml

Line 76: <block class="Magento\Theme\Block\Html\Topmenu" name="catalog.topnav" template="Magento_Theme::html/topmenu.phtml" ttl="3600" before="-"/>

The default varnish setting is 84600 and this block is being refreshed by 3600.

If you have HTTPS activated I think that could be the origin of the issue with Varnish. 

I hope this approach helps.
Regards,
Francisco
