### ISSUE TITLE
Magento 2.2.4 Temando_Shipping stops MultiShipping from functioning properly?

### ISSUE THREAD

**Issue by dyuk1987** [magento/magento2#16104]
### Preconditions

1. Magento **CE 2.2.4** without demo data
2. Temando_Shipping module **enabled by default** but **not configured and enabled** as a shipping method
3. **Allow Shipping to Multiple Addresses** is enabled
4. A few simple, downloadable and virtual products are created
5. Amazon_Core, Klarna_Core, Amazon_Login, Amazon_Payment, Klarna_Ordermanagement, Klarna_Kp, Dotdigitalgroup_Email, Shopial_Facebook and Vertex_Tax modules are **disabled**

### Steps to reproduce

1. Register as a user
2. Add at least 2 shipping addresses
3. Add a few products to the cart (a mix of virtual, downloadable and simple)
4. Proceed to shopping cart and checkout with multiple shipping addresses
5. Click **Update Qty & Addresses**
6. The following error appears:
> Data saving problem 
7. Updates on quantities and shupping addresses are rolled back

### Expected result

The updates on quantities and shipping addresses should have been saved properly.

### Actual result

An error occurred instead
![image](https://user-images.githubusercontent.com/28293734/41390997-d549a40e-6fca-11e8-982e-22474af64165.png)

### Other observations
1. Tha above error occurs whenever there are virtual or downloadable products (to be more precise, for products where shipping is not applicable) in the cart. 
According to the logs below:
`main.CRITICAL: Exception message: Notice: Undefined index: address in <WEB_ROOT>/vendor/temando/module-shipping-m2/Plugin/Multishipping/Checkout/MultishippingSavePlugin.php on line 151`
It seems to me that the plugin could not handle the request properly when there are products without a shipping selection drop-down.

2. When the Temando_Shipping module is disabled, the error goes away.
**HOWEVER,** when the module is disabled, when I proceed to checkout (normally instead of multiple shipping addresses), I got the following error now:
![image](https://user-images.githubusercontent.com/28293734/41391751-1ec1dbb6-6fcf-11e8-926a-3b96bb5a98ce.png)

**Comment by speedupmate** [comment]
this relates to https://github.com/magento/magento2/issues/15968 . Best option is to : php bin/magento m:di Temando_Shipping if it is not used , then js mappings won't be loaded.

**Comment by dyuk1987** [comment]
@speedupmate Thanks for your reply. But what about the second issue I have pointed out in the section **Other observations**?

**Comment by speedupmate** [comment]
get a full trace on this issue and see if it is related to Temando at all

**Comment by marcelo-monteiro** [comment]
Hi @dyuk1987 
Like @okorshenko replied, in #17131, this issue is caused by a vendor extension. Please contact the  vendor support team for the assistance:
https://developer.temando.com/soap/index.html or email them tsupport@temando.com
