### ISSUE TITLE
Frontend Apps Specific CMS Pages Targeting Feature Request

### ISSUE THREAD

**Issue by TRMMarketing** [magento/magento2#1611]
Not exactly sure where I should submit this but it would be very beneficial to be able to target Frontend Apps (Old widgets) to specific CMS pages. At present you can only target all cms pages, homepages, no route and no cookie cms pages.

This would add a lot of additional power for shop owners to create campaign specific pages without the need to know how to use the Layout Updates.

**Comment by tkacheva** [comment]
you can do it now via WYSIWYG on specific CMS Page. Plugin is integrated with magento widgets, image library and variables. We are planning to update  WYSIWYG  soon so it will be even easier
