### ISSUE TITLE
klarna-module-ordermanagement-4.1.3.0 checksum verification failed

### ISSUE THREAD

**Issue by piotrjozwiak** [magento/magento2#16129]
### Preconditions

1. PHP 7.0
2. NGINX 
3. Composer 1.6.5

### Steps to reproduce
1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2

### Expected result
1. Successfull fresh Magento 2.2.4 install
### Actual result
1. Exception while downloading dependency module: 

```
Installing klarna/module-ordermanagement (4.1.3): Downloading (100%)         
                                                                                                                                                                            
  [UnexpectedValueException]                                                                                                                                                
  The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/klarna/module-ordermanagement/klarna-module-ordermanagement-4.1.3.0.zip) 
```

**Comment by wardominic** [comment]
Am having the same issue attempting to upgrade

**Comment by quisse** [comment]
Temporary if you don't need that module you can remove (replace) it by adding this to your composer.json
**I was updating the installation.**
```
    "replace": {
        "klarna\/module-ordermanagement": "*"
    },
```

[credits](https://www.integer-net.com/removing-unused-core-modules-from-magento-2-the-right-way/)

**Comment by bap14** [comment]
Just to be clear, a `403 Forbidden` error is returned when you try to download the file:

```
GET /archives/klarna/module-ordermanagement/klarna-module-ordermanagement-4.1.3.0.zip HTTP/1.1
Host: repo.magento.com
Authorization: Basic bXlwdWJrZXk6bXlwcml2a2V5

HTTP/1.1 403 Forbidden
Date: Thu, 14 Jun 2018 17:20:31 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: nginx
Cache-Control: no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=15984000
```

**Comment by ccasciotti** [comment]
Same issue for me, upgrading from 2.2.2 to 2.2.4.
Composer stop on `klarna/module-ordermanagement` installation and removes some php files from `bin/` and `app/` folders, like `bin/magento` e `app/bootstrap.php`. 
I have to revert composer.json and lock to previous versions (2.2.2 for me), re-run composer install to restore them

**Comment by careys7** [comment]
For us, the workaround mentioned here doesn't work: https://github.com/magento/magento2/issues/16129#issuecomment-397289956

I receive this:

```
^@^@Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/product-community-edition 2.2.4 -> satisfiable by magento/product-community-edition[2.2.4].
    - magento/product-community-edition 2.2.4 requires klarna/module-ordermanagement ^4.1.2 -> no matching package found.
  Problem 2
    - Installation request for magento/product-enterprise-edition 2.2.4 -> satisfiable by magento/product-enterprise-edition[2.2.4].
    - magento/product-enterprise-edition 2.2.4 requires klarna/module-ordermanagement ^4.1.2 -> no matching package found.
```

**Comment by quisse** [comment]
@careys7 Are you updating magento or making a fresh install? I was upgrading. (updated original comment)

**Comment by careys7** [comment]
@quisse We have a running version of 2.2.4. `composer install` stopped for some of our team yesterday, and has worked its way through to CI (as caches have started to expire I guess)

**Comment by quisse** [comment]
@careys7 Can you check if the module is enabled somewhere? Here one of our team members updated magento in a project to 2.2.4 and i was pulling & installing the latest version of the project and adding that line & run composer install again solved the checksum issue...

**Comment by aingham** [comment]
@quisse This workaround worked for me. I was doing a fresh install on a free trial.

**Comment by simonmaass** [comment]
having the same issue

**Comment by webspeaks** [comment]
Having same issue on Magento Cloud v 2.2.4

**Comment by simonmaass** [comment]
@quisse workaround worked for me aswell - if u dont use klarna...

**Comment by PieterCappelle** [comment]
Can confirm this issue, having the same problem when trying to install 2.2.4.

**Comment by munkhulzii** [comment]
i had same issue, but now it seems to work again.

**Comment by siju-corra** [comment]
I had the same issue, and after a composer update I got it working fine.

**Comment by quisse** [comment]
The issue doesn't appear anymore for me neither, so i'll close this for now.

**Comment by arunu** [comment]
Getting the same issue on Magento Cloud v 2.2.4

**Comment by quisse** [comment]
Have you tried flushing the composer cache?

**Comment by Swahjak** [comment]
Getting the same issue on a Gitlab CI without composer cache

Edit: The solution in comment  https://github.com/magento/magento2/issues/16129#issuecomment-397463615 does work for me.

**Comment by ccasciotti** [comment]
I can confirm that issue is back again without composer cache, the only working solution is in the comment made by @quisse

**Comment by yyevgenii** [comment]
The klarna/module-ordermanagement package was re-uploaded to the Marketplace (the package contents is the same, but file meta data differs, that's why the checksum has been changed). Magento has identified an issue and prevent it from happening this in the future, but now to solve it you have to run:
* `composer clearcache`
* `rm -rf vendor/klarna/module-ordermanagement`
* `composer update`

You can't update just a single package because it isn't in the require section, that's why you have to run `composer update`. The version of the package remains the same, so composer won't download it again, if the package is already installed, that's why you have to remove the package from the vendor folder. Clear the composer cache just in case.

**Comment by yyevgenii** [comment]
@magento-engcom-team could you please mark this issue as solved? Thanks!

**Comment by hostep** [comment]
@yyevgenii: if a package is re-uploaded and the hash changes it **should always** get a new version. The way this was handled right now is just bad management. Hope this won't happen anymore in the future...

**Comment by yyevgenii** [comment]
@hostep the team responsible for this has found the process in a workflow which may cause issue like this one. they said that it'll be reworked and the issue shouldn't happen again.

**Comment by mmenozzi** [comment]
Hi @yyevgenii ,
the issue appeared today again on a Commerce installation.

**Comment by ghost** [comment]
@mmenozzi, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by cmuench** [comment]
The issue occured today in my Magento Commerce 2.2.5 installation.

**Comment by mmenozzi** [comment]
@engcom-backlog-pb this IS a Magento Core technical issue.

**Comment by ghost** [comment]
@cmuench, please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only.

**Comment by cmuench** [comment]
@engcom-backlog-pb I created a ticket in the Enterprise Support.
For documentation purposes I will update this ticket if I got an solution for the issue.
This issue is really annoying. So everyone with the same problem is in the loop.

**Comment by cmuench** [comment]
Enterprise support suggests:

```
composer clearcache
rm -rf vendor/klarna/module-ordermanagement
composer update
```

In my case this solves the problem.
It is important that the composer.lock file will be commited. 
If not in an environment the commands must be called.
In my case we run this in a docker container with an Magento 2.2.5 image.

**Comment by yyevgenii** [comment]
@cmuench have you seen the same instruction in this thread?
https://github.com/magento/magento2/issues/16129#issuecomment-400583192

**Comment by quisse** [comment]
`composer.lock` should **always** be commited.

**Comment by cmuench** [comment]
@quisse we always commit the composer.lock. It is only a hint for other ppl here.

@yyevgenii yes, but we need this information in the release notes of Magento 2.2.5. This is an problem for all developer who update from 2.2.4.

**Comment by giuseppemorelli** [comment]
Just a little clarification about @cmuench commands:

```
composer clearcache
rm -rf vendor/klarna/module-ordermanagement
composer update
```

If you run composer update you will update all packages, and sometimes maybe you don't want to.
Just update the package with that has checksum error

```
composer clearcache
rm -rf vendor/klarna/module-ordermanagement
# update only the "broken package"
composer update klarna/module-ordermanagement
```

So the `composer.lock' will be update with shasum correctly and you can download the package

**Comment by yyevgenii** [comment]
@giuseppemorelli it looks like the klarna/module-ordermanagement won't be updated with the `composer update klarna/module-ordermanagement` command if it isn't listed in the `required` packages.

**Comment by cmuench** [comment]
@yyevgenii 
Maybe we should remove all Klarna modules before any update?

```
composer clearcache
rm -rf vendor/klarna
# update only the "broken package"
composer update klarna/module-ordermanagement
```

**Comment by vk-chts** [comment]
Remove the composer.lock file and then run composer install again
