### ISSUE TITLE
Required param Coupons Code Helper

### ISSUE THREAD

**Issue by bvboas** [magento/magento2#1612]
Hi,

We have a Cart Price Rule that offers 20%off. And we generate one coupon per customer.

The way we present the coupon to the customer varies, normally in the email, but also in the website.

And for that we built a widget (Frontend App). But the issue is that the template filter is not allowing generating new coupons and throws the following exception:

>Error filtering template: Missing required argument $couponParameters of Magento\SalesRule\Helper\Coupon.   

The Coupon constructor :
```php
    public function __construct(
        \Magento\Framework\App\Helper\Context $context,
        array $couponParameters
    ) {
        $this->_couponParameters = $couponParameters;
        parent::__construct($context);
    }
```

We can do this in a Controller 
```php
$generator = $this->_objectManager->get('Magento\SalesRule\Model\Coupon\Massgenerator');
```
But we can't use inside the Filter Interface Objects

One option would be create default values in the Coupon Helper class and add change 
```php
array $couponParameters
```
to
```php
array $couponParameters = array()
```
Regards

**Comment by vpelipenko** [comment]
Internal ticket: https://jira.corp.x.com/browse/MAGETWO-41365

**Comment by vpelipenko** [comment]
Hi @bvboas. We've started to investigate this issue internally and have a question to you. Could you give us more details which will help to reproduce the issue? What are going to do in your widget? Generate coupons? How did you implement this?

**Comment by bvboas** [comment]
HI @vpelipenko 

To reproduce the error try to instantiate the Massgenerator within a widget. 
If you execute the code below in a controller it will execute just fine, but if you execute it within a widget, the code will fail. 

```php
//This code will fail inside any widget
  $generator = $this->_objectManager->get('Magento\SalesRule\Model\Coupon\Massgenerator');
```

Widgets content is parsed by a Filter Interface Object,

> Magento\Framework\Filter\Template->filter()

, and because there are required params not set in the constructor, build will fail. In this case, 
>Magento\SalesRule\Helper\Coupon 

requires an array of params that have no default value.
```php
  public function __construct(
        \Magento\Framework\App\Helper\Context $context,
        array $couponParameters
    ) {
        $this->_couponParameters = $couponParameters;
        parent::__construct($context);
    }
```

We use this feature to assign coupon codes to customers, so they can't be used by others. They can be sent in a email marketing campaign, to a specific segment of customers, in a SMS campaign, presented at the store, etc. 

However, we generate coupons in a per-needed basis. We have many rules and many thousands of customers and if we generated 1 coupon per customer per rule we would be talking about many millions of coupons, and we don't need/want that.

Coupons are generated based on rules  (order average, days since last order, customer net profit, ltv, and other metrics ).  One rule can have less than 10 coupons and other can have tens of thousands. It all depends the conditions required for the customer to match the rule conditions.

If we send a campaign to 100.000 customers, emails will have different content per customer, and some content might be a coupon code. It depends if the customer matches or not a cart rule.

The code we use to generate coupons is the following:
```php
//\Magento\Salesrule\Model\Coupon\MassgeneratorFactory
 $generator = $this->_massGeneratorFactory->create();
//$params  = widget params
//$rule = Shopping cart rule
$data = [
    'uses_per_customer' => 1,
    'uses_per_coupon'   => 1,
    'qty'               => 1,
    'length'            => (int) $params['length'] == 0 ? 10 : $params['length'],
    'to_date'           => $rule->getToDate(),
    'format'            => $params['format'],
    'suffix'            => $params['suffix'],
    'dash'              => $params['dash'],
    'prefix'            => $params['prefix'],
    'rule_id'           => $rule->getId(),
];

$generator->validateData($data);
$generator->setData($data);
$generator->generatePool();
```

**Comment by sivaschenko** [comment]
@bvboas The fix for this issue is delivered to develop. Default coupon parameters are provided.

**Comment by mage2dev** [comment]
It doesn't work if you use Massgenerator by cron. It seems you should move the fix from app/code/Magento/SalesRule/etc/frontend/di.xml to app/code/Magento/SalesRule/etc/di.xml.
