### ISSUE TITLE
JS Error by deleting Store Design Change

### ISSUE THREAD

**Issue by annapet** [magento/magento2#1613]
I try to delete a Store Design Change (backend Content/Schedule, then open store design change). I click on "delete" button, but nothing happens und I getting JS error in console "ReferenceError: confirmSetLocation is not defined"
![magento2-edit-store-design-change](https://cloud.githubusercontent.com/assets/841562/9066280/f00b2b4a-3ad6-11e5-8b0f-370867c5afa1.png)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-41366

**Comment by sivaschenko** [comment]
@annapet Fix for this issue is delivered to `develop` branch

**Comment by annapet** [comment]
@sivaschenko Thank you for info!
