### ISSUE TITLE
Magento 2.2 wrong product url with multiple store views

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#16134]
### Summary
Magento 2.2.2 with one website, one store and 2 store views. 
On frontend:
- the second store view created is ok
- the default store view has all the products urls wrong
On backend:
- the second store view is ok
- the default store view has all the checkboxes unchecked + the url key field is not saved

### Preconditions
- magento version 2.2.2 with no sample data on ubuntu with mysql and php 7

### Steps to reproduce
- import products (via backend import or cli script it doesn't matter)
- create second store view
- change url suffix from default (.html) to nothing

### Expected result
- on frontend, url for products should be www.domain.com/url-key-of-product for both store views
- on backend, url key attribute of product should be filled in with the actual url key of the product + checkboxes "use default value" and "create permanent redirect..." should be already checked for both store views

### Actual result
- on frontend, only the second store view shows the correct url, while the default store view shows product with urls like: https://www.domain.com/catalog/product/view/id/1713/s/jip-jan-scarpine/category/6/
- on backend, "all store views" is ok, second store view is ok but the default store view is not ok, which means: 
-- all the "use default value" checkboxes are unchecked
-- the url_key attribute appears to be filled in with the correct url key but if I check "use default value" for this attribute, then save, then go check the attribute again, then the input field for url_key is empty (and the "use default value" checkbox is still unchecked). If I manually copy the url key from "all store views" to the default store view and check "use default value" and save, then the url key is still not saved. If I manually copy the url key from "all store views" to the default store view and leave the "use default value" unchecked and save, then the url key is saved but the url on frontend still displays wrong. 

Clean and flush cache + reindexing from cli does not help, issue persists. 

I also tried to revert back product url suffix to default. At first glance it didn't do any change but if I save the product manually, the url gets correctly rewritten. What I mean by manually is: 
- open the product
- copy the url key from all store views
- swith to default store view
- check all the "use default value" checkboxes
- save
- stay in the default store view and check the url key field: it is empty and none of its 2 checkboxes (use default and create redirect) are checked
- paste url key
- check the create redirect checkbox (leave the use default unchecked)
- save the product again
- go to frontend: product url is correct (www.domain.com/url-of-the-product.html)

Note: I don't care much about the checkboxes but I'm concerned about the url situation. We cannot go online with the website until the product urls are ok so this is really a big big issue.

**Comment by LouNik1984** [comment]
Just to add: 
- after saving the product manually with the procedure described above, the default store view shows the url correctly but the second store does not. So after saving the product, the default store view shows the url correctly (www.domain.com/url-of-the-product.html) while the second store view shows the url wrong (www.domain.com/catalog/product/view/id/1713/s/product-url-key/category/6/).

I also tried to enable the store codes so maybe this would help the rewrite procedure but it doesn't do anything: the store code is correctly added to the url, but the url itself doesn't change, so now correct urls are like "www.domain.com/code/url-of-the-product.html" while wrong urls are like "www.domain.com/code/catalog/product/view/id/1713/s/product-url-key/category/6/"

**Comment by ghost** [comment]
Hi @LouNik1984 When i flush cache in admin (system-> cache management) urls was right, however the error in cli it not right, and the fix for this issue is already available in the 2.3-develop branch, so we've acknowledged the issue and added to our backlog.

**Comment by maxchen666** [comment]
@engcom-backlog-nazar May I know the number of change list in 2.3-develop?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @LouNik1984 The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by dipak85shinde** [comment]
I am still facing this issue for categories on Magento 2.3.1. Categories URLs are generated correctly for the default store but not for the new store.

**Comment by bobemoe** [comment]
Yeah I'm still seeing this on 2.3.1 too, kind of.

If I create the category in the admin then the URL Rewrites are generated correctly.

However if I create the category programmatically, then the rewrite is only generated for the default store view, and the other store views have .../view/id/... style URL.

I wonder if its an error in my code? Do I need to trigger the generation of rewrites? Shouldn't creating the category be enough?

```php
    $category = $this->_objectManager->get('\Magento\Catalog\Model\CategoryFactory')->create();
    $category->setName($name);
    $category->setParentId($parent_id); 
    $category->setIsActive(true);
    $this->_objectManager->get('\Magento\CatalogApi\CategoryRepositoryInterface')->save($category);
```

**Comment by Layer5-PaulC** [comment]
I also see this issue in 2.3.2 with programmatically created products (via CLI script), only the default store view has an seo-friendly product url. Did you find the correct modification to your script? It's wasteful of resources, but you might have to foreach over your storeviews, setStoreId($storeviewid), and repeatedly save your category?

**Comment by bobemoe** [comment]
Kind of a workaround but I ended up using olegkoval/magento2-regenerate-url-rewrites to fix the issues.

**Comment by angelflo** [comment]
same for me , this is issue is still here on 2.3.2 version

**Comment by Layer5-PaulC** [comment]
I can confirm olegkoval/magento2-regenerate-url-rewrites sorted it for me too, obviously I have to schedule the running of that, but I found running it against products for a whole store-view  cleaned it up straight away.

**Comment by SewHappy58** [comment]
Still having the same problem on Magento 2.3.4

**Comment by gabriel3iri** [comment]
I can confirm this is still an issue on 2.3.4

**Comment by skdude** [comment]
confirm still an issue.

**Comment by angelflo** [comment]
confirm also ... still the issue ! how is it possible to have a so major bug not solved since a SO LONG TIME ????
