### ISSUE TITLE
Change magento github install to normal install

### ISSUE THREAD

**Issue by cdpi404** [magento/magento2#16131]
### Preconditions

1. Installed Magento 2.1.7
2. Migrated Magento 1.9 data to 2.1.7  and live

### Expected result

1. I want to know if there is a way to upgrade my magento 2.1.7 to magento 2.2.3 without being on the github install, i've read that the github install is only for dev and now my site in live on this version. Or does i need to reinstall all on a new fresh magento 2 install but how to keep my data?

### Actual result

1. i've tried to upgrade from 2.1.7 to 2.2.3 with github but always fail

**Comment by orlangur** [comment]
Hi @cdpi404,

First of all, GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. 

On your question, switching from GitHub-based to Composer-based installation should be seamless. They are compatible from data perspective.

First create a proper repo for `2.1.7` as Composer-based installation with all your custom code. Test it on staging with copy of your live database. After you assure everything works as expected, try upgrading to `2.2.3` on staging and check how it worked.

The only tricky part I see is switching repository used on prod from old to new.

**Comment by orlangur** [comment]
> i've tried to upgrade from `2.1.7` to `2.2.3` with github but always fail

By the way, normally it should work. You just `git checkout` a new tag and then run `./bin/magento setup:upgrade`.
