### ISSUE TITLE
Instalation error: MySQL server has gone away in 

### ISSUE THREAD

**Issue by ArniXXX** [magento/magento2#1614]
We can see this error for OpenServer.

php.ini

[MySQL]
mysql.allow_local_infile = On
mysql.allow_persistent = On
mysql.cache_size = 2000
mysql.max_persistent = -1
mysql.max_links = -1
mysql.default_port = %mysqlport%
mysql.default_socket =
mysql.default_host =
mysql.default_user =
mysql.default_password =
mysql.connect_timeout = -1
mysql.trace_mode = Off

After start Try Again we have this error.

[ERROR] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'' in

**Comment by mazhalai** [comment]
@ArniXXX Thank you for reporting this issue, your error shows that the database has some data in it. Can you please clear your database and try again? Also, are you installing with sample data?

**Comment by ArniXXX** [comment]
1) I used the default settings. (Also, are you installing with sample data?)
2) I did this several times. (Can you please clear your database and try again?)

**Comment by mazhalai** [comment]
What is your exact MySQL version? We do not support 5.5 and the specific version for 5.6 is 5.6.5

**Comment by ArniXXX** [comment]
[We do not support 5.5 and the specific version for 5.6 is 5.6.5]
I think this is very bad idea.

**Comment by mazhalai** [comment]
@ArniXXX would you explain why this is a very bad idea?
Please see [this related thread](https://github.com/magento/magento2/issues/1740#issuecomment-135986837) on why we support 5.6.5

**Comment by ArniXXX** [comment]
I got it! Thx

**Comment by mazhalai** [comment]
@ArniXXX Thank you for your response. We are closing this ticket!
