### ISSUE TITLE
Unable to load category checkbox tree

### ISSUE THREAD

**Issue by jwcarder** [magento/magento2#16140]
### Preconditions

1. Magento 2.2.4 without sample data is installed
2. Multiple root categories are added (3)
3. Multiple subcategories added to each root category (2 each)

### Steps to reproduce
1. In Admin, navigate to Marketing-Catalog Price Rule
2. Add a new rule
3. Under conditions, add a condition and select Category
4. Click on the ... link
5. Click the open chooser button

### Expected result
1. Category checkbox tree loads

### Actual result
1. Category checkbox tree fails to load and script enters an endless loop

After some digging, it appears as though the issue may be in the following file -vendor/magento/module-catalog/view/adminhtml/web/js/category-checkbox-tree.js line 164

```
categoryLoader.buildCategoryTree = function (parent, config) {// eslint-disable-line no-shadow

                if (!config) {
                    return null;
                }

                if (parent && config && config.length) {
                    for (i = 0; i < config.length; i++) {
                        categoryLoader.processCategoryTree(parent, config, i);
                    }
                }
            };
```

The counter in the for loop will get a config.length equal to the number of root categories, but will not increment past the number of subcategories contained in the root category.

**Comment by hostep** [comment]
Hi @jwcarder 

I'm going to close this issue as it duplicates https://github.com/magento/magento2/issues/15121, which already got fixed in https://github.com/magento/magento2/pull/15265 (https://github.com/magento/magento2/commit/d9dc66cfc5e1988bd8673c2cfdd1de2b85f0a3c6) and the fix should get included in Magento 2.2.5
