### ISSUE TITLE
Issues While adding 3rd Party jQuery Library to Module

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16156]
### Preconditions

1.  Magento CE 2.2.4 , PHP 7.1 ,Apache/2.4.23

### Steps to reproduce

1.  Create Sample Frontend Module 
2.  Try to include Croppie JS for Image Crop 
3.  Declare Dependency with requireJS 
4.  Use In template file for achieving scope

`var config = {
 map: {
   '*': {
       croppie: 'Vendor_Module/js/croppie.min',
     }
   }};`

**Use in Template like**

`require(['jquery', 'croppie'], function($){ $(function(){
        	$uploadCrop = $('#upload-demo').croppie({
    enableExif: true,
    viewport: {
        width: 200,
        height: 200,
        type: 'circle'
    },
    boundary: {
        width: 300,
        height: 300
    }
});}`

### Expected result

1. It should work even visitor reloads page. Not only first Time.

### Actual result

1. After setup first time it working but after reload page its causing conflicting. 
![console](https://user-images.githubusercontent.com/39085366/41462248-d3f44ba0-70af-11e8-8827-e70135c89c52.png)
![console2](https://user-images.githubusercontent.com/39085366/41462251-d86c5d1c-70af-11e8-83da-99285c72323f.png)

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
