### ISSUE TITLE
Magento 2.2.3, In block grid after apply filter gives blank csv in export.

### ISSUE THREAD

**Issue by jitendra-cedcoss** [magento/magento2#16158]
**Preconditions:**

1.In a block grid csv export functionality we get a blank csv after apply filter (more than one).
example of block grid : Newsletter Subscribers 

**Steps to reproduce**

- Go to Marketing >> Marketing >> Communications >> Newsletter Subscribers
- Apply filter on a Customer First Name, Customer Last Name (more than one column) , make sure you get a record in a grid.
- Select option CSV or Export XML, click on a export button.

 **Expected result**

1. We get a record which is shown in the grid.

 **Actual result**

1. We get a blank csv or xml.

**Comment by xpoback** [comment]
@jitendra-cedcoss I could reproduce the issue in 2.1.x but not in 2.2.x

**Comment by jitendra-cedcoss** [comment]
@magento-team any update ?

**Comment by ghost** [comment]
@jitendra-cedcoss, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by jitendra-cedcoss** [comment]
@magento-engcom-team 
We found this issue in Magento 2.2.3 CE but this issue is not available in Magento 2.2.4 CE. We attach a video to produce issue, I think this will help you to produce issue.
[video.zip](https://github.com/magento/magento2/files/2194671/video.zip)

**Comment by ghost** [comment]
@jitendra-cedcoss, thank you for clarification. We are fixing only problems, related to the latest release.
