### ISSUE TITLE
Feature Suggestion: Attribute notes

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#16150]
I would like to see the possibility to add notes to attributes so they would show up in the admin interface. 
There is a note field in the eav_attribute table but that can only be filled via an install or update script or directly in the database. 

Why not enhance the admin interface and make it editable?

**Comment by orlangur** [comment]
It would complicate the things a lot. You have to think about ACL - which admin can view and which can edit such notes.

Sounds more like a documentation and it is much more convenient to not keep it within Magento.

Is there any example of similar documentation functionality in Magento currently?

**Comment by OvalMedia** [comment]
Wow, such a seemingly simple task "complicates things a lot"? Then this system is missing flexibility.

> Sounds more like a documentation and it is much more convenient to not keep it within Magento.

Quite the opposite. It makes a lot of sense to display a simple two-liner that explains the purpose of a particular field rather than plowing through the documentation.

> Is there any example of similar documentation functionality in Magento currently?

Not that I know of. That's why I am suggesting this feature. I have built many magento stores with a lot of attributes. And it always bugged me that this is missing.

If I had to name a good example in the wild for this then take a look at drupal. It's not a shop-system but they have a similar EAV system with extensive inline documentation features.

BTW: There already IS a note field and it's content displays under the attribute fields. But like mentioned, it is only administrable through code (ouch) or direct database edit. Why have it if it can't be used properly?

**Comment by orlangur** [comment]
Such note, like many other database columns, is not supposed to be editable via UI.

> Not that I know of. That's why I am suggesting this feature. I have built many magento stores with a lot of attributes. And it always bugged me that this is missing.

Features cannot be introduced out of the blue. It is not enough to just implement notes for attributes but it should be defined which other Magento areas require similar functionality. Probably it is not even needed within Magento, there are services allowing to collaborate in comments for arbitrary URLs.

This repository is intended for bug reports only, feel free to add your suggestion into https://github.com/magento/community-features
