### ISSUE TITLE
testing new instance feature

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#16163]
@magento-engcom-team give me 2.2.4 instance

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by orlangur** [comment]
Looks like only PRs are supported :)

```
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation
```

**Comment by orlangur** [comment]
Hmmm,

"for Issue or Pull Request"

is misleading then

**Comment by DanielRuf** [comment]
> Hmmm,
> 
> "for Issue or Pull Request"
> 
> is misleading then

Exactly. I thought I could use it to create a test instance for projects where we can not give the URL or some text description is not enough and a real demo would be needed.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-16163-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16163-2-2-4.engcom.dev.magento.com/admin](https://i-16163-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
Hi @DanielRuf 

Sorry for confusing. I can explain why it does not work:
1. use used the command `@magento-engcom-team give me 2.2.4 instance` in the issue description, but it should be in the **comment**. That's why it didn't work

2. use used the command `@magento-engcom-team give me 2.3 instance` in the issue comment which is correct, but we don't have 2.3 release available yet (it is not released). So to get 2.3 you need to use `@magento-engcom-team give me 2.3-develop instance`

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-16163-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16163-2-2-4.engcom.dev.magento.com/admin](https://i-16163-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
Makes sense. Can we make this a bit more clear for the bot that it can not be directly used in new issues but as comments on issues and PRs?

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by DanielRuf** [comment]
Awesome =)

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-16163-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16163-2-3-develop.engcom.dev.magento.com/admin](https://i-16163-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
> but we don't have 2.3 release available yet (it is not released)

@okorshenko thanks for comprehensive explanation, some response from bot like "no 2.3 released yet, you may use 2.3-develop" or "invalid release specified, available releases: 2.1.15, 2.2.4, 2.3-develop" would not hurt though.

**Comment by CristiLodor** [comment]
@magento-engcom-team give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @CristiLodor. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @CristiLodor, here is your [Magento instance](https://i-16163-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-16163-2-3-2.instances.magento-community.engineering/admin](https://i-16163-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by DanielRuf** [comment]
Seems the bot got stuck. Let's try again

@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by DanielRuf** [comment]
Hm, let's create a new issue.

**Comment by DanielRuf** [comment]
And another try

@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by sdzhepa** [comment]
Hello @DanielRuf 

I am working on this issue `give me 2.3.0 instance`.
I will keep you updated  here or directly in Slack

Sorry for inconveniences

**Comment by DanielRuf** [comment]
It does not seem to work with any tagged version. Only branches (2.3-develop).

**Comment by sdzhepa** [comment]
Hello @DanielRuf 

Just update.
There root cause of this issue with the deployer is PHP version on the server with deployer.
Recently we have updated it to `7.3.11` and as a result, we have:

```
On GitHub> @magento give me 2.3.0 instance

In logs > 
Problem 1
    - This package requires php ~7.1.3||~7.2.0 but your PHP version (7.3.11) does not satisfy that requirement.
```
Now I am trying to figure out how it can be hotfixed.
One of the possible quick solutions is downgrade PHP to 7.2.0.

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by sdzhepa** [comment]
@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-16163-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-16163-2-3-0.instances.magento-community.engineering/admin](https://i-16163-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-16163-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-16163-2-3-develop.instances.magento-community.engineering/admin](https://i-16163-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@DanielRuf 

We have applied hotfix and it works now for 2.3.0 ... 2.3-develop

I hope it is a temporary solution because we have a lot of tasks in our backlog related to Instance Deployer functionality(refactor/rewrite). We planned to work on it starting from the next year.

Also, let me remind that the main goals of this tool are
- provides the ability to check(confirm) is a newly created issue can be reproduced on the **latest codebase**
- provides the ability to deploy a Magento instance based on created PR for **the latest code**
- It has a limited feature list and can be used only for some high-level verification. This point I hope will be improved but even after all planned changes it will have limitation(do not expect it will be the same access/control as for local instance)

**Comment by DanielRuf** [comment]
Awesome, many thanks.

Well but about testing 2.2 releases and testing against specific releases? This is a valid usecase.

**Comment by sdzhepa** [comment]
A couple of months ago `2.2-develop` branch was closed/removed for the public repository and after it, we no longer accept Pull Request/Issue for 2.2.x version in this repository.

For more details:
> *We no longer accept pull requests to the v2.2 ... release lines to focus all development efforts on v2.3.*
Related DevDoc was updated https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules

[MAGENTO OPEN SOURCE SOFTWARE MAINTENANCE POLICY](https://magento.com/sites/default/files/magento-open-source-software-maintenance-policy.pdf)

So, according to all mentioned above support of 2.2.x was disabled for Instance Deployer as well

**Comment by APanteleychuk** [comment]
@magento-engcom-team  give me 2.4.4 instance

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.0.7 instance

**Comment by fabiopelloso** [comment]
@magento-engcom-team give me 2.4.6 instance

**Comment by fabiopelloso** [comment]
@magento-engcom-team give me 2.4.7 instance

**Comment by yogesh-valiya** [comment]
@magento-engcom-team give me 2.4.7 instance

**Comment by Deepak-solveda** [comment]
@magento-engcom-team give me latest instance
