### ISSUE TITLE
The value 'Vendor\Xxx5\Model\Queue\Consumer::processMessage' is not accepted by the pattern '[a-zA-Z\\]+::[a-zA-Z]+'.

### ISSUE THREAD

**Issue by weverson83** [magento/magento2#16168]
The xml validator fail when you pass a class with numeric value in it's namespace.

### Preconditions
Magento 2.2.2
magento/framework-message-queue

### Steps to reproduce
1. Create etc/queue.xml file
```
<broker topic="xxxx" type="amqp" exchange="magento">
       <queue consumer="yyyy" name="zzzz" handler="Vendor\Xxx5\Model\Consumer::processMessage" consumerInstance="Magento\Framework\MessageQueue\Consumer"/>
    </broker>
```
2. Run `bin/magento setup:upgrade`

### Actual result
The value 'Vendor\Xxx5\Model\Queue\Consumer::processMessage' is not accepted by the pattern '[a-zA-Z\\]+::[a-zA-Z]+'.

### Work arround
Created a virtualType for my class without a number in it's namespace

### Solution
At vendor/magento/framework-message-queue/etc/queue_base.xsd
```
<xs:simpleType name="handlerType">
        <xs:annotation>
            <xs:documentation>
                @deprecated
                Handler is expected in a format "Vendor\Module\Api\ServiceName::methodName".
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z\\]+::[a-zA-Z]+" />
            <xs:minLength value="5" />
        </xs:restriction>
    </xs:simpleType>
```
Fix the pattern to accept numbers (Make sure it doesn't allow start with number)
`[a-zA-Z]+[a-zA-Z0-9\\]+::[a-zA-Z0-9]+` should work

**Comment by engcom-backlog-nickolas** [comment]
@weverson83, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by domeglic** [comment]
@magento-engcom-team Can we reopen this issue because message queues are now in Open source, the issue still exists and was not fixed.
[Magento: 2.3.3](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/MessageQueue/etc/consumer.xsd#L35)
