### ISSUE TITLE
Disabling Amazon Payments on web wizard install breaks checkout

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#16167]
### Preconditions
1. Magento 2.2.4

### Steps to reproduce

    1. Install 2.2.4 via composer using magento/product-community-edition
    2. Start web wizard
    3. During install choose to leave Amazon Payments disabled
    4. Add a product and enable an offline payment method
    5. Add product to cart on frontend and visit checkout

### Expected result:

To see checkout

### Actual result:

Following Exception:

Exception #0 (UnexpectedValueException): Payment model name is not provided in config!
--
#0 .../vendor/magento/module-payment/Model/PaymentMethodList.php(46): Magento\Payment\Helper\Data->getMethodInstance('amazon_payment')

### Additional information

I can see the admin options for Amazon Payments even though it is disabled in app/etc/config.php, so it may be that there is close coupling between Amazon payments and another module.

**Comment by magento-engcom-team** [comment]
Hi @maderlock 
Please use the Amazon Payments tracker to report issues with the extension: https://github.com/amzn/amazon-payments-magento-2-plugin/issues

Thank you
