### ISSUE TITLE
500 Internal Server Error caused by conflicting web values in system_config_snapshot

### ISSUE THREAD

**Issue by nathancasebolt** [magento/magento2#16176]
**Preconditions**
1. Magento Open Source 2.2.3
2. Ubuntu 16.04.1
3. PHP 7.1.17

**Steps to reproduce**
1. Set up two instances of Magento 2.2.3 in separate Ubuntu environments (e.g., site1 and site2), both instances sharing the same database.
2. Add the following configuration entries to env.php:
```
'system' => 
  array (
    'default' => 
    array (
      ...
      'web' =>
      array (
        'unsecure' =>
        array (
          'base_url' => '{{secure_base_url}}',
          'base_link_url' => '{{secure_base_url}}',
        ),
        'secure' =>
        array (
          'base_url' => 'https://site1.com/',
          'base_link_url' => '{{secure_base_url}}',
        ),
        ...
      ),
    ),
  ),
```

3. Add similar values to site2's env.php file, but use `https://site2.com` for the `web_secure_base_url` value
4. Run `bin/magento app:config:import` on site1
5. Run `bin/magento app:config:import` on site2

**Expected result**
Both site1 and site2 are functional Magento sites because system-specific values from env.php are only accessible to and deployed by their respective environments (site1 or site2).

**Actual result**
site1 throws a 500 Internal Server Error because the `system_config_snapshot` record in the `flag` table includes the `web_unsecure` and `web_secure` values from the env.php file of the most recent environment to run `app:config:import`. In this example, site2 most recently ran the import command. The aforementioned values from site2's env.php file were captured in `system_config_snapshot` and conflict with the configuration of site1, so the latter crashes.

**Comment by springerin** [comment]
Duplicated or Related to https://github.com/magento/magento2/issues/16171

**Comment by engcom-backlog-nickolas** [comment]
Hello @nathancasebolt, thank you for report. I'm closing this issue as duplicate #16171. If you'd like to update it, please reopen the issue.
