### ISSUE TITLE
Order factory instead of repository in Invoice

### ISSUE THREAD

**Issue by springimport** [magento/magento2#16172]
### Preconditions
1. Magento 2.2.3.
2. Get order from invoice.

### Steps to reproduce
1. Get invoice.
2. [Get order](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Sales/Model/Order/Invoice.php#L236) from invoice.

### Expected result
```php
if (!$this->_order instanceof \Magento\Sales\Model\Order) {
    $this->_order = $this->orderRepository->get...
}
```

### Actual result
```php
/**
 * Retrieve the order the invoice for created for
 *
 * @return \Magento\Sales\Model\Order
 */
public function getOrder()
{
    if (!$this->_order instanceof \Magento\Sales\Model\Order) {
        $this->_order = $this->_orderFactory->create()->load($this->getOrderId());
    }
    return $this->_order->setHistoryEntityName($this->entityType);
}
```

**Comment by orlangur** [comment]
@springimport please provide information on undesired system behavior (buggy). Obtaining order via factory is still valid and may occur in legacy code.

**Comment by springimport** [comment]
@orlangur Just check [same issue](https://github.com/magento/magento2/issues/14424).

**Comment by orlangur** [comment]
@springimport why do we need two issues then? Thanks for clarification, closing as duplicate.
