### ISSUE TITLE
Uncaught Type Error in magento 2, JS not loaded properly

### ISSUE THREAD

**Issue by nic02381** [magento/magento2#16186]
I am integrating a new theme in magento 2.2. Also I used some third party JS like bootstrap select menu, owl carousel and wow js for animation.

Preconditions
1.  My Magento version is 2.2 CE

Steps to reproduce
1. I use all my third party js inside require js with a custom module.
2. Also I edit the js with define([
    'jquery'
], function () {
<js content>
});

Expected result

1. I want to clear my js error because it is stuck my performance sometime. 

 Actual result
1. ![image](https://user-images.githubusercontent.com/39520881/41497759-90df75f4-7179-11e8-9750-c1b66a3a1d61.png)

If any one know the idea how to resolve this please let me know.

I run the upgrade, static-deploy, cache clear, reindex command many times.
Please let me know if you want more information.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-16186-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16186-2-2-4.engcom.dev.magento.com/admin](https://i-16186-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
Hi @nic02381 could you reproduce the issue on vanilla Magento installation? 
Try https://i-16186-2-2-4.engcom.dev.magento.com/admin

**Comment by nic02381** [comment]
Hi @okorshenko 
I didn't try with vanilla Magento installation. What's this?
what I do with this [https://i-16186-2-2-4.engcom.dev.magento.com/admin](url) link.

What I need to check in this?

**Comment by nic02381** [comment]
@okorshenko I got an answer.
