### ISSUE TITLE
Multiple refresh on checkout page removes items from cart

### ISSUE THREAD

**Issue by xpoback** [magento/magento2#16188]
### Preconditions

1. Magento 2.2.3
2. PHP 7.1

### Steps to reproduce

1. Add a product to cart
2. Go to checkout 
3. Quickly refresh the page a couple of times, not waiting until everything is loaded

### Expected result

1. The page is refreshed

### Actual result

1. User redirected to cart page
2. Cart is empty (no items in quote)
3. Minicart is still cached and shows the previous state 

This is obviously related to #15434 and is the actual problem source.

**Comment by xpoback** [comment]
There appears to be a [fix](https://github.com/magento/magento2/commit/a6f146cd9302fbbb6305df9613c7ce3eea7a05ae) for this issue, but has not been released yet. Let's just wait for it.

**Comment by sanganinamrata** [comment]
@xpoback This solution [Fix](https://github.com/magento/magento2/commit/a6f146cd9302fbbb6305df9613c7ce3eea7a05ae) works for Secure domain only.

**Comment by xpoback** [comment]
@sanganinamrata Since it is strongly _not_ recommended to use Magento and especially the checkout with unsecure urls, the issue can be considered as an acceptable negative side effect of such use and will not affect the majority of systems. Well, at least not the ones I have to work with.
