### ISSUE TITLE
Magento2 error after git pull

### ISSUE THREAD

**Issue by vinhtrau** [magento/magento2#1618]
When I update new code from developer, my site always occurs error:
Autoload error: Strict Notice: Declaration of Magento\Framework\App\Resource\Proxy::getConnection() should be compatible with Magento\Framework\App\Resource::getConnection($resourceName = self::DEFAULT_CONNECTION) in /private/var/www/magento2/htdocs/var/generation/Magento/Framework/App/Resource/Proxy.php

This error also display when I tried to clear cache by command line: php bin/magento cache:clean --all

**Comment by mazhalai** [comment]
@vinhtrau thank you for your report, but can you try again after cleaning you `var/generation` folder?

**Comment by vinhtrau** [comment]
Yes, it works. thank you!
