### ISSUE TITLE
[HELP Wanted] One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by kaman7114** [magento/magento2#16185]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by okorshenko** [comment]
Configure your cron jobs, please
Here is some documentation https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-cron.html
