### ISSUE TITLE
PNG with transparency resized to completely transparent image

### ISSUE THREAD

**Issue by Orstio** [magento/magento2#16201]
### Preconditions

1. Upload a PNG image with a transparency. (Original image attached)
![americana steel front](https://user-images.githubusercontent.com/6753949/41509580-eaedb388-721b-11e8-966b-fffb529b2ea9.png)

2. All of the resized images are blank, completely filled with transparency. (resized image attached, YES there is an image there.)
![americana-steel-front_1_9](https://user-images.githubusercontent.com/6753949/41509588-16212fda-721c-11e8-8650-dc1cdd619072.png)

3. Environment:  PHP 7.1.17, Linux 3.10.0 #1 SMP Fri Apr 20 17:42:34 MSK 2018 x86_64

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.4.11
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.5.13
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1

Magento 2.2.4

### Steps to reproduce

1. Upload a catalog image with a transparency.
2. View the product on the frontend.

### Expected result

1. Image should be resized, and should look like the original but resized.  It should not be completely blank.

### Actual result

1. Resized image is completely filled with transparent pixels.

**Comment by ghost** [comment]
Hi @Orstio Thank you for your report. The issue has been fixed in 2.2.5 release

**Comment by ghost** [comment]
@engcom-backlog-nazar ,
Can you inform here which files need to be modify in Magento 2.2.4. ?

**Comment by Orstio** [comment]
Definitely NOT fixed in 2.2.5.

Original image:

![2612-mens-crew-neck](https://user-images.githubusercontent.com/6753949/43852063-ea5cd322-9b01-11e8-999e-b9a4c017a61b.png)

Resized in Magento 2.2.5:

![2612-mens-crew-neck](https://user-images.githubusercontent.com/6753949/43852085-f7d3d87a-9b01-11e8-9542-2e6d74dc7ca0.png)

Again, yes, there is a completely transparent image there.
