### ISSUE TITLE
User registration is not working

### ISSUE THREAD

**Issue by tejabhagavankollepara** [magento/magento2#16207]
I have installed fresh Magento-2.2.2 in my local server. In this, Registration is not working. I have entered the first name, last name, email id for login and password then hit on the submit button. After entered this is just loading and be at same page but registration is not working . Please check once. Thank you.

**Comment by nikidexa** [comment]
check the log file...maybe some extension create this issue

**Comment by kkrieger85** [comment]
Hi @TejaBhagavan please pay attention to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template)

**Comment by ishakhsuvarov** [comment]
Hi @TejaBhagavan 
We are closing this ticket for now as it does not follow [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). Please reopen when it's updated.
