### ISSUE TITLE
Theme file for Magento_SendFriend should have capital 'F'

### ISSUE THREAD

**Issue by davefarthing** [magento/magento2#1620]
After the rename of the Magento_SendFriend  module to include a capital 'F' - the theme directories need to be renamed also (else client-side LESS parsing fails with case sensitive file systems):

`app/design/frontend/Magento/blank/Magento_Sendfriend -> app/design/frontend/Magento/blank/Magento_SendFriend`

`app/design/frontend/Magento/luma/Magento_Sendfriend -> app/design/frontend/Magento/luma/Magento_SendFriend`

**Comment by godban** [comment]
Hello @davefarthing, 
Thanks for reporting, another good catch.

We already fixed it in internal MAGETWO-40859, should be available with next update

**Comment by davefarthing** [comment]
Great  - in which case i'll consider it closed ;)
