### ISSUE TITLE
Category Condition in cart price rule not working

### ISSUE THREAD

**Issue by shachiarkatkar** [magento/magento2#16205]
When we setup a cart price rule with category condition in product sub-selection, all categories are not shown in category tree and even after selecting any of the visible category coupon is invalid
### Preconditions

1. Magento 2.2.4 
2. PHP 7.0.27
3. Mysql 5.7.21
4. Nginx

### Steps to reproduce

1. Navigate to Cart price rule tab and create a cart price rule
2. Add condition of category
3. Apply coupon on cart or checkout 

### Expected result

1. All categories should be visible in category condition tree
2. Discount Coupon should be successfully applied / Discount should be shown in summary

### Actual result

1. Not all categories are shown in category tree of condition tab in cart price rule
![screen shot 2018-06-18 at 11 56 10 am](https://user-images.githubusercontent.com/2101412/41521136-a7ccf11c-72ee-11e8-8586-5a6177aa5d3a.png)

2. After selecting any category the coupon is invalid
![screen shot 2018-06-15 at 7 27 55 pm](https://user-images.githubusercontent.com/2101412/41520749-d05b288a-72ec-11e8-9d52-5f306da5eaae.png)

**Comment by hostep** [comment]
@shachiarkatkar: this sounds like a duplicate of https://github.com/magento/magento2/issues/15121, for not being able to see all categories, although I don't know if the fix mentioned in that thread (https://github.com/magento/magento2/commit/d9dc66cfc5e1988bd8673c2cfdd1de2b85f0a3c6), will also fix the fact that the coupon is invalid.

Feel free to close this issue, if you believe this is a duplicate.

**Comment by shachiarkatkar** [comment]
@hostep its not a duplicate, I am facing two issue the category tree not loading properly and coupon code invalid even after . I can see some categories in tree but not all of them there is no error in console. The coupon code is invalid even after applying visible categories as shown in screenshot.

**Comment by ghost** [comment]
Hi @shachiarkatkar Thank you for your report. The issue has been fixed in 2.2.5 release https://github.com/magento/magento2/tree/2.2.5
