### ISSUE TITLE
Call to a member function getRates() using multishipping checkout

### ISSUE THREAD

**Issue by atsareva** [magento/magento2#16219]
Hi guys,

I've got error on multishipping checkout using default magento with sample data.

### Preconditions
1. Magento 2.2.3 / 2.2.4 (with sample data)
2. Ubuntu 16.04 lts
3. PHP 7.0.30
4. mysql  Ver 14.14 Distrib 5.7.22
5. apache

### Steps to reproduce
1. Login to customer account from sample data (roni_cost@example.com / roni_cost@example.com1)
2. Added product to the cart
3. Go to multishipping checkout 
4. Use default 'Flat Rate' shipping method and 'Check/Money order' payment method

![order_review](https://user-images.githubusercontent.com/1243876/41553195-aa23961e-7339-11e8-825c-f171f6880d08.png)

### Expected result
Order should be created without error.

### Actual result
I've got getRates() error

**Error: Call to a member function getRates() on array in /var/www/magento-2.2.4.loc/public_html/vendor/magento/module-tax/Model/Plugin/OrderSave.php on line 83**

### Temporary solution 
I've found that order object should contain **'extension_attributes'** and **tax rates** in it like objects but they are arrays. Please look at **_prepareOrder**() (public_html/vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php). It contains order convertation
`$order = $this->quoteAddressToOrder->convert($address); `
and **convert**() method contains population data object using data in array format. However tax rates are added into order after these actions using plugin **afterConvert**(). If we look at standard checkout, it contains the next code (public_html/vendor/magento/module-quote/Model/QuoteManagement.php - **submitQuote**())

``` 
$order = $this->orderFactory->create();
....
$this->dataObjectHelper->mergeDataObjects(
                \Magento\Sales\Api\Data\OrderInterface::class,
                $order,
                $this->quoteAddressToOrder->convert($quote->getShippingAddress(), $orderData)
            );
```

**mergeDataObjects**() contains population data object using data in array format too. But it in this case order already contains tax rate array and it will be converted into object.

Therefore  I've create observer using '**checkout_type_multishipping_create_orders_single**' event and added the next code

```
$order = $this->orderFactory->create();
        $multishippingOrder = $observer->getEvent()->getOrder();

        $this->dataObjectHelper->mergeDataObjects(
            \Magento\Sales\Api\Data\OrderInterface::class,
            $order,
            $multishippingOrder
        );

        //Re-set extension attributes using converted object
        $multishippingOrder->setExtensionAttributes($order->getExtensionAttributes());
        return $this;
```
This works for me. But I hope this will be fixed soon.

Thanks,
Alona Tsarova

**Comment by ghost** [comment]
@atsareva, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by atsareva** [comment]
Hi @engcom-backlog-pb ,
Yes, I can't reproduce this issue on the last version of magento... I'll continue investigation.
Thanks,
Alona

**Comment by ghost** [comment]
@atsareva, thank you. If you'd like to update the issue, please reopen it.
