### ISSUE TITLE
Unable to get oauth_verifier for Magento2.0

### ISSUE THREAD

**Issue by PrajaktaKalyankar-GSLab** [magento/magento2#16210]
I am trying to do authentication using oauth 1 for Magento 2.0

I am unable to get oauth_verifier for Magento2.0 which is needed to get the access_token

I am trying to get the access token using POST /oauth/token/access which requires oauth_vefirier as one of the parameter.

I am refereeing [this](https://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html) doc.

When I try to activate the integration, it redirects to the callback url but a blank page appears. Not able to get the oauth_verifier.

Can anybody please let me know from where we can get the oauth_verifier generated by the Magento?

**Comment by kkrieger85** [comment]
Hi @PrajaktaKalyankar-GSLab please pay attention to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template)

**Comment by kkrieger85** [comment]
@PrajaktaKalyankar-GSLab Is this issue related to #16238 ?

**Comment by PrajaktaKalyankar-GSLab** [comment]
No. I could get the oauth_verifier but not able to get access_token. I referred this: https://magento.stackexchange.com/questions/110026/magento-2-where-does-the-oauth-verifier-token-come-from?rq=1

Getting errors mentioned in https://github.com/magento/magento2/issues/16238.

**Comment by ishakhsuvarov** [comment]
Hi @PrajaktaKalyankar-GSLab 
Unfortunately it is impossible to provide any help with the issue report which does not contain clear and detailed steps to reproduce. Please update your report according to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template). 
We are closing the ticket now, please reopen when updated.
