### ISSUE TITLE
Updating a cart item via REST API with quantity 0 should remove the cart item

### ISSUE THREAD

**Issue by mhaack** [magento/magento2#16214]
Updating a cart item via REST API with quantity 0 should remove the item from the quote. But instead it is always set to 1?

### Preconditions

1. Magento 2.2 CE 

### Steps to reproduce

1. Create quote for guess user via REST API
2. Add product with quantity > 1
3. Update cart item with `PUT /rest/V1/guest-carts/CART_ID/items/ITEM_ID` and use `"qty": 0` as part of body.

### Expected result

1. Cart item should be removed from quote

### Actual result

1. Cart item quantity is always set o 1, independently for the value before

**Comment by kkrieger85** [comment]
Hi @mhaack please pay attention to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template) 

Please add section **Precondition** to issue description.

**Comment by engcom-backlog-nickolas** [comment]
@mhaack, thank you for your report. In order to remove product from cart, you may try to use DELETE /rest/V1/guest-carts/:cartId/items/:itemId. 
PUT /rest/V1/guest-carts/:cartId/items/:itemId not intended to remove items from cart.

**Comment by mhaack** [comment]
I‘m aware of the DELETE method.
However sending a PUT with qty 0 should not set quantity to 1? That why I suggest to remove the item for such a case. Alternatively the PUT has the return an error that 0 is no valid value in this context.

**Comment by magento-engcom-team** [comment]
Hi @mhaack
We are moving this to the features backlog to evaluate requirements for this item.

Thanks

**Comment by magento-engcom-team** [comment]
Hi @mhaack. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/72
