### ISSUE TITLE
Second level Category page Layered Navigation not rendered when subcategory is added to category.

### ISSUE THREAD

**Issue by AlbiIT** [magento/magento2#16212]
Magento 2.2.2

When I create a New Category and add products to it via the Category Products tab then the category layered navigation renders on the front end for that Category.

As soon as I add one subcategory, assign it some products, and save then Layered Navigation disappears from Parent category page.  Everything is work fine excepts layered navigation is missing on only second level category if it has minimum one child category.
I have created all categories as Is Anchor = Yes.

Please help me with this, i m stuck with this error.

**Comment by kkrieger85** [comment]
Hi @AlbiIT please pay attention to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template)

**Comment by engcom-backlog-nickolas** [comment]
Hello @AlbiIT, thank you for your report. Unfortunately I wasn't able to reproduce this issue.
![peek 2018-07-24 13-29](https://user-images.githubusercontent.com/40755810/43132798-8fa493f6-8f45-11e8-9f30-a4a299a67122.gif)

If you'd like to update it, please reopen the issue.
