### ISSUE TITLE
Orders page: Can't use mouse wheel click to open order page in a new tab

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#1621]
If I want to open more than 1 order, I usually click on "View" link using wheel on my mouse to open links in new tab. But when I try to do this in M2 (magento2), then it does not open in new window. It opens it in current window. Magento1 does it as expected though.
It looks like something catches this click type. =\
Please fix it.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-41362

**Comment by okorshenko** [comment]
@stasleo , Internal ticket MAGETWO-41362 is closed and delivered to mainline. Please, see https://github.com/magento/magento2/commit/11cf8af049a702829857cc3c6d87aaed2e941054. Please, let us know if you still have an issue
