### ISSUE TITLE
Abandoned cart page not opening in magento

### ISSUE THREAD

**Issue by MCReynolds73** [magento/magento2#16218]
When i click on Abandoned Carts under the Reports tab I get an error message that the page isn't working. The error message states: This page isn’t working
www.americanflags.com is currently unable to handle this request.
HTTP ERROR 500
Please advise on how to fix. Thank you.

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by kkrieger85** [comment]
@MCReynolds73 please pay attention to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template)

**Comment by ghost** [comment]
@MCReynolds73, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
