### ISSUE TITLE
requirejs-config misunderstanding?

### ISSUE THREAD

**Issue by RanzigeMilch** [magento/magento2#1622]
Hi all,

i have an own module in app/code/Namespace/Module.
In this module there is in /view/frontend a requirejs-conig.js
with:
var config = {
	map: {
		'*': {
			test:'Namespace_Module/js/test'
		}
	}
};

The test.js is under /view/frontend/web/js.
In my theme (Namespace/name/) is a customfuncs.js under /web/js

This file is included in my layout default_head_blocks.xml

I have following require-statement in this customfuncs:
require(['jquery','test'], function(I$){}

I get an 404 for /pub/static/frontend/Namespace/themename/de_DE/test.js"

Do i have a misunderstanding with registering resources in modules or is there a mistake i dont see?

Greets

**Comment by guz-anton** [comment]
> i have an own module in app/code/Namespace/Module.
In this module there is in /view/frontend a requirejs-conig.js

First note. As you described you should have
 - materialized file or link under `/pub/static/frontend/Namespace/themename/de_DE/Namespace_Module/js/test.js`
 - request from Storefront `/static/frontend/Namespace/themename/de_DE/Namespace_Module/js/test.js`

> I get an 404 for /pub/static/frontend/Namespace/themename/de_DE/test.js"

Second note. It looks like RequireJS on the page doesn't know about `Namespace_Module/js/test` module.

Please locate autogenerated file `/pub/static/_requirejs/frontend/Namespace/themename/de_DE/requirejs-config.js` on your file system. And check if there string _test:'Namespace_Module/js/test'_ appears.

If it absent - delete file `/pub/static/_requirejs/ .. /requirejs-config.js`. It should regenereted with your configuration. Then issue will resolved.

**Comment by vpelipenko** [comment]
Closed. There is no response from contributor. @RanzigeMilch, if you still have some questions or your issue is not resolved, please, feel free to reopen this issue or create new one.
