### ISSUE TITLE
Adding product in category in product->categories page in admin side is not working

### ISSUE THREAD

**Issue by ravikiranpullela** [magento/magento2#16227]
Issue:
1) when I am going to product->categories and trying to add product in that category,it is adding and after i click save button it is throwing error 
Something went wrong while saving the category.SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dilmahlive_uat`.`catalog_category_product`, CONSTRAINT `CAT_CTGR_PRD_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL` FOREIGN KEY (`product_id`) REFERENCES `sequence_product` (`sequence_value`) ON DELETE CA), query was: INSERT INTO `catalog_category_product` (`category_id`,`product_id`,`position`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)

2) when i am disabling the Magento_VisualMerchandiser core module,it is working fine.I think this core module is causing issue.
I am not able to debug this module to get the solution.
At the time of adding product it is taking correct product id.
After caching and retrieving it is taking different product id and thowing the error.

### Preconditions

1. magento - 2.1.13 enterprise edition
2. PHP - 7.0.21
3.mysql - 5.6.33

### Expected result

1. In product->categories when i try to add product in products in category, it should add the product and save the category.

### Actual result

1. In product->categories when i try to add product in products in category, it is not adding and throwing the error
![ad](https://user-images.githubusercontent.com/40379308/41578665-fe1d6606-73b0-11e8-8c80-3a8ff90f4c86.png)

### Steps to reproduce

1. Go to admin side and goto product->categories and select any category and goto to products in category
![2](https://user-images.githubusercontent.com/40379308/41578843-d997eca6-73b1-11e8-9363-06ea5bc42600.png)

2. Now click on add products and select any product and click on save and close.
![3](https://user-images.githubusercontent.com/40379308/41578883-153a7ef4-73b2-11e8-9f18-2484e2111f52.png)

3. Now click on Save button and it should save the category,but it is throwing error.
![4](https://user-images.githubusercontent.com/40379308/41578961-6d6c3d10-73b2-11e8-8bbc-94bf9ad3470a.png)

**Comment by ghost** [comment]
@ravikiranpullela , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by rvsingh007** [comment]
Please share your solution, i have same issue facing in my magento2 website.

**Comment by ccrothers** [comment]
Also having this issue.

**Comment by Eddcapone** [comment]
We have the same Issue on Magento 2.4.2 EE
