### ISSUE TITLE
Order confirmation & shipment mail not send on 2.2.4

### ISSUE THREAD

**Issue by wangzhi0417** [magento/magento2#16231]
Preconditions
magento 2.2.4
magento2-gmailsmtpapp

Steps to reproduce
1) Upgrade magento to 2.2.4
2) Check Stores-> Advanced -> System -> Gmail/Google Apps SMTP Pro, all configurations are ok.
3) Click "Send test email", can receive test mail correctly.
4) Can send mail when a new user is registered.
5) After user placing an order, no confirmation mail, after ship the order, no shipment mail.

Please advise, thanks.

**Comment by orlangur** [comment]
@wangzhi0417, which extension are you referring to? This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

**Comment by kingyond** [comment]
I also in trouble with this issue for 2.2.4. I found that it’s missing sender informations. I test on 2.2.5 branch , it works. I use mageplaze smtp extension. Just setup x
debug yesterday. Will try to get why it doesn’t get correct sender information today.

**Comment by wangzhi0417** [comment]
@kingyond Thanks, do you know when 2.2.5 will be released?

**Comment by wangzhi0417** [comment]
@orlangur I am using mageplaze smtp extension, thanks for the reminder, but I cannot find a place to discuss that extension.

**Comment by kingyond** [comment]
@wangzhi0417 I don't know when 2.2.5 will release. I were in trouble for a month with version 2.2.3 and 2.2.4 release. Look like 2.2.x release cannot using as live commerce site. There are many bugs for these versions.

**Comment by kingyond** [comment]
@wangzhi0417 Also, i confirm this bug cause by 2.2.4 itself. But not cause by mageplaze smtp extension. I am waiting 2.2.5 release. But had to consider using version 2.1.x . Really wasting time for 2.2.3 and 2.2.4. I think that should not be set flag as release version. Really not friend to new magento user. It's jump into trap after using version 2.2.3 and 2.2.4.

**Comment by kingyond** [comment]
@wangzhi0417 I found a solution how to fix this bug.
open this file 
`vendor/amzn/amazon-pay-and-login-magento-2-module/src/Payment/etc/di.xml`
find this line #63
`<type name="Magento\Framework\Mail\MessageInterface" shared="false" />`
remove the shared string
`<type name="Magento\Framework\Mail\MessageInterface" />`
save it.
after that, remove generated data and compile the di again. this should fix the bug.
`rm -rf generated/metadata/* generated/code/*`
`php bin/magento setup:di:compile`

If the above step not solved the problem.
try to fully clean the cache and run fully deploy
`php bin/magento maintenance:enable`
`redis-cli flushall`
`rm -rf var/page_cache/* var/cache/* var/view_preprocessed/*`
`rm -rf generated/metadata/* generated/code/*`
`php bin/magento setup:upgrade`
`php bin/magento setup:di:compile`
`composer dump-autoload -o`
`php bin/magento setup:static-content:deploy zh_Hans_CN -f`
`php bin/magento setup:static-content:deploy -f`
`service varnish restart`
`php bin/magento cache:clean`
`php bin/magento cache:enable`
`php bin/magento cache:flush`
`chown -Rf nginx:nginx  *`
`php bin/magento maintenance:disable`

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

**Comment by hostep** [comment]
@orlangur: that amazon module is now part of Magento 2.2.4 by default, so Magento has some kind of responsibility to deal with bugs introduced by those modules I think (even if it is only passing the information around that bug on to that particular vendor).

But luckily, for this particular module, there is an open source repository to report these issues: https://github.com/amzn/amazon-payments-magento-2-plugin/
@kingyond: would you be so kind to report this issue to that repo? And maybe even send in a Pull Request?

This also sounds like a duplicate of https://github.com/magento/magento2/issues/14952, but I'm not 100% sure...

**Comment by hostep** [comment]
@kingyond: I can confirm, disabling Amazon_Payment & Amazon_Login fixes the problem:
```
bin/magento module:disable Amazon_Payment Amazon_Login
```

<img width="958" alt="screen shot 2018-06-24 at 17 29 04" src="https://user-images.githubusercontent.com/85479/41820657-a7e97fbc-77d5-11e8-8af8-0df95f788a93.png">

But not sure if this was the same issue as was initially reported by @wangzhi0417, but it feels like it is strongly related.

**Comment by orlangur** [comment]
@hostep,

> that amazon module is now part of Magento 2.2.4 by default, so Magento has some kind of responsibility to deal with bugs introduced by those modules I think

Definitely yes. Such responsibility does not mean bugs in such modules should be reported in this repo IMO. It's like making Magento responsible for bug in Symfony framework if such bug is breaking something in your custom code.

However, it's a responsibility of a vendor to test extension with new Magento version like `2.2.4`. Without such testing any third-party extension should not be used with newly released version, ideally there should be constraint in `composer.json` `<=2.2.3` until compatibility with `2.2.4` is confirmed.

> disabling Amazon_Payment & Amazon_Login fixes the problem

The big question here is why they were enabled during upgrade in the first place ;) `app/etc/config.php` should be under VCS.

**Comment by hostep** [comment]
> Definitely yes. Such responsibility does not mean bugs in such modules should be reported in this repo IMO. It's like making Magento responsible for bug in Symfony framework if such bug is breaking something in your custom code.

Problem is that most of these modules are *not* on Github or some place else (luckily Amazon's module is), I've opened a devdocs issue for contact information for all these CBE's: https://github.com/magento/devdocs/issues/1961

> The big question here is why they were enabled during upgrade in the first place ;) app/etc/config.php should be under VCS.

Installing a clean 2.2.4 from scratch enables all modules.
Also updating from 2.2.3 to 2.2.4 enables all newly introduced modules. And yes, you can see those popping up in the `config.php` file (if you aren't distracted by all the shuffling of modules in that file).
Problem is that people expect that those modules just work and expect that Magento tested these before including them by default, but it looks like the testing was forgotten or was only very briefly done.

In my opinion, these non-Magento modules should be disabled by default, new Magento modules can be enabled though.

**Comment by orlangur** [comment]
> Also updating from 2.2.3 to 2.2.4 enables all newly introduced modules

I see...

> people expect that those modules just work and expect that Magento tested these before including them by default

Such expectation is correct and I'm pretty sure testing with all modules enabled is performed as a part of release activities. However, testing for compatibility with "mageplaze smtp extension" or any other third-party extension is not performed and SHOULD NOT be performed. This is a responsibility of those extensions respective vendors.

**Comment by hostep** [comment]
Correct, I was talking about those Amazon modules :) Which most likely triggered the problem with the mageplaze smtp extension, it also breaks default magento email sending, so yeah... Anyway, this is probably not the correct thread for such discussions :)

**Comment by Jacob-Wilsons** [comment]
I have exactly the same symptoms in magento 2.2.5

Is  this issue is related to magento2-gmailsmtpapp extension or to magento core files ?

Preconditions
magento 2.2.5
magento2-gmailsmtpapp

Steps to reproduce

Upgraded magento to 2.2.5
Check Stores-> Advanced -> System -> Gmail/Google Apps SMTP Pro, all configurations are ok.
Click "Send test email", can receive test mail correctly.
Can send mail when a new user is registered.
Can send mail when password reset.
Can send mail when newsletter subscribed/ unsubscribe

After user placing an order (payment via paypal, or payment as "cash / check" method), no confirmation mail, after ship the order, no shipment mail.

I asked the question here [#smtp issues/117 ](https://github.com/magepal/magento2-gmail-smtp-app/issues/117)

**Comment by ihor-sviziev** [comment]
Related issue: https://github.com/magento/magento2/issues/14952

**Comment by bansined** [comment]
@hostep your solution worked for me. Issue solved just after disabling module 

bin/magento module:disable Amazon_Payment Amazon_Login

Thanks a lot for this solution

**Comment by vutrankien** [comment]
@hostep your solution working fine with my project magento 2.2.4

bin/magento module:disable Amazon_Payment Amazon_Login

Thanks you very much.
