### ISSUE TITLE
Create LESS from CSS console error

### ISSUE THREAD

**Issue by annapet** [magento/magento2#1623]
I tried to create less from css http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-less-sass.html, but I've got an error (see screen)
This happens because in class CssDeployCommand (https://github.com/magento/magento2/blob/develop/app/code/Magento/Developer/Console/Command/CssDeployCommand.php) in function call $this->chainFactory->create param origAssetPath is missing.

<img width="568" alt="magento2-create-less" src="https://cloud.githubusercontent.com/assets/841562/9093419/5873e016-3bac-11e5-88c5-71132b5e7059.png">

**Comment by godban** [comment]
Hello @annapet,
Thanks for reporting this issue. We already started working on that, and seems it in developer complete status, so it will be merged and fixed soon. Internal ticket MAGETWO-41056

**Comment by godban** [comment]
Should be fixed. Please check it.

**Comment by okorshenko** [comment]
This issue was fixed in https://github.com/magento/magento2/commit/3cf2916b4335494adf1cabb6e0f7bf031e8eddec. Please, let us know if you still have an issue
