### ISSUE TITLE
Unable to get access_token for Magento2.0

### ISSUE THREAD

**Issue by PrajaktaKalyankar-GSLab** [magento/magento2#16238]
I am doing **OAuth1 authentication for Magento2.0**. I am referring this doc: https://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-oauth.html.

I am trying to do this using Postman. I have followed steps mentioned in : [Magento 2: Where does the oAuth verifier token come from
](https://magento.stackexchange.com/questions/110026/magento-2-where-does-the-oauth-verifier-token-come-from?rq=1) 
I am able to get the oauth_verifier. But when I try to get the access token I face some issues. I tried **POST /oauth/token/access** by 2 ways:

**1. Using online curl tool:** I got "oauth_problem=OAuth+version+%5C%221.0%5C+is+not+supported" error.

**2. Using Postman:** I got "oauth_problem=Token+verifier+and+verifier+token+do+not+match" error.

I searched for these errors but could not get much information.

Any help on this would be appreciated.

**Comment by kkrieger85** [comment]
Hi @PrajaktaKalyankar-GSLab please pay attention to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template)

**Comment by ishakhsuvarov** [comment]
Hi @PrajaktaKalyankar-GSLab 
Unfortunately it is impossible to provide any help with the issue report which does not contain clear and detailed steps to reproduce. Please update your report according to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template). 
We are closing the ticket now, please reopen when updated.
