### ISSUE TITLE
Cannot redirect url in the post dispatch event

### ISSUE THREAD

**Issue by lucbaojang** [magento/magento2#1624]
I want to redirect to my page after I saved a product in the back-end. So, I used the "controller_action_postdispatch_catalog_product_save" event but it didn't work for me. 

Could you please let me know what was wrong with this code?

public function adminhtmlCatalogProductSaveAfter(EventObserver $observer) {
        $action = $observer->getEvent()->getControllerAction();
        
        $action->getActionFlag()->set('', \Magento\Framework\App\Action\Action::FLAG_NO_DISPATCH, true);
        $this->messageManager->addSuccess(__('You saved the product.'));
        $action->getResponse()->setRedirect(
            $action->getUrl('myrouter/index/index')
        );   
        
    }

**Comment by lucbaojang** [comment]
Can anyone help me? :(

**Comment by Edward-Nguyen** [comment]
Hi, 

You need to create an object 
 \Magento\Framework\UrlInterface $urlBuilder
Then you can use this function 
$action->getResponse()->setRedirect( $urlBuilder->getUrl('myrouter/index/index');

**Comment by lucbaojang** [comment]
I tried but the product wasn't save.

**Comment by lucbaojang** [comment]
It still didn't redirect to my page.

**Comment by lucbaojang** [comment]
@vpelipenko: can you help me?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
