### ISSUE TITLE
categories section spinner loads forever

### ISSUE THREAD

**Issue by d4ve46** [magento/magento2#16258]
Please i just installed Magento 2.2.4 and i'm facing problems with the spinner that loads the page section.
When i go to catalog->categories, the page loads but then the spinner icon spins forever. Doesn't load the form fields to create new categories.

Please help!! I really need to submit this project by the end of the week.

**Comment by DanielRuf** [comment]
Please check if there are any errors in the browser console. And test in an incognito browser instance.

**Comment by d4ve46** [comment]
There are errors in the browser console.

**Comment by DanielRuf** [comment]
> There are errors in the browser console.

Can you show them to us or paste them here?

**Comment by d4ve46** [comment]
I just re-installed magento and created new database and now it loads everything well but quite slow.

**Comment by d4ve46** [comment]
Sorry but i deleted the old one with the console errors. But this one is slow in loading. Probably slow network.
I'm really thankful for the immediate response. I never expected it.

**Comment by d4ve46** [comment]
I have a system message at the backend which says: "One or more indexers are invalid. Make sure your Magento cron job is running".

**Comment by DanielRuf** [comment]
> I have a system message at the backend which says: "One or more indexers are invalid. Make sure your Magento cron job is running".

This is normal.
