### ISSUE TITLE
Something went wrong while saving the new password

### ISSUE THREAD

**Issue by gobyweb2** [magento/magento2#16269]
### Preconditions

1. 
2. 

### Steps to reproduce

1. Siteground Server
2. Magento 2.2.4
3. Custom Theme

### Expected result

1. Should login

### Actual result

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/40428621/41656590-24dc08a8-74ae-11e8-8de0-42aaa125e4b5.png)

**Comment by gobyweb2** [comment]
![image](https://user-images.githubusercontent.com/40428621/41656486-c1c08dfc-74ad-11e8-959d-52d923aa502a.png)

**Comment by gobyweb2** [comment]
After clicking reset password from customer email > entering new pass and above error coming. And SSH command to fix ?

**Comment by ghost** [comment]
@gobyweb2, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
