### ISSUE TITLE
Incorrect #rrggbbaa hex color notation after compiling css on server side

### ISSUE THREAD

**Issue by denistrator** [magento/magento2#16267]
### Preconditions
1. Magento 2.2.3

### Steps to reproduce
1. Add css style with color in "#rrggbbaa hex color notation"
`.test-element {
        background: #00000020;
    }`
2. Run `bin/magento setup:static-content:deploy` to compile css
3. Open Magento site, create element `.test-element`

### Expected result
1. `.test-element` has `background: #00000020;`

### Actual result
1. `.test-element` has `background: #000;`

### Additional notes
After compiling css on server side
![screenshot_32](https://user-images.githubusercontent.com/21016905/41655348-402ec2a8-7495-11e8-819e-035026a92411.png)

After compiling css on client side (Grunt)
![screenshot_31](https://user-images.githubusercontent.com/21016905/41655367-51e8ff4a-7495-11e8-951f-c39e8e921c5b.png)

**Comment by ghost** [comment]
@denistrator, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![default](https://user-images.githubusercontent.com/40756187/43259585-64a6e1d6-90df-11e8-9fb6-6d8c26b46332.png)
