### ISSUE TITLE
Magento not clearing interceptor class cache

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#1627]
In my `etc/adminhtml/di.xml` I have

```XML
    <type name="Vendor\Module\Controller\Adminhtml\Controller\Action">
        <arguments>
            <argument name="registry" xsi:type="object">Magento\Framework\Registry</argument>
        </arguments>
    </type>  
```

as I'm trying to pass the registry to the constructor:

```php
namespace Vendor\Module\Controller\Adminhtml\Controller;

class Action extends \Magento\Backend\App\Action
{
    protected $_registry = null;
    /* @var $_registry \Magento\Framework\Registry */

    public function __construct(
            \Magento\Backend\App\Action\Context $context,
            \Magento\Framework\Registry $registry)
    {
        $this->_registry = $registry
        parent::__construct($context);
    }
```

However I get this error:

```
a:4:{i:0;s:404:"Recoverable Error: Argument 2 passed to Vendor\Module\Controller\Adminhtml\Controller\Action::__construct() must be an instance of Magento\Framework\Registry, none given...
```

With Xdebug I can see that `$context` is being passed fine, but there is nothing there for `$registry`.

**Comment by kandy** [comment]
Did you try run command `bin/magento cache:flush`?

**Comment by jameswithers** [comment]
@kandy cache is disabled but I ran that command anyway. Still get the same error even when moving `di.xml` to `etc` making it global.

**Comment by Vinai** [comment]
I think you don't actually have to configure the argument in di.xml at all, since the object type is already specified as the type in the constuctor, and all the preference does is try to set the same type again.
Does it work if you delete the section of the di.xml?

**Comment by jameswithers** [comment]
@kandy @Vinai  Got it resolved.

The interceptor class Magento had generated was using an old constructor, without `registry` present.

Frustratingly, clearing the Magento cache had not cleared `var/generation/Vendor/Module`. Manually deleting this cache meant the interceptor was re-generated, and it now works.

I could not find any reference to this http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html or http://devdocs.magento.com/guides/v2.0/config-guide/config/caching.html and am currently resorting to deleting `var/generation` each time I make a change.

**Comment by kandy** [comment]
@jameswithers, did you enable developer mode?

**Comment by jameswithers** [comment]
@kandy no I did not. I assume this would stop the interceptor class caching? Is there a Magento2-way to clear this cache too? I could not find it in the documentation.

**Comment by turgayozgur** [comment]
Delete "magento2/var/generation/ModuleName" works for me.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
