### ISSUE TITLE
Unable to edit customer in backend

### ISSUE THREAD

**Issue by gawpo50** [magento/magento2#16272]
### Preconditions

1. 
2. 

### Steps to reproduce

1. Go to Customers > All Customers
2. Choose any customer and click edit
3. Returns error...Page can not be found

### Expected result

1. Expect to have what I had before the upgrade to 2.2.4 which is to be able to edit any customer

### Actual result

1. When picking any customer and click the edit button...get error returned....Cannot find page

**Comment by gawpo50** [comment]
Does anybody have any solutions to this problem?

**Comment by Leandry** [comment]
Can not reproduce on clean Magento 2.2.4 installation
![2018-06-30_15-19-23](https://user-images.githubusercontent.com/9416636/42125120-1e857a2a-7c79-11e8-9c67-921358dccd45.png)

**Comment by gawpo50** [comment]
well...thanks for nothing
