### ISSUE TITLE
Unable to add swatch options to attribute, soap Magento

### ISSUE THREAD

**Issue by EBotha1** [magento/magento2#16289]
### Preconditions

1. Magento 2.2
2. Soap

### Steps to reproduce

![request](https://user-images.githubusercontent.com/40459630/41713558-c3b80496-754d-11e8-8065-d29c3e596c36.png)

### Expected result

1. The swatch attribute 'Test' should have an option 'Test1'
2. I am not sure if the wrong method is being used, but when adding an option to an dropdown/option attribute, it works fine. Or if i am missing tags

### Actual result

![response](https://user-images.githubusercontent.com/40459630/41713549-bfbf6da2-754d-11e8-8ae1-66969d3032dc.png)

**Comment by EBotha1** [comment]
@magento-engcom-team @magento-devops @magento-admin Could  someone please assist with the issue?

**Comment by engcom-backlog-nickolas** [comment]
Hello @EBotha1, thank you for your report.
We've acknowledged the issue and added to our backlog.
