### ISSUE TITLE
Suggestion: Add a web interface for bin/magento module:enable/setup:upgrade/...

### ISSUE THREAD

**Issue by ikk0** [magento/magento2#1629]
For (simple) stores and not so experienced merchants it will be very hard to install new extensions using bin/magento module:enable, module:disable, setup:upgrade, etc. Thus, in the interest of the whole extension developer community, a web interface should be added that allows module activation (not upload/install like Connect Downloader, just simply the ability to enable a module using module:enable, setup:upgrade) from the backend or a separated web interface.

Let's discuss this, please.

**Comment by Vinai** [comment]
I disagree. Currently merchants using Magento 1 suffer from the ability to install any extensions without sufficient knowledge. I think Magento 2 requiring the person to install an extension to at least know how to use the command line is a very good thing.
I don't want to repeat myself, so if you want to know why I think so please refer to the following two rather lengthy posts.

Reference one: http://magento.stackexchange.com/questions/40359/to-use-or-not-to-use-magento-connect-that-is-the-question/40375#40375
Reference two: http://vinaikopp.com/2014/10/17/magento-connect-for-merchants/

**Comment by ikk0** [comment]
I'm not suggesting adding Magento Connect again. Instead, only a simple way to enable a previously uploaded module. Not having this could potentially harm extension developers and keep smaller merchants away from Magento because they won't find a way to install new extensions on their own.. I am not saying it's good they can do this on their own, but it may affect the growth of Magento.

**Comment by mazhalai** [comment]
@ikk0 Thank you for your suggestions! A web interface is in progress, and we will keep you updated when it is available.

**Comment by vpelipenko** [comment]
@mazhalai, please, provide internal ticket here.

**Comment by mazhalai** [comment]
@vpelipenko the internal tickets are MAGETWO-34696,  MAGETWO-36388 and MAGETWO-34698

**Comment by piotrekkaminski** [comment]
All mentioned above stories were closed and should be published soon.
