### ISSUE TITLE
Problem with the translations from javascript in Magento 2.2.2

### ISSUE THREAD

**Issue by ekiba** [magento/magento2#16290]
Hi! I'm developing a project on _Magento 2.2.2_ and I don't know if it's a new bug or I'm not doing well the correct steps when I try to do a translation from javascript and it works if I do it from a static text... 

The problem comes if I try to translate using a variable. In that case the translation is not done correctly and it does not look for the associated translation that is generated in the file js-translation.json

As I know that maybe I do not explain well I put an example in code:

It works!
`$t("Blue")`

Doesn't works... ️:S 
`label = "Blue";`
`$t(label);`

If I follow the steps indicated in the official documentation (https://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/translate_theory.html), it does not work either.
`$t('%1').replace('%1', label);`

Someone can help me, please?

**Comment by Vinai** [comment]
The strings are parsed out of the translation functions by regular expressions, so it is not possible to use variables as the translation string in JavaScript. I think this is how the system is built, probably unlikely that will ever change.

**Comment by ghost** [comment]
@ekiba, thank you for your report.
It seems like @Vinai is right and this is not a bug. If you want to add such functionality to Magento, feel free to create pull request.

**Comment by magento-engcom-team** [comment]
Hi @ekiba. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/73
