### ISSUE TITLE
Having problem in color swatch layer navigation

### ISSUE THREAD

**Issue by jyotirhizonex** [magento/magento2#16299]
Hello,

I have problem with smile elasticsuite.For this elastic search module color swatch values are not getting rendered in category page layernavigaion.

         Please any one look on it.Thank you in advance for any help.

**Comment by okorshenko** [comment]
Hi @jyotirhizonex thank you for your report. This repository is designed for Magento 2 framework issues only. Please contact the support team of `smile elasticsuite` for the assistance
