### ISSUE TITLE
Checkout/Model/Session doesn't set the $quoteIdMask

### ISSUE THREAD

**Issue by daancart2quote** [magento/magento2#1631]
In the file `magento2/app/code/Magento/Checkout/Model/Session.php` on line `256` there seem to be a small error.

`$this->isQuoteMasked()` us used to get the `bool $isQuoteMasked` but that should be `$this->getIsQuoteMasked()` or `$this->isQuoteMasked`

**Comment by vpelipenko** [comment]
Hi @daancart2quote, there is a long discussion about naming convention here https://github.com/magento/magento2/issues/935. We don't have strict rules how method should be named, only recommendations. In this case, I think, it is OK to use name 'isQuoteMasked', look at the latest @TexanHogman comment.

**Comment by daancart2quote** [comment]
Hello @vpelipenko,

The issue is not the naming, the issue is that `function isQuoteMasked()` doesn't exits.
So, `$this->isQuoteMasked()` won't work.

So in the example of @TexanHogman, the way to solve this is to add the following function:

```
    /**
     * @return bool|null
     */
    protected function isQuoteMasked()
    {
        return $this->isQuoteMasked;
    }
```

**Comment by vpelipenko** [comment]
Probably, I missed something... but isQuoteMasked function exists in this class https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/Session.php#L504

**Comment by daancart2quote** [comment]
It looks like my beta was just a version older... Sorry!
Anyway thanks for your time!
