### ISSUE TITLE
Cost param missing from importShippingRate Method

### ISSUE THREAD

**Issue by bvboas** [magento/magento2#1633]
In the 

> \Magento\Quote\Model\Quote\Address\Rate 

the 

> importShippingRate 

does not retrieve the shipping cost for that quote. 

This issue was already present in M1, but saving the order shipping cost is a good idea. 

DB schema changes are necessary and the following line should be added to the above method

> ->setCost($rate->getCost())

**Comment by kassner** [comment]
I think #1008 already requests that. Shame on me, I abandoned it completely.

**Comment by piotrekkaminski** [comment]
Internal issue: MAGETWO-34880

**Comment by magento-engcom-team** [comment]
Hi @bvboas 
Your request has been rejected by PO. Anyway that you for report
