### ISSUE TITLE
Error while installing sample data for magento2

### ISSUE THREAD

**Issue by Manashvi** [magento/magento2#1637]
I am facing this issue while trying to install sample data for magento2. 

The error is 
[Magento\Setup\SampleDataException] Error during sample data installation: Class Magento\Sales\Model\Service\OrderFactory does not exist

This error occurs while trying to install downloadable products. 

Can anyone tell what is the issue.

**Comment by mazhalai** [comment]
@Manashvi thank you for reporting this issue. Can you please provide more details? What is your version of magento 2 and sample-data?

**Comment by Manashvi** [comment]
I downloaded the latest zip of magento2 from here https://github.com/magento/magento2 

The sample data is 1.0.0-beta

**Comment by mazhalai** [comment]
The default is the develop branch, which is not stable, please download the stable master version https://github.com/magento/magento2/archive/master.zip

**Comment by Manashvi** [comment]
@mazhalai Thanks for your support. I downloaded the stable master version. Its completely working now along with the sample data. (P.S. There was still some memory limit issue while installing the sample data which i resolved by increasing the memory limit in php.ini file)

**Comment by vpelipenko** [comment]
It is known issue with sample data on develop branch. We are working on fix now.

**Comment by daim2k5** [comment]
@vpelipenko thanks any timeline?

**Comment by daim2k5** [comment]
Fixed.
