### ISSUE TITLE
admin > advanced > advanced lacks meaning

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1638]
I understand this may be kept for legacy purposes, but this section lacks meaning. The Advanced>Advanced section should really be renamed "Module Output" or similar.

![screen shot 2015-08-10 at 10 58 49 am](https://cloud.githubusercontent.com/assets/437029/9174641/216c693e-3f4f-11e5-9d6a-75ca95f06254.png)

**Comment by markoshust** [comment]
Better yet, this section should probably be eliminated by moving it to Advanced > System > Disable Modules Output

**Comment by therouv** [comment]
:+1:

**Comment by pboisvert** [comment]
My suggestion of "Here be Dragons" was dismissed outright. Will run this by UX team for a recommendation.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/admin-gt-advanced-gt-advanced-lacks-meaning/idi-p/45431).
