### ISSUE TITLE
Quantity Increments in Configurable Products Not Works

### ISSUE THREAD

**Issue by Scqualo71** [magento/magento2#16383]
### Summary of the issue
Quantity increments condition of Magento2 not works, I see its in configurable products with associate many simple products. I tried setting the conditions in both configurable and simple products.

### Preconditions
1. Magento 2.2.3
2. PHP 7.0

### Steps to reproduce
1. Configurable product with associate simple products. Simple products have different quantity increments
Example:
configurable product: minimun order = 50, quantity increments = 10 or quantity increments = not enabled (same results).
Print screen of Product Configuration Page - Advanced Inventory:
![configurable_product_qty_increments](https://user-images.githubusercontent.com/29307582/41853491-2c3072ae-788e-11e8-893c-535439ffbd36.JPG)

simple product: minimun order = 50, quantity increments = 20
Print screen of Product Configuration Page - Advanced Inventory:
![simple_product_qty_increments](https://user-images.githubusercontent.com/29307582/41853517-3ce99f80-788e-11e8-9028-102ef96c8fce.JPG)

### Expected result
1. configuration simple product "win" with configuration configurable product --> order possible are only: 50 pcs, 70 pcs, 90 pcs, 110 pcs  ....

### Actual result
1. quantity increments condition not works. Infact it's possible to order also 51 pcs, 52, pcs, ....60 pcs, 61 pcs ....
![cart](https://user-images.githubusercontent.com/29307582/41853706-a82f2ee0-788e-11e8-9aef-96821153b017.JPG)

Thanks
Fabio

**Comment by magento-engcom-team** [comment]
Hi @Scqualo71. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Scqualo71 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@Scqualo71,

> I tried setting the conditions in both configurable and simple products.

Are you saying that even if you set Qty Increments on configurable product it is ignored?

**Comment by Scqualo71** [comment]
Yes, I can set Qty Increments in configurable product or/and in simple product but the condition is even ignored.

**Comment by orlangur** [comment]
@Scqualo71, ok! Just that Qty Increments of simple products must be ignored when they are added to configurable/bundle products AFAIR, but Qty Increments for configurable should work.

**Comment by Scqualo71** [comment]
What you say is a possible solution but I think it's better that minimum order and quantity increments must work the same way. 
So if it's right that the minimum order of the simple product "wins" on that of the configurable product, I think it must be so also for the quantity increments.
In my store I have this case:  
- product configurable is the product model (image, shape, materials,...)
- product simple are the specific products (sizes, color) and every product has its own packaging (with a specific minimum order and quantity increments).

**Comment by orlangur** [comment]
> minimum order and quantity increments must work the same way

Minimum order currently working the way you described, right? So, you can specify arbitrary value for any simple and it will be effective even when you buy simple as a variation of configurable product.

**Comment by Scqualo71** [comment]
yes, but it is not always possible to use it: it doesn't work if you have to manage packs of products.
Example:
Packs 1 = 10 pcs you have to configure simple product 1 with minimun order = 10 and qty increments = 10
Packs 2 = 20 pcs you have to configure simple product 1 with minimun order = 20 and qty increments = 20
So you can have a configurable product with associate simpe product 1 and 2 but you are not able to manage the packs because qty increments in simple product doesn't works.

**Comment by orlangur** [comment]
> but you are not able to manage the packs because qty increments in simple product don't work

This is totally fine, it means that you need to have a custom implementation in-place.

**Comment by ghost** [comment]
@Scqualo71, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Only Configurable product settings "Minimum Qty Allowed in Shopping Cart" and "Qty Increments" are used.
Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

**Comment by Scqualo71** [comment]
**Steps to reproduce**
Example:
- configurable product (name = Automontante apertura a Libro) : minimun order = 50,  Enable Qty Increments = Yes,  quantity increments = 10
![1_configurable_product](https://user-images.githubusercontent.com/29307582/42474297-6a9a9ef4-83c7-11e8-9e23-52a218db2a23.JPG)
- simple product (name = Barchetta-Avorio-NoAccessori-12x9x3, associated at configurable product with this attributes: Color = Avorio and Dimensioni axbxh = 12x9x3)
![2_configurable_product_front_end](https://user-images.githubusercontent.com/29307582/42474420-d178775e-83c7-11e8-8f46-762c83255111.JPG)
Simple product has minimun order = 50,  Enable Qty Increments = Yes,  quantity increments = 10
![3_simple_product](https://user-images.githubusercontent.com/29307582/42474632-7d9a4a62-83c8-11e8-9b43-d8148a4b6867.JPG)

**Expected result**
You can order only 50 pcs, 60 pcs, 70 pcs....

**Actual result**
You can order 51 pcs
![4_cart](https://user-images.githubusercontent.com/29307582/42474888-3b68168c-83c9-11e8-9ac4-5648a7845572.JPG)

Now I haven't a new (clean) Magento2 installation, but you can see the product at my test enviroment a this [link](http://testa.scatolesumisura.it/it/automontante-apertura-a-libro-barchetta.html)

thanks

**Comment by ghost** [comment]
@Scqualo71, please ask bot for instance and try to reproduce this issue on a clean installation. See instruction in this [post](https://github.com/magento/magento2/issues/16383#issuecomment-399957811).

**Comment by Scqualo71** [comment]
Hi,

in clean installation magento 2.2.5, Quantity Increment works, I replicated the same configurations (you can see [here](http://test2.scatolesumisura.it/chaz-kangeroo-hoodie.html)).
Sorry for this warning that it can now be closed.

Fabio

**Comment by ghost** [comment]
@Scqualo71, thank you for investigation.

**Comment by duffner** [comment]
@magento-engcom-team This is still a valid issue

**Comment by orlangur** [comment]
@duffner what do you mean? Please provide clear steps where you believe Magento behavior is incorrect.

**Comment by jegan1986** [comment]
Associated product decimal quantity increment in magento 2 is not working. It only taking parent product quantity increment setting. When we select the associated product its quantity increment is not updated in quantity field of product view page.

**Comment by orlangur** [comment]
@jegan1986,

>  It only taking parent product quantity increment setting

This is intended system behavior. Parent product setting takes precedence over child product one.

**Comment by jegan1986** [comment]
@orlangur 
Thanks for your valuable comment
Is there any way to fulfill my requirement?

{quote}
 When I select the associated product, its quantity increment should be updated in quantity field of product view page.
{quote}

**Comment by orlangur** [comment]
@jegan1986 only by customizing core implementation, as far as I remember there is only an option to take an image from child product instead of parent.

**Comment by duffner** [comment]
@orlangur , "This is intended system behavior. Parent product setting takes precedence over child product one" 

I believe this to be incorrect as pricing, tiered pricing, and basic inventory features of the child take precedence. Why would one random feature be the opposite?

**Comment by duffner** [comment]
Magento 1 followed what you believe as "expected" however, Magento 2, redesigned this to take the child products as priority.

**Comment by duffner** [comment]
Business Case, I sell three Types of Whiskey,  Standard, Gold and Limited Quantity.  I can buy as much as I want of Standard and Gold, but should only be able to purchased one of the limited Quantity.  

The opposite is also true, I sell boxes of t-shirts, long-sleeve t-shirts.   t-shirts come in boxes of 50, and longsleeve come in boxes of 25... how do I sell?   This was a feature of Magento 1 and worked as expected in this way.

**Comment by orlangur** [comment]
@duffner I have no idea whether it was revised in M2 or unintentionally changed.

You can describe such feature as you see it in https://github.com/magento/community-features. Looks like it would be nice to have some generic way to give priority to child or parent product.
