### ISSUE TITLE
Ability to add Translation for CMS page and CMS block 

### ISSUE THREAD

**Issue by jigneshthummar** [magento/magento2#164]
As all know in magento .phtml we can translate text by using 

<?php   echo $this->__('text to translate'); ?>

but it is not possible to do in cms pages and blocks 

if we can use following directive in cms page or static block

{{translate text="text to translate"}} 

then it will be very useful and store owner can work with very less block and pages instead of duplicating same block or page for multiple stores where text change required.

if we add this functionality to magento core then it can be very useful.

Ref : http://www.lotusseedsdesign.com/blog/extend-the-use-of-links-phtml

**Comment by gplanchat** [comment]
For the record, there is natively the `trans` CMS directive, at least since version 2.0.0, eg :

```
{{trans "Email:"}}
```

or 

```
{{trans
        'Forgot your account password? Click <a href="%reset_url">here</a> to reset it.'

        reset_url="$this.getUrl($store,'customer/account/createPassword/',[_query:[id:$customer.id,token:$customer.rp_token],_nosid:1])"
    |raw}}
```

**Comment by george-vlahakis** [comment]
Is the {{trans directive documented somewhere on this matter?
