### ISSUE TITLE
Readiness Check - AngularJS cancels requests, fails check

### ISSUE THREAD

**Issue by frehner** [magento/magento2#1640]
I'm running Magento2 through Docker right now, and I'm not on a very powerful machine which means that requests take about 1 second or so to process.  The problem I'm having is that the readiness check's AngularJS code appears to cancel requests after 3 seconds, which causes the checks to fail for me for the most part.  

Occasionally one or a couple of the readiness checks processes in time and I pass that particular check, but the others didn't process in time so overall my server fails the readiness check.  I'm stuck on the readiness check page even though all the checks do actually pass if the server responds in time.

I can see a couple of solutions to this.

1) Give the option or show where we can change the AngularJS timeout, so it can be longer.
2) Give the option to run checks individually instead of sending all the requests at the same time.
3) Make the "Try Again" button check only the ones that have failed, instead of checking all of them at the same time.

This isn't a big deal, since Magento2 in a production environment wouldn't be on this constrained of a machine, but it does make it so that I can't test and prototype on my local machine.

Any thoughts?

**Comment by piotrekkaminski** [comment]
@tanya-soroka can you look into that?

**Comment by mazhalai** [comment]
@frehner we are working on this. Ticket # MAGETWO-43385

**Comment by frehner** [comment]
Thanks, glad to know!

**Comment by mazhalai** [comment]
@frehner this issue has been fixed in 2.0.0. Closing this issue. Please open a new one if it persists.
