### ISSUE TITLE
Magento 2 Create Order Programatically, Not working via cron job

### ISSUE THREAD

**Issue by ERajkumar** [magento/magento2#16402]
### Preconditions

1.  PHP 7.0
2. Mysql 5.6
3. Ubuntu 16.04
4. Magento 2.1

### Steps to reproduce

1.  Order Programmatically via cron

I am working on the subscription-based module, I need to put order based on subscription. so I write a code to create order.  If run this cron using [n98-magerun2.phar](https://github.com/netz98/n98-magerun2) plugin its works fine. But Once I configured cron job its stop before setup shipping method.

Suggest Me Why it's failing. 

**What I did:**

 		<?php

		namespace Vendor\Module\Helper;

		class DailyOrder extends \Magento\Framework\App\Helper\AbstractHelper
		{
		    protected $customerSession;

		    protected $_storeManager;

		    protected $_productFactory;

		    protected $quoteManagement;

		    protected $customerFactory;

		    protected $customerRepository;

		    protected $orderService;

		    protected $cartRepositoryInterface;

		    protected $cartManagementInterface;

		    protected $shippingRate;

		    protected $orderFactory;

		    public function __construct(
			\Magento\Framework\App\Helper\Context $context,
			\Magento\Store\Model\StoreManagerInterface $storeManager,
			\Magento\Catalog\Model\ProductFactory $productFactory,
			\Magento\Quote\Model\QuoteManagement $quoteManagement,
			\Magento\Customer\Model\CustomerFactory $customerFactory,
			\Magento\Customer\Api\CustomerRepositoryInterface $customerRepository,
			\Magento\Sales\Model\Service\OrderService $orderService,
			\Magento\Quote\Api\CartRepositoryInterface $cartRepositoryInterface,
			\Magento\Quote\Api\CartManagementInterface $cartManagementInterface,
			\Magento\Quote\Model\Quote\Address\Rate $shippingRate,
			\Magento\Customer\Model\Session $customerSession,
			\Magento\Sales\Model\OrderFactory $orderFactory
		    ) {
			$this->_storeManager = $storeManager;
			$this->_productFactory = $productFactory;
			$this->quoteManagement = $quoteManagement;
			$this->customerFactory = $customerFactory;
			$this->customerRepository = $customerRepository;
			$this->orderService = $orderService;
			$this->cartRepositoryInterface = $cartRepositoryInterface;
			$this->cartManagementInterface = $cartManagementInterface;
			$this->shippingRate = $shippingRate;
			$this->customerSession = $customerSession;
			$this->_logger = $context->getLogger();
			$this->orderFactory = $orderFactory;
		    }

		    public function CronDailyOrder($one_time_order, $order_price)
		    {
			//init the store id and website id @todo pass from array
			date_default_timezone_set('Asia/Kolkata');
			$this->_logger->addDebug(date('Y-m-d H:i:s'));
			$store = $this->_storeManager->getStore();
			$websiteId = $this->_storeManager->getStore()->getWebsiteId();

			//init the customer
			$customer=$this->customerFactory->create()->load($one_time_order["customer_id"]);
			$customer->setWebsiteId($websiteId);
			$customer_login = $this->customerSession->setCustomerAsLoggedIn($customer);

			if ($customer_login->isLoggedIn()) {
			    $this->_logger->addDebug("Customer Logged in");

			    /* order place based on subscription */

			    //init the quote
			    $cart_id = $this->cartManagementInterface->createEmptyCart();
			    $cart = $this->cartRepositoryInterface->get($cart_id);

			    $cart->setStore($store);

			    // if you have already buyer id then you can load customer directly
			    $customer= $this->customerRepository->getById($this->customerSession->getCustomer()->getId());
			    $cart->setCurrency();
			    $cart->assignCustomer($customer); //Assign quote to customer

			    /*start to add product to cart */
			    try {
				$product_id  = $one_time_order['product_id'];
				$price  = $one_time_order['product_price'];
				$quantity  = $one_time_order['qunatity'];
				$this->_logger->addDebug("cart Product id: " .$product_id);
				$this->_logger->addDebug("cart Price: " .$price);
				$this->_logger->addDebug("cart quantity: " .$quantity);
				$product = $this->_productFactory->create()->load($product_id);
				// $product->setPrice($price);
				$product->setPrice($order_price);
				$cart->addProduct(
				                $product,
				                intval(1)
				            );
			    } catch (Exception $e) {
				$this->_logger->addDebug("addtocart exception " .$product_id);
				$result['Status']= "500";
				$result['Message']= "product_not_addtocart";
				return $result;
			    }
			    //Set Address to quote

			    /*Prepare address for billing and shipping address*/
			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    $this->_logger->addDebug("get customer info");
			    $users_data = $this->customerRepository->getById($one_time_order["customer_id"]);
			    $customer_data = $users_data->__toArray();
			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    $address = array();

			    $address['firstname'] = "xxxx";
			    $address['lastname'] = "xxxxx";
			    $address['street'] = "xxxxx";
			    $address['city'] =  "xxxx";
			    $address['country_id'] = "xx";
			    $address['region_id'] = "xxxx";
			    $address['postcode'] = "xxxxxxx";
			    $address['telephone'] = "xxxxxx";
			    // $address['save_in_address_book'] = "1";
			    $this->_logger->addDebug("assign shipping address" . serialize($address));

			    $shipping_addr = array();
			    $shipping_addr['addresses'] = $address;
			    // print_r($shipping_addr['addresses']);
			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    //Set Address to quote @todo add section in order data for seperate billing and handle it
			    $cart->getBillingAddress()->addData($shipping_addr['addresses']);
			    $cart->getShippingAddress()->addData($shipping_addr['addresses']);

			    $this->_logger->addDebug("set billing and shipping address");

			    // Collect Rates and Set Shipping & Payment Method
			    $this->shippingRate
			    ->setCode('freeshipping_freeshipping')
			    ->getPrice("0");

			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    $this->_logger->addDebug("currently we are set free shipping");
			    $this->_logger->addDebug("before get shipping address");

			    $shippingAddress = $cart->getShippingAddress();

			    $this->_logger->addDebug("before get shipping address");

			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    // set in order data

			    $shippingAddress->setCollectShippingRates(true)
			    ->collectShippingRates()
			    ->setShippingMethod('freeshipping_freeshipping'); //shipping method

			    $this->_logger->addDebug("set shipping method");
			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    $cart->getShippingAddress()->addShippingRate($this->shippingRate);

			    $this->_logger->addDebug("free shipping");

			    $cart->setPaymentMethod('checkmo'); //payment method

			    $this->_logger->addDebug("assign payment method");

			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    //@todo insert a variable to affect the invetory
			    $cart->setInventoryProcessed(false);

			    $this->_logger->addDebug("invetory process");

			    // Set sales order payment
			    $cart->getPayment()->importData(['method' => 'checkmo']);

			    // Collect total and saeve
			    $cart->collectTotals();

			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    $this->_logger->addDebug("collection total");

			    // Submit the quote and create the order
			    $cart->save();
			    $this->_logger->addDebug("save the cart");

			    $this->_logger->addDebug(date('Y-m-d H:i:s'));

			    // total_qty_ordered

			    $cart = $this->cartRepositoryInterface->get($cart->getId());
			    $order_id = $this->cartManagementInterface->placeOrder($cart->getId());
			    if ($order_id !="") {

			       echo "order placed successfully";

			    } else {
				$result['Status']= "500";
				$result['Message']= "order_not_placed";
			    }
			    return $result;
			} else {
			    $this->_logger->addDebug("Customer not Logged in while cron");
			    $result['Status']= "500";
			    $result['Message']= "customer_not_login";
			    return $result;
			}
		    }
		}
Once run  cron call this helper to put order,  But stop before setting shipping method.

            $shippingAddress->setCollectShippingRates(true)
			    ->collectShippingRates()
			    ->setShippingMethod('freeshipping_freeshipping'); //shipping method

Suggest Me, Why? and How to fix this.

**Referenece:**  https://magento.stackexchange.com/questions/231363/create-order-programatically-not-working-via-cron

**Comment by magento-engcom-team** [comment]
Hi @ERajkumar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ERajkumar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mhauri** [comment]
Hi @ERajkumar 

GitHub is intended for bug reports only, as you already opened the same question on [Magento Stack Exchange](https://magento.stackexchange.com/questions/231363/create-order-programatically-not-working-via-cron) it's not necessaryto ask the same question here.

**Comment by usman786cs** [comment]
I'm facing same issue, any fix please?
