### ISSUE TITLE
Vimeo with froogaloop2.min.js cdn results in 504

### ISSUE THREAD

**Issue by wintermute-84** [magento/magento2#16419]
### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Add vimeo video to product
2. See the product page

### Expected result

1. Video playing

### Actual result

1. Video is not loading in every browser except safari on mac os (for unknown reason)
The issue is actually in https://secure-a.vimeocdn.com/js/froogaloop2.min.js that results in 504 gateway timeout

Also looks like vimeo has it's own player and migration notes from froogaloop:
https://github.com/vimeo/player.js#migrate-from-froogaloop

Here is a vanilla instance where video situation can be checked:
http://46.101.28.242/fusion-backpack.html

**Comment by magento-engcom-team** [comment]
Hi @wintermute-84. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@wintermute-84 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by wintermute-84** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @wintermute-84. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @wintermute-84, here is your [Magento instance](https://i-16419-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16419-2-2-4.engcom.dev.magento.com/admin](https://i-16419-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by luoxulx** [comment]
@magento-engcom-team  Can you tell the difference between the next 2.2-develop and 2.3-develop versions? Which is more stable and better performance?Thanks!

**Comment by wintermute-84** [comment]
@magento-engcom-team the deployed vanilla instance is useless as it is not possible to upload any media 
(file not found in temp folder)

**Comment by wintermute-84** [comment]
added a link to the vanilla m2 page where video problem can be seeing
http://46.101.28.242/fusion-backpack.html

**Comment by ghost** [comment]
@magento-engcom-team , yes, I can confirm this issue, Check Below URL for vanilla Magento CE Instance Provided by you.

https://i-16419-2-2-4.engcom.dev.magento.com/test-simple.html

Video is looking for https://secure-a.vimeocdn.com/js/froogaloop2.min.js
Which can't be loaded with Instance.

**Comment by engcom-backlog-nickolas** [comment]
Hello @wintermute-84 , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by gelanivishal** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal, here is your [Magento instance](https://i-16419-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16419-2-2-4.engcom.dev.magento.com/admin](https://i-16419-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gelanivishal** [comment]
@wintermute-84 I have checked in v2.2.4 instance it is working well. Please check it.

**Comment by Knight017** [comment]
Hi,@magento-engcom-team any update on this.

**Comment by zipnfc** [comment]
I tried this and does not work on 2.2.6 as still using the old library - whilst we are waiting for this to be fixed, does anyone have the code fix and location to changes for this work properly with their updated https://player.vimeo.com/api/player.js' - thanks in advance

**Comment by holdenmonroe** [comment]
It seems like just today Vimeo has resolved the 504 error on the CDN: https://secure-a.vimeocdn.com/js/froogaloop2.min.js

This link works now seemingly and Vimeo videos now work on Magento.

**Comment by zipnfc** [comment]
Just tried it but sill waits for ages and eventually comes back with an error:

An error occurred while processing your request.
Reference #97.99e86768.1540994119.41d4cdb

**Comment by holdenmonroe** [comment]
Weird it was working this morning... now it's only partially working maybe half the time or not at all.

**Comment by zipnfc** [comment]
I seem to remember seeing something about it being cached so depends on where you get bounced as to whether you get it or not. 

I think we need Magento to use the new library or use YouTube. Unfortunately our business has everything on Vimeo !!

**Comment by holdenmonroe** [comment]
Having the same problem right now everything is on Vimeo. We are trying to work to have everything moved to Youtube due to this problem.

**Comment by zipnfc** [comment]
As I am new to the process on here so can someone explain how the backlog is prioritised / actioned? Is there a candidate list for the next release?

Cheers.

**Comment by zipnfc** [comment]
I have managed to get this working with the following changes - seems fine and tested on various browsers, but not 100% convinced it is the correct approach:

copied and changed two files:

1: vendor/magento/catalog_product_video/view/frontend/web/js/fotorama-add-video-events.js

Changed line 454 - element.src from

`element.src = 'https://secure-a.vimeocdn.com/js/froogaloop2.min.js';` 
to
 `element.src = 'https://player.vimeo.com/api/player.js';`

2: vendor/magento/catalog_product_video/view/frontend/web/js/load-player.js

Commented out these lines as when in they caused an error in the browser console and from what I can tell are not required.

`//this._player = window.$f(this.element.children(':first')[0]);

            // Froogaloop throws error without a registered ready event
           /* this._player.addEvent('ready', function (id) {
               $('#' + id).closest('.fotorama__stage__frame').addClass('fotorama__product-video--loaded');
            });*/`

Cleared cache and rebuilt and all seems good.  Look forward to getting the real fix, but this is at least allowing us to use our vimeo videos - here is an example of it working on our test site we are building:

https://zipnfc.store/nfc-encoding-and-scanning.html

**Comment by jordanbernadel** [comment]
Here's a patch from Magento support : 
[MDVA-12264_EE_2.2.4_v1.composer.txt](https://github.com/magento/magento2/files/2554503/MDVA-12264_EE_2.2.4_v1.composer.txt)

In vendor/magento/catalog_product_video/view/frontend/web/js/fotorama-add-video-events.js, they change : 
--> element.src = 'https://secure-a.vimeocdn.com/js/froogaloop2.min.js';
for
--> element.src = 'https://f.vimeocdn.com/js/froogaloop2.min.js';

**Comment by FYBYR** [comment]
> Here's a patch from Magento support :
> [MDVA-12264_EE_2.2.4_v1.composer.txt](https://github.com/magento/magento2/files/2554503/MDVA-12264_EE_2.2.4_v1.composer.txt)
> 
> In vendor/magento/catalog_product_video/view/frontend/web/js/fotorama-add-video-events.js, they change :
> --> element.src = 'https://secure-a.vimeocdn.com/js/froogaloop2.min.js';
> for
> --> element.src = 'https://f.vimeocdn.com/js/froogaloop2.min.js';

How is this applied? v2.2.6 I have changed this file but the 

element.src = 'https://secure-a.vimeocdn.com/js/froogaloop2.min.js';

link stays the same and I have recompiled and it does not change

**Comment by gclift** [comment]
Hey @Prizm4all,

The _patch_ command on linux can be used for one off patches. Using composer will always apply the patch on updates which is the best practice if you are going to use patches. Note, the patch file jordanbernadel submit was applied to line 444 but on our 2.2.6 instance, the starting line was 450. 

Here is a good article on using composer to add the patch. https://support.magento.com/hc/en-us/articles/360005484154-Create-a-patch-for-a-Magento-2-Composer-installation-from-a-GitHub-commit.

I hope this helps.

**Comment by BB-000** [comment]
Is there a 2.2.5 patch available for this? 

Edit: Don't need it anymore, just did a theme override, someone else might want it though

**Comment by tr33m4n** [comment]
For reference, here's a guide on migrating away from Froogaloop, I'd imagine this would need to be applied to Magento's Vimeo player functionality https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md

**Comment by tr33m4n** [comment]
My bad, clicked the close button by accident

**Comment by BiteSPT** [comment]
https://youtu.be/1qE2VbZnb-s Spanish solution but it works

**Comment by joshdavenport** [comment]
Froogaloop references are still in fotorama-add-video-events.js in [2.4-develop](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ProductVideo/view/frontend/web/js/fotorama-add-video-events.js) and [2.5-develop](https://github.com/magento/magento2/blob/2.5-develop/app/code/Magento/ProductVideo/view/frontend/web/js/fotorama-add-video-events.js) so one can only assume this is reproducable in 2.4 and 2.5. Seemingly adding vimeo videos is niche, which sucks for those of us who want to use it :(
