### ISSUE TITLE
links

### ISSUE THREAD

**Issue by pavanusn** [magento/magento2#1642]
In admin panel links are not working

**Comment by vpelipenko** [comment]
@pavanusn, could you provide more details? Which links?

**Comment by pavanusn** [comment]
those are Sales, Products,Customers,Marketing,Content,Reports,Stores...
 
Which are in left side nav-bar..

**Comment by vpelipenko** [comment]
@pavanusn, can you see some JS errors in console? which Magento version do you use?

**Comment by pavanusn** [comment]
it is working fine now
