### ISSUE TITLE
Uncaught SyntaxError: Unexpected token , on product page

### ISSUE THREAD

**Issue by SLv99** [magento/magento2#1643]
Hi,

I get the following error on a product page:
```
Uncaught SyntaxError: Unexpected token ,
```

This comes from the script in base-image.phtml. When I comment the "[data-role=media-gallery]": { function the error is gone. It's thrown from scripts.js, the getNodeData function.

**Comment by kandy** [comment]
Could you please provide browser version?

**Comment by SLv99** [comment]
I had to reinstall Magento due to another error. After reinstall I cannot reproduce the error anymore.

**Comment by patrickpeng2091** [comment]
hello ,
I encountered the same problem。
![image](https://cloud.githubusercontent.com/assets/4326820/15602387/8519dbe8-2427-11e6-85fe-a1ebd481e9ac.png)
VM12300:1 Uncaught SyntaxError: Unexpected token < in JSON at position 104688

chrome :  50.0.2661.102 (64-bit)
firefox: 46.0.1

**Comment by Jeeva-Rathinam** [comment]
@patrickpeng830 Did you solve the issue, i have same error during add-to-cart button in CM page -> code https://justpaste.it/49eqz
