### ISSUE TITLE
[ERROR] PDOException: SQLSTATE[HY000]: General error: 1881 Operation not allowed when innodb_forced_recovery > 0

### ISSUE THREAD

**Issue by topjx** [magento/magento2#16443]
[ERROR] PDOException: SQLSTATE[HY000]: General error: 1881 Operation not allowed when innodb_forced_recovery > 0. in /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#2 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `zh...', Array)
#5 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `zh...', Array)
#6 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `zh...', Array)
#7 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `zh...', Array)
#8 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1853): Zend_Db_Adapter_Abstract->insert('zhgstore_websit...', Array)
#9 /Applications/MAMP/htdocs/magentoce/vendor/magento/module-store/Setup/InstallSchema.php(248): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('zhgstore_websit...', Array)
#10 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Model/Installer.php(868): Magento\Store\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#11 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Model/Installer.php(776): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#12 [internal function]: Magento\Setup\Model\Installer->installSchema()
#13 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Model/Installer.php(343): call_user_func_array(Array, Array)
#14 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#15 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#20 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#22 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#23 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#25 /Applications/MAMP/htdocs/magentoce/setup/index.php(35): Zend\Mvc\Application->run()
#26 {main}

Next Zend_Db_Statement_Exception: SQLSTATE[HY000]: General error: 1881 Operation not allowed when innodb_forced_recovery > 0., query was: INSERT INTO `zhgstore_website` (`website_id`, `code`, `name`, `sort_order`, `default_group_id`, `is_default`) VALUES (?, ?, ?, ?, ?, ?) in /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `zh...', Array)
#4 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `zh...', Array)
#5 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `zh...', Array)
#6 /Applications/MAMP/htdocs/magentoce/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `zh...', Array)
#7 /Applications/MAMP/htdocs/magentoce/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1853): Zend_Db_Adapter_Abstract->insert('zhgstore_websit...', Array)
#8 /Applications/MAMP/htdocs/magentoce/vendor/magento/module-store/Setup/InstallSchema.php(248): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('zhgstore_websit...', Array)
#9 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Model/Installer.php(868): Magento\Store\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#10 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Model/Installer.php(776): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#11 [internal function]: Magento\Setup\Model\Installer->installSchema()
#12 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Model/Installer.php(343): call_user_func_array(Array, Array)
#13 /Applications/MAMP/htdocs/magentoce/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#14 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#19 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /Applications/MAMP/htdocs/magentoce/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#24 /Applications/MAMP/htdocs/magentoce/setup/index.php(35): Zend\Mvc\Application->run()
#25 {main}

**Comment by magento-engcom-team** [comment]
Hi @topjx. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@topjx do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by topjx** [comment]
![2018-06-28 4 56 15](https://user-images.githubusercontent.com/13688627/42024248-4eaa1fca-7af4-11e8-8ad7-10b25b862555.PNG)

**Comment by topjx** [comment]
Not sure this is actually an issue or not but I'm not experiencing issues with other plugins so I'll post it.

I'm no expert in mysql/apache/php at all so when my MAMP setup got screwed up I was trying a bunch of different solutions and one that fixed it was setting innodb_forced_recovery to 2. Everything on my craft site has worked fine except for SuperTable - it seems to error out when trying to use it under this forced recovery setting.

Fortunately I set it back to 0 and things seem to be working just fine now.

**Comment by anilbajracharya** [comment]
try searching  innodb_forced_recovery on my.cnf or php.ini and comment it out with # at beginning

**Comment by orlangur** [comment]
Yeah, `0` should work according to https://stackoverflow.com/questions/25155777/operation-not-allowed-when-innodb-forced-recovery-0-sqlyog. Closing as not a Magento issue.
