### ISSUE TITLE
Wrong use of Magento\Framework\Exception\LocalizedException

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#1644]
The class `Magento\Framework\Exception\LocalizedException` expects a `\Magento\Framework\Phrase` object in the [constructor](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Exception/LocalizedException.php#L31), but it is instantiated with a string parameter in [`Magento\Framework\View\Element\UiComponent\Config\DomMerger::createDomDocument`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMerger.php#L322).

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-43682

**Comment by tzyganu** [comment]
@piotrekkaminski This looks like it's fixed now. Thank you for this. I will close the issue now.
