### ISSUE TITLE
Minicart does not get updated after paypal checkout

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1645]
Mini cart does not get updated after paypal checkout.
![image](https://cloud.githubusercontent.com/assets/3830093/9203509/3d56cd84-4075-11e5-9216-09d2dd0fb0ed.png)

**Comment by vpelipenko** [comment]
@bgkavinga, is it reproduced only with PayPal? Did you try another offline/online payment  methods? Offline Check Money Order for example?

**Comment by bgkavinga** [comment]
@vpelipenko Yes. It is working for check money order.

**Comment by vpelipenko** [comment]
@bgkavinga, which version do you use? We can't reproduce this issue internally. Looks like you session was expired during checkout. Could you provide more details? Ideally, step-by-step instruction.

**Comment by bgkavinga** [comment]
@vpelipenko I am using the code from master(1.0.0-beta) branch. Please check the screen cast.
https://youtu.be/bHS-mI_7OHM

**Comment by vpelipenko** [comment]
Hi @bgkavinga, probably it is an issue in 1.0.0-beta version. In current development version it can't be reproduced. All works as expected.

**Comment by bgkavinga** [comment]
ok. Thanks I will check with new version.

**Comment by sivaschenko** [comment]
Feel free to reopen if you are able to reproduce this issue.

**Comment by grasdaggel** [comment]
Bug occours on Magento 2.0.4 again. Wrote an issue about that: #4114
