### ISSUE TITLE
Unable to install sample data on Magento 2.2.6-dev

### ISSUE THREAD

**Issue by Gurdit** [magento/magento2#16457]
### Preconditions

1. Magento 2.2.6-dev
2. php 7.0.30

### Steps to reproduce

1. Clone [magento](https://github.com/magento/magento2) github repository on localhost
2. After successful installation composer update to install sample data
3. Command used php bin/magento sampledata:deploy

### Expected result

[1. Sample data get installed.]

### Actual result
 
![error](https://user-images.githubusercontent.com/4478648/42078402-f4e35a50-7b99-11e8-855a-7c61ce4b0dbe.png)
[Problem 1
    - The requested package magento/module-downloadable-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package magento/sample-data-media could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package magento/module-theme-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package magento/module-widget-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package magento/module-msrp-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package magento/module-configurable-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package magento/module-product-links-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package magento/module-catalog-rule-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package magento/module-grouped-product-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 10
    - The requested package magento/module-tax-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 11
    - The requested package magento/module-bundle-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 12
    - The requested package magento/module-sales-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 13
    - The requested package magento/module-customer-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 14
    - The requested package magento/module-offline-shipping-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 15
    - The requested package magento/module-swatches-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 16
    - The requested package magento/module-sales-rule-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 17
    - The requested package magento/module-cms-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 18
    - The requested package magento/module-catalog-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 19
    - The requested package magento/module-review-sample-data could not be found in any version, there may be a typo in the package name.
  Problem 20
    - The requested package magento/module-wishlist-sample-data could not be found in any version, there may be a typo in the package name.]

**Comment by magento-engcom-team** [comment]
Hi @Gurdit. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Gurdit do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Gurdit** [comment]
@magento-engcom-team give me {2.2.6-dev} instance

**Comment by dmanners** [comment]
Hi @Gurdit when using a clone of Magento 2 you will also need to clone in the sample data rather than using the bin/magento command. See https://devdocs.magento.com/guides/v2.2/install-gde/install/sample-data-after-clone.html for more information on how to do this.

**Comment by orlangur** [comment]
> After successful installation composer update to install sample data

There is no need in this as mentioned command `php bin/magento sampledata:deploy` does it by itself.

**Comment by chokri** [comment]
I used it with 2.2.5 and still have the same errors.

**Comment by Leandry** [comment]
Hi @chokri and @Gurdit 

This will be expected result when you trying to install sample data using `bin/magento` command after cloning Magento 2.

Try to install sample data for cloned Magento, please, use [instruction](https://devdocs.magento.com/guides/v2.2/install-gde/install/sample-data-after-clone.html)

**Comment by Gurdit** [comment]
Thanks @Leandry
