### ISSUE TITLE
Customer Attribute  - Visible/Required per website behavior

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#16452]
Last days I've been working a lot with Customer Attributes. They're inconsistent and complicated by default, however managable. (Last time when I worked with them, I updated Dev Documentation: https://devdocs.magento.com/guides/v2.2/extension-dev-guide/attributes.html#customer-eav-attribute).

Currently I'm thinking about doing contribution to Customer Attributes, however I need as much information as I can get from Magento Architects (@maghamed - can I count on you?)

### Preconditions
1. I'm working on Magento 2.2-dev.
2. Clear installation without any customizations.
3. Two `website` (let's say `b2c` and `b2b` codes) scopes created (one `store` in each)

### Steps to reproduce
1. Create new Customer attribute (`myattribute`) with Admin UI, setting default visibility to `Yes`, and `Required` to `Yes`
2. Switch the scope to `b2b` and change `visible` and `required` to `No`
3. Open Edit form for one of the customers that was registered to `b2b` website.

### Expected result
1. As I disabled field visibility in `b2b` website scope, I'd expect that `myattribute` field will be no longer displayed for customer registered with `b2b` scope. Let's assume that I need some fields that are required only for B2B website, which cannot be shown to B2C users.

### Actual result
1. The `myattribute` field is still visible. Althought it's not required, but still visible.

### My point of view
1. After my contribution, I'd expect the `myattribute` to be invisible, and even if it has `visibility` switched to  No and `required` to Yes

### Steps to reproduce
1. Create new Customer attribute (`myattribute`) with Admin UI, setting default visibility to `No` and required to `No`.
2. Switch the scope to `b2b` and change `visible` and `required` to `Yes`

### Expected result
1. As I disabled field visibility and marked as not required globally:
  - when I edit customer registered for `b2c` website, I should not see `myattribute`
  - when I edit customer registered for `b2b` website, I should see `myattribute`

### Actual result
1. The `myattribute` is not visibl to `b2c` but is visible to `b2b` as it should be which is fine.

### My point of view
We can understand global scope with 2 ways:
1. Global scope settings are callback if scope settings were not set. *I prefer this*
2. Global scope `visible` setting overrides the scope setting, so if I disable attribute globally, it should not be visible even if locally it's enabled.

### Actual result
When I assign `backend_model` to the attribute (using database, as a shortcut), and disable attribute visibility globally, enable it to `b2b` and edit the customer (/ add the customer), the attribute value is not passed to the `backend_model`, even if it's filled properly.

**However** when I just enable attribute visibility globally, it is passed to the backend model.

### Expected result
Attributes of the customer should be passed not depending on the global setting, but depending on the local setting (for current scope) of the attribute. So if I'm registering as a customer for B2B website, I'd rather expect that data I provided for registration form is passed to the Backend Model - eg. to be validated (that was my purpose).

## Before contribution

Is there anyone who can explain me why attribute Backend Model `validate()` (or `validation()` method is not executed everytime when the object is going to be saved, just for specific cases like admin saves it?

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lbajsarowicz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @lbajsarowicz  , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
