### ISSUE TITLE
unable to add database in setup

### ISSUE THREAD

**Issue by MenDo2015** [magento/magento2#1648]
I cant install magento 2 (Step 2: Add a Database), when i click "Next" nothing happens. i tried Firefox, chrome, edge ... the same result.

I use Xampp  and I install Magento 1.9 without any problem.

in the Apache error log :
[Wed Aug 12 00:16:29.874552 2015] [:error] [pid 4880:tid 1900] [client 127.0.0.1:64735] PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0, referer: http://127.0.0.1/magento2/setup/

**Comment by joshuakleveter** [comment]
Having the same problem here. I've tried both the master and dev branches.

**Comment by buskamuza** [comment]
Hi, @MenDo2015 , @joshuakleveter ,
do you still have this issue?
@joshuakleveter , could you provide a Vagrant setup, so we could try and debug it? Thanks.

**Comment by MenDo2015** [comment]
Yes.

**Comment by xcomSteveJohnson** [comment]
is the php_pdo extension installed?

**Comment by piotrekkaminski** [comment]
Closing due to no response.
