### ISSUE TITLE
page_layout for 3columns and 2columns right is missing

### ISSUE THREAD

**Issue by riconeitzel** [magento/magento2#1649]
corresponding page_layout/*.xml files are bare copies of 2columns-left

**Comment by vpelipenko** [comment]
@riconeitzel, could you give us more details? Want to understand where is issue.

**Comment by riconeitzel** [comment]
@vpelipenko there is a 3columns.xml file but it's just configuring a 2columns page … so technically there is no 3 columns design available in Magento.

**Comment by eug123** [comment]
Markup and column containers for 2 columns and 3 columns layouts are the same. Visual representation of sidebars is controlled via css class added to the body like .page-layout-3columns automatically depending on layout applied.
You can always add your custom layout. Please check the [documentation](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/layout-types.html#layout-types-page)
