### ISSUE TITLE
Adding columns to sales order grid AJAX call

### ISSUE THREAD

**Issue by kassner** [magento/magento2#1650]
Hi,

Since 1.0.0-beta the Sales Order Grid retrieves all data using an AJAX call and renders the columns and rows using Javascript only. To gather the data to assemble the grid, a call to `/backend/mui/render/index` is made.

With some inspection, I found out that the AJAX result is based on the `sales_order_grid` table, all columns from this table are retrieved. The confusing part is [this piece of code](https://github.com/magento/magento2/blob/e5a2d0052e8066f14f5e27f7696d6b0c19b6ff48/app/code/Magento/Sales/etc/di.xml#L275-L321), that looks like the configuration for the dataset, but can be removed and the grid keeps working (didn't checked the frontend).

That piece of code is used somewhere else? Can't I add a join to `sales_order_grid`? Is there a way (observer) to intercept this dataset?

Thanks!

**Comment by blankapham** [comment]
Hi
After I view some code of Magento 2, I can help you do that.
1. Ui component is in app\code\Magento\Sales\view\adminhtml\ui_component\sales_order_grid.xml
If searching dataSource you can find class OrderGridDataProvider - that you can find in di.xml (app\code\Magento\Sales\etc\di.xml)
2. Class collection for this grid is: Magento\Sales\Model\Resource\Order\Grid\Collection (find in di.xml line 541) and if viewing this file you can find 2 lines:
protected $_eventPrefix = 'sales_order_grid_collection';
protected $_eventObject = 'order_grid_collection';
So you can catch 2 events(sales_order_grid_collection_load_before, sales_order_grid_collection_load_after) and custom this collection

If having any problem in my answer, hoping everyone comments to have a perfect solution for this.
Thanks,

**Comment by sivaschenko** [comment]
Hi,

Referenced di configuration is used for filling sales_order_grid (index table) with data (during place order operation or later, according to dev/grid/async_indexing config value).

There are two ways of adding custom columns to sales order grid:
* Update grid index table (alter sales_order_grid) - ensures good performance of sales order grid, but can have influence on place order performance if asynchronous indexing is disabled.
* Replace/modify collection used by ui component (advantage is less changes to be made, disadvantage is bypassing grid indexing - grid view performance)

Second approach is described by blankapjam in previous comment.

With the first approach you have to perform 3 changes:
* Add columns to sales_order_grid table (install/update script)
* Extend referenced di configuration to make sure new columns will be populated
* Add columns and corresponding filters on frontend extending app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_grid.xml

**Comment by vpelipenko** [comment]
@kassner, do you have another questions?

**Comment by kassner** [comment]
Hi,

Sorry for the delay, I was working with something else in meanwhile.

@blankapham Thank you for this explanation about dataSource, now I understand how it works.

Where did you find the `protected $_eventPrefix = 'sales_order_grid_collection';` line? Looks like `Magento\Sales\Model\Resource\Order\Grid\Collection` is a virtualType and there is no eventPrefix set anywhere. I've grep'd the entire repo and could not find it.

@sivaschenko Thank you as well. I was able to overwrite the Collection mentioned above in `di.xml`, but I'm not yet sure which approach is more suitable for my specific case (I need to show some aggregated data from my own tables).

@vpelipenko keep this open for a while, sivaschenko mentioned about "asynchronous indexing" and I'll run some tests (I'm presuming that sales_order_grid is not populated in such case).

**Comment by sivaschenko** [comment]
@kassner, I you are not sure which approach to choose, I would recomend you second one (Replace/modify collection used by ui component).
According to populating of sales_order_grid - please take a look at https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/Observer/IndexGrid.php

**Comment by LifeAsBook** [comment]
@sivaschenko  how to Extend referenced di configuration to make sure new columns will be populated?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by mdmujassam** [comment]
hi,
@kassner ,  did you achieve the joining the collection for sales/order/grid..
I can add the column but unable to join the collection, Help me if anybody have the solution..
I want to join the sales_grid_collection with my table to display the custom column data in sales order grid..

Thanks

**Comment by m1keharris** [comment]
This solution doesn't seem to work in version 2.0.4, is there a new way to do this now, it would appear that sales_order_grid_collection_load_before is no longer a valid event.

**Comment by sivaschenko** [comment]
@kassner, @LifeAsBook, @mdmujassam, @m1keharris See [these notes](http://blog.sivaschenko.com/2016/05/magento-2-tutorial-add-column-to-sales.html) for detailed instructions.
