### ISSUE TITLE
Big Performance issue with query pagination

### ISSUE THREAD

**Issue by lucasgonzalez** [magento/magento2#16516]
### Preconditions

1. Magento v 2.2.2 (and probably any other version)

### Steps to reproduce

1. Every collection using the limit offset to paginate the results

### Expected result

1. Not run a SELECT COUNT(*) on the entire collection if I just ask for 10 items

### Actual result

1. SELECT COUNT(*) is run against the entire collection

The code with the bug is:

```
public function getCurPage($displacement = 0)
    {
        if ($this->_curPage + $displacement < 1) {
            return 1;
        } elseif ($this->_curPage + $displacement > $this->getLastPageNumber()) {
            return $this->getLastPageNumber();
        } else {
            return $this->_curPage + $displacement;
        }
    }
```

Basically that code is wrong not only for performance but also for functionality. But the big performance issue, is that every time a page is set, the code tries to find the last page number, which actually does a SELECT COUNT(*).

So, let's said we have a table with 10M rows, and I just ask page 1 with 10 items per page, I will expect that to be pretty fast. But instead of that I may have to wait a lot of time, because it is counting the entire table just to be sure that we are not trying to find an invalid page.

And even if we try to find an invalid page, the right behavior should be to return an empty collection.

**Comment by magento-engcom-team** [comment]
Hi @lucasgonzalez. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lucasgonzalez do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@lucasgonzalez regarding the "an invalid page, the right behavior should be to return an empty collection" this has already been reported, there are a couple of WIP PRs on this matter now.

Regarding performance of `SELECT COUNT(*)`, there is no such issue, we should do it to determine amount of pages and it is not a heavy operation having appropriate indexes.

**Comment by lucasgonzalez** [comment]
I do not know why the issue is closed. 

Clearly we expect different result in the performance. Having to wait for a count(*) to finish when there is no real need for it, is not ok. Please explain why we need to wait for the count if I just want the first 10 results?

Also how do you create a proper index if you are not filtering for anything?

I just try a SELECT COUNT(*) in a database using Amazon Aurora, with a bit more than 100M rows, and it took 48 seconds to run.

If I run this on the magento table:

`select count(*) from sales_order_grid`

it takes 1.5 seconds to return 8M.

Again, there is no need to wait 1.5 seconds if I do not want that result, I just want the first 10 items.

And that was only using that table, if I try to join that to other tables it will be slower.

So again, can you explain me how this is not a real issue?

**Comment by orlangur** [comment]
> why we need to wait for the count if I just want the first 10 results?

Because last page must be obtained according to current logic and it cannot be removed out of the blue.

The issue is closed because such collection behavior is already reported and because count cannot be removed without losing functionality.

**Comment by lucasgonzalez** [comment]
let me clarify because I still do not know if someone will try to fix it or not.

First you said that it is not an issue -> which means that nobody is going to try to fix it
Now you said that it is an issue but it is already reported -> this means that someone at some point will try to fix it.

Which one is the real answer? I really need to know to see how I will try to fix it for my specific case.

The issue reported talked only about the functionality problem, but not that it is also a big performance penalty.


This is not the only issue with the COUNT (*) (maybe it is the worst, but not the only one).
But without fixing this first, there is no way to fix the others.
EX: in the admin grids, every time you change the page, the total number of records are being returned, but that information is already in the page, so why keep counting?

Thanks for you answers.

**Comment by orlangur** [comment]
@lucasgonzalez,

1) Calling `getLastPageNumber` is going to be removed from collection
2) Calling `COUNT(*)` cannot be removed in places where we, for example, calculate total amount of pages. You can do some caching in a custom project if MySQL caching is not enough for a particular huge table.

> that information is already in the page, so why keep counting?

As it could change on served side.
