### ISSUE TITLE
After installtion it takes long time to load the website 

### ISSUE THREAD

**Issue by chaluvadiswamy** [magento/magento2#1651]
After completed the magento installation  , i run the front end url  its keep loading.
It took almost 25sec load the website in local installtion.

**Comment by vpelipenko** [comment]
I think, it is ok for first run. System creates static content and generate caches. It requires some time.

**Comment by chaluvadiswamy** [comment]
But in admin panel section no js files are loading and after installing the inside pub/static template  skin is not creating.

**Comment by piotrekkaminski** [comment]
@chaluvadiswamy do you still have this issue? On what kind of server are you installing it?

**Comment by chaluvadiswamy** [comment]
@piotrekkaminski  Still the issue is existing and also loading time is taking more compare the existing magento version 1.9.2

**Comment by chaluvadiswamy** [comment]
@piotrekkaminski  Still i have same  issue, i have installed in the local by using XAMPP

**Comment by buskamuza** [comment]
@chaluvadiswamy , do you have xDebug enabled? It may slow-down the application significantly.

**Comment by chaluvadiswamy** [comment]
@buskamuza yes xDebug is enabled , if we disable that it will work

**Comment by chaluvadiswamy** [comment]
@buskamuza , after disabled the xDebug it is working properly.

**Comment by nathandallaire** [comment]
Hahaha buddy. 25 seconds is a dream. I ran a `php bin/magento c:f` (cache flush) and I have literally been waiting over 1 hour for this page to load.

**Comment by MohammedAlzard** [comment]
When the magento is installed it takes a long time
