### ISSUE TITLE
Magento_Email - overriding logo with logo_email.png

### ISSUE THREAD

**Issue by cshaw-inviqa** [magento/magento2#1652]
Hi,

Within my theme, I've created a Magento_Email directory with a web directory inside that. I've added a png asset in there called logo_email.png to override the default magento logo. However this does not work. Is this a bug or is there something else I need to do?

**Comment by eug123** [comment]
Hi,
Assets are published in the `pub/static` folder, please check
`pub/static/frontend/<yourVendor>/<yourTheme>/<locale>/Magento_Email/logo_email.png`
It may be published before you overrided default logo in your theme. Just delete this file from `pub/static` and try to check your emails again.

**Comment by cshaw-inviqa** [comment]
I did this but it didn't copy the logo into pub/static

**Comment by cshaw-inviqa** [comment]
FYI, it shows the correct logo in the template preview, just not in the email itself.

**Comment by eug123** [comment]
I've tried to reproduce your issue, checking using newsletter subscription on storefront and incoming email has right logo.
Please describe steps to reproduce.

**Comment by cshaw-inviqa** [comment]
This is order confirmation email:

1. I created a Magento_Email directory in our theme.
2. I added our logo in a web directory inside the Magento_Email directory
3. The logo is named logo_email.png
4. I modified the new order template in Magento_Sales/email/order_new.html
5. This uses this bit of code at the top:

```
<img
                                {{if logo_width}}
                                    width="{{var logo_width}}"
                                {{else}}
                                    width="169"
                                {{/if}}

                                {{if logo_height}}
                                    height="{{var logo_height}}"
                                {{else}}
                                    height="36"
                                {{/if}}

                                src="{{var logo_url}}"
                                alt="{{var logo_alt}}"
                                border="0"
                            />
```

6. I submitted an order
7. The confirmation email came through styled as per the overriden template, from point 4 above.
8. The logo doesn't come through. It's neither the default Magento logo or our logo.

Hopefully that'll help

**Comment by eug123** [comment]
Sorry, still cannot reproduce this issue
I've created custom theme,
overrode email logo file: `app/design/frontend/Magento/mytheme/Magento_Email/web/logo_email.png `,
overrode order confirmation template:
`app/design/frontend/Magento/mytheme/Magento_Sales/email/order_new.html`
Added your code (5) in the top of it.
Applied theme in the admin, cleared `var` and `pub/static` folders.
After completing checkout on storefront order confirmation email came with 2 'mytheme' logos.
- One was added in overridden template 
- Another comes from email header template: `app\code\Magento\Email\view\frontend\email\header.html`

**Comment by vpelipenko** [comment]
@cshaw-inviqa, which Magento version do you use?

**Comment by cshaw-inviqa** [comment]
Enterprise edition

**Comment by cshaw-inviqa** [comment]
Hi,

Yes, it just doesn't create the Magento_Email folder in pub/static

**Comment by nagno** [comment]
Hi @vpelipenko,

we are using Mage 2 Merchant Beta from the master branch.

**Comment by erikhansen** [comment]
@nagno @cshaw-inviqa I was involved in writing the functionality in question. I've never seen the issue you've described and it doesn't seem to be reproducible, but I'd like to dig into it to see whether it is a core bug or a user error. If you're able to provide FTP (or shell) access to a server where this issue is reproducible, I'll take a look at it. You can email me: erik [at] classyllama.com [dot] com

**Comment by eug123** [comment]
Hi, can you please check whether magento is running in production mode and `pub\static` folder permissions?

**Comment by nagno** [comment]
Thanks for your help.

Unfortunately Craig is on training for the next 3 days so probably he is not going to be available.

@erikhansen: Thanks for your help, unfortunately I cannot give you access, we have an NDA with the client. :( However I'm happy to check every suggestion you have.

@eug123: Magento is running in development mode (we are working on our development environment yet). The static folder has write access, all of the other frontend assets are there (we have adminhtml, frontend and _requirejs directories inside of it)

**Comment by sivaschenko** [comment]
Feel free to reopen this issue if any additional details that may be helpful to reproduce it will be discovered

**Comment by hellsanos** [comment]
Hi all
I am currently stuck on the same problem. Did the same tasks as described by @cshaw-inviqa with same result. Wrong logo is displayed in the emails.
Also no pub/static/frontend/VENDOR/THEME/lang_LANG/Magento_Email directory with the logo_email.png in it is created...

Any success yet on that "bug"?

**Comment by Brengineer** [comment]
I was having this same issue inexplicably, so I tried changing the name of the image file and (temporarily) changing \Magento\Email\Model\AbstractTemplate::DEFAULT_LOGO_FILE_ID to match, and then it worked. So **it appears that my email client was caching the image**.
