### ISSUE TITLE
bin/magento crashes when --no-dev is used

### ISSUE THREAD

**Issue by moleman** [magento/magento2#1653]
Hi,

It seems that a dependency for bin/magento is missing when you install the project with the --no-dev flag in Composer. The reason why you want to do this is because you don't want or need to have development requirements on a production site but you would still like to have bin/magento.

**How to reproduce it**
1. composer create-project magento/product-community-edition --stability="beta" --no-dev magento2
2. cd magento2
3. php bin/magento

**Error**
Autoload error: An abstract factory could not create an instance of magentosetupconsolecommandmoduleuninstallcommand(alias: Magento\Setup\Console\Command\ModuleUninstallCommand)

After digging around it seems that the symfony/event-dispatcher package is required for bin/magento not to crash with --no-dev. This package is required by the development requirement fabpot/php-cs-fixer which is why it is not installed when running with --no-dev.

I'm not sure if the symfony/event-dispatcher is really needed or used by bin/magento because it is only suggested by the symfony/console package.

**Comment by mazhalai** [comment]
@moleman thank you for reporting this issue. We have created MAGETWO-41422 to track this internally.

**Comment by piotrekkaminski** [comment]
This should be fixed now.
