### ISSUE TITLE
Configurable product: Get swatch attributes in list.phtml takes too much time

### ISSUE THREAD

**Issue by mritu19** [magento/magento2#16532]
**Preconditions**
Magento CE 2.2.0
PHP 7.0.23-1

Database migrated from 1.9.2 to 2.2.0

Checked with different instances and various versions.
Configured highest possible server configuration.

-We have one 'classicrings' category, there are only 12 configurable products. Each configurable product containing minimum 1100 simple products, some of them have more than 1500 simple products and total more than 13k products (including with configurable and simple variations) under one 'classicrings' category.

one configurable product have 5 attributes 'color, material,finishing,thickness,width' and we displaying the each product attributes on listing page, including with its all swatch options (like color :red,green,yellow.., material: 10k,14k,18k.., width:2mm,4mm to 12mm.. etc.)

**Steps to reproduce**

When we click on classicrings category (i.e. listing page in frontend) to display the all 12 configurable products in frontend then server going to time out Or loading page some times after 10 to 15 min.

-So, we debugged the list.phtml code and commented the below code, through from which all swatch 
attributes and its options is coming on listing page :

	//echo $block->getProductDetailsHtml($_product);
	
	After commenting above line of code, listing page start loading quickly within 2 sec. But this is not the solution. As client want to display the all attributes with its options, which is taking too much time to load and going server time out most of the time.
	

**Expected result**

category Product listing page should be load with all attribute and options, withing at least 2 to 5 seconds (Including with showing all attributes and options).

**Actual result**

Request Timeout

This request takes too long to process, it is timed out by the server. If it should not be timed out. Sometime system crashed.

For smaller product variations, it is loading good, but its also taking more than 40 seconds.

**Comment by magento-engcom-team** [comment]
Hi @mritu19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mritu19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mritu19** [comment]
@magento-engcom-team , we have also attached the variations list of one of the configurable product, for your reference : 

![image](https://user-images.githubusercontent.com/32297749/42278418-5f5a5420-7fb8-11e8-8412-caeb37ee2956.png)

**Comment by orlangur** [comment]
@kandy was this improved recently? I remember some improvements in changelog related to configurable product performance.

**Comment by mritu19** [comment]
Hi @orlangur @kandy .. can you please suggest any solutions/alternatives.

**Comment by mritu19** [comment]
Hi @verklov .. I would request you to please look into above issue and please share your feedback. 
Thanks !

**Comment by mritu19** [comment]
@magento-engcom-team @veloraven  @wert2all .. looking for feasible solution. any updates ?

**Comment by orlangur** [comment]
@mritu19 you need to find out MySQL queries which are slow in your case and try to optimize them.

**Comment by kandy** [comment]
@mritu19 I believe there is no the simple solution to show option/price for a 13k product.

In your case, I will recommend moving the loading  of option in a separate ajax call,  write code that load  only needed data and render  it in the browser

**Comment by mritu19** [comment]
@kandy  Thanks for your response.

Further, I would like to share with you that yes I have already implemented seperate ajax call for this page by loading each product's swatch options one by one through ajax call, But still page is loading much more time to load and user experience is not good.

Also, I have tried to fetch and display the swatch data by another method , using the concept of filter only one swatch attribute (in my case "Width" attribute). For the same, I  have overridden the "SwatchAttributesAsArray" function of class 'Magento\Swatches\Helper\Data'  by using plugin. But still its taking min 5 to 8 min to load the page.

Have implemented the code in below way:
//di.xml -- type name="Magento\Swatches\Helper\Data"
//plugin name="RestrictProductsOptions" type="Synapsemage\Import\Plugin\SwatchData" 

// class SwatchData
 public function afterGetSwatchAttributesAsArray($subject, $attributesData)
    {  
	    $actions = ['catalog_category_view','catalogsearch_result_index','catalogsearch_advanced_result'];
		if (in_array($this->getFullAction(), $actions))
		{	
			$objectManager = ObjectManager::getInstance();
		  	//get current category
		  	$categoryId = $parentId = 0;
			$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
			if($category!=null){
				$categoryId = $category->getId();
				$parentId = $category->getParentCategory()->getId();
			}
			//Here $categoryId==34 is my classicrings category which is containing 13k product and 182 indicates 'Width' attribute 
			
			if($categoryId==34){
				$newAttributesData = array();
				$newAttributesData[182] = $attributesData[182];
				// print_r($newAttributesData);die;
				return $newAttributesData;
			}

		  	foreach($attributesData as $attr)
		  	{
				$attrcode = $attr['attribute_code'];
				if(!empty($attrcode))
				{
					if($categoryId==44){
						if($attrcode=='stone'){
						  unset($attributesData[$attr['attribute_id']]);
						}
					}elseif($categoryId==31 || $parentId==31 || $categoryId==28){
						if($attrcode=='material'){
						  unset($attributesData[$attr['attribute_id']]);
						}
						if($categoryId==31 || $parentId==31){
							if($attrcode=='color'){
							  unset($attributesData[$attr['attribute_id']]);
							}
						}
						if($categoryId==33 ){
							if($attrcode=='stone'){
							  unset($attributesData[$attr['attribute_id']]);
							}
						}
					}elseif($categoryId==21 || $parentId==21){
						
						if($attrcode=='stone'){
						  unset($attributesData[$attr['attribute_id']]);
						}
					}				
				}			
		  	}
		}
		return $attributesData;
   	}

**Comment by mritu19** [comment]
Hi @orlangur 
I would like to share with you that I haven't modify any default query of magento2.. I am using the default/core code. 

The only things i have done :: I have added 5 attributes and there are many options in a configurable products. and combining all attributes options for a configurable product , total variations becomes around 1100 simple products under one configurable product. 

did  magento2 team not checked/test with only this much variations ?

@magento-engcom-team , @kandy  Can you please suggest us.. Can we see, configurable product performance better (with this much variation) in next version ?

**Comment by ghost** [comment]
@mritu19, thank you for your report.
We've acknowledged the issue and added to our backlog.
