### ISSUE TITLE
Magento CLI --db-host doesn't work

### ISSUE THREAD

**Issue by frehner** [magento/magento2#1655]
Trying to install Magento using Magento CLI. Here's the command I'm making

```
bin/magento setup:install --base-url=http://192.168.99.100:32773/ --db-host=mysql1 --db-name=magento --db-user=xxx --db-password=xxx --admin-firstname=xxx --admin-lastname=xxx --admin-email=xxx@xxx.com --admin-user=xxx --admin-password=xxx --language=en_US --currency=USD --timezone=America/Chicago --use-sample-data
```

But the error I get when I run this is:

```
SQLSTATE[HY000] [1045] Access denied for user 'xxx'@'phpfpm_mysql1' (using password: YES)
```

I've tried replacing "mysql1" with environment variables, with the IP address of the mysql host, etc., and they all give me the same error as above.  

The only thing that does actually seem to change the host is when I put in `--db-host=localhost`... but that obviously doesn't work since MySQL isn't running on that localhost. 

Bug? Or am I doing something wrong?

**Comment by mazhalai** [comment]
@frehner are you able to connect to the mysql host directly from your localhost? also, in the error you provided, it is attempting to connect to `phpfpm_mysql1`

**Comment by frehner** [comment]
@mazhalai As I've dug into it, there appears to be something wrong with the networking in my box.  Closing this ticket for the moment as it doesn't appear to be a Magento issue.
