### ISSUE TITLE
Shipping address entered when placing the order is overwritten with the PayPal delivery address

### ISSUE THREAD

**Issue by abhaykhatariya** [magento/magento2#16556]
### Preconditions

1. Coming this issue to all magento 2 version.
2. Configure sandbox or live Paypal details
3. Select country address as Russia

### Steps to reproduce

1. Try to checkout with Russia country address 
2. Select Paypal Express checkout. 

### Expected result

1. Place order should be successful. 

### Actual result

1. 
![screenshot](https://user-images.githubusercontent.com/23476956/42315280-b0399534-8064-11e8-9dbb-f29788a38881.png)

**Comment by magento-engcom-team** [comment]
Hi @abhaykhatariya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@abhaykhatariya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by abhaykhatariya** [comment]
Paypal Express checkout when shipping country is Russia not working

**Comment by pratikmage** [comment]
I have facing same issue.

**Comment by abhaykhatariya** [comment]
@mariuscris

**Comment by abhaykhatariya** [comment]
@tzyganu Can you please check this issue as it seems problem with all magento versions. 1.x and 2.x

**Comment by ghost** [comment]
@abhaykhatariya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please share your Paypal Express configuration.

**Comment by abhaykhatariya** [comment]
Removed

**Comment by ghost** [comment]
@abhaykhatariya, please share full Paypal Express configuration, not your credentials.

**Comment by abhaykhatariya** [comment]
@engcom-backlog-pb 

Please do find below

Merchant Country : US
API Authentication Methods  - API signature
Payment Action  Sale
Debug Mode	YEs
Payment Applicable From Allow all countries
Enable SSL verification Yes
Transfer Cart Line Items Yes
Transfer Shipping Options No
Skip Order Review Step Yes

![1](https://user-images.githubusercontent.com/23476956/43397199-9db41882-9421-11e8-98c1-325092b97679.png)

**Comment by ghost** [comment]
Hi @abhaykhatariya I'm not able to reproduce by your scenario, The problem in you side, please check your PayPal account settings

**Comment by abhaykhatariya** [comment]
@engcom-backlog-nazar 
I am 100% sure that if you do check with sandbox or live account into fresh magento 2 installation it will not work. currently i am facing same issue with magento 1.x and 2.x as well.

try to use below address while checkout as billing and shipping.

Svetlaya ul. Apt 191 (street name, house + apartment numbers)
Nizhnelunohodsk (city name)
Zabytaya oblast (region name)
877561 (postal index)
Russian Federation (country)

Because i have tried with magento 1.x and 2.x fresh installation too and same issue is coming for me when i am selecting russia as billing and shipping address into checkout.

**Comment by ghost** [comment]
@abhaykhatariya Problem not in magento side is your account setting to paypal specific to Russia ->https://developer.paypal.com/webapps/developer/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/   So magento have no response out paypal.

**Comment by ghost** [comment]
@abhaykhatariya also see exception log why paypal rejected request.

**Comment by abhaykhatariya** [comment]
@engcom-backlog-nazar 
Shipping address is invalid is the exception log but address is right. 
It seems problem with shipping address ...instead of override customer shipping address on paypal
it is taking paypal shipping address which is used into account.

**Comment by ghost** [comment]
@abhaykhatariya , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by abhaykhatariya** [comment]
@engcom-backlog-nazar 
see this video which i have prepare with fresh magento installation
http://www.screencast.com/t/8TsVQpgGEH

note : Please mute video to avoid background noise 👍

**Comment by abhaykhatariya** [comment]
@engcom-backlog-nazar @magento-admin 
Any update on this ?

**Comment by abhaykhatariya** [comment]
@engcom-backlog-nazar  Is it fixed on 2.2.6?

**Comment by ghost** [comment]
@abhaykhatariya Hi, no seems like still exist this issue.

**Comment by abhaykhatariya** [comment]
@engcom-backlog-nazar Are you going to provide solution to next release ?

**Comment by magento-engcom-team** [comment]
The Issue should be re-verified on the latest Magento code and re-Confirmed if its still actual
