### ISSUE TITLE
customizing widget.xml for CatalogWidget module

### ISSUE THREAD

**Issue by uchenic** [magento/magento2#1657]
How to overwrite widget.xml options without editing source codes in etc/widget.xml? Could it be done through creating file in theme? There are menu option to select different templates but new one  added in theme can`t be used without adding option to widget.xml.

PS excuse me for my english

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
