### ISSUE TITLE
Magento 2.2.3 add to cart button hangs in keep adding

### ISSUE THREAD

**Issue by hanzels** [magento/magento2#16578]
I am new here and now a little about Magento. We currently run a Magento 2 Store with the Porto theme from Smartwave.

We use the TIG PostNL extension for shipping. After the latest update of this extension the add to cart button doesn't work anymore. The nice people at TIG checked it and said nothing is disturbing the process.

In the log files I found: [06-Jul-2018 05:30:15 UTC] PHP Fatal error: Uncaught Error: Call to a member function getParentItem() on null in /home/fotoloom/public_html/app/code/Smartwave/Dailydeals/Observer/DealProductDiscountPrice.php:27 Stack trace: 0 /home/fotoloom/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Smartwave\Dailydeals\Observer\DealProductDiscountPrice->execute(Object(Magento\Framework\Event\Observer)) 1 /home/fotoloom/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Smartwave\Dailydeals\Observer\DealProductDiscountPrice), Object(Magento\Framework\Event\Observer)) 2 /home/fotoloom/public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) 3 /home/fotoloom/public_html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('checkout_cart_p...', Array) 4 /home/fotoloom/public_html/v in /home/fotoloom/public_html/app/code/Smartwave/Dailydeals/Observer/DealProductDiscountPrice.php on line 27**

It appears to me this could cause the error. However Smartwave says it also happens if the template is disabled.

I am looking for a solution and can't find it.
There were some problem solvers but this required editing source code and I think this is less desirable so I would do this if it is the only way and last resort.

Could you tell me where to look to solve this issue? Clients are walking away and already a week trying to find a solution. Even the hoster says nothing on their side is causing this and Redis is configurated well.

I am desperate right now.

Thanks in advance and warm regards,

Hans

Recent information:
     - Add to cart button hangs in adding
     - Magento 2.2.3
     - Check fotolooman.nl
     - Add to cart button hangs in adding and nothing is added to cart

Environment
    - PHP 7.0.29
    - Magento 2.2.3
    - Smartwave Porto theme 3.0.4
    - Amasty Custom stock status extension
    - IWD one page checkout suite latest
    - TIG PostNL extension latest

Steps to reproduce
The issue is easy to see. Go to fotolooman.nl and add something to the cart.
The button says and keeps saying adding and nothing is put in the cart and nothing further happens.

Expected result
The desired product should be put in the basket and client could go to checkout page.

Actual result
The button says and keeps saying adding and nothing is put in the cart and nothing further happens.

**Comment by magento-engcom-team** [comment]
Hi @hanzels. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@hanzels do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

In your case `Smartwave_Dailydeals` module is causing the trouble.

**Comment by hanzels** [comment]
Hi Orlangur,

Thanks for your reply.
Smartwave support says it also happens when the template is disabled.

I contacted them again and still waiting for an answer.

Any tips in narrowing down the issue?

Your advise is highly apreciated.

Thanks and warm regards,

Hans

**Comment by orlangur** [comment]
@hanzels try disabling their module and check how it works. There could be another fatal but with different stack trace, not in this module, after that.

**Comment by hanzels** [comment]
Hi Orlangur,

That is what is frustrating. We don't use it and it is disabled.
Somehow it still throws errors.

If you need anything to take a deeper look, let me know.

**Comment by orlangur** [comment]
@hanzels disabled module does not affect application normally after you flush the caches. Try removing it physically then.

**Comment by hanzels** [comment]
@orlangur I considered it but am realy scared that I completely ruin the theme beyond fixable.
And the other thing is, that I don't know how to remove it. Never did this...

**Comment by hanzels** [comment]
@orlangur Removed de daily deals extension and add to cart functions.

Thanks for your moral support.
