### ISSUE TITLE
magento setup is failing due to nonexistent Magento\CacheInvalidate\Model\Observer

### ISSUE THREAD

**Issue by keithbentrup** [magento/magento2#1658]
[Progress: 146 / 409]
Module 'Magento_Indexer':
Running recurring..

  [ReflectionException]
  Class Magento\CacheInvalidate\Model\Observer does not exist

**Comment by xcomSteveJohnson** [comment]
CLI installer or Setup Wizard? Have you tried both?

**Comment by keithbentrup** [comment]
just tried CLI

**Comment by xcomSteveJohnson** [comment]
@mazhalai Seen this before?

**Comment by mazhalai** [comment]
@keithbentrup Thank you for reporting, can you please give us more details, what version and if you are using sample-data. Also, did you have a previous installation? Please clear your `var` directory if you did. If you are using sample-data, can you please ensure you use the master branch. 

@xcomSteveJohnson Nope have'nt seen this before, but there were some changes related to Observers recently

**Comment by keithbentrup** [comment]
not using the sample data; var is empty
pretty clear why this is failing .. the referenced file doesn't exist.

seems like it's the sort of issue that should be caught by automated testing

**Comment by piotrekkaminski** [comment]
@keithbentrup do you still have this issue?

**Comment by mbrinton01** [comment]
Hi @keithbentrup please let us know if you are still seeing this issue so we can investigate or close out the issue. Thanks!
