### ISSUE TITLE
Issue in response for extension attributes to check stock availability in rest/V1/carts/mine/items

### ISSUE THREAD

**Issue by ilyasmuyiwa** [magento/magento2#16593]
### Preconditions

PHP 7.1
Version MySQL 5.6
MAgento EE v2.1.6

### Steps to reproduce
1. Add new extension attribute 

> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
> 
>     <extension_attributes for="Magento\Quote\Api\Data\CartItemInterface">
>         <attribute code="is_in_stock" type="integer" />
>     </extension_attributes>
> </config>
2) Create Plugin
```
<config` xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Quote\Model\Quote\Item\Repository">
        <plugin name="stock" type="Vendor\ModuleName\Plugin\StockMessage" disabled="false" sortOrder="70"/>
    </type>
</config>
```

3. Use the Plugin

```

public function aroundGetList(ItemRepository $subject, \Closure $proceed, $cartId)
    {
        $cartItems = $proceed($cartId);
        /** @var  \Magento\Quote\Model\Quote $quote */
        $quote = $this->quoteRepository->getActive($cartId);
        /** @var  \Magento\Quote\Model\Quote\Item  $item */

        /** @var \Magento\Quote\Api\Data\CartItemExtensionInterface $extensionAttributes */
      
        foreach ($quote->getAllVisibleItems() as $item) {
            $extensionAttributes = $item->getExtensionAttributes();
            if ($extensionAttributes === null) {
                $extensionAttributes = $this->cartItemExtensionFactory->create();
            }
            $sku = $item->getSku();
            $stock = $this->stockRegistry->getStockItemBySku($sku)->getIsInStock();
            if ($stock) {
                $message = 1;
            } else {
                $message = 0;
            }
            $extensionAttributes->setIsInStock($message);
            $Item->setExtensionAttributes($extensionAttributes);
    
        }

        return $cartItems;
  
}
```

### Expected result

1. I expected to get in rest/V1/carts/mine/items list of items like this,
    {
        "item_id": 1111111,
        "sku": "22222222",
        "qty": 2,
        "name": "AAAAAAAA",
        "price": 1111,
        "product_type": "configurable",
        "quote_id": "111",
        "product_option": {
            "extension_attributes": {
                "configurable_item_options": [
                    {
                        "option_id": "90",
                        "option_value": 13
                    },
                    {
                        "option_id": "20",
                        "option_value": 93
                    }
                ]
            }
        },
     "extension_attributes": {
            "is_in_stock": 1
        }
    },
    
### Actual result

1. The rest/V1/carts/mine/items  returns 
{
        "item_id": 1111111,
        "sku": "22222222",
        "qty": 2,
        "name": "AAAAAAAA",
        "price": 1111,
        "product_type": "configurable",
        "quote_id": "111",
     "extension_attributes": {
            "is_in_stock": 1
        }
    }

It first show as expected when magento compilation starts, but when it finishes, it removes this field below. This is affecting add to cart for configurable products.
"product_option": {
            "extension_attributes": {
                "configurable_item_options": [
                    {
                        "option_id": "90",
                        "option_value": 42
                    },
                    {
                        "option_id": "270",
                        "option_value": 1180
                    }
                ]
            }
        }
    }

**Comment by magento-engcom-team** [comment]
Hi @ilyasmuyiwa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ilyasmuyiwa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@ilyasmuyiwa, thank you for your report. You may try to rewrite your plugin to something like:
 ```
public function aroundGetList(CartItemRepositoryInterface $subject, \Closure $proceed, $cartId)
    {
        $cartItems = $proceed($cartId);
        foreach ($cartItems as $item) {
            $extensionAttributes = $item->getExtensionAttributes();
            if ($extensionAttributes === null) {
                $extensionAttributes = $this->cartItemExtensionFactory->create();
            }
            $sku = $item->getSku();
            $stock = $this->stockRegistry->getStockItemBySku($sku)->getIsInStock();
            if ($stock) {
                $message = 1;
            } else {
                $message = 0;
            }
            $extensionAttributes->setIsInStock($message);
            $item->setExtensionAttributes($extensionAttributes);
        }

        return $cartItems;
    }
```
![peek 2018-07-06 18-17](https://user-images.githubusercontent.com/40755810/42386764-192b403a-8149-11e8-9ed1-cbdb36d937aa.gif)

**Comment by ilyasmuyiwa** [comment]
Thanks a lot. I really appreciate. But even using your code, it still same result.

<?xml version="1.0"?>

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Quote\Api\CartItemRepositoryInterface">
        <plugin name="stock_message" type="Venfor\ModuleName\Plugin\StockMessage" disabled="false" sortOrder="1"/>
    </type>
</config>
```

Then StockMessage 

```
class StockMessage
{
    protected $quoteRepository;
    protected $cartItemExtensionFactory;
    protected $stockRegistry;


    public function __construct(
        \Magento\Quote\Api\CartRepositoryInterface $quoteRepository,
        \Magento\Quote\Api\Data\CartItemExtensionFactory $cartItemExtensionFactory,
        \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry
    ) {
        $this->quoteRepository = $quoteRepository;
        $this->stockRegistry = $stockRegistry;
        $this->cartItemExtensionFactory = $cartItemExtensionFactory;
    }

    public function aroundGetList(\Magento\Quote\Api\CartItemRepositoryInterface $subject, \Closure $proceed, $cartId)
    {
        $cartItems = $proceed($cartId);
        foreach ($cartItems as $item) {
            $extensionAttributes = $item->getExtensionAttributes();
            if ($extensionAttributes === null) {
                $extensionAttributes = $this->cartItemExtensionFactory->create();
            }
            $sku = $item->getSku();
            $stock = $this->stockRegistry->getStockItemBySku($sku)->getIsInStock();
            if ($stock) {
                $message = 1;
            } else {
                $message = 0;
            }
            $extensionAttributes->setIsInStock($message);
            $item->setExtensionAttributes($extensionAttributes);
        }

        return $cartItems;
    }

```
This is still same response. After clearing cache and recompiling...
<img width="854" alt="screen shot 2018-07-06 at 9 27 30 pm" src="https://user-images.githubusercontent.com/7964412/42392325-7cafe4a2-8163-11e8-921a-753ba3e63673.png">
