### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by gfxguru** [magento/magento2#166]
Magento needs a way of representing a product view with a configurable product, In other words a product image that changes based on it's simple product attributes. I know lots of people that have been requesting this capability. If we build a configurable product and assign multiple simple product to the configurable, there should be a way to change the product image on the customer end, based on  the customers choices.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-32407

**Comment by dustinnordquist** [comment]
@vpelipenko Are MAGETWO-32407 and MAGETWO-23739 being handled together? 

MAGETWO-23739 came from the discussion of Simple Configurable Products, which covers much of the functionality discussed above. See: https://github.com/magento/magento2/issues/335

Also, roughly half of my installs use SCP extension. So, I'm happy to help in anyway I can. Let me know if/how/when I can get involved. Thanks.

**Comment by vpelipenko** [comment]
@dustinnordquist, it will be decided by Product owner. But unfortunately, this work is still not in progress now.

**Comment by tanya-soroka** [comment]
@gfxguru  would you mind to clarify if the existing functionality in Magento 2 version covers your request. Right now when customer select the final option of the configurable product (simple product) the simple product images is going to be display on the main image section.

**Comment by vpelipenko** [comment]
@gfxguru, we are still waiting for update from you. Did you have a chance to look at existing solution provided by @tanya-soroka?
