### ISSUE TITLE
Consolidate/improve nested XML children elements

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1663]
Here is a screenshot of a module that is in development:
![screen shot 2015-08-12 at 9 56 47 pm](https://cloud.githubusercontent.com/assets/437029/9241121/1bf499be-413d-11e5-8685-b8c647e80aee.png)

The deep nesting is a bit extreme and I don't think it is needed, specifically in regards to the `name="children"` elements. Is there any way to consolidate these by attribute rather than element, so setting something like `is-child="true"` accomplishes the same thing?

I haven't explored the Magento 2 XML layers significantly, however I'm assuming this appears in a few different other locations as well. Anything to assist us devs debugging this very deep nesting would be helpful.

**Comment by antonkril** [comment]
Solution here is to have separate UI component for checkout. This way we will be able to configure checkout structure in separate xml files with dedicated xml syntax that does not have <children> node.

**Comment by piotrekkaminski** [comment]
@tkacheva are you tracking this?

**Comment by tkacheva** [comment]
@eug123 please look into it MAGETWO-54481

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-51525

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Consolidate-improve-nested-XML-children-elements/idi-p/46956).
