### ISSUE TITLE
Error trying create a button into system->config

### ISSUE THREAD

**Issue by Iuri-Bertto** [magento/magento2#16662]
# Declaring my button into system.xml
`<field id="moip_reset_button" type="button" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Redefinir Configurações</label>
                    <frontend_model>IcozWeb\Moip\Block\Adminhtml\Button\Reset</frontend_model>
                </field>`

#My Block
`<?php

namespace IcozWeb\Moip\Block\Adminhtml\Button;

class Reset extends \Magento\Config\Block\System\Config\Form\Field {

    /**
     * @var string
     */
    public $buttonLabel = 'Redefinir Configurações';

    /**
     * @var \Magento\Framework\App\Request\Http
     */
    protected $request;

    public function __construct(\Magento\Framework\App\Request\Http $request) {
        $this->request = $request;
    }

    /**
     * @param string $buttonLabel
     *
     * @return $this
     */
    public function setButtonLabel($buttonLabel) {
        $this->buttonLabel = $buttonLabel;
        return $this;
    }

    /**
     * @return $this
     */
    public function _prepareLayout() {
        parent::_prepareLayout();
        if (!$this->getTemplate()) {
            $this->setTemplate('icozweb/moip/system/config/form/field/reset.phtml');
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getLink() {
        $scopeType = \Magento\Framework\App\Config\ScopeConfigInterface::SCOPE_TYPE_DEFAULT;
        $scopeCode = null;
        if ($websiteId = (int) $this->request->getParam('website', 0)) {
            $scopeType = \Magento\Store\Model\ScopeInterface::SCOPE_WEBSITE;
            $scopeCode = $websiteId;
        }

        if ($storeId = (int) $this->request->getParam('store', 0)) {
            $scopeType = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
            $scopeCode = $storeId;
        }

        return $this->getUrl('adminhtml/moip_settings/reset', array('scope_type' => $scopeType, 'scope_code' => $scopeCode));
    }

    /**
     * Unset some non-related element parameters.
     *
     * @param \Magento\Framework\Data\Form\Element\AbstractElement $element
     *
     * @return string
     */
    //public function render(\Magento\Framework\Data\Form\Element\AbstractElement $element) {
    //    $element->unsScope()->unsCanUseWebsiteValue()->unsCanUseDefaultValue();
    //    return parent::render($element);
    //}

    /**
     * Get the button and scripts contents.
     *
     * @param \Magento\Framework\Data\Form\Element\AbstractElement $element
     *
     * @return string
     */
    public function _getElementHtml(\Magento\Framework\Data\Form\Element\AbstractElement $element) {
        $originalData = $element->getOriginalData();
        $buttonLabel  = !empty($originalData['button_label']) ? $originalData['button_label'] : $this->buttonLabel;
        $url          = $this->getLink();
        $this->addData([
            'button_label' => $buttonLabel,
            'html_id'      => $element->getHtmlId(),
            'class'        => 'delete',
            'ajax_url'     => $url,
        ]);

        return $this->_toHtml();
    }

}
`
#Error
`
Fatal error: Uncaught Error: Call to a member function isSingleStoreMode() on null in C:\xampp\htdocs\magento\vendor\magento\module-config\Block\System\Config\Form\Field.php:157 Stack trace: #0 C:\xampp\htdocs\magento\vendor\magento\module-config\Block\System\Config\Form\Field.php(49): Magento\Config\Block\System\Config\Form\Field->_renderScopeLabel(Object(Magento\Framework\Data\Form\Element\Button)) #1 C:\xampp\htdocs\magento\vendor\magento\framework\Data\Form\Element\AbstractElement.php(454): Magento\Config\Block\System\Config\Form\Field->render(Object(Magento\Framework\Data\Form\Element\Button)) #2 C:\xampp\htdocs\magento\vendor\magento\framework\Data\Form\Element\AbstractElement.php(468): Magento\Framework\Data\Form\Element\AbstractElement->getHtml() #3 C:\xampp\htdocs\magento\vendor\magento\module-config\Block\System\Config\Form\Fieldset.php(86): Magento\Framework\Data\Form\Element\AbstractElement->toHtml() #4 C:\xampp\htdocs\magento\vendor\magento\module-config\Block\System\Config\Form\Fieldset.php(66): Magento\Conf in C:\xampp\htdocs\magento\vendor\magento\module-config\Block\System\Config\Form\Field.php on line 157`

**Comment by magento-engcom-team** [comment]
Hi @Iuri-Bertto. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Iuri-Bertto do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @Iuri-Bertto, thank you for your report. When you extending some class, block in your case, you should respect parent class constructor method.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
