### ISSUE TITLE
Incorrect Order date at Customer Area > My Orders

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#1667]
I've placed 2 orders: 11 aug and 12 aug.
Today is 13 aug. And I see that all orders displayed with TODAY'S date.
You can see it at store/index.php/sales/order/history/ and at index.php/sales/order/view/order_id/6/ for example.
![default](https://cloud.githubusercontent.com/assets/3024248/9247835/2a9f61ce-41bf-11e5-8a10-ee60f16c131c.PNG)
![2](https://cloud.githubusercontent.com/assets/3024248/9247836/2ab7c03e-41bf-11e5-8394-9be71c0d11ce.PNG)
![3](https://cloud.githubusercontent.com/assets/3024248/9247837/2acb7fa2-41bf-11e5-8be4-34570729b4f7.PNG)

**Comment by vpelipenko** [comment]
Internal ticket: https://jira.corp.x.com/browse/MAGETWO-41473.

**Comment by sivaschenko** [comment]
@stasleo the fix for this issue is delivered to `develop`

**Comment by okorshenko** [comment]
@stasleo , Please, let us know if you still have an issue
