### ISSUE TITLE
upgrade problem

### ISSUE THREAD

**Issue by Perfect-Web** [magento/magento2#1668]
This situation is absurd and im stuck with it ... im on development branch

Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Theme schema: current version - 2.0.1, required version - 2.0.0
Magento_Theme data: current version - 2.0.1, required version - 2.0.0
Magento_Backend schema: current version - 2.0.0.0, required version - 2.0.0
Magento_Backend data: current version - 2.0.0.0, required version - 2.0.0
Magento_Customer schema: current version - 2.0.0.2, required version - 2.0.0
Magento_Customer data: current version - 2.0.0.2, required version - 2.0.0
Magento_Search schema: current version - 2.0.0.1, required version - 2.0.0
Magento_Search data: current version - 2.0.0.1, required version - 2.0.0
Magento_Catalog schema: current version - 2.0.0.2, required version - 2.0.0
Magento_Catalog data: current version - 2.0.0.2, required version - 2.0.0
Magento_SalesSequence schema: current version - 2.0.1, required version - 2.0.0
Magento_SalesSequence data: current version - 2.0.1, required version - 2.0.0
Magento_Sales schema: current version - 2.0.4, required version - 2.0.0
Magento_Sales data: current version - 2.0.4, required version - 2.0.0
Magento_ImportExport schema: current version - 2.0.1, required version - 2.0.0
Magento_ImportExport data: current version - 2.0.1, required version - 2.0.0
Magento_User schema: current version - 2.0.1, required version - 2.0.0
Magento_User data: current version - 2.0.1, required version - 2.0.0
Magento_ConfigurableProduct schema: current version - 2.0.1, required version - 2.0.0
Magento_ConfigurableProduct data: current version - 2.0.1, required version - 2.0.0
Magento_Multishipping schema: current version - 2.0.0.0, required version - 2.0.0
Magento_Multishipping data: current version - 2.0.0.0, required version - 2.0.0
Magento_CatalogSearch schema: current version - 2.0.1, required version - 2.0.0
Magento_CatalogSearch data: current version - 2.0.1, required version - 2.0.0
Magento_Weee schema: current version - 2.0.0.1, required version - 2.0.0
Magento_Weee data: current version - 2.0.0.1, required version - 2.0.0

**Comment by vpelipenko** [comment]
@Perfect-Web, sorry for that, but you need to do new clear installation. Looks like that your version is old. In 1.0.0-beta release all data/schema upgrades were removed and all changes from them applied in data/schema install scripts. It means that it is not possible to do system upgrade to 1.0.0-beta from all previous versions.

**Comment by Perfect-Web** [comment]
and how do i backup the data ?

**Comment by xcomSteveJohnson** [comment]
Try this: http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-backup.html

Depending on your Magento build, the command might not be available.

**Comment by ghost** [comment]
I think you come across this when you have a newer version of the components installed, example latest from development branch, and then you checkout a released version. I'm experiencing this now. The solutions isn't to upgrade but to uninstall and re-install, which has other implications. The database has to be regenerated.
