### ISSUE TITLE
Security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by shanethehat** [magento/magento2#1669]
The version of Monolog used has a security vulnerability: https://github.com/Seldaek/monolog/pull/448. The solution seems to be to upgrade to `~1.16.0`.

The version of zend-http used has a security vulnerability: http://framework.zend.com/security/advisory/ZF2015-04. The solution to this is to upgrade to `~2.4.1`.

**Comment by piotrekkaminski** [comment]
@shanethehat we have updated the packages and introduced Symfony dependency checker into our CI process to make sure we stay up to date on dependencies in the future.
