### ISSUE TITLE
setup version optional but required...

### ISSUE THREAD

**Issue by andrew-smart** [magento/magento2#1670]
Hi,

Is there a reason why in the xsd declaration (https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/etc/module.xsd#L46) setup_version is marked as optional but required by this check (https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/Declaration/Converter/Dom.php#L32).

Is this now the equivalent to "version" in Magento 1 and that is why it is required?

Also, despite a module doing very little and not containing any setup scripts you are forced to run bin/magento setup:upgrade i presume as a result of the setup_version. If that is just the way it needs to work then fine we can incorporate it in to our flow.

Thanks,
Andy

**Comment by mazhalai** [comment]
@andrew-smart Thank you for reporting, we have created MAGETWO-41517 to investigate

**Comment by piotrekkaminski** [comment]
This is fixed now and should be already published.

**Comment by mazhalai** [comment]
MAGETWO-41517 was closed in favor of MAGETWO-40320
