### ISSUE TITLE
When attribute attribute group name changed it not updates attribute group code 

### ISSUE THREAD

**Issue by sashas777** [magento/magento2#16728]
When attribute attribute group name changed it not updates attribute group code. This code used by setup scripts to assign attribute to attribute group. This can be viewed at the eav_attribute_group table.

The issue comes when you have installation script which assign attribute to a attribute group and run bin/magento setup:upgrade.  Then you will see a error.

### Preconditions
1. Magento 2.2.4
2. nginx/1.15.1
3.  php-fpm 7.1
4.  Created custom Attribute group

### Steps to reproduce
 
1.  Login to the admin then open Stores->Attribute Set and Select attribute set
2.  Select the attribute group which you going to rename and check values for this attribute group at the eav_attribute_group table.
3. rename the attribute group from the admin panel and save attribute set.
4. check the eav_attribute_group  table and you will see that field attribute_group_code not changed where attribute_group_name  has been changed.
6. Now make custom module with upgrade script which adds product attribute and assign it to a section:
```
/*Create Attribute Group and Add Attributes*/
        $entityTypeId = $eavSetup->getEntityTypeId(\Magento\Catalog\Model\Product::ENTITY);
        $attributeSetIds = [**ATTRIBUTE_SET_ID_HERE**];
        $groupName="** NEW GROUP NAME HERE**";
        $attributeCodes=['**ATTRIBUTE CODE HERE**'];
        foreach ($attributeSetIds as $attributeSetId) {
            $eavSetup->addAttributeGroup($entityTypeId, $attributeSetId, $groupName, 19);
            $attributeGroupId = $eavSetup->getAttributeGroupId($entityTypeId, $attributeSetId, $groupName);
            foreach ($attributeCodes as $attributeCode) {
                $eavSetup->addAttributeToGroup(
                    $entityTypeId,
                    $attributeSetId,
                    $attributeGroupId,
                    $attributeCode,
                    null
                );
            }
        }
```
### Expected result
1.  After renaming attribute_group_name  then attribute_group_code  should be updated 

### Actual result
1.  After renaming attribute_group_name  then attribute_group_code  not updates

**Comment by magento-engcom-team** [comment]
Hi @sashas777. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sashas777 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @sashas777, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
> attribute_group_code not updates

This is correct behavior so that static group code may be used in setup scripts or tab templates.

**Comment by sashas777** [comment]
@orlangur 

This causes the issue for upgrade scripts when you assign an attribute to attribute group.  Basically you cannot use attribute groups in the setup scripts.

**Comment by orlangur** [comment]
@sashas777 what kind of issue?

**Comment by sashas777** [comment]
@orlangur 
When you follow steps to reproduce issue Magento will throw an error because it matches adding to attribute group in setup script by attribute_group_code which has old value and there is no way to find it out once group name changed. 

I tried to explain all in the description - please let me know what specific questions you have

**Comment by orlangur** [comment]
@sashas777,

> field attribute_group_code not changed where attribute_group_name has been changed
> there is no way to find it out once group name changed

What is the problem in finding attribute group code from database?

**Comment by sashas777** [comment]
@orlangur 

You may not always have access to database or have the same exact version  of it.  Also, there may be case when it has been modified at the admin while another component were in development.

Also if you look at the code it seems suppose to work by attribute_group_name but it takes into account attribute_group_code. 

```
$eavSetup->addAttributeGroup($entityTypeId, $attributeSetId, $groupName, 19);
$attributeGroupId = $eavSetup->getAttributeGroupId($entityTypeId, $attributeSetId, $groupName);
```

Basically there is no way to know what parameter should be passed except of looking at production database to get current value of attribute_group_code because it not visible anywhere. This doesn't looks to be a good way in cases there is no access to a production db.

**Comment by ghost** [comment]
@sashas777, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sashas777** [comment]
@orlangur @sidolov 
Is there a way to keep it open?
