### ISSUE TITLE
The autoload section in the Magento2 project composer.json

### ISSUE THREAD

**Issue by moleman** [magento/magento2#1673]
Hi,

Is there any special reason why the autoloading mapping of both **Magento\Framework\** and **Magento\Setup\** are in the Magento2 project composer.json file? Wouldn't it be better to have them in the packages where they belong, **Magento\Framework\** in magento/framework and **Magento\Setup\** in magento/magento2-base? 

The reason why is that it would make the Magento2 project composer.json cleaner and you wouldn't have to specify it in your own project composer.json when you require the "magento/product-community-edition" package.

**Comment by buskamuza** [comment]
Hi @moleman ,

magento/framework and magento/magento2-base, actually, have their autoload.
The reason why this Git repository (magento/magento2) is that it includes whole Magento and so does not download components (such as Framework) via Composer. That's why composer.json of the Git repository includes duplicated information to let Composer read and process it.

**Comment by mazhalai** [comment]
@moleman this is due to dependency on magento-composer-installer which copies the components to the folder instead of loading directly from vendor.  Some of this is work in progress.  See related issue in PR #1490

**Comment by moleman** [comment]
@buskamuza @mazhalai Aha, the Framework package autoload has "Magento\\Framework\\": "" which is correct mapping in the package context but the project needs to map "Magento\\Framework\\" to  "lib/internal/Magento/Framework/" because thats the location where the package files will be placed in the project by the installer. Then I understand. Thanks.

But still, I think that the autoloading of the setup can be moved to the magento/magento2-base composer.json because the folder structure is the same in the package as in the project.

**Comment by piotrekkaminski** [comment]
@buskamuza are there any changes here?

**Comment by buskamuza** [comment]
@moleman , yes, it would be better to move the autoload to corresponding packages. I created an internal ticket for this MAGETWO-70242

**Comment by magento-engcom-team** [comment]
@moleman, thank you for your report.
We've created internal ticket(s) MAGETWO-70242 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @moleman this is not an issue but improvement to the modularity. Closing the issue. But we have MAGETWO-70242 in our backlog to improve this.
