### ISSUE TITLE
Not all required PHP extensions are checked (pdo_mysql)

### ISSUE THREAD

**Issue by Dell-** [magento/magento2#1674]
Hi!
![extensions-check](https://cloud.githubusercontent.com/assets/6927645/9261391/468fc7be-4216-11e5-9a4e-e4361f57b86a.png)
![extension-not-installed](https://cloud.githubusercontent.com/assets/6927645/9261399/4cfedc84-4216-11e5-9db3-94bc1ffe2b13.png)

**Comment by mazhalai** [comment]
Thank you for reporting @Dell- We have created MAGETWO-41553  to investigate and fix this internally.

**Comment by piotrekkaminski** [comment]
It is fixed and should be published soon.
