### ISSUE TITLE
Error category in Backend

### ISSUE THREAD

**Issue by jerachu** [magento/magento2#1676]
When I click on any category in backend, it return this string in white page:

{"data":[{"text":"Apple (1)","id":"4","store":1,"path":"1\/2\/4","cls":"folder active-category","allowDrop":true,"allowDrag":true,"expanded":true}],"parameters":{"text":"Default Category (0)","draggable":false,"allowDrop":true,"id":2,"expanded":0,"store_id":1,"category_id":4,"root_visible":1}}

So I cannot add sub or modify any category.

**Comment by zhaoxiong123** [comment]
i found the same problem!

**Comment by shausol** [comment]
Hey,
I had the same problem and i solved it by changing the code in Tree.php file.
Go To Magento\Catalog\Controller\Adminhtml\Category folder open Tree.php file now copy the code from line no 60 in execute function $resultRedirect = $this->resultRedirectFactory->create(); and paste it at the start of the function Now go to end of the execute function remove return from the line return $resultJson->setData([
            'data' => $block->getTree(),
            'parameters' => [
                'text' => $block->buildNodeName($root),
                'draggable' => false,
                'allowDrop' => (bool)$root->getIsVisible(),
                'id' => (int)$root->getId(),
                'expanded' => (int)$block->getIsWasExpanded(),
                'store_id' => (int)$block->getStore()->getId(),
                'category_id' => (int)$category->getId(),
                'root_visible' => (int)$root->getIsVisible(),
            ],
        ]);
and add a line below this code
return $resultRedirect->setPath('catalog/category/edit', ['_current' => true, 'id' => $categoryId]);.

Now the two line will become
$resultJson->setData([
            'data' => $block->getTree(),
            'parameters' => [
                'text' => $block->buildNodeName($root),
                'draggable' => false,
                'allowDrop' => (bool)$root->getIsVisible(),
                'id' => (int)$root->getId(),
                'expanded' => (int)$block->getIsWasExpanded(),
                'store_id' => (int)$block->getStore()->getId(),
                'category_id' => (int)$category->getId(),
                'root_visible' => (int)$root->getIsVisible(),
            ],
        ]);
        return $resultRedirect->setPath('catalog/category/edit', ['_current' => true, 'id' => $categoryId]); 

It works fine for me

**Comment by jerachu** [comment]
Thank you shausol! It worked.
You are genius :).

**Comment by shausol** [comment]
Thanks @jerachu

**Comment by alankent** [comment]
Feel free to turn into a pull request if you think there is a bug here!

**Comment by shausol** [comment]
@alankent  This is bug and not yet fixed in M2.

**Comment by alankent** [comment]
Thanks for the pull request, but something looks a bit funny: https://github.com/magento/magento2/pull/1758/files - shows thousands of files changed which I don't think is your intent. You can leave it to us, but your name goes down in history in the GitHub log if you create the pull request for us to accept.

**Comment by shausol** [comment]
Sorry i am new to github so created a funny pull request.  Now working on how to create a proper pull request. Thanks for advise. :)

**Comment by piotrekkaminski** [comment]
@shausol any luck with that?

**Comment by vzabaznov** [comment]
Hi @jerachu, thank you for reporting, our functionality has been changed, and bug cannot be reproduced, if you feel that issue is not fixed, please write here or open another issue

**Comment by meenagowri** [comment]
Hi I have the error when I click the categories.The error is "There has been an error processing your request"..What I have to do to clear the error
