### ISSUE TITLE
Cannot run php bin/magento setup:di:compile (have to delete contents of var/di) first

### ISSUE THREAD

**Issue by davefarthing** [magento/magento2#1679]
Running `php bin/magento setup:di:compile`

Results in 
`Autoload error: Argument 1 passed to Magento\Setup\Model\SampleData::__construct() must be an instance of Magento\Framework\App\Filesystem\DirectoryList, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /Volumes/ExStorage/sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined`

Works fine if i remove the contents of `var/di` first.

**Comment by mazhalai** [comment]
@davefarthing Thank you for reporting, we have created ticket MAGETWO-41445 to fix this issue.

**Comment by piotrekkaminski** [comment]
It is fixed and should be published now.
