### ISSUE TITLE
Changes was made in the magento/framework without increasing the package version

### ISSUE THREAD

**Issue by moleman** [magento/magento2#1680]
Hi,

I just noticed that the files in the **magento/framework** Composer package was recently changed but no new package version was released.

I noticed this when running a fresh *composer install* in a project that requires "magento/product-community-edition": "1.0.0-beta" with an existing composer.lock file and a clean Composer cache. Composer will download the zip package of magento/framework and compare the checksum in the composer.lock with the file which will of course fail because the zip package contains changes since the package was installed the first time and composer.lock was generated.

This is the error I get when running composer install:

…
  - Installing magento/framework (1.0.0-beta)
    Downloading: 100%

  [UnexpectedValueException]
  The checksum verification of the file failed (downloaded from https://packages.magento.com/_packages/magento_framework-1.0.0-beta.zip)

Correct me if I’m wrong, but *1.0.0-beta* is a real version and not a branch-alias (see https://getcomposer.org/doc/articles/aliases.md) or a development version? This means that I can’t run *composer update magento/framework* in the project in order get the new version of 1.0.0-beta because Composer doesn’t recognise that the package has changed. The content of a package version that is not a development version should not change.

I see that previous beta versions has a number as a suffix, 0.74.0-beta16, 0.74.0-beta15, 0.74.0-beta14 which is correct. Is there any reason why 1.0.0-beta is not also suffixed with numbers?

**Comment by alankent** [comment]
Hi. Thanks for the feedback. You are right we don't have all this completely working currently. packages.magento.com for example was set up as a stop gap measure until the new Connect is available. The new Connect will allow downloads via Composer instead. We are changing around processes internally incrementally to get closer to where we want to end up. We are looking at this one internally to try and minimize these sorts of breakages while we move forward towards the final goal.

The likely final place is for the main development branch to be just that - more unstable (a true "dev") - with releases (and patches) being created from branches. We are in this slightly funny mode still of making releases on mainline (no patching of those releases will be done, so no branching in Git is required).

So sorry for the instability right now. We are looking at it. But it is not in its final state yet.

**Comment by moleman** [comment]
Ok, I understand and thanks for your answer but currently the Composer way of installing Magento2 doesn't work at all.
I did a clean composer install without any Composer cache of magento/product-community-edition: 1.0.0-beta and the installation went fine but the setup crashes because of:

Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for Magento\Framework\DB\Logger\Null

When looking into it more it seems that only some 1.0.0-beta packages has been changed but not all. The 1.0.0-beta package of magento/magento2-base still has references to Magento\Framework\DB\Logger\Null which differs from the main repository.

Then I saw that there is a new(?) 1.0.0-rc package of magento/product-community-edition but when I try to install that it fails because it requires 1.0.0-rc of all the sub packages but there is no 1.0.0-rc package available of magento/framework, http://packages.magento.com/#!/framework

**Comment by buskamuza** [comment]
Hi @moleman ,

thanks for reporting the issue. Looks like we accidentally updated the packages. We're working now or restoring old versions.
Unfortunately, it will require cleaning composer cache again. But at least after that Magento installation should be working.

**Comment by buskamuza** [comment]
Update: the packages for `1.0.0-beta` version has been updated to be consistent with https://github.com/magento/magento2/releases/tag/1.0.0-beta

Installation now works fine.
Please, let us know whether it works for you. Don't forget to clean composer cache.

**Comment by moleman** [comment]
Great. Now it works again. Thanks
