### ISSUE TITLE
How to integrate third-party systems of commodity data

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1681]
hi,this is I encountered a problem difficult to break through ,Can you tell me a solution for it ,Thanks!

**Comment by choukalos** [comment]
Hello @LifeAsBook can you be more specific by what you're asking for?   I think you might be asking how to integrate a 3rd party system into Magento 2 ( i.e. product information management system [catalog data], or CRM like salesforce [customer data] ).

In which case you have a few paths in order of difficulty:
1.  Manually you can do an import/export as needed
2.  [ Enterprise; Manually once ] you can schedule an import/export to FTP directory
3.  You can create a Magento extension ( really just XML files ) defining allowed APIs ( say catalog ) to be used to push and poll changes called from the 3rd party system.  In addition you can setup an Oauth v1 style handshake.  Your 3rd party system would then have to call the Magento APIs to manage the data.
4.  You can create your own Magento extension; with your own code to integrate to the 3rd party system.  You might say create your own service and expose as a web api; or you could do a feed or any such other style of data integration you need.

**Comment by LifeAsBook** [comment]
@choukalos  the 3rd  systems also b2c and provided porduct ,order's REST API,i want to  integrate that  product information  into  Magento 2 and when the order to pay the successful  then called 3rd order‘s REST API to pay. can you  tell me an idea.thank you very much!
