### ISSUE TITLE
Can't overwrite a block in functional tests

### ISSUE THREAD

**Issue by kassner** [magento/magento2#1682]
Hi,

I'm trying to overwrite a block page in functional tests to extend functionality, but currently I'm just able to add blocks. If I do something like this in the [OrderIndex.xml](https://github.com/magento/magento2/blob/2dff306ab148a6b6a908332ecf2eb444879ef0bd/dev/tests/functional/tests/app/Magento/Sales/Test/Page/Adminhtml/OrderIndex.xml) from my module:

```xml
    <page name="OrderIndex" area="Adminhtml" mca="sales/order/index" module="Magento_Sales">
        <block name="salesOrderGrid" class="Abc\Module\Test\Block\Adminhtml\Order\Grid" locator=".admin__data-grid-outer-wrap" strategy="css selector"/>
    </page>
```

The resulting blocks property is:

```php
    protected $blocks = [
        'gridPageActions' => [
            'class' => 'Magento\Backend\Test\Block\GridPageActions',
            'locator' => '.page-main-actions',
            'strategy' => 'css selector',
        ],
        'salesOrderGrid' => [
            'class' => 'Magento\Sales\Test\Block\Adminhtml\Order\Grid',
            'locator' => '.admin__data-grid-outer-wrap',
            'strategy' => 'css selector',
        ],
        'messagesBlock' => [
            'class' => 'Magento\Backend\Test\Block\Messages',
            'locator' => '#messages',
            'strategy' => 'css selector',
        ],
    ];
```
But, if I change the block's name:

```xml
    <page name="OrderIndex" area="Adminhtml" mca="sales/order/index" module="Magento_Sales">
        <block name="customGrid" class="Abc\Module\Test\Block\Adminhtml\Order\Grid" locator=".admin__data-grid-outer-wrap" strategy="css selector"/>
    </page>
```

The resulting blocks property is:

```php
    protected $blocks = [
        'customGrid' => [
            'class' => 'Abc\Module\Test\Block\Adminhtml\Order\Grid',
            'locator' => '.admin__data-grid-outer-wrap',
            'strategy' => 'css selector',
        ],
        'gridPageActions' => [
            'class' => 'Magento\Backend\Test\Block\GridPageActions',
            'locator' => '.page-main-actions',
            'strategy' => 'css selector',
        ],
        'salesOrderGrid' => [
            'class' => 'Magento\Sales\Test\Block\Adminhtml\Order\Grid',
            'locator' => '.admin__data-grid-outer-wrap',
            'strategy' => 'css selector',
        ],
        'messagesBlock' => [
            'class' => 'Magento\Backend\Test\Block\Messages',
            'locator' => '#messages',
            'strategy' => 'css selector',
        ],
    ];
```

Maybe something wrong with the order the files are loaded?

Thanks!

**Comment by alankent** [comment]
Try adding a <remove name="customGrid"> element to remove the name first. I think you are adding a second block with the same name, but the old one is still there. (I still need to think about if this is a bug or a feature!)

**Comment by kassner** [comment]
@alankent <remove> is not a valid entity, this uses `pages.xsd` as validation.

I think this is just something wrong with the loading order. If I add an `rsort($paths)` [in this line](https://github.com/magento/mtf/blob/19aa3591e07504e2a0a4ff3bffb357397cc4bafc/Magento/Mtf/Config/FileResolver/Mask.php#L68), it works as expected.

I guess `Magento\Mtf\Util\ModuleResolver::getModulesPath` should sort the list to put Magento modules first. I'm not sure if this makes sense, but M1 has this kind of behavior (but was done in a different way, loading `app/code/core` first).

**Comment by fooman** [comment]
Just some further background on this. Magento2 itself allows you to state a sequence in your module.xml file which then affects the load order of all future configuration files - see Anton's  https://github.com/magento/magento2/issues/953#issuecomment-73667752

This allows one to overwrite any existing xml nodes with your own content. This behaviour is different for the MTF as it uses its own configuration loader https://github.com/magento/mtf/blob/19aa3591e07504e2a0a4ff3bffb357397cc4bafc/Magento/Mtf/Config/FileResolver/Mask.php#L45 which does not include the ability to sort by [sequence](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Module/ModuleList/Loader.php#L111) or take into consideration the order in the config.php.

It seems unfair that all namespaces sorted after Magento get this "feature" but the ones before miss out.

**Comment by lanken** [comment]
@fooman, you are right.
@kassner, thanks for rising a question. We know about this limitation and have internal ticket MTA-2410. Currently if your changes don't affect existing functionality and just add new one, you can add new block customGrid. It should be extended from default grid in Sales module, and in your tests in Abc module you should use customGrid.

**Comment by lanken** [comment]
@kassner, we added an ability to overwrite block nodes in page declaration based on Magento 2 module sequence loading. So if your module loads after Magento_Sales module you can overwrite **salesOrderGrid** block in your custom module.

``` xml
    <page name="OrderIndex" area="Adminhtml" mca="sales/order/index">
        <block name="salesOrderGrid" class="Magento\CustomModule\Test\Block\Adminhtml\Order\Grid" locator=".admin__data-grid-outer-wrap" strategy="css selector"/>
    </page>
```

If you still have any questions, feel free to reopen the issue.
