### ISSUE TITLE
No generic buttons for admin forms

### ISSUE THREAD

**Issue by danslo** [magento/magento2#1683]
There are things like ``Magento\Customer\Block\Adminhtml\Edit\BackButton`` which don't contain any customer specific functionality, preferably they should be moved to a more generic place (``Magento\Framework\View`` or ``Magento\Ui``?) so other modules can make use of them without having dependency on ``Magento_Customer``.

**Comment by danslo** [comment]
Other buttons, like ``Magento\Customer\Block\Adminhtml\Edit\DeleteButton`` should probably inject a label in constructor and also moved to generic location so that we can re-use them with virtual types.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/No-generic-buttons-for-admin-forms/idi-p/45429).
