### ISSUE TITLE
Mass Actions "Required field" fired when saving form

### ISSUE THREAD

**Issue by bvboas** [magento/magento2#1685]
I've a form with multiple tabs and in some tabs there are grids with mass actions.

When I try to save the form, I get a "This is a required field" warning fired from the mass actions select element  and I can't save the form. 

![ma](https://cloud.githubusercontent.com/assets/13635432/9296622/0d97f222-4489-11e5-98db-cf1bf804268f.png)

**Comment by bvboas** [comment]
Anyone knows how to fix this?

**Comment by vinhbt90vn** [comment]
Hi,
I have a same problem so I have to set the new template for the massaction block to fix it.

Use this code in the _prepareMassaction() function of your grid class file:
$this->getMassactionBlock()->setTemplate('Vendor_Module::widget/grid/massaction_extended.phtml');

Then copy the content of Magento_Backend::widget/grid/massaction_extended.phtml to your module and remove the "required-entry" class.

**Comment by Manashvi** [comment]
The same issue still continues in the ver. 2.0.4
I wonder if this bug is not resolved by the team.

**Comment by maksek** [comment]
@Manashvi, i have hard time to reproduce it, can you provide steps how you are getting it with env settings?

**Comment by veloraven** [comment]
@bvboas is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.
