### ISSUE TITLE
Incorrect behavior after changing config through command line

### ISSUE THREAD

**Issue by HardRock88** [magento/magento2#16866]
When I changing Add Secret Key to URLs through command line, changes take effet only after manual save in Stores -> Configuration -> ADVANCED -> Admin

### Preconditions

1. Magento 2.2.5 (vanilla) with sample products
2. Php 7.1.19
3. Apache 2.4.33
4. Operating system: Fedora 28

### Steps to reproduce
1.  Install magento2 with compsoer
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./magento2/`
`php bin/magento sampledata:deploy`
`php bin/magento setup:install --backend-frontname=admin --base-url="magento2.loc" --db-host=127.0.0.1 --db-name=magento_2 --db-password=qweqwe --admin-user=admin --admin-password=qweqwe --admin-email=admin@magento.loc --admin-firstname=admin --admin-lastname=admin --use-sample-data`
2.  Change config
        php bin/magento config:set admin/security/use_form_key false

### Expected result
1. No secret key in adminpanel urls

### Actual result
1. Add Secret Key to URLs = No
2. Urls still has secret key param
![err](https://user-images.githubusercontent.com/5637425/42775731-c365c920-893d-11e8-8970-50d540d6c816.PNG)

Also i had tryed clearing cache with:
	`php bin/magento cache:clean`
	`php bin/magento cache:flush`
	
and it does not help

**Comment by engcom-backlog-nickolas** [comment]
Hello @HardRock88, thank you for your report. "use_form_key" configuration receives numbers. So, if you try to enter "php bin/magento config:set admin/security/use_form_key 0" 
![peek 2018-07-17 09-47](https://user-images.githubusercontent.com/40755810/42800904-3a0feebc-89a6-11e8-8e27-dc5c37603425.gif)
everything will work just fine.
If you'd like to update this issue, please feel free to reopen it.
