### ISSUE TITLE
Wrong stylesheet path when installing master branch and sample data

### ISSUE THREAD

**Issue by nhc** [magento/magento2#1687]
Having had this issue https://github.com/magento/magento2/issues/1610 I followed the newly updated instructions in the devdocs which states to use the master branch not the develop branch

So I installed the master branch and all went well except for one thing - the head section of the generated html contains this which causes the body of the home page not to display properly 

<link  rel="stylesheet" type="text/css"  media="all" href="http://localhost/pub/media/styles.css" />    

<img width="841" alt="screenshot 2015-08-17 13 45 03" src="https://cloud.githubusercontent.com/assets/288772/9305090/396dc9d2-44e6-11e5-8acb-53c027df4abb.png">

All other references to stylesheets work as you can see here 

```html
<title>Home Page</title>
<link  rel="stylesheet" type="text/css"  media="all" href="http://178.62.22.124/pub/static/frontend/Magento/luma/en_GB/mage/calendar.css" />
<link  rel="stylesheet" type="text/css"  media="all" href="http://178.62.22.124/pub/static/frontend/Magento/luma/en_GB/css/styles-m.css" />
<link  rel="stylesheet" type="text/css"  media="screen and (min-width: 768px)" href="http://178.62.22.124/pub/static/frontend/Magento/luma/en_GB/css/styles-l.css" />
<link  rel="stylesheet" type="text/css"  media="print" href="http://178.62.22.124/pub/static/frontend/Magento/luma/en_GB/css/print.css" />
<link  rel="icon" type="image/x-icon" href="http://178.62.22.124/pub/static/frontend/Magento/luma/en_GB/Magento_Theme/favicon.ico" />
<link  rel="shortcut icon" type="image/x-icon" href="http://178.62.22.124/pub/static/frontend/Magento/luma/en_GB/Magento_Theme/favicon.ico" />
<script  type="text/javascript"  src="http://178.62.22.124/pub/static/frontend/Magento/luma/en_GB/requirejs/require.js"></script>
<script  type="text/javascript"  src="http://178.62.22.124/pub/static/_requirejs/frontend/Magento/luma/en_GB/requirejs-config.js"></script>
<link  rel="stylesheet" type="text/css"  media="all" href="http://localhost/pub/media/styles.css" />            </head>
```
I tried altering the base url of the site in the admin but this has no effect.

**Comment by piotrekkaminski** [comment]
I cannot reproduce it @nhc can you check on latest version?
