### ISSUE TITLE
Add Custom Product attributes to minicart template

### ISSUE THREAD

**Issue by Zaylril** [magento/magento2#1688]
So in the minicart template in web/template/minicart/item/default.html you have the following code:

```html
<a data-bind="attr: {href: product_url, title: product_name}, text: product_name"></a>
```

What I want to do is add a custom product attribute to this, as well as maybe some default existing ones such as weight for example.

I know how the template can be modified to display the data I'm just not sure how i can assign custom data to the KO js var I need.

Thanks

**Comment by mslabko** [comment]
Hello Zaylril,

Currently we store private data in local storage and renders them using ko templates.
Class responds for retrieving private data should be placed in namespace "Vendor/ModuleName/CustomerData"
Class must implement \Magento\Customer\Model\CustomerData\SectionSourceInterface interface.

The following class is used for retrieving privata data for mini-cart: \Magento\Checkout\CustomerData\Cart
\Magento\Checkout\CustomerData\ItemInterface is responsible for retrieving data for each item in the shopping cart

So, for your case you need to create plugin for *\Magento\Checkout\CustomerData\DefaultItem::getItemData* and extend data.
After that in template web/template/minicart/item/default.html new data will be accessible

**Comment by isydorenko** [comment]
It's not possible to get access to product or item data from a plugin, almost all methods are protected.
