### ISSUE TITLE
Widget (Frontend App) Documentation

### ISSUE THREAD

**Issue by eCommerceGorilla** [magento/magento2#1696]
In the previous Magento 2 development documentation the changes to markup was illustrated at the following: https://wiki.magento.com/display/MAGE2DOC/Changes+to+Configuration+of+Widget

However it appears that this information is no longer accurate. Is there any updated real documentation for Magento2 Frontend App's? If not is there a standalone sample of a widget that can be used to dissect the changes?

**Comment by tanberry** [comment]
Hi @eCommerceGorilla, please take a look at http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/jquery-widgets-about.html and see if the docs there answer your questions. If not, let us know, and always feel free to make pull requests against our docs at https://github.com/magento/devdocs. We welcome input and contributions from the community to our growing doc set. Thanks!

**Comment by eCommerceGorilla** [comment]
@tanberry The link you provided is absolutely nothing to do with front-end apps as I can see and only has to do with tying into query functionality. 

I am looking for documentation on the implementation of front-end apps (formerly called widgets) inside Magento 2. Or if no documentation exists is there is a sample of a basic widget that can be viewed without trying to pull all the information directly out of the core files.

**Comment by antonkril** [comment]
No major changes were made to schema. Why do you think the doc is no longer accurate?
