### ISSUE TITLE
Security Error when checking out using Paypal

### ISSUE THREAD

**Issue by Ben-Islin** [magento/magento2#1697]
PAYPAL GATEWAY HAS REJECTED REQUEST. SECURITY HEADER IS NOT VALID (#10002: SECURITY ERROR).

When we check out using Paypal Website Payments Pro Hosted Solution (CC + PP) then one of two erros happen

1) PAYPAL GATEWAY HAS REJECTED REQUEST. SECURITY HEADER IS NOT VALID (#10002: SECURITY ERROR). appears at the top of the page

2) The message "Please do not refresh the page until payment is complete" appears but no payment portal ever appears

**Comment by asemenenko** [comment]
Hi @Ben-Islin 

Have you checked Apache settings to use TSL?

**Comment by Ben-Islin** [comment]
thanks!

That is probably it

*Benjamin Islin*
*Business Analyst*

*Inviqa*
enterprise open source

skype: bislin  <bislin@inviqa.com>
e-mail: bislin@inviqa.com

phone: +44 7879333004
twitter:@Inviqa <http://twitter.com/#!/Inviqa>
*inviqa.com <http://www.inviqa.com/>*

Disclaimer
This email and any attachments may be confidential and are intended solely
for the use of the addressee. Any views or opinions expressed are those of
the author and may not represent those of Inviqa. If you are not the
intended recipient of this email, you must neither take any action based
upon its contents, nor copy or show it to anyone. Please contact the sender
if you believe you have received this email in error.

**Comment by vpelipenko** [comment]
@Ben-Islin, could you confirm that the problem was in Apache settings? If yes, we can close this issue, right?
