### ISSUE TITLE
ProductAlert for out of stock not working

### ISSUE THREAD

**Issue by Ingvar1917** [magento/magento2#1699]
What I do:
1. subscribe to a product is not in stock
2.  change inventory to "in stock", and start reindex (bin/magento indexer:reindex)
3. run cron, make sure the load observer app/code/Magento/ProductAlert/Model/Observer.php::process()
actual result - the message is not sent

I think the problem with the following code

app/code/Magento/CatalogInventory/Model/StockRegistry.php

    public function getStockStatus($productId, $websiteId = null)
    {
      //if (!$websiteId) {
        $websiteId = $this->stockConfiguration->getDefaultWebsiteId();
      //}
        return $this->stockRegistryProvider->getStockStatus($productId, $websiteId);
    }

debug case:

    public function getStockStatus($productId, $websiteId = null) // $websiteId == 1
    {
      //if (!$websiteId) {
        $websiteId = $this->stockConfiguration->getDefaultWebsiteId(); $websiteId == 0
      //}
        return $this->stockRegistryProvider->getStockStatus($productId, $websiteId);
    }

if remove commented code, the message is sent.

Thank you.

**Comment by Ingvar1917** [comment]
Sorry.
As you understand , I mean, if you remove the comments, the message is sent.

**Comment by eleonova** [comment]
Hi, we have created an internal ticket to fix the issue: MAGETWO-42361

**Comment by piotrekkaminski** [comment]
This is fixed and should be published soon.
