### ISSUE TITLE
Customer Group Code Char Limit

### ISSUE THREAD

**Issue by steig** [magento/magento2#1701]
Customer group codes are limited to 32 chars and if there is a valid reason to keep them at 32 that makes sense, but I really can't find a reason right now as to why.   If they can be increased, would 64 be enough?

**Comment by vpelipenko** [comment]
@steigerwald, I think, we can increase it. But do you really need more than 32 chars for group codes?

**Comment by steigerwald** [comment]
As a merchant who uses Magento in the B2B setting, a customer group for us maps to a company name.   You can imagine the number of company names greater than 32 chars.

Also see.. 

http://magento.stackexchange.com/questions/13721/customer-group-code-limited-to-32-chars-why

**Comment by ilol** [comment]
@steigerwald, we will do it. MAGETWO-41983. Thank you

**Comment by piotrekkaminski** [comment]
@mbrinton01  tagging you regarding B2B need

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Customer-Group-Code-Char-Limit/idi-p/46950).
