### ISSUE TITLE
Minicart inconsistant behavior between http and https

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1704]
1. Go to listing page and click on add to cart. > Will redirect to the product details page
2. Select appropriate product options and Add to Cart. > Mini cart is updated and swowing correct count and details
3. Go to a https page. In this case login page. > Updated mini cart is not there.
4. Go to cart page which is also a https page shows cart details but no mini cart.

Please check below screen cast. 
https://vimeo.com/136696374
https://vimeo.com/136696375

**Comment by okorshenko** [comment]
@bgkavinga thank you for reporting. Internal ticket MAGETWO-42157.

**Comment by piotrekkaminski** [comment]
It should be fixed now and published soon.
