### ISSUE TITLE
Remove item from Minicart does not work

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#1705]
1. Add item to the cart
2. Remove item from the minicart > Doesn't happen anything. Just expands the description.
3. Go to cart page and remove item. > Will remove the item from the cart.
4. Minicart still show the item.
5. Remove item from minicart again > Will remove the item from the Minicart
Please check below screen cast
https://vimeo.com/136697006

**Comment by okorshenko** [comment]
@bgkavinga thank you for reporting. Internal ticket MAGETWO-42188

**Comment by piotrekkaminski** [comment]
This is fixed and should be published soon.
