### ISSUE TITLE
why china not in Merchant Country 

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1706]
![20150819180733](https://cloud.githubusercontent.com/assets/10986726/9353733/423c4c10-469d-11e5-92cb-21e392ae5a37.png)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-40299

**Comment by dfediuk** [comment]
Similar to https://github.com/magento/magento2/issues/1489
Magento 2  (and Magento 1.x, including the latest Magento 1.9.x) use very outdated PayPal merchant countries and currencies lists.

**Comment by piotrekkaminski** [comment]
This issue is resolved and should be published soon. 
@asemenenko tagging you to make sure the PayPal integration uses latest list.
