### ISSUE TITLE
Create Credit Memo for Braintree transactions.

### ISSUE THREAD

**Issue by devgoku** [magento/magento2#17068]
Getting error when do the Credit Memo by clicking on Refund button in Braintree payment gateway.
  In debug log, it is saying that 

> Cannot refund a transaction unless it is settled

But transaction is showing settled in Braintree account.

![image](https://user-images.githubusercontent.com/30754318/43147787-7c836c3e-8f81-11e8-98a2-8884d58b492c.png)

### Preconditions

1. Magento 2.1.4

### Steps to reproduce

1. Order from frontend and make payment with credit card using Braintree payment gateway
2. In admin , create credit memo from invoice detail page. Click on Refund button 

### Expected result

1. It should show success message for credit memo.

### Actual result

1. Transaction has been declined. Please try again later.
2. In log it says - [2018-07-24 12:55:05] main.CRITICAL: Braintree error response. [] []
3. ![image](https://user-images.githubusercontent.com/30754318/43141328-473d552a-8f73-11e8-80be-e94aa8d72c41.png)
4. In debug.log
[2018-07-24 13:43:34] main.DEBUG: array (
  'request' => 
  array (
    'transaction_id' => 'bh7598p1',
    'amount' => '230.11',
  ),
  'client' => 'Magento\\Braintree\\Gateway\\Http\\Client\\TransactionRefund',
  'response' => 
  array (
    'success' => false,
    '' . "\0" . '*' . "\0" . '_attributes' => 
    array (
      'errors' => 
      Braintree\Error\ErrorCollection::__set_state(array(
         '_errors' => 
        Braintree\Error\ValidationErrorCollection::__set_state(array(
           '_errors' => 
          array (
          ),
           '_nested' => 
          array (
            'transaction' => 
            Braintree\Error\ValidationErrorCollection::__set_state(array(
               '_errors' => 
              array (
                0 => 
                Braintree\Error\Validation::__set_state(array(
                   '_attribute' => 'base',
                   '_code' => '91506',
                   '_message' => 'Cannot refund a transaction unless it is settled.',
                )),
              ),
               '_nested' => 
              array (
              ),
               '_collection' => 
              array (
              ),
            )),
          ),
           '_collection' => 
          array (
          ),
        )),
      )),
      'params' => 
      array (
        'transaction' => 
        array (
          'amount' => '230.11',
        ),
        'merchantId' => 'XXXXXXXXXX',
        'id' => 'bh7598p1',
      ),
      'message' => 'Cannot refund a transaction unless it is settled.',
      'creditCardVerification' => NULL,
      'transaction' => NULL,
      'subscription' => NULL,
      'merchantAccount' => NULL,
    ),
  ),
) {"is_exception":false} []

**Comment by magento-engcom-team** [comment]
Hi @devgoku. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@devgoku do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @devgoku, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by devgoku** [comment]
@engcom-backlog-nickolas, So there will be release on v2.1.4? Or I need to upgrade Magento version

**Comment by engcom-backlog-nickolas** [comment]
@devgoku, there definitely won't be fix for 2.1.4, as it already has been released. 
The best solution is to upgrade you magento instance to released 2.2.x. Which is 2.2.5 currently.

**Comment by magento-engcom-team** [comment]
@devgoku We are closing this issue now, as we are winding down `2.1-develop` in this repository. Please consider upgrading to the newer version where issue is fixed.

**Comment by poojapawar12** [comment]
@magento-engcom-team  I am using magento2.4.6 and getting same error 
1) Create Order using any ship method 
2) Paid amount using braintree sandbox credit card
3) in admin section while creating Credit-memo online refund
4) getting error : 
![image](https://github.com/magento/magento2/assets/133887565/5861f400-be28-4376-bfea-58d18d41c737)
![image](https://github.com/magento/magento2/assets/133887565/6b16aeac-71f7-42e2-a681-8333a1cb257d)
