### ISSUE TITLE
Buttons don't work FF 40.02

### ISSUE THREAD

**Issue by kingdiablo** [magento/magento2#1707]
![capturemm2](https://cloud.githubusercontent.com/assets/13867895/9354760/02678460-466b-11e5-91a7-3b03ab4352db.PNG)
New install - first time login to admin.

**Comment by kingdiablo** [comment]
![capturemm21](https://cloud.githubusercontent.com/assets/13867895/9354826/869a93ee-466b-11e5-8cb9-191c48340ea8.PNG)

**Comment by guz-anton** [comment]
HI kingdiablo,
It's very strange issue. Looks like something wrong with static files generation. But if it is an Server issue then I'm surprising how you get to this page. Any way it would be handy if you provide:
 - What server do you use: nginx + php-fpm or apache or other
 - Do you setup *mode* for Magento app? What mode does Server use?
 - Does Server user has write permissions for `pub/static` folder?
 - Does `pub/static` contains anything?

**Comment by sivaschenko** [comment]
Closing this ticket as there is no response. Please feel free to reopen it case any additional details will be available.
