### ISSUE TITLE
Install stuck at 80%

### ISSUE THREAD

**Issue by shikata-ga-nai** [magento/magento2#1708]
Hi,

I deployed a new LAMP droplet on digital ocean and was trying to install magento 2. Firstly i tried 3 times using [official guide](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html) with safari, the installation got stuck at 91% and no progress even after 2 hours each time. Every time i started again from scratch with completely new droplet. Now I tried using chrome and got stuck at 80% installing online sales module.

Any ideas?

**Comment by mazhalai** [comment]
@shikata-ga-nai Thank you for reporting this issue, can you please tell us what version of magento? and if you are using sample-data.

**Comment by shikata-ga-nai** [comment]
@mazhalai I'm trying to install current 1.0.0-beta version. The install was without sample data, because the checkbox was disabled in my case.

**Comment by mazhalai** [comment]
@shikata-ga-nai do you have xdebug enabled? Also, can you try again after clearing your `var` directory? Any errors in logs? If you have access to command line, please try the [CLI](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli.html)

**Comment by shikata-ga-nai** [comment]
@mazhalai no xdebug was installed. Installed magento with command line, without sample data. Installation completed but only text displayed. I found [this manual](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_no-styles.html) but the problem is that there are no frontend and adminhtml directories inside pub folder. So the images and stylesheets are not loaded, only pure text.

**Comment by mazhalai** [comment]
@shikata-ga-nai  is `mod_rewrite` turned on? what version of apache do you have?

**Comment by shikata-ga-nai** [comment]
@mazhalai mod_rewrite is loaded and apache version is 2.4.7

**Comment by mazhalai** [comment]
Are you on [developer or default or production](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) mode? if you are not on developer mode, you have to [deploy the static files](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html).

**Comment by shikata-ga-nai** [comment]
@mazhalai the mode wasn't specified, so apparently it was default mode. Although I followed your advice and deployed the static files, the stylesheets and images were loaded, the links on the page don't work. And I cannot access /admin interface. In guide I saw the url is generated when installation is complete in a /admin_123abcd way, but for me it only showed
[Progress: 280 / 280]
[SUCCESS]: Magento installation complete.
and no admin url link.
Could the problem be in mod_rewrite module? What do you think?

**Comment by xcomSteveJohnson** [comment]
What branch are you using ... develop or master?

In addition to enabling the mod_rewrite module, did you set AllowOverrides All in your Apache or virtual host config?

http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache.html#install-ubuntu-apache-rewrites

**Comment by shikata-ga-nai** [comment]
@xcomSteveJohnson master. The AllowOverrides All was not set, so it was the problem. Thank you.
