### ISSUE TITLE
Problem Installing Sample Data

### ISSUE THREAD

**Issue by chapagain** [magento/magento2#1710]
I followed instructions from: http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data.html

I am trying to install Magento2 version `1.0.0-beta`.

I enabled sample data before installing Magento and at the end of installation, I got the following error: 

>Error during sample data installation: 
>Source class "\Magento\SampleData\Model" for "Magento\SampleData\Model\Logger" generation does not exist

I then tried installing sample data after installing Magento.
I am getting the following error while installing sample data after installing Magento:

>[InvalidArgumentException]
>There are no commands defined in the "sampledata" namespace.

**Comment by xcomSteveJohnson** [comment]
Are you using the develop branch or master branch?

**Comment by chapagain** [comment]
Had checkout `0.74.0-beta14` before but hadn't installed it. Recently, I tried to update it to `1.0.0-beta` from the releases page. I used the following commands:

>git reset --hard
>git checkout -b 1.0.0-beta

After that, I tried to install Magento2 with and without sample data and got this problem.

**Comment by xcomSteveJohnson** [comment]
In https://github.com/magento/magento2, there is a master branch and a develop branch.

**Comment by daim2k5** [comment]
@chapagain remove the hole magento directory and make a new clone (so we can be sure that no old files left) and then try the install again

**Comment by chapagain** [comment]
@xcomSteveJohnson @daim2k5 @vpelipenko : 

Thanks for the reply. 

- I deleted the whole magento2 directory.
- Cloned magento2 again.
- Enabled sample data before installing Magento2.
- Installed Magento2.
- Finally, done! 

Magento2 installed successfully with sample data.

**Comment by dmitrii-fediuk** [comment]
`There are no commands defined` message hides some internal error: usually an error in `composer.json` or `module.xml` file:
https://mage2.pro/t/176 
https://github.com/magento/magento2/issues/2300
