### ISSUE TITLE
Enterprise Edition Beta?

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1712]
Hi,

As an enterprise when/if can we get access to enterprise beta? This was mentioned at Magento Live.

**Comment by vpelipenko** [comment]
Hi @craigcarnell. Enterprise version is not free and it won't be available for all.

**Comment by craigcarnell** [comment]
@vpelipenko I know it's not free we pay for the thing :8ball:

**Comment by natrod** [comment]
Would nice if existing enterprise users could get a copy of the code

**Comment by choukalos** [comment]
Currently it's only available to a few merchants as part of our merchant beta program.  We'll open that up to all of our current enterprise merchants at GA.
