### ISSUE TITLE
XAMPP All Static Resources are missing after clean install

### ISSUE THREAD

**Issue by RawPhunky** [magento/magento2#1713]
Static resources are missing after clean install of magento: pub/static is empty.
After attempt to go to http://127.0.0.1/magento20/admin/ folder tree is created under pub/static/ but it has no files inside.
I'm setting it up on XAMPP, tried both Master and Dev branches.

This seems to be related to this issue:
http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_no-styles.html
But I do have mod_rewrite enabled and working.

![1](https://cloud.githubusercontent.com/assets/2244332/9404522/1c15324c-47f9-11e5-938a-194e8943effe.png)

![magentoissue](https://cloud.githubusercontent.com/assets/2244332/9381270/72f5e252-473e-11e5-84c1-3515094da55d.png)

**Comment by RawPhunky** [comment]
This seems to be related to this issue:
http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_no-styles.html

But I do have mod_rewrite enabled and working.

I have tried deploying directly to 127.0.0.1 many times 

All static resources are missing for both frontend and adminhtml. Only the directory trees are set up, but no files in them.

![1](https://cloud.githubusercontent.com/assets/2244332/9404522/1c15324c-47f9-11e5-938a-194e8943effe.png)

**Comment by RawPhunky** [comment]
After clean install pub/static is empty.
After attempt to go to http://127.0.0.1/magento20/admin/ folder tree is created under pub/static/ but it has no files inside.

**Comment by mazhalai** [comment]
@RawPhunky have you set up `AllowOverride` in apache? Also, what [mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) are you running magento in?  If you are not on developer mode, you have to [deploy the static files](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html).

**Comment by RawPhunky** [comment]
Duplicate to https://github.com/magento/magento2/issues/1369

Changing app/etc/di.xml from Symlink to Copy fixes my issues.
