### ISSUE TITLE
Incorrect xsd location in resources.xml for Sales Module

### ISSUE THREAD

**Issue by jitze** [magento/magento2#1714]
The xsd location in the resource file of the Sales module (app/code/Magento/Sales/etc/resources.xml)  is incorrect.

It has A as the xsd instead of B
A: ../../../../../../magento2ce/lib/internal/Magento/Framework/App/etc/resources.xsd
B: ../../../../../lib/internal/Magento/Framework/App/etc/resources.xsd

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-41992

**Comment by okorshenko** [comment]
@jitze  Internal ticket MAGETWO-41992 is closed and delivered to mainline. Please, see https://github.com/magento/magento2/commit/bb5cae98f764275e3b4e9b4834e1775336357199. 
Please, let us know if you still have an issue
