### ISSUE TITLE
Backend quick jump form

### ISSUE THREAD

**Issue by dmaciej** [magento/magento2#1715]
I have an idea to introduce some kind of a quick jump form in the backend. There is a lot of pages and settings sections in the admin panel, and we should consider implementing some method to make it easier to review. It would be very useful for casual administrators and developers as well.

We have product search in backend already, so it could be some base for this feature. However, addional search box on the oposite side should also be taken into consideration.

There is a similar module for Magento 1.x here https://github.com/tim-reynolds/magento-qconfig
but it provides configuration search only (like phpStorm settings search).

Thanks in advance for your feedback.

**Comment by pboisvert** [comment]
@elenleonova Elena--can you take ownership on this one? @piotrekkaminski Wasn't this one of the hack ideas from Imagine? If so is there a starting point that could be leveraged?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Backend-quick-jump-form/idi-p/44895).
