### ISSUE TITLE
Issue with SOAP services after upgrading to 2.2.5 when adding store code to urls

### ISSUE THREAD

**Issue by carolineboivin** [magento/magento2#17164]
Hello, 

We recently upgraded a project from Magento CE 2.2.2 to 2.2.5 and we have been experiencing an issue with SOAP services since. 
It seems that, when adding store code to urls is enabled, the endpoint for services in the WSDL always contains the store code. Whilst this works fine for a store-view scope request, it is problematic for the scope "all" because the part "/admin" is added in the domain name but requests using the "/admin" part will return 404s. 

If I load the WSDL at 
https://mydomainname.com/soap/all?wsdl&services=catalogProductRepositoryV1, 
all services urls in the returned WSDL will be like this: 
https://mydomainname.com/admin/soap/all?services=catalogProductRepositoryV1.

Although, calling this url returns a 404 because the call for the scope all should not contain the /admin part in the base url, before the /soap part. And if I call the services without the /admin part, I get a "ProcedureNotPresent" soap fault because there is a mismatch between the urls in the wsdl and the url that actually works.

For further call in a store view scope, calling
https://mydomainname.com/fr/soap/fr?services=catalogProductRepositoryV1
returns services urls in the same way
https://mydomainname.com/fr/soap/fr?services=catalogProductRepositoryV1
which works fine because the "add store code to urls" functionality recognizes the base url with the store view code.

I have for now just worked around the issue with an after plugin that removes the /admin part that is added in the getEndpointUri() function from the Soap Server Model in the module webapi. But if anyone else have this issue and this can be fixed that would be great.

### Preconditions
1. Magento CE 2.2.5
2. Have the configuration "Add store code to urls" set to Yes and two different store views on one website.

### Steps to reproduce
1. Create a soap client that requests the WSDL within the scope "all".
2. Use the URL returned in the WSDL to make a catalogProductRepositoryV1GetListRequest (or any other request)

### Expected result
1. The SOAP call should return a catalogProductRepositoryV1GetListResponse

### Actual result
1. The response is a 404 page.

The WSDL urls should not contain the /admin store code when requesting the scope all.

**Comment by magento-engcom-team** [comment]
Hi @carolineboivin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@carolineboivin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by carolineboivin** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @carolineboivin. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @carolineboivin, here is your [Magento instance](https://i-17164-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17164-2-2-5.engcom.dev.magento.com/admin](https://i-17164-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by carolineboivin** [comment]
@magento-engcom-team I confirm that I was able to reproduce the issue on the 2.2.5 vanilla instance

**Comment by ghost** [comment]
Hi @carolineboivin thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by baljinder981** [comment]
Any clue on when we can expect the extension to be compatible with Magento 2.3

**Comment by sureshsdckap** [comment]
the issue is not reproducible on 2.4-develop branch
@magento give me 2.3.x instance with sample data

**Comment by magento-engcom-team** [comment]
Hi @sureshsdckap. Thank you for your request. I'm working on Magento 2.3.x instance for you

**Comment by sureshsdckap** [comment]
@magetno the issue is not reproducible on 2.3.4 version

**Comment by jpellerin-absolunet** [comment]
@magento-engcom-team I can still reproduce this bug on a 2.4 instance. Is there a fix I can apply to make it work? Or would @carolineboivin's workaround be the way to go?

**Comment by magento-engcom-team** [comment]
Hi @carolineboivin. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24531` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
