### ISSUE TITLE
Reviews Grid Listing, Reviews Edit Form and Reviews New Form are not showing in admin Magento2.2.2

### ISSUE THREAD

**Issue by A-1A** [magento/magento2#17165]
**Preconditions:** 

Magento 2.2.2
PHP Version 7.0.25

**Steps to reproduce**

Go to admin > MARKETING > User Content > Reviews
![ozd5s](https://user-images.githubusercontent.com/37658339/43267819-9ac3f042-910c-11e8-8d20-316ce6525aa5.png)

**Expected result**
Want list of reviews
![doeqp](https://user-images.githubusercontent.com/37658339/43267877-bfbd56a4-910c-11e8-89c2-449ccbd80092.png)

**Actual result**
No review list showing only "New  Review" button showing
![screenshot-192 168 1 120-2018 07 24-15-23-55](https://user-images.githubusercontent.com/37658339/43268072-499f6c54-910d-11e8-9ca2-45fe4ec9e26d.png)

**Comment by magento-engcom-team** [comment]
Hi @A-1A. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@A-1A do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@A-1A, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit the issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result
Also, make sure what issue is reproducible on clean magento installation without any custom modules.

**Comment by A-1A** [comment]
**Preconditions:** 

Magento 2.2.2
PHP Version 7.0.25

**Steps to reproduce**

Go to admin > MARKETING > User Content > Reviews
![ozd5s](https://user-images.githubusercontent.com/37658339/43267819-9ac3f042-910c-11e8-8d20-316ce6525aa5.png)

**Expected result**
Want list of reviews
![doeqp](https://user-images.githubusercontent.com/37658339/43267877-bfbd56a4-910c-11e8-89c2-449ccbd80092.png)


**Actual result**
No review list showing only "New  Review" button showing
![screenshot-192 168 1 120-2018 07 24-15-23-55](https://user-images.githubusercontent.com/37658339/43268072-499f6c54-910d-11e8-9ca2-45fe4ec9e26d.png)

**Comment by A-1A** [comment]
Also Please Check For Other Infomation
https://magento.stackexchange.com/questions/235681/reviews-grid-listing-reviews-edit-form-and-reviews-new-form-are-not-showing-in
https://magento.stackexchange.com/questions/235727/review-and-rating-not-working-in-admin-and-frontend-in-magento2

**Comment by ghost** [comment]
@A-1A, this information is not enough. We assume you have some custom modules, which break correct workflow. Please ask bot for a test instance and try to reproduce the issue on it.

**Comment by A-1A** [comment]
But I checked after disabled all custom modules also I reconfig module-review via composer.
AND
Also I disabled all third-party module via config.php and via command line but issue not resolving. I am working on this task from last 5 days and continues working...

**Comment by A-1A** [comment]
Log File Showing Error Below
[2018-07-24 06:25:27] main.DEBUG: cache_invalidate: {"method":"GET","url":"http://localhost/magento2/admin/review/product/index/key/33716591056fa74ee620fcd6424973062b37f27da9b6fe33cc1bcab69a9e5ba0/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"}} []

**Comment by ghost** [comment]
@A-1A please ask bot for a test instance and try to reproduce the issue on it.

**Comment by A-1A** [comment]
Please check video i shared
https://www.useloom.com/share/e8c320100c2d4cbabec5997988f00ef5

**Comment by ghost** [comment]
@A-1A please try to reproduce the issue on a clean Magento installation. If you succeed, please reopen the issue.

**Comment by A-1A** [comment]
After copy module-review code in app/code/Custom/Review folder it working with same code.
I Replace Magento with Custom and change tables names only then it working.
Why it is not working with Magento_Review Name in vendor/magento/module-review/


IT'S MEAN THERE ARE NO CONFLICT ISSUE WITH OTHER MODULES SO PLEASE OPEN TICKET AGAIN AND PLEASE CHECK.
THIS ISSUE ARE COMING IN ANOTHER MAGNTO2.2.2 SETUP.
