### ISSUE TITLE
Cookie deletion not working on cookies with leading "." in domain

### ISSUE THREAD

**Issue by michi-p** [magento/magento2#17173]
### Preconditions

1. Magento 2.2.5
2. PHP 7.1.13

### Steps to reproduce

1. Create cookie with name `foo`, value `bar` and domain `.example.shop.com` (leading dot)
2. execute function `deleteCookie('foo')` of `\Magento\Framework\Stdlib\CookieManagerInterface`

### Expected result

1. Cookie should be deleted (at least after page refresh)

### Actual result

1. Cookie is not deleted and still contains the value 'bar'

**Comment by magento-engcom-team** [comment]
Hi @michi-p. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@michi-p do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
In general, the function to delete a cookie needs the same input parameters.

**Comment by michi-p** [comment]
@DanielRuf what do you mean by that?  
The function `deleteCookie` accepts two parameters: the name of the cookie ('foo' in my example) and a default return value if the cookie doesn't exists.

**Comment by DanielRuf** [comment]
https://github.com/magento/magento2/blob/1795f67500287244e4a2443cd51ee29fd5f4a77a/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php#L303

https://github.com/magento/magento2/blob/1795f67500287244e4a2443cd51ee29fd5f4a77a/lib/internal/Magento/Framework/Stdlib/Cookie/CookieMetadata.php#L17

http://php.net/manual/en/function.setcookie.php

https://stackoverflow.com/a/2287755/753676

**Comment by DanielRuf** [comment]
> and a default return value if the cookie doesn't exist

Not sure where you see this. Can you point me to the method declaration?

**Comment by michi-p** [comment]
Sorry, I mixed something up. Now I know what you meant.  

> In general, the function to delete a cookie needs the same input parameters.  

You are right. If I create the cookie with the `setPublicCookie` function and deletes it with the `deleteCookie` function (from \Magento\Framework\Stdlib\CookieManagerInterface) everything works as expected if I provide the same input parameters. The default domain for the cookie would be something like `example.shop.com`  
However, in my case the cookie is set in a javascript function and therefore has a domain with a leading `.` set (`.example.shop.com`).  
Now the `deleteCookie` function can't delete the cookie anymore, because of the slightly different cookie-domain.

**Comment by DanielRuf** [comment]
> Now the deleteCookie function can't delete the cookie anymore, because of the slightly different cookie-domain.

Please check the `$metadata` parameter which supports setting the domain.
This is what I mean, you can explicitely set it to `.domain.tld`.

**Comment by DanielRuf** [comment]
https://magenest.com/manage-cookies-in-magento-2/
https://www.maximehuran.fr/en/cookies-and-magento-2/

```
$metadata = $this->_cookieMetadataFactory
->createPublicCookieMetadata()
->setPath('YOUR PATH')
->setDomain('YOUR DOMAIN')
->setDuration(self::JOB_COOKIE_DURATION);
```

**Comment by michi-p** [comment]
It's working that way - I already tried - but in my opinion it should not be necessary to set the domain with a leading dot.  
It should be irrelevant if a cookie domain has a leading dot or not: https://stackoverflow.com/a/20884869/6769302

**Comment by DanielRuf** [comment]
> It's working that way - I already tried - but in my opinion it should not be necessary to set the domain with a leading dot.
> It should be irrelevant if a cookie domain has a leading dot or not: stackoverflow.com/a/20884869/6769302

This can not be done in general as this is no how setcookie and others work.
The dot is for all subdomains and deleting all cookies of all subdomains with the same name would produce issues on multi site shops with multiple subdomains.

Imho the current code is correct and how it should be
By default setcookie uses the normal domain + subdomain, not the one with the dot at the beginning.


Also the dot is a relict for old browsers and standards. setcookie does not use it by default

http://php.net/manual/en/function.setcookie.php

```
domain
The (sub)domain that the cookie is available to. Setting this to a subdomain (such as 'www.example.com') will make the cookie available to that subdomain and all other sub-domains of it (i.e. w2.www.example.com). To make the cookie available to the whole domain (including all subdomains of it), simply set the value to the domain name ('example.com', in this case).

Older browsers still implementing the deprecated » RFC 2109 may require a leading . to match all subdomains.
```

**Comment by DanielRuf** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

```
;domain=domain (e.g., 'example.com' or 'subdomain.example.com'). If not specified, this defaults to the host portion of the current document location. Contrary to earlier specifications, leading dots in domain names are ignored, but browsers may decline to set the cookie containing such dots. If a domain is specified, subdomains are always included.
```

The problem is your JavaScript code, not the PHP part.

**Comment by engcom-backlog-nickolas** [comment]
Hello @michi-p, thank you for your report. As, @DanielRuf kindly pointed out, and I agree with him, there is nothing wrong with magento code in this case. Therefore I'm closing this issue for now.
If you'd like to update it, please reopen the issue.

**Comment by michi-p** [comment]
Thank you for your help @DanielRuf   
For those of you struggling with the same problem:  
I used the the jquery cookie library and set the cookie with the function `$.cookie('foo', 'bar');`  
The result was a cookie with the domain `.example.shop.com`.  
When I set an empty domain as parameter `$.cookie('foo', 'bar', { domain: '' });` I get a cookie with the domain `example.shop.com` and everything works fine with the Magento PHP functions.
