### ISSUE TITLE
Product doesn't show on website when adding it with REST

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1720]
We're trying to load our categories and products through REST. Everything is added nicely and is visible in the backend, but it doesn't appear on the website. The option "Display Out of Stock Products" is put on "Yes".

After saving the product in the admin OR re-enabling it in the admin, it does show up!

Steps to reproduce:

- Add category (REST or admin, doesn't matter)
- Add product with REST:

url: magento2/rest/V1/products

{
    "product": {
        "sku": "TEST", 
        "name": "TEST",
        "visibility": 4, 
        "type_id": "simple",
        "price": 3.62, 
        "status": 1,
        "attribute_set_id": 4, 
        "custom_attributes": [
            {
                "attribute_code": "description",
                "value": "TEST"
            }
        ]
    }
}

- Add product link with REST:

url: magento2/rest/V1/categories/[CATEGORY_ID]/products

{
    "productLink": {
        "sku": "TEST",
        "category_id": [CATEGORY_ID]
    }
}

After there steps the product is NOT visible on the website!

**Comment by kokoc** [comment]
@rklerck thank you for reporting the issue. Internal reference: MAGETWO-39663

**Comment by rklerck** [comment]
When running the indexer, by a index on schedule, this one also works fine. 
Not sure if it works when the indexes are on update on save.

**Comment by arkadiych** [comment]
@rklerck Thank you for your issue. It has been fixed in 2.0.0-rc.
You can find changes in next commits:
https://github.com/magento/magento2/commit/149a9363bb33756115cf3076973064c229860835
https://github.com/magento/magento2/commit/e39e8d4a3a2b6d69b5dacbfd256bb21bdaa87e4a
