### ISSUE TITLE
DI compilation fails on class keyword

### ISSUE THREAD

**Issue by shanethehat** [magento/magento2#1722]
PHP 5.5 introduced the ability to use the `class` keyword to return the fully qualified class name of a class: http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

When compiling the DI container, the setup module's PHPScanner tokenises PHP files that it finds, and upon discovering a `T_CLASS` token it attempts to capture the following class name and create a ReflectionClass object from it. In the case of `Foo::class` this fails, causing a reflection exception.

The PHPScanner needs to be modified so that it allows for this use of the class keyword.

**Comment by melnikovi** [comment]
Internal ticket MAGETWO-41996

**Comment by piotrekkaminski** [comment]
This should be fixed now.
