### ISSUE TITLE
Filter of FilterGroup doesn't work if field is not set

### ISSUE THREAD

**Issue by swolf91** [magento/magento2#17254]
If you wanna have the product list using several filters in a filter group (or condition) it only works if all of the or condition fields have values specified. So if I wanna have a product with the name containing a string and a description containing the same string, products matching the name will only be retrieved when a description is set.

# Preconditions

Issue occurs with Magento 2.2.5.

# Steps to reproduce

I'm working with the rest api and call the route V1/products with the query params:

searchCriteria[page_size]: 30
searchCriteria[current_page]: 1
searchCriteria[filter_groups][0][filters][0][field]: name
searchCriteria[filter_groups][0][filters][0][value]: %wahr%
searchCriteria[filter_groups][0][filters][0][condition_type]: like
searchCriteria[filter_groups][0][filters][1][field]: sku
searchCriteria[filter_groups][0][filters][1][value]: %wahr%
searchCriteria[filter_groups][0][filters][1][condition_type]: like
searchCriteria[filter_groups][0][filters][2][field]: description
searchCriteria[filter_groups][0][filters][2][value]: %wahr%
searchCriteria[filter_groups][0][filters][2][condition_type]: like
searchCriteria[filter_groups][0][filters][3][field]: short_description
searchCriteria[filter_groups][0][filters][3][value]: %wahr%
searchCriteria[filter_groups][0][filters][3][condition_type]: like
fields: items[id,sku,name,custom_attributes],search_criteria,total_count

```
<magento-env>/rest/<store-view>/V1/products?searchCriteria%5Bpage_size%5D=30&searchCriteria%5Bcurrent_page%5D=1&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=name&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=%25wahr%25&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=like&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bfield%5D=sku&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bvalue%5D=%25wahr%25&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bcondition_type%5D=like&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B2%5D%5Bfield%5D=description&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B2%5D%5Bvalue%5D=%25wahr%25&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B2%5D%5Bcondition_type%5D=like&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B3%5D%5Bfield%5D=short_description&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B3%5D%5Bvalue%5D=%25wahr%25&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B3%5D%5Bcondition_type%5D=like&fields=items%5Bid%2Csku%2Cname%2Ccustom_attributes%5D%2Csearch_criteria%2Ctotal_count
```

Magento tries to load the products with the following sql querry:
```sql
SELECT `e`.*,
       IF(at_status.value_id > 0, at_status.value, at_status_default.value) AS `status`,
       IF(at_visibility.value_id > 0, at_visibility.value,
          at_visibility_default.value)                                      AS `visibility`,
       IF(at_name.value_id > 0, at_name.value, at_name_default.value)       AS `name`,
       IF(at_description.value_id > 0, at_description.value,
          at_description_default.value)                                     AS `description`,
       IF(at_short_description.value_id > 0, at_short_description.value,
          at_short_description_default.value)                               AS `short_description`
FROM `catalog_product_entity` AS `e`
       INNER JOIN `catalog_product_entity_int` AS `at_status_default`
         ON (`at_status_default`.`entity_id` = `e`.`entity_id`) AND (`at_status_default`.`attribute_id` = '97') AND
            `at_status_default`.`store_id` = 0
       LEFT JOIN `catalog_product_entity_int` AS `at_status`
         ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '97') AND
            (`at_status`.`store_id` = 3)
       INNER JOIN `catalog_product_entity_int` AS `at_visibility_default`
         ON (`at_visibility_default`.`entity_id` = `e`.`entity_id`) AND
            (`at_visibility_default`.`attribute_id` = '99') AND `at_visibility_default`.`store_id` = 0
       LEFT JOIN `catalog_product_entity_int` AS `at_visibility`
         ON (`at_visibility`.`entity_id` = `e`.`entity_id`) AND (`at_visibility`.`attribute_id` = '99') AND
            (`at_visibility`.`store_id` = 3)
       INNER JOIN `catalog_product_entity_varchar` AS `at_name_default`
         ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '73') AND
            `at_name_default`.`store_id` = 0
       LEFT JOIN `catalog_product_entity_varchar` AS `at_name`
         ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '73') AND
            (`at_name`.`store_id` = 3)
       INNER JOIN `catalog_product_entity_text` AS `at_description_default`
         ON (`at_description_default`.`entity_id` = `e`.`entity_id`) AND
            (`at_description_default`.`attribute_id` = '75') AND `at_description_default`.`store_id` = 0
       LEFT JOIN `catalog_product_entity_text` AS `at_description`
         ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '75') AND
            (`at_description`.`store_id` = 3)
       INNER JOIN `catalog_product_entity_text` AS `at_short_description_default`
         ON (`at_short_description_default`.`entity_id` = `e`.`entity_id`) AND
            (`at_short_description_default`.`attribute_id` = '76') AND `at_short_description_default`.`store_id` = 0
       LEFT JOIN `catalog_product_entity_text` AS `at_short_description`
         ON (`at_short_description`.`entity_id` = `e`.`entity_id`) AND
            (`at_short_description`.`attribute_id` = '76') AND (`at_short_description`.`store_id` = 3)
WHERE ((IF(at_name.value_id > 0, at_name.value, at_name_default.value) LIKE '%wahr%') OR
       (`e`.`sku` LIKE '%wahr%') OR
       (IF(at_description.value_id > 0, at_description.value, at_description_default.value) LIKE '%wahr%') OR
       (IF(at_short_description.value_id > 0, at_short_description.value, at_short_description_default.value) LIKE
        '%wahr%'))
LIMIT 30;
```

The problem is the left join. It will only join the values, if the right table is set (so if I don't have a short description, the products won't be found even if the description, name or sku matches)

# Expected result

In my expectation, products should be found nevertheless if one of the values is not set. So maybe using a full join would be better.

# Actual result

Products are not found

**Comment by magento-engcom-team** [comment]
Hi @boeserwolf91. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@boeserwolf91 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by swolf91** [comment]
@engcom-backlog-pb Why did you add the label feature request? For me its definitely a bug. You search for a certain thing in your products. For example "shirt". Now you wanna show the searcher all products having the word "shirt" in the name, in the sku, in the description or in the short description. So why should the search only consider products having all attributes set? It's a legal case that for example the short description isnt set. It must work nevertheless. So it's a bug, not a new feature.

**Comment by engcom-backlog-nickolas** [comment]
@boeserwolf91, thank you for your report. I'm closing this issue as duplicate #16425
