### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) - Magento 2.3

### ISSUE THREAD

**Issue by edwinbos** [magento/magento2#17285]
### Preconditions
* Magento 2.3-alpha57
* PHP 7.1.19
* MySQL 5.7

### Steps to reproduce
Magento 2.3 was working, but after upgrading to the latest alpha release Magento has the following error:
`Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in .../vendor/magento/framework/Filesystem/Directory/Write.php on line 35`

There is a question mark before PathValidatorInterface and is added on the 13th of July. https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Filesystem/Directory/Write.php

After removing the question mark for testing, I get the same error in .../vendor/magento/framework/Filesystem/Directory/Read.php on line 54 and after removing that one I get the same error on line 71 and so on.

**Comment by magento-engcom-team** [comment]
Hi @edwinbos. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@edwinbos do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by edwinbos** [comment]
@magento-engcom-team give me 2.3-develop instance

Installed a fresh Magento 2.2.5 and upgraded to 2.3 from there and used the update script that is provided by Magento.
I can confirm that I was able to reproduce the issue on vanilla Magento instance following steps to reproduce.

**Comment by magento-engcom-team** [comment]
Hi @edwinbos. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edwinbos, here is your [Magento instance](https://i-17285-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-17285-2-3-develop.engcom.dev.magento.com/admin](https://i-17285-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
You mean nullable types in this line?
Can you try PHP 7.2.x?

**Comment by ghost** [comment]
@edwinbos, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Nullable types are introduced in PHP 7.1 and Magento 2.3 currently supports PHP 7.1 & 7.2, so nullable type hint should not cause any problems.

**Comment by edwinbos** [comment]
@DanielRuf Yes, it works with PHP 7.2, but not with PHP 7.1.
The exact version of PHP was 7.1.19

**Comment by ghost** [comment]
@edwinbos, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![1](https://user-images.githubusercontent.com/40756187/44212784-f1cfb600-a174-11e8-86cd-c4b9447ea9dd.gif)

**Comment by vinaysikarwar** [comment]
I am facing the same issue when installing the fresh magento 2.3

**Comment by DanielRuf** [comment]
> I am facing the same issue when installing the fresh magento 2.3

Which PHP version do you use?

**Comment by vinaysikarwar** [comment]
Php 7.1.2

**Comment by DanielRuf** [comment]
@vinayshah can you try a newer version of PHP 7.1 or 7.2?

**Comment by vitmarks** [comment]
guys, for those who has this error, here solution:
IF you upgraded php from xxx<7.1 to 7.1>xxx, don't forget this:
sudo a2dismod phpx.x < (x.x) version you are used before
sudo a2enmod php7.2 
sudo service apache2 restart

Don't forget to set permission!!
have fun!

**Comment by vitmarks** [comment]
Maybe it is a good note, to mention it on the installation documentation 2.3 Beta

**Comment by DanielRuf** [comment]
> sudo a2enmod php7.2

Well, this is the PHP 7.2 service, not 7.1.

**Comment by nuovecode** [comment]
Same issue for me on php 7.1.23

**Comment by DanielRuf** [comment]
@nuovecode

https://github.com/magento/magento2/issues/17285#issuecomment-423089807

**Comment by nuovecode** [comment]
It works with php 7.2.* ( I was reporting just to add info to the issue) thanks!

**Comment by DanielRuf** [comment]
> It works with php 7.2.* ( I was reporting just to add info to the issue) thanks!

Thanks for the info. was not quite clear for me.

**Comment by fballiano** [comment]
same error for me with M2.3.0 on php 7.0.25

**Comment by fballiano** [comment]
I see now that M2.3 is not compatible with 7.0, but when I first started the installation I got this message:

![schermata 2018-11-29 alle 10 39 03](https://user-images.githubusercontent.com/909743/49216481-1b7ab900-f3c3-11e8-9a58-dac94a7b01a1.jpg)

with the link to the 2.2 documentation (should be 2.3) and the wrong php version showed.

**Comment by DanielRuf** [comment]
See https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html. You get there from https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements2.html and https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements.html

**Comment by DanielRuf** [comment]
![bildschirmfoto 2018-11-29 um 11 57 40](https://user-images.githubusercontent.com/827205/49217511-09eade80-f3ce-11e8-9143-d25e3993b80d.png)

**Comment by fballiano** [comment]
yes, I'll create a PR to change that message in app/bootstrap.php

**Comment by ytterdal** [comment]
I use UnoEuro as webhost and faced same problem.
Their documentation recommended adding following line to the .htaccess file to support latestet .php version (7.2):

AddType application/x-httpd-php-latest .php

After adding this line, i got my installation working.

**Comment by taqvi** [comment]
Same issue with php 7.0.2 and Magento 2.3.0

**Comment by DanielRuf** [comment]
Please try upgrading PHP.
You need 7.1.3+.

**Comment by taqvi** [comment]
Hi @DanielRuf, Can you share link to download? I have spent a pretty good time in searching 7.1.3

**Comment by DanielRuf** [comment]
Download for what? It depends on your hosting provider how you can upgrade PHP.

**Comment by DanielRuf** [comment]
PHP 7.1.24 is the latest 7.1.x release.

**Comment by taqvi** [comment]
I am working on local server. So I am looking for xampp with php 7.1.3. It will be supporting if you correct.

**Comment by DanielRuf** [comment]
See https://www.apachefriends.org/en/download.html (7.1.24).

**Comment by BhaskarPothineni** [comment]
> guys, for those who has this error, here solution:
> IF you upgraded php from xxx<7.1 to 7.1>xxx, don't forget this:
> sudo a2dismod phpx.x < (x.x) version you are used before
> sudo a2enmod php7.2
> sudo service apache2 restart
> 
> Don't forget to set permission!!
> have fun!

Its Working ......

**Comment by amilaudana** [comment]
This is a compatibility issue with php 7.0.x and 7.1.x. New version is using "?" where it does not support in php previous versions. We want to install Magento on php7.0.32 and not to install php7.2 for Magento.

**Comment by DanielRuf** [comment]
7.0.x is not supported.

**Comment by DanielRuf** [comment]
See https://github.com/magento/magento2/issues/17285#issuecomment-442792234 and the screenshot after it.

Also 7.0 has reached its EOL.

**Comment by DanielRuf** [comment]
See http://php.net/supported-versions.php

**Comment by amilaudana** [comment]
ok see this too https://devdocs.magento.com/guides/v2.0/install-gde/system-requirements-tech.html

**Comment by DanielRuf** [comment]
Wrong link, there is a version selector for 2.1, 2,2, 2.3.

**Comment by DanielRuf** [comment]
Wrong link, there is a version selector for 2.1, 2.2, 2.3.

**Comment by amilaudana** [comment]
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html
correct

**Comment by DanielRuf** [comment]
Also this only affects 2.3.

**Comment by DanielRuf** [comment]
As you should not use PHP 7.0 and the docs clearly say which PHP versions are supported, this is not a problem and resolved.

Please use a newer PHP version, also regarding security.
