### ISSUE TITLE
Change in Magento Server Paths breaks setup:di:compile

### ISSUE THREAD

**Issue by tschirmer** [magento/magento2#17282]
Found that after changing $_SERVER Environment values, the cli setup:di:compile no longer works.
### Preconditions
1. php 7.0.30
2. apache 2.4.6
3. Centos 7.5.1804
4. Magento 2.2.4 (seen on Magento 2.2.5 as well)

### Steps to reproduce

1. Put Magento code into folder outside of public dir (/opt/magento2/2.2.4)
2. Add in environmental variables via a prepend_file containing the following:
```<?php
$_SERVER["MAGE_DIRS"] = array();
$_SERVER["MAGE_DIRS"]['base']["path"] = "/opt/magento2/2.2.4/";
$_SERVER["MAGE_DIRS"]['etc']["path"] = "/var/www/html/magento2/httpdocs/app/etc";
$_SERVER["MAGE_DIRS"]['upload']["path"] = "/var/www/html/magento2/httpdocs/pub/media/upload";
$_SERVER["MAGE_DIRS"]['media']["path"] = "/var/www/html/magento2/httpdocs/pub/media";
$_SERVER["MAGE_DIRS"]['static']["path"] = "/var/www/html/magento2/httpdocs/pub/static";
$_SERVER["MAGE_DIRS"]['pub']["path"] = "/var/www/html/magento2/httpdocs/pub";
$_SERVER["MAGE_DIRS"]['code']["path"] = "/var/www/html/magento2/httpdocs/generated/code";
$_SERVER["MAGE_DIRS"]['di']["path"] = "/var/www/html/magento2/httpdocs/generated/metadata";
$_SERVER["MAGE_DIRS"]['metadata']["path"] = "/var/www/html/magento2/httpdocs/generated/metadata";
$_SERVER["MAGE_DIRS"]['generated']["path"] = "/var/www/html/magento2/httpdocs/generated";
$_SERVER["MAGE_DIRS"]['var']["path"] = "/var/www/html/magento2/httpdocs/var";
$_SERVER["MAGE_DIRS"]['cache']["path"] = "/var/www/html/magento2/httpdocs/var/cache";
$_SERVER["MAGE_DIRS"]['log']["path"] = "/var/www/html/magento2/httpdocs/var/log";
$_SERVER["MAGE_DIRS"]['session']["path"] = "/var/www/html/magento2/httpdocs/var/session";
$_SERVER["MAGE_DIRS"]['tmp']["path"] = "/var/www/html/magento2/httpdocs/var/tmp";
$_SERVER["MAGE_DIRS"]['composer_home']["path"] = "/var/www/html/magento2/httpdocs/var/composer_home";
$_SERVER["MAGE_DIRS"]['view_preprocessed']["path"] = "/var/www/html/magento2/httpdocs/var/view_preprocessed/pub/static";
$_SERVER["MAGE_DIRS"]['html']["path"] = "/var/www/html/magento2/httpdocs/var/view_preprocessed";

$_SERVER["TMPDIR"] = '/var/www/html/magento2/httpdocs/var/tmp';
putenv('TMPDIR=/var/www/html/magento2/httpdocs/var/tmp');
```
3. Run the following line
`php -d auto_prepend_file=/var/www/html/magento2/httpdocs/user_env.php bin/magento setup:di:compile`

### Expected result
```
[magento_user@centos-server httpdocs]$ php -d auto_prepend_file=/var/www/html/magento2/httpdocs/user_env.php bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 7/7 [============================] 100% 1 min 386.0 MiB
Generated code and dependency injection configuration successfully.
```

### Actual result
```
[magento_user@centos-server httpdocs]$ php -d auto_prepend_file=/var/www/html/magento2/httpdocs/user_env.php bin/magento setup:di:compile
Compilation was started.
Application code generator... 3/7 [============>---------------]  42% 20 secs 216.0 MiB

  [ReflectionException]
  Class \My\NamespaceA\My\NamespaceB\InterfaceB does not exist
```

### Preliminary Fix
Remove all of the Magento/Setup Tests folder. 
Doing a scan of the Magento Codebase, `NamespaceB\InterfaceB` exists in `Magento/Setup/Test/Unit/Module/Di/Code/Reader/FileScannerTest.php`

Removing all tests from the codebase removes the error.
that is:
`[magento_user@centos-server httpdocs]$ rm /opt/magento2/2.2.4/setup/src/Magento/Setup/Test -rf`

```
[magento_user@centos-server httpdocs]$ php -d auto_prepend_file=/var/www/html/magento2/httpdocs/user_env.php bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 7/7 [============================] 100% 1 min 386.0 MiB
Generated code and dependency injection configuration successfully.
```

**Comment by magento-engcom-team** [comment]
Hi @tschirmer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@tschirmer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tschirmer** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @tschirmer. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @tschirmer, here is your [Magento instance](https://i-17282-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-17282-2-2-4.engcom.dev.magento.com/admin](https://i-17282-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tschirmer** [comment]
Can't reproduce without cli access

**Comment by ghost** [comment]
Hi @tschirmer i'm not able to reproduce by you scenario, see attachments, 
 If you'd like to update it, please reopen the issue.

![selection_047](https://user-images.githubusercontent.com/40756439/43518535-11781fba-9595-11e8-8305-fa2ff6e92d35.png)
