### ISSUE TITLE
Allow onUpdate in install

### ISSUE THREAD

**Issue by Michal-sk** [magento/magento2#1728]
I would like to suggest to add onUpdate parameter to ```Magento\Framework\DB\Ddl\Table::addForeignKey``` we now can only add ```onDelete```

**Comment by mazhalai** [comment]
@Michal-sk Thank you for your suggestion, we have created MAGETWO-42066 to track this request.

**Comment by akaplya** [comment]
Hi, this is deliberate restriction, to achieve better compatibility with other possible database engines.
But you can implement actions like  "ON UPDATE" on application level. In this case your code will be compatible with Magento SPI ( events, interceptors, e.t.c).

**Comment by piotrekkaminski** [comment]
Hello. We decided against this one and also remove existing cascades for performance reasons wherever we could.

**Comment by Michal-sk** [comment]
No problem, im actually removing it from other projects as well.
