### ISSUE TITLE
stronger passwords allowed for admin accounts

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1729]
I'm trying to set a new password for a Magento2 admin account, and I'm receiving the following error:

    Please enter 7 or more characters, using both numeric and alphabetic.

Here is the password I'm trying to set:

    mfW;z.pwl{GvBy,&r=g-cGMsE!:g

This is a common password, with punctuality to avoid brute force hacking and etc.

**Comment by mazhalai** [comment]
@markoshust Thank you for reporting this issue. We have created MAGETWO-42031 to track the progress of this request.

**Comment by markoshust** [comment]
:+1:

**Comment by TRMMarketing** [comment]
It appears the password you were setting did not contain any numeric aspects. Should there perhaps be an administrative option to select the types of restrictions allowed for passwords. Eg, Numerica, Alpha, Symbols? From my perspective passwords should require Alpha (both lower and upper) as well as numbers and symbols.

**Comment by markoshust** [comment]
Thank you -- I must have had numbers turned off in my password generator.

This does (& shall) lead to an interesting discussion. I know password length & security are very opinionated in nature, however, the password policies for Magento 2 are saying:
`Abc1234`
is a more secure password than:
`mfW;z.pwl{GvBy,&r=g-cGMsE!:g`

I believe the password guidelines should be updated because the above is just simply not the case. Is there a specific library we can use to add in dictionary checks or things to generally flag the password as too generic/easy to hack? `Abc1234`, `Password1`, `Letme1n`, `1234God`.... these should all be unacceptable passwords because they are common passwords in dictionaries that would be cracked in seconds. The fact that `mfW;z.pwl{GvBy,&r=g-cGMsE!:g` "isn't secure", and the other ones are, should bring to light that the general policies for acceptable passwords need major updates.

**Comment by piotrekkaminski** [comment]
This is something that we will try to address in future releases (unless someone wants to provide a pull request). There should be admin configuration option to enforce given class of password.

**Comment by alankent** [comment]
And it makes sense to allow people to define their own password classes via an extension if they want to.

**Comment by markoshust** [comment]
Yes, that would be great as there could be different security requirements depending on the vendor.

**Comment by steverobbins** [comment]
Or something like (sorry for the M1 comp)...

![image](http://i.imgur.com/Mp7qeH8.png)

You can be as strict or lenient as you want.

**Comment by piotrekkaminski** [comment]
That is very risky - easy for someone to create a too simple policy with just poor regex. I was thinking rather require 2 or 3 out of 4 classes of characters (alpha lowercase, alpha uppercase, numbers, special)

**Comment by TRMMarketing** [comment]
So looking at this from the perspective of a store owner the idea of regex would not be ideal. From my perspective, giving them the following options would do the trick without adding undo compilation: 
1) Password Length field (Minimum 8 characters but can be longer)
2) Automatically require Upper and lower Alpha and Numeric with the option of adding symbols (personally I think symbols should just be required by default)

Ideal options for increasing security, require password changes to administrative accounts after X period of time configurable in admin. Along with this ensure that new password does not match any previously used passwords. This will greatly assist in eliminating the recycling of passwords.

Ideally administrative accounts would have built-in Google Authenticator and the ability for administrators to add a dictionary of forbidden passwords to prevent horrible passwords such as "Password1"

**Comment by markoshust** [comment]
Store owner/implementor should have final discretion over password policies. Forcing users to not reuse passwords, or required a special character, or etc. is a bad policy.

Perhaps having a simple version and more-advanced version (being RegEx). I love the RegEx suggestion as that gives the implementor complete control over what they want to do with their store.

**Comment by sshrewz** [comment]
The fix has been delivered to develop branch.  Feel free to let us know if you encounter any further issues by reopening this or submitting a new issues.
