### ISSUE TITLE
Wrong linefeeds

### ISSUE THREAD

**Issue by amenk** [magento/magento2#1730]
There seem to be some wrong line feeds (I installed via composer)

	warning: CRLF will be replaced by LF in public/app/code/Magento/Catalog/view/adminhtml/web/catalog/category-selector.css.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/Product/Type/_files/product_with_custom_options.csv.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/app/code/Magento/ImportExport/Files/Sample/catalog_product.csv.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/app/code/Magento/Sales/view/adminhtml/layout/sales_order_creditmemo_new.xml.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/app/code/Magento/Ui/view/base/web/js/grid/listing.js.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/app/design/adminhtml/Magento/backend/Magento_Backend/web/css/source/module/_footer.less.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/dev/tests/integration/testsuite/Magento/Indexer/Model/Config/_files/indexer.xml.
	The file will have its original line endings in your working directory.
	warning: LF will be replaced by CRLF in public/dev/tests/static/testsuite/Magento/Test/Php/Exemplar/CodeStyleTest/phpcs/input/general/line_endings_crlf.php.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/magento-composer-installer/res/target.xml.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/magento2-base/dev/tests/integration/testsuite/Magento/Indexer/Model/Config/_files/indexer.xml.
	The file will have its original line endings in your working directory.
	warning: LF will be replaced by CRLF in public/vendor/magento/magento2-base/dev/tests/static/testsuite/Magento/Test/Php/Exemplar/CodeStyleTest/phpcs/input/general/line_endings_crlf.php.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/module-catalog-import-export/Test/Unit/Model/Import/Product/Type/_files/product_with_custom_options.csv.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/module-catalog/view/adminhtml/web/catalog/category-selector.css.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/module-import-export/Files/Sample/catalog_product.csv.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/module-sales/view/adminhtml/layout/sales_order_creditmemo_new.xml.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/module-ui/view/base/web/js/grid/listing.js.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/theme-adminhtml-backend/Magento_Backend/web/css/source/module/_footer.less.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in public/vendor/magento/zendframework1/library/Zend/Queue/Adapter/Db/postgresql.sql.

**Comment by mazhalai** [comment]
@amenk thank you for reporting this issue, but can you please give us more details how to reproduce this issue?

**Comment by amenk** [comment]
I saw it when committing to the Git. It is just about the line endings in those files.

**Comment by piotrekkaminski** [comment]
@amenk is it still an issue? I haven't seen this problem
