### ISSUE TITLE
paypal express checkout not sync with magento 2.2.4

### ISSUE THREAD

**Issue by balwant20** [magento/magento2#17349]
1. When an Order is placed, registered notification about transaction complete on Paypal is not updated automatically in comment history.

2. Whenever we Refund the amount from Paypal, registered notification about refunded amount is not updated automatically in comment history.

3. If the order is in "Payment Review" status at the time order placing, then it should be automatically changed to "Processing" status whenever the funds got cleared from PayPal. Currently this is not syncing automatically from PayPal and we have to click on "Get Payment Update" to check the status.

**Preconditions**
Magento 2.2.4
PHP 7.1.18 
PayPal Express enabled in-checkout payment methods(for sandbox mode)

**Steps to reproduce**
STEP:1 place order on magento store.
STEP:2 Go to https://www.sandbox.paypal.com
STEP:2 open recent order history
STEP:3 issue refund

**Expected result**
paypal transaction status maintain in magento admin order view page in comment history section and also refund comment should be visbile on order view page in comment history section.

**Actual result**
there is no sync between paypal and magento store. any activity which done in paypal panel ,not reflect in magento admin panel.

below the screenshot of  magento 2.1.7 admin order view page when the order is placed from paypal expree checkout .
![screenshot 1](https://user-images.githubusercontent.com/31465231/43644522-b2039faa-974c-11e8-9713-6464a7c22842.png)

**Comment by magento-engcom-team** [comment]
Hi @balwant20. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@balwant20 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @balwant20, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by balwant20** [comment]
hello @engcom-backlog-nickolas ,
thank you for your quick response, i am waiting for the solution of my problem

**Comment by balwant20** [comment]
hello @engcom-backlog-nickolas ,
i got the solution of my problem by changing some settings in my paypal sandbox account.below i mentioned steps.

*Steps to Set-up IPN listener**
	*Step1:* LogIn with paypal business account at https://www.sandbox.paypal.com
				
	*Step2:* In the *Profile menu* on the top right, click *Profile and Settings* .
	
	*Step3:* click *My selling tools* .
	
	*Step4:* Click the Update link in the *Instant payment notifications row*, in the Getting paid and managing my risk section.
			 
	*Step5:* Click Choose IPN Settings to specify your listener's URL and activate the listener.
	
	*Step6:* Specify the URL for your listener in the *Notification URL field* .
			 i.e servername/paypal/ipn/index. 
			 
	*Step7:* Click Receive IPN messages (Enabled) to enable your listener.
	
	*Step8:* Click *Save*.
	
	*Step9:* Click Back to Profile Summary to return to the Profile after activating your listener. You also can click Edit settings to modify your notification URL or disable your listener. You can click Turn Off IPN to reset your IPN preferences.

**Comment by balwant20** [comment]
hello @engcom-backlog-nickolas ,
i got the solution of my problem by changing some settings in my paypal sandbox account.below i mentioned steps.

**Steps to Set-up IPN listener**
	Step1: LogIn with paypal business account at https://www.sandbox.paypal.com 
				
	Step2: In the Profile menu on the top right, click Profile and Settings .
	
	Step3: click My selling tools .
	
	Step4: Click the Update link in the Instant payment notifications row , in the Getting paid and managing my risk section.
			 
	Step5: Click Choose IPN Settings to specify your listener's URL and activate the listener.
	
	Step6: Specify the URL for your listener in the Notification URL field .
			 i.e servername/paypal/ipn/index. 
			 
	Step7: Click Receive IPN messages (Enabled) to enable your listener.
	
	Step8: Click Save .
	
	Step9: Click Back to Profile Summary to return to the Profile after activating your listener. You also can click Edit settings to modify your notification URL or disable your listener. You can click Turn Off IPN to reset your IPN preferences.
