### ISSUE TITLE
Magento 2 - Success / Error message not disappearing(auto hiding)

### ISSUE THREAD

**Issue by Vikram0811** [magento/magento2#17340]
**Preconditions**

- Magento Version - 2.2.2
- PHP Version - 7
- Environment - Magento 2.2.2 with sample data

**Steps to reproduce**

- When a user add a product to cart, 
- When user adds a new address
- When a new user account is created

The success message does not disappear. It stays there until user reload the page. The same issue appears with error messages. Below is extended **messages.js** located at **/app/design/frontend/Namespace/Themename/Magento_Theme/web/js/view/** but it is not working.
```
define([
    'jquery',
    'uiComponent',
    'Magento_Customer/js/customer-data',
    'underscore',
    'jquery/jquery-storageapi'
], function ($, Component, customerData, _) {
    'use strict';

    return Component.extend({
        defaults: {
            cookieMessages: [],
            messages: [],
            isHidden: false,
            selector: '.page.messages .messages',
            listens: {
                isHidden: 'onHiddenChange'
            }
        },

        /**
         * Extends Component object by storage observable messages.
         */
        initialize: function () {
            this._super();

            this.cookieMessages = $.cookieStorage.get('mage-messages');
            this.messages = customerData.get('messages').extend({
                disposableCustomerData: 'messages'
            });

            // Force to clean obsolete messages
            if (!_.isEmpty(this.messages().messages)) {
                customerData.set('messages', {});
            }

            $.cookieStorage.set('mage-messages', '');

        },

        initObservable: function () {
            this._super()
                .observe('isHidden');

            return this;
        },

        isVisible: function () {
            return this.isHidden(!_.isEmpty(this.messages().messages) || !_.isEmpty(this.cookieMessages));
        },

        removeAll: function () {
            //$(self.selector).hide();
            customerData.set('messages', {});
        },

        onHiddenChange: function (isHidden) {
            var self = this;

            // Hide message block if needed
            if (isHidden) {
                setTimeout(function () {
                    //$(self.selector).hide();
                    customerData.set('messages', {});
                }, 5000);
            }
        }
    });
});
```

I even tired this https://github.com/magento/magento2/commit/9515999f75fc728084079b8aae7ccc784cd8c1f3#r21946984 commit but it does not seem to work. How do I achieve below

1. Auto hide success/error message
2. Increase time interval to show success/error message

@magento-engcom-team give me 2.2.2 instance

Thanks

**Comment by magento-engcom-team** [comment]
Hi @Vikram0811. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Vikram0811 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Vikram0811,  thank you for your report.We were not able to reproduce this issue by following the steps you provided.Please provide more detailed steps to reproduce or try to reproduce this issue ona clean installation or latest release.

**Comment by dbsdsun** [comment]
You need to upgrade a javascript library, I remember it is jQuery.

The problem is the javascript to remove cookie failed.

**Comment by Vikram0811** [comment]
@dbsdsun can you let me know which JS to update and where to update?

Thanks

**Comment by Vikram0811** [comment]
Hi @magento-engcom-team 

If you check below URL's it will show the same issue i.e. success/error message not disappearing after certain seconds. Try using invalid credentials or add product to cart, you will encounter the same issue

http://magento2-demo.nexcess.net/customer/account/login/
http://magento2-demo.nexcess.net/radiant-tee.html

The same issue is occurring in our store. Only when you reload the page, the message goes away which is obvious.

Thanks

**Comment by dbsdsun** [comment]
I don't think it will disappear automatically after a few seconds. Where did you see the message disappear automatically?

**Comment by ghost** [comment]
@Vikram0811, hi thanks for you update, but this is not a bug and expected Magento behavior.

**Comment by Eddcapone** [comment]
I have the same issue, but the cookieMessages do not appear even after reloading the site. I am on Enterprise 2.4.1
