### ISSUE TITLE
Adding product configurations uses name based SKU

### ISSUE THREAD

**Issue by syilmaz** [magento/magento2#1736]
When adding new configurations to a configurable product, the simple products contain a SKU that's based on the name, rather than the parent SKU.

See example:
![sku-example](https://cloud.githubusercontent.com/assets/250755/9461789/41263016-4b11-11e5-9f77-22782e21b7a8.jpg)

Not sure if this is intentional, but to me it makes more sense if the SKU of the parent is used as a prefix.

Kind regards,
Samet

**Comment by pronto2000** [comment]
Apparently it's not the only issue -- sub-products are not aware of base currency (€) and use $ instead. Please note that this only happens BEFORE saving the configurable product.

**Comment by syilmaz** [comment]
@pronto2000 Yeah the issues might be the cause of the unfinished work. I couldn't find any issues relating to this so I reported it anyway, just in case it's an oversight.

I've also created a separate issue to track the currency problem, since that seems to happen on more than one place: #1737.

**Comment by tanya-soroka** [comment]
@syilmaz thank you for reporting the issue.
Internal ticket has been created MAGETWO-43791.

**Comment by davidalger** [comment]
Fixed. Please reopen if issue persists.
