### ISSUE TITLE
Adding product configurations shows wrong currency

### ISSUE THREAD

**Issue by syilmaz** [magento/magento2#1737]
When adding new configurations to a configurable product, the simple products show a different currency sign than the parent product.

Note that this issue seems to be visual only.
This issue happens both on the "Create Product Configurations" summary and on the product details page.

Product details page:
![currency-example-1](https://cloud.githubusercontent.com/assets/250755/9462331/55732494-4b15-11e5-80dc-debefef65c2d.jpg)

Create Product Configurations - Summary:
![currency-example-2](https://cloud.githubusercontent.com/assets/250755/9462335/5fe89d0a-4b15-11e5-9728-360b087e5fe0.jpg)

Kind Regards,
Samet

**Comment by kokoc** [comment]
@syilmaz thank you for reporting the issue. Internal reference: MAGETWO-42486

**Comment by davidalger** [comment]
Fixed. Please reopen if issue persists.
