### ISSUE TITLE
Shopping cart rules with multishipping

### ISSUE THREAD

**Issue by ldusan84** [magento/magento2#174]
Currently in Magento if you create a shopping cart rule with condition that is satisfied with your current cart and if you checkout with multishipping with 2 addresses with items on those addresses that do not satisfy the condition separately, the rule is not applied. I think this is a bug since shipping should not affect the rule in my opinion and it should be fixed in Magento 2.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-23682

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Shopping-cart-rules-with-multishipping/idi-p/46283).
