### ISSUE TITLE
 Unknown database 'magento' when try to upgrade DB using bin/magento setup:upgrade command

### ISSUE THREAD

**Issue by DRAJI** [magento/magento2#1740]
I have created one simple (Helloworld module) module, After installed, when i run frontend, I got an error like below

a:4:{i:0;s:273:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Gmi_HelloWorld schema: current version - none, required version - 0.0.1
Gmi_HelloWorld data: current version - none, required version - 0.0.1";i:1;s:1015:"#0 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 /opt/lampp/htdocs/projects/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#2 /opt/lampp/htdocs/projects/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#3 /opt/lampp/htdocs/projects/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /opt/lampp/htdocs/projects/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#5 /opt/lampp/htdocs/projects/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main}";s:3:"url";s:25:"/projects/magento2/admin/";s:11:"script_name";s:28:"/projects/magento2/index.php";}

But when i run "bin/magento setup:upgrade" this command via terminal, got following error in terminal

Cache cleared successfully
File system cleanup:
/opt/lampp/htdocs/projects/magento2/var/generation/Magento
Updating modules:                                                         
  [Zend_Db_Adapter_Exception]                               
  SQLSTATE[42000] [1049] Unknown database 'magento'  
                                                        
  [PDOException]                                            
  SQLSTATE[42000] [1049] Unknown database 'magento'  
                                                            
setup:upgrade [--magento-init-params="..."]
 

I have been using "magento" DB only,

**Comment by mazhalai** [comment]
@DRAJI can you confirm if your MySQL is up and running?

**Comment by DRAJI** [comment]
ya! I'm sure. If i disable my custom module, it's working fine.

**Comment by mazhalai** [comment]
Can you please post the install and upgrade script of your custom module?

**Comment by DRAJI** [comment]
<b>Gmi/Helloworld/etc/module.xml</b>

<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd"> 
    <module name="Gmi_HelloWorld" schema_version="0.0.1" setup_version="0.0.1" /> 
</config>

<b>Gmi/Helloworld/etc/frontend/routes.xml</b>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../lib/internal/Magento/Framework/App/etc/routes.xsd"> 
    <router id="standard"> 
        <route id="helloworld" frontName="helloworld"> 
            <module name="Gmi_HelloWorld" /> 
        </route> 
    </router> 
</config> 

<b>Gmi/HelloWorld/Controller/Index/Index.php</b>

<?php
namespace Gmi\HelloWorld\Controller\Index;

class Index extends \Magento\Framework\App\Action\Action
{
    public function execute()
    {
        return 'welcome';
    }
}
?>

**Comment by mazhalai** [comment]
I checked with these files, and `setup:upgrade` is working fine. I am able to confirm that `Gmi_HelloWorld` is installed. 
```
return array (
  'modules' => 
  array (
    'Gmi_HelloWorld' => 1,
    'Magento_Store' => 1,

````

**Comment by DRAJI** [comment]
But i got "Unknown database" issue when i run setup:upgrade command via terminal. I didn't do any changes..

**Comment by mazhalai** [comment]
Can you clear everything in your `var` directory and try again?

**Comment by DRAJI** [comment]
yeah. After clearing that directory only, My custom module has enabled. But got an error like above..

**Comment by buskamuza** [comment]
Hi @DRAJI ,

I think your module has been enabled from the beginning because your web application was already discovering it and complained about its outdated version.

The question is why your web application can connect to the DB (the connection is required to make comparison between versions and show message "The following modules are outdated...") and your CLI application can't connect to the DB.

1. Could you, please, confirm that you still have same message on the Magento frontend?
2. Could you, please, confirm that you still have same message when run `bin/magento setup:upgrade`?
3. Could you, please, provide contents of your `app/etc/env.php` (feel free to replace all sensitive information)?
4. Could you, please, provide output of `php -i`?

Thanks.

**Comment by mazhalai** [comment]
@DRAJI maybe this is a permission issue. It seems that web server can connect to db, but user executing `setup:upgrade` cannot?  Maybe logged in user does not have permissions to access the database.

**Comment by DRAJI** [comment]
@buskamuza Yes, Still i have met the same issue.

<b> 3. app/etc/env.php</b>

'db' => 
  array (
    'table_prefix' => '',
    'connection' => 
    array (
      'default' => 
      array (
        'host' => 'localhost',
        'dbname' => 'magento',
        'username' => 'root',
        'password' => 'admin123',
        'active' => '1',
      ),
    ),
  ),


4.Output of <b>php -i</b> returns large report. I think, you expect mysql part which i post below. 

mysql

MySQL Support => enabled
Active Persistent Links => 0
Active Links => 0
Client API version => 5.5.44
MYSQL_MODULE_TYPE => external
MYSQL_SOCKET => /var/run/mysqld/mysqld.sock
MYSQL_INCLUDE => -I/usr/include/mysql
MYSQL_LIBS => -L/usr/lib/i386-linux-gnu -lmysqlclient_r 

Directive => Local Value => Master Value
mysql.allow_local_infile => On => On
mysql.allow_persistent => On => On
mysql.connect_timeout => 60 => 60
mysql.default_host => no value => no value
mysql.default_password => no value => no value
mysql.default_port => no value => no value
mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock
mysql.default_user => no value => no value
mysql.max_links => Unlimited => Unlimited
mysql.max_persistent => Unlimited => Unlimited
mysql.trace_mode => Off => Off


If my expect is wrong, please notify me.
Thanks.

**Comment by DRAJI** [comment]
@mazhalai hi, What you mean by logged in user? You mean 'root' user?

Thanks!

**Comment by mazhalai** [comment]
@DRAJI thank you for the details, yes I meant root user. Since your report of php -i is truncated, please verify `pdo_mysql` is enabled. Also, can you check if the php version used by web server is same as cli?

**Comment by buskamuza** [comment]
Thanks, @DRAJI .
The PHP info looks same as mine...
1. Could you, please, look at the MySQL error log? You can find its location in your `my.cnf` as `log_error = ...` or just somewhere here `/var/log/mysql/error.log`.
2. Could you also enable SQL logging in Magento, so we could see on which query it fails? You can enable it in `app/etc/di.xml`. Find the following line:
```
    <preference for="Magento\Framework\DB\LoggerInterface" type="Magento\Framework\DB\Logger\Null"/>
```
and replace it with the next section:
```
    <preference for="Magento\Framework\DB\LoggerInterface" type="Magento\Framework\DB\Logger\File"/>
    <type name="Magento\Framework\DB\Logger\File">
        <arguments>
            <argument name="logAllQueries" xsi:type="boolean">true</argument>
        </arguments>
    </type>
```
Then run the command once again and you should find the log in `<magento root>/var/debug/db.log`. Please, attach whole log or, if it's too big, at least last lines (~20 or so).

**Comment by DRAJI** [comment]
@mazhalai Thanks.

Yes, pdo_mysql is enabled. And also checked both client and server php version are same

**Comment by DRAJI** [comment]
@buskamuza Thanks.

1. I have checked mysql error log file. It seems being empty. There is no error here.
2. After enabling sql logging in magento, I got below error in magento-root/var/log/debug.log file rather than magento-root/var/debug/db.log(debug folder doesn't exist)

[2015-08-27 05:20:48] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
[2015-08-27 11:30:59] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://localhost/projects/magento2/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-27 12:51:19] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://localhost/projects/magento2/customer/account/createpost/","invalidateInfo":{"tags":["wishlist_1","wishlist"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-27 12:51:19] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://localhost/projects/magento2/customer/account/createpost/","invalidateInfo":{"tags":["wishlist_1","wishlist"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-28 07:08:55] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://localhost/projects/magento2/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-28 05:19:56] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
[2015-08-28 05:19:56] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
[2015-08-28 05:20:29] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-28 05:20:31] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
[2015-08-28 05:20:31] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
[2015-08-28 07:22:46] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://localhost/projects/magento2/admin","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-28 07:24:55] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://localhost/projects/magento2/admin","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-28 05:25:02] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []
[2015-08-28 05:25:02] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []

**Comment by mazhalai** [comment]
@DRAJI can you please give us the following details
- what OS and version
- PHP version
- MySQL version (also top 20 lines of mysqldump)
- Magento version

**Comment by DRAJI** [comment]
@mazhalai Ya, Sure.

1. Os version - Ubuntu - 14.10
2. Php Version - 5.6.11
3. Mysql Version - 5.5.44 (sorry, I think- magento 2 support only in mysql 5.6.x version. But I have installed successfully. Can we install magento 2 in this below version?)
4. Magento version - downloaded it from here - https://github.com/magento/magento2/ (1.0.0 beta)
5. Installed via browser (ran composer install)

Thanks!

**Comment by xcomSteveJohnson** [comment]
Magento 2 supports only MySQL 5.6 for the following reasons:

a) Index pushdown, which improves performance: http://dev.mysql.com/doc/refman/5.6/en/index-condition-pushdown-optimization.html
b) Multi-range read: http://dev.mysql.com/doc/refman/5.6/en/mrr-optimization.html
c) File sort optimization: http://dev.mysql.com/doc/refman/5.6/en/limit-optimization.html
d) Subquery optimization: http://dev.mysql.com/doc/refman/5.6/en/subquery-optimization.html
e) And more: http://www.percona.com/blog/2013/01/27/mysql-5-6-improvements-in-the-nutshell/
I do not know exactly how these are used. This is from an internal wiki. Let us know if you have other questions.

**Comment by DRAJI** [comment]
@xcomSteveJohnson Thank you for your knowledge sharing. Let me update mysql version, and will check.

Thanks!

**Comment by piotrekkaminski** [comment]
@DRAJI do you still have this issue?

**Comment by FermionInfo** [comment]
I had created module which was running properly later after some time I deleted that from Neatbeans. Now whenever I creates new module it was throwing same errors as below:

a:4:{i:0;s:273:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Namespace_modulename

But I could resolved it:
-By deleting the previous deleted whole module from server,
-etc/config.xml : removed the line ( 'Namespace_Modulename' => 1,)  for that deleted module
- cleared cache.

and It worked for me...!

**Comment by SailendraShakyaEbp** [comment]
Hi Darji,

Have you got the solution of your above problem? If not I have faced the same issue and figure out the issue. I am posting this, hoping it may help others.

Actually in my case the problem was the php system environment variable was not set.Go to system environment variable add your php location to path, in my case ";D:\xampp\php".

Now run the script given in the error message on your terminal to upgrade your module to database.

Hope, this helps.

**Comment by aton1004** [comment]
Hi Darji,

Have you got the solution of your above problem? If not I have faced the same issue and figure out the issue. I am posting this, hoping it may help others.

Actually in my case the problem was the php system environment variable was not set.Go to system environment variable add your php location to path, in my case ";D:\xampp\php".

Now run the script given in the error message on your terminal to upgrade your module to database.

Hope, this helps.
