### ISSUE TITLE
Bug in date formatting in back-end, Chinese locale

### ISSUE THREAD

**Issue by aricwatson** [magento/magento2#1743]
When the Chinese is selected as the Interface Locale in the backend, dates are incorrectly displayed in grids, for example as "2015yyy-8-17 PM04:56:10".

**Comment by miguelbalparda** [comment]
![index2](https://cloud.githubusercontent.com/assets/3997682/9478323/113f359e-4b45-11e5-8382-57aa71e4151c.png)

**Comment by piotrekkaminski** [comment]
@miguelbalparda @aricwatson what is the correct format?

**Comment by piotrekkaminski** [comment]
internal issue: MAGETWO-43792

**Comment by miguelbalparda** [comment]
Format is ok as it is @piotrekkaminski, the issue here is the extra yyy after the year.

**Comment by NadiyaS** [comment]
hi @miguelbalparda and @aricwatson,
do you still have the same problem on the latest version? or can you provide us more detailed information about reproducing this bug? and what exactly Chinese locale do you use (e.g. zh_Hans_CN)?

**Comment by miguelbalparda** [comment]
We were able to reproduce this in the merchant beta, locale is zh_Hans_CN. You can reproduce this issue by going to http://magento2-demo.nexcess.net/admin - Sales - Orders and selecting Chinese in the footer dropdown.

**Comment by dfediuk** [comment]
Looks like the same as https://github.com/magento/magento2/issues/1926

**Comment by NadiyaS** [comment]
@miguelbalparda ,
nor merchant beta nor latest magento 2 has this problem. Please be sure that you have latest version.

**Comment by dfediuk** [comment]
The bug still is not fixed.

**Comment by dfediuk** [comment]
I have reproduced it now with the foillowing:
- English version of Google Chrome
- Russian locale in Magento backend.
And it leads to the mixed english/russian date formatting: https://github.com/magento/magento2/issues/1926
I am sure that the chinese issue is the same problem.

**Comment by FranRoy** [comment]
I have Spanish locale and I have the same issue. "yyy" is added at the end of the dates in the backend. Magento2 version: 2.0.2
