### ISSUE TITLE
what is the role of $_isGateway in payment ?

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1744]

**Comment by dkvashninbay** [comment]
It's a legacy flag, which is used in invoice creation process https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/view/adminhtml/templates/order/invoice/create/items.phtml#L109 to print information, that invoice can be created offline only, as capture through gateway is not possible due to some determined business case.
Actually this flag  duplicates https://github.com/magento/magento2/blob/develop/app/code/Magento/Payment/Model/Method/AbstractMethod.php#L88
and currently you need to define them both if you have an integration with third-party system.

**Comment by LifeAsBook** [comment]
@dkvashninbay when i change Checkmo.php 
![qq 20150910170808](https://cloud.githubusercontent.com/assets/10986726/9784617/d3d3ce1c-57de-11e5-9b04-864f9b31c7c3.png)
 i use admin to view order is error 
Notice: Undefined index: label in C:\wamp\www\master\app\code\Magento\Backend\Block\Widget\Grid\Column\Filter\Select.php on line 73
#0 C:\wamp\www\master\app\code\Magento\Backend\Block\Widget\Grid\Column\Filter\Select.php(73): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', 'C:\\wamp\\www\\mas...', 73, Array)
#1 C:\wamp\www\master\app\code\Magento\Backend\Block\Widget\Grid\Column.php(488): Magento\Backend\Block\Widget\Grid\Column\Filter\Select->getHtml()
#2 C:\wamp\www\master\app\code\Magento\Backend\view\adminhtml\templates\widget\grid\column_set.phtml(42): Magento\Backend\Block\Widget\Grid\Column->getFilterHtml()
#3 C:\wamp\www\master\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('C:\\wamp\\www\\mas...')
#4 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid\ColumnSet), 'C:/wamp/www/mas...', Array)
#5 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\Template.php(275): Magento\Framework\View\Element\Template->fetchView('C:/wamp/www/mas...')
#6 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Framework\View\Element\Template->_toHtml()
#7 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(521): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(497): Magento\Framework\View\Layout->_renderBlock('sales.transacti...')
#9 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales.transacti...')
#10 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales.transacti...')
#11 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales.transacti...', true)
#12 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(492): Magento\Framework\View\Layout\Interceptor->renderElement('sales.transacti...', true)
#13 C:\wamp\www\master\app\code\Magento\Backend\view\adminhtml\templates\widget\grid.phtml(133): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid.columnSet')
#14 C:\wamp\www\master\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('C:\\wamp\\www\\mas...')
#15 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid), 'C:/wamp/www/mas...', Array)
#16 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\Template.php(275): Magento\Framework\View\Element\Template->fetchView('C:/wamp/www/mas...')
#17 C:\wamp\www\master\app\code\Magento\Backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#18 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Backend\Block\Template->_toHtml()
#19 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(521): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(497): Magento\Framework\View\Layout->_renderBlock('sales.transacti...')
#21 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales.transacti...')
#22 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales.transacti...')
#23 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales.transacti...', false)
#24 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\Text\ListText.php(26): Magento\Framework\View\Layout\Interceptor->renderElement('sales.transacti...', false)
#25 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Framework\View\Element\Text\ListText->_toHtml()
#26 C:\wamp\www\master\app\code\Magento\Backend\Block\Widget\Tabs.php(384): Magento\Framework\View\Element\AbstractBlock->toHtml()
#27 C:\wamp\www\master\app\code\Magento\Backend\view\adminhtml\templates\widget\tabs.phtml(57): Magento\Backend\Block\Widget\Tabs->getTabContent(Object(Magento\Sales\Block\Adminhtml\Order\View\Tab\Transactions))
#28 C:\wamp\www\master\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('C:\\wamp\\www\\mas...')
#29 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\View\Tabs), 'C:/wamp/www/mas...', Array)
#30 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\Template.php(275): Magento\Framework\View\Element\Template->fetchView('C:/wamp/www/mas...')
#31 C:\wamp\www\master\app\code\Magento\Backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#32 C:\wamp\www\master\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Backend\Block\Template->_toHtml()
#33 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(521): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(497): Magento\Framework\View\Layout->_renderBlock('sales_order_tab...')
#35 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales_order_tab...')
#36 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales_order_tab...')
#37 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales_order_tab...', true)
#38 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('sales_order_tab...')
#39 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(499): Magento\Framework\View\Layout->_renderContainer('left')
#40 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('left')
#41 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('left')
#42 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('left', true)
#43 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('left')
#44 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(499): Magento\Framework\View\Layout->_renderContainer('side.col')
#45 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('side.col')
#46 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('side.col')
#47 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('side.col', true)
#48 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('side.col')
#49 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(499): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#50 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#51 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#52 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#53 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#54 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(499): Magento\Framework\View\Layout->_renderContainer('page.content')
#55 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#56 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#57 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#58 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#59 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(499): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#60 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#61 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#62 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#63 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#64 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(499): Magento\Framework\View\Layout->_renderContainer('backend.page')
#65 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#66 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#67 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#68 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(548): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#69 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(499): Magento\Framework\View\Layout->_renderContainer('root')
#70 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#71 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(473): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#72 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#73 C:\wamp\www\master\lib\internal\Magento\Framework\View\Layout.php(917): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#74 C:\wamp\www\master\var\generation\Magento\Framework\View\Layout\Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#75 C:\wamp\www\master\lib\internal\Magento\Framework\View\Result\Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#76 C:\wamp\www\master\lib\internal\Magento\Framework\View\Result\Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#77 C:\wamp\www\master\var\generation\Magento\Backend\Model\View\Result\Page\Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#78 C:\wamp\www\master\lib\internal\Magento\Framework\App\Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#79 C:\wamp\www\master\lib\internal\Magento\Framework\App\Bootstrap.php(257): Magento\Framework\App\Http->launch()
#80 C:\wamp\www\master\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#81 {main}

**Comment by LifeAsBook** [comment]
@dkvashninbay i use paypal payment then i use admin view order is still error?
@alankent

**Comment by dkvashninbay** [comment]
I can't reproduce this issue, also these flags are not something which can cause problems with rendering, especially for Check / Money order

**Comment by LifeAsBook** [comment]
@dkvashninbay  are you change $_isOffline = false

**Comment by dkvashninbay** [comment]
Yes, i've placed order in several combinations of these flags.

**Comment by piotrekkaminski** [comment]
Do you still have this issue @LifeAsBook ?

**Comment by jk100magnys** [comment]
I have the same error when i turned isOffline to false.. So, i think you should to do something with it...
