### ISSUE TITLE
Add new tab to product bundle edit page not working  - tab with knockout component

### ISSUE THREAD

**Issue by MateuszRybak** [magento/magento2#17445]
Hi!

I have a problem with adding new tab to admin product bundle edit page. 

I create a new file with tab in path: MyModule/Testing/Block/Adminhtml/Catalog/Product/Edit/Tab/MyTab

Content this file:
`<?php

namespace TradeGecko\Integration\Block\Adminhtml\Catalog\Product\Edit\Tab;

use Magento\Backend\Block\Template\Context;
use Magento\Framework\Registry;
use Magento\Backend\Block\Widget;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Catalog\Block\Adminhtml\Product\Edit\Tabs;

class TradeGecko extends Widget implements TabInterface
{
    /**
     * Reference to product objects that is being edited
     *
     * @var \Magento\Catalog\Model\Product
     */
    protected $_product = null;

    /**
     * @var \Magento\Framework\DataObject|null
     */
    protected $_config = null;

    /**
     * @var string
     */
    protected $_template = 'product/edit/bundle.phtml';

    /**
     * Accordion block id
     *
     * @var string
     */
    protected $blockId = 'tradegeckoBundle';

    /**
     * Core registry
     *
     * @var Registry
     */
    protected $_coreRegistry = null;

    /**
     * @param Context $context
     * @param Registry $registry
     * @param array $data
     */
    public function __construct(
        Context $context,
        Registry $registry,
        array $data = []
    ) {
        $this->_coreRegistry = $registry;
        parent::__construct($context, $data);
    }

    /**
     * Retrieve product
     *
     * @return \Magento\Catalog\Model\Product
     */
    public function getProduct()
    {
        return $this->_coreRegistry->registry('current_product');
    }

    /**
     * Get tab label
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('TradeGecko Bundle');
    }

    /**
     * Get tab title
     *
     * @return \Magento\Framework\Phrase
     */
    public function getTabTitle()
    {
        return __('TradeGecko Bundle');
    }

    /**
     * @return string
     */
    public function getGroupCode()
    {
        return Tabs::ADVANCED_TAB_GROUP_CODE;
    }

    /**
     * Check if tab can be displayed
     *
     * @return boolean
     */
    public function canShowTab()
    {
        return $this->isBundle();
    }

    /**
     * Retrieve Tab class (for loading)
     *
     * @return string
     */
    public function getTabClass()
    {
        return 'ajax';
    }

    /**
     * Check if tab is hidden
     *
     * @return boolean
     */
    public function isHidden()
    {
        return false;
    }

     /**
     * Get parent tab code
     *
     * @return string
     */
    public function getParentTab()
    {
        return 'product-details';
    }

    protected function isBundle()
    {
        $productType = $this->getProduct()->getTypeId();
        return $productType == \Magento\Catalog\Model\Product\Type::TYPE_BUNDLE;
    }

    /**
     * @return $this
     */
    protected function _prepareLayout()
    {
        if (!$this->isBundle()) {
            return false;
        }
        return parent::_prepareLayout();
    }

}`

Next, create bundle.phtml file in path: MyModule/Testing/view/adminhtml/templates/product/edit/bundle.phtml

Content:
`<div>
    <h1>HELLO</h1>
</div>`

UI component: app/code/MyModule/Testing/view/adminhtml/ui_component/product_form.xml
`<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <htmlContent name="test" sortOrder="1">
        <argument name="data" xsi:type="array">
            <item name="wrapper" xsi:type="array">
                <item name="label" xsi:type="string" translate="true">Test</item>
                <item name="collapsible" xsi:type="boolean">true</item>
                <item name="opened" xsi:type="boolean">false</item>
                <item name="canShow" xsi:type="boolean">true</item>
                <item name="componentType" xsi:type="string">fieldset</item>
            </item>
        </argument>
        <block class="MyModule\Testing\Block\Adminhtml\Catalog\Product\Edit\Tab\TradeGecko" name="test"></block>
    </htmlContent>
</form>
`

Now create knockout component:
app/code/MyModule/Testing/view/adminhtml/web/js/view/testbundle.js
`define(['jquery', 'uiComponent', 'ko'], function ($, Component, ko) {
    'use strict';
        return Component.extend({
            initialize: function () {
                this._super();
            },
            test: function() {
                console.log('test');
            }
        });
    }
);`

app/code/MyModule/Testing/view/adminhtml/web/template/test-component-template.html
`<div data-scope="scope: TradeGecko_Integration_Scope" class="component-wrapper">
    <div>test</div>
    <button type="button" data-bind="click: test()" type="button">Click!</button>
</div>`

If you change the name of the label in the vendor code, e.g. "bundle Items", anything else is not reflected on the bundle editing page.

What am I doing wrong? I am asking for information on how to add a tab that will contain a knockout component. And it will only be displayed on the bundle editing page.

**Comment by magento-engcom-team** [comment]
Hi @MateuszRybak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@MateuszRybak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@MateuszRybak , please refer to the [Community Forums](https://community.magento.com/)or the [Magento Stack Exchange](https://magento.stackexchange.com/) site foradvice or general discussion about this issue. The GitHub issue tracker isintended for Magento Core technical issues only.
