### ISSUE TITLE
sortOrder XML config attribute not working as intended for custom admin form fields appended to vendor provided form fields

### ISSUE THREAD

**Issue by rodioncatargiu** [magento/magento2#17451]
After attempting to add a custom select form element to the 'New Cart Price Rule' page, I noticed that my custom form field always ends up at the top of the fieldset, regardless of which sortOrder value I set up in the configuration XML for this new field. 

I think this problem would present further complications if the desired placement would be in the middle of the form, say between 'Rule Name' and 'Description'.

### Preconditions
Magento version 2.2.5

### Steps to reproduce
1. Attempt to insert a custom field to the 'New/Edit Cart Price Rule' -> 'Rule Information' section form to any location other than the top of the form, while specifying an ordering index via sortOrder values in `sales_rule_form.xml`

The config file of the destination/vendor-provided template: `/vendor/magento/module-sales-rule/view/adminhtml/ui_component/sales_rule_form.xml`

My config file: `/app/code/MyDomain/SalesRule/view/adminhtml/ui_component/sales_rule_form.xml`

Contents of my config file: 
```
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="rule_information">
        <field name="custom_field">
            <argument name="data" xsi:type="array">
                <item name="options" xsi:type="object">MyDomain\SalesRule\Config\Source\Options</item>
                <item name="config" xsi:type="array">
                    <item name="label" xsi:type="string">Custom Field Label</item>
                    <item name="visible" xsi:type="boolean">true</item>
                    <item name="dataType" xsi:type="string">int</item>
                    <item name="formElement" xsi:type="string">select</item>
                    <item name="source" xsi:type="string">sales_rule</item>
                    <item name="dataScope" xsi:type="string">custom_field</item>
                    <item name="default" xsi:type="string">0</item>
                    <item name="validation" xsi:type="array">
                        <item name="required-entry" xsi:type="boolean">false</item>
                    </item>

                    <item name="sortOrder" xsi:type="number">999</item>
                </item>
            </argument>
        </field>
    </fieldset>
</form>
```

I have already attempted specifying sortOrder as part of the `<field>` tag as well, but to no avail.

What did work however, was going back to the vendor provided `sales_rule_form.xml` and adding sortOrder values to each `<field>`, like so: `<field name="name" formElement="input" sortOrder="1">` and so on for the rest of the rule_information `<fieldset>`.

Needless to say, this is not a long-term solution.

### Expected result
1. The newly added custom field should render at the bottom of the rule_information fieldset (considering the rest of the fields do not define their own sortOrder, and merely render in the order they are defined)

### Actual result
1. The newly added custom field renders at the very top of the rule_information fieldset every time, irrespective of sortOrder values

**Comment by magento-engcom-team** [comment]
Hi @rodioncatargiu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@rodioncatargiu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rodioncatargiu** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @rodioncatargiu. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodioncatargiu, here is your [Magento instance](https://i-17451-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17451-2-2-5.engcom.dev.magento.com/admin](https://i-17451-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
