### ISSUE TITLE
magento2 1.0.0-beta admin dashboard not responsive yet

### ISSUE THREAD

**Issue by matinict** [magento/magento2#1745]
All popular ecom CMS admin panel are responsive  but magento why not responsive yet
![magento2admindashboard](https://cloud.githubusercontent.com/assets/4470372/9486009/7376295e-4be3-11e5-8830-d4c1358afe8e.jpg)

**Comment by matinict** [comment]
Even Magento2 admin login screen is not responsive that make funny !!

**Comment by tkacheva** [comment]
@matinict Magento storefront is fully responsive. Magento Admin is touch ready.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
