### ISSUE TITLE
magento 2 customer address Bangladesh State/Province not showing as like as United States.

### ISSUE THREAD

**Issue by matinict** [magento/magento2#1746]
magento 2 customer address Bangladesh State/Province/District not showing as like as United States.

I add Manually on database  as :

For District:
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES
('BD', 'BD-BAG', 'Bagerhat'),
('BD', 'BD-BAN', 'Bandarban'),
('BD', 'BD-BAR', 'Barguna'),
('BD', 'BD-BRI', 'Barisal'),
('BD', 'BD-BHO', 'Bhola'),
('BD', 'BD-BOG', 'Bogra'),
('BD', 'BD-BRA', 'Brahmanbaria'),
('BD', 'BD-CHA', 'Chandpur'),
('BD', 'BD-CHI', 'Chittagong'),
('BD', 'BD-CHU', 'Chuadanga'),
('BD', 'BD-COM', 'Comilla'),
('BD', 'BD-COX', 'Coxs Bazar'),
('BD', 'BD-DHA', 'Dhaka'),
('BD', 'BD-DIN', 'Dinajpur'),
('BD', 'BD-FAR', 'Faridpur'),
('BD', 'BD-FEN', 'Feni'),
('BD', 'BD-GAI', 'Gaibandha'),
('BD', 'BD-GAZ', 'Gazipur'),
('BD', 'BD-GOP', 'Gopalganj'),
('BD', 'BD-HAB', 'Habiganj'),
('BD', 'BD-JAM', 'Jamalpur'),
('BD', 'BD-JES', 'Jessore'),
('BD', 'BD-JHA', 'Jhalokati'),
('BD', 'BD-JHE', 'Jhenaidah'),
('BD', 'BD-JOY', 'Joypurhat'),
('BD', 'BD-KHA', 'Khagrachhari'),
('BD', 'BD-KHU', 'Khulna'),
('BD', 'BD-KIS', 'Kishoreganj'),
('BD', 'BD-KUR', 'Kurigram'),
('BD', 'BD-KUS', 'Kushtia'),
('BD', 'BD-LAK', 'Lakshmipur'),
('BD', 'BD-LAL', 'Lalmonirhat '),
('BD', 'BD-MAD', 'Madaripur'),
('BD', 'BD-MAG', 'Magura'),
('BD', 'BD-MAN', 'Manikganj'),
('BD', 'BD-MEH', 'Meherpur'),
('BD', 'BD-MOU', 'Moulvibazar'),
('BD', 'BD-MUN', 'Munshiganj'),
('BD', 'BD-MYM', 'Mymensingh'),
('BD', 'BD-NAO', 'Naogaon'),
('BD', 'BD-NAR', 'Narail'),
('BD', 'BD-NRG', 'Narayanganj'),
('BD', 'BD-NRS', 'Narsingdi'),
('BD', 'BD-NAT', 'Natore'),
('BD', 'BD-NAW', 'Nawabganj'),
('BD', 'BD-NET', 'Netrakona'),
('BD', 'BD-NIL', 'Nilphamari '),
('BD', 'BD-NOA', 'Noakhali'),
('BD', 'BD-PAB', 'Pabna'),
('BD', 'BD-PAN', 'Panchagarh'),
('BD', 'BD-PAT', 'Patuakhali'),
('BD', 'BD-PIR', 'Pirojpur'),
('BD', 'BD-RAJ', 'Rajbari'),
('BD', 'BD-RJB', 'Rajshahi'),
('BD', 'BD-RAN', 'Rangamati'),
('BD', 'BD-RNP', 'Rangpur'),
('BD', 'BD-SAT', 'Satkhira'),
('BD', 'BD-SHA', 'Shariatpur'),
('BD', 'BD-SHE', 'Sherpur'),
('BD', 'BD-SIR', 'Sirajganj'),
('BD', 'BD-SUN', 'Sunamganj'),
('BD', 'BD-SYL', 'Sylhet'),
('BD', 'BD-TAN', 'Tangail'),
('BD', 'BD-THA', 'Thakurgaon');

INSERT INTO `directory_country_region_name` (`locale` ,`region_id` ,`name` )
SELECT 'en_US', tmp.region_id, tmp.default_name FROM `directory_country_region`
AS tmp WHERE tmp.country_id='BD';

**Comment by piotrekkaminski** [comment]
@matinict feel free to provide  this as a pull request.

**Comment by bojjaiah** [comment]
@matinict, how to extend Customer Address in Adminhtml?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/magento-2-customer-address-Bangladesh-State-Province-not-showing/idi-p/45806).
