### ISSUE TITLE
Not able to set bundle product option title value store wise in magento 2

### ISSUE THREAD

**Issue by bharat-elsner** [magento/magento2#17465]
i have multi store website and i am trying to add bundle product with two option. Option 1 and Option 2. after created this product i switch my store to other store view and change  title Option 1 to Optizon 1 but it is reflecting to all store. i want to change only this particular store view. not for all.

**Preconditions**

Magento 2.2.4
PHP 7.0.3

**Steps to reproduce**

Create multi store.
than add new bundle product with bundle items and save it. after that switch to another store view and change bundle item option title and save it. it will reflect to all store.
i.e i have two store. 'Store en' and 'Store it' (Italian). i have created bundle product and their bundle item option title is 'Option 1' for 'Store en'. now switch to Store it (Italian) and change bundle option "Store View Title" from Option 1 to Opzione 1 and save. 

**Expected result**

Store en' bundle option title = Option 1.
Store it' bundle option title = Opzione 1.
It should change bundle item option title store wise.

**Actual result**

it is reflecting to all store view.
Store en' bundle option title = Opzione 1.
Store it' bundle option title = Opzione 1.

**Comment by magento-engcom-team** [comment]
Hi @Mrjain13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Mrjain13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ghost** [comment]
@Mrjain13, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ktpl-prakash** [comment]
Issue is not available into 2.2-develop and 2.3-develop but for the quick fix in 2.2.4 and 2.2.5 Magento version please find below code.

/vendor/magento/module-bundle/Model/ResourceModel/Option.php

Replace with below function 

```
protected function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {
        parent::_afterSave($object);
        $conditions = [
            'option_id = ?' => $object->getId(),
            'store_id = ?' => $object->getStoreId(),
            'parent_product_id = ?' => $object->getParentId()
        ];
        $connection = $this->getConnection();
        if ($this->isOptionPresent($conditions)) {
            $connection->update(
                $this->getTable('catalog_product_bundle_option_value'),
                [
                    'title' => $object->getTitle()
                ],
                $conditions
            );
        } else {
            $data = new \Magento\Framework\DataObject();
            $data->setOptionId($object->getId())
                ->setStoreId($object->getStoreId())
                ->setParentProductId($object->getParentId())
                ->setTitle($object->getTitle());
            $connection->insert($this->getTable('catalog_product_bundle_option_value'), $data->getData());            
        }
        return $this;
    }
```

**Comment by rajputbbs** [comment]
Above code gives duplicate entry for store id 0
Better to overwrite the Resource Model
i.e 
1. app/code/NameSpace/ExtensionName/etc/adminhtml/di.xml
<pre>
<p>&lt;config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd"&gt;<br />&lt;preference for="Magento\Bundle\Model\ResourceModel\Option" type="NameSpace\ExtensionName\Model\ResourceModel\Option" /&gt;<br />&lt;/config&gt;</p>
</pre>

2. app/code/NameSpace/ExtensionName/Model/ResourceModel/Option.php

<pre>

namespace NameSpace\ExtensionName\Model\ResourceModel;

class Option extends \Magento\Bundle\Model\ResourceModel\Option
{
	
	protected function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {
        $conditions = [
            'option_id = ?' => $object->getId(),
            'store_id = ?' => $object->getStoreId(),
            'parent_product_id = ?' => $object->getParentId()
        ];

        $connection = $this->getConnection();

        if ($this->isOptionPresent($conditions)) {
            $connection->update(
                $this->getTable('catalog_product_bundle_option_value'),
                [
                    'title' => $object->getTitle()
                ],
                $conditions
            );
        } else {
            $data = new \Magento\Framework\DataObject();
            $data->setOptionId($object->getId())
                ->setStoreId($object->getStoreId())
                ->setParentProductId($object->getParentId())
                ->setTitle($object->getTitle());

            $connection->insert($this->getTable('catalog_product_bundle_option_value'), $data->getData());

            /**
             * also saving default value if this store view scope
             */
            if ($object->getStoreId()) {
                $mainConditions = [
                    'option_id = ?' => $object->getId(),
                    'store_id = 0' => $object->getStoreId(),
                    'parent_product_id = ?' => $object->getParentId()
                ];
                if (!$this->isOptionPresent($conditions)) {
                    $data->setStoreId(0);
                    $data->setTitle($object->getDefaultTitle());
                    $connection->insert($this->getTable('catalog_product_bundle_option_value'), $data->getData());
                }
            }
        }

        return $this;
    }

    private function isOptionPresent($conditions)
    {
        $connection = $this->getConnection();

        $select = $connection->select()->from($this->getTable('catalog_product_bundle_option_value'));
        foreach ($conditions as $condition => $conditionValue) {
            $select->where($condition, $conditionValue);
        }
        $select->limit(1);

        $rowSelect = $connection->fetchRow($select);

        return (is_array($rowSelect) && !empty($rowSelect));
    }
}
</pre>

This code may be used

**Comment by geet07** [comment]
I have checked this issue and it has been not reproduce.

**Comment by engcom-Charlie** [comment]
Hello @Mrjain13 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by nkikkertyouwe** [comment]
I was able to reproduce this on a project of ours using the API:

PUT /rest/english/V1/products/BUNDLE-0001

{
    "product": {
        "id": 844874,
        "sku": "WMS-BUNDLE-0001",
        "type_id": "bundle",
        "custom_attributes": [],
        "extension_attributes": {
            "bundle_product_options": [
                {
                    "option_id": 1,
                    "title": "TITLE",
                    "required": true,
                    "type": "size",
                    "position": 1,
                }
            ]
        }
    },
    "saveOptions": true
}

This will update not only the bundle option title for the English store view, but also the default title.

**Comment by nkikkertyouwe** [comment]
@magento give me 2.4-develop instance

**Comment by nkikkertyouwe** [comment]
Thanks, I have been able to reproduce this on the Magento Instance.

I have used the default bundle product "24-WG080", and I have created a new store view called "custom".

When I update the "title" in the "bundle_product_options" to "Sprite Stasis Ball - New Title 3" for only the first option, I see that it updates the "Default Title" for all options (see screenshot).

PUT https://49dafa074e0acbf9482e90168bce5889.instances.magento-community.engineering/rest/custom/V1/products/24-WG080

{
    "product": {
        "id": 52,
        "sku": "24-WG080",
        "name": "Sprite Yoga Companion Kit",
        "attribute_set_id": 11,
        "price": 0,
        "status": 1,
        "visibility": 4,
        "type_id": "bundle",
        "created_at": "2022-05-09 09:37:11",
        "updated_at": "2022-05-09 09:37:11",
        "weight": 0,
        "extension_attributes": {
            "website_ids": [
                1
            ],
            "category_links": [
                {
                    "position": 0,
                    "category_id": "3"
                },
                {
                    "position": 0,
                    "category_id": "5"
                }
            ],
            "bundle_product_options": [
                {
                    "option_id": 1,
                    "title": "Sprite Stasis Ball - New Title 3",
                    "required": true,
                    "type": "radio",
                    "position": 1,
                    "sku": "24-WG080",
                    "product_links": [
                        {
                            "id": "1",
                            "sku": "24-WG081-blue",
                            "option_id": 1,
                            "qty": 1,
                            "position": 1,
                            "is_default": true,
                            "price": 23,
                            "price_type": null,
                            "can_change_quantity": 1
                        },
                        {
                            "id": "2",
                            "sku": "24-WG082-blue",
                            "option_id": 1,
                            "qty": 1,
                            "position": 2,
                            "is_default": false,
                            "price": 27,
                            "price_type": null,
                            "can_change_quantity": 1
                        },
                        {
                            "id": "3",
                            "sku": "24-WG083-blue",
                            "option_id": 1,
                            "qty": 1,
                            "position": 3,
                            "is_default": false,
                            "price": 32,
                            "price_type": null,
                            "can_change_quantity": 1
                        }
                    ]
                },
                {
                    "option_id": 2,
                    "title": "Sprite Foam Yoga Brick 3",
                    "required": true,
                    "type": "radio",
                    "position": 2,
                    "sku": "24-WG080",
                    "product_links": [
                        {
                            "id": "4",
                            "sku": "24-WG084",
                            "option_id": 2,
                            "qty": 1,
                            "position": 1,
                            "is_default": true,
                            "price": 5,
                            "price_type": null,
                            "can_change_quantity": 1
                        }
                    ]
                },
                {
                    "option_id": 3,
                    "title": "Sprite Yoga Strap 3",
                    "required": true,
                    "type": "radio",
                    "position": 3,
                    "sku": "24-WG080",
                    "product_links": [
                        {
                            "id": "5",
                            "sku": "24-WG085",
                            "option_id": 3,
                            "qty": 1,
                            "position": 1,
                            "is_default": true,
                            "price": 14,
                            "price_type": null,
                            "can_change_quantity": 1
                        },
                        {
                            "id": "6",
                            "sku": "24-WG086",
                            "option_id": 3,
                            "qty": 1,
                            "position": 2,
                            "is_default": false,
                            "price": 17,
                            "price_type": null,
                            "can_change_quantity": 1
                        },
                        {
                            "id": "7",
                            "sku": "24-WG087",
                            "option_id": 3,
                            "qty": 1,
                            "position": 3,
                            "is_default": false,
                            "price": 21,
                            "price_type": null,
                            "can_change_quantity": 1
                        }
                    ]
                },
                {
                    "option_id": 4,
                    "title": "Sprite Foam Roller 3",
                    "required": true,
                    "type": "radio",
                    "position": 4,
                    "sku": "24-WG080",
                    "product_links": [
                        {
                            "id": "8",
                            "sku": "24-WG088",
                            "option_id": 4,
                            "qty": 1,
                            "position": 1,
                            "is_default": true,
                            "price": 19,
                            "price_type": null,
                            "can_change_quantity": 1
                        }
                    ]
                }
            ]
        },
        "product_links": [],
        "options": [],
        "media_gallery_entries": [
            {
                "id": 58,
                "media_type": "image",
                "label": "Image",
                "position": 1,
                "disabled": false,
                "types": [
                    "image",
                    "small_image",
                    "thumbnail"
                ],
                "file": "/l/u/luma-yoga-kit-2.jpg"
            }
        ],
        "tier_prices": [],
        "custom_attributes": [
            {
                "attribute_code": "image",
                "value": "/l/u/luma-yoga-kit-2.jpg"
            },
            {
                "attribute_code": "shipment_type",
                "value": "0"
            },
            {
                "attribute_code": "small_image",
                "value": "/l/u/luma-yoga-kit-2.jpg"
            },
            {
                "attribute_code": "thumbnail",
                "value": "/l/u/luma-yoga-kit-2.jpg"
            },
            {
                "attribute_code": "options_container",
                "value": "container2"
            },
            {
                "attribute_code": "msrp_display_actual_price_type",
                "value": "0"
            },
            {
                "attribute_code": "url_key",
                "value": "sprite-yoga-companion-kit"
            },
            {
                "attribute_code": "price_view",
                "value": "0"
            },
            {
                "attribute_code": "required_options",
                "value": "1"
            },
            {
                "attribute_code": "has_options",
                "value": "1"
            },
            {
                "attribute_code": "sku_type",
                "value": "0"
            },
            {
                "attribute_code": "price_type",
                "value": "0"
            },
            {
                "attribute_code": "tax_class_id",
                "value": "2"
            },
            {
                "attribute_code": "weight_type",
                "value": "0"
            },
            {
                "attribute_code": "category_ids",
                "value": [
                    "3",
                    "5"
                ]
            },
            {
                "attribute_code": "description",
                "value": "<p>A well-rounded yoga workout takes more than a mat. The Sprite Yoga Companion Kit helps stock your studio with the basics you need for a full-range workout. The kit is composed of four best-selling Luma Sprite accessories in one easy bundle: statis ball, foam block, yoga strap, and foam roller. Choose sizes and colors and leave the rest to us. The kit includes:</p>\n<ul>\n<li> Sprite Statis Ball\n<li> Sprite Foam Yoga Brick\n<li> Sprite Yoga Strap\n<li> Sprite Foam Roller\n</ul>"
            },
            {
                "attribute_code": "activity",
                "value": "8,11"
            },
            {
                "attribute_code": "gender",
                "value": "80,81,84"
            },
            {
                "attribute_code": "category_gear",
                "value": "87"
            }
        ]
    }
}

![after](https://user-images.githubusercontent.com/105205819/167399022-0f56e370-9a37-4d6d-94ef-d206bc53bc95.png)
