### ISSUE TITLE
Attributes assigned to Product Listings cannot be removed / Product Templates

### ISSUE THREAD

**Issue by wax000** [magento/magento2#1747]
I have added various custom attributes that are required for products, and then also created a product template using these attributes. I have 2 issues as follows:
1. Once you have created a product template, does anyone know how to actually use this template to begin adding products? I cant seem to find anywhere in the Catalog section, how to list products using this template. In the old version of Magento, I recall being able to assign an attribute set to a product, but I cant seem to find a way of doing this in this version.

2. I have tried listing products without using the template, and added the attributes to the Catalog / Add Product area. Once you have added an attribute here, there seems to be no way to remove this for adding products which dont share similar attributes. (I have set the values as not required, so it isnt much of issue, but it just makedsthe whole adding product procedure appear messy)

Anyone else having similar issues?

**Comment by kokoc** [comment]
@wax000 thank you for contacting us. Currently, switcher is located on product creation page. Specifically, above "Product Details" header. The same switcher could be used to solve second question.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
