### ISSUE TITLE
Search appears not to be working

### ISSUE THREAD

**Issue by wax000** [magento/magento2#1748]
I am having an issue with the search feature - it doesnt seem to be pulling products which contain the data searched for - I have flushed the cache, made sure the description etc are searchable, and the product is visible in both catalog and search. I have also checked that quantity is valid, item is in stock etc. 
Anyone else having this issue?

**Comment by wax000** [comment]
Just to provide an update - I think this may be caused by the Index being out of date - but when you go to Index management, there doesnt seem to be a reindex option from the drop down actions box?

**Comment by choukalos** [comment]
That's correct - Magento 2 expects cron to be running frequently.  Please try running cron manually twice and then check search again.

**Comment by alankent** [comment]
You can run cron manually by using `bin/magento cron:run`.

**Comment by piotrekkaminski** [comment]
@wax000 was your issue resolved by running cron?
