### ISSUE TITLE
Multiple issues with taxes

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1752]
We're experiencing multiple issues regarding taxes. We've setup a tax rate (6%) and a tax rule (default tax class with tax rate 6%). All our products are linked to the default tax class.

We add our products including tax, so in the admin the tax option "Catalog Prices" is set to "Including tax". The prices in the admin have the prefix "Inc. Tax", so that's ok.

But on the website the excl tax price is the price we setup in the catalog (that's incl tax), and the calculation of the inc tax price is done over this price. 

Example:
Price in backend: 34,72 (inc tax)
Excl tax on website: 34,72
Inc tax on website: 36,80

Should be:
Price in backend: 34,72
Excl tax on website: 32,75
Inc tax on website: 34,72

Also the prices in the shopping cart are wrong, the same mistakes as in the example.
Is this a bug or a wrong configuration?

**Comment by choukalos** [comment]
Hi @rklerck can you include a screen shot of your tax configuration screen?  Also what's the default address origin for your store's shipping ( i.e. stores/configuration/sales/shipping configuration/origin )?  Is the country/state for that origin tied into your sales rule (i.e. you setup a tax rate for UK that's in your tax rule and your Origin has a UK address ).

**Comment by rklerck** [comment]
I didn't do anything with shipping configuration.

Here's the configuration:

![magento_tax_1](https://cloud.githubusercontent.com/assets/2596896/9523578/fb7bc80c-4cda-11e5-8377-4e05a8f5b160.PNG)
![magento_tax_2](https://cloud.githubusercontent.com/assets/2596896/9523582/fe317dda-4cda-11e5-9ecf-a1636d4df92e.PNG)
![magento_tax_3](https://cloud.githubusercontent.com/assets/2596896/9523589/00796012-4cdb-11e5-8318-866b44f3b4e7.PNG)
![magento_tax_4](https://cloud.githubusercontent.com/assets/2596896/9523593/0207dae4-4cdb-11e5-9e47-f0f68440ca0b.PNG)

**Comment by tang-yu** [comment]
@rklerck , when catalog price includes tax, the included tax is based on store shipping origin. If you have not set store shipping origin, the store tax rate would be 0, which would explain why price excluding tax is 34.72.  The price including tax displayed on frontend is calculated based on customer's tax rate, which is 6%. 

If you set store shipping origin address to Netherlands, you should see the expected bahavior.

**Comment by rklerck** [comment]
Yep, it works, thanks!
