### ISSUE TITLE
How to Update to Latest version to fix known bugs?

### ISSUE THREAD

**Issue by wax000** [magento/magento2#1753]
Hi Everyone - I was wondering if anyone could outline the procedure for updating Magento to the latest beta version (or to incorporate the bug fixed which have been applied so far). I can see that many changes have been made since I installed the version I am running, and I was wondering what the procedure was to update so as not to lose any of the data in the catalog and database.
Thanks!

**Comment by mazhalai** [comment]
@wax000 thank you for your question, if you used `git clone` to create your instance, just `git pull` and run `bin/magento setup:upgrade`

**Comment by xcomSteveJohnson** [comment]
See also: http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall.html#instgde-install-magento-update

**Comment by danielc1234** [comment]
It always seems this breaks the site. I followed the instructions on the link above and killed the whole site.
Now getting this error...

a:4:{i:0;s:62:"Setup version for module 'Magento_SampleData' is not specified";i:1;s:2227:"#0 /Projects/magento2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(56): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Magento_SampleD...', '2.0.0')

But I had the sample data in place. 
What would I do if I just wanted to start from scratch and have the develop branch with the sample data and the means to git pull all the updates to keep everything in the latest releases? I want to stay current with all the changes, etc.

**Comment by xcomSteveJohnson** [comment]
Currently, sample data works with the master branch only. We're still waiting on a fix for that.

**Comment by daim2k5** [comment]
Fixed.
