### ISSUE TITLE
why i disable all  caches and enable xdebug  that  cause   magento very slow?

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1755]

**Comment by ooxi** [comment]
That's like asking why your car is slow if you remove all tires but add a heavily loaded trailer ;)

**Comment by dfediuk** [comment]
XDebug slows PHP down in several (3-5-10, depends on a particular code) times, it is normal.

**Comment by LifeAsBook** [comment]
@dfediuk Can you tell me a way to do efficient develop and to see the effect so as not to clear the cache every time

**Comment by buskamuza** [comment]
@LifeAsBook , it depends on your developer flow. Could you, please, clarify what exactly you're modifying, so you need to cleanup cache all the time? Maybe you can disable just some specific parts of cache and still get benefits of other caches. What kind of files you often modify and need to refresh cache after it?

**Comment by LifeAsBook** [comment]
@buskamuza  thank you, you are beautiful! I do Implementing payment gateway in Magento 2 , what can i disable some specific parts?

**Comment by buskamuza** [comment]
@LifeAsBook , sorry for the delay.
So, if you're developing a payment gateway, I would assume that you may go through different stages of the development, where different files are changed.
1. You may change configuration files. In this case, I'd recommend to refresh "Configuration" cache type, when you want to see your changes. You may also disable this cache, but it may slow-down the application significantly, so it's better to just refresh the cache after the changes.
2. When you work with layouts or templates, you may want to disable "Layouts" and "Blocks HTML output" cache types, as well as "Page Cache" type. When you're done, enable it back.
3. When you work with the classes, you may keep all the cache types enabled, but you need to clean-up `var/di` and `var/generation`, if you change public interface of the classes or DI configuration (deeper understanding of how DI works in Magento may help to understand when you really need to clean it up and when not).
4. If you work with JS, CSS, LESS files, you may also want to disable or refresh "View files fallback" and "View files pre-processing" cache types in case you add or remove these files. In case you modify LESS files, you may want to cleanup `pub/static` folder or switch to `developer` mode of the application (both ways lead to significant slow-down of the application). You may also use `bin/magento dev:css:deploy` CLI command to process specific LESS files (see the command's help for more information).

**Comment by LifeAsBook** [comment]
@buskamuza  thank you very much!i want you to be a  friend

**Comment by magento-engcom-team** [comment]
Hi @LifeAsBook. Thank you for your report. 
The issue has been fixed in magento/magento2#29429 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [4ebe9d6397312bda6da09654c5fac51391844757](https://github.com/magento/magento2/commit/4ebe9d6397312bda6da09654c5fac51391844757)

The fix will be available with the upcoming 2.4.1 release.
