### ISSUE TITLE
2.2.5: Admin page stuck in 301/302 redirect loop when HTTPS is enabled, using SSL certificate from Comodo

### ISSUE THREAD

**Issue by muckee** [magento/magento2#17556]
### Preconditions
1. Ubuntu 18.04 DigitalOcean droplet
2. Nginx 1.1.4
3. MariaDB 10.1.34 (MySQL 15.1)
4. PHP 7.1 (Using FPM)
5. Redis server 4.0.11

### Steps to reproduce
1. Download Magento 2.2.5 via Composer
2. Install Magento 2.2.5 via CLI using existing database
3. Install SSL certificate.
4. (At this point the website is functioning properly).
5. Enable https on magento frontend and admin.
6. Execute `setup:upgrade`,`setup:di:compile`,`indexer:reindex`,`cache:flush` and `setup:static-content:deploy` in that order.

### Expected result
1. Frontend is displayed without any security warnings.
2. Admin is displayed without any security warnings.

### Actual result
1. Frontend is displayed without any security warnings.
2. Admin is stuck in 301/302 redirect loop
3. I can see in the headers that the SSL certificate is recognised as valid.

### Notes
I have this problem running 2.2.5 with nginx and redis, no varnish, all on a single digitalocean droplet.

I have read that it can be to do with cookie configuration and set `cookie_path` to "/" and `cookie_domain` to both ".example.com" and "example.com", neither of which have produced successful results. I have made changes to the default nginx config provided by magento as suggested above but that wasn't successful either. The nginx config file for my website is as follows:

```
upstream fastcgi_backend {
         server  unix:/run/php/php7.1-fpm.sock;
}

server {
        listen 80 default_server;
        listen [::]:80 default_server;
        index  index.php index.html index.htm;
        server_name  example.com www.example.com;

        set $MAGE_ROOT /[web_root]/magento;
        set $MAGE_MODE production;

        access_log [path_to_access].log;
        error_log [path_to_error].log;

        include /[web_root]/magento/nginx.conf.sample;

        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl;
        index  index.php index.html index.htm;
        server_name example.com www.example.com

        ssl_certificate /path/to/ssl.crt;
        ssl_certificate_key /path/to/ssl.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers [ssl_cipher];
        ssl_session_cache    shared:SSL:10m;
        ssl_session_timeout 24h;
        keepalive_timeout 300s;

        set $MAGE_ROOT /[web_root]/magento;
        set $MAGE_MODE production;

        access_log /path/to/access.log;
        error_log /path/to/error.log;

        include /[web_root]/magento/nginx.conf.sample;
}
```

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JoshuaFlood do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by muckee** [comment]
Sorry but I can't reproduce the issue as I don't know how you configure your servers and would not be able to re-configure them if I did. I believe it is mentioned at #9424

Also here #10113

But based on their comments, my experience and the age of the post I won't hold out much hope. Perhaps it is best to close this issue and I'll continue stabbing blindly in the dark.

**Comment by JoshuaFlood** [comment]
Also here #10113

But based on their comments, my experience and the age of the post I won't hold out much hope. Perhaps it is best to close this issue and I'll continue stabbing blindly in the dark.

**Comment by JoshuaFlood** [comment]
Or, maybe, you could provide an proper explanation of how you create all these vanilla instances for testing, in order that people can replicate them and won't face such tremendous disappointment when attempting to manouver your current docs and build on systems which magento is clearly not fit for.

**Comment by ihor-sviziev** [comment]
Hi @JoshuaFlood.
Looks like you implemented 301 redirect by nginx conf, but didn't updated Base URLs for Admin and frontend. As result - Magento tries to redirect to http protocol, and nginx - to https.

Try to remove following line in nginx.conf: 
```
return 301 https://$server_name$request_uri;
```
 and go to admin, change secure URLs to https protocol both for frontend and admin.
Tip 1: 301 redirects cached in browser, so try to re-check it in incognito mode

**Comment by muckee** [comment]
@ihor-sviziev 
Nope. Still the same problem.
Deleted that line in my nginx config.
Set URLs to https on both secure and unsecure (which I don't want to do, because magento should be able to handle its own default configuration).
Cleared caches of all browsers and executed CCleaner to be safe.
Tested on both firefox and chrome, incognito mode with code inspector open and disable caching set to true.
Still getting a redirect error.

**Comment by muckee** [comment]
I mean, I already configured magento itself to redirect to HTTPS before you said that... and I can tell from the frontend that the logic I applied to the configuration makes sense, but magento is doing something with it that does not make sense, else I should see the same result on the frontend as the admin panel.

**Comment by muckee** [comment]
For future reference, I have added this issue as a [question on stackexchange](https://magento.stackexchange.com/questions/238105/magento-2-2-5-admin-login-page-redirect-loop-301-302-after-installing-ssl-and-e).

**Comment by muckee** [comment]
@ihor-sviziev why is it a 'non-issue'? Surely the fact that the standard configuration does not work means that it is more of an issue?

**Comment by JoshuaFlood** [comment]
Do you know the reason that frontend and admin pages behave differently? They are served from the same location so I don't see why one would loop and the other wouldn't. Perhaps if you could point me in the right direction, i.e. explain what you understand about the problem I'm having, then I can work out more specifically what I am actually having problems with, then we can troubleshoot more effectively.

The way that magento devs operate is weird and exclusive. I don't get why exclusivity is prioritized before efficiency.

**Comment by muckee** [comment]
@ihor-sviziev do you have some prior understanding of this issue? Do you know if there is any change that can be made to the nginx sample config?

This problem didn't occur until I actually installed an SSL certificate. I've also noticed that removing the 301 redirect seems to make the connection more volatile. Firefox seems to reload the page intermittently and redirect another 20 or so times if I even click on the page in the network tab of code inspector on firefox... and on google it just loops forever, whereas the loop cuts out and the error is reported properly if I include the redirect in my nginx config... which makes me think that it is not the redirect which is the problem (that error is being caught and handled properly, the error in magento configuration is not).

**Comment by muckee** [comment]
I've just noticed that http simply isn't redirecting to https. When I type either url into the address bar I still get the redirect loop. I've just checked all the settings in core_config_data and they are correct. I executed all the commands to re-deploy magento again and rebooted my server, just to be sure. Cleared all the browser caches again, ran in incognito mode with caching disabled and still get the redirect error on chrome and firefox. But, as I said, the http address just redirects to an http address, so surely there is something wrong with the way magento is handling redirects.

**Comment by muckee** [comment]
@ihor-sviziev 

I have just got it working, but there's a problem.

I looked at app/etc/env.php and noticed that, alongside the usual base, media, static etc. entries that are found within the system>web>... entry in env.php, there was another entry at the bottom of the file with just the base urls, both set to http.

Although they are duplicate entries, I didn't want to delete them because I'm not sure why magento has created them (I've never manually edited the env.php file for this instance). Instead, I just updated every value which began "http://" with "https://...".

Now I can access the admin panel, but the configuration options for secure URLs in `Stores>Configuration>General>Web>Url Options` are greyed out and the frontpage no longer redirects to https, though there is no mention of http anywhere in the config file.

I guess that it is greyed out because I'm running in production mode, but I want to make as few changes as possible to the system because it's so close to functioning.

**Comment by muckee** [comment]
Ok I just inserted the line `return 301 https://$server_name$request_uri;` back into my nginx config for port 80 and everything is working as it should. Accessing 'http://www.example.com/' redirects to 'https://www.example.com/' and 'http://www.example.com/admin/' redirects to https://www.example.com/admin' without any loops. There is obviously still an issue with the magento software, but my own problem is fixed.

**Comment by ihor-sviziev** [comment]
@JoshuaFlood I see that it was your configuration issue. Wasn't it?

**Comment by muckee** [comment]
No. I replaced the configuration with the one I originally posted, then followed all of the other steps that you suggested.. so I only actually altered the magento configuration.

The problem here, though, is that magento should redirect to 'https' without a 301 redirect written in the nginx configuration, as you said... particularly when no 'http' record exists in the magento configuration.

To re-iterate:

Assume that I have made the changes you suggested and removed the 301 redirect from the nginx configuration.
The secure and unsecure base URLs are both defined as 'https://www.example.com/'.
Although it should not matter, I have tried the configuration with 'use secure in frontend/admin' options both enabled and disabled.
Regardless of which setting I choose, when I type 'http://example.com/' directly into the address bar, I receive the 'http' site, not the 'https' site, as expected. (Here is where the problem is with the Magento software)

The solution:
I must replace the original 301 redirect in my nginx config.
This means that I have made no alterations to the nginx config that I posted here originally, only to magento... and your advice (which I assume is the proper solution) did not work... so there is a problem with the magento software and not my nginx config.

**Comment by muckee** [comment]
Or, rather, there is a problem with magento which can only be fixed by applying an improper configuration to nginx.

**Comment by ghost** [comment]
Hi @JoshuaFlood I'm not able to reproduce by following steps your described, but i'm believe that it's because i'm not have in file app/etc/env.php settings that you are described on comment, can you please show yours env.php ?

**Comment by ghost** [comment]
Hi @JoshuaFlood , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by vtransy** [comment]
please set: web/secure/use_in_frontend  and web/secure/use_in_adminhtml to 0

Please read here for more detail:
https://mrvts.wordpress.com/2018/12/17/magento-2-nginx-varnish-full-page-cache-backend-admin-redirect-loop-why-and-how-to-fix/

**Comment by ihor-sviziev** [comment]
Hi @vtransy,
In such configuration both variables web/secure/use_in_frontend and web/secure/use_in_adminhtml should be set to 1. 
You need to check if your nginx proxy sets X-Forwarded-Proto header. For https requests value for this header should be "https".

You can see how to setup it correctly here: https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination

**Comment by Sarke** [comment]
I'm using Traefik with Let's Encrypt and Docker running Magento on port 80.  Adding `X-Forwarded-Proto = 'https'` worked for me too.
