### ISSUE TITLE
Error While Installing sample data Using magento console

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#1757]
Fatal error: Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection() in app\code\Magento\SampleData\Module\Catalog\Setup\Product\Gallery.php on line 144

I get the following error while trying to install The sample data.

The full stack trace is as following

Call Stack:
    0.0010     233624   1. {main}() E:\wamp\www\magento2\bin\magento:0
    9.7730   58621760   2. Symfony\Component\Console\Application->run()E:\wamp\www\magento2\bin\magento:25
    9.7780   58668888   3. Symfony\Component\Console\Application->doRun() E:\wam
p\www\magento2\vendor\symfony\console\Symfony\Component\Console\Application.php:
126
    9.7790   58669760   4. Symfony\Component\Console\Application->doRunCommand()
 E:\wamp\www\magento2\vendor\symfony\console\Symfony\Component\Console\Applicati
on.php:195
    9.7790   58670184   5. Symfony\Component\Console\Command\Command->run() E:\w
amp\www\magento2\vendor\symfony\console\Symfony\Component\Console\Application.ph
p:874
    9.7800   58673536   6. Magento\SampleData\Console\Command\SampleDataInstallC
ommand->execute() E:\wamp\www\magento2\vendor\symfony\console\Symfony\Component\
Console\Command\Command.php:257
    9.7840   58702968   7. Magento\Setup\Model\SampleData->install() E:\wamp\www
\magento2\app\code\Magento\SampleData\Console\Command\SampleDataInstallCommand.p
hp:102
   12.4540   67001704   8. Magento\SampleData\Model\Installer->run() E:\wamp\www
\magento2\setup\src\Magento\Setup\Model\SampleData.php:122
   43.2730  107763760   9. Magento\SampleData\Module\Catalog\Setup->run() E:\wam
p\www\magento2\app\code\Magento\SampleData\Model\Installer.php:104
   72.8960  112579704  10. Magento\SampleData\Module\Catalog\Setup\Product->run(
) E:\wamp\www\magento2\app\code\Magento\SampleData\Module\Catalog\Setup.php:78
   75.9280  122310032  11. Magento\SampleData\Module\Catalog\Setup\Product\Galle
ry->install() E:\wamp\www\magento2\app\code\Magento\SampleData\Module\Catalog\Se
tup\Product.php:149
   75.9280  122310480  12. Magento\SampleData\Module\Catalog\Setup\Product\Galle
ry->storeImage() E:\wamp\www\magento2\app\code\Magento\SampleData\Module\Catalog
\Setup\Product\Gallery.php:95

**Comment by kandy** [comment]
Sample Data package is not comparable with developer version of Magento (developer branch). Please use master branch to install sample data and than update to developer branch if you need latest version.
