### ISSUE TITLE
1 exception(s): Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlTag': [facet 'enumeration'] The value '' is not an element of the set {'aside', 'dd', 'div', 'dl', 'fieldset', 'main', 'nav', 'header', 'footer', 'ol', 'p', 'section', 'table', 'tfoot', 'ul'}. Line: 1306

### ISSUE THREAD

**Issue by hapdes** [magento/magento2#17570]
### Preconditions
1. PHP 7.1
2. mysql 5.6.40
3. CENTOS 7.5 standard 

### Steps to reproduce
Upgrade magento 2.1 to 2.2.5
goto product page 

### Expected result
1. No errors!

### Actual result
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlTag': [facet 'enumeration'] The value '' is not an element of the set {'aside', 'dd', 'div', 'dl', 'fieldset', 'main', 'nav', 'header', 'footer', 'ol', 'p', 'section', 'table', 'tfoot', 'ul'}.
Line: 1306

Element 'referenceContainer', attribute 'htmlTag': '' is not a valid value of the atomic type 'htmlTagType'.
Line: 1306

Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 1306

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 1306

Element 'referenceContainer', attribute 'before': The attribute 'before' is not allowed.
Line: 1306

Element 'referenceContainer', attribute 'htmlTag': [facet 'enumeration'] The value '' is not an element of the set {'aside', 'dd', 'div', 'dl', 'fieldset', 'main', 'nav', 'header', 'footer', 'ol', 'p', 'section', 'table', 'tfoot', 'ul'}.
Line: 1307

Element 'referenceContainer', attribute 'htmlTag': '' is not a valid value of the atomic type 'htmlTagType'.
Line: 1307

Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 1307

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 1307

Element 'referenceContainer', attribute 'after': The attribute 'after' is not allowed.
Line: 1307

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlTag': [facet 'enumeration'] The value '' is not an element of the set {'aside', 'dd', 'div', 'dl', 'fieldset', 'main', 'nav', 'header', 'footer', 'ol', 'p', 'section', 'table', 'tfoot', 'ul'}.
Line: 1306

Element 'referenceContainer', attribute 'htmlTag': '' is not a valid value of the atomic type 'htmlTagType'.
Line: 1306

Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 1306

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 1306

Element 'referenceContainer', attribute 'before': The attribute 'before' is not allowed.
Line: 1306

Element 'referenceContainer', attribute 'htmlTag': [facet 'enumeration'] The value '' is not an element of the set {'aside', 'dd', 'div', 'dl', 'fieldset', 'main', 'nav', 'header', 'footer', 'ol', 'p', 'section', 'table', 'tfoot', 'ul'}.
Line: 1307

Element 'referenceContainer', attribute 'htmlTag': '' is not a valid value of the atomic type 'htmlTagType'.
Line: 1307

Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 1307

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 1307

Element 'referenceContainer', attribute 'after': The attribute 'after' is not allowed.
Line: 1307

#0 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/home/km2ca05/p...', '%message%\nLine:...')
#2 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#4 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/View/Model/Layout/Update/Validator.php(141): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<body>\n   <refe...')
#8 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php(193): Magento\Framework\View\Model\Layout\Merge->load(Array)
#9 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge\Interceptor->load()
#10 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#11 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#12 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/View/Layout.php(876): Magento\Framework\View\Layout->build()
#13 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#14 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/module-cms/Helper/Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#15 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/module-cms/Controller/Noroute/Index.php(44): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Noroute\Index\Interceptor), 'no-route')
#16 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php(24): Magento\Cms\Controller\Noroute\Index->execute()
#17 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/App/Action/Action.php(107): Magento\Cms\Controller\Noroute\Index\Interceptor->execute()
#18 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Noroute\Index\Interceptor->___callParent('dispatch', Array)
#20 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Noroute\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php(39): Magento\Cms\Controller\Noroute\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Noroute\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/km2ca05/public_html/firearmsoutlet/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(135): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#33 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#35 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#36 /home/km2ca05/public_html/firearmsoutlet/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#37 {main}

**Comment by magento-engcom-team** [comment]
Hi @hapdes. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@hapdes do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@hapdes, thank you for your report.
Seems like your problem is caused by custom module or theme. Please reopen the issue if it is reproducible on clean Magento 2 installation.

**Comment by hapdes** [comment]
@engcom-backlog-pb 
all custom modules are disabled now getting below Exception

1 exception(s):
Exception #0 (LogicException): Front controller reached 100 router match iterations

Exception #0 (LogicException): Front controller reached 100 router match iterations
#0 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#1 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#2 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#3 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#5 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#6 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#8 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /home/km2ca05/public_html/firearmsoutlet/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#10 /home/km2ca05/public_html/firearmsoutlet/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#11 /home/km2ca05/public_html/firearmsoutlet/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#12 {main}

**Comment by ghost** [comment]
@hapdes, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
