### ISSUE TITLE
Error on  Multi-store checkout success page

### ISSUE THREAD

**Issue by rqsakai** [magento/magento2#17580]
### Preconditions
1. Magento 2.2.5
2. Multistore (more than 2 stores in the same website)

### Steps to reproduce
1. Make an order on store A with user A
2. Make an order on store B with user B
3. Make an order on Store C with user C
*Make sure carts are different products  (to make easier to see the error)

### Expected result
In this case, you should see you order information on your custom success.phtml.

### Actual result
But after the second or third time that you place an order, you will see that the order  details are not from that order

### Root cause
We've noticed that since we upgraded to 2.2.5  (from 2.2.3), Magento Commerce (not sure about community) uses a different sales sequence for each store view.

Thus the 100000001 order can exist any (amount of store views) times.

And on block \Magento\Checkout\Block\Onepage\Success on line 82 you have:
```
$order = $this->_checkoutSession->getLastRealOrder();
```

Followign to \Magento\Checkout\Model\Session it load by increment id regardless the store:
```
  public function getLastRealOrder()
    {
        $orderId = $this->getLastRealOrderId();
        if ($this->_order !== null && $orderId == $this->_order->getIncrementId()) {
            return $this->_order;
        }
        $this->_order = $this->_orderFactory->create();
        if ($orderId) {
            $this->_order->loadByIncrementId($orderId);
        }
        return $this->_order;
    }
```

We've fixed using a custom block that extends magento default block, in this block we load as the following:
```
$order = $this->orderModel->load($this->_checkoutSession->getLastOrderId());
```

Hope this helps someone and Magento Team to investigate this.

Kind regards

**Comment by magento-engcom-team** [comment]
Hi @rqsakai. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@rqsakai do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @rqsakai, thank you for your report. I'm not able to reproduce this issue. Could you please add more details to steps to reproduce?

**Comment by rqsakai** [comment]
Ok so here it goes:

Create 2 websites with 4 stores in each one of them.

Your website needs to have a custom success page using the order id (provided by the default Magento block) and load the allVisibleItems for that order to show the customer.

Important information: Since upgrade 2.2.5 Magento creates a different sales_sequence for each store view.

Make different orders with different customers in all store views.

Once you do the 4th > order in the same website but in different store views, you'll be able to see that the order shown, is a previous order due to the increment id.

So for ex: on you 4th order you will see increment id 1000000001 but it will retrieve the order information from the same increment id in another store view.

Kind regards,

**Comment by engcom-backlog-nickolas** [comment]
![peek 2018-08-15 18-53](https://user-images.githubusercontent.com/40755810/44158313-0ea8b280-a0bd-11e8-99ba-eb8e68eb21b7.gif)
@rqsakai, could you please correct my steps?

**Comment by rqsakai** [comment]
In your case, it didn't happen because your stores have different increment id prefixes.

In my vanilla installation and in my customer installation when I create store views they have the same prefixes.

Kind regards,

**Comment by engcom-backlog-nickolas** [comment]
@rqsakai, different increment id prefixes for different store views it's default vanilla magento behaviour.
https://github.com/magento/magento2/blob/50f974b0c8f3ada8d7a2c9b0f9924976dacd2088/app/code/Magento/Quote/Model/QuoteManagement.php#L458
https://github.com/magento/magento2/blob/50f974b0c8f3ada8d7a2c9b0f9924976dacd2088/app/code/Magento/Quote/Model/ResourceModel/Quote.php#L166-L172

If you'd like to update this issue, please reopen it.

**Comment by rqsakai** [comment]
I found out the problem, apparently when you have more than 10 stores, then 10th and forward the prefix was caped on the first number.

So
prefix 10 = prefix 1
prefix 30 = prefix 3

**Comment by engcom-backlog-nickolas** [comment]
@rqsakai, thanks for feedback. I've tried to generate 20 store views. But, still there is a difference between order increment ids for store view with id = 2 and store view with id = 20. Therefore I wasn't able to reproduce this issue. Result is the same as on video I've posted before.

**Comment by rqsakai** [comment]
Found the issue, this was due to a legacy modification to keep the increment id at 9 chars.
