### ISSUE TITLE
Widget.xml <depends> on parameter "template" throws error in adminhtml_widget_instance_edit

### ISSUE THREAD

**Issue by noahm96** [magento/magento2#17595]
If a widget defined in widget.xml has a "template" parameter and another parameter that <depends> on template having a certain value, the widget instance edit area of the admin will throw an error. This error does not occur when adding widgets via the WYSIWYG editor, and behaves as one would expect, where if the template parameter is set to the <depends> value, the dependent parameter will show and if not it will hide.

### Preconditions
- Magento 2.2.4
- PHP 7.0.27
- MySQL 5.7

### Steps to reproduce
1. Create a simple widget like so within a module's widget.xml:
```PHP
<widget id="bug_demo" class="Vendor\Module\Block\Widget\Demo">
		<label translate="true">!Bug Demo</label>
<description translate="true">Test.</description>
<parameters>
		<parameter name="template" xsi:type="select" required="true" visible="true">
			<label translate="true">Template</label>
		
			<options>
					<option name="1" value="widget/1.phtml" selected="true">
							<label translate="true">1</label>
					</option>
					<option name="2" value="widget/2.phtml">
							<label translate="true">2</label>
					</option>
					<option name="3" value="widget/3.phtml">
							<label translate="true">3</label>
					</option>
			</options>
		</parameter>
		<parameter name="dependent_on_template" xsi:type="select" source_model="Magento\Config\Model\Config\Source\Yesno">
			<label translate="true">Dependent</label>
			<depends>
				<parameter name="template" value="widget/1.phtml" />
			</depends>
		</parameter>
</parameters>
	</widget>
```
2. In admin, go to Content > Elements > Widgets  and Add a new Widget
3. In the New page, choose the !Bug Demo widget and theme and click continue.

### Expected result
Expected that no error would occur and the Template parameter is omitted from the Widget Options, but the dependent parameter still respects the Template set in the Storefront Properties > Layout Updates tab, or hidden if no template set.
This behaviour would be similar to how the widget's dependent parameter would behave if added via a WYSIWYG editor:
![image](https://user-images.githubusercontent.com/42378486/44093240-e13a8b68-9fca-11e8-97ba-b5d52f41a388.png)
![image](https://user-images.githubusercontent.com/42378486/44093264-efa43abe-9fca-11e8-9d47-f85b2cbb629d.png)

### Actual result
Instead, an error is thrown with this being the stack trace:

```
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: template in /home/noahm96/project/vendor/magento/module-backend/Block/Widget/Form/Element/Dependence.php on line 147

Exception #0 (Exception): Notice: Undefined index: template in /home/noahm96/project/vendor/magento/module-backend/Block/Widget/Form/Element/Dependence.php on line 147
#0 /home/noahm96/project/vendor/magento/module-backend/Block/Widget/Form/Element/Dependence.php(147): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/noahm96/pro...', 147, Array)
#1 /home/noahm96/project/vendor/magento/module-backend/Block/Widget/Form/Element/Dependence.php(130): Magento\Backend\Block\Widget\Form\Element\Dependence->_getDependsJson()
#2 /home/noahm96/project/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Widget\Form\Element\Dependence->_toHtml()
#3 /home/noahm96/project/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
.....
```

**Comment by magento-engcom-team** [comment]
Hi @noahm96. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@noahm96 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@noahm96 ,thank you for your report.  
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
