### ISSUE TITLE
updating product clears all pages from varnish? Magento 2.2.4

### ISSUE THREAD

**Issue by N1ghtfl0w** [magento/magento2#17600]
Hi There!

Im really struggling with the last bit off the website, caching... and i was wondering if anyone has/had the same problem we have now:

If i browse on my website for the first time the ttfb is around 2.5s, then it get chached by varnish and the second time the ttfb is around 0.3s AMAZING! But when i'm changing for example a price of one of my products, it clears all off the cached pages in varnish?

Shouldn't it only clear the pages where the product is linked to, such as the categories he's in?

HELP!

### Preconditions
Magento 2.2.4
Apache Server
Varnish 5
Redis

### Steps to reproduce
1. Visit url first time 2.5s load
2. Visit url second time 0.3s load (varnish cached)
3. Update product not related to url in cache
4. Visit url again

### Expected result
 url still cached cause non related to product

### Actual result
 varnish cache completely cleared?

**Comment by magento-engcom-team** [comment]
Hi @N1ghtfl0w. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@N1ghtfl0w do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @N1ghtfl0w, thank you for your report. I'm not able to reproduce this issue. Also, I've checked tags for varnish purge request on product update. They all related to given product and categories for this product.
Could you please add more details?

**Comment by N1ghtfl0w** [comment]
Thank you for looking in to it!

I checked the varnish log what happends when i update a product:

<< Request  >> 5318281
-   Begin          req 5318280 rxreq
-   Timestamp      Start: 1534320174.817462 0.000000 0.000000
-   Timestamp      Req: 1534320174.817462 0.000000 0.000000
-   ReqStart       2a00:f10:305:0:4e1:f0ff:fe00:44d 41106
-   ReqMethod      PURGE
-   ReqURL         /
-   ReqProtocol    HTTP/1.1
-   ReqHeader      X-Magento-Tags-Pattern: ((^|,)cat_p_8836(,|$))|((^|,)cat_p_8835(,|$))|((^|,)cat_c_2(,|$))|((^|,)cat_c_3(,|$))|((^|,)cat_c_4(,|$))|((^|,)cat_c_13(,|$))|((^|,)cat_c_28(,|$))|((^|,)cat_c_96(,|$))|((^|,)cat_c_1(,|$))
-   ReqHeader      Host: www.hengeldiscount.nl
-   ReqHeader      X-Forwarded-For: 2a00:f10:305:0:4e1:f0ff:fe00:44d
-   VCL_call       RECV
-   VCL_acl        MATCH purge "2a00:f10:305:0:4e1:f0ff:fe00:44d"
-   VCL_return     synth
-   VCL_call       HASH
-   VCL_return     lookup
-   Timestamp      Process: 1534320174.817913 0.000451 0.000451
-   RespHeader     Date: Wed, 15 Aug 2018 08:02:54 GMT
-   RespHeader     Server: Varnish
-   RespHeader     X-Varnish: 5318281
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespReason     Purged
-   VCL_call       SYNTH
-   RespHeader     Content-Type: text/html; charset=utf-8
-   RespHeader     Retry-After: 5
-   VCL_return     deliver
-   RespHeader     Content-Length: 242
-   Storage        malloc Transient
-   RespHeader     Accept-Ranges: bytes
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1534320174.818010 0.000547 0.000097
-   ReqAcct        263 0 263 220 242 462
-   End
------------------------------------------------------------------------

i can trace all the categories accept for one, cat_c_1 our webshop begins with cat_c_2.

is it possible that when varnsih can't find a category he flushes everything?

**Comment by engcom-backlog-nickolas** [comment]
@N1ghtfl0w, thanks for feedback. cat_c_1 it's "Root Catalog" category. It exists but doesn't show up in admin area. I've double checked on different versions magento 2.2.x and still not able to reproduce this issue.

**Comment by engcom-backlog-nickolas** [comment]
@N1ghtfl0w, I've tested with your vcl, still have no problems.

**Comment by N1ghtfl0w** [comment]
So if you update a product, the cache remains with the categories that are not associated with that product?

if so im losing it...

**Comment by N1ghtfl0w** [comment]
ow wait! i forgot to comment that we are using hitch for handling SSL!

**Comment by engcom-backlog-nickolas** [comment]
@N1ghtfl0w, thank you for feedback. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by N1ghtfl0w** [comment]
@engcom-backlog-nickolas still have one question, is it possible to remove cat_c_1 & cat_c_2 from the purge requests?
