### ISSUE TITLE
angular infdig error on first page of setup

### ISSUE THREAD

**Issue by jclyons52** [magento/magento2#1761]
[the error](https://docs.angularjs.org/error/$rootScope/infdig?p0=10&p1=%5B%5B%22fn:%20function%20()%7Breturn%20d%7D;%20newVal:%20%5C%22index.php%2Fnavigation%2Fmenu%5C%22;%20oldVal:%20undefined%22,%22fn:%20function%20(a)%7Btry%7Bfor(var%20b%3D0,c%3DD,f;b%3Cc;b%2B%2B)%7Bif(%5C%22function%5C%22%3D%3Dtypeof(f%3DA%5Bb%5D))if(f%3D%5Cnf(a),f%3Dl%3Fe.getTrusted(l,f):e.valueOf(f),null%3D%3Df)f%3D%5C%22%5C%22;else%20switch(typeof%20f)%7Bcase%20%5C%22string%5C%22:break;case%20%5C%22number%5C%22:f%3D%5C%22%5C%22%2Bf;break;default:f%3Dqa(f)%7Dt%5Bb%5D%3Df%7Dreturn%20t.join(%5C%22%5C%22)%7Dcatch(h)%7Ba%3Dyc(%5C%22interr%5C%22,g,h.toString()),d(a)%7D%7D;%20newVal:%20%5C%22main%20%5C%22;%20oldVal:%20undefined%22%5D,%5B%22fn:%20function%20()%7Breturn%20d%7D;%20newVal:%20%5C%22index.php%2Fnavigation%2Fmenu%5C%22;%20oldVal:%20undefined%22,%22fn:%20function%20(a)%7Btry%7Bfor(var%20b%3D0,c%3DD,f;b%3Cc;b%2B%2B)%7Bif(%5C%22function%5C%22%3D%3Dtypeof(f%3DA%5Bb%5D))if(f%3D%5Cnf(a),f%3Dl%3Fe.getTrusted(l,f):e.valueOf(f),null%3D%3Df)f%3D%5C%22%5C%22;else%20switch(typeof%20f)%7Bcase%20%5C%22string%5C%22:break;case%20%5C%22number%5C%22:f%3D%5C%22%5C%22%2Bf;break;default:f%3Dqa(f)%7Dt%5Bb%5D%3Df%7Dreturn%20t.join(%5C%22%5C%22)%7Dcatch(h)%7Ba%3Dyc(%5C%22interr%5C%22,g,h.toString()),d(a)%7D%7D;%20newVal:%20%5C%22main%20%5C%22;%20oldVal:%20undefined%22%5D,%5B%22fn:%20function%20()%7Breturn%20d%7D;%20newVal:%20%5C%22index.php%2Fnavigation%2Fmenu%5C%22;%20oldVal:%20undefined%22,%22fn:%20function%20(a)%7Btry%7Bfor(var%20b%3D0,c%3DD,f;b%3Cc;b%2B%2B)%7Bif(%5C%22function%5C%22%3D%3Dtypeof(f%3DA%5Bb%5D))if(f%3D%5Cnf(a),f%3Dl%3Fe.getTrusted(l,f):e.valueOf(f),null%3D%3Df)f%3D%5C%22%5C%22;else%20switch(typeof%20f)%7Bcase%20%5C%22string%5C%22:break;case%20%5C%22number%5C%22:f%3D%5C%22%5C%22%2Bf;break;default:f%3Dqa(f)%7Dt%5Bb%5D%3Df%7Dreturn%20t.join(%5C%22%5C%22)%7Dcatch(h)%7Ba%3Dyc(%5C%22interr%5C%22,g,h.toString()),d(a)%7D%7D;%20newVal:%20%5C%22main%20%5C%22;%20oldVal:%20undefined%22%5D,%5B%22fn:%20function%20()%7Breturn%20d%7D;%20newVal:%20%5C%22index.php%2Fnavigation%2Fmenu%5C%22;%20oldVal:%20undefined%22,%22fn:%20function%20(a)%7Btry%7Bfor(var%20b%3D0,c%3DD,f;b%3Cc;b%2B%2B)%7Bif(%5C%22function%5C%22%3D%3Dtypeof(f%3DA%5Bb%5D))if(f%3D%5Cnf(a),f%3Dl%3Fe.getTrusted(l,f):e.valueOf(f),null%3D%3Df)f%3D%5C%22%5C%22;else%20switch(typeof%20f)%7Bcase%20%5C%22string%5C%22:break;case%20%5C%22number%5C%22:f%3D%5C%22%5C%22%2Bf;break;default:f%3Dqa(f)%7Dt%5Bb%5D%3Df%7Dreturn%20t.join(%5C%22%5C%22)%7Dcatch(h)%7Ba%3Dyc(%5C%22interr%5C%22,g,h.toString()),d(a)%7D%7D;%20newVal:%20%5C%22main%20%5C%22;%20oldVal:%20undefined%22%5D,%5B%22fn:%20function%20()%7Breturn%20d%7D;%20newVal:%20%5C%22index.php%2Fnavigation%2Fmenu%5C%22;%20oldVal:%20undefined%22,%22fn:%20function%20(a)%7Btry%7Bfor(var%20b%3D0,c%3DD,f;b%3Cc;b%2B%2B)%7Bif(%5C%22function%5C%22%3D%3Dtypeof(f%3DA%5Bb%5D))if(f%3D%5Cnf(a),f%3Dl%3Fe.getTrusted(l,f):e.valueOf(f),null%3D%3Df)f%3D%5C%22%5C%22;else%20switch(typeof%20f)%7Bcase%20%5C%22string%5C%22:break;case%20%5C%22number%5C%22:f%3D%5C%22%5C%22%2Bf;break;default:f%3Dqa(f)%7Dt%5Bb%5D%3Df%7Dreturn%20t.join(%5C%22%5C%22)%7Dcatch(h)%7Ba%3Dyc(%5C%22interr%5C%22,g,h.toString()),d(a)%7D%7D;%20newVal:%20%5C%22main%20%5C%22;%20oldVal:%20undefined%22%5D%5D)

steps that got me to it:
- clone the repo running 
- composer install 
- npm install
- create new site on vm (Laravel homestead) and add it to hosts file locally as magento2.dev
- navigate to magento2.dev
- redirected to magento2.dev/setup/
- blank page with the above error on the console and over 50 request for favicon-16x16.png

The setup works fine when i run it on MAMP but I can't finish it because of the mysql 5.6 requirement

**Comment by mazhalai** [comment]
@jclyons52 Can you please give us more details: What browser are you using, versions of Magento, MySQL, Apache (or other servers), PHP version.

**Comment by jclyons52** [comment]
Sure thing, the browser was chrome but I get the same error on firefox.
the server is:
nginx 1.6.2
PHP 5.6.3
mysql 5.6.19
ubuntu 14.04

It's a [Laravel homestead] (http://laravel.com/docs/5.1/homestead) vagrant box.

**Comment by mazhalai** [comment]
@jclyons52 thank you for the details. We have created ticket MAGETWO-42424 to investigate

**Comment by mazhalai** [comment]
@jclyons52 can you please try temporary fix provided here https://github.com/magento/magento2/issues/2005#issuecomment-145916079 to see if it solves your problem

**Comment by jclyons52** [comment]
That solves it. Thanks!
