### ISSUE TITLE
"2 columns with left bar" doesn't work

### ISSUE THREAD

**Issue by naspar** [magento/magento2#1762]
On a fresh installation I get a blank screen and the following message into the log after changing the HOME page layout from the default 1 column to "2 columns with left bar" : 

[2015-08-30 16:28:00] main.INFO: Cache file with merged layout: LAYOUT_frontend_STORE1_4c7461af04bb11fe209659d7147d2c579: Please correct the XML data and try again.  [] [] 

cache has been already cleaned from command line and GUI.

any idea how can I fix it ?

**Comment by alankent** [comment]
Was there any file name or line number near the "please correct the XML" message? It would be good to know what the error is - hopefully it told you the file name and line number, or else that would make another good bug request to submit.

Do you install from the 'master' or 'develop' branch? I just tried as following, but it worked for me. I want to Admin, Content, and the "404" page. I am in developer mode. I tried too access /foo and got the 404 page. I changed the content and reloaded /foo, and got the revised content page (no cache refresh required for me). I changed the layout from 2 columns on right to 2 columns on left and reloaded /foo and the content flipped to the other side. So it all seemed to be work for me. Could you provide any additional details? The fastest thing would be the filename and line number of the XML file which had the problem.

**Comment by naspar** [comment]
Hi Alan,
sorry for my very late reply, I have been out for a while.

Let me give you some background first. I have my own module created into app/code folder which provides a custom LeftNavigationMenu in the home page. It was working perfectly with previous releases and not working with the latest taken from here https://github.com/magento/magento2.git .

I did a quick and (maybe) dirty workaround to fix it .. just removed the extra </block> node from the default.xml layout into my module as following : 

I had this
`
<block class="MyModule\LeftNavigationMenu\Block\Leftmenu" template="MyModule_LeftNavigationMenu::menu.phtml"></block>
`

and then replaced with this
`
<block class="MyModule\LeftNavigationMenu\Block\Leftmenu" template="MyModule_LeftNavigationMenu::menu.phtml">
`

and now it is working.

hope it helps .. if you have any other question or you want me try differently, just le met know.

Thanks!

**Comment by alankent** [comment]
Sounds cool!

If all you did was remove the closing `</block>` tag, I suspect you may have accidentally added an extra close tag on a following line. 

Anything else you need from us?  If not, is it ok to close this issue? Thanks!

**Comment by naspar** [comment]
yes, please close the issue and thanks again!
