### ISSUE TITLE
Magento 2.2.5: Closing bracket/semi-colon is removed from Magento_Ui bootstrap.js and app.js files.

### ISSUE THREAD

**Issue by muckee** [magento/magento2#17647]
When I access the files via the path `[magento_dir]/vendor/magento/module-ui/js/...`, then I can see that the files do contain the closing bracket and semi-colon, but when they are rendered on the frontend it is missing.

### Preconditions
1. Ubuntu 18.04
2. Nginx 1.14
3. MariaDB 15.1 Distrib 10.1.34
4. PHP 7.1

### Steps to reproduce
1. Install Magento 2.2.5.
2. Access website frontend
3. View console in code inspector.

### Expected result
1. No console errors are shown.

### Actual result
1. The console reads "SyntaxError: missing ) after argument list" for file `app/code/Magento_Ui/js/lib/knockout/bootstrap.js`.
2. The console reads "SyntaxError: missing ) after argument list" for file `app/code/Magento_Ui/js/core/app.js`.

When I use the Firefox 'Reveal in sources panel' option, I can see that the files are rendered like so:

> Bootstrap.js
```
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** Loads all available knockout bindings, sets custom template engine, initializes knockout on page */

define([
    'ko',
    './template/engine',
    'knockoutjs/knockout-es5',
    './bindings/bootstrap',
    './extender/observable_array',
    './extender/bound-nodes',
    'domReady!'
], function (ko, templateEngine) {
    'use strict';

    ko.uid = 0;

    ko.setTemplateEngine(templateEngine);
    ko.applyBindings();
}
```

> App.js
```
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
define([
    './renderer/types',
    './renderer/layout',
    '../lib/knockout/bootstrap'
], function (types, layout) {
    'use strict';

    return function (data, merge) {
        types.set(data.types);
        layout(data.components, undefined, true, merge);
    };
}
```

The last line of each file should not be a single curly brace. It should read like this:
```
});
```

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JoshuaFlood do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@JoshuaFlood, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by muckee** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood, here is your [Magento instance](https://i-17647-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17647-2-2-5.engcom.dev.magento.com/admin](https://i-17647-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by muckee** [comment]
@magento-engcom-team Oops... I missed it. May I have another?

It is more common when the store is running in developer/default mode, when the cache is flushed and the website is visited for the first time, though it does appear intermittently on cached pages.

**Comment by muckee** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood, here is your [Magento instance](https://i-17647-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17647-2-2-5.engcom.dev.magento.com/admin](https://i-17647-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by muckee** [comment]
Well, I'm getting a different error... but an error is reported for `require.js` when I simply access the frontend without making any changes and refresh using "`Ctrl + f5`".

Here are screenshots of the console...

![1](https://user-images.githubusercontent.com/32198963/44273526-9f0b0280-a237-11e8-894c-3e67ca9711d2.png)
![2](https://user-images.githubusercontent.com/32198963/44273527-9f0b0280-a237-11e8-87c3-34f1197734ef.png)
![3](https://user-images.githubusercontent.com/32198963/44273528-9fa39900-a237-11e8-96e6-2b076fc50fe0.png)
![4](https://user-images.githubusercontent.com/32198963/44273529-9fa39900-a237-11e8-8fac-85788afad74a.png)


Actually, after flushing the cache the error resolves itself. Perhaps, though, if you could explain to me why those errors are shown then I can compare with my instance and see if its related.

**Comment by muckee** [comment]
@magento-admin @magento-engcom-team @magento-devops Please describe in explicit detail how you build these 'vanilla instances' so that I can replicate it. Your documentation is not clear at all and countless people have countless problems that you are rarely able to replicate, despite their common occurence amongst the Magento community. Presumably this is because you know something that we don't about what is required to ensure that Magento is stable... something which definitely is not explained in your current docs.

**Comment by muckee** [comment]
@magento-engcom-team I have just worked out that it occurs upon first visiting a page after flushing the cache/deploying static files.

I'm sure it must have been reported before that pages sometimes load incorrectly the first time, presumably because the event which requests files is asynchronous and the files being requested have not been properly generated before they are requested.

I also see an error sometimes which references knockout.js and alerts me that multiple bindings cannot be applied to the same element... or something... but that error also disappears after refreshing the page a few times.

So this is not a problem once all files are deployed properly, but it does mean that a user might encounter a broken page if it has never been visited before since the last execution of `cache:flush` or `setup:static-content:deploy`.

Of course, it's smart for a vendor/web designer to attempt to visit the frontpage, or any other pages that are likely to be visited regularly at least once when the site is in production, in order to trigger the cache and allow faster load times for genuine site visitors, but might still miss pages.

It seems to occur more often on pages where there are input fields, such as the one-page checkout or 'Contact Us' page... and I guess it is more likely to do with how knockout is implemented than anything specific to Magento functionality.

**Comment by engcom-backlog-nickolas** [comment]
@JoshuaFlood, thank you for feedback. Unfortunately I'm still not able to reproduce issue You've described.
If you'd like to update it, please reopen the issue.
