### ISSUE TITLE
error when printing order packing slip

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1765]
Receiving error: `There are no shipping labels related to selected orders.`

Trying to print sample order 00000002 where there is a shipment created.

![screen shot 2015-08-31 at 1 03 05 am](https://cloud.githubusercontent.com/assets/437029/9572344/79aad0f8-4f7c-11e5-81ec-a4e77aa764f7.png)

**Comment by okorshenko** [comment]
@markoshust , thank you for reporting. Internal ticket: MAGETWO-43230

**Comment by piotrekkaminski** [comment]
We are unable to reproduce this issue @markoshust. Can you provide steps leading to this error?

**Comment by markoshust** [comment]
This now seems to be fixed in develop
