### ISSUE TITLE
Error on the reviews grid page due to PHP notice "iconv_strlen(): Detected an illegal character in input string"

### ISSUE THREAD

**Issue by zlik** [magento/magento2#17653]
### Summary
Our Magento administrators were sometimes getting a blank page when opening a reviews grid page (Marketing -> Reviews) in Magento admin panel. We are using standard Magento product reviews functionality.

### Steps to reproduce

1. Submit a product review with an invalid UTF-8 escape sequence, e.g. `\xe9` in details. Make sure your string is not escaped and sent as is. You can craft and send a raw `POST` cURL request.
2. As an administrator, open the reviews grid page, filter it if neccessary such, so the submitted review is in the list of grid items.

### Expected result
Reviews grid is visible.

### Actual result
Seeing a blank page.

### Preconditions
1. Magento version: `2.2.3`;
2. PHP version: `7.0.31`;
3. `MAGE_MODE`: `production`;
4. `php.ini` settings:
- `error_reporting`: `22527`;
- `display_errors`: `Off`;
- `log_errors`: `On`.

### Debug info
Under the hood, it was caused by Magento error handler throwing an error when catching the `iconv_strlen(): Detected an illegal character in input string` PHP notice.

An example record in `system.log`:

```
[2018-08-14 23:43:45] main.CRITICAL: Notice: iconv_strlen(): Detected an illegal character in input string in /var/www/project/vendor/magento/framework/Stdlib/StringUtils.php on line 152 [] []
```

We traced the error to this core method: `Magento\Framework\Stdlib\StringUtils::strlen()`. It is called on the reviews grid page to determine a review detail string length. It uses PHP native `iconv_strlen` function, which may raise a PHP notice if a string contains invalid characters. 

It's easy to reproduce `iconv_strlen` raising PHP notice scenario locally by using an example from http://php.net/manual/en/function.iconv-strlen.php:

```
$ php -a
Interactive shell

php > $str = "I�t�rn�ti�n\xe9�liz�ti�n";
php > print "iconv_strlen: ".iconv_strlen($str,'UTF-8')."\n";
PHP Notice:  iconv_strlen(): Detected an illegal character in input string in php shell code on line 1

Notice: iconv_strlen(): Detected an illegal character in input string in php shell code on line 1
iconv_strlen: 
```

In our case, the product review detail string arrived from user input. It was escaped but not sanitized so we got the notice. Even though we do not display PHP errors or notices (only log them) and `MAGE_MODE` is set to `production`, Magento error handler wasn't able to handle this PHP notice properly so we ended up seeing a blank page.

### Fix
The reviews with broken characters were identified as spam so we deleted them. As a quick solution, to prevent this from happening going forward, we created a plugin around `Magento\Framework\Stdlib\StringUtils::strlen()` and replace `iconv_strlen` with `mb_strlen`, which calculates the length of the input string correctly without raising a PHP notice, even if a string contains an invalid escape sequence.

We have't done anything with filtering or sanitization of input product reviews data yet but it would be nice if review records in the database ended up being clean UTF-8 strings.

**Comment by magento-engcom-team** [comment]
Hi @zlik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@zlik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@zlik , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![reviews](https://user-images.githubusercontent.com/41946904/44265973-78e26400-a231-11e8-9bbc-617f07e03fa8.png)

**Comment by zlik** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @zlik. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @zlik, here is your [Magento instance](https://i-17653-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17653-2-2-3.engcom.dev.magento.com/admin](https://i-17653-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by zlik** [comment]
@engcom-backlog-andrii, I was able to reproduce the issue in https://i-17653-2-2-3.engcom.dev.magento.com. Just go to https://i-17653-2-2-3.engcom.dev.magento.com/admin/review/product/index/ and you will see a blank broken page.

I used a string containing a malicious payload from one of our spam reviews to post a new review in your vanilla Magento environment. Here is the script that I used:

```
<?php

function hexToStr($hex)
{
    $string = '';
    for ($i = 0; $i < strlen($hex) - 1; $i += 2) {
        $string .= chr(hexdec($hex[$i] . $hex[$i + 1]));
    }
    return $string;
}

$hex = '6164756C7420776F6D656E2077616E742073657820776974686F757420636F6D6D69746D656E742053652062696C64657220EDA0BDEDB18968747470733A2F2F736578796769726C667265652E636F6D20D0A0D0B5D0B0D0BBD18CD0BDD18BD0B520D0B7D0BDD0B0D0BAD0BED0BCD181D182D0B2D0B020D0B2D0B7D180D0BED181D0BBD18BD18520D0B6D0B5D0BDD189D0B8D0BD20D0B8D0B720D182D0B2D0BED0B5D0B3D0BE20D0B3D0BED180D0BED0B4D0B020D0BAD0BED182D0BED180D18BD0B520D185D0BED182D18FD18220D0B7D0BDD0B0D0BAD0BED0BCD181D182D0B220D0B1D0B5D0B720D0BED0B1D18FD0B7D0B0D182D0B5D0BBD18CD181D182D0B220D0BDD0B020D0BED0B4D0BDD18320D0BDD0BED187D18C2E';
$str = hexToStr($hex);

$a = <<<HERE
curl -d "form_key=wmSTfmbf5GOfhT5h&nickname=test&title=test&detail=$str" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -H "Cookie: form_key=wmSTfmbf5GOfhT5h;" \
    -X POST https://i-17653-2-2-3.engcom.dev.magento.com/review/product/post/id/1/
HERE;

`$a`;
```

Please make sure to insert a correct `form_key` value belonging to your user session when runinng the script.

**Comment by ghost** [comment]
@zlik , thanks for you update.
We've acknowledged the issue and added to our backlog.

**Comment by zlik** [comment]
No problem at all, thanks for checking @engcom-backlog-andrii. I understand this could have been tricky to reproduce so thanks for your patience.
