### ISSUE TITLE
"System" Backup not backing up completely 

### ISSUE THREAD

**Issue by rishabhchd19** [magento/magento2#17664]
### Preconditions

PHP 7.1, MAGENTO CE 2.2.5

### Steps to reproduce

1.  Cron jobs running: 

* | * | * | * | * | /opt/cpanel/ea-php70/root/usr/bin/php -dmemory_limit=5G /home1/server/public_html/Magento CE 2.2.5/bin/magento cron:run >/dev/null 2>&1

* | * | * | * | * | /opt/cpanel/ea-php70/root/usr/bin/php -dmemory_limit=5G /home1/server/public_html/Magento CE 2.2.5/update/cron.php >/dev/null 2>&1

* | * | * | * | * | /opt/cpanel/ea-php70/root/usr/bin/php -dmemory_limit=5G /home1/server/public_html/Magento CE 2.2.5/bin/magento setup:cron:run >/dev/null 2>&1

2. Login Admin>System>>Backups>>>System Backup
3. When tap to "System" Backup, Enter the name, "Select" Please put your store into maintenance mode during backup.
4. When tap to "System" Backup, Enter the name, "DeSelect" Please put your store into maintenance mode during backup.
### Expected result

1. The System Backup Loading "Please wait..." should not be finished earlier and disappear until System is backup Completely. 
2. If "Selected" Maintenance Mode, the Loading"Please Wait..." should be running and when it disappears, it should not remain on Maintenance Mode and backup should be "Complete". 
3. If "Deselected" Maintenance Mode, the Loading"Please Wait..." should be running or may not be, but it should the Backup "Complete" and must show the image size as same as a backup when Maintenance Mode is Enabled. 

### Actual result

1. When Maintenance Mode is Enabled during System Backup, it remains on maintenance mode Indefinitely period. Maintenance mode is disabled when command : php bin/magento maintenance:disable
2. When Maintenance Mode is Disabled during System Backup, the Loading "Please Wait" disappear and System Backup by its name doesn't display there. When refreshed the page, it shows incorrect image size, and even smaller than the size when system was backup with Maintenance mode enabled. 
3. Cron Jobs are running perfectly. No issue in cron jobs.
4. Different image size every time with different options and every time when it is run. 

[Video](https://drive.google.com/file/d/1u7CJ6F6FSphxnMkkLQOFOa6aM9KQvf_p/view)

**Comment by magento-engcom-team** [comment]
Hi @rishabhchd19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rishabhchd19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @rishabhchd19, thank you for your report. I'm able to reproduce only different sizes for backups. Could you please add more details, or try to reproduce this issue on clean installation?

**Comment by rishabhchd19** [comment]
Yes. Different sizes of the same "System". It should be the same if nothing has been added or updated. eg. System backup taken at 13:00:01 size 345MB. Now the system has no user and nothing updating or operating the website. On again backing up the System backup at 13:01:01 size will be different. 
It shows that system files are not backing up completely.

**Comment by rishabhchd19** [comment]
The loading "Please wait" disappears while backing up and Page doesn't refresh automatically to show System backup and Backup image size. On manual refresh, the backup image is of different size and indicate that backup was stopped when Loading disappeared. 
You can watch the problem [here ](https://drive.google.com/file/d/1u7CJ6F6FSphxnMkkLQOFOa6aM9KQvf_p/view?usp=sharing) at 2:15 - 3:00 and at the end.

**Comment by magento-engcom-team** [comment]
@rishabhchd19, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
