### ISSUE TITLE
Update UI so modal doesn't show when cache clear is needed

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1769]
There are two "One or more of the Cache Types are invalidated" messages that appear when a cache clear is needed. 

![screen shot 2015-08-31 at 9 42 13 am](https://cloud.githubusercontent.com/assets/437029/9580023/c6902b46-4fc4-11e5-940b-5e1b714affcd.png)

I don't see the purpose of the modal prompting, and then when closing the modal, still seeing the alert at the top of the screen.

The modal is redundant. I believe this should be removed, and stick with the "M1" way of the prompts by just displaying the message at the top of the screen. It's plenty apparent the cache needs to be cleared. Having to close the modal every time is also very cumbersome and annoying...

![screen shot 2015-08-31 at 9 43 35 am](https://cloud.githubusercontent.com/assets/437029/9580044/f66aa63e-4fc4-11e5-8a3e-af8437248df6.png)

**Comment by laupkram** [comment]
+1

**Comment by MomotenkoNatalia** [comment]
Internal reference: MAGETWO-37976
Thanks for reporting this issue!

**Comment by markshust** [comment]
I don't think this issue was ever resolved, as it still exists in 2.0.0.

**Comment by markshust** [comment]
@MomotenkoNatalia since 2.0.0 is released, are tickets still handled internally or is everything on github now? I wasn't sure if this was being resolved (because you have an internal ticket number noted), or if you were taking PR's for stuff like this. Lmk. Thanks!

**Comment by sshrewz** [comment]
@markoshust, there was a misunderstanding.  Internal ticket should be MAGETWO-43718.

**Comment by vkorotun** [comment]
There is related internal ticket in progress now MAGETWO-50670 that need to address issue with automated caches flushes without displaying modals/notifications (especially in developer/default modes). We will check this one if it still valid and will fix it if so.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Update-UI-so-modal-doesn-t-show-when-cache-clear-is-needed/idi-p/46942).

**Comment by magento-engcom-team** [comment]
Hi @markoshust. Thank you for your report. 
The issue has been fixed in magento/magento2#29684 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [4e112321d92b65852db358feb1e9098e023eb346](https://github.com/magento/magento2/commit/4e112321d92b65852db358feb1e9098e023eb346)
 - [f648b8b3c293f837bbbbad6688990ecf228f323d](https://github.com/magento/magento2/commit/f648b8b3c293f837bbbbad6688990ecf228f323d)
 - [fe781002e372ff7fe7b5952f34a268266956698a](https://github.com/magento/magento2/commit/fe781002e372ff7fe7b5952f34a268266956698a)

The fix will be available with the upcoming 2.4.2 release.
