### ISSUE TITLE
Installing Magento 2 on Apache Server

### ISSUE THREAD

**Issue by aneeshjajodia** [magento/magento2#1772]
Hello

I've been trying to install Magento 2 on my mac, on apache server and always failing with some stupid errors.

I would be very happy if someone helped me through the same thing.

Herewith attached the screenshot of the error after using the command `composer install` on the public_html directory.
<img width="577" alt="screenshot 2015-09-01 14 37 12" src="https://cloud.githubusercontent.com/assets/1062704/9600173/1ba5e8bc-50b7-11e5-9192-c50ae5af5a67.png">

**Comment by vpelipenko** [comment]
@aneeshjajodia, enable this extension if it is included in your PHP build.

**Comment by xcomSteveJohnson** [comment]
Yes, this is somewhat of a new requirement. Depending on your PHP version and OS, you can try something like

apt-get -y install php5-xsl

**Comment by mazhalai** [comment]
@aneeshjajodia what do you use to install php packages on mac? homebrew? or something else?

**Comment by uchsarath** [comment]
just installing sudo apt-get -y install php5-intl

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
