### ISSUE TITLE
Is there a reason why customerData works different on Product Page?

### ISSUE THREAD

**Issue by ezequielalba** [magento/magento2#17732]
Hello!

I am working a lot lately with the client side interactions and mage-cache-storage using the customerData. Like when the user clicks some button, I send information to the customerData and store it there for future use in the same session.

For example:
```
storeCustomData: function(data){
            customSection = customerData.get('custom-section')();
            customSection['data'] = data;
            customerData.set('custom-section', customSection);
},
```

So far, really good, I was doing some cool stuff retrieving data from the Client side when User Interacts, storing information once the user does something, and rendering a JavaScript template using `mageTemplate` without any issues. 

All of this while working on the CMS page side, Category/Catalog side, but **is not working while on the Product View page**. 

If I set the values of that customerData custom section from the Product View page, every time that I refresh the page, the value is there stored on the Browser (tested on Chrome, Safari, and Firefox), but If I tried to get the data with `customerData.get('custom-section')()` from it at page load always response with an empty object. 10-20 times refreshes without cleaning cache, and no luck. 

Any ideas why? 

Curious behavior: If I change from the Product view (while having the data stored on my `mage-cache-storage`) to the Category view, the response is correct, I can get the object and render my template correctly, so if I get back to Product again, works! (weird), so apparently there is something else going on while interacting from the Product view side and reloading inside that instance over and over.

### Preconditions
1. PHP 7.0.30
2. Magento 2.2.3

### Steps to reproduce
**First of all, you have to be on the Product View page**.
1. Declare the custom section on the di.xml inside your custom module with this:
```
<type name="Magento\Customer\Block\SectionConfig">
        <arguments>
            <argument name="clientSideSections" xsi:type="array">
                <item name="custom-section" xsi:type="string">custom-section</item>
            </argument>
        </arguments>
    </type>
```
2. Setup a user click interaction like `open/close` and inside the click function retrieve **data** from the HTML and store it on the customerData using the example function from the code above. Then execute this function like a widget with the `data-mage-init` when one of the product view templates renders, for example, `form.phtml`.
3. Refresh the page, product view, and try to retrieve that data at load with 
```
getCustomData: function() {
            customSection = customerData.get('custom-section')();
            data = customSection['data'];
            return data;
 },
```
### Actual result
Response is "undefined" cause of an empty object. But the `custom-section` is still there with all the information from before. 

_Note_: I am checking if the object is empty first, so if the user has not interacted with it before, won't render the template with the information null. I am checking with underscore:
```
if (_.isEmpty(data)) {
                return status = false;
            } else {
                return status = true;
   }
```
The console.log of that function always returns `false` even with the data being there.

If I work from Catalog page, it works. It gets the object correctly and renders the information at refresh.

### Expected result
1. Get the information correctly in the Product view page from the customerData custom section as every other page from Magento.
2. The `mage-cache-storage` doesn't refresh my custom-section in the product view, like catalog or cms views works. The object is not empty as a response from the function.

**Comment by magento-engcom-team** [comment]
Hi @ezequielalba. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ezequielalba do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ezequielalba** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @ezequielalba. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ezequielalba, here is your [Magento instance](https://i-17732-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17732-2-2-3.engcom.dev.magento.com/admin](https://i-17732-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ezequielalba** [comment]
@magento-engcom-team I just need to know if that is something that is supposed to happen in the product View or it is actually something that I can avoid by using another method or approach. 
All the information required to reproduce the issue is specified correctly in the first comment/post of the thread. Thanks!

**Comment by ghost** [comment]
Hi @ezequielalba I'm not able to reproduce by following steps your described, in my case i use this example
```
define([
    'uiComponent',
    'Magento_Customer/js/customer-data'
], function (Component, customerData) {
    'use strict';

    return Component.extend({
        /** @inheritdoc */
        initialize: function () {
            this._super();
            this.customsection = customerData.get('customsection'); //pass your custom section name
        }
    });
});
```

**Comment by ezequielalba** [comment]
@engcom-backlog-nazar Hi! Thanks for testing that out.

So it actually works differently in the Product View, because I am not using uiComponent for this case due to the module it is something being used across the whole site with a lot of User Interactions that can change the customerData at any time.

I am using only JavaScript without KO. We need the interactions to be fast, and with uiComponent the response it is slow for our final goal.

What is the reason for this to work perfectly everywhere else without the use of uiComponent besides the Product View Page? It can be overridden/extended so it can work without that? Or it is strictly mandatory for me to use the uiComponent when I am at the Product View? if that is the case, may I ask, why?

In the end, I am using localStorage for this purpose, but I would like to not have to, and use only `mage-cache-storage`.

Thanks, and sorry for all the doubts!

**Comment by ghost** [comment]
@ezequielalba As the devDocs says, you need to use UiComponent for custom sections, so it's not best practic to use only Javascript. And in this case you should better to use uiComponent on product page.

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching/private-content.html

**Comment by ezequielalba** [comment]
@engcom-backlog-nazar I have read the devdocs, a lot of times, but thanks for the heads up again! 

You see, I wanted a reason for that because you say it is bad practice, but in the Magento Core, there are JS files that use the customerData (`Magento_Customer/js/customer-data`) without being included within an uiComponent, also, there are a lot of examples across the web that follows the same steps as my development without the uiComponent and work perfectly, mostly because the interactions are simpler, but this case is different. I know is very particular, that is why I created a very detailed post in order to get answers. 

The uiComponent response for the custom js-module-component I developed needs the response almost instantly, and refreshes, deletes, and creates new data in all the pages, giving the user a lot of power of the data at any time. 

So that is why I wanted more info about it because it is actually really odd, that works perfectly fine in every page but not in the Product page. 

I did research before posting here, Magento on the Product Page triggers the customerData after render, refreshes the content and that is why my `custom-section` is not being loaded at first. This behavior only happens here, I wanted a reason for that. But it is ok, thanks again for the time, I really appreciate it.

Note: You can close the ticket if you want to.

**Comment by ghost** [comment]
Hi @ezequielalba thank you for you report, 
ok  so as we have the solution for this issue i close him,
