### ISSUE TITLE
  Error in Applying Discount Comes in Core of Magento

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#1776]
I have created a coupon programmatically and when I have applied that coupon in discount it is giving the Error in core as:-
"Fatal error: Cannot use assign-op operators with overloaded objects nor string offsets in /opt/lampp/htdocs/workspace/magento_2_Aug/magento2/app/code/Magento/SalesRule/Model/Rule/Action/Discount/CartFixed.php on line 70"
$cartRules[$rule->getId()] -= $baseDiscountAmount;

Solution:-When I have changed the code to :-
$cartRules[$rule->getId()] = $cartRules[$rule->getId()]-$baseDiscountAmount;
It works.
Thank you

**Comment by sivaschenko** [comment]
@aishwaryacedcoss Thank you for your report. Internal ticket MAGETWO-42590 is created to track this issue.

**Comment by slavvka** [comment]
There is a duplicate #1768 which is to be closed on delivery.
