### ISSUE TITLE
Customer Address Import - Invalid data for insert

### ISSUE THREAD

**Issue by ajzele** [magento/magento2#1777]
When I try to import `Customer Address` entity type from Magento admin, the Check Data button reports my CSV fully correct. However, when I hit the actual import, I get the "Invalid data for insert" error message originating from lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php file. The reason is that $cols count is diff than $row count.

As shown below.

$cols array(19) {
  entity_id
  parent_id
  updated_at
  city
  company
  country_id
  fax
  firstname
  lastname
  middlename
  postcode
  prefix
  region
  street
  suffix
  telephone
  vat_id
  region_id
  created_at
}

$row array(18) {
  entity_id
  parent_id
  updated_at
  city
  company
  country_id
  fax
  firstname
  lastname
  middlename
  postcode
  prefix
  region
  street
  suffix
  telephone
  vat_id
  created_at
}

I traced the issue back to app/code/Magento/CustomerImportExport/Model/Import/Address.php, around line 526, where it says 

        // let's try to find region ID
        if (!empty($rowData[self::COLUMN_REGION])) {
            $countryNormalized = strtolower($rowData[self::COLUMN_COUNTRY_ID]);
            $regionNormalized = strtolower($rowData[self::COLUMN_REGION]);

            if (isset($this->_countryRegions[$countryNormalized][$regionNormalized])) {
                $regionId = $this->_countryRegions[$countryNormalized][$regionNormalized];
                $entityRow[self::COLUMN_REGION] = $this->_regions[$regionId];
                $entityRow['region_id'] = $regionId;
            }
        }

When I comment out the section `$entityRow['region_id'] = $regionId;`, then import works. Obviously not a solution as you want to figure out region id, so the fix needs to be more proper.

**Comment by okorshenko** [comment]
@ajzele Thank you for your report. Internal ticket MAGETWO-42619 is created to track this issue.

**Comment by slavvka** [comment]
@ajzele Could you please provide your CSV file with addresses as importing previously exported addresses causes no error?

**Comment by okorshenko** [comment]
@ajzele could you please provide additional information?

**Comment by piotrekkaminski** [comment]
@ajzele we cannot reproduce - can you provide example file?
