### ISSUE TITLE
CarrierInterface additional requirement

### ISSUE THREAD

**Issue by joshpennington** [magento/magento2#1779]
When creating a shipping module, your class should implement \Magento\Shipping\Model\Carrier\CarrierInterface

However, in order for your shipping module to actually be used, you have to implement a method called  proccessAdditionalValidation that is not required by the CarrierInterface

Failure to implement this method causes your module to be ignored in /app/code/Magento/Shipping/Model/Shipping.php because on line 250, $result will equal false because that method is not called because it does not exist in your module.

**Comment by sivaschenko** [comment]
@joshpennington Thank you for report. Internal ticket MAGETWO-42591 created to track this issue

**Comment by magento-engcom-team** [comment]
@joshpennington, thank you for your report.
We've created internal ticket(s) MAGETWO-42591 to track progress on the issue.

**Comment by dverkade** [comment]
I will pickup this issue. #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @joshpennington Thank you for your report. Unfortunately we can not change `\Magento\Shipping\Model\Carrier\CarrierInterface` interface due to backward compatibility policy. We have MAGETWO-42591 to introduce new shipping carrier API.
