### ISSUE TITLE
Error install data sample

### ISSUE THREAD

**Issue by quockhanh91** [magento/magento2#1780]
Fatal error: Call to undefined method Magento\SampleData\Helper\State::isError() in /Applications/XAMPP/xamppfiles/htdocs/magento2-develop/setup/src/Magento/Setup/Model/SampleData.php on line 89
<img width="1039" alt="screen shot 2015-09-03 at 2 14 13 pm" src="https://cloud.githubusercontent.com/assets/14105484/9652493/333e9d30-5246-11e5-96ce-fbbdc88b40da.png">

**Comment by xcomSteveJohnson** [comment]
Are you using the develop branch or the master branch?

**Comment by vinhbt90vn** [comment]
I had same error. It happens on the develop branch, not on the master branch.

**Comment by mazhalai** [comment]
@quockhanh91 and @vinhbt90vn  sample data is not compatible with `develop` branch. Please use `master` branch if you want to use sample data.
