### ISSUE TITLE
Plugins not called for Magento\Catalog\Block\Product\ListProduct in search page in developer mode

### ISSUE THREAD

**Issue by mlindholm** [magento/magento2#17825]
### Preconditions
1. Magento 2.2.5
2. PHP 7.1.9
3. MySQL 5.6.37

### Steps to reproduce
1. Set deploy mode to developer.
2. Create plugin for Magento\Catalog\Block\Product\ListProduct
3. Go to search page.

### Expected result
1. Magento\Catalog\Block\Product\ListProduct\Interceptor should be used to render the product list.

### Actual result
1. Magento\Catalog\Block\Product\ListProduct is used instead and therefore the plugin is not called.

![image](https://user-images.githubusercontent.com/5977769/44701045-a636d980-aa9d-11e8-86aa-36b8cf0b9c16.png)

Problem seems to stem from Magento\Framework\Interception\Config\Config. The $_omConfig doesn't contain virtualType for Magento\CatalogSearch\Block\SearchResult\ListProduct and is marked as not intercepted.

```
/**
     * Process interception inheritance
     *
     * @param string $type
     * @return bool
     */
    protected function _inheritInterception($type)
    {
        $type = ltrim($type, '\\');
        if (!isset($this->_intercepted[$type])) {
            $realType = $this->_omConfig->getOriginalInstanceType($type);
            if ($type !== $realType) {
                if ($this->_inheritInterception($realType)) {
                    $this->_intercepted[$type] = true;
                    return true;
                }
            } else {
                $parts = explode('\\', $type);
                if (!in_array(end($parts), $this->_serviceClassTypes) && $this->_relations->has($type)) {
                    $relations = $this->_relations->getParents($type);
                    foreach ($relations as $relation) {
                        if ($relation && $this->_inheritInterception($relation)) {
                            $this->_intercepted[$type] = true;
                            return true;
                        }
                    }
                }
            }
            $this->_intercepted[$type] = false;
        }
        return $this->_intercepted[$type];
    }
```

Later on Magento\Framework\Interception\ObjectManager\Config\Developer, this value is checked on hasPlugins function and it will return false.

```
/**
     * Retrieve instance type with interception processing
     *
     * @param string $instanceName
     * @return string
     */
    public function getInstanceType($instanceName)
    {
        $type = parent::getInstanceType($instanceName);
        if ($this->interceptionConfig && $this->interceptionConfig->hasPlugins($instanceName)
            && $this->interceptableValidator->validate($instanceName)
        ) {
            return $type . '\\Interceptor';
        }
        return $type;
    }
```

**Comment by magento-engcom-team** [comment]
Hi @Tuuhea. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Tuuhea do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mlindholm** [comment]
Hello,

I don't believe the vanilla Magento contains any plugins for the product list block, but I managed to replicate the problem on local instance of vanilla Magento.

### Summary
Virtual types defined in frontend di.xml are not taken account when interception config is initialized in
Magento\Framework\Interception\Config\Config on developer mode.

### Information on your environment
1. WAMP stack on Windows 10
2.  Apache 2.4.27
3. PHP 7.1.9
4. MySQL 5.6.37

### Steps to reproduce
1. Set deployment mode to developer
2. Create plugin for Magento\Catalog\Block\Product\ListProduct, which has virtual type Magento\CatalogSearch\Block\SearchResult\ListProduct defined in frontend di.xml


### Expected result
Magento\Framework\Interception\Config\Config should find original instance type for Magento\CatalogSearch\Block\SearchResult\ListProduct, which has plugin and mark it as intercepted.

### Actual Result
Magento\Framework\Interception\Config\Config doesn't find original type for Magento\CatalogSearch\Block\SearchResult\ListProduct. This virtual type can't have plugins so it's marked as not intercepted even, if the original class would have plugin.

**Comment by engcom-backlog-nickolas** [comment]
Hello @Tuuhea, thank you for your report. I'm not able to reproduce this issue.
![peek 2018-08-28 14-35](https://user-images.githubusercontent.com/40755810/44720615-fd55a200-aacf-11e8-932d-08526b58f989.gif)
Could you please add more details?

**Comment by mlindholm** [comment]
Hello @engcom-backlog-nickolas,

Issue happens on search page, where virtual type is used. On production mode the original plugin type is triggered, but in development mode this is not happening.

I set up following plugin:
![image](https://user-images.githubusercontent.com/5977769/44742420-d9668080-ab10-11e8-92cc-b3d3d098af8e.png)

Plugin is not called on search page:
![image](https://user-images.githubusercontent.com/5977769/44742523-19c5fe80-ab11-11e8-87b5-ca7db6686ba3.png)

But appears correctly on category page: 
![image](https://user-images.githubusercontent.com/5977769/44742553-2ba7a180-ab11-11e8-9eb1-db370b1cd5b4.png)

**Comment by engcom-backlog-nickolas** [comment]
@Tuuhea, thanks for details.
We've acknowledged the issue and added to our backlog.

**Comment by visahardik** [comment]
Hello @Tuuhea,

I think [this](https://magento.stackexchange.com/a/150987/24801) link will help you.

**Comment by mlindholm** [comment]
> Hello @Tuuhea,
> 
> I think [this](https://magento.stackexchange.com/a/150987/24801) link will help you.

Hello @visahardik,

Thank you for the link.

The issue here was that the plugin defined for virtual type in etc/frontend/di.xml wasn't working on as expected when using developer mode. 

The link you provided is using global area for defining the plugin. These were working just fine for me, but I wanted to just target frontend.

**Comment by engcom-Echo** [comment]
Hi @Tuuhea. Thank you for your report.
Unfortunately, issue does not reproduce on 2.4-develop. During testing, I got the expected result.

Plugin is called on search page and category page (production and develop mode).

![image](https://user-images.githubusercontent.com/51681435/87934785-6c5b8b80-ca98-11ea-9c9d-bdd1536ed531.png)
![image](https://user-images.githubusercontent.com/51681435/87934795-74b3c680-ca98-11ea-8a1b-58b19643d332.png)

**Comment by VladimirZaets** [comment]
Hi @Tuuhea, due to the results of the investigation this issue is already fixed. If you still have a problem with it, please reopen the issue and provide additional details.

**Comment by Sanjay-100** [comment]
> Hi @Tuuhea. Thank you for your report. Unfortunately, issue does not reproduce on 2.4-develop. During testing, I got the expected result.
> 
> Plugin is called on search page and category page (production and develop mode).
> 
> ![image](https://user-images.githubusercontent.com/51681435/87934785-6c5b8b80-ca98-11ea-9c9d-bdd1536ed531.png) ![image](https://user-images.githubusercontent.com/51681435/87934795-74b3c680-ca98-11ea-8a1b-58b19643d332.png)

@[engcom-Echo](https://github.com/engcom-Echo)


can you the the code you there is no issue.


i try with block i am not getting the expected result.
