### ISSUE TITLE
Missing order IDs after upgrade 2.1.9 to 2.2.5

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#17824]
### Preconditions

1.  Magento 2.2.5
2.  Before Upgrade it was 2.1.9
3.  PHP 7

### Steps to reproduce

-    Run composer update command
-    run php bin/magento setup:upgrade command
-    remove /var/* and generated/*
-    clear browser cache
-    Add product to cart
-    Use Braintree payment method
-    Place an order
-    issue is not getting every time, so you need to check after place order too many time
    please try to place approx 10 to 15 orders

### Expected result

1. In my Orders grid in the admin, all the of orders have sequential order ids, like 100000103, 100000104, 100000105 etc...

### Actual result

I have noticed that in my Orders grid in the admin, all of the orders have sequential order ids, but some order ids are missing like I have 100000103 and then 100000105 in order grid but 100000104 is missing, this happens many time in order grid with different missing order ids 

This issue happens after upgrade 2.1.9 to 2.2.5, but it was working fine before upgrade.

So I don't know what happened to that missing order numbers, I have read some of the posts in Magento community and Stackexchange and they all are saying that this can happen If there is session error or the transaction was declined to the order. Because of this, the order number will not be used again.

I have checked in Braintree Payment log (/var/log/payment.log) for missing orders, and I can see the missing orders are available in **payment.log** with Braintree error message "Cannot use a paymentMethodNonce more than once."

```
'transaction' => 
            Braintree\Error\ValidationErrorCollection::__set_state(array(
               '_errors' => 
              array (
                0 => 
                Braintree\Error\Validation::__set_state(array(
                   '_attribute' => 'paymentMethodNonce',
                   '_code' => '91564',
                   '_message' => 'Cannot use a paymentMethodNonce more than once.',
                )),
              ),

```
For your information before upgrade it was working fine.

**Comment by magento-engcom-team** [comment]
Hi @aasim110. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@aasim110 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@aasim110, thank you for your report.
Please update Steps to reproduce, Expected and Actual results. Currently, they are confusing and not obvious.

**Comment by aasim110** [comment]
@engcom-backlog-pb  I have updated my question, please check and let me know if anything.

**Comment by ghost** [comment]
@aasim110, thank you for update. We cannot reproduce this issue. Please try to reproduce it on the clean Magento installation.
![2 1 9](https://user-images.githubusercontent.com/40756187/44775963-a5767400-ab7f-11e8-904e-abc971973b6e.gif)
![1](https://user-images.githubusercontent.com/40756187/44775970-aad3be80-ab7f-11e8-9688-e8fc3552c3d7.gif)

**Comment by aasim110** [comment]
@engcom-backlog-pb  I think you have misunderstood my question, you are checking order data only after upgrade but my issue is when customer place and order with braintree after upgrade then the issue occurred.

please try to place new orders after upgrade via braintree payment method.
For your information issue haven't occurred every time.

**Comment by ghost** [comment]
@aasim110, please update Steps to Reproduce.

**Comment by aasim110** [comment]
**Steps to reproduce**
- Run composer update command
- run php bin/magento setup:upgrade command
- remove /var/* and generated/*
- clear browser cache
- Add product to cart 
- Use Braintree payment method 
- Place an order
- issue is not getting every time, so you need to check after place order too many time
- please try to place approx 10 to 15 orders

**Comment by ghost** [comment]
@aasim110 I have placed 1 order on 2.1.9 and 20 orders after update through Braintree. This issue is not reproducible.
![1](https://user-images.githubusercontent.com/40756187/45552269-0d43e480-b839-11e8-85fe-4aea137192b8.gif)

**Comment by jalogut** [comment]
Hi @aasim110 

Did you manage to fix the issue? We are facing exactly the same after upgrading from 2.2.5 to 2.2.8

Thanks in advance.
