### ISSUE TITLE
Set Configurable Product Default Configuration

### ISSUE THREAD

**Issue by chasteIT** [magento/magento2#1783]
In Magento2, can we please get the ability to set default configurations of Configurable Products?

@tzyganu's [Easylife Switcher](https://github.com/tzyganu/Switcher) that sets default configurations, keeps the selected options when other above them change. It also changes the product image or media block when options are changed -- among other cool stuff. 

Also, Inchoo did a tutorial on [autoselecting configurable product options](http://inchoo.net/magento/how-to-make-configurable-options-autoselected-on-configurable-product-view-page/), and Iceberg Commerce  provided a [Javascript method](http://icebergcommerce.com/software/blog/iss/article/magento-configurable-products-setting-default-value-for-options/).

Lastly, pre-selecting default simple products would affect the [Simple Configurable Products #335](https://github.com/magento/magento2/issues/335) undertaking. 

Edit: This could be used in conjunction with layered navigation. See issue: [Layered Navigation Filters Pre-Select Configurable Product Options #1784](https://github.com/magento/magento2/issues/1784)

**Comment by webspeaks** [comment]
Hi, any update on this? Has this feature been implemented?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Set-Configurable-Product-Default-Configuration/idi-p/44893).
