### ISSUE TITLE
Filter/Sort Grouped Products by Associated Simple Product Attributes

### ISSUE THREAD

**Issue by chasteIT** [magento/magento2#1785]
Filtering items in grouped product grids using the attributes of their associated simple products could allow users to select options to find their desired simple products similar to configurable product selectors, but it would also allow the store owner to display all of the available simple products initially.

For example, a Grouped Product could contain TVs of brand Samsung, Vizio and LG available in sizes 50, 55 and 60 inches. Upon entering the page, the customer could see the grid of products and their varying brands, sizes and prices. The customer could then select options in a dropdown filter to only show their desired brand and size.

A sorting feature for the initial grid would also be cool.

Edit:  I found Magneto extension, [Grouped Products Filter](http://www.magentocommerce.com/magento-connect/grouped-products-filter.html), which does this exactly. Here is the [demo](http://www.mage-demo.com/test-product-for-filterable-grouped-products-extension/).

**Comment by antboiko** [comment]
Hi @dustinnordquist , sorry for the delay in response. Thanks for your inquiry. We've created internal ticket MAGETWO-52687 for this feature and added it to the backlog.

Best,
Anton.

**Comment by apurv-anand** [comment]
What is the progress on this? We are looking forward for this to be part of Magento.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Filter-Sort-Grouped-Products-by-Associated-Simple-Product/idi-p/47240).
