### ISSUE TITLE
\Magento\Framework\View\Design\Fallback\RulePool::createTemplateFileRule adds redundant (repeated) slash after themes and modules directories

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1786]
Looks like a bug.
My fix is just to remove the redundant slash: https://mage2.pro/t/67

**Comment by okorshenko** [comment]
@dfediuk Thank you for report. Internal ticket MAGETWO-42622 created to track this issue

**Comment by piotrekkaminski** [comment]
This is fixed and should be published soon.
