### ISSUE TITLE
After Update M2.1.11 => 2.2.5: SalesSequence recurring constraint violation

### ISSUE THREAD

**Issue by FerihumF** [magento/magento2#17918]
### Preconditions

1. Magento 2.2.5
2. PHP 7.0.31

### Steps to reproduce

1. I updated Magento from version 2.1.11 to 2.2.5
2. After running the setup:upgrade script I receive the error:
Module 'Magento_SalesSequence':
Running data recurring...Unique constraint violation found

### Expected result

1. The upgrade script running without any issues.

### Actual result

1. The error in SalesSequence RecurringData.php:
Module 'Magento_SalesSequence':
Running data recurring...Unique constraint violation found

Deleting from table sales_sequence_meta does only help once, after running setup:upgrade again, the error appears again.

To me it seems, that https://github.com/magento/magento2/blob/3a2c177d0e268d2ddea6c9bbe14f6b8f183a157c/app/code/Magento/SalesSequence/Setup/SequenceCreator.php#L53
should check if there already is a sales_sequence_meta for the stores defined. And why not shift this to the upgrade data script anyway?

I could not find this issue anywhere, so am I the only one experiencing it? What details have I missed?

**Comment by magento-engcom-team** [comment]
Hi @FerihumF. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@FerihumF do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @FerihumF Can you please  show full exception message ?

**Comment by ghost** [comment]
@FerihumF  First of all, we need to add ‘meta id’ to ‘sales_sequence_meta’ table.
![screenshot_1](https://user-images.githubusercontent.com/40756439/45095507-e265dc00-b126-11e8-9f2a-14f177a122fc.png)
After adding ‘meta id’ to ‘sales_sequence_meta’ table, you need to add those ‘meta id’ to ‘profile id’ into existing ‘sales_sequence_profile’ table and additionally, we have to add more entry in ‘prefix’ column.
![screenshot_2](https://user-images.githubusercontent.com/40756439/45095534-f3aee880-b126-11e8-8903-a570aaaaf7c8.png)

**Comment by FerihumF** [comment]
Hello @engcom-backlog-nazar,

unfortunately it does not say more than: Unique constraint violation found. The script just stops there. Is there a way to specifically execute the RecurringData.php script?

**Comment by ghost** [comment]
Hi @FerihumF Did You have any module with have Sequence on module.xml file ?

**Comment by ghost** [comment]
@FerihumF Did you migrate from 1.* version of magento ?

**Comment by FerihumF** [comment]
No, there is no third party module.xml with a sequence to Magento_SalesSequence. I never had a Magento 1.*, this update was from 2.1.11 to 2.2.5

I have looked in all log files, no clue either.

**Comment by ghost** [comment]
@FerihumF I'm tested it 2 times migrate from 2.1.11 to 2.2.5 but doesn't have no errors. problem may be related to your data.

**Comment by FerihumF** [comment]
@engcom-backlog-nazar thanks for investigating. I now found a third party plugin extending SalesSequence\Model\ResourceModel\Meta which caused the problem. Consider issue closed.

**Comment by jsdupuis** [comment]
@FerihumF may we know the plugin that was causing the problem? I have the same issue as you on Magento 2.2.4. I get Module 'Magento_SalesSequence':
Running data recurring...Unique constraint violation found

**Comment by benjamw** [comment]
I'm getting the same error when trying to install a fresh Magento 2.3.4:

`
Module 'Magento_SalesSequence':
Running schema recurring...
[ERROR] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`sales_sequence_profile`, CONSTRAINT `SALES_SEQUENCE_PROFILE_META_ID_SALES_SEQUENCE_META_META_ID` FOREIGN KEY (`meta_id`) REFERENCES `sales_sequence_meta` (`meta_id`) ON DELETE CASCA) in D:\Development\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php:91 Stack trace: #0 D:\Development\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(91): PDOStatement->execute(Array) #1 D:\Development\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(107): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}() #2 D:\Development\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(92): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute(Object(Closure)) #3 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #4 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #5 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `sa...', Array) #6 D:\Development\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `sa...', Array) #7 D:\Development\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(613): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `sa...', Array) #8 D:\Development\magento\generated\code\Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor.php(128): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `sa...', Array) #9 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query('INSERT INTO `sa...', Array) #10 D:\Development\magento\generated\code\Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor.php(1506): Zend_Db_Adapter_Abstract->insert('sales_sequence_...', Array) #11 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(781): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->insert('sales_sequence_...', Array) #12 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(421): Magento\Framework\Model\ResourceModel\Db\AbstractDb->saveNewObject(Object(Magento\SalesSequence\Model\Profile)) #13 D:\Development\magento\vendor\magento\module-sales-sequence\Model\ResourceModel\Meta.php(153): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\SalesSequence\Model\Profile)) #14 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(863): Magento\SalesSequence\Model\ResourceModel\Meta->_afterSave(Object(Magento\SalesSequence\Model\Meta)) #15 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(424): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Magento\SalesSequence\Model\Meta)) #16 D:\Development\magento\vendor\magento\module-sales-sequence\Model\Builder.php(250): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\SalesSequence\Model\Meta)) #17 D:\Development\magento\vendor\magento\module-sales-sequence\Setup\SequenceCreator.php(67): Magento\SalesSequence\Model\Builder->create() #18 D:\Development\magento\vendor\magento\module-sales-sequence\Setup\Recurring.php(37): Magento\SalesSequence\Setup\SequenceCreator->create() #19 D:\Development\magento\setup\src\Magento\Setup\Model\Installer.php(1033): Magento\SalesSequence\Setup\Recurring->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext)) #20 D:\Development\magento\setup\src\Magento\Setup\Model\Installer.php(836): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array) #21 [internal function]: Magento\Setup\Model\Installer->installSchema(Array) #22 D:\Development\magento\setup\src\Magento\Setup\Model\Installer.php(368): call_user_func_array(Array, Array) #23 D:\Development\magento\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #24 D:\Development\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction() #25 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #26 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure)) #27 D:\Development\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #28 D:\Development\magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #29 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #30 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure)) #31 D:\Development\magento\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #32 D:\Development\magento\setup\index.php(39): Zend\Mvc\Application->run() #33 {main} Next Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`sales_sequence_profile`, CONSTRAINT `SALES_SEQUENCE_PROFILE_META_ID_SALES_SEQUENCE_META_META_ID` FOREIGN KEY (`meta_id`) REFERENCES `sales_sequence_meta` (`meta_id`) ON DELETE CASCA), query was: INSERT INTO `sales_sequence_profile` (`meta_id`, `prefix`, `suffix`, `start_value`, `step`, `max_value`, `warning_value`, `is_active`) VALUES (?, ?, ?, ?, ?, ?, ?, ?) in D:\Development\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php:110 Stack trace: #0 D:\Development\magento\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(92): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute(Object(Closure)) #1 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `sa...', Array) #4 D:\Development\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(546): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `sa...', Array) #5 D:\Development\magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(613): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `sa...', Array) #6 D:\Development\magento\generated\code\Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor.php(128): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `sa...', Array) #7 D:\Development\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query('INSERT INTO `sa...', Array) #8 D:\Development\magento\generated\code\Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor.php(1506): Zend_Db_Adapter_Abstract->insert('sales_sequence_...', Array) #9 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(781): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->insert('sales_sequence_...', Array) #10 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(421): Magento\Framework\Model\ResourceModel\Db\AbstractDb->saveNewObject(Object(Magento\SalesSequence\Model\Profile)) #11 D:\Development\magento\vendor\magento\module-sales-sequence\Model\ResourceModel\Meta.php(153): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\SalesSequence\Model\Profile)) #12 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(863): Magento\SalesSequence\Model\ResourceModel\Meta->_afterSave(Object(Magento\SalesSequence\Model\Meta)) #13 D:\Development\magento\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(424): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Magento\SalesSequence\Model\Meta)) #14 D:\Development\magento\vendor\magento\module-sales-sequence\Model\Builder.php(250): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\SalesSequence\Model\Meta)) #15 D:\Development\magento\vendor\magento\module-sales-sequence\Setup\SequenceCreator.php(67): Magento\SalesSequence\Model\Builder->create() #16 D:\Development\magento\vendor\magento\module-sales-sequence\Setup\Recurring.php(37): Magento\SalesSequence\Setup\SequenceCreator->create() #17 D:\Development\magento\setup\src\Magento\Setup\Model\Installer.php(1033): Magento\SalesSequence\Setup\Recurring->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext)) #18 D:\Development\magento\setup\src\Magento\Setup\Model\Installer.php(836): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array) #19 [internal function]: Magento\Setup\Model\Installer->installSchema(Array) #20 D:\Development\magento\setup\src\Magento\Setup\Model\Installer.php(368): call_user_func_array(Array, Array) #21 D:\Development\magento\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #22 D:\Development\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction() #23 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #24 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure)) #25 D:\Development\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #26 D:\Development\magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #27 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #28 D:\Development\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure)) #29 D:\Development\magento\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #30 D:\Development\magento\setup\index.php(39): Zend\Mvc\Application->run() #31 {main}
`
