### ISSUE TITLE
Bug: the Knockout templates in the app/code/Magento/Ui/view/base/web/templates folder are not translatable despite of bind-attr i18n usage (and my fix)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1791]
My fix: https://mage2.pro/t/70

**Comment by sivaschenko** [comment]
@dfediuk Thank you for report. This issue is already fixed and will be soon available on develop branch

**Comment by mbrinton01** [comment]
@sivaschenko can you confirm if the fix has been merged to develop branch?

**Comment by dfediuk** [comment]
It is NOT fixed: there is no fix in the `develop` branch.

**Comment by dfediuk** [comment]
My new fix for the current core code: https://mage2.pro/t/70/2

**Comment by daim2k5** [comment]
@dfediuk why you don't create a PR?

**Comment by NadiyaS** [comment]
Hi @mage2pro ,
now all phrases are translatable. 
You can upgrade your code from develop branch or wait until next release.
This issue is closed as resolved.
Feel free to reopen this issue if you have the same problem on upgraded version.
