### ISSUE TITLE
Checkbox 'Billing address = Shipping address' not cleared (in time) after changing shipping address

### ISSUE THREAD

**Issue by Rickertje** [magento/magento2#17925]
### Preconditions
1. M2.2.5

**PART A**
### Steps to reproduce
1. Add product to cart
2. Go to checkout Step 1
3. Enter shipping address
4. Go to checkout Step 2
5. Go back to checkout Step 1
6. Change the address (or whatever item)
7. Go to checkout Step 2 

### Expected result
Billing address is different from shipping address AND checkbox is cleared

### Actual result
Billing address is different from shipping address but checkbox is NOT cleared - which is very confusing for the user (see attachment)
![afbeelding](https://user-images.githubusercontent.com/27420995/45056735-088e6c00-b094-11e8-969e-2a11c6fc0b65.png)

**PART B**
### Steps to reproduce  (just continue from A)
8. Choose payment method

### Actual result
Only now the checkbox is cleared which is too late

**PART C**
### Steps to reproduce (just continue from B)
9. Click the button to edit the billing address

### Expected result
A pre filled form containing the billing address is presented (ready for change by the user)

### Actual result part C
1) An empty form is presented

NOTE ALSO THAT as long as the checkbox (Billing=Shipping) is checked and not unchecked by the user I think updating the shipping address SHOULD ALSO update the billing address accordingly. This is a far more natural approach then to let Magento clear the checkbox ( .... unseen by the user). 
Customers make mistakes. A customer discovers in Step 2 that there was an error in the shipping (=billing) address. He gets back to Step 1 to correct the error but is completely unaware that the billing address is not changed accordingly. 
Maybe I should create a new issue for this?

**Comment by magento-engcom-team** [comment]
Hi @Rickertje. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Rickertje do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Rickertje thank you for you report, the fix for this issue has already available in 2.2-develop branch

**Comment by Rickertje** [comment]
Ok can you give me a reference ?

**Comment by ghost** [comment]
@Rickertje i can't find the commit, but tested it on 2.2-develop branch the issue not present.

**Comment by Rickertje** [comment]
Did you reproduce on 2.2.5 ?
What about part C  - is that fixed as well?
And what about the wished-for-behavior I note in the end ? Should I create a new issue for this?

**Comment by ghost** [comment]
@Rickertje https://github.com/magento/magento2/issues/12184 This seems to be correct Magento behavior.

**Comment by Rickertje** [comment]
What I can see is that initially 12184 was added as TODO but was closed later on. So I am not sure  that this is fixed. Could you reproduce in your 2.2.5?
One can discuss about prefered behavior but the situation in the screenshot that I added (which was also similarly added in 12184) is a 100% error. The screenshot shows a situation in which the billing address and shipping address are different while the checkbox is checked.

**Comment by ghost** [comment]
@Rickertje i'm see this behavior on 2.2-develop instance and in 2.2.5 release, but in comment https://github.com/magento/magento2/issues/12184#issuecomment-357009062 says that it is ok.  as you can see from referenced issue its reproduced on 2.2 - 2.3 branch

**Comment by Rickertje** [comment]
I'm not sure what you mean with 'this behavior'
When the billing addres does not equal the shipping address the checkbox should be unchecked at all times - which it is not the actual result of Part A.

**Comment by ghost** [comment]
@Rickertje  on 2.2-develop branch, When the billing addres does not equal the shipping address checkbox unchecked.

**Comment by Rickertje** [comment]
Ok .. but:
a) Did you reproduce this problem on 2.2.5? So that I know that M2 out-of-the-box is the problem and not my payment module f.e.
b) What about the problem with the empty form (PART C) - is this solved as well in 2-2-dev ?
c) Should I create a request for changing the standard behavior I decribed in the note?

**Comment by ghost** [comment]
@Rickertje Yes on 2.2.5 still exist this problem.
b) yes empty field present on 2.2-develop but is may be empty, because you may enter a new address not edit.

**Comment by wwwebgainss** [comment]
any updates concerning that behavior?

**Comment by henk-hypershop** [comment]
Any updates? This issue still persists on M2.2.6, fresh install. BillingAddress does not update when changing the shipping address, even if the billingaddres same as shipping is checked. How can this issue be closed?

**Comment by Rickertje** [comment]
I originally created this issue. And I am still on 2.2.5 so I dont know. This issue was closed because @engcom-backlog-nazar said it was solved in 2.2-develop. If that means that I shoud have been solved in 2.2.6 also is unclear. My experience is that it is almost impossible to get attention from development for closed issues (and also for open ones most of the time). However if you open a new issue someone is likely to respond. So I would suggest you open a new issue with reference to this one.
