### ISSUE TITLE
Gruntfile should not rely on PHP

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1793]
I'm getting an odd bug when attaching a Magento 2 volume to a nodejs task runner container and executing `grunt refresh`:

```
gruntrefresh_1 | Running "exec:all" (exec) task
gruntrefresh_1 | grunt --force clean:blank
gruntrefresh_1 | >> /bin/sh: 1: php: not found
gruntrefresh_1 | >> Exited with code: 127.
gruntrefresh_1 | Warning: Task "exec:all" failed. Use --force to continue.
gruntrefresh_1 | 
gruntrefresh_1 | Aborted due to warnings.
gruntrefresh_1 | 
gruntrefresh_1 | 
gruntrefresh_1 | Execution Time (2015-09-04 18:36:10 UTC)
gruntrefresh_1 | loading tasks  1.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
gruntrefresh_1 | exec:all       29ms  ▇▇ 2%
gruntrefresh_1 | Total 1.2s
gruntrefresh_1 | 
magento2_gruntrefresh_1 exited with code 3
```

It appears that grunt is looking for PHP, when I don't believe PHP should be required at all to run a `grunt refresh` (strictly nodejs, right?). I tried looking for `exec:all` to fix, but wasn't successful...

**Comment by markoshust** [comment]
Ahh... never mind. It appears `./bin/magento` is building out static asset content. I don't think we can get around this right now...
`
deploy = spawn('php', ['bin/magento', 'setup:static-content:deploy']);
`

**Comment by godban** [comment]
It's pretty organic if think about [Magento import directive](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css-preprocess.html#fedg_css-magento-import)

But if you don't wanna mix a worlds, you can always setup own way with separate theme and own Grunt config. It's not a mandatory.
