### ISSUE TITLE
Pressing "Enter" in "Affected Product Template" dialog reloads page

### ISSUE THREAD

**Issue by steverobbins** [magento/magento2#1794]
After taking the time to set up my first configurable product, I hit <kbd>Save</kbd> and was shown this window

![the window](https://i.imgur.com/7RZgeRS.png)

After typing in my template name, I pressed <kbd>Enter</kbd> on my keyboard, instead of clicking the <kbd>Confirm</kbd> button.  The page was reloaded and my product was not saved.

Pressing <kbd>Enter</kbd> while focussed on the text field should behave the same as clicking the <kbd>Confirm</kbd> button, or at least do nothing so that work isn't lost.

**Comment by okorshenko** [comment]
@steverobbins thank you for reporting. Internal ticket MAGETWO-42658 created to track this issue

**Comment by davidalger** [comment]
Fixed. Please reopen if issue persists.
