### ISSUE TITLE
Attribute not updated if it has more than 2000 options

### ISSUE THREAD

**Issue by Melint** [magento/magento2#17948]
### Preconditions

1. Magento 2.25
2. AWS 2 core, 8GB
3. PHP7

### Steps to reproduce

1. on the admin page **attribute** - **part_number** which has more than 2000 options
2. Use in Layered Navigation - changed from **No** to **filterable**(with results)
3. save

### Expected result

1. shows **saved** and Use in Layered Navigation - changed from **No** to **filterable**(with results)

### Actual result

1. it shows **You saved the configuration.**, but if you check the Use in Layered Navigation it still shows **No**.

**Comment by magento-engcom-team** [comment]
Hi @Melint. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Melint do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment]
@Melint, you probably just need to increase the [php configuration value `max_input_vars`](http://php.net/manual/en/info.configuration.php#ini.max-input-vars) to a higher value (default is 1000).

This isn't really a Magento bug, but a problem in the environment.
If you agree and this fixes the problem, could you close this ticket?

Thanks!

**Comment by Melint** [comment]
sure I will close IT tomorrow...Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [magento/magento2] Attribute not updated if it has more than 2000 options (#17948)From: Pieter Hoste To: magento/magento2 CC: Melint ,Mention @Melint, you probably just need to increase the php configuration value max_input_vars to a higher value (default is 1000).
This isn't really a Magento bug, but a problem in the environment.
If you agree and this fixes the problem, could you close this ticket?
Thanks!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/magento/magento2","title":"magento/magento2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/magento/magento2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hostep in #17948: @Melint, you probably just need to increase the [php configuration value `max_input_vars`](http://php.net/manual/en/info.configuration.php#ini.max-input-vars) to a higher value (default is 1000).\r\n\r\nThis isn't really a Magento bug, but a problem in the environment.\r\nIf you agree and this fixes the problem, could you close this ticket?\r\n\r\nThanks!"}],"action":{"name":"View Issue","url":"https://github.com/magento/magento2/issues/17948#issuecomment-418987392"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/magento/magento2/issues/17948#issuecomment-418987392",
"url": "https://github.com/magento/magento2/issues/17948#issuecomment-418987392",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [magento/magento2] Attribute not updated if it has more than 2000 options (#17948)",
"sections": [
{
"text": "",
"activityTitle": "**Pieter Hoste**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@hostep",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"magento/magento2\",\n\"issueId\": 17948,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"magento/magento2\",\n\"issueId\": 17948\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/magento/magento2/issues/17948#issuecomment-418987392"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 376516792\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ghost** [comment]
Hi @Melint  Closing this issue, on yours comment https://github.com/magento/magento2/issues/17948#issuecomment-418999380
