### ISSUE TITLE
No control over invoice generation

### ISSUE THREAD

**Issue by sheldmandu** [magento/magento2#17952]
### Summary
Magento currently automatically creates Invoices associated with Sales Orders when a payment for a sales order is received.  This is incorrect and this is currently the case for Braintree, PayPal and other payment methods developed by the magento core team.

The fundamental problem with this is that there is no control over it and not all merchants should have an Invoice automatically generated.

Although this may be fine for some small merchants, it is not appropriate for larger merchants that have an integration with an ERP system and follow GAAP.

In particular GAAP stipulate that revenue should NOT be recognised too early and an Invoice is fundamentally an accounting transaction that affects the P&L statement.  By creating and issuing an Invoice at the time of payment receipt for the Sales Order the merchant is effectively not following GAAP as they are recognising the revenue too early.  It is generally accepted under GAAP to recognise revenue (i.e. Issuing of Invoice) at the time of order fulfillment / shipment rather than receipt of payment.  Furthermore it results in time-separation of Revenue recognition (Invoice) and related COGS expense that is directly related to that revenue, which is also against GAAP.

Receipt of Payment for a Sales Order is actually a Balance Sheet transaction with Debit (Increase) to a Bank Account (Asset) account and a Credit (Increase) to a Customer Prepayments (Liability) account.

Invoicing and Item Fulfillment in turn result in Credit (Increase) to Sales Revenue, Debit (Decrease) in Customer Prepayments Liability, Credit (Decrease) in Inventory Asset and Debit (Increase) in COGS Expense.

Furthermore, it is possible for a Sales Order to change between the time it is received and fulfilled when stock isn't available or sold through another channel, the customer changes their mind, etc.

Where Magento is integrated with an ERP it is also generally desirable to have the ERP create the invoice and sync the invoice to Magento, rather than having the eCommerce platform try to handle accounting concepts and do so incorrectly.

If a merchant wants to generate an Invoice at the time of Payment receipt they should be allowed to do so, but at the same time they should not be forced to do so.

Similarly a refund (which is a balance sheet transaction) should not be tied to a Credit Memo (which is a P&L transaction).

This has been a constant problem and frustration for a number of larger clients with ERP integrations with Magento.

This is particularly important in the B2B space.

### Examples
Create an order and pay for it through Braintree or PayPal and see how an Invoice is automatically generated.

### Proposed solution
Implement a configuration option on the base payment method class that controls whether an Invoice is automatically generated when a payment accepted by that payment method.  Also implement and expose a Payment entity that actually keeps track of payments.

Magento already separates payments from invoices at the lower level with data stored in sales_order_payment and sales_payment_transaction so it should not be particularly difficult to show it that way.

It is also worth noting that Payments are usually applied / allocated to Invoices when an Invoice is created and it should be possible to configure the system to either automatically allocate Payments associated with Sales Orders to Invoices or to do so manually (and sync back from the backend ERP).

**Comment by magento-engcom-team** [comment]
Hi @sheldmandu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sheldmandu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sheldmandu** [comment]
I can confirm that the issues is reproduced on 2.2.5.

**Comment by ghost** [comment]
Hi @sheldmandu , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by tomekjordan** [comment]
This bevahior is present in any magento versions. M1 and M2. the funny thing is that Paypal can automatically create credit memo when order is refunded in Paypal, merchant cannot control this process. I agree, this behavior should be changed. moreover, any online payments block qty change for invoice, that block partial invoicing. even when you capture payment offline, you cannot change qty for such invoice, so you can invoice whole or order or nothing

**Comment by matin73** [comment]
Same problem for me. Shops have ERP system connected. This can also cause problem with tax office because of 2 invoices (the invoice genereted by magento is not taken in accounting)

**Comment by magento-engcom-team** [comment]
Hi @sheldmandu. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/81
