### ISSUE TITLE
Vimeo Video Gateway Problem - Will Not Play on Product Page

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#17955]
### Preconditions

1. Magento 2.1.14
2. 

### Steps to reproduce

1. Tried to play product video in the image gallery on a product page.
2.

### Expected result

1. Expect video to play.
2.

### Actual result

1. Video does not play, just spins infinitely
2. Problem is with Vimeo gateway (see attached) froogaloop2.min.js is not loading from https://secure-a.vimeocdn.com/js/froogaloop2.min.js
3. Saw this problem last week, but it resolved itself and videos were playing normal. Checked today and the gateway is not responding again.

![screen-shot-2018-09-06-at-9 33 26-am](https://user-images.githubusercontent.com/19981272/45162913-0f64ce00-b1bd-11e8-931a-c71a9236a5f5.jpg)

**Comment by magento-engcom-team** [comment]
Hi @pioneerathletics. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pioneerathletics do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pioneerathletics** [comment]
@magento-engcom-team give me {2.1.14} instance

**Comment by ghost** [comment]
Hi @pioneerathletics  you need to "give me 2.1.14 instance"

**Comment by pioneerathletics** [comment]
I don't understand what you mean by I need to "give you 2.1.14 instance"

**Comment by ghost** [comment]
@pioneerathletics  to get test instance dont use the -> {} and Magento can deploy only 2.2 and 2.3 instances

**Comment by pioneerathletics** [comment]
@magento-engcom-team  "give me 2.2.5 instance"

**Comment by ghost** [comment]
Hi @pioneerathletics I'm not able to reproduce following steps your described. Have no 504 error 
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-17955-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17955-2-2-5.engcom.dev.magento.com/admin](https://i-17955-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@pioneerathletics I'm not able to reproduce on vanilla instance. can i close issue ?

**Comment by pioneerathletics** [comment]
@magento-engcom-team I noticed that it is working again. Here's the thing, last week it had the same problem connecting to the gateway, then resolved itself, only to have the same problem this week.
Should I reopen if it happens again?

**Comment by ghost** [comment]
@pioneerathletics No this issue not related to magento .

**Comment by Abdulkadiragoliya** [comment]
if you have used magiczoomplus then please update 
app\code\MagicToolbox\MagicZoomPlus\view\frontend\web\js\thumb-switcher.js

and replace   https://secure-a.vimeocdn.com/js/froogaloop2.min.js 
with
https://f.vimeocdn.com/js/froogaloop2.min.js

**Comment by tuyennn** [comment]
MAGETWO-94202: Video is displayed as image and can't be played

```
From cc4e2fa2b498d7e041d58a7237307636b27e79c9 Mon Sep 17 00:00:00 2001
From: tuyennn <thinghost76@gmail.com>
Date: Wed, 25 Nov 2020 17:57:44 +0700
Subject: [PATCH] MAGETWO-94202: Video is displayed as image and can't be
 played

---
 .../view/frontend/web/js/fotorama-add-video-events.js           | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/vendor/magento/module-product-video/view/frontend/web/js/fotorama-add-video-events.js b/vendor/magento/module-product-video/view/frontend/web/js/fotorama-add-video-events.js
index edf02c197..3966321f6 100644
--- a/vendor/magento/module-product-video/view/frontend/web/js/fotorama-add-video-events.js
+++ b/vendor/magento/module-product-video/view/frontend/web/js/fotorama-add-video-events.js
@@ -450,7 +450,7 @@ define([
                 scriptTag = document.getElementsByTagName('script')[0];
 
             element.async = true;
-            element.src = 'https://secure-a.vimeocdn.com/js/froogaloop2.min.js';
+            element.src = 'https://f.vimeocdn.com/js/froogaloop2.min.js';
 
             /**
              * Vimeo js framework on load callback.
-- 
2.25.1

```
