### ISSUE TITLE
Cant add product to cart

### ISSUE THREAD

**Issue by dungdk** [magento/magento2#1798]
I have try add product to cart, but ajax loading about 3s then nothing happen.
I am using version develop version 1.0.0-beta.

**Comment by okorshenko** [comment]
@dungdk, thank you for reporting. 
Could you, please, add more details about the issue? 
- system configuration changes
- used Theme
- used product types
- any code customizations

**Comment by dungdk** [comment]
@okorshenko , yep sure.
Browser: chrome. (Firefox still works).
Theme: Luma
Product type: all
No customize any code.

**Comment by okorshenko** [comment]
@dungdk, thank you for additional information. Internal ticket is created MAGETWO-42593 to track this issue.

**Comment by Schoeny1** [comment]
I am having a similar issue, however the only browser working for me is Chrome.  I cannot add to cart in IE or Firefox.  Fresh install, same beta version.  Firefox gives the message: Unable to send the cookie. Maximum number of cookies would be exceeded.  IE says "added" when I click add to cart, but nothing is in the basket.

**Comment by okorshenko** [comment]
@Schoeny1 thank you for additional information

**Comment by okorshenko** [comment]
@dungdk , This issue was fixed in https://github.com/magento/magento2/commit/0a87feb0e3b35e758115719ad75ab113eed00a19. Please, let us know if you still have an issue
