### ISSUE TITLE
Problem in sending mail 

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#1799]
This is my email function but giving error :- 
Invalid sender data
#0 /home/cedcommerce/public_html/demo/magento2/extensions/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php(160): Magento\Email\Model\Template\SenderResolver->resolve('aishwarya@cedco...')
#1 /home/cedcommerce/public_html/demo/magento2/extensions/app/code/Ced/ReferAFriend/Model/Invitations.php(71): Magento\Framework\Mail\Template\TransportBuilder->setFrom('aishwarya@cedco...', 'Aishwarya')

FUNCTION :- 
public function sendEmail($invitation)
    {
       
    	$baseUrl=$this->getBaseUrl();
    	$Email_id=$invitation['email'];
    	$subject=$invitation['subject'];
    	$message=$invitation['message'];
    	
    	$store_id="1";
    
	
    	$customer=$this->customerSession->getCustomer();
    	$customer_id=$this->customerSession->getCustomerId();
    	$customer_email=$customer->getEmail();
    	$customer_name=$customer->getName();

    	$baseUrl=$this->getBaseUrl()."customer/account/create/id/".$customer_id;
    	$templateParams=['customer' => $Email_id, 'store' => $store_id,'subject' =>$subject,'message' => $message,'Website_link'=>$baseUrl];
         try{
    	$transport = $this->_transportBuilder->setTemplateIdentifier(
    		$this->_scopeConfig->getValue(self::XML_PATH_FORGOT_EMAIL_TEMPLATES, \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $store_id)
        )->setTemplateOptions(
     		['area' => \Magento\Framework\App\Area::AREA_FRONTEND, 'store' => $store_id]
        )/*->setTemplateVars(
    		$templateParams
    )*/ ->setFrom(
            'aishwarya@cedcoss.com',
             'Aishwarya'
           
    		 
    ) ->addTo(
    		$Email_id,
            'Friend'
    )->getTransport();
    }
    catch(Exception $e){
        echo $e->getMessage();
    }
     $transport->sendMessage(); 
    }
}

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
