### ISSUE TITLE
problem rest authentication

### ISSUE THREAD

**Issue by Antonioele** [magento/magento2#1800]
I request token for an admin user
curl -X POST "http://localhost/magento21/index.php/rest/V1/integration/admin/token" \
>      -H "Content-Type:application/json" \
>      -d '{"username":"admin", "password":"antonioxxx"}'
Magento respond:
"hlvqig3je87vfg9w3s3cjpqegewxc6e0"
I would view the customers :
curl -X GET "http://localhost/magento21/index.php/rest/V1/customers/me" \ -H "Authorization: Bearer hlvqig3je87vfg9w3s3cjpqegewxc6e0"
answer:
{"message":"Consumer is not authorized to access %resources","parameters":{"resources":"self"}}
Why I have token admin???????????????

**Comment by kandy** [comment]
Looks like you use admin account to request customer resource. 
Use /V1/integration/customer/token to login as customer or use /customers/ endpoint with admin rights.

**Comment by Antonioele** [comment]
@kandy  Credential admin to login  for request   rest consumer return same message 
{"message":"Consumer is not authorized to access %resources","parameters":{"resources":"self"}}
Perhaps hte problem is:I not  use the protocol https but http

**Comment by Antonioele** [comment]
@kandy  thanks the role of admin not set now works

**Comment by vaimeo** [comment]
i have problem my user is admin its working fine on Magento admin but not working when i request for token You did not sign in correctly or your account is temporarily disabled.
