### ISSUE TITLE
No ajax interruption for large import.

### ISSUE THREAD

**Issue by armababy** [magento/magento2#1804]
Hello,

When importing file too large set by server (in this case nginx) and/or php, ajax responds with 413 (Request Entity Too Large) which is correct
But "Please wait" animation/spinner never goes away and problem is not reflected to the user screen.

Just a minor bummer, but still :)

**Comment by piotrekkaminski** [comment]
internal id MAGETWO-43853

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#60
