### ISSUE TITLE
Import data 2.2.5   Value for 'product_type' attribute contains incorrect value

### ISSUE THREAD

**Issue by valuead** [magento/magento2#18052]
fresh install 2.2.5 with the template and sample data 
Exporting products from the live store and can't re-import them back right away because impossible to pass data validation check without cvs file modification. 
file cvs utf8 English language unix

the same thing happens when downloading sample data link at the Import section (Download Sample File) and can't pass data validation check because of  Value for 'product_type' attribute contains incorrect value all through the is a word simple without spaces and capitalization. 

If you remove word simple strangely you will **pass** data check validation and system will offer you to import. When you click on Import you will get the same issue Value for 'product_type' attribute contains an incorrect value right during the import.

More information and screenshots where posted in the community forum here https://community.magento.com/t5/Magento-2-x-Programming/Magento2-Import-sample-data-ERROR/m-p/105097#M5684
![imp1](https://user-images.githubusercontent.com/9205462/45525693-ef1eab80-b788-11e8-946d-4689d65b166c.PNG)
![imp2](https://user-images.githubusercontent.com/9205462/45525694-ef1eab80-b788-11e8-8852-6b8ff75a97ac.PNG)
![import1](https://user-images.githubusercontent.com/9205462/45525695-efb74200-b788-11e8-90cf-8f205e87c750.PNG)
![import2](https://user-images.githubusercontent.com/9205462/45525697-efb74200-b788-11e8-9c8d-d90c0d1da495.PNG)
![import3](https://user-images.githubusercontent.com/9205462/45525698-efb74200-b788-11e8-9753-02910a1bb403.PNG)

**Comment by magento-engcom-team** [comment]
Hi @valuead. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@valuead do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @valuead i'm not able to reproduce following steps you described.

![selection_086](https://user-images.githubusercontent.com/40756439/45535564-8e828380-b807-11e8-96ab-b3e0dafc08f0.png)


Unfortunately we can not provide any help for the reports not containing all required information. Please update the report and reopen if the issue persists.

**Comment by valuead** [comment]
can you please attach your import file for testing. the same one you used and can't reproduce. I'm gonna run it thru my install.

**Comment by ghost** [comment]
@valuead You can download by link In your screen-> "Download Sample file".

**Comment by valuead** [comment]
just now 
1. download file
2. import. What could be wrong?
![import4](https://user-images.githubusercontent.com/9205462/45538088-e9da5480-b7ba-11e8-911d-8a7b0ad42b52.PNG)

**Comment by ghost** [comment]
@valuead Please see if you have website with code "base".

**Comment by valuead** [comment]
well I did play with it and now I'm getting this and I heard this is a common issue of duplicated headers?

Yes, I'm aware of the website code, thank you for raising that up. I must admit I did misspell it. 

this is a new error now. 
Duplicates found in column names: array ( 0 => 'sku', 1 => 'store_view_code', 2 => 'attribute_set_code', 3 => 'product_type', 4 => 'categories', 5 => 'product_websites', 6 => 'name', 7 => 'description', 8 => 'short_description', 9 => 'weight', 10 => 'product_online', 11 => 'tax_class_name', 12 => 'visibility', 13 => 'price', 14 => 'special_price', 15 => 'special_price_from_date', 16 => 'special_price_to_date', 17 => 'url_key', 18 => 'meta_title', 19 => 'meta_keywords', 20 => 'meta_description', 21 => 'created_at', 22 => 'updated_at', 23 => 'new_from_date', 24 => 'new_to_date', 25 => 'display_product_options_in', 26 => 'map_price', 27 => 'msrp_price', 28 => 'map_enabled', 29 => 'gift_message_available', 30 => 'custom_design', 31 => 'custom_design_from', 32 => 'custom_design_to', 33 => 'custom_layout_update', 34 => 'page_layout', 35 => 'product_options_container', 36 => 'msrp_display_actual_price_type', 37 => 'country_of_manufacture', 38 => 'additional_attributes', 39 => 'qty', 40 => 'out_of_stock_qty', 41 => 'use_config_min_qty', 42 => 'is_qty_decimal', 43 => 'allow_backorders', 44 => 'use_config_backorders', 45 => 'min_cart_qty', 46 => 'use_config_min_sale_qty', 47 => 'max_cart_qty', 48 => 'use_config_max_sale_qty', 49 => 'is_in_stock', 50 => 'notify_on_stock_below', 51 => 'use_config_notify_stock_qty', 52 => 'manage_stock', 53 => 'use_config_manage_stock', 54 => 'use_config_qty_increments', 55 => 'qty_increments', 56 => 'use_config_enable_qty_inc', 57 => 'enable_qty_increments', 58 => 'is_decimal_divided', 59 => 'website_id', 60 => 'deferred_stock_update', 61 => 'use_config_deferred_stock_update', 62 => 'related_skus', 63 => 'crosssell_skus', 64 => 'upsell_skus', 65 => 'hide_from_product_page', 66 => 'custom_options', 67 => 'bundle_price_type', 68 => 'bundle_sku_type', 69 => 'bundle_price_view', 70 => 'bundle_weight_type', 71 => '', 72 => '', 73 => '', 74 => '', 75 => '', 76 => '', 77 => '', 78 => '', 79 => '', 80 => '', 81 => '', 82 => '', 83 => '', )

**Comment by ghost** [comment]
@valuead is that in sample file ? Can you verify this in vanilla instance ?

**Comment by valuead** [comment]
yes, this is in a sample file. I'm sorry I'm not aware of vanilla instance

**Comment by ghost** [comment]
@valuead seems strange, maybe something wrong with yours instance, seems like some attributes are required in csv file, or something else,

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-18052-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18052-2-2-5.engcom.dev.magento.com/admin](https://i-18052-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@valuead Here you vanilla instance, try same on this instance

**Comment by valuead** [comment]
https://dropmefiles.com/kZ4Jt <--- CSV  sample data file with my website code. I use base but still the same 

![fail](https://user-images.githubusercontent.com/9205462/45541414-e5666980-b7c3-11e8-84c7-d0de4e42ee6c.PNG)

**Comment by engcom-backlog-nazar** [comment]
@valuead which version of magento this csv file ?

**Comment by ghost** [comment]
@valuead Ok i'm found the problem :) your file seems to be broken, i upload the sample file an everything is ok , and with yours have an error

**Comment by ghost** [comment]
@valuead 

![selection_091](https://user-images.githubusercontent.com/40756439/45542346-4587fa80-b81a-11e8-939a-7f7b6afea590.png)

**Comment by valuead** [comment]
cat composer.json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.2.5",
    "license": [
        "OSL-3.0",
        "AFL-3.0"

**Comment by valuead** [comment]
Do you mean my install erroring out or I have bad csv file?

**Comment by ghost** [comment]
@valuead  Problem in your csv file not in magento, the code website may not contain the "_" character.

**Comment by valuead** [comment]
why is it allowing to enter that? to mee, this is Magento issue and not the csv cause we place in csv that we see in Magento interface. I will try to change and will report back soon.

**Comment by valuead** [comment]
Changed the website codes as you told me to.
Created a new product, export it out and trying to import 
1 item ))) still the same error 
Here is the file with 1 record I'm trying to import. https://dropmefiles.com/xv5sk
Test product in file on the site http://usawheelchair.com/test.html
![imp1](https://user-images.githubusercontent.com/9205462/45577687-01085900-b832-11e8-99ae-80f6d41f4707.PNG) and 
![imp2](https://user-images.githubusercontent.com/9205462/45577824-e8e50980-b832-11e8-8859-c992d7780b76.PNG)

**Comment by valuead** [comment]
I wipeout mageto and reinstall it fresh. I'm having the same issue. I even try to use replace instead of add/replace with the same error message. I may offer someone login to my admin to see what's up. this is getting silly. nothing important in that test server. please advice.

**Comment by valuead** [comment]
SURPRISE  I was able to delete that record with that file... amazing. no luck with add or replace ...

**Comment by ankit-sf** [comment]
Hello @valuead and @engcom-backlog-nazar  in my case issue occurs when you also have an attribute with code product_type.
http://i.prntscr.com/AwUJuhizQKatBwNwRa1S7Q.png

**Comment by ankit-sf** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @ankit-sf. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ankit-sf, here is your [Magento instance](https://i-18052-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-18052-2-2-6.instances.magento-community.engineering/admin](https://i-18052-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ankit-sf** [comment]
issue reproduced on magento 2.2.6
http://i.prntscr.com/OZuGKogQQVeCHpU2Am4jTA.png

Added new issue with better description and format
https://github.com/magento/magento2/issues/19346

**Comment by valuead** [comment]
Please send me your file vlad @ valuead.com and I will help you. Could be multiple things

**Comment by ankit-sf** [comment]
> vlad @ valuead.com

hello @valuead ,
i tried with import after downloading sample file present at import page in magento2 admin after
 trying steps given at https://github.com/magento/magento2/issues/19346 and you can reproduce it easily.
thanks
