### ISSUE TITLE
Event does not exist in Magento Framework

### ISSUE THREAD

**Issue by adesigner2** [magento/magento2#1805]
We are trying to move extension to magento 2 and find out that here is 'view_block_abstract_to_html_before' in \Magento\Framework\View\Element\AbstractBlock in toHtml(), but here is no 'view_block_abstract_to_html_after' in end of toHtml() which dispatched when block is generated - which is quite useful if we need to control results of specific blocks. Is here any plans to add it release version of magento 2? It is extremely useful feature which exist in magento 1.x.x.

**Comment by akaplya** [comment]
you may use plugin to define after[Method] behavior  http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
