### ISSUE TITLE
Installation is Incomplete

### ISSUE THREAD

**Issue by modkore** [magento/magento2#18070]
### Preconditions

Magento version is 2.2.5

### Steps to reproduce

1. Install Magento 2.2.5 to the root
2. Upload demo media files to the root
3. Upload demo pub files to the root
4. Create empty database and upload the premium theme database dump.
5. Upload 2.2.5 theme patch
6. Clear Browser Cache
7. Install the magento domain.com/setup/

### Expected result
Installation is incomplete. 
Check the console log for errors before trying again.
### Actual result

[ERROR] Zend_Db_Exception: There is no field "attribute_group_code" that you are trying to create an index on "eav_attribute_group" in /home/abcshopph/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:2655
Stack trace:
#0 /home/abcshopph/public_html/vendor/magento/module-eav/Setup/UpgradeSchema.php(49): Magento\Framework\DB\Adapter\Pdo\Mysql->addIndex('eav_attribute_g...', 'CATALOG_CATEGOR...', Array, 'unique')
#1 /home/abcshopph/public_html/vendor/magento/module-eav/Setup/UpgradeSchema.php(26): Magento\Eav\Setup\UpgradeSchema->addUniqueKeyToEavAttributeGroupTable(Object(Magento\Setup\Module\Setup))
#2 /home/abcshopph/public_html/setup/src/Magento/Setup/Model/Installer.php(864): Magento\Eav\Setup\UpgradeSchema->upgrade(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#3 /home/abcshopph/public_html/setup/src/Magento/Setup/Model/Installer.php(767): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#4 [internal function]: Magento\Setup\Model\Installer->installSchema()
#5 /home/abcshopph/public_html/setup/src/Magento/Setup/Model/Installer.php(334): call_user_func_array(Array, Array)
#6 /home/abcshopph/public_html/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#7 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#17 /home/abcshopph/public_html/setup/index.php(35): Zend\Mvc\Application->run()
#18 {main}

**Comment by magento-engcom-team** [comment]
Hi @modkore. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@modkore do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by marcelo-monteiro** [comment]
@modkore this is not a bug, this an environment issue. You can have support to install this magento version at slack channel (faster communication):
to sign-up at channel slack: tinyurl.com/engcom-signup
https://magentocommeng.slack.com/messages/C4YS78WE6
Or check in the forum, maybe someone already faced this issue, also you can ask for help there:
https://community.magento.com/
