### ISSUE TITLE
how to use DI  when argument (xsi:type="array")  and item is function like strtoupper('MD5');

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1807]

**Comment by LifeAsBook** [comment]
@buskamuza   ![1](https://cloud.githubusercontent.com/assets/10986726/9705269/e8616424-54f1-11e5-9479-83ab30d29cd0.jpg)

**Comment by kandy** [comment]
Configuration should be declarative. I you need same imperative instruction like getcwd(), please put it to class constructor

**Comment by alankent** [comment]
To expand slightly, the di.xml file contains strings when xsi:type="string", not PHP code that is executed to return a string.  The di.xml file allows you to specify constants in the config file, not PHP code to execute. As soon as you want to execute code, you need to work out a solution yourself - dependency injection is not trying to replace writing code.  For example, make the cacert string a path name. If absolute, use it; if relative, then prepend the current working directory if you need to make it absolute. Don't expect the di.xml to solve this for you. (As Mr Kandy said, please make your configuration declarative.)

**Comment by LifeAsBook** [comment]
thank you!
