### ISSUE TITLE
Magento 2.2.1 Error During Install 

### ISSUE THREAD

**Issue by modkore** [magento/magento2#18071]
### Preconditions

Magento Version is 2.2.1

### Steps to reproduce

1. Create empty database upload demo theme 2.2.1 sql dump
2. Upload the magento 2.2.1 quickstart to the root of cpanel
3. Run the magento setup
4. Error will show up around Installing... 75%

### Expected result
Installation is incomplete. 
Check the console log for errors before trying again.

### Actual result

[ERROR] Exception: Warning: Error while sending QUERY packet. PID=1655958 in /home/abcshopph/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228 in /home/abcshopph/public_html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Error while sen...', '/home/abcshopph...', 228, Array)
#1 /home/abcshopph/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#2 /home/abcshopph/public_html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#3 /home/abcshopph/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#4 /home/abcshopph/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#5 /home/abcshopph/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#6 /home/abcshopph/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#7 /home/abcshopph/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#8 /home/abcshopph/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#9 /home/abcshopph/public_html/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#10 /home/abcshopph/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(774): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#11 /home/abcshopph/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(670): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#12 /home/abcshopph/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(574): Magento\Framework\Data\Collection\AbstractDb->getData()
#13 /home/abcshopph/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(559): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#14 /home/abcshopph/public_html/vendor/magento/framework/Data/Collection.php(298): Magento\Framework\Data\Collection\AbstractDb->load()
#15 /home/abcshopph/public_html/vendor/magento/module-theme/Model/ResourceModel/Theme/Collection.php(141): Magento\Framework\Data\Collection->getFirstItem()
#16 /home/abcshopph/public_html/vendor/magento/module-theme/Model/Theme/Registration.php(146): Magento\Theme\Model\ResourceModel\Theme\Collection->getThemeByFullPath('frontend/Magent...')
#17 /home/abcshopph/public_html/vendor/magento/module-theme/Model/Theme/Registration.php(95): Magento\Theme\Model\Theme\Registration->getThemeFromDb('frontend/Magent...')
#18 /home/abcshopph/public_html/vendor/magento/module-theme/Model/Theme/Registration.php(73): Magento\Theme\Model\Theme\Registration->_registerThemeRecursively(Object(Magento\Theme\Model\Theme\Data))
#19 /home/abcshopph/public_html/vendor/magento/module-theme/Setup/RecurringData.php(41): Magento\Theme\Model\Theme\Registration->register()
#20 /home/abcshopph/public_html/setup/src/Magento/Setup/Model/Installer.php(895): Magento\Theme\Setup\RecurringData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#21 /home/abcshopph/public_html/setup/src/Magento/Setup/Model/Installer.php(791): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#22 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#23 /home/abcshopph/public_html/setup/src/Magento/Setup/Model/Installer.php(342): call_user_func_array(Array, Array)
#24 /home/abcshopph/public_html/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#25 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#26 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#27 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#28 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#29 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#30 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#31 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#32 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#33 /home/abcshopph/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#34 /home/abcshopph/public_html/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#35 /home/abcshopph/public_html/setup/index.php(35): Zend\Mvc\Application->run()
#36 {main}

**Comment by magento-engcom-team** [comment]
Hi @modkore. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@modkore do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by marcelo-monteiro** [comment]
@modkore this is not a bug, this an environment issue. You can have support to install this magento version at slack channel (faster communication):
to sign-up at channel slack: tinyurl.com/engcom-signup
https://magentocommeng.slack.com/messages/C4YS78WE6
Or check in the forum, maybe someone already faced this issue, also you can ask for help there:
https://community.magento.com/
