### ISSUE TITLE
Switching off FPC causes config key collision (beta)

### ISSUE THREAD

**Issue by amenk** [magento/magento2#1808]
Steps to reproduce:

1. Disable a cache (full page cache in backend)
2. Now the cache settings are written to `env.php`
3. On the next page view, I get the following error:

		exception 'Exception' with message 'Key collision! The following keys occur in multiple config files: cache_types 
		' in /home/me/workspace/example.com/public/lib/internal/Magento/Framework/App/DeploymentConfig/Reader.php:91 Stack
		 trace: #0 /home/me/workspace/example.com/public/lib/internal/Magento/Framework/App/DeploymentConfig.php(130):
		 Magento\Framework\App\DeploymentConfig\Reader->load() #1 /home/me/workspace/example.com/public/lib/internal/Magento
		/Framework/App/DeploymentConfig.php(72): Magento\Framework\App\DeploymentConfig->load() #2 /home/me/workspace/example.com
		/public/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(112): Magento\Framework\App\DeploymentConfig->get() #3 
		/home/me/workspace/example.com/public/lib/internal/Magento/Framework/App/Bootstrap.php(384): Magento\Framework\App
		\ObjectManagerFactory->create(Array) #4 /home/me/workspace/example.com/public/lib/internal/Magento/Framework/App/Bootstrap.php(231): 
		Magento\Framework\App\Bootstrap->initObjectManager() #5 /home/me/workspace/example.com/public/index.php(38): 
		Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...') #6 {main}

What I saw is, that the cache_types section is in `env.php` as well as `config.php`. I actually was expecting, that config file merging / overwriting of values should work?

**Comment by mazhalai** [comment]
@amenk This error happens if you had an older version of magento 2 when config was saved only in config.php. Now config.php only has module related info. There is no way to accurately determine which is the correct set and can overwrite values.

**Comment by amenk** [comment]
I started with the merchant beta ...

**Comment by mazhalai** [comment]
@amenk can you give us detailed steps to reproduce this issue? We are having trouble reproducing it.

**Comment by amenk** [comment]
As far as I remember, I did a composer based installation of Magento and then tried to change the cache settings.

**Comment by monkeysee** [comment]
@amenk , I tried to reproduce, but could not.  The steps I tried were:

1.  composer create-project magento/project-community-edition --stability="beta" magento2Proj
2.  Ran through the setup wizard
3.  Examined config files
  * app/etc/config.php, only contains array of enabled modules
  * app/etc/env.php contains other settings, including 'full_page' => 1 in cache_types array
4.  Went to admin and disabled full page cache
5.  Went to front end, pages loaded OK
6.  Went to other pages in Admin, they are OK also
7.  examined config files:
  * app/etc/config.php, still only contains array of enabled modules
  * app/etc/env.php contains other settings, including 'full_page' => 0 in cache_types array

There was a time when we only had config.php, and all settings were in there.  When we split the config it was necessary to reinstall to get everything in the right place. Is it possible you had an old version of config.php? or some files in the var/generation directory from an older install?  You shouldn't have anything else in config.php other than the array of modules.

env.php and config.php are not merged, rather they have different entries in them. If you have the same entry in both, then you see the error you are getting.

**Comment by amenk** [comment]
I am having "magento/product-community-edition": "1.0.0-beta" - when I install now it is -beta2
Maybe there was that change?

**Comment by amenk** [comment]
This is all pretty confusing as there are no -beta1 and -beta2 tags in this (magento/magento2/) github repository...

**Comment by monkeysee** [comment]
I tried with the 1.0.0-beta and still no failure. The split of the config files took place before 1.0.0-beta. Did you ever install before 1.0.0-beta?
If you edit the config files so that config.php only has the 'modules' array, and env.php has everything else, it should work on 1.0.0-beta and beyond.

**Comment by amenk** [comment]
I did a fresh installation at 2015-08-24. I will try to edit the config files and see what happens.

**Comment by amenk** [comment]
I am not sure, but I might have tried to switch caching with `n98-magerun2.phar` - maybe there is or was an issue.

**Comment by amenk** [comment]
Putting the cache config to env.php solved the problem.
So it's not reproducible. Not worth the effort. I am closing this.
@monkeysee thanks a lot for your help.

**Comment by monkeysee** [comment]
NP, @amenk, glad you got it going. We'll keep an eye out for this in the future.
