### ISSUE TITLE
How to VIewfileUrl in Magento2 on Model

### ISSUE THREAD

**Issue by aishwaryacedcoss** [magento/magento2#1810]
Please tell me the extended class in model to get View file url .???

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
