### ISSUE TITLE
command line option to clear static assets

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1811]
There is a flag on the `./bin/magento module:enable` command: `--clear-static-content`

Unfortunately, this only appears to be on the module-enable option. If static assets are desired to be cleared at any other time, this isn't an option.

I believe there should be a new command under `./bin/magento` that just clears this static content, something like:
`./bin/magento cache:clear-static-content`

I'm not sure if static assets are considered a cached asset, so this may need some revision.

Thanks!
Mark

**Comment by xcomSteveJohnson** [comment]
Fair point. There is one other time that static view files are cleared: switching from developer <> production modes.

http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html

**Comment by godban** [comment]
@markoshust there is `grunt clean`, maybe would be helpful

**Comment by alankent** [comment]
We need this separation potentially for automated deployment pipelines. Grunt might be  a short term workaround, but must not be mandatory for that (e.g. switching from dev to prod mode). We should have a separate magento command if its needed. We have been introducing these CLI commands to avoid "oh, for use case X remove directory Y" - we want it to be "for use case X run command Y" so if we change things internally related to "use case X", we can adjust "command Y" to follow the new rules without breaking existing deployment pipelines.

**Comment by tdgroot** [comment]
Really missing this feature as well, people shouldn't be removing directories when deploying..
Thinking about creating my own pull request to get it on the rails asap.

**Comment by mbrinton01** [comment]
Created internal issue MAGETWO-57193 to track this suggestion

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/command-line-option-to-clear-static-assets/idi-p/46935).
