### ISSUE TITLE
documentation for implementing date & time selectors

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1812]
There is no documentation (or reference to other documentation) on implementing date & time selectors from the admin pattern library:

http://devdocs.magento.com/guides/v2.0/pattern-library/getting-user-input/date_time_selector/date_time_selector.html

**Comment by almarchenko** [comment]
Hi!

This is implemented using the standard jQuery UI timepicker widget https://jqueryui.com/datepicker/ + addon https://github.com/magento/magento2/blob/develop/lib/web/jquery/jquery-ui-timepicker-addon.js

**Comment by markoshust** [comment]
Thank you very much -- it might be worth noting that in the pattern library and linking to the api documentation http://api.jqueryui.com/datepicker/

**Comment by markoshust** [comment]
I'm going to reopen this issue -- there appears to be some Magento2 magic going on behind the scenes, and it's very unclear what is going on with the datepicker, and how styles are pulled into the admin pages. I really think we need some clear documentation on this, along with how to implement all of the different time pickers.

**Comment by almarchenko** [comment]
>Thank you very much -- it might be worth noting that in the pattern library and linking to the api 
Yeah, definitely you are right. There are several teams working on docs, we'll contact the team which authored the Admin Pattern Library.
> I'm going to reopen this issue... I really think we need some clear documentation on this
We'll create a ticket for adding detailed docs, but we'll need some time to write and publish them.
Do you mind if we close this issue, once the internal once is created?

**Comment by markoshust** [comment]
Sure no prob

**Comment by almarchenko** [comment]
I've added links http://devdocs.magento.com/guides/v2.0/pattern-library/getting-user-input/date_time_selector/date_time_selector.html#implementation
+ the task of creating a detailed docs is in progress. 
Thank you!

**Comment by markoshust** [comment]
Can we re-open this ticket? This is not complete. I still don't know how to implement the this, as there is no documentation.

**Comment by daim2k5** [comment]
Can you explain what we need to complete the task?

**Comment by markoshust** [comment]
We need code examples to show how to use the datepicker with an input field, for all variations (ex. Single Time Picker, Date Range Picker, Horizontal stacked, Vertical stacked... all of them, how to implement), for both Admin and Frontend implementations.

**Comment by tanberry** [comment]
Agreed, we need to expand the docs, and include code snippets and real-life examples. We will prioritize this for immediately post-GA work. Thanks @markoshust, please keep the feedback coming; I hope you plan on watching the Keynote at MLAustralia next week! ;-)

**Comment by tanberry** [comment]
Oh, forgot to mention, DevDocs welcomes contributions of topics (complete topics, paragraphs, code examples, edits, added sentences, anything we can get) from the community. We have a sign-up sheet (http://devdocs.magento.com/guides/v2.0/howdoi/howdoi_contribute.html) specifically for How To topics, but we would welcome any topics, and any edits, clean-up etc of existing topics. Just do a PR and help any way that you can. Community-driven docs. ;-) 

Thanks also @daim2k5 for helping out with moderation, labels, etc. "Up for Grabs" is my favorite. ;-)

**Comment by almarchenko** [comment]
Internal issue magetwo-47806

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/documentation-for-implementing-date-amp-time-selectors/idi-p/48481).

**Comment by tanberry** [comment]
We can keep the internal DevDocs ticket, and try to push it through, possibly as part of the upcoming Frontend docs push. Your longstanding request is not lost, @markoshust ... just in a new home. ;-)

**Comment by qwerty7869** [comment]
We also want to use Magento 2 default DateTime picker on the frontend in input field but can't implement without its sample code snippets  .Please share the documentation for DateTime picker implementation so we can start using in our projects.

**Comment by tanberry** [comment]
We've moved to an internal ticket (MAGETWO-58288) and are working this now. Thanks for your persistence/patience. ;-) @almarchenko

**Comment by almarchenko** [comment]
Hi @qwerty7869 , @markoshust 
Do you need info about using datepicker via the Field UI component (date input in Admin forms are implemented like this) or simply using the widget?
In other words, was your request about improving the  http://devdocs.magento.com/guides/v2.1/javascript-dev-guide/widgets/widget_calendar.html doc, or about the absence of the comprehensive doc about Field UI comp?
We will add the latter in any case, but I would like to know your opinion if the calendar widget doc is good enough.

Thank you.

**Comment by markshust** [comment]
@almarchenko there is information about the widget themselves, but not how to use them. how would we use them in a module?

**Comment by almarchenko** [comment]
@markoshust Thanks, I got it!

**Comment by rparsi-commer** [comment]
@almarchenko Why is the internal mage ticket marked as done?
I don't see any update in the developer docs regarding this.

I have this in my knockoutjs html template:
```
<input type="text"
                           id="gift-message-whole-delivery-date"
                           class="input-text"
                           data-bind="datepicker: getObservable('deliveryDate'),
                           value: getObservable('deliveryDate'),
                           datePickerOptions: {
                            dateFormat: 'yy-mm-dd',
                            changeMonth: true,
                            changeYear: true,
                            maxDate: new Date(),
                            datePickerPlaceholder: 'yy-mm-dd'
                            }">
```

What should it be so that the user can pick a date AND time?

**Comment by alfredo4c** [comment]
Hello, 

when I found this description [Date and Time Selector](https://devdocs.magento.com/guides/v2.0/pattern-library/getting-user-input/date_time_selector/date_time_selector.html#implementation) I though something like this would come next to every example `<source_model>Magento\Config\Model\Config\Source\Date\Short</source_model>`
