### ISSUE TITLE
Magento 2 1.0.0-beta Merchant Beta1 - Webinstaller / Console Installer - Error "Database user does not have enough privileges"

### ISSUE THREAD

**Issue by magentofaz** [magento/magento2#1813]
Since the Magento 2 1.0.0-beta, the webinstaller and "console installer" doesn't work anymore at the step adddatabase, I always have the message "Database user does not have enough privileges.". Since previous beta/alpha versions of Magento 2 we use GRANT ALL PRIVILEGES ON `synbshop\_%`.* TO 'synbshop'@'localhost' WITH GRANT OPTION, and now the % is not interpreted. So to bypass this we need to put each database in the GRANT (for exemple GRANT ALL PRIVILEGES ON `synbshop_faz_magento2merchant1`.* TO 'synbshop'@'localhost' WITH GRANT OPTION). Our MySql version is 5.6.23-72.1.

Can you fix it ? or find a workaround ?

**Comment by xcomSteveJohnson** [comment]
This way has always worked for me:
GRANT ALL ON magento.* TO magento@localhost IDENTIFIED BY 'magento';

**Comment by magentofaz** [comment]
The problem is on the joker % . On your exemple you specify a database name with GRANT ALL, in development context all databases are named like synbshop_mydatabasename. This type of syntax worked on the magento2-0740beta9 version, what do you suggest ?

**Comment by magentofaz** [comment]
After quick test on magento2-0740beta16, this type of syntax also worked. 

I have compared the file DbValidatorTest.php (in setup/src/Magento/Setup/Test/Unit/Validator) in magento2-0740beta16 and magento2-merchant1, it seems the function testCheckDatabaseConnectionNotEnoughPrivileges only exist in merchant1 version and it brings this bug.

**Comment by mazhalai** [comment]
@magentofaz thank you for the details, we have created MAGETWO-42678 to track this fix internally.

**Comment by scholtz** [comment]
I confirm this is not fixed yet.

I did clear installation from git as is described in the manual.

I did create new magento user and database through phpmyadmin by creating user, and clicking the checkbox "create database with the same name" .. it grants all permissions to database for this user, but does not grant it any global permissions. After granting some global permissions the installation moved on, however i clicked ctrl-c in process and it did not create database structure correctly, and now it fails.. now i have to find out how to clear cache or something.. 

php magento --version shows only "Magento CLI version 1.0.0-beta" not version of magento installed, but these are currently installed packages by composer (you can consider not showing a magento version through console as suggestion for improvement)

braintree/braintree_php            2.39.0        Braintree PHP Client Library
composer/composer                  1.0.0-alpha10 Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
doctrine/instantiator              1.0.5         A small, lightweight utility to instantiate objects in PHP without invoking their constructors
fabpot/php-cs-fixer                v1.10.1       A tool to automatically fix PHP code style
justinrainbow/json-schema          1.5.0         A library to validate a json schema.
league/climate                     2.6.1         PHP's best friend for the terminal. CLImate allows you to easily output colored text, special formats, and more.
lusitanian/oauth                   v0.7.0        PHP 5.3+ oAuth 1/2 Library
magento/composer                   1.0.2         Magento composer library helps to instantiate Composer application and run composer commands.
magento/magento-composer-installer 0.1.5         Composer installer for Magento modules
magento/zendframework1             1.12.16       Magento Zend Framework 1
monolog/monolog                    1.16.0        Sends your logs to files, sockets, inboxes, databases and various web services
oyejorge/less.php                  v1.7.0.3      PHP port of the Javascript version of LESS http://lesscss.org
pdepend/pdepend                    2.0.6         Official version of pdepend to be handled with Composer
pelago/emogrifier                  v0.1.1        Converts CSS styles into inline style attributes in your HTML code
phpmd/phpmd                        2.3.2         PHPMD is a spin-off project of PHP Depend and aims to be a PHP equivalent of the well known Java tool PMD.
phpseclib/phpseclib                0.3.10        PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpunit/php-code-coverage          2.2.4         Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.3.4         FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1         Simple template engine.
phpunit/php-timer                  1.0.7         Utility class for timing
phpunit/php-token-stream           1.4.8         Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    4.1.0         The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       2.3.8         Mock Object library for PHPUnit
psr/log                            1.0.0         Common interface for logging libraries
sebastian/comparator               1.2.0         Provides the functionality to compare PHP values for equality
sebastian/diff                     1.3.0         Diff implementation
sebastian/environment              1.3.2         Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 1.2.1         Provides the functionality to export PHP variables for visualization
sebastian/recursion-context        1.0.1         Provides functionality to recursively process PHP variables
sebastian/version                  1.0.6         Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                      1.3.1         JSON Linter
sjparkinson/static-review          4.1.1         An extendable framework for version control hooks.
squizlabs/php_codesniffer          1.5.3         PHP_CodeSniffer tokenises PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
symfony/config                     v2.7.5        Symfony Config Component
symfony/console                    v2.6.11       Symfony Console Component
symfony/dependency-injection       v2.7.5        Symfony DependencyInjection Component
symfony/event-dispatcher           v2.7.5        Symfony EventDispatcher Component
symfony/filesystem                 v2.7.5        Symfony Filesystem Component
symfony/finder                     v2.7.5        Symfony Finder Component
symfony/process                    v2.7.5        Symfony Process Component
symfony/stopwatch                  v2.7.5        Symfony Stopwatch Component
symfony/yaml                       v2.7.5        Symfony Yaml Component
tedivm/jshrink                     v1.0.1        Javascript Minifier built in PHP
tubalmartin/cssmin                 v2.4.8-p4     A PHP port of the YUI CSS compressor
zendframework/zend-code            2.4.8         provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-config          2.4.8         provides a nested object property based user interface for accessing this configuration data within application code
zendframework/zend-console         2.4.8         
zendframework/zend-crypt           2.4.8         
zendframework/zend-di              2.4.8         
zendframework/zend-escaper         2.4.8         
zendframework/zend-eventmanager    2.4.8         
zendframework/zend-filter          2.4.8         provides a set of commonly needed data filters
zendframework/zend-form            2.4.8         
zendframework/zend-http            2.4.8         provides an easy interface for performing Hyper-Text Transfer Protocol (HTTP) requests
zendframework/zend-i18n            2.4.8         
zendframework/zend-inputfilter     2.4.8         
zendframework/zend-json            2.4.8         provides convenience methods for serializing native PHP to JSON and decoding JSON to native PHP
zendframework/zend-loader          2.4.8         
zendframework/zend-log             2.4.8         component for general purpose logging
zendframework/zend-math            2.4.8         
zendframework/zend-modulemanager   2.4.8         
zendframework/zend-mvc             2.4.8         
zendframework/zend-serializer      2.4.8         provides an adapter based interface to simply generate storable representation of PHP types by different facilities, and recover
zendframework/zend-server          2.4.8         
zendframework/zend-servicemanager  2.4.8         
zendframework/zend-soap            2.4.8         
zendframework/zend-stdlib          2.4.8         
zendframework/zend-text            2.4.8         
zendframework/zend-uri             2.4.8         a component that aids in manipulating and validating » Uniform Resource Identifiers (URIs)
zendframework/zend-validator       2.4.8         provides a set of commonly needed validators
zendframework/zend-view            2.4.8         provides a system of helpers, output filters, and variable escaping

**Comment by mazhalai** [comment]
@scholtz thank you for your report. We are still working on this ticket.

**Comment by thomascrepain** [comment]
@mazhalai I provided pull request #2055 for this issue, with a unittest to proof that permissions with wildcards are now supported. Please look into this first before fixing it a second time internally.

**Comment by mazhalai** [comment]
@magentofaz and @scholtz this has been fixed in 2.0.0 Please have a look and create a new issue if necessary.

**Comment by magento-engcom-team** [comment]
Hi @magentofaz. Thank you for your report. 
The issue has been fixed in magento/magento2#29959 by @engcom-Golf in 2.4-develop branch
Related commit(s):
 - [f8fd731bc3a56a59a89ffc967456d162275476aa](https://github.com/magento/magento2/commit/f8fd731bc3a56a59a89ffc967456d162275476aa)
 - [a948194c397046497cd1b55030fa543dfa25d2d2](https://github.com/magento/magento2/commit/a948194c397046497cd1b55030fa543dfa25d2d2)
 - [235318a1d715e32ff1d685a9f36c612501e77c9a](https://github.com/magento/magento2/commit/235318a1d715e32ff1d685a9f36c612501e77c9a)
 - [b1ed802014177c6bb1b5d49ecb398fa71ccee1d2](https://github.com/magento/magento2/commit/b1ed802014177c6bb1b5d49ecb398fa71ccee1d2)
 - [f5bd1756f94ef968db322bc454171a91f13f3288](https://github.com/magento/magento2/commit/f5bd1756f94ef968db322bc454171a91f13f3288)
 - [be49be365affd0c4d29f42f99335669bd943a8a3](https://github.com/magento/magento2/commit/be49be365affd0c4d29f42f99335669bd943a8a3)

The fix will be available with the upcoming 2.4.2 release.
