### ISSUE TITLE
Overridable permitted actions for unauthorised users 

### ISSUE THREAD

**Issue by nevvermind** [magento/magento2#1815]
I think this property here (or the `getAllowedActions()` method)- https://github.com/magento/magento2/blob/75751593e7cc3b5b399fa7cc67bfca6b4349c3a9/app/code/Magento/Customer/Controller/Account.php#L26-L39 - should be made into a config of some sort, as right now it's near impossible to change those, as other classes _extend_ the `Account` action.

**Comment by sivaschenko** [comment]
Thank you for report. Internal ticket MAGETWO-42624

**Comment by slavvka** [comment]
@nevvermind, Internal ticket MAGETWO-42624 is closed and delivered to mainline. Please, see 78c5312, 9a632d0 and 8383487. Please, let us know if you still have an issue

**Comment by nevvermind** [comment]
Much better. Thanks.
