### ISSUE TITLE
what is mean of  $this->checkoutSession->setLastQuoteId($quote->getId());

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1820]
setLastQuoteId and setLastOrderId adn setLastRealOrderId in Magento\Quote\Model\QuoteManagement->placeOrder()

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
