### ISSUE TITLE
tax added twice in cart on configurable product

### ISSUE THREAD

**Issue by netrixab** [magento/magento2#1822]
It looks like configurable products add tax twice in the shopping cart.
The store is set to show prices including tax for products and shipping and the rate is 25%.
Everything is setup as a swdish merchant. Locality, orign, default countries etc.
Images below show the  shopping cart with two different products, one configurable and one simple, each have a price of 100 sek excl tax. 
## Shopping cart adding tax twice on configurable:
![skarmavbild 2015-09-08 kl 20 39 55](https://cloud.githubusercontent.com/assets/13679677/9744966/417350f8-566f-11e5-9200-c91f53180dd1.png)
## Catalog page of the configurable product:
![skarmavbild 2015-09-08 kl 21 04 06](https://cloud.githubusercontent.com/assets/13679677/9745207/a2a1f518-5670-11e5-9a61-812796dc93e6.png)
## Catalog page of the simple product:
![skarmavbild 2015-09-08 kl 21 05 17](https://cloud.githubusercontent.com/assets/13679677/9745218/b31e09d6-5670-11e5-8352-6e9eded41ee9.png)

**Comment by sdzhepa** [comment]
@netrixab thank you for reporting. Internal ticket MAGETWO-42708 created to track this issue

**Comment by vkholoshenko** [comment]
@netrixab, the team has processed this ticket (fb62bafeac50db7ed748e8ed313b4f1bdecd3317). Sorry for the delay.

**Comment by peterjaap** [comment]
@magento-engcom-team you moved this to DONE in 2.3-develop branch. Do you have a commit that belongs to this? I'm still having this issue on 2.2.3.

**Comment by peterjaap** [comment]
This is my dirty workaround for the issue (after 6 hours of investigation I still haven't found what causes this, the tax module is one complicated mess);

```
From cb1cc3428a21df322d215c01ef7d36525ffb5af5 Mon Sep 17 00:00:00 2001
From: peterjaap <peterjaap@elgentos.nl>
Date: Thu, 31 May 2018 11:27:24 +0200
Subject: [PATCH 1/1] Child already contains calculated tax; let Magento know
 that

Signed-off-by: peterjaap <peterjaap@elgentos.nl>
---
 Model/TaxCalculation.php | 1 +
 1 file changed, 1 insertion(+)

diff --git a/Model/TaxCalculation.php b/Model/TaxCalculation.php
index ac18dfe..8b39114 100644
--- a/Model/TaxCalculation.php
+++ b/Model/TaxCalculation.php
@@ -174,6 +174,7 @@ class TaxCalculation implements TaxCalculationInterface
             if (isset($this->parentToChildren[$item->getCode()])) {
                 $processedChildren = [];
                 foreach ($this->parentToChildren[$item->getCode()] as $child) {
+                    $child->setIsTaxIncluded(true);
                     $processedItem = $this->processItem($child, $calculator, $round);
                     $taxDetailsData = $this->aggregateItemData($taxDetailsData, $processedItem);
                     $processedItems[$processedItem->getCode()] = $processedItem;
-- 
2.17.0


```

Edit; this causes wrong prices for different products... :(
