### ISSUE TITLE
No updated_at for Customer?

### ISSUE THREAD

**Issue by rlieser** [magento/magento2#1824]
Is it intended to have a created_at but not an updated_at for Customer?

**Comment by sivaschenko** [comment]
@rlieser I think this field should be added to CustomerInterface. Internal ticket: MAGETWO-42689

**Comment by slavvka** [comment]
@rlieser, Internal ticket MAGETWO-42689 is closed and delivered to mainline. Please, see 0271946, 2772209 and def9a60. Please, let us know if you still have an issue

**Comment by okorshenko** [comment]
@rlieser thank you for reporting. Please, let us know if you still have an issue
