### ISSUE TITLE
Footer links requiring double press on touch devices

### ISSUE THREAD

**Issue by Tomouse55** [magento/magento2#1825]
The text links in the footer of the mobile layout require two taps to move to the destination page, the first tap activates the hover state. This should ideally be one click when on a touch screen device.

This doesn't occur when tapping on the rest of the area that makes up each footer link, only the text link itself.

**Comment by MomotenkoNatalia** [comment]
@Tomouse55  We can’t reproduce this issue on our test devices, 
Please specify more technical details.

**Comment by Tomouse55** [comment]
Hi,

I’ve just tried replicating this issue on the original device I was testing on and can no longer replicate this issue. The device I’m using has been upgraded from iOS8 to iOS9 in the intervening period however, so that might be the reason that it was occurring and no longer it.

Thanks for looking into it for me.

Best regards,

Tom.

Thomas Day
Client Services Director

[cid:image001.png@01D0F9CB.FFF97440]<http://www.screenpages.com/>

4 The Courtyard, Wisley, Surrey, GU23 6QL
web: www.screenpages.com<http://www.screenpages.com/>
tel: 01932 359 166
mob: 07834 903 415
fax: 01932 345 545
twitter: @screenpages<http://twitter.com/screenpages>

P  Please consider the environment, do you need to print this email?
_________________________________________________________________________________

  Screen Pages Limited, Registered in England and Wales No. 03066989
  Registered Office: 4 The Courtyard, Wisley, Surrey, GU23 6QL
  VAT Number: GB 938 0045 31

  The contents of this message and any attachments are confidential and are intended for the use
  of the persons to whom it is addressed.  If you are not the intended recipient you should not copy,
  forward, use or alter it in any way, nor disclose its contents to any other person. If you are not the
  intended recipient, please notify the sender immediately. The sender is not responsible for any
  alterations that may have transpired without authorisation.
_________________________________________________________________________________

**Comment by okorshenko** [comment]
@Tomouse55 , Please, let us know if you still have an issue
