### ISSUE TITLE
Adding product with rest doesn't work when having multiple stores

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1826]
When configuring 2 stores with 1 website, both same category.. Adding products with rest doesn't work. It works fine with one store! 

The problem seems to be that they are not linked to the category correctly. The products do appear in the backend. But when checking the category, category products.. they are not there. Although the count on the left counts them (for example category_name (2)).

**Comment by rklerck** [comment]
The website isn't set when adding a product with Rest (when configured multiple stores). That's the problem. How can we fix this?

This might me the same fix for https://github.com/magento/magento2/issues/1720

**Comment by BingQiangChen** [comment]
yes，same things happens to me. How to fix?
thanks!

**Comment by choukalos** [comment]
Tracking as - MAGETWO-38439; in progress now.  

Essentially we'll be adding an 'all' store code that allows you to fire 1 API call to the 'All' store and all stores in the system will inherit the values pushed into the system via the API ( similar to the admin gui ).  

Currently you can work around this by firing an API create to each store ( i.e. fire the API two times - once for your first store ( i.e. store code ) and 2nd time for the next store code ).

**Comment by choukalos** [comment]
Bug should be closed and pushed to mainline.
