### ISSUE TITLE
product assigning with new category not working

### ISSUE THREAD

**Issue by doth-web-developer** [magento/magento2#18278]
$_product->setCategoryIds(13);
$interface->save($_product);

Fatal error: Uncaught Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Category\Flat::saveAttribute() in /home/divinec1/public_html/demo/vendor/magento/module-catalog-url-rewrite/Observer/CategoryUrlPathAutogeneratorObserver.php:66 Stack trace: #0 /home/divinec1/public_html/demo/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\CatalogUrlRewrite\Observer\CategoryUrlPathAutogeneratorObserver->execute(Object(Magento\Framework\Event\Observer)) #1 /home/divinec1/public_html/demo/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogUrlRewrite\Observer\CategoryUrlPathAutogeneratorObserver), Object(Magento\Framework\Event\Observer)) #2 /home/divinec1/public_html/demo/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 /home/divinec1/public_html/demo/generated/code/Magento/Framework/Event/ in /home/divinec1/public_html/demo/vendor/magento/module-catalog-url-rewrite/Observer/CategoryUrlPathAutogeneratorObserver.php on line 66

**Comment by engcom-backlog-nazar** [comment]
Hi @doth-web-developer  , thank you for you report, Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
