### ISSUE TITLE
what happens when i configure multiple  interface implement  in different di.xml

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1829]
preference for="Life\Alipay\Model\PaymentInterface" type="Life\Alipay\Model\Payment1"  in module1 di.xml 
preference for="Life\Alipay\Model\PaymentInterface"  type="Life\Alipay\Model\Payment2"  in module2 di.xml(others)
preference for="Life\Alipay\Model\PaymentInterface"  type="Life\Alipay\Model\Payment3"  in module3 di.xml()

which one to use

**Comment by okorshenko** [comment]
@LifeAsBook, in provided use case you will get implementation Life\Alipay\Model\Payment3. All these files will be merged into one container. The sequence of configuration merging (priorities) depends on modules configuration. For more details, please, refer this [documentaiton](http://devdocs.magento.com/guides/v2.0/config-guide/config/config-files.html#config-files-loadmerge)

**Comment by LifeAsBook** [comment]
@okorshenko thank you!

**Comment by LifeAsBook** [comment]
@okorshenko If the original document has multiple nodes with the same identifier, an error is triggered because the identifiers cannot be distinguished ...can you give me a demo?

**Comment by alankent** [comment]
Could you be more precise what "multiple nodes with the same identifier" means?  (My assumption is either it is an error or there is a rule like "last one wins", but wanted to make sure I understood first.)

**Comment by LifeAsBook** [comment]
@alankent  yes,what ""multiple nodes with the same identifier" means in Configuration file merge?  this <a href ="http://devdocs.magento.com/guides/v2.0/config-guide/config/config-files.html#config-files-loadmerge">documentaiton</a>

**Comment by alankent** [comment]
Thanks. If you have a single di.xml file that declares the same ID multiple times I would generally say "don't do that - its strange". We provide the mechanism so module B can override module A. Having module A override itself feels weird - like is the module schizophrenic or something!
Do you have a use case why it is useful for a di.xml file to specify an id twice?

**Comment by LifeAsBook** [comment]
@alankent thank you ! the ID is name Attributes in di.xml?

**Comment by alankent** [comment]
Yes, sorry. I keep thinking of them as id's, but as you say it is the "name" attribute in the di.xml file I am referring to. (I think of it as an 'id' like in HTML - the are meant to be unique in the document.)

**Comment by LifeAsBook** [comment]
@alankent
![qq 20150910090129](https://cloud.githubusercontent.com/assets/10986726/9777771/9e0ad5da-579a-11e5-9bfd-6627c334e764.png)
is like 
![23](https://cloud.githubusercontent.com/assets/10986726/9777846/805208e6-579b-11e5-921b-76a4bdfa4e34.png)


 my understanding is if the (name) is unique type that is an 'id',is right?

**Comment by alankent** [comment]
It does not make sense to me to define the same type twice, so it makes sense this being an error.  Whether the code is correctly reporting an error I don't know (I have not checked). But it is "wrong" / "strange" (to me) to declare the type twice in the same file.

**Comment by LifeAsBook** [comment]
i want to understand configuration file merge,Because when i extend magento modules  i don't konw others places is have to definition it .The above example and this example 
![qq 20150910163758](https://cloud.githubusercontent.com/assets/10986726/9783983/e33eaea2-57da-11e5-95c9-f9999ee0dfb6.png)


 the second is to use and not happen an error

**Comment by dkvashninbay** [comment]
Hi,

To understand how configuration is merged, please inspect DomTest, which documents the general cases: https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Config/Test/Unit/DomTest.php
and the source: https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Config/Dom.php

To understand how DI configuration is extended in runtime (for ex. primary configuration is extended by global area configuration, and then extended by frontend area configuration), please inspect this method (at runtime):
https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/ObjectManager/Config/Config.php#L222
unit tests:
https://github.com/magento/magento2/tree/develop/lib/internal/Magento/Framework/ObjectManager/Test/Unit/Config

**Comment by LifeAsBook** [comment]
@dkvashninbay @alankent thnk you very much! i  will go to see
