### ISSUE TITLE
Magento CLI Zend PDO Mysql error running bin/magento after install

### ISSUE THREAD

**Issue by ljrweb** [magento/magento2#1830]
Error trying to run bin/magento after install from develop branch

[root@ip-172-31-30-205 html]# php bin/magento 
SQLSTATE[HY000] [2002] No such file or directory#0 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(110): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 /usr/share/nginx/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(332): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(861): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#3 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(931): Zend_Db_Adapter_Abstract->quote('1', NULL)
#4 /usr/share/nginx/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1351): Zend_Db_Adapter_Abstract->quoteInto('`store`.`store_...', '1', NULL, NULL)
#5 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Select.php(1005): Magento\Framework\DB\Adapter\Pdo\Mysql->quoteInto('`store`.`store_...', '1', NULL)
#6 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Select.php(475): Zend_Db_Select->_where('`store`.`store_...', '1', NULL, true)
#7 /usr/share/nginx/html/lib/internal/Magento/Framework/DB/Select.php(107): Zend_Db_Select->where('`store`.`store_...', '1', NULL)
#8 /usr/share/nginx/html/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(366): Magento\Framework\DB\Select->where('`store`.`store_...', '1')
#9 /usr/share/nginx/html/app/code/Magento/Store/Model/Resource/Store.php(168): Magento\Framework\Model\Resource\Db\AbstractDb->_getLoadSelect('store_id', '1', Object(Magento\Store\Model\Store\Interceptor))
#10 /usr/share/nginx/html/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(340): Magento\Store\Model\Resource\Store->_getLoadSelect('store_id', '1', Object(Magento\Store\Model\Store\Interceptor))
#11 /usr/share/nginx/html/var/generation/Magento/Store/Model/Resource/Store/Interceptor.php(89): Magento\Framework\Model\Resource\Db\AbstractDb->load(Object(Magento\Store\Model\Store\Interceptor), '1', NULL)
#12 /usr/share/nginx/html/lib/internal/Magento/Framework/Model/AbstractModel.php(518): Magento\Store\Model\Resource\Store\Interceptor->load(Object(Magento\Store\Model\Store\Interceptor), '1', NULL)
#13 /usr/share/nginx/html/app/code/Magento/Store/Model/Store.php(477): Magento\Framework\Model\AbstractModel->load('1', NULL)
#14 /usr/share/nginx/html/var/generation/Magento/Store/Model/Store/Interceptor.php(24): Magento\Store\Model\Store->load('1', NULL)
#15 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreRepository.php(90): Magento\Store\Model\Store\Interceptor->load('1')
#16 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreRepository.php(104): Magento\Store\Model\StoreRepository->getById('1')
#17 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreResolver.php(157): Magento\Store\Model\StoreRepository->getActiveStoreById('1')
#18 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreResolver.php(90): Magento\Store\Model\StoreResolver->getDefaultStoreById('1')
#19 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreManager.php(151): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#20 /usr/share/nginx/html/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#21 /usr/share/nginx/html/app/code/Magento/Store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#22 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Config/ScopePool.php(119): Magento\Store\Model\Resolver\Store->getScope(NULL)
#23 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Config/ScopePool.php(74): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#24 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#25 /usr/share/nginx/html/lib/internal/Magento/Framework/Locale/Resolver.php(90): Magento\Framework\App\Config->getValue('general/locale/...', 'store')
#26 /usr/share/nginx/html/lib/internal/Magento/Framework/Locale/Resolver.php(107): Magento\Framework\Locale\Resolver->getDefaultLocale()
#27 /usr/share/nginx/html/lib/internal/Magento/Framework/Locale/Resolver.php(64): Magento\Framework\Locale\Resolver->setLocale(NULL)
#28 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(103): Magento\Framework\Locale\Resolver->__construct(Object(Magento\Framework\App\Config), 'general/locale/...', 'store', NULL)
#29 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#30 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#31 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#32 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'localeResolver', 'Magento\\Framewo...')
#33 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#34 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#35 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#36 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'localeDate', 'Magento\\Framewo...')
#37 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#38 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#39 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#40 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'dateFilter', 'Magento\\Catalog...')
#41 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#42 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#43 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#44 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'initializationH...', 'Magento\\Catalog...')
#45 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#46 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#47 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#48 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'productReposito...', 'Magento\\Catalog...')
#49 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#50 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#51 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#52 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(249): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#53 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'commands', 'Magento\\Framewo...')
#54 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#55 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#56 /usr/share/nginx/html/lib/internal/Magento/Framework/Console/Cli.php(61): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...')
#57 /usr/share/nginx/html/lib/internal/Magento/Framework/Console/Cli.php(30): Magento\Framework\Console\Cli->getApplicationCommands()
#58 /usr/share/nginx/html/vendor/symfony/console/Symfony/Component/Console/Application.php(91): Magento\Framework\Console\Cli->getDefaultCommands()
#59 /usr/share/nginx/html/bin/magento(24): Symfony\Component\Console\Application->__construct('Magento CLI', '1.0.0-beta')
#60 {main}

SQLSTATE[HY000] [2002] No such file or directory#0 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(129): PDO->__construct('mysql:host=;dbn...', '', '', Array)
#1 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(110): Zend_Db_Adapter_Pdo_Abstract->_connect()
#2 /usr/share/nginx/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(332): Zend_Db_Adapter_Pdo_Mysql->_connect()
#3 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(861): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#4 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(931): Zend_Db_Adapter_Abstract->quote('1', NULL)
#5 /usr/share/nginx/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(1351): Zend_Db_Adapter_Abstract->quoteInto('`store`.`store_...', '1', NULL, NULL)
#6 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Select.php(1005): Magento\Framework\DB\Adapter\Pdo\Mysql->quoteInto('`store`.`store_...', '1', NULL)
#7 /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Db/Select.php(475): Zend_Db_Select->_where('`store`.`store_...', '1', NULL, true)
#8 /usr/share/nginx/html/lib/internal/Magento/Framework/DB/Select.php(107): Zend_Db_Select->where('`store`.`store_...', '1', NULL)
#9 /usr/share/nginx/html/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(366): Magento\Framework\DB\Select->where('`store`.`store_...', '1')
#10 /usr/share/nginx/html/app/code/Magento/Store/Model/Resource/Store.php(168): Magento\Framework\Model\Resource\Db\AbstractDb->_getLoadSelect('store_id', '1', Object(Magento\Store\Model\Store\Interceptor))
#11 /usr/share/nginx/html/lib/internal/Magento/Framework/Model/Resource/Db/AbstractDb.php(340): Magento\Store\Model\Resource\Store->_getLoadSelect('store_id', '1', Object(Magento\Store\Model\Store\Interceptor))
#12 /usr/share/nginx/html/var/generation/Magento/Store/Model/Resource/Store/Interceptor.php(89): Magento\Framework\Model\Resource\Db\AbstractDb->load(Object(Magento\Store\Model\Store\Interceptor), '1', NULL)
#13 /usr/share/nginx/html/lib/internal/Magento/Framework/Model/AbstractModel.php(518): Magento\Store\Model\Resource\Store\Interceptor->load(Object(Magento\Store\Model\Store\Interceptor), '1', NULL)
#14 /usr/share/nginx/html/app/code/Magento/Store/Model/Store.php(477): Magento\Framework\Model\AbstractModel->load('1', NULL)
#15 /usr/share/nginx/html/var/generation/Magento/Store/Model/Store/Interceptor.php(24): Magento\Store\Model\Store->load('1', NULL)
#16 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreRepository.php(90): Magento\Store\Model\Store\Interceptor->load('1')
#17 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreRepository.php(104): Magento\Store\Model\StoreRepository->getById('1')
#18 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreResolver.php(157): Magento\Store\Model\StoreRepository->getActiveStoreById('1')
#19 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreResolver.php(90): Magento\Store\Model\StoreResolver->getDefaultStoreById('1')
#20 /usr/share/nginx/html/app/code/Magento/Store/Model/StoreManager.php(151): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#21 /usr/share/nginx/html/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#22 /usr/share/nginx/html/app/code/Magento/Store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#23 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Config/ScopePool.php(119): Magento\Store\Model\Resolver\Store->getScope(NULL)
#24 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Config/ScopePool.php(74): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#25 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#26 /usr/share/nginx/html/lib/internal/Magento/Framework/Locale/Resolver.php(90): Magento\Framework\App\Config->getValue('general/locale/...', 'store')
#27 /usr/share/nginx/html/lib/internal/Magento/Framework/Locale/Resolver.php(107): Magento\Framework\Locale\Resolver->getDefaultLocale()
#28 /usr/share/nginx/html/lib/internal/Magento/Framework/Locale/Resolver.php(64): Magento\Framework\Locale\Resolver->setLocale(NULL)
#29 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(103): Magento\Framework\Locale\Resolver->__construct(Object(Magento\Framework\App\Config), 'general/locale/...', 'store', NULL)
#30 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#31 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#32 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#33 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'localeResolver', 'Magento\\Framewo...')
#34 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#35 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#36 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#37 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'localeDate', 'Magento\\Framewo...')
#38 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#39 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#40 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#41 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'dateFilter', 'Magento\\Catalog...')
#42 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#43 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#44 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#45 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'initializationH...', 'Magento\\Catalog...')
#46 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#47 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#48 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#49 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'productReposito...', 'Magento\\Catalog...')
#50 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#51 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#52 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#53 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(249): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#54 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'commands', 'Magento\\Framewo...')
#55 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#56 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#57 /usr/share/nginx/html/lib/internal/Magento/Framework/Console/Cli.php(61): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...')
#58 /usr/share/nginx/html/lib/internal/Magento/Framework/Console/Cli.php(30): Magento\Framework\Console\Cli->getApplicationCommands()
#59 /usr/share/nginx/html/vendor/symfony/console/Symfony/Component/Console/Application.php(91): Magento\Framework\Console\Cli->getDefaultCommands()
#60 /usr/share/nginx/html/bin/magento(24): Symfony\Component\Console\Application->__construct('Magento CLI', '1.0.0-beta')
#61 {main}

**Comment by alankent** [comment]
Did you do a "composer update" to download all the other libraries we depend on (like Zend)?

**Comment by ljrweb** [comment]
Ah, I missed that part of the install guide. Is this something that will always be required on a fresh install or are there plans to bring the dependency updater into the default code base?
http://devdocs.magento.com/guides/v2.0/install-gde/install/dev_updater.html

**Comment by ljrweb** [comment]
Actually, this may be related to something else. After installing via the web setup, my env.php file seems to be missing the database connection information. Closing. Thanks @alankent

**Comment by MaximeAnsquer** [comment]
I have the same problem, but my env.php does contain the database connection information:

```
  'db' => 
  array (
    'table_prefix' => '',
    'connection' => 
    array (
      'default' => 
      array (
        'host' => 'localhost',
        'dbname' => 'magento',
        'username' => 'root',
        'password' => 'mypassword',
        'active' => '1',
      ),
    ),
  ),
```

Do you know how I could solve this ? Thanks a lot.
