### ISSUE TITLE
setup:upgrade - Strict Notice

### ISSUE THREAD

**Issue by RanzigeMilch** [magento/magento2#1832]
Hi all,

after doing a "git pull origin develop" and a setup:upgrade today, i always get (in the command line tool) and at the frontend:

Strict Standards: Declaration of Magento\Framework\App\Resource\Proxy::getConnection() should be compatible with Magento\Framework\App\Resource::getConnection($resourceName = self::DEFAULT_CONNECTION) in /xxx/xxx/webseiten/magento2/var/generation/Magento/Framework/App/Resource/Proxy.php on line 0

Strict Standards: Declaration of Magento\Directory\Helper\Data\Proxy::getCountryCollection() should be compatible with Magento\Directory\Helper\Data::getCountryCollection($store = NULL) in /xxx/xxx/webseiten/magento2/var/generation/Magento/Directory/Helper/Data/Proxy.php on line 0

**Comment by dkvashninbay** [comment]
Hi,

You need to flush generated code after each git pull from magento2, as the codebase changes and the generated code should be refreshed to a new version.
In current case you've had a generated proxy for Magento\Framework\App\Resource::getConnection(), but the interface changed to getCountryCollection($store = null), while the generated code in your project  not.

**Comment by RanzigeMilch** [comment]
Yes thank you, after doing that several times, the notice disappeared.
But now i get an error (in report files) "Setup version for module 'Magento_DesignEditor' is not specified"

**Comment by dkvashninbay** [comment]
As i understand, Magento_DesignEditor is your custom extension, so it should have its own  configuration file with contents similar to this:
app/code/Magento/DesignEditor/etc/module.xml:
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
    <module name="Magento_DesignEditor" setup_version="2.0.0">
    </module>
</config>
```

Then you should define modules composer.json similar to this:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Cms/composer.json#L2

And then you should add module similar to others into root composer.json:
https://github.com/magento/magento2/blob/develop/composer.json#L75

After that please run setup:upgrade tool. 

Here you can find a documentation, related to this topic.

**Comment by mazhalai** [comment]
@dkvashninbay @RanzigeMilch `Magento_DesignEditor` module was removed. Please just delete that entry from `setup_module`

**Comment by teemingpl** [comment]
Hi, how do you flush the generated code after git pull? I'm having the same issue with "Strict Notice: Declaration of Magento\Framework\App\Resource\Proxy::getConnection() should be compatible with..".

**Comment by xcomSteveJohnson** [comment]
Manually delete var/di/* and var/generation/*

You could also try magento setup:upgrade, which does this for you (and updates the DB and schema)

**Comment by teemingpl** [comment]
@xcomSteveJohnson thanks for the help! now I'm facing the "Setup version for module 'Magento_DesignEditor' is not specified" issue. Removed the Magento_DesignEditor in setup_modules table but it doesn't seem to help.

**Comment by alankent** [comment]
Try removing from app/etc/config.php as well - please let me know if that works.

**Comment by teemingpl** [comment]
@alankent thanks for prompt reply. however, I just removed it from app/etc/config.php and did a setup:upgrade but its giving me another error "PHP Fatal error:  Class 'Magento\Composer\MagentoComposerApplication' not found in /Applications/MAMP/htdocs/magento2/lib/internal/Magento/Framework/Composer/MagentoComposerApplicationFactory.php on line 46"

**Comment by xcomSteveJohnson** [comment]
@teemingpl Kind of grasping at straws but aside from the DB and config.php, did you look at composer.json? Removing it there and running composer update should remove it from the file system. Then you should have all bases covered: DB, config, file system.

And clear these directories as well if you haven't already: var/cache/*, var/di/*, var/generation/*, var/page_cache/*

**Comment by buskamuza** [comment]
@teemingpl , please, run `composer install` after each `git pull`.

**Comment by piotrekkaminski** [comment]
@RanzigeMilch @teemingpl were your problems resolved?

**Comment by ashish3006** [comment]
I am facing an issue during record creation on my table 
"The resource isn't set ".
Please help me out.

**Comment by alankent** [comment]
Hi, if you are encountering a problem please create a new issue rather than adding a comment to a closed ticket. Also please include sufficient details for the team to try and reproduce the issue - otherwise there is not much they can do to help.
