### ISSUE TITLE
magento 2 built in webserver router 

### ISSUE THREAD

**Issue by danrcoull** [magento/magento2#18358]
### Summary
Been having an issue with using the php built in web server router, so added some conditions to try resolve. The main point of the issue is without the index.php it fails to load just 404's as it doesnt match to anything but if you condition '/' or empty to the request uri and return false this issue is resolved. Making development locally easier. 

### Environment
Standard ubuntu php 7.1 environment stack with mysql local development. 

### Issue
When using the built in webserver without index.php in the url the system 404's means working with the phpserver/router.php a bit of a pain where it should just work as if it was  a vhost. 

### Proposed solution
```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * this is a router file for the php Built-in web server
 * https://secure.php.net/manual/en/features.commandline.webserver.php
 *
 * It provides the same "rewrites" as the .htaccess for apache,
 * or the nginx.conf.sample for nginx.
 *
 * example usage: php -S 127.0.0.41:8082 -t ./pub/ ./router.php
 */

/**
 * Set it to true to enable debug mode
 */
define('DEBUG_ROUTER', false);

$debug = function ($val) {
    if (!DEBUG_ROUTER) {
        return;
    }

    if (is_array($val)) {
        $val = json_encode($val);
    }

    echo 'debug: ' . $val . PHP_EOL . '<br/>' . PHP_EOL;
};

/**
 * Note: the code below is experimental and not intended to be used outside development environment.
 * The code is protected against running outside of PHP built-in web server.
 */

if (php_sapi_name() === 'cli-server') {
    $debug($_SERVER["REQUEST_URI"]);
      if($_SERVER["REQUEST_URI"] == '/'|| strpos($_SERVER["REQUEST_URI"],'/admin') !==false)
    {
        return false;
    }


    if (preg_match('/^\/(index|get|static)\.php(\/)?/', $_SERVER["REQUEST_URI"])) {
        return false;    // serve the requested resource as-is.
    }

    $path = pathinfo($_SERVER["SCRIPT_FILENAME"]);
    $url   = pathinfo(substr($_SERVER["REQUEST_URI"], 1));
    $route = parse_url(substr($_SERVER["REQUEST_URI"], 1));
    if(isset($route["path"])){
       $route = $route["path"];
    }else{
        return false;
    }

    $debug($path);
    $debug($route);

    if ($path["basename"] == 'favicon.ico') {
        return false;
    }

    $debug($route);
    $debug(strpos($route, 'errors/default/css/'));

    if (strpos($route, 'pub/errors/default/') === 0) {
        $route = preg_replace('#pub/errors/default/#', 'errors/default/', $route, 1);
    }

    $debug($route);

    if (strpos($route, 'media/') === 0 ||
        strpos($route, 'opt/') === 0 ||
        strpos($route, 'static/') === 0 ||
        strpos($route, 'errors/default/css/') === 0 ||
        strpos($route, 'errors/default/images/') === 0
    ) {
        $magentoPackagePubDir = __DIR__ . "/../pub";

        $file = $magentoPackagePubDir . '/' . $route;
        $debug($file);
        if (file_exists($file)) {
            $debug('file exists');
            return false;
        } else {
            $debug('file does not exist');
            if (strpos($route, 'static/') === 0) {
                $route = preg_replace('#static/#', '', $route, 1);
                $_GET['resource'] = $route;
                include $magentoPackagePubDir . '/static.php';
                exit;
            } elseif (strpos($route, 'media/') === 0) {
                include $magentoPackagePubDir . '/get.php';
                exit;
            }
        }
    }

    header('HTTP/1.0 404 Not Found');
}

```

This was a complete vanilla issue, both commerce and open source.

**Comment by magento-engcom-team** [comment]
Hi @danrcoull. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@danrcoull do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by danrcoull** [comment]
Wasnt actually a problem as such just an irritation that could easily be fixed allowing built in web server to be used without having to declare index.php as part of the url

**Comment by orlangur** [comment]
@danrcoull please propose your changes as a pull request against `2.3-develop`.

**Comment by danrcoull** [comment]
sure will do.
