### ISSUE TITLE
Retrieve order with rest fails with exception

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1836]
When placing an order (product added in rest or backend), and getting the order with rest "magento2/rest/V1/orders/[orderNumber]" it returns the error "Internal Error. Details are available in Magento log file. Report ID: webapi-55f16a2255cbc". We think this is a major critical bug!

This exception in the log:

[2015-09-10 10:15:06] main.CRITICAL: exception 'Exception' with message 'Report ID: webapi-55f16a2255cbc; Message: Notice: Array to string conversion in /var/www/html/magento2/lib/internal/Magento/Framework/Reflection/TypeCaster.php on line 34' in /var/www/html/magento2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/html/magento2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/www/html/magento2/app/code/Magento/Webapi/Controller/Rest.php(191): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/www/html/magento2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#5 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by adragus-inviqa** [comment]
I think this has the same cause as https://github.com/magento/magento2/issues/1578

**Comment by rklerck** [comment]
Checked it, and indeed has the same cause as #1578 ! It works when changing code locally.

**Comment by sshymko** [comment]
Experiencing the issue on the 2.1 release when an order has been paid with a credit card **stored in a vault** (Braintree in our case).

Please consider reopening the ticket.
