### ISSUE TITLE
Exception on setup:upgrade

### ISSUE THREAD

**Issue by MaxYaroshenko** [magento/magento2#1837]
$ php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/Users/mcs/Sites/magento2/var/generation/Magento
Updating modules:

  [ErrorException]
  Argument 1 passed to Magento\Framework\Module\Setup::__construct() must be
  an instance of Magento\Framework\App\Resource, instance of Magento\Framewor
  k\ObjectManager\ObjectManager given, called in /Users/mcs/Sites/magento2/li
  b/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on l
  ine 97 and defined

setup:upgrade [--magento-init-params="..."]

**Comment by mazhalai** [comment]
@MaxYaroshenko Thank you for reporting this issue. Can you please provide us with more details? What versions of magento 2 did you encounter this error? How to reproduce it?

**Comment by MaxYaroshenko** [comment]
I'm trying to upgrade my magento 2 installation. I'm use branch develop. After run git pull I tryed CLI command setup:upgrade execute again and received another error:

$ php bin/magento setup:upgrade
Recoverable Error: Argument 2 passed to Magento\Framework\App\Request\Http::__construct() must be an instance of Magento\Framework\Stdlib\StringUtils, instance of Magento\Framework\App\Route\ConfigInterface\Proxy given, called in /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 107 and defined in /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Request/Http.php on line 104#0 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Request/Http.php(104): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 2 pass...', '/Users/mcs/Site...', 104, Array)
#1 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(107): Magento\Framework\App\Request\Http->__construct(Object(Magento\Framework\Stdlib\Cookie\PhpCookieReader), Object(Magento\Framework\App\Route\ConfigInterface\Proxy), Object(Magento\Store\App\Request\PathInfoProcessor\Proxy), Object(Magento\Framework\ObjectManager\ObjectManager), NULL, Array)
#2 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#4 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#5 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#6 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#7 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
#8 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Factory.php(193): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#9 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Factory.php(157): Magento\Framework\App\Cache\Frontend\Factory->_applyDecorators(Object(Magento\Framework\Cache\Frontend\Adapter\Zend))
#10 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Pool.php(67): Magento\Framework\App\Cache\Frontend\Factory->create(Array)
#11 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Pool.php(146): Magento\Framework\App\Cache\Frontend\Pool->_initialize()
#12 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Cache/Type/FrontendPool.php(84): Magento\Framework\App\Cache\Frontend\Pool->get('default')
#13 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Cache/Type/Config.php(49): Magento\Framework\App\Cache\Type\FrontendPool->get('config')
#14 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\App\Cache\Type\Config->_getFrontend()
#15 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/Interception/Config/Config.php(99): Magento\Framework\Cache\Frontend\Decorator\Bare->load('interception')
#16 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(109): Magento\Framework\Interception\Config\Config->__construct(Object(Magento\Framework\ObjectManager\Config\Reader\Dom\Proxy), Object(Magento\Framework\Config\Scope), Object(Magento\Framework\App\Cache\Type\Config), Object(Magento\Framework\ObjectManager\Relations\Runtime), Object(Magento\Framework\Interception\ObjectManager\Config\Compiled), Object(Magento\Framework\ObjectManager\Definition\Runtime), 'interception')
#17 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#18 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#19 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/ObjectManager/Environment/Compiled.php(109): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#20 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(181): Magento\Framework\App\ObjectManager\Environment\Compiled->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Compiled), Array)
#21 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(384): Magento\Framework\App\ObjectManagerFactory->create(Array)
#22 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(361): Magento\Framework\App\Bootstrap->initObjectManager()
#23 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/Console/Cli.php(47): Magento\Framework\App\Bootstrap->getObjectManager()
#24 /Users/mcs/Sites/magento2/lib/internal/Magento/Framework/Console/Cli.php(30): Magento\Framework\Console\Cli->getApplicationCommands()
#25 /Users/mcs/Sites/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php(91): Magento\Framework\Console\Cli->getDefaultCommands()
#26 /Users/mcs/Sites/magento2/bin/magento(24): Symfony\Component\Console\Application->__construct('Magento CLI', '1.0.0-beta')
#27 {main}

**Comment by buskamuza** [comment]
Hi @MaxYaroshenko ,

please, run `composer install` after pulling from GitHub.
If it will not help, try to cleanup `var` folder.

**Comment by MaxYaroshenko** [comment]
I've received after composer install
Loading composer repositories with package information
 Installing dependencies (including require-dev) from lock file
  - Removing lusitanian/oauth (v0.4.1)
  - Installing lusitanian/oauth (v0.3.5)
    Loading from cache

 Generating autoload files

After run setup:upgrade got exception

 Module 'Magento_CatalogSearch':
 Installing data..


  [Magento\Framework\Exception\SessionException]
  Area code not set: Area code must be set before starting a session.


  [Magento\Framework\Exception\LocalizedException]
  Area code is not set

**Comment by buskamuza** [comment]
@MaxYaroshenko , could you, please, provide exact revision you're upgrading to?

**Comment by MaxYaroshenko** [comment]
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.

**Comment by buskamuza** [comment]
@MaxYaroshenko , could you, please, show the exact commit? For example, with `git log -n 1`.
Your `origin/develop` still may be outdated or it's just not precise because the branch is updated continuously.

**Comment by MaxYaroshenko** [comment]
$ git log -n 1
commit b94eaed9ffc0d520240995a062d8faa3da7064bc
Merge: 2dc1854 ec0cf53
Author: He, Joan(johe) <johe@ebay.com>
Date:   Wed Sep 16 21:39:04 2015 -0500

    Merge pull request #610 from magento-extensibility/MAGETWO-42977-use-factories-to-inject-dependencies

    MAGETWO-42977: Use factories to inject dependencies on Zend classes in \Magento\CacheInvalidate\Model\PurgeCache

**Comment by piotrekkaminski** [comment]
Do you still have this issue @MaxYaroshenko? Feel free to reopen the issue if still a problem.
