### ISSUE TITLE
customer addresses export missing customer_id

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1839]
**Problem:** The customer id should be included in customer addresses export for referential check capabilities 
**Version affected:** 2.2
**Steps:** admin panel -> export customers addresses
**Expected:** customer ID/address ID is included in export file so it can be used to later import the customers and update fields
**Actual:** customer ID/address ID is not included

**Comment by piotrekkaminski** [comment]
@asemenenko please review

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44684

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/customer-addresses-export-missing-customer-id/idi-p/47232).

**Comment by piotrekkaminski** [comment]
Version affected: 2.2
Steps: export customers
Expected: customer ID is included in export file so it can be used to later import the customers and update fields
Actual: customer ID is not included

**Comment by keyurshah070** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @markoshust. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/34
