### ISSUE TITLE
system > import > customers sample data files missing

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1840]
Sample files are missing for:
- Customers
- Customers Main File
- Customer Addresses

![screen shot 2015-09-10 at 2 16 51 pm](https://cloud.githubusercontent.com/assets/437029/9796960/c2c63d48-57c6-11e5-9389-f28e80a84843.png)

**Comment by markoshust** [comment]
On a related note in #1838 and #1839, it's impossible to import customers/addresses if we can't get the related id's from the exports.

**Comment by piotrekkaminski** [comment]
@asemenenko please review

**Comment by asemenenko** [comment]
Internal ticket MAGETWO-44775

**Comment by slavvka** [comment]
@markoshust, the issue is fixed and delivered to mainline. Please see e87f267.

**Comment by markoshust** [comment]
Awesome thank you

**Comment by Taral-Patoliya** [comment]
@slavvka  I have recently encountered this problem in 2.0.7, the `Customers and Addresses (single file)` Option does not seem to have the sample file. When i try to download the sample file, it gives the same error.

**Comment by slavvka** [comment]
@Taral-Patoliya I do know that this fix is in 2.1.0 release but I am not sure about 2.0.7.

**Comment by Taral-Patoliya** [comment]
@slavvka Thank you for the prompt reply, is there any way i can get the file? i need the reference as soon as possible. If possible it can be attached in the comments bellow.

**Comment by ceer** [comment]
@Taral-Patoliya, I think you can download Magento 2.1.0 and find it here: /vendor/magento/module-import-export/Files/Sample/customer_composite.csv
