### ISSUE TITLE
system > import > customers ambiguity

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1841]
What is the difference between Customers and Customers Main File? I don't think the Customers Main File option makes any sense. If there's a reason these two exist, there should be an explanation somewhere, however these options should be directly related to specific entities, and I believe Customers Main File is superfluous.

![screen shot 2015-09-10 at 2 18 33 pm](https://cloud.githubusercontent.com/assets/437029/9797008/0d3cac72-57c7-11e5-91cd-cd1af9b3dfc6.png)

**Comment by piotrekkaminski** [comment]
@asemenenko please review

**Comment by slavvka** [comment]
@markoshust, Internal ticket MAGETWO-44090 is closed and delivered to mainline. Please, see 5542bb1. Please, let us know if you still have an issue.
