### ISSUE TITLE
scenario for importing complete new set of customers + addresses

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1842]
How would one go about importing a completely new set of customers and addresses (say from another ecommerce system)?

I believe right now to import a customer address, you would need to reference the customer id. However, this doesn't exist yet as this is a completely new import. I believe we would need a secondary unique ID (say previous_entity_id) to create references before the import process starts, and then tie this into the import process (if entity_id doesn't exist, use previous_entity_id)?

**Comment by choukalos** [comment]
Customer can use website/email as a unique key.  So you don't need to pass in an ID if you want to import new customers.  Best way to do this is to push all data related to customer (including multiple addresses) in 1 post call using this api http://devdocs.magento.com/guides/v2.0/rest/restApi/restCollection/Magento/Customer/Api/AccountManagement/createCustomer.html

**Comment by markoshust** [comment]
Thanks much -- that makes sense.
