### ISSUE TITLE
make single-store mode default

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1843]
Is there any reason not to make single-store mode the default setting, since it only applies if there is only one store view? I think this could simplify some admin settings and make things a bit cleaner on the backend. 

![screen shot 2015-09-10 at 2 49 09 pm](https://cloud.githubusercontent.com/assets/437029/9797856/5e146500-57cb-11e5-9c89-c41f5b73cc43.png)

**Comment by therouv** [comment]
I've also stumbled over this.. :+1:

**Comment by piotrekkaminski** [comment]
I think it makes sense. Can you submit PR for that?

**Comment by therouv** [comment]
@piotrekkaminski Here you go :-)

**Comment by orlangur** [comment]
> Is there any reason not to make single-store mode the default setting, since it only applies if there is only one store view?

Is there any reason to keep this option in Admin UI at all then? ;)

**Comment by markoshust** [comment]
I agree - I think it should just be removed.

**Comment by vjournal** [comment]
I gree, but in my installation if I change this value to Yes in backend are no more Products shown in catalog.
This must be a bug.

**Comment by markshust** [comment]
Just wanted to bring this ticket back into conversation.
- Default value should be changed to Yes, as it dramatically simplifies some views when there is only one store setup (as most sites are).
- If set to Yes, the config option shouldn't exist in the admin, because if set to Yes and multiple stores exist, it isn't applicable.

**Comment by pboisvert** [comment]
@piotrekkaminski Piotr--can you own this one or reassign as appropriate?

**Comment by piotrekkaminski** [comment]
Reassigned to @tanya-soroka

**Comment by tanya-soroka** [comment]
We have already task MAGETWO-43040 for this changes which is related to the #1885 and #2446 pull requests

**Comment by magento-engcom-team** [comment]
Hi @markoshust 
thank you for the suggestion. We have this in our backlog . The GitHub issue tracker is intended for Magento Core technical issues only.
