### ISSUE TITLE
cache types don't properly invalidate all the time

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1844]
I've noticed different scenarios where after changing a setting in the admin, the related cache types don't properly invalidate. 

For example, when changing the site theme, the only cache type that invalidates is Page Cache, when it should also invalidate View Files, Layouts, Bock HTML Output, etc. The only way I can see the new theme is if I completely flush the entire cache. 

This is just one example, there are also various items throughout the stores > config options which cause the same situation.

**Comment by piotrekkaminski** [comment]
internal issue : MAGETWO-43857

**Comment by daim2k5** [comment]
Fixed. Please reopen if issue persists.
