### ISSUE TITLE
luma theme > my account, page title is in incorrect location

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1845]
This appears to be happening in all My Account subsections. 

![screen shot 2015-09-10 at 3 01 26 pm](https://cloud.githubusercontent.com/assets/437029/9798128/028e5932-57cd-11e5-876a-92124a201805.png)

**Comment by godban** [comment]
Hello @markoshust,
unfortunately (or maybe fortunately) we can not reproduce this issue. Please compare last version of Magento with your fork. Looks like that page-title is moved in templates.

**Comment by markoshust** [comment]
Ok thanks will check out on `develop`.
