### ISSUE TITLE
adding item to cart from My Wish List shows JSON object

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1846]
Adding item from wishlist sidebar:

![screen shot 2015-09-10 at 3 05 22 pm](https://cloud.githubusercontent.com/assets/437029/9798228/ad64f4e2-57cd-11e5-85b3-b701b55700e5.png)

Shows this:

![screen shot 2015-09-10 at 3 05 56 pm](https://cloud.githubusercontent.com/assets/437029/9798235/b4388cd4-57cd-11e5-96ee-891d818f7aca.png)

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-43237

**Comment by piotrekkaminski** [comment]
This is fixed and should be available soon.
