### ISSUE TITLE
UI improvement to top nav / user account onHover

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1847]
Hovering over the currently logged in user's name looks like this:

![screen shot 2015-09-10 at 3 13 15 pm](https://cloud.githubusercontent.com/assets/437029/9798400/ae00db22-57ce-11e5-92e4-2010b8031418.png)

However, clicking on the name shows the account dropdown. So, the cursor should instead look like this on hover:

![screen shot 2015-09-10 at 3 13 45 pm](https://cloud.githubusercontent.com/assets/437029/9798415/c4815ae8-57ce-11e5-92ca-62619bd487e8.png)

I believe not setting `cursor:pointer` is going to cause a lot of customers to think their name is not clickable.

**Comment by godban** [comment]
Hello @markoshust,
thank you for this report. Actually there is marker that points to dropdown, but you are right name is clickable and should have a pointer.

Created internal ticket MAGETWO-42900

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-42900 is closed and delivered to mainline. Please let us know if you still have an issue.
