### ISSUE TITLE
Javascript error on Cart

### ISSUE THREAD

**Issue by afroz92** [magento/magento2#1848]
I have installed Master branch on my local machine with sample data . When i am on cart page and clicking on "Go to Checkout " nothing happens and i can see error in console 
"TypeError: window.authenticationPopup is undefined
location.href = window.authenticationPopup.checkoutUrl;"

**Comment by sidolov** [comment]
Hi, @afroz92 
Provided issue is reproducible only on Luma theme and is fixed in develop branch.
GitHub issue https://github.com/magento/magento2/issues/1508
Fixed in commit 56e3e556be6f092e07dc8a6930d01547d94f27eb
You may cherry-pick commit to fix this issue or use develop branch.

**Comment by okorshenko** [comment]
@afroz92, could you please confirm that this solution works for you?

**Comment by okorshenko** [comment]
@afroz92 , thank you for reporting. Please, let us know if you still have an issue
