### ISSUE TITLE
luma theme > shopping cart headers missing column

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1849]
See this screenshot:

![screen shot 2015-09-10 at 3 24 29 pm](https://cloud.githubusercontent.com/assets/437029/9798628/24764fa2-57d0-11e5-8c1d-878df0725ea4.png)

Subtotal should be right-aligned to the second price beneath it, and both lines (beneath shopping cart row headers and above the Update Cart button) should expand all the way to the right. There are four columns in each thead and tbody, but something isn't quite aligning right.

**Comment by godban** [comment]
@markoshust hello

Thank you for reporting this issue. Reproduced. Seems columns in heading and table body are async. Interesting case. Created internal ticket MAGETWO-43073

**Comment by piotrekkaminski** [comment]
Hey @markoshust I got info we can no longer reproduce this issue. Can you check and let us know if fixed?

**Comment by markoshust** [comment]
Sure, about to fire up new m2 copy from develop to check this and some other things out. Will let you know. Thanks -M

**Comment by markoshust** [comment]
Yes, this seems to have been fixed in develop.
