### ISSUE TITLE
order charts on dashboard not working

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1850]
Please see this screenshot:
![screen shot 2015-09-10 at 3 32 25 pm](https://cloud.githubusercontent.com/assets/437029/9798787/544a836e-57d1-11e5-8596-0b7df79fc680.png)

Notice that orders are placed (within the last hour or so), but charts aren't showing. I've ran the cron, updated lifetime statistics, and flushed the Magento cache. The reports area is still saying "No Data Found" for both Orders and Amounts tabs.

**Comment by alankent** [comment]
Did you run cron once or twice?  There was something about the first run set up instructions that got picked up on the second run of cron.  (I don't recall why. but if you could try running cron again to see if that addresses it that would be great - then we know its an indexing issue.)

**Comment by markoshust** [comment]
I tried running it again, but no dice. Same result ("No Data Found").

**Comment by alankent** [comment]
Thx. I will leave it to the experts then.

**Comment by icesky366** [comment]
how to run cron?

**Comment by alankent** [comment]
If you mean from the command line, you can run `magento cron:run`. (See the 'bin' directory for the 'magento' command.) For more documentation see http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-43858

**Comment by ulianakostur** [comment]
Is "Enabled Chart" setting enabled in admin?
![09-10-2015 16-25-16](https://cloud.githubusercontent.com/assets/11276363/10394943/fdff6536-6ea2-11e5-9272-fcb0ecf64748.png)

**Comment by Zatara7** [comment]
@markoshust Hello, I believe the reason it isn't showing is because the order that you placed (or your customer placed) is not marked complete. It will only show up in those statistics if that is true. To make it marked complete you need to make sure you process the shipping and the invoice for the order. Please let us know if that worked for you.

**Comment by markoshust** [comment]
Let me retest, seems lots of code updates since I last tested this.

**Comment by markoshust** [comment]
@Zatara7 yes I believe you are right, order wasn't complete. All working now.
