### ISSUE TITLE
admin search bar - unspecified functionality

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1851]
It's a bit confusing as to what the admin search actually does.

- When I search by a keyword and hit enter on my keyboard, the page just reloads, regardless of what is typed in.
- It appears to only search for products. If this is the case, why am I not sent to the product search result upon hitting enter on my keyboard?
- When I first searched, I thought I could type in things like "configuration" or "cache", thinking I can search anywhere in the admin. However, this is not the case (as it only appears to search for products).

I'd recommend either searching the entire admin area so we can search for various items (newsletter, cache, customers, etc.), or add placeholder text that says "Search products", so the user knows exactly what this search box is supposed to be doing. It's very inconspicuous right now.

**Comment by choukalos** [comment]
Hi @markoshust currently the admin search does a search preview on (customer, catalog, orders) which can be a little slow.  Right now you would see a link that you could click on to go to the respective item (if found).  We'll be addressing this in the future where you would link to the admin grids to enable some more drill down capability ( i.e. could go to customer grid and see the grid already pre-filtered based on the admin search query ).  Internally we're tracking with this ticket - MAGETWO-36039.

**Comment by vzabaznov** [comment]
Hi @markoshust, issue was fixed, please check it, and if you think that not, feel free to write here or to open new one
