### ISSUE TITLE
Content - Preview actually isn't Preview

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1852]
Clicking on the dropdown box next to a content page shows:

![screen shot 2015-09-10 at 3 47 05 pm](https://cloud.githubusercontent.com/assets/437029/9799112/423d0794-57d3-11e5-8b76-8e1a19d35d94.png)

However, the Preview option is either named bad, or has non-existent functionality.

To properly "preview" a page, there needs to be the ability to make edits to a page, save it, and publish it at a later date, so you can "preview" the page before it is published. However, you really aren't previewing anything here, as that link just shows you the page as it is already published on the frontend site.

I believe there should either be full preview functionality added (ability to make edits, "preview" changes (before they are made viewable to the public), and then be able to publish the desired updates. It's possible this could be done on the content edit page without revision tracking, however if this is the case, the "preview" option should be removed from the content grid view, because it's not appropriate here.

I don't think the option to view the page on the frontend website is bad, but if this is kept in, it should be renamed "View", and also open in a new window so it doesn't kick you out of the admin.

**Comment by tkacheva** [comment]
@markoshust, that totally makes sense. We have this to be updated in backlog. Once is done, I'll update you

**Comment by tkacheva** [comment]
MAGETWO-42861

**Comment by markoshust** [comment]
Thanks. I was just wondering, what was decided internally on the proposed solution?

**Comment by tkacheva** [comment]
Basically both options are considered and taken into account. Can't tell you more for now.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Content-Preview-actually-isn-t-Preview/idi-p/46929).
