### ISSUE TITLE
new customers report shows extra/un-needed columns

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1853]
If you go to Admin > Reports > Customers > New, and just click Refresh, it appears to show all dates from 1/1/01 to present.

![screen shot 2015-09-10 at 3 55 24 pm](https://cloud.githubusercontent.com/assets/437029/9799352/a43d8c7e-57d4-11e5-8361-6ac48c6005fe.png)

It shows a row for each date, whether or not there is data for this date. Since I only have one customer record:

![screen shot 2015-09-10 at 3 57 12 pm](https://cloud.githubusercontent.com/assets/437029/9799366/b89e8600-57d4-11e5-90b0-814462675b9a.png)

it is showing me 5477 unneeded rows. I believe this page would render a lot quicker and be easier to read if it just showed you the rows that have data. It may also be a good idea to default the "Refresh" button to a tighter time span, such as YTD.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/new-customers-report-shows-extra-un-needed-columns/idi-p/45797).
