### ISSUE TITLE
CMS Hierarchy not working

### ISSUE THREAD

**Issue by abhilash123** [magento/magento2#1855]
We have tried to create few CMS pages with hierarchy.  All the CMS pages in the hierarchy follows the 2 column left layout.  While creating the hierarchy we have also enabled the Display in navigation menu also.  Unfortunately the left menu is not displayed in any of the CMS pages in the hierarchy.  Can anyone know how this CMS hierarchy works in magento2

Thanks!

**Comment by lijithmg** [comment]
Anyone have this CMS Hierarchy working on master branch.

**Comment by maksek** [comment]
Use forum for questions.
