### ISSUE TITLE
rest api : {"message":"Invalid attribute name: %1","parameters":["store_id"]} ,  when I use 'searchCriteria' by 'store_id' 

### ISSUE THREAD

**Issue by BingQiangChen** [magento/magento2#1861]
my request:
https://www.teadata.cn/product/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=store_id&searchCriteria[filter_groups][0][filters][0][value]=1&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[current_page]=1&searchCriteria[page_size]=2"

my response：
{"message":"Invalid attribute name: %1","parameters":["store_id"]}

I want to filter products by 'store_id',  but i don't know.
thanks!

**Comment by kandy** [comment]
Products service returns product only from one store, to select concrete store please use url in format http://host/rest/{store_id}/V1/products

**Comment by BingQiangChen** [comment]
thanks, how to get all information of all products by "catalog_id"?

**Comment by BingQiangChen** [comment]
@kandy thanks ！
