### ISSUE TITLE
\Magento\Catalog\Model\Resource\Product\Collection method to set $needToAddWebsiteNamesToResult

### ISSUE THREAD

**Issue by Michal-sk** [magento/magento2#1862]
I would like to suggest a method to set the ```$needToAddWebsiteNamesToResult``` property of ```\Magento\Catalog\Model\Resource\Product\Collection```. I could work around it trough a ```Plugin``` and change the logic of the ```load()``` method in that collection, but would be easier if we could just set that value.

**Comment by Michal-sk** [comment]
And personally it would be better fit for me if you would make ```doAddWebsiteNamesToResult``` public.

**Comment by Michal-sk** [comment]
What is the reason that this adding the names of the websites is in the ```load()```? https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Resource/Product/Collection.php#L735

Very problematic, because there doesnt seem to be a way to override this, even with a plugin. Because when you do a ```afterLoad``` plugin, and than  want to change the added products in the collection, you have to loop trough the collection which again calls the ```load``` method, and that again calls the ```afterLoad``` plugin... i have tried settings flags etcetc but im out of ideas on how to override this little method which adds the names to the product.

**Comment by Michal-sk** [comment]
One way which seems to be helpfull is to find what calls ```$collection->addWebsiteNamesToResult()``` that makes it even more important to have that ```addWebsiteNamesToResult``` method public or atleast have a event on it, so we can alter this information.

For now i will try to have plugins that change the methods which call ```addWebsiteNamesToResult```

**Comment by Michal-sk** [comment]
Additionally, what magic are we using to call the protected ```addWebsiteNamesToResult()``` from ```AddWebsitesFieldToCollection``` class. Because that method is protected i didn't initially think about looking for other objects calling that class.

**Comment by BingQiangChen** [comment]
very useful！
