### ISSUE TITLE
Setupscript: TYPE_NUMERIC has wrong default precision and scale

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#1863]
I have the following setup script:

```
$installer = $setup;
        $installer->startSetup();
        $table = $installer->getConnection()->newTable(
            $installer->getTable('some_cool_table')
        )->addColumn(
            'qty',
            \Magento\Framework\DB\Ddl\Table::TYPE_NUMERIC,
            null,
            array(),
            'Qty'
        );
        $installer->getConnection()->createTable($table);
        $installer->endSetup();
```

I do not define precision and scale and therefore this column gets the following default values: **precision = 0** and **scale = 10** in **Magento\Framework\DB\Ddl\Table::addColumn()**. This ends up in **Magento\Framework\DB\Adapter\Pdo\Mysql::_getColumnDefinition()** in being converted in a wrong column type as I get the mysql error: *SQLSTATE[42000]: Syntax error or access violation: 1427 For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'qty')*. 

It should be the other way round:
**precision = 10** and **scale = 0**.

**Comment by piotrekkaminski** [comment]
Internal issue /MAGETWO-43860

**Comment by convenient** [comment]
Just found the same issue in Magento 1, wish we could backport these kind of things a bit easier!

**Comment by sshrewz** [comment]
This has been resolved.  Feel free to let us know if you encounter any issues by reopening this.
