### ISSUE TITLE
How to overwrite a javascript component method?

### ISSUE THREAD

**Issue by kassner** [magento/magento2#1864]
Hi,

I'm looking for a way to overwrite a javascript method in `Magento_Checkout/js/payment/default`, I'm able to extend it with my own `My_Module/js/payment/default` and use it without problem, but I need to change every `define` that is calling it directly by `Magento_Checkout`.

Is there a way to make requirejs understand that I want to change the file it should lookup? Back in Magento 1 the concept was different, but it was possible to overwrite a JS class method using prototypes, this new structure does not allow it or I'm missing something?

Devdocs say about extending a component (which works when changing the define function) or overwriting a widget, but that one does not work with components.

Thanks!

**Comment by kumbas111** [comment]
You can try 'mixins' feature, all you need is to create requireJS module with extended method like this

**Comment by kassner** [comment]
@kumbas111 Thanks! That's exactly what I needed.

Just to document here, if you need to overwrite a function instead a class method (I used to overwrite `Magento_Checkout/js/action/place-order`).

requirejs-config.js
```javascript
var config = {
    config: {
        mixins: {
            'Magento_Checkout/js/action/place-order': {
                'My_Module/js/action/place-order': true
            }
        }
    }
};
```

place-order.js
```javascript
define(['mage/utils/wrapper'], function (wrapper) {
    'use strict';

    return function (placeOrderAction) {
        return wrapper.wrap(placeOrderAction, function (originalAction, paymentData, redirectOnSuccess) {
            // my own code here
            return originalAction(paymentData, redirectOnSuccess);
        });
    };
});
```

**Comment by barbala4o** [comment]
Hi. This does not seem to work for me.. I want to rewrite 
`
vendor/magento/module-ui/view/base/web/js/grid/provider.js`

the function reload of it. 

My view/adminhtml/web/js/default_mixin.js code 

```
define(function () {
    'use strict';
    var mixin = {
    		reload:function (){
    			console.log('ddd');
    			alert('3333');
    		}
    }
    
    return function (target) { // target == Result that Magento_Ui/.../default returns.
        return target.extend(mixin); // new result that all other modules receive 
    };
});

My view/adminhtml/requirejs-config.js code

`var config = {
	config : {
	    mixins: {
	        'Magento_Ui/js/grid/provider': {  // Target module
	        	'MyVendor_MyModule/js/default_mixin': true  // Extender module
	        }
	    }
	}
};

Did something change in the methodology  or...  ? Where am I going wrong

**Comment by AntonEvers** [comment]
As seen in `Magento_CheckoutAgreements/js/model/place-order-mixin`

**Comment by shiva805** [comment]
But not finding information how to call parent component method from extended method.
