### ISSUE TITLE
Mini Cart not updated

### ISSUE THREAD

**Issue by fooman** [magento/magento2#1865]
1. Search for a product,
2. Use Add to Cart button

Expected result:
Product that was added to the cart is visible in the mini cart
(the product is in the cart when proceeding to checkout for example)

![screenshot-e361882f50f5 local fooman co nz 2015-09-14 15-33-05](https://cloud.githubusercontent.com/assets/455508/9841657/a248bb12-5af6-11e5-8901-92f63b94406c.png)

**Comment by okorshenko** [comment]
Hi @fooman, could you, please, add more details about pre-conditions and steps to reproduce. I tested this flow on latest version of code base, but can't reproduce this issue. Different product types were successfully added to shipping cart. It would be great if you can take a look at browser console (for some JS errors), provide information about changed values in system configuration and code customizations. Thank you!

**Comment by gordonknoppe** [comment]
Is HTTPS involved here?  If so there's a known issue for that.

**Comment by fooman** [comment]
No https involved.

Steps:
1.Install latest dev (pulled yesterday)
2.Configuration changes:

    magerun2 config:set web/url/redirect_to_base 0
    magerun2 config:set web/cookie/cookie_path /
    magerun2 config:set web/seo/use_rewrites 1
    magerun2 config:set web/session/use_frontend_sid 0
    magerun2 config:set admin/security/use_form_key 0

3.Install performance fixture small.xml
4.Search for "simple"
5.Click "Add to Cart"

Result
See success message 
Don't see product in mini cart.

No JS errors.

The add to cart POST

    curl 'http://example.com/checkout/cart/add/uenc/aHR0cDovLzE3Mi4xNy4wLjUvY2F0YWxvZ3NlYXJjaC9yZXN1bHQvP3E9c2ltcGxl/product/99/?SID=7hv5as08p8cfvl6flpbhqmtau1' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.5' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Cookie: PHPSESSID=7hv5as08p8cfvl6flpbhqmtau1; form_key=xfiVYumPCrRAI3Sx; mage-cache-storage=%7B%7D; mage-cache-storage-section-invalidation=%7B%7D; mage-cache-sessid=true' -H 'DNT: 1' -H 'Host: example.com' -H 'Pragma: no-cache' -H 'Referer: http://example.com/catalogsearch/result/?q=simple' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 FirePHP/0.7.4' -H 'X-Requested-With: XMLHttpRequest' -H 'x-insight: activate' --data 'product=99&uenc=aHR0cDovL2JkYjJjN2E1N2Q4OC5sb2NhbC5mb29tYW4uY28ubnovY2hlY2tvdXQvY2FydC9hZGQvdWVuYy9hSFIwY0Rvdkx6RTNNaTR4Tnk0d0xqVXZZMkYwWVd4dlozTmxZWEpqYUM5eVpYTjFiSFF2UDNFOWMybHRjR3hsL3Byb2R1Y3QvOTkvP1NJRD03aHY1YXMwOHA4Y2Z2bDZmbHBiaHFtdGF1MQ%2C%2C'

Response

    []


Another GET for the message

    curl 'http://example.com/customer/section/load/?SID=7hv5as08p8cfvl6flpbhqmtau1&sections=messages&_=1442365548288' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.5' -H 'Connection: keep-alive' -H 'Cookie: PHPSESSID=7hv5as08p8cfvl6flpbhqmtau1; form_key=xfiVYumPCrRAI3Sx; mage-cache-storage=%7B%7D; mage-cache-storage-section-invalidation=%7B%7D; mage-cache-sessid=true; private_content_version=a15839bec1580594c7a3b728571b8ae8; message_box_display=1' -H 'DNT: 1' -H 'Host: example.com' -H 'Referer: http://example.com/catalogsearch/result/?q=simple' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 FirePHP/0.7.4' -H 'X-Requested-With: XMLHttpRequest' -H 'x-insight: activate'

Response

    {"messages":{"messages":[{"type":"success","text":"You added Simple Product 99 to your shopping cart."}]}}

**Comment by okorshenko** [comment]
Thank you for reporting. Internal ticket MAGETWO-43008 is created to track this issue

**Comment by sdzhepa** [comment]
Hi @footman

We have verified it on current "develop" branch: 02e18015cfbb1872fdca35e43c923ba17f6ce05a from https://github.com/magento/magento2.git repo.

We can’t reproduce this issue for now. Could you please verify whether this issue still present?

**Comment by piotrekkaminski** [comment]
@fooman can you check it now?

**Comment by fooman** [comment]
Thanks it works for me now as well.

**Comment by ghost** [comment]
I am having this issue again in Magento version 2.0.4. Adding product to cart is working fine. However it is not updating cart - specifically for configurable products.
