### ISSUE TITLE
sample_data install error

### ISSUE THREAD

**Issue by xddhaibo** [magento/magento2#1866]
![qq 20150914130753](https://cloud.githubusercontent.com/assets/12825951/9842539/e17533c0-5ae1-11e5-8c54-4feb25873c06.png)

**Comment by tataranovich** [comment]
Try to use memory_limit=-1, example:
``
php -d memory_limit=-1 bin/magento setup:install <the-rest-of-command>
``

**Comment by mazhalai** [comment]
@xddhaibo If you have xdebug turned on, please turn it off and try again.

**Comment by piotrekkaminski** [comment]
@xddhaibo do you still see this issue?
