### ISSUE TITLE
Mage_Core_Model_Store::setConfig() not present in m2 and required

### ISSUE THREAD

**Issue by wsakaren** [magento/magento2#1867]
This method seems to have been removed from M2, wanting to understand the reasoning for this one.  We use it to temporarily set carriers to enabled so that we can call in a backup scenario. 

I've checked the M2 code and all the way up the chain there is no access to change the config values dynamically from what I can see.

**Comment by kandy** [comment]
Please use \Magento\Framework\App\MutableScopeConfig::setValue method instead

**Comment by kandy** [comment]
The reasoning for this was to move all knowledge about configuration to one module/class and split on read only part and mutable part to follow "interface segregation principle"

**Comment by wsakaren** [comment]
Thanks for info.
