### ISSUE TITLE
exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory

### ISSUE THREAD

**Issue by comunidademagento** [magento/magento2#1870]
See image and error.

![captura de tela de 2015-09-14 20 28 25](https://cloud.githubusercontent.com/assets/7476455/9864400/93879598-5b1f-11e5-9da2-51109f22aea7.png)

![captura de tela de 2015-09-14 20 29 35](https://cloud.githubusercontent.com/assets/7476455/9864413/b6555600-5b1f-11e5-8edc-2b7913a1ae96.png)

exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Framework/App/Resource/.' in /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Code/Generator.php:106 Stack trace: #0 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...') #1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...') #2 [internal function]: spl_autoload_call('Magento\\Framewo...') #3 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...') #4 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...') #5 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Framewo...') #6 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #7 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #8 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'resource', 'Magento\\Framewo...') #9 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array) #10 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #11 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #12 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'frontendFactory', 'Magento\\Framewo...') #13 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array) #14 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #15 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #16 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'frontendPool', 'Magento\\Framewo...') #17 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array) #18 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #19 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #20 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cacheFrontendPo...', 'Magento\\Framewo...') #21 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array) #22 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #23 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #24 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cache', 'Magento\\Framewo...') #25 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array) #26 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #27 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/ObjectManager/Environment/Developer.php(67): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #28 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(181): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Array) #29 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(384): Magento\Framework\App\ObjectManagerFactory->create(Array) #30 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(231): Magento\Framework\App\Bootstrap->initObjectManager() #31 /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/index.php(38): Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...') #32 {main}

**Comment by maksek** [comment]
Seems like exception is very clear - 'Can't create directory /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/

make var dir writable for webserver.

**Comment by dannymichel** [comment]
I've -R 777 var but am still getting the error

**Comment by ghost** [comment]
Giving full permission  (777) to var and pub directory after upgrade solved this issue for me.

Run  the command using .

php bin/magento setup:upgrade

chmod -R 777 var pub

clear cache.

rm -rf var/cache/\* var/generation/*
