### ISSUE TITLE
how to extend the order's attribute

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1873]

**Comment by okorshenko** [comment]
@LifeAsBook, could you please add more description to this ticket? What exactly do you want to change/extend? What are your requirements and pre conditions? What do you want to get in result? Thanks you!

**Comment by LifeAsBook** [comment]
@okorshenko i want to add the 3rd's orderID to my magento's order attribute

**Comment by sivaschenko** [comment]
@LifeAsBook, pay attention that Order model is extending \Magento\Framework\Model\AbstractExtensibleModel that enables custom attributes processing. As for adding custom columns to order grid, please take a look on the following ticket: https://github.com/magento/magento2/issues/1650

**Comment by LifeAsBook** [comment]
@sivaschenko  thank you! i don't understand  the role of the ExtensionAttributesInterface and ExtensibleDataInterface  which can you tell me about it?

**Comment by LifeAsBook** [comment]
@sivaschenko  
The following code and the fourth step not take a value, why
1、$payment = $this->_quote->getPayment();
2、$payment->setCustomAttribute(self::JD_ORDER_ID, $jdOrderResultArray['result']['jdOrderId']);
3、$this->quoteRepository->save($this->_quote);
4、$payment->getCustomAttribute(self::JD_ORDER_ID);

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
