### ISSUE TITLE
product addition problem

### ISSUE THREAD

**Issue by GGNB** [magento/magento2#1875]
I have added a product in the backend like this
![qq 20150915194806](https://cloud.githubusercontent.com/assets/14269355/9875977/15d26e36-5be5-11e5-89c6-4772ab91acc0.png)
but it's not show in the frontend
![qq 20150915200512](https://cloud.githubusercontent.com/assets/14269355/9875998/444c33b4-5be5-11e5-9f00-9b40b83571e7.png)

**Comment by melnikovi** [comment]
@GGNB double check if you selected qty, added product to this category and that cron jobs are running. If this doesn't help, please provide screenshots with product configuration.

**Comment by GGNB** [comment]
@melnikovi  it's just don't in the main category(what'new,women,
![qq 20150917114545](https://cloud.githubusercontent.com/assets/14269355/9924422/f001799c-5d31-11e5-9036-dcc4144455d1.png)
![qq 20150917114231](https://cloud.githubusercontent.com/assets/14269355/9924423/f3786bbc-5d31-11e5-92c1-b75c4e2791aa.png)

men)

**Comment by GGNB** [comment]
It will show in the second category
![qq 20150917114425](https://cloud.githubusercontent.com/assets/14269355/9924440/282a8192-5d32-11e5-9d33-d78e5229289d.png)

**Comment by GGNB** [comment]
@melnikovi  my product configurations
![qq 20150917114440](https://cloud.githubusercontent.com/assets/14269355/9924455/3f32c14c-5d32-11e5-8bcf-3aea289e6e02.png)

**Comment by melnikovi** [comment]
Could you check if display mode is set to display products for top level categories? It's on display settings tab, when you edit category. Also, are you using sample data?

**Comment by GGNB** [comment]
@melnikovi  yes,i'm using sample data,but it's not compeletely installed,by the way,I have gotten this problem.
![qq 20150918101215](https://cloud.githubusercontent.com/assets/14269355/9950531/245fed74-5dee-11e5-8376-5739760c147c.png)

**Comment by melnikovi** [comment]
@GGNB if there is an XML in Custom Layout Update field on Custom Design tab, please remove it or correct the issue with it and try to save category again. What was the initial value for Display Mode?

**Comment by GGNB** [comment]
@melnikovi  thank U,I have already solved the problem.thank U for your patient answers

**Comment by melnikovi** [comment]
@GGNB you are welcome. Please tell what was the issue, thank you.

**Comment by GGNB** [comment]
@melnikovi I install the sample data again like this:
1.git clone -b master https://github.com/magento/magento2.git
2.php -r "readfile('https://getcomposer.org/installer');" | php
3.php composer.phar config repositories.magento composer http://packages.magento.com
4.php composer.phar install
5.open firefox, begin install (don't choose 'sample data')
6.install success
7.php composer.phar require magento/sample-data:1.0.0-beta
8.php magento setup:upgrade
9.php magento sampledata:install admin
10.sampledata install success
memory_limit = 2048M

**Comment by melnikovi** [comment]
Sorry, I meant what was the solution to your issue?

**Comment by GGNB** [comment]
sorry,I have no solution.I just install It again.
