### ISSUE TITLE
Migration between servers 

### ISSUE THREAD

**Issue by ahmadalkaid** [magento/magento2#1876]
Hi Guys,

Just to test, I move the demo store from server to server. But the store goes down after the migration form the old server. 
So here some piece of the log file ,,,

[2015-09-15 05:47:15] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-09-15 05:47:15] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-09-15 05:47:15] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' element cannot be added as child to 'minicart.subtotal.container', because the latter doesn't exist [] []
[2015-09-15 05:47:15] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' tries to reorder itself towards 'minicart.subtotal', but their parents are different: 'minicart.subtotal.container' and '' respectively. [] []
[2015-09-15 05:47:15] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-09-15 05:47:15] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-09-15 05:47:15] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] [] 

Best,
-Kaid

**Comment by buskamuza** [comment]
Hi @ahmadalkaid , such records in the log most likely are not related to the issue itself.
Do you have any other information? With which error does it crash? Or it's just empty page you see?
Are there any errors in the web-server logs?

**Comment by ahmadalkaid** [comment]
Hi @buskamuza ,
Sorry I didn't explain more, but after I migrate the store from server to another I sow this message ,,
An error has happened during application run. See exception log for details. Could not write error message to log. Please use developer mode to see the message. 
And as I mansion before about the exception log from Magento, but in the /var/log/apache2/error_log I didn't find any error, sorry for that .

**Comment by buskamuza** [comment]
@ahmadalkaid , I see. Thanks for the information. By some reason it can't write to the log. Could you, please, try to enable 'developer' mode and see if the error appear on the page?
You can enable developer mode in `.htaccess` file - just uncomment this line https://github.com/magento/magento2/blob/develop/.htaccess#L5

**Comment by ahmadalkaid** [comment]
Hi @buskamuza ,
Thanks for that :+1: , and here is the exception that Magento through after enabling the developer mode .

exception 'Zend_Cache_Exception' with message 'cache_dir "/Library/WebServer/Documents/magento2/var/page_cache" is not writable' in /Library/WebServer/Documents/magento2/vendor/magento/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /Library/WebServer/Documents/magento2/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/Lib...') #1 /Library/WebServer/Documents/magento2/lib/internal/Cm/Cache/Backend/File.php(82): Zend_Cache_Backend_File->setCacheDir('/Library/WebSer...') #2 /Library/WebServer/Documents/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /Library/WebServer/Documents/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Factory.php(153): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true) #5 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Pool.php(67): Magento\Framework\App\Cache\Frontend\Factory->create(Array) #6 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Pool.php(146): Magento\Framework\App\Cache\Frontend\Pool->_initialize() #7 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/Cache/Type/FrontendPool.php(84): Magento\Framework\App\Cache\Frontend\Pool->get('default') #8 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/Cache/Type/Config.php(49): Magento\Framework\App\Cache\Type\FrontendPool->get('config') #9 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\App\Cache\Type\Config->_getFrontend() #10 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/ObjectManager/ConfigLoader.php(66): Magento\Framework\Cache\Frontend\Decorator\Bare->load('global::DiConfi...') #11 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/ObjectManager/Environment/Developer.php(76): Magento\Framework\App\ObjectManager\ConfigLoader->load('global') #12 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(181): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Array) #13 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(384): Magento\Framework\App\ObjectManagerFactory->create(Array) #14 /Library/WebServer/Documents/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(231): Magento\Framework\App\Bootstrap->initObjectManager() #15 /Library/WebServer/Documents/magento2/index.php(38): Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...') #16 {main}

**Comment by buskamuza** [comment]
@ahmadalkaid , you're welcome.
