### ISSUE TITLE
Default home page slider

### ISSUE THREAD

**Issue by afroz92** [magento/magento2#1877]
As we had default slider in RWD theme in 1.9.x , do we have such facility in Magento 2 Luma theme ?

**Comment by godban** [comment]
@afroz92 hello
No, Magento 2 have no slider by default. Current themes doesn't have such component.
But according to https://github.com/magento/devdocs/issues/344#issuecomment-139168968 it will be implemented in the future.

**Comment by okorshenko** [comment]
@afroz92 , if you have any additional questions, please, create a new ticket. Thank you
