### ISSUE TITLE
Remove php setting from .htaccess

### ISSUE THREAD

**Issue by amenk** [magento/magento2#1878]
The php_value settings do not work with PHP-FPM which is often used.

Even the memory_limit settings differ in the different .htaccess files (in the root folder, in pub/static).
And the memory limit recommended in http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html is also different (512M vs. 768M)

**Comment by xcomSteveJohnson** [comment]
When you say the settings do not work with PHP-FPM, are they ignored or do they cause problems?

**Comment by amenk** [comment]
As far as I know they are ignored.

**Comment by xcomSteveJohnson** [comment]
Changed the install guide to recommend 768M: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone

**Comment by daim2k5** [comment]
@amenk can we close this issue?
