### ISSUE TITLE
Search result page override

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#1880]
I am trying to override Search result page to show my own template.

I have did --

1. created di.xml and overrides the controller like this -

< preference for="Magento\CatalogSearch\Controller\Result\Index" type="CompanyName\Search\Controller\Search\Result" / >

2. In CompanyName/Search/Controller/Search/Result.php, i have used this code -

namespace CompanyName\Search\Controller\Search;
class Result extends \Magento\CatalogSearch\Controller\Result\Index
{
    public function execute($coreRoute = null)
    {
        return parent::execute($coreRoute);
    }
} 

3. in view/frontend/layout/, i have created catalogsearch_result_index.xml and used 

< referenceContainer name="content" >
            < block class="CompanyName\Search\Block\Search" template="CompanyName_Search::search/result.phtml" / >
        < /referenceContainer >  
4. created template file and put my code there.

After doing all this, it is appending my content to magento default search result.
![screen](https://cloud.githubusercontent.com/assets/6079017/9882938/eb434a22-5bf4-11e5-9ae0-804a829abfeb.png)

but i want to override this. Please help me to do this is in appropriate way.

**Comment by ankursachdeva11** [comment]
Override done.
I forgot to use name attribute into the block tag.

but i need to stop override on the basis of system configuration option.

When 'Yes', then it will override the controller.
When 'No' then it will show default controller.

Is there any way to do this?

**Comment by maksek** [comment]
GitHub issue must contain bug description with steps to reproduce, all HowTo questions please post in forum or other sources.
