### ISSUE TITLE
How to change the less variables in the php files?

### ISSUE THREAD

**Issue by choma828** [magento/magento2#1881]
Hi, everyone.

I'm working on Magento 2. I want to set the colors and other less variables in an extension's block.

eg: @primary__color

Anyone know how to do this?
Please help me.

Thanks

**Comment by godban** [comment]
@choma828 hello

Need clarification. You want to change Less variables via php? Or you need mechanism how to do it in extension?

**Comment by choma828** [comment]
Thanks for your reply.

I want to change the colors using extension's configurations. Is it possible?

**Comment by godban** [comment]
@choma828 only inside .less files for the moment

**Comment by choma828** [comment]
It's bad, this function will be implemented in the merchant version?

Or, do I need to find other way for it? eg: create a less file with color variables, when save the configurations

**Comment by godban** [comment]
> It's bad, this function will be implemented in the merchant version?

@choma828 no, but you can create feature request for that

> Or, do I need to find other way for it? eg: create a less file with color variables, when save the configurations

yea, sure, you can do it by yourself, add a generated source/_theme.less with variables, it should work

**Comment by choma828** [comment]
Thanks for your answer.

One more thing.

styles-l.less and styles-m.less files were compiled with the configuration values, but how to make them for multi-stores with different configuration values?

**Comment by godban** [comment]
@choma828 each storeview / store / website can have own theme, each theme can have own styles-l.less & styles-m.less

**Comment by choma828** [comment]
Thanks for your answer.

So, should I make the child themes for each stores? Is there any other way use only one theme?

**Comment by eug123** [comment]
Hi,
To have different styles for store views, there should be child themes assigned to each store view. As your changes for the store views involves just some color variable values, so your themes will just contain minimum set of files, actually you just need to have one _theme.less overrided in child themes

app\design\frontend\YourVendor\yourTheme\web\css\source\_theme.less
app\design\frontend\YourVendor\yourThemeDark\web\css\source\_theme.less
app\design\frontend\YourVendor\yourThemeLight\web\css\source\_theme.less

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
