### ISSUE TITLE
Import csv data

### ISSUE THREAD

**Issue by zhanyi8866** [magento/magento2#1884]
SYSTEM -- Export
    Entity Type:             Products
    Export File Format: CSV

result file: catalog_product_20150916_142806.csv

Next, import 'catalog_product_20150916_142806.csv'
    Entity Type:            Products
    Import Behavior:    Add/Update

Validation Results
Notice: Undefined index: Gear in D:\magento2\app\code\Magento\CatalogImportExport\Model\Import\Product\Type\AbstractType.php on line 170
Please fix errors and re-upload the file.

**Comment by voleye** [comment]
Hi @zhanyi8866 

Could you please, provide more details because I tried to do the same on a just installed Magento but can not reproduce the issue.
Could you recheck it on a latest code version?

**Comment by piotrekkaminski** [comment]
Closing as we did not hear any response. Please reopen if you can provide more details.
