### ISSUE TITLE
Magento 2 Portuguese, Brazilian translation

### ISSUE THREAD

**Issue by comunidademagento** [magento/magento2#1886]
https://crowdin.com/project/magento-2/pt-BR

There is only the file source.csv

All terms are translated.

How to collaborate with the translation Portuguese/Brazil?

**Comment by mazhalai** [comment]
@comunidademagento maybe this doc will help http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/xlate.html

**Comment by comunidademagento** [comment]
See images below ...

Why the phrase " Current User Identity Verification", it is not translated in Magento , but is translated into Crowdin?

https://crowdin.com/translate/magento-2/219/enus-ptbr#q=+Current+User+Identity+Verification

![captura de tela de 2015-09-16 17 36 38](https://cloud.githubusercontent.com/assets/7476455/9917783/e96cb2ce-5c99-11e5-9649-5538ddbab036.png)

![captura de tela de 2015-09-16 17 37 32](https://cloud.githubusercontent.com/assets/7476455/9917789/ef3f72fe-5c99-11e5-8218-d6718fcbf710.png)

**Comment by piotrekkaminski** [comment]
@comunidademagento Can you confirm you did the following:
- translated the phrases in Crowding
- exported the translated source.csv file from Crowding
- packaged the translation http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.html#config-cli-subcommands-xlate-dict
- copy it to app/i18n and check if it is picked up by Magento

and it failed?
