### ISSUE TITLE
Multiple select in layered navigation

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1887]
Hello, I've not found any options to use multiple selection (for the same attribute) for layered navigation. In Magento 1 this options was very frustrating, now is implemented?

**Comment by choukalos** [comment]
We plan on implementing this in the near term after our GA launch.  Internally we're tracking it as (MAGETWO-39787) to enhance our layered navigation.  Those enhancements include a category element ( to drill down via category ), multi-select (effectively or) within an attribute, and adding category to advanced search form.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Multiple-select-in-layered-navigation/idi-p/47229).
