### ISSUE TITLE
Beta to Release 

### ISSUE THREAD

**Issue by restaurantsupply** [magento/magento2#1888]
If I have the beta version and I start to build out the site when the release comes will I need to start all over again or can I just update the release changes??

**Comment by mprototype** [comment]
Just update the release changes. Magento 2 is ready enough to be developed
with and the community's momentum spinning up Magento builds will
significantly speed up final polishing on the platform.

All The Best,

Joel I. Hart
CEO


720.201.9594 (m)
303.335.0932 (o)

**Comment by piotrekkaminski** [comment]
Note there are also upgrade scripts you need to run to migrate password.
