### ISSUE TITLE
Before the function name "_"  What does it mean?

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1889]
![12](https://cloud.githubusercontent.com/assets/10986726/9923620/af5372d6-5d29-11e5-9f1f-65f99bc5a809.png)

**Comment by melnikovi** [comment]
@LifeAsBook this convention has been used to indicate private and protected methods and properties as a part of old coding standard. Now we use PSR standard http://www.php-fig.org/psr/, but in some classes you can still see examples of old style.

**Comment by LifeAsBook** [comment]
@melnikovi than you!
