### ISSUE TITLE
[PERFORMANCE] Configuration option to disable product specific layout update handles

### ISSUE THREAD

**Issue by tmotyl** [magento/magento2#189]
Magento provides layout update handles specific for each product e.g. PRODUCT_123
So for each product in each store view there is one layout cache record (with xml layout) even if you;re not using this feature.
if you have e.g. 1000 simple products, than you will also have 1000 cache entries, each for one product. If you are not using layout handles for specific products, than all these 1000 records are the same.
Actually most of the cache entries in the cache backend are cached layouts.

If there were configuration option for disabling usage of these update handles, than Magento would need to generate this layout xml only once. This way layouts could be generated once and reused between products, which would save a lot of rendering time.

The same problem applies for categories. Each category has also dedicated layout update handle which caused layout to be cached separately.

**Comment by ilnytskyi** [comment]
Wow it's 2020 and I faced the same issue.
![Selection_860](https://user-images.githubusercontent.com/3192770/94168542-07545580-fe8e-11ea-80a2-cab031c8d4e4.png)
If we do not need (do not use) updates for products and categories, we would just disable them and would save a lot of space in cache storage and have faster rendering on big catalogs.
For now I see possibility  to apply patches or pluginize those classes.
```
\Magento\Catalog\Helper\Product\View::initProductLayout
 
\Magento\Framework\View\Result\Page::addPageLayoutHandles
```
it would be extremely useful to manage it from config panel

**Comment by ilnytskyi** [comment]
When we removed entity ids from layout handles. We reduced used cache space significantly and it also improved overall page performance.
![Selection_639](https://user-images.githubusercontent.com/3192770/115952943-36e14400-a4e9-11eb-863f-b08a43a30edb.png)
