### ISSUE TITLE
File Permission Check Error

### ISSUE THREAD

**Issue by RGROCKS** [magento/magento2#1891]
Hi,
 I am installing magento 2 vanila  copy in my windows 8 system using wamp, but unable to install getting error in Step 1  :  Readiness Check 
Error Getting "File Permission Check Server Failed to respond. Please try again"

How can i resolve this ?
![issue](https://cloud.githubusercontent.com/assets/14318157/9925397/a5c97f72-5d28-11e5-92f0-7ea71d7ae76f.png)

**Comment by mazhalai** [comment]
@RGROCKS please check what [mode](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html) you are operating in. In certain modes, all details are not shown. More info the folders that need write permissions [here](http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html)

**Comment by mazhalai** [comment]
Thank you for reporting @RGROCKS, we have created MAGETWO-43039 to track a fix for this.

**Comment by sky4git** [comment]
I think it is probably the issue of 
 "/www/magento2/app/etc" writable directory permission.
"/www/magento2/magento2/var" writable directory permission.
"/www/magento2//htdocs/magento2/pub/media" writable directory permission.
"/www/magento2/htdocs/magento2/pub/static" writable directory permission. 

these directories which permission should be 777.
Thats what worked for me.
![file-permission-issue](https://cloud.githubusercontent.com/assets/8438024/9984493/e2a5960c-605b-11e5-9643-c9e36a56ec1f.PNG)

**Comment by darshanb87** [comment]
Hi,
I also face this issue but i did try continue on Try Again button and after some number of clicks its working fine for me.

**Comment by dmcdaniel12** [comment]
I had the same issue and did what darshanb87 said and was able to progress through.

**Comment by ferrarisaacv** [comment]
Hi,

Also had the same issue and did what darshanb87 and dmcdaniel12 said and was able to progress through. I did it like 10 -15 times.

**Comment by darshanb87** [comment]
Hi,
There is no file permission check required for windows system. If you are still facing this issue just remove disable from Next button by inspect element in browser and go ahead with click on Next button.

**Comment by haariiii** [comment]
Hi
I've tried continue many times but it didn't worked... 
I use windows 7..

**Comment by skjethva** [comment]
Hello
I am using window 7 and i am facing the same issue.
Please help

**Comment by darshanb87** [comment]
Hi sanjayjethva,
Follow my comment mentioned above. Open firebug in mozila and you can easily enable next button.

**Comment by mazhalai** [comment]
This issue has been resolved 2.0.0. Please open a new ticket if issue persists.

**Comment by HamiltonWang** [comment]
this happens to magento 2.0.0 too. Im using CentOS 7.0  and t doesn't progress though by clicking many times.

**Comment by mazhalai** [comment]
@HamiltonWang please do not comment on closed issues. Please open a new one.
