### ISSUE TITLE
RestFul: How to get all information of products by catalog_id?

### ISSUE THREAD

**Issue by BingQiangChen** [magento/magento2#1892]
How to write "searchCriteria"?
https://host/product/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=catalog_id&searchCriteria[filter_groups][0][filters][0][value]=1&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[current_page]=1&searchCriteria[page_size]=2"

thanks

**Comment by sakiss** [comment]
Have a look at a sample module that uses that:
https://github.com/magento/magento2-samples/blob/master/sample-module-service-contract-client/Block/ProductList.php

**Comment by choukalos** [comment]
if you use the search API you only get product id not sku, yet we only exposed the catalog api's that take sku.  Work around is as suggested do a getlist for search condition on id.  Team is tracking internally as a bug - (MAGETWO-43185) to address.

**Comment by maksek** [comment]
Please ask questions in forum
