### ISSUE TITLE
Error tracking ?

### ISSUE THREAD

**Issue by sakiss** [magento/magento2#1893]
Hi

I am developing a module and getting a blank page but i cannot found a way to track the errors.

I checked both the system.log and exception.log in the var/log folder with no luck. Also the var/report folder is empty.

Which is the way for a developer to track errors?
Any help/hint is really appreciated as i am stuck on that.

**Comment by mazhalai** [comment]
@sakiss you can turn on development [mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) to see detailed errors.

**Comment by sakiss** [comment]
Thanks @mazhalai 
I have this enabled but still cannot find info about errors. Where can i see them?

I partially solved my issue by displaying the errors through ini_set but it does not seem like a proper solution

**Comment by mazhalai** [comment]
@sakiss what about apache log? or nginx log? also can you check your browser for javascript errors if any?

**Comment by sakiss** [comment]
As said i find my way but i suppose that Magento has (or should have) an error logging process

**Comment by xcomSteveJohnson** [comment]
FWIW, I had a similar situation and found a 500 error in the apache access_log and by curling. Didn't really help ultimately though. Turned out to be bad syntax in env.php.

**Comment by orlangur** [comment]
Just make PHP errors display properly as usual: http://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display

This has nothing to do with Magento itself.

**Comment by sakiss** [comment]
@orlangur This concerns the display of the errors on the screen. 
I am referring to error logging.

**Comment by buskamuza** [comment]
@sakiss , it depends on type (or level) of error you have. If it's a syntax error, the code will just not run, so it's impossible to handle from inside the application. Such errors usually should be looked for in the php/apache error logs.

**Comment by orlangur** [comment]
@sakiss, surely, if you faced with a problem which you believe could be handled using error log, please provide steps to reproduce it.

For example, in most cases `Fatal Error` could not be logged by application while `Recoverable Error` could.
