### ISSUE TITLE
Issue with OrderItemRepository

### ISSUE THREAD

**Issue by dpotkoc** [magento/magento2#1894]
When I try to use \Magento\Sales\Api\OrderItemRepositoryInterface I got an error, which makes OrderItem service contracts/apis imposible to use.

I seems Magento\Sales\Model\Resource\Order\Item should implement OrderItemResourceInterface

this is error:
Recoverable Error: Argument 1 passed to Magento\Sales\Api\Data\OrderItemInterfacePersistor::__construct() must implement interface Magento\Sales\Model\Spi\OrderItemResourceInterface, instance of Magento\Sales\Model\Resource\Order\Item given, called in /home/dpotkoc/public_html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 101 and defined in /home/dpotkoc/public_html/magento2/var/generation/Magento/Sales/Api/Data/OrderItemInterfacePersistor.php on line 60

**Comment by okorshenko** [comment]
please, remove all files from  /home/dpotkoc/public_html/magento2/var/generation and try again

**Comment by ivanweiler** [comment]
Confirming the problem, exactly like @dpotkoc wrote. /var/generation cleared :)

Tested on merchant beta, but I believe problem still exists.

**Comment by mbrinton01** [comment]
This issue should be resolved now that #1957 has been merged. Closing the issue.
