### ISSUE TITLE
Improve code writing in admin textarea with a Syntax Highlighter

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1896]
Hello, i'm currently testing 1.0 beta and I think who all the textarea of block could be improved with a Syntax Highlighter like CodeMirror or Ace Editor.

it would be a big improvement that should not take away too much work.

**Comment by tkacheva** [comment]
Internal ticket for improving dev experience MAGETWO-54478

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Improve-code-writing-in-admin-textarea-with-a-Syntax-Highlighter/idi-p/47226).
