### ISSUE TITLE
«Unknown column 'failures_num' in 'field list'» (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1898]
My fix: https://mage2.pro/t/71

**Comment by okorshenko** [comment]
@dfediuk , could you please add more details? Pleas, describe preconditions for this issue

**Comment by okorshenko** [comment]
@dfediuk , thank you for reposting the issue.
We was able to reproduce this issue by the following steps:

1 Checkout merchant beta release https://github.com/magento/magento2.git *master* branch
2 Install Magento instance
3 Update code base with latest changes from develop branch  https://github.com/magento/magento2.git *develop* branch
4 Clean caches
5 run bin/magento setup:upgrade
6 Go to admin login page
7 Enter admin login and password
8 Click Sign In

**Current Result**
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'failures_num' in 'field list', query was: UPDATE `admin_user` SET `failures_num` = ?, `first_failure` = ?, `lock_expires` = ? WHERE (user_id IN ('1'))
```

**Extepected Result**
Admin user successfully logged in 

Internal ticket **MAGETWO-43512** is created to track this issue.
Thank you!

**Comment by piotrekkaminski** [comment]
This issue was fixed and should be published soon.
