### ISSUE TITLE
why the database of [catalog_category_entity] which the column  entity_id,attribute_set_id,parent_id,etc..not in table [eav_attribute] ? 

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1899]

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
