### ISSUE TITLE
the Magento\Sales\Model\Resource\Order  EAV entity  why not extend  Magento\Eav\Model\Entity\AbstractEntity

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1900]
 EAV based entity models also extend Magento\Framework\Model\AbstractModel.
 EAV based resource models extend Magento\Eav\Model\Entity\AbstractEntity, rather than
\Magento\Framework\Model\Resource\Db\AbstractDb

Is Magento\Sales\Model\Resource\Order not an EAV entity?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
