### ISSUE TITLE
Sql Error on saving configurable product 

### ISSUE THREAD

**Issue by mad0house** [magento/magento2#1901]
When saving a configurable product with 2 attributes to a new set get the following message

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mag2`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`)), query was: INSERT INTO `catalog_product_entity` (`type_id`, `sku`) VALUES (?, ?)

Product has 2 attributes
Colour(11) Size(5) for a total of 55 product skus, each of the colour attribute has had a custom image, price the same for all skus, and quantity the same for all skus of 5.

Using the latest code bases as of today.

**Comment by piotrekkaminski** [comment]
Can you try again on the latest version? We cannot reproduce it.

**Comment by mad0house** [comment]
As of today works ok on a fresh install,

**Comment by jason-vivid** [comment]
Just received this exact error running v2.0.2.

Steps to reproduce:
1. Create Simple Product
2. Change the attribute set (configurable product workaround).
3. Fill out product data
4.  Select "Create Configurations"
5. Select Attributes - two attributes created for this store(sizes (text swatch - 11 values) & color (visual swatch - 28 values)).
6. Selected all 11 sizes and 14 of the color values.
7. Generate products populates correctly.
8. Save.

**Comment by jason-vivid** [comment]
The apache error.log solved this for me.

[Wed Feb 03 19:40:22.281476 2016] [:error] [pid 17178] [client 69.14.235.233:59851] PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0, referer:  https://website

Increasing the limit in .htaccess solves the problem. PHP default is 1000.  I bumped up to 5000.

`php_value max_input_vars 5000`

**Comment by to-var** [comment]
Increased PHP max_input_vars to 5000 worked for me. Thanks @jason-vivid
