### ISSUE TITLE
Issue after Magento installation.

### ISSUE THREAD

**Issue by sumanparihar** [magento/magento2#1902]
Hello,

I have installed the magento2 with sample data using zip folder. After installed this, it's work fine. But after 2 day when i open again in browser, i got error as below:-

Warning: DOMDocument::loadXML(): AttValue: &quot; or ' expected in Entity, line: 1 in E:\wamp\www\magento2\lib\internal\Magento\Framework\Config\Dom.php on line 327

When i set developer mode via .htaccess then back-end is working fine but still i got error in front-end.

Thank-you for help in advance!

Thanks
Suman

**Comment by mazhalai** [comment]
@sumanparihar can you please provide more details: version of magento, which branch are you using, master or develop, PHP version, and server details.
Have you introduced any custom modules?
