### ISSUE TITLE
CSS Changes - Cache Clearing

### ISSUE THREAD

**Issue by danielc1234** [magento/magento2#1904]
I am making some simple changes to the CSS, but does not show up unless I physically delete the pub folders (except .htaccess) and all the caches under the /var folder. This gets very old real quick to have to do on each and every change.

Is there a way to just NOT have any of the css cached so it makes it easier to work? Or can someone advise me the best way to do this? I'm used to the magento 1 where you could just turn off css combining and your changes would just show.

Thanks
Dan

**Comment by alankent** [comment]
Have you looked at http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html ?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
