### ISSUE TITLE
data-bind i18n expressions with JavaScript function calls are used in the core but untranslatable due to regular expression and architectural limitations

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1905]
An example of expression which can not be translated: https://github.com/magento/magento2/blob/444e252d40b3a5d5cca3468a9819743af8ed3513/app/code/Magento/Ui/view/base/web/templates/grid/controls/bookmarks/bookmarks.html#L18

The bug description in details: https://mage2.pro/t/72

**Comment by okorshenko** [comment]
@dfediuk , thank you for reporting. Could you, please, create a Pull Request with your fix?

**Comment by dfediuk** [comment]
The similar (but not the same) bug https://github.com/magento/magento2/issues/1951

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44049

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-44049 is closed and delivered to mainline. Please, let us know if you still have an issue.
