### ISSUE TITLE
official support for mariadb 10+

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1906]
Is it possible to add official support for MariaDB 10.0+? I've tested Magento 2 with MariaDB and all seems to work just fine. 10.0+ is really a drop-in replacement for MySQL 5.6 (and contains additional features that needn't be used).

I believe Magento 2 should fully support completely open-source software where others can contribute to software belonging to the LAMP stack. I would think it would be minimal effort to support MariaDB, and by doing so it would also help related code to be more platform-agnostic and prevent vendor lock-in.

Oh, and.... Oracle is the devil. Can't leave that out.

**Comment by alankent** [comment]
If MariaDB takes responsibility to be compatible with MySQL, what are you suggesting Magento do? 

(on practical front we need to keep officially supported list short or else automated tests blow out - eg test everything with MySQL, MySQL cluster, MariaDB, clustrix, persona, tesora, etc? Then test every web browser. Then test every web server. Then every cache.... Oh, every version of php? You get the idea. Basically needs to be a real need. Is there some reason Magento needs to take responsibility for MariaDB compatibility?)

**Comment by markoshust** [comment]
Understood.




I think moreso than adding it to test stack, if it can at least be supported within issues/tickets if issues arise. I've heard a lot in the past that since "it's not on the supported versions list, I'm closing this ticket". It would be nice to at least investigate or respond to issues that may arise rather than just staying it's not supported.




Basically if something comes up, perhaps community or issuer can supply a patch that could fix and be backwards compatible with MySQL and all tests, rather than not implement a fix at all.

**Comment by choukalos** [comment]
@markoshust We totally welcome community support for MariaDB (PR's etc).  I think as long as MariaDB has committed to being MySQL compatible we shouldn't have any issues.  

If in the off chance there are any issues please feel free to reach out to me and I can drive those internal discussions to see how we want to handle as I'm aware of a number of SI's and merchants using MariaDB rather than MySQL in our community.

**Comment by markoshust** [comment]
Great, thanks!
