### ISSUE TITLE
Admin grid uses grammatically incorrect phrase «1 records found»

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1907]
See https://github.com/magento/magento2/blob/444e252d40b3a5d5cca3468a9819743af8ed3513/app/code/Magento/Backend/view/adminhtml/templates/widget/grid.phtml#L54-L56

https://github.com/magento/magento2/blob/444e252d40b3a5d5cca3468a9819743af8ed3513/app/code/Magento/Backend/view/adminhtml/templates/widget/grid/extended.phtml#L65-L67

Surely Magento 2 must distinguish the singular and plural cases.

**Comment by andimov** [comment]
@mage2pro 
Could you please add the description of steps, actual result and expected result to this ticket?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Admin-grid-uses-grammatically-incorrect-phrase-1-records-found/idi-p/45795).
