### ISSUE TITLE
Wrong PHPDoc result type for \Magento\Eav\Model\Entity\Attribute\AbstractAttribute::getEntityType() method

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1908]
https://github.com/magento/magento2/blob/444e252d40b3a5d5cca3468a9819743af8ed3513/app/code/Magento/Eav/Model/Entity/Attribute/AbstractAttribute.php#L441

Must be \Magento\Eav\Model\Entity\Type, not string

**Comment by okorshenko** [comment]
@dfediuk , thank you for reporting the issue. Internal ticket MAGETWO-43098 is created to track this issue

**Comment by piotrekkaminski** [comment]
This issue is resolved and should be published soon.
