### ISSUE TITLE
Attribute labels on admin category pages are untranslatable

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1909]
This is a long term bug from Magento 1.x, and still is in Magento 2: attribute labels on admin category pages are untranslatable.
I fixed it for myself with a plugin: https://mage2.pro/t/73
But surely it must be in the core.

![fireshot capture 1 - categories _ categ_ - http___localhost com_900_store_zudra5uw_catalog_category_](https://cloud.githubusercontent.com/assets/83204/9980511/44463fd6-5fa5-11e5-9fe9-8be811eb7b39.png)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Attribute-labels-on-admin-category-pages-are-untranslatable/idi-p/44892).
