### ISSUE TITLE
Module detection not sensible enough

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#1910]
I have an module `Cotya_Debug` but had it inside a directory `code/Cotya/DebugModule`.

Thats obviously wrong, the module was not even loaded.  
Still, the cli `setup:upgrade ` command has listed it, so I did first not notice, I had named the Directoy wrong.

I use the `"magento/product-community-edition": "1.0.0-beta2"` release.

can someone reproduce this? maybe I just messed up my environment

**Comment by mazhalai** [comment]
@Flyingmana can you clarify was this within `app/code/Cotya/DebugModule`?
Also did you create `etc/module.xml` as well as `composer.json`

**Comment by Flyingmana** [comment]
the most obvious sign it was not loaded occurred while I debugged why my controller did not work. Dont know the exact place, but in the list of modules which was iterated, the module was not listed.

So simplest way to reproduce the Issue for me: Module name is `Cotya/Debug`  
Have it in `app/code/Cotya/DebugModule`: route does not work.  
Have it in `app/code/Cotya/Debug`: route does work


`etc/module.xml` does exist, and has `...<module name="Cotya_Debug" setup_version="0.1.1" >...`

`composer.json` is also there, but I used the module via direct git checkout, which caused the mismatch in name.


Just tried it out again, the module is still listed on config->advanced->advanced->"disable module output"
Maybe it is only some parts which do not work, at least the frontend route does not work with the wrong named directory.
 
not important, still wanted to report it.
maybe someone adds a warning during setup or module:status command for this

**Comment by mazhalai** [comment]
@Flyingmana we have created MAGETWO-43502 to investigate.

**Comment by mazhalai** [comment]
@Flyingmana do you still have this issue on latest 2.0.0?

**Comment by Flyingmana** [comment]
No, Issue is not occuring anymore :+1:
