### ISSUE TITLE
Admin «WYSIWYG Editor» popup is untranslatable

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1911]
![wysiwyg-editor](https://cloud.githubusercontent.com/assets/83204/9983039/2a688598-5ff9-11e5-973a-1c1c5f97a13c.png)

As I see it does not use any form of translation.
For example, the title declaration and usage:
https://github.com/magento/magento2/blob/444e252d40b3a5d5cca3468a9819743af8ed3513/app/code/Magento/Catalog/view/adminhtml/templates/catalog/wysiwyg/js.phtml#L56

https://github.com/magento/magento2/blob/444e252d40b3a5d5cca3468a9819743af8ed3513/lib/web/prototype/window.js#L634

**Comment by anton-huz** [comment]
Hm..
[Not actual any more](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/adminhtml/templates/catalog/wysiwyg/js.phtml#L48). But you was right. There was no possibility to translate.
