### ISSUE TITLE
Allow Arbitary Block Objects

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#1912]
while we already have an Interface for Blocks (`BlockInterface`), there is still a place, which enforces usage of the abstract Block class (`\Magento\Framework\View\Element\AbstractBlock`).

https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/View/Layout/Generator/Block.php#L261-L265

While its not a problem to extend from there, I think it is not necessary for all Blocks

**Comment by voleye** [comment]
@Flyingmana ,Thank you for the idea! We have created an issue in the product backlog. We will get back to you once we complete the analysis.

**Comment by davidalger** [comment]
@voleye Can you provide an update on what the result of the internal analysis of this was?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Allow-Arbitary-Block-Objects/idi-p/45792).
