### ISSUE TITLE
Cant install magento2 on shared server

### ISSUE THREAD

**Issue by rohitgoel18** [magento/magento2#1914]
HI yesterday i have try to install magento on my server which is a shared server. BUt i got error during installation that MySQL version is not supported.My MySQL version is 5.5 but it seems magento2 needs at-least 5.6 . For this i have try to upgrade my MySQL but my host says this is not applicable on shared server,.
Does it mean that magento cant install on shared servers ?
Please suggest some solution.

thanks

**Comment by dfediuk** [comment]
Just carefully choose another hosting which comply with the Magento 2 requirements (includung MySQL 5.6 support).

**Comment by mazhalai** [comment]
@rohitgoel18 Magento needs MySQL 5.6. Read this [thread](https://github.com/magento/magento2/issues/1740#issuecomment-135986837) for more details.

**Comment by alankent** [comment]
"Does it mean that Magento cant install on shared servers ?"  It means you cannot installed on a shared server where they don't support MySQL 5.6. MySQL 5.6 GA was early 2013 http://www.oracle.com/us/corporate/press/1904335, so it is hardly new any more.

**Comment by choukalos** [comment]
Yes you can install on a shared server.  

Your host needs to support MySQL 5.6 along with PHP 5.5+ .  

In addition if you do not have command line access to your server you'll need to use git to get the code on your development machine, do a composer install and then zip up that directory structure to upload to your shared host.
