### ISSUE TITLE
Unnasigned attributes show for attribute set

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#19157]
### Preconditions (*)

1. Magento 2.2.6
2. PHP 7.1
3. Cpanel Centos 7
4. Mysql

### Steps to reproduce (*)

1. Go to Stores -> Attributes -> Attribute set and create a new attribute set Key as an example
2. Go to Stores -> Attributes -> Product and create some attributes, size, shape and hole size as examples. Navigate back to the created attribute set and add/assign the newly created attributes to the attribute set "Key"
3. Unnasign unwanted attribute "color"  from Attribute set, reindex, flush etc. in Magento 2
3. Go to Catalog -> Products -> Add  Product Configurable Product
4. Choose the newly created attribute set on the "New Product" page
5. Enter name, price etc.
6. Scroll down to configurations "Configurable products allow customers to choose options (Ex: shirt color). You need to create a simple product for each configuration (Ex: a product for each color)." and click "Create Configurations"
7. All product attributes display in create configurations section, even the unassigned attribute color from step "3."
### Expected result (*)

1. Go to Stores -> Attributes -> Attribute set and create a new attribute set Key as an example
2. Go to Stores -> Attributes -> Product and create some attributes, size, shape and hole size as examples. Navigate back to the created attribute set and add/assign the newly created attributes to the attribute set "Key"
3. Unnasign unwanted attribute "color"  from Attribute set, reindex, flush etc. in Magento 2
3. Go to Catalog -> Products -> Add  Product Configurable Product
4. Choose the newly created attribute set on the "New Product" page
5. Enter name, price etc.
6. Scroll down to configurations "Configurable products allow customers to choose options (Ex: shirt color). You need to create a simple product for each configuration (Ex: a product for each color)." and click "Create Configurations"
7. Only assigned attributes should display for the attribute set "Key" for our new product. The unnasigned attribute color should not show and netiher should any other attributes which are not assgined to our attribute set.
8. If an attribute(s) are removed or unnasigned from an attribute set, they should not still show in "Create confiiguratons" in add/edit product pages in the backend admin

### Actual result (*)

1. All attributes show, even the unassigned ones in the Create configurations section
2. Also, when one or more attributes assigned to an attribute set, are unassigned form an attribute set, they still show in the "create configurations" section even though they were removed.

**Comment by magento-engcom-team** [comment]
Hi @GlobalOutsourcing. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@GlobalOutsourcing do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by GlobalOutsourcing** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @GlobalOutsourcing. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @GlobalOutsourcing, here is your [Magento instance](http://34.228.235.121/i-19157-2-2-6/).
Admin access: [http://34.228.235.121/i-19157-2-2-6//admin](http://34.228.235.121/i-19157-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by GlobalOutsourcing** [comment]
@magento-engcom-team 

> Hi @GlobalOutsourcing, here is your [Magento instance](http://34.228.235.121/i-19157-2-2-6/).
> Admin access: http://34.228.235.121/i-19157-2-2-6//admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

Reproduced the issue on the new instance provided.

Unassigned product attribute color, for example, shows when creating a product with the new attribute set.

After assigning new or existing product attributes to an attribute set and then removing the same one or more attributes from the set after, they still show in "create configuration" section as well.

**Comment by orlangur** [comment]
Observed system behavior is correct, this is intentional change compared to Magento 1 so that there is no need to assign attribute to attribute set before creating configurations.
