### ISSUE TITLE
Rename confusing CategorySetup class name

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#1915]
There is a class `\Magento\Catalog\Setup\CategorySetup` which takes care of setup for `catalog_product` and `catalog_category` entities. 

This name is confusing and better name would be `CatalogSetup`.

**Comment by davidalger** [comment]
@wojtekn Would you like to submit a PR which effects the requested name change?

**Comment by wojtekn** [comment]
@davidalger I could, however at this point it could introduce backward compatibility issue. Do you think it still could be fixed?

Also, I guess this would also need to be done in EE code. What is preferred procedure to achieve this for both CE and EE?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rename-confusing-CategorySetup-class-name/idi-p/45789).
