### ISSUE TITLE
Backend customer form doesn't render if custom customer attribute is added

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#1916]
I installed custom customer attribute in a way shown on Magento 2 training which is similar to one from @Vinai comment:

https://github.com/magento/magento2/issues/1238#issuecomment-105034397

            $customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);

            $customerSetup->addAttribute(
                \Magento\Customer\Model\Customer::ENTITY,
                'nickname',
                [
                    'label'            => 'Nickname',
                    'required'         => 0,
                    'system'           => 0,
                    'position'         => 100
                ]
            );

            $customerSetup->getEavConfig()->getAttribute('customer', 'nickname')
                ->setData('used_in_forms', ['adminhtml_customer'])
                ->save();

Attribute is properly installed as I see it in `eav_attribute`, `customer_eav_attribute` and `customer_form_attribute` tables. However, backend customer form doesn't work for me anymore and it is empty. It looks that the whole `main-col` container is missing in rendered html. Store is in developer mode, logs are empty. I cleared `var/cache/*`, `var/generation/*` and `pub/static/*`.

When I change my custom attribute property `is_visible` to 0 manually in database, form works again.

Any idea what could be wrong?

**Comment by voleye** [comment]
Hi @wojtekn 

I tried to do the same but it works for me.
Looks on an error during rendering. (see the file lib/internal/Magento/Framework/View/TemplateEngine/Php.php, method "render")
If you are able debug this exception probably you will see the error. But any way this error should be present in your logs.

Could you remove "./var/log" or "./var/report" folders then trigger error by opening broken customer page  and then check these folders again?

**Comment by wojtekn** [comment]
Thanks for checking this @voleye. I tried it again on fresh installation on master and develop branches and it looks it works well on develop and it doesn't work on master. I'm not sure if it should be considered as issue then.

**Comment by voleye** [comment]
@wojtekn no problem, please feel free to ask if you have any additional questions

I closed this issue since it was fixed in develop branch

**Comment by phanikumar111** [comment]
How to add the custom field in registration form and save from frontend
