### ISSUE TITLE
Exception catching in catalog/product/view controller may be too broad

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#1918]
I was working on adding plugin for block on PDP and made a mistake in plugin class name. I couldn't figure out what is wrong for a while as PDP was returning 404 error. Then I noticed that `Magento\Catalog\Controller\Product\View::execute()` displays 404 error if any `Exception` is thrown. 

Isn't it too broad? I think it would be better to throw 404 only when product doesn't exist and let other exceptions go through.

For reference, I used `Training\Test\Block\Product\View\DescriptionPlugin` class name and put this in `di.xml` file:

    <type name="Magento\Catalog\Block\Product\View\Description">
        <plugin name="product-view-desription-plugin"
                type="Training\Test\Block\Product\View\Description" sortOrder="10" />
    </type>

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by wojtekn** [comment]
@daim2k5 why you closed this? this isn't a question but issue.

**Comment by daim2k5** [comment]
@wojtekn hi i could reproduced the behaviour and also to other people tagged this with question and forum

**Comment by wojtekn** [comment]
@daim2k5  so do you consider this as good behavior?

**Comment by daim2k5** [comment]
@wojtekn i spent me free time to scan all issues and help the magento 2 team / community to resolve or help with issue. As i mention before and i explained this before i don't see a issue. Other People taged also the same way. So 3 people have the same opinion on this. So whats bad to close the issue and give you the hint to please use the forum?

**Comment by daim2k5** [comment]
https://community.magento.com/t5/Just-Ask-Alan/Exception-catching-in-catalog-product-view-controller-may-be-too/m-p/22346#U22346

**Comment by wojtekn** [comment]
Thanks @daim2k5, I explained it more there.
