### ISSUE TITLE
Bug: the dropdown «Page Layout» on admin category page is untranslatable (and my fix)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1919]
The dropdown «Page Layout» on admin category page is untranslatable due to Magento 2 core bug:

![untitled-1](https://cloud.githubusercontent.com/assets/83204/9990474/5145e8f6-606a-11e5-8da1-5edfe37451d0.png)

My fix: https://mage2.pro/t/74

**Comment by okorshenko** [comment]
@dfediuk , thank you for reporting. Could you, please, create a Pull Request with your fix?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Bug-the-dropdown-Page-Layout-on-admin-category-page-is/idi-p/45787).
