### ISSUE TITLE
Bug: «Transaction Type» value on «Sales» → «Transactions» → <transaction> admin screen is untranslatable (and my fix)

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#1920]
![magento2-01](https://cloud.githubusercontent.com/assets/83204/10006543/c62c8ee8-60c6-11e5-9b9a-2057bfe999ec.png)

My fix: https://mage2.pro/t/75

**Comment by okorshenko** [comment]
@dfediuk , thank you for reporting. Could you, please, create a Pull Request with your fix?

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-43911

**Comment by YevSent** [comment]
Fixed on develop branch https://github.com/magento/magento2/commit/5b3e39f3bc9f6ca3794a733fc0de6554602b6dd5.
