### ISSUE TITLE
Wrong (nonsense) title "Select Items" for actions dropdown on admin orders grid

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1921]
It could be "Actions" (as for admin product grid) or "Select an Action".
"Select Items" is just nonsense here.

![magento2-03](https://cloud.githubusercontent.com/assets/83204/10007508/89d5e522-60ce-11e5-922c-34a301c51c0b.png)

**Comment by pboisvert** [comment]
comment makes sense (label is not helpful) but also low priority overall

**Comment by MomotenkoNatalia** [comment]
Thanks for reporting this issue! Internal ticket - MAGETWO-47289

**Comment by MomotenkoNatalia** [comment]
Changes are currently in the mainline. Issue can be closed.
