### ISSUE TITLE
Bug: order statuses in admin order grid are not translatable automatically (and my fix)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1922]
![magento2-04](https://cloud.githubusercontent.com/assets/83204/10008355/4453e924-60d6-11e5-89c1-3cfdc2d820a2.png)

You can translate order statuses manually in «Stores» → «Order Status» admin section.
But it is inconvenient because:
- you must do it manullay for each new Magento installation
- it works for a single language but does not work for multistore Magento installation with multiple languages.

My fix for automatical translation: https://mage2.pro/t/76

**Comment by okorshenko** [comment]
@dfediuk , thank you for reporting. Could you, please, create a Pull Request with your fix?

**Comment by okorshenko** [comment]
@dfediuk , it would be great if you can combine all translation fixes into one Pull Request. Thank you for your great contribution!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Bug-order-statuses-in-admin-order-grid-are-not-translatable/idi-p/45784).
