### ISSUE TITLE
Papal Express checkout review page 

### ISSUE THREAD

**Issue by niranjanleanswift** [magento/magento2#1923]
When we are trying to create the order using paypal express checkout and after the review the order item and when we are trying to place the order it shows the following error.

Fatal error: Call to a member function getPayment() on boolean in D:\XAMPP\htdocs\magento2marketplace\app\code\Magento\Paypal\Observer\HtmlTransactionIdObserver.php on line 40

**Comment by asemenenko** [comment]
@niranjanleanswift 
You are using Windows, is problem reproduced on Linux environment as well?

**Comment by dkvashninbay** [comment]
On what branch do you face this issue?

**Comment by niranjanleanswift** [comment]
@asemenenko I have facing the problem in windows is that specific to the OS . and I faced the issue in the developer branch

**Comment by piotrekkaminski** [comment]
@asemenenko any updated? we should support Windows.
