### ISSUE TITLE
Not needed button Update on checkout

### ISSUE THREAD

**Issue by MaxYaroshenko** [magento/magento2#1924]
Could you explain what logic of button Update? http://take.ms/55GaJ
It shows only when configurable product in the cart. Where are shipping methods?

**Comment by asemenenko** [comment]
@MaxYaroshenko 
It seems that in you case configurable product is not physical (virtual). Due to this fact shipping address is not displayed as well as shipping methods.

**Comment by MaxYaroshenko** [comment]
Thank you for your explanation). One concern left, for what button 'update' need?

**Comment by asemenenko** [comment]
@MaxYaroshenko 
Billing address can initiate total amount update, thus needs to be saved before render the payment form. Reloading the payment form every time user update any of the field is not a considered as a best UX practice. Especially for iFrame based payment integrations.

**Comment by piotrekkaminski** [comment]
@MaxYaroshenko @asemenenko can I close this issue?

**Comment by MaxYaroshenko** [comment]
If you think that current behavior is proper.
