### ISSUE TITLE
Correct way to horizontally scale and possible compile bug

### ISSUE THREAD

**Issue by owenhaynes** [magento/magento2#1925]
Tried to use Kubernetes with Magento trying to work out the steps needs to set up.

I copy in the configuration files "config.php, env.php" . I would of thought this would of been enough. 

This did not work so I thought the code needed compiling so ran bin/magento setup:di:compile
and then get the following error.

[ReflectionException]                                                                                
  Class Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\\Config\Attribute does not exist

So no idea what is wrong, or if theses are even the correct steps,

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [technical issues forum](https://community.magento.com/t5/Technical-Issues/bd-p/magento-2-technical-issues) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
