### ISSUE TITLE
Magento\Framework\HTTP\Client::getInstance() creates wrong class names

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#1927]
Calling `\Magento\Framework\HTTP\Client::getInstance();` cannot but error with `PHP Fatal error:  Class 'Magento\Framework\HTTP\Client_Curl' not found in /vagrant/lib/internal/Magento/Framework/HTTP/Client.php on line 38`, because of the frontend resolve logic: https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/HTTP/Client.php#L37

Changing it to `$class = __CLASS__ . "\\" . str_replace(' ', '/', ucwords(str_replace('_', ' ', $frontend)));` fixes it.

Also, I'm not really sure of the usefulness of a frontend param here, because another frontend implementation would need to be in the `Magento\Framework\HTTP` namespace.

Related question: what's the standard way of doing HTTP requests from M2? Should I still use that class above or do you think I'd rather go a new dependency (like Guzzle)?

**Comment by adragus-inviqa** [comment]
Regarding that last note (Guzzle), do you think it would be worthwhile to have a modern HTTP Client bundled with M2? I know people will start integrating M2 alot with other services, especially with the new integration features. 

Having said that, if you deem `Magento\Framework\HTTP\Client` sufficient, fine by me.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by adragus-inviqa** [comment]
@davidalger - forum or no forum, the bug's still there.

Here, I've deleted my question post so that this won't be tagged "forum", because you guys seem to close *bugs* if they have even a slight hint of interrogation in them.

Stop closing bugs, people.

**Comment by davidalger** [comment]
@adragus-inviqa Please update with current details and steps to reproduce the bug. Currently the link provided to the HTTP\Client class is a dead 404'ing URL. Also I cannot find the `getInstance` method anywhere in the `Magento\Framework\HTTP` namespace. The proper way to create an instance of the client class is to use the factory class create() routine.

**Comment by adragus-inviqa** [comment]
It was fixed in RC: https://github.com/magento/magento2/commit/b5cea5c4e21eb5c3a58e5db99df80f1d15cff44b

Guess this is a dupe of https://github.com/magento/magento2/issues/1435.

All good. Closing.
