### ISSUE TITLE
php magento setup:di:compile doesn't work

### ISSUE THREAD

**Issue by andreymoskvenkov** [magento/magento2#1928]
It compiles all tests in lib/Magento/Framework folder, which throw errors. Need to exclude tests, fixtures and helper methods for tests from compliling.

**Comment by mazhalai** [comment]
@andreymoskvenkov are you on `master` or `develop` branch?  Can you post what error did you get?

**Comment by andreymoskvenkov** [comment]
We have got an Enterprise release of Magento2 from Magento team. It is not Gidhub version.
I have got tons of errors from tests. One of them: Reflection Exception: Not_Existed_Class does not exist.

**Comment by andreymoskvenkov** [comment]
After the latest release of Magento2 EE it works now on the Server (Ubuntu Linux), but still does not work locally on Windows. Seems that the problem is reproduced only on Windows developer's machines.
