### ISSUE TITLE
Installation Error : PHP Extensions "0" must be loaded.

### ISSUE THREAD

**Issue by mrugeshrocks** [magento/magento2#193]

**Comment by blackqubers** [comment]
To fix the PHP Extensions “0” must be loaded issue while installing the magento , Please follow the below codes. Please check the below link

https://magentoextensiondevelopers.wordpress.com/2015/04/08/magento-issue-php-extensions-0-must-be-loaded/

**Comment by buskamuza** [comment]
@vigentocommerce , could you, please, provide more information about your installation process for Magento 2? Fixe in app/code/core/Mage/Install/etc/config.xml is not for Magento 2, Magento 2 doesn't have such module.
