### ISSUE TITLE
Filter clearing link is too far from filters on admin orders grid when using a wide PC screen

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1930]
![magento2-06](https://cloud.githubusercontent.com/assets/83204/10025787/b527d2a6-6166-11e5-8616-511c96dccf40.png)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by dfediuk** [comment]
I consider it as a user experience bug. 
Does the Magento 2 team have a different view?
