### ISSUE TITLE
Bug: Magento 2 ignores simple product with variations in the Grouped product#

### ISSUE THREAD

**Issue by Smartos76** [magento/magento2#1932]
Hello,

I created a Grouped product and added simple products with variations. Unfortunately, in the grouped product, the product does not appear with the variations. It appears only like a simple product without the variations. Do I have to change settings somewhere? 

Thanks.

Sam

**Comment by voleye** [comment]
Hi, @Smartos76 
Grouped product may contains only the products that does not have required options (as in your case). 
Could you share an example why you need to solve such exercise?

Thank you for helping us make Magento better!

**Comment by Smartos76** [comment]
Hello Voleye,
 
Thank you for your message and for having considered our request.

Actually, until now I did not understand why there was such restriction. What is the logic behind the fact that Grouped product may only contains products with not required option ?

Most of time, the custom options within a product are required, so finally this rule is quite restrictive. Hopefully, couple of extensions resolved the issue in Magento 1, so we thought that it would be great to have it natively resolved in Magento 2.

Below is an example of Grouped product associated with simple products (with custom options):

http://demo.itoris.com/main/index.php/magento-red-furniture-set.html

Thank you for your great support!

Sam

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
