### ISSUE TITLE
 Catchable fatal error: Argument 1 passed to Magento\Framework\App\Response\Http::__construct()

### ISSUE THREAD

**Issue by vishveskrish** [magento/magento2#1933]
![m2-bug](https://cloud.githubusercontent.com/assets/6836510/10045939/b1e881ae-6223-11e5-9955-96e5adebd59b.png)

**Comment by voleye** [comment]
Hi @vishveskrish, could you please provide more details how to reproduce this issue?

**Comment by piotrekkaminski** [comment]
@vishveskrish closing this ticket as we haven't received any response. Please reopene if you still have this issue.
