### ISSUE TITLE
Uncaught Error: You cannot apply bindings multiple times to the same element. when use  ko.applyBindings(viewModel,province);

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1934]
require([
        "jquery",
        "ko"
    ], function($,ko){

        var viewModel = {
            jdprovince: ko.observable(),
            jdprovinces: ko.observableArray()
        };
        viewModel.jdprovinceSelect = ko.dependentObservable({
            read: viewModel.jdprovince,
            write: function (jdprovince) {
                this.jdprovince(jdprovince);
       
            },
            owner: viewModel
        });

        $(function () {

            $.getJSON('<?php echo $block->getProvinceUrl()?>',
                null, function (response) {
                    viewModel.jdprovinces(response);
                });
            var province = document.getElementById('province');

            ko.applyBindings(viewModel,province);

        });

    });

**Comment by guz-anton** [comment]
Hi Albert,
Here is [jsfiddle](http://jsfiddle.net/oc4yz2sp/7/) example with your code. You can see it works. So on isolate environment code works as expected.

Probably you are trying execute it on some Magento page. And if it contains some [`uiComponent`](http://devdocs.magento.com/guides/v2.0/ui-library/ui-library-component.html) form then it already has binded context (that Knockout kindly says). But inside `uiComponents` Knockout isn't used directly.

So could you point on what page your issue occurs? What environment for code? How you add his js on the page?

**Comment by LifeAsBook** [comment]
thank you, i fixed
http://codelea.com/X6zbDq3nDjOn/knockoutjs-single-page-application-with-pagerjs-you-cannot-apply-bindings-multiple-times-to-the-same-element.html

**Comment by 4DallasC** [comment]
I've got this error after upgrading to Magento 2.1.0 from 2.0.7. There seems to be something left in the session that causing the problem. I launched a private window and logged in again - it went away.

**Comment by rou9e** [comment]
I can confirm that the purge of the browser data (session, cookies, cache, etc), login again, solved the problem for me.

**Comment by sintsov** [comment]
@4DallasC Thanks, it helped me
