### ISSUE TITLE
JQMIGRATE: $(html) HTML strings must start with '<' character

### ISSUE THREAD

**Issue by danielc1234** [magento/magento2#1936]
Hey, I'm not a developer, but wanted to throw this out there in case one of the Magento devs thinks this is an issue.

In Windows Chrome, while on a product page, if on the page for an extended amount of time, when refreshing the page, it will just 'spin' and 'spin'. It does not throw an error on the page, but will just not completely load.

I took a screen shot of the console so you can see what is it saying.

![image](https://cloud.githubusercontent.com/assets/1151357/10047740/94879988-61dd-11e5-8cdd-875c66e26427.png)

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-44051

@danielc1234 do you know approximately how much time you had to wait for it to happen? Did you experience lost session (ie lost cart contents or were logged out)?

**Comment by danielc1234** [comment]
Seemed to happen immediately. That was a while back, so can't remember exactly. I am waiting for some more development before updating and working with 2.0

**Comment by guz-anton** [comment]
Hi @danielc1234,
Issue not reproducible any more: we eliminate use of `lib/web/gallery.js` mentioned in issue.

Fill free to reopen issue in case it is still reproducible on fresh mainline.
