### ISSUE TITLE
Bug: PayPal «Payer Status» and «Merchant Protection Eligibility» payment values on admin order page are untranslatable (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1937]
![magento2-11](https://cloud.githubusercontent.com/assets/83204/10050764/a00c76b8-6226-11e5-982d-eccb7b8d90e4.png)

My fix: https://mage2.pro/t/80
I makes all the PayPal payment properties translatable:
![magento2-10](https://cloud.githubusercontent.com/assets/83204/10050791/b883eea6-6226-11e5-8109-4020743a37c4.png)

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-43612

**Comment by sshrewz** [comment]
Issue has been resolved.  Feel free to reopen if you still encounter any issues.
