### ISSUE TITLE
Slow Function Execution / High Memory Usage / Slow Request Execution

### ISSUE THREAD

**Issue by comunidademagento** [magento/magento2#1938]
Hello,

This environment: Vagrant + Zend Server + Magento2

See images ...

The apache is work and run normally phpinfo.php in http://magento2.dev/phpinfo.php

In the browser does not finish loading content in folder http://magento2.dev/magento2beta02/

Any tips?

Thanks!!!

![01](https://cloud.githubusercontent.com/assets/7476455/10052410/236eb964-61fd-11e5-9534-fc68d27d623c.png)
![02](https://cloud.githubusercontent.com/assets/7476455/10052409/236e1e14-61fd-11e5-8ab6-6f013473862f.png)
![03](https://cloud.githubusercontent.com/assets/7476455/10052408/236d9eee-61fd-11e5-99d0-7d0cdcc7ee37.png)

**Comment by melnikovi** [comment]
@comunidademagento what is your host machine operating system and what virtual machine do you use? Also, do you have shared folder between host and guest machine? If yes, what sharing method do you use? Maybe you can show your Vagrantfile here.

**Comment by comunidademagento** [comment]
what is your host machine operating system and what virtual machine do you use?
:: Linux Ubuntu

Also, do you have shared folder between host and guest machine? If yes, what sharing method do you use?
:: Yes

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "zend.magento2.dev"
  config.vm.network :private_network, ip: "192.168.50.107"
  config.vm.synced_folder ".", "/var/www", type: "nfs"

config.vm.provider :virtualbox do |vb|
  vb.customize ["modifyvm", :id, "--memory", "2048"]
  vb.customize ["modifyvm", :id, "--ioapic", "on"]
  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
 end
end

**Comment by melnikovi** [comment]
I see that you use NFS, so it shouldn't be shared folder performance. You run Vagrant + VirtualBox on Mac, correct? Did you try with our Zend Server?

**Comment by comunidademagento** [comment]
You run Vagrant + VirtualBox on Mac, correct?
:: No.
:: Vagrant + VirtualBox on Linux Ubuntu 15.04

Have you tried with out Zend Server?
:: You say without Vagrant?

See images ...

I exclude NFS in vagrantfile

I try insert permission on directory /var, but not work.

![captura de tela de 2015-09-23 15 29 05](https://cloud.githubusercontent.com/assets/7476455/10054760/2bf44728-6209-11e5-8375-1e3412f4a397.png)
![captura de tela de 2015-09-23 15 31 18](https://cloud.githubusercontent.com/assets/7476455/10054761/2bf4aee8-6209-11e5-95aa-c412c28ecf30.png)
![captura de tela de 2015-09-23 15 31 24](https://cloud.githubusercontent.com/assets/7476455/10054759/2bf0f7b2-6209-11e5-900b-e22cea2830d8.png)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
