### ISSUE TITLE
Javascript error when selecting the country as Brazil at checkout

### ISSUE THREAD

**Issue by cerebrumgit** [magento/magento2#1939]
======
en_US
======

Javascript error when selecting the country as Brazil at checkout

As we see images that appears javascript error when selecting the country as Brazil at checkout and the states are not born in the state field, I see that appears only Acre state together with the states of the United States of America

======
pt_BR
======

Erro de javascript ao selecionar o País como Brasil no checkout

Conforme imagens vemos que é exibido erro de javascript ao selecionar o País como Brasil no checkout e os estados não é carregado no campo estado, vejo que é exibido somente o estado Acre em conjunto com os estados dos Estados Unidos da America

---

![captura de tela de 2015-09-23 16 03 04](https://cloud.githubusercontent.com/assets/3661079/10055571/616119b4-620d-11e5-9df5-476a5edc12ec.png)
![captura de tela de 2015-09-23 16 03 46](https://cloud.githubusercontent.com/assets/3661079/10055572/6166ed4e-620d-11e5-9f21-9e8bb69f8542.png)
![captura de tela de 2015-09-23 16 03 57](https://cloud.githubusercontent.com/assets/3661079/10055573/61aa5a70-620d-11e5-8de6-12d8fa930471.png)

**Comment by okorshenko** [comment]
@cerebrumgit thank you for reporting. Internal ticket MAGETWO-42440 is created to track this issue.

**Comment by piotrekkaminski** [comment]
It should be fixed now.
