### ISSUE TITLE
Inconsistency: unable to open an order by a click in the admin order grid while we can do so in the admin product grid

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1940]
![magento2-12](https://cloud.githubusercontent.com/assets/83204/10058443/23099380-624e-11e5-829d-940669d802d9.png)

![magento2-13](https://cloud.githubusercontent.com/assets/83204/10058446/2788f112-624e-11e5-828b-7e545dec8bcf.png)

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-43915

**Comment by vil11** [comment]
This issue isn't reproduced in the latest versions.

## 

:sunny: dvilchynskyi, M2 QA

**Comment by MomotenkoNatalia** [comment]
@mage2pro Please let us know if you still have an issue.
