### ISSUE TITLE
Order Item «Returned» status (STATUS_RETURNED) is defined but never used

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1944]
Global code search shows that the order item status «Returned» is never used in the core.

PHP constant  \Magento\Sales\Model\Order\Item::STATUS_RETURNED is defined here: https://github.com/magento/magento2/blob/c077da60335dfeb72d9678d519e38d4191170dd9/app/code/Magento/Sales/Model/Order/Item.php#L52

Screen Label "Returned" is defined here:
https://github.com/magento/magento2/blob/c077da60335dfeb72d9678d519e38d4191170dd9/app/code/Magento/Sales/Model/Order/Item.php#L425

**Comment by asemenenko** [comment]
Hi @dfediuk 

It should be used in the RMA module that is a part of EE bundle.

/regards

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
