### ISSUE TITLE
How to override mini-cart default item template? (is loaded via JS)

### ISSUE THREAD

**Issue by debuysserk** [magento/magento2#1946]
Hi guys,

We're in the process of building our own theme based on the Magento Blank theme and we would like to implement 2 small changes to the minicart dropdown in the header. These files are loaded through JS I think, but simply duplicating the file to our own theme in the same folder (Name/name2/web/template/minicart/item/default.html) and editing them doesn't show up any changes so we suspect the override behaviour is different in this case.

Can you point us in the right direction? Thanks!

**Comment by AndyArcherKG** [comment]
Hello, have you tried 'template' with an 's' at the end e.g.
Name/name2/web/templates/minicart/item/default.html

**Comment by debuysserk** [comment]
@AndyArcherKG regular overrides/extends are templateS yes. But the ones in web/template are not.

See screenshot from app/code/Magento/Checkout

![template_dir](https://cloud.githubusercontent.com/assets/14332813/10074764/24be97fa-62d2-11e5-89ce-cf5831f6c1c9.png)

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
