### ISSUE TITLE
A method by name offsetUnset already exists in this class.

### ISSUE THREAD

**Issue by comunidademagento** [magento/magento2#1947]
![captura de tela de 2015-09-24 17 06 07](https://cloud.githubusercontent.com/assets/7476455/10085275/a7744cb0-62de-11e5-9a16-0a3f993cedbd.png)

![captura de tela de 2015-09-24 17 47 22](https://cloud.githubusercontent.com/assets/7476455/10086677/197e86e8-62e6-11e5-8be1-aca8aee44c88.png)

A method by name offsetUnset already exists in this class.
#0 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Store\\M...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Store\\M...')
#2 [internal function]: spl_autoload_call('Magento\\Store\\M...')
#3 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Store\\M...')
#4 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Store\\M...')
#5 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Store\\M...')
#6 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\M...', Array)
#7 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Data/Collection/EntityFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Store\\M...', Array)
#8 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Data/Collection.php(610): Magento\Framework\Data\Collection\EntityFactory->create('Magento\\Store\\M...')
#9 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(569): Magento\Framework\Data\Collection->getNewEmptyItem()
#10 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(550): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#11 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/Model/Resource/Website/Collection.php(119): Magento\Framework\Data\Collection\AbstractDb->load(false, false)
#12 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/Data/Collection.php(333): Magento\Store\Model\Resource\Website\Collection->load()
#13 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/Model/WebsiteRepository.php(123): Magento\Framework\Data\Collection->getItems()
#14 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/Model/StoreResolver/Website.php(46): Magento\Store\Model\WebsiteRepository->getDefault()
#15 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/Model/StoreResolver.php(121): Magento\Store\Model\StoreResolver\Website->getAllowedStoreIds(NULL)
#16 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/Model/StoreResolver.php(107): Magento\Store\Model\StoreResolver->readStoresData()
#17 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/Model/StoreResolver.php(80): Magento\Store\Model\StoreResolver->getStoresData()
#18 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/Model/StoreManager.php(151): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#19 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/app/code/Magento/Store/App/Request/PathInfoProcessor.php(36): Magento\Store\Model\StoreManager->getStore('')
#20 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/var/generation/Magento/Store/App/Request/PathInfoProcessor/Proxy.php(95): Magento\Store\App\Request\PathInfoProcessor->process(Object(Magento\Framework\App\Request\Http), '/')
#21 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Request/Http.php(161): Magento\Store\App\Request\PathInfoProcessor\Proxy->process(Object(Magento\Framework\App\Request\Http), '/')
#22 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/HTTP/PhpEnvironment/Request.php(194): Magento\Framework\App\Request\Http->setPathInfo()
#23 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Request/Http.php(204): Magento\Framework\HTTP\PhpEnvironment\Request->getPathInfo()
#24 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Http.php(110): Magento\Framework\App\Request\Http->getFrontName()
#25 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#26 /home/marcelo/dados/public_html/magento2-1.0.0-beta-dev01/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#27 {main}

**Comment by piotrekkaminski** [comment]
@comunidademagento can you try now? Which branch did you try (development branch could be temporarily broken). Please reopen if you still have this issue and provide more information like PHP version

**Comment by pradipmanna2000** [comment]
Module 'Magento_Indexer':
Running recurring..
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'A method by name offsetUnset already exists in this class.' in /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Code/Generator.php:103
Stack trace:
#0 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\Store\M...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\Store\M...')
#2 [internal function]: spl_autoload_call('Magento\Store\M...')
#3 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\Store\M...')
#4 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\Store\M...')
#5 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\Store\M...')
#6 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Store\M...', Array)
#7 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Data/Collection/EntityFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Store\M...', Array)
#8 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Data/Collection.php(610): Magento\Framework\Data\Collection\EntityFactory->create('Magento\Store\M...')
#9 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Data/Collection/AbstractDb.php(569): Magento\Framework\Data\Collection->getNewEmptyItem()
#10 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Data/Collection/AbstractDb.php(550): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#11 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/ResourceModel/Website/Collection.php(119): Magento\Framework\Data\Collection\AbstractDb->load(false, false)
#12 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Data/Collection.php(333): Magento\Store\Model\ResourceModel\Website\Collection->load()
#13 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/WebsiteRepository.php(124): Magento\Framework\Data\Collection->getItems()
#14 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/StoreResolver/Website.php(46): Magento\Store\Model\WebsiteRepository->getDefault()
#15 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/StoreResolver.php(125): Magento\Store\Model\StoreResolver\Website->getAllowedStoreIds(NULL)
#16 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/StoreResolver.php(111): Magento\Store\Model\StoreResolver->readStoresData()
#17 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/StoreResolver.php(80): Magento\Store\Model\StoreResolver->getStoresData()
#18 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/StoreManager.php(151): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#19 /home/knockbrand/public_html/megasuperstores/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#20 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#21 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/App/Config/ScopePool.php(119): Magento\Store\Model\Resolver\Store->getScope(NULL)
#22 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/App/Config/ScopePool.php(74): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#23 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#24 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/App/Config.php(58): Magento\Framework\App\Config->getValue('catalog/fronten...', 'store', NULL)
#25 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-catalog/Model/Indexer/AbstractFlatState.php(57): Magento\Framework\App\Config->isSetFlag('catalog/fronten...', 'store')
#26 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-catalog/Model/Indexer/Category/Flat/Plugin/IndexerConfigData.php(42): Magento\Catalog\Model\Indexer\AbstractFlatState->isFlatEnabled()
#27 [internal function]: Magento\Catalog\Model\Indexer\Category\Flat\Plugin\IndexerConfigData->aroundGet(Object(Magento\Indexer\Model\Config\Data\Interceptor), Object(Closure), NULL, NULL)
#28 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#29 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Indexer...', 'get', Object(Magento\Indexer\Model\Config\Data\Interceptor), Array, 'indexerProductF...')
#30 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-catalog/Model/Indexer/Product/Flat/Plugin/IndexerConfigData.php(41): Magento\Indexer\Model\Config\Data\Interceptor->Magento\Framework\Interception{closure}(NULL, NULL)
#31 [internal function]: Magento\Catalog\Model\Indexer\Product\Flat\Plugin\IndexerConfigData->aroundGet(Object(Magento\Indexer\Model\Config\Data\Interceptor), Object(Closure), NULL, NULL)
#32 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#33 /home/knockbrand/public_html/megasuperstores/var/generation/Magento/Indexer/Model/Config/Data/Interceptor.php(39): Magento\Indexer\Model\Config\Data\Interceptor->___callPlugins('get', Array, Array)
#34 /home/knockbrand/public_html/megasuperstores/var/generation/Magento/Indexer/Model/Config/Data/Proxy.php(103): Magento\Indexer\Model\Config\Data\Interceptor->get(NULL, NULL)
#35 [internal function]: Magento\Indexer\Model\Config\Data\Proxy->get(NULL, NULL)
#36 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#37 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Indexer\Model\Config\Data\Proxy\Interceptor->___callParent('get', Array)
#38 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Indexer...', 'get', Object(Magento\Indexer\Model\Config\Data\Proxy\Interceptor), Array, 'indexerProductF...')
#39 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-catalog/Model/Indexer/Product/Flat/Plugin/IndexerConfigData.php(41): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(NULL, NULL)
#40 [internal function]: Magento\Catalog\Model\Indexer\Product\Flat\Plugin\IndexerConfigData->aroundGet(Object(Magento\Indexer\Model\Config\Data\Proxy\Interceptor), Object(Closure), NULL, NULL)
#41 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#42 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Indexer...', 'get', Object(Magento\Indexer\Model\Config\Data\Proxy\Interceptor), Array, 'indexerCategory...')
#43 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-catalog/Model/Indexer/Category/Flat/Plugin/IndexerConfigData.php(40): Magento\Indexer\Model\Config\Data\Proxy\Interceptor->Magento\Framework\Interception{closure}(NULL, NULL)
#44 [internal function]: Magento\Catalog\Model\Indexer\Category\Flat\Plugin\IndexerConfigData->aroundGet(Object(Magento\Indexer\Model\Config\Data\Proxy\Interceptor), Object(Closure))
#45 /home/knockbrand/public_html/megasuperstores/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#46 /home/knockbrand/public_html/megasuperstores/var/generation/Magento/Indexer/Model/Config/Data/Proxy/Interceptor.php(39): Magento\Indexer\Model\Config\Data\Proxy\Interceptor->___callPlugins('get', Array, Array)
#47 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-indexer/Model/Config.php(32): Magento\Indexer\Model\Config\Data\Proxy\Interceptor->get()
#48 /home/knockbrand/public_html/megasuperstores/vendor/magento/module-indexer/Setup/Recurring.php(90): Magento\Indexer\Model\Config->getIndexers()
#49 /home/knockbrand/public_html/megasuperstores/setup/src/Magento/Setup/Model/Installer.php(821): Magento\Indexer\Setup\Recurring->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#50 /home/knockbrand/public_html/megasuperstores/setup/src/Magento/Setup/Model/Installer.php(732): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#51 [internal function]: Magento\Setup\Model\Installer->installSchema()
#52 /home/knockbrand/public_html/megasuperstores/setup/src/Magento/Setup/Model/Installer.php(331): call_user_func_array(Array, Array)
#53 /home/knockbrand/public_html/megasuperstores/setup/src/Magento/Setup/Controller/Install.php(97): Magento\Setup\Model\Installer->install(Array)
#54 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#55 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#56 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#57 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#58 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#59 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#60 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#61 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#62 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#63 /home/knockbrand/public_html/megasuperstores/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#64 /home/knockbrand/public_html/megasuperstores/setup/index.php(31): Zend\Mvc\Application->run()
#65 {main}
***_i unable to install magento 2, Pls help
***_http://megasuperstores.knockingdoorbrand.com/index1.php for phpinfo
