### ISSUE TITLE
I've added the custom attribute to customer_address_entity and display in UI form.how to save the custom attribute to database when submit form 

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1949]
![33](https://cloud.githubusercontent.com/assets/10986726/10102378/a75cc674-63d0-11e5-8f29-969a433d6846.png)

**Comment by dfediuk** [comment]
I think you use the wrong place for such question, because it is an issue tracker, not a forum
StackExchange [magento 2](http://magento.stackexchange.com/questions/tagged/magento2) section would be better for Magento 2 "How to..." questions.

**Comment by LifeAsBook** [comment]
oh i'm sorry,thak you for your reminder.

**Comment by dfediuk** [comment]
Surely Magento 2 core developers read StackExchange Magento 2 section and answer the questions. :)
For example, [KAndy](http://magento.stackexchange.com/users/12503/kandy) do it frequently.
But other StackExchange members (not Magento 2 core developers) do it even faster.

**Comment by LifeAsBook** [comment]
@dfediuk thank you
