### ISSUE TITLE
URL Issue

### ISSUE THREAD

**Issue by restaurantsupply** [magento/magento2#1950]
Please go to icemaker.com and mouse over the Top Navigation. 

Click on Brand link. You will notice the URL is: 

http://www.icemaker.com/catalog/category/view/s/brands/id/3/

The correct URL should be: 

http://www.icemaker.com/brands

Second

Mouse over Ice Machines in the top bar and all the categories in the level under Ice Machines had the weird URL. When you go to the next level down (Ice Machines(bad URL) > Undercounter Ice Machines(bad URL) > Commercial Undercounter Ice Machines (GOOD URL) the lowest lever URL is ok. 

Does anyone have any recommendation on how to fix this issue??

**Comment by danielc1234** [comment]
I'm using Chrome and I do not see what you are talking about. It shows for me the correct URLs

**Comment by danielc1234** [comment]
Did you set rewrite to be ON?

**Comment by restaurantsupply** [comment]
If you go to the top navigation bar you will notice when you click ice
machines the URL is not correct

On Fri, Sep 25, 2015 at 11:16 AM, danielc1234 <notifications@github.com>
wrote:

> Did you set rewrite to be ON?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magento/magento2/issues/1950#issuecomment-143249636>.
>



-- 

Michael Sullo

312 Murphy Road
Hartford, CT 06114
Toll Free* 1.855.838.1010 x116*
Direct *(860) 246.1111*

*michael@restaurantsupply.com <michael@restaurantsupply.com>*

**Comment by DavidBruchmann** [comment]
In chrome all links are different including sub-menus and sub-sub-menus.
Don't see a reason to mention about chrome but doesn't matter too ;-)
Just clear your caches perhaps.

**Comment by Vinai** [comment]
The site is password protected, and I'm not able to reproduce the issue on the current develop branch.
Please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) if you require further assistance. If you have introduced custom code for the rendering of the menu please add that in the post there.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
