### ISSUE TITLE
Enabling "Merge Javascript Files" and "JS Bundling" increases size of page by 2-3 times.

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#19518]
### Preconditions (*)
1. Magento 2.2-develop or Magento 2.3-develop

### Steps to reproduce (*)
1. deploy vanilla instance
2. change to production mode
3. Use Web page analysis tool to give you size of web page
4. Enable Minify Javascript Files - php -f bin/magento config:set dev/js/minify_files 1
5. Use Web page analysis tool to give you size of web page
6. Enable JS Bundling - php -f bin/magento config:set dev/js/enable_js_bundling 1
7. Enable Merge JS - php -f bin/magento config:set dev/js/merge_files 1
8. Use Web page analysis tool to give you size of web page

### Expected result (*)
1. After enabling minification, expect webpage size to decrease and number of requests to remain static
2. After enabling bundling and merging, expect webpage size to stay approximately the same and number of requests to decrease.

### Actual result (*)
2.2-devel
Vanilla production mode - 0.99MB 185 Requests
With minification - 0.78MB - 185 Requests
With bundling and Merging - 1.4MB - 31 Requests

2.3-devel
Vanilla production mode - 1.06MB 192 Requests
With minification - 0.84MB 193 Requests
With bundling and Merging - 2.36MB 30 Requests

So why does bundling and merging increase the size of the webpage by between 2 and 3 times. Am i misunderstanding what bundling does here. I thought it was just a process of combining?

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment]
Oh, hang on. Is it because bundling, bundles up all js files regardless of whether they are used or not, whereas a webpage load, will only request whats required?

**Comment by orlangur** [comment]
@gwharton yeah. As far as I remember it collects all JS files added to `<head>` via layout.

Are you opening a home page or which one bu the way?

**Comment by orlangur** [comment]
@gwharton also, please check https://devdocs.magento.com/guides/v2.2/performance-best-practices/configuration.html#bundling-tips. It is not recommended to use merging.

**Comment by gwharton** [comment]
Yeah, I've turned off bundling for now.

On my production store, with many addons/modules, without bundling a load of the home page has 220 requests at about 1.5MB in size or 38 requests at 6MB in size with bundling.

I do support HTTP/2.0 so 220 requests isn't worrying me too much, but does feel a little excessive for a single webpage. I can't stomach 6MB per page as alot of my visitors are mobile.

I see there is some advanced bundling techniques in the 2.3 docs, but it seems way too complicated for me. Lets hope someone gets a grip and manages to integrate better bundling into M2 in the future.

There must be a core set of js scripts that are used everywhere, which could be bundled, leaving everything else not bundled, but even sorting this out seems a task and a half.

**Comment by orlangur** [comment]
@gwharton,

> There must be a core set of js scripts that are used everywhere, which could be bundled, leaving everything else not bundled, but even sorting this out seems a task and a half.

It was announced during MageConf month ago that JS team is currently working on determining such set and splitting everything else into few bundles (like "catalog", "checkout" and so on).

So, for now I would recommend using whatever out-of-the-box option works better for your site and do not invest efforts into investigation which duplicates core team work.

Assume this issue can be closed?

**Comment by gwharton** [comment]
Thats great news that this is being considered and worked on elsewhere. I will eagerly await any updates.

**Comment by cscd98** [comment]
Any updates on this?

**Comment by djixas** [comment]
Any updates on this?

**Comment by cscd98** [comment]
@orlangur Any updates on js bundling improvements?

**Comment by orlangur** [comment]
@craigcarnell not any I'm aware of. Please come to Slack `#app-design` or some frontend-related channel.
