### ISSUE TITLE
Bug: i18n phrases with apostrophes (') in Knockout templates are untranslatable (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1951]
The bug description and my fix: https://mage2.pro/t/86
The bug is similar to https://github.com/magento/magento2/issues/1905, but not the same.

**Comment by piotrekkaminski** [comment]
internal Issue ID MAGETWO-44053

**Comment by MomotenkoNatalia** [comment]
Internal ticket  MAGETWO-44053 is closed and delivered to mainline. Please, let us know if you still have an issue.
