### ISSUE TITLE
Bug: the phrase «start typing to search attribute» on admin product page is untranslatable (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1952]
![2015-09-26_3-45-12](https://cloud.githubusercontent.com/assets/83204/10114887/f76273b8-6401-11e5-96d3-462264c2c5ac.png)

A detailed description and my fix: https://mage2.pro/t/87

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44054

**Comment by vkholoshenko** [comment]
Issue has been fixed 0d85b24fd0f0d9da4a729cdaf236325cd6855fef. Thanks for reporting!
