### ISSUE TITLE
Bug: the phrase «start typing to search template» on admin product page is untranslatable (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1953]
![2015-09-26_4-04-07](https://cloud.githubusercontent.com/assets/83204/10115026/7d2c1042-6404-11e5-9ac1-3515f4543895.png)

The bug is very similar to https://github.com/magento/magento2/issues/1952
My fix: https://mage2.pro/t/topic/88

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44054

**Comment by vkholoshenko** [comment]
The team has processed this ticket 0d85b24fd0f0d9da4a729cdaf236325cd6855fef. Thanks for reporting!
