### ISSUE TITLE
Inconsistency: the admin product grid uses the old Magento 1.x term «Attribute Set» while other admin parts use the new Magento 2 term «Product Template» for the same thing 

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1956]
![magento2-04](https://cloud.githubusercontent.com/assets/83204/10117486/32a1c866-6461-11e5-9121-6c191f35baf8.png)

![magento2-05](https://cloud.githubusercontent.com/assets/83204/10117487/368daaf8-6461-11e5-83ce-bd3a28aaa9bf.png)

**Comment by voleye** [comment]
Hi @dfediuk, thank you for the comment! 

We have already started the discussion of this issue. We will get back to you once we agreed on it.

**Comment by NadiyaS** [comment]
@dfediuk ,
fix was delivered to mainline. Please see [ff0c608](https://github.com/magento/magento2/commit/ff0c6088f17cb8127f59eef9a87d41e1ff148981)

**Comment by dfediuk** [comment]
Fixed.
