### ISSUE TITLE
Unable to create blank page without head.

### ISSUE THREAD

**Issue by SasiKiranK** [magento/magento2#1958]
So far i have created the new layout called new layout inside my page_layout folder and 

copied the content of empty layout.
and the head content coming from the root.phtml. which i am unable to overwrite.

In mangento 1, i have done same using the new layout file.phtml i have removed <?php echo 

$this->getChildHtml('head') ?>
This allows me to remove the head section. 

Since magento can able to create any web app. i need to create a bank page using new 
layout.

**Comment by vkorotun** [comment]
Him you can override native root template via di.xml configuration file.

Please, check in `app/etc/di.xml`:

```xml
<type name="Magento\Framework\View\Result\Page">
        <arguments>
            <argument name="layoutReaderPool" xsi:type="object">pageConfigRenderPool</argument>
            <argument name="generatorPool" xsi:type="object">pageLayoutGeneratorPool</argument>
            <argument name="template" xsi:type="string">Magento_Theme::root.phtml</argument>
        </arguments>
    </type>
```

But, you can specify different root templates only per each area (frontend, adminhtml) which is not the good case if you need some pages with head and other without head section.

We'll open internal ticket to add possibility to configure root template on `page layout` level. Is it sounds like a good plan to solve the issue you have?

**Comment by SasiKiranK** [comment]
Exactly vkorotun. I need that feature in my extension. so that i can start developing my extension.

Thank you

**Comment by SasiKiranK** [comment]
Hi Team

Kindly share if any update in this ticket.
added @vkorotun

Thanks

**Comment by victorgugo** [comment]
Hello, @SasiKiranK .
Thank you for reporting the issue. We created interal MAGETWO-44095 to resolve the problem

**Comment by SasiKiranK** [comment]
Thank you. Where can i see the ticket info/status. also please provide me the estimated date so i can plan accordingly. 
Thanks again

**Comment by SasiKiranK** [comment]
Please release the new version with this fix.

Thank you
Sasikiran K

**Comment by SasiKiranK** [comment]
Hi @victorgugo 

Kindly update the improvement. Magento 2 released without fixing this issue. i am unable to create  the blank page to proceed with my extension. 
Please let me know is there any other way to do the same.

Regards
Sasikiran K

**Comment by SasiKiranK** [comment]
Hi Team

Any Updates on this issue

Regards
Sasikiran K

**Comment by SasiKiranK** [comment]
Hi Team 
Kindly update the Improvement or any updates

Thanks 
Sasikiran K

**Comment by SasiKiranK** [comment]
Hi Team

Please provide any other way to create the empty page or without head.

Thanks

**Comment by SasiKiranK** [comment]
Hi @vkorotun 

Many versions were released. Please resolve the issue.

Thanks
Sasikiran Kesavan

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unable-to-create-blank-page-without-head/idi-p/46917).

**Comment by almuete** [comment]
Any good news on this feature?
