### ISSUE TITLE
The phrase «add above» is oddly word-wrapped in an admin price tier row

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1959]
![magento2-06](https://cloud.githubusercontent.com/assets/83204/10121046/96c499b4-64e2-11e5-9cc1-170475d39f3c.png)

Tested with the latest Chrome / Firefox.

**Comment by zanilee** [comment]
Hello, @dfediuk!

Thank you for reporting this issue. It is reproduced.
Internal ticket MAGETWO-43298

**Comment by zanilee** [comment]
@dfediuk thank you for reporting the issue. Internal ticket: MAGETWO-43298 has been closed and merged to develop branch. Please, let us know if you still have an issue.

**Comment by vzabaznov** [comment]
Hi @dfediuk, issue was fixed, please check it, and if you think that not, feel free to write here or to open new one
