### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#19604]
PHP 7.3 has now been released. Would like to see Magento 2 support it

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php

Does something not work in 7.3?
Also this would rake some time.

**Comment by orlangur** [comment]
Thanks @craigcarnell, Magento team keeps an eye on new PHP releases by itself, there is no need in such reports.

**Comment by cscd98** [comment]
@orlangur Any updates on this? Are we expecting allow installation in 2.3.1?

**Comment by orlangur** [comment]
@craigcarnell dunno. All I know is that @buskamuza confirmed 7.3 support is in the backlog.

**Comment by buskamuza** [comment]
Not in 2.3.1. But should be in one of 2.3.x.
cc @piotrekkaminski

**Comment by djixas** [comment]
Any updates on this? I can't believe how slow you are

**Comment by DanielRuf** [comment]
Hi @djixas, as you can see there was no update in this specific issue. 2.3.1 was released a few days ago.

**Comment by cscd98** [comment]
@DanielRuf Can we expect an ETA please?

**Comment by bassmo** [comment]
Any update on magento2 setup working with php 7.3...  ?

**Comment by emkookmer** [comment]
Hi @buskamuza & @orlangur,

I'm planning to upgrade the servers that i'm managing to PHP7.3, but a couple of customers are running Magento2.
Could you provide a global timeline as to when support for PHP 7.3 is planned to be implemented?

**Comment by lracicot** [comment]
Any updates on this? PHP 7.2 is only actively supported for the next 6 months and PHP 7.4 is already in alpha so there is plenty of material to work with already.

**Comment by chernenm-zz** [comment]
Hello everyone!

We are currently working on this. We plan to release PHP 7.3 support in 2.3.3.

**Comment by cscd98** [comment]
@chernenm Really surpised this was not included in 2.3.2???

**Comment by DanielRuf** [comment]
@craigcarnell releases are cut and planned much earlier as changelogs and more gave to be created and so on.

If you need it earlier you can use the .patch/diff version of the PR then and apply it with composer-patches.

**Comment by cscd98** [comment]
@DanielRuf Do you have a PR or diff to use? It must be quite big to update composer.json of most modules?

**Comment by DanielRuf** [comment]
@chernenm cam probably answer this.

**Comment by DanielRuf** [comment]
@chernenm can probably answer this.

**Comment by kuldeepkaushik** [comment]
When i am trying to run composer install command in command prompt . it's end with with a error 

amzn/amazon-pay-and-login-with-amazon-core-module 3.2.9 requires php 7.1.3- 7.2.0 your php version 7.3.2 doesn't satisfy that requirment.

I installed xampp with php 7.3 . do you think i should switch to php 7.2 for magento 2.3 ?

Best Regards
Kuldeep

**Comment by DanielRuf** [comment]
> I installed xampp with php 7.3 . do you think i should switch to php 7.2 for magento 2.3 ?

Yes, please switch to PHP 7.2

2.3.3 may support 7.3, see https://github.com/magento/magento2/issues/24062#issuecomment-519463117

**Comment by ipoddine** [comment]
> Hello everyone!
> chernenm commented on **Jun 24**
> We are currently working on this. We plan to release PHP 7.3 support in 2.3.3.

It seems release 2.3.11 is still not compatible with PHP7.3... 

> 31 Oct 2019  PHP 7.4.0RC5 released!
and 7.2 active support until Nov 30th

Shall we hope for the support for version 7.3 anytime soon?

Thanks in advance

**Comment by Nikkumawat** [comment]
on putty command use after show error magento supports PHP 7.1.3 or later. Please read https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html 

please help me

**Comment by orlangur** [comment]
@Nikkumawat please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions

**Comment by AndyJAllen** [comment]
FYI I tried PHP 7.3.16 with Magento 2.3.3 and I couldn't even run bin/magento commands.

**Comment by Natskumawat** [comment]
After command error :
Fatal error: Uncaught Error: Class 'DOMDocument' not found in
/home/bigshopnz/public_html/vendor/magento/framework/Config/Dom.php:388
Stack trace:

my php version : 7.2
magento version : 2.3.2

**Comment by DanielRuf** [comment]
@Natskumawat I guess you wanted to comment on a different issue.

https://www.php.net/manual/en/class.domdocument.php

Check `phpinfo()` if your PHP version has the DOM extension installed and enabled.

https://www.php.net/manual/en/dom.installation.php

Also this is an old version of Magento 2.

**Comment by Natskumawat** [comment]
project already on server Linux base
pls send  command line DOM extension installed and enabled.

**Comment by DanielRuf** [comment]
Write a php file with `<?php phpinfo();`.

> @Natskumawat please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions

Closing this issue here as resolved. Please ask further questions on [Magento Stack Exchange](https://magento.stackexchange.com)
