### ISSUE TITLE
The phrase «Gift Messages is not applicable for virtual products» looks like grammatically incorrect

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1960]
- https://github.com/magento/magento2/blob/daf301d625d8652996a6d3c9400e5f9816184bde/app/code/Magento/GiftMessage/Model/CartRepository.php#L108
- https://github.com/magento/magento2/blob/daf301d625d8652996a6d3c9400e5f9816184bde/app/code/Magento/GiftMessage/Model/ItemRepository.php#L122
- https://github.com/magento/magento2/blob/daf301d625d8652996a6d3c9400e5f9816184bde/app/code/Magento/GiftMessage/Model/OrderItemRepository.php#L113
- https://github.com/magento/magento2/blob/daf301d625d8652996a6d3c9400e5f9816184bde/app/code/Magento/GiftMessage/Model/OrderRepository.php#L114

**Comment by ishakhsuvarov** [comment]
@dfediuk Closing the issue, as the fix for this issue had been delivered to the `develop` branch. Thank you for contribution.
