### ISSUE TITLE
Unable to use second website's Base Currency while creating a product

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#1961]
I have a multisite system: 2 websites with **different** base currencies:

![magento2-10](https://cloud.githubusercontent.com/assets/83204/10123124/788418de-6538-11e5-96cd-a61b30f02fe4.png)

![magento2-08](https://cloud.githubusercontent.com/assets/83204/10123126/7f8c82e2-6538-11e5-9b0a-4f55fc71b8ed.png)

But Magento 2 does not allow me to use second website's Base Curency while creating a product:

![magento2-07](https://cloud.githubusercontent.com/assets/83204/10123123/6b6475ae-6538-11e5-9513-41a2f90d70ae.png)

**Comment by dfediuk** [comment]
1. А roundabout solution is: 
- set a fake price in the first store's base currency
- assign product to the second store
- save the product
- open the product
- set the product price in the second store's base currency
- save the pproduct

As you can see, it too labour-intensive.

**Comment by johnny-longneck** [comment]
I can confirm this issue. 
We have two base currencies (€ and $) on two websites. 
In the US store it ignores the $ base currency.

When being charged for online transactions, it will use € which is by all means a total different price. 
Workaround is not an option with a high volume of products. 

This is a no go. Please...anyone, help?

**Comment by RomanKrut** [comment]
@dmitry-fedyuk Hi. Thanks for reporting this issue. When you start to create a product, the currency symbol is $ because in default config you have selected Base Currency = $, but if you have two websites with different currencies(For example web1 = $ and web2 = € ) and you create a product with price 10 for two websites it means you create a product with price 10$ for web1 and 10€  for web2. It works correctly. 
If you want to have currency ( for example € ) when creating new product, you should change Default config in Stores-Configuration-General- Currency setup and Base currency set to €.

**Comment by korostii** [comment]
> you create a product with price 10 for two websites it means you create a product with price 10$ for web1 and 10€ for web2

Which would make perfect sense in a universe where 1$ = 1€ all the time. 
Unfortunately, in our universe that's rarely true: https://www.bloomberg.com/quote/EURUSD:CUR

**Comment by antboiko** [comment]
@dmitry-fedyuk This is a correct behavior described by @krutkoroma79911 . Scope selector is not present on product creation page, and all values are being set on "All store views" (i.e. Default scope) level during product creation. Scope selector is available right after the product is saved, so user can set prices per website if Catalog Price Scope was set to "Website".

@korostii there is no auto conversion for the price. The values on websites (in this case "10") are inherited from "All Store Views" scope where it's set "10" during product creation. The user is able to change the scope to specific store view and uncheck the checkbox "Use Default Value" next to price input field and set the desired price according to the currency of the website.
