### ISSUE TITLE
Cannot use custom attribute as placeholder

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1963]
Placeholders are great, but I've a question, is possibile to use a custom attribute (like color), into the varius mask (Es. Meta Title, Keywords, ecc...)?

I've tried to use (for meta title): {{name}} {{color}}, and the only replaced placeholder was the name.

thank you

**Comment by okorshenko** [comment]
@CRYX2 , could you please add more details for this issue?

**Comment by CRYX2** [comment]
Sure, i've edited the Mask for meta title:

![senza-titolo-2](https://cloud.githubusercontent.com/assets/5001801/10146497/7ca24908-6629-11e5-8d5b-ead4361daf9c.jpg)

After, I've create a new product with a Color attribute:

![senza-titolo-3](https://cloud.githubusercontent.com/assets/5001801/10146507/89af7f76-6629-11e5-8255-607d8399c2fd.jpg)

And after save, i've checked the frontend, and my Meta title was:

![senza-titolo-4](https://cloud.githubusercontent.com/assets/5001801/10146515/95f07272-6629-11e5-8554-834a7ab332ec.jpg)

Obviously I would have expected that {{color}} was replaced with the selected color

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
