### ISSUE TITLE
Block sorting does not work from layout

### ISSUE THREAD

**Issue by kirillkorovkin** [magento/magento2#1966]
**Steps:**
1 Create module with company name as Foobar.
2 Create *view/frontend/layout/customeraccount.xml* file with the following content
```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="customer_account_navigation">
            <block class="Magento\Framework\View\Element\Html\Link\Current" name="customer-account-navigation-foobar-link" after="-">
                <arguments>
                    <argument name="path" xsi:type="string">foobar/customer</argument>
                    <argument name="label" xsi:type="string">Foobar link</argument>
                </arguments>
            </block>
        </referenceBlock>
    </body>
</page>
```
3 Go to customer account and see in navigation menu
**Actual result**
"Foobar link" is the first in the navigation menu
**Expected result**
"Foobar link" is the last in the navigation menu
**Additional info**
Company name must be less than "Magento" in string compare.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-43914

**Comment by okorshenko** [comment]
@kirillkorovkin, thank you for reporting the issue. Internal ticket: MAGETWO-43914 has been closed and merged to develop branch. Please, let us know if you still have an issue
