### ISSUE TITLE
Documentation Problem / Clearing LESS cache

### ISSUE THREAD

**Issue by amenk** [magento/magento2#1967]
I am trying to edit a custom theme following the steps in
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_mode.html
Section "Making simple style changes in server-side compilation mode"

`MAGE_MODE` is "developer"

1. make a change in `app/design/frontend/Foo/default/web/css/source/_sources.less`
2. `rm pub/static/frontend/Foo/default/* -rf`
3. `rm var/view_preprocessed/less/* -rf`

Result: The page still shows the old CSS
Expected: CSS update

Workaround:

`rm -rf var/view_preprocessed/source/frontend/Foo/*`

But now I get an file-not-found error for example for `http://foo.localhost/pub/static/frontend/fooo/default/de_DE/css/styles-m.css`

When I flush alle caches, the CSS is regenerated.

Anyways, this seems to be an error in the documentation.
And is there a quicker way than clearing all caches to regenerate CSS? (not using grunt)

**Comment by chicgeek** [comment]
Advice to remove static and preprocessed folders is mentioned here:
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html

As for speed, I disabled some cache types including `View files pre-processing`, though this still requires two slow page refreshes: one to trigger the build start, the next to successfully show the files after they are built. Do you get the `styles-m.css` error after this second refresh?

**Comment by amenk** [comment]
> Advice to remove static and preprocessed folders is mentioned here:
> http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html

okay, but it should also be mentioned in http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_mode.html 

I actually will try `grunt` now ... might be a much better option

**Comment by dougkm** [comment]
@tkacheva - Can you take a look at this issue?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
