### ISSUE TITLE
Sample Data issue

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#1968]
Hello,

can you please tell us how to install sample data?

because i checked all command list  magento list there is no command for  magento sampledata:install <your Magento administrator user name>

=> also i am trying to add "magento/sample-data": "0.74.0-beta1", but it is not working.

**Comment by mazhalai** [comment]
@sunilit42 The `sampledata:install` will show up only if you already have the sample data module in your code base. Please follow the instructions [here](http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data.html) to install sample data.

**Comment by sunilit42** [comment]
@mazhalai added  "magento/sample-data": "~1.0.0" but after that i tried to run setup command but showing below error: Class Magento\Setup\Model\SampleData does not exist#

**Comment by voleye** [comment]
Hi @sunilit42 , could you please specify which Magento version do you use?

**Comment by mazhalai** [comment]
@sunilit42 did you run `composer update` after adding ` "magento/sample-data": "~1.0.0" `

**Comment by sunilit42** [comment]
@voleye latest version just uploaded it
@mazhalai yes i run 3 times. same thing happen.

**Comment by mazhalai** [comment]
@sunilit42 please clearing you `var` folder and try again

**Comment by johnbendi** [comment]
I'm having the same issue. Clearing the `/var` folder does not help.

**Comment by johnbendi** [comment]
what is the difference between `magento/sample-data` and `magento/module-sample-data` ?

**Comment by sunilit42** [comment]
Before some time they added into setup folder, now a days he provide as magento core module.

But we tried to add into composer and download it, it comes old version. does not include all the files with latest commit.

Check below one:
https://github.com/magento/magento2-sample-data

download it and manually install manually it will works.

**Comment by danielc1234** [comment]
I've been trying for hours to get the sample data into the develop version with no luck. Seems like it imports, but nothing shows on the front end. Very frustrating.

**Comment by mazhalai** [comment]
@danielc1234 did you try to install via composer or via git repository?

**Comment by danielc1234** [comment]
@mazhalai 
I tried both. I can see the cms blocks with images in admin, but looks like they lost their links in the category sections.
What is the best way to add sample data with the develop branch? Is there any docs that we should be following?

Thanks

**Comment by danielc1234** [comment]
but if I do it via setup wizard within magento, the sample data is grayed out.

**Comment by mazhalai** [comment]
If you want to use `develop` branch please install sample-data via the git repository. See the readme [here](https://github.com/magento/magento2-sample-data) 
Also, are there any errors in the browser's console?

**Comment by danielc1234** [comment]
@mazhalai I did use the git repository, which says it was updated, however in the wizard setup, the sample data cannot be checked off cause it is grayed out.

**Comment by mazhalai** [comment]
@danielc1234 can you check your `/app/etc/config.php` file. Does it have sample data? if not please run `bin/magento setup:upgrade`, check `config.php` again to confirm sample-data exists and then run the wizard

**Comment by mazhalai** [comment]
@danielc1234 @sunilit42 @johnbendi we have created ticket MAGETWO-42770 to investigate.

**Comment by johnbendi** [comment]
@danielc1234 use the git repo as follow the second instruction for installation on the readme. It will output something like:
```
All symlinks you can see at files:
/opt/magento2-sample-data/dev/tools/exclude.log
```
after the script is run. Then use the command line style of installation to proceed as normal.

**Comment by mazhalai** [comment]
Yes CLI with `--use-sample-data` flag works perfectly. The fix for web setup is in progress.

**Comment by piotrekkaminski** [comment]
Closing as no recent comments.
