### ISSUE TITLE
Prefered way to update to the latest version

### ISSUE THREAD

**Issue by sakiss** [magento/magento2#1969]
Hi

I am using the beta 0.74.0-beta16.
I cannot find the "System Upgrade" (described in the docs) functionality in my system.

So what is the preferred way to update to the latest version?

**Comment by mazhalai** [comment]
@sakiss it is available under `System > Web Setup Wizard` More details [here](http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html)

**Comment by sakiss** [comment]
As said this option does not exist in my version.
If i get the latest files from github and put them in my installation will work?

**Comment by mazhalai** [comment]
You can upgrade using CLI tools, details [here](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall.html#instgde-install-magento-update)

**Comment by sakiss** [comment]
Thanks for the feedback.
I followed that carefully but now i am getting some errors.
It report file asks me to run the setup:upgrade which i do.

At the end of the setup messages it gives me that:
*Please re-run Magento compile command*

Visiting the site gives me another message:
*exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory /var/www/html/magento2/var/generation/Magento/Framework/App/Resource/.' in /var/www/html/magento2/lib/internal/Magento/Framework/Code/Generator.php:106 Stack trace: #0 /var/www/html/magento2/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35)*

Any idea?

**Comment by mazhalai** [comment]
@sakiss please give your `var/generation`  folder write access.

**Comment by sakiss** [comment]
all the files and folders have rw (permissions)

**Comment by mazhalai** [comment]
Did you follow permissions based on [http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html]

**Comment by sakiss** [comment]
Thanks for the feedback.

It's a local installation where everybody has read-write-execute (777) permissions 

I think it's not a permissions issue as this was a working installation. 
I just upgraded it by fetching the latest files from github and then upgraded the db-schema (setup:upgrade)

**Comment by sakiss** [comment]
Don't know if this helps but when i change again permissions the initial messages disappear and i am getting:
*Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:.......*

When i run the *bin/magento setup:upgrade* at the end i am getting the message:
*Please re-run Magento compile command*

Visiting the site i am getting the initial message so i am in a loop

**Comment by sakiss** [comment]
I re-install it from scratch so can be closed
