### ISSUE TITLE
Unable to override knockout templates for form elements

### ISSUE THREAD

**Issue by chicgeek** [magento/magento2#1970]
I'm trying to override some knockout templates for basic form UI. I've coped over the files to the module folder in my theme dir and deleted the static folder so it knows to regenerate, with no luck.

An example of one of the template files I'm trying to overwrite, and the override path:

    /app/code/Magento/Ui/view/frontend/web/templates/form/element/input.html
    /app/design/frontend/MyPackage/MyTheme/Magento_Ui/web/templates/form/element/input.html

Things I've checked:
* I was very careful with these paths. The Ui module has both `template` and `templates`.
* Definitely using `.html`, not `.phtml`. :smile: 
* I am editing the correct template for what I want to change. I made a test change to the core files to check and it showed the change on the FE.
* Static files rebuilt successfully, excepting these templates.
* Cleared every cache I could find: Magento, Varnish, and local browser.

**Comment by lijithmg** [comment]
Your file should be placed at 
`/app/design/frontend/MyPackage/MyTheme/Magento_Ui/templates/form/element/input.html`

**Comment by chicgeek** [comment]
Arg, that seems to have solved it. Thanks for looking.

**Comment by rixitpatel13** [comment]
Hi, I got the things but what I am not getting is that How can I apply any custom onchange function for the zip code field on onepage checkout !

because what HTML is displaying, its generating by Knockout JS !

so, please tell me how can I do that !

Thanks in advance !
