### ISSUE TITLE
Admin product «Custom Options» tab controls («Import Options», «Add New Option» buttons) do not work when non-English locale is used

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1971]
![magento2-14](https://cloud.githubusercontent.com/assets/83204/10134829/8c6b0ab0-65f1-11e5-8b00-e0aa4d1d566f.png)

A detailed bug description and my fix: https://mage2.pro/t/92

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44055

**Comment by duhon** [comment]
Which language is the problem?

**Comment by dfediuk** [comment]
Every language with translation dictionary. Just read the analysys by the reference above.

**Comment by tanya-soroka** [comment]
@dfediuk could you please provide information about used browser and version of M2?

**Comment by dfediuk** [comment]
No. If you prefer do not read the analysis then I prefer to leave the bug unfixed.

**Comment by tanya-soroka** [comment]
@dfediuk , unfortunately we can't reproduce the issue on the later version. That is why we have requested additional information so we fix it.

**Comment by dfediuk** [comment]
Obviously, to reproduce the bug you need to create a translation dictionary with a translation for "Custom Options" phrase.
