### ISSUE TITLE
Inconsistency: 2 different verbs and 2 different nouns for the same action and thing: «The product template has been removed» / «We can't delete this set right now»

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1972]
I think the system should use the same verb in the both cases and it should be the standard verb "**delete**" (as in the other parts of the system).

The 2 nouns problem is similar to https://github.com/magento/magento2/issues/1956

https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/app/code/Magento/Catalog/Controller/Adminhtml/Product/Set/Delete.php#L39

https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/app/code/Magento/Catalog/Controller/Adminhtml/Product/Set/Delete.php#L42

**Comment by orlangur** [comment]
Nice catch :+1: "Product template" must be used everywhere instead of "attribute set", looks like "We can't delete this set right now" message was not updated.

**Comment by NadiyaS** [comment]
@dfediuk,
fix was delivered to mainline. Please see [ff0c608](https://github.com/magento/magento2/commit/ff0c6088f17cb8127f59eef9a87d41e1ff148981)
