### ISSUE TITLE
No Swap out Swatches for 2.0?

### ISSUE THREAD

**Issue by danielc1234** [magento/magento2#1973]
Unless I am missing it, I do not see the configurable swatches options for configurable products in Magento 2.0 like what was added in 1.9.  Will this be something that will be incorporated or am I just not seeing it?

**Comment by voleye** [comment]
Hi @danielc1234 , "Swatches" module is available in "develop" branch.

Once you install Magento from "develop" branch you can create an attribute with frontend type "Visual Swatch" or "Text Swatch".

Also, do not forget to set "global" scope in "Advanced Attribute Properties" section

**Comment by danielc1234** [comment]
@voleye I switched over to the deveop branch and now have massive errors. Is there a way to just get the develop branch to begin with? Mine was set to master.

Here is the lastest error I have tracked down.

a:4:{i:0;s:206:"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'failures_num' in 'field list', query was: UPDATE `admin_user` SET `failures_num` = ?, `first_failure` = ?, `lock_expires` = ? WHERE (user_id IN ('1'))";i:1;s:8147:"#0 /Projects/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)

**Comment by voleye** [comment]
@danielc1234 If it is not a problem to re-install Magento from scratch it probably would be the easiest way

In this case do the following:
 - drop the database and create new one
 - run the command in magento root `rm -rf ./var/* ./pub/static/* ./app/etc/config.php ./app/etc/env.php` please be sure that  you do not have any important files in these directories
 - go through Setup Wizard steps

**Comment by danielc1234** [comment]
@voleye Thanks, I was able to reinstall from scratch, however not able to add sample data and when trying to create a new product, it will not save. Just spins and spins. Can't seem to get anything working.

How often to you guys update to the master branch with updates?

**Comment by danielc1234** [comment]
@voleye nevermind on the saving issue, I was able to resolve that. However for some reason on configurable products, when I try to save  modifications, it says that I have to select a color, but yet the color options are grayed out.


![image](https://cloud.githubusercontent.com/assets/1151357/10172503/ab25b36c-66ad-11e5-8fe7-de23b2e411e0.png)

**Comment by danielc1234** [comment]
The value of attribute "color" must be set is the exact message

**Comment by voleye** [comment]
@danielc1234, you may made the color attribute as "not required".

Also check does this attribute has values?

**Comment by danielc1234** [comment]
@voleye Yes, set as required. Seems to be working, except swap out is not working on product page only on category page. But no big deal at this point, just trying to get fundamentals going.

What I was hoping to do is; as an example..., let's say we sell a chair that comes in 12 different colors. These chairs would have an optional 'cushion' if they wanted to add it to the chair order. There are over 22 different cushion colors. I was trying to get it so the swap out worked on the different colored chairs, but would like to have the option of the customer to be able to select the optional cushion and show the cushion color as well. But I did not want to have to create simple products for each chair color and cushion color available. That would be massive to say the least. Is there a way to accomplish this in magento 2.0? Or what would be your recommendations?

**Comment by voleye** [comment]
@danielc1234 

Unfortunately, you can`t create configurable product without creation the set of variations (that are simple products).

But these simple products are "Not Visible Individually" so you will not have any issues on the frontend. Also, you need not set the color for each of simple product it is enough to set the color for attribute values, so it should not be a routine job

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
