### ISSUE TITLE
The «i18n:collect-phrases» command wrongly handles PHP string concatenation

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1974]
An example of wrongly handled string: https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Main.php#L132-L133

A more detailed bug description: https://mage2.pro/t/93

**Comment by mazhalai** [comment]
Thank you for reporting, we have ticket MAGETWO-43435 to investigate a fix.

**Comment by mazhalai** [comment]
This has been delivered a while back and should be available in 2.0 Please have a look and let us know if this is fixed.

**Comment by mazhalai** [comment]
Closing since no response, and issue has been fixed.
