### ISSUE TITLE
Admin renaming product template group dialog: an input box height does not match the input text size

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1975]
![magento2-15](https://cloud.githubusercontent.com/assets/83204/10140662/5b4a63de-6611-11e5-8ebd-799b9f499287.png)

The latest Google Chrome browser.

**Comment by MomotenkoNatalia** [comment]
Internal reference: MAGETWO-43387 Thanks for reporting this issue!

**Comment by piotrekkaminski** [comment]
This was fixed and should be published soon.
