### ISSUE TITLE
Admin menu: why «Rating» is placed to the «Attributes» section?

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1977]
![magento2-16](https://cloud.githubusercontent.com/assets/83204/10141413/1490c3da-6615-11e5-887d-24f55ea77dd7.png)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
