### ISSUE TITLE
The diagnostic message «An attribute code must be fewer than %1 characters.» is semantically wrong

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1978]
It is wrong because the high bound is acceptable. 
A right phrase could be "not more than..."
A detailed description here: https://mage2.pro/t/94

**Comment by orlangur** [comment]
Could you prepare a pull request then? :wink: 

What is the reason of placing detailed description on separate site?

**Comment by dfediuk** [comment]
See also another bug with attribute code length validation: https://github.com/magento/magento2/issues/2073

**Comment by tanya-soroka** [comment]
Internal ticket has been created MAGETWO-44070.

**Comment by tanya-soroka** [comment]
@dfediuk issue has been fixed and available in the new version.
