### ISSUE TITLE
Cannot select next year from calendar picker

### ISSUE THREAD

**Issue by ffrodoe** [magento/magento2#1979]
Calendar picker offers years from 1915 to 2015. For example how can I select next year date for catalog price rule "to" field?
![screen_000042](https://cloud.githubusercontent.com/assets/12183505/10159328/46ac9c0a-66a0-11e5-9277-0fd453c23e45.jpg)

**Comment by vzaporozhets** [comment]
Will be merged soon: MAGETWO-43231. Thanks for reporting.
