### ISSUE TITLE
Product attribute labels in admin attribute grid and admin attribute view are not translatable (and my fix)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1983]
![magento2-20](https://cloud.githubusercontent.com/assets/83204/10181439/c58105d6-6720-11e5-80cc-e0f23c35d116.png)

The issue is similar to (but not the same as) https://github.com/magento/magento2/issues/1909 and https://github.com/magento/magento2/issues/1980

My fix with plugins: https://mage2.pro/t/96
Surely the possibility to translate product attributes should be in the core.

![magento2-18](https://cloud.githubusercontent.com/assets/83204/10181457/f50b2a3e-6720-11e5-87df-84a609850b09.png)

**Comment by voleye** [comment]
Hi @dfediuk 

Thank you for helping us make Magento better! We will discuss it and get back to you once we agreed on it.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-attribute-labels-in-admin-attribute-grid-and-admin/idi-p/45427).
