### ISSUE TITLE
when add custom attribute to customer which the backend New Customer  is now show

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1984]
class UpgradeData implements UpgradeDataInterface
{
    
    /**
     * @var CustomerSetupFactory
     */
    protected $customerSetupFactory;
    
    /**
     * @var AttributeSetFactory
     */
    private $attributeSetFactory;
    
    /**
     * @param CustomerSetupFactory $customerSetupFactory
     * @param AttributeSetFactory $attributeSetFactory
     */
    public function __construct(
        CustomerSetupFactory $customerSetupFactory,
        AttributeSetFactory $attributeSetFactory
    ) {
        $this->customerSetupFactory = $customerSetupFactory;
        $this->attributeSetFactory = $attributeSetFactory;
    }
 
    
    /**
     * {@inheritdoc}
     */
    public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        
        /** @var CustomerSetup $customerSetup */
        $customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);

        $customerEntity = $customerSetup->getEavConfig()->getEntityType('customer');
        $attributeSetId = $customerEntity->getDefaultAttributeSetId();

        /** @var $attributeSet AttributeSet */
        $attributeSet = $this->attributeSetFactory->create();
        $attributeGroupId = $attributeSet->getDefaultGroupId($attributeSetId);

        $customerSetup->addAttribute(Customer::ENTITY, 'magento_username', [
            'type' => 'varchar',
            'label' => 'Magento Username',
            'input' => 'text',
            'required' => false,
            'visible' => true,
            'user_defined' => true,
            'sort_order' => 1000,
            'position' => 1000,
            'system' => 0,
        ]);

        $attribute = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'magento_username')
        ->addData([
            'attribute_set_id' => $attributeSetId,
            'attribute_group_id' => $attributeGroupId,
            'used_in_forms' => ['adminhtml_customer'],
        ]);

        $attribute->save();
//        $customerSetup->removeAttribute(Customer::ENTITY, 'magento_username');
    }
}

the backend the backend New Customer  is now show
![1](https://cloud.githubusercontent.com/assets/10986726/10188856/391f916e-6795-11e5-871e-e540116efd8d.png)

**Comment by piotrekkaminski** [comment]
@LifeAsBook can you provide more information what were you trying to do and specific issue you have problems with?

**Comment by dfediuk** [comment]
Here is my code to add a custom attribute to the customers: https://mage2.pro/t/118
It work nice.

**Comment by LifeAsBook** [comment]
@dfediuk @piotrekkaminski  this bug on 1.0.0 beat master

**Comment by Vinai** [comment]
The github issue tracker is intended for technical issues only.
Please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) for technical questions. In your case probably the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2 would ) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
