### ISSUE TITLE
Trying to create admin controller but getting below error

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#1986]
Hello,

Fatal error: Class MageArray\Slider\Controller\Adminhtml\Slider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Magento\Framework\App\Action\Action::execute) in D:\wamp\www\mageArray\magento2\app\code\MageArray\Slider\Controller\Adminhtml\Slider.php on line 59

**Comment by okorshenko** [comment]
@sunilit42 , Could you, please, show content of your controller?

**Comment by sunilit42** [comment]
Controller Index File :+1: 
<?php
namespace MageArray\Slider\Controller\Adminhtml\Slider;
class Index extends \MageArray\Slider\Controller\Adminhtml\Slider {
	/**
     * @return void
     */
    public function execute()
    {
        echo "Gg";exit;
    }
}
Slider.php file 

<?php

namespace MageArray\Slider\Controller\Adminhtml;
use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Framework\Registry;
use Magento\Framework\View\Result\PageFactory;
use MageArray\Slider\Model\SliderFactory;
/**
 * Slider Controller
 */
abstract class Slider extends Action {
	/**
     * Core registry
     *
     * @var \Magento\Framework\Registry
     */
    protected $_coreRegistry;
 
    /**
     * Result page factory
     *
     * @var \Magento\Framework\View\Result\PageFactory
     */
    protected $_resultPageFactory;
 
    /**
     * News model factory
     *
     * @var \MageArray\Slider\Model\SliderFactory
     */
    protected $_sliderFactory;
 
    /**
     * @param Context $context
     * @param Registry $coreRegistry
     * @param PageFactory $resultPageFactory
     * @param SliderFactory $_sliderFactory
     */
	 
	  public function __construct(
        Context $context,
        Registry $coreRegistry,
        PageFactory $resultPageFactory,
        SliderFactory $sliderFactory
    ) {
       parent::__construct($context);
        $this->_coreRegistry = $coreRegistry;
        $this->_resultPageFactory = $resultPageFactory;
        $this->_sliderFactory = $sliderFactory;
    }
	
	protected function _isAllowed()
    {
        return true;
    }
	
	
}

**Comment by piotrekkaminski** [comment]
@okorshenko can you look at the provided code?

**Comment by antonkril** [comment]
Class is declared abstract, so php should not trigger this error. Does it still reproduce?

By the way, creating abstract controller for group of controllers in module is bad practice (especially if that controller only receives some arguments).
