### ISSUE TITLE
Order View page add custom button using Events

### ISSUE THREAD

**Issue by admin123** [magento/magento2#1987]
I have uses "adminhtml_block_html_before" events to add button in order view page.
I have print button list in tohtlm I got my custom button there but in backend It not displayed.

**Comment by admin123** [comment]
Please give me some solution, is It bug ?

**Comment by Stuperfied** [comment]
Please be patient, developers here are very busy and don't have time to troubleshoot possible errors when there are so many confirmed actual errors to be fixed. Sorry for being blunt but this section is for you to tell developers about bugs, not get help with your code. If you are in a hurry, please use a 3rd party source such as the magento section in stack exchange and report back here if you can confirm it is a bug.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
