### ISSUE TITLE
\Magento\Mail\Message is to closed in 2.3

### ISSUE THREAD

**Issue by 0m3r** [magento/magento2#19876]
### Summary
In Magento 2.3 
[\Magento\Mail\Message](https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/Mail/Message.php) is to close.

It does not allow you to change headers, encoding, add attachments.
[\Magento\Mail\Message](https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/Mail/Message.php) don't support setSender, addHeader, setMimeBoundary, [set|get]MessageId anymore.
But what if need to set custom headers like a 'in-reply-to', 'message-id', 'references' etc.
or for example we need to set multipart body and content-type 'multipart/alternative'

### Examples 
It works in Magento 2.2.7
~~~php
if ($mailMessage instanceof \Zend_Mail) {
    foreach ($headers as $headerKey => $headerValue) {
        $mailMessage->addHeader($headerKey, $headerValue);
    }
   //...
    $mailMessageId = $mailMessage->createMessageId();
    $mailMessage->setMessageId($mailMessageId);
   // ...
   $mailMessage->setMimeBoundary($boundary);
}
~~~

#### Solution 1 
Add public function getZendMessage()
~~~php
/**
 * @return \Zend\Mail\Message
 */
public function getZendMessage()
{
    return $this->zendMessage;
}
~~~

#### Solution 2 
Add getHeaders (getMime, setEncoding, etc.)
~~~php 
public function getHeaders()
{
    return $this->zendMessage->getHeaders();
}
~~~

#### Solution 3 
Add "public static function fromString($rawMessage)" something like in \Zend\Mail\Message

#### Solution 4 
Why don't extend \Zend\Mail\Message ?

**Comment by magento-engcom-team** [comment]
Hi @0m3r. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@0m3r do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@0m3r,

> \Magento\Mail\Message don't support setSender, addHeader, setMimeBoundary, [set|get]MessageId anymore.

Are they used in core currently?

Solution 1 and 4 - simply refer to PR where such interface was introduced for answers.

**Comment by 0m3r** [comment]
@orlangur
> Are they used in core currently?

No, I mean 3rd party modules. 
We need to send multipart mail.  We can't do that in Magento 2.3 but that option was available in earlier 2.2.x.

**Comment by orlangur** [comment]
> We can't do that in Magento 2.3 but that option was available in earlier 2.2.x.

This is not true, you can still do the same by relying on concrete ZF class implementation.

As we cannot add new methods to existing interfaces, I would recommend you to summarize methods which fulfill your needs in a new interface, probably some `MultipartMailMessageInterface`.

GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.

**Comment by 0m3r** [comment]
@orlangur  thanks for your advice.

**Comment by 0m3r** [comment]
>This is not true, you can still do the same by relying on concrete ZF class implementation.
>
> ... I would recommend you to summarize methods which fulfill your needs in a new interface, probably some MultipartMailMessageInterface.

One  problem with MultipartMailMessage

Dotdigitalgroup\Email\Plugin\MessagePlugin::afterSetBody() strong require Magento\Framework\Mail\Message

So for 2.3 all MessageInterface implements must extend \Magento\Framework\Mail\Message and cannot extend \Zend\Mail\Message
~~~
Fatal error: Uncaught TypeError: Argument 1 passed to Dotdigitalgroup\Email\Plugin\MessagePlugin::afterSetBody() must be an instance of Magento\Framework\Mail\Message, instance of [Vendor]\[Module]\Mail\Message\Interceptor given
~~~
That was fixed in dotmailer/dotmailer-magento2-extension https://github.com/dotmailer/dotmailer-magento2-extension/commit/6d452bcadf2940ab8e7949c21ada78cea7a0b095

but unfortunately magento/product-community-edition has strong version requirement for dotmailer/dotmailer-magento2-extension 3.0.1

~~~
 composer require dotmailer/dotmailer-magento2-extension:3.0.3

  Problem 1
    - magento/product-community-edition 2.3.0 requires dotmailer/dotmailer-magento2-extension 3.0.1 -> satisfiable by dotmailer/dotmailer-magento2-extension[3.0.1] but these conflict with your requirements or minimum-stability.
    - magento/product-community-edition 2.3.0 requires dotmailer/dotmailer-magento2-extension 3.0.1 -> satisfiable by dotmailer/dotmailer-magento2-extension[3.0.1] but these conflict with your requirements or minimum-stability.
    - magento/product-community-edition 2.3.0 requires dotmailer/dotmailer-magento2-extension 3.0.1 -> satisfiable by dotmailer/dotmailer-magento2-extension[3.0.1] but these conflict with your requirements or minimum-stability.
    - Installation request for magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0].

~~~

~~~
composer show magento/product-community-edition | grep dotmail
dotmailer/dotmailer-magento2-extension 3.0.1
~~~

**Comment by orlangur** [comment]
> So for 2.3 all MessageInterface implements must extend \Magento\Framework\Mail\Message and cannot extend \Zend\Mail\Message

I don't see a problem with this - use `\Zend\Mail\Message` the same way `\Magento\Framework\Mail\Message` uses it. Extending classes in general is discouraged.

**Comment by simon-letch** [comment]
@0m3r you can upgrade to dotmailer 3.0.3 by using the following composer command:

`composer require dotmailer/dotmailer-magento2-extension:"3.0.3 as 3.0.1"`

**Comment by 0m3r** [comment]
@simon-letch  
Do you mean that I can add this custom require in my module?
I think is not a good idea.
