### ISSUE TITLE
Install Magento 2.3.0 : Install fail with unchecked some modules

### ISSUE THREAD

**Issue by alex4allofyou** [magento/magento2#19882]
### Preconditions (*)

1. Magento 2.3.0
2. Wampserver 3.1.6 / Windows 10
3. PHP 7.2.13
4. Apache 2.4.35
5. MySQL 5.7.23

### Steps to reproduce (*)
1. Download magento 2.3.0 with Composer and open browser to get setup wizard page
2. Readiness Check approved
3. Add DB
4. Use normal settings, Magento generated key
5. Uncheck some or all additional modules, or check them all, tried every variation
6. Install

### Expected result (*)
You'd expect with a clean install, an easy install. 

### Actual result (*)

I get error seen in the title, well, the first time i did. 
Because after the error written down below I thought that maybe I needed to restart computer, that maybe some files of WAMP after upgrade PHP were not properly found, 

After I did this I did not get the error below but you see the install not progressing, it stays at : Installing... 15%. Console Log shows that it hangs at: Module 'Magento_InventorySales':

The first time it did not hang but gave this message:
Unable to apply patch for module Magento_InventorySales. Original exception message: The store that was requested wasn't found. Verify the store and try again. 

To be complete, this one:

Module 'Magento_InventorySales':
[ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\InventorySales\Setup\Patch\Schema\InitializeWebsiteDefaultSock for module Magento_InventorySales. Original exception message: The store that was requested wasn't found. Verify the store and try again. in C:\myurl.localhost\vendor\magento\framework\Setup\Patch\PatchApplier.php:232 Stack trace: #0 C:\myurl.localhost\setup\src\Magento\Setup\Model\Installer.php(1000): Magento\Framework\Setup\Patch\PatchApplier->applySchemaPatch('Magento_Invento...') #1 C:\myurl.localhost\setup\src\Magento\Setup\Model\Installer.php(831): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array) #2 [internal function]: Magento\Setup\Model\Installer->installSchema(Array) #3 C:\myurl.localhost\setup\src\Magento\Setup\Model\Installer.php(367): call_user_func_array(Array, Array) #4 C:\myurl.localhost\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #5 C:\myurl.localhost\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction() #6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #7 C:\myurl.localhost\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #8 C:\myurl.localhost\vendor\zendframework\zend-eventmanager\src\EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #9 C:\myurl.localhost\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #10 C:\myurl.localhost\vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #12 C:\myurl.localhost\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #13 C:\myurl.localhost\vendor\zendframework\zend-eventmanager\src\EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #14 C:\myurl.localhost\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent)) #15 C:\myurl.localhost\setup\index.php(39): Zend\Mvc\Application->run() #16 {main}

**Comment by magento-engcom-team** [comment]
Hi @alex4allofyou. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@alex4allofyou do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by alex4allofyou** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @alex4allofyou. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @alex4allofyou, here is your [Magento instance](https://i-19882-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19882-2-3-0.instances.magento-community.engineering/admin](https://i-19882-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by alex4allofyou** [comment]
Did not know I had to reproduce it like this, of course I cannot, it is happening during install.

**Comment by orlangur** [comment]
@alex4allofyou,

> Wampserver 3.1.6 / Windows 10

Can you reproduce an issue using a supported operating system: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html? Please reopen then. Note that Windows is not in the list.

**Comment by alex4allofyou** [comment]
Yes I have the same issue with Apache/2.4.6 CentOS with PHP 7.2.13. Hangs at Magento_InventorySales. Have tried many times.

**Comment by alex4allofyou** [comment]
> 
> 
> @alex4allofyou,
> 
> > Wampserver 3.1.6 / Windows 10
> 
> Can you reproduce an issue using a supported operating system: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html? Please reopen then. Note that Windows is not in the list.

I have tested it. 
Yes I have the same issue with Apache/2.4.6 CentOS with PHP 7.2.13. Hangs at Magento_InventorySales. Have tried many times.

**Comment by simonspoerri** [comment]
The Problem might be that the store ID was changed through a webserver configuration before the installation. At least that was causing this problem for me. Make sure your webserver sets the MAGE_RUN_CODE to "default" (or not at all) for the URL you're using for the installation process.

**Comment by orlangur** [comment]
@alex4allofyou sorry, missed your comment. Let's recheck. If you was able to figure out a root cause, please share your findings.

**Comment by engcom-Bravo** [comment]
Hello @alex4allofyou. Update your newely Preconditions and Actual result

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-19882-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19882-2-3-develop.instances.magento-community.engineering/admin](https://i-19882-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hi @alex4allofyou . We can't reproduce this issue. 
We tried on 4 computers and we never met such a problem. 
Can you give more information and maybe more steps for testing scenario?
Thanks!

**Comment by sdzhepa** [comment]
Hello @alex4allofyou 

I close this issue as `cannot reproduce` because we are not able to reproduce it by provided steps.

**Comment by sshymko** [comment]
As @simonspoerri correctly pointed out, the issue is reproducible when non-existing store code is specified in a web server configuration.

<img width="987" alt="magento2_install_store_not_found" src="https://user-images.githubusercontent.com/1231423/67363164-9f7ce880-f521-11e9-842d-7db9a2009b73.png">

You may have something like this in the Nginx config:
```nginx
map $host $MAGE_RUN_CODE {
    default                store1;
    store1.example.com     store1;
    store2.example.com     store2;
}
```

The issue is the Nginx misconfiguration and the fix would be:
```nginx
map $host $MAGE_RUN_CODE {
    default                "";
    store1.example.com     store1;
    store2.example.com     store2;
}
```
