### ISSUE TITLE
Keep Image Aspect Ratio

### ISSUE THREAD

**Issue by choma828** [magento/magento2#1989]
I'm working with Magento 2 Category Page.

But I couldn't know how to keep the product image aspect ratios.

In magento 1.x, I can get the image src to use below code.

<?php
    echo $this->helper('catalog/image')
    ->init($_product, 'small_image')
    ->constrainOnly(FALSE)
    ->keepAspectRatio(TRUE)
    ->keepFrame(FALSE)
    ->resize(300);
?>

But in magento 2, I can set the image sizes in /app/design/frontend/Magento/luma/etc/view.xml file.

&lt;image id=&quot;category_page_grid&quot; type=&quot;small_image&quot;&gt;
    &lt;width&gt;240&lt;/width&gt;
    &lt;height&gt;300&lt;/height&gt;
&lt;/image&gt;
&lt;image id=&quot;category_page_list&quot; type=&quot;small_image&quot;&gt;
    &lt;width&gt;240&lt;/width&gt;
    &lt;height&gt;300&lt;/height&gt;
&lt;/image&gt;

I tried to input the height with "auto", but it didn't work.

I also tried to input only width, it didn't work, too.

And I found below code for showing product images in Magento_Catalog/templates/product/list.phtml file.

<?php
    $productImage = $block->getImage($_product, $image);
?>
&lt;a href=&quot;&lt;?php echo $_product-&gt;getProductUrl() ?&gt;&quot; class=&quot;product photo product-item-photo&quot; tabindex=&quot;-1&quot;&gt;
    &lt;?php echo $productImage-&gt;toHtml(); ?&gt;
&lt;/a&gt;

Anyone know how to show the product images with keep Image aspect ratios?

**Comment by zanilee** [comment]
Hi, @choma828!

Try to add ```<aspect_ratio>true</aspect_ratio>``` to your image configuration like this:
```
<image id="category_page_list" type="small_image">
     <width>240</width>
     <height>300</height>
     <aspect_ratio>true</aspect_ratio>
</image>
```
See http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-images.html for details

**Comment by choma828** [comment]
Thanks for your reply.

How can I do it based on admin configuration values?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
