### ISSUE TITLE
Bug: A value of a custom dropdown attribute is formatted incorrectly (with leading comma) in admin product grid (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1990]
![magento2-01](https://cloud.githubusercontent.com/assets/83204/10210858/0990d04c-67f5-11e5-991e-06d097f02839.png)

A detailed description and my fix: https://mage2.pro/t/98

**Comment by piotrekkaminski** [comment]
internal issue: MAGETWO-43611

**Comment by sshrewz** [comment]
This issue has been fixed and merged to develop.  Let us know if you still encounter any issues by reopening this ticket.
