### ISSUE TITLE
[Proposal] - Easily create backend-readonly attributes

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#1991]
I tried to create Customer attribute which renders as readonly in the backend, but couldn't find an easy way to do it.

"Easy" for me means a new flag when creating an attribute (like `label`, `frontend_class` etc.) - say `adminhtml_readonly` - which changes the way its default renderer displays the input - exactly the way it renders when the attribute is `locked()`. 

Although the classes that render various HTML elements do support readonly functionality, I'm not sure if those can be easily coupled with an EAV attr flag.

I guess this can only be done for a couple of inputs, like `text`, `textarea`, but it'll be nice to be able to mark the attribute as readonly even for (multi)selects, `file`, `images` or others.

What do you think?

**Comment by pboisvert** [comment]
@antboiko Anton--passing to you since this is a catalog function

**Comment by ravichandrarv** [comment]
hey guys i'm trying to make some custom attributes as read only in magento2 i could not find a way to do it

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Proposal-Easily-create-backend-readonly-attributes/idi-p/44889).
