### ISSUE TITLE
Namespace and DI in Magento/Framework/App/Action (lib)

### ISSUE THREAD

**Issue by himssri** [magento/magento2#1992]
Hi, i got stuck on a point that there is three classes inside "Magento\Framework\App\Action" 
Action.php, AbstractAction.php and Context.php.

All three files are under same namespace "Magento\Framework\App\Action" defined on the top of each three files.

now my confusion is:
In Action.php in contructor is look like:
public function __construct(Context $context)
    {
       // some code
    }
And in AbstractAction.php constructor look like:
public function __construct(
        \Magento\Framework\App\Action\Context $context
    ) {
        // some code
    }

Now comparing both code see in the Constructor parameter that Context is passed in two different way, one is full path and second is just name. even both are working fine.
 Please clear my query regarding this.

**Comment by adragus-inviqa** [comment]
They both work. The first is relative to the current namespace and the latter, albeit being a bit redundant, is absolute. The second could've been very well set to `Context` instead of the full-qualified name and it still would've worked.

**Comment by himssri** [comment]
Yes i made a change to second as 'Context' it was working, i would have been digging that is inside magento 2  standard library they used both way with same moto. i think it is only just like.
correct?

**Comment by adragus-inviqa** [comment]
Not sure I understand what you're saying, but this is a consistency thing, and a small at that.
If you want, you could submit a PR, changing the `AbstractAction.php`'s constructor type hint to the more succint `Context`, instead of `\Magento\Framework\App\Action\Context`.

**Comment by himssri** [comment]
Sure, Thanks to you!
