### ISSUE TITLE
Design is broken in firefox if hide mass-action from new grid

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#1993]
We are making a new grid in our extension, and we don't need any actions for items. We disabled mass-action, and now design is broken in Firefox. Chrome OK.
![74b5bfea5632de70cb6d6fa5d1a1c68e33e29ede21d21c17d0 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/3024248/10220422/0623a2e4-6850-11e5-9bbf-6517c1be1c67.jpg)

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-43610

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-43610 is closed and delivered to mainline. Please, let us know if you still have an issue.
