### ISSUE TITLE
Feature Request: grid bookmark improvements

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#1994]
We want to use Bookmarks in new M2 Grids, but we have faced some issues.
First - there is no confirmation when I accedentally click on 'delete' icon. 
Also we can't just save current bookmark after some changes (I need to create new one). 
We also want to display list of bookmarks always somehow (buttons bar for instance), so that we could access it in just one click. There is also an idea to display bookmark name somewhere else, so that it would be clear what bookmark is actually beign used, for example to h1 page title.
There is also an idea to share bookmarks for other admin users. 
As for the grid. Column width is not a part of bookmark, unfortunately. If I made changes, it remember it in browser for all bookmarks within the grid. I think it would be better not to share width for another bookmarks within one grid.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-grid-bookmark-improvements/idi-p/44888).
