### ISSUE TITLE
Password Reset doesn't work.

### ISSUE THREAD

**Issue by alexhlynskyy** [magento/magento2#1996]
I receive email but it redirects to login page.

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-43608

**Comment by slavvka** [comment]
@alexhlynskyy, I couldn't reproduce the issue on the latest code. I have created an account, then logged out and opened 'Forget Your Password?' link. I entered my email, then got a letter with recovery link. I clicked on the link and got to Set a New Password form. After entering a new password awas redirected to log in page with 'You updated your password.' message. Please provide more details on how to reproduce your issue. Thank you!
