### ISSUE TITLE
«Admin» store title is untranslatable on admin attribute edit page neither by a dictionary nor manually (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#1998]
![magento2-01](https://cloud.githubusercontent.com/assets/83204/10237510/220d2d16-68bb-11e5-9721-eeb16d525095.png)

I fixed the problem with a plugin: https://mage2.pro/t/99

![2015-10-02_4-04-47](https://cloud.githubusercontent.com/assets/83204/10237531/4ddc92e2-68bb-11e5-97e7-17db3ba35cfd.png)

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-43612

**Comment by sshrewz** [comment]
Issue has been resolved. Feel free to reopen if you still encounter any issues.
