### ISSUE TITLE
Grid columns don't have identifiers

### ISSUE THREAD

**Issue by kassner** [magento/magento2#1999]
Hi,

The new grid system that was rolled out some weeks ago does not have any identifiers in the DOM, like a `id`, a `class` or a `data-*` attribute that allows us to know which data each column holds.

In that way, some useful resources for functional tests like [retrieving invoice IDs of an order](https://github.com/magento/magento2/blob/b4d2cb55f565a4a15921d976b067128803cc7246/dev/tests/functional/tests/app/Magento/Sales/Test/Block/Adminhtml/Order/View/Tab/Invoices/Grid.php#L55-L64) (used in CreateInvoiceStep) aren't achievable anymore since we can't identify the columns.

Is there a way to achieve this? I guess even with Javascript this isn't achievable anymore since RequireJS removes everything from the global scope.

Thanks!

**Comment by MaxSavich** [comment]
@kassner Thank you for the report, the internal ticket MAGETWO-43622 has been created.

**Comment by guz-anton** [comment]
Hi Rafael,
 1. As about storing info in DOM:
   - using `class` or even `id` is the worth decision that could be
   - using `data-*` attribute is make more sense. But.. It has limited number of usecases.
 2. From JS side you can access to any data that originated mentioned markup. Try in browser console on Products grid inside Admin area:
````
require('uiRegistry').get('product_listing.product_listing_data_source')['data']['items']; // to get array of products

require('uiRegistry').get('product_listing.product_listing.product_columns').elems(); // to get array of columns
````
You can find that when we talk about some **cell** in Grid we have access to huge amount of data: about row (Product item) and about column (Products Field). It not so suitable to store all this inside DOM node.

**Comment by kassner** [comment]
@guz-anton thanks for the update!

But that does not solve our testing problems. Even though this JavaScript works when running from console (it will help a lot for debugging), we still can't use it with Selenium to achieve what [this piece of code](https://github.com/magento/magento2/blob/b4d2cb55f565a4a15921d976b067128803cc7246/dev/tests/functional/tests/app/Magento/Sales/Test/Block/Adminhtml/Order/View/Tab/Invoices/Grid.php#L55-L64) was doing before the grid system update.
