### ISSUE TITLE
Magento Installation Issue

### ISSUE THREAD

**Issue by sanjayjethva** [magento/magento2#2000]
I am trying to installing the magento 2 but in step6 i facing below error.
tarting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema..
[ERROR] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'' in E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `st...', Array) #5 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(441): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `st...', Array) #6 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(496): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `st...', Array) #7 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `st...', Array) #8 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(1769): Zend_Db_Adapter_Abstract->insert('store_website', Array) #9 E:\xampp\htdocs\magento\app\code\Magento\Store\Setup\InstallSchema.php(236): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('store_website', Array) #10 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Model\Installer.php(779): Magento\Store\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext)) #11 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Model\Installer.php(713): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema') #12 [internal function]: Magento\Setup\Model\Installer->installSchema() #13 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Model\Installer.php(315): call_user_func_array(Array, Array) #14 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Controller\Install.php(88): Magento\Setup\Model\Installer->install(Array) #15 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #17 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #18 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #20 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #22 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #23 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #25 E:\xampp\htdocs\magento\setup\index.php(31): Zend\Mvc\Application->run() #26 {main} Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY', query was: INSERT INTO `store_website` (`website_id`, `code`, `name`, `sort_order`, `default_group_id`, `is_default`) VALUES (?, ?, ?, ?, ?, ?)' in E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:235 Stack trace: #0 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #1 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `st...', Array) #4 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(441): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `st...', Array) #5 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(496): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `st...', Array) #6 E:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `st...', Array) #7 E:\xampp\htdocs\magento\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(1769): Zend_Db_Adapter_Abstract->insert('store_website', Array) #8 E:\xampp\htdocs\magento\app\code\Magento\Store\Setup\InstallSchema.php(236): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('store_website', Array) #9 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Model\Installer.php(779): Magento\Store\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext)) #10 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Model\Installer.php(713): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema') #11 [internal function]: Magento\Setup\Model\Installer->installSchema() #12 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Model\Installer.php(315): call_user_func_array(Array, Array) #13 E:\xampp\htdocs\magento\setup\src\Magento\Setup\Controller\Install.php(88): Magento\Setup\Model\Installer->install(Array) #14 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #16 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #17 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #18 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #21 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #22 E:\xampp\htdocs\magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #23 E:\xampp\htdocs\magento\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 E:\xampp\htdocs\magento\setup\index.php(31): Zend\Mvc\Application->run() #25 {main}

**Comment by mazhalai** [comment]
@sanjayjethva did you have a previous installation of Magento? Looks like your database is not empty. You might want to use `bin/magento setup:upgrade` instead.

**Comment by MaxSavich** [comment]
@sanjayjethva, before launch the installation process - please make sure that Magento is not already installed. You can run php -f bin/magento setup:uninstall to make 100% sure that it is completely uninstalled, also try to do the composer update.

**Comment by sanjayjethva** [comment]
I have run the bin/magento setup:upgrade command and my problem get resolved.
Thanks for your answer.

**Comment by ghost** [comment]
Yes this solves the problem. But what caused it, does anyone know ?
