### ISSUE TITLE
Magento 2.3.0 installation stops at 96% at data recurring

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [magento/magento2#20035]
I am using Windows 7 and wamp server.

My installation log shows as follows

Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_Config':

Module 'Magento_Indexer':

Module 'Magento_Search':

Module 'Magento_Security':

Module 'Magento_User':

Module 'Magento_Authorization':

Module 'Magento_Customer':

Module 'Magento_Rule':

Module 'Magento_Backup':

Module 'Magento_Cms':

Module 'Magento_Catalog':

Module 'Magento_CatalogRule':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Integration':

Module 'Magento_EavGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Payment':

Module 'Magento_CatalogInventory':

Module 'Magento_Cron':

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_Vault':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Paypal':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_UrlRewrite':

Module 'Magento_ConfigurableProduct':

Module 'Magento_GroupedProduct':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Email':

Module 'Klarna_Core':

Module 'Magento_SampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Amazon_Core':

Module 'Magento_Tax':

Module 'Magento_CatalogGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_AdvancedSearch':

Module 'Magento_Newsletter':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_CatalogSampleData':

Module 'Magento_InstantPurchase':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryApi':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventorySalesApi':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_MediaStorage':

Module 'Magento_Multishipping':

Module 'Magento_ProductAlert':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Klarna_Ordermanagement':

Module 'Magento_Reports':

Module 'Magento_Bundle':

Module 'Amazon_Login':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_SendFriend':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_ThemeSampleData':

Module 'Magento_SalesInventory':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_Wishlist':

Module 'Magento_Webapi':

Module 'Magento_Swatches':

Module 'Magento_Translation':

Module 'Magento_UrlRewriteGraphQl':

Module 'Magento_AsynchronousOperations':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Swagger':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_Config':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_Search':

Module 'Magento_Security':

Module 'Magento_User':

Module 'Magento_Authorization':

Module 'Magento_Customer':

Module 'Magento_Rule':

Module 'Magento_Backup':

Module 'Magento_Cms':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_CatalogRule':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':
Running schema recurring...

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_EavGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Payment':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_Cron':
Running schema recurring...

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_Widget':

Module 'Magento_Vault':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Paypal':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_UrlRewrite':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_GroupedProduct':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Email':

Module 'Klarna_Core':

Module 'Magento_SampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Amazon_Core':

Module 'Magento_Tax':

Module 'Magento_CatalogGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_AdvancedSearch':

Module 'Magento_Newsletter':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_CatalogSampleData':

Module 'Magento_InstantPurchase':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryApi':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventorySalesApi':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_MediaStorage':

Module 'Magento_Multishipping':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Klarna_Ordermanagement':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_Bundle':
Running schema recurring...

Module 'Amazon_Login':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_SendFriend':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_ThemeSampleData':

Module 'Magento_SalesInventory':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_Wishlist':
Running schema recurring...

Module 'Magento_Webapi':

Module 'Magento_Swatches':

Module 'Magento_Translation':

Module 'Magento_UrlRewriteGraphQl':

Module 'Magento_AsynchronousOperations':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Swagger':

Installing user configuration...

Enabling caches:
Current status:
Array ( [config] => 1 [layout] => 1 [block_html] => 1 [collections] => 1 [reflection] => 1 [db_ddl] => 1 [compiled_config] => 1 [eav] => 1 [customer_notification] => 1 [config_integration] => 1 [config_integration_api] => 1 [full_page] => 1 [config_webservice] => 1 [translate] => 1 ) 

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_Config':

Module 'Magento_Indexer':

Module 'Magento_Search':

Module 'Magento_Security':

Module 'Magento_User':

Module 'Magento_Authorization':

Module 'Magento_Customer':

Module 'Magento_Rule':

Module 'Magento_Backup':

Module 'Magento_Cms':

Module 'Magento_Catalog':

Module 'Magento_CatalogRule':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Integration':

Module 'Magento_EavGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Payment':

Module 'Magento_CatalogInventory':

Module 'Magento_Cron':

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_Vault':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Paypal':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_UrlRewrite':

Module 'Magento_ConfigurableProduct':

Module 'Magento_GroupedProduct':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Email':

Module 'Klarna_Core':

Module 'Magento_SampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Amazon_Core':

Module 'Magento_Tax':

Module 'Magento_CatalogGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_AdvancedSearch':

Module 'Magento_Newsletter':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_CatalogSampleData':

Module 'Magento_InstantPurchase':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryApi':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventorySalesApi':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_MediaStorage':

Module 'Magento_Multishipping':

Module 'Magento_ProductAlert':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Klarna_Ordermanagement':

Module 'Magento_Reports':

Module 'Magento_Bundle':

Module 'Amazon_Login':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_SendFriend':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_ThemeSampleData':

Module 'Magento_SalesInventory':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_Wishlist':

Module 'Magento_Webapi':

Module 'Magento_Swatches':

Module 'Magento_Translation':

Module 'Magento_UrlRewriteGraphQl':

Module 'Magento_AsynchronousOperations':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Swagger':

Data post-updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':
Running data recurring...

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_Config':

Module 'Magento_Indexer':
Running data recurring...

Module 'Magento_Search':

Module 'Magento_Security':

Module 'Magento_User':

Module 'Magento_Authorization':

Module 'Magento_Customer':
Running data recurring...

Module 'Magento_Rule':

Module 'Magento_Backup':

Module 'Magento_Cms':

Module 'Magento_Catalog':

Module 'Magento_CatalogRule':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':
Running data recurring...

Module 'Magento_Integration':

Module 'Magento_EavGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Payment':

Module 'Magento_CatalogInventory':

Module 'Magento_Cron':

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_Vault':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Paypal':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_UrlRewrite':

Module 'Magento_ConfigurableProduct':

Module 'Magento_GroupedProduct':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Email':

Module 'Klarna_Core':

Module 'Magento_SampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Amazon_Core':

Module 'Magento_Tax':

Module 'Magento_CatalogGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_AdvancedSearch':

Module 'Magento_Newsletter':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_CatalogSampleData':

Module 'Magento_InstantPurchase':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryApi':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventorySalesApi':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_MediaStorage':

Module 'Magento_Multishipping':

Module 'Magento_ProductAlert':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Klarna_Ordermanagement':

Module 'Magento_Reports':

Module 'Magento_Bundle':

Module 'Amazon_Login':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_SendFriend':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_ThemeSampleData':

Module 'Magento_SalesInventory':

Module 'Magento_ConfigurableSampleData':
Running data recurring...

The error in my window console is 
POST http://localhost/magento/setup/index.php/install/start 500 (Internal Server Error)

**Comment by magento-engcom-team** [comment]
Hi @JERINJACOBCHERIAN. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@JERINJACOBCHERIAN do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
Please check your server logs for the exact error. Also such questions were often asked and this is more about your setup than Magento itself.

**Comment by DanielRuf** [comment]
https://magento.stackexchange.com/ is a better place to ask such general questions.

**Comment by JERINJACOBCHERIAN** [comment]
But I think is a bit of a bug in 2.3.0

Could you just check this question

https://magento.stackexchange.com/questions/252188/magento-2-2-7-admin-panel-blank-page/252293?noredirect=1#comment360810_252293

**Comment by DanielRuf** [comment]
In general we can not do much without the logfile entries. Still, this is not a bug per se but a problem with your system probably.
