### ISSUE TITLE
The commit «PCF: removing grouped price» from 2015-10-02 breaks Magento schema upgrading with the exception: «there can be only one auto column and it must be defined as a key» (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2007]
https://mage2.pro/t/102

**Comment by dfediuk** [comment]
My fix: https://mage2.pro/t/topic/102/2

**Comment by NadiyaS** [comment]
Hi @dfediuk,
thanks for your report. Internal issue was created MAGETWO-43755

**Comment by vladimir-k** [comment]
Hi, @dfediuk . The issue has already been fixed and delivered to develop branch (0f351d6a80cd5c8c981e517dd849dd7ce06791d4). Thanks for reporting!
