### ISSUE TITLE
Magento 2 Can't Install Sample Data

### ISSUE THREAD

**Issue by amustci065** [magento/magento2#20099]
Magento 2 Sample Data suddenly stopped at this junction @ "Module'Magento_DownloadableSampleData':" during installation.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 3449720 bytes) in C:\wamp64\www\magento\vendor\magento\module-downloadable-samp le-data\Model\Product\Converter.php on line 103

Have tried every solution but doesn't work for me. But when I check memory limit with using php -r "echo ini_get('memory_limit').PHP_EOL; Discovered I have 128M. Off which have changed every files that have to do with memory_limit to 2048M.

 Magento 2 version is 2.1.0  Php 7.1.0

`I'm not really sure what I can do to alleviate this issue. Please someone help me

**Here is the installation process:** 

Module 'Magento_Braintree':
Module 'Magento_InstantPurchase':
Module 'Magento_CatalogAnalytics':
Module 'Magento_Inventory':
Module 'Magento_InventoryAdminUi':
Module 'Magento_InventoryApi':
Module 'Magento_InventoryBundleProduct':
Module 'Magento_InventoryBundleProductAdminUi':
Module 'Magento_InventoryCatalog':
Module 'Magento_InventorySales':
Module 'Magento_InventoryCatalogAdminUi':
Module 'Magento_InventoryCatalogApi':
Module 'Magento_InventoryCatalogSearch':
Module 'Magento_InventoryConfigurableProduct':
Module 'Magento_InventoryConfigurableProductAdminUi':
Module 'Magento_InventoryConfigurableProductIndexer':
Module 'Magento_InventoryConfiguration':
Module 'Magento_InventoryConfigurationApi':
Module 'Magento_InventoryGroupedProduct':
Module 'Magento_InventoryGroupedProductAdminUi':
Module 'Magento_InventoryGroupedProductIndexer':
Module 'Magento_InventoryImportExport':
Module 'Magento_InventoryIndexer':
Module 'Magento_InventoryLowQuantityNotification':
Module 'Magento_InventoryLowQuantityNotificationAdminUi':
Module 'Magento_InventoryLowQuantityNotificationApi':
Module 'Magento_InventoryMultiDimensionalIndexerApi':
Module 'Magento_InventoryProductAlert':
Module 'Magento_InventoryReservations':
Module 'Magento_InventoryReservationsApi':
Module 'Magento_InventoryCache':
Module 'Magento_InventorySalesAdminUi':
Module 'Magento_InventorySalesApi':
Module 'Magento_InventorySalesFrontendUi':
Module 'Magento_InventoryShipping':
Module 'Magento_Shipping':
Module 'Magento_InventorySourceDeductionApi':
Module 'Magento_InventorySourceSelection':
Module 'Magento_InventorySourceSelectionApi':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_MessageQueue':
Module 'Magento_GroupedProductSampleData':
Module 'Magento_MsrpSampleData':
Module 'Magento_Multishipping':
Module 'Magento_MysqlMq':
Running schema recurring...
Module 'Magento_NewRelicReporting':
Module 'Magento_ProductAlert':
Running schema recurring...
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_OfflineShipping':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Klarna_Ordermanagement':
Module 'Magento_Persistent':
Module 'Magento_Reports':
Running schema recurring...
Module 'Magento_Bundle':
Running schema recurring...
Module 'Magento_ProductVideo':
Module 'Amazon_Login':
Module 'Magento_QuoteAnalytics':
Module 'Magento_QuoteGraphQl':
Module 'Magento_ReleaseNotification':
Module 'Magento_Review':
Module 'Magento_RequireJs':
Module 'Magento_SendFriend':
Module 'Magento_ReviewAnalytics':
Module 'Magento_BundleSampleData':
Module 'Magento_Robots':
Module 'Magento_Rss':
Module 'Magento_ThemeSampleData':
Module 'Amazon_Payment':
Module 'Magento_SalesAnalytics':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShippingSampleData':
Module 'Magento_DownloadableSampleData':
Module 'Magento_TaxSampleData':
Module 'Magento_ConfigurableSampleData':
Module 'Magento_ProductLinksSampleData':
Module 'Magento_Elasticsearch':
Module 'Magento_CustomerAnalytics':
Module 'Magento_Wishlist':
Running schema recurring...
Module 'Magento_InventoryShippingAdminUi':
Module 'Magento_Signifyd':
Module 'Magento_Sitemap':
Module 'Magento_CatalogInventoryGraphQl':
Module 'Magento_DownloadableGraphQl':
Module 'Magento_Webapi':
Module 'Magento_SwaggerWebapi':
Module 'Magento_SwaggerWebapiAsync':
Module 'Magento_Swatches':
Module 'Magento_SwatchesGraphQl':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_SwatchesSampleData':
Module 'Magento_ReviewSampleData':
Module 'Magento_TaxGraphQl':
Module 'Magento_TaxImportExport':
Module 'Magento_CustomerSampleData':
Module 'Magento_ConfigurableProductSales':
Module 'Magento_CmsSampleData':
Module 'Magento_Tinymce3':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_SalesSampleData':
Module 'Magento_UrlRewriteGraphQl':
Module 'Magento_AsynchronousOperations':
Module 'Magento_Usps':
Module 'Magento_CatalogRuleSampleData':
Module 'Klarna_Kp':
Module 'Magento_Version':
Module 'Magento_Swagger':
Module 'Magento_WebapiAsync':
Module 'Magento_WebapiSecurity':
Module 'Magento_SalesRuleSampleData':
Module 'Magento_WeeeGraphQl':
Module 'Magento_CatalogWidget':
Module 'Magento_WidgetSampleData':
Module 'Dotdigitalgroup_Email':
Running schema recurring...
Module 'Magento_WishlistAnalytics':
Module 'Magento_WishlistSampleData':
Module 'Temando_Shipping':
Module 'Vertex_Tax':
Data install/update:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_Theme':
Module 'Magento_Backend':
Module 'Magento_Variable':
Module 'Magento_Eav':
Module 'Magento_AdminNotification':
Module 'MSP_ReCaptcha':
Module 'Magento_Config':
Module 'Magento_Indexer':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Search':
Module 'Magento_Amqp':
Module 'Magento_Security':
Module 'Magento_User':
Module 'Magento_Authorization':
Module 'Magento_Customer':
Module 'Magento_Rule':
Module 'Magento_Backup':
Module 'Magento_Cms':
Module 'Magento_Catalog':
Module 'Magento_GraphQl':
Module 'Magento_BundleImportExport':
Module 'Magento_CatalogRule':
Module 'Magento_CacheInvalidate':
Module 'Magento_Quote':
Module 'Magento_SalesSequence':
Module 'Magento_Integration':
Module 'Magento_EavGraphQl':
Module 'Magento_CatalogImportExport':
Module 'Magento_Payment':
Module 'Magento_CatalogInventory':
Module 'Magento_Cron':
Module 'Magento_Msrp':
Module 'Magento_CatalogSearch':
Module 'Magento_Sales':
Module 'Magento_Checkout':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_CatalogUrlRewriteGraphQl':
Module 'Magento_Widget':
Module 'Magento_Vault':
Module 'Magento_CheckoutAgreements':
Module 'Magento_Paypal':
Module 'Magento_CmsGraphQl':
Module 'Magento_Downloadable':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_CmsUrlRewriteGraphQl':
Module 'MSP_TwoFactorAuth':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_UrlRewrite':
Module 'Magento_StoreGraphQl':
Module 'Magento_ConfigurableProduct':
Module 'Magento_GroupedProduct':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Email':
Module 'Magento_CurrencySymbol':
Module 'Klarna_Core':
Module 'Magento_Analytics':
Module 'Magento_CustomerGraphQl':
Module 'Magento_CustomerImportExport':
Module 'Magento_SampleData':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Amazon_Core':
Module 'Magento_Tax':
Module 'Magento_CatalogGraphQl':
Module 'Magento_ImportExport':
Module 'Magento_Weee':
Module 'Magento_Authorizenet':
Module 'Magento_BundleGraphQl':
Module 'Magento_AdvancedSearch':
Module 'Magento_Newsletter':
Module 'Magento_EncryptionKey':
Module 'Magento_Fedex':
Module 'Magento_GiftMessage':
Module 'Magento_GoogleAdwords':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_ConfigurableProductGraphQl':
Module 'Magento_GroupedImportExport':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_GroupedProductGraphQl':
Module 'Magento_CatalogSampleData':
Module 'Magento_DownloadableImportExport':
Module 'Magento_Braintree':
Module 'Magento_InstantPurchase':
Module 'Magento_CatalogAnalytics':
Module 'Magento_Inventory':
Module 'Magento_InventoryAdminUi':
Module 'Magento_InventoryApi':
Module 'Magento_InventoryBundleProduct':
Module 'Magento_InventoryBundleProductAdminUi':
Module 'Magento_InventoryCatalog':
Module 'Magento_InventorySales':
Module 'Magento_InventoryCatalogAdminUi':
Module 'Magento_InventoryCatalogApi':
Module 'Magento_InventoryCatalogSearch':
Module 'Magento_InventoryConfigurableProduct':
Module 'Magento_InventoryConfigurableProductAdminUi':
Module 'Magento_InventoryConfigurableProductIndexer':
Module 'Magento_InventoryConfiguration':
Module 'Magento_InventoryConfigurationApi':
Module 'Magento_InventoryGroupedProduct':
Module 'Magento_InventoryGroupedProductAdminUi':
Module 'Magento_InventoryGroupedProductIndexer':
Module 'Magento_InventoryImportExport':
Module 'Magento_InventoryIndexer':
Module 'Magento_InventoryLowQuantityNotification':
Module 'Magento_InventoryLowQuantityNotificationAdminUi':
Module 'Magento_InventoryLowQuantityNotificationApi':
Module 'Magento_InventoryMultiDimensionalIndexerApi':
Module 'Magento_InventoryProductAlert':
Module 'Magento_InventoryReservations':
Module 'Magento_InventoryReservationsApi':
Module 'Magento_InventoryCache':
Module 'Magento_InventorySalesAdminUi':
Module 'Magento_InventorySalesApi':
Module 'Magento_InventorySalesFrontendUi':
Module 'Magento_InventoryShipping':
Module 'Magento_Shipping':
Module 'Magento_InventorySourceDeductionApi':
Module 'Magento_InventorySourceSelection':
Module 'Magento_InventorySourceSelectionApi':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_MessageQueue':
Module 'Magento_GroupedProductSampleData':
Module 'Magento_MsrpSampleData':
Module 'Magento_Multishipping':
Module 'Magento_MysqlMq':
Module 'Magento_NewRelicReporting':
Module 'Magento_ProductAlert':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_OfflineShipping':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Klarna_Ordermanagement':
Module 'Magento_Persistent':
Module 'Magento_Reports':
Module 'Magento_Bundle':
Module 'Magento_ProductVideo':
Module 'Amazon_Login':
Module 'Magento_QuoteAnalytics':
Module 'Magento_QuoteGraphQl':
Module 'Magento_ReleaseNotification':
Module 'Magento_Review':
Module 'Magento_RequireJs':
Module 'Magento_SendFriend':
Module 'Magento_ReviewAnalytics':
Module 'Magento_BundleSampleData':
Module 'Magento_Robots':
Module 'Magento_Rss':
Module 'Magento_ThemeSampleData':
Module 'Amazon_Payment':
Module 'Magento_SalesAnalytics':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShippingSampleData':
Module 'Magento_DownloadableSampleData':

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
 3449720 bytes) in C:\wamp64\www\magento\vendor\magento\module-downloadable-samp
le-data\Model\Product\Converter.php on line 103

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-error
s for more info on how to handle out of memory errors.
C:\wamp64\www\magento>

`

**Comment by magento-engcom-team** [comment]
Hi @amustci065. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amustci065 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
Hi @amustci065, I see few issues with this report.

Windows is not supported and thus WAMP must not be used to deploy Magento.
Memory limit should be increased to recommended values.
Problems with `2.1.x` release line are not maintained here anymore, try using `2.2.x` or `2.3.x` version.
