### ISSUE TITLE
The title «Store Design Schedule» above the admin design changes grid is untranslatable (and my fix)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2009]
https://mage2.pro/t/104

![magento2-01](https://cloud.githubusercontent.com/assets/83204/10254705/0cc38c0a-694e-11e5-8d6c-38ef733055ee.png)

**Comment by mbrinton01** [comment]
Hello @dfediuk, can you create a pull request for the fix you propose?

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thank you for contributing, i will close this issue for now as no update more than 14 days, if you think that issue is still reproducible, please fell free to open another one.
