### ISSUE TITLE
Unable to get customer data from customer session

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#2010]
I have DI in constructor to inject customer session to my class \Magento\Customer\Model\Session $customerSession, But the injected session object does not contain customer id or customer reference.I also checked the injected session on Magento\Catalog\Block\Product\View it also does not contain customer id or reference
```php
public function __construct(
        TemplateContext $context,
        Session $customerSession,
        CustomerRepositoryInterface $customerRepository,
        HttpContext $httpContext,
        array $data = []
    ) {
        $this->customerSession = $customerSession;
        $this->customerRepository = $customerRepository;
        $this->httpContext = $httpContext;
        $this->scopeConfig = $context->getScopeConfig();
        parent::__construct($context, $data);
        
        // customer session does not contain customer data
        $cid=$this->customerSession->getId(); // returns null
    }
```

**Comment by bgkavinga** [comment]
After some investigation we found that Magento/Customer/Model/Layout/DepersonalizePlugin.php::afterGenerateXml() is clearing the data from customer session when cache is enabled
```php
public function afterGenerateXml(\Magento\Framework\View\LayoutInterface $subject, $result)
    {
        if ($this->depersonalizeChecker->checkIfDepersonalize($subject)) {
            $this->visitor->setSkipRequestLogging(true);
            $this->visitor->unsetData();
            $this->session->clearStorage();
            $this->customerSession->clearStorage();
            $this->session->setData(\Magento\Framework\Data\Form\FormKey::FORM_KEY, $this->formKey);
            $this->customerSession->setCustomerGroupId($this->customerGroupId);
            $this->customerSession->setCustomer($this->customerFactory->create()->setGroupId($this->customerGroupId));
        }
        return $result;
    }
```

**Comment by antonkril** [comment]
Can this issue be closed?

**Comment by sylvainraye** [comment]
@bgkavinga and how did you fix your issue ? I have a similar problem with a block which needs customer information. Due to the plugin which depersonalize customer data in Customer Module, I cannot get the customer data when the cache is enabled. This depersonalizeChecker method is called before the block is instantiated.

**Comment by sylvainraye** [comment]
Looks like that you may find the answer here: http://magento.stackexchange.com/questions/86674/block-with-cachable-false-not-rendered-on-product-view-page/90130#90130

The block must not be in saved in cache (which is quite logic) however it must also be the property of the block must be set to `_isScopePrivate = true`

**Comment by bgkavinga** [comment]
@diglin My first solution was disable cache for that block in layout file. But it slows down the page load. When it comes to Varnish it always do esi update for that block. So I had to get customer session data directly from the $_SESSION until they come up with solution. May be this has been fixed in GA release.

**Comment by sylvainraye** [comment]
@bgkavinga thanks for your feedback. The solution from stack exchange worked for me. Do not forget to clean your cache.

**Comment by ankita-agrawal** [comment]
Any updates for this issue on latest magento2 version? I tried  $_SESSION but its not working for category and product pages.

**Comment by sengaigibon** [comment]
I think this issue is directly related to #3572

**Comment by mudithae** [comment]
It seems that this issue is still exist even in the 2.1.6. Any workaround is appreciated.
$_SESSION['customer_base']['customer_id'] is also null

**Comment by mudithae** [comment]
Finally below workaround worked for me. (Clue from : https://github.com/magento/magento2/issues/3294  post by @saravananvelu)
` $customerSession = $this->_objectManager->create('Magento\Customer\Model\SessionFactory')->create();
        return $customerSession->getCustomer()->getId();`

**Comment by dmytro-ch** [comment]
That does not seem to be an issue since Magento 2 cleans the session storage for cacheable requests in order to avoid caching of customer private content. In short, you should not access the customer session data, while processing the GET request intended to render the cacheable page.
I would also not recommend disabling the cache for the whole page via layout update as a workaround.
Magento 2 provides a special approach to work with a customer private content.
You can find more details in [Magento DevDocs: Private Content](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching/private-content.html) section.

**Comment by adnnor** [comment]
As @dmytro-ch said you have to use a special Magento approach to work with the private content. Here is an example https://github.com/adnnor/customer-session-sections

**Comment by erikffflabel** [comment]
when cache is enabled and you have session->getCustomerId = null issue, you just need to add Factory pattern
Magento/blabla/Customer/SessionFactory

private SessionFactory $customerSessionFactory;

construct(SessionFactory $customerSessionFactory) {
$this-customerSessionFactory = $customerSessionFactory;
}

public function someFunction() {
$sessionModel = $this->customerSessionFactory->create();
return $sessionModel->getCustomer()->getId()
}

that is very good solution for this issue :)

**Comment by duckchip** [comment]
@erikffflabel thanks for the tip, this helped me a lot!
