### ISSUE TITLE
Assets cache on develop branch not exist?

### ISSUE THREAD

**Issue by cermat** [magento/magento2#2011]
I just work on develop branch, but i can't see "Index Management" and assets cache(css/js) on "Cache Management".

This is normal or there something wrong with my enviorment?

I was work on "master" branch before, Index Management and Assets cache exist there.

Thanks

![screen shot 2015-10-03 at 2 06 54 pm](https://cloud.githubusercontent.com/assets/14008673/10261870/8f1312b8-69d8-11e5-9181-a2a7c7658987.png)

**Comment by davidalger** [comment]
@cermat on a copy of M2 running on the latest develop branch I cannot reproduce this as a bug - they both show up fine - Index Management is located under the top-level System menu and the static asset caches have buttons beneath the grid in your screenshot to clear.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
