### ISSUE TITLE
Why does «Manage Stock» setting have the GLOBAL scope? Need set it per website.

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2012]
Two different websites could  have totally different kind of products: virtual for a one and physical for another.
What was the sense to make the scope of «**Manage Stock**» option global?

![2015-10-03_19-33-53](https://cloud.githubusercontent.com/assets/83204/10263923/ffc555ba-6a06-11e5-9663-ba1279da161d.png)

**Comment by piotrekkaminski** [comment]
@mbrinton01 please check this one

**Comment by mbrinton01** [comment]
Thank you for your feedback @dfediuk, we will consider this for a future update. It was originally created this way because the stock management option was created before it was possible to have multiple webstores.

**Comment by katmoon** [comment]
I'm closing the ticket due to @mbrinton01 comment.

@dfediuk thank you for sharing the idea for improvement!

**Comment by katmoon** [comment]
Internal ticket `MAGETWO-50583` has been created for this issue.

**Comment by qrz-io** [comment]
Hey @katmoon - can you share clarify if this will include the ability to have different product stock per website? Is there an ETA?

**Comment by katmoon** [comment]
I don't have this knowledge. Maybe @mbrinton01 knows.

**Comment by mbrinton01** [comment]
Hello @qrz-io, we are working on building Multi-Node Inventory that will include the ability to set stock for multiple sources and assign these sources to websites, but do not have an exact ETA.  More detail is in #473

**Comment by tuyennn** [comment]
Hi @magento-engcom-team any ref to this issue as you marked it was done on branch [2.3-develop]?

**Comment by mbrinton01** [comment]
@tuyennn Please see the MSI project for more information: https://github.com/magento-engcom/msi
