### ISSUE TITLE
A failure while creating a configurable product: «URL key for specified store already exists»

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2013]
Surely, while autogenerate simple variants of a configurable product the system need to check whether an autogenerated url key conflicts with an already existed product.

https://mage2.pro/t/107

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44058

**Comment by tanya-soroka** [comment]
@dfediuk the fix of the issues is available. I am going to close this ticket.
Feel free to reopen if you have any comments.
