### ISSUE TITLE
Discussion: Setting MAGE_MODE in app/etc/env.php?

### ISSUE THREAD

**Issue by amenk** [magento/magento2#2014]
Why don't we set the MAGE_MODE in app/etc/env.php ? By doing so the setting could be used consistently by the webserver and console. 

And there would not be two points to change configuration.

**Comment by xcomSteveJohnson** [comment]
Nowadays you can; in fact, there's a fairly new CLI for it: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html

**Comment by amenk** [comment]
Interesting. Where does it store the mode? And is this the reason for removing the static content deploy command?

**Comment by xcomSteveJohnson** [comment]
The static content command is still there. See https://github.com/magento/magento2/commit/857221f70af2aedcd6192a2e00655f4abdf6083a#commitcomment-13593500

Mode is stored in env.php.

**Comment by alankent** [comment]
See also http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html - it documents the CLI command etc to change the mode.

**Comment by choukalos** [comment]
It was stored in the config.xml file when the CLI changed mode.  Team's going to refactor it so it'll only be stored in env.php when the CLI makes a change.  Note that if the shell's environment is set that'll take precedence.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
