### ISSUE TITLE
Bug: the system requires to set a configurable option of configurable (not simple) product

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2015]
https://mage2.pro/t/108

![magento2-01](https://cloud.githubusercontent.com/assets/83204/10265272/b7cefe38-6a32-11e5-9f03-6e9a88f7dca8.png)

![magento2-02](https://cloud.githubusercontent.com/assets/83204/10265273/bbc92144-6a32-11e5-8ca4-6c1e79d3a03e.png)

**Comment by tanya-soroka** [comment]
@dfediuk , This issue should be fixed in new versions. We will verify it.
