### ISSUE TITLE
BUG: the product general attributes (name, sku, price, quantity) are wrongly in "Images and Videos" section now

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2016]
![magento2-03](https://cloud.githubusercontent.com/assets/83204/10265303/b6aa8700-6a34-11e5-8d4e-4fd35dfb821b.png)

**Comment by dfediuk** [comment]
The cause of the bug: https://mage2.pro/t/topic/111/2

**Comment by tkacheva** [comment]
@dfediuk, please provide steps to reproduce the bug

**Comment by maghamed** [comment]
Internal ticket to fix this problem created

**Comment by dfediuk** [comment]
Just look at the code: it is definitely wrong and I have decribed it by the reference above.
The bug can be reproduced by `bin/magento setup:upgrade`.

**Comment by piotrekkaminski** [comment]
@maghamed can you provide ticket ID?

**Comment by tkacheva** [comment]
Fix is in merging process. Expect it soon

**Comment by vkholoshenko** [comment]
Internal ticket: MAGETWO-43771

**Comment by vzabaznov** [comment]
Hi @dfediuk, issue was fixed, please check it, and if you think that not, feel free to write here or to open new one
