### ISSUE TITLE
After resaving a configurable product the system makes it simple (not configurable)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2017]
Related to: https://github.com/magento/magento2/issues/2015
See the screenshots from there.
The system wrongly requires to set configurable attributes to configurable product.
After setting them and saving the product becomes simple, not configurable.

**Comment by tanya-soroka** [comment]
@dfediuk we are using one template for few product types: configurable, downloadable, virtual and simple. So if you won't provide the correct infroamiton for the configurable ( like configuration option), system will identify this product as a simple.  

Could you please confirm that you have setup configuration list and after saving the product still become as a simple product?

**Comment by vkholoshenko** [comment]
Hi @dfediuk,  we haven't heard back from you and, thus, will proceed with closing this issue. In case you have any additional questions, please don't hesitate to reopen the issue (or create a new one).
