### ISSUE TITLE
Typographical error: «do not add grops without attributes»

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2018]
https://github.com/magento/magento2/blob/12955b1c7e43c560dc1060c136858531d403c682/app/code/Magento/Catalog/Block/Adminhtml/Category/Tabs.php#L146

**Comment by NadiyaS** [comment]
Hi @dfediuk ,
thanks for notice. Internal issue was created MAGETWO-43768

**Comment by vzabaznov** [comment]
Hi @dfediuk, issue is irrelevant in context of new implementation, please check it, and if you think that not, feel free to write here or to open new one
