### ISSUE TITLE
«Argument 1 passed to Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\ChildTab::setTab() must implement interface Magento\Backend\Block\Widget\Tab\TabInterface, instance of Magento\Framework\DataObject given» while opening a simple product in admin

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2019]
The bug description: https://mage2.pro/t/110
Related to https://github.com/magento/magento2/issues/1646
My fix is the same.

**Comment by yaronish** [comment]
@dfediuk please confirm this issue still exists after b9f2ad7
Thank you.

**Comment by ishakhsuvarov** [comment]
Closing the ticket for now. Please reopen if the issue persists.
