### ISSUE TITLE
Attribute group code generation algorithm is incorrect because it returns null for an attribute group with non-Latin name

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2020]
A detailed description: https://mage2.pro/t/112

**Comment by dfediuk** [comment]
This leads to the bugs:
- https://github.com/magento/magento2/issues/1646
- https://github.com/magento/magento2/issues/2019

**Comment by NadiyaS** [comment]
Thanks, @dfediuk 
internal issue was created MAGETWO-43717

**Comment by ilagno89** [comment]
@dfediuk,  internal ticket is fixed and already available in develop branch. Please, check the fix, if something doesn't work for you, feel free to reopen this issue.
