### ISSUE TITLE
Admin product tab generation is incorrect for configurable, downloadable, bundle and grouped products because it depends on «product-details» tab which could be absent

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2021]
https://mage2.pro/t/113

**Comment by dfediuk** [comment]
Related bugs: https://github.com/magento/magento2/issues/2015, https://github.com/magento/magento2/issues/2017

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44059

**Comment by vzabaznov** [comment]
Hi, issue is irrelevant in context of new implementation, please check it, and if you think that not, feel free to write here or to open new one
