### ISSUE TITLE
Why does the default product quantity on the frontend is 0, not 1?

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2022]
![magento2-06](https://cloud.githubusercontent.com/assets/83204/10269589/05b099ce-6ae5-11e5-98c8-a2db82899521.png)

**Comment by nevvermind** [comment]
I bet you have more than one website setup: https://github.com/magento/magento2/blob/b67a5e02e520683ddd0083bf388e87186501a65b/app/code/Magento/CatalogInventory/Model/StockRegistry.php#L88 :)

**Comment by dfediuk** [comment]
Yes. But what is the sense to suggest a customer to order 0 items by default? Why is not 1?

**Comment by nevvermind** [comment]
I wasn't suggesting that it's correct behaviour. It's just that the functionality doesn't seem to be there yet, is all.

**Comment by tkacheva** [comment]
@dfediuk what product type have you configured?

**Comment by dfediuk** [comment]
Configurable. All the simple variants are in stock.
And I saw the same problem with virtual products too.

**Comment by antboiko** [comment]
@mage2pro 

Hi Dmitry, sorry for the delayed response.

The fix is already in develop branch and will be available in 2.1 release.

I'm closing the issue. Feel free to reopen it if needed.

Thanks,
Anton.

**Comment by IlyaSkriblovsky** [comment]
@antboiko ~~Hi, Anton. I have Magento 2.1.2 installed and default quantity is zero for me too. Is it something wrong with my configuration?~~

Never mind, I've messed up with inventory settings
