### ISSUE TITLE
Inconsistency in the config section ACL resource handling: a non-existent ACL resource is always allowed but access to a config section without a resource is always forbidden

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2024]
https://mage2.pro/t/114

**Comment by antonkril** [comment]
Whitelisting approach was used to make sure developers do not forget to add resource to allow store admin manage access to section. But I agree that there are inconsistencies:
- resource attribute might be obligatory or
- non-existing section should be forbidden by default

**Comment by andimov** [comment]
@mage2pro
Could you please add the description of steps, actual result and expected result to this ticket?
It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Inconsistency-in-the-config-section-ACL-resource-handling-a-non/idi-p/45424).
