### ISSUE TITLE
Varnish purge does not work with bin/magento CLI tool.

### ISSUE THREAD

**Issue by andrewkett** [magento/magento2#2025]
We have got varnish set up and running and using the admin UI are able to clear varnish by doing a full cache flush or by refreshing the full page cache. When doing this I can see the PURGE request coming through the varnish server, everything works as expected. However when using the CLI to purge, e.g magento cache:flush —all or magento cache:flush full_page, I cannot see a PURGE request happening. 

The code that makes this request is in an observer in Magento_CacheInvalidate. Perhaps the the CLI is firing a different event which the observer isn't listening for?

**Comment by dougkm** [comment]
Created internal issue - MAGETWO-44439

**Comment by erikhansen** [comment]
@andrewkett This may be related to this PR: #3339

**Comment by vzabaznov** [comment]
Hi @andrewkett  bug was fixed and delivered to latest version.
