### ISSUE TITLE
Step 2: Add a Database - "Next" doesn't work.

### ISSUE THREAD

**Issue by iio7** [magento/magento2#2027]
Testing Magento 2 installation.

During "Step 2: Add a Database" the "Next" button doesn't work. It doesn't matter what data is entered into the different fields, right or wrong, pressing the "Next" button doesn't do anything. No error messages, no confirmation, nothing.

I can use the "Back" button, but get stranded on "Step 2: Add a Database", cannot continue.

**Comment by daim2k5** [comment]
Can you give more informations? "develop" branch from today? Browser?

**Comment by mazhalai** [comment]
@iio7 are there any javascript errors on your browser?

**Comment by iio7** [comment]
Development branch from the day I filed the report. Problem exists in both Firefox 41.0.1 and Chrome 45.

05.10.2015, 13:29, "Damian Luszczymak" <notifications@github.com>:

**Comment by iio7** [comment]
No. I get no errors at all.

05.10.2015, 17:56, "mazhalai" <notifications@github.com>:

**Comment by mazhalai** [comment]
@iio7 can you please clean your browser cache as well as `var` and try again?

**Comment by mazhalai** [comment]
@iio7 can you please clean your browser cache as well as `var` and try again?

**Comment by celeonardo** [comment]
i have a same problem, how to fix it?

**Comment by celeonardo** [comment]
when click "NExt" in 2step to create BD, only stay stoping

**Comment by Hugo22O** [comment]
[Removed]

**Comment by rajeev1405** [comment]
Installing magento 2 on localhost, I had the same issue, next button was not working on step 2 Add a database. In step 2 in field Database Server Host it was written localhost by default I deleted it and wrote localhost again and it worked. Sounds silly but this what happened.

**Comment by unaipuelles** [comment]
I have the same problem, I can't fix it. I have made what @mazhalai said but nothing happened. Thanks!

**Comment by nogoodskam** [comment]
I Have the same problem, have anyone fixed it?

**Comment by nogoodskam** [comment]
> 
> 
> Testing Magento 2 installation.
> 
> During "Step 2: Add a Database" the "Next" button doesn't work. It doesn't matter what data is entered into the different fields, right or wrong, pressing the "Next" button doesn't do anything. No error messages, no confirmation, nothing.
> 
> I can use the "Back" button, but get stranded on "Step 2: Add a Database", cannot continue.

Have you find the solution?

**Comment by AizSedaj** [comment]
Check if you mysql port is 3306, if you changed it, this can be the problem.

**Comment by Normalyk** [comment]
> Check if you mysql port is 3306, if you changed it, this can be the problem.

Thanks. It was the problem. You are a good man.
