### ISSUE TITLE
not loaded CSS

### ISSUE THREAD

**Issue by oucart** [magento/magento2#2030]
![qq 20151006074658](https://cloud.githubusercontent.com/assets/4326820/10296814/ed19d09a-6bfe-11e5-9055-cf69a159ae62.png)

Successful installation,
But not loaded CSS  ？

**Comment by mazhalai** [comment]
@pengting are you using apache? do you have `mod_rewrite` turned on? Also, what [mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) are you operating in? If you are in `production` mode you need to run `bin/magento setup:static-content:deploy` in the CLI

**Comment by pengting** [comment]
use nginx 

run bin/magento setup:static-content:deploy  

Successful

Displayed a picture
But not loaded CSS

**Comment by eug123** [comment]
Hi,
Seems you pub/static folder is not available - logo image is absent too, please check folder content and permissions.

**Comment by royduin** [comment]
Ran `bin/magento setup:static-content:deploy` with your selected language code? For example: `bin/magento setup:static-content:deploy nl_NL`

**Comment by mazhalai** [comment]
@pengting for nginx, please check this sample configuration as [here](https://github.com/magento/magento2/blob/develop/nginx.conf.sample). Also, you did not specify which mode Magento2 is running on.

**Comment by xcomSteveJohnson** [comment]
Also, make sure the Base URL you specified is correct.

**Comment by patruvlad** [comment]
@pengting do as @royduin said, check the nginx settings as @mazhalai said and if after this you still have problems set corect permissions for the magento directory

**Comment by pengting** [comment]
my configuration
user www www;
worker_processes auto;

error_log /home/wwwlogs/error_nginx.log crit;
pid /var/run/nginx.pid;
worker_rlimit_nofile 51200;

events {
    use epoll;
    worker_connections 51200;
    }

http {
    include mime.types;
    default_type application/octet-stream;
    server_names_hash_bucket_size 128;
    client_header_buffer_size 32k;
    large_client_header_buffers 4 32k;
    client_max_body_size 50m;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 120;
    server_tokens off;
    tcp_nodelay on;

    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 128k;

    #Gzip Compression
client_max_body_size 50m;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 120;
    server_tokens off;
    tcp_nodelay on;

    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 128k;

    #Gzip Compression
    gzip on;
    gzip_buffers 16 8k;
    gzip_comp_level 6;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;
    gzip_types
        text/xml application/xml application/atom+xml application/rss+xml application/xhtml+xml image/svg+xml
        text/javascript application/javascript application/x-javascript
        text/x-json application/json application/x-web-app-manifest+json
        text/css text/plain text/x-component
        font/opentype application/x-font-ttf application/vnd.ms-fontobject
        image/x-icon;
    gzip_disable  "msie6";

    #If you have a lot of static files to serve through Nginx then caching of the files' metadata (not the actual files' contents) can save some latency.
    open_file_cache max=1000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

################### demo(you can delete) ############################
    server {
    listen 80;
    server_name _;
    access_log /home/wwwlogs/access_nginx.log combined;
    root /home/wwwroot/magento2;
    index index.html index.php;
    location / {
        try_files $uri @apache;
        }
    location @apache {
        proxy_pass http://127.0.0.1:88;
                      include proxy.conf;
        }
    location ~ .*\.(php|php5)?$  {
        proxy_pass http://127.0.0.1:88;
        include proxy.conf;
        }
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
        expires 30d;
        access_log off;
        }
    location ~ .*\.(js|css)?$ {
        expires 7d;
        access_log off;
        }
    }

##########################vhost#####################################
    include vhost/*.conf;         



Apache:


<VirtualHost *:88>
    ServerAdmin admin@linuxeye.com
    DocumentRoot "/home/wwwroot/magento2"
    ServerName 127.0.0.1
    ErrorLog "/home/wwwlogs/error_apache.log"
    CustomLog "/home/wwwlogs/access_apache.log" common
<Directory "/home/wwwroot/magento2">
    SetOutputFilter DEFLATE
    Options FollowSymLinks
    Require all granted
    AllowOverride All
    Order allow,deny
    Allow from all
    DirectoryIndex index.html index.php
</Directory>
</VirtualHost>
~

**Comment by pengting** [comment]
pub/static   777

**Comment by piotrekkaminski** [comment]
@mazhalai any ideas?

**Comment by mazhalai** [comment]
@pengting do you still have the same issue? Is there any error in nginx logs?

**Comment by NadiyaS** [comment]
Problem is not reproducible.  As there are no new updates from reporter, issue will be closed.
