### ISSUE TITLE
Error when install magento2 1.0.0 beta ?

### ISSUE THREAD

**Issue by xanka** [magento/magento2#2031]
Console log show  error
Module 'Magento_Customer':
Installing data..
[ERROR] exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'' in C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `cu...', Array) #5 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `cu...', Array) #6 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(488): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `cu...', Array) #7 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `cu...', Array) #8 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(1761): Zend_Db_Adapter_Abstract->insert('customer_group', Array) #9 C:\localhost\magento2-1.0.0-beta\app\code\Magento\Customer\Setup\InstallData.php(51): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('customer_group', Array) #10 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Model\Installer.php(761): Magento\Customer\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #11 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Model\Installer.php(709): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #12 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #13 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Model\Installer.php(298): call_user_func_array(Array, Array) #14 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Controller\Install.php(87): Magento\Setup\Model\Installer->install(Array) #15 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #17 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #18 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #20 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #22 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #23 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #25 C:\localhost\magento2-1.0.0-beta\setup\index.php(31): Zend\Mvc\Application->run() #26 {main} Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY', query was: INSERT INTO `customer_group` (`customer_group_id`, `customer_group_code`, `tax_class_id`) VALUES (?, ?, ?)' in C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:235 Stack trace: #0 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #1 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #2 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #3 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `cu...', Array) #4 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(433): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `cu...', Array) #5 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(488): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `cu...', Array) #6 C:\localhost\magento2-1.0.0-beta\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `cu...', Array) #7 C:\localhost\magento2-1.0.0-beta\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(1761): Zend_Db_Adapter_Abstract->insert('customer_group', Array) #8 C:\localhost\magento2-1.0.0-beta\app\code\Magento\Customer\Setup\InstallData.php(51): Magento\Framework\DB\Adapter\Pdo\Mysql->insertForce('customer_group', Array) #9 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Model\Installer.php(761): Magento\Customer\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext)) #10 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Model\Installer.php(709): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #11 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #12 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Model\Installer.php(298): call_user_func_array(Array, Array) #13 C:\localhost\magento2-1.0.0-beta\setup\src\Magento\Setup\Controller\Install.php(87): Magento\Setup\Model\Installer->install(Array) #14 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #16 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #17 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #18 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #21 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #22 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-eventmanager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #23 C:\localhost\magento2-1.0.0-beta\vendor\zendframework\zend-mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 C:\localhost\magento2-1.0.0-beta\setup\index.php(31): Zend\Mvc\Application->run() #25 {main}

**Comment by NadiyaS** [comment]
Hi @xanka,
looks like you try to install Magento on not empty database.
After pulling the resent Magento version you do not need to reinstall it. You may run `bin/magento setup:upgrade`.
Or if you want to reinstall it anyway you need to run `bin/magento setup:uninstall` to be sure that all data is uninstalled and then install Magento in the way you prefer

**Comment by xanka** [comment]
Yes I thing so. I have tried but failed.
I don't know the installation process is stopped repeatedly. It is related to mysql in my computer file import supper slow computer.

**Comment by mazhalai** [comment]
@xanka thank you for reporting this issue. Did @NadiyaS's  suggestions also give you errors? What about `uninstall`?

**Comment by piotrekkaminski** [comment]
Closing as no response.
