### ISSUE TITLE
Wrong class name in a comment: «\Magento\Customer\Block\Adminhtml\Edit\Tab\View\Status\PersonalInfo»

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2032]
https://github.com/magento/magento2/blob/1270ddb2ba5f5a3159c621047fc7a4af0825d219/app/code/Magento/Customer/view/adminhtml/templates/tab/view/personal_info.phtml#L10

Need to be changed to the right class name: `\Magento\Customer\Block\Adminhtml\Edit\Tab\View\PersonalInfo`

**Comment by NadiyaS** [comment]
Thanks @dfediuk,
internal issue was created MAGETWO-43710

**Comment by slavvka** [comment]
@dfediuk, Internal ticket MAGETWO-43710 is closed and delivered to mainline. Please, see efb29c8. Please, let us know if you still have an issue.
