### ISSUE TITLE
Soap API Fails once DI is compiled

### ISSUE THREAD

**Issue by davefarthing** [magento/magento2#2033]
Hi,

I can call and use the Soap API fine until I run `bin/magento setup:di:compile` then all Soap Interface stop working.

After the DI is compiled as Soap Interfaces return with 
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>SOAP-ENV:Server</faultcode>
         <faultstring>SoapServer::SoapServer(): Invalid parameters</faultstring>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Tracing through it seems that DI does not see the arguments required by the SoapServer construct. There are no di preferences/arguments that I could find for the SoapSever class and presumably reflection fails to spot the construct arguments. I am running under php 5.5.29.

If I remove the var/di folder everything works as expected. I am working against master currently so apologies if this is already taken care of in develop. I checked the issues, but couldn't see any matches.

Here is an example of the request:

WSDL
```
http://www.magento2.local/index.php/soap/default?services=catalogProductRepositoryV1&wsdl=1
```

BODY
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://www.magento2.m2/soap/default?services=catalogProductRepositoryV1">
   <soap:Header/>
   <soap:Body>
      <def:catalogProductRepositoryV1GetRequest>
         <sku>24-MB01</sku>
      </def:catalogProductRepositoryV1GetRequest>
   </soap:Body>
</soap:Envelope>
```

**Comment by piotrekkaminski** [comment]
@choukalos FYI

internal issue MAGETWO-44060

**Comment by cspruiell** [comment]
@davefarthing this issue does not exist in the develop branch.

**Comment by sydekumf** [comment]
I have the same issue on master branch. As M2 is already released when do you want to fix this?

**Comment by cspruiell** [comment]
This has been fixed in our latest develop branch and will be included in our next release.

**Comment by svdev** [comment]
This issue is still happening in Magento 2.0.12

**Comment by ngoctruong1610** [comment]
I met that issue on my project [Magento 2.0.10], any update please ?
