### ISSUE TITLE
Exclude pages, products or categories from the sitemap generation

### ISSUE THREAD

**Issue by royduin** [magento/magento2#2035]
It would be nice if there where options in the backend to exclude pages, products or categories from the sitemap generation.

**Comment by tanya-soroka** [comment]
@royduin would you like to share the business use-case in the this request? 
Thank you in advance.

**Comment by royduin** [comment]
For example I don't want the contact and cookie information page indexed by any search engines. I can disallow them by adding custom XML to set a robots meta tag*, but why should they be present in the `sitemap.xml` if I don't want them indexed?

* Now I'm thinking about this any further, it would be nice too to have a dropdown on every page, product and category with the possibility to change the robots meta tag, like this: http://inchoo.net/magento/per-product-meta-robots-tag-control-in-magento/

**Comment by pboisvert** [comment]
@elenleonova Elena--domain owner page shows you for sitemap so assigning to you

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Exclude-pages-products-or-categories-from-the-sitemap-generation/idi-p/44884).

**Comment by rav-redchamps** [comment]
@royduin There is an extension available for the purpose 

https://redchamps.com/xml-sitemap-exclude-url-magento-2-extension.html

Give it a try. It should solve the purpose.
