### ISSUE TITLE
Google Tag Manager support?

### ISSUE THREAD

**Issue by royduin** [magento/magento2#2036]
Currently I only find Google Analytics in the backend.

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by piotrekkaminski** [comment]
Google Tag Manager is available in Enterprise Edition. The version published on github is Community Edition.

**Comment by craigcarnell** [comment]
@piotrekkaminski Who would I speak to about getting the Magento 2 Ent Beta? We are a customer

**Comment by royduin** [comment]
Support for GTM is recently added in Magento CE 1.9.x.x and not in Magento 2?
