### ISSUE TITLE
Routers over satisfy the interface RequestInterface

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#2038]
As digging thru the code, I've seen usages of methods which are not implemented in the interface of `\Magento\Framework\App\RequestInterface`. In other programming languages that would not compile/execute ...

https://github.com/magento/magento2/blob/develop/app%2Fcode%2FMagento%2FCms%2FController%2FRouter.php#L94 `getPathInfo()` not implemented.

https://github.com/magento/magento2/blob/develop/app%2Fcode%2FMagento%2FCms%2FController%2FRouter.php#L105 `setDispatched()` not implemented.

https://github.com/magento/magento2/blob/develop/app%2Fcode%2FMagento%2FCms%2FController%2FRouter.php#L121 `setAlias()` not implemented.

https://github.com/magento/magento2/blob/develop/app%2Fcode%2FMagento%2FUrlRewrite%2FController%2FRouter.php#L89 `setPathInfo()` not implemented.

Can that be fixed to be more strict?

Thanks guys!

**Comment by SchumacherFM** [comment]
Same goes with the [`ResponseInterface`](https://github.com/magento/magento2/blob/develop/lib%2Finternal%2FMagento%2FFramework%2FApp%2FResponseInterface.php#L10)

https://github.com/magento/magento2/blob/develop/lib%2Finternal%2FMagento%2FFramework%2FController%2FResult%2FJson.php#L67 `representJson()` not implemented

https://github.com/magento/magento2/blob/develop/lib%2Finternal%2FMagento%2FFramework%2FController%2FResult%2FRaw.php#L38 `setBody()` not implemented

**Comment by antonkril** [comment]
General idea is to abstract application from HTTP request, so application can serve different requests. Also setDispatched/isDispatched is legacy method of request processing flow control (plugins can be used for this). Whole code is not refactored yet (not high priority), but not having those methods on interface is a way to tell developers not to use implementation specific methods.

Extending interface in implementation is allowed, it's just clients that work by parent interface should not use methods of child interface (or implementation).
