### ISSUE TITLE
Stock issues

### ISSUE THREAD

**Issue by wkaminsk** [magento/magento2#2040]
Hi,
I started playing with Magento2 and have some issues with it.
I've created simple product, named test product, qty = 1000, I've gone to its product page and... product is *out of stock*. Why is that ?

Next thing, the same product, I've gone to Advanced Inventory. Set "Manage Stock" to *No*, save and still see  Manage Stock to Yes with all options.

Regards.

**Comment by tanya-soroka** [comment]
Hello @wojkam.
Could you please check the stock value for the first issue. 
Second issue has been confirm and internal MAGETWO-43780 ticket has been created.

**Comment by wojkam** [comment]
Hi,
Attached screenshots for virtual product (same issue).
![screen shot 2015-10-08 at 18 51 14](https://cloud.githubusercontent.com/assets/7458051/10373418/97e27046-6ded-11e5-9db3-44b2b1357572.png)

![screen shot 2015-10-08 at 18 49 38](https://cloud.githubusercontent.com/assets/7458051/10373403/7b5dae0e-6ded-11e5-89d7-d0a21181c876.png)
![screen shot 2015-10-08 at 18 49 12](https://cloud.githubusercontent.com/assets/7458051/10373404/7b5f1f32-6ded-11e5-9133-f8f60f47fec8.png)

**Comment by mslabko** [comment]
Issue has been fixed.
