### ISSUE TITLE
Braintree MyAccount pages are not resposive

### ISSUE THREAD

**Issue by lijithmg** [magento/magento2#2041]
My Account >> "My Credit Card" links are not responsive.

**Comment by alena-marchenko** [comment]
Hi,
Please provide more detailed description on this issue

**Comment by lijithmg** [comment]
Login to your account as customer after enabling the Braintree Void method. You will see My Credit Card link on the My Accounts section. 

Navigate to the My Credit Card page. Add/List pages here are not responsive.

**Comment by alena-marchenko** [comment]
Please specify commit on which you are reproducing the issue
