### ISSUE TITLE
Problem running setup:upgrade

### ISSUE THREAD

**Issue by whizkid79** [magento/magento2#2042]
I experienced the same issue descriped here and the solution worked for me.
https://mage2.pro/t/topic/102

using branch develop, on commit 86d5abe5adf8f452e52e5876c1ba2008aa0e6e30

**Comment by NadiyaS** [comment]
Hi @whizkid79 ,
internal issue was created MAGETWO-43755.
Problem was already described in issue [2007] (https://github.com/magento/magento2/issues/2007)

**Comment by vladimir-k** [comment]
Hi, @whizkid79. The issue has already been fixed and delivered to develop branch (0f351d6a80cd5c8c981e517dd849dd7ce06791d4). Thanks for reporting!
