### ISSUE TITLE
Segfaults with PHP 7.0 RC4

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2044]
PHP will segfault on Ubuntu 14.04, no output in logs other than the segfault itself :)

**Comment by kandy** [comment]
May be better to post bugs to php bug tracking system?

**Comment by mazhalai** [comment]
@craigcarnell What are you trying to do, installation? Have you checked `max_execution_time` setting?

**Comment by craigcarnell** [comment]
@mazhalai Readiness check

**Comment by craigcarnell** [comment]
@mazhalai I think this most likely a PHP bug so will close for now. They are not likely to look at it however, as Magento 2 is not exactly a small bit of code to reproduce the issue

**Comment by kandy** [comment]
link to php bug https://bugs.php.net/bug.php?id=68781

**Comment by craigcarnell** [comment]
@kandy  Thanks
