### ISSUE TITLE
Warning: Expiry date cannot have a year greater than

### ISSUE THREAD

**Issue by motorlesha** [magento/magento2#2045]
I tried to set session time more that 9999

Warning: Expiry date cannot have a year greater than 9999 in /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php on line 124
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Expiry date can...', '/var/www/source...', 124, Array)
#1 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php(124): setcookie('admin', '8n1gt2hhajjtqu5...', 1001444221846, '/admin', 'magento2.motorn...', false, true)
#2 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php(96): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie('admin', '8n1gt2hhajjtqu5...', Array)
#3 /var/www/sources/motorny/magento2/app/code/Magento/Backend/Model/Auth/Session.php(192): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie('admin', '8n1gt2hhajjtqu5...', Object(Magento\Framework\Stdlib\Cookie\PublicCookieMetadata))
#4 /var/www/sources/motorny/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(119): Magento\Backend\Model\Auth\Session->prolong()
#5 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#6 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#7 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Configg\...','dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'designLoader')
#8 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#9 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#11 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Configg\...','dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'adminMassaction...')
#12 /var/www/sources/motorny/magento2/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#13 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#15 /var/www/sources/motorny/magento2/var/generation/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php(40): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#16 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/App/FrontController.php(45): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#19 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#20 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewwo..', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#21 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#24 /var/www/sources/motorny/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/sources/motorny/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#27 /var/www/sources/motorny/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by piotrekkaminski** [comment]
internal id MAGETWO-44437

**Comment by sidolov** [comment]
Hi @motorlesha, could you provide more information about this issue? (steps to reproduce, git branch, environment setting: php version, etc). I can't reproduce this issue on current develop branch (commit 0be91a56d050791ac0b67a47185d79df31e79329)

**Comment by brideo** [comment]
Hi @sidolov,

I just came across this issue too, steps to reproduce:

Environment:
- Make sure PHP Warnings are one
- Developer mode on
- My PHP version is: 5.6.17

Steps to reproduce:
- `update core_config_data set value = 9999999 where path = 'admin/security/session_lifetime';`

You can set the value in the admin by going to:
- Configuration > Advanced > Admin > Security > Session Lifetime (Seconds).

Validation needs to be added around this in the admin to prevent store owners being able to cause warnings and errors on their websites, I'm happy to implement if given the thumbs up.

PS I haven't tested this on develop so it may of been fixed.

**Comment by magento-engcom-team** [comment]
@motorlesha, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
