### ISSUE TITLE
Bug: the customer name showed twice in the top right corner

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2047]
What is the sense to show the customer name twice?
The first block is welcome message. The second block is the customer menu.
Please note that the welcome message for authenticated customers can not be changed or disabled in admin panel.
 
![magento2-01](https://cloud.githubusercontent.com/assets/83204/10357058/8f2011fa-6d86-11e5-8198-dfa7e80c9119.png)

**Comment by zanilee** [comment]
Thank you for reporting the issue.
Internal ticket: MAGETWO-42900

**Comment by tkacheva** [comment]
Issue is created MAGETWO-32511

**Comment by tkacheva** [comment]
@dfediuk That totally makes sense. thanks for the feedback

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Bug-the-customer-name-showed-twice-in-the-top-right-corner/idi-p/46907).
