### ISSUE TITLE
Bug: the mouse cursor has wrong type ("text") while it is above a customer's name in the right top corner (the type need to be "pointer")

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2048]
![magento2-02](https://cloud.githubusercontent.com/assets/83204/10357890/5e374c84-6d90-11e5-9ee7-534d51da34cc.png)

![magento2-05](https://cloud.githubusercontent.com/assets/83204/10357894/63cf28c4-6d90-11e5-8d80-3e5e74a2a680.png)

**Comment by zanilee** [comment]
Thank you for reporting the issue.
Internal ticket: MAGETWO-42900

**Comment by MomotenkoNatalia** [comment]
@dfediuk  Internal ticket MAGETWO-42900 is closed and delivered to mainline. Please, let us know if you still have an issue.

**Comment by davidalger** [comment]
As this issue has been resolved and the fix pushed to develop, I am closing this issue. Please feel free to reopen should you believe the issue has not been properly addressed.
