### ISSUE TITLE
dissapointments

### ISSUE THREAD

**Issue by Stuperfied** [magento/magento2#2049]
I apologize in advance as I could not find any other way of guaranteeing this would actually reach the developers.  

2 big disappointments. The following (what should be default features) are missing.

Price: POA  - common and very useful shopping cart feature
Sometimes its just easier if the customer calls but you don't want to put zero price. Price should however appear as zero in schema.org as google only accepts integers.

Orders > Action > Complete - Prevents 100's of orders lingering after manual shipping.
Many store owners find themselves with failed paypal IPN's or in the circumstance where they need or prefer to just call the courier on the phone. In that case they end up with orders litterally STUCK in their magento store in limbo for eternity.

Now there are conveniences, which can be added by 3rd party extensions but I believe these are two of the basics. I firmly believe they should be core features and not require a 3rd party extension.

**Comment by choukalos** [comment]
No worries.  We're pretty active on Twitter (I'm Blue_Bovine) along with pretty easy with handing out email addresses.  

Since this is Github will you send in a pull request (PR) for these improvements?

**Comment by Stuperfied** [comment]
Thank you for the quick reply. I'm new to GitHub and so still learning what a pull request is. I think you are asking me if I can write the code and request a merge.

if so, I can but will take a long time as i'm still playing catch up from magento 1.9.0.1. I am happy to do this but if anyone gets to it before me, I wont object. ;)

**Comment by Stuperfied** [comment]
My first thought for "POA" is to add it as a separate form field as all pricing seems strictly bound to Integer. This would also allow for additional options to be added such as "Coming Soon". Immediately thats a new database entry with sql to do the setup on install. Would also need a ..... Ok, is there a discussion forum somewhere?

**Comment by choukalos** [comment]
Our forums are here - https://community.magento.com

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
