### ISSUE TITLE
Cannot add product in backend

### ISSUE THREAD

**Issue by tapantechno2007** [magento/magento2#2050]
I am trying to add a product through backend interface but the process never completes, the spinning image shows up and never goes and the product is not added at all.

I have a fresh version of master branch and have no customized code inside my setup, neither I have made any changes to any configuration except that I have enabled developer mode through htaccess.

**Comment by orlangur** [comment]
Please enable `display_errors` and look into server response in `Network` tab of developer tool of your choice. Most likely there is some fatal error instead of proper JSON response.

**Comment by tanya-soroka** [comment]
@tapantechno2007 did you get any error ( see the previous comment form Vlad)? Could you please share with us it?
