### ISSUE TITLE
Data Migration tool for EE 1.14.2.2

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2051]
Hi,

I need this! Where is it please? :)

**Comment by craigcarnell** [comment]
If not at least some way of exporting products, attributes and categories from EE into Magento 2

**Comment by choukalos** [comment]
Hi @asemenenko where's the EE migration tool - isn't it in the partner portal?  The CE tool is in our public Github:  https://github.com/magento/data-migration-tool-ce

**Comment by xcomSteveJohnson** [comment]
The Magento 2 data migration tool works for both CE and EE: http://devdocs.magento.com/guides/v2.0/migration/migration-overview-supported.html

**Comment by craigcarnell** [comment]
@xcomSteveJohnson In that case can it be updated to support EE 1.14.2.1?

**Comment by gordonknoppe** [comment]
There is an internal ticket to complete support for the latest edition of EE and it is in code review.  @craigcarnell it should be out shortly

**Comment by craigcarnell** [comment]
@gordonknoppe Define shortly!!!

**Comment by craigcarnell** [comment]
@choukalos @gordonknoppe Any update on this?

**Comment by craigcarnell** [comment]
@ilol Still waiting!!!

**Comment by ilol** [comment]
Hi @craigcarnell, sorry for delay )
We are almost ready to release versions for 1.14.2.1 and 1.9.2.1 (see https://github.com/magento/data-migration-tool-ce/issues/3). I am expecting middle of next week. Since 1.14.2.2 and 1.9.2.2 have been released recently we are trying to update MT ASAP with these latest versions. But most probably we will release them some time later than 1.14.2.1 and 1.9.2.1.

**Comment by craigcarnell** [comment]
@ilol Hi, Still not released. Any updates? It's a shame we have to patch/upgrade m1 and then are stuck trying m2 because we can't get the data migration tool relevant to the version!

**Comment by sarjangautam** [comment]
Hi , 

I am trying to test Data Migration functionality for EE 1.14.2.2 to M2. Please let me know if it is available now.

Regards,
Sarjan

**Comment by ilol** [comment]
Hi @sarjangautam, this is available for EE license owners. The EE Migration Tool code is stored in the hidden repository. Request the access to your Magento representative.
