### ISSUE TITLE
Class Magento\Tax\Model\Calculation\Proxy does not exist

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2052]
Ran the re-index process as requested.. then after that the front end is broken.

php bin/magento indexer:reindex
```
Customer Grid index has been rebuilt successfully in 00:00:01
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:01
```

In the front end:
```
Class Magento\Tax\Model\Calculation\Proxy does not exist
#0 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Tax\\Mod...')
#1 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Tax\\Mod...')
#2 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Tax\\Mod...')
#3 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/PluginList/PluginList.php(233): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Tax\\Mod...')
#4 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(139): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Cms\\Con...', 'tax-app-action-...')
#5 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#6 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/FrontController.php(54): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#9 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#10 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#11 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#14 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#15 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#16 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#18 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#19 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Store/Model/Plugin/StoreCookie.php(78): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#20 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#22 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#23 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#24 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#26 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#27 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#30 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#33 /Users/ccarnell/Sites/vax-uk2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#34 {main}
```

**Comment by craigcarnell** [comment]
Worked after clearing the cache

**Comment by smatric** [comment]
It's very likely related to insufficient write permission under `var` directory.

**Comment by Microguru** [comment]
I have run setup-upgrade and given full permission and also deleted var but it is showing error


1 exception(s):
Exception #0 (RuntimeException): Class ClassyLlama\AvaTax\Framework\Interaction\TaxCalculation\Proxy does not exist in [ClassyLlama\AvaTax\Model\Tax\Sales\Total\Quote\Tax\Interceptor]

Exception #0 (RuntimeException): Class ClassyLlama\AvaTax\Framework\Interaction\TaxCalculation\Proxy does not exist in [ClassyLlama\AvaTax\Model\Tax\Sales\Total\Quote\Tax\Interceptor]
#0 /var/www/html/m2/master/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('ClassyLlama\\Ava...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('ClassyLlama\\Ava...')
#2 [internal function]: spl_autoload_call('ClassyLlama\\Ava...')
#3 /var/www/html/m2/master/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('ClassyLlama\\Ava...')
#4 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('ClassyLlama\\Ava...')
#5 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('ClassyLlama\\Ava...')
#6 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('ClassyLlama\\Ava...', Array)
#7 /var/www/html/m2/master/vendor/magento/module-quote/Model/Quote/Address/TotalFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Tax\\Mod...', Array)
#8 /var/www/html/m2/master/vendor/magento/module-quote/Model/Quote/Address/Total/Collector.php(125): Magento\Quote\Model\Quote\Address\TotalFactory->create('Magento\\Tax\\Mod...')
#9 /var/www/html/m2/master/vendor/magento/module-sales/Model/Config/Ordered.php(114): Magento\Quote\Model\Quote\Address\Total\Collector->_initModelInstance('Magento\\Tax\\Mod...', 'tax', Array)
#10 /var/www/html/m2/master/vendor/magento/module-quote/Model/Quote/Address/Total/Collector.php(91): Magento\Sales\Model\Config\Ordered->_initModels()
#11 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Quote\Model\Quote\Address\Total\Collector->__construct(Object(Magento\Framework\App\Cache\Type\Config), Object(Magento\Framework\Logger\Monolog), Object(Magento\Sales\Model\Config), Object(Magento\Framework\App\Config), Object(Magento\Store\Model\StoreManager\Interceptor), Object(Magento\Quote\Model\Quote\Address\TotalFactory), NULL, NULL, NULL)
#12 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Quote\\M...', Array)
#13 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Quote\\M...')
#14 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Quote\\M...')
#15 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Quote\\M...', NULL, 'totalCollector', 'Magento\\Quote\\M...')
#16 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Quote\\M...', Array, Array)
#17 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Quote\\M...', Array, Array)
#18 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Quote\\M...')
#19 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Quote\\M...')
#20 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Quote\\M...', NULL, 'totalsCollector', 'Magento\\Quote\\M...')
#21 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Quote\\M...', Array, Array)
#22 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Quote\\M...', Array, Array)
#23 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Quote\\M...')
#24 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Quote\\M...')
#25 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Quote\\M...', NULL, 'address', 'Amasty\\Storeloc...')
#26 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Amasty\\Storeloc...', Array, Array)
#27 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Amasty\\Storeloc...', Array, Array)
#28 /var/www/html/m2/master/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Amasty\\Storeloc...', Array)
#29 /var/www/html/m2/master/vendor/magento/framework/Model/AbstractModel.php(508): Magento\Framework\ObjectManager\ObjectManager->create('Amasty\\Storeloc...')
#30 /var/www/html/m2/master/vendor/magento/framework/Model/AbstractModel.php(521): Magento\Framework\Model\AbstractModel->getResourceCollection()
#31 /var/www/html/m2/master/app/code/Amasty/Storelocator/Block/Location.php(360): Magento\Framework\Model\AbstractModel->getCollection()
#32 [internal function]: Amasty\Storelocator\Block\Location->getLocationCollection()
#33 /var/www/html/m2/master/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array)
#34 /var/www/html/m2/master/app/code/Amasty/Storelocator/view/frontend/templates/link.phtml(14): Magento\Framework\View\TemplateEngine\Php->__call('getLocationColl...', Array)
#35 /var/www/html/m2/master/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/m...')
#36 /var/www/html/m2/master/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Amasty\Storelocator\Block\Location), '/var/www/html/m...', Array)
#37 /var/www/html/m2/master/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/html/m...')
#38 /var/www/html/m2/master/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#39 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#40 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('amlocator.link')
#41 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('amlocator.link')
#42 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('amlocator.link')
#43 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('amlocator.link', false)
#44 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('amlocator.link', false)
#45 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('product.info.ma...', false)
#46 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.ma...')
#47 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.ma...')
#48 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.ma...', false)
#49 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.ma...', false)
#50 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content', false)
#51 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#52 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#53 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#54 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#55 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main', false)
#56 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#57 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#58 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', false)
#59 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('main', false)
#60 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns', false)
#61 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#62 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#63 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', false)
#64 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('columns', false)
#65 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#66 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#67 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#68 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', false)
#69 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false)
#70 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#71 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#72 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#73 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#74 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#75 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root', false)
#76 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#77 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#78 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#79 /var/www/html/m2/master/vendor/magento/framework/View/Layout.php(955): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#80 /var/www/html/m2/master/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#81 /var/www/html/m2/master/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#82 /var/www/html/m2/master/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#83 /var/www/html/m2/master/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#84 /var/www/html/m2/master/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#85 /var/www/html/m2/master/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#86 /var/www/html/m2/master/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#87 /var/www/html/m2/master/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#88 /var/www/html/m2/master/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#89 /var/www/html/m2/master/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#90 /var/www/html/m2/master/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#91 /var/www/html/m2/master/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#92 /var/www/html/m2/master/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#93 /var/www/html/m2/master/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#94 {main}
