### ISSUE TITLE
Video is not playable on product page

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2054]
I added a youtube video to the Magento  back end under product. On the product page all I see is an image with no video controls/playback

**Comment by craigcarnell** [comment]
Also on my server when I try to add a new product I get:

```
[Thu Oct  8 14:23:25 2015] [hphp] [24764:7f6234bff700:1:000001] [] \nFatal error: infinite recursion detected in /var/www/vhosts/magento2-capistrano/releases/20151008103838/app/code/Magento/ProductVideo/Block/Adminhtml/Product/Edit/NewVideo.php on line 218
```

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only.
Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by craigcarnell** [comment]
@davidalger This is a technical issue...

**Comment by davidalger** [comment]
@craigcarnell Sorry, I misunderstood that you were indicating a bug in Magento 2. :) Would you provide precise steps to reproduce and a screenshot of the faulty result?
