### ISSUE TITLE
Logging to a custom file and replacing a DI-injected array argument

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#2058]
I want to log to a new file other than the default ones, but still use the `\Psr\Log\LoggerInterface` type hint. 

For this, I created a new virtual type that wraps the original logger implementations, adding a new handler. My problem is that it's _adding_ the handler, instead of _replacing_ the originals. This happens because DI array arguments are merged.

Let's take for example the case of `Magento\Framework\Logger\Monolog`:
```xml
<type name="Magento\Framework\Logger\Monolog">
    <arguments>
        <argument name="name" xsi:type="string">main</argument>
        <argument name="handlers"  xsi:type="array">
            <item name="system" xsi:type="object">Magento\Framework\Logger\Handler\System</item>
            <item name="debug" xsi:type="object">Magento\Framework\Logger\Handler\Debug</item>
        </argument>
    </arguments>
</type>
```

Now I want to inject that logger implementation into a class of mine, say `ClassWithInjectedLogger`:
```php
<?php
class ClassWithInjectedLogger
{
    public function __construct(\Psr\Log\LoggerInterface $logger)
    {
        $logger->log('DEBUG', 'this should be logged into my own file');
    }
}
```
To be able to use the code above, I did some XML juggling:
```xml
<virtualType name="logger_with_custom_handler" type="Magento\Framework\Logger\Monolog">
    <arguments>
        <argument name="name" xsi:type="string">custom_log_channel</argument>
        <argument name="handlers"  xsi:type="array">
            <!-- I want ONLY this handler -->
            <item name="custom_handler" xsi:type="object">\MyModule\LoggerHandler</item>
        </argument>
    </arguments>
</virtualType>

<type name="\ClassWithInjectedLogger">
    <arguments>
        <argument name="logger" xsi:type="object">logger_with_custom_handler</argument>
    </arguments>
</type>
```
But because the arrays get merged, M2 basically reads this:
```xml
<argument name="handlers"  xsi:type="array">
    <item name="system" xsi:type="object">Magento\Framework\Logger\Handler\System</item>
    <item name="debug" xsi:type="object">Magento\Framework\Logger\Handler\Debug</item>
    <item name="custom_handler" xsi:type="object">\MyModule\LoggerHandler</item>
</argument>
```
So my class gets injected a logger with 3 handlers (instead of the expected 1) and my log info gets added in the `system.log` file (because of the way Monolog works).

----

The [documentation](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html) says this:

"When the configuration files for a given scope are merged, **array arguments with the same name are merged into a new array**. If a new configuration is loaded at a later time, either a more specific scope or through code, then any array definitions in the new configuration will completely replace the previously loaded config instead of being merged."  

Fair enough. 

----
My questions:
a) Regarding the documentation, what does `either a more specific scope or through code` mean exactly in the context of replacing the array arg instead of merging?
b) Is there simpler way to tell the DI system to _replace_ the array?
c) Since I talked about the logger, I'll ask anyway: is there a convenient way to have a logger log to a specific file _only_ and, more importantly, keeping the `\Psr\Log\LoggerInterface` type hint? I know I can directly set the type to `\Monolog\Logger` instead of `Magento\Framework\Logger\Monolog`, but I don't want to.

Thanks for reading.

**Comment by adragus-inviqa** [comment]
I managed to log to a different file by making my own logger *and* handler, logger which passes only the said handler to the parent.

Feels hackish though:
```xml
<type name="\Logger">
    <arguments>
        <argument name="handler" xsi:type="object">\FileHandler</argument>
    </arguments>
</type>

<type name="\ClassWithInjectedLogger">
    <arguments>
        <argument name="logger" xsi:type="object">\Logger</argument>
    </arguments>
</type>
```
```php
class Logger extends \Magento\Framework\Logger\Monolog
{
    public function __construct(\Monolog\Handler\HandlerInterface $handler)
    {
        parent::__construct(
            'custom_log_channel',
            [ $handler ] // only one handler
        );
    }
}

class FileHandler extends \Magento\Framework\Logger\Handler\System
{
    protected $fileName = '/var/log/custom_file.log';
    protected $loggerType = \Monolog\Logger::DEBUG;
}
```
My questions still stand though. :)

**Comment by kandy** [comment]
You can not replace an array using a DI (mainly because it conflicts changes) and your code is correct for your case.

**Comment by adragus-inviqa** [comment]
Alright. Thanks for letting me know. At least now I know what to do.
