### ISSUE TITLE
Rename admin sidebar Products to Catalog

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#2060]
![screen shot 2015-10-08 at 10 16 51 pm](https://cloud.githubusercontent.com/assets/437029/10384514/59658818-6e0a-11e5-936d-747d8354ca36.png)

I find it odd that the main sidebar item is named Products, with Catalog as a sub item. Shouldn't it be the other way around, with Catalog as the main sidebar item, and Products as a sub item?

Categories and Products are both sub items of Catalog, no?

**Comment by markoshust** [comment]
There is further evidence this should be changed once following the "Catalog" link. The URL is prefixed `catalog/product`, denoting that catalog is a higher-level item. There is also a big "Add Product" button on the Catalog page, leading to further confusion.

![screen shot 2015-10-08 at 10 19 46 pm](https://cloud.githubusercontent.com/assets/437029/10384563/f93c9516-6e0a-11e5-9dc5-51c911f2c608.png)

**Comment by tanya-soroka** [comment]
@markoshust Thank you for the report. Would you like to provide a pull request to change this?

**Comment by markoshust** [comment]
@daim2k5 has the hot hands :)

**Comment by markoshust** [comment]
still need to update the main page titles for each page

**Comment by markoshust** [comment]
PR https://github.com/magento/magento2/pull/2199

**Comment by markshust** [comment]
Is there a reason this hasn't been merged yet?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rename-admin-sidebar-Products-to-Catalog/idi-p/44877).
