### ISSUE TITLE
REST  Sales OrderStatusHistoryAdd orderCommentAdd doesn't send mail

### ISSUE THREAD

**Issue by bbraspenning** [magento/magento2#2063]
Using the REST Sales OrderStatusHistoryAdd orderCommentAdd webservice to change the order status, doesn't send an email even when "is_customer_notified" is set to true.

When logging in with admin console and using orders submit comment (same functionality), you do get an email "order update" with "your order 999999 has been {orderstate}.

How can you trigger the same email through the REST call?

**Comment by mbrinton01** [comment]
Logged as internal issue MAGETWO-44234

**Comment by cspruiell** [comment]
@bbraspenning This issue has been fixed in MAGETWO-43903.

**Comment by MomotenkoNatalia** [comment]
@bbraspenning  Internal ticket MAGETWO-43903 is closed and delivered to mainline. Please let us know if you still have an issue.
