### ISSUE TITLE
[Bug?] \Magento\Framework\App\Config::getValue() behavior is inconsistent with Magento 1.x Mage::getStoreConfig() method

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2064]
Magento 2 by default returns a config option value for the default scope while Magento 1.x by default returns  a config option value for the current store scope.
A detailed analysis here: https://mage2.pro/t/128
May be it is assumed but it looks like a bug and I do not understand the reason why the behavior was changed.

**Comment by adragus-inviqa** [comment]
Being different than M1 does not make it a bug, but I whole-heartedly agree that the default scope should not be `DEFAULT`, but `STORE`. 

The lowest scope should be used, as that's what usually people want. Besides, I think the `STORE` scope falls back to `DEFAULT` anyway, whereas `DEFAULT` doesn't.

**Comment by antonkril** [comment]
In Magento 2 Scoped config is part of Framework, and stores are part of ECommerce Application. ECommerce Application is built on top of framework, so Framework parts can not know about Application parts. 

`Magento\Framework\App\Config` is Framework level object that does not know about stores (and can not know about current store). So when you ask for config you should specify which scope you want. So it should not be compared to Mage::getStoreConfig.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
