### ISSUE TITLE
Cannot read contents from file pub/static/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.min.js

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2065]
When minification etc is all turned on in back end developer options

```
[2015-10-09 09:46:41] main.CRITICAL: exception 'Magento\Framework\Exception\FileSystemException' with message 'Cannot read contents from file "/var/www/vhosts/magento2-capistrano/releases/20151009084420/pub/static/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.min.js" Warning!No such file or directory' in /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/Filesystem/Driver/File.php:153
Stack trace:
#0 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/Filesystem/Directory/Read.php(207): Magento\Framework\Filesystem\Driver\File->fileGetContents()
#1 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/Source.php(241): Magento\Framework\Filesystem\Directory\Read->readFile()
#2 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/Source.php(127): Magento\Framework\View\Asset\Source->createChain()
#3 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/Source.php(102): Magento\Framework\View\Asset\Source->preProcess()
#4 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/File.php(163): Magento\Framework\View\Asset\Source->getContent()
#5 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/MergeStrategy/Direct.php(70): Magento\Framework\View\Asset\File->getContent()
#6 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/MergeStrategy/Direct.php(52): Magento\Framework\View\Asset\MergeStrategy\Direct->composeMergedContent()
#7 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/MergeStrategy/FileExists.php(44): Magento\Framework\View\Asset\MergeStrategy\Direct->merge()
#8 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/Merged.php(97): Magento\Framework\View\Asset\MergeStrategy\FileExists->merge()
#9 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Asset/Merged.php(157): Magento\Framework\View\Asset\Merged->initialize()
#10 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(356): Magento\Framework\View\Asset\Merged->rewind()
#11 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(247): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml()
#12 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(222): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup()
#13 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(99): Magento\Framework\View\Page\Config\Renderer->renderAssets()
#14 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Result/Page.php(233): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#15 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render()
#16 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult()
#17 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/App/Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#18 /var/www/vhosts/magento2-capistrano/releases/20151009084420/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#19 /var/www/vhosts/magento2-capistrano/releases/20151009084420/pub/index.php(37): Magento\Framework\App\Bootstrap->run()
#20 {main} [] []
```

**Comment by daim2k5** [comment]
@craigcarnell i can reproduce this error on my fresh installation. Do you get still the error?

**Comment by treestonemedia** [comment]
getting this error on a fresh install

**Comment by zolthan** [comment]
We are getting this error on the first frontend or backend request after deleting the static files.

```
[2016-08-01 12:55:49] main.CRITICAL: Magento\Framework\Exception\FileSystemException: Inhalte der Datei "/var/www/.../pub/static/adminhtml/Magento/backend/de_DE/mage/requirejs/mixins.js" "Warning!file_get_contents(/var/www/.../pub/static/adminhtml/Magento/backend/de_DE/mage/requirejs/mixins.js): failed to open stream: No such file or directory" können nicht gelesen werden in /var/www/.../vendor/magento/framework/Filesystem/Driver/File.php:149
Stack trace:
#0 /var/www/.../vendor/magento/framework/Filesystem/Directory/Read.php(207): Magento\Framework\Filesystem\Driver\File->fileGetContents('/var/www/share/...', NULL, NULL)
#1 /var/www/.../vendor/magento/framework/View/Asset/Source.php(262): Magento\Framework\Filesystem\Directory\Read->readFile('mixins.js')
#2 /var/www/.../vendor/magento/framework/View/Asset/Source.php(143): Magento\Framework\View\Asset\Source->createChain(Object(Magento\Framework\View\Asset\File), '/var/www/share/...', 'mixins.js')
#3 /var/www/.../vendor/magento/framework/View/Asset/Source.php(97): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#4 /var/www/.../vendor/magento/framework/View/Asset/File.php(150): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#5 /var/www/.../vendor/magento/framework/View/Asset/MergeStrategy/Checksum.php(49): Magento\Framework\View\Asset\File->getSourceFile()
#6 /var/www/.../vendor/magento/framework/View/Asset/Merged.php(97): Magento\Framework\View\Asset\MergeStrategy\Checksum->merge(Array, Object(Magento\Framework\View\Asset\File))
#7 /var/www/.../vendor/magento/framework/View/Asset/Merged.php(157): Magento\Framework\View\Asset\Merged->initialize()
#8 /var/www/.../vendor/magento/framework/View/Page/Config/Renderer.php(358): Magento\Framework\View\Asset\Merged->rewind()
#9 /var/www/.../vendor/magento/framework/View/Page/Config/Renderer.php(251): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml('<script  type="...', Object(Magento\Framework\View\Asset\Merged))
#10 /var/www/.../vendor/magento/framework/View/Page/Config/Renderer.php(226): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(Object(Magento\Framework\View\Asset\PropertyGroup))
#11 /var/www/.../vendor/magento/framework/View/Page/Config/Renderer.php(99): Magento\Framework\View\Page\Config\Renderer->renderAssets(Array)
#12 /var/www/.../vendor/magento/framework/View/Result/Page.php(235): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#13 /var/www/.../vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#14 /var/www/.../var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#15 /var/www/.../vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#16 /var/www/.../vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#17 /var/www/.../index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
```

In the following requests the error doesn't appear anymore, because the file was created.

How should I proceed here? Should I open a new isssue?

**Comment by southerncomputer** [comment]
This occurs after php bin/magento deploy:mode:set developer and after you have cleaned out your cache and pub/static/ is clean!

`[2016-09-21 15:20:37] report.CRITICAL: Magento\Framework\Exception\FileSystemException: Cannot read contents from file "/home//public_html/pub/static/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.js" Warning!file_get_contents(/home/public_html/pub/static/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.js): failed to open stream: No such file or directory in /home/public_html/vendor/magento/framework/Filesystem/Driver/File.php:149
Stack trace:
#0 /home/public_html/vendor/magento/framework/Filesystem/Directory/Read.php(207): Magento\Framework\Filesystem\Driver\File->fileGetContents('/home/publi...', NULL, NULL)
#1 /home/public_html/vendor/magento/framework/View/Asset/Source.php(285): Magento\Framework\Filesystem\Directory\Read->readFile('mixins.js')
#2 /home/public_html/vendor/magento/framework/View/Asset/Source.php(151): Magento\Framework\View\Asset\Source->createChain(Object(Magento\Framework\View\Asset\File), '/home/publi...', 'mixins.js')
#3 /home/public_html/vendor/magento/framework/View/Asset/Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#4 /home/public_html/vendor/magento/framework/View/Asset/File.php(150): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#5 /home/public_html/vendor/magento/framework/View/Asset/MergeStrategy/Checksum.php(49): Magento\Framework\View\Asset\File->getSourceFile()
#6 /home/scw/public_html/vendor/magento/framework/View/Asset/Merged.php(97): Magento\Framework\View\Asset\MergeStrategy\Checksum->merge(Array, Object(Magento\Framework\View\Asset\File))
#7 /home/scw/public_html/vendor/magento/framework/View/Asset/Merged.php(157): Magento\Framework\View\Asset\Merged->initialize()
#8 /home/scw/public_html/vendor/magento/framework/View/Page/Config/Renderer.php(358): Magento\Framework\View\Asset\Merged->rewind()
#9 /home/scw/public_html/vendor/magento/framework/View/Page/Config/Renderer.php(251): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml('<script  type="...', Object(Magento\Framework\View\Asset\Merged))
#10 /home/scw/public_html/vendor/magento/framework/View/Page/Config/Renderer.php(226): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(Object(Magento\Framework\View\Asset\PropertyGroup))
#11 /home/scw/public_html/vendor/magento/framework/View/Page/Config/Renderer.php(99): Magento\Framework\View\Page\Config\Renderer->renderAssets(Array)
#12 /home/scw/public_html/vendor/magento/framework/View/Result/Page.php(235): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#13 /home/scw/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#14 /home/scw/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#15 /home/scw/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#16 /home/scw/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#17 /home/scw/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#18 {main} [] []
[2016-09-21 15:20:40] report.CRITICAL: Magento\Framework\Exception\FileSystemException: Cannot read contents from file "/home/scw/public_html/pub/static/frontend/Magento/luma/en_US/mage/requirejs/mixins.js" Warning!file_get_contents(/home/scw/public_html/pub/static/frontend/Magento/luma/en_US/mage/requirejs/mixins.js): failed to open stream: No such file or directory in /home/scw/public_html/vendor/magento/framework/Filesystem/Driver/File.php:149
`

**Comment by davidnguyen2205** [comment]
me too...

**Comment by romeof1980** [comment]
hi there,
we're getting the same issue after moving Magento 2.1.0 (using the same same server in a shared environment).
Redeploying static content hasn't helped.  
Stucked with the same issue:
`'Cannot read contents from file "/html/pub/static/adminhtml/Magento/backend/en_US/mage/requirejs/mixins.min.js"`

Permission have been set correctly (we checked the entire path).

We've been working for some month with Magento 2 but it's the first time that redeploying static content hasn't helped.
Curiously, we don't get any error/warning from the Firebug console (we expected some 404 error) but the error is only found in the exception log)

working on it...

**Comment by webtekindo** [comment]
same for me on a fresh instal 2.1.1

**Comment by sergy-gzh** [comment]
Spotted this issue on 2.1 after enabling js merge in the backend.
@daim2k5 can you please double check it?

**Comment by Will-I4M** [comment]
Same issue for me but it's working after redeploying static content / cleaning & flushing cache.

**Comment by lingwooc** [comment]
I had this problem. For some reason I only had an en_US folder in /pub/static and it was looking for an en_GB folder. This problem started after upgrade from 2.1.1 to 2.1.2. I had to run 

php bin/magento setup:static-content:deploy en_GB

Your language may vary. Doesn't look like its the problem that @craigcarnell is having but it might help someone else. Try running static-content:deploy with -v, that command errors _very_ quietly without it. Try -vv to output all the paths too (helps with finding the troublesome files).

**Comment by romeof1980** [comment]
Hi Chris 
did you try
php bin/magento setup:static-content:deploy en_Gb   ?
 us_US is the default when you don't specify another "locale"

cheers,
romeo


---- On Sun, 11 Dec 2016 04:38:48 -1000 notifications@github.com wrote ----

I had this problem. For some reason I only had an en_US folder in /pub/static and it was looking for an en_GB folder. This problem started after upgrade from 2.1.1 to 2.1.2. I had to run

php bin/magento setup:static-content:deploy en_GB

Your language may vary. Doesn't look like its the problem that @craigcarnell is having but it might help someone else. Try running static-content:deploy with -v, that command errors very quietly without it. Try -vv to output all the paths too (helps with finding the troublesome files).

**Comment by lingwooc** [comment]
Yup, that's what fixed it.

**Comment by hareshpatel** [comment]
hello same issue how can resolve ?
