### ISSUE TITLE
Unable to add product to backend using HHVM

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2067]
```
[Fri Oct  9 08:59:46 2015] [hphp] [26909:7fa9dd3ff700:66:000001] [] \nFatal error: infinite recursion detected in /var/www/vhosts/magento2-capistrano/releases/20151009085140/app/code/Magento/ProductVideo/Block/Adminhtml/Product/Edit/NewVideo.php on line 218
```

**Comment by mslabko** [comment]
Hello, @craigcarnell 
Thank you for reporting the issue.
Internal ticket has been created.

**Comment by craigcarnell** [comment]
@mslabko I don't know if you have changed something but I just pulled down develop and deployed to my server and ran the upgrade, and now I can get to the add product page.

However after adding some basic details (name, sku, price, default category and short description) I just get a spinning wheel. No errors recorded in hhvm, nginx or magento.

**Comment by antonkril** [comment]
@craigcarnell, did you clear browser cache? JS files were modified, and your browser may be using old versions.

**Comment by craigcarnell** [comment]
@antonkril It works after clearing out pub/static. Thanks
