### ISSUE TITLE
The Topmenu class looks procedural

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#2068]
https://github.com/magento/magento2/blob/4985acecc2a9204712531ba25b0c867ef09a4667/app/code/Magento/Theme/Block/Html/Topmenu.php

Could we please use more templates for rendering the markup? You can't easily change the HTML/menu without having to rewrite the whole class. I'm talking especially about the `_getHtml()`.

**Comment by orlangur** [comment]
Nice try on refactoring this class was performed in https://github.com/magento/magento2/pull/1123.

**Comment by antonkril** [comment]
One thing to consider here is performance. If Topmenu is refactored incorrectly (every item is separate template) on some installations this will result in hundreds of template inclusions (more than rest of the page). But if this will be done with one template for whole menu, all logic from class will move to that template, and there will be no noticeable complexity reduction.

**Comment by okorshenko** [comment]
Closing. Considering on performance.

**Comment by orlangur** [comment]
> But if this will be done with one template for whole menu as it is done in PR referenced by @orlangur, customizability will grow, but most logic from class will move to that template, and there will be no noticeable complexity reduction.

This PR did a step in right direction as to me (moving hardcoded view logic from PHP class to PHTML) but I would suggest to move further with this refactoring. The next step would be unnecessary template complexity elimination by splitting one big phtml into multiple smaller.

> One thing to consider here is performance. If Topmenu is refactored to granular rendering (every item is rendered by renderer with template) on some installations this will result in hundreds of template inclusions (more than rest of the page).

Cannot agree with that. Just like for any other renderer there is no need to create many objects and to include templates again and again. So, in optimal implementation there should be only one instance of each renderer and only one inclusion of each distinct template.

Taking into account recursion, we will need to create separate renderer for 0, 1, 2, 3 etc. menu level but no more than that. Each of them may be reused with something like `$renderer->setMenuItem(...); return $renderer->toHtml();`

**Comment by JamesAnelay** [comment]
People just want to easily customise the menu in a template.

As @antonkril said "If this will be done with one template for whole menu as it is done in PR referenced by @orlangur, customizability will grow, but most logic from class will move to that template, and there will be no noticeable complexity reduction." So that's still an improvement lets do that, don't need to over engineer everything if there is a performance issue with going down that route.
