### ISSUE TITLE
Not able to get order details fails with exception 

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2069]
{
    "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-56178c6a16ecb"
}

**Comment by alena-marchenko** [comment]
Hi arunkasyakar,

Please provide exact steps to reproduce the issue and webapi-56178c6a16ecb report for us to be able to investigate the issue.

**Comment by arunkasyakar** [comment]
when i am calling the api http://myhost/rest/default/V1/orders?criteria[filter_groups][0][filters][0][field]=status&criteria[filter_groups][0][filters][0][value]=complete, and if complete state has some value then i am getting this issue, same thing is happening with the processing and pending status of order

**Comment by arunkasyakar** [comment]
and same issue i am getting with the api call http://myhost/magento2/rest/default/V1/orders/2
the error message is  "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-561b9563df59c"

**Comment by arunkasyakar** [comment]
error log are:

[2015-10-12 11:13:23] main.CRITICAL: exception 'Exception' with message 'Report ID: webapi-561b95d3396b1; Message: Notice: Array to string conversion in /var/www/html/magento2/lib/internal/Magento/Framework/Reflection/TypeCaster.php on line 34' in /var/www/html/magento2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/html/magento2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/www/html/magento2/app/code/Magento/Webapi/Controller/Rest.php(188): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/www/html/magento2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#5 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by NadiyaS** [comment]
Hi @arunkasyakar ,
internal issue was created MAGETWO-44585

**Comment by tuyennn** [comment]
@magento-engcom-team Which ref link for this fix? Could you provide the commit, merge ref
