### ISSUE TITLE
bin/magento setup:di:compile throws InvalidArgumentExcepton

### ISSUE THREAD

**Issue by johnbendi** [magento/magento2#2070]
After installing a module the cli says to run the compile command. The only compile command I can see is `setup:di:compile`. 

Running it returns this:
```
Compilation was started.
Application code generator... 2/6 [=========>------------------]  33% 46 secs 275.2 MiB75.2 MiB
                                                  
  [Zend\Code\Exception\InvalidArgumentException]  
  File "" not found                               
                                                  
setup:di:compile

```

**Comment by orlangur** [comment]
I observed another error running `php -f bin/magento -- setup:di:compile`:
```
$ php -f bin/magento -- setup:di:compile
Could not locate schema: 'urn:magento:framework:ObjectManager/etc/config.xsd' at '/ObjectManager/etc/config.xsd'#0 /home/user/workspace/magento2/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(137): Magento\Framework\App\ObjectManagerFactory->_loadPrimaryConfig(Object(Magento\Framework\App\Filesystem\DirectoryList), Object(Magento\Framework\Filesystem\DriverPool), Object(Magento\Framework\ObjectManager\Config\Mapper\Dom), 'default')
```

but it disappeared after `composer install`.

Could you provide a example of module which causes problem for compilation after install?

**Comment by mazhalai** [comment]
@johnbendi are you installing a custom module? Can you please check your custom module for references to missing classes?

**Comment by Vinai** [comment]
Same issue here. No custom module involved. Current develop branch.

**Comment by mazhalai** [comment]
@johnbendi can you please try solutions mentioned by @orlangur and @Vinai

**Comment by johnbendi** [comment]
@mazhalai It will take a while before I get around to this issue. I'm currently updating to latest develop and getting dfferent issues. I'll report progress when I get to use this command again.

**Comment by daim2k5** [comment]
@johnbendi hopefully its working now. If not please feel free to reopen the issue
