### ISSUE TITLE
Regarding magento catalog and category type attribute

### ISSUE THREAD

**Issue by sanjayjethva** [magento/magento2#2071]
Hello Friends,
I am creating the InstallSchema.php file and when i run this file from the extension then it throws the error.
Actually i am creating one catalog product type attribute and one category type attribute.

Thanks for your help in advnace.

[ErrorException]
  Argument 1 passed to Magento\Eav\Setup\EavSetup::__construct() must impleme
  nt interface Magento\Framework\Setup\ModuleDataSetupInterface, instance of
  Magento\Setup\Module\Setup given, called in \lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php on
   line 103 and defined

Here is my code and please help me to resolve the issue.

<?php
namespace Magento\Callforquote\Setup;

use Magento\Eav\Setup\EavSetup;
use Magento\Eav\Setup\EavSetupFactory;
use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;
use Magento\Framework\DB\Ddl\Table;
 
class InstallSchema implements InstallSchemaInterface
{
	private $eavSetupFactory;
	
	public function __construct(EavSetupFactory $eavSetupFactory)
    {
    	$this->eavSetupFactory = $eavSetupFactory;
	}
	
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
		$installer = $setup;
        $installer->startSetup();
 
        // Get magecomp_callforprice table
        $tableName = $installer->getTable('callforquote');
        // Check if the table already exists
        if ($installer->getConnection()->isTableExists($tableName) != true)
		{
            // Create tutorial_simplenews table
            $table = $installer->getConnection()
                ->newTable($tableName)
                ->addColumn(
                    'id',
                    \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                    null,
                    [
                        'identity' => true,
                        'unsigned' => true,
                        'nullable' => false,
                        'primary' => true
                    ],
                    'ID'
                )
                ->addColumn(
                    'name',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    null,
                    ['nullable' => false, 'default' => ''],
                    'Name'
                )
                ->addColumn(
                    'email',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => false, 'default' => ''],
                    'Email'
                )
				->addColumn(
                	'product_id',
                	\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                	null,
                	['unsigned' => true, 'nullable' => false, 'default' => '0'],
                	'Product Id'
            	)
                ->addColumn(
                    'product_name',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => false, 'default' => ''],
                    'Product Name'
                )
                ->addColumn(
                    'country_id',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => false, 'default' => ''],
                    'Country'
                )
				->addColumn(
                    'telephone',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => false, 'default' => ''],
                    'Phone Number'
                )
				->addColumn(
                    'message',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => false, 'default' => ''],
                    'Message'
                )
				->addColumn(
                	'store_id',
                	\Magento\Framework\DB\Ddl\Table::TYPE_SMALLINT,
                	null,
                	['unsigned' => true, 'nullable' => false, 'default' => '0'],
                	'Store ID'
            	)
				->addColumn(
                    'created_time',
                    \Magento\Framework\DB\Ddl\Table::TYPE_DATETIME,
                    null,
                    ['nullable' => true, 'default' => null],
                    'Created Time'
                )
				->setComment('Call For Price Details')
                ->setOption('type', 'InnoDB')
                ->setOption('charset', 'utf8');
            $installer->getConnection()->createTable($table);
        }
		$eavSetupFactory = $this->eavSetupFactory->create(['setup' => $setup]);
		
		$eavSetupFactory->addAttributeGroup(\Magento\Catalog\Model\Product::ENTITY, 'Default', 'Call For Price', 1000);
	
		$eavSetupFactory->addAttribute(\Magento\Catalog\Model\Product::ENTITY, 'callforquote',
		[
			'group'         	=> 'Call for quote',
			'label'				=> 'Call for quote',
			'type'				=> 'int',
			'input'            	=> 'boolean',
			'source'           	=> 'Magento\Eav\Model\Entity\Attribute\Source\Boolean',
			'global'           	=> \Magento\Catalog\Model\Resource\Eav\Attribute::SCOPE_GLOBAL,
			'visible'          	=> true,
			'required'         	=> false,
			'user_defined'     	=> true,
			'searchable'       	=> false,
			'filterable'       	=> false,
			'comparable'       	=> false,
			'visible_on_front' 	=> false,
			'visible_in_advanced_search'	=> false,
			'used_in_product_listing' => false,
			'unique'            => false,
			'apply_to'=>'simple,configurable,virtual,bundle,downloadable',
			'default'			=> false
		]);
	
		
		$categorySetup = $this->eavSetupFactory->create(['setup' => $setup]);

    	$entityTypeId = $categorySetup->getEntityTypeId(\Magento\Catalog\Model\Category::ENTITY);
    	$attributeSetId = $categorySetup->getDefaultAttributeSetId($entityTypeId);
    	$testAttributeGroupId = $categorySetup->getAttributeGroupId($entityTypeId, $attributeSetId, 'Test');

		$categorySetup->addAttributeGroup($entityTypeId, $attributeSetId, 'callforquote', 'callforquote', 3000);
		$categorySetup->addAttribute(\Magento\Catalog\Model\Category::ENTITY, 'callforquote',
		[
			'group'         	=> 'Call Quote',
			'label'				=> 'Call Quote',
			'type'				=> 'int',
			'input'            	=> 'select',
			'source'           	=> 'Magento\Eav\Model\Entity\Attribute\Source\Boolean',
			'global'           	=> \Magento\Catalog\Model\Resource\Eav\Attribute::SCOPE_GLOBAL,
			'visible'          	=> true,
			'required'         	=> true,
			'user_defined'     	=> true,
			'searchable'       	=> false,
			'filterable'       	=> false,
			'comparable'       	=> false,
			'visible_on_front' 	=> false,
			'visible_in_advanced_search'	=> false,
			'unique'            => false,
			'default'			=> false
		]);
		
		
		$installer->endSetup();
    }
}

**Comment by orlangur** [comment]
I didn't try your code in action but it seems to me that attributes must be added in `InstallData`, not in `InstallSchema`. You can see working example of adding attribute in https://github.com/magento/magento2/blob/develop/app/code/Magento/Msrp/Setup/InstallData.php

**Comment by sanjayjethva** [comment]
Hello @orlangur 
Thanks for your answer and can you please give an example of category attribute creation.
Thanks in advance.

**Comment by orlangur** [comment]
Just another entity constant: https://github.com/magento/magento2/blob/7dcac823e102042d9052304b40c79b16efc56399/app/code/Magento/CatalogUrlRewrite/Setup/InstallData.php#L44

**Comment by sanjayjethva** [comment]
Hello @orlangur 
Thank you very much for your help.
