### ISSUE TITLE
how to import customers in magento-2 ??

### ISSUE THREAD

**Issue by aman91u** [magento/magento2#2075]
I am trying to import customers using csv in magento-2 . I have fill all coloum and row according to need , But i am always getting this error,"1. Please make sure attribute "firstname" is not empty. in rows: 1". Please help me ..

**Comment by slavvka** [comment]
@aman91u , thank you for the question. Could you please provide your file to be imported to check what is wrong? Thank you!

**Comment by aman91u** [comment]
i found solution and i successfully imported all propducts . Issue with shippingname note blank that`s by this issue occurs
