### ISSUE TITLE
Admin page just a white box and black background

### ISSUE THREAD

**Issue by serkia** [magento/magento2#2077]
I'm at a dead end. Result is the same with chrome, firefox, and the latest IE on windows 10

running on apache 2.4, php 5.6

screenshot 
http://prntscr.com/8pvods

**Comment by daim2k5** [comment]
https://github.com/magento/magento2/issues/1491#issuecomment-147092719 so you can close this issue?

**Comment by serkia** [comment]
no...unfortunately I thought I was in the clear, but I was wrong. The front end works, the backend doesn't.

The previous post fixed an install issue I had. I belive I'm past the install at this point and there is a setting in apache or maybe php.ini that I can't figure out. Or just something in magento??? Driving myself nuts trying to figure this out

**Comment by dfediuk** [comment]
Yes, admin interface is broken now.
It is not a technical problem, it is the management problem: Magento 2 team regularly do low quality commits with critical bugs on fridays (https://github.com/magento/magento2/issues/2007, https://github.com/magento/magento2/issues/2072).

**Comment by serkia** [comment]
Thank you for clearing up my weekend.

**Comment by dmitrii-fediuk** [comment]
_Removed by moderator_

**Comment by serkia** [comment]
That code worked to bring up a user name and password boxes, but I"m getting a message
>> You did not sign in correctly or your account is temporarily disabled.

I even reset the password in phpMyAdmin under the table "admin_user". Added a MD5 functioin to convert the plain password. Still same thing. So I'm sure I'm not getting the u/p incorrect.

Thanks for the help Dmitry

**Comment by buskamuza** [comment]
Hi @serkia , please, try command `./bin/magento admin:user:unlock <username>` in case the account is locked.

**Comment by gputignano** [comment]
I also got the same problem.

**Comment by yigab** [comment]
So what was the solution to this? unlocking from cli does not work either..

**Comment by buskamuza** [comment]
> unlocking from cli does not work either

Do you mean, it fails? Or it doesn't unlock the user? Or it doesn't fix your issue?

**Comment by zoneradx** [comment]
I got the same issue, when I try to unlock from cli it shows error, that the syntax is wrong.

**Comment by buskamuza** [comment]
@zoneradx , could you, please, provide the exact error message and how you run the command? Thanks.

**Comment by daim2k5** [comment]
@zoneradx can you provide more informations?

**Comment by aravindbaskaran** [comment]
@buskamuza The error I get is `Couldn't find the user account xxx`

**Comment by yigab** [comment]
oh it hasn't been fixed???

What I did was, create a new magento folder, run the installation and type the same information and password as before. after that copy the salt from the new database and paste it on the other one. > run the unlock from cli. and you should be able to login again...

**Comment by rapidmod** [comment]
> You did not sign in correctly or your account is temporarily disabled.

I have been installing via the command line and ran into this problem yesterday, after banging my head off the wall all day, I tried creating a new user via the cli "./bin/magento admin:user:create" and that’s when I noticed an error. I guess usually my random typing contains numbers....

The fix was to make sure there is 1 alpha character and 1 numeric character in the admin password. This should be labelled a **bug** if the password is not validated during install with magento setup:install

password requirements are:

> User Name is a required field.
> First Name is a required field.
> Last Name is a required field.
> Please enter a valid email.
> Password is required field.
> Your password must be at least 7 characters.
> Your password must include both numeric and alphabetic characters.

**Comment by daim2k5** [comment]
@serkia can we close the issue?

**Comment by vnahalpara** [comment]
Solution for 

> You did not sign in correctly or your account is temporarily disabled

[1356-219146758](https://github.com/magento/magento2/issues/1356#issuecomment-219146758)

**Comment by vzabaznov** [comment]
All related bug was closed, issue is not reproducible now
