### ISSUE TITLE
[question] From which code are packages.magento.com packages derived?

### ISSUE THREAD

**Issue by amenk** [magento/magento2#2078]
There is a 1.0.0-beta4 package on packages.magento.com (http://packages.magento.com/_packages/magento_framework-1.0.0-beta4.zip). From which git branch / commit is this derived? There is no such tag on GitHub.

**Comment by maksek** [comment]
hi @amenk, the packages are increment patches/fixes for Merchant Beta program release. 
Basically it is separate branch starting 1.0.0-beta, and targeted only for Merchant Beta program team. Develop branch is much more ahead, and developers must use it for development. We didn't publish the merchant_beta branch yet, due it will be deprecated after GA. But we may publish it just for reference.

**Comment by okorshenko** [comment]
@amenk , please, let us know if you have other questions.
