### ISSUE TITLE
Naming inconsistency: mixed ResourceModel and ModelResource usage for the same thing

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2079]
- a `ModelResource` usage example: https://github.com/magento/magento2/tree/1d97cd9ddee038c9b93c43b74c8e318702a70a33/lib/internal/Magento/Framework/Model/ModelResource/
- a `ResourceModel` usage example: https://github.com/magento/magento2/tree/1d97cd9ddee038c9b93c43b74c8e318702a70a33/app/code/Magento/Catalog/Model/ResourceModel/

**Comment by SerhiyShkolyarenko** [comment]
@dfediuk we renamed ModelResource namespace in framework to ResourceModel. Thank you for reporting.

**Comment by okorshenko** [comment]
Closing. @dfediuk, please, let us know if you still have an issue
