### ISSUE TITLE
On Admin Dashboard Order & Amount Tab Not Working

### ISSUE THREAD

**Issue by janihemanspice** [magento/magento2#208]
Hi mage2-Team,

In dev41 -new admin theme, dashboard page Above Chart/graph two tabs Order(s) & Amount(s) are not working properly. please verify the issue.

Thanks,
Heman

**Comment by Kristiansky** [comment]
still not working

**Comment by joanhe** [comment]
@Kristiansky Could you let us know the version you are working on, so we can verify it?
