### ISSUE TITLE
«Argument 1 passed to Magento\Framework\View\Xsd\Reader::addHeadChildIntoParent() must be an instance of DOMElement, null given» (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2082]
https://mage2.pro/t/133

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44691

**Comment by dsikkema** [comment]
@dfediuk can you please provide steps to reproduce the exception, and a stack trace?

**Comment by ishakhsuvarov** [comment]
Closing the ticket for now, please reopen if you have any updates.
