### ISSUE TITLE
Using parts of Magento in other software

### ISSUE THREAD

**Issue by XedinUnknown** [magento/magento2#2083]
Hi,

First of all, I would like to express appreciation for this amazing project. I have been developing for Magento for over 4 years now, and have come to admire it as the greatest PHP work ever written; it opened my eyes to PHP. In fact, I like it so much that I use many practices common to Magento in other software I write. And this brings up a question...

I would like to use some parts of Magento 2, namely the [`Magento\Framework\DataObject`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/DataObject.php) class, in my software. I would like to distribute it with my software, because I intend to subclass it and use the descendant in my own project. I do not wish to modify the original class in any way. However, I anticipate that my software will be used with other software, including software licensed under the GNU GPL, and therefore I will license most of my software under the MIT license.

By doing this, am I creating a Derivative Work? More importantly, will this break compatibility, thus not allowing the usage of my software with software licensed under GPL-compatible licenses? If yes, is there another way in which I could use the said class?

Thank you very much!

**Comment by davidalger** [comment]
The GitHub issue tracker is only intended for technical issues resulting from underlying issues in the Magento software. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions and support.
