### ISSUE TITLE
Allow running cron jobs by code

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#2085]
To make debugging cronjobs a lot easier, it would be great if I can execute them directly via CLI

**Comment by antonkril** [comment]
Also you can (should) write integration tests for them.

**Comment by Flyingmana** [comment]
Can I find documentation or an example for a integration test of cron?

I tried custom cron groups, but I can not rerun a job multiple times in less then a minute.

Also, I dont deploy phpunit to production environment, so I cant run the job there again to see, if the failing is random or reproducable, or just rerun it after changing a setting I forgot.
Are this enough reasons to have this?

**Comment by alankent** [comment]
Do you mean more than 'magento cron:run'?  You want to select the specific code to run? Maybe add a command line option to the existing command?

**Comment by Flyingmana** [comment]
yes, the specific code, and then having this one job directly running.
A command line option would be probably enough for this.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Allow-running-cron-jobs-by-code/idi-p/45419).
