### ISSUE TITLE
Backend: page.loader template admin/loader.phtml is missing

### ISSUE THREAD

**Issue by amenk** [magento/magento2#2086]
The template referenced here https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/view/adminhtml/layout/default.xml#L68 (`Magento_Backend::admin/loader.phtml`) seems to be missing.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44688

**Comment by shiftedreality** [comment]
Should be fixed already.
Closed.
