### ISSUE TITLE
Parameter type for \Magento\Customer\Model\Customer::setStore() should be \Magento\Store\Api\Data\StoreInterface, not \Magento\Store\Model\Store

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2087]
https://github.com/magento/magento2/blob/3a72e6eeda90d6f19c0ee5ca807028b8447bc4fe/app/code/Magento/Customer/Model/Customer.php#L958

**Comment by slavvka** [comment]
@dfediuk thank you for your notification. Could you please give us more details why current definition is a problem for you?

**Comment by slavvka** [comment]
@mage2pro Is this issue still actual?

**Comment by slavvka** [comment]
Closing since the author didn't respond
