### ISSUE TITLE
Method setStoreId() need to be added to the PHPDoc declaration of the class \Magento\Customer\Model\Customer

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2088]
An example of usage: https://github.com/magento/magento2/blob/4d5990adea0b49ade3794b8a1dde793d25103d35/app/code/Magento/Customer/Model/Customer.php#L960

**Comment by slavvka** [comment]
Hi @dfediuk. Could you please explain why do you need that?

**Comment by dfediuk** [comment]
Because a usage of an undeclared method leads to IDE inspection warnings.

**Comment by slavvka** [comment]
I see. It isn't an urgent fix to be made so feel free to make a pull request with your changes and we will merge it. Thank you!
