### ISSUE TITLE
Method \Magento\Customer\Model\Customer::setWebsiteId() has wrong PHPDoc declaration

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2089]
https://github.com/magento/magento2/blob/4d5990adea0b49ade3794b8a1dde793d25103d35/app/code/Magento/Customer/Model/Customer.php#L25

Need to be `@method Customer setWebsiteId($value)`

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44062

**Comment by maxwhite-ua** [comment]
@dfediuk, thank you for info. This fix will be merged soon in scope of MAGETWO-44062

**Comment by slavvka** [comment]
@dfediuk, Internal ticket MAGETWO-44062 is closed and delivered to mainline. Please, see a698766. Please, let us know if you still have an issue.
