### ISSUE TITLE
Creation of orders for downloadable products under the cron

### ISSUE THREAD

**Issue by mklishevych** [magento/magento2#209]
Currently, it's only possible to create orders for downloadable products only from frontend or admin area. I've investigated the problem and I can say the problem is caused by wrong event subscription configuration.

In file app/code/core/Mage/Downloadable/etc/config.xml, subscription for event called sales_order_item_save_commit_after presented for both frontend and adminhtml areas. 

Observer for this event is not triggered under the cron (because the only available area under the cron is crontab area), so the order will have no downloadable links in it.

I believe there is no reason to ignore the crontab area and it should be changed for sure.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the 
backlog. We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-19106

**Comment by choukalos** [comment]
As of 0.74-beta8 in production.  You can now create downloadable products via APIs in two different ways.  

First way
1.  Create product ( POST /V1/products )
2.  Create downloadable Link ( POST /V1/products/:sku/downloadable-links ) for the product you created

Second way
1.  Create product and as part of request object include both the product object and the downloadable link object (plus any other's that you want - perhaps media, etc); via POST /V1/products

We don't have much API documentation right now but if you'd like to get the latest/greatest for REST url's and payload/responses try running the api-functional tests.  Make sure you update the phpunit.xml.dist file and set your base url, admin user, admin password, and change GENERATE_REST_DOCUMENTATION variable to true.  That'll create an output file with the documentation for all REST calls, requests and responses in the system.

**Comment by mklishevych** [comment]
Initial issue was not related to API at all. It was related to the situation, when some module (e.g. M2ePro) re-implements checkout functionality to create orders in magento, which came from 3rd party source (eBay in this case). And the problem was that subscription for event called "sales_order_item_save_commit_after" was explicitly configured for adminhtml and frontend event areas. Under the cron only global and crontab areas are available, and that was the issue.
