### ISSUE TITLE
\Magento\Framework\App\DeploymentConfig::get() method is declared with wrong PHPDoc return type

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2090]
https://github.com/magento/magento2/blob/fa9c56951a16070661a89de73c2cbb10949eb32e/lib/internal/Magento/Framework/App/DeploymentConfig.php#L68

`@return array|null` is wrong because the method can return also a string.

**Comment by piotrekkaminski** [comment]
internal ID MAGETWO-44687

**Comment by ishakhsuvarov** [comment]
@dfediuk Closing this ticket as fix was delivered to the `develop` branch.
