### ISSUE TITLE
\Magento\Eav\Model\Config::getAttribute() method is declared with wrong PHPDoc return type

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2092]
https://github.com/magento/magento2/blob/fa9c56951a16070661a89de73c2cbb10949eb32e/app/code/Magento/Eav/Model/Config.php#L421

The declaration `@return  \Magento\Eav\Model\Entity\Attribute\AbstractAttribute|false` is wrong because the method unable to return false.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44686

**Comment by davidalger** [comment]
Fixed. Please reopen if issue persists.
