### ISSUE TITLE
Group Price missing in developer branch

### ISSUE THREAD

**Issue by thomasnordkvist** [magento/magento2#2094]
Group Price is missing.
Just installed at commit 6fa09047a6d4a1ec71494fadec5a42284ba7cc1d and the Group Price function in Advanced Pricing is no longer there.
Why is it removed?

**Comment by antonkril** [comment]
Because of functional intersection with tier prices

**Comment by thomasnordkvist** [comment]
Makse sense, same result can be achived with less code maintenance.

**Comment by sammarcus** [comment]
@antonkril Is the independent Group Price section permanently removed? I see how you can use Tier Pricing to get this functionality, but the docs still show the sections are independent:
http://docs.magento.com/m2/ce/user_guide/catalog/settings-advanced-advanced-pricing.html

Just want to be sure. Thanks!
