### ISSUE TITLE
CMS roadmap?

### ISSUE THREAD

**Issue by acharrex** [magento/magento2#2095]
Hi, I'm working on a CMS extension for Magento 2, and I would know if major improvements will be released soon on this part of Magento? (see note https://github.com/magento/magento2/issues/1964#issuecomment-143597629)

**Comment by alankent** [comment]
Sorry! I missed your question on the other thread. This is a question for the product managers however. I will make sure they see this.

**Comment by acharrex** [comment]
Thanks a lot Alan.
I'm looking forward to getting their feedback.

**Comment by choukalos** [comment]
Hey Olena can you share some insight with @acharrex on our near term CMS improvements?

**Comment by acharrex** [comment]
Nobody is here?

**Comment by tkacheva** [comment]
@acharrex we have plans on improving CMS capabilities in future Magento 2 releases. The top priority is to improve content editing capabilities and make page creation faster and easier for admin user.

**Comment by acharrex** [comment]
Thanks Oleva for your reply.
When do you know these changes will be released? In three months, six months, one year?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As a somewhat non-technical question regarding the product, the [Community Forums](https://community.magento.com) is likely the most appropriate place.
