### ISSUE TITLE
rest api's are not working 

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2096]
any of rest api is not working for category, i tried for the api calls: 
1. http://MYHOST/magento2/rest/default/V1/categories
2.http://MYHOST/magento2/rest/default/V1/categories?searchCriteria[filter_groups][0][filters][0][field]=categoryId&searchCriteria[filter_groups][0][filters][0][value]=3
  
    and various other search criteria but in all cases it returns only the first record of the categories list

3. i am not able to fetch the list of product by categoryId, i tried the api call
      http://MYHOST/magento2/rest/default/V1/categories/3/products, but the result is a blank array( [] )

**Comment by choukalos** [comment]
Just checked on the latest dev commit and am unable to replicate.  Closing.

**Comment by gg24** [comment]
Try with,
http://MYHOST/magento2/rest/V1/categories
for all categories.

http://MYHOST/magento2/rest/V1/categories/4/products
for products of category id 4,

http://MYHOST/magento2/rest/V1/products/testsku
for product's data of sku testsku
