### ISSUE TITLE
Product import only adds image to last product.

### ISSUE THREAD

**Issue by thomasnordkvist** [magento/magento2#2097]
When i try to import products with images, only the last product in the import-file gets the images attached correct. Thumb shows in the admin product grid but no images are visible on product edit page.

The magento installation is from commit 6fa09047a6d4a1ec71494fadec5a42284ba7cc1d from 2015-10-12.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-44061

**Comment by thomasnordkvist** [comment]
@MomotenkoNatalia  @piotrekkaminski 
What's the protocoll for closing issues?
I don't seem to have this problem anymore.
/Thomas

**Comment by davidalger** [comment]
@thomasnordkvist As this issue has been resolved (per your latest comment) I'm closing this issue. Please feel free to reopen if you re-encounter the issue!
