### ISSUE TITLE
Disable module does not remove it from setup_module table

### ISSUE THREAD

**Issue by johnbendi** [magento/magento2#2098]
Disabling a module does not remove it from the setup_module table.

**Comment by mazhalai** [comment]
@johnbendi if you require to completely remove a module, please use `bin/magento module:uninstall` instead.

**Comment by johnbendi** [comment]
`bin/magento module:uninstall` doesn't handle the case where a module is not installed with composer.

Sample output:
```
Vendor_Module is not an installed composer package
```

**Comment by piotrekkaminski** [comment]
@tanya-soroka please review

**Comment by alankent** [comment]
Does your module have a composer.json file?  You should always have a composer.json file, even when not installed via composer.

**Comment by johnbendi** [comment]
@alankent the module didn't have a `composer.json`. I included it and it made no difference since if you are not installing via composer you would only have to do module:enable. After adding `composer.json` and disabling module, it is still listed in `setup_module` table.

**Comment by alankent** [comment]
Hmmm. I am going to have to leave this one for the developers working in this area. The code looks like it is checking two sources to work out if module is known - I don't the subtleties of how it works. @mazhalai .

**Comment by mazhalai** [comment]
@johnbendi `module:uninstall` is intended to be used only if you are absolutely certain it wont be used any longer. However, other modules may have dependencies on the module that is to be removed. Hence we use `composer remove`, which calculates dependencies, to remove code of the module from the file system. 
In module enable/disable, the code is never removed from the filesystem, so that it can be used if required at a later time. Hence, it is not removed from the `setup_module` table.

@alankent since the latest changes regarding composer deployment, each module now requires to have a `registration.php` file. That is the only source of how magento is aware if a module is present.

**Comment by tanya-soroka** [comment]
@johnbendi  Do you have any additional question / Comments? 
If not please close the ticket.

**Comment by igoreus-barmaleus** [comment]
1) Open

`setup/src/Magento/Setup/Console/Command/ModuleUninstallCommand.php`

and replace

```
    protected function validate(array $modules)
    {
        $messages = [];
        $unknownPackages = [];
        $unknownModules = [];
        $installedPackages = $this->composer->getRootRequiredPackages();
        foreach ($modules as $module) {
            if (array_search($this->packageInfo->getPackageName($module), $installedPackages) === false) {
                $unknownPackages[] = $module;
            }
            if (!$this->fullModuleList->has($module)) {
                $unknownModules[] = $module;
            }
        }
        $unknownPackages = array_diff($unknownPackages, $unknownModules);
        if (!empty($unknownPackages)) {
            $text = count($unknownPackages) > 1 ?
                ' are not installed composer packages' : ' is not an installed composer package';
            $messages[] = '<error>' . implode(', ', $unknownPackages) . $text . '</error>';
        }
        if (!empty($unknownModules)) {
            $messages[] = '<error>Unknown module(s): ' . implode(', ', $unknownModules) . '</error>';
        }
        return $messages;
    }
```

with

```
    protected function validate(array $modules)
    {
        $messages = [];
        $unknownPackages = [];
        $unknownModules = [];
        $installedPackages = $this->composer->getRootRequiredPackages();
        foreach ($modules as $module) {
            if (array_search($this->packageInfo->getPackageName($module), $installedPackages) === false) {
                $unknownPackages[] = $module;
            }
            if (!$this->fullModuleList->has($module)) {
                $unknownModules[] = $module;
            }
        }
        if (!empty($unknownModules)) {
            $messages[] = '<error>Unknown module(s): ' . implode(', ', $unknownModules) . '</error>';
        }
        return $messages;
    }
```

2) Open

`setup/src/Magento/Setup/Model/ModuleUninstaller.php`

and replace

```
    public function uninstallCode(OutputInterface $output, array $modules)
    {
        $output->writeln('<info>Removing code from Magento codebase:</info>');
        $packages = [];
        /** @var \Magento\Framework\Module\PackageInfo $packageInfo */
        $packageInfo = $this->objectManager->get('Magento\Framework\Module\PackageInfoFactory')->create();
        foreach ($modules as $module) {
            $packages[] = $packageInfo->getPackageName($module);
        }
        $this->remove->remove($packages);
    }
```

with

```
    public function uninstallCode(OutputInterface $output, array $modules)
    {
        $output->writeln('<info>Removing code from Magento codebase:</info>');
        $packages = [];
        /** @var \Magento\Framework\Module\PackageInfo $packageInfo */
        $packageInfo = $this->objectManager->get('Magento\Framework\Module\PackageInfoFactory')->create();
        foreach ($modules as $module) {
            $packages[] = $packageInfo->getPackageName($module);
        }
    }
```

3) Say "lyaska masyaska"

Note, the solution is not recommended on production server.
