### ISSUE TITLE
Attribute with attributeCode 

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2099]
with any of GET request for product related search getting the message

{
    "message": "Attribute with attributeCode \"%1\" does not exist.",
    "parameters": [
        "rating"
    ]
}

**Comment by tanya-soroka** [comment]
@arunkasyakar  thanks for reporting the issue. Internal ticket has been created MAGETWO-44070.

**Comment by tanya-soroka** [comment]
@arunkasyakar thanks for reporting this. Could you please provide use-case to reproduce or more information?

**Comment by tanya-soroka** [comment]
@arunkasyakar the issues should be fixed. Please verify and reopen a ticket if you will have any issues.

**Comment by arunkasyakar** [comment]
thanks @tanya-soroka  it is resolved
