### ISSUE TITLE
Backup Enhancements

### ISSUE THREAD

**Issue by Lewiscowles1986** [magento/magento2#2101]
It's fantastic that you can take backups in Magento 2 for the three different areas, I have some suggestions I believe would make this more professional solution

 * Ability to backup automatically to a schedule (not just when installing plug-ins)
 * Default to exclude media from system backups
 * Default to put system into maintenance mode during backup
 * Ability to launch all three backups with formatting string
   * "%Y-%m-%d %H%i backup db"
   * "%Y-%m-%d %H%i backup sys"
   * "%Y-%m-%d %H%i backup uploads"

**Comment by mazhalai** [comment]
@Lewiscowles1986 thank you for your suggestions. However, could you expand on why this is required?
`Default to put system into maintenance mode during backup`

**Comment by Lewiscowles1986** [comment]
Hi @mazhalai :smile: 

It's an enhancement so that resource locking will not affect the backup for large sites. 

It's also not a requirement, just an enhancement idea that would be nice if there is time. To be honest it's the least valuable of the enhancements listed, supporting formatted strings for backups and having scheduled backups are much more important.

**Comment by tanya-soroka** [comment]
internal ticket for improvement has been created MAGETWO-44435

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Backup-Enhancements/idi-p/46902).
