### ISSUE TITLE
Undeclared dynamic property gets leaked in public space

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#2103]
I'm talking about this: https://github.com/magento/magento2/blob/e5dedb8b75cfe46eb9e68b5d55c983e8b5ce3c55/app/code/Magento/LayeredNavigation/Block/Navigation.php#L62

There is no `\Magento\LayeredNavigation\Block\Navigation::$renderer` member, so it becomes public.

**Comment by piotrekkaminski** [comment]
@antonkril  can you look into this and decide on priority?

**Comment by antonkril** [comment]
It's low priority, but we should create static test to catch such cases. They allow unreliable implementations of extensions and make instantiation of such classes bit slower.

**Comment by voleye** [comment]
I have created an internal ticket (MAGETWO-48089) to track the progress of the issue

**Comment by KrystynaKabannyk** [comment]
Hello @adragus-inviqa, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.
