### ISSUE TITLE
Trying to upgrade version but getting error

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#2108]
Hello,
i am trying to upgrade version but getting below error:
 Class Magento\Customer\Model\Resource\Address\Attribute\Collection does not exist

**Comment by orlangur** [comment]
There was a backward-incompatible change which require re-install with clean DB, see https://github.com/magento/magento2/issues/2072#issuecomment-146909469 for more details.

**Comment by tanya-soroka** [comment]
@sunilit42 thank you for reporting the issues. Could you please confirm that recommendation from the #2072 help you?

**Comment by sunilit42** [comment]
every time drop table not possible, you need to make some script for that

**Comment by SerhiyShkolyarenko** [comment]
We delivered upgrade scripts.
@sunilit42 please try to pull these changes and run upgrade.

**Comment by okorshenko** [comment]
Closing. @sunilit42, please, let us know if you still have an issue
