### ISSUE TITLE
Current dev branch: static content deploy gives error: Undefined offset: 2>

### ISSUE THREAD

**Issue by RawPhunky** [magento/magento2#2111]
Installed current dev branch on Windows XAMPP.
Trying to deploy static content or set mage mode to production give error Undefined offset: 2>

None admin or front page works...

![image](https://cloud.githubusercontent.com/assets/2244332/10493413/ac17f7b8-72b9-11e5-9877-430395fc6440.png)

![image](https://cloud.githubusercontent.com/assets/2244332/10493548/73f9f98e-72ba-11e5-9fd7-3f2eb1e1220a.png)

**Comment by mazhalai** [comment]
@RawPhunky did you have a previous instance and you have updated to the latest code? Did you run `composer update` after getting the latest code?

**Comment by mazhalai** [comment]
@RawPhunky we do have a fix for it in ticket MAGETWO-43774. As a temporary solution you can replace line 51 with `self::$paths[$type][$componentName] = str_replace('\\', '/', $path);`  in  https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Component/ComponentRegistrar.php#L51

**Comment by ivanweiler** [comment]
Same problem here on Win, posted fix did the trick, thx.

**Comment by chaluvadiswamy** [comment]
@mazhalai , Me too have same issue (var 1.0.0 beta)

**Comment by mazhalai** [comment]
@chaluvadiswamy  there were some auto merge issues, we are working on getting the fix back in. In the mean time can you please refer to the temporary fix above?

**Comment by chaluvadiswamy** [comment]
@mazhalai i tried with that ,problem is there is Component Folder in following path  lib\internal\Magento\Framework\.
So i can't able to proceed with above fix,also i refered the following version 
 - 1.0.0 Beta
 - 0.74.0 Beta

**Comment by mazhalai** [comment]
@chaluvadiswamy are you on the `master` branch or `develop`? Also the component folder did not  exist in 0.74.0.Beta. Please try with 1.0.0-beta in the `develop` branch. Also, the fix is now merged again!

**Comment by chaluvadiswamy** [comment]
@mazhalai , thanks for the update .Actually i downloaded 1.0.0-beta  it from the following link 
https://github.com/magento/magento2/releases/tag/1.0.0-beta

**Comment by mazhalai** [comment]
@chaluvadiswamy that should be the stable `master` branch. Please try with the latest `develop` branch

**Comment by chaluvadiswamy** [comment]
@mazhalai Thanks for the update.

**Comment by mazhalai** [comment]
Closing since this has been resolved.
