### ISSUE TITLE
Allow installation of GitHub branches via Composer

### ISSUE THREAD

**Issue by amenk** [magento/magento2#2112]
Please allow installation from the GitHub repository via Composer

Benefits: 

* enables installation of arbitrary branches, for example dev-develop
* enables installation of any forks via Composer aliasing
* allows `composer install --prefer-source` with having access to the Git -> So it is easier to create Pull Requests

**Comment by alankent** [comment]
Hi. We have thought about this a number of times internally, but the only way I know how to achieve this is to have one repository per module (per composer package). We are not going to do this for now. Have a read of http://alankent.me/2015/10/02/magento-2-version-numbering-update/ for more information.

The problem is Composer assumes one repo per composer package. Magento modules don't follow this pattern for now (its all in one repo). So I don't think it is technically possible without a major restructuring of the git repo.

**Comment by kandy** [comment]
Maybe best way to improve developer experience is improve composer and add support of multi module repository

**Comment by amenk** [comment]
What would be so wrong about splitting the repo up to it's modules?
Then also there would be separate issue trackers and every thing is well ordered. 
There could be proper git tags per composer version.

There still could be a main repo to gather not yet categorized issues.

The splitting should be possible using git filter-branch retaining the commit data.

The splitting could be done with the composer-version update.

Please consider.

**Comment by Vinai** [comment]
Having modules in separate repositories adds quite a bit of management overhead in my experiences. 
For example, assume we are refactoring the `\Magento\Framework\App\ActionInterface`.
If all implementations are in the project, PHPStorm can easily do most signature changes. If the modules are in separate repositories, things get more complicated. If all modules are checked out under vendor, it wouldn't be so hard to have a script commit and push each one. But then that probably would also require opening a ticket for each one to get a issue number, check out a new appropriately named branch, commit and push, send a PR etc (depending on the internal processes that I don't know).
Sure it is technically possible, but from my experience it would probably add a lot of overhead and also delay the project.
Once the core has become more stable it might be a better time to reconsider.

**Comment by daim2k5** [comment]
@Vinai :+1:

**Comment by amenk** [comment]
PhpStorm actually has pretty good multi-git functionalities.

**Comment by Vinai** [comment]
I have to admit I might be totally talking out of my backend here, as I really have no idea about the internal processes of the core team. The above are just a bunch of assumptions based on past projects with a multitude of clients.
I haven't found PHPStorm can properly take into account all business requirements in regards to multi-git projects, but of course I might be totally mistaken there, too.

**Comment by orlangur** [comment]
@alankent,
> So I don't think it is technically possible without a major restructuring of the git repo.

It's pretty easy.

@amenk,
> Then also there would be separate issue trackers and every thing is well ordered. 

Unnecessary overhead as to me, at least till the moment Magento 2 will consist of loosely coupled components.

@Vinai,
> Having modules in separate repositories adds quite a bit of management overhead in my experiences. 

No overhead at all if done properly. Currently there is a lot of overhead already with separate CE/EE/zf1/sample-data/etc repos. It could be avoided.

### Solution
There is no need to reinvent the wheel. [Git subtree](http://stackoverflow.com/a/17864475) does the job pretty well.

If you look into https://github.com/symfony and https://github.com/zendframework you'll see they have both main ([monolithic](http://gregoryszorc.com/blog/2014/09/09/on-monolithic-repositories/)) repository with all modules and also one repository per each module. The difference between ZF2 and Symfony multi-repository approaches is that ZF2 accepts PRs and issues per-component while Symfony not, the so-called "[READ-ONLY] Subtree split".

So, https://github.com/magento/magento2/ repository should just co-exist with additional repositories per each component which are just a subtree split. Mandatory components, like https://github.com/magento/zf1, would be better placed inside main repository. Issues and PRs could be not assumed for separate components at all, assumed for all or assumed only for some of them.

**Comment by Vinai** [comment]
Thanks @orlangur, I haven't thought or having read only repositories using `git subtree`. That makes it a lot easier.
From a quick try, the master and the develop branches have to be split independently for each module and both have to be pulled into the new repository for each module.
The whole process would have to be automated so that the module repositories are updated on each push.
I would consider the infrastructure still fair bit of work, even though none of the complicated kind.

**Comment by amenk** [comment]
Sounds very interesting. Why do the branches have to be split separately? How do Symfony and Send handle this?

**Comment by Vinai** [comment]
I didn't spend a lot of time on it, but it looks like git subtree extracts a folder of the current branch into a new branch. So for example "take `app/code/Magento/Theme` and put only those files into the new branch `magento-module-theme`. That new branch only seems to include the commits of the one branch from which I made the split.
After splitting both the master and develop into `module-master` and `module-develop` branches, both can be pulled into the new repository as the `master` and `develop` branch respectively. So just a little more to script.
Maybe git-subtree has a way to split a folder tree in several branches, but I didn't spend the time to fully research after the individual split and pull worked out.

**Comment by orlangur** [comment]
> From a quick try, the master and the develop branches have to be split independently for each module and both have to be pulled into the new repository for each module.

Yes, initial preparation will require some cycle of work. After that any push to main repository to whatever branch is just reflected in dependent component repositories.

**Comment by amenk** [comment]
I pinged @fabpot on twitter https://twitter.com/s3lf/status/654641466317369344 - maybe Magento could just use the Symfony script?

**Comment by alankent** [comment]
We have been looking at what other projects do, and we may do it at some time. We have also discussed the one repo vs many a number of times internally. It is just not on the short term roadmap - we are going to get to GA, get a bit more practical experience, then move on once we have more feedback. There is lots of other stuff to do in the mean time.

So this is not "no", just "not yet".

**Comment by amenk** [comment]
Alright then. Thanks for the productive discussion.

**Comment by amenk** [comment]
I am trying to make such a split at https://github.com/m2split - let's see how it goes.

**Comment by daim2k5** [comment]
@amenk thanks for your nice module. I close the ticket for know, if you are uncomfortable with my decision feel free to reopen.

**Comment by amenk** [comment]
I actually stopped working on that, because I was hoping that Magento hosts such a split themselve
