### ISSUE TITLE
[Suggestion] REST API: Consistent naming of search parameters

### ISSUE THREAD

**Issue by thomasnordkvist** [magento/magento2#2116]
It would be nice if all rest call parameters to \Magento\Framework\Api\SearchCriteria would be named the same in all places.

Right now it's searchCriteria[][][][][] in some places and criteria[][][][][] on others.

After a quick (not complete) check it seems like criteria is used in the sales module, and the rest of the places use searchCriteria.

/Thomas

**Comment by choukalos** [comment]
Logged as bug, Internal ticket:  MAGETWO-44134

**Comment by NadiyaS** [comment]
Hi @thomasnordkvist ,
fix was delivered to mainline. Please see [3e9a74f](https://github.com/magento/magento2/commit/3e9a74f763fe8e4b4acac0bf3258844385a6b22c)

**Comment by thomasnordkvist** [comment]
Great @NadiyaS !
I'll do an update and test this soon.
