### ISSUE TITLE
Mincicart show 1 product but cart is empty

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2118]
I tested this on Magento ver. 1.0.0-beta
1. I logged in to my account
2. I added 1 product to the cart
3. I went to the checkout
3. I refreshed the browser on checkout on step 2 (review & payments)
4. I was redirected tot the shopping cart (stating that the shopping cart is empty) but the mnicart is still showing 1 item in the basket (see screenshot).

Note that this problem doesn't occur every time I tried to reproduce it
![2015-10-15_11h37_49](https://cloud.githubusercontent.com/assets/13572447/10510400/1156cb1c-7333-11e5-8994-055415ac9fa7.png)

**Comment by okorshenko** [comment]
@SidneyBilliet thank you for reporting the issue. This issues already fixed in develop branch. In master branch this fix will available with Magento 2  GA release.
