### ISSUE TITLE
Checkout as guest Intraunion Tax calculation

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2119]
Tested on Magento ver. 1.0.0-beta

For intra union tax EU regulation I have enabled Automatic Assignment to Customer Group
Default group = Retailer
Group for Valid VAT ID - Intra-Union =  Valid VAT Customer group

I have two tax rules
Tax Rule 1: Customer With VAT 21 = Customer tax class: Customer with VAT and Product Tax class = taxable goods 
Tax rule 2: Retail Customer 21 = Customer tax class: Retail Customer and and Product Tax class = taxable goods 

Tax zones and rates:
Belgium: state=* Zipcode=* Rate=21
Netherlands: state=* Zipcode=* Rate=21

Tax calculation is set to Billing address

Now logic says whether I am From Belgium or The Netherlands I will pay 21% tax on each product.
OK so Far.

However when adding a Valid VAT ID when Billing address=The Netherlands I would be placed in the customer Group "Valid VAT Customer group" --> This contains NO rate for The Netherlands so would not be charged VAT.
OK so Far.

Now:
1. I add a product of 121 EURO excl. tax to the cart
2. I go to checkout (as guest)
at this point: Cart Subtotal € 121,00
Shipping 	Not yet calculated
Tax 	Not yet calculated
3. I fill in SHIPPING ADDRESS --> I Use an address in the Netherlands
4. I ADD a VALID VAT Number
5. I CLICK NEXT (at this time tax will be calculated)
at this point: Cart Subtotal € 121,00
Shipping 	€ 0.00 Flat Rate Fixed
Tax 	€ 25.41
![2015-10-15_14h11_26](https://cloud.githubusercontent.com/assets/13572447/10513274/c4fe843a-7346-11e5-8df6-bba8bb65f6a3.png)
NOTE that I am paying € 25.41 tax (but I entered a VALID VAT ID)
6. I  place the order

On the order confirmation e-mail you can see that I am NOT Paying tax. 
![2015-10-15_14h15_59](https://cloud.githubusercontent.com/assets/13572447/10513359/64e04a24-7347-11e5-80c9-934f4e7e5ee9.png)
Which is normal (I entered a valid VAT id, so according to intraunion tax regulation (i was taxed according to the Customer with VAT group, which contains no rate for the Netherlands, so I am not charged tax). This works just fine. 

However I would suspect that During step 5 of my checkout process (above), when the tax calculation is done, that it would be clear in that step (before placing the order) that I will NOT be charged VAT.

Kind regards,

**Comment by mazhalai** [comment]
@SidneyBilliet Thank you for reporting, we have created a ticket for it: MAGETWO-44122

**Comment by mazhalai** [comment]
@SidneyBilliet this has been fixed in the 2.0.0-rc. Closing this ticket. If you still have issues, please reopen or create a new ticket.

**Comment by Styopchik** [comment]
Still have same issue on 2.1.2. Customer with VALID VAT_ID  in catalog gets prices without tax (correct), but in checkout TAXes are calculated, and in order TAXES ARE CALCULATED

**Comment by EnricoMalavasi** [comment]
Hi everyone,

referred to this problem, is there Magento 2.1.6 checking the tax rules for a guest user? Specifically, if a guest user inserts the correct European VAT code, can it be associated with a tax class in which he does not pay the VAT?
