### ISSUE TITLE
sample data installation guide is out of date

### ISSUE THREAD

**Issue by oshanrube** [magento/magento2#2120]
i was following the guide given [here](http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data.html). but it seems to be out of date for 2 reasons
* installing the wizard does not install the sample data
* theres no such command `sampledata:install admin` and `sampledata:deploy` loads non-existing repos such as `magento/module-downloadable-sample-data`. which are shown [here](http://magento.stackexchange.com/questions/85753/magento-2-uninstallable-set-of-packages-when-deploying-magento-sample-data?answertab=oldest#tab-top)

**Comment by xcomSteveJohnson** [comment]
Thanks for letting us know. From the standpoint of documentation, we're aware of this. If you follow us on Twitter, we'll announce when the instructions are updated.

**Comment by ghost** [comment]
This should be fixed now. The sample data installation instructions have been updated.

http://devdocs.magento.com/guides/v2.1/install-gde/install/web/install-web-sample-data.html

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
