### ISSUE TITLE
Backend Catalog: Change status of products does not work

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#2123]
It is not the same as https://github.com/magento/magento2/issues/1559
Because the fix is already in there and I am on the develop branch. 

If you click on "Change status", nothing happens. There is some javascript being executed in tree-massactions.js, but I don't know what does not work there.

**Comment by tanya-soroka** [comment]
@sydekumf thanks for reporting. we was not able to reproduce this issue on new version. Please wait for the new version.
