### ISSUE TITLE
After Successful installation Admin stuck to login box without fields

### ISSUE THREAD

**Issue by MageArray** [magento/magento2#2125]
i have successfully installed magento2 on my local server. also i have tried with another system too but it shows just white box in admin and no fields to login in to admin as well.

here is screenshots.
Back End:
![image](https://cloud.githubusercontent.com/assets/15083969/10535446/a72207a6-7400-11e5-8afd-ee284b4e0ed9.png)

Front End:
![image](https://cloud.githubusercontent.com/assets/15083969/10535416/72f7c588-7400-11e5-9efb-ac434e95934b.png)

**Comment by dfediuk** [comment]
It is broken from the past Friday.
https://github.com/magento/magento2/issues/2077

**Comment by sunilit42** [comment]
Download master version and check it.

**Comment by mazhalai** [comment]
@MageArray do you have any errors on browser? Can you please give more details about your environment? Also, what mode are you operating in?

**Comment by serkia** [comment]
Dmitry code in issue #2077 fixes the template.

Try it out. I have the same problem with the develop branch, but haven't
had time to unlock the account, of that is an issue, as was suggested lower
in the conversation

**Comment by aravinth512** [comment]
Me too, having the same problem

**Comment by okorshenko** [comment]
@MageArray, Could you please, check latest version?
