### ISSUE TITLE
error while setup:upgrade

### ISSUE THREAD

**Issue by Manashvi** [magento/magento2#2126]
I downloaded the stable magento version from here https://github.com/magento/magento2/archive/master.zip.

Now the issue comes when i try to update the setup after installing a module.
I am trying to upgrade the setup from the magento root directory using :- 
php/bin magento setup:upgrade

But i get this error 
Autoload error: An abstract factory could not create an instance of magentosetup
consolecommandmoduleuninstallcommand(alias: Magento\Setup\Console\Command\Module
UninstallCommand).

**Comment by Vinai** [comment]
Did you run `composer install` after unpacking the ZIP archive?

**Comment by Manashvi** [comment]
Yes i had. Now when i run `composer install` from the magento root folder. i get below issue : 

Warning: This development build of composer is over 60 days old. It is recommend
ed to update it by running "C:\ProgramData\ComposerSetup\bin\composer.phar self-
update" to get the latest version.



  [RuntimeException]
  The lock file does not contain require-dev information, run install with th
  e --no-dev option or run update to install those packages.



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [pac
kages1] ... [packagesN]

**Comment by Vinai** [comment]
I would suggest updating composer as the message says and then trying again with with `update` instead of install.
I must admit, so far I have never installed using the ZIP archive download, only a git clone or the repository, but I guess it should work the same.

**Comment by Manashvi** [comment]
can you suggest how to update composer ?

**Comment by Vinai** [comment]
`composer self-update`
See https://getcomposer.org/doc/03-cli.md#self-update

**Comment by mazhalai** [comment]
@Manashvi `composer self-update`

**Comment by Manashvi** [comment]
i have updated the composer successfully.! still the same issue continues. PS i would like to mention here that i tried to disable a module and then this error occured,

**Comment by Vinai** [comment]
How long ago did you download the ZIP from github?

**Comment by mazhalai** [comment]
@Manashvi can you please the absolute last error in the stack trace?

**Comment by Flyingmana** [comment]
Some Comments.

The original Error had probably nothing to do with a failed update of dependencies. Its just a bad error message which can be fixed with the patch in https://github.com/magento/magento2/pull/1323

Then:
```
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "C:\ProgramData\ComposerSetup\bin\composer.phar self-update" to get the latest version.
```
thats a regular error you probably get every two months, just follow the advice and it goes away for another 60 days :)

```
[RuntimeException]
The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.
```

thats also an easy one, Composer diferentiates between --dev and --no-dev installs. The composer.lock stores all needed dependency states to have a reproducable setup.
Magento did not provide a --dev state it seems, so follow the advice and run the install again with `--no-dev`.

A hint @Vinai 
***never!*** run `composer update` in context of magento2, it will cause a non tested developer setup and waste a lot of time into debugging.

**Comment by Vinai** [comment]
@Flyingmana I run `composer update` after every `git pull`

**Comment by Flyingmana** [comment]
@Vinai yeah thats wrong, you have to run `composer install`, it then looks for changes in the composer.lock and applies them.

`composer update` ignores the composer.lock and generates a new one

**Comment by Vinai** [comment]
Well, that is exactly what I want :)
In my case additional dependencies are added after the git pull.
