### ISSUE TITLE
Product detail page issues

### ISSUE THREAD

**Issue by kathir26** [magento/magento2#2127]
When i opened the review by product in admin panel it throws an error as mentioned below,

Uncaught TypeError: Cannot read property 'select' of undefined  in grid.js at line 280

var dataElements = $(this.containerId+this.tableSufix).down('tbody').select('input', 'select');

**Comment by mbrinton01** [comment]
@kathir26 does this happen when you click on Marketing > Reviews in the admin UI?  Have you installed sample data?

**Comment by kathir26** [comment]
@mbrinton01 When i click Reports > Review by products it throws the error but it shows one records found but no listing and there is an error what i had mentioned in my previous comment.

**Comment by kathir26** [comment]
@mbrinton01 
This is the error screenshot. Check it.
https://cloud.githubusercontent.com/assets/4454720/10557439/de0f8a2a-74ca-11e5-948c-790873e33923.png

**Comment by kathir26** [comment]
@mbrinton01 

I found one more error in bundle product front end while adding product it throws js error but product is added to cart.

Uncaught Error: Syntax error, unrecognized expression: # option:selected in jquery.js 1471 

Sizzle.error = function( msg ) {
	throw new Error( "Syntax error, unrecognized expression: " + msg );
};

**Comment by kathir26** [comment]
@mbrinton01 

One more issue after i added the bundle product it is not showing after i click the cart icon in header and also proceed to checkout also not working.
![fireshot capture 2 - home page - http___27 124 25 171_magento2beta_](https://cloud.githubusercontent.com/assets/4454720/10557929/e4bc4dac-74db-11e5-8894-cdf4e2b10e33.png)

**Comment by kathir26** [comment]
@mbrinton01 

After uploaded the video it not working in front end detail page and also popup(fullscreen gallery) of image is also not working i.e. when you click the image it will show the popup but it is not working for product which have video in it. 

This error is occured
 pub/static/frontend/Magento/luma/en_US/Magento_ProductVideo/js/fotorama-add-video-events.js:39 Uncaught TypeError: srchref.search.split is not a function 

 function _getYoutubeId(srchref) {
            var srcid = srchref.search.split('v=')[1]; // Error line
    .....
  }
The below screenshot gallery popup is working only for products which doesn't have videos. If the product has videos it is not working and throwing the above error.

![fireshot capture 3 - shirts - http___27 124 25 171_magento2beta_shirts html](https://cloud.githubusercontent.com/assets/4454720/10558153/71c69f8e-74e3-11e5-9896-099a7673df0c.png)

**Comment by anton-huz** [comment]
Hi @kathir26 ,
We will investigate issue more deeply under internal ticket MAGETWO-55453.

**Comment by magento-engcom-team** [comment]
@kathir26, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
