### ISSUE TITLE
Magento2 Installation Issue

### ISSUE THREAD

**Issue by sankaran-consultant** [magento/magento2#2129]
1) Magento 2 installation show Integrity error on table "store_website" table.

2) 
Module 'Magento_Widget':
Installing schema.. 
[ERROR] exception 'Zend_Db_Exception' with message 'Column "code" does not exist in table "widget".' in C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php:964 Stack trace: #0 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\app\code\Magento\Widget\Setup\InstallSchema.php(102): Magento\Framework\DB\Adapter\Pdo\Mysql->changeColumn('widget', 'code', 'widget_code', Array) #1 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\setup\src\Magento\Setup\Model\Installer.php(798): Magento\Widget\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext)) #2 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\setup\src\Magento\Setup\Model\Installer.php(732): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema') #3 [internal function]: Magento\Setup\Model\Installer->installSchema() #4 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\setup\src\Magento\Setup\Model\Installer.php(331): call_user_func_array(Array, Array) #5 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\setup\src\Magento\Setup\Controller\Install.php(97): Magento\Setup\Model\Installer->install(Array) #6 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #8 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #9 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #10 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #11 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #13 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #14 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #15 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #16 C:\Users\000798\wamp2.5\www\projects\magento\magento2-develop\setup\index.php(31): Zend\Mvc\Application->run() #17 {main}

**Comment by mazhalai** [comment]
@sankaran-consultant do you have a previous installation of magento? Please use `setup:upgrade` if you want to keep your instance. Else, please run `setup:uninstall` to clear everything and start over.
