### ISSUE TITLE
php readiness check fail

### ISSUE THREAD

**Issue by dcthelord** [magento/magento2#2131]
Hi, I'm facing the following issue the installation:
In the readiness check, the setup fails all 3 php tests. It says "Your PHP version is . The required PHP version is . " (no version number shows). See screenshots below.

I'm using the latest xampp. php version (5.6.12) shows correctly in phpinfo.php

I'm installing in xampp (win 7) with sample data. 'composer update' gives no error.

Screenshots:
![01 readiness-check](https://cloud.githubusercontent.com/assets/15167154/10558277/ca4dfefa-74e7-11e5-9ddd-8fedae7409bb.jpg)
![02 phpinfo](https://cloud.githubusercontent.com/assets/15167154/10558278/ca5bb9dc-74e7-11e5-9ac6-029782bb71e5.jpg)
![03 composer](https://cloud.githubusercontent.com/assets/15167154/10558279/ca6677dc-74e7-11e5-91e3-cd181232d5ee.jpg)

**Comment by mazhalai** [comment]
@dcthelord do you have the latest from the `develop` branch?

**Comment by dcthelord** [comment]
@mazhalai : Yes, I do. It was synced the same day I posted the issue. I also synced it right now. Still, same issue.

**Comment by mazhalai** [comment]
@dcthelord, develop has the latest code. On your browser, there should be an option for [developer tools](http://www.wickedlysmart.com/hfjsconsole/).  Can you please enable that and post a screen-shot of the "network" tab.

**Comment by dcthelord** [comment]
@mazhalai, Is this what is needed?
01 is regular. 02 is with cache disabled.

Also, for some reason, during the screenshot runs, the check was getting stuck on 1 or the other checks. Happened a few times before I got a clean run. 

![01](https://cloud.githubusercontent.com/assets/15167154/10592381/5a8f5b92-76d9-11e5-8727-b69e08554e05.jpg)
![02](https://cloud.githubusercontent.com/assets/15167154/10592382/5aa31c9a-76d9-11e5-945c-0490bdd6bc8c.jpg)

**Comment by mazhalai** [comment]
@dcthelord can you post the json response?

**Comment by dcthelord** [comment]
@mazhalai I'm sorry, but I'm not sure how to do that. 
I googled it a bit and found I have to enter the following:
public function indexAction()
{
        $this->getResponse()->clearHeaders()->setHeader('Content-type','application/json',true);
        $this->getResponse()->setBody(json_encode($response));
}

Is this code correct? And where should I enter this code? In the console? And how to extract the response?

I'm sorry for asking this type of question in developer forum, but I have very basic programming knowledge.

**Comment by eddielau** [comment]
@dcthelord Hi. If you click on any item on the list under the "network" tab you will something like this:
![screen shot 2015-10-20 at 2 42 15 pm](https://cloud.githubusercontent.com/assets/5254230/10618988/c91a6a8e-7738-11e5-81b9-9c7fbd2225ed.png)
Please click on the "Response" tab then you will see the JSON response.

**Comment by dcthelord** [comment]
@eddielau : Thank you so much.
The 3 php tabs had the same warning:
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />

The json responses are:
php-version: {"responseType":"success","data":{"required":"~5.5.0|~5.6.0|~7.0.0","current":"5.6.12"}}
php-settings: {"responseType":"success","data":[]}
php-extensions: {"responseType":"success","data":{"required":["ctype","gd","spl","dom","simplexml","mcrypt","hash","curl","iconv","intl","xsl","mbstring"],"missing":[]}}


The php.ini file in the main folder is not there. sample file is there. If I'm not mistaken, doesn't it get created during this setup?

**Comment by mazhalai** [comment]
@dcthelord that helps, please follow instructions in the deprecated section, edit your `php.ini` and set `always_populate_raw_post_data` to `-1`. We do have an internal ticket MAGETWO-40303 for this issue

**Comment by dcthelord** [comment]
@mazhalai @eddielau : Thank you so much guys. This solved the problem.

**Comment by jernejh** [comment]
Hi everyone.

I am using XAMPP 5.6.15 under Windows (Both Windows 2012 R2 Server and WIndows 10) and have the same problem for upgrading magento 2.0.2 to 2.0.4

Setting always_populate_raw_post_data to -1 in php.ini did not resolve my problem. 

I installed magento using command line
- call composer create-project
- php bin\magento setup:install
- php bin\magento deploy:mode:set developer

I get the following readiness check fails when upgrading in the backend:

- Check Cron Scripts, 
- PHP Version Check (Your PHP version is . The required PHP version is .), 
- PHP Extensions Check (missing PHP extensions.)

Regarding Cron Scripts - I wonder how to override this fail, since there are no cron scripts available in Windows?

Composer update and php bin\magento setup:upgrade works without errors (I properly set write permissions to var and pub folders).

Thank you.

**Comment by thomaszoeger** [comment]
Just write into your composer.json file, inside "require" section an required php version like:
 "php": "~7.1.0",

**Comment by DanielRuf** [comment]
> Just write into your composer.json file, inside "require" section an required php version like:
> "php": "~7.1.0",

You replied to a very old issue which was already closed ;)

**Comment by ostap-mykhaylyak** [comment]
Follow this guide: [Readiness Check Failure in Magento 2
](https://ostap.dev/readiness-check-failure-magento-2/)
