### ISSUE TITLE
Shipping Method Pickup is missing in the Backend

### ISSUE THREAD

**Issue by amenk** [magento/magento2#2132]
I can't activate the PickUp method in the backend.

I think it is missing in

https://github.com/magento/magento2/blob/develop/app/code/Magento/OfflineShipping/etc/adminhtml/system.xml

**Comment by tanya-soroka** [comment]
@amenk thanks for the contribution of the new shipping method for the Magento2. I assignee this implementation to Ilya.

**Comment by amansilla** [comment]
I'm experiencing the same issue in my case using Magento EE 2.1.1. Is there any update?

**Comment by charmeleon-zz** [comment]
Also need in store pickup and it's not available in Magento CE 2.1.7

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Shipping-Method-Pickup-is-missing-in-the-Backend/idi-p/73608).
