### ISSUE TITLE
Tax zones import csv limitation

### ISSUE THREAD

**Issue by nallias** [magento/magento2#21366]
### Preconditions (*)

1. magento 2.2.0
2. no additional module about V.A.T. managment

### Steps to reproduce (*)

1. Administration panel
2. Stores tab
3. Taxes > Tax rules
4. add or edit one tax rule
5. at the bottom of "Additional Settings", upload a 200+ lines csv

### Expected result (*)

1. All correct lines are uploaded (not necessary every lines)
2. If necessary, error message

### Actual result (*)

1. at the top of the page: "One of the countries has invalid code."
2. i the tax rate field, 200 of my lines are shown
3. Button "export tax rates" shows a csv truncated after the 200th line.

Additional experiment: 
1. if I shuffle the lines of the csv, 
2. clean some of the uploaded ones (lots of clics)
3. still the first 200 lines **of the new csv** are loaded on magento : it is not my 201th line that is bugged but the import process that stops after the 200th.

Questions:
- is there any hard limitation for this 200 limit of tax zones?
- if yes, why?
- can I use a wildcard in the "country" field (that would save me 150 lines out of 270)
- is there any detailled log of "One of the countries has invalid code" indicating which line(s)?

All suggestions are welcome, tell me if you want to see my huge csv (and how to show it here).
Topic linked to https://magento.stackexchange.com/questions/262702/tax-zones-limitation

**Comment by magento-engcom-team** [comment]
Hi @nallias. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nallias do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nallias** [comment]
> Hi @nallias. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @nallias do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no

Indeed, I reproduced it on a vanilla magento 2.2.0
The environment (further from magento 2.2.0) is a Linux 4.4.0-98-generic Ubuntu.
If you need any more precision, tell me.

**Comment by magento-engcom-team** [comment]
Hi @nallias. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nallias, here is your [Magento instance](https://i-21366-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21366-2-3-develop.instances.magento-community.engineering/admin](https://i-21366-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by priti2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  priti@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (264/250 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-16.smtp.github.com ([192.30.254.199]:41389)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1gwUhN-000LAp-Ug
	for priti@2jcommerce.in; Wed, 20 Feb 2019 16:26:19 +0000
Date: Wed, 20 Feb 2019 08:25:36 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1550679936;
	bh=5DYKd4+GmVt3g29WD65jIhFJgdzngd3Oz1aACv/yHOg=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=k7npgdGCfbDpO9ZfX7AOzDo2ZrAt8g71MAM+64EMWN786soqT8+/Zj8DgVA72rNXL
	 WlVqcy3aYiBYAnmBrm3i/1szJysiW0ZzL/OVA2In6bG/f1TNFHFe5Fv7iI377wYtzL
	 NaHgEUrdAdwuFAnCdipQOx7pc6D8ERmYU/zpNfYA=

**Comment by nilesh2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  nilesh@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (264/250 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:60960)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-306a-nilesh=2jcommerce.in@sgmail.github.com>)
	id 1gwUhO-000LAn-0n
	for nilesh@2jcommerce.in; Wed, 20 Feb 2019 16:26:20 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Gwf1Aj2NuSP/u9nH03U7kqiXfio=; b=WH4Slo5K8eofvTOU
	/aqRec5AENmnITcolNNXj5udh3qxV+SMHP8gB3XYAZlH4717K1EBVxgMuPPr3dnK
	3t8bGqSSbVtKwUoKmoNFr2jT1rCFdOYeieaQUy9qHooCipxjIViJHjG8Azd9LVwS
	yZ8t8lFXS1eBjZaSPKmI+NaMmQU=
Received: by filter1205p1las1.sendgrid.net with SMTP id filter1205p1las1-12326-5C6D7F80-12
        2019-02-20 16:25:36.497186656 +0000 UTC m=+158704.589015622
Received: from github-lowworker-fc273f0.cp1-iad.github.net (unknown [192.30.252.33])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id P-H9WS7mQ96MVga-aNktYw
	for <nilesh@2jcommerce.in>; Wed, 20 Feb 2019 16:25:36.346 +0000 (UTC)
Received: from github.com (localhost [127.0.0.1])
	by github-lowworker-fc273f0.cp1-iad.github.net (Postfix) with ESMTP id 529A3C0AD1
	for <nilesh@2jcommerce.in>; Wed, 20 Feb 2019 08:25:36 -0800 (PST)
Date: Wed, 20 Feb 2019 16:25:36 +0000 (UTC)

**Comment by ajay2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ajay@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (256/250 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:14791)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-4d95-ajay=2jcommerce.in@sgmail.github.com>)
	id 1gwUhO-000LAo-CI
	for ajay@2jcommerce.in; Wed, 20 Feb 2019 16:26:21 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=V9W5b6wPq6ZxVYKy2BHzP1j/6Dk=; b=QVGJApOtdlrJfYof
	JGByxmjmSJasQ9MANiUNys9CWzmRZjcEvTpJy6X+zHbvrQFMRs6tKQqarszCALqS
	6YLzR5uCJRsom4yK5jOezoXoZOjuY/Aqv/pTFpeILpoA7fb+5EDhgn2vLWupVbn7
	5HxNuBtag0b8hZi57Gc49dHliIY=
Received: by filter1199p1las1.sendgrid.net with SMTP id filter1199p1las1-28080-5C6D7F80-D
        2019-02-20 16:25:36.311550642 +0000 UTC m=+162356.627845859
Received: from github-lowworker-fc273f0.cp1-iad.github.net (unknown [192.30.252.33])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id QWrLD2afTaGOYLRVp_rSVQ
	for <ajay@2jcommerce.in>; Wed, 20 Feb 2019 16:25:36.209 +0000 (UTC)
Received: from github.com (localhost [127.0.0.1])
	by github-lowworker-fc273f0.cp1-iad.github.net (Postfix) with ESMTP id 30CE5C0AD1
	for <ajay@2jcommerce.in>; Wed, 20 Feb 2019 08:25:36 -0800 (PST)
Date: Wed, 20 Feb 2019 16:25:36 +0000 (UTC)

**Comment by nainesh2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  nainesh@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (258/250 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-6.smtp.github.com ([192.30.252.197]:60443)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1gwUhN-000LAg-9T
	for nainesh@2jcommerce.in; Wed, 20 Feb 2019 16:26:18 +0000
Date: Wed, 20 Feb 2019 08:25:36 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1550679936;
	bh=TXTG6bROmuqu/Bi9WjZtM325505ro/tIP1E7mJ90xM0=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=t4yEvIgMkFggLbVz/LKPeEPCnhmOgtcDU3QtC29qe244Xk/EY2XFrLQ01Y0Y9y4do
	 xOrCcvMrJnLyAcgJS9U4SE1YTXVd1Uqu8leszsYOy8e/aQ1vivtH1uNpWmO6BT1cGN
	 Wuur8QxMtuGTnG4UJWEA3nYOdVnrl4vmYXKoApHE=

**Comment by amol2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  amol@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (257/250 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:22708)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d057-amol=2jcommerce.in@sgmail.github.com>)
	id 1gwUhO-000LAm-1I
	for amol@2jcommerce.in; Wed, 20 Feb 2019 16:26:20 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=6nr1HLF+K9n9WkDz4cKz2NhJf1Q=; b=jxOegdrDsFD27XSN
	PBGZ16gllucr9iigglbUAQCFsu1Qeq04+ELzLzpnpZBqVL9VZwZJHLHzIoM1pogt
	Wc+QQEsj0rgQXkC7dqSScHHqxe0LNg3irpWH+g5pE2dz9dNX824SYRnpI+tV9/Or
	wmgeGDG7JE0vISClWJfLI1A7hwM=
Received: by filter1148p1las1.sendgrid.net with SMTP id filter1148p1las1-16728-5C6D7F80-10
        2019-02-20 16:25:36.369712035 +0000 UTC m=+1026907.511719975
Received: from github-lowworker-fc273f0.cp1-iad.github.net (unknown [192.30.252.33])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id QNnXo-LKRDev2dS1I8l5XQ
	for <amol@2jcommerce.in>; Wed, 20 Feb 2019 16:25:36.269 +0000 (UTC)
Received: from github.com (localhost [127.0.0.1])
	by github-lowworker-fc273f0.cp1-iad.github.net (Postfix) with ESMTP id 3F87FC0B66
	for <amol@2jcommerce.in>; Wed, 20 Feb 2019 08:25:36 -0800 (PST)
Date: Wed, 20 Feb 2019 16:25:36 +0000 (UTC)

**Comment by nallias** [comment]
> Hi @nallias, here is your [Magento instance](https://i-21366-2-3-develop.instances.magento-community.engineering).
> Admin access: https://i-21366-2-3-develop.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

Thanks. On your 2.3 the upload is impossible with my file "as is", I had to remove the Puerto Rico line (country code PR is refused)
Then, all my lines are uploaded.

This means that I shall abandon my 2.2.0 and attempt to migrate on 2.3?

Also, why do you refuse the 'PR' country code?
EDIT: according to https://github.com/magento/magento2/issues/8295 Puerto Rico is part of US

**Comment by nallias** [comment]
> > Hi @nallias, here is your [Magento instance](https://i-21366-2-3-develop.instances.magento-community.engineering).
> > Admin access: https://i-21366-2-3-develop.instances.magento-community.engineering/admin
> > Login: `admin` Password: `123123q`
> > Instance will be terminated in up to 3 hours.
> 
> Thanks. On your 2.3 the upload is impossible with my file "as is", I had to remove the Puerto Rico line (country code PR is refused)
> Then, all my lines are uploaded.
> 
> This means that I shall abandon my 2.2.0 and attempt to migrate on 2.3?
> Also, why do you refuse the 'PR' country code?

New attempt on my 2.2.0 with the file without the line for 'PR' : no error message.
Every lines are imported!
Many thanks @magento-engcom-team for the 2.3 instance that put me on track by detailing the error.

**Comment by nainesh2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  nainesh@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (252/250 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-3.smtp.github.com ([192.30.252.194]:34399)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1gwUgY-000L5B-T5
	for nainesh@2jcommerce.in; Wed, 20 Feb 2019 16:25:27 +0000
Date: Wed, 20 Feb 2019 08:24:45 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1550679885;
	bh=TpxIgQxEaMyazJsfzD/ytXmHUYviYRGpLudYciSffbE=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aJYRL3YlduK4AIOVu1iWABJBQpVZLFqj2a5TDK0/RwCzU4zA3XZGyK0zxPDw+ac3H
	 PHQvOKKyK6MMYjmBLiJlrESXrypbThly9+EgK5ZMEuxZUsEBFPhSmCyMrQ/nWLC4A3
	 q5r+IzYtyRxDh7SAJ2YiZMt6MEMDrw/9GeYCWe5k=
