### ISSUE TITLE
Configurable products

### ISSUE THREAD

**Issue by JosephMaxwell** [magento/magento2#2138]
Is there a way to assign already-created products to a configurable product? In Magento 1, this was possible by going into the configurable product and checking items in the grid that we wished to be associated. I am not seeing a way for this in Magento 2?

**Comment by pronto2000** [comment]
I've complained about that couple of times as well, but so far nobody seemed to care ...

**Comment by alankent** [comment]
"Not caring" is not the same as "has not reached a high enough level compared to all the other requests and features". The more people that raise it, the higher the priority it gets. So +1's on any request like this *do* make a difference.

**Comment by pronto2000** [comment]
Working on it. :) I've postponed my first M2 project couple of times because the state of configurable products and since GA is right around the corner I'm getting increasingly concerned. How come I've seen only two other people talk about it?

**Comment by kandy** [comment]
<img width="883" alt="screenshot 2015-10-19 23 09 09" src="https://cloud.githubusercontent.com/assets/100289/10589895/8ddd34b0-76b6-11e5-9a0b-df27a822f62f.png">

You can use "Choose a different Product" if you need select product for exists variation or use "Add Products Manually" to add product as new variation

**Comment by pronto2000** [comment]
This add product manually wasn't there when I checked it last time around (a handful of week ago). Cool, maybe somebody actually have been working on it ...

**Comment by tanya-soroka** [comment]
@pronto2000 configurable product in on the implementation for the last milestone, so we are adding feature by feature in each of the release.

All your comments and recommendations are really helpful. Thank you.

Can we close this ticket?

**Comment by pronto2000** [comment]
I'm good with this. @JosephMaxwell?

**Comment by tanya-soroka** [comment]
I am going to closed this ticket. Feel free to reopen if you have any questions.
