### ISSUE TITLE
Allow Guest Checkout and Require Customer To Be Logged In To Checkout

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2139]
Seems rather strange behavior.
CASE 1: When Allow Guest Checkout = NO

![2015-10-20_11h57_56](https://cloud.githubusercontent.com/assets/13572447/10604074/53c57e2e-7722-11e5-8836-9e31798fdf2a.png)
You simply get a message "Guest checkout is disabled." There is no suggestion to log-in or register?

![2015-10-20_12h00_28](https://cloud.githubusercontent.com/assets/13572447/10604061/413e3d04-7722-11e5-9d84-d631999a9a54.png)

CASE 2:Further more if you set "Require Customer To Be Logged In To Checkout" to NO

![2015-10-20_11h58_09](https://cloud.githubusercontent.com/assets/13572447/10604100/7b70fbb0-7722-11e5-96b0-32b204235b02.png)

Nothing changes at all?

You still get the same message and no suggestion to log-in or register.

![2015-10-20_12h00_28](https://cloud.githubusercontent.com/assets/13572447/10604148/bf848416-7722-11e5-9e54-dcd4bcfc53a2.png)

What is this setting suppose to do?

NOTE:
When clicking "Check Out with Multiple Addresses" 

CASE 1 shows
![2015-10-20_12h05_31](https://cloud.githubusercontent.com/assets/13572447/10604181/fc8bed90-7722-11e5-97a7-5cf58b9f029d.png)

CASE 2 shows 
![2015-10-20_12h05_31](https://cloud.githubusercontent.com/assets/13572447/10604181/fc8bed90-7722-11e5-97a7-5cf58b9f029d.png)

Still no difference at all for the setting "Require Customer To Be Logged In To Checkout" 

Kind regards,

**Comment by serkia** [comment]
+1 subtle but effective. A customer confused during checkout would lead to
abandoned carts

**Comment by choukalos** [comment]
Filed bug MAGETWO-44436; add links/notification to ask customer to login.

**Comment by ishakhsuvarov** [comment]
Closing this for now. Currently it is a know issue that if configuration settings that affect customer's private data is updated in Magento then customer's quotes need to be deleted to avoid unexpected behaviour.
Please feel free to reopen if you have any additional questions.

**Comment by gabriellecrossland** [comment]
Hi is there a resolution for this issue?

Still unable to check out as a guest

Thanks

**Comment by ch1oe** [comment]
Yes we're still experiencing issues with this. 

Can anyone help?

Thanks

**Comment by ishakhsuvarov** [comment]
@gabriellecrossland @ch1oe Do you use exactly the same configuration as displayed in the first post?

**Comment by ch1oe** [comment]
All sorted now thank you.

**Comment by maksek** [comment]
@ch1oe assuming we can close the issue?

**Comment by ch1oe** [comment]
Yes @maksek

**Comment by ludwig-gramberg** [comment]
i'm experiencing this too in magento 2.0.7
how was this resolved if at all?

as far as i can see it is not possible to allow an unregistered person to go straight to the checkout and being forced to create an account while ordering, which is exactly what the 2 options imply:
- allow guest checkout : no
- customer must log in to order : no

any help?

**Comment by viktordodev** [comment]
This is still present in the 2.12 version of magento.
If the ALLOW GUEST TO CHECKOUT is set to NO he cannot go to CHECKOUT page without login in.

**Comment by CreamyG31337** [comment]
This needs to be re-opened. There has to be a suggestion to log in or create an account. "Guest checkout is disabled" is a stupid message to display to a user.

**Comment by royvanos** [comment]
Clearing all cookies in my browser did the trick for me!

**Comment by shenmusam** [comment]
Yes we're still experiencing issues with this.
![image](https://user-images.githubusercontent.com/37282394/37818491-4322eda2-2eb5-11e8-98e0-67e3ec230d2e.png)
![image](https://user-images.githubusercontent.com/37282394/37818509-530f8270-2eb5-11e8-9b9e-ff647a832a9d.png)
@ishakhsuvarov
