### ISSUE TITLE
Product User Role can not add video link

### ISSUE THREAD

**Issue by odom** [magento/magento2#2140]
Hi Team, 

I just fresh clone your develop branch, I test with video it is awesome, and I can add, update all youtube link when I am login as Admin user. Then I create a Product Role I can add only Picture for video it is error 403 
admin/product_video/product_gallery/retrieveImage/key/9ea1e12a7613d27a51b6075742f6c58d1b17c9e3c86e4e22ffc1a824eaa155da/?isAjax=true 
and I look at Role Resources I can not find the Product Video.
Or I miss some configuration

Thanks, 
 Odom

**Comment by daim2k5** [comment]
@odom  Please let us know if you are still having this issue

**Comment by m0zziter** [comment]
I'm running 2.0.7 and am also receiving this error. 

One thing I noticed is that if the user's role has "All" resource access videos can be added no problem. However, if the role has "Custom" resource access with each resource checkbox selected the user will be unable to upload a video.

Is there some permission I can grant my users to allow them to upload videos in the meantime?
