### ISSUE TITLE
Manage stock on Product level --> Use Config Settings is never checked by default

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2141]
When creating a new product "Manage stock" on the advanced inventory tab is never checked as "Use Config Settings"

![2015-10-20_12h22_18](https://cloud.githubusercontent.com/assets/13572447/10604553/67a63426-7725-11e5-8c81-ac869e27cf59.png)

**Comment by tanya-soroka** [comment]
Internal ticket has been created MAGETWO-44432

**Comment by tanya-soroka** [comment]
Issue has been resolved. Thanks
