### ISSUE TITLE
Nginx root location configuration

### ISSUE THREAD

**Issue by ClementParis016** [magento/magento2#2142]
I'm trying to run a Magento 2 installation on Nginx alongside an Express.js app that uses Nginx as a proxy. I used the [sample Nginx configuration you provide](https://github.com/magento/magento2/wiki/Nginx-Configuration-Settings-and-Environment-Variables) but I can't get it to work.
My Express.js app is under the `/var/www` folder and works correctly, but I can't map correctly my Magento demo project which is located under `/mnt/storage/demo-magento2` to be accessible at `http://example.com/demos/demo-magento2`:

```nginx
upstream doc_engine_js {
   server 127.0.0.1:5858;
}

upstream fastcgi_backend {
   server unix:/var/run/php5-fpm.sock;
}

server {
   server_name example.com;
   access_log /var/www/logs/example.access.log;
   error_log /var/www/logs/example.error.log;

   root /var/www/;
   underscores_in_headers on;
   disable_symlinks off;

   location /docs/ {
      rewrite ^/docs/sandbox/?(.*)$ /$1?mode=sandbox break;
      rewrite ^/docs(.*) $1 break;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://doc_engine_js/;
      proxy_redirect off;
   }

   location /demos/demo-magento2/ {
     set $MAGE_ROOT /mnt/storage/demo-magento2/;
     set $MAGE_MODE developers;
     include /mnt/storage/demo-magento2/nginx.conf.sample;
   }
}
```

And Nginx's error.log keeps saying:
`2015/10/20 11:30:20 [emerg] 8887#0: location "/setup" is outside location "/demos/demo-magento2/" in /mnt/storage/demo-magento2/nginx.conf.sample:27`

What should I do?

**Comment by mazhalai** [comment]
@ClementParis016 that link for nginx sample is outdated. Please refer to a newer version [here](https://github.com/magento/magento2/blob/develop/nginx.conf.sample) also, there is an additional fix in this thread #2005 .

**Comment by ClementParis016** [comment]
Thanks, but I still have the same problem which is very specific to my environment.

**Comment by johnbendi** [comment]
@ClementParis016 please clarify what you are trying to do. Are you trying to get nginx to serve your express app and magento at the same time? If so you have to separate the two applications into their own nginx virtual host configurations. If you are still having problems after that, find a way to link here 
the nginx configuraton you are using for magento2.

**Comment by ClementParis016** [comment]
@johnbendi yes, I would like nginx to serve my Express app, acting as a proxy server, and also serve my Magento site at the same time.
I don't think virtual hosts are going to be helpful here, since I don't want to use two different domains, but just two different paths, `/docs/` and `/demos/demo-magento2/`.

> If you are still having problems after that, find a way to link here 
the nginx configuraton you are using for magento2.

I'm including [the exact same file](https://github.com/magento/magento2/blob/develop/nginx.conf.sample) that @mazhalai gave me, I didn't change anything in it.

**Comment by mazhalai** [comment]
@ClementParis016 but you do need to edit the sample file to customize it for your paths

**Comment by ClementParis016** [comment]
Ok then this is totally due to my environment, I will take a closer look at it but it's definitely not due to a mistake from the nGinx you provide, which means I can close the issue. Thanks for your help ;)
