### ISSUE TITLE
Setup script EavSetup - is_visible_on_front and visible_on_front

### ISSUE THREAD

**Issue by rodrigozulu** [magento/magento2#2143]
Hi,

The visible on front definition appears in different maners in addAttribute and in updateAttribute

In addAttribute is visible_on_front and in update is is_visible_on_front.

```
$catalogInstaller->addAttribute(
    \Magento\Catalog\Model\Product::ENTITY,
    'some_attr',
    [
        'label'     => 'Some Attribute',
        'group'     => 'Product Details',
        'required'  => false,
        'visible_on_front' => true,
    ]
);
```
```
$catalogInstaller->updateAttribute(
    \Magento\Catalog\Model\Product::ENTITY,
    'some_attr',
    'is_visible_on_front',
    true
);
```

Regards

**Comment by dmanners** [comment]
This was part of Magento1 and appears to have been ported into Magento2 also, I assume for backwards comparability. There is now a PropertyMapper class `app/code/Magento/Catalog/Model/Resource/Setup/PropertyMapper.php` which should help out when dealing with the names. It looks like this is called when the eavsetup calls `addAttribute`.

    $data = array_replace(
        ['entity_type_id' => $entityTypeId, 'attribute_code' => $code],
        $this->attributeMapper->map($attr, $entityTypeId)
    );

This is not only used in the catalog but also on other setup scripts. For me this feels a bit odd porting this confusion into Magento2 but I am sure there was a reason for this.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
