### ISSUE TITLE
Overwrite the Block file and .phtml files.

### ISSUE THREAD

**Issue by chaluvadiswamy** [magento/magento2#2144]
I would like to overwrite the the Block files and .phtml files of the magento modules.Here is example
 -Magento Newsletter Module

I want to extended the Block file '\Magento\Newsletter\Block\Subscribe' to the custom Module as mentioned in the below code 
<?php
namespace Sample\Test\Block;

class Customsubscribe extends \Magento\Newsletter\Block\Subscribe
{
	
    /**
     * Retrieve form action url and set "secure" param to avoid confirm
     * message when we submit form from secure page to unsecure
     *
     * @return string
     */
    public function getFormActionUrl()
    {
        return $this->getUrl('newsletter/subscriber/new1231', ['_secure' => true]);
    }
}
?>

Add tried to override the subscriber.phtml  for Magento newsletter Module to My sample Module 'Test'

In the custom modules folder i add the below code 

app\code\Sample\Test\view\frontend\layout\default.xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">
    <body>
    
		
        <referenceContainer name="footer">
            <block class="Training\Test\Block\Customsubscribe" name="form.subscribe" as="subscribe" before="-" template="subscribe.phtml"/>
        </referenceContainer>
    </body>
</page>

After Doing that i run the CLI : php bin/magento setup:upgrade, but still the file is loading from the Magento_Newsletter Module .

Can any one please help on the  this issues.

**Comment by dfediuk** [comment]
- You need to owerwrite all the block class to change just a single method. Use plugins: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html

- Here is my working code to change a standard block template: https://mage2.pro/t/66

**Comment by chaluvadiswamy** [comment]
@dfediuk ,Thanks For the Update.
But the plugin concept they mentioned only to overwrite the Model Files as  they mentioned in following link :http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html

 But in My case i want to catalog modules .phtml files into my front end view  as per my design requirement.

**Comment by dfediuk** [comment]
Plugins work for **almost all** classes (including the blocks), not only for Models.

**Comment by chaluvadiswamy** [comment]
@dfediuk thanks .

I will try and get you back.

**Comment by chaluvadiswamy** [comment]
@dfediuk , I tried both ways ,but still i am facing the issue with rewrite  .phtml files .

**Comment by antonkril** [comment]
If you use template from different module than block, you should use full path to template: Module_Name::path/to/template.phtml

**Comment by chaluvadiswamy** [comment]
@antonkril  you need to give as follows 
<referenceBlock name='copyright'>
	<action method='setTemplate'>
		<argument name='template' xsi:type='string'>Sample_Test::/view/frontend/template/test/copyright.phtml</argument>
	</action>
</referenceBlock>

**Comment by chaluvadiswamy** [comment]
@dfediuk , Still issue existing is there any other option

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
