### ISSUE TITLE
ServiceLocatorUsageException Error in magneto 2

### ISSUE THREAD

**Issue by muhammadawais93** [magento/magento2#2145]
Im getting this error when i try to setup magneto through setup wizard.

An error occurred during execution; please try again later.

Additional information:

Zend\ServiceManager\Exception\ServiceLocatorUsageException

File:
/work/www/magento2/vendor/zendframework/zend-servicemanager/Exception/ServiceLocatorUsageException.php:34
Message:
Service "Magento\Setup\Controller\Index" has been requested to plugin manager of type "Zend\Mvc\Controller\ControllerManager", but couldn't be retrieved.
A previous exception of type "Zend\ServiceManager\Exception\ServiceNotCreatedException" has been raised in the process.
By the way, a service with the name "Magento\Setup\Controller\Index" has been found in the parent service locator "Zend\ServiceManager\ServiceManager": did you forget to use $parentLocator = $serviceLocator->getServiceLocator() in your factory code?
Stack trace:
#0 /work/www/magento2/vendor/zendframework/zend-servicemanager/AbstractPluginManager.php(312): Zend\ServiceManager\Exception\ServiceLocatorUsageException::fromInvalidPluginManagerRequestedServiceName(Object(Zend\Mvc\Controller\ControllerManager), Object(Zend\ServiceManager\ServiceManager), 'Magento\\Setup\\C...', Object(Zend\ServiceManager\Exception\ServiceNotCreatedException))
#1 /work/www/magento2/vendor/zendframework/zend-servicemanager/AbstractPluginManager.php(120): Zend\ServiceManager\AbstractPluginManager->tryThrowingServiceLocatorUsageException('Magento\\Setup\\C...', false, Object(Zend\ServiceManager\Exception\ServiceNotCreatedException))
#2 /work/www/magento2/vendor/zendframework/zend-mvc/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('Magento\\Setup\\C...', Array, false)
#3 /work/www/magento2/vendor/zendframework/zend-mvc/DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('Magento\\Setup\\C...')
#4 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /work/www/magento2/vendor/zendframework/zend-mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /work/www/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#9 {main}
Previous exceptions:

Zend\ServiceManager\Exception\ServiceNotCreatedException

File:
/work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php:1135
Message:
An abstract factory could not create an instance of magentosetupcontrollerindex(alias: Magento\Setup\Controller\Index).
Stack trace:
#0 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(646): Zend\ServiceManager\ServiceManager->createFromAbstractFactory('magentosetupcon...', 'Magento\\Setup\\C...')
#1 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('Magento\\Setup\\C...', 'magentosetupcon...')
#2 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#3 /work/www/magento2/vendor/zendframework/zend-servicemanager/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('Magento\\Setup\\C...', false)
#4 /work/www/magento2/vendor/zendframework/zend-mvc/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('Magento\\Setup\\C...', Array, false)
#5 /work/www/magento2/vendor/zendframework/zend-mvc/DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('Magento\\Setup\\C...')
#6 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /work/www/magento2/vendor/zendframework/zend-mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /work/www/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#11 {main}
Zend\ServiceManager\Exception\ServiceNotCreatedException

File:
/work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php:946
Message:
An exception was raised while creating "Magento\Setup\Controller\Index"; no instance returned
Stack trace:
#0 /work/www/magento2/vendor/zendframework/zend-servicemanager/AbstractPluginManager.php(284): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'magentosetupcon...', 'Magento\\Setup\\C...')
#1 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(1129): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'magentosetupcon...', 'Magento\\Setup\\C...')
#2 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(646): Zend\ServiceManager\ServiceManager->createFromAbstractFactory('magentosetupcon...', 'Magento\\Setup\\C...')
#3 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('Magento\\Setup\\C...', 'magentosetupcon...')
#4 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#5 /work/www/magento2/vendor/zendframework/zend-servicemanager/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('Magento\\Setup\\C...', false)
#6 /work/www/magento2/vendor/zendframework/zend-mvc/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('Magento\\Setup\\C...', Array, false)
#7 /work/www/magento2/vendor/zendframework/zend-mvc/DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('Magento\\Setup\\C...')
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /work/www/magento2/vendor/zendframework/zend-mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /work/www/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#13 {main}
Exception

File:
/work/www/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:67
Message:
Warning: include(/work/www/magento2/app/etc/config.php): failed to open stream: No such file or directory in /work/www/magento2/lib/internal/Magento/Framework/App/DeploymentConfig/Reader.php on line 83
Stack trace:
#0 /work/www/magento2/lib/internal/Magento/Framework/App/DeploymentConfig/Reader.php(83): Magento\Framework\App\ErrorHandler->handler(2, 'include(/work/w...', '/work/www/magen...', 83, Array)
#1 /work/www/magento2/lib/internal/Magento/Framework/App/DeploymentConfig/Reader.php(83): Magento\Framework\App\DeploymentConfig\Reader->load()
#2 /work/www/magento2/lib/internal/Magento/Framework/App/DeploymentConfig.php(130): Magento\Framework\App\DeploymentConfig\Reader->load()
#3 /work/www/magento2/lib/internal/Magento/Framework/App/DeploymentConfig.php(72): Magento\Framework\App\DeploymentConfig->load()
#4 /work/www/magento2/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(112): Magento\Framework\App\DeploymentConfig->get()
#5 /work/www/magento2/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(59): Magento\Framework\App\ObjectManagerFactory->create(Array)
#6 /work/www/magento2/setup/src/Magento/Setup/Controller/Index.php(29): Magento\Setup\Model\ObjectManagerProvider->get()
#7 /work/www/magento2/vendor/zendframework/zend-di/Di.php(488): Magento\Setup\Controller\Index->__construct(Object(Magento\Setup\Model\ObjectManagerProvider))
#8 /work/www/magento2/vendor/zendframework/zend-di/Di.php(299): Zend\Di\Di->createInstanceViaConstructor('Magento\\Setup\\C...', Array, NULL)
#9 /work/www/magento2/vendor/zendframework/zend-di/Di.php(248): Zend\Di\Di->newInstance('Magento\\Setup\\C...', Array, true)
#10 /work/www/magento2/vendor/zendframework/zend-mvc/Service/DiStrictAbstractServiceFactory.php(97): Zend\Di\Di->get('Magento\\Setup\\C...')
#11 [internal function]: Zend\Mvc\Service\DiStrictAbstractServiceFactory->createServiceWithName(Object(Zend\Mvc\Controller\ControllerManager), 'magentosetupcon...', 'Magento\\Setup\\C...')
#12 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(939): call_user_func(Array, Object(Zend\Mvc\Controller\ControllerManager), 'magentosetupcon...', 'Magento\\Setup\\C...')
#13 /work/www/magento2/vendor/zendframework/zend-servicemanager/AbstractPluginManager.php(284): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'magentosetupcon...', 'Magento\\Setup\\C...')
#14 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(1129): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'magentosetupcon...', 'Magento\\Setup\\C...')
#15 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(646): Zend\ServiceManager\ServiceManager->createFromAbstractFactory('magentosetupcon...', 'Magento\\Setup\\C...')
#16 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('Magento\\Setup\\C...', 'magentosetupcon...')
#17 /work/www/magento2/vendor/zendframework/zend-servicemanager/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#18 /work/www/magento2/vendor/zendframework/zend-servicemanager/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('Magento\\Setup\\C...', false)
#19 /work/www/magento2/vendor/zendframework/zend-mvc/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('Magento\\Setup\\C...', Array, false)
#20 /work/www/magento2/vendor/zendframework/zend-mvc/DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('Magento\\Setup\\C...')
#21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#22 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#23 /work/www/magento2/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /work/www/magento2/vendor/zendframework/zend-mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /work/www/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#26 {main}

**Comment by mazhalai** [comment]
@muhammadawais93 in what step did you encounter this problem? How did you deploy magento, git clone? or composer create-project? Also, what is your environment?

**Comment by muhammadawais93** [comment]
im using debian wheezy linux vm, i just clone the magento2 and install  composer cammands

after that i tried to setup through setup wizard then thats error came.

**Comment by mazhalai** [comment]
@muhammadawais93 please check [permissions](http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html). `app/etc`, `pub/static` and `var` need to be writable.

**Comment by muhammadawais93** [comment]
i checked all directories are set to 0770 permission and files are set to 0660 permission but error is still 
plz help me im stuck there

**Comment by mazhalai** [comment]
@muhammadawais93 just want to make sure that you have a `group` to which apache `_www` user has been added. If not, the above permissions will not work.

**Comment by xcomSteveJohnson** [comment]
@muhammadawais93 Please see http://bit.ly/1GrYajK

**Comment by daim2k5** [comment]
@muhammadawais93 hopefully the answers resolve your issue. If not feel free to reopen this issue
