### ISSUE TITLE
Grammar issues during the install process

### ISSUE THREAD

**Issue by beckindesigns** [magento/magento2#2148]
There are grammar issues during the install. When checking the server environment it outputs the following. 

"We're making sure your server environment is ready for to be <b>installered.</b>"

**Comment by mazhalai** [comment]
We are working on a fix for that @beckindesigns. Internal ticket MAGETWO-44043

**Comment by mazhalai** [comment]
@beckindesigns this has been fixed in 2.0.0. Please open a new issue if problem persists.
