### ISSUE TITLE
Can't enable module

### ISSUE THREAD

**Issue by beckindesigns** [magento/magento2#2150]
I created a file located (app/code/Beckin/TestModule/etc/module.xml) as described here: http://devdocs.magento.com/guides/v2.0/architecture/modules/mod_intro.html

This file contains the following:

    <config>
        <module name="Beckin_TestModule" setup_version="1.0.0">
            <sequence>
                <module name="Magento_Newsletter" />
            </sequence>
        </module>
    </config>

Finally I tried to activate the module as described http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-enable.html

This is the code and results that I get:

<pre>
$ ./magento module:enable Beckin_TestModule
Unknown module(s): 'Beckin_TestModule'
</pre>

I also tried:
<pre>
[beckin@beckindesignsmhm bin]$ ./magento module:enable --clear-static-content Beckin_TestModule
Unknown module(s): 'Beckin_TestModule'
</pre>

Is this a bug b/c I am following the docs and I am not able to move forward?

**Comment by odom** [comment]
@beckindesigns : do you have registration.php in the module structure? 
Ex:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/registration.php
I think

**Comment by beckindesigns** [comment]
Thanks for that info. That was the issue. I wonder why that wasn't in the doc? I found another one too here: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/create_module.html Why are they two of them?

That one says you need the composer.json file also but neither mentioned the registration.php file. 

Thanks again for the help!

**Comment by chaluvadiswamy** [comment]
@beckindesigns , i too face the same issue , if you using the beat version 1.0.0 or 0.74 you need to run the below steps:

1. Go to root path of you magento2  setup

2.Run the Command : php bin/magento setup:upgrade

3. After that you will see that Scheme  updated in you terminal .

4. Go to app/etc/Config.php , inside that you module will enabled like 'Beckin_TestModule' =>1

let me know if you have any other clarification.

**Comment by beckindesigns** [comment]
Thanks. After I ran:

    $ ./magento module:enable Beckin_TestModule

I ran that one too with no issues. The biggest problem I was facing was getting the first command to run and it was due to the missing registration.php file.

I'm all good now, thanks!

**Comment by chaluvadiswamy** [comment]
@beckindesigns , Have to over write the method after the extending the  existing module block file. as below code 
<?php
namespace Sample\Test\Block;

class Customsubscribe extends \Magento\Newsletter\Block\Subscribe
{

/**
 * Retrieve form action url and set "secure" param to avoid confirm
 * message when we submit form from secure page to unsecure
 *
 * @return string
 */
public function getFormActionUrl()
{
    return $this->getUrl('newsletter/subscriber/new1231', ['_secure' => true]);
}

}
?>

**Comment by alankent** [comment]
The registration.php file is relatively new - the docs may not have caught up quite yet. The registration.php file was required to allow modules to reside in the 'vendor' directory.

**Comment by beckindesigns** [comment]
Cool, thats what I figured it probably was. Thanks @alankent.

**Comment by xcomSteveJohnson** [comment]
The topic on registration is just published: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/component-registration.html

Please let us know if it helps.

**Comment by beckindesigns** [comment]
@xcomSteveJohnson Perfect!

**Comment by mazhalai** [comment]
@beckindesigns thank you for reporting this issue. We are closing this ticket. Please open a new one if you still have issues.
