### ISSUE TITLE
World users care these. Can Magento2 add the two functions?

### ISSUE THREAD

**Issue by cfcnn** [magento/magento2#2151]
1. About produt images. When delete a product at the backend, the related product images are not deleted automatically, so that those useless images still occupy storage. Will Magento2 delete products and product images together?
If 3 images for each product, 500KB for each image, there are 1,000 deleted products, and the 3,000 images are not deleted together with products, they waste 1.4GB storage; If there are 10,000 items, that's 14GB... Magento users have to pay for that storage. And more and more time when backup or transfer website.
1,000 items × 3 images × 500 KB/image=1.4GB
10,000 items × 3 images × 500 KB/image=14GB

2. The default customer registeration verification of Magento is too simple, it's unable to reject robot registration, it's a problem for world magento users, a number of robot registration makes database  very large. And they leave batch comments with ad links automatically by soft, or send spam ad emails to other people through " Email to Friend".
Could magento2 add a google verification ReCaptcha to identify human or robot? ( as follows)

![recaptcha](https://cloud.githubusercontent.com/assets/15027055/10626566/ec329adc-77e2-11e5-9481-592d3a0eaad9.png)

![createaccount](https://cloud.githubusercontent.com/assets/15027055/10626569/fd387f90-77e2-11e5-8201-8a14e7fdd56f.png)

![review](https://cloud.githubusercontent.com/assets/15027055/10626583/16949f28-77e3-11e5-8fe4-7522bd9e1241.png)

![email](https://cloud.githubusercontent.com/assets/15027055/10626589/27ff16bc-77e3-11e5-84cc-8fac0040e26e.png)

![contactus](https://cloud.githubusercontent.com/assets/15027055/10626783/e29493b6-77e4-11e5-8df4-2ad74b6464b2.png)

**Comment by antonkril** [comment]
Did you try magento captcha?

**Comment by cfcnn** [comment]
Yes, I tried. Magento captcha is too simple, robots register very easily. And the technology is out of date, because of captcha recognition software, even magento has email verification, they can login and click the verification link automatically to finish the registration. The popular automatic registration software "senuke" and automatic captcha recognition software" captcha sniper".  There are many charged automatic captcha websites. Hope that magento2 will have google verification ReCaptcha that keeps update continually.

![436761407_640](https://cloud.githubusercontent.com/assets/15027055/10661207/25f3dba8-78df-11e5-98c8-015c195d105b.jpg)

![captcha](https://cloud.githubusercontent.com/assets/15027055/10661266/72d09506-78df-11e5-9066-977b8bc8ff2d.jpg)

https://vimeo.com/65662654

**Comment by antonkril** [comment]
@piotrekkaminski can you look at this request?

**Comment by cfcnn** [comment]
@antonkril Thanks for response, I thought it would be ignored. It's an unavailable site but  the product keywords were grabbed by search engine. The robots registered automatically by tools, all customer emails on the list are robots(as the picture shows).
 
![robot](https://cloud.githubusercontent.com/assets/15027055/10808341/2383c4fa-7e25-11e5-9a8c-7fd9795eaeed.png)

Magento is the most popular online shopping program in the world, but the verification function never updates, robots can recognize, those robots software/tools keep updating. All Magento users have troubles from robot registrations/spams.
Google captcha is the best one in preventing disturbing from robots.
You're advised to add the Google captcha function, in the meanwhile, keep your own verification code,update it continually. Because some users may not link to Google webserver for some reasons or in specific environment,e.g. the internal web,or specific countries like China, the national firewall prevents linking to Google.

**Comment by piotrekkaminski** [comment]
Related epic: MAGETWO-46399

**Comment by piotrekkaminski** [comment]
@cfcnn hey, thanks for reporting this. We are aware of the weakness of current captcha solution. The feature was put in backlog for one of the next releases.

**Comment by eoghanobrien** [comment]
Hi, I created the [reCAPTCHA extension](https://github.com/StudioForty9/Recaptcha) from the screenshots provided, I've just started work on the Magento 2 version (over 50% of the way there including unit tests)

The issue for me was always getting the reCAPTCHA widget to show up on the review and send to friend forms. The contact form recently got an additional info container (`form.additional.info`), is there any chance that will happen for review and send to friend forms soon?

**Comment by piotrekkaminski** [comment]
CAPTCHA changes are on the roadmap, tentatively scheduled for next year.
In github it is tracked here https://github.com/magento/magento2/issues/3023.
As for deleting the images, it is usually a bad idea as they might be referenced from marketing emails, blogs, search engines etc. With storage costs going down I do not consider it a priority - is it a problem for many users?

**Comment by cfcnn** [comment]
@eoghanobrien  I used your reCAPTCHA extension , it worked excellently in Magento 1.9, solved well with the problem of robot. Looking forward to your Magento 2 version.

**Comment by cfcnn** [comment]
@piotrekkaminski  Thanks for the Magento 2 official agreement to solve the problem of the reCAPTCHA. It's great. Although next year is a little bit late for me.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/World-users-care-these-Can-Magento2-add-the-two-functions/idi-p/47214).
