### ISSUE TITLE
Why does \Magento\Translation\Model\Js\DataProvider use \Magento\Framework\Phrase\Renderer\Translate, not \Magento\Framework\Phrase\Renderer\Composite?

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2156]
https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Translation/Model/Js/DataProvider.php#L63

This lead to the 2 problems:
- Inline translation does not work for Knockout templates.
- Custom translators (which can be injected as an argument for \Magento\Framework\Phrase\Renderer\Composite) do not work for Knockout templates.

**Comment by antonkril** [comment]
Agree, but RendererInterface should be used instead of Renderer\Composite

**Comment by IlnitskiyArtem** [comment]
@dmitry-fedyuk, Thanks for reporting this issue. 
Created internal issue MAGETWO-70240 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@dmitry-fedyuk, thank you for your report.
We've created internal ticket(s) MAGETWO-70240 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#12007 by @dverkade in 2.3-develop branch
Related commit(s):
 - db0c775b36769a3e729f9598613ea0fc462b74a2

The fix will be available with the upcoming patch release.

**Comment by magento-team** [comment]
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#12953 by @dverkade in 2.2-develop branch
Related commit(s):
 - cfce6310fed212ebd22d8ceddf6a2d53d2a5d7c4

The fix will be available with the upcoming patch release.

**Comment by magento-team** [comment]
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#12954 by @dverkade in 2.1-develop branch
Related commit(s):
 - 65c99b982c15ebbbd0d9a5535af0f3dc156552e7
 - f215350f211c50590981b12c4ab3146499e087cf
 - a0b7bc5ae9c151889d382fc27d6605d15ed5625b

The fix will be available with the upcoming patch release.
