### ISSUE TITLE
PayPal currency list need to be updated 

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2157]
Related to https://github.com/magento/magento2/issues/1489
Russia has been added to PayPal merchant country list but the Russian Ruble currency has not been added:
https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Paypal/Model/Config.php#L196-L217

The PayPal currency list used by Magento is outdated and the same problem would be with another currencies.
Please use the official PayPal currency list: https://developer.paypal.com/docs/classic/api/currency_codes/
Please note that "For in-border payments (payments made within Russia), **the Russian Ruble is the only accepted currency**. If you use another currency for in-border payments, the transaction will fail returning error code 10001 – Internal Error."

**Comment by choukalos** [comment]
Opened internal ticket MAGETWO-44616.

**Comment by alena-marchenko** [comment]
Hi Dmitry,

We have added Russian Ruble PayPal currency list.
Please feel free creating new issue on github or reopen this one if you have any further issues
