### ISSUE TITLE
ko.getObservable is not a function in admin section

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#2158]
After updating to the latest version of develop (commit 0be91a56d050791ac0b67a47185d79df31e79329) I am seeing the error `ko.getObservable is not a function` in events.js:46 across the whole admin section.

I have updated magento via composer and performed the static-content:deploy. Did I miss out another step?

**Comment by dmanners** [comment]
Never mind, removing the whole static folder and calling static-content deploy seems to have fixed the issue. Is there a flag that would do that for you when calling deploy?

**Comment by gigadesign1** [comment]
After a clean install from the latest develop branch I have the same issue.
Removing the static folder and calling deploy does not work for me, I still get the same error.

TypeError: ko.getObservable is not a function:  events.js:46:13
