### ISSUE TITLE
The variable name «categorySetup» in \Magento\Catalog\Setup\InstallData::install() method is misleading because $categorySetup->installEntities() installs both the products and categories attributes

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2163]
https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Catalog/Setup/InstallData.php#L46

Similar to https://github.com/magento/magento2/issues/2162

**Comment by vzabaznov** [comment]
Closed as duplicate #1915
