### ISSUE TITLE
Inconsistency: \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Attributes::_getAdditionalElementTypes() fires the event «adminhtml_catalog_product_edit_element_types» but \Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes::_getAdditionalElementTypes() does not fire a similar event

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2165]
Method `\Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Attributes::_getAdditionalElementTypes()` allows an extension to add custom element types to admin product page by handling `adminhtml_catalog_product_edit_element_types` event:

https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Catalog/Block/Adminhtml/Product/Edit/Tab/Attributes.php#L151

A similar method for categories \Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes::_getAdditionalElementTypes()  needs to do so too.

https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Catalog/Block/Adminhtml/Category/Tab/Attributes.php#L124-L130

Now an extension can add custom element types to admin product page, but can not do so for admin category page.

**Comment by dfediuk** [comment]
My workaround solution: https://mage2.pro/t/148
It is not perfect because it overrides a core class, but I have not found a more proper solution.

**Comment by andimov** [comment]
@mage2pro

Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
