### ISSUE TITLE
Installer: Write Permissions on Additional File

### ISSUE THREAD

**Issue by astorm** [magento/magento2#2166]
The following folder

    pub/media/downloadable

should be added as a "needs write permission" folder to the installer's readiness check.  While the bare bones Magento installer doesn't need access to this folder, an install with the sample data **does**.  If a user attempts to install the sample data without write permission on `pub/media/downloadable`, they'll get a permission denied error during the final install step.  You can see an example of this behavior in the following screencast at the 24 minutes, 30 seconds point (link below include timecode)

https://vimeo.com/142970298#t=24m30s

**Comment by xcomSteveJohnson** [comment]
Please look at the latest iteration and let us know what you think. We've installed Magento with sample data several times and have not needed to do anything special for that directory. 

http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data.html

**Comment by mazhalai** [comment]
@astorm thank you for reporting this issue. MAGETWO-44544 will track fixes for it.

**Comment by xcomSteveJohnson** [comment]
If you use our guidance on permissions and ownership, you shouldn't run into this. Tried it today and Setup Wizard ran just fine. 
Most important part of creating the user: http://bit.ly/1GrYajK
Setting permissions and ownership: http://bit.ly/1W9H4hM
Sample data, which also involves setting permissions and ownership: http://bit.ly/1OMJEpB
Note that if you install sample data after Magento, you also need to run magento setup:upgrade and clear some directories under var (cache, page_cache, and generation).

**Comment by astorm** [comment]
@xcomSteveJohnson Good information, and thank for you for sharing!  

I'm not sure if your post was meant as a "here's some extra helpful info" or a "we don't need to do this because we have advice on permissions".  If it's the former, folks can stop reading. :) 

If it was the later, (and take this as one person's opinion), then consider that lots of people **won't** follow any guidance on permissions and ownership rights.  How a system owner sets up their permissions is going to vary wildly on that owner's level of technical expertise,  whether they're running PHP under apache as `MOD_PHP` or under apache/nginx as FastCGI, what other processes are running on the the server or VM Magento's running on, etc.  Additionally, the way someone might setup permissions on their **development** machine is going to vary wildly depending on if they're using a stock PHP apache, one of the all in one installers, or self compiled versions of PHP.  In this early stage of Magento 2's life making sure developers can install and use the platform easily should be priority number one.

It's great that Magento's offering strong guidance on how this should work -- but from a **product** point of view if there's a folder that the installer may need to write to, then that folder should be included in the readiness check step. Doubly so since there's already a number of folders the installer checks permissions on.

**Comment by mazhalai** [comment]
@astorm `pub\media\` is being checked in readiness check. See https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Model/FilePermissions.php#L75
But, sample-data https://github.com/magento/magento2-sample-data/blob/master/app/code/Magento/SampleData/Helper/Deploy.php#L99 is attempting `mkdir` with the wrong permissions.

**Comment by astorm** [comment]
@mazhalai Thank you for chiming in!

I'm not sure I understand completely what you're saying -- it seems incorrect. Or maybe just the imprecision of the english language. It's true that `pub/media` is part of the readiness check.  However, the sample data installer is trying to make a folder inside of of the following folder

    `pub/media/downloadable` 

with `mkdir`.  Specifically, it's trying to make the following folder

    public/media/downloadable/link_samples/l

You can see that at the 27 minute mark of the screencast I mentioned: https://vimeo.com/142970298#t=27m00s

So the problem, better stated, is the installer, during the sample data installation, is trying to create a sub-folder in the `pub/media/downloadable` folder.  However, since `pub/media/downloadable` has incorrect permissions, and incorrect permissions on `pub/media/downloadable` do not trigger an invalid readiness during the readiness check, the installation fails. 

The problem is **not** that `mkdir` is attempting to "create with the wrong permissions", it's that `mkdir` tries to create a folder when the web server doesn't have the correct permissions to create it. 

The larger product point I'm trying to make with this ticket is that, as things sit now, many developers (myself included), will download Magento 2 and try to install it with the sample data, pass the readiness check, but still run into a problem the readiness checker should have caught.  This sort of things happens in betas all the time, but if Magento 2 **ships** like this it's going to turn off lots of people, and going to cement a lot of irrevocable first impressions people have of the platform.

Question: Does the permissions check in the readiness check check all the subfolders?

**Comment by mazhalai** [comment]
Readiness check does not check all subfolders, we will fix it in scope of ticket MAGETWO-44552

**Comment by mazhalai** [comment]
@astorm checking of subfolder fix is available in 2.0.0. Please have a look and create a new issue if necessary.
