### ISSUE TITLE
Could not fetch https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/31f8b717e51d9a2afca6c9f046f5d69fc27c8686

### ISSUE THREAD

**Issue by themestechnology** [magento/magento2#2169]
I got the below error on a clean Ubuntu install when using composer for the first time

Installing phpunit/php-text-template (1.2.1)
    Downloading: Connecting...
Could not fetch https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/31f8b717e51d9a2afca6c9f046f5d69fc27c8686, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+web-Aspire-TC-105+2015-10-23+1333
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by mazhalai** [comment]
@themestechnology this is not a Magento2 issue, but a composer+github one. Please see [this link](https://circleci.com/docs/composer-api-rate-limit) on how to solve this issue.
