### ISSUE TITLE
Unable to extend adminhtml customer addresses tab in magento2

### ISSUE THREAD

**Issue by VLCSolutions** [magento/magento2#2170]
In magento1 i could extend the adminhtml customer addresses tab
`class Vendor_Module_Block_Adminhtml_Customer_Edit_Tab_Addresses extends Mage_Adminhtml_Block_Customer_Edit_Tab_Addresses
{
    public function __construct()
    {
        parent::__construct();
        $this->setTemplate('vlcsolutions/customer/tab/addresses.phtml');
    }
}`
and now if i modify vlcsolutions/customer/tab/addresses.phtml, changes are reflected,

How to achieve the same in magento2.

I have not found any class or template like customer/tab/addresses.phtml

**Comment by AndriyNasinnyk** [comment]
HI @VLCSolutions 
We have a example in app/code/Magento/Wishlist/view/adminhtml/layout/customer_index_edit.xml
In our code Wishlist module adds new custom tab in Customer edit form.
Take into your attention, because your custom block must implement Magento\Ui\Component\Layout\Tabs\TabInterface.

**Comment by AndriyNasinnyk** [comment]
You can try overwrite fieldset template just for address tab.
Create file YourVendor/ModuleName/view/base/ui_component/customer_form.xml
```
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Ui/etc/ui_configuration.xsd">
    <fieldset name="address">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="template" xsi:type="string">YourVendor_ModuleName/form/my-address-template</item>
            </item>
        </argument>
    </fieldset>
</form>
```
Copy template form app/code/Magento/Ui/view/base/web/templates/form/fieldset.html to you app/code/YourVendor/ModuleName/view/base/web/templates/form/my-address-template.html and modify for your changes.

If it's not help you, we have internal issue that modify our address tab in customer form to be more flexible for changes. Our internal issue MAGETWO-44654. Please wait for updates.

**Comment by VLCSolutions** [comment]
@AndriyNasinnyk, suggested solution is not working, do we have any updates on issue MAGETWO-44654

**Comment by VLCSolutions** [comment]
@AndriyNasinnyk We are looking this issue for our magento2 extension, And this is the only one issue left over to complete our extension. Do we have any latest updates on this issue.

**Comment by VLCSolutions** [comment]
@AndriyNasinnyk We have found solution for this. When we change `magento\module-ui\view\base\web\templates\form\components\Collection.html`, `C:\xampp\htdocs\M2EE\vendor\magento\module-ui\view\base\web\js\form\components\Collection.js`, we are able change the addresses template file.

But how to override this files in standard way. We have tried with '`app\design\adminhtml\Magento\backend\Magento_Ui\web\templates\form\components\Collection.html` and `app\design\adminhtml\Magento\backend\Magento_Ui\web\js\form\components.Collection.js` but we are unable render changes.
When we change the same files in core files we are able to see the changes

**Comment by twosg** [comment]
Any update on this?

**Comment by cpartica** [comment]
Yes we started working on it, 
Just to clarify are you trying to add a new tab or extend the form that edits the address? maybe add more fields to the address or html or functionality?

_note that phtml usage is not recommended anymore as most of the admin is now made using ui components, and those templates exist in web/templates as html templates used by the knockout js classes that define behavior_

**Comment by cpartica** [comment]
Can you please comment on the above question? We are waiting on your response to further proceed

**Comment by twosg** [comment]
I wanted to extend the form that edits the address. I want add new fields as well sort existing fields in a new fieldset or visually seperated. Further I want to add a button and do some AJAX and update the fields.

Maybe that is possible already with extending the ui components, but I was unable to determine which files are the base files for this form.

**Comment by veloraven** [comment]
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
