### ISSUE TITLE
The method \Magento\Eav\Model\ResourceModel\Helper::getLoadAttributesSelectGroups() can be sped up and simplified

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2171]
https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Eav/Model/ResourceModel/Helper.php#L77-L84

Can be simplified to `array_values(array_merge($selects))`
It is not only simplier but much faster too.

**Comment by davidalger** [comment]
@dfediuk Thanks for the feedback. Would you mind submitting this as a PR so it may be further processed?

**Comment by davidalger** [comment]
Closing due to lack of response
