### ISSUE TITLE
Get Config Structure Tabs in Console Command

### ISSUE THREAD

**Issue by dmaciej** [magento/magento2#2172]
It looks there is no way to get configuration tabs from console command class:

``` php
try {
    $this->appState->setAreaCode('adminhtml');
} catch (\Magento\Framework\Exception\LocalizedException $e) { }

$configStructure = $this->getObjectManager()->get('Magento\Config\Model\Config\Structure');
$tabs = $configStructure->getTabs(); // Null
```

The above code return tabs on the normal application boot.

**Comment by veloraven** [comment]
@dmaciej is this issue still actual?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
