### ISSUE TITLE
Review - Rating does not retrieve selected star

### ISSUE THREAD

**Issue by rodrigowebjump** [magento/magento2#2173]
Hi,

In the review page, if save process fail, all the data of review form is retrieved except the review star selection.

This occurred while I implemented a custom review validation in a plugin that return an error message in afterValidate.

Before submit
![review-before-submit](https://cloud.githubusercontent.com/assets/635466/10708439/16d6663c-79e7-11e5-81af-7d4899527213.png)

After submited - All form data were retrieved, except the stars
![review-after-submit](https://cloud.githubusercontent.com/assets/635466/10708440/16d6a73c-79e7-11e5-8c8f-f43545c9de33.png)

**Comment by yaronish** [comment]
Hi @rodrigozulu internal ticket MAGETWO-47781 created for this issue 
Thanks.

**Comment by magento-engcom-team** [comment]
@rodrigowebjump, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
