### ISSUE TITLE
The system forbids reverse paths (../) in Less @import statements so how can an extension share its Less file between frontend and backend?

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2179]
https://github.com/magento/magento2/blob/4499554d4e47135cdb8f5464e1d7eed3ebfb985e/lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/Resolver/Simple.php#L79

**Comment by dfediuk** [comment]
I have found a solution: the common Less files can be placed into the extension's `web/base` folder and then referred from both the `web/frontend` and `web/adminhtml` folders.

**Comment by alankent** [comment]
Too quick for me!  Yes, base is "global", not per area. It is designed for sharing files between different areas like what you were after.
