### ISSUE TITLE
Error updating Tier-Prices when Price-Scope is not Global

### ISSUE THREAD

**Issue by m-schreiber** [magento/magento2#21823]
### Preconditions (*)

1. Magento 2.3.0 CE
2. Global-Settings catalog/price/scope = 1 (WEBSITE)
`bin/magento config:set catalog/price/scope 1`

### Steps to reproduce (*)

1. Login to Admin
2. Create & Save Product with Tier-Price
3. Open & Save Product again

### Expected result (*)

1. Product saved successfully

### Actual result (*)

1. Error Message "Unique constraint violation found"
```
[2019-03-18 14:18:30] main.CRITICAL: Unique constraint violation found
{"exception":"[object] (Magento\\Framework\\Exception\\AlreadyExistsException(code: 0): 
Unique constraint violation found at 
/var/www/vendor/magento/framework/EntityManager/Operation/Update.php:121, 
Magento\\Framework\\DB\\Adapter\\DuplicateException(code: 1062): SQLSTATE[23000]: 
Integrity constraint violation: 1062 Duplicate entry '1-0-1-1.0000-0' for key
'UNQ_E8AB433B9ACB00343ABB312AD2FAB087', query was: 
INSERT INTO `catalog_product_entity_tier_price` 
(`entity_id`, `all_groups`, `customer_group_id`, `qty`, `value`, `website_id`, `percentage_value`) 
VALUES (?, ?, ?, ?, ?, ?, ?) 
at /var/www/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:588, 
Zend_Db_Statement_Exception(code: 23000): 
SQLSTATE[23000]: Integrity constraint violation: 1062 
Duplicate entry '1-0-1-1.0000-0' for key 
'UNQ_E8AB433B9ACB00343ABB312AD2FAB087', query was:
INSERT INTO `catalog_product_entity_tier_price` 
(`entity_id`, `all_groups`, `customer_group_id`, `qty`, `value`, `website_id`, `percentage_value`) 
VALUES 
(?, ?, ?, ?, ?, ?, ?) at 
/var/www/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, 
PDOException(code: 23000): SQLSTATE[23000]: 
Integrity constraint violation: 
1062 Duplicate entry '1-0-1-1.0000-0' for key 
'UNQ_E8AB433B9ACB00343ABB312AD2FAB087' at 
/var/www/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"} []
```

### Additional Information:
I've tracked the error to the following code 
`vendor/magento/module-catalog/Model/Product/Attribute/Backend/TierPrice/UpdateHandler.php:96`. 
The Functions "prepareOriginalDataToCompare" & "prepareNewDataForSave" seam to return incorrect data when $isGlobal is not true.

This Issue seams to be related: #19958

@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @m-schreiber. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@m-schreiber do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by m-schreiber** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @m-schreiber. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @m-schreiber, here is your [Magento instance](https://i-21823-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21823-2-3-develop.instances.magento-community.engineering/admin](https://i-21823-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by m-schreiber** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @m-schreiber. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @m-schreiber, here is your [Magento instance](https://i-21823-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21823-2-3-0.instances.magento-community.engineering/admin](https://i-21823-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by m-schreiber** [comment]
Bug can only be reproduced on 2.3.0 NOT on 2.3-develop.

**Comment by balwant20** [comment]
@m-schreiber : Have you found the solution of above issue? I am also facing the same issue.

**Comment by ssx** [comment]
@balwant20 set your price scope to global if possible.
