### ISSUE TITLE
Make API jsonapi compliant 

### ISSUE THREAD

**Issue by owenhaynes** [magento/magento2#2183]
At the moment the json API is not very compliant to  http://jsonapi.org.

This makes life hard when trying to use the magento API with angluarjs modules such as
rectangular, angualr-restmod.

I can imagine this is a lot of work.

**Comment by antonkril** [comment]
JSON api stable version was not released when we introduced APIs. Also usage of jsonapi might get to conflict with idea that service contracts should be represented the same way in php and through webapi.

But we will definitely look at this idea.

**Comment by mad0house** [comment]
its just making it extremely difficult to work with angularjs with rest frameworks, one example is the 
GET /V1/guest-carts/{cartId}/items
POST /V1/guest-carts/items
PUT /V1/guest-carts/items/{itemId}
DELETE /V1/guest-carts/{cartId}/items/{itemId}

the POST and PUT endpoints should in theory match DELETE and GET as you are modifying a cart, angualr-restmod expects this to be the case.

The cart call to create a cart 
POST /V1/guest-carts
also cases issues as it does not return an object, thinking of writing a patch for this but no idea how much stuff would break.

At this rate going to have to write a wrapper around the API to format the endpoints to be more compliant.

**Comment by ilagno89** [comment]
Internal ticket MAGETWO-44589 has been created.

**Comment by choukalos** [comment]
This looks like partially a bug ( Cart APIs - we would like our API's to be easily used by node based platform i.e. Angular with out a wrapper ) and a feature request ( be compliant with json api standard which includes definitions on response payload structure).  We'll look into the later portion as part of our future work to improve the web API framework

**Comment by antonkril** [comment]
Just to clarify: internal ticket reported by @irenelagno is to fix naming of resources, not full support of jsonapi

**Comment by sidolov** [comment]
Fixed naming of resources for cart items management. 
Delivered in cd0808932965b6bfd77599bafebb297803f0be97

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Make-API-jsonapi-compliant/idi-p/47196).
