### ISSUE TITLE
Config setting of Client Side Less Compilation generates warning

### ISSUE THREAD

**Issue by will-b** [magento/magento2#2186]
If the config value for 'dev/front_end_development_workflow/type' is set to 'client_side_compilation' a warning is generated.

> Warning: trim() expects parameter 1 to be string, array given in /lib/internal/Magento/Framework/View/Page/Config/Renderer.php on line 314'

trim is called on the $attributes parameter which is an empty array.

see:
app/code/Magento/Developer/Model/View/Page/Config/ClientSideLessCompilation/Renderer.php Line 121

`$attributes = $this->addDefaultAttributes('less', []);`

**Comment by piotrekkaminski** [comment]
internal ID MAGETWO-45018

**Comment by eug123** [comment]
@will-b,
Can not reproduce this warning, please check if the issue still exist on the current develop branch.
