### ISSUE TITLE
Remove type="text/javascript" for script tags

### ISSUE THREAD

**Issue by will-b** [magento/magento2#2187]
type="text/javascript" is not needed for script tags any more.
http://www.w3.org/TR/html5/scripting-1.html

app/code/Magento/Developer/Model/View/Page/Config/ClientSideLessCompilation/Renderer.php

line 307

` $attributes = ' type="text/javascript" ' . trim($attributes);`

**Comment by guz-anton** [comment]
I've created internal issue for this little fix MAGETWO-44724. Will see how fast it can be fixed.
Thanks for note.

**Comment by MomotenkoNatalia** [comment]
Hi @will-b, Part of the fixes was delivered under MAGETWO-33631

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Remove-type-quot-text-javascript-quot-for-script-tags/idi-p/48477).

**Comment by will-b** [comment]
@MomotenkoNatalia @piotrekkaminski cool thank you
