### ISSUE TITLE
Suggest to restore parameterless constructor _construct in the base class \Magento\Framework\DataObject (like Varien_Object::_construct() in Magento 1.x). For now the method is duplicated in the base block, base model, base form and so on.

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2188]
`Varien_Object::_construct()`:
https://github.com/OpenMage/magento-mirror/blob/1.9.2.1/lib/Varien/Object.php#L154-L156

I see it is already restored (by duplication) in the base model, base block, base form and so on: 

`\Magento\Framework\Model\AbstractModel::_construct()`:
https://github.com/magento/magento2/blob/02e0378c33054acb0cdb8d731d1e2b2c2069bc1b/lib/internal/Magento/Framework/Model/AbstractModel.php#L201-L203

`\Magento\Framework\View\Element\AbstractBlock::_construct()`
https://github.com/magento/magento2/blob/02e0378c33054acb0cdb8d731d1e2b2c2069bc1b/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L223-L228

`\Magento\Framework\Data\Form\AbstractForm::_construct()`
https://github.com/magento/magento2/blob/02e0378c33054acb0cdb8d731d1e2b2c2069bc1b/lib/internal/Magento/Framework/Data/Form/AbstractForm.php#L71-L73

Why does it absent in `\Magento\Framework\DataObject`?

**Comment by andimov** [comment]
@mage2pro 
Could you please add the description of steps, actual result and expected result to this ticket?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Suggest-to-restore-parameterless-constructor-construct-in-the/idi-p/45380).
