### ISSUE TITLE
Rest API Categories excludes other root Categories

### ISSUE THREAD

**Issue by owenhaynes** [magento/magento2#2193]
If you have more then one root category the following endpoint only ever returns one.

Have 2 root categories (default and test root) the following is returned

GET /rest/V1/categories
```json
{"id":2,"parent_id":1,"name":"Default Category","is_active":true,"position":1,"level":1,"product_count":0,"children_data":[{"id":3,"parent_id":2,"name":"Cat 1","is_active":true,"position":1,"level":2,"product_count":0,"children_data":[{"id":4,"parent_id":3,"name":"Cat 1 sub","is_active":true,"position":1,"level":3,"product_count":0,"children_data":[{"id":5,"parent_id":4,"name":"Cat 1 sub sub","is_active":true,"position":1,"level":4,"product_count":1,"children_data":[]}]}]}]}
```
should this end point not return an array so that all the root categories are listed?

This is very similar to #2096, as I guess he was only using root categories

**Comment by choukalos** [comment]
yes this looks like a bug; you should be able to see the 2nd 'test' root category.  Internal ticket MAGETWO-44763

**Comment by choukalos** [comment]
Closing 44763;  this isn't a bug - you can only have 1 root category per store view.  If you create a root category in admin under default it's just a floating category.  You should really be creating a root category associated with a store view.  Seems we should add a service to assign categories to store view ( APIs auto assigns if you call out a store view ( not default ) in your url ).  I'll put that work in our internal epic - MAGETWO-11434

**Comment by mad0house** [comment]
if that that case could we at least remove the default category from the root of this end point? as it does not flow as categories should return some sort of list? or users will have to filter this when using rectangular or similar as it expects a collection at /rest/V1/categories

**Comment by mackelito** [comment]
Is there any examples using Restangular? If yes I would love to see it! :)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Rest-API-Categories-excludes-other-root-Categories/idi-p/46506).
