### ISSUE TITLE
Need the possibility to load CSS asynchronously

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2194]
The decision whether a JavaScript component need be shown could be made when the layout is already built, so the component is unable to add its CSS resources by the standard way (`\Magento\Framework\View\Page\Config::addPageAsset()`).
Is any standard possibility to load stylesheet asynchronously? (like [`require-css`](https://github.com/guybedford/require-css) do).

**Comment by kandy** [comment]
You can use requirejs + data-mage-init / x-magento-init. See: http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js_init.html

**Comment by dfediuk** [comment]
I do not see any word about CSS there.

**Comment by kandy** [comment]
Sorry, i missed that it's about css.   require-css will be good for this

**Comment by dfediuk** [comment]
My workaround solutions: https://mage2.pro/t/149

**Comment by guz-anton** [comment]
You can do it now in your project just with mentioned `require-css`.
Steps to do:
0. Imagine you are writing own Magento module
1. You go to `view/frontend` folder under Your module.
2. Create file `requirejs-config.js` with content:
````javascript
var config = {
 'map': {
  '*': {
   'css': 'Your_Module/js/require-css'
// 'css': 'https://cdnjs.cloudflare.com/ajax/libs/require-css/0.1.8/css.js'
// 'css': 'https://cdn.jsdelivr.net/require-css/0.1.8/css.min.js'
 }
};
````
3. Put source from `https://cdnjs.cloudflare.com/ajax/libs/require-css/0.1.8/css.js` to `Your/Module/view/base/web/js/require-css.js`
4. Here you are! You can use it. For example:
````javascript
require([ 'css!mage/calendar' ], function() {
   // JS code is ready to use markup with styles
});
````

And now Magento has no precedent to use css load in JS code. So we doesn't provide such plugin out-of-the-box.

**Comment by anton-huz** [comment]
Hi Dmitriy,
We decide to make improvement in this area. We'll do some investigation under MAGETWO-55352.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Need-the-possibility-to-load-CSS-asynchronously/idi-p/47188).
