### ISSUE TITLE
Upgrade from 2.3.0 => 2.3.1 failed. "Unable to unserialize value"

### ISSUE THREAD

**Issue by abcpremium** [magento/magento2#21957]
Hey,

I was trying to upgrade from Magento 2.3.0 to Magento 2.3.1 via composer. While downloading all dependencies worked, the setup:upgrade command fails instantly. Any way to fix this? Details below:

### Preconditions (*)
1. Magento 2.3.0
2. No changes made to any core code files
3. PHP 7.2.16
4. memory_limit 2G

### Steps to reproduce (*)
1. Change directory to the Magento root.
2. Run `composer require magento/product-community-edition 2.3.1 --no-update`
3. Run `composer update`
4. Run `php bin/magento setup:upgrade`

### Expected result (*)
1. The upgrade procedure should start
2. After that you should be able to compile, deploy etc.
3. Upgrade should succeed

### Actual result (*)
1. When running setup:upgrade the following error appears: **Unable to unserialize value. Error: Syntax error**

**Comment by magento-engcom-team** [comment]
Hi @abcpremium. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abcpremium do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by abcpremium** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @abcpremium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @abcpremium, here is your [Magento instance](https://i-21957-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21957-2-3-develop.instances.magento-community.engineering/admin](https://i-21957-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by abcpremium** [comment]
I tried to connect via SSH to the deployed instance, which does not seem to be possible. How should I reproduce the issue then?

EDIT: I used my own second vanilla magento instance and I can reproduce the issue.

**Comment by monotheist** [comment]
@abcpremium Flush your redis cache. And you should be all set. I am facing different error during compilation. 

In Generator.php line 218:

Source class "\Magento\Elasticsearch6\Model\Adapter\FieldMapper\ProductField" for "Magento\Elasticsearch6\Model\Adapter\FieldMapper\P
roductFieldMapper" generation does not exist.

**Comment by abcpremium** [comment]
@ethniccode Thank you that worked. However I face a similar issue to yours:

```
In Generator.php line 218:
                                                                                                                                          
  Source class "\AuthorizenetAcceptjsVirtualErrorMessage" for "AuthorizenetAcceptjsVirtualErrorMessageMapper" generation does not exist.
```

**EDIT:** Running the `setup:di:compile` a second time resolved the issue for me.

**Comment by monotheist** [comment]
@abcpremium I tried setup di:compile multiple times. Doesn't seem to work for me. Also can you tell me if you are facing this issue. https://github.com/magento/magento2/issues/20255

**Comment by abcpremium** [comment]
@ethniccode Sorry to hear that. But regarding your question, I do not have that issue. However now with 2.3.1 some JS files are missing. Only some, not all ... weird...

**Comment by mikehenze** [comment]
@ethniccode I am facing the same problem as you with the Elasticsearch6 error.
Please share your solution when you find it.

**Comment by monotheist** [comment]
@mikehenze Sure. I will do that. You also please share if you find a solution.

**Comment by mikehenze** [comment]
@ethniccode You can disable the Elasticsearch6 module and continue for now:
php bin/magento module:disable Magento_Elasticsearch6

**Comment by monotheist** [comment]
@mikehenze Thanks Mike. Do let me know if you find a permanent solution. This seems to be a workaround.

**Comment by ahentea** [comment]
Clearing redis cache ( `redis-cli flushall` ) resolved the issue for me.

**Comment by ndianabasi** [comment]
> 
> 
> Clearing redis cache ( `redis-cli flushall` ) resolved the issue for me.

This should be part of the steps outlined in the upgrade document (https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html). The command should be run after `composer update `and before `bin/magento cache:clean`.

The Magento team should take note of this.

**Comment by QuentinFarizon** [comment]
Got this error too when upgrading to 2.3.1
Flushing redis cache manually is a working workaround, but a permanent solution should be found.

**Comment by engcom-Alfa** [comment]
I can't reproduce this issue on 2.3-develop.
