### ISSUE TITLE
magento2 shipping method :Table Rates import issue : Windows

### ISSUE THREAD

**Issue by phpdevgeek** [magento/magento2#2195]
Right now I am trying to import table rates, shipping method rates in Magento 2 in windows environment.But whenever I am trying to import it throw me error like

The file "C:/Windows/Temp/E:/wamp/tmp/php9B36.tmp" doesn't exist

I have already set upload_tmp_dir to E:/wamp/tmp, I don't know why it appends C drive directory.

**Comment by alena-marchenko** [comment]
Hi,
please try to change upload_tmp_dir = "E:/wamp/tmp" to upload_tmp_dir = "C:/Windows/Temp" in php.ini file and restart apache. This should resolve the issue.

**Comment by icreativetechnology** [comment]
hello I am changed change upload_tmp_dir = "E:/wamp/tmp" to upload_tmp_dir = "C:/Windows/Temp" in php.ini  but there are also getting error.
