### ISSUE TITLE
Magento\Framework\View\Asset\File is not checked if it's indeed a file

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#2196]
This happens when I request an non-existent asset, like `http://m2.dev/static/frontend/Site/default/en_US/js/what.js`. 

The file is resolved to bool `false`, but, when prepending the full path, it ends up becoming `/var/www/site/releases/20151027072301/` - hence a folder -, so it fools the system into thinking that it exists, but it's no the file that exists, but the folder. Finally, `assertIsFile` does the right thing, but it's a bit too late to be honest.

```
The "/var/www/site/releases/20151027072301/" file doesn't exist or not a file
#0 /var/www/site/releases/20151027072301/lib/internal/Magento/Framework/Filesystem/Directory/Write.php(145): Magento\Framework\Filesystem\Directory\Write->assertIsFile(false)
#1 /var/www/site/releases/20151027072301/lib/internal/Magento/Framework/App/View/Asset/MaterializationStrategy/Symlink.php(30): Magento\Framework\Filesystem\Directory\Write->createSymlink(false, 'frontend/Site/...', Object(Magento\Framework\Filesystem\Directory\Write))
#2 /var/www/site/releases/20151027072301/lib/internal/Magento/Framework/App/View/Asset/Publisher.php(65): Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink->publishFile(Object(Magento\Framework\Filesystem\Directory\Write), Object(Magento\Framework\Filesystem\Directory\Write), false, 'frontend/Site/...')
#3 /var/www/site/releases/20151027072301/lib/internal/Magento/Framework/App/View/Asset/Publisher.php(49): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#4 /var/www/site/releases/20151027072301/lib/internal/Magento/Framework/App/StaticResource.php(118): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#5 /var/www/site/releases/20151027072301/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\StaticResource->launch()
#6 /var/www/site/releases/20151027072301/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#7 {main}
```
I think the check needs to be done at the `\Magento\Framework\View\Asset\File::__construct()` level, when passing `$filePath`.

**Comment by buskamuza** [comment]
Hi @adragus-inviqa ,

`$filePath` in the constructor of `\Magento\Framework\View\Asset\File` is intended file path, it may be absent at the moment the constructor is called. Real file is calculated in `\Magento\Framework\View\Asset\File::getSourceFile()` basing on the intended file path (`$filePath`).

Regarding the issue, looks like it's somewhere in the `\Magento\Framework\View\Asset\Source::getFile()` - it should return `false`, if requested file is not found. If `false` is returned `\Magento\Framework\View\Asset\File::getSourceFile()` will throw an exception and the execution will not come to https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/App/StaticResource.php#L108 .

Do you have the requested file (for your `frontend/Site/default` theme) inside Magento root folder or is it outside?

**Comment by vzabaznov** [comment]
Hi @adragus-inviqa if you still have such problems please provide description according to the template, provide the used version, and create new bug.
Closed now as no update
