### ISSUE TITLE
Need a standard way to detect whether the layout has already been built

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2198]
There is an internal field `\Magento/Framework/View/Layout/Builder::$isBuilt`
https://github.com/magento/magento2/blob/ffa02d82c6344c76ea6de8b50d9612b3200ea2c7/lib/internal/Magento/Framework/View/Layout/Builder.php#L61
Need a public method.

There is an event `layout_generate_blocks_after`: 
https://github.com/magento/magento2/blob/ffa02d82c6344c76ea6de8b50d9612b3200ea2c7/lib/internal/Magento/Framework/View/Layout/Builder.php#L133

But it is inconvenient to listen for the event while an extension just need to get the current layout state: built or not.

**Comment by andimov** [comment]
@mage2pro 
Could you please add the description of steps, actual result and expected result to this ticket?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Need-a-standard-way-to-detect-whether-the-layout-has-already/idi-p/45378).
