### ISSUE TITLE
Custom option Price not consider the Catalog rule discount in Cart

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#21990]
Products with custom option and price display correct on Product page but on cart page its not include the catalog discount.
Example: product price = 100.00 (Excluding Tax); custom option price = 0
10% Catalog discount applied to product.
10% Tax Will apply

### Preconditions (*)
1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)
1. Create Simple Product with a price of 100.00 and add a custom option with a price 0
2. Create a 10% catalog price rule for this product and apply rules
3. Create 10 % Tax Rule
4. Price Display Settings should be Including Tax in Stores -> Configuration -> Sales -> Tax 

### Expected result (*)
1. Shopping cart should be display price after calculating discount which should be 99

### Actual result (*)
1. Product page Price is correct
2. When adding to cart product with custom option then It does not calculate the 10 % discount in the cart
![Screenshot_1](https://user-images.githubusercontent.com/16815711/55139684-5831a380-515c-11e9-9931-efbf76478f13.png)
![Screenshot_2](https://user-images.githubusercontent.com/16815711/55139688-58ca3a00-515c-11e9-8937-fd5ba74243f1.png)
![Screenshot_3](https://user-images.githubusercontent.com/16815711/55139689-58ca3a00-515c-11e9-8d27-877a2773e2a8.png)
![Screenshot_4](https://user-images.githubusercontent.com/16815711/55139690-58ca3a00-515c-11e9-8fc3-4686110d7bd9.png)

**Comment by magento-engcom-team** [comment]
Hi @jigar48. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jigar48 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jigar48** [comment]
yes

**Comment by ghost** [comment]
Hi @jigar48 thank you for you report, this is non issue, please use this settings to have correct result
![notabug](https://user-images.githubusercontent.com/40756439/55860505-0f76e300-5b7d-11e9-9158-7e7b9322b930.png)
thanks for collaboration :+1:

**Comment by jigar48** [comment]
@engcom-backlog-nazar 

The result should be correct in both cases, either it is Including Tax Or Excluding Tax.
You need to follow up on this issue.

**Comment by maghamed** [comment]
The ticket should be re-validated

**Comment by AlexWorking** [comment]
Hello @jigar48, @maghamed. We revised Your issue and we confirm it's not a bug. lets take Your very case. Please take a look of the following things:
1. Price Display Settings You are most probably talking about in step 4
![1](https://user-images.githubusercontent.com/27814011/58428668-dd2d3080-80ab-11e9-8837-075461853f9e.png)
are responsible for Product Page price:
![2](https://user-images.githubusercontent.com/27814011/58428746-2a110700-80ac-11e9-926d-20a0debb4cb3.png)
2. Display Prices in Shopping Cart Display Settings 
![3](https://user-images.githubusercontent.com/27814011/58428850-8542f980-80ac-11e9-97f8-89c615e07826.png)
is responsible for theese two prices in the Cart:
![4](https://user-images.githubusercontent.com/27814011/58429132-89234b80-80ad-11e9-9165-d2698e3dfe5b.png)
3. Display Subtotal in Shopping Cart Display Settings
![5](https://user-images.githubusercontent.com/27814011/58429265-05b62a00-80ae-11e9-8f92-2407e7c2bd5d.png)
is responsible for Subtotal in the Cart:
![6](https://user-images.githubusercontent.com/27814011/58429383-5f1e5900-80ae-11e9-88bd-c62dda1d1a91.png)
You may configure all of those price display settings just as You like.

**Comment by sdzhepa** [comment]
Hello @jigar48 @AlexWorking @maghamed 

As we can see from the thread and last https://github.com/magento/magento2/issues/21990#issuecomment-496250461 it is a configuration issue but not a bug. Magento has a lot of tax calculation and tax display settings and it could confuse.

Little bit more details about tax setting could be found on DevDocs: https://docs.magento.com/m2/ee/user_guide/tax/tax-settings-general.html

Close this issue for now with resolution `non-issue`
