### ISSUE TITLE
Transaction Rest API call timing out

### ISSUE THREAD

**Issue by jwilliamson1098** [magento/magento2#21997]
### Preconditions (*)

1. Magento 2.3.0
2. Stripe Credit Card Plugin 1.9.0 / Tested on Vanilla build using Braintree payment
3. Clean installation, with no transactions
4. Credit card set to separate Authorisation and Capture
5. Apache2 webserver. Php 7.2.

### Steps to reproduce (*)

1.  Create a dummy sale, using a test Credit Card number
2. Transaction created as Authorisation successfully.
3. REST call of transactions (/V1/transactions?searchCriteria) returns the transaction correctly. Response is almost immediate.
4. Raise an invoice on the order. Capture online. Works Successfully.
5. Check transactions from admin web interface, shows all correct. Transaction is at Capture state and closed.
6. Re-run the same REST call above. It times out.

### Expected result (*)

1. All transactions should be returned to the REST call.
2. Apache2 logs show REST call in the access log.

### Actual result (*)

1. Request times out.
2. Nothing is shown in the logs (neither in Magento logs or in Apache2 logs.

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jwilliamson1098 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jwilliamson1098** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098, here is your [Magento instance](https://i-21997-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21997-2-3-develop.instances.magento-community.engineering/admin](https://i-21997-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jwilliamson1098** [comment]
> Hi @jwilliamson1098. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @jwilliamson1098 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ *]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by jwilliamson1098** [comment]
Confirm the issue is the same on the vanilla instance created, using the Braintree card payment.

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098, here is your [Magento instance](https://i-21997-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21997-2-3-develop.instances.magento-community.engineering/admin](https://i-21997-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jwilliamson1098** [comment]
> Hi @jwilliamson1098. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @jwilliamson1098 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no

YES I confirm it is recreated on the vanilla magento following the steps.

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jwilliamson1098, here is your [Magento instance](https://i-21997-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21997-2-3-develop.instances.magento-community.engineering/admin](https://i-21997-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jwilliamson1098** [comment]
@magento-engcom-team Yes I was able to reproduce it on 2.3.x

**Comment by ghost** [comment]
HI @jwilliamson1098 thank you for you report, i'm not able to reproduce following steps you described, on clean magento 2.3-dev instance, please provide steps to reproduce without any 3th party extensions.

**Comment by lilbumblebear** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by lilbumblebear** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by lilbumblebear** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by lilbumblebear** [comment]
I'm having a similar issue, and having trouble testing without adding a plugin to Magento because payment methods have been moved outside of core magento code.  None of the default Magento payment methods create a transaction for the payment.  When I query for a specific transaction ID, the rest API returns, when I use the searchCriteria with payment_id = n, if none exist, then it returns empty results quickly, but if results exist, it times out.
