### ISSUE TITLE
adminhtml - top menu

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2200]
Hi,

The screenshot here shows that the admin menu is at the top, but on my system it's on the left. I prefer it on the top, is there anyway to change it?

http://ubertheme.s3.amazonaws.com/Blog/dec2014/magento2feature/blog/BackendM.jpg

Thanks

**Comment by dfediuk** [comment]
It is an old screenshot. No way to return it to the top (without programming).

**Comment by craigcarnell** [comment]
@dfediuk That's a shame. If you have a lot of people trained to use it on the top that is!

**Comment by tkacheva** [comment]
Admin menu became vertical after admin UI update

**Comment by daim2k5** [comment]
@craigcarnell i close this issues because i think you got your answer. If not please feel free to reopen the issue
