### ISSUE TITLE
"Storage Configuration For Media" isn't respected 

### ISSUE THREAD

**Issue by matthewwiggins** [magento/magento2#2201]
Hi, as of commit 80c5e2b the store configuration option for storing media on the database doesn't appear to work, at least in how our team is expecting it to. With this enabled, when product images are uploaded they are placed in media/catalogue/product/ and all the image urls point to that location. If those files are then deleted they are never replaced by any process and therefore 404.

Our expectation is that with the option to store media in the database that images will be served from DB via a cache. Please let me know if this is the wrong expectation, or if this is a bug. Thanks!

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by matthewwiggins** [comment]
Reopening - this is a bug. Storing images in the database does not serve them correctly, as it relies on there being an on-disk representation as well.

**Comment by saturn72** [comment]
Hi,

I'm facing the same issue - did you manage to resolve it?

Thank you
