### ISSUE TITLE
Magento2 admin catalog product grid is too slow 

### ISSUE THREAD

**Issue by wasimsayyad** [magento/magento2#22025]

**Comment by wasimsayyad** [comment]
we have magento version2.2.5 , nginx, mysql.
we have more 50,000 product on site category more than 800. whenever we are trying to open product from backend catalog-->product it is taking more than 5 minute to open product grid.
Any help would be appreciated.

**Comment by shikhamis11** [comment]
@wasimsayyad Please update the issues description in valid format

**Comment by Nazar65** [comment]
Hi @wasimsayyad Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site
