### ISSUE TITLE
can't add Header and Footer on checkout page

### ISSUE THREAD

**Issue by hetramjanghu** [magento/magento2#22029]
Hi Developers,
i am developing a e-store using Magento 2.3.0 and facing issue with adding header and footer on checkout page. I am using Magento blank theme as parent
I have tried to overriding "checkout_index_index.xml" in my child theme ->> "app/design/frontend/XXXXXX/xxxx/Magento_Checkout/layout"
        `<referenceBlock` name="minicart" remove="false" />
        `<referenceContainer` name="header.panel" remove="false" />
        `<referenceBlock` name="top.search" remove="false" />
        `<referenceBlock` name="catalog.compare.link" remove="false" />
        `<referenceBlock` name="catalog.topnav" remove="false"/>
        `<referenceContainer` name="footer-container"  remove="false"/>

and
        `<referenceBlock` name="minicart" display="true" />
        `<referenceContainer` name="header.panel" display="true" />
        `<referenceBlock` name="top.search" display="true" />
        `<referenceBlock` name="catalog.compare.link" display="true" />
        `<referenceBlock` name="catalog.topnav" display="true" />
        `<referenceContainer` name="footer-container"  display="true" />

Please suggest a way to do this.

**Comment by ghost** [comment]
Hi @hetramjanghu, same here -> https://github.com/magento/magento2/issues/5849 I'm closing as duplicate. thanks for collaboration.

**Comment by ywsw** [comment]
I am having this same issue with 2.3.1 
Editing checkout_index_index.xml does not help
the #5849 link above is not a duplicate. Please reopen this and advise us how to add the header and footer to the checkout page

**Comment by twoatechguy** [comment]
Experiencing this in 2.3.3.  This is completely unrelated to #5849. 

I was able to change layout="checkout" to layout="1column" and added the code in the initial report to fix this bug. 

```<?xml version="1.0"?>
  <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
   <body>
             <referenceBlock name="minicart" remove="false" />
             <referenceContainer name="header.panel" remove="false" />     
             <referenceBlock name="top.search" remove="false" />
             <referenceBlock name="catalog.compare.link" remove="false" /> 
             <referenceBlock name="catalog.topnav" remove="false"/>
             <referenceContainer name="footer-container"  remove="false"/>
 </body>
 </page> 
```

**Comment by ThakarshiSiddhiDev** [comment]
Thank you so much brother
