### ISSUE TITLE
Issue on lifetime sales figure in admin dashboard

### ISSUE THREAD

**Issue by surendragamage** [magento/magento2#22024]
### Preconditions (*)

1. Magento version 2.2.5 Open Source
2. Shipping - Flat Rate enabled
3. Payment - Check / Money Order enabled

### Steps to reproduce (*)

1. Issue is in lifetime sales figure in admin dashboard
2. This is happening if there are orders create with 100% discount code for both product price and shipping. Follow the below steps,
3. Marketing > Cart Price Rules > Add New Rule
4. Create Rule with following values > Customer group - General, Coupon - Specific Coupon, Coupon Code - XXXX, Actions > Apply - Percent of product price discount, Discount Amount - 100, Apply to Shipping Amount - Yes
5. Add a product to cart and go to checkout
6. Select Flat rate shipping (ex. $5) and proceed
7. Add XXXX discount code and the checkout total become 0, so the customer will pay nothing and complete the order.
8. Go to backend and create a invoice for the above order
9. Check the lifetime sale figure in admin dashboard and you will notice the value is wrong

### Expected result (*)

1. Expected result is 0 as lifetime sale, because the total order got discounted

### Actual result (*)

1. Actual result I got is -5 which is wrong
2. This is because when you are creating the invoice even though you have fully discounted the shipping that does not take in to consideration for life time sale calculation. base_shipping_invoiced will not become 0 in sales_order table. 
3. I did check the calculation for lifetime sale and it is like this,
4. lifetime sale = (base_total_invoiced - base_tax_invoiced - base_shipping_invoiced) - (base_total_refunded - base_tax_refunded - base_shipping_refunded) * base_to_global_rate
5. So in my case this will be come like as follows,
6. (0 - 0 - 5) - (0 - 0 - 0) = -5 (so the lifetime sale should be 0 and not -5)

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22024-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22024-2-2-develop.instances.magento-community.engineering/admin](https://i-22024-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22024-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22024-2-2-develop.instances.magento-community.engineering/admin](https://i-22024-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22024-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22024-2-3-develop.instances.magento-community.engineering/admin](https://i-22024-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98975`, `MAGETWO-98976` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](https://i-22024-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22024-2-3-develop.instances.magento-community.engineering/admin](https://i-22024-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gaurav-473** [comment]
I am working on this #dmcdindia1

**Comment by gaurav-473** [comment]
#imagine2019

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
