### ISSUE TITLE
Typo issue: Magento admin sales order shipment header typo issue

### ISSUE THREAD

**Issue by vishal-7037** [magento/magento2#22030]
There are typo errors found on the Magento admin panel. Please review Sales invoice grid & Sales shipment grid or Sales credit memo grip. You will find typo error for the order column header. In the Sales invoice grid, the header title of a column is **'Order #'** and in Sales shipment/Credit memo grid the header title of a column is **'Order'**. they should be the same.
### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Login to Magento admin
2. Open Sale > Shipment
3. Check header title of Order column.

### Expected result (*)

![2019_03_29_Expected](https://user-images.githubusercontent.com/38535982/55231348-580ed200-5248-11e9-90e6-b82e90d8c6d3.png)

### Actual result (*)

![2019_03_29_Actual](https://user-images.githubusercontent.com/38535982/55231354-5c3aef80-5248-11e9-8347-7ba668a1a085.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98969`, `MAGETWO-98970` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
