### ISSUE TITLE
2.2.8 cart bug

### ISSUE THREAD

**Issue by brokentuskk** [magento/magento2#22042]
Magento 2.2.8 EE

Steps to reproduce
1. Add item to cart
2. Enter cart
3. Change quantity and hit return instead of pressing button.

Expected result
1. Cart quantity update
2. Cart total update

Actual result
1. Deletion of all items in cart

This is visible on stock/Luma carts. The clear cart button, which may or may not be hidden, takes focus when the quantity box is selected. Pressing return activates it and your cart is wiped out. Revert to 2.2.7 behavior returns to normal.

**Comment by brokentuskk** [comment]
@magento-engcom-team give me 2.2.8-develop instance

**Comment by magento-engcom-team** [comment]
Hi @brokentuskk. Thank you for your request. I'm working on Magento 2.2.8-develop instance for you

**Comment by gwharton** [comment]
Yes, I see this is 2.2.8 also.

**Comment by maddumarala** [comment]
@brokentuskk 
This issue has been reported before
https://github.com/magento/magento2/issues/21499
See comments for pull request

**Comment by brokentuskk** [comment]
That's a 2.3 issue reported in February. This is a problem you introduced going from 2.2.7 to 2.2.8. You might tag your tech support database. Because support says this isn't an issue at all.

**Comment by hostep** [comment]
@brokentuskk: it looks like a backport was already created, but somehow forgotten, there seems to be some activity in the last couple of days luckily: https://github.com/magento/magento2/pull/21512
