### ISSUE TITLE
checkout page custom dropdown field can't be save when having caption

### ISSUE THREAD

**Issue by HungTran236** [magento/magento2#22048]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by shikhamis11** [comment]
@HungTran236 please follow issue reporting guideline to report your issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ghost** [comment]
Hi @HungTran236. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Then, please reopen the issue, thank you.
