### ISSUE TITLE
Confirmation Email bug -vers. 2.2.8 - sent from hostname@server

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#22049]
### Preconditions (*)

1. Magento version 2.2.8
2. Upgraded from version 2.2.7
3. Patches successfully applied for the email sender bug (PR-18472) on 2.2.7

### Steps to reproduce (*)

1. Upgraded from Magento 2.2.7 to 2.2.8 via composer
2. 

### Expected result (*)

1. Magento should update appropriately with patches installed, or with a fix to the issue in the framework

### Actual result (*)

1. First when trying to update to 2.2.8 with the PR-18472 patches in place I got an error:
 Could not apply patch! Skipping. The error was: Cannot apply patch patches/composer/PR-18472-Framework.diff

  [Exception]                                                                  
  Cannot apply patch PR-18472: Alternative fix for Multi Store Emails issue,   
  Fix Async Emails issues, Fix Multiple Email issues (patches/composer/PR-184  
  72-Framework.diff)!  
           
2.If i continued on with the update process ie. setup:upgrade or setup:d:compile then I got this error

[RuntimeException]                                                           
  Class Zend\Mail\Message does not exist                                       
  Class Magento\Email\Model\Transport\Interceptor generation error: The reque  
  sted class did not generate properly, because the 'generated' directory per  
  mission is read-only. If --- after running the 'bin/magento setup:di:compil  
  e' CLI command when the 'generated' directory permission is set to write --  
  - the requested class did not generate properly, then you must add the gene  
  rated class object to the signature of the related construct method, only.  

3. I uninstalled the patch thinking that maybe the issue was fixed and that’s why it wouldn’t allow me to apply the patch.

4. After successfully updating the issue was not fixed, the email was sent from our hostname@server and not from the store email address.

5. Tried applying the patches again after it was updated to 2.2.8. But received this error:

Could not apply patch! Skipping. The error was: Cannot apply patch patches/composer/PR-18472-Framework.diff
  [Exception]                                                                  
  Cannot apply patch PR-18472: Alternative fix for Multi Store Emails issue,   
  Fix Async Emails issues, Fix Multiple Email issues (patches/composer/PR-184  
  72-Framework.diff)!                   

6. Related to issue - https://github.com/magento/magento2/issues/14952

7. Is there another patch I should be applying to 2.2.8? Since the email bug was not fixed?

**Comment by pioneerathletics** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pioneerathletics. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pioneerathletics, here is your [Magento instance](https://i-22049-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22049-2-3-develop.instances.magento-community.engineering/admin](https://i-22049-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hostep** [comment]
Closing this as it is expected that this happens.
Patches are your own responsability, not Magento's.

If Magento changes files between versions 2.2.7 and 2.2.8, and the patches touch those same files, then there is a possibility that existing patches no longer apply. (In this case, several files the patch touches, got changed in https://github.com/magento/magento2/commit/da204ffcbfb & https://github.com/magento/magento2/commit/d196dcc8592)

If you want working patches for the email issue, you can try these I just created: https://github.com/magento/magento2/issues/14952#issuecomment-478103498
