### ISSUE TITLE
mage.toggleAdvanced class toggling broken

### ISSUE THREAD

**Issue by PhilipRowe** [magento/magento2#22040]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Add an element to the page with the following markup:
```html
<a href="#" data-mage-init='{"toggleAdvanced": { "baseToggleClass":"active" }}'>Click Me</a>
```
2. Open inspector and click the element

### Expected result (*)

1. The "active" class should be toggled on the element

### Actual result (*)

1. The active class gets added and then immediately removed from the element

file lib\web\mage\toggle.js contains this function

```js
_toggleSelectors: function () {
    this._super();

    if (this.options.toggleContainers) {
        $(this.options.toggleContainers).toggleClass(this.options.selectorsToggleClass);
    } else {
        this.element.toggleClass(this.options.baseToggleClass);
    }
},
```

If this.options.selectorsToggleClass isn't set it will toggle the class however it also calls this._super(); at the start of the function which runs this:

```js
_toggleSelectors: function () {
    this.element.toggleClass(this.options.baseToggleClass);
},
```

Therefore the active class is added and then instantly removed again.

**Comment by ghost** [comment]
Hi @PhilipRowe thank you for you report, this is expected behavior, please set .containers
`<a href="#" id="sampleid"  data-mage-init='{"toggleAdvanced": {  "baseToggleClass": "active", "toggleContainers": ".some-container-class" }}'>Click Me</a>`
