### ISSUE TITLE
Lock timeout when programmatically creating category.

### ISSUE THREAD

**Issue by dudzio12** [magento/magento2#22057]
### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1. Create simple script with category creation ending with save() method on category.

### Expected result (*)
1. Category should be saved.

### Actual result (*)
1. SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: INSERT  INTO `url_rewrite` (`redirect_type`,`is_autogenerated`,`metadata`,`description`,`store_id`,`entity_type`,`entity_id`,`request_path`,`target_path`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)

Changing timeout config for mysql does not fix this issue.
Everything worked on 2.3.0 branch.
I don't know how to debug it, because I have nothing in sleep any mysql query, only that Insert to `url_rewrite`. I've tested it on 3 different machines and core datebases.

**Comment by a-dite** [comment]
We fixed this problem, in an import module importing categories, by changing DB Transaction Isolation Level Globally from REPEATABLE READ (Default) to READ COMMITED.

**Comment by nimbus2300** [comment]
> We fixed this problem, in an import module importing categories, by changing DB Transaction Isolation Level Globally from REPEATABLE READ (Default) to READ COMMITTED.

Thank you so much - this fixed it for me. 

I added this to /etc/my.cnf in the innodb section, and restarted mysql server:

`transaction-isolation=READ-COMMITTED`

Note using DBeaver/Workbench still displays 'REPEATABLE-READ' even after you set this! But it you hop over to MySQL command line and run this, you should see it set to 'READ-COMMITTED'


```
mysql> show variables like '%_isolation';
+-----------------------+----------------+
| Variable_name         | Value          |
+-----------------------+----------------+
| transaction_isolation | READ-COMMITTED |
+-----------------------+----------------+
1 row in set (0.00 sec)
```

For reference - how my lock error manifested:
Using MySQL 8, for Magento 2.4.1.
This problem manifested when trying to programatically add categories via MySQL. A lock was being made on the url_rewrite table. I discovered the lock by running this MySQL command and observing the values for 'innodb_row_lock*':

`show status`
