### ISSUE TITLE
Customer account confirmation is overwritten by backend customer save

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#22052]
### Preconditions (*)

1. Clean Magento setup 2.3.1
2. Set the account confirmation to **"Yes"** by visiting store > configuration > Customers > Customer Configuration > Create New Account Options > Require Emails Confirmation 

![cuonfig](https://user-images.githubusercontent.com/17308601/55266757-dab28400-527e-11e9-9c85-4e13700b3e4e.png)

### Steps to reproduce (*)

1. Create a new customer account on frontend by visiting "Create a new account" link from header
2. Open Magento backend with valid credentials
3. Go to Customer > All Customers
4. Open the newly created customer and please notice the value of "Confirmed email:" is "Confirmation Required"
5. Now click on "Save and continue"
6. Now Please notice the value of "Confirmed email:" is "Confirmed"

**Customer account while opening customer**
![require](https://user-images.githubusercontent.com/17308601/55267005-0c781a80-5280-11e9-98ad-18e733e71226.png)

**After saving customer**

![confirm](https://user-images.githubusercontent.com/17308601/55267037-2b76ac80-5280-11e9-9b85-8f2673f1668c.png)

### Expected result (*)

1. Customer account should confirm by email link not from by saving customer from backend

### Actual result (*)

1. Customer account is getting confirmed even customer did not click on email activation link

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22052-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22052-2-3-develop.instances.magento-community.engineering/admin](https://i-22052-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98988`, `MAGETWO-98989` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
