### ISSUE TITLE
Import products returns invalid response

### ISSUE THREAD

**Issue by manzanoca** [magento/magento2#22050]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by manzanoca** [comment]
Backoffice Magento tool returns an alert that sais "invalid response" when I try to import my products wuth a CSV file

**Comment by lbajsarowicz** [comment]
Could you share any extra information about the issue?
* Version of Magento
* CSV file that you use
* Server logs

**Comment by shikhamis11** [comment]
@manzanoca  please follow issue reporting guideline to report your issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ghost** [comment]
Hi @manzanoca. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Then, please reopen the issue, thank you.

**Comment by tzsolti** [comment]
This happened to me when I had a CSV file with UTF-16 encoding. Convert your CSV to UTF-8 and then it will work.
