### ISSUE TITLE
Vertical "ice skating" in zoom function in Chrome on product page with large image

### ISSUE THREAD

**Issue by scottsb** [magento/magento2#22053]
### Preconditions (*)
* Magento 2.2.7, but code in question has not been changed in 2.3.x
* Chrome 72

### Steps to reproduce (*)
1. Open product page with a large image included.
2. Open full-screen zoom
3. Zoom in all the way so that the image is larger than the window (shrink browser window if need be)
4. Click and drag image vertically, and then without letting go of mouse, reverse direction

### Expected result (*)
Image pans in proportion to mouse movement. Image pan directly reverses course at the same time the mouse reverses course.

### Actual result (*)
Image pans faster than mouse movement. Image pan continues in initial direction before later reversing course.

See video:
https://www.useloom.com/share/4ec4573b853c44a58999d464f5c21edd

### Analysis
This issue only affects vertical panning, not horizontal panning. This is because of a new buggy approach that was introduced in db8476afd44fa54094d6d3453d14600cb5fc01f5 only for vertical panning, leaving the original approach for horizontal panning. This commit seems it was aimed at fixing #12704 (commit message matches that description), but I'm not sure since the timing doesn't quite match up.

**Comment by ananth-iyer** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ananth-iyer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ananth-iyer** [comment]
@scottsb Please give the resolution of the product image

**Comment by magento-engcom-team** [comment]
Hi @ananth-iyer, here is your [Magento instance](https://i-22053-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22053-2-3-develop.instances.magento-community.engineering/admin](https://i-22053-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by scottsb** [comment]
@ananth-iyer The resolution of product image you need depends on the size of your browser window. You just need one that is large enough to be taller than the full browser height when zoomed in.

**Comment by Mobecls** [comment]
Was able to reproduce on magento 2.3-develop. 
There is a delay between mouse movement and actual image movement.
Image dimension was 3840 × 2160. Screen resolution - 2560x1600.

**Comment by magento-engcom-team** [comment]
@Mobecls Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Mobecls 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99204` were created

**Issue Available**: @Mobecls, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by scottsb** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by scottsb** [comment]
I can verify this still exists on Magento 2.4. Don't have the rights to add the label, though.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
