### ISSUE TITLE
Extension attribute of boolean type case issues for UI implementation in Admin Panel

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#22067]
### Summary
Ui Data provider do not support boolean values for extension attributes.
To make it properly working on frontend, you need to manually cast boolean to corresponding integer in string. For not-extension attributes it works fine.
Reference where convertation take a place for not-extension attributes https://github.com/magento/magento2/blob/2bca2aa1a6c1828c379bb9c75db2810a92cd3d37/app/code/Magento/Ui/DataProvider/SearchResultFactory.php#L98

### Examples (*)
There issue was faced in PRs:
* https://github.com/magento-engcom/msi/pull/2044
* https://github.com/magento-engcom/msi/pull/2125
What you need to face this issue:
1) Create extension attribute with boolean type for entity with adminhtml form (e.g. [tap](https://github.com/magento/inventory/blob/fdf409aacda03c705cccfa5c5069daba598ddc72/InventoryInStorePickupApi/etc/extension_attributes.xml#L10))
2) Add this extension attribute to the edit form and listing (e.g. [tap](https://github.com/magento/inventory/blob/fdf409aacda03c705cccfa5c5069daba598ddc72/InventoryInStorePickupAdminUi/view/adminhtml/ui_component/inventory_source_form.xml#L10))
3) Without manual convertation bool -> string -> int, field will not work properly on edit form. (e.g. [tap](https://github.com/magento/inventory/blob/develop/InventoryInStorePickupAdminUi/Plugin/Ui/DataProvider/ConvertBooleanToStringPlugin.php)).

### Proposed solution
Check if we can add convertation for nested attributes in
https://github.com/magento/magento2/blob/2bca2aa1a6c1828c379bb9c75db2810a92cd3d37/app/code/Magento/Ui/DataProvider/SearchResultFactory.php#L98

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99069` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by evgeniykapelko** [comment]
@magento I'm working on it

**Comment by engcom-Hotel** [comment]
Hello @swnsma,

We have tried to reproduce the issue but the links mentioned in the steps mentioned in the main description do not work. Please update the links, so that we can proceed further with this issue.

> * Create extension attribute with boolean type for entity with adminhtml form (e.g. [tap](https://github.com/magento-engcom/msi/blob/store-pickup/app/code/Magento/InventoryInStorePickup/etc/extension_attributes.xml))
> * Add this extension attribute to the edit form and listing (e.g. [tap](https://github.com/magento-engcom/msi/blob/store-pickup/app/code/Magento/InventoryInStorePickupAdminUi/view/adminhtml/ui_component/inventory_source_form.xml))
> * Without manual convertation bool -> string -> int, field will not work properly on edit form. (e.g. [tap](https://github.com/magento-engcom/msi/blob/store-pickup/app/code/Magento/InventoryInStorePickupAdminUi/Plugin/Ui/DataProvider/AddInStorePickupToDataProvider.php#L25)).

Thanks

**Comment by swnsma** [comment]
Hi,

I have updated the links in the description.
Please let me know if you would need any other assistance.
Thank you.

**Comment by engcom-Hotel** [comment]
Hello @swnsma,

Thanks for the quick reply!

We have tried to reproduce the issue in the latest 2.4-develop branch and it seems the issue is no more reproducible. Please find attached the custom module we have prepared to reproduce this issue:
[Vendor.zip](https://github.com/user-attachments/files/17747564/Vendor.zip)

Let us know if we missed anything.

Thanks
