### ISSUE TITLE
Plugins declared against SessionManager cause crash on class instantiation

### ISSUE THREAD

**Issue by allanpaiste** [magento/magento2#22060]
Crash on application run flow when there are Plugins declared against a Session Manager class where the magic method __call has a Exception throwing logic built into it. 

The problem here comes from the fact that [class Interceptors](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Interception/Interceptor.php#L44) have the following code in them:

```
    if (method_exists($this->subjectType, '___init')) {
        parent::___init();
    }
```

... which in most cases causes no issues except in situations where __call has been declared on a class.  Because method_exists on classes that have [SessionManager::__call](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Session/SessionManager.php#L161) declared will make method_exists to ALWAYS evaluate as TRUE and due to the fact that Session Manager does not have that method directly (it's reserved for Interception Trait), it'll end up dribbling down to __call method where it causes the crash due to - naturally - not starting with none of the valid prefixes (seen below in this patch).

Exception will be something along the lines of ...

```
InvalidArgumentException: Invalid method SomeClass::___init(Array())
```

This means that although the issue is something that will not happen by default, it'll randomly pop up for people based on what extension they have installed.

In short - the chain of events that lead to a crash:

1. Runtime request for SessionManager (or and of it's subclasses) from OM is triggered
1. ... from there OM uses Interception class due to there being Plugins declared against the class
1. ... from there, the Interceptor of the said class is instantiated AND __construct() of Interceptor is called
1. ... from there ___init() of Interception Trait is called
1. ... from there method_exist check for ___init() of the parent class is done (for any class with __call, it's always true).
1. ... from there SessionManager ___init() is called
1. ... from there, the call is routed to __call() as there's no explicit ____init() method on SessionManager
1. ... from there, an Exception is thrown due to __call definitely not starting with any of the typical DataObject method prefixes.
1. ... from there, great sadness.

### Preconditions (*)

1. Use any Magento version since 2.1.0 (the implementation has remained the same both in Interceptor and in SessionManager).

### Steps to reproduce (*)

1. [code] Declare plugin against any of the sub-classes of session manager (can be a no-op plugin; the idea here is to get the interceptor to be generated for the said class; the crash is triggered in interceptor's __construct). A good choice here is to choose Magento\Customer\Model\Session (easy to trigger instantiation for)
2. [store] load front-page

### Expected result (*)
1. Page loads without issues

### Actual result (*)
1. Page crashes because SessionManager throwing an exception due to getting Interception Traits public method getting passed to __call

**Comment by ghost** [comment]
Hi @allanpaiste thank you for you report, i'm not able to reproduce following steps you described, on clean magento 2.3-develop instance, seems like this already fixed. 
![deepin-screen-recorder_Select area_20190417110130](https://user-images.githubusercontent.com/40756439/56271061-4199bf00-6100-11e9-9394-bbdf787334c7.gif)
