### ISSUE TITLE
Category data is changed after saving category link in a loop for different stores

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#22063]
### Summary (*)
When there is a loop going through a few products and linking those products to categories. Some categories get data copied from another store.

### Examples (*)
It's hard to reproduce but imagine that we import/update some product data for different stores. And if we want to link / unlink products to / from "marketing categories" and those categories have different descriptions or other data.
The data may be received  from previous store and saved in current store because `\Magento\Catalog\Model\CategoryLinkRepository` loads categories without specifying store id. And in `\Magento\Catalog\Model\CategoryRepository::get` all entities are stored as cached  in a class property.

### Proposed solution
Since there is no any data about a **store_id** in `\Magento\Catalog\Model\CategoryProductLink` and column for store id in the table `catalog_category_product` we can just load a category from the default store to avoid mismatch because of cache key **all** in CategoryRepository

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99236` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
