### ISSUE TITLE
Multiple custom tabs on product detail page does not work since Magento 2.3.1

### ISSUE THREAD

**Issue by nobodyMO** [magento/magento2#22068]
I use three custom tabs on the product page since Magento 2.1. 
They are defined in a catalog_module_view.xml in my own module. That works fine with 2.3.0, but after update to 2.3.1 only the last defined tab is shown. The two before are ignored. Also the after attribute is ignored. The tab is always the first.

### Preconditions (*)
1. Install Magento 2.3.1
2. Create a custom module
3. Define three custom tabs in catalog_module_view.xml like this:
`
<?xml version="1.0"?>
<page layout="1column" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>		
      <referenceBlock name="product.info.details">
          <block class="Magento\Catalog\Block\Product\View" name="product.info.ingredients" as="ingredigents" template="Vendor_Module::product/view/ingredientstab.phtml" group="detailed_info" after="product.info.description">
              <arguments>
                  <argument translate="true" name="title" xsi:type="string">Ingredients</argument>
              </arguments>
          </block> 
          <block class="Magento\Catalog\Block\Product\View" name="product.info.nutrioninformation" as="nutrioninformation" template="Vendor_Module::product/view/nutriontab.phtml" group="detailed_info" after="product.info.ingredients">
              <arguments>
                  <argument translate="true" name="title" xsi:type="string">Nutrion Information</argument>
              </arguments>
          </block> 
          <block class="Magento\Catalog\Block\Product\View" name="product.info.allergen" as="allergen" template="Vendor_Module::product/view/allergentab.phtml" group="detailed_info" after="product.info.nutrioninformation">
              <arguments>
                  <argument translate="true" name="title" xsi:type="string">Information for allergic persons</argument>
              </arguments>
          </block> 
      </referenceBlock>				  
    </body>		
</page>

`

### Steps to reproduce (*)
Show product detail page

### Expected result (*)
Magento 2.3.0 shows the Tabs correctly:
![custom tab with magento 2 3 0](https://user-images.githubusercontent.com/13558044/55287898-a094cf80-53af-11e9-8517-941dba6ece17.png)

### Actual result (*)
Magento 2.3.1 shows only the last defined tab at the first position:
![custom tab with magento 2 3 1](https://user-images.githubusercontent.com/13558044/55287903-c28e5200-53af-11e9-9c55-580338403959.png)

**Comment by nobodyMO** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @nobodyMO. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by ernesthernandez** [comment]
You need to add the new argument in your catalog_module_view.xml for each custom tab.

` <argument name="sort_order" xsi:type="string">2</argument>`

**Comment by nobodyMO** [comment]
hi @ernesthernandez,
thank you very much for the tip.
With the additional attribute entries the display now works again.
@magento 
It would have been nice if this had been described more clearly in the release notes.

**Comment by lexiconnect** [comment]
Just encountered this issue and while the comment from @ernesthernandez fixes the problem for the site I am developing, I wonder if there should now be a way of calculating how many tabs there are.  What if we install a third party extension and they do not know we have custom tabs on the site?  It appears that this will just overwrite the custom tab if the same sort_order value is set.

**Comment by deloenzien** [comment]
I did the test: 
**TEST1**
tab 'description' sort order 10
tab 'more information' sort order 40
tab 'custom1' sort order 30
tab 'custom2' sort order 40

the last tab overrides the previous tab.  
result: tab 'description'  /  tab 'cutom1'  /  tab 'custom2'

TEST2
tab 'description' sort order 10
tab 'more information' sort order 10
tab 'custom1' sort order 10
tab 'custom2' sort order 10

the last tab overrides the previous tabs.  
result is only: tab 'custom2'
