### ISSUE TITLE
Error on language switcher

### ISSUE THREAD

**Issue by Julen10** [magento/magento2#22079]
### Preconditions (*)
1. Magento 2.3.1
2. PHP 7.2.16

### Steps to reproduce (*)

1. I had 3 languages before the update.
2. I updated the magento version.
3. Got into the main url.

### Expected result (*)

1. The theme loads correctly.

### Actual result (*)

1. Debugging I got an error like this:
`<b>Fatal error</b>:  Uncaught Error: Call to a member function getTargetStoreRedirectUrl() on null in`
2. The html loads:

```
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language-nav">
    <strong class="label switcher-label"><span>Language</span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger-nav"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-default">
                <span>English</span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-target="dropdown">
                                                                            <li class="view-es switcher-option">
                        <a href="<br />
```

3. An error 500 appears.

If I copy and paste the previous version of the file on my theme it works correctly where ` $block->getTargetStorePostData($_lang)` is called instead of `$block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang))`

The line which throws the error is this one: https://github.com/magento/magento2/blob/36097739bbb0b8939ad9a2a0dadee64318153dca/app/code/Magento/Store/view/frontend/templates/switch/languages.phtml#L30

**Comment by ghost** [comment]
HI @Julen10 thank you for you report, i'm not able to reproduce following steps you described, seems like in your extension missing viewModel. can you described more detail ?
![DeepinScreenshot_select-area_20190401112854](https://user-images.githubusercontent.com/40756439/55313959-c4204e80-5471-11e9-8023-39af32dad99b.png)

**Comment by Julen10** [comment]
I have this one inside $block:
```
Array ( [id_modifier] => nav [type] => Magento\Store\Block\Switcher [module_name] => Magento_Store [raw_stores] => Array ( [1] => Array ( [1 (Magento\Store\Model\Store\Interceptor)] => Array ( [store_id] => 1 [code] => default [website_id] => 1 [group_id] => 1 [name] => English [sort_order] => 0 [is_active] => 1 [locale_code] => en_US [home_url] => http://localhost:8080/?___store=default ) [3 (Magento\Store\Model\Store\Interceptor)] => Array ( [store_id] => 3 [code] => es [website_id] => 1 [group_id] => 1 [name] => Español [sort_order] => 0 [is_active] => 1 [locale_code] => es_ES [home_url] => http://localhost:8080/?___store=es ) [4 (Magento\Store\Model\Store\Interceptor)] => Array ( [store_id] => 4 [code] => fr [website_id] => 1 [group_id] => 1 [name] => Francais [sort_order] => 2 [is_active] => 1 [locale_code] => fr_FR [home_url] => http://localhost:8080/?___store=fr ) ) ) [stores] => Array ( [1 (Magento\Store\Model\Store\Interceptor)] => *** RECURSION *** [3 (Magento\Store\Model\Store\Interceptor)] => *** RECURSION *** [4 (Magento\Store\Model\Store\Interceptor)] => *** RECURSION *** ) ) 
```

And getViewModel() returns an empty response, I don´t know even if it´s defined somewhere on Switcher.php

**Comment by ghost** [comment]
@Julen10 can you show how you implemented the switcher ?

**Comment by Julen10** [comment]
In default.xml I use the block like this:  
`<block class="Magento\Store\Block\Switcher" name="store_language" as="store_language" template="switch/languages.phtml"/>`

Then in header.phtml:
```
<div class="child-content right-content">
                    <?php echo $topSearch ?>
                    <?php echo $storeLanguage ?>
                    <?php echo $currency ?>
                    <?php echo $miniCart ?>
                </div>
```

With this variable defined:  
`$storeLanguage = $block->getChildHtml('store_language');`

And I didn´t edit the module_store template, I use the magento´s vendor template (https://github.com/magento/magento2/blob/36097739bbb0b8939ad9a2a0dadee64318153dca/app/code/Magento/Store/view/frontend/templates/switch/languages.phtml)

**Comment by ghost** [comment]
@Julen10 what the version of magento you have before upgrade ? 2.3.0 ?

**Comment by Julen10** [comment]
Yes, and using this archive all works perfect (https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Store/view/frontend/templates/switch/languages.phtml)

**Comment by ghost** [comment]
@Julen10 try this example 
```
   <block class="Magento\Store\Block\Switcher" name="store_language" as="store_language" template="Magento_Store::switch/languages.phtml">
                        <arguments>
                            <argument name="view_model" xsi:type="object">Magento\Store\ViewModel\SwitcherUrlProvider</argument>
                        </arguments>
                    </block>
```

**Comment by Julen10** [comment]
Same issue, trying to call the function on null

**Comment by ghost** [comment]
@Julen10 I'm able to reproduce following steps you described, and you have wrong default.xml please use this
```
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<page layout="3columns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <update handle="default_head_blocks"/>
    <body>
        <referenceContainer name="header.container">
            <container name="header.panel.wrapper" htmlClass="panel wrapper" htmlTag="div" before="-">
                <container name="header.panel" label="Page Header Panel" htmlTag="div" htmlClass="panel header">
                    <block class="Magento\Store\Block\Switcher" name="store_language" as="store_language" template="Magento_Store::switch/languages.phtml">
                        <arguments>
                            <argument name="view_model" xsi:type="object">Magento\Store\ViewModel\SwitcherUrlProvider</argument>
                        </arguments>
                    </block>
                </container>
            </container>
        </referenceContainer>
    </body>
</page>
```

**Comment by mauveine** [comment]
@engcom-backlog-nazar 
I've tried to apply your fix and I still have the issue.
Magento 2.3.1 with PHP7.1

```
<referenceContainer name="header.container">
            <block class="Magento\Theme\Block\Html\Header" name="header" as="header" after="-">
                <arguments>
                    <argument name="show_part" xsi:type="string">welcome</argument>
                </arguments>

                <block class="Magento\Store\Block\Switcher" name="store_language" as="store_language"
                       template="Magento_Store::switch/languages.phtml">
                    <arguments>
                        <argument name="view_model" xsi:type="object">Magento\Store\ViewModel\SwitcherUrlProvider
                        </argument>
                    </arguments>
                </block>
             </block>
</referenceContainer>
```

**Comment by sushantvishwas1990** [comment]
Override languages.phtml in your theme with the following content:
path :/magento_root_direcory/app/design/frontend/VendorName/ThemeName/Magento_Store/templates/switch/languages.phtml

`<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="javascript:void(0)" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang) ?>'>
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>`
