### ISSUE TITLE
Exporting Products - Fatal Error Uncaught Error Call to a member function getName() on null

### ISSUE THREAD

**Issue by garmentprinterink** [magento/magento2#22088]
### Preconditions (*)

1. Magento 2.3
2.

### Steps to reproduce (*)

1. Create a fresh version of Magento 2.3
2. Go to: System > Data Transfer > Export > Products - csv 

### Expected result (*)

1. I expected to see a form that I can use to export products
2.

### Actual result (*)

1. Fatal error: Uncaught Error: Call to a member function getName() on null in /home/gpi/public_html/shop/vendor/magento/module-catalog-import-export/Model/Export/Product.php:444 Stack trace: #0 /home/gpi/public_html/shop/vendor/magento/module-catalog-import-export/Model/Export/Product.php(412): Magento\CatalogImportExport\Model\Export\Product->initCategories() #1 /home/gpi/public_html/shop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): Magento\CatalogImportExport\Model\Export\Product->__construct(Object(Magento\Framework\Stdlib\DateTime\Timezone), Object(Magento\Eav\Model\Config), Object(Magento\Framework\App\ResourceConnection\Interceptor), Object(Magento\Store\Model\StoreManager), Object(WeltPixel\Backend\Model\Logger), Object(Magento\Catalog\Model\ResourceModel\Product\CollectionFactory), Object(Magento\ImportExport\Model\Export\Config), Object(Magento\Catalog\Model\ResourceModel\ProductFactory), Object(Magento\Eav\Model\ResourceModel\Entity\Attribute\Set\CollectionFactory), Object(Magento\Catal in /home/gpi/public_html/shop/vendor/magento/module-catalog-import-export/Model/Export/Product.php on line 444
2.
![image](https://user-images.githubusercontent.com/43342733/55333062-85d06280-5464-11e9-979e-5e4b861a2667.png)
https://gyazo.com/15d0f4b5c92d45eccadc3af799650ee1

**Comment by ghost** [comment]
Hi @garmentprinterink thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.3.1 and 2.3-develop instance, this may be related to you custom modules, or data, please verify you category data.
