### ISSUE TITLE
Not focusable moreButton on Catalog page using Tab

### ISSUE THREAD

**Issue by Amadeco** [magento/magento2#22085]
Good afternoon,

In testing _lib/web/mage/smart-keyboard-handler.js_ with a custom theme, I have noticed you can not have the focus on more swatches button in products grid.

I have made a test on a fresh install of Magento 2.3.0

a tag have not the focus even if I had tabindex="0", role="button" attributes. I do not know why. However if I change to html tag to button, everything is back to normal.

That is too bad, developers have taken in account the Keyboard Accessibility in the entire script, event this link.

### Preconditions (*)

1.  You need to have a product with more than 3 swatches option
2. Option in 
Stores -> Configuration -> Catalog / Catalog -> Swatches per Product set to 3
Show Swatches in Product List set to Yes

### Steps to reproduce (*)

1. Try to navigate in the products list with keywoard Tab input

### Expected result (*)

1. When you navigate with the keywoard, more link button must have the focus

### Actual result (*)

1. More link button not have the focus

![Capture d’écran 2019-04-01 à 13 34 35](https://user-images.githubusercontent.com/2975845/55325558-c2608600-5485-11e9-9720-7c1e10610afd.png)

I did not figure why the current code can not have the focus.

Ilan PARMENTIER

**Comment by Amadeco** [comment]
### Current solution have I found

https://github.com/magento/magento2/blob/2bca2aa1a6c1828c379bb9c75db2810a92cd3d37/app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js#L514
Change to 
                    `html += '<button class="' + moreClass + '"><span>' + moreText + '</span></button>';`

https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/lib/web/css/source/lib/_buttons.less#L192

to have the same style as before patch.

**Comment by Amadeco** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mageho. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mageho, here is your [Magento instance](https://i-22085-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22085-2-3-develop.instances.magento-community.engineering/admin](https://i-22085-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Amadeco** [comment]
Verified on Magento 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99120`, `MAGETWO-99121` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by niravkrish** [comment]
Not Able To Reproduce in Morzilla Firefox Browser 66.0.2 (64-bit) in My Linux Mint  System.

**Comment by pushpagupta-magento** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pushpagupta-magento. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pushpagupta-magento, here is your [Magento instance](https://i-22085-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22085-2-3-develop.instances.magento-community.engineering/admin](https://i-22085-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rajeshwebkul** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul, here is your [Magento instance](https://i-22085-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22085-2-3-develop.instances.magento-community.engineering/admin](https://i-22085-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahsn** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [Magento instance](https://i-22085-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22085-2-3-develop.instances.magento-community.engineering/admin](https://i-22085-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
I am closing this as this is MacOS + FireFox specific thing. Firefox respects the setting in MacOS keyboard setting.

> In System Preferences → Keyboard, in the Shortcuts pane, check the “all controls” radio at the bottom then restart the browser.

More information on this:

- https://stackoverflow.com/questions/3846868/why-wont-tabindex-work-with-firefox
- https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox

My assumption would be that in case anybody really wanted to use the keyboard to navigate, they would have this setting enabled.
