### ISSUE TITLE
The stock item was unable to be saved. Please try again.

### ISSUE THREAD

**Issue by djixas** [magento/magento2#22094]
### Preconditions (*)
Magento: 2.3.1
PHP 7.2 + MySQL 5.6

The following extensions were disabled during fresh install

Amazon_Core
Amazon_Payment
Amazon_Login
Dotdigitalgroup_Email
Klarna_Core
Klarna_Kp
Klarna_Ordermanagement
Magento_Authorizenet
Magento_AuthorizenetAcceptjs
Magento_Braintree
Magento_Dhl
Magento_DownloadableGraphQl
Magento_DownloadableImportExport
Magento_Fedex
Magento_InventoryProductAlert
Magento_NewRelicReporting
Magento_OfflinePayments
Magento_OfflineShipping
Magento_ReleaseNotification
Magento_SampleData
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Ups
Magento_Usps
Magento_Weee
Magento_WeeeGraphQl
Magento_WishlistAnalytics
Magento_WishlistGraphQl
MSP_ReCaptcha
MSP_TwoFactorAuth
Temando_Shipping
Vertex_Tax

### Steps to reproduce (*)
1. Install Magento with these extensions off
2. Try to add any item, configurable, simple or not
3. Save it

### Expected result (*)

1. It should work if.
2. Not sure if related to extensions disabling, but should not allow to disable something that throws error

### Actual result (*)

The stock item was unable to be saved. Please try again.

![pic](https://user-images.githubusercontent.com/12409425/55345985-fbb2e900-54b9-11e9-9e52-37d7c0fcacb6.png)

from debug.log

[2019-04-01 17:08:48] main.CRITICAL: The stock item was unable to be saved. Please try again. {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): The stock item was unable to be saved. Please try again. at /home/xxxx/public_html/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:187, LogicException(code: 0): Indexer handler is not available: elasticsearch6 at /home/xxxx/public_html/vendor/magento/module-catalog-search/Model/Indexer/IndexerHandlerFactory.php:79)"} []
[2019-04-01 17:08:48] main.CRITICAL: Exception message: The stock item was unable to be saved. Please try again.
Trace: <pre>#1 Magento\CatalogInventory\Model\StockRegistry->updateStockItemBySku() called at [generated/code/Magento/CatalogInventory/Model/StockRegistry/Interceptor.php:128]
#2 Magento\CatalogInventory\Model\StockRegistry\Interceptor->updateStockItemBySku() called at [vendor/magento/module-catalog-inventory/Observer/SaveInventoryDataObserver.php:110]
#3 Magento\CatalogInventory\Observer\SaveInventoryDataObserver->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:72]
#4 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:60]
#5 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#6 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#7 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/Model/AbstractModel.php:828]
#8 Magento\Framework\Model\AbstractModel->afterSave() called at [vendor/magento/module-catalog/Model/Product.php:963]
#9 Magento\Catalog\Model\Product->afterSave() called at [generated/code/Magento/Catalog/Model/Product/Interceptor.php:349]
#10 Magento\Catalog\Model\Product\Interceptor->afterSave() called at [vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php:34]
#11 Magento\Framework\EntityManager\Observer\AfterEntitySave->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:72]
#12 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:60]
#13 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#14 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#15 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/EntityManager/EventManager.php:52]
#16 Magento\Framework\EntityManager\EventManager->dispatchEntityEvent() called at [vendor/magento/framework/EntityManager/Operation/Create.php:123]
#17 Magento\Framework\EntityManager\Operation\Create->execute() called at [vendor/magento/framework/EntityManager/EntityManager.php:96]
#18 Magento\Framework\EntityManager\EntityManager->save() called at [vendor/magento/module-catalog/Model/ResourceModel/Product.php:677]
#19 Magento\Catalog\Model\ResourceModel\Product->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php:58]
#22 Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback() called at [vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php:28]
#23 Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#24 Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Cache/FlushCacheByTags.php:68]
#25 Magento\Framework\App\Cache\FlushCacheByTags->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#26 Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#27 Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php:273]
#28 Magento\Catalog\Model\ResourceModel\Product\Interceptor->save() called at [vendor/magento/framework/Model/AbstractModel.php:654]
#29 Magento\Framework\Model\AbstractModel->save() called at [generated/code/Magento/Catalog/Model/Product/Interceptor.php:2442]
#30 Magento\Catalog\Model\Product\Interceptor->save() called at [vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php:131]
#31 Magento\Catalog\Controller\Adminhtml\Product\Save->execute() called at [generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php:24]
#32 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#33 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#34 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#35 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#36 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#37 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#38 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#39 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php:39]
#40 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#41 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#42 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#43 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#44 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#45 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#46 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#47 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#48 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre> [] []

**Comment by djixas** [comment]
EDIT: Issue solves itself when I switch from ElasticSearch (6.0 or regular) to MySQL search.

Guess it should throw error related to that instead of a general one?

**Comment by ghost** [comment]
Hi @djixas thank you for you report, this issue has already fixed in 2.3-dev branch and will be available on 2.3.2

**Comment by Maaggel** [comment]
I'm experiencing the same issue - and I'm already using MySQL search.
When will 2.3.2 be out? And is it possible to have a patch with this fix?

**Comment by jpelayo** [comment]
Same here (Magento 2.3.1 on CentOS) after getting  Elasticsearch 6.7.1 to work.
Bug or misconfiguration?

exception.log

"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): The stock item was unable to be saved. Please try again. at /var/www/html/magento/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:187, LogicException(code: 0): Indexer handler is not available: elasticsearch6 at /var/www/html/magento/vendor/magento/module-catalog-search/Model/Indexer/IndexerHandlerFactory.php:79)"} []

system.log

[2019-04-15 09:45:21] main.CRITICAL: Exception message: The stock item was unable to be saved. Please try again.
Trace: <pre>#1 Magento\CatalogInventory\Model\StockRegistry->updateStockItemBySku() called at [vendor/magento/module-catalog-inventory/Observer/SaveInventoryDataObserver.php:110]
#2 Magento\CatalogInventory\Observer\SaveInventoryDataObserver->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:72]
#3 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:60]
#4 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#5 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#6 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/Model/AbstractModel.php:828]
#7 Magento\Framework\Model\AbstractModel->afterSave() called at [vendor/magento/module-catalog/Model/Product.php:963]
#8 Magento\Catalog\Model\Product->afterSave() called at [vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php:34]
#9 Magento\Framework\EntityManager\Observer\AfterEntitySave->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:72]
#10 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:60]
#11 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#12 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#13 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/EntityManager/EventManager.php:52]
#14 Magento\Framework\EntityManager\EventManager->dispatchEntityEvent() called at [vendor/magento/framework/EntityManager/Operation/Create.php:123]
#15 Magento\Framework\EntityManager\Operation\Create->execute() called at [vendor/magento/framework/EntityManager/EntityManager.php:96]
#16 Magento\Framework\EntityManager\EntityManager->save() called at [vendor/magento/module-catalog/Model/ResourceModel/Product.php:677]
#17 Magento\Catalog\Model\ResourceModel\Product->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php:58]
#20 Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback() called at [vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php:28]
#21 Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Cache/FlushCacheByTags.php:68]
#23 Magento\Framework\App\Cache\FlushCacheByTags->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#24 Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php:39]
#26 Magento\Catalog\Model\ResourceModel\Product\Interceptor->save() called at [vendor/magento/framework/Model/AbstractModel.php:654]
#27 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php:131]
#28 Magento\Catalog\Controller\Adminhtml\Product\Save->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#29 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#30 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#31 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#32 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#33 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#34 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#35 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php:26]
#36 Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#37 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#38 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#39 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#40 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#41 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#42 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#43 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#44 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre> [] []

**Comment by harryems** [comment]
getting same error, trying to install sample data.

**Comment by davidduong90** [comment]
I get same issue. Anybody have solve?

**Comment by frostblogNet** [comment]
@engcom-backlog-nazar can you provide more information about what has been changed to fix this issue?

**Comment by Swahjak** [comment]
@engcom-backlog-nazar any reference to commits or pull requests? Experiencing this on 2.3.0

**Comment by raghuiamsingh** [comment]
@engcom-backlog-nazar can you please help us getting the changes to fix this? This issue is causing a lot of problems to us.

**Comment by manfrinm** [comment]
Hello @engcom-backlog-nazar 
I'm looking to find the commit on 2.3.2 milestone that you mentioned, but I can't find any commit related to this issue.

I think that your comment: "this issue has already fixed in 2.3-dev branch and will be available on 2.3.2" is completely useless, the 2.3.2 release date is not published.
I observe that almost all official members of magento2 dev team use this response to close issues without solved it or showing solution to community. 
It's just mine opinion and I would be glad to be disproved by your answer with all details on how to fix issue on magento 2.3.1 without waiting next release.

Thanks,
Matteo

**Comment by archonkulis** [comment]
I was able to overcome the issue by creating a new source (Stores -> Inventory -> Sources) with code 'default'.

While debugging, I've noticed that it tries to insert the data into `inventory_source_item` table with `source_code = 'default'`. And since that source_code is a foreign key to the `inventory_source` table, it showed the error. When creating the source with code 'default', it then fixed the issue.

**Comment by manfrinm** [comment]
@archonkulis forcing specific data on input can not be the solution for this issue!
For example in my case I've 4 different sources with different codes.
Please reopen this issue to allow community to propose more elegant solutions.

**Comment by archonkulis** [comment]
@manfrinm this isn't my ticket, so I didn't close it. Of course, your situation is different, because I didn't have any source created in the beginning. 

Have you tried setting code as 'default' for any of the sources, maybe the first one? Perhaps it could solve the issue.

Cheers

**Comment by manfrinm** [comment]
@engcom-backlog-nazar  any updates about it? you don't care anymore this issue?

**Comment by Nazar65** [comment]
HI @djixas @manfrinm i think we need to open issue here -> https://github.com/magento-engcom/msi

**Comment by Mericic** [comment]
I had the same issue on a project I just joined. Product did not wanted to be saved, and elasticsearch was mentionned in the logs. After I started it (systemctl start elasticsearch), the problem disapeared. Hope It will help.

**Comment by inkobject** [comment]
Attempting to add a new product throws this error on 2.3.1. Already on MySQL search. Seriously this is bad. 
If this is closed, where is the solution?

**Comment by ValeSauer** [comment]
I had the same issue when updating lots of products simultaneously via API. Disabling Index or switching from "Update on save" to "Update on schedule" solved the issue completely.

**Comment by ghost** [comment]
**Magento Team** Please provide the solution of this issue, otheriwse just guide us, we will find the solution.

**Comment by sergei-sss** [comment]
I got this bug in 2.3.2 on 
`bun/magento sampledata:deploy`
after installation.

I deleted the search engine setting (Elastic Search was earlier set)
`DELETE FROM core_config_data WHERE path='catalog/search/engine';`

and now it's ok, sample data was successfully installed.

**Comment by debrarhogan** [comment]
I had the same problem (not being able to save a stock item).  It worked fine with only one website, but when I added a second, the problem started (deleting the second website and it worked fine again).  After a lot of research, I found that the second website was not listed in the following table:
inventory_stock_sales_channel
I added the website and it works just fine (also makes sense why it didn't before).
I added a third website (just to test).  Same problem, same fix.
I hope this helps someone else.

**Comment by scne** [comment]
I've still this problem! I'm using elastichsearch5 with magento 2.3.1, please let's me know if someone resolve this issue!

**Comment by scne** [comment]
Also in magento 2.3.2 this problem persists!

**Comment by benlau87** [comment]
Having the same issue after update to 2.3.2...please help

**Comment by arunu** [comment]
Issue seen in 2.3.2

**Comment by scne** [comment]
related issue [here](https://github.com/magento/magento2/issues/23962)

**Comment by engcom-Charlie** [comment]
Hello @benlau87 @arunu 
I can't reproduce this issue on Magento 2.3.2. All products can be saved. Can you provide me your steps to reproduce this issue?

**Comment by engcom-Charlie** [comment]
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by MisterMcJohn** [comment]
I'm experiencing the same issue - and I'm change back to MySQL search instead of elasticsearch.
And already on Magento 2.3.2? Still a bug?

**Comment by engcom-Charlie** [comment]
@MisterMcJohn i was tested only with MySQL and i didn't had a bug.

**Comment by MisterMcJohn** [comment]
@engcom-Charlie 

MySQL is no problem, it's only even elasticSearch is selected. 

PHP 7.2 
Magento 2.3.2

**Comment by rob-gonz** [comment]
@engcom-Charlie, I am seeing this issue on Magento 2.3.2 when running the integration unit tests. `dev:run:tests integration` produces:

There is no elastic search, there is nothing special. Just the default installation that is performed by the magento integration test into is own database.  Using default configurations and database as defined by phpunit.xml and install-confi-mysql.php in their appropriate file locations.

```
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

S...II.IIFEFE.........................FEIIFFF..............II.FEEEEEError in fixture: "\/var\/<my web directory>\/dev\/tests\/integration\/testsuite\/Magento\/Catalog\/_files\/categories.php".
 The stock item was unable to be saved. Please try again.
 #0 /var/<my web directory>/vendor/magento/module-catalog-inventory/Model/StockRegistry.php(181): Magento\CatalogInventory\Model\Stock\StockItemRepository->save(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
```

**Comment by engcom-Charlie** [comment]
Hello @rob-gonz !
I can't reproduce your issue on Magento 2.3.2.
My result(test in module-catalog-inventory):

```
Testing started at 09:33 ...
/usr/bin/php /var/www/html/magento2pr/vendor/phpunit/phpunit/phpunit --configuration /var/www/html/magento2pr/dev/tests/unit/phpunit.xml.dist /var/www/html/magento2pr/vendor/magento/module-catalog-inventory/Test/Unit --teamcity
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.



Time: 5.29 seconds, Memory: 42.00MB

OK (197 tests, 508 assertions)
Process finished with exit code 0

```

**Comment by engcom-Charlie** [comment]
@rob-gonz thanks, I know(uploaded the wrong screenshot). After this i run integration test and there was no errors.

**Comment by henk-hypershop** [comment]
We also got this issue after disabling MSI in 2.3.1. Disabling Magento_Elasticsearch and Magento_Elasticsearch6 did the trick.

**Comment by scne** [comment]
@engcom-Charlie so is this issue related to elastic search?

**Comment by MisterMcJohn** [comment]
Yes, IT shoot be have todo with elastic search due the fact as soon you switch IT off the problem of save issue dissapear

**Comment by engcom-Charlie** [comment]
@scne is not.

**Comment by scne** [comment]
@engcom-Charlie but I've still this problem with elastic search as indexer and 'Save on Update' strategy. I try to switch from elastic to mysql but the issue is the same

**Comment by srahmel** [comment]
We have solved it. There was an entry missing in cataloginventory_stock

INSERT INTO `cataloginventory_stock` (`stock_id`, `website_id`, `stock_name`) VALUES ('1', '1', 'default');

**Comment by Kings347** [comment]
Try to change Catalog Search Engine to "MySQL".

Stores/Configuration/Catalog/Catalog Search/Search Engine

I change "ElasticSearch" to "MySQL" , 

Then go to Cache Management and refresh cache

It works to me.

**Comment by benmcntsh** [comment]
@srahmel This solved it for me as well.

**Comment by tsurkanovm** [comment]
I've fixed this issue by restart my elasticsearch and reindexing:
```
service elasticsearch restart
php bin/magento i:rei
```
Magento 2.3.1 open source.

**Comment by legweilo** [comment]
@tsurkanovm thanks for the tip, you saved my day !

**Comment by DavaGordon** [comment]
This still seems to be an issue when elasticsearch is not active on the environment especially local environments. duplicated this on 2.3.3 and 2.3.4 recommended fix would be to unset the predefined variables in the env.php and allow the default to be MySql thus giving people the option to use it also it will prevent this error going forward

**Comment by onlyapproved** [comment]
+1 Dosn't matter if elastic search is disabled / enabled.

**Comment by palviggi-flagbit** [comment]
In my case it started happening after upgrading to 2.3.4. 
The internal exception said that it couldn't execute a DDL during a transaction, and the error went away when I changed the indexers from "Run on Save" to "Run on Schedule". It's probably trying to create an index table during the product save

**Comment by damienwebdev** [comment]
Can also confirm that this is still an issue on v2.3.4. Can someone from the core team respond?

I've got a fresh instance with Elasticsearch configured and I'm running:

```bash
bin/magento sampledata:deploy
```

**Comment by usman786cs** [comment]
Thank you @djixas - It worked for me.

**Comment by LiamKarlMitchell** [comment]
How do we fix this?
```The stock item was unable to be saved. Please try again.```
Is there a table I need to clear out in Magento?

**Comment by djixas** [comment]
> How do we fix this?
> `The stock item was unable to be saved. Please try again.`
> Is there a table I need to clear out in Magento?

Migrate from Magento 2 to something that works :) we're not using this buggy 3-year old still buggy and slow trash

**Comment by j-lloyd-slc** [comment]
In a case that I had to deal with, the problem was that the `cataloginventory_stock` table was empty (even though everything looked fine from the admin under Stores > Inventory).

I was able to resolve the problem by viewing another database and copying the single row, via `INSERT INTO cataloginventory_stock values(1, 0, 'Default');`

Magento version 2.3.5-p1,

**Comment by Morgy93** [comment]
I recently updated from 2.3.5-p2 to 2.4.1 and I'm now facing the same issue.

Doesn't matter if using elasticsearch or disabling flat tables completely.

My `cataloginventory_stock` table is not empty and other stock tables "seem to be correct"

The side effect here for me is that all of my categories are empty.

**Comment by onlyapproved** [comment]
> I recently updated from 2.3.5-p2 to 2.4.1 and I'm now facing the same issue.
> 
> Doesn't matter if using elasticsearch or disabling flat tables completely.
> 
> My `cataloginventory_stock` table is not empty and other stock tables "seem to be correct"
> 
> The side effect here for me is that all of my categories are empty.
> 
> _EDIT_:
> Not quite sure why the error is gone now, probably there was some issue with elasticsearch, but sadly my stock is still broken.
> However, THIS specific issue is resolved for me, currently.

Hey Morgy93. 

Do you have your indexer running by schedule or "on save"

For updating over API I found that it needs to be on schedule, elsewhere the database tables will lock up and cause the error here.

**Comment by Morgy93** [comment]
> Hey Morgy93.
> 
> Do you have your indexer running by schedule or "on save"
> 
> For updating over API I found that it needs to be on schedule, elsewhere the database tables will lock up and cause the error here.
> 
> Anyway, it can also happen with scheduled indexer tasks running. Optimal would be to add a magento feature, that postprones the cron if a lot of requests over api is recieved. Async indexing does create the same issue as-well.


Doesn't matter ... if I manually save the product from admin ui the product is shown in the category and elasticsearch has this one entry.
If I reindex the `cataloginventory_stock` index then all elasticsearch data is lost. Doesn't matter if update on save or via cronjob (by schedule)

But I assume my princess is in another issue,  thanks anyway!

**Comment by scottbolasevich** [comment]
> > How do we fix this?
> > `The stock item was unable to be saved. Please try again.`
> > Is there a table I need to clear out in Magento?
> 
> Migrate from Magento 2 to something that works :) we're not using this buggy 3-year old still buggy and slow trash

best advice on here. m2 is trash

**Comment by himanitayal010** [comment]
Magento 2 is trash for those who don't have it's knowledge.
Otherwise it's best.
ADOBE IS BEST
MAGENTO IS BEST

**Comment by onlyapproved** [comment]
> Magento 2 is trash for those who don't have it's knowledge. Otherwise it's best. ADOBE IS BEST MAGENTO IS BEST
> […](#)

Go troll on facebook or reddit. This is for dev purposes. Impressive anyone feel entitled to behave like this.

**Comment by Dheeraj351** [comment]
> In a case that I had to deal with, the problem was that the `cataloginventory_stock` table was empty (even though everything looked fine from the admin under Stores > Inventory).
> 
> I was able to resolve the problem by viewing another database and copying the single row, via `INSERT INTO cataloginventory_stock values(1, 0, 'Default');`
> 
> Magento version 2.3.5-p1,

Thank you. You made my day.

**Comment by murtuza1234** [comment]
in my case elastic service stop working due to low storage so I increase storage run below command curl -X PUT -H "Content-Type: application/json" http://127.0.0.1:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'; and then again done reindex and issue solved

**Comment by Beachmeister** [comment]
Hello, as Agila kaliyan on [stackoverflow](https://stackoverflow.com/questions/64647851/the-stock-item-was-unable-to-be-saved-please-try-again-magento-2-4-0/64674567#64674567) wrote,
"please change all indexer as update by 'Update by Schedule' mode in system->index management. "
that worked for me - and I could even save existing products!

**Comment by Joso** [comment]
> Hello, as Agila kaliyan on [stackoverflow](https://stackoverflow.com/questions/64647851/the-stock-item-was-unable-to-be-saved-please-try-again-magento-2-4-0/64674567#64674567) wrote,
> "please change all indexer as update by 'Update by Schedule' mode in system->index management. "
> that worked for me - and I could even save existing products!

I had already set to schedule, but it kept giving me the error. I changed on save and the error disappeared, but I also changed the database user permissions from "usage" to "ALL" and changed two products without getting the error.

**Comment by engcom-Alfa** [comment]
Hi @djixas 
I have tried in the latest version and it is working fine with 4.2-develop version.
Kindly upgrade to the latest version yourself and try again. If you are going to find the same issue, kindly mention to me with the latest reproducible steps in detail to reproduce.

**Comment by iphigenie** [comment]
i have in the past had errors coming out of upgrading with core modules disabled. Seems it lead to some database changes not happening esp around views, triggers, permissions etc

**Comment by engcom-Alfa** [comment]
Hi @iphigenie 
As per you reply, I understood that you have got the issue resolved. Kindly give more information in case if you are facing issue still.
Thanks for your contribution here.

**Comment by engcom-Bravo** [comment]
As we have not received any reply on this since few days, we are closing this issue. Please open a new ticket if you are still facing the issue.

Thanks.
