### ISSUE TITLE
Why main model instance creates not in controller?

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#2209]
I found that during rendering current model object (as example product) creates not always in controller, sometimes it creates in helper. As example product object creates [in helper on frontend](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Controller/Product/View.php#L109) and [in controller in adminhtml](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Controller/Adminhtml/Product/Edit.php#L45) (but link to this object isn't saved anywhere).

In Magento 1 we had main object in registry and in every place we had ability to get this object.

Why we have different behavior? How should do developers in own modules?

Thanks,
Ihor

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
