### ISSUE TITLE
Error editing or creating inventory source

### ISSUE THREAD

**Issue by djixas** [magento/magento2#22093]
### Preconditions (*)
Magento: 2.3.1
PHP 7.2 + MySQL 5.6

The following extensions were disabled during fresh install

Amazon_Core
Amazon_Payment
Amazon_Login
Dotdigitalgroup_Email
Klarna_Core
Klarna_Kp
Klarna_Ordermanagement
Magento_Authorizenet
Magento_AuthorizenetAcceptjs
Magento_Braintree
Magento_Dhl
Magento_DownloadableGraphQl
Magento_DownloadableImportExport
Magento_Fedex
Magento_InventoryProductAlert
Magento_NewRelicReporting
Magento_OfflinePayments
Magento_OfflineShipping
Magento_ReleaseNotification
Magento_SampleData
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Ups
Magento_Usps
Magento_Weee
Magento_WeeeGraphQl
Magento_WishlistAnalytics
Magento_WishlistGraphQl
MSP_ReCaptcha
MSP_TwoFactorAuth
Temando_Shipping
Vertex_Tax

### Steps to reproduce (*)
1. Install Magento
2. Hit edit inventory source
3. Save new settings

### Expected result (*)

1. It should work if.
2. Not sure if related to extensions disabling, but should not allow to disable something that throws error

### Actual result (*)

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\HTTP\ClientInterface in /home/xxxx/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace: #0 /home/xxxx/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #1 /home/xxxx/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #2 /home/xxxx/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'client', 'Magento\\Invento...') #3 /home/xxxx/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Invento...', Array, in /home/xxxx/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

**Comment by ghost** [comment]
Hi @djixas thank you for you report, please open issue here -> https://github.com/magento-engcom/msi/issues
