### ISSUE TITLE
MsrpPriceCalculator exception after upgrade to 2.3.1

### ISSUE THREAD

**Issue by williankeller** [magento/magento2#22090]
### Preconditions (*)
After performing an upgrade to the last magento version, I faced the following message:
1. Magento 2.3.0
2. PHP 7.2.15-0ubuntu0.18.04.1
3. MySQL 5.7.25-0ubuntu0.18.04.2

### Steps to reproduce (*)
1. Enable Magento maintenance mode
2. Apply updates by updating Magento to last version (2.3.1)
3. Clean the Magento cache
4. Manually clear caches and generated content
5. Update the database schema and data
6. Disable maintenance mode
7. Restart Varnish

### Expected result (*)
1. Upgrade occurs normally.

### Actual result (*)
1. MsrpPriceCalculator exception. See the full error message:

`{"0":"Missing required argument $msrpPriceCalculators of Magento\\Msrp\\Pricing\\MsrpPriceCalculator.","1":"<pre>#1 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\Msrp\\Pri...', array(array('msrpPriceCalcula...', NULL, true, NULL)), array()) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#2 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\Msrp\\Pri...') called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#3 Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\Msrp\\Pri...') called at [vendor\/magento\/module-msrp\/Helper\/Data.php:82]\n#4 Magento\\Msrp\\Helper\\Data->__construct(&Magento\\Framework\\App\\Helper\\Context#00000000533b03ea0000000034d54959#, &Magento\\Store\\Model\\StoreManager#00000000533b03d70000000034d54959#, &Magento\\Msrp\\Model\\Product\\Options\\Proxy#00000000533b07360000000034d54959#, &Magento\\Msrp\\Model\\Msrp#00000000533b07340000000034d54959#, &Magento\\Msrp\\Model\\Config#00000000533b07720000000034d54959#, &Magento\\Directory\\Model\\PriceCurrency#00000000533b01ea0000000034d54959#, &Magento\\Catalog\\Model\\ProductRepository\\Interceptor#00000000533b013f0000000034d54959#, NULL) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:116]\n#5 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\Msrp\\Hel...', array(&Magento\\Framework\\App\\Helper\\Context#00000000533b03ea0000000034d54959#, &Magento\\Store\\Model\\StoreManager#00000000533b03d70000000034d54959#, &Magento\\Msrp\\Model\\Product\\Options\\Proxy#00000000533b07360000000034d54959#, &Magento\\Msrp\\Model\\Msrp#00000000533b07340000000034d54959#, &Magento\\Msrp\\Model\\Config#00000000533b07720000000034d54959#, &Magento\\Directory\\Model\\PriceCurrency#00000000533b01ea0000000034d54959#, &Magento\\Catalog\\Model\\ProductRepository\\Interceptor#00000000533b013f0000000034d54959#, NULL)) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#6 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\Msrp\\Hel...') called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#7 Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\Msrp\\Hel...') called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:160]\n#8 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(array('instance' => 'Magento\\Msrp\\Hel...'), 'Magento\\Msrp\\Hel...', NULL, 'msrpData', 'Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:246]\n#9 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\Advanced...', array(array('context', 'Magento\\Framewor...', true, NULL), array('cart', 'Magento\\Advanced...', true, NULL), array('products', 'Magento\\Advanced...', true, NULL), array('catalogConfig', 'Magento\\Catalog\\...', true, NULL), array('session', 'Magento\\Framewor...', true, NULL), array('customerSession', 'Magento\\Customer...', true, NULL), array('checkoutSession', 'Magento\\Checkout...', true, NULL), array('checkoutCart', 'Magento\\Checkout...', true, NULL), array('catalogData', 'Magento\\Catalog\\...', true, NULL), array('importFactory', 'Magento\\Advanced...', true, NULL), array('stockRegistry', 'Magento\\CatalogI...', true, NULL), array('stockHelper', 'Magento\\CatalogI...', true, NULL), array('productFactory', 'Magento\\Catalog\\...', true, NULL), array('quoteItemFactory', 'Magento\\Quote\\Mo...', true, NULL), array('messageManager', 'Magento\\Framewor...', true, NULL), array('priceCurrency', 'Magento\\Framewor...', true, NULL), array('msrpData', 'Magento\\Msrp\\Hel...', true, NULL), array('groupManagement', 'Magento\\Customer...', true, NULL)), array('cart' => array('instance' => 'Magento\\Advanced...'), 'catalogConfig' => array('instance' => 'Magento\\Catalog\\...'), 'session' => array('instance' => 'Magento\\Customer...'), 'customerSession' => array('instance' => 'Magento\\Customer...'), 'checkoutSession' => array('instance' => 'Magento\\Checkout...'), 'scopeConfig' => array('instance' => 'Magento\\Framewor...'))) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#10 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\Advanced...', array(array('context', 'Magento\\Framewor...', true, NULL), array('cart', 'Magento\\Advanced...', true, NULL), array('products', 'Magento\\Advanced...', true, NULL), array('catalogConfig', 'Magento\\Catalog\\...', true, NULL), array('session', 'Magento\\Framewor...', true, NULL), array('customerSession', 'Magento\\Customer...', true, NULL), array('checkoutSession', 'Magento\\Checkout...', true, NULL), array('checkoutCart', 'Magento\\Checkout...', true, NULL), array('catalogData', 'Magento\\Catalog\\...', true, NULL), array('importFactory', 'Magento\\Advanced...', true, NULL), array('stockRegistry', 'Magento\\CatalogI...', true, NULL), array('stockHelper', 'Magento\\CatalogI...', true, NULL), array('productFactory', 'Magento\\Catalog\\...', true, NULL), array('quoteItemFactory', 'Magento\\Quote\\Mo...', true, NULL), array('messageManager', 'Magento\\Framewor...', true, NULL), array('priceCurrency', 'Magento\\Framewor...', true, NULL), array('msrpData', 'Magento\\Msrp\\Hel...', true, NULL), array('groupManagement', 'Magento\\Customer...', true, NULL)), array('cart' => array('instance' => 'Magento\\Advanced...'), 'catalogConfig' => array('instance' => 'Magento\\Catalog\\...'), 'session' => array('instance' => 'Magento\\Customer...'), 'customerSession' => array('instance' => 'Magento\\Customer...'), 'checkoutSession' => array('instance' => 'Magento\\Checkout...'), 'scopeConfig' => array('instance' => 'Magento\\Framewor...'))) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#11 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#12 Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:160]\n#13 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(array('instance' => 'Magento\\Advanced...'), 'Magento\\Advanced...', NULL, 'checkoutData', 'Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:246]\n#14 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\Advanced...', array(array('cart', 'Magento\\Checkout...', true, NULL), array('messageFactory', 'Magento\\Framewor...', true, NULL), array('eventManager', 'Magento\\Framewor...', true, NULL), array('checkoutData', 'Magento\\Advanced...', true, NULL), array('optionFactory', 'Magento\\Catalog\\...', true, NULL), array('wishlistFactory', 'Magento\\Wishlist...', true, NULL), array('quoteRepository', 'Magento\\Quote\\Ap...', true, NULL), array('storeManager', 'Magento\\Store\\Mo...', true, NULL), array('localeFormat', 'Magento\\Framewor...', true, NULL), array('messageManager', 'Magento\\Framewor...', true, NULL), array('productTypeConfi...', 'Magento\\Catalog\\...', true, NULL), array('productConfigura...', 'Magento\\Catalog\\...', true, NULL), array('customerSession', 'Magento\\Customer...', true, NULL), array('stockRegistry', 'Magento\\CatalogI...', true, NULL), array('stockState', 'Magento\\CatalogI...', true, NULL), array('stockHelper', 'Magento\\CatalogI...', true, NULL), array('productRepositor...', 'Magento\\Catalog\\...', true, NULL), array('quoteFactory', 'Magento\\Quote\\Mo...', true, NULL), array('itemFailedStatus', NULL, false, 'failed_sku'), array('data', NULL, false, array()), array('serializer', 'Magento\\Framewor...', false, NULL), array('searchCriteriaBu...', 'Magento\\Framewor...', false, NULL)), array()) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#15 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\Advanced...', array(array('cart', 'Magento\\Checkout...', true, NULL), array('messageFactory', 'Magento\\Framewor...', true, NULL), array('eventManager', 'Magento\\Framewor...', true, NULL), array('checkoutData', 'Magento\\Advanced...', true, NULL), array('optionFactory', 'Magento\\Catalog\\...', true, NULL), array('wishlistFactory', 'Magento\\Wishlist...', true, NULL), array('quoteRepository', 'Magento\\Quote\\Ap...', true, NULL), array('storeManager', 'Magento\\Store\\Mo...', true, NULL), array('localeFormat', 'Magento\\Framewor...', true, NULL), array('messageManager', 'Magento\\Framewor...', true, NULL), array('productTypeConfi...', 'Magento\\Catalog\\...', true, NULL), array('productConfigura...', 'Magento\\Catalog\\...', true, NULL), array('customerSession', 'Magento\\Customer...', true, NULL), array('stockRegistry', 'Magento\\CatalogI...', true, NULL), array('stockState', 'Magento\\CatalogI...', true, NULL), array('stockHelper', 'Magento\\CatalogI...', true, NULL), array('productRepositor...', 'Magento\\Catalog\\...', true, NULL), array('quoteFactory', 'Magento\\Quote\\Mo...', true, NULL), array('itemFailedStatus', NULL, false, 'failed_sku'), array('data', NULL, false, array()), array('serializer', 'Magento\\Framewor...', false, NULL), array('searchCriteriaBu...', 'Magento\\Framewor...', false, NULL)), array()) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#16 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#17 Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:160]\n#18 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(array('instance' => 'Magento\\Advanced...'), 'Magento\\Advanced...', NULL, 'cart', 'Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:246]\n#19 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\Advanced...', array(array('cart', 'Magento\\Advanced...', true, NULL)), array()) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:34]\n#20 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\Advanced...', array(array('cart', 'Magento\\Advanced...', true, NULL)), array()) called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:59]\n#21 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\Advanced...') called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#22 Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\Advanced...') called at [vendor\/magento\/framework\/Event\/ObserverFactory.php:33]\n#23 Magento\\Framework\\Event\\ObserverFactory->get('Magento\\Advanced...') called at [vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php:58]\n#24 Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(array('instance' => 'Magento\\Advanced...', 'name' => 'magento_advanced...'), &Magento\\Framework\\Event\\Observer#00000000533b07490000000034d54959#) called at [vendor\/magento\/module-staging\/Model\/Event\/Manager.php:97]\n#25 Magento\\Staging\\Model\\Event\\Manager->dispatch('view_block_abstr...', array('block' => &Magento\\Framework\\View\\Element\\Template#00000000533b061e0000000034d54959#)) called at [generated\/code\/Magento\/Staging\/Model\/Event\/Manager\/Proxy.php:95]\n#26 Magento\\Staging\\Model\\Event\\Manager\\Proxy->dispatch('view_block_abstr...', array('block' => &Magento\\Framework\\View\\Element\\Template#00000000533b061e0000000034d54959#)) called at [vendor\/magento\/framework\/View\/Element\/AbstractBlock.php:653]\n#27 Magento\\Framework\\View\\Element\\AbstractBlock->toHtml() called at [vendor\/magento\/framework\/View\/Result\/Page.php:249]\n#28 Magento\\Framework\\View\\Result\\Page->render(&Magento\\Framework\\App\\Response\\Http\\Interceptor#00000000533b02360000000034d54959#) called at [vendor\/magento\/framework\/View\/Result\/Layout.php:171]\n#29 Magento\\Framework\\View\\Result\\Layout->renderResult(&Magento\\Framework\\App\\Response\\Http\\Interceptor#00000000533b02360000000034d54959#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#30 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', array(&Magento\\Framework\\App\\Response\\Http\\Interceptor#00000000533b02360000000034d54959#)) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#31 Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Response\\Http\\Interceptor#00000000533b02360000000034d54959#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#32 Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', array(&Magento\\Framework\\App\\Response\\Http\\Interceptor#00000000533b02360000000034d54959#), array(array('result-messages', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php:130]\n#33 Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(&Magento\\Framework\\App\\Response\\Http\\Interceptor#00000000533b02360000000034d54959#) called at [vendor\/magento\/framework\/App\/Http.php:140]\n#34 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#35 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#36 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#00000000533b02340000000034d54959#) called at [index.php:39]\n<\/pre>","url":"\/","script_name":"\/index.php"}`

I found the same issue reported by anoter user here:
https://magento.stackexchange.com/questions/268064/msrppricecalculator-exception

Have you guys faced this issue before?

**Comment by ghost** [comment]
Any update on this? It happens on a fresh install of 2.3.1 for me. The installation initially appears fine, but during a second deployment it breaks with the above error.

**Comment by orlangur** [comment]
https://github.com/magento/magento2/commit/c3effa5c1e2da8fb2cffa87b7415efe04d65100d seems correct from backward-compatibility perspective.

Try to locate invalid third-party code which does not construct objects correctly.

**Comment by ghost** [comment]
HI @williankeller your magento version is CE or EE ?

**Comment by ghost** [comment]
HI @williankeller thank you for you report, i'm not able to reproduce following steps you described, on clean magento 2.3.1 and upgrade from 2.3.0 to 2.3.1 this seems to be related to your custom modules, or  environment, please verify that your magento cache is flushed.

**Comment by williankeller** [comment]
@engcom-backlog-nazar 
I'm using with a Vanilla version, there are no custom modules. However, it is an Enterprise edition. But I created the issue to get more users reporting the same issue. I've also opened an issue into the EE support.
Thanks

**Comment by lfluvisotto** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @lfluvisotto. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @lfluvisotto, here is your [Magento instance](https://i-22090-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22090-2-3-1.instances.magento-community.engineering/admin](https://i-22090-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hostep** [comment]
@williankeller: you might want to follow https://github.com/magento/magento2/issues/22190 & possible solution: https://github.com/magento/magento2/pull/22191

**Comment by lfluvisotto** [comment]
@williankeller @hostep 

My pull request https://github.com/magento/magento2/pull/22191 is wrong, it's generating > Circular sequence reference > after I double check it

If you're experiencing the issue in some server, make sure at least that MsrpConfigurableProduct and MsrpGroupedProduct are enabled.
