### ISSUE TITLE
Backend products cannot use WYSIWYG editor after switching views

### ISSUE THREAD

**Issue by nineov** [magento/magento2#22102]
### Preconditions (*)

Magento2.3 Community Edition
### Steps to reproduce (*)

1.In the background product interface, when I switch the view, I want to modify the Description field, do not check Use Default Value, this time can not be edited at all.

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/37391614/55374368-cac6c880-553a-11e9-8e6e-810069df99c9.png)

2.The expected result should be that the content can be edited, but it is actually uneditable.

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/37391614/55374393-e16d1f80-553a-11e9-8aaf-4a1c57ea7db6.png)

2.

**Comment by ghost** [comment]
Hi @nineov thank you for you report, this issue has already fixed in 2.3-develop branch.

![deepin-screen-recorder_Select area_20190402094101](https://user-images.githubusercontent.com/40756439/55381348-98619f00-552b-11e9-8b0c-19b493a647f1.gif)
