### ISSUE TITLE
Checkout Loaders

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#22100]
### Description (*)

Do away with multiple loaders on checkout page.

### Expected behavior (*)

When loading checkout page, it should be much faster like shopify/amazon. Crucial to make as fast and clean as possible

### Benefits

Greatly increase conversion rates and customer confidence.

### Additional information

You should do away completely with all the multiple loaders on the checkout page. It looks bad and gives the impression it may or may not complete.  This is a very bad place to lose customer confidence.

**Comment by orlangur** [comment]
Checkout works just fine if you setup Magento properly: https://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_perf-optimize.html

**Comment by ladle3000** [comment]
@orlangur agree to disagree

**Comment by ladle3000** [comment]
I suppose if 'just fine' is your goal.

**Comment by orlangur** [comment]
@snoroozi works perfectly I mean. And in any case such observation is not a valid bug report, it could be placed in https://github.com/magento/community-features but should contain some not so vague metrics.

**Comment by ladle3000** [comment]
@orlangur no metric is needed to see that there are too many loaders. Take a poll.
