### ISSUE TITLE
i have a issue with logo update

### ISSUE THREAD

**Issue by thedustymagic** [magento/magento2#22106]
![Screenshot (7)](https://user-images.githubusercontent.com/49187710/55387912-ef796b00-554f-11e9-9bd4-a64b1cfb0839.png)

**Comment by ghost** [comment]
Hi @thedustymagic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results 

Then please reopen the issue, thank you.
