### ISSUE TITLE
2.3.1 Still invalid input time. 

### ISSUE THREAD

**Issue by CKENT0369** [magento/magento2#22101]
Going back to issue https://github.com/magento/magento2/issues/21666 I just upgraded to 2.3.1 I am still having the same issue. 

Preconditions (*)

    Magento 2.3.1
    en_US locale

Steps to reproduce (*)

    Create or edit product
    Change date field for new from to anything
    Click Save

Expected result (*)

    Product Saves with new from date

Actual result (*)

    Error occurs stating "Invalid input datetime format of value '04/01/2019'"
    Product does not save.
    Clearing the new from or to date allows save

Note: Further changing to en_GB accepts the date but i want my locale to be en_us so that date formats are in a format that I am use to.

Any help will be appreciated.

**Comment by CKENT0369** [comment]
Invalid input datetime format of value '4/01/2019'

**Comment by engcom-backlog-nazar** [comment]
@magento-engcom-team give me 2.3.1instance

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-22101-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22101-2-3-1.instances.magento-community.engineering/admin](https://i-22101-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @CKENT0369 thank you for you report, but i'm not able to reproduce following steps you described, on clean magento 2.3.1 instance.
![deepin-screen-recorder_Select area_20190402095735](https://user-images.githubusercontent.com/40756439/55382290-fbeccc00-552d-11e9-88d3-2091c834f4ca.gif)

**Comment by CKENT0369** [comment]
I just went in and flushed all magento cache. Also flushed magento static files cache. It appears to be working now. Why woulding the upgrade from web setup wizard do this?

**Comment by wclansar** [comment]
Hi ,
I am also getting same issue like as 
Invalid input datetime format of value '11/22/2018'
In magento 2.3.1 after upgrade from 2.2.7.
Even my locale is en_US.
![magento2](https://user-images.githubusercontent.com/10025094/57844697-382e7000-77ee-11e9-9de3-7823dd9844ed.png)
