### ISSUE TITLE
i have issue with logo update

### ISSUE THREAD

**Issue by thedustymagic** [magento/magento2#22109]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
![Screenshot (7)](https://user-images.githubusercontent.com/49187710/55388093-48e19a00-5550-11e9-94a6-76bc25420824.png)

**Comment by ghost** [comment]
Hi @thedustymagic thank you for you report, i'm closing as duplicate to this -> https://github.com/magento/magento2/issues/19687
