### ISSUE TITLE
2.3.x - Product list show 3 products, layout is broken

### ISSUE THREAD

**Issue by hoangnm89** [magento/magento2#22110]
### Preconditions (*)
1. install fresh magento 2.3.x with sample data and Luma theme

### Steps to reproduce (*)

1. Observe product listing page

### Expected result (*)
1. Products fit on the rows, like 2.2.x: 4 items

### Actual result (*)

1. show 3 products per row and layout seems broken
![2 3-2 2](https://user-images.githubusercontent.com/655821/55388914-6158b100-555e-11e9-8c9a-9b8297a6b809.png)

i think i found why this issue is happend:
![code 2 3-2 2](https://user-images.githubusercontent.com/655821/55389021-9fee6b80-555e-11e9-9d4b-9a437450c4dd.png)

vendor/magento/module-catalog/view/frontend/templates/product/list.phtml

ps: i know no one use Luma for real site, but with a demo it should look fine(my opinion).

**Comment by ghost** [comment]
Hi @hoangnm89 thank you for you report, this issue has already fixed in 2.3-develop branch, I'm closing this as duplicate to this ->https://github.com/magento/magento2/issues/20140
