### ISSUE TITLE
Allow declaration of "always" checks for Magento\Payment\Model\Checks\SpecificationFactory

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#2211]
Magento\Payment\Model\Checks\SpecificationFactory is used for defining and running checks to determine if payment methods are available.  The architecture makes it easy to define new checks using DI.  However, the areas that use this class (e.g., \Magento\Payment\Block\Form\Container::_canUseMethod) directly specifies which checks to run.  This means that, in addition to creating a new check via DI, each such area must be modified (e.g., via plugin) to declare that the new check should be run.

What would be very useful is the ability to declare which checks should always be run via DI as well.  In addition to the "mapping" argument defined in DI, an "alwaysChecks" or "requiredChecks" argument should be added, allowing for an array of check names.  Magento\Payment\Model\Checks\SpecificationFactory::create should then be modified to resolve to a list of the checks specified in the argument plus any other "always" checks. 

Extension developers would thus be able to create new payment method checks and ensure they are run, entirely with DI, without needing to modify any code that calls SpecificationFactory::create.

I'm opening this issue before creating a PR for such an addition to start discussion on whether this is an appropriate direction.

**Comment by Dell-** [comment]
Hi @CNanninga !
The code that you've found is an old implementation, we have corresponding task for elimination of this code.
Please feel free using app/code/Magento/Payment/Gateway/* library for creating new payment method, we will post and example soon.
For now, you can put all checks logic in \Magento\Payment\Model\MethodInterface:isAvailable() method and use ‘payment_method_is_active’ event subscription.

**Comment by Dell-** [comment]
Internal ticket MAGETWO-45604.

**Comment by CNanninga** [comment]
Can you clarify about "elimination of this code?"  Are you indicating that the entire SpecificationFactory class and implementation will be removed in the future?  (I see that it is still included in the GA release.)

**Comment by alena-marchenko** [comment]
Hi,

We recommend you to use app/code/Magento/Payment/Gateway/\* library for creating new payment method, since code mentioned by you is an old implementation and can be removed in future releases. Please feel free using [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for further technical questions.
