### ISSUE TITLE
when i try to upload logo after that the error occured 

### ISSUE THREAD

**Issue by thedustymagic** [magento/magento2#22111]
### Summary (*)
 my website www.thedustymagic.com , when i try to upload header logo after that the error occured .A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later. 

### Examples (*)
 when i try to  upload header logo, issue will be occure. 

### Proposed solution

![Screenshot (7)](https://user-images.githubusercontent.com/49187710/55389126-48e29980-5552-11e9-8967-f50a91b43020.png)

**Comment by ghost** [comment]
Hi @thedustymagic thank you for you report, bu as i say in another your ticket this problem related to your environment, what's is your php version ? magento version ?  and this issue has already fixed in this PR -> https://github.com/magento/magento2/pull/18851 and available on 2.3.1 release.

**Comment by ghost** [comment]
@thedustymagic  I'm Closing this as this was fixed in 2.3.1 release.
