### ISSUE TITLE
2.3.1 admin blank page on godaddy hostting 

### ISSUE THREAD

**Issue by a7medeeuae** [magento/magento2#22122]
hi 

have problem with magento 2.3.1

the admin page not working is showing 

 blank page on godaddy hostting

**Comment by ghost** [comment]
Hello @a7medeeuae.
This is not issues of Magento,

Please check your server configuration and check proper permission of file and folders.

Please check server configuration using the below script.
https://github.com/sjanjic/magento2-check/blob/master/index.php

for the file and folder permissions please check 
https://magento.stackexchange.com/questions/91870/magento-2-folder-file-permissions

**Comment by ghost** [comment]
Hi @a7medeeuae  
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
