### ISSUE TITLE
Improve method canBeShowInCategory

### ISSUE THREAD

**Issue by will-b** [magento/magento2#2212]
The method name 'canBeShowInCategory' does not sound right. Can it be changed to 
- canBeShownInCategory
- canShowInCategory
- canProductBeShownInCategory

It appears multiple time within Magento\Catalog

It returns a string of the product Id if true and a false when its not. A method name starting with 'can' or 'has' should usually return a boolean only.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
