### ISSUE TITLE
Paypal buttons disable issue - Magento 2.3.1

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#22134]
Paypal buttons on the product page cannot be disabled.

### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2

### Steps to reproduce (*)

1. Paypal backend settings
2. Display on Product Details Page "NO"
3. Product page

### Expected result (*)

1. Paypal backend settings is Display on Product Details Page "NO"
2. Product page is disabled paypal buttons.

![paypal_settings](https://user-images.githubusercontent.com/26794034/55478276-f1acf980-5623-11e9-8377-38a0ce4b3c42.png)

![product_page](https://user-images.githubusercontent.com/26794034/55478549-a47d5780-5624-11e9-866f-26fd72731b6f.png)

### Actual result (*)

1. The product page still has paypal buttons even they are disabled in paypal settings.

![paypal_settings](https://user-images.githubusercontent.com/26794034/55478276-f1acf980-5623-11e9-8377-38a0ce4b3c42.png)
![product_page](https://user-images.githubusercontent.com/26794034/55478187-b7dbf300-5623-11e9-825d-803a03d11e9f.png)

**Comment by ghost** [comment]
HI @Userr017 thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/22045

**Comment by magento-engcom-team** [comment]
Hi @Userr017. Thank you for your report. 
The issue has been fixed in magento/magento2#22260 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [233e4c51f7d525f4573b11a24ae5a81c13762343](https://github.com/magento/magento2/commit/233e4c51f7d525f4573b11a24ae5a81c13762343)

The fix will be available with the upcoming 2.3.3 release.

**Comment by quantumAV** [comment]
Applying the fix detailed in [https://github.com/magento/magento2/commit/233e4c51f7d525f4573b11a24ae5a81c13762343](url) 

does remove the Paypal buttons from the Product page but has the adverse effect of removing any ability to alter the look of the Paypal Smart Buttons. The buttons all revert to the standard small buttons with no ability to change colour or size.

I reverted the changes in the fix and buttons then switched back to expected smart buttons

version 2.3.2

**Comment by pod6wasjerks** [comment]
I have found that you additionally need to set **Enable In-Context Checkout Experience** to 'No' in order to remove those buttons from the product details page.

version 2.3.2

![Capture](https://user-images.githubusercontent.com/18634161/64284538-d2dec600-cf27-11e9-9e10-cadfae1f16f4.JPG)
