### ISSUE TITLE
Issue With Minimum Order Amount including Tax

### ISSUE THREAD

**Issue by EChandresh** [magento/magento2#22130]
### Preconditions (*)

1. Magento 2.1, 2.2, 2.3
2. I have set minimum order amount is 97 and Include tax to amount to Yes. On the cart page product price 90 and tax is 7.54. it's obviously greater than $97. Although Proceed to Checkout is disabled.

### Steps to reproduce (*)

1. Set Minimum order amount and Include tax to amount Yes
2. Add product to cart which amount is less than Minimum Order Amount. In Estimated shipping tax select address by which Tax amount should added to order amount.
3. After applying tax Order amount should be greater than Minimum order Amount

### Expected result (*)

1. Proceed to Checkout should be enabled if Order amount including tax is greater than Minimum Order Amount

### Actual result (*)

1. https://www.screencast.com/t/rsUbnGOhlxgQ
2. Proceed to Checkout is disabled although Order Amount including Tax is greater than Minimum Order Amount.

**Comment by maddumarala** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by ghost** [comment]
HI @EChandresh thank you for you report, this is confirmed issue please refer to -> https://github.com/magento/magento2/issues/20004

**Comment by EChandresh** [comment]
@engcom-backlog-nazar May I know when it will be resolved?
