### ISSUE TITLE
Search auto-complete can be vandalised

### ISSUE THREAD

**Issue by danielgoodwin97** [magento/magento2#22136]
### Preconditions (*)
1. Magento 2.2+ (Haven't tested on any lower)
2. Any Magento install which uses the auto-complete function

### Steps to reproduce (*)
1. Create any product.
2. Search for the product name and append anything after a '?' (ex. simple?thisisatest).
3. As long as products come up you've succeeded (products must show up in search).
4. Go back to homepage or anywhere where you can search and start typing in the name of the product.
5. The vandalised auto-suggestion should be there.

### Expected result (*)
![Screenshot 2019-04-03 at 14 54 21](https://user-images.githubusercontent.com/25493846/55484434-67af6180-5620-11e9-8b7e-43e1d48be1be.png)

### Actual result (*)
![Screenshot 2019-04-03 at 14 52 45](https://user-images.githubusercontent.com/25493846/55484308-3040b500-5620-11e9-958e-4cdc034b2c8f.png)

**Comment by thedanielgoodwin** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @danielgoodwin97. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @danielgoodwin97, here is your [Magento instance](https://i-22136-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22136-2-3-develop.instances.magento-community.engineering/admin](https://i-22136-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by thedanielgoodwin** [comment]
I've reproduced the issue using the above instance with a product named 'simple'.
You can also add unicode which can spew all over the page.

![Screenshot 2019-04-03 at 15 17 04](https://user-images.githubusercontent.com/25493846/55486092-9d097e80-5623-11e9-92a8-77c5fdc2c760.png)

**Comment by orlangur** [comment]
This affects any other customer visiting store?

Please provide more details on expected result. What's so special about question mark? Could some other symbols cause issues?

**Comment by thedanielgoodwin** [comment]
@orlangur There's nothing special about the question mark, it's just what I had found it with. You can use any symbol, or even a space. 

I'd imagine that the expected result wouldn't be to show anything which has completely unrelated text after the product name.

And yes, this is visible to every customer, not just the person who searched it.

Also, from what I can tell, this isn't able to be configured or played with in the admin panel, which means if you wanted to remove any of these you'd have to delete lines from the database, which seems like an oversight.

**Comment by orlangur** [comment]
I see, search is just treated as "simple test2" and there is nothing wrong with it.

In a real store there will be other more frequent queries.

> expected result wouldn't be to show anything which has completely unrelated text after the product name.

And how can we determine "completely unrelated text"?

**Comment by thedanielgoodwin** [comment]
Well, you could put literally anything you wanted there. Which means people could put something vulgar and it would show up to every customer on your website. Like this:
![Screenshot 2019-04-03 at 15 32 19](https://user-images.githubusercontent.com/25493846/55487310-c5927800-5625-11e9-93c7-c2593b640e0d.png)

**Comment by orlangur** [comment]
@danielgoodwin97 thanks for the use case, could be really influencing other customers. However, to avoid this some kind of censorship needs to be implemented so this sounds more like a feature request to me.

**Comment by thedanielgoodwin** [comment]
I'm not sure that this could be classed as a feature, but I can see why this wouldn't be seen as a bug. However, you can deface live sites with this right now.
I think that it should only really show the name of the product, not what people have searched. I think you're asking for trouble by showing user inputted search terms.

**Comment by ghost** [comment]
Hi @danielgoodwin97  It will be processed faster if you move this to https://github.com/magento/community-features
