### ISSUE TITLE
Products suddenly disappeared on frontend

### ISSUE THREAD

**Issue by SLv99** [magento/magento2#2214]
I've been developing Magento 2.0 themes/extensions for a while now and almost releasing the first Magento webshop. My problem is that in this webshop the products are suddenly disappeared on the frontend. The backend still shows the products correct. I've spent a lot of hours now to search for a solution, but I still did not manage to get it working again.

I checked all standard possible solutions:

* Cleared/flushed Magento cache/ Cache storage (via admin and command line)
* Product is in stock and has a qty of 10
* Product visibility is enabled
* Run indexer:reindex

The webshop is here: http://goo.gl/Tqwm3O. There are product in this category, they did show, but suddenly they disappeared.

Did anyone have a similar problem?

**Comment by SLv99** [comment]
If I rollback to a previous backup, the products are back again. I think this is because of the page cache, when I clear this the products are gone again. I did a database compare, but nothing critical changed.

**Comment by SLv99** [comment]
Another update, products are still available when I access the product directly via the URL. When I try to add the product to my cart I get this error: 'We can't add this item to your shopping cart right now.'

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
