### ISSUE TITLE
Manufacturer Attribute Missing after upgrade from 2.2.5 to 2.2.8

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#22141]
I noticed this issue when we upgraded our development site to 2.2.6, we ended up not upgrading the site from 2.2.5 because there were so many issues with 2.2.6. Figured they were resolved by 2.2.8 and needed to upgrade based on Security Updates recently. Now we're losing SO much functionality, yet again. Not sure how it's possible for so many things to change in small version updates.

### Preconditions (*)
1. Magento 2.2.5 - Manufacturer Attribute fully enabled and being used. Visible on product edit page and product grid.
2. Upgrade to Magento 2.2.8 - Manufacturer Attribute enabled still, completely missing from product grid and product edit page.

### Steps to reproduce (*)
1. Upgrade from Magento 2.2.5 to Magento 2.2.8
2. Manufacturer Attribute enabled in 2.2.5, Manufacturer Attribute enabled still in 2.2.8
3. Edit product, Manufacturer Attribute missing.

### Expected result (*)
1. Manufacturer Attribute not missing?

### Actual result (*)
1. Manufacturer Attribute from both Product Edit Page and Product Grid.

**Comment by nickpiro** [comment]
@magento-engcom-team give me 2.2.8 instance

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nickpiro, here is your [Magento instance](https://i-22141-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-22141-2-2-8.instances.magento-community.engineering/admin](https://i-22141-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nickpiro** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by nickpiro** [comment]
I was not able to reproduce this on a vanilla Magento 2.2.8, which leads me to believe it has something to do with the upgrade. Again, I noticed this with upgrading from 2.2.5 - 2.2.6. 

On our site, we have a "**Group**" called "**Attributes**" on the Attribute Sets. This is where we place "**Manufacturer**" attribute. I moved the Manufacturer Attribute to the General Group to see if that changed/resolved the issue and it did not.

**Comment by nickpiro** [comment]
I just did some testing, with Magento 2.2.8, the apply_to column for the manufacturer attribute in the catalog_eav_attribute table in the database only has the value configurable with a , in front as if everything before was deleted..

Before upgrading to Magento 2.2.8, the apply_to value was simple,virtual,bundle,downloadable,configurable

I was able to fix this manually by going into the database, but this is a strange bug in the upgrade!

**Comment by hammockvienna** [comment]
@nickpiro i face the same issue. 
We upgraded from 2.2.3 to 2.2.8
When i check the database the apply_to value is nearly everywhere NULL. Even when i add manually simple,virtual,bundle,downloadable,configurable
it does not work.
I have reindexed everything + and i have rebuild the EAV cache.

**Comment by thanasisgalanis** [comment]
Issue still exist in 2.3.1!

**Comment by nickpiro** [comment]
@sakisplus :( ---- If you need a fix just go into catalog_eav_attribute, find your manufacturer ID (mine is 83) and change the apply to column to 'simple,virtual,bundle,downloadable,configurable,grouped'

Works for me. Inconvenient none the less.

**Comment by ghost** [comment]
Hi @nickpiro thank you for you report, this issue has already fixed 2.3-dev branch, and will be available on 2.3.2  and 2.2.9 release soon .
