### ISSUE TITLE
Can not import table rates when condition is set in the global scope

### ISSUE THREAD

**Issue by leabaertschi** [magento/magento2#22142]
### Preconditions (*)

1. Magento 2.3.1, the system was upgraded from Magento 2.2.6
2. PHP 7.2.10
3. MySQL 5.7.23
4. Mac OS 10.14.3
5. Apache 2.2.34
6. The application config is dumped to `app/etc/config.php`

### Steps to reproduce (*)

1. Activate tablerate shipping method
2. Set condition to 'Weight vs. Destination' in the global scope and save
3. Change to the website scope of the configuration
4. Upload a tablerate.csv file
5. You get an error that something went wrong
6. To be able to import the file I had to uncheck the 'standard value' checkbox for the condition and save the config in website scope before importing the file

### Expected result (*)

1. I'm able to import a tablerate.csv file in the website scope, when the shipping method is correctly configured in global scope

### Actual result (*)

1. In the `exception.log` I got the following error message: 
```
main.CRITICAL: The "condition_name_short: " code type for Table Rate is incorrect. Verify the type and try again. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The \"condition_name_short: \" code type for Table Rate is incorrect. Verify the type and try again. at vendor/magento/module-offline-shipping/Model/Carrier/Tablerate.php:252)"} []
```

**Comment by leabaertschi** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @leahaense. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @leahaense, here is your [Magento instance](https://i-22142-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22142-2-3-1.instances.magento-community.engineering/admin](https://i-22142-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by leabaertschi** [comment]
The issue is not reproducible on a vanilla Magento 2.3.1 instance.

**Comment by ghost** [comment]
Hi @leahaense thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.3-develop, seems like problem related to your configuration , or wrong data in csv file.

**Comment by leabaertschi** [comment]
Hi @engcom-backlog-nazar, definitely not the csv file, since I was able to import it after changing the configuration in website scope, as described in the issue. I was thinking that maybe it was caused due to something going wrong during the upgrade from version 2.2.6, or due to the `app:config:dump`, `app:config:import` messing something up. If I have time I will try to reproduce it with a clean 2.2.x with upgrade to 2.3.1 with dumped config.

**Comment by ghost** [comment]
@leahaense i think this related to `app:config:dump, app:config:import` error that you have, says that `condition_name_short` is the key of value but we need value, so i think this related to wrong config data array.

**Comment by ghost** [comment]
@leahaense found! you have `condition_name_short:  `  must  be `condition_name_short`

**Comment by leabaertschi** [comment]
@engcom-backlog-nazar the `:` is just in the exception error message coming from the file mentioned in the comment, which is Magento core. The issue seems to be, that it does not find the condition name in the config when fetching it from the default config scope here: https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/app/code/Magento/OfflineShipping/Model/ResourceModel/Carrier/Tablerate.php#L307
The result of this function is `NULL`.

**Comment by ghost** [comment]
@leahaense hmm...  this may be related to `app:config:import`

**Comment by giacmir** [comment]
I'm having the same issue after upgrading from 2.2.6 to 2.3.1. My config is also dumped in config.php.
Probably this issue should be reopened. It's an upgrade issue or something related to `app:config:dump` not reproducible with simple checks.

**Comment by akosglue** [comment]
so it is closed, but what is the solution for this problem?

**Comment by byjujohn** [comment]
@giacmir I managed to import it after removing the below entries from the `app/etc/config.php` file temporarily. Please note that there are two set of entries for the `tablerate` remove both.
```
'carriers' => [
    'tablerate' => [
    	//....
    ]
]
```

Then do a cache clean - `php bin/magento cache:clean`. Now if you try to import it, this should work.

**Comment by AndresAndreev** [comment]
I had the same problem on Magento 2.2.8. I can confirm that the issue is related to `app:config:dump` / `app:config:import`. When I removed all tablerates related configurations in `config.php` file, I managed to import the csv file.

**Comment by slackerzz** [comment]
Magento 2.3.4 on Magento Cloud and this bug is still present
