### ISSUE TITLE
Error filtering template: Warning: Illegal offset type in /home/abwizbio/public_html/wp/wp-includes/l10n.php on line 1099

### ISSUE THREAD

**Issue by Abwizbio** [magento/magento2#22146]
### Summary (*)
<Error filtering template: Warning: Illegal offset type in /home/abwizbio/public_html/wp/wp-includes/l10n.php on line 1099>

### Examples (*)
<Error filtering template: Warning: Illegal offset type in /home/abwizbio/public_html/wp/wp-includes/l10n.php on line 1099>

**Comment by Abwizbio** [comment]
Error filtering template: Warning: Illegal offset type in /home/abwizbio/public_html/wp/wp-includes/l10n.php on line 1099

**Comment by Abwizbio** [comment]
Error filtering template: Warning: Illegal offset type in /home/abwizbio/public_html/wp/wp-includes/l10n.php on line 1099

**Comment by Abwizbio** [comment]
Magento system could not send the e-mail. Receiver always received Error filtering template: Warning: Illegal offset type in /home/abwizbio/public_html/wp/wp-includes/l10n.php on line 1099

**Comment by shikhamis11** [comment]
@Abwizbio with your issue description 
Magento system could not send the e-mail. Receiver always received Error filtering template: Warning: Illegal offset type in /home/abwizbio/public_html/wp/wp-includes/l10n.php on line 1099 

the issue doesn't seems coming from magento files Please check at your end.
