### ISSUE TITLE
Uploading images using API set "use default value" unchecked

### ISSUE THREAD

**Issue by francescorm** [magento/magento2#22159]
### Preconditions (*)
1. Magento 2.3

### Steps to reproduce (*)
Updating image using API REST default attribute checkbox became unchecked.

### Expected result (*)
attributes has the default store view checked

### Actual result (*)
"Use default value" is unchecked

1. [Screenshots, logs or description]

**Comment by francescorm** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @francescorm. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @francescorm, here is your [Magento instance](https://i-22159-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22159-2-3-develop.instances.magento-community.engineering/admin](https://i-22159-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hostep** [comment]
This is probably a duplicate of https://github.com/magento/magento2/issues/9186 ?

**Comment by francescorm** [comment]
The problem still persist and i think it's a bug on Magento2.3.
How to recreate:
1) Create a multistore

![Schermata del 2019-04-04 17-22-03](https://user-images.githubusercontent.com/47854158/55567552-30af7d80-56fe-11e9-8e11-b79b86f91f08.png)

2) Create a product

![Schermata del 2019-04-04 17-22-49](https://user-images.githubusercontent.com/47854158/55567601-4a50c500-56fe-11e9-97d8-fd5085ec177b.png)

3) Using API load a product image 
https://i-22159-2-3-develop.instances.magento-community.engineering/rest/V1/products/Prova1/media

![Schermata del 2019-04-04 17-24-05](https://user-images.githubusercontent.com/47854158/55567697-808e4480-56fe-11e9-88da-769dcbf03ef8.png)

Expected Behaviour --> if i change the scope of the product, "Use default Value" is checked.
Problem--> All attributes has "Use Default Value" unchecked 

![Schermata del 2019-04-04 17-26-44](https://user-images.githubusercontent.com/47854158/55567846-d4009280-56fe-11e9-8cfc-99547000f657.png)

**Comment by francescorm** [comment]
Is dangerous to delete single tuple of the database of the specific store view?
Can i delete tuple inside 'catalog_product_entity_int'  without any problem? 
i could create a script that delete value inside this table and the problem could be managed.
What do you think about it?

**Comment by ghost** [comment]
Hi @francescorm thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/9186
