### ISSUE TITLE
Click on search icon it does not working

### ISSUE THREAD

**Issue by Dharmeshvaja91** [magento/magento2#22152]
### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Admin >> Go to Orders,Customers and Products grid.
2. Scroll down the page
3. On sticky top bar click on search icon" Search field should active when click on search icon.

### Expected result (*)

1 . When user click on search icon its should be navigate to search box. 

### Actual result (*)

![magento23_issue_video](https://user-images.githubusercontent.com/43463281/55532077-2d9a9a00-56ca-11e9-8ede-bf8c69891a1d.gif)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22152-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22152-2-3-develop.instances.magento-community.engineering/admin](https://i-22152-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22152-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22152-2-2-develop.instances.magento-community.engineering/admin](https://i-22152-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22152-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22152-2-3-develop.instances.magento-community.engineering/admin](https://i-22152-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99037`, `MAGETWO-99038` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your report. 
The issue has been fixed in magento/magento2#22154 by @niravkrish in 2.3-develop branch
Related commit(s):
 - [6cbf55d40ebb33e5fb73c68ba62df83f2af98aa2](https://github.com/magento/magento2/commit/6cbf55d40ebb33e5fb73c68ba62df83f2af98aa2)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your report. 
The issue has been fixed in magento/magento2#22441 by @saphaljha in 2.2-develop branch
Related commit(s):
 - [b3a799deb5e744e286a37e04abc8425eacc4e878](https://github.com/magento/magento2/commit/b3a799deb5e744e286a37e04abc8425eacc4e878)

The fix will be available with the upcoming 2.2.9 release.
