### ISSUE TITLE
Magento 2.0 nothing updating

### ISSUE THREAD

**Issue by laykinx** [magento/magento2#22158]
Hello, 

### Preconditions (*)
New installation. 
Magento ver. 2.0.0
Plesk Panel
PHP version 7.0.33

### Steps to reproduce (*)
1. Go to Store > Configuration > Design 
2. Select my design theme
3. And Save Config
4. "Please Wait..." but nothing happens

i install today magento, and when i update the panel nothing updating.

### Actual result (*)
it still like this : https://imgur.com/LM62y69

### Expected result (*)
`
-bash-4.2# cat /etc/redhat-release 

CentOS Linux release 7.6.1810 (Core) 

-bash-4.2# 

-bash-4.2# uname -r

3.10.0-327.10.1.el7.x86_64

-bash-4.2# mysql --version

mysql  Ver 15.1 Distrib 10.2.23-MariaDB, for Linux (x86_64) using readline 5.1

-bash-4.2# 

`

**Comment by ghost** [comment]
HI @laykinx thank you for you report, this issue is not reproducing on latest 2.3.1 version and on 2.2.8. please try upgrading.
