### ISSUE TITLE
Magento\CustomerCustomAttributes\Helper\Data class problem

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#22157]
### Summary (*)

Hi team,
Magento 2.3.1 EE, php7.2, nginx
The creation of the plugin for the Magento\CustomAttributeManagement\Helper\Data class generates Fatal Error:
`[04-Apr-2019 08:42:35 UTC] PHP Fatal error:  Uncaught Error: Cannot access  property Magento\CustomerCustomAttributes\Helper\Data\Interceptor::$allowLengthValidationTypes in /var/www/src/vendor/magento/module-customer-custom-attributes/Helper/Data.php:128
Stack trace:
#0 /var/www/src/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CustomerCustomAttributes\Helper\Data->getAttributeInputTypes()
#1 /var/www/src/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CustomerCustomAttributes\Helper\Data\Interceptor->___callParent('getAttributeInp...', Array)
#2 /var/www/src/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CustomerCustomAttributes\Helper\Data\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/src/generated/code/Magento/CustomerCustomAttributes/Helper/Data/Interceptor.php(91): Magento\CustomerCustomAttributes\Helper\Data\Interceptor->___callPlugins('getAttributeInp...', Array, Array)
#4 /var/www/src/vendor/magento/module-custom-attribute-management/Helper/Data.php(268): Magent in /var/www/src/vendor/magento/module-customer-custom-attributes/Helper/Data.php on line 128
`

### Examples (*)

The problem raises only when plugin for the Magento\CustomAttributeManagement\Helper\Data class is created:
http://pix.toile-libre.org/upload/original/1554369196.png

### Proposed solution

http://pix.toile-libre.org/upload/original/1554369017.png

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Magento Open Source, isn't it?

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.
