### ISSUE TITLE
How to add category tree to custom module in backend?

### ISSUE THREAD

**Issue by dungdk** [magento/magento2#2215]
Hi All,
I want to add category tree to my module, it's like product edit page.
Anyone know how to do it.
Thanks all in advance.
Regards,

**Comment by Vinai** [comment]
The github issue tracker is intended for technical issues only.
Please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) for technical questions. In your case probably the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2 would ) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
