### ISSUE TITLE
Mail function not working after upgrade to Magento 2.3 Zend_Mail_Transport_Abstract::send()

### ISSUE THREAD

**Issue by rvinothraj** [magento/magento2#22150]
Fatal error: Uncaught TypeError: Argument 1 passed to Zend_Mail_Transport_Abstract::send() must be an instance of Zend_Mail, instance of Magento\Framework\Mail\Message given, called in /home/gcadmin/gc_m2/app/code/MagePal/GmailSmtpApp/Plugin/Mail/TransportPlugin.php on line 92 and defined in /home/gcadmin/gc_m2/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php:305 Stack trace: #0 /home/gcadmin/gc_m2/app/code/MagePal/GmailSmtpApp/Plugin/Mail/TransportPlugin.php(92): Zend_Mail_Transport_Abstract->send(Object(Magento\Framework\Mail\Message)) #1 /home/gcadmin/gc_m2/app/code/MagePal/GmailSmtpApp/Plugin/Mail/TransportPlugin.php(30): MagePal\GmailSmtpApp\Plugin\Mail\TransportPlugin->sendSmtpMessage(Object(Magento\Framework\Mail\Message))

2 /home/gcadmin/gc_m2/vendor/magento/framework/Interception/Interceptor.php(135):

MagePal\GmailSmtpApp\Plugin\Mail\TransportPlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure)) #3 /home/gcadmin/gc_m2/vendor/magento/module-email/Model in /home/gcadmin/gc_m2/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php on line 305

Sample issue: (issue in all email process in magento)
1. Fill contact form and submit, then mail functions throws issue
2. Order success email - issue
3. Forgot password email sending issue
....

**Comment by ghost** [comment]
Hi @rvinothraj 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
