### ISSUE TITLE
Category scope Name cached incorrectly on product edit

### ISSUE THREAD

**Issue by ekalinak** [magento/magento2#22155]
### Preconditions
1. Magento 2.3-develop GitHub branch ( Also reproducible on 2.2.5 )
2. Make sure you have enabled all caches

### Steps to reproduce
On clean Magento 2.-3 installation

*Create new store view:*
1. Go to `Stores > Settings > All Stores`
2. Click on `Create Store View`
3. Fill "New store view" form correctly
4. Click on `Save Store View`

*Create new category:*
1. Go to `Catalog > Categories`
2. Click on `Add Subcategory` button
3. Fill category name 
4. Click on `Save` button
5. Change Store View to one you've created in "Create new store view" part of description
6. Unclick `Use Default Value` and fill different `Category Name` value
7. Click on `Save` button

*Create new product*
1. Go to `Catalog > Products`
2. Click on `Add Product`
3. Fill required fields in "New Product" form
4. Click on `Save` button
5. Change Store View to one you've created in "Create new store view" part of description

### Expected result
* Category name for attribute "Categories" is changed according to value for Store View

### Actual result
* Category name for attribute "Categories" is same as for previous Store View

### Additional Info 
* After you clear caches *( In my case via CLI `php bin/magento cache:clean` )* and refresh Product Edit form, you can see correct Category Name *( of course after you change Store View again, category names are not changed )*
* I think in issue #13726 was reported the same bug, but maybe described in wrong way

### Whole issue in GIF

![translations-magento-bug](https://user-images.githubusercontent.com/5930161/55541713-d1357b80-56c5-11e9-8850-1e08105ea35c.gif)

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM, here is your [Magento instance](https://i-22155-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22155-2-3-develop.instances.magento-community.engineering/admin](https://i-22155-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @SikailoISM
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @SikailoISM
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99050`, `MAGETWO-99051` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment]
Hello @ekalinak

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
