### ISSUE TITLE
Order cancel -> payment adapter cancel

### ISSUE THREAD

**Issue by LucianMihalache** [magento/magento2#22153]
### Summary (*) + Examples (*)

I've created a custom payment method with it doing some stuff.
The payment method is using the recommended way of implementing using the adapter (Magento\Payment\Model\Method\Adapter) all good and nice, using some Commands (Magento\Payment\Gateway\CommandInterface), placing (order) and refund (refund) payment actions are working good. The only thing I need more is the cancel command, which I cannot figure out how to call it in the proper way. Firstly I thought that Magento will automatically call the payment method command "cancel" like he is using the other commands as well. After some time after I finished coding, I started testing out the feature, guess what: the cancel is not called.
So I started debugging, going all the way from Magento\Sales\Model\Order.php::cancel() -> calls: $this->getPayment()->cancel(); -> Magento/Sales/Model/Order/Payment.php::cancel(); and all way code that goes from there, has nothing to do with the payment adapter.

I should specify that the payment method does not use all the gateway stuff. It is an offline payment method.

So, my question: Is Magento right on this? Or the feature is not fully implemented?
Should I just use an observer hooking on the event "order_cancel_after" and to simply call the command "manually"?

### Proposed solution

No solution, just questions.

**Edit: The Magento instance used is the latest one from composer, 2.3.1, with no custom extensions installed, just the one I am working on.

***Edit2: I know that this is not a bug or anything else, but this might be a small issue, so I decided to post it here instead of going on other websites.

**Comment by ghost** [comment]
Hi @LucianMihalache thank you for you report, this is real interesting, but can you propose the pr directly and explain, steps to have an issue here, seems like this an good improvement, feel free to propose Pull request with all details, thanks for collaboration :+1:

**Comment by orlangur** [comment]
@engcom-backlog-nazar your message does not make any sense to me :(
