### ISSUE TITLE
Magento 2 Product Attributes Not Allowing New Additions

### ISSUE THREAD

**Issue by ryanandersonLCI** [magento/magento2#22167]
Magento 2 Version 2.2.0

Stores --> Attributes --> Product 

Product attribute values will not update on the admin panel when added. Once a value is added, and save attribute is clicked on the newly added value is no longer present, and not saved.

Steps to reproduce:

Stores --> Attributes --> Product:
Add a new value to your attribute and click save. Expected result is the value gets saved to the brand attribute. The actual result is that the value does not get saved. No error messages are present. There are over 100 values within this attribute.

**Comment by ghost** [comment]
Hi @ryanandersonLCI 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
