### ISSUE TITLE
Sample Data installation erros

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#2216]
HI,

When trying to install the sample data, more preciesly the configurable products sample data I get the following error
PHP Fatal error:  Undefined class constant 'FIELD_NAME_VALIDATION_STRATEGY' in  /app/code/Magento/SampleData/Module/ConfigurableProduct/Setup/Product.php on line 84
I am using the master branch on both repositories. 

Question is: sample data is not yet supported for magento2 on master branch?

Thanks

**Comment by xcomSteveJohnson** [comment]
My understanding is that both master and develop are supported; however, you must *clone* both branches for it to work. Please provide the steps you used.

**Comment by ksz2013** [comment]
Hi,

The steps were the following:
+ checkout from master on magento
+ composer update
+ checkout from master on magento-sample-data
+ build the symlinks between sample-data repo and magento repo using php -f build-sample-data.php -- --ce-source="<your Magento CE install dir>
+ run the installation -> everything went fine until the ConfigurableProductsSampleData -> and there i received that error 
-> in summary on both the master branch was used

**Comment by mazhalai** [comment]
@ksz2013 thank you for reporting the issue. We have created issue MAGETWO-44755.

**Comment by mttjohnson** [comment]
You might try copying the files directly into the magento root rather than running the build script to create symbolic links for all of them.

**Comment by xcomSteveJohnson** [comment]
I believe you should also be able to use the `bin/magento sampledata:deploy` CLI command.

**Comment by Weltpixel** [comment]
Hi,

Issue can be closed, with the latest upgrade everything went smoothly.  
Used bin/magento sampledata:deploy

Thanks,

Ps: Now I have some missing css files on the frontend

**Comment by ksz2013** [comment]
Hi,

Issue can be closed, with the latest upgrade everything went smoothly.  
Used bin/magento sampledata:deploy

Thanks,

Ps: Now I have some missing css files on the frontend
