### ISSUE TITLE
--no-interaction and -n parameters do not work with the setup:config:set CLI subcommand

### ISSUE THREAD

**Issue by tomvoss** [magento/magento2#22168]
### Preconditions (*)

1. Magento CE 2.3.0
2. Previously migrated from Magento CE 1.8.0.0

### Steps to reproduce (*)

1. Run the command:

> bin/magento setup:config:set --cache-backend='redis' \\
                             --cache-backend-redis-server='redis1.example.com' \\
                             --cache-backend-redis-db=0 \\
                             --cache-backend-redis-port=6379 \\
                             --page-cache='redis' \\
                             --page-cache-redis-server='redis1.example.com' \\
                             --page-cache-redis-db=1 \\
                             --session-save='redis' \\
                             --session-save-redis-host='redis1.example.com' \\
                             --session-save-redis-db=2 \\
                             --no-interaction

### Expected result (*)

1. app/etc/env.php should be updated according to the values supplied in the command.

### Actual result (*)

1. app/etc/env.php is not modified.

If the same command is run without the --no-interaction parameter it is successful, but a user must be present to answer the [Y/n] prompt.

Using -n instead of --no-interaction is allowed according to [official documentation](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands.html), but unfortunately it yields the same results.

**Comment by tomvoss** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tomvoss. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tomvoss, here is your [Magento instance](https://i-22168-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22168-2-3-develop.instances.magento-community.engineering/admin](https://i-22168-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tomvoss** [comment]
I am unable to attempt to reproduce this issue according to Magento guidelines because I cannot access the command line. Is SSH access available? Is there another method I can use to run a single bin/magento subcommand then check the contents of app/etc/env.php?

**Comment by ghost** [comment]
Hi @tomvoss thank you for you report, i'm not able to reproduce following steps you described. 
![DeepinScreenshot_select-area_20190405093917](https://user-images.githubusercontent.com/40756439/55608310-da3a5180-5786-11e9-8653-08a48966e564.png)
![DeepinScreenshot_select-area_20190405093943](https://user-images.githubusercontent.com/40756439/55608311-dad2e800-5786-11e9-8bd8-2a522a90818c.png)

problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by tomvoss** [comment]
I'm unable to test this at the moment, but for future viewers of this issue, I believe the first time the command is run it works as intended. Subsequent issuing of the same command appears to succeed but no values are changed. If this behavior is confirmed this issue should be reopened.

**Comment by medigeek** [comment]
was this fixed?

had similar issues on an older m2 version, 2.3.0

to reproduce env.php must a value such as:

```
    'session' => [
        'save' => 'files',
```

tried to change it:
`php bin/magento setup:config:set --session-save='redis' --no-interaction`

it didn't change 'save' to 'redis'

what happens in the background is that the command asks to overwrite or not, I assume the default reply is "no" with --no-interaction, so it doesn't overwrite it.

it worked using a workaround with yes command (i.e. to input "Y" repeatedly):
`{ sleep 3; yes Y; }  | php bin/magento setup:config:set --session-save='redis'`
