### ISSUE TITLE
i have a issue when i want to login to admin panel 

### ISSUE THREAD

**Issue by a7medeeuae** [magento/magento2#22165]
hi

issue when i want to login to admin panel 

i have opencart 3.0.1 on my hosting on godaddy the main domain 
Is it possible that the reason that for the erorr ??

i install magento 2.3.1 on my hosting on godaddy on sub domain :-

 admin panel:-
Fatal error: Magento\Backend\Model\Locale\Manager::getUserInterfaceLocale(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Magento\User\Model\User\Interceptor&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /m/vendor/magento/module-backend/Model/Locale/Manager.php on line 96

**Comment by ghost** [comment]
Hi @a7medeeuae 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by paesjoaopaulo** [comment]
In my case, this problem was caused by session start flag. Set session.autostart = off;

**Comment by luka4** [comment]
for me - simply clear cookie in browser solved the issue.
