### ISSUE TITLE
Upgrade from 2.2.7 to 2.3.1 breaks Authorize.Net Direct Post configuration - "Unable to serialize value"

### ISSUE THREAD

**Issue by Tiberriver256** [magento/magento2#22164]
### Preconditions (*)

Magento 2.2.7 installation with Authorize.Net configuration settings filled in (i.e. api key, etc.)

### Steps to reproduce (*)

1. Upgrade to 2.3.1
2. Attempt to checkout an order

### Expected result (*)

Checkout page should load

### Actual result (*)

Receive an error "Unable to serialize value". Clearing the authorize.net settings from the database and re-entering them resolves the issue as a workaround

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99086` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
Hi @Tiberriver256 ,
According to following announcement this extension was already removed from 2.4 version:
https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445

All future collaboration related to this extension should be on Marketplace using "Contacts" or "Bug reports" related to this extension.

I'm closing this issue.
