### ISSUE TITLE
Typo issue:Magento admin store configuration general web Base url place holder comment spelling mistake

### ISSUE THREAD

**Issue by mohith-ecommerce** [magento/magento2#22169]
There are typo errors found on the Magento admin panel. Please review Base url (secure) . You will find typo error for the place holder comment. In the Base url, the comment should be
Specify URL or placeholder  instead of Specify URL or , or  placeholder.

### Preconditions (*)
1. Magento 2.2.x
2. Magento 2.3.x

### Steps to reproduce (*)
1. Login to Magento admin
2. stores > configuration > general > web > Base Urls(secure)

### Expected result (*)
1. <img width="1226" alt="Screenshot 2019-04-05 at 21 36 33" src="https://user-images.githubusercontent.com/85479/55652182-16070280-57eb-11e9-9ffc-1ad46cc34489.png">

### Actual result (*)
1. ![2019-04-05_12h55_40](https://user-images.githubusercontent.com/35759837/55611174-6148f300-57a2-11e9-8eee-43cc23dd1215.png)

**Comment by magento-engcom-team** [comment]
@amjadm61 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @amjadm61
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99065`, `MAGETWO-99066` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
Expected result is incorrect. This is the expected result (taken from a Magento 2.1.17 installation):

<img width="1226" alt="Screenshot 2019-04-05 at 21 36 33" src="https://user-images.githubusercontent.com/85479/55652182-16070280-57eb-11e9-9ffc-1ad46cc34489.png">

**Comment by orlangur** [comment]
Thanks @hostep, I've edited description.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sanjaychouhan-webkul. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sanjaychouhan-webkul, here is your [Magento instance](https://i-22169-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22169-2-2-develop.instances.magento-community.engineering/admin](https://i-22169-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sanjaychouhan-webkul. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by sureshsdckap** [comment]
I am working on this #dmdcindia1

**Comment by mohith-ecommerce** [comment]
@magento-engcom-team this issue is their in 2.3.1 kindly give the development instance to check once

**Comment by brunoroeder** [comment]
Hello,

I created the PR https://github.com/magento/magento2/pull/24832 for this issue related to #24721 issue

**Comment by hostep** [comment]
Since the auto-close-resolved-issues-bot seems to be sleeping today, let me manually close this one.

----

Hi @mohith227. Thank you for your report.
The issue has been fixed in #24832 by @brunoroeder in 2.3-develop branch
Related commit(s):

- 41e73b35294e7f60f855888363dc9918b02027ab
- 745ac409ea121d9d602ebf2d471531c97cf4746a

The fix will be available with the upcoming 2.3.4 release.
