### ISSUE TITLE
[2.2.7, 2.2.8] - Indexer Schedule - backlog with product import

### ISSUE THREAD

**Issue by jbrada** [magento/magento2#22161]
If I import a product using the CSV import function, index changes are written to the backlog of:

- Product rule catalog
- Catalog Search
- Product price

even though the value has not changed (imported values are same as Magento 2 values).

This behavior did not affect either 2.2.5 or 2.2.6. This behavior occurs in versions 2.2.7 and 2.2.8.

### Preconditions (*)
1. Magento 2.2.7 or Magento 2.2.8 (Not tested on 2.3.x versions) with sample data.
2. indexer:set-mode schedule

### Steps to reproduce (*)
As an example, I will import only 2 fields: sku, qty

1. First import - The qty value is different from the original value. 
Backlog (1) for indexes
- Product rule catalog
- Cataog Search
- Product price
- Stock

2. Second import - The value is the same, there is no change
Backlog (1) for indexes:
- Product rule catalog
- Cataog Search
- Product price

In this case, no index should be backlog (1) because there are no changes made.

### Expected result (*)
Expected result if i import csv with no changes beside actual Magento 2 state.
(sku, qty)
![image](https://user-images.githubusercontent.com/7402947/55558699-e5d93a00-56ec-11e9-9471-905b04f63d60.jpeg)

### Actual result (*)
Actual result if i import csv with no changes as actual Magento 2 state.
![alojbggalhhphobf](https://user-images.githubusercontent.com/7402947/55558766-14efab80-56ed-11e9-943a-4c9d53d8a4cd.jpeg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99126`, `MAGETWO-99127` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by verma-ankur** [comment]
I am working on this at #dmcdindia1

**Comment by jaybouvet** [comment]
Hi !

What is the status of this ?

**Comment by ryanb945** [comment]
Any status update on this?

**Comment by hostep** [comment]
Is this related to https://github.com/magento/magento2/issues/23077 & https://github.com/magento/magento2/pull/23294?
- If yes, then it was fixed by https://github.com/magento/magento2/commit/eec9c26a44f3a62ef426f9ac326ff36269a77d7b (my guess is it will be included in Magento 2.3.4, but don't take my word for it)
- If no, then ignore me :)

**Comment by ryanb945** [comment]
It was related to #22161. Was that moved to those two ticket numbers you referenced?

**Comment by ryanb945** [comment]
Any update on this??

**Comment by magento-engcom-team** [comment]
Hi @jbrada. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24407` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by pmsteil** [comment]
Any details on what causes this "backlog" on the indexes?

Is there a workaround?  I am seeing:

`| catalogrule_product                             | Catalog Product Rule                         | Ready  | Schedule  | working (24658 in backlog) `

**Comment by ryanb945** [comment]
> Any details on what causes this "backlog" on the indexes?
> 
> Is there a workaround? I am seeing:
> 
> `| catalogrule_product | Catalog Product Rule | Ready | Schedule | working (24658 in backlog) `

From what I can tell, the cause is whenever there is a mass amount of data changed using the import function. Workaround that we use is to just run bin/magento indexer:reset and then running bin/magento indexer:reindex commands. That usually clears the backlog and makes all data updates show up properly on frontend. At least that is what works for us.
