### ISSUE TITLE
Reorder configurable product adds 2nd invalid simple product to shipping request

### ISSUE THREAD

**Issue by wsajosh** [magento/magento2#22175]
### Preconditions (*)
Reproduced on Magento 2.2.8 and 2.3-develop

Enable UPS XML (or any other live rate carrier) and set a debug point in the collectRates function. E.g: app/code/Magento/Ups/Model/Carrier.php::collectRates() around line 215. The goal of this is to inspect the $request variable. This won't affect UPS but is the simplest way to highlight the issue. It will affect any module which uses the all items array.

### Steps to reproduce (*)
1. Place a order with one configurable product in it with a qty of 1 in the cart
2. Navigate to Magento admin panel -> Sales -> Orders and view the order that was just placed
3. Click re-order from within the admin panel
4. This should hit your debug point now. Check the $request object and look at the all_items array. It will contain the configurable product (correct) and a simple product (incorrect)

### Expected result (*)
1. $request->getAllItems() within shipping carriers to return accurate representation of items in cart

### Actual result (*)
1. $request->getAllItems() returns an invalid simple product

![admin_order_view](https://user-images.githubusercontent.com/1335244/55623779-e7157000-579b-11e9-8b8c-99179cdf50f1.jpg)
![all_items_array](https://user-images.githubusercontent.com/1335244/55623780-e7ae0680-579b-11e9-8963-315c4c5a0a05.png)
![items_ordered](https://user-images.githubusercontent.com/1335244/55623781-e7ae0680-579b-11e9-9014-e5c0fca21ad2.jpg)
![valid_configurable_item](https://user-images.githubusercontent.com/1335244/55623782-e7ae0680-579b-11e9-983b-c3405e0a6b14.png)
![invalid_simple_item](https://user-images.githubusercontent.com/1335244/55623783-e7ae0680-579b-11e9-9dfe-6e67497c24a7.png)

**Comment by orlangur** [comment]
@wsajosh is there only `$request->getAllItems()`? There is no something like `$request->getAllVisibleItems()`?

**Comment by orlangur** [comment]
@wsajosh just noticed screenshots contain all the needed information. Observed system behavior is absolutely correct.
