### ISSUE TITLE
tag for 1.0.0-beta5 missing

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#2217]
hi, I saw in your changelog that 1.0.0-beta5 should be available, but I cannot find a tag for it. How can I get 1.0.0-beta5?

**Comment by markoshust** [comment]
the tag for `1.0.0-beta6` is also missing

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by Flyingmana** [comment]
The tag is listed in http://packages.magento.com/ also we now have an first RC, so I think this Issue can get closed?

**Comment by markoshust** [comment]
Yea, now that RC is out I don't think we need this.

**Comment by davidalger** [comment]
Just pushed the beta5 and beta6 tags up to this repo. Closing.
