### ISSUE TITLE
Offline Payment Methods not decrease Stock on Place Order

### ISSUE THREAD

**Issue by mapescador-integramedia** [magento/magento2#22176]
### Preconditions (*)

1. Magento 2.1.16 (possible others)
2. Stores->Configuration->Catalog->Inventory->Stock Options->display Out of Stock Products=Yes

### Steps to reproduce (*)

1. Place an Order with offline payment method (Bank Transfer, Cash on delivery)

### Expected result (*)

1. Stock of products decrease.

### Actual result (*)
1. Stock not decrease

### Posible Cause
Event Observer Mage_CatalogInventory_Model_Observer::subtractQuoteInventory not detect InventoryProcessed=false.

### Posible Patch
Add  call to $order->setInventoryProcessed(false) on place order. 

Specifically on module-checkout\Controller Onepage\SaveOrder.php
```
--- vendor/magento/module-checkout/Controller/Onepage/SaveOrder.php	(revision 9d20328417d98993c7a2bdbc055201221c37ffee)
+++ vendor/magento/module-checkout/Controller/Onepage/SaveOrder.php	(revision 841942aca0fba85e2ac583ad8e77fee11e07ac5a)
@@ -52,7 +52,8 @@
                 $this->getOnepage()->getQuote()->getPayment()->setQuote($this->getOnepage()->getQuote());
                 $this->getOnepage()->getQuote()->getPayment()->importData($data);
             }
-
+            # Ref: Mage_CatalogInventory_Model_Observer::subtractQuoteInventory
+            $this->getOnepage()->getQuote()->setInventoryProcessed(false);
             $this->getOnepage()->saveOrder();
 
             $redirectUrl = $this->getOnepage()->getCheckout()->getRedirectUrl();

```

**Comment by ghost** [comment]
Hi @mapescador-integramedia thank you for you report, We no longer accept pull requests to the v2.1 or v2.0 release lines to focus all development efforts on v2.3 and v2.2. 
https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html  
Thanks for collaboration, This issue will help people who discovered this issue on 2.1 version
