### ISSUE TITLE
Configuration -> Advanced -> System ERROR

### ISSUE THREAD

**Issue by Bravarg** [magento/magento2#22172]
### Preconditions (*)

1. Magento 2.2-develop

### Steps to reproduce (*)

1. Install magento
2. Go to admin -> stores -> configurations -> advanced -> system
3. Reload page WITHOUT SAVING configurations.

### Expected result (*)

1. Page reloads without errors and with content

### Actual result (*)

1. Page content empty because of errors, that appears in developer mode:
4 exception(s):
Exception #0 (Magento\Framework\Exception\AlreadyExistsException): Unique constraint violation found
Exception #1 (Magento\Framework\DB\Adapter\DuplicateException): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'default-0-system/full_page_cache/varnish/access_list' for key 'DEV_CORE_CONFIG_DATA_SCOPE_SCOPE_ID_PATH', query was: INSERT INTO `dev_core_config_data` (`path`, `value`) VALUES (?, ?)
Exception #2 (Zend_Db_Statement_Exception): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'default-0-system/full_page_cache/varnish/access_list' for key 'DEV_CORE_CONFIG_DATA_SCOPE_SCOPE_ID_PATH', query was: INSERT INTO `dev_core_config_data` (`path`, `value`) VALUES (?, ?)
Exception #3 (PDOException): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'default-0-system/full_page_cache/varnish/access_list' for key 'DEV_CORE_CONFIG_DATA_SCOPE_SCOPE_ID_PATH'

Related issue #13224

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22172-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22172-2-3-develop.instances.magento-community.engineering/admin](https://i-22172-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @OlehWolf hi @shikhamis11 i'm also facing this issue with varnish configuration, but this is random.

**Comment by shikhamis11** [comment]
@OlehWolf this issue is not reproducible at current magento 2.3-develop instance . Please check if you are able to reproduce it or not ? Also check if you need to change the issue summary to update the steps to reproduce the issue

**Comment by shikhamis11** [comment]
@engcom-backlog-nazar Thanks for the information

**Comment by Bravarg** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @OlehWolf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @OlehWolf, here is your [Magento instance](https://i-22172-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22172-2-3-develop.instances.magento-community.engineering/admin](https://i-22172-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Bravarg** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @OlehWolf. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @OlehWolf, here is your [Magento instance](https://i-22172-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22172-2-2-develop.instances.magento-community.engineering/admin](https://i-22172-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Bravarg** [comment]
@shikhamis11 Sorry, in newest 2.3-develop I wasn't able to reproduce, but in 2.2-develop issue still exists.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99070` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nadeefit6** [comment]
This issue cannot be reproduced in 2.2.7.

**Comment by Bravarg** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @OlehWolf. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @OlehWolf, here is your [Magento instance](https://i-22172-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22172-2-2-develop.instances.magento-community.engineering/admin](https://i-22172-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Bravarg** [comment]
True, now its already fixed in 2.2-develop branch, can be closed.
