### ISSUE TITLE
Empty LESS source file causes setup:static-content:deploy command fail

### ISSUE THREAD

**Issue by Hailong** [magento/magento2#22183]
### Preconditions (*)

1. 3.2-develop

### Steps to reproduce (*)

1. Clone the latest code from 3.2-develop branch.
2. Setup a new site.
3. Add an empty LESS file (or with some comments in it) to `app/design/frontend/Magento/blank/web/css/test-empty.less`
4. Edit `app/design/frontend/Magento/blank/Magento_Theme/layout/default_head_blocks.xml` file to include it with `<css src="css/test-empty.css"/>`
5. Run the static content deploy command: `bin/magento setup:static-content:deploy`

### Expected result (*)

1. Error or warning message for the empty file
2. The content deploy command continues and finishes.

### Actual result (*)

1. Content deploy command fails.
2. Error message is a full stack trace, and hard to figure out the real problem.

**Comment by Hailong** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @Hailong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Hailong, here is your [Magento instance](https://i-22183-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22183-2-3-develop.instances.magento-community.engineering/admin](https://i-22183-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@Hailong Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by Hailong** [comment]
This issue has been fixed with PR#22182, closing it now.
