### ISSUE TITLE
Magento 2.3.1, Invalid URL key when saving category for store view

### ISSUE THREAD

**Issue by KhaledJoulani** [magento/magento2#22187]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2.15-0ubuntu0.18.04.2
3. nginx version: nginx/1.14.0

### Steps to reproduce (*)

You must have a second store view.
1. Create a category with an English name and save.
2. Select the category you just created and switch to the second store view.
3. Un-check Use Default Value for category name and rename the category using Arabic letters and save.
4. Now try to edit the Arabic name again and hit save, or even just save again while selecting the store view that has the Arabic category name.

### Expected result (*)

1. You saved the category.

### Actual result (*)

1. Invalid URL key
### Additional information
So I checked the log file in, var/log/system.log

[2019-04-06 14:45:41] main.CRITICAL: Exception message: Invalid URL key
Trace: <pre>#1 Magento\CatalogUrlRewrite\Observer\CategoryUrlPathAutogeneratorObserver->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:72]
#2 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:60]
#3 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#4 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#5 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/Model/AbstractModel.php:701]
#6 Magento\Framework\Model\AbstractModel->beforeSave() called at [vendor/magento/module-catalog/Model/AbstractModel.php:383]
#7 Magento\Catalog\Model\AbstractModel->beforeSave() called at [vendor/magento/framework/EntityManager/Observer/BeforeEntitySave.php:34]
#8 Magento\Framework\EntityManager\Observer\BeforeEntitySave->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:72]
#9 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:60]
#10 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#11 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#12 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/EntityManager/EventManager.php:52]
#13 Magento\Framework\EntityManager\EventManager->dispatchEntityEvent() called at [vendor/magento/framework/EntityManager/Operation/Update.php:106]
#14 Magento\Framework\EntityManager\Operation\Update->execute() called at [vendor/magento/framework/EntityManager/EntityManager.php:96]
#15 Magento\Framework\EntityManager\EntityManager->save() called at [vendor/magento/module-catalog/Model/ResourceModel/Category.php:1104]
#16 Magento\Catalog\Model\ResourceModel\Category->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Catalog\Model\ResourceModel\Category\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Catalog\Model\ResourceModel\Category\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Category.php:44]
#19 Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Category->addCommitCallback() called at [vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Category.php:28]
#20 Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Category->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\Catalog\Model\ResourceModel\Category\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Cache/FlushCacheByTags.php:68]
#22 Magento\Framework\App\Cache\FlushCacheByTags->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Catalog\Model\ResourceModel\Category\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\Catalog\Model\ResourceModel\Category\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php:52]
#25 Magento\Catalog\Model\ResourceModel\Category\Interceptor->save() called at [vendor/magento/framework/Model/AbstractModel.php:654]
#26 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Catalog\Model\Category\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Catalog\Model\Category\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Catalog\Model\Category\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Model/Category/Interceptor.php:26]
#30 Magento\Catalog\Model\Category\Interceptor->save() called at [vendor/magento/module-catalog/Controller/Adminhtml/Category/Save.php:220]
#31 Magento\Catalog\Controller\Adminhtml\Category\Save->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#32 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#33 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#34 Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#35 Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#36 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#37 Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#38 Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Controller/Adminhtml/Category/Save/Interceptor.php:26]
#39 Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#40 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#41 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#42 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#43 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#44 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#45 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#46 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#47 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre> 
<pre>[] []
[2019-04-06 14:45:41] main.INFO: Broken reference: the 'atwix_testblock' element cannot be added as child to 'head.additional', because the latter doesn't exist [] []
[2019-04-06 14:45:41] main.INFO: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header.inner.right' and 'header' respectively. [] []</pre>
And I tried to debug the issue.
In the execute function here:
Magento\CatalogUrlRewrite\Observer\CategoryUrlPathAutogeneratorObserver->execute()
which for my Magento 2 installation  is in this file:
vendor/magento/module-catalog-url-rewrite/Observer/CategoryUrlPathAutogeneratorObserver.php, Line:76.
This one: $resultUrlKey = $category->formatUrlKey($category->getOrigData('name'));
The value of $resultUrlKey  is empty,
now the next line is :
$this->updateUrlKey($category, $resultUrlKey);
and in updateUrlKey() there is a check:
 if (empty($urlKey)) {
            throw new \Magento\Framework\Exception\LocalizedException(__('Invalid URL key'));
 }.
So after all this i debugged formatUrlKey() function from line 76, found the function in:
vendor/magento/module-catalog/Model/Category.php, line:649.
In this function there is only one line:
return $this->filter->translitUrl($str);
that leads to this class:
vendor/magento/framework/Filter/TranslitUrl.php
and in there, there is this code:
<pre>
class TranslitUrl extends Translit
{
    /**
     * Filter value
     *
     * @param string $string
     * @return string
     */
    public function filter($string)
    {

        $string = preg_replace('#[^0-9a-z]+#i', '-', parent::filter($string));
        $string = strtolower($string);
        $string = trim($string, '-');
        return $string;
    }
}
</pre>
at this line $string = preg_replace('#[^0-9a-z]+#i', '-', parent::filter($string));
it returns " - " only.
and at this line it makes it empty : 
$string = trim($string, '-');
That's all, so what pattern should I used that wont effect Arabic letters, I'm not a regex expert!.

**Comment by KhaledJoulani** [comment]
@magento-engcom-team give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @KhaledJoulani. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by KhaledJoulani** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @KhaledJoulani. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @KhaledJoulani, here is your [Magento instance](https://i-22187-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22187-2-3-develop.instances.magento-community.engineering/admin](https://i-22187-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by KhaledJoulani** [comment]
I confirm that I was able to reproduce the issue on vanilla Magento instance following steps to reproduce.
How do i actually confirm this ? the checkbox is disabled

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22187-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22187-2-3-develop.instances.magento-community.engineering/admin](https://i-22187-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99081` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22187-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22187-2-2-develop.instances.magento-community.engineering/admin](https://i-22187-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
it's may be related to #13689

**Comment by KhaledJoulani** [comment]
Wow it's been a year on the related issue you linked, no one fixed it ?

**Comment by hostep** [comment]
And probably also related to https://github.com/magento/magento2/issues/20879
Magento is working on adding Japanese support for url's in https://github.com/magento/magento2-jp/pull/77, and this solution will probably be generalised for other languages later on I'm guessing.
Maybe @vkublytskyi can help out here?

**Comment by dmanners** [comment]
In my view this is a duplicate of https://github.com/magento/magento2/issues/22187 so I will close this. I know that we have a module in the Japanese localization project that is aiming at URLRewrites https://github.com/magento/magento2-jp/tree/2.3-develop/JapaneseUrlRewrite and I think this would be a good module or fixes to have in the main repository as well.

Thank you for raising this issue please feel free to track the progress in the other issue.

**Comment by sjgdk** [comment]
> In my view this is a duplicate of #22187 so I will close this. I know that we have a module in the Japanese localization project that is aiming at URLRewrites https://github.com/magento/magento2-jp/tree/2.3-develop/JapaneseUrlRewrite and I think this would be a good module or fixes to have in the main repository as well.
> 
> Thank you for raising this issue please feel free to track the progress in the other issue.

I am sorry I couldn't get which issue you are referring to. #22187 is this issue, there is no other issue.

It's not fixed as well, so you shouldn't have closed this issue without providing a fix yet.

**Comment by knro** [comment]
Is there any update on this?

**Comment by hostep** [comment]
https://github.com/magento/magento2/commit/6f4f511822fbbcb743a7d4a8de6353d207d99429 "might" fix this problem based on the commit message. (will be included in Magento 2.3.3, which will be out in a couple of weeks)

**Comment by Berman59** [comment]
Was this ever fixed?

**Comment by NiklasBr** [comment]
2.3.3 did not fix this, I don't understand why @dmanners closed this issue by saying that it is a duplicate of itself, he probably found some other issue and copied the incorrect number. But which issue number should it be?

**Comment by vishalthakurit** [comment]
> 

Actually according to commit files... this is for product URL rewrite module. not for Categories.
