### ISSUE TITLE
2.3 to 2.3.1 System Upgrade Status: update application is running from 12 hours

### ISSUE THREAD

**Issue by nittn** [magento/magento2#22193]
### Preconditions (*)

1. Magento 2.3 to Magento 2.3.1 system upgrade started - Apache Centos 7, php 7.2.15
![Screen Shot 2019-04-07 at 11 22 10 AM](https://user-images.githubusercontent.com/48263579/55679345-92066500-5927-11e9-9dc7-1e518528b56f.png)

### Steps to reproduce (*)

1. Login to magento admin >> system upgrade

### Expected result (*)

1. started at 20:42 UTC time 
[Screenshots, logs or description]
![Screen Shot 2019-04-07 at 11 22 10 AM](https://user-images.githubusercontent.com/48263579/55679350-c4b05d80-5927-11e9-83b1-b2c49967a5e4.png)

### Actual result (*)

1.and still running for more than 9 hrs 
[Screenshots, logs or description]
![Screen Shot 2019-04-07 at 11 25 31 AM](https://user-images.githubusercontent.com/48263579/55679364-0fca7080-5928-11e9-96bb-1d00c7ad1d1e.png)

**Comment by nittn** [comment]
> Hi @nittn. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @nittn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [x]  no

**Comment by magento-engcom-team** [comment]
Hi @nittn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nittn, here is your [Magento instance](https://i-22193-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22193-2-3-develop.instances.magento-community.engineering/admin](https://i-22193-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nittn** [comment]
> Hi @nittn. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]   Summary of the issue
> * [ ]   Information on your environment
> * [x]   Steps to reproduce
> * [x]   Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @nittn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]   yes
> * [x]   no

**Comment by magento-engcom-team** [comment]
Hi @nittn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nittn, here is your [Magento instance](https://i-22193-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22193-2-3-develop.instances.magento-community.engineering/admin](https://i-22193-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
