### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by adrok** [magento/magento2#2219]
In magento profiler, execution time for locale/currency ~ 0.7 sec. (same for frontend and backend)

**Comment by mazhalai** [comment]
@adrok what benchmark are you using to perform this calculation? Profiler in M1?

**Comment by adrok** [comment]
Hello,

M2 Profiler (.htaccess MAGE_PROFILER html)

**Comment by mazhalai** [comment]
@adrok yes, but what exact problems are you experiencing? can you please give us more details? Magento version? how did you deploy - git or composer? OS? Server?
