### ISSUE TITLE
 Magento 2.3 Command line installation issue : Connection "default" is not defined 

### ISSUE THREAD

**Issue by netorica** [magento/magento2#22198]
### Preconditions (*)

1. Magento 2.3.1
2. Ubuntu 18.04 LTS
3. PHP 7.2.16-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar 7 2019 20:23:29) ( NTS )
4. MySQL 5.6.43-84.3 Percona Server (GPL), Release 84.3, Revision 71967c9
5. Composer 1.9-dev (using composer.phar)
6. /var/run/mysqld/mysqld.sock exist
7. PDO config pdo_mysql.default_socket points to /var/run/mysqld/mysqld.sock (reference to this issue https://github.com/magento/magento2/issues/4281)

### Steps to reproduce (*)
1. run the following using composer.phar
`php composer.phar create-project --repository=https://repo.magento.com/ magento/project-community-edition htdocs`
2. And do the the following installation in command line
`php bin/magento setup:install --base-url=http://magepwa.test --db-host=localhost --db-name=magepwa --db-user=root --db-password=pass --backend-frontname=admin --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=xxxx --language=en_US --currency=USD --timezone=UTC --use-rewrites=1`

### Expected result (*)
1. It should install the magento2.3 without any problems

### Actual result (*)
1. ![image](https://user-images.githubusercontent.com/1390979/55698849-88016680-59fa-11e9-8651-9c742b6c3e9f.png)

**Comment by ghost** [comment]
HI @mahanmp thank you for you report, this issue related to your configuration, please verify all your settings, and try again, i believe that you are missed something in your environment config.

**Comment by netorica** [comment]
Can you lead me to a possible config that i missed with this kind of error?
I tried to put incorrect database credentials and it seems to show a different error which is mysql error.

**Comment by ghost** [comment]
@mahanmp  **Composer 1.9-dev (using composer.phar)** can you try with non dev version ?

**Comment by netorica** [comment]
I tried to use the latest snapshot now https://getcomposer.org/download/1.8.4/composer.phar which is Composer version 1.8.4 2019-02-11 10:52:10
And i still get the same issue. 

I really don't get the idea where this thing leads to an issue aside from this https://github.com/magento/magento2/issues/4281 but I don't use HHVM and the /var/run/mysqld/mysqld.sock exist

I would suggest that you try the same Preconditions that I did above to replicate my issue.

**Comment by netorica** [comment]
I captured the issue, the issue was the opcache.enable_cli was enabled. Is this intentional?

**Comment by amenk** [comment]
Does anybody have a clue how this was influence by the opcache?

**Comment by phoenix-bjoern** [comment]
We can reproduce this issue with Magento 2.4.4 + PHP 8.1. It is not related to OpCache (we uninstalled the module). In our scenario the error occurs at the very end of the `setup:install` routine where the maintenance mode gets disabled and the `Magento\MessageQueue\Model\Plugin\ResourceModel\Lock` plugin gets triggered. The class `Magento\MessageQueue\Model\ResourceModel\Lock` gets instantiated with an outdated `$context` where the `\Magento\Framework\App\DeploymentConfig` object has been initiated before the database connection has been written to `app/etc/env.php`.
![Bildschirmfoto 2022-06-23 um 12 24 33](https://user-images.githubusercontent.com/846569/175278003-b37abaf5-f776-439e-a627-4b041ae37f55.png)

We tried all kinds of "late binding" (proxies, non-shared instances, ObjectManager etc.) but we haven't been able to create the `ResourceModel\Lock` with an updated version of the DeploymentConfig which would reflect the updated connection information in `app/etc/env.php`.
The only workaround for us is a try..catch block in the plugin - there are no outdated locks in a fresh database anyway.
Not sure if this is useful to other devs but this is our patch to make the install routing pass:
```
diff --git a/vendor/magento/module-message-queue/Model/Plugin/ResourceModel/Lock.php b/vendor/magento/module-message-queue/Model/Plugin/ResourceModel/Lock.php
index 30f275520f..9934c53460 100644
--- a/vendor/magento/module-message-queue/Model/Plugin/ResourceModel/Lock.php
+++ b/vendor/magento/module-message-queue/Model/Plugin/ResourceModel/Lock.php
@@ -36,7 +36,11 @@ class Lock
     public function afterSet(\Magento\Framework\App\MaintenanceMode $subject, $result)
     {
         if (!$subject->isOn() && $result) {
-            $this->lock->releaseOutdatedLocks();
+            try {
+                $this->lock->releaseOutdatedLocks();
+            } catch (\DomainException $e) {
+                // during installation it is okay to fail as no outdated locks exists in a fresh DB
+            }
         }
     }
 }
```

**Comment by Jarzebowsky** [comment]
@phoenix-bjoern please check if you have `config.php` file in `app/etc/` directory when you try to run `setup:install`.

**Comment by phoenix-bjoern** [comment]
@Jarzebowsky yes, we definitely have `app/etc/config.php`. There is no `env.php` as it gets created by ece-tools on-the-fly on first deployment.

**Comment by Jarzebowsky** [comment]
@phoenix-bjoern so that's the issue here. Removal of `app/etc/config.php` file resolves the issue. It can't exists when you try to install magento.

**Comment by phoenix-bjoern** [comment]
@Jarzebowsky is that a philosophical question? OFC it can exist. There can also be 3rd party modules and the config.php tells which modules are enabled and which are not. What does not exist are the database tables. 
But thanks for the hint, will do some tests to see if it changes the behavior.
