### ISSUE TITLE
Trailing slash on layered navigation filter pages results in 404 page not found

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#22192]
### Preconditions (*)

1.Magento 2.3.1
2.

### Steps to reproduce (*)

1.Create a category
2.Create a product
3.Create attribute of any color and assign for example lets say blue color to the product
4.Go to the created category and select blue color to filter the product.
5.Go to browser URL and add trailing slash to the end of this URL

### Expected result (*)

1. Layered navigation filter page with trailing slash should not result in 404 page not found
2.

### Actual result (*)

1. 404 page not found
2.

**Comment by monotheist** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ethniccode. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ethniccode, here is your [Magento instance](https://i-22192-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22192-2-3-develop.instances.magento-community.engineering/admin](https://i-22192-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by monotheist** [comment]
Closed. Not reproducible.
