### ISSUE TITLE
Concern with Elasticsearch migration

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#22209]
I have concerns with the SQL search being depreciated and replaced with Elasticsearch, our cloud server hosted by Siteground doesn't support Java Development Kit that is required and they also say that there is quite a resource requirement if they were able to support. Unless we upgrade to a very expensive dedicated server plan the latest Magento versions going forward may not work without 3rd party search engine modules.

Will the SQL search be staying in Magento or is it being phased out?

**Comment by ghost** [comment]
Hi @devchris79 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
