### ISSUE TITLE
Ability to delete a Content Staging event

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#22221]
### Preconditions (*)
Magento Commerce 2.3.0 / 2.3.1
At least 1 scheduled content update

### Steps to reproduce (*)
Create an scheduled content update

### Description (*)
Add ability to delete a scheduled content update. 

### Expected behavior (*)
'Delete' button on Staging > Update > Edit screen, and/or Delete from row in grid view

### Benefits
Would allow removal of scheduled content changes that were programmed in error

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Magento Open Source, isn't it?

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.
