### ISSUE TITLE
Magento 2.3 not saving image category

### ISSUE THREAD

**Issue by lucasvm** [magento/magento2#22222]
### Summary (*)
When creating a new category or editing an existing one, we are not able to save a new image category or icon.

The image is being uploaded but not saved , so it will still show the old image, we can see the new image on server, but not saved.

### Examples (*)
We are using Magento 2.3.

### Proposed solution
Not sure whats the problem, we can updated the category icon or main image.

**Comment by ananth-iyer** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ananth-iyer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ananth-iyer, here is your [Magento instance](https://i-22222-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22222-2-3-develop.instances.magento-community.engineering/admin](https://i-22222-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lucasvm** [comment]
Thank you, just to clarify, for example the title is being saved ... But not the image or icon ... And the image is being uploaded to server...

**Comment by ananth-iyer** [comment]
@lucasvm Did you perform migration to Magento 2.3?

**Comment by lucasvm** [comment]
Hello Sir

 No, i have just made a clean instalation from Git, just done:
 git clone..

**Comment by ananth-iyer** [comment]
@lucasvm Please try it on the below fresh Magento 2.3 instance and let us know if the issue still exists.

> Hi @ananth-iyer, here is your [Magento instance](https://i-22222-2-3-develop.instances.magento-community.engineering).
> Admin access: https://i-22222-2-3-develop.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

**Comment by lucasvm** [comment]
Looks good on demo site, whats the files involved on this?

**Comment by ananth-iyer** [comment]
@lucasvm demo site is a fresh instance which is generated by Magento bot for testing purposes and reproduce the issue reported.
I will try tomorrow with git clone because it takes long time to setup.
Please let me know your server configuration also.

**Comment by neeta-wagento** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento, here is your [Magento instance](https://i-22222-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22222-2-3-develop.instances.magento-community.engineering/admin](https://i-22222-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by neeta-wagento** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento, here is your [Magento instance](https://i-22222-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22222-2-2-develop.instances.magento-community.engineering/admin](https://i-22222-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by neeta-wagento** [comment]
Hello . 

I have verified the issue in 2.2 and 2.3 develop instance 

I cannot reproduce the issue in 2.3-develop and 2.2-develop
Here is attached screenshots!
![Screenshot from 2019-04-09 12-25-49](https://user-images.githubusercontent.com/33098216/55779465-1f31f100-5ac3-11e9-92ef-acbb222fc5db.png)

**Comment by lucasvm** [comment]
Hello Sir, ok, i have done a fresh install and it works, but with my db not, so, i assume its a db issue, can you please tell me witch tables are involved on this? so i can truncate them...i think its catalog_eav_entity maybe?
