### ISSUE TITLE
Can not delete Attribute Set from Backend

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#22224]
### Preconditions (*)

1. Magento 2.3.x
2.

### Steps to reproduce (*)

1. Create a new attribute or edit existing one.
2. Try to delete it.

### Expected result (*)

1. 
![Screenshot](https://user-images.githubusercontent.com/32479280/55744171-ec9be000-5a51-11e9-8a24-c91d1aac325f.png)

2.

### Actual result (*)

1. It gives 404.
2.
![Screenshot](https://user-images.githubusercontent.com/32479280/55744265-28cf4080-5a52-11e9-86a3-3a8c5520d91f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @maheshWebkul721
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @maheshWebkul721
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99097` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SzabKel** [comment]
Isn't this issue fixed as of 2.3.1? I had this too on 2.3.0 but not after patching to 2.3.1.

**Comment by mageshrdckap** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
@mageshrdckap thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mageshrdckap** [comment]
This issue isn't reproducible 2.3.develop . Working Fine. Steps  Used to Check this

1. Add a New Attribute Set
2. Select The Attribute Set from the List
3. Click on Delete Button
4. Attribute has been deleted. And following message is shown "The attribute set has been removed.
"
![magento2_attribute_delete](https://user-images.githubusercontent.com/44895854/57174523-09afad00-6e5e-11e9-9572-3f77add7a95c.png)

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-22224-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22224-2-3-develop.instances.magento-community.engineering/admin](https://i-22224-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
