### ISSUE TITLE
The method \Magento\Cms\Helper\Wysiwyg\Images::getImageHtmlDeclaration()...

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2222]
The method \Magento\Cms\Helper\Wysiwyg\Images::getImageHtmlDeclaration() uses \Magento\Store\Api\Data\StoreInterface interface but relies on getBaseUrl() method with is absent in the interface and presents in a particular implementation only (\Magento\Store\Model\Store)

### Preconditions

1. Magento 2 code.

### Steps to reproduce

1. Open method \Magento\Cms\Helper\Wysiwyg\Images::getImageHtmlDeclaration code.
2. Make sure method it uses method \Magento\Store\Model\Store::getBaseUrl.
3. Open \Magento\Store\Api\Data\StoreInterface code.

### Expected result

getBaseUrl method is declared in  \Magento\Store\Api\Data\StoreInterface.

### Actual result

getBaseUrl method is absent in \Magento\Store\Api\Data\StoreInterface and is present in a particular implementation only (\Magento\Store\Model\Store).

https://github.com/magento/magento2/blob/550f10ef2bb6dcc3ba1ea492b7311d7a80d01560/app/code/Magento/Cms/Helper/Wysiwyg/Images.php#L170

I think if the method `\Magento\Cms\Helper\Wysiwyg\Images::getImageHtmlDeclaration()` needs a concrete non-standard `\Magento\Store\Api\Data\StoreInterface` implementation then it must declare it explicitly.

**Comment by antonkril** [comment]
Agree. Should be fixed.

**Comment by magento-engcom-team** [comment]
@dmitry-fedyuk, thank you for your report.
We've created internal ticket(s) MAGETWO-84436 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@dmitry-fedyuk, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
