### ISSUE TITLE
IE11 cannot checkout on 2.2.8

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#22229]
### Preconditions
1. Magento 2.2.8 (It did not manifest itself on 2.2.7)
2. PHP 7.1.27 (In our case - may or may not be a factor - we are running in php-fpm)
3. MariaDB 10.3.13-1.el7.centos (In our case - may or may not be a factor)
4. Windows 7 with IE 11 *OR* Windows 10 with IE11 (I have heard rumors this also affects IE10, but I cannot confirm this) - Edge does not seem to be a problem

### Steps to reproduce
1. Create a product in the back end, set to active with a qty > 1
2. In IE11, Go to the front end, add item to cart
3. Go to the checkout page

### Expected result
1. Checkout page loads and spinner disappears

### Actual result
1. Checkout page hangs with the default spinner
2. This error in the inspector:
SCRIPT445: Object doesn't support this action
File: checkout, Line: 1817, Column: 17

Here is the code snippet in the inspector
```
 <script type="text/javascript">
        //<![CDATA[
        require([
            'jquery',
            'mage/cookies'
        ], function ($) {
            "use strict";

            var referConfig = {"cookieName":"mp_refer","prefix":"code","isUrlParam":true,"defaultReferUrl":false};
            var value;
            if (referConfig.isUrlParam) {
                var url = new URL(window.location);   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<That line is here
                value = url.searchParams.get(referConfig.prefix);
            } else {
                value = window.location.hash;
                if (value) {
                    if (referConfig.prefix && (value.indexOf(referConfig.prefix) !== -1)) {
                        value = value.substr(referConfig.prefix.length + 1)
                    } else {
                        value = value.substr(1);
                    }
                }
            }

            setCookie(value, referConfig);

            function setCookie(value, referConfig) {
                if (value) {
                    $.mage.cookies.set(referConfig.cookieName, value);
                    if (referConfig.defaultReferUrl) {
                        window.location = referConfig.defaultReferUrl;
                    }
                }
            }
        });
        //]]>
</script>
```

**Comment by justinharris1986** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986, here is your [Magento instance](https://i-22229-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22229-2-2-develop.instances.magento-community.engineering/admin](https://i-22229-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by justinharris1986** [comment]
@magento-engcom-team give me 2.2.8 instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986, here is your [Magento instance](https://i-22229-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-22229-2-2-8.instances.magento-community.engineering/admin](https://i-22229-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by justinharris1986** [comment]
@magento-engcom-team give me 2.2 instance

**Comment by justinharris1986** [comment]
ugh I cannot reproduce it in your instances. I'll go back to my dev and see whats up.
