### ISSUE TITLE
Backward-incompatible change between 2.2.7 and 2.2.8

### ISSUE THREAD

**Issue by yutv** [magento/magento2#22238]
### Preconditions (*)

1. Magento 2.2.7 and Magento 2.2.8
2. PHP 7.1.10

### Steps to reproduce (*)
1. Create a custom module in Magento 2.2.7 with the following class:
**app/code/Vendor/Module/Block/Product/View/Options/Type/Swatch.php**

        <?php

        namespace Vendor\Module\Block\Product\View\Options\Type;

        use Magento\Catalog\Block\Product\View\Options\Type\Select;

        class Swatch extends Select
        {
            public function getValuesHtml()
            {
                $html = parent:getValuesHtml();
                // custom logic goes here
                return $html;
            }
        }
2. Check that this class doesn't cause PHP Fatal Error in Magento 2.2.7
3. Upgrade to Magento 2.2.8

### Expected result (*)

1. No fatal error in custom module
2. **Method declaration in Magento classes MUST NOT change between patch versions (e.g. 2.2.7 and 2.2.8)**

### Actual result (*)

1. Fatal error in custom module:

        Fatal error:  Declaration of Vendor\Module\Block\Product\View\Options\Type\Swatch::getValuesHtml() 
        must be compatible with Magento\Catalog\Block\Product\View\Options\Type\Select::getValuesHtml(): string 
        in app/code/Vendor/Module/Block/Product/View/Options/Type/Swatch.php on line 9

### Backward-incompatible change

The issue caused by backward-incompatible [commit](https://github.com/magento/magento2/commit/4fae2efc33d433b71fe0e231beeade9e5d22dbfd#diff-7322af2a3adbb8b9d8fc376bd3040f93R62) between Magento 2.2.7 and 2.2.8 made by @rleshchenko.

The declaration of the **getValuesHtml** method was changed from:

    public function getValuesHtml()

to:

    public function getValuesHtml(): string

As result any class which extends this method in old declaration becomes incompatible with the new one and throws fatal error.

Note: Issue is still exists in the 2.2-develop branch: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Block/Product/View/Options/Type/Select.php#L62

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99129` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @yutv. Thank you for your report. 
The issue has been fixed in magento/magento2#22267 by @VitaliyBoyko in 2.2-develop branch
Related commit(s):
 - [179bedf3de99244b384c97cf7b2be106967f47cf](https://github.com/magento/magento2/commit/179bedf3de99244b384c97cf7b2be106967f47cf)

The fix will be available with the upcoming 2.2.9 release.

**Comment by keyurk-emipro** [comment]
This backward-incompatibility reproduced again in between 2.3.1 and 2.3.2 but can not found on 2.3-dev branch, Is there anyone know when this resolved from 2.3?
