### ISSUE TITLE
Price currency symbol show not correctly in product form when switch store view

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#22236]
### Preconditions (*)

1. Magento 2.3.1 and 2.3.0
2. Linux Ubuntu Server
3. Chrome browser

### Steps to reproduce (*)

1. Create Secondary store view. Ex: UK Store
2. Catalog Price scope default set to Global
3. Stores > Configuration > General > Currency Setup > Currency Options
set **Allowed Currencies** Euro
set **Base Currency** to  US Dollar
set **Default Display Currency** to US Dollar
4. Switch store view config to UK Store
change Default Display Currency to Euro
5. Go to edit product and change store view
Price field should be show Euro symbol 

### Expected result (*)

1. correct currency symbol, if switch to store view UK currency should show euro instead dollar

### Actual result (*)

1. default currency symbol show
2.

**Comment by mrtuvn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn, here is your [Magento instance](https://i-22236-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22236-2-3-develop.instances.magento-community.engineering/admin](https://i-22236-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment]
Component: CurrencySymbol

**Comment by ghost** [comment]
Hi @mrtuvn thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.3-develop instance
![DeepinScreenshot_select-area_20190409120756](https://user-images.githubusercontent.com/40756439/55787998-33c0ba00-5ac0-11e9-954e-70c49383d191.png)

**Comment by ghost** [comment]
@mrtuvn also` Default Display Currency` used in frontend, instead you need to set base currency .

**Comment by mrtuvn** [comment]
@engcom-backlog-nazar frontend work fine but in admin i can't make symbol correctly follow store view. Default symbol of base currency always used. In my case magento always show us dollar
So this possible not issue but i think should be change symbol right after  magento switched store view
