### ISSUE TITLE
Configurable Product Gallery Images Out of Order when More than 10 images

### ISSUE THREAD

**Issue by sjb9774** [magento/magento2#22249]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Create a configurable product or use one from SampleData
2. Set up an attribute for use with the configurable product as a swatch
![color : Product Attributes : Attributes : Stores : Magento Admin 2019-04-10 10-22-46](https://user-images.githubusercontent.com/6181127/55892247-962ac080-5b7b-11e9-88ef-d358e8cc788a.png)
3. Edit one of the simple products related to that configurable product to have 10 or more images in its gallery (sometimes 11 images are required do to 0-indexed positions. I haven't looked into why they are sometimes 0-indexed and sometimes 1-indexed)
![ Magento Admin 2019-04-09 13-28-34](https://user-images.githubusercontent.com/6181127/55825358-72a83d00-5acb-11e9-8b4f-de8c6d637539.png)
4. View that product through the configurable product detail page
![Chaz Kangeroo Hoodie 2019-04-09 13-30-06](https://user-images.githubusercontent.com/6181127/55825476-b3a05180-5acb-11e9-9311-6fd505629cb3.png)

### Expected result (*)

1. Gallery images will appear in the same order as they are configured in the backend

### Actual result (*)

1.  Gallery images are in a different order than  configured in the backend

## Solution
This is due to the `swatch-renderer.js` file's `_sortImages` method not converting the image position values to integers first, thus sorting strings. Once you have a position of 10 or greater, you get strange orders because values of `"1", "2", "10"` are sorted to `"1", "10", "2"`. Wrapping `swatch-renderer.js` line 700 with `parseInt` fixes the problem.![Configurable Test 2019-04-10 10-20-19](https://user-images.githubusercontent.com/6181127/55892264-a2af1900-5b7b-11e9-987b-095b5ef02391.png)

**Comment by ghost** [comment]
Hi @sjb9774 thank you for you report, i'm not able to reproduce following steps you described, this issue may be related to your cache, please flush cache and try again. thank you for collaboration.
![deepin-screen-recorder_Select area_20190410105033](https://user-images.githubusercontent.com/40756439/55861351-e2c3cb00-5b7e-11e9-89b6-7de39d7f871a.gif)

**Comment by sjb9774** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sjb9774. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sjb9774, here is your [Magento instance](https://i-22249-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22249-2-3-develop.instances.magento-community.engineering/admin](https://i-22249-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sjb9774** [comment]
@magento-engcom-team Thanks for the GIF, I missed that the attribute your product variation is based on needs to be setup as a swatch. There are also some scenarios where the positions are 0-indexed instead of 1-indexed as I had locally so you could need to add 11 images total. I've reproduced this issue again on a 2.3-develop instance.
![color : Product Attributes : Attributes : Stores : Magento Admin 2019-04-10 10-22-46](https://user-images.githubusercontent.com/6181127/55891813-d473b000-5b7a-11e9-9e4a-9408316dbc17.png)

- Backend configuration
![Configurable Test-Blue : Products : Inventory : Catalog : Magento Admin 2019-04-10 10-24-55](https://user-images.githubusercontent.com/6181127/55891980-20265980-5b7b-11e9-9096-fb3940db1bd7.png)
- Frontend display
![Configurable Test 2019-04-10 10-25-51](https://user-images.githubusercontent.com/6181127/55892008-29afc180-5b7b-11e9-8a6a-719bbfd36495.png)
- JS bug demonstration
![Configurable Test 2019-04-10 10-20-19](https://user-images.githubusercontent.com/6181127/55892079-477d2680-5b7b-11e9-98ec-f9ead06b23e6.png)

**Comment by sjb9774** [comment]
I've updated the issue description to indicate the attribute needs to be setup as a swatch.

**Comment by ghost** [comment]
@sjb9774 thanks now clear :+1:

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99138` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sjb9774. Thank you for your report. 
The issue has been fixed in magento/magento2#22287 by @Wirson in 2.3-develop branch
Related commit(s):
 - [700a1535cb6f58224e8e302ad1b4556d8a118e01](https://github.com/magento/magento2/commit/700a1535cb6f58224e8e302ad1b4556d8a118e01)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @sjb9774. Thank you for your report. 
The issue has been fixed in magento/magento2#22288 by @Wirson in 2.2-develop branch
Related commit(s):
 - [f4ab0e6d9280920b6c64b789ec7a155330cfb681](https://github.com/magento/magento2/commit/f4ab0e6d9280920b6c64b789ec7a155330cfb681)

The fix will be available with the upcoming 2.2.9 release.
