### ISSUE TITLE
Programatically created invoices miss items when both simple products and bundled products are mixed in an order

### ISSUE THREAD

**Issue by ryanpalmerweb** [magento/magento2#22246]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)
1. Create an order containing both a bundled product and a simple product
2. Check out with a payment method which does not automatically create an invoice
3. Programatically get an instance of the order, and then run the following code

```
$invoice = $order->prepareInvoice();
$invoice->getOrder()->setIsInProcess(true);
$invoice->register()->pay();
$invoice->save();
```

### Expected result (*)
1. All of the items in the invoice should be ordered

### Actual result (*)

1. Only the bundled product will be invoiced, the simple product will be ignored, causing a partial invoice to be created

### Explanation

1. Payment modules commonly call $order->prepareInvoice()
2. This calls Magento\Sales\Model\Service\InvoiceService->prepareInvoice()
3. New logic introduced by https://github.com/magento/magento2/commit/2fb6b3b81ada22e1a172272a7eb5454a50a71a2d populates the quantity for the bundled products but not the simple products.
4. $qtys is no longer empty causing the following code to fail on the simple products
```
foreach ($order->getAllItems() as $orderItem) {
...
if (empty($qtys)) {
      $qty = $orderItem->getQtyToInvoice();
}
```
5. $this->setInvoiceItemQuantity($item, $qty); now sets a zero quantity, meaning that $invoiceItem->getQty() returns 0 instead of $orderItem->getQtyToInvoice();
6. Instead of registering simple items for the invoice, the following code now acts as if the simple items have been deleted, 
```
foreach ($this->getAllItems() as $item) {
    if ($item->getQty() > 0) {
        $item->register();
    } else {
        $item->isDeleted(true);
    }
}
```

**Comment by ryanpalmerweb** [comment]
Here's an example showing the order overview when it happens - the top product is a bundle and the bottom is a simple

<img width="458" alt="Screen Shot 2019-04-09 at 18 22 19" src="https://user-images.githubusercontent.com/7669058/55821067-81efb080-5af4-11e9-81f2-a4f8345e1664.png">

**Comment by magento-engcom-team** [comment]
Hi @ryanpalmerweb. Thank you for your report. 
The issue has been fixed in magento/magento2#22263 by @ryanpalmerweb in 2.3-develop branch
Related commit(s):
 - [ec2c6ca7df68de9aaccecfb899b102a2a3eaa631](https://github.com/magento/magento2/commit/ec2c6ca7df68de9aaccecfb899b102a2a3eaa631)

The fix will be available with the upcoming 2.3.2 release.

**Comment by dphilipps** [comment]
Thank you - we were experiencing this bug on 2.3.1, I have applied patch and now working again. Cheers.

**Comment by paul-gene** [comment]
I am having a similar issue, but instead of the simple item not being invoiced, if I have multiple simple items, only 1 is invoiced

**Comment by simiMart26** [comment]
This is issue is still happening on magento 2.3.2
