### ISSUE TITLE
Upload several optimized images to media

### ISSUE THREAD

**Issue by Jupagar77** [magento/magento2#22247]
We have 90 optimized images that we need to upload to our production server hosted in Magento Cloud, the problem is that Magento Cloud just provides read-access only.

Is there a proper fast way to do this process without having to upload the images one by one on the admin?

**Comment by ghost** [comment]
Hi @Jupagar77 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
