### ISSUE TITLE
REST API Cart totals calculation error

### ISSUE THREAD

**Issue by jonathan-may** [magento/magento2#22245]
### Preconditions (*)

1. Magento Commerce 2.3.0

### Steps to reproduce (*)

1. Obtain customer token (/rest/V1/integration/customer/token)
2. Create cart (/rest/default/V1/carts/mine)
3. Add item to cart (/rest/default/V1/carts/mine/items)
4. Check cart totals (/rest/default/V1/carts/mine/totals)
 - This returns the correct total amounts
5. Delete item from cart (/rest/default/V1/carts/mine/items/:itemId)
6. Add item to cart again (/rest/default/V1/carts/mine/items)
7. Check cart totals (/rest/default/V1/carts/mine/totals)
- The grand_total for the cart = 0

### Expected result (*)

1. The cart totals API (/rest/default/V1/carts/mine/totals) should return the correct calculated totals.

### Actual result (*)

1. After deleting the item, and adding the item again the cart totals API is returning incorrect total amounts

@magento-engcom-team give me 2.3-develop instance

**Comment by jonathan-may** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may, here is your [Magento instance](https://i-22245-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-22245-2-3-0.instances.magento-community.engineering/admin](https://i-22245-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jonathan-may** [comment]
@magento-engcom-team 

I was able to reproduce this bug using the Magento instance /i-22245-2-3-0.instances.magento-community.engineering.

Here are more detailed steps that I used to reproduce it.

1) Logged in the admin and created a new simple product using TEST as the SKU.
2) Created a new customer account in the frontend.

The following steps were completed using the Postman application.
3) Obtained an authorization token using a POST request, passing the username and password parameters:
https://i-22245-2-3-0.instances.magento-community.engineering/index.php/rest/V1/integration/customer/token

4) Created a new cart using a POST request and the customer's authorization token:
https://i-22245-2-3-0.instances.magento-community.engineering/index.php/rest/default/V1/carts/mine

Response was an integer: 1

5) Added an item to the cart using a POST request, passing the following JSON in the request body:
https://i-22245-2-3-0.instances.magento-community.engineering/index.php/rest/default/V1/carts/mine/items

Request:
{
    "cartItem": {
        "sku": "TEST",
        "qty": 1,
        "quote_id": "1"
    }
}

Response:
{
    "item_id": 1,
    "sku": "TEST",
    "qty": 1,
    "name": "Test Product",
    "price": 13.99,
    "product_type": "simple",
    "quote_id": "1"
}

6) Checked the cart totals using a GET request:
https://i-22245-2-3-0.instances.magento-community.engineering/rest/V1/carts/mine/totals

The JSON response showed the grand_total as 13.99

7) Deleted the item from the cart using a DELETE request, passing the itemId=1 as the parameter

8) Repeated step 5), but the response did not include the price in the JSON response.

Response:
{
    "item_id": 2,
    "sku": "TEST",
    "qty": 1,
    "name": "Test Product",
    "product_type": "simple",
    "quote_id": "1"
}

9) Repeated step 6), the JSON response showed the grand_total as 0

We are using Magento Cloud 2.3.0 in a headless implementation.

I'd like to test this in 2.3.1 also, so...
 @magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may, here is your [Magento instance](https://i-22245-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22245-2-3-1.instances.magento-community.engineering/admin](https://i-22245-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jonathan-may** [comment]
@magento-engcom-team 
Using the steps outline in my previous comment, I was also able to reproduce this bug in the 2.3.1 instance.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22245-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22245-2-3-develop.instances.magento-community.engineering/admin](https://i-22245-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jonathan-may** [comment]
@shikhamis11, Were you able to reproduce this?

**Comment by shikhamis11** [comment]
@jonathan-may sorry for delay in reply .. 
I checked at magento 2.3-develop instance .. I am not able to reproduce this issue. Are you able to reproduce this issue on magento 2.3-develop instance ?

**Comment by jonathan-may** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may, here is your [Magento instance](https://i-22245-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22245-2-3-develop.instances.magento-community.engineering/admin](https://i-22245-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jonathan-may** [comment]
@shikhamis11, I followed the same steps that I outlined to reproduce the issue on 2.3.0 and 2.3.1, but I was not able to reproduce the issue on the 2.3-develop instance.

**Comment by shikhamis11** [comment]
Then in that case it seems this issue in already fixed .. it will be available at Magento 2.3.2 version

**Comment by complexthings** [comment]
Was fixed here for those who come to this issue later:

https://github.com/magento/magento2/commit/01eb7e61c9a3ebadd7d3350b473fd5d0db8d1578

Shout out to @eduard13 for the fix.

**Comment by jonathan-may** [comment]
@complexthings Thank you for updating where the fix was added! I created a patch file for my project, and confirmed it fixed this issue.
