### ISSUE TITLE
Old Price Not visible when one child product has both price higher than configurable product

### ISSUE THREAD

**Issue by arptg** [magento/magento2#22257]
### Preconditions (*)

1. Magento 2.3.0 & 2.3-develop

### Steps to reproduce (*)
1. Create a Configurable product with attributes color swatch and text swatch.
2. Set the price of the configurable product.
3. Create simple products with price same as the configurable product.
4. Change the price of one simple product (except the one with lowest product ID) to be greater than all other products.
5. Change the special price of the same products to be greater than the normal price of all other products but not greater than its normal price.
6. Check Frontend.

### Expected result (*)
On frontend, when swatches are selected, both old price and normal price should be visible.

### Actual result (*)\
Only Normal Price is Shown and not the Old Price

**Comment by arptg** [comment]
> Hi @TheGreatWhites. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @TheGreatWhites do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @TheGreatWhites. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TheGreatWhites, here is your [Magento instance](https://i-22257-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22257-2-3-develop.instances.magento-community.engineering/admin](https://i-22257-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
hi @TheGreatWhites `Change the special price of the same products to be greater than the normal price of all other products ` how can be special price be greater then normal ? you mean i sell you product by special price 20$ but my product is 19$ ?

**Comment by arptg** [comment]
@engcom-backlog-nazar No, just one product which has a price greater than the other configurable options and whose special price is also greater than the normal price of other configurable options.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99125` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by arptg** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TheGreatWhites. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TheGreatWhites, here is your [Magento instance](https://i-22257-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22257-2-3-develop.instances.magento-community.engineering/admin](https://i-22257-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kandy** [comment]
Currently Magento show prices of cheapest child product.  So it works as expected, and if you want other behavior,  please create improvement request

**Comment by venugopal-codilar** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @venugopal-codilar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @venugopal-codilar, here is your [Magento instance](https://i-22257-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22257-2-3-develop.instances.magento-community.engineering/admin](https://i-22257-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by venugopal-codilar** [comment]
1. Advanced Price.

![Screenshot from 2019-08-14 15-33-24](https://user-images.githubusercontent.com/26595808/63013239-6d0f9900-bea9-11e9-8f5d-6760a79d7827.png)

2. Normal Price

![Screenshot from 2019-08-14 15-34-08](https://user-images.githubusercontent.com/26595808/63013241-6da82f80-bea9-11e9-8d0b-e561f14515de.png)

3. PDP

![Screenshot from 2019-08-14 15-34-37](https://user-images.githubusercontent.com/26595808/63013244-6da82f80-bea9-11e9-86d8-3c882af0ab75.png)

**Comment by venugopal-codilar** [comment]
@kandy  I'm able to reproduce this in Magento 2.3.x

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19221` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
