### ISSUE TITLE
Add Category attributes for second time using upgrade

### ISSUE THREAD

**Issue by chaluvadiswamy** [magento/magento2#2225]
Add Category attributes for second time using upgrade #1857

**Comment by chaluvadiswamy** [comment]
get the below error as mentioned one

Notice: Array to string conversion in D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php on line 2876

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
