### ISSUE TITLE
Product Alert after login shows 404 page

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#22266]
### Preconditions (*)

Since 2.3.1 When customer is logged out and click subscribe to price or stock notification (on product page) then after login, gets redirected to the 404 page.

### Steps to reproduce (*)

1. Click subscribe for stock alert on product page
2. Log in
3. See 404 page

### Expected result (*)

1. Customer moved to correct page and subscribed to notification succesfully

### Actual result (*)

1. Customer see 404 page

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22266-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22266-2-2-develop.instances.magento-community.engineering/admin](https://i-22266-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22266-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22266-2-3-develop.instances.magento-community.engineering/admin](https://i-22266-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
strange this issue is coming only on 2.3-develop instance not on 2.2-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99134` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sean-cognella** [comment]
to confirm, we were not able to replicate this on 2.3.0, but are able to replicate on 2.3.1

**Comment by Al3ks73** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Al3ks73. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Al3ks73, here is your [Magento instance](https://i-22266-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22266-2-3-develop.instances.magento-community.engineering/admin](https://i-22266-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rajeshwebkul** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul, here is your [Magento instance](https://i-22266-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22266-2-3-develop.instances.magento-community.engineering/admin](https://i-22266-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ArjenMiedema** [comment]
I also ran into this issue and the reason why this happens is that in https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/ProductAlert/Controller/Add/Stock.php, the interface `use Magento\Framework\App\Action\HttpPostActionInterface;` is implemented. In prior versions, this change didn't exist yet. 

When logging in, the POST action is overwritten by submitting the login form. The redirect done after that has a GET header, which causes the issue. So basically all we need is to change the interface to `HttpGetActionInterface` as there's no need to have this call done as a POST call.

**Comment by magento-engcom-team** [comment]
Hi @ilnytskyi. Thank you for your report. 
The issue has been fixed in magento/magento2#23218 by @ArjenMiedema in 2.3-develop branch
Related commit(s):
 - [361965b1c874f096d0758782ed7539e53460dc19](https://github.com/magento/magento2/commit/361965b1c874f096d0758782ed7539e53460dc19)

The fix will be available with the upcoming 2.3.3 release.
