### ISSUE TITLE
Magento 2.3.1 PHP7.2

### ISSUE THREAD

**Issue by treybake** [magento/magento2#22262]
### Preconditions (*)

1. 2.3.1
2. centos7
3. php7.2.17

### Steps to reproduce (*)

1. $ composer require magento/product-community-edition=2.3.1 

### Expected result (*)

1. installation of Magento

### Actual result (*)

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.17) does not satisfy that requirement.
    - magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.17) does not satisfy that requirement.
    - magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.17) does not satisfy that requirement.
    - Installation request for magento/framework (locked at 101.0.5) -> satisfiable by magento/framework[101.0.5].

As you can see it wants up-to php 7.1.0 however, in the docs (https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html) it says it supports php7.2?

**Comment by ghost** [comment]
HI @treybake thank you for you report, you need to upgrade your version of magento/framework
`magento/product-community-edition 2.3.1 requires magento/framework 102.0.0 `

**Comment by treybake** [comment]
@engcom-backlog-nazar  I just followed upgrade instructions for Magento2.3 ... surely this should be mentioned in the docs?

**Comment by ghost** [comment]
@treybake this is very strange that version of magento framework not updated, from which magento version you try to upgrade ?

**Comment by treybake** [comment]
@engcom-backlog-nazar 2.2.5

**Comment by treybake** [comment]
@engcom-backlog-nazar 

Ok, so managed to get it almost there. I'm not on this step:

`$ composer update`

However, this now generates this error:

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

> Problem 1
> - owebia/magento2-module-advanced-shipping-setting 2.1.1 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.17) does not satisfy that requirement.
> - owebia/magento2-module-advanced-shipping-setting 2.1.1 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.17) does not satisfy that requirement.
> - Installation request for owebia/magento2-module-advanced-shipping-setting 2.1.1 -> satisfiable by owebia/magento2-module-advanced-shipping-setting[2.1.1].

**Comment by treybake** [comment]
now fixed

**Comment by PawanKumarN** [comment]
@treybake  How you fixed the issue i am also facing same issue can you provide solution

**Comment by dipakCrayon** [comment]
> now fixed

How you fixed the issue ?
