### ISSUE TITLE
M2.3.1 Open source - can't delete all selected products

### ISSUE THREAD

**Issue by bloodbool** [magento/magento2#22261]
### Preconditions (*)

1. Magento 2.3.1
2. I noticed an error in the admin panel, when selecting in the list, all products and clicking on the "Delete" button, only those elements that fit on page 1 are deleted.

### Steps to reproduce (*)

1. Catalog -> Products 
2. Select All products 
3. Click Delete in action 
4. Click Ok (Delete all products) 
http://prntscr.com/n9yl33
### Expected result (*)

1. Expected result -  delete all selected products 

### Actual result (*)

1. Actual result - only products thet fit on page 1 are deleted 
before delete all products - > http://prntscr.com/n9ylg1 
after delete all prdoucts - > http://prntscr.com/n9ym00

**Comment by bloodbool** [comment]
> Hi @bloodbool. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [✓]  Summary of the issue
> * [✓]  Information on your environment
> * [✓]  Steps to reproduce
> * [✓]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @bloodbool do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [✓]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @bloodbool. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ghost** [comment]
hi @bloodbool thank you for you report, this issue already confirmed, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/22004

**Comment by magento-engcom-team** [comment]
Hi @bloodbool, here is your [Magento instance](https://i-22261-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22261-2-3-develop.instances.magento-community.engineering/admin](https://i-22261-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
