### ISSUE TITLE
issues about adding configurable products, attribute set, attribute.

### ISSUE THREAD

**Issue by cfcnn** [magento/magento2#2226]
Under Magento2 Merchant Beta5.

1. Adding a configurable products, 
![add configurable product](https://cloud.githubusercontent.com/assets/15027055/10847006/8e971088-7f4e-11e5-8a31-2c7aff0dbb0f.jpg)

2. Select " color" as configuration attribute, 
![select colors](https://cloud.githubusercontent.com/assets/15027055/10847042/d200966e-7f4e-11e5-9df1-d908ea8da2fb.jpg)

3. When save product, "choose affected product template",
![choose affected product template](https://cloud.githubusercontent.com/assets/15027055/10847116/31bad1be-7f4f-11e5-9172-c9e41c6b52a4.jpg)
4. If choose " Add configurable attributes to the new set based on current".  The configurable products and its linked simple products displayed at the backend product list, but the configurable product is disabled, and it doesn't display at frontend. The base image of configurable products might disappear.
![product list backend no frontend](https://cloud.githubusercontent.com/assets/15027055/10847142/666285b0-7f4f-11e5-93b3-7a70b5b49dae.jpg)
If choose " Add configurable attributes to the current set (" Default")", the configurable products and its linked simple products displayed at both backend and frontend.
![default displayed at frontend](https://cloud.githubusercontent.com/assets/15027055/10847383/ff7e6c4a-7f50-11e5-9811-11ff839aecd5.jpg)

5.  The linked simple product of configurable has two pictures at backend, but at frontend there's only one displayed when click the color.
![linked product images backend](https://cloud.githubusercontent.com/assets/15027055/10847485/ab065000-7f51-11e5-9910-b7c2105714b9.jpg)
![fronend only one image](https://cloud.githubusercontent.com/assets/15027055/10847523/facd32c0-7f51-11e5-944d-5c347d70c78c.jpg)

6. There are many color options when adding a products , but no value displayed in ' Attribute Properties" . Even " Add Option", after " Save Attribute", all options disappeared.
![attribute properties](https://cloud.githubusercontent.com/assets/15027055/10847598/56372b2a-7f52-11e5-81ac-65c39cf72059.jpg)

**Comment by tanya-soroka** [comment]
Hello @cfcnn . Thank you for reporting all these issues.  Internal ticket has been created : MAGETWO-44971.

**Comment by cfcnn** [comment]
@tanya-soroka  Just found that : The images of configurable products (under  magento2/pub/media/catalog/product, not cache)  can not be deleted together with configurable products. Simple products and the images can be normally deleted together.

**Comment by katmoon** [comment]
Closing the issue as it has been fixed.
@cfcnn Thanks again for reporting!

**Comment by GreenImp** [comment]
Hi @katmoon could you tell me which release these fixes made it in to? I'm seeing issues where configurable products aren't showing on the frontend - a single product in a category and the category page just shows an empty container, instead of the product. If I remove the product from the category it shows the standard "No products" message.

I'm just wondering if it is this issue. I'm running Magento 2.0.5.

**Comment by katmoon** [comment]
@GreenImp this sounds like a different bug. Please [log a new issue](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for your problem.
