### ISSUE TITLE
Special price displays always the lowest price from both Default and Current Store

### ISSUE THREAD

**Issue by haelbichalex** [magento/magento2#22269]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Create new Website, Store, Store View
2. Set Base Currency and Default Display Currency to 'Euro' in Default Config
3. Set Base Currency and Default Display Currency to 'Polish Zloty' in New Store
4. Setup Currency Rates
5. Set 'Catalog Price Scope' to Website in Configuration -> Catalog -> Catalog -> Price
6. Create new product and set price and special price in Euro for All Store Views
7. Set price and special price in Polish Zloty for New Store

### Expected result (*)

1. Price on Product Detail Page for New Store should display given Polish Zloty value.

### Actual result (*)

1. The price of All Store Views (Euro) is shown, but with Polish Zloty Currency Symbol.

#### Example 1:
Scope: Global (EURO) -> specialprice = 60 €
Scope: Website (Polish Zloty) -> specialprice = 80 zloty
=> Frontend Website Polish: specialprice 60 zloty is shown

#### Example 2:
Scope: Global (EURO) -> specialprice = 90 €
Scope: Website (Polish Zloty) -> specialprice  = 70 zloty
=> Frontend Website Polish: specialprice 70 zloty is shown

The code responsible for the calculation of the special price is here: https://github.com/magento/magento2/blob/ab188bcbed5672a253f4601dbd96354ad0f065f3/app/code/Magento/Catalog/Model/Product/Type/FrontSpecialPrice.php#L77

I fixed this for our environment quickly by replacing this line with:
```php
if (!(empty($specialPrices))) {
    if (array_key_exists($this->_storeManager->getStore()->getId(), $specialPrices)) {
        $specialPrice = $specialPrices[$this->_storeManager->getStore()->getId()];
    }
} else {
    $specialPrice = $product->getSpecialPrice();
}
```

And the method for getting both prices from scope global and current store is here:
https://github.com/magento/magento2/blob/ab188bcbed5672a253f4601dbd96354ad0f065f3/app/code/Magento/Catalog/Model/Product/Type/FrontSpecialPrice.php#L117

I'm not sure where to fix this, that's why I didn't create a PR.
Regards

**Comment by haelbichalex** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @haelbichalex. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @haelbichalex, here is your [Magento instance](https://i-22269-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22269-2-3-develop.instances.magento-community.engineering/admin](https://i-22269-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by haelbichalex** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @haelbichalex. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @haelbichalex, here is your [Magento instance](https://i-22269-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22269-2-3-1.instances.magento-community.engineering/admin](https://i-22269-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by haelbichalex** [comment]
I **could** reproduce this on the 2.3.1 instance, but **not** on the 2.3-develop. What commit is responsible for this?

**Comment by ghost** [comment]
Hi @haelbichalex thank you for you report, i'm also not able to reproduce this on 2.3-develop branch, and this may be fixed by this commit -> https://github.com/magento/magento2/commit/d07e18450b17c3d92e6c88542b52e3c64d4d9cc3

**Comment by haelbichalex** [comment]
@engcom-backlog-nazar Thanks for your answer. This commit though is already included in 2.3.1 and doesn't fix this, as it's reproducible there.

**Comment by nimeshdolphin** [comment]
The issue doesn't seems resolved yet? 

As a workaround in 2.3.1, 
/vendor/magento/module-catalog/Model/Product/Type/FrontSpecialPrice.php
from 
private function isSuitableSpecialPrice($product, array $price): bool

I have replaced line
if (($priceStoreId == Store::DEFAULT_STORE_ID || $product->getStoreId() == $priceStoreId)
with
if (($product->getStoreId() == $priceStoreId)

**Comment by rohit-prjpt** [comment]
The issue doesn't seems resolved yet?

As a workaround in 2.3.1,
/vendor/magento/module-catalog/Model/Product/Type/FrontSpecialPrice.php
from
private function isSuitableSpecialPrice($product, array $price): bool

I have replaced line
if (($priceStoreId == Store::DEFAULT_STORE_ID || $product->getStoreId() == $priceStoreId)
with
if (($product->getStoreId() == $priceStoreId)

**Comment by OvalMedia** [comment]
Same issue was reported [here](https://github.com/magento/magento2/issues/22567).
This is also an issue in 2.2.9.
