### ISSUE TITLE
Payflow Pro does not show errors on checkout

### ISSUE THREAD

**Issue by Lealopez95PSF** [magento/magento2#22277]
### Preconditions (*)

1. Magento C.E. 2.2.8

### Steps to reproduce (*)

1. Have Payflow pro sandbox configured.
2. Add a products to shopping cart with an amount greater than $2001.
3. Fill shipping form and Credit card info with test cards.
4. Place Order.

### Expected result (*)

1. See an error with at least a generic description on the checkout page.

### Actual result (*)

1. Loader stops and nothing happens. No messages are shown on the page.

**Comment by Lealopez95PSF** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Lealopez95PSF. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Lealopez95PSF, here is your [Magento instance](https://i-22277-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22277-2-3-develop.instances.magento-community.engineering/admin](https://i-22277-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Lealopez95PSF** [comment]
@magento-engcom-team I could not reproduce it on Vainilla Magento instance. It showed the error.

**Comment by Lealopez95PSF** [comment]
> Hi @Lealopez95PSF. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * [ ]  Summary of the issue
> 
>     * [ ]  Information on your environment
> 
>     * [ ]  Steps to reproduce
> 
>     * [ ]  Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @Lealopez95PSF do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [ ]  yes
> 
>     * [X ]  no

**Comment by magento-engcom-team** [comment]
Hi @Lealopez95PSF. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Lealopez95PSF, here is your [Magento instance](https://i-22277-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22277-2-3-develop.instances.magento-community.engineering/admin](https://i-22277-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @Lealopez95PSF thank you for you report, i'm not able to reproduce following steps you described, this may be related to your custom modules or wrong configuration.
