### ISSUE TITLE
M2 catalogrule_product__temp Tables

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#22273]
### Preconditions (*)

1. Magento 2.3.1
2. MySQL 5.7 / PHP 7.2

### Steps to reproduce (*)

1. Look at database in phpmyadmin

### Expected result (*)

1. These tables should delete after cart/catalog price rule is disabled/expired/inactive.

### Actual result (*)
1. These tables are not removed after rules are over. Database stays inflated but thankfully doesn't use the rule prices/actions.
![Capture](https://user-images.githubusercontent.com/12517908/55896814-ce82cc80-5b84-11e9-9c29-65fa2d2c18ba.JPG)

**Comment by ghost** [comment]
Hi @heyepic thank you for your report can you please, verify if your user have permission to create or drop table ?

**Comment by mbnsc** [comment]
Yes, I do. I deleted all of the cart/catalog rules in M2 admin and those tables still exist.

![Capture](https://user-images.githubusercontent.com/47368163/55963933-4c081480-5c39-11e9-9a7c-720eb94243a4.PNG)

Are those tables safe to drop?

**Comment by ghost** [comment]
@heyepic this tables may be automatically drops after reindex.

**Comment by mbnsc** [comment]
I've re-indexed and they do not remove - so it is safe to drop via phpmyadmin?

**Comment by ghost** [comment]
@heyepic yes, but be careful to not drop other tables.

**Comment by mbnsc** [comment]
Thanks for the support. Keep rocking it guys.

**Comment by ghost** [comment]
@heyepic i'm closing this as i'm not able to reproduce, and seems like thish may be related to configuration with your  environment, feel free to reopen, with additional information if issue still exists.

**Comment by php4umagento** [comment]
This is still happening - we have 10k tables created

**Comment by quisse** [comment]
@php4umagento This occurs when the Catalog Rule indexer throws an exception. The temporary table doesn't get cleaned up.

**Comment by springerin** [comment]
Same issue on magento 2.3.6 instances.
