### ISSUE TITLE
Replace deprecated jQuery-Storage-API with js-storage

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#22271]
### Description (*)

Replace deprecated jQuery-Storage-API with js-storage;

> IMPORTANT
> This plugin is no longer maintained.
> 
> A new one, without dependencies with jQuery, is available : https://github.com/julien-maurel/js-storage
> 
> APIs are same, but are accessibles with global variable "Storages" instead "$".
> 
> Thanks!

### Expected behavior (*)

An uptodate and maintained library to set cookies

### Benefits

Uptodate code

**Comment by arnoudhgz** [comment]
@peterjaap @magento-engcom-team  related to this, `jquery-cookie` [is also deprecated](https://github.com/carhartl/jquery-cookie) and should be replaced by [js-cookie](https://github.com/js-cookie/js-cookie)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19273` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @peterjaap. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23970` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by aligent-lturner** [comment]
@magento give me 2.4-develop instance
