### ISSUE TITLE
Using a Wildcard in front of integer on product query through REST API turns into html entity

### ISSUE THREAD

**Issue by willboudle** [magento/magento2#22279]
When searching for a product through the api and using conditional statements. If you use LIKE and % at the beginning of a sku search, when the sku is integers, the percent sign transforms into a html entity. 

https://api.site.com/rest/V1/products?searchCriteria[filterGroups][0][filters][0][field]=sku&searchCriteria[filterGroups][0][filters][0][value]=%130748%&searchCriteria[filterGroups][0][filters][0][conditionType]=like

![image](https://user-images.githubusercontent.com/936237/55908236-e1a69400-5ba6-11e9-924f-3cfb0ba16586.png)

**Comment by ghost** [comment]
Hi @willboudle 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
