### ISSUE TITLE
why  $quote->getBillingAddress()->validate() throw exception  when i use quoteManagement->submit($this->_quote) 

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#2227]
thank you!

**Comment by LifeAsBook** [comment]
This problem has troubled me for a long time！I hope someone can help me, be grateful

**Comment by daim2k5** [comment]
The github issue tracker is intended for technical issues only.
Please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) for technical questions. In your case probably the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
