### ISSUE TITLE
Can't disable store views in admin panel.

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#22278]
Ok, I don't know if it's a bug or a feature :-) Basically we have a multistore setup, a lot of extensions and we would like to disable few store_views in admin panel so they are not usable in configuration scopes in backend.

### Preconditions (*)

1. Magento EE 2.2.x
2. Multistore setup: 5 website, each 1 store, each store 1 store view

### Steps to reproduce (*)

1. Simply create multistore setup

### Expected result (*)

1. You should be able to disable store view / website if that is not a default store view / website

### Actual result (*)

1. Set Store 1 as default store
2. Go to admin panel, go to 2nd or another store view 
3. "Status: Enabled" is grayed out, and it cannot be disabled. 

Like I've explained before, I don't know if it's a bug or a feature.

**Comment by ghost** [comment]
HI @qsolutions-pl thank you for your report, to be able to disable store view, be sure that you have 2 store view per store.
![DeepinScreenshot_select-area_20190411110619](https://user-images.githubusercontent.com/40756439/55940984-ebcd9e80-5c49-11e9-98b8-bc73d4b08ec3.png)

**Comment by nadeefit6** [comment]
If you have more than 2 store-views per website,enable/disable of the non-default store-view is possible.
If you have only one store-view, it becomes the default one,so it cannot be enabled/disabled.
Its the default behavior.

**Comment by ghost** [comment]
@qsolutions-pl It will be processed faster if you move this to https://github.com/magento/community-features
