### ISSUE TITLE
Magento 2.2.7 Order comments not saved

### ISSUE THREAD

**Issue by Siyadev9** [magento/magento2#22286]
### Preconditions (*)

1. Magento 2.2.7
2. Upgraded from magento 1.9.4

### Steps to reproduce (*)

1. Place an order and view order on the admin panel.
2. Add a comment to the order and click submit button.

### Expected result (*)

1. [Screenshots, logs or description]
2. What I expected was the comment to be saved and visible in the comments tab, and at the 
    bottom of the order

### Actual result (*)

1. [Screenshots, logs or description]
2. Comments not showing and not save in sales_order_status_history table in the database either.

**Comment by ghost** [comment]
Hi @Siyadev9 , problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.
