### ISSUE TITLE
User menu sub items not visible for access n browser

### ISSUE THREAD

**Issue by shu1313** [magento/magento2#2229]
When we open the menu bar in Google chrome  / opera , we cant see Index and compile
We cant move the menu up or down to access other buttons.

attached screenshot below 
![mag2 menu move ssue](https://cloud.githubusercontent.com/assets/12825344/10863495/92afd11c-7ff5-11e5-959e-dfcffeb7fd2b.JPG)

**Comment by MomotenkoNatalia** [comment]
Hi @shu1313 , thank you for report.
Could you please specify your screen resolution.

**Comment by shu1313** [comment]
Hi, 
my screen resolution is 1366 X 768I am not sure what is the problem but sometimes it is working and sometimes it is not

 Date: Tue, 3 Nov 2015 06:07:22 -0800

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by MomotenkoNatalia** [comment]
@shu1313 We will do fixes under MAGETWO-49758.

**Comment by magento-engcom-team** [comment]
@shu1313, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
