### ISSUE TITLE
Cannot export shipper hq dimensional shipping 

### ISSUE THREAD

**Issue by github-Rach** [magento/magento2#22292]
### Preconditions (*)

1. mag 2.2.7
2. cannot export Catalog > Product > Dimensional Shipping > Product Dimensions

### Steps to reproduce (*)

1. Export >  Catalog > Product > Dimensional Shipping > Product Dimensions 
2. Dimension Length and Dimension Height and Dimension Width
![dim-shipping-mag](https://user-images.githubusercontent.com/48331509/55995354-2135b480-5c69-11e9-8f6b-07c7f4884812.jpg)

### Expected result (*)

1. [Screenshots, logs or description]
2. I would like to export this information.

### Actual result (*)

1. No export

**Comment by hostep** [comment]
@github-Rach: this seems to be a problem you should discuss with the people of https://shipperhq.com/.
This isn't a core Magento problem. Closing ticket.
