### ISSUE TITLE
Localisation and Internationalisation request

### ISSUE THREAD

**Issue by mikebranderhorst** [magento/magento2#223]
Apple, Dell, Microsoft all do the same as Magento (or the other way around ;-). But did you ever experience how hard it is to order a product living in a country if you do not speak nor read the foreign language? Apple for example, if you live in the Netherlands but cannot read Dutch how do you order? It must go through http://store.apple.com/nl which is Dutch. If you want to select English it is not possible to deliver to an address in The Netherlands. Now my feature request is to add an extra scope, named Language scope. If you add for example a product, translate it in multiple languages regardless of Store View scope. The Store View scope has a language and just picks the right translated product but a customer can stay on the Netherlands store but order everything in English or German or whatever.

Read my comments in this blog post.

http://inchoo.net/online-marketing/translation-is-not-localization-multi-country-e-commerce-tips/

Summary:

We have a:

* Store A (.nl) Netherlands (Dutch is main language, German and English)
* Store B (.de) Germany (German is main language, Dutch and English)
* Store C (.eu) Europe (English is main language, Dutch and German)

Future: .be, .it, .se etc.

All shops share the same products, different prices, different static content and ! 3 languages. Currently it is difficult to get a internationalisation scope in a localized store.

A German store != the store of Germany. The store in the Netherlands could also be translated in German but is not the same as the German text on the store of Germany.

How I see this in practice:

Product:
When you add a product you have a Global scope product with multiple translations, not only text but also metadata, url, title pictures etc. Then when you add a product to a store view it gets automatically the language of that store view.

Static content:
This could be Global text in multiple languages or Website scope text in multiple languages. For example a Contact of Return policy page could be translated in say three languages but is for Store A, B and C not the same. But other pages could be the same in all Store A, B, C.

Configuration:

(.nl)
Store A - Netherlands - Dutch (main)
Store A - Netherlands - German
Store A - Netherlands - English

(.de)
Store B - Germany - German (main)
Store B - Germany - Dutch
Store B - Germany - English

(.eu)
Store C - Europe - English (main)
Store C - Europe - Dutch
Store C - Europe - German

Now, when I add a product, I should choose to make it global or assign it only to a country (website scope). I translate the product in multiple languages with English as fallback. When a customer visits the Store A but does not speaks Dutch and selects English he/she is still on Store A. Why not Store C? Store C has different content (maybe also theme) and different regulations (tax, law, delivery regulations, etc.)

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-32658

**Comment by tkacheva** [comment]
@antboiko look into it please MAGETWO-32658

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Localisation-and-Internationalisation-request/idi-p/46271).
