### ISSUE TITLE
Not able to create partial invoice from Magento2 REST API for Pay on account [Credit limit] payment method orders

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#22300]
**Preconditions**

1. Magento EE 2.2.6 B2B
2. PHP 7.0.14

**Steps to reproduce**

1. Create order in Magento either with company user or company admin with Pay on account(Company Credit) payment method with multiple items with different quantities or single item with more than one quantity
2. Try to create invoice for the order for the partial quantity from Magento REST API using service POST /V1/order/{orderId}/invoice

**Expected result**

1. Getting error like **_“Invoice Document Validation Error(s): An invoice for partial quantities cannot be issued for this order. To continue, change the specified quantity to the full quantity.”_**

**Actual result**

1. Invoice should be created with the partial quantity

**Note**

1. We are able to create partial from Magento2 admin order view page

**Comment by i95devdivya** [comment]
We observed the following plug-in from B2B Company Credit module causing the issue

"Magento\CompanyCredit\Plugin\Sales\Model\Order\InvoiceQuantityValidatorPlugin"

If we comment above plug-in from di.xml then we are able to create partial invoice from REST API.

**Comment by ghost** [comment]
Hi @i95devdivya thank you for you report, this issue has already fixed in 2.3-develop branch and 2.2-develop branch and available on 2.2.8 release and 2.3.1 release.

**Comment by i95devdivya** [comment]
@engcom-backlog-nazar 
Is there any patch is available for EE 2.2.6?

**Comment by i95devdivya** [comment]
We are facing the same issue in Magento Commerce B2B 2.3.5.

The same plug-in which I have mentioned earlier from B2B Company Credit module causing the issue

"Magento\CompanyCredit\Plugin\Sales\Model\Order\InvoiceQuantityValidatorPlugin"

If we comment above plug-in from di.xml then we are able to create partial invoice from REST API.
