### ISSUE TITLE
Pointer in catalog view

### ISSUE THREAD

**Issue by elfstone** [magento/magento2#2230]
In admin catalog the cursor should change to pointer (hand) when hovering a product. Now only changes to pointer at the "Edit" function at the end of the row.

**Comment by MomotenkoNatalia** [comment]
Hi @elfstone!
You are completely right! We will fix this. Internal ticket MAGETWO-44936.
Thanks for reporting this issue!

**Comment by MomotenkoNatalia** [comment]
@elfstone Internal ticket MAGETWO-44936 is closed and delivered to mainline. Please, let us know if you still have an issue.
