### ISSUE TITLE
Flashing glitch

### ISSUE THREAD

**Issue by elfstone** [magento/magento2#2231]
When in Dashboard (bestsellers, most viewed products etc.) there is a little flashing point present when there are no records present.
![flashing](https://cloud.githubusercontent.com/assets/11913551/10866027/7c0afea8-801f-11e5-894e-494beb2ffb25.jpg)

**Comment by zanilee** [comment]
Hi, @elfstone!

This issue was fixed in the internal ticket MAGETWO-43337 and delivered recently.
Please update.

**Comment by daim2k5** [comment]
@elfstone can you confirm the fix?
