### ISSUE TITLE
Colossal security issue in magento 1 and magento 2

### ISSUE THREAD

**Issue by jainmca4444** [magento/magento2#22315]
Dear Magento Team,
I have encountered  a big issue  with magento query adapter. It is a perception that we can run and read query using  this  **$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');**  and we can write or update query on  table using **$writeConnection = Mage::getSingleton('core/resource')->getConnection('core_write');**  . but  on the contarary, we can write anything, drop table,  truncate table and drop databse using read mysql adapter.

**Example : Magento 2**

```
<?php
use Magento\Framework\App\Bootstrap;
 
require __DIR__ . '/app/bootstrap.php';
 
$params = $_SERVER;
 
$bootstrap = Bootstrap::create(BP, $params);
 
$obj = $bootstrap->getObjectManager();
 
$resource = $obj->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();

$Get_Qry="delete from TableName";


try
{
	$rows=$connection->fetchAll($Get_Qry);
	$count=count($rows);
	if($count>0)
	{
				
foreach($rows as $row)
				{ 
					print_r($row);
					echo "<br><hr>";
				}
		echo "Success!";
	}
	else
	{
		echo "No record found!";
	}
}
catch(Exception $e)
{

   echo "<hr><p>{$e->getmessage()}</p>";
}
?>
```

**Example Magento 1:**
```
<?php

require_once 'app/Mage.php';
Mage::app('default');
$readConnection = Mage::getSingleton('core/resource')->getConnection('core_read');


$Get_Qry="delete from TableName";

try
{
	$rows=$readConnection->fetchAll($Get_Qry);
	$count=count($rows);
	if($count>0)
	{
				
		echo "Success!";
	}
	else
	{
		echo "No record found!";
	}
}
catch(Exception $e)
{
   // handle error 
   //die($e->getmessage());
   echo "<hr><p>{$e->getmessage()}</p>";
}

?>
```

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by shikhamis11** [comment]
@jainmca4444 Please correct format of issue 
follow issue reporting guideline and edit the description
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by siliconrockstar** [comment]
The M2 code operates as expected. Object Manager gets a 'Magento\Framework\App\ResourceConnection'; that object's getConnection() returns a \Magento\Framework\DB\Adapter\AdapterInterface, and that Adapter interface defines methods to truncate and drop tables, so it's no surprise that you can use the Adapter to run arbitrary destructive SQL.

I don't have a copy of M1 handy to test the M1 example code, but I'm not sure if this whole thing is a bug or just a preconception on the part of the OP.

**Comment by jainmca4444** [comment]
Hi siliconrockstar,

Thanks for your  Quick Reply
It is  not the matter that how i am using FetchAll() method in our code.  it's behaviour  should be only fetching the data from table.

**Comment by orlangur** [comment]
Hi @jainmca4444, thanks for your report, please check https://github.com/magento/magento2#reporting-security-issues on how to report security issues.
