### ISSUE TITLE
magento2 Customer unable to get token in customer/token rest api

### ISSUE THREAD

**Issue by uthegenius** [magento/magento2#22312]
**Preconditions**
Magento 2.3 

**Steps to reproduce**
Customer is signup through rest api in magento 2.3 successfully. after signup, I am unable to get customer's token through customer/token rest api. Api returns following error:

 **Actual result**
![issue1](https://user-images.githubusercontent.com/6263757/56051857-617c5c00-5d69-11e9-8f8b-bd9c2278bb1f.PNG)

Although customer is successfully login through web but unable to get validate in rest api.

**Expected result**
token must be generated

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99167`, `MAGETWO-99168` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-22312-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22312-2-3-develop.instances.magento-community.engineering/admin](https://i-22312-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Shubham0492** [comment]
Reproduced on 2.3.x
chrome-extension://fdpohaocaechififmbbbbbknoalclacl/capture.html?id=9&url=https%3A%2F%2Fi-22312-2-3-develop.instances.magento-community.engineering%2Fswagger%23%2FintegrationCustomerTokenServiceV1%2FintegrationCustomerTokenServiceV1CreateCustomerAccessTokenPost

**Comment by ronak2ram** [comment]
Hie @uthegenius,
I think there is no issue with the API. Can you please remove `all` store code form URL.
so URL would be:  /rest/V1/integration/customer/token.
Please refer this for more information about store code `all` in URL: https://devdocs.magento.com/guides/v2.3/get-started/gs-web-api-request.html#endpoints

**Comment by shikhamis11** [comment]
@ronak2ram 
Yes it will work if `all` is removed from the url .. but if anyone using Magento swagger it must be correct there

**Comment by uthegenius** [comment]
Swagger also returns the same error.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ronak2ram** [comment]
You correct @shikhamis11 
I think, have an issue with swagger.

**Comment by Shubham0492** [comment]
@ronak2ram  & @shikhamis11 
There is no issue in Swagger. This is related createCustomerAccessToken API. It should one more parameter is website_id because if you check Magento configuration -> Customer Configuration -> Share Customer Accounts is set per website . If you will get token after set is global then it will work. In this case website_id pass 0 and there is no customer exist for this website.

**Comment by uthegenius** [comment]
@Shubham-Webkul thanks for pointing out the issue. There is only one parameter passed to get customer. I just passed the website_id to that method and API returns the access_token. I think there should be default website_id passed to it to get the customer which is not happening in this version.

**Comment by adityarshah** [comment]
- For customer token if  pass **all** in the API url then you need to pass website_id 0


- For customer token if you want it store wise then you need to pass **store_code** in the API url


   ` POST <host>/rest/<store_code>/V1/integration/customer/token
`
- But if you haven't configure any stores then pass **default**


    `POST <host>/rest/default/V1/integration/customer/token`


**And to fetch all store data using API** 

> storeStoreRepositoryV1

___

**Group repository interface**


    http://magento.host/index.php/rest/V1/store/storeGroups

 - `method : GET`
 - `Authorization : Bearer <admin token>`

This will return `website_id`, `root_category_id`, `default_store_id`, `name`, `code`
___

**Comment by amitvishvakarma** [comment]
Not the valid issue,
If you are trying to check in swagger so please change the base url first..
To view the Swagger documentation for a specific store view, use this URL:
http://<magento_host>/swagger?store=<store_code>
So in your case the url will be like this
http://<magento_host>/swagger?store=default

Now you can try to customer/token rest api, it will generate token successfully

**Comment by rksain** [comment]
magneto 2.3.3 not returning customer token
I am unable to get customer's token through customer/token rest api. Api returns following error:
"The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again [later."]
![Screenshot from 2020-01-08 16-32-23](https://user-images.githubusercontent.com/59612953/71973539-34e06c80-3235-11ea-93cc-436a07ecf092.png)

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-22312-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-22312-2-4-develop.instances.magento-community.engineering/admin_a251](https://i-22312-2-4-develop.instances.magento-community.engineering/admin_a251)
Login: `bf9aeace` Password: `e1ffe43bff75`
Instance will be terminated in up to 3 hours.
