### ISSUE TITLE
LESS import directive doesn't work with compact SCD strategy

### ISSUE THREAD

**Issue by robbie-thompson** [magento/magento2#22311]
In email-extend.less, the compiled email-fonts.css is imported using the base URL. However, this path is incorrect when using the compact SCD strategy, as the base URL includes the store view path, and the compact strategy puts email-fonts.css into the /default folder.

### Preconditions (*)
1. 2.2.6

### Steps to reproduce (*)
1. Deploy SCD with compact strategy: bin/magento setup:static-content:deploy -s compact
2. Create an account to receive an email
3. Locate <style> tag in email content's head, and find @import tag
4. Import should be failing, as the URL includes the store view path (not /default)

### Expected result (*)
1. The URL contains the correct locale path depending on the strategy (/default for compact)
2. The file is imported

### Actual result (*)
1. The URL contains the store view path, even though the asset is in the /default folder
2. The file can't be imported, @import rule will then be visible in style tag instead of being replaced with files contents

**Comment by sivaschenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [Magento instance](https://i-22311-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22311-2-3-develop.instances.magento-community.engineering/admin](https://i-22311-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99360` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by robbie-thompson** [comment]
I'm able to reproduce on 2.4.1 and the compact SCD strategy is still recommended, so I believe it's still relevant.

**Comment by robbie-thompson** [comment]
Still relevant
