### ISSUE TITLE
Unable to know magento version installed

### ISSUE THREAD

**Issue by myselfgaurav** [magento/magento2#22326]
i have installed magento 2.3 using composer , now in admin i can not see magento version it show as below :

**Magento ver. No version set (parsed as 1.0.0)**

**Comment by shikhamis11** [comment]
@myselfgaurav  Please correct format of issue
follow issue reporting guideline and edit the description
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ghost** [comment]
Hi @myselfgaurav 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
