### ISSUE TITLE
"Select all" to update all products will only update current products in grid.

### ISSUE THREAD

**Issue by onepack** [magento/magento2#22327]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2

### Steps to reproduce (*)

1. Go to backend of Magento2
2. Go to Catalog -> Products
3. Check if you have 20 items active on the grid per page. 
4. Select "Select all" dropdown value (next to products id) and read the result like "110 selected"
5. Choose "Update attributes" from the actions dropdown.
6. Change something and save.

### Expected result (*)

1. I expect all products like "110" of the selection will be updated.
2. I expect he message to say, 110 products are updated.

### Actual result (*)

1. Magento will tell me 20 items were updated (number of items in the grid on one page)
2. Checking the products on the first grid page will show me products with the attribute value changed.
3. The next pages will show products without this change so the message that 20 items were changed was correct. However it should have been the whole collection of 110 products.

**Comment by onepack** [comment]
I have this on the development and production environment of magento2.3 + PHP 7.2

**Comment by konarshankar07** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07, here is your [Magento instance](https://i-22327-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22327-2-3-develop.instances.magento-community.engineering/admin](https://i-22327-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by konarshankar07** [comment]
@onepack  @magento-engcom-team 
I'm able to reproduce this issue in the vanilla instance. Here Screenshot of my current testing
![Screenshot_3](https://user-images.githubusercontent.com/39480008/56089585-d0b19780-5eb2-11e9-913e-11b71465c3f0.png)

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-backlog[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by Nazar65** [comment]
@dmytro-ch  duplicate to this https://github.com/magento/magento2/issues/22004

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99205` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
@Nazar65, thank you for the update!
I'm closing the current issue as a duplicate.
