### ISSUE TITLE
Virtual Product for Bookings and Reservation

### ISSUE THREAD

**Issue by sonumartolia** [magento/magento2#2232]
Can Magento have one more out of the box feature for creating a virtual product for booking, reservation or rentals service ?

**Comment by kandy** [comment]
What's the difference between exists "Virtual Product" and "Virtual Product for Bookings and Reservation"?

**Comment by sonumartolia** [comment]
Virtual Product for Bookings or Reservation has Duration selector for product or services for specific period of time and then merchant can charge the customer accordingly. On the other hand simple virtual doesn't have Duration selector and Price Logic.

**Comment by gplanchat** [comment]
Hello,

Is there any info about this feature implementation? either if it will be in CE or EE and current status?

Thanks in advance

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Virtual-Product-for-Bookings-and-Reservation/idi-p/44864).
