### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'intl' (tried: ext\intl (The specified module could not be found.), ext\php_intl.dll (The specified module could not be found.))

### ISSUE THREAD

**Issue by HardikWebTechDevloper** [magento/magento2#22331]
I'm getting an error of 

> PHP Startup: Unable to load dynamic library 'intl' (tried: ext\intl (The specified module could not be found.), ext\php_intl.dll (The specified module could not be found.))

While I'm installing Magento 2.3 in localhost. I've tried to installed using Xampp.

![image](https://user-images.githubusercontent.com/16513408/56095843-5575d300-5efe-11e9-9267-697a4cbd0541.png)

**Comment by shikhamis11** [comment]
@HardikWebTechDevloper this is not bug. 
follow magento 2 systeem requirements before magento 2 installation 
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by HardikWebTechDevloper** [comment]
> @HardikWebTechDevloper this is not bug.
> follow magento 2 systeem requirements before magento 2 installation
> https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

I have checked everything but I can't resolve it. Could you please help me to install Magento 2.3?

**Comment by shikhamis11** [comment]
@HardikWebTechDevloper make sure you have installed all required php extension 
you can take help from here 
https://magento.stackexchange.com/questions/123246/magento-2-php-extensions-missing

**Comment by HardikWebTechDevloper** [comment]
Yes I did.
