### ISSUE TITLE
Order Status always 'Closed' after creating invoice and shipment

### ISSUE THREAD

**Issue by markjuliusuy** [magento/magento2#22337]
We created a module to enable canCapture and canCapturePartial on bank transfer so that we can select if it's pending or paid
### Preconditions (*)

1. Magento 2.2.8 or Magento 2.3.1

### Steps to reproduce (*)

I. Scenario
1. Created an order on admin
2. Created a pending invoice using no capture option and checked create shipment

### Expected result (*)

I. Scenario
1. The order status should be processing since it's not yet paid and complete when invoice is captured

### Actual result (*)

1. The order status is closed

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-22337-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22337-2-3-develop.instances.magento-community.engineering/admin](https://i-22337-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @markjuliusuy  It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by xpoback** [comment]
For what reason has this been closed? It's an existing bug.

**Comment by gkueny** [comment]
Can we re-open this issue? We have a similar issue but  https://github.com/magento/magento2/issues/22337 doesn't fix it (we do not have order with only virtual products)

**Comment by willryanuk** [comment]
We also have the same issue. Our order contains normal products (not virtual products).

When we create an invoice programatically, the order is shipped and invoiced, and the status is changed to CLOSED when it should be COMPLETE.

**Comment by seyuf** [comment]
Hi @ghost can you please reopen this? For further investigation? We just encountered the same issue after upgrade to 2.3.6.
