### ISSUE TITLE
Error "extend ' .no-link a' has no matches" when compiling email-inline css using an alternative less compiler

### ISSUE THREAD

**Issue by hostep** [magento/magento2#22330]
### Preconditions (*)
1. Magento 2.3.1
2. PHP 7.1.27
3. Nodejs 8.15.1

### Steps to reproduce (*)
1. Setting up vanilla Magento installation using composer
2. Run `npm install less@2.7.3` to install an alternative less compiler then what Magento ships with
3. Run `bin/magento setup:static-content:deploy -f -t Magento/luma en_US` (this is just to generate the necessary files in `var/view_preprocessed`)
4. Run `node_modules/.bin/lessc --no-color var/view_preprocessed/pub/static/frontend/Magento/luma/en_US/css/email-inline.less | head`

### Expected result (*)
1. No errors during less compilation

### Actual result (*)
1. First line of output says: `extend ' .no-link a' has no matches`

### Discussion
This was done using the Magento/luma theme, but can be reproduced using the Magento/blank theme as well.

I can get rid of the less compilation problem by removing the following lines:
- Magento/luma: https://github.com/magento/magento2/blob/2.3.1/app/design/frontend/Magento/luma/Magento_Sales/web/css/source/_email.less#L80
- Magento/blank: https://github.com/magento/magento2/blob/2.3.1/app/design/frontend/Magento/blank/Magento_Sales/web/css/source/_email.less#L72

But not sure if removing these lines is good, I think this has something to do with the difference between inline email styles and non-inline email styles. But I don't know much about the logic of how that works.
The `.no-link a` mixin (?) is defined over here btw: https://github.com/magento/magento2/blob/2.3.1/app/design/frontend/Magento/blank/web/css/source/_email-base.less#L136-L140

**Comment by hostep** [comment]
Alright, if I understand it correctly, the mixin `.no-link a` should get outputted for the selector `.address-details a` in the generated `email.css` file, but not in the `email-inline.css` file.

According to the comments in the css files around those lines ("Remove address and phone number link color on iOS"), it is to remove the link styling from links in the address details block in sales emails, like for example on the phone number.

Here's an example with an order confirmation email:
<img width="1682" alt="Screenshot 2019-04-14 at 18 23 59" src="https://user-images.githubusercontent.com/85479/56096035-2736ca00-5ee3-11e9-8078-5b95137bdc2d.png">

This already happen and it is currently correct in Magento 2.3.1, so this isn't a bug which is visible, but we can still easily fix the less compilation error itself without affecting the end result, by wrapping the offending lines in the `.email-non-inline()` mixin. This seems to result in the exact same output but then without the less compilation error.

I'll create a PR with a fix for this shortly.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99256` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#22332 by @hostep in 2.3-develop branch
Related commit(s):
 - [12c848c79237bb4e6237e4ac4dd5d989ec9bbc53](https://github.com/magento/magento2/commit/12c848c79237bb4e6237e4ac4dd5d989ec9bbc53)

The fix will be available with the upcoming 2.3.2 release.
