### ISSUE TITLE
Make Company Required Field In Admin- Back-Port 2.1.x

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#22347]
### Description (*)

In Magento 2.2.x you can easily make Company a required field for customers in both the checkout and creating an account pages - Settings>Configuration>Customers>Customer Configuration>Name and Address Options (see magento.2.2.jpg screenshot).
![magento 2 2](https://user-images.githubusercontent.com/19981272/56141041-0bc2d200-5f6a-11e9-8d88-737bc702808f.jpg)

But in Magento 2.1.x, there is no option for this (see magenta 2.1.jpg screenshot). **Can this feature be back-ported to 2.1.x?** 
![magento 2 1](https://user-images.githubusercontent.com/19981272/56141049-0feeef80-5f6a-11e9-9ea3-3e9ae465ab6d.jpg)

### Expected behavior (*)

Admin users would easily be able to make company a required field across the website through Settings>Configuration>Customers>Customer Configuration>Name and Address Options

### Benefits

Would allow more B2B focused stores the ability to make the company field a required one on 2.1.x. Would give a consistent user experience across the website as well.

### Additional information

I think this would benefit users on 2.1 greatly. We are not ready to move to 2.2.x yet, but this would make our store more user friendly in the meantime.

**Comment by orlangur** [comment]
@pioneerathletics unfortunately only contributions to `2.2-develop` and `2.3-develop` are acceptable currently.

**Comment by ghost** [comment]
@orlangur super fast response :)
