### ISSUE TITLE
Nonce Is not being populated in API call to Braintree via Magento Default Checkout

### ISSUE THREAD

**Issue by ebofi** [magento/magento2#22348]
Hi, 

**Summary of the issue --**

We are using Magento 2.2.7 , we use Magento default checkout for our site whenever we enter card details on Braintree Checkout page, the 3 d secure will popup asking OTP received in our phone. We enter it and the popup close and shows .. Something Went Wrong. Upon checking the log we found that Braintree is responding back with a message 

      'message' => 'Cannot determine payment method.',

Modules we use  are listed below : 

List of enabled modules:
Magento_Store
Magento_AdminNotification
Magento_Directory
Magento_Eav
Boolfly_PaymentFee
Magento_Customer
Magento_Theme
FishPig_WordPress
Magento_Indexer
Magento_Cms
Magento_Catalog
Magento_Payment
Mageants_FrontOrderComment
Magefan_Blog
Magento_Quote
Magento_Rule
Magento_AdvancedPricingImportExport
Magento_Config
Magento_Backend
Magento_SalesSequence
Magento_CatalogRule
Magento_Backup
Magento_Sales
Magento_Msrp
Magento_BundleImportExport
Magento_CacheInvalidate
Magento_CatalogInventory
Magento_Checkout
Magento_Security
Magento_CatalogImportExport
Amazon_Core
Magento_Cron
Magento_ConfigurableProduct
Magento_Search
Magento_CatalogUrlRewrite
Magento_Widget
Magento_Vault
Magento_CheckoutAgreements
Magento_Paypal
Magento_CmsUrlRewrite
Magento_User
Magento_ConfigurableImportExport
Magento_Bundle
Magento_ConfigurableProductSales
Magento_Contact
Magento_Cookie
Magento_Email
Magento_CurrencySymbol
Magento_Downloadable
Magento_Integration
Magento_CustomerImportExport
Magento_DataMigrationTool
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_GroupedProduct
Magento_ImportExport
Klarna_Core
Magento_Newsletter
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_GroupedImportExport
Bss_AjaxCart
Magento_DownloadableImportExport
Magento_SalesRule
Magento_InstantPurchase
Magento_Analytics
Magento_LayeredNavigation
Magento_Marketplace
Magento_MediaStorage
Magento_CatalogRuleConfigurable
Magento_Multishipping
Magento_NewRelicReporting
Magento_ProductAlert
Magento_OfflinePayments
Magento_OfflineShipping
Magento_PageCache
Magenest_RewardPoints
Magento_Braintree
Magento_Persistent
Magento_Reports
Magento_ProductVideo
Amazon_Login
Magento_QuoteAnalytics
Magento_ReleaseNotification
Magento_Review
Magento_RequireJs
Magento_SendFriend
Magento_ReviewAnalytics
Magento_Robots
Magento_Rss
Magento_Authorizenet
Klarna_Ordermanagement
Magento_SalesAnalytics
Magento_SalesInventory
MageXtensions_TntItalia
Magento_Captcha
Magento_UrlRewrite
Magento_CatalogSearch
Magento_CustomerAnalytics
Magento_Shipping
Magento_Wishlist
Magento_Signifyd
Magento_Sitemap
Amazon_Payment
Magento_Webapi
Magento_SwaggerWebapi
Magento_Swatches
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxImportExport
Magento_Authorization
Magento_Translation
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_CatalogAnalytics
Magento_Usps
Magento_Variable
Klarna_Kp
Magento_Version
Magento_Swagger
Magento_WebapiSecurity
Magento_Weee
Magento_CatalogWidget
Dotdigitalgroup_Email
Magento_WishlistAnalytics
Mageplaza_Core
Mageplaza_GiftCard
Mageplaza_LayeredNavigation
Mageplaza_Smtp
Mageside_SaleCategory
Smartwave_Core
Smartwave_Filterproducts
Smartwave_Megamenu
Smartwave_Porto
Smartwave_Socialfeeds
Temando_Shipping
Trustpilot_Reviews
Vertex_Tax
WeltPixel_Backend
WeltPixel_Quickview

**Our Log - Payment.log from var/log**

[2019-04-15 15:41:04] main.DEBUG: array (
  'request' => 
  array (
    'customer' => 
    array (
      'firstName' => 'Stanly',
      'lastName' => 'Stephen',
      'company' => NULL,
      'phone' => '99123456789',
      'email' => 'axxxx@xxxxxx.com',
    ),
    'amount' => '1.00',
    'paymentMethodNonce' => NULL,
    'orderId' => '3700000353',
    'channel' => 'Magento2_Cart_Community_BT',
    'billing' => 
    array (
      'firstName' => 'Stanly',
      'lastName' => 'Stephen',
      'company' => NULL,
      'streetAddress' => 'Via Sky Avenues',
      'extendedAddress' => '',
      'locality' => 'Kochi ',
      'region' => Kerala,
      'postalCode' => '682019',
      'countryCodeAlpha2' => 'IN',
    ),
    'shipping' => 
    array (
      'firstName' => 'Stanly',
      'lastName' => 'Stephen',
      'company' => NULL,
      'streetAddress' => 'Via Sky Avenues',
      'extendedAddress' => '',
      'locality' => 'Kochi ',
      'region' => Kerala,
      'postalCode' => '682019',
      'countryCodeAlpha2' => 'IN',
    ),
    'options' => 
    array (
      'storeInVaultOnSuccess' => true,
      'three_d_secure' => 
      array (
        'required' => true,
      ),
    ),
    'descriptor' => 
    array (
      'name' => 'mydemo',
      'phone' => '3938528106',
      'url' => 'https://www.mydemo.com',
    ),
    'store_id' => 3,
  ),
  'client' => 'Magento\\Braintree\\Gateway\\Http\\Client\\TransactionSale',
  'response' => 
  array (
    'success' => false,
    '' . "\0" . '*' . "\0" . '_attributes' => 
    array (
      'errors' => 
      Braintree\Error\ErrorCollection::__set_state(array(
         '_errors' => 
        Braintree\Error\ValidationErrorCollection::__set_state(array(
           '_errors' => 
          array (
          ),
           '_nested' => 
          array (
            'transaction' => 
            Braintree\Error\ValidationErrorCollection::__set_state(array(
               '_errors' => 
              array (
                0 => 
                Braintree\Error\Validation::__set_state(array(
                   '_attribute' => 'base',
                   '_code' => '91508',
                   '_message' => 'Cannot determine payment method.',
                )),
              ),
               '_nested' => 
              array (
                'shipping' => 
                Braintree\Error\ValidationErrorCollection::__set_state(array(
                   '_errors' => 
                  array (
                  ),
                   '_nested' => 
                  array (
                  ),
                   '_collection' => 
                  array (
                  ),
                )),
                'customer' => 
                Braintree\Error\ValidationErrorCollection::__set_state(array(
                   '_errors' => 
                  array (
                  ),
                   '_nested' => 
                  array (
                  ),
                   '_collection' => 
                  array (
                  ),
                )),
                'billing' => 
                Braintree\Error\ValidationErrorCollection::__set_state(array(
                   '_errors' => 
                  array (
                  ),
                   '_nested' => 
                  array (
                  ),
                   '_collection' => 
                  array (
                  ),
                )),
              ),
               '_collection' => 
              array (
              ),
            )),
          ),
           '_collection' => 
          array (
          ),
        )),
      )),
      'params' => 
      array (
        'transaction' => 
        array (
          'type' => 'sale',
          'customer' => 
          array (
            'firstName' => 'Stanly',
            'lastName' => 'Stephen',
            'company' => NULL,
            'phone' => '3282571299',
            'email' => 'stanly@gangiz.com',
          ),
          'amount' => '1.00',
          'paymentMethodNonce' => NULL,
          'orderId' => '3700000353',
          'channel' => 'Magento2_Cart_Community_BT',
          'billing' => 
          array (
            'firstName' => 'Stanly',
            'lastName' => 'Stephen',
            'company' => NULL,
            'streetAddress' => 'Via Sky Avenues',
            'extendedAddress' => NULL,
            'locality' => 'Kochi',
            'region' => Kerala,
            'postalCode' => '682019',
            'countryCodeAlpha2' => 'IN',
          ),
          'shipping' => 
          array (
            'firstName' => 'Stanly',
            'lastName' => 'Stephen',
            'company' => NULL,
            'streetAddress' => 'Via Sky Avenues',
            'extendedAddress' => NULL,
            'locality' => 'Kochi',
            'region' => Kerala,
            'postalCode' => '682019',
            'countryCodeAlpha2' => 'IN',
          ),
          'options' => 
          array (
            'storeInVaultOnSuccess' => 'true',
            'threeDSecure' => 
            array (
              'required' => 'true',
            ),
          ),
          'descriptor' => 
          array (
            'name' => 'mydemo',
            'phone' => '3938528106',
            'url' => 'https://www.mydemo.com',
          ),
        ),
      ),
      'message' => 'Cannot determine payment method.',
      'creditCardVerification' => NULL,
      'transaction' => NULL,
      'subscription' => NULL,
      'merchantAccount' => NULL,
      'verification' => NULL,
    ),
  ),
) [] []

Information on your environment
PHP 7.1.28 
Magento 2.2.7
Centos 7

 **Steps to reproduce**

1. Install magento 2.2.7 , configure Braintree try to checkout 

 **Expected and actual results**
Payment completed and page should be redirected to cart success page.

**Comment by ghost** [comment]
Hi @ebofi 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by ebofi** [comment]
@engcom-backlog-nazar 
This is realted to Magento Core, Since i tried with similar enviroment on my other machine and saw the same errors.

**Comment by ghost** [comment]
@ebofi please try reproduce on clean magento without 3rth party extensions. Because i'm not able to reproduce steps you described on clean magento instance.
