### ISSUE TITLE
Custom cart price rule error

### ISSUE THREAD

**Issue by sammaggs** [magento/magento2#22349]
### Summary (*)
Minimum order amount error when trying to checkout with new custom Cart Price rule.

Information on your environment -  Magento v2.2.3
Steps to reproduce
Expected - Cart price is reduced to the amount specified in the discount amount field in Marketing > Cart Price Rule >  Discount Amount
Actual - Cart price is reduced but error 'Minimum Order amount is 0.01' stop customer from progressing.

### Examples (*)

![image](https://user-images.githubusercontent.com/40165029/56147798-cd94d500-5fa0-11e9-84cc-2b1dc6128cea.png)

This new cart price rule is supposed to reduce the final price to the equivalent of the discount value, however this causes an issue where the 'Minimum Order Amount' is erroring. Have set minimum order amount to 0.01, so this should not be happening. It looks like Magento is not coping with this size of discount, as the calculations saved in quote table are incorrect (minus figures)

### Proposed solution
Supply a fix to resolve this issue.

**Comment by ghost** [comment]
Hi @sammaggs thank you for you report, i;m not able to reproduce following steps you described on clean magento 2.3-dev instance, seems like this issue not present in latest version, thank you for collaboration.
