### ISSUE TITLE
Widget editing does not work: «Uncaught TypeError: Cannot read property 'innerHTML' of null» (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2235]
![magento2-02](https://cloud.githubusercontent.com/assets/83204/10872331/99128448-8110-11e5-9f32-5b521e750b84.png)
A detailed description and my fix: https://mage2.pro/t/155

**Comment by piotrekkaminski** [comment]
internal id MAGETWO-45017
