### ISSUE TITLE
setup:upgrade throwing sql errors after updating to Magento 2.3.1

### ISSUE THREAD

**Issue by ebofi** [magento/magento2#22353]
Hi,

We had updated our magento from Magento 2.1.14 => 2.3.1. After following magento official notification on the update process. We had completed the update to 2.3.1 via composer. 

Right after we had cleared cache and run the php bin/magento setup:upgrade , what we got when executing this code was 

php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/home/evc/public_html/generated/code/Composer
/home/evc/public_html/generated/code/MSP
/home/evc/public_html/generated/code/Magento
/home/evc/public_html/generated/code/Magmodules
/home/evc/public_html/generated/code/Symfony
/home/evc/public_html/generated/code/TemplateMonster
The directory '/home/evc/public_html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
SQLSTATE[HY000]: General error: 1025 Error on rename of './firesonl_main/#sql-d90_1b45f' to './firesonl_main/customer_group' (errno: 150 - Foreign key constraint is incorrectly formed), query was: ALTER TABLE `customer_group` MODIFY COLUMN `customer_group_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT
[evc@evc public_html]$

### Preconditions (*)

1. Current Magento version 2.3.1
2. Used Magento  https://raw.githubusercontent.com/magento/magento2/2.3.0/dev/tools/UpgradeScripts/pre_composer_update_2.3.php
to fix composer prior to run composer update

### Steps to reproduce (*)

1. Install Magento 2.1.14 and use https://raw.githubusercontent.com/magento/magento2/2.3.0/dev/tools/UpgradeScripts/pre_composer_update_2.3.php to fix the composer and run composer update.
2. You will end on the error shown above.

### Expected result (*)

1. We accept a smooth run of the setup:upgrade command 
2.

### Actual result (*)

1. Running, php bin/magento setup:upgrade will shows  the error 
2. php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/home/evc/public_html/generated/code/Composer
/home/evc/public_html/generated/code/MSP
/home/evc/public_html/generated/code/Magento
/home/evc/public_html/generated/code/Magmodules
/home/evc/public_html/generated/code/Symfony
/home/evc/public_html/generated/code/TemplateMonster
The directory '/home/evc/public_html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
SQLSTATE[HY000]: General error: 1025 Error on rename of './firesonl_main/#sql-d90_1b45f' to './firesonl_main/customer_group' (errno: 150 - Foreign key constraint is incorrectly formed), query was: ALTER TABLE `customer_group` MODIFY COLUMN `customer_group_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT
[evc@evc public_html]$

**Comment by orlangur** [comment]
@ebofi please check if something mentioned on https://stackoverflow.com/questions/8434518/mysql-foreign-key-constraint-is-incorrectly-formed-error works for you.

**Comment by ebofi** [comment]
@orlangur  The issue is from Magento Codes. So a proper instruction on the above case will be more preferred. Thanks for your help friend.

**Comment by orlangur** [comment]
@ebofi,

> The issue is from Magento Codes

Are you able to reproduce it on a clean Magento installation?

**Comment by ebofi** [comment]
@orlangur  Nope, Only when we do a Upgrade from 2.1.14 to 2.3.1

**Comment by orlangur** [comment]
@ebofi I mean, by upgrading clean Magento from 2.1.14 to 2.3.1? Without this issue cannot be investigated, it is most likely caused by some of your shop customizations

**Comment by ghost** [comment]
Hi @ebofi, thank you for you report, i'm not able to reproduce steps you described on clean 2.1 to 2.3 seems like this related to your customizable modules.  also please verify that oreign key column and the referencing column are of the same type or length

**Comment by Sonal824** [comment]
@ebofi 
have you solved issue ?
i am experiencing same after upgrading from magento 2.1.9 to 2.2.3

Thanks
Sona

**Comment by ebofi** [comment]
@sona, We are working to resolve this we made some trial checks .

**Comment by TheFredRoger** [comment]
@eboli 
have you solved issue ?
i am experiencing the exact same issue after upgrading from magento 2.1.1 to 2.3.1. It seems to come from the Amasty extension. Do you use Amasty on this problematic project?

Thanks

**Comment by ebofi** [comment]
@TheFredRoger 

Our issue was a ThemeMonster modules present on the magento system which was not removed properly from the system, We had fixed it by removing the unwanted thememonster extensions from the system. And installed it again( after completely removing those)

**Comment by TheFredRoger** [comment]
Ok, thanks. :)

**Comment by muhammedomar32** [comment]
@TheFredRoger @Sonal824
Dears,
 I have same issue i tried to upgrade magento 2.1.9 to 2.3
ERROR 1833 (HY000): Cannot change column 'customer_group_id': used in a foreign key constraint 'CAT_PRD_IDX_PRICE_STORE_CSTR_GROUP_ID_CSTR_GROUP_CSTR_GROUP_ID' of table 'magento2.catalog_product_index_price_store'

anyone can help me

**Comment by karlhass15** [comment]
Same SQLSTATE[HY000]: General error: 1025 Error on rename of './magento2/#sql-1_2fb' to './magento2/customer_group' (errno: 150 - Foreign key constraint is incorrectly formed), query was: ALTER TABLE `customer_group` MODIFY COLUMN `customer_group_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT  2.1.17 to 2.3.2 upgrade

**Comment by nilarocks** [comment]
Same Error show after upgrade Magento 2.1.7 to 2.3.2.

SQLSTATE[HY000]: General error: 1025 Error on rename of './databsename/#sql-e76_ed2' to './databsename/customer_group' (errno: 150 - Foreign key constraint is incorrectly formed), query was: ALTER TABLE `customer_group` MODIFY COLUMN `customer_group_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT

**Comment by seyuf** [comment]
What worked here: 
1. Try to alter `customer_group_id` type to **int(10)** from mysql or your database manager gui.
 Sql should show the origin of the issue i.e (the foreign key preventing the update).
Mine was due to amasty `Cannot change column 'customer_group_id': used in a foreign key constraint 'AMASTY_FPC_LOG_CUSTOMER_GROUP_CUSTOMER_GROUP_CUSTOMER_GROUP_ID' of table 'db.amasty_fpc_log' 2x:xx:xx SQL command`
2. Go to the concerned table drop the foreign key
3. Update the types of **customer_group_id** column  to **int(10)** in both tables (ie **customer_group** and the table with the deleted foreign key here **amasty_fpc_log**)
4. Recreate the foreign key

The concerned tables should be locked to preserve integrity (additional help https://stackoverflow.com/questions/13606469/cannot-change-column-used-in-a-foreign-key-constraint).

**Comment by adam-roger** [comment]
Same Error show after upgrade Magento 2.1.18 to 2.3.2.

SQLSTATE[HY000]: General error: 1025 Error on rename of './mulondon_dev/#sql-908b1_21b758' to './mulondon_dev/customer_group' (errno: 150 "Foreign key constraint is incorrectly formed"), query was: ALTER TABLE `customer_group` MODIFY COLUMN `customer_group_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT

**Comment by kishansatasiya** [comment]
Same Error show after upgrade Magento 2.1.1 to 2.3.5.

SQLSTATE[HY000]: General error: 1025 Error on rename of './databsename/#sql-e76_ed2' to './databsename/customer_group' (errno: 150 - Foreign key constraint is incorrectly formed), query was: ALTER TABLE customer_group MODIFY COLUMN customer_group_id int(10) UNSIGNED NOT NULL AUTO_INCREMENT
