### ISSUE TITLE
Checkout Agreement Magento 2.2.8, HTML is displayed instead of interpreted

### ISSUE THREAD

**Issue by Webroju** [magento/magento2#22350]
If the content for the checkbox of the checkout terms and conditions contains HTML, then HTML code will be displayed instead of being interpreted.  Iin earlier magento versions html was interpreted.

### Preconditions (*)

1. Magento 2.2.8
2. NGINX

### Steps to reproduce (*)

1. Stores > Terms and Conditions > Add a new condition
2. Fill out the fields, and type at "Checkbox Text" a content with html like: "Some HTML <a href="/link.html">Link</a>"

### Expected result (*)

1. HTML Content at the checkout agreements is interpreted ( in earlier magento versions html was interpreted)

### Actual result (*)

1. HTML is displayed at the checkout agreements
![Screenshot_1](https://user-images.githubusercontent.com/13220558/56151341-4d2aa000-5fb1-11e9-96ec-3b2cc264d497.jpg)

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22350-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22350-2-2-develop.instances.magento-community.engineering/admin](https://i-22350-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@Webroju while creating `terms and conditions` the field name `Checkbox Text` is clear that it would be Text so in that reference this is not bug. I will take opinion from maintainers also about this issue.

**Comment by Webroju** [comment]
@shikhamis11 I understand what you mean, but the knockout.js say it has to interpreted as html, or I'm wrong?
![Screenshot_2](https://user-images.githubusercontent.com/13220558/56157094-f330d700-5fbe-11e9-84ee-b53055542300.jpg)

**Comment by shikhamis11** [comment]
@Webroju as I said since the label already explained that it is text for `terms and conditions` so it will not be converted. It seems it is expected behaviour.

**Comment by Webroju** [comment]
the current behavior is not legal in Germany, because if I want to integrate certain terms & conditions in the contract, I have to link to the document, it would be nice if you reconsider your position.

**Comment by shikhamis11** [comment]
@Webroju you can add your html content inside the content field . while click on the `Checkbox Text ` the content section will be opened in popup where you can add your details

**Comment by Webroju** [comment]
Ok this is not nice, but it will work. Thanks for your help!

**Comment by hostep** [comment]
@Webroju: just for some extra info, the reason why this was changed in Magento 2.2.8 is probably because a security issue was found and fixed.
See https://magento.com/security/patches/magento-2.3.1-2.2.8-and-2.1.17-security-update (search for `PRODSECBUG-2184`).

**Comment by Webroju** [comment]
@hostep: Thanks for the info.

**Comment by pocallaghan** [comment]
According to their own bounty program ```Cross-Site Scripting (XSS) bugs in the admin interface (URLs containing /admin/) where the code is only executed in front-end context but not in admin context. Merchants are explicitly allowed to use active content when designing their stores, so this is a required feature. The admin XSS capability does not give the administrator any additional powers to do harm beyond what other administrative features already allow. XSS issues where an administrator with limited access can impact other administration pages are valid.```

Therefore the ability to add HTML to something that's output on the front-end of the site is not a security concern. Whilst I agree with @hostep that it was probably the attempt to fix `PRODSECBUG-2184` that led to this "break", it's not a valid reason to remove the "feature".

**Comment by jerrydkingx** [comment]
@pocallaghan Have you got any chance to revert it back ?
