### ISSUE TITLE
Double initialization of classes

### ISSUE THREAD

**Issue by ghost** [magento/magento2#22361]
### Preconditions (*)

1. Magento 2.3.1
2. Browser Google Chrome

### Steps to reproduce (*)

1. Inject code
```
debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 3);
        echo '///////////';
```
 to class /vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php in __construct() function
2. run command php bin/magento setup:upgrade (with developer mode)
3. open admin /sales/order/index

### Expected result (*)

1. Show one trace

### Actual result (*)

1. Showed two trace
2. After I reloaded page showed one trace again (it is correct)

It happens with all classes

**Comment by orlangur** [comment]
@Faradey so what is the problem?

Could check stack trace in each occasion to understand in which context class is created?

**Comment by ghost** [comment]
Why after reload page does trace is one time?  The model has been one instance in my module, but after run command php bin/magento setup:upgrade it has two instance

**Comment by orlangur** [comment]
@Faradey it can be created arbitrary amount of times.

Please check stack track in each case to understand why each particular instance was created.

**Comment by ghost** [comment]
Hi folks,  @orlangur , @Faradey there is stack trace with first and second call, in diff
![DeepinScreenshot_select-area_20190416141634](https://user-images.githubusercontent.com/40756439/56205398-56b81480-6052-11e9-9c15-dc0de87c7369.png)

**Comment by ghost** [comment]
@Faradey this class initialize with to different context, so basically there is no issue here. and if you clean cache then it again initializes 2 times
![DeepinScreenshot_select-area_20190416143908](https://user-images.githubusercontent.com/40756439/56206652-84528d00-6055-11e9-9fa9-bad9f483fd79.png)
