### ISSUE TITLE
Trying to open the category chooser to select a category condition for the «Catalog Product List» widget leads to the exception «Cannot read property 'value' of null»

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2236]
![magento2-03](https://cloud.githubusercontent.com/assets/83204/10872798/c0542d36-811a-11e5-9261-2ade0edfbfd0.png)

https://mage2.pro/t/156

**Comment by piotrekkaminski** [comment]
Internal ticket MAGETWO-44969

**Comment by dfediuk** [comment]
Fixed.
