### ISSUE TITLE
Magento 2 Stores -> Configuration redirects to dashboard

### ISSUE THREAD

**Issue by Mitrajsinh** [magento/magento2#22366]
Preconditions (*)
newly setup of magento 2.2.8. 
Stores -> Configuration redirects to the Dashboard.

Steps to reproduce (*)
Enable : - Add Secret Key to URLs from Backend
Go to order section After That click on store > config 

Expected result (*)
Access to the Stores -> Configuration page

Actual result (*)
I'm being redirected to the dashboard

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22366-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22366-2-2-develop.instances.magento-community.engineering/admin](https://i-22366-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22366-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22366-2-3-develop.instances.magento-community.engineering/admin](https://i-22366-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99227` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
**Note:** This issue is not reproduced on 2.3.x.

**Comment by gwharton** [comment]
I got so fed up of this that I disabled adding Secret Key to URLs from Backend. After the update to 2.2.8 It changed from being a one off every now and again, to 100% of the time for me. Disabling secret key as workaround.

**Comment by nocturnalfrog** [comment]
Looks like https://github.com/magento/magento2/pull/18018 is to blame.

**Comment by sarfarazbheda** [comment]
I am able to replicate the issue on Magento 2.2.8 after the upgrade.

@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sarfarazbheda. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sarfarazbheda, here is your [Magento instance](https://i-22366-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22366-2-2-develop.instances.magento-community.engineering/admin](https://i-22366-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sarfarazbheda** [comment]
I am able to replicate issue with above instance. Steps:
- Enable Add Secret Key to URLs
- Go to Sales-> Orders
- Navigate to any other menu

**Comment by pemann** [comment]
Occurs for me also after I upgraded to 2.2.8 (from 2.2.3)

**Comment by ghost** [comment]
+1, I'm seeing it after upgrading to 2.2.9 from 2.2.7

**Comment by ghost** [comment]
+1 2.2.8 -> 2.2.9

**Comment by elvinristi** [comment]
this seems to fix the issue what is in 2.3 branch for `app/code/Magento/Backend/Block/Menu.php`
- https://github.com/magento/magento2/commit/956f36132e3438acfea61a3e4cd41b43e1bd1fc0

```diff
     {
         $routeId = $this->routeConfig->getRouteByFrontName($match[1]);
         return \Magento\Backend\Model\UrlInterface::SECRET_KEY_PARAM_NAME . '/' . $this->_url->getSecretKey(
-            $routeId,
+            $routeId ?: $match[1],
             $match[2],
             $match[3]
         );
```

It seems to be also already in 2.2-development branch but not part of 2.2.9
- https://github.com/magento/magento2/commit/5be13c5da3f73360fef761c9a4f368bf715927fd#diff-69ae04f06b2a290de8d689525dfe33e0R222

**Comment by wjpbill** [comment]
Hello everyone

Did anyone find a fix for this. I'm running 2.2.8 and for the minute have disabled secret keys in the admin and it's working again but wondered if there's a code fix anywhere for 2.2.8?

**Comment by elvinristi** [comment]
@wjpbill check previous comment https://github.com/magento/magento2/issues/22366#issuecomment-508707963

**Comment by wjpbill** [comment]
> @wjpbill check previous comment #22366 (comment)

That work, thank you very much. It was driving me around the bend.
The only problem I have now is that stupid "Attention, Something Went Wrong" popup with it's associated "There was a technical problem blah blah" error when you click a menu item. It always goes way when I close it but it's so irritating and nothing in the logs.

**Comment by ghost** [comment]
@wjpbill, we only get that message when viewing an order on the admin. We haven't investigated it. It seems to go away after showing up 1 time.

**Comment by engcom-Bravo** [comment]
Hello, @Mitrajsinh 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by aashworth-ldg** [comment]
> Occurs for me also after I upgraded to 2.2.8 (from 2.2.3)

Same for me.
