### ISSUE TITLE
Checkout problem

### ISSUE THREAD

**Issue by colettamatteo98** [magento/magento2#22360]
### Preconditions (*)

1.Magento ver. 2.3.1

### Steps to reproduce (*)

1. Make checkout choosing one payment method and shipping method (indifferent choice)

### Expected result (*)

The checkout should be function.

### Actual result (*)

1. Checkout does not function. When i press the button "place order" appear a point of interruption, so the checkout does not go on and does not function.
![checkout_758](https://user-images.githubusercontent.com/49673688/56192931-cb2d8c00-602f-11e9-87e3-ef1eaabb3730.jpg)

2.

**Comment by ghost** [comment]
HI @colettamatteo98 thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.3-develop instance this may be related to your custom modules or themes.

**Comment by colettamatteo98** [comment]
This problem could be a theme problem?
