### ISSUE TITLE
magento2.3 - Group product can't add virtual product type.

### ISSUE THREAD

**Issue by sidealice** [magento/magento2#22374]
### Description (*)
Group product can't add virtual product type in backend after saving.

### Expected behavior (*)
Add group product as expected

### Benefits
Virtual product also need group selling marketing tool

### Additional information
No.

**Comment by shikhamis11** [comment]
@sidealice Thank you for your report.
 I am able to add virtual products into grouped product. please check this at 2.3-develop instance. message here if you still able to reproduce this issue.
