### ISSUE TITLE
Sales Order - Reorder - No shipping methods available

### ISSUE THREAD

**Issue by pjw345** [magento/magento2#22372]
### Preconditions (*)

1. Fresh Install - Magento 2.3.0
2. Install sample data

### Steps to reproduce (*)

1. Create an order (adminhtml)
2. After the order has been created use Reorder to duplicate the order
3. Remove the original product ordered (Update Items and Quantities)
4. Add a different product to the order (Add Products)

### Expected result (*)

1. Select a shipping method
2. Select payment method
3. Create order

### Actual result (*)

1. Get shipping methods and rates.
2. Sorry, no quotes are available for this order.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22372-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22372-2-3-develop.instances.magento-community.engineering/admin](https://i-22372-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@pjw345 Thank you for your report. 
I am not able to reproduce this issue on magento 2.3-develop instance with your provided step . I don't think sample data will make any difference, Please check if you are able to reproduce it on magento 2.3-develop instance also update here if it require any additional step to reproduce the issue.

**Comment by pjw345** [comment]
A fresh version of Magento 2.3.0 was installed, along with sample data, Braintree was configured as a payment method, along with flat shipping.

**Comment by pjw345** [comment]
The only other thing I can thing of was that the hosting directory was pointed to httpdoc/pub and not httpdoc

**Comment by pjw345** [comment]
Shipping methods flat rate and table rate were enabled, all others were disabled

**Comment by shikhamis11** [comment]
are you able to reproduce this issue at 2.3-develop instance .. Please check

**Comment by shikhamis11** [comment]
@pjw345 I am not able to reproduce this issue with your provided steps, Please let me know here if you are still able to reproduce this issue on magento 2.3-develop instance. If possible share the screenshots also
