### ISSUE TITLE
Custom attribute convert from quote to order and its item its not working

### ISSUE THREAD

**Issue by pradeeprcs** [magento/magento2#2237]
I am trying to add custom filed in quote quote_item and order order_item table 

once product is add to cart i added custom value to quote and quote_item table 

then i place order data is not copy from quote to order tables 

i gave solution or work around for that in
 http://magento.stackexchange.com/questions/77016/copy-custom-data-from-quote-to-order-and-order-item/88024#88024

i created filedset.xml  
data is moving from order to invoices but not from quote to order 

is this is bug in magento2 or not if not then can you please tell me where i made wrong code is in the give link 
 http://magento.stackexchange.com/questions/77016/copy-custom-data-from-quote-to-order-and-order-item/88024#88024

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by pradeeprcs** [comment]
Hi david alger,

My question is it bug or not in magento2
if not please let me know which post or forum i need to check
