### ISSUE TITLE
Admin panel Product Stock status is not automatically getting updated from out of stock to in-stock

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#22388]
### Preconditions (*)

1. Magento 2.3.0
2. Magento Admin panel 

### Steps to reproduce (*)

1. Login to the Admin panel
2. Navigate to catalog -> product
3. Select preferred product OR Click on Add new product  button
4. On product page change quantitiy to 0  and save then system automatically changing the stock status to "Out-of-stock".
5. Now again change the quantity to more than 0 and save, observe in this case system is not automatically changing stock status to "Instock"

### Expected result (*)
1. When qty is updated more than 0 then system should automaticaaly change the stock status to "Instock"

### Actual result (*)

1. After updating the qty to more than 0, stock status is not updating to "Instock" automatically. 

Please refer to the attached screen shot. 
https://drive.google.com/file/d/1pZsHG3uL3afPGim8-h30nsT7ejSmMK9u/view

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22388-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22388-2-3-develop.instances.magento-community.engineering/admin](https://i-22388-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22388-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22388-2-2-develop.instances.magento-community.engineering/admin](https://i-22388-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99246` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ktpl-rammohan** [comment]
FYI, Issue is not reproduced on Magento 2.2

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](https://i-22388-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22388-2-3-develop.instances.magento-community.engineering/admin](https://i-22388-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](https://i-22388-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22388-2-2-develop.instances.magento-community.engineering/admin](https://i-22388-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Hashamwebdev** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Hashamwebdev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Hashamwebdev, here is your [Magento instance](https://i-22388-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22388-2-3-develop.instances.magento-community.engineering/admin](https://i-22388-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Hashamwebdev** [comment]
label:"Issue: Confirmed"

**Comment by Hashamwebdev** [comment]
@magento-engcom-team Issue confirmed on Magento 2.3

**Comment by GovindaSharma** [comment]
#dmcdindia1

**Comment by mageshrdckap** [comment]
I am working on this at #dmcdindia1

**Comment by slavvka** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @slavvka. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by slavvka** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @slavvka. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by magento-engcom-team** [comment]
Hi @slavvka, here is your [Magento instance](https://i-22388-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22388-2-3-develop.instances.magento-community.engineering/admin](https://i-22388-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment]
@magento-engcom-team give me 2.2 instance

**Comment by sdzhepa** [comment]
Hello @GraysonChiang  and @rammohan-krish 

I am not sure it is really a bug.
Seems it is expected behavior and it was made intentionally.
The idea to do it manually is to give merchants more control and flexibility for all business scenarios.
Such fix could make setting "Out-of-stock" useless and affect another camp of merchants who use current behavior. For scenarios like: Merchan has received items in-stock But according to an agreement, a merchant cannot start sales before the official announcement from the manufacturer(Marketing campaign or so)

Also, please have a look at other settings such as [Inventory Management](https://docs.magento.com/m2/ce/user_guide/catalog/inventory-configure-inventory-management.html), [Backorders](https://docs.magento.com/m2/ce/user_guide/catalog/inventory-backorders.html), [Product Options](https://docs.magento.com/m2/ce/user_guide/catalog/inventory-product-stock-options.html). All of them have dependency or relation to "In Stock/Out of Stock" setting. Probably it is possible to cover your case in a different way but using existed settings.

But to be 100% sure, I am going to ask the Product Management team to clarify is it expected result or it is a bug. As soon as I have an answer, I will share it here

**Comment by ghost** [comment]
Ok Thanks

**Comment by slavvka** [comment]
Guys, according to the response from our PO this is not a bug:

> this is definitely not a bug, product stock status should not be updated automatically to “In stock” when quantity is updated, this should be done manually.
