### ISSUE TITLE
Why is out of stock product having add to cart button in grids of sample data in magento 2.3.0 vanilla instance?

### ISSUE THREAD

**Issue by sanjay-github** [magento/magento2#22385]
### Preconditions (*)

1. Magento 2.3.0 with sample data.
2.

### Steps to reproduce (*)

1.Please install magento 2.3.0 instance with sample data and observe LifeLong Fitness IV product.
2.Observe this product on detail page  and on home page/grids.

### Expected result (*)

1. Product should not have Add to Cart button when it is out of stock.
2.

### Actual result (*)

1.Product is having Add to Cart button even though it is out of stock.
2.

**Comment by ajijshekh123** [comment]
Please provide the Magento 2.3.0 instance.

**Comment by ghost** [comment]
hi @ajijshekh123 i already in process this issue.

**Comment by ajijshekh123** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22385-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22385-2-3-develop.instances.magento-community.engineering/admin](https://i-22385-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
HI @sanjay-github thank you for you report, this issue does not exist in 2.3-develop branch.
![DeepinScreenshot_select-area_20190417140836](https://user-images.githubusercontent.com/40756439/56283419-5e42f080-611a-11e9-963a-a565a2e29bee.png)

**Comment by ghost** [comment]
@ajijshekh123 if you see that issue already has assigned another user please do not start verification process. thank you
