### ISSUE TITLE
How to create custom new attribtue for the Category ?

### ISSUE THREAD

**Issue by chaluvadiswamy** [magento/magento2#2239]
I want to create the Custom new attribute for Category in admin form .I have tried with following ways:
- By using the InstallData.php in Setup folder
- By using the UpgradeData.php In SetUp folder 
But its does not give any result ,also in am unable to find 'Magento\Catalog\Model\CategoryFactory.php '  not found .

Can any face same issue let me know.

**Comment by daim2k5** [comment]
The github issue tracker is intended for technical issues only.
Please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) for technical questions. In your case probably the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
