### ISSUE TITLE
Google Analytics Not Recording Conversions 2.2.8

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#22398]
We have seen this issue since Magento 2.2.5. We are currently using Magento 2.2.8. 

Google Analytics has tracked just under 50% of our conversions this month so far.

### Preconditions (*)
1. Magento 2.2.8
2. Google Analytics

### Steps to reproduce (*)
1. Make various purchases on site.

### Expected result (*)
1. All purchases tracked via Google Analytics

### Actual result (*)
1. Only about half of purchases recorded in Google Analytics.

**Comment by orlangur** [comment]
@nickpiro how you think such bug report can be investigated?

**Comment by inkobject** [comment]
Just a note of concurrence: I have seen the same behavior on my install from 2.2.5+. I have not been able to determine a reason.

**Comment by DanielRuf** [comment]
> We have seen this issue since Magento 2.2.5

Might be useful to bisect this.
Which steps do we need to reproduce it in our test environment?

**Comment by nickpiro** [comment]
@magento-engcom-team give me 2.2.8 instance

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nickpiro, here is your [Magento instance](https://i-22398-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-22398-2-2-8.instances.magento-community.engineering/admin](https://i-22398-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nickpiro** [comment]
@orlangur I think the best way would be to do test orders with Check/Money Order payment.

Setup Google Analytics with eCommerce conversion tracking, link it to Magento 2.2.8 instance, test orders. They should show fairly quickly. Unfortunately it's not all orders.

I spoke to someone and it was a js issue on checkout, I did a temp fix on 2.2.5 but it never actually worked.

**Comment by orlangur** [comment]
@nickpiro ok, please confirm you're able to reproduce problem with such steps on a clean Magento installation and then put such steps into description.

**Comment by gwharton** [comment]
Use the Google Tag assistant addon to the Chrome Browser (may be available for other browsers too) to diagnose what GA tags are present, where, and when they are being fired. You can record entire sessions while purchasing and the tag assistant will tell you what it did, with regard to submitting info to GA.

**Comment by engcom-Charlie** [comment]
Hello @nickpiro 
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!
