### ISSUE TITLE
Rest API Magento 2.3.1 update product attribute not working as expected / documented

### ISSUE THREAD

**Issue by AlterWeb** [magento/magento2#22391]
### Preconditions (*)
1. Magento 2.3.1
2. Product attribute with attribute code "test_attribute" exists with the default frontend label "Test"

### Steps to reproduce (*)
1. Call the url https://domain.tld/rest/V1/products/attributes/test_attribute with a PUT request containing the following data:
{
  "attribute": {
    "default_frontend_label": "Test2"
  }
}

### Expected result (*)

1. The default frontend label should be changed to "Test2"

### Actual result (*)

1. Get an 400 Bad Request, saying something about missing the frontend_input
2. The default frontend label still is set to "Test"
3. If the frontend_input is supplied it states the attribute already exist

### Workaround 
Also supply the attribute_id in your data like:

{
  "attribute": {
    "attribute_id": 138,
    "default_frontend_label": "Test2"
  }
}

But this is kind of strange because we already supplied the attribute code in the URL to identify what attribute we like to change. Also in our case forcing me to first fire an extra GET request to get the attribute id from the Magento installation.

**Comment by AlterWeb** [comment]
This was indeed on a vanilla Magento instance. I only added a attribute to test this behavior.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99309`, `MAGETWO-99310` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by masuknj** [comment]
while updating attribute:

_An attribute with the same code (product_type) already exists._

**Comment by gomencal** [comment]
@magento I am working on it

**Comment by leeroybrun** [comment]
Do you have an idea when this will be fixed/merged?
