### ISSUE TITLE
getImageUploadConfigData in template returns null causing crash

### ISSUE THREAD

**Issue by aario** [magento/magento2#22394]
### Preconditions (*)
1. Using an extension which calls template:
```
vendor/magento/module-backend/view/adminhtml/templates/media/uploader.phtml
```
In its edit action in admin panel.
2. The extension is [magefan/module-blog](https://github.com/magefan/module-blog/)
3. Rendering the magento template crashes on line: 18
4. Magento 2.3.1
5. `magento/module-backend` version: 101.0.1

### Steps to reproduce (*)
1. Go to admin panel
2. Trigger any action that calls the above template

### Expected result (*)
1. Admin panel should not crash

### Actual result (*)
1. The template runs:
```
            "isResizeEnabled": <?= /* @noEscape */ $block->getImageUploadConfigData()->getIsResizeEnabled() ?>
```
2. `$block->getImageUploadConfigData()` comes `null`
3. `getIsResizeEnabled()` causes crash

**Comment by orlangur** [comment]
@aario so why `$block->getImageUploadConfigData() comes null` happend?

**Comment by aario** [comment]
Issue was with older version of the third party extension not initializing image upload block well. The block should be initialized as in:
`vendor/magento/module-catalog/Block/Adminhtml/Product/Helper/Form/Gallery/Content.php`
like:
```
        $this->addChild(
            'uploader',
            \Magento\Backend\Block\Media\Uploader::class,
            ['image_upload_config_data' => $this->imageUploadConfigDataProvider]
        );
```
