### ISSUE TITLE
Fatal error: Class 'Codeception\Platform\Extension' not found

### ISSUE THREAD

**Issue by farhangithub27** [magento/magento2#22400]
### Preconditions (*)

1. Magento 2.3.1
2. Php 7.2.15
3. OS : Ubuntu 18.04 Bionic
4 Phpstorm 2019.1.1
4 Evnironemnt : Magento development

### Steps to reproduce (*)

1. bin/magento dev:tests:run unit
2. vendor/phpunit/phpunit/phpunit -c dev/tests/unit/phpunit.xml.dist

### Expected result (*)

1. A successful unit test for my Model Class
2.

### Actual result (*)

1. Fatal error: Class 'Codeception\Platform\Extension' not found in /var/www/html/magento23demo/vendor/allure-framework/allure-codeception/src/Yandex/Allure/Adapter/AllureAdapter.php on line 49
2.

**Comment by ghost** [comment]
HI @farhangithub27 thank you for you report, i'm not able to reproduce following steps you described please refer to ->
![DeepinScreenshot_select-area_20190418104931](https://user-images.githubusercontent.com/40756439/56345176-c7cd0880-61c7-11e9-8813-903a10c90ebe.png)
https://devdocs.magento.com/guides/v2.3/test/unit/unit_test_execution_cli.html

**Comment by farhangithub27** [comment]
Hi @engcom-backlog-nazar. please run following commands and observe the output. 
`bin/magento dev:tests:run unit` or  `vendor/phpunit/phpunit/phpunit -c dev/tests/unit/phpunit.xml.dist`
