### ISSUE TITLE
Store view specific labels cut in left navigation menu

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#22406]
Store view specific labels cut in left navigation menu in cart price rule.

### Preconditions (*)

Magento 2.3.x

### Steps to reproduce (*)

1. Go to Admin
2. Marketing >> Cart Price rule
3. Labels >> Store View Specific Labels 
4. Review the Main Websites and Main Website Store labels

### Expected result (*)

https://www.screencast.com/t/kQG9Kmwk

### Actual result (*)

https://www.screencast.com/t/ECiEKvkHS

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22406-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22406-2-3-develop.instances.magento-community.engineering/admin](https://i-22406-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99262` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudhanshu-bajaj** [comment]
Already created pull request here #22423

**Comment by Karlasa** [comment]
@sudhanshu-bajaj Issue tickets should be closed when they are not relevant or fixed. Currently this ticket should be kept open till your PR gets merged. 
Thanks for noticing and connecting PR and issue. You can updated your PR description with issue number that it fixes. 

Cheers,

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#22423 by @sudhanshu-bajaj in 2.3-develop branch
Related commit(s):
 - [2b60b9fad8d06b47ef0dca54fa321cb35aab2f42](https://github.com/magento/magento2/commit/2b60b9fad8d06b47ef0dca54fa321cb35aab2f42)

The fix will be available with the upcoming 2.3.3 release.
