### ISSUE TITLE
Configurable products are shown on Select Associated Product modal

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#22409]
### Preconditions (*)

1. Magento 2.3.1 

### Steps to reproduce (*)

1.Create a configurable product **Test 1** with 2 child products (color = red and color = black for the example)
2. Create a new simple product **Test 2** with color = red
3. Open the last created product **Test 2** in admin panel and convert it to configurable by adding child products (color = green, color = grey), do not change the value for color attribute while you edit product
4. Open the first configurable product **Test 1**, remove the child product with color = red, click on 'Add products manually' link in Configurations section

### Expected result (*)

Select Associated Product modal contains only simple and virtual products

### Actual result (*)

Configurable product **Test 2** is shown on Select Associated Product modal. If it is selected in modal the configurable product is added on Configurations section of product **Test 1**, saving the product doesn't give any error message, configurable product **Test 2** is not added as a child product during saving

![test 1   Products   Inventory   Catalog   Magento Admin](https://user-images.githubusercontent.com/8502721/56364174-9a4b8380-61f6-11e9-9655-b727c4113f2d.png)
![Products   Inventory   Catalog   Magento Admin](https://user-images.githubusercontent.com/8502721/56364229-bc450600-61f6-11e9-8698-3025d1d2bf4e.png)

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22409-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22409-2-3-develop.instances.magento-community.engineering/admin](https://i-22409-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22409-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22409-2-2-develop.instances.magento-community.engineering/admin](https://i-22409-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99268`, `MAGETWO-99269` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by orlangur** [comment]
@mslabko ай-яй-яй :)

**Comment by mallikaverma** [comment]
I am working on this at #dmcdindia1

**Comment by mallikaverma** [comment]
#MM20IN

**Comment by mallikaverma** [comment]
#dmcdindia2020

**Comment by VuThuan** [comment]
Hi @magento-engcom-team this bug. Do you have any idea ?

**Comment by engcom-Bravo** [comment]
@magento give me develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @lyusya-nnn,

Thanks for your reporting and collaboration.

We have verified the issue and the issue is no more reproducible in Latest 2.4-develop instance.

<img width="1266" alt="Screenshot 2024-04-25 at 15 13 58" src="https://github.com/magento/magento2/assets/51680745/22275fbd-034e-4ea1-8a33-d5a34a6f819a">



Select Associated Product modal contains only simple and virtual products


Hence We are closing this issue.

Thanks.
