### ISSUE TITLE
Method \Magento\Cms\Controller\Adminhtml\Page\Save::executeInternal() ignores the result of the «cms_page_prepare_save» event while validation

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2240]
The problem line is 
https://github.com/magento/magento2/blob/f578e54e093c31378ca981cfe336f7e651194585/app/code/Magento/Cms/Controller/Adminhtml/Page/Save.php#L62

I propose to change it to
```
if (!$this->dataProcessor->validate($model->getData())) {
```

My detailed explanation: https://mage2.pro/t/159

**Comment by andimov** [comment]
@mage2pro 
Could you please add the description of steps, actual result and expected result to this ticket?
It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Method-Magento-Cms-Controller-Adminhtml-Page-Save/idi-p/45376).
