### ISSUE TITLE
Unable save product which has custom url rewrite (M 2.2.5,2.2.8)

### ISSUE THREAD

**Issue by xchuki00** [magento/magento2#22408]
When I try to save product with custom rewrite, i get this error:
![Screenshot from 2019-04-18 13-45-46](https://user-images.githubusercontent.com/22961273/56359335-93fedc80-61e1-11e9-9b84-276a4f88b601.png)
Error is caused by sql select in function afterReplace in file Magento\CatalogUrlRewrite\Model\Category\Plugin\Storage, because of fetch custom url_rewrites without category.
### Preconditions (*)

1. Magento version 2.2.5
2. Product X used in two websites(.com, .de), in both with checked use default url_key
3. Custom url rewrite for product X for redirect 
         shop.de/englishCategoryName/ProductX -> shop.de/ProductX, 301, store de
         In database (1738,1747
![Screenshot from 2019-04-18 13-52-27](https://user-images.githubusercontent.com/22961273/56359382-b264d800-61e1-11e9-8c68-b00e61d0e0d9.png)
)
  

### Steps to reproduce (*)

1. Install magento 2.2.5 with sample data
2. Create new store
3. Create new product common for both store, default url_key for both, and will be at least in one category(this category shoud have different url key for store 1 and store 2)
4. Create url rewrite for this product without set category, like /store1CategoryName/ProductX -> /ProductX, with 301 pernament
![Screenshot from 2019-04-18 14-01-33](https://user-images.githubusercontent.com/22961273/56359683-8bf36c80-61e2-11e9-8f8e-3092c24f7169.png)
5. now try save new Product with change visibility, category or url_key for "all store views"

### Expected result (*)

1. You saved the product.

### Actual result (*)

1. ![Screenshot from 2019-04-18 13-45-46](https://user-images.githubusercontent.com/22961273/56359335-93fedc80-61e1-11e9-9b84-276a4f88b601.png)

**Comment by xchuki00** [comment]
I was able reproduce issue on 2.2.8 too.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99303`, `MAGETWO-99304` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mallikaverma** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @xchuki00. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24153` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
