### ISSUE TITLE
Cart Page delete all Products after edit quantity of any products

### ISSUE THREAD

**Issue by alessandrosiervo** [magento/magento2#22401]
Hi,
i have this problem on Magento 2.3.1. Sorry for my language 

### Summary:

I go in cart page and i have already some products ( example products A, B and C ) . I want edit quantity one of them ( example edit Qty product A from 1 to 2 ). After change quantity i click enter keyboard button for cart update. 

The result:  all product are deleted from cart !!

### Preconditions:

Magento 2.3.1 installed with Installatron of CPanel. 
( There is this problem on 2.3.1 version but there isn't on 2.3.0 version )

### Steps to reproduce:

Add to cart some products ( one or more, it's not important ) , example:
  A qty 1 
  B qty 2

Go to cart page, edit quantity of item A from 1 to 3 and click enter keyboard button.
The result ( error ) :  items A and B are deleted from cart

### Expected results:

Cart should not be empty and product is updated.

### Actual results:

Update quantity of item A .

Sorry again for my poor language. I hope I was clear.
Thank you all

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22401-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22401-2-3-develop.instances.magento-community.engineering/admin](https://i-22401-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22401-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22401-2-2-develop.instances.magento-community.engineering/admin](https://i-22401-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by alessandrosiervo** [comment]
In Magento 2.3.0 there isn't this problem, only in 2.3.1. and 2.2.8 version

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2.8-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2.8-develop instance for you

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2.8-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2.8-develop instance for you

**Comment by krishprakash** [comment]
Hi @alessandrosiervo. Thank you for your report.
I am not able to reproduce It may be page loading issue or session time out issue.
So please check after page loaded properly.

**Comment by alessandrosiervo** [comment]
Hi, thanks for your answer.
I don't understand what version is this istance but in 2.3.0 there isn't this problem but only in 2.3.1.

You can try in my test website https://www.keyhelmshop.it/new/

**Comment by krishprakash** [comment]
Hi @alessandrosiervo,
Thank you for your response.
I'm not able to reproduce this issue. 
Issue may be related to your custom module or Porto theme issue.

**Comment by alessandrosiervo** [comment]
I created the ticket for the port support and was told that it is a magento problem :(

**Comment by alessandrosiervo** [comment]
if you can try my test website https://www.keyhelmshop.it/new/ you can see the problem.... 


However, if there is nothing that can be done, I thank you and wait for the next version of magento xD.

Thanks for everything

**Comment by jkeller92** [comment]
The problem here is, that the cart form contains 2 submit buttons.
After hitting `enter` on keyboard or clicking `ok` on mobile devices, the first button[type="submit"] will be triggered.

If you have a look at `module-checkout/view/frontend/templates/cart/form.phtml` you can see the first button[type="submit"] is the delete button.

Changing the order will fix the problem.

just change this:

        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */ __('Clear Shopping Cart') ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
        </button>
 

to:

        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */ __('Clear Shopping Cart') ?></span>
        </button>

**Comment by jkeller92** [comment]
> Hi @alessandrosiervo,
> Thank you for your response.
> I'm not able to reproduce this issue.
> Issue may be related to your custom module or Porto theme issue.

This is core issue.
