### ISSUE TITLE
"Select all" on admin product grid only passes the first page of products to grid actions since 2.3.1.

### ISSUE THREAD

**Issue by samsteele** [magento/magento2#22414]
### Preconditions (*)

1. Fresh Magento Commerce 2.3.1 install.
2. Create more than 20 products. 

### Steps to reproduce (*)

1. Navigate to the Catalog > Products grid in the admin area.
2. Click "Select All" in the first column of the product grid headers.
3. The label updates to say "X records found (X selected)"
4. Perform an action on all selected products (eg, Delete, Change Status...)

### Expected result (*)
1. All selected products will be affected by the action.

### Actual result (*)
1. Only the first page of products are affected by the action.

**Comment by samsteele** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @samsteele. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @samsteele, here is your [Magento instance](https://i-22414-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22414-2-3-develop.instances.magento-community.engineering/admin](https://i-22414-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by samsteele** [comment]
Replicated on 2.3-develop instance

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22414-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22414-2-3-develop.instances.magento-community.engineering/admin](https://i-22414-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99274` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Nazar65** [comment]
Hi @aredridel This is duplicate to  https://github.com/magento/magento2/issues/22004

**Comment by krishprakash** [comment]
@Nazar65,
Thank you for verify this for duplication issue.
