### ISSUE TITLE
assignProductToCategories seems very slow 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#22412]
### Summary (*)
I've created a custom command that updates the categories in the eshop programmatically. More specifically amongst other things it does the following 
1. locates all products
2. Checks the current categories of the product. 
3. Checks the parent categories of the already assigned categories.
4. Assigns the ones missing from the product category chain 
5. Saves the new relation

To achieve this I'm utilizing the function `assignProductToCategories` from `CategoryLinkManagementInterface`
but the speed of saving the relations is incredibly slow. 
The whole thing gets stuck in the actual saving of the category and it's ridiculously slow.

My dataset is about 10000 products and about 70 categories. 
Each product is normally assigned to 1,2 categories and needs to be assigned to 1-2 extra parent categories. 

The end result after 12 hours of processing this piece of code is about 5000 products. If I omit the actual saving action it runs in less than a few seconds. Resaving already processed products is almost instant. 

Environment and Server Specs:
Magento 2.3.0
CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
SSD
64GB RAM
Debian 9 
PHP 7.2 

### Examples (*)
Here is a part of the code I'm using for this action
`<?php
    namespace Ioweb\Toolbox\Console\Command;

    use Magento\Catalog\Api\CategoryLinkManagementInterface;
    use Magento\Catalog\Api\CategoryRepositoryInterface;
    use Magento\Catalog\Api\ProductRepositoryInterface;
    use Magento\Catalog\Model\Category;
    use Magento\Catalog\Model\CategoryRepository;
    use Magento\Catalog\Model\ResourceModel\Product;
    use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;
    use Magento\Framework\Api\SearchCriteriaBuilderFactory;
    use Magento\Framework\App\Area;
    use Magento\Framework\App\State;
    use Magento\Store\Model\StoreManagerInterface;
    use Psr\Log\LoggerInterface;
    use Symfony\Component\Console\Command\Command;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Input\InputOption;
    use Symfony\Component\Console\Output\OutputInterface;

    class AssignParentCategories extends Command
    {

        const NAME = 'ioweb:toolbox:assign-parent-categories';
        const DESCRIPTION = 'Reset product categories to use all their parents as well';
        const OPTION_AREA = 'area';
        const OPTION_STORE = 'store';
        protected $logger;
        protected $state;
        protected $collectionFactory;
        protected $storeInterface;
        protected $categoryRepository;
        protected $categoryLinkManagement;
        public function __construct(
            LoggerInterface $logger,
            State $state,
            CollectionFactory $collectionFactory,
            StoreManagerInterface $storeInterface,
            Product $productModel,
            CategoryRepository $categoryRepository,
            CategoryLinkManagementInterface $categoryLinkManagement
        )
        {
            $this->state = $state;
            $this->logger = $logger;
            $this->storeInterface = $storeInterface;
            $this->collectionFactory = $collectionFactory;
            $this->productModel = $productModel;
            $this->categoryRepository = $categoryRepository;
            $this->categoryLinkManagement = $categoryLinkManagement;
            parent::__construct();
        }

        /**
         * {@inheritdoc}
         */
        protected function configure()
        {

            $this->setName(self::NAME)
                ->setDescription(self::DESCRIPTION)
                ->addOption(self::OPTION_AREA, null, InputOption::VALUE_OPTIONAL, 'area: can be one of global, adminhtml, frontend')
                ->addOption(self::OPTION_STORE, null, InputOption::VALUE_REQUIRED, 'Store view id')
            ;
            parent::configure();
        }

        /**
         * {@inheritdoc}
         */
        protected function execute(InputInterface $input, OutputInterface $output)
        {
            $this->state->setAreaCode(Area::AREA_ADMINHTML);
            $storeId = $input->getOption(self::OPTION_STORE);

            if (empty($storeId) && $storeId != 0) {
                $output->writeln("<error>Please specify a storeId --store</error>");
                return false;
            }
            $collection = $this->collectionFactory->create();
            $collection->setStoreId($storeId)
                ->addAttributeToSelect(['sku'])
            ;
            $items = $collection->getItems();

            $loop = 1;

            foreach ($items as $item) {

                /**
                 * @var $item \Magento\Catalog\Model\Product
                 */
                $itemId = $item->getId();
                $output->writeln("<info>Processing product $itemId " . $item->getData('sku') . "</info>");
                $productCategoryIds = $item->getCategoryIds();
                $productCategories = $item->getCategoryCollection();
                foreach ($productCategories as $productCategory) {
                    $parentCategories = $productCategory->getParentCategories();
                    foreach ($parentCategories as $parentCategory) {
                        /**
                         * @var $parentCategory Category
                         */
                        $productCategoryIds[] = $parentCategory->getId();
                    }
                }

                $productCategoryIds = array_unique($productCategoryIds);

                $this->categoryLinkManagement->assignProductToCategories($item->getSku(), $productCategoryIds);
                $loop++;

            }
        }

    }`

### Proposed solution
I've tracked the issue down to this command 
vendor/magento/module-catalog/Model/CategoryLinkRepository.php: save()::47
`$category->save()`

Is it possible to just save the needed attributes only instead of the whole category? Perhaps it could improve the time needed to perform this task.

**Comment by ghost** [comment]
HI @ioweb-gr thank you for you report, such changes is backward incompatible, see>https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/ , 
Please try use queue to perfomance your code , and split for batches.  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/message-queues.html
thanks for collaboration :+1:

**Comment by kl3m3n** [comment]
Hi, I've encountered the same problem on M 2.4.4 and was able to fix it or at least come around it. Just make sure your indexes are set to schedule and not to realtime (save).
