### ISSUE TITLE
Markdown inside less file

### ISSUE THREAD

**Issue by 00F100** [magento/magento2#22417]
### Preconditions (*)

1. Magento ver. 2.1.7

### Steps to reproduce (*)

1. Open file magento/magento2-base/lib/web/css/docs/source/_actions-toolbar.less
2. Have markdown into LESS file

### Expected result (*)

1. only LESS content

### Actual result (*)

1. Markdown into LESS files

**Comment by 00F100** [comment]
Hi @00F100. Thank you for your report.
To help us process this issue please make sure that you provided the following information:

* [x]  Summary of the issue
* [X]  Information on your environment
* [X]  Steps to reproduce
* [X]  Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following Steps to reproduce. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the Magento Contributor Assistant documentation.

@00F100 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

* [X]  yes
* [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @00F100. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @00F100, here is your [Magento instance](https://i-22417-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22417-2-3-develop.instances.magento-community.engineering/admin](https://i-22417-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @00F100   i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.
