### ISSUE TITLE
After migration, I can not click "save configuration" button

### ISSUE THREAD

**Issue by qkgm828** [magento/magento2#22419]
### Summary (*)

after migration from 1.7.2 to 2.2.2, i can not click "Save and Continue" and "Save Configuration" button on Design Configuration. other buttons are clickable.

so i can not see any error message.
![save_configuration](https://user-images.githubusercontent.com/44738639/56390825-8f8eef80-61f2-11e9-81ae-0261711c8f4b.jpg)

### Examples (*)

1. Login to Admin 
2.  Content ->Design -> Configration -> click edit action -> select a Theme -> Click "Save configuration" button

### Proposed solution

Changes should be saved and refresh page

**Comment by krishprakash** [comment]
Hi @qkgm828. Thank you for your report. problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by qasimali786** [comment]
Hi
Login to Admin
Content ->Design -> Configration -> click edit action -> select a Theme -> Click "Save configuration" button

**Comment by theabeing** [comment]
maybe this helps: https://magento.stackexchange.com/questions/216029/magento-2-catalog-product-edit-save-button-not-working/309221#309221
