### ISSUE TITLE
Event is not dispatched when collecting totals on ajax request

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#2242]
We've created an observer on the event 'sales_quote_address_collect_totals_after', and it works when the page is visited the first time. But when the spinner shows (ajax?) on the shopping cart, the event is dispatched again. But now the observer never 'catches' the event?!

**Comment by Vinai** [comment]
This issue probably has to do with the are processing the request. The github issue tracker is intended for technical issues only.
Please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) for technical questions. In your case probably the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2 would ) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by rklerck** [comment]
Not sure why this is closed?
It looks like a bug in Magento. My observer works, but now when the ajax request is done in the shopping cart collecting totals..?

**Comment by Vinai** [comment]
As I've said, please reopen the issue if you believe it is a bug indeed.
But first, have you checked in which area the ajax request is processed? Is it in the frontend or webapi_rest? In what areas `events.xml` have you declared the observer? If you need more information about this please refer to the resources listed above.

**Comment by rklerck** [comment]
And how can I reopen the issue?
I declared it in frontend and admin (just to be sure). It's weird that it works when the shoppingcart is opened, but not on the ajax call.. should be the same area in my opinion.

**Comment by Vinai** [comment]
There should be a button "Reopen" below this thread. Just click that.
Different from M1, in M2 API requests have their own areas, see `app/code/Magento/Reports/etc/webapi_rest/events.xml` for example.

**Comment by rklerck** [comment]
I only knew about the frontend and adminhtml, copying the events.xml to webapi_rest folder did the trick, thanks.
