### ISSUE TITLE
wrong url redirect when edit product review from Customer view page

### ISSUE THREAD

**Issue by ketan-krish** [magento/magento2#22425]
### Preconditions (*)
1. Magento 2.3.X
2. Magento 2.2.X

### Steps to reproduce (*)
1. Navigate to Customer for edit
2. CUSTOMER INFORMATION tab -> Product Reviews -> Edit Review 
3. After edit review -> click on save

### Expected result (*)
1. After save redirect to edit Customer page

### Actual result (*)
1. After save redirect review -> product -> index

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22425-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22425-2-3-develop.instances.magento-community.engineering/admin](https://i-22425-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22425-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22425-2-2-develop.instances.magento-community.engineering/admin](https://i-22425-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99305`, `MAGETWO-99306` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ketan-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#22426 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [19e7380ec70ab4df8cc1d1704024dcce4600d24c](https://github.com/magento/magento2/commit/19e7380ec70ab4df8cc1d1704024dcce4600d24c)

The fix will be available with the upcoming 2.3.3 release.
