### ISSUE TITLE
Admin user role issues about saving blocks.

### ISSUE THREAD

**Issue by wachdai** [magento/magento2#22428]
### Preconditions (*)

Warning: array_intersect(): Argument #1 is not an array in /var/www/html/vendor/magento/module-admin-gws/Model/Models.php on line 1105
Magento 2.1.17 Commerce version
Magento instance with multiple website/store/store_view 

### Steps to reproduce (*)

1. Create an admin role with custom Roles Resource(**not all**) and limited Role Scope(**not all**). For example: If your Magento instance has 3 websites, set this role scope for 1 or 2 websites.
2. Create an admin user and assign this user belongs to a user that you created in step 1.
3. Go to backend and log in using the user you created in step 2.
4. Go to Content > Block > Edit > Save > => An error message display: Something went wrong while saving the block.

After debugging I find out that the issue comes from this function: \Magento\AdminGws\Model\Models::cmsBlockSaveBefore

* @param \Magento\Cms\Model\Block $model->getData('stores') return Null.

That why exception throws out next call:

### Expected result (*)

1. Able to save block without error message

### Actual result (*)

1. Error message display, not able to save block.

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Magento Open Source, isn't it?

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.
