### ISSUE TITLE
Change store view in admin text mismatch with remove icon issue in popup

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22435]
### Preconditions (*)
Magento 2.3.x

### Steps to reproduce (*)
1. Admin >> Reports >> Products >> Views/Best Sellers

2. Change store view from default current store

3. Review the popup design

### Expected result (*)
Text should not be mismatch with cross icon.

### Actual result (*)
![issue2](https://user-images.githubusercontent.com/49804008/56456603-2511b700-638c-11e9-9fc3-80f9fbd5dbea.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22435-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22435-2-3-develop.instances.magento-community.engineering/admin](https://i-22435-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22435-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22435-2-2-develop.instances.magento-community.engineering/admin](https://i-22435-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @bhavik43. Thank you for your report.
I'm not able to reproduce this issue.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22435-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22435-2-3-develop.instances.magento-community.engineering/admin](https://i-22435-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22435-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22435-2-3-develop.instances.magento-community.engineering/admin](https://i-22435-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
