### ISSUE TITLE
Make Relevance sort order available for sorting catalog product list through admin panel

### ISSUE THREAD

**Issue by skdsg** [magento/magento2#22437]
I am using Magento v 2.3.0 While working with the search issue I found out that magento search list the products with relevance sort order but as soon as you go to next page the default sorting option selected for product listing through admin panel takes over. Also, when you go back to page 1 via pagination the results change as they are being listed by that default option such as position, price, name.

I found the way to solve this issue through code but the results that I am getting are not as per my requirement. In fact, I am quite happy with the relevance sorting results and would like to have it as an option in the admin panel for catalog product listing as well.

Is there a way to achieve this?

**Comment by skdsg** [comment]
This is a new thing. How can I describe to reproduce it? I need some guidance here so I can start working on it. Thanks

**Comment by kalpmehta** [comment]
@skdsg Please create the issue in the required format, you can find the issue format here: https://github.com/magento/magento2/blob/2.3-develop/.github/ISSUE_TEMPLATE.md

Also make sure you can reproduce the issue in vanilla Magento 2.3 installation.

**Comment by neeta-wagento** [comment]
Dear @skdsg, 
If you want to achieve something new so please post the question https://magento.stackexchange.com/ This is the right platform to get your answers related to your customization.

Thank you!

**Comment by shikhamis11** [comment]
@skdsg Please follow issue reporting guideline to report issue.
