### ISSUE TITLE
mass update attributes with "Select All" not actually update all

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#22433]
### Preconditions (*)

1. Magento CE 2.3.1 (Composer version)
2. Enabled Developer mode
3. Sample data deployed
4. Grid settings Asynchronous indexing Disabled (default)

### Steps to reproduce (*)

1. Go to admin
2. Catalog > Products
3. In grid products select all product and select action "Update Attributes" . Grid show 2046 records found (2046 selected)
4. Choose any field for update value

### Expected result (*)

1. All products should be updated.

### Actual result (*)

1. A total of 20 record(s) were updated.

**Comment by mrtuvn** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn, here is your [Magento instance](https://i-22433-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22433-2-3-1.instances.magento-community.engineering/admin](https://i-22433-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment]
@magento-engcom-team how can i deploy sample data ?

**Comment by krishprakash** [comment]
Hi @mrtuvn. Thank you for your report.
This is duplicate to #22004 and #22414
