### ISSUE TITLE
Products are not merged in shopping cart into 1 row

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#22436]
### Preconditions (*)

1. Magento 2.2.5, Commerce Edition
2. Persistence Shopping Cart: disabled

### Steps to reproduce (*)

1. Login as customer
2. Go to category page
3. Add product to shopping cart
4. Logout 
5. Visit **product page** you added to cart
6. Add prodcut to shopping cart

### Expected result (*)

1. Either products are merged into 1 row, or there is only 1 instance of the product in shopping cart, added as loggout user.

### Actual result (*)

1. https://www.screencast.com/t/Dx6wloOvQ
2. It seems like magento merges 2 sessions into 1.
3. It only happens on Safari

I've debugged the issue to be related to Magento\Quote\Model\Quote\Item\Compare class which is not merging 2 items due to different values in **buyRequest** object.

**Comment by krishprakash** [comment]
Hi @qsolutions-pl. Thank you for your report.
This issue already fixed and merged in related PR #21375

**Comment by Ctucker9233** [comment]
@krishprakash That PR has been closed for some reason. Please link the PR that fixes this in the 2.2 branch.

**Comment by krishprakash** [comment]
Hi @qsolutions-pl. 
PR is merged for both 2.2 and 2.3
Please review  related PR: #21501
