### ISSUE TITLE
Magento version UNKNOWN

### ISSUE THREAD

**Issue by benhtn** [magento/magento2#22445]
### Preconditions 

1.  Starting with Magento 2.2.5 installed via composer on CentOS7 (centos-release-7-6.1810.2.el7.centos.x86_64) on CentOS 7 & nginx version: nginx/1.12.2, php 7.0.  My original [Magento 2.2.5 composer.json is here](https://drive.google.com/open?id=1hP6JvgbYdP6h36DrDU2Rx5qyyTgiUenW).  Config and data were migrated from a pre-existing Magento 1.9 store.
2. Upgraded php to 7.1.28 and Magento 2.3.1.  My final [composer.json is here](https://drive.google.com/file/d/1GxeA2yn0GqiMmywWTk-eaHczOTXE53cl/view?usp=sharing).

### Steps to reproduce
1.  I (believe I have) upgraded to 2.3.1 using the script method.    I hit issues along the way ([documented here](https://community.magento.com/t5/Magento-2-x-Version-Upgrades/Problems-upgrading-from-2-2-5-to-2-3-1/m-p/127326#M1900)) but eventually I have managed to run the  pre_composer_update_2.3.php script.  To do this I had to amend the composer.json with 
`"name": "magento/product-community-edition",
"version": "2.3.1",
`
Then I had to repeatedly run `composer update` and progressively run remove all the pre-existing dependancies from composer.json that conflicted with those for the new upgrade.
2. Probably not related, but, I had not installed mcrypt at this stage since it was [not mentioned here](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html), however after enabling compilation I got exception
`main.CRITICAL: Notice: Use of undefined constant MCRYPT_BLOWFISH - assumed 'MCRYPT_BLOWFISH'`
So, I installed it and after flushing caches and recompiling, both front and backends are working.

### Expected result
1. Expect to be able to retrieve a Magento version by any of these methods: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/check-version.html

### Actual result
1. I log into the admin area however at the bottom of the page I see "Magento ver. UNKNOWN".
2. Running: `bin/magento --version`
gives: "Magento CLI" 
3. I see nothing in the headers when requesting http://<magento2-store>/magento_version
4. There is no "magento/product-community-edition" mentioned in my [composer.lock](https://drive.google.com/file/d/1i28oAqwl4sNp4Fm-rvofI6OhSLpQ0NOZ/view?usp=sharing)

**Comment by ghost** [comment]
Hi @benhtn  Thank you for your report. problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by benhtn** [comment]
Where is the evidence that this is due to migration from v1 to v2 please?

**Comment by ghost** [comment]
@benhtn because i'm not able to reproduce with upgrading from 2.2.5 to 2.3.1

**Comment by ghost** [comment]
@benhtn 
![DeepinScreenshot_select-area_20190422111408](https://user-images.githubusercontent.com/40756439/56491002-c49b8a80-64ef-11e9-9645-47e7d73fa5a7.png)

**Comment by benhtn** [comment]
The thing is, prior to upgrading from 2.2.5 to 2.3.1 CE, the version was showing correctly.  Can you tell me where the system retrieves it's version code from please?  If it is db based for instance, maybe I can just set it manually and everything will be OK...?

**Comment by ghost** [comment]
@benhtn the version comes from composer package 
![DeepinScreenshot_select-area_20190422115813](https://user-images.githubusercontent.com/40756439/56492932-f7488180-64f5-11e9-9f1b-0b162ee34d1c.png)

**Comment by benhtn** [comment]
Thanks Nazar.  Could you post up the composer.json you get after upgrade please?  Just the meta package bit at the top will do.  I had to manually edit that to get the upgrade to work and maybe I did something to upset it...

**Comment by ghost** [comment]
@benhtn in the end of file composer.json you must have something like this
![DeepinScreenshot_select-area_20190422121032](https://user-images.githubusercontent.com/40756439/56493432-c10c0180-64f7-11e9-84c6-87203f81e157.png)

**Comment by ghost** [comment]
just add version

**Comment by hostep** [comment]
@engcom-backlog-nazar : what `composer.json` file are you talking about exactly? I can't be the root one, because we always strip out the version from there, and running `bin/magento --version` still reports the correct version. So I think your comment might be incorrect.

```bash
$ grep 'version' composer.json
        "magento/module-version": "*",

$ grep 'community-edition' composer.json
        "magento/product-community-edition": "2.3.1",

$ bin/magento --version
Magento CLI 2.3.1
```

**Comment by ghost** [comment]
@hostep yes you are right, version comes from root-package, 
![DeepinScreenshot_select-area_20190422150929](https://user-images.githubusercontent.com/40756439/56499887-2b7d6b80-6511-11e9-906b-9512f46051f4.png)

**Comment by hostep** [comment]
So I dug in a bit more, since I was curious :)

It looks like when you install Magento2 using composer, it searches the version in a package what Magento calls a "system package", that [is determined](https://github.com/magento/magento2/blob/2.3.1/lib/internal/Magento/Framework/Composer/ComposerInformation.php#L260-L266) if the name of that package matches the regex `magento/product-*` and then that version is used. (this regex is wrong in my opinion, it should probably be: `magento/product-.+`, but that's beside the question here).
If it can't find such a package, it assumes Magento is installed by cloning the git repo, and it will search for the version in the root `composer.json` file.
But it looks like the `version` is no longer provided in the `composer.json` file in the git repo, this got removed in: https://github.com/magento/magento2/commit/95bfd2c790f9f84c81f0f25807623d136555f7ea#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R4 (it is still there in tagged versions however, then it gets put back in place luckily).
So how does composer then figure out a version if it isn't specified in the `composer.json` file? It looks like it takes the current branch in git which is checked out, this happens in Composer's [VersionGuesser class](https://github.com/composer/composer/blob/dd40d74bf6041ddcefa1ebe46fb9117d031b1ccd/src/Composer/Package/Version/VersionGuesser.php#L98).

So summary @benhtn: 
- Check if you have one or multiple packages in your `composer.json` file which name starts with: `magento/product`. If that's the case, the version of that one should be used.
- If that isn't the case, then there is probably a problem with your `composer.json` file (see below for an example file).
- But it might also be caused by an outdated version of `composer/composer` being installed in your Magento shop (run `composer show | grep composer/composer` to see which one is installed, latest available at the time of writing is 1.8.5 for Magento 2.3.1), or even an outdated `git` version (I'm using 2.21.0).

Hope this helps somehow :)

As a reference, here is the root `composer.json` when setting up a new Magento 2.3.1 installation:
```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "magento/product-community-edition": "2.3.1"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "~2.13.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento2-functional-testing-framework": "~2.3.13",
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "3.3.1",
        "allure-framework/allure-phpunit": "~1.2.0"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "version": "2.3.1",
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

**Comment by benhtn** [comment]
Hi guys,
Many thanks for your help and curiosity @hostep and @Nazar65!

My [current composer.json is here]( https://drive.google.com/file/d/1GxeA2yn0GqiMmywWTk-eaHczOTXE53cl/view) - it looks a real mess compared to a clean install (and seems to be missing some bits) however - it does contain 
        "magento/product-community-edition": "2.3.1"
in the require section - I put it there manually in order to get the pre_composer_update_2.3.php script to work, however prior to that it was missing - as can be seen in my (Magento 2.2.25 composer.json file prior to upgrade)[https://drive.google.com/drive/folders/1kCU_umdTxNPmHPUfeg6Iuecnirqaj_Zg].

`composer show | grep composer/composer` gives
composer/composer                          1.4.1
I've updated the global composer version using `composer self-update` to 1.8.5, however the above command still gives the same?  I think I am missing something there?  Should I update composer/composer manually in the composer.json?

`git --version`
git version 1.8.3.1
I've now installed git 2.9.5 from source, however I'm not sure where to go next...?  

Do I just have to start from a clean install?

**Comment by hostep** [comment]
@benhtn: your `composer.json` files looks like a mess indeed. Honestly I would start over from a clean `composer.json` file and add your extra dependencies (`ebizmarts/sagepaysuite`, and maybe others?) to it and try again.
The fact that the version isn't showing up is probably the least of your worries based on this `composer.json` file you posted I think.

**Comment by benhtn** [comment]
Thanks @hostep - OK, what a pain!  I just wish I understood what went wrong to get it like this...
