### ISSUE TITLE
Chebox terms and conditions not showing in checkout

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2244]
I have added a terms and conditions but it is not showing up in the checkout.
Where should  I normally have to see it appear?

![2015-11-02_15h53_18](https://cloud.githubusercontent.com/assets/13572447/10884731/f8207c88-8179-11e5-8f77-e3ed9392557f.png)

![2015-11-02_15h54_14](https://cloud.githubusercontent.com/assets/13572447/10884754/171b3326-817a-11e5-9fbd-acbfefab7ddf.png)

**Comment by dfediuk** [comment]
You need to enable it not only only Terms and Conditions screen, but on store settings screen too.
It is counter-intuitive and may be should be changed but it resembles the bevabiour of Magento 1.x.

**Comment by Vinai** [comment]
If @dfediuks answer didn't resolve your issue, please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) for this type of questions. In your case probably the [admin & configuration questions forum](https://community.magento.com/t5/Admin-Configuration-Questions/bd-p/admin-config) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
