### ISSUE TITLE
Add more than available qty order placed successfully

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22443]
Add more than available qty order placed successfully

### Preconditions (*)
Magento 2.2

### Steps to reproduce (*)
1. Admin >> Add product with 1 qty
2. Sales >> Orders >> Create new order
3. Select customer and add product with 2 qty
4. Submit order 
5. Placed order successfully with 2 qty

### Expected result (*)
Order should not be placed
and error message should display.

### Actual result (*)
Order placed successfully with not available qty.

### Additional Information (*)

When enter more than available qty it displays the alert like "The requested qty is not available"
But when ignore this alert and added more than available qty then order created successfully.
Also when checked in product it displays qty in **Minus**
![Screenshot](https://user-images.githubusercontent.com/46617848/56469954-ddf3f680-645d-11e9-8793-6517619bf320.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22443-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22443-2-2-develop.instances.magento-community.engineering/admin](https://i-22443-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22443-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22443-2-3-develop.instances.magento-community.engineering/admin](https://i-22443-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99317`, `MAGETWO-99318` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by somat211** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @somat211. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @somat211, here is your [Magento instance](https://i-22443-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22443-2-3-develop.instances.magento-community.engineering/admin](https://i-22443-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tomekjordan** [comment]
This is not an issue, its standard behavior for admin orders since M1.
Until real inventory will not be introduced (with procurement managemetn) this should be normal, and its expected behavior for admin orders. Admin knows what he is doing, so he can place order even stock negative. This is just backorder and can be even considered as preorder or something.
But as I mentioned - if Magento will have true procurement management - with stock history, PO managmenet, delivery sourcing - then it should be blocked. But right know - its just normal behavior

**Comment by mallikaverma** [comment]
I am working on this at #dmcdindia1

**Comment by engcom-Bravo** [comment]
@tomekjordan, could You please provide some official documentary or may be some other proof to these of Your words: "This is not an issue, its standard behavior for admin orders since M1." Thank You.

**Comment by rparsi-boxycharm** [comment]
@tomekjordan This IS an issue...an admin (or several admins) may not always know the exact product stock situation, especially in high volume sales sites.
We do NOT use the backorders setting; (setting is disabled, `No Backorders` value in config)
What magento core code do I need to override to prevent admin created Orders that result in negative product stock quantity?

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24331` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
