### ISSUE TITLE
Issue With Text editor in magent 2.3 Show and Hide editor is not working

### ISSUE THREAD

**Issue by harsh719** [magento/magento2#22449]

**Comment by harsh719** [comment]
I have faced this problem when i edit content in CMS -> Pages.Show/hide editor doesn't work sometimes.Eventhough i have removed all content and save it doesn't work.I can't see any js error in console. So please let me know how to solve this.

**Comment by krishprakash** [comment]
Hi @harsh719. Thank you for your report.
Please add the issue description as mentioned in below guidelines:
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by harsh719** [comment]
I faced issue while opening my cms block and then scroll to a content area and text editor is not working.

**Comment by krishprakash** [comment]
Hi @harsh719. 
Yes if issue is there we will check and update you but first you need to update issue description as per magento standard so our team can work further.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22449-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22449-2-3-develop.instances.magento-community.engineering/admin](https://i-22449-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
As created same issue #22452 so I'm closing this issue.
