### ISSUE TITLE
Shopping cart total price doesn't changed after product delete from admin panel

### ISSUE THREAD

**Issue by ydaood** [magento/magento2#22454]
### Preconditions (*)

1. In Magento 2.3.1
2. Add at least two product to shopping cart

### Steps to reproduce (*)

1. Delete One of two products that in Shopping cart form admin panel
2. Check Mini cart

### Expected result (*)

1. Total Price Changed as Product deleted in mini cart

### Actual result (*)

1. Total Price doesn't Change in mini cart

**Comment by ghost** [comment]
Hi @ydaood thank  you for you report, i;m not able to reproduce following steps you described on clean magento 2.3-develop instance.
![deepin-screen-recorder_Select area_20190422163516](https://user-images.githubusercontent.com/40756439/56502938-cb8cc200-651c-11e9-9507-f9e34011fbab.gif)

**Comment by ydaood** [comment]
@engcom-backlog-nazar  Please check this issue again in mini cart only with open shopping cart page

**Comment by ghost** [comment]
@ydaood did you able to proceed order with that total ?

**Comment by ydaood** [comment]
@engcom-backlog-nazar no  it is  changed when proceed to checkout
