### ISSUE TITLE
search criteria not working for custom category attribute, magento in built attribute, as mentioned in the Api documentation.

### ISSUE THREAD

**Issue by gg24** [magento/magento2#2245]
Search criteria not working in category API for custom category attribute, Magento inbuilt attribute, as mentioned in the API documentation,I want to filter product collection on the basis of custom attributes.

**Comment by choukalos** [comment]
Feature request - internal ticket:  MAGETWO-32717

Who else wants to search by custom attributes?
What other improvements to search criteria are you looking for?

**Comment by thomasnordkvist** [comment]
@choukalos 
I would like this to work.
And i would also like if it where possible to get all categories with a custom attribute where the value is a string length>0.

I did create a list like this by going through all catagories. But that would be inefficient with large gategory trees.

/Thomas

**Comment by gg24** [comment]
Actually this is my requirement, 
https://github.com/magento/magento2/issues/2255
I am creating a custom Api for product collection which should be filter by custom attribute(Store id, Customer group Id), problem occurs on the product collection.

**Comment by thomasnordkvist** [comment]
@choukalos 
I wrongly assumed @gg24  where working with the REST api where you can't do a search for catagories via parameters searchCriteria[filterGroups][][filters][][field].... as can do with products.

/Thomas

**Comment by gg24** [comment]
I want to narrow the search in the following way,

http://magento2.magestore.com/rest/V1/products/search?searchCriteria[filterGroups][][filters][][field]=sku&searchCriteria[filterGroups][][filters][][value]=WH01&searchcriteria[filter_groups][][filters][][condition_type]=eq


http://magento2.magestore.com/rest/V1/categories/24/search?
searchCriteria[filterGroups][][filters][][field]=url_key&
searchCriteria[filterGroups][][filters][][value]=women&
searchCriteria[filterGroups][][filters][][condition_type]=eq

http://www.example.com/rest/V1/categories/24/products/search?
searchCriteria[filterGroups][][filters][][field]=custom_segmentation&searchCriteria[filterGroups][][filters][][value]=3,4&searchCriteria[filterGroups][][filters][][condition_type]=eq

so how should i filter the collection on the basis of magento attributes, custom attributes.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by gg24** [comment]
I Think i am using API as Magento2.0 documentation, but search criteria not working.

**Comment by sinamiandashti** [comment]
this should be open
really needed !

**Comment by nagaraj1121993** [comment]
just follow the following pattern

http://10.201.62.75/magento/rest/default/V1/products?searchCriteria[filter_groups][0][filters][0][field]=attribute_code{the custom attribute that you have created}&searchCriteria[filter_groups][0][filters][0][value]={value of the attribute code, ex: for attribute_code color values will be blue, red, green atc}&searchCriteria[filter_groups][0][filters][0][condition_type]=eq

**Comment by raihanruhin** [comment]
@nagaraj1121993 my pattern is:
https://{my ip}/index.php/rest/V1/rrproducts?searchCriteria[filterGroups][0][filters][0][field]=attribute_code{color}&searchCriteria[filterGroups][0][filters][0][value]={52}&searchCriteria[filterGroups][0][filters][0][condition_type]=eq

But I am getting this error in chrome's postman
  "message": "Invalid attribute name: %1",
  "parameters": [
    "attribute_code{color}"

**Comment by nagaraj1121993** [comment]
You have to share me complete details, fist of all URL is wrong. You gave
rrproducts instead of products.
