### ISSUE TITLE
Unable to unarchive an order

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento2#22458]
### Preconditions (*)
1. Magento 2.2.8
2. Have orders in your Magento store
3. Order Archiving is enabled

### Steps to reproduce (*)
1. Navigate to Sales -> Operations -> Orders
2. Select 1 order and select action "Move To Archive"
3. Navigate to Sales -> Archive -> Orders
4. Select previous order and attempt to unarchive it (There is no action)

### Expected result (*)
If an order was archived by mistake, we should be able to unarchive the order.

### Actual result (*)
1. Order is archived and impossible to unarchive.
2. Archive actions show "Remove To Archive" and I have no idea what this is supposed to be. Delete order? Remove From Archive?

**Comment by kalpmehta** [comment]
Hi @Stoyvo , this is duplicate to [#13645](https://github.com/magento/magento2/issues/13645)

Please contact Magento support from your Magento Commerce account.
