### ISSUE TITLE
Show/hide text editor is not working on magento2

### ISSUE THREAD

**Issue by harsh719** [magento/magento2#22452]
I am getting an error while opening cms block and in that, I am not able to see show/hide text editor on Magento 2 and I tried every possible solution that available on internet and GitHub but still not finding any solutions that work for me.

![Magento Issue](https://user-images.githubusercontent.com/49854559/56485260-f6f9b780-64f0-11e9-96b0-7b90b8ff8000.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22452-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22452-2-3-develop.instances.magento-community.engineering/admin](https://i-22452-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @harsh719, 
Can not reproduce this issue on clean magento instance.
Please review screencast : https://www.screencast.com/t/erhCytaDYsYa
Also please check on fresh magento instance and let us know if you phase this issue again.
Thanks.
