### ISSUE TITLE
Magento 2.2.8 Filtered search shows out-of-stock subproducts when multiple filters are chosen

### ISSUE THREAD

**Issue by AndrewPenry** [magento/magento2#22459]
### Preconditions (*)

1. Magento 2.2.8
2. Sample data installed

### Steps to reproduce (*)

1. In the admin, set all the size S simple products of the Leah Yoga Top to 0.
2. In the frontend, choose Women>Tops.
3. Select Size: S and Color: Purple from the filters.

### Expected result (*)

1. The Leah Yoga Top should not be part of the search results.

### Actual result (*)

1. The Leah Yoga Top should not be is part of the search results, with the S swatch missing. This is immediately confusing for a customer who only wants size S products.

![Capture](https://user-images.githubusercontent.com/730188/56527928-6cc74880-651c-11e9-9f43-366cde3cd614.PNG)

**Comment by AndrewPenry** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, here is your [Magento instance](https://i-22459-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22459-2-3-develop.instances.magento-community.engineering/admin](https://i-22459-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AndrewPenry** [comment]
> Hi @AndrewPenry. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [X]  Summary of the issue
> * [X]  Information on your environment
> * [X]  Steps to reproduce
> * [X]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @AndrewPenry do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [X]  yes
> * []  no

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, here is your [Magento instance](https://i-22459-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22459-2-3-develop.instances.magento-community.engineering/admin](https://i-22459-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AndrewPenry** [comment]
I was able to reproduce in 2.3-develop as well.

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22459-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22459-2-3-develop.instances.magento-community.engineering/admin](https://i-22459-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22459-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22459-2-2-develop.instances.magento-community.engineering/admin](https://i-22459-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99351`, `MAGETWO-99352` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AndrewPenry** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, here is your [Magento instance](https://i-22459-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-22459-2-2-5.instances.magento-community.engineering/admin](https://i-22459-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AndrewPenry** [comment]
I think this is a regression. We updated from 2.2.5 to 2.2.8. On 2.2.5 this issue does not reproduce. When I have some time, I'll test all the intervening releases to see when it first appeared.

**Comment by verma-ankur** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
