### ISSUE TITLE
"Add Store Code to Urls" option in store configuration

### ISSUE THREAD

**Issue by Seb33300** [magento/magento2#22450]
I would like to define an url code for both store and store view.
I expect that both url codes will be concatenated.

This could be useful to add both lang code and an other specific store code to URL.

I have 2 multilingual stores:
- public store
- professional store

I am expecting to get URL like:

`/{store-view-code}/{store-code}/`

- public:
`/en/public/`
`/fr/public/`

- professional:
`/en/professional/`
`/fr/professionnel/`

This seems to not be possible with the current configuration options.

**Comment by kalpmehta** [comment]
@Seb33300 This does not look like out of the box Magento bug. Please ask this question on https://community.magento.com/ or https://magento.stackexchange.com/

**Comment by kalpmehta** [comment]
Feel free to reopen it if you still think it is core Magento issue. Make sure you edit the issue in the acceptable format so it is easy to review. Thanks
