### ISSUE TITLE
Customer cannot reset password when DOB is required.

### ISSUE THREAD

**Issue by will-b** [magento/magento2#2246]
When a customer is created while the configuration for "Customer > Name and Address Options > Show Date Of Birth" is set to "No". If the config is then changed to have DOB as a required field then the customer is unable to reset their password.

Same issue exists in M1 with details here. http://magento.stackexchange.com/questions/29595/customer-reset-password-issue.

Would it be possible to add a "skip dob validation" flag/property on the customer model when saving?Guessing the same happens for Gender as well but have not tested that.

**Comment by piotrekkaminski** [comment]
This issue is tracked internally as MAGETWO-52672

**Comment by ilol** [comment]
Hi all,
since the required fields are literraly reqiured, the user must fill in these fiells, and the system will not allow any further action without that information. Agree?

**Comment by johnhughes1984** [comment]
Happy to open a new issue for this but I'd suggest my issue is related and they could all be resolved by the same fix potentially.

### Issue

If you have any of 'Date of Birth', 'Gender' or 'Tax/VAT Number' as a required field you also cannot create an account after checkout on the success page (see attached screenshots).

I would also assume the same is true for 'Gender' and 'Tax/VAT Number' in regards to the original password reset issue, but I have not tested.

Please note I am using Magento CE 2.1.0

![screen shot 2016-07-20 at 10 34 01](https://cloud.githubusercontent.com/assets/3949917/16982223/b1c4b10e-4e66-11e6-9302-e609e08a2b16.png)
![screen shot 2016-07-20 at 10 38 13](https://cloud.githubusercontent.com/assets/3949917/16982225/b1c78636-4e66-11e6-8c77-feca199c82bf.png)
![screen shot 2016-07-20 at 10 40 22](https://cloud.githubusercontent.com/assets/3949917/16982224/b1c74a7c-4e66-11e6-9dbd-1b705bfe2570.png)

**Comment by wert2all** [comment]
Closed as duplicate #4694
