### ISSUE TITLE
How to change the price format to Indian price format in Magento 2?

### ISSUE THREAD

**Issue by satyavir-singh** [magento/magento2#22477]
How to change the price format to Indian price format in Magento 2
Example: Price display like 453,453, want to display in the Indian manner like 4,53,453

### Preconditions (*)

1.Magento2.2.5
2.Php 7
3.Mysql 5.6
4.nginx server

**Comment by satyavir-singh** [comment]
It can be resolved by the following steps but still want a proper solution from the Magento Community?

1. File path: vendor/magento/zendframework1/library/Zend/Locale/Data/en.xml

2. On line number 3353, under section currencyFormat and type = "standard", change the pattern from  `<pattern>¤#,##0.00</pattern>` to `<pattern>¤ #,##,##0.00</pattern>`

3. Still, on PDP page and cart page summary the price format does not change because the prize format is coming from the js in which Magento using a RegExp function for only US price format.
For that, please change the code in the below file.

File path: vendor/magento/module-catalog/view/base/web/js/price-utils.js (First extend this file in your theme directory and do the respected changes.)

Under the function formatPrice below this line comment all the line in the respect function. 

 i = parseInt(
                amount = Number(Math.round(Math.abs(+amount || 0) + 'e+' + precision) + ('e-' + precision)),
                10
            ) + '';

And add this set of code below the above line.
       var x=i;
        x=x.toString();
        var afterPoint = '';
        if(x.indexOf('.') > 0)
           afterPoint = x.substring(x.indexOf('.'),x.length);
        x = Math.floor(x);
        x=x.toString();
        var lastThree = x.substring(x.length-3);
        var otherNumbers = x.substring(0,x.length-3);
        if(otherNumbers != '')
            lastThree = ',' + lastThree;
        var response = otherNumbers.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + lastThree + afterPoint;
        return pattern.replace('%s', response);


4. deploy and rm -rf var/cache/*`

5. Done

Example: A price previously displayed like 453,453, will now display in the Indian manner like 4,53,453.

**Comment by AlexWorking** [comment]
Hello @satyavir-singh. The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by satyavir-singh** [comment]
Hi @AlexWorking @m2-assistant ,

How to change the price format to Indian price format in Magento 2
Example: Price display like 453,453, want to display in the Indian manner like 4,53,453

### Preconditions (*)

1.Magento2.2.5
2.Php 7
3.Mysql 5.6
4.nginx server

### Steps to reproduce (*)

1. Magento does not provide en_IN language.
2. And even the price format is coming from js is also hard code for en_US price format only. (file path: vendor/magento/module-catalog/view/base/web/js/price-utils.js Under the function formatPrice )

### Expected result (*)

1. Want en_IN in languages so we can deploy on en_IN.
2. Price format coming from the XML and JS should be in the Indian price format like 5,12,450

I have resolved this by using the following step in the above comment (Reference link: https://github.com/magento/magento2/issues/22477#issuecomment-486160001 )
But want a  proper solution from the Magento Community?

**Comment by adjig** [comment]
Hello @AlexWorking 
I also need price format in Indian format.
How to do this?
