### ISSUE TITLE
Site going down again and again, multiple tables like 'search_tmp_54455' are created and removed in database

### ISSUE THREAD

**Issue by km9484** [magento/magento2#22476]
Site going down again and again, because some tables like "search_tmp_" are creating automatically.
this cause cpu utilization 99% and showing maximum connections to database. as a result site goes down

### Preconditions (*)
1. Magento2.2.7
2. Php 7
3. Mysql 5.6
4. nginx server

### Steps to reproduce (*)
1. Open your site 
2. go to any category page
3. print the query on category page

### Expected result (*)
1. site should work fine
2. why we are using search_tmp join on category pages

### Actual result (*)
1. sometime site going down
2. showing search_tmp in category page query

Query is this:-
`catalog_product_flat_2` AS `e` INNER JOIN `catalog_category_product_index_store2` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=2 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='15' INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 INNER JOIN `search_tmp_5cc0108165e221_57009269` AS `search_result` ON e.entity_id = search_result.entity_id WHERE (stock_status_index.stock_status = 1) ORDER BY `cat_index_position` desc, `cat_index`.`position` desc, FIELD(accessories, 1) ASC, `cat_index_position` DESC, `cat_index`.`position` DESC, `e`.`created_at` DESC, `e`.`entity_id` DESC, `cat_index_position` desc, `cat_index`.`position` desc LIMIT 12

**Comment by km9484** [comment]
yes
site is working fine but whenever any bot hit the url's like www.example.cop/dress.html?color=42&size=10
then site goes down.

**Comment by ghost** [comment]
HI @km9484 thank you for you report, i'm not able to reproduce following steps you described on clean magento 2 install, in my case all temp_ table are cleared and removed, please verify is you  user have acces to drop table? and this may be related to your custom modules.

**Comment by alexandrosk** [comment]
hello @km9484 did you manage to find an answer to this one? Seems I'm experiencing something similar

**Comment by alexandrosk** [comment]
I think it's connected to this one https://github.com/magento/magento2/issues/22587

**Comment by joaolisboa** [comment]
@alexandrosk I assume that since it's filters, they're not text/varchar attributes. If they are text/varchar those get written to those tables constantly as if they were search queries and I've had that issue basically making our production website unusable until we found out about it. This issue for me, was unrelated to the one you linked, since the issue in #22587 is an actual issue in the query being built. The patch in the issue fixes most of the issues, at least it did for me.
