### ISSUE TITLE
Bundled product pricing as configured doesn't show special price when available

### ISSUE THREAD

**Issue by tschirmer** [magento/magento2#22488]
### Preconditions (*)

1. Magento 2.3.1
2. php 7.1.27

### Steps to reproduce (*)

1. Setup a bundled product with a radio select box option with definable qty by the end user
2. Add special price to the bundled product

### Expected result (*)

1. ![MagentoBug-expected](https://user-images.githubusercontent.com/3872130/56706620-07ac6680-6759-11e9-8cbd-1b1d3dc65d74.png) This has some var_dumps during debugging (that's what the configured base price and configured special price are in this example).
2. See that the configured price has the special contained in it.

### Actual result (*)

1. ![MagentoBugpng](https://user-images.githubusercontent.com/3872130/56706669-2d397000-6759-11e9-866d-dc299c6f6510.png)
2. This is what's happening instead. Only 1 price is being included in the html markup

**Comment by tschirmer** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tschirmer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tschirmer, here is your [Magento instance](https://i-22488-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22488-2-3-develop.instances.magento-community.engineering/admin](https://i-22488-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tschirmer** [comment]
This is replicated on the test instance. Special price does not appear in customisation:
https://i-22488-2-3-develop.instances.magento-community.engineering/catalog/product/view/id/3/

**Comment by tschirmer** [comment]
Bundled Option Product setup in default Magento sandbox:
![MagentoBugBundleSetup](https://user-images.githubusercontent.com/3872130/56707856-f6198d80-675d-11e9-969b-fa544571e4de.png)

Product pricing discount setup in default Magento sandbox:
![MagentoBugBundleSetupDiscount](https://user-images.githubusercontent.com/3872130/56707944-4abd0880-675e-11e9-9078-5e3d73c34e30.png)

Discount not showing in frontend on customisation:
![MagentoBugBundleFrontend](https://user-images.githubusercontent.com/3872130/56707885-121d2f00-675e-11e9-9fdb-2ce0651d8fb9.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22488-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22488-2-3-develop.instances.magento-community.engineering/admin](https://i-22488-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tschirmer** [comment]
As a temp workaround, we can load via the regular price, not the configured regular price:

vendor/magento/module-catalog/view/base/templates/product/price/configured_price.phtml
change:
```
$configuredPrice = $block->getPrice();
/** @var \Magento\Catalog\Pricing\Price\ConfiguredRegularPrice $configuredRegularPrice */
$configuredRegularPrice = $block->getPriceType(
    \Magento\Catalog\Pricing\Price\ConfiguredPriceInterface::CONFIGURED_REGULAR_PRICE_CODE
);
```
to:
```
$configuredPrice = $block->getPrice();
/** @var \Magento\Catalog\Pricing\Price\ConfiguredRegularPrice $configuredRegularPrice */
$configuredRegularPrice = $block->getPriceType(
    \Magento\Catalog\Pricing\Price\RegularPrice::PRICE_CODE
//\Magento\Catalog\Pricing\Price\ConfiguredPriceInterface::CONFIGURED_REGULAR_PRICE_CODE
);
```

**Comment by krishprakash** [comment]
Hi @tschirmer,
We set special price in % for bundle product which is directly calculated in bundle child products while we add Customize product.
So i think it is proper.
Please let me know your thoughts.
Thanks.

**Comment by tschirmer** [comment]
I don't think that's what's intended after reading the code here. 

On the first page load, the html markup should give us the 2 prices when there's a discount on the bundled product, so that when the javascript updates it, it'll have the markup to inject the price into. At the moment that html markup is missing so if you add a combination of goods that result in a special price, it's not shown as a special price in the customisation.

**Comment by krishprakash** [comment]
Hi @tschirmer,
This is not an issue because price calculation is working properly on front end.
This should be consider as feature request.

**Comment by tschirmer** [comment]
I wouldn't say the price calculation is working correctly, even though the price is correct on the frontend.

The code is expecting to show a discount and the processing of the configuredRegularPrice is showing an incorrect price (it's calculating it with the discount, which means it's always matching the first price).

**Comment by tschirmer** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tschirmer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tschirmer, here is your [Magento instance](https://i-22488-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22488-2-3-develop.instances.magento-community.engineering/admin](https://i-22488-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @tschirmer 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

**Manual testing scenario:**
1. Go to the Catalog-->Products
2. Press "Add bundled product" button
3. Set configuration:
**Advanced price:**
![image](https://user-images.githubusercontent.com/51680850/66294908-cf59a880-e8f2-11e9-9322-953062cb192e.png)
**Bundled Items:**
![image](https://user-images.githubusercontent.com/51680850/66294943-eb5d4a00-e8f2-11e9-9bfe-756e1e4fa6e7.png)

4. Save 
5. Go to the product front page  

**Actual result:**
Special and regular prices are displayed
![image](https://user-images.githubusercontent.com/51680850/66294504-d16f3780-e8f1-11e9-93b6-4fc1de148c92.png)

So i have to close this issue.

**Comment by elisei** [comment]
Hi

@magento-engcom-team give me 2.3-5 instance

**Comment by magento-engcom-team** [comment]
Hi @elisei. Thank you for your request. I'm working on Magento 2.3-5 instance for you
