### ISSUE TITLE
Discount keep exclude shipping tax even if shipping tax included

### ISSUE THREAD

**Issue by tnsezer** [magento/magento2#22480]
### Preconditions (*)

Magento 2.3.1 community edition

Settings:
https://ibb.co/GsPrwt1
https://ibb.co/LzjN2RZ
https://ibb.co/yQ1CKVS

### Steps to reproduce (*)

1. Created a cart price rule which applies shipping amount and affects the whole cart
2.Added a product which 155 pounds and shipping is fixed price 5 pound
3. Applied discount code 

### Expected result (*)

1. Needs to reduce whole price and grand total must be 0

### Actual result (*)

1. It seems to reduce the tax from shipping price then apply discount
2. https://ibb.co/mzvzQPP

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22480-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22480-2-3-develop.instances.magento-community.engineering/admin](https://i-22480-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @tnsezer. Thank you for your report.
Issue is duplicate to #21456
