### ISSUE TITLE
Sales Email does not arrive

### ISSUE THREAD

**Issue by colettamatteo98** [magento/magento2#22482]
### Preconditions (*)

 Magento ver. 2.3.1
### Steps to reproduce (*)

Checkout

### Expected result (*)

New Order email should arrive.

### Actual result (*)

New Order email does not arrive.

**Comment by shikhamis11** [comment]
Hi @colettamatteo98 , Thank you for your report
I have checked the issue at magento 2.3.1 version also magento 2.3-develop version . I am not able to reproduce the issue. Please make sure you have setup mails on your server & also order emails are enabled from magento backend sales configuration
