### ISSUE TITLE
error magento 2.3.1 in catalog (product list)

### ISSUE THREAD

**Issue by Eduardosys** [magento/magento2#22489]
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later in Magento 2.3.1

The Product Catalog is displaying this error and does not open the product list. Magento 2.3.1.

**Comment by AlexWorking** [comment]
Hello @Eduardosys. Thank You for reporting. Please provide more information on Your issue and put it out in the way described by the bot under Your post. Install a fresh magento2 instance and describe us every step You take in order to get that issue reproduced.

**Comment by Eduardosys** [comment]
There is not much to talk about. When I click on Catalog> Product it does not open the list of products and this error "A technical problem with the server created an error. On the screen the spinner is spinning and it does not go away.

**Comment by Eduardosys** [comment]
Already done for SSH
php -dmemory_limit = 5G bin / magento setup: upgrade
php -dmemory_limit = 5G bin / magento indexer: reindex
php -dmemory_limit = 5G bin / magento setup: di: compile
php -dmemory_limit = 5G bin / magento setup: static-content: deploy -f
php -dmemory_limit = 5G bin / magento cache: clean
php -dmemory_limit = 5G bin / magento cache: flush
Everything was 100% correct.

**Comment by AlexWorking** [comment]
@Eduardosys But would You please confirm that the same error happens to You with the newly installed instance of magento2 , empty of products, customers and other acquired objects , having no third party extensions etc., just re-indexed and cache-flushed after having been installed?

**Comment by Eduardosys** [comment]
do upgrade from magento 2.3 to magento 2.3.1

**Comment by Eduardosys** [comment]
I deleted the registered products and the problem continues.

**Comment by Eduardosys** [comment]
I deleted from MySQL

**Comment by AlexWorking** [comment]
@Eduardosys It's not exactly what we meant.  Please try to deploy on Your server another instance taking code from official magento sources like github or magento.com, so that code does not contain any third party extensions. And use a newly created database for that instance. With that we've been trying now to reproduce your issue updating 2.3 version to 2.3.1.

**Comment by Eduardosys** [comment]
When I click on Catalog> Product in keywords appears several commas and in pages appears 20,20,20,20 and gives the error

**Comment by Nazar65** [comment]
Hi @Eduardosys 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site

**Comment by Eduardosys** [comment]
I understand that the problem is in the new magento 2.3.1. It is difficult to perform such a procedure by installing from scratch. I do not know if it can be the prefix used in the mysql tables.

**Comment by Eduardosys** [comment]
I already figured out where the error is. You are in the search for products.

**Comment by AlexWorking** [comment]
@Eduardosys We've just obtained a successful upgrade from 2.3 to 2.3.1. It's most likely that the issue You are facing is caused by some custom changes or adds to the code of Your magento2 instance. For such we can not take a responsibility. Please  try to refer to the forums as it was aforementioned.

**Comment by Eduardosys** [comment]
ok Alex however I insist that I did not make any customization in magento 2.3.1. I just got the copy and it was installed on the server and gave this error.

**Comment by Eduardosys** [comment]
Alex just to inform you that the error is happening only in Chrome Browser. I opened by firefox and ran normal.
