### ISSUE TITLE
Will remaining todo's be solved/closed in 2.3.2?

### ISSUE THREAD

**Issue by seansan** [magento/magento2#22486]
### Summary (*)
Coming from M1 where the code was quite full of TODO's: is there any planning to clean up all TODO annotations? Either do the code or remove the TODO?

### Examples (*)

![image](https://user-images.githubusercontent.com/652395/56683157-485e9e00-66cd-11e9-88a2-5ecad339a807.png)

### Proposed solution
Fix code or remove todo

**Comment by orlangur** [comment]
@seansan no. Feel free to refactor code related to any of them or remove outdated ones.

**Comment by AlexWorking** [comment]
Hi @seansan 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
