### ISSUE TITLE
Each method must have a docblock

### ISSUE THREAD

**Issue by seansan** [magento/magento2#22483]
### Preconditions (*)
M2.3.1 on php72

### Steps to reproduce (*)
1. Have an error somewhere in a docblock
2. run setup:upgrade

### Expected result (*)
1. docblock warning telling me WHERE in the code/function/file there is something wrong

### Actual result (*)
1. General warning like below, but not specific enough to act on it

### Possible improvement
Show calling method, class and filename for better debugging/development

`Each method must have a doc block.
See Magento\Eav\Api\AttributeSetRepositoryInterface::getList()`

added by ourselves
`
```
contents:     public function getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria);
params: Parameter #0 [ <required> Magento\Framework\Api\SearchCriteriaInterface $searchCriteria ]
string:Method [ <user> abstract public method getList ] {
  @@ /var/www/html/m2/m2_dev/vendor/magento/module-eav/Api/AttributeSetRepositoryInterface.php 26 - 26

  - Parameters [1] {
    Parameter #0 [ <required> Magento\Framework\Api\SearchCriteriaInterface $searchCriteria ]
  }
}
```
`

triggered in code here

````
    private function getMethodReturnAnnotation(MethodReflection $methodReflection)
    {
        $methodName = $methodReflection->getName();
        $returnAnnotations = $this->getReturnFromDocBlock($methodReflection);
        if (empty($returnAnnotations)) {
            // method can inherit doc block from implemented interface, like for interceptors
            $implemented = $methodReflection->getDeclaringClass()->getInterfaces();
            /** @var ClassReflection $parentClassReflection */
            foreach ($implemented as $parentClassReflection) {
                if ($parentClassReflection->hasMethod($methodName)) {
                    $returnAnnotations = $this->getReturnFromDocBlock(
                        $parentClassReflection->getMethod($methodName)
                    );
                    break;
                }
            }
            // throw an exception if even implemented interface doesn't have return annotations
            if (empty($returnAnnotations)) {
                throw new \InvalidArgumentException(
                    "Method's return type must be specified using @return annotation. "
                    . "See {$methodReflection->getDeclaringClass()->getName()}::{$methodName}()"
                );
            }
        }
        return $returnAnnotations;
    }

```
    /**
     * Parses `return` annotation from doc block.
     *
     * @param MethodReflection $methodReflection
     * @return ReturnTag
     */
    private function getReturnFromDocBlock(MethodReflection $methodReflection)
    {
        $methodDocBlock = $methodReflection->getDocBlock();
        if (!$methodDocBlock) {
            throw new \InvalidArgumentException(
                "Each method must have a doc block. "
                . "\nSee {$methodReflection->getDeclaringClass()->getName()}::{$methodReflection->getName()}()"
                    . "\ncontents: {$methodReflection->getContents()} "
                        . "\nparams: " . implode("|",$methodReflection->getParameters())
                            . "\nstring:{$methodReflection->toString()} "
            );
            // . "proto:" . implode("|", $methodReflection->getPrototype())
        }
        return current($methodDocBlock->getTags('return'));
    }`

**Comment by seansan** [comment]
Yes done. BTW the buttons above in the autocomment are not "clickable"

**Comment by pixiemediaweb** [comment]
we're getting variations of this 'doc block is required' error with 2.3.1 as well - narrowed it down php opcache. Check this setting in /etc/php.d/opcache.ini;

; If disabled, all PHPDoc comments are dropped from the code to reduce the
 ;size of the optimized code.
opcache.save_comments=0

This needs to be set to 1 or magento 2.3.1 will throw many variants of the 'doc block is required' error

**Comment by seansan** [comment]
Amazing!

We came to the exact same conclusion today. Cost us 2 days.

I do think this issue should stay open because I think it is wise to add a
INI settings check for this value I have heard several developers now who
ran into it

So if opcache skip comments ini setting is enabled

then raise warning

**Comment by ghost** [comment]
Hi @seansan thank you for you report i'm closing this one as i'm not able to reproduce on clean install and, this settings set to 1 with default configuration. thanks for collaboration.
![DeepinScreenshot_select-area_20190426135818](https://user-images.githubusercontent.com/40756439/56803647-dfda0300-682b-11e9-8550-2aae3ade2468.png)

**Comment by seansan** [comment]
The answer is given here:
https://magento.stackexchange.com/questions/271048/magento-2-2-3-1-each-method-must-have-a-doc-block-see-magento-eav-api-attri

We advise Magento2 adds a check for the existance of this INI setting

(it has caused developers a LOT of time to discover this - which feels
logical afterwards - but M2 telling the developer this really solves a lot)

Quick win

**Comment by seansan** [comment]
see my comment

is is not about the quick INI fix: it is about check for the setting

**Comment by ghost** [comment]
@seansan ok, but as i know from all default installs on unix systems this options always sets to default, i think its better to create issue or PR on devdocs to explain that this option should be set to 1

**Comment by seansan** [comment]
Some M1 optimizations would advice to skip the comments
I think these admin/developers/users are the  ones commonly affected
