### ISSUE TITLE
Inconsistency: the «adminhtml_cms_page_edit_tab_content_prepare_form» event is fired on a backend CMS page form creation, but no any event is fired on a backend CMS block form creation

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2248]
An event on a backend CMS page form creation:

https://github.com/magento/magento2/blob/f578e54e093c31378ca981cfe336f7e651194585/app/code/Magento/Cms/Block/Adminhtml/Page/Edit/Tab/Content.php#L99

No any event on a backend CMS block form creation:
https://github.com/magento/magento2/blob/c743dec47b2e5de036eb5638fec44a54bfb31040/app/code/Magento/Cms/Block/Adminhtml/Block/Edit/Form.php#L61-L158

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Inconsistency-the-adminhtml-cms-page-edit-tab-content-prepare/idi-p/45375).
