### ISSUE TITLE
Customer not logged to other stores in multistore setup, session ID params passed in URL

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#22496]
### Preconditions (*)

1. Magento Commerce 2.2.x
2. Multistore Setup, (4 stores, 4 different websites - 4 URLs)
3. Set Customer Account Sharing Options to "global"

### Steps to reproduce (*)

1. Create multistore setup and create customer account
2. Login
3. Store customer session id somewhere (copy to clipboard)
4. Visit 2nd (3rd / 4th) website and add "?SID=jtgm4ejhbkr5t22e25197mj3g3" in the URL

### Expected result (*)

1. Customer is logged in to second (and other) website
2. Customer private content is refreshed
3. Customer is always logged in when browsing other websites

### Actual result (*)

1. Customer private-section blocks are loaded (My Account, mini cart) 
2. When you click anywhere else in the store (category link / go to product page) and there is no SID param in the URL, customer is being logged 

Hope I made the description clear :-)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99433` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by orlangur** [comment]
@qsolutions-pl what's wrong with actual result? Besides SID in URL, there are also cookie-based checks to avoid CSRF attacks.

**Comment by jakwinkler** [comment]
@orlangur in my opinion customer should be logged in to all websites when account is shared between websites.

**Comment by orlangur** [comment]
@qsolutions-pl again: this should not work when you type link with SID in another browser but should work in the same. Please provide more details on why actual result seems not correct.

**Comment by jakwinkler** [comment]
@orlangur  ok, so how can we make this work? (logged to multiple websites)

**Comment by orlangur** [comment]
@qsolutions-pl using some SSO, for example, OAuth.

Login by SID only must not occur as it would lead to https://en.wikipedia.org/wiki/Cross-site_request_forgery
