### ISSUE TITLE
Inconsistency: the «cms_page_prepare_save» event is fired by a controller on a CMS page saving in the backend, but no any similar event is fired on a CMS block saving

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2249]
Similar to https://github.com/magento/magento2/issues/2248

The «cms_page_prepare_save» event firing :

https://github.com/magento/magento2/blob/f578e54e093c31378ca981cfe336f7e651194585/app/code/Magento/Cms/Controller/Adminhtml/Page/Save.php#L57-L60

There is no similar event for block:
https://github.com/magento/magento2/blob/f578e54e093c31378ca981cfe336f7e651194585/app/code/Magento/Cms/Controller/Adminhtml/Block/Save.php#L16-L59

**Comment by andimov** [comment]
@mage2pro
Could you please add the description of steps, actual result and expected result to this ticket?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Inconsistency-the-cms-page-prepare-save-event-is-fired-by-a/idi-p/45373).
