### ISSUE TITLE
Magento\Email\Model\Transport only accepts Message implementation instead of interface

### ISSUE THREAD

**Issue by bcerban** [magento/magento2#22494]
### Summary (*)

Class `Magento\Email\Model\Transport` requires a `Magento\Framework\Mail\Message` in the constructor ([see here](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Email/Model/Transport.php#L73)), but the `Magento\Framework\Mail\MessageInterface` should be used instead. The `TransportBuilder` object responsible for instantiating the transport requires and passes on a `MessageInterface` object ([see here](https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php#L108)). 

* This breaks extensibility since the message object can't be swapped. 
* This was already fixed in the 2.3 branch. 

### Examples (*)

To test this, define a custom `MessageInterface` implementation, and inject it via `di.xml` with 
```xml
<preference for="Magento\Framework\Mail\MessageInterface" type="MyCompany\MyModule\Model\Message"/>
```

When trying to send and email, you will get the following error:
```
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Transport::__construct() must be an instance of Magento\Framework\Mail\Message, instance of MyCompany\MyModule\Model\Message\Interceptor given
```

### Proposed solution

Change message dependency in constructor for `Magento\Email\Model\Transport`, from `Magento\Framework\Mail\Message` to `Magento\Framework\Mail\MessageInterface`.

**Comment by engcom-Bravo** [comment]
This issue is fixed on 2.3.x branches(i tried to reproduce on 2.3-develop).
