### ISSUE TITLE
Cron Observer currentTime calculation change to make it cleanly extendable

### ISSUE THREAD

**Issue by gody01** [magento/magento2#22500]
### Summary (*)
We have user story requirement to run Cron jobs in local time instead 'UTC' for synchronization issues with external processes.

As we tried to extend Observer we found that it is cumbersome, as private and protected functions are used. Function execute and saveSchedule has to be changed for customization which can brake functionalitiy changes in the future.

However, we found simple and clean solution which require minimal change in core code (described below)

### Examples (*)
Cron jobs are run at UTC time. However in DayLight saving time environement some customers needs to run cron jobs on local time or even on some other timezone.

### Proposed solution
We found out that if we introduce public method getCurrentTime and replace:
$currentTime = $this->dateTime->gmtTimestamp();
with 
$currentTime = $this->getCurrentTime();

Method getCurrentTime being just:

    public function getCurrentTime ()
    {
        return $this->dateTime->gmtTimestamp();
    }

Observer becomes cleanly extendable without any architectural change or risk of break on upgrades.

Extension for extending Observer to run jobs at localtime is then very simple and clean (will put example on github)

We also prepared pull request wich will be attached to this issue.

**Comment by engcom-Charlie** [comment]
Hello @gody01 
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!
