### ISSUE TITLE
How do override block?

### ISSUE THREAD

**Issue by xanka** [magento/magento2#2250]
i  created Block override but i not success. [visit link view code](http://magento.stackexchange.com/questions/88652/overriding-block-issues)

**Comment by chaluvadiswamy** [comment]
Me too Face same issue , i have tried with preference tag  but no result

**Comment by Vinai** [comment]
In the pasted code there seems to be a typo in the template file name.

That said, the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) is indeed the right place for technical questions such as yours. This github repository is intended for tracking code bugs.
For the forums, in your case probably the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2 would ) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
