### ISSUE TITLE
Simple products  are removed from configurable on product import

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#22507]
### Preconditions (*)

Magento 2.3.1

### Steps to reproduce (*)

1. Add options to product attribute color - red, black, green
![color   Product Attributes   Attributes   Stores   Magento Admin](https://user-images.githubusercontent.com/8502721/56805368-81178800-6831-11e9-8a1e-dc6803234aa9.png)

2. Create a configurable product with 2 products attached:
sku = test_csv_color-red, color = red; 
sku = test_csv_color-black, color = black
![Test conf 1   Products   Inventory   Catalog   Magento Admin](https://user-images.githubusercontent.com/8502721/56805153-c7b8b280-6830-11e9-8e35-a43e9496cd4a.png)

3. Create a csv file that has update for color attribute for just created products:
sku,color
test_csv_color-red,green

4. Import csv file (System->Import, select Entity Type = Products, Import Behavior = Add/Update)
5. Check the configurable product

### Expected result (*)

Configurable product must have 2 products attached:
sku = test_csv_color-red, color = green; 
sku = test_csv_color-black, color = black

### Actual result (*)

Configurable product has only 1 product attached:
![Test conf 1   Products   Inventory   Catalog   Magento Admin2](https://user-images.githubusercontent.com/8502721/56805584-35b1a980-6832-11e9-99a3-1360fa9526dc.png)

Note: If you update color for a child product manually in admin panel it stays assigned to the configurable, so we do expect the same behaviour for product import

**Comment by AlexWorking** [comment]
Hello @lyusya-nnn . Thanks for reporting. This issue has been fixed in the develop version and will be available in the next 2.3 release version.
