### ISSUE TITLE
Insert variable in existing Email Template

### ISSUE THREAD

**Issue by stoutik** [magento/magento2#22502]
### Preconditions (*)

1. Magento CE 2.3.1

### Steps to reproduce (*)

1. Navigate to Admin
2. Go to : Marketing > Communication > Email Templates >
3. Click to edit an existing template
4. Click button "Insert Variable..."
5. Show browser console

### Expected result (*)

1. Modal with listing variables

### Actual result (*)

1. Nothing
![image](https://user-images.githubusercontent.com/10999921/56791936-a774fd80-6808-11e9-83e3-cb099cf39bbc.png)
### Proposed solution
- In /vendor/magento/module-email/Block/Adminhtml/Template/Edit/Form.php (Line 114).
$this->serializer->serialize($this->getVariables()) this line return an object.
- In /vendor/magento/module-email/view/adminhtml/web/js/variables.js (Line 53)
variables.each(function (variableGroup) {..., each function not working with Object, use for or other looping method.

**Comment by krishprakash** [comment]
Hi @stoutik. Thank you for your report.
Issue is duplicate to #20111
