### ISSUE TITLE
Search suggestion panel overlapping on advance reporting button

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#22506]
### Preconditions (*)
1. Admin panel magento 2.3

### Steps to reproduce (*)
1. Log into the admin panel 
2. Click on search icon form the dashboard
3. Enter any Search keyword (Email Id)  
4. Search result pop-up overlapping on advanced reporting button 

### Expected result (*)
1. After entering sample data in the search box then the system should not be overlapped pop-up on advanced reporting button.

### Actual result (*)
1. Search result pop-up should not be overlapped on advanced reporting.

![search](https://user-images.githubusercontent.com/47663332/56803486-61d42700-6840-11e9-9602-12dd8d6e44ca.png)

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22506-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22506-2-3-develop.instances.magento-community.engineering/admin](https://i-22506-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.2-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22506-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22506-2-2-develop.instances.magento-community.engineering/admin](https://i-22506-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Issue reproduce in Magento 2.2 and Magento 2.3 Instance:

Magento 2.2
![2 2](https://user-images.githubusercontent.com/24711761/56803978-db204980-6841-11e9-9ac5-1c6b138cc254.png)

Magento 2.3
![2 3 Magento](https://user-images.githubusercontent.com/24711761/56803989-e3788480-6841-11e9-9287-56962cdaec6d.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99428`, `MAGETWO-99429` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dev-ajaysaini** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini, here is your [Magento instance](https://i-22506-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22506-2-3-develop.instances.magento-community.engineering/admin](https://i-22506-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-22506-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22506-2-3-develop.instances.magento-community.engineering/admin](https://i-22506-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by solwininfotech** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
Hi @GrishmaNayee. Thank you for your report. 
The issue has been fixed in magento/magento2#23151 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [15b5cac75555ded4b9a8ddcf6ab7c756dea8a23a](https://github.com/magento/magento2/commit/15b5cac75555ded4b9a8ddcf6ab7c756dea8a23a)

The fix will be available with the upcoming 2.2.10 release.
