### ISSUE TITLE
Checkout page_Cancel link is not working in the payment section 

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#22508]
### Preconditions (*)
1. Admin panel Magento 2.3

### Steps to reproduce (*)
1. Log in Or Create an Account.
2. Add the Downloadable Product in the Mini cart 
3. Go to the Checkout page.
4. Select any the Payment method 
5. The system will open the address fields
4. Click on Cancel link.

### Expected result (*)
1. When user link on the cancel link system should redirect to the previous page. Open Address section should be closed. 

### Actual result (*)
1. Click on cancel button system is not closing the address section. 

![Cancelbutton_Issue](https://user-images.githubusercontent.com/47663332/56808850-1d508780-6850-11e9-8737-8f5c26a9b509.png)

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22508-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22508-2-3-develop.instances.magento-community.engineering/admin](https://i-22508-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.2-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22508-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22508-2-2-develop.instances.magento-community.engineering/admin](https://i-22508-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Cancel button is not available in Magento 2.2 and Magento 2.3 Instance.

Issue not reproduced in Magento 2.2 and Magento 2.3 Instance.

Magento 2.2
![2 2 Cancel button issue](https://user-images.githubusercontent.com/24711761/56811517-83400d80-6856-11e9-99cb-b58ea47c3f77.png)

Magento 2.3
![2 3 Cancel button](https://user-images.githubusercontent.com/24711761/56811534-8affb200-6856-11e9-8fac-8eb607fbc9df.png)
