### ISSUE TITLE
2FA Magento Admin - does not remember devices

### ISSUE THREAD

**Issue by mrlerch** [magento/magento2#22509]
### Preconditions (*)

1. Magento 2.3.1
2. CentOS Linux release 7.6.1810, nginx/1.15.12, 5.7.24-27 Percona Server, PHP 7.2.17 FPM

### Steps to reproduce (*)

1. Enable 2FA in Magento admin for your account
2. Log in with your account.
3. Enter 2FA code, and check the "remember me" box
4. Work in Magento as usual for a day or so
5. at a point you will be prompted to enter the 2FA again, even though you elected to rember the device.

### Expected result (*)

1. When I check the "remember me" box when entering 2FA on a device I would expect that this device/browser will not be prompted for the 2FA code
2.

### Actual result (*)

1. After a while the login prompt will ask for 2FA again.
2.

**Comment by sdzhepa** [comment]
Hello @mrlerch 


Unfortunately, we not able to reproduce the issue.
Probably, some important preconditions or steps were missed.

Could you please provide more details?


We tried to reproduce it by next steps


## Preconditions

1. Install a vanilla instance of the last version of Magento using Composer. [Used steps from DevDocs](https://devdocs.magento.com/guides/v2.3/install-gde/composer.html)	 
2. Login to Admin
3. Go to Stores > Configuration > Security > 2FA
4. Enable 2FA using "Google Authenticator"
5. Save Config and Flush Caches
6. Scan QR-code using mobile device and input "Authenticator code"
7. Click "Confirm" button
8. Logout and Sign In again
9. Input "Authenticator code" again
10. Select "Trust this device, do not ask again"

## Verified cases 

**Case 1: "Admin Session Lifetime (seconds)**
1. Login and wait till Admin Session Lifetime will be expired. According to setting "Stores > Configuration > Advanced > Admin > Security" - "Admin Session Lifetime (seconds)"
2. After it, log in again

**Result**:  2FA did not ask again "Authenticator code"

**Case 2: "Admin Account Sharing"**
1. Be sure that "Admin Account Sharing" = No. "Stores > Configuration > Advanced > Admin > Security"
2. In Browser_1: Login as admin user
3. Open another browser(Browser_2) and login as the same admin user
4. Login in Browser_1 again as admin user
**Result**:  2FA did not ask again "Authenticator code"



**Case 3: "Use additional admin user"**
1. Create new admin user
2. Enable/configure 2fa for the new user(scan code, login, re-login and select "Trust this device, do not ask again"
3. Relogin
4. Wait till "Admin Session"
**Result:**  2FA did not ask again "Authenticator code"

**Case 4: "Disable and enabled again 2fa"**
1. Go to admin 
2. Go to Stores > Configuration > Security > 2FA
3. Set "Enable Two Factor Auth"  = No
4. Save Config and flush caches
5. Sign Out and the Sign in
6. Go to Stores > Configuration > Security > 2FA
7. And enable 2fa again
8. Save Config and flush caches
9. Check case with Admin Session Lifetime 
10. Check case "Use additional admin user"

**Result**:  2FA did not ask again "Authenticator code"

**Case 5:  "Reset Providers: Reset Google Authenticator"**
1. Login as test admin
2. Go to "System > All USers"
3. Open for edit test admin user with enabled Authenticator
4. Click "Reset Google Authenticator" and Confirm
5. Scan QR code again using app on mobile device
6. Input received from mob.device code and confirm
7. Sign Out and Sing In
8. Check case with Admin Session Lifetime
9. Check case "Use additional admin user"

**Result:**  2FA did not ask again "Authenticator code"



**Case 6: "Revoke Trusted devices"**
1. Login as test admin
2. Go to "System > All USers"
3. Open for edit test admin user with enabled Authenticator and trusted devices
4. Click "Revoke" for trusted devices using for testing
5. Fill "Authenticator code" from app and select "Trust this device, do not ask again"
6. Sign Out and Sing In
7. Check case with Admin Session Lifetime 
8. Check case "Use additional admin user"

**Result**:  2FA did not ask again "Authenticator code"

**Comment by mrlerch** [comment]
Hello sdzhepa, thank you for your time to respond. I will go down your list and try all the suggestions and get back to you. Thank you.

**Comment by sdzhepa** [comment]
Closed due to no activities for the log time.
Feel free to reopen this issue with additional details at this moment we cannot reproduce it by provided steps

**Comment by gulshankumar** [comment]
Remember device checkbox is missing in latest versions 2.4.4+
