### ISSUE TITLE
B2B - Company Edit Profile - full page cache

### ISSUE THREAD

**Issue by ipascual** [magento/magento2#22517]
### Preconditions (*)
1. B2B Company activated

### Steps to reproduce (*)
1. Disable Rewards Points from Stores > Configuration
2. Enable Full Page Cache
3. Login in FrontEnd as Company administrator
4. Click on Company Profile

### Expected result (*)
1. See Company Profile Index view

### Actual result (*)
```
Fatal error: Uncaught Error: Call to a member function getCompanyName() on null
vendor/magento/module-company/view/frontend/templates/company/management/profile/index.phtml:23
```

### Reason
Reward block has `cacheable=false`. But without this block active, Magento\PageCache\Model\DepersonalizeChecker is removing user from context. 
Magento Company Profile Edit is getting company from UserContext, with FPC activated, customerId and company will be removed from context.

### Solution
``` 
<block class="Magento\Company\Block\Company\CompanyProfile" name="company_profile"
	                   ifconfig="btob/website_configuration/company_active"
	                   template="company/management/profile/edit.phtml"
	                   cacheable="false"
	            />
```
```
<block class="Magento\Company\Block\Company\CompanyProfile" name="company_profile"
	                   ifconfig="btob/website_configuration/company_active"
	                   template="company/management/profile/index.phtml"
	                   cacheable="false" />
	        </referenceContainer>
```

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-22517-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22517-2-3-develop.instances.magento-community.engineering/admin](https://i-22517-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Magento Open Source, isn't it?

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.
