### ISSUE TITLE
Magento 2 does not adhere to Redis security protocols.

### ISSUE THREAD

**Issue by muckee** [magento/magento2#22519]
### Preconditions (*)

1. Magento 2 - all versions
2. Any distribution which utilises Redis

### Steps to reproduce (*)

1. Install redis-server and rename dangerous commands
2. Install magento

### Expected result (*)

1. Some configuration option should be available to assign custom command names to redis commands.

### Actual result (*)

1. Cache management is not properly functional due to Magento's inability to recognise custom commands.

It is noted in the redis documentation that altering dangerous command names is absolutely vital, but magento offers no out-of-the-box option to do this. Although technically not a bug, the magento software lacks vital functionality and therefore is not fit for purpose.

How can I reconfigure magento to use renamed redis commands?

**Comment by muckee** [comment]
@magento-engcom-team it is not possible to replicate this issue without the ability to rename redis commands.

**Comment by orlangur** [comment]
@JoshuaFlood please report in https://github.com/magento/community-features/issues.
