### ISSUE TITLE
/checkout/cart/add

### ISSUE THREAD

**Issue by aaron-renovationbrands** [magento/magento2#22515]
### Preconditions (*)

1. Magento ver. 2.1.9 update to Magento ver. 2.1.17

### Steps to reproduce (*)

1. composer require magento/product-community-edition 2.1.17 --no-update
2. composer update
3. Hit [HOST]/checkout/cart/add

### Expected result (*)

1. 302 Redirect to [HOST]/checkout/cart/

### Actual result (*)

1.  404 Page not found

**Comment by orlangur** [comment]
`2.1.x` bug reports are not acceptable anymore.
