### ISSUE TITLE
Attribute Update refers to page display and not selection

### ISSUE THREAD

**Issue by acrpro** [magento/magento2#22512]
### Preconditions (*)
Magento 2.3.1

### Steps to reproduce (*)

1. Catalog > Product
2. Select All (550) with diplay of 20
3. Change attribute

### Expected result (*)

4. The change should be applied to 550 and not 20

### Actual result (*)
4. The change will be applied to 20 and not 550

**Comment by krishprakash** [comment]
Hi @acrpro. Thank you for your report.
This is duplicate to #22004

**Comment by acrpro** [comment]
Sorry about that thanks

ACR Fuchs & Hanimann
35-37, rte de Veyrier
CH-1227 Carouge
Switzerland
T.:+41223435277
F.:+41223000413
W.:www.acrpro.ch
CHE-107.963.696
Custom Acct: 9033-4
