### ISSUE TITLE
Show by section mismatch issue in admin

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22524]
Show by section mismatch issue

### Preconditions (*)
Magento 2.2 and 2.3

### Steps to reproduce (*)
1. Admin > Reports >> Customers > Order Total/Order Count/New
2. See the Show by section

### Expected result (*)
Show by section design should display appropriate.

### Actual result (*)
![shop by](https://user-images.githubusercontent.com/49804008/56849973-805a2100-6919-11e9-9bd9-5011d5d7f060.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22524-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22524-2-3-develop.instances.magento-community.engineering/admin](https://i-22524-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22524-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22524-2-2-develop.instances.magento-community.engineering/admin](https://i-22524-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @bhavik43. Thank you for your report.
Not able to reproduce in 2.2 and 2.3 
May be it is your custom module issue.

**Comment by bhavik43** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bhavik43, here is your [Magento instance](https://i-22524-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22524-2-3-develop.instances.magento-community.engineering/admin](https://i-22524-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
