### ISSUE TITLE
Wishlist and compare icon align issue in product listing page

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22527]
Wishlist and compare icon align issue in product listing page

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
Go to product listing > See the wish list and compare icons in list and grid both views

### Expected result (*)
Both button should display center align with add to cart button as per magento 2.2

![expected](https://user-images.githubusercontent.com/49804008/56864341-ee1c5080-69de-11e9-9725-08de8122c656.png)

### Actual result (*)
![actual](https://user-images.githubusercontent.com/49804008/56864346-faa0a900-69de-11e9-8aa4-d2db0730de2e.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22527-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22527-2-3-develop.instances.magento-community.engineering/admin](https://i-22527-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22527-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22527-2-2-develop.instances.magento-community.engineering/admin](https://i-22527-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99442` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
I am working on the issue

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#22532 by @sanjaychouhan-webkul in 2.3-develop branch
Related commit(s):
 - [e161862468831a99cfb6fee8b77930909551c702](https://github.com/magento/magento2/commit/e161862468831a99cfb6fee8b77930909551c702)

The fix will be available with the upcoming 2.3.3 release.
