### ISSUE TITLE
Print a meaningful error message when gets the error code 15005 in PayPal payment.

### ISSUE THREAD

**Issue by Hailong** [magento/magento2#22522]
### Description (*)

Our website has PayPal Payflow Pro enabled for user to pay with credit card directly on the same page. And in the operation we found that the error code 15005 is very popular, but the error message just tells user that the transaction is declined. Usually user would try multiple times since there is no specific reason given, and they may think that's some problem of the website. Eventually they get very upset.

But this error code was actually because PayPal got declined by the bank, thus user needs to reach out to bank. So a better error message in this condition would be very helpful and user friendly.

### Expected behavior (*)

Ask user to reach out to their bank for the problem.
### Benefits

Make it clear that the problem is due to dependencies, not the defect of Magento.
### Additional information

I opened PayPal tickets several time to investigate this problem, let me quote their reply below:
> Hello Zhao,
> 
> Thank you for your response. I wanted to let you know that after researching further, I was able to find the payment attempts by XXX XXX here at our side. I determined that PayPal declined the transactions based on the response of the payment processor (HSBC.) My apologies, but because of confidentiality reasons, we cannot share the responses of the payment processor.
> 
> As I mentioned in the previous case, I recommend that if the customer has a different credit card or payment method that they can use for those transactions, it's possible that the transaction might succeed if they try paying again using one of those. Some common reasons that transactions decline are the credit card's security code not being correct, and/or the payment type's billing address not being correct (however this is only something to keep in mind, and is not necessarily the reason these transactions in question were declined.)
> 
> If you need to know the specific responses that the payment processor sent to PayPal that caused us to decline the transactions, you will need to contact HSBC for those details.
> 
> Please let me know if acting on this recommendation resolves your issue, or if you have any further questions or concerns.

**Comment by krishprakash** [comment]
Hi @Hailong. Thank you for your report.
As per your report it should be enhancement request.

**Comment by krishprakash** [comment]
Hi @Hailong.
please report in https://github.com/magento/community-features/issues.

**Comment by Hailong** [comment]
Thank you @krishprakash , I had moved it to https://github.com/magento/community-features/issues/166
