### ISSUE TITLE
Title Suffix is also shown on Search page title

### ISSUE THREAD

**Issue by debuysserk** [magento/magento2#2252]
When you add a title suffix (Html Head), for example "| test", it gets added to the title of your search results as well, inside your page. I'm guessing it's a bug?

<img width="603" alt="screen shot 2015-11-03 at 19 15 55" src="https://cloud.githubusercontent.com/assets/14332813/10917118/5bbb8356-825f-11e5-8052-fae4c5a64c76.png">

Thx!

**Comment by piotrekkaminski** [comment]
internal id MAGETWO-44997

**Comment by magento-engcom-team** [comment]
@debuysserk, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9
