### ISSUE TITLE
Enable PayPal Credit option not avaible for USA

### ISSUE THREAD

**Issue by GlOnSa** [magento/magento2#22525]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Stores > Config > Sales > Payment Methods
2. Set Merchant Country to United States
3. PayPal Express Checkout > Configure

### Expected result (*)

1. Same with version 2.3.0, there should be Enable PayPal Credit [YES/NO] and Sort Order PayPal Credit.

### Actual result (*)

1. On 2.3.1, after Merchant Account ID, neither option is shown.

![M2_2 3 0-2 3 1_PPC](https://user-images.githubusercontent.com/50052661/56851749-963ef600-68c7-11e9-80d7-b667e5b0e744.jpg)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22525-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22525-2-3-develop.instances.magento-community.engineering/admin](https://i-22525-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
![issue](https://user-images.githubusercontent.com/46617848/56852288-f0c36b00-6936-11e9-95f5-884c797edf92.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99441` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Nazar65** [comment]
@krishprakash this is expected behavior,` MC-11034: Enable Paypal Credit option should be disabled/greyed out when a non-US merchant is chosen - Fixed review comments` fixed in this commit.

**Comment by GlOnSa** [comment]
> 
> 
> @krishprakash this is expected behavior,` MC-11034: Enable Paypal Credit option should be disabled/greyed out when a non-US merchant is chosen - Fixed review comments` fixed in this commit.

I don't follow this comment.  The issue pertains to United States... not a non-US Merchant.

**Comment by Nazar65** [comment]
@GIOnsa however I'd don't think that this an issue.

**Comment by GlOnSa** [comment]
> 
> 
> @GIOnsa however I'd don't think that this an issue.

So, you're saying Magento made the decision to remove this option in 2.3.1, but yet the option advertise PayPal Credit is still there?  I don't think so.

**Comment by Nazar65** [comment]
@GlOnSa based on this commit this option should be available to specific country https://github.com/magento/magento2/commit/7cd52fb59a15b0aae863fe98addc4578b77eac75

**Comment by Nazar65** [comment]
@GlOnSa if your country US you don't have this option 
![DeepinScreenshot_select-area_20190427204035](https://user-images.githubusercontent.com/2481206/56853181-cf5d8180-692c-11e9-8965-f8f68242f694.png)

**Comment by Nazar65** [comment]
@GlOnSa  also `MC-13710: PayPal label "Credit" should be removed from label configuration when PayPal Credit is disabled from Disable Funding Options multi-select`

**Comment by GlOnSa** [comment]
Sorry Nazar65, I guess I just don't understand.  According to this Magento document...  https://docs.magento.com/m2/ce/user_guide/payment/paypal-credit.html  it states...  "For US merchants, PayPal Credit is included as a PayPal Express Checkout option"

And also...  https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.1OpenSource.html  ... "Update PayPal Express Checkout to checkout.js v4. This introduces a modernized checkout flow, faster checkout performance, and new payment options in a single integration that does not have to be updated as new payment methods become available. It also unlocks new payment options including Venmo and PayPal Credit. "

**Comment by Nazar65** [comment]
@GlOnSa 
![DeepinScreenshot_select-area_20190427233235](https://user-images.githubusercontent.com/2481206/56854777-c37db980-6944-11e9-8970-a89fa27d6d36.png)

**Comment by GlOnSa** [comment]
Yep.  That's me. I'm in the US and only accept USD.

**Comment by Nazar65** [comment]
@GlOnSa this is new feature was introduced in 2.3.1 release. so you don't need this option anymore :)

**Comment by Nazar65** [comment]
@GlOnSa https://github.com/magento/magento2/commit/d0a5ba4491d2cc34e2f23cf407304516e50b7b5e

**Comment by GlOnSa** [comment]
Nazar65... the option is NOT being shown during checkout.  Yes, I am in the US so therefore, based your logic, the PayPal Credit option should display... but it doesn't.

**Comment by Nazar65** [comment]
@GlOnSa 
![DeepinScreenshot_select-area_20190427235141](https://user-images.githubusercontent.com/2481206/56854947-6df6dc00-6947-11e9-92c4-f245207cc69b.png)
![DeepinScreenshot_select-area_20190427235414](https://user-images.githubusercontent.com/2481206/56854969-c9c16500-6947-11e9-8afc-539606108d50.png)

**Comment by chequille** [comment]
Hi Everybody,

sorry, but this is an issue which is really bad.
It does not matter which country or currency is used in the shop.
I as the shop owner have to make the decision which Payment methods are offered in my shop.
Therefore, it cannot be, that Magento/PayPal is making this decision.
Therefore, the possibility to configure ( enable/disable) as well the "PayPal Credit" must be there independently of the country and/or currency and/or whether it is supported by PayPal or not.

The first decision must be in my hands and nowhere else!!!!

Currently as it is in 2.3.1, I have no possibiity to disbale "PayPal Credit", but I want to disable it, regardless PayPal is supporting it in Germany or not.

I hope this made everything clear and understandable for everybody, and hopefully some people will see this as mandatory feature which have to be implemented again.

Best regards,
Jürgen

**Comment by oleksii-lisovyi** [comment]
@chequille, please check out my comment https://github.com/magento/magento2/issues/22528#issuecomment-523359831.

**Comment by magento-engcom-team** [comment]
Hi @GlOnSa. Thank you for your report. 
The issue has been fixed in magento/magento2#24121 by @oleksii-lisovyi in 2.3-develop branch
Related commit(s):
 - [7507dcef7dfa144a59df3e134ad3819963fc05d8](https://github.com/magento/magento2/commit/7507dcef7dfa144a59df3e134ad3819963fc05d8)
 - [c80bcb929325d2a3a4319d9b17d75a73c5731afe](https://github.com/magento/magento2/commit/c80bcb929325d2a3a4319d9b17d75a73c5731afe)
 - [ce7b33c6e1c1d416ecbd852b09a4d6a384394c7c](https://github.com/magento/magento2/commit/ce7b33c6e1c1d416ecbd852b09a4d6a384394c7c)

The fix will be available with the upcoming 2.3.4 release.

**Comment by maderlock** [comment]
I'll raise a separate ticket for this, but it's worth pointing out that even after this fix the check for the merchant country will still be done for store id = 1 instead of the current store, so if your store ID 1 uses a different account for PayPal then you will not be able to see PayPal credit on any store on your site.
