### ISSUE TITLE
Fatal error: Class 'Codeception\Platform\Extension' not found. Issue occurred after magento 2.3.0 upgrade to 2.3.1

### ISSUE THREAD

**Issue by farhangithub27** [magento/magento2#22531]
### Preconditions (*)

1.Magento 2.3.1 upgraded from Magento 2.3.0 
2.Php 7.2.15
3. OS : Ubuntu 18.04 Bionic
4. Phpstorm 2019.1.1
5. Evnironemnt : Magento development

### Steps to reproduce (*)

1. Issue appears after upgrading magento from 2.3.0 to 2.3.1 and run below commands.
2.`bin/magento dev:tests:run unit`
3.`vendor/phpunit/phpunit/phpunit -c dev/tests/unit/phpunit.xml.dist`.
4. Above commands will work if version 2.3.0 is installed directly and also for 2.3.1 if installed directly.

These commands should run unit test on entire magento project not just on one mdoule.
### Expected result (*)

1. A successful unit test.
2.

### Actual result (*)

1. Fatal error: Class 'Codeception\Platform\Extension' not found in /var/www/html/magento23demo/vendor/allure-framework/allure-codeception/src/Yandex/Allure/Adapter/AllureAdapter.php on line 49

Please note I can't find Platform\Extension codeception library in vendor folder.

> Also use the commands provided to reproduce the issue and don't use the command as executed by @engcom-backlog-nazar in https://github.com/magento/magento2/issues/22400. Since that issue was closed as I was away and couldn't reply so I'm raising it again with more investigation into it.

**Comment by fooman** [comment]
How did you upgrade? If it works with a fresh install but not with an upgrade the most likely is that the require-dev dependencies are different. Please compare your composer.json after the upgrade to the composer.json of the 2.3.1 direct install.

**Comment by farhangithub27** [comment]
@fooman require-dev for both installations (upgraded and clean) is same only except clean install of 2.3.1 has mftf version 2.3.13 and upgraded has 2.3.9. Rest of require-dev is exactly same

**Comment by fooman** [comment]
Try running `composer require magento2/magento2-functional-testing-framework:~2.3.13 --dev`

**Comment by orlangur** [comment]
@farhangithub27 there is nothing to fix here, it seems like you didn't upgrade vendors correctly during Magento upgrade.

As you already have a working version with clean 2.3.1 install, you can find the differences and get rid of them by yourself.

**Comment by fooman** [comment]
Just to cross reference https://github.com/magento/magento2/pull/21565.

Also there are no upgrade instructions that reference this step.

**Comment by farhangithub27** [comment]
@fooman This seems like a plausible solution but it generated following error. 
```
Problem 1
    - Installation request for allure-framework/allure-codeception (locked at 1.2.7) -> satisfiable by allure-framework/allure-codeception[1.2.7].
    - magento/magento2-functional-testing-framework 2.3.13 requires allure-framework/allure-codeception ~1.3.0 -> satisfiable by allure-framework/allure-codeception[1.3.0].
    - magento/magento2-functional-testing-framework 2.3.14 requires allure-framework/allure-codeception ~1.3.0 -> satisfiable by allure-framework/allure-codeception[1.3.0].
    - Conclusion: don't install allure-framework/allure-codeception 1.3.0
    - Installation request for magento/magento2-functional-testing-framework ~2.3.13 -> satisfiable by magento/magento2-functional-testing-framework[2.3.13, 2.3.14].
```
If I do 
```
composer require allure-framework/allure-codeception:~1.3.0
```
then following occurs 
```
Problem 1
    - magento/magento2-functional-testing-framework 2.3.9 requires allure-framework/allure-codeception ~1.2.6 -> satisfiable by allure-framework/allure-codeception[1.2.6, 1.2.7] but these conflict with your requirements or minimum-stability.
    - magento/magento2-functional-testing-framework 2.3.9 requires allure-framework/allure-codeception ~1.2.6 -> satisfiable by allure-framework/allure-codeception[1.2.6, 1.2.7] but these conflict with your requirements or minimum-stability.
    - magento/magento2-functional-testing-framework 2.3.9 requires allure-framework/allure-codeception ~1.2.6 -> satisfiable by allure-framework/allure-codeception[1.2.6, 1.2.7] but these conflict with your requirements or minimum-stability.
    - Installation request for magento/magento2-functional-testing-framework 2.3.9 -> satisfiable by magento/magento2-functional-testing-framework[2.3.9].
```
So I removed  magento/magento2-functional-testing-framework 2.3.9 and installed magento/magento2-functional-testing-framework:~2.3.13 but now following error occured.

```
Class "Yandex\Allure\Adapter\AllureAdapter" does not exist
```

**Comment by farhangithub27** [comment]
@orlangur Your suggestion is vague. cli upgrade command should have taken care of all dependencies by itself. It should not be a manual process. 
Also upgraded 2.3.1 install still has this old 
```/vendor/allure-framework/allure-codeception/src/Yandex/Allure/Adapter/AllureAdapter.php ```
where as clean 2.3.1 install has this 
```/vendor/allure-framework/allure-codeception/src/Yandex/Allure/Codeception/AllureCodeception.php ``` . 
Issues like this should have been handled by upgrade cli command mentioned [here](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)

**Comment by farhangithub27** [comment]
Solution is provided in following [link](https://magento.stackexchange.com/questions/270555/fatal-error-class-codeception-platform-extension-not-found-issue-occurred-af)

**Comment by orlangur** [comment]
@farhangithub27 `allure-phpunit` was already there: https://github.com/magento/magento2/blob/2.3.1/composer.json#L93
