### ISSUE TITLE
Saved Payment methods (Magento Vault) are not remembered on checkout

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#22539]
### Preconditions (*)

Magento 2.3
### Steps to reproduce (*)

1. Enable BrainTree Payment method with Credit Card saving in Magento admin.
2. Checkout as a registered customer, using Braintree as a payment option and tick the box to save the card details.
3. Complete the checkout
4. Build a new order and go to checkout. Select your new saved card as the payment option.
5. Navigate away from the checkout (using back button, refresh page, etc). 
6. Return to checkout.  

### Expected result (*)

1. Saved card is remembered and selected when returning to checkout
![image](https://user-images.githubusercontent.com/49071342/56885688-f6b76a00-6a64-11e9-9639-bb9a81a83a5e.png)

### Actual result (*)

1. Saved card selection is lost on returning to checkout and now no payment option is selected
![image](https://user-images.githubusercontent.com/49071342/56885724-0fc01b00-6a65-11e9-9630-c82bb25125f4.png)

**The issue is caused by the following file:**
Magento_Checkout/js/model/payment-service.js

Specifically, the following check:
`methodIsAvailable = methods.some(function (item) {
    return item.method === quote.paymentMethod().method;
});`

This check doesn't take into account Vault payment options have a unique identifier appended to them (e.g braintree_cc_vault_28). So the function is comparing braintree_cc_vault vs braintree_cc_vault_28 and thus returns false.

**Comment by itmsenior** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-22539-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22539-2-3-develop.instances.magento-community.engineering/admin](https://i-22539-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
I can confirm this issue is reproducible on a vanilla Magento instance using steps provided.

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop.

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22539-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22539-2-3-develop.instances.magento-community.engineering/admin](https://i-22539-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.2-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22539-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22539-2-2-develop.instances.magento-community.engineering/admin](https://i-22539-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
This issue I have reproduced in Magento 2.2 and Magento 2.3 instance.
@itwebdev2 - This is not an issue. This is default featured by the Magento instance.
If a user has available 2 saved card and user will refresh the page Or navigate another page to redirect to check out user can select the another saved card.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99444`, `MAGETWO-99445` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by itmsenior** [comment]
@ajijshekh123 If this is default behaviour, then why are other payment methods remembered? If you select Paypal and navigate away, upon returning paypal is still selected. Why isn't it removed to allow the user to select another method?

**Comment by ajijshekh123** [comment]
Okay, @itwebdev2. I understand your point.

**Comment by subbu1993** [comment]
@magento-engcom-team Please give me 2.2.8 instance

**Comment by Krishnan369** [comment]
"I am working on this at #dmcdindia19”

**Comment by Krishnan369** [comment]
"I am working on this at #dmcdindia19”

**Comment by itmsenior** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-22539-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22539-2-3-develop.instances.magento-community.engineering/admin](https://i-22539-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-22539-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22539-2-3-develop.instances.magento-community.engineering/admin](https://i-22539-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sppascha** [comment]
We're encountering this problem in 2.3.5 Enterprise more than a year after it was identified. This was _just_ shifted to the Community backlog in March of this year?

Seeing as Braintree is a major payment processing gateway and this module's part of the standard package, I'm a little stunned that this hasn't received higher priority.

**Comment by magento-engcom-team** [comment]
Hi @itmsenior. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24303` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
