### ISSUE TITLE
Magento 2.2.8 After Create New Store View Sequence and catalogsearch_fulltext_scope tables not created automatically 

### ISSUE THREAD

**Issue by jaimin104** [magento/magento2#22537]
Summary of the issue

- sequence and scope related tables not created so We have facing issue in re-indexing.

Information on your environment
1.Magento 2.2.8

Steps to reproduce (*)

- Create new store view form admin not created catalogsearch_fulltext_scope, sequence_creditmemo, sequence_invoice, sequence_order and sequence_shipment tables.

Expected and actual results

- catalogsearch_fulltext_scope, sequence_creditmemo, sequence_invoice, sequence_order and sequence_shipment tables created automatically.

**Comment by soleksii** [comment]
Hi @jaimin104, thank you for your report.  I am not able to reproduce issue by steps you described on clean 2.2 and 2.3-develop .

**Result:** Tables was created automatically

![screen](https://user-images.githubusercontent.com/44244273/58944421-82ba6100-878a-11e9-9dd5-fa6d7db6813e.png)
