### ISSUE TITLE
Inconsistency: the «controller_action_catalog_product_save_entity_after» event is fired by a backend controller on a product saving, but no similar event is fired by a controller on a category saving

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2253]
Similar to https://github.com/magento/magento2/issues/2248 and https://github.com/magento/magento2/issues/2249.

The «controller_action_catalog_product_save_entity_after» event firing :

https://github.com/magento/magento2/blob/16dc76df41fac703b322cc0f9ab3dba43742bbed/app/code/Magento/Catalog/Controller/Adminhtml/Product/Save.php#L105-L108

There is no similar event for a category:
https://github.com/magento/magento2/blob/16dc76df41fac703b322cc0f9ab3dba43742bbed/app/code/Magento/Catalog/Controller/Adminhtml/Category/Save.php#L73-L212

**Comment by dfediuk** [comment]
The «`controller_action_catalog_product_save_entity_after`» event seems unnecessary because of the generic «`controller_action_postdispatch_catalog_product_save`» event.

I propose to delete the «`controller_action_catalog_product_save_entity_after`» event  to make the system more consistent and reduce it complexity.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Inconsistency-the-controller-action-catalog-product-save-entity/idi-p/45371).
