### ISSUE TITLE
Access Denied You don't have permission to access

### ISSUE THREAD

**Issue by KishorkumarKar** [magento/magento2#22540]
### Preconditions (*)

**Steps to reproduce (*)**

Magento 2.3.0

### Steps to reproduce (*)
**Steps to reproduce (*)**

1. Login to admin go to Marketing ->Email Template -> Add new template
2. Tried to create a mail template.
3. Gatting and error.
![image](https://user-images.githubusercontent.com/24475017/56897669-c1366f00-6aac-11e9-9ef7-1dc7af120678.png)

I am not gating any error in my test server where it is **http**.

### Expected result (*)

**Expected result (*)**
While saving the Email template it should save.

### Actual result (*)

**Actual result (*)**
When I click on save template I am getting that error.
![image](https://user-images.githubusercontent.com/24475017/56898155-f2636f00-6aad-11e9-9dc6-bde46265f107.png)

![image](https://user-images.githubusercontent.com/24475017/56897669-c1366f00-6aac-11e9-9ef7-1dc7af120678.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22540-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22540-2-3-develop.instances.magento-community.engineering/admin](https://i-22540-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @KishorkumarKar. Thank you for your report.
May be this issue from server side, or this blocked from ht-access or user role permission issue.
So please contact to server guy for this issue.

**Comment by KishorkumarKar** [comment]
@krishprakash thanks for the response our website doesn't open in **http**
I am gating this error.

![image](https://user-images.githubusercontent.com/24475017/56901139-10809d80-6ab5-11e9-993c-391e4e8c94cd.png)

**Comment by krishprakash** [comment]
Please contact to server support.
They can help you.
Thank you!
