### ISSUE TITLE
The call for \Magento\Store\Model\StoreManager::getStore() without parameters inside the backend returns the default frontend store, not the «admin» store, which is inconsistent with Magento 1.x behaviour and I think it will lead to developer mistakes

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2254]
See also another pitfall for Magento 1.x developers: https://github.com/magento/magento2/issues/2064

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by dfediuk** [comment]
I want to know from the Magento 2 team: is it the correct behaviour, not bug?
