### ISSUE TITLE
Can not update attribute options label via REST Api.

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#22554]
### Preconditions (*)

1. Magento 2.3.x
2.

### Steps to reproduce (*)

1. Create a dropdown type product attribute from admin.
2. Add some attribute options.
3. Save it.
4. Get admin token by rest request `https://i-22554-2-3-develop.instances.magento-community.engineering/rest/V1/integration/admin/token`
5. Now update option label like:
`URL:  https://i-22554-2-3-develop.instances.magento-community.engineering/rest/V1/products/attributes/color/options`
`Request type:  POST`
`BODY: 
{
  "option": {
    "value": "4",
    "store_labels": [
      {
        "store_id": 0,
        "label": "Yellow2"
      }
    ]
  }
}
`

### Expected result (*)

1. Attribute option label must be update with new label.
2.

### Actual result (*)

1. It creates new option with given label for update.
2.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-22554-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22554-2-3-develop.instances.magento-community.engineering/admin](https://i-22554-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
@krishprakash , check this issue by REST api request.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team , why we are adding prefix **'id_**' in option id here https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Eav/Model/Entity/Attribute/OptionManagement.php#L163  ??

**Comment by mahesh-rajawat** [comment]
@Nazar65 , have you checked it via REST api?

**Comment by Nazar65** [comment]
@maheshWebkul721 there is no "PUT" endpoint, so you don't have a request to update option .
![DeepinScreenshot_select-area_20190430130442](https://user-images.githubusercontent.com/2481206/56954926-bb8e6700-6b48-11e9-9399-3ace5878bbfa.png)

**Comment by krishprakash** [comment]
Hi @maheshWebkul721 
Magento does not provided attribute option update API endpoint
Here is list of all API endpoints provided by magento:
https://devdocs.magento.com/guides/v2.3/rest/list.html
Please review it.

**Comment by Nazar65** [comment]
@maheshWebkul721  It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by LusienGG** [comment]
Whats the resolution? Mentioned POST req worked for updates before 2.3... whats the point of changing it ?

**Comment by hdkiller** [comment]
I am stuck with this as well. 

> Whats the resolution? Mentioned POST req worked for updates before 2.3... whats the point of changing it ?

Did you have luck resolving it? I have the same issue... There is no way to update an option just delete and re-add?

**Comment by LusienGG** [comment]
> I am stuck with this as well.
> 
> > Whats the resolution? Mentioned POST req worked for updates before 2.3... whats the point of changing it ?
> 
> Did you have luck resolving it? I have the same issue... There is no way to update an option just delete and re-add?

I just reorganized my logic.

**Comment by leo-leung** [comment]
You can update option, but you need to mention the "option id" which has the field key "value".

Endpoint:   PUT /rest/all/V1/products/attributes/[your attribute code]

....[in your body json]
"options": [
        {
          "label": "Easy to detach",
          "value": "19013",
}]

After called, go back to your Magento backend, you will see the option is updated but not created.

**Comment by LiamKarlMitchell** [comment]
Note: POST with label and value to update does not appear to update existing, it creates a brand new one with a new id...
Also can not update multiple option labels at once.

API to POST returns a weird id_ prefixed number (the option id)
PUT API endpoint does not exist for **/rest/all/V1/products/attributes/{attributeCode}/options**

**Comment by LusienGG** [comment]
> Note: POST with label and value to update does not appear to update existing, it creates a brand new one with a new id...
> Also can not update multiple option labels at once.
> 
> API to POST returns a weird id_ prefixed number (the option id)
> PUT API endpoint does not exist for **/rest/all/V1/products/attributes/{attributeCode}/options**

That's resulting in self-DDoSing to some web servers due to many requests that should be handled on bulk updating of whole catalog.

**Comment by tonlam** [comment]
> You can update option, but you need to mention the "option id" which has the field key "value".
> 
> **Endpoint: PUT /rest/all/V1/products/attributes/[your attribute code]**
> 
> ```
> ....[in your body json]
> "options": [
>         {
>           "label": "Easy to detach",
>           "value": "19013"
> }]
> ```
> 
> After called, go back to your Magento backend, you will see the option is updated but not created.

This works for me. But it only updates Admin option label. How to update option label in other store?
