### ISSUE TITLE
New child products are not attached to configurable on import

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#22555]
### Preconditions (*)

1. Magento 2.3.1 

### Steps to reproduce (*)

1. Add options to product attribute color - red, black, green
![56805368-81178800-6831-11e9-8a1e-dc6803234aa9](https://user-images.githubusercontent.com/8502721/56956013-92bba100-6b4b-11e9-8694-102e3f317680.png)

2. Create a configurable product with sku **test-configurable** and one virtual/simple product attached (sku = test-configurable-red, color = red)
![Test Configurable   Products   Inventory   Catalog   Magento Admin](https://user-images.githubusercontent.com/8502721/56956093-d7473c80-6b4b-11e9-951c-03dcaad05d86.png)

3. create an import CSV file that contains a new simple/virtual product and update for the configurable to attach a new child product (file content):

sku,name,price,store_view_code,attribute_set_code,product_type,categories,product_websites,color,associated_skus,configurable_variations
test-configurable-black,Test Black,5,,Default,virtual,,base,black,,
test-configurable,Test Configurable,,,Default,configurable,,base,,"test-configurable-red,test-configurable-black","sku=test-configurable-red,color=red|sku=test-configurable-black,color=black"

4. Go to System -> Import, select Entity Type = Products, Import Behavior = Add/Update, Select File to Import = upload your CSV file and run import
5. Recheck **test-configurable** product

### Expected result (*)

New product **test-configurable-black** is attached to the configurable product **test-configurable**

### Actual result (*)

New product **test-configurable-black** is not attached to the configurable product **test-configurable**

![Test Configurable   Products   Inventory   Catalog   Magento Admin](https://user-images.githubusercontent.com/8502721/56952212-75360980-6b42-11e9-9ed7-b2b077c7f192.png)

**Comment by ajijshekh123** [comment]
@lyusya-nnn - Please provide the Step to reproduce steps properly. Please manage the list of product which you will be used.

**Comment by lyusya-nnn** [comment]
@ajijshekh123 description is updated.

**Comment by ajijshekh123** [comment]
Thanks for the update @lyusya-nnn

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22555-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22555-2-3-develop.instances.magento-community.engineering/admin](https://i-22555-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99458` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hi @lyusya-nnn. Thank you for your report.
Issue is duplicate to -> magento-engcom/import-export-improvements#90
