### ISSUE TITLE
VatValidator::validate returns error if region in quoteAddress is not set

### ISSUE THREAD

**Issue by Leone** [magento/magento2#22556]
There is an issue in \Magento\Quote\Observer\Frontend\Quote\Address\VatValidator::validate method.
Magento adds additional data to $quoteAddress object and throws an error during $quoteAddress->save(); if regionId in the address is not set.

### Preconditions (*)

1. Magento 2.3.0+
2. Configured taxes for EU
3. Enable Automatic Assignment to Customer Group is set to "Yes" and configured
4. Allow to Choose State if It is Optional for Country is set to "Yes"

### Steps to reproduce (*)

1. Configure taxes in the admin panel (e.g. for Germany and Austria)
2. Enable Automatic Assignment to Customer Group
3. Create a test customer account
4. Set customer address, region field should be empty, enter valid vat number
5. Add any product to cart
6. Go to the checkout

### Expected result (*)

1. Magento should validate the vat number and display the proper information (shipping methods, totals)

### Actual result (*)

1. Magento throws error in the checkout: "Internal Error. Details are available in Magento log file. Report ID: webapi-5cc8155d027de"
2. Report in logs: "Notice: Array to string conversion in /{path}/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3102"

**Comment by Leone** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leone. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leone, here is your [Magento instance](https://i-22556-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22556-2-3-develop.instances.magento-community.engineering/admin](https://i-22556-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Leone** [comment]
I was able to reproduce this error on vanilla Magento instance

![Image](http://creativecast.de/gb/vatValidator_validate_error2.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99459` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mallikaverma** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @Leone. Thank you for your report. 
The issue has been fixed in magento/magento2#22558 by @Leone in 2.3-develop branch
Related commit(s):
 - [a2fc3b98bf52ff7741579d16042b9c6376ecebfc](https://github.com/magento/magento2/commit/a2fc3b98bf52ff7741579d16042b9c6376ecebfc)
 - [2f8fad776e0ab1f66aacbfe4714c399598e165c8](https://github.com/magento/magento2/commit/2f8fad776e0ab1f66aacbfe4714c399598e165c8)
 - [bd56e2f6943eb650e2734eebe230e874180aa6d5](https://github.com/magento/magento2/commit/bd56e2f6943eb650e2734eebe230e874180aa6d5)

The fix will be available with the upcoming 2.3.3 release.
