### ISSUE TITLE
Admin section won't allow for Flushing Cache

### ISSUE THREAD

**Issue by Jayce2000** [magento/magento2#22550]
Was able to lush the cache this morning now I only get listed features, I know longer get the style of the backend any longer.

**Comment by shikhamis11** [comment]
@Jayce2000 Please follow issue reporting guideline to report an issue 
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks.

**Comment by shikhamis11** [comment]
@Jayce2000 thank you for your report Please correct the format of your issue as per reporting guideline and provide more information about the issue. and message here to reopen the issue
