### ISSUE TITLE
Price getting populated on child item in order JSON

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#22562]
### Preconditions (*)

1. Magento 2.2.8 CE

### Steps to reproduce (*)

1. Create Configurable item
2. Create order using the configurable item
3. get order JSON using order API

### Expected result (*)

1. Items node for child item should not show the price ., It should show price 0 as same as 2.2.7 and before.

### Actual result (*)

1. items node for child item showing the only price in "price" node. not in "original_price", "base_price", "base_original_price", etc.

**Comment by ankursachdeva11** [comment]
Any Updates
@magento-engcom-team

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99521`, `MAGETWO-99522` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-22562-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22562-2-3-develop.instances.magento-community.engineering/admin](https://i-22562-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia19

**Comment by sanjay-wagento** [comment]
@magento-engcom-team 
I placed a configurable product order and fetch order details by rest API. 
In Items node it shows prices for a configurable item but not for a simple item.
So this is a functionality of Magento, not a BUG.
`"items": [
                    {
                        "amount_refunded": 0,
                        "base_amount_refunded": 0,
                        "base_discount_amount": 0,
                        "base_discount_invoiced": 0,
                        "base_discount_tax_compensation_amount": 0,
                        "base_original_price": 47,
                        "base_price": 47,
                        "base_price_incl_tax": 47,
                        "base_row_invoiced": 0,
                        "base_row_total": 47,
                        "base_row_total_incl_tax": 47,
                        "base_tax_amount": 0,
                        "base_tax_invoiced": 0,
                        "created_at": "2019-05-04 04:05:46",
                        "discount_amount": 0,
                        "discount_invoiced": 0,
                        "discount_percent": 0,
                        "free_shipping": 0,
                        "discount_tax_compensation_amount": 0,
                        "is_qty_decimal": 0,
                        "is_virtual": 0,
                        "item_id": 3,
                        "name": "Kenobi Trail Jacket",
                        "no_discount": 0,
                        "order_id": 3,
                        "original_price": 47,
                        "price": 47,
                        "price_incl_tax": 47,
                        "product_id": 308,
                        "product_type": "configurable",
                        "qty_canceled": 0,
                        "qty_invoiced": 0,
                        "qty_ordered": 1,
                        "qty_refunded": 0,
                        "qty_shipped": 0,
                        "quote_item_id": 7,
                        "row_invoiced": 0,
                        "row_total": 47,
                        "row_total_incl_tax": 47,
                        "row_weight": 1,
                        "sku": "MJ04-XS-Black",
                        "store_id": 1,
                        "tax_amount": 0,
                        "tax_invoiced": 0,
                        "tax_percent": 0,
                        "updated_at": "2019-05-04 04:05:46",
                        "weight": 1,
                        "product_option": {
                            "extension_attributes": {
                                "configurable_item_options": [
                                    {
                                        "option_id": "355",
                                        "option_value": 167
                                    },
                                    {
                                        "option_id": "306",
                                        "option_value": 49
                                    }
                                ]
                            }
                        }
                    },
                    {
                        "amount_refunded": 0,
                        "base_amount_refunded": 0,
                        "base_discount_amount": 0,
                        "base_discount_invoiced": 0,
                        "base_price": 0,
                        "base_row_invoiced": 0,
                        "base_row_total": 0,
                        "base_tax_amount": 0,
                        "base_tax_invoiced": 0,
                        "created_at": "2019-05-04 04:05:46",
                        "discount_amount": 0,
                        "discount_invoiced": 0,
                        "discount_percent": 0,
                        "free_shipping": 0,
                        "is_qty_decimal": 0,
                        "is_virtual": 0,
                        "item_id": 4,
                        "name": "Kenobi Trail Jacket-XS-Black",
                        "no_discount": 0,
                        "order_id": 3,
                        "original_price": 0,
                        "parent_item_id": 3,
                        "price": 0,
                        "product_id": 293,
                        "product_type": "simple",
                        "qty_canceled": 0,
                        "qty_invoiced": 0,
                        "qty_ordered": 1,
                        "qty_refunded": 0,
                        "qty_shipped": 0,
                        "quote_item_id": 8,
                        "row_invoiced": 0,
                        "row_total": 0,
                        "row_weight": 0,
                        "sku": "MJ04-XS-Black",
                        "store_id": 1,
                        "tax_amount": 0,
                        "tax_invoiced": 0,
                        "tax_percent": 0,
                        "updated_at": "2019-05-04 04:05:46",
                        "weight": 1,
                        "parent_item": {
                            "amount_refunded": 0,
                            "base_amount_refunded": 0,
                            "base_discount_amount": 0,
                            "base_discount_invoiced": 0,
                            "base_discount_tax_compensation_amount": 0,
                            "base_original_price": 47,
                            "base_price": 47,
                            "base_price_incl_tax": 47,
                            "base_row_invoiced": 0,
                            "base_row_total": 47,
                            "base_row_total_incl_tax": 47,
                            "base_tax_amount": 0,
                            "base_tax_invoiced": 0,
                            "created_at": "2019-05-04 04:05:46",
                            "discount_amount": 0,
                            "discount_invoiced": 0,
                            "discount_percent": 0,
                            "free_shipping": 0,
                            "discount_tax_compensation_amount": 0,
                            "is_qty_decimal": 0,
                            "is_virtual": 0,
                            "item_id": 3,
                            "name": "Kenobi Trail Jacket",
                            "no_discount": 0,
                            "order_id": 3,
                            "original_price": 47,
                            "price": 47,
                            "price_incl_tax": 47,
                            "product_id": 308,
                            "product_type": "configurable",
                            "qty_canceled": 0,
                            "qty_invoiced": 0,
                            "qty_ordered": 1,
                            "qty_refunded": 0,
                            "qty_shipped": 0,
                            "quote_item_id": 7,
                            "row_invoiced": 0,
                            "row_total": 47,
                            "row_total_incl_tax": 47,
                            "row_weight": 1,
                            "sku": "MJ04-XS-Black",
                            "store_id": 1,
                            "tax_amount": 0,
                            "tax_invoiced": 0,
                            "tax_percent": 0,
                            "updated_at": "2019-05-04 04:05:46",
                            "weight": 1,
                            "product_option": {
                                "extension_attributes": {
                                    "configurable_item_options": [
                                        {
                                            "option_id": "355",
                                            "option_value": 167
                                        },
                                        {
                                            "option_id": "306",
                                            "option_value": 49
                                        }
                                    ]
                                }
                            }
                        },
                        "row_total_incl_tax": 0,
                        "base_row_total_incl_tax": 0
                    }
                ]`

**Comment by ankursachdeva11** [comment]
@magento-engcom-team @sanjay-wagento 
I placed a configurable product order in Magento 2.2.8 and fetch order details by rest API.
Items node it shows prices for a configurable item and also showing for a simple item.
So this seems a BUG. Please check again.
"items": [
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_discount_tax_compensation_amount": 0,
            "base_original_price": 123,
            "base_price": 123,
            "base_price_incl_tax": 123,
            "base_row_invoiced": 0,
            "base_row_total": 123,
            "base_row_total_incl_tax": 123,
            "base_tax_amount": 0,
            "base_tax_invoiced": 0,
            "created_at": "2019-04-30 15:17:18",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "free_shipping": 0,
            "discount_tax_compensation_amount": 0,
            "is_qty_decimal": 0,
            "is_virtual": 1,
            "item_id": 6,
            "name": "test",
            "no_discount": 0,
            "order_id": 6,
            "original_price": 123,
            "price": 123,
            "price_incl_tax": 123,
            "product_id": 9,
            "product_type": "configurable",
            "qty_canceled": 0,
            "qty_invoiced": 0,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_returned": 0,
            "qty_shipped": 0,
            "quote_item_id": 16,
            "row_invoiced": 0,
            "row_total": 123,
            "row_total_incl_tax": 123,
            "row_weight": 0,
            "sku": "test-Blue",
            "store_id": 1,
            "tax_amount": 0,
            "tax_invoiced": 0,
            "tax_percent": 0,
            "updated_at": "2019-04-30 15:17:18",
            "product_option": {
                "extension_attributes": {
                    "configurable_item_options": [
                        {
                            "option_id": "93",
                            "option_value": 16
                        }
                    ]
                }
            }
        },
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_price": 0,
            "base_row_invoiced": 0,
            "base_row_total": 0,
            "base_tax_amount": 0,
            "base_tax_invoiced": 0,
            "created_at": "2019-04-30 15:17:18",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "free_shipping": 0,
            "is_qty_decimal": 0,
            "is_virtual": 1,
            "item_id": 7,
            "name": "test-Blue",
            "no_discount": 0,
            "order_id": 6,
            "original_price": 0,
            "parent_item_id": 6,
            **"price": 123,**
            "product_id": 7,
            "product_type": "virtual",
            "qty_backordered": 1,
            "qty_canceled": 0,
            "qty_invoiced": 0,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_returned": 0,
            "qty_shipped": 0,
            "quote_item_id": 17,
            "row_invoiced": 0,
            "row_total": 0,
            "row_weight": 0,
            "sku": "test-Blue",
            "store_id": 1,
            "tax_amount": 0,
            "tax_invoiced": 0,
            "tax_percent": 0,
            "updated_at": "2019-04-30 15:17:18",
            "parent_item": {
                "amount_refunded": 0,
                "base_amount_refunded": 0,
                "base_discount_amount": 0,
                "base_discount_invoiced": 0,
                "base_discount_tax_compensation_amount": 0,
                "base_original_price": 123,
                "base_price": 123,
                "base_price_incl_tax": 123,
                "base_row_invoiced": 0,
                "base_row_total": 123,
                "base_row_total_incl_tax": 123,
                "base_tax_amount": 0,
                "base_tax_invoiced": 0,
                "created_at": "2019-04-30 15:17:18",
                "discount_amount": 0,
                "discount_invoiced": 0,
                "discount_percent": 0,
                "free_shipping": 0,
                "discount_tax_compensation_amount": 0,
                "is_qty_decimal": 0,
                "is_virtual": 1,
                "item_id": 6,
                "name": "test",
                "no_discount": 0,
                "order_id": 6,
                "original_price": 123,
                "price": 123,
                "price_incl_tax": 123,
                "product_id": 9,
                "product_type": "configurable",
                "qty_canceled": 0,
                "qty_invoiced": 0,
                "qty_ordered": 1,
                "qty_refunded": 0,
                "qty_returned": 0,
                "qty_shipped": 0,
                "quote_item_id": 16,
                "row_invoiced": 0,
                "row_total": 123,
                "row_total_incl_tax": 123,
                "row_weight": 0,
                "sku": "test-Blue",
                "store_id": 1,
                "tax_amount": 0,
                "tax_invoiced": 0,
                "tax_percent": 0,
                "updated_at": "2019-04-30 15:17:18",
                "product_option": {
                    "extension_attributes": {
                        "configurable_item_options": [
                            {
                                "option_id": "93",
                                "option_value": 16
                            }
                        ]
                    }
                }
            },
            "row_total_incl_tax": 0,
            "base_row_total_incl_tax": 0
        }
    ]

**Comment by ankursachdeva11** [comment]
@magento-engcom-team , Please open this issue

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18897` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ankursachdeva11. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24352` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by giacmir** [comment]
@magento-engcom-team this fix can break existing integrations based on simple product. Can you share which commit solved the issue?
