### ISSUE TITLE
[2.3.1] [API] Unable to add Youtube/Vimeo video using catalogProductRepository endpoint

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#22574]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)
1. Add a product using the catalogProductRepository endpoint including a youtube video.
2. Example JSON request (You need to add the encoded image to "base64_encoded_data"):
```
{
  "product": {
    "sku": "1",
    "media_gallery_entries": [
        {
            "media_type": "external-video",
            "disabled": false,
            "label": "Test Video",
            "types": [],
            "content": {
                "type": "image/jpeg",
                "name": "thumbnail.jpg",
                "base64_encoded_data": "ENCODE DATA HERE REMOVED AS TOO BIG FOR GITHUB"
            },
            "extension_attributes": {
                "video_content": {
                    "media_type": "external-video",
	            "video_provider":"youtube",
                    "video_url": "https://www.youtube.com/watch?v=2VLSaceaDnM",
                    "video_title": "Video title",
                    "video_description": "Video description",
                    "video_metadata": "Video meta"
                }
            }
        }
    ]
  },
  "saveOptions": true
}
```

### Expected result (*)

1. Product has Youtube video appear in media gallery
![image](https://user-images.githubusercontent.com/49071342/57027709-0c7b8980-6c35-11e9-81c0-50ff6270e044.png)

### Actual result (*)

1. Encoded image for placeholder is uploaded but no other data
![image](https://user-images.githubusercontent.com/49071342/57027634-db02be00-6c34-11e9-9184-605aa393ed3b.png)

Note: Using the MediaGallery endpoint still works, it's only when using the CatalogProductRepository.

**Comment by itmsenior** [comment]
Reproduced on Vanilla Magento 2.3.1

**Comment by krishprakash** [comment]
Hi @itwebdev2. Thank you for your report.
This is not an issue
![youtube](https://user-images.githubusercontent.com/46617848/57057918-f8359c00-6cc9-11e9-809a-03e50fc4be76.jpg)
You need to set API key for you tube video in below path
Store > Configuration > Catalog > Product video > YouTube API Key

**Comment by itmsenior** [comment]
> Hi @itwebdev2. Thank you for your report.
> This is not an issue
> ![youtube](https://user-images.githubusercontent.com/46617848/57057918-f8359c00-6cc9-11e9-809a-03e50fc4be76.jpg)
> You need to set API key for you tube video in below path
> Store > Configuration > Catalog > Product video > YouTube API Key

Hi @krishprakash are you sure you used the catalogProductRepository on Magento 2.3.1? Could you please share your JSON used for that result?
