### ISSUE TITLE
Date header missing in sent email

### ISSUE THREAD

**Issue by Rickertje** [magento/magento2#22572]
### Preconditions (*)
1. Magento 2.2.7

### Steps to reproduce (*)
1. Put item in cart
2. Checkout

### Expected result (*)
1. Confirmation order email with a date added to the header

### Actual result (*)
1. Confirmation order email without a date added to the header
2. Spamfilter says: X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date"

**Comment by ajijshekh123** [comment]
@Rickertje - 
1. Please send the Email which is not available date. 
2. Place Order in which payment method you are using in the Checkout page.

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22572-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22572-2-3-develop.instances.magento-community.engineering/admin](https://i-22572-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@Rickertje - Email configuration is not working on Magento Instance 2.3 that's why I can't able to review this issue.

**Comment by ajijshekh123** [comment]
@maheshWebkul721 - How to configure email in Magento Instance?

**Comment by Rickertje** [comment]
@ajijshekh123 
Ok I'm glad I'm still on 2.2. 
I have reason to believe this problem was solved in 2.2.8. I will try to post the details asap. You can relax and sit back for now.

**Comment by ajijshekh123** [comment]
Thanks for the update @Rickertje

**Comment by Rickertje** [comment]
I am not in the position to check this but the problem seems resolved on Magento version 2.2.8 and up (you can see Zend/Mail/Header/Date.php). Maybe someone can doublecheck?

If you are using Magento version less than 2.2.7, you need the code (http://prntscr.com/njbufb) on the Mail/Transport file. This is the code:
```
if ($message instanceof \Magento\Framework\Mail\Message && $message->getDate() == NULL) {
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
$date = $objDate->gmtDate();
$message->setDate($date);
}
```
Thanks to Arthas from Mageplaza for providing

**Comment by ajijshekh123** [comment]
Okay @Rickertje

**Comment by VasylShvorak** [comment]
Hi @Rickertje thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.3-develop.
