### ISSUE TITLE
Not able to create color swatches Magento ver. 2.2.4

### ISSUE THREAD

**Issue by saxenapritesh** [magento/magento2#22586]
Preconditions

    Magento ver. 2.2.4
    Developer mode/Production Mode

Steps to reproduce

	Add your own colors

Expected result

    You should be able to add as many colors as you want.

Actual result

    After 39 color swatches, new colors are not saved even though you still get the "You saved the product attribute." success message.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22586-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22586-2-2-develop.instances.magento-community.engineering/admin](https://i-22586-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @saxenapritesh. Thank you for your report.
I'am not able to reproduce this issue as provided steps by you.
https://www.screencast.com/t/T7zDzs4AuK

**Comment by saxenapritesh** [comment]
I have increased max_input_vars to 5000 in my php.ini file and it solved my problem.
Is this is the right way to solve that ?

**Comment by krishprakash** [comment]
Yes, You need to increase the memory limit.
Please follow below document for this:
https://devdocs.magento.com/guides/v2.3/install-gde/trouble/php/tshoot_php-set.html
