### ISSUE TITLE
Theme deploy after cronjob

### ISSUE THREAD

**Issue by Julen10** [magento/magento2#22585]
### Preconditions (*)

1. Magento 2.3.0 and 2.3.1

### Steps to reproduce (*)

1. Setup the cronjobs
2. Wait them to be executed

### Expected result (*)

1. Cronjobs are executed correctly and all works perfect

### Actual result (*)

1. Cronjobs are executed and sometimes the homepage gives 404
2. I need to redeploy theme

Logs doesn´t give me any clue, because it seems like all works perfect saying how much crons were cleaned. Even if I executed them manually, it doesn´t give any problem, it happens sometimes at night 23:00 UTC.

**Comment by ghost** [comment]
Hi, @Julen10 thank you for your report , i`m not able to reproduce this issue , please provide more information about steps for reproduce.

**Comment by Julen10** [comment]
Hi @engcom-backlog-nazar , 
I solved the problem in some way. The problem is that HEAD petition to the homepage throws a 404 error and that´s stored in the cache. So, the next home petitions will throw a 404 and for solving it you need to deploy again the theme.

This problem is given because I use uptimerobot on his free plan, and I can´t change there the petition mode so it´s always a HEAD ones. I´m not able to make a patch of some commit that solve it, so I made an easier change not storing in cache the HEAD petitions.

Hope it helps, Regards :)

**Comment by hostep** [comment]
@Julen10: nice find!

This means this ticket is a duplicate of https://github.com/magento/magento2/issues/21299
It was fixed in https://github.com/magento/magento2/pull/21378
The fix is scheduled to be released in Magento 2.3.2

I'm going to close this issue now if you don't mind.

**Comment by Julen10** [comment]
@hostep For sure, thanks.
