### ISSUE TITLE
Conditions Cart Rules Not working Magento 2.3.1

### ISSUE THREAD

**Issue by Rajan-Bhola** [magento/magento2#22584]
### Preconditions (*)

1. Magento 2.3.1
2.

### Steps to reproduce (*)

1. Go to Marketing > Cart Price Rules > Add new Rule > Conditions > select one.
2. On any linux server

### Expected result (*)

1. [Screenshots, logs or description] - one of previous developer posted this issue same screenshots you can check,
2. On select it redirects and show 404 not fount error.

### Actual result (*)

1. [Screenshots, logs or description]
2. On select it shows that selected cart rule html in ajax response

**Comment by krishprakash** [comment]
Hi @Rajan-Bhola. Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Also please mention additional details with issue scenario
Thanks.

**Comment by Rajan-Bhola** [comment]
> Hi @Rajan-Bhola. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * [ ]  Summary of the issue
> 
>     * [ ]  Information on your environment
> 
>     * [ ]  Steps to reproduce
> 
>     * [ ]  Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @Rajan-Bhola do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [ ]  yes
> 
>     * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @Rajan-Bhola. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Rajan-Bhola, here is your [Magento instance](https://i-22584-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22584-2-3-develop.instances.magento-community.engineering/admin](https://i-22584-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Rajan-Bhola** [comment]
on instance its working but not on mine. i do install a fresh setup of magento 2.3.1
- no error log . no system log. no exception log to fix this error

**Comment by Rajan-Bhola** [comment]
can you please share apache module list so i can check respectively

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by Rajan-Bhola** [comment]
please reply to my question please i am stuck in between

**Comment by Rajan-Bhola** [comment]
also reopen this issue

**Comment by krishprakash** [comment]
Hi @Rajan-Bhola, 
i'm not able to reproduce in 2.3.1 as following steps you described, seems like this related to your custom modules.

**Comment by Rajan-Bhola** [comment]
Go to Marketing > Cart Price Rules > Add new Rule > Conditions > select one. 
admin panel
![Screenshot from 2019-05-02 12-50-02](https://user-images.githubusercontent.com/29483720/57060954-d98ad180-6cd8-11e9-87f2-cd296483023e.png)

**Comment by Rajan-Bhola** [comment]
![Screenshot from 2019-05-02 12-51-13](https://user-images.githubusercontent.com/29483720/57060999-0808ac80-6cd9-11e9-9c74-6ea63ee71992.png)

**Comment by Rajan-Bhola** [comment]
its fresh setup on my server

**Comment by Rajan-Bhola** [comment]
https://www.xxtestxx.com/demo/admin/sales_rule/index/index/key/1a26fb37fdf300c48feca40db7409229871d2514f96cd40deef53925f97927c2/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard

**Comment by Rajan-Bhola** [comment]
this is done after infinite redirection

**Comment by Rajan-Bhola** [comment]
![Screenshot from 2019-05-02 13-10-36](https://user-images.githubusercontent.com/29483720/57061767-bf9ebe00-6cdb-11e9-87ba-2b1e60c4c003.png)
