### ISSUE TITLE
Bug? When a configurable product is moved to another store its simple variants are stayed in the previous store. Surely they need to be moved to the new store too.

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2258]

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Bug-When-a-configurable-product-is-moved-to-another-store-its/idi-p/45370).
