### ISSUE TITLE
Tax amount position showing wrong in order email with multi store

### ISSUE THREAD

**Issue by deepakk-webkul** [magento/magento2#22583]
**Preconditions** (*)
1. Magento CE 2.2.7 with sample data installed
2. PHP 7.1.25

**Steps to reproduce** (*)
1. Go to Magento admin
2. Create a new store view (Store > All Store > Create Store View)
3. Now Change the New Store View Currency &
![Screenshot (7)](https://user-images.githubusercontent.com/50043226/57057854-8bba9d00-6cc9-11e9-857d-692c7e54bbae.png)
4. Add  Currency rate 
![Screenshot (8)](https://user-images.githubusercontent.com/50043226/57057898-cae8ee00-6cc9-11e9-99da-6303ac835780.png)
5. Go to frontend, first change the store view and click on category "Gear > Bags"
6. Add taxable product "Push It Messenger Bag" to cart (qty = 1)
7. Go to checkout
8. Continue as guest or as authenticated user
9. Provide shipping address with country United States (according to tax country configured)
10. Place order
11. And check the order confirmation mail.

**Expected result** (*)
1. Tax amount should be comes first 
![Screenshot from 2019-05-02 11-16-38](https://user-images.githubusercontent.com/50043226/57058220-20be9580-6ccc-11e9-89a5-581590359ba6.png)

**Actual result** (*)

![Screenshot from 2019-05-02 11-21-11](https://user-images.githubusercontent.com/50043226/57058274-8743b380-6ccc-11e9-8ecd-35992d4565d0.png)

**Comment by deepakk-webkul** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar, here is your [Magento instance](https://i-22583-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22583-2-3-develop.instances.magento-community.engineering/admin](https://i-22583-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @maheshWebkul721
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @webkul-deepakkumar
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by deepakk-webkul** [comment]
I was able to reproduce this issue on vanilla Magento instance
![Screenshot (9)](https://user-images.githubusercontent.com/50043226/57064192-38eddf00-6ce3-11e9-9fa6-bc211c6222a2.png)

**Comment by krishprakash** [comment]
Hi @webkul-deepakkumar.
Can you please explain in more detail i'm not able to reproduce this issue.
Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99494`, `MAGETWO-99495` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by surabhisrivastava09** [comment]
I am working on this at #dmcdindia1

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance #dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @ManishGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ManishGangola-Webkul, here is your [Magento instance](https://i-22583-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22583-2-3-develop.instances.magento-community.engineering/admin](https://i-22583-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Duplicate issue https://github.com/magento/magento2/issues/21768

**Comment by Vishrootways** [comment]
Facing the same issue on Magento 2.3.3, any workaround to this?
