### ISSUE TITLE
Cart form default action is to empty cart

### ISSUE THREAD

**Issue by aario** [magento/magento2#22597]
### Preconditions (*)

1. Magento 2.3.1
2. Firefox, Chrome, Safari

### Steps to reproduce (*)

1. Add a product to cart
2. Go to cart page
3. Edit the quantity
4. Press enter inside quantity input box

### Expected result (*)

1. Quantity must be updated

### Actual result (*)

1. Cart gets empty

### More info:
It happens in:
`vendor/magento/module-checkout/view/frontend/templates/cart/form.phtml`
Where there are two submit buttons in a form:
```
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */ __('Clear Shopping Cart') ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
        </button>
```
When the `Enter` key is pressed inside quantity input box, the browser automatically chooses the first submit button which is to `empty_cart`. Order of these buttons should be reversed or a javascript added to define the default behavior when `Enter` key is pressed.

### Additional Information (*)

FYI: This issue is only reproduced on **magento 2.3.1**  not in 2.3 nor in 2.2

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22597-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22597-2-3-develop.instances.magento-community.engineering/admin](https://i-22597-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Not reproduced on magento 2.3 instance which provided by magento.
But i have tested in my local 2.3.1 instance and issue is reproduced.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99497` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-22597-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22597-2-3-develop.instances.magento-community.engineering/admin](https://i-22597-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Shubham0492** [comment]
Reproduced on 2.3.x

**Comment by Shubham0492** [comment]
But i noticed if cart page loaded completely(Estimate shipping section) then update item quantity otherwise it's empty.

**Comment by krishprakash** [comment]
@Shubham-Webkul, In 2.3.1 after proper page load this issue is appeared.
Thanks for your response.

**Comment by ghost** [comment]
I am working on this issue

**Comment by rogyar** [comment]
I cannot reproduce this issue on 2.3-develop branch. If this issue is related to 2.3.1, it's probably fixed in 2.3-develop

**Comment by krishprakash** [comment]
I'm closing this issue as it's fixed in future releases.

**Comment by hostep** [comment]
Indeed, this ticket duplicates at least https://github.com/magento/magento2/issues/21499 & https://github.com/magento/magento2/issues/22042 & https://github.com/magento/magento2/issues/22137. The fix was done in https://github.com/magento/magento2/pull/21509 (for 2.3) and https://github.com/magento/magento2/pull/21512 (for 2.2) and should get rolled out in Magento 2.3.2 & 2.2.9

**Comment by marco7319** [comment]
Hello
I installed magento 2.3.2 with Luma theme,
when I add product to cart, the basket remains empty
Thank you

**Comment by marco7319** [comment]
empty cart when adding product, reproduced in magento 2.3.2. with theme Luma
