### ISSUE TITLE
Unable to change Product URL Suffix and Category URL Suffix when using custom prefix on Magento tables

### ISSUE THREAD

**Issue by maxrasguidogoja** [magento/magento2#2259]
I'm using the custom prefix for tables in my install, when I try to change Product URL Suffix and Category URL Suffix I get the following error:

![UPDATE error](https://cloud.githubusercontent.com/assets/14097399/10941989/578aeeea-82e4-11e5-80df-32203eec84cd.png)

**Comment by choukalos** [comment]
Created internal ticket - MAGETWO-44997

**Comment by vkholoshenko** [comment]
The issue has been fixed in 42f74ccf60874034536a4311ad4eac7d531e34ce. Thanks for reporting!
