### ISSUE TITLE
2.2.8 Order workflow - orders not set to complete after order shipped.

### ISSUE THREAD

**Issue by pietervanuhm** [magento/magento2#22591]
### Preconditions (*)

1. Magento Open Source 2.2.8
2. After order processing we have a custom status **PostNL** (processing), this status will remain until we fully shipped the order.
2. Update order shipment and tracking by API 
2. Order not set to complete

### Steps to reproduce (*)

1. Update from 2.2.7 to 2.2.8
- For processing orders with custom status **PostNL** (processing)
2. Sent Shipping by API with /rest/default/V1/shipment
3. Shipment is created
4. Sent Tracking by api with /rest/default/V1/shipment/track
5. Tracking is created
-- Order have now Invoice, Shipment and Tracking
6. Order is not set to Complete
-- 

### Expected result (*)

- For processing orders with custom status **PostNL** (processing)
2. We sent Shipping by API with /rest/default/V1/shipment
3. Shipment is created
4. We sent Tracking by api with /rest/default/V1/shipment/track
5. Tracking is created
-- Order have now Invoice, Shipment and Tracking
6. Order set to Complete

### Actual result (*)

- For processing orders with custom status **PostNL** (processing)
2. Sent Shipping by API with /rest/default/V1/shipment
3. Shipment is created
4. Sent Tracking by api with /rest/default/V1/shipment/track
5. Tracking is created
-- Order have now Invoice, Shipment and Tracking
6. Order is **not** set to Complete

Is there something changed in Magento 2.2.8 that we need to do an extra handing by api to complete the order?

**Comment by irajneeshgupta** [comment]
dmcindia1

**Comment by irajneeshgupta** [comment]
I am working on this at #dmcdindia1

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-22591-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22591-2-2-develop.instances.magento-community.engineering/admin](https://i-22591-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-22591-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22591-2-2-develop.instances.magento-community.engineering/admin](https://i-22591-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-22591-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22591-2-2-develop.instances.magento-community.engineering/admin](https://i-22591-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
Hi @pietervanuhm,
thank you for your report.
I could not reproduce the mentioned issue while using the appropriate resource for shipment creation `salesShipOrderV1`.

The `/V1/shipment` endpoint should be used in case you need to update the existent shipment.

Please check the following guide for more details:
https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-shipment.html

**Comment by pietervanuhm** [comment]
@dmytro-ch 
Thanks for investigate this issue. But i still have a question..
An order have correctly qty Ordered, invoiced and shipped, should the order now go automatically complete or do we need to do something else to complete the order?
Because this was always working but since 2.2.7 or 2.2.8 this is not working anymore..

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-22591-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22591-2-2-develop.instances.magento-community.engineering/admin](https://i-22591-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@pietervanuhm, sorry for late reply and thanks for your patience!

After performing some internal checks, I agree that the order state should be changed to `complete` in the described case. It's pretty obvious after checking the conditions in `\Magento\Sales\Model\Order\StateResolver::getStateForOrder` method.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17621` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by pietervanuhm** [comment]
Just a quick update: This issue is still remaining on 2.3.2

**Comment by duckchip** [comment]
i can reproduce this on m2.3.5.

**Comment by nikhil91100** [comment]
Any update on this issue . I have this issue in magento 2.3.2.

**Comment by btantlinger** [comment]
We're still seeing this issue intermittently on version 2.4.2
