### ISSUE TITLE
"Invalid Form Key. Please refresh the page." error when assigning more than 1,200 products to a category.

### ISSUE THREAD

**Issue by muckee** [magento/magento2#22600]
### Preconditions (*)

1. Ubuntu 18.04
2. Apache 2.4
3. PHP 7.2
4. Magento 2.3.x
5. Magento sample data

### Steps to reproduce (*)

1. Go to the category with  more than 1000+ products
2. Open 'Products in category' section
3. Uncheck 'Select all' checkbox and check it again
4. Press 'Next page' button

### Expected result (*)

1. Products successfully selected
2. User is able to proceed and save the category configuration

### Actual result (*)

1. Upon selecting all entries on the 7th page with 200 results per page, the user receives an error: "Invalid Form Key. Please refresh the page." 
![image](https://user-images.githubusercontent.com/51680850/65860682-6e225a00-e373-11e9-990c-b094b42a6c76.png)

I have read that this can be a problem with PHP's `max_input_vars` setting, which I have changed to 75,000. I have cleared the cache and my browser and the problem persists.

**Comment by muckee** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood, here is your [Magento instance](https://i-22600-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22600-2-3-develop.instances.magento-community.engineering/admin](https://i-22600-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by muckee** [comment]
I can't reproduce the code without sample data. Is there any way to create an instance with sample data?

I could manually re-create all of the products, categories and product attributes, but that would take a very long time.

**Comment by muckee** [comment]
The [magento stack exchange answer by Ahmad Vaqas Khan](https://magento.stackexchange.com/a/171089/60221) shows the solution.

The problem here is the documentation. It explains that the `/etc/php/7.2/cli/php.ini` file should be edited, but not the `/etc/php/7.2/apache2/php.ini` file.

I've been away from magento for a while so I'd forgotten, but I had the same problem when developing a website.  The documentation clearly specifies an incorrect file, or incomplete list of files.

**Comment by vikalps4** [comment]
I am working on this issue at #dmdcindia1

**Comment by vikalps4** [comment]
I am working on this at #dmcdindia1

**Comment by vikalps4** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vikalps4. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vikalps4, here is your [Magento instance](https://i-22600-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22600-2-3-develop.instances.magento-community.engineering/admin](https://i-22600-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vikalps4** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vikalps4. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vikalps4, here is your [Magento instance](https://i-22600-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22600-2-2-develop.instances.magento-community.engineering/admin](https://i-22600-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by muckee** [comment]
@vikalps4 how can I install sample data on the magento test instances?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20620` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chickenland** [comment]
@JoshuaFlood Is this an actual issue within Magento?  From reading through this, it looks like it was an issue with max_input_vars, and you edited the wrong file.  It looks like the documentation you used was from Stack exchange rather than any Magento documentation?  I think this could be closed if that's the case?

**Comment by muckee** [comment]
@chickenland this is largely an issue with magento's documentation. It's massively flawed. Attempting to set up an instance with proper https, php, nginx/apache configuration etc. on almost any system, aside from one of the instances created by the engcom robot, produces all kinds of weird and wonderful errors. I've never managed to build a stable, deployable instance without implementing workarounds or googling for CLI commands which are not mentioned anywhere within the official documentation.

Yes, you are right in thinking that I am referring to unofficial documentation, but that is exactly my point. I have just found [this page](https://devdocs.magento.com/guides/v2.3/install-gde/trouble/php/tshoot_php-set.html?itm_source=devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=max_inpu) in the official documentation, which provides some insight, but it does not mention the error message that is actually displayed, so there is no way of locating it within the documentation until we already know the answer.

It is a UX bug. An error message has been provided to the end user without any supporting documentation. Either the bug should be fixed (in this case, downloading magento with sample data should not be possible.. it is outside of the scope of the current documentation and breaks the application). Or, supplementary documentation should be provided to explain this error message within the documentation in an easy-to-locate format, so it is no longer a bug.

**Comment by muckee** [comment]
I know that Magento just got bought out by Adobe, so hopefully their added resources will provide more of a focus on up-to-date documentation but, honestly, I've abandoned Magento because the documentation is just... absent.

When you spend weeks trying to solve a problem in your code, only to find that the controller you are relying on hasn't even been written (another issue I had with 2.1), it makes you wonder why the developers of the software are even allowed to mention production environments.

**Comment by chickenland** [comment]
Hi @JoshuaFlood Thanks for confirming.  I completely agree, however, it's going to be your webserver that hits this limit rather than Magento (the application) so I'm not aware that Magento could surface a better error message than the one it currently is (apart from "oops, something went wrong" so that it doesn't lead you down the garden path).  I don't think it's in Magento's remit to try and cover all possible server configurations.

I'll go ahead and close this ticket - The devdocs are a separate repository, so a PR can be made against this - https://devdocs.magento.com/guides/v2.3/install-gde/trouble/php/tshoot_php-set.html
