### ISSUE TITLE
Attention! Something went wrong.

### ISSUE THREAD

**Issue by dilsunlife** [magento/magento2#22604]
### Preconditions (*)

1. Magento 2.2.0 
2. Getting Error Attention! Something went wrong.
3. A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

![image](https://user-images.githubusercontent.com/10502226/57089682-9f462200-6d22-11e9-9e52-31eebad90903.png)

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. 
![image](https://user-images.githubusercontent.com/10502226/57089617-73c33780-6d22-11e9-8732-66e7f86d2edd.png)

### Actual result (*)

1. [Screenshots, logs or description]
2. I am getting below error. anyone help me how to solve.

**Comment by orlangur** [comment]
@dilsunlife `2.2.0` is pretty old, are you able to reproduce an issue on a clean Magento installation?

**Comment by ghost** [comment]
Hi @dilsunlife thank you for your report ! I am not able to reproduce this issue , probably the problem is with your custom modules
