### ISSUE TITLE
The products are not reindexed after batch (group) moving to another store while indexers mode is «Update on Save»

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2260]

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
