### ISSUE TITLE
Since Magento 2.3 the wysiwyg image uploader incorrectly uses pub/media as storage root.

### ISSUE THREAD

**Issue by hostep** [magento/magento2#22609]
### Preconditions (*)
1. Magento 2.3.1 or 2.3-develop (I've used commit d3fdecf0d0f, can't use the latest commit 28757e409c9 since it breaks the backend due to some 'unserialize' warnings)
2. PHP 7.1.27

### Steps to reproduce (*)
1. In the backend go to Content => Pages
2. Click 'Add New Page'
3. Expand the 'Content' section, click 'Show / Hide Editor' and click 'Insert Image...'

### Expected result (*)
1. The Storage Root being represented by `pub/media/wysiwyg`
2. <img width="1076" alt="Screenshot 2019-05-02 at 20 54 14" src="https://user-images.githubusercontent.com/85479/57100101-6441ef80-6d1e-11e9-97d6-80706ab68e8d.png"> (screenshot is from 2.2-develop)

### Actual result (*)
1. The Storage Root being represented by `pub/media`
2. <img width="1077" alt="Screenshot 2019-05-02 at 21 01 48" src="https://user-images.githubusercontent.com/85479/57100126-715ede80-6d1e-11e9-81b6-cdf779e73214.png">

### Discussion
I think this is incorrect in Magento 2.3.x, as it would allow non-technical users to delete/change files they probably shouldn't touch. For example I was perfectly able to just remove the `pub/media/catalog` directory using this interface, which is not a really good idea ...

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99520` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vishal-7037** [comment]
I am working on this at #dmcdindia19

**Comment by Darkbelg** [comment]
This issue is reproducible on version 2.2.9.

**Comment by pemann** [comment]
I think this commit has changed the root folder: https://github.com/magento/magento2/commit/a270b5b1a5d0cbec6752d1e95d797d3d84d000b8#diff-624b27794e761bd53831eba1ede517bcR74

**Comment by hostep** [comment]
I've left some more findings of this problem in https://github.com/magento/magento2/pull/22681#issuecomment-521386307

I think the biggest problem is that if the `wysiwyg` directory does not exist yet, you see the behavior I initially reported. But when you manually create a `wysiwyg` directory, it will correctly select that one as a default in the tree. So that would already be a first good solution if that can happen automatically.

But I still feel like the root of tree itself should also be set to the `wysiwyg` directory in this case.

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#24878 by @hostep in 2.4-develop branch
Related commit(s):
 - [99a9405b24083c88d00bb35a2be2248d3d1d3f07](https://github.com/magento/magento2/commit/99a9405b24083c88d00bb35a2be2248d3d1d3f07)

The fix will be available with the upcoming 2.4.0 release.

**Comment by ganeddact** [comment]
I'm sorry to reopen this issue, but with several 2.4.2 installations I'm facing this issue, the wysiwyg opens the storage root from pub/media and not pub/media/wysiwyg.
I can see that files in merged fix are present, so I should be up to date with the current status. Has something else changed after the merge? I can't explain why I'm running in this issue
