### ISSUE TITLE
On the home page some images are not displayed and the file "/pub/media/styles.css" is not generated, some category images are also not displayed

### ISSUE THREAD

**Issue by mozgbrasil** [magento/magento2#22603]
### Preconditions (*)

Magento 2.3.1

https://imgur.com/g8g7RUO

### Steps to reproduce (*)

I have been developing the following project that has the purpose of automating the construction of Magento2 in order to facilitate the evangelization of the platform.

https://github.com/mozgbrasil/deploy-magento2#install

The installation of Magento works as expected, displaying all the images from the "sample data"

But at the time of re-deploying the magento, problems occur

https://github.com/mozgbrasil/deploy-magento2#deploy--re-deploy

On the home page some images are not displayed and the file "/pub/media/styles.css" is not generated, some category images are also not displayed

See process instalation 

https://imgur.com/NLYpMuF
https://imgur.com/EMooFsm
https://imgur.com/XnRdWq9
https://imgur.com/nb7daXS
https://imgur.com/BgUO5Sd
https://imgur.com/mcdbG5c
https://imgur.com/5se5INd
https://imgur.com/bc9FLlE
https://imgur.com/2yy1DsL
https://imgur.com/WclO9Dj

See process re-deploy, using same database

https://imgur.com/a4CprNy
https://imgur.com/oah0SIM
https://imgur.com/DnNiHuU
https://imgur.com/TgcpLYj
https://imgur.com/xX5Gpho
https://imgur.com/rtclnhQ
https://imgur.com/UiGPfqO
https://imgur.com/N7wpFZV
https://imgur.com/NJz2fMW
https://imgur.com/08BXtEX
https://imgur.com/EYLT3yK
https://imgur.com/g0gg90y
https://imgur.com/g8g7RUO

### Expected result (*)

1. [Screenshots, logs or description]

https://imgur.com/2yy1DsL
https://imgur.com/WclO9Dj

### Actual result (*)

1. [Screenshots, logs or description]

https://imgur.com/g0gg90y

###

-

Thank you in advance for those who can contribute to the improvement of the project.

-

I have a deployment on AWS EBS in

http://304674501456-test-webapp014.us-west-2.elasticbeanstalk.com/

The magento is in

http://304674501456-test-webapp014.us-west-2.elasticbeanstalk.com/magento/

and the backend in

http://304674501456-test-webapp014.us-west-2.elasticbeanstalk.com/magento/admin/

You can access as

admin / 123456a

###

**Comment by mozgbrasil** [comment]
yes

**Comment by hiren-aimsinfosoft** [comment]
I am working on this at #dmcdindia19.

**Comment by magento-engcom-team** [comment]
@hiren-aimsinfosoft thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by hiren-aimsinfosoft** [comment]
Hello @mozgbrasil ,

I can reproduce this error in My Magento 2.3-develop branch

I have added sample data in this branch and then deployed it and I can produce this error.

Screenshot of the error from my end : http://prntscr.com/nk859t 

**For Solution** 

1. Go to <Magento root directory> / pub / media / and then open file .htaccess [ http://prntscr.com/nk861r ] in your editor.

2. Find line with text `Options +FollowSymLinks `
expected line no is : 23

3.  Comment this line . For comment this line you can add `#` in the beginning of the line.  screenshot :  `http://prntscr.com/nk874o`

4. After that **Flush** Magento cache using command `bin/magento cache:flush` .

5. Then you can check that your media images will be appear in your site.

6. If you still not getting only product media images then try to run command : `bin/magento catalog:images:resize` and wait for complete this.

7. After that **Flush** Magento cache using command `bin/magento cache:flush` and check you site for images issue .

Please check this step and follow this.

If you still facing an issue then let me know exact step to reproduce this. 

**Screenshot of done task** : http://prntscr.com/nk8ame , http://prntscr.com/nk8ask

Thanks
Hiren Patel

**Comment by mozgbrasil** [comment]
Hello

Thanks for interacting

Conform images did not succeed

See that an error is returned in the attempt to resize the images, even if it is an installation via Composer where the intention is that Composer has already downloaded the images from Sample Data

https://drive.google.com/open?id=1SG-b2N4WeZBmwbBCE5Q8ClhJjin1Xj-i

**Comment by mozgbrasil** [comment]
I updated my repository with the appropriate automation, but this part for the time being without success

https://github.com/mozgbrasil/deploy-magento2

**Comment by hiren-aimsinfosoft** [comment]
Hello @mozgbrasil 

I am working with your repository.

**Comment by mozgbrasil** [comment]
Hello @hiren-aimsinfosoft 

Thank you, if I can help you, please let me know.

**Comment by hiren-aimsinfosoft** [comment]
Hello @mozgbrasil ,

I have did clone in my local from your repository `https://github.com/mozgbrasil/deploy-magento2` .

I have followed below step to setup.

1. git clone https://github.com/mozgbrasil/deploy-magento2
2. cp env-example .env
3. nano .env [ I have setup my data base information and site baseurl in this. ]
4. composer install

Once I install I did not get any images in frontend page.

Once I changed following thing in File vendor/magento/framework/View/Element/Template/File/Validator.php

I have commented one line and added one line.

> Line No. 138::  //$realPath = $this->fileDriver->getRealPath($path);
> Line No. 139::  $realPath = str_replace('\\', '/',$this->fileDriver->getRealPath($path));

Then I have flushed the cache using `php bin/magento cache:flush` and then permission to var pub generated/ using command `chmod -R 777 var pub generated/`

I have attached screenshot what I have done with code and screenshot of the front store.
![2019-05-17_014227](https://user-images.githubusercontent.com/50257430/57885512-b6b7fb80-7848-11e9-8363-2f0d0ee8f047.png)
![2019-05-17_021028](https://user-images.githubusercontent.com/50257430/57885721-2f1ebc80-7849-11e9-970f-68df3edbb5a3.png)

Please check like this and let me know if any.

Thank you
Hiren Patel

**Comment by mozgbrasil** [comment]
Hello

Now after the installation is running run the following command

    ls
    rm -fr magento backdoor composer.lock
    ls
    composer install -vvv

You should note that the installation process should not be done, but the deployment process should be done.

Note that the deployment process automatically creates the config.php and env.php files

It is at this point that it generates the occurrences of errors

Thank you for now

**Comment by mozgbrasil** [comment]
Hello @hiren-aimsinfosoft  @magento-engcom-team  @AlexWorking  @krishprakash 

If possible I would like some positioning informing if this occurrence is something in Magento

Would you have some more support in Magento to solve this problem

As I made available my script that has the purpose of automating the installation of Magento implantation I thought it would be easy to reproduce the occurrence

Unfortunately the occurrence I mention occurs in both local environment and AWS EBS, 

if you can help thank you

Also I already got to post the occurrence in the forum but I did not get any interaction

**Comment by engcom-Charlie** [comment]
Hello 
I'm closing this issue because it is not relevant.
