### ISSUE TITLE
Update to 2.3 Issue if magento downloaded from Github

### ISSUE THREAD

**Issue by yogeshkhasturi** [magento/magento2#22619]
### Preconditions (*)

1. Magento 2.2.6 (Downloaded from Github
2. Want to update to 2.3.1

### Steps to reproduce (*)

1. 
Execute Below Cammand
```
composer require magento/product-community-edition=2.3.1 --no-update
composer require --dev phpunit/phpunit:~6.2.0 friendsofphp/php-cs-fixer:~2.10.1 lusitanian/oauth:~0.8.10 pdepend/pdepend:2.5.2 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:3.2.2 --no-update
composer remove --dev sjparkinson/static-review fabpot/php-cs-fixer --no-update
composer update
```
2. Following These steps. https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html

### Expected result (*)

1. Magento 2 dependencies should be updated. 

### Actual result (*)

1. Getting Error : 

> Could not find a matching version of package magento/product-community-edit ion. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable ).

Please Help me with the process to update or if this is an issue with GitHub Version.

Thanks

**Comment by yogeshkhasturi** [comment]
Hello @GovindaSharma,

Any Idea where how to update to 2.3.1. **composer update** method is not working with GitHub version.

Thanks
Yogesh

**Comment by orlangur** [comment]
Hi @yogeshkhasturi, here is a proper guide for Magento installed from GitHub: https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/dev_options.html
