### ISSUE TITLE
Because of inventory_sales module (MSI) : Backorder Item Status is not showing if we placed order with backorder item in magento2.3.x 

### ISSUE THREAD

**Issue by pushpagupta-magento** [magento/magento2#22616]
### Preconditions (*)

1. Magento version 2.3.0
2. Should have inventory_sales module (MSI)

### Steps to reproduce (*)

1. Set a product up as backorderable - 0 quantity stock, "allow orders below 0", in stock, enabled
2. As a frontend customer, add this backordered product to a cart
3. Add an additional "normal" stock item to the cart (not backordered - this step may not be strictly required but is useful to make it easier to compare normal vs backordered line items)
4. Go through a normal customer frontend order process with this product
5. After placing the order, note that in the order history / admin order view that the order items list shows **ordered** in the "item status" column for **backorder** item and a **normal** item as well - **this is incorrect**

![actual](https://user-images.githubusercontent.com/50232568/57130746-21345a80-6db8-11e9-8963-573dd2c22c8f.jpg)

You can also look in the database and see that the **sales_order_item** table has a **qty_backordered** column with NULL - again, this is unexpected and incorrect

<img width="501" alt="actual-db" src="https://user-images.githubusercontent.com/50232568/57130792-4d4fdb80-6db8-11e9-8dbb-654e244b24de.png">

### Expected result (*)

1. After placing the order, note that in the order history / admin order view that the order items list shows **ordered** in the "item status" column for a **normal** item  and **backordered** in the "item status" column for a **backorder** item - **this is correct**

<img width="816" alt="expected" src="https://user-images.githubusercontent.com/50232568/57130851-8720e200-6db8-11e9-9077-3bf883eed0bc.png">

You can also look in the database and see that the **sales_order_item** table has a **qty_backordered** column with 1 - again, this is expected and correct

<img width="824" alt="excepted-db" src="https://user-images.githubusercontent.com/50232568/57130875-93a53a80-6db8-11e9-85f6-b2d934b4a2a1.png">

### Actual result (*)

1. After placing the order, note that in the order history / admin order view that the order items list shows **ordered** in the "item status" column for **backorder** item and a **normal** item as well - **this is incorrect**

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22616-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22616-2-3-develop.instances.magento-community.engineering/admin](https://i-22616-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pushpagupta-magento** [comment]
Hi @krishprakash : I have found the solution for it and worked upon it and soon will generate the PR. May be you can help me to verify my PR :)

**Comment by pushpagupta-magento** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pushpagupta-magento. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pushpagupta-magento, here is your [Magento instance](https://i-22616-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22616-2-3-develop.instances.magento-community.engineering/admin](https://i-22616-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @pushpagupta-magento. 
I'm not able to reproduce this issue.
Please explain with additional steps.

**Comment by pushpagupta-magento** [comment]
I am closing this issue as this is related to MSI.
