### ISSUE TITLE
Export of Downloadable Products type

### ISSUE THREAD

**Issue by vinayshah** [magento/magento2#22612]
### Description (*)

Customers should be able to export product of type downloadable. 
### Expected behavior (*)

Customer should be able to see **downloadable_links** and **downloadable_samples**, which has all the details for Downloadable product type.
### Benefits

This will help customers to export product of type downloadable. So that customer can benefit from it and can have the information on their downloadable products.
### Additional information

The importer help in importing downloadable data, now we can have export as well.

**Comment by vinayshah** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20291` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @vinayshah. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24224` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
