### ISSUE TITLE
Deploy content files theme issue in production mode if have empty less file

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#22617]
### Preconditions (*)

Magento 2.3.1
my local tested on vagrant box
https://github.com/paliarush/magento2-vagrant-for-developers

### Steps to reproduce (*)

1. Deploy clean magento instance
2. Enable production mode
3. Create new theme based on luma as parent: Ex Magento/winter
path app/design/frontend/Magento/winter
4. Create required file composer.json theme.xml registration.php 
5. Inside new theme folder create web/css/source folder
6. Create empty file less with name _extends.less or _theme.less inside source folder (totally empty file without any comment)
app/design/frontend/Magento/winter/web/css/source/_theme.less
7. run php bin/magento setup:upgrade for register theme
8. run php bin/magento setup:di:compile (optional)
9. run php bin/magento setup:static-content:deploy en_US -f

Guide link for create theme
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-create.html

### Expected result (*)

All green success deploy 

### Actual result (*)

Error in in last line
The contents from the "/var/www/html/pub/static/frontend/Magento/winter/en_US/css/styles-m.css" file can't be read No such file or directory 
File related with problem in console
Magento\Framework\View\Asset\File->getSourceFile() In File.php line 151

some red error while deploy (undefined variable)

Here is my theme structure
![Screenshot from 2019-05-03 17-47-33](https://user-images.githubusercontent.com/1908873/57133047-cdcc0780-6dcb-11e9-8061-d3dc00e894f9.png)

![Screenshot 2019-05-03 22 46 40](https://user-images.githubusercontent.com/1908873/57149243-7c387280-6df5-11e9-81ff-2315866d53e2.png)

### Things i have done
Try remove files and re-deploy but not get any luck
rm -rf var/view_preprocessed/* pub/static/frontend/* var/page_cache/*

**Comment by ghost** [comment]
Hi @mrtuvn ! Thank you for your report but i am not able to reproduce this issue on magento 2.3.1 . Please provide more more steps to reproduce

**Comment by mrtuvn** [comment]
@engcom-backlog-nazar i have updated info can you try to reproduce issue one again

**Comment by mrtuvn** [comment]
Updated reproduce steps! Anyone checking this because i can reproduce problem in my local

**Comment by mrtuvn** [comment]
steps reproduce is seem clearly now

**Comment by ghost** [comment]
Hi @mrtuvn thank you for your updates, i;m not able to reproduce on fresh magento 2.3.1 and 2.3-develop, seems like this related to your configuration, or file system permission, feel free to reopen if issue still exists.
