### ISSUE TITLE
Disabled multiselect fields in system configuration are saved clearing the configuration

### ISSUE THREAD

**Issue by phoenix128** [magento/magento2#22618]
### Preconditions (*)
1. Magento 2.2+ with at least 2 websites
2. At least one configured payment methods
3. Configuration dumped to `config.php`

### Steps to reproduce (*)
1. Open System > Config > Sales > Payment Method
2. Switch your view from global to any of your websites
3. Click on save without modifying anything

### Expected result (*)
1. Disabled fields are not modified

### Actual result (*)
1. Every multiselect field in the page is cleared and "Use default value" unchecked

### Additional
This issue seems to be introduced by commit db9be6ae9059c96035dcba32ac6caee32ddde78f and tracked to `\Magento\Framework\Data\Form\Element\Multiselect::getElementHtml`.

Specifically, removing the following lines seems to fix the issue, but I don't know why they were added and I don't know if removing them may cause some side effect:

```
        if (!empty($this->_data['disabled'])) {
            $html .= '<input type="hidden" name="' . parent::getName() . '_disabled" value="" />';
        }
```

**Comment by kassner** [comment]
#22891 might fix this one as well. Can you test it @phoenix128?

**Comment by phoenix128** [comment]
Thank you @kassner for your contribution.
Your fix seems to be correctly working, I am reviewing your PR right now.

**Comment by engcom-Charlie** [comment]
Hello everyone!
I am closing this issue because it is not relevant.
