### ISSUE TITLE
Magento 2.3.0 Admin grid using UI component sticky CSS is not working

### ISSUE THREAD

**Issue by Patelcc** [magento/magento2#22614]
### Preconditions (*)

1. Magento version CE 2.3.0
2. PHP version 7.1.
3. Admin area

### Steps to reproduce (*)

1. Create admin grid using Ui-component Make sure Sticky true `<sticky>true</sticky>`
2. Display only grid don't add button `<buttons></buttons>` just above the grid. 
3. Because I just want to display the record in a grid I don't need any form so there is no need to display button in the grid page.

### Expected result (*)
 
![without-sticky](https://user-images.githubusercontent.com/40203855/57120677-8f652700-6d90-11e9-957f-d674d958f637.png)

1. sticky is true and a button is not added then scroll down sticky CSS should be working.

### Actual result (*)

![with sticky](https://user-images.githubusercontent.com/40203855/57120736-f1be2780-6d90-11e9-992c-c56ab8169be5.png)

1. Sticky is true and a button is not added then scroll down sticky CSS is not working.

**Comment by NishaJangid** [comment]
I am working on this at #dmcdindia19”

**Comment by magento-engcom-team** [comment]
@NishaJangid thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by amitvishvakarma** [comment]
#imagine2019

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99686`, `MAGETWO-99687` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment]
Hello,
I've fixed this issue here [#23247](https://github.com/magento/magento2/pull/23247). So I'm closing this issue.
Thanks
