### ISSUE TITLE
Stock Status of configurable products seems inconsitent

### ISSUE THREAD

**Issue by amenk** [magento/magento2#22622]
### Preconditions (*)
1. Magento  2.2.8
2. Want to verify also on 2.3.1

### Steps to reproduce (*)
1. Create a configurable product with SKU "shirt" and simples shirt-L and shirt-M via API (or backend???)
2. shirt-L and shirt-M shall have manage_stock = false
3. shirt has manage_stock = true
### Expected result (*)

1. shirt stock is visible because manage_stock = false of the simples does not mean it is out of stock

### Actual result (*)

1. shirt now is out of stock, and not displayed in list views

**Comment by amenk** [comment]
@magento-engcom-team give me 2.2.8 instance

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by amenk** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @amenk, here is your [Magento instance](https://i-22622-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-22622-2-2-8.instances.magento-community.engineering/admin](https://i-22622-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
> shirt-L and shirt-M shall have manage_stock = false
> shirt has manage_stock = true

This is obviously not a valid configuration.

**Comment by amenk** [comment]
@orlangur Thanks for checking. But I don't understand it. Can you elaborate?

We do not understand why the configurable has a stock configuration at all ... but it's set automatically to manage_stock = true when creating via API and we are wondering why is that - because it causes the configurables to be hidden.

**Comment by amenk** [comment]
@orlangur Bump ;-)
