### ISSUE TITLE
On installing; database section, PHP deprecated message

### ISSUE THREAD

**Issue by gigadesign1** [magento/magento2#2262]
When I want to set up Magento, on step 2, I get a deprecated warning:

Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

PHP version: 5.6.10

**Comment by mazhalai** [comment]
@gigadesign1 what branch are you on?

**Comment by gigadesign1** [comment]
@mazhalai master

**Comment by mazhalai** [comment]
@gigadesign1 there is a fix in the `develop` branch. Please try again.

**Comment by JuanxCursed** [comment]
I have same problem here.
I already set `always_populate_raw_post_data` to `-1`, but still not working and asking to set to `-1`.

**Comment by mazhalai** [comment]
@juanmonstra is it possible you have multiple php.ini files? Please create a temporary file with `phpinfo()` and check the value of `always_populate_raw_post_data` in it.
