### ISSUE TITLE
Customer group pricing not showing in frontend (advanced pricing, tier price)

### ISSUE THREAD

**Issue by tsifra** [magento/magento2#22629]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)
1. Edit product advanced pricing. Create record Website - All websites, Customer group - Wholesale, Qty - 1, Price - Fixed, Last field - [some price less than the base]
2. Change group to wholesale for selected customer
3. Log in frontend with customer from 2 (wholesale group)
4. Go to category with product
5. Go to product page
6. Add product to cart

### Expected result (*)

1. See product tier price for wholesale customer group (discounted) on category page 
2. See product tier price for wholesale customer group (discounted) on product page 
3. See product tier price for wholesale customer group (discounted) on cart page

### Actual result (*)

1. Have base product price on category page
2. Have base product price on product page 
3. See discounted product price (from tier table) on cart page

**Comment by tsifra** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tsifra. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tsifra, here is your [Magento instance](https://i-22629-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22629-2-3-develop.instances.magento-community.engineering/admin](https://i-22629-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tsifra** [comment]
i've checked your 2.3-develop instance and can confirm this unexpected behavior

**Comment by darshan-khatri-16** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@darshan-khatri-16 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by darshan-khatri-16** [comment]
The issue is not reproducible.

**Comment by tsifra** [comment]
> The issue is not reproducible.

darshan-khatri-16 which step is not reproducible? I've done this on my environment and reproduced situation on instance offered by magento team. Do you need more steps to reproduce on clean instance?

.. Create new category
.. Create new product
.. Register new customer

It's very important that you set product price for qty = 1 for all customer groups and mage working exactly as expected. But if product price is changed for qty = 1 and current customer group. you can see this price only in cart.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22629-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22629-2-3-develop.instances.magento-community.engineering/admin](https://i-22629-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by darshan-khatri-16** [comment]
Hi tsifra,

I have verified in on all the pages with customer group wholsesale. Let me share screenshot with you.
![Screenshot from 2019-05-04 10-39-52](https://user-images.githubusercontent.com/39530983/57174215-141b7800-6e59-11e9-849f-04df08b099f1.png)
![Screenshot from 2019-05-04 10-41-37](https://user-images.githubusercontent.com/39530983/57174224-390feb00-6e59-11e9-9b70-2552e6004dca.png)

**Comment by tsifra** [comment]
> Hi tsifra,
> 
> I have verified in on all the pages with customer group wholsesale. Let me share screenshot with you.

Could you check it on instance that was offered to me right now, while it's not cleaned?
Admin access: https://i-22629-2-3-develop.instances.magento-community.engineering/admin
Login: admin Password: 123123q
Frontend login test@test.com - Qweqweqwe123

i've followed steps described by me and can confirm, that result is still the same. Right price for current customer can be seen only in shopping cart. Not in catalog, not on product page.

**Comment by darshan-khatri-16** [comment]
Hi tsifra,
Its working fine on this instance as well. Please find below screenshot.
![Screenshot from 2019-05-04 11-18-43](https://user-images.githubusercontent.com/39530983/57174557-6b701700-6e5e-11e9-8daf-ede66fd80f48.png)

![Screenshot from 2019-05-04 11-18-52](https://user-images.githubusercontent.com/39530983/57174562-70cd6180-6e5e-11e9-8822-599622b88611.png)

**Comment by tsifra** [comment]
Hi, darshan-khatri-16 Have no idea what's happening but price right for test product is okay. Here is screenshot that i've made right after repeating test case. I've created new product right now and price is okay again. Do you have any ideas what was it? I still have issue on my local instance running 2.3.1
![image](https://user-images.githubusercontent.com/5971188/57174716-bfbdcb80-6e4b-11e9-8df1-67b980765864.png)

**Comment by darshan-khatri-16** [comment]
Hi tsifra,
Good to hear that now it's working for you. After revising product price you need to perform below steps

1. Do the Magento reindexing
2. If you already logged in then kindly please once log out and log in back again.

Let me know if you need any further help needed.

**Comment by tsifra** [comment]
Reindexing is disabled on the instance offered by mage team as i can see message in top of admin. Anyway thanks for assistance. Some kind of my fault. Need further investigation.

**Comment by darshan-khatri-16** [comment]
Sure.

**Comment by koenner01** [comment]
I can confirm this behaviour on 2.3.2.
- Create price rule for specific customer group
- Go to catalog page where any of the discounted products should be
- Log in
=> after log-in the prices will appear to be correct
- Add a product to cart
- See that the product was added with base price to cart (not discounted)
- Refresh page to see products not having the price rule applied

**Comment by koenner01** [comment]
We have found that the "Disable Automatic Group Change Based on VAT ID" on the customer account configuration is the cause of this _problem_ 

We setting the checkbox to true, for us it resolved the problem. But we are unsure if it's intended behaviour if adding/removing a product to and from the cart that it would validate the customer VAT.

However all of the above is kinda moot as in 2.3.4 we could not reproduce this anymore.

**Comment by elfeffe** [comment]
@koenner01 I confirm that this is still happening in 2.3.4, I had to Disable Automatic Group to make it work in a custom customer group.

**Comment by theodorhanu** [comment]
@magento-engcom-team give me 2.4.1 instance

**Comment by lazanicol90** [comment]
@magento-engcom-team give me 2.4.1 instance

**Comment by lazanicol90** [comment]
@magento-engcom-team give me 2.4.1 instance

**Comment by delessandrei** [comment]
@magento-engcom-team give me 2.4.1 instance
