### ISSUE TITLE
I want like keyword search with mysql in catalog search configuration i did not find any configuration related to this 

### ISSUE THREAD

**Issue by srikanth829** [magento/magento2#22620]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by krishprakash** [comment]
Hi @srikanth829. Thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the Community Forums or the Magento Stack Exchange site for your queries.

**Comment by srikanth829** [comment]
Thanks @krishprakash
