### ISSUE TITLE
Asterisk(*) sign position does not consistent in admin

### ISSUE THREAD

**Issue by magesanjay** [magento/magento2#22638]
Asterisk(*) sign position does not consistent in admin

### Preconditions (*)
magento 2.2
magento 2.3

### Steps to reproduce (*)
1. Go to admin
2. Sales > Orders
3. Create new order > Create new customer
4. Review the asterisk(*) sign position

### Expected result (*)
In whole admin asterisk(*) sign postion should be right side.

### Actual result (*)
![bug_snap](https://user-images.githubusercontent.com/39721144/57174268-f864a180-6e59-11e9-8871-872dc6185ca6.png)

**Comment by krishprakash** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@krishprakash thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22638-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22638-2-3-develop.instances.magento-community.engineering/admin](https://i-22638-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22638-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22638-2-2-develop.instances.magento-community.engineering/admin](https://i-22638-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99546`, `MAGETWO-99547` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shubhamkhandelwalrtpl** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@shubhamkhandelwalrtpl thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ghost** [comment]
It seems like it isn't an issue and it was intended. 
![Screenshot from 2019-05-06 22-32-02](https://user-images.githubusercontent.com/42089978/57241898-bb620000-704f-11e9-889f-2e26b489a619.png)

**Comment by krishprakash** [comment]
Asterisk(*) sign position should be consistent through out the admin or front end.
So it should be done as per consistency.

**Comment by magento-engcom-team** [comment]
Hi @magesanjay. Thank you for your report. 
The issue has been fixed in magento/magento2#22800 by @sanjaychouhan-webkul in 2.3-develop branch
Related commit(s):
 - [4eab52881a5fd646a4283dbe5e0df2c147b25564](https://github.com/magento/magento2/commit/4eab52881a5fd646a4283dbe5e0df2c147b25564)

The fix will be available with the upcoming 2.3.3 release.
