### ISSUE TITLE
Magento 2 checkout error: payment-information REST API being “canceled”

### ISSUE THREAD

**Issue by pkavanaghjr** [magento/magento2#22632]
### Summary (*)
Our Magento 2.2.8 store is having issues at checkout recently. We are using the Magento 2 Authorize.net extension for our payment gateway.

Our issue is when a customer checks out and we watch the network tab of the inspector, the REST API call for "payment-information" is being 'canceled.' The endpoint its trying to reach is "https://domain-name.com/rest/default/V1/carts/mine/payment-information." Once this XHR call is canceled, the page attempts to reload the onepage checkout but throws an error and says "cartId is a required field."

Even though the page throws an error, the order is fully placed and goes into processing. Authorize.net is reached, the confirmation email is sent, and the order appears in the dashboard.

I believe the "cartId is a required field" error appears because the 'cartId' is no longer valid since that cartId's order has already been completed but the page refresh is looking for the same data to display.

My question is, why is "payment-information" being canceled? The few times an order has gone through without an error, "payment-information" was not canceled so I feel this is the root issue of our checkout problem, not so much the "cartId is a required field" error.

### Examples (*)
The inspector network tab has an XHR request named "payment-information." I have pasted redacted JSON data that is included in this XHR request. We are not sure why this XHR is being canceled.

```
{"cartId":"cart-id-hash","billingAddress":{"countryId":"US","regionId":"34","regionCode":"MN","region":"State","street":["Street Address"],"company":"","telephone":"","postcode":"12345","city":"City","firstname":"TEST","lastname":"TEST","saveInAddressBook":null},"paymentMethod":{"method":"anet_creditcard","additional_data":{"opaque_data":"{\"dataDescriptor\":\"COMMON.ACCEPT.INAPP.PAYMENT\",\"dataValue\":\"data-value-hash\"}","cardExpYear":"0000","cardExpMonth":"0"}},"email":"email@email.com"}
```

Any help or ideas would be greatly appreciated, thanks in advance!

**Comment by engcom-Delta** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [Magento instance](https://i-22632-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22632-2-3-develop.instances.magento-community.engineering/admin](https://i-22632-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @pkavanaghjr thank you for your report. It is hard to understand and reproduce this issue without clear steps to reproduce. 
You could refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
And if you'd like to update issue, please reopen it.
