### ISSUE TITLE
Vanishing SEO URLs/ URL Rewrites on mass attribute update add/remove store multi-store

### ISSUE THREAD

**Issue by robyerevan** [magento/magento2#22633]
### Preconditions (*)

1. Magento 2.2.3
2. Multi-store

### Steps to reproduce (*)

1. Setup store A and store B on magento
2. Add a product to store A
3. Open product page in store front
4. Go to Admin -> Catalog -> Products
5. Check product checkbox and Select Action -> update attributes
6. Click Websites tab
7. Add product to website B (checkbox) -> Save

### Expected result (*)

1. Product added to store B
2. SEO URL is created for product in store B
3 Store A SEO URL is intact

### Actual result (*)

1. SEO URL of product vanished in store A
2. Record removed from url_rewrite for product , store A
3. SEO URL is crated only for store B

**Comment by robyerevan** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @robyerevan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @robyerevan, here is your [Magento instance](https://i-22633-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22633-2-3-develop.instances.magento-community.engineering/admin](https://i-22633-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by robyerevan** [comment]
Can not reproduce on 2.3-develop instance

Issue did exist in magento 2.2.3

Code that removes all SEO url's located 
magento/module-catalog-url-rewrite/Observer/ProductToWebsiteChangeObserver.php :72

    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        foreach ($observer->getEvent()->getProducts() as $productId) {
            $product = $this->productRepository->getById(
                $productId,
                false,
                $this->request->getParam('store_id', Store::DEFAULT_STORE_ID)
            );

           $this->urlPersist->deleteByData([
                UrlRewrite::ENTITY_ID => $product->getId(),
                UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE
            ]);
            if ($product->getVisibility() != Visibility::VISIBILITY_NOT_VISIBLE) {
                $this->urlPersist->replace($this->productUrlRewriteGenerator->generate($product));
            }
        }
    }
