### ISSUE TITLE
Broken *tinymce.min.js*  js on opening wysiwyg in content section 

### ISSUE THREAD

**Issue by Eayshwary** [magento/magento2#22642]
### Preconditions (*)
Magento 2.3.1 version

### Steps to reproduce (*)
1. Go to content -> Pages
2. Then click on add new page --> Add New Page
3. Now click on Content Tab and click on show/hide editor 

### Expected result (*)
Js should not break so that it can go in one flow

### Actual result (*)
js broke please refer this from instance branch
![wysiwygbug](https://user-images.githubusercontent.com/31269039/57174479-45964280-6e5d-11e9-90f9-698a05067f1f.png)

**Comment by Eayshwary** [comment]
#dmcdindia1

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22642-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22642-2-3-develop.instances.magento-community.engineering/admin](https://i-22642-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@Eayshwary thank you for your report but this issue is not reproducible at mgento 2.3 develop instance
