### ISSUE TITLE
Typo Issue and Missing header title at Customer Sales order grid 

### ISSUE THREAD

**Issue by vishal-7037** [magento/magento2#22641]
There are typo errors found on the Magento admin panel. Please review Customer Sales order grid. You will find typo error for the order column header. In the Sales invoice grid, the header title of a column is 'Order #' and here it is 'Order'. they should be the same.

### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Login to Magento admin
2. Open Customer > All Customers > Edit any customer 
3. Check header title of Order column and header title of last column.

### Expected result (*)

![magento_customer_order_grid_fixed](https://user-images.githubusercontent.com/38535982/57174473-37e0bd00-6e5d-11e9-9117-ccd2ced2992d.jpg)

### Actual result (*)

![magento_customer_order_grid](https://user-images.githubusercontent.com/38535982/57174476-416a2500-6e5d-11e9-808f-9efce4bd5e20.jpg)

**Comment by vishal-7037** [comment]
I am working on this at #dmcdindia19

**Comment by NishaJangid** [comment]
I am working on this at #dmcdindia19”

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99565` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-22641-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22641-2-2-develop.instances.magento-community.engineering/admin](https://i-22641-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @vishal-7037. Thank you for your report. 
The issue has been fixed in magento/magento2#22643 by @vishal-7037 in 2.3-develop branch
Related commit(s):
 - [df3047bfc17f96ce37f0f9106dcf1b4eed2b5790](https://github.com/magento/magento2/commit/df3047bfc17f96ce37f0f9106dcf1b4eed2b5790)

The fix will be available with the upcoming 2.3.3 release.
