### ISSUE TITLE
Add tax rule form checkbox design is not as per the magento admin panel checkbox design, It is showing default design 

### ISSUE THREAD

**Issue by surabhisrivastava09** [magento/magento2#22640]
### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1. Go to Tax rules in Admin panel. 
2. Open Add New Tax Rule Form and click Add New Tax Rate Button.

### Expected result (*)
![Screenshot_2019-05-04_11-30-16](https://user-images.githubusercontent.com/25526119/57174687-2f26c180-6e32-11e9-82b2-c2f796cc6e42.png)

### Actual result (*)
![Screenshot_2019-05-04_11-29-57](https://user-images.githubusercontent.com/25526119/57174689-351ca280-6e32-11e9-8038-58a291cda24c.png)

**Comment by shikhamis11** [comment]
#dmcdindia1

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22640-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22640-2-3-develop.instances.magento-community.engineering/admin](https://i-22640-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22640-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22640-2-2-develop.instances.magento-community.engineering/admin](https://i-22640-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99550`, `MAGETWO-99551` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance #dmcdindia1

**Comment by magento-engcom-team** [comment]
@ManishGangola-Webkul thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @ManishGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ManishGangola-Webkul, here is your [Magento instance](https://i-22640-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22640-2-3-develop.instances.magento-community.engineering/admin](https://i-22640-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by surabhisrivastava09** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#22908 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [e5b5bc10ba53634a7b5de257ed10e3fa3d472023](https://github.com/magento/magento2/commit/e5b5bc10ba53634a7b5de257ed10e3fa3d472023)
 - [ae9fa7981ef8925baf8ed8f0914440d700cf70aa](https://github.com/magento/magento2/commit/ae9fa7981ef8925baf8ed8f0914440d700cf70aa)
 - [a2fc106bf4808cdccf179e288f71ba36ed1e1958](https://github.com/magento/magento2/commit/a2fc106bf4808cdccf179e288f71ba36ed1e1958)
 - [6fc7d7a27a251a19da1afd0afa230bbc6fb8b96d](https://github.com/magento/magento2/commit/6fc7d7a27a251a19da1afd0afa230bbc6fb8b96d)

The fix will be available with the upcoming 2.2.10 release.
