### ISSUE TITLE
Unable to plug in to the public static method but there is no such limitation in the documentation. 

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2265]
http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html#plugin-limit

**Comment by davidalger** [comment]
@dfediuk Are you suggesting the docs be updated or that this limitation is bogus and Magento 2 should support plugins on static methods? :)

**Comment by alankent** [comment]
Since plugins work behind the scenes by creating a descendant class, I would like to see *that* ported to static methods!!

**Comment by dfediuk** [comment]
I have already developed 6 extensions for Magento 2.
First 5 of them was quite simple, but 6th is complex ([Markdown Editor](https://mage2.pro/t/topic/160)) and while developing it I have reached the current plugin system limitations twice.

1)
In the first case I needed an ability to show my custom control (Markdown Editor) on the backend category pages:
![magento2-markdown-editor-extension-05](https://cloud.githubusercontent.com/assets/83204/10993214/15f63cf0-847e-11e5-80f8-0aa83f2607aa.png)

I was unable to change the behaviour of `\Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes::_getAdditionalElementTypes()` method because it is protected:
https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Catalog/Block/Adminhtml/Category/Tab/Attributes.php#L124-L130  
In contrast to the similar method for products [`\Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Attributes::_getAdditionalElementTypes()`](https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Catalog/Block/Adminhtml/Product/Edit/Tab/Attributes.php#L151) the method `\Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes::_getAdditionalElementTypes()` does not generare any event and I was unable to plug in to it because it is protected.
So I was forced to override all the class with a `preference`.

The case is described here: https://github.com/magento/magento2/issues/2165

2)
In the second case I worked on the "Preview Mode" of my Markdown Editor.
![magento2-markdown-editor-extension-04](https://cloud.githubusercontent.com/assets/83204/10993248/6550e07a-847e-11e5-934d-9b6d8caad26f.png)

I tried to do the preview appearance as close as I can to the frontend appearance  so I planned to import the standard Magento Less files for typography but was unable to do so because of the reverse path limitation: https://github.com/magento/magento2/issues/2264
So I tried to disable the limitation for my particular extension but was unable to plug in to the `\Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple::assertFilePathFormat()` method because it is static.

So, in my experience, it would be great to plug in to the static and protected method if it is possible and if it will not hurt Magento 2 performance.

**Comment by antonkril** [comment]
It's not possible to intercept static calls because static call reference specific class name. Static calls hard-code class name and are not replaceable without hacking autoloading. So they should be avoided. In magento 2 you will see significantly less static calls, but they are still there, and will be gradually removed. 

As for protected methods, limitation is there to avoid situations when third-party extensions depend on protected interfaces of objects.

**Comment by dfediuk** [comment]
OK, then the documentation need to be updated and I need another way to overcome the problems https://github.com/magento/magento2/issues/2165 and https://github.com/magento/magento2/issues/2264

**Comment by davidalger** [comment]
@dfediuk Have you considered submitting a PR which refactors these methods you need to plugin to from protected methods to public? There are many protected methods in the system simply because of legacy code, and there is a good chance making some of these public via a PR would be accepted.

**Comment by nevvermind** [comment]
@davidalger - yes, he has considered it: https://github.com/magento/magento2/issues/2062#issuecomment-147273258
You can remove the `needs update` tag now.

**Comment by davidalger** [comment]
The documentation page has been updated for accuracy of current functionality. Closing.
