### ISSUE TITLE
Inconsistent Behaviour in Catalog Product: Set Product as New From To date

### ISSUE THREAD

**Issue by Eayshwary** [magento/magento2#22665]
### Preconditions (*)
Magento 2.3.1

### Steps to reproduce (*)
Add Product Or edit product page and set just 7 in To date under Set Product as New From

### Expected result (*)
It should display a message that enter full date (day and year is missing) or a valid date so that day and month can also be chosen instead of just applying 1st day of the current year with the entered month

### Actual result (*)
It saves product with 07.01.2019 as To date
taking 1st day and current year for 07th Month.
![incon1](https://user-images.githubusercontent.com/31269039/57175889-dd505c80-6e6e-11e9-892c-2a9acf85e450.png)
![incon2](https://user-images.githubusercontent.com/31269039/57175892-e2ada700-6e6e-11e9-8505-34bb37ee1189.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by pushpagupta-magento** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pushpagupta-magento. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22665-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22665-2-2-develop.instances.magento-community.engineering/admin](https://i-22665-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99553`, `MAGETWO-99554` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Eayshwary** [comment]
@orlangur please state as this is a feature of datepicker in magento or we need to restrict the users entering only single digit in set product as new TO DATE and saving the product, Thanks.

**Comment by saark-akash** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
@akashwebkul thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
