### ISSUE TITLE
Action column menu does not stay over the action column

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#2266]
I've added my own column in the `CMS Page` admin grid, and because the grid state is kept in the database, and I have previously visited the cms page grid, my column is added last.  
This is just part of a problem. I can do with that, but now the actions dropdown appear over my column instead of the actions column itself.  
See screenshot for more details

![Imgur](http://i.imgur.com/DRNaxLw.png)

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by tzyganu** [comment]
@vzabaznov The problem stil exists in the develop branch.  
Here is a screenshot that includes the version number:  
![image](https://cloud.githubusercontent.com/assets/2447784/16612611/78b0fe6e-4370-11e6-922b-e72c7edc231b.png)

**Steps to reproduce:**  
- Open the admin panel.  
- Go to the cms pages list:  Content->Pages (from the main menu)
- After the grid is rendered add this code in the file `app/code/Magento/Cms/view/adminhtml/ui_component/cms_page_listing.xml` (I edited that file to make it easier to explain. It also happens if I add a new column using the file `cms_page_listing.xml` from my module also)

```
      <column name="dummy1">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="filter" xsi:type="string">text</item>
                    <item name="label" xsi:type="string" translate="true">Dummy 1</item>
                </item>
            </argument>
        </column>
        <column name="dummy2">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="filter" xsi:type="string">text</item>
                    <item name="label" xsi:type="string" translate="true">Dummy 2</item>
                </item>
            </argument>
        </column>
```
- Refresh the pages list.  
- click on the actions link for the first item in the grid.

**Expected Result:**  
- My 2 columns should appear last in the grid.  
- The available actions should appear over the actions column

**Actual Result:**
- My 2 columns appear last in the grid
- The available actions appear over my last added column (as shown in the screenshot above).

**Comment by xmav** [comment]
Hi @tzyganu, thanks for reporting this issue. Internal ticket MAGETWO-58235 was created.

Thanks,
Maksym

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70310

**Comment by qsolutions-pl** [comment]
Issues still active in 2021 :D
