### ISSUE TITLE
Wrong currency symbol in creditmemo_grid & sales_order_view > creditmemo grid  for subtotal & Shipping and Handling fee

### ISSUE THREAD

**Issue by anujwebkul** [magento/magento2#22662]
**Preconditions (*)**
0. Magento CE 2.2.8

1.Magento 2.4-develop
2.Create second website with store and store view
3.Set another currency for second website(in my case its Ukrainian Hryvnia)
![image](https://user-images.githubusercontent.com/51681379/98379339-dac85780-204f-11eb-84b8-e03c897b88ec.png)
4.Go the Stores-->Currency Rates and set value for UAH = 2 
![image](https://user-images.githubusercontent.com/51681379/98377190-2a595400-204d-11eb-96a3-beeb295f43ff.png)

**Steps to reproduce (*)**
1. Create order in a store view with different currency as configured on default store view
2. Go to Backend --> Sales--->Orders and make an invoice and credit memo 
3. Check Subtotal and Shipping and Handling columns on Order page grid and Credit Memos pages grid.

 **Expected result (*)**
1. Display the Subtotal, Shipping & Handling with correct currency sign.

**Actual result (*)**

Wrong currency sign for Subtotal, Shipping & Handling Fee on Order and Credit memos pages grid(correct currency only for Grand Total(Purchased)):

- Order Grid
![image](https://user-images.githubusercontent.com/51681379/98377944-12ce9b00-204e-11eb-86b1-e52d24e9b673.png)

- CreditMemo Grid
![image](https://user-images.githubusercontent.com/51681379/98378073-3abdfe80-204e-11eb-8fb7-66de45f41f93.png)

**Comment by anujwebkul** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul, here is your [Magento instance](https://i-22662-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22662-2-2-develop.instances.magento-community.engineering/admin](https://i-22662-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by anujwebkul** [comment]
I am working on this.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @anujwebkul
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22662-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22662-2-3-develop.instances.magento-community.engineering/admin](https://i-22662-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
@anujwebkul @shikhamis11 what about 2.3 here?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18855` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by anujwebkul** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul, here is your [Magento instance](https://i-22662-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22662-2-3-develop.instances.magento-community.engineering/admin](https://i-22662-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by zakdma** [comment]
Need to reimplement
