### ISSUE TITLE
adminhtml grid based on ui_component does not show columns for me 

### ISSUE THREAD

**Issue by 0m3r** [magento/magento2#2267]
customer, content pages,  content blocks grids don't show columns

After 
* git pull 
* composer update 

![whereis_columns](https://cloud.githubusercontent.com/assets/412612/10971696/324de39e-83de-11e5-846d-01735741455e.png)
Now I stay on  2fc983463ca5ae4a78159674f65e3c7ad4a9beaf

**Comment by daim2k5** [comment]
Please delete also the var/* content
and make a
1. `bin/magento setup:upgrade`
2. `bin/magento setup:static-content:deploy`

If you have still the issue please open the dev console maybe you face the same problem as #2268

**Comment by 0m3r** [comment]
It still fails.
~~~js
ReferenceError: getVisible is not defined
http://local.magentocommerce2.com/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js line 2624 > Function
Line 1
~~~

~~~js
ReferenceError: viewsArray is not defined
http://local.magentocommerce2.com/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js line 2624 > Function
Line 2
~~~
~~~js
ReferenceError: getRanges is not defined
http://local.magentocommerce2.com/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js line 2624 > Function
Line 1
~~~
~~~js
ReferenceError: hasPreviews is not defined
http://local.magentocommerce2.com/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js line 2624 > Function
Line 2
~~~

**Comment by guz-anton** [comment]
I can suggest also:
3. Clean `pub/static` directory
4. Clean browser cache

Looks like .js files on the page are outdated.

**Comment by 0m3r** [comment]
Do you mean rm -rf pub/static ?
