### ISSUE TITLE
ko.getObservable is not a function in admin section

### ISSUE THREAD

**Issue by gigadesign1** [magento/magento2#2268]
I have the same issue as #2158 
The solution provided in that issue (remove static folder and run deploy again) did not work for me.

I am on develop branch commit 2fc9834
OS: Mac OSX 10.11.1
Browser: Firefox 41.0.2

The error is thrown on all pages in the admin, preventing me from adding poducts.

**Comment by daim2k5** [comment]
I can confirm this issue.

**Comment by SLv99** [comment]
I also have this error, removing static folder did not work.

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.
