### ISSUE TITLE
\Magento\Shipping\Model\Config class is missing constants for street lines 1/2

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#2269]
In Magento 2, "Street Address" and "Street Address 2" have been added to the "Shipping Settings" section of the configuration:

![configuration___settings___stores___magento_admin](https://cloud.githubusercontent.com/assets/129031/10977431/a1994086-83b6-11e5-8a7b-d7ccc461e7f2.png)

However the corresponding config class (`\Magento\Shipping\Model\Config`) does not contain XML_PATH constants for the address lines:

```
namespace Magento\Shipping\Model;

class Config extends \Magento\Framework\DataObject
{
    /**
     * Shipping origin settings
     */
    const XML_PATH_ORIGIN_COUNTRY_ID = 'shipping/origin/country_id';

    const XML_PATH_ORIGIN_REGION_ID = 'shipping/origin/region_id';

    const XML_PATH_ORIGIN_CITY = 'shipping/origin/city';

    const XML_PATH_ORIGIN_POSTCODE = 'shipping/origin/postcode';

```

While Magento 2 doesn't appear to use those two address lines anywhere, it would be useful if these two new constants could be added in order to allow third-party extensions to use core constants to refer to the system config values.

If you would like me to submit a PR for this, please let me know.

**Comment by davidalger** [comment]
@erikhansen There are constants for these present in `Magento\Sales\Model\Order\Shipment` along with duplicates for the others. If you would like to submit a PR introducing these and cleaning up the others in the shipment model, that would be awesome.

**Comment by erikhansen** [comment]
@davidalger Can you confirm that you are suggesting that the following be done:

* the XML_PATH_STORE_* constants in `\Magento\Sales\Model\Order\Shipment` should be removed
* street_line1/street_line2 constants should be added to the `\Magento\Shipping\Model\Config` class
* any usages of the \Magento\Sales\Model\Order\Shipment constants should be refactored to the \Magento\Shipping\Model\Config constants

**Comment by erikhansen** [comment]
@davidalger Ping.

**Comment by davidalger** [comment]
@erikhansen You are welcome to submit a PR. :) They are not merged by community moderators, as the core team takes care of that once it passes their review. So I can't confirm that one way or another will be accepted, but if you have ideas, submitting a PR is going to be the best way to get that in and reviewed by the team which processes these.

**Comment by NadiyaS** [comment]
Hi @erikhansen,

thanks for reporting this. Internal issue MAGETWO-50521 was created.

**Comment by orlangur** [comment]
`\Magento\Sales\Model\Order\Shipment` already contains constants for all six fields which are widely used in core.

They cannot be removed by BC policy but can be deprecated. However as constants from `\Magento\Shipping\Model\Config` have only 0-1 usages it does not make a lot of sense.
