### ISSUE TITLE
«TypeError: this.trigger is not a function» in lib/web/mage/backend/validation.js on line 205 (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2270]
https://mage2.pro/t/164

**Comment by daim2k5** [comment]
Created PR.

**Comment by valibus** [comment]
Same error on magento 2.0.7 when trying to save too many value for the same list box attribute
![image](https://cloud.githubusercontent.com/assets/6961470/16306074/c4b7fc72-395c-11e6-9be3-536051968106.png)

**Comment by zzvara** [comment]
Same error. Can not modify my attributes. Stuck. Latest Magento CE.
