### ISSUE TITLE
Magento 2 with CentOS 7 VMware / Virtualbox filesystem permissions fatal error

### ISSUE THREAD

**Issue by ljrweb** [magento/magento2#2271]
I've tried installing Magento 2 on VMware and Virtualbox running Centos 7 with the same steps I use in test boxes at AWS and Rackspace. CentOS 6.x seems to work fine. I have triple checked all permissions, but still get this exception. Has anyone had similar issue?

```
PHP Fatal error:  Uncaught exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory /usr/share/nginx/html/var/generation/Magento/Framework/App/ResourceConnection/.' in /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Generator.php:103
Stack trace:
#0 /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...')
#2 [internal function]: spl_autoload_call('Magento\\Framewo...')
#3 /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...')
#4 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...')
#5 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71 in /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Generator.php on line 103
[05-Nov-2015 23:33:31 UTC] PHP Fatal error:  Uncaught exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory /usr/share/nginx/html/var/generation/Magento/Framework/App/ResourceConnection/.' in /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Generator.php:103
Stack trace:
#0 /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...')
#2 [internal function]: spl_autoload_call('Magento\\Framewo...')
#3 /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...')
#4 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...')
#5 /usr/share/nginx/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71 in /usr/share/nginx/html/lib/internal/Magento/Framework/Code/Generator.php on line 103
```

**Comment by mazhalai** [comment]
Can you please check if SELINUX is enabled?  Permission settings will be more restrictive

**Comment by ljrweb** [comment]
@mazhalai @davidalger SELINUX was the issue. I disabled it in my dev environment, hopefully we can provide the correct setting in the install guide as a note. I can work with my team here at Rackspace, and suggest something if you'd like.

Thanks for the help!

**Comment by mazhalai** [comment]
@ljrweb Yes! that would be awesome! Please feel free to create a PR for the docs [here](https://github.com/magento/devdocs)  or suggest updates on this page [devdocs.magento.com](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html) and click on "Edit this page on GitHub"

cc: @xcomSteveJohnson

**Comment by davidalger** [comment]
@ljrweb Haven't done it personally, but what you'll need to do if you wish to secure the box with SELinux is switch it to permissive mode so you can run the site while logging all access attempts, and then use that information to create the appropriate policies before switching back to enforcing mode. You can read a bit on this here: https://wiki.gentoo.org/wiki/SELinux/Tutorials/Permissive_versus_enforcing

Re documentation, probably just a simple note on http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html about needing to properly configure SELinux if used on the box would be sufficient IMO. I'm thinking under Step 1.

**Comment by xcomSteveJohnson** [comment]
SELinux is optional. Magento doesn't recommend using it or not using it. It's discussed here: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/security.html and in some troubleshooting sections.

I do not think adding it to the page you suggest is a good idea because we want to keep that particular page as short as possible. We assume that if you enable SELinux, you know what you're doing. We can't anticipate every possible permutation that you might try to do.

**Comment by ljrweb** [comment]
@davidalger  @xcomSteveJohnson understood. If you're using SELinux the commands would be as follows:

chcon -R --type httpd_sys_rw_content_t {magento root dir}/app/etc
chcon -R --type httpd_sys_rw_content_t {magento root dir}/var
chcon -R --type httpd_sys_rw_content_t {magento root dir}/pub/media
chcon -R --type httpd_sys_rw_content_t {magento root dir}/pub/static

This will change these directories / files to the web server context and permit the web server to write to them.

**Comment by davidalger** [comment]
@ljrweb Great to know! I updated the title here so if anyone searches for SELinux they'll find this issue page.

**Comment by xcomSteveJohnson** [comment]
@ljrweb OK, thanks. Expect an update soon.

**Comment by ghost** [comment]
Selinux disabled your asking to get hacked that simple
