### ISSUE TITLE
"/rest/V1/products?searchCriteria" API endpoint" does not return information about stock in the "extension_attributes" section

### ISSUE THREAD

**Issue by growsera** [magento/magento2#22737]
**Preconditions**

1. Magento 2.2.7 community Edition.
2. REST API filtering products using rest/V1/products?searchCriteria

**Steps to reproduce**
1. we have disable showing out of stock products from Magento Dashboard (Stores > Configuration > Catalog > Inventory > Display Out of stock products **No**)
2. we using this api to filtering product 
`/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][value]=35&searchCriteria[current_page]=1&searchCriteria[page_size]=40`

**Expected result**
1. The response contains infromation about stock per each product in the "extension_attributes" section

**Actual result**
1. There is no information about stock status per product in "extension_attributes" and no possibility to understand is it available on Storefront

**Comment by growsera** [comment]
Hi @AlexWorking 
thank you very much for working on this issue.
i'll waiting your updates.

**Comment by growsera** [comment]
@AlexWorking  @vteofilo

any help in this issue would be great..
it's urgent problem in our store .

Thanks & Regards

**Comment by vteofilo** [comment]
@MagentoAr , please look at my solution:

https://github.com/magento/magento2/issues/15201#issuecomment-417867348

Hope this helps!

**Comment by MagentoAr** [comment]
@vteofilo 
thank you but i really don't know where to put your code.

**Comment by vteofilo** [comment]
> @vteofilo
> thank you but i really don't know where to put your code.

Can you find the StockRegistry.php class?

**Comment by MagentoAr** [comment]
> > @vteofilo
> > thank you but i really don't know where to put your code.
> 
> Can you find the StockRegistry.php class?

yes i found it on this path
/vendor/magento/module-catalog-inventory/Model/StockRegistry.php

but i don't know wheres to put the code

**Comment by vteofilo** [comment]
> > > @vteofilo
> > > thank you but i really don't know where to put your code.
> > 
> > 
> > Can you find the StockRegistry.php class?
> 
> yes i found it on this path
> /vendor/magento/module-catalog-inventory/Model/StockRegistry.php
> 
> but i don't know wheres to put the code

You must override the syncProductStock method.

**Comment by growsera** [comment]
> > > > @vteofilo
> > > > thank you but i really don't know where to put your code.
> > > 
> > > 
> > > Can you find the StockRegistry.php class?
> > 
> > 
> > yes i found it on this path
> > /vendor/magento/module-catalog-inventory/Model/StockRegistry.php
> > but i don't know wheres to put the code
> 
> You must override the syncProductStock method.

i couldn't find any method called syncProductStock in this file
/vendor/magento/module-catalog-inventory/Model/StockRegistry.php

**Comment by growsera** [comment]
@vteofilo 
any help would be great

**Comment by sdzhepa** [comment]
Hello @MagentoAr 

Thank you for the report!

We investigated this issue and  as results:

1. Initially "/rest/V1/products?searchCriteria" API endpoint was developed for wider use and it should not returns only In Stock products by design.
Even if you set "Stores > Configuration > Catalog > Inventory > Display Out of stock products No" the product will be available by direct URL on Storefront. 
I suppose it needs for SEO purposes and indexation by other systems.
And because of that _issue cannot be confirmed and proved for fix with described use case_

2. But the real bug is **"/rest/V1/products?searchCriteria" API endpoint" does not return information about stock in the "extension_attributes" section.**

so, I updated Issue title and description with this information
Are you ok with this?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99618`, `MAGETWO-99619` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MagentoAr** [comment]
> Hello @MagentoAr
> 
> Thank you for the report!
> 
> We investigated this issue and as results:
> 
> 1. Initially "/rest/V1/products?searchCriteria" API endpoint was developed for wider use and it should not returns only In Stock products by design.
>    Even if you set "Stores > Configuration > Catalog > Inventory > Display Out of stock products No" the product will be available by direct URL on Storefront.
>    I suppose it needs for SEO purposes and indexation by other systems.
>    And because of that _issue cannot be confirmed and proved for fix with described use case_
> 2. But the real bug is **"/rest/V1/products?searchCriteria" API endpoint" does not return information about stock in the "extension_attributes" section.**
> 
> so, I updated Issue title and description with this information
> Are you ok with this?

okay great..
could you please tell me if there is any quick solution?
i'm too late to finish this task for my client.

**Comment by dwang12** [comment]
Hi Guys,

We're also experiencing this in a production setting. Any updates would be greatly appreciated.

Thanks!

**Comment by farhansaid127** [comment]
> ✅ Confirmed by @sdzhepa
> Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99618`, `MAGETWO-99619` were created
> 
> **Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

But we are still not able to find if product available in stock or not, there is no parameter in search result that shows whether the product available in stock or out of stock

**Comment by farhansaid127** [comment]
> Hello @MagentoAr
> 
> Thank you for the report!
> 
> We investigated this issue and as results:
> 
> 1. Initially "/rest/V1/products?searchCriteria" API endpoint was developed for wider use and it should not returns only In Stock products by design.
>    Even if you set "Stores > Configuration > Catalog > Inventory > Display Out of stock products No" the product will be available by direct URL on Storefront.
>    I suppose it needs for SEO purposes and indexation by other systems.
>    And because of that _issue cannot be confirmed and proved for fix with described use case_
> 2. But the real bug is **"/rest/V1/products?searchCriteria" API endpoint" does not return information about stock in the "extension_attributes" section.**
> 
> so, I updated Issue title and description with this information
> Are you ok with this?

But we are still not able to find if product available in stock or not, there is no parameter in search result that shows whether the product available in stock or out of stock.

**Comment by scne** [comment]
any news about this issue?

**Comment by menacoders** [comment]
> any news about this issue?

it's still not fixed in any version
i have built a module to solve this issue, i'll share it with you these days.

**Comment by menacoders** [comment]
Hi @scne 
i have uploaded the module, get it from here
https://github.com/menacoders/stock-API/

and let me know if you need anything else 👍

**Comment by scne** [comment]
Hi @menacoders thank you so much for your help! I'm using Magento 2.3.2, is your code compliant?

**Comment by menacoders** [comment]
> Hi @menacoders thank you so much for your help! I'm using Magento 2.3.2, is your code compliant?

yes, i have build it for m2.3.x

**Comment by titechnologies** [comment]
> Hi @scne
> i have uploaded the module, get it from here
> https://github.com/menacoders/Stock-Info-API-searchCriteria
> 
> and let me know if you need anything else

Thank you.
One question, how can we filter out these out-of-stock products from the API result?

**Comment by menacoders** [comment]
> > Hi @scne
> > i have uploaded the module, get it from here
> > https://github.com/menacoders/Stock-Info-API-searchCriteria
> > and let me know if you need anything else
> 
> Thank you.
> One question, how can we filter out these out-of-stock products from the API result?

you mean, you only want to return the in_stock products ?
if that what you want.. you could use this api

`rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=quantity_and_stock_status&searchCriteria[filter_groups][0][filters][0][value]=2`

just add the quantity_and_stock_status filter so it's will return the in_stock products 
instock value = 2
outofstock value = 1
