### ISSUE TITLE
Language switcher redirects to home page a new created page in Magento 2.3.1

### ISSUE THREAD

**Issue by doeri** [magento/magento2#22732]
Hello everybody!

I am encountering an issue in Magento 2.3.1
I have created two pages with the same url and assigned different stores for each page, however it still redirects to home.
The issue happens only with a new created pages.
The Home page and the Contact page as the Category pages work fine.

I have Magento 2,3,1 installed and php 7.2 version

I also see that it create a different page ids for each of the two pages, however the category multilingual pages have the same page id.

Could I have your assistance here please?

@magento-engcom-team give me 2.3.1-develop instance

**Comment by doeri** [comment]
I do not know why this happens with the cms pages.
I found the solution creating the category pages for the 'about us' page.
I do not thing that this is a correct way to create simple pages...

Any opinion here would be appreciated.

**Comment by krishprakash** [comment]
Hi @doeri. Thank you for your report.
The issue is duplicate to #14674
