### ISSUE TITLE
Product doesn't appear on front end after enabling it when using Scheduled Indexing

### ISSUE THREAD

**Issue by nitishcs6** [magento/magento2#22749]
### Preconditions (*)

1. Magento Open Source/Commerce (2.3.1 or 2.3.1) with/without Sample Data.
2. Enabled Flat Tables (BO -> Stores -> Configuration -> Catalog -> Catalog -> Storefront -> Use Flat Catalog Product).
3. Indexer set to 'UPDATE BY SCHEDULE' mode (BO -> System -> Index Management).
4. Initial reindex was done and all indexes already created.

### Steps to reproduce (*)

1. Create a Simple Product with "Stock Status = In Stock" and "Inventory Qty = 1000" and "Product Status  = Disabled".
2. Then after few minute change "Product Status to Enabled". After enabling the product , it won't appear on front end.

### Expected result (*)

1.Product should appear on front end.

### Actual result (*)

Product doesn't appear on front end.

**Comment by nitishcs6** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @nitishcs6. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nitishcs6, here is your [Magento instance](https://i-22749-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22749-2-3-develop.instances.magento-community.engineering/admin](https://i-22749-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nitishcs6** [comment]
@magento-engcom-team 
can you confirm schedule indexing cron is enabled on given instance?

**Comment by nitishcs6** [comment]
@magento-engcom-team 
can you confirm schedule indexing cron is enabled on given instance?
