### ISSUE TITLE
"select all" in backend grid not working properly, only the visiable items are getting updated

### ISSUE THREAD

**Issue by David-Magebinary** [magento/magento2#22740]
### Preconditions (*)
Magento version: 2.3.1

### Steps to reproduce (*)
1. Go Customers > All Customers 
2. Select 'Select all' 
![image](https://user-images.githubusercontent.com/26532379/57204716-92208000-700d-11e9-9b19-f236080a31d4.png)
3. Select 'Delete' from the Actions dropdown
4.Shows 'A total of 20 record(s) were deleted.'
![image](https://user-images.githubusercontent.com/26532379/57204746-bf6d2e00-700d-11e9-8b9b-5d1c18ef47c1.png)

### Expected result (*)
Delete all customers (not only for deleting also not working for update attributes, so really bad user experience for the website administrators)

### Actual result (*)
1. [Shows 'A total of 20 record(s) were deleted.'
![image](https://user-images.githubusercontent.com/26532379/57204746-bf6d2e00-700d-11e9-8b9b-5d1c18ef47c1.png)
2. Only visible items getting deleted

**Comment by krishprakash** [comment]
Hi @David-Magebinary. Thank you for your report.
This issue is duplicate to #22004
