### ISSUE TITLE
Wrong discount amount calculating for cart price rules if cart rule set to fixed amount

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#22745]
### Steps to reproduce

1.  Create cart price rule with Fixed amount discount.
2. Add products to shopping cart.
3. Add discount coupon to cart, click on apply discount button and check for cart totals.

### Expected result

Mentioned Discount amount should apply to cart.

### Actual result

100% discount applying on subtotal.

**Comment by deepakk-webkul** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar, here is your [Magento instance](https://i-22745-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22745-2-3-develop.instances.magento-community.engineering/admin](https://i-22745-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@webkul-deepakkumar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @webkul-deepakkumar
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @webkul-deepakkumar
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by deepakk-webkul** [comment]
@magento-engcom-team why i am not able to add confirmed label on it

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @webkul-deepakkumar
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by AlexWorking** [comment]
Dear @maheshWebkul721. Please next time do not assign to Yourself issues for recheck if they have already been assigned to somebody else. Thank You for understanding.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99576`, `MAGETWO-99577` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
@AlexWorking , i did not assign it for rechecking issue, i assigned it for fix this issue.

**Comment by magento-engcom-team** [comment]
The Issue should be re-verified on the latest Magento code and re-Confirmed if its still actual

**Comment by engcom-Foxtrot** [comment]
Issue description and steps to reproduce are unobvious. Fixed amount discount works as described in https://docs.magento.com/user-guide/marketing/price-rules-cart-create.html. Please feel free to reopen issue if you have some clarifications.
