### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry multi-source inventory assignment.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#22741]
### Preconditions (*)

1.Magento 2.3.0 CE
2.

### Steps to reproduce (*)

1. create an item
2. setup multi-source inventory
3. use V1/inventory/source-items API to allocate inventory.
4. make multiple calls to allocate different source to a single SKU

### Expected result (*)

1. It should pass and give [] response every time.

### Actual result (*)

Request 1: {"sourceItems":[{"sku":"prices/a","source_code":"500081","quantity":"24","status":"1"}]}
Request 2: {"sourceItems":[{"sku":"prices/a","source_code":"500084","quantity":"20","status":"1"}]}
For request 1 getting response: []
For request 2 getting response: {"message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'prices/a' for key 'PRIMARY', query was: INSERT  INTO `inventory_stock_2` (`sku`,`quantity`,`is_salable`) VALUES (?, ?, ?)","code":1062}

Any idea why this is happening.

**Comment by ankursachdeva11** [comment]
@engcom-backlog-nazar any updates on this?

**Comment by ankursachdeva11** [comment]
Any updates @magento-engcom-team

**Comment by mallikaverma** [comment]
I am working on it..

**Comment by mallikaverma** [comment]
#imagine2019

**Comment by Nazar65** [comment]
Hi @ankursachdeva11 thank you for you report, please open issue here -> https://github.com/magento-engcom/msi
