### ISSUE TITLE
Using Customer Session Factory to avoid depersonalization

### ISSUE THREAD

**Issue by CompactCodeEU** [magento/magento2#22751]
I know this is more of a question but i do not seem to find any good documentation if this is expected behavior or not and what the consequences could be.

### Summary (*)
We have a plugin that adjusts the customer price on the front-end based on its customer ID. When you use the Customer Session class it is depersonalized for a very good reason. But when you use the factory of the same class suddenly you have all the customer data you need. My questions for using this method :

- Does this create multiple caching instances for the same page when FPC enabled
- Does this have certain security risks?
- When using this is there any chance of caching the customer data resulting in mixed results?

### Examples (*)
```
    /**
     * @param \Magento\Customer\Model\Session $customerSession
     */
    public function __construct(
        Magento\Customer\Model\Session $customerSession
    )
    {
        $this->customerSession = $customerSession;
    }

    public function afterGetPrice(\Magento\Catalog\Model\Product $subject, $result)
    {
        $customerId = null;
        $customerId = $this->customerSession->getCustomerId();
        //$customerId =  NULL
}
```

```
    /**
     * @param \Magento\Customer\Model\Session $customerSession
     */
    public function __construct(
       Magento\Customer\Model\SessionFactory $customerSession
    )
    {
        $this->customerSession = $customerSession;
    }

    public function afterGetPrice(\Magento\Catalog\Model\Product $subject, $result)
    {
        $customerId = null;
        $customerId = $this->customerSession->create()->getCustomerId();
        //$customerId =  the logged in customer ID
}
```

### Proposed solution

Provide more information on denationalization of CustomerData and what we should avoid.

**Comment by VasylShvorak** [comment]
Hi @CompactCodeEU . The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
