### ISSUE TITLE
There is no clear indication when "Use default value" is set for themes in Content -> Design -> Configuration

### ISSUE THREAD

**Issue by diamondavocado** [magento/magento2#22756]
### Preconditions (*)

1. Version 2.3.1

### Steps to reproduce (*)

1. Visit Admin panel -> Content -> Design -> Configuration
2. Try to identify which website/store/store view is set to "Use default value" for its theme

### Expected result (*)

1. It should be clear which website/store/store view has been set to "Use default value" and which one has been allocated a specific (non-default) theme
2. The entries under the "Theme name" column should state something like "[Uses default value]" where appropriate

### Actual result (*)

1. All entries under the "Theme name" column just display the name of the theme, even if that website/store/store view has not specifically been set to use that theme by the user
2. It is therefore not clear that those entries are actually "Using default value" or if they've manually been set by the user

**It needs to be clearer which entries** 
- have been set and
-  which are just inheriting the default theme from the hierarchy above. (see https://github.com/magento/magento2/issues/22756#issuecomment-489865091 for details)

![i22756](https://user-images.githubusercontent.com/3409584/58901782-75886e00-86c7-11e9-8c5a-4a290735c06e.jpg)

**Comment by diamondavocado** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @diamondavocado. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @diamondavocado, here is your [Magento instance](https://i-22756-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22756-2-3-develop.instances.magento-community.engineering/admin](https://i-22756-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by diamondavocado** [comment]
@m2-assistant Issue confirmed in 2.3-develop instance

I changed the 2nd row's theme to "Magento Luma" but did not touch the 3rd row's theme. The 3rd row therefore inherits the 2nd row's theme, but is still technically set to "Use default value". This is not clear. It looks like the 3rd row's theme has also been changed by me, but it has not:
https://i.imgur.com/UDKNmAv.png

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-22756-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22756-2-3-develop.instances.magento-community.engineering/admin](https://i-22756-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17219` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
