### ISSUE TITLE
Notice: getimagesize(): Read error! in app/code/Magento/Catalog/Model/Product/Image.php on line 949

### ISSUE THREAD

**Issue by gigadesign1** [magento/magento2#2276]
According to documentation, the etc/view.xml is optional when inheriting from a parent theme.
I am inhereting from Magento/blank, so I did not create this file. It gave me this error in developer mode, in default mode the products just won't be displayed.

When I copy and paste the etc/view.xml file from the parent theme, the error is gone and everything works as expected.

Like this issue #1647

**Comment by maghamed** [comment]
Thanks, for your feedback. Internal issue number for current bug - MAGETWO-45125

**Comment by maghamed** [comment]
Fix delivered to mainline

**Comment by Enelar** [comment]
@magento-team catched it on 1.13.0.2, on zero length file

**Comment by spyrule** [comment]
This problem persists in version 2.1.3

**Comment by versdivers** [comment]
Got this error in default mode while compiling catalog:images:resize on 2.2.0
