### ISSUE TITLE
Unable to install Magento 2 if a console command depends on ProductRepositoryInterface

### ISSUE THREAD

**Issue by marcusirgens** [magento/magento2#22777]
### Preconditions (*)

1. Have an env.php file
2. Magento 2.2.7, Magento 2.2.8, Magento 2.3.1 with any custom command that uses ProductRepositoryInterface
3. With the fixes from #21693 this does not occur on 2.3.1
4. This issue still occurs on 2.2.7 with fixes from #21719 applied

### Steps to reproduce (*)

1. Install a custom CLI command that injects `Magento\Catalog\Api\ProductRepositoryInterface` into its constructor
2. Set up an env file with your environment settings
3. Install Magento from CLI

### Expected result (*)

Magento will be installed

### Actual result (*)

Magento is not installed. At step 4, `Installing database schema`, the installer will fail with the exception:
```Base table or view not found: 1146 Table 'YOUR_DATABASE_NAME.store_website' doesn't exist```
The exception occurs because `Magento\Framework\Locale\Resolver` has logic in its constructor that ends up making a database query. The "creation stack" goes down through  `\Magento\Framework\Stdlib\DateTime\Timezone` -> `Magento\Framework\Stdlib\DateTime\Filter\Date` -> `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` -> `\Magento\Catalog\Model\ProductRepository`.

**Comment by marcusirgens** [comment]
More specifically, it seems to occur when the install/date key exists in the app/etc/env.php file

**Comment by FreekVandeursen** [comment]
Duplicate of https://github.com/magento/magento2/issues/16173 I think.

**Comment by soleksii** [comment]
Hi @marcusirgens, thank you for you report, i'm closing this as duplicate to this -> #16173
