### ISSUE TITLE
Update to widget options in not saved in Page Builder

### ISSUE THREAD

**Issue by dpolt-codifi** [magento/magento2#22776]
### Preconditions (*)

1. Magento Version: 2.3.1

### Steps to reproduce (*)

1. Create a new empty CMS page
2. Drag and drop Text element into Page Builder Content
3. Insert any widget that has options, for example, "Catalog Product Link"
4. Save the page
5. Double click on the widget to open it's configuration
6. Change any widget options and save the widget
7. Save the page

### Expected result (*)
1. Updated widget options values are saved

### Actual result (*)
1. Changes to the widget options are not saved

### Workaround
1. Create a new empty CMS page
2. Drag and drop Text element into Page Builder Content
3. Insert any widget that has options, for example, "Catalog Product Link"
4. Save the page
5. Double click on the widget to open it's configuration
6. Change any widget options and save the widget
7. Double click on the widget again
8. **Making no changes** either close the model, or save the widget, does not matter. Buy this time an Ajax request already happened which updated the editor content.
9. Save the page

### Reason
After widget options are updated and inserted back into the editor it does not trigger the change event in tinyMCE editor which means no changes happen in Page Builder data source model (Wysiwyg.onChangeContent does not get triggered in vendor/magento/module-page-builder/view/adminhtml/web/ts/js/wysiwyg/tinymce4.ts)

I was able to fix it with he following patch:
```
--- a/lib/web/mage/adminhtml/wysiwyg/widget.js
+++ b/lib/web/mage/adminhtml/wysiwyg/widget.js
@@ -468,6 +468,7 @@
                                 if (activeNode) {
                                     editor.selection.select(activeNode);
                                     editor.selection.setContent(transport.responseText);
+                                    editor.fire('Change');
                                 } else if (this.bMark) {
                                     wysiwyg.activeEditor().selection.moveToBookmark(this.bMark);
                                 }
```

Hope this helps.

**Comment by dpolt-codifi** [comment]
Yes, I was able to reproduce the issue on vanilla Magento instance.

**Comment by atishgoswami** [comment]
Hello @dpolt-codifi this seems to be page builder issue which seems to be associated with the enterprise release of magento.

This GitHub repository is only for issues related to the magento community.

You need to raise a ticket in Magento support using you merchant/partner portal.

**Comment by davemacaulay** [comment]
The issue has been moved into Page Builder repository: https://github.com/magento/magento2-page-builder-ee/issues/63
_Created internal issue: MC-15367_

**Comment by freeloop001** [comment]
@davemacaulay [magento/magento2-page-builder-ee#63](url) now is 404 not found , can you tell me how to fix this bug, like above patch? thank you.

**Comment by davemacaulay** [comment]
@freeloop001 Page Builder repositories are private, the issue is not yet fixed in core. You can simply apply the patch in the first post if you'd like to fix it or wait for a future release where we fix it.

**Comment by MrDevOpss** [comment]
is the issue fixed in core yet ? i still can see this problem when adding widget into page builder and save the page. Changes does not reflect and widget drag and drop is empty.
