### ISSUE TITLE
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data

### ISSUE THREAD

**Issue by akamenew** [magento/magento2#22773]
Following the instructions on https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html for upgrading Magento, I got this error when executing the command "php  bin/magento setup:upgrade"

### Preconditions (*)
1. Upgraded from 2.2.3 -> 2.3.1
2. PHP Version 7.2.16

### Steps to reproduce (*)
0. Starting with a 2.2.3 installation, in Magento root dir:
1. php bin/magento maintenance:enable
2. composer require magento/product-community-edition=2.3.1 --no-update
3. composer require --dev phpunit/phpunit:~6.2.0 friendsofphp/php-cs-fixer:~2.10.1 lusitanian/oauth:~0.8.10 pdepend/pdepend:2.5.2 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:3.2.2 --no-update
4. composer remove --dev sjparkinson/static-review fabpot/php-cs-fixer --no-update
5. Open composer.json and edit the "autoload": "psr-4" section to include "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/":

"autoload": {
    "psr-4": {
        "Magento\\Framework\\": "lib/internal/Magento/Framework/",
        "Magento\\Setup\\": "setup/src/Magento/Setup/",
        "Magento\\": "app/code/Magento/",
        "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
    },
    ...
}
6.  composer create-project --repository=https://repo.magento.com magento/project-community-edition=2.3.1 temp_dir --no-install
7. rm -rf update
8. mv temp_dir/update .
9. rm -rf temp_dir
10. composer update
11. bin/magento cache:clean
12. rm -rf var/cache/*
13. rm -rf var/page_cache/*
14. rm -rf generated/code/*
15. bin/magento setup:upgrade

### Expected result (*)
1. The command "bin/magento setup:upgrade" should finish without errors

### Actual result (*)
1. The command "bin/magento setup:upgrade" breaks with message:
`Type Error occurred when creating object: Magento\Framework\Communication\Config\Data`

In the system.log I see the whole message:
`[2019-05-07 13:47:47] main.CRITICAL: Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /var/www/vhosts/schuhjaeger.at/magento2_test/shop-v2/vendor/magento/framework/Reflection/TypeProcessor.php on line 535 [] []`

**This is the function from TypeProcess.php:**

`
/**
     * Get the parameter type
     *
     * @param ParameterReflection $param
     * @return string
     * @throws \LogicException
     */
    public function getParamType(ParameterReflection $param)
    {
        $type = $param->detectType();
        if ($type === 'null') {
            throw new \LogicException(sprintf(
                '@param annotation is incorrect for the parameter "%s" in the method "%s:%s".'
                . ' First declared type should not be null. E.g. string|null',
                $param->getName(),
                $param->getDeclaringClass()->getName(),
                $param->getDeclaringFunction()->name
            ));
        }
        if ($type === 'array') {
            // try to determine class, if it's array of objects
            $paramDocBlock = $this->getParamDocBlockTag($param);
            $paramTypes = $paramDocBlock->getTypes();
            $paramType = array_shift($paramTypes);

            $paramType = $this->resolveFullyQualifiedClassName($param->getDeclaringClass(), $paramType);

            return strpos($paramType, '[]') !== false ? $paramType : "{$paramType}[]";
        }
        return $this->resolveFullyQualifiedClassName($param->getDeclaringClass(), $type);
    }
`

According to the error message, the variable $type is null.

How can I solve this?

Thank you very much in advance!

**Comment by shikhamis11** [comment]
@akamenew Thank you for your report, I followed the same step and I am not able to reproduce the issue. Let me know If It requires any additional step too to reproduce the issue.

**Comment by akamenew** [comment]
@shikhamis11 Actually that were all the steps I went through to observe this behaviour. Do you have any idea on how to resolve this? I have tried different approaches (like cleaning cache, deleting stuff in generated and var folder) but nothing worked yet. Any help is highly appreciated.

**Comment by just-tom** [comment]
Im also having the same issue. Upgraded from 2.3.0 to 2.3.1, Error getting thrown after Module 'Magento_AMQP' in setup:upgrade. I am using AMQP in my build.
![Screenshot 2019-05-09 at 09 52 22](https://user-images.githubusercontent.com/12802934/57440598-368a0880-7240-11e9-8353-4feed81feba3.png)

**Comment by just-tom** [comment]
For some more information:
The error is occurring on trying to define the "type" for Magento\Framework\MessageQueue\Consumer::process docblock. In the screenshot you can see the Docblock for the method. It has a param.

![Screenshot 2019-05-09 at 10 13 25](https://user-images.githubusercontent.com/12802934/57443156-5ec83600-7245-11e9-8d76-f16f5cb6cc6f.png)

Problem is the Zend\Code\Reflection\ParameterReflection::detectType method is returning null. This is because the DocBlock params aren't being picked up on line 107, but as you can see in the screenshot the param type is available on the Interface. In the screenshot below you can see there are no tags.

![Screenshot 2019-05-09 at 10 36 11](https://user-images.githubusercontent.com/12802934/57443646-718f3a80-7246-11e9-90e1-88aabc987b3a.png)

**Comment by Fadjolo** [comment]
I also got his error but only with payment module,


I have a payment module for Magento for one Croatian online payment provider, i tried it to install on Magento 2.3.1 and everything is fine but when i want to go on Checkout it says https://www.example.com/rest/default/V1/guest-carts/auIzs7o1NSN0KyEoq6jHv5MJkbcnUbC7/estimate-shipping-methods - Failed to load resource: the server responded with a status of 500 () and i have no shipping methods?

Module 'Magento_Amqp':
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data

debug.log

[2019-06-06 11:57:30] main.CRITICAL: Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /home/nulledzo/capriolo.hr/vendor/magento/framework/Reflection/TypeProcessor.php on line 535 [] [] [2019-06-06 11:57:30] main.ERROR: Type Error occurred when creating object: Magento\Framework\Communication\Config\Data [] []

system.log

[2019-06-06 11:57:30] main.CRITICAL: Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /home/nulledzo/capriolo.hr/vendor/magento/framework/Reflection/TypeProcessor.php on line 535 [] [] [2019-06-06 11:57:30] main.ERROR: Type Error occurred when creating object: Magento\Framework\Communication\Config\Data [] []


Report:

{"0":"Type Error occurred when creating object: Magento\Framework\Communication\Config\Data","1":"#1 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#2 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:160]\n#3 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246]\n#4 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]\n#5 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]\n#6 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#7 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:160]\n#8 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246]\n#9 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]\n#10 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]\n#11 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#12 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:160]\n#13 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246]\n#14 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]\n#15 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]\n#16 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#17 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:160]\n#18 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246]\n#19 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]\n#20 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]\n#21 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#22 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:160]\n#23 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246]\n#24 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]\n#25 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]\n#26 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#27 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:196]\n#28 Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:172]\n#29 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246]\n#30 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]\n#31 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]\n#32 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#33 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:160]\n#34 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:246]\n#35 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]\n#36 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]\n#37 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]\n#38 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/App/Http.php:135]\n#39 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]\n#40 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]\n#41 Magento\Framework\App\Bootstrap->run() called at [index.php:39]\n</pre>","url":"/rest/default/V1/guest-carts/auIzs7o1NSN0KyEoq6jHv5MJkbcnUbC7/estimate-shipping-methods","script_name":"/index.php"}

`
`
Any Help???

**Comment by vjcspy** [comment]
For anyone want to fix this issue. 
The root cause is magento read the configurations files of queue and it try to resolve the parameter in consumer handler method. 
- How to fix?
 add PHPDOC block for all consumer class in your custom module.
- How to find all consumer class?
 you can set break point debugger in this file or just wrap this method in try/catch block and print the class you need to fix.
![image](https://user-images.githubusercontent.com/11264727/59499966-b308aa80-8ec2-11e9-86be-3c5a1200e2fe.png)

**Comment by tushar2197** [comment]
@akamenew @just-tom just-tom
change function
Path: Magento\Framework\Reflection\TypeProcessor

 public function getParamType(ParameterReflection $param)
    {
        $type = $param->detectType();
        if ($type === 'null') {
            throw new \LogicException(sprintf(
                '@param annotation is incorrect for the parameter "%s" in the method "%s:%s".'
                . ' First declared type should not be null. E.g. string|null',
                $param->getName(),
                $param->getDeclaringClass()->getName(),
                $param->getDeclaringFunction()->name
            ));
        }
        if ($type === 'array') {
            // try to determine class, if it's array of objects
            $paramDocBlock = $this->getParamDocBlockTag($param);
            $paramTypes = $paramDocBlock->getTypes();
            $paramType = array_shift($paramTypes);

            $paramType = $this->resolveFullyQualifiedClassName($param->getDeclaringClass(), $paramType);

            return strpos($paramType, '[]') !== false ? $paramType : "{$paramType}[]";
        }

        return $type;
    }

**Comment by LakshmanKatragadda** [comment]
> Im also having the same issue. Upgraded from 2.3.0 to 2.3.1, Error getting thrown after Module 'Magento_AMQP' in setup:upgrade. I am using AMQP in my build.
> ![Screenshot 2019-05-09 at 09 52 22](https://user-images.githubusercontent.com/12802934/57440598-368a0880-7240-11e9-8353-4feed81feba3.png)

What is solution for this ..? i am slo got same issue and why ?

**Comment by purna12** [comment]
Im also having the same issue. My application with 2.3.4-p2 version Error getting thrown after Module 'Magento_AMQP' in setup:upgrade.
![Screenshot from 2021-01-28 13-11-14](https://user-images.githubusercontent.com/2920246/106106503-a3a7a500-616b-11eb-864d-3a69ff9c4051.png)

I havent modified any code, which was working fine.
What is solution for this ..? i am slo got same issue and why ?

**Comment by alek-s-andr** [comment]
After updating the **Magento** to version **2.4.4** we have the same error on running **bin/magento setup:upgrade**.

![2022-04-20-12-51-18](https://user-images.githubusercontent.com/34573954/164152885-c6d22acc-7fb9-44b1-8d93-18a2f0b64e2c.png)

**Comment by YouCanDoIt12** [comment]
After upgrading to Magento 2.4.4 I am also getting the same error

**Comment by archerv-windcave** [comment]
Same issue when installing Magento 2.4.4. Please advice as to how to fix the issue.
![mage244_upgrade_error](https://user-images.githubusercontent.com/84824317/165195938-7d393a8e-9fc7-49d0-8248-3cd259ed5bd8.png)

**Comment by rawsj24** [comment]
I had a similar issue after upgrading to 2.4.4, I just checked that it causing because by a third-party module.

file : vendor\magento\framework\Reflection\TypeProcessor.php

Add this line of code before line 550, and check which class is causing the issue:
if($type==null || empty($type)){
            echo "<pre>";
            print_r($type);
            echo "<pre>";
            print_r($param->getDeclaringClass());
            echo "<br>";
            exit;    
}

after upgrading my module to latest version issue solved.

**Comment by zeeshan2523806** [comment]
@rawsj24 thank you for your recommendation.

**Comment by abcpremium** [comment]
Can someone please tell me what is wrong with my consumer class here? It throws exactly the exception mentioned here in this issue. I try to get it work for 2 days now... I don't understand what's wrong... 

```
<?php

namespace TimoG\OrderTransfer\Model\Queue;

use Exception;
use Psr\Log\LoggerInterface;
use Magento\Framework\Serialize\Serializer\Json;
use Magento\Sales\Model\Order;
use Magento\Sales\Model\OrderRepository;

class Consumer
{

    private LoggerInterface $_logger;
    private Json $_json;
    private OrderRepository $_orderRepository;


    public function __construct(
        LoggerInterface $logger,
        Json $json,
        OrderRepository $orderRepository
    )
    {
        $this->_orderRepository = $orderRepository;
        $this->_json = $json;
        $this->_logger = $logger;
    }


    public function process($request)
    {
        try {
            $data = $this->_json->unserialize($request);
            $orderState = Order::STATE_PROCESSING;
            $order = $this->_orderRepository->get($data['order_id']);
            $order->setState($orderState)->setStatus($orderState);
            $this->_orderRepository->save($order);
        } catch (Exception $exc) {
            $this->_logger->critical($exc->getMessage());
        }
    }
}

```

**Comment by snez** [comment]
I got this error on 2.4.4 after creating a custom webapi.xml route. I forgot to declare the method param types in the docblock, which produced this non-intuitive error.

**Comment by pmonosolo** [comment]
> I had a similar issue after upgrading to 2.4.4, I just checked that it causing because by a third-party module.
> 
> file : vendor\magento\framework\Reflection\TypeProcessor.php
> 
> Add this line of code before line 550, and check which class is causing the issue:
> 
> ```
> if($type==null || empty($type)){
>             print_r($type);
>             echo "<pre>";
>             print_r($param->getDeclaringClass());
>             echo "<br>";
>             exit;    
> }
> ```
> 
> after upgrading my module to latest version issue solved.

Thanks! If anybody else needs a better hint after that, I recommend installing PHP Stan:
https://github.com/bitExpert/phpstan-magento

And then run:
vendor/bin/phpstan analyse --level 9 vendor/folder-of-the-class-with-issue

My issue was just misspelled return value for one of the functions.
