### ISSUE TITLE
New Customer Checkout not working for downloadable products

### ISSUE THREAD

**Issue by DJ0815** [magento/magento2#22770]
Hi,
I try to buy a download product, it does not matter whether free or paid. Guest Checkout for downloable products is disabled, so customer is asked to register first. Works fine, but when i am going to checkout as the new registered customer, enter my whole address (all required fields) under the payment method, i get the error message, that lastname and so on are required fields.

### Preconditions (*)
Magento CE 2.3.0
php 7.1
no payments methods added manually
problem appears on default luma and custom theme

### Steps to reproduce (*)

1. add a downloadable product to cart and try to checkout as guest.
2. guest checkout is disabled for downloads, so register as a new customer.
3. go to checkout, enter your adress (all required fields) and try to check out.
4. error appears to enter all required fields and customer cannot checkout

### Expected result (*)
customer can checkout without an error....

### Actual result (*)
customer gets error message to enter all required fields, although he has entered all
![magentocheckout](https://user-images.githubusercontent.com/29231142/57303378-7b495e80-70dd-11e9-95f3-420581bd9e80.jpg)

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22770-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22770-2-3-develop.instances.magento-community.engineering/admin](https://i-22770-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@DJ0815 I am not able to reproduce this issue at magento 2.3-develop instance can you please check &  confirm

**Comment by DJ0815** [comment]
Hi, i am really sorry, i could also not reproduce it, so it might be a local problem and i will close the ticket.
Sorry for inconveniences!
