### ISSUE TITLE
Unable to send mail on Magento 2.2.8 with Arabic or Persian locale as Sender Name

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#22778]
### Preconditions (*)

1. Magento 2.2.8
2. Persian or Arabic set as main locale

### Steps to reproduce (*)

1. Set sender Name for General Email a Persian or Arabic Name. Ex: نام فرستنده
2. Well to send any email as Welcome or Order confirmation

### Expected result (*)

1. Email should be sent correctly without any issue

### Actual result (*)

1. Error exception throw: Invalid header value detected
2. All mails failed to sent

**Comment by tuyennn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tuyennn, here is your [Magento instance](https://i-22778-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22778-2-3-develop.instances.magento-community.engineering/admin](https://i-22778-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tuyennn** [comment]
@magento-engcom-team confirmed issue on 2.3-develop instance No welcome email, order confirmation email.
Though from Magento 2.2.8 and Magento 2.3 the Zend Mail 1 was not exist and changed by Zend Mail 2 lib, in some kind the validation of Header was failed during mail send.

**Comment by tuyennn** [comment]
https://github.com/zendframework/zend-mail/issues/221
https://github.com/zendframework/zend-mail/issues/97

**Comment by tuyennn** [comment]
After debugging
```
vendor/zendframework/zend-mail/src/Header/HeaderValue.php
```

```
/**
     * Determine if the header value contains any invalid characters.
     *
     * @see    http://www.rfc-base.org/txt/rfc-2822.txt (section 2.2)
     * @param string $value
     * @return bool
     */
    public static function isValid($value)
    {
        $total = strlen($value);
        for ($i = 0; $i < $total; $i += 1) {
            $ord = ord($value[$i]);

            // bare LF means we aren't valid
            if ($ord === 10 || $ord > 127) {
                return false;
            }

            if ($ord === 13) {
                if ($i + 2 >= $total) {
                    return false;
                }

                $lf = ord($value[$i + 1]);
                $sp = ord($value[$i + 2]);

                if ($lf !== 10 || ! in_array($sp, [9, 32], true)) {
                    return false;
                }

                // skip over the LF following this
                $i += 2;
            }
        }

        return true;
    }
```

Just found out my Sender name was exceed int the ASCII value 127 characters and the validation was return false.

**Comment by mugua** [comment]
@tuyennn  I met the same issue using chinese words, how do you fix it ?
Mine: Magento 2.3.2+SMTP:Amasty
Thanks very much.

**Comment by tuyennn** [comment]
@mugua see ref issue and fix on above #22103

**Comment by mugua** [comment]
@tuyennn , still can't find which is the right fix method on #22103
Could you show me on this post, Thanks.

**Comment by tuyennn** [comment]
@mugua 
Use 2 ref here to create your own patch.
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Email/Model/Transport.php#L90
https://github.com/magento/magento2/issues/22103#issuecomment-491280738

For Amasty, please try to contact them for support. Or you could try to fix by yourself while adding
```
->setEncoding('utf-8')
```
To their own mail and transporter

**Comment by mugua** [comment]
@tuyennn  Well done, Fixed it now. Thanks a lot.

**Comment by ryandiamond23** [comment]
@magento-engcom-team give me 2.2.9 instance

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23. Thank you for your request. I'm working on Magento 2.2.9 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23, here is your [Magento instance](https://i-22778-2-2-9.instances.magento-community.engineering).
Admin access: [https://i-22778-2-2-9.instances.magento-community.engineering/admin](https://i-22778-2-2-9.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ryandiamond23** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23, here is your [Magento instance](https://i-22778-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22778-2-3-1.instances.magento-community.engineering/admin](https://i-22778-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
