### ISSUE TITLE
Product Page: Please enter a quantity greater than 0.

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#22785]
### Preconditions (*)

1. Magento 2.2.x Commerce Edition

### Steps to reproduce (*)

1. Add a simple product
2. Go to Advanced Inventory 
3. Set "Minimum Qty Allowed in Shopping Cart" to 1
4. Save product
5. Go to product page on frontend and try to add it to shopping cart.

### Expected result (*)

1. Qty input on product page default value = 1 (above value), should be equal to product settings
2. You can add product to shopping cart without any issues 

### Actual result (*)

1. Qty input has value  = 0 (not the one above)
2. Cannot add product to shopping cart
3. Validation error is visible next to input:  "Please enter a quantity greater than 0."
4. Product data-validate attribute = `{"required-number":true,"validate-item-quantity":{"minAllowed":0,"maxAllowed":10000}}`
Screenshot:
![stock](https://user-images.githubusercontent.com/4256191/57373944-f3755a00-7199-11e9-8aad-cb2019bbcd1d.png)

**Comment by AlexWorking** [comment]
Hello @qsolutions-pl. Thanks for reporting. Currently we are not able to reproduce Your issue. Please have a look at our video. Were we doing everything right as You meant?
![Inventory](https://user-images.githubusercontent.com/27814011/57377663-3adef480-7160-11e9-9584-73d7ea0c142e.gif)

**Comment by jakwinkler** [comment]
Our exact version is 2.2.5, maybe its version related?

**Comment by jakwinkler** [comment]
@AlexWorking the issue we experience is on Magento 2.2.5

**Comment by AlexWorking** [comment]
@qsolutions-pl though we usually do not consider bugs that are not reproduced on 2.2 and 2.3 develop versions we still have tried to reproduce it on 2.2.5 version as well. But unfortunately the result is the same - we've been not able to do that. Have You watched our gif above carefully? Probably we are missing something or doing it not exactly as You are doing it. Yet, for example, it sounds a bit strange to  "Set "Minimum Qty Allowed in Shopping Cart" to 1" when it is already set to it by default.

**Comment by jakwinkler** [comment]
When we set it to 1, on EE version it shows value 0 in the qty input. 
And when we try to add to shopping cart, we have following error displayed (the one attached)

**Comment by AlexWorking** [comment]
Ok, @qsolutions-pl, this feature ("Minimum Qty Allowed in Shopping Cart") is available only in EE. So what was the reason You set it to 1 when it already had been set to one by default?

**Comment by jakwinkler** [comment]
We import data from Magento 1, that data is set there and if that data is set, we got the error as submitted here.

**Comment by AlexWorking** [comment]
Thank You @qsolutions-pl. For posting issues related to migration from magento1 to magento2 there is a special repository https://github.com/magento/data-migration-tool. So we are closing this issue here and ask You to reopen it there. Also keep in mind that as an Enterprise Edition user You always may refer directly to Magento Support.

**Comment by jakwinkler** [comment]
@AlexWorking  please close the issue. This was related to data import.
We've created SQL scripts which fixed wrong data
