### ISSUE TITLE
Magento 2.3.1 - 2FA is not working

### ISSUE THREAD

**Issue by ghost** [magento/magento2#22782]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by AlexWorking** [comment]
Hello @rahulbarot. Please open this issue in a more appropriate repository https://github.com/magento/magespecialist_TwoFactorAuth providing the concrete Steps to Reproduce it with concrete Preconditions, Expected and Actual results. Thank You.
