### ISSUE TITLE
Client rejecting PHPSESSID cookie will create the sess file anyway.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#22789]
### Preconditions (*)

1. Magento 2.3.1
2. Alpine Linux on a Debian buster GNU/Linux host. 
3. PHP 7.2 

### Steps to reproduce (*)

1. Use a browser that can manually reject cookies (such as lynx or elinks). (I know someone will jump on that it is a text-based browser. That's not the point. Any browser can reject cookies.)
2. Reject the PHPSESSID cookie. 
3. Observe how the var/session/sess_* file gets created regardless. 

### Expected result (*)

1. The file not being created when rejecting the cookie.

### Actual result (*)

1. the file being created and being a waste of disk space.

**Comment by ghost** [comment]
Bug report for your bot. I cant click any of the confirm checkboxes
![image](https://user-images.githubusercontent.com/50411291/57379032-48b76880-71a6-11e9-9537-26b0c6af3379.png)

**Comment by ghost** [comment]
bump?

**Comment by engcom-Charlie** [comment]
Hello @tvanriel  ! We can not reproduce this issue follow steps that you provide.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

**Comment by ghost** [comment]
Hello, thanks for the response.

May I please know what step you are referring to? The comment your bot made is pretty generic and doesn't properly inform me on how to update or fix my bug report.

**Comment by engcom-Charlie** [comment]
@tvanriel please provide more details and more steps(for example i don't have  `var/session/` directory and i wont to know how to reject PHPSESSID cookie).
