### ISSUE TITLE
No Response from source item allocation API. (MSI)

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#22781]
### Preconditions (*)

1. Magento 2.3.0/2.3.1

### Steps to reproduce (*)

1. use V1/inventory/source-items API to allocate inventory.

### Expected result (*)

1. It should provide some result to know if anything fails or pass.

### Actual result (*)

1. getting an only empty response [] which is causing issues in third-party integrations.

**Comment by ankursachdeva11** [comment]
@magento-engcom-team , checked in 2.3.0 and 2.3.1 CE version. please provide the reason behind giving an empty response.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-22781-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22781-2-3-develop.instances.magento-community.engineering/admin](https://i-22781-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-22781-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22781-2-3-develop.instances.magento-community.engineering/admin](https://i-22781-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by irajneeshgupta** [comment]
@ankursachdeva11
It is not an issue , V1/inventory/source-items API is working as expected.
you may check http code 200 and response body [] in your third party integration.

**Comment by ankursachdeva11** [comment]
@irajneeshgupta , I know about API response body and status code. Which is working as expected.

I want to know the reason behind giving empty response []. 
No error when SKU is incorrect.

if we post multiple source-item updates in a single request and one source is incorrect then it will fail the whole request. why?

**Comment by VasylShvorak** [comment]
Hi @ankursachdeva11 thank you for your report.  Please open issue related with MSI in [msi](https://github.com/magento-engcom/msi) repo to get answer for your question.
