### ISSUE TITLE
Disable "Please upgrade your database" ?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#22797]
When you deploy a version of Magento to a live web server you may have multiple servers and you will eventually run bin/magento setup:upgrade as part of the deployment process.

However there is the possibility that has not run yet and instead you are presented with an exception.

It would be better if we had the option to suppress this, so the whole website is not taken offline!

### Preconditions (*)
1.Magento 2.3.1

### Steps to reproduce (*)
1.Deploy code that changes the setup_version or schema_version of a module in etc/module.xml

### Expected result (*)
1. User on the front end to be told to run bin/magento setup:upgrade
2. Have an option instead to bypass this error.

### Actual result (*)
1. User on the front end to be told to run bin/magento setup:upgrade

```
There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: 875229215420
```

2.

```
{"0":"Please upgrade your database: Run \"bin\/magento setup:upgrade\" from the Magento root directory.\nThe following modules are outdated:\nBazaarvoice_Connector schema: current version - 7.2.2, required version - 7.2.3\nBazaarvoice_Connector data: current version - 7.2.2, required version - 7.2.3","1":"<pre>#1 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:69]\n#2 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#3 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#4 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#5 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:136]\n#6 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#7 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#8 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:53]\n<\/pre>","url":"\/","script_name":"\/index.php"}
```

**Comment by shikhamis11** [comment]
Hello @craigcarnell 
I wanted to confirm that do you want there should be option that the error 
`Please upgrade your database` should not display at frontend ?

**Comment by cscd98** [comment]
@shikhamis11 Exactly, the schema being out of date, while important, should not bring the site down. Would like the option to suppress the error, instead perhaps write to a log file.

**Comment by shikhamis11** [comment]
Hello @craigcarnell 
sorry for delay in response , I think you must move the issue into feature request so that It must process faster https://github.com/magento/community-features/issues
