### ISSUE TITLE
Message to use Cron.php after install

### ISSUE THREAD

**Issue by erichileman** [magento/magento2#2279]
<img width="1376" alt="screenshot 2015-11-05 19 13 39" src="https://cloud.githubusercontent.com/assets/4987539/11005017/671923c6-8489-11e5-836c-ba513fde67aa.png">

**Comment by mazhalai** [comment]
@erichileman, this is expected. Unless you already have cron for indexers setup.

**Comment by erichileman** [comment]
The documentation is incorrectly showing users to schedule cron.php over HTTP.  The most recent patch for M1 SUPEE-6788 even removes this for security concerns.  Cron.php should not be run over HTTP.

Would it not be better to direct users to running the cron another way instead of asking them to "launch cron.php"?

**Comment by mazhalai** [comment]
{quote}
Would it not be better to direct users to running the cron another way instead of asking them to "launch cron.php"?
{quote}
Yes we will fix it in the ticket MAGETWO-45148

**Comment by rganin** [comment]
Fixed in 34b3d48
