### ISSUE TITLE
Admin section won't flush cache

### ISSUE THREAD

**Issue by knightfox1337** [magento/magento2#22809]
I am having problems with flushing cache on 2.2.8. When i go to the admin backend and try to flush it, it doesn't work. I can however use the cli to flush it. 
I am getting the same issue on another version (2.2.3) but when you click "flush magento cache" it 302s you to the front end and doesn't flush the cache. (i understand this is a separate issue)

### Preconditions (*)

1. Magento 2.2.8
2. php 7.2.16
3. Sonassi stack

### Steps to reproduce (*)

1.  Login to backend
2. Navigate to System -> cache management
3. click "flush magento cache"

### Expected result (*)

1. Returns to cache management page with message of "cache flushed"
2. Cache actually flushed

### Actual result (*)

1. redirecting to dashboard (302)
2. Cache not flushed.

**Comment by AlexWorking** [comment]
Hello @knightfox1337. Could You please try to reproduce Your issue on a clear instance of Magento as You were advised to do: 
![advise](https://user-images.githubusercontent.com/27814011/57510753-c83b5980-72c4-11e9-8bb5-a637445d4928.png)
Thank You.

**Comment by gulshanchitransh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gulshanchitransh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gulshanchitransh, here is your [Magento instance](https://i-22809-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22809-2-3-develop.instances.magento-community.engineering/admin](https://i-22809-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AlexWorking** [comment]
Hi @knightfox1337. The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
