### ISSUE TITLE
Bundles and tier price give unexpected results

### ISSUE THREAD

**Issue by kassner** [magento/magento2#22807]
### Preconditions

1. Magento Open Source 2.3.1;
2. Create a simple product with price $10.00 and tier price of $9.00 for 2 or more quantities;
3. Create a bundle product, with only one option, and add the simple product as the only selection, use `Quantity = 2` and `User defined = unchecked`;

### Steps to reproduce

1. Go to the bundle product page on the frontend;
2. Select qty = 1 and click add to cart. Minicart shows correct prices (unit $18, total $18);
3. Without leaving the page, select qty = 2 and click add to cart. Minicart shows wrong prices (unit $36, total $108, should be $18/$54);

![Screenshot from 2019-05-09 14-03-39](https://user-images.githubusercontent.com/301255/57452174-7ca49380-7263-11e9-8751-4482c48d39a9.png)

4. Without leaving the page, select qty = 3 and click add to cart. Minicart shows wrong prices (unit $54, total $324, should be $18/$108);

![Screenshot from 2019-05-09 14-04-18](https://user-images.githubusercontent.com/301255/57452185-80d0b100-7263-11e9-97d9-b5f58550ce4f.png)

5. Click `Proceed to Checkout`. Order summary has the wrong total:

![Screenshot from 2019-05-09 14-06-59](https://user-images.githubusercontent.com/301255/57452319-ca210080-7263-11e9-88a1-67c7cd7dc464.png)

6. Place the order;
7. Go to Admin > Sales > Order and select your order;
8. Check the Items ordered and the totals:

![Screenshot from 2019-05-09 14-08-50](https://user-images.githubusercontent.com/301255/57452427-0a807e80-7264-11e9-83c1-c7eada378466.png)

9. Click the `Ship` button. `Items to ship` report 6x the bundle product, as expected:

![Screenshot from 2019-05-09 14-11-51](https://user-images.githubusercontent.com/301255/57452581-7c58c800-7264-11e9-91a2-c30acca30b3e.png)

10. Edit the bundle product, set `Ship Bundle Items` as `Separately`;
11. Place a new order, repeating the steps 2 to 6;
12. Go to Admin > Sales > Order and select your new order and click the ship button. `Items to ship` report 36x the simple product, instead of just 12:

![Screenshot from 2019-05-09 14-16-40](https://user-images.githubusercontent.com/301255/57452870-2a647200-7265-11e9-9dae-1422a81ddcd9.png)

### Expected result

1. Order should have 6x the bundle product, meaning 12 simple products;
2. Subtotal should be $108.00;
3. The simple product row should show just once;

### Actual result

1. Order has 6x the bundle product, but it reports 36x simple product;
2. Subtotal is $324.00;
3. The simple product row shows 3 times;

**Comment by kassner** [comment]
My technical investigation:

When adding the product to the cart the 2nd (and subsequent times), `Magento\Quote\Model\Quote\Item::representProduct` returns false when iterating over the simple product. Digging a bit further, `compareOptions` reports false because the `bundle_selection_attributes` option for the quote_item already persisted contains the price inside:

```
{"price":"9.0000","qty":2,"option_label":"Option","option_id":"1"}
```

But, when the new cart item is being compared, the price is the original one:

```
{"price":10,"qty":2,"option_label":"Option","option_id":"1"}
```

This happens because `Magento\Bundle\Model\Product\Type::_prepareProduct` has this piece of code:

```
/*
 * Create extra attributes that will be converted to product options in order item
 * for selection (not for all bundle)
 */
$price = $product->getPriceModel()
    ->getSelectionFinalTotalPrice($product, $selection, 0, 1);
$attributes = [
    'price' => $price,
    'qty' => $qty,
    'option_label' => $selection->getOption()
        ->getTitle(),
    'option_id' => $selection->getOption()
        ->getId(),
];
```

`$product->getPriceModel()->getSelectionFinalTotalPrice` will take care of the tier price, but it's being called with a forced quantity of `1`, never triggering our tier price rule, so returning a price different than the one saved in the current quote item in the database. The result of this is having multiple simple products attached to the bundle in the `quote_item` table:

```
MySQL [magento]> select item_id, quote_id, created_at, updated_at, product_id, store_id, parent_item_id, sku, name, qty, price, base_price, custom_price from quote_item where quote_id=6;
+---------+----------+---------------------+---------------------+------------+----------+----------------+---------------+-------------+--------+---------+------------+--------------+
| item_id | quote_id | created_at          | updated_at          | product_id | store_id | parent_item_id | sku           | name        | qty    | price   | base_price | custom_price |
+---------+----------+---------------------+---------------------+------------+----------+----------------+---------------+-------------+--------+---------+------------+--------------+
|      22 |        6 | 2019-05-09 12:14:01 | 2019-05-09 12:14:07 |          2 |        1 |           NULL | bundle-simple | Test Bundle | 6.0000 | 54.0000 |    54.0000 |         NULL |
|      23 |        6 | 2019-05-09 12:14:01 | 2019-05-09 12:14:07 |          1 |        1 |             22 | simple        | Simple      | 2.0000 |  9.0000 |     9.0000 |         NULL |
|      24 |        6 | 2019-05-09 12:14:04 | 2019-05-09 12:14:07 |          1 |        1 |             22 | simple        | Simple      | 2.0000 |  9.0000 |     9.0000 |         NULL |
|      25 |        6 | 2019-05-09 12:14:07 | 0000-00-00 00:00:00 |          1 |        1 |             22 | simple        | Simple      | 2.0000 |  9.0000 |     9.0000 |         NULL |
+---------+----------+---------------------+---------------------+------------+----------+----------------+---------------+-------------+--------+---------+------------+--------------+
```

--

I am not sure why do we store the price there. Just removing the price from the previously mentioned `$attributes` makes everything working as expected. Is there any reason to have the price there, giving that this same price is stored in the `price`/`base_price` column in the quote_item table?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99620`, `MAGETWO-99621` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by akondratenkeo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @alexkwellbe. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @alexkwellbe, here is your [Magento instance](https://i-22807-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22807-2-3-develop.instances.magento-community.engineering/admin](https://i-22807-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Oscar** [comment]
Hi @kassner , I could not reproduce this issue on latest 2.4- develop branch, can you please recheck?

**Comment by marcomessa** [comment]
@magento-engcom-team give me 2.3-develop instance
