### ISSUE TITLE
Issue: Static block shows up above sidebar category page

### ISSUE THREAD

**Issue by Kjellzweers** [magento/magento2#22803]
### Summary (*)
Static block on category page show up above category sidebar, except for one page. Need to have them all like that one page, literally checked every option in category and in static block and it's all the same.

### Examples (*)
Code of the page that's correct: http://bit.ly/2LLa2GD
Code of the one of the other pages that doesn't work correctly: http://bit.ly/2LG60PM
Screenshot of the page that's correct: https://prnt.sc/nmb6gd
Screenshot of the page that isn't correct: https://prnt.sc/nmb6id

When I change the max-width (1150px) to for example 600px, it looks like this: https://prnt.sc/nmb85p

### Proposed solution
I really don't have a clue what the solution might be.

**Comment by hitesh-wagento** [comment]
Hi @Kjellzweers

I think you have set 1column layout in below screenshot. please once 2columns-left and test again.

https://prnt.sc/nmb6id
