### ISSUE TITLE
Store View Specific Labels tool tip icon not proper align

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#22812]
### Preconditions (*)

1.Magento 2.3

### Steps to reproduce (*)

1. Go to Admin
2. Marketing >> Cart Price rule
3. Labels
4. Review the Store View Specific Labels  and (?)

### Expected result (*)

1. https://www.screencast.com/t/49dUUmOw6h5

### Actual result (*)

1. https://www.screencast.com/t/nwBLFp8b

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22812-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22812-2-3-develop.instances.magento-community.engineering/admin](https://i-22812-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @abrarpathan19. May be issue is already fixed.
Thank you for your report.
