### ISSUE TITLE
Product stock alert - unsubscribe not working

### ISSUE THREAD

**Issue by davidpixie** [magento/magento2#22814]
### Preconditions (*)

1. Magento Commerce 2.3.1
2.  PHP 7.1.27

### Steps to reproduce (*)

1. Sign up for a "Notify me when back in stock" notification on a product
2. Check record is in **product_alert_stock** table
3. If so, try manually hitting the unsubscribe controller endpoint for that product whilst logged in: **site.com/productalert/unsubscribe/stock/product/1** (where "1" is the product ID). Alternatively, you can also parse the store parameter too: **site.com/productalert/unsubscribe/stock/product/1/?___store=store**

### Expected result (*)

1. The customer's alert for this product should be removed from **product_alert_stock** table

### Actual result (*)

1. The product alert is not removed.
2. But the **You will no longer receive stock alerts for this product.** message still displays on the frontend for the user.

Current Workaround:

It seems that the **_getAlertRow** method in the **Magento/ProductAlert/Model/ResourceModelAbstract.php** now expects the store_id to be parsed as well as the website_id. This wasn't the case in 2.2.x:

**2.2.8 version:**

```
protected function _getAlertRow(\Magento\Framework\Model\AbstractModel $object)
    {
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/test.log');
$logger = new \Zend\Log\Logger();
$logger->addWriter($writer);

        $connection = $this->getConnection();
        if ($object->getCustomerId() && $object->getProductId() && $object->getWebsiteId()) {
            $select = $connection->select()->from(
                $this->getMainTable()
            )->where(
                'customer_id = :customer_id'
            )->where(
                'product_id  = :product_id'
            )->where(
                'website_id  = :website_id'
            );
            $bind = [
                ':customer_id' => $object->getCustomerId(),
                ':product_id' => $object->getProductId(),
                ':website_id' => $object->getWebsiteId(),
            ];
            $logger->info($object->getCustomerId() . " / " . $object->getProductId() . " / " . $object->getWebsiteId());
            return $connection->fetchRow($select, $bind);
        }
        return false;
    }
```

**2.3.1 version:**

```
protected function _getAlertRow(AbstractModel $object)
    {
        $connection = $this->getConnection();
        if ($this->isExistAllBindIds($object)) {
            $select = $connection->select()->from(
                $this->getMainTable()
            )->where(
                'customer_id = :customer_id'
            )->where(
                'product_id  = :product_id'
            )->where(
                'website_id  = :website_id'
            )->where(
                'store_id = :store_id'
            );
            $bind = [
                ':customer_id' => $object->getCustomerId(),
                ':product_id' => $object->getProductId(),
                ':website_id' => $object->getWebsiteId(),
                ':store_id' => $object->getStoreId()
            ];
            return $connection->fetchRow($select, $bind);
        }
        return false;
    }
```

However, the execute method of the Unsubscribe controller hasn't updated to reflect this (**Magento/ProductAlert/Controller/Unsubscribe/Stock.php**):

**2.2.8 version:**

```
public function execute()
    {
        $productId = (int)$this->getRequest()->getParam('product');
        /** @var \Magento\Framework\Controller\Result\Redirect $resultRedirect */
        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        if (!$productId) {
            $resultRedirect->setPath('/');
            return $resultRedirect;
        }

        try {
            $product = $this->productRepository->getById($productId);
            if (!$product->isVisibleInCatalog()) {
                throw new NoSuchEntityException();
            }

            $model = $this->_objectManager->create(\Magento\ProductAlert\Model\Stock::class)
                ->setCustomerId($this->customerSession->getCustomerId())
                ->setProductId($product->getId())
                ->setWebsiteId(
                    $this->_objectManager->get(\Magento\Store\Model\StoreManagerInterface::class)
                        ->getStore()
                        ->getWebsiteId()
                )
                ->loadByParam();
            if ($model->getId()) {
                $model->delete();
            }
            $this->messageManager->addSuccess(__('You will no longer receive stock alerts for this product.'));
        } catch (NoSuchEntityException $noEntityException) {
            $this->messageManager->addError(__('The product was not found.'));
            $resultRedirect->setPath('customer/account/');
            return $resultRedirect;
        } catch (\Exception $e) {
            $this->messageManager->addException($e, __('We can\'t update the alert subscription right now.'));
        }
        $resultRedirect->setUrl($product->getProductUrl());
        return $resultRedirect;
    }
```

**2.3.1 version:**

```
public function execute()
    {
        $productId = (int)$this->getRequest()->getParam('product');
        /** @var \Magento\Framework\Controller\Result\Redirect $resultRedirect */
        $resultRedirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        if (!$productId) {
            $resultRedirect->setPath('/');
            return $resultRedirect;
        }

        try {
            $product = $this->productRepository->getById($productId);
            if (!$product->isVisibleInCatalog()) {
                throw new NoSuchEntityException();
            }

            $model = $this->_objectManager->create(\Magento\ProductAlert\Model\Stock::class)
                ->setCustomerId($this->customerSession->getCustomerId())
                ->setProductId($product->getId())
                ->setWebsiteId(
                    $this->_objectManager->get(\Magento\Store\Model\StoreManagerInterface::class)
                        ->getStore()
                        ->getWebsiteId()
                )
                ->loadByParam();
            if ($model->getId()) {
                $model->delete();
            }
            $this->messageManager->addSuccess(__('You will no longer receive stock alerts for this product.'));
        } catch (NoSuchEntityException $noEntityException) {
            $this->messageManager->addError(__('The product was not found.'));
            $resultRedirect->setPath('customer/account/');
            return $resultRedirect;
        } catch (\Exception $e) {
            $this->messageManager->addException(
                $e,
                __("The alert subscription couldn't update at this time. Please try again later.")
            );
        }
        $resultRedirect->setUrl($product->getProductUrl());
        return $resultRedirect;
    }
```

In my workaround, I'm manually setting the StoreId as follows:

```
->setStoreId(
                    $this->_objectManager->get(\Magento\Store\Model\StoreManagerInterface::class)
                        ->getStore()
                        ->getStoreId()
                )
```

This appears to fix the issue, and removes the alert from the **product_alert_stock** table.

**Comment by magento-engcom-team** [comment]
@AlexWorking Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@AlexWorking Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99641` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by davidpixie** [comment]
@irajneeshgupta 

Thanks for acknowledging and submitting fix as a PR!

**Comment by magento-engcom-team** [comment]
Hi @davidpixie. Thank you for your report. 
The issue has been fixed in magento/magento2#23459 by @yuriichayka in 2.3-develop branch
Related commit(s):
 - [259534d7f7fe143a7f5846a931657205fee24003](https://github.com/magento/magento2/commit/259534d7f7fe143a7f5846a931657205fee24003)
 - [e2b58cd92e8229dd1b95c6a8412ebd1f16dc4f6f](https://github.com/magento/magento2/commit/e2b58cd92e8229dd1b95c6a8412ebd1f16dc4f6f)

The fix will be available with the upcoming 2.3.3 release.

**Comment by nicoaghe** [comment]
Hello, 
I have magento 2.3.3 and the unsubscribe link doesn't work. 
For the stock alerts the link gets 404 error.
For the price alerts the unsubscribe link sends me to the product page, shows the message "You deleted the alert subscription.", but when i check in the database the product is still there. 
Any idea how can I solve this?
Thank you!

**Comment by ManikandanKaruppaiah** [comment]
Solution not worked fro me as well
