### ISSUE TITLE
It is not working support for "Sample Data" and "Sample Module" and "Third Party Module" in "Magento 2.0.0-rc"

### ISSUE THREAD

**Issue by cerebrumgit** [magento/magento2#2281]
========
en_US
========

Hello good afternoon

1)

It is not working support for "Sample Data" and "Sample Module" and "Third Party Module" in "Magento 2.0.0-rc"

2)

It was created the following program in Shell Script for the installation of Magento 2 with support for Sample Data and Sample Module

https://github.com/cerebrumgit/cerebrum/blob/master/magento2_install.sh

3)

To run the script enter the following commands in terminal

Note. Before you run the "./magento2_install.sh" be sure to check out the variables, especially "dbpass" and "directory_base"

wget --no-check-certificate https://raw.githubusercontent.com/cerebrumgit/cerebrum/master/magento2_install.sh
chmod + x ./magento2_install.sh
nano magento2_install.sh
./magento2_install.sh

4)

We see that is generated error

========
pt_BR
========

Ola Boa Tarde

1)

Não está funcionando o suporte a "Sample Data" e "Sample Module" e "Módulo de terceiros" no "Magento 2.0.0-rc"

2)

Foi criado o seguinte programa em Shell Script para a instalação do Magento 2 com suporte a Sample Data e Sample Module

https://github.com/cerebrumgit/cerebrum/blob/master/magento2_install.sh

3)

Para executar o script informe os seguintes comandos no terminal

Obs. Antes de executar o comando "./magento2_install.sh" certifique se conferir as variaveis, em especial "dbpass" e "directory_base"

	wget --no-check-certificate https://raw.githubusercontent.com/cerebrumgit/cerebrum/master/magento2_install.sh
	chmod +x ./magento2_install.sh
	nano magento2_install.sh
	./magento2_install.sh

4)

Vemos que é gerado erro 

=======================

![captura de tela de 2015-11-06 15 00 26](https://cloud.githubusercontent.com/assets/3661079/11005397/b2cd16ea-84a4-11e5-9b5d-3da78e49cbb7.png)
![captura de tela de 2015-11-06 15 02 34](https://cloud.githubusercontent.com/assets/3661079/11005399/b3018470-84a4-11e5-8c6a-110a2bd12989.png)
![captura de tela de 2015-11-06 15 04 00](https://cloud.githubusercontent.com/assets/3661079/11005400/b31bd168-84a4-11e5-939a-69cdba4c35ca.png)
![captura de tela de 2015-11-06 15 05 09](https://cloud.githubusercontent.com/assets/3661079/11005401/b32088de-84a4-11e5-84f2-833c16a0c1c2.png)
![captura de tela de 2015-11-06 16 35 06](https://cloud.githubusercontent.com/assets/3661079/11005402/b3249d20-84a4-11e5-8400-2da1f7fdd66d.png)
![captura de tela de 2015-11-06 16 37 17](https://cloud.githubusercontent.com/assets/3661079/11005403/b329964a-84a4-11e5-9c55-6287d41d97ca.png)

**Comment by mazhalai** [comment]
@cerebrumgit sample data process has been changed, Please refer to instructions [here](https://github.com/magento/magento2-sample-data)

**Comment by cerebrumgit** [comment]
========
en_US
========
Hello, good morning

1)

As images can apply the support sample data on Magento2

2)

You know me know about when you should be working on Magento2 support for "Sample Module" and "Third Party Module"?

I have interest in developing modules for Magento2, you recommend me to start developing modules or should I wait a little?

========
pt_BR
========

Ola Bom dia

1)

Conforme imagens consegui aplicar o suporte ao sample data no Magento2

2)

Você sabe me informar aproximadamente quando deve estar funcionando no Magento2 o suporte a "Sample Module" e "Módulo de terceiros" ?

Tenho interesse em desenvolver módulos para o Magento2, você me recomendaria iniciar o desenvolvimento de módulos ou eu deveria aguardar mais um pouco ?

========================

![captura de tela de 2015-11-09 11 29 05](https://cloud.githubusercontent.com/assets/3661079/11034994/a73dc0c0-86d6-11e5-965d-3676b210e537.png)
![captura de tela de 2015-11-09 11 29 09](https://cloud.githubusercontent.com/assets/3661079/11034995/a7402cca-86d6-11e5-8e96-f58a2b5c37b6.png)
![captura de tela de 2015-11-09 11 29 50](https://cloud.githubusercontent.com/assets/3661079/11034996/a7414132-86d6-11e5-99e4-ad69437304d9.png)
![captura de tela de 2015-11-09 11 30 02](https://cloud.githubusercontent.com/assets/3661079/11034997/a742bbe8-86d6-11e5-94ba-43c8e0574f54.png)
![captura de tela de 2015-11-09 11 30 26](https://cloud.githubusercontent.com/assets/3661079/11034998/a74a5a6a-86d6-11e5-96dd-765f3435df67.png)
![captura de tela de 2015-11-09 11 30 35](https://cloud.githubusercontent.com/assets/3661079/11034999/a74c11d4-86d6-11e5-89d5-6fa84469a1fa.png)
![captura de tela de 2015-11-09 11 34 49](https://cloud.githubusercontent.com/assets/3661079/11035001/a77856fe-86d6-11e5-8183-8520d63756d5.png)
![captura de tela de 2015-11-09 11 35 05](https://cloud.githubusercontent.com/assets/3661079/11035000/a777b74e-86d6-11e5-9b5b-c217104d64ae.png)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by cerebrumgit** [comment]
=========
en_US
=========

Good day

In the above interaction

---
mazalai commented 5 days ago
Regarding the modules samples we will fix it in scope of MAGETWO-41938
---

So far I can not make use of any module in "Magento 2.0.0-rc"

View as images

What did I do to use the module?

=========
pt_BR
=========

Bom dia

Na interação anterior 

---
mazhalai commented 5 days ago
Regarding the samples modules we will fix it in scope of MAGETWO-41938
---

Até o momento não consigo efetuar o uso de nenhum módulo no "Magento 2.0.0-rc"

Veja conforme imagens

Oque devo fazer para usar o módulo ?

![captura de tela de 2015-11-11 11 54 54](https://cloud.githubusercontent.com/assets/3661079/11093304/a1bb93f2-8870-11e5-8055-deabd414e5c7.png)
![captura de tela de 2015-11-11 12 14 58](https://cloud.githubusercontent.com/assets/3661079/11093305/a1c2ff02-8870-11e5-9232-7944a6509f24.png)
![captura de tela de 2015-11-11 12 15 09](https://cloud.githubusercontent.com/assets/3661079/11093306/a1cc0b9c-8870-11e5-8684-8d5faf628eae.png)
![captura de tela de 2015-11-11 12 15 13](https://cloud.githubusercontent.com/assets/3661079/11093308/a1cf7cfa-8870-11e5-9999-7e7bab263dda.png)
![captura de tela de 2015-11-11 12 22 09](https://cloud.githubusercontent.com/assets/3661079/11093307/a1ce3bf6-8870-11e5-81ea-c1c9b76d4a03.png)
![captura de tela de 2015-11-11 12 22 17](https://cloud.githubusercontent.com/assets/3661079/11093309/a24d1b74-8870-11e5-98cf-1f5bcee5cd84.png)

**Comment by cerebrumgit** [comment]
========
en_US
========

Able to operate the module in Magento 2

We see the following article

https://maxyek.wordpress.com/2015/03/27/building-magento-2-extension-lets-begin/

Who in October was put a new rule for modules must have the module root a file called registration.php

========
pt_BR
========

Consegui fazer funcionar o módulo no Magento 2

Vemos no artigo a seguir

https://maxyek.wordpress.com/2015/03/27/building-magento-2-extension-lets-begin/

Que em outubro foi colocado uma nova regra para módulos devendo ter na raiz do módulo um arquivo chamado registration.php
