### ISSUE TITLE
Disappearing products on admin 

### ISSUE THREAD

**Issue by Nickr33d** [magento/magento2#22816]
Hello,

i have been facing some issues recently on Magento Version 2.2.7 where by some products randomly disappear from the admin panel and the front end, in the last week i have seen multiple items which are not able to be located on the back end nor front subsequently i have had to recreate these items

there is not a method to reproduce this issue only when i have come to book in certain SKU and realised that its gone.

a resolution would be very helpfull as i now have no product sales/cost history for those lines making it very difficult to track profits etc

many thanks

**Comment by AlexWorking** [comment]
Hello @Nickr33d. Thanks for reporting, but the GitHub issue tracker is intended for Magento Core technical issues only which can be clearly reproduced having concrete Preconditions, Steps to Reproduce, Expected and Actual results. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
