### ISSUE TITLE
Incorrect overridden custom options & their values in email templates

### ISSUE THREAD

**Issue by arendarenko** [magento/magento2#22817]
### Preconditions (*)
1. Magento 2.2.8
2. Multistore (for example: Default and France)

### Steps to reproduce (*)

1. Create product with custom option (for example: Drop-Down) and add value into it.
2. Go to France Store View and override previously created custom option title and custom options values (the idea is that they should be named different than on Default store view)
3. Go to Orders -> Create new order -> Choose France store view -> Add previously created product with custom option value to order -> Wait until customer will receive new order email.

### Expected result (*)
1. Custom options title and value should be named like they named in France store view.

### Actual result (*)
1. Custom options title and value is named like they named in Default store view.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99639`, `MAGETWO-99640` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mallikaverma** [comment]
I am working on it..

**Comment by mallikaverma** [comment]
@magento-engcom-team  give me 2.3-develop instance

**Comment by mallikaverma** [comment]
#imagine2019

**Comment by mallikaverma** [comment]
@magento-engcom-team Can you please give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @arendarenko. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24421` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
