### ISSUE TITLE
GraphQL. Cannot query field "addSimpleProductsToCart" on type "Mutation"

### ISSUE THREAD

**Issue by YevgenK** [magento/magento2#22828]
### Preconditions
1. Magento 2.3.1 without sample data and installed modules 
2. Test product is set up

### Steps to reproduce
1. Add a simple product via admin panel 
2. Install ChromeiQL extension to run the request below
3. Create an empty cart according to the [doc](https://devdocs.magento.com/guides/v2.3/graphql/reference/quote.html#createEmptyCart) 
4. Add the simple product to cart according to https://devdocs.magento.com/guides/v2.3/graphql/reference/quote.html#add-simple-products-to-cart-attributes

### Expected result
1. Response with information about the added product 

### Actual result
1. Got error: Cannot query field "addSimpleProductsToCart" on type "Mutation"
![image](https://user-images.githubusercontent.com/2874309/57568397-9246c400-73ef-11e9-85b6-7d89014e71f1.png)

### Additional information
I found the class which should do the magic vendor/magento/module-quote-graph-ql/Model/Resolver/AddSimpleProductsToCart.php but seems like this file vendor/magento/module-quote-graph-ql/etc/schema.graphql has an only createEmptyCart definition.

**Comment by YevgenK** [comment]
Can I have any comment from Magento support team?

**Comment by Nazar65** [comment]
Hi @YevgenK thank you for you report, please open issue here -> https://github.com/magento/graphql-ce
