### ISSUE TITLE
Bundle products broken

### ISSUE THREAD

**Issue by fbrnc** [magento/magento2#2282]
Not sure if this is an issue in the Magento core or with the sample data.

However, I did a fresh install of M2 2.0.0-rc (both for Magento and the Sample Data) and I'm noticing the the only bundle product (id 2045 - the blue ball) doesn't have a name although this field is required (and I assume this is also the reason why I can't access this product in the frontend).

While trying to set a name Magento complains about the missing attribute price_type:

![06-11-_2015_12-56-11](https://cloud.githubusercontent.com/assets/468820/11008521/f18ea8ae-8485-11e5-893c-f83bcf28fbcd.jpg)

First of all this isn't very user-friendly since the user might not understand which field this message is really referring to.

And then of course the field is disabled and can't be set.

Of course the bundle product in the Sample data shouldn't have been broken in the first place...

**Comment by mazhalai** [comment]
@fbrnc thank you for reporting, we have created MAGETWO-45201 to fix this

**Comment by vzabaznov** [comment]
Hi @fbrnc , issue was fixed, please check it, and if you think that not, feel free to write here or to open new one
