### ISSUE TITLE
Should not hide element in page as In customer account register page a element hide from css, But we should properly remove from html

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#22832]
Should not hide element in page as In customer account register page a element hide from css, But we should properly remove from html

### Preconditions (*)
1. Magento 2.3 develop
2. php7.2 

### Steps to reproduce (*)
>> Open customer account register page 
>> inspect element in **create an account** and look `<div class="actions-toolbar">` and inside this look `<div class="secondary">`
>> Content of this ( `<div class="secondary">` ) is hide from css.

### Expected result (*)
>> We should remove element from phtml file as not showing element in any devices

### Actual result (*)
![issues](https://user-images.githubusercontent.com/26018716/57573257-c6af8580-73d9-11e9-853d-2d457dfa9ad8.jpeg)

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22832-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22832-2-3-develop.instances.magento-community.engineering/admin](https://i-22832-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Karlasa** [comment]
@cedarvinda 
Will close this issue as it should not be removed as css style is part of Luma Theme and we should not remove functionality that is part of Blank Theme and is visible there. 

Cheers,
