### ISSUE TITLE
Short-term admin accounts

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#22833]
### Description (*)
Merchants often create admin accounts for allowing extension vendors to support their extensions remotely. Such admin accounts often have simple, easy to guess passwords - and they are never removed even when no longer used.

### Expected behavior (*)

Ability to define how long given account is enabled. The account will be disabled after the specified time passes. There should be ability to reopen the account for another time frame or make it permanent. Additionally, system should propose high complexity password during account creation to encourage using strong passwords.

### Benefits

Given that majority of attacks on Magento installations include getting admin access and installing JavaScript malware, all features allowing to limit the admin accounts could help protect systems.

**Comment by lfolco** [comment]
Question about password complexity: should that be included in this issue or should it be moved into a separate issue? The two issues are related but are distinct functionality.
