### ISSUE TITLE
"Product online" switch

### ISSUE THREAD

**Issue by fbrnc** [magento/magento2#2283]
It is disturbing that the background of this icon is red (and not green), since red indicates that something is wrong.

Also there are many reasons why this product continues not to be accessible in the frontend. "Product online" is misleading.

![06-11-_2015_13-01-36](https://cloud.githubusercontent.com/assets/468820/11008641/bb80f7f2-8486-11e5-9e49-11b358b75dbb.jpg)

**Comment by MomotenkoNatalia** [comment]
Hi @fbrnc ! You are right. Such changes will be implemented in future, Internal ticket have been already created - MAGETWO-42171

**Comment by MomotenkoNatalia** [comment]
Hi @fbrnc !
This switcher is already green. Do you like new look and feel of product page?
