### ISSUE TITLE
Google Tag Manager: 500 error when removing items from cart

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#22857]
### Preconditions (*)

1. Magento 2.2.5 Commerce Edition
2. Enabled Google Tag Manager (vendor/magento/module-google-tag-manager)

### Steps to reproduce (*)

1. Enable GTM 
2. Add products to shopping cart
3. Go to cart page
4. Remove product from shopping cart and before page reloads, click to remove the same product again 

### Expected result (*)

1. Product is removed from shopping cart
2. No errors

### Actual result (*)

1. https://www.screencast.com/t/FWV3aKecl
2. Error in server logs

`Call to a member function getQty() on boolean in [...]/vendor/magento/module-google-tag-manager/Model/Plugin/Quote/SetGoogleAnalyticsOnCartRemove.php`

**Comment by jakwinkler** [comment]
any update on this?

**Comment by Leandry** [comment]
Hello @qsolutions-pl 

The current repository and issue tracker aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in[ Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:

> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> 
> You can use the Support portal associated with your account
> If you are a Partner reporting on behalf of a merchant, use the Partner portal.


Also, I was not able to reproduce the issue on the latest stable vanilla instance of Magento 2.3.2 Commerce. Product was removed successfully and no errors were noticed.

Thank you!
