### ISSUE TITLE
Magento script and style filtering issue in CMS Blocks and Pages

### ISSUE THREAD

**Issue by Siyadev9** [magento/magento2#22867]
### Preconditions (*)

1. Magento version 2.3.1
2. PHP version 7.2
3. MySQL 5.7

### Steps to reproduce (*)

1. Clean Magento 2.3.1 installation
2. Create a new block 
3. add some HTML and add CSS in <style> tag
4. Save and toggle between Editor and Code using Show/Hide Editor
5. You will see style and script tags are gone

### Expected result (*)

1. This is my input
 ![image](https://user-images.githubusercontent.com/29921007/57622959-01a6ea00-758f-11e9-93f2-5e15fed590a4.png)

### Actual result (*)

1. This is what I get after saving
![image](https://user-images.githubusercontent.com/29921007/57623002-1edbb880-758f-11e9-911e-a483e89d529e.png)

**Comment by Siyadev9** [comment]
Yes I was able to reproduce on a vanilla Magento 2.3.1

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22867-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22867-2-3-develop.instances.magento-community.engineering/admin](https://i-22867-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22867-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22867-2-2-develop.instances.magento-community.engineering/admin](https://i-22867-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @Siyadev9.
All css are applied properly.
Can you please check on front end all page/block display properly as applied css.
If any issue in front end then update the issue description.

**Comment by Siyadev9** [comment]
Hi @krishprakash. I create a new Magento 2.3.1 installation on my server and am still having this issue. I am also having this issue on my local windows machine. Any suggestions what it might be, or whether there is a setting I can check and test, both on Magento and in my environments?

**Comment by Siyadev9** [comment]
Hi @krishprakash. I tested on the servers created for you as well, if I wasn't suppose to please forgive me, and I am getting the issue on the 2.3 version. On the 2.2 version I can add the <style> tag and add styles with no issues.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99670` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by svorfolomiev** [comment]
It's probably a problem TinyMCE 3/4 redactor - it's removing the inline styles. Possible solution - add something like valid_children : "+body[style]" to TinyMCE config. Here more details: https://www.tiny.cloud/docs/configure/content-filtering/#valid_children.

**Comment by winds1983** [comment]
Same issue in 2.3.1, how to fix this? any patch?

**Comment by magento-engcom-team** [comment]
Hi @Siyadev9. Thank you for your report. 
The issue has been fixed in magento/magento2#24114 by @gwharton in 2.3-develop branch
Related commit(s):
 - [8c0958d735f88e4dab5faa6ab6d40b73f9f6a409](https://github.com/magento/magento2/commit/8c0958d735f88e4dab5faa6ab6d40b73f9f6a409)

The fix will be available with the upcoming 2.3.4 release.
