### ISSUE TITLE
image roles( base, small and thumbnail) is not set via rest api rest/V1/products/{sku}/media

### ISSUE THREAD

**Issue by mavajih** [magento/magento2#22863]
### Preconditions (*)

1. Magento Community 2.3.1
2. PHP 7.2.17
3. Mysql Server version: 5.7.26
4. Nginx on ubuntu 18.04.1

### Steps to reproduce (*)

1. Call Rest api with below python script
2. Python script code:
import base64
import urllib
from json import dumps
from pprint import pprint
from requests_oauthlib import OAuth1Session
client_key    = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
client_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
access_token  = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
access_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

magento = OAuth1Session(client_key,
                        client_secret = client_secret,
                        resource_owner_key = access_token,
                        resource_owner_secret = access_secret)

IMGFILENAME='testimage.jpg'
SKU='TESIMAGESKU3'
DOMAIN='https://beta.mywebsitedomain.com'

with open(IMGFILENAME, "rb") as image_file:
    b64_encoded_string = base64.b64encode(image_file.read()).decode("utf8")
raw_data = {'base64_encoded_data': b64_encoded_string, 'type': 'image/jpeg', 'name': IMGFILENAME}
json_data = dumps(raw_data, indent=2)
url = DOMAIN + '/rest/V1/products/' + urllib.parse.quote_plus(SKU) + '/media'
mystring = f'''
{{
  "entry": {{
    "media_type": "image",
    "label": "my image label",
    "position": 1,
    "disabled": false,
    "types": [
      "image",
      "small_image",
      "thumbnail"
    ],
    "content": 
        {json_data}
    ,
    "file": "{IMGFILENAME}"
 }} 
}}
'''
headers = {'content-type': 'application/json'}
response = magento.post(url, data=mystring, headers=headers)
print(str(response.text))
print(str(response.request.headers))
print(str(response.headers))

### Expected result (*)

1. In Image and Video section - image roles ( base, small and thumbnail) should be set
![expected_result_rest_api](https://user-images.githubusercontent.com/23309666/57616597-2bb2d900-759c-11e9-8f0b-e7c3fa675ab9.png)

### Actual result (*)

1. In Image and Video section - image roles ( base, small and thumbnail) is not set
![actual_result_rest_api](https://user-images.githubusercontent.com/23309666/57616698-6b79c080-759c-11e9-8af7-2ecd309b5c40.png)

**Comment by mavajih** [comment]
> Hi @mavajih. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @mavajih do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.
@magento-engcom-team  give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mavajih. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by mavajih** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mavajih. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mavajih, here is your [Magento instance](https://i-22863-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22863-2-3-develop.instances.magento-community.engineering/admin](https://i-22863-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mavajih** [comment]
Hi @magento-engcom-team I am not able to reproduce issue with steps i mentioned in given 2.3-develop instance. It is showing base, small, thumbnail but so it works, this is not happening in my case.

Also, image is not showing in product page - https://i-22863-2-3-develop.instances.magento-community.engineering/test-product3-for-image-via-rest-api.html

![Screenshot from 2019-05-13 17-50-21](https://user-images.githubusercontent.com/23309666/57620865-a7fee980-75a7-11e9-8e17-f159e4186081.png)

**Comment by mavajih** [comment]
Hi @magento-engcom-team can you please give solution for Magento community 2.3.1

**Comment by arnoudhgz** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz, here is your [Magento instance](https://i-22863-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22863-2-3-1.instances.magento-community.engineering/admin](https://i-22863-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mavajih** [comment]
Hi @arnoudhgz Did you reproduce issue or get success to set image roles on Magento 2.3.1 instance ?

**Comment by arnoudhgz** [comment]
@mavajih no, I could not reproduce it with in 2.3.1. Could be that also flat tables is the issue. I have the issue in my Commerce 2.3.1 instance for a client. But I don't know yet why.

**Comment by mavajih** [comment]
Hi @arnoudhgz If you got success to set image roles via rest api in 2.3.1, then please share payload and way you tried.

**Comment by arnoudhgz** [comment]
@mavajih no I only tested it in the back-end with normal upload / roles (this is where I have the issue and I thought it might be the same case).

**Comment by mavajih** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @mavajih. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @mavajih, here is your [Magento instance](https://i-22863-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22863-2-3-1.instances.magento-community.engineering/admin](https://i-22863-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by arnoudhgz** [comment]
@mavajih I created a PR which solves my issue, could you maybe check if you apply this same change to your installation it also solves your issue? 

`!isset` changed to `empty` check: https://github.com/magento/magento2/pull/22910

Please note that between Magento 2.3.1 an the current 2.3-develop branch this logic is moved to a new file. In Magento 2.3.1 this logic is still in `app/code/Magento/Catalog/Model/ProductRepository.php`

**Comment by mavajih** [comment]
@arnoudhgz thanks for suggestion but i tried this api URL /rest/all/V1/products/{sku}/media and it works. I guess, need to use "all" in api url when there are multiple websites/stores in single installation.

Now issue is - Product page's size image is generates but category page's images are not generated automatically when page renders or not pre-generated. I need to run "php bin/magento catalog:images:resize" everytime in magento root. Please suggest the way with we can automate this.

**Comment by arnoudhgz** [comment]
@mavajih this seems more an issue for your specific installation and not part of this issue. Please ask for help on stackexchange / stackoverflow. Or create a new issue

**Comment by arnoudhgz** [comment]
Closed since @mavajih found already the solution for his issue.
