### ISSUE TITLE
Error after install magento 2 rc with sample data

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#2286]
sytems.log

[2015-11-07 03:38:28] main.CRITICAL: 
Compilation from source: 
frontend/Magento/luma/en_US/css/email.less
variable @modal-slide-header__padding-vertical is undefined in file D:/App/htdocs/magentodev/var/view_preprocessed/css/frontend/Magento/luma/en_US/css/source/_theme.less in _theme.less on line 254, column 37
252| //  Modal popup
253| @modal-action-close__font-size: @font-size__base;
254| @modal-slide-action-close__padding: @modal-slide-header__padding-vertical @modal-popup__padding;
255| 
256| //  Checkout tooltip icon
257| @checkout-tooltip-icon__font-size: 21px;
 [] []
[2015-11-07 03:38:29] main.CRITICAL: 
Compilation from source: 
frontend/Magento/luma/en_US/css/email-inline.less
variable @modal-slide-header__padding-vertical is undefined in file D:/App/htdocs/magentodev/var/view_preprocessed/css/frontend/Magento/luma/en_US/css/source/_theme.less in _theme.less on line 254, column 37
252| //  Modal popup
253| @modal-action-close__font-size: @font-size__base;
254| @modal-slide-action-close__padding: @modal-slide-header__padding-vertical @modal-popup__padding;
255| 
256| //  Checkout tooltip icon
257| @checkout-tooltip-icon__font-size: 21px;
 [] []
[2015-11-07 03:42:39] main.ERROR: Sample Data error: Error in data structure: entity values are mixed [] []
[2015-11-07 03:43:25] main.ERROR: Sample Data error: Notice: Undefined index: Black
 in D:\App\htdocs\magento2-sample-data\app\code\Magento\SwatchesSampleData\Model\Swatches.php on line 131 [] []

**Comment by MomotenkoNatalia** [comment]
Related issue #2273

**Comment by dfediuk** [comment]
My universal fix for all the «variable @modal-slide-header__padding-vertical is undefined» problems: https://mage2.pro/t/193

**Comment by woei66** [comment]
diff --git a/app/design/frontend/Magento/luma/web/css/source/_theme.less b/app/design/frontend/Magento/luma/web/css/source/_theme.less
index 3ff123e..cbb274d 100644
--- a/app/design/frontend/Magento/luma/web/css/source/_theme.less
+++ b/app/design/frontend/Magento/luma/web/css/source/_theme.less
@@ -19,6 +19,8 @@
 @icons__font-path: '@{baseDir}fonts/Luma-Icons';
 @icons__font-name: 'luma-icons';

+@import 'components/_modals.less';
+
 //  Color nesting
 @panel__background-color: @color-gray-light0;
 @border-color__base: @color-gray80;

**Comment by woei66** [comment]
reference to https://github.com/magento/magento2/issues/2273#issuecomment-155225366
you should
1. modify the app/design/frontend/Magento/luma/web/css/source/_theme.less
2. rm -rf var/
3. bin/magento setup:upgrade
4. bin/magento setup:static-content:deploy

**Comment by woei66** [comment]
sometime, you may see the memory message like
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12475503 bytes)
you should modify the /etc/php.ini or /etc/php-5.6.ini and change the memory_limit = 512M

**Comment by minhluan259** [comment]
@woei66 @dfediuk  , i've fixed _theme.less
but remaining errors

[2015-11-07 03:42:39] main.ERROR: Sample Data error: Error in data structure: entity values are mixed [] []
[2015-11-07 03:43:25] main.ERROR: Sample Data error: Notice: Undefined index: Black
in D:\App\htdocs\magento2-sample-data\app\code\Magento\SwatchesSampleData\Model\Swatches.php on line 131 [] []

Data were missing something

**Comment by vektor-dev** [comment]
Same problem here: 
Compilation from source: 
frontend/Vektor/petscorner/en_US/css/email-fonts.less

Any way of sorting it out?
