### ISSUE TITLE
Linnworks product images are not getting updated in magento 2.3

### ISSUE THREAD

**Issue by RezaidFaisalHameed** [magento/magento2#22861]
Magento 2.3 Integration with Linnworks.

When syncing products from linnworks to magento 2.3, all data related to product is transferred except the images.

Following is the Magento API response when image request is sent from Linnworks

HTTP/1.1 400 Bad Request
Date: Fri, 10 May 2019 18:35:52 GMT
Server: Apache/2.4.29 (Ubuntu)
Set-Cookie: PHPSESSID=rg6almkkiho90t4hprf8bktvqq; expires=Fri, 10-May-2019 19:35:52 GMT; Max-Age=3600; path=/; domain= HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 41
Connection: close
Content-Type: application/json; charset=utf-8

{"message":"The product can't be saved."}

**Comment by RezaidFaisalHameed** [comment]
**Summary of the issue**

Magento 2.3 Integration with Linnworks.

When syncing products from linnworks to magento 2.3, all data related to product is transferred except the images.

Following is the Magento API response when image request is sent from Linnworks

HTTP/1.1 400 Bad Request
Date: Fri, 10 May 2019 18:35:52 GMT
Server: Apache/2.4.29 (Ubuntu)
Set-Cookie: PHPSESSID=rg6almkkiho90t4hprf8bktvqq; expires=Fri, 10-May-2019 19:35:52 GMT; Max-Age=3600; path=/; domain= HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 41
Connection: close
Content-Type: application/json; charset=utf-8

{"message":"The product can't be saved."}


  **Information on your environment**

Magento 2.3

  **Steps to reproduce**

    1. From linnworks add items to magento 2 configurator
    2. Click the create or update button 
    3. Item information is sent from linnworks to magento
    4. Open mangeto 2 admin
    5. Look for the same product in catalog -> products
    6. The product information will be there but with out any images.
   

  **Expected and actual results**

    The images should be displayed in magento 2.3

     But Images are not displaying in magento 2.3

**Comment by ankitsrivastavacedcoss** [comment]
Hello @SS7User 
I think you have to contact the Linnworks support or your module provider for this issue only they can help you properly because this issue can not be reproducible in the vanilla instance of magento.

**Comment by Nazar65** [comment]
Hi @SS7User 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
