### ISSUE TITLE
Edit existing shipping address on checkout page not working

### ISSUE THREAD

**Issue by suvajitxejic** [magento/magento2#22860]
### Summary (*)
The feature required is to allow the logged in user to edit any of his previously added address on the checkout page.

Initially, the edit option was not there against the existing addresses. I changed the following lines in the following file

> /Magento_Customer/web/js/model/customer/address.js

```
 isEditable: function ()
 {
     return true;       
 },
```
In doing so the edit link does appear on the addresses. ( please check the links in the Examples Section ) 

Now the problem is when I click on the edit link, the popup which gets displayed doesn't have the fields populated with the address selected ( please check the links in the Examples Section ). If I fill the fields up and save the address, it gets added as a new address.

Another point to notice here: If I add a new address and save it and without refreshing/redirecting I click on edit then the form fields populate properly and gets saved properly as well.

Does anyone have any suggestion or solution as to how to allow edit of the old addresses properly on the checkout step?

### Examples (*)
[http://tinyurl.com/yxdcocln](http://tinyurl.com/yxdcocln)
[http://tinyurl.com/y2eu7ajn](http://tinyurl.com/y2eu7ajn)

### Proposed solution
On clicking on edit button, the functionality actually edits the selected address, rather than displaying a new address form.

**Comment by krishprakash** [comment]
Hi @suvajitxejic. Thank you for your report.
This is not an issue.
It should be considered as feature request so for processed faster please report this in below community feature repository.
https://github.com/magento/community-features/issues
Thank you.

**Comment by suvajitxejic** [comment]
Hi @krishprakash 

I created a issue in the specified community but an edit link shouldn't behave as a add new address form, right? So isn't it more of a issue. Also as per your suggestion, do you mean that the edit functionality was never done?

**Comment by krishprakash** [comment]
Hi @suvajitxejic.
No, Default magento does not provide edit feature for existing addresses.
You can review for this in #4771
Please refer to the Community Forums or the Magento Stack Exchange site for advice or general discussion about this.
Thank You.

**Comment by gustavo807** [comment]
Is there an update?

**Comment by sanganb** [comment]
Issue resovled?

**Comment by Shooler87** [comment]
Still waiting? Any links to other related issues?
