### ISSUE TITLE
Catalog Products Page not open

### ISSUE THREAD

**Issue by nilarocks** [magento/magento2#22862]
### Preconditions (*)

1. Magento 2.3.1 
2. PHP 7.1.4

### Steps to reproduce (*)

1. Login In backend
2. click ON  Catalog->Products 

### Expected result (*)

1. open Products Grid page

### Actual result (*)

1. Give a error "There has been an error processing your request"
2. IN report, 
`{"0":"Warning: Magento\\Framework\\Locale\\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in G:\\xampp-win32-7.1.4-0-VC14\\xampp\\htdocs\\repo\\vendor\\magento\\framework\\Locale\\TranslatedLists.php on line 202","1":"<pre>#1 Magento\\Framework\\Locale\\TranslatedLists->getCountryTranslation('AN') called at `

**Comment by AlexWorking** [comment]
Hello @nilarocks. Thanks for reporting. But the GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
