### ISSUE TITLE
actionGroup ProductSetAdvancedPricing does not work for Fixed Price

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2#22879]
### Preconditions (*)

1. Magento 2.3.0

### Steps to reproduce (*)

1. Create a custom MFTF Test and use the action group ProductSetAdvancedPricing with argument price = "Fixed"
2. Run the test

### Expected result (*)

1. This should normally fill the advanced price form with a fixed discount amount.

### Actual result (*)

1. The test fails and does not find the selector `[name='product[tier_price][0][percentage_value]']`

In magento/module-catalog/Test/Mftf/ActionGroup/AdminProductActionGroup.xml line 205 the amount is inserted into the field with the selector `{{AdminProductFormAdvancedPricingSection.productTierPricePercentageValuePriceInput('0')}}`
But this field only exists, when the price argument is set to "Discount". As soon as this is "Fixed", the field is called `product[tier_price][0][price]`.
So either the action group should be renamed to "ProductSetAdvancedPricingDiscountAmount" and the price removed or there should be a condition check which decides which field to fill.

**Comment by Nazar65** [comment]
Hi @norgeindian thank you for you report, please open issue here -> https://github.com/magento/magento2-functional-testing-framework
