### ISSUE TITLE
ACL issue

### ISSUE THREAD

**Issue by deepakk-webkul** [magento/magento2#22877]
### Preconditions (*)
1. Magento CE 2.2.8 with sample data installed
2. PHP 7.1.27

### Steps to reproduce (*)
1. Login to Magento 2 admin panel with your current admin user (that has full access).
2. Add a new admin user from "System > Permissions > All Users" page.
3. Go to permissions user roles page (System > Permissions > User Roles), and click "Add New Role" button.
4. Fill the "Role Name" under "Role Info" tab.
5. Change "Resource Access" to "Custom".
6. Make sure that some "Resources" checkboxes are checked, According to screenshot
![Screenshot](https://user-images.githubusercontent.com/50043226/57674346-adf2da00-763c-11e9-91f1-883b4ca5c907.png)
7. Go to "Role Users" tab and select the new user that you added in step 2.
![Screenshot (1)](https://user-images.githubusercontent.com/50043226/57674449-f4483900-763c-11e9-8d4d-f6160a8b07d4.png)
8. Click "Save Role" button.
9. Logout from admin panel.
10. Login to admin panel with the new user that you created in step 2.

### Expected result (*)
1.  Go to Stores –> If we try to click on the Configuration section then configuration section page should be open.

### Actual result (*)
1. Go to Stores –> If we try to click on Configuration section / All Stores section then screen will be redirected on Sales order page.

**Comment by deepakk-webkul** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar, here is your [Magento instance](https://i-22877-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22877-2-2-develop.instances.magento-community.engineering/admin](https://i-22877-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gulshanchitransh** [comment]
I cannot reproduce this issue on this instance.

**Comment by deepakk-webkul** [comment]
@gulshanchitransh This issue is only reproducible on Magento 2.2.8 instance

**Comment by gulshanchitransh** [comment]
@magento-engcom-team give me 2.2.8-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gulshanchitransh. Thank you for your request. I'm working on Magento 2.2.8-develop instance for you

**Comment by AlexWorking** [comment]
Hello @webkul-deepakkumar. Thanks for reporting. Could You please try to reproduce Your issue on 2.3-develop versionю

**Comment by deepakk-webkul** [comment]
@AlexWorking I have already checked this issue on 2.3 develop but can't be reproduced, this issue is only coming under Magento 2.2.8 instance

**Comment by AlexWorking** [comment]
@webkul-deepakkumar, we also haven't been able to reproduce it on 2.3-develop version. Therefore according to our instructions You may find above on this page, 
![223](https://user-images.githubusercontent.com/27814011/57692945-45d4d180-7605-11e9-9ce1-1d8f5fd48fcb.png)
we are closing the issue.
