### ISSUE TITLE
Remove required from UPS shipping fields

### ISSUE THREAD

**Issue by ghost** [magento/magento2#22878]
### Preconditions (*)
1. Magento 2.3-develop

### Steps to reproduce (*)
1. Go to "Shipping Methods" tab under Store Configuration
2. Click on "Save Config"

### Expected result (*)
1. Save without any issue

### Actual result (*)
1. Not able to save because some fields in UPS are required
2. ![Screenshot_533](https://user-images.githubusercontent.com/42089978/57680789-0c738480-764c-11e9-860c-0ec6f806aefb.png)

**Comment by AlexWorking** [comment]
Hello @sanjaychouhan-webkul. Thanks for reporting, but we ought to close this issue as a duplicate of https://github.com/magento/magento2/issues/22786.
