### ISSUE TITLE
\Magento\CatalogInventory\Model\StockRegistry $scopeId parameter value immediately overwritten

### ISSUE THREAD

**Issue by jefflenz** [magento/magento2#22872]
### Preconditions (*)
1. 2.3.1 Commerce

### Steps to reproduce (*)
1. Call the function \Magento\CatalogInventory\Model\StockRegistry->getStockStatus($productId, $scopeId) with a $scopeId of 1 (or any other storeview)

### Expected result (*)

1. Should return stock status for passed value for $scopeId

### Actual result (*)
1. The value of $scopeId is overwritten in the function with this line:
`$scopeId = $this->stockConfiguration->getDefaultScopeId();`

**Comment by engcom-Charlie** [comment]
Hello @jefflenz 
As you can see that all tests fell on PR #23231 because it is not so easy to fix and a [Magento Inventory project](https://github.com/magento/inventory/wiki) was created for this.
So i have to close this issue.
Thanks for your report!
