### ISSUE TITLE
ProductRepository fails to update an existing product with a changed SKU

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#22870]
### Preconditions (*)
1. Magento 2.3.1
2. One product with SKU = "EXAMPLE"

### Steps to reproduce (*)
1. Load a ProductInterface for the product with SKU "EXAMPLE" 
2. Execute $product->setData('sku', 'CHANGE')
3. Execute $productRepository->save($product)
4. The productRepository will silently fail to retrieve the existing product while saving at code vendor/magento/module-catalog/Model/ProductRepository.php:578 and continue the process without finding the product that already exists. 
5. This in turn causes a problem with existing media images and obstructs saving. 

### Expected result (*)
1. The product should be detected as existing product correctly and the sku should be adjusted accordingly.
2. The product is saved correctly.

### Actual result (*)
1. In my case when the product had images attached in the media gallery I was unable to save the product because I received an error `The image content is invalid. Verify the content and try again.`

I'm assuming that the original author of the code is making the assumption that the SKU will never change for a product and if it changes it's a new product. Also because it's unique it helps to identify products but in some cases a single product may have more than one SKUs to it depending on the manufacturer / origin / barcode etc etc.  In most ERPs there's the ability to add multiple SKUs under one product entity and it wouldn't be reasonable to create 20 different items which are 99% the same data for each SKU.

 As a note, the sku can be changed directly in the edit form of Magento products.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99720` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr, @p-bystritsky. 

Thank you for your report and collaboration!

The issue was fixed and delivered in the scope of https://github.com/magento/magento2/pull/22933

The fix will be available with the upcoming `2.3.3` release.
