### ISSUE TITLE
Need a useful way for an average store administrator to register an external code repository to the Composer

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2288]
I host my [Magento 2 extensions](https://mage2.pro/c/extensions) in an external repository and make it available for the Composer with the following code in the root [`composer.json`](https://github.com/magento/magento2/blob/develop/composer.json) file:

```
"repositories": [
	{
		"type": "composer",
		"url": "http://packages.magento.com/"
	}
	,{
		"type": "composer",
		"url": "mage2.pro"
	}
]
```

It works nice for me, but the root [`composer.json`](https://github.com/magento/magento2/blob/develop/composer.json) file is under the source control so when I need to update Magento it leads to the file version conflict. It is OK for me to resolve such conflicts, but it could be too complicated for an average store administrator who uses my extensions.

Need a useful for an average store administrator method to register an external code repository in the Composer.
I like the solution of a similar problem: storing an authentication credentials in the external [`auth.json`](https://getcomposer.org/doc/articles/http-basic-authentication.md) file.
Maybe Magento could use a similar solution (an external `*.json` file not under the source control) for storing a custom repository info and other custom composer configuration?

**Comment by dfediuk** [comment]
I have found the solution: https://getcomposer.org/doc/03-cli.md#composer-home-config-json

**Comment by alankent** [comment]
Hi. For production sites we recommend to *not* use git clone to get the code base checked out. We recommend downloading packages from the Magento composer repository, so projects should have its own composer.json file (not the one from the git repo). But this is still useful for those who want to try unreleased code.
