### ISSUE TITLE
Static content deploy - Randomly css files not generated

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#22880]
### Preconditions (*)
1. Magento 2.3.x(2.3-develop too)
2. Configured Build system according to [technical details](https://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/technical-details.html).
3. Create own theme that extends from Magento/luma
4. Magento mode is **default** OR **developer**

### Steps to reproduce (*)
1. Run `php bin/magento setup:static-content:deploy -f -j $(nproc)` (`-j 8` in my case) with 6 different locales **on build system**

### Expected result (*)
1. We should NOT have any errors/exceptions during SCD

### Actual result (*)
1. **Randomly** we have following issue (sometimes from 4-5th time):
- Some CSS files are missing in pub/static directory
- Exception somewhere in the middle of SCD

![image](https://user-images.githubusercontent.com/51680850/63772618-22970f00-c8e2-11e9-8167-92d762e264d1.png)

This happening really randomly, sometimes with Magento/luma theme, sometimes with our own
**File with errors:**
[errors.txt](https://github.com/magento/magento2/files/3546118/errors.txt)

### Technical details
During SCD - it tries to compile LESS -> CSS files. During working on it - it tries to create lock, add some files and then unlock:
https://github.com/magento/magento2/blob/15e3c07f3aeb94d4147e49401d409afc3dcd93c9/lib/internal/Magento/Framework/View/Asset/PreProcessor/AlternativeSource.php#L108-L116

Details of these locks:
https://github.com/magento/magento2/blob/15e3c07f3aeb94d4147e49401d409afc3dcd93c9/lib/internal/Magento/Framework/View/Asset/LockerProcess.php#L63-L77

 and 
https://github.com/magento/magento2/blob/15e3c07f3aeb94d4147e49401d409afc3dcd93c9/lib/internal/Magento/Framework/View/Asset/LockerProcess.php#L83-L90

As you can see above - locking process doesn't work in production mode, but static contend deploy we're running when env.php file is not present, so by fallback it runs in "default" magento mode.

Also that's not expected to have some lock when we're running SCD in parallel, it might significantly slow down this process.

This issue was discovered during testing https://github.com/magento/magento2/pull/22607

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19666` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#22886 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [63063bcc6cb9a2343a906d0e05e3f7490b8a6a0d](https://github.com/magento/magento2/commit/63063bcc6cb9a2343a906d0e05e3f7490b8a6a0d)
 - [0f43b32c2d5a22bee305fa8bc211f835d4590b59](https://github.com/magento/magento2/commit/0f43b32c2d5a22bee305fa8bc211f835d4590b59)

The fix will be available with the upcoming 2.3.4 release.
