### ISSUE TITLE
Search criteria not working.

### ISSUE THREAD

**Issue by gg24** [magento/magento2#2289]
I want to narrow the search in the following way,

http://magento2.magestore.com/rest/V1/products/search?searchCriteria[filterGroups][][filters][][field]=sku&searchCriteria[filterGroups][][filters][][value]=WH01&searchcriteria[filter_groups][][filters][][condition_type]=eq

http://magento2.magestore.com/rest/V1/categories/24/search?
searchCriteria[filterGroups][][filters][][field]=url_key&
searchCriteria[filterGroups][][filters][][value]=women&
searchCriteria[filterGroups][][filters][][condition_type]=eq

http://www.example.com/rest/V1/categories/24/products/search?
searchCriteria[filterGroups][][filters][][field]=custom_segmentation&searchCriteria[filterGroups][][filters][][value]=3,4&searchCriteria[filterGroups][][filters][][condition_type]=eq

so how should i filter the collection on the basis of magento attributes, custom attributes.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
