### ISSUE TITLE
Disabled config can be overwritten via admin

### ISSUE THREAD

**Issue by kassner** [magento/magento2#22890]
Related to #19609

### Preconditions

1. Magento Open Source 2.3.1;
2. `php bin/magento config:set --lock-config general/store_information/name "Test lock"`;

### Steps to reproduce

1. Go to Admin > Stores > Configuration > General > General > Store Information;
2. On the disabled input for the Store Name field, use the browser tool to remove the `disabled="disabled"` attribute from the `<input>` field;
3. Change the value and click `Save Config`;
4. The value is unchanged;
5. On the store selector, change the scope to `Main Website`;
6. On the disabled input for the Store Name field, use the browser tool to remove the `disabled="disabled"` attribute from the `<input>` field;
7. Change the value and click `Save Config`;

### Expected result

1. The value is not saved.

### Actual result

1. The value is changed, but the field is disabled.

![Screenshot from 2019-05-14 15-17-48](https://user-images.githubusercontent.com/301255/57701070-7a737800-765b-11e9-90a2-d223c33d6ca1.png)

**Comment by landryr121** [comment]
Thank you

**Comment by engcom-Charlie** [comment]
Hello @kassner 
I am closing this issue because it is fixed on Magento 2.3-develop in this [PR](https://github.com/magento-engcom/magento2ce/pull/3045).
Thanks for your report!
