### ISSUE TITLE
Declined Error. Paypal not the issue Error 10606

### ISSUE THREAD

**Issue by Eduran1234** [magento/magento2#22896]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by ajijshekh123** [comment]
Hi, @Eduran1234. Thank you for your report.
Please explain the issue in the proper format.
Explain in the description, step to be reproduced, Expected result and Actual result properly.

Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ajijshekh123** [comment]
@Eduran1234  fell free to reopen this issue when you will be ready to provide more details and we will review it and confirm
