### ISSUE TITLE
Payment Declined 10606 Transaction rejected please contact the buyer

### ISSUE THREAD

**Issue by Eduran1234** [magento/magento2#22897]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
This issue is related to #22896.
@Eduran1234 - If this issue found in a different scenario, Please add a proper step to be reproduced, Actual result and Expected result.

**Comment by ajijshekh123** [comment]
Hi, @Eduran1234. Thank you for your report.
Please explain the issue in the proper format.
Explain in the description, Step to be reproduced, Expected result and Actual result properly.

Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ajijshekh123** [comment]
@Eduran1234  fell free to reopen this issue when you will be ready to provide more details and we will review it and confirm.
