### ISSUE TITLE
Ability to redefine module sequence of core or third party modules. 

### ISSUE THREAD

**Issue by magicaner** [magento/magento2#22892]
### Description (*)

There is ability to setup modules sort order by using sequence tag in module.xml. Current implementation of module.xsd allows to put multiple <module> tags into module.xml. But reader would read only first module definition from the list. 
The idea of current feature it to fix module config reader so that it can read and merge multiple module definition from module.xml. And then merge them all to single list before sorting procedure. 
Proposed way of implementation would allow to define sequence for core or other third party modules. Developers will be able to make any existing third party modules be depended on their modules.
There is question: Why such feature needed at all?  
Here is use case: There is a module which has corrupt data in database. And it has setup upgrade script which has to be run using those data. Sure thing, the script fails with exception. 
To fix this, it is good choice to use new module with new setup upgrade script and load it before buggy module. 

### Expected behavior (*)

Feature allows to define sequence of other modules in current module.xml. 
For example below is module.xml which makes core Magento_Quote module depended on Vendor_Module
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Vendor_Module" setup_version="1.0.0">
    </module>
    <module name="Magento_Quote">
        <sequence>
            <module name="Vendor_Module" />
        </sequence>
    </module>
</config>
```

### Benefits

Ability to load setup upgrade scripts before existing modules.

**Comment by orlangur** [comment]
Hi @magicaner, `module.xml` will be eliminated soon (see https://github.com/magento/architecture/blob/master/design-documents/simplified-module-declaration.md) so new features should not be added on top of it.
