### ISSUE TITLE
Can't Add Google Analytics - Get cacheing error everytime

### ISSUE THREAD

**Issue by VSevenUser** [magento/magento2#22900]
**Preconditions** 
Magento 2.2.2

**Steps to reproduce**
Sales >> Google API >> Enabled >> Add Tracking Code >> Anonymous IP NO >> Enable Content Experiments NO
Save
Get error: One or more of the Cache Types are invalidated: Configuration, Page Cache. Please go to Cache Management and refresh cache types.
All information in Google API is erased. 
No Google UA number found when checking site with inspector view. 

### Expected result (*)

1. Google Analytics to be installed and tracking. 
2. UA number to be saved in the Google API section

### Actual result (*)

1. Google Analytics to be installed 
2. Google UA Information is gone

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-22900-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22900-2-2-develop.instances.magento-community.engineering/admin](https://i-22900-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by soleksii** [comment]
Hi @VSevenUser , thank you for your report, this issue has already fixed in 2.2-develop and 2.3-develop branch and available on 2.2.9 and 2.3.1 release.
