### ISSUE TITLE
Cart is emptied on product update

### ISSUE THREAD

**Issue by tschirmer** [magento/magento2#22905]
### Preconditions (*)

1. 2.3.1
2. php 7.2

### Steps to reproduce (*)

1. Create a simple product
2. Add product to cart
3. Goto Cart page (view / edit cart from minicart)
4. Update the product qty within cart and press enter

### Expected result (*)

1. Product qty should change in cart

### Actual result (*)

1. Cart is emptied and no items are left in cart

**Comment by tschirmer** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tschirmer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tschirmer, here is your [Magento instance](https://i-22905-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22905-2-3-develop.instances.magento-community.engineering/admin](https://i-22905-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tschirmer** [comment]
Found that this issue isn't present on the latest build of Magento as spunup by the bot. 

This is current on Magento 2.3.1 as spun up by the bot in https://github.com/magento/magento2/issues/22488
