### ISSUE TITLE
Failed to load the "ui/grid/cells/html"

### ISSUE THREAD

**Issue by pietervanuhm** [magento/magento2#22912]
### Preconditions (*)

1. Magento 2.2.8
2. Magento Admin - All views where tablegrids are used and then only in cells with multiple lines.

### Steps to reproduce (*)

1. Go to Sales > Orders
2. The pages keeps loading in de console log you see 2 errors.
-- If you do a CTRL + F5 the page is loaded but with empty cells where are multiple lines, like Purchase Point, Shipping address etc.

**Error 1:** /static/version1557983524/adminhtml/Magento/backend/en_US/Magento_Ui/templates/grid/cells.html:1 Failed to load resource: the server responded with a status of 404 ()

**Error 2:** console-output-handler.min.js:2
[2019-05-16 10:35:33] [ERROR] Failed to load the "ui/grid/cells/html" template requested by "sales_order_grid.sales_order_grid.sales_order_columns.store_id".

### Expected result (*)

1. Page correctly loaded, with data in the multiple line cells.

### Actual result (*)

1. Empty cells where multiple lines are used, like Purchase Point, Shipping address etc.

Console log error screenshot
![image](https://user-images.githubusercontent.com/4670666/57839793-a449ad80-77c7-11e9-83cd-6524b3525113.png)

Sales Order loaded page after CTRL + F5.
![image](https://user-images.githubusercontent.com/4670666/57839835-bc213180-77c7-11e9-9c10-3999ea114952.png)

**Comment by maurixxxx** [comment]
Hi did you ran the php bin/magento setup:static-content:deploy -f with the correct language option? i had the same issue and i solved it running again content:deploy in it_IT in my case.

**Comment by ghost** [comment]
Hi @pietervanuhm thank you for you report, i'm not able to reproduce following steps you described, seems like this related to your configuration, feel free to reopen this one if issue still exists.

**Comment by IvanVizcaino** [comment]
Hello, I have the same problem in Magento 2.4.4 in other component. I resolve the problem modifying the 'ui/grid/cells/html' for 'ui/grid/cells/text'  and modify the component to return a string.

**Comment by kestraly** [comment]
@IvanVizcaino - Old thread but maybe useful to someone

If you JS file uses the following in define, **uiElement**

`define(['uiElement'], function (Column) {`

change to **Magento_Ui/js/grid/columns/column**

`define(['Magento_Ui/js/grid/columns/column'], function (Column) {`

This will allow for **_bodyTmpl: 'ui/grid/cells/html_'** on admin grids again
