### ISSUE TITLE
Special Price cannot be removed for single website

### ISSUE THREAD

**Issue by psuthar12** [magento/magento2#22913]
Preconditions
1.Magento 2.3.0 Or Magento 2.2.8 CE with Sample data  

Steps to reproduce

1. Setup multiple websites.
2. Open any product in admin panel assign it to all websites and set special price for it
3. Now edit product for any one website and remove special price for that.

Expected result

- Special price for the product should be removed for that particular website.

Actual result

- It is set to "use default value" instead of removing special price.

**Comment by AlexWorking** [comment]
Hello @psuthar12. We have not been able to reproduce Your Issue. Could You please try to reproduce it on a clear instance of Magento as You are asked above:
![Screenshot_1](https://user-images.githubusercontent.com/27814011/57851368-9a12b980-779d-11e9-9838-6e2783291dee.png)
Thank You.

**Comment by psuthar12** [comment]
@AlexWorking  Yes it is reproducing on vanilla Magento instance. Follow below steps

1. Add Multiple Websites.
2. Edit any product,  assign it to all websites, add special price and save.
3. Now edit that product again and switch to any particular website.
4. Now remove the special price from advanced pricing pop up (un check the use default value and empty the special price field and save).

Expected result

- Special price for the product should be removed for that particular website.

Actual result

- It is set to "use default value" instead of removing special price.

**Comment by AlexWorking** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking, here is your [Magento instance](https://i-22913-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22913-2-3-develop.instances.magento-community.engineering/admin](https://i-22913-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AlexWorking** [comment]
@psuthar12, we are still not able to reproduce the issue. Please watch the attached video and tell us where we go astray from Your way of reproduction. Thank You.
![SpPr](https://user-images.githubusercontent.com/27814011/57927520-7cac2100-786b-11e9-924f-1f3ab9b79a49.gif)

**Comment by AlexWorking** [comment]
@psuthar12, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by harleeniweb** [comment]
Hi

This is still an issue in 2.4.6 , can you provide me vanilla instance @AlexWorking
