### ISSUE TITLE
On Magento2.2.8 adding images in product attribute in WUSIWUG sot showing image in frontend.

### ISSUE THREAD

**Issue by saiky** [magento/magento2#22918]
Hi, 

Working with Magento2.2.8 we added product attribute with WUSIWUG editor in admin 
image is showing perfect with admin url. 

But, in product detail page its not showing image seems like media is not rendering
please check below code, the media url is not changing to dynamic url as its doing in admin.

`<div class="col-md-4 custom-accordion__col"><img src="{{media url=" wysiwyg="" u4888.png"}}"="" width="400" height="400"></div>`

Your help is highly appreciable. 

Thanks,
Saikat

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22918-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22918-2-2-develop.instances.magento-community.engineering/admin](https://i-22918-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22918-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22918-2-3-develop.instances.magento-community.engineering/admin](https://i-22918-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hi @saiky,  please update issue description as per magento 2 issue reporting guideline .
you can refer link : https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by saiky** [comment]
Hi @shikhamis11 ,

To reproduce this issue simply follow below steps:
1. In the product attribute add a text area attribute.
2. After adding it In the Storefront properties Enable WYSIWYG 
3. Now add a product with this attribute and put a image in this field.
4. In admin you find the image is displaying with admin url.
5. While in front-end the image is broken and appear as i mention in the code:
`<img src="{{media url=" wysiwyg="" u4888.png"}}"="" width="400" height="400">`

So, it seems rich text editor's images aren't rendering in front-end.

**Comment by saiky** [comment]
Hi @shikhamis11 ,

I get the solution for this by doing following:

` 
$_helper = $this->helper('Magento\Catalog\Helper\Output');

<?= $_helper->productAttribute($_product, $product->getData('attribute_name'), 'attribute_name') ?>`

Thank you.
