### ISSUE TITLE
Store view label not in the middle of panel

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#22924]
### Preconditions (*)

1. Magento 2.3 - Develop
1. Magento 2.2- Develop

### Steps to reproduce (*)

1. Login to admin panel
2. Content -> Design -> Configuration -> Edit any theme

### Expected result (*)

![expected](https://user-images.githubusercontent.com/33230237/57907301-a7619e00-789a-11e9-8586-327842a74e57.png)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/33230237/57907313-b0526f80-789a-11e9-90f0-f385276f9943.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22924-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22924-2-3-develop.instances.magento-community.engineering/admin](https://i-22924-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22924-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22924-2-2-develop.instances.magento-community.engineering/admin](https://i-22924-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99728`, `MAGETWO-99729` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @speedy008, @dipti2jcommerce, @speedy008. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.
