### ISSUE TITLE
404 Not Found css folder

### ISSUE THREAD

**Issue by kamranbhutto** [magento/magento2#22923]
### Summary (*)

ver 2.3.1

-Added March 26, 2019

### Examples (*)

pub/static/frontend/Magento/luma/en_US/mage/calendar.css
404 Not Found

**Comment by shikhamis11** [comment]
hello @kamranbhutto , did you try running upgrade and deploy commands ?

**Comment by kamranbhutto** [comment]
> 
> 
> hello @kamranbhutto , did you try running upgrade and deploy commands ?

deploy

**Comment by shikhamis11** [comment]
I am not able to reproduce this issue on magento 2.3.1 instance.Please share more details about the issue . also please check the same on 2.3-develop instnace If you find issue Please share screenshot also

**Comment by shikhamis11** [comment]
@kamranbhutto I am closing this issue since this is not reproducible . Please share more details about the issue if you think it still exits, also please check the same on 2.3-develop instance If you find issue Please also share screenshot
