### ISSUE TITLE
Catalog Product Gallery Processor: Add Image not working if move true

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#22929]
### Preconditions (*)

1. Magento 2.2.8 and 2.3.1 CE

### Steps to reproduce (*)

1. Write custom module where you have an image place in any folder and you are using \Magento\Catalog\Model\Product\Gallery\Processor to link image in the product.
2. Use addImage($product, $newFileName, $imageType, true, $disabled); with move true in 4th param.

### Expected result (*)

1. It should add an image to product

### Actual result (*)

1. If move true then on this line: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Product/Gallery/Processor.php#L180: check will pass and it will move the image to the media folder.
2. on line https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Product/Gallery/Processor.php#L201, it's again trying to read MimeType of the file on the old path. 
3. it will throw error file does not exist.

**Comment by ankursachdeva11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ankursachdeva11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ankursachdeva11, here is your [Magento instance](https://i-22929-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22929-2-3-develop.instances.magento-community.engineering/admin](https://i-22929-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
