### ISSUE TITLE
Grand Total excluding Tax

### ISSUE THREAD

**Issue by matthiashamacher** [magento/magento2#22925]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Create two websites
2. Make the following settings for the first Website:
    - Calculation Settings:
        - Catalog Prices: Including Tax
        - Shipping Prices: Including Tax
    - Price Display Setting:
        - Display Product Prices In Catalog: Including Tax
        - Display Shipping Prices: Including Tax
    - Shopping Cart Display Settings:
        - Display Prices: Including Tax
        - Display Subtotal: Including Tax
        - Display Shipping Amount: Including Tax
        - Include Tax In Order Total: No
        - Display Full Tax Summary: Yes
3. Make the following settings for the second Website:
    - Calculation Settings:
        - Catalog Prices: Excluding Tax
        - Shipping Prices: Excluding Tax
    - Price Display Setting:
        - Display Product Prices In Catalog: Excluding Tax
        - Display Shipping Prices: Excluding Tax
    - Shopping Cart Display Settings:
        - Display Prices: Excluding Tax
        - Display Subtotal: Excluding Tax
        - Display Shipping Amount: Excluding Tax
        - Include Tax In Order Total: No
        - Display Full Tax Summary: No
4. Add a product to cart and go to the checkout

### Expected result (*)
Website 1 (including Tax):
The grand total is the same amount as the subtotal (plus eventually shipping costs)

Website 2 (excluding Tax):
The grand total is the same amount as the subtotal (plus eventually shipping costs)

### Actual result (*)
Website 1 (including Tax):
Here everything is ok.
![image](https://user-images.githubusercontent.com/32356549/57907148-c5b8a100-787c-11e9-9286-2a6b8ed1f0f7.png)

Website 2 (excluding Tax):
There is a difference between the subtotal and the grand total. This difference is the tax amount.
![image](https://user-images.githubusercontent.com/32356549/57907206-f567a900-787c-11e9-9e7d-bd7a1a07aae2.png)

Because we have an extra theme for the second website I could temporarily fix this by using getGrandTotalExclTax() in this template https://github.com/magento/magento2/blob/211dd25c73bb2539c3c064374d9d5649f253fd14/app/code/Magento/Tax/view/frontend/web/template/checkout/summary/grand-total.html#L31

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22925-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22925-2-3-develop.instances.magento-community.engineering/admin](https://i-22925-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@magento-engcom-team - Can you please provide me multistore Magento 2.3-develop and 2.2-develop Instance?

**Comment by AlexWorking** [comment]
Hello @matthiashamacher. Thank You for applying. The current magento's behavior looks to be pretty correct. If You want to equalize Your subtotal with Your total please try to set Your Display Subtotal in Shopping Cart Display Settings to Including Tax instead of Excluding.

**Comment by deepakk-webkul** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar, here is your [Magento instance](https://i-22925-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22925-2-3-develop.instances.magento-community.engineering/admin](https://i-22925-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by matthiashamacher** [comment]
@AlexWorking 
So, which meaning have the "Include Tax In Order Total" setting then?
My goal is that the grand total is shown without tax. So in my second screenshot, "Bestellsumme" should be "1205,00 €".
Because the total should be shown without tax, including the tax in the subtotal doesn't solve the problem.

**Comment by AlexWorking** [comment]
Yes @matthiashamacher, precisely - for Your case You need something like "Include Tax In Order Total" setting. But there is no such setting because Grand Total as You called it Yourself in the issue's title cannot exclude anything, not the tax ether. If it were able to it couldn't be called "Grand". Grand Total must always be the end amount the customer has to, so ta say, take out of his or her pocket and put on the merchant's table. It is only possible for subtotal to not contain everything.  So the only case the Grand Total will not include tax is when the order's condition do not trigger any of the tax rules set at Your web store.

**Comment by matthiashamacher** [comment]
@AlexWorking 
Thanks. I rechecked the tax rules settings and tax classes. With setting the "Tax Class for Shipping" to None and the tax class of the product to none for the website, the right grand total (without tax) is shown.
