### ISSUE TITLE
Multistore restrict user to a specific store

### ISSUE THREAD

**Issue by Lumiahna** [magento/magento2#22935]
### Preconditions (*)
Env: debian 9 / apache2/mariadb/php 7.1

### Expected result (*)
On multistore mode, I would like to restrict an user / store and avoid them to get access to the others ones.
### Actual result (*)
I don't see any ACL permissions to check ..

**Comment by AlexWorking** [comment]
Hello @Lumiahna. Thanks for applying. In fact, the feature Your are talking about is present in Magento but only in its Enterprise Edition versions. Please have a look
Community Edition Version:
![CE](https://user-images.githubusercontent.com/27814011/57979130-52c33d80-79d6-11e9-9ddb-778d869abee8.png)
Enterprise Edition Version:
![EE](https://user-images.githubusercontent.com/27814011/57979136-6f5f7580-79d6-11e9-857b-3accb0b43bb7.png)
