### ISSUE TITLE
Incorrect work of "Use Categories Path for Product URLs" in sitemap generation.

### ISSUE THREAD

**Issue by AlexWorking** [magento/magento2#22934]
Related issue: #4788

### Preconditions (*)

1. Magento version 2.3-develop version clear install.

### Steps to reproduce (*)

1. Create category “categ”.
2. Create Product “simp” and assign it to categ.
3. Generate sitemap. URLs like http(s)://your-magento-instance/categ.html  and http(s)://your-magento-instance/simp.htm are present.
4. Now set to Yes "Use Categories Path for Product URLs"  in configuration -> catalog -> catalog -> Search Engine Optimization.
5. Generate sitemap.

### Expected result (*)

1 Another URL has appeared:  http(s)://your-magento-instance/categ/simp.html.

### Actual result (*)

http(s)://your-magento-instance/categ/simp.html has not appeared.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99740` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sergiy-v** [comment]
#23129 
@AlexWorking do you have any updates for the issue after [discussions with Valerii](https://github.com/magento/magento2/issues/4788#issuecomment-496940717)?
Thank you.

**Comment by AlexWorking** [comment]
Hi, @sergiy-v. No we haven't had any discussion yet.

**Comment by sergiy-v** [comment]
> Hi, @sergiy-v. No we haven't had any discussion yet.

oh, thank you for reply. Please add an update here in case of any.

**Comment by AlexWorking** [comment]
@sergiy-v, 👌

**Comment by sergiy-v** [comment]
@AlexWorking please check related [comment](https://github.com/magento/magento2/pull/23129#issuecomment-500464060).
Thank you.

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking, @sergiy-v. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.
