### ISSUE TITLE
Products size images are not generating in cache directory 

### ISSUE THREAD

**Issue by mavajih** [magento/magento2#22938]
Products page image are not generating when render page and not pregenerated. I need to run "php bin/magento catalog:images:resize" everytime in magento root. 
Issue in generating size images in pub/media/catalog/product/cache/ and i think permission is not an issue since image is showing on category page after product page opens. Please suggest the way with we can automate size image generation in cache directory.

### Preconditions (*)
1. Magento Community 2.3.1
2. PHP 7.2.17
3. Mysql Server version: 5.7.26
4. Nginx on ubuntu 18.04.1
5. chmod -R 777 pub/

### Steps to reproduce (*)

1. Upload product with image via csv import with attached format
[test_product_import.xlsx](https://github.com/magento/magento2/files/3194087/test_product_import.xlsx)

2. Indexing and php bin/magento cache:clean && php bin/magento cache:flush
3. Open category page, image not showing on category page, open product page - image not showing on product page, again open category page, now image is showing on category page but not on product page.

### Expected result (*)

1. Product image should show on category page, product page etc.

### Actual result (*)

1. Open category page, Product image is not showing on category page, 
2. Now open product page, image not showing on product page.
3. Now again open category page, image is showing now.
4. Now again open product page, image still not showing.

Note: There is showing call for image in developer console of product page. but with 404 not found
https://mydomain.com/pub/media/catalog/product/cache/a32785f299d1d6627cb18126779d91a2/4/_/4_sxo7pef-thumbnail-700x980-100.jpg  - not found

**Comment by benjamin-volle** [comment]
Hi,

There are comments here that seems related : https://github.com/magento/magento2/issues/19710#issuecomment-478573879

**Comment by eliademoga** [comment]
Hi,
we have exactly the same problem after a recent upgrade from Magento 2.2.5 to Magento 2.3.1.
After any .csv import we see the images in the back-end, but no resized image is created in the cache/ folder. We even saved the products again after the import, but again with no success.
Fortunately "php bin/magento catalog:images:resize" does the job, but running that for over 9000 images every time we import a product or two is too much overhead.

Our coordinates are:

- Magento 2.3.1
- PHP 7.1.28
- MariaDB 10.1.35
- Nginx 1.12.1
- pub/ writable

Is there any other way to resize images for just a certain list of products? Or for certain filenames?

**Comment by mavajih** [comment]
Hi @magento-engcom-team around 15000 images took 3 hours to generate size images in cache directory  via "php bin/magento catalog:images:resize" Please suggest solution so that we can pre - generate images of selected products (new listed) or it auto generates when page render.

**Comment by harperruss** [comment]
Same thing here with 2.3.1....

**Comment by soleksii** [comment]
Hi @mavajih , thank you for you report, i'm closing this as duplicate to this -> #19710
