### ISSUE TITLE
Product custom options date saved less then select date while add to cart

### ISSUE THREAD

**Issue by ghost** [magento/magento2#22939]
I have just set the time zone from admin configuration.
Time Zone: Gulf Standard Time (Asia/Muscat) Time Zone Configuration
I have a product which has an option for the delivery date and once I am selecting any date and trying to add to cart at that time always 1 date is minus from selected date and save value is always less than one from a selected date see video for more information Issue Video

This issue faced while we have select Gulf Standard Time (Asia/Muscat) Time zone from admin or any other timezone 
### Preconditions (*)
1. Magento Community 2.2.2 
2. PHP 7.1.20-1
3. Ubuntu 16.04.6 LTS
4. Apache2

### Steps to reproduce (*)
1. Create any simple product with custom option and option type must be date e.g Delivery Date 
2. Change Time Zone From Configuration. E.g Gulf Standard Time (Asia/Muscat) Time zone 
3. Catalog configuration In Date & Time Custom Options Use JavaScript Calendar enable it.
4. Set date format for options : dd/mm/YYYY 
5. https://prnt.sc/nqh6z7 see configuration 
5.  On Front end go to product page and select any date from custom product option and try to add to cart and check on cart page you can see one less then selected date is saved in option see this video for more understanding https://www.loom.com/share/df64a448caf445f0a17cf8f49c559f87 

### Expected result (*)
1.  product must be add to cart with correct selected date and on cart page must be show correct selected date.

### Actual result (*)
1.  while we select any date in product option on product page and after add to cart date is less than one always...

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22939-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22939-2-3-develop.instances.magento-community.engineering/admin](https://i-22939-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22939-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22939-2-2-develop.instances.magento-community.engineering/admin](https://i-22939-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @navinbhudiya. 
I'm not able to reproduce this issue in clean magento instance.
Please provide additional steps for this issue.
Also could you please try to reproduce it on a clean instance of Magento as you described above
![test1](https://user-images.githubusercontent.com/46617848/57979072-0871a900-7a36-11e9-9736-83c7d233f9f0.png)
Thank You.

**Comment by ghost** [comment]
@magento-engcom-team i just re generate issue. see
https://www.loom.com/share/630dccbe928842e18b1cc0fb6d8f853e

sorry i just forgot 2 things also need to seet this configuration then bug regenerated
1) Catalog configuration  In Date & Time Custom Options **Use JavaScript Calendar** enable it.
2) Set date format for options : dd/mm/YYYY

![download](https://user-images.githubusercontent.com/22772614/57980267-ad947d80-7a46-11e9-99a4-56c88d858c0c.png)

**Comment by ghost** [comment]
@magento-engcom-team information updated please check

**Comment by ghost** [comment]
@krishprakash i just regenerate bug please check

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99762`, `MAGETWO-99763` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento-engcom-team  i had fixed issue in local allready so please assign me i will commit code and create pull request

**Comment by krishprakash** [comment]
Assigned.
@navinbhudiya further you can assign your self in the issue.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @navinbhudiya. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @navinbhudiya, here is your [Magento instance](https://i-22939-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22939-2-3-develop.instances.magento-community.engineering/admin](https://i-22939-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento-engcom-team @m2-assistant i have Reproduced on 2.3.x issue on https://i-22939-2-3-develop.instances.magento-community.engineering/ please check

**Comment by ghost** [comment]
here module available for fixed issue https://github.com/navinbhudiya/bug-fix-product-options-date-saved-less

**Comment by magento-engcom-team** [comment]
Hi @navinbhudiya. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24406` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
