### ISSUE TITLE
Locked out of Admin.

### ISSUE THREAD

**Issue by rifraff63** [magento/magento2#22945]
I had super admin rights and was attempting to give my developer the same. Now he nor I have any rights. How can I get back into my site as a super user? I can still get into the admin section with another log in, but it doesn't have all of the rights. HELP!!!

**Comment by rifraff63** [comment]
I'm using Magento 2
Could not reproduce once locked out
Would like to know how to have my rights back

**Comment by VasylShvorak** [comment]
Hi @rifraff63 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
