### ISSUE TITLE
Autorize.net Payment not loading checkout

### ISSUE THREAD

**Issue by lucasvm** [magento/magento2#22954]
### Preconditions (*)
At this moment we are unable to get this working on a Magento 2.3.1 site

### Steps to reproduce (*)
Upgraded from 2.3.0 to 2.3.1 to use Autorize.net

### Expected result (*)

1. We should be able to accept the payment and go to next step
2.

### Actual result (*)

1. Javascript error
TypeError: a.authData.clientKey is null[Conocer más] AcceptCore.js:1:389
    b https://js.authorize.net/v1/AcceptCore.js:1
    dispatchData https://js.authorize.net/v1/AcceptCore.js:1
    _createTokens https://site.com/pub/static/version1557932525/frontend/theme/en_US/Magento_AuthorizenetAcceptjs/js/view/payment/acceptjs-client.js:59
    createTokens https://site.com/pub/static/version1557932525/frontend/theme/en_US/Magento_AuthorizenetAcceptjs/js/view/payment/acceptjs-client.js:45
    <anonymous> self-hosted:974
    jQuery 3
    <anonymous> https://site.com/pub/static/version1557932525/frontend/theme/en_US/Magento_AuthorizenetAcceptjs/js/view/payment/acceptjs-factory.js:29
    jQuery 2
    v https://js.authorize.net/v1/AcceptCore.js:1
    w https://js.authorize.net/v1/AcceptCore.js:1
    <anonymous> https://js.authorize.net/v1/AcceptCore.js:1
    <anonymous> https://js.authorize.net/v1/AcceptCore.js:1

**Comment by engcom-Delta** [comment]
Hi @lucasvm thank you for your report. Unfortunatelly,  I'm not able to reproduce issue by steps you described on clean 2.3-develop. 
And I cannot reproduce issue by upgrading from 2.3.0 to 2.3.2(latest release version )
If you'd like to update the issue, please reopen it.
