### ISSUE TITLE
after data migration admin goes to 404

### ISSUE THREAD

**Issue by gtrocks** [magento/magento2#22957]
### Preconditions (*)

1.i have installed magento 2.3.1 and migrated data from magento 1.9.1.1 to magento 2.3.1
2.

### Steps to reproduce (*)

1. after migrating multi-store site admin goes to 404
2.

### Expected result (*)

1 . able to see admin page and login to admin

### Actual result (*)

1. 404 page on admin
http://ashianadev.co.uk/admin_kksk2233 , please check and help me to resolve this issue

**Comment by gtrocks** [comment]
Hi @magento-engcom-team ,

Updated issue correctly

**Comment by AlexWorking** [comment]
Hello @gtrocks, thanks for applying. There could be several reasons for admin page going 404. And they are noty technical issues. Probably here You can find the answer to Your problem: https://magento.stackexchange.com/questions/133679/404-not-found-error-for-admin-page. If You still do not obtain the answer then it's probably some techncal issue. But if that's the case please reopen Your issue on a correct repository: https://github.com/magento/data-migration-tool repository.
