### ISSUE TITLE
Error after upgrade to 2.3.1 from 2.2.5

### ISSUE THREAD

**Issue by xnhinzkyx** [magento/magento2#22960]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

Frontend:
1. Login to account with previous orders.

Backend:
1. Login admin account and go to Customers->All Customers
2. Click customer account and go to Orders tab.

### Expected result (*)

Frontend:
1. Shows customer details like orders, address, etc.

Backend:
1. Shows customer details and orders.

### Actual result (*)

1. Throws an error: 

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Framework\DataObject::__construct() must be of the type array, string given, called in /home/site/www/vendor/magento/module-sales/Model/Order/Item.php on line 666 and defined in /home/site/www/vendor/magento/framework/DataObject.php:39 Stack trace: #0 /home/site/www/vendor/magento/module-sales/Model/Order/Item.php(666): Magento\Framework\DataObject->__construct('a:4:{s:4:"uenc"...') #1 /home/site/www/generated/code/Magento/Sales/Model/Order/Item/Interceptor.php(362): Magento\Sales\Model\Order\Item->getBuyRequest() #2 /home/site/www/vendor/magento/module-sales/Model/Order/ProductOption.php(63): Magento\Sales\Model\Order\Item\Interceptor->getBuyRequest() #3 /home/site/www/vendor/magento/module-sales/Model/Order/ItemRepository.php(130): Magento\Sales\Model\Order\ProductOption->add(Object(Magento\Sales\Model\Order\Item\Interceptor)) #4 /home/site/www/vendor/magento/module-sales/Model/Order.php(2118): Magento\Sales\Mo in /home/site/www/vendor/magento/framework/DataObject.php on line 39

![Screen Shot 2019-05-21 at 5 51 07 PM copy](https://user-images.githubusercontent.com/2484559/58087458-29332d80-7bf3-11e9-9563-92697425cc5f.png)
![Screen-Shot-2019-05-21-at-5 53 42-PM](https://user-images.githubusercontent.com/2484559/58087473-32bc9580-7bf3-11e9-9b9f-6ef40a624732.jpg)

**Comment by AndyJAllen** [comment]
I am also experiencing this after upgrading from 2.2.6 to 2.3.1. Same exact error doing the same steps. Just clicking to view/edit an existing order results in the error pointed out by the op. I also cant view invoices, shipments, or credit memos.

**Comment by AndyJAllen** [comment]
No one knows anything about this?

**Comment by AndyJAllen** [comment]
I got this problem solved by applying a coding change all the way back from a post in August of 2016:
https://github.com/magento/magento2/issues/4801

**Comment by AndyJAllen** [comment]
A little more information here. 

When overriding vendor/magento/module-sales/Model/Order/Item.php
with function:

```
class Item extends \Magento\Sales\Model\Order\Item{
	protected function _construct() {
        parent::_construct();
    }
	public function getProductOptions()
    {
        $data = $this->_getData('product_options');
        if (is_string($data['info_buyRequest'])) {
            $data['info_buyRequest'] =  unserialize($data['info_buyRequest']);
        }
        return $data;
    }
}
```

It will fix the problem indicated here however I am now suspecting this implementation of causing new problem here https://github.com/magento/magento2/issues/23384

**Comment by engcom-Charlie** [comment]
Hello @xnhinzkyx , @AndyJAllen ! Thank you for your reports !
I`ve tried to reproduce it on Magento 2.3-dev and 2.3.1 and seems like its not reproducible . Can you provide more steps how to reproduce it and update this ticket ?

![Screenshot from 2019-07-03 12-48-59](https://user-images.githubusercontent.com/51680850/60582532-ae346980-9d91-11e9-9cc2-69b946521a1c.png)

**Comment by AndyJAllen** [comment]
> 
> 
> Hello @xnhinzkyx , @AndyJAllen ! Thank you for your reports !
> I`ve tried to reproduce it on Magento 2.3-dev and 2.3.1 and seems like its not reproducible . Can you provide more steps how to reproduce it and update this ticket ?
> 
> ![Screenshot from 2019-07-03 12-48-59](https://user-images.githubusercontent.com/51680850/60582532-ae346980-9d91-11e9-9cc2-69b946521a1c.png)

Hi @engcom-Charlie ,

The order listing you show a screenshot of will not show the error we are pointing out...You would have to view the order details or view the orders from the customer record. In the screenshot shown by xnhinzkyx he is looking at the orders tab from a customer record.

Some other info; 100% of all the products in my environment are configurable products....it could be related to that configuration. The error indicates something at the item level....and the temp solution I posted manipulates code that pertains to the product options.

-Andy

**Comment by engcom-Charlie** [comment]
@xnhinzkyx i can`t reproduce this issue . Feel free to reopen it in case you can provide more steps to reproduce this issue .

![Screenshot from 2019-07-10 14-08-03](https://user-images.githubusercontent.com/51680850/60964827-05e84d00-a31d-11e9-8bc7-1aa11d5ee48b.png)

**Comment by AndyJAllen** [comment]
@xnhinzkyx did you ever find the solution to this issue without impacting order creation in admin or affecting the ability to add configurable products with swatches to your cart? do you use a modified version of Serializer/Json.php?
