### ISSUE TITLE
Listing page _ sort by text is getting crop

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#22969]
### Preconditions
1. Magento 2.3 with sample data installed
2. Open site in mobile view(320*568) 
2. The listing page should be opened.

### Steps to reproduce
1. Go to home page -> Navigate to the listing page 
2. Review shop by drop down and sort by text 

### Expected result
Sort by text should not crop in between dropdowns
### Actual result
Should have some space between shop by & sort by drop down, adjust sort by text in a smaller device. 

![image](https://user-images.githubusercontent.com/47663332/58152680-c0978f80-7c8a-11e9-99c1-d486acbff41e.png)

**Comment by williankeller** [comment]
Hi @GrishmaNayee,
Thanks for your request, we already have this issue tracked and fixed.
Issue: https://github.com/magento/magento2/issues/20124.
Pull request: https://github.com/magento/magento2/pull/20135.
Commit: https://github.com/magento/magento2/commit/11af87753f43c38d95c373a046ed9490cc2f88e3

I am closing this one and you can track the updates on the above-mentioned issue links.
