### ISSUE TITLE
While adding product to cart as guest user same form key displaying for two different sessions. 

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#22962]
### Preconditions
1. Magento CE 2.2.2 with sample data installed
2. Cache enabled 

### Steps to reproduce
1.Navigate to the product detail page in the browser 
2. Check the form key.
3. Open the same page on the incognito window and verify the form key.

### Expected result
1. Form_key should be different for different sessions.
### Actual result
1. Displaying the same form key for two different guest sessions

**Comment by ktpl-rammohan** [comment]
Hello @AlexWorking, why I am unassigned may I know the reason, please

**Comment by AlexWorking** [comment]
Hello, @rammohan-krish. Would You please answer me first (please look a bit above:
![assign](https://user-images.githubusercontent.com/27814011/58097599-7954c480-7be0-11e9-9da4-ba830993000b.png)) Tank You.

**Comment by ktpl-rammohan** [comment]
@AlexWorking oops, My mistake seems like a difference in milliseconds time while assigning.
I didn't see your name while assigning it to my self.
Anyway, you can go head with issue verification.
**ALL THE BEST**

**Comment by AlexWorking** [comment]
@rammohan-krish That's Ok. Thank You for understanding.

**Comment by AlexWorking** [comment]
Hello @GrishmaNayee. Thanks for reporting. Currently we've been not able to reproduce Your issue on 2.3-develop version. Could You please try do it by Yourself as You are advised to
![Advised](https://user-images.githubusercontent.com/27814011/58099291-051c2000-7be4-11e9-81de-d3f2ca47fc57.png)
Thank You.

**Comment by GrishmaNayee** [comment]
It's reproducing in 2.2 and 2.3 instances.

**Comment by ktpl-rammohan** [comment]
Hello @GrishmaNayee , investigated on this issue, it is a valid issue but it is duplicate of #13746.
for your reference please verify the following link:
https://github.com/magento/magento2/issues/13746.
I am closing this issue, you can track the updates on the above-mentioned issue link.
