### ISSUE TITLE
Admin Menu doesn't slide out and configuration menue doesnt open

### ISSUE THREAD

**Issue by farhangithub27** [magento/magento2#22967]
### Preconditions (*)

1.Magento 2.3.1
2.Ubuntu 18.04.2 LTS
3. PHP 7.2.17

Working in dev environment and and enabled few optimization parameters which made admin panel inaccessible and buttons were don't appear correct with proper text , appears shrinked.
Admin panels don't draw out even if does then none of the buttons registers a click and hence I'm not able to change the configurations back.

### Steps to reproduce (*)

I was trying to speed up my webstore but it created a havoc.
1. Enable JS minify/merge/bundling
2. Enable CSS minify/merging
3. Enable Html minify
4.Enable Embedded Translation Mode for JS translation strategy.

### Expected result (*)

1. Proper Functioning
2.

### Actual result (*)

1. Screenshot of open basket
![Screenshot from 2019-05-22 13-48-00](https://user-images.githubusercontent.com/22092017/58146166-4bcb5200-7c98-11e9-869f-7f39830714b7.png)

2. Can provide admin and its related to clicking and menu opening.

**Comment by farhangithub27** [comment]
Hi, I have found problem. Change Embedded JS translation strategy to Dictionary. AS upon inspection I was getting alot of i18n related js error in browser.

However this bug should be solved.

**Comment by VasylShvorak** [comment]
Hi @farhangithub27 thank you for you report, i'm not able to reproduce issue by steps you described on clean 2.3-develop .
