### ISSUE TITLE
Detail page_When the 'More Information' tab is open, the screen focus is not displayed properly.

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#22961]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Open Default Magento Front end in Mobile view.
2. Select Women Category > Jackets Subcategory.
3. Click on any product > Open the details page.
4. Click on details tab > Open the description content properly.
5. Click on More Information tab > Application focus is not displayed in a proper position.

### Expected result (*)

 Application focus should be displayed on the More Information tab.

### Actual result (*)

The application focus is displayed footer of the screen.

[DetailsPage_Issue_MP4.zip](https://github.com/magento/magento2/files/3202401/DetailsPage_Issue_MP4.zip)

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22961-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22961-2-3-develop.instances.magento-community.engineering/admin](https://i-22961-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-22961-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22961-2-2-develop.instances.magento-community.engineering/admin](https://i-22961-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by ajijshekh123** [comment]
@GrishmaNayee  I have verified this issue Magento 2.2 and 2.3 instances in mobile view but I haven't found this issue. If you found this issue in specific device please let me know.
This issue is not reproduced.

**Comment by ajijshekh123** [comment]
@GrishmaNayee fell free to reopen this issue when you will be ready to provide more details and we will review it and confirm
