### ISSUE TITLE
Unable to save any dates if the user interface locale is not english (US) in 2.3.1

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#22964]
### Preconditions (*)
1. Magento 2.3.1
2. A user with interface locale set to Greek

### Steps to reproduce (*)
1. Create a product using the user that has interface locale set to Greek. 
2. Add any date value, news_from_date, news_to_date, special_price_from_date, special_price_to_date
3. Save the product

### Expected result (*)
1. The product is saved correctly with the new date.

### Actual result (*)
1. Error that says invalid date Invalid input datetime format of value '22/5/2019'

![image](https://user-images.githubusercontent.com/20220341/58126184-04eb4700-7c1b-11e9-85af-71378bb81516.png)

I've found other references in other issues that are closed saying this problem was fixed but unfortunately I'm on 2.3.1 and the issue persists. There's no real solution or workaround yet for this. Apparently it's not just Greek locale but other locales as well. 

The bug has been acknowledged in the past, added to backlog even but years later we still face the same issue from version 2.1 to 2.3.1

Unless Magento is operating in a country where the users speak english natively it's pretty much pointless to use Magento if this is not fixed. I opened a new issue for this because any messages in closed issues get burried and never watched upon. 

I'm hoping someone who understands the inner workings of this date format validation will pay attention to this or else the biggest question we'll have to ask any potential customer before choosing a platform will pretty much be: "Are you fluent in English?" 

PS: at least if you could provide an official way to workaround this or what to change until it's fixed it would be completely fine so we can at least use the platform.

**Comment by ioweb-gr** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr, here is your [Magento instance](https://i-22964-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22964-2-3-develop.instances.magento-community.engineering/admin](https://i-22964-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ioweb-gr** [comment]
Reproduced on demo instance. 

![image](https://user-images.githubusercontent.com/20220341/58126820-8f807600-7c1c-11e9-864a-733baa231346.png)

**Comment by orlangur** [comment]
@ioweb-gr it's better to search for closed issues and reopen them to track regressions better.

https://github.com/magento/magento2/issues/9743 seems one of those, is it reproducible again? Is this issue introduced by 2.3.1 and not present in 2.3.0?

**Comment by ioweb-gr** [comment]
@orlangur For me it was never fixed in the first place. I can't seem to be able to track this issue that made me open a new one now, but it was a closed ticket with a few replies spaning over a year that the issue still persists. 

I mean if noone reopened that ticket after a year or so, I kinda gave up on reopening closed issues.
Also I've tried to comment on a newer one #13112 which was for 2.2 version but it seems it was ignored as well for quite some time (from Jan 18). 

It seems closed issues and old issues are never paid any attention to. You're right that it helps if it's reopened and worked on again, but it doesn't help if no one sees it.

**Comment by orlangur** [comment]
> It seems closed issues and old issues are never paid any attention to

@ioweb-gr well, it is simply impossible, unless anybody finds such issue and reopens it or if we have a proper end-to-end functional test covering this scenario.

**Comment by ioweb-gr** [comment]
Only collaborators can reopen issues they closed though so it's out of out hands but one choice would be to mark the duplicates when found and reopen the originals I guess in such cases. 

I'm sure you agree that since we can't reopen them, and commenting on the closed is never read, our only option as users is to raise a new issue

**Comment by Nazar65** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Nazar65, here is your [Magento instance](https://i-22964-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22964-2-3-develop.instances.magento-community.engineering/admin](https://i-22964-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99821` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Nazar65** [comment]
https://github.com/magento/magento2/pull/18578/files related "PR" may be help to process on this issue.

**Comment by chohanbhagchand** [comment]
Please assign me this issue

**Comment by orlangur** [comment]
@chohanbhagchand, please note that it was assigned recently to @maheshWebkul721

**Comment by cavalier79** [comment]
Hello, there's any news about this issue? I'm facing the same problem when importing products

**Comment by brampta** [comment]
got a fix for now. in file vendor/magento/module-catalog/Controller/Adminhtml/Product/Initialization/Helper.php, function convertSpecialFromDateStringToObject().

Just comment out the line that says
`$productData['special_from_date'] = $this->getDateTimeFilter()->filter($productData['special_from_date']);`

and then it works.

------edit---------

Actually my fix only fixed the special from date. A better fix is in this file: vendor/magento/framework/Stdlib/DateTime/Timezone.php this function: appendTimeIfNeeded() change the line that says 
`$date .= " 0:00am";`
to
`$date .= " 00:00";`

with the original line PHP was throwing an error:

> DateTime::__construct(): Failed to parse time string (3/06/1977 0:00am) at position 14 (a): The timezone could not be found in the database

Which caused the try catch in vendor/magento/framework/Stdlib/DateTime/Filter/DateTime.php::filter() to fail. And causing this problem.

**Comment by ioweb-gr** [comment]
For me it didn't really work for either so  I guess the above workaround is only specific for your case unfortunately :(

**Comment by Wirson** [comment]
In Greek locale date format is dd/mm/yyyy. In English is mm/dd/yyyy.
Exactly [here](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php#L186) the new DateTime() is called.
Try new DateTime('25/06/2019'). Fatal error occurs, but with new DateTime('06/25/2019') works.

**Comment by ioweb-gr** [comment]
Sorry for bringing this up again, but I need to mention that this issue was raised about 2 months ago and I think it's going to get burried again like the original issues were 2+ years ago. It would be nice to know if there is at least a timeframe to fix this issue or an internal ticket number to track progress as it is a critical issue for non-English speaking users. Could someone let us know at least what the status is?

**Comment by mrtuvn** [comment]
got same issue with korean locale here
i have tested in 2.3.2 instance

**Comment by LucasCalazans** [comment]
I'm trying to get a solution to this issue.

#MM19BR

**Comment by ioweb-gr** [comment]
I'm hoping this issue will be given some attention again. Apparently this is a long standing thorn in Magento multilingual deployments.

**Comment by mahsn** [comment]
Reproduced in 2.3.3

**Comment by Jilco** [comment]
Yep, i have the same problem in 2.3.3

**Comment by sujitcp** [comment]
We have Fixed it and will commit soon

**Comment by folektoras** [comment]
@magento-engcom-team I created a pull request for this one here: https://github.com/magento/magento2/pull/25574. Let's hope that this is now fixed.

**Comment by marcoaacoliveira** [comment]
@ioweb-gr I'll work on it. 

My first thought about it was changing my interface to Brazil/Portuguese (because we use dd/mm/yyyy format too, hoping that I would face the same problem) for my surprise I could save it in portuguese. When I change it for Greek it really mess something around and I'm not able to save date. So it looks like more a problem with the locale then the date format.

I'll get a more deeply analysis and I'll try to solve it.

**Comment by ioweb-gr** [comment]
@marcoaacoliveira Thanks for taking a look at it first of all. This is such a long standing issue. If you track the original issues you'll see it goes back all the way to 2016 and it occured on Australian locale as well. 4 years later it would be nice to have a real fix or at least a working workaround on this. I've tried to debug this but you have to dig very deep to understand the logic and the proper fix

**Comment by marcoaacoliveira** [comment]
@ioweb-gr I got to the root of the problem, I'll try to solve it today and open a PR.

**Comment by marcoaacoliveira** [comment]
@ioweb-gr I solved it. I'll do some test coverage and I'll open the PR.

**Comment by marcoaacoliveira** [comment]
@ioweb-gr now it's really solved, covered with tests. You can check it requesting a instance for test in the PR if you want:
https://github.com/magento/magento2/pull/26270

**Comment by VladimirZaets** [comment]
Hi @ioweb-gr. Thank you for your report. 
The issue has been fixed in magento/magento2#26270 by @marcoaacoliveira in 2.4-develop branch
Related commit(s):
 - [bb16e33f41d14fac93ae93e56b051f485e0d53d2](https://github.com/magento/magento2/commit/bb16e33f41d14fac93ae93e56b051f485e0d53d2)
 - [d12ac2178592c7a999e14e04b98b6f319357a725](https://github.com/magento/magento2/commit/d12ac2178592c7a999e14e04b98b6f319357a725)
 - [32be47258b96b18f8f589635ff4bd22a6aeabe32](https://github.com/magento/magento2/commit/32be47258b96b18f8f589635ff4bd22a6aeabe32)
 - [6a19b1297a7f740ecb4cedcd4afbd6a42e70904a](https://github.com/magento/magento2/commit/6a19b1297a7f740ecb4cedcd4afbd6a42e70904a)
 - [6e80158edd564a14d2643798584d3f9331b4fff9](https://github.com/magento/magento2/commit/6e80158edd564a14d2643798584d3f9331b4fff9)
 - [8ee89af88ec90b3992fb26b305ec63d39c0f4b2e](https://github.com/magento/magento2/commit/8ee89af88ec90b3992fb26b305ec63d39c0f4b2e)
 - [c85410d14fc4db09d21ebbc37f880330a7094390](https://github.com/magento/magento2/commit/c85410d14fc4db09d21ebbc37f880330a7094390)

The fix will be available with the upcoming 2.4.0 release.
