### ISSUE TITLE
Magento_Backend modules search and filter in sales_order_create

### ISSUE THREAD

**Issue by VasylBudnik** [magento/magento2#22963]
### Preconditions (*)

1.Magento ver. 2.2.2 EE

### Steps to reproduce (*)

1. Replicate > Sales >Orders>Create New order>use filters to search for a customer

### Expected result (*)

1. Get filter list of customer

### Actual result (*)

1. Make filter and go next page

**Comment by VasylBudnik** [comment]
### Solution
1. In vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml
`
                                <button  title="<?= /* @escapeNotVerified */ __('Next page') ?>"
                                        class="action-next"
                                        onclick="<?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.setPage('<?= /* @escapeNotVerified */ ($_curPage + 1) ?>');return false;">
                                    <span><?= /* @escapeNotVerified */ __('Next page') ?></span>
                                </button>
`
add type of button

`
                                <button type="button" title="<?= /* @escapeNotVerified */ __('Next page') ?>"
                                        class="action-next"
                                        onclick="<?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.setPage('<?= /* @escapeNotVerified */ ($_curPage + 1) ?>');return false;">
                                    <span><?= /* @escapeNotVerified */ __('Next page') ?></span>
                                </button>
`
Maybe it's problem just in my magento, but you can check this.

**Comment by ktpl-rammohan** [comment]
The description is not clear to reproduce the issue, closing the issue for now.
