### ISSUE TITLE
Dynamically created inventory tables (MSI) break integration tests

### ISSUE THREAD

**Issue by Berdir** [magento/magento2#22979]
### Preconditions (*)

1. Magento 2.3.1
2.

### Steps to reproduce (*)

1. Running an integration test that accesses alternative stocks
2.

### Expected result (*)

1. Tests work.
2.

### Actual result (*)
 Zend_Db_Statement_Exception: SQLSTATE[HY000]: General error: 1412 Table definition has changed, please retry transaction, query was: SELECT `inventory_stock_2`.`quantity`, `inventory_stock_2`.`is_salable` FROM `inventory_stock_2` WHERE (sku = 'simple1')

When rerunning a test with disabled cleanup, then it works but it always fails on the first run after a new install.

Maybe I'm doing something wrong, but this seems like a pretty big conflict between how the MSI works and how integration tests work, which rely on being able to run everything in a transaction.

**Comment by Nazar65** [comment]
Hi @Berdir thank you for you report, please open issue here -> https://github.com/magento-engcom/msi/issues
