### ISSUE TITLE
After upgrade from 2.2.8 to 2.3 receiving "The stock item was unable to be saved. Please try again." error when saving the product in admin

### ISSUE THREAD

**Issue by archonkulis** [magento/magento2#22978]
### Preconditions (*)

1. Magento 2.3.1
2. php7.2

### Steps to reproduce (*)

1. You need to have existing products in 2.2.8 version
2. Upgrade to 2.3.1 version
3. Open product in admin, click on Save

### Expected result (*)

1. The product should save successfully

### Actual result (*)

1. It throws following error: "The stock item was unable to be saved. Please try again."

After some initial investigation, it ends up in `vendor/magento/module-inventory/Model/SourceItem/Command/Handler/SourceItemsSaveHandler.php` file in `execute()` functions `catch` block with following error:

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (inventory_source_item`, CONSTRAINT `INVENTORY_SOURCE_ITEM_SOURCE_CODE_INVENTORY_SOURCE_SOURCE_CODE` FOREIGN KEY (`source_code`) REFERENCES `inventory_source` (`source_code`) ON DELET), query was: INSERT INTO `inventory_source_item` (`source_code`, `sku`, `quantity`, `status`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `quantity` = VALUES(`quantity`), `status` = VALUES(`status`)"`

I've checked and all `inventory_` tables are empty except one `inventory_stock` table, which has one record with stock_id = 1 and name = Default Stock.

This could be related to https://github.com/magento/magento2/issues/22094 , but not sure. If this has been fixed in any newer versions, please provide the link to the commit.

**Comment by archonkulis** [comment]
Please close. The fix that worked for me is mentioned here https://github.com/magento/magento2/issues/22094#issuecomment-495098764

**Comment by manfrinm** [comment]
@magento-engcom-team any updates about it? you don't care anymore this issue?

**Comment by rakeshdonga** [comment]
@archonkulis 
i have same issue facing during magento 2.2,6 to magento 2.3.3 upgrade duration 
how can solve this?
