### ISSUE TITLE
BUG FIX

### ISSUE THREAD

**Issue by ivanoanekcha** [magento/magento2#22977]
we have security issue report and we need them to be fixed. One of the major issue is that the cookies flag.

Kindly help me fix this issues as soon as possible. 

Thanks

**Comment by ivanoanekcha** [comment]
Hi **@ivanoanekcha.** Thank you for your report.
To get solutions to the problems stated above you would need to contact the support of your hosting server to rectify this problem. Our team has gone through to know what actually went wrong and we discovered it's a core bug from the server you are hosted to.  Thanks for contacting us!


Let close this as it duplicates #22994

**Comment by hostep** [comment]
Let close this as it duplicates https://github.com/magento/magento2/issues/22993

@ivanoanekcha: please only create one issue for the same problem. Also try to follow the issue template which you are presented with when opening an issue. Thanks!
