### ISSUE TITLE
Magento 2.3 - Country Options vs Customer Account Sharing Options

### ISSUE THREAD

**Issue by NikZar** [magento/magento2#22973]
### Preconditions (*)
Server config:
Ubuntu 16.04 LTS
MySql 5.7.26
Apache 2.4.18
PHP 7.2.18

In a Magento 2.3.0 installation we configured multiple stores (each one as its own custom prices). 
We have 15 stores for each country (plus a "world" store for all the remaining countries). 

In the single country stores configuration we configured as an allowed and default country (in the Country Options) only the corresponding country.
In the world store we allowed all the remaining countries.

We enabled the customer Account Sharing Options in order not to require customers to create new account for each store.

### Steps to reproduce (*)
During the checkout the user is able to select from all the allowed countries (not only the single store specific one).

### Expected result (*)
I believe that even if we enabled the customer Account Sharing Options the user should only be able to see the allowed countries for that store.

### Actual result (*)
During the checkout the user is able to select from all the allowed countries (not only the single store specific one), it seems like a merge of all the stores (even if in some cases some stores are missing, for one store (russia) the default store is not even in the list... that is awkward).

Should we configure some other option in Magento or it is not possible to handle this kind of scenario?

**Comment by middlegrey** [comment]
We are also experiencing this problem.

Multiple websites with specific allowed countries.

When Configuration > Customers > Customer Configuration > Account Sharing Options > Share Customer Accounts is set to Global, during checkout rather than listing the allowed countries for that website, countries are shown from all websites.

Magento 2.3.1
Apache 2.4.39
PHP 7.1.29
MySQL 5.7.26

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99848`, `MAGETWO-99849` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @NikZar. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24357` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by jonathanribas** [comment]
Hi @magento-engcom-team, we are actually running `2.4.3-p1` and we still have this issue. Are you sure it was fixed?!

**Comment by jurvi** [comment]
> Hi @magento-engcom-team, we are actually running `2.4.3-p1` and we still have this issue. Are you sure it was fixed?!

Yea, I concur. I've been struggling today to find out why the heck we are getting full countries list via graphql no matter how we try to limit them. It's because of this. We also have a need to have global customers, but still be able to limit countries list.

**Comment by Crashead** [comment]
Hi everyone,
I had the same issue. Multiple websites, every website had different set of Allowed Countries for the checkout, and the user share account is set to Global.
The fix I did, is following. I overide the Magento\Directory\Model\AllowedCountries the getAllowedCountries method by setting the following:

`$scopeCode = [$storeManager->getStore()->getId()];`

Thanks
