### ISSUE TITLE
Drop requirement for plugin «name» when «type» attribute is present

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2297]
As I see, the sole purpose of the [`name`](https://github.com/magento/magento2/blob/22629abe10f9c640fe47b6081d57fedccdea8e0f/lib/internal/Magento/Framework/ObjectManager/etc/config.xsd#L141) attribute is to allow the plugin to be redefined by an extension.  
I propose to make the  `name` attribute optional (not required) and use the [`type`](https://github.com/magento/magento2/blob/22629abe10f9c640fe47b6081d57fedccdea8e0f/lib/internal/Magento/Framework/ObjectManager/etc/config.xsd#L142) attribute value as the name when the `name` attribute is absent. 
It would reduce an amount of code, so a developer can write
```
<type name='Magento\Framework\App\ActionInterface'>
	<plugin type='Df\Framework\App\ActionInterfacePlugin' />
</type>
```

instead of
```
<type name='Magento\Framework\App\ActionInterface'>
	<plugin
		name='SomeDummyName'
		type='Df\Framework\App\ActionInterfacePlugin'
	/>
</type>
```

**Comment by antonkril** [comment]
Plugin name is required for ability to rewrite plugin type.

**Comment by dfediuk** [comment]
I have said the same in my 1th sentence. What is about my 2nd sentence?

**Comment by antonkril** [comment]
So if plugin declaration is missing attribute "name", the "type" attribute for such plugin can not be overridden in other module, because "type" now becomes identifier.

To allow "type" override, we need "name" as identifier for all plugins.

**Comment by dfediuk** [comment]
It can. 
1) Initial plugin:
```
<type name='Magento\Framework\App\ActionInterface'>
    <plugin type='Df\Framework\App\ActionInterfacePlugin' />
</type>
```

2) Overrider:
```
<type name='Magento\Framework\App\ActionInterface'>
    <plugin
        name='Df\Framework\App\ActionInterfacePlugin'
        type='Override\Framework\App\ActionInterfacePlugin'
    />
</type>
```

By the way (not the puprose of the issue), the overrider looks more clear when specifying `Df\Framework\App\ActionInterfacePlugin` as the name instead of an abstract `SomeDummyName`.

**Comment by antonkril** [comment]
Oh, I see your idea now. It might work, but It mixes values of different nodes, which is confusing for developer. Also It would require specific customized configuration merger. And it's different from what we do in any configuration type.

Alternative approach would be to remove feature of plugin type rewrite (I don't know scenarios for this), but that would be a breaking change.

**Comment by dfediuk** [comment]
Yes, 99% of plugins declarations are of type 1
```
<type name='Magento\Framework\App\ActionInterface'>
    <plugin type='Df\Framework\App\ActionInterfacePlugin' />
</type>
```
so making the `name` optional can reduce the total amount of the plugin declaration code about 25%.

**Comment by antonkril** [comment]
Just to clarify: I think that making name optional would be confusing for developers. It should either stay as is, or name attribute should be removed at all.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by dfediuk** [comment]
I propose to do a good desion before the Release, otherwise it would hard to do it in the next 7-8 years because of compatibility importance.
