### ISSUE TITLE
Reindexing issue after upgrading to magento 2.3

### ISSUE THREAD

**Issue by himanshu-tech** [magento/magento2#22970]
### Preconditions (*)

1. Install magento 2.2.x
2. Make custom multiselect product attribute with souce model

### Steps to reproduce (*)

1. Upgrade above magento2.2.x to magento2.3.1 
2.Reindex Data

### Expected result (*)

1. Successful reidexing should happen for all indexers.

### Actual result (*)

1. Got error while reindexing Product EAV(catalog_product_attribute). The error which I got is: Warning: Illegal offset type in vendor/magento/module-catalog/Model/ResourceModel/Product/Indexer/Eav/Source.php line 351

**Comment by himanshu-tech** [comment]
@magento-engcom-team Yes, I was able to reproduce the issue on vanilla Magento instance.

**Comment by himanshu-tech** [comment]
My bad. I have used translation function in one of the options value.

**Comment by JonathanHelvey** [comment]
Hi [himanshu-tech], I am running into this exact same error. I take it, its one of my attributes values is wrong. However, I am not sure. How exactly did you find what attribute was throwing error? How did you fix? Just curious, thank you for the help.
