### ISSUE TITLE
Admin is logged out multiple times when a module's system.xml is modified

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#22981]
### Preconditions (*)
1. Magento 2.3.1
2. A custom module which adds a configuration section and tab defined via system.xml.
3. Create an acl.xml file for the module.
4. Developer Mode
5. Redis for cache
6. PHP 7.2
7. Debian 9 and 8. 
8. CSS / JS Merging is off
9. Sign Static files is off (with it on we get too many times auto log out for no reason)

### Steps to reproduce (*)
1. Create a module and a configuration page system.xml file for it. 
2. Add a few fields. 
3. Log in the backend. 
4. Go to store configuration.
5. Make a change to system.xml to add a new field (not a section or tab just a field under a group is fine). 

For example

```
            <group id="orders" showInWebsite="1" showInStore="1" showInDefault="1">
                <label>Order</label>
                <field id="last_id" type="text" showInDefault="1">
                    <label>Last order entity_id</label>
                </field>
                <field id="customer_list" type="text" showInDefault="1" showInStore="1" showInWebsite="1">
                    <label>Customer Browser Name</label>
                </field>
            </group>
```

And add

```
<field id="customer_series" type="text" showInWebsite="1" showInStore="1" showInDefault="1">
                    <label>Customer Series</label>
                </field>

```

6. Clear magento cache
7. Try to visit the module's configuration page. 
8. You are being logged out from the system
9. Log in again and try to revisit the module's configuration page.
10. You are being logged out from the system

The error is always `visible section not found`. 

### Expected result (*)
1. The user is logged out at most 1 times. Ideally no log out if you only added a field in a group and not a new section or tab that requires ACL to be refreshed. 

### Actual result (*)
1. Multiple auto log outs until you are able to reach the section. After 2-4 times of logging in and trying to reach the page you're able to access the page normally.

**Comment by ghost** [comment]
HI @ioweb-gr thank you for you report, i'm not able to reproduce following steps you described, seems like this related to your configuration, or enviroument m please recheck your system configuration like php.ini.
