### ISSUE TITLE
Advanced Reporting shows 404 Error

### ISSUE THREAD

**Issue by dev-cogniter** [magento/magento2#22982]
I own Magento ver 2.2.3. Advanced reporting shows 404 Error page. All settings are good but still it is not working.

**Comment by AlexWorking** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3-develop

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking, here is your [Magento instance](https://i-22982-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22982-2-3-develop.instances.magento-community.engineering/admin](https://i-22982-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AlexWorking** [comment]
Hi @dev-cogniter. Thanks for applying. We are closing this issue as a duplicate of #21452.

**Comment by davidduong90** [comment]
@dev-cogniter Do you find a solution for it?
