### ISSUE TITLE
Newsletter_subscription service interface and data interface is missing.

### ISSUE THREAD

**Issue by kumarbikash411** [magento/magento2#22985]
This issue is related with the API interaction to GET, POST,UPDATE AND DELETE API in magento 2, i was using the core component to subscribe via email which is working fine but when i was trying to delete or update using the rest API , it was not working.

The Interfaces are missing in vendor module and there are no endpoint available for newsletter_subscribers.

**Comment by Nazar65** [comment]
HI @kumarbikash411  It will be processed faster if you move this to https://github.com/magento/community-features
