### ISSUE TITLE
Bulk update product attributes

### ISSUE THREAD

**Issue by matthijsburki** [magento/magento2#22986]
When a user wants to change or update an attribute to all products (or a selection greater that the given items shown per page) the result is that when attributes are changed, Magento reports that a total of the current items shown per page were updated. The expected result should be that all records were changed.

### Preconditions (*)
1. Magento 2.3.1
2. More than 25 products

### Steps to reproduce (*)
1. Login to Magento admin
2. Go to Catalog > Products
3. Go to Select All
4. Go to Actions > Update attributes
5. Change an attribute
6. Magento reports that a total of X products (not all) were updated

### Expected result (*)
1. What should happen is that all records should be changed, not only the records of the first page.

### Actual result (*)
1. Only the records of the first page are changed / updated.
![Schermafbeelding 2019-05-23 om 13 25 07](https://user-images.githubusercontent.com/44090792/58249212-944d4300-7d5e-11e9-86a3-c5a6c67fc2e7.png)

**Comment by krishprakash** [comment]
Hi @matthijsburki. Thank you for your report.
This is duplicate to #22004

**Comment by AlexWorking** [comment]
Hello @matthijsburki. Thanks for reporting. As You can see the issue is already reported, confirmed and is being worked on. But as a temporary solution You may try to go the last page of the grid with the selected products and try to make an update then. Seems it works - all the records are updated then.
