### ISSUE TITLE
Wrong heading display in create configuration popup

### ISSUE THREAD

**Issue by krishprakash** [magento/magento2#22980]
Wrong heading display in create configuration popup.

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Admin
2. Add product
3. Configuration >> Create Configuration
4. Go to Summary Step with select all info
5. Review the heading "New Product Review" displaying.

### Expected result (*)
Heading should be Associated Products.
![image](https://user-images.githubusercontent.com/46617848/58232314-e12d1b80-7d56-11e9-8e33-826aa24ceb29.png)

### Actual result (*)
Displaying the New Product Review heading.
![image](https://user-images.githubusercontent.com/46617848/58232181-7f6cb180-7d56-11e9-9558-34169a94c721.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22980-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22980-2-2-develop.instances.magento-community.engineering/admin](https://i-22980-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Same issue in 2.2.
![image](https://user-images.githubusercontent.com/46617848/58232915-649b3c80-7d58-11e9-9704-9a7c32312b1d.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99807`, `MAGETWO-99808` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
It is not an issue because it is saying to review the new products.
According to the code if the configurable products have associated products then it will show "Associated Products" and if we are adding new products then it will show "New Products Review".

![Selection_002](https://user-images.githubusercontent.com/42089978/58273929-57f60300-7daf-11e9-9a3a-8586f0d97dc2.png)

**Comment by krishprakash** [comment]
Thanks for clarifying.
Closing this as non issue
