### ISSUE TITLE
MySQL Error on setup:upgrade going from 2.2.8 to 2.3.1

### ISSUE THREAD

**Issue by gldt-arandazzo** [magento/magento2#22999]
### Preconditions (*)
1. A magento 2.2.8 site with the files for 2.3.1 and a database that needs to be upgraded via bin/magento setup:upgrade

### Steps to reproduce (*)
1. Take a 2.2.8 site, upgrade the files following the directions here (https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html) (I did use 2.3.1 instead of 2.3.0 for the version numbers)
2. Get to the step of running `bin/magento setup:upgrade` (https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html#update-the-database-schema-and-data)
3. run `bin/magento setup:upgrade`

### Expected result (*)
1. `bin/magento setup:upgrade` completes successfully

### Actual result (*)
I receive the following error: ```SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-1692_10ff', query was: ALTER TABLE `customer_address_entity_decimal` MODIFY COLUMN `value_id` int(11)  NOT NULL  AUTO_INCREMENT COMMENT "Value Id", MODIFY COLUMN `attribute_id` smallint(5) UNSIGNED NOT NULL DEFAULT 0  COMMENT "Attribute Id", MODIFY COLUMN `entity_id` int(10) UNSIGNED NOT NULL DEFAULT 0  COMMENT "Entity ID", MODIFY COLUMN `value` decimal(12, 4)  NOT NULL DEFAULT 0 COMMENT "Value", ADD CONSTRAINT  PRIMARY KEY (`value_id`), ADD CONSTRAINT `CSTR_ADDR_ENTT_DEC_ATTR_ID_EAV_ATTR_ATTR_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`)  ON DELETE CASCADE, ADD CONSTRAINT `CSTR_ADDR_ENTT_DEC_ENTT_ID_CSTR_ADDR_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `customer_address_entity` (`entity_id`)  ON DELETE CASCADE, ADD CONSTRAINT `CUSTOMER_ADDRESS_ENTITY_DECIMAL_ENTITY_ID_ATTRIBUTE_ID` UNIQUE KEY (`entity_id`,`attribute_id`), DEFAULT CHARSET='utf8', DEFAULT COLLATE='utf8_general_ci'```

Please note that the `customer_address_entity_decimal` table is empty on my instance.

Thank you.

**Comment by gldt-arandazzo** [comment]
Environment  Is PHP 7.1-latest and Amazon RDS Aurora with compatibility of MySQL 5.7.12

**Comment by ghost** [comment]
HI @glo-arandazzo thank you for you report, this issue related to your customization or custom modules, on clean 2.2.8 we are  able to run setup:upgrade without this errors. thank you for collaboration if issue still exists, feel free to reopen.

**Comment by kriswen** [comment]
@glo-arandazzo did you ever find a solution to this issue? I tried upgrading with 2.2.9 to 2.3.3 also facing the same issue. thanks

**Comment by adamrandazzo** [comment]
@kriswen I unfortunately did not find a good solution. I had to modify the schema file to remove the addition of the FK constraint and run the setup:upgrade command. Total hack to get around it =( We have since upgraded to 2.3.2 and it is working correctly.

**Comment by kriswen** [comment]
@adamrandazzo Can you share where/how to modify the schema file for this case? I might have to do the same if i can't find a solution. Thanks.

**Comment by adamrandazzo** [comment]
Sure thing.. it was in vendor/magento/module-customer/etc/db_schema.xml

If you scroll down to the table with the error, you will see a contraint tag that you can comment out.

**Comment by kriswen** [comment]
thanks man! For my case, it was 'catalog_product_entity_text' table. For the reference, I think it was due to import the data using CSV import in the past, all the data in the same .csv file got assigned to the same value_id, which is 0.
