### ISSUE TITLE
Firefox JS translation issue when removing product from minicart

### ISSUE THREAD

**Issue by jburel-ca** [magento/magento2#22994]
### Preconditions (*)
1. Magento CE 2.2.7 or greater (I can't test in older version for now)
2. Another locale than default one. In my case, I used a Poland language pack installed by composer
3. Have one or more products availables for the website
4. Have Firefox browser (this bug is reproduced on all versions)

### Steps to reproduce (*)
1. With Firefox, navigate to a category or product page
2. Add product to cart
3. Into the header, click on the basket logo that opens mini cart popin
4. Click on the delete button at the right side of the product line you added previously

### Expected result (*)
1. OK and CANCEL buttons of the confirmation popin are translated into the right locale

### Actual result (*)
1. Sometimes, we haven't the right translation, buttons texts are "Cancel" and "OK"
2. You may be try again in other page (category, cart, checkout, homepage) if you can't reproduce this issue. And it's only with Firefox browser that I can reproduce this issue

Please let me know if you need more informations!

Thanks,

**Comment by jburel-ca** [comment]
> @jburel-clever-age do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
>

**Comment by magento-engcom-team** [comment]
Hi @jburel-clever-age. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jburel-clever-age, here is your [Magento instance](https://i-22994-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22994-2-3-develop.instances.magento-community.engineering/admin](https://i-22994-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by soleksii** [comment]
Hi @jburel-clever-age, thank you for your report. I can not reproduce this issue.

**Result:**
![screen](https://user-images.githubusercontent.com/44244273/58935766-c99e5b80-8776-11e9-9545-637fddb07112.png)


Firefox ver. 67.0

**Comment by jburel-ca** [comment]
Like i said in the last bullet point, you may try on several page, and on some pages you will lost translation. I reproduced this issue on a fresh 2.3.1 environment.

Never mind, we solved the problem on our side by making a homemade patch. You can keep this ticket closed.
