### ISSUE TITLE
SQL error on indexer:reindex 2.2.8

### ISSUE THREAD

**Issue by danharper83** [magento/magento2#23003]
### Summary
Catalog indexer is broken when flat mode is turned on.

### Information on your environment
Local environment (containerised NGINX with lando) and hosting provided by platform sh

### Preconditions (*)

1. Magento version 2.2.8
2. Flat category and flat product catalogue enabled (Error doesn't appear with them off)

### Steps to reproduce (*)

1. Updated to 2.2.8 from 2.2.6
2. Run ```php bin/magento indexer:reindex```

### Expected result (*)

1. Indexer completes successfully 

### Actual result (*)

1. Indexer produces SQL error
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'condition IS NOT NULL)' at line 5, query was: UPDATE `catalog_product_flat_1_tmp_indexer` AS `et`
 LEFT JOIN `eav_attribute_option_value` AS `t0` ON t0.option_id = et.condition AND t0.store_id = 0
 LEFT JOIN `eav_attribute_option_value` AS `ts` ON ts.option_id = et.condition AND ts.store_id = 1
SET `et`.`condition_value` = IFNULL(ts.value, t0.value)
WHERE (condition IS NOT NULL)
```

**Comment by danharper83** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @danharper83. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @danharper83, here is your [Magento instance](https://i-23003-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23003-2-3-develop.instances.magento-community.engineering/admin](https://i-23003-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by danharper83** [comment]
I could not replicate this on a Vanilla install.

**Comment by danharper83** [comment]
I think the problem with this query is that the ```WHERE (condition IS NOT NULL)``` should be ```WHERE ('condition' IS NOT NULL)```

```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'condition IS NOT NULL)' at line 5, query was: UPDATE `catalog_product_flat_1_tmp_indexer` AS `et`
 LEFT JOIN `eav_attribute_option_value` AS `t0` ON t0.option_id = et.condition AND t0.store_id = 0
 LEFT JOIN `eav_attribute_option_value` AS `ts` ON ts.option_id = et.condition AND ts.store_id = 1
SET `et`.`condition_value` = IFNULL(ts.value, t0.value)
WHERE (condition IS NOT NULL)```

**Comment by Eayshwary** [comment]
Hi, can you provide me the instance for 2.2.8 ?

**Comment by danmooney2** [comment]
Yeah, try this in app/code/Magento/Catalog/Model/Indexer/Product/Flat/FlatTableBuilder.php line 368:

```
)->where("`$attributeCode` IS NOT NULL");
```

**Comment by danharper83** [comment]
@danmooney2 it was an attribute called condition 🤦‍♂ 

I deleted the attribute on staging and it indexed successfully, I'm not sure how I can fix the attribute "condition" though.

**Comment by danmooney2** [comment]
@danharper83 `condition` is a reserved word in MySQL/MariaDB.  Backticks (`) around the keyword would escape it and it would not be interpreted in a special manner by the parser; I think that's the correct change to make that I referenced above

**Comment by ghost** [comment]
HI @danharper83 thank you for you report, this issue has already fixed in 2.3-develop and 2.2-develop branch and available on 2.3.1 release and 2.2.9 release.

**Comment by danielpfarmer** [comment]
@engcom-backlog-nazar  I can still replicate this issue on 2.2.9

**Comment by danielpfarmer** [comment]
Reopening as still and issue an 2.2.9 & 2.3.2

**Comment by engcom-Charlie** [comment]
Hello @danharper83 
We are not able to reproduce this issue on the lates 2.3-develop branch. 
So we have to close this issue.
