### ISSUE TITLE
Invoice email not received while place order in magento 2

### ISSUE THREAD

**Issue by nayan88** [magento/magento2#23001]
I have not received invoice email after placing order.

Magento version : 2.2.2 & 2.3.0

Checked in these Payment Methods : Authorize.net & Zero subtotal Checkout

**Expected result:**
1. Order Created
2. Email with order information send.
3. Invoice Created
4. Email with invoice information send

**Actual Result**

1. Order Created <- working
2. Email with order information send. <- working
3. Invoice Created <- working
4. Email with invoice information is not send <- not working

For Zero subtotal Checkout payment method settings follow below steps:

**Enable zero subtotal checkout.**

1. Set new order status to processing.
2. Create a cart rule with 100% rebate and free shipping.
3. Place order with coupon code & free shipping method.
4. Check order detail in admin Invoice was generated but email not received.

From back-end when send email button clicked manually in Invoice view page - proper email invoice received.

**Same issue happen will Authorize.net Direct Post payment method,** 
set Payment action as **Authorize & Capture**, 
new Order status as **Processing** ,
so while place an order with authorize.net order placed successfully >> order email was also received >> Invoice generated properly >> but invoice email not received.
 

If anyone have any idea please let me know.

Thanks in Advance..!!!

**Comment by syed92hasan** [comment]
I am working on this at #dmcdindia19

**Comment by AlexWorking** [comment]
Hello @nayan88. Thanks for applying. Your issue seems to be the duplicate of an earlier issue #13466, which is confirmed and is already having been worked on.

**Comment by sjgdk** [comment]
> Hello @nayan88. Thanks for applying. Your issue seems to be the duplicate of an earlier issue #13466, which is confirmed and is already having been worked on.

How is this going? I see that it's at Ready for Dev at Community Backlog

Can you give me an idea how to solve it as a temporary solution?

By the way, why are you being unassigned by @engcom-Bravo ?

**Comment by rav-redchamps** [comment]
In case, anyone interested in a paid extension then this should do the trick https://redchamps.com/invoice-email-magento-2-extension.html
