### ISSUE TITLE
Nginx is downloading cron instead of executing it when run from browser

### ISSUE THREAD

**Issue by johnbendi** [magento/magento2#2301]
other php files get executed but cron.php doesn't

```
location cron\.php {
	auth_basic "Cron Authentication";
	auth_basic_user_file <path to password file>;
} 
```

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [technical issues forum](https://community.magento.com/t5/Technical-Issues/bd-p/magento-2-technical-issues) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
