### ISSUE TITLE
Order Item Status to Enable Downloads Does Not Work

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#23013]
When working with downloadable products, since upgrading to Magento 2.2.8 from 2.2.5, this error has occurred. You are not able to change the item status to enable downloads. For instance, there are two options: Pending, Invoiced. When a downloadable order comes in (specifically free) they come in as pending. We want users to be able to immediately download their free product. On 2.2.5 this functionality worked. Since then something has changed and it has since not worked.

### Preconditions (*)
1. Magento 2.2.8

### Steps to reproduce (*)
1. Create Downloadable Product
2. In backend, goto Configuration>Catalog>Catalog>Download Product Options
3. Order Item Status to Enable Downloads: Pending
4. Order downloadable product on frontend, (free or paid).
5. Order Grid shows order as pending.
5. On frontend, goto My Account> My Downloadable Products
<img width="478" alt="Downloads-Pending" src="https://user-images.githubusercontent.com/36938969/58350107-fbd4c280-7e32-11e9-8ea2-dfb015f0f6b9.png">

### Expected result (*)
1. Downloadable product is available for download.

### Actual result (*)
1. Downloadable product is marked pending and not able to be downloaded.

**Comment by nickpiro** [comment]
@magento give me 2.2.8 instance

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nickpiro, here is your [Magento instance](https://i-23013-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-23013-2-2-8.instances.magento-community.engineering/admin](https://i-23013-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23013-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23013-2-3-develop.instances.magento-community.engineering/admin](https://i-23013-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue not reproduced on the 2.3-develop instance

**Comment by ktpl-rammohan** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23013-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23013-2-2-develop.instances.magento-community.engineering/admin](https://i-23013-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue not reproduced on Magento ver. 2.2.9-dev

**Comment by KaustubhBorate** [comment]
I am facing this issue on Magento 2.2.9. I have Upgrade the version from 2.2.3 to 2.2.9 and after that i am facing this issue. 
Please  guide me to resolve.
