### ISSUE TITLE
newsletter subscription simple captcha and double opt in

### ISSUE THREAD

**Issue by engineergreg** [magento/magento2#23018]
### Description (*)
simple captcha requirement for newsletter subscibers to prevent bots from populating subscriber list

### Expected behavior (*)
admin can enable captcha for newsletter email form in footer of frontend if desired and require confirmation of subscription in response email, (double opt in to validate newsletter subscriptions)

### Benefits
subscriptions to newsletter would be from verified humans to comply with can-spam laws

**Comment by ajijshekh123** [comment]
Hi @engineergreg.
Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Also please mention additional details about the issue.
Please explain the in which Magento version you phase this issue?

**Comment by ajijshekh123** [comment]
@engineergreg fell free to reopen this issue when you will be ready to provide more details and we will review it and confirm
