### ISSUE TITLE
Newsletter Queue Start Time ends up 7 hours in future

### ISSUE THREAD

**Issue by engineergreg** [magento/magento2#23017]
### Preconditions (*)
Magento 2.3.1

### Steps to reproduce (*)
1.create newsletter
2.queue newsletter
3. set start date and time

### Expected result (*)
 time should match entered time

### Actual result (*)
start time listed in queue is 7 hours ahead of expected time

**Comment by engineergreg** [comment]
the current solution is to enter a start time 7 hours before the expected start time

**Comment by orlangur** [comment]
Please specify all relevant to timezone configuration of your PHP/MySQL.

**Comment by engineergreg** [comment]
the xampp server on windows has NO TIME ZONE SETTING declared in the
php.ini, suppose it is using the windows time service

**Comment by orlangur** [comment]
@engineergreg, are you able to reproduce an issue on a supported OS?

**Comment by ghost** [comment]
H @engineergreg thank you for your report, i'm not able to reproduce following steps you described, seems like this related to your timezone configuration, please specify wich time zone use your php or mysql, then verify if this timezone the same with magento timezone. feel free to reopen if issue still exist. thank you for collaboration.
