### ISSUE TITLE
Print This Page link alignment not as per magento 2.2

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#23010]
Print This Page link alignment issue in compare page.

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Front end: Add to compare product
2. Compare page
3. Review the Print this page link 

### Expected result (*)
It should be display on right side as magento 2.2
![compare expected](https://user-images.githubusercontent.com/49804008/58333341-d3f95500-7e5a-11e9-816e-851f3db56c93.jpg)

### Actual result (*)
![compare actual](https://user-images.githubusercontent.com/49804008/58333360-dcea2680-7e5a-11e9-9fc3-23af9f50a7a9.jpg)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23010-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23010-2-3-develop.instances.magento-community.engineering/admin](https://i-23010-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23010-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23010-2-2-develop.instances.magento-community.engineering/admin](https://i-23010-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @bhavik43. 
Print This Page link position is left side in both magento 2.2 and 2.3.
So this is not an issue.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23010-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23010-2-3-develop.instances.magento-community.engineering/admin](https://i-23010-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance
