### ISSUE TITLE
Profiler rendering issue on admin

### ISSUE THREAD

**Issue by sanganinamrata** [magento/magento2#23016]
### Preconditions (*)

1. Configure the database profiler: https://devdocs.magento.com/guides/v2.0/config-guide/db-profiler/db-profiler.html
2. Enable profiling (MAGE_PROFILER) using CLI command https://devdocs.magento.com/guides/v2.3/config-guide/bootstrap/mage-profiler.html

### Steps to reproduce (*)

1. Enabled profiler for HTML and database queries, Go to admin panel login screen.

### Expected result (*)

![admin_profiler_result](https://user-images.githubusercontent.com/37930646/58368937-57757d80-7f11-11e9-8cae-624f8ba44fbd.png)

### Actual result (*)

![admin_profiler](https://user-images.githubusercontent.com/37930646/58368931-3319a100-7f11-11e9-8181-5b703726cc86.png)

**Comment by sanganinamrata** [comment]
I'll fix this design issue soon.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21925` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
