### ISSUE TITLE
Magento 2.2.8 - Config Cache not Updated on Save

### ISSUE THREAD

**Issue by svenakela** [magento/magento2#23015]
### Preconditions (*)
1. Upgraded 2.2.3 to 2.2.8, no issues during upgrade

### Steps to reproduce (*)
1. We did an upgrade, have no idea if the previous version affects the problem.
2. Config Cache should be enabled.

### Expected result (*)

1. Go to Admin System Config or Store Config and make any configuration change.
2. Save.
3. Value should be updated in GUI as well as DB.

### Actual result (*)

1. After save, no errors in browser nor in logs.
2. The old config value is still present in the GUI but the new is listed with the CLI.
3. Go to Cache Management and refresh the Config Cache.
4. Go back to the config changed, the new value is listed.

The effect is also that if a setting is changed and saved, the old value is prefilled when the page is refreshed. If another value is changed and saved, the FIRST value is rollbacked to the old value as the GUI holds the old value.

If the Config Cache is disabled, everything works as expected and the new value is present after save.

**Comment by svenakela** [comment]
The behavior is exactly as in this video clip, except that I must Flush Cache Storage to get the change visible.
https://www.youtube.com/watch?v=0E6TDEvcFbE

Setup is like following:
Nginx(SSL) -> Varnish -> Nginx(Magento) -> PHP FPM
Purging Varnish manually has no effect. 

Only system and store config is affected. Changing products and customers behaves normally.

**Comment by engcom-Charlie** [comment]
Hello @svenakela ! Thank you for your report !
I`ve tried to reproduce this issue both on 2.3.x-develop and 2.2.x-develop instances and was not able to do it. I`m closing this issue for now but if you can confirm that problem is still exist on 2.3.x release line then feel free to reopen this issue.
Thanks in advance!
