### ISSUE TITLE
Incorrectly invoicing and capturing values when a bundle item is present

### ISSUE THREAD

**Issue by DavidSim80** [magento/magento2#23012]
### Preconditions (*)

Magento 2.3.1

### Steps to reproduce (*)

Add a bundle item to the cart
Add another item we added in our test (1x Sprite Yoga Companion Kit) then also 30x Joust Duffle Bag) from the sample data
Have payment gateway set to capture sale
Checkout as you would normally 

### Expected result (*)
To invoice and capture full payments for all items, not part of it

### Actual result (*)
An item with a qty above 1 only taking and charging for total qty 1

Please see attached image of sale transaction showing the issue. 
![2019-05-24_17-20-19](https://user-images.githubusercontent.com/50997517/58342422-3bf27000-7e48-11e9-9a61-d580e3e2b44c.png)

**Comment by ktpl-rammohan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23012-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23012-2-3-develop.instances.magento-community.engineering/admin](https://i-23012-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue not reproduced on Magento 2.3-develop

**Comment by ktpl-rammohan** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23012-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23012-2-2-develop.instances.magento-community.engineering/admin](https://i-23012-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue not Reproduced on Magento 2.2-develop instance.

@DavidSim80 Issues not reproduce on clean Magento, please recheck and let me know if you are facing the same issue on Default Magento instance.

I am closing this issue.

**Comment by DavidSim80** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DavidSim80. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DavidSim80, here is your [Magento instance](https://i-23012-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23012-2-3-develop.instances.magento-community.engineering/admin](https://i-23012-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DavidSim80** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DavidSim80. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DavidSim80, here is your [Magento instance](https://i-23012-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23012-2-2-develop.instances.magento-community.engineering/admin](https://i-23012-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cyberbasement** [comment]
> 
> ### Preconditions (*)
> 
> Magento 2.3.1
> ### Steps to reproduce (*)
> 
> Add a bundle item to the cart
> Add another item we added in our test (1x Sprite Yoga Companion Kit) then also 30x Joust Duffle Bag) from the sample data
> Have payment gateway set to capture sale
> Checkout as you would normally
> ### Expected result (*)
> 
> To invoice and capture full payments for all items, not part of it
> ### Actual result (*)
> 
> An item with a qty above 1 only taking and charging for total qty 1
> 
> Please see attached image of sale transaction showing the issue.
> ![2019-05-24_17-20-19](https://user-images.githubusercontent.com/50997517/58342422-3bf27000-7e48-11e9-9a61-d580e3e2b44c.png)

I have this exact same issue on 2.3.1 - Did you ever find a solution / the cause?

**Comment by DavidSim80** [comment]
Hi

No the person looking as you can see said they could not replicate it. But we can replicate it on a vanilla version. I don't think they followed the steps correctly. It only happens when you capture at the time of the order. The workaround we have at the moment is to authorise and when you then raise the invoice against the shipment it captures the correct amount. It does not matter what gateway you use and the gateway providers have also stated this is a Magento bug as they can also replicate the error

**Comment by ktpl-rammohan** [comment]
@DavidSim80 okay understood. let me recheck it again.

**Comment by ghost** [comment]
@magento give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @paul-gene. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @paul-gene, here is your [Magento instance](https://i-23012-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-23012-2-3-1.instances.magento-community.engineering/admin](https://i-23012-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cyberbasement** [comment]
FYI - This issue is directly related to another issue ( https://github.com/magento/magento2/pull/22944 ), the fix proposed in "Fix Issue 22743" to app/code/Magento/Sales/Model/Service/InvoiceService.php appears to also correct the incorrect invoicing issue stated above. We have thoroughly tested this fix in our dev environment and it corrected both issues for us.

**Comment by xylodev** [comment]
I am also encountering this issue on Magento 2.3.2. As stated in #22743 it concerns all payment methods that capture the amount on order placement, eg. appropriately configured PayPal (Payment Action = **Sale**) and Amazon Pay (Payment Action = **Charge on Order**). I'd be happy to provide PR for this bug.

@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @xylodev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @xylodev, here is your [Magento instance](https://i-23012-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23012-2-3-develop.instances.magento-community.engineering/admin](https://i-23012-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by xylodev** [comment]
Issue not reproducible on Magento 2.3-develop instance. Either the issue is resolved in 2.3-develop or I confused some PayPal settings. I will setup a 2.3-develop locally to re-trace the order placement process and will get back.

**Comment by ghost** [comment]
@xylodev yea, I imagine it was fixed inbetween it being reported and your tests now. Maybe start with 2.3.1 locally and test that, then increase the version and try again?
