### ISSUE TITLE
does not work on latest verson of xampp

### ISSUE THREAD

**Issue by shyandsy** [magento/magento2#2302]
when I finished the setup process, it shows "success"
![image](https://cloud.githubusercontent.com/assets/5271457/11021403/f86c13e2-8605-11e5-96be-2a6b31db70ed.png)

but I cant open the home page and admin page, always keep loading 

![image](https://cloud.githubusercontent.com/assets/5271457/11021408/21881b40-8606-11e5-8bd6-11c2427f1cc4.png)

**Comment by dfediuk** [comment]
First of all, you should use a domain name (and it must be not top-level) instead of an IP address.

**Comment by mazhalai** [comment]
@shyandsy are there any javascript errors on the developer console?
