### ISSUE TITLE
Default uploading image size wysiwyg editor M2.3.1

### ISSUE THREAD

**Issue by fasaro** [magento/magento2#23026]
> **Fatal error**: Uncaught Error: Call to a member function getIsResizeEnabled() on null in /public_html/vendor/magento/module-cms/view/adminhtml/templates/browser/content/uploader.phtml:20 Stack trace: #0 /public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include() #1 /public_html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Uploader), '/pu...', Array) #2 /public_html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/pu...') #3 /public_html/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml() #4 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Backend\Block\Template->_toHtml() #5 /public_html/vendor/magento/framework/View/Layout.php(557): in **/public_html/vendor/magento/module-cms/view/adminhtml/templates/browser/content/uploader.phtml on line 20**

**Comment by pauldonnelly** [comment]
I'm having the same issue, started all of a sudden. Using 2.3.1 as well.

**Comment by pauldonnelly** [comment]
It may be a Cloudinary issue (if you have it installed), I disabled it and it worked again. Maybe not a Magento issue.

**Comment by VasylShvorak** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak, here is your [Magento instance](https://i-23026-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23026-2-3-develop.instances.magento-community.engineering/admin](https://i-23026-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VasylShvorak** [comment]
Hi @fasaro thank you for you report, but i'm not able to reproduce issue you described on clean 2.3-develop

**Comment by clion007** [comment]
I found the same issue when a extension call on getImageUploadConfigData()->getIsResizeEnabled() method in vendor\magento\module-backend\view\adminhtml\templates\media\uploader.phtml and how should I update the extension?
