### ISSUE TITLE
Element 'move' : Magento

### ISSUE THREAD

**Issue by uniquedeveloper17** [magento/magento2#23027]
Site Link : https://www.leis.synergixfast.com

1 exception(s): Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'move': This element is not expected. Expected is one of ( action, arguments, block, container, referenceBlock, uiComponent ). Line: 834

Element 'referenceBlock', attribute 'ifconfig': The attribute 'ifconfig' is not allowed. Line: 891

Element 'referenceBlock', attribute 'ifconfig': The attribute 'ifconfig' is not allowed. Line: 903

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'move': This element is not expected. Expected is one of ( action, arguments, block, container, referenceBlock, uiComponent ). Line: 834

Element 'referenceBlock', attribute 'ifconfig': The attribute 'ifconfig' is not allowed. Line: 891

Element 'referenceBlock', attribute 'ifconfig': The attribute 'ifconfig' is not allowed. Line: 903

I just copied the website from the main domain and set up on a subdomain and I found many errors. Please help.

Waiting for a quick response.

**Comment by uniquedeveloper17** [comment]
any response

**Comment by syed92hasan** [comment]
I want to work on this issue.

**Comment by uniquedeveloper17** [comment]
please tell me how can i resolve this ... i have ftp details

**Comment by VasylShvorak** [comment]
Hi @uniquedeveloper17 . The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
