### ISSUE TITLE
Reinstall triggers

### ISSUE THREAD

**Issue by QuentinFarizon** [magento/magento2#23023]
### Description (*)
I think my database lacks some triggers, and I'd like to know if there a feature / workaround / command line to reinstall them.

In particular, I'm missing triggers on the catalog_product_entity table (trg_catalog_product_entity_after_insert, trg_catalog_product_entity_after_insert, ...), but I do have triggers on all, attribute tables (trg_catalog_product_entity_text_after_update, ...)

### Expected behavior (*)
Being able to reinstall triggers

### Benefits
Repair a broken system

### Additional information
None

**Comment by hostep** [comment]
@QuentinFarizonAfrimarket, if you switch the indexer mode around it will either remove triggers or add them.

So, this will remove all the triggers:
```
bin/magento indexer:set-mode realtime
```

And this will add them again:
```
bin/magento indexer:set-mode schedule
```

Can you test this and let us know if this fixes your issue?

I think this hasn't been documented yet on https://devdocs.magento.com/, it might be best if we add a small remark over there.

**Comment by QuentinFarizon** [comment]
Hello @hostep thanks for the response !

I have figured that out, and ran them, I didn't check all of them but it seems to have added some more triggers.
It's possible we missed some after our database migration and/or our upgrade 2.1.13 -> 2.2.8

**Comment by hostep** [comment]
Ok great! Let's close this issue then 🙂

**Comment by QuentinFarizon** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @QuentinFarizonAfrimarket. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @QuentinFarizonAfrimarket, here is your [Magento instance](https://i-23023-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23023-2-2-develop.instances.magento-community.engineering/admin](https://i-23023-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
