### ISSUE TITLE
Inconsistency in payment error message handling

### ISSUE THREAD

**Issue by tylers-username** [magento/magento2#23037]
### Summary (*)

**Discovered:** Magento 2.2
**Reproduced:** 2.2 & 2.3

Magento allows developers to provide files such as `vendor/magento/module-braintree/etc/braintree_error_mapping.xml` so that we can output our own payment error messages to the end user. However, sometimes `GatewayCommand::execute()`'s validator sometimes outputs the message codes (as expected) but other times outputs "Processor Declined" rather than the code.

The issue is that "Processor Declined" cannot be mapped to a custom message - we need the code.

### Examples (*)
With Braintree sandbox credentials, add items to your card to bring your grand total to the $2,100 - $2,999 range.  By setting the grand total to $2,100-$2,999 we tell Braintree to give us a "Processor Declined" response.  Provide a test card such as:

- Card: 4111-1111-1111-1111
- Exp: *Any future date*
- Security #: 111

(Refer to: https://developers.braintreepayments.com/reference/general/testing/php#transaction-amounts)

Normally, Braintree errors are mapped by [code](https://developers.braintreepayments.com/reference/general/validation-errors/all/php#address), however, in this example Magento uses "Processor_Declined" as the code - which is not mappable.

### Proposed solution
Always use the payment processor code when checking for error message mapping.

**Comment by tylers-username** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tylerssn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tylerssn, here is your [Magento instance](https://i-23037-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23037-2-3-develop.instances.magento-community.engineering/admin](https://i-23037-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23037-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23037-2-3-develop.instances.magento-community.engineering/admin](https://i-23037-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23037-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23037-2-2-develop.instances.magento-community.engineering/admin](https://i-23037-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @tylerssn,
I have verified this issue in Magento 2.3 and Magento 2.2 Instance as per your details.

In Magento 2.3, I have displayed the 'Transaction has been declined. Please try again later.' error.

**See attached the Screenshot:**

![2 3](https://user-images.githubusercontent.com/24711761/58532852-70797980-8204-11e9-95b1-f7953cc0ab71.png)

In Magento 2.2, I have displayed the Same 'Transaction has been declined. Please try again later.' error.

**See attached the Screenshot:**

![2 2](https://user-images.githubusercontent.com/24711761/58532878-85560d00-8204-11e9-8557-9bc3e15adb42.png)

@tylerssn - If you found 'Processor Declined' error in a specific scenario. Please update here.

**Comment by tylers-username** [comment]
@ajijshekh123 - thanks for jumping in here.

> "Transaction has been declined. Please try again later"

This is a generic error message that indicates that no messages have been mapped to the error code returned by this gateway -  thrown by `Magento\Payment\Gateway\Command\GatewayCommand::processErrors()` which is called by the class method pointed out in my opening comment `GatewayCommand::execute()`.

If the payment processor you were testing is Braintree and returned code `81703` then Magento would have referenced `vendor/magento/module-braintree/etc/braintree_error_mapping.xml` to look up the message and would have outputted "*Credit card type is not accepted by this merchant account.*" rather than "*Transaction has been declined.*". 

The problem I'm pointing out is that, at times, Magento's payment response validator does not always use the payment processor error codes. For example, with Braintree, Magento sometimes prefers to use "PROCESSOR_DECLINED" rather than the unique code associated with the actual error returned by the payment gateway.

**Edit:** For added detail, in my Braintree example, it appears that [Validation Errors](https://developers.braintreepayments.com/reference/general/validation-errors/overview/php) are handled by Magento's mapper, but [processor response errors (declines)](https://developers.braintreepayments.com/reference/general/processor-responses/authorization-responses#declines) are not even though they are output to Braintree's error class.

**Comment by ajijshekh123** [comment]
Hello @tylerssn,
I can't able to reproduce this issue. 
Can you please provide the Step to be reproduced Or Video?

**Comment by tylers-username** [comment]
@ajijshekh123 - from our Slack conversation.

> The only thing that I think would help troubleshoot this further is, using Braintree as an example, mappable error codes are limited to [Validation Errors](https://developers.braintreepayments.com/reference/general/validation-errors/all/php) even though [Processor Errors](https://developers.braintreepayments.com/reference/general/processor-responses/authorization-responses#declines) are still passed into Braintree's error class. (edited) 
> 
> This is the best way to reproduce, as outlined in the issue on GitHub:
> 
> > With Braintree sandbox credentials, add items to your card to bring your grand total to the $2,100 - $2,999 range. By setting the grand total to $2,100-$2,999 we tell Braintree to give us a "Processor Declined" response. Provide a test card such as:
> >
> > Card: 4111-1111-1111-1111
> > Exp: Any future date
> > Security #: 111
> > (Refer to: https://developers.braintreepayments.com/reference/general/testing/php#transaction-amounts)
> >
> > Normally, Braintree errors are mapped by code, however, in this example Magento uses "Processor_Declined" as the code - which is not mappable.
> 
> The example above forces Braintree to return a Processor Declined error - which means mappers such as `vendor/magento/module-braintree/etc/braintree_error_mapping.xml` will have no impact on what is output to the customer.
> 

> Using the Braintree example, when a response from Braintree is deemed an "error" response, an Error class is returned to the payment gateway that contains the response, error code, error message, etc. Magento's `Gateway::execute()` and `Gateway::_processErrors()` methods take the error code provided by Braintree's error class and searches for a mapped message. If a message is not found in `braintree_error_mapping.xml` it outputs:
> 
> > Transaction has been declined. Please try again later.
> 
> This is the same for all payment gateways. I should be able to add decline codes such as https://developers.braintreepayments.com/reference/general/processor-responses/authorization-responses#decline-codes to the mapping XML for any payment gateway in order to provide my own error message, however, in the Braintree example, only validation error codes can be added

**Comment by ajijshekh123** [comment]
Okay, @tylerssn.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18736` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @tylerssn. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23901` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by rey8a** [comment]
Is there a patch for this? Will this fix be added to 2.4.2-p1?
I see 2.4.3 beta is not scheduled to be released until July 6th, 2021.
