### ISSUE TITLE
Meta property not showing on social media such as Facebook

### ISSUE THREAD

**Issue by zeekzeeky** [magento/magento2#23039]
### Summary
I have inserted Search Engine Optimisation metadata such as Meta title, description and keywords using Bluefoot CMS builder on Magento 2.1.9 (screenshot below). 
<img width="1268" alt="Screenshot 2019-05-29 at 3 21 45 PM" src="https://user-images.githubusercontent.com/32473615/58537450-7c296800-8225-11e9-9948-217095790c6a.png">

The meta property appears perfectly when I inspect the webpage's element as you can see in the screenshot below. 
<img width="826" alt="Screenshot 2019-05-29 at 3 20 03 PM" src="https://user-images.githubusercontent.com/32473615/58537331-44babb80-8225-11e9-98a9-4d1e6882ddcc.png">

But the problem comes when I tried to post my webpage on social media such as Facebook that the meta title and description does not follow the specific copy that was inserted for that webpage alone. Instead, it is pulling copy from the default metadata such as the screenshot below. I have scrape the page on Facebook Debugger repeated to no avail. 
<img width="995" alt="Screenshot 2019-05-29 at 3 24 11 PM" src="https://user-images.githubusercontent.com/32473615/58537632-d296a680-8225-11e9-9d71-c7e566cbc1de.png">

Also, is there any way that I can upload my own image to replace the default meta image shown on social media?

Any help on this from you will be super great. Thank you.

**Comment by soleksii** [comment]
Hi @zeekzeeky, thank you for your report, this issue has already fixed in 2.2-develop and 2.3-develop branch and available on 2.2.9 and 2.3.1 release.
