### ISSUE TITLE
Plus sign is not allowed in SKU on Product API

### ISSUE THREAD

**Issue by iamsambrown** [magento/magento2#23043]
### Preconditions (*)

1. Found the bug using Magento 2.2.3
2. Vanilla implementation of Magento Product Repository

### Steps to reproduce (*)

1. Create a product with SKU containing '+' eg. 'BAH-SB+7'
2. Query Magento instance via REST API /rest/V1/products/BAH-SB+7
3. Observe response

### Expected result (*)

1. ![Screenshot 2019-05-29 at 11 13 43](https://user-images.githubusercontent.com/6470667/58549195-e11f9680-8202-11e9-9de4-58f1318e593f.png)
2. JSON Object of the product

### Actual result (*)

1. ![Screenshot 2019-05-29 at 11 11 13](https://user-images.githubusercontent.com/6470667/58549182-da911f00-8202-11e9-97a2-1a33dfe50cdb.png)
2. JSON response 'Requested product does not exist'
3. You can see in the response that it is looking for a product with SKU 'BAH-SB 7' in the repository, as the + has been replaced with space.

**Comment by AlexWorking** [comment]
Hello @iamsambrown. Thanks for reporting. The behavior You have described here is really reproduced. But it's hard to definitely say that behavior is a bug. You see the API requests are sent via URLs, and the "+" in URL stands for space and that is, so to say,  the universally known truth. So if one needs to pass the "+" sign via URL one will simply encode it to "%2B". Thus if You change the behavior to the one that enables sending "+" as it is, someone, who wants to pass a space via URL trying to normally do that by writing in the "+" sign (though it is also possible to do by "%20"), will definitely encounter an unexpected behavior. What do You thing about it?

**Comment by iamsambrown** [comment]
Hello @AlexWorking - I understand what you mean. A plus represents a space in a URL

The problem is that without this code in place, even putting in %2B in place ( ie. `BAH-SB%2B7` ) will return a space. It will encode %2B to a plus, and then seemingly encode it again into a space character. So `BAH-SB%2B7` will read as `BAH-SB 7`. Whereas inputting %20 will still result as a space character, with this code in place.

Do you agree that there is an issue, but potentially need a more intelligent solution? Allowing for + to equal a space character, and %2B to equal a plus character?

**Comment by orlangur** [comment]
> It will encode %2B to a plus, and then seemingly encode it again into a space character

Why? Will `urlencode('%2B')` work?

Described system behavior is absolutely correct.

**Comment by AlexWorking** [comment]
@iamsambrown, don't exactly understand what You mean by "and then seemingly encode it again into a space character". I performed the request one by one for several times and here is what I got:
![plusku1](https://user-images.githubusercontent.com/27814011/58559315-8189b100-822b-11e9-974f-73e60ec854bb.png)
![plusku2](https://user-images.githubusercontent.com/27814011/58559321-85b5ce80-822b-11e9-8871-7d3cd3436335.png)
Seems everything works correctly, doesn't it?

**Comment by iamsambrown** [comment]
That does look correct. Is that on a vanilla Magento instance? 

That was not working on my instance, please see in the screenshot below. In the trace, the product repository is trying to get `ProductRepository->get('BAH-SB 7', false, NULL, false)` - whilst the SKU passed in is `BAH-SB%2B7`

![Screenshot 2019-05-29 at 14 10 46](https://user-images.githubusercontent.com/6470667/58559720-a1b17400-821b-11e9-824c-d542e2e33f5e.png)

**Comment by AlexWorking** [comment]
@iamsambrown, yes, mine was on an almost vanilla instance. I mean there had already been created several products before I created the one with that SKU. But I don't believe I has some impact on the situation.

**Comment by david-garcia-garcia** [comment]
For anyone using IIS to run magento, this issue happens if you have not properly configured your rewrite rules to tell zend-framework that you are running rewrites, you need to add this to your rewrite rules:

`                    <serverVariables>
                        <set name="IIS_WasUrlRewritten" value="1" />
                        <set name="ENABLE_IIS_REWRITES" value="1" />
                    </serverVariables>`
