### ISSUE TITLE
Composer Install error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed 

### ISSUE THREAD

**Issue by eCommerceGorilla** [magento/magento2#2304]
Ran into an issue when running composer install with the newest RC1 candidate.

It received the following error:
[Composer\Downloader\TransportException]                                     
  The "https://packages.magento.com/_packages/composer-1.0.2.zip" file could   
  not be downloaded: SSL operation failed with code 1. OpenSSL Error messages  
  :                                                                            
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify   
  failed                                                                       
  Failed to enable crypto                                                      
  failed to open stream: operation failed 

Any ideas of what causes this would be appreciated.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by eCommerceGorilla** [comment]
I know right, I mean running into an error only on the latest release candidate when the others betas run fine could have absolutely nothing to do with the update.
