### ISSUE TITLE
We don't have as many quantity as you requested, but we'll back order the remaining 1

### ISSUE THREAD

**Issue by imark73** [magento/magento2#23047]
Summary of the issue -
Hi. In the latest Magento 2.3.1 version, I'm getting a message in the basket - "We don't have as many quantity as you requested, but we'll back order the remaining 1." - See attached screenshot. I'm guessing this is a bug? It appears to be inserting the word "quantity" instead of the product name. It also causes the i18n translation not to work which is a problem for our shop which is in Swedish.
The problem did not exist in ver 2.2.5 that we had previously. 
![Clip 2019-05-29 091225](https://user-images.githubusercontent.com/47882051/58551276-f18a3e00-820f-11e9-8eea-52cc89b4f450.png)

### Preconditions
1. Magento 2.3.1
2. php 7.2

### Steps to reproduce
1. Set a product qty 0 and under advanced inventory to "Allow Qty Below 0 and Notify Customer"
2. In the front end, add the product to the cart
3. open the shopping cart to view it.

### Expected result
1. Beside the product, it should display 'We don\'t have as many "product name" as you requested, but we'll back order the remaining 1.'

### Actual result
1. Beside the product, it should display, the following text is displayed - 'We don't have as many quantity as you requested, but we'll back order the remaining 1."
2. The i18n translation is also not working, presumably for the same reason - "We don't have as many ""%1"" as you requested, but we'll back order the remaining %2.","Ej tillräcklig ""%1"", %2 st. restnoteras",module,Magento_CatalogInventory

I have done some digging and found that the message is generated from - 
\vendor\magento\module-catalog-inventory\Model\StockStateProvider.php, line 201 - 
$result->setMessage(
                                __(
                                    'We don\'t have as many "%1" as you requested, '
                                    . 'but we\'ll back order the remaining %2.',
                                    $stockItem->getProductName(),
                                    $backOrderQty * 1
                                )

**Comment by AlexWorking** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.1

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking, here is your [Magento instance](https://i-23047-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23047-2-3-develop.instances.magento-community.engineering/admin](https://i-23047-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AlexWorking** [comment]
Hello @imark73. Thanks for applying. We've been not able to reproduce Your issue. Could You please try to do it Yourself on a clear magento instance. You may use the one above (in the previous comment of the bot).

**Comment by imark73** [comment]
Hello @AlexWorking. Many thanks for looking into it - I've tested using your magento instance and can confirm that I do not get the same issue. I'll discuss it further with templatemonster who provided with version we have.

**Comment by AlexWorking** [comment]
You are welcome @imark73.

**Comment by Fresko112** [comment]
Hi Imark,

Did you find a solution. I am stuck at this for days.

Thanks in advance

**Comment by imark73** [comment]
> Hi Imark,
> 
> Did you find a solution. I am stuck at this for days.
> 
> Thanks in advance

Hi Fresko112
I did some digging in my history and found the support ticket on our templatemonster account. Here was the resolution - 
That text is outputted by "module-inventory-sales" Magento's core module:
"We don't have as many quantity as you requested, but we'll back order the remaining %1."
As you can see, it's not supposed to insert product's name here.
We've added that line translation to "/app/i18n/sv_SE/sv_SE.csv" file, so the translated line looks like:
"We do not have as many quantity as you requested, but we'll back order the remaining %1."

Hope that helps!
Regards, Mark

**Comment by Fresko112** [comment]
Thanks Imark, This helped me a lot. At least i can translate it the hard way in:
vendor/magento/module-inventory-sales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php 

For some reason the translaton dont work on this module. I even tried to edit the en_US.csv and my nl_NL.csv in:
public_html/vendor/magento/module-inventory-sales/i18n without any succes.

I also tried to translate through my themefile en translate module without any succes?

vendor/mageplaza/magento-2-dutch-language-pack/nl_NL.csv
app/design/frontend/Infortis/base/i18n/nl_NL.csv
and added this one to try:
app/i18n/nl_NL/nl_NL.csv

All without any visible changes.

I dont have any clue anymore.

But so much thanks for the help Imark. You helped me a lot.

**Comment by imark73** [comment]
Hi Fresko112

Glad to help, I've lost days too at times, tearing my hair out! 
I find that to get some language changes to show you have to do a very thorough clear and republish, even when Magento is in development mode and should regenerate more automatically. Here is the full belt and braces ssh routine I use:

rm -R pub/static/* var/cache/* var/page_cache* generated/metadata/* generated/code/* var/view_preprocessed/*
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy -f --area adminhtml sv_SE en_US
bin/magento setup:static-content:deploy -f --theme TemplateMonster/theme007 sv_SE de_DE en_US
bin/magento indexer:reindex
bin/magento cache:flush

I'm sure someone more expert than me would say some of the above is excessive/unecessary (and some things I've added when I've encountered other issues) but it has worked for me and is handy to copy and paste into pageant as a full clear, reset and republish routine..
Hope it helps! 🙂

**Comment by Fresko112** [comment]
Hi Imark,

I getting closer. I did the translation in the Theme 
app/design/frontend/Infortis/ultimo/i18n/nl_NL.csv

But what happens now is that it only translate the mini cart? Geting crazy by the hour??? See attached screenshot.

Should that be another module maybe?

Thanks again .

![cart2](https://user-images.githubusercontent.com/72803836/97006433-2a7f2d00-1540-11eb-90df-d396d37bdbe5.jpg)

**Comment by imark73** [comment]
Hi Fresko112

I just added a translation to the csv file, no other modifications.  To be honest I thought the original text was way too long for the amount of space there was for it in our theme, so I simplified the translation to just say - "Note: 1 pc(s) on backorder."
Here's the line from my Swedish langage csv file -

"We don't have as many quantity as you requested, but we'll back order the remaining %1.","Obs: %1 st. restnoteras",module,Magento_CatalogInventory

Regards, Mark

**Comment by Fresko112** [comment]
Hi Imark,

Spending my all day trying and testing but still same result. I give up. Its strange behaviour probably no one can declare.

I edited the 
vendor/magento/module-inventory-sales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php

So i need to be aware for updates from Magento but see no other solution.

Thanks for your help.

**Comment by imark73** [comment]
Hi Fresko112

Instead of modifying the files in the vendor folder, you should copy them to your theme first and then modify them.  The copies in your theme then override the vendor versions, and updates can therefore be installed to the vendor folder without breaking your installation.
See for example this discussion - https://stackoverflow.com/questions/42220806/magento2-how-can-override-vendor-module-catalog-to-magento-default-theme

**Comment by Fresko112** [comment]
Tried it but still same result. Stranfge but true.

Thanks for your help anyway.

**Comment by norgeindian** [comment]
I'm facing the same issue.
The text is not translated at all, no matter where we put the translation.
I debugged that a bit, and it seems as if the correct renderer in `\Magento\Framework\Phrase` is set too late.
So when I debug into `\Magento\InventorySales\Model\IsProductSalableCondition\BackOrderNotifyCustomerCondition::execute` for the first two runs, the only renderer is `\Magento\Framework\Phrase\Renderer\Placeholder`, which of course translates nothing.
Then, the breakpoint is hit again, and the error message is correctly translated.
But that's already too late, and so the translated text is not displayed any more.
So please be so kind and reopen this ticket.

**Comment by loneken79** [comment]
Hi,
For those who are stil searching for info on this issue for Magento prior 2.4.3
This have been resolved in 2.4.3 with this PR https://github.com/magento/magento2/pull/32326

For those who can't upgrade but wan't make this work (even if it meens changing `vendor` code) you can reproduce this change whit this commit https://github.com/magento/magento2/pull/32326/commits/14558892cc0aa06629e0e7b0a78276587fcc6d6d

Hopes it can help some of you
