### ISSUE TITLE
Can not find current CI setup, missing CI status and tests

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#23041]
### Summary (*)
Currently I am missing the CI status on the last commits and it is not clear where we can find the used tests and CI setup. It seems this is not public anymore?

**Comment by ghost** [comment]
Hi @DanielRuf
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by hostep** [comment]
@DanielRuf: if I understand you correctly, this is probably a similar request: https://github.com/magento/devdocs/issues/4495

**Comment by DanielRuf** [comment]
@hostep you are right.

**Comment by DanielRuf** [comment]
@hostep you are right. This is about the same.
