### ISSUE TITLE
Magento2 CSV product import automatic stock status broken

### ISSUE THREAD

**Issue by obukhow** [magento/magento2#23042]
### Preconditions

- PHP 7.1.26
- Magento CE 2.2.8 
- MySql 5.6.35

### Steps to reproduce

1. Create product with positive qty in stock and stock status "In stock"
2. Create an CSV file for import products
3. Set Quantity (field qty) to 0
4. import CSV

### Expected result

Product should have quantity 0 and status "Out of Stock"

### Actual result

Product has zero quantity but is "In Stock"

And otherwise out of stock product doesn't swtich to in stock after positive qty import.
Has been broken in #15950

**Comment by ktpl-rammohan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23042-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23042-2-3-develop.instances.magento-community.engineering/admin](https://i-23042-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23042-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23042-2-2-develop.instances.magento-community.engineering/admin](https://i-23042-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17151`, `MC-17152` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Can be closed as fixed and delivered https://github.com/magento/magento2/pull/24053
