### ISSUE TITLE
cms page not redirecting correctly after changing store view

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#23052]
I have these following cases for redirecting CMS pages to a different store view because of different language. In 2 different Magento 2 eshops using Magento 2.3.1 I'm facing this issue where the store switcher module redirects me to the homepage instead of the equivalent page.

### Preconditions (*)
1. Magento 2.3.1
2. 2 store views for 2 languages.
3. A CMS Page for each language with the same url-key but different entity_id

### Steps to reproduce (*)
Here's my database url rewrites as produced by the system for a cms page with a url key `oroi-xrhshs` which I duplicated for each language. I maintain the url-key as I would in Magento 1 to keep the redirection working. 

![image](https://user-images.githubusercontent.com/20220341/58561426-bd267a00-822f-11e9-8c6e-6af01545396e.png)

### Expected result (*)
When I use the store switcher, I see the equivalent page with the same url key. 

### Actual result (*)
I'm redirected to the homepage

From what I can see in the class 
`\Magento\UrlRewrite\Model\StoreSwitcher\RewriteUrl`

```php
      $oldStoreId = $fromStore->getId();
        $oldRewrite = $this->urlFinder->findOneByData([
            UrlRewrite::REQUEST_PATH => $urlPath,
            UrlRewrite::STORE_ID => $oldStoreId,
        ]);
        if ($oldRewrite) {
            $targetUrl = $targetStore->getBaseUrl();
            // look for url rewrite match on the target store
            $currentRewrite = $this->urlFinder->findOneByData([
                UrlRewrite::TARGET_PATH => $oldRewrite->getTargetPath(),
                UrlRewrite::STORE_ID => $targetStore->getId(),
            ]);
            if ($currentRewrite) {
                $targetUrl .= $currentRewrite->getRequestPath();
            }
        } else {
            $existingRewrite = $this->urlFinder->findOneByData([
                UrlRewrite::REQUEST_PATH => $urlPath
            ]);
            if ($existingRewrite) {
                /** @var \Magento\Framework\App\Response\Http $response */
                $targetUrl = $targetStore->getBaseUrl();
            }
        }
        return $targetUrl;
```

It's trying to find a match using the targetPath from the `$oldRewrite` which was found correctly in the rewrites. 

In my case the code above executes like this 
- Check if oldRewrite exists -> True 
- Read oldRewrite target path
- Find a currentRewrite with the old target path 
- currentRewrite does not exist in my example
- return the base url 

I can't see how this piece of code could find the correct URL for my case. I'm assuming that the `if($currentRewrite)` statement would need to have an `else` statement as a fallback mechanism that will detect the rewrite using the urlPath instead of the targetPath for the target store view. 

Something like this maybe?

```php
            if ($currentRewrite) {
                $targetUrl .= $currentRewrite->getRequestPath();
            }
            else{
                $currentRewrite = $this->urlFinder->findOneByData([
                    UrlRewrite::REQUEST_PATH=> $urlPath,
                    UrlRewrite::STORE_ID => $targetStore->getId(),
                ]);
                if ($currentRewrite) {
                    $targetUrl .= $currentRewrite->getRequestPath();
                }
            }
```

I'm also puzzled by this code if someone could explain to me the reason behind it if the oldRewrite is not found it's searching for an existing rewrite. If the existing rewrite is found, it's redirecting to the base url instead of the existing rewrite url path. 

```php
else {
            $existingRewrite = $this->urlFinder->findOneByData([
                UrlRewrite::REQUEST_PATH => $urlPath
            ]);
            if ($existingRewrite) {
                /** @var \Magento\Framework\App\Response\Http $response */
                $targetUrl = $targetStore->getBaseUrl();
            }
        }
```

**Comment by ioweb-gr** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr, here is your [Magento instance](https://i-23052-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23052-2-3-develop.instances.magento-community.engineering/admin](https://i-23052-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ioweb-gr** [comment]
Reproduced on demo instance. If you go to page https://i-23052-2-3-develop.instances.magento-community.engineering/test  and try to switch store view from "default store view" to "Gr"  you will get redirected to homepage
https://i-23052-2-3-develop.instances.magento-community.engineering/test

![2019-05-29_17-04-35](https://user-images.githubusercontent.com/20220341/58563516-f95bd980-8233-11e9-99d9-4a9a0344b168.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17098`, `MC-17099` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @ioweb-gr 
Thank you for your report. 

The issue has been fixed by internal Magento team in 2.3-develop branch
All related commit(s):

- e0a82d0c88458a0274ba6cd27ad0d0122a1b2023
- ecd3a1c64574e6abccc5f51af4cb984115eafedc
- 8375d0815f36d47152601cb47c8cf497f1e45695
- a86bd547d09b0187b9a7b71a60ef3127a0740bec
- 4205adc8c812abb2d4f67765a22e81502a98056e
- b82bdda674f7a222f7a471ff722015dbcf74f9af
- b287f41a7653945cf336326d9c486c7e71ab0ae0
- 308162eaf4d1b5a108d70aad741558dcfccde43e
- d7a9a4fb4612ebc2e35b7adc60db1d6c3d85bc51
- d62890f48a8289027d792ef941f4a020abfa2f2f

The fix will be available with the upcoming 2.3.4 release.

**Comment by ahmadwaliesipick** [comment]
I try above patches but not works for me, still redirecting to home page. i try at magneto 2.3.2

**Comment by dipakCrayon** [comment]
I also try above patches but not works for me in magento 2.3.3

**Comment by VZeroCool** [comment]
Any update on this ? I'm facing same issue with 2.3.3 @ioweb-gr @magento-engcom-team 
Any patches instead of upgrade our application ?

**Comment by ioweb-gr** [comment]
@VZeroCool unfortunately the magento patches didn't work for me either. I ended up staying on the original code sample I put up in the OP for a while.

**Comment by Axel29** [comment]
Hi,

The issue seems to still be present, even with the patches.

The problem is that even if we follow @ioweb-gr suggestion to use the urlPath (request_path), it wouldn't work if you try to translate the slug.

In my opinion, Magento should create URL rewrites for CMS pages as it does for Products and Categories, because right now a translate CMS page has absolutely no link to the original page...

**Comment by Sankarant** [comment]
Referred the code from magneto2.4. I have changed the code like below its working fine.

File: \Magento\UrlRewrite\Model\StoreSwitcher\RewriteUrl
Magento 2.3
```
if ($oldRewrite) {
  $targetUrl = $targetStore->getBaseUrl();
  // look for url rewrite match on the target store
  $currentRewrite = $this->urlFinder->findOneByData([
      UrlRewrite::TARGET_PATH => $oldRewrite->getTargetPath(),
      UrlRewrite::STORE_ID => $targetStore->getId(),
  ]);
  if ($currentRewrite) {
      $targetUrl .= $currentRewrite->getRequestPath();
  }
```
After changed
```
if ($oldRewrite) {
  $targetUrl = $targetStore->getBaseUrl();
  // look for url rewrite match on the target store
  $currentRewrite = $this->findCurrentRewrite($oldRewrite, $targetStore);
  if ($currentRewrite) {
      $targetUrl .= $currentRewrite->getRequestPath();
  }
```
Have to add new function in magento 2.3
```
/**
 * Look for url rewrite match on the target store
 *
 * @param UrlRewrite $oldRewrite
 * @param StoreInterface $targetStore
 * @return UrlRewrite|null
 */
  private function findCurrentRewrite(UrlRewrite $oldRewrite, StoreInterface $targetStore)
  {
    $currentRewrite = $this->urlFinder->findOneByData(
        [
            UrlRewrite::TARGET_PATH => $oldRewrite->getTargetPath(),
            UrlRewrite::STORE_ID => $targetStore->getId(),
        ]
    );
    if (!$currentRewrite) {
        $currentRewrite = $this->urlFinder->findOneByData(
            [
                UrlRewrite::REQUEST_PATH => $oldRewrite->getRequestPath(),
                UrlRewrite::STORE_ID => $targetStore->getId(),
            ]
        );
    }
    return $currentRewrite;
  }
```
--------------------------
Magento 2.3
```
$existingRewrite = $this->urlFinder->findOneByData([
    UrlRewrite::REQUEST_PATH => $urlPath
]);
if ($existingRewrite) {
    /** @var \Magento\Framework\App\Response\Http $response */
    $targetUrl = $targetStore->getBaseUrl();
}
```
After changed 
```
} else {
  $existingRewrite = $this->urlFinder->findOneByData([UrlRewrite::REQUEST_PATH => $urlPath]);
  $currentRewrite = $this->urlFinder->findOneByData(
      [
          UrlRewrite::REQUEST_PATH => $urlPath,
          UrlRewrite::STORE_ID => $targetStore->getId(),
      ]
  );
  
  if ($existingRewrite && !$currentRewrite) {
      /** @var \Magento\Framework\App\Response\Http $response */
      $targetUrl = $targetStore->getBaseUrl();
  }
```
