### ISSUE TITLE
styles-m.css and styles-l.css import duplicate CSS

### ISSUE THREAD

**Issue by QuentinFarizon** [magento/magento2#23050]
### Preconditions (*)
Magento 2.2.8 EE

### Steps to reproduce (*)
- Create a theme that inherits Magento/luma
- In a _theme.less file, add CSS conditionned by "& when (@media-common = true) {"
- Generate static assets for this theme 

### Expected result (*)
CSS is only present in styles-m.css, as per documentation https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/responsive-web-design/rwd_css.html

### Actual result (*)
CSS conditionned by media-common=true is duplicated in styles-m.css and styles-l.css

**Comment by krishprakash** [comment]
Hi @QuentinFarizonAfrimarket.
Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks.

**Comment by QuentinFarizon** [comment]
Hello @krishprakash 
Sorry, I misclicked, I filled the description

**Comment by Karlasa** [comment]
@QuentinFarizonAfrimarket 

_theme.less file should contain only variable overrides that are specific for child theme and not CSS. 
I think this can't be count as an issue if new theme is not extended correctly. 
Because of that will close this issue. Feel free to re-open this issue if you thing otherwise or if you have any other questions you can contact with me in community engineering slack. 

Cheers, 
Karla

**Comment by QuentinFarizon** [comment]
Hello @Karlasa thanks for your answer 
Where should the CSS go then ? 
Can you point me to some documentation on this ? 

Best regards,
Quentin

**Comment by Karlasa** [comment]
@QuentinFarizonAfrimarket 
I think what you are looking for is _extend.less file instead of _theme.less
Don't really have good reference for documentation but you can look Luma Theme files and follow the idea how they have extended Blank Theme :)

**Comment by QuentinFarizon** [comment]
Hello and thanks @Karlasa

Following your recommendation, I have modev my CSS definitions to _extends.less
But, they are still duplicated in both styles-l.css and styles-m.css 

What am I missing ?

**Comment by Karlasa** [comment]
@QuentinFarizonAfrimarket Haven't been able to reproduce that and don't have overview of how and what have you done under your theme but could guess that maybe there are some kind of typo or CSS in not correctly inside media selector. example: 
`
& when (@media-common = true) {
// code should go here
}
`
