### ISSUE TITLE
No way to move an image to another Media Storage folder

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2305]
![](https://mage2.pro/uploads/default/original/1X/9283b0ff8b2bfea51f3c730611b6e7882c36d222.png)

**Comment by eddielau** [comment]
@dfediuk We tried it and the "Delete File" button should show up after you click on an image. How did you get to this page? And what is the "storage configuration for media" under Stores > Configuration > Advanced > System?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/No-way-to-move-an-image-to-another-Media-Storage-folder/idi-p/44863).
