### ISSUE TITLE
Advanced Search Allows Search using Blank Spaces 

### ISSUE THREAD

**Issue by RonakParmar** [magento/magento2#23055]
Advanced Search allows search by entering only blank spaces in all the fields of the form and it will generate blank search result. which is not correct behavior of search result.
### Preconditions (*)

1. Magento 2.3.x
2. PHP 7.1

### Steps to reproduce (*)

1. Click on Advanced Search link in the footer 
2. Enter only blank spaces in any/all fields 
3. Click on Search button

### Expected result (*)

1. It should not allow to search if we enter only blank spaces. 
2. It should show validation message on click of Search button.
3. It should not generate search result of blank spaces.

### Actual result (*)

1. It is allowing to search using blank spaces. 
2. Please see below screenshot of Advanced Search Form and Search Result Page.
![advanced-search-form](https://user-images.githubusercontent.com/6551912/58568157-5d40cb00-8251-11e9-9cc3-74d7b7d5963d.png)
![advanced-search-result](https://user-images.githubusercontent.com/6551912/58568163-60d45200-8251-11e9-9cc5-d6582523bfd0.png)

**Comment by AlexWorking** [comment]
Works correctly only with price fields.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17100`, `MC-17101` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Can be closed as fixed and delivered https://github.com/magento/magento2/pull/23059
