### ISSUE TITLE
Product Import via CSV Fails to Update Existing Product Data

### ISSUE THREAD

**Issue by nfourteen** [magento/magento2#23062]
### Preconditions
1. Magento 2.3.1

### Steps to reproduce
1. Create a configurable product on a new Magento instance
2. Navigate to `System > Data Transfer > Export` and export the **Products** entity
3. Open the CSV file and update prices
4. Navigate to `System > Data Transfer > Import` and import the updated CSV file using the **Import Behavior** Add/Update.

### Expected result
1. The product prices should be updated to the new values.

### Actual result
1. On import, `Duplicates found in column names:` error is thrown. 
    - After some digging, this error is thrown because the `url_key` column exists within the CSV data.
2. Delete the `url_key` column and retry **Import**.
3. Another error is thrown, stating `1. Url key: 'test.html' was already generated for an item with the SKU: '0001'. You need to specify the unique URL key manually in row(s): 19`. 
    - Digging further, the `url_key` is generated using the value from the `name` column if the `url_key` column doesn't exist. 
4. Delete the `name` column and retry **Import**.
5. Another error is thrown, stating `Please make sure attribute "name" is not empty. in row(s): 19`.

The note under the **Import Behavior** field states: `New product data is added to the existing product data for the existing entries in the database. All fields except sku can be updated.`, but all fields can't be updated due to the `url_key` validation and auto-generation logic.

**EDIT**
To propose a solution to generate a discussion, I think the `url_key` logic should be:

1. Upon import, if the SKU doesn't already exist in the database and the `url_key` column doesn't exist in the CSV, then the `url_key` value can be auto-generated as it is currently using the column `name` value.
2. Upon import, if the SKU already exists in the database and the `url_key` column doesn't exist in the CSV, then the `url_key` should not be auto-generated and it's value should not be updated.
3. Upon import, if the SKU already exists in the database and the `url_key` column exists in the CSV, then the value should be updated to the one contained in the CSV if the CSV and database values are different.
4.  Upon import, if the `url_key` column exists in the CSV or is auto-generated, but the `url_key` exists for another SKU, then the `1. Url key: 'test.html' was already generated for an item with the SKU: '0001'. You need to specify the unique URL key manually in row(s): 19` error should be thrown.

**Comment by AlexWorking** [comment]
Hello @nfourteen. Thanks for reporting. We've been not able to reproduce Your issue on a clean instance of magento. Could You please try to install a vanilla instance of the latest version and try to reproduce on that. It's quite possible that the issue has already been fixed.

**Comment by nfourteen** [comment]
@AlexWorking It was a clean install...the issue was the CSV editor was removing the padded zeros from the SKU and Magento was considering that a new SKU. I'll close this issue as it's not a Magento problem.
