### ISSUE TITLE
main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cps.row_id' in 'where clause', query was: SELECT `cps`.* FROM `cms_page_store` AS `cps` WHERE (cps.row_id = ('66'))

### ISSUE THREAD

**Issue by olgaIskra** [magento/magento2#23060]
### Preconditions (*)
Magento version 2.3.1

### Steps to reproduce (*)

system.log get this error message, after click on the cms-page, because: 

vendor/magento/module-cms/Model/ResourceModel/Page.php
has procedute:

/**
     * Get store ids to which specified item is assigned
     *
     * @param int $pageId
     * @return array
     */
    public function lookupStoreIds($pageId)
    {
        $connection = $this->getConnection();

        $entityMetadata = $this->metadataPool->getMetadata(PageInterface::class);
        $linkField = $entityMetadata->getLinkField();

        $select = $connection->select()
            ->from(['cps' => $this->getTable('cms_page_store')], 'store_id')
            ->join(
                ['cp' => $this->getMainTable()],
                'cps.' . $linkField . ' = cp.' . $linkField,
                []
            )
            ->where('cp.' . $entityMetadata->getIdentifierField() . ' = :page_id');

        return $connection->fetchCol($select, ['page_id' => (int)$pageId]);
    }

$linkField  get value = row_id, but table cms_page_store don't have column row_id.

Please, fix this bug!!!

Best wishes, Olga

**Comment by chohanbhagchand** [comment]
I am working on this at #dmcdindia19”

**Comment by ghost** [comment]
Hi @olgaIskra, thank you for you report, this issue has already fixed in 2.3-develop branch, and will be available on 2.3.2 release
