### ISSUE TITLE
paypal is not giving lastname in express checkout

### ISSUE THREAD

**Issue by netzwelt-nishu** [magento/magento2#23061]
### Preconditions (*)

1. magento version 2.3.0
2. Express checkout

### Steps to reproduce (*)

1. Place a order on magento using express checkout in guest mode 
2. After successful order, when you check you find order details are  correct.
3. But in DB we found that, last name in billing and shipping details are NULL.
### Expected result (*)

1. Last name should not be NULL and it should be filled with the customer last name
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23061-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23061-2-3-develop.instances.magento-community.engineering/admin](https://i-23061-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@netzwelt-nishu - I have verified this issue in my Magento 2.3 instance database.
Last name is not displayed on shipping and billing address details after placed order throw the Paypal account.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17148` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bartlomiejsz** [comment]
This has been fixed by [02e18bf2dfe10e9a9513fa578c9108a5a9b11475](https://github.com/magento/magento2/commit/02e18bf2dfe10e9a9513fa578c9108a5a9b11475#diff-1a75129a8ba75d322070c8e8920eab3d)
