### ISSUE TITLE
Minor LESS Variable Issue 

### ISSUE THREAD

**Issue by DeviateDefiant** [magento/magento2#2306]
Deploying static content:

    Compilation from source:
    frontend/Magento/luma/en_US/css/print.less
    variable @modal-slide-header__padding-vertical is undefined in file /var/view_preprocessed/css/frontend/Magento/luma/en_US/css/source/_theme.less in _theme.less on line 254, column 37
    252| //  Modal popup
    253| @modal-action-close__font-size: @font-size__base;
    254| @modal-slide-action-close__padding: @modal-slide-header__padding-vertical @modal-popup__padding;
    255|
    256| //  Checkout tooltip icon
    257| @checkout-tooltip-icon__font-size: 21px;>

Removing the variable it'll compile fine.

**Comment by zanilee** [comment]
Related issue #2273

**Comment by dfediuk** [comment]
My fix for a similar problem with the frontend product gallery: https://mage2.pro/t/188

**Comment by dfediuk** [comment]
My universal fix for all the «variable @modal-slide-header__padding-vertical is undefined» problems: https://mage2.pro/t/193

**Comment by MomotenkoNatalia** [comment]
@DeviateDefiant Internal ticket MAGETWO-45071 is closed and delivered to mainline. Please, let us know if you still have an issue.
