### ISSUE TITLE
Using Event : checkout_cart_product_add_after Adding "additional_options" to Quote Item is not validating stock when adding product to the Cart

### ISSUE THREAD

**Issue by rselvakumar29** [magento/magento2#23075]
### Preconditions (*)

1. Version 2.3

### Steps to reproduce (*)

1. Create Event checkout_cart_product_add_after
2. Update the Quote Items "additional_options" in Observer 

$parentItem = $observer->getEvent()->getQuoteItem();

$additionalOptions = [];

$additionalOptions[] = array(
'label' => "Some Label ",
'value' => rand(99,9999),
);

$parentItem->addOption(
[
'product_id' => $parentItem->getProductId(),
'code' => 'additional_options',
'value' => $this->_serializer->serialize($additionalOptions)
]
);
$parentItem->save();

3. In storefront, do add to cart and check Stock Validation.  

### Expected result (*)

1.  Available Qty is 3. But I can able to add more with different additional_option

### Actual result (*)

1.  Available Qty is 3. Trying to add more that 3, Need to show an Error message and Prevent add to cart

**Comment by orlangur** [comment]
Event payload must not be changed in observers.
