### ISSUE TITLE
Magento 2.3 Table rate shipping charge with free cart price rule for Configurable Product

### ISSUE THREAD

**Issue by krishnamsgr** [magento/magento2#23078]
Hai,

I have my ecommerce in magento 2.3 which has configurable product with attribute checkout type.
There are 2 option for checkout type home delivery and Pay and collect.
I uploaded table rate shipping weight vs destination. I created free cart price rule if customer choose product with pay and collect then shipping free. other wise it will take shipping from csv.

It is working only after i need to save multiple times product in back end.
when i create a new configurable product with 2 or 3 associated product then on first save shipping charge not appears. Only after save again and update then only correct shipping happening. 
i checked all core code. i can't find any solution. 

Any one has solution then please help me

**Comment by ghost** [comment]
Hi @krishnamsgr 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
