### ISSUE TITLE
Index Management page Mass Action no dropdown in Chrome (OSX)

### ISSUE THREAD

**Issue by neverovsky** [magento/magento2#2307]
Index Management page Mass Action clickable but no drop down in Chrome MacOSX El Capitan (46.0.2490.80 (64-bit)) but in In Firefox works fine 
screen resolution : 1920x1080

![index management - tools - system - magento admin 2015-11-09 16-15-42](https://cloud.githubusercontent.com/assets/8119716/11034525/3c0b7abe-86fd-11e5-898b-7c7b7341ae26.png)

**Comment by MomotenkoNatalia** [comment]
Hi @neverovsky ! Thanks for reporting this issue! Internal ticket MAGETWO-45546 is closed and delivered to mainline. Please, let us know if you still have an issue.
