### ISSUE TITLE
Select billing address lost on update with shipping address that cant be use for billing

### ISSUE THREAD

**Issue by manuelcanepa** [magento/magento2#23070]
### Summary (*)
I have a module of "pickup stores" that set the pickup store address as the shipping address, this address has the canUseForBilling method set to false, so the first time on billing step, is required that the customer set the billing address. For guest customers, this is ok, but, for customer with address on his address book, when click on update button, the address information show the shipping address information and customer can't change it because the checkbox "My billing and shipping address are the same" is invisible.

### Examples (*)
- Select a shipping address that cant be used for billing

### Proposed solution
- Don't show the shipping information as billing information when shipping information can't be used as billing
- Show the address selector when update and shipping address can't be used as billing address

**Comment by ghost** [comment]
Hi @manuelcanepa thank you for you report, it will be proceed faster if you move this to https://github.com/magento/community-features
