### ISSUE TITLE
Autorize.net order not being cancelled on payment rejected

### ISSUE THREAD

**Issue by lucasvm** [magento/magento2#23087]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7

### Steps to reproduce (*)

1. Install lastest patch with Autorize new signature.
2. Place order with a invalid credit card
3. Card will be rejected
4. Order should be cancelled, but instead is created and processing.

### Expected result (*)

1. On rejected payments from autorize the order is being created and processing, it should be cancelled
Sites are able to properly process valid cards but failed transactions do not get canceled as expected

### Actual result (*)

1. The order is being created and procesed.

**Comment by orlangur** [comment]
If payment was rejected you can create a new invoice, isn't it?

**Comment by lucasvm** [comment]
No, sorry, the order should be cancelled , as others methods works, because I'm using shipstation to manage the shipments and it will send and approve if Magento does, the order needs to be cancelled when payment is rejected , is this a bug?

**Comment by lucasvm** [comment]
I have found the issue here on github reported few days ago, seems to be a patch, https://github.com/magento/magento2/issues/22373

You can close, i will follow there.
