### ISSUE TITLE
B2B Shared Catalog Extremely Slow Loading.

### ISSUE THREAD

**Issue by rob-gonz** [magento/magento2#23088]
### Summary (*)
Attempting to associate products to a shared catalog after enabling the sharedCatalog results in HTTP Timeout Errors (504) (Catalog -> shared Catalogs -> Add Shared catalog | Set Pricing and Structure).  If the Timeout is increased on the web server and load balancers to 10+ minutes the page will eventually load after 10min. Once loaded, clicking on a category to associate the products within the category results in another round of waiting 10+ minutes.  Sometimes it just does not finish (1-hour plus).  After a refresh, the category is either fully or only partially associated.

### Examples (*)
You need a lot of data to reproduce the issue to the extent we are experiencing it, but its effects can still felt using the EE sample product catalog.
#### Setup
- Magento 2.3.x EE
- B2B modules installed and all features enabled
- Split Databases
- 70k + products
- 13k + categories
- multiple websites and stores
- Shard Catalog enabled

#### Steps:
- Go to Admin -> Catalog -> shared catalogs -> 'Select' [existing catalog] -> Set Pricing and Structure.
- wait..... (probably get a 504 or  'problem was encountered' pop up)
- Select a 2nd or 3rd level category
- wait..... (probably get a 504 'problem was encountered' pop up)

This makes using the shared catalog functionality borderline impossible for a standard user.  We expect to have upwards of 30+ shared catalogs.  This makes things very difficult/impossible to manage.

### Proposed solution
* Change how the category list is acquired for this page.  Do it the same way it is done for Admin -> Catalog -> Categories
* Do not worry about live updating the products displayed on the right when associating products/categories to a shared catalog. This just slows things down even more.
* (Improvement to above point) Separate the category association from the product association.  They don't need to be on the same page and only adds to page/request weight.
* Actions like selecting a category to associate has an immediate effect and causes the page to take additional time to register that selection. The only purpose of this is to change the visible status of products on the right.  This is inefficient for large catalogs.  Allow the user to check all the boxes they want and process everything after the request is submitted.

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Magento Open Source, isn't it?

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.

**Comment by rob-gonz** [comment]
@orlangur, A Magento project manager has said to report issues here.  See https://github.com/magento/magento2/issues/10439#issuecomment-320287006.  

Where are we to discuss EE issues **in the open**  so others may learn too. If this is not the best place - please direct me to the correct forum to discuss EE.  Many questions go unanswered or unacknowledged in the community.magento.com forum.

**Comment by orlangur** [comment]
@rob-gonz did you notice the date? It is applicable for Release Candidate phase only (`2.2-RC issues `).

**Comment by rob-gonz** [comment]
@orlangur, sure that's fine.  I still don't know, where are we to discuss EE code issues in the open with the magento team so others may learn too.

**Comment by orlangur** [comment]
@rob-gonz there are some programs like partners/insiders intended exactly for this. @sidolov could you please give an accurate answer?
