### ISSUE TITLE
Shopping cart layout break when enter long coupon

### ISSUE THREAD

**Issue by renard123** [magento/magento2#23093]
Shopping cart layout break when enter long coupon.

### Preconditions (*)
magento 2.2

### Steps to Reproduce(*)
1. Go to shopping cart
2. Enter coupon code like ""!!!!!!!!!!!!!!!!!!aaaaaaaaaaaaaaaaaaaaaaaaaaBBBBBBbbbbbb####################^^^^^^^^^^^^^^^^^^^^nnnnnnnnnnnnnnnnnnnnnnnnnDDDDDDDDDDDDDDDDDDDD%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%""
3. Apply coupon code
4. Review the layout of cart

### Expected result (*)
Cart layout should not be break.

### Actual result (*)
![coupon code issue](https://user-images.githubusercontent.com/50658701/58748189-5c4aac00-8492-11e9-89d3-a73e2c1f4f3e.png)

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23093-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23093-2-2-develop.instances.magento-community.engineering/admin](https://i-23093-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23093-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23093-2-3-develop.instances.magento-community.engineering/admin](https://i-23093-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17173`, `MC-17174` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by orlangur** [comment]
There is nothing to fix here, actually. Such coupon code is obviously not realistic.
