### ISSUE TITLE
Swagger definition documentation and result mismatch

### ISSUE THREAD

**Issue by nettrix** [magento/magento2#2310]
The swagger documentation returns camel case names for properties; the actual response in json returns underscore separated fields. This mismatch causes java client generation based on swagger definition to fail due to deserialization issues based on that mismatch.

Example:
GET /V1/categories

Reponse as documented:
`catalog-data-category-tree-interface {
...
  "childrenData": [
    {}
  ]
}
`

Actual response:
`...
"children_data":[
{}
]
}
`

**Comment by vrann** [comment]
Hi, @nettrix 
I believe right now WebApi framework for the REST requests support both formats, "children_data" and "childrenData". Do you see any issues when send a request to REST API?

**Comment by nettrix** [comment]
Well, it's about the response (so only GET actions for now). There underscore is used, and when you generate a client using the swagger client generator you have a problem cause the client expects childrenData to be returned. Or is there a way (that i might have missed) to specify what naming conventions to use in the response when performing a GET on a resource?

**Comment by vrann** [comment]
I see, generated client validates response and expects to have childrenData, while both children_data and childrenData are acceptable by Magento (though only children_data recommended).

It looks like an issue

**Comment by wienczny** [comment]
Any update on this issue?

**Comment by Robar666** [comment]
Any update on this issue?

**Comment by magento-engcom-team** [comment]
@nettrix, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by cscd98** [comment]
This is still an issue, my JS framework is expecting camel case in it's returns but Magento returns underscores.

Was there a workaround for this?
