### ISSUE TITLE
Payment Failed Email not working

### ISSUE THREAD

**Issue by niravkrish** [magento/magento2#23103]
I made a couple of tests and in my environment, trying a couple of different payment methods, Magento never run those controllers. So, even if the payment fails, the email notification is not sent.

This behaviour is very different from Magento 1, where the merchant receives effective notifications and can monitor checkout/payment problems.

### Preconditions (*)

1. Magento CE 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

1. Enable Cybersource payment method (or any other that require configuration) without configuring it
2. Add a product to cart and proceed to checkout
3. select Cybersource and input fake credit card information
4. get the "An error occurred on the server. Please try to place the order again." error message at checkout

### Expected result (*)

1. the merchant should receive a failed payment email notification

### Actual result (*)

1. no emails are sent

**Comment by krishprakash** [comment]
Hi @niravkrish.
I'm closing this issue as it's duplicate to #11347
