### ISSUE TITLE
Validation form "invalid-form" event duplicated

### ISSUE THREAD

**Issue by apomili** [magento/magento2#23108]
When you hit "submit button" on a non filled form, multiple submit event error are triggered (listenFormValidateHandler).

The lines in /lib/web/mage/validion.js are extecuted multiple times  and the page jump if you scroll before all the animations are completed. (jQuery create a queue of animations, that scroll one by one to firstActive, but only the first animation is visible).
```
            if (firstActive.length) {
                $('html, body').animate({
                    scrollTop: firstActive.offset().top
                });
                firstActive.focus();
            }
```

_I suppose, beside the scroll bug, all the logic is intended to run once._

### Preconditions (*)
Magento 2.2.8
Luma Theme

### Steps to reproduce (*)
- Go on the create account page
- Leave the form empty and click "Create an account".
- When the page has landend to the invalid input try to scroll and the page jump until all the animations are completed

### Expected result (*)
The page stop to scroll after positioning to the invalid input

### Actual result (*)
The page continue to scroll until the jquery animation queue is completed

**Comment by AlexWorking** [comment]
Hello @apomili, This issue is seemingly fixed in 2.3-develop version. Could You please try to reproduce Your issue on it asking for a clear instance from the bot by just leaving a comment "@magento give me 2.3-develop instance" (without quotes). Thank You.

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AlexWorking, here is your [Magento instance](https://i-23108-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23108-2-3-develop.instances.magento-community.engineering/admin](https://i-23108-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by apomili** [comment]
Hi @AlexWorking, I just tried to reproduce the problem in the istance  above.
Seems to be fixed cause I don't see animations on the page at all (despite of the code).
I don't know if listenFormValidateHandler is triggered multiple times.

**Comment by AlexWorking** [comment]
Ok @apomili, then for now we are supposed to close the issue according to step 4 of our issue confirmation workflow You can find above on this page:
![Supposed](https://user-images.githubusercontent.com/27814011/58807236-5edb0c00-8620-11e9-8167-fcd485b8a982.png)
