### ISSUE TITLE
The attribute option should be sorted alphabeticaly on saving - Magento 2.3

### ISSUE THREAD

**Issue by rohankatkar** [magento/magento2#23109]
### Description (*)
The attribute option should be sorted alphabetically on saving - Magento 2.3

### Expected behavior (*)
When adding the option for the attribute it should be saved and sorted alphabetically for
following are the scenarios. 

A) When the value of "Use Product Image for Swatch if Possible"  =  Dropdown
B) When the value of "Use Product Image for Swatch if Possible"  =  Text Swatch
C) When the value of "Use Product Image for Swatch if Possible"  =  Visual Swatch

### Benefits
- Currently, Magento provides the provision to sort the option by drag & drop. 
- E.g If there are 200 color attribute values with visual swatches, and when we need to add new swatch, it will be hectic to check swatches options. 
- So if there are large no of options present for any attribute then it becomes easy before adding options.

**Comment by orlangur** [comment]
Hi @rohankatkar,

> The attribute option should be sorted alphabetically on saving - Magento 2.3

Nope.

Linked SO question seems to be a buggy implementation.
