### ISSUE TITLE
Paypal configurations missing at admin 

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#23115]
### Preconditions (*)

1.  Magento Ver. 2.3.1
2. Apache 2.4.37, Nginx 1.12.2 PHP 7.2

### Steps to reproduce (*)

1. Upgrade to 2.3.1 from 2.3 CE using composer

### Expected result (*)

![paypal avaialble](https://user-images.githubusercontent.com/36662131/58857778-a36bb380-86c3-11e9-9ed3-a1497bd933ba.png)

### Actual result (*)

![paypal missing](https://user-images.githubusercontent.com/36662131/58857814-b41c2980-86c3-11e9-8f11-419fbe5105e0.png)

**Don't know when it get disappear It was there when I initially setup sandbox paypal but after upgrade its missing and wanted to push store to production :(**

**Comment by ghost** [comment]
Hi @VZeroCool thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/22243
