### ISSUE TITLE
registration.php of non-composer modules does not seem to be loaded

### ISSUE THREAD

**Issue by amenk** [magento/magento2#2311]
When installing by cloning https://github.com/magento/magento2-community-edition and `composer install`, the `registration.php` of custom modules not pulled  via composer does not seem to work.

Details & workaround see here: http://magento.stackexchange.com/a/89446/81

Actually I am not sure how to fix that, because I am unsure where the `composer.json` files for the ZIPs your provide come from, so no Pullrequest here..

**Comment by alankent** [comment]
Have you seen https://github.com/magento/magento2/blob/develop/app/etc/NonComposerComponentRegistration.php ?  This is how Magento finds all the packages. So when you say "custom modules", is it in one of the paths this script will find?

**Comment by amenk** [comment]
Yes it is. Just this file you mention is not loaded in my setup.
So this looks like a bug to me which can be fixed by adding

"autoload": {
    "files": [
        "app/etc/NonComposerComponentRegistration.php"
    ]
},
to your composer.json

**Comment by vrann** [comment]
Currently it is in the composer.json
https://github.com/magento/magento2/blob/develop/composer.json#L229
Is it different for you?

**Comment by amenk** [comment]
Yes. See above how I installed.

**Comment by vrann** [comment]
Thanks, now I see the issue. This will be fixed as a bug.

**Comment by amenk** [comment]
Seems to be fixed https://github.com/magento/magento2-community-edition/blob/master/composer.json#L42
