### ISSUE TITLE
Update blank gender it does not saved in direct edits from customer grid

### ISSUE THREAD

**Issue by renard123** [magento/magento2#23128]
Update blank gender it does not saved in direct edits from customer grid.

Whereas when update with Male/Female gender it works fine
Also it works fine when edit customer.

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Go to Admin
2. Customers > All Customers 
3. From customer grid update any customer which already have value like male/female to blank
4. Click on save
5. Display success message like "You have successfully saved your edits" but it does not saved.

### Expected result (*)
Gender update should working fine from direct edits.

### Actual result (*)
![gender actual](https://user-images.githubusercontent.com/50658701/58931123-0caefd80-877c-11e9-8036-c89e1ee54a61.jpg)

**Comment by renard123** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @renard123, here is your [Magento instance](https://i-23128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23128-2-3-develop.instances.magento-community.engineering/admin](https://i-23128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
I reproduced it on given instance.

**Comment by renard123** [comment]
Reproduced it on given instance.

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23128-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23128-2-2-develop.instances.magento-community.engineering/admin](https://i-23128-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17258`, `MC-17259` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
I am working on it.

**Comment by sdzhepa** [comment]
The internal Magento team is working on this issue now.
The fix should be delivered by internal Pull Request in the scope of `MC-17259`

**Comment by magento-engcom-team** [comment]
Hi @renard123, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [27b9d8c0640311096fafb834e312c9e0eef18206](https://github.com/magento/magento2/commit/27b9d8c0640311096fafb834e312c9e0eef18206)
 - [c1937ed4c29c01944f13c244f576da8ad97c263d](https://github.com/magento/magento2/commit/c1937ed4c29c01944f13c244f576da8ad97c263d)
 - [f29afc8e9f8b118bc3c8918f1018228020747b8b](https://github.com/magento/magento2/commit/f29afc8e9f8b118bc3c8918f1018228020747b8b)

The fix will be available with the upcoming `2.3.5` release.
