### ISSUE TITLE
Media Browser loses PNG transparency for the thumbnails

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2312]
![](https://mage2.pro/uploads/default/original/1X/cc37b8d557fad21fd9b03b9dff753a69ea2493fc.png)

**Comment by MomotenkoNatalia** [comment]
@dfediuk Thanks for reporting this issue!
Internal ticket MAGETWO-45264.

**Comment by Bartlomiejsz** [comment]
Not only for the thumbnails. When you add .png image to wysiwyg attribute using '{{media url="..."}}', it is generated with white background, this is definitely wrong.

**Comment by kassner** [comment]
#7307

**Comment by maghamed** [comment]
gonna be fixed as soon as PR [#7307](https://github.com/magento/magento2/pull/7307) would be merged into mainline

**Comment by okorshenko** [comment]
Closing this issue. PR https://github.com/magento/magento2/pull/7307 was delivered to develop branch.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-69238
