### ISSUE TITLE
Shopping cart Labels are never shown in cart

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2313]
When adding a shopping cart rule (any type, in this case free shipping with coupon) the lable is not shown in the cart or in the checkout.

![2015-11-10_14h15_52](https://cloud.githubusercontent.com/assets/13572447/11063297/d7fff360-87b5-11e5-87cf-c24d18bc56dc.png)

![2015-11-10_14h15_05](https://cloud.githubusercontent.com/assets/13572447/11063305/edb79406-87b5-11e5-9e17-ad27a1a03e67.png)

![2015-11-10_14h16_19](https://cloud.githubusercontent.com/assets/13572447/11063306/f0ba774a-87b5-11e5-9292-1919e4966d00.png)

**Comment by vil11** [comment]
@SidneyBilliet, thanks for reporting the issue!
Internal ticket **MAGETWO-48435**.

Dmytro Vilchynskyi, M2 QA engineer.

**Comment by lucscu** [comment]
2 years bug?

**Comment by magento-engcom-team** [comment]
@SidneyBilliet, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
