### ISSUE TITLE
Sales rule condtions are duplicated when data validation error occurs

### ISSUE THREAD

**Issue by JaromirMullerQuanti** [magento/magento2#23137]
### Preconditions (*)

1. 2.3

### Steps to reproduce (*)

1. Create any sales rule with conditions like:
  - If ALL  of these conditions are TRUE
    - If an item is FOUND  in the cart with ANY  of these conditions true:
      - At least any condition (I used category is one of ...)
    - If ALL  of these conditions are TRUE
      - At least any condition (I used Subtotal  greater than 0)
2. Save rule
3. Simulate error behavior by adding an error into Magento\Rule\Model\AbstractModel::validateData , the method shoud return any number of errors like `[__('any error')]`
4. Try to save rule again. You should receive 'any error' message and rule conditions should be duplicated which is faulty. See:

### Expected result (*)

1. Rule conditions should not by duplicated. Rule conditions should be in same state as before saving rule.

![Promotions Marketing Magento Admin CORRECT](https://user-images.githubusercontent.com/49402296/58946257-c78fc900-8785-11e9-9c07-79dd583caa30.png)

### Actual result (*)

1. Rule conditions are duplicated, see attached screenshot.

![Promotions Marketing Magento Admin ERROR](https://user-images.githubusercontent.com/49402296/58946288-d4acb800-8785-11e9-8803-3d00e32ab49a.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23137-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23137-2-3-develop.instances.magento-community.engineering/admin](https://i-23137-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by JaromirMullerQuanti** [comment]
Please let me know if you need any further information or clarification. I'm not able to replicate issue in admin panel without possibility to raise validation error.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17564`, `MC-17565` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23137-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23137-2-3-develop.instances.magento-community.engineering/admin](https://i-23137-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by keyurshah070** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
Hi @JaromirMullerQuanti. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23758` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
