### ISSUE TITLE
Compiled Config cache always enable

### ISSUE THREAD

**Issue by devamitbera** [magento/magento2#23133]
### Preconditions (*)

1. Magento 2.3.0
2. Magento 2.3.1

### Steps to reproduce (*)

1. Get Magento 2.3.x according to [devdocs](https://devdocs.magento.com/guides/v2.3/install-gde/install-quick-ref.html#get-the-magento-software)
2. Install Magento according to [devdocs](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-install.html)
3. Run once `bin/magento setup:di:compile`
4. Run `bin/magento cache:status` to check statuses
5. Run `bin/magento cache:disable` to disable caches or `bin/magento cache:disable compiled_config` to disable compiled_config cache only
6. Run `bin/magento cache:status` to check statuses

### Expected result (*)

1. When run `php bin/magento cache:disable compiled_config` .Compile cache status should be changed to  Disabled if it previously enabled.

2.When we run Cache status ,the status should be show as disabled. 

### Actual result (*)

1. When Run Compile cache disable command .Output Show  : `Changed cache status:compiled_config: 1 -> 0` . Means Cache status is changed.
 
2. when Run command `php bin/magento cache:status` for  getting current cache status.It is showing cache compile enable. `compiled_config: 1`

![Screenshot from 2019-06-05 13-48-10](https://user-images.githubusercontent.com/6008488/58941407-5528e400-8799-11e9-8f48-15a1b1c96cfa.png)

**Comment by devamitbera** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.1 release

**Comment by magento-engcom-team** [comment]
Hi @devamitbera. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @devamitbera, here is your [Magento instance](https://i-23133-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23133-2-3-develop.instances.magento-community.engineering/admin](https://i-23133-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devamitbera** [comment]
Hi @magento-engcom-team com, i need ssh access to test this  issue.

**Comment by shikhamis11** [comment]
@devamitbera I checked on magento 2.3.1 I am not able to reproduce the issue . It's working fine

**Comment by devamitbera** [comment]
@shikhamis11 ,  Have you check using Command line. Am i right?

**Comment by devamitbera** [comment]
@shikhamis11 , seems it is fixed at 2.3-develop branch. Thanks for you all test.

**Comment by choussamaster** [comment]
The bug is reproductible on magento 2.3.3 fresh installation
compiled_config cache can't be disabled nether by cli or via backoffice
![image](https://user-images.githubusercontent.com/750352/69527457-a5287c80-0f6c-11ea-95c4-fe0eef19abb9.png)

![image](https://user-images.githubusercontent.com/750352/69527513-bd000080-0f6c-11ea-82f5-2f6ea6e7ce74.png)

**Comment by maksymMezhensky** [comment]
This bug is also reproducible on version magento 2.3.2

![image](https://user-images.githubusercontent.com/47173539/69634396-c798c380-105a-11ea-908e-48f85e7c6fbd.png)

**Comment by choussamaster** [comment]
I think the bug is happening at default mode, switching to developer mode fix it

**Comment by andrewbess** [comment]
> I think the bug is happening at default mode, switching to developer mode fix it

This problem is reproduced in developer mode too.
Take a look at my screenshot
<img width="740" alt="m2-contrib  projectsmageneocontributionm2-contrib  -  magento-contriblibinternalMagentoFrameworkAppCacheState php 2019-11-26 22-11-52" src="https://user-images.githubusercontent.com/10788564/69669649-f171da80-109a-11ea-91b5-a55e9fec1e32.png">

**Comment by shikhamis11** [comment]
hello @choussamaster , @maksymMezhensky ,@andrewbess 
I checked this on magento 2.3.-develop and 2.3.3 versions. I am not able to reproduce this issue with the steps written in description . 
Please check if it requires any additional steps to reproduce this issue please update description too

**Comment by andrewbess** [comment]
Hello @shikhamis11 
Ok, I have already changed steps for reproduce in description of this issue.
Also, please take a look at my gif
![screencast 2019-11-27 17-20-03](https://user-images.githubusercontent.com/10788564/69736316-eec6c200-113a-11ea-9f9f-d8b65fd78131.gif)
Running `bin/magento setup:di:compile` is required

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29232` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
I am working on this issue at #MM20IN

**Comment by Genaker** [comment]
This issue also affected by permissions If app/etc is read only and you cache config_compiled manually. It will not switch back to 1; Basically disable feature works however after any Magento command or page execution it switches back to 1. It reproduces on 2.3.4 version.

**Comment by Genaker** [comment]
Seams it is related to what object manager APP uses. If Config/Compiled config_compiled is always enabled and generates generated metadata folder. 

Depending on whether or not one of the compilers has been run before, the Magento application consumes the compilation using one of the following classes:

Magento\Framework\Interception\ObjectManager\Config\Compiled, which is used if global.ser exists.

Magento\Framework\Interception\ObjectManager\Config\Developer, which is used if global.ser does not exist.

This class is slower than Magento\Framework\Interception\ObjectManager\Config\Compiled.

**Comment by simon-murray** [comment]
Whats the update here, has the fix been completed yet?

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by admintools** [comment]
Hello, the same issue here:

[root@whm-1001 public_html]# php bin/magento setup:di:compile
Compilation was started.
Plugin list generation... 9/9 [============================] 100% 52 secs 438.0 MiB
Generated code and dependency injection configuration successfully.
[root@whm-1001 public_html]# 
[root@whm-1001 public_html]# php bin/magento cache:disable compiled_config
Changed cache status:
               compiled_config: 1 -> 0
[root@whm-1001 public_html]# php bin/magento cache:status
Current status:
                        config: 0
                        layout: 0
                    block_html: 0
                   collections: 0
                    reflection: 0
                        db_ddl: 0
               compiled_config: 1
                           eav: 0
         customer_notification: 0
            config_integration: 0
        config_integration_api: 0
                     full_page: 0
             config_webservice: 0
                     translate: 0
                        vertex: 0
[root@whm-1001 public_html]#

**Comment by adamzero1** [comment]
Can this be re-opened, we are seeing this on 2.4.5-p1

**Comment by nordcomputer** [comment]
I have the same problem with 2.4.6

**Comment by faraazmalak** [comment]
This bug is specific to 'default' mode.
Switch to 'developer' mode and the bug is not there.

**Comment by nordcomputer** [comment]
This bug occurs in production mode here, too:

![image](https://github.com/magento/magento2/assets/13378398/1b550420-a27a-452d-a98e-c4d9d5b250a2)

**Comment by JonathanHelvey** [comment]
The Bug happens in Magento2.4.4-p6 as well.
