### ISSUE TITLE
Insert Variable popup missing template variables for new templates

### ISSUE THREAD

**Issue by roma84** [magento/magento2#23135]
After the following PR https://github.com/magento/magento2/pull/22469 was merged into 2.3-develop, you cannot anymore insert template variables in the newly created email templates.

### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Marketing > Email Templates and press Add New Template button.
2. Select some template (e.g. Contact Form) and press Load Template button.
3. Press Insert Variable button.

### Expected result (*)

1. You should be able to insert template variables:
![vars1](https://user-images.githubusercontent.com/2668851/58944203-fe67de00-8789-11e9-94ac-273367651a8a.png)

### Actual result (*)

1. Template variables section missing:
![vars2](https://user-images.githubusercontent.com/2668851/58944439-8a7a0580-878a-11e9-8682-05eec96f55d0.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17239` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by roma84** [comment]
A possible solution for the issue:
1. Revert changes made in PR https://github.com/magento/magento2/pull/22469
2. Modify the following line instead:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Email/Block/Adminhtml/Template/Edit/Form.php#L194

```diff
--- a/app/code/Magento/Email/Block/Adminhtml/Template/Edit/Form.php
+++ b/app/code/Magento/Email/Block/Adminhtml/Template/Edit/Form.php
@@ -191,7 +191,7 @@ class Form extends \Magento\Backend\Block\Widget\Form\Generic
         }
         $template = $this->getEmailTemplate();
         if ($template->getId() && ($templateVariables = $template->getVariablesOptionArray(true))) {
-            $variables = array_merge_recursive($variables, $templateVariables);
+            $variables = array_merge_recursive($variables, [$templateVariables]);
         }
         return $variables;
     }

```

**Comment by shikhamis11** [comment]
@roma84 , your changes seems working . you can prepare a pull request with your changes 
https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#pull_request
