### ISSUE TITLE
Removing disabled product from flat table throw fatal errors.

### ISSUE THREAD

**Issue by the-midi** [magento/magento2#23146]
### Description
With flat tables enabled, one website, 5 store views and 4000 products product saving is throwing a fatal error due to either:
`PHP Fatal error:  Allowed memory size of 792723456 bytes exhausted (tried to allocate 33554440 bytes) in magento/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 291`
or with more memory
`PHP Fatal error:  PDOException(code: 08S01): SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes at magento/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228`

where the query is: `DELETE FROM catalog_product_flat_2 WHERE (entity_id IN('696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696', '696',......`

This is caused by \Magento\Catalog\Model\Indexer\Product\Flat\Action\Eraser::removeDisabledProducts select statement joining `catalog_product_entity` to the `catalog_product_entity_int` without the condition for `catalog_product_entity.row_id=catalog_product_entity_int.row_id` and therefore the fetchall returns count(catalog_product_entity) * count(catalog_product_entity_int) which in my case was 658544 results of the same entity.

### Preconditions (*)
Using the Latest Magento 2.3.1 release (also in Magento 2.3-develop)
1. Create a large number of products 
2. Enable flat tables
3. Disable some products

### Steps to reproduce (*)
1. Save a product or reindex
2. Watch SQL logs for incorrect query or receive fatal error.

### Expected result (*)
1. Product would save correctly
2. Flat tables would index (update and remove) correctly
3. No fatal errors should occur.

### Actual result (*)
1. Fatal error occurs
2. Product is not saved
3. Index are not correct.

**Comment by AlexWorking** [comment]
Hello @michaelwylde. Thanks for reporting. We've been not able to reproduce Your issue following the steps You provided. 
![flat](https://user-images.githubusercontent.com/27814011/59017537-6979e900-884c-11e9-92a8-e4ae47528f2c.png)

Please confirm You can reproduce it on a fresh clear, i.e vanilla instance of magento.

**Comment by the-midi** [comment]
@AlexWorking Yes I can confirm I could replicate this on a vanilla install. My max_allowed_packet and/or memory_limit may be different to yours. Since you did not receive the fatal error did you `Watch SQL logs for incorrect query or receive fatal error.` instead? Were your removal of the disabled products `DELETE FROM catalog_product_flat_2 WHERE (entity_id IN(1,1,1,1,1,1,1...` queries sane with non duplicate ids?

**Comment by AlexWorking** [comment]
Got no fatal error but SQL queries really contain those duplicate ids. The issue is not reproduced on 2.2-develop.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17318` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by the-midi** [comment]
This issue has been resolved in https://github.com/magento/magento2/pull/23100 targetted for 2.3.3 release
