### ISSUE TITLE
Has it any sense to show the active «Quantity», «Stock Status» and «Weight» controls for a virtual product on the backend product screen? Should not they be hidden or disabled?

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2314]
![magento2-03](https://cloud.githubusercontent.com/assets/83204/11063421/8fe18244-87c7-11e5-8a5a-b9d7ea6ad9f6.png)

**Comment by dfediuk** [comment]
Because «Manage Stock» setting has the GLOBAL scope (https://github.com/magento/magento2/issues/2012) and because an administrator is unable to set «`In Stock`» without setting the «`Quantity`» (https://github.com/magento/magento2/issues/2362) the administror is forced to set some "dummy" quantity (e.g. `10000`) for the Virtual products otherwise these products will not be avalable for purchase.

**Comment by antboiko** [comment]
@dfediuk
Hi Dmitry, I'm sorry for the delay with providing a response. Thank you for your inquiry. The Weight control is already not displayed while creating a virtual product on current mainline.

For "Quantity" and "Stock Status" I've created internal ticket MAGETWO-49913 and placed it into our backlog.

Best,
Anton.

**Comment by ellasravani** [comment]
Hi Friends,

I am new to magento. Trying to set up magento for virtual products and I need to hide quantity and in-stock options. I could not find solution anywhere. Could you please tell whether this issue is fixed or is it still the same for everyone?

Kindly help.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Has-it-any-sense-to-show-the-active-Quantity-Stock-Status-and/idi-p/47183).
