### ISSUE TITLE
Selecting top destination country which isn't in the allowed countries list generates country "0" on frontend.

### ISSUE THREAD

**Issue by hostep** [magento/magento2#23141]
### Preconditions (*)
1. PHP 7.2.18
2. Magento 2.3.1

### Steps to reproduce (*)
1. Login to the backend
2. Go to Stores > Configuration > General > General > Country Options
3. In the Allow Countries, select Afghanistan, Albania & Algeria
4. In the Top destinations, select Afghanistan, Algeria & American Samoa
5. On the frontend, register as a new user
6. Go to your Address Book and add a new address and take a look at the Country dropdown

### Expected result (*)
1. Seeing the countries where Afghanistan and Algeria are top destination and Albania is lower in the list

### Actual result (*)
1. Seeing the countries where Afghanistan, Algeria and **0** are top destination and Albania is lower in the list

<img width="513" alt="Screenshot 2019-06-05 at 15 07 50" src="https://user-images.githubusercontent.com/85479/58958674-b8b80f00-87a3-11e9-8869-d5fa5df617f6.png">

Additionally: I seem to remember there was a line in between the top destinations and the other countries, this no longer seems to be there. Found a screenshot in the opening post of https://github.com/magento/magento2/issues/10885 where it shows this line. If this is a bug and I need to open a separate issue for this, let me know!

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23141-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23141-2-3-develop.instances.magento-community.engineering/admin](https://i-23141-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @hostep. 
I'm not able to reproduce on clean manento instance as provided steps by you.
![not reproduce](https://user-images.githubusercontent.com/46617848/58960189-473c8880-87c4-11e9-9106-a2a754386506.jpg)
Please give the more information regarding this issue.
Thanks.

**Comment by hostep** [comment]
Thanks for looking into this @krishprakash, your result is also not what is expected, because Albania should be in the last spot.

I'll try again on 2.3-develop branch a bit later, maybe something was changed over there.

**Comment by hostep** [comment]
@krishprakash: I can confirm your findings on the 2.3-develop branch. It looks like this already got fixed by: [MAGETWO-99424: "0" in country dropdown list when allowed countries differs from top destinations](https://github.com/magento/magento2/commit/0731944dba50283e313f01bceb409592888f97c0)

But the end result is different than what is expected, I'll try to do some more digging...

**Comment by hostep** [comment]
Ok closing issue, I made a mistake in my testing on 2.3-develop, looks like @krishprakash made the same mistake. I accidentally selected Albania instead of Algeria in the top destinations. After correcting it, it looks like everything is fixed and works as expected. The extra empty line in the dropdown which used to be represented by a `------` in older versions of Magento2 as a divider between top countries and the rest, is also removed, which is probably a good idea.
<img width="532" alt="Screenshot 2019-06-05 at 20 11 30" src="https://user-images.githubusercontent.com/85479/58979348-26793080-87ce-11e9-8d13-581030f7cf18.png">

For people running into the same issue.
Fix for 2.3: https://github.com/magento/magento2/commit/0731944dba50283e313f01bceb409592888f97c0 (will probably be included in 2.3.3)
Fix for 2.2: https://github.com/magento/magento2/commit/2c1bc817660923c856d686436a4e3aac5ca282cc (will probably be included in 2.2.10)
