### ISSUE TITLE
Magento2 products csv export , getting 404 page , nearly after  7 minutes. ( products count 46452)

### ISSUE THREAD

**Issue by yashjain87553** [magento/magento2#23154]
### Preconditions (*)
1.Magento CE 2.3.1 without sample data is installed.
2.Codero (centos 7) server.
3.Total no of Products is 46452
4.All products are of Simple Type.
5.All products are imported using csv. 
6.Memory_Limit 4096M

### Steps to reproduce (*)
1.Login to admin
2.Click on SYSTEM->Data Transfer->Export
3.Select Entity type products, Export File Format (CSV)
4.Click Continue.
5.Initial url before clicking continue , https://domian.com/admin_path/admin/export/index/key/555b413cb896da7f627c1e6e49ed8eb5f56cffac10d99d0f97e41a584afceab1/
6.Wait for 7 to 8 minutes page load.
7.At last getting 404 error (Page not found)
8.Url changed to https://domian.com/admin_path/admin/export/export/key/0b8ba06e8e984bcc50088f1d33b958ed8f5be37be15141d75ca6c946ad31451e/entity/catalog_product/file_format/csv
9.Products csv is created in magento_installed_folder/var/.  

### Expected result (*)
1.Download CSV File Pop up .

### Actual result (*)
1.Getting 404 error  after 7 to 8 minutes page load.

Please help me to get rid of this problem.
Thank You
![Screenshot_2019-06-06 Magento Admin](https://user-images.githubusercontent.com/50539155/59017307-d9926a00-8860-11e9-8a4b-d02a5c178ce5.png)

**Comment by AlexWorking** [comment]
Hello, @yashjain87553. We are not able to reproduce Your issue:
![export](https://user-images.githubusercontent.com/27814011/59087399-3186aa80-890d-11e9-8944-d2754595fe5d.png)
Our export as You can see is quite successful.
Could You please try to reproduce it on a clear, vanilla instance of Magento. Thank You.

**Comment by yashjain87553** [comment]
Thank you Alex for the reply ,
I don't know why it is working on your system and giving 404 error on my side.

**Comment by engcom-Bravo** [comment]
@yashjain87553, so could You please install a fresh Magento instance of the latest 2.3-develop version without any code ads, code changes, third party extensions, etc. and try to reproduce Your issue on it?

**Comment by yashjain87553** [comment]
> 
> 
> @yashjain87553, so could You please install a fresh Magento instance of the latest 2.3-develop version without any code ads, code changes, third party extensions, etc. and try to reproduce Your issue on it?

ok ,

**Comment by adamlavery** [comment]
This has been closed without any resolution published. 

@yashjain87553 - we are getting this too. Worked fine on 2.2.8 but now also getting this 404 error on 2.3.1. Did you find a solution?

**Comment by yashjain87553** [comment]
No , I updated magento 2.3.1 to magento2.3.2 , issue resolved
