### ISSUE TITLE
Fix for issue 18009 broke attribute option management

### ISSUE THREAD

**Issue by jarnooravainen** [magento/magento2#23162]
### Preconditions (*)

1. 2.2.8, Magento_Eav 101.0.7

### Steps to reproduce (*)

1. Update existing attribute option with \Magento\Eav\Api\AttributeOptionManagementInterface::add

### Expected result (*)

1. Existing option and its values get updated

### Actual result (*)

1. New option is being created instead of updating existing one

Fix (https://github.com/magento/magento2/commit/3b9e96360e71b5d38167068b2b1a069ca97dc672) for reported issue 18009 (https://github.com/magento/magento2/issues/18009) seems to be unnecessary and it breaks option management so that you cannot update existing option, for example to update the store labels (values). Numeric option ID of existing option will be converted to string having 'id_' prefix and resource model will then always create new option, instead of updating existing option.

Option value (option ID) should not be provided in the request when creating new options. If this is acceptable, then fix for issue 18009 should be just reverted. Otherwise, fix should be changed so that resource model allows to create new option with given option ID and this 'id_' prefix fix is removed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17317` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @jarnooravainen 

After internal investigation and discussion with Product Managers and Architects related jira ticket was closed as `Not a But` an expected system behavior 
quote 1:

> Updating product attribute options was never meant to be supported by \Magento\Eav\Api\AttributeOptionManagementInterface::add method, and could have potentially lead to unpredicted and unwanted consequences.
> 
> All current internal workflows of updating product attribute options always worked the following way:
> 1. Deleting old product attribute options.
> 2. Crating new ones with updated information.
> 
> Currently, the system works according to the official documentation, which is confirmed by the architect of the module.
> 

quote 2:

> According to existing documentation and confirmation from the architect team , the issue described is an expected system behavior and not a bug.
