### ISSUE TITLE
Hour is not based on timezone in grid (back-office)

### ISSUE THREAD

**Issue by MeCapron** [magento/magento2#23160]
### Preconditions (*)

Magento 2.3.1

### Steps to reproduce (*)

1. Change Timezone to Europe
2. Create an order
3. Check the hour, there is a gap of ~1hour

### Expected result (*)

1. The hour should be based on the locale

### Actual result (*)

This is the result in the grid
![image](https://user-images.githubusercontent.com/49562288/59047894-0fe1e080-8885-11e9-8d85-ca7bd681098b.png)

This is the result in the order

![image](https://user-images.githubusercontent.com/49562288/59047951-30aa3600-8885-11e9-9a0c-4416361933ea.png)

**Comment by MeCapron** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MeCapron. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MeCapron, here is your [Magento instance](https://i-23160-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23160-2-3-develop.instances.magento-community.engineering/admin](https://i-23160-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by MeCapron** [comment]
I could not reproduce it on a vanilla instance.

**Comment by AlexWorking** [comment]
Hello @MeCapron. Thank You for applying. We also haven't been able to reproduce Your issue. So it's most likely that the problem You are facing is caused not by Magento itself. So we are closing the issue now, but If You find the way how to reproduce it on a vanilla instance of the latest develop version please feel free to reopen it.
