### ISSUE TITLE
Slack Support

### ISSUE THREAD

**Issue by sivasdescalzo** [magento/magento2#23168]
I am trying to connect my Slack with https://github.com/magento/magento2 repo in order to get notifications everytime there is a release, but it seems GitHub Slack APP needs some permissions to the repo to do that.

Cloud you please install GitHub Slack APP in your repo in order to be able to connect Slack with your repo?
Many thx!

**Comment by soleksii** [comment]
Hi @sivasdescalzo 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) Or slack channel,  for advice or general discussion about this issue.
