### ISSUE TITLE
why this jerry-rig?

### ISSUE THREAD

**Issue by 00F100** [magento/magento2#23161]
Why use this jerry-rig? so amateur.

Please @magento-team have many files with jerry-rig, why?

This is not a serious solution!

2.3-develop/app/code/Magento/Tax/view/adminhtml/templates/rate/js.phtml

**Comment by DanielRuf** [comment]
Hi @00F100,

what exact issue do you have?

**Comment by ghost** [comment]
Hi @00F100 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) Or slack channel,  for advice or general discussion about this issue.

**Comment by 00F100** [comment]
this is gambiarra!

**Comment by 00F100** [comment]
@engcom-backlog-nazar gambiarra! just this!

**Comment by 00F100** [comment]
@DanielRuf this is bad pratice, very bad!

**Comment by 00F100** [comment]
JS inline is bad pratice

**Comment by 00F100** [comment]
i use magento EE and I refuse to accept this kind of "thing"

**Comment by 00F100** [comment]
how I will be ignored solemnly

**Comment by 00F100** [comment]
I'll leave some messages

**Comment by 00F100** [comment]
to say: BAD PRATICE!!!!!!11

**Comment by 00F100** [comment]
even an eastern child knows that this should not be done
