### ISSUE TITLE
Unable to override padding in .lib-main-navigation-desktop mixin using @submenu-desktop__padding

### ISSUE THREAD

**Issue by Emanuel-23** [magento/magento2#23170]
Currently it is not possible to override the `.submenu` padding within the `.lib-main-navigation-desktops()` mixin because of a duplicate definition of the padding property:
[Line 408](https://github.com/magento/magento2/blob/36097739bbb0b8939ad9a2a0dadee64318153dca/lib/web/css/source/lib/_navigation.less#L408)
[Line 412](https://github.com/magento/magento2/blob/36097739bbb0b8939ad9a2a0dadee64318153dca/lib/web/css/source/lib/_navigation.less#L412)

The mixin is defined in: `/lib/web/css/source/lib/_navigation.less`

### Preconditions (*)

1. Magento Version: 2.3.x
2. Luma theme and demo data set up
3. The navigation should contain at least one submenu 
4. Inspection should be done with a Desktop screen resolution (min-width: 768px)

### Steps to reproduce (*)

First things first: with preconditions as described above, you do not have to define values as described below at all. Magento2 overrides its submenu padding by default. 

Optionally
1. define @submenu-desktop__padding with a px value of your choice
2. compile less
3. open the magento2 website with defaultopen inspector

### Expected result (*)

1. The padding property should be overridden if @submenu-desktop__padding is defined and valid (px value )
2. The navigation submenu should show the padding 

### Actual result (*)

1. The padding of @submenu-desktop__padding (within mixin: @_submenu-padding) gets instantly overridden, because of the `padding: 0` defined 4 lines later.

**Comment by orlangur** [comment]
@Emanuel-23 great finding! Can you create a PR maybe?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21686` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Emanuel-23. Thank you for your report. 
The issue has been fixed in magento/magento2#25176 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [93034ab3569dde8cf2f6889b7c4ac3e786845866](https://github.com/magento/magento2/commit/93034ab3569dde8cf2f6889b7c4ac3e786845866)

The fix will be available with the upcoming 2.3.4 release.
