### ISSUE TITLE
Bug - Magento_Eav - eav_attribute_group (repository) filtering

### ISSUE THREAD

**Issue by LucianMihalache** [magento/magento2#23172]
There is a bug on the Magento_Eav Module, to be more precise, there is a bug when you want to filter the attribute_group collection by multiple values (IN).

**The bug affects rest api too*

### Preconditions (*)

1. Any Magento 2.3.1 that does not overwrite Magento_Eav module
2. Some data on the site, I tested with sampledata

### Steps to reproduce (*)

1. Try to filter the eav_attribute_group (AttributeGroupRepository) by multiple attribute_set_id's or by multiple attribute_group_code

If you try to filter by attribute_group_code, you won't be able to filter at all.

>     /**
>      * @var \Magento\Eav\Api\AttributeGroupRepositoryInterface
>      */
>     protected $attributeGroupRepository;
> 
>     /**
>      * @var \Magento\Framework\Api\Search\SearchCriteriaBuilderFactory
>      */
>     protected $searchCriteriaBuilderFactory;
> 
>     /**
>      * @var \Magento\Framework\Api\FilterBuilder
>      */
>     protected $filterBuilder;
> 
>     public function __construct(
>         \Magento\Eav\Api\AttributeGroupRepositoryInterface $attributeGroupRepository,
>         \Magento\Framework\Api\Search\SearchCriteriaBuilderFactory >$searchCriteriaBuilderFactory,
>         \Magento\Framework\Api\FilterBuilder $filterBuilder
>     ) {
>         $this->attributeGroupRepository = $attributeGroupRepository;
>         $this->searchCriteriaBuilderFactory = $searchCriteriaBuilderFactory;
>         $this->filterBuilder = $filterBuilder;
>     }
>
>     public function test()
>     {
>         /** @var \Magento\Framework\Api\Search\SearchCriteriaBuilder $criteriaBuilder */
>         $criteriaBuilder = $this->searchCriteriaBuilderFactory->create();
>         $setIdFilter = $this->filterBuilder
>             ->setField('attribute_set_id')
>             ->setValue('15,10,4,14,11,12,13,9') // All the attribute_set_id from that are present on clean install with sampledata
>             ->setConditionType('in')
>             ->create();
>
>         $groupCodeFilter = $this->filterBuilder
>             ->setField('attribute_group_code')
>             ->setValue('"advanced-pricing", "autosettings", "bundle-items", "content"')
>             ->setConditionType('in')
>             ->create();
>
>     /* I am using directly imploded strings because this is the format I need when I am doing rest api 
>        get, and since is the same repository, it works the same way.*/
>
>         $criteria = $criteriaBuilder->addFilter($setIdFilter)->create();
>         //$criteria = $criteriaBuilder->addFilter($groupCodeFilter)->create();
>
>         $groupList = $this->attributeGroupRepository->getList($criteria);
>         //Do something with $groupList
>         var_dump($groupList->getSearchCriteria()->getFilterGroups()[0]->getFilters());
>         var_dump($groupList->getTotalCount());
>         foreach ($groupList->getItems() as $group) {
>             var_dump('AttributeSetId: ' . $group->getAttributeSetId());
>         }
>         die('asdfasfasdf');
>     }

### Expected result (*)

1. Returning all the groups assigned to all the attribute_set_id's given.
In the database, that means, 80 records (sampledata)

![select](https://user-images.githubusercontent.com/48981554/59113458-b5f91d80-894d-11e9-9a3e-a9359c444f21.png)

### Actual result (*)

>         ....php:102:
>         array (size=1)
>        0 => 
>          object(Magento\Framework\Api\Filter)[1784]
>            protected '_data' => 
>              array (size=3)
>                'field' => string 'attribute_set_id' (length=16)
>                'value' => string '15,10,4,14,11,12,13,9' (length=21)
>                'condition_type' => string 'in' (length=2)
>          ....php:103:int 10
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)
>          ....php:105:string 'AttributeSetId: 15' (length=18)

The query string after applying the filters:

>      SELECT `main_table`.* FROM `eav_attribute_group` AS `main_table` WHERE (`attribute_set_id` = '15,10,4,14,11,12,13,9')

The problem, as I said in some other post (https://github.com/magento/magento2/issues/2892#issuecomment-499893836) is:

After some debugging, I found the problem:
When the AttributeGroupRepository processes the collection, the process goes through:
>     vendor/magento/framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php
>         addFilterGroupToCollection(...)

Here, on the line 66-70:

>             $customFilter = $this->getCustomFilterForField($filter->getField());
>             if ($customFilter) {
>                 $isApplied = $customFilter->apply($filter, $collection);
>             }

There IS a custom field for my search (attribute_set_id), and the code goes in:
>      vendor/magento/module-eav/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/AttributeGroupAttributeSetIdFilter.php

Here there is: 

>     public function apply(Filter $filter, AbstractDb $collection)
>     {
>         /** @var \Magento\Eav\Model\ResourceModel\Entity\Attribute\Group\Collection $collection */
>         $collection->setAttributeSetFilter($filter->getValue());
> 
>         return true;
>     }

Which goes on:

>      vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute/Group/Collection.php

>     public function setAttributeSetFilter($setId)
>     {
>         $this->addFieldToFilter('attribute_set_id', ['eq' => $setId]);
>         $this->setOrder('sort_order');
>         return $this;
>     }

Here we can see that the eav_attribute_group collection does not even care about what we want us to do with the filter, it simply forces us on equal.

I don't want to believe that this was intentional, but instead, I believe that this was some old code that was done before the whole process-filter-thing, and it was forgotten.

The same goes for all filters from the eav_attribute_group:
>           vendor/magento/module-eav/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/AttributeGroupAttributeSetIdFilter.php

>     vendor/magento/module-eav/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/AttributeGroupCodeFilter.php

>     vendor/magento/module-eav/Model/Api/SearchCriteria/CollectionProcessor/FilterProcessor/AttributeSetEntityTypeCodeFilter.php

All of them, don't bother to see what condition type we want to use on the collection.

For fixes, I think that the best solution is to let the processor do its job. That means:

>     vendor/magento/module-eav/etc/di.xml

Remove the lines 184-154:

>     <virtualType name="Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor\AttributeSetFilterProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor\FilterProcessor">
>         <arguments>
>             <argument name="customFilters" xsi:type="array">
>                 <item name="entity_type_code" xsi:type="object">Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor\AttributeSetEntityTypeCodeFilter</item>
>             </argument>
>         </arguments>
>     </virtualType>

Remove the lines: 169-179

>     <virtualType name="Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor\AttributeGroupFilterProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor\FilterProcessor">
>         <arguments>
>             <argument name="fieldMapping" xsi:type="array">
>                 <item name="attribute_group_code" xsi:type="string">main_table.attribute_group_code</item>
>             </argument>
>             <argument name="customFilters" xsi:type="array">
>                 <item name="attribute_set_id" xsi:type="object">Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor\AttributeGroupAttributeSetIdFilter</item>
>                 <item name="attribute_group_code" xsi:type="object">Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor\AttributeGroupCodeFilter</item>
>             </argument>
>         </arguments>
>     </virtualType>

And of course, remove the not used (anymore) code...

**Comment by LucianMihalache** [comment]
@magento-engcom-team Yes, I can reproduce it on multiple instances of 2.3.1
Can somebody work on this?
There is a little problem because I need to do api requests, and by doing N requests to get some attribute groups is really... inneficient, nobody wants to wait 10-20 seconds just to do some checks on the other end...

**Comment by engcom-Charlie** [comment]
Hello @LucianMihalache ! Thank you for your report !
I`ve just tested this on Vanilla Magento 2.3-develop without Sample Data and got this result 

![Screenshot from 2019-07-10 11-14-32](https://user-images.githubusercontent.com/51680850/60952827-a8e09d00-a304-11e9-94e7-4e103538ae6a.png)

**Comment by LucianMihalache** [comment]
@engcom-Charlie so, for you, a filter of AttributeGroupRepository by multiple attribute_set_id applied the correct filter, 'IN' ?
Can I get a develop instance?
I wanna try a rest api call for that repository to see if the response is the same.
What is the exact version of your instance? Release 2.3.1, or the develop version?

**Comment by LucianMihalache** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LucianMihalache. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LucianMihalache, here is your [Magento instance](https://i-23172-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23172-2-3-develop.instances.magento-community.engineering/admin](https://i-23172-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by LucianMihalache** [comment]
@engcom-Charlie , Look, on the develop instance, run this curl:

This one is for you to see how many groups are there, and note their attribute_set_id.
I created 3 more attribute_sets

![attribute sets](https://user-images.githubusercontent.com/48981554/60954462-ac295800-a307-11e9-80d3-69f60fa9caa2.png)

And the curl is to get all the groups assigned to the attribute sets.
I made it with swagger.
https://i-23172-2-3-develop.instances.magento-community.engineering/swagger
Api key: lbpbbo4he8kp8sit9ln4uwkj7t9scfb1

Firstly, lets get all the groups of all attribute_sets that exists on the site (4,9,10,11)

![swagg1](https://user-images.githubusercontent.com/48981554/60955015-abdd8c80-a308-11e9-9a1f-1dd06a4b8c96.png)

![swagg2](https://user-images.githubusercontent.com/48981554/60955016-abdd8c80-a308-11e9-95df-f2547b1294d7.png)

And the result:

![swagg3](https://user-images.githubusercontent.com/48981554/60955017-abdd8c80-a308-11e9-82c2-d207b185ac79.png)

As you can see, there are no groups to any other attribute set.

Than, lets see how many groups are there (including the customer, etc..., we will just ignore them)

To do that, we will just sort the group table.

![swagg4](https://user-images.githubusercontent.com/48981554/60955012-ab44f600-a308-11e9-8686-6560b61e6355.png)

And the result:

![swagg5](https://user-images.githubusercontent.com/48981554/60955013-ab44f600-a308-11e9-86f3-ae0ed4b65ab0.png)

As you can see, there all our attribute sets. But, the search for all of them, does not work.
It will give you only the first value searched in our query: 4,9,10,11 - that means, the value 4.
Because the query run into the database by the repository looks like this:

Select * from `eav_attribute_group` where `attribute_set_id` = '4,9,10,11';

And the problem (+answer) why there is '=' instead of 'in', is written above.

curl -X GET "https://i-23172-2-3-develop.instances.magento-community.engineering/rest/all/V1/products/attribute-sets/groups/list?searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=attribute_set_id&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=4%2C9%2C10%2C11&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5BconditionType%5D=in&searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=attribute_set_id&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=asc" -H "accept: application/json" -H "Authorization: Bearer lbpbbo4he8kp8sit9ln4uwkj7t9scfb1"

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18024` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by LucianMihalache** [comment]
@engcom-Charlie Thank you

**Comment by VladimirZaets** [comment]
Please recheck this issue due to https://github.com/magento/magento2/pull/22133/

**Comment by dorje7** [comment]
#mageсonfcd2020

**Comment by dorje7** [comment]
#mageсonfcd2020
