### ISSUE TITLE
Configurable - saving without childs and no stock - gives 500

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#23184]
### Preconditions (*)

1. Magento 2.3.1
2. MSI enabled by default. No any additional sources/stockes created. Just default config after install vanilla Magento 2.3.1
Probably with MSI disabled error will no appear - but I'm not sure.
3. Php 7.2

### Steps to reproduce (*)

1. Create Configurable
2. Dont create/assign any child products
3. Dont fill qty field
4. TRY to save Configurable

### Expected result (*)

1. Product saved correctly OR
2. Error before save - with notification to correct missing things

### Actual result (*)

1. Error 500
2. log
`[Sun Jun 09 13:49:14.432897 2019] [proxy_fcgi:error] [pid 29246] [client 127.0.0.1:38540] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\\Inventory\\Model\\SourceItem::setQuantity() must be of the type float or null, string given, called in /home/282739.com/qrjhdbnngj/public_html/vendor/magento/framework/Api/DataObjectHelper.php on line 125 and defined in /home/282739.com/qrjhdbnngj/public_html/vendor/magento/module-inventory/Model/SourceItem.php:75\nStack trace:\n#0 /home/282739.com/qrjhdbnngj/public_html/vendor/magento/framework/Api/DataObjectHelper.php(125): Magento\\Inventory\\Model\\SourceItem->setQuantity('')\n#1 /home/282739.com/qrjhdbnngj/public_html/vendor/magento/framework/Api/DataObjectHelper.php(85): Magento\\Framework\\Api\\DataObjectHelper->_setDataValues(Object(Magento\\Inventory\\Model\\SourceItem), Array, 'Magento\\\\Invento...')\n#2 /home/282739.com/qrjhdbnngj/public_html/vendor/magento/module-inventory-catalog-admin-ui/Observer/SourceItemsProcessor.php(104): Magento\\Framework\\Api\\DataObjectH...\n', referer: https://domain.com/admin/catalog/product/new/set/4/type/configurable/key/10d3c9ac2eadf2e1745577b0e134f5b87cf8bb136bab7c337a38335a0d5eee0c/
`

**Comment by EternalBobby** [comment]
Hi @tomekjordan ! thank you for your report.  Please open issue related with MSI in [msi](https://github.com/magento-engcom/msi) repo to get answer for your question.
