### ISSUE TITLE
Cart price rule on configurable product apply discount to all cart

### ISSUE THREAD

**Issue by guillaumecochard** [magento/magento2#23185]
### Preconditions (*)
1. Magento 2.3.0 without sample date and totaly nude and on Magento 2.3.1 with custom template
2. PHP 7.1.27
3. Debian 8

### Steps to reproduce (*)
1. Create two configurable product with color configuration
2. Create Cart Rule with conditions : 

If ALL  of these conditions are TRUE :
If an item is FOUND  in the cart with ANY  of these conditions true:
SKU  is  testproduit-blue 

where testproduit-blue is the SKU of a simple product (a configuration)

3. Add the testproduit-blue to the cart
4. Add another product to the cart (simple product too, for example testproduit-red)
5. Apply the discount code in the cart

### Expected result (*)
1. The promo code is applied only to the testproduit-blue product price

### Actual result (*)
1. The promo code is applied to the subtotal cart
![cartpricecoupon](https://user-images.githubusercontent.com/7467023/59161451-0786e100-8ae3-11e9-9ae4-2e0caadf721e.png)
![cartpriceruleconfig](https://user-images.githubusercontent.com/7467023/59161452-0786e100-8ae3-11e9-9a8d-61818bc02ba5.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23185-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23185-2-3-develop.instances.magento-community.engineering/admin](https://i-23185-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23185-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23185-2-2-develop.instances.magento-community.engineering/admin](https://i-23185-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17348`, `MC-17349` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AndreaShining** [comment]
Hello @guillaumecochard and @krishprakash ,
i think this is not an issue.

You should add "testproduit-blue" in Action conditions if you want to apply rule just for such sku (or cart items you specify in action conditions).

You can find "action conditions" just below Actions.

**Comment by krishprakash** [comment]
@AndreaShining thank you for clarification.
Closing this as non issue.
