### ISSUE TITLE
Configurable - removed child from configurable - checkout still possible

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#23182]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Add Configurable product to the cart
2. Move to checkout
3. REMOVE configurable child and save configurable product. Of course simple child still exists in the store- but its not visible individually. BUT its not a part of configurable anymore.
4. Finish checkout is possible with product child that doesnt' exist

### Expected result (*)

1. Finish checkout should check if the configurable child product is still existing in configurable set.

### Actual result (*)

1. Checkout is allowed with child product that is removed from Configurable
2. Order product row shows - configurable with child is ordered. So it getting its SKU (configurable)+child. But this child is not a part of configurable yet.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @EternalBobby 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17391`, `MC-17392` were created

**Issue Available**: @EternalBobby, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Martinsl** [comment]
#mm19br

**Comment by magento-engcom-team** [comment]
@Martinsl thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23738` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
