### ISSUE TITLE
ALTER TABLE `customer_group` MODIFY COLUMN `customer_group_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT

### ISSUE THREAD

**Issue by mssyogi** [magento/magento2#23193]
(*) PHP 7.1.3
(*)Magnento 2.1.16

### Summary (*)
I tried to upgrde the magento from 2.1.16 To 2.3.1 and i face thiss issue.

### Examples (*)

ALTER TABLE `customer_group` MODIFY COLUMN `customer_group_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT

**Comment by mssyogi** [comment]
Steps to reproduce:
Do setup Magento 2.1.16 With Php 7.0,
Try to upgrade the Magento to 2.3.1
Using Composer update command

**Comment by developer-vtnetzwelt** [comment]
Any update on this issue?

We are getting same issue.

**Comment by engcom-Delta** [comment]
Hi @mssyogi thank you for your report. I cannot reproduce issue by steps you described on clean 2.3-develop. 
I also tried to upgrade from latest magento release versions: 2.1.18->2.3.2 and upgrade was successful
In this case I used devdoc [article](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)
If you'd like to update issue, please reopen it.
