### ISSUE TITLE
Select All products then Delete don't actually delete all products, but only the products visible on the page

### ISSUE THREAD

**Issue by pinguluk** [magento/magento2#23197]
### Preconditions (*)

1. Magento 2.3.1 Community

### Steps to reproduce (*)

1. Select **Select All** on products catalog page (not **Select All on This Page**)
2. Actions -> Delete

### Expected result (*)

1. **All** products to be deleted

### Actual result (*)

1. Only products from the page (20 per page default) are deleted

**Comment by pinguluk** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pinguluk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pinguluk, here is your [Magento instance](https://i-23197-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23197-2-3-develop.instances.magento-community.engineering/admin](https://i-23197-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pinguluk** [comment]
> Hi @pinguluk, here is your [Magento instance](https://i-23197-2-3-develop.instances.magento-community.engineering).
> Admin access: https://i-23197-2-3-develop.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

**Comment by pinguluk** [comment]
> Hi @pinguluk, here is your [Magento instance](https://i-23197-2-3-develop.instances.magento-community.engineering).
> Admin access: https://i-23197-2-3-develop.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

**Comment by pinguluk** [comment]
I reproduced the issue on the instance as well

**Comment by krishprakash** [comment]
Hi @pinguluk,
Thank you for your report.
This issue is duplicate to #22704 
Issue is already added so I'm closing this.
