### ISSUE TITLE
unable to install Authorize.net Direct Post Signature Key patch 

### ISSUE THREAD

**Issue by wingsoul** [magento/magento2#23198]
### Preconditions (*)
Ubuntu Linux 16.4.10,
PHP 7.0 php-fpm,
nginx/1.15.12,
Mariadb 5.7
M2.1.8

### Steps to reproduce (*)
1. download patch from magento site:
[https://magento.com/tech-resources/download#download2279](url)
2. Upload the patch to Magento root directory.
3. run the following code
patch -p1 < %patch_name%

### Actual result (*)
following error will be appear and website will be blank
`oot@ip-172-31-4-87:/mnt/dev/magento2.new# php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 48.0 MiBPHP Fatal error:  Cannot redeclare Magento\Authorizenet\Model\Directpost\Response::generateSha2Hash() in /mnt/dev/magento2.new/vendor/magento/module-authorizenet/Model/Directpost/Response.php on line 120`

Hope someone can help, Thanks a lot

**Comment by engcom-Charlie** [comment]
Hello @wingsoul ! Thank you for your report . Seems like link that you attached is not valid anymore, please update it .

**Comment by engcom-Charlie** [comment]
Feel free to reopen this issue when you will update it .
