### ISSUE TITLE
Magento 2 Downloadable Product issue with checkout API

### ISSUE THREAD

**Issue by aishwaryasunarc** [magento/magento2#23192]
I am using magento 2.3 instance. I am developing android app with magento 2 default APIs but I am facing issue with checkout.
According to magento 2 default , we don't required billing and shipping information for virtual and downloadable products but when I placing order using magento 2 default API I am getting billing and shipping information required.

Step to reproduce( Using Magento 2 Rest API)
1. Add downloadable product to cart
2. After add product to cart set payment method
3. Place order 

After call place order API getting error Billing information is required with downloadable products.

Please help me to find any solution for this.

**Comment by makkoff** [comment]
When you set payment method your API request must contain billing address. For example:
{
	"paymentMethod": {
    	    	"method": "banktransfer"
	 },
	"billing_address": {
    	    	"email": "jdoe@example.com",
  	      	"region": "New York",
          	"region_id": 43,
          	"region_code": "NY",
    	    	"country_id": "US",
    	    	"street": ["123 Oak Ave"],
    	    	"postcode": "10577",
    	    	"city": "Purchase",
    	    	"telephone": "512-555-1111",
    	    	"firstname": "Jane",
    	    	"lastname": "Doe"
	 }
}

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @EternalBobby 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17389`, `MC-17390` were created

**Issue Available**: @EternalBobby, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by arushibansal013** [comment]
Hi @aishwaryasunarc,

Did you tried to place an order with front-end or admin panel using virtual or downloadable product. As per magento shipping method is not mandatory but billing address is required for placing an order.
