### ISSUE TITLE
Show Out of Stock configurable product options

### ISSUE THREAD

**Issue by flamboy85** [magento/magento2#23196]
### Preconditions (*)

1. Set show out fo stock products https://i.imgur.com/IcgxEtz.png
2. Clean-up caches

### Steps to reproduce (*)

1. Go to product list
2.

### Expected result (*)

1. Out of stock options must be visible https://i.imgur.com/ersI0cj.png
2.

### Actual result (*)

1. Out of stock options NOT visible
2.

@see vendor/magento/module-configurable-product/Plugin/Model/ResourceModel/Attribute/InStockOptionSelectBuilder.php

**Comment by makkoff** [comment]
Hello. I have expected result on 2.3-develop.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23196-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23196-2-3-develop.instances.magento-community.engineering/admin](https://i-23196-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23196-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23196-2-2-develop.instances.magento-community.engineering/admin](https://i-23196-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
In the Configuration section, Config > Inventory > Stock Options > Display Out of Stock Products to YES, Out of Stock Product options is not visible on the Product details page.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17432`, `MC-17433` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hi @flamboy85,
Thank you for report.
This issue is duplicate to #16069

**Comment by palomamtnez** [comment]
Hi, any solution for this? on 2.3

**Comment by jaykobi** [comment]
@krishprakash It's no a direct duplicate of the ticket you mention.
@magento-engcom-team 
If you do a google search on "magento2 configurable product show out of stock" you'll see a many people an on all platforms (github, stackoverflow, magento forums) that complain about this magento2 behaviour. We all just want magento to adhere to a simple e-commerce standard: **If a child product is sold out, show this to the customer**. Show the product, but grey it out. Simple as that. Please reopen the ticket and fix the issue.

**Comment by seb-jean** [comment]
Any news ?

**Comment by aliuosio** [comment]
there is a composer package with which you can show "sold out" options but it dos not mark does soll out. try it out yourself: https://packagist.org/packages/interjar/module-configurable-child-visibility

**Comment by maddyBoy** [comment]
Hi, any solution for this? on 2.3.x

**Comment by aliuosio** [comment]
@maddyBoy 
Add this to your composer.json. 

```
{
  "require": {
    "interjar/module-configurable-child-visibility": "dev-patch-1"
  },
  "repositories": {
    "configurable-child-visibility": {
      "type": "git",
      "url": "https://github.com/Stevie-Ray/configurable-child-visibility"
    }
  }
}

```

You have to use this GitHub Fork because the original Repro has an dependency version problem causing the extension not to work with Magento 2.3.0

Run 
```
composer update;
bin/magento setup:upgrade;
bin/magento cache:flush;
```

Set one of your simple products belonging to a configurable Product to 
"out of stock" in the Backend and test the Frontend Product Detail Page 

With this module the "out of stock" options are displayed and Selectable

**Comment by Stevie-Ray** [comment]
hi @aliuosio,

I've removed my fork because the problem got fixed in the **interjar** repo! 
So it should work on 2.3.x now:

```shell
composer require interjar/module-configurable-child-visibility
bin/magento module:enable Interjar_ConfigurableChildVisibility
```

**Comment by aliuosio** [comment]
@Stevie-Ray 
:+1:  
thx for the info... will try it out right now.

**Comment by hemendraajmera** [comment]
after using 
composer require interjar/module-configurable-child-visibility
bin/magento module:enable Interjar_ConfigurableChildVisibility 
facing issue as  Interjar\ConfigurableChildVisibility\Plugin\Model\ResourceModel\Attribute\InStockOptionSelectBuilder
Missed required argument stockConfig in parent::__construct call. File:/vendor/interjar/module-configurable-child-visibility/Plugin/Model/ResourceModel/Attribute/InStockOptionSelectBuilder.php

**Comment by aliuosio** [comment]
@hemendraajmera:
The bug was fixed in the latest Magento 2 version. 
No need for this extension anymore.
Throw it out and update to Magento 2.3.5-p1.

**Comment by magneticeye** [comment]
I have 2.3.4 and it seems to be fixed in this version.
I am looking to add the text (out of stock) to out of stock items in drop down for configurable products.
Can't seem to find a solution for Magento 2.
Any body have any ideas?

**Comment by aliuosio** [comment]
@magneticeye 
Upgrade to Magento 2.3.5-p1 and try again.
I saw the "sold out" option marked with using swatches on configurable products.

**Comment by hemendraajmera** [comment]
Updated with Magento 2.3.5-p1 but still facing issue

**Comment by aliuosio** [comment]
@hemendraajmera 
- [ ] Did you set one simple product to "out of stock"? 
- [ ] Do you have the function "show out of stock products" enabled under configuration -> catalog -> inventory?
- [ ] Did you choose a combination of Optionen that would be recognized as "sold out"?
- [ ] Are you working with Sample Data or an existing Project DB

**Comment by aliuosio** [comment]
@hemendraajmera
I have a instance set up with sample data.
Feel free to use it
https://mage2.dev-hh.de/admin
User: mage2_admin
Password: mage2_admin123#T

https://mage2.dev-hh.de

**Comment by hemendraajmera** [comment]
@aliuosio above details prompt username and password
![image](https://user-images.githubusercontent.com/2478037/81138413-a0d2a780-8f7f-11ea-8bef-ea7d7339a598.png)

**Comment by aliuosio** [comment]
mage2
mage2

tell me when you are done

**Comment by hemendraajmera** [comment]
Still out of stock (both configurable)product not showing options and price as well 
![image](https://user-images.githubusercontent.com/2478037/81172422-d7c6ae80-8fbb-11ea-8ab8-0c03f79b8b58.png)

working fine when one product is instock as 
![image](https://user-images.githubusercontent.com/2478037/81172671-4c015200-8fbc-11ea-9d91-74e4cf938515.png)

**Comment by aliuosio** [comment]
@hemendraajmera 
now i understand.... :rofl: 
Without looking at the code right now.
i would write a plugin.
Try stepping through the code using xdebug to find the the block.
I know the answer is very wide

**Comment by hemendraajmera** [comment]
Ok please share plugin ASAP

**Comment by aliuosio** [comment]
@hemendraajmera 
a plugin is not flying around at this time but i can send you a link to my Paypal account if you hit me on skype containing a money offer :-)

**Comment by magneticeye** [comment]
I upgraded to magento 2.3.5 but it is the same a 2.3.4
It shows greyed out option for out of stock item, but doesn't say "Sold Out" or "Out of Stock"
Is there a setting that I am missing?

**Comment by hemendraajmera** [comment]
Any updates on the solution Please

**Comment by scoops87** [comment]
Facing the same issue. It's absurd.

**Comment by scoops87** [comment]
@hemendraajmera - what happens if you click the Greyed out item, as shown in your picture.
Does it allow you to click it?

**Comment by scoops87** [comment]
I see Amasty have an extension. Has anyone else tried this?

**Comment by hemendraajmera** [comment]
@scoops87 can you please share URL of Amasty extension.
