### ISSUE TITLE
Permission Denied htaccess in folders where no htaccess file even exists

### ISSUE THREAD

**Issue by primaatlanta** [magento/magento2#2320]
This permissions issue comes up in the server log.  It doesn't stop the site from loading but it does stop a lot of the site.  Some things I did fix through permissions but things like this keep popping up and I'm not sure if it is an Apache thing with rewrites or if this is a permissions issue.  There's not supposed to be a htaccess file in this folder correct?

/pub/static/adminhtml/Magento/backend/en_US/mage/utils/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that ... is executable

also errors for:
Magento_Paypal/
Magento_Braintree/
Magento_Ui/js/lib/ko/extender/
frontend/Magento/luma/en_US/Magento_Ui/js/lib/
frontend/Magento/luma/en_US/Magento_Ui/js/core/renderer/

I've gone all the way to 777 on files and folders in /en_US/ just to test and still same issue

What steps should I take to narrow this issue down?  What permissions does pub/static/ need in order to function?  Also, if a mod_rewrite issue, how can I enable this for the root magento directory without doing in the httpd.conf file?  When I look for mod_rewrite, I am not having any luck finding a way to ensure it is in fact enabled and working.  I have PHP 5.6.15, Apache 2.4.16, Easy::Apache v3.32.5 rev 9999, and MySQL 5.6.27, Magento 2.0.0-rc.

httpd.conf directory setting:

<Directory "/">
    AllowOverride All
    Options All
</Directory>

<Directory "/usr/local/apache/htdocs">
    Options All
    AllowOverride All
    Require all granted
</Directory>

<Directory "/public_html">
        AllowOverride All
        Options All
        Require all granted
</Directory>

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by primaatlanta** [comment]
Did I word it correctly to be asked?  Just making sure I am giving the information needed in order to get help.

**Comment by davidalger** [comment]
@primaatlanta Basically I'm saying this is the wrong place for requesting technical assistance and to please visit the forums or Magento stack exchange site (see above for links).

**Comment by primaatlanta** [comment]
@davidalger I understand what you're saying I'm asking if the question makes sense or if I need to give better or different info when posting to the forum or magento stack exchange but don't worry about it.
