### ISSUE TITLE
Backup functionality is disabled in my magento 

### ISSUE THREAD

**Issue by indibuyz** [magento/magento2#23203]
I have launched my magento in google cloud but i am getting this error while i am instaling my extenction " back up functionality is disabled" please tell me how can i solve it & also i went into setting there also getting the same error in the backup folder

**Comment by krishprakash** [comment]
Hi @indibuyz.
Please refer below links for enable backup:
https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-backup.html
https://devdocs.magento.com/guides/v2.3/comp-mgr/module-man/compman-backup.html

**Comment by engcom-Charlie** [comment]
Hello @indibuyz . Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
