### ISSUE TITLE
head_shortcut_icon does not contain field 'file' error after uploading favicon icon

### ISSUE THREAD

**Issue by Ant5rev** [magento/magento2#23204]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
@Ant5rev  fell free to reopen this issue when you will be ready to provide more details and we will review it and confirm it.
