### ISSUE TITLE
Unable to unserialize on new product page

### ISSUE THREAD

**Issue by netzwelt-nishu** [magento/magento2#23206]
### Preconditions (*)

1. Magento 2.3.1 
2. 

### Steps to reproduce (*)

1. we create any product into our magento admin 
2.

### Expected result (*)

1. New product form should open.
2.

### Actual result (*)

1. I am getting issue (Unable to unserialize value. Error: Syntax error) with the stack trace

**Comment by netzwelt-nishu** [comment]
﻿{"0":"Unable to unserialize value. Error: Syntax error","1":"<pre>#1 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Categories->getCategoriesTree() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Categories.php:248]\n#2 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Categories->customizeCategoriesField() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/Modifier\/Categories.php:127]\n#3 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\Modifier\\Categories->modifyMeta() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/ProductDataProvider.php:73]\n#4 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\ProductDataProvider->getMeta() called at [vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php:316]\n#5 Magento\\Framework\\View\\Element\\UiComponentFactory->mergeMetadata() called at [vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php:218]\n#6 Magento\\Framework\\View\\Element\\UiComponentFactory->create() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:140]\n#7 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->generateComponent() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:102]\n#8 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->process() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:81]\n#9 Magento\\Framework\\View\\Layout\\GeneratorPool->process() called at [vendor\/magento\/framework\/View\/Layout.php:343]\n#10 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:89]\n#11 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]\n#12 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:55]\n#13 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]\n#14 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Layout.php:253]\n#15 Magento\\Framework\\View\\Layout->build() called at [vendor\/magento\/framework\/View\/Layout.php:875]\n#16 Magento\\Framework\\View\\Layout->getBlock() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:414]\n#17 Magento\\Framework\\View\\Layout\\Interceptor->getBlock() called at [vendor\/magento\/module-backend\/Model\/View\/Result\/Page.php:26]\n#18 Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu() called at [vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Product\/NewAction.php:72]\n#19 Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#20 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#21 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#22 Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#23 Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#24 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#25 Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#26 Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/NewAction\/Interceptor.php:26]\n#27 Magento\\Catalog\\Controller\\Adminhtml\\Product\\NewAction\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#28 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#29 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#30 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#31 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#32 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#33 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:136]\n#34 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:258]\n#35 Magento\\Framework\\App\\Bootstrap->run() called at [index.php:39]\n<\/pre>","url":"\/admin\/catalog\/product\/new\/set\/35\/type\/simple\/key\/098cfb6c11ca7eb4b84b80deff661349f29558203f548fe9ffa4c639db709df2\/","script_name":"\/index.php"}

**Comment by EternalBobby** [comment]
Hello @netzwelt-nishu !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) Or slack channel,  for advice or general discussion about this issue.
