### ISSUE TITLE
Zero Subtotal Checkout erroneously says the default value for "Automatically Invoice All Items" is "Yes"

### ISSUE THREAD

**Issue by navarr** [magento/magento2#23211]
### Preconditions

1. Magento 2.3.1 with some products
2. Cart Price rule that discounts products and shipping to 100% (use coupon code "FREE" to make life easier)
3. In Configuration for "Zero Subtotal Checkout", uncheck "Use system value" for "New Order Status" and set to "Processing"
4. NOTE but do not change "Automatically Invoice All Items."  It should be readonly and should say "Yes".  "Use system value" checkbox beside it should be checked.

### Steps to reproduce

1. On storefront, check out order with FREE coupon to make order $0
2. In admin panel, view the order just created and click on the Invoices tab

### Expected result

1. An invoice appears in the grid

### Actual result

1. No invoice appears in the grid

### Note and Technical Information

This is because while the dropdown says "Yes," the default is non-existent.  One might think this would show "No" in the dropdown box, since its value is set to "" but it does not.

Updating this would be easy enough to change, but there are two routes that can be taken and I am unsure as to which would be the best:

#. Set the default to explicitly be yes, to reflect what it already says
#. Update the default to either be explicitly no, or update the source model so that No appears before yes.

**Comment by navarr** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @navarr, here is your [Magento instance](https://i-23211-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23211-2-3-develop.instances.magento-community.engineering/admin](https://i-23211-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by navarr** [comment]
I successfully recreated the issue on the Vanilla instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @EternalBobby 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17435`, `MC-17436` were created

**Issue Available**: @EternalBobby, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh, here is your [Magento instance](https://i-23211-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-23211-2-3-1.instances.magento-community.engineering/admin](https://i-23211-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23211-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23211-2-3-develop.instances.magento-community.engineering/admin](https://i-23211-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @navarr, @edenduong. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.
