### ISSUE TITLE
Serving multiple HTTP requests to a store simultaneously when the «var/generation» folder is empty leads to a random shared resources access (concurrency) conflict

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2321]
https://mage2.pro/t/187

**Comment by dfediuk** [comment]
The solution is to [compile the code](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler.html) before serving any requests.

**Comment by davidalger** [comment]
@dfediuk When you ran into this, what mode was Magento 2 running in? Production mode? In production mode, last I checked, I don't think it's supposed to try the generation but I could be mistaken.

**Comment by dfediuk** [comment]
I use the Development mode.
