### ISSUE TITLE
Text swatches blank

### ISSUE THREAD

**Issue by PedroKTFC** [magento/magento2#23215]
### Preconditions (*)

1. Magento CE 2.3.1

### Steps to reproduce (*)

1. Migrate from 1.8.1 to 2.3 (and upgrade to 2.3.1 but this latter step is irrelevant)
2. For configurable products select text swatches

### Expected result (*)

1. Swatches should display text values such as Black, White or Large, Small

### Actual result (*)

1. Swatches show the word "null" everywhere except in layered navigation where they are blank
2. See https://stackoverflow.com/questions/56323032/magento-2-not-showing-text-swatches-values and https://magento.stackexchange.com/questions/277343/magento-2-layered-navigation-text-swatches-blank which also discusses how I've solved it for now

**Comment by AlexWorking** [comment]
Hi @PedroKTFC. Problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository. Please reopen Your issue there. Thank You.
