### ISSUE TITLE
Need help with Ship API Call

### ISSUE THREAD

**Issue by DhanyaSoft** [magento/magento2#23212]
Hi,

I am trying to do the partial shipping in Magento2.
The Ship API call marks all the line items shipped, instead of the one I am sending in the request.
Please see my request below, I am shipping only this SKU 1014.
But it has shipped the entire order. 
Can someone help me what I am doing wrong?

Magento version: 2.2.5

This is my request
https://mydomain.com/rest/V1/order/43043/ship/

Body
-----

{
  "entity": {
    "items": [
      {
        "order_item_id": 328962,
        "qty": 1
      }
    ],
    "notify": false,
    "appendComment": false,
    "comment": null,
    "tracks": null,
    "packages": null,
    "arguments": null,
    "orderId": 43043
  }
}

![image](https://user-images.githubusercontent.com/51720002/59299307-f76d2e00-8ca9-11e9-972e-9262816f8626.png)

**Comment by AlexWorking** [comment]
Hello @DhanyaSoft. The GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. Thank You.
