### ISSUE TITLE
While editing Product Knockout Error: Unable to process binding "if: function(){return label }"

### ISSUE THREAD

**Issue by ghost** [magento/magento2#23217]
![Screenshot from 2019-06-12 10-07-33](https://user-images.githubusercontent.com/24873505/59323942-82761480-8cfa-11e9-9398-c4ab408acd12.png)
Please check attached Screenshot...
Please provide us the solution.

**Comment by EternalBobby** [comment]
Hello @himanitayal ! The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) Or slack channel,  for advice or general discussion about this issue.
