### ISSUE TITLE
advanced pricing displays price correct in product page but not in product archive 

### ISSUE THREAD

**Issue by sims158** [magento/magento2#23223]
Hi, we have a site that is displaying the prices incorrectly. In the product page, it is correct, but not in product archive. The issues is related to advanced pricing, for some reason magento is adding the tax (20%) twice in product archive view, but not in product page view. 

Example: Product page price displays as follows.
£13.73 
Ex VAT £11.43
Buy 5 for £13.19 (ex VAT £10.99)  each and save 4% 

Product archive displays the price as follows.
£13.72
Ex VAT £11.43
As low as
£15.83

That final price, £15.83 should be £13.99 as it is in the product page

Magento version 2.3.1. Apache server. PHP version 7

**Comment by EternalBobby** [comment]
Hello @sims158 ! Thank you for your report . Please provide steps to reproduce this issue and update your post .

**Comment by sims158** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @sims158. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sims158, here is your [Magento instance](https://i-23223-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23223-2-3-develop.instances.magento-community.engineering/admin](https://i-23223-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sims158** [comment]
Can't replicate it, PLEASE HELP

**Comment by engcom-Bravo** [comment]
Hi @sims158. Please at least specify what exactly You mean under term of Product archive.

**Comment by sims158** [comment]
Product list on the home page or in any category page

**Comment by engcom-Bravo** [comment]
@sims158 We still need the detailed steps You made in order to get those results described above.

**Comment by engcom-Bravo** [comment]
@sims158 we are closing this issue as we can not reproduce it following the steps given. Please feel free to reopen it if You find the way to reproduce it. Thank You for applying.
