### ISSUE TITLE
Overriding di.xml config reader

### ISSUE THREAD

**Issue by vernard** [magento/magento2#2322]
Hi,

I'm trying to create an extension that can disable/enable my other extensions.

When an extension is disabled, its `menu.xml` entries will be ignored. I did this using a plugin in the class `Magento\Backend\Model\Menu\Config\Reader`.

Same idea for `indexer.xml`, `system.xml`.

However, I had problems overriding the config reader for `di.xml`. Any ideas?

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
