### ISSUE TITLE
Unable to change theme in magento 2.31

### ISSUE THREAD

**Issue by arjunrai1t** [magento/magento2#23220]
I am not able to override magento theme in admin ver 2.3.1 .its always set to no theme option please give me solution

**Comment by EternalBobby** [comment]
Hello @ArjunItaeld ! The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) Or slack channel,  for advice or general discussion about this issue.
