### ISSUE TITLE
Customer does not receive refund for a second order with the same money value

### ISSUE THREAD

**Issue by cliveontoast** [magento/magento2#23229]
### Preconditions (*)

2.2.5

### Steps to reproduce (*)

1. A customer creates two identical orders, same credit card (different names on the credit card), for the same line items, for the same price. Created on the same day, within minutes of each other.
2. The stock is not available so a refund is made.
3. The refund is processed, showing a total of four transactions, two refunds with two parents.
4. The customer only receives one refund transaction on their credit card.

### Expected result (*)

1. The customer's credit card transactions would show four transactions. Two negative money transactions, and two positive money refund transactions.

### Actual result (*)

1. No errors.
2. The software reports four transactions.
3. The customer only has three transactions on their credit card. The second refund never occurred.
4. The customer creates a disputed transaction with their bank to resolve the issue.
5. Haven't worked this part out yet, lets see what the bank says.

P.S.
Yes this is the customer creating this issue, I'm creating it because I've got a print out of the two orders, both saying they're refunded.. and only one has been.

This might not be the software's problem. But it will become a problem of one of the magento customers in 1-10 business days.

**Comment by ktpl-rammohan** [comment]
Hello @cliveontoast, understood your concern but it seems like a problem with the  Bank operator. please check with the Bank operators.
Thanks.

**Comment by cliveontoast** [comment]
Thanks for the follow up @rammohan-krish 
Me not being a customer of magento2 just the humble consumer, I can't reproduce the issue. I also understand how it is hard for integration testing with banks and payment gateways. I've let your customer know about this issue, and hopefully they can provide some logs. Otherwise scratch it up to a not your problem.

**Comment by ktpl-rammohan** [comment]
@cliveontoast Noted, I will surely investigate further on this but for now, I am closing the issue.

Also if you found and specific cause/steps to reproduce for this issue in the future. please comment here so that I will reopen and confirm the issue.

Thanks.
