### ISSUE TITLE
Stock Sources Import - Maximum error count has been reached or system error is occurred!

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#23249]
### Preconditions (*)

Running Magento 2.3.1, no modules installed. 
PHP 7.2
MySQL 5.7

### Steps to reproduce (*)

System -> Import -> Stock Sources
Export the sample data and adjust SKU and adjust the QTY

Content of csv: 
source_code,sku,status,quantity
default,20140603,1,12

![Screenshot 2019-06-13 at 19 45 31](https://user-images.githubusercontent.com/1254741/59455188-f3f5b600-8e13-11e9-8d8e-60d7f492283a.png)

### Expected result (*)
Update the inventory successfully.

### Actual result (*)
![Screenshot 2019-06-13 at 19 45 39](https://user-images.githubusercontent.com/1254741/59455162-e93b2100-8e13-11e9-9a7f-d00d5e6c854e.png)

**Comment by oefterdal** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oefterdal. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @oefterdal, here is your [Magento instance](https://i-23249-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23249-2-3-develop.instances.magento-community.engineering/admin](https://i-23249-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by oefterdal** [comment]
@magento give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oefterdal. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by oefterdal** [comment]
@magento-engcom-team Same error on vanilla install

**Comment by oefterdal** [comment]
@magento give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oefterdal. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by oefterdal** [comment]
This module was making the problem firegento/fastsimpleimport

**Comment by ansarul121** [comment]
I am also facing the same error 

Maximum error count has been reached or system error is occurred!

My Magento Version:2.3.4
