### ISSUE TITLE
Urgent please :: {"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/571656540374" }]}}

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2324]
Impossible to execute coupon code in cart or checkout when having more then one different products in the shopping cart.

Reproduce:
1. make an auto generated coupon code that does a discount for the whole cart. Condition is that the subtotal minimum of x is met.
2. one single products to the cart and apply the coupon code --> this works just fine
3. now add a different product to the cart (the two products must be different sku)
4. apply the coupon code (iin the cart or the checkout; doesn't matter)
5. result:  {"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/571656540374" }]}}
![2015-11-11_09h54_59](https://cloud.githubusercontent.com/assets/13572447/11087419/6f02c7f2-885a-11e5-872e-315bf63121f7.png)
![2015-11-11_09h47_41](https://cloud.githubusercontent.com/assets/13572447/11087429/80bf023a-885a-11e5-9945-b04a171f2d7f.png)

**Comment by ishakhsuvarov** [comment]
@SidneyBilliet Thank you for reporting the issue.
I could not reproduce the error you described on the latest commit, could you please check if there are any additional conditions and provide the generated error report?

**Comment by vrann** [comment]
Can you show the contents of the var/report/571656540374 file?
If it is not possible, please enable developer mode (uncomment "SetEnv MAGE_MODE developer" in root .htaccess) and run your test again -- you will be able to see the stack trace.

**Comment by SidneyBilliet** [comment]
Here is the content of the file api/571656540374


s:213:"Fatal Error: 'Cannot use assign-op operators with overloaded objects nor string offsets' in '/var/www/www.giftsandbottles.com/wwwroot/app/code/Magento/SalesRule/Model/Rule/Action/Discount/CartFixed.php' on line 70"

**Comment by SidneyBilliet** [comment]
Haven't had this problem since Magento ver. 2.0.0
