### ISSUE TITLE
Admin does not receive order email confirmations

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#23258]
### Preconditions (*)

1. Magento 2.3.1
2. Sales Email Order Enabled
3. Asynchronous sending Disabled

### Steps to reproduce (*)

1. Go to Configuration
2. Sales > Sales Emails > Order > Send Order Email Copy To
3. Put one email as admin's email here
4. Create new customer with work email
5. Place new order
### Expected result (*)

1. Customer receive email order confirm
3. Admin should receive email copy

### Actual result (*)

1. Customer received email order confirm
2. Admin not receive any email

**Comment by mrtuvn** [comment]
@magento give me 2.3 instance

**Comment by engcom-Bravo** [comment]
Hello @mrtuvn. Thanks for reporting. We've been not able to reproduce Your issue. Can You confirm You are able to reproduce it on a vanilla Magento instance of the latest 2.3-develop version?

**Comment by mrtuvn** [comment]
i'm using 2.3.1 vanilla. Not test with 2.3-develop

**Comment by engcom-Bravo** [comment]
@mrtuvn, we still have to ask You to test it on 2.3-develop instance. Because in case You are successfull in that we will be looking for what we are missing now for being able to reproduce the issue. And once we'll have found what it is we will confirm the issue. In case You also cannot reproduce the issue it will mean the issue has been fixed and we'll be supposed to close it.

**Comment by mrtuvn** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn, here is your [Magento instance](https://i-23258-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23258-2-3-develop.instances.magento-community.engineering/admin](https://i-23258-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment]
Tested today with 2.3-develop branch
Used mailhog with SMTP client module by Mageplaza in my local machine! Everything set. Email admin set, Customer email set But after place order only customer receive email in mailhog and i don't see email to admin
![Screenshot from 2019-06-15 18-15-35](https://user-images.githubusercontent.com/1908873/59550828-0e599c00-8f9a-11e9-8089-d327a1694afe.png)

![Screenshot from 2019-06-15 18-19-29](https://user-images.githubusercontent.com/1908873/59550841-3c3ee080-8f9a-11e9-8966-37d70f3d99a8.png)

**Comment by hostep** [comment]
@mrtuvn: Mailhog [doesn't support BCC headers](https://github.com/mailhog/MailHog/issues/98), maybe try by sending a separate email?

**Comment by hostep** [comment]
Just tested this myself on Magento 2.3.1, with Mailhog and the configuration `Send Order Email Copy Method` set to `Separate Email` and it works perfectly fine, 2 emails are send:

<img width="920" alt="Screenshot 2019-06-16 at 10 57 23" src="https://user-images.githubusercontent.com/85479/59561905-df890780-9025-11e9-9e68-3c60853dc091.png">

Closing for now, if you still run into this problem without some local mailcatcher tool, let me know and we can review this again.
