### ISSUE TITLE
Search doesn't always return product

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#2325]
I found a problem with search on my website.

We have these products:

- "WERKHANDSCHOEN THERMISCHE VOERING L"
- "ROYAL CANIN SHIH TZU - ADULT - HONDENVOER - 500 GR"

When I type in the searchterm "VOER", it should return both products. But only the first one is returned. Is this a bug?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
