### ISSUE TITLE
Unit testing fails in 2.3.1

### ISSUE THREAD

**Issue by vignates** [magento/magento2#23259]
### Preconditions (*)
In Magento 2.3.1 opensource version, run unit tests with the fresh installation.

### Steps to reproduce (*)
In Magento 2.3.1 opensource version, run unit tests with the fresh installation.
`php bin/magento dev:tests:run unit`

### Expected result (*)
1. All tests should pass

### Actual result (*)
1.ERRORS!
Tests: 21787, Assertions: 60740, Errors: 3, Failures: 17, Skipped: 129, Incomplete: 44.

Errors:
`
Time: 3.64 minutes, Memory: 2074.00MB

There were 3 errors:

1) Magento\Catalog\Test\Unit\Model\Product\TierPriceManagementTest::testSetNewPriceWithGlobalPriceScopeAll
Magento\Framework\Exception\InputException: The data was invalid. Verify the data and try again.

/var/www/html/vendor/magento/module-catalog/Model/Product/TierPriceManagement.php:94
/var/www/html/vendor/magento/module-catalog/Test/Unit/Model/Product/TierPriceManagementTest.php:271

2) Magento\Catalog\Test\Unit\Model\Product\TierPriceManagementTest::testSetNewPriceWithGlobalPriceScope
Magento\Framework\Exception\InputException: The data was invalid. Verify the data and try again.

/var/www/html/vendor/magento/module-catalog/Model/Product/TierPriceManagement.php:94
/var/www/html/vendor/magento/module-catalog/Test/Unit/Model/Product/TierPriceManagementTest.php:302

3) Magento\Catalog\Test\Unit\Model\Product\TierPriceManagementTest::testSetUpdatedPriceWithGlobalPriceScope
Magento\Framework\Exception\InputException: The data was invalid. Verify the data and try again.

/var/www/html/vendor/magento/module-catalog/Model/Product/TierPriceManagement.php:94
/var/www/html/vendor/magento/module-catalog/Test/Unit/Model/Product/TierPriceManagementTest.php:329

--

There were 17 failures:

1) Magento\Catalog\Test\Unit\Model\Product\TierPriceManagementTest::testSetThrowsExceptionIfDoesntValidate
Failed asserting that exception message 'The data was invalid. Verify the data and try again.' contains 'Values in the attr1, attr2 attributes are invalid. Verify the values and try again.'.

2) Magento\Catalog\Test\Unit\Model\Product\TierPriceManagementTest::testSetThrowsExceptionIfCantSave
Failed asserting that exception of type "Magento\Framework\Exception\InputException" matches expected exception "\Magento\Framework\Exception\CouldNotSaveException". Message was: "The data was invalid. Verify the data and try again." at
/var/www/html/vendor/magento/module-catalog/Model/Product/TierPriceManagement.php:94
/var/www/html/vendor/magento/module-catalog/Test/Unit/Model/Product/TierPriceManagementTest.php:371
.

3) Magento\Catalog\Test\Unit\Model\Product\TierPriceManagementTest::testAddRethrowsTemporaryStateExceptionIfRecoverableErrorOccurred
Failed asserting that exception of type "Magento\Framework\Exception\InputException" matches expected exception "\Magento\Framework\Exception\TemporaryState\CouldNotSaveException". Message was: "The data was invalid. Verify the data and try again." at
/var/www/html/vendor/magento/module-catalog/Model/Product/TierPriceManagement.php:94
/var/www/html/vendor/magento/module-catalog/Test/Unit/Model/Product/TierPriceManagementTest.php:395
.

4) Magento\Config\Test\Unit\Model\Config\Structure\ReaderTest::testReadWithValidationException
Failed asserting that exception of type "TypeError" matches expected exception "\Magento\Framework\Exception\LocalizedException". Message was: "Argument 1 passed to Mock_CompilerInterface_a8958148::compile() must be an instance of DOMNode, null given, called in /var/www/html/vendor/magento/module-config/Model/Config/Structure/Reader.php on line 143" at
/var/www/html/vendor/magento/module-config/Model/Config/Structure/Reader.php:143
/var/www/html/vendor/magento/module-config/Model/Config/Structure/Reader.php:93
/var/www/html/vendor/magento/framework/Config/Reader/Filesystem.php:132
/var/www/html/vendor/magento/module-config/Test/Unit/Model/Config/Structure/ReaderTest.php:121
.

5) Magento\ProductVideo\Test\Unit\Controller\Adminhtml\Product\Gallery\RetrieveImageTest::testExecute
Expectation failed for method name is equal to 'getDirectoryWrite' when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

6) Magento\Framework\Test\Unit\ShellTest::testExecute with data set "STDOUT" ('php -r %s', array('echo 27181;'), '27181', array('php -r `echo 27181;` 2>&1', '27181'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27181'
+27181'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:42
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:57

7) Magento\Framework\Test\Unit\ShellTest::testExecute with data set "STDERR" ('php -r %s', array('fwrite(STDERR, 27182);'), '27182', array('php -r `fwrite(STDERR, 27182);` 2>&1', '27182'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27182'
+27182'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:42
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:57

8) Magento\Framework\Test\Unit\ShellTest::testExecute with data set "piping STDERR -> STDOUT" ('php -r %s|php -r %s', array('fwrite(STDERR, 27183);', 'echo fgets(STDIN);'), '27183', array('php -r `fwrite(STDERR, 27183)...` 2>&1', '27183'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27183'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:42
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:57

9) Magento\Framework\Test\Unit\ShellTest::testExecute with data set "piping STDERR -> STDERR" ('php -r %s | php -r %s', array('fwrite(STDERR, 27184);', 'fwrite(STDERR, fgets(STDIN));'), '27184', array('php -r `fwrite(STDERR, 27184)...` 2>&1', '27184'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27184'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:42
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:57

10) Magento\Framework\Test\Unit\ShellTest::testExecuteLog with data set "STDOUT" ('php -r %s', array('echo 27181;'), '27181', array('php -r `echo 27181;` 2>&1', '27181'))
Expectation failed for method name is equal to 'info' when invoked at sequence index 1
--- Expected
+++ Actual
@@ @@
-'27181'
+27181'

/var/www/html/vendor/magento/framework/Shell.php:81
/var/www/html/vendor/magento/framework/Shell.php:60
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:41
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:82

11) Magento\Framework\Test\Unit\ShellTest::testExecuteLog with data set "STDERR" ('php -r %s', array('fwrite(STDERR, 27182);'), '27182', array('php -r `fwrite(STDERR, 27182);` 2>&1', '27182'))
Expectation failed for method name is equal to 'info' when invoked at sequence index 1
--- Expected
+++ Actual
@@ @@
-'27182'
+27182'

/var/www/html/vendor/magento/framework/Shell.php:81
/var/www/html/vendor/magento/framework/Shell.php:60
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:41
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:82

12) Magento\Framework\Test\Unit\ShellTest::testExecuteLog with data set "piping STDERR -> STDOUT" ('php -r %s|php -r %s', array('fwrite(STDERR, 27183);', 'echo fgets(STDIN);'), '27183', array('php -r `fwrite(STDERR, 27183)...` 2>&1', '27183'))
Expectation failed for method name is equal to 'info' when invoked at sequence index 1
--- Expected
+++ Actual
@@ @@
-'27183'

/var/www/html/vendor/magento/framework/Shell.php:81
/var/www/html/vendor/magento/framework/Shell.php:60
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:41
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:82

13) Magento\Framework\Test\Unit\ShellTest::testExecuteLog with data set "piping STDERR -> STDERR" ('php -r %s | php -r %s', array('fwrite(STDERR, 27184);', 'fwrite(STDERR, fgets(STDIN));'), '27184', array('php -r `fwrite(STDERR, 27184)...` 2>&1', '27184'))
Expectation failed for method name is equal to 'info' when invoked at sequence index 1
--- Expected
+++ Actual
@@ @@
-'27184'

/var/www/html/vendor/magento/framework/Shell.php:81
/var/www/html/vendor/magento/framework/Shell.php:60
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:41
/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:82

14) Magento\Framework\Test\Unit\ShellTest::testExecuteFailureDetails with data set "STDOUT" ('php -r %s', array('echo 27181;'), '27181', array('php -r `echo 27181;` 2>&1', '27181'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27181'
+27181'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:141

15) Magento\Framework\Test\Unit\ShellTest::testExecuteFailureDetails with data set "STDERR" ('php -r %s', array('fwrite(STDERR, 27182);'), '27182', array('php -r `fwrite(STDERR, 27182);` 2>&1', '27182'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27182'
+27182'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:141

16) Magento\Framework\Test\Unit\ShellTest::testExecuteFailureDetails with data set "piping STDERR -> STDOUT" ('php -r %s|php -r %s', array('fwrite(STDERR, 27183);', 'echo fgets(STDIN);'), '27183', array('php -r `fwrite(STDERR, 27183)...` 2>&1', '27183'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27183'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:141

17) Magento\Framework\Test\Unit\ShellTest::testExecuteFailureDetails with data set "piping STDERR -> STDERR" ('php -r %s | php -r %s', array('fwrite(STDERR, 27184);', 'fwrite(STDERR, fgets(STDIN));'), '27184', array('php -r `fwrite(STDERR, 27184)...` 2>&1', '27184'))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'27184'

/var/www/html/vendor/magento/framework/Test/Unit/ShellTest.php:141

ERRORS!
Tests: 21787, Assertions: 60740, Errors: 3, Failures: 17, Skipped: 129, Incomplete: 44.

---- /var/www/html/dev/tests/static/framework/tests/unit> /usr/bin/php7.1 /var/www/html/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

...............................................................................................                                  95 / 95 (100%)

Time: 3.58 seconds, Memory: 12.00MB

OK (95 tests, 138 assertions)

---- /var/www/html/dev/tests/integration/framework/tests/unit> /usr/bin/php7.1 /var/www/html/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

.............................................................................................................................. 126 / 181 ( 69%)
.............................S.........................                                                                        181 / 181 (100%)

Time: 1.06 seconds, Memory: 18.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 181, Assertions: 365, Skipped: 1.
----------------------------------------------------------------------
FAILED - 1 of 3:
 - /var/www/html/dev/tests/unit> /usr/bin/php7.1 /var/www/html/./vendor/phpunit/phpunit/phpunit 

`

**Comment by engcom-Charlie** [comment]
Hello @vignates ! 
Thank you for your report . I can`t reproduce this issue on Magento 2.3

**Comment by mani513** [comment]
Hello @engcom-Charlie 
I've downloaded your https://github.com/magento/magento2.git clone and i'm also facing the same issue, can you please help me to resolve this issue.
