### ISSUE TITLE
Importing custom LESS on compact deployment strategy

### ISSUE THREAD

**Issue by danielgoodwin97** [magento/magento2#23260]
### Preconditions (*)
1. Magento 2.3.x
2. A theme which extends blank and also has a child (blank -> parent -> child)

### Steps to reproduce (*)
1. Create new child theme of Magento/blank
2. Add a magento import rule for a custom less file inside `web/css/styles-l.less` & `web/css/styles-m.less` in your new theme
`//@magento_import 'source/_extend-child.less';`
3. Create new child theme of new parent theme
4. Create an `_extend-child.less` in any modules `<Vendor>_<Module>/web/css/source` directory
5. Add any styles to the `_extend-child.less` for example:
`body {
    background-color: red;
}`
6. Run `php bin/magento setup:upgrade`
7. Remove any existing static content using this command
`rm -rf pub/static/deployed-version.txt && rm -rf pub/static/frontend && rm -rf pub/static/adminhtml`
8. Deploy static content with the compact strategy enabled
`php ./bin/magento setup:static-content:deploy --ansi --no-interaction -f -s compact --jobs 1 --no-html-minify`
9. Load page and none of your LESS changes will be there.
10. Remove static content again using the same commands in step 7
11. Run static content deploy using the quick strategy and it will work perfectly.
`php ./bin/magento setup:static-content:deploy --ansi --no-interaction -f --jobs 1 --no-html-minify`

### Expected result (*)
1. LESS changes to take effect. All changes are included via the import.

### Actual result (*)

1. LESS changes do not take effect. Nothing is included from the import.

It only seems to happen when you have at least 3 layers of themes (blank => parent => child), with 2 layers of themes, it works fine (blank => child).

**Comment by hostep** [comment]
Also seeing this problem using Magento 2.3.2.
Switching from the `compact` strategy to `quick` or `standard` fixes the issue.

It only seems to happen when you have at least 3 layers of themes (blank => parent => child), with 2 layers of themes, it works fine (blank => child).

So I can confirm @danielgoodwin97's finding.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21658` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @danielgoodwin97. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-21658` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
