### ISSUE TITLE
"Static Files Settings" still have BUG,  below  php-fpm + nginx

### ISSUE THREAD

**Issue by Shop123admin** [magento/magento2#2326]
PHP 5.6.15 (fpm-fcgi) 
Nginx 1.8 

STORES--> Configuration --> ADVANCED --> Developer -->Static Files Settings

If set it to YES,  All static files are not displayed .

![1](https://cloud.githubusercontent.com/assets/15684656/11088247/a0af6dd2-889b-11e5-9d7e-3bb4ee472803.png)
![2](https://cloud.githubusercontent.com/assets/15684656/11088262/cfe03488-889b-11e5-9620-c82ca5e9f268.png)

If the web server is apache, then everything is normal.

**Comment by ad1s** [comment]
In the nginx conf file, the static-folder is in root. But it's actually inside the pub-folder. 
Just add "pub/" before any "static/"-reference inside the static-location-block:

location /**pub/**static/ {
if ($MAGE_MODE = "production") {
	expires max;
}
location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
	add_header Cache-Control "public";
	add_header X-Frame-Options "SAMEORIGIN";
	expires +1y;

if (!-f $request_filename) {
    rewrite ^/**pub/**static/(version\d*/)?(.*)$ /**pub/**static.php?resource=$2 last;
}
}
location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
	add_header Cache-Control "no-store";
	add_header X-Frame-Options "SAMEORIGIN";
	expires    off;

if (!-f $request_filename) {
   rewrite ^/**pub/**static/(version\d*/)?(.*)$ /**pub/**static.php?resource=$2 last;
}
}
if (!-f $request_filename) {
	rewrite ^/**pub/**static/(version\d*/)?(.*)$ /**pub/**static.php?resource=$2 last;
}
add_header X-Frame-Options "SAMEORIGIN";
}

**Comment by defyasdf** [comment]
Hi @ad1s 
I have same problem and my vhost:
```
server
{   
  listen 8080; 
  server_name demo.xxx.com;
  set $MAGE_ROOT /home/xxx/wwwroot/;
  set $MAGE_MODE developer;
  include /home/xxx/wwwroot/nginx.conf.sample;
}```
if disable the `Static Files Settings` it's all well.
when enable 'Static Files Settings' some of the js file is not find.so I can't fix this.Can some help?

**Comment by guoping001** [comment]
I 'm using  the "nginx.conf.sample" in magento's root directory.

Other places are normal, But missing some js files if enable the "Static Files Settings".

You can see the screenshots, some files are still there but some js file was missed.

**Comment by mazhalai** [comment]
#2323 has been merged, @Shop123admin have you checked on the latest develop?

**Comment by maksek** [comment]
closing due inactivity, PR was merged.
