### ISSUE TITLE
Product'ss images cache not displayed /regenerated after Flush Catalog Images Caches

### ISSUE THREAD

**Issue by 29sunil** [magento/magento2#23262]
### Preconditions (*)

1.Magento 2.3.0
2. Mysql 5.6.41
3. Php 7.1

### Steps to reproduce (*)

1. Go on Magento's Backed and click on: Flush Catalog Images Cache

### Expected result (*)

1.All product images will show at category list page and detail page

### Actual result (*)

1. The image of Catalog of product on frontend and backend are displayed correctly
1.No apache errors, php or exception thrown
3. We are using this command to regenerate the images ( php bin/magento catalog:image:resize ). But this is not a solution. The client is not able to use this step.

**Comment by engcom-Bravo** [comment]
Hello @29sunil. Thanks for reporting. We don't clearly comprehend what is wrong with the Actual Result You are facing and where is the discrepancy with the Expected Result: "The image of Catalog of product on frontend and backend are displayed **correctly**". Do You mean **"not correctly"** or something like that?

**Comment by 29sunil** [comment]
Hello Team,
Thanks for support
The images of the product shown in the admin section and frontend. but after flush catalog images cache from Magento admin, images are not showing at frontend category page and product page.
To show these images we need to regenerate images using this command. 
**php bin/magento catalog:image:resize**
Print screen: https://prnt.sc/o1rxac
                   https://prnt.sc/o1rxlb
Website URL: https://www.sofasupply.nl
Right now images are showing at category page and details. Because we have regenerated images. 
If there is any server configuration missing then let us know. 
which PHP extension is used for image cache at a server. 
Thanks

**Comment by engcom-Bravo** [comment]
@29sunil, please watch the attached video. Have we done everything as You meant?
![imagecache](https://user-images.githubusercontent.com/51680745/59505892-6d8eb200-8eaf-11e9-99dd-0b0b9bd14f1a.gif)
At the Product detail page images would also be displayed.

**Comment by 29sunil** [comment]
Hello Team,
Thanks for reply
Please check below video and print screen. Please check the website now. Please check category page and details page. Now we need to use this command to generate images.
**php bin/magento catalog:image:resize**
https://www.sofasupply.nl/woonkamer/tafels/bijzettafels.html

Flush Catalog Images Cache  Pregenerated product images files

Print screen: https://prnt.sc/o1spxq
              https://prnt.sc/o1snya

Without theme 
https://www.loom.com/share/0d5ff2a4426c4d019318c8322a36d382


With theme:
https://www.loom.com/share/98ab3bff5adf47ffb8e9c04286703cbd

**Comment by 29sunil** [comment]
There are more than 3558 product images. Now  We have run this command to regenerate imges.
php bin/magento catalog:image:resize

**Comment by engcom-Bravo** [comment]
Ok, @29sunil, but please point us out what we did incorrectly in our video, what we did not like You mean in Your steps to reproduce. As we understand You want to get the images being regenerated without **php bin/magento catalog:image:resize**. We didn't use that command and our images remain displayed, probably we miss something?

**Comment by 29sunil** [comment]
Hello Team,
Yes, I see your video. The same thing works at my local system. But we are facing these issues at the live website.  if there were any server related issues then let us know. What we suggest to the client regarding these issues.  how we solve it. 
This is not the right solution ( php bin/magento catalog:image:resize ).
That is the reason we are posting our query here.
Hopefully, the Magento team provide solutions 
Thanks

**Comment by anthonyhacart** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @anthonyhacart. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anthonyhacart, here is your [Magento instance](https://i-23262-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23262-2-3-develop.instances.magento-community.engineering/admin](https://i-23262-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 29sunil** [comment]
Hello Team,
Thanks for sharing instance
This instance working fine with image upload.  As i already say that image upload is working fine at our local system. 
But we are facing the issue at client server.  What are the solutions to this problem?
What we say to the client regarding these issues.   its seems that issues are not related to magneto or any premium theme.  Because the same thing happens with default and premium theme. 

If it is server issues then tell us solutions. what is missing at this server?

**Comment by Nazar65** [comment]
@29sunil same here https://github.com/magento/magento2/issues/22808 did you upgraded from 2.2 version ?

**Comment by 29sunil** [comment]
Hello  Team,
We have migrated data from magento1 to Magento 2. Now, these catalog images issues are generated.
Kindly suggest these issues. 
Thanks

**Comment by engcom-Bravo** [comment]
Hi again @29sunil. The GitHub issue tracker is intended for Magento Core technical issues only. If You are not able to reproduce it on a vanilla instance locally or on other server like the one we provided You with ( https://i-23262-2-3-develop.instances.magento-community.engineering) its not an issue relevant for this repository. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. Also as You migrated from magento1 You may post Your issue on the specially opened for such issues repository https://github.com/magento/data-migration-tool. With that we are closing this issue here. Thank You for applying.

**Comment by zolthan** [comment]
We can reproduce this issue with a Magento 2 Apache instance. In the pub/.htaccess the following lines are missing in the section `<IfModule mod_rewrite.c>` in about line 150 before the final rewrite rules for existing files:

```
############################################
## Rewrite for non-existing files, directories and links in media

	RewriteCond %{REQUEST_URI} ^/media
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-l
	RewriteRule media/(.*) get.php?$1 [L]
```

@engcom-Bravo could you please reopen this ticket? An Apache installation doesn't process the media files through `pub/get.php`. For nginx the directives in line https://github.com/magento/magento2/blob/ee6bc3729e85ed1f1b5cd7c0eb9a3800bdd274c5/nginx.conf.sample#L136 ff are taking care of the processing.

**Comment by engcom-Bravo** [comment]
Hi @zolthan. Would You please describe the steps You make on a vanilla Magento instalation in order to reproduce the issue. Thank You.

**Comment by zolthan** [comment]
Hi @engcom-Bravo ,
we just have an Apache setup and clear the image cache via backend.

Afterwards any calls to the cached files (that currently don't exist) are running on a 404 error as there is no rewrite rule in pub/.htaccess to catch media requests and redirect them to pub/get.php where the image processing takes place.

After running `bin/magento catalog:images:resize` the requests for product images on the category page succeed.

Best Sebastian

**Comment by engcom-Bravo** [comment]
@zolthan I would yet have two questions to You (probably with the obvious answers but):
1. Are You running Your Magento in the Production mode and
2. Is Your Mageento root directory is configured to be "pub"?

**Comment by zolthan** [comment]
Yes and yes. It makes no difference in which mode Magento is running in this case.

**Comment by engcom-Bravo** [comment]
@zolthan, when I asked You to provide the the steps to reproduce You described the essence of reproduction. But I need the concrete and detailed steps that lead to reproduction. At least watch my [video above](https://github.com/magento/magento2/issues/23262#issuecomment-502071375). I did not replenish .htaccess with any rewrite conditions and everything works as expected. I just followed the steps provided by the issue reporter. Yes pub/media/catalog/product/cache is deleted as it is supposed to be after Flush Catalog Images Caches, but it is successfully regenerated when You for example first enter the catalog on the Frontend. So please tell what I'm missing in the video or doing something not as You mean. Thank You.

**Comment by hostep** [comment]
I also did some quick testing myself as well and couldn't reproduce the problem. I was using Apache 2.4.39 and PHP 7.2.19
Magento was in production mode and `pub` was used as documentroot.

I could see the `get.php` file being called by simply putting a `die();` statement in there and noticing the image not being generated. After removing the `die();`, the image got generated.

So it looks like everything works and there is no bug. Maybe there is some weird Apache configuration going which causes your issue @zolthan?

**Comment by zolthan** [comment]
It could be a crappy Apache config. The server with the mentioned problem is not managed by us, so I can‘t see the complete configuration. 

But what I don’t understand is, how the redirect to  get.php is working without the redirect? For nginx there is an explicit redirect. Could you show M.E. how that works?

**Comment by hostep** [comment]
@zolthan: the rewrite is in [the `pub/media/.htaccess` file](https://github.com/magento/magento2/blob/bfa0fd440c499ceb6016e78f21599db89ece6306/pub/media/.htaccess#L18-L37), maybe you accidentally deleted that file?

**Comment by zolthan** [comment]
Thank you @hostep you did it. Some automated deployment processes removed the additional htaccess files in pub.

So I'm out here. Everything is working fine now.

**Comment by hostep** [comment]
Excellent!

@29sunil: you might have the same problem then? Did this discussion above help you as well?

**Comment by ebanolopes** [comment]
Hello, this is an old one, but I had some issues with images on my store on this scenario: when the resized image was not on images cache, then the first time it was requested an empty image was returned. The second request and on everything was working. But we had a CDN caching images, so, many times the empty images end up cached on CDN.

The issue was a PHP file with two leading spaces at the top of it, something like this:

```php
1
2
3 <?php
```

More specifically this leading lines were on a registration.php of a admin theme.

After removing the leading lines from this file everything worked as expected.

**Comment by wingsryder** [comment]
> @zolthan: the rewrite is in [the `pub/media/.htaccess` file](https://github.com/magento/magento2/blob/bfa0fd440c499ceb6016e78f21599db89ece6306/pub/media/.htaccess#L18-L37), maybe you accidentally deleted that file?

This had fixed my issue.
