### ISSUE TITLE
Configurable products showing zero 0 price after assigning to secondary website when indexers set to schedule

### ISSUE THREAD

**Issue by JamesAllwood** [magento/magento2#23261]
When indexers are set to `Update by Schedule`, assigning a configurable product and associated simples to a secondary website, does not update the price indexes, and subsequently, the product displays a price of £0(zero) on the second website until a simple product is selected. 

This is specific to the use of `Update by Schedule`. If indexers are set to `Update on Save`, the issue does not occur.

### Preconditions (*)

1. Vanilla Magento 2.2.8 
2. Two websites setup in admin
3. Cron is enabled to run changelog index updates

### Steps to reproduce (*)

1. Update indexers to `Update by Schedule`
2. Create a new configurable product and assign it and its child products to website 1. Ensure child products have prices set
3. Check configurable product on store front of website 1
4. Return to admin, and assign configurable product and associated simples to website 2
5. Check configurable product on store front of website 2

### Expected result (*)

1. I expect to see the configurable product loaded on the store front of website 1 to show the correct `As Low As` price.
2. I expect to see the configurable product loaded on the store front of website 2 to show the correct `As Low As` price.

![image](https://user-images.githubusercontent.com/5270957/59499580-9737e100-8e8f-11e9-97b3-86566b2f2f88.png)

### Actual result (*)

1. The `As Low As` price is displayed as £120 on website 1
2. The `As Low As` price is displayed as £0(zero) on website 2

![image](https://user-images.githubusercontent.com/5270957/59499752-f0077980-8e8f-11e9-92b5-2902a6ee27cb.png)

3. Price can only be rectified by manually running the the price indexer

**Comment by engcom-Charlie** [comment]
Hello @JamesAllwood ! 
Thank you for your report but i can`t reproduce this issue on a vanilla Magento instance of the latest 2.3-develop version.
