### ISSUE TITLE
Main navigation menu disappearing when enabling Varnish (Removing TTL attribute doesn't work)

### ISSUE THREAD

**Issue by Adrift** [magento/magento2#23276]
### Information of environment

- Magento CE 2.3.1
- PHP 7.1.26
- MySQL 5.7

### Summary

I'm developing a CE 2.3.1 site, which has a custom theme I've created enabled. I decided to enabled Varnish within the admin, set TTL to the default (86400) and then filled in the rest of config settings.

On the homepage, category page, product page there is no navigation. Strangely, the navigation does show on the checkout page. So I tried removing the TTL attribute from default.xml and after flushing Magento and browser cache the problem still exists.

I was wondering if anyone still has this issue or if someone has another workaround. Thank you.

**Comment by engcom-Charlie** [comment]
Hello @Adrift ! Thank you for your report ! 
Can you confirm that you are able reproduce your issue on Vanilla Magneto CE 2.3.1 ?

**Comment by Adrift** [comment]
Hey @engcom-Charlie I was not able to reproduce on Vanilla CE 2.3.1 so it's something related to the theme I developed. I'm still trying to pinpoint the cause, will update you if I find something.

**Comment by engcom-Charlie** [comment]
Hello @Adrift !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
