### ISSUE TITLE
Magento 2 Rest API Does not allow to use email with the Special character in "PUT" Method

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#23271]
I have installed the Magento 2.3.1.

I have generated the admin token to use Rest API.

I am using this API - http://prntscr.com/o1wpju

**Preconditions (*)**

Customer account with the email like this : testing+3@gmail.com (should have special character)

Here is command to use that API
curl -X PUT "http://www.website.com/index.php/rest/V1/customers/testing+3@gmail.com/activate" -H "Content-Type:application/json" -H "Authorization: Bearer no9wurama94bmq3brwagfns0dy06bch3" -d '{ "confirmationKey": "testing"}'

**Information on your environment**
I have installed the Magento 2.3.1.

**Steps to reproduce (*)**
Run this command on the SSH to activate the email and I am using M2 Rest API 
curl -X PUT "http://www.website.com/index.php/rest/V1/customers/testing+3@gmail.com/activate" -H "Content-Type:application/json" -H "Authorization: Bearer no9wurama94bmq3brwagfns0dy06bch3" -d '{ "confirmationKey": "testing"}'

**Expected result (*)**
It should be working like with the POST method, If we use the any API with the POST method and special character email then its working.

**Actual result (*)**
{"message":"No such entity with %fieldName = %fieldValue, %field2Name = %field2Value","parameters":{"fieldName":"email","fieldValue":"testing 3@gmail.com","field2Name":"websiteId","field2Value":"1"},"trace":"#0 \/vendor\/magento\/module-customer\/Model\/ResourceModel\/CustomerRepository.php(288): Magento\\Customer\\Model\\CustomerRegistry->retrieveByEmail('testing 3@gmai...', '1')\n#1 \/generated\/code\/Magento\/Customer\/Model\/ResourceModel\/CustomerRepository\/Interceptor.php(37): Magento\\Customer\\Model\\ResourceModel\\CustomerRepository->get('testing 3@gmai...', NULL)\n#2 \/vendor\/magento\/module-customer\/Model\/AccountManagement.php(458): Magento\\Customer\\Model\\ResourceModel\\CustomerRepository\\Interceptor->get('testing 3@gmai...')\n#3 \/generated\/code\/Magento\/Customer\/Model\/AccountManagement\/Interceptor.php(37): Magento\\Customer\\Model\\AccountManagement->activate('testing 3@gmai...', 'testing')\n#4 [internal function]: Magento\\Customer\\Model\\AccountManagement\\Interceptor->activate('testing 3@gmai...', 'testing')\n#5 \/vendor\/magento\/module-webapi\/Controller\/Rest.php(330): call_user_func_array(Array, Array)\n#6 \/vendor\/magento\/module-webapi\/Controller\/Rest.php(239): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#7 \/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#9 \/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(39): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#11 \/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#13 \/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#14 \/index.php(48): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#15 {main}"}

**Comment by jigar48** [comment]
yes

**Comment by engcom-Bravo** [comment]
Hello @jigar48. Thanks for applying. "+" character when passed in URL just as that will be interpreted as a space character. And it's not an issue of Magento or curl or whatever else. URLs originally work that way. if You want to pass the very "+" You ought to encode it. Use "%2B" instead of it and the request shall work. For Your case when You intended to pass "testing+3@gmail.com" just like that In fact You passed "testing 3@gmail.com". Try to pass this: "testing%2B@gmail.com".

**Comment by jigar48** [comment]
Thanks @engcom-Bravo. I have checked with the "%2B" and It showing the result 
"message":"Account already active"

so Its working. Thanks for checking.

I just concern about that end user will dont know how "+" character will be parsed to  API end points.

**Comment by engcom-Bravo** [comment]
Yes, @jigar48, I agree with You there is a problem: most of the end users will not know this thing with plus sign encoding. But unfortunately we can do nothing with it becouse it's not a thing invented by Magento. It's one of the common rules URLs behavior is submitted to. You may test it even through a browser. Here is an example with the random active currency-converting website. If You enter a URL like this "https://freecurrencyrates.com/en/convert-USD-EUR" You will get the rezult of conversion. Now if You change that URL to "https://freecurrencyrates.com/en/convert-USD+EUR" You will get a page wit 404 Status Code and this message "The requested URL USD EUR could not be found on this server." Notice: not "URL **USD+EUR** could not be found" but "URL **USD EUR** could not be found" With that we are closing this issue being glad we were helpfull to You.
