### ISSUE TITLE
Static Content Deploy -> ERRORS

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#2327]
Hi,

When i try to deploy the static content 
php -f bin/magento setup:static-content:deploy  the following error is recieved:
Compilation from source: 
frontend/Magento/luma/en_US/css/email-inline.less
variable @modal-slide-header__padding-vertical is undefined in file /m2/var/view_preprocessed/css/frontend/Magento/luma/en_US/css/source/_theme.less in _theme.less on line 254, column 37
252| //  Modal popup
253| @modal-action-close__font-size: @font-size__base;
254| @modal-slide-action-close__padding: @modal-slide-header__padding-vertical @modal-popup__padding;
255| 
256| //  Checkout tooltip icon
257| @checkout-tooltip-icon__font-size: 21px;>

I am also having missing css files on the frontend, seems there are some errors in the less files

**Comment by daim2k5** [comment]
Related issue #2273, #2306

**Comment by dfediuk** [comment]
My universal fix for all the «variable @modal-slide-header__padding-vertical is undefined» problems: https://mage2.pro/t/193
