### ISSUE TITLE
different themes for multi stores not working Magento 2.3.1

### ISSUE THREAD

**Issue by manjulabwi** [magento/magento2#23287]
Created child-themes and assigned to the corresponding stores at Magento admin. Below is the screenshot. 
![image](https://user-images.githubusercontent.com/51914234/59606950-f582ef00-912f-11e9-858e-db33a86da44e.png)
But, when switched to other stores at frontend, the default main store's theme getting applied for all the stores. Cleared cache, cleared pub/static, var/view_preprocessed, re-generated static content. Still NO use.

**Comment by engcom-Charlie** [comment]
Hello @manjulabwi ! 
Thank you for your report but i can`t reproduce your issue on Magento 2.3-develop and Magento 2.2.x
