### ISSUE TITLE
posible cookies limit excided in admin panel 

### ISSUE THREAD

**Issue by uchenic** [magento/magento2#2328]
when using admin panel for some time an error occures 
[error.txt](https://github.com/magento/magento2/files/31845/error.txt)
and when viewing browser cookies storage, it is clear that cookies duplicating

using magento 2.0.0-rc

**Comment by uchenic** [comment]
here is the  screen of the cookies storage
![2015-11-11-145006_1366x768_scrot](https://cloud.githubusercontent.com/assets/8637701/11091534/f04986c4-8883-11e5-8d4f-ad12fe2581a9.png)

**Comment by vrann** [comment]
Hi, @uchenic 
Can you please check this issue https://github.com/magento/magento2/issues/1500 which seems same as yours.

As far as I see the discussion, the suspicion there is that cookies are set not by Magento but by other system running on your domain

**Comment by uchenic** [comment]
I have this only with version 2.0.0-rc of Magento2 on Firefox 42.0 browser, Chromium 46.0 browser doesn't have this issue.

The site is using dedicated domain and there no other site using this domain.

**Comment by daim2k5** [comment]
Hi @uchenic have you tried this again with the magento 2 GA? If yes, have you still the issue?

**Comment by uchenic** [comment]
The problem has gone in magento2  GA
