### ISSUE TITLE
RC deploy via composer

### ISSUE THREAD

**Issue by luckyraul** [magento/magento2#2329]
With this config Magento2 core modules do not copy to their folders
```
"require": {
        "magento/product-community-edition": "2.0.0-rc",
        "magento/magento-composer-installer": "*",
        "php": "~5.5.0|~5.6.0|~7.0.0"
    },
    "extra": {
        "magento-root-dir": "public/",
        "magento-force": "override"
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "public/lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "public/setup/src/Magento/Setup/"
        }
    }
```
same config worked well with beta6

**Comment by mazhalai** [comment]
@luckyraul we have changed how magento is deployed via composer. Now modules will not be marshaled anymore and will work fine from any location, as long as a component is properly registered. Please see [this documentation](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/component-registration.html) for more details.

**Comment by luckyraul** [comment]
It's okay to load from vendor,  but now I get this error after clean install
```
"Cannot read contents from file "/var/www/shop.stagingxxx.net/releases/7/public/var/www/shop.stagingxxx.net/releases/7/vendor/magento/
module-ui/view/base/ui_component/etc/definition.xml" 
Warning!file_get_contents(/var/www/shop.stagingxxx.net/releases/7/public/var/www/shop.stagingxxx
.net/releases/7/vendor/magento/module-ui/view/base/ui_component/etc/definition.xml): failed to open stream: No such file or directory"
```

**Comment by luckyraul** [comment]
It's a problem of getting relative path from vendor

**Comment by mazhalai** [comment]
@luckyraul there is an issue with relative paths, please see [this comment](https://github.com/magento/magento2/issues/2293#issuecomment-154770033) for more details. Workaround is to ensure
> There is a known restriction that files currently must be under Magento base directory.

**Comment by luckyraul** [comment]
That's it, thanks.
