### ISSUE TITLE
Magento2 Customer can login with any wrong password

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#23296]
### Preconditions (*)
1- Magento 2.3.1
2- php 7.1

### Steps to reproduce (*)
1- open https://beta.jomlah.com/arabic
2- login using user: saleh.awal@gmail.com & password: 123 or any password you pick
3- it will login for any password you may pick

### Expected result (*)

1. system should prevent users with wrong passwords to log in 

### Actual result (*)
1. anyone can login with any password

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23296-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23296-2-3-develop.instances.magento-community.engineering/admin](https://i-23296-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@salehawal - In Default, Magento 2.3 instance login functionality is working fine. User can't able to login valid email and invalid password.
In your Magento instance, User can be able to log in any of the passwords. So please verify this issue in your custom code. This issue is related to your website.

@salehawal - Please update me whenever you have found the issue in your custom code and resolved it. so I will close this issue.

**Comment by salehawal** [comment]
if it is from my side, how can i debug to know which module is responsible for the issue?

**Comment by ajijshekh123** [comment]
@salehawal - Please enable and disable to every custom module which you are using in login functionality. Follow the debug process and verify the issue. 

@salehawal - This does not default Magento issue so now I am closing this issue. If you have detected the issue in Magento instance you can reopen the issue again.

**Comment by salehawal** [comment]
i did remove all 3rd part modules and still i was able to login with any password?

i do have 2 magento sites ( 2.2 & 2.3 ) running under the same server ( jomlah.com | beta.jomlah.com )

**Comment by ajijshekh123** [comment]
@salehawal - If I am not finding an issue in Default Magento Instance I can't open it. So, please check the issue in your end.
This below scenario will be happening on the login module.
1. Data Migration from 2.2 to 2.3
2. Custom module affected
3. Check your login page coding
4. JS Issue

**Comment by salehawal** [comment]
it was working just last week, the only thing we did b4 facing the issue is a composer update, i also recall that this issue did raise with 2.2 after the same thing composer update which was resolved by disabling until finding the conflict and contacting the 3rd part company

in this case, we disabled all, and still we were unable to locate the source of issue, how can we debug and find the source

**Comment by salehawal** [comment]
we checked the server side to see if there was anything wrong, didnt find anything, then can you please let us know where dose the authentication happends ( module >> file ) .. so that we can check the code .. thanks

also if there is a upgraded version from 2.3.1 > , let us know maybe the upgrade will fix the issue

![Screenshot from 2019-06-19 15-09-40](https://user-images.githubusercontent.com/3238761/59768249-54697500-92a4-11e9-91fc-58004342ea17.png)

**Comment by ajijshekh123** [comment]
@salehawal - Please first upgrade the Magento 2.3.1 instance and also check the varnish cache if you are using in your project.

**Comment by salehawal** [comment]
i have a nother app running in the same server with same config ( 2.2 ), no issues

currently the app i am having issue with is ( 2.3.1 ), is there later upgrades i can move to?

**Comment by salehawal** [comment]
issue was resolved, and here is the updated file that was causing the problem...
Location: app/app_jomlah.com/vendor/magento/framework/Encryption/Encryptor.php

Old Version
`
public function isValidHash($password, $hash)
{
    $this->explodePasswordHash($hash);

    foreach ($this->getPasswordVersion() as $hashVersion) {
        $password = $this->hash($this->getPasswordSalt() . $password, $hashVersion);
    }

    return Security::compareStrings(
        $password,
        $this->getPasswordHash()
    );
}
`

New Version
`
public function isValidHash($password, $hash)
{
    $this->explodePasswordHash($hash);

    foreach ($this->getPasswordVersion() as $hashVersion) {
        $password = $this->hash($this->getPasswordSalt() . $password, $hashVersion);
    }

    $hash = $this->getPasswordHash();
    return Security::compareStrings($password, $hash);
}
`

**Comment by ajijshekh123** [comment]
Good work @salehawal.

**Comment by pixmin** [comment]
@ajijshekh123 
@salehawal  Care to explain why this change solves the problem / what was happening?

> Old Version
```php
return Security::compareStrings(
     $password,
     $this->getPasswordHash()
);
```

> New Version
```php
$hash = $this->getPasswordHash();
return Security::compareStrings($password, $hash);
```

**Comment by salehawal** [comment]
not the first time, i had this issue with other project unrelated to magento, you may include a php expert to explain in depth, i just know that this is the way to fix it (:

**Comment by salehawal** [comment]
i have create a post about it since i just faced the same issue again : magento 2 | customer can't login or logins with wrong password https://blog.darelm.cc/2020/07/magento-2-customer-cant-login-or-logins.html #php #magento #zend #issue #login
