### ISSUE TITLE
Deleting disabled category forces category flat and catalog search re-indexed fully

### ISSUE THREAD

**Issue by gulshan-streammarket** [magento/magento2#23297]
### Description (*)
 When deleting a disabled category having no child and not product assigned to it then the status of Category Flat Data and Catalog search updated to Re-index Required 

### Steps to reproduce (*)

1. Create a disabled category
2. Run`indexer:reindex` to make sure that all indexer valid
3. Set all indexer to `Update by schedule` mode
4. Delete category (from step 1)
5. Observe indexers status

### Expected behavior (*)
 If a category is inactive then there should be no effect expected on catalog search and category flat index tables 

### Actual result (*)
Indexers have `invalid` status

### Benefits
 If this event happens Magento cron will try to full re-index and as indexing is time and resource consuming process then it may add some extra load unnecessarily. So we can avoid such things and save resource consumption if this event happens.

### Additional information
Magento version: 2.4-develop
Indexer Mode: Update By Schedule

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17560`, `MC-17561` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gulshan-streammarket** [comment]
@engcom-Charlie Thanks for confirming the issue.

**Comment by konarshankar07** [comment]
Hello @gulshan-streammarket ,

I fix the issue with deleting disabled category leads to Category Flat Data and Catalog search Re-index required. Do we need to do the same when new category creation?

Thanks

**Comment by gulshan-streammarket** [comment]
@konarshankar07 That would be great.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23756` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
