### ISSUE TITLE
Not possible to import product cost

### ISSUE THREAD

**Issue by jammy-git** [magento/magento2#23305]
### Preconditions (*)
Using Magento 2.7.x or 2.8.x

### Steps to reproduce (*)
1. Log in to admin panel
2. Go to System > Import.
3. Using either the Products or Advanced Pricing imports, it is not possible to add a `cost` or `price_cost` column to import the product cost (found in the Advanced Pricing section when adding/editing a product).

### Expected result (*)
1. To be able to bulk import cost prices against products

### Actual result (*)
1. No error message, the import routine just seems to ignore the field and data. Product cost is not changed/updated.

**Comment by engcom-Bravo** [comment]
Hello @jammy-git. Thanks for reporting. Please look at the following image.
![AP](https://user-images.githubusercontent.com/51680745/59756288-16635580-9292-11e9-8309-09048806e795.png)
The Products Import is responsible for the importing data of the first part of the image, while the Advanced Pricing Import is responsible for the importing data of the second part of the image. For importing the first part data please include fields like special_price, special_price_from_date, special_price_to_date and additional_attributes. The last one in Your case is for cost (e.g column name: additional_attributes, column value: cost=25.000000). Would You try please.

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-23305-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23305-2-3-develop.instances.magento-community.engineering/admin](https://i-23305-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jammy-git** [comment]
> The last one in Your case is for cost (e.g column name: additional_attributes, column value: cost=25.000000). Would You try please.

Thank you @engcom-Bravo, that is exactly what was needed and I can confirm that this works. Just for future reference, how would one know that the `cost` field should be under `additional_attributes` rather than as a separate column in the import file?

**Comment by engcom-Bravo** [comment]
@jammy-git, please take a note of this link on the Import page:
![import](https://user-images.githubusercontent.com/51680745/60108681-b37e2c80-9771-11e9-89e5-6cf7fcf6d5ff.png)
Here You can download a sample file with all the fields that are available for import with the current import Entity Type.
Also [here](https://docs.magento.com/m2/ce/user_guide/system/data-attributes-product.html) You can find more information on that. We admit intuitively it's confusing that some of  Advanced Pricing section fields are exported/imported via Entity Type of Products when there is an eponymous Entity Type. And we will consider that in our next releases. Thank You for bringing the issue up.
