### ISSUE TITLE
Order State dropdown shows new assigned status label not default state label in Assign Order Status

### ISSUE THREAD

**Issue by BharathN96** [magento/magento2#23318]
### Preconditions (*)

1. Magento 2.3.0  
2. PHP 7.2

### Steps to reproduce (*)

1. Admin: Stores -> Settings -> Order Status
2. Create a new order status(ex: Payment Refund).
3. Assign new order status to a state(canceled).
4. Create a new status(ex: Payment Failed) try to assign this to state canceled
5. In Order state Dropdown in assign state it shows Payment Refund which is not a order state

### Expected result (*)

1. It should display State Label instend of Status label

### Actual result (*)

1. It shows Order status label, not order state label
![Screenshot from 2019-06-19 11-34-04-edited](https://user-images.githubusercontent.com/31137693/59741535-dd72b300-9288-11e9-9fb4-82115a89c624.jpeg)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23318-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23318-2-3-develop.instances.magento-community.engineering/admin](https://i-23318-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have also verified this issue in Magento 2.3 instance and I don't have found the issue. In the drop-down, It is displaying State instead of Status.
See attached the screenshot:

**Magento 2.3 Instance:**
![2019-06-19 (3)](https://user-images.githubusercontent.com/24711761/59743089-e06fa280-928c-11e9-9916-0e06611376c4.png)

![2019-06-19 (2)](https://user-images.githubusercontent.com/24711761/59742949-79ea8480-928c-11e9-849b-8975315714b5.png)


This issue is related to #17844.

**Comment by engcom-Bravo** [comment]
@ajijshekh123, could You tell me please what was this?
![WTF](https://user-images.githubusercontent.com/51680745/59743879-f58f0600-9279-11e9-8984-50d4bd5bcfb3.png)

**Comment by ajijshekh123** [comment]
@BharathN96 - I have verified this issue in Magento 2.3 instance as per your steps and it's working fine in Fresh Magento 2.3 instance. I have also check this issue in the previous added list so this issue is related to #17844.

@BharathN96 - Let me know if you have any doubt.

**Comment by jayachandraoggy** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jayachandraoggy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayachandraoggy, here is your [Magento instance](https://i-23318-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23318-2-3-develop.instances.magento-community.engineering/admin](https://i-23318-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @BharathN96. Thank You for reporting. We managed to reproduce on Your issue on two or three weeks old 2.3-develop version. But on the latest version it is reproduced no more. So it has been fixed.
