### ISSUE TITLE
The \Magento\Config\Model\Config\Structure\Element\Field::getComment() method does not report about an invalid backend config field's comment XML declaration but just silently drop the invalid comment without any message

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2331]
https://mage2.pro/t/180

**Comment by vzabaznov** [comment]
To allow us research the issue, please, provide description according to the template.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
