### ISSUE TITLE
Invalid Base URL. Value must be a URL or one of placeholders: {{base_url}}

### ISSUE THREAD

**Issue by twocs** [magento/magento2#23316]
### Preconditions (*)

1. Version 2.3.1

### Steps to reproduce (*)

1. Try to enter a new base_url like "http://bmt.consulting".

### Expected result (*)

1. Change the base url.

### Actual result (*)
Result: `Invalid Base URL. Value must be a URL or one of placeholders: {{base_url}}`
![magento_error_baseurl](https://user-images.githubusercontent.com/72763/59736033-36494800-9297-11e9-82f9-c7e6fc89f9e0.png)

1. I modified the value of base_url in mysql so now it works. However, it seemed like I was still unable to modify anything on the stores web administration page. I incorrectly assumed that it was because of a new style of .consulting website address, but finally I realised that I could add a slash to the end of the url and it could be accepted. The message `Invalid Base URL` could more clearly why the validation failed. Here, this error occurred simply because I did not have a trailing slash on my base URL.

This issue took a bit of time to resolve. It seems that it was just a missing trailing slash in my base_url. The server seemed to work fine when I had set it via mysql without a trailing slash. 

My suggestion is to make the error message more clear or to automatically put a trailing slash on website addresses rather than have them fail. The tests at lib/internal/Magento/Framework/Validator/Test/Unit/UrlTest.php don't fail so I don't know why my address without trailing slash gets picked up.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23316-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23316-2-3-develop.instances.magento-community.engineering/admin](https://i-23316-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23316-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23316-2-2-develop.instances.magento-community.engineering/admin](https://i-23316-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have verified both issues in Magento 2.2 and 2.3 Instance. Without entering slash end of the URL, I have saved the configuration it is displaying the error and user can't understand why this URL is not accepted. 
Please apply the proper validation message Or display the proper error message so the user can easily understand what is the issue about this added URL.

See attached screenshot:
**Magento 2.2 Instance:**
![2 2 BaseURL_Issue](https://user-images.githubusercontent.com/24711761/59738293-5d475000-927e-11e9-9371-cd4f22413c91.png)

**Magento 2.3 Instance:**
![2 3_BaseURL_Issue](https://user-images.githubusercontent.com/24711761/59738294-5d475000-927e-11e9-80bf-74b2efa9569b.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17599`, `MC-17600` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
