### ISSUE TITLE
Magento 2.1.11 impossible finish reindex

### ISSUE THREAD

**Issue by Sylvesterx1** [magento/magento2#23320]
### Preconditions (*)

1. 2.1.11
2. CentOs 7

### Steps to reproduce (*)

1. php bin/magento indexer:reindex
2.

### Expected result (*)

1.
![image](https://user-images.githubusercontent.com/35328055/59759634-d94a9380-9290-11e9-947d-4889ff3872c4.png)

### Actual result (*)

1. In our magento version 2.1.11 impossible run reindex. We have total  60425 records. In our second website store on magento 2.2.5 we have same number of products and reindex it only lasts a 1-2 minutes.  I've been trying to solve this problem for several weeks.  The manual reindex stops at: Category products and impossible finish. We wait over 15 hours and nothing. In log file I do not see any bugs. I tried to change to different magento modes, I also tried to change to conversation mode. Nothing helps.

**Comment by engcom-Charlie** [comment]
Hello @Sylvesterx1 ! Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) ,  for advice or general discussion about this issue.
