### ISSUE TITLE
getting error Required parameter 'theme_dir' was not passed when try to sent custom email via cron in magento 2

### ISSUE THREAD

**Issue by Ridik123** [magento/magento2#23321]
I want to send a custom email via cron but it is throwing me an error that theme_dir was not passed
![Screenshot from 2019-06-19 16-59-40](https://user-images.githubusercontent.com/48005891/59761959-b2518900-92b3-11e9-9d86-d34618cd8abe.png)
My Magento version is 2.2.7

The cron runs fine but if I add the custom mail code the error arrives

**Comment by engcom-Charlie** [comment]
Hello @Ridik123 ! 
Thank you for your report , please provide steps to reproduce this issue

**Comment by Ridik123** [comment]
I'm trying to send email with cronjob to list from adminhtml area, throws error:

Required parameter 'theme_dir' was not passed

email sending works with magento cron:run command.

**Comment by engcom-Charlie** [comment]
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) Or slack channel,  for advice or general discussion about this issue.
