### ISSUE TITLE
Magento 2.3.1: Get rewrite with redirect_type 301 instead of rewrite with redirect_type 0 for entity_type category

### ISSUE THREAD

**Issue by Filipe-Bicho** [magento/magento2#23330]
### Preconditions

1. Magento 2.3
2. PHP 7.2
3. MySQL 5.6.42-84.2

### Steps to reproduce 

1. Create and save a category with url_key = 'test-url' and option 'Create Permanent Redirect for old URL' selected
2. Change url_key to 'test-url2' with option 'Create Permanent Redirect for old URL' selected.
3. Change the category path of a random product to the new category path.
4. Go to the product detail page of the selected product and inspect the breadcrumb link of the new category.

### Expected result 

1. The breadcrumb of the new category has the request_path of the rewrite with redirect_type = 0
### Actual result 

1.  The breadcrumb of the new category has the request_path of the rewrite with redirect_type = 301

### Possible fix

In src/www/vendor/magento/module-catalog/Model/Category.php::getUrl()

Change:

```
$rewrite = $this->urlFinder->findOneByData([
     UrlRewrite::ENTITY_ID => $this->getId(),
     UrlRewrite::ENTITY_TYPE => CategoryUrlRewriteGenerator::ENTITY_TYPE,
     UrlRewrite::STORE_ID => $this->getStoreId(),
 ]);
```

to:

```
$rewrite = $this->urlFinder->findOneByData([
     UrlRewrite::ENTITY_ID => $this->getId(),
     **UrlRewrite::REDIRECT_TYPE => 0,**
     UrlRewrite::ENTITY_TYPE => CategoryUrlRewriteGenerator::ENTITY_TYPE,
     UrlRewrite::STORE_ID => $this->getStoreId(),
  ]);
```
This way we make sure that we get the request_path of the rewrite with redirect_type = 0.

**Comment by engcom-Bravo** [comment]
Hello @Filipe-Bicho. Could You please try to reproduce Your issue asking the bot for an instance of the latest 2.3-develop version as You are advised above.
![Advised](https://user-images.githubusercontent.com/51680745/59848724-89da9500-936e-11e9-9c92-c673943f03c3.png)
Thanks You.

**Comment by Filipe-Bicho** [comment]
> Hi @Filipe-Bicho. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @Filipe-Bicho do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [X ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @Filipe-Bicho. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Filipe-Bicho, here is your [Magento instance](https://i-23330-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23330-2-3-develop.instances.magento-community.engineering/admin](https://i-23330-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
@Filipe-Bicho, and could You please provide us some screenshots on the Actual Result?

**Comment by engcom-Bravo** [comment]
@Filipe-Bicho, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
