### ISSUE TITLE
Magento 2 FA - restrict requirement to specific users or outside IPs?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#23337]
### Description (*)
Enabling Magento 2 FA (Google) in Admin requires all users to use 2FA. I want to be more specific.

### Expected behavior (*)
It would be useful in the admin to only require 2 FA for:
1) Specific users (e.g. administrators) and/or
2) Specific IPs not in the exclusion list (e.g. IP outside your office)

### Benefits
Some call centre staff are not allowed to use personal phones, or have business phones so 2FA is not applicable to them.

**Comment by engcom-Charlie** [comment]
Hello @craigcarnell ! Thank your for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
