### ISSUE TITLE
Setup version for module '' is not specified

### ISSUE THREAD

**Issue by calawers** [magento/magento2#2333]
Hello I've installed the Version 2.0.0-rc, in each module that I try to create or install from a third party, as soon as I add in config.php the module name in order to enable it, Magento reporst me that error:

Setup version for module '' is not specified

Any idea? I tried to find the solution but I couldn't.

Regards,

**Comment by dfediuk** [comment]
Magento 2 API is fastly changed without a backward compatibility so 95% of Magento 2 extensions developed more than 2-3 months ago are not working anymore if the developer is not updating them constantly (I do it for my [extensions](https://mage2.pro/c/extensions)).

**Comment by mazhalai** [comment]
@calawers modules now require a `registration.php`  Please see [devdocs.magento.com](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/component-registration.html) for more details

**Comment by calawers** [comment]
Thank you so much!!! You've helped me a lot.

**Comment by lunch22result** [comment]
I followed this tutorial to fix that issue [https://magentoexplorer.com/magento-2-setup-version-for-module-is-not-specified-how-to-fix](url)
