### ISSUE TITLE
Magento 2 & DB SSL

### ISSUE THREAD

**Issue by robert-schmidt** [magento/magento2#23336]
### Preconditions (*)

1. Magento 2.3.1, PHP 7.2, Azure MariaDB 10.X

### Steps to reproduce (*)

1. Set up SSL required options in env.php (driver_options)
2. Run CLI setup:upgrade

### Expected result (*)

1. DB should be upgraded accordingly

### Actual result (*)

1. SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry.

I managed to trace the issue to Magento\Setup\Validator\DbValidator::checkDatabaseConnection(). This method checks the DB connection without using the SSL options.

**Comment by robert-schmidt** [comment]
> Hi @robert-schmidt. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @robert-schmidt do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

I confirm.

**Comment by magento-engcom-team** [comment]
Hi @robert-schmidt. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @robert-schmidt, here is your [Magento instance](https://i-23336-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23336-2-3-develop.instances.magento-community.engineering/admin](https://i-23336-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by robert-schmidt** [comment]
This is a bug in the code. Don't know what am I supposed to do with a running instance :)

**Comment by engcom-Delta** [comment]
Hi @robert-schmidt thank you for your report. I'm not able to reproduce issue by steps you described on clean 2.3-develop.
My database config in env.php:
`
'db' => [
        'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => '127.0.0.1',
                'dbname' => 'magento',
                'username' => 'sslclient',
                'password' => 'sslclient',
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8;',
                'active' => '1',
                'driver_options' => [
                    1007 => 'client-ssl/client-key.pem',
                    1008 => 'client-ssl/client-cert.pem',
                    1009 => 'client-ssl/ca.pem',
                    1014 => false
                ]
            ]
        ]
`
As advice, you could verify permissions and ownership of your *.pem files and check if you could connect to database via command line: `mysql -usslclient -psslclient -h 127.0.0.1 --ssl-ca=client-ssl/ca.pem --ssl-cert=client-ssl/client-cert.pem --ssl-key=client-ssl/client-key.pem`
If you'd like to update the issue, please reopen it.

**Comment by robert-schmidt** [comment]
Thanks @engcom-Delta.

Did you also try to run setup:upgrade after setting up magento to use an SSL MySQL connection? 

Did you inspect the Magento\Setup\Validator\DbValidator::checkDatabaseConnection() method and see that it "doesn't know" about any driver_options instruction?

Thanks.

**Comment by robert-schmidt** [comment]
Just to bring this up again, maybe someone else is trying desperately to set up a non-working functionality.

Here's a reply we got from addressing this SSL related issue to your support team (on our Commerce subscription + gold support):

> Hello,
> 
> Thank you for contacting the Magento Commerce Support team.
> 
> My developer advised that MySQL connection through SSL is not implemented in Magento currently.
> 
> There is an enhancement request open to improve this behavior but I'm unable to provide an ETA.
> 
> Please turn off SSL until the feature gets implemented.

**Comment by robert-schmidt** [comment]
@engcom-Delta please reopen this. Thanks.

**Comment by xpoback** [comment]
@robert-schmidt They say they fixed it in 2.3.4
https://github.com/magento/magento2/pull/25398

Haven't tried it yet tough
