### ISSUE TITLE
Sort Orders not applied to Magento\Catalog\Model\CategoryList::getList result

### ISSUE THREAD

**Issue by pocketprogrammer** [magento/magento2#23342]
### Summary
`\Magento\Catalog\Model\CategoryList::getList` method does not respect searchCriteria sort orders.
This is due to calling `\Magento\Eav\Model\Entity\Collection\AbstractCollection::getAllIds` which calls `\Magento\Eav\Model\Entity\Collection\AbstractCollection::_getAllIdsSelect`.
`_getAllIdsSelect` resets the sort order and it is never again applied to the collection or search result.

### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1. Create an instance of `\Magento\Framework\Api\SearchCriteria` with sort orders applied
2. Pass the instance as an argument to the `\Magento\Catalog\Model\CategoryList::getList` method.
3. Inspect the search results to see the items have not been sorted.

```php
public function getSortedCategories()
{
    $sortOrder = $this->sortOrderBuilder->setField('name')->setDirection('ASC')->create();
    $searchCriteria = $this->searchCriteriaBuilder
        ->setSortOrders([$sortOrder])
        ->create();
    
    /** On inspection we can see the sortOrder is applied to searchCriteria correctly */
        
    $categories = $this->categoryListInterface->getList($searchCriteria);
    
    /** Stepping through the getList method, we see the sortOrder is not respected
        once getAllIds is called and iterated through to get the category instances.
        The searchResult items property is filled with the unsorted result.
    */
    
    return $categories->getItems();
}
```

### Expected result (*)
1. Sort orders should be applied to the search result instance

### Actual result (*)
1. Sort orders are not applied, and the search result returns items by which order getAllIds was returned.

**Comment by milindsingh** [comment]
Hi @pocketprogrammer As I can see the select object cloned with the original. I don't think it should cause any issue with the original.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17673`, `MC-17674` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rleshchenko** [comment]
#kharkiv2019

**Comment by magento-engcom-team** [comment]
@rleshchenko thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by madbounce** [comment]
Hey, checked current issue on branch 2.3-develop and it's not reproduced anymore.
