### ISSUE TITLE
Connection was reset

### ISSUE THREAD

**Issue by bbaulos** [magento/magento2#23348]

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23348-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23348-2-3-develop.instances.magento-community.engineering/admin](https://i-23348-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23348-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23348-2-2-develop.instances.magento-community.engineering/admin](https://i-23348-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@bbaulos - I have verified this issue in latest Chrome, Firefox and Opera browser with Magento 2.3 and Magneto 2.2 Instance. I am not finding any issue related to your attached screenshot.
@bbaulos - This issue is related to any code customization, third-party extensions, Caching or Browser issues which you are using it.

**Comment by bbaulos** [comment]
let me check on my end

**Comment by bbaulos** [comment]
Hello sir. 
I've tried accessing magento 2.2.5 using newly installed chrome with no third party extensions, cleared caches, stable connection but still the same issue persist. here's the link: https://www.screencast.com/t/6xYg6rLOy
Is it possible that my Internet's IP has been black listed by this site?

**Comment by ajijshekh123** [comment]
Hi @bbaulos,
It may be possible.
So can you please access a different site with Magento 2.2.5 Instance?
Can you please send your admin credential if feasible in your end?

**Comment by bbaulos** [comment]
let me ask my client about this. I'll get back to you on this one

**Comment by ajijshekh123** [comment]
@bbaulos - Have you resolve this issue? Update me. If this issue is not related to Magento instance I will close this issue.

**Comment by bbaulos** [comment]
hello sir. the issue is not anymore related to Magento instance please close and delete the screenshots you provided in this ticket. thank you so much

**Comment by ajijshekh123** [comment]
Okay @bbaulos
