### ISSUE TITLE
Parameters for "method":"ewayrapid" - in payment-information API call

### ISSUE THREAD

**Issue by VjIntesols** [magento/magento2#23349]
After referring to the document (Ref: https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-order.html#send-payment)

I understood we need to pass the payment method while creating the order.

So, when I pass the parameters as:
{
  "billing_address": {
    "region": "Victoria",
    "region_id": 539,
    "region_code": "VIC",
    "country_id": "AU",
    "street": [
      "Dandenong"
    ],
    "postcode": "1086",
    "city": "Melborne",
    "firstname": "Moin",
    "lastname": "Shk",
    "email": "aboutusintes@gmail.com",
    "telephone": "9913611234"
  },
  "paymentMethod": {
    "method": "ewayrapid"
  }
}

The payment-information API response me with the response:
{"message":"An error occurred on the server. Please try to place the order again."}

I am willing to do the payment via eWay and I have successfully received the accessToken from eWay after doing the transaction.

What parameters need to be sent, while the paymentMethod is "ewayrapid", Is there any sample provided in document for all payment methods available for Magento store?

**Comment by krishprakash** [comment]
Hi @VjIntesols.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.
Thank You.
