### ISSUE TITLE
Unable to save price for configurable product.

### ISSUE THREAD

**Issue by cigogma** [magento/magento2#23344]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Import some products.
2. Price is set and is in the product list
3. When you open a configurable product.

### Expected result (*)

1. Price should be there inherit form the childs.

### Actual result (*)

1. Price dissapears and is also is erased form the product list when saved.
![image](https://user-images.githubusercontent.com/19759658/59856806-4be66c80-9380-11e9-9a08-6f350d99cdaf.png)
2. Price cannot be edited since is a configurable product.
![image](https://user-images.githubusercontent.com/19759658/59856896-70424900-9380-11e9-93cf-9abf578a10f9.png)

**Comment by engcom-Bravo** [comment]
Hello @razvang10. Thanks for applying. The behavior You described is correct. In reality Configurable product itself does not exist. There exist its variations (as You call them "childs"). For example You can create a Configurable Product called "Pencil" which has two variations "Red-Pencil" (price=1$) and "Blue-Pencil" (price=2$). Pencil itself will not exist It'll be only Red-Pencil and Blue-Pencil that really exist and are the real products a buyer can buy. Even if You want to put a price for the Pencil (not for the one of the Simple products Red-Pencil or Blue-Pencil but for the Configurable product Pencil) what You will expect it to be 1$ or 2$ or something else?

**Comment by engcom-Bravo** [comment]
@razvang10, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
