### ISSUE TITLE
Unable to serialize Magento Items (Product)

### ISSUE THREAD

**Issue by pietrogalassi** [magento/magento2#23341]
### Summary 
I'm trying to serialize a magenti item (Product) on disk in order to avoid the retrieve from database (simple cache).

### Examples
$productRepository = $this->_object_Manager->get('\Magento\Catalog\Model\ProductRepository');
$product = $this->_cache->get("products", $sku);
$this->_cache->set("products", $sku, $product);

This is the called function:
function set( $catalog, $id, $obj) {
		$file = $this->path . '/' . $catalog .'.'. $id . '.cache';
		file_put_contents($file, serialize($obj));
	}
that serialize on disk.

### Error
Exeception: Exception: Serialization of 'Closure' is not allowed in /product/apache2/magento/custom/PhpCache.php:23
Stack trace:
#0 /product/apache2/magento/custom/PhpCache.php(23): serialize(Object(Magento\Catalog\Model\Product\Interceptor))

## Note
It was working with Magento 2.1.x.

### Proposed solution
How i can remediate ?

**Comment by engcom-Charlie** [comment]
Hi @pietrogalassi ! Thank you for your report . Seems like you are using custom code there .
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
