### ISSUE TITLE
There are no commands defined in the "cron" namespace.

### ISSUE THREAD

**Issue by woei66** [magento/magento2#2335]
based on the doc
http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html
I setup the cron and execute on cli
php /path/magento2/bin/magento cron:run
but I got an error message
 [InvalidArgumentException]
  There are no commands defined in the "cron" namespace.
![2015-11-12_175346](https://cloud.githubusercontent.com/assets/5770807/11115445/832ae982-8966-11e5-8dda-6610a84fdd89.png)

**Comment by dfediuk** [comment]
[How to fix the «There are no commands defined» failure while executing a console command](https://mage2.pro/t/176)

**Comment by mazhalai** [comment]
@woei66 please use the `-v` or `-vv` option in the command line for more details to see what exactly is causing this error.

**Comment by nkarthickannan** [comment]
@woei66 

I was also facing the similar issue. Issuing sudo chmod -R 777 \* in my Ubuntu system solves this issue. It seems Magento is not able to create classes under var/generation directory. I am not sure what directory permission should be given to avoid this problem

**Comment by stepzerosolutions** [comment]
This could be due to composer.json file in your module or theme. I've got the same issue 

[InvalidArgumentException]
  There are no commands defined in the "setup" namespace.

remove the composer file and run the command and it will update the module.

**Comment by stepzerosolutions** [comment]
My exception trace is 


() at /home/www/secondnaturecharitabletrustwero/wero.dev/public/vendor/symfony/console/Symfony/Component/Console/Application.php:501
 Symfony\Component\Console\Application->findNamespace() at /home/www/secondnaturecharitabletrustwero/wero.dev/public/vendor/symfony/console/Symfony/Component/Console/Application.php:535
 Symfony\Component\Console\Application->find() at /home/www/secondnaturecharitabletrustwero/wero.dev/public/vendor/symfony/console/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /home/www/secondnaturecharitabletrustwero/wero.dev/public/lib/internal/Magento/Framework/Console/Cli.php:49
 Magento\Framework\Console\Cli->doRun() at /home/www/secondnaturecharitabletrustwero/wero.dev/public/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/www/secondnaturecharitabletrustwero/wero.dev/public/bin/magento:25

**Comment by ghost** [comment]
@woei66 Your issue is likely with permissions and ownership. See [this page](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html) for more info.

**Comment by woei66** [comment]
@stepzerosolutions 
remove the composer file doesn't fix the probelm

@mazhalai  here is the -vv output
Exception trace:
 () at /xxx/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php:501
 Symfony\Component\Console\Application->findNamespace() at /xxx/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php:535
 Symfony\Component\Console\Application->find() at /xxx/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /xxx/magento2/lib/internal/Magento/Framework/Console/Cli.php:49
 Magento\Framework\Console\Cli->doRun() at /xxx/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /xxx/magento2/bin/magento:25

@karthickannan 
You are right. The problem is the permission.
I try to execute the command with root permission and traced which directories and files are generated/modified.
Here are the output
./var/cache/mage--b/mage---064_CRONTAB__EVENT_CONFIG_CACHE
./var/cache/mage--b/mage---064_CRONTAB_CONFIG_CACHE
./var/cache/mage--7/mage---064_DB_PDO_MYSQL_DDL_CRON_SCHEDULE_1
./var/cache/mage--e/mage---064_CRON_LAST_SCHEDULE_GENERATE_ATDEFAULT
./var/cache/mage--9/mage---064_RESOLVED_STORES_D7A094A061F9E5121D10DBCA79ABB6E0
./var/cache/mage--3/mage---064_CRON_LAST_HISTORY_CLEANUP_ATINDEX
./var/cache/mage--0/mage---064_CRON_LAST_HISTORY_CLEANUP_ATDEFAULT
./var/cache/mage--0/mage---064_CRONTAB__RESOURCESCACHE
./var/cache/mage--c/mage---064_GLOBAL_CRONTAB_PLUGIN_LIST
./var/cache/mage--1/mage---064_CRON_LAST_SCHEDULE_GENERATE_ATINDEX

So, to fix the problem is simple, just make sure the cron account has the permission to write data to var/cache permission.

I think:
1. the error message is not clear and user can't figure out the problem easily
2. the -vv doesn't display enough information since it's a permission, I didn't see the permission warning on this.

**Comment by woei66** [comment]
the next question is: where is the check point for the permission checking?
at the check point, it should throw a exception that the cron owner has no enough permission to write the directory.

**Comment by woei66** [comment]
What I did:
1. using root to execute "php bin/magento cron:run"
2. using "find ./ -mmin -60" to know which files or directories are modified
3. It displayed that some files are generated at the "var/cache/" directory
4. I knew that the account which execute the  "php bin/magento cron:run" without enough permission to write data to the "var/cache/" directory
5. I need to add permission to the account and it can write the "var/cache/" directory

**Comment by nkarthickannan** [comment]
@woei66 

Hi,

Please check if this document helps to resolve this problem http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache-user.html

I'll check this procedure and update here if it solves this problem.

Thanks

**Comment by nkarthickannan** [comment]
@woei66 

In my opinion, running the CLI commands as root user will create more problems. Because the Cache files will be generated as root user. Hence you may face problems while removing the cache files. So, never run the CLI commands as root user. Instead use the sudo (if it is Ubuntu) for authorization.

Thanks

**Comment by nkarthickannan** [comment]
@woei66 

The following commands helped for me to install Magento 2 with sample data

**Magento 2 installation with sample data**
1)  cd /var/www
2)  composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition mage2
3)  ps aux | grep apache
4)  groups www-data
5)  groups <my_user_name> (<my_user_name> is already in the primary group of www-data)
6)  sudo service apache2 restart
7)  cd mage2
8)  sudo chown -R :www-data .
9)  sudo find . -type d -exec chmod 770 {} \; && sudo find . -type f -exec chmod 660 {} \; && sudo chmod u+x bin/magento
10) bin/magento sampledata:deploy
11) composer update
12) bin/magento setup:upgrade
13) sudo chown -R :www-data .

I'm using LAMP stack in Ubuntu 14.04. Please check these and let me know the result.

Thanks

**Comment by katmoon** [comment]
Internal ticket `MAGETWO-49955` is created for this issue.
Thanks everyone for your input.

**Comment by mazhalai** [comment]
@woei66 this issue has been fixed in the develop branch. Please open a new issue, if you have any other problems.

**Comment by ghost** [comment]
I know this is a different command but...
For me I had to manually rm -Rf var/di/*
sudo php bin/magento setup:upgrade
sudo php bin/magento setup:di:compile

now I dont get
[InvalidArgumentException]
There are no commands defined in the "deploy:mode" namespace.

I get this

sudo php bin/magento deploy:mode:set developer
Enabled developer mode.

:)

hope that helps...

**Comment by stevensagaar** [comment]
For me it has always to do with etc\module.xml, best to check etc\module.xml file either it could be missing or format of the file might be incorrect.

**Comment by WebDweller** [comment]
I had this same issue and it got resolved after updating directory & files permissions and adding my magento user to www-data group.

```
sudo chmod -R 755 /var/www/html/Magento2/
sudo chmod -R 777 /var/www/html/Magento2/var/
sudo chmod -R 777 /var/www/html/Magento2/pub/
sudo chmod -R 777 /var/www/html/Magento2/app/etc
sudo chmod -R 777 /var/www/html/Magento2/generated
```

`sudo adduser ubuntu www-data`
