### ISSUE TITLE
Product price on cart is not displayed proper with tax when custom price is applied.

### ISSUE THREAD

**Issue by sanjay-github** [magento/magento2#23355]
### Preconditions (*)

1. Magento 2.3.0- Community edition

### Steps to reproduce (*)

1. Please configure tax settings and tax rules as seen in screenshots.
2. Now login in storefront using Demo Customer Access provided by Magento (roni_cost@example.com).
3. Please integrate the below code to apply custom price.

**Observer** : 

namespace Vendor\MyModule\Observer;

use Magento\Framework\Event\ObserverInterface;

class BindPriceToCart implements ObserverInterface
{

    public function execute(\Magento\Framework\Event\Observer $observer)
    {   
            $price = 100;
            $event = $observer->getEvent();
            $item = $event->getQuoteItem();
            $item->setCustomPrice($price);
            $item->setOriginalCustomPrice($price);
            return $this;
    }    
}

**Events** : 
checkout_cart_product_add_after

**Configuration that needs to be set is as below**:
![Screenshot from 2019-06-21 16:40:58](https://user-images.githubusercontent.com/7973021/60005754-c408a700-968c-11e9-8977-0ec23ac0ce2d.png)
![Screenshot from 2019-06-21 16:41:06](https://user-images.githubusercontent.com/7973021/60005755-c408a700-968c-11e9-995f-4532cefc5a0f.png)
![Screenshot from 2019-06-21 16:41:12](https://user-images.githubusercontent.com/7973021/60005756-c4a13d80-968c-11e9-8f0a-313e13ab79b3.png)
![Screenshot from 2019-06-21 16:41:48](https://user-images.githubusercontent.com/7973021/60005757-c4a13d80-968c-11e9-9c1e-670c9b500a13.png)

### Expected result (*)

1.
![Screenshot from 2019-06-21 16_50_34 (copy)](https://user-images.githubusercontent.com/7973021/60009681-ec47d400-9693-11e9-9c0f-ca0f2159389a.jpg)

### Actual result (*)

1. 
![Screenshot from 2019-06-21 16:50:34](https://user-images.githubusercontent.com/7973021/60005787-cf5bd280-968c-11e9-8146-8a96f493ad0e.png)

**Comment by sanjay-github** [comment]
Sorry , for some reason was not able to add code.
I am still not able to format code and add screenshots.
Observer : 
<?php
namespace Vendor\MyModule\Observer;

use Magento\Framework\Event\ObserverInterface;

class BindPriceToCart implements ObserverInterface
{

    public function execute(\Magento\Framework\Event\Observer $observer)
    {   
            $price = 50;
            $event = $observer->getEvent();
            $item = $event->getQuoteItem();
            $item->setCustomPrice($price);
            $item->setOriginalCustomPrice($price);
            return $this;
    }    
}

Events : 

<event name="checkout_cart_product_add_after"> 
        <observer name="add_new_custom_price" instance="Vendor\MyModule\Observer\BindPriceToCart" shared="true" /> 
    </event>

**Comment by sanjay-github** [comment]
Observer : 

namespace Vendor\MyModule\Observer;

use Magento\Framework\Event\ObserverInterface;

class BindPriceToCart implements ObserverInterface
{

    public function execute(\Magento\Framework\Event\Observer $observer)
    {   
            $price = 50;
            $event = $observer->getEvent();
            $item = $event->getQuoteItem();
            $item->setCustomPrice($price);
            $item->setOriginalCustomPrice($price);
            return $this;
    }    
}

Events : 

<event name="checkout_cart_product_add_after"> 
        <observer name="add_new_custom_price" instance="Vendor\MyModule\Observer\BindPriceToCart" shared="true" /> 
    </event>

**Comment by sanjay-github** [comment]
Observer : 

namespace Vendor\MyModule\Observer;

use Magento\Framework\Event\ObserverInterface;

class BindPriceToCart implements ObserverInterface
{

    public function execute(\Magento\Framework\Event\Observer $observer)
    {   
            $price = 50;
            $event = $observer->getEvent();
            $item = $event->getQuoteItem();
            $item->setCustomPrice($price);
            $item->setOriginalCustomPrice($price);
            return $this;
    }    
}

Events : 

<event name="checkout_cart_product_add_after"> 
        <observer name="add_new_custom_price" instance="Vendor\MyModule\Observer\BindPriceToCart" shared="true" /> 
    </event>

**Comment by sanjay-github** [comment]
Sorry, for some reason I was not able to upload the code.
Still could not upload the screenshots.

Observer : 

namespace Vendor\MyModule\Observer;

use Magento\Framework\Event\ObserverInterface;

class BindPriceToCart implements ObserverInterface
{

    public function execute(\Magento\Framework\Event\Observer $observer)
    {   
            $price = 50;
            $event = $observer->getEvent();
            $item = $event->getQuoteItem();
            $item->setCustomPrice($price);
            $item->setOriginalCustomPrice($price);
            return $this;
    }    
}

Events :  checkout_cart_product_add_after

**Comment by krishprakash** [comment]
Hi @sanjay-github.
Can you please upload the screenshot so it will help to reproduce this issue.
Thanks.

**Comment by sanjay-github** [comment]
/home/sanjay/Pictures/Screenshot from 2019-06-21 16:40:58.png

**Comment by sanjay-github** [comment]
Hi @krishprakash, I will soon upload images. For some reason I am not able to upload images, may be I need to update my browser.

**Comment by sanjay-github** [comment]
Hi @krishprakash :
I have attached all the necessary screenshots.

**Comment by engcom-Charlie** [comment]
Hello @sanjay-github ! Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
