### ISSUE TITLE
Chinese product description utf error

### ISSUE THREAD

**Issue by xiaolinwuu** [magento/magento2#23356]
### Preconditions (*)

1. Magento 2.3.1 version

### Steps to reproduce (*)

1. Add product and write a description in Chinese characters (66+ characters) less than 66, it works
2. Go to product page in the Chinese locale store view

### Expected result (*)

1. Product page and Description should be displayed

### Actual result (*)

1.```
 1 exception(s):
Exception #0 (InvalidArgumentException): Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded

Exception #0 (InvalidArgumentException): Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded
<pre>#1 Magento\Framework\App\PageCache\Kernel->process(&Magento\Framework\App\Response\Http\Interceptor#00000000232e592500000000223bceff#) called at [vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php:96]
#2 Magento\PageCache\Model\Controller\Result\BuiltinPlugin->afterRenderResult(&Magento\Framework\View\Result\Page\Interceptor#00000000232e41d800000000223bceff#, &Magento\Framework\View\Result\Page\Interceptor#00000000232e41d800000000223bceff#, &Magento\Framework\App\Response\Http\Interceptor#00000000232e592500000000223bceff#) called at [vendor/magento/framework/Interception/Interceptor.php:146]
#3 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Response\Http\Interceptor#00000000232e592500000000223bceff#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#4 Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#00000000232e592500000000223bceff#), array(array('result-messages', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:130]
#5 Magento\Framework\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#00000000232e592500000000223bceff#) called at [vendor/magento/framework/App/Http.php:140]
#6 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#7 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#8 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#00000000232e594600000000223bceff#) called at [index.php:39]
</pre>

```

**Comment by xiaolinwuu** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @xiaolinwuu. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @xiaolinwuu, here is your [Magento instance](https://i-23356-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23356-2-3-develop.instances.magento-community.engineering/admin](https://i-23356-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
@xiaolinwuu can you send an example of description you used ?

**Comment by engcom-Charlie** [comment]
I can`t reproduce your issue due the steps your provided. Please update description.

**Comment by xiaolinwuu** [comment]
this is the link https://www.italianleathermarket.com/cn/asdf.html
do you need to access to admin?

**Comment by engcom-Charlie** [comment]
@xiaolinwuu can you confirm that you can reproduce this issue on Vanilla Magneto ?

**Comment by engcom-Charlie** [comment]
Feel free to reopen if you can confirm that issue is reproducible on Vanilla Magento .

**Comment by jdereus87** [comment]
@magento give me 2.4-develop instance

**Comment by jdereus87** [comment]
@engcom-Charlie 
This issue still persists on 2.4.6-p6. Can confirm on a vanilla instance once its spinned up

**Comment by jdereus87** [comment]
https://github.com/magento give me 2.4.6-p6 instance

**Comment by jdereus87** [comment]
@magento give me 2.4.6-p6 instance

**Comment by jdereus87** [comment]
@magento give me 2.4-develop instance

**Comment by jdereus87** [comment]
Ok not a bug it seemed. If anyone else encounters this, we had malformed UTF8 characters in our system due to a developer using non-multibyte safe functions like substr(). Check your templates/code for multibyte unsafe characters
