### ISSUE TITLE
Controller 404 error for multishipping/checkout/checkItems

### ISSUE THREAD

**Issue by konarshankar07** [magento/magento2#23361]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1.Login from the frontend
2. Add a product in the cart and go to cart page
3. click on checkout with multiple addresses
4. Update the qty field and click update qty and addresses button

### Expected result (*)

1. No JS should display and validation should be executed

### Actual result (*)

1. JS error with the controller multishipping/checkout/checkItems 404 error
![image](https://user-images.githubusercontent.com/39480008/59931147-f97d7c80-9461-11e9-9bfe-d00bf96ee45b.png)

**Comment by konarshankar07** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07, here is your [Magento instance](https://i-23361-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23361-2-3-develop.instances.magento-community.engineering/admin](https://i-23361-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by konarshankar07** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07, here is your [Magento instance](https://i-23361-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23361-2-2-develop.instances.magento-community.engineering/admin](https://i-23361-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @konarshankar07. Thanks for reporting. We've been not able to reproduce Your issue on the latest 2.3-develop instance. Could You please confirm You remain able to do that?

**Comment by konarshankar07** [comment]
Hello @engcom-Bravo ,
I'm also not able to reproduce this issue in Magento instance So I'm closing this issue
