### ISSUE TITLE
Not getting any value while searching the products using REST API

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [magento/magento2#23370]
**Preconditions**
1. Magento CE 2.3
2. Rest API
3. Simple product 
    > "id":124,
    > "sku":"Birthday Cake",
    > "name":"Birthday Cakes",

I am searching product as per product ```sku and name``` using the end point API of magento2 but for some search text no value is coming. I am explaining my code below.

**Steps to reproduce**
When I am searching this product using the following code its returning null as output.

$stext='Cake';
$searchText='%'.$stext.'%';
$ch = curl_init('http://abcd.com/index.php/rest/V1/products?searchCriteria[filterGroups][0][filters][0][field]=name&searchCriteria[filterGroups][0][filters][0][value]='.$searchText.'&searchCriteria[filterGroups][0][filters][0][conditionType]=like&searchCriteria[filterGroups][0][filters][1][field]=sku&searchCriteria[filterGroups][0][filters][1][value]='.$searchText.'&searchCriteria[filterGroups][0][filters][1][conditionType]=like');
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Authorization: Bearer " . json_decode($token)));
$res = curl_exec($ch);
$resu = json_decode($res, 1);
echo json_encode($resu);```

Here I need to check the similar keyword. For this  $stext='Cake' the output is coming null but for $stext='Birthday'  the proper output is coming. Again when I am searching $stext='Birthday Cake'  no output is coming.

Here I need to do the text search as per name and sku.

**Expected result**
Rest API call returns product

**Actual result**
Rest API call returns null

**Comment by subhrajyotiw5rtc** [comment]
Hi @engcom-Charlie. Regarding this issue I can just search for other products name or sku but one part of one product which is present also throwing this king of issue.

**Comment by magento-engcom-team** [comment]
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17756`, `MC-17757` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by xmav** [comment]
@subhrajyotiw5rtc 
It seems that `%` should be encoded in query.
Could you try following update to your script?

```
$stext="Cake";
$searchText="%".$stext."%";
$searchCriteria = [
    "searchCriteria" => [
        "filterGroups" => [
            [
                "filters" => [
                    [
                        "field" => "name",
                        "value" => $searchText,
                        "conditionType" => "like"
                    ],
                    [
                        "field" => "sku",
                        "value" => $searchText,
                        "conditionType" => "like"
                    ]
                ],
            ]
        ],
    ]];
$query = http_build_query($searchCriteria);
$ch = curl_init("http://magento2ce.loc:8080/index.php/rest/V1/products?" . $query);
```
Please check https://devdocs.magento.com/guides/v2.3/rest/performing-searches.html#logical-or-search for more information

**Comment by engcom-Charlie** [comment]
Hello @subhrajyotiw5rtc ! I rechecked this issue and i found out that your API call isn`t correct. @xmav is right here , so please try to use API call which he provided or refer here(https://devdocs.magento.com/guides/v2.3/rest/performing-searches.html#logical-or-search) to find some more information about searching using REST endpoints.
