### ISSUE TITLE
Notice: Undefined index: mg_vss_mp_seller_reviews in /home/b0jqdi25k02i/public_html/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 152

### ISSUE THREAD

**Issue by aqidul** [magento/magento2#23379]

**Comment by aqidul** [comment]
Please solve this issue
my whatsapp number is +918604261683

**Comment by engcom-Charlie** [comment]
Hello @aqidul !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
