### ISSUE TITLE
magento2.0.15 product detail page 404 after delete all product & add

### ISSUE THREAD

**Issue by lykang** [magento/magento2#23373]
### Preconditions (*)

1. Magento 2.0.15 Community

### Steps to reproduce (*)

1. admin panel -> select all product & delete
2. admin panel -> add product

### Expected result (*)

1. product detail page -> 200

### Actual result (*)

1.  product list page is showed, but detail page not found 404

**Comment by engcom-Charlie** [comment]
Hello @lykang ! Thank you for your report !
This issue is not reproducible on Vanilla Magento 2.3.x
