### ISSUE TITLE
Incomplete core zipcode validation database

### ISSUE THREAD

**Issue by kapil-infobeans** [magento/magento2#23371]
### Preconditions (*)

1. Magento EE 2.2.5 with sample data is installed.
2.  Use core class "\Magento\Directory\Model\Country\Postcode\ValidatorInterface" for validation of postcode by countryId
3. Only 94 countries validation database exist in file "app/code/Magento/Directory/etc/zip_codes.xml" out of 246 countries from database table "directory_country"

### Steps to reproduce (*)
1.Incomplete core zip-code validation configuration file: 

`app/code/Magento/Directory/etc/zip_codes.xml`

2.  Code snippet used for testing it.

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
ini_set('memory_limit', '5G');
error_reporting(E_ALL);

use Magento\Framework\App\Bootstrap;
require 'app/bootstrap.php';

$bootstrap = Bootstrap::create(BP, $_SERVER);

$objectManager = $bootstrap->getObjectManager();

$state = $objectManager->get('Magento\Framework\App\State');
$state->setAreaCode('frontend');  


try {
  $postalCode = 'KY1-1202';
  $countryId = 'KY';
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $postCodeValidator = $objectManager->create(\Magento\Directory\Model\Country\Postcode\ValidatorInterface::class);
  $isValid = (bool) $postCodeValidator->validate($postalCode,$countryId);
} catch (\Exception $e) {
  echo $e->getMessage();	
}

?>
```

### Expected result (*)
1. It should either return true or false.

### Actual result (*)
1. **Exception**: Provided countryId does not exist.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18688` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kapil-infobeans** [comment]
Is anybody taking this for development? I do not have zipcode pattern database. If anyone has that, I can take this for development.

**Comment by gabrieldagama** [comment]
This issue is too abstract, it would be better to have an issue specific to a country instead of a general issue. Magento provides a way for developers to extend the functionality and add their country's postcodes as well.

Closing this issue since it is probably not achievable.
