### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by JoaoOlsenTecnico** [magento/magento2#23378]
### Preconditions (*)
Magento was installed by Bitnami, is version 2.3.0 and is allocated on an AWS server

### Steps to Reproduce (*)
Make the connection to the Email using the MagePal (Free Email module).

### Expected result (*)
By receiving the "welcome" e-mail and registration in the "newsletter", the name of the sender to come as configured in the "Store Emails"
![image](https://user-images.githubusercontent.com/32138879/60022011-66169800-9669-11e9-8f12-a10470e78d39.png)
![image](https://user-images.githubusercontent.com/32138879/60022037-6fa00000-9669-11e9-9163-ec14544c8c68.png)

### Current results (*)
The user receives the "welcome" email with the name of the sender being the beginning of the email, for example:
john@gmail.com, sender's name: "john".
support@gmail.com, sender name: "suport".
In transactional emails, such as sales, the name comes correct.
![image](https://user-images.githubusercontent.com/32138879/60021973-58611280-9669-11e9-912a-370af0ef4aa1.png)
![image](https://user-images.githubusercontent.com/32138879/60021996-5eef8a00-9669-11e9-9f76-b05e4a86b505.png)
![image](https://user-images.githubusercontent.com/32138879/60022060-775fa480-9669-11e9-822a-677e76061da5.png)

**Comment by engcom-Alfa** [comment]
Hi @JoaoOlsenTecnico !  thank you for you report, i'm closing this as duplicate to this -> #23380
