### ISSUE TITLE
magento2 rc install error

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#2338]
what's the problem?

[ERROR] exception 'LogicException' with message 'Unknown module in the requested list: 'Magento_DesignEditor'' in 
C:\xamp\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php:403 Stack trace: 
#0 C:\xamp\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(364): Magento\Setup\Model\Installer->readListOfModules(Array, Array, 'enable_modules') 
#1 C:\xamp\htdocs\magento2\setup\src\Magento\Setup\Model\Installer.php(323): Magento\Setup\Model\Installer->createModulesConfig(Array) 
#2 C:\xamp\htdocs\magento2\setup\src\Magento\Setup\Controller\Install.php(97): Magento\Setup\Model\Installer->install(Array) 
#3 C:\xamp\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() 
#4 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) 
#5 C:\xamp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) 
#6 C:\xamp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#7 C:\xamp\htdocs\magento2\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#8 C:\xamp\htdocs\magento2\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) 
#9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) 
#10 C:\xamp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) 
#11 C:\xamp\htdocs\magento2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#12 C:\xamp\htdocs\magento2\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#13 C:\xamp\htdocs\magento2\setup\index.php(31): Zend\Mvc\Application->run() #14 {main}

**Comment by mazhalai** [comment]
@ideirj `Magento_DesignEditor` module has been removed. You can try `bin/magento setup:uninstall` to clean your installation and install again, or manually clean up in `app/etc/config.php` as well as in the db.

**Comment by ideirj** [comment]
it's on the install procedure (about 1 hour ago i use gitclone https url)

so not exist app/etc/config.php

**Comment by mazhalai** [comment]
@ideirj  Was this installation via CLI or Web Setup? If it was web, please clear browser cache.
Did you have a previous instance? If you did have a previous instance, please make sure your database is clean.

**Comment by ideirj** [comment]
It was a clear install (clear db) with web setup, but the browser cache don't clean.

cleaned the cache the install is ok.

thank you

**Comment by redochka** [comment]
For me it the browser cache  but how is possible the browser cache can cause such error?!

**Comment by pabloberlin** [comment]
Yes, I had the same problem, and its solved cleaning browser cache ;)
