### ISSUE TITLE
form_key parameter gets added to all forms

### ISSUE THREAD

**Issue by kozie** [magento/magento2#23382]
### Preconditions (*)

1. Magento 2.3.X CE && EE

### Steps to reproduce (*)

1. Add a form to the site without form_key with method="post" and (for example) an external URL
2. Submit the form (while inspecting for example)
3. form_key gets added and it posted along the rest of the form data

### Expected result (*)

1. No form_key is added to forms i don't need or even want them to be

### Actual result (*)

1. form_key gets added anyway

As seen in [common.js](https://github.com/magento/magento2/blob/2.3.1/lib/web/mage/common.js) from [this commit](https://github.com/magento/magento2/commit/b475068f894b95674454cc08dc327a45d218a72f) the conditional that checks the target forms seems way too global.

**Comment by kozie** [comment]
yes

**Comment by engcom-Bravo** [comment]
Hello @kozie. The behavior You've reported about is quite expected. Form keys are added deliberately. Form key must be added to any form posted via Magento page as it is a matter of security. Form key validation helps to prevent Your store from hacking or other potential dangers comming from the web. So we are supposed to close Your issue. Feеl free to reopen it if deem necessary. Thanks for applying.

**Comment by hostep** [comment]
@engcom-Bravo: @kozie is talking about forms which post to an external non-Magento url. I think his issue makes sense, let's reopen this so you can try to reproduce if it's valid or not.

**Comment by kozie** [comment]
@hostep is right. Forms posting to external url's can also get the form_key. I don't think it's desirable at all to have this but in my case it was about a PSP form which errorred because of an unknown parameter being sent along (the form_key).

**Comment by sivaschenko** [comment]
I think https://github.com/magento/magento2/blob/2.3.1/lib/web/mage/common.js can verify if form action is external and skip adding form key in that case

**Comment by magento-engcom-team** [comment]
@sivaschenko Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18730` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
