### ISSUE TITLE
Re:  Magento 2.3.1 Site loading issue with Multiple stores

### ISSUE THREAD

**Issue by MeetKamal** [magento/magento2#23381]
Hello Dear,

We have migrated one Magento site with multiple stores  from 2.2.4 to 2.3.1 and then facing so many issues with site loading.  One thing we have 300+ Stores and sub domain configured at server end.

### Summary (*)
Our site works fine with Magento 2.2.4 but to upgrade security and improve Indexing mechanism we tried to go on Magento 2.3.1,  When we upgrade site on M 2.3.1 it becomes really slow.  

We have asked the Server team to cross check server traffic and apache log, but it is almost free. But our site never load properly.  We were faced issue with Indexing data on multi stores in Magento 2.2.4 as well, but we assume that will be fixed with newer version.

Does Re-indexing mechanism has been completely changed in M 2.3.1 and that's why we are getting this issue. 

### Examples (*)
For now we have revert back the version to M 2.2.4 so not possible to check the site now. Once we get some work around solution we will try it again on live

### Proposed solution
We assume site should be working well in all cases. With Multiple websites and  Sub domains.

**Comment by engcom-Charlie** [comment]
Hello @MeetKamal ! Thank you for report !
We are not able to reproduce your issue , feel free to reopen it in case you can provide steps to reproduce it .
