### ISSUE TITLE
Products which are not assigned to any store are automatically being force-assigned a store ID after being saved

### ISSUE THREAD

**Issue by diamondavocado** [magento/magento2#23383]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Find a product in your store which is not currently assigned to any store/websites. 

In my case, I achieved this by deleting several old websites (store views) which left a bunch of products "orphaned" without a store ID. 

For testing purposes you could also un-tick all of the boxes under the "Product in websites" section in the Magento admin panel -> Manage products -> [your product] area.

You could probably also achieve this by deleting a product from the `catalog_product_website` database table.

I was able to find a list of all my "orphaned" products using the following query:

    SELECT * FROM catalog_product_entity WHERE entity_id NOT IN (SELECT product_id FROM catalog_product_website);

2. Open the above product in Magento's admin panel (Manage products) section.

3. Don't make any changes (or you can change the product title etc. if you wish) but just hit the "Save" button to save the product.

### Expected result (*)

1. Since you haven't touched the "Product in Websites" section, the product should remain orphaned (i.e. it should NOT have a store ID associated with it). The product should NOT appear in the `catalog_product_website` table.

### Actual result (*)

1. The product is automatically assigned a store ID. If you expand the "Product in websites" section, the first website checkbox is automatically ticked. The product DOES appear in the `catalog_product_website` database table even though you have not chosen to assign this product to a store.

**Comment by diamondavocado** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @diamondavocado. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @diamondavocado, here is your [Magento instance](https://i-23383-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23383-2-3-develop.instances.magento-community.engineering/admin](https://i-23383-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by diamondavocado** [comment]
I was able to reproduce this on 2.3-develop instance.

I created a product but made sure to **assign it to no stores**:

![image](https://user-images.githubusercontent.com/32345083/60030772-7d6e7900-969b-11e9-8b80-1fa158b789f2.png)

The products grid shows that no stores/websites have been associated with this product:

![image](https://user-images.githubusercontent.com/32345083/60030912-b4448f00-969b-11e9-9b05-3d54ae6923f4.png)

However, I then returned to the Edit Product page, and expanded the "Product in websites" section and it has automatically pre-checked the "Main Website" box:

![image](https://user-images.githubusercontent.com/32345083/60031001-dc33f280-969b-11e9-9dc2-63c4472a639e.png)

At this point, if I were to Save this product, it would be associated with the Main Website. 
I do not save the product at this stage.

I refresh the page and this time I **do not** expand the "Product in websites section":

![image](https://user-images.githubusercontent.com/32345083/60031174-21582480-969c-11e9-8cd9-6622d2629c73.png)

I do not edit anything at all and I click the Save button to save the product.

Now I discover the product has forcibly been assigned to the Main Website store even though I did not even expand that section:

![image](https://user-images.githubusercontent.com/32345083/60031235-4351a700-969c-11e9-9c3b-a06d1b12cb96.png)

This is the bug.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17780`, `MC-17781` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by manishgoswamig** [comment]
I am working on this issue.

**Comment by magento-engcom-team** [comment]
Hi @diamondavocado. Thank you for your report. 
The issue has been fixed in magento/magento2#23500 by @manishgoswamij in 2.3-develop branch
Related commit(s):
 - [45e211f0ee5a3f7fb5606915d2b2eb326967d3b5](https://github.com/magento/magento2/commit/45e211f0ee5a3f7fb5606915d2b2eb326967d3b5)
 - [50c051f3bee94921e2be0c2349edf0c08ba9a2b2](https://github.com/magento/magento2/commit/50c051f3bee94921e2be0c2349edf0c08ba9a2b2)

The fix will be available with the upcoming 2.3.3 release.
