### ISSUE TITLE
Minicart qty does not update when using POST /V1/guest-carts/{cartId}/items API

### ISSUE THREAD

**Issue by dr0uleau** [magento/magento2#2339]
The orange minicart quantity value does not update when a POST request to this REST API is processed successfully. If I click the minicart to popup the list of items and the big blue "Go to Checkout" button, the new item/item quantity is also not updated in this list. However, when I click "view and edit cart" I can see all the items I added and correct quantities.

Even after flushing the cache on the server side, I still see no change.

I've attached the script I am using to submit the POST request (rename to .php).
[addItemToGuestQuote.txt](https://github.com/magento/magento2/files/33291/addItemToGuestQuote.txt)

Example call to this script:
php app/code/Training5/WarrantyApi/shell/addItemToGuestQuote.php --cart_id=da38e7c3712f7702452b45c143f2f51e --sku=dans-product2 --qty=1

**Comment by ishakhsuvarov** [comment]
@dr0uleau Thank you for reporting this. 
We already have similar item in the backlog (MAGETWO-35354). Ticket will be updated when the issue is fixed.

**Comment by magento-engcom-team** [comment]
@dr0uleau, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
