### ISSUE TITLE
Product prices: not caluclated based on exchange rates

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#23395]
### Preconditions (*)

1. Magento 2.2.x CE
2. Multistore, 2 websites (for testing)
3. Prices per website, each website different currency, 1 USD, 1 EUR
4. Exchange rates set manually to reflect different exchange rates, for example USD/EUR = 1.5 (just for testing)

### Steps to reproduce (*)

1. Set different base currency for each website
2. Set only display currency for each website (different), 1st: USD, 2nd EUR
3. Set product price on default scope to: 100

### Expected result (*)

1. Price on website 1, USD, should be 100
2. Price on second website, EUR, should be 66,67 EURO

### Actual result (*)

1. Price for USD is 100
2. Price for EUR is 100

Prices for second website are not recalculated on website level.
Price recalculation only works for multiple store views, in my opinion it should also work on website level if exchange rates are set.

**Comment by engcom-Bravo** [comment]
Hello @qsolutions-pl. Thanks for applying. The current behavior is expected and necessary. Catalog Price for the product is 100. It is nether 100$ nor 100€ or any other currency. The price, so to say, gains its currency and its display value in a concrete situation depending on such things as Catalog Price Scope, Base Currency and Display Currency. For a better demonstration assume we have one more website in £ with the following exchange rate USD/GBP = 2. And each of the thre websites has three allowed display currencies USD, EUR and GBP. Also lets have USD as a base currency set for default configuration. So once more the **CATALOG PRICE OF THE PRODUCT IS 100** and the **BASE CURRENCY FOR THE DEFAULT CONFIGURATION IS USD**. Now lets see what we'll have in case the _**Price scope is set to Global**_ (You are not able to set Base Currecy per a website. All the web sites has the same Base currency - the one that is defined in Default Configuration):

Web Site | Base Price | Display USD | Display EUR | Display GBP
-- | -- | -- | -- | --
  |   |   |   |  
Any Web Site | 100$ | 100$ | 66.67€ | 50£

Now if the **_Price scope is set to Website_**  and with that while **CATALOG PRICE OF THE PRODUCT REMAINS 100** You assing **DIFFERENT BASE CURRENCIES TO EACH WEBSITE** accordingly, the result You'll get will be as follows:

Web Site | Base Price | Display USD | Display EUR | Display GBP
-- | -- | -- | -- | --
  |   |   |   |  
USD Web Site | 100$ | 100$ | 66.67€ | 50£
EUR Web Site | 100€ | 150$ | 100€ | 75£
GBP Web Site | 100£ | 200$ | 133.33€ | 100£

In fact to reach the behavior You expect You need to set the catalog price scope to Global.

**Comment by engcom-Bravo** [comment]
@qsolutions-pl, The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
