### ISSUE TITLE
Unable to edit/update Magento2.3.0 Admin login page copyright notice except from core.

### ISSUE THREAD

**Issue by mshoaibqureshi** [magento/magento2#23391]
### Summary (*)

I am experiencing an issue in Magento2.3.0 admin end login page. I need to change the copyright text below the login credentials field box. I am unable to update it from anywhere, except the core file from vendor folder. i.e..
/vendor/magento/module-backend/view/adminhtml/templates/page/copyright.phtml

### Proposed solution

Should be able to extend the copyright section so that we can enter our own text from our own module template copyright.phtml

**Comment by engcom-Charlie** [comment]
Hello @mshoaibqureshi ! Thank you for your report ! 
Seems like you are trying to run custom code. The GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
