### ISSUE TITLE
Magento 2.3.1: Downloadable Purchased Link Items not added due to list result bug in SaveDownloadableOrderItemObserver

### ISSUE THREAD

**Issue by pisc-software** [magento/magento2#23402]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2

### Steps to reproduce (*)

1. Add Downloadable Product with minimum 1 Downloadable Link
2. Create new order in Backend with the Downloadable Product

### Expected result (*)

1. Table "downloadable_purchased_link_item" is filled with the downloadable links from the product.

### Actual result (*)

1. Only "downloadable_purchased_link" receives data.
2. Links are not added to "downloadable_purchased_link_item" due to bug in "SaveDownloadableOrderItemObserver"

### Bug FIX required
In `\Magento\Downloadable\Observer\SaveDownloadableOrderItemObserver`
the downloadable Links are retrieved from the Type Instance, but the list is indexed without the ID of the links:
`
$links = $product->getTypeInstance()->getLinks($product);
`

Later on the ID of the links is checked if part of the list, however the links array is indexed starting with "0" without the Link ID, hence creation of the Purchased Link Item will not happen:

`
foreach ($linkIds as $linkId) {
    if (isset($links[$linkId])) {
`

The Link Repository should return the Array of Links indexed with the Link ID as key.

**Comment by engcom-Bravo** [comment]
Hello @pisc-software. Thanks for reporting. We used as we are supposed to the latest 2.3-develop version when trying to reproduce Your issue. And here is what we've got:
![download](https://user-images.githubusercontent.com/51680745/60180643-2e564e80-9829-11e9-86e1-82811cc340fc.png)
Is there still some expected information missing in downloadable_link_purchased_item table?

**Comment by engcom-Bravo** [comment]
@pisc-software, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by pisc-software** [comment]
> Hello @pisc-software. Thanks for reporting. We used as we are supposed to the latest 2.3-develop version when trying to reproduce Your issue. And here is what we've got:
> ![download](https://user-images.githubusercontent.com/51680745/60180643-2e564e80-9829-11e9-86e1-82811cc340fc.png)
> Is there still some expected information missing in downloadable_link_purchased_item table?

Hello,

you did not get the point. I am talking about the Observer (see original post) where a list is retrieved as array and the array key is used on the loop to identify the purchased link, however the array key is NOT EQUAL the row id in the database.

So the repository list being received by the observer does not use the row id as array key, hence the observer does not work correctly in assigning the link to the purchased link tables.
