### ISSUE TITLE
<depends> field doesn't work in system.xml for "label" fields

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#2340]
The system.xml file allows certain fields to only show when the value of other fields is set to a certain value. For example, you can hide all fields for a custom extension until that extension is changed to "Enabled: Yes". This functionality works well, except it does not work for fields that are of the type "label". The "label" field type is only used one place in Magento 2, but this type is used by third-party extension developers, so it should work. Screenshot describing issue:

![banners_and_alerts_and_configuration___settings___stores___magento_admin](https://cloud.githubusercontent.com/assets/129031/11129735/9f226e28-8946-11e5-9f6a-67313d7838b0.png)

Steps to reproduce problem:

* Add XML like this to an adminhtml/system.xml file in any enabled module:

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Config:etc/system_file.xsd">
    <system>
        <section id="tax">
            <group id="custom_tax" translate="label" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="1">
                <label>Custom Tax Settings</label>
                <field id="enabled" translate="label" type="select" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Enable Custom Tax</label>
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </field>

                <!-- The "depends" node in this field will not work because the type of this field is "label" -->
                <field id="connection_settings_header" translate="label" type="label" sortOrder="20" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Connection Settings</label>
                    <depends>
                        <field id="enabled">1</field>
                    </depends>
                </field>

                <!-- The "depends" node in this field will work normally. However you need to remove the above field node in order for this to work, as the JS error causes neither "depends" statements to work. -->
                <field id="custom_input" translate="label" type="text" sortOrder="30" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Custom Input</label>
                    <depends>
                        <field id="enabled">1</field>
                    </depends>
                </field>
            </group>
        </section>
    </system>
</config>
```

* Go to *Stores > Configuration > Sales > Tax* to see the new configuration fields.

* Look at the JS console. You'll see an error like this:

![configuration___settings___stores___magento_admin](https://cloud.githubusercontent.com/assets/129031/11129419/cebe7f70-8944-11e5-9155-720a22a72f97.png)

The reason this error is happening is because the JS to handle the `<depends>` functionality assumes that each field will have an input in it, but that is not the case with fields with the type of "label".

I'm working on a pull request to fix this issue and will submit it shortly.

**Comment by okorshenko** [comment]
Closing. Pull request https://github.com/magento/magento2/pull/2343 merged to develop. Thank you for contribution

**Comment by saurabhjain929** [comment]
<field id="connection_settings_header" translate="label" type="text" sortOrder="20" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Connection Settings</label>
                    <depends>
                        <field id="enabled">1</field>
                    </depends>
</field>

Hello,
Your Field type is wrong you can change this code.

Change type="label" to  type="text"
