### ISSUE TITLE
Bad display of product names in the minicart

### ISSUE THREAD

**Issue by chdzma** [magento/magento2#23401]
In the minicart the quotes are replaced by "& quot;", this happens with all the products.

### Preconditions (*)

1. Magento 2.2.8
2. PHP 7.1.24

### Steps to reproduce (*)

1. Create a new product where your name is between quotation marks. Ex: My "Product"
2. Go to page of this product.
3. Add this product in the checkout.

### Expected result (*)

![Selection_010](https://user-images.githubusercontent.com/24399312/60111959-3356c780-976f-11e9-9133-88ccb9bb01c7.png)

### Actual result (*)

![Selection_007](https://user-images.githubusercontent.com/24399312/60111665-a875cd00-976e-11e9-854d-df955a551e61.png)

**Comment by chdzma** [comment]
@magento give me 2.2.8 instance

**Comment by magento-engcom-team** [comment]
Hi @chdzma. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by magento-engcom-team** [comment]
Hi @chdzma, here is your [Magento instance](https://i-23401-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-23401-2-2-8.instances.magento-community.engineering/admin](https://i-23401-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by chdzma** [comment]
Not reproduce on magento 2.2.8. The bug comes from a third party extension. The issue can be closed
