### ISSUE TITLE
missing folder /lib/internal/Magento in 2.1.18

### ISSUE THREAD

**Issue by j0e1an** [magento/magento2#23409]
**### Summary of the issue (*)**
Updated my magento 2.1.16 to 2.1.18 and could not get past setup:upgrade, saying missing serialize. Look for it and found out that the whole folder is missing. Download the zip file from https://magento.com/tech-resources/download also has no such folder but it exists in the github. Any ideas??
**### Preconditions (*)**
no
**### Expected result (*)**
Successfully run the setup:upgrade after update. 
**### Actual result (*)**
[ReflectionException]
  Class Magento\Framework\Serialize\SerializerInterface does not exist

**Comment by xmav** [comment]
@jaycccca 
You may locate framework related code under vendor/magento/framework folder.
Could you please share full exception message with trace ?

**Comment by engcom-Alfa** [comment]
Hi @jaycccca !
The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
Thanks!
