### ISSUE TITLE
Generate coupon code with code length

### ISSUE THREAD

**Issue by tudn9x** [magento/magento2#23414]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Create new Cart Price Rule
![image](https://user-images.githubusercontent.com/51681379/85837618-eb62ea00-b7a0-11ea-97c1-73c0b8fdaa7b.png)
![image](https://user-images.githubusercontent.com/51681379/85837645-f7e74280-b7a0-11ea-96de-d8f69638e5bf.png)
2. Click on Save and Continue Edit button
3. Open Manage Coupon Codes tab
4. Choose Generate coupon code with **Coupon Qty=99**, **Code Length=2**, **Code format=Numeric**
5. Run `cron:run` twice
6. Reload page

### Expected result (*)

1. Result is 99 coupon codes with series from 00 (or 01) to 99 with code length is 2: 01, 02, 03, .., 99

### Actual result (*)

1. Result is 99 random coupon codes with 3 character not 2: 500, 700, 232, 432, ....
![image](https://user-images.githubusercontent.com/51681379/85837947-7512b780-b7a1-11ea-9eee-9058b1ded10a.png)

**Note:** **Coupon Qty=9**, **Code Length=2**, **Code format=Numeric**.
:heavy_check_mark: It works. Result is 9 random coupon code with 2 character.
![image](https://user-images.githubusercontent.com/51681379/85838314-0e41ce00-b7a2-11ea-872f-dd717c9f589f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17800`, `MC-17801` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by praful-rajput** [comment]
@magento-engcom-team  @engcom-Bravo 
I'm working on this issue.

**Comment by jignesh26** [comment]
@vasuscoin  are you still working?

**Comment by luismiguelyangehuaman** [comment]
@mage

**Comment by luismiguelyangehuaman** [comment]
@magento-engcom-team I'm working this issue

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17801` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35495` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @htmyheart. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-35495` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
