### ISSUE TITLE
Meta Title & Product Description Not Changing through SEO section

### ISSUE THREAD

**Issue by thepratikpatel** [magento/magento2#23419]

**Comment by engcom-Charlie** [comment]
Hello @thepratikpatel ! Thank you for your report !
Could you provide more information about this issue ?

**Comment by krishprakash** [comment]
Hi @thepratikpatel. 
I'm closing this issue as you not provided steps to reproduce.
Feel free to reopen if you confirm issue in venilla magento instace
Thanks
