### ISSUE TITLE
Saving "NOT LOGGED IN" customer group fails

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#2341]
Note that this issue is not encountered unless #2337 is addressed.

The "NOT LOGGED IN" customer group has a DB ID of 0.  Magento\Customer\Model\ResourceModel\GroupRepository::save contains the check "if $group->getId()" when deciding whether to load an existing model.  ID 0 fails this check, and no existing model is loaded, ultimately resulting in a "code already exists" error when attempting to save.

Note that, because the ID ends up set as an int, not a string, in this save method, the fix for this issue will also require that (preferable solution) the check in Magento\Framework\Model\ResourceModel\Db\AbstractDb::_checkUnique be changed from this:
if ($object->getId() || $object->getId() === '0')
to this:
if ($object->getId() || (string) $object->getId() === '0') 
… or else the group repository's save method must be modified to avoid setting the ID as an int.

**Comment by slavvka** [comment]
The issue has a fix in PR #2345 and should be closed after it is merged.

**Comment by slavvka** [comment]
@CNanninga, the issue has been fixed. Please see 6c0b8cf, 5e74abf, d865ca8, b3789a4, f8b2344.
