### ISSUE TITLE
MAGETWO-95294 commit breaks backwards compatibility

### ISSUE THREAD

**Issue by marcusirgens** [magento/magento2#23415]
In commit 021a953482e06a622d1508fe35aa4e744d636493 [lib/internal/Magento/Framework/Search/Adapter/Mysql/ResponseFactory.php](lib/internal/Magento/Framework/Search/Adapter/Mysql/ResponseFactory.php) was changed in a non-backward compatible way that breaks the API of the class (`\Magento\Framework\Search\Adapter\Mysql\ResponseFactory::create` now requires a third array element named "total").

### Preconditions (*)
Magento 2.3.2

### Steps to reproduce (*)
1. Call `\Magento\Framework\Search\Adapter\Mysql\ResponseFactory::create` with the array elements `documents`, `aggregations`

### Expected result (*)

1. The class returns a `\Magento\Framework\Search\Response\QueryResponse`

### Actual result (*)

1. The application throws the exception `Exception #0 (Exception): Notice: Undefined index: total in /base/path/vendor/magento/framework/Search/Adapter/Mysql/ResponseFactory.php on line 72`

**Comment by jgahn-xom** [comment]
Just ran in to this as well, it's broken my development right now as 2.3.2 is required for our Branch Staging deploys. Any idea when that PR will see a release? This is critical for us as I'm trying to put together a proposal for using Algolia on our site Thanks

**Comment by sdzhepa** [comment]
Hello @marcusirgens and @jgahn-xom 

As I can see from the internal Jira ticket `MAGETWO-95294` this change was made intentionally by the Magento team.
And backward incompatible changes were approved
The main reason is perfromance improvement.

Information about it should be on DevDocs:
- [Backward incompatible changes reference](https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/reference.html#231---23-develop)  
- [Magento 2.3 backward incompatible changes](https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/index.html)

**Comment by simonlandry0** [comment]
@jgahn-xom This would be more of an issue for the Aloglia extension side to fix. If you need to fix it now, you can try replicating the changes to the plugin made in this pull request that addresses the issue: 
https://github.com/algolia/algoliasearch-magento-2/pull/806

Alternatively you can wait until they release a new stable version shortly and you'll be able to update to it.

**Comment by marcusirgens** [comment]
Does Magento ship with any guarantees about what kind of content will be protected from backwards-incompatible changes? This file is part of the framework package, which I am surprised does not enforce any BC-guarantees.

**Comment by sdzhepa** [comment]
As I can see the issue has been fixed and merged  https://github.com/algolia/algoliasearch-magento-2/pull/806

Close this issue
