### ISSUE TITLE
Sub-category disabled in global scope not indexed in store scope

### ISSUE THREAD

**Issue by robyerevan** [magento/magento2#23412]
### Preconditions (*)

1.  Multistore Magento 2.3.1 with sample data
2. Category hierarchy with minimum 3 levels and products within category
3. Enabled Layered Navigation

### Steps to reproduce (*)

1. Disable sub-category in global scope
2. Enable same category in store scope
3. Reindex catalog_category_product

### Expected result (*)

1. Category left navigation is showing correct number of items next to category names
2. Sub-category disable in global scope enabled and has products in store scope
3. catalog_category_product_index_store1 table has record of products in sub-category linking them to parent category
4. Layered navigation sub-category filter displaying correct item count.

### Actual result (*)

1. In left navigation parent category has wrong number of items, items of sub-category missing
2. Sub-category appears to have 0 items
3. Records of items of sub-category linking with parent category missing from catalog_category_product_index_store1 index table

**Comment by robyerevan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @robyerevan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @robyerevan, here is your [Magento instance](https://i-23412-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23412-2-3-develop.instances.magento-community.engineering/admin](https://i-23412-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @robyerevan ! Thank you for your report !
I`m not able to reproduce your issue on Vanilla Magento 2.3-develop with sample data.
