### ISSUE TITLE
Exception #0 (Exception): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "#" already exists.

### ISSUE THREAD

**Issue by atomixstar** [magento/magento2#23416]
Hello, I know there are a lot of issues posted related to this problem but I cannot find the solution.

After migrate products from 1.9 to 2.x I am getting the following error on some products "Exception #0 (Exception): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "#" already exists."

Frontpage, Category, Compare etc, I deleted some products manually but I need to fix it in mass.

Now, in frontpage I have a custom module wich show featured products: Here we have a product ID "2", everything is showing and working. If I add the product (ID 2) to compare I am getting this error:

"Exception #0 (Exception): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "2" already exists."

I enabled SQL debug and I found this

`SELECT `e`.*, `t_compare`.`product_id`, `t_compare`.`customer_id`, `t_compare`.`visitor_id`, `t_compare`.`store_id` AS 
`item_store_id`, `t_compare`.`catalog_compare_item_id`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, 
IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) 
AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `cat_index`.`position` 
AS `cat_index_position`, `cat_index`.`visibility`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_compare_item` AS `t_compare` ON (t_compare.product_id=e.entity_id) AND (t_compare.visitor_id = '24429')
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.category_id=7163
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id WHERE (cat_index.visibility IN(3, 2, 4))`

Seems we have an duplicate:

![duplicate](https://user-images.githubusercontent.com/11572616/60166628-318e1200-980a-11e9-91b7-987175043e0e.png)

But is not having an unique column so I cannot simple delete, I just need to know which table have the duplicate. Can someone guide me to the correct table so I can fix the duplicates?

Thank you very much.

**Comment by engcom-Bravo** [comment]
Hello @atomixstar. Problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository. We are supposed to close this issue here. Please reopen it there. Thank You for applying.
