### ISSUE TITLE
Payment methods not visible on checkout

### ISSUE THREAD

**Issue by asshumski** [magento/magento2#23426]
### Preconditions (*)

1. Magento 2.2.8
2. Magento Cloud

### Steps to reproduce (*)

1. Add item to cart and Go to checkout
2. On the first step fill in required data and click next to proceed to the second step (notice that 'next' button is disabled after the first click)
3. Go back to the first step and click 'next' button multiple times, after that 'payment methods' on the second step will blink (they will disappear if you click next button 2 times)

### Expected result (*)

1. Payment methods will not disappear

### Actual result (*)

1. ![Screen Shot 2019-06-26 at 17 12 12](https://user-images.githubusercontent.com/19212187/60187079-9d39a480-9835-11e9-8211-3297260ed788.png)

**Comment by engcom-Charlie** [comment]
Hello @asshumski ! Thank you for your report !
I`m not able to reproduce this issue. Feel free to reopen it in case you can confirm that it`s reproducible on Vanilla Magento instance.

**Comment by asshumski** [comment]
It is reproducible
[magento_2_checkout.zip](https://github.com/magento/magento2/files/3334280/magento_2_checkout.zip)
