### ISSUE TITLE
Dynamically created config fields filtered out in the save controller (M2.3.2)

### ISSUE THREAD

**Issue by mattijv** [magento/magento2#23423]
### Summary

We have a module that adds config fields dynamically to the admin shipping method page. When testing the module in M2.3.2 we ran into an issue where saving any values via the admin page was impossible. The reason is the filter in the save controller added in this commit https://github.com/magento/magento2/commit/8089bd741cd3521943c1b33b6d80c74df8a49667 that strips out all fields not defined in a system.xml file.

In our use case (dynamically created shipping methods) it is impossible to create corresponding system.xml files. Fortunately we can bypass the new filter by making a plugin to the Magento/Config/Model/Config/Structure::getFieldPaths-method. This, however, seems a bit kludgy and non-semantic.

### Examples

1. Create a field in an adminhtml section dynamically.
2. Try to save a value for the dynamic field.

Works in <= M2.3.1, but not in M2.3.2.

### Proposed solution

I'm not 100% sure this even is an issue, since the workaround is fairly obvious. However, I feel there could be a more semantic way of being able to use dynamic fields in the adminhtml. Tricking the filter into believing there are system.xml paths for the config values isn't a great for code smell and readability perspective.

I am not sure what the addition of the filter was meant to fix as there is little info in the commit, but I assume a filter like that is necessary. As I don't think our use case is that outlandish for an extension developer, I think there could be a more obvious method added that can be pluginized into, or some other way of whitelisting fields for the filter. Thoughs?

**Comment by mattijv** [comment]
Since there seems to be no label for it, I want to stress that this is strictly a developer experience issue.

**Comment by engcom-Delta** [comment]
Hi @mattijv thank you for your report. I'm not able to reproduce issue by steps you described on clean 2.3-develop.
![#23423Issue](https://user-images.githubusercontent.com/51681379/60889510-d3c5e500-a261-11e9-8f34-4e85c9ebdd7b.png)

![#23423IssueDb](https://user-images.githubusercontent.com/51681379/60889515-d7596c00-a261-11e9-9d0a-972c24d9a755.png)

If you'd like to update issue, please reopen it.

**Comment by mattijv** [comment]
@engcom-Delta To clarify: by dynamic I don't mean the FieldArray input type. I guess "dynamic" was not a good term.

What I mean by "dynamically" is to use a plugin to add fields (of any input type) that are not defined in a system.xml file. For example by creating a plugin for the `setData` method of `app/code/Magento/Config/Model/Config/Structure/Element/AbstractComposite.php``that adds an additional field besides those defined in a system.xml file.

EDIT: I'm leaving this closed since it's a developer experience issue rather than a functional issue and it's more your decision if you wish this to be discussed more.
