### ISSUE TITLE
Incorrect shipment amount after credit memo.

### ISSUE THREAD

**Issue by supportnubix** [magento/magento2#23437]
### Preconditions (*)
1. Magento 2.2.8 clean install.

### Steps to reproduce (*)
1. Create a new order
2. Add 4 different products to order.
3. Submit the order.
4. Open the newly created order
5. Invoice the order.
6. Create a credit memo.
7. For 2 products set the number to credit on 1 and for 2 products on 0, so you're refunding 2 products.
![image](https://user-images.githubusercontent.com/32568309/60255733-94e27780-98d0-11e9-86d0-0e764909343b.png)
8. Click "Refund offline", you can see in order now that the products are refunded.
![image](https://user-images.githubusercontent.com/32568309/60255770-a9267480-98d0-11e9-97ce-621b7d4b22f0.png)
9. Now create shipment for this order.

### Expected result (*)
1. A shipment with 2 shipped products.

### Actual result (*)
1. A shipment with 4 shipped products, which is incorrect seeing we've refunded 2.
![image](https://user-images.githubusercontent.com/32568309/60255901-e1c64e00-98d0-11e9-9804-5caccd8ff775.png)

**Comment by supportnubix** [comment]
@magento give me 2.2.8-develop instance

**Comment by magento-engcom-team** [comment]
Hi @supportnubix. Thank you for your request. I'm working on Magento 2.2.8-develop instance for you

**Comment by engcom-Charlie** [comment]
Hello @supportnubix ! Thank you for report !
I`m not able to reproduce this issue on Vanilla Magento instance. I`ve tried to reproduce it on Magento 2.3-develop and 2.2.9-develop , seems like it`s not reproducible.
![Screenshot from 2019-06-27 14-16-12](https://user-images.githubusercontent.com/51680850/60262404-bfd7c600-98e6-11e9-814f-0aa71419b712.png)

**Comment by engcom-Charlie** [comment]
@supportnubix Okay , i found a way to reproduce it on Magento 2.2.9-develop
