### ISSUE TITLE
getImageUploadConfigData method is not defined in block and hence throwing undefined method issue.

### ISSUE THREAD

**Issue by sanjay-github** [magento/magento2#23434]
### Preconditions (*)

1. Magento 2.3.2 CE

### Steps to reproduce (*)

1. Have not found specific area where it would show this error but I have used the core code in my application so listing out the files that needs to be checked.

2. Please refer this files 
1.` /var/www/html/magento2/vendor/magento/module-backend/view/adminhtml/templates/media/uploader.phtml.`

2.` /var/www/html/magento2/vendor/magento/module-backend/Block/Media/Uploader.php`

### Expected result (*)

1. Method getImageUploadConfigData() should be defined in the block.

### Actual result (*)

1. Method getImageUploadConfigData() is not defined in the block.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17842` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sanjay-github** [comment]
@engcom-Charlie: I am working on this issue.

**Comment by sanjay-github** [comment]
Just figured out that it is not actually a issue but a different approach to call a method.
This method is not actually defined in the block but added dynamically this way.

```
$this->addChild(
      'uploader',
      \Magento\Backend\Block\Media\Uploader::class,
      ['image_upload_config_data' => $this->imageUploadConfigDataProvider]
);
```
So I am closing the issue.
