### ISSUE TITLE
Magento Admin Panel not loading properly.

### ISSUE THREAD

**Issue by barrakoot43** [magento/magento2#23431]
Hey Everyone,

Just wondering if anyone can help me, all of a sudden i cannot view the Magento Admin Panel, it seems as if the page isn't loading properly or restricted. Any help would be greatly appreciated.

![Screen Shot 2019-06-26 at 4 48 15 pm](https://user-images.githubusercontent.com/52262550/60221000-53939d00-98bb-11e9-8284-d4f340971e59.png)

Magento ver. 2.3.0

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by ajijshekh123** [comment]
Hi @barrakoot43,
This issue related to Default Magento caching or Any config the JS error or Custom module.
If you have found this issue in Magento instance please add Preconditions, Steps to reproduce and Actual result.
If you are not fill up all the details properly I will close this issue shortly.

**Comment by barrakoot43** [comment]
Preconditions:
-I am working with a website developer to build a new Magento based website for our business
-When i login to the Admin Panel the page does not display CSS properly, appears to be broken.
-The website developer is in another country and does not experience this issue, the issue only arises on our end.
![Screen Shot 2019-06-26 at 4 48 15 pm](https://user-images.githubusercontent.com/52262550/60235309-aa649b00-98ea-11e9-93bd-24608ab63a12.png)

Expected result
-I expect to be able to login to the Admin Control Panel and everything displays as it should, the Admin Panel was working fine until yesterday.

Actual result
- I have tried logging in from multiple devices but i always get the same result, the Admin Panel does not display properly.

![Screen Shot 2019-06-26 at 4 48 15 pm](https://user-images.githubusercontent.com/52262550/60235399-f7487180-98ea-11e9-9101-4ef7b3e63c54.png)

**Comment by ajijshekh123** [comment]
@barrakoot43 - It seems that the static resources are giving 404 errors while browsing Magento backend. If this Magento instance is working well at developers end then probably the issue in the network in which you are currently browsing the site and blocks static resources to get rendered.

This doesn't seem Magento's default issue. Please communicate your website developer for the same.

**Comment by barrakoot43** [comment]
Thank you for the reply @ajijshekh123, what would be the possible resolution for this?

**Comment by ajijshekh123** [comment]
@barrakoot43 - As I have mentioned earlier, this is not Magento's default issue and I am afraid we won't be able to help in such cases. For now, I am closing this issue, if you have any further concerns, please feel free to reopen issue again and I will try best to respond to your concern.

**Comment by barrakoot43** [comment]
I think this is absolutely a Magento issue. Magento was working fine, and now it is not. I have tried everything to rectify it outside of Magento but nothing is working which clearly shows this is an issue within Magento. I have searched other issues on this forum and found other people have had similar issues as well and it has been Magento related.
