### ISSUE TITLE
VAT Issues on Checkout after updating to Magento 2.3.2

### ISSUE THREAD

**Issue by KooTjoo** [magento/magento2#23448]
After updating to Magento 2.3.2. I sell goods from withinh EU and therefore EU Countries should get a 0% VAT when VAT ID is correct. This doesn't work poperly for existing customers who created an account earlier. It seems that the VAT Group is not updated properly in the checkout.

### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Create customer account with correct VAT ID
2. Make sure you are in group with 0% VAT
3. Login to Account
4. Place order.
5. Go to Checkout Page

### Expected result (*)

1. Order should show 0% VAT in Overview
2. Order should show 0% VAT in Order Confirmation etc.

### Actual result (*)

1. Order Shows VAT in Checkout
![2 3 2 VAT 1](https://user-images.githubusercontent.com/1156194/60277453-d76e7900-98fd-11e9-994d-f48ae8daca58.png)
2. At the Address Click on EDIT and then Update VAT is set to 0 (this would mean the correct VAT ID is there).
![2 3 2 VAT 2](https://user-images.githubusercontent.com/1156194/60277459-de958700-98fd-11e9-8a6c-3bb65d7d08f3.png)
3. After making order final by clicking on Place Order. The VAT is added despite of it being correct in Checkout view.

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23448-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23448-2-3-develop.instances.magento-community.engineering/admin](https://i-23448-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @KooTjoo can you provide more steps how to reproduce this issue ?
Thanks in advance

**Comment by engcom-Charlie** [comment]
This issue is not reproduced on fresh magento 2.3.2 and 2.3-develop.

**Comment by dragonfly4** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @dragonfly4. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @dragonfly4, here is your [Magento instance](https://i-23448-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-23448-2-3-4.instances.magento-community.engineering/admin_ad20](https://i-23448-2-3-4.instances.magento-community.engineering/admin_ad20)
Login: `63c1b56b` Password: `12500c135616`
Instance will be terminated in up to 3 hours.

**Comment by TvL-NL** [comment]
I found the same issue in version 2.3.4. When an existing customer from an EU country (assigned to correct group) creates an order, VAT is charged on checkout.

To validate i did a fresh install of Magento 2.3.4. Setup VAT validation based on group. All checks out and works fine with guest checkout. When I create an account and enter a valid VAT ID all checks out. Message is displayed (Your VAT ID was successfully validated. You will not be charged tax.) When account is checked in backend, group is changed correctly.

On purchase, VAT is still charged. When same data is used with a guest checkout, no VAT is charged.
