### ISSUE TITLE
Array to string conversion in 2.3.1 value.php

### ISSUE THREAD

**Issue by govereem** [magento/magento2#23442]
### Preconditions (*)
Magento 2.3.1
Set default setting in env.php, something like.
```
    'system' => [
        'default' => [
            'dev' => [
                'js' => [
                    'session_storage_key' => 'collected_errors'
                ],
                'debug' => [
                    'debug_logging' => '0'
                ]
            ], 
```

### Steps to reproduce (*)
When env.php file is set with some values run `bin/magento  app:config:import`

### Expected result (*)
Processing configurations data from configuration file...
System config was processed

Process finished with exit code 0

### Actual result (*)
The change in app/code/Magento/Store/etc/config.xml 
<tiny_mce>/tiny_mce/</tiny_mce>

Will resolve in an error Notice: Array to string conversion in https://github.com/magento/magento2/blob/21b3cafa7e2c2acea150d6555f23906e2872db61/lib/internal/Magento/Framework/App/Config/Value.php#L96 when running `bin/magento app:config:import` in relation to default values set in the env.php 

By adding <tiny_mce> magento will resolve it as array.

**Comment by Rutvee123** [comment]
i am working on it

**Comment by Rutvee123** [comment]
It's not reproduced in Magento2.3.1

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23442-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23442-2-3-develop.instances.magento-community.engineering/admin](https://i-23442-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hi @govereem thank you for your report.  Please, rewrite your code on this:
'system' => [
        'default' => [
            'dev' => [
                'js' => [
                    'session_storage_key' => 'collected_errors'
                ],
                'debug' => [
                    'debug_logging' => '0'
                ]
            ] 
]
],

**Comment by davekleijnkega** [comment]
Hi @govereem,

Had the same problem. I solved this by removing 'system_config_snapshot' inside the 'flag' table.

`DELETE FROM flag WHERE flag_code = 'system_config_snapshot';`

**Comment by usman786cs** [comment]
Thanks @davekleijnkega  - it worked fine for me.

Can you please confirm it will not cause any affect for other configurations.

**Comment by chellinki** [comment]
Thanks, @davekleijnkega - Even it worked for me too in the 2.3.5-p2 upgrade process.
