### ISSUE TITLE
Unable to set sliders to No to unselect components during upgrade to 2.3.2

### ISSUE THREAD

**Issue by melaxon** [magento/magento2#23445]
### Preconditions (*)

1. 2.3.1
2. Developer mode

### Steps to reproduce (*)

1. Proceed to Web Setup Wizard
2. Insert the keys and proceed to system upgrade
3. Set Other components to Yes
4. Wait while the system checks for new versions and try to unselect some components.

### Expected result (*)

1. The sliders must move left and right to select/unselect components
2.

### Actual result (*)

1. The sliders do not move. See screenshot
![2019-06-27_15-41-13](https://user-images.githubusercontent.com/8507631/60271557-3e3e6300-98fb-11e9-8785-13c4d0146483.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17910` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @melaxon. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23804` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
