### ISSUE TITLE
REST API attribute delete lets you delete system attributes

### ISSUE THREAD

**Issue by centipedexv** [magento/magento2#23453]
### Preconditions (*)

1. Magento version 2.3.1
2. MariaDB 10.3.15
3. PHP 7.2.19

### Steps to reproduce (*)

1. example URL: /rest/all/V1/products/attributes/77
2. request type DELETE

### Expected result (*)

1. have some type of error saying you can not delete system defined attributes

### Actual result (*)

1. lets you delete with no error

**Comment by centipedexv** [comment]
yes I was using vanilla Magento

**Comment by shikhamis11** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by shikhamis11** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-23453-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23453-2-2-develop.instances.magento-community.engineering/admin](https://i-23453-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17877`, `MC-17878` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @centipedexv. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3.3-develop` branch(es).
Related commit(s):
 - [564f4411775cc0495a8dd8bffc6a110989c75b7d](https://github.com/magento/magento2/commit/564f4411775cc0495a8dd8bffc6a110989c75b7d)

The fix will be available with the upcoming `2.3.3` release.
