### ISSUE TITLE
Search are not working according to SKU in frontend

### ISSUE THREAD

**Issue by chohanbhagchand** [magento/magento2#23458]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Create a product with SKU in XX-XX format, for example MK-2222, and reindex.
2. Search for MK-2222 in Quick search.

### Expected result (*)

1. Their is no results in search page

### Actual result (*)

1. Product with SKU will be in result

**Comment by krishprakash** [comment]
Hi @chohanbhagchand. Thank you for your report.
Issue is duplicate to #23447
