### ISSUE TITLE
Pending Payment Order Lifetime doesn't expire or cancel orders

### ISSUE THREAD

**Issue by jtalel** [magento/magento2#23455]
### Preconditions (*)

1. Magento Open Source version 2.2.8
2.PHP 7.1.29, MySQL 5.6, Apache 2.4. 
3. Clean install. No extensions or themes installed.

### Steps to reproduce (*)

1. Go to Stores -> Configuration -> Sales -> Sales -> Orders Cron Settings -> Pending Payment Order Lifetime (minutes)
2. Set "Pending Payment Order Lifetime" to 1 minute.  
3. Create a order using a offline payment method such as "Check / Money order"

### Expected result (*)

1. We expect the created order to be cancelled and re-stock items after 1 minute in pending status.

Even though in user guide doesn't explicit say that the order will be cancelled it do say it implies that: https://docs.magento.com/m2/ce/user_guide/sales/order-pending-payment-lifetime.html

### Actual result (*)

1. Order keeps in "pending" status forever unless it's cancelled by the admin.

### EDIT 04/July/2019 ###

Just noticed following issues:

1. It's not possible to assign to a custom status the state "new". Had to change it through database.
2. Assuming the Order Lifetime refer only to the "Pending Payment" method I assigned "new" state to that order and created orders in "pending payment" status.
3. Cron is not cancelling those orders either.
4. Magento is supposed to clean (Cancel) orders as per this question: https://magento.stackexchange.com/questions/206514/does-magento2-cancel-orders-after-2-hours
5) I can't see generation of job "sales_clean_orders" in table cron_schedule as per "Pending Payment Order Lifetime" config in admin.  
6) Nothing happens If i Run following command CLI: `php /var/www/html/magento2/vendor/magento/module-sales/Model/CronJob/CleanExpiredOrders.php`

**Comment by jtalel** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jtalel. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jtalel, here is your [Magento instance](https://i-23455-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23455-2-3-develop.instances.magento-community.engineering/admin](https://i-23455-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jtalel** [comment]
> Hi @jtalel, here is your [Magento instance](https://i-23455-2-3-develop.instances.magento-community.engineering).
> Admin access: https://i-23455-2-3-develop.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

Can't test since this instance doesn't have a cron job running.

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23455-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23455-2-3-develop.instances.magento-community.engineering/admin](https://i-23455-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jtalel** [comment]
> @magento give me 2.3-develop instance

Hello @Den4ik, how do you test a cron related issue on those instances? I tried but couldn't get the expected result. Tought it might be related with a cron not running.

**Comment by magento-engcom-team** [comment]
Hi @jtalel. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jtalel, here is your [Magento instance](https://i-23455-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23455-2-3-develop.instances.magento-community.engineering/admin](https://i-23455-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23455-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23455-2-3-develop.instances.magento-community.engineering/admin](https://i-23455-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
> Hello @Den4ik, how do you test a cron related issue on those instances? I tried but couldn't get the expected result. Tought it might be related with a cron not running.

@jtalel Sorry, I taken fresh instance for different checks. I have past comment in your issue because it was the first in the grid

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23455-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23455-2-3-develop.instances.magento-community.engineering/admin](https://i-23455-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jtalel** [comment]
Just noticed following issues:

1. It's not possible to assigned to a custom status the state "new". Had to change it through database.
2. Assuming the Order Lifetime refer only to the "Pending Payment" method I assigned "new" state to that order and created orders in "pending payment" status.
3. Cron is not cancelling those orders either.
4. Magento is supposed to clean (Cancel) orders as per this question: https://magento.stackexchange.com/questions/206514/does-magento2-cancel-orders-after-2-hours
5) I can't see generation of job "sales_clean_orders" in table cron_schedule as per "Pending Payment Order Lifetime" config in admin.

**Comment by jtalel** [comment]
help wanted

**Comment by jtalel** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jtalel. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jtalel, here is your [Magento instance](https://i-23455-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23455-2-3-develop.instances.magento-community.engineering/admin](https://i-23455-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jtalel** [comment]
@magento-engcom-team Reproduced on 2.3-develop

**Comment by jtalel** [comment]
Ok, So, the actual issue is caused because you have to create orders in "Pending Payment" status, but Magento 2 won't let you select this payment method by default. I'm closing this issue because the issue is beter explain in this link: https://github.com/magento/magento2/issues/23682#issue-467479872
