### ISSUE TITLE
Quote and Order records being deleted from database

### ISSUE THREAD

**Issue by bvboas** [magento/magento2#23463]
### Preconditions (*)
Magento 2.2.6 but also verified on Magento 2.2.9
1. MySQL 5.7
2. PHP 7.1.26
3. Page cache - Redis Cache
4. Session files

### Steps to reproduce (*)
1. Add products to cart
2. Go trough Checkout
3. Click "Submit Order"

### Expected result (*)
1. Order Success page

### Actual result (*)
1. Flux is the same as an order has been placed successfully, but the customer won't receive the new order email.
2. Order is not saved into the database
3. Database records from the quote and quote_* are deleted. The table 'quote' has no record of an auto_increment captures when the event 'sales_order_payment_place_end' is fired.
4. No 'sales_model_service_quote_submit_failure' event is dispatched.
5. 'sales_order_payment_place_end' event is dispatched.

How are database records being deleted? 

No errors in /var/log/exception.log, debug.log, system.log

**Comment by rigroweb** [comment]
I am having this issue as well with Magento 2.3.3

I have seen this occurring across different payment processors with no correlation or commonalities between the orders that this is occurring to.

Was this issue resolved or simply closed?

**Comment by licentia** [comment]
@rigroweb I've closed this issue.

In my case, our client had previously made a custom development with some MySQL triggers firing when adding new records to the sales grid which were falling and breaking the transaction. That's why the records where not being committed. 

I would advise you to check your INNODB engine status to look for any possible issues

Regards

**Comment by bvboas** [comment]
@rigroweb I've closed this issue.

In my case, our client had previously made a custom development with some MySQL triggers firing when adding new records to the sales grid which were falling and breaking the transaction. That's why the records where not being committed.

I would advise you to check your INNODB engine status to look for any possible issues

Regards

**Comment by rigroweb** [comment]
Thank you so much for replying.
What kind of triggers? That might be able to point me in the right
direction.

**Comment by bvboas** [comment]
@rigroweb They were performing some kind of reporting, when adding a new record to the sales table, with a large dataset of records, which was taking too long and returning a timeout.

This was a custom development, and is not included in Magento.

Running the following MySQL query might give you an idea about the problem

```sql
SHOW ENGINE INNODB STATUS
```
