### ISSUE TITLE
Display double quote in order id field in order CSV export time

### ISSUE THREAD

**Issue by meetvora69** [magento/magento2#23465]
Display double quote in order id field in order CSV export time

### Preconditions (*)
1. Magento 2.3.2

### Steps to reproduce (*)
1. Go to admin panel
2. Select sales ->Order
3. Export the order CSV

### Expected result (*)
1. Double quote's should not be display in CSV field title

### Actual result (*)
1. 
![image_2019_06_29T05_10_32_105Z](https://user-images.githubusercontent.com/19776194/60379964-9770d880-9a5a-11e9-97d4-e59a9f3619ee.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23465-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23465-2-3-develop.instances.magento-community.engineering/admin](https://i-23465-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23465-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23465-2-2-develop.instances.magento-community.engineering/admin](https://i-23465-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17884`, `MC-17885` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @meetvora69. Thank you for your report. 
The issue has been fixed in magento/magento2#24969 by @sashas777 in 2.3-develop branch
Related commit(s):
 - [f38ceaf98e3935c4b17419114bb108bef4e43b47](https://github.com/magento/magento2/commit/f38ceaf98e3935c4b17419114bb108bef4e43b47)
 - [b32c65e7c0f046866823025088c18b52d7a19787](https://github.com/magento/magento2/commit/b32c65e7c0f046866823025088c18b52d7a19787)

The fix will be available with the upcoming 2.3.4 release.
