### ISSUE TITLE
Notification counter design issue 

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#23473]
### Preconditions (*)

1. Magento 2.2
2. Magento 2.3

### Steps to reproduce (*)

1. Login to Magento admin dashboard.
2. Please review the attached screenshots. 
3. Getting issue while counter number in two digits.

### Expected result (*)

![image](https://user-images.githubusercontent.com/43603387/60381025-ec691a80-9a6b-11e9-9584-abc73c66079a.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/43603387/60381039-14587e00-9a6c-11e9-8782-8ce798717a54.png)

**Comment by magento-engcom-team** [comment]
@abrarpathan19 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@abrarpathan19 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17892`, `MC-17893` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rogyar** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-23473-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23473-2-3-develop.instances.magento-community.engineering/admin](https://i-23473-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
Hi @abrarpathan19. Could you describe, please, what's exactly wrong with the notification counter? If we are talking about enlarging the "circle" horizontally - it's normal behavior. How do you see the improvement? Enlargement of the circle is not the case: we can enlarge it to fit 2 digits but it results in weird look for 1 digit. Also, what if we have 3 digits?

**Comment by Erik-ID-89** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
@Erik-ID-89 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by thurow** [comment]
#mm19br

**Comment by magento-engcom-team** [comment]
@thurow thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Tduartw** [comment]
@magento I am working on it

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#24589 by @thurow in 2.3-develop branch
Related commit(s):
 - [d009e26e9a199dbddc66cb43832eb1f571c25d59](https://github.com/magento/magento2/commit/d009e26e9a199dbddc66cb43832eb1f571c25d59)
 - [3187c6167bff7cc925249de829ebbeb2ac02dc13](https://github.com/magento/magento2/commit/3187c6167bff7cc925249de829ebbeb2ac02dc13)
 - [07d6cb915944a6a7d43f82177f151c233fa856fc](https://github.com/magento/magento2/commit/07d6cb915944a6a7d43f82177f151c233fa856fc)

The fix will be available with the upcoming 2.3.4 release.
