### ISSUE TITLE
First name and Last name field must not allow to enter URL and Special character's

### ISSUE THREAD

**Issue by meetvora69** [magento/magento2#23487]
### Description (*)
It must not allow to enter URL details for First name and Last name field

### Preconditions (*)

1. Magento 2.2.x
2. Magento 2.3.x

### Steps to reproduce (*)

1. Go to Admin
2. Customers > All customers > Add New Customer
3. Enter URL details for First name Last name field

### Expected result (*)

1. It must not allow user to enter URL, Special character details for first name and last name field

### Actual result (*)

1. https://prnt.sc/o87umo

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17896`, `MC-17897` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vinay-chhabra** [comment]
@magento I am working on it

**Comment by krzksz** [comment]
I'm closing this as the expected result (prohibiting special characters) is an unacceptable solution for people in many countries. There is a [great article by W3C](https://www.w3.org/International/questions/qa-personal-names), which outlines only a few examples of valid names which would be prohibited like `Björk Guðmundsdóttir`, `María-Jose Carreño Quiñones` or `John Q. Public`. Additionally, Magento escapes all the strings it outputs plus customer reviews have to be approved so there is no way for SQL injection or spamming.
