### ISSUE TITLE
Hardcoded Import/Export Class name.

### ISSUE THREAD

**Issue by JamesAnelay** [magento/magento2#2348]
In M1 to add a new Import file type handler e.g .tsv I need to add a new file with the class Mage_ImportExport_Model_Import_Adapter_Tsv in a local codepool (which sucks).
It looks like this is similar in m2 (https://github.com/magento/magento2/blob/develop/app/code/Magento/ImportExport/Model/Import/Adapter.php)

```
$adapterClass = 'Magento\ImportExport\Model\Import\Source\\' . ucfirst(strtolower($type));
```

Would be nice to be able to add a new import type via XML so I don't have to touch the Magento namespace. As is the case with Export types.

**Comment by asemenenko** [comment]
Added an improvement to internal MAGETWO-45472

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Hardcoded-Import-Export-Class-name/idi-p/46503).
