### ISSUE TITLE
(Landscape Mode - iPhoneXS) Listing & Search result page_Shop By_Click on Shopping options & Close icon, It is not working.

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#23486]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Open Home Page > Select any of the Category Or Search any of the product.
2. Open the Listing page Or Search result page.
3. Change the device mode Portrait To Landscape.
4. Click on Up and down icon & Close icon

### Expected result (*)

Shopping options (Size, Price, Color) should be Open and Close and Close icon should be working.

### Actual result (*)

Shopping options and Close icon is not working.

**Comment by ktpl-rammohan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23486-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23486-2-3-develop.instances.magento-community.engineering/admin](https://i-23486-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Give me @magento give me 2.2-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23486-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23486-2-2-develop.instances.magento-community.engineering/admin](https://i-23486-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue reproduced in Magento 2.3 Instance and In Magento 2.2 Instance issue is not reproduced.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17898` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dipti2jcommerce** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce, here is your [Magento instance](https://i-23486-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23486-2-3-develop.instances.magento-community.engineering/admin](https://i-23486-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ptylek** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ptylek. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ptylek, here is your [Magento instance](https://i-23486-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-23486-2-4-develop.instances.magento-community.engineering/admin](https://i-23486-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ptylek** [comment]
Issue is not reproducible.
