### ISSUE TITLE
Billing/Shipping Address edit form design update from order backend

### ISSUE THREAD

**Issue by Kush2507** [magento/magento2#23481]
### Preconditions (*)

1.Magento 2.2
2.Magento 2.3

### Steps to reproduce (*)

1. Admin -> Sales -> Invoices -> Click on View -> Address Information section -> Billing Address/Shipping Address click on Edit 

### Expected result (*)

1. Structure format plan design ought to be consistency according to other Magento structure.
2. Please review link: https://imgur.com/RUALt3B

### Actual result (*)

1. https://imgur.com/5MbXbgi

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23481-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23481-2-3-develop.instances.magento-community.engineering/admin](https://i-23481-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17894`, `MC-17895` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment]
This is a dupplicate of https://github.com/magento/magento2/issues/19805

**Comment by VladimirZaets** [comment]
Hi @Kush2507. Thank you for your report. 
The issue has been fixed in magento/magento2#25699 by @alexey-rakitin in 2.4-develop branch
Related commit(s):
 - [95eea5245b97a8c6f62d435dbfe32c2f3ddcb4c8](https://github.com/magento/magento2/commit/95eea5245b97a8c6f62d435dbfe32c2f3ddcb4c8)

The fix will be available with the upcoming 2.4.0 release.
