### ISSUE TITLE
No images found under pub/static/adminhtml and /frontend

### ISSUE THREAD

**Issue by lgarridoj** [magento/magento2#2349]
The backend dont display any image at all. No Magento logo in the upper left corner, no icons in the left column elements: sales, products, customers, etc.
The folder where images were supposed to be are empty:
pub/static/adminhtml/Magento/backend/en_US/images

In addition, it seems the left column links (sales, products, customers...) are broken. When I click on them nothing happens.

New installation on a local WAMP env.
Magento files cloned via:
git clone -b master https://github.com/magento/magento2.git
Installed via web setup.

**Comment by mazhalai** [comment]
@lgarridoj do you have mod_rewrite turned on? Are you in [production or developer mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html)? If you are in production mode, you need to run [`bin/magento setup:static-content:deploy`](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-static-view.html)

**Comment by lgarridoj** [comment]
@mazhalai Yes, I have mod_rewrite turned on.
I'm trying to find out which mode I'm in by running: magento deploy:mode:show from the magento2/bin folder.
However, I got the error "magento not recognized as an internal or external command..."

**Comment by mazhalai** [comment]
@lgarridoj please try `php bin/magento deploy:mode:show`

**Comment by lgarridoj** [comment]
@mazhalai I got this error "Could not open input file: bin/magento"

**Comment by mazhalai** [comment]
does bin/magento have proper execute permissions? If you are in the bin folder, you should run  `php magento deploy:mode:show`

**Comment by techsoulman** [comment]
I am having the exact same problem and am a real noob, so I am really interested in an answer to this...preferably explained for dummies...
Thanks everyone

**Comment by jibrandlr** [comment]
I have not been able to fix this yet.
I downloaded Magento with Composers.
Installation through Setup Wizard. I attached 2 images to explain the issue better.
![frontend-magento2](https://cloud.githubusercontent.com/assets/8398744/11433211/be74c8e0-947f-11e5-87fb-afe662e52086.jpg)
![backend-magento2](https://cloud.githubusercontent.com/assets/8398744/11433214/c14e0388-947f-11e5-91dc-e72d5b729b72.jpg)

**Comment by jibrandlr** [comment]
@mazhalai is it normal that these folders are empty?
pub/static/adminhtml/Magento/backend/en_US/images

By the way, the command magento deploy:mode:show says I'm in default mode

**Comment by jibrandlr** [comment]
@mazhalai I just run bin/magento setup:static-content:deploy and the backend now looks good, however the front end looks like the image below
![frontend-magento](https://cloud.githubusercontent.com/assets/8398744/11434866/10ff7f7e-9499-11e5-99cd-f052823b6b63.jpg)

**Comment by jibrandlr** [comment]
after restarting my pc, the backend now shows  like this too:
![backend-magento](https://cloud.githubusercontent.com/assets/8398744/11446927/0bb6bbf2-9504-11e5-91d8-52d49770f549.jpg)

**Comment by jibrandlr** [comment]
@mazhalai the folders pub/static/frontend and pub/static/adminhtml are missing.
![no-files](https://cloud.githubusercontent.com/assets/8398744/11447202/f9e4846e-9507-11e5-9645-dfb94aac8e12.jpg)

**Comment by jibrandlr** [comment]
Problem solved. The locale configuration in admin was set to "Español - Mexico", but there are no "es_MX" folder. I changed the locale to "en_US" and worked.

**Comment by mazhalai** [comment]
@lgarridoj closing this issue since it has been resolved. Please feel free to open a new one in case you encounter new issues.
