### ISSUE TITLE
Backed Store View Specific Labels and Manage Coupon Codes label and input not aligned properly.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#23493]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Login into admin panel > Marketing >Cart Price Rules >  Add/Edit any cart rule.

### Expected result (*)

1. ![Expected-result](https://user-images.githubusercontent.com/43638601/60383441-3b27ac00-9a8e-11e9-8cfe-89345e042756.jpg)

### Actual result (*)

1. ![actual-result](https://user-images.githubusercontent.com/43638601/60383449-55fa2080-9a8e-11e9-85bd-a4183f067656.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17899` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Labels cut issue already solved in related issue #22406
Need to do proper alignment for consistency.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
