### ISSUE TITLE
The breadcrumbs are unnecessary shown on the frontend home page of a multistore system when another store has the home page with the same identifier (and my fix)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2350]
https://mage2.pro/t/186

**Comment by vzabaznov** [comment]
To allow us research the issue, please, provide description according to the template.

**Comment by vzabaznov** [comment]
Hi, @mage2pro  thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
