### ISSUE TITLE
Image "Hide from product page" with API not working

### ISSUE THREAD

**Issue by fohnbit** [magento/magento2#23508]
### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1. Upload new product via API Rest Endpoint with 3 images:
`{
  "product": {
    "attribute_set_id": 4,
    "custom_attributes": [
      {
        "attribute_code": "description",
        "value": ""
      },
      {
        "attribute_code": "short_description",
        "value": "Fingerprint"
      },
      {
        "attribute_code": "meta_title",
        "value": "VTO2000A\u002DF"
      },
      {
        "attribute_code": "meta_keyword",
        "value": "VTO2000A\u002DF,\u0020Gedomo\u0020GmbH,\u00204571,\u0020Video\u0020IP\u0020Sprechanlage\u0020Modular"
      },
      {
        "attribute_code": "meta_description",
        "value": "Fingerprint\u0020Leseger\u00E4t\u0020Fingerprint\u0020Leseger\u00E4t\u0020Masse\u003A\u0020110\u002A120\u002A24.9\u0020\u0028H\u002AW\u002AT\u0029\u0020Gewicht\u003A\u00200.27kg,\u0020"
      },
      {
        "attribute_code": "url_key",
        "value": "VTO2000A\u002DF"
      }
    ],
    "media_gallery_entries": [
      {
        "content": {
          "base64_encoded_data": "\u002F902FZ",
          "name": "VTO2000A\u002DF",
          "type": "image\u002Fjpeg"
        },
        "disabled": false,
        "file": "file9026",
        "id": 0,
        "label": "VTO2000A\u002DF",
        "media_type": "image",
        "types": [
          "image"
        ]
      },
      {
        "content": {
          "base64_encoded_data": "\u00h02F9k\u003D",
          "name": "VTO2000A\u002DF_thumb",
          "type": "image\u002Fjpeg"
        },
        **"disabled": true,**
        "file": "9026_small",
        "id": 0,
        "label": "VTO2000A\u002DF_thumb",
        "media_type": "image",
        "position": 2,
        "types": [
          "thumbnail"
        ]
      },
      {
        "content": {
          "base64_encoded_data": "\u00u002FZ",
          "name": "VTO2000A\u002DF_small",
          "type": "image\u002Fjpeg"
        },
        **"disabled": true,**
        "file": "9026_medium",
        "id": 0,
        "label": "VTO2000A\u002DF_small",
        "media_type": "image",
        "position": 3,
        "types": [
          "small_image"
        ]
      }
    ],
    "name": "Fingerprint\u0020Leseger\u00E4t",
    "price": 170.0,
    "sku": "VTO2000A\u002DF",
    "status": 1,
    "type_id": "simple",
    "visibility": 4,
    "weight": 0.0
  },
  "saveOptions": true
}`

### Expected result (*)
1. The images small and thumbs should be "Hide from Product Page"

### Actual result (*)
1. The images are uploaded and displayed .. but the checkbox "Hide from Product Page" isn´t checked  and all 3 images are displayed at frontend. When I set the checkbox in admin, it is hide.
2. Even when you read the "disable" from the products ... I receive it is checked, but it isn´t

Could it be, the Attribute "disabled" at the images are not the "Hide from Product Page"?

**Comment by fohnbit** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fohnbit. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fohnbit, here is your [Magento instance](https://i-23508-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23508-2-3-develop.instances.magento-community.engineering/admin](https://i-23508-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by fohnbit** [comment]
Tested with a new upload ... "hide from Product Page" is not selected! But in the json I set it to true!

**Comment by fohnbit** [comment]
Did you tested? Can you confirm the bug?

Thank you!

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-23508-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23508-2-3-develop.instances.magento-community.engineering/admin](https://i-23508-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @fohnbit 
yes I checked the issue .. I am not able to reproduce it at current magento 2.3-develop instance 
I am adding product with magento rest api here is my request params 

{
  "product": {
    "sku": "p0006",
    "name": "p0006",
    "attribute_set_id": 4,
    "price": 25,
    "status": 1,
    "visibility": 4,
    "type_id": "simple",
    "weight": "0.5",
    "extension_attributes": {
    	"category_links": [
    		{
    			"position": 0,
    			"category_id": "2"
    		},
    		{
    			"position": 1,
    			"category_id": "3"
    		},
    		{
    			"position": 2,
    			"category_id": "4"
    		}
    	],
    	"stock_item": {
    		"qty": "10",
    		"is_in_stock": true
    	}
    },
    "custom_attributes": [
    	{
    		"attribute_code": "description",
    		"value": "The Champ Tee keeps you cool and dry while you do your thing. Let everyone know who you are by adding your name on the back for only $10."
    	},
    	{
    		"attribute_code": "tax_class_id",
    		"value": "2"
    	}
    ],
   "media_gallery_entries": [
    {
      "content":{
       "base64_encoded_data":"correct base64 code for image ",
       "name":"img3.jpeg",
       "type":"image/jpeg"
       },
       "disabled":true,
       "file":"/i/m/img3.jpeg",
       "id":0,
       "label":"img3.jpeg",
       "media_type":"image",
       "types":[
          "thumbnail"
        ]
     }
  ]
  }

}

**Comment by fohnbit** [comment]
Hello,

no, not working on my site.
Did you checked if the Option in the image at admin "Hide from Product Page" is checked after creating the product?

I used your JSON and just add a JPEG.
The Option "
**"disabled": true**
is set, but after upload the new product, it is not hide from product page:
https://ibb.co/ZMNtK5H


`{
    "product": {
        "sku": "p0006",
        "name": "p0006",
        "attribute_set_id": 4,
        "price": 25,
        "status": 1,
        "visibility": 4,
        "type_id": "simple",
        "weight": "0.5",
        "extension_attributes": {
            "category_links": [
                {
                    "position": 0,
                    "category_id": "2"
                },
                {
                    "position": 1,
                    "category_id": "3"
                },
                {
                    "position": 2,
                    "category_id": "4"
                }
            ],
            "stock_item": {
                "qty": "10",
                "is_in_stock": true
            }
        },
        "custom_attributes": [
            {
                "attribute_code": "description",
                "value": "The Champ Tee keeps you cool and dry while you do your thing. Let everyone know who you are by adding your name on the back for only $10."
            },
            {
                "attribute_code": "tax_class_id",
                "value": "2"
            }
        ],
        "media_gallery_entries": [
            {
                "content": {
                    "base64_encoded_data": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEBESDxARFRAVFRgVFRgVFRIVExMVFhIWFhUXGRYYHSggGBonGxUVIjUhJSkrLi8vFx8zODMsNygtLisBCgoKDQ0NFQ8PDi0ZFR0rNysrKysrKysrKysrKystKysrKysrKysrKysrLSsrKysrKysrKysrKysrKysrKysrK//AABEIAO8AnAMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAAAQYEBQcDAgj/xAA2EAACAgEBBQQHCAMBAQAAAAAAAQIDBBEFBiExQRITIlEHIzJCYXGBFDM0UmKhscEkkeHRcv/EABYBAQEBAAAAAAAAAAAAAAAAAAABAv/EABcRAQEBAQAAAAAAAAAAAAAAAAABMRH/2gAMAwEAAhEDEQA/AO4AAAAAAAAAAAAAAAAAAAAADNPtvbSolBcOs7G/crXN/M2OblRrrnZN6RitWcS9Iu8MtHXr623xWaP2I+5X9E/3A7jTYpRUotOLWqa5NNapnocx9Cu8ve48sK1+toSdf6qW+Xzi+HycTpqAAAAAAAAAAAAAAAAAAAAAa7bm0O5r1jo7JeGC85efyQFX3629GHa1+7p8Uv12v2I/TmcFy8uVtkrJvVyer+vEsO/W2O9tWPXLtQg32n+eb9pmjwcGV1sKa+cnxfw14sIuXok2TZLKWVHgoaxj+pPhL6aHfEV7c7YsceiMYrkkkWIKgAAAAAAAAAAAAAAAAAARJ6cW9Eco3+3n7MJ2p8Z610LXlHlOf14cS5737TSiqIy0c05WNe5UvafzfI4FvLtT7Xktx4VQ8MEuUYosRq6eCc5Pi/8AZ1X0Ubrv7+xeKemnwiUjdLYry8lRS9XDRy/pH6L2ThKqtRSIrMhHRaI+iCQIAAAAAAAAAAAAAAAAMXaedGmqds3pGK1+fkjKOd777ei5S140Y/NdLLtPDH4pAUvf/b84wlBv/IyPFZ+iHuV/Qo9VDSjCC1sm9D0syHdbO+168dfqXj0Ybuu637RYuGukE/3YqL76Ot2o49EdV4nxk/Nl3POmtRSS5HoFCSCQIAAAAAAAAAAAAAAD4utUYuUnpGK1b8kgNNvXtZ0VdmvTv7dYVry85fJanBt8No95ZDGpfq69e0/zS9+T+upad9d52+3ke9YnXQvyVLnL5tnO6ouENXxsny8wjYbJ2Y8m6FFa8K9tryP0Tu3sqNFUYxSXBIpfou3X7qvvLF6yXGXD/SOlpBQAACSCQIAAAAAAAAAAAAAGUPf/AG2m3jRlpXFdvIkvL3YfN8Syb0bZWLQ587JeGuP5pvl9Dgm9205N/Z4y7Vk5OVsvzTfNa+SLEavNzXlXyslwrjyXkuiRYdw9iPLye9kvVQfh8myvU4bnKvGq4yb8TXn1Z+gdydgxxqIxS5Iit9hYyrgooyAAAAAEkEgQAAAAAAAAAAB53Wxiu1JpJdWehVd5bL7baa8SNU64y1uc2+xHTknoBRfSDtm1TeRdXOMI6148Wno9edj+fA5pjtxUr7Pbl7Ovz5nZNqbRWbk14uTDsVRlpOS1dUtOSU9NFqVzbG5lb2lGFLbxtE+zz7LXT5Dpxl+inddv/ItXinppr0j0OxQjotEYWx8FVVqKWnAzgAAAAAASQSBAAAAAAAAAB8XWKMXKT0ilq35JAYG3syUKJ93xtaagurfwKXmbWvxsOFV1MXdYn4a3LvdW+sWuLfmb+jL4WZty0WnZpi+kfPj1fM0ezMd5HfZd0moLhX0eq5tfsSqx82Ea8CMq7O1OyOsk/wA3RNc00zJ3C2RZr3t/GTS+iK9s7DuyMqcW9alPXX8z16nW8HHUIKIiMgAFAAAAAAJIJAgAAAAAAAAr22rHfcsWD9WtJ3y8o9IfXibHbe0VRU585vhBdZSfJfwVjaWV9jxWpPXIt8Vj66vp9AMXb+RLLyIYlHCtcHpyjFaf0fW9ueqoQxqOSXZWnV8tT72Jj/ZMWV9v393H4xia7dnBlk3u6erin4dfLzMzVWjc3ZPdVJtcX+76llPmqCSSXQ+jSAAAAAAAABJBIEAAAAABEnpzJK/vLlyk4YlD9bb7TXuV9X8AMWvIV908qf4ajWNS6Sl1l8eRodnVPOzJW2/cVPV+TfRHvvXmJKvCxf8A5SXnyPbbFkcHEjRBrttazfVvQzVjV7xZ0sm9U1+z8OSii+bB2cqqkkuhWNxtjPjdYvFLi/6L0WRAAFAAAAAAAAAkgkCAAAAAGLtPPhTVO2b8MVr830S+LKpVfKiizMu/EX8Un7kPdS/2ZGZYszK7vX/ExvFY+k7Oi16paM0O0rJbQzY0Qfqo8Z6clFEoy90sbTvM/I+KrT/dmqojLNy9XxhF6/Bs2G+W0l4MXH5LwpIsO6GxlTUtV4v76sQb3Dx1XBRXQ9wCgAAAAAAAAAABJBIEAAAaHezasqq1XTxyLn2K11WvOXyRusm6MISnNpRitW30SKZsq/vJW7SvWi9miL6RXX68APDbl8cHEjj1vWyXtPXjKb5npgVLZ+G52fiLl2pea4cvpqYG7eK8zKnl3v1FT8OvJy/4Yu3s2WblKqHsJ8dOiM6r23P2bLIud9i58tfI6XCOi0Rg7FwFVWopdDYGkAAAAAAAAAAAAAAkgkCAwanebbKxceVnOb8NcespvkBpt5rpZV8MGp+BPtXyXRLlH+TS735rtsqwsXlwitOi5amXXL7Bhztuf+Vd45+a146Hjubid1VbtDJXjn92n0j/ANMj13iyYYOJDFp9rTSXm3/1mRuJsTsx7yz2pcX/AOFc2ZTLOy3ZLVwi+Hk2dVxaVCKiiweoAKAAAAAAAAAAAAAASQSB8ylom3wSKHiXLOzJ5U/weNwr15Tn1fx5GZ6Ts+6vEUKNO1a+y35R6/yVrO2q6tm0101OC4Rk1xj2n1bXL6ko9ZxltPO7Gr7it9qbXLTyPTfbaneThi4/CK8PD+foZy7GzcBRUk77V2pS4dUYW42x5WTd9qer5a9F0JBbN0tjqiqK046FgIitFouSJNAAAAAAAAAAAAAAAAASQSBq94NlrIqcJfNfBnMM3Dtxu1GSk4Pg+DcZL4o7FoY+ThQmtJRTA4zg4l2TbCtqfcx89eX5Vr0OwbJwVVWopdD6xtmVw4xijM0AAAAAAAAAAAAAAAAAAAASQSB//9k=",
                    "name": "img3.jpeg",
                    "type": "image/jpeg"
                },
                "disabled": true,
                "file": "/i/m/img3.jpeg",
                "id": 0,
                "label": "img3.jpeg",
                "media_type": "image",
                "types": [
                    "thumbnail"
                ]
            }
        ]
    }
}`

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-23508-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23508-2-3-develop.instances.magento-community.engineering/admin](https://i-23508-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@fohnbit 
I checked this at magento 2.3-develop instance it's working fine . Please check screenshots 
![Screenshot from 2019-07-05 22-17-41](https://user-images.githubusercontent.com/25526037/60736011-2e65f500-9f73-11e9-8e8e-0453dadef173.png)
![Screenshot from 2019-07-05 22-18-27](https://user-images.githubusercontent.com/25526037/60736012-2efe8b80-9f73-11e9-9d30-9c8d001acd8f.png)
![Screenshot from 2019-07-05 22-19-59](https://user-images.githubusercontent.com/25526037/60736013-2efe8b80-9f73-11e9-91ef-290ac819ac20.png)

Please share screen shots of 2.3-develop instance if you think issue still exists.

**Comment by shikhamis11** [comment]
@fohnbit 
I checked this at magento 2.3-develop instance it's working fine . Please check screenshots 
![Screenshot from 2019-07-05 22-17-41](https://user-images.githubusercontent.com/25526037/60736011-2e65f500-9f73-11e9-8e8e-0453dadef173.png)
![Screenshot from 2019-07-05 22-18-27](https://user-images.githubusercontent.com/25526037/60736012-2efe8b80-9f73-11e9-9d30-9c8d001acd8f.png)
![Screenshot from 2019-07-05 22-19-59](https://user-images.githubusercontent.com/25526037/60736013-2efe8b80-9f73-11e9-91ef-290ac819ac20.png)

Please share screen shots of 2.3-develop instance if you think issue still exists.

**Comment by fohnbit** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fohnbit. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fohnbit, here is your [Magento instance](https://i-23508-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23508-2-3-develop.instances.magento-community.engineering/admin](https://i-23508-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by fohnbit** [comment]
Hi @shikhamis11 

it is not working on my site. I made a complete video to show you my steps:
1. Login as admin and setup API to get access token (in the video you see just an integration that I test before and which I deleted)
2. upload the JSON above with the access token (bearer authentification) with Postman
3. open product at admin and check image
4. At the end of the video you see, the **"disabled": true** was set and the response was also **"disabled": true** ... but the image is still not "Hide from Product Page"

So when its working at your site ... which steps did you made different? Different way of upload? Different authentification?

Here is the video:
[magento2.zip](https://github.com/magento/magento2/files/3378004/magento2.zip)

Here is the response of the Post command:
`{
    "id": 2,
    "sku": "p0006",
    "name": "p0006",
    "attribute_set_id": 4,
    "price": 25,
    "status": 1,
    "visibility": 4,
    "type_id": "simple",
    "created_at": "2019-07-10 14:28:09",
    "updated_at": "2019-07-10 14:28:09",
    "weight": 0.5,
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "category_links": [
            {
                "position": 0,
                "category_id": "2"
            }
        ],
        "stock_item": {
            "item_id": 2,
            "product_id": 2,
            "stock_id": 1,
            "qty": 10,
            "is_in_stock": true,
            "is_qty_decimal": false,
            "show_default_notification_message": false,
            "use_config_min_qty": true,
            "min_qty": 0,
            "use_config_min_sale_qty": 1,
            "min_sale_qty": 1,
            "use_config_max_sale_qty": true,
            "max_sale_qty": 10000,
            "use_config_backorders": true,
            "backorders": 0,
            "use_config_notify_stock_qty": true,
            "notify_stock_qty": 1,
            "use_config_qty_increments": true,
            "qty_increments": 0,
            "use_config_enable_qty_inc": true,
            "enable_qty_increments": false,
            "use_config_manage_stock": true,
            "manage_stock": true,
            "low_stock_date": null,
            "is_decimal_divided": false,
            "stock_status_changed_auto": 0
        }
    },
    "product_links": [],
    "options": [],
    "media_gallery_entries": [
        {
            "id": 2,
            "media_type": "image",
            "label": "img3.jpeg",
            "position": 1,
            "disabled": true,
            "types": [
                "thumbnail"
            ],
            "file": "\/i\/m\/img3_1.jpeg"
        }
    ],
    "tier_prices": [],
    "custom_attributes": [
        {
            "attribute_code": "image",
            "value": "no_selection"
        },
        {
            "attribute_code": "small_image",
            "value": "no_selection"
        },
        {
            "attribute_code": "thumbnail",
            "value": "\/i\/m\/img3_1.jpeg"
        },
        {
            "attribute_code": "swatch_image",
            "value": "no_selection"
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "msrp_display_actual_price_type",
            "value": "0"
        },
        {
            "attribute_code": "url_key",
            "value": "p0006"
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "2"
            ]
        },
        {
            "attribute_code": "description",
            "value": "The Champ Tee keeps you cool and dry while you do your thing. Let everyone know who you are by adding your name on the back for only $10."
        }
    ]
}`

**Comment by fohnbit** [comment]
Hello,

as you in see in my video it is not working. Please check my video.

Thank you!
