### ISSUE TITLE
Help tooltip icon extra space issue

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#23502]
### Preconditions (*)

1. Magento 2.2
2. Magento 2.3

### Steps to reproduce (*)

1. Login to Magento admin
2. Where help tooltip available in Magento admin
3. Please review the attached screenshots. 

### Expected result (*)

I would like to remove/reduce extra space from the left side which is not proper as per Magento standard. 

![image](https://user-images.githubusercontent.com/43603387/60384262-52b86200-9a99-11e9-985d-68d6188af72a.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/43603387/60384302-9f9c3880-9a99-11e9-9ab6-fad4547bc52a.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17900`, `MC-17901` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amjadm61** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amjadm61. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amjadm61, here is your [Magento instance](https://i-23502-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23502-2-3-develop.instances.magento-community.engineering/admin](https://i-23502-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by e-neria** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
@eneria2209 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by e-neria** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eneria2209. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by alefemafra** [comment]
@magento I am working on it

**Comment by alefemafra** [comment]
@magento I am working on it

**Comment by ptylek** [comment]
Issue is not reproducible
