### ISSUE TITLE
Additional addresses disappears after select upper limit from 2nd pagination.

### ISSUE THREAD

**Issue by anerishah1** [magento/magento2#23501]
### Preconditions 
magento 2.3

### Steps to reproduce 
1. Go to My account >> Address book
2. Add more than 10 additional addresses
3.  Go to Addresses on 2nd pagination
4. Now select uper limit (20,50) from pagination drop-down
5. It will disappears all the additional addresses

### Expected result 
All addresses should display in the list.

### Actual result 
![image](https://user-images.githubusercontent.com/50940094/60384132-85f9f180-9a97-11e9-8a4a-61a035aaa532.png)

**Comment by ktpl-rammohan** [comment]
Issue is duplicate to #21396
