### ISSUE TITLE
City,Fax,VAT Number,Company,Billing Firstname and Billing Lastname not update if customer have no saved address

### ISSUE THREAD

**Issue by vrajesh-patel1993** [magento/magento2#23503]
### Preconditions (*)

1.Magento 2.2.x
2.Magento 2.3.x

### Steps to reproduce (*)

1. Go to Admin
2. Customers >> All Customers
3. From customer grid Add City,Fax,VAT Number,Company,Billing Firstname and Billing Lastname
4. Click on save
5. Display success message like "You have successfully saved your edits"but it does not saved.

### Expected result (*)

1. https://prnt.sc/o8ahi5

### Actual result (*)

1.Text fields should not be display and saved in inline editor for Phone and zip code if customer not saved any address.

**Comment by krishprakash** [comment]
Hi @vrajesh-patel1993. Thank you for your report.
Issue is already added and duplicated to #23467
