### ISSUE TITLE
Cache management won't refresh at all & stays on disabled. 

### ISSUE THREAD

**Issue by vivianCollins11** [magento/magento2#23513]

**Comment by vivianCollins11** [comment]
my website was working fine up till last Tuesday, My private servers hosting company reduced my ram from 4GB to 2GB without realising that I was paid for until 19-September-2019. This resulted in my website going completely down and all buyers could see is "HTTP ERROR 500"..
A potential customer saw this and called my number which in turn I called my server hosting support team who rectified their error and increased the servers ram back up to 4GB. 

Even though they increased the ram and the website came back up, the website runs like a snail both front and back end & on top of this the Cache management won't enable when I select refresh.

Server was running on PHP 7.1, the server hosting company changed it without asking me to PHP 7.2 when they asked me for my passwords when they went to fix the ram issue.

It has been 6 days now that I have had no customers as they get frustrated with a slow website  that neither I or my web developer or server experts at my web developers company nor the server level 3 experts at my server hosting company can fix, therefore I request your urgent help in this matter

Kind regards

Vivian

**Comment by shikhamis11** [comment]
Hi @vivianCollins11 
It seems some issue due to your server 
GitHub is intended for Magento 2 core functionalities bug for discussion you can use 
https://community.magento.com and https://magento.stackexchange.com
