### ISSUE TITLE
Magento 2.3.2 Undefined offset Encryptor.php

### ISSUE THREAD

**Issue by zhiyicai** [magento/magento2#23511]
#22849 # Preconditions (*)

1. Magento 2.3.2 community edition
2. nginx 1.16
3. php 7.2.19

### Steps to reproduce (*)

1.login magento store admin

### Expected result (*)

1. {"0":"Notice: Undefined offset: 2 in \/www\/web\/demo\/vendor\/magento\/framework\/Encryption\/Encryptor.php on line 588"
### Actual result (*)

1. {"0":"Notice: Undefined offset: 2 in \/www\/web\/demo\/vendor\/magento\/framework\/Encryption\/Encryptor.php on line 588","1":"<pre>#1 Magento\\Framework\\Encryption\\Encryptor->getArgonHash() called at [vendor\/magento\/framework\/Encryption\/Encryptor.php:278]\n#2 Magento\\Framework\\Encryption\\Encryptor->isValidHash() called at [vendor\/magento\/framework\/Encryption\/Encryptor.php:266]\n#3 Magento\\Framework\\Encryption\\Encryptor->validateHash() called at [vendor\/magento\/module-user\/Model\/User.php:608]\n#4 Magento\\User\\Model\\User->verifyIdentity() called at [generated\/code\/Magento\/User\/Model\/User\/Interceptor.php:206]\n#5 Magento\\User\\Model\\User\\Interceptor->verifyIdentity() called at [vendor\/magento\/module-user\/Model\/User.php:580]\n#6 Magento\\User\\Model\\User->authenticate() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#7 Magento\\User\\Model\\User\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#8 Magento\\User\\Model\\User\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/mirasvit\/module-event\/src\/Event\/Event\/Admin\/LoginEvent.php:135]\n#9 Mirasvit\\Event\\Event\\Admin\\LoginEvent->aroundAuthenticate() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#10 Magento\\User\\Model\\User\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#11 Magento\\User\\Model\\User\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/User\/Model\/User\/Interceptor.php:195]\n#12 Magento\\User\\Model\\User\\Interceptor->authenticate() called at [vendor\/magento\/module-user\/Model\/User.php:635]\n#13 Magento\\User\\Model\\User->login() called at [generated\/code\/Magento\/User\/Model\/User\/Interceptor.php:219]\n#14 Magento\\User\\Model\\User\\Interceptor->login() called at [vendor\/magento\/module-backend\/Model\/Auth.php:162]\n#15 Magento\\Backend\\Model\\Auth->login() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#16 Magento\\Backend\\Model\\Auth\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#17 Magento\\Backend\\Model\\Auth\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#18 Magento\\Backend\\Model\\Auth\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Backend\/Model\/Auth\/Interceptor.php:78]\n#19 Magento\\Backend\\Model\\Auth\\Interceptor->login() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:205]\n#20 Magento\\Backend\\App\\Action\\Plugin\\Authentication->_performLogin() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:157]\n#21 Magento\\Backend\\App\\Action\\Plugin\\Authentication->_processNotLoggedInUser() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:125]\n#22 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#23 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#24 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Backend\/Controller\/Adminhtml\/Index\/Index\/Interceptor.php:39]\n#25 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#26 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#27 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#28 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#30 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#31 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#32 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#33 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#34 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/m_demo\/admin\/index\/index\/key\/ed11bf3331221182a6\/","script_name":"\/index.php"}

**Comment by AigarsMurins** [comment]
I was encountering the same issue on a fresh 2.3.2, but I was using php 7.1.3. Haven't done much investigation, but what I noticed was that it was selecting ARGON2ID13 instead of SHA256 for hashing in \Magento\Framework\Encryption\Encryptor::getLatestHashVersion because I had 'sodium' extension. I decided switching to php 7.2.19 and this resolved this issue for me.

**Comment by evs-xsarus** [comment]
Duplicate with https://github.com/magento/magento2/issues/23405

**Comment by shikhamis11** [comment]
Hello @evs-xsarus thanks for your information.
since it is duplicate issue I am closing this one.
@zhiyicai you can check the progress of this issue with #23405

**Comment by asrar7787** [comment]
I randomly got trapped into this bug on Magento Cloud as well. _The fix was to remove the admin user having issues with and create a new one._

**Comment by hostep** [comment]
Yes indeed.

For the record, for people running against this problem:
This can happen when you take a database where one or multiple of the password hashes of customers and/or admin users got upgraded from the old sha256 hash to the new argon2id hash. And then using that database on a system where you don't have support yet for argon2id.

So if you do run against this problem, try installing libsodium >= 1.0.13 and the php sodium extension, which should give your system support for the argon2id algorithm and then you will no longer have this error in theory.

Hope this helps.

**Comment by mnoman83** [comment]
Hi,

I have just solved the issue, you don't need sodium any more, just follow this
1.  goto vendor/magento/framework/Encryption/Encryptor.php
2. comment code from line 165 to 167 like this 
//if (extension_loaded('sodium')) {
//            return self::HASH_VERSION_ARGON2ID13;
//        }
it will start working.

Good luck

**Comment by peter-warmenhoven-zz** [comment]
Changing my password with bin/magento admin:user:create was enough for me

**Comment by Yonn-Trimoreau** [comment]
`UPDATE admin_user SET password = CONCAT(SHA2('xxxxxxxxNewPassword', 256), ':xxxxxxxx:1') WHERE username = 'admin';`

**Comment by kleestb** [comment]
we run libsodium >=1.0.13 and commented encryptor.php, but the problem persists :-(

any other idea?

**Comment by mnoman83** [comment]
> we run libsodium >=1.0.13 and commented encryptor.php, but the problem persists :-(
> 
> any other idea?

which php version are you using ? make sure php version  should be 7.2 or greater

**Comment by kleestb** [comment]
php version is 7.2.15

**Comment by mnoman83** [comment]
i can solve it

**Comment by kleestb** [comment]
how?

**Comment by Yonn-Trimoreau** [comment]
grabbing a donut

**Comment by mnoman83** [comment]
you need to provide me your server details

**Comment by Yonn-Trimoreau** [comment]
https://media.giphy.com/media/L0f8DZfq7xwdnapptG/source.gif

**Comment by kleestb** [comment]
you can see all details here: https://shopgeistlichcom.stage5.cs2.ch/stefan.php

**Comment by RishiRanjan21** [comment]
Try this

if you are using localhost go to php.ini file and remove ; from below extension

`;extension=sodium`

or if you are using any server enable sodium extension on it

**Comment by DavaGordon** [comment]
If you are using PHP 7.2 to fix this id recommend you do the following. this has been tested on multiple instances of Magento and running on a server with multiple instances of php installed

Step 1. 
In the command line run 
`sudo apt remove php-libsodium`

Step 2. 
In phpMyAdmin or another DB client run 
`UPDATE admin_user SET password = CONCAT(SHA2('xxxxxxxxNewPassword', 256), ':xxxxxxxx:1') WHERE username = 'admin';`

Please remember to replace the xxxxxxxx with the crypt key located in your env.php

**Comment by PietroFantini** [comment]
> If you are using PHP 7.2 to fix this id recommend you do the following. this has been tested on multiple instances of Magento and running on a server with multiple instances of php installed
> 
> Step 1.
> In the command line run
> `sudo apt remove php-libsodium`
> 
> Step 2.
> In phpMyAdmin or another DB client run
> `UPDATE admin_user SET password = CONCAT(SHA2('xxxxxxxxNewPassword', 256), ':xxxxxxxx:1') WHERE username = 'admin';`
> 
> Please remember to replace the xxxxxxxx with the crypt key located in your env.php
> 
> ```
>     'crypt' => [
>         'key' => 'xxxxxxxx'
>     ],
> ```

This worked for me but for now I didn't remove "sudo apt remove php-libsodium"

**Comment by BB-000** [comment]
I just created a new user to allow me access. Changing the password of the original user using the new user didn't work for me, but wasn't necessary in my case (local development environment), just needed to get into admin!

`php bin/magento admin:user:create --admin-user="admin" --admin-password="pa55w0rd123" --admin-email="admin@example.com" --admin-firstname="Admin" --admin-lastname="Admin"
`

**Comment by nicholasscottfish** [comment]
I had the same issue but realised it was due to me having switched php version to 7.1.

For anyone have this issue it is definitely worth checking the php version you're running as the first port of call.

**Comment by rajansahota** [comment]
delete your user entries in "admin_passwords" table DB then change your password again.

I have resolved same issue in Magento ver. 2.2.1

**Comment by Eddcapone** [comment]
> Changing my password with bin/magento admin:user:create was enough for me

So do you want to tell your customers that they all have to change their passwords?

**Comment by jarbascerino** [comment]
> I just created a new user to allow me access. Changing the password of the original user using the new user didn't work for me, but wasn't necessary in my case (local development environment), just needed to get into admin!
> 
> `php bin/magento admin:user:create --admin-user="admin" --admin-password="pa55w0rd123" --admin-email="admin@example.com" --admin-firstname="Admin" --admin-lastname="Admin" `

I have magento 2.3.3 running on php 7.2 and for me this solution solved the problem.
