### ISSUE TITLE
Product customizable options of Area type render issue in Dashboard

### ISSUE THREAD

**Issue by vDeggial** [magento/magento2#23510]
### Preconditions (*)

Magento CE 2.2.9

### Steps to reproduce (*)

1. Create a product with a customizable option field of type Area
2. When placing an order for that product fill that Area type field with multiple lines of text
3. Look at the new order in Admin Dashboard

### Expected result (*)

The text of the field value of Area type is rendered with respect of each line (each line of next is on new line)

### Actual result (*)

The value of product customizable option field of type Area is rendered with HTML &lt;br&gt; tag inside

**Comment by vDeggial** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shinoamakusa. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shinoamakusa, here is your [Magento instance](https://i-23510-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23510-2-2-develop.instances.magento-community.engineering/admin](https://i-23510-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vDeggial** [comment]
This is on dev instance:
![screenshot-i-23510-2-2-develop instances magento-community engineering-2019 06 29-16-48-46](https://user-images.githubusercontent.com/9992759/60390544-d9ffd880-9a8d-11e9-96a3-524e78d90d4e.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23510-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23510-2-3-develop.instances.magento-community.engineering/admin](https://i-23510-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17903`, `MC-17904` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-23510-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23510-2-2-develop.instances.magento-community.engineering/admin](https://i-23510-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sunilit42** [comment]
Created pull request for this:-
https://github.com/magento/magento2/pull/23524

**Comment by vDeggial** [comment]
Just wondering if there is any update on this? :p

**Comment by magento-engcom-team** [comment]
Hi @shinoamakusa. Thank you for your report. 
The issue has been fixed in magento/magento2#23524 by @sunilit42 in 2.3-develop branch
Related commit(s):
 - [439831f03bf1ff03902315d5bda490107c4aaa3a](https://github.com/magento/magento2/commit/439831f03bf1ff03902315d5bda490107c4aaa3a)

The fix will be available with the upcoming 2.3.3 release.

**Comment by vDeggial** [comment]
That fix seems to just remove the &lt;br&gt; tag altogether, what I was asking is to make it so the tag is properly rendered so that each line is indeed on new line without the html tag visible in text
