### ISSUE TITLE
Logging in on frontend of Magento 2.3.2 doesn't seem to work properly after you ran 'bin/magento customer:hash:upgrade'

### ISSUE THREAD

**Issue by hostep** [magento/magento2#23517]
### Preconditions (*)
1. PHP 7.2.19 where you have the sodium extension installed, and have libsodium >= 1.0.13 (this is very important!)

### Steps to reproduce (*)
1. Have Magento 2.3.1 installed
2. Create 2 customers in the frontend, remember their passwords
3. Look into the database to the `password_hash` column in the `customer_entity` table, they look something like this: `{64-random-chars}:{32-random-chars}:1` [Screen1](https://www.screencast.com/t/kLZZoIqQTZ)
4. Upgrade to Magento 2.3.2
5. Login with the first customer in the frontend
6. Look at the database again, his `password_hash` has changed to: `{64-random-chars}:{16-random-chars}:2` [Screen2](https://www.screencast.com/t/mcKbvkqXeoG)
7. Logout and log back in with the first customer, notice that this works => **good**
8. Now, assume you can't wait on every customer to login to upgrade their password hash and just do it yourself by running `bin/magento customer:hash:upgrade`
9. Look at the database again, the `password_hash` for the second customer has changed to: `{64-random-chars}:{32-random-chars}:1:2` [Screen3](https://www.screencast.com/t/rLD9w8uWa)
10. Now try to login with the second customer on the frontend, this does not work => **not good**

### Expected result (*)
1. It is expected to be able to login with a customer after you ran `bin/magento customer:hash:upgrade`

### Actual result (*)
1. You can't login with a customer after you ran `bin/magento customer:hash:upgrade`

### Discussion
I assume executing `bin/magento customer:hash:upgrade` upgrades the `password_hash` to the new algorithm, but not by using the unhashed password, because it can't know it. Then on the next login of that particular customer, it should detect this because the hash ends with `:1:2` and then again re-hash it and change it to just `:2`.
But that doesn't seem to be working here for some reason.
Watch out: I have no idea if this is actually how Magento wanted to implement this, but this makes sense. Unfortunately there seems to be something broken in the implementation.

**Comment by hostep** [comment]
I haven't tested it yet on a vanilla installation, but it would surprise me if it actually works on vanilla. I can spend some time testing it on a vanilla installation later if you want me to (bit busy at the moment, sorry).

**Comment by hostep** [comment]
@engcom-Bravo, just FYI: please don't try to test this on the 2.3-develop branch, because parts of the Magento 2.3.2 code which is necessary for this issue hasn't landed yet in the 2.3-develop branch at the time of writing. (specifically this commit: [MC-5843: Add Argon2ID support](https://github.com/magento/magento2/commit/eb2d36a4b0f8669f15cafaaf230c33e73adea653))

**Comment by engcom-Bravo** [comment]
Hello @hostep. I know this. Thanks

**Comment by engcom-Bravo** [comment]
I have 2.3.2 composer version and with upgrade from 2.3.1 to 2.3.2 all reproduce where step9. but I able login both customer1 and customer2. On step10 I have {64-random-chars}:{32-random-chars}:2.

**Comment by hostep** [comment]
Ok, that means that you don't have the sodium php extension installed. So Magento still uses the old password hashing algorithm.
So try to install the sodium php extension, and also libsodium (at least version 1.0.13) and you should be able to reproduce the problem.

**Comment by engcom-Bravo** [comment]
Now checked database: 
![90](https://user-images.githubusercontent.com/51680745/61037608-190a2400-a3d4-11e9-863c-766f59f60222.png)

**Comment by engcom-Bravo** [comment]
{64-random-chars}:{16-random-chars}:2. Then runed bin/magento customer:hash:upgrade. After this problem not reproduce. And Hashe not changed

**Comment by hostep** [comment]
Are you sure you didn't log in first with the second user?

So steps:
1) Magento 2.3.1: create a new user in frontend and logout.
2) Upgrade to Magento 2.3.2, and run `bin/magento customer:hash:upgrade` (do **not** attempt to login before you executed that command)
3) Try to login with the user in frontend, it doesn't work anymore.

*Update*: I've just updated my initial post, the steps to reproduce were a little bit too complex, it should be more clear now.
I also tried to reproduce it again, and was able to trigger the bug, so please follow all the steps carefully.

**Comment by hostep** [comment]
@sdzhepa: any updates? I feel like this is quite an important bug and shouldn't be left hanging here for too long? Thanks!

**Comment by sdzhepa** [comment]
Hello @hostep

Sorry for the long delay with the response we had a problem with reproducing this issue.
Finally, I have reproduced it and added screens to the steps to reproduce.
Tested cases with upgrade from 
-- `2.3.1` to `2.3.2` and 
-- `2.3.1` to current `2.3-develop` (lates commit: adee85d5549c4c2671856f7ebe0caee1142b4324)

Libsodium version
```
php -i | grep libs
libSSH Version => libssh2/1.7.0
libsodium headers version => 1.0.13
libsodium library version => 1.0.13
```
PHP version
```
www/magento# php -v
PHP 7.2.18 (cli) (built: May  8 2019 03:11:14) ( NTS )
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19686` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
Thanks @sdzhepa!

In order to provide more info about what is wrong here and maybe get the community involved in fixing this, we would need to know exactly what the bug is here and what the intention of this were when implementing this upgrade of the password hashing algorithm, so either:
- the `customer:hash:upgrade` command is doing something wrong and mangling up the hashes in a way it wasn't intended
- logging in doesn't support these halfway-upgraded hashes yet

If we know what is wrong and how this was intended to be implemented, it might be easier to find a solution.

Thanks again!

**Comment by Akki-8388** [comment]
Hello @sdzhepa ,

Is there any update regarding this issue, I get same issue when i upgrade site from 2.2.0 to 2.3.2?

**Comment by bchatard** [comment]
Hello @magento-engcom-team 

Any update on this? 
We are facing the same issue when migrating from M1.9 CE to M2.3 EE. The issue seems easy to fix

```php
// in \Magento\Framework\Encryption\Encryptor

    public function isValidHash($password, $hash)
    {
        try {
            $this->explodePasswordHash($hash);
            $hashedPassword = $password;
            foreach ($this->getPasswordVersion() as $hashVersion) {
                if ($hashVersion === self::HASH_VERSION_ARGON2ID13) {
                    $hashedPassword = $this->getArgonHash($hashedPassword, $this->getPasswordSalt());
                } else {
                    $hashedPassword = $this->generateSimpleHash($this->getPasswordSalt() . $hashedPassword, $hashVersion);
                }
                $hash = $this->getPasswordHash();
            }
        } catch (\RuntimeException $exception) {
            //Hash is not a password hash.
            $hashedPassword = $this->hash($password);
        }

        return Security::compareStrings(
            $hashedPassword,
            $hash
        );
    }
```

We need to hash "hashed password" against all hash version to mimic `customer:hash:upgrade` logic

**Comment by sdzhepa** [comment]
Hello @hostep and @bchatard, @Akki-8388

Sorry for the late response but the only couple of minutes ago I received an update from about status for related internal Jira ticket `MC-19686`.

At this moment `MC-19686` has status: RESOLVED and Resolution: Fixed. It means that fix in the delivery queue and will be delivered soon by an internal Pull Request

**Comment by Akki8388** [comment]
thanks for update @sdzhepa

**Comment by onepack** [comment]
This is another great bug. I'm amazed with the amount of "great big" bugs in Magento2.

**Comment by onepack** [comment]
I applied the fix of @bchatard.
Imported the customer passwords again from M1 to M2.3.3
One customer has this hash in the import file: 95a665d0bb5da014912d1b823e12604d:uq
After importing and a successful upgrade:  
`php bin/magento customer:hash:upgrade`
.
Finished

I check the database and the customer password value is still identical. Same hash.
Login in is still impossible for the customer.

What to do?

**Comment by magento-engcom-team** [comment]
Hi @hostep, @bchatard. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [f02cb965d7f0a21404c1e25535f98e74e4b928cd](https://github.com/magento/magento2/commit/f02cb965d7f0a21404c1e25535f98e74e4b928cd)

The fix will be available with the upcoming `2.3.4` release.

**Comment by onepack** [comment]
I was actually facing the issue that I could not log in at all.
Before and after hash upgrade.
Nothing happened to the passwords.
Found out that appending `:0` to the hash fixed things for me.

**Comment by hostep** [comment]
@sdzhepa: can you clarify if you executed `customer:hash:upgrade` before this fix, if you need to run it again, or if everything is screwed in the database and there is no way of getting the passwords back unless a customer resets his password?

It's not for me personally, but having this information might be useful for people who actually ran into this problem.

Thanks!

**Comment by bchatard** [comment]
@hostep @onepack 

In M1, with the following password pattern: `hash_m1:salt`

When you migrate from M1 to M2, you need to use the data migration tool. This tool add `:0` or `:1` to the password (see https://github.com/magento/data-migration-tool/blob/2.3-develop/src/Migration/Step/Customer/Model/AttributesDataToCustomerEntityRecords.php#L186). Now your password looks like this: `hash_m1:salt:m1_hash_algorithm`

Then you need to run the command `customer:hash:upgrade`, which will re-hash the hashed password with latest hash algorithm, and put `:2` to the result. New password: `hash_m1_hashed_with_m2:salt:m1_hash_algorithm:m2_hash_algorithm`

So now (with the fix), Magento will hash the password with M1 hash algorithm, then M2 hash algorithm. If it's ok, the password hash will be updated in the database, to avoid the "hashing chaining"

**Comment by sdzhepa** [comment]
Hello @hostep 

Very good and important question  https://github.com/magento/magento2/issues/23517#issuecomment-550377818 

I have requested an answer to this question from the internal Magento team members who worked on the fix and waiting for a response now.
I will respond here as soon as I have any updates

**Comment by jordanelbaz** [comment]
Hello,

I have a similar issue, when i try to run customer:hash:upgrade i got this error : 

In Address.php line 108:

  "Phone Number" is a required value.


![image](https://user-images.githubusercontent.com/12926641/100139041-2c197900-2e8f-11eb-8421-919569f49ba6.png)

does someone has the same issue ?

Regards,
