### ISSUE TITLE
Alert and Confirmation Widgets aren't well documented

### ISSUE THREAD

**Issue by NickvdMeij** [magento/magento2#23519]
### Summary (*)
After doing some research on the Alert and Confirmation widgets, I noticed some lack in documentation about these widgets on their documentation pages ([here ](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_alert.html) and [here](https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_confirm.html)).
Appearently, both widgets have a `buttons` property, containing an array of buttons which will be displayed. The documentation does not mention you can fill this property yourself, and more so, it simply doesn't even specify is exists. I request that this will be changes, so other developers see this earlier in their development process.

### Examples (*)
```
                              require([
                                  'jquery',
                                  'Magento_Ui/js/modal/alert'
                              ], function ($) {
                                  'use strict';
                                  
                                  $('.alert-modal-content').alert({
                                      title: 'Title',
                                      modalClass: 'alert',
                                      buttons: [{
                                          text: $.mage.__('Button Label'),
                                          class: 'action-primary action-accept',
                        
                                          /**
                                           * Click handler.
                                           */
                                          click: function () {
                                            this.closeModal(true);
                                          }
                                      }]
                                  });
                              });
```

### Proposed solution
Add an explanation to the documentation mentioning the `button` property

**Comment by NickvdMeij** [comment]
> Hi @NickvdMeij. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @NickvdMeij do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @NickvdMeij. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @NickvdMeij, here is your [Magento instance](https://i-23519-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23519-2-3-develop.instances.magento-community.engineering/admin](https://i-23519-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @NickvdMeij ! Thank you for your report !
Please refer here (https://github.com/magento/devdocs/issues) and create same issue there .
