### ISSUE TITLE
Paypal buttons disable issue - Magento 2.3.2

### ISSUE THREAD

**Issue by quantumAV** [magento/magento2#23527]
### Preconditions (*)

1. 2.3.2
2. Fix implemented from 
2.3-develop (#22260)

### Steps to reproduce (*)

1. Fix implemented from 
2.3-develop (#22260)
2. 

### Expected result (*)

1. Hide Paypal Smart buttons on product page 
2.

### Actual result (*)

1. Hide Paypal Smart buttons on product page works as expected
2. Side effect - removes any ability to alter the look of the Paypal Smart Buttons. The buttons on the shopping cart, mini cart and checkout all revert to the standard small buttons with no ability to change colour or size per settings in Paypal Express Checkout - Front End Experience Settings
3. Removing implemented fix - the Smart buttons alter as expected to colour and shape as per Front End Experience Settings

**Comment by engcom-Charlie** [comment]
Hello @quantumAV ! 
Link that you attached is not valid , please update it.

**Comment by quantumAV** [comment]
it keeps giving me an error on the link to 2.3-develop (#22260)
https://github.com/magento/magento2/commit/233e4c51f7d525f4573b11a24ae5a81c13762343

**Comment by quantumAV** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @quantumAV. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @quantumAV, here is your [Magento instance](https://i-23527-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23527-2-3-develop.instances.magento-community.engineering/admin](https://i-23527-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by quantumAV** [comment]
Realised I am unable to confirm this on the develop instance as I would need FTP access to be able to apply the Fix from #22260

**Comment by Nazar65** [comment]
hi @quantumAV  this fix not included on 2.3.2 release ? but this present in 2.3-develop so can you describe what the problem you have ?

**Comment by Nazar65** [comment]
@quantumAV well, I understand what the problem is, I will work on this issue

**Comment by quantumAV** [comment]
I have applied the fix to 2.3.2 and it did hide the paypal smart buttons on the product page which is what the fix is supposed to do. The issue is the side effect of the fix which caused the paypal Smart buttons on the cart, mini cart and checkout to stop being smart buttons – the buttons reverted to being standard Paypal small buttons and the settings  in Paypal Express Checkout - Front End Experience Settings are ignored.

 

When I remove the fix again the buttons act as they should and the Front End Experience settings work to change colours and sizes

 

regards

 

Andrew

quantumAV

 

 <http://www.quantumav.co.uk/> www.quantumAV.co.uk

Tel -  01492 330550

**Comment by quantumAV** [comment]
Is there a temporary fix available for this or will it wait for a future release?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18588` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @quantumAV. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23886` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
