### ISSUE TITLE
The «Magento\CatalogInventory\Observer\DisplayProductStatusInfoObserver» obverver declaration should be moved from «etc/events.xml» to «etc/frontend/events.xml» because it relies on the «Display products availability in stock on STOREFRONT» config option

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2352]
See [How does Magento 2 decide whether to display the product's Stock Status?](https://mage2.pro/t/topic/198)

**Comment by vzabaznov** [comment]
To allow us research the issue, please, provide description according to the template.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
