### ISSUE TITLE
Catalog product attribute indexer breaks for multiselect varchar attribute on Magento 2.3.2

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#23534]
Custom multiselect product attributes which have custom source and string as source item value break the indexer

### Preconditions (*)
1. PHP 7.1.17
2. Magento 2.3.0 (upgrade to 2.3.2)

### Steps to reproduce (*)
1. Create a custom attribute which is stored in *_varchar table
```
$eavSetup->addAttribute(
                Product::ENTITY,
                'my_attribute',
                [
                    'group'                      => 'General',
                    'type'                       => 'varchar',
                    'label'                      => 'My attribute',
                    'input'                      => 'multiselect',
                    'frontend'                   => '',
                    'source'                     => 'Vendor\Module\Model\Product\Attribute\MyAttribute',
                    'backend'                    => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
                    'global'                     => ScopedAttributeInterface::SCOPE_GLOBAL,
                    'visible'                    => true,
                    'required'                   => false,
                    'user_defined'               => true,
                    'default'                    => 0,
                    'searchable'                 => false,
                    'filterable'                 => true,
                    'comparable'                 => false,
                    'visible_on_front'           => true,
                    'visible_in_advanced_search' => true,
                    'used_in_product_listing'    => true,
                    'sort_order'                 => 10,
                    'is_used_in_grid'            => false,
                    'is_visible_in_grid'         => false,
                    'is_filterable_in_grid'      => false,
                    'used_for_promo_rules'       => false,
                    'unique'                     => false,
                    'apply_to'                   => 'simple',
                ]
            )
```
2. Source model for attribute: 
```
namespace Vendor\Module\Model\Product\Attribute;
class ProductionDays extends \Magento\Eav\Model\Entity\Attribute\Source\AbstractSource{

        /**
         * Get all options
         *
         * @return array
         */
        public function getAllOptions() {
            $this->_options = [
                //the value option is a string, not "stringified" integer
                [ 'label' => 'Option1', 'value' => 'option1' ],
                [ 'label' => 'Option2', 'value' => 'option2' ],
                [ 'label' => 'Option3', 'value' => 'option3' ],
            ];
            return $this->_options;
        }
}
```

3. After adding attribute through installer open product edit page and select all options for **My attribute** attribute ( or at least two)

4. Upgrade to Magento 2.3.2
 
5. Run `bin/magento indexer:reindex catalog_product_attribute`

### Expected result (*)
1. Indexer should reindex all product attributes 

### Actual result (*)
The indexer script crashes while trying to index custom attribute

1. In pasted text below, instead of 0 should be one of selected values of my_attribute
> Integrity constraint violation: 1062 Duplicate entry '2053-175-1-0-2053' for key 'PRIMARY', query was: INSERT  INTO `catalog_product_index_eav_temp` (`entity_id`,`attribute_id`,`store_id`,`value`,`source_id`) VALUES (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?)

=======================
After digging through the code I found out that the table structure for catalog_product_index_eav_temp has integer as type for **value** column. Since the values to be indexed are strings, they are converted to int and hence the duplicate entry error.

**Comment by sudheers-kensium** [comment]
Attribute type should be "text" .
Run below query to resolve the issue:
UPDATE eav_attribute SET backend_type = 'text' WHERE eav_attribute.attribute_code = 'my_attribute';

**Comment by theodorhanu** [comment]
Hi @sudheers-kensium 
Thanks for your answer.
Even though your answer is correct, this seems to be a bug in magento, at least for me.
If the varchar can be used with multiselect, then the indexer must correctly reindex data in it

**Comment by sudheers-kensium** [comment]
@theodorhanu  If you want to use attribute type is varchar the option values should be int or attribute type is text then you can use option values like option1, option2 etc.

**Comment by engcom-Charlie** [comment]
I am closing this issue because it is not relevant.
Thanks for your report!
