### ISSUE TITLE
Magento Security Scan Incorrectly Failing ?

### ISSUE THREAD

**Issue by rossmc** [magento/magento2#23539]
### Summary (*)
The Magento security scan is failing for sites upgraded to Magento v2.1.18 becuase this version of Magento is missing a newer version of AngularJS.

Please note that this file is only used by the Magento installation wizard.

### Preconditions (*)

1. Magento Open Source Upgraded from 2.1.17 to 2.1.18

### Steps to reproduce (*)

1. Run a [Magento Security Scan](https://docs.magento.com/m2/ce/user_guide/magento/security-scan.html)

### Expected result (*)

1. Expect the Scan to PASS

### Actual result (*)

1. Scan fails due to 
> Outdated JS Libraries - Failed.
> Outdated AngularJS library found, response body contains unexpected ‘AngularJS v1.2.17-build.178+sha.2406084’
![Screenshot 2019-07-02 at 13 08 52](https://user-images.githubusercontent.com/2452991/60512143-1de41f00-9cd4-11e9-83c6-951f86dd99ba.png)
2. This issue seems to be because the _setup/pub/angular/angular.min.js_ file was never updated in Magento v2.1.18.
https://github.com/magento/magento2/blob/2.1.18/setup/pub/angular/angular.min.js#L2

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23539-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23539-2-3-develop.instances.magento-community.engineering/admin](https://i-23539-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @rossmc ! This issue is not reproducible on Magento 2.3-develop

**Comment by rossmc** [comment]
@engcom-Charlie 
That is becuase it's only occurring on Magento v2.1.18, not Magento 2.3-develop.

I thought that was clear from the ticket description?

**Comment by engcom-Charlie** [comment]
@rossmc Magento 2.1.x is not actual anymore so i`m closing this issue .

**Comment by rossmc** [comment]
Really because it was the last upgrade to it last week which broke it :(

What Angular JS version was meant to be changed to in v2.1.18 and we'll create our own patch for it.

**Comment by rossmc** [comment]
If you're unable to help, I think we will create our own patch to use the newer version of the file from 2.2.9

https://github.com/magento/magento2/blob/2.2.9/setup/pub/angular/angular.min.js

This file is only used for the installation wizard as far as I can see so it will be just so it passes the Magento Security Scan

**Comment by andrewescapsolutions** [comment]
If you're running from the /pub/ directory this shouldn't flag as an issue as setup isn't accessible to check the file

The other option is to add

Deny from all

To the setup/.htaccess file as if it's on production you shouldn't need anyone in there anyway :)

**Comment by rossmc** [comment]
Thank you @andrewescapsolutions :)
I hadn't set up the security scan tool and did not think of that.  

Very good point, that must be it.

**Comment by DanielRuf** [comment]
Hi @rossmc,

Is this resolved or why did you reopen it?

**Comment by rossmc** [comment]
I agree that changing the file permissions makes sense for `setup/` directory to get around the security scan.  I'm not sure if it's the best solution?

The Magento docs says this directory [should be have read access](https://devdocs.magento.com/guides/v2.3/config-guide/prod/prod_file-sys-perms.html#make-code-files-and-directories-read-only).

**Comment by andrewescapsolutions** [comment]
Changing to the /pub directory on production sites would be the
best option. I was just giving another alternative
