### ISSUE TITLE
Downloadable product status not updating despite invoice being paid and order complete.

### ISSUE THREAD

**Issue by saeohioalpha** [magento/magento2#23549]
### Preconditions (*)
1. Magento v2.3.1 
2. PHP v7.2

### Steps to reproduce (*)

1. Purchase A Downloadable Product normally

### Expected result (*)
1. The downloadable product should be available for download with status 'Available'.

### Actual result (*)
1. The downloadable product is in pending status and not available for download.
2. The order is marked as complete, and the invoice is marked as paid, but the status did not update to 'Available' and provide the download link.

![Screen Shot 2019-07-02 at 3 42 34 PM](https://user-images.githubusercontent.com/969559/60541808-5d186d00-9ce0-11e9-86f6-a269f020fa1f.png)

![Screen Shot 2019-07-02 at 3 43 40 PM](https://user-images.githubusercontent.com/969559/60541976-c00a0400-9ce0-11e9-8d5f-3b257934a82a.png)

![Screen Shot 2019-07-02 at 3 43 25 PM](https://user-images.githubusercontent.com/969559/60541977-c1d3c780-9ce0-11e9-96e6-41590ecd06c8.png)

**Comment by saeohioalpha** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @saeohioalpha. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @saeohioalpha, here is your [Magento instance](https://i-23549-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23549-2-3-develop.instances.magento-community.engineering/admin](https://i-23549-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by saeohioalpha** [comment]
@magento yes

Confirmed on vanilla. Order is closed, invoice paid. Downloadable still pending.

![Screen Shot 2019-07-02 at 4 00 58 PM](https://user-images.githubusercontent.com/969559/60542802-c7caa800-9ce2-11e9-9163-038336cf4388.png)
![Screen Shot 2019-07-02 at 4 01 15 PM](https://user-images.githubusercontent.com/969559/60542810-c9946b80-9ce2-11e9-9e2b-a0bb53c5cc73.png)
![Screen Shot 2019-07-02 at 4 01 25 PM](https://user-images.githubusercontent.com/969559/60542811-cb5e2f00-9ce2-11e9-8201-4498e5510a39.png)

**Comment by krishprakash** [comment]
Hi @saeohioalpha. Thank you for your report.
l'm closing this as Issue is duplicate to #22545
Once it will fixed it's available in next release.
