### ISSUE TITLE
Magento 2.3 Error: "Invalid Form Key. Please refresh the page." When create new customer account frontend

### ISSUE THREAD

**Issue by Shaggy003** [magento/magento2#23551]
Preconditions
2.3.1
PHP 7 / windows
Steps to reproduce
Go to Sign in
Fill data
Click Button to Create An Account
Expected Result
Account created, email is sent to verify an account? or account must be created
Actual result
![image](https://user-images.githubusercontent.com/51018149/60572119-8691d100-9d92-11e9-967c-f5c2f46fe040.png)

Page refreshes. and shows Invalid Form Key. Please refresh the page. error every time I refresh

**Comment by engcom-Charlie** [comment]
Hello @Shaggy003 ! I can`t reproduce this issue due your steps.
Magento 2 is not supported by Windows OS (please refer here: https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html). Also you are using custom theme. The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
Try to clear the cache from var/cache directory, then clear browser cache (especially clear or delete cookies) . Maybe it will help you.
