### ISSUE TITLE
Magento 2.3 backend: Stores > Settings > Configuration pages issue

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#23558]
Everything Configuration pages display error when use browsers chrome, firefox etc...

### Preconditions (*)

1. Magento 2.3, 2.3.1, 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Open Magento 2 backend and then tab Stores > Settings > Configuration pages
2. Open browser (console)

### Expected result (*)

1. Open Magento 2 backend and then tab Stores > Settings > Configuration pages
2. Open browser (console) and you cannot see error notfications

### Actual result (*)

1. When open Magento 2 backend and then tab Stores > Settings > Configuration pages, you can see error notification when open browser (console)
![error](https://user-images.githubusercontent.com/26794034/60590660-36703a00-9da5-11e9-8875-925c6ff41d34.JPG)

Click on the top right text: **require.min.js:13**
https://********/pub/static/version ******/adminhtml/Magento/backend/en_US/requirejs/require.min.js

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23558-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23558-2-3-develop.instances.magento-community.engineering/admin](https://i-23558-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @Userr017. Thank you for your report.
I'm not able to reproduce the issue as described, seems like this related to your custom modules.
Feel free to reopen it in case you can confirm that its reproducible on Vanilla Magento instance.
