### ISSUE TITLE
Configurable product creation issue in admin 

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#2355]
When  I’m trying to create configurable product from admin its creating virtual products instead of simple products.
![configissue](https://cloud.githubusercontent.com/assets/7636894/11140312/28de8ec2-89ff-11e5-90b9-ee40402da003.png)

**Comment by sivajik34** [comment]
I think this is not an issue.when I’m trying to create configurable product with out giving weight, its creating virtual items.if I’m giving weight, its creating simple items.

**Comment by daim2k5** [comment]
@sivajik34 so we can close the issue?
