### ISSUE TITLE
REST API Swagger Documentation uses /all/ and confuses people with errors

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#23559]
### Preconditions (*)

1. Customer is created from Storefront
2. Product is created
3. Cart is active and contains product

### Steps to reproduce (*)

1. Get Customer's token using Swagger. After this message appears
`"The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later."` use this snippet to get customer token then copy and paste token to the Swagger **api_key** field.
```shell
### Set your endpoint name, customer's email and password, example: endpoint="http://gql-ce.io/rest"
endpoint="REPLACE"

customer_token=$(curl -X POST "${endpoint}/V1/integration/customer/token" \
 -H "Content-Type: application/json" \
 -d '{"username":"REPLACE","password":"REPLACE"}') && echo $customer_token $ && customer_token=$(echo $customer_token | tr -d '"')
```
2. Get Customer's cart or use any other request that uses `.../mine/...` and `.../all/...`

### Expected result (*)

1. Get token, Cart information without any hassle

### Actual result (*)

1. User has to copy requests and remove `all` part from URL. 
Errors like:
`"message":"The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later."`,
`"message": "Current customer does not have an active cart."`,
```json
{
  "message": "No such entity with %fieldName = %fieldValue",
  "parameters": {
    "fieldName": "customerId",
    "fieldValue": 1
  }
}
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17941`, `MC-17942` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23559-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23559-2-3-develop.instances.magento-community.engineering/admin](https://i-23559-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by portchris** [comment]
Not a solution but, a temp fix to suppress error until this is fixed:
```xml

    <type name="Magento\Quote\Model\Webapi\ParamOverriderCartId">
        <plugin name="checkout-suppress-customer-cart-notification" type="MyVendor\MyModule\Plugin\Webapi\ParamOverriderCartId" sortOrder="50" />
    </type>
```

```php
<?php

namespace MyVendor\MyModule\Plugin\Webapi;

use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Quote\Model\Webapi\ParamOverriderCartId as Original;

class ParamOverriderCartId
{
    function aroundGetOverriddenValue(Original $subject, callable $proceed, ...$args): ?int
    {
        $r = null;
        try {
            $r = (int) $proceed(...$args);
        } catch (NoSuchEntityException $e) {
            $r = null;
        }
        return $r;
    }
}

```

**Comment by gabrieldagama** [comment]
Hi @TomashKhamlai 

Can you provide which endpoints have the `/all/`, couldn't understand properly the issue here.

Thanks.

**Comment by gabrieldagama** [comment]
Hi, @TomashKhamlai I will be closing this now, but if you have more details, please feel free to reopen it.
