### ISSUE TITLE
Magento 2.3 Error: "Invalid Form Key. Please refresh the page." When create new customer account frontend

### ISSUE THREAD

**Issue by Shaggy003** [magento/magento2#23550]
hey there,
![image](https://user-images.githubusercontent.com/51018149/60571379-264e5f80-9d91-11e9-82cc-25a98f1fbdb4.png)

I got this error whenever I tried to create a new customer account in frontend please give me a solution

Preconditions
2.3.1
PHP 7 / windows
Steps to reproduce
Go to Sign in
Fill data
Click Button to Create An Account
Expected Result
Account created, email is sent to verify an account? or account must be created
Actual result
Page refreshes. and shows Invalid Form Key. Please refresh the page. error every time I refresh

**Comment by engcom-Charlie** [comment]
Hello @Shaggy003 ! It is impossible to reproduce this issue . Feel free to reopen it in case you can provide 
some steps to reproduce it
