### ISSUE TITLE
authorize.net payment get "Credit card number is required" error message when creating invoice in Magento 2.3

### ISSUE THREAD

**Issue by rohankatkar** [magento/magento2#23555]
### Preconditions (*)

1. Install Magento 2.3 CE
2. PHP 7.1.27

### Steps to reproduce (*)

1. Added a product into the shopping cart.
2. Choose authorize.net payment method in the checkout page.
3. Input credit card number expired date and CCV.
4. Place order.
5. Create invoice at the backend.

### Expected result (*)

1.  The invoice should be created.

### Actual result (*)

![Screenshot from 2019-07-03 15:56:53](https://user-images.githubusercontent.com/5929761/60584572-3ffca080-9dab-11e9-9e3a-958d5026c654.png)

it is giving the error when creating the invoice

**Comment by rohankatkar** [comment]
Is this related to the change of MD5 to SHA-512 in Magento 2.3. Because the Magento stopped the support for MD5 on 28 June, 2019

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23555-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23555-2-3-develop.instances.magento-community.engineering/admin](https://i-23555-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rohankatkar** [comment]
Hi @engcom-Charlie , are you looking into it?

**Comment by engcom-Charlie** [comment]
Hello @rohankatkar ! yes

**Comment by engcom-Charlie** [comment]
Hello @rohankatkar ! I`m not able to reproduce this issue on Vanilla Magento 2.3-develop

![Screenshot from 2019-07-03 15-28-49](https://user-images.githubusercontent.com/51680850/60591807-e646a700-9da7-11e9-8f7d-d3de1895275d.png)

**Comment by rohankatkar** [comment]
the above order is created through Authorized.net Direct Post using Credit card?
Have you used the signature key as per new rule?

**Comment by engcom-Charlie** [comment]
@rohankatkar you can login here (https://i-23555-2-3-develop.instances.magento-community.engineering/admin) and check credentials which i used
