### ISSUE TITLE
Can't extend admin_login.xml / Change admin logo

### ISSUE THREAD

**Issue by verdde** [magento/magento2#23568]
### Summary (*)
Can't extend admin_login.xml, in order to change the admin logo. The version on which i've tested is 2.3.1 and 2.3.2. 

### Examples (*)
Follow exactly the example provided in the dev docs:
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/admin_theme_create.html

Admin theme is applied but admin_login.xml does not apply.

### Proposed solution
Haven't found a solution yet.

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23568-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23568-2-3-develop.instances.magento-community.engineering/admin](https://i-23568-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hi @verdde thank you for your report, I'm not able to reproduce issue on clean 2.3-develop.
If you'd like to update issue, please reopen it.
![1](https://user-images.githubusercontent.com/51680850/60708404-aeaa3d00-9f16-11e9-97fa-33c077e2d6a9.png)
![2](https://user-images.githubusercontent.com/51680850/60708405-aeaa3d00-9f16-11e9-83a7-1de154bad677.png)
