### ISSUE TITLE
Admin Dashboard Charts not working

### ISSUE THREAD

**Issue by vDeggial** [magento/magento2#23562]
### Preconditions (*)

Magento CE 2.2.9

### Steps to reproduce (*)

After updating Magento from 2.2.8 (where Charts in Dashboard were working fine) to 2.2.9 the Charts in Admin Dashboard stopped showing.

### Expected result (*)

Charts in Admin Dashboard show up as they were in previous versions of Magento

### Actual result (*)

Chart doesn't show in Admin Dashboard and exception.log shows
`[2019-07-03 18:04:48] main.CRITICAL: Invalid header line detected {"exception":"[object] (Zend_Http_Exception(code: 0): Invalid header line detected at /home/jri/public_html/vendor/magento/zendframework1/library/Zend/Http/Response.php:572)"} []`

**Comment by vDeggial** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shinoamakusa. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shinoamakusa, here is your [Magento instance](https://i-23562-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23562-2-2-develop.instances.magento-community.engineering/admin](https://i-23562-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vDeggial** [comment]
Vanilla instance will not work as it has no data to show :(

**Comment by hostep** [comment]
I've noticed the same problem on a Magento1 shop a couple of months ago on my local machine which uses HTTP/2 on my webserver. There is some bug in parsing of HTTP headers in Magento when you use HTTP/2. If you use HTTP/1.1 it will work fine.

I could fix it like this (Magento1 patch), but haven't tested this very much, so not sure if this fix won't cause new issues:
```diff
--- lib/Zend/Http/Response.php	2019-03-20 22:54:02.000000000 +0100
+++ lib/Zend/Http/Response.php	2019-04-25 15:23:48.000000000 +0200
@@ -182,7 +182,7 @@
         $this->body = $body;
 
         // Set the HTTP version
-        if (! preg_match('|^\d\.\d$|', $version)) {
+        if (! preg_match('|^\d(?:\.\d)?$|', $version)) {
             #require_once 'Zend/Http/Exception.php';
             throw new Zend_Http_Exception("Invalid HTTP response version: $version");
         }
@@ -514,7 +514,7 @@
         $last_header = null;
 
         foreach($lines as $index => $line) {
-            if ($index === 0 && preg_match('#^HTTP/\d+(?:\.\d+) [1-5]\d+#', $line)) {
+            if ($index === 0 && preg_match('#^HTTP/\d+(?:\.\d+)? [1-5]\d+#', $line)) {
                 // Status line; ignore
                 continue;
             }
```

It looks like the same class is being used in Magento 2 and the same problem still exists over there: https://github.com/magento/zf1/blob/1.14.1/library/Zend/Http/Response.php#L185 & https://github.com/magento/zf1/blob/1.14.1/library/Zend/Http/Response.php#L517

**Comment by vDeggial** [comment]
But charts worked just short time ago with 2.2.8, after upgrade 2.2.9 it broke down. A bit weird ...

**Comment by scoops87** [comment]
shinoamakusa are you using litespeed cache ?

**Comment by vDeggial** [comment]
No, our vps server is regular apache 2.4

**Comment by hostep** [comment]
> But charts worked just short time ago with 2.2.8, after upgrade 2.2.9 it broke down. A bit weird ...

They've changed the service they used for generating charts, because Google ended (or was going to end) their service, and now Magento uses a different service for rendering charts, see the [release notes](https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.9CE.html):
> **Google chart API updated to the Image-Charts.** Magento now uses the Image-Charts free service to render static charts in Admin dashboards. Earlier deployments used Google Image Charts, which was deprecated in 2012 and turned off on [March 18, 2019](https://developers.google.com/chart/image/docs/making_charts).

**Comment by vDeggial** [comment]
I know that but isn't it supposed to work seamlessly out of the box?

**Comment by hostep** [comment]
Yes, but they forgot to test when using a webserver running HTTP/2 I suppose ...

**Comment by vDeggial** [comment]
well i have http2 set on cloudflare but not on server itself ...

**Comment by engcom-Alfa** [comment]
I can't reproduce this issue. I close it, but you can re-open this issue with more details and steps to reproduce.
