### ISSUE TITLE
Product Status Filter doesn't always work

### ISSUE THREAD

**Issue by vDeggial** [magento/magento2#23563]
### Preconditions (*)

Magento CE 2.2.9
Product attributes and attribute sets (which do not include all custom attributes on each one)

### Steps to reproduce (*)

After updating Magento from 2.2.8 to 2.2.9 (it seems) there is a strange issue with Product Grid and applying the Status filter (enabled/disabled). It doesn't always work as it should. 

### Expected result (*)

When Status filter is set to Enabled, it shows only Enabled products

### Actual result (*)

Grid shows disabled products along with enabled ones
![image](https://user-images.githubusercontent.com/9992759/60633320-f1f19800-9dbe-11e9-98c8-9e6b92ff8289.png)
Some products, I got to show with correct filters by changing some custom attributes on them and they worked "fine", but a lot of the products we have disabled still show up with enabled filter on. Not too sure if it is quite reproducible on Vanilla Magento. 

Extensions are not really at fault as they are the same as we had on 2.2.8 and none of them alter the Product grid behavior in any way

**Comment by engcom-Bravo** [comment]
Hello @shinoamakusa. Thanks for applying. We are closing this issue as a duplicate of #23435.

**Comment by vDeggial** [comment]
Then I patiently await the resolution :)
