### ISSUE TITLE
Main Navigation Codezone Megamenu structure not displaying but loading

### ISSUE THREAD

**Issue by g2genious** [magento/magento2#23565]
Main Navigation Code zone Mega menu structure not displaying but loading

Hi Im very new to Magneto I m using Version 2.3 . Ivave a strange Problem. I ve installed Code Zone Fastest Theme. When I trying to edit menu via Code zone->Manage mega menu , Mega menu section is loading nothing is displaying 

![Untitled](https://user-images.githubusercontent.com/52526612/60650339-9af0cf00-9e61-11e9-9ebd-19ba164be9b4.png)

**Comment by engcom-Delta** [comment]
Hi @g2genious , thank you for your report . Your issue is connected with third-party extension. Please, contact with support of your extension to get solution. If you'd like to update issue, please reopen it.
