### ISSUE TITLE
PHPDoc block class declaration is wrong in the template app/code/Magento/Catalog/view/frontend/templates/product/view/attribute.phtml

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2357]
https://github.com/magento/magento2/blob/2335247d4ae2dc1e0728ee73022b0a244ccd7f4c/app/code/Magento/Catalog/view/frontend/templates/product/view/attribute.phtml#L12

It should be `\Magento\Catalog\Block\Product\View\Description`.

**Comment by vkholoshenko** [comment]
Thanks for reporting! Internal ticket: MAGETWO-47665

**Comment by mslabko** [comment]
Issue has been fixed. Thank you for reporting!
