### ISSUE TITLE
Created date mismatch with calendar icon

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#23575]
Created date mismatch with calendar icon

### Preconditions (*)
magento 2.3
magento 2.2

### Steps to reproduce (*)
1) Admin -> Marketing -> User Contents -> Reviews
2) Select created date 

### Expected result (*)
Date should not be mismatch with calendar icon

### Actual result (*)
![created date issue](https://user-images.githubusercontent.com/49804008/60702778-7f4afe80-9f1d-11e9-897b-85a4cbb6fa28.jpg)

### Additional Information (*)
Issue is in below 1366 resolution desktop view

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23575-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23575-2-3-develop.instances.magento-community.engineering/admin](https://i-23575-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23575-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23575-2-2-develop.instances.magento-community.engineering/admin](https://i-23575-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17949`, `MC-17950` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment]
Fixed by https://github.com/magento/magento2/pull/23699, closing.
