### ISSUE TITLE
Add support for new lines to the Wysiwyg widget plugin 

### ISSUE THREAD

**Issue by simonlandry0** [magento/magento2#23571]
### Description (*)

The Magento Wysiwyg plugin for tinymce4 does not detect a widget when it has a new line in the data because of a regex. Changing this regex would add support for textarea inputs in widgets.

https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/adminhtml/wysiwyg/tiny_mce/plugins/magentowidget/editor_plugin.js#L126

This regex should be changed:
(old) 
`return content.gsub(/\{\{widget(.*?)\}\}/i, function (match) {`
(suggested) 
`return content.gsub(/\{\{widget([^}]*?)\}\}/i, function (match) {`

### Expected behavior (*)

Wysiwyg widgets should not break with newline characters in the text data.

### Benefits

Would allow for widgets with data that have newlines inside them. Currently the base installation of Magento does not have any widget inputs that can have newlines in them, but would add room for developers to create their own textarea/wysiwyg inputs.

**Comment by shikhamis11** [comment]
hello @simonlandry0 
Thanks for reporting this issue.
This will process faster if you will create it on [Magento  Feature request ](https://github.com/magento/community-features). so closing from here .
