### ISSUE TITLE
Type Error occurred when creating object

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#23572]
### Summary (*)
frontend to displaying any product .. i get this error

[2019-07-05 03:01:42] main.CRITICAL: Type Error occurred when creating object: Magento\ConfigurableProduct\Model\Product\Type\Configurable\Variations\Prices {"exception":"[object] (Magento\\Framework\\Exception\\RuntimeException(code: 0): Type Error occurred when creating object: Magento\\ConfigurableProduct\\Model\\Product\\Type\\Configurable\\Variations\\Prices at /mnt/data/home/251599.cloudwaysapps.com/wwdgefaryy/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:124)"} []

### Examples (*)
jomlah.com

### Proposed solution
looking forward to

**Comment by salehawal** [comment]
Detailed Error Message ...

1 exception(s):
Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Magento\ConfigurableProduct\Model\Product\Type\Configurable\Variations\Prices

Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Magento\ConfigurableProduct\Model\Product\Type\Configurable\Variations\Prices
<pre>#1 Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\Configur...') called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#2 Magento\Framework\ObjectManager\ObjectManager->get('Magento\Configur...') called at [vendor/magento/module-configurable-product/Block/Product/View/Type/Configurable.php:122]
#3 Magento\ConfigurableProduct\Block\Product\View\Type\Configurable->__construct(&Magento\Catalog\Block\Product\Context#0000000033fdb07400000000354c9e7b#, &Magento\Framework\Stdlib\ArrayUtils#0000000033fdb72300000000354c9e7b#, &Magento\Framework\Json\Encoder#0000000033fdb73800000000354c9e7b#, &Magento\ConfigurableProduct\Helper\Data#0000000033fdb02100000000354c9e7b#, &Magento\Catalog\Helper\Product\Interceptor#0000000033fdb6e500000000354c9e7b#, &Magento\Customer\Helper\Session\CurrentCustomer#0000000033fdb02300000000354c9e7b#, &Magento\Directory\Model\PriceCurrency#0000000033fdb6ff00000000354c9e7b#, &Magento\ConfigurableProduct\Model\ConfigurableAttributeData#0000000033fdb02200000000354c9e7b#, array()) called at [vendor/magento/module-swatches/Block/Product/Renderer/Configurable.php:139]
#4 Magento\Swatches\Block\Product\Renderer\Configurable->__construct(&Magento\Catalog\Block\Product\Context#0000000033fdb07400000000354c9e7b#, &Magento\Framework\Stdlib\ArrayUtils#0000000033fdb72300000000354c9e7b#, &Magento\Framework\Json\Encoder#0000000033fdb73800000000354c9e7b#, &Magento\ConfigurableProduct\Helper\Data#0000000033fdb02100000000354c9e7b#, &Magento\Catalog\Helper\Product\Interceptor#0000000033fdb6e500000000354c9e7b#, &Magento\Customer\Helper\Session\CurrentCustomer#0000000033fdb02300000000354c9e7b#, &Magento\Directory\Model\PriceCurrency#0000000033fdb6ff00000000354c9e7b#, &Magento\ConfigurableProduct\Model\ConfigurableAttributeData#0000000033fdb02200000000354c9e7b#, &Magento\Swatches\Helper\Data#0000000033fdb03c00000000354c9e7b#, &Magento\Swatches\Helper\Media#0000000033fdb3d500000000354c9e7b#, array(), NULL) called at [vendor/magento/module-swatches/Block/Product/Renderer/Listing/Configurable.php:95]
#5 Magento\Swatches\Block\Product\Renderer\Listing\Configurable->__construct(&Magento\Catalog\Block\Product\Context#0000000033fdb07400000000354c9e7b#, &Magento\Framework\Stdlib\ArrayUtils#0000000033fdb72300000000354c9e7b#, &Magento\Framework\Json\Encoder#0000000033fdb73800000000354c9e7b#, &Magento\ConfigurableProduct\Helper\Data#0000000033fdb02100000000354c9e7b#, &Magento\Catalog\Helper\Product\Interceptor#0000000033fdb6e500000000354c9e7b#, &Magento\Customer\Helper\Session\CurrentCustomer#0000000033fdb02300000000354c9e7b#, &Magento\Directory\Model\PriceCurrency#0000000033fdb6ff00000000354c9e7b#, &Magento\ConfigurableProduct\Model\ConfigurableAttributeData#0000000033fdb02200000000354c9e7b#, &Magento\Swatches\Helper\Data#0000000033fdb03c00000000354c9e7b#, &Magento\Swatches\Helper\Media#0000000033fdb3d500000000354c9e7b#, array(), NULL, NULL, NULL, NULL) called at [generated/code/Magento/Swatches/Block/Product/Renderer/Listing/Configurable/Interceptor.php:14]
#6 Magento\Swatches\Block\Product\Renderer\Listing\Configurable\Interceptor->__construct(&Magento\Catalog\Block\Product\Context#0000000033fdb07400000000354c9e7b#, &Magento\Framework\Stdlib\ArrayUtils#0000000033fdb72300000000354c9e7b#, &Magento\Framework\Json\Encoder#0000000033fdb73800000000354c9e7b#, &Magento\ConfigurableProduct\Helper\Data#0000000033fdb02100000000354c9e7b#, &Magento\Catalog\Helper\Product\Interceptor#0000000033fdb6e500000000354c9e7b#, &Magento\Customer\Helper\Session\CurrentCustomer#0000000033fdb02300000000354c9e7b#, &Magento\Directory\Model\PriceCurrency#0000000033fdb6ff00000000354c9e7b#, &Magento\ConfigurableProduct\Model\ConfigurableAttributeData#0000000033fdb02200000000354c9e7b#, &Magento\Swatches\Helper\Data#0000000033fdb03c00000000354c9e7b#, &Magento\Swatches\Helper\Media#0000000033fdb3d500000000354c9e7b#, array(), NULL, NULL, NULL, NULL) called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116]
#7 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Swatches...', array(&Magento\Catalog\Block\Product\Context#0000000033fdb07400000000354c9e7b#, &Magento\Framework\Stdlib\ArrayUtils#0000000033fdb72300000000354c9e7b#, &Magento\Framework\Json\Encoder#0000000033fdb73800000000354c9e7b#, &Magento\ConfigurableProduct\Helper\Data#0000000033fdb02100000000354c9e7b#, &Magento\Catalog\Helper\Product\Interceptor#0000000033fdb6e500000000354c9e7b#, &Magento\Customer\Helper\Session\CurrentCustomer#0000000033fdb02300000000354c9e7b#, &Magento\Directory\Model\PriceCurrency#0000000033fdb6ff00000000354c9e7b#, &Magento\ConfigurableProduct\Model\ConfigurableAttributeData#0000000033fdb02200000000354c9e7b#, &Magento\Swatches\Helper\Data#0000000033fdb03c00000000354c9e7b#, &Magento\Swatches\Helper\Media#0000000033fdb3d500000000354c9e7b#, array(), NULL, NULL, NULL, NULL)) called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#8 Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\Swatches...', array('data' => array())) called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#9 Magento\Framework\ObjectManager\ObjectManager->create('Magento\Swatches...', array('data' => array())) called at [vendor/magento/framework/View/Element/BlockFactory.php:46]
#10 Magento\Framework\View\Element\BlockFactory->createBlock('Magento\Swatches...', array('data' => array())) called at [vendor/magento/framework/View/Layout/Generator/Block.php:268]
#11 Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\Swatches...', array('data' => array())) called at [vendor/magento/framework/View/Layout/Generator/Block.php:248]
#12 Magento\Framework\View\Layout\Generator\Block->createBlock('Magento\Swatches...', 'category.product...', array('data' => array())) called at [vendor/magento/framework/View/Layout/Generator/Block.php:226]
#13 Magento\Framework\View\Layout\Generator\Block->generateBlock(&Magento\Framework\View\Layout\ScheduledStructure#0000000033fdb1b500000000354c9e7b#, &Magento\Framework\View\Layout\Data\Structure#0000000033fdb42900000000354c9e7b#, 'category.product...') called at [vendor/magento/framework/View/Layout/Generator/Block.php:134]
#14 Magento\Framework\View\Layout\Generator\Block->process(&Magento\Framework\View\Layout\Reader\Context#0000000033fdb14200000000354c9e7b#, &Magento\Framework\View\Layout\Generator\Context#0000000033fdb15c00000000354c9e7b#) called at [vendor/magento/framework/View/Layout/GeneratorPool.php:81]
#15 Magento\Framework\View\Layout\GeneratorPool->process(&Magento\Framework\View\Layout\Reader\Context#0000000033fdb14200000000354c9e7b#, &Magento\Framework\View\Layout\Generator\Context#0000000033fdb15c00000000354c9e7b#) called at [vendor/magento/framework/View/Layout.php:343]
#16 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#17 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#18 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#19 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#20 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Page/Config.php:212]
#21 Magento\Framework\View\Page\Config->build() called at [vendor/magento/framework/View/Page/Config.php:575]
#22 Magento\Framework\View\Page\Config->getElementAttribute('body', 'class') called at [vendor/magento/framework/View/Page/Config.php:533]
#23 Magento\Framework\View\Page\Config->addBodyClass('page-products') called at [vendor/magento/module-catalog/Controller/Category/View.php:215]
#24 Magento\Catalog\Controller\Category\View->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Magento\Catalog\Controller\Category\View\Interceptor->___callParent('execute', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Sm/ShopBy/Plugin/Category/View.php:26]
#27 Sm\ShopBy\Plugin\Category\View->aroundExecute(&Magento\Catalog\Controller\Category\View\Interceptor#0000000033fdb74a00000000354c9e7b#, &Closure#0000000033fdb62800000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('execute', array(), array(array('ajax_layer_navig...'))) called at [generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php:26]
#30 Magento\Catalog\Controller\Category\View\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#31 Magento\Framework\App\Action\Action->dispatch(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#32 Magento\Catalog\Controller\Category\View\Interceptor->___callParent('dispatch', array(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#33 Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#34 Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('dispatch', array(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php:39]
#35 Magento\Catalog\Controller\Category\View\Interceptor->dispatch(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/App/FrontController.php:159]
#36 Magento\Framework\App\FrontController->processRequest(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#, &Magento\Catalog\Controller\Category\View\Interceptor#0000000033fdb74a00000000354c9e7b#) called at [vendor/magento/framework/App/FrontController.php:99]
#37 Magento\Framework\App\FrontController->dispatch(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#38 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#39 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#40 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000033fdb4f600000000354c9e7b#, &Closure#0000000033fdb49a00000000354c9e7b#, &Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#41 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#42 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000033fdb4f600000000354c9e7b#, &Closure#0000000033fdb49a00000000354c9e7b#, &Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#43 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/amasty/module-push-notifications/Plugin/Action.php:85]
#44 Amasty\PushNotifications\Plugin\Action->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000033fdb4f600000000354c9e7b#, &Closure#0000000033fdb49a00000000354c9e7b#, &Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#45 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#46 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#47 Magento\Framework\App\FrontController\Interceptor->dispatch(&Basicphp\Customurl\Magento\Framework\App\Request\Http2#0000000033fdb58200000000354c9e7b#) called at [vendor/magento/framework/App/Http.php:136]
#48 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#49 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#50 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000033fdb56100000000354c9e7b#) called at [index.php:39]
</pre>

**Comment by engcom-Charlie** [comment]
Could you provide more steps how to reproduce it ?

**Comment by salehawal** [comment]
here i also tried to change the theme to Luma and same error
![jomlah com-Sales24HourJomlah comWholesaleMarket](https://user-images.githubusercontent.com/3238761/60721343-ea043600-9f2d-11e9-9ec8-4d8b7698426b.png)

**Comment by salehawal** [comment]
ok problem resolved .. there was a custom module causing this issue, i disable modules until i found it, this custom module was overriding magneot module related to price filter
