### ISSUE TITLE
Custom UI component conditions can't add category

### ISSUE THREAD

**Issue by Nazar65** [magento/magento2#23582]
When i Implements custom UI component conditions can't add category   from category tree js error.Uncaught TypeError: Cannot read property 'updateElement' of undefined

### Preconditions (*)
magento 2.3.1
Create custom module with ui component admin page.

### Steps to reproduce (*)
1- Add conditions element to form.
```
    <fieldset name="conditions_fieldset" sortOrder="20">
        <settings>
            <label translate="true">Conditions</label>
        </settings>
        <container name="conditions_apply_to" sortOrder="10">
            <htmlContent name="html_content">
                <block name="conditions_apply_to" class="Vrndor\Vendor\Block\Adminhtml\Rule\Edit\Tab\Conditions" />
            </htmlContent>
        </container>
    </fieldset>
```
2. Go to admin page and try to select conditions with category tree.
![DeepinScreenshot_select-area_20190705143119](https://user-images.githubusercontent.com/2481206/60720252-de673e00-9f32-11e9-8418-377073319f50.png)

### Expected result (*)
ID added to input form 

### Actual result (*)
js error

**Comment by ghost** [comment]
Hi @Nazar65 ,
how did you solve this problem?
