### ISSUE TITLE
Script error when loading product grid

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2358]
![2015-11-13_10h43_38](https://cloud.githubusercontent.com/assets/13572447/11143414/36725d02-89f5-11e5-94d9-833b69eab191.png)

**Comment by dfediuk** [comment]
Firstly, try to wait.
If there is no success then try to delete the cache and `pub/static` contents and reload the page.

**Comment by guz-anton** [comment]
Hi Sidney,
It's not a `script error`. It's a performance issue of your environment. JS Grid is a complex application. It can require some browser resources on first load. Also there is time delay when script-files load on the page. On first load ("cold run") this time shift is longer than usual. Also if your PC was busy it can limit browser with process time resource. Altogether it can put browser in _"too slow"_ mode. And so you got this error.

Currently it's not a bug. Unless you can provide more details about your local environment.
