### ISSUE TITLE
\Magento\Catalog\Model\ProductRepository does not respect store scope

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#23583]
### Preconditions (*)
1. Create 2 websites (W1, W2) with with 1 store each (Store1, Store2) (W1 - Store1, W2 - Store2).
2. Create product P1 and assign it to W1.

### Steps to reproduce (*)
1. Try to load in code P1 in context of Store2 from Product Repository
```
/** @var ProductRepository $repo */
$repo = ObjectManager::getInstance()->get(ProductRepository::class);
$repo->getById([product_id], false, 2);
```
### Expected result (*)
1. \Magento\Framework\Exception\NoSuchEntityException

### Actual result (*)
1. Product has been  loaded and contains data from default store.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18129` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Tomasz18** [comment]
@magento I am working on it

**Comment by gabrieldagama** [comment]
Closing this one as based on the discussion on https://jira.corp.magento.com/browse/MC-18129. The fix for this would be backward incompatible, as is today it shouldn't affect merchant experience and it will be addressed on new storefront APIs.
