### ISSUE TITLE
Database Media Storage : php bin/magento catalog:images:resize fails when image does not exist locally

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#23594]
### Preconditions (*)
1. magento 2.3-develop
2. Database Storage Mode Enabled

### Steps to reproduce (*)
1. Deploy 2.3-develop
2. Change mode to database media storage mode
3. Clear cache
4. Create product and assign image
5. Save Product
6. Delete pub/media/catalog folder

`www-data@dev:~/dev2$ rm -rf pub/media/catalog/`

7. Verify image exists in database

```
mysql> select filename,directory from media_storage_file_storage;
+----------------------------------+---------------------+
| filename                         | directory           |
+----------------------------------+---------------------+
| preview_image_5d2093b1ab619.jpeg | theme/preview       |
| preview_image_5d2093b1b954f.jpeg | theme/preview       |
| a.jpg                            | catalog/product/a/_ |
+----------------------------------+---------------------+
3 rows in set (0.00 sec)
```
8. run php/magento catalog:image:resize to generate cached images

### Expected result (*)
Cached images generated in database and on file system

### Actual result (*)
```
www-data@dev:~/dev2$ php bin/magento catalog:images:resize
File '/var/www/dev2/pub/media/catalog/product/a/_/a.jpg' does not exist.
```

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#23598 by @gwharton in 2.3-develop branch
Related commit(s):
 - [2f6238232a43c9fb8808f41683d7ab6584ade4b3](https://github.com/magento/magento2/commit/2f6238232a43c9fb8808f41683d7ab6584ade4b3)

The fix will be available with the upcoming 2.3.3 release.
