### ISSUE TITLE
Magento 2 has no ability to hide the SKU from a frontend product page

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2359]
For example, displaying the SKU to the customers would be unnecessary for some Virtual products (software, support, repair, consulting).

**Comment by xitude** [comment]
+1

**Comment by antboiko** [comment]
@dfediuk 
Hi Dmitry, I'm sorry for delay with answering on your inquiry. 

I've created internal ticket MAGETWO-49911 to cover this feature and placed it into our backlog.

Best,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-2-has-no-ability-to-hide-the-SKU-from-a-frontend-product/idi-p/46499).
