### ISSUE TITLE
POST product with REST API doesn't save manufacturer attribute

### ISSUE THREAD

**Issue by scne** [magento/magento2#23604]
### Preconditions
1. magento 2.3.1 CE
2. PHP 7.1.29

### Steps to reproduce
I'm able to save a product with a POST request to my REST API endpoint. Now I would like to save **manufacture** attribute,too. 
To reproduce this issue send a POST request to insert a product (or a PUT request to update).  I prepare this json structure.

```
{
    	"product": {
    		"sku": "code",
    		"name": "name",
    		"price": 5,
    		"attribute_set_id": 4,
    		"status": 1,
    		"visibility": 1,
    		"extension_attributes": {
    			"stock_item": {
    				"qty": 0,
    				"is_in_stock": false,
    				"is_qty_decimal": false,
    				"min_qty": "0",
    				"qty_increments": "0"
    			}
    		},
    		"custom_attributes": [{
    			"attribute_code": "barcode",
    			"value": "############"
    		}, {
    			"attribute_code": "family",
    			"value": "product family"
    		}, {
    			"attribute_code": "description",
    			"value": "product description"
    		}, {
    			"attribute_code": "category_ids",
    			"value": ["1", "2", "41", "53", "87"]
    		}, {
    			"attribute_code": "manufacturer",
    			"value": "213"
    		}]
    	}
    }
```

### Expected result
I'm expecting that all `custom_attributes`  will be saved to related product

### Actual result 
This product is saved on my catalog but without manufacturer value, indeed the response about above request is

   ```
 {
    	"id": 2059,
    	"sku": "code",
    	"name": "name",
    	"attribute_set_id": 4,
    	"status": 1,
    	"visibility": 1,
    	"type_id": "simple",
    	"created_at": "2019-06-17 08:02:23",
    	"updated_at": "2019-06-17 08:02:23",
    	"extension_attributes": {
    		"website_ids": [1],
    		"category_links": [{
    			"position": 0,
    			"category_id": "1"
    		}, {
    			"position": 0,
    			"category_id": "2"
    		}, {
    			"position": 0,
    			"category_id": "41"
    		}, {
    			"position": 0,
    			"category_id": "53"
    		}, {
    			"position": 0,
    			"category_id": "87"
    		}]
    	},
    	"product_links": [],
    	"options": [],
    	"media_gallery_entries": [],
    	"tier_prices": [],
    	"custom_attributes": [{
    		"attribute_code": "description",
    		"value": "description"
    	}, {
    		"attribute_code": "url_key",
    		"value": "name-of-product"
    	}, {
    		"attribute_code": "options_container",
    		"value": "container2"
    	}, {
    		"attribute_code": "barcode",
    		"value": "###########"
    	}, {
    		"attribute_code": "family",
    		"value": "product family"
    	}, {
    		"attribute_code": "required_options",
    		"value": "0"
    	}, {
    		"attribute_code": "has_options",
    		"value": "0"
    	}, {
    		"attribute_code": "category_ids",
    		"value": ["1", "2", "41", "53", "87"]
    	}]
    }
```

**Comment by chohanbhagchand** [comment]
@scne can you please use attribute code **country_of_manufacture**  in place of  **manufacture** I am able to save attribute value

**Comment by chohanbhagchand** [comment]
![image](https://user-images.githubusercontent.com/43440703/60805885-183c7c80-a19f-11e9-8089-faf9cadbb12c.png)

**Comment by chohanbhagchand** [comment]
Here is the response array which I get 
===========================Response =======================
![image](https://user-images.githubusercontent.com/43440703/60805921-36a27800-a19f-11e9-8ef7-fdc1146f4b48.png)


Please let me know if the issue is still persists

**Comment by scne** [comment]
@chohanbhagchand thanks for your replay but I have to set **manufacture** (drop-down value on admin backend) with my REST request. All other custom attribute are ok i.e. _categories_ or _description_ or custom attribute _family_

**Comment by chohanbhagchand** [comment]
@scne can you please send me your admin URL where manufacture attribute already set to any particular product. so it is easy to debug.

**Comment by scne** [comment]
@chohanbhagchand do you need only admin URL of my magento or do you want admin and password, too? How can I send you securely?

**Comment by chohanbhagchand** [comment]
@scne Please send me your developing instance where the issue occurred. with admin URL and credentials.

**Comment by scne** [comment]
@chohanbhagchand give me your ip address because my instance is in maintenance mode. Admin url is [this](http://shop.dicanio.it) and credentials are developer:9dPuV5PC.

**Comment by chohanbhagchand** [comment]
@scne I also unable to share my IP with you can you pls inbox me your cred in the mail my mail id is chohan.bhagchand@gmail.com

**Comment by chohanbhagchand** [comment]
@scne Please put file which is emailed to you in the root folder of your server.

**Comment by chohanbhagchand** [comment]
@scne here is the product which is I save in your backend
![image](https://user-images.githubusercontent.com/43440703/60873776-8727dd00-a254-11e9-86a8-0f2ae6a8fad8.png)

**Comment by chohanbhagchand** [comment]
@scne now you are able to save **manufacture** attribute and also please note in the problem statement you will give manufacture id i.e. 213 

{
    			"attribute_code": "manufacturer",
    			"value": "213"
    		}]


and in your backend, no **manufacture** value is associated with 213


Kindly let me know if your still facing problem to save :)

**Comment by LucianMihalache** [comment]
Your problem is that you are saving(sending to magento) the wrong value of manufacturer.

If you want to update the value of an attribute, you must send an existing value.
Basically, you must do a request to get the option_ids (value) of the manufacturer attribute.
Map them with your wanted value.
Send the correct (the remote) value along with the product.

**Comment by chohanbhagchand** [comment]
@scne issue is resolved and is still if you are in problem then let me know.
