### ISSUE TITLE
Default value for report filters might result in errors

### ISSUE THREAD

**Issue by rogyar** [magento/magento2#23606]
### Description
For reports like Reports -> Products -> Ordered and other reports, the default date range is set to past 18 years (from the year 2001 till today). If you have large orders history, this default range might result in an attempt to get millions of records with no luck (because of the timeout).

### Preconditions (*)
1. Webshop with ~100 orders per day
2. The orders history starts from, let's say, 2013.

### Steps to reproduce (*)
1. Go to Reports -> Products -> Ordered
2. Click on the "Refresh" button without setting values for "From -> To" filter.

### Expected result (*)
1. A limited number of records is shown

### Actual result (*)
1. Gateway timeout (best case)
2. Database locks, high server load, denial of service (worst case)

My recommendation is setting the default date range for the past month instead of the past 18 years.

**Comment by magento-engcom-team** [comment]
@kalpmehta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @kalpmehta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17968` were created

**Issue Available**: @kalpmehta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your report. 
The issue has been fixed in magento/magento2#23607 by @rogyar in 2.3-develop branch
Related commit(s):
 - [9aa4744ee6eafbd7ecc722b8c501493cd594b28c](https://github.com/magento/magento2/commit/9aa4744ee6eafbd7ecc722b8c501493cd594b28c)

The fix will be available with the upcoming 2.3.3 release.
