### ISSUE TITLE
ElasticSearch module inconsistent DI

### ISSUE THREAD

**Issue by romainruaud** [magento/magento2#23615]
### Summary (*)

The Magento_Elasticsearch module has too authoritative DI and is happening functional & technical modifications even when Elasticsearch is not used as search engine.

### Examples (*)

See here : 

https://github.com/magento/magento2/blame/2.3-develop/app/code/Magento/Elasticsearch/etc/di.xml#L25

In any cases, when having the Magento_Elasticsearch module, the `context` injected into the `Magento\Catalog\Model\Layer\Category` is a `Magento\Elasticsearch\Model\Layer\Category\Context`.

If you follow the path, this lead to the fact that an `elasticsearchLayerCategoryItemCollectionProvider` is always used as collection provider by the Layer.

And so on.

Later on, you'll see this : 

```
    <virtualType name="elasticsearchLayerSearchItemCollectionProvider" type="Magento\Elasticsearch\Model\Layer\Search\ItemCollectionProvider">
        <arguments>
            <argument name="factories" xsi:type="array">
                <item name="mysql" xsi:type="object">Magento\CatalogSearch\Model\ResourceModel\Fulltext\SearchCollectionFactory</item>
                <item name="elasticsearch" xsi:type="object">elasticsearchFulltextSearchCollectionFactory</item>
                <item name="elasticsearch5" xsi:type="object">elasticsearchFulltextSearchCollectionFactory</item>
            </argument>
        </arguments>
    </virtualType>
```

Which is especially something I cannot agree with.

Conceptually, this means that `Magento_Elasticsearch` could be seen as **the default search engine implementation**, and that subsequent factories have to be added here if you are using other search engines. We can see that you added a factory for `mysql` which is a complete non-sense for me.

I can inject easily my own factories here if needed, yes that's true, but regarding dependencies management, logical concerns and extensibility by third-party extensions, this part should not remain like this.

### Proposed solution

Remove the arbitrary injection of `elasticsearchLayerSearchItemCollectionProvider` or at least condition it to the fact that Elasticsearch is the currently selected search engine.

Do not manage other engines collection inside the `Magento_ElasticSearch` module.

Regards

**Comment by engcom-Charlie** [comment]
Hello @romainruaud 

We are closing this issue because fix for this problem was merged:
https://github.com/elastic/app-search-magento/pull/64#issue-327772200

Thanks for your report!

**Comment by romainruaud** [comment]
@engcom-Charlie why are you referencing an issue from an external repository to say it has been fixed ?

**Comment by engcom-Charlie** [comment]
@romainruaud 
oh, sorry. 
I missed the fact that this is not magento2 repository

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22955` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
