### ISSUE TITLE
Magento\Backend\App\AbstractAction::_isAllowed() should use a static binding

### ISSUE THREAD

**Issue by brideo** [magento/magento2#2361]
http://php.net/manual/en/language.oop5.late-static-bindings.php

Rather than this:

    /**
     * @return bool
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed(self::ADMIN_RESOURCE);
    }

We should have this:

    /**
     * @return bool
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed(static::ADMIN_RESOURCE);
    }

By using a static binding, we don't have to completely re-write the `_isAllowed` method in our controller action, instead we can simply define our `ADMIN_RESOURCE` constant, we then can let the `AbstractAction` handle our logic. 

This would be a completely backwards compatible change.

**Comment by ashsmith** [comment]
:+1:

**Comment by pantaoran** [comment]
I also just stumbled across this. Please implement this.

**Comment by nkarthickannan** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by antonkril** [comment]
We have plans to move Action Resource configuration to XML files.

But agree that `static` might be a good quick improvement

**Comment by brideo** [comment]
I'm happy to submit a pull request if this gets approved.

**Comment by brideo** [comment]
I see the static binding has been added but the controllers weren't updated, I have done so in the following pull request:

https://github.com/magento/magento2/pull/3428

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-Backend-App-AbstractAction-isAllowed-should-use-a-static/idi-p/45352).
