### ISSUE TITLE
Magento 2.8.2 stuck in orders  

### ISSUE THREAD

**Issue by Shopahollik** [magento/magento2#23617]
### Summary (*)

My magento 2 is currently stuck in orders please see link 
https://www.loom.com/share/f7b980d94cde4448a1fa5fdc4ad2a16c?fbclid=IwAR3OEjD1p5k3lJXSWBePka6e4bnIzg6P-SG-J1y0fBknhv0LKmZQdzPCun0

### Examples (*)

 see link problem
https://www.loom.com/share/f7b980d94cde4448a1fa5fdc4ad2a16c?fbclid=IwAR3OEjD1p5k3lJXSWBePka6e4bnIzg6P-SG-J1y0fBknhv0LKmZQdzPCun0

**Comment by engcom-Charlie** [comment]
Hello @Shopahollik ! I`m not able to reproduce it on Vanilla Magento . Feel free to reopen it in case you can provide some steps how to reproduce this issue .
