### ISSUE TITLE
Magento 2.2.6  Cart Price Rules for Bundle Product Items

### ISSUE THREAD

**Issue by mangamuri** [magento/magento2#23610]
### Preconditions (*)

1. Magento 2.2.6
2.

### Steps to reproduce (*)

1. Create  2 simple products
2.Create a Bundle product and add those 2 simple products as options in Bundle product
3. Create a cart price rule  Condition : Items in cart matching  SKU is one of  simpleproduct1, Bundle product and Action as 100% discount
4. When i have added  Bundle product with Simple product 1 , apply coupon gave me 100% discount
5. when i have added Bundle product with simple product 2, apply same coupon gave me 100% discount

### Expected result (*)

1. [Screenshots, logs or description]
2. Coupon should only applied for Bundle Option given in rule , it should not apply for other options in Bundle

### Actual result (*)

1. [Screenshots, logs or description]
2. All Bundle Options are able to apply for coupon

**Comment by krishprakash** [comment]
Hi @mangamuri. 
This is not an issue.
You should add that specific SKU in Action conditions if you want to apply rule just for such SKU (or cart items you specify in action conditions).
![image](https://user-images.githubusercontent.com/46617848/60786264-75bad400-a173-11e9-80d1-b9d1c3551495.png)
You can find "action conditions" just below Actions.
Feel free to reopen it in case you can confirm that it's reproducible on Vanilla Magento instance.
Thanks.

**Comment by mangamuri** [comment]
@magento give me 2.2.6-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mangamuri. Thank you for your request. I'm working on Magento 2.2.6-develop instance for you

**Comment by mangamuri** [comment]
@krishprakash thanks for testing it. Could you please share your bundle product details and conditions screenshots . I have tried action rule as per your screen shot but no luck. Anyways I am requesting instance to reproduce this.

**Comment by krishprakash** [comment]
FYI:-
Bundle product child:
![image](https://user-images.githubusercontent.com/46617848/60786826-810eff00-a175-11e9-9b4f-6c778803791d.png)

Action Condition:
![image](https://user-images.githubusercontent.com/46617848/60787658-29be5e00-a178-11e9-9606-4cc06aa08738.png)

**Comment by mangamuri** [comment]
@krishprakash Thanks.

Here is my screenshots:

Bundle product:

![image](https://user-images.githubusercontent.com/1827538/60788258-e507d800-a121-11e9-8507-6a5b24c98f03.png)

![image](https://user-images.githubusercontent.com/1827538/60788288-f6e97b00-a121-11e9-89f5-c80c3dff4f6b.png)

Sales Rule -> Rule setup

![image](https://user-images.githubusercontent.com/1827538/60788378-2ac4a080-a122-11e9-9b54-047b5fe95302.png)


Sales Rule -> Condition and Action

![image](https://user-images.githubusercontent.com/1827538/60788411-47f96f00-a122-11e9-8c9b-50b4546cb738.png)

StoreFront Behavior: with simple1 product

![image](https://user-images.githubusercontent.com/1827538/60788447-63647a00-a122-11e9-9079-a087fca69f39.png)

with simple2 product

![image](https://user-images.githubusercontent.com/1827538/60788627-c35b2080-a122-11e9-899d-c74150a3c6e3.png)
If I use sku is simple1 in condition and action coupon is not applying so I have tried adding bundle sku using one of or contains also..

**Comment by krishprakash** [comment]
Hi @mangamuri. Thanks for response.
Please review attached screenshot
![image](https://user-images.githubusercontent.com/46617848/60789500-de5a7e80-a17c-11e9-8021-62914daaa520.png)

**Comment by mangamuri** [comment]
@krishprakash 
I have tried that option as well when i use sku is simple1 condition my coupon is not working as expected.

![image](https://user-images.githubusercontent.com/1827538/60790345-e556a200-a126-11e9-8dfd-516356c01cb9.png)


I have tried tweaking both conditions and actions  with various combinations, only working one is for me is the sku is one of simple1,bundle.

**Comment by krishprakash** [comment]
Please verify once in Vanilla Magento instance
![image](https://user-images.githubusercontent.com/46617848/60790616-8a9d6480-a17f-11e9-814f-6d69da0a1a25.png)

**Comment by mangamuri** [comment]
@krishprakash Thanks i assume you have tested this in 2.3.x?

**Comment by mangamuri** [comment]
> develop



> Hi @mangamuri. Thank you for your request. I'm working on Magento 2.2.6-develop instance for you

@magento could you please give me 2.3.x instance as i would like to test that with latest release.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23610-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23610-2-3-develop.instances.magento-community.engineering/admin](https://i-23610-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23610-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23610-2-2-develop.instances.magento-community.engineering/admin](https://i-23610-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Please verify once in above both Vanilla Magento instances and add your feedback 
Thanks.

**Comment by mangamuri** [comment]
@krishprakash i am not able to reproduce this issue in 2.2.9-dev , i think this issue might be fixed in later versions 2.2.6 i guess. Thanks for helping with testing this and appreciate your help.
