### ISSUE TITLE
Saved customer information lost in checkout after changing quantity of item in cart or adding a new product

### ISSUE THREAD

**Issue by marklehm** [magento/magento2#23622]
### Preconditions (*)
1. Magento 2.2.4
2. Magento 2.3.0
3. Magento 2.3.1

PHP 7.2

### Steps to reproduce (*)
The issue was found with and without sample data.
1. Begin as a guest customer and add any product to cart
2. Proceed to checkout and fill out shipping information and proceed to review and payments.
<img width="2054" alt="Screen Shot 2019-07-08 at 10 45 44 AM" src="https://user-images.githubusercontent.com/1315931/60831446-7a30be00-a16e-11e9-8414-18a717b70d7f.png">
3. Go back to cart /checkout/cart.
4. Modify the quantity of the product in the cart to 2 or more.
5. Proceed back to the checkout.
6. Customer shipping information lost.

Confirmed customer data is left intact as long as quantity was not adjusted.

Adding a new item to the cart also removes the customer data.

### Expected result (*)
1. Proceeding to checkout after adding another product or modifying quantity should retain the customers shipping address in the quote.

### Actual result (*)
1. Customer information in checkout is lost.

Video of bug on sample data within Magento 2.2.4
https://www.dropbox.com/s/bcdyyrzjd9cax7h/M2-customer-data-bug.mov?dl=0

**Comment by krishprakash** [comment]
Hi @marklehm.
I'm not able to reproduce this issue as provided steps by you.
Kindly confirm that it's reproducible on Vanilla Magento instance.
![image](https://user-images.githubusercontent.com/46617848/60860873-e88c8380-a235-11e9-8c93-ec14bbcbf854.png)
Thanks.

**Comment by marklehm** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @marklehm. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @marklehm, here is your [Magento instance](https://i-23622-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23622-2-2-develop.instances.magento-community.engineering/admin](https://i-23622-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by marklehm** [comment]
We upgraded our 2.3.0 instance to 2.3.2 and the bug was resolved.
