### ISSUE TITLE
[Authorize.net accept.js] "Place Order" button not being disabled

### ISSUE THREAD

**Issue by simonlandry0** [magento/magento2#23624]
### Preconditions (*)

1. Magento 2.3.2
2. Configure and setup authorize.net accept js payment method

### Steps to reproduce (*)

1. Place non-free item in cart
2. Proceed to checkout.
3. Enter shipping information and proceed to the billing step.
4. Use Authorize.net accept js payment method.
5. Fill out billing information + card details but don't hit the "update" button (this would make isPlaceOrderActionAllowed() return false)

### Expected result (*)

1. The place order button at the bottom should be disabled as long as billing information is not updated 
(Similiar to how the old authorize.net extension, the brain tree extension and the paypal extension work).

### Actual result (*)

1. Place order button is always enabled regardless of isPlaceOrderActionAllowed()'s return (unlike how the old authorize.net extension, the brain tree extension and the paypal extension currently work)
2. Will return reported confusing errors for customers when the form is submitted without first updating billing information. Bad UX.

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23624-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23624-2-3-develop.instances.magento-community.engineering/admin](https://i-23624-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17996` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @simonlandry0, @edenduong. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.
