### ISSUE TITLE
Order's "protect_code" is changed on every save causing old shipment links to 404.

### ISSUE THREAD

**Issue by fsw** [magento/magento2#23623]
### Preconditions (*)
1. Magento version 2.2.5 on cloud (probably affects any version)

### Steps to reproduce (*)
1. Create any order
2. Go to Order page in admin panel
3. Click "Ship", click "add Tracking Number" on shipping form and fill tracking data
4. Click "Submit Shipment"
5. User receives working tracking link to email (A)
6. Perform any action that triggers save on order. For example "Hold" and "Unhold" order in admin panel.
7. Order gets new "protect_code" and link sent before stops working.
8. Go to shipment tab and click "Send Tracking Information"
9. User receives new link that works (B) (until order is saved again) 

### Expected result (*)
Both links in (A) and (B) should be working (and look the same?).

### Actual result (*)
Link (A) stops working (shows 404) as soon as order is saved.

### Proposed solution

My idea for a solution would be to move this line:
https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/app/code/Magento/Sales/Model/ResourceModel/Order.php#L156
up a bit placing it under `if (!$object->getId()) {` thus making `protect_code` being set to random value only when order is created and not change later.

It seems that this `protect_code` is used only to construct such links and I assume those links should be working even after order is changed. However I am not sure about that.

What is the idea behind this field and why it is being changed on every save?

**Comment by fsw** [comment]
After posting this and trying to reproduce on vanilla Magento I realized that the link to shipment comes from our custom implementation witch simply assumed this code does not change. Please ignore and sorry for confusion.

**Comment by zouhongzhao** [comment]
This is a bug in the design, it is generally difficult to trigger, but I successfully triggered, the steps are as follows:
1. Create an order without creating an invoice
2. Create a ship, you will receive an email, open this tracking link, it is normal now
3. Create invoice, then refresh the tracking link above, and find 404.
Because protect_code is updated every time it is saved, the code is in
Magento \ Sales \ Model \ ResourceModel \ Order \
_beforeSave

**Comment by fsw** [comment]
@zouhongzhao I have closed this issue as for my case this error happened because of custom integration. If for you it is happening on vanilla Magento 2 I think you should open a separate issue.
