### ISSUE TITLE
A usability issue: if an administrator set «In Stock» as a product stock status, but did not set the «Quantity» then after the product saving Magento 2 silently resets the stock status to «Out of Stock» without any notification to the administrator

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2362]
Surely, Magento 2 should notify the administrator: "Please, specify the quantity".
![magento2-03](https://cloud.githubusercontent.com/assets/83204/11146199/3586432c-8a1d-11e5-87d1-c453628993e1.png)

**Comment by andimov** [comment]
@mage2pro 
Could you please add the description of steps, actual result and expected result to this ticket?
It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
