### ISSUE TITLE
Magento 2 table not found after Migration

### ISSUE THREAD

**Issue by AJHopper** [magento/magento2#23626]
### Preconditions (*)

1. Magento 2.3.1
### Steps to reproduce (*)
Important: Provide a set of clear steps to reproduce this bug. We can not provide support without clear instructions on how to reproduce.
--
1. Migrated data from Magento 1.9.3.8 using migration tool
2. Attempt to access or index Customers

### Expected result (*)
1. re-index customers or load customer tab

### Actual result (*)
1. Base table or view not found: 1146 Table 'larpwarr_SSwordsMagento2.mg2_' doesn't exist, query was: DESCRIBE `mg2_`

Prior to the migration this was looking into the customer_grid table correctly, 'mg2_customer_grid' however since the migration it seems to have dropped out the 'customer_grid' part and is now looking for a non-existent table.

Any ideas why, or where this value is stored / pulled from so I can look into altering it back to what it should be?

**Comment by engcom-Alfa** [comment]
Hello @AJHopper  ! Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
