### ISSUE TITLE
UPS negotiated price not work

### ISSUE THREAD

**Issue by nguyenbach95** [magento/magento2#23636]
### Preconditions (*)

1. Magento 2.2.8

### Steps to reproduce (*)

1. Create order with UPS shipping (use negotiated price is enable)
2. The shipping price is right on checkout screen
3. Shipping price on UPS is different to Magento

### Expected result (*)

1. Price on UPS and Magento are the same

### Actual result (*)

1. Prices are not the same

Note: After I added RateInformation on line 1314 file vendor/magento/module-ups/Model/Carrier.php, it works
`$ratePart = $xmlRequest->addChild('RateInformation');`
`$ratePart->addChild('NegotiatedRatesIndicator');`

**Comment by engcom-Charlie** [comment]
Hello @nguyenbach95 ! Please provide more info and update your issue

**Comment by nguyenbach95** [comment]
@engcom-Charlie What information do you need?

**Comment by engcom-Charlie** [comment]
@nguyenbach95 What do you mean "Price on UPS and Magento are the same" ?

**Comment by nguyenbach95** [comment]
@engcom-Charlie Example: 
Negotiated price is applied, shipping cost , shown on checkout, is $12.8. But on UPS account, shipping cost is $16.x

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23636-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23636-2-3-develop.instances.magento-community.engineering/admin](https://i-23636-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @nguyenbach95 ! I have just tested this this on fresh 2.3-develop instance and i was not able to reproduce this issue (i used valid destination information) . Price on UPS and Magento are the same. Check screenshots 

![Screenshot from 2019-07-18 12-41-24](https://user-images.githubusercontent.com/51680850/61447849-76fdb500-a95a-11e9-8025-5ec59ac11766.png)

![Screenshot from 2019-07-18 12-41-06](https://user-images.githubusercontent.com/51680850/61447840-7402c480-a95a-11e9-9b13-809208836f47.png)

Maybe i missed some steps ? Feel free to reopen it in case you can add more steps and confirm issue .
Thanks for collaboration !

**Comment by nguyenbach95** [comment]
@engcom-Charlie Did you turn on negotiated price? And Did your UPS account have negotiated rate? 
`<RatedShipment>
        <Service>
            <Code>03</Code>
        </Service>
        <RatedShipmentWarning>Your invoice may vary from the displayed reference rates</RatedShipmentWarning>
        <BillingWeight>
            <UnitOfMeasurement>
                <Code>LBS</Code>
            </UnitOfMeasurement>
            <Weight>7.0</Weight>
        </BillingWeight>
        <TransportationCharges>
            <CurrencyCode>USD</CurrencyCode>
            <MonetaryValue>21.85</MonetaryValue>
        </TransportationCharges>
        <ServiceOptionsCharges>
            <CurrencyCode>USD</CurrencyCode>
            <MonetaryValue>0.00</MonetaryValue>
        </ServiceOptionsCharges>
        <TotalCharges>
            <CurrencyCode>USD</CurrencyCode>
            <MonetaryValue>21.85</MonetaryValue>
        </TotalCharges>
        <GuaranteedDaysToDelivery/>
        <ScheduledDeliveryTime/>
        <RatedPackage>
            <TransportationCharges>
                <CurrencyCode>USD</CurrencyCode>
                <MonetaryValue>21.85</MonetaryValue>
            </TransportationCharges>
            <ServiceOptionsCharges>
                <CurrencyCode>USD</CurrencyCode>
                <MonetaryValue>0.00</MonetaryValue>
            </ServiceOptionsCharges>
            <TotalCharges>
                <CurrencyCode>USD</CurrencyCode>
                <MonetaryValue>21.85</MonetaryValue>
            </TotalCharges>
            <Weight>6.7</Weight>
            <BillingWeight>
                <UnitOfMeasurement>
                    <Code>LBS</Code>
                </UnitOfMeasurement>
                <Weight>7.0</Weight>
            </BillingWeight>
        </RatedPackage>
        <NegotiatedRates>
            <NetSummaryCharges>
                <GrandTotal>
                    <CurrencyCode>USD</CurrencyCode>
                    <MonetaryValue>12.38</MonetaryValue>
                </GrandTotal>
            </NetSummaryCharges>
        </NegotiatedRates>
    </RatedShipment>`
Negotiated Rate is 12.38 ( it is real cost ) instead of 21.85
