### ISSUE TITLE
Cart Price Rule - No expiry date field

### ISSUE THREAD

**Issue by asim-vax** [magento/magento2#23639]
Hi,
When trying to edit expiry dates for voucher codes, i noticed that the box is missing.
This is made worse by migrating data from m1 - and all of our live voucher codes expired, and we can't change them via them admin, only via direct sql on the database.

### Preconditions (*)
1. Magento 2.3.2
2. Ubuntu 19.04, php 7.2

### Steps to reproduce (*)
1. Set up blank magento 2.3.2 installation
2. Log in to admin
3. Browse Marketing -> Cart Price Rules
4. Click Add New Rule
5. No box for expiry date

### Expected result (*)
1. Be able to input a to and from date for coupon codes
2. Magento 1 screenshot as to expected functionality:
![Screenshot from 2019-07-09 14-25-39](https://user-images.githubusercontent.com/4798940/60892015-4f219980-a256-11e9-8ab0-9493333c7467.png)

### Actual result (*)
1. Can't input to and from date
2. magento 2 screenshot:
![Screenshot from 2019-07-09 14-20-52](https://user-images.githubusercontent.com/4798940/60892625-572e0900-a257-11e9-8054-08347a96426c.png)

**Comment by asim-vax** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @asim-vax. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @asim-vax, here is your [Magento instance](https://i-23639-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23639-2-3-develop.instances.magento-community.engineering/admin](https://i-23639-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by asim-vax** [comment]
Hi,
I do apologise - this is an issue with EE 2.3.2 - the to/from date is there in the above instance, but not in a vanilla EE 2.3.2 install.
![Screenshot from 2019-07-09 14-44-57](https://user-images.githubusercontent.com/4798940/60893101-331ef780-a258-11e9-84bf-b1e2fbab9888.png)

Do you want me to close this ticket?

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23639-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23639-2-3-develop.instances.magento-community.engineering/admin](https://i-23639-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hi @asim-vax thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.3-develop
![55](https://user-images.githubusercontent.com/51680745/60893560-c9a7e480-a269-11e9-8964-11b73866e138.png)
.

**Comment by asim-vax** [comment]
@engcom-Bravo as above - it is an issue with the enterprise version of magento 2.3.2, i cannot replicate the issue with the 2-3-develop instance granted here

**Comment by engcom-Bravo** [comment]
@asim-vax on enterprise 2.3.2 also not reproduse 
![66](https://user-images.githubusercontent.com/51680745/60894414-47202480-a26b-11e9-8873-bbc7cb8ae598.png)

**Comment by engcom-Bravo** [comment]
@asim-vax really, on 2.3.2 is reproduced.

**Comment by sdzhepa** [comment]
Hello @asim-vax 

It is not a bug it is expected behavior because of Commerce(Enterprise) version of Magento has Staging functionality.
In general, all "From" and "To" time fields were removed and should be used "Staging Updates Schedule" functionality.

More information about "Content Staging" can be found in Magento docs for Commerce version:
- [Content Staging](https://docs.magento.com/m2/ee/user_guide/cms/content-staging.html)
- [Create a Cart Price Rule](https://docs.magento.com/m2/ee/user_guide/marketing/price-rules-cart-create.html)
