### ISSUE TITLE
CSV Import error: Please enter a correct entity model

### ISSUE THREAD

**Issue by avoelkl** [magento/magento2#23630]
I have recently updated from Magento Magento Open Source 2.3.1 to 2.3.2 and out of a sudden the CSV import does not work any more.
The error message when importing products is: "Please enter a correct entity model."

### Preconditions (*)
1. Update from Magento Open Source 2.3.1 to 2.3.2

### Steps to reproduce (*)
1. Go to System > Import
2. Choose Entity Type: Products
Import Behavior: Add/Update
Field Seperator: ;
Multiple value separtor: |
select a valid CSV file (which worked before in 2.3.1)
Images File directory: pub/media/import

3. Click "Check Data"
4. Receive error message: Please enter a correct entity model.

Those exact settings worked in 2.3.1

### Expected result (*)
1. Either receive infos about the import or a successful result to process the import

### Actual result (*)
1. Error message: Please enter a correct entity model.

### Environment

- Magento Open Source 2.3.2
- PHP 7.2.20

**Comment by engcom-Bravo** [comment]
Hello @avoelkl. Thanks for reporting. Give me please your code from .csv file for import. And add description of steps when exporting products to CSV file on 2.3.1. Thanks.

**Comment by avoelkl** [comment]
Turns out it was my own mistake. Shame on me. Sorry!

**Comment by imtiaz0405** [comment]
Hi ,
I have the same issue with magneto 2.3.5. i found the module ImageMagick was missing .
i found this error in exception logs .

you can install this by ssh
yum -y install ImageMagick-devel ImageMagick-c++-devel ImageMagick-perl
