### ISSUE TITLE
Braintree Integration support for 3D Secure 2.0 for hosted fields (JS SDK 3.46)

### ISSUE THREAD

**Issue by lingwooc** [magento/magento2#23642]
In order for users of the Braintree magento2 integration in the EU to continue using it after September 14, 2019 3D Secure 2.0 (3DS 2.0) must be used. This is the SCA used by braintree to comply with PSD2.

For users of the hosted fields method this isn't available in the current version (2.3.2) which uses version 2.32.0 of the Braintree JS SDK. The 2.3-develop branch is also behind as it is on 3.44.1 which also doesn't support it.

I have confirmed today with braintree support that the minimum compliant version is 3.46.0-beta-3ds.8 . I suspect this hasn't hit 2.3-develop as it is beta but time runs short and I can't find any statements from magento that this will be supported in 2.3.3.

More infomation here https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3

The braintree php sdk (not hosted fields) is more complex as braintree are yet to release a 3dsecure 2.0 compatible version (also confirmed with braintree support today).

### Description (*)

3D Secure 2.0 for hosted fields in magento2. Minimum braintree js sdk version 3.46.0-beta-3ds.8

### Expected behavior (*)

3D Secure 2.0 for hosted fields in magento2 is supported

### Benefits

Without it the braintree integration will no longer be usable in the EU

**Comment by sdzhepa** [comment]
Hello @lingwooc 

Thank you for contribution and collaboration!

We have already updated the Braintree API to the latest Js SDK 3 and implemented integration with Braintree 3DS 2.0 service. These changes will be available in 2.3.3 and 2.2.10. 

Also, we have started communication https://community.magento.com/t5/Magento-DevBlog/3D-Secure-2-0-changes/ba-p/136460  that we are going to deprecate all the core payments integrations in favor of their official marketplace extensions which we are also going to bundle in 2.4.
So, we do not need to create a separate ticket for this issue.
