### ISSUE TITLE
Trying to change images for site - error code "Invalid input datetime format of value '03/01/+00201818"

### ISSUE THREAD

**Issue by FurnitureboxKate** [magento/magento2#23647]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ajijshekh123** [comment]
@FurnitureboxKate - fell free to reopen this issue when you will be ready to provide more details and we will review it and confirm it.
