### ISSUE TITLE
Send friend sender email should be static not user defined

### ISSUE THREAD

**Issue by juhanihaapala** [magento/magento2#23646]
### Preconditions (*)

1. Magento 2.3.2 with send friend email enabled

### Steps to reproduce (*)

1. On product page select email friend
2. Fill the form

### Expected result (*)

1. Email is sent from the email configured as sender in configuration

### Actual result (*)

1. Email is sent from the email filled in form it won't work because server is not qualified sender and gmail for example set the email in spam with this huge warning
![Screenshot_2019-07-12_16-09-01](https://user-images.githubusercontent.com/3079827/61130454-644d3100-a4bf-11e9-8fce-b5cb4431479f.png)

### Proposed solution (*)
It makes more sense to put the email address from the Sender email form field in the Reply-To header instead of the From header. The From header should be one of the addresses configured in Magento's configuration under General > Store Email Addresses.

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23646-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23646-2-3-develop.instances.magento-community.engineering/admin](https://i-23646-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @juhanihaapala.  Thank you for your request. I'm not able to reproduce issue by steps you described on clean 2.3-develop
![99](https://user-images.githubusercontent.com/51680745/60960548-e9dfae00-a312-11e9-98bb-eb99c3d385ac.png)
.

**Comment by juhanihaapala** [comment]
@engcom-Bravo I was abel to confirm it in that instance. The email never came to my gmail box even not in spam. But yes it will happily send it but it's for sure marked as spam because the sender is not qualified sender.

**Comment by juhanihaapala** [comment]
Oh, and I was using the form as guest. So enabled guest sending first on settings.

**Comment by engcom-Bravo** [comment]
On your hosting is configured mail server? If your sending email in spam Gmail maybe determines it as spam.

**Comment by juhanihaapala** [comment]
Of course. And to clarify the issue: the email shouldn't be sent as the email user has defined email address.

1. When settings are like this:
![Screenshot_2019-07-12_15-54-01](https://user-images.githubusercontent.com/3079827/61129623-7332e400-a4bd-11e9-916b-412399ff1397.png)

2. Then in send friend form user can select where is it send from:
![Screenshot_2019-07-12_16-00-49](https://user-images.githubusercontent.com/3079827/61129997-5945d100-a4be-11e9-84e1-ec724554ae3d.png)

3. And it will be sent with that email to the friend:
![Screenshot_2019-07-12_16-01-28](https://user-images.githubusercontent.com/3079827/61130017-619e0c00-a4be-11e9-8bf7-a46d41655ae6.png)

And because of that gmail, outlook or any decent email provider will flag it as spam.

**Comment by engcom-Bravo** [comment]
It is Thunderbird Mozilla. It is blocks your email. Change your settings and everything will be good.
https://support.mozilla.org/en-US/kb/how-change-thunderbird-layout

**Comment by hostep** [comment]
@engcom-Bravo: I'm able to reproduce on vanilla 2.3.2

It makes more sense to put the email address from the Sender email form field in the `Reply-To` header instead of the `From` header. The `From` header should be one of the addresses configured in Magento's configuration under General > Store Email Addresses.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18139` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
@hostep @juhanihaapala , thanks for the communication!

**Comment by amelaraby** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @araby93. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @araby93, here is your [Magento instance](https://i-23646-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23646-2-3-develop.instances.magento-community.engineering/admin](https://i-23646-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @juhanihaapala. Thank you for your report. 
The issue has been fixed in magento/magento2#23684 by @edenduong in 2.3-develop branch
Related commit(s):
 - [2048b40ce5dd3ea7c6344cb0a33dca6cc10954d9](https://github.com/magento/magento2/commit/2048b40ce5dd3ea7c6344cb0a33dca6cc10954d9)
 - [6ae022367e1dd3a6e40d6b9d602f525f2bae900e](https://github.com/magento/magento2/commit/6ae022367e1dd3a6e40d6b9d602f525f2bae900e)

The fix will be available with the upcoming 2.3.4 release.
