### ISSUE TITLE
Magento 2.3 contact form not sending emails( No log entry)

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#23645]
### Preconditions
Magento 2.4-develop

### Steps to reproduce (*)

- Add `throw new LocalizedException(__('test localized exception'));` before https://github.com/magento/magento2/blob/2268edc5cadfb7b0fbf0e998a23abd60a4608efb/app/code/Magento/Contact/Controller/Index/Post.php#L75
- Enter the contact form
- Send a message

### Expected result (*)
1. Exception with stack trace is logged

### Actual result (*)
1. No log entry in any of the Magento, PHP or Apache logs that provides any insight

**Original case:**
Preconditions
Magento 2.3.0, 2.3.1 or 2.3.2  CE

1. sendmail is installed and working (Courier-MTA on Debian 10)
2. php mail() command working fine
3. order status emails are being send fine

Steps to reproduce (*)

1. enter the contact form
2. send a message

Expected result (*)
1. email is sent

Actual result (*)
1**. as a user get a generic error message that email could not be sent**
2. **No log entry in any of the Magento, PHP or Apache logs that provides any insight**

Since order status emails can be sent, Magento is clearly capable of sending emails to users.
At the very least, there must be a log entry THAT something happend and best even provide inside what needs fixing. Currently there is no log entry at all. Not even on DEBUG level.

**Comment by engcom-Charlie** [comment]
Hello @YiffyToys ! Please provide more information about this issue

**Comment by YiffyToys** [comment]
@magento give me 2.3-develop instance
@engcom-Charlie  How to reproduct that no information is logged if the contact form fails to send an email? How to check logs on the automatically created instances used to reproduce an issue? Can these instances actually send email?

**Comment by magento-engcom-team** [comment]
Hi @YiffyToys. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @YiffyToys, here is your [Magento instance](https://i-23645-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23645-2-3-develop.instances.magento-community.engineering/admin](https://i-23645-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18023` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by BrentRobert** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @BrentRobert. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @BrentRobert, here is your [Magento instance](https://i-23645-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23645-2-3-develop.instances.magento-community.engineering/admin](https://i-23645-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by YiffyToys** [comment]
I can confirm that it is fixed in Magento CE 2.3.3

If you are reading this, please note that #24902 may have been added in the process.

**Comment by elvinristi** [comment]
FYI @YiffyToys - it's not fixed in M2.3.3, but in M2.3-dev. Hopefully will be included in next M2.3.4 release.

**Comment by YiffyToys** [comment]
I reported this issue and after the update to 2.3.3-CE my contact form works again.

**Comment by BrentRobert** [comment]
@YiffyToys This issue is still valid as it states that there is not always logging available. Your underlying issue might have been fixed meanwhile.

**Comment by YiffyToys** [comment]
> @YiffyToys This issue is still valid as it states that there is not always logging available. Your underlying issue might have been fixed meanwhile.

You are right about that.

**Comment by Vishrootways** [comment]
@YiffyToys Could you please let us know how did you solve that issue? I am also getting same issue with Magento 2.3.3 version. Contact us and order emails not getting send to customer as well admin. We have not added any non-ASCII chars to email sender and/or receiver detail.

NOTE: We have migrated data from Magento 1.9 to Magento 2.3

It would be good if you can suggest us what can be the issue into this case.

**Comment by engcom-Delta** [comment]
**Note:** Pull request [#24882](https://github.com/magento/magento2/pull/24882) should fix the issue with logging exception

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31077` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MarcusWolschon** [comment]
The automatic text block fails to mention if this ticket will be updated with status (fixed, wontfix, notreproducable,closed,...) information as well as release-information when MV-31077 gets status updates (such as when it gets closed as fixed and assigned to a release).

**Comment by Amit-Hariyani** [comment]
@magento I am working on this

**Comment by mateuszrusiecki** [comment]
seriously it's not fixed yet!? why am I surprised...
