### ISSUE TITLE
The incorrect qty ( Bundle products)

### ISSUE THREAD

**Issue by levi-dtn** [magento/magento2#23644]
Preconditions (*)
1.Magento 2.3.2
2.PHP 7.2.x

Steps to reproduce (*)
1. Add Bundle product ( including child product with qty greater than 1)
2. Checkout by Paypal/ Visa/ Master card

Show error message: We found an invalid quantity to invoice item (edited) 
I checked and found that $orderItem->getId() return null  in vendor/magento/module-sales/Model/Service/InvoiceService.php

Expected result (*)
1. No error

Actual result (*)
1. Error above

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23644-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23644-2-3-develop.instances.magento-community.engineering/admin](https://i-23644-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @levi-dtn,
I have verified this issue as per your steps to be reproduced. I have placed a Bundle product with incorrect qty to order using the Credit card. I have placed an order successfully and I have not found any Qty related issue invoice section in Front end as well as in the backend.

Please see attached screenshot:
![Order details_1](https://user-images.githubusercontent.com/24711761/60948286-3675ba00-a310-11e9-9567-c76a25392306.png)

![Order details_Admin](https://user-images.githubusercontent.com/24711761/60948287-3675ba00-a310-11e9-8c55-fee359be17a6.png)

![Order details_Invoice](https://user-images.githubusercontent.com/24711761/60948288-370e5080-a310-11e9-858b-f354c3641d30.png)

![Order details_Invoice_Admin](https://user-images.githubusercontent.com/24711761/60948289-370e5080-a310-11e9-94b2-2b34e9b96e95.png)

@levi-dtn - Please see the Qty and place order details. If anything missing in my end please let me know.

**Comment by ajijshekh123** [comment]
@levi-dtn - fell free to reopen this issue when you will reproduce this issue. we will review it and confirm it.

**Comment by levi-dtn** [comment]
@ajijshekh123 Sorry for the late response. I encounter this issue in Magento 2.3.2, please give a Magento 2.3.2 default so that I can reproduce it for u

**Comment by ajijshekh123** [comment]
@levi-dtn - You can ask directly to Magento Team. It will provide you to Magento 2.3 and 2.2 Instance for reproducing this issue.

**Comment by levi-dtn** [comment]
@magento give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @levi-dtn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @levi-dtn, here is your [Magento instance](https://i-23644-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23644-2-3-develop.instances.magento-community.engineering/admin](https://i-23644-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by levi-dtn** [comment]
@ajijshekh123 can u config payments?

**Comment by ajijshekh123** [comment]
Yes @levi-dtn

**Comment by levi-dtn** [comment]
@ajijshekh123 I found that this issue just happens on my local, I tried to reproduce it on your site but everything works well

**Comment by ajijshekh123** [comment]
@levi-dtn - This issue may be related to your custom module or extension. So please debug your code in your local system and fix the issue. if this issue did not reproduce in Magento Instance I can't do anything.

@levi-dtn - If any other help you want from my side, You can reply to me.

**Comment by levi-dtn** [comment]
@ajijshekh123 I don't use any module or extension on my local

**Comment by levi-dtn** [comment]
![image](https://user-images.githubusercontent.com/48718611/61354249-f5475200-a89b-11e9-8be2-9d3ba71dc7fa.png)

**Comment by ajijshekh123** [comment]
@levi-dtn - If you have available Paypal Credential (Sandbox Credential), Send me I will again verify this issue Or You can reopen this issue.

**Comment by levi-dtn** [comment]
@ajijshekh123 
Username:
giang.UK-Facilitator_api1.gmail.com
Password:
ZQU3F8AGRFWYMLSE
Signature:
AFrsE.uQ6zMrM-0onONjJA3MlieKAyF8NEqPg7xJVLXkLwVeHv020l7B

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23644-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23644-2-3-develop.instances.magento-community.engineering/admin](https://i-23644-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by levi-dtn** [comment]
@ajijshekh123 example
[Sprite Yoga Companion Kit _ Products _ Inventory _ Catalog _ Magento Admin.pdf](https://github.com/magento/magento2/files/3400883/Sprite.Yoga.Companion.Kit._.Products._.Inventory._.Catalog._.Magento.Admin.pdf)

**Comment by ajijshekh123** [comment]
@levi-dtn - I want 'Merchant Account ID', Can you please send me?

**Comment by levi-dtn** [comment]
@ajijshekh123 
Merchant Account ID: G6Y3B2X3KH6FA

**Comment by ajijshekh123** [comment]
@levi-dtn - I have placed orders using Paypal. Placed order successfully with Bundle Items.

**See attached screenshot:**

![Checkout_SuccessOrder](https://user-images.githubusercontent.com/24711761/61364243-11022680-a8a3-11e9-8b63-91bb09182de1.png)

![SuccessOrder](https://user-images.githubusercontent.com/24711761/61364244-119abd00-a8a3-11e9-846c-b5bf6602b770.png)

**Comment by levi-dtn** [comment]
@ajijshekh123 https://drive.google.com/file/d/1mxOZyJ5SLzQ0xzm829HCEHhMM4ckdaX6/view?usp=sharing

**Comment by cscd98** [comment]
https://github.com/magento/magento2/issues/22743
