### ISSUE TITLE
Frontend Label For Custom Order Status not Editable in Magento Admin in Single Store Mode

### ISSUE THREAD

**Issue by ghost** [magento/magento2#23654]
### Preconditions (*)

1. Magento version 2.2.9 with Single Store Mode turned on

### Steps to reproduce (*)

1. Go to Stores -> Order Status
2. Select any status
3. There is no place to edit the status label for the frontend.
4. If single store mode is turned off, there is a field where the status label for the frontend can be modified.

### Expected result (*)

1. There should be a field where we can modify the string for a status for the frontend only

### Actual result (*)

1. There is no field to change the label for the frontend on the status page.

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23654-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23654-2-3-develop.instances.magento-community.engineering/admin](https://i-23654-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23654-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23654-2-2-develop.instances.magento-community.engineering/admin](https://i-23654-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18054`, `MC-18055` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @shilpambb, @edenduong. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.

**Comment by ghost** [comment]
@magento-engcom-team Will this be included in 2.2?
