### ISSUE TITLE
Advanced Reporting not working

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#23653]
Advanced Reporting is not working in Magento 2.2.4 after following set up steps and verifying that the code change in the patch reported in

https://github.com/magento/magento2/issues/21452#issuecomment-467799311

is present in the code base.

### Preconditions (*)

1. Magento version 2.2.4
2. PHP 7.0.33

### Steps to reproduce (*)

1. Enable Advanced Reporting in Admin
2. Go to System > Integrations > Magento Analytics user > Reauthorize
3. Wait 24 hours

### Expected result (*)

1. Link to 'Advanced Reporting' from Admin dashboard goes to Advanced Reporting dashboard

### Actual result (*)

1. Link to 'Advanced Reporting' from Admin dashboard shows a 404

**Comment by nbennett25** [comment]
No updates yet? Do I need to spin up a 2.2.4 instance and then wait for 24 hours to test.. the sample data? What are the next steps here?

**Comment by engcom-Alfa** [comment]
Hi @nbennett25. Thanks for applying. We are closing this issue as a duplicate of #21452.
