### ISSUE TITLE
No se ve nada del Admin de mi Magento 2

### ISSUE THREAD

**Issue by RodrigoSGE** [magento/magento2#23655]
Buenas tardes, me ha surgido un problema en Magento 2 y es que cuando entro al administrador me dice que necesito permisos para tener acceso. Ayuda por favor

**Comment by sdzhepa** [comment]
Hello @RodrigoSGE 

Unfortunately, it very hard or even impossible to help without additional details.
Could you please provide more details as mentioned in this [comment](https://github.com/magento/magento2/issues/23655#issuecomment-510253522)?  

> To help us process this issue please make sure that you provided the following information:
> 
>  - Summary of the issue
>  - Information on your environment
>  - Steps to reproduce
>  - Expected and actual results

> **Please make sure that the issue is reproducible on the vanilla Magento instance following Steps to reproduce.** To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> @ magento give me 2.3-develop instance - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

Without additional details, we will have to close this issue.

Thank you in advance
