### ISSUE TITLE
The «Use Default Value» backend option is broken for product images

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2366]

**Comment by yaronish** [comment]
@dfediuk Thank you for issue reporting. 
We already have internal ticket connected with this problem: MAGETWO-45306

**Comment by orlangur** [comment]
@dmitry-fedyuk thanks for bug report! This issue is already covered in https://github.com/magento/magento2/issues/10863 together with the way it should be fixed.
