### ISSUE TITLE
Advanced JavaScript bundling with dependencies that load from urls does not work

### ISSUE THREAD

**Issue by drazulay** [magento/magento2#23664]
### Preconditions (*)

1. Magento2 2.3.x 
2. The [Advanced JavaScript bundling guide](https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-js-bundling.html)

### Steps to reproduce (*)
1. Create a build.js file that contains dependencies loaded from urls (for example in 'paths' or 'map').

For example:

```
({
  optimize: 'none',
  inlineText: true,
  ...
  paths: {
    ...
    paypalInContextExpressCheckout: 'https://www.paypalobjects.com/api/checkout',
    acceptjssandbox: 'https://jstest.authorize.net/v1/Accept',
    acceptjs: 'https://js.authorize.net/v1/Accept',
    ...
  },
  ...
})
```
  
### Expected result (*)

1. When running the r.js optimizer it should generate bundles.

### Actual result (*)

1. Generating bundles failes with messages like:
```
Error: Error: ENOENT: no such file or directory, open 'https://www.paypalobjects.com/api/checkout.js'
    at Object.fs.openSync (fs.js:646:18)
```

When I remove these dependencies from the build.js file i can succesfully create bundles.

It seems this is an issue with requirejs, but perhaps someone knows how to make this work (And will document it in the Magento guide)?

**Comment by drazulay** [comment]
> Hi @drazulay. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @drazulay do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

These checkboxes don't work, not sure what to do with this. Was tested on a vanilla instance locally.

**Comment by magento-engcom-team** [comment]
Hi @drazulay. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @drazulay, here is your [Magento instance](https://i-23664-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23664-2-3-develop.instances.magento-community.engineering/admin](https://i-23664-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by junaidq57** [comment]
Did you find any solution?? I am having the same issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21921` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment]
Hello @drazulay, thanks for the report! Unfortunately, the issue you're discribing has nothing to do with Magento but rather with RequireJS optimizer itself. [In the official documentation](https://requirejs.org/docs/optimization.html#empty) you can find:

> The optimizer cannot load network resources, so if you want it included in the build, be sure to create a paths config to map the file to a module name. Then, for running the optimizer, download the CDN script and pass a paths config to the optimizer that maps the module name to the local file path.

There are two different approaches described there depending if you really want the file to be included in the bundle or not.
