### ISSUE TITLE
Shipping address selected changes to default shipping address after clicking browser back button

### ISSUE THREAD

**Issue by magentopits** [magento/magento2#23667]
### Preconditions (*)

1. Magento 2.2.6 and Magento 2.3.2

### Steps to reproduce (*)

1. Login customer.
2. Add multiple addresses from my account page.
3. Set one as default billing address and other as default shipping address.
4. Add product to cart.
5. Proceed to checkout.
5. Select any address other than the default shipping address as shipping address.
6. Select any online payment method (Eg:- Postfinance payment or Visa).
7. Proceed to the bank's payment page.
8. Click browser back button.
9. Check the selected shipping address in magento payment page or shipping address selection page.

### Expected result (*)

1. Previously selected address will be shown as shipping address.

### Actual result (*)

1. Default shipping address is shown as selected shipping address.

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23667-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23667-2-3-develop.instances.magento-community.engineering/admin](https://i-23667-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hi @magentopits thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.3-develop. If you'd like to update issue, please reopen it.
![v6](https://user-images.githubusercontent.com/51680745/61047176-8d01f780-a3e7-11e9-8f71-a6c37dde5a91.png)

**Comment by operations1** [comment]
Hello,

The same issue is appearing for me on Magento 2.2.8 and its confusing some of the shipping/payment methods rules and restrictions. Please provide a complete solution to keep the selected address (quote address) and not select the default address again. You can reproduce this on a fresh Magento 2.2.8 installation by logging out and login again, and going back to the checkout page!

**Comment by magentopits** [comment]
I'm not sure how to reopen this issue. @engcom-Bravo could you please do that for me as @operations1 is also getting this issue.

**Comment by engcom-Bravo** [comment]
@magentopits we are supposed to close the issues that are not reproduced on 2.3-develop branch. (Please see the details to point 4 of our [workflow](https://github.com/magento/magento2/issues/23667#issuecomment-510441064)). In case You find the way to reproduce it on 2.3-develop please let us know and we will reopen the issue.

**Comment by operations1** [comment]
Hello @engcom-Bravo,

Fair enough, but where should we post it? Its a core bug and we need a solution/workaround please.

**Comment by engcom-Bravo** [comment]
Hello @operations1. As You've mentioned You are facing the issue on 2.2.8. Unfortunately
branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still face this issue on `2.3` and it is reproducible on 2.3-develop (what means it is still not fixed), please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank You.
