### ISSUE TITLE
Magento 2.3.1 Category update issue via repository save

### ISSUE THREAD

**Issue by pavanusn** [magento/magento2#23662]
**Preconditions (*)**

1. Magento 2.3.1

**Steps to reproduce (*)**

1. When I tried to update category using repository save
2. Here $this->categoryRepository = \Magento\Catalog\Model\CategoryRepository
 
 		$category = $this->categoryRepository->get($magentoCategory->getId());
         try {
             $category->setData($mappedData);
             $this->categoryRepository->save($category);
         } catch (\Exception $e) {
 
         }
 
3. And I'm able to update the category after setting the category id to $category.
 
 		$category = $this->categoryRepository->get($magentoCategory->getId());
         try {
             $category->setData($mappedData);
             $category->setId($magentoCategory->getId());
             $this->categoryRepository->save($category);
         } catch (\Exception $e) {

         }
**Expected result (*)**

1. It should update the category with updated values.

**Actual result (*)**

1. Instead of updating the category, it is creating a new category.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18056` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Nazar65** [comment]
Hi @pavanusn seems like this is not an issue , can you please show how you get this ->` $mappedData `and just show `var_dump($mappedData);`

**Comment by Nazar65** [comment]
@pavanusn and if you want to update please use` addData` instead of `setData`

**Comment by pavanusn** [comment]
Thanks, @Nazar65 addData is working. May I know the difference between addData and setData

**Comment by Nazar65** [comment]
@pavanusn setData completely deletes all data and set yours, addData replaced existing keys
