### ISSUE TITLE
Unable to get invoice id in Magento 2.3.2

### ISSUE THREAD

**Issue by pandyakrunal** [magento/magento2#23668]
I am sending the invoice id to third-party API but I did not get the Invoice id. (Magento 2.3.2)
### Summary (*)

 for that, I use the sales_order_invoice_register event and in observer my code is

 $invoice = $observer->getEvent()->getInvoice();
 $orderId = $invoice->getOrderId();
 $invoiceNumber = $invoice->getIncrementId();
I got OrderId but InvoiceId is blank.

**Comment by engcom-Bravo** [comment]
Hello @pandyakrunal. Rewrite code 
instead:
$invoiceNumber = $invoice->getIncrementId();
rewrite
$invoiceNumber = $invoice->getData('entity_id'); //or use ->getEntityId();

**Comment by pandyakrunal** [comment]
Yes, I used that all but not working.

**Comment by edenduong** [comment]
@pandyakrunal : The invoice id is blank because it isn't saved in the Database  . So the id is null,

**Comment by pandyakrunal** [comment]
@edenduong So What should I do? I want Invoice id(In observer) when we create the invoice.

**Comment by edenduong** [comment]
@pandyakrunal you can use **sales_order_invoice_save_after** event

**Comment by Nazar65** [comment]
@pandyakrunal this is not best practices to use observers, please use plugin instead.

**Comment by engcom-Charlie** [comment]
Hello @pandyakrunal 
We are not able to reproduce this issue on the lates 2.3-develop branch.
Use `sales_order_invoice_save_after` event for getting invoice id.

**Comment by DividedByNULL** [comment]
> Hello @pandyakrunal
> We are not able to reproduce this issue on the lates 2.3-develop branch.
> Use `sales_order_invoice_save_after` event for getting invoice id.
There is no chance that you were able to get any type of Invoice ID using sales_order_invoice_register. I was also not able to get the Invoice ID by using this Event just simply because it's not stored in the Database (used exit, and checked the sales_invoice table).

**Comment by paugnu** [comment]
Hi,
In my case, to create a new invoice, I've created a class based on the Paypal Ipn.php class (this is my code: https://github.com/catgento/magento-2-redsys/blob/master/Controller/Result/Index.php#L238)

On the other hand, I have an observer using the event: sales_order_invoice_register. When an order is made with Paypal, the invoice id is there. When the order is created paying with my module, the invoice increment id is empty (but the invoice is correctly being created). It's like the observer is triggered before the increment id is registered in the database.
