### ISSUE TITLE
Unable to plug in to the constructor (__construct method) but there is no such limitation in the documentation

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2367]
http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html#plugin-limit
A similar issue https://github.com/magento/magento2/issues/2265

**Comment by davidalger** [comment]
@dfediuk this is intrinsic to how PHP / OOP works. since the __construct method is called when the object is instantiated, it's simply not possible to intercept the call. The documentation should not contain a list of detailed scenarios which are not possible due to how OOP works. I'm closing this as a non-issue.

@xcomSteveJohnson feel free to chime in here if you wish

**Comment by dfediuk** [comment]
Actually, it IS intercepted, for example:

```
<?php
namespace Magento\Authorization\Model\Role;

/**
 * Interceptor class for @see \Magento\Authorization\Model\Role
 */
class Interceptor extends \Magento\Authorization\Model\Role implements \Magento\Framework\Interception\InterceptorInterface
{
    use \Magento\Framework\Interception\Interceptor;

    public function __construct(\Magento\Framework\Model\Context $context, \Magento\Framework\Registry $registry, \Magento\Authorization\Model\ResourceModel\Role $resource, \Magento\Authorization\Model\ResourceModel\Role\Collection $resourceCollection, array $data = array())
    {
        $this->___init();
        parent::__construct($context, $registry, $resource, $resourceCollection, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function update()
    {
        $pluginInfo = $this->pluginList->getNext($this->subjectType, 'update');
        if (!$pluginInfo) {
            return parent::update();
        } else {
            return $this->___callPlugins('update', func_get_args(), $pluginInfo);
        }
    }
}
```

**Comment by davidalger** [comment]
@dfediuk Had the chance to look at this further… I must have been tired from living on conference sleep when I replied initially. You're right, it is intercepted! :) Question though, are you recommending the documentation be amended or suggesting there is a need to allow plugins to wrap the __construct methods? My initial reaction to it being needed is that perhaps what needs to be plugged into should really be factored out of the construct method, but I'd like to know for sure what you're suggesting here.

**Comment by dmitrii-fediuk** [comment]
Surely, it would great to have the possibility to plug in to the constructors.

**Comment by davidalger** [comment]
+@antonkril

**Comment by antonkril** [comment]
What would be a scenario for such plugin?

One scenario we discussed was to have implicit factories - objects that would be called to define list of constructor arguments dynamically. Is it the way you want to use it?

Generally plugins are there to Intercept public method calls. Technically, constructor is not an object method. It's static function, we do not intercept static functions. But if there are useful scenarios, we might add this feature.

**Comment by dmitrii-fediuk** [comment]
1) To modify an argument of a constructor (`before` plugin)
2) To do some additional initialization after constuctor have finished (`after` plugin).
3) To change a constructor's behavior (`around` plugin)
All of them have a practical sense.

**Comment by davidalger** [comment]
The documentation page has been updated for accuracy of current functionality.

**Comment by erfanimani** [comment]
I might be beating a dead horse here, but an `after` constructor plugin would be super useful for doing further initialisation after the object has been created, as @dmitry-fedyuk has pointed out.

Consider the following example: I would like to change the quality of the catalog image processor by calling `setQuality` on `Magento\Catalog\Model\Product\Image` after the constructor has finished. 

I guess the reason for that is that `Magento\Catalog\Helper\Image`, the class that's responsible for creating the object, doesn't seem to give me anything useful - the method that creates the object is protected.
