### ISSUE TITLE
 Asynchronous web endpoints & Bulk Endpoints

### ISSUE THREAD

**Issue by karthik32cse** [magento/magento2#23677]
From which version the following features are available in Magento 2 Enterprise Edition,
1. Asynchronous web endpoints
2. Bulk Endpoints

Form the dev docs, I can see the above features are available from Magento EE 2.2. But I want to know the exact version. Please give your inputs on the same

Thanks in advance

**Comment by engcom-Charlie** [comment]
Hello @karthik32cse ! Thank you for your report !
Asynchronous web endpoints & Bulk Endpoints are not exist in Magento 2 EE 2.2.x release line . That features was released in Magento 2 EE 2.3.x release line . For more information please refer here: https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0Commerce.html
