### ISSUE TITLE
Token always invalid while timezone has been set

### ISSUE THREAD

**Issue by Haiwera** [magento/magento2#23672]
### Steps to reproduce (*)

1. Go to Admin > Configuration > General > Local
2. Set timezone to Asia/Shanghai
3. Call login API with password and username to exchange a valid token
4. Call get account info API with the token

### Expected result (*)

1. Account info can be fetched

### Actual result (*)

1. Exception, The consumer isn't authorized to access self

I've debugged that the issue was caused by the TokenUserContext::isTokenExpired which is using a wrong timestamp converted by strtotime without UTC passed in.

**Comment by Haiwera** [comment]
app/code/Magento/Webapi/Model/Authorization/TokenUserContext.php
```php
if ($this->dateTime->strToTime($token->getCreatedAt()) < ($this->date->gmtTimestamp() - $tokenTtl * 3600)) {
```
Should add UTC like
```php
if ($this->dateTime->strToTime($token->getCreatedAt().' GMT') < ($this->date->gmtTimestamp() - $tokenTtl * 3600)) {
```

**Comment by engcom-Bravo** [comment]
Hi, @Haiwera . I can't reproduce this issue on 2.2-develop and 2.3-develop. Can you give me more information and maybe more steps to testing scenario?

**Comment by engcom-Bravo** [comment]
@Haiwera, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
