### ISSUE TITLE
"Vertex Settings" has the extra line at the bottom

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23676]
### Preconditions (*)

1. Magento version 2.3.2
2. PHP 7.1.30

### Steps to reproduce (*)

1. Go to the Backend, 
2. Configuration->Sales/Tax
3. Check the display of Vertex Settings

### Expected result (*)

1. It has no extra line at the bottom (the normal style)

### Actual result (*)

1. It has the extra line at the bottom
![image](https://user-images.githubusercontent.com/8234209/61119609-6adea700-a4c5-11e9-94b6-553013356871.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23676-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23676-2-3-develop.instances.magento-community.engineering/admin](https://i-23676-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23676-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23676-2-3-develop.instances.magento-community.engineering/admin](https://i-23676-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23676-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23676-2-2-develop.instances.magento-community.engineering/admin](https://i-23676-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@edenduong - In Default Magento 2.2 and 2.3 Instance, Vertex options are not available in below Configuration.  **Stores >> Configuration >> Sales >> Tax**.
See attached below screenshot:

![2 2 Screenshot](https://user-images.githubusercontent.com/24711761/61120674-23ebb400-a4bb-11e9-9b16-dce6d6b9560c.png)

![2 3 Screenshot](https://user-images.githubusercontent.com/24711761/61120675-24844a80-a4bb-11e9-8458-db4126dc2d23.png)

@edenduong - Can you please let me know how to configure Vertex Settings?

**Comment by edenduong** [comment]
Hello @ajijshekh123,

 It seems in this repository, it doesn't have this module. Because I install the magento version in 

https://magento.com/tech-resources/download

So the source code is different. You can close this issue.

Thank you very much!

**Comment by ajijshekh123** [comment]
Okay, @edenduong.
Thanks for the Update.

**Comment by hostep** [comment]
In theory you should report this bug to https://github.com/magento/ext-vertex/ (but that's still not accessible at the moment of writing)

[According](https://github.com/magento/magento2/issues/18402#issuecomment-427579396) to @okorshenko it was going to be opened to the public one day, but until now this doesn't seem to have happened yet :(

**Comment by navarr** [comment]
This is kind of a Magento bug, but I don't know that any core modules replicate it.

The extra-thick/multiple lines are caused by several sections being hidden.  Vertex does not do any custom styling here.

I have plans to turn those sections into subsections instead, but that's a little further on the roadmap.

**Comment by hostep** [comment]
Ok thanks for the explanation @navarr. Sounds like a Magento bug, let's reopen this then :)

**Comment by navarr** [comment]
Issue here is that when vertex is set to disabled, all of the Vertex sections disappear (b/c they depend on "enabled").  When that happens, only the fieldsets below them are set to display: none; - which means the div.config-section still is displayed, and it is what contains the border.

**Comment by engcom-Bravo** [comment]
High everyone. In order to see this bug in action just pull down the latest release of Community Edition via composer.

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20221` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
The same issue can be observed on Magento 2.4.0 when you go to Stores > Configuration > Security > Security.txt (when General > Enable is set to `No`)

**Comment by hostep** [comment]
@sidolov or @sdzhepa: why was this issue closed without specifying any reason?

**Comment by sdzhepa** [comment]
Hello @hostep 

Thank you for letting me know about it.
As I can see internal jira ticket has been closed. I suppose as cannot be reproduced on the latest version

@engcom-Delta @engcom-Alfa @engcom-Bravo 
Could you please check on the latest release version?
- if the initial report still actually, reopen, update, confirm
- Also, please check https://github.com/magento/magento2/issues/23676#issuecomment-665284346 if an issue exists please create a new report in https://github.com/magento/security-package/issues

**Comment by hostep** [comment]
@sdzhepa: I can still reproduce the issue in the Security section on Magento 2.4.1

In my opinion this is **not** a bug in the security-package but in the Magento/backend theme of core Magento. I'm pretty sure that you should be able to create a small simple module to reproduce it outside of the security-package.

This is super low priority though, so do with it what you want 🙂

**Comment by engcom-Delta** [comment]
@hostep I rechecked initial issue and it is not reproducible by steps on latest released version 2.4.0.
**Result:**
:heavy_check_mark: No extra line at the bottom of section
![image](https://user-images.githubusercontent.com/51681379/96114076-caf4a200-0eed-11eb-8d74-cd41ee79968f.png)
![image](https://user-images.githubusercontent.com/51681379/96114093-d21bb000-0eed-11eb-89db-86d9b8d91c19.png)

I create [issue](https://github.com/magento/security-package/issues/279) in security-package repo according your [comment](https://github.com/magento/magento2/issues/23676#issuecomment-665284346) for easier investigation. If it is Magento/backend theme issue, fix could be delivered into core Magento

**Comment by hostep** [comment]
Why do we even bother trying to guide you guys in the correct direction ... Anyway, at least there is an open ticket again but it's in the wrong repo.
