### ISSUE TITLE
Products not adding to cart magento 2.3.2

### ISSUE THREAD

**Issue by s70n1e** [magento/magento2#23675]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by engcom-Bravo** [comment]
Hi, @s70n1e . I can't reproduce this issue on 2.2-develop and 2.3-develop. Could you give me more information and preconditions, also steps to testing scenario?

**Comment by s70n1e** [comment]
Hi, my new site I have been creating is live at http://sallyswigs.co.uk

Please go to the site and try to add any product, then you will see it does not add to the cart, I recently upgraded magento from 2.3.1 to 2.3.2 so not sure if this has caused the problem. It is driving me insane.

Thanks

Andy

**Comment by engcom-Bravo** [comment]
We don`t testing websites of peoples. We testing clean instance magento of 2.x.x. I closed these issue.
