### ISSUE TITLE
[TEST] TEST ISSUES

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#23671]
### Preconditions (*)

1.  Magento 2.3
2.

### Steps to reproduce (*)

1. Create new product 
2. Add product to cart
3. Place order with product

### Expected result (*)

1. [Screenshots, logs or description]
2. Order is placed

### Actual result (*)

1. [Screenshots, logs or description]
2. Error during palce order

[BEFORE_result.json.txt](https://github.com/magento/magento2/files/3393215/BEFORE_result.json.txt)

### Additional information

Issue reproduced only with Configurable product

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Issue reproduced only with Configurable product

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18061` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-tester** [comment]
@magento I am working on it

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18313` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-tester** [comment]
@magento I'm working on it

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18313` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18773` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by sdzhepa** [comment]
Thank you for your request. I'm working on Magento 2.1-develop instance for you

**Comment by sdzhepa** [comment]
@magento give me 2.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by sdzhepa** [comment]
@magento give me 2.2 instance

**Comment by sdzhepa** [comment]
@magento give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by sdzhepa** [comment]
@magento give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by sdzhepa** [comment]
@magento give me 2.2 instance

**Comment by sdzhepa** [comment]
@magento give me 2.2 instance

**Comment by sdzhepa** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by sdzhepa** [comment]
test

**Comment by sdzhepa** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by sdzhepa** [comment]
@magento give me 2.2

**Comment by sdzhepa** [comment]
@magento give me 2.2 instance

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Foxtrot** [comment]
@magento I am working on it

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@sdzhepa, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen the ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Comment by sdzhepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-23671-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23671-2-3-develop.instances.magento-community.engineering/admin](https://i-23671-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by taoufiqaitali** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @taoufiqaitali. Thank you for your request. I'm working on Magento 2.3-develop instance for you
