### ISSUE TITLE
Bug: Magento 2 does not require an administrator to enter the URL Key, tries to autogenerate it on a product saving, but do it wrongly and fails with the message: «URL key for specified store already exists»

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2368]
![](https://mage2.pro/uploads/default/original/1X/14eec90c7ce8a0cb1b395a924d3ee3eea9d15cd3.png)
Looks similar to https://github.com/magento/magento2/issues/2013

**Comment by jsakars** [comment]
Still present using 2.0.2 version. I would expect it increment the key - e.g. `slug` & `slug-1`

**Comment by mazhalai** [comment]
@werdlv please do not post on closed issues. Please create a new one with details how to reproduce.

**Comment by jsakars** [comment]
@mazhalai this issue is not closed :) Referenced issue #2474 however is

**Comment by iflairkinjal** [comment]
It seems like if there is blank field for category URL, need to add category URL manually which is not existing for any other category

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by martinmonnier** [comment]
I have the same problem with the url key while creating products by backend as well as by api. I tested with version 2.1.0

How to reproduce: Simple create two simple products with the same name in backend (or api). That's it.

**Comment by antboiko** [comment]
Hello @mage2pro , this is a correct behavior. 

URL key is autogenerated upon saving the product/category using the Name value if it's left empty. If specified (manually or autogenerated) URL key already exists the user will be notified about this after the Save. Such conflicts should be handled manually by the user.

**Comment by nomuprive** [comment]
I'm having the same issue and posted for help, but have not received any answer yet. I just don't understand why Magento 2 cannot not be programmed to automatically create a different "Category" or "Product" "URL Key" when the default "URL Key" matches an existing "URL Key", and if a different URL key has not been added manually by user? This is well done by even some basic ecommerce and CMS platform. The bigger side of it is that even when you try to add new products to an existing category the system throws the same error, ""URL key for specified store already exists." So do we have to manually enter a new "URL Key" each time we want to create/ move a category or product?

In my case, even manually adding a different "URL Key" does not work. I still get error, ""URL key for specified store already exists." when saving/ moving a category. I think if a fix is not on the way this is too much left for users to handle or deal with.

Any help would be appreciated.

Thanks!

**Comment by andimov** [comment]
@mage2pro
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

@williambize 
Thank you for reporting https://github.com/magento/magento2/issues/5792
We will process your ticket by our workflow.

**Comment by sv63rus** [comment]
I confirm, is still present in 2.1.5. Let's create the module itself correct? Magento Developers  apparently do not want to fix it ever. ))

**Comment by sv63rus** [comment]
I confirm, is still present in 2.1.5. 

I do not know exactly how to reproduce it, but the fact is that the renamed categories in the urlrievrite table still have old records. As it turned out that the two categories had the same urlkey
