### ISSUE TITLE
Framework Search/suggest offset is wrong

### ISSUE THREAD

**Issue by robdevmen** [magento/magento2#23685]
### Preconditions (*)
1. Magento 2.3.2 
2. Use default MySql indexing and search adapter

### Steps to reproduce (*)
1. Do a autocomplete/suggest search that has less than 5 results

### Expected result (*)
1. Show the results of the search query

### Actual result (*)
1. Empty result set 

### Solution 

class : Magento\Framework\Search\Search
line 72 :         
$this->requestBuilder->setFrom($searchCriteria->getCurrentPage() * $searchCriteria->getPageSize());

because of this the offset in the resulting query starts at 5 

Should be : 
$this->requestBuilder->setFrom( ($searchCriteria->getCurrentPage() - 1) * $searchCriteria->getPageSize());

**Comment by engcom-Bravo** [comment]
Hi @robdevmen . I can't reproduce this issue on vanila 2.3-develop and on 2.3.2. My search works fine. Can you add more details?
