### ISSUE TITLE
upgrade from 2.2.2 to 2.3.2, Cannot add foreign key constraint

### ISSUE THREAD

**Issue by fohnbit** [magento/magento2#23689]
### Preconditions (*)
1. Magento 2.2.2 copied to a local webserver and update to 2.3.2

### Steps to reproduce (*)
1. after composer update I start "bin/magento setup:upgrade"

### Actual result (*)
I get this error:
Cache cleared successfully
File system cleanup:
/var/www/html/generated/code/Composer
/var/www/html/generated/code/Firebear
/var/www/html/generated/code/Iazel
/var/www/html/generated/code/MSP
/var/www/html/generated/code/Magento
/var/www/html/generated/code/Mageplaza
/var/www/html/generated/code/Symfony
The directory '/var/www/html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint, query was: ALTER TABLE `quote_item` MODIFY COLUMN `item_id` int(10) UNSIGNED NOT NULL  AUTO_INCREMENT COMMENT "Item Id", MODIFY COLUMN `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "Updated At", MODIFY COLUMN `discount_amount` decimal(20, 4)  NULL DEFAULT 0 COMMENT "Discount Amount", MODIFY COLUMN `base_discount_amount` decimal(20, 4)  NULL DEFAULT 0 COMMENT "Base Discount Amount", MODIFY COLUMN `tax_amount` decimal(20, 4)  NULL DEFAULT 0 COMMENT "Tax Amount", MODIFY COLUMN `base_tax_amount` decimal(20, 4)  NULL DEFAULT 0 COMMENT "Base Tax Amount", MODIFY COLUMN `row_total` decimal(20, 4)  NOT NULL DEFAULT 0 COMMENT "Row Total", MODIFY COLUMN `base_row_total` decimal(20, 4)  NOT NULL DEFAULT 0 COMMENT "Base Row Total", MODIFY COLUMN `row_total_with_discount` decimal(20, 4)  NULL DEFAULT 0 COMMENT "Row Total With Discount", MODIFY COLUMN `base_tax_before_discount` decimal(20, 4)  NULL  COMMENT "Base Tax Before Discount", MODIFY COLUMN `tax_before_discount` decimal(20, 4)  NULL  COMMENT "Tax Before Discount", MODIFY COLUMN `price_incl_tax` decimal(20, 4)  NULL  COMMENT "Price Incl Tax", MODIFY COLUMN `base_price_incl_tax` decimal(20, 4)  NULL  COMMENT "Base Price Incl Tax", MODIFY COLUMN `row_total_incl_tax` decimal(20, 4)  NULL  COMMENT "Row Total Incl Tax", MODIFY COLUMN `base_row_total_incl_tax` decimal(20, 4)  NULL  COMMENT "Base Row Total Incl Tax", MODIFY COLUMN `discount_tax_compensation_amount` decimal(20, 4)  NULL  COMMENT "Discount Tax Compensation Amount", MODIFY COLUMN `base_discount_tax_compensation_amount` decimal(20, 4)  NULL  COMMENT "Base Discount Tax Compensation Amount", ADD CONSTRAINT  PRIMARY KEY (`item_id`), ADD CONSTRAINT `QUOTE_ITEM_PARENT_ITEM_ID_QUOTE_ITEM_ITEM_ID` FOREIGN KEY (`parent_item_id`) REFERENCES `quote_item` (`item_id`)  ON DELETE CASCADE, ADD CONSTRAINT `QUOTE_ITEM_QUOTE_ID_QUOTE_ENTITY_ID` FOREIGN KEY (`quote_id`) REFERENCES `quote` (`entity_id`)  ON DELETE CASCADE, ADD CONSTRAINT `QUOTE_ITEM_STORE_ID_STORE_STORE_ID` FOREIGN KEY (`store_id`) REFERENCES `store` (`store_id`)  ON DELETE SET NULL, ADD INDEX `QUOTE_ITEM_PARENT_ITEM_ID` (`parent_item_id`), ADD INDEX `QUOTE_ITEM_PRODUCT_ID` (`product_id`), ADD INDEX `QUOTE_ITEM_QUOTE_ID` (`quote_id`), ADD INDEX `QUOTE_ITEM_STORE_ID` (`store_id`)

**Comment by fohnbit** [comment]
Hello,

When I copy the query in myPhpAdmin, I get the error at:
ADD CONSTRAINT **PRIMARY** KEY 
This option conflicts with Constraint (near Primary key).

How can I fix this? Is there a update SQl query wrong in 2.3.2?

**Comment by shikhamis11** [comment]
hello @fohnbit 
for upgrading to magento 2 you can follow magento dev-docs guidelines
https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html

also you can discuss issue on [magento stack exchange](https://magento.stackexchange.com/) and  [community forums](https://community.magento.com/)
