### ISSUE TITLE
Activating B2B company account does not send company admin email with password link

### ISSUE THREAD

**Issue by mattment** [magento/magento2#23683]
### Preconditions (*)

1. 2.3.2 Commerce

### Steps to reproduce (*)

1. Set Company accounts to "Pending Approval" by default. 
2. Sign up with company account.
3. Approve company account within admin area.
4. Company admin gets email about account approval but can't then use the account or login

### Expected result (*)

1. Company account admin should get an email with a link to set password so they can login via the frontend.

### Actual result (*)

1. Company admin gets email saying account is now active but no where to set account password.

**Comment by mattment** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mattment. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mattment, here is your [Magento instance](https://i-23683-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23683-2-3-develop.instances.magento-community.engineering/admin](https://i-23683-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @mattment ! Thank you for you report !
I have tried to reproduce this issue but unfortunately i was not able to do it . I`m closing this for now but feel free to reopen in case you can confirm that issue is reproducible and add some extra information/screenshots.
Thanks in advance !
