### ISSUE TITLE
UI component events: observable name limitations

### ISSUE THREAD

**Issue by neillrobson** [magento/magento2#23691]
### Summary

In Magento's event implementation for Javascript UI components, one capability of event registration is creating a handler for a Knockout observable variable simply by passing the variable's qualified name to the `on` function. However, the internal `addHandler` utility function within `events.js` looks for this observable variable using array notation (checking the type of the value at `obj[name]` where `name` is the string identifier). This strategy works if the variable identifier is a single variable name (such as `myVariable`), but not if the identifier includes a dereference (such as `myDataContainer.myProperty`). In the latter case, the variable will not be found and the event will be registered without connection to the intended variable.

The relevant line of code is here:

https://github.com/magento/magento2/blob/d200ae8e6cd23372bf66c5fc93bb10da698ae121/app/code/Magento/Ui/view/base/web/js/lib/core/events.js#L47

### Examples

I do not have a development environment readily available, but I believe that this JS component would reproduce the issue:

```javascript
require([
    'ko',
    'uiElement'
], function (
    ko,
    Element
) {
    'use strict';

    return Element.extend({
        defaults: {
            myVariable: ko.observable(127),
            myDataObject: {
                myProperty: ko.observable(255)
            }
        },

        initialize: function () {
            this._super();

            this.on('myVariable', this.updateMyVariable);
            this.on('myDataObject.myProperty', this.updateMyProperty);

            return this;
        },

        updateMyVariable: function (value) {
            console.log("myVariable set to: " + value);
        },

        updateMyProperty: function (value) {
            console.log("myProperty set to: " + value);
        }
    });
});
```

Instantiating that component and changing the values of `myVariable` and `myProperty` in the browser console would only log the change of `myVariable`.

### Proposed solution

I don't know if this behavior (supporting nested variables in event names) is even desired or considered necessary. Personally, in my development I just restructured my variables to avoid the issue, and perhaps the use of complex objects in JS component `defaults` is considered a bad practice. In that case, I would recommend some form of **documentation update** describing this practice (and associated limitation).

**Comment by neillrobson** [comment]
@magento give me 2.3-develop instance

For the purpose of reproducing this bug, I will attempt to re-create the faulty UI component within the JS console of a vanilla Magento instance.

**Comment by magento-engcom-team** [comment]
Hi @neillrobson. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @neillrobson, here is your [Magento instance](https://i-23691-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23691-2-3-develop.instances.magento-community.engineering/admin](https://i-23691-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Nazar65** [comment]
Hi @neillrobson , why you use `on `? and not `.subscribe` ?

```
 this.myDataObject.myProperty.subscribe(function () {
                //do the magic
            }, this);
```

**Comment by neillrobson** [comment]
It has been a few months since I wrote this issue, and I do not have a Magento instance around to test at the moment. However, if I remember correctly, the `on` function is equipped specially in `events.js` to hook into Knockout's data binding system, which is the functionality that I intended to reach in the first place. The `subscribe` function may register a standard callback, but it requires a direct reference to the property in question (through the dot operator) rather than a string that can be resolved later (after dependency injection, etc). 

Again, I could be mistaken in my analysis at this point, because I haven't looked at Magento in a few months.

**Comment by Nazar65** [comment]
@neillrobson https://devdocs.magento.com/page-builder/docs/reference/events.html

**Comment by neillrobson** [comment]
@Nazar65 That documentation looks promising, but it seems specific to Magento's (relatively) new Page Builder module. If the `Magento_PageBuilder/js/events` component is the new standard for UI component event handling, then it could well be that this issue is resolved. Unfortunately, I myself am not an active Magento developer at the moment, so I cannot offer more specific insights into the system's limitations or architecture.

One way or another, it seems that Magento has workarounds for the problem that I identified in the original issue post. I would be comfortable closing this issue, so long as it remains online as public documentation for the current best practice.

Thanks for your help!

**Comment by engcom-Charlie** [comment]
Hello everyone! 
I am closing this issue per @neillrobson https://github.com/magento/magento2/issues/23691#issuecomment-544480687 ( Magento has workarounds for it).

Thanks everyone for contribution and collaboration!
