### ISSUE TITLE
Magento 2.3.2 Venus Megamenu problem

### ISSUE THREAD

**Issue by Goldstar215** [magento/magento2#23696]
### Summary (*)
I am upgrading Magento version from 2.2.7 to 2.3.2.
I have installed Magento 2.3.2 on my local.
Then I have installed Theme, Modules and migrated database from live server.
All Theme features work fine, but only Venus Megamenu doesn't work.
In admin panel, I can see menu items and Ves_Megamenu module already enabled.
But in frontend, I can't see menu items.

**Comment by Nazar65** [comment]
Hi @Goldstar215 i think you probably need to contact to "Venus" support, as this bug not related to magento.

**Comment by Goldstar215** [comment]
Hi @Nazar65 thanks for your answer.
I have already contacted to them, but they ask "Have you bought our extension?" first.
And they require their license.
But I work for my client and hard to contact to him now.
Could you please help me?
I am checking code, but didn't found the reason yet.

Thanks again!
Regards!!!

**Comment by Goldstar215** [comment]
Hi @hostep Could you please help me?

**Comment by hostep** [comment]
Hi @Goldstar215, unfortunately Github isn't meant for support requests. I agree with @Nazar65 in that you should contact the vendor. Try to find the license from your client and tell him/her you can't proceed with fixing the issue if you haven't received it.

**Comment by Goldstar215** [comment]
Hi @hostep, could you please accept me on Skype?
I have sent request to you.
