### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by shravan148** [magento/magento2#23700]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by shravan148** [comment]
![city](https://user-images.githubusercontent.com/46593382/61199320-263c5100-a6fb-11e9-9e60-716f4ed31d28.PNG)
i have restored the checkout_index_index.xml to stock magento.. now the problem there is two city field coming in checkout.

**Comment by krishprakash** [comment]
@shravan148 
Please follow issue reporting guideline to report an issue with all issue reproducible steps.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks.

**Comment by krishprakash** [comment]
Hi @shravan148,
Please feel free to reopen if you confirm that issue is reproduce on vanilla magento instace with proper issue format.
Thanks.
