### ISSUE TITLE
A PHPDoc comment for \Magento\Config\Model\Config\SourceFactory::create() method is wrong

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2370]
https://github.com/magento/magento2/blob/2335247d4ae2dc1e0728ee73022b0a244ccd7f4c/app/code/Magento/Config/Model/Config/SourceFactory.php#L26

Should be «`Create source model by name`».

The PHPDoc declaration for result can be improved too:
https://github.com/magento/magento2/blob/2335247d4ae2dc1e0728ee73022b0a244ccd7f4c/app/code/Magento/Config/Model/Config/SourceFactory.php#L29
`@return \Magento\Framework\Option\ArrayInterface|object`
would be better.

**Comment by joanhe** [comment]
@dfediuk Thank you for reporting this issue. Internal issue MAGETWO-45625 is created for this.

**Comment by okorshenko** [comment]
@madotto

**Comment by okorshenko** [comment]
@dmitry-fedyuk thank you for reporting the issue.
@cavalier79 thank you for fixing this issue in PR: magento/magento2#8758
