### ISSUE TITLE
Css selector [role="button"] in related products javascript is not specific enough

### ISSUE THREAD

**Issue by enr-beck** [magento/magento2#23705]
### Preconditions (*)
1. Magento 2.3.2
2. PHP 7.1.26
3. MySQL 5.7.25

### Steps to reproduce (*)
1. Open product detail page with related products (e.g. http://demoshops.splendid-internet.de/magento/demoshop-magento2-daily/olivia-1-4-zip-light-jacket.html)
2. Click on "Add to wishlist" or "Compare" icon of a related product

### Expected result (*)
1. Text "Unselect all" should not get appended to the html element of the clicked icon

### Actual result (*)
1. Text "Unselect all" gets appended to html element of clicked icon

### Cause of this error
In the following commit the css selector for the related products functionality was changed from [role="select-all"] to [role="button"]
https://github.com/magento/magento2/commit/679d8a542dedf330ee899332fd46a7d701c44071

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18206` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @enr-beck. Thank you for your report. 
The issue has been fixed in magento/magento2#23774 by @konarshankar07 in 2.3-develop branch
Related commit(s):
 - [3bac25f1dad11f6d48dac6880016d71254c395bf](https://github.com/magento/magento2/commit/3bac25f1dad11f6d48dac6880016d71254c395bf)

The fix will be available with the upcoming 2.3.4 release.
