### ISSUE TITLE
After upgrading from 2.1.0 to 2.3.2, bin/magento commands throwing exception

### ISSUE THREAD

**Issue by Jehangir-Wahid** [magento/magento2#23701]
### Preconditions (*)

I am using Ubuntu 18.04, on my local machine, with the following requirements for Magento.

1.    **Apache 2.4.29**
2.    **Php 7.1.30**
3.    **Composer 1.6.1**
4.    **MySQL 5.7.26**

I am facing the exception mentioned below in the **Actual result** section.

### Steps to reproduce (*)

I have upgraded Magento, from 2.1.0 (Community Edition) to 2.3.2 (Open Source), for my project on my local machine using the steps mentioned [here](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html).

On [Update metadata](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html#update-metadata), I replaced the `/var/www/html/magento_root_dir/composer.json` with [this](https://github.com/magento/magento2/blob/2.3.2/composer.json) one.

The `composer update` command ran successfully, but after that I am trying to run `bin/magento cache:clean` or even on every `bin/magento` command, I am been prompted the exception mentioned below in **Actual result** section.

### Expected result (*)

I am expecting the normal behavior of `bin/magento` commands.

### Actual result (*)

Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for Magento\Setup\Mvc\Bootstrap\InitParamListener#0 /var/www/html/magento_root_dir/vendor/zendframework/zend-mvc/src/Application.php(156): Zend\ServiceManager\ServiceManager->get('Magento\\Setup\\M...')
#1 /var/www/html/magento_root_dir/vendor/zendframework/zend-mvc/src/Application.php(281): Zend\Mvc\Application->bootstrap(Array)
#2 /var/www/html/magento_root_dir/lib/internal/Magento/Framework/Console/Cli.php(57): Zend\Mvc\Application::init(Array)
#3 /var/www/html/magento_root_dir/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#4 {main}

PHP Fatal error:  Uncaught Error: Class 'Cli' not found in /var/www/html/magento_root_dir/bin/magento:31
Stack trace:
#0 {main}
  thrown in /var/www/html/magento_root_dir/bin/magento on line 31

**Comment by Jehangir-Wahid** [comment]
I haven't tried to reproduce this issue on vanilla Magento instance.

**Comment by engcom-Bravo** [comment]
Hi, @Jehangir-Wahid . I have one question for you: 
how did you install 2.1.0 version of magento if you have 7.1.30 php version? 
This version does not support PHP 7.1.30. 
I think the PHP version is affecting this problem(wrong update).
![222](https://user-images.githubusercontent.com/51680745/61290433-8eab3100-a7d4-11e9-98b5-2bb5c0c4454a.png)

**Comment by Jehangir-Wahid** [comment]
Hi @engcom-Bravo,
Yes, you are right. But, I have installed Magento 2.1.0 on php7.0.2 and then for upgrading Magento to 2.3.2, I installed php7.1.30.

**Comment by engcom-Bravo** [comment]
@Jehangir-Wahid , unfortunately the 2.1.x branches is already closed. We do not work with such issue.
Thank you for your report!

**Comment by hostep** [comment]
@engcom-Bravo: issue report was for Magento 2.3.2 😉

But not reopening as this seems to be something which went wrong in the upgrade.

@Jehangir-Wahid: could it be that your `bin/magento` file is still the [old one](https://github.com/magento/magento2/blob/2.1.0/bin/magento) and not the [new one](https://github.com/magento/magento2/blob/2.3.2/bin/magento)?

In that case, you'll need to figure out why exactly that file isn't being updated, what you could try is removing your entire `vendor` directory and run `composer install` and after that check if the `bin/magento` file is now updated.
If that still doesn't resolve it, check if the file `vendor/magento/magento2-base/bin/magento` is correct. If this one is correct and `bin/magento` is not correct, then you have a problem where that first file isn't being copied to the second file, which should normally happen during `composer install`. But figuring out where that goes wrong might be somewhat complicated.

Anyways, good luck!
