### ISSUE TITLE
Category doesn't work after setup:upgrade

### ISSUE THREAD

**Issue by Goldstar215** [magento/magento2#23709]
### Preconditions (*)

1. Magento version 2.3.2
2. Environment: Windows/Xampp

### Steps to reproduce (*)

1. in Magento root folder, run command php bin/magento setup:upgrade
2. php bin/magento indexer:reindex

### Expected result (*)

1. Catalog url rewrite works well.
2. Category names should be shown in admin/category edit page.

### Actual result (*)

1. Category names show in homepage, but url rewrite doesn't work only for category.
2. Other url rewrites(cms page, product) work well.
3. In category edit page, I can't see category name and other category datas.

**Comment by engcom-Bravo** [comment]
Hi,@Goldstar215 ! I can't reproduce this issue on vanila magento 2.3.2 and on 2.3-develop.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
Thanks!
