### ISSUE TITLE
Google Tag Manager: JavaScript Issue in HEAD [2.3.1]

### ISSUE THREAD

**Issue by erickamoedo** [magento/magento2#23708]
### Preconditions (*)

1. Magento Open Source version 2.3.1
2. PHP 7.2 

### Steps to reproduce (*)

I add GTM without third-party extensions

1.  Put the GTM snippet into these two phtml templates for head and body

2. Script to head
 ```
// YourTheme/Magento_Theme/templates/html/gtm_head.phtml
<script>..</script> <!-- GTM code -->
```

3. Script to body
```
// YourTheme/Magento_Theme/templates/html/gtm_body.phtml
<noscript>..</noscript> <!-- GTM code -->
```

4. To load the files correspondingly i use the default .xml file:

```
<!-- YourTheme/Magento_Theme/layout/default.xml -->
<referenceContainer name="head.additional">
<block class="Magento\Framework\View\Element\Template" name="gtm.head" before="-" template="Magento_Theme::html/gtm_head.phtml" />
</referenceContainer>

```
```
<referenceContainer name="after.body.start">
<block class="Magento\Framework\View\Element\Template" name="gtm.body" before="-" template="Magento_Theme::html/gtm_body.phtml" />
</referenceContainer>

```
### Expected result (*)

1. After GTM is added you can check the Google Tag Assistant to see if its right installed. If you see a Tag green it's perfect and working.
![download](https://user-images.githubusercontent.com/8376149/61227699-2ccac880-a6fb-11e9-9428-89fc723a0822.png)

### Actual result (*)

1. GTM JavaScript code not found as a direct child of the <head> tag

![Error](https://user-images.githubusercontent.com/8376149/61227879-8df29c00-a6fb-11e9-9b5c-be12f91ba7ba.jpg)

And when i will inspect the code, i don't see the script:

![lom-IGmvDVriHRyp5rdj9w](https://user-images.githubusercontent.com/8376149/61227913-a5ca2000-a6fb-11e9-9172-209ed643e722.png)

**Comment by erickamoedo** [comment]
> Hi @erickamoedo. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @erickamoedo do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [x]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @erickamoedo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @erickamoedo, here is your [Magento instance](https://i-23708-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23708-2-3-develop.instances.magento-community.engineering/admin](https://i-23708-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18205` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by NickvdMeij** [comment]
This is actually Magento protecting you I believe. For more info about using JS in Magento, look here: https://www.ryanmpoe.com/post/requirejs-and-magento-2/

**Comment by DmitryPirvu** [comment]
Hey there
Could be closed as not an issue.
Regards,
Dmitry.

**Comment by ventureonerealty** [comment]
hi

i want connect google tag manager to my website https://ventureonerealtyllc.com/ , after creating google tag manager account i copied code to header.php


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-BZZSQ00');</script>

</head>

<?php
$object_id      = get_queried_object_id();
$c_page_id      = Avada()->fusion_library->get_page_id();
$wrapper_class  = 'fusion-wrapper';
$wrapper_class .= ( is_page_template( 'blank.php' ) ) ? ' wrapper_blank' : '';
?>
<body <?php body_class(); ?> <?php fusion_element_attributes( 'body' ); ?>>
	
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-BZZSQ00"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>


I put it correctly to header.ph file but i got error through tag assistant google chrom extension

GTM JavaScript code not found as a direct child of the <head> tag

please sombody help  what can i do??

thank you
