### ISSUE TITLE
The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by josiahglassone** [magento/magento2#23712]
### Summary (*)
I have been working on connecting Magento 2 to Shipworks (3rd party shipping software) via their module and Rest API. Both attempts have returned an error saying 

> The remote server returned an error: (401) Unauthorized.

 I've worked with the Shipworks support and concluded that the issue is not with their software but with my setup.
Additionally I have PayPal Pro setup to allow me to take Debit/Credit card on the website without opening their virtual terminal and it is also returning an unauthorized message.
All the users currently have full admin privileges. The server has the default suggested permissions 755-folders 644-files. There are no server errors or exception or system log errors.
When the error was traced in Shipworks it returned

> {"message":"The consumer isn't authorized to access %resources.","parameters":{"resources":"Magento_Sales::actions_view"},"trace":"#0 /home/buyglasswoodstov/public_html/vendor/magento/module-webapi/Controller/Rest/RequestValidator.php(68):

What could be causing these authentication issues? I've been researching and working on this issue for 3 weeks.

### Preconditions(*)
Magento 2.3.1
Php 7.2

**Comment by engcom-Charlie** [comment]
Hello @josiahglassone ! Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
