### ISSUE TITLE
Date Time Format in Backend Order list

### ISSUE THREAD

**Issue by chequille** [magento/magento2#23713]
Sorry, why there is no way to change date time format for the orders list view (as well shipment and incoice and all others ...) in the backend. Picture shows what I mean:

![datetime](https://user-images.githubusercontent.com/15807794/61247539-95dd2b00-a751-11e9-842a-c125c52862a1.PNG)

I want to have written there the german format like 29. Juni 09:56:44

Is there a way t do it?

Please advise.

BR
Chequille

**Comment by chequille** [comment]
Yes, I can confirm  this is in vanilla Magento instance the same.
Becuase I found, that this format is hard coded in magento-ui module class \component\filters\type\Date.php and DateRange.php and as well in \component\listing\Colmns\Date.php.

So ias far as I see no way to change this.

Is there any plan to change this in the future to be able to have the same date format all over all parts of Magento?

BR
Chequille

**Comment by krishprakash** [comment]
Hi @chequille. Thank you for your report.
This is default magento issue which is already reported earlier #23113
So I'm closing this as duplicate issue.
You can also refer [Community Forums](https://community.magento.com/) or [ Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
