### ISSUE TITLE
Magento 2 ignores XML schema location in the etc/adminhtml/system.xml documents and always uses the Magento/Config/etc/system_file.xsd schema instead

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2372]
https://mage2.pro/t/213

**Comment by joanhe** [comment]
@dfediuk Thank you for reporting this issue. Internal issue MAGETWO-45613 is created to investigate this issue.

**Comment by dsikkema-magento** [comment]
For system.xml files, an alternative XSD file may not be used. The URN in system.xml exists to document which XSD is being used
