### ISSUE TITLE
Redis Clarifications and Cache Flush 

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#23727]
### Summary (*)

I am using Redis in my magento 2.3 setup and all works ok. I need some clarification regarding a few things and am not finding answers anywhere that satisfy me.

1.  Does cache:flush clear REDIS.  If so, how do you avoid having it flush out sessions as well?  I already have separate databases, but if cache:flush is essentially doing the same as redis-cli flushall then separate databases don't help.

2. Regarding Redis as a page cache. It seems everyone does this, adding redis as a page cache in env.php, but what is the actual point if we are already setup using Varnish for full page cache.  Are they redundant, or are they actually caching different things?  I see no clarification in magento devdocs explaining this.

### Examples (*)

See above

### Proposed solution

To include more detailed information in the devdocs

**Comment by engcom-Bravo** [comment]
Hi, @snoroozi. 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

**Comment by hostep** [comment]
Hi @snoroozi: you'd probably best want to open an issue on https://github.com/magento/devdocs/issues for this if you want to see better explanation of this in the documentation. Since that's the repo for the documentation.
