### ISSUE TITLE
Ves_BaseWidget not working after upgrade from 2.2.7 to 2.3.2

### ISSUE THREAD

**Issue by Goldstar215** [magento/magento2#23726]
### Summary (*)

I have upgrade Magento version from 2.2.7 to 2.3.2
After upgrade, Ves_BaseWidget module doesn't work.
It shows 2 console errors.
The issue is TinyMCE(Wysiwyg Setup) issue.
And in admin panel, all Wysiwyg editors not working.

**Comment by engcom-Charlie** [comment]
Hello @Goldstar215 ! Thank you for your report !
I was not able to reproduce this issue on Vanilla Magento instance . The GitHub issue tracker is intended for Magento Core technical issues only. Problem that you describe is with 3rd party module/extension. Please refer to the Community Forums or the Magento Stack Exchange, for advice or general discussion about this issue.
Thanks !
