### ISSUE TITLE
\Magento\Framework\Config\Reader\Filesystem::_createConfigMerger() uses the «new» keyword instead of the Object Manager even after the Object Manager has already been initialized, so it breaks a dependency injection possibility

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2373]
https://mage2.pro/t/214

**Comment by vzabaznov** [comment]
To allow us research the issue, please, provide description according to the template.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
