### ISSUE TITLE
Bad style on Validate VAT number messages

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23738]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Stores->Configuration->General
2. Scroll to Store Information
3. Click "Validate VAT number" with empty information. 
- Fill the correct VAT number with the country. Click "Validate VAT number"

### Expected result (*)

1. The error message should be red.
2. The success message should be green.

### Actual result (*)

Both messages are same color.
1. 
![image](https://user-images.githubusercontent.com/8234209/61343452-ffeff000-a877-11e9-8e6c-0661b46161fe.png)

2. 
![image](https://user-images.githubusercontent.com/8234209/61343441-f5cdf180-a877-11e9-88b6-0fcf75cf04c0.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23738-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23738-2-3-develop.instances.magento-community.engineering/admin](https://i-23738-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23738-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23738-2-3-develop.instances.magento-community.engineering/admin](https://i-23738-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18220` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23739 by @edenduong in 2.3-develop branch
Related commit(s):
 - [d8b4d828f5d9e8d5bea3e64b46c2845544865f89](https://github.com/magento/magento2/commit/d8b4d828f5d9e8d5bea3e64b46c2845544865f89)
 - [101a9f3521535fc100dcf0ea9e684a307f3be6f4](https://github.com/magento/magento2/commit/101a9f3521535fc100dcf0ea9e684a307f3be6f4)

The fix will be available with the upcoming 2.3.4 release.
