### ISSUE TITLE
Change catalog_category_view.xml to 1column return zero products with elastic search on 2.3.2

### ISSUE THREAD

**Issue by ron-jomashop** [magento/magento2#23736]
### Preconditions (*)

1. Magento 2.3.2
2. Enabled elastic search 2

### Steps to reproduce (*)

1. Extend catalog_category_view.xml to 1column in a new theme
2. Enable elastic search 2
3. Reindex all indexes
4. Go to any category pages and it will not show any products

### Expected result (*)

1. Should have products

### Actual result (*)

1. It does not have any products showing

**Comment by ron-jomashop** [comment]
I cannot reproduce this in Magento 2 instance because this requires change of the theme and enable elastic search.

**Comment by engcom-Bravo** [comment]
Hi, @ron-jomashop ! I can't reproduce this issue on fresh 2.3-develop branch.

**Manual testing scenario:**
1.Extend catalog_category_view.xml to 1column in a luma theme
2.Enable elastic search 2
3.Reindex all indexes
4.Cache flush
5.Go to any category pages 

If in your case used custom theme please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

Thank for your report!

**Comment by ron-jomashop** [comment]
Can you show me an image with 1 column category page working in your local? Because I have tested with Magento 2.3.2 repository and it does not work.

With 2 column:
![Capture](https://user-images.githubusercontent.com/40342628/61385961-64637d00-a881-11e9-8ec8-c6356c20dcc5.PNG)

With 1 column:
![Capture](https://user-images.githubusercontent.com/40342628/61386138-b73d3480-a881-11e9-87fc-958446bd6bcc.PNG)

**Comment by ron-jomashop** [comment]
@engcom-Bravo All you need is to enable the category to 1 column with elasticsearch 2 enable and it should reproduce the bug.

**Comment by engcom-Bravo** [comment]
@ron-jomashop 
I did it on 2.3.2 and the result is the same as on 2.3-develop:
**With 2 column:**
![column2](https://user-images.githubusercontent.com/51680745/61438333-e4541a80-a947-11e9-9f0b-da49cfb34810.png)

**With 1 column:**
Page is blank(no any exceptions and errors):
![column1](https://user-images.githubusercontent.com/51680745/61438351-eddd8280-a947-11e9-9164-f2ad2fef1b29.png)

**Comment by engcom-Bravo** [comment]
@ron-jomashop okay, i don't like this behavior and i confirm this issue.
Thank for contributing!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18255` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
Since this issue was confirmed, I think the status should be Open instead of Closed, right?

**Comment by hostep** [comment]
@engcom-Bravo: can you add those labels again which got automatically removed?

**Comment by engcom-Bravo** [comment]
@hostep , thanks for contributing! that was my mistake.

**Comment by ron-jomashop** [comment]
> @ron-jomashop okay, i don't like this behavior and i confirm this issue.
> Thank for contributing!

Thanks for rechecking. The elastic search does have many bugs currently. I have some patches in order to make it work that's why I can bypass the blank page.

**Comment by ghost** [comment]
I think this issue is fixed since I am not able to reproduce it then why it is still in open state

**Comment by sedax90** [comment]
I've the same problem on 2.3.3... issue is still open

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-18255, MC-23842` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
