### ISSUE TITLE
Credit memo email sent to other customers

### ISSUE THREAD

**Issue by nathanjhastings** [magento/magento2#23745]
### Preconditions (*)

1. 2.3.1

### Steps to reproduce (*)

1. Customer orders product
2. Customer Pays via PayPal successfully
3. Merchant refunds order via PayPal
4. A credit note is automatically generated by Magento

### Expected result (*)

1. Email is sent to the customers who placed the orders in TO field.

### Actual result (*)

1. Email is sent to last 28 customers who have placed orders in TO field. These customers are not related to this order.

![Screenshot 2019-07-17 at 14 47 36](https://user-images.githubusercontent.com/6231100/61381039-5eca5f00-a8a2-11e9-9e7e-e62b4856007a.png)

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23745-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23745-2-3-develop.instances.magento-community.engineering/admin](https://i-23745-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @nathanjhastings ! Thank you for your report !
I was not able to reproduce this issue on Vanilla Magento 2.3-develop instance . Can you provide some extra information or steps how to reproduce this issue ? 
Feel free to reopen it in case you want to describe this issue more detailed

Thanks for collaboration !

![Screenshot from 2019-07-19 12-44-38](https://user-images.githubusercontent.com/51680850/61527547-62d2ba00-aa25-11e9-91da-8a12c5815426.jpg)

**Comment by nathanjhastings** [comment]
Hi @engcom-Charlie,

Thanks for looking into this for us!

Our issue is related to the issue of a credit memo email, your screenshot is of an order confirmation email. We have not had any problems with order confirmation emails (they are only sent to the correct customers).

To properly test from a vanilla installation I would suggest the following steps:
Successfully order a product as one customer
Successfully order a product via PayPal as a different customer with a different email address
In PayPal, refund the second order
Magento should issue a credit memo email, Check credit memo to addresses

**Comment by engcom-Charlie** [comment]
@ Hi. @nathanjhastings . I tested it again(on fresh 2.3-develop) with your scenario and second credit memo email was sent to email of second customer.
