### ISSUE TITLE
Field "Billing ZIP Code" shows and disappears immediately in "Orders and Returns" form

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23746]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to http://[Magento 2 Domain]/sales/guest/form/
2. See the form

### Expected result (*)

1. Field "Billing ZIP Code" is hiddened.

### Actual result (*)

1. Field "Billing ZIP Code" shows and disappears immediately

See:

![bug](https://user-images.githubusercontent.com/8234209/61381636-8be43500-a8d5-11e9-99d7-2e7bb88c604b.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18838` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
