### ISSUE TITLE
Payment method (Authorise.net) is not display in order (admin side).

### ISSUE THREAD

**Issue by pandyakrunal** [magento/magento2#23758]
I Migrate the site in Magento 2.3.2 all works fine but when open the order in admin side another payment method is display but Authorise.net payment method is not showing.
![image](https://user-images.githubusercontent.com/39430090/61434706-4b77cc00-a954-11e9-8207-428762ed8a0e.png)

### Preconditions (*)

1.Magento 2.3.2
2.Authorise.net method does not display in admin order edit.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by ktpl-rammohan** [comment]
@pandyakrunal Could to please provide us the clear steps to reproduce the issue

**Comment by pandyakrunal** [comment]
Actually, Data is different (Magento 1 response data is different and Magento response data is different). so Condition is not fulfilled that's why it not display.

**Comment by ktpl-rammohan** [comment]
@pandyakrunal Thankyou.

**Comment by pardyalbert** [comment]
Checks should be made before moving it from QA to Done
