### ISSUE TITLE
magento2-updater dose not exist!!!!

### ISSUE THREAD

**Issue by farhadniaz** [magento/magento2#23756]

**Comment by ajijshekh123** [comment]
@farhadniaz - Please follow issue-reporting guideline to report an issue with all issue reproducible steps.
**https://github.com/magento/magento2/wiki/Issue-reporting-guidelines**

Thanks.

**Comment by ajijshekh123** [comment]
@farhadniaz - feel free to reopen this issue when you will be ready to provide more details and we will review it and confirm it.
