### ISSUE TITLE
Incorrect 'Details' link in the Blocks grid in the backend

### ISSUE THREAD

**Issue by hostep** [magento/magento2#2375]
Hi

Using Magento 2.0.0-rc2.

If you go to the Content => Blocks grid in the backend, inside the Actions column, there is a 'Details' link which is incorrect. It redirects you to the dashboard. I don't know what's the purpose of this link? Shouldn't it be removed?

**Comment by shiftedreality** [comment]
Hi @hostep 

We have internal ticket for your issue MAGETWO-44966

**Comment by hostep** [comment]
This is most likely fixed by now, as being reported in https://github.com/magento/magento2/issues/2483 & https://github.com/magento/magento2/issues/3078, so closing this super old issue :)
