### ISSUE TITLE
Inline editing for CMS grids is a bit frustrating

### ISSUE THREAD

**Issue by hostep** [magento/magento2#2376]
Hi

Using Magento 2.0.0-rc2.

I currently find it hard to edit a static block or cms page. We are now obligated to click at least twice on a tiny target, or even more then that if you make the mistake of clicking into a column which isn't the action column, due to the inline editing feature opening up.
I can see the usefulness of inline editing when clicking on a row, but now it's becoming a bit harder to actually edit the contents of the page/block.
I think in 80% of the cases when someone goes to the blocks/pages grid, it is to edit the contents of that block/page, not to change the title or the status or something like that.

Here are some ideas to make it a bit more practical while keeping the inline editing feature:
1. Split the actions into multiple columns, so you can click directly on 'Edit'
2. Clicking on a column in a row which you can't edit inline (ID, created/modified dates, ...) should open up the static block/page immediately
3. Add a configuration option above the grid to enable/disable the inline editing feature
4. ...

If anybody has other ideas to make this a less frustrating experience, please tune in :)

Thanks!

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Inline-editing-for-CMS-grids-is-a-bit-frustrating/idi-p/45351).
