### ISSUE TITLE
Magento Upgrade from 2.2 to 2.3.2 Issue while placing an order

### ISSUE THREAD

**Issue by moinmalek17** [magento/magento2#23769]
Hi,

I have upgraded Magento site from Magento 2.2 to 2.3.2. I have an issue with placing an order.

I checked the var/report/api/ directory. And It is showing me Call to a member function appendChild() on null in vendor\/pelago\/emogrifier\/src\/Emogrifier.php:1419.

I fixed the issue

From 
`$headElement->appendChild($styleElement);`

To 
`if($headElement){
            $headElement->appendChild($styleElement);    
        }`

Can you please check it? because I modified the file directly in the vendor folder.
Any help would be appreciated.
Thanks

**Comment by sdzhepa** [comment]
Hello @moinmalek17 

As I can see from issue description
```
And It is showing me Call to a member function appendChild() on null in vendor/pelago/emogrifier/src/Emogrifier.php:1419.
```

It is not related to Magento code because it is in `vendor/pelago/` and we cannot fix it from our side.
I would recommend reporting this issue to the extension owner.

**Comment by hostep** [comment]
This is most likely not a bug in emogrifier. I'm guessing there is probably something wrong with a custom email template @moinmalek17 is using.

@moinmalek17: the emogrifier library is used to inline css into html emails which get send out from Magento. Can you check your custom email templates if they are correct? Especially the email template which is send for new orders. This error indicates that it can't find a `<head>` element in your html email template.
Maybe try using the default email template for new orders from Magento and see if that works. If that works, then start by trying to figure out what is wrong with your custom email template.

Hope this helps 🙂

**Comment by john-ofagbe** [comment]
I had the same issue when creating a custom email template on Magento 2.3.2. as @hostep commented above, I resolved the issue by fixing a bug on my email.html template file.

**Comment by usman786cs** [comment]
I was facing same issue and it was with the custom template .......

After I change custom template file, Issue get resolved.
