### ISSUE TITLE
No auto focus in the invalid field if the fieldset collapse is closed

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23765]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Store->Configuration->Catalog->Inventory
2. Open Collapse "Product Stock Options"
3. Fill "ggggggg" into "Maximum Qty Allowed in Shopping Cart"
4. **Close** collapse "Product Stock Options" Fieldset
5. Click "Save"

### Expected result (*)

1. Validate failed and auto focus to the "Maximum Qty Allowed in Shopping Cart" fields

### Actual result (*)

1. Nothing happened, no notifcation to notify the admin

![issue_23765](https://user-images.githubusercontent.com/3409584/81409910-90e4d000-9105-11ea-8b51-836fe8cfb732.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18257` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07, here is your [Magento instance](https://i-23765-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23765-2-3-develop.instances.magento-community.engineering/admin](https://i-23765-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by konarshankar07** [comment]
Hello @edenduong 

I'm not able to reproduce this issue in the vanilla instance. Please check the below screenshot
![image](https://user-images.githubusercontent.com/39480008/61476316-637a3a80-a9aa-11e9-82d7-071359a0fdc5.png)
Thanks

**Comment by edenduong** [comment]
Hi @konarshankar07 ,
You should close the collapse “Product Stock Options” by click to label and try again. 
Thanks.
