### ISSUE TITLE
On checkout cart submit, pattern regex validation fails

### ISSUE THREAD

**Issue by vahir2016** [magento/magento2#23766]
### Preconditions (*)

1. Magento ver. 2.2.6
2.

### Steps to reproduce (*)

1. On checkout cart page, use input type text for quantity and use pattern like "[0-9]"
2. Bind jquery submit to submit form on input change
3. In broswer console, you will see : "param.test is not a function"
4. The form will not submit

` <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                           name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                           value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                           type="text"
                           size="4"
                           pattern="^(0|[1-9][0-9]*)$"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>`

`require([
            'jquery',
        ], function($) {
            $('#form-validate .input-text.qty').on('change', function() {
                console.log('here');
                $('#form-validate').submit();
            });
        });`

### Expected result (*)

1. Form submits
2.

### Actual result (*)

1. Uncaught TypeError: param.test is not a function
    at $.validator.<anonymous> (validation.js:541)
    at $.validator.check (jquery.validate.js:556)
    at $.validator.checkForm (jquery.validate.js:372)
    at $.validator.form (jquery.validate.js:359)
    at jQuery.fn.init.valid (jquery.validate.js:108)
    at $.<computed>.<computed>.isValid (validation.js:1845)
    at $.<computed>.<computed>.isValid (jquery-ui.js:402)
    at HTMLFormElement.<anonymous> (jquery-ui.js:494)
    at Function.each (jquery.js:370)
    at jQuery.fn.init.each (jquery.js:137)

![Sélection_078](https://user-images.githubusercontent.com/24229641/61444331-76a9ed80-a94b-11e9-8fa5-89bf15bedaea.png)

I fixed the problem with this solution : 
in magento/lib/web/mage/validation.js line 538

replace :

` /* eslint-enable max-len */
        'pattern': [
            function (value, element, param) {
                return this.optional(element) || param.test(value);
            },
            $.mage.__('Invalid format.')
        ],`

by
`       /* eslint-enable max-len */
        'pattern': [
            function (value, element, param) {
                return this.optional(element) || new RegExp(param).test(value);
            },
            $.mage.__('Invalid format.')
        ],`

I am doing a pull request for this.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18258` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment]
I believe this is fixed by 8488c07818215f92b073a6e6b31b38162caa7aaf
