### ISSUE TITLE
"Discount Amount" field is validated after the page load without any action from user in Create New Catalog Rule form

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23777]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. In back end, go to Marketing -> Catalog Price Rule -> Add New Rule
2. Scroll to the Action fieldset
3. See the " Discount Amount" Field

### Expected result (*)

1. Normal field without validate (because no action from User)

### Actual result (*)
1. The " Discount Amount" field is validated and show error
![image](https://user-images.githubusercontent.com/8234209/61510167-05863b00-aa1c-11e9-811a-9700d53cce23.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23777-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23777-2-3-develop.instances.magento-community.engineering/admin](https://i-23777-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23777-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23777-2-3-develop.instances.magento-community.engineering/admin](https://i-23777-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by ajijshekh123** [comment]
Without action performed, validate error message is displayed on the 'Discount Amount' field. In ' Rule Name' text field validation error message is displayed.

Expected:- If admin performs action then validate error message should be displayed.

**See attached screenshot:**

![2 3_CatalogRule](https://user-images.githubusercontent.com/24711761/61513654-72e59c00-aa1b-11e9-8463-e6c95e58a68b.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18316` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23779 by @edenduong in 2.3-develop branch
Related commit(s):
 - [4954bd1f9f80fe0d725569602a40ba5f250a4dae](https://github.com/magento/magento2/commit/4954bd1f9f80fe0d725569602a40ba5f250a4dae)

The fix will be available with the upcoming 2.3.3 release.
