### ISSUE TITLE
Rule coupon code generate form validation

### ISSUE THREAD

**Issue by Jitheesh** [magento/magento2#23778]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

Case 1: 
1. Login to Admin
2. Create new sales rule with 'Use Auto Generation' enabled 
3. save rule
4. Open 'Manage Coupon Codes' section
5. Click 'Generate' button without filling required values

case 1:
### Expected result (*)

1. Validation error messages should be displayed 

### Actual result (*)

1. Validation failed but no no error message

Case 2: 
1. Login to Admin
2. Create new sales rule with 'Use Auto Generation' enabled 
3. save rule
4. Open 'Manage Coupon Codes' section
5. Add non integer value to 'Dash Every X Characters' box
5. Click 'Generate' button 

case 2:
### Expected result (*)

1.Proper  Validation error messages should be displayed so customer can input integer value there

### Actual result (*)

1. Validation failed but no no error message

**Comment by deepakk-webkul** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar, here is your [Magento instance](https://i-23778-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23778-2-3-develop.instances.magento-community.engineering/admin](https://i-23778-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@webkul-deepakkumar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18323`, `MC-18324` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrodespin** [comment]
I have been checking this issue i am not able to reproduce it. In a clean Magento 2.3 the result of the commented steps are the expected ones, as you can see in the following pictures

Case 1:
<img width="1061" alt="Captura de pantalla 2019-10-27 a las 16 25 43" src="https://user-images.githubusercontent.com/31536387/67637011-a5364d80-f8d6-11e9-9bf0-f396fdfdc751.png">

Case 2:
<img width="1044" alt="Captura de pantalla 2019-10-27 a las 16 26 05" src="https://user-images.githubusercontent.com/31536387/67637016-aff0e280-f8d6-11e9-93d4-9aaa2f57f9dd.png">
