### ISSUE TITLE
Lots of redundant javascripts get included on setup page when you aren't logged in as admin

### ISSUE THREAD

**Issue by hostep** [magento/magento2#2377]
Hi

Using Magento 2.0.0-rc2

Not a big issue, just something I noticed.

When you navigate to http://www.yourmagentoinstallation.com/setup/ while you are not logged in as an admin user, a lot of javascript files get included which aren't necessary.
All of these js files also are linked incorrectly and result in a whole bunch 404's.

**Comment by mazhalai** [comment]
@hostep we have already fixed this. Should be available when GA is released.

**Comment by davidalger** [comment]
This is fixed in the 2.0 GA. Please re-open if issue persists.

**Comment by hostep** [comment]
Hmm, the 404's are fixed indeed, but the javascript files are still included, while they have absolutely no purpose if you aren't logged in.

I don't think it's a big deal, just want to make sure you are aware of this.
