### ISSUE TITLE
Cannot type Japanese in TinyMCE4 WYSIWYG Editor

### ISSUE THREAD

**Issue by walish** [magento/magento2#23776]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2 
3. Japanese typing software (IME - Windows, Mozc - Ubuntu)

### Steps to reproduce (*)
1. Go to admin panel, edit static block
2. Turn on Japanese typing, type in WYSIWYG

### Expected result (*)
1. Can type properly

### Actual result (*)
1. I can't type japanese properly. This issue happens with Vietnamese, Chinese too.

![New Block _ Blocks _ Elements _ Content _ Magento Admin](https://user-images.githubusercontent.com/13128541/61506620-e207c400-aa0c-11e9-9314-c29df91411c6.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18317` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by walish** [comment]
@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @walish. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @walish, here is your [Magento instance](https://i-23776-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-23776-2-3-0.instances.magento-community.engineering/admin](https://i-23776-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
Setting it as a duplicate of https://github.com/magento/magento2/issues/24637 as that issue already has some work in progress.
