### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Mail\Template\TransportBuilder\Interceptor::setFromByScope

### ISSUE THREAD

**Issue by bigbywolf-uk** [magento/magento2#23773]
### Preconditions (*)
1. Magento 2.3.2 Community
2. PHP 7.1.3
3. Ubuntu 16.04

### Steps to reproduce (*)
1. Upgrade from PHP 7.0 to 7.1
2. Upgrade from 2.2.x to 2.3.2
3. Place test order on newly updated store

### Expected result (*)
1. Get forwarded to Success page

### Actual result (*)
1. Magento shows an empty error message notice
2. Order shows up in admin panel, but customer never reaches Success page
3. No errors whatsoever in magento_root/var/log
4. Error found in /var/log/php_errors.log

Full error message here:
https://pastebin.com/UPXNdJJu

**Comment by bigbywolf-uk** [comment]
Setting
Sales -> Sales Emails -> Order -> Enabled to No resolves the issue and customer gets forwarded to Success page correctly.

**Comment by secaliskan** [comment]
So customers never get order confimation mail. This breaks default magento functionality. 
Is this the solution?

**Comment by karlsminton** [comment]
How is this closed when the issue is to disable core mail functionality?
