### ISSUE TITLE
Backend products mass action for all products only affects visible products

### ISSUE THREAD

**Issue by marvinhinz** [magento/magento2#23783]
### Preconditions (*)
1. Freshly installed Magento 2.3.2

### Steps to reproduce (*)
1. Create 25 Products with the same status (enabled or disabled)
2. Go to Backend Product Grid and make sure 20 per page is selected
3. Select all products with the dropdown
4. Make sure it reads 25 records found (25 selected)
5. Go to Actions -> Change status -> (select new status)

### Expected result (*)
1. A total of 25 record(s) have been updated.

### Actual result (*)
1. A total of 20 record(s) have been updated.

**Comment by marvinhinz** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @marvinhinz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @marvinhinz, here is your [Magento instance](https://i-23783-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23783-2-3-develop.instances.magento-community.engineering/admin](https://i-23783-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-23783-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23783-2-3-develop.instances.magento-community.engineering/admin](https://i-23783-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @marvinhinz 
this issue is already reported  & fixed in the PR #22704 and merged to 2.3-develop branch

**Comment by marvinhinz** [comment]
@shikhamis11 okay thank you! I didnt see the merge was not released yet
