### ISSUE TITLE
A logical error: Magento 2 checks whether a backend config form field's «backend_model» implements the \Magento\Framework\App\Config\ValueInterface interface only, but actually calls the «backend_model» for much more methods (absent in the interface)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2378]
https://mage2.pro/t/218

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
