### ISSUE TITLE
Admin Dash Board Not Working Magento ver. 2.3.2

### ISSUE THREAD

**Issue by block0xhash** [magento/magento2#23785]
Hi

I have installed Magento ver. 2.3.2.  when I login to the Admin site the   click on the side menus nothing happens.

I have tried to run:
php bin/magento cache:clean 
php bin/magento indexer:reindex
php bin/magento setup:static-content:deploy

but doesn't seem to help.

please assist on how to troubleshoot this

![image](https://user-images.githubusercontent.com/16897613/61528423-02d91500-aa1f-11e9-889e-dfd708bafafd.png)

**Comment by engcom-Charlie** [comment]
Hello @bothwellw ! Thank you for your report !
I`m not able to reproduce this issue on 2.3.x release line . Make sure that you are following all Magento requirements (check it here : https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html ) . This is not Magento core bug just problems with your system/configuration . Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

Thanks for collaboration !
