### ISSUE TITLE
Can not edit the name for the list on Multiple Wish Lists 

### ISSUE THREAD

**Issue by jorgealonso78** [magento/magento2#23786]
### Preconditions (*)

1. a B2B magnto vanilla 2.3.1

### Steps to reproduce (*)

1. Enable Multiple Wish Lists on admin panel
2. login as customer and go to "My Wish List"
3. create  all the 5 list allow by default 
4. start to edit this list 
5. at some point you can not edit 

### Expected result (*)

1. that you can edit the name of the list

### Actual result (*)

1 .you can not edit the name of the list because the popup appears more than once
![2019-07-19_06h32_54](https://user-images.githubusercontent.com/8143525/61529596-bf1ae700-a9ef-11e9-953c-08f3e3c01ff2.png)
![2019-07-19_06h34_29](https://user-images.githubusercontent.com/8143525/61529598-c0e4aa80-a9ef-11e9-9c41-a58b9ce0615d.png)

**Comment by jorgealonso78** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @jorgealonso78. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jorgealonso78, here is your [Magento instance](https://i-23786-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23786-2-3-develop.instances.magento-community.engineering/admin](https://i-23786-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jorgealonso78** [comment]
i can not set the Multiple Wish Lists in the Magento instance provided
![2019-07-19_06h56_57](https://user-images.githubusercontent.com/8143525/61530680-c42d6580-a9f2-11e9-9e01-2ccb83eb9db1.png)

**Comment by jorgealonso78** [comment]
my vanilla magento look like this 
![2019-07-19_07h01_12](https://user-images.githubusercontent.com/8143525/61530799-179fb380-a9f3-11e9-993b-9e4dcccd5bc7.png)

**Comment by jorgealonso78** [comment]
@magento give me 2.3.1 instance - upcoming 2.3.1 release

**Comment by magento-engcom-team** [comment]
Hi @jorgealonso78. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jorgealonso78, here is your [Magento instance](https://i-23786-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-23786-2-3-1.instances.magento-community.engineering/admin](https://i-23786-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
Hi @jorgealonso78 !
Multiple Wish List available only for **B2B** version of magento. Magento instance presented in **CE** version
You can read here: 
https://docs.magento.com/m2/b2b/user_guide/configuration/customers/wishlist.html

**Comment by jorgealonso78** [comment]
ok, I work on EE, how I can test this for you guy using your instance?

**Comment by sdzhepa** [comment]
Hello @jorgealonso78 

Based on the description of this issue, it related to Magento Commerce and/or B2B functionality.
Current repository https://github.com/magento/magento2 and issue backlog related only to Magento Open Source version.

Magento Commerce and B2B code-base are located in private repositories and not available for community contributions.

[Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines):

> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.
>
