### ISSUE TITLE
Class  'Magento\CatalogSearch\Model\Indexer\Fulltext\Action\FullFactory' not found

### ISSUE THREAD

**Issue by Goldstar215** [magento/magento2#23798]
### Preconditions (*)

1. Magento version: 2.3.2
2. Server environment: Ubuntu nginx

### Steps to reproduce (*)

1. Enable Magento Inventory modules
2. Enable Smile/Elasticsuite modules

### Expected result (*)

1. Elasticsuite works well.

### Actual result (*)

1. Shows an 500 error.
Fatal error: Class 'Magento\CatalogSearch\Model\Indexer\Fulltext\Action\FullFactory' not found in /var/www/html/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Action/FullFactory.php on line 30

**Comment by engcom-Alfa** [comment]
Hello @Goldstar215!  Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
