### ISSUE TITLE
When category over 10000 products, the price filter is not showing with elastic search

### ISSUE THREAD

**Issue by ron-jomashop** [magento/magento2#23793]
### Preconditions (*)

1. Magento 2.3.2
2. Elastic Search 2

### Steps to reproduce (*)

1. Add 10000 products to a category
2. Go to config, set Layer Navigation:
  - Display product count: Yes
  - Price Navigation Step Calculation: Automatic (equalize product counts)
  - Display Price Interval as One Price: Yes
  - Interval Division Limit: 9
3. Enable elastic search 2
4. Reindex

### Expected result (*)

1. Should have the price filter in the layered navigation in the 10000 products category

### Actual result (*)

1. No price filter showing in the 10000 products category

**Comment by ron-jomashop** [comment]
I cannot test this with the Magento instance because it does not have Elastic Search enabled.

**Comment by ron-jomashop** [comment]
I think this is related to this ticket (https://github.com/magento/magento2/issues/22792).

**Comment by engcom-Charlie** [comment]
Hi, @ron-jomashop ! I close this issue because i confirmed the #22792(same problem) recently.
Thank you for contributing!

**Comment by ron-jomashop** [comment]
Can you give this a test? I think this also happens when there are 8000 products. This ticket is related to the price filter is not showing in the layered navigation with elasticsearch enabled.

**Comment by engcom-Charlie** [comment]
@ron-jomashop okay, i confirm this issue.
Thank you for contributing!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18474` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ron-jomashop** [comment]
It seems like this commit 021a953482e06a622d1508fe35aa4e744d636493 is introducing the bug after git bisect.

**Comment by engcom-Echo** [comment]
Hi, @ron-jomashop.
The filter may not be displayed when only one range is found by the algorithm. And it can create the impression that it doesn't work.
app/code/Magento/CatalogSearch/Model/Layer/Filter/Price.php 
![image](https://user-images.githubusercontent.com/51681435/101055003-2cea9300-3592-11eb-8cbb-9908dab643ea.png)
![image](https://user-images.githubusercontent.com/51681435/101055969-23155f80-3593-11eb-8e3f-8bc23020b9ac.png)

I did research and could not reproduce an issue.
![image](https://user-images.githubusercontent.com/51681435/101055349-7c30c380-3592-11eb-8033-0ad0f4bc54cd.png)
So, I think it is not related to Elastic search.

**Comment by engcom-Echo** [comment]
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @ron-jomashop. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23872` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.2` release.
