### ISSUE TITLE
Can't install non-composer modules

### ISSUE THREAD

**Issue by kassner** [magento/magento2#2379]
Hi,

With 2.0.0-RC2 is not possible to install modules without composer (like copy and paste files into `app/code`). The cause is the [`_empty_` key](https://github.com/magento/magento2/blob/2.0.0-rc2/composer.json#L226) in the composer.json.

I'm guessing that the composer.json is now generated by script and the we're bumping into [a PHP bug](https://bugs.php.net/bug.php?id=46600). With this `_empty_` key, the behaviour of looking for any undeclared namespace inside `app/code` no longer works, forcing vendors to distribute their modules through Composer.

Thanks!

**Comment by mazhalai** [comment]
@kassner yes, we are aware of this problem. We will have it fixed in the GA release.

**Comment by davidalger** [comment]
This should be fixed in the 2.0 GA.
