### ISSUE TITLE
In admin, design configuration falls out of sync with store configuration, reindex fixes

### ISSUE THREAD

**Issue by siliconrockstar** [magento/magento2#23795]
### Preconditions (*)
Magento CE 2.3.2, PHP 7.1.30, Ubuntu 18.04, MariaDb 14.14, Magento caching enabled

### Steps to reproduce - missing design record
1. install Magento 2.3.2
2. log in to admin
3. got to Stores > All Stores
4. enter data for a new store view with Status=Enabled
5. click 'Save Store View'
6. click 'OK' in Warning Model that says 'This operation can take a long time'
7. Wait
8. Go to Content > Design > Configuration

### Expected result (*)
The new store view has a record in Design Configuration

### Actual result (*)
The new store view does not show up. Running ./bin/magento indexer:reindex fixes.

At some point I also caused a broken record to show up in design configuration by editing store configuration, but I can't remember how.

### Proposed Fix
All this is easily fixed by reindexing, but that's not immediately obvious. If it is not feasible to have the store configuration save event trigger a reindex, than should add some text to the store view save confirmation dialog saying a reindex may be required.

![2019-07-19_13h22_44](https://user-images.githubusercontent.com/1700502/61557513-06be6480-aa2a-11e9-848e-6ab30f9c3504.png)

**Comment by siliconrockstar** [comment]
Related issue happens if you delete a store view - a broken record appears in design configuration with an empty Store View field.

**Comment by siliconrockstar** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @siliconrockstar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @siliconrockstar, here is your [Magento instance](https://i-23795-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23795-2-3-develop.instances.magento-community.engineering/admin](https://i-23795-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by siliconrockstar** [comment]
Behavior reproduces on vanilla instance.

**Comment by siliconrockstar** [comment]
UI messaging for store configuration changes lives in the controllers for module-backend. If forcing a reindex is the right course of action, would probably add it in the same places.

![2019-07-19_13h51_02](https://user-images.githubusercontent.com/1700502/61558334-54d46780-aa2c-11e9-863a-85a500db5743.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18373` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @siliconrockstar. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23863` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
