### ISSUE TITLE
When Disable Onepage Checkout Can't go on checkout step

### ISSUE THREAD

**Issue by defyasdf** [magento/magento2#2380]
Install with magento 2 rc master branch.
Backend:Store -- Configuration -- Sales -- Checkout -- Checkout Options -- Enable Onepage Checkout set to No.
Frontend: add product to cart
that minicart can't goto checkout only a button "view and edit cart" and click that only has "Check Out with Multiple Addresses" 
is that a bug?

**Comment by NadiyaS** [comment]
Hi, 
it is not a bug. If you want to disable Check Out with Multiple Addresses go to Store > Configuration > Sales > Multishipping Settings and in 'Allow Shipping to Multiple Addresses' set No

**Comment by defyasdf** [comment]
Hi @NadiyaS 
But that no button go to checkout shipping.

**Comment by defyasdf** [comment]
Backend:
![19](https://cloud.githubusercontent.com/assets/1632536/11203570/16bf5c24-8d30-11e5-9071-b1c971c36dca.JPG)
Frontend:
![20](https://cloud.githubusercontent.com/assets/1632536/11203578/23b0074e-8d30-11e5-859a-8dfcf028c6cd.JPG)
![18](https://cloud.githubusercontent.com/assets/1632536/11203583/29a982ce-8d30-11e5-90ad-4968edd3506c.JPG)

**Comment by AgentGod** [comment]
Hi 
I have the same issue with Magento 2.2.0
What was the solution?

**Comment by fabianus76** [comment]
same problem here - did anybody find a solution ?

**Comment by ghost** [comment]
This still happens on 2.2.5 and is not very funny since the one page checkout is illegal in most EU countries since it does not show all products and their amount on the last checkout step - it hides them in a sidebar. Who the hell came up with that?? Happens with blank and luma theme and most themes that are based on them.

**Comment by jonrandy** [comment]
Same thing happens on Magento 1

**Comment by Ahmed-Ayman** [comment]
this still happens in magento2 !

**Comment by johncarlson21** [comment]
This issue should not be closed. I can confirm that this still doesn't work correctly.
If I disable One Page Checkout, shouldn't there be a way to checkout without having to use the Multi-Shipping option? Shouldn't there just be a Proceed to Checkout button?
Are you forcing us to use One Page Checkout?

**Comment by Ahmed-Ayman** [comment]
@magento-admin can you please reopen this?

**Comment by neobiz** [comment]
Hello,
The issue still happens in Magento 2.2.6, is there a solution please ?

**Comment by sivasdescalzo** [comment]
Still happening in Magento 2.3.3

**Comment by muhannadalhariri** [comment]
also faced in 2.3.5-p1

**Comment by giglsmith** [comment]
This has still not been fixed? We can't use one page checkout in our business and don't want multi address shipping so what is the solution?

**Comment by alanvo8** [comment]
This is still happenning in 2.4.0 - it does not look like Magento will fix this.

**Comment by lucianopeluso10** [comment]
This is still happenning in 2.4.1

**Comment by ronak197** [comment]
Is this ever gonna be fix?

**Comment by onahkenneth** [comment]
Seems this issue is being ignored by Magento core team and will never be fixed
