### ISSUE TITLE
Incorrect base currency in order grid for historical orders

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#23805]
### Preconditions
1. Magento 2.3.1

### Steps to reproduce 
1. Create an order
2. Change store base currency
3. Go to order grid screen. New base currency is shown instead of base currency in which the order was placed in. 

### Expected result 
1. Old base currency should be shown

### Actual result (*)
1. Newly configured base currency is shown instead of base currency in which the order was placed in.

**Comment by dverkade** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dverkade, here is your [Magento instance](https://i-23805-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23805-2-3-develop.instances.magento-community.engineering/admin](https://i-23805-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18372` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sidolov** [comment]
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#23817 by @edenduong in 2.3-develop branch
Related commit(s):
 - [a52ae7ed3cb6ceb075f65cfbb2c819ef6bcf30f2](https://github.com/magento/magento2/commit/a52ae7ed3cb6ceb075f65cfbb2c819ef6bcf30f2)

The fix will be available with the upcoming 2.3.3 release.
