### ISSUE TITLE
Import Product with 2 languages (2 store views) but product categories import invalid pattern

### ISSUE THREAD

**Issue by Mizogorou** [magento/magento2#23804]
### Preconditions (*)

1. Magento Version 2.3.2
2. Ubuntu 18.04.1 LTS
3. PHP 7.2.19-0ubuntu0.18.04.1 (cli)
4. MySQL  Ver 14.14

### Steps to reproduce (*)

1. Go to **System >> Import** for importing new product with the following option:
    1.1 Entity Type: Product
    1.2 Import Behavior: Add/Update
    1.3 Validation Strategy: Stop on Error
    1.4 Allowed Errors Count: 10
    1.5 Field separator: #
    1.6 Multiple value separator: ,
    1.7 Empty attribute value constant: __EMPTY__VALUE__
    1.8 Fields enclosure: Not Selected
    1.9 Select File to Import: sample_csv.csv
    1.10 Images File Directory:     (NULL, Not modified)

2. Click 'Check Data' button, Every thing seem to be ok
3. Click 'Import' button
4. Import successfully done with no error message.

### Expected result (*)

1. Category will add only one category (with 2 languages [2 store views])
[https://www.oasismine.com/expect-1.png](https://www.oasismine.com/expect-1.png)
[https://www.oasismine.com/expect-2.png](https://www.oasismine.com/expect-2.png)

### Actual result (*)

1. Category was added 2 categories (1 for English + 1 for Vietnamese)
[https://www.oasismine.com/actual.png](https://www.oasismine.com/actual.png)

The following file is my csv for reproducing.
[CSV File Sample](https://www.oasismine.com/sample_csv.csv)

**Comment by engcom-Charlie** [comment]
Hi, @Mizogorou ! I can't reproduce this issue,because i don't know configuration of your attributes... Can you give me more details? 
My problem:
![errors](https://user-images.githubusercontent.com/51680850/61618711-13cf9380-ac76-11e9-81c3-940cfa1a6e90.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18371` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Mizogorou. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23862` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
