### ISSUE TITLE
Patch SUPEE-11155 is supported in Magento EE 2.2.4?

### ISSUE THREAD

**Issue by karthik32cse** [magento/magento2#23816]
Hi
Patch Questions:
1. I want to know Patch SUPEE-11155 is supported in Magento EE 2.2.4? What are the versions it is supported?
2. Following 2 patches only available in Magento 2.2.4 
    a. MAGETWO-93036
    b. MAGETWO-92926
Are any other patches available for Magento 2.2.4?
3. How to check the patch is already applied? Here I can compare it manually. But I want to know the best way.

Thanks in advance

**Comment by hostep** [comment]
Hi @karthik32cse 

Please refer to the documenation: https://magento.com/security/patches/supee-11155
> Patches and upgrades are available for the following Magento versions:
> - Magento Commerce 1.9.0.0-1.14.4.1: SUPEE-11155 or upgrade to Magento Commerce 1.14.4.2.
> - Magento Open Source 1.5.0.0-1.9.4.1: SUPEE-11155 or upgrade to Magento Open Source 1.9.4.2.

These SUPEE patches are usually only for Magento 1 installations.
Magento (unfortunately) at this point doesn't provide security patches for Magento 2, they advise you to always upgrade to the latest supported version (2.2.9 or 2.3.2 at the moment of writing). And I know this is a pain in the ass, but it is what it is.
