### ISSUE TITLE
Transaction overview screen doesn't show payment method

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#23815]
### Preconditions 
1. Magento 2.3.2

### Steps to reproduce
1. Place an order on the frontend.
2. Go to the backend into the transaction overview screen.

### Expected result
1. In the backoffice the transaction overview screen should show the payment method.

### Actual result
1. Payment method is blank in the transaction overview screen. 

![image](https://user-images.githubusercontent.com/1058480/61626873-b5f37980-ac7e-11e9-9da6-9531c3b5c9b8.png)

**Comment by dverkade** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dverkade, here is your [Magento instance](https://i-23815-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23815-2-3-develop.instances.magento-community.engineering/admin](https://i-23815-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23815-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23815-2-3-develop.instances.magento-community.engineering/admin](https://i-23815-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@dverkade - Payment list is displayed in the Transaction List. I am using Magento 2.3 Instance and Placed the Order throw the Braintree Payment method.

**See attached below screenshot:**
![Transaction List](https://user-images.githubusercontent.com/24711761/61626026-c402c380-ac99-11e9-9c7b-2afd5dd7cda7.png)

@dverkade - Let me send the details if you have found this issue again.
Thanks.

**Comment by ajijshekh123** [comment]
@dverkade - feel free to reopen this issue when you will reproduce this issue in fresh Magento Instance.

**Comment by matthijsburki** [comment]
Same issue here. Only on Magento Open Source 2.3.2
![image](https://user-images.githubusercontent.com/44090792/65027390-8ab59f80-d93a-11e9-87a6-63e5eaab28ed.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20200` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by demtaric** [comment]
Issue was fixed already in `2.3-develop` branch.
Branch #MAGETWO-99112
[Commit](https://github.com/magento/magento2/commit/da0c7374e5dcae81735552bdd685ee5e646b8486)
