### ISSUE TITLE
Visual Swatch image not updating in color attribute

### ISSUE THREAD

**Issue by TexPrint** [magento/magento2#23814]
### Preconditions (*)

1. Magento 2.3.1 and 2.3.2
2. PHP 7.2
3. Development Mode

### Steps to reproduce (*)

1. Open the product attribute color.
2. Add a swatch and select an image.

### Expected result (*)

1. Should show the image in the little color swatch field.

### Actual result (*)

1. Field stays empty.
2. Error message in Console: 

SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 115 of the JSON datajquery.js:9011:23

/pub/static/version1563787092/adminhtml/Magento/backend/de_DE/Magento_Swatches/js/visual.js:364

<img width="1878" alt="Bildschirmfoto 2019-07-22 um 11 51 59" src="https://user-images.githubusercontent.com/53174031/61623613-4201a300-ac77-11e9-9525-1aa879a0da49.png">

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-23814-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23814-2-3-develop.instances.magento-community.engineering/admin](https://i-23814-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
Hi @TexPrint  ! I can't reproduce this issue on 2.3.2 and 2.3-develop branches.

**Comment by TexPrint** [comment]
Thank you. How should I proceed to get to the bottom of this?

**Comment by engcom-Bravo** [comment]
Hello @TexPrint. Indeed, Your issue seems to be not reproducible on a vanilla Magento instance:
![swatchimage](https://user-images.githubusercontent.com/51680745/61633627-28248800-ac98-11e9-96cb-195bc26f2dcb.gif)
And please specify what do You mean by "proceed to get to the bottom of this". Thank You.

**Comment by TexPrint** [comment]
Since it seems to not be a core bug, there must be a conflict with something else, maybe another extension. I don't know. Is there a guideline how to proceed to narrow down the culprit?

Thank you for your help.

**Comment by engcom-Bravo** [comment]
@TexPrint, Unfortunately, the GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
