### ISSUE TITLE
Unable to add order tags in Magestore Extension

### ISSUE THREAD

**Issue by ulmweb** [magento/magento2#23822]
### Preconditions (*)

1. Magento CE 2.3.1
2. Magestore Extension installed

### Steps to reproduce (*)

1. Configuration>Magestore Extension>Order Configuration
2. Attempting to add product tag "Ready for Pickup" (color #1FA8DA)

### Expected result (*)

1.  I expect the new product tag to save and be available in the order screen for selection

### Actual result (*)

1.  New order tag cannot be saved, setting screen freezes upon clicking "save config"

additonal information:
TypeError: window.jscolor.installByClassName is not a function
window.jscolor.installByClassName('jscolor'); in
app/code/Magestore/OrderSuccess/view/adminhtml/templates/system/config/form/field/array.phtml

**Comment by ulmweb** [comment]
This information was provided to us by our team developer, who informed us he pinpointed the issue:

TypeError: window.jscolor.installByClassName is not a function
window.jscolor.installByClassName('jscolor'); in
app/code/Magestore/OrderSuccess/view/adminhtml/templates/system/config/form/field/array.phtml

**Comment by hostep** [comment]
Hi @ulmweb 

I think you best take this up with Magestore themselves.
The magento source code doesn't contain code regarding `jscolor`, so we can't help you here I'm afraid.
