### ISSUE TITLE
advanced bundling js translation not (always) working

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#23821]
When using advanced bundling, some core strings are not translatable.

### Preconditions (*)

1. Use any supported Magento Version (e.g. latest)
2. Configure and use advanced bundling (eventually also reproducable with current default bundling implementation) 
3. use a language pack or translate "Cancel" to anything else in your locale

### Steps to reproduce (*)

1. add product to cart
2. hit the delete button in minicart

### Expected result (*)

1. The Cancel Button is translated

### Actual result (*)

1. The Cancel Button is not translated
(same probably for OK, but OK does not have to be translated for many locales)

This error can potentially appear in many more cases, where strings are translated in js before the translations are fully initialized.

I'm not a frontend dev but it seems that the translations are initialized in the body here while some js components already try to use the translate function during initialization.
When bundled, this happens before the actual translations are loaded

See translation initialization:
https://github.com/magento/magento2/blob/2e7f0396e370074b4998a6b56636fb1ddb6da74b/app/code/Magento/Translation/view/base/templates/translate.phtml

and confirm modal initialization:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Ui/view/base/web/js/modal/confirm.js

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @davidverholen 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18420`, `MC-18421` were created

**Issue Available**: @davidverholen, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by davidverholen** [comment]
@DrewML fyi. I do not really have an idea what happens in the translate.phtml and why it is implemented like that (instead of adding the translations during init of the translate component) so I do not really have an Idea how to fix this.

**Comment by DrewML** [comment]
No problem @davidverholen - appreciate the thorough bug report. Getting it assigned out to someone internally

**Comment by adifucan** [comment]
Internal ticket MC-19247 created and it is currently in progress

**Comment by adifucan** [comment]
Hi @davidverholen fix is merged into mainline with this commit:
https://github.com/magento/magento2/commit/71c781df5536a2ec79c9cf42ade0c262396767a3

**Comment by sdzhepa** [comment]
The issue has been fixed and delivered into `2.3develop`.
Closed.
