### ISSUE TITLE
Authorize.net Different Code Magento 1 and Magento 2.3.1 (After Data Migration sales order Payment details not showing)

### ISSUE THREAD

**Issue by niksjethva** [magento/magento2#23829]
### Preconditions (*)

1. Magento 1 version: 1.9.1
2. Magento 2 version: 2.3.1
3. Orders that were placed in the Magento 1.9 store using Authorize.net payment methods

### Steps to reproduce (*)

1. Proceed with the data migration.
2. Review the orders in the Magento 2 admin panel after the migration. as I have checked and found that magento 1 Authorize.net Payment Method CODE is different than Magento 2.3.1. In Magento 1 Authorize.net Payment CODE is 'authorizenet' And in Magento 2.3.1 Authorize.net Payment Code is 'authorizenet_acceptjs'

### Expected result (*)

1. In Magento 1 Authorize.net Payment CODE and Magento 2.3.1 authorize.net Payment Code should be the same and The orders should display the payment information.
2. CODE should be like this: https://nimb.ws/ZBxTIm  to show migrated sales order payment details in admin grid Magento 

### Actual result (*)

1. After Migration Magento 1.9.1 to Magento 2.3.1 Payment method in sales_order_grid : https://nimb.ws/M7bcdt  
2. The payment information block for the orders is displaying the following text: "Payment method is not available. You still can process offline actions".

**Additional notes**

After investigating this problem, I found that this is related to two potential reasons:

- The order was placed in Magento 1 using an Authorize.net payment method that is available in Magento 2.
- The order was placed in Magento 1 using an Authorize.net payment method that is available in Magento 2 but the payment method code has changed.

**Comment by niksjethva** [comment]
> Hi @niksjethva. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [x]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @niksjethva do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

In the step reproduce we are using vanilla Magento, So please reproduce my issue.

**Comment by magento-engcom-team** [comment]
Hi @niksjethva. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @niksjethva, here is your [Magento instance](https://i-23829-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23829-2-3-develop.instances.magento-community.engineering/admin](https://i-23829-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by niksjethva** [comment]
Hello,

Authorize.net Payments works fine, but my concern is that after migration from Magento 1.9.1 to Magento 2.3.1 authorize.net Payment details not showing in sales order admin grid in Magento 2.3.1 check screenshot here : https://nimb.ws/4qotxE

**Comment by DevAbbacus** [comment]
I am also facing the same issue. Someone, please help me to fix this at the earliest.

**Comment by sandipweb** [comment]
i also migrated from magento 1.9.3.2 to magento 2.3.1  but same issue facing like payment details not showing in sales order section. So can anyone suggest me how to get all magento 1 authorize.net payment details to magento 2 by migration data.

**Comment by hitesh-shingala** [comment]
I have still same issue facing authorize.net payment details not showing after data migration magento 1.9.3.0 to magento 2.3.1. Please help me to fix this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19263` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
Hi @niksjethva ,
According to following announcement this extension was already removed from 2.4 version:
https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445

All future collaboration related to this extension should be on Marketplace using "Contacts" or "Bug reports" related to this extension.

I'm closing this issue.
