### ISSUE TITLE
Can't Add Configurable products to New Orders in Backend from a User's Cart

### ISSUE THREAD

**Issue by ilamp** [magento/magento2#23826]
### Preconditions (*)
1. Magento CE 2.3.2 without sample data is installed
2. Two store/websites are setup
3. Configurable items are added and used for testing on both stores
4. Two separate user accounts on both sites exist for testing

### Steps to reproduce (*)
1. Login to first website (Frontend) as a user
2. Add configurable products to the cart
3. Login to backend and start the process to create a new order
4. Select the the user from Step 1 and click continue
5. Select the configurable product from user's Cart and transfer that to the order.
6. Quantity is missing in the sidebar/cart

Result: *Works* but quantity on the sidebar isn't visible

1. Login to second website (Frontend) as user
2. Add configurable products to the cart
3. Login to backend and start the process to create a new order
4. Select the the user from Step 1 and click continue
5. Select the configurable product from user's Cart and transfer that to the order.
6. Quantity is missing in the sidebar/cart

Result: *Doesn't work*

### Expected result (*)
1. Configurable product should be added to the order

### Actual result (*)
1. Redirects to the order page and cart is emptied.

**Comment by ilamp** [comment]
> Hi @ilamp. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @ilamp do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @ilamp. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ilamp, here is your [Magento instance](https://i-23826-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23826-2-3-develop.instances.magento-community.engineering/admin](https://i-23826-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18468` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahsn** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [Magento instance](https://i-23826-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23826-2-3-develop.instances.magento-community.engineering/admin](https://i-23826-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul, here is your [Magento instance](https://i-23826-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23826-2-3-develop.instances.magento-community.engineering/admin](https://i-23826-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @ilamp. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23869` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
