### ISSUE TITLE
\Magento\Sales\Api\Data\OrderInterface::getShippingAddress is gone in 2.0.0-RC2

### ISSUE THREAD

**Issue by mwr** [magento/magento2#2382]
With the commit 6c1a87aaa5d173f0e4d6e56feb048db61277f331 the method getShippingAddress is removed from the \Magento\Sales\Api\Data\OrderInterface.

I don't get why this has been done.

I know that virtual orders don't need a ShippingAddress, but in this case it should just return null.

Can anybody clear things up a bit?

**Comment by antonkril** [comment]
To support more complicated shipping scenarios, shipping address should be linked to order item shipping information. So to support this in future, shipping address was removed from order.

**Comment by cmuench** [comment]
@antonkril I think such changes should not be done close before final release in a RC.

**Comment by mwr** [comment]
@antonkril thank you for the clarifcation. But that brings me to my next question, how can I retrieve the ShippingAddress when working against the OrderInterface / OrderItemInterface?

**Comment by fooman** [comment]
Changing something this late is bad enough, however I am even more concerned about the lack of adherence to semantic versioning. Removing anything from the API is backwards incompatible and should have triggered a major version update for the Magento_Sales module.

**Comment by antonkril** [comment]
@cmuench @fooman agree with your concerns. After we release stable version of product, versioning and code stability will be enforced by static tools to prevent such situations.
