### ISSUE TITLE
Web Server Rewrites not working in multi-store environment

### ISSUE THREAD

**Issue by ilamp** [magento/magento2#23831]
### Preconditions (*)
1. Magento CE 2.3.2 without sample data is installed
2. URL Rewrites are turned on
3. Two store/websites are setup

### Steps to reproduce (*)
1. Add a new Product
2. Add Product to a category in both of the stores.
3. View the product URL in both stores on the frontend

### Expected result (*)
1. Store 1 URL should be /test-product.html
1. Store 2 URL should be /test-product.html

### Actual result (*)
1. Store 1 URL for the product ends up to be /catalog/product/view/id/9/s/test-product/category/3/  **(Wrong)**
2. Store 2 URL for the product ends up to be /test-product.html **(Correct)**

**Comment by ilamp** [comment]
> Hi @ilamp. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @ilamp do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.



> Hi @ilamp. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @ilamp do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @ilamp. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ilamp, here is your [Magento instance](https://i-23831-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23831-2-3-develop.instances.magento-community.engineering/admin](https://i-23831-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ilamp** [comment]
@engcom-Alfa You logged me out. hah I was already testing it on the dev instance.

**Comment by engcom-Alfa** [comment]
Hi @ilamp ! 

According to the test scenario, I am not able to reproduce this issue on fresh 2.3-develop and 2.3.2 instances.
Everything works correctly.

**Actual Result:**
(first store)
![screen1](https://user-images.githubusercontent.com/51679138/61707638-a134e580-ad53-11e9-926a-3afcc3e34b52.png)

(second store)
![screen2](https://user-images.githubusercontent.com/51679138/61707689-b9a50000-ad53-11e9-8fc5-8b7e5f873bf7.png)

Thank you for collaboration!
