### ISSUE TITLE
Product png transparent image ignore "transparent" and "background" color parameters

### ISSUE THREAD

**Issue by apomili** [magento/magento2#23835]
### Preconditions (*)

1. Magento 2.2.8
2. Choose "ImageMagick" as Image Processing (configuration > advanced > developer)
3. A transparent background PNG to upload as a product image

### Steps to reproduce (*)

1. Create a product and add the transparent png as image
2. Open the etc/view.xml file and edit the parameters for the product list/grid image as below

```
            <image id="category_page_grid" type="small_image">
                <width>500</width>
                <height>500</height>
                <transparency>false</transparency>
                <background>[255,0,0]</background>
            </image>
            <image id="category_page_list" type="small_image">
                <width>500</width>
                <height>500</height>
                <transparency>false</transparency>
                <background>[255,0,0]</background>
            </image>
```

### Expected result (*)

1. The product should have a red background and be converted in jpg

### Actual result (*)

1. The picture remain with the transparent background and as a png file.

**Comment by apomili** [comment]
I added the ImageMagick option as precondition

**Comment by engcom-Alfa** [comment]
Hi @apomili !

Thank you for you report!
I'm not able to reproduce issue on fresh 2.3-develop instance. All works correctly.

**Actual Result:**
![screen](https://user-images.githubusercontent.com/51679138/61778593-b408f200-ae07-11e9-8d46-a5bce5ca1337.png)

Probably, you need to clear image cache folder (pub/media/catalog/product/cache).

If you'd like to update the issue, please reopen it.

**Comment by apomili** [comment]
In my Luma I can't reach the same result. In the red circle the only png of the set, no red bg and a 180k png file.
Maybe the fix is in the 2.3 version?

![Schermata da 2019-07-24 10-52-31](https://user-images.githubusercontent.com/7668956/61779869-be27f200-ae01-11e9-9b93-c3a3614acb6c.jpg)

**Comment by engcom-Alfa** [comment]
Yes, on 2.3-develop instance all works correctly.

**Comment by apomili** [comment]
Please can you explain what you have done?
I tried on a new installation of magento 2.3.1 and have the same issue. 
Could you try with this image?
[D3062WGIGA900119_01.zip](https://github.com/magento/magento2/files/3426883/D3062WGIGA900119_01.zip)
