### ISSUE TITLE
Authorize.net Error in Payment Info Rest api magento 2.3.2

### ISSUE THREAD

**Issue by Rajan-Bhola** [magento/magento2#23830]
### Preconditions (*)

1. Magento 2.3.2
2.

### Steps to reproduce (*)

1.While checkout with authorize.net using credit card
2.

### Expected result (*)

1.http://prntscr.com/oisx8o - Error showing while payment using test credit card
checkout needs to be successful.

### Actual result (*)

1.http://prntscr.com/oisx8o - Error showing while payment using test credit card
2.http://prntscr.com/oisxi3 - Payment is successful issue in magneto rest api cart module

**Comment by Rajan-Bhola** [comment]
Need Help from support

**Comment by Rajan-Bhola** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Rajan-Bhola. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Rajan-Bhola, here is your [Magento instance](https://i-23830-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23830-2-3-develop.instances.magento-community.engineering/admin](https://i-23830-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Rajan-Bhola** [comment]
Yes : instance also have same error :http://prntscr.com/oit8z2

**Comment by Rajan-Bhola** [comment]
@magento Yes : instance also have same error :http://prntscr.com/oit8z2

**Comment by Rajan-Bhola** [comment]
@aredridel Please help me with bug magento 2.3.2

**Comment by Rajan-Bhola** [comment]
@engcom-Charlie  please check

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23830-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23830-2-3-develop.instances.magento-community.engineering/admin](https://i-23830-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Rajan-Bhola** [comment]
shall i enter my authorize.net test keys

**Comment by engcom-Charlie** [comment]
Hi, @Rajan-Bhola ! I can't reproduce this issue on vanilla 2.3-develop .I think problem in your authorize.net  test keys.The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
Thank you for contributing!
