### ISSUE TITLE
CHANGELOG.md already exists

### ISSUE THREAD

**Issue by mc388** [magento/magento2#2383]
Hi,

I include the `magento/product-community-edition` package into the composer file from my main project. 

```
  "require": {
    "php": "~5.5.0|~5.6.0|~7.0.0",
    "magento/product-community-edition": "2.0.0-rc2",
    "my_custom/module": "dev-develop"
  },
```

If I set `"magento-force": "override"` the installation works fine, but there are some files which I don't want to override. I want to keep the `CHANGELOG.md` and some more from the main project.

Is there an option to ignore these files in the mapping from the `magento2-base` project? Otherwise I get the following error:

```
  [ErrorException]                                                                
  Target ./CHANGELOG.md already exists (set extra.magento-force to override) 
```

**Comment by veloraven** [comment]
@mc388 is this issue still actual?

**Comment by marvincaspar** [comment]
no
