### ISSUE TITLE
Hello! system log error "Broken reference"

### ISSUE THREAD

**Issue by Dkmafia** [magento/magento2#23842]
### Summary (*)

Upon checkout (credit card only) the cart hangs. 

In the system log I found:
main.WARNING: Broken reference: No element found with ID 'footer-container'. [] []

Thank you in advance!

**Comment by engcom-Delta** [comment]
Hi @Dkmafia, thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
