### ISSUE TITLE
Magento Upgrade Issue 2.3.1 ==> 2.3.2 

### ISSUE THREAD

**Issue by fab-rkd** [magento/magento2#23850]
PHP fatal error after upgrading to 2.3.2 from 2.3.1.  
I have upgraded the Magento via composer and followed the steps mentioned [here](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html) I was able to upgrade all the packages without any error, but when I am running `php bin/magento setup:upgrade` or any other command it throws following error :

> PHP Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventoryReservationsApi\Model\ReservationBuilderInterface in vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50

I've tried clearing `var/cache` ,  `generated/code`,  `var/page_cache` and `redis-cli flushall` as well. But no luck. I have also tried upgrading it on different local setups but no luck. 

### Preconditions (*)

1. Magento 2.3.1 Open Source and deploy mode set to `developer`
2. PHP 7.2.20 
3. Composer 1.8.6
4. Ubuntu 18.04.1
5. MySQL 14.14 Distrib 5.7.26
6. Apache/2.4.29 (Ubuntu)

### Steps to reproduce (*)

1.  Follow the steps mentioned [here](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html) 
2. After successfull `composer update`, run `bin/magento setup:upgrade`

### Expected result (*)

1. Able to run `setup:upgrade` or any other command without any fatal errors

### Actual result (*)

1. PHP Fatal error: Cannot instantiate interface `Magento\InventoryReservationsApi\Model\ReservationBuilderInterface`

**Comment by engcom-Alfa** [comment]
Hi @fab-rkd ! Thank you for your report.
I suppose it could be related to Multi-source Inventory Modules.
You could create this issue with details in the https://github.com/magento/inventory/issues .

Thanks!
