### ISSUE TITLE
Magento 2.3 Customer Configuration in the Online Customers Options field have not proper validation

### ISSUE THREAD

**Issue by kirtinariya1** [magento/magento2#23852]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

`Customer Configuration` in the `Online Customers Options` have `Online Minutes Interval` and `Customer Data Lifetime` two field and that field have used for minutes interval. But issue is that two field taking any of the value. There should be take proper validation. 
1. Login to the Magento 2 admin.
2. Go to the STORES >> Settings >> Configuration >> CUSTOMERS >> Customer Configuration >> Online Customers Options: 
3. Online Minutes Interval: add any text value
4. Customer Data Lifetime: add any text value
5. Save Config

### Expected result (*)

1. There should be allow only digit. Validation is missing
2. ![Correct-Validation](https://user-images.githubusercontent.com/28681937/61788325-76b85a80-ae2f-11e9-8a1b-7f5328e8b5fc.png)

### Actual result (*)

1. There is a taking all the value like text and string as well.
2. ![Wrong-Validation](https://user-images.githubusercontent.com/28681937/61788399-9ea7be00-ae2f-11e9-88e2-21df23b462e3.png)

**Comment by kirtinariya1** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1, here is your [Magento instance](https://i-23852-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23852-2-3-develop.instances.magento-community.engineering/admin](https://i-23852-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18544`, `MC-18545` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1. Thank you for your report. 
The issue has been fixed in magento/magento2#23856 by @kirtinariya1 in 2.3-develop branch
Related commit(s):
 - [c347ef413d666b09333e1a41c51957ccf20f8aa9](https://github.com/magento/magento2/commit/c347ef413d666b09333e1a41c51957ccf20f8aa9)
 - [f353af1dfefa9a1221b1b2be9b0fe233fc233be4](https://github.com/magento/magento2/commit/f353af1dfefa9a1221b1b2be9b0fe233fc233be4)

The fix will be available with the upcoming 2.3.4 release.
