### ISSUE TITLE
Class Dhl\Shipping\Model\Attribute\Backend\TariffNumber does not exist

### ISSUE THREAD

**Issue by gnsaran** [magento/magento2#23857]
When i update magento version then i showing this error where i edit product 
![erroe](https://user-images.githubusercontent.com/30433788/61792739-0b748580-ae3b-11e9-92cb-656db55d6f59.jpg)
in admin panel.

**Comment by engcom-Alfa** [comment]
Hi @gnsaran !
Thank you for your report.
 Unfortunately, there are not enough information to reproduce issue you described.
You could refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
Or if you'd like to update the issue, please reopen it.
