### ISSUE TITLE
Magento 2.3 Image cache not generating

### ISSUE THREAD

**Issue by junaidq57** [magento/magento2#23851]
### Preconditions (*)
Magento EE upgrade from 2.2.7 to 2.3.2

### Steps to reproduce (*)
After upgrade, product images are missing on product detail page only.

I debugged a bit and ran the command "catalog:image:resize" and images appeared. But when I flush catalog images cache from admin, the issue appeared again.

I think the images cache is not generating. The permission for pub/media are also 777.

### Expected result (*)
Product image visible on product detail page

### Actual result (*)
Product images missing on product detail page

**Comment by engcom-Alfa** [comment]
Hi @junaidq57 ! Thank you for your report.
This issue is duplicate to [#19710](https://github.com/magento/magento2/issues/19710)
