### ISSUE TITLE
Can't add product to cart with customizable options (type checkbox) through REST API 

### ISSUE THREAD

**Issue by gekamikh** [magento/magento2#23869]
### Preconditions (*)

1. Magento version: 2.3.1
2. PHP version: 7.2.12

### Steps to reproduce (*)

1. Create quest cart using API endpoint: `POST /V1/guest-carts`
2. Get `cartId` from response
1. Try to add product to guest cart using API endpoint: `POST /V1/guest-carts/{cartId}/items`
Body:
```
{
    "cartItem": {
        "sku": "some-sku",
        "qty": 1,
        "quote_id": cartId
        "product_option": {
            "extension_attributes": {
                "custom_options": [
                    {
                        "option_id": "12",
                        "option_value": "20,21,22"
                    }
                ]
            }
        }
    }
}
```

### Expected result (*)

1. Product added to cart

### Actual result (*)

1. Error:
```
{
    "message": "The product's required option(s) weren't entered. Make sure the options are entered and try again."
}
```

Error thrown from:
https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Catalog/Model/Product/Option/Type/Select.php#L77

Potentially this commit https://github.com/magento/magento2/commit/64ee8e937481efa0212e63a367d939332b84bb74 broke functionality, because if change `0` to `1` as it was before this fix, everything works. Product added to the cart.

Also, if I try to add product with radio option everything works

**Comment by krishprakash** [comment]
Hi @gekamikh. Thank you for your report.
Issue is duplicate to #23863
