### ISSUE TITLE
Website logo and upload from gallery features not working

### ISSUE THREAD

**Issue by bojjaiah** [magento/magento2#23861]
### Preconditions (*)

1. Install Magento version2.3.1/2.3.2
2.

### Steps to reproduce (*)

1. Login to admin panel
2. Content -> Configuration -> Edit Theme -> Upload logo/ upload logo from gallery

### Expected result (*)

1. [Screenshots, logs or description]
2. The image needs to be upload

### Actual result (*)

1. [Screenshots, logs or description]
2. Error throwing see my thread from [StackExchange](https://magento.stackexchange.com/questions/283125/strange-error-file-you-are-trying-to-upload-exceeds-maximum-file-size-limit-in)

**Comment by engcom-Bravo** [comment]
Hello @bojjaiah, thanks for reporting. We've been not able to reproduce Your issue and so it is highly likely not a core bug of Magento, but a matter of server's settings. You can try to reproduce the issue Yourself on a clear, vanilla instance of Magento asking a bot for it by just leaving here a comment like '@magento give me 2.3-develop instance' (without quotes). If You manage to reproduce it let us know and we will continue to work on the issue in order to confirm it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23861-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23861-2-3-develop.instances.magento-community.engineering/admin](https://i-23861-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gwharton** [comment]
@bojjaiah Can you reproduce this on a vanilla instance of Magento 2.3-develop as I cannot.

From the look of your screen recording on stackexchange, it doesn't look vanilla.

Stock Magento states under the logo image "Maximum file size: 2 MB. Allowed file types: JPG, GIF, PNG." but yours states "Maximum File Size : NaN" which indicates that something is messing with the design config for that form.

The config is set in the file 

```
app\code\Magento\Theme\view\adminhtml\ui_component\design_config_form.xml

                    <imageUploader>
                        <settings>
                            <allowedExtensions>jpg jpeg gif png</allowedExtensions>
                            <maxFileSize>2097152</maxFileSize>
                            <uploaderConfig>
                                <param xsi:type="string" name="url">theme/design_config_fileUploader/save</param>
                            </uploaderConfig>
                        </settings>
                    </imageUploader>
```

**Comment by engcom-Bravo** [comment]
@bojjaiah, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
