### ISSUE TITLE
Grand total in the new Credit memo view is not updated

### ISSUE THREAD

**Issue by kassner** [magento/magento2#2386]
Hi,

On the new Credit Memo form, the field `Grand total` is not updated when you change any value in the `Refund totals` block.

![New credit memo form](http://i.imgur.com/xW79lzV.png)

In the image above, please note that the `Grand total` is $20.00, even though the `Subtotal` is $10.00 and the fields below are $0.00. When you change any of those fields, the `Grand total` is not updated.

Thanks!

**Comment by choukalos** [comment]
Hi @kassner - agreed, looks like we could improve the UX a bit more here.  If you hit the Refund Offline it would re-calculate and then submit.  If you had refunded shipping or made an adjustment prior to hitting the update qty button it would re-calc the grand total.  Noted that the button requires the qty of product to be changed before it'll let you push it.

@tkacheva @eleonova - do you have this comprehended in the UX improvement plan ( Credit Memo UX improvements )?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Grand-total-in-the-new-Credit-memo-view-is-not-updated/idi-p/45349).

**Comment by kassner** [comment]
@piotrekkaminski I believe this should be classified as a bug, not an improvement. We're dealing with the exhibition of misleading information here.
