### ISSUE TITLE
Magento 2.3.2 My Account -> Add new Address -> Phone number field not showing with * mark

### ISSUE THREAD

**Issue by dhiraj-danode** [magento/magento2#23860]
### Preconditions (*)

1. 2.3.2
2. 2.3.1

### Steps to reproduce (*)

1. Go to Frotnend and Login
2. Go to My Account -> Add new address.
3. We can see phone number field is mandatory and * mark is missing.

### Expected result (*)

1. [Screenshots, logs or description]
2. In add new address form * marks should be there for phone number.
3. In Magento\Customer\Block\Address\Edit.php precheckRequiredAttributes() function $precheckAttributes data showing empty

### Actual result (*)

1. [Screenshots, logs or description]
2. Plese check the attachment,
![address issue](https://user-images.githubusercontent.com/47853083/61795746-bb4cf180-ae41-11e9-9c89-353c0bbbf603.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23860-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23860-2-3-develop.instances.magento-community.engineering/admin](https://i-23860-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by ajijshekh123** [comment]
The issue is not reproduced in Fresh Magento 2.3 Instance.
**See attached screenshot:**

![2 3 Magento Instance](https://user-images.githubusercontent.com/24711761/61796675-80e45400-ae43-11e9-9afb-202178ac0a29.png)

@dhiraj-danode - Please update me which Magento instance you are using?

**Comment by dhiraj-danode** [comment]
Hello @ajijshekh123 

Can you please check in 2.3.1 version.

**Comment by ajijshekh123** [comment]
Okay @dhiraj-danode

**Comment by ajijshekh123** [comment]
@dhiraj-danode - This issue I have to verify in Magento 2.3.1 Instance but I don't have found this issue.

![2019-07-24 (2)](https://user-images.githubusercontent.com/24711761/61798490-03224780-ae47-11e9-8770-03e8e8cb0925.png)

@dhiraj-danode - Can I close this issue or not?

**Comment by dhiraj-danode** [comment]
ok, Thanks @ajijshekh123 
I am still facing issue in fresh magento 2.3.1 instance, I will check it.

**Comment by ajijshekh123** [comment]
Okay @dhiraj-danode

**Comment by dhiraj-danode** [comment]
@ajijshekh123 Can you please confirm. I have issue in magento EE 2.3.1
