### ISSUE TITLE
youtube url is added in downloadable products, but it is not playing through customer account

### ISSUE THREAD

**Issue by vini1996** [magento/magento2#23875]
### Preconditions (*)

1. PHP 7.14
2.magento 2.2.7

### Steps to reproduce (*)

1. add downloadable products from admin
catalog->products->downloadable products->downloadable information -<Links ->File -> Select URL. add youtube URL in the placeholder.
2.from customer myaccount->downloadable products 
play a video
![image](https://user-images.githubusercontent.com/39683802/61851570-f9dfbc00-aed4-11e9-8419-5a2e63c31b10.png)

### Expected result (*)

1. video should play 

### Actual result (*)

1. it is showing messy 
![image](https://user-images.githubusercontent.com/39683802/61851614-17ad2100-aed5-11e9-96d5-7c47b96e3c9c.png)

**Comment by engcom-Alfa** [comment]
Hello @vini1996.  Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
