### ISSUE TITLE
Media gallery thumbnails stretched when image is horizontal ratio

### ISSUE THREAD

**Issue by NickdeK** [magento/magento2#23877]
When using images with a horizontal ratio, and prevent the image generation from adding white space to the images, the thumbnail images in the gallery come out pixelated on the product page.

### Preconditions (*)
1. Magento 2.3.2
2. `<var name="product_image_white_borders">0</var>` in the view.xml of a theme (including the luma theme)

### Steps to reproduce (*)
1. Have a product with images that have a horizontal ratio (the width is bigger than the height)
2. Make sure that `product_image_white_borders` is set to 0 in the view.xml of the activated theme
3. If cache images are already created remove the `pub/media/catalog/product/cache/` folder.

### Expected result (*)
1. Thumbnail images to be shown crisp and sharp

### Actual result (*)
1. Thumbnail images are stretched and therefor pixelated (see screenshot below)

![Screenshot 2019-07-25 at 11 43 20](https://user-images.githubusercontent.com/6631170/61864304-78d2f580-aed1-11e9-8ea5-cb7d72051589.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18589` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by erfanimani** [comment]
Same is happening for the mini cart. If `product_image_white_borders` is false, the product image is stretched until it fits inside a square (75px x 75px for the Luma theme).

@NickdeK I'm just wondering what's the expected result exactly? For the image to be zoomed-in and cropped until it fits the specified width and hight as declared in view.xml?

**Comment by NickdeK** [comment]
@erfanimani I don't think the default behaviour should be to crop the image; essential product information may be lost depending on the content. My current fix is to just resize the image with CSS to fit the container and align it in the center/middle of the container.

**Comment by magento-engcom-team** [comment]
Hi @NickdeK, @NickdeK. 

Thank you for your report and collaboration!

The issue was fixed by @NickdeK in https://github.com/magento/magento2/pull/23884
The fix will be available with the upcoming `2.3.4` release.

**Comment by OnYXCoding** [comment]
Issue also exists in minicart. Sadly, the fix [#23884](https://github.com/magento/magento2/pull/23884) doesn't work for the minicart.
