### ISSUE TITLE
Performance issue: \Magento\Config\Model\Config\Structure::getTabs() does not cache its result and is called multiple times for the same result

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2387]
https://mage2.pro/t/topic/209

**Comment by orlangur** [comment]
If this is a performance issue, what is an actual performance impact?

**Comment by dfediuk** [comment]
In my case it was also a consistency issue and unpredictable system behavior: I plugged in to the method  for some custom processing and noticed that my plugin is called twice for the same data.

**Comment by andimov** [comment]
@mage2pro 
Could you please add the description of steps, actual result and expected result to this ticket?
It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Performance-issue-Magento-Config-Model-Config-Structure-getTabs/idi-p/45345).
