### ISSUE TITLE
Product list widget duplicated HTML ID when special price is available

### ISSUE THREAD

**Issue by extroniks** [magento/magento2#23870]
### Preconditions (*)

1. Clean Magento 2.3.2 install with sample data

### Steps to reproduce (*)

1. Set a special price on simple product (example: Fusion Backpack SKU: 24-MB02)
2. Inspect resulting html on a page with product list widget with said product

### Expected result (*)

1. The price HTML elements id's should be unique

### Actual result (*)

1. The price HTML element id's are repeated:
Home page with widget:
![image](https://user-images.githubusercontent.com/16757761/61817115-1389f080-ae4e-11e9-907a-99563ec55264.png)

**Comment by extroniks** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @extroniks. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @extroniks, here is your [Magento instance](https://i-23870-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23870-2-3-develop.instances.magento-community.engineering/admin](https://i-23870-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by extroniks** [comment]
Hello, reproduced on given 2.3 develop instance:
![image](https://user-images.githubusercontent.com/16757761/61817916-f81fe500-ae4f-11e9-8f08-90852307d6a3.png)

**Comment by engcom-Bravo** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18569`, `MC-18570` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rajeshwebkul** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul, here is your [Magento instance](https://i-23870-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23870-2-3-develop.instances.magento-community.engineering/admin](https://i-23870-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vivekkumar945744** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul, here is your [Magento instance](https://i-23870-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23870-2-3-develop.instances.magento-community.engineering/admin](https://i-23870-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
