### ISSUE TITLE
Magento 2.3.2 email templates not editable

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#23876]
### Preconditions (*)

1. Magento 2.3.2
2. php 7.2

### Steps to reproduce (*)

1. Upgrade magento from 2.3.1 to 2.3.2 following this guide : https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html
2. Edit existing template(s)
3. Preview existing template(s)

### Expected result (*)

1. When editing template you should be able to edit template.
2. In preview mode you should be able to see template without iframe

### Actual result (*)

1. Edit template has no content in main, just forms with hidden input fields.
<img width="1645" alt="Schermafbeelding 2019-07-25 om 11 08 02" src="https://user-images.githubusercontent.com/37579149/61862323-001e6a00-aece-11e9-9c9d-8ed36c3a7ad0.png">

2. Preview mode shows iframe in popup.
<img width="781" alt="Schermafbeelding 2019-07-25 om 11 07 24" src="https://user-images.githubusercontent.com/37579149/61862297-f4cb3e80-aecd-11e9-8f23-d810ff8e6744.png">

in attached screenshots top is magento 2.3.2 bottom is magento 2.3.1

It seem that templates containing inline styling cannot be loaded in 2.3.2, was able to edit simple templates.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18591` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wbeltranc** [comment]
#cd19latam

**Comment by wbeltranc** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
@wbeltranc thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by jorgehs91** [comment]
#mm19br

**Comment by magento-engcom-team** [comment]
@jorgehs91 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by torhoehn** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [Magento instance](https://i-23876-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23876-2-3-develop.instances.magento-community.engineering/admin](https://i-23876-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by torhoehn** [comment]
Closing this issue, because this issue seems to be fixed in 2.3-develop.
![Screenshot 2019-10-21 at 21 46 40](https://user-images.githubusercontent.com/1945725/67237843-5870f380-f44c-11e9-92d2-bb6b2bcf789a.png)
