### ISSUE TITLE
Fedex Free Method should allow multi selection

### ISSUE THREAD

**Issue by patellalit** [magento/magento2#23883]
Fedex shipping method configuration, Free Method dropdown has single method selection. It should be allow multi selection.

### Preconditions
1. Magento CE 2.3.1 without sample data is installed.
2. Fedex Shipping method is set up.
3. Free methods not allow to select multiple

### Steps to reproduce
1. Navigate to store configuration
2. Under Sales/Shipping methods/Fedex
3. Free Methods dropdown. I can select any one free methods.

### Expected result
Free Methods should allow multiple selection

![image](https://user-images.githubusercontent.com/244568/61871360-41c70900-aefe-11e9-8154-c393c4576ca7.png)

**Comment by engcom-Alfa** [comment]
Hi  @patellalit   thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features
