### ISSUE TITLE
Bundle Product Show Incorrect Price if bundle options has only one multiple select option

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#23886]
### Preconditions (*)

1. Magento version: 2.3.2
2. Php version: 7.2.19
3. Mysql version: 5.7.27

### Steps to reproduce (*)

1. Create a bundle product
2. Now add some bundle items along with a bundle item of input type **multiple select** which has only **one** default option and make it as required.
3. For Example(use options set like it) : 
![image](https://user-images.githubusercontent.com/51680850/61938469-da5e9700-af99-11e9-8015-212e77377e7f.png)

### Expected result (*)

1. On product page it should be ($23 + $5 = $28)

### Actual result (*)

1. It's not adding multiple select option price it's showing $5 below the add to cart button.
![Screenshot](https://user-images.githubusercontent.com/44425160/61877650-11d33200-af0d-11e9-90a7-8dc519a1d9e6.png)

**Comment by dmytro-ch** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-23886-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23886-2-3-develop.instances.magento-community.engineering/admin](https://i-23886-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hi, @rani-webkul ! I can't reproduce this issue on vanilla Magento 2.3.2. 

**Manual testing scenario:**
1.Create a bundle product
2.Now add some bundle items along with a bundle item of input type multiple select which has only one default option and make it as required.
3.Add second option with multiple select with another product added and set is default
4.Save product
5.Go to the product page 
6.Click on Customize and Add to Cart button

**Actual result:**
![image](https://user-images.githubusercontent.com/51680850/61935280-d4b18300-af92-11e9-8ded-fa6435e62de5.png)

---------------------------------------------------------------------------------------------------------------------
So i close this issue because the problem is not identified.
If you have some updates write it on your answer.
Thank you for contributing!

**Comment by rani-priya** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul, here is your [Magento instance](https://i-23886-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23886-2-3-develop.instances.magento-community.engineering/admin](https://i-23886-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rani-priya** [comment]
Hi @engcom-Charlie 

it's reproducible. Please check https://i-23886-2-3-develop.instances.magento-community.engineering/bundle-product.html

![bundle2](https://user-images.githubusercontent.com/44425160/61937304-316d6780-afac-11e9-9d66-805ad83115e7.png)
 
![bundle1](https://user-images.githubusercontent.com/44425160/61937325-3cc09300-afac-11e9-9ec7-e201f63a92be.png)

**Comment by engcom-Charlie** [comment]
@rani-webkul , i agree. But configuration of bundle product not like in your steps. I will change decription and confirm it.
Thank you for contributing!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18659` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul, @rani-webkul. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.4` release.
