### ISSUE TITLE
Sales Configuration in the Minimum Amount field have not proper validation

### ISSUE THREAD

**Issue by kirtinariya1** [magento/magento2#23897]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

`Sales` configuration in the `Sales` have `Minimum Order Amount` have a field `Minimum Amount` that field have used Minimum Order Amount. But issue is that field taking any of the value. There should be take proper validation.

1. Login to the Magento 2 admin.
2. Go to the STORES >> Settings >> Configuration >> Sales >> Sales >> Minimum Order Amount: 
3. Minimum Amount: add any text value
4. Save Config

### Expected result (*)

1. There should be allow only digit.
2. ![Expected-Result-Sales-MinimumAmount png](https://user-images.githubusercontent.com/28681937/61929051-06791880-af98-11e9-9d81-f39cfa7e0133.png)

### Actual result (*)

1. There is a taking all the value like text and string as well.  Validation is missing
2. ![Actual-Result-Sales-MinimumAmount png](https://user-images.githubusercontent.com/28681937/61929080-142e9e00-af98-11e9-9abf-b36fef8f502c.png)

**Comment by kirtinariya1** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1, here is your [Magento instance](https://i-23897-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23897-2-3-develop.instances.magento-community.engineering/admin](https://i-23897-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@kirtinariya1 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18657`, `MC-18658` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
