### ISSUE TITLE
Configurable product validation doesn't work correct

### ISSUE THREAD

**Issue by davidduong90** [magento/magento2#23892]
Summary of the issue:
When I click add cart it show second option. I think it should show first option.

Now it show:
  [1]: https://i.stack.imgur.com/nJIEl.png
I think it should show
  [2]: https://i.stack.imgur.com/vTYu4.png

Information on my environment:
I'm using magento 2.3.2 and window 10.

Steps to reproduce:
+Install magento 2.3.2 with sample data 
+Check any configurable product 
+Click to add cart button

 Expected and actual results:
It should show first option to select. Now, i show second option

**Comment by ajijshekh123** [comment]
@davidduong90 -Please follow issue-reporting guideline to report an issue with all issue reproducible steps.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

Thanks.

**Comment by ajijshekh123** [comment]
@davidduong90  - feel free to reopen this issue when you are entering the issue details in the proper format.
