### ISSUE TITLE
Feature Request: Record User Agent In Admin Grid

### ISSUE THREAD

**Issue by lukebranch** [magento/magento2#239]
I'd like to suggest a simple feature that would record the user-agent a visitor has placed an order with in much the same way the IP address is now recorded.

This would help immensely with the technical support side of things if the user-agent and operating system were recorded it would be much easier to reproduce browser-specific issues without having to trouble an already frustrated customer who may or may not be completely computer-illiterate.

Here is one of the issues with IE9 that I have experienced with Magento (http://www.human-element.com/Blog/ArticleDetailsPage/tabid/91/ArticleID/53/Magento-Checkout-with-Internet-Explorer-9-IE9-Cant-Select-Credit-Card.aspx).

I'm sure you are well aware of these types of bugs, however a bandaid solution like this .htaccess hack to be provided in the .htaccess installed out of the box (perhaps commented out by default), could prove to be very handy until a more permanent solution can be found to get around the issue.

**Comment by choukalos** [comment]
Assigning Sergey since he would own the ticket for this improvement.

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the 
backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-23726
