### ISSUE TITLE
category not shown in home page

### ISSUE THREAD

**Issue by joshi8383** [magento/magento2#23903]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Bravo** [comment]
Hello @joshi8383. You need to give us some information about Your case. So please fill in the required parts of the issue description. Thank You.

**Comment by engcom-Bravo** [comment]
@joshi8383, if the issue is still actual for You, please add needed details and reopen it.
