### ISSUE TITLE
Canceled items in invoice grand total

### ISSUE THREAD

**Issue by mdhia** [magento/magento2#23909]
### Preconditions (*)

1. A Magento 2.2.9 instance

### Steps to reproduce (*)

1. Put the same item twice in the cart
2. Make a regular checkout
3. Cancel one of the items and create for the other a shipment
4. Create a Invoice for the shipped item

### Expected result (*)

1. The grand total in the created invoice contains only the one invoiced items

### Actual result (*)

1. The grad total in the created invoice contains the price of two items

**Comment by engcom-Bravo** [comment]
Hello @mdhia. Would You please describe us in more details how exactly You canceled one of the items after the order had been created. Thank You.

**Comment by engcom-Bravo** [comment]
@mdhia, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
