### ISSUE TITLE
Coupon applied more than once when per customer usage is set to 1

### ISSUE THREAD

**Issue by vivekkumar945744** [magento/magento2#23907]
### Preconditions (*)

1. Magento Community 2.3.1

### Steps to reproduce (*)

1. Create Cart Price rule with 'Uses per Customer' value set to 1
2. Add 2 Items in cart
3. Apply coupon
4. Place order with Multiple Addresses to different shipping address for each item
5. Increase "Uses per Customer" limit to 2 for coupon and then try to apply the same coupon for the same customer.

### Expected result (*)

1. After step 4 the coupon should be applied to single order. With that Uses per Customer setting should have a hint or a clear indication in Devdocs that one "Use" here is meant to be not just a fact of coupon applying for a single time but applying it to one order only. Besides during checkout with Multiple Addresses the user should have an ability and be prompted to choose which order to apply the coupon to.

### Actual result (*)

1. After step 4 Coupon is applied on all orders created as if "Use per Coupon" is meant to be just a fact of applying the coupon for a single time (no matter to how many orders). At the same time at step 5 the coupon is not accepted as being invalid as if  "Use" in "Uses per Customer" stands for applying the coupon not only for one time but also to one order only.

**Comment by engcom-Bravo** [comment]
Hello @vivekkumar-webkul, Thanks for reporting. The setting is called "Uses per Customer". Now, here the customer uses the coupon only once - "Apply coupon" in Your steps to reproduce is mentioned only once isn't it? So the behavior is quite correct. If the setting were called something like "Uses per shipping" or "Uses per order" and the behavior remained the same as now then it would definitely be a bug.

**Comment by engcom-Bravo** [comment]
@vivekkumar-webkul, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-23907-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23907-2-3-develop.instances.magento-community.engineering/admin](https://i-23907-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hello @engcom-Bravo , please look into this issue once again.
After completing above steps, please proceed the following steps and let me know the issue exists or not.

Steps to regenerate (After using coupon once, with checkout with multiple address):
1. Add some items in the cart.
2. Apply the same coupon on the cart.
-- It would not apply as already used once as per "Uses per Customer" limit.
3. Increase "Uses per Customer" limit to 2 for coupon.
4. Apply the same coupon again on the cart.
-- It would not still apply, as the coupon was applied on 2 customer orders when checkout with different address was used. (It should work as per your previous comment.)
5. Increase "Uses per Customer" limit to 2 for coupon.
4. Apply the same coupon once again on the cart.
-- It would apply on the cart this time.

**Comment by magento-engcom-team** [comment]
@MrGangola-Webkul Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20084` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar945744. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24177` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by manrahulsingh** [comment]
I have 2 Magento Instances one is production site and another one is development Instance 
I'm stucked on the same issue both Magento Setups have Version 2.4.3-p2 but for production Instance Coupon Usage is not updating in database .

**Comment by vipin12117** [comment]
Still same issue in magento 2.4.5. Any one have solution ?

**Comment by rishigupta121** [comment]
Issue is still in magento 2.4.6-p2
