### ISSUE TITLE
in magento 2 used this command php bin/magento setup:upgrade,its successfully update but site is not open .its showing blank page?

### ISSUE THREAD

**Issue by ramsampathi** [magento/magento2#2391]
Hi,
I try to create the module in magento2.after module changes i run a command like 
php bin/magento setup:upgrade
its successfully upgrade but site is showing blank page..
its asking "Please re-run magento Compile command".  
can u please give the suggestions to avoid this blank page?
how to run  magento Compile command?

![magento2_error](https://cloud.githubusercontent.com/assets/7812791/11205489/3018c4b4-8d2e-11e5-8b38-ec8c78d9fee0.png)
![magento2_home_error](https://cloud.githubusercontent.com/assets/7812791/11205812/92dd746c-8d30-11e5-9974-0210bd108b8b.png)

**Comment by dfediuk** [comment]
The `Please re-run magento Compile command` message has no relation to your problem.
In the case of a blank page please do the following: http://magento.stackexchange.com/questions/87641/how-to-debug-custom-theme-layout-in-magento-2/87647#87647

**Comment by ramsampathi** [comment]
after run  command #php bin/magento setup:upgrade..its give the blank page .before that its working good

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by user3748173** [comment]
I know that it is an old post. But I post link here, because this is the place what I found first in google search. I had run setup:upgrade and the white page loaded in browsers. 

The solution to the issue I had was in this [Magento documentation](http://devdocs.magento.com/guides/v2.1/install-gde/prereq/file-system-perms.html) page.

**Comment by Bikermanirl** [comment]
It would be nice if the message at the end of the setup stated what the command was. Or if not, somebody posted a link to how to do it on this thread.
