### ISSUE TITLE
Missing Validation at some Payment Method Settings

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23916]
### Preconditions (*)

1. Magento 2.3 develop

### Steps to reproduce (*)

1. Go to Store->Configurations->Sales->Payment Method
2. Find these fields:
- Check/Money Order
  * Minimum Order Total
  * Maximum Order Total
- Bank Transfer Payment
  * Minimum Order Total
  * Maximum Order Total
  * Sort Order
- Cash On Delivery Payment
  * Minimum Order Total
  * Maximum Order Total
  * Sort Order
- Purchased Order
  * Minimum Order Total
  * Maximum Order Total
- Authorize.Net Direct Post (Deprecated)
  * Minimum Order Total
  * Maximum Order Total
- Authorize.Net
  * Minimum Order Total
  * Maximum Order Total

3. Fill string "one" to the fields
4. Save
### Expected result (*)

1. Can not save because it is not number

### Actual result (*)

1. Save normally with the wrong data type

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23916-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23916-2-3-develop.instances.magento-community.engineering/admin](https://i-23916-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18707` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23917 by @edenduong in 2.3-develop branch
Related commit(s):
 - [d4e86dd824031d9e50380e0c2da55000079006e3](https://github.com/magento/magento2/commit/d4e86dd824031d9e50380e0c2da55000079006e3)

The fix will be available with the upcoming 2.3.3 release.
