### ISSUE TITLE
Merchant will have problems with shipping if price of configurable is $0.00 and configurable variation has weight

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#23912]
### Preconditions (*)

1. Flat Rate is on
2. Free Shipping is off
3. Customer is registered(with or without address)

### Steps to reproduce (*)

1. Create Configurable Product.
Fill name, SKU and price = 0.00
Leave everything else as is
Click **Create Configurations** button
Select attribute `color`
black - $0 - 100500, white- $2 -100500
Click Generate Products
In the grid "Current Variations" set the weight to 3 for both products
Click Save Product
2. Log in as a registered customer
3. Add the cheapest variation to cart and place order

### Expected result (*)

1. Even the product is free this doesn't mean that shipping is also free.
2. I can choose a shipping method and pay for it.

### Actual result (*)

1. No **Ship to** information
![image](https://user-images.githubusercontent.com/11827230/61966689-ec612980-afdb-11e9-8ab5-2504e8fe516b.png)

2. Shipping was not payed
![image](https://user-images.githubusercontent.com/11827230/61966620-bb80f480-afdb-11e9-9e7c-c1905c2315e4.png)

**Comment by engcom-Bravo** [comment]
Hello, @TomashKhamlai. Currently we've been bot able to reproduce Your issue following the steps provided. Probably there is (are) some essential detail(s) You have missed. Would You please revise the issue and help us to reproduce it. Thank You.

**Comment by TomashKhamlai** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](https://i-23912-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23912-2-3-develop.instances.magento-community.engineering/admin](https://i-23912-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
