### ISSUE TITLE
cart empty with magento 2.3.2 theme luma with samples

### ISSUE THREAD

**Issue by marco7319** [magento/magento2#23923]
### Preconditions (*)

1. Magento 2.3.2.
2. Theme Luma with samples
3. Website over Linux server
4. Google Chrome
5. PHP 7.2
6. Install via Softaculous
7. Date install : 26/07/2019

### Steps to reproduce (*)

1. Install Magento 2.3.2 with theme Luma with samples via cpanel via softaculous
2. If your are connected or not, add a product with the button "Add in the cart" 
3. Click on the button "cart" and i have a message "cart empty"

### Expected result (*)

1. number of products
2. a page cart open

### Actual result (*)

1. a message "cart empty"
2.

**Comment by engcom-Charlie** [comment]
Hi @marco7319 ! Magento is not supported on Windows OS. You can read it on this page https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html. 
Thank for your report!

**Comment by marco7319** [comment]
@engcom-Charlie 

hi my website is over Linux server installed with Cpanel by Lukuid and Softaculous

thank you

> Bonjour @ marco7319 ! Magento n'est pas pris en charge sous Windows. Vous pouvez le lire sur cette page https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html . 
> Merci pour votre rapport!

**Comment by engcom-Charlie** [comment]
@marco7319 but i can't reproduce it on fresh Magento 2.3.2 and 2.3-develop. You can try to reproduce it in 2.3-develop instance. I will request it for you or you can write "@magento give me 2.3-develop instance" and try to reproduce this issue please.

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23923-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23923-2-3-develop.instances.magento-community.engineering/admin](https://i-23923-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by marco7319** [comment]
@engcom-Charlie  Hello
Thank you for the access
Yes same résults , cart empty

**Comment by engcom-Charlie** [comment]
@marco7319 i open this instance and try to reproduce it after you. Result:
![Peek 2019-07-30 11-08](https://user-images.githubusercontent.com/51680850/62112037-954ca480-b2ba-11e9-911a-d6dc60684b4f.gif)
Can you try to reproduce it on your server with another browser?

**Comment by marco7319** [comment]
@engcom-Charlie 
Hello
thank you, it works well now.
I do not understand pq I had this problem ...
I made disconnect after creating a category and a product ...

**Comment by engcom-Charlie** [comment]
@marco7319 you are welcome!
Thank for your report!

**Comment by wajahatbashir** [comment]
@engcom-Charlie 
How you was fix this issue in Magento 2.3 ?

I'm facing same issue on my live server, when i'm adding product to cart the ajax requests from (1) to (0). i'm getting this message (Product added successfully) But mini cart, cart page and checkout are empty. I'm using Magento 2.3.0.

On localhost add to cart is working fine but on live server i'm facing this issue.

anyone can help me regarding this issue. Thanks
