### ISSUE TITLE
We are unable to write any object in customer session

### ISSUE THREAD

**Issue by cedcoss** [magento/magento2#2393]
if we are assigning array or simple variables in session then it is working.. but if we are trying to assign object in customer session then  we are unable to get it from session..

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
