### ISSUE TITLE
Decimal quantity is not displayed for wishlist items.

### ISSUE THREAD

**Issue by mfickers** [magento/magento2#23932]
### Preconditions (*)

1. Magento 2.2 or 2.3

### Steps to reproduce (*)

1. Add a product with decimal quantity to wishlist.
2. Try to save a decimal quantity for the wishlist item.

### Expected result (*)

1. Decimal quantity is saved for the item and displayed in the wishlist.

### Actual result (*)

1. Decimal quantity is saved but not displayed in the wishlist.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23932-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23932-2-3-develop.instances.magento-community.engineering/admin](https://i-23932-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
This issue I have reproduced in the Magento 2.3 Instance.
**See attached screenshot:**

![2019-07-29 (1)](https://user-images.githubusercontent.com/24711761/62035911-65e05e00-b20e-11e9-8120-54b886b378b8.png)

![2019-07-29](https://user-images.githubusercontent.com/24711761/62035913-6678f480-b20e-11e9-843e-51f1b8e493cc.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18712` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @mfickers. Thank you for your report. 
The issue has been fixed in magento/magento2#23933 by @mfickers in 2.3-develop branch
Related commit(s):
 - [922573b1667e22ff90cfd4577b06b27c7f4202ee](https://github.com/magento/magento2/commit/922573b1667e22ff90cfd4577b06b27c7f4202ee)
 - [d0d42fe2f08563880c1c44d6feafc35d12dd343e](https://github.com/magento/magento2/commit/d0d42fe2f08563880c1c44d6feafc35d12dd343e)

The fix will be available with the upcoming 2.3.3 release.
