### ISSUE TITLE
Tablerate Shipping regex not correct at RateQuery:134

### ISSUE THREAD

**Issue by delve-game-studios** [magento/magento2#23948]
### Preconditions (*)

1. Magento version 2.3.2
2. UK zip codes are separated by space not a dash and the tablerate plugin doesn't recognize it.
3. File to be fixed: magento/module-offline-shipping/Model/ResourceModel/Carrier/Tablerate/RateQuery.php at line 134. It checks for prefixes from zip codes that are separated only by as dash but UK zip codes are separated by empty space.

### Steps to reproduce (*)

1. Add records to the DB with some specific ZIP code prefixes from the UK
![image](https://user-images.githubusercontent.com/3236677/62134663-9812be00-b2e9-11e9-9a99-a566f5213abe.png)

2. Try to input your address in the checkout page with a full ZIP code. 
be sure to input the correct format e.g: "AB31 2AR"

![image](https://user-images.githubusercontent.com/3236677/62134702-ab258e00-b2e9-11e9-9236-bd57d15197ff.png)

### Expected result (*)

1. Show me the correct shipping method

### Actual result (*)

1. There is no shipping method found.

![image](https://user-images.githubusercontent.com/3236677/62134732-ba0c4080-b2e9-11e9-8a46-e9d26fdb3ad4.png)

### Way of fixing (*)
Add the white space as an option in the regex. 

`"/^(.+)-(.+)$/"` - Original Regex
`"/^(.+)(\s|-)(.+)$/"` - Fixed Regex

This way it will get the correct prefix and will show the

**Comment by heldchen** [comment]
this should be a configurable option (with a sane default) IMO, as it makes too many assumptions that are valid for just one (US?) / a few countries currently.

**Comment by engcom-Bravo** [comment]
Hello @milan-vugrinchev, Thanks for applying. Would You please give us a reference to the official source on Table Rate shipping method in Magento where it is said that the rate of a particular record in the DB table will be applied to all zip-codes starting with a string given in dest_zip field of that record. Or anything else saying that dest_zip value is not necessarily supposed to be a valid zip-code in order for the according rate to be applied. Thank You.

**Comment by delve-game-studios** [comment]
Can’t really give anything of value just stating that this should be an issue because it’s not said that the TableRate shipping method for (for example US only method) that’s the idea behind my issue. UK zip codes start with String and are separated by space not a dash. I would only like this to be an official release instead of me touching vendor folder. That’s all.

Best Regards,
Milan Vugrinchev

**Comment by engcom-Bravo** [comment]
Thank You for replly @milan-vugrinchev. Seems there is some misunderstanding. If You store not the prefix but the valid UK zip-code in the DB (like AB31 2AR with a space in between, just as it should be) then everything will work properly. And as so then where the bug is?

**Comment by engcom-Bravo** [comment]
Or @milan-vugrinchev You mean there is no bug. You simply want Magento to be able to work with prefixes and not just with the full zip-codes?

**Comment by delve-game-studios** [comment]
Of course… otherwise we’ll have a 100GB table only for zip codes and for each zip code there’ll be at least 20 rows for price per package_value_with_discount … which makes this method inefficient. It has the functionality to check for prefixes but only one kind… not everywhere the zip code is separated from the prefix with a dash in some countries is a space.

Best Regards,
Milan Vugrinchev

**Comment by engcom-Bravo** [comment]
Ok, @milan-vugrinchev, now everything has become clear. We are confirming Your issue. Thanks for reporting.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18786` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
