### ISSUE TITLE
[2019-07-30 12:11:53] [ERROR] SyntaxError: Unexpected token < in JSON at position 83

### ISSUE THREAD

**Issue by stenovishal98** [magento/magento2#23945]
I am Working on localhost. when I click in place order button   then I saw console error "[2019-07-30 12:11:53] [ERROR] SyntaxError: Unexpected token < in JSON at position 83". how I solve this issue.please guys help me.
![error](https://user-images.githubusercontent.com/53423249/62107700-cda5b000-b2c5-11e9-8865-d54f93ea794f.png)

**Comment by engcom-Charlie** [comment]
Hi @stenovishal98 ! Can you give me more info about you Magento configuration?

**Comment by engcom-Charlie** [comment]
I close this issue because we can't reproduce it.
