### ISSUE TITLE
Issue uploading table rate in magento 2

### ISSUE THREAD

**Issue by reymart081678** [magento/magento2#23944]
### Preconditions (*)

1. Magento ver 2.2.9 under builderall

### Steps to reproduce (*)

1. Export csv file under table rate
2. Update table rate table based on the shipping rate in our country
3. Upload table rate using upload button
4. Save config but an error occurred
![tableRateExport](https://user-images.githubusercontent.com/4920883/62093530-33853e00-b2ac-11e9-9abf-0331db6d0fb5.png)

### Expected result (*)

1. Successful upload

### Actual result (*)

1. Below is the screenshot of error
![tableRateError](https://user-images.githubusercontent.com/4920883/62093505-19e3f680-b2ac-11e9-8f9d-4ac4151f51ba.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23944-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23944-2-3-develop.instances.magento-community.engineering/admin](https://i-23944-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@reymart081678 - I have verified this issue in Magneto 2.3 Instance. But I haven't reproduced this issue.
@reymart081678 - Can you please share the table rate file which you have uploaded?

**Comment by reymart081678** [comment]
Hi Ajij,
   Please see attach table file.

Thank you

**Comment by ajijshekh123** [comment]
@reymart081678 - No attachment file is available in your previous message.

**Comment by reymart081678** [comment]
Using github now to attach the file, but it says "we don't support that file type" .csv
re save as xsls. resave as .csv later
[tablerates.xlsx](https://github.com/magento/magento2/files/3446151/tablerates.xlsx)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23944-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23944-2-3-develop.instances.magento-community.engineering/admin](https://i-23944-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@reymart081678 - Successfully uploaded your attached file in Magento Instance 2.3 and It's not reproduced.
**See attached the Video:**

![2019-07-30_16-50-26](https://user-images.githubusercontent.com/24711761/62184445-bc1edf80-b37b-11e9-8f85-31966d1fd80a.gif)

**Comment by ajijshekh123** [comment]
@reymart081678 - Please update here.

**Comment by reymart081678** [comment]
Hi Ajij,
   I cannot upgrade to 2.3 for now. Current version is 2.2.9

**Comment by ajijshekh123** [comment]
Hi @reymart081678, 
If it feasible in your end please upgrade the Magento version and verify the issue.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by ajijshekh123** [comment]
@reymart081678 - feel free to reopen the issue if you have found in Magento 2.3 instance.
