### ISSUE TITLE
using quick edit on CMS pages changes store view to default

### ISSUE THREAD

**Issue by GavChap** [magento/magento2#2394]
Magento ver. 2.0.0-rc2

To reproduce:

1) Go to content -> Elements -> Pages
2) Click on a page to get quick edit
3) Click save

The Store View will have changed from All Store Views to Main Website -> Main Website Store -> Default Store View

**Comment by shiftedreality** [comment]
Hi @GavChap 

Internal ticket MAGETWO-47931 was created to fix this issue.

**Comment by shiftedreality** [comment]
Fix was merged to develop branch. Closed.
