### ISSUE TITLE
Incorrect Quantity Displayed In Admin Area when used 'Qty Uses Decimals'

### ISSUE THREAD

**Issue by nmalevanec** [magento/magento2#23940]
###### Preconditions (*)

1. Magento 2.3-develop
###### Steps to reproduce (*)
1. Create a product with the following configurations
Minimum Qty Allowed in Shopping Cart = 2.14
Qty Uses Decimals = Yes
Qty Increments = 2.14
1. Navigate to Storefront and add created simple product to cart with qty = 2.14
1. Navigate to Checkout and verify, qty still = 2.14
1. Place order.
1. Navigate to admin area order page.
1. Verify 'Items Ordered' tab
1. Create Shipment
1. Open Order details page on the fronend.
1. Open "Order Shipments" tab
1. Check "Qty shipped" 

###### Expected result (*)

1. Column 'Qty' has 'Ordered 2.14' value
###### Actual result (*)

1. Column 'Qty Shipped' = 2

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18739`, `MC-18740` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
