### ISSUE TITLE
magento 2.3.2 back end product not visible showing error

### ISSUE THREAD

**Issue by sunbeamshawls** [magento/magento2#23959]
Just installed magento 2.3.2 but on the front end the products are displaying which are default sample products while installing magento 2.3.2

BUT ON THE BACK END ADMIN PANEL WHEN YOU CLICK ON CATALOG > PRODUCT IT SHOWS ERROR

A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.
![product not loading](https://user-images.githubusercontent.com/53515140/62201629-6bbc7780-b3a5-11e9-9c2c-f8fae98bf1bb.png)

**Comment by engcom-Charlie** [comment]
Hi @sunbeamshawls! Can't reproduce this issue on Magento 2.3.2 and 2.3-develop. I think that problem only on your instance. You can try to re-install magento for fix it. 
Thank for your report!
