### ISSUE TITLE
About the Plugin to modify the Product\Collection::load function

### ISSUE THREAD

**Issue by wenfei158** [magento/magento2#23956]
### Summary (*)
We want to use MongoDB to save some product attributes for performance. So I want to override the function  `\Magento\Catalog\Model\ResourceModel\Product\Collection::load`  by plugin.

But we found it will make `Infinite loop` to customize `\Magento\Catalog\Model\ResourceModel\Product\Collection::load`  by plugin.

### Examples (*)

The ProductCollection.php
```
<?php
namespace Magento2\MongoCatalog\Plugin;

class ProductCollectionPlugin
{
    public function afterLoad(
        \Magento\Catalog\Model\ResourceModel\Product\Collection $subject,
        \Magento\Catalog\Model\ResourceModel\Product\Collection $result
    ) {
        foreach ($result as $product) {
            $product->getId();
        }
    }
}
```
di.xml
```
    <type name="Magento\Catalog\Model\ResourceModel\Product\Collection">
        <plugin name="AddMongoProcess" type="MonotaRO\MongoCatalog\Plugin\ProductCollectionPlugin" sortOrder="1" disabled="false" />
    </type>
```
 The result is  `Infinite loop` .

### Proposed solution

I have analyzed the code, and found the problem is  `Magento\Framework\Data\Collection::getIterator` .

```
    /**
     * Implementation of \IteratorAggregate::getIterator()
     *
     * @return \ArrayIterator
     */
    public function getIterator()
    {
        $this->load();
        return new \ArrayIterator($this->_items);
    }
```

It will call the load function himself again and again.  The result is  `Infinite loop` .

If It is possible, I think It will resolve this problem by changing the source code like as follows.
```
    /**
     * Implementation of \IteratorAggregate::getIterator()
     *
     * @return \ArrayIterator
     */
    public function getIterator()
    {
        if(!$this->isLoaded()) {
            $this->load();
        }
        return new \ArrayIterator($this->_items);
    }
```

If It is loaded, do not load again. 
It will not generate any other effects, but make the plugin able to use for `\Magento\Catalog\Model\ResourceModel\Product\Collection::load`  .

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19043` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
After clarification with Community Engineering Team, the issue was considered as incorrect usage of collection loading. The collection's `load` method is not responsible for returning items itself, thus it's not a good idea to affect collection items results in `afterLoad` plugin.
It should be possible to add an observer on *_after_load event or even plugin on the `getItems` method if you want to iterate through the collection results.

Thank you!
