### ISSUE TITLE
It would be nice to have an ability to skip the current module name prefix in layout files for CSS/JS declarations like it is possible for templates

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2395]
See, for example:
https://github.com/magento/magento2/blob/2335247d4ae2dc1e0728ee73022b0a244ccd7f4c/app/code/Magento/Catalog/view/adminhtml/layout/catalog_product_new.xml#L55

```
<block 
    class="Magento\Catalog\Block\Adminhtml\Product\Edit\Js" 
    name="catalog_product_js" 
    template="catalog/product/js.phtml"
/>
```

is the same as

```
<block 
    class="Magento\Catalog\Block\Adminhtml\Product\Edit\Js" 
    name="catalog_product_js" 
    template="Magento_Catalog::catalog/product/js.phtml"
/>
```

But it is not possible for CSS and JS declarations:
https://github.com/magento/magento2/blob/2335247d4ae2dc1e0728ee73022b0a244ccd7f4c/app/code/Magento/Catalog/view/adminhtml/layout/catalog_product_new.xml#L12

```
<css src="Magento_Catalog::product/product.css"/>
```

It would be nice to have an abilily skip the current module prefix and use some shorter syntax like `<css src="product/product.css"/>` or `<css src="::product/product.css"/>`

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/It-would-be-nice-to-have-an-ability-to-skip-the-current-module/idi-p/45344).
