### ISSUE TITLE
"Merge On Conflict" missing the Label in "New Synonym Group" form

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23953]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go Marketing -> Search Synonyms -> New Synonym Group
2. Check the form

![image](https://user-images.githubusercontent.com/8234209/62174769-4576e780-b365-11e9-892d-76cf17d582b2.png)

### Expected result (*)

1. Has the label

### Actual result (*)

1. No Label (User can not understand, must hover on ? to read) => BAD UX

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23953-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23953-2-3-develop.instances.magento-community.engineering/admin](https://i-23953-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18779` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23954 by @edenduong in 2.3-develop branch
Related commit(s):
 - [c2de0bacb3040baa477629eedf89aa1dfb0dcf60](https://github.com/magento/magento2/commit/c2de0bacb3040baa477629eedf89aa1dfb0dcf60)

The fix will be available with the upcoming 2.3.4 release.
