### ISSUE TITLE
Minicart shows HTML when using file upload custom option

### ISSUE THREAD

**Issue by erfanimani** [magento/magento2#23955]
### Preconditions (*)

1. Tested on Magento 2.3.2
2. Luma theme

### Steps to reproduce (*)

1. As an admin, create a product with a custom option with type file upload
2. As a customer, add the product to the cart after having selected a file
3. Open up the mini cart, and expand "See Details" for the recently added product

### Expected result (*)

1. See the custom option label with the filename of the uploaded file

### Actual result (*)

1. See the custom option label, but with a whole lot of HTML

It seems that HTML is being escaped on the minicart template, which is correct. However, the custom option value contains HTML; namely an anchor link to the uploaded file. It would be OK with me if this HTML was stripped — I don't necessarily need a link to the uploaded file. Just showing the filename is enough. Security wise that's probably the most straightforward solution, otherwise escaping has to be either dropped from the custom option value on the template, and done on a different level (possibly in `\Magento\Checkout\CustomerData\DefaultItem::doGetItemData`).

![image](https://user-images.githubusercontent.com/930470/62180184-9ac0f200-b381-11e9-83bf-7a971616e4f9.png)

**Comment by erfanimani** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @erfanimani. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @erfanimani, here is your [Magento instance](https://i-23955-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23955-2-3-develop.instances.magento-community.engineering/admin](https://i-23955-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by erfanimani** [comment]
Reproduced:

![image](https://user-images.githubusercontent.com/930470/62180184-9ac0f200-b381-11e9-83bf-7a971616e4f9.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18780` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tiagobnu** [comment]
#mm19br

**Comment by magento-engcom-team** [comment]
@tiagobnu thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by tiagobnu** [comment]
Resolved in https://github.com/magento/magento2/pull/24237
