### ISSUE TITLE
Configurable product is not display shipping information on checkout page

### ISSUE THREAD

**Issue by bhaveshpp** [magento/magento2#23957]
### Preconditions (*)

1. Magento ver. 2.3.2
2. Browser: Any
3. Hosted on Apache2
### Steps to reproduce (*)

1. Install Magento 2.3.2
2. Create one simple product and one configurable product with any attribute [here I have use color].
3. First, add the simple product to cart and proceed checkout it works normally [with the simple product is redirected to the [magento project]/checkout/#shipping default] it will display Shipping information. Place order and next...
4. Add configurable product to cart and proceed checkout, it not working properly [with the configurable product it will automatically redirect to [magento project]/checkout/#payment]. /#shipping is not displayed.
5. Every time when I have tried to proceed checkout with configurable Product it will automatically redirect on payment section.
6. I have checked with 5/0 Weight for the configurable product but the same issue is faced.
### Expected result (*)

1. For any product [configurable/simple/etc] the process will be the same. 
2. shipping is required for a product.

### Actual result (*)

1. Here we can see the Configurable Product demo[[Configurable Product](https://www.screencast.com/t/4F85gWEPZs)].
2. Here we can see the Simple Product demo [[Simple product](https://www.screencast.com/t/8z8UR7X4)].
3. When one simple product and one configurable Product add to cart and Proceed to checkout then it will work fine. [ [simple+configurable product](https://www.screencast.com/t/hLe0TEyJgRhu)].

**Comment by edenduong** [comment]
@bhaveshpp : Please check the children of the configurable product. I think it is the Virtual Product. So it doesn't have the shipping.

**Comment by TomashKhamlai** [comment]
@bhaveshpp, exactly the same behavior described in #23912. I thought that the reason is 0 price or 0 weight of the configurable when price and weight have only configurable variants (simple product with some color) but it looks like I was wrong.

**Comment by TomashKhamlai** [comment]
@bhaveshpp, if your problem was solved please close this issue.

**Comment by bhaveshpp** [comment]
@TomashKhamlai Thank you 
@edenduong Thank you for Providing me solution 
My issue is solved.
