### ISSUE TITLE
Customer Group / Tier Prices not applied

### ISSUE THREAD

**Issue by matthiashamacher** [magento/magento2#23969]
### Preconditions (*)

1. Magento 2.3.1 CE

### Steps to reproduce (*)

1. Add a new Customer Group
2. Assign a customer the new customer group
3. Add a tier price to a product
4. Save the product
5. Log in as the customer
6. Open the product
<img width="403" alt="Screenshot 2019-08-01 at 09 44 28" src="https://user-images.githubusercontent.com/32356549/62274858-fb633400-b440-11e9-8499-57d6ffe70513.png">
<img width="852" alt="Screenshot 2019-08-01 at 09 41 45" src="https://user-images.githubusercontent.com/32356549/62274684-a1626e80-b440-11e9-8e38-7b780a898dbf.png">

### Expected result (*)

1. The price on the category/product detail/cart/checkout page should be 150.60€

### Actual result (*)

1. The price on all pages is the base price
<img width="375" alt="Screenshot 2019-08-01 at 09 43 52" src="https://user-images.githubusercontent.com/32356549/62274870-04540580-b441-11e9-918d-6155d5bd03d9.png">

**Comment by matthiashamacher** [comment]
That the Price isn't 150.60€ is default Magento behaviour because the price is higher than the base price. 
Tier Prices are only shown if the Tier Price which would be shown is lower than the base price.

**Comment by bikash-webo** [comment]
@matthiashamacher did you found any technique to override base price when tier prices is higher than base price?
