### ISSUE TITLE
Azure BlobFuse + Magento 2 Static Files sync

### ISSUE THREAD

**Issue by murali290987** [magento/magento2#23960]
### Preconditions (*)

1. Magento Version 2.3.1

### Steps to reproduce (*)

1. RHEL 7.4
2. Azure Virtual Machine
3. Azure Database for MySQL server
4. Install BlobFuse for file sync between VM and BlobStorage https://github.com/Azure/azure-storage-fuse
5. Run deployment command - sudo php -dmemory_limit=6G ../bin/magento setup:static-content:deploy

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/993891/62203076-1f266b80-b3a8-11e9-92ff-b286e0b97059.png)

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/993891/62203019-01590680-b3a8-11e9-8ae7-20b9ed1b1e64.png)
2.

**Comment by engcom-Alfa** [comment]
Hi @murali290987 ! 
Thank you for your report.
Probably problem is with "Blob Fuse" extension. 
You could refer to the [Azure Community Forum](https://azure.microsoft.com/en-in/support/community/)   site for advice or general discussion about this issue.
Or if you'd like to update the issue, please reopen it.
