### ISSUE TITLE
Unable to get quote items in custom module phtml file or in observer.

### ISSUE THREAD

**Issue by btarshad** [magento/magento2#23961]
I have created a phtml file in my custom module.
Path: app/code/Essence/Fcf/view/frontend/templates/packages.phtml

I called this file in my cms page "packages"  by following code:

> {{block class="Magento\Framework\View\Element\Template" template="Essence_Fcf::packages.phtml" cacheable="false"}}

Url: http://essence.onlineprojectprogress.com/packages

I have listed here a specific category products. I have also added "Add to Cart" button on each product.

After adding products to the cart, products are successfully added to cart which I can see in my minicart dropdown on header.

What I want is that when I add product to cart, I want to get all information of quote item of cart is to be listed in same page.

**My code:**
`	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();    `
`	$cart = $objectManager->get('\Magento\Checkout\Model\Cart');`
`	$items = $cart->getQuote()->getAllItems();`
`	foreach($items as $item) {`
`		     echo 'ID: '.$item->getProductId().'<br />';`
`		     echo 'Name: '.$item->getName().'<br />';`
`		echo 'Sku: '.$item->getSku().'<br />';`
`		echo 'Quantity: '.$item->getQty().'<br />';`
`		echo 'Price: '.$item->getPrice().'<br />';`
`		echo "<br />";            `
`	}`

It is returning nothing.

I also want an event to be executed after add to cart. For this I created and event and try to get quote item in observer file but nothing is returning there as well.

I have also used session but it is also not working.

Please help.

@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by btarshad** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @btarshad. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @btarshad, here is your [Magento instance](https://i-23961-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23961-2-3-develop.instances.magento-community.engineering/admin](https://i-23961-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by btarshad** [comment]
I cannot produce this issue only on admin panel but in my custom module.

**Comment by engcom-Charlie** [comment]
Hi @btarshad! I goes to your site and when i click add to card i saw this code is worked:
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$items = $cart->getQuote()->getAllItems();
foreach($items as $item) {
echo 'ID: '.$item->getProductId().'<br />';
echo 'Name: '.$item->getName().'<br />';
echo 'Sku: '.$item->getSku().'<br />';
echo 'Quantity: '.$item->getQty().'<br />';
echo 'Price: '.$item->getPrice().'<br />';
echo "<br />"; 
}
Only one thing doesn't worked its $item->getPrice(). 
![image](https://user-images.githubusercontent.com/51680850/62214808-74fe1200-b3ae-11e9-866f-562f9b7b672a.png)

So i understand you are fixing it now.
Do you really need a help with it now?
Thank for your report!

**Comment by btarshad** [comment]
I really need help.

That result is coming using objectmanager in observer that I cannot use. I want to use observer default feautres as below:

`    public function execute(EventObserver $observer)`
 `   {`
    `    $item = $observer->getQuoteItem();`
`	}`

I am using following event:
checkout_cart_product_add_after

But it returns nothing.

Second thing, I want to get cart item in my phtml file using objectmanager but it returns nothing.

Please help.

**Comment by engcom-Charlie** [comment]
@btarshad in my local $item = $observer->getQuoteItem(); works fine, but i tested it not in custom module.

**Comment by engcom-Charlie** [comment]
@btarshad well i check your site again and i see you fix it.
I close this issue.
Thank you for your report!

**Comment by btarshad** [comment]
But it is not working in my module. See my packages.phtml file full code:

`<div class="col-md-12"><h2 class="page-title">Choose how many guests per package:</h2></div>`
`<?php`
`$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();       ` 

`$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');`
`$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');`
`$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');`
`$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');`
`$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');`

`$cart = $objectManager->get('\Magento\Checkout\Model\Cart');`
`$items = $cart->getQuote()->getAllItems();`
`foreach($items as $item) {`
`    echo 'ID: '.$item->getProductId().'<br />';`
`    echo 'Name: '.$item->getName().'<br />';`
`    echo 'Sku: '.$item->getSku().'<br />';`
`    echo 'Quantity: '.$item->getQty().'<br />';`
`    echo 'Price: '.$item->getPrice().'<br />';`
`    echo "<br />";            
`}

`$categoryId = 3; // YOUR CATEGORY ID`
`$category = $categoryFactory->create()->load($categoryId);`
`$categoryProducts = $category->getProductCollection() ->addAttributeToSelect('*');`							 
` $categoryProducts->addAttributeToSort('featured', 'DESC');`      
`foreach ($categoryProducts as $product) {`
`$currentQty = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());`
`$addToCartUrl =  $listBlock->getAddToCartUrl($product);`
`$price = $objectManager->create('Magento\Framework\Pricing\Helper\Data')->currency($product->getPrice());`
`?>`
`<div class="col-md-6">`
`<div class="package-box package-box-1 <?php if($product->getFeatured()) {echo "featured_cont"; } ?>">`
`<h3><?php echo $product->getName(); ?></h3>`
`<?php echo $product->getDescription(); ?>`
`<strong><?= $price; ?> <span class="currency">USD</span></strong>`
`<form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">`
`<?php echo $block->getBlockHtml('formkey')?>`
`<div class="remain_text">Ticket Remaining: <?= $currentQty; ?></div>`
`<div class="qty_section">`
`<div class="form-group main-select-wrap">`
`<select class="form-control main_qty" name="qty" data-proid="<?= $product->getId(); ?>" style="width: 22%;float:left;margin-right:5px;">`
`<option value="">Quantity</option>`
`<option value="1">1</option>`
`<option value="2">2</option>`
`<option value="3">3</option>`
`<option value="4">4</option>`
`</select>`
`<div class="inner-select" id="adult_child_qty_<?= $product->getId(); ?>" style="display:none">`
`<select class="form-control" name="essence[male_qty]">`
`<option value="">Male</option>`
`<option value="1">1</option>`
`<option value="2">2</option>`
`<option value="3">3</option>`
`<option value="4">4</option>`
`</select>`
`<select class="form-control" name="female_qty">`
`<option value="">Female</option>`
`<option value="1">1</option>`
`<option value="2">2</option>`
`<option value="3">3</option>`
`<option value="4">4</option>`
`</select>`
`<select class="form-control" name="child_qty">`
`<option value="">Child</option>`
`<option value="1">1</option>`
`<option value="2">2</option>`
`<option value="3">3</option>`
`<option value="4">4</option>`
`</select>`
`</div>`
`</div>`
`</div>`
`<button type="submit" title="Add to Cart" class="btn"><span>Add</span></button>`
`</form>`
`</div>`
`</div>`
`<?php } ?>`
`<div class="col-md-12" id="total_calculations">`
`<div class="total_guests_wrap" style="font-size:20px">`
`<span><strong>Total Guests:</strong> </span> <span class="total_guests_number"></span>`
`</div>`
`<div class="total_amount_wrap" style="font-size:20px">`
`<span><strong>Total Amount:</strong> </span> <span class="total_amount_number"></span>`
`</div>`
`<div class="package-box text-center">`
`<a class="btn" href="<?php echo $block->getUrl('checkout', ['_secure' => true]);?>">Purchase</a>`
`</div>`
`</div>`
`<script>`
`// <![CDATA[`
 ` require([`
`  'jquery',`
 `   'domReady!'`
 ` ], function (jQuery) {`
`setTimeout(function(){`
`var subtotal = jQuery('.subtotal .price-container .price-wrapper .price').text();
jQuery(".total_amount_number").text(subtotal);`
`}, 3000);`
 ` });`
 ` // ]]>`
`</script>`
`<script type="text/javascript">`
 `  require([ 'jquery'], function(jQuery){`
`/* On select main quantity */`
`jQuery('.main_qty').change(function(){`
`var proid 	 = jQuery(this).attr('data-proid');`
`if(jQuery(this).children("option:selected").val() != ''){`
`jQuery('#adult_child_qty_'+proid).show();`
`} else {`
`jQuery('#adult_child_qty_'+proid).hide();`
`}`
`});`
`</script>`

**Comment by engcom-Charlie** [comment]
@btarshad  can you drop me your module?

**Comment by btarshad** [comment]
[Essence.zip](https://github.com/magento/magento2/files/3455812/Essence.zip)

**Comment by engcom-Charlie** [comment]
@btarshad thank for contributing! Sorry,but i can't use your module to test. 
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.Or you can post your issue on [Stackoverflow](https://stackoverflow.com/) and someone will give a decision.
