### ISSUE TITLE
middleName not present in Order List from Admin

### ISSUE THREAD

**Issue by joinso** [magento/magento2#23963]
### Preconditions (*)

1. Magento 2.3
2.

### Steps to reproduce (*)

1. In Magento Admin, setup MiddleName as visible on Customer Configuration
2. Register a new customer and provide First Name, Middle Name and Last Name.
3. Place an order.
4. Go to Admin > Sales

### Expected result (*)

1. "Middle Name", "Prefix" and "Suffix" must shown.

### Actual result (*)

1. "Middle Name" is not present in columns. only "Billing Firstname" or "Shipping Firstname"

Regards,
JOINSO

### Additional info from Engcom 
Reproducible on 2.4-develop

*Steps to reproduce:*

1. In Magento Admin, setup MiddleName as visible on Customer Configuration
2. Register a new customer and provide First Name, Middle Name and Last Name.
![Customer](https://user-images.githubusercontent.com/67371013/98372470-7d7bd880-2046-11eb-8cbb-3f8b18031158.png)
3. Go to store and place an order.
4. Go to Admin > Sales > Orders and observe Bill-to Name and Ship-to Name colums

**Actual result (*)**
"Middle Name" is not present in columns. only "Billing Firstname Lastname" or "Shipping Firstname Lastname"
![Order](https://user-images.githubusercontent.com/67371013/98372676-d21f5380-2046-11eb-8db5-e9d664aa85f8.png)

**Comment by engcom-Bravo** [comment]
Hello @joinso. Thanks for applying. In fact Name and Address Options section where middle name, prefix and suffix are configured is responsible for displaying these options in Customers Account (please see official Magento [user guide])(https://docs.magento.com/m2/ce/user_guide/customers/name-address-options.html))
And there everything works as expected. There is nowhere said that all of the configured options are supposed to be displayed everywhere where the customer is mentioned.

**Comment by jordipujol-mcneel** [comment]
But must be displayed in Order List, like First Name or Last Name.

**Comment by engcom-Bravo** [comment]
Reproducible on the latest 2.4-develop. Additional info from Engcom is added to the Description

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38959` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
