### ISSUE TITLE
"New Tax Rate" missing  validation => data is automatically changed when saving

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23967]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Store -> Tax Zone and Rate
2. New Tax Rate
3. Fill: 12345678901 (over 10 character) in "Zip/Post Code"
4. Save
5. Back to the tax rate which is saved
6. See "Zip/Post Code"

### Expected result (*)

1. Don't allow to save

### Actual result (*)

1. Saved. But the "Zip/Post Code" cut to 1234567890

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18817` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
