### ISSUE TITLE
Can't install through composer

### ISSUE THREAD

**Issue by vmasciotta** [magento/magento2#2396]
If You install through composer You will get this error:

```
 [Composer\Downloader\TransportException]                                                                                                     
  The "https://repo.magento.com/archives/magento/composer/magento-composer-1.0.2.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found)  
```

**Comment by kassner** [comment]
repo.magento.com needs basic auth for Composer (it was using packages.magento.com until RC2).

You can setup `~/.composer/auth.json` with your Magento.com login details:

```
{
    "http-basic": {
        "repo.magento.com": {
            "username": "email@example.com",
            "password": "plain-text-password"
        }
    }
}
```

We need at least tokens, but direct access would be the best case scenario, but I'm not sure if Magento will remove the auth, they already ignored my complaint for M1 and patches :(

**Comment by mbrinton01** [comment]
Hello @vmasciotta we also have an example for this on the page http://devdocs.magento.com/guides/v2.0/install-gde/prereq/dev_install.html under "Creating an authorization file."  Closing the issue, but please re-open if you continue to have a problem getting it to work.

**Comment by vmasciotta** [comment]
Oh thank U, I totally missed that part!

**Comment by woei66** [comment]
according to the doc http://devdocs.magento.com/guides/v2.0/install-gde/prereq/dev_install.html#instgde-prereq-compose-install
you should create a ~/.composer/auth.json file
there is "github-oauth" field and you can get the value from https://github.com/settings/tokens
