### ISSUE TITLE
Unable to place an order

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#23974]
### Preconditions (*)
1. Magento 2.3
2. Active Store with id 1.
3. Created Product with SKU 'TEST-123' with qty 1 and assigned to website of Store 1.
4. Backorders disabled.
5. Enabled Flatrate shipping method (Admin Panel -> Stores -> Configuration -> Sales -> Shipping Methods -> Flat Rate).
6. Enabled Check/Money Order payment method (Admin Panel -> Stores -> Configuration -> Sales -> Payment Methods -> Check / Money Order).
7. US is allowed country (Admin Panel -> Stores -> Configuration -> General -> General -> Country Options -> Allow Countries).

### Steps to reproduce (*)
1. Execute code under

```
$om = ObjectManager::getInstance();
// CREATE A CART
/** @var \Magento\Quote\Api\CartManagementInterface $cartManagement */
$cartManagement = $om->get(\Magento\Quote\Api\CartManagementInterface::class);
/** @var \Magento\Quote\Api\CartRepositoryInterface $cartRepo */
$cartRepo = $om->get(\Magento\Quote\Api\CartRepositoryInterface::class);
$cartId = $cartManagement->createEmptyCart();
$cart = $cartRepo->get($cartId);

// CREATE ADDRESS
$addressFactory = $om->get(\Magento\Quote\Api\Data\AddressInterfaceFactory::class);
/** @var \Magento\Quote\Api\Data\AddressInterface $address */
$address = $addressFactory->create(
    [
        'data' => [
            \Magento\Quote\Api\Data\AddressInterface::KEY_COUNTRY_ID => 'US',
            \Magento\Quote\Api\Data\AddressInterface::KEY_REGION_ID => 15,
            \Magento\Quote\Api\Data\AddressInterface::KEY_LASTNAME => 'Doe',
            \Magento\Quote\Api\Data\AddressInterface::KEY_FIRSTNAME => 'John',
            \Magento\Quote\Api\Data\AddressInterface::KEY_STREET => 'example street',
            \Magento\Quote\Api\Data\AddressInterface::KEY_EMAIL => 'customer@example.com',
            \Magento\Quote\Api\Data\AddressInterface::KEY_CITY => 'Los Angeles',
            \Magento\Quote\Api\Data\AddressInterface::KEY_TELEPHONE => '937 99 92',
            \Magento\Quote\Api\Data\AddressInterface::KEY_POSTCODE => 12345
        ]
    ]
);

//FILL THE CART
$cart->setCustomerEmail('admin@example.com')
     ->setCustomerIsGuest(true)
     ->setStoreId(1)
     ->setBillingAddress($address)
     ->setShippingAddress($address);
$cart->getPayment()->setMethod('checkmo');
$cart->getShippingAddress()->setShippingMethod('flatrate_flatrate');
$cart->getShippingAddress()->setCollectShippingRates(true);
$cart->getShippingAddress()->collectShippingRates();
$cartRepo->save($cart);

// ADD THE PRODUCT
/** @var \Magento\Catalog\Api\ProductRepositoryInterface $productRepo */
$productRepo = $om->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
$product = $productRepo->get('TEST-123');

$requestData = [
    'product' => $product->getProductId(),
    'qty' => 1
];

$request = new DataObject($requestData);
$cart->addProduct($product, $request);
$cartRepo->save($cart);
//PLACE THE ORDER
$cartManagement->placeOrder($cart->getId());
```

### Expected result (*)
1. Order has been placed.

### Actual result (*)
1. Error appears `The requested qty is not available`.

### Description
In the deep, problem is related to \Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList.

In the method \Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList::getQty is used run-time cache for quantity of Product and Quote Items.

The problem can appear when in this method come Quote Item without 'entity_id' (before save, when `addProduct` method is called).
And, right after that, in this method come the same Quote Item but with 'entity_id' (validation during order placement). 
In result, it will think that there are 2 different items (but there is only one) and will use `x2` Qty for validation.

The error will come from https://github.com/magento/magento2/blob/cea3e798c145e37f6fb821687dadd0f043352d94/app/code/Magento/CatalogInventory/Model/StockStateProvider.php#L166
In described example, `$qty` will be 1 and `$summaryQty` will be 2.

**The easiest way to understand what is going is to debug the code provided below with a breakpoint in** https://github.com/magento/magento2/blob/cea3e798c145e37f6fb821687dadd0f043352d94/app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator/QuoteItemQtyList.php#L31

**Comment by shikhamis11** [comment]
Hi @swnsma 
Thank you for reporting this issue . May be the issue is related to #18812.

**Comment by swnsma** [comment]
Hi @shikhamis11,
Agree. This is the same issue. 
I am closing current issue as duplicate.
