### ISSUE TITLE
"This item has weight" switcher is not sensitive to weight changes

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#23977]
When the product is virtual Merchant cannot set the weight before he hasn't switched to "The item has weight" and from this point, the issues sounds pointless. But there is another way to update weight from Magento UI with virtual configurable variants

### Preconditions (*)

1. Explanation to #23957 and #23912

### Steps to reproduce (*)

1. Create Configurable Product.
Fill name, SKU and price = 0.00
Leave everything else as is
Click **Create Configurations** button
Select attribute `color`
black - $1 - 1000, white - $2 - 1000
Click Generate Products
Click Save Product
2. Verify that the product variants are of virtual type
3. Edit configurable product
Click "Edit Configurations"
End generation process without any changes
Change the weight of all variations to 1 and set the quantity of the first variation to 0 in the configuration grid of the product edit page
4. Save the product

### Expected result (*)

1. Qty change to 0 leads to the "Out of Stock" state of the product
2. Weight change leads to the "This item has weight" state and the virtual product is simple product now.

### Actual result (*)

1. Qty change to 0 leads to the "Out of Stock" state of the product
2. Weight change does not lead to the "This item has weight state" however the weight was saved even in grey color (disabled input)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18856` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by TomashKhamlai** [comment]
Closed due to #24013
