### ISSUE TITLE
Product image disappeared in product view page after appearing for a while

### ISSUE THREAD

**Issue by btarshad** [magento/magento2#23973]
This is my url:
http://essence.onlineprojectprogress.com/basic-package.html

This is a configurable product. When this url loads, product image appears for a seconds and disappears suddenly.

![asdfe](https://user-images.githubusercontent.com/53523233/62282688-983bc680-b46d-11e9-840c-a87f8becb35b.png)

What could be the issue?

**Comment by krishprakash** [comment]
Hi @btarshad. Thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
It will help faster for you.
Thank You.
