### ISSUE TITLE
Iframe element fails in product WYSIWYG editor on Magento 2.2.9

### ISSUE THREAD

**Issue by mdesplenter** [magento/magento2#23970]
### Preconditions (*)
1. Magento 2.2.9 & 2.3-develop
2. The condition is to switch the tinyMCE from version 4 to version 3 in the backend config (General > Content Management)

### Steps to reproduce (*)
1. Go to Youtube, select a movie, and use the embed function
2. Go to a product
3. Add this line of code in the text area for content
4. Switch to the editor

or

1. Open a product that already has an iframe in the editor

### Expected result (*)
1. The iframe area shows up in the editor area.

### Actual result (*)

1. An javascript error is shown: "error: error in [unknown object].fireEvent(): event name: tinymceSetContent error message: data is undefined"
2. The editor stops working, you can't edit anything.

### Temporary fix
As a hotfix, I reverted the lib/web/tiny_mce folder to the 2.2.8 version. It seems that the JSON.parse for iframe objects isn't correctly implemented.

**Comment by mdesplenter** [comment]
@magento give me 2.2.9 instance

**Comment by magento-engcom-team** [comment]
Hi @mdesplenter. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by mdesplenter** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mdesplenter. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mdesplenter, here is your [Magento instance](https://i-23970-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23970-2-3-develop.instances.magento-community.engineering/admin](https://i-23970-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mdesplenter** [comment]
I cannot reproduce this in 2.3.x , it's a different editor.
Testing on a local vanilla 2.2.9 instance gives the same error.

**Comment by mdesplenter** [comment]
@magento no , not in 2.2.3

**Comment by engcom-Charlie** [comment]
Hello @mdesplenter 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

**Comment by pemann** [comment]
It seems like this commit is to blame: https://github.com/magento/magento2/commit/f2b87a63e846525b1addd00fa48198391d4a324a#diff-1ac9393c18718fce8d3b2eed7ce35bcb

**Comment by svenakela** [comment]
I can verify the problem, and it works after a revert of the commit @pemann posted.

**Comment by engcom-Charlie** [comment]
@svenakela can you verify the problem on Magento 2.3-develop?

**Comment by Detzler** [comment]
Confirm bug on Magento v2.3.2.

The condition is to switch the tinyMCE from version 4 to version 3 in the backend config (General > Content Management)

**Comment by engcom-Charlie** [comment]
@Detzler thank for contributing! Now i can confirm.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19219` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by johnperricruz** [comment]
Temporary fix using this patch : 

[Magento_v2.2.9_Iframe_Issue.patch.zip](https://github.com/magento/magento2/files/3872978/Magento_v2.2.9_Iframe_Issue.patch.zip)

git apply --whitespace=nowarn Magento_v2.2.9_Iframe_Issue.patch

**Comment by jamie-selesti** [comment]
Do we know when an official fix will be released?

**Comment by Detzler** [comment]
@stale[bot], still relevant

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by yurii-denyshchenko** [comment]
For those of you who had to support Magento 2.2.x, 
This could be a better workaround instead of using dangerous eval('(' + s + ')'):
```
--- a/lib/web/tiny_mce/classes/util/JSON.js
+++ b/lib/web/tiny_mce/classes/util/JSON.js
@@ -92,6 +92,7 @@
 		 */
 		parse: function(s) {
 			try {
+                s = s.replace(/'/g, '"');
 				return JSON.parse(s);
 			} catch (ex) {
 				// Ignore
--- a/lib/web/tiny_mce/tiny_mce_src.js
+++ b/lib/web/tiny_mce/tiny_mce_src.js
@@ -918,6 +918,7 @@
 
 		parse: function(s) {
 			try {
+                s = s.replace(/'/g, '"');
 				return JSON.parse(s);
 			} catch (ex) {
 				// Ignore
--- a/lib/web/tiny_mce/tiny_mce_jquery_src.js
+++ b/lib/web/tiny_mce/tiny_mce_jquery_src.js
@@ -1193,6 +1193,7 @@
 
 		parse: function(s) {
 			try {
+                s = s.replace(/'/g, '"');
 				return JSON.parse(s);
 			} catch (ex) {
 				// Ignore
--- a/lib/web/tiny_mce/tiny_mce_prototype_src.js
+++ b/lib/web/tiny_mce/tiny_mce_prototype_src.js
@@ -945,6 +945,7 @@
 
 		parse: function(s) {
 			try {
+                s = s.replace(/'/g, '"');
 				return JSON.parse(s);
 			} catch (ex) {
 				// Ignore
```
