### ISSUE TITLE
how to fetch swatch_images url in product listing in magento 2 and how to loop them in an array

### ISSUE THREAD

**Issue by Naveesh29** [magento/magento2#23978]

**Comment by engcom-Alfa** [comment]
Hello @Naveesh29 .  Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
