### ISSUE TITLE
Typo in the Merchant Docs about Product Variation Attribute Requirements

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#23979]
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. [Product Variation Attribute Requirements](https://docs.magento.com/m2/ee/user_guide/catalog/product-create-configurable.html#Product-Variation-Attribute-Requirements). Strange: anchor links do not work on https://docs.magento.com, so scroll down to the section **Product Variation Attribute Requirements**

### Expected result (*)

1. `The input type of any attribute that is used for a product variation must be one of the following: Dropdown, Visual Swatch, Text Swatch`
![Screenshot from 2019-08-01 15-25-30](https://user-images.githubusercontent.com/11827230/62293689-d0450880-b471-11e9-89ff-163e168362aa.png)

### Actual result (*)

1. `The input type of any attribute that is used for a product variation must be one of the following: DropdownVisual, SwatchText, Swatch`
![Screenshot from 2019-08-01 15-24-21](https://user-images.githubusercontent.com/11827230/62293690-d0450880-b471-11e9-80db-19c4980b3add.png)

**Comment by TomashKhamlai** [comment]
@lorikrell, is it the right place to create issues on Merchant Documentation?

**Comment by engcom-Alfa** [comment]
Hi @TomashKhamlai please open issue here -> https://github.com/magento/merchdocs
