### ISSUE TITLE
Escaper#escapeXssInUrl (internally: Escaper#escapeScriptIdentifiers) incorrectly convert un-truthy values to empty string

### ISSUE THREAD

**Issue by wpalmer** [magento/magento2#23987]
### Preconditions (*)
1. Any version (up to current HEAD as of July 2nd 2019)

### Steps to reproduce (*)
1. Call Escaper#escapeXssInUrl with value `"0"` (eg: `$this->_escaper->escapeXssInUrl("0");` in block context)

### Expected result (*)
1. return value of `"0"`, ie: unmodified

### Actual result (*)
1. returns an empty string `""`

This appears to be due to lines such as:

        $filteredData = preg_replace('/[\x00-\x1F\x7F\xA0]/u', '', $data) ?: '';
        $filteredData = preg_replace(self::$xssFiltrationPattern, ':', $filteredData) ?: '';

Which assume that the only un-truthy value which could be returned by `preg_replace` is an empty string or `false`

These should be updated to something like:

        $filteredData = preg_replace('/[\x00-\x1F\x7F\xA0]/u', '', $data);
        if ($filteredData === false || $filteredData === '') return '';
        $filteredData = preg_replace(self::$xssFiltrationPattern, ':', $filteredData);
        if ($filteredData === false) return '';

Arguably, this is not the "real" solution. Theoretically, this happens because of the expectation that `escapeXssInUrl` should only be called on "full" URLs, and is intended to remove URLs such as `"javascript:alert('I am an XSS attack')"` However, `escapeXssInUrl` is used by `escapeUrl`, which is in-turn used by `encodeUrlParam`. I believe this to potentially be a bug in `encodeUrlParam`, which (by its name) seems to be intended to actually do something similar to PHP's builtin `urlencode(...)` function.

I consider this to be a separate issue, however, and this change would both fix the `encodeUrlParam` case for this specific issue, while not negatively-impacting the pathological case of the string `"0"` being passed to `escapeUrl` directly.

**Comment by ferrazzuk** [comment]
Give me @magento give me 2.0 instance
