### ISSUE TITLE
No validation "Sort Order" in "New Rating" form

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23984]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Stores-> Rating
2. Add New Rating
3. Fill All information, "Sort Order" fill "one"
4. Save Rating 

### Expected result (*)

1. Can not save

### Actual result (*)

1. Still save

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23984-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23984-2-3-develop.instances.magento-community.engineering/admin](https://i-23984-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @edenduong. 
If you fill all required fields and click on save it should save ratings so what is the issue.
Can you please explain and update the issue description.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18854` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
