### ISSUE TITLE
Sales Configuration in the 'Orders Cron Settings' under the field 'Pending Payment Order Lifetime (minutes)' have not proper validation

### ISSUE THREAD

**Issue by kirtinariya1** [magento/magento2#23982]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

`Sales` configuration in the `Orders Cron Settings` have a field `Pending Payment Order Lifetime (minutes)` that field have used `Pending Payment Order Lifetime (minutes)`. But issue is that field taking any of the value. There should be take proper validation.

1. Login to the Magento 2 admin.
2. Go to the STORES >> Settings >> Configuration >> Sales >> Orders Cron Settings >> Pending Payment Order Lifetime (minutes):
3. Pending Payment Order Lifetime (minutes): add any text value
4. Save Config

### Expected result (*)

1. There should be allow only digit.

### Actual result (*)

1. There is a taking all the value like text and string as well.  Validation is missing

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23982-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23982-2-3-develop.instances.magento-community.engineering/admin](https://i-23982-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Issue reproduced.

**See attached screenshot:**

![Magento 2 3 Cron Issue](https://user-images.githubusercontent.com/24711761/62346723-c9bb9d00-b514-11e9-9f3d-8abbb8f29845.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18848` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
