### ISSUE TITLE
State/Province field does not clear after select country which have no state drop down.

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#23989]
### Preconditions (*)

1. magento 2.3
2.

### Steps to reproduce (*)

1. Go to Admin
2. Customer -> All Customers
3. Add New Customer
4. Edit Customer -> Addresses
5. Add New Address
6. Select country as US and select any state
7. Now select different country which have no country drop down
8. See the state/province

### Expected result (*)

1. State/Province field should empty.

### Actual result (*)

1. State/Province filled with old selected value in text field.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18892` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
@sdzhepa @krishprakash this issue may be similar to #23460

**Comment by kanevbg** [comment]
No it is not similar to #23460, this one is for the admin panel, the other one is for the frontend.
