### ISSUE TITLE
Create API endpoint for creating and editing customer addresses

### ISSUE THREAD

**Issue by degaray** [magento/magento2#2398]
There is no way to creating or editing customer addresses in the API

**Comment by choukalos** [comment]
Hello @degaray this would be more appropriate as a forum question.  However there's a pretty easy answer.

Address is an extensible object under customer (actually you can pass an array of addresses) and is represented as an array of address objects.  As such you can pass that array with a new object ( and it will be created and associated with that customer ) or send in a changed address object and it'll be updated.  If you pass in an empty array then all the address objects will be destroyed.

You should find a similar pattern when you look at Catalog.  For example say you want to fire 1 API call that creates a downloadable product with media.  You can fire the catalog api create call with the downloadable object and the media object ( your pictures would be base64 encoded ) in that API call and voila you'd have a new downloadable product.  You can then update by doing the same thing as customer ( changed downloadable object for example ) or delete by passing in an empty array for that object.

This pattern is out integration style API feature and is dependent upon how the plugin is implemented on the main service but something we're internally trying to be consistent on unless it doesn't make sense.  As a 3rd party you could extend a core api by creating a plugin and adding your extension object ( could be something like customer social login extension object ).  

Check out:  http://devdocs.magento.com/swagger/index.html#!/customerAccountManagementV1 and look at the addresses array.

**Comment by degaray** [comment]
Thanks! I assume any object with children in it will behave that way,  right? Can you tell me which is the most active community or forum so I can place my questions there?

**Comment by choukalos** [comment]
https://community.magento.com or http://magento.stackexchange.com would be the most appropriate forums to ask questions.

From a Magento perspective we'll handle as described, but there are no restrictions in the framework so 3rd parties extending Magento could behave differently.
