### ISSUE TITLE
bin/magento throws a Warning: array_key_exists(): The first argument should be either a string or an integer

### ISSUE THREAD

**Issue by diazwatson** [magento/magento2#23993]
### Preconditions (*)

1. Checkuot commit e008e80c6ee in 2.3-develop branch
2. PHP 7.1.26

### Steps to reproduce (*)

1. Run `bin/magento`

### Expected result (*)

1. See a list of all commands available

### Actual result (*)

```
Warning: array_key_exists(): The first argument should be either a string or an integer in magento/vendor/zendframework/zend-eventmanager/src/SharedEventManager.php on line 153
```

**Comment by diazwatson** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @diazwatson. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @diazwatson, here is your [Magento instance](https://i-23993-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23993-2-3-develop.instances.magento-community.engineering/admin](https://i-23993-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by diazwatson** [comment]
Forgot there is not ssh access to this instance so it is not possible to reproduce the issue there 🤷‍♂

**Comment by diazwatson** [comment]
I have re tested this after fetching the latest changes in 2.3-develop branch and don't see the issue

**Comment by devamitbera** [comment]
I have faced the same issue and i have update my repo with the last 2.3-develop.

After that, I run **`composer update`**  and my issue is resolved.

**Comment by rav-redchamps** [comment]
I had faced the same problem in 2.4-develop. As shared by @devamitbera, running `composer update `solves the error.

**Comment by hmib** [comment]
Running composer upgrade solved this issue.

**Comment by hiteshgb** [comment]
Any update on this issue as I am also facing same issue.

**Comment by diazwatson** [comment]
hi @hiteshgb have you tried after running `composer update` ?

**Comment by hiteshgb** [comment]
Yes but after after removing updates it is still showing error.
