### ISSUE TITLE
"Selected Attributes" lost selected value when filter

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23999]
### Preconditions (*)

1. Magento 2.3-develop
2. Created at least 2 dropdown attributes (color, size)

### Steps to reproduce (*)

Remember: **Created at least 2 dropdown attributes (color, size)**
1. Go to backend
2. Catalog -> Product -> Add Product
3. Fill require information
4. Click "Create Configurations"
5. In "Selected Attributes", select "color"
6. Go to filter, filter "size" in "Attribute Code"
7. Select "size"
8. View "**Selected Attributes**"

### Expected result (*)

1. Select "Color, Size"
![image](https://user-images.githubusercontent.com/8234209/62409889-1f24a680-b608-11e9-9ea4-ae5c5c5f7c40.png)

### Actual result (*)

1. Select only "Size"
![image](https://user-images.githubusercontent.com/8234209/62409867-eab0ea80-b607-11e9-93f5-cf19859f02f8.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23999-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23999-2-3-develop.instances.magento-community.engineering/admin](https://i-23999-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18926` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24000 by @edenduong in 2.3-develop branch
Related commit(s):
 - [35a135b74e0e202f313aeba1106acf1dcccaea38](https://github.com/magento/magento2/commit/35a135b74e0e202f313aeba1106acf1dcccaea38)
 - [0226f2aeff603cb393a02b5960593aae536d6c8c](https://github.com/magento/magento2/commit/0226f2aeff603cb393a02b5960593aae536d6c8c)

The fix will be available with the upcoming 2.3.4 release.
