### ISSUE TITLE
Store view specific label text field not clear when click on reset

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#23991]
### Preconditions (*)

1. Magento 2.3
2.

### Steps to reproduce (*)

1. Go to Admin
2. Marketing -> Cart Price Rule
3. Fill all the fields
4. Click on Reset
5. Review the Store View Specific Labels -> Default Store View field

### Expected result (*)

1. All the fields should clear when click on Reset.

### Actual result (*)

1. "Store View Specific Labels" still has value
2. https://www.screencast.com/t/bznJ2QGK
![Peek 2020-08-05 16-30](https://user-images.githubusercontent.com/51679138/89418736-1e51b380-d739-11ea-8c4c-9a1f3e499016.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18896` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by keval123** [comment]
Working on this issue.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
