### ISSUE TITLE
Configurable product in Magento 2 not show in product manager after import

### ISSUE THREAD

**Issue by thanhnhan98** [magento/magento2#23998]
### Preconditions (*)

1.PHP 7.0.6
2.MySQL CE 5.6.30
3.Magento 2.1.0

### Steps to reproduce (*)

1.Create a CSV with 3 virtual products and one configurable product.
2.The only attribute configurable is COLOR.
3.Add to the CSV (screenshot attached) the additional_attributes field, as well as configurable_variations and configurable_variation_lables.

### Expected result (*)

1. Import success
2. Show in Configurations Tab

### Actual result (*)

1.Import by this csv

![image](https://user-images.githubusercontent.com/41219883/62407446-db6b7600-b5e2-11e9-9d59-9c8001c228d9.png)

2.Import success but it not show in Configurations Tab

![image](https://user-images.githubusercontent.com/41219883/62407461-140b4f80-b5e3-11e9-9a85-31521739e3f4.png)

Please help me, thanks all

**Comment by arushibansal013** [comment]
@thanhnhan98 thanhnhan98 Can you attach the CSV you are using and is the issue reproducible in Magento 2.3-develop version

**Comment by ajijshekh123** [comment]
@thanhnhan98 - Give me CSV file so I can reproduce this issue in Magento 2.3 Instance.

**Comment by thanhnhan98** [comment]
hi @ajijshekh123. please check it 
https://drive.google.com/file/d/1ca9GFhDiGhwerlGePqYE42_DSOI3t061/view?usp=sharing

**Comment by ajijshekh123** [comment]
Thanks to @thanhnhan98

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23998-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23998-2-3-develop.instances.magento-community.engineering/admin](https://i-23998-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @thanhnhan98,
Product import CSV file is not proper. After import, it is displaying an error.

**See attached screenshot:**
![Import Product Error](https://user-images.githubusercontent.com/24711761/62513438-aad14980-b839-11e9-81a6-95f943e43354.png)

@thanhnhan98 - Please send the proper file with proper data,

**Comment by dev-ajaysaini** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini, here is your [Magento instance](https://i-23998-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23998-2-3-develop.instances.magento-community.engineering/admin](https://i-23998-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @thanhnhan98 

I do not think it is a bug.
In your `example.scv` file is missed lines for simple products(related to configurable).
Only defined relations to the simple products in `configurable_variations` but there are no target simples.

So, it linked to non existed products and as result= Configurable product is imported, but  Configurations tab is empty.

Please, have a look at [Importing Configurable Products](https://docs.magento.com/m2/ce/user_guide/system/data-transfer-configurable-products.html?itm_source=merchdocs_ce&itm_medium=search_page&itm_campaign=federated_search&itm_term=configurable_variations)
 
But in case if I missed something in steps from descriptions, feel free to reopen it with additional details and steps to reproduce

**Comment by alex24409331** [comment]
also you can try this third party app Here is a relevant step by step tutor. https://www.mag-manager.com/product-information/magento-product-management/how-import-configurable-products-to-magento-2/
