### ISSUE TITLE
"Conditions" field of Catalog Price Rule no reset after clicking reset button

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23996]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Admin
2. Marketing -> Catalog Price Rule
3. Fill "Condition" Field
4. Click on Reset

### Expected result (*)

1.  should clear when click on Reset.

### Actual result (*)

1. "Condition" still has value

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instanc

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23996-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23996-2-3-develop.instances.magento-community.engineering/admin](https://i-23996-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18925` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23922` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
