### ISSUE TITLE
Feature Request: Hard Failure (in Developer Mode) for Layout Handle XML Errors 

### ISSUE THREAD

**Issue by astorm** [magento/magento2#2399]
**Existing Behavior**:  When Magento 2 encounters a parsing error in a layout handle XML file, it logs the error here.

```
#File: lib/internal/Magento/Framework/View/Model/Layout/Merge.php
protected function _logXmlErrors($fileName, $libXmlErrors)
{
    $errors = [];
    if (count($libXmlErrors)) {
        foreach ($libXmlErrors as $error) {
            $errors[] = "{$error->message} Line: {$error->line}";
        }
        $this->logger->info(
            sprintf("Theme layout update file '%s' is not valid.\n%s", $fileName, implode("\n", $errors))
        );
    }
}
```

and then continues with system execution.

**Requested Behavior**: When developer mode is enabled, this should be a "hard crash" instead (throwing an exception?).  i.e. If a developer's working on their system with developer mode on, and they make a mistake in a layout handle configuration file, the system should halt execution and tell at them about their bad XML.  

This would match Magento 1.x behavior, as well as follow the general "fail fast" principle exposed in certain corners of the software development world.

**Comment by mrkhoa99** [comment]
:+1: Thanks Alan!

**Comment by astorm** [comment]
Any update on this issue?  It's been six months since it was originally opened, and it's not clear if this isn't a priority for the core team, or if it's just gotten lost in the business of launch. 

/cc @piotrekkaminski

**Comment by piotrekkaminski** [comment]
Logged as MAGETWO-52625, asked @antonkril  & @alankent to provide guidance as this should be global and consistent behavior if to fail fast or log error & continue.

**Comment by antonkril** [comment]
"Fail fast" - should be default behavior for developer mode. This will be processed as dev experience improvement.

**Comment by astorm** [comment]
No update since June -- assuming this isn't a priority for the engineering team and closing out.

**Comment by antonkril** [comment]
This one was fixed.

**Comment by astorm** [comment]
Was it @antonkril?  I just built out a 2.1.0 and 2.0.9 enviornment and Magento still silently swallows invalid XML errors in layout handle XML files.
