### ISSUE TITLE
New Quote is not creating after order place for logged in customer

### ISSUE THREAD

**Issue by hiteshagrawal84** [magento/magento2#24009]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Logged with registered customer
2. Place a new order
3. Check exception.log file

### Expected result (*)

1. New quote should be created for customer

### Actual result (*)

1. report.CRITICAL: No such entity with customerId = 31 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0)

**Comment by ihor-sviziev** [comment]
Duplicate of #23411
