### ISSUE TITLE
No focus to invalid element in "Advance Pricing" => User can not see the error message when Creating Bundle Product

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24002]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Create new Bundle Product
3. Go to Advanced Pricing
4. In "Customer Group Price" - Click "Add"
5. Fill 22 in Quantity
6. Click Done

### Expected result (*)

1. Validate, focus to the "%" element => User can see the message "This is a required field."

### Actual result (*)

1. Validate, but user can not see the error message
![validatenofocus](https://user-images.githubusercontent.com/8234209/62410452-b2150f00-b60f-11e9-809f-1024c8b0b9cd.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18927` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
