### ISSUE TITLE
Magento 2 Release archives don't match Github 

### ISSUE THREAD

**Issue by davefarthing** [magento/magento2#2401]
Hi,

I've just taken a look at the release archive from magento.com/download and noticed that all modules have been moved to the 'vendor' folder e.g. vendor/module-catalog. However the github repo still has all modules under app/code. This makes to codebases significantly different.

Whilst I appreciate there is no functional difference, Will github be updated to match the archives?

.Dave

**Comment by amenk** [comment]
The composer modules are derived from the full source tree from GitHub. See also here #2112

**Comment by buskamuza** [comment]
@davefarthing , there are two approaches of installing Magento:
1. from Git repository. Then all modules are in `app/code`, so contributors can work with them as a regular GitHub repo
2. via Composer. Then all core modules will be in `vendor` and custom modules can be created under `app/code` and stored under project's Git repository. The zip archive is based on this approach, just everything is already downloaded and packed in one zip

Source for the files is the same.
