### ISSUE TITLE
Shipping methods not working correctly after coupon discount (Sorry, no quotes are available for this order)

### ISSUE THREAD

**Issue by noahp78** [magento/magento2#24014]
### Preconditions (*)
1. Magento version: 2.3.2

### Steps to reproduce (*)

1. Configure the following shipping methods:
   * Free Shipping
   * Flat Rate
     * Type: Per Order
     * Price: 2.95
     * Calculate Handling Fee: Fixed
     * Handling fee: 0
   * Free Shipping:
     * Minimum Order Amount: 20
     * Show method if not applicable: no
2.  Create a Cart Price Rule
   * Coupon; Specific Coupon
   * Conditions: empty
   * Actions: Fixed amount discount for whole cart
      * Discount amount: 100
      * Free shipping: for shipment with matching items
3.  Add products to cart up to somewhere between 100.01 and 119.99
4. Apply the just created discount code

### Expected result (*)
1. The customer is able to choose a shipping method.

### Actual result (*)
1. The customer get's a message saying "Sorry, no quotes are available for this order"
2. The customer is unable to place the order. (Couldn't save order information)

**Comment by engcom-Bravo** [comment]
Hello @noahp78. Thanks for reporting. Please try to reproduce Your issue on a clean 2.3-develop instance. Just leave a simple comment as You are advised above:
![Advised](https://user-images.githubusercontent.com/51680745/62532236-9ea2b780-b84c-11e9-8f56-f122091605e1.png)
We've been not able to reproduce the issue on such an instance so far.

**Comment by noahp78** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @noahp78. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @noahp78, here is your [Magento instance](https://i-24014-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24014-2-3-develop.instances.magento-community.engineering/admin](https://i-24014-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
