### ISSUE TITLE
Magento 2.3.2 Update Attributes screen not loading

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#24011]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.1

### Steps to reproduce (*)

1. Select multiple products from product grid
2. Select Actions > Update attributes from drop down

### Expected result (*)

1. Expected load Update Attributes screen with attribute options

### Actual result (*)

1. No options available on update attributes screen - just a heading
2. No console errors visible
![image](https://user-images.githubusercontent.com/39824288/62425176-11d2ef00-b6d0-11e9-9cdc-be160058022e.png)

**Comment by nadroj467** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nadroj467, here is your [Magento instance](https://i-24011-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24011-2-3-develop.instances.magento-community.engineering/admin](https://i-24011-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nadroj467** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nadroj467, here is your [Magento instance](https://i-24011-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24011-2-3-2.instances.magento-community.engineering/admin](https://i-24011-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
