### ISSUE TITLE
No alert when user "Apply empty Coupon Code" in create new order form

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24015]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Sales->Orders->Create New Order
3. Choose Customer, go to the Create New Order form
4. Add some product to cart
5. Click "Apply Coupon Code" without filling the field.

### Expected result (*)

1. Alert the notification 

### Actual result (*)

1. No alert, still send the request, and nothing happens

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24015-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24015-2-3-develop.instances.magento-community.engineering/admin](https://i-24015-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have reproduced this issue in Magento 2.3 Instance.

**See attached screenshot:**
![Magento Coupon Code_Issue](https://user-images.githubusercontent.com/24711761/62457046-83c23b80-b797-11e9-8490-f3e135255cba.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18936` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24016 by @edenduong in 2.3-develop branch
Related commit(s):
 - [866a15414c4f0bf2c8a8c6e8dd0a97fd869d05a8](https://github.com/magento/magento2/commit/866a15414c4f0bf2c8a8c6e8dd0a97fd869d05a8)
 - [7c4032176af6f943f369f309c1a8e494f7ceaf48](https://github.com/magento/magento2/commit/7c4032176af6f943f369f309c1a8e494f7ceaf48)

The fix will be available with the upcoming 2.3.4 release.
