### ISSUE TITLE
Declarative schema: Patch dependencies can cause a patch to apply twice

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#24019]
### Preconditions (*)
1. Magento version 2.3.2 & 2.3-develop
2. Magento already installed

### Steps to reproduce (*)
1. Create one magento module with a setup data patch but don't enable or install the module. Let's call it `Vendor_First` with the patch `Vendor\First\Setup\Patch\Data\First`. This patch should not have dependencies.
2. Create another module (has to be a separate module) similar as the one above. Let's call this `Vendor_Second` with the data patch `Vendor\Second\Setup\Patch\Data\Second`. The only difference from above is that this patch depends on `Vendor\First\Setup\Patch\Data\First`. 
3. the `apply` method can just contain a  `log` command  that writes to a file.
4. Install both modules at once by running `php bin/magento setup:upgrade` (don't run `module:enable` prior to this).

### Expected result (*)

1. Data patches `Vendor\First\Setup\Patch\Data\First` and `Vendor\Second\Setup\Patch\Data\Second` are installed ONCE.  
2. Data patches from above are listed once in the table `patch_list`.

### Actual result (*)

1. Patch `Vendor\First\Setup\Patch\Data\First` is executed twice.  `Vendor\Second\Setup\Patch\Data\Second` is executed once. 
2. `Vendor\First\Setup\Patch\Data\First` shows up twice in `patch_list` table.  

### Additional Info
Removing the dependency between the patches makes them execute once each, but it cannot predict the order in which they are executed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19267` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dfelton** [comment]
Would like to add to this conversation:

- This issue is reproduce-able with Magento's `bin/magento setup:install` command as well.
  - Reproduced in Magento Commerce 2.3.2.
