### ISSUE TITLE
To form the configurable variant SKU description is used instead of label when configured around attribute of Text Swatch type  

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#24021]
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. Create attribute
 - Default Label: Condition
 - Catalog Input Type for Store Owner: Text Swatch
 -  Values Required: Yes
 Manage Swatch
![image](https://user-images.githubusercontent.com/11827230/62478954-145b4480-b7b5-11e9-83a6-5f7dbee9ab0a.png)
Attribute Code: attr_tswatch
Scope: Global
Use in Filter Options: Yes
Manage Titles (Size, Color, etc.): Condition
2. Create a configurable product using this attribute to create configurations. Also take a look at this attribute's values on the Product page.

### Expected result (*)

1. SKUs are:
configurable-product-1-new, configurable-product-1-used, configurable-product-1-refurbished
2. Works like any other attribute
3. On the product page the attribute has values new, used, refurbished.

### Actual result (*)

1. SKUs are: configurable-product-1-wholesale@us-mobiles.cn, configurable-product-1-info@dia-phone.com, +1234567890, configurable-product-1-Jim Bob, +1234567890
2. Works not like other attributes
3. On the product page the attribute has values wholesale@us-mobiles.cn, info@dia-phone.com, +1234567890, Jim Bob, +1234567890

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18960` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23929` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
