### ISSUE TITLE
Unable to import Catalog Categories in v2.3.2

### ISSUE THREAD

**Issue by dinesh6686** [magento/magento2#24023]
Preconditions (*)

1. for v2.3.2
2.

### Steps to reproduce (*)

1. using /V1/categories to get catalogCategoryManagementV1
2. facing an issue during the category import for the instance 2.3.2 

### Expected result (*)

1. for the previous versions, the export data is like this using /V1/categories: 
`{
  "id": 5,
  "parent_id": 1,
  "name": "seconday category",
  "is_active": true,
  "position": 2,
  "level": 1,
  "product_count": 0,
  "children_data": []
}`
2. Because of the 'name' in the export data, the categories are getting imported correctly (for the previous versions)

### Actual result (*)

1. for the version 2.3.2, the export data is like this using /V1/categories: 
`{
      "id": 5,
      "parent_id": 1,
      "name": null,
      "is_active": null,
      "position": 4,
      "level": 1,
      "product_count": null,
      "children_data": []
    }`
2. Because of the 'name' in the export data is null, the categories at root level are not getting imported

Please check and let us know if we are missing anything.

**Comment by milindsingh** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @milindsingh, here is your [Magento instance](https://i-24023-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24023-2-3-develop.instances.magento-community.engineering/admin](https://i-24023-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dinesh6686** [comment]
Any update on this?
@magento-engcom-team

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19067` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dinesh6686** [comment]
@magento-engcom-team Any updates? Can we get ETA for this bug getting fixed.
Thanks.

**Comment by hvdmolenprive** [comment]
I had the same problem.
It looks like the problem is caused in \Magento\Catalog\Model\Category\Tree getNode
Replacing 
        $categoryTree = $this->treeResourceFactory->create();
        $node = $categoryTree->loadNode($nodeId);
by
       $node = $this->categoryTree->loadNode($nodeId);
seems to resolve the issue, however, i did not fully test this.

**Comment by YouCanDoIt12** [comment]
I am also facing the same issue in Magento v2.3.2 
RestApi /V1/Categories is not giving the name in Result.

**Comment by YouCanDoIt12** [comment]
@magento-engcom-team / @shikhamis11 any update on this issue

**Comment by milindsingh** [comment]
@13mcmc12 I am working on it.

**Comment by dinesh6686** [comment]
@milindsingh Any update on this issue

**Comment by gjportegies** [comment]
@milindsingh why is this issue suddenly closed? The issue is still appearing in 2.3.3. Please reopen this issue.

**Comment by dinesh6686** [comment]
@magento-engcom-team / @milindsingh can I know why this issue has been closed with status **Cannot reproduce**? I'm still able to reproduce it in 2.3.3
