### ISSUE TITLE
Unable to create new category

### ISSUE THREAD

**Issue by tahiryasin** [magento/magento2#2402]
When I click <i>Add Root Category</i> or <i>Add Subcategory</i> button from Products > Categories page it doesn't load the form. Console shows below error message. 

`ReferenceError: updateContent is not defined
`

**Comment by anton-huz** [comment]
If after  _Refresh_ page you still reproduce this then it kind of issue.
Then it would be handy to provide more details: do you change any default settings? How do you install Magento? What browser do you use?

**Comment by tahiryasin** [comment]
Yes, I refreshed page many times. I manually installed Magento by downloading from download page. No default settings were changed. And I was using Firefox V 42.0

**Comment by CalamityJames** [comment]
I am also getting this with a fresh install out of the box. No 404 errors appearing in the Network list so all files are being loaded.

I'm using Chrome 46.

If it helps it's this part:

``` javascript
            function addNew(url, isRoot) {
                if (isRoot) {
                    tree.currentNodeId = tree.root.id;
                }

                if (/store\/\d+/.test(url)) {
                    url = url.replace(/store\/\d+/, "store/" + tree.storeId);
                }
                else {
                    url += "store/" + tree.storeId + "/";
                }

                url += 'parent/' + tree.currentNodeId;
                updateContent(url);
            }
```

Edit: I notice comparing to a store with demo data installed that the form fields for adding categories is missing altogether on this install (see attachment):
![image](https://cloud.githubusercontent.com/assets/5637797/11270443/0175e724-8eb7-11e5-84e6-8045eb2f0b44.png)

**Comment by tahiryasin** [comment]
Issue resolved!
I am on Linux and issue was wrong CHMOD 

below commands solved my problem. 

``` bash
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
```

**Comment by magebay99** [comment]
I got same problem but not solved by change permission. Is there other solution? 
Magento 2.0.4

**Comment by magebay99** [comment]
---------------> solved after try again @tahiryasin  solution. Thanks
