### ISSUE TITLE
Use magento with Azure Database for MySQL

### ISSUE THREAD

**Issue by mlennon-spr** [magento/magento2#24022]
### Preconditions (*)

1. Magento 2.3.2
2. Set up an instance of Azure Database for MySQL

### Steps to reproduce (*)

1. Ensure connection works: 

```
$ mysql -h example-db-server.mysql.database.azure.com  -u foo@example-db-server--password=foo
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 65115
Server version: 5.6.39.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ^DBye
```
2. Run `$ bin/magento setup:config:set --no-interaction --db-host example-db-server.mysql.database.azure.com --db-name=magento --db-user=foo@example-db-server --db-password=foo --key=bar --backend-frontname=admin`

### Expected result (*)

1. The config is set

### Actual result (*)

```$ bin/magento setup:config:set --no-interaction --db-host example-db-server.mysql.database.azure.com --db-name=magento --db-user=foo@example-db-server --db-password=foo --key=bar --backend-frontname=admin
SQLSTATE[HY000] [1045] Access denied for user 'foo'@'10.0.0.4' (using password: YES)
```
Magento doesn't use the whole username passed in for --db-user, instead it replaces the portion after the '@' with the IP address it finds for the machine.  This is incorrect at least for Azure Mysql, where the after the '@' must be the name of the resource: (docs)[https://docs.microsoft.com/en-us/azure/mysql/quickstart-create-mysql-server-database-using-azure-portal#connect-to-mysql-by-using-the-mysql-command-line-tool]

How can I get magento to connect to this database?

**Comment by mlennon-spr** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mlennon-spr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mlennon-spr, here is your [Magento instance](https://i-24022-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24022-2-3-develop.instances.magento-community.engineering/admin](https://i-24022-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
Hello @mlennon-spr  ! Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [AzureDatabaseforMySQL](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureDatabaseforMySQL), for advice or general discussion about this issue.

**Comment by hostep** [comment]
@engcom-Alfa: this report is not about a problem with Azure, but with a problem with Magento if I understand it correctly.

But I can't reproduce the problem over here:
```
$ bin/magento setup:config:set --no-interaction --db-user=foo@example.com --db-host=localhost
SQLSTATE[HY000] [1045] Access denied for user 'foo@example.com'@'localhost' (using password: YES)
```

Then tried:
```
$ bin/magento setup:config:set --no-interaction --skip-db-validation --db-user=foo@example.com --db-host=localhost

$ grep 'username' app/etc/env.php
                'username' => 'foo@example.com',
```

So it looks like it doesn't strip of the part after the `@` sign over here.
Tested on Magento 2.3.2.

@mlennon-spr: I'm not sure how to test this though:
> instead it replaces the portion after the '@' with the IP address **it finds for the machine**.

**Comment by tomingoglia** [comment]
Followup from my original reply...It turns out that the command line install does work with Azure. I was doing an install from a Dockerfile and there was a $ in the password that needed to be escaped. My original message was not accurate.
