### ISSUE TITLE
In 2.3.2 in Module-Newsletter Subcribe button is hidden by .sr-only

### ISSUE THREAD

**Issue by Krielkip** [magento/magento2#24027]
With the Magento 2.3.2 the button on subscribe form has been hidden because of the addition of .sr-only;
File: [app/code/Magento/Newsletter/view/frontend/templates/subscribe.phtml 
](https://github.com/magento/magento2/blob/679d8a542dedf330ee899332fd46a7d701c44071/app/code/Magento/Newsletter/view/frontend/templates/subscribe.phtml#L36)

As stated by @nimbus2300; 

![Screenshot by Nimbus2300 ](https://user-images.githubusercontent.com/10194846/62524585-2d580a00-b836-11e9-90c1-42fc2387577c.png)

### Preconditions (*)
1. Magento 2.3.2
2. Module-Newsletter 
3. Have Font-awesome css used in theme

### Steps to reproduce (*)
1. Open storeview
2. have `block class="Magento\Newsletter\Block\Subscribe" template="Magento_Newsletter::subscribe.phtml"` on the page. 

### Expected result (*)
1. Button to subscribe

### Actual result (*)
1. Hidden button because of .sr-only

**Comment by Krielkip** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Krielkip. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Krielkip, here is your [Magento instance](https://i-24027-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24027-2-3-develop.instances.magento-community.engineering/admin](https://i-24027-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
Hi @Krielkip,
This issue was fixed in https://github.com/magento/magento2/pull/24028 and planned to be included in release 2.3.4.
Related commits:
- https://github.com/magento/magento2/commit/9279b695156d1c92149459115db10b4ebf832881

**Comment by karlhass15** [comment]
$('.subscribe').removeClass('sr-only');
