### ISSUE TITLE
Can't create customer and save address to his addressbook

### ISSUE THREAD

**Issue by NickvdMeij** [magento/magento2#24032]
We at MyCademy have out own oAuth implementation, where if the customer does not exist, the customer gets created. This works like a charm and no problem here.
There is however, 1 small inconvinience in the following logic:

```php
if (empty($address)) {
                    $addressFactory = $this->objectManager->get(AddressFactory::class);
                    /** @var \Magento\Customer\Model\Data\Address $address */
                    $address = $addressFactory->create()->getDataModel();
                }

                $address->setCustomerId($customer->getId())
                        ->setFirstname($customerData['first_name'])
                        ->setLastname($customerData['last_name'])
                        ->setStreet([
                            $customerData['address']['street_address_one'],
                            ($customerData['address']['street_address_two'] ? "\n" . $customerData['address']['street_address_two'] : null)
                        ])
                        ->setCountryId($customerData['address']['country_code'])
                        ->setPostcode($customerData['address']['zip_code'])
                        ->setCity($customerData['address']['city'])
                        ->setTelephone($customerData['address']['phone'])
                        ->setIsDefaultShipping('1')
                        ->setIsDefaultBilling('1');

                if (!empty($customerData['address']['company'])) {
                    $address->setCompany($customerData['address']['company']);
                }

                if (!empty($customerData['address']['vat_number'])) {
                    $address->setVatId($customerData['address']['country_code'] . $customerData['address']['vat_number']);
                }

                $addresses[] = $this->addressRepository->save($address);
```

There used to be a "->setSaveInAddressBook()" function, that also saved the address to the customers addresbook, so that it can be used for future reference. However, this function got removed in 2.3 without any replacement from what i can find. Now people log in, go to the checkout page and their address info **is** filled in but they have to manually "submit" it to have it saved to their addressbook and than they can use it. (instead of having it save to the addressbook when the user logs in and doing this step for them, making the checkout process faster and more user friendly).

Does any1 know how this might be achieved now in 2.3?

Thanks in Advance

NickvdMeij

**Comment by arushibansal013** [comment]
@NickvdMeij Since this is not an issue, but a question I am closing the issue. Magento recommend posting any "questions about Magento functionality or processes" to a question-and-answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Comment by NickvdMeij** [comment]
Thanks, i will ask others how to fix your shit while you guys keep forgetting to write documentation.. Best way ofcourse to share knowledge, just let everyone reinvent the wheel again and again and again... 1103 open issues, you might wanna close all those and refer them to stackoverflow as well, then you guys can call it a day and go home
