### ISSUE TITLE
Message "Are you sure you want to delete this category?" can not be translated when delete category

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24038]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Set developer mode `php bin/magento deploy:mode:set developer `
2. Add the line "Are you sure you want to delete this category?","bbbbbbbbbbbbbbbbbbb" to the csv file: **app/code/Magento/Catalog/i18n/en_US.csv**
3. Refresh the cache: `php bin/magento cache:flush`
4. Go to backend.
5. Catalog->Categories
6. "Add SubCategory" - **Shoes**
7. Click category "Shoes" in the category tree.
8. Click Delete
9. View the message

### Expected result (*)

1. The message displays: "bbbbbbbbbbbbbbbbbbb"

### Actual result (*)

1. The message still displays: "Are you sure you want to delete this category?"

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19002` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
It is my mistake. Can not Reproduced on 2.3-develop.
