### ISSUE TITLE
Updating image via API returns true instead of the new id

### ISSUE THREAD

**Issue by TysvdHeuvel** [magento/magento2#24037]
### Preconditions
Magento 2.3-develop
Use Postman, or any other application that communicates via REST API with that Magento installation.
### Steps to reproduce

1. Create a new product image via REST API (POST to /rest/V1/products/{sku}/media). The API returns the id of this new image. 
2. Now update that same image via REST API (PUT to /rest/V1/products/{sku}/media/{id}), and give it a new file and content (new base64_encoded_data). 

### Expected result
The new id (integer) that was produced with the update. When updating the file & content, Magento actually deletes the existing image, and creates a new one. When you just update a property like position or disabled, this does not happen.
You can use the same REST API (GET to /rest/V1/products/{sku}/media/) to verify what just happened, and to see that the image was really deleted and a new entry, with a new id, was created. 
### Actual result
The update/PUT only returns a message: "No image with the provided ID was found. Verify the ID and try again.". Now you have lost control over the image. The last known id has just been deleted, and you didn't get a new id which you could store and use for future updates.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19028` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by geet07** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @geet07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @geet07, here is your [Magento instance](https://i-24037-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24037-2-3-develop.instances.magento-community.engineering/admin](https://i-24037-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by drahreg** [comment]
I can confirm this issue with version 2.3.2

**Comment by sdzhepa** [comment]
Hello @TysvdHeuvel and @maheshWebkul721 

Related internal jira ticket `MC-19028` has been closed as a duplicate of https://github.com/magento/magento2/issues/24639

This fix for this issue currently in development by internal Magento team and should be delivered in the scope of internal Jira ticket `MC-20259` - internal ticket for magento/magento2/issues/24639

Quote from jira

> PUT method should not return the new id. It should re-write an existing entity. This behavior will be fixed in MC-20259
