### ISSUE TITLE
auth.json authentication is insecure and forces users to breach Magento Terms of Service

### ISSUE THREAD

**Issue by rossbearman** [magento/magento2#2403]
The current auth.json approach uses your main Magento.com account credentials to authenticate, given that these accounts are used to manage publishing and payment for Magento Connect extensions, this presents a serious security concern. At the very least the authentication should be done using separate accounts created inside your main Magento account that can be revoked as and when necessary.

Furthermore, you're explicitly forcing any developer in a shared development environment (i.e. most development companies) to breach your own [terms of service](http://magento.com/legal/terms/website).

> You agree to treat as strictly private and confidential any user ID and related password which you may have received required for entry to any tool or service that we provide and all information to which you have access through password-protected areas and will not cause or permit any such information to be communicated, copied or otherwise divulged to any other person whatsoever. You are solely responsible for the security of your password. Any loss that you sustain due to a lack of security on your part regarding your codes or passwords is your sole loss to sustain.

While I'm sure nobody would actually be pursued over this breach of terms, that's simply not good enough.

**Comment by marvincaspar** [comment]
+1

**Comment by amenk** [comment]
+1

**Comment by CalamityJames** [comment]
+1 wholeheartedly

**Comment by amenk** [comment]
Fun fact: If you currently don't auth, you get 404 errrors - not forbidden errors as you might expect.

**Comment by muasir** [comment]
@rossbearman thanks for reporting the issue.  We have an internal ticket created to have this issue resolved soonest. 

@amenk the 404 instead of 401 is another issue we are looking at.  Thanks for reporting it.

**Comment by mazhalai** [comment]
@rossbearman @mc388 @amenk @CalamityJames you can now use authentication tokens:
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

**Comment by amenk** [comment]
Are You aware that for open source projects which build on Magento those tokens have to be published, for example n98-magerun
 Currently @cmuench uses a Travis secret for this, but this is not working for pull requests. Can't you just get rid of the login for the open source parts if the Magento repo?

**Comment by muasir** [comment]
we have also fixed the issue reported by @amenk regarding 404.

**Comment by amenk** [comment]
Does that mean the open components do not require any auth?

**Comment by ghost** [comment]
I think it means that if you use composer create-project, you won't get a 404.

**Comment by amenk** [comment]
http://alankent.me/2015/11/22/magento-2-and-composer-authentication/

**Comment by magento-engcom-team** [comment]
Hi @rossbearman thank you for the report. We will take into account your concerns during the backlog planning
