### ISSUE TITLE
Magento 2.3.2 delete product issue

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#24034]
### Preconditions (*)

1.Magento 2.3.2 
2.Uploaded more than 20 products  to test

### Steps to reproduce (*)

1. Upload 30+ products
2. Go to dashboard -> Catalog -> Products 
3. Show 20 Products per page
4. Click checkbox and click Select all to select all 30 products
5. Click "Action" dropdown menu and delete , it will show "Delete selected items? (30 records) , Click OK
6. A total of 20 records instead of 30  have been deleted.

### Expected result (*)

All the items should be deleted instead of only 1 page of items .

### Actual result (*)

Only 1 page of the items had been deleted.

**Comment by arushibansal013** [comment]
HI @Yuwei9291,

This is duplicate to #22004
