### ISSUE TITLE
Unit test failure 2.3.2

### ISSUE THREAD

**Issue by rszczepaniec** [magento/magento2#24046]
1. Preconditions:
-  Magento 2.3.2 open source, 
- reproduced only on clean composer installation (git based - ok)

2. Steps to reproduce:
- Install clean magento 2.3.2 open source version,
- run 'php bin/magento dev:tests:run unit' command
### Steps to reproduce (*)

3. Expected result:
- Successful unit tests

4. Actual result:
- Failures and skipped unit tests
Results:
![result1](https://user-images.githubusercontent.com/29597016/62614188-31099080-b90b-11e9-8fe8-892bdbd99cc3.png)
![result2](https://user-images.githubusercontent.com/29597016/62614200-3535ae00-b90b-11e9-9a69-1d1deba55c10.png)

Trace:
![trace1](https://user-images.githubusercontent.com/29597016/62614232-4bdc0500-b90b-11e9-8f6f-19ab90dcc79e.png)
![trace2](https://user-images.githubusercontent.com/29597016/62614233-4c749b80-b90b-11e9-9e8e-89629ecd9cc0.png)
![trace3](https://user-images.githubusercontent.com/29597016/62614234-4c749b80-b90b-11e9-8a48-084cace3b610.png)

**Comment by aleromano89** [comment]
Failures and errors happen also on 2.3.1
Here is the report
[errori_unit_tests_m231.log](https://github.com/magento/magento2/files/3489983/errori_unit_tests_m231.log)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19495` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jnando91** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
@jnando91 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by jnando91** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jnando91. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jnando91, here is your [Magento instance](https://i-24046-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24046-2-3-develop.instances.magento-community.engineering/admin](https://i-24046-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jnando91** [comment]
I could not reproduce this issue.
My test result was.

Time: 2.42 minutes, Memory: 2093.15MB

OK, but incomplete, skipped, or risky tests!
Tests: 21960, Assertions: 61261, Skipped: 127, Incomplete: 43.

---- /usr/share/nginx/m23ce/dev/tests/static/framework/tests/unit> /usr/bin/php7.2 /usr/share/nginx/m23ce/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

.........................................................................................                                                                                   89 / 89 (100%)

Time: 1.38 seconds, Memory: 16.00MB

OK (89 tests, 134 assertions)

---- /usr/share/nginx/m23ce/dev/tests/integration/framework/tests/unit> /usr/bin/php7.2 /usr/share/nginx/m23ce/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

............................................................................................................................................................S............ 169 / 182 ( 92%)
.............                                                                                                                                                             182 / 182 (100%)


PASSED (3)

**Comment by sdzhepa** [comment]
Hello  @jnando91 

Just want to double-check.
Did you try to reproduce it on Composer or Git  based Magento installation?

**Comment by jnando91** [comment]
Hi @sdzhepa 
I reproduced the error with a git clone version.
Let me try in a composer installation.

**Comment by jnando91** [comment]
Hi @rszczepaniec 
your test was in production mode or developer mode? 
I executed the cli command in both modes and the result was different.

In production mode my result was like your output, and developer mode was different 

I got the same warning filezise and loadxml
My final output result was the next:

Time: 2.19 minutes, Memory: 2086.00MB

There were 2 failures:

1) Magento\Config\Test\Unit\Model\Config\Structure\ReaderTest::testReadWithValidationException
Failed asserting that exception of type "TypeError" matches expected exception "\Magento\Framework\Exception\LocalizedException". Message was: "Argument 1 passed to Mock_CompilerInterface_42ed9f7b::compile() must be an instance of DOMNode, null given, called in /usr/share/nginx/mdtci/vendor/magento/module-config/Model/Config/Structure/Reader.php on line 143" at
/usr/share/nginx/mdtci/vendor/magento/module-config/Model/Config/Structure/Reader.php:143
/usr/share/nginx/mdtci/vendor/magento/module-config/Model/Config/Structure/Reader.php:93
/usr/share/nginx/mdtci/vendor/magento/framework/Config/Reader/Filesystem.php:132
/usr/share/nginx/mdtci/vendor/magento/module-config/Test/Unit/Model/Config/Structure/ReaderTest.php:121
.

2) Magento\ProductVideo\Test\Unit\Controller\Adminhtml\Product\Gallery\RetrieveImageTest::testExecute
Expectation failed for method name is equal to 'getDirectoryWrite' when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

FAILURES!
Tests: 21867, Assertions: 61095, Failures: 2, Skipped: 132, Incomplete: 43.

---- /usr/share/nginx/mdtci/dev/tests/static/framework/tests/unit> /usr/bin/php7.2 /usr/share/nginx/mdtci/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

........................................................................................                                                                   88 / 88 (100%)

Time: 263 ms, Memory: 12.00MB

OK (88 tests, 131 assertions)

---- /usr/share/nginx/mdtci/dev/tests/integration/framework/tests/unit> /usr/bin/php7.2 /usr/share/nginx/mdtci/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

........................................................................................................................................................ 152 / 182 ( 83%)
....S.........................                                                                                                                           182 / 182 (100%)
FAILED - 1 of 3:
 - /usr/share/nginx/mdtci/dev/tests/unit> /usr/bin/php7.2 /usr/share/nginx/mdtci/./vendor/phpunit/phpunit/phpunit

**Comment by rszczepaniec** [comment]
@jnando91 
My output in developer and production mode is the same.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19634` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by smartsanthosh** [comment]
@magento i would like to work on this ticket
