### ISSUE TITLE
Dupplicate Label in Sales->Transactions at Backend

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24040]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Sales-> Transactions
3. Check the grid at "Payment Method"

![image](https://user-images.githubusercontent.com/8234209/62594150-a6716300-b903-11e9-961f-7179d4f0a5ab.png)

### Expected result (*)

1. The label should be different 

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/8234209/62594162-ab361700-b903-11e9-903c-f8257ebbb69f.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24040-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24040-2-3-develop.instances.magento-community.engineering/admin](https://i-24040-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have reproduced the issue in Magento 2.3 instance.

See attached screenshot:

![2019-08-07 (1)](https://user-images.githubusercontent.com/24711761/62598620-9bb8cd00-b907-11e9-8389-9713625ddb0f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19003` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bydrei** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ferrazzuk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ferrazzuk, here is your [Magento instance](https://i-24040-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24040-2-3-develop.instances.magento-community.engineering/admin](https://i-24040-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
