### ISSUE TITLE
No auto-focus if the invalid field in the collapsed block (Catalog->Add New Product form)

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24045]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Create Require Attribute 
- Go to Backend. Stores->Attributes->Product
- Add New Attribute "musthaveattr"
- Fill all information, "Values Required" is Yes.
2. Assign the Required Attribute to **collapsed group**
- Go to Backend. Stores->Attributes->Attribute Sets
- Edit "Default"
- Move "musthaveattr" to "Search Engine Optimization" Group
- Save
3. Go to Catalog-> Product-> Add Product
4. Fill " Product Name", "SKU", "Price"
5. Save

### Expected result (*)

1. Should focus to the invalid field "musthaveattr"

### Actual result (*)

1. No focus, no notification at the first time
**Click second times**, it  focus to the invalid field "musthaveattr"=> it run correctly (But two clicks)

![Peek 2020-08-05 16-24](https://user-images.githubusercontent.com/51679138/89418154-59071c00-d738-11ea-9879-144dc057ea3b.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19007` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-24045-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24045-2-3-develop.instances.magento-community.engineering/admin](https://i-24045-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sunilit42** [comment]
I have reproduced this issue in Magento 2.3 Instance.

**Comment by sunilit42** [comment]
I have reproduced this issue in Magento 2.3 Instance.

**Comment by krzksz** [comment]
Issue is still reproducible on `2.4-develop` branch:
https://share.getcloudapp.com/jkunKL0q

**Comment by ashish-viradiya** [comment]
#MM20IN

**Comment by engcom-Bravo** [comment]
Hi @edenduong,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.



https://github.com/magento/magento2/assets/51680745/2cf573ef-7978-46d2-8499-66edd077b344





it is focusing to the invalid field "musthaveattr" with the single click on save.

Hence we are closing this issue.

Thanks.
