### ISSUE TITLE
Magento2 - Setup Compile Error - Class Not_Existing_Class does not exist

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#2404]
I installed magento 2 Community version successfully. Now when i try to upgrade the setup i get the error "Please re-run Magento compile command".

So i ran the compile command - magento setup:di:compile

but i am getting following error:

```
Area configuration aggregation... 5/7 [====================>-------]  71% 35 min
s 736.2 MiB

  [ReflectionException]
  Class Not_Existing_Class does not exist


  [ReflectionException]
  Class Not_Existing_Class does not exist

```

Any ideas as to how this can be resolved ?!

**Comment by parekhreena** [comment]
@joanhe hi joan, any update on this ?

**Comment by buskamuza** [comment]
Hi @parekhreena ,
do you have this issue on Windows?

**Comment by buskamuza** [comment]
Internal ticket MAGETWO-43500

**Comment by parekhreena** [comment]
@buskamuza - yes i have this issue on Windows, WAMP server.

**Comment by greg-io7** [comment]
You're seeing that because your class reference to a class called `Not_Existing_Class` does not exist. It looks like maybe this was a placeholder that was never removed?

**Comment by parekhreena** [comment]
Yes you are right. As a temporary fix, i was able to resolve this problem by commenting following line:

 \Not_Existing_Class $notExistingClass

in << Magento2 Root Folder >>\vendor\magento\framework\Code\Test\Unit\Generator\TestAsset\TestGenerationClass.php 

However, after this also there are various other errors showing up.

**Comment by okorshenko** [comment]
@parekhreena Thank you for reporting the issue. We merged fix for this issue to develop branch. https://github.com/magento/magento2/commit/e07ce7367563d1ffbb693824621e43c9f0f92cb0

**Comment by parekhreena** [comment]
Thank you @okorshenko

**Comment by ghost** [comment]
Hi,

I am new bee to magento, need help from you guys.
I am getting the issue after running following command
sudo php bin/magento setup:di:compile

error : [ReflectionException]                                                                 
  Class Magento\Config\Model\Config\Reader\Source\Deployed\DocumentRoot does not exist

This is my local environment:
Magento: 2.1.10
Php: 7.0.30
