### ISSUE TITLE
Bug: the mouse cursor has wrong type ("text") while it is above the «Images and Videos» link on the backend «Product Details» screen

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2405]
![](https://mage2.pro/uploads/default/original/1X/add3ae6ab246027de3d26d107a76f40326f28edc.png)

**Comment by MomotenkoNatalia** [comment]
@dfediuk 
Thanks for your contributing.
I'm closing this issue since Images And Videos section have new look and feel.
