### ISSUE TITLE
Bundle products not appearing in front end

### ISSUE THREAD

**Issue by essexboyupnorth** [magento/magento2#24051]
Hi there,

I recently upgraded to Magento 2.3.2 from 2.2.5 and have noticed that none of our bundle products appear in the categories on the front end or in searches. We also have the same experience in our development area with all but one bundle product. I cannot see any difference in this product and have tried to export this working product out of development into production to see if it would work to no avail.

It's not that the bundle products don't work. They can be reached by going directly to their URLs and can be configured and added to the basket without issue. It's just that they won't show up in searches or in categories. Here are some links:
https://www.rompa.com/snoezelenr-magnetic-led100-projector-saver-pack.html
https://www.rompa.com/snoezelenr-magnetic-led-projector-saver-pack.html
https://www.rompa.com/snoezelenr-in-a-bag.html

This is the URL for one of the products in the category it should be appearing in:
https://www.rompa.com/snoezelen-sensory-rooms/projection/projector-saver-packs/snoezelenr-magnetic-led-projector-saver-pack.html

I've also tried:

- Creating a bundle product post upgrade to see if this would appear but it didn't.
- Enabling and disabling the products.
- Assigning and unassigning products from the website.
- Flushing caches (including Varnish) and reindexing.

### Preconditions (*)
1. Have existing bundle products in Magento 2.2.5
2. Upgrade to Magento 2.3.2

### Steps to reproduce (*)
1. Create bundle product
2. Upgrade 2.2.5 to 2.3.2
3. Try and access bundle products on the front end

### Expected result (*)
1. Be able to access products through front end search and categories.

### Actual result (*)
1. Products do not appear in categories or in search

**Comment by essexboyupnorth** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @essexboyupnorth. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @essexboyupnorth, here is your [Magento instance](https://i-24051-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24051-2-3-develop.instances.magento-community.engineering/admin](https://i-24051-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by essexboyupnorth** [comment]
@magento I was unable to produce the issue on the vanilla 2.3-develop. However it's possible that the issue with bundle products has occurred during the upgrade from 2.2.5 to 2.3.2 and therefore would not be replicated in a vanilla install.

**Comment by essexboyupnorth** [comment]
The bundled products are now showing in the search and the categories. I have just disabled all the new inventory modules with the following command and this fixed my issue.
php bin/magento module:disable Magento_Inventory Magento_InventoryAdminUi Magento_InventoryApi Magento_InventoryGraphQl Magento_InventoryBundleProduct Magento_InventoryBundleProductAdminUi Magento_InventoryCache Magento_InventoryConfigurableProduct Magento_InventoryCatalogApi Magento_InventoryCatalog Magento_InventoryCatalogAdminUi Magento_InventoryCatalogSearch Magento_InventoryConfigurableProductAdminUi Magento_InventoryConfigurableProductIndexer Magento_InventoryConfiguration Magento_InventoryConfigurationApi Magento_InventoryDistanceBasedSourceSelection Magento_InventoryDistanceBasedSourceSelectionAdminUi Magento_InventoryDistanceBasedSourceSelectionApi Magento_InventoryElasticsearch Magento_InventoryExportStock Magento_InventoryExportStockApi Magento_InventoryGroupedProduct Magento_InventoryGroupedProductAdminUi Magento_InventoryGroupedProductIndexer Magento_InventoryImportExport Magento_InventoryIndexer Magento_InventoryLowQuantityNotification Magento_InventoryLowQuantityNotificationAdminUi Magento_InventoryLowQuantityNotificationApi Magento_InventoryMultiDimensionalIndexerApi Magento_InventoryProductAlert Magento_InventoryReservations Magento_InventoryReservationsApi Magento_InventoryReservationCli Magento_InventorySales Magento_InventorySalesAdminUi Magento_InventorySalesApi Magento_InventorySalesFrontendUi Magento_InventorySetupFixtureGenerator Magento_InventoryShipping Magento_InventoryShippingAdminUi Magento_InventorySourceDeductionApi Magento_InventorySourceSelection Magento_InventorySourceSelectionApi
