### ISSUE TITLE
magento2 , api's not working using https only

### ISSUE THREAD

**Issue by yashjain87553** [magento/magento2#24050]
###Information on your environment
1.Magento2.3.2 (community)
2.centos 7 server
3.ssl enabled

### Preconditions (*)
1.Created new user 
2.Assign role as administrator

### Steps to reproduce (*)
1.Use postman.
2.Call api token url using username and password (https://domian.com/index.php/rest/V1/integration/admin/token)(success)
3.Using get method on url https://domain.com/index.php/rest/V1/customers/1  , passing headers(key=Authorization, value=Bearer nw4dat7rqkd0oo802upjdmecgona994p(token received in step one)).

### Expected result (*)
1.Customer Data have id equal to 1.

### Actual result (*)
1. "message": "The consumer isn't authorized to access %resources."

Notes:
1.I added SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1 in httpd.conf.
2.Now expected data is received when calling api using http .
3.Still getting "message": "The consumer isn't authorized to access %resources, when using https.

Please help me.
Thank You

**Comment by engcom-Alfa** [comment]
Hi @yashjain87553 ! Thank you for your report.
Probably the error occurs because you missed **_/all/_** in your url.
It should be like this: https://domain.com/index.php/rest/all/V1/customers/1
Could you take a look?
Thanks!

**Comment by yashjain87553** [comment]
Hi @engcom-Alfa ! Thank you for your reply
1. I added ( all ) after rest (https://domain.com/index.php/rest/all/V1/customers/1) as you suggested.
2. Still getting same error (The consumer isn't authorized to access %resources) on https .
3. Working fine on http .

**Comment by engcom-Alfa** [comment]
Hi @yashjain87553 .
 Try to create a new integration following by steps providing in **[DevDocs](https://devdocs.magento.com/guides/v2.3/get-started/authentication/gs-authentication-token.html)**
Thanks!

**Comment by yashjain87553** [comment]
Hi @engcom-Alfa 
1. I am using token base authentication not  oauth base .
2. I fire curl command in place of postman , getting same error .
3. I also tried to check using oauth authentication as suggested in docs.
4. First create integration than used attached  php script for oauth base authentication 
[oauthapitest.zip](https://github.com/magento/magento2/files/3481359/oauthapitest.zip)
Result:
for http --
string(391) "{"id":1,"group_id":1,"created_at":"2019-05-20 06:35:53","updated_at":"2019-05-20 08:54:49","created_in":"Default Store View","email":"test@saunitech.com","firstname":"Saunitech","lastname":"User","store_id":1,"website_id":1,"addresses":[],"disable_auto_group_change":0,"extension_attributes":{"is_subscribed":true},"custom_attributes":[{"attribute_code":"rewards_subscription","value":"1"}]}"

for https  --
string(121) "{"message":"The consumer isn't authorized to access %resources.","parameters":{"resources":"Magento_Customer::customer"}}"

Thank you

**Comment by engcom-Alfa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-24050-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24050-2-3-develop.instances.magento-community.engineering/admin](https://i-24050-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
@yashjain87553 Please try to reproduce the issue on test instance.
Thanks!

**Comment by engcom-Alfa** [comment]
@yashjain87553 I am not able to reproduce this issue on test instance. All works correctly.
![screen](https://user-images.githubusercontent.com/51679138/62699768-f4ac6200-b9e8-11e9-8049-32cbddeb2c1c.png)

**Comment by yashjain87553** [comment]
Yes , I checked , it is working fine on the instance you provided.  But not on mine .
Please suggest me any changes I can do , like in https.conf, any configration file to make my api's working on https.

**Comment by engcom-Alfa** [comment]
Hello @yashjain87553   ! Thank you for your report !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

**Comment by yashjain87553** [comment]
Ok thank you
