### ISSUE TITLE
Magento\Customer\Block\Address\Grid.php getBackUrl()

### ISSUE THREAD

**Issue by j-robin-hunter** [magento/magento2#24058]
### Preconditions (*)

1. Version 2.3.2 - Customer account exists and has at least a billing or shipping address
2. Watch Back button (visible only if the address grid has more elements than the number selected in Show per page section on the page).

### Steps to reproduce (*)

1. Select Manage Addresses from a customer account

### Expected result (*)

1. Back button in form should return user to the customer account

### Actual result (*)

1. No effect as the href attribute on the anchor has not been set to anything

**Comment by j-robin-hunter** [comment]
This bug can be reproduced on the 2.3.2 vanilla Magento instance

**Comment by engcom-Bravo** [comment]
Hello @j-robin-hunter, thanks for reporting. Please watch this gif, probably we misunderstand something:
![BackButton](https://user-images.githubusercontent.com/51680745/62684055-7fc93000-b9c8-11e9-9f68-117f2c5b5bde.gif)

**Comment by j-robin-hunter** [comment]
Hi, Your gif doesn't go to the correct location to show the problem. From My  Account, click Manage Addresses (next to the Address Book section). This will take you to a page to manage addresses, this page has a back button at the bottom right. This button does not have it's href populated. I can fix this by changing the Magento\Customer\Block\Address\Grid.php file and adding a getBackUrl() function. This button is not visible on Luma Theme

This is the 'default' address grid Magento\Customer\view\frontend\templates\address\grid.phtml file snip

```
<div class="actions-toolbar">
    <div class="primary">
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
    </div>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
    </div>
</div>
```

The $block->getBackUrl() is not found in the block so the href is not populated

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19027` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hell @j-robin-hunter 

The issue has been fixed  by @edenduong and delivered with https://github.com/magento/magento2/pull/24079
