### ISSUE TITLE
Wrong tax amounts when creating New Order with Custom Price using multi currency 

### ISSUE THREAD

**Issue by mikelewis-au** [magento/magento2#24055]
### Preconditions 

1. Magento ver. 2.3.2 & 2.3-develop
2. Base Currency: USD
3. Currency Options > Allowed Currencies: USD, AUD
4. Currency Rates: USD to AUD: 1.47925
5. Tax Rules: GST, Australia, all states, all postcodes, 10%

### Steps to reproduce 

1. Go to admin
2. Create a simple product
3. Create a new customer with and Australian address
4. Sales->Orders->Create New Order
5. Choose the Australian customer
6. Change Order Currency to Australian Dollar
7. Add the product to cart
8. Check Custom Price and enter an amount that's lower than the original price
9. Click Update items and Quantities button
10. Add a payment and shipping method and Submit order

### Expected result 
1. Tax amount should be converted and different from Base tax amount
![expected-result](https://user-images.githubusercontent.com/14268720/62669381-b4da8000-b9d2-11e9-934c-a0c78b3be315.png)

### Actual result 
1. Base tax amount and tax amount are the same in the total summary and product line items. The conversion is not happening.
![actual-result](https://user-images.githubusercontent.com/14268720/62669437-f4a16780-b9d2-11e9-8786-8baddcf4723f.png)
![line-item](https://user-images.githubusercontent.com/14268720/62669461-10a50900-b9d3-11e9-89cb-221c27f3bf63.png)

**Comment by mikelewis-au** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Crikey-Mikey. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Crikey-Mikey, here is your [Magento instance](https://i-24055-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24055-2-3-develop.instances.magento-community.engineering/admin](https://i-24055-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mikelewis-au** [comment]
@magento yes,
Confirmed the issue is reproducible on the vanilla 2.3-develop instance provided above.
![results-2](https://user-images.githubusercontent.com/14268720/62681861-0b10e880-b9fe-11e9-80d9-f1a30894c922.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19135` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mikelewis-au** [comment]
Hi @maheshWebkul721 ,

Thanks for looking into this. Wondering if you had any luck solving this one?

**Comment by engcom-Echo** [comment]
Hi, @Crikey-Mikey. Unfortunately, I can't reproduce this issue. 
![Peek 2021-01-22 11-57](https://user-images.githubusercontent.com/51681435/105476570-79587200-5ca9-11eb-89cf-d8e2d68a1a2b.gif)
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
