### ISSUE TITLE
CatalogPermissions module triggers [Err] 1054 - Unknown column 'MAX ...`

### ISSUE THREAD

**Issue by theloveofcode** [magento/magento2#24057]
### Preconditions (*)

1. Magento Commerce 2.3.2
2. CatalogPermissions are enabled for some or all customer groups.

### Steps to reproduce (*)

1. Create new Catalog Permission rules based on customer group
2. Save a Product in the Admin

### Expected result (*)

1. Product saves without error.

### Actual result (*)

1. Error is triggered:
```
[SQL]SELECT MAX(product_id) as max, COUNT(*) as cnt FROM (SELECT `category_product`.`product_id`, `store`.`store_id`, `permission_index`.`customer_group_id`, `MAX(IF(IF(grant_catalog_category_view = 0, NULL, grant_catalog_category_view) IS NULL, (CASE  WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 0 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 1 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 2 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 3 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 4 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 5 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 6 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 7 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 8 THEN -1 WHEN store.store_id = ' 1 ' THEN -2 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 0 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 1 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 2 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 3 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 4 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 5 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 6 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 7 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 8 THEN -1 WHEN store.store_id = ' 2 ' THEN -2 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 0 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 1 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 2 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 3 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 4 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 5 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 6 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 7 THEN -1 WHEN store.store_id = ' 3 ' AND permission_index.customer_group_id = 8 THEN -1 WHEN store`.`store_id = ' 3 ' THEN -2 END), IF(grant_catalog_category_view = 0, NULL, grant_catalog_category_view)))` AS `grant_catalog_category_view`, `MAX(IF(IF(grant_catalog_product_price = 0, NULL, grant_catalog_product_price) IS NULL, (CASE  WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 0 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 1 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 2 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 3 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 4 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 5 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 6 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 7 THEN -1 WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 8 THEN -1 WHEN store.store_id = ' 1 ' THEN -2 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 0 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 1 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 2 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 3 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 4 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 5 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 6 THEN -1 WHEN store.store_id = ' 2 ' AND permission_index.customer_group_id = 7 THEN -1 WHEN store.s
[Err] 1054 - Unknown column 'MAX(IF(IF(grant_catalog_category_view = 0, NULL, grant_catalog_category_view) IS NULL, (CASE  WHEN store.store_id = ' 1 ' AND permission_index.customer_group_id = 0 THEN -1 WHEN store.store_id' in 'field list'
```

### Proposed Solution
In `\Magento\CatalogPermissions\Model\Indexer\AbstractAction::getPermissionColumns` wrap the SQL functions in the array like `new \Zend_Db_Expr($value)` to prevent them from being treated as column names.

**Comment by engcom-Bravo** [comment]
Hello @theloveofcode. Thanks for reporting. Please watch our video. Probably we miss or misunderstand something.
![CatPerm](https://user-images.githubusercontent.com/51680745/62689158-f3703a80-b9d2-11e9-97fd-130b21b64955.gif)

**Comment by engcom-Bravo** [comment]
@theloveofcode, The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by sdouma** [comment]
@engcom-Bravo 
We get the same error. I have not been able to recreate the issue but regardless \Magento\CatalogPermissions\Model\Indexer\AbstractAction::getPermissionColumn seems like the queries should be wrapper in `new \Zend_Db_Expr($value)`.

**Comment by bogdan-iwd** [comment]
The issue still actual in 2.3.3. It can be reproduce after enable catalog permissions and select 30 or more customer groups in any configuration multi-select. For example:
![Screenshot at Dec 18 12-22-27](https://user-images.githubusercontent.com/14113116/71078037-4633dd00-2191-11ea-94cc-1195d02ead34.png)
The faster way for reproduce it is run reindex for permission: "php bin/magento index:reindex catalogpermissions_product". 
![Screenshot at Dec 18 12-35-51](https://user-images.githubusercontent.com/14113116/71078924-f48c5200-2192-11ea-83a4-8a284abdcbf8.png)

About fix:
It looks like pattern for preg_match is incorrect in
vendor/magento/zendframework1/library/Zend/Db/Select.php line 972:
function _tableCols
We can exclude current permissions from the checking list:
![Screenshot at Dec 18 12-38-18](https://user-images.githubusercontent.com/14113116/71079127-4e8d1780-2193-11ea-8e18-818a7d8c4777.png)

It is a temporary solution and I believe that the Magento developers can find more comfortable solution. 
Also, we can use this patch for fix issue in Magento core:
https://drive.google.com/file/d/19YKycw35bY5f7nww8DidVf4P6RFutEre/view?usp=sharing

**Comment by sdouma** [comment]
@bogdan-iwd 
Thanks for your post. Hopefully this issue can be reopened.

**Comment by sdouma** [comment]
I verify that @bogdan-iwd's patch works. I would like to note we have this error but not quite as many customer groups.

**Comment by ericclaeren** [comment]
Is this still an issue in Magento 2.4.x?

**Comment by sdouma** [comment]
I don't see the updated function in 2.4, so it seems like it should still
be an issue.
