### ISSUE TITLE
Correct Cron Expression shown as invalid

### ISSUE THREAD

**Issue by avoelkl** [magento/magento2#24059]
### Preconditions (*)
- Magento 2.3.2
- PHP 7.2

### Steps to reproduce (*)
1. Set up a cronjob with the following cron expression in XML: */5 4-21 * * 1-5
2. Try to edit the cron schedule in the magento admin: the error message "Invalid cron expression. Please try again." is shown even though the expression is valid (and the cronjob is executed as planned)

<img width="1200" alt="Bildschirmfoto 2019-08-08 um 09 33 06" src="https://user-images.githubusercontent.com/1798594/62683997-f9a8eb80-b9bf-11e9-9bc4-982b99d4ce41.png">

### Expected result (*)
1. Cronjob can be edited, no error message will be shown and correct cron expression is accepted

### Actual result (*)
1. error message "Invalid cron expression. Please try again." is shown even though the expression is valid

**Comment by engcom-Charlie** [comment]
Hello @avoelkl 
I can't reproduce this issue on Magento 2.3-develop. How to open "edit the cron schedule" page in the magento admin?

**Comment by engcom-Charlie** [comment]
@avoelkl I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!
