### ISSUE TITLE
Incorrect layouts override behavior

### ISSUE THREAD

**Issue by ityetti** [magento/magento2#24066]
### Summary (*)

Magento 2.3.2 clear instalation + simple custom theme + one simple extension.

### Examples (*)

1. Installed clear magento 2.3.2
2. Created simple custom theme which contain (`theme.xml`, `registration.php` and `CustomTheme/Magento_Customer/layout/customer_account_create.xml`).
3. Also I created a simple extension which add a custom field to customer accout create form (This extension also use `customer_account_create.xml`.
```
<body>
   <referenceContainer name="form.additional.info">
       <block class="CompanyName\ModuleName\Block\Test" name="test"
              template="CompanyName_ModuleName::form/test.phtml"/>
   </referenceContainer>
</body>
```
).

After that I got strange behavior:
If my `CustomTheme/Magento_Customer/layout/customer_account_create.xml` as is like original file from core, non-standard field is added to the form without problems from my custom extension.

But if I will modify my file `CustomTheme/Magento_Customer/layout/customer_account_create.xml` (for example I just added this string to remove minicart: `<referenceBlock name="minicart" remove="true" />`).
My non-standard field does not apply to the form

Everything looks as if I modify the layout for my needs in custom theme (delete some elements from the registration page), then all other custom extension that use this layout or reference to this layout will stop working.

**Comment by engcom-Charlie** [comment]
Hello @ityetti 
I can't reproduce this issue on fresh Magento 2.3-develop.
**Manual testing scenario:**

1. Created simple custom theme which contain (theme.xml, registration.php and CustomTheme/Magento_Customer/layout/customer_account_create.xml).
2.  Also I created a simple extension which add a custom field to customer account create form
3. Check Customer create from on frontend page( have to see new custom field)
4. Add a `<referenceBlock name="minicart" remove="true" />`
5. Check Customer create from on frontend page again

**Actual result:**
All works fine. The custom field are present and minicart is removed.

**Comment by ityetti** [comment]
@engcom-Charlie 
I will test on m23-develop.
But I wrote a version with which this bug is reproduced (2.3.2 - which was download from Magento website). If this is fixed in a future version, that’s good.

**Comment by ityetti** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ityetti. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ityetti, here is your [Magento instance](https://i-24066-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24066-2-3-develop.instances.magento-community.engineering/admin](https://i-24066-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ityetti** [comment]
@engcom-Charlie
I reproduced this bug on magento 2.3-develop.
I can upload my theme and Extension to github. And will explain you what need to do for reproduce this issue. Thanks for your help.

**Comment by engcom-Charlie** [comment]
@ityetti so please upload your module and i will try to reproduce it.

**Comment by ityetti** [comment]
@engcom-Charlie I figured out this issue.
Me helped this sections of the documentation
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-extend.html
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/layout-override.html

Thanks for your responce.

**Comment by engcom-Charlie** [comment]
@ityetti that is nice! 
Good luck!
