### ISSUE TITLE
how we can place order with “Paypal express” OR via “Credit Card” using REST API Magento 2?

### ISSUE THREAD

**Issue by gunjanparekh** [magento/magento2#24063]
I want to place an order with "Paypal express" OR via "Credit Card" using REST API but not get any success.

I tried with "Braintree" extension but they also not provide API. Also, I checked the Magento2 REST API document but not got any API endpoint.

I develop a standalone application for place order with "Paypal Express" and after the success, I got "Token" and "Payer ID" and after that, I passed in Magento REST API but got an error message.

```
REST Endpoint : rest/V1/carts/mine/order

Method : PUT

RAW Data :

{
    "paymentMethod": {
    "method": "paypal_express",
        "additional_data": {
            "paypal_express_checkout_token" : "EC-xxxxxxxxxxxx",
            "paypal_express_checkout_redirect_required" : false,
            "paypal_express_checkout_payer_id" : "xxxxxxxxxx"
        }
    }
}

Response :

{
    "message": "PayPal gateway has rejected request. %1",
    "parameters": [
        "Invalid token (#10410: Invalid token)."
    ]
}
```

**Comment by engcom-Charlie** [comment]
Hello @gunjanparekh 
I think you have to try with this endpoint: `V1/carts/mine/payment-information`
You can use this guide to create an order: https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-order.html

**Comment by gunjanparekh** [comment]
> Hello @gunjanparekh
> I think you have to try with this endpoint: `V1/carts/mine/payment-information`
> You can use this guide to create an order: https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-order.html

I have placed an order successfully using "Cash on delivery" and "Check / Money order" but there in no REST endpoint for how to palace order with other payment gateways like PayPal, credit card, etc.

**Comment by engcom-Charlie** [comment]
@gunjanparekh use it for `V1/carts/mine/payment-information`:
   ```
 {
    "email": "vikram.sharma@xymob.in",
    "cart_id": 2,
    "billing_address": {
                    "email": "vikram.sharma@xymob.in",
                "region": "New York",
                "region_id": 43,
                "region_code": "NY",
                    "country_id": "US",
                    "street": ["123 Oak Ave"],
                    "postcode": "10577",
                    "city": "Purchase",
                    "telephone": "512-555-1111",
                    "firstname": "Jane",
                    "lastname": "Doe"
         },
    "paymentMethod": {
        "method": "paypal_express",
        "additional_data": {
            "paypal_express_payment_payload": "{\"id\":\"PAY-3F734824YB370341TLOQNO3Y\",\"intent\":\"sale\",\"state\":\"approved\",\"cart\":\"9W5899822J563802S\",\"create_time\":\"2018-09-18T10:50:31Z\",\"payer\":{\"payment_method\":\"paypal\",\"status\":\"VERIFIED\",\"payer_info\":{\"email\":\"vikramdummy-buyer@outlook.com\",\"first_name\":\"test\",\"middle_name\":\"test\",\"last_name\":\"buyer\",\"payer_id\":\"CAQR5B2LGGB9S\",\"country_code\":\"US\",\"shipping_address\":{\"recipient_name\":\"test buyer\",\"line1\":\"1 Main St\",\"city\":\"San Jose\",\"state\":\"CA\",\"postal_code\":\"95131\",\"country_code\":\"US\"}}},\"transactions\":[{\"amount\":{\"total\":\"102.00\",\"currency\":\"USD\",\"details\":{}},\"item_list\":{\"items\":[{\"name\":\"SATA HardDisk\",\"price\":\"1.00\",\"currency\":\"USD\",\"quantity\":2},{\"name\":\"Logitech Mouse\",\"price\":\"100.00\",\"currency\":\"USD\",\"quantity\":1}]},\"related_resources\":[{\"sale\":{\"id\":\"7CM65242K9229980W\",\"state\":\"completed\",\"payment_mode\":\"INSTANT_TRANSFER\",\"protection_eligibility\":\"ELIGIBLE\",\"parent_payment\":\"PAY-3F734824YB370341TLOQNO3Y\",\"create_time\":\"2018-09-18T10:50:29Z\",\"update_time\":\"2018-09-18T10:50:29Z\",\"amount\":{\"total\":\"102.00\",\"currency\":\"USD\",\"details\":{\"subtotal\":\"102.00\"}}}}]}]}",
            "paypal_express_checkout_token": "EC-9W5899822J563802S",
            "paypal_express_checkout_redirect_required": false,
            "paypal_express_checkout_payer_id": "CAQR5B2LGGB9S"
        }
    }
}
```

**Comment by gunjanparekh** [comment]
> @gunjanparekh use it for `V1/carts/mine/payment-information`:
> 
> ```
> {
>  "email": "vikram.sharma@xymob.in",
>  "cart_id": 2,
>  "billing_address": {
>                  "email": "vikram.sharma@xymob.in",
>              "region": "New York",
>              "region_id": 43,
>              "region_code": "NY",
>                  "country_id": "US",
>                  "street": ["123 Oak Ave"],
>                  "postcode": "10577",
>                  "city": "Purchase",
>                  "telephone": "512-555-1111",
>                  "firstname": "Jane",
>                  "lastname": "Doe"
>       },
>  "paymentMethod": {
>      "method": "paypal_express",
>      "additional_data": {
>          "paypal_express_payment_payload": "{\"id\":\"PAY-3F734824YB370341TLOQNO3Y\",\"intent\":\"sale\",\"state\":\"approved\",\"cart\":\"9W5899822J563802S\",\"create_time\":\"2018-09-18T10:50:31Z\",\"payer\":{\"payment_method\":\"paypal\",\"status\":\"VERIFIED\",\"payer_info\":{\"email\":\"vikramdummy-buyer@outlook.com\",\"first_name\":\"test\",\"middle_name\":\"test\",\"last_name\":\"buyer\",\"payer_id\":\"CAQR5B2LGGB9S\",\"country_code\":\"US\",\"shipping_address\":{\"recipient_name\":\"test buyer\",\"line1\":\"1 Main St\",\"city\":\"San Jose\",\"state\":\"CA\",\"postal_code\":\"95131\",\"country_code\":\"US\"}}},\"transactions\":[{\"amount\":{\"total\":\"102.00\",\"currency\":\"USD\",\"details\":{}},\"item_list\":{\"items\":[{\"name\":\"SATA HardDisk\",\"price\":\"1.00\",\"currency\":\"USD\",\"quantity\":2},{\"name\":\"Logitech Mouse\",\"price\":\"100.00\",\"currency\":\"USD\",\"quantity\":1}]},\"related_resources\":[{\"sale\":{\"id\":\"7CM65242K9229980W\",\"state\":\"completed\",\"payment_mode\":\"INSTANT_TRANSFER\",\"protection_eligibility\":\"ELIGIBLE\",\"parent_payment\":\"PAY-3F734824YB370341TLOQNO3Y\",\"create_time\":\"2018-09-18T10:50:29Z\",\"update_time\":\"2018-09-18T10:50:29Z\",\"amount\":{\"total\":\"102.00\",\"currency\":\"USD\",\"details\":{\"subtotal\":\"102.00\"}}}}]}]}",
>          "paypal_express_checkout_token": "EC-9W5899822J563802S",
>          "paypal_express_checkout_redirect_required": false,
>          "paypal_express_checkout_payer_id": "CAQR5B2LGGB9S"
>      }
>  }
> }
> ```

Thanks for the reply.
Every time I got the same error :

{
    "message": "PayPal gateway has rejected request. Invalid token (#10410: Invalid token)."
}

**Comment by gunjanparekh** [comment]
Can you please explain flow for how to place the order using "Paypal Express" OR via "Credit Card" with Magento 2 REST api?

**Comment by engcom-Charlie** [comment]
@gunjanparekh you have to use valid token i think.

**Comment by gunjanparekh** [comment]
> @gunjanparekh you have to use valid token i think.

I have used the same token, payer id which I get from "standalone application". Below is my flow.

created standalone application for place order with "Paypal Express"
After place order, I got "Token" and "Payer ID" and used in "paypal_express_payment_payload" for place order (Magento 2 REST api).

But every time got the same error

{
"message": "PayPal gateway has rejected request. Invalid token (#10410: Invalid token)."
}

**Comment by engcom-Charlie** [comment]
@gunjanparekh can you change a description of this issue for more valid? Please add a Precondition(with your system configuration and version of magento), Steps to reproduce, Expected and Actual results and i will confirm it.

**Comment by engcom-Charlie** [comment]
@gunjanparekh I am closing this issue now due to inactivity.
Please update if you wish to continue.
Thank you for the collaboration!

**Comment by santosh-gaggle** [comment]
> > @gunjanparekh you have to use valid token i think.
> 
> I have used the same token, payer id which I get from "standalone application". Below is my flow.
> 
> created standalone application for place order with "Paypal Express" After place order, I got "Token" and "Payer ID" and used in "paypal_express_payment_payload" for place order (Magento 2 REST api).
> 
> But every time got the same error
> 
> { "message": "PayPal gateway has rejected request. Invalid token (#10410: Invalid token)." }

Here a module i think which can help  you

https://github.com/santosh-gaggle/paypal-rest-api

**Comment by MimirRnD** [comment]
@santosh-gaggle 
I have tried your module. Calling your module with the first create token makes the module respond like this

[
    {
        "code": 404,
        "message": "The current user cannot perform operations on cart \"140942\""
    }
]

What is going wrong?

**Comment by RaguApto** [comment]
@ghost! Did you got solution? am also facing same issue

**Comment by palak-ana** [comment]
> @santosh-gaggle and @ghost Did you got solution? am also facing same issue
 Were you able to make it work. I am also getting the same error.
