### ISSUE TITLE
Magento 2.3 - Cannot create a new shipping label for an already created shipment

### ISSUE THREAD

**Issue by HannesJa** [magento/magento2#24064]
### Preconditions (*)

1. Magento 2.3 CE (Installed using composer)
2. A carrier, that supports shipping labels
3. Firefox 68.0.1 (Tested also on Chrome, Issue not dependent on browser, but the console error message is different on different browsers)

### Steps to reproduce (*)

This has been done by following the [Magento's documentation](https://docs.magento.com/m2/ce/user_guide/shipping/shipping-label-create.html#method-2-create-label-for-existing-shipment): 
1. Choose any product
2. Go to checkout
3. Choose the shipping method, that uses the carrier that supports shipping labels
4. Pay with whatever payment method
5. After the order is done, go to admin-panel and ship it with creating a shipping label
6. After the shipping is done, go to the shipment's page in Admin->Orders-><the_order_done>->Shipments->View
7. Select "Create Shipping Label..."
8. Put the product to the package, as you would do when creating the label the first time
9. Open the browser's developer console
10. Click "Save", and observe the error in console

### Expected result (*)

Expected the new shipping label to be created

### Actual result (*)

Got a JS-error, saying that "#edit_form" is not defined:
![Screenshot 2019-08-08 at 13 40 33](https://user-images.githubusercontent.com/31092047/62697659-dbed7d80-b9e3-11e9-9e4b-da763da95324.png)

This error occurs in *magento/module-shipping/view/adminhtml/templates/order/packaging/popup.phtml*:
```javascript
packaging.setConfirmPackagingCallback(function(){
    packaging.setParamsCreateLabelRequest($('edit_form').serialize(true));
    packaging.sendCreateLabelRequest();
});
```

This code tries to serialize the form with id: *edit_form*, but this does not exist on the page of an already created shipment. The phtml-file used here, is *vendor/magento/module-shipping/view/adminhtml/templates/view/form.phtml*.

The *#edit_form* only seems to exist, when creating the shipping label the first time, in: *vendor/magento/module-shipping/view/adminhtml/templates/create/form.phtml*

Edit 2019-08-08: Added a reference to Magento's documentation on this matter & Changed the formatting of the code snippet

**Comment by engcom-Bravo** [comment]
Hello @HannesJa. Please watch this gif.
![ShipLab](https://user-images.githubusercontent.com/51680745/62778274-a23a7680-bab8-11e9-8689-1b7d4fbc8ee4.gif)
It was done on a 2.3.2 composer CE version, vanilla installation. Probably the issue has already been fix. Could You please confirm You can reproduce the issue on a vanilla instance of 2.3.2 composer or better 2.3-develop version. Thank You.

**Comment by engcom-Bravo** [comment]
@HannesJa, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
