### ISSUE TITLE
Magento not compatible php latest version (7.3.0)

### ISSUE THREAD

**Issue by kuldip1** [magento/magento2#24062]
Hi All,

When i try to install magento in PHP 7.1 version it's not working.
But while i update my PHP version 7.2 it;s working fine.

Now i found one major issue that if i have lower version that is okay but if i have PHP latest version then magento should be work but it's not working.

I think you should update your magento version with all PHP version working.

**Comment by engcom-Alfa** [comment]
Hi @kuldip1.
Thank you for your report!
Magento does not support in PHP v.7.3.0 according to the [documentation](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html).

**Comment by hostep** [comment]
Maybe good to mention that Magento 2.3.3 will support PHP 7.3.x
Source: https://github.com/magento/magento2/issues/19604#issuecomment-505107830

**Comment by engcom-Alfa** [comment]
@hostep Thank you for clarification!
