### ISSUE TITLE
REST API store code placement different from documentation

### ISSUE THREAD

**Issue by rain2o** [magento/magento2#24071]
### Summary (*)
There seems to be a discrepancy between real-life implementation of the M2 REST API and the documentation around it. I am not sure if this is an issue with documentation, implementation, or perhaps my lack of understanding. The [documentation](https://devdocs.magento.com/guides/v2.3/get-started/gs-web-api-request.html#endpoints) for the API structure is as follows:

> An endpoint is a combination of the server that fulfills a request, the web service, the store code, the resource against which the request is being made, and any template parameters.
>For example, in the http://magento.ll/index.php/rest/default/V1/customerGroups/:id endpoint, the server is magento.ll/index.php/, the web service is rest, the resource is /V1/customerGroups, and the template parameter is id.

In my experience, the results of a request like `https://magento.ll/index.php/rest/{store_code}/V1/{endpoint}` are different than the results of `https://magento.ll/index.php/{store_code}/rest/V1/{endpoint}`. The documentation indicates the first is correct, however in testing the 2nd is what provides the expected results. And when testing vanilla M2 with Luma, the endpoints are actually a mixture of both - `https://magento.ll/index.php/{store_code}/rest/{store_code}/V1/{endpoint}`. It also provides the expected results. 

I'm trying to understand, which _should_ it be? And why are there two store codes, what's the difference between the first and the 2nd? Swagger also uses the structure with both store codes.

### Examples (*)
For example, I have one payment method always enabled, Stripe Credit Card, and then I have Stripe's iDeal method enabled for only one store view with the code `nl_nl`. Testing with generic Luma, I get the expected payment methods based on the store view I'm on, and the endpoint called is `https://shop.example.com/nl_nl/rest/nl_nl/V1/guest-carts/UrHE2W1L7HtNg2RMdgdhiTTvdm23czmS/shipping-information`. 

However, if I try to follow the documentation's structure for the API, I make a call to `https://shop.example.com/rest/nl_nl/V1/guest-carts/UrHE2W1L7HtNg2RMdgdhiTTvdm23czmS/shipping-information`, and I _don't_ get back the iDeal payment method like I should. If I call just `https://shop.example.com/nl_nl/rest/V1/guest-carts/UrHE2W1L7HtNg2RMdgdhiTTvdm23czmS/shipping-information` then _I DO_ get back both payment methods as expected.

So it seems like using the store_code _before_ `rest` works, and adding the 2nd store_code seems to not make an impact in this specific scenario.

### Proposed solution
Clarify the proper structure and explanation of the two store codes in the documentation, or perhaps resolve the incorrect processing of the store_code when used after `rest`.

**Comment by rain2o** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rain2o. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rain2o, here is your [Magento instance](https://i-24071-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24071-2-3-develop.instances.magento-community.engineering/admin](https://i-24071-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rain2o** [comment]
While the discrepancy between documentation and the APIs that are used still exists in vanilla Magento, I am not able to replicate the results in the example I provided in the vanilla instance. So the original question still stands. However for my issue I will start with a fresh instance locally and start adding things in until I am able to replicate the issue.

**Comment by rain2o** [comment]
After further testing I am not able to replicate this issue in a fresh instance of the latest Magento 2.3.2 version. I will close this issue. I have opened a new issue in the devdocs repo requesting the documentation address the discrepancy between the API structure in the docs and in implementation.
