### ISSUE TITLE
Product import get  "query was: INSERT INTO `catalog_product_entity_media_gallery` (`attribute_id`,`value`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `attribute_id` = VALUES(`attribute_id`), `value` = VALUES(`value`)" and "1. Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 1"

### ISSUE THREAD

**Issue by prabhash76** [magento/magento2#24084]
### Preconditions (*)

1. Magento 2.3.2
2.

### Steps to reproduce (*)

1.Update 2.3.1 to 2.3.2
2.And try to import product with base, small and thumbnail images

### Expected result (*)

1. Import data with image as well

### Actual result (*)

1. `1. Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 1
General system exception happened
Additional data:
Invalid Stock data for insert`
![Screenshot from 2019-08-09 12-41-31](https://user-images.githubusercontent.com/50201715/62761112-621cc900-baa3-11e9-9d90-0905f8413082.png)

**The images are in the pub/media/import folder as the documentation tells us to I've changed the chmod of these images to 777 just in case The csv file is UTF-8 The image doesn't contain the path in the CSV, just the file name (e.g. 12356.jpg) Checked my categories to make sure they match the existing categories in my store Tried adding other image fields as well instead of just 'base_image' as I did at first to make sure I wasn't missing required fields Turned the CSV file into one line to check if this would work (which it didn't) What am I doing wrong?**

2- `General system exception happened
Additional data:
SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('mage_alberto'@'%') does not exist, query was: INSERT INTO `catalog_product_entity_media_gallery` (`attribute_id`,`value`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `attribute_id` = VALUES(`attribute_id`), `value` = VALUES(`value`)`

**Comment by prabhash76** [comment]
If you want to access the csv file, then you can download file from below link :
http://217.61.57.229/importing_config.csv

**Comment by engcom-Charlie** [comment]
Hello @prabhash76 
I can't reproduce this issue on Magento 2.3-develop. I think you have problems with your csv file.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.
Thank for your report!

**Comment by prabhash76** [comment]
Did you try with CSV which I have posted above?

**Comment by engcom-Charlie** [comment]
@prabhash76 yes, something is not valid in file.

**Comment by prabhash76** [comment]
@engcom-Charlie can you please let me know what is wrong with the file?

**Comment by engcom-Charlie** [comment]
@prabhash76 i don't know, but if you create a product with img and than export it and than you can try to import. All will be ok.
