### ISSUE TITLE
M2.3.1 template binding not working

### ISSUE THREAD

**Issue by aleromano89** [magento/magento2#24087]
### Preconditions (*)
Magento 2.3.1

### Steps to reproduce (*)
1. Create a new empty module (example Alx_KnockoutExample)
2. Generate a new route 
(for example by using pestle
`pestle.phar generate_route Alx_KnockoutExample frontend alx_knockout`) 
3. Associate a block to the route 
(`pestle.phar generate_view Alx_KnockoutExample frontend alx_knockout_index_index Main content.phtml 1column`)
4. Create the file Alx/KnockoutExample/view/frontend/web/template/hello.html
`<p>Hello World</p>`
5. Add the following code in content.phtml
`<div data-bind="template:'Alx_KnockoutExample/hello'"></div>`
6. clean cache and run `bin/magento setup:upgrade`
7. Visit the url `<magentoBaseUrl>/alx_knockout`

### Expected result (*)
I should see the message Hello world as defined in the hello.html file

### Actual result (*)
The content is empty and inside chrome console I get the following
```
Uncaught TypeError: Unable to process binding "template: function(){return 'Alx_KnockoutExample/hello' }"
Message: Cannot read property 'name' of undefined
    at RemoteTemplateEngine.makeTemplateSource (engine.js:184)
    at RemoteTemplateEngine.renderTemplate (engine.js:246)
    at executeTemplate (knockout.js:5327)
    at ko.dependentObservable.disposeWhen (knockout.js:5391)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2183)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2150)
    at Function.evaluateImmediate (knockout.js:2111)
    at Object.ko.computed.ko.dependentObservable (knockout.js:1964)
    at Object.ko.renderTemplate (knockout.js:5383)
    at update (knockout.js:5518)
```

**Comment by aleromano89** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @aleromano89. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleromano89, here is your [Magento instance](https://i-24087-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24087-2-3-develop.instances.magento-community.engineering/admin](https://i-24087-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by aleromano89** [comment]
@magento-engcom-team Can I have the ssh access? thanks

**Comment by Stepa4man** [comment]
@aleromano89 no. It's not supported

**Comment by Stepa4man** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, here is your [Magento instance](https://i-24087-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24087-2-3-develop.instances.magento-community.engineering/admin](https://i-24087-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by aleromano89** [comment]
Hi @Stepa4man , how can you reproduce the issue without ssh?

**Comment by Stepa4man** [comment]
Hi @aleromano89, You don't need.

**Comment by magento-engcom-team** [comment]
@Stepa4man Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@Stepa4man Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@Stepa4man Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Stepa4man 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19127` were created

**Issue Available**: @Stepa4man, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by aleromano89** [comment]
> Hi @aleromano89, You don't need.

Ok @Stepa4man. Can you tell me what are the steps to do? thanks

**Comment by Stepa4man** [comment]
@aleromano89, nobody has access to the codebase. So the only way, for now, is to check it locally at the own machine.

**Comment by rani-priya** [comment]
I think we need to bind like &lt;div data-bind="template:{name:'Webkul_Pos/hello',data:{}}"&gt;&lt;/div&gt;
it's working fine for me..

**Comment by aleromano89** [comment]
@rani-webkul thanks. I confirm that now the bind is working in that way. So the docs should be updated

**Comment by Stepa4man** [comment]
Hi @aleromano89

I'm closing this issue because it's not an issue.

If you still think it's an issue, please, provide all files that you implemented.
What I can see from the description and the error message is that you didn't create any component but try to request its template. I'm not aware that it should work as you did it. If you are sure it should -> please provide some link to documentation where it was mentioned.

Here is a [positive case](https://github.com/magento/adobe-ims/blob/93aa3b5a72106ec7feacbbb983d0e78ce2397f85/AdobeIms/view/adminhtml/templates/signIn.phtml#L10) of how it works for sure.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
