### ISSUE TITLE
Problems with Front/Back-end displaying after Magento 2 installation

### ISSUE THREAD

**Issue by ValentinPetrov** [magento/magento2#2408]
Hello!

I installed today Magento 2. Everything seems fine for a while, but after some time I've found that frontend page and some backend pages (i.e. Stores - General - Web) doesn't displaying - I have just blank pages.

I've tried to delete var folders (/cache, /generation, /page_cache) and clear browser cache and cookies but it doesnt help.

Could you please help me with this issue.

**Comment by mazhalai** [comment]
@ValentinPetrov any JS errors? Also, please give us more details with php version, apache or nginx and OS?

**Comment by daim2k5** [comment]
Hi @ValentinPetrov have you still the issue? If yes can you give us more details?

**Comment by elfstone** [comment]
I believe i have a similar problem. Front end is a blank page, admin is working ok. I think it happened after i enabled varnish. It doesn't help if i put it back on built in caching. 
Update: When i restart server front end came back.

**Comment by davidalger** [comment]
Closing due to lack of response.
