### ISSUE TITLE
"Delete Template" and "Convert to Plain Text" confirm message (at Edit email template) should have the Magento Backend Design

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24082]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Marketing -> Email Templates
3. Create 1 email template
4. Edit the email template which is created
5. Click "Delete Template"
6. Click "Convert to Plain Text"

### Expected result (*)

1. 
![image](https://user-images.githubusercontent.com/8234209/62759155-becfb200-baaa-11e9-8054-eb77d2fc2498.png)

2.
![image](https://user-images.githubusercontent.com/8234209/62759174-c5f6c000-baaa-11e9-8b34-dbb67e3dbe57.png)

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/8234209/62759243-efafe700-baaa-11e9-8200-d2ec4b2eb183.png)

2.
![image](https://user-images.githubusercontent.com/8234209/62759255-f8082200-baaa-11e9-81cf-02c96297ef57.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24082-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24082-2-3-develop.instances.magento-community.engineering/admin](https://i-24082-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19077` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24083 by @edenduong in 2.3-develop branch
Related commit(s):
 - [ce2ec3ee8b6a5a250f2c02fd83bc11415c3ca088](https://github.com/magento/magento2/commit/ce2ec3ee8b6a5a250f2c02fd83bc11415c3ca088)
 - [8c4e44ca58c399b3a4bc120e67244a96e0997d95](https://github.com/magento/magento2/commit/8c4e44ca58c399b3a4bc120e67244a96e0997d95)

The fix will be available with the upcoming 2.3.4 release.
