### ISSUE TITLE
UK postcode validation throwing error at checkout

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#24092]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.1

### Steps to reproduce (*)

1. Add item to cart, proceed to checkout
2. Select UK as shipping country
3. Enter valid UK postcode: example AB1 2CD

### Expected result (*)

1. Postcode should be accepted without validation notice error

### Actual result (*)

1. Error is shown below postcode field
2. PROVIDED ZIP/POSTAL CODE SEEMS TO BE INVALID.

**Comment by nadroj467** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nadroj467, here is your [Magento instance](https://i-24092-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24092-2-3-2.instances.magento-community.engineering/admin](https://i-24092-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
