### ISSUE TITLE
Jquery library outdated

### ISSUE THREAD

**Issue by JustinHermanM** [magento/magento2#24095]
### Description (*)
Update outdated jquery plug in 
jQuery File Upload Plugin 5.16.4 to jQuery File Upload Plugin 5.41.1

Magento version 2.3.1

### Expected behavior (*)
no errors from securi security scan 

### Benefits
PCI compliance by having up to date files

**Comment by JustinHermanM** [comment]
Yes this issue is present in 2.3.1 and 2.3.2 - outdated jquery plugins

**Comment by sdzhepa** [comment]
Hello @JustinHermanM 
  
  Thank you for contribution and collaboration!
   
  Could you please provide more details?
  What type of security scan do you use?
  What exactly the errors it shows?
  
  We need this information to confirm issue as a bug or transfer issue to [Magento Feature Request](https://github.com/magento/community-features) public repo.
