### ISSUE TITLE
"Integrations" Grid missing header label

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24096]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. System -> Integrations
3. Check the Grid header

### Expected result (*)

1. Should have the label
![image](https://user-images.githubusercontent.com/8234209/62822552-5f0eff00-bbaf-11e9-88bf-87c7d2117067.png)

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/8234209/62822577-aac1a880-bbaf-11e9-8763-fda420aeb144.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24096-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24096-2-3-develop.instances.magento-community.engineering/admin](https://i-24096-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19125` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24097 by @edenduong in 2.3-develop branch
Related commit(s):
 - [3945a4c5b33ea0c573180a52d209d9a1b1ef382b](https://github.com/magento/magento2/commit/3945a4c5b33ea0c573180a52d209d9a1b1ef382b)

The fix will be available with the upcoming 2.3.4 release.
