### ISSUE TITLE
Console error when clicking checkbox at "Newsletter Problems Report"

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24102]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Report -> Newsletter Problems Report
3. Make sure no record in the grid. Check the checkbox

When Click

![image](https://user-images.githubusercontent.com/8234209/62835768-51787880-bc86-11e9-9598-afa27abd2da2.png)

### Expected result (*)

1. Should  no console error

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/62835768-51787880-bc86-11e9-9598-afa27abd2da2.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-24102-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24102-2-3-develop.instances.magento-community.engineering/admin](https://i-24102-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24102-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24102-2-3-develop.instances.magento-community.engineering/admin](https://i-24102-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19129` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24104 by @edenduong in 2.3-develop branch
Related commit(s):
 - [d7606f4cb8ca4769d49123aea69bb61b527a1c1b](https://github.com/magento/magento2/commit/d7606f4cb8ca4769d49123aea69bb61b527a1c1b)
 - [86d5c2254cf3cd50051f83c30fd873c0657e6977](https://github.com/magento/magento2/commit/86d5c2254cf3cd50051f83c30fd873c0657e6977)

The fix will be available with the upcoming 2.3.4 release.
