### ISSUE TITLE
Problem with FPT (Eco tax) in checkout process

### ISSUE THREAD

**Issue by latenights** [magento/magento2#2410]
During the checkout process I found one bug connected to FPT or Eco tax price. Final price in checkout are ok, but price in cart preview is not. See picture:
![image](https://cloud.githubusercontent.com/assets/5650354/11245407/e186a952-8e12-11e5-921d-fa6aeb14e7a2.png)

When I added another same product, price is correct. I do not have applied tax on FPT.
![image](https://cloud.githubusercontent.com/assets/5650354/11245317/6d5e1ed4-8e12-11e5-8f9c-7989349e71b9.png)

Maybe something with rounding?

**Comment by mazhalai** [comment]
@latenights thank you for reporting this issue, we have create ticket MAGETWO-45729 to contribute a fix.

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-45729 is closed and delivered to mainline. Please, let us know if you still have an issue.
