### ISSUE TITLE
"Visibility" column in Review Grid should disable the "Sort" ability

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24105]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Marketing -> All Reviews or Pending Review
3. Click the "Visibility" header

### Expected result (*)

1. Should disable "Sort" ability. 

Reference:
 "Content"-> "Block" or "Content" -> "Page". It will disable the sort ability of Store View Column

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/62836802-4840d900-bc91-11e9-8dfb-65a6f62bb6cf.png)

1. It runs. But this is the "Store View information". It can not be sortable. Because it is rendered, not the value.

**See:**

![sort](https://user-images.githubusercontent.com/8234209/62841972-5fef8000-bcd8-11e9-9eba-99289feca424.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19130` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-24105-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24105-2-3-develop.instances.magento-community.engineering/admin](https://i-24105-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24106 by @edenduong in 2.3-develop branch
Related commit(s):
 - [da8766fb7d3bac4713be2408191228ef9416d05c](https://github.com/magento/magento2/commit/da8766fb7d3bac4713be2408191228ef9416d05c)
 - [2cb86cbf51e37aac4dbb83a5a41f8da434ed7ea5](https://github.com/magento/magento2/commit/2cb86cbf51e37aac4dbb83a5a41f8da434ed7ea5)

The fix will be available with the upcoming 2.3.4 release.
