### ISSUE TITLE
Cart Price Rules. Autogenerated coupons does not add to coupons grid

### ISSUE THREAD

**Issue by XxXgeoXxX** [magento/magento2#24107]
### Preconditions (*)
1. Magento 2.3.2
2. Magento 2.3-develop branch

### Steps to reproduce (*)
1. Go to BO->Marketing->Cart Price Rule->Add new rule
2. Fill data
3.  Set Coupon->Specifiec Coupon
3. Click  'Use Auto Generation'
4. Save
5. Open 'Manage Coupon Codes '
6. Set Coupon Qty->2
7. Click 'Generate'

### Expected result (*)

![Screenshot from 2019-08-12 10-28-09](https://user-images.githubusercontent.com/44254165/62850579-f8dbc680-bceb-11e9-99a0-4b85fd834d66.png)

### Actual result (*)
![Screenshot from 2019-08-12 10-27-32](https://user-images.githubusercontent.com/44254165/62850574-f37e7c00-bceb-11e9-9347-2244f5a3d3e0.png)

**Comment by engcom-Bravo** [comment]
Hello @XxXgeoXxX. Thanks for applying. Please after You have clicked "Generate" make sure Your cron jobs are running well. Anyway You may execute `php bin/magento cron:run` twice. And then look back to Your coupon grid.

**Comment by xuanmanhdao** [comment]
> Hello @XxXgeoXxX. Thanks for applying. Please after You have clicked "Generate" make sure Your cron jobs are running well. Anyway You may execute `php bin/magento cron:run` twice. And then look back to Your coupon grid.

Thank you this way worked for me. But it's quite inconvenient, is there any other way to completely fix this problem?
