### ISSUE TITLE
Color swatch validation issue on product page

### ISSUE THREAD

**Issue by vincent2090311** [magento/magento2#24115]
### Preconditions (*)

1. Magento 2.3.2 with sample data
2.

### Steps to reproduce (*)

1. Go to product page with long content (you can add related product or product review to make more height)
2. Dont choose color swatch, click Add to cart button

### Expected result (*)

1. I can see all color swatch options of product (see how it work on magento 2.2)
![Capture 2019-08-13 at 10 40 25](https://user-images.githubusercontent.com/8340835/62913585-e8445280-bdb6-11e9-8ac5-e8f393259e1d.png)

2.

### Actual result (*)

1. The validation message show under color swatch so I dont see 1st color swatch option in current view port
![Capture 2019-08-13 at 10 38 56](https://user-images.githubusercontent.com/8340835/62913537-b3380000-bdb6-11e9-90e0-a08f903591b8.png)
2.

**Comment by engcom-Bravo** [comment]
Hello, @vincent2090311. Thanks for applying. I do not quite understand how You manage to do that. Probably I miss something but here is what I've got:
![sampledata](https://user-images.githubusercontent.com/51680745/62919344-115ee600-bdab-11e9-825b-5b0f5ba8309c.gif)
Is Your installation a vanilla one?

**Comment by vincent2090311** [comment]
@engcom-Bravo 
With product "Radiant Tee" you just need go to the product page, click button add to cart, then you will see the browser scrolling to error section. The problem is after scroll, I don't see the size options (XL, L, M,...), you can ref my screenshot
And yes, I tested with vanilla magento 2.3.2 and 2.2.9

**Comment by engcom-Bravo** [comment]
Ok, @vincent2090311, thank You for reply. But it seems I do exactly the same You say and I don't get that result. Would You please tell me where I go wrong, considering the gif above and the one below:
![sampledata](https://user-images.githubusercontent.com/51680745/62923401-4de40f00-bdb6-11e9-9cba-56b77b2cc92b.gif)

**Comment by vincent2090311** [comment]
@engcom-Bravo 
Here is what I get https://www.loom.com/share/33cb901c4de24c3ea5647736bc471985. Could you check this video
Pls note: v2.2 seem ok I just see the issue on v2.3.2 (I haven't tested on v2.3.0 and v2.3.1 yet)

**Comment by engcom-Bravo** [comment]
Yes @vincent2090311, Your issue is really reproduced on 2.3.2 version but it is not reproduced on 2.3-develop version, not even in 2.3.3. That means the issue have already been fixed. Thus we are supposed to close the issue. But please feel free reopen it if You manage to reproduce it on a vanilla 2.3-develop instance.
