### ISSUE TITLE
Unable to make field depend on field from a different group

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24125]
### Preconditions (*)
1. Magento 2.3.1
2. PHP 7.2.17

### Steps to reproduce (*)
1. Create custom module with system.xml
2. In system.xml create some nested groups of fields
3. For a field in a nested group, add a `<depends>` directive to depends on a field in the parent group

### Expected result (*)
1. Field with the `<depends>` should not be visible until the parent field is set to the specified value

### Actual result (*)
1. Field is visible regardless

----------------------------------------------------------

Below is a more "human" explanation:

In system.xml, I should be able to use the `<depends>` directive to make my custom field depend on any other field, given the fields full ID e.g. 

```
<depends>
    <field id="section_id/group_id/field_id">value</field>
</depends>
```

However, this simply does not work.

Example, I am trying to depend on the Merchant Country field in Sales > Payment Methods

```
<depends>
    <field id="payment/account/merchant_country">value</field>
</depends>
```

(The section, group and field ID are set in "vendor/magento/module-paypal/etc/adminhtml/system.xml")

Not only can I not depend on a field from a core module, I have been unable to depend on a field in a group that is up one level from the current custom field, within my own system.xml file.

**Comment by engcom-Charlie** [comment]
Hello @paul-gene 
Can you update this issue(add precondition with your magento version and server configuration, steps to reproduce, expected and actual result)?
Guide:
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by ghost** [comment]
@engcom-Charlie I have updated the original post.

**Comment by engcom-Charlie** [comment]
Hello @paul-gene thank you for your report! I'm not able to reproduce issue by steps you described on clean 2.3-develop seems like this related to your custom modules.  

**Manual testing scenario:**

1. Create custom module with system.xml
2. In system.xml create some nested groups of fields
3. For a field in a nested group, add a `<depends>` directive to depends on a field in the parent group

**Actual result:**
All works as well

**GIF:**
![Peek 2019-08-28 11-56](https://user-images.githubusercontent.com/51680850/63841469-89bcce00-c98b-11e9-829a-99c094f1852f.gif)

So i have to close this issue.

**Comment by ghost** [comment]
@engcom-Charlie I think your test was a bit too basic.

Try this system.xml layout:

Section (payment) > Group (A) > Group (B) > Group (C) >Group (D) > Field

Where the Field depends on a field inside Group B, C or D (put a field in each Group and try)

This is not a trivial bug to replicate, and I **can** replicate it, so it'd be appreciated if you re-opened the issue.

**Comment by engcom-Charlie** [comment]
@paul-gene can you drop me your xml?

**Comment by ghost** [comment]
Here is the XML as a TXT file, please rename to be .XML

In this XML, find the group `braintree_paypal` and the child group `button_checkout`.

Add a new field to `button_checkout` group, which depends on the field `payment_action` within the `braintree_paypal` group.

With this setup, a directive of `<depends><field id="payment/braintree_paypal/payment_action">authorize_capture</field></depends>` on the new field should work, but it doesn't.

Also, please try on 2.3.1 if possible. But I doubt it works in 2.3.develop either.

[system.txt](https://github.com/magento/magento2/files/3550187/system.txt)

**Comment by ghost** [comment]
@engcom-Charlie also, with that XML, see lines 247-269, the `<depends>` directive in a group, that should look at the merchant country. You'll see I'm targeting it with `section/group/id` but it doesn't work. The field ID is correct and so is the expected value. But the merchant country can be anything and the group is visible regardless.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19693` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment]
@paul-gene thanks for contributing! I confirm it.

**Comment by ghost** [comment]
@engcom-Charlie thank you, I knew I wasn't going mad ;)

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
