### ISSUE TITLE
Something went wrong while saving the category Magento 2.1.16

### ISSUE THREAD

**Issue by subhropots** [magento/magento2#24124]
Magento verion 2.1.16. Whenever I am trying to create a new category I am getting the error -  Something went wrong while saving the category.
In the exception log its showing 
[2019-08-13 10:33:09] main.CRITICAL: RuntimeException: Can't create directory /home/onelifehair/public_html/var/generation/Magento/Framework/App/Response/Http/. in /home/onelifehair/public_html/vendor/magento/framework/Code/Generator.php:115
Stack trace:
#0 /home/onelifehair/public_html/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...')
#2 [internal function]: spl_autoload_call('Magento\\Framewo...')
#3 /home/onelifehair/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...')
#4 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...')
#5 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Framewo...')
#6 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#7 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#8 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(232): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'response', 'Magento\\Framewo...')
#9 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#10 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#11 /home/onelifehair/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#12 /home/onelifehair/public_html/vendor/magento/framework/App/Bootstrap.php(233): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#13 /home/onelifehair/public_html/index.php(38): Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...')
#14 {main} [] []

I have tried reindexing, deleting the content of var/generation, running setup:di:compile and static:content:deploy. Also tried chmod -r -v 777 var/generation. But nothing is working.

Please help me regarding this

**Comment by engcom-Bravo** [comment]
Hello @subhropots. Thanks for applying. The issue You are facing is not a core bug of Magento - the kind this repository is intended posting for. Magento Users successfully create categories every day. So please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
