### ISSUE TITLE
tmp dir file doen't exists error

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#24120]
### Preconditions (*)

1. magento 2.3.2
2. php 7.2

### Steps to reproduce (*)

1. Create module to add images for product from url ( we have custom module since it uses api to connect and get product data )
```
/**
     * Main service executor
     *
     * @param Product $product
     * @param string $imageUrl
     * @param array $imageType
     * @param bool $visible
     *
     * @return bool
     */
    public function execute($product, $imageUrl, $visible = false, $imageType = [])
    {
        /** @var string $tmpDir */
        $tmpDir = $this->getMediaDirTmpDir();
        /** create folder if it is not exists */
        $this->file->checkAndCreateFolder($tmpDir);
        /** @var string $newFileName */
        $newFileName = $tmpDir . baseName($imageUrl);
        /** read file from URL and copy it to the new destination */
        $result = $this->file->read($imageUrl, $newFileName);
        
        if ($result) {
            /** add saved file to the $product gallery */
            $product->addImageToMediaGallery($newFileName, $imageType, true, $visible);
        }

        return $result;
    }
```
for complete file refer this url: https://magento.stackexchange.com/a/173440/77261

### Expected result (*)

1. Image should be added to product

### Actual result (*)

1. We get error that file doesn't exists
`$newFileName = $tmpDir . baseName($imageUrl);`
gives us path: path to magento dir/pub/media/tmp/name of file
also `$newFileName = $this->file->getDestinationFolder($tmpDir) . baseName($imageUrl);` gives us same path as above
but file was placed as
path to magento dir/pub/media/tmp/catalog/product/0/9/name of file

**Comment by Naberdz** [comment]
found problem, seem to be this line:
`$product->addImageToMediaGallery($newFileName, $imageType, true, $visible);`
if change it to `$product->addImageToMediaGallery($newFileName, $imageType, false, false);`

error with file not found is solved and image is properly saved.

**Comment by ruheadshot** [comment]
@Naberdz, this commit resolves issue https://github.com/magento/magento2/commit/103c28be56300b235582504bbeb7a1325ef95eb7#diff-fb2eb8215c1aa379e33f45d400c579e0
