### ISSUE TITLE
Cannot change product type from downloadable to virtual by unchecking "Is this downloadable Product?"

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#24122]
### Preconditions (*)

1. Downloadable Product 1
qty: 100500
status: enabled, IN_STOCK
weight: This item has no weight
links: no links, just samples
samples: 1 sample file

### Steps to reproduce (*)

1. Log in as Admin
2. Open Downloadable Product 1
3. Uncheck "Is this downloadable Product?"
4. Save the product

### Expected result (*)

1. Save is effective. 
2. I can buy a virtual product with that SKU
3. References to samples are kept in the database but the type_id and/or switcher prevents using this information almost like the weight is kept in the Virtual type of product. this gives an ability to switch back from virtual to downloadable smoothly without losing data
4. Alternative: if the first 2 options cannot be implemented, then Merchant receives alert or validation with instruction to remove links and samples first and only then Magento application allows to uncheck "Is this downloadable Product?"
Example:
![image](https://user-images.githubusercontent.com/11827230/62943761-df1daa80-bde3-11e9-83a9-19b13e6a144c.png)

### Actual result (*)

1. Save is not effective.
2. When I try to add product through API the product ~is out of stock~ behaves like a product that is out of stock (missing links) so it is still downloadable.
3. No alert. No validation. The checkbox "Is this downloadable Product?" is checked again, however, it was unchecked before save.
![Peek 2020-08-10 19-16](https://user-images.githubusercontent.com/51679138/89805236-05cd0900-db3e-11ea-8879-c24999cde1ab.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19186` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wittyvishwas** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wittyvishwas. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wittyvishwas, here is your [Magento instance](https://i-24122-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24122-2-3-develop.instances.magento-community.engineering/admin](https://i-24122-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by deepaktiwariwebkul** [comment]
@magento I am working on it.

**Comment by ksenia-zlotin** [comment]
Please reopen this - looks like in vendor/magento/module-downloadable/Model/Product/TypeTransitionManager/Plugin/Downloadable.php:66 the code is expecting some data by the key 'is_delete' on the downloadable data / downloadable product link to be able to change from a downloadable product to virtual, however there is no way to make that data be there.
