### ISSUE TITLE
Fail to upload image on configurable returns "alert("true")"

### ISSUE THREAD

**Issue by r-martins** [magento/magento2#24128]
### Summary of the issue (*)
An alert saying **true** is displayed when trying to upload a large image in one of the configurable options created under _Configurations_ section, when creating a new configurable product.

### Preconditions (*)
1. Magento 2.3.2 Open Source, Production mode. Also reproducible on 2.4-develop in Default mode
2. Nginx/1.14.0 (Ubuntu)
3. PHP 7.1.30
4. Opcache v. 7.1.30
5. Ubuntu 18.04.1 on Digital Ocean
6. Redis v.4.0.9
7. Vanilla Magento with sample data deployed, installed via composer
8. SSL Enabled via certbot / Lets encrypt

### Steps to reproduce (*)
1. Start creating new configurable product
2. In the _Configurations_ section, click on _Create Configurations_ and generate some products. I created 2 just for this example.
3. Click on the + icon to add a photo on the first product
![New_Product___Products___Inventory___Catalog___Magento_Admin](https://user-images.githubusercontent.com/191149/62982561-dc689700-be6f-11e9-87fb-cc8aef07e9a6.jpg)

4. Select a large file (in my case, 11 Mb was enough) and try to upload it. You can use [this one](https://www.dropbox.com/s/zxh3lu0r4wtcyon/beautiful-woman-wrapped-in-a-wool-towel-TLGPZQ9-demo-magentoissue-24128.jpg?dl=1) if you want.

### Expected result (*)
1. Some warning saying the file is too big to my configuration or see the uploaded image. The same file can be uploaded when editing/creating a simple product.

### Actual result (*)
1. I got a alert saying "True".
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/191149/62981695-47649e80-be6d-11e9-8699-ca7628a93f31.png">

2. The ajax request to /mageadmin/catalog/product_gallery/upload/key/.../?isAjax=true brings a wrong error: `{"error":true,"message":"Invalid Form Key. Please refresh the page."}`, which is not true, as I can navigate to other pages in the admin.

3. Nginx error log shows: 

>==> /var/log/nginx/error.log <==
> 2019/08/13 19:38:20 [error] 5288#5288: *4759 FastCGI sent in stderr: "PHP message: PHP Warning:  POST Content-Length of 13816642 bytes exceeds the limit of 8388608 bytes in Unknown on line 0" while reading response header from upstream, client: 103.217.166.165, server: magento2.magenteiro.com, request: "POST /mageadmin/catalog/product_gallery/upload/key/c2ce4a909e2fc7442d229ee38953ad5e82c015b2db68086fc2a7b1514451cc67/?isAjax=true HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "magento2.magenteiro.com", referrer: "https://magento2.magenteiro.com/mageadmin/catalog/product/new/set/4/type/configurable/key/e3879da6ef8893c356e2cc9d0b854b81e30f10005f7fbeed6883d908eb76b6ab/

4. If I upload the same image when editing a simple product, I have no errors.

**Comment by r-martins** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @r-martins. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @r-martins, here is your [Magento instance](https://i-24128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24128-2-3-develop.instances.magento-community.engineering/admin](https://i-24128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by r-martins** [comment]
Yes, I can reproduce it on the dev instance provided by @magento 
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/191149/62983011-4897ca80-be71-11e9-87af-b8461e98421b.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19215` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gaurav-473** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [Magento instance](https://i-24128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24128-2-3-develop.instances.magento-community.engineering/admin](https://i-24128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cristhianss** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cristhianss. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cristhianss, here is your [Magento instance](https://i-24128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24128-2-3-develop.instances.magento-community.engineering/admin](https://i-24128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vivekkumar945744** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul, here is your [Magento instance](https://i-24128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24128-2-3-develop.instances.magento-community.engineering/admin](https://i-24128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vivekkumar-webkul** [comment]
@magento I'm working

**Comment by vivekkumar-webkul** [comment]
@magento i am working on it

**Comment by vivekkumar945744** [comment]
@magento i am working on it.

**Comment by vivekkumar945744** [comment]
@magento I am working on it

**Comment by vivekkumar945744** [comment]
@magento I am not able to assign this issue.

**Comment by vivekkumar945744** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul, here is your [Magento instance](https://i-24128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24128-2-3-develop.instances.magento-community.engineering/admin](https://i-24128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krisdante** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krisdante. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krisdante, here is your [Magento instance](https://i-24128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24128-2-3-develop.instances.magento-community.engineering/admin](https://i-24128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krisdante** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krisdante. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krisdante, here is your [Magento instance](https://i-24128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24128-2-3-develop.instances.magento-community.engineering/admin](https://i-24128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krisdante** [comment]
This issue is caused by POST payload larger than post_max_size for PHP.
This causes to truncate POST data and also Form Key is truncated.
Missing Form Key executes the exception that it is missing and JSON response that is not compatible with the current implementation of javascript uploader:
The response is:
{"error":true,"message":"Invalid Form Key. Please refresh the page."}
while JS Uploader expects error as humar readable string on "error" field.
For that reason here it shows Alert with "true" as this is the value of the field.

To fix that somebody would have to either add proper handling to js uploader - but this will be like halfway solution as it will output error of "Invalid Form Key. Please refresh the page." - this is also misleading.
Or implement a file size validator before the file is uploaded, and set the limit based on max_post_data value in PHP settings.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
