### ISSUE TITLE
Magento 2.3.1 Rest API getting empty extension_attributes field using search criteria on shipments endpoint

### ISSUE THREAD

**Issue by HolyWalley** [magento/magento2#24135]
If you try to get a shipment list from the /shipments endpoints using search criteria you will get an empty extension_attributes field.

**Preconditions**
Magento 2.3.1 & 2.3-develop
PHP 7

**Steps to reproduce**
1.Perform a curl to YOUR_MAGENTO_HOST/rest/V1/shipments?searchCriteria[pageSize]=X&searchCriteria[currentPage]=Y with an authorization header
2.Check the returned JSON

**Expected result**
As API reference and Swagger [say](https://devdocs.magento.com/redoc/2.3/admin-rest-api.html#operation/salesShipmentRepositoryV1GetListGet) extension_attributes should be not empty and containing some information like source_code, like the following part of JSON taken from API reference

**Actual result**
extension_attributes is always not presented:
```
{
    "items": [
        {
            "billing_address_id": 32,
            "created_at": "2019-08-14 14:06:06",
            "entity_id": 9,
            "increment_id": "000000005",
            "order_id": 16,
            "packages": [],
            "shipping_address_id": 31,
            "store_id": 1,
            "total_qty": 1,
            "updated_at": "2019-08-14 14:06:06",
            "items": [
                ...
            ],
            "tracks": [
                ...
            ],
            "comments": []
        }
    ],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "order_id",
                        "value": "16",
                        "condition_type": "eq"
                    }
                ]
            }
        ],
        "page_size": 0,
        "current_page": 1
    },
    "total_count": 1
}
```

Anyway if you use the /shipment/id API endpoint you can see that the product extension_attributes field is populated.

```
{
    "billing_address_id": 32,
    "created_at": "2019-08-14 14:06:06",
    "entity_id": 9,
    "increment_id": "000000005",
    "order_id": 16,
    "packages": [],
    "shipping_address_id": 31,
    "store_id": 1,
    "total_qty": 1,
    "updated_at": "2019-08-14 14:06:06",
    "items": [
        ...
    ],
    "tracks": [
       ...
    ],
    "comments": [],
    "extension_attributes": {
        "source_code": "second"
    }
}
```

I found a similar issue with /products here https://github.com/magento/magento2/issues/8700

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19262` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sebastianCarry** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
@sebastianCarry thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mrmurray** [comment]
Please can we get an update on this?

**Comment by sdzhepa** [comment]
Hello @HolyWalley  and @mrmurray 

The internal Jira ticket related to this issue has been closed with comment

> Issue is not reproducible on 2.4-develop branch.
> This issue seems to be fixed by this Pull Request https://github.com/magento/inventory/pull/2142  which fixes this issue https://github.com/magento/inventory/issues/2135 which describes exactly the same problem as in this ticket.
