### ISSUE TITLE
Error when saving product in admin - Plugin doesn't exist

### ISSUE THREAD

**Issue by PatrickVisserNZ** [magento/magento2#24132]
Error = Plugin class Magento\InventoryLowQuantityNotification\Plugin\InventoryLowQuantityNotificationApi\UpdateLegacyStockItemConfigurationAtSourceItemConfigurationSavePlugin doesn't exist

1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Open product in admin area
2. Save Product
and . . .
Problem also exists when using Command Line  php bin/magento setup:di:compile

### Expected result (*)
1. Product Saves

### Actual result (*)

1. Plugin class Magento\InventoryLowQuantityNotification\Plugin\InventoryLowQuantityNotificationApi\UpdateLegacyStockItemConfigurationAtSourceItemConfigurationSavePlugin doesn't exist
2. Debug Log . . .
[2019-08-14 10:53:45] main.CRITICAL: Plugin class Magento\InventoryLowQuantityNotification\Plugin\InventoryLowQuantityNotificationApi\UpdateLegacyStockItemConfigurationAtSourceItemConfigurationSavePlugin doesn't exist {"exception":"[object] (InvalidArgumentException(code: 0): Plugin class Magento\\InventoryLowQuantityNotification\\Plugin\\InventoryLowQuantityNotificationApi\\UpdateLegacyStockItemConfigurationAtSourceItemConfigurationSavePlugin doesn't exist at /home/widemo/public_html/vendor/magento/framework/Interception/PluginList/PluginList.php:182)"} []

Additionally I cannot seem to be able to duplicate a product. Same error message at top if screen.

**Comment by engcom-Bravo** [comment]
Hello @PatrickVisserNZ. Thanks for applying. Do we miss something here:
![dowemiss](https://user-images.githubusercontent.com/51680745/63017579-6714ba80-be9f-11e9-83c5-91279b23e0c6.gif)

**Comment by MisterMcJohn** [comment]
I just installed a new fresh Magento 2.3.2 and have the some issue as PatrickVisserNZ

**Comment by MisterMcJohn** [comment]
I just installed a new fresh Magento 2.3.2 and have the some issue as PatrickVisserNZ

UPDATE
I did a fast fix creating this file below until they fix it, and it's working.

nano vendor/magento/module-new-relic-reporting/Plugin/StatePlugin.php

File content:
<?php
namespace Magento\NewRelicReporting\Plugin;
class StatePlugin{
}

**Comment by engcom-Bravo** [comment]
Ok, @MisterMcJohn, but the issue is not going to undergo any fixing procedures unless it's confirmed. And in order to confirm it we need to have the steps following which we can reproduce it. For now we've  been not having such ones.

**Comment by PatrickVisserNZ** [comment]
Quick fix is to disable the module.
php bin/magento module:disable Magento_InventoryLowQuantityNotificationApi

**Comment by engcom-Bravo** [comment]
@PatrickVisserNZ, could You please provide us not the fix but the steps on how we can reproduce the issue because those given in the description have not lead us to reproduction as You can see it from our gif. (We had that module enabled wile trying to reproduce the issue).

**Comment by engcom-Bravo** [comment]
@PatrickVisserNZ, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by mediadiv** [comment]
I have the same problem.
Magento open source ver. 2.3.2
PHP 7.3 (ea-php73) 

![error](https://user-images.githubusercontent.com/11540227/69983815-e5bd6280-1537-11ea-946d-637a86a178c1.PNG)
