### ISSUE TITLE
composer install display file could not be downloaded

### ISSUE THREAD

**Issue by price2b** [magento/magento2#2413]
Im trying to run composer install in magento2 directory. I downloaded the zip file from github.com/magento/magento2 and running the composer install process the following information appears:

![untitled-2](https://cloud.githubusercontent.com/assets/396666/11253426/2d4e9870-8e1a-11e5-8dfa-e497f6a62ea0.png)

I check the repo and nothing there : https://repo.magento.com/archives/magento/composer/magento-composer-1.0.2.0.zip

anyone knows if its wrong or we have to update something in composer.json?.

**Comment by mazhalai** [comment]
@price2b have you set up the `auth.json` as suggested [here](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/dev_install.html#instgde-prereq-compose-clone)

**Comment by price2b** [comment]
thank you @mazhalai , I didnt read that. I will proceed. brgds and thank you!

**Comment by marcobax** [comment]
For those who are wondering how to fix this: I've put up a blog post with step-by-step instructions on how to resolve this issue: http://magento2king.com/magento2-insta-be-downloaded/
