### ISSUE TITLE
Shiping Address overriden in checkout with Default Tax Destination Calculation

### ISSUE THREAD

**Issue by bmatth** [magento/magento2#24136]
### Preconditions (*)

Magento 2.3.2 (new installation, used sample data)
PHP 7.2.12

### Steps to reproduce (*)
(Backend)
1. In the Admin Panel under Shop -> Configuration -> Sales -> Tax -> Default Tax Destination Calculation set a Country and Postcode (e.g. Country: "Germany", Postcode: "012345").

(Frontend)
2. Create a new account as customer or use the deme account.
3. Make sure the customer uses the same address for both shipping and billing as default.
4. Add a product to the cart and proceed to the checkout.
5. Use the preselected Address under Shipping and click next.
![Anmerkung 2019-08-15 082543](https://user-images.githubusercontent.com/48289032/63077369-57958000-bf38-11e9-960a-f276861c5f81.jpg)
6. Select a payment option.
7. Ship to should be the previously selected address.
8. uncheck "My billing and shipping address are the same" checkbox.
![Anmerkung 2019-08-15 082728](https://user-images.githubusercontent.com/48289032/63077414-86abf180-bf38-11e9-9bc8-d13c867fff9c.jpg)
9. Select "New Address" in the dropdown.
10. Enter Address data, leave the Zip Code is empty when selecting a country or an invalide zip code that fails Validation on unfocus.
11. The "Ship To" address gets changed to to the one set in "Default Tax Destination Calculation" with the customer name.

![Anmerkung 2019-08-15 083540](https://user-images.githubusercontent.com/48289032/63077424-91668680-bf38-11e9-861a-33924b20f5a6.jpg)

### Expected result (*)
The Shipping address shouldn't change when entering data for a new billing address.

### Actual result (*)
The Shipping address gets changed to the "Default Tax Destination Calculation", that is not a valid address to ship to.

**Comment by bmatth** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bmatth. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bmatth, here is your [Magento instance](https://i-24136-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24136-2-3-develop.instances.magento-community.engineering/admin](https://i-24136-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bmatth** [comment]
Unable to reproduce in Develop-instance.

Looks like it's fixed there already.
