### ISSUE TITLE
Magento admin user without role

### ISSUE THREAD

**Issue by miguelbalparda** [magento/magento2#2414]
Now it is possible to create an admin user without selecting a role. Is this on purpose? I found out this when trying to access the admin with a new user and i got this

![screenshot - 11182015 - 06 21 47 pm](https://cloud.githubusercontent.com/assets/3997682/11254759/434e4f7e-8e21-11e5-8f8b-d8453bad3af1.png)

To replicate, use test/admin1234 on http://magento2-demo.nexcess.net/admin and admin/admin123 as a valid user.
This is fixed if I try to edit the user and add a role to it, but I was able to save the user without one in the first place.

**Comment by mazhalai** [comment]
@miguelbalparda we have created MAGETWO-45760 to investigate.

**Comment by ilol** [comment]
@miguelbalparda, the current behavior is expected. The admin can create the user without role assignment.

**Comment by daim2k5** [comment]
@miguelbalparda i close the issue for now. If you have futher question to this issue please feel free to reopen
