### ISSUE TITLE
Wrong Label when create new "Attribute Set"

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24147]
### Preconditions (*)

1. Magento 2.3-develop 

### Steps to reproduce (*)

1. Go to backend
2. Store->Attribute Set
3. New Attribute Set
See the label:

![image](https://user-images.githubusercontent.com/8234209/63142472-25595080-c014-11e9-9f06-32728a1e9b4d.png)

### Expected result (*)
Should be:

![image](https://user-images.githubusercontent.com/8234209/63142496-3b671100-c014-11e9-894a-04a3c996271d.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/63142475-28ecd780-c014-11e9-8321-cd18bfaffddf.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24147-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24147-2-3-develop.instances.magento-community.engineering/admin](https://i-24147-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@edenduong - This is not an issue. This is a suggestion.
Suggestion Verified.

See attached screenshot:

![2019-08-16](https://user-images.githubusercontent.com/24711761/63143252-fd192400-c00a-11e9-84ca-d4f7c4da1f99.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19304` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Shubham0492** [comment]
@magento give me 2.3-develop

**Comment by Ctucker9233** [comment]
@ajijshekh123 I agree with you. I see no problem with the verbage as it is as it directs the user as to what to do next.

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24148 by @edenduong in 2.3-develop branch
Related commit(s):
 - [86434a200dc60ab7293c7db51a0667fc98eca953](https://github.com/magento/magento2/commit/86434a200dc60ab7293c7db51a0667fc98eca953)
 - [8e57b691fc4cea336a3fe74d8e89aa98eccb4fc5](https://github.com/magento/magento2/commit/8e57b691fc4cea336a3fe74d8e89aa98eccb4fc5)

The fix will be available with the upcoming 2.3.4 release.
