### ISSUE TITLE
PayPal and InContext Checkout cannot be disabled

### ISSUE THREAD

**Issue by chequille** [magento/magento2#24144]
Configuration of PayPal module in the Backend of Magento 2.3.2 does have the setting:
Activate InContext Checkout Yes or No
Unfortuntely, there is no difference.
Checkout is always using the inContext checkout.

### Preconditions (*)
1. Magento 2.3.2
2. Paypal express checkout
3. PHP 7.1

### Steps to reproduce (*)
1. Set up vanilla 2.3.2 install
2. Go to Stores > Configuration > Sales > Payment Methods
3. Switch scope to 'Main Website'
4. Open Paypal settings and look at the 'Enable In-Context Checkout Experience' setting
5. Notice that the checkbox 'Use Default' is unchecked while there is no value stored in the database for the website scope (payment/paypal_express/in_context)
6. Check the checkbox
7. Save
8. Look at the checkbox again, it's again unchecked and still no value in the database for the website scope

### Expected result (*)
1. Checkbox is checked and value has changed in the database for the website

### Actual result (*)
1. Checkbox again unchecked and still no value in the database for the website scope

**Comment by engcom-Charlie** [comment]
Hello @chequille 
Magento 2.3.2 have this option in the admin configurations:
![image](https://user-images.githubusercontent.com/51680850/63149178-0eaefb80-c00c-11e9-97cd-aa160d6dec7e.png)

1. On the Admin sidebar, tap Stores. Then under Settings, choose Configuration.
2. In the panel on the left under Sales, choose Payment Methods.
3. In the PayPal Express Checkout section, tap Configure. 
4. In the Required PayPal Settings section, set Enable In-Context Checkout Experience to “Yes/No.”

Thank for your report!

**Comment by chequille** [comment]
@engcom-Charlie 
I am a little bit confused. Do I speak another language?

Of course I know this setting, but I reported with this issue, that it is not working.

To make it clear:
I set Enable In-Context Checkout Experience to **YES**
Checkout uses InContext Checkout

I set Enable In-Context Checkout Experience to **NO**
Checkout uses InContext Checkout as well

**NO DIFFERENCE**

That's what I am reporting. I did not ask how and where to Enable/Disable it. I reported, that these setting is not working.

So please reopen this issue, because it is not working.

Regards,
Chequille

**Comment by chequille** [comment]
@engcom-Charlie
Hi, I found the problem and in my point of view it is a bug.
When setting In-Context Checkout Experience to “Yes/No.” in the backend, it is stored under default skope in core_config_data and not under skope websites.
![grafik](https://user-images.githubusercontent.com/15807794/63213869-a34f5180-c111-11e9-9b00-b2d64f1ea5aa.png)
Therefore, it does have no effect on the frontpage, because frontpage is reading the value from skope websites and not the default.
So, I hope I could help on this and everybody understands what i am saying :-)

**Comment by chequille** [comment]
Please reopen this issue, because it is a bug

**Comment by chequille** [comment]
Why do you ignore this issue and keep it closed?
Do not understand this, because it is a bug.
Please confirm this issue and reopen it.
Thanks.

**Comment by engcom-Charlie** [comment]
@chequille sorry but i was off for 4 days. Please update a description of this issue(please add Precondition, Steps to reproduce, Expected and Actual result, Proposed solution) and i will confirm it.

**Comment by hostep** [comment]
This sounds very similar to https://github.com/magento/magento2/issues/23669.

@chequille: are you using single store mode by any chance? Disabling that might fix your issue (I realize that's not a proper bug fix, but it might get you further)

**Comment by chequille** [comment]
@hostep 
Hi, 
I tried single store mode, but no difference. I will explain again what happens, so charlie can handle it.

**Comment by chequille** [comment]
Used Version:Magento 2.3.2

Setting In-Context Checkout Experience to "YES"
core_config_data entry
scope -> default
path -> payment/paypal_express/in_context
is set to value=1

Setting In-Context Checkout Experience to "NO"
core_config_data entry
scope -> default
path -> payment/paypal_express/in_context
is set to value=0

BUT
PayPal in the frontend during checkout is reading the value from 
core_config_data entry
scope -> websites
and not from 
scope -> default

Therefore the frontend is doing it as it is set in core_config_data entry for scope websites

Expected behaviour:
As the backend is mentioning in brackets [websites]
![grafik](https://user-images.githubusercontent.com/15807794/63461551-285fa100-c459-11e9-92a6-5d7f78b1aaa4.png)
it should store it as well for scope "websites" and not "default"

**Comment by hostep** [comment]
Hi @chequille 

That's not really true. The indication `[website]` means you **can** configure the value per website.
But you can also just configure it globally and not overwrite it on website level and then the value from 'default' will be used, because there won't be a value on website level in the database.
If you do have it overwritten on website level, then that value will be used on the frontend for the website associated to that particular frontend.

What you now need to figure out is how the value got saved on the website level? Perhaps you changed the scope in the configuration to one of your websites and changed it there?
If that was the case, then the solution is very easy, just change it again on the website level by checking that box to use the default values.

Hope this helps!

This no longer sounds like a bug to me, but if you still believe it is, please let us know what exactly you think the bug is.

**Comment by chequille** [comment]
Hi @hostep 
Sorry, do not know what you mean with configure it per website.
I have only one.
Where can I configure it per website?
I think, this is only possible if I would have more than one website.

Frontend is reading it from scope websites and I do only have one website:
![grafik](https://user-images.githubusercontent.com/15807794/63464697-15040400-c460-11e9-8e71-6473c3c919a3.png)

So, where is my mistake when you think it is one.
Fact is as far as I see it, that frontend is reading it from the entry in core_config_data where scope is websites.
This is definetely the case, because if I change the value manually in the database to 0, checkout is not using InContext PayPal. If I set it back to 1 it is using InContext.

Other values from the PayPal settings  are working, so only this one not.
So, this indicates it is a bug.
Backend should save my setting for InContext as well with scope=websites not with default.

**Comment by chequille** [comment]
Addendum:
Or frontend should read values for all PayPal settings from the same scope, what it is not doing.

**Comment by hostep** [comment]
In Stores > Configurations, at the top left, you should see a dropdown where you can switch scopes. If you pick 'Main Website' there, you'll be configuring settings on the 'Main Website' scope.

<img width="1044" alt="Screenshot 2019-08-21 at 22 44 20" src="https://user-images.githubusercontent.com/85479/63467339-885c4480-c465-11e9-8cc5-c238abcde7bd.png">

**Comment by chequille** [comment]
Ok, but if I did this, at all parameters the checkbox use standard was selected. So frontend should use the setting of default store view or?

**Comment by hostep** [comment]
Correct.

Ok, instead of theorising, I just tried it out that setting you are talking about, and there is something fishy going on with that one.

@engcom-Charlie, please confirm:
1. Set up vanilla 2.3.2 install
2. Go to Stores > Configuration > Sales > Payment Methods
3. Switch scope to 'Main Website'
4. Open Paypal settings and look at the 'Enable In-Context Checkout Experience' setting
5. Notice that the checkbox 'Use Default' is unchecked while there is no value stored in the database for the website scope (`payment/paypal_express/in_context`)
6. Check the checkbox
7. Save
8. Look at the checkbox again, it's again unchecked and still no value in the database for the website scope

This is very strange and might explain what @chequille is seeing

@chequille: in your case, try to check to box, save the config and check your database, the row for 'website' should be gone and your problem on the frontend should be gone as well.

But this strange checkbox behavior feels like a bug to me.

@chequille: Thanks for the report and being persistent!

**Comment by chequille** [comment]
@hostep 
Ok, I did this and the entry in core_config_data is gone.
Now, it is working as it is set in default configuration.
I think, that you have to store at least once the MainWebsite configuration if the check box "use standard" is checked. 
This deletes the entry for scope websites as you said before and of course frontend is using the value from scope default.
If you do not do this and the entry for scope websites is in the database, frontend is using this entry even if "use standard" checkbox is checked.
That is my conclusion to this issue.

Thanks for your help and we will stay in contact.
BR
Chequille

**Comment by magento-engcom-team** [comment]
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19561` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rommelfreddy** [comment]
Hello ! is there an update for this ticket?
is this ticket already in development?

**Comment by rommelfreddy** [comment]
i digged a little bit more into this issue and figured out, that it isn't a bug, just a misconfiguration of the paypal module.
I guess that the configuration of the Context-Setting is by default in the default-website set to "Yes".
So you just must change the scope of the configuration to the default website (if you have a single store) and check the checkbox behind the field to "use default" (in german language: "Standard verwenden").
If you have a multistore, you must figure out which was the first website, that was set up.

After you checked the checkbox the configuration of the default-configuration will used.

I got this issue also with some other settings of the PayPal express module.
Maybe there is a "bug" in the module-installation. Or is it a feature ? 😆 

@chequille if you still have troubles with the configuration scope, maybe this guide will help you:
https://docs.magento.com/user-guide/configuration/scope-change.html#set-the-configuration-scope

**Comment by magento-engcom-team** [comment]
Hi @chequille. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23993` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
