### ISSUE TITLE
Image component of pagebuilder events are not triggered properly

### ISSUE THREAD

**Issue by tnsezer** [magento/magento2#24141]
### Preconditions (*)

1. Magento 2.3.2
2. Php 7.2

### Steps to reproduce (*)

when to set an event for image uploadAfter
Example;
`_events.on("image:" + _this5.contentType.id + ":uploadAfter", function(args) {});`

It is triggered on image_uploader.js of Pagebuilder But the preview image upload component is built by image_uploader.js of Pagebuilder because when open the setting popup the image upload component is built by image_uploader.js of Magento Ui (see the images below)

https://i.ibb.co/zbCVxD5/Screenshot-from-2019-08-15-10-28-03.png
https://i.ibb.co/qxYP4yF/Screenshot-from-2019-08-15-10-28-40.png

### Expected result (*)

Those  components should be built by image_uploader.js of Pagebuilder and both of them should trigger events

### Actual result (*)
Only one of them triggers events

**Comment by engcom-Charlie** [comment]
Hello @tnsezer 
You messed up the repository, such questions should be left here https://github.com/magento/magento2-page-builder/issues.
Please refer to this repository and you will definitely be helped.
Thank for your report!
