### ISSUE TITLE
Product objects don’t fully reset after executing $product->reset()

### ISSUE THREAD

**Issue by jrvision** [magento/magento2#24156]
Description:
When looping through products, and using a product object pushed through DI (in the constructor) and loading it, the load fails on Configurable Products if the product before was a simple product.  The reset seems to clear the data array and unlock the attributes for what that means.  However the Type Instance (model class) never gets reset.  This causes the configurable product when loaded to throw an error that getting product options (or something similar) is not a function on the class \Magento\Catalog\Model\Product\Type\Simple.

Possible solution 
This was how we solved that without altering any Magento Core files
$this->productObject->reset()->setTypeInstance(null);

We would recommend that the reset method on line 2122 of /Magento/Catalog/Model/Product should look like this

    public function reset()
    {
        $this->unlockAttributes();
        $this->_clearData();
        $this->setTypeInstance(null);
        return $this;
    }

**Comment by engcom-Charlie** [comment]
Hello @jrvision 
Can you add some steps to reproduce and other required info?
You can use this guide https://github.com/magento/magento2/wiki/Issue-reporting-guidelines.

**Comment by engcom-Charlie** [comment]
Hello @jrvision 
I am closing this issue now due to inactivity.
Please update if you wish to continue.
Thank you for the collaboration!
