### ISSUE TITLE
Spacing Issue with the Admin grids pages

### ISSUE THREAD

**Issue by sudheer-gajjala** [magento/magento2#24152]
### Preconditions (*)

1. Magento 2.2
2. Magento 2.3

### Steps to reproduce (*)

1. Login to Magento admin.
2. Go to Catalog > Product page.
3. Space between the select box and "per page" text is not consistent when compared to Reports > Products in Cart page
4. The same issue exist with Customers > All Customers Grid, Content >Pages Grid and many other pages  

### Expected result (*)

1. Select Input box should have a space of 0.7 rem after select box.

### Actual result (*)
1. There is no space of 0.7 rem after Select Input box which is not as per Magento standards. Please refer screen shot.

**Actual Result:**
![2019-08-16_18-42-23](https://user-images.githubusercontent.com/51822411/63171133-8b67c700-c058-11e9-9db8-0595148a00a2.png)

**Expected Result:**
![2019-08-16_18-38-04](https://user-images.githubusercontent.com/51822411/63171099-7854f700-c058-11e9-9f7b-fcdca668f394.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19340` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sudheer-gajjala. Thank you for your report. 
The issue has been fixed in magento/magento2#24359 by @Nagamaiah333 in 2.3-develop branch
Related commit(s):
 - [785cdcdfaa618ed77d896dcda5658b17514c61c8](https://github.com/magento/magento2/commit/785cdcdfaa618ed77d896dcda5658b17514c61c8)

The fix will be available with the upcoming 2.3.4 release.
