### ISSUE TITLE
 Step 2: Add a Database : "Database user does not have enough privileges."

### ISSUE THREAD

**Issue by ek0892** [magento/magento2#2415]
Use Ubuntu 14.04 with plesk 12.5 . php 5.6.14 . mysql 5.6.27    .

No problems if create bases for magento 1.9, wordpress or others applications. and All privileges user mysql are ready .

while installing Magento2, I get an error at step # 2 "Add a Database."

Database user does not have enough privileges. Please make sure SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER privileges are granted to table 'magento4'.

**Comment by mazhalai** [comment]
@ek0892 can you please login to mysql using the db user specified in setup wizard and 
show output from the command `SHOW GRANTS FOR CURRENT_USER();` exact details [here](https://dev.mysql.com/doc/refman/5.7/en/show-grants.html)

**Comment by ek0892** [comment]
SHOW GRANTS;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for magento4@%                                                                                                                                            |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT FILE ON _._ TO 'magento4'@'%' IDENTIFIED BY PASSWORD <secret>                                                                                              |
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW ON `magento4`.\* TO 'magento4'@'%' |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0,00 sec)

**Comment by mazhalai** [comment]
User `magento4@%` is missing permissions for `REFERENCES, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER`

**Comment by ek0892** [comment]
if active this,  no change the problem : SHOW GRANTS FOR CURRENT_USER();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for magento4@%                                                                                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT FILE, EXECUTE, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON _._ TO 'magento4'@'%' IDENTIFIED BY PASSWORD <secret>                                                                                              |
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `magento4`.\* TO 'magento4'@'%' |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0,00 sec)

but is not possible change "REFERENCES" in plesk ?

**Comment by mazhalai** [comment]
That should be a question to plesk. `REFERENCES` is very commonly used in foreign_keys https://dev.mysql.com/doc/refman/5.6/en/privileges-provided.html#priv_references

**Comment by ek0892** [comment]
Thank you very much I will put the question to Odin (Plesk).. but that is not win.

**Comment by mazhalai** [comment]
@ek0892 Thank you. Closing this issue. Please open a new issue if you still have problems
