### ISSUE TITLE
Uncaught TypeError: Cannot read property 'collapsed' of null

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#24151]
It can be hard to reproduce. At the bottom of this page, there is a case that shows how to get this error with probability not lower than 99%

### Preconditions (*)

1. Fresh install

### Steps to reproduce (*)

1. Log in to admin (On a fresh install, can be not reproducible in production mode)
2. Open DevTools (`<Ctrl|Cmd> + <Shift> + <I>`). 
2. Type in search one of these without quotes: wishlist, xml, **paypal**. Tip: can be not reproducible if the page was visited by navigating manually before or in the production mode.
3. Wait for search autocomplete. Click on the link related to the Magento configuration

### Expected result (*)

1. Search allows me to navigate between settings multiple times.
2. DevTools without error.
3. Can search again.
4. Sidebar navigation works
5. Refresh of the page helps to go away from the page

### Actual result (*)

1. Search stuck after one successful navigation
2. DevTools Javascript Console contains an error.
3. Can not search again.
4. Sidebar navigation doesn't work
5. Refresh of the page doesn't help
![search](https://user-images.githubusercontent.com/51680745/63171952-48e8bf00-c045-11e9-8429-35b6522f54b1.gif)

**Fast way:**
1. Add Secret Key to URLs = No
2. Flush cache
3. Navigate to `{base_url}/admin/admin/system_config/edit/section/rss/group/options/field/wishlist_share_enabled/`

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-24151-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24151-2-3-develop.instances.magento-community.engineering/admin](https://i-24151-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19339` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/magento2#24158 by @sunilit42 in 2.3-develop branch
Related commit(s):
 - [8189449897ed01a3d532b8ea6390082ef3b1bd47](https://github.com/magento/magento2/commit/8189449897ed01a3d532b8ea6390082ef3b1bd47)
 - [8e08b2180f07f264ca08f3b580d2b8db5d9eae6c](https://github.com/magento/magento2/commit/8e08b2180f07f264ca08f3b580d2b8db5d9eae6c)

The fix will be available with the upcoming 2.3.4 release.

**Comment by TomashKhamlai** [comment]
:thinking:
