### ISSUE TITLE
Meta title & description are updated at backend but not able to see it live on website.

### ISSUE THREAD

**Issue by chandantyagi1** [magento/magento2#24161]
### Summary (*)
Meta title & description are updated at the backend but not able to see it live on the website..

**Comment by engcom-Bravo** [comment]
Hello @chandantyagi1. Please Include and fill in all the required parts in the issue's description like Preconditions, Steps to Reproduce, Expected and Actual results in order to make the issue have a valid format. Thank You.

**Comment by engcom-Bravo** [comment]
@chandantyagi1, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
