### ISSUE TITLE
"Layered Navigation Price Step" must validate number

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24169]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Catalog->Categories
3. in "Display Settings" -> "Layered Navigation Price Step"
4. Fill "test"
5. Save

### Expected result (*)

1. Can not save, because it is not number

### Actual result (*)

1. Still save, and after save, the value is "0.0000"

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24169-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24169-2-3-develop.instances.magento-community.engineering/admin](https://i-24169-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19405` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24170 by @edenduong in 2.3-develop branch
Related commit(s):
 - [a041a3e6f1042f999a154cd1e508c7a6bde6a44a](https://github.com/magento/magento2/commit/a041a3e6f1042f999a154cd1e508c7a6bde6a44a)

The fix will be available with the upcoming 2.3.4 release.
