### ISSUE TITLE
magento 2.3.1 cache and indexer are not defined namespace 

### ISSUE THREAD

**Issue by surya357** [magento/magento2#24189]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by surya357** [comment]
> Hi @surya357. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @surya357 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @surya357. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @surya357, here is your [Magento instance](https://i-24189-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24189-2-3-develop.instances.magento-community.engineering/admin](https://i-24189-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by surya357** [comment]
![Capture](https://user-images.githubusercontent.com/54279799/63276178-7f7e3e00-c2c0-11e9-9791-c520986f55fe.PNG)
![Capture1](https://user-images.githubusercontent.com/54279799/63276179-7f7e3e00-c2c0-11e9-8436-2549dc0c4ad3.PNG)
this is the issue iam facing even i update all dependacies so please give an idea to solve it

**Comment by hostep** [comment]
@surya357: try executing `bin/magento` and you'll most likely see an error at the bottom. That might help you further.

I'm going to close this issue now, because Github is intended for bug reports, not for support questions. Hope you don't mind. If you have further support questions, please refer to https://community.magento.com or https://magento.stackexchange.com
