### ISSUE TITLE
Add video for product?

### ISSUE THREAD

**Issue by nhimxugia** [magento/magento2#2418]
I can't add videos for my product. No action to show when click add video button
http://prntscr.com/94e43z

I used:
Xampp lastest version
Firefox
Window 10

**Comment by anton-huz** [comment]
HI,
Could you screen browser with opened console (F12 on latest Chrome, Firefox, IE)?
Also latest commit (if you pull from github) will be handy.
It should not be environment' (XAMPP, Win) issue. Looks like some javascript files was not loaded on that moment.

**Comment by nhimxugia** [comment]
It work fine!..Thanks
