### ISSUE TITLE
Product URL Rewrites are not removed when product removed from website

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#24184]
### Preconditions (*)
1. 2.4-develop

### Steps to reproduce (*)
1. Deploy 2.4-develop
2. Create 2nd Website, 2nd Store, 2nd Store View
3. Create New Cateogory
4. Create New Product in New Category
5. Add product to Main Website and 2nd Website
6. Check URL table contains entries for Product, Category/Product for each store in each website
7. Remove Product from 2nd Website

### Expected result (*)
6. Check URL table contains entries for Product, Category/Product for only the stores in the first website

### Actual result (*)
1. URL Rewrites remain for all stores in all websites

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19416` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-24184-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24184-2-3-develop.instances.magento-community.engineering/admin](https://i-24184-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by naydav** [comment]
Reopened due to fix reverting.
See details in https://github.com/magento/inventory/pull/2887

**Comment by gwharton** [comment]
This turned out to be more complicated than i originally thought. Removing rewrites is broken for the product page. And adding and removing rewrites are both broken when adding and removing websites from massaction.

I will leave this for someone else to pick up. Feel free to use anything from the PR that was reverted.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23975` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Closed by mistake
Reopen

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38931` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
