### ISSUE TITLE
Placing order in Admin for backordered items shows incorrect backorder message

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#24191]
### Preconditions (*)
1. magento 2.3-develop

### Steps to reproduce (*)
1. Deploy 2.3-develop
2. Create Test Product with Qty 10, and Allow backorders with Notify Customer
3. Create Test Customer
4. Sales Order -> Create New Order
5. Select Test Customer
6. Add Products
7. Select Test Product and enter qty 15
8. Add selected product to order

### Expected result (*)
1. Warning Displayed that 5 need to be backordered

### Actual result (*)
1. Two warnings displayed, one for backorder of 5, and one for backorder of 15.

Infact

10 products in stock
Try and order 8, you get a single warning that 6 need backordering
Try and order 11, you get two warnings, one for 1, and one for 11.

It is due to Line 137 here

https://github.com/magento/inventory/blob/4eed86a0b93e905e41744f6d77de1943c8f22731/app/code/Magento/Sales/Block/Adminhtml/Order/Create/Items/Grid.php#L130-L143

Where the grid code actually calls setqty(getqty) on the quote to trigger off an event dispatch.

This actually causes the quote to be revalidated for the wrong quantity.

![image](https://user-images.githubusercontent.com/30697781/63284267-1213e280-c2ab-11e9-91a8-25f88eb60cf6.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24191-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24191-2-3-develop.instances.magento-community.engineering/admin](https://i-24191-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19431` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mazurekiza** [comment]
mazurekiza #mm19pl

**Comment by magento-engcom-team** [comment]
@mazurekiza thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by vietanh1606** [comment]
[mcfeelys.zip](https://github.com/magento/magento2/files/3945560/mcfeelys.zip)
This is module for fix this issue

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
