### ISSUE TITLE
catalog_product_entity_varchar value field is too short

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#24199]
### Preconditions (*)

1.Magento 2.3.2
2.php 7.2

### Steps to reproduce (*)

1.Create multiselect attribute
2. Add some values to it (more is better )
3. Create product select all options from created attribute.

### Expected result (*)

1. Product must contain all selected options

### Actual result (*)

1. Product is saved but not all options where added since the field is limited to 255 characters

### Solution
After discussion with architect @akaplya 
> Please do not change caalog_product_entity value data type. instead, change storage from varchar to text table

**Comment by FreekVandeursen** [comment]
This is actually a regression from Magento 1, where multiselect was updated from varchar to text table at some point.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24199-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24199-2-3-develop.instances.magento-community.engineering/admin](https://i-24199-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19514` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gloriadg20** [comment]
#cd19latam

**Comment by gloriadg20** [comment]
The issue has been replicated and we've found that due to the kind of issue, and that this issue is affected by the type of data in the database, this issue must be checked by Magento architec, in order to know if it's possible to change the data type of the field in database or increase the actual value of the same.

**Comment by saark-akash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @akashwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @akashwebkul, here is your [Magento instance](https://i-24199-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24199-2-3-develop.instances.magento-community.engineering/admin](https://i-24199-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by PivitParkour94** [comment]
So is the length of the varchar data getting changed? Or is there a different backend_type value we should use for long custom product attributes?

**Comment by Naberdz** [comment]
@PivitParkour94 the length of 255 is not enough for multiselect attribute. if you have selected 70 options * ( 3( length of id ) + 1(separating char) )  we will get 70*4 -1=279 which is greater than 255.

**Comment by PivitParkour94** [comment]
@Naberdz yeah I get that, I was more asking if we were supposed to continue using the varchar EAV `backend_type` but found in core there was a `text` type that much larger and changed to using that and it all worked as expected

**Comment by tjorgensborg** [comment]
@PivitParkour94 How did you do to make it work for Layered Navigation?

**Comment by PivitParkour94** [comment]
@tjorgensborg sorry, I was just having an issue with the backend type of `varchar` being too short, so I changed it to `text` I didn't actually have this issue, I just wanted to point out that `text` was a larger column type available. I should have been more clear.

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-23985` was closed as `non-reproducible` in ``2.4-develop``.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.

**Comment by qsolutions-pl** [comment]
This issue can be reprodeuced in ALL M2.4 versions...

**Comment by monvelweb** [comment]
> The related internal Jira ticket `MC-23985` was closed as `non-reproducible` in `2.4-develop`. It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.
> 
> But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.

if the magento team cant reproduce this, they may should look at jobs as janitors because they arent programmers.

**Comment by jakwinkler** [comment]
This was fixed by me in 2021, it is merged to the CORE along with proper data patch to move data from `_varchar` table into `_text` table :-) 
PR here: https://github.com/magento/magento2/pull/33487
I see no reason to rant in this ticket ;-)
