### ISSUE TITLE
One or more indexers are invalid. Make sure your Magento cron job is running.

### ISSUE THREAD

**Issue by citystamps** [magento/magento2#24192]
I just installed magento ver 2.3.2 via exlcusive hosting provider I use.

When I open the magento page I get this error

One or more indexers are invalid. Make sure your Magento cron job is running.

I tried to follow the guidlines to solve it via

"Please run the below command from your command line.

php bin/magento indexer:reindex

To resolve your indexer error.

If you want that to happen automatically then you will have to setup a cron job for that command to execute automatically."

I tried to do that in my cpannel via Hepsia Web SSH (beta)

and I get this error :

citystamps@web10:~/www/city-auctions.co.uk/magento$ php bin/magento indexer/reindex
Failed loading /usr/local/Zend5/lib/ZendExtensionManager.so:  /usr/local/Zend5/lib/ZendExtensionManager.so: wrong ELF class: ELFCLASS32
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php5/lib/php/extensions/no-debug-non-zts-20060613/memcached.so' - /usr/local/php5/lib/php/extensions/no-debug-non-zts-20060613/memcached.so: undefined symbol: empty_fcall_info in Unknown on line 0

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /home/www/city-auctions.co.uk/magento/bin/magento on line 15

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /home/www/city-auctions.co.uk/magento/bin/magento on line 20

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /home/www/city-auctions.co.uk/magento/bin/magento on line 20

Parse error: syntax error, unexpected T_STRING in /home/www/city-auctions.co.uk/magento/bin/magento on line 20

What am I doing wrong.

I have no knowledge on php or anything... sorry

**Comment by engcom-Bravo** [comment]
Hello @citystamps. Thanks for applying, but  the GitHub issue tracker is intended for Magento Core technical issues only. So please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
