### ISSUE TITLE
Cache needs clearing/Indexers reindexing after adding new Catalog Price Rule

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#24194]
# Preconditions (*)
1. 2.3-develop

### Steps to reproduce (*)
1. Deploy 2.3-develop
2. Create test category
3. Create test product with price 100, qty 1 in test category
4. Go to frontend in browser and navigate to product. Verify price is 100
5. Add new catalog price rule for Main website, Not logged in, 10%
6. Save and Apply catalog rule
7. Refresh Product page in browser. Check Price
8. Clear caches or reindex indexers
9. Refresh Product page in browser. Check Price

### Expected result (*)
1. New catalog price rule should be effective immediately

### Actual result (*)
1. Catalog price rule is only effective on uncached pages. Pages in cache display old price until cache is cleared.

**Comment by engcom-Bravo** [comment]
Hello @gwharton. Thanks for reporting. Please tell us what exactly You mean by Save and Apply: click on "Save and Apply" or click on "Save" and then on "Apply Rules". Because If it's about clicking "Save and Apply" the system output a message on reindex required. And once You've resolved it the Frontend Page shows the correct price with the rule applied. Thus it seems there is no wrong behavior.

**Comment by gwharton** [comment]
I click on "Save and Apply". OK, I see a warning that an indexer is invalid after applying rules.

If I do nothing else and go to the front end, the front end does not show the special price.

I have to either clear cache, or reindex to get the frontend to show new price.

Now that the price is applied, if I delete the rule, there is no warning about invalid indexers.

Going to the frontend still shows the special price, even though the rule is deleted.

Since when has it been policy to have to refresh cache, or manually reindex, on making a change in the backend. The system should invalidate/reindex what needs to be done when any change is made surely?

**Comment by engcom-Bravo** [comment]
Thank You @gwharton. You don't have to manually reindex if Your indexer is set to be updated by schedule and Your Cron jobs are running well. Of course the anticipated changes appearance on the Frontend would depend then on Cron schedules.

> If I do nothing else and go to the front end, the front end does not show the special price.

Should it show it anyway, even without keeping in the System Message requirements?

> Now that the price is applied, if I delete the rule, there is no warning about invalid indexers.

We do not observe such behavior after deleting an applied rule. Indexer message is there right after that.

> Since when has it been policy to have to refresh cache, or manually reindex, on making a change in the backend. The system should invalidate/reindex what needs to be done when any change is made surely?

Isn't this topic more appropriate for discussing it outside this issue?
So  the scenario You've described in this ticket in my opinion is not valid for the issue to be confirmed as You have ignored here a prompting system message. What do You think of it? Probably there still persists some buggish behavior around Catalog Price Rules, but in that case please edit the description to include appropriate steps.  Thank You.

**Comment by gwharton** [comment]
My indexers are set to run as stock Magento which should be index on save and my crons are running fine. It is a vanilla test installation for testing purposes.

The fact remains, if I edit the product price, it is reflected straight away on the frontend with no requirement to clear any caches, or reindex an indexers. So why is the catalog price rules any different. I apply them, and expect them to be there immediately.

Yes, there is a message warning me an indexer is invalid, but in my opinion that is a warning that Magento has failed to do something and I now need to intervene, i.e reindex indexer.
