### ISSUE TITLE
How to check the list of security patches applied on the magento EE 2.x

### ISSUE THREAD

**Issue by karthik32cse** [magento/magento2#24198]
I want to check the list of security patches applied on the Magento EE 2.x  store.

Thanks in advance

**Comment by krishprakash** [comment]
Hi @karthik32cse. Thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Thank You.
