### ISSUE TITLE
Backorder Quantities not calculated correctly when QuoteItem->addQty() used.

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#24203]
### Preconditions (*)
1. 2.3-develop

### Steps to reproduce (*)
1. Run the following integration test placed in 

/dev/tests/integration/testsuite/Magento/Quote/Model/Quote/Item/SetQtyTest.php

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\Quote\Model\Quote\Item;

use Magento\Quote\Api\CartItemRepositoryInterface;
use Magento\Quote\Model\Quote;
use Magento\TestFramework\Helper\Bootstrap;

class SetQtyTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var \Magento\Framework\ObjectManagerInterface
     */
    private $objectManager;

    /**
     * @var CartItemRepositoryInterface
     */
    private $quoteItemRepository;

    /**
     * @var Quote
     */
    private $quote;
    /**
     * @inheritdoc
     */
    protected function setUp()
    {
        $this->objectManager = Bootstrap::getObjectManager();
        $this->quoteItemRepository = $this->objectManager->create(CartItemRepositoryInterface::class);
        $this->quote = $this->objectManager->create(Quote::class);
    }

    /**
     * @magentoDataFixture                  Magento/Sales/_files/quote.php
     * @magentoConfigFixture current_store  cataloginventory/item_options/backorders 2
     */
    public function testSetQty(): void
    {
        $quoteItems = $this->quoteItemRepository->getList(
            $this->quote->load('test01', 'reserved_order_id')->getId()
        );

        $quoteItems[0]->setQty(200.0);
        $this->assertEquals(200.0, $quoteItems[0]->getQty());
        $this->assertEquals(100.0, $quoteItems[0]->getBackorders());

        $quoteItems[0]->setQty(110.0);
        $this->assertEquals(110.0, $quoteItems[0]->getQty());
        $this->assertEquals(10.0, $quoteItems[0]->getBackorders());

        $quoteItems[0]->addQty(10.0);
        $this->assertEquals(120.0, $quoteItems[0]->getQty());
        $this->assertEquals(20.0, $quoteItems[0]->getBackorders());

        $quoteItems[0]->setQty(110.0);
        $this->assertEquals(110.0, $quoteItems[0]->getQty());
        $this->assertEquals(10.0, $quoteItems[0]->getBackorders());

        $quoteItems[0]->setQty(200.0);
        $this->assertEquals(200.0, $quoteItems[0]->getQty());
        $this->assertEquals(100.0, $quoteItems[0]->getBackorders());
    }
}
```

### Expected result (*)
1. Integration test should pass

### Actual result (*)
1. Sadly it does not.

After adding 10 to the cart, the backorder quantity remains at 10. It should be 20. Even when the cart is manually set to 110 or 200, the backorder quantity remains at 10 for some reason.

The issue occurs because the quoteitem->addQty call adds a data item to the quoteitem object called qty_to_add with the quantity being added. The addQty call triggers the \Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\Initializer\StockItem.php::initialize routine to initialize a stock item and check for backorders. It checks for the presence of qty_to_add and checks if backorders will apply to the added quantity. The qty_to_add data item is not cleared after the addQty call is completed. 

Future calls to quoteitem->setQty also trigger the 
\Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\Initializer\StockItem.php::initialize routine to initialize a stock item and check for backorders, but it looks for the presence of qty_to_add and uses that to check for quantities instead of the real qty being set.

**Comment by gwharton** [comment]
Seems my initial conclusions only cover part of the issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21659` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by gwharton** [comment]
Don't know why I bothered. I wrote you an integration test that proved the issue but still noone was bothered to look at it, and now it gets closed. Looks like the bug will just remain.
