### ISSUE TITLE
CMS Page Grid View action should be allowed only for enabled pages

### ISSUE THREAD

**Issue by serhiyzhovnir** [magento/magento2#24208]
### Preconditions 

1. Magento 2.3.*

### Steps to reproduce (*)
1. Log in as an admin
2. Go to *Content > Elements > Pages*
3. Disable a CMS page
4. Try to use **View** action for the disabled page

### Expected result 

1. The View action is not shown for a disabled page
<img width="1794" alt="Screen Shot 2019-08-21 at 08 59 39" src="https://user-images.githubusercontent.com/31502344/63406350-480fae80-c3f2-11e9-942a-f7aea7225a9c.png">

### Actual result 

1. The View action is shown for a disabled page and it leads to 404 page
<img width="1920" alt="Screen Shot 2019-08-21 at 08 58 57" src="https://user-images.githubusercontent.com/31502344/63406360-5067e980-c3f2-11e9-8fd1-d5a5270a1841.png">
<img width="1357" alt="Screen Shot 2019-08-21 at 08 59 15" src="https://user-images.githubusercontent.com/31502344/63406362-5067e980-c3f2-11e9-9275-46a43eba24ec.png">

**Comment by engcom-Bravo** [comment]
Hello @serhiyzhovnir. Thanks for applying. But why You think it's  a bug? In fact View action shows how the page requested by the URL of {magento-instance-base-url}/{the page's URL-key} looks like. You can't ban one to manually navigate to lets say {magento-instance-base-url}/enable-cookies page in one's browser. The one will get some rendered page anyway even if Enable Cookies is disabled. So it's quite logical that the View Action should demonstrate that page. Why it should be unavailable for that page (the View Action)?

**Comment by dmytro-ch** [comment]
The issue is a bit tricky.
I guess, the "View" action was expected to be used as a preview feature:
```
    $item[$name]['preview'] = [
        'href' => $this->scopeUrlBuilder->getUrl(
            $item['identifier'],
            isset($item['_first_store_id']) ? $item['_first_store_id'] : null,
            isset($item['store_code']) ? $item['store_code'] : null
        ),
        'label' => __('View')
    ];
```
I would say that the preview feature is currently implemented not correctly. If the page is disabled, we always get the preview for CMS page set as 404 Not Found page in-store configurations. So admin user alwys has to enable the page in order check the actual view of the page on frontend.
In my opinion, this is also not correct behavior.

Thus, It would be better to provide a proper implementation for the Preview feature instead of removing the View action for disabled pages.

**Comment by engcom-Bravo** [comment]
Hi @dmytro-ch. I admit Your logic is quite viable. It's good for admin to be able to preview the page regardless of whether it's enabled or not. But though that logic is related to this issue, the issue itself is not literary about that logic - the Expected Results anticipates disabling View feature for the disabled pages. I think Your logic deserves (and it would be more correctly) to be raised up in a separate issue, and yes, with the label of "feature request".

**Comment by engcom-Bravo** [comment]
@serhiyzhovnir  or @dmytro-ch, please create a new feature request issue with the Expected result @dmytro-ch is talking about above if deem necessary. Thank You.
