### ISSUE TITLE
Some Fields in "Currency Setup" must have validate number

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24204]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Store->Configuration
2. General->Currency Setup
3. Fill "ggg" in "Connection Timeout in Seconds" of "Fixer.io" and "Currency Converter API"

### Expected result (*)

1. Can not save because it is not a number

### Actual result (*)

1. Save the wrong data

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24204-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24204-2-3-develop.instances.magento-community.engineering/admin](https://i-24204-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19497` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24205 by @edenduong in 2.3-develop branch
Related commit(s):
 - [b9646cea8324f2ca01da81a196d0e44fabf23644](https://github.com/magento/magento2/commit/b9646cea8324f2ca01da81a196d0e44fabf23644)

The fix will be available with the upcoming 2.3.4 release.
