### ISSUE TITLE
Hitting enter while creation of folder in media browser closes media browser

### ISSUE THREAD

**Issue by krisdante** [magento/magento2#24214]
Hitting enter while creation of folder in media browser closes media browser

### Preconditions (*)

1. Magneto 2.3.1 but also affects older ones and newer ones.

### Steps to reproduce (*)

1. Go to Content > Blocks > New Block
2. Use Insert Image option -> Media Browser will open
3. Use the option to Create Folder
4. Type in folder name like "foobar" and hit Enter key 

### Expected result (*)

1. Folder shall be created - the dialog shall behave the same way as I would click on OK button

### Actual result (*)

1. The folder is not created and all Magento Dialogs (including media browser) are being closed
2. The page gets reloaded and all your edits are lost

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19532` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by manuelmattar** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
@manuelmattar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by manuelmattar** [comment]
#cd19latam

**Comment by manuelmattar** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
Hi @krisdante. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23990` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
