### ISSUE TITLE
After Successful installation 2.0 CE getting JS error in console and don't let me to save anything

### ISSUE THREAD

**Issue by magearray** [magento/magento2#2421]
adding the errors below and giving 777 permision to pub directory

GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/extjs/resources/images/default/dd/drop-no.gif 403 (Forbidden)El.getStyle._9.getComputedStyle.el @ ext-tree.js:37Ext.extend.getZIndex @ ext-tree.js:181Ext.Layer @ ext-tree.js:181Ext.dd.StatusProxy @ ext-tree.js:105Ext.dd.DragSource @ ext-tree.js:109Ext.dd.DragZone @ ext-tree.js:117Ext.tree.TreeDragZone @ ext-tree.js:229Ext.extend.render @ ext-tree.js:193Ext.extend.loadTree @ (index):1280_renderNewTree @ (index):1454reRenderTree @ (index):1439(anonymous function) @ (index):1574fire @ jquery.js:3099self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3423completed @ jquery.js:3453
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/mage/adminhtml/wysiwyg/tiny_mce/plugins/magentowidget/editor_plugin.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/mage/adminhtml/wysiwyg/tiny_mce/plugins/magentowidget/editor_plugin.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/mage/adminhtml/wysiwyg/tiny_mce/plugins/magentovariable/editor_plugin.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/mage/adminhtml/wysiwyg/tiny_mce/plugins/magentovariable/editor_plugin.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/langs/en.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/langs/en.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/themes/advanced/editor_template_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/themes/advanced/editor_template_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/inlinepopups/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/inlinepopups/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/pagebreak/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/pagebreak/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/style/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/style/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/layer/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/layer/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/table/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/table/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/advhr/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/advhr/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/advimage/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/advimage/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/emotions/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/emotions/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/iespell/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/iespell/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/media/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/media/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/searchreplace/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/searchreplace/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/contextmenu/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/contextmenu/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/paste/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/paste/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/directionality/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/directionality/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/fullscreen/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/fullscreen/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/noneditable/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/noneditable/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/visualchars/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/visualchars/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/nonbreaking/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/nonbreaking/editor_plugin_src.js
tiny_mce_src.js:8665 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/xhtmlxtras/editor_plugin_src.js loadScript @ tiny_mce_src.js:8665(anonymous function) @ tiny_mce_src.js:8737tinymce.each @ tiny_mce_src.js:143loadScripts @ tiny_mce_src.js:8725loadScripts @ tiny_mce_src.js:8759loadQueue @ tiny_mce_src.js:8698loadScripts @ tiny_mce_src.js:11418tinymce.create.render @ tiny_mce_src.js:11424(anonymous function) @ tiny_mce_src.js:11311cb @ tiny_mce_src.js:7064(anonymous function) @ tiny_mce_src.js:7217tinymce.each @ tiny_mce_src.js:143tinymce.create._pageInit @ tiny_mce_src.js:7216(anonymous function) @ tiny_mce_src.js:7265
tiny_mce_src.js:8589 Failed to load: http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/tiny_mce/plugins/xhtmlxtras/editor_plugin_src.js
ext-tree.js:209 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/extjs/resources/images/magento/tree/elbow-end.gif 403 (Forbidden)Ext.extend.render @ ext-tree.js:209Ext.extend.render @ ext-tree.js:201Ext.extend.render @ ext-tree.js:193Ext.extend.loadTree @ (index):1280_renderNewTree @ (index):1454reRenderTree @ (index):1439(anonymous function) @ (index):1574fire @ jquery.js:3099self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3423completed @ jquery.js:3453
ext-tree.js:209 GET http://www.magearray.com/demo/pub/static/adminhtml/Magento/backend/en_US/extjs/resources/images/magento/tree/leaf.gif 403 (Forbidden)Ext.extend.render @ ext-tree.js:209Ext.extend.render @ ext-tree.js:201Ext.extend.render @ ext-tree.js:193Ext.extend.loadTree @ (index):1280_renderNewTree @ (index):1454reRenderTree @ (index):1439(anonymous function) @ (index):1574fire @ jquery.js:3099self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3423completed @ jquery.js:3453

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [Installing Magento 2](https://community.magento.com/t5/Installing-Magento-2/bd-p/installing-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
