### ISSUE TITLE
Virtual Quote shouldn't display "Shipping & Handling" total when Create New Order 

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24212]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Create New Order at backend
3. Add only "Virtual Product"
4. Check the Total at the bottom

![image](https://user-images.githubusercontent.com/8234209/63414322-cafe2c80-c425-11e9-99ff-a5b494844cd1.png)

### Expected result (*)

1. Shouldn't have "Shipping & Handling"

### Actual result (*)

1. 
Still have:

![image](https://user-images.githubusercontent.com/8234209/63414327-cf2a4a00-c425-11e9-8fb9-28684cf97142.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24212-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24212-2-3-develop.instances.magento-community.engineering/admin](https://i-24212-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19534` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24213 by @edenduong in 2.3-develop branch
Related commit(s):
 - [d7949280344ed316ded0871b831319c009548b37](https://github.com/magento/magento2/commit/d7949280344ed316ded0871b831319c009548b37)

The fix will be available with the upcoming 2.3.4 release.
