### ISSUE TITLE
Magento 2.3.2 How to remove the city field in checkout ?

### ISSUE THREAD

**Issue by magehardik** [magento/magento2#24217]
### Summary (*)

Hello,

Hope you are doing well!

How to remove city field into the Magento Checkout?

I have tried using the checkout_cart_index.xml file but no solution.

Please guide me.

Thanks

**Comment by engcom-Bravo** [comment]
Hello @hardikm-cirkleinc. Thanks for applying. But the GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
