### ISSUE TITLE
Add addComplexExceptionMessage method to ManagerInterface

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#24219]
### Summary (*)

There are the situations when you should
- log exception 
- display an alternative error message to customer

**Current solution:** use Magento\Framework\Message\ManagerInterface::addExceptionMessage

Minor part of `addExceptionMessage`: we can display to customer a text which does not have HTML or any special tags. For example, "We can not delete a customer". 

But if we want to display `We can't delete a customer` then customer will see `We can&#039;t delete the customer`.

### Proposed solution

Add new method - `Magento\Framework\Message\ManagerInterface`::`addComplexExceptionMessage`

### Examples of usage

*1.* Call: 

```
...
} catch (StateException $e) {
    $this->messageManager->addComplexExceptionMessage(
                'unableDeleteCustomerErrorMessage',
                $e,
                true,
                []
            );
}
....
```

*2.* Declaration in `frontend/di.xml`:

```
    <type name="Magento\Framework\View\Element\Message\MessageConfigurationsPool">
        <arguments>
            <argument name="configurationsMap" xsi:type="array">
                <item name="unableDeleteCustomerMessage" xsi:type="array">
                    <item name="renderer" xsi:type="const">\Magento\Framework\View\Element\Message\Renderer\BlockRenderer::CODE</item>
                    <item name="data" xsi:type="array">
                        <item name="template" xsi:type="string">Magento_Customer::messages/unableDeleteCustomerMessage.phtml</item>
                    </item>
                </item>
            </argument>
        </arguments>
    </type>
```

*3.* Template - `Magento/Customer/view/frontend/templates/messages/unableDeleteCustomerMessage.phtml`

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>

<?= $block->escapeHtml(__('We can\'t delete the customer.'));
```

**Comment by ihor-sviziev** [comment]
Based on discussion in related PR - this is not really correct behavior https://github.com/magento/magento2/pull/24220#issuecomment-606065187.
>  Exceptions should not be used for business logic, client code should build the response. The exception itself should not care about its message and moreover manage those messages.

I'm closing this issue as not relevant.
