### ISSUE TITLE
Content editor don't support html5 tags

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#2422]
Please make content editor support html5 tags

**Comment by dmitrii-fediuk** [comment]
Maybe somebody will be interested, I have done an alternative to TineMCE content editor with Markdown and HTML 5 syntax support: https://mage2.pro/t/160

**Comment by tkacheva** [comment]
@minhluan259 We are working on replacing WYSIWYG with more modern solution that supports html 5. Stay tuned. MAGETWO-36659

**Comment by minhluan259** [comment]
Awesome, Thank you.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Content-editor-don-t-support-html5-tags/idi-p/46494).
