### ISSUE TITLE
cart persistent, shipping rates survive changing store

### ISSUE THREAD

**Issue by davidlopes** [magento/magento2#24222]
With the persistent cart enabled we found that switching store, clear the cart but shipping information persists, including shipping rates.

### Preconditions (*)
1. Magento EE 2.3.1
2. PHP 7.1
3. 10.0.37-MariaDB-1~jessie-wsrep

### Steps to reproduce (*)
1. Add a product into cart
2. Go to checkout and fill address
3. Print Shipping Methods
4. Change Website
5. Cart is empty now. Repeat steps 1-2
6. Shipping methods are the same, even if they are not active in this website

### Expected result (*)
when cart clears, shipping information should clear as well .

### Actual result (*)
when cart clears, shipping information persists, even if is not valid

**Comment by engcom-Bravo** [comment]
Hello @davidlopes. Thanks for reporting. Yes we've noticed that the shipping information persists after the cart has been cleared but the shipping methods lists in our case remain correct. i.e. corresponding to their websites. 

> Shipping methods are the same, even if they are not active in this website

So we could confirm the issue only without that. Could You please try to reproduce Your issue on a vanilla Magento 2.3-develop installation and tell us if You still can reproduce the behavior with the shipping methods. Thank You.

**Comment by davidlopes** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @davidlopes. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @davidlopes, here is your [Magento instance](https://i-24222-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24222-2-3-develop.instances.magento-community.engineering/admin](https://i-24222-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by davidlopes** [comment]
hi @engcom-Bravo, 
I was not able to reproduce the persistent methods in vanilla.

**Comment by engcom-Bravo** [comment]
Hi again, @davidlopes. Are there any updates?

**Comment by davidlopes** [comment]
Hi @engcom-Bravo,
Sorry did not got time yet. will try to test during this week.

**Comment by engcom-Bravo** [comment]
Hi again @davidlopes. Please Excuse me, but the contributor guide suggests that tickets that have not been active for two weeks should be closed. If You find the way how to reproduce the issue on a vanilla just let me know and we'll reopen it. Good luck.
