### ISSUE TITLE
Magento 2.3.2 Required parameter 'theme_dir' was not passed

### ISSUE THREAD

**Issue by Anantkprajapati** [magento/magento2#24224]
### Preconditions (*)
1. Magento 2.3.2

### Steps to reproduce (*)

1. Login to backend 
2. Go to Marketing > Email Templates 
3. Add New Template
4. Load Default Email template and select New Account : 

### Expected result (*)

1. there should load default New Account template

### Actual result (*)

1. getting error :  http://prntscr.com/ovr6v6

Notes : I checked in exception log and getting error like 
main.CRITICAL: Required parameter 'theme_dir' was not passed.{"area":"frontend","locale":"en_US","module_name":"Magento_Customer","file":"account_new.html","theme_dir":null}"
May be this is happen with all those templates which have more than one templates.

**Comment by engcom-Bravo** [comment]
Hello @Anantkprajapati. Thanks for applying. Please watch the gif below if we do everything right.
![template](https://user-images.githubusercontent.com/51680745/63509979-209a0e00-c4e6-11e9-9213-583883dc60bb.gif)

**Comment by Anantkprajapati** [comment]
Hello @engcom-Bravo - i see i installed fresh magento2.3.2 and it's look like working fine.
Thank you

**Comment by engcom-Bravo** [comment]
You are welcome, @Anantkprajapati.
