### ISSUE TITLE
Dynamic comment for Group element in system.xml

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24221]
How can I make a dynamic comment for a `<group>` element in the `system.xml`?

I need to have a group level comment that I can pass the store URL into.

Now, `<field>` element comments can use a Model class that implements `CommentInterface` to return a custom string. But this is not possible for `<group>` comments, because the XSD schema does not allow it.

What are my options or viable alternatives?

**Comment by engcom-Bravo** [comment]
Hello, @paul-gene. Thanks for applying. But this GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
