### ISSUE TITLE
"Thumbnail" in Related Products, Up-Sells, and Cross-Sells has the redundant Label

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24228]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Create New Product
3. In "Related Products, Up-Sells, and Cross-Sells" add some product from Modals

![image](https://user-images.githubusercontent.com/8234209/63486169-8b404f00-c4d0-11e9-9d06-9e0dbb1ec0a4.png)

### Expected result (*)

1. Don't have the redundant "Thumbnail" Text

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/63486169-8b404f00-c4d0-11e9-9d06-9e0dbb1ec0a4.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-24228-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24228-2-3-develop.instances.magento-community.engineering/admin](https://i-24228-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24228-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24228-2-3-develop.instances.magento-community.engineering/admin](https://i-24228-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
In 2.3-develop instance, Now can not go to "Related Products, Up-Sells, and Cross-Sells"  Modal

**Comment by edenduong** [comment]
Seems I can not reproduce now. Maybe it is solved. So I will close this issue. Thanks.

**Comment by ajijshekh123** [comment]
In Magento 2.3 Instance, Related Products, Up-Sells, and Cross-Sells" section, It is displaying properly.

![2019-08-22](https://user-images.githubusercontent.com/24711761/63486965-1f0d1d80-c4c7-11e9-81e0-017d1d6c037e.png)
