### ISSUE TITLE
Incorrect decimal separator in minicart and checkout.

### ISSUE THREAD

**Issue by mfickers** [magento/magento2#24234]
### Preconditions (*)

1. Reproduced on Magento 2.3.0 and 2.3.2 and 2.3-develop

### Steps to reproduce (*)

1. Set the storefront locale to a locale with a comma as a decimal separator (e.g. de_DE) (this step is not required).
2. Create a product with a decimal quantity.
3. Add the product with a decimal quantity to your cart.

### Expected result (*)

1. Item quantity is displayed with a comma as decimal separator everywhere.

### Actual result (*)

1. Minicart item counter and checkout summary show the incorrect decimal separator:
![Bildschirmfoto 2019-08-22 um 14 08 36](https://user-images.githubusercontent.com/12683535/63514046-fb0e0400-c4e7-11e9-9dde-cfe4098c610f.png)
![Bildschirmfoto 2019-08-22 um 14 08 47](https://user-images.githubusercontent.com/12683535/63514047-fba69a80-c4e7-11e9-8148-e9908034e6d5.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19571` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Shubham0492** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-24234-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24234-2-3-develop.instances.magento-community.engineering/admin](https://i-24234-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Shubham0492** [comment]
Reproduced on 2.3.x

**Comment by magento-engcom-team** [comment]
Hi @mfickers. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23996` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
