### ISSUE TITLE
Deploy shared folders and actions

### ISSUE THREAD

**Issue by luckyraul** [magento/magento2#2423]
Can anyone help me with creation deploy scenario?

Which folders and files should be shared between releases ( for ex - pub/media, var, ) ? 

What actions shell I run with bin/magento during production deploy ? 

I guess it should be documented however I didn't find anything related to this question

**Comment by BlackIkeEagle** [comment]
@luckyraul I think only pub/media and app/etc/env.php are shared files

from what I see the following commands are needed for deploy:
bin/magento setup:di:compile
bin/magento setup:static-content:deploy
bin/magento setup:upgrade

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [Installing Magento 2](https://community.magento.com/t5/Installing-Magento-2/bd-p/installing-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by luckyraul** [comment]
this is a bug in documentation )

**Comment by daim2k5** [comment]
So please create a issue and if you like also a PR here: https://github.com/magento/devdocs
