### ISSUE TITLE
setting custom attributes unexpected TypeError

### ISSUE THREAD

**Issue by LukaszDembicki** [magento/magento2#24238]
### Summary (*)
The unit test:

```
public function testSomeCustomAttributesTest()
{
    $product = $this->objectManagerHelper->getObject(Product::class);
    $product->setCustomAttributes([]);

    $product->getCustomAttributes();
}

```
Will produce TypeError : Argument 1 passed to Mock_FilterProductCustomAttribute_33fe8dcd::execute() must be of the type array, null given, called in /var/www/magento/vendor/magento/module-catalog/Model/Product.php on line 517
 /var/www/magento/vendor/magento/module-catalog/Model/Product.php:517

Seems there is a problem in `Magento\Catalog\Model\Product` in constructor`$filterCustomAttribute` is called after method `getCustomAttributesCodes` so `$filterCustomAttribute` is not initialized and there is no way to mock it.

Greetings

**Comment by georgebabarus** [comment]
You should mock the getEntityAttributes method because it is used

    public function testSomeCustomAttributesTest()
    {
        $this->eavConfig->expects($this->once())
                        ->method('getEntityAttributes')
                        ->willReturn([]);

        $this->model->setCustomAttributes([]);

        $this->model->getCustomAttributes();
    }

**Comment by sudheers-kensium** [comment]
@LukaszDembicki this is not an  isuue.
