### ISSUE TITLE
Unable to Verify Password Reset Token Without Customer ID - REST API

### ISSUE THREAD

**Issue by c-doug** [magento/magento2#24245]
The REST API endpoint for validating a password reset token will always fail unless a valid customer id is provided.

In the documentation (https://devdocs.magento.com/redoc/2.3/customer-rest-api.html#operation/customerAccountManagementV1ValidateResetPasswordLinkTokenGet) the customerId parameter description outlines 
> If null is given then a customer will be matched by the RP token

It is impossible to provide null for this GET request. The default password reset link that contains the reset token does not contain the customer ID. 

### Preconditions (*)

1. Magento 2.3.1. & 2.3-develop
2. At least one customer must exist.

### Steps to reproduce (*)

1. Issue a password reset email for an existing customer.
2. Attempt to validate the password reset token via the REST API without customer ID since it is unavailable.

### Expected result (*)

1. The password reset token is used to match the customer account.
2. The reset password token is compared.

### Actual result (*)

1. Without the customer ID (which is unavailable) this API call will always fail.

### Examples
The link sent to the customer email address does not contain the customer ID. `{{base_secure_url}}/customer/account/createPassword/?token={resetPasswordLinkToken}` 

The documentation example shows the following:
`/V1/customers/{customerId}/password/resetLinkToken/{resetPasswordLinkToken}`

This REST API endpoint resolves to the validateResetPasswordLinkToken method of class Magento\Customer\Model\AccountManagement.

Internally, the following snippet is used, and so customer ID is not required as the token can identify the customer on its own:
`$this->accountManagement->validateResetPasswordLinkToken(null, $resetPasswordToken);`

However, it is not possible to pass a null value via the REST API without impacting the routing of this request.

Removing the customer id portion entirely routes differently and results in a no route response.
`/V1/customers/password/resetLinkToken/{resetPasswordLinkToken}`
`{"message":"Request does not match any route.","trace":null}`

Providing a URL encoded null value fails with a 404 html response:
`/V1/customers/%00/password/resetLinkToken/{resetPasswordLinkToken}`
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>404 Not Found</title>
> </head><body>
> <h1>Not Found</h1>
> <p>The requested URL /rest/V1/customers/ was not found on this server.</p>
> </body></html>

Passing the phrase null, or any other non-integer value responds with a type error:
`/V1/customers/null/password/resetLinkToken/{resetPasswordLinkToken}`
`{"message":"The \"null\" value's type is invalid. The \"int\" type was expected. Verify and try again.","trace":null}`

Passing a zero value also fails:
`/V1/customers/0/password/resetLinkToken/{resetPasswordLinkToken}`
`{"message":"Invalid value of \"%value\" provided for the %fieldName field.","parameters":{"value":0,"fieldName":"customerId"}`

**Comment by c-doug** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @c-doug. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @c-doug, here is your [Magento instance](https://i-24245-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24245-2-3-develop.instances.magento-community.engineering/admin](https://i-24245-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by c-doug** [comment]
I'm guessing these instances are not set up to allow sending of email. Without that I cannot receive my password reset token to use in the API call. Thats fine though, it won't even get to the point of verifying the token because an error is returned with every response I've tried that has no customerId.

`curl https://i-24245-2-3-develop.instances.magento-community.engineering/rest/V1/customers/{cusomter_id}/password/resetLinkToken/55555_fakeresettoken_55555`
`{"message":"The \"cusomter_id\" value's type is invalid. The \"int\" type was expected. Verify and try again."}`

`curl https://i-24245-2-3-develop.instances.magento-community.engineering/rest/V1/customers/null/password/resetLinkToken/55555_fakeresettoken_55555`
`{"message":"The \"null\" value's type is invalid. The \"int\" type was expected. Verify and try again."}`


`curl https://i-24245-2-3-develop.instances.magento-community.engineering/rest/V1/customers/0/password/resetLinkToken/55555_fakeresettoken_55555`
`{"message":"Invalid value of \"%value\" provided for the %fieldName field.","parameters":{"value":0,"fieldName":"customerId"}}`

`curl https://i-24245-2-3-develop.instances.magento-community.engineering/rest/V1/customers/password/resetLinkToken/55555_fakeresettoken_55555`
`{"message":"Request does not match any route."}`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19600` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vitalii0o** [comment]
@magento I am working on it

**Comment by magento-engcom-team** [comment]
Hi @c-doug. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23998` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.2` release.

**Comment by ihor-sviziev** [comment]
This issue was closed due to the lack of attention from the community - it looks like not so many people are getting it. It also wasn't fixed in 2.4.x

**Comment by srsathish92** [comment]
Temporary fix: 

```diff --git a/vendor/magento/module-customer/Api/AccountManagementInterface.php b/vendor/magento/module-customer/Api/AccountManagementInterface.php
index 10fc23499..c7abf9b97 100644
--- a/vendor/magento/module-customer/Api/AccountManagementInterface.php
+++ b/vendor/magento/module-customer/Api/AccountManagementInterface.php
@@ -160,7 +160,7 @@ interface AccountManagementInterface
     /**
      * Check if password reset token is valid.
      *
-     * @param int $customerId If null is given then a customer
+     * @param mixed $customerId If null is given then a customer
      * will be matched by the RP token.
      * @param string $resetPasswordLinkToken
      *
diff --git a/vendor/magento/module-customer/Model/AccountManagement.php b/vendor/magento/module-customer/Model/AccountManagement.php
index a1cb6606d..40a5f3551 100644
--- a/vendor/magento/module-customer/Model/AccountManagement.php
+++ b/vendor/magento/module-customer/Model/AccountManagement.php
@@ -1151,7 +1151,7 @@ class AccountManagement implements AccountManagementInterface
     /**
      * Validate the Reset Password Token for a customer.
      *
-     * @param int $customerId
+     * @param mixed $customerId
      * @param string $resetPasswordLinkToken
      *
      * @return bool
@@ -1164,7 +1164,7 @@ class AccountManagement implements AccountManagementInterface
      */
     private function validateResetPasswordToken($customerId, $resetPasswordLinkToken)
     {
-        if ($customerId !== null && $customerId <= 0) {
+        if ($customerId !== null && $customerId !== 'null' && $customerId <= 0) {
             throw new InputException(
                 __(
                     'Invalid value of "%value" provided for the %fieldName field.',
@@ -1173,7 +1173,7 @@ class AccountManagement implements AccountManagementInterface
             );
         }
 
-        if ($customerId === null) {
+        if ($customerId === null || $customerId === 'null') {
             //Looking for the customer.
             $customerId = $this->getByToken
                 ->execute($resetPasswordLinkToken)```

**Comment by srsathish92** [comment]
@magento I am working on it
