### ISSUE TITLE
"Save Product" with the invalid data must scroll to the error message

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24241]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Create New Product
3. Fill all required field
4. Scroll down to "Schedule Design Update", fill date of "From" is greater than date of "To"
5. Click Save

### Expected result (*)

1. Scroll to the error message "Make sure the To Date is later than or the same as the From Date." so user can see the error message

### Actual result (*)

1. Nothing happen. User can not see anything and don't know the product isn't saved

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-24241-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24241-2-3-develop.instances.magento-community.engineering/admin](https://i-24241-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19603` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24242 by @edenduong in 2.3-develop branch
Related commit(s):
 - [157e1cdea9940c808f558f29af193d0d74bc74ea](https://github.com/magento/magento2/commit/157e1cdea9940c808f558f29af193d0d74bc74ea)

The fix will be available with the upcoming 2.3.4 release.
