### ISSUE TITLE
Catalog Conditions - 'contains' works as "is"

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#2424]
It looks like 'contains' works as "is", for example condition "SKU contains test" will not be true for SKU which actually contains 'test', e.g. 'testblabla'.

Please also let me know what is the difference between 'contains' and 'is one of' for multiple selection:
sku contains value1, value2 
and
sku is one of value1, value2
What is the difference and how should it actually work?

**Comment by maksek** [comment]
Please ask questions on forum, you won't get answer in github. GitHub only for bugs with proper descriptions.

**Comment by stasleo** [comment]
> It looks like 'contains' works as "is", for example condition "SKU contains test" will not be true for SKU which actually contains 'test', e.g. 'testblabla'.

Isn't it a bug? As for me, it's an obvious bug, and you close the issue.  `¯\_(ツ)_/¯`

Ok, here is my "_proper description_" of the bug:
1) Create a product with sku **testblabla**
2) Create a catalog rule with condition  **SKU contains test** so that it give 20% discount on the product in catalog
3) Apply and enjoy the actual result

Expected result: the new product has 20% discount because of created catalog rule, because product's sku DOES CONTAIN 'test'
Actual result: the rule does not impact the product price.

Please take a look @ishakhsuvarov @voleye @maksek @piotrekkaminski

**Comment by pboisvert** [comment]
@tkacheva Can you have the team investigate this one?

**Comment by tkacheva** [comment]
@pboisvert the research is in progress. Internal ticket is MAGETWO-51920

**Comment by tkacheva** [comment]
bug reported MAGETWO-53288

**Comment by katmoon** [comment]
Hi @stasleo 

I cannot reproduce the issue.
I've created a catalog rule with condition 'SKU contains 01' on sample data and it matches and applies the discount to the expected products.

Can you reproduce the issue? If yes, please provide more detailed [steps](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) on how you create the rule.

Thanks,
Kateryna.

**Comment by tkacheva** [comment]
Contains condition works as expected on my side as well
If you still have the issue, reopen the ticket with reference to Magento version you use
 ![contain_operator](https://cloud.githubusercontent.com/assets/5603216/15930765/4e1c49ec-2e5d-11e6-9846-9393de10ad75.png)
