### ISSUE TITLE
\Magento\Framework\Mail\MailMessageInterface missing setFromAddress

### ISSUE THREAD

**Issue by dbsdsun** [magento/magento2#24250]
### Preconditions (*)
1. Magento 2.3.2 & 2.3-develop

### Steps to reproduce (*)
1. \Magento\Framework\Mail\MailMessageInterface missing setFromAddress()
public function setFromAddress($fromAddress, $fromName = null);
2. in \Magento\Framework\Mail\Message
setFrom($fromAddress) is deprecated, and setFromAddress is introduced.
but in the \Magento\Framework\Mail\MailMessageInterface, setFromAddress is not defined.

### Expected result (*)
1. setFromAddress() is defined in the \Magento\Framework\Mail\MailMessageInterface

### Actual result (*)
1.  setFromAddress() is not defined in the \Magento\Framework\Mail\MailMessageInterface
---------------------------------------------------------------
    /**
     * @inheritdoc
     *
     * @deprecated 102.0.1 This function is missing the from name. The
     * setFromAddress() function sets both from address and from name.
     * @see setFromAddress()
     */
    public function setFrom($fromAddress)
    {
        $this->setFromAddress($fromAddress, null);
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function setFromAddress($fromAddress, $fromName = null)
    {
        $this->zendMessage->setFrom($fromAddress, $fromName);
        return $this;
    }

### Proposed solution (*)
define setFromAddress as following in the \Magento\Framework\Mail\MailMessageInterface
public function setFromAddress($fromAddress, $fromName);

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19598` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
Looks like related to https://github.com/magento/architecture/pull/144
/CC @melnikovi

**Comment by melnikovi** [comment]
@dbsdsun please use `Magento\Framework\Mail\EmailMessageInterface` instead.

**Comment by dbsdsun** [comment]
> @dbsdsun please use `Magento\Framework\Mail\EmailMessageInterface` instead.

In Magento 2.3.2, `Magento\Framework\Mail\EmailMessageInterface` doesn't exist. Where is it?

**Comment by melnikovi** [comment]
It will be available in 2.3.3 which will be released soon. Sorry, was under impression that it has been released.

**Comment by dmytro-ch** [comment]
Closing the current issue, considering it is not relevant since the refactoring of `MailAddress` and `MailAddressConverter` design has been provided:
- 3a90a0f61e953c8b943b8242525e77477cee8455
- 7fd2dc8581ac1722ed5f51671d12a8bc50a63aa2
- 3aabe1926b5b2555200118b73a432ac0c68f9b93

Thank you!
