### ISSUE TITLE
Programmatically add image to product with flag move true

### ISSUE THREAD

**Issue by magedevel** [magento/magento2#24256]
### Preconditions (*)

1. Magento versione 2.3.2
2. Php version 7.2
3. Nginx Env using Valet +

### Steps to reproduce (*)

1. Add an image on var/import/imagetest.jpg 
2. Try to create a product and add photo using method addImage of class Magento\Catalog\Model\Product\Gallery. As parameter add move = true. 

### Expected result (*)

1. Images added to product

### Actual result (*)

1. Image not found

The problem is on this pieace of code:
`try {
            /** @var $storageHelper \Magento\MediaStorage\Helper\File\Storage\Database */
            $storageHelper = $this->fileStorageDb;
            if ($move) {
                $this->mediaDirectory->renameFile($file, $destinationFile);
                //If this is used, filesystem should be configured properly
                $storageHelper->saveFile($this->mediaConfig->getTmpMediaShortUrl($fileName));
            } else {
                $this->mediaDirectory->copyFile($file, $destinationFile);
                $storageHelper->saveFile($this->mediaConfig->getTmpMediaShortUrl($fileName));
            }
        } catch (\Exception $e) {
            throw new LocalizedException(__('The "%1" file couldn\'t be moved.', $e->getMessage()));
        }`
if we move, the file is moved. After this part of code at line 200 we have:
`$fileName = str_replace('\\', '/', $fileName);

        $attrCode = $this->getAttribute()->getAttributeCode();
        $mediaGalleryData = $product->getData($attrCode);
        $position = 0;

        $absoluteFilePath = $this->mediaDirectory->getAbsolutePath($file);
        $imageMimeType = $this->mime->getMimeType($absoluteFilePath);
        $imageContent = $this->mediaDirectory->readFile($absoluteFilePath);
        $imageBase64 = base64_encode($imageContent);
        $imageName = $pathinfo['filename'];`

**Comment by magedevel** [comment]
I have checked the file now and it seems correct. You can close the issue.

**Comment by Leandry** [comment]
Thank you @magedevel for the update. I will close the issue
