### ISSUE TITLE
URL key/SEO friendly URL not used for products when in single-store mode

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#24259]
### Preconditions (*)

1. Magento v2.3.2
2. Single-store Mode (Stores > Configuration > General > Single-Store Mode)

### Steps to reproduce (*)

1. Add product to site using /V1/products (catalogProductRepositoryV1) via swagger
2. Example JSON:
`{
  "product": {
	  "sku": "TestApi",
	  "name": " API Test",
	  "attribute_set_id": 4,
	  "price": 0.75,
	  "status": 1,
	  "visibility": 4,
	  "type_id": "simple",
	  "created_at": "2019-07-23 16:25:27",
	  "updated_at": "2019-07-23 16:25:27",
	  "extension_attributes": {
		"website_ids": [
		  1
		],
		"stock_item": {
		  "qty": 99999,
		  "is_in_stock": true,
		  "use_config_min_qty": true,
		  "min_qty": 0,
		  "use_config_min_sale_qty": 1,
		  "min_sale_qty": 1,
		  "use_config_max_sale_qty": true,
		  "max_sale_qty": 10000,
		  "use_config_backorders": false,
		  "backorders": 0,
		  "use_config_notify_stock_qty": true,
		  "notify_stock_qty": 1,
		  "use_config_qty_increments": true,
		  "qty_increments": 0,
		  "use_config_enable_qty_inc": true,
		  "enable_qty_increments": false,
		  "use_config_manage_stock": true,
		  "manage_stock": true
		}
	  }
	}
}`
3. Search for product on frontend of site
4. Click product and review URL used

### Expected result (*)

1. URL key is generated for product based on product name.
In admin:
![image](https://user-images.githubusercontent.com/49071342/63605882-c15ffa80-c5c6-11e9-91c8-96c451fe21b3.png)

On Frontend:
![image](https://user-images.githubusercontent.com/49071342/63605910-d472ca80-c5c6-11e9-9ba9-ccbcdfcbd64d.png)

### Actual result (*)

1. URL key is correctly generated and appears in admin
![image](https://user-images.githubusercontent.com/49071342/63605882-c15ffa80-c5c6-11e9-91c8-96c451fe21b3.png)

2. On frontend the URL key is not used and instead the fallback is to use entity_id
![image](https://user-images.githubusercontent.com/49071342/63606004-071cc300-c5c7-11e9-8797-88e7bcb583dd.png)

**Comment by itmsenior** [comment]
Confirmed on 2.3-develop instance

**Comment by itmsenior** [comment]
Hi @engcom-Bravo 
This doesn't look to be specifically caused by the API. Adding an item in the Magento admin appears to have the same effect.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19667` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-24259-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24259-2-3-develop.instances.magento-community.engineering/admin](https://i-24259-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
@itwebdev2 @engcom-Bravo , i have followed the same steps, i am not able to reproduce this issue:
1. https://prnt.sc/p2zb2m 
2. http://i.prntscr.com/Ftts5I6_R8_pQZlp4o9DtA.png
3. http://i.prntscr.com/NFLBIhEVSc2LYcEH5ekh5g.png

Please check again, and reopen this issue again.
Thanks

**Comment by engcom-Bravo** [comment]
@maheshWebkul721 if You want to reproduce the issue take a fresh vanilla install of Magento and just follow steps to reproduce. You may add the product via admin. Do not create categories at all. Here is what I've got for an instance just has been cloned from GitHub 2.3-develop version and installed.
![wrongurl](https://user-images.githubusercontent.com/51680745/64608925-66a30d00-d3d4-11e9-80d7-77f90693d840.gif)

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20085` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by corbett3289** [comment]
Also experiencing this issue.

**Comment by MaxSouza** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MaxSouza. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MaxSouza, here is your [Magento instance](https://i-24259-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24259-2-3-develop.instances.magento-community.engineering/admin](https://i-24259-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, @oscarsanch. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-20085` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by itmsenior** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-24259-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24259-2-3-develop.instances.magento-community.engineering/admin](https://i-24259-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
