### ISSUE TITLE
bin/magento sampledata:deploy fails

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#2425]
Hi,

if I run `bin/magento sampledata:deploy` I get the following error:

```
  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate
```

After running `composer update` and `bin/magento setup:install ... --use-sample-data` the sample data are available. My login credentials are already stored in `auth.json`.

**Comment by woei66** [comment]
token may be expired
visit https://github.com/settings/tokens to update your token and update your auth.json

then, try below steps:
rm -rf var/
bin/magento setup:upgrade
bin/magento sampledata:deploy
bin/magento setup:static-content:deploy

**Comment by marvincaspar** [comment]
Token is valid and an installation without sample data workd fine. Only the `bin/magento sampledata:deploy` command fails.

**Comment by davidalger** [comment]
This is a known issue in the sampledata:deploy command which has been addressed and delivered to the develop mainline in 764d75a7b. The workaround specified is documented on devdocs. Closing.

**Comment by ci2014** [comment]
The workaround "composer update" is not working for me. It is not asking for auth data, as mentioned in the devdocs.

Link to the devdocs for deploying sample data: http://devdocs.magento.com/guides/v2.0/install-gde/install/sample-data-after-magento.html

**Comment by mazhalai** [comment]
@ci2014 please do not comment on closed issues. If you have the latest code, auth data is not required anymore.

**Comment by grichards** [comment]
Sorry to leave a comment on a closed issue... don't know where else to leave it, but I echo @ci2014's comments... running composer update does not ask for auth... and a fresh install of mag2 via composer still gives me this error trying to deploy sample data.

**Comment by mazhalai** [comment]
@grichards please start a new thread, with what exactly you tired and what didnt work?

**Comment by MorganGonzales** [comment]
Solution: https://github.com/magento/magento2/issues/2523
