### ISSUE TITLE
[TEST] #cd19latam

### ISSUE THREAD

**Issue by slavvka** [magento/magento2#24260]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by slavvka** [comment]
#cd19latam

**Comment by slavvka** [comment]
@magento I am working on it

**Comment by slavvka** [comment]
#cd19latam

**Comment by slavvka** [comment]
@magento I am working on it

**Comment by jnando91** [comment]
#cd19latam
