### ISSUE TITLE
Unable to set unique «name» attribute values for the HTML inputs generated by the \Magento\Framework\Data\Form\Element\Checkboxes class

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2426]

**Comment by shiftedreality** [comment]
Hi @dfediuk 

Thank you for reporting. I think we will need to extend base method getName() in AsbstractElement class with optional paramter .

Internal issue MAGETWO-47893 created

**Comment by orlangur** [comment]
@dmitry-fedyuk thanks for the suggestion!

Such feature does not seem to be useful in core and desired behavior can be easily achieved with custom implementation.  However, if you prepare a pull request I believe there is a high chance it could be merged.
