### ISSUE TITLE
Magento 2.3.2 Design configurations empty

### ISSUE THREAD

**Issue by radua** [magento/magento2#24261]
### Preconditions (*)

1. Magento version : 2.3.2

### Steps to reproduce (*)

1. Backend > Content > Design Configuration

### Expected result (*)

1. Should show a list of scopes - Global, All Websites and Stores

### Actual result (*)

1. Shows : No records found

**Comment by engcom-Bravo** [comment]
Hello @radua. Thanks for applying. Are we doing below something wrong?
![design](https://user-images.githubusercontent.com/51680745/63607003-178a6900-c5da-11e9-9da9-b3da92098bc4.gif)
Seems there everything works as expected. Or should there be something else?

**Comment by radua** [comment]
Hi @engcom-Bravo : Thanks for the prompt response. I get this
![image](https://user-images.githubusercontent.com/14368934/63607848-78497f80-c5a1-11e9-86b0-ac0797a4fbcb.png)

**Comment by engcom-Bravo** [comment]
@radua, seems Your magento instance is far from the vanilla one. Could You please try to reproduce Your issue on a clear instance containing only native code as You are advised above:
![Advised](https://user-images.githubusercontent.com/51680745/63609196-5242d000-c5df-11e9-88bc-dd8f0f3c9f20.png)
Thank You.

**Comment by radua** [comment]
I am working with the community edition release that I installed using composer. Is that the same as the vanilla release? Since I'm running community edition in production, I tested on this.

`composer create-project --repository=https://repo.magento.com/ magento/project-community-edition mageTest`

That's the command I had used. I will still verify it on vanilla. How can I install a vanilla instance?

**Comment by toddbc** [comment]
I think I've seen something like this before when mod_pagespeed or Cloudflare was stripping HTML comments.  Magento won't work if that's happening.
