### ISSUE TITLE
Magento 2.3-delop Create new address phone number validation doesn't work

### ISSUE THREAD

**Issue by irving0mar** [magento/magento2#24269]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Login as customer
2. Create a new address in customer account area
3. Without filling the Phone Number field click send

### Expected result (*)

1. 
![image](https://user-images.githubusercontent.com/25356743/63622042-32011a00-c5bb-11e9-89ea-69b3a33c590b.png)

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/25356743/63622097-51984280-c5bb-11e9-8c79-0ab249f4234a.png)

**Comment by irving0mar** [comment]
#cd19latam

**Comment by irving0mar** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irving0mar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irving0mar, here is your [Magento instance](https://i-24269-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24269-2-3-develop.instances.magento-community.engineering/admin](https://i-24269-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by irving0mar** [comment]
Couldn't reproduce this issue on vanilla instance
