### ISSUE TITLE
Click on "enter YouTube API Key" sends you off the product edit page

### ISSUE THREAD

**Issue by simbus82** [magento/magento2#2427]
Magento 2 stable.

If i'm editing a new product and go to "add video", if i have not entered a YouTube API Key, when i click this link, magento load the configuration page and i lose all data entered in the new product.

This link need to:
- open in a news windows/tab
  or
- notify that i'm leaving a not saved products
  or
- save product that i'm editing and go to configuration page.

Thanks

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Click-on-quot-enter-YouTube-API-Key-quot-sends-you-off-the/idi-p/45778).
