### ISSUE TITLE
Discount restricted by payment method is still applying.

### ISSUE THREAD

**Issue by ysapoodle** [magento/magento2#24275]
### Preconditions (*)

1. Magento 2.2.5
2. Standard Checkout 

### Steps to reproduce (*)

1. Create a Cart Discount Code for example 5% off everything
2. If ANY  of these conditions are TRUE : Payment Method  is not  "Imegamedia Finance Gateway " (so should only apply to other payment methods, no discount for finance gateway)

### Expected result (*)

Entering the code into the checkout shows correctly, if i select paypal then the 5% discount is visible and correct, if i select finance then the 5% discount dissapears.

Clicking Place order should process the order with the discount shown. Either 5% for credit card or 5% for paypal or no discount for finance.

### Actual result (*)

When order is placed 5% is applied to ALL payment methods including discounted one. 

I have also tried this using only standard magento paypal express methods to illiminate the finance module.

If i switch it around so 

if ANY  of these conditions are TRUE : Payment Method  is "Paypal Express Checkout"

The error is "coupon code is not valid."

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24275-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24275-2-3-develop.instances.magento-community.engineering/admin](https://i-24275-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19632` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gixid192** [comment]
This issue has been fixed in Magento 2.3.5, here is the commit: https://github.com/magento/magento2/commit/dac83def7ac97a184fe5f3cad77116b2b2221015#diff-62a9eb70c523c6139f365640935a809fe043aed799010defb94d6a36491f4fc4

I checked and none of Magento which is less than 2.3.5 has this fix. So you may need to implement it yourself. Or upgrade to new Magento

**Comment by magento-engcom-team** [comment]
Hi @ysapoodle, @engcom-Kilo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24004` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @ysapoodle. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24004` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
