### ISSUE TITLE
Magento 2.3.2 Products In Category Issue with varnish cache

### ISSUE THREAD

**Issue by hiepecom** [magento/magento2#24287]
### Preconditions (*)

1. magento2.3.2 with sample data
2. Varnish 5

### Steps to reproduce (*)
1. Install fresh magento 2.3.2 with sample data
2. Config Varnish Cache following https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-configure.html
3. Go to Admin -> Catalog -> Categories
4. In Default Category, Click Products In Category
5.a Do not click "Reset Filter" -> Click next page -> It's working correctly
5.b Click "Reset Filter" -> Click next page -> Check the response request from Inspect -> It show page 2 -> But Still return Page 1, If Click "Reset Filter" again -> It's working and show page 2 correctly

### Expected result (*)
1. 5.b should work correctly with varnish as 5.a

### Actual result (*)
1. 5.b not working

I have made some debugging and These are what I found out
1. Before Clicking "Reset Filter" and clicking next page
![image](https://user-images.githubusercontent.com/19380309/63671354-839ee400-c809-11e9-9e3a-aec58a05e943.png)

2. After Clicking "Reset Filter" and then Clicking next page
![image](https://user-images.githubusercontent.com/19380309/63671404-9d402b80-c809-11e9-942f-d831d28df6ca.png)

The Request still goes to page 3, but the output is still page 1

3. After Step 2. , Click "Reset Filter again"
![image](https://user-images.githubusercontent.com/19380309/63671470-bb0d9080-c809-11e9-8175-1455e495dcd6.png)

**Conclusion:**
- Varnish cache not working if request url is
admin/catalog/category/grid/key/14cb81ddaf76769139e9fcac86021911db3b5f93b5be17c6b3e8955328d74a62/id/2/filter//page/3/?ajax=true&isAjax=true

- But it is working if request url is slightly changed:
admin/catalog/category/grid/key/14cb81ddaf76769139e9fcac86021911db3b5f93b5be17c6b3e8955328d74a62/id/2/page/3/filter//?ajax=true&isAjax=true

Please help or at least provide workaround

**Comment by hiepecom** [comment]
looking deeper into the issue: The root cause was filter param was missing a slash "/" when pass to varnish

admin/catalog/category/grid/key/14cb81ddaf76769139e9fcac86021911db3b5f93b5be17c6b3e8955328d74a62/id/2/**filter//**page/3/?ajax=true&isAjax=true

was become:
admin/catalog/category/grid/key/14cb81ddaf76769139e9fcac86021911db3b5f93b5be17c6b3e8955328d74a62/id/2/**filter/**page/3/?ajax=true&isAjax=true

So param filter instead of "" , now take page as value, then param page was not found

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19694` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hiepecom** [comment]
It has been a while, is this issue is fixed or do we have any workarounds?

**Comment by magento-engcom-team** [comment]
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Comment by magento-engcom-team** [comment]
Hi @hiepecom. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24014` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by nilesh-gosai-born** [comment]
Hello Team,
I am facing same issue on Magento 2.4.3
if this is fixed then any one can give the files which has been changed to fix this issue.
