### ISSUE TITLE
Inventory reservation list inconsistencies command does not work

### ISSUE THREAD

**Issue by arvind-curotec** [magento/magento2#24297]
The command to list inconsistencies never completes in Magento 2.3.2.
Database size: ~15GB
Order Count: ~1137711 
SKU Count: 7788

### Preconditions (*)

1. Migrated from Magento 1.9.4 to Magento 2.3.1
2. Upgraded from Magento 2.3.1 to Magento 2.3.2
3. Migration from 1.9 to 2.3 caused inventory inconsistencies as listed here - https://devdocs.magento.com/guides/v2.3/inventory/inventory-cli-reference.html

### Steps to reproduce (*)

1. Upgrade from 2.3.1  to 2.3.2
2. Run the command to list inventory inconsistencies `php -d memory_limit=-1 bin/magento inventory:reservation:list-inconsistencies -ir`

### Expected result (*)

1. It should list the inconsistent inventories for effected SKUs

### Actual result (*)

1. The command keeps running forever and does not yield any result. It takes up all the server memory and still no result.
2. In our case, it takes more than 20GB of memory and still not finished. here is screenshot from our server:
![image](https://user-images.githubusercontent.com/53758829/63712216-dfde2400-c85a-11e9-85ab-c32ff101068a.png)

**Comment by engcom-Bravo** [comment]
Hi @arvind-curotec. The problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository. Please reopen the issue there. Thank You.

**Comment by arvind-curotec** [comment]
@engcom-Bravo The issue is not with data migration. We did data migration 6 months back and site is running smoothly after that. Issue started after the upgrade to 2.3.2.
Please do no close issues just to clear your backlog. It's a genuine problem and you should look into it.

**Comment by jefflenz** [comment]
Same issue, much smaller database, scripts been running for hours and eating massive amounts of memory.  Magento 2.3.2-p2 Enterprise
