### ISSUE TITLE
Magento 2 community rest api

### ISSUE THREAD

**Issue by MrYogi** [magento/magento2#2429]
is magento 2 community rest api support full functionality to develop a complete customer app for my store? there is any sdk available for same? any sample or mobile client available? any help will be appriciated

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by MrYogi** [comment]
already asked long ago there:
https://community.magento.com/t5/Installing-Magento-2/is-mobile-sdk-for-android-and-ios-availble-with-magento-2/m-p/18343#U18343
but no response from anyone, i hope any one will be more interested in guiding me instead of just pointing places where to ask my issue, thanks

**Comment by alankent** [comment]
The Magento 2 REST API is the recommended way to connect applications to Magento 2. If you go to http://devdocs.magento.com and look under "developers" you will find the REST documentation, including the recommended way to authenticate from mobile apps. Magento 2 does not have a SDK - it exposes extensive REST APIs instead. If you have any more questions, feel free to ask over in the "just ask Alan" section of the forums.

**Comment by famousTM** [comment]
What does that mean it using extensive REST APIs instead? Are you saying it won't have an SDK, so all app code will need to be built by the user?

Thanks

**Comment by ilol** [comment]
@famousTM Yes, Magento2 hasn`t SDK for mobile app but has the iOS sample app as a part of Enterprise Edition. If you have license you can download it.

**Comment by famousTM** [comment]
But does that iOS sample app work with Magento 2.0. And is it modifiable?

Thanks

On Friday, March 18, 2016, Illia Oliinyk notifications@github.com wrote:

> @famousTM
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_famousTM&d=CwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Xo9IOOXaHMcm-vxQ8NpoJ-69RrC_va-S3eYlGDiWkZo&m=Jf9B8I5eIAhMDCBgrXWzexx45YfZ-YdqA9bjixOKMK8&s=rwXPZNsUZAAeu__Tu0PFa9T3R9HvxdXu_ZQhfxYwzhk&e=
> Yes, Magento2 hasn`t SDK for mobile app but has the iOS sample app as a
> part of Enterprise Edition. If you have license you can download it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magento_magento2_issues_2429-23issuecomment-2D198373405&d=CwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Xo9IOOXaHMcm-vxQ8NpoJ-69RrC_va-S3eYlGDiWkZo&m=Jf9B8I5eIAhMDCBgrXWzexx45YfZ-YdqA9bjixOKMK8&s=waRJIgbAUkFuoXVWhCSxkysBvHrHsAGcxXL59jDood4&e=

## 

Ruben Ramirez
_famous@alumni.usc.edu famous@alumni.usc.edu_
562.556.5556

**Comment by ilol** [comment]
Yes, it is open sourced.

**Comment by famousTM** [comment]
Thank you for your help

On Mon, Mar 21, 2016 at 2:02 AM, Illia Oliinyk notifications@github.com
wrote:

> Yes, it is open sourced.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magento_magento2_issues_2429-23issuecomment-2D199182549&d=CwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Xo9IOOXaHMcm-vxQ8NpoJ-69RrC_va-S3eYlGDiWkZo&m=lphViot4f60-V_q5ntKi9iBB2gDRW4eMSnqBieCVZYI&s=s-5BpG8ZFdZTF8lYUSgbS-G2LJopexuJec0zMR4LiuA&e=

## 

Ruben Ramirez
_famous@alumni.usc.edu famous@alumni.usc.edu_
562.556.5556

**Comment by ipragmatechadmin** [comment]
yes Magento2 provide most of the APIs required to develop mobile app. There are a couple of APIs related to payments and my orders are missing but that can be developed easily. If you are looking for readily available solution then take a look at our app http://www.ipragmatech.com/products/android-magento-mobile-app/. Feel free to contact us if you have any question.

**Comment by Davidmichael4u** [comment]
Magento - one among the top 3 most preferred eCommerce development platform offers a new REST API that is compatible with its latest Magento 2.0 version. https://magento.uservoice.com/forums/72699-magento-mobile/suggestions/17099923-magento-rest-api-for-magento-2-mobile-app
