### ISSUE TITLE
Arabic language csv upload error

### ISSUE THREAD

**Issue by ashrabq** [magento/magento2#24298]
hello am trying to import products from csv file to but it gives an error and says the file should be in UTF-8. what i know that Arabic letters are included in utf-8 so why it gives such error and how to fix it

**Comment by engcom-Bravo** [comment]
Hello @ashrabq, thanks for applying. Please watch this gif below:
![arabic](https://user-images.githubusercontent.com/51680745/63776963-ffbd2880-c8ea-11e9-9b63-cadf41c60e1a.gif)
As You can see we have successfully imported a product with arabic Name and SKU. Have we missed something or done something wrong?

**Comment by ashrabq** [comment]
thank you all but i tried same csv file when it is all English it uploads correctly and when i just add  Arabic word it gives this error

@magento give me 2.3-develop instanc
@engcom-Bravo 
look at image

![Untitled](https://user-images.githubusercontent.com/47795342/63784698-b6bfa100-c8f7-11e9-8a8e-764be4ad54e4.png)

**Comment by ashrabq** [comment]
> Hello @ashrabq, thanks for applying. Please watch this gif below:
> ![arabic](https://user-images.githubusercontent.com/51680745/63776963-ffbd2880-c8ea-11e9-9b63-cadf41c60e1a.gif)
> As You can see we have successfully imported a product with arabic Name and SKU. Have we missed something or done something wrong?

**Comment by engcom-Bravo** [comment]
@ashrabq, of course as You've said Arabic letters are included in utf-8. I think there's a problem with Your CSV  file - it contains information that it is saved not in UTF-8 but in some other coding system. Maybe this link will help You to save Your CSV file [as UTF-8](https://www.webtoffee.com/how-to-save-csv-excel-file-as-utf-8-encoded/#save-csv-libre-office).

**Comment by ashrabq** [comment]
Thank you Dear @engcom-Bravo the link helped I Opend it with Officelibre and I checked on format quoted field as a text and when saving it I should save it and confirm "use csv file format"
