### ISSUE TITLE
After upgrade to Magento 2.3.2 product image are changing to my logo

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#24299]
**Preconditions (*)**

Magento 2.3.2

**Steps to reproduce (*)**

 Upgrade to ver 2.3.2 
then navigate to my product.

Expected result (*)

To show product image.

**Actual result (*)**

Some of the image in the products are changing to a weird image of my logo.

![image_issue_bad](https://user-images.githubusercontent.com/33385380/63734570-c6cd7700-c84a-11e9-93fa-a089841dabaf.PNG)

**Comment by testmagento2** [comment]
The issue was with image type. 
Image with gif type wasn't good.
When change it to jpeg the image show.

Any idea why?

**Comment by engcom-Charlie** [comment]
Hello @testmagento2 
Can you provide more info(screenshots and steps) please?

**Comment by engcom-Charlie** [comment]
Hello @testmagento2 
I am closing this issue now due to inactivity.
Please update if you wish to continue.
Thank you for the collaboration!
