### ISSUE TITLE
After M1 -> M2 data migration cannot save url keys of products with same name.

### ISSUE THREAD

**Issue by zb** [magento/magento2#24301]
My client duplicated products in M1 - they sell high-end products one at a time. These products often have the same name. 

After data migration, products with the same name do not have URL keys(only the product with lowest id does).

If product with name of "asdf" with id of 1 is saved and has a url key, product with name of "asdf" with id of 99 has no url key and cannot be saved.

Can correct by attempting to import and being provided links to every single url key that must be changed.

Going to provide client with list of skus with duplicate products for manual correction. Popular URL Key generation utilities did not fix. 

Is a real bug. Will not duplicate on vanilla because is post-import.

I assume is due to a key constraint. 

2.3.2 did not fix. 

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by engcom-Bravo** [comment]
Hi @zb. The problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository. So please reopen Your issue there. Thank You.
