### ISSUE TITLE
Edit configurable product from cart doesn't show selected swatch options

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24306]
### Preconditions (*)

1. Magento 2.3.2
2. Php 7.2.19

### Steps to reproduce (*)

1. create a configurable product with more than one swatch attribute
2. add product to cart
3. then edit the same from cart

### Expected result (*)

![config1](https://user-images.githubusercontent.com/44425160/63743688-b1903100-c8ba-11e9-8d19-a838ed1added.png)

### Actual result (*)

![issue](https://user-images.githubusercontent.com/44425160/63743698-b9e86c00-c8ba-11e9-97ee-7262c8edeca9.png)

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24306-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24306-2-3-develop.instances.magento-community.engineering/admin](https://i-24306-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19656` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24308 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [b6f2b5cb0a35ade677fb281b488882edd4fc783e](https://github.com/magento/magento2/commit/b6f2b5cb0a35ade677fb281b488882edd4fc783e)

The fix will be available with the upcoming 2.3.4 release.
