### ISSUE TITLE
New Review form is redirected to review grid

### ISSUE THREAD

**Issue by konarshankar07** [magento/magento2#24310]
### Preconditions (*)

1.magento 2.3-develop
2.Magento instance doesn't have any products

### Steps to reproduce (*)

1. Go to Admin
2. Marketing -> All Reviews -> New Review
3. Click on add new review

### Expected result (*)

Add review button should not be visible in the grid

### Actual result (*)

![image](https://user-images.githubusercontent.com/39480008/63744184-32036180-c8bc-11e9-9dde-65591eed1da1.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24310-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24310-2-3-develop.instances.magento-community.engineering/admin](https://i-24310-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
In New Review section, User can't add the review, After loading the page. It is redirected to the Review list page.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19657` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajijshekh123** [comment]
See attached the Issue video:

![AwesomeScreenshot-2019-8-27-1566885470864](https://user-images.githubusercontent.com/24711761/63744963-90c9da80-c8be-11e9-83ea-9d32843fca08.gif)

**Comment by shikhamis11** [comment]
@ajijshekh123 @konarshankar07  for creating review you need to select product first 
if product is available in grid process seems working fine

**Comment by sudheers-kensium** [comment]
Hi @konarshankar07, I think you don't have any products in your instance, without products we can't create reviews. Please create products and try again, then you will be able to create reviews.

**Comment by ajijshekh123** [comment]
I know @shikhamis11 and @sudheers-kensium, But on loading time it should not display default add review UI. If products are not available on your Magento instance, It should display some static message so admin can understand why it is not open.

**Comment by adarshkhatri** [comment]
> See attached the Issue video:
> 
> ![AwesomeScreenshot-2019-8-27-1566885470864](https://user-images.githubusercontent.com/24711761/63744963-90c9da80-c8be-11e9-83ea-9d32843fca08.gif)

You must have products in order to add review.

**Comment by adarshkhatri** [comment]
@magento give me 2.3

**Comment by adarshkhatri** [comment]
@magento give me 2.3 instance

**Comment by adarshkhatri** [comment]
@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri, here is your [Magento instance](https://i-24310-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-24310-2-3-0.instances.magento-community.engineering/admin](https://i-24310-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by konarshankar07** [comment]
Hello @shikhamis11  and @sudheers-kensium ,
I agree with @ajijshekh123 . The button should not be visible if there are no products in the instance

**Comment by konarshankar07** [comment]
I'll update the precondition so everyone can easily understand the current issue

**Comment by konarshankar07** [comment]
Even with adding product. I'm not able to view the add review form in magento admin. I think admin should not able to add the review
https://www.loom.com/share/35d37ad6d1524265bcc25d3c83aefb51

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your report. 
The issue has been fixed in magento/magento2#24399 by @edenduong in 2.3-develop branch
Related commit(s):
 - [38cf8d61b3cca8d7e522f92601feccafbb0107b6](https://github.com/magento/magento2/commit/38cf8d61b3cca8d7e522f92601feccafbb0107b6)

The fix will be available with the upcoming 2.3.4 release.
