### ISSUE TITLE
Store Configuration Currency Setup Connection Timeout in Seconds field have not proper validation

### ISSUE THREAD

**Issue by kirtinariya1** [magento/magento2#24315]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

Store configuration in the `General` `Currency Setup` have `Fixer.io` and `Currency Converter API` have a field `Connection Timeout in Seconds` that field have not proper numeric validation. Issue is that field taking any of the value. There should be take proper validation.

Login to the Magento 2 admin.
Go to the STORES >> Settings >> Configuration >> GENERAL >> Currency Setup >> Fixer.io  and Currency Converter API`

Connection Timeout in Seconds: add any text value
Save Config

### Expected result (*)

1. There should be allow only digit.
2.
![Expected-Result-CurrencySetup](https://user-images.githubusercontent.com/28681937/63763144-c338ff00-c8e1-11e9-9cd8-999b79322e9b.png)

### Actual result (*)

1. There is a taking all the value like text and string as well. Validation is missing
2. 
![Actual-Result-CurrencySetup](https://user-images.githubusercontent.com/28681937/63763154-c8964980-c8e1-11e9-9f92-8d40e50bc092.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24315-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24315-2-3-develop.instances.magento-community.engineering/admin](https://i-24315-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@kirtinariya1 - This issue is relevant to #24204, That's why I am closing this issue.
