### ISSUE TITLE
Much time taken for installing and running site

### ISSUE THREAD

**Issue by devloperhimanshu** [magento/magento2#2431]
Magento 2 tacks much time more than older magento version for installing new with sample data and also much time to run on front even if beck end side.
I try with run on local wamp server.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [Installing Magento 2](https://community.magento.com/t5/Installing-Magento-2/bd-p/installing-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
