### ISSUE TITLE
translation data load after price-box.js

### ISSUE THREAD

**Issue by ameshca** [magento/magento2#24316]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Override the price-box.js like following method : app/design/frontend/vendor/package/Magento_Catalog/web/js/price-box.js
2. Included the 'mage/translate' inside the dependency
3. Edited the 'priceTemplate' variable default value and added a 'Price' text before the price like below
` priceTemplate: '<span class="price-label custom-label">' + $t('Price') + '</span><span class="price"><%- data.formatted %></span>'`
4. Translations added for the 'Price' text

### Expected result (*)

1. Translation should work

### Actual result (*)

1. Translation is not properly working

I have edited the lib/web/mage/translate.js file for debugging and when i checked, there is no data is populated inside the '_data' array at the time of price-box.js is loaded. So when it checked for a translation for the text 'Price' it will not found and return the same string. I found that this is because it causing a delay in the translation data population and at the time of requesting the translation for the 'Price' text, the data is not populated yet which cause translation not work. There is an issue already reported related to this https://github.com/magento/magento2/issues/7363. But in this its commented that it will fix in 2.2.0 version, but it still exist in 2.3 version

**Comment by ameshca** [comment]
#7363

**Comment by engcom-Charlie** [comment]
Hello @ameshca 
Can you add more steps to reproduce?
I find only one page where we use price-box.js, but there are no 'Price' word for translate.
![image](https://user-images.githubusercontent.com/51680850/63852354-c0511380-c9a0-11e9-9224-3dd6d693a129.png)

**Comment by ameshca** [comment]
@engcom-Charlie This is not a default one. I have overrided the js file price-box.js into theme and added the 'Price' label in the priceTemplate as i specified in the description.

**Comment by engcom-Charlie** [comment]
@ameshca and how to reproduce translation?

**Comment by engcom-Charlie** [comment]
Hello @ameshca 
 I am closing this issue now due to inactivity.
Please update if you wish to continue.
Thank you for the collaboration!
