### ISSUE TITLE
WYSIWYG editor incorrectly show (and save) quotes

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#24329]
### Preconditions (*)
1. Magento 2.3

### Steps to reproduce (*)
1. Go to BO -> Content -> Elements -> Blocks -> Add New Block
2. Fill:
Block Title -> Test
Identified -> Test
3. Press Show/Hide Editor. It should looks like:
![image](https://user-images.githubusercontent.com/9420807/63833955-e1077200-c97c-11e9-81cf-6fff53f3edde.png)
4. Pass the content to WYSIWYG editor:
`<p><a href="{{config path="web/unsecure/base_url"}}">T</a></p>`
5. Press 'Save'.
6. Check the WYSIWYG content.

### Expected result (*)
![image](https://user-images.githubusercontent.com/9420807/63834081-1ca23c00-c97d-11e9-884d-e96b18327321.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/9420807/63834169-583d0600-c97d-11e9-9f0b-ee0f17b7b24a.png)

### Additional
The problem that after second save the initial content in DB will be replaced with the content where all quotes have been escaped.
And this content will still be shown in editor in escaped variation.

The consequence of the problem in that you can not correctly use variables in CMS entities inside quotes (e.g. set variable as HTML attribute).

**Comment by swnsma** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swnsma, here is your [Magento instance](https://i-24329-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24329-2-3-develop.instances.magento-community.engineering/admin](https://i-24329-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
