### ISSUE TITLE
Magento\Framework\Filesystem\Driver\File isExists function not working with symlinks

### ISSUE THREAD

**Issue by luckyraul** [magento/magento2#2432]
For example if app/etc/env.php is symlinked - returns false

by #2423

**Comment by BlackIkeEagle** [comment]
@luckyraul maybe interesting to mention the OS ?

I have env.php symlinked on linux and my magento2 setup is just working fine.

Maybe there is need for some more context :)

**Comment by luckyraul** [comment]
it was dead symlink
