### ISSUE TITLE
Configurable Product Price $0.00 In Stock Alert Emails

### ISSUE THREAD

**Issue by twistedindustries** [magento/magento2#24325]
### Preconditions (*)

Magento 2.3.2, 2.3.1

### Steps to reproduce (*)

1.  Create product stock alert email for a configurable product
2.  Inside the email the configurable product's price is $0.00

### Expected result (*)

1. The correct price should show with the product i.e. $44.00

### Actual result (*)

![image](https://user-images.githubusercontent.com/5498323/63811615-cb427000-c8dc-11e9-89df-5863677e01a0.png)

I tracked this down to website id being set to 0 in the query that happens on line 71 in Magento\ConfigurableProduct\Pricing\Price\LowestPriceOptionsProvider

**Comment by mahesh-rajawat** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-24325-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24325-2-3-develop.instances.magento-community.engineering/admin](https://i-24325-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19724` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @twistedindustries. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24021` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
