### ISSUE TITLE
indexer.xml & mview.xml doesn't allow numbers in vendor name and class name

### ISSUE THREAD

**Issue by Jason-Sy** [magento/magento2#24323]
This issue is similar to [#4470](https://github.com/magento/magento2/issues/4470)
### Preconditions (*)

1. Magento 2.3.0/1
2. PHP 7.2

### Steps to reproduce (*)

1. Create a simple module with a vendor name which contains at least one number (ex. Mage2Vendor) 
2. Add a custom indexer to the module just like on [the devdocs](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexing-custom.html)
```
<indexer id="mage2module_url_rewrites" view_id="mage2module_url_rewrites" class="Mage2Vendor\Module\Model\Indexer\UrlRewrites">
  <title translate="true">Title.</title>
  <description translate="true">Description.</description>
</indexer>
```
3. setup:upgrade

### Expected result (*)

1. Normal Upgrade output & module gets properly installed.

### Actual result (*)

1. Console trows an error at running scheme:
```
Running schema recurring...The XML in file "/root/app/code/Mage2Vendor/Module/etc/indexer.xml" is invalid:
Element 'indexer', attribute 'class': [facet 'pattern'] The value 'Mage2Vendor\Module\Model\Indexer\UrlRewrites' is not accepted by the pattern '[a-zA-Z\\]+'.
Line: 3

Element 'indexer', attribute 'class': 'Mage2Vendor\Module\Model\Indexer\UrlRewrites' is not a valid value of the atomic type 'classType'.
Line: 3
```

### Note
If you bypass the first issue by editing `Magento/Framework/Indexer/etc/indexer.xsd`
the same issue happens with the mview.xml file.
```
Running data recurring...The XML in file "/root/app/code/Mage2Vendor/Module/etc/mview.xml" is invalid:
Element 'view', attribute 'class': [facet 'pattern'] The value 'Mage2Vendor\Module\Model\Indexer\UrlRewrites' is not accepted by the pattern '[a-zA-Z\\]+'.
Line: 3

Element 'view', attribute 'class': 'Mage2Vendor\Module\Model\Indexer\UrlRewrites' is not a valid value of the atomic type 'classType'.
Line: 3
```

**Comment by Jason-Sy** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Jason-Sy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jason-Sy, here is your [Magento instance](https://i-24323-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24323-2-3-develop.instances.magento-community.engineering/admin](https://i-24323-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jason-Sy** [comment]
> Hi @Jason-Sy. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [X]  Summary of the issue
> * [X]  Information on your environment
> * [X]  Steps to reproduce
> * [X]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @Jason-Sy do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [X]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

Tested on a vanilla magento 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @Jason-Sy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jason-Sy, here is your [Magento instance](https://i-24323-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24323-2-3-develop.instances.magento-community.engineering/admin](https://i-24323-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19692` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Can be closed ad fixed and delivered in https://github.com/magento/magento2/pull/24324

**Comment by Ksardarion** [comment]
@magento-engcom-team 
The same issue exists for table subscriptions in version 2.3.3
Do I need to create another one here, on the github?
