### ISSUE TITLE
"extra/map" nodes in composer.json files of Magento 2.0.0 modules (MAGETWO-42282)

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#2433]
Hello, guys.

I have found [commit](https://github.com/magento/magento2/commit/ffe77589e2555353556ad9590bf9aa1990937f0c) that has removed all "extra/map" nodes from "composer.json" files of the Magento modules:

```
{
    "extra": {
        "map": [
            [
                "*",
                "Magento/Authorization"
            ]
        ]
    }
}
```

New node was added (MAGETWO-42282):

```
{
    "autoload": {
        "files": [ "registration.php" ]
    }
}
```

The "extra/map" nodes are used by ["magento/magento-composer-installer"](https://github.com/magento/magento-composer-installer) to deploy Magento modules into Magento application structure (./app/code/...).

Does it mean that "magento/magento-composer-installer" will not be supported in the future?

Thanks,

Alex.

**Comment by kassner** [comment]
magento-composer-installer used the extra/map to copy files from `vendor/` to `app/code`. Now it's possible to modules live in `vendor/`, so no need to copy. `registration.php` is the file used by autoloader to know that there is a module in that folder.

**Comment by marvincaspar** [comment]
You don't need to put you modules to `app/code`. It is also possible to access each module from the `vendor` folder.

**Comment by flancer64** [comment]
There is an error in \Magento\Framework\Filesystem\Driver\File::getRelativePath that is appeared when files are in "vendor" folder that is not placed under root Magento 2 folder:

```
public function getRelativePath($basePath, $path = null)
{
    $path = $this->fixSeparator($path);
    if (strpos($path, $basePath) === 0 || $basePath == $path . '/') {
        $result = substr($path, strlen($basePath));
    } else {
        $result = $path;
    }
    return $result;
}
```

The relative path is failed when modules are placed in the "wrong" vendor folder:

![filestructure](http://i.imgur.com/Kboa7F6.png)

**Comment by davidalger** [comment]
@Vinai I believe you wrote that method on #1490. Perhaps you could chime in on this one?

**Comment by flancer64** [comment]
I have created sample M2 application with "[composer.json](https://github.com/flancer32/sample_mage2_module/blob/master/live/composer.json)". You can deploy sample:

```
$ git clone git@github.com:flancer32/sample_mage2_module.git
$ cd sample_mage2_module/live/
$ composer install
```

(please, ignore error message "Praxigento\Composer\Plugin\Templates\Main: Cannot open configuration file './templates.vars.json'. Plugin will be disabled.")

Then you can launch `./live/htdocs/bin/magento setup:install ...` to install database but web access to application will fail with error like:

```
a:4:{i:0;s:447:"Cannot read contents from file "/home/alex/work/github/sample_mage2_module/live/htdocs/home/alex/work/github/sample_mage2_module/live/vendor/magento/module-ui/view/base/ui_component/etc/definition.xml" Warning!file_get_contents(/home/alex/work/github/sample_mage2_module/live/htdocs/home/alex/work/github/sample_mage2_module/live/vendor/magento/module-ui/view/base/ui_component/etc/definition.xml): failed to open stream: No such file or directory";i:1;s:16360:"#0 /home/alex/work/github/sample_mage2_module/live/vendor/magento/framework/Filesystem/Directory/Read.php(207): Magento\Framework\Filesystem\Driver\File->fileGetContents('/home/alex/work...', NULL, NULL)
#1 /home/alex/work/github/sample_mage2_module/live/vendor/magento/framework/View/Element/UiComponent/Config/FileCollector/AggregatedFileCollector.php(81): Magento\Framework\Filesystem\Directory\Read->readFile('/home/alex/work...')
#2 /home/alex/work/github/sample_mage2_module/live/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(47): Magento\Framework\View\Element\UiComponent\Config\FileCollector\AggregatedFileCollector->collectFiles()
#3 /home/alex/work/github/sample_mage2_module/live/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(101): Magento\Framework\View\Element\UiComponent\Config\Reader->__construct(Object(Magento\Framework\View\Element\UiComponent\Config\FileCollector\AggregatedFileCollector), Object(Magento\Framework\View\Element\UiComponent\Config\Converter), Object(Magento\Framework\View\Element\UiComponent\Config\DomMerger))
...
#67 /home/alex/work/github/sample_mage2_module/live/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#68 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#69 /home/alex/work/github/sample_mage2_module/live/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#70 /home/alex/work/github/sample_mage2_module/live/htdocs/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#71 /home/alex/work/github/sample_mage2_module/live/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#72 /home/alex/work/github/sample_mage2_module/live/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#73 /home/alex/work/github/sample_mage2_module/live/htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#74 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}
```

**Comment by Vinai** [comment]
@davidalger No, unfortunately my patch wasn't merged, this is still the original method with (in my opinion) broken behavior.

**Comment by buskamuza** [comment]
@flancer64 , you're right, right now Magento does not support `vendor` outside of Magento root folder, but we're working on fixing it. So, for now, `vendor` must be inside Magento root.

Internal ticket MAGETWO-42262

**Comment by vzabaznov** [comment]
Hi @flancer64 bug was closed and delivered, please check it out.

**Comment by ghost** [comment]
@flancer64 @vzabaznov @buskamuza @Vinai Not sure why this was removed. Without it the I cant get require.config to load. It will only load if its mapped and loaded in app/code/modulename

**Comment by buskamuza** [comment]
@joshspivey , what was removed? Could you please elaborate a little bit more on your issue?
