### ISSUE TITLE
[Magento 2.3.2] Upload fails in image uploader

### ISSUE THREAD

**Issue by posttechguy** [magento/magento2#24332]
**Preconditions:**
Magento 2.4-develop
Php 7.3
_fileinfo_ php extension is disabled

**Steps to reproduce:**

1. Go to Admin -> Content -> Pages;
2. Open "Home Page" to edit (for ex.);
3. Expand the **Content** tab;
4. Select the image uploader ("Insert Image" button or the one in the editor);
5. Select an image from your HD and upload it.

**Actual Result:** :heavy_multiplication_x:  Error: Call to undefined function _mime_content_type()_

:heavy_multiplication_x:  An error is shown: "File validation failed." No image is uploaded.

![Screenshot from 2020-09-08 10-59-21](https://user-images.githubusercontent.com/51679138/92455322-339f7f00-f1ca-11ea-8fcd-2590f2a29dd3.png)

**Expected Result:** :heavy_check_mark: An image must be uploaded without errors

![Screenshot from 2020-09-18 15-54-24](https://user-images.githubusercontent.com/51679138/93601095-551e1900-f9c9-11ea-8ce5-e0ea55492db4.png)

The temp uploaded file, i.e., '/tmp/sdfds5we23e', which has no extension, is trying to get the extension thus failing to verify against the validTypes array

**Comment by engcom-Charlie** [comment]
Hello @posttechguy thank you for your report! I'm not able to reproduce issue on clean Magento 2.3.2 .

**Manual testing scenario:**

1. Go to Content -> Pages -> Edit Home page
2. Add img to Content of CMS Page
![image](https://user-images.githubusercontent.com/51680850/63842752-def9df00-c98d-11e9-96ea-5727e5405155.png)


**Actual result:**
Image uploaded without any errors
![image](https://user-images.githubusercontent.com/51680850/63842784-f1741880-c98d-11e9-875d-d888e23f28aa.png)

So i have to close this issue. If you have more info please update your issue.

**Comment by posttechguy** [comment]
Hi @engcom-Charlie I can confirm that the file upload does not work on 2.3-develop. The reason is that the `mime_content_type` is removed in 7.1, and while it is checked to see if it exists the `getFileExtension` is not retrieving the ext because when the file is uploaded to /tmp directory, it saves it without an extension. So there is now way to ascertain whether the file is valid or not.

I have tried it on PHP 7.2.16 also 
![Screen Shot 2019-08-29 at 9 57 44 am](https://user-images.githubusercontent.com/14158530/63904478-afa5a980-ca43-11e9-9362-495e518d42c4.png)

Bevan

**Comment by posttechguy** [comment]
I have also found this bug, on PHP 7.2.16

Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /vagrant/httpdocs/m23-dev/app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php:362 Stack trace: #0 /vagrant/httpdocs/m23-dev/app/code/Magento/Cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(60): Magento\Cms\Model\Wysiwyg\Images\Storage->getFilesCollection('/vagrant/httpdo...', 'image') #1 /vagrant/httpdocs/m23-dev/app/code/Magento/Cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(74): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFiles() #2 /vagrant/httpdocs/m23-dev/app/code/Magento/Cms/view/adminhtml/templates/browser/content/files.phtml(13): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFilesCount() #3 /vagrant/httpdocs/m23-dev/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/vagrant/httpdo...') #4 /vagrant/httpdocs/m23-dev/lib/internal/Magento/Framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Cms\Block\Adminhtml\Wysiwyg\Im in /vagrant/httpdocs/m23-dev/app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php on line 362

Again calling the removed function mime_content_type

**Comment by engcom-Charlie** [comment]
@posttechguy  sorry but in my Magento 2.3.2 instance all works fine:
![image](https://user-images.githubusercontent.com/51680850/63916773-c1864d00-ca41-11e9-86e4-b3e683244b2b.png)

**Comment by hostep** [comment]
This is a duplicate of https://github.com/magento/magento2/issues/16531#issuecomment-405508290

@posttechguy: installing the `fileinfo` php extension should solve your issue.

In my opinion the `fileinfo` extension needs to get added to the requirements in the [`composer.json` file of Magento's Framework](https://github.com/magento/magento2/blob/2.3.2/lib/internal/Magento/Framework/composer.json#L14-L23) and the [`composer.json` file of the CMS module](https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Cms/composer.json#L8)

Interested in creating a pull request for this?

**Comment by posttechguy** [comment]
Thanks @hostep, that was my issue.

I have added a PR for the issue

Cheers

**Comment by AndyJAllen** [comment]
Adding the fileinfo extension fixed my issue too. This should be added to the requirements page:
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21825` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krisdante** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krisdante. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krisdante, here is your [Magento instance](https://i-24332-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24332-2-3-develop.instances.magento-community.engineering/admin](https://i-24332-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Noman77** [comment]
Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/public_html/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php:331 Stack trace: #0 /home/public_html/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(60): Magento\Cms\Model\Wysiwyg\Images\Storage->getFilesCollection('/home/amarcodex...', NULL) #1 /home/amarcodex/public_html/test/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(74): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFiles() #2 /home/public_html/vendor/magento/module-cms/view/adminhtml/templates/browser/content/files.phtml(15): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFilesCount() #3 /home/amarcodex/public_html/test/vendor/magento/framework/View/TemplateEngine/Php.php(59)

**Comment by hostep** [comment]
@Noman77: please read all the comments, the workaround for now is to install the `fileinfo` php extension.
See my comment in https://github.com/magento/magento2/issues/24695#issuecomment-534223837

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37754` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @posttechguy. Thank you for your report. 
The issue has been fixed in magento/magento2#29671 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [8344b1193b33ec89457b3717362dd923f4a7c97d](https://github.com/magento/magento2/commit/8344b1193b33ec89457b3717362dd923f4a7c97d)
 - [8da5e70859784f0cf097fae1bcbaa240db55fb85](https://github.com/magento/magento2/commit/8da5e70859784f0cf097fae1bcbaa240db55fb85)
 - [d312ab5f63f22329c3dde98cbcebb2347c8f077c](https://github.com/magento/magento2/commit/d312ab5f63f22329c3dde98cbcebb2347c8f077c)
 - [f7503ea597d79ed29b544daf169c7ced14ba42f9](https://github.com/magento/magento2/commit/f7503ea597d79ed29b544daf169c7ced14ba42f9)
 - [c09a26144f24548271e908efb4232baec079b92a](https://github.com/magento/magento2/commit/c09a26144f24548271e908efb4232baec079b92a)
 - [12098680bbfa555b8aad268bf8156ada710d507b](https://github.com/magento/magento2/commit/12098680bbfa555b8aad268bf8156ada710d507b)
 - [60c01638fe0f00d92184308eba1599cd58a74f6f](https://github.com/magento/magento2/commit/60c01638fe0f00d92184308eba1599cd58a74f6f)
 - [21f1eb357ce85f236f9af06ba3e429643ad28e3c](https://github.com/magento/magento2/commit/21f1eb357ce85f236f9af06ba3e429643ad28e3c)
 - [0cf0e09cf5453c7fb4f8502722b1a0447c00b9db](https://github.com/magento/magento2/commit/0cf0e09cf5453c7fb4f8502722b1a0447c00b9db)
 - [09bd902440a57c2253f8f44abbbe1da8e98901fc](https://github.com/magento/magento2/commit/09bd902440a57c2253f8f44abbbe1da8e98901fc)

The fix will be available with the upcoming 2.4.2 release.
