### ISSUE TITLE
contradictory when using escapeHtml after getFormattedOption

### ISSUE THREAD

**Issue by dbsdsun** [magento/magento2#24349]
### Preconditions (*)
1.Magento 2.3.2

### Steps to reproduce (*)
1.in vendor\magento\module-sales\view\adminhtml\templates\items\column\name.phtml line 33
 
    <?php $_option = $block->getFormattedOption($_option['value']); ?>
    <?php $dots = 'dots' . uniqid(); ?>
    <?= $block->escapeHtml($_option['value']) ?>

2. the class of $block is vendor\magento\module-sales\Block\Adminhtml\Items\Column\Name.php

    public function getFormattedOption($value)
    {
        $remainder = '';
        $this->truncateString($value, 55, '', $remainder);
        $result = [
            'value' => nl2br($this->truncateResult->getValue()),
            'remainder' => nl2br($this->truncateResult->getRemainder())
        ];
        return $result;
    }

3. problem:
in name.phtml, "</br>" may be added in getFormattedOption, then "</br>" is escaped by 
$block->escapeHtml

### Expected result (*)

1. maybe, you can call  with parameter $allowedTags like this
  
    <?= $block->escapeHtml($_option['value'], ['br']) ?>

2. Actually, this issue exists in many template files.

### Actual result (*)

Lens Options: Single Vision Distance (SVD);&lt;br /&gt; Index: 1.5;&lt;br /&gt; Seg Heigh t: 50;&lt;br /&gt; Right DPD: 40;&lt;br /&gt; Left DPD: 40.

**Comment by dbsdsun** [comment]
BTW, it may not be a good idea to use escapeHtml everywhere. That makes the function very rigid by removing the capability to render with html tags. At least, there should be a flag to turn it off.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19721` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @dbsdsun. Thank you for your report. 
The issue has been fixed in magento/magento2#24392 by @wwwadminwww in 2.3-develop branch
Related commit(s):
 - [f02e79155499978aebe17d9419dcd712346aa912](https://github.com/magento/magento2/commit/f02e79155499978aebe17d9419dcd712346aa912)

The fix will be available with the upcoming 2.3.4 release.
