### ISSUE TITLE
Cannot add a custom elasticsearch field mapper to `Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver`

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#24350]
### Description (*)
I'm adding a custom filter to the layered navigation. My filter is not a product attribute. 
this filter has a request key that does not match the field I store in elasticsearch (similar to how the price works. Price request key is `price` but in elasticsearch is stored as `price_{customer_group}_{website_id}`).  
I need to map this request key to the elasticsearch field. 
I've found that this is done via `Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver` which goes through a list of mappers so I tried to add my own.

### Preconditions (*)
1. Magento 2.3.2

### Steps to reproduce (*)
1. Create a custom module that adds one custom filter in the layered navigation
2. Create one field resolver class that implements `Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\ResolverInterface`

```
namespace [Vendor]\[Module]\Model;

class CustomFieldMapper implements \Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\ResolverInterface
{
    public function getFieldName(AttributeAdapter $attribute, $context = []): ?string
    {
         return $attribute->getAttributeCode() == 'some_value' ? 'some_other_value' : null;
    }
}
```
3. Attach the new mapper to the composite mapper

```
    <type name="Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver">
        <arguments>
            <argument name="items" xsi:type="array">
                <item name="custom_mapper" xsi:type="object">[Vendor]\[Module]\Model\CustomFieldMapper</item>
            </argument>
        </arguments>
    </type>
```

### Expected result (*)

1. My custom mapper should get called
2. The call to  `Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver::getFieldName($attribute)` where `$attribute->getAttributeCode()` returns `some_value` should return `some_other_value`

### Actual result (*)
1. The call from above returns `some_value` because my custom field mapper never gets called. This happens because the default mapper always returns something and my mapper is lower that the default mapper in the list of mappers. 

### Additional info:
My mapper gets attached to the conpositeResolver class properly.   
If I put my mapper higher in the list (editing a core file because I cannot do it via a module) everything works as expected.
I know I can go around it using a plugin for the `ResolverInterface` method, but that kind of defeats the purpose of using composite resolvers.

### Suggestion(s):
 - have a sort order for the mappers
 - (or) ensure that `default` is not part of the list of mappers and it is always executued last.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19780` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ram10raj** [comment]
@m2-community-projec Any update on above i'm also trying with custom fieldmapper my mapper class is not calling

**Comment by ram10raj** [comment]
@mariuscris  any update

**Comment by mariuscris** [comment]
@ram10raj I not involved in this issue. Maybe you want to address it to another Marius :)

**Comment by Axel29** [comment]
Hi @tzyganu , did you get your issue fixed by the PR  https://github.com/magento/magento2/pull/32742?

I'm trying to do the same but get the exact same result... The custom field name provider is in the last position, even though I set the "sortOrder" to "31" (right after "price").

I also tried to put this in evey di.xml declarations for both elasticsaerch, elasticsearch5, elasticsearch6 and elasticsearch7.

Here are the parts of my `di.xml` that are supposed to do this...

```xml
<virtualType name="elasticsearch5FieldNameResolver" type="\Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver">
    <arguments>
        <argument name="items" xsi:type="array">
            <item name="customPriceAsc" xsi:type="object" sortOrder="31">Vendor\Module\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CustomPriceAsc</item>
            <item name="customPriceDesc" xsi:type="object" sortOrder="32">Vendor\Module\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CustomPriceDesc</item>
        </argument>
    </arguments>
</virtualType>
<virtualType name="elasticsearch6FieldNameResolver" type="\Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver">
<arguments>
    <argument name="items" xsi:type="array">
        <item name="customPriceAsc" xsi:type="object" sortOrder="31">Vendor\Module\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CustomPriceAsc</item>
        <item name="customPriceDesc" xsi:type="object" sortOrder="32">Vendor\Module\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CustomPriceDesc</item>
    </argument>
</arguments>
</virtualType>
<virtualType name="\Magento\Elasticsearch7\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver" type="\Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CompositeResolver">
<arguments>
    <argument name="items" xsi:type="array">
        <item name="customPriceAsc" xsi:type="object" sortOrder="31">Vendor\Module\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CustomPriceAsc</item>
        <item name="customPriceDesc" xsi:type="object" sortOrder="32">Vendor\Module\Model\Adapter\FieldMapper\Product\FieldProvider\FieldName\Resolver\CustomPriceDesc</item>
    </argument>
</arguments>
</virtualType>
```

Thanks for your help 🙏
