### ISSUE TITLE
Box layout broken in description box while add new sub category

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#24352]
Box layout broken in description box while add new sub category

### Preconditions (*)
1. magento 2.3
2. Chrome Version 76.0.3809.100 (Official Build) (64-bit)
3. OS: Windows 7
4. Desktop screen resolution: 1366X768

### Steps to reproduce (*)
1. Go to Admin 
2. Catalog -> Categories
3. Add Subcategory
4. Content -> Description
 
### Expected result (*)
![expected result](https://user-images.githubusercontent.com/49804008/63917347-159c2c00-ca58-11e9-975c-558c6c7aeee5.png)

### Actual result (*)
![actual result](https://user-images.githubusercontent.com/49804008/63917358-19c84980-ca58-11e9-95ad-2d57cec71219.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19720` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-24352-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24352-2-3-develop.instances.magento-community.engineering/admin](https://i-24352-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
Hi @bhavik43.  Not reproduced on 2.3-develop instance
![image](https://user-images.githubusercontent.com/50358141/63994960-32963500-cb14-11e9-8927-117606563b57.png)

**Comment by bhavik43** [comment]
@sudheers-kensium, It could be browser specific issue.
I am working on Chrome Browser (Version 76.0.3809.100 (Official Build) (64-bit)) and checking in Windows 7.
Desktop screen resolution: 1366X768
So please check in that way also
Please review below image
![image](https://user-images.githubusercontent.com/49804008/63995479-4b074f00-cb16-11e9-946c-f39186a0a187.png)

**Comment by rajeshwebkul** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sagarwebkul, here is your [Magento instance](https://i-24352-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24352-2-3-develop.instances.magento-community.engineering/admin](https://i-24352-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ptylek** [comment]
Not reproducible on Magento 2.3. I checked browsers below:
- Chrome Version 78.0.3904.70
- Firefox Browser 70.0
- Safari Version 12.1.2
