### ISSUE TITLE
PayPal gateway has rejected request. A match of the Shipping Address City, State, and Postal Code failed (#10736: Shipping Address Invalid City State Postal Code).

### ISSUE THREAD

**Issue by 29sunil** [magento/magento2#24354]
### Preconditions (*)

1.Magento version 2.3.2
2. Fresh Magento install at this URL ( http://newfp.midselec.co.uk/ ) with default theme

### Steps to reproduce (*)

1.open this URL (http://newfp.midselec.co.uk/test.html )
2. add to cart prdocut 
3. checkout using PayPal express checkout

### Expected result (*)

1. payment will be successful
2.

### Actual result (*)

1. We get this error PayPal gateway has rejected request. A match of the Shipping Address City, State, and Postal Code failed (#10736: Shipping Address Invalid City State Postal Code).
and page redirect to cart page
2.

**Comment by 29sunil** [comment]
Yes this we are facing this issue at fresh Magento install. http://newfp.midselec.co.uk

please tell us what is the reason

**Comment by krishprakash** [comment]
Hi @29sunil
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://magento.stackexchange.com/) or the [Magento Stack Exchange](https://community.magento.com/) site for advice or general discussion about this.
Thank You.

**Comment by 29sunil** [comment]
We think this issue is related to magento2 core functionally.Because PayPal is not working with 
default magento 2.3.2. If paypal is working fine than let us know

**Comment by 29sunil** [comment]
We get below errror when merchant country is UK
See attached video
https://www.loom.com/share/f7d20acdb57241039ac73a9c495dd691
