### ISSUE TITLE
Reset not clear date of birth while add new customer

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#24351]
Reset not clear date of birth while add new customer

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Go to Admin 
2. Customers -> All Customers 
3. Add New Customers
4. Add all values with date of birth 
5. Click on reset

### Expected result (*)
All fields should be clear

### Actual result (*)
![dob reset issue](https://user-images.githubusercontent.com/49804008/63913812-12507280-ca4f-11e9-89ec-df29e08f9e84.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24351-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24351-2-3-develop.instances.magento-community.engineering/admin](https://i-24351-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @bhavik43. Thank you for your report.
Issue is not reproduce on vanilla magento instance.
