### ISSUE TITLE
Can't select the category when create the URL Rewrites

### ISSUE THREAD

**Issue by DavidEu000** [magento/magento2#2435]
It's showing nothing but a javascript error after selected the option " For category ", as shown:

SyntaxError: JSON.parse: unterminated string at line 1 column 354 of the JSON data
data: JSON.parse(data)

from main.js (Col:51,Line:18)

Please kindly tell me how to solve this issus?

**Comment by daim2k5** [comment]
@yeedavid sorry for the late response do you can provide more information, maybe include also a screenshot or a step by step guide how we can reproduce this?

**Comment by dgoyachev** [comment]
Have same problem with fresh M2 install with test data (and w/o test data too).

JS error exactly as above,
SyntaxError: JSON.parse: unterminated string at line 1 column 354 of the JSON data

i belive that the error is concerned with this part of code from category page:

{&quot;categoryTree&quot;:{&quot;data&quot;:{&quot;id&quot;:1,&quot;parent_id&quot;:0,&quot;children_count&quot;:39,&quot;is_active&quot;:false,&quot;name&quot;:&quot;Root&quot;,&quot;level&quot;:0,&quot;product_count&quot;:0,&quot;children&quot;:[{&quot;id&quot;:2,&quot;parent_id&quot;:1,&quot;children_count&quot;:38,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Default Category&quot;,&quot;level&quot;:1,&quot;product_count&quot;:1181,&quot;disabled&quot;:true,&quot;children&quot;:[{&quot;id&quot;:38,&quot;parent_id&quot;:2,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;What's New&quot;,&quot;level&quot;:2,&quot;product_count&quot;:0,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:20,&quot;parent_id&quot;:2,&quot;children_count&quot;:8,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Women&quot;,&quot;level&quot;:2,&quot;product_count&quot;:0,&quot;children&quot;:[{&quot;id&quot;:21,&quot;parent_id&quot;:20,&quot;children_count&quot;:4,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Tops&quot;,&quot;level&quot;:3,&quot;product_count&quot;:784,&quot;children&quot;:[{&quot;id&quot;:23,&quot;parent_id&quot;:21,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Jackets&quot;,&quot;level&quot;:4,&quot;product_count&quot;:186,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:24,&quot;parent_id&quot;:21,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Hoodies &amp; Sweatshirts&quot;,&quot;level&quot;:4,&quot;product_count&quot;:182,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:25,&quot;parent_id&quot;:21,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Tees&quot;,&quot;level&quot;:4,&quot;product_count&quot;:192,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:26,&quot;parent_id&quot;:21,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Bras &amp; Tanks&quot;,&quot;level&quot;:4,&quot;product_count&quot;:224,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:22,&quot;parent_id&quot;:20,&quot;children_count&quot;:2,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Bottoms&quot;,&quot;level&quot;:3,&quot;product_count&quot;:228,&quot;children&quot;:[{&quot;id&quot;:27,&quot;parent_id&quot;:22,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Pants&quot;,&quot;level&quot;:4,&quot;product_count&quot;:91,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:28,&quot;parent_id&quot;:22,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Shorts&quot;,&quot;level&quot;:4,&quot;product_count&quot;:137,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:11,&quot;parent_id&quot;:2,&quot;children_count&quot;:8,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Men&quot;,&quot;level&quot;:2,&quot;product_count&quot;:0,&quot;children&quot;:[{&quot;id&quot;:12,&quot;parent_id&quot;:11,&quot;children_count&quot;:4,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Tops&quot;,&quot;level&quot;:3,&quot;product_count&quot;:678,&quot;children&quot;:[{&quot;id&quot;:14,&quot;parent_id&quot;:12,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Jackets&quot;,&quot;level&quot;:4,&quot;product_count&quot;:176,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:15,&quot;parent_id&quot;:12,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Hoodies &amp; Sweatshirts&quot;,&quot;level&quot;:4,&quot;product_count&quot;:208,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:16,&quot;parent_id&quot;:12,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Tees&quot;,&quot;level&quot;:4,&quot;product_count&quot;:192,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:17,&quot;parent_id&quot;:12,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Tanks&quot;,&quot;level&quot;:4,&quot;product_count&quot;:102,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:13,&quot;parent_id&quot;:11,&quot;children_count&quot;:2,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Bottoms&quot;,&quot;level&quot;:3,&quot;product_count&quot;:304,&quot;children&quot;:[{&quot;id&quot;:18,&quot;parent_id&quot;:13,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Pants&quot;,&quot;level&quot;:4,&quot;product_count&quot;:156,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:19,&quot;parent_id&quot;:13,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Shorts&quot;,&quot;level&quot;:4,&quot;product_count&quot;:148,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:3,&quot;parent_id&quot;:2,&quot;children_count&quot;:3,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Gear&quot;,&quot;level&quot;:2,&quot;product_count&quot;:46,&quot;children&quot;:[{&quot;id&quot;:4,&quot;parent_id&quot;:3,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Bags&quot;,&quot;level&quot;:3,&quot;product_count&quot;:14,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:5,&quot;parent_id&quot;:3,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Fitness Equipment&quot;,&quot;level&quot;:3,&quot;product_count&quot;:23,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:6,&quot;parent_id&quot;:3,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Watches&quot;,&quot;level&quot;:3,&quot;product_count&quot;:9,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:7,&quot;parent_id&quot;:2,&quot;children_count&quot;:6,&quot;is_active&quot;:false,&quot;name&quot;:&quot;Collections&quot;,&quot;level&quot;:2,&quot;product_count&quot;:13,&quot;children&quot;:[{&quot;id&quot;:8,&quot;parent_id&quot;:7,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;New Luma Yoga Collection&quot;,&quot;level&quot;:3,&quot;product_count&quot;:347,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:34,&quot;parent_id&quot;:7,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Erin Recommends&quot;,&quot;level&quot;:3,&quot;product_count&quot;:279,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:35,&quot;parent_id&quot;:7,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Performance Fabrics&quot;,&quot;level&quot;:3,&quot;product_count&quot;:310,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:36,&quot;parent_id&quot;:7,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Eco Friendly&quot;,&quot;level&quot;:3,&quot;product_count&quot;:247,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:39,&quot;parent_id&quot;:7,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Performance Sportswear New&quot;,&quot;level&quot;:3,&quot;product_count&quot;:0,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:40,&quot;parent_id&quot;:7,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Eco Collection New&quot;,&quot;level&quot;:3,&quot;product_count&quot;:0,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;no-active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:9,&quot;parent_id&quot;:2,&quot;children_count&quot;:1,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Training&quot;,&quot;level&quot;:2,&quot;product_count&quot;:6,&quot;children&quot;:[{&quot;id&quot;:10,&quot;parent_id&quot;:9,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Video Download&quot;,&quot;level&quot;:3,&quot;product_count&quot;:6,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:29,&quot;parent_id&quot;:2,&quot;children_count&quot;:4,&quot;is_active&quot;:false,&quot;name&quot;:&quot;Promotions&quot;,&quot;level&quot;:2,&quot;product_count&quot;:0,&quot;children&quot;:[{&quot;id&quot;:30,&quot;parent_id&quot;:29,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Women Sale&quot;,&quot;level&quot;:3,&quot;product_count&quot;:224,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:31,&quot;parent_id&quot;:29,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Men Sale&quot;,&quot;level&quot;:3,&quot;product_count&quot;:39,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:32,&quot;parent_id&quot;:29,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Pants&quot;,&quot;level&quot;:3,&quot;product_count&quot;:247,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false},{&quot;id&quot;:33,&quot;parent_id&quot;:29,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Tees&quot;,&quot;level&quot;:3,&quot;product_count&quot;:192,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;no-active-category&quot;,&quot;expanded&quot;:true},{&quot;id&quot;:37,&quot;parent_id&quot;:2,&quot;children_count&quot;:0,&quot;is_active&quot;:true,&quot;name&quot;:&quot;Sale&quot;,&quot;level&quot;:2,&quot;product_count&quot;:0,&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:false}],&quot;cls&quot;:&quot;active-category&quot;,&quot;expanded&quot;:true}],&quot;cls&quot;:&quot;no-active-category&quot;,&quot;expanded&quot;:true},&quot;url&quot;:&quot;http:\/\/dgoryachev.la.net.ua\/admin\/admin\/url_rewrite\/categoriesJson\/key\/20c5e1eda4a2d9f24660e1d056e8c409a16541a18c7dc9ba25debfe9b9e291aa\/&quot;}}

**Comment by DavidEu000** [comment]
Yes, can this be solved?

Thank you,

Best Regards,
David Eu

**Comment by vzabaznov** [comment]
@yeedavid  thanks for reporting, our functionality has been changed and bug cannot be reproduced
Fell free to write comment, or open a new GitHub issue if you feel that issue has not been resolved
