### ISSUE TITLE
Magento 2.3.2: Sort by Bestselling Minimal results

### ISSUE THREAD

**Issue by NagamaniNaresh** [magento/magento2#24370]
### Summary of the issue (*)
I am using custom code to implement sort by Best selling on the category page, I have created an around plugin
```
<type name="Magento\Catalog\Block\Product\ProductList\Toolbar">
    <plugin name="Vnu_Catalog::addPriceDecendingFilterInToolbar" type="Vnu\Catalog\Plugin\Product\ProductList\Toolbar"/>
</type>
```
Toolbar.php
```
/**
     * Plugin
     *
     * @param \Magento\Catalog\Block\Product\ProductList\Toolbar $subject
     * @param \Closure $proceed
     * @param \Magento\Framework\Data\Collection $collection
     * @return \Magento\Catalog\Block\Product\ProductList\Toolbar
     */
    public function aroundSetCollection(
        \Magento\Catalog\Block\Product\ProductList\Toolbar $subject,
        \Closure $proceed,
        $collection
    ) {
        $currentOrder = $subject->getCurrentOrder();
        $currentDirection = $subject->getCurrentDirection();
        $result = $proceed($collection);
        $subject->getCollection()->addAttributeToSelect('manufacturer');

        if ($currentOrder) {
            switch ($currentOrder) {
                case 'best_selling':
                    $subject->getCollection()->getSelect()->joinLeft(
                        'sales_order_item',
                        'e.entity_id = sales_order_item.product_id',
                        ['qty_ordered'=>'SUM(sales_order_item.qty_ordered)'])
                        ->group('e.entity_id')
                        ->order('qty_ordered desc');
                    //echo $subject->getCollection()->getSelect();die;


                    break;
                
                default:
                    $subject->getCollection()->setOrder($currentOrder, $currentDirection);
                    break;

            }
        }
        return $result;
    }
```

### Preconditions (*)
1. Magento 2.3.2
2. PHP 7.2 (Nginx)

### Steps to reproduce (*)
1. Create plugin or preference for adding left join to Toolbar.php
2. Update the collection with left join to sales_order_item table

### Expected result (*)
1. It should display ordered products at top and other products from the category should be followed without reducing the count.

### Actual result (*)
1. I am getting some irrelevant result without pagination. Same code is working fine with M2.2.X

**Comment by jmcharadva** [comment]
@NagamaniNaresh 
Can you please try with below-mentioned code? 
It's working for me. 

$subject->getCollection()->getSelect()->joinLeft( 
                    'sales_order_item', 
                    'e.entity_id = sales_order_item.product_id', 
                    array('qty_ordered'=>'(select sum(soi.qty_ordered) from sales_order_item soi where soi.product_id = e.entity_id)'))->distinct(true) 
                    ->order('qty_ordered '.$currentDirection);

**Comment by NagamaniNaresh** [comment]
@jmcharadva I have added the solution which you have provided, It's working fine. Thank you very much :)-
