### ISSUE TITLE
Related products causing side scrolling on some mobile devices

### ISSUE THREAD

**Issue by elganif** [magento/magento2#24378]
### Preconditions (*)

1. Magento community edition 2.2.9 
2. Bug is visible on newer iPhones (Force enable zoom seems to be default after 10.3.3), and other mobile browsers with force enable zoom (was able to view in both Opera and Dolphin on android with the force enable zoom option on) 

### Steps to reproduce (*)

1. Have any product with 3 or more related products
2. While on product page attempt to scroll side to side on a mobile device with force enable zoom active

### Expected result (*)

1. Expectation no Side scrolling occurs as site is within width of window
2. View remains centered on content  / some content is always on screen

### Actual result (*)

1. Was able to Scroll sideways off page into area with no visible content.
2. Testers would scroll away from content to the right and just see white screen with no content present.

was able to "Fix" this issue for the moment by setting related products not display when mobile display mode activates.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24378-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24378-2-3-develop.instances.magento-community.engineering/admin](https://i-24378-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@elganif - I have verified this issue on latest iPhone X device on latest Magento 2.3 Instance. I do not find any zooming functionality. 
Please review attached the video:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24711761/64105825-9169e180-cd94-11e9-959d-674550ac1619.gif)

**Comment by elganif** [comment]
Thank you for all this work, especial over the long weekend. That looks very different from how it appears on our 2.2.9 site. I will need to look into our back end and make sure we are using the magento default plugin for the related products display.

**Comment by elganif** [comment]
Closing this as I have found it is not a Magento issue, but comes from a plugin I did not realized was affecting the related products. Website was setup before I became involved in the project and I did not realize we were not running the original implementation of related products.
