### ISSUE TITLE
Preselecting configurable product options through URL doesn't update product image

### ISSUE THREAD

**Issue by dugunl** [magento/magento2#24374]
### Preconditions
1. Magento 2.3.1

### Steps to reproduce
1. Create a new configurable product with at least one option.
2. Upload photo A to the configurable product.
3. Upload photo B to the associated simple product.
4. Make sure that Magento automatically loads the image B when the option is selected.
5. Open the configurable product page, with the option pre-selected. For example: https://magento.app/sample-product.html#89=1245

### Expected result
I'd expect Magento to load the product image of the pre-selected option (image B).

### Actual result
Doesn't show image B of the preselected option, but instead shows the main image of configurable product.

I've seen multiple reports about a similar issue, but it seems like those issues were caused by something else. E.g.:
- https://github.com/magento/magento2/issues/18017
- https://daan.dev/how-to/uncaught-typeerror-updatedata-undefined/ (fix)

The updateBaseImage function has changed a lot since then, so this is clearly caused by something else. Is anybody experiencing this too, or is this just on my installations?

One of the (dev area) installations I'm experiencing this on is:
http://gerritsma.dugu.nl/montis-axel#186=216 (the orange block is the configurable product's image, the sofa is the option's image it should be showing instantly).

**Comment by dugunl** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dugnl. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dugnl, here is your [Magento instance](https://i-24374-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24374-2-3-develop.instances.magento-community.engineering/admin](https://i-24374-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dugnl** [comment]
@magento-engcom-team How do I force a reindex on your instances? I've set up all dummy data to test.
