### ISSUE TITLE
Zero subtotal checkout > Automatically Invoice All Items not working

### ISSUE THREAD

**Issue by dankhrapiyush** [magento/magento2#24382]
### Preconditions (*)

1. Magento 2.2.8

### Steps to reproduce (*)

1. Go to: Store > Configuration > Sales > Payment Methods > Zero Subtotal Checkout
2. Set 'New Order Status' to 'Processing'.
3. On select above option, 'Automatically Invoice All Items' option by default set to 'Yes'. Keep it as it is.
![2019-08-31_11-36-32](https://user-images.githubusercontent.com/1868477/64059958-bc610380-cbe3-11e9-9538-2213c7ae42f7.jpg)
4. Go to frontend, add an item to cart
5. Create a cart rule with 100% rebate and free shipping and apply to the cart
6. Place an order with 'Zero Subtotal Checkout' payment method

### Expected result (*)

1. Invoice should generate on place an order

### Actual result (*)

1. Invoice is not generating

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24382-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24382-2-3-develop.instances.magento-community.engineering/admin](https://i-24382-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @dankhrapiyush 
I checked this on magento 2.3-develop instance . It seems this issue already fixed on 2.3-deveop instance please check again on 2.3 dev instance and if it still persists Please share screenshots also 
![image](https://user-images.githubusercontent.com/25526037/64060396-90e11780-cbe9-11e9-9ea0-e28f596bfb6b.png)

**Comment by dankhrapiyush** [comment]
@shikhamis11 Thanks for looking into the issue.

I already mentioned **Magento 2.2.8** under **Preconditions**.
So you should check in the Magento 2.2 instance.

Please verify. Also, let me know if there is no further support on Magento 2.2 release line.

**Comment by shikhamis11** [comment]
@dankhrapiyush yes Magento no logner gives support for magento 2.2.x versions . I try to share the comits which fix this issue

**Comment by krishprakash** [comment]
@dankhrapiyush 
You can review the fixes in related PR
https://github.com/magento/magento2/pull/23688

**Comment by dankhrapiyush** [comment]
Okay, Thank you.
