### ISSUE TITLE
Selected options are not showing on edit wish list page.

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24389]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.19

### Steps to reproduce (*)

1. Create a configurable product with swatches
2. Navigate to product page at frontend
3. Select swatches options and to wish list
4. open wish list and click on edit

### Expected result (*)

1. Selected options should be displayed on edit wish list page
![wishlist-selected-options](https://user-images.githubusercontent.com/44425160/64063066-db27c000-cc0c-11e9-957f-6460e0efa45a.png)
![wishlist-configure](https://user-images.githubusercontent.com/44425160/64063068-e0850a80-cc0c-11e9-947a-76c3e842adb4.png)

### Actual result (*)

1. Selected options are not showing 
![wishlist](https://user-images.githubusercontent.com/44425160/64063072-fe526f80-cc0c-11e9-9948-91c51e62dee2.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19775` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
