### ISSUE TITLE
Creating shipments for two different orders and getting the tracking number inmediately after each creation gets the same tracking number for both orders.

### ISSUE THREAD

**Issue by rpelorosso** [magento/magento2#24381]
When creating a shipment for two orders one after another, if after each creation I get the tracking number (as it happens in the shipping notification template) the tracking number gotten for the second order is the one used in the first order.

However, the tracking numbers are right in the admin. This means that shipping notifications are sent with the wrong tracking number, but they are ok in the admin.

### Preconditions (*)
1. Magento EE 2.3.2

### Steps to reproduce (*)

1. Programmatically create a shipment for an order X and assign Tracking number TNX.
2. Get the tracking number for order X.
3. Programmatically create a shipment for an order Y and assign Tracking number TNY.
4. Get the tracking number for order Y.

### Expected result (*)

1. The tracking number gotten for order X should be TNX.
2. The tracking number gotten for order Y should be TNY.

### Actual result (*)

1. The tracking number gotten for order X is TNX.
2. The tracking number gotten for order Y is TNX.

I tested this in a vanilla install of Magento 2.3.2 Enterprise Edition. I created a module that has this function for creating a shipment for an order and assigns a tracking number.

```
public function updateOrderWithTrackingNumber($order_id, $tracking_number) {

    // Load up the order
    $order = $this->ordersModel->loadByIncrementId($order_id);

    if ($order->canShip()) {

        // Initialize the order shipment object
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $convertOrder = $objectManager->create('Magento\Sales\Model\Convert\Order');
        
        // Create shipment
        $shipment = $convertOrder->toShipment($order);

        // Loop through order items
        foreach ($order->getAllItems() AS $orderItem) {
            // Check if order item has qty to ship or is virtual
            if (! $orderItem->getQtyToShip() || $orderItem->getIsVirtual()) {
                continue;
            }
            $qtyShipped = $orderItem->getQtyToShip();
            // Create shipment item with qty
            $shipmentItem = $convertOrder->itemToShipmentItem($orderItem)->setQty($qtyShipped);
            // Add shipment item to shipment
            $shipment->addItem($shipmentItem);
        }

        // Register shipment
        $shipment->register();
        $shipment->getOrder()->setIsInProcess(true);

        // Create Track 
        $track = $this->trackFactory->create(); // ->addData($data);

        // set tracking number to track
        $track->setTrackNumber($tracking_number);

        // set carrier code
        $track->setCarrierCode("UPS");

        // set title
        $track->setTitle("UPS GROUND");

        // add track to shipment
        $shipment->addTrack($track);

        echo "Adding track number {$tracking_number} to order #{$order_id}<br>";

        try {
            // Save created shipment and order
            $shipment->save();
            $shipment->getOrder()->save();

        } catch (\Exception $e) {
            echo "Shipment Not Created". $e->getMessage(); exit;
        }

        echo "Shipment Succesfully Generated for order: #".$order_id. "<br>";

        $this->printTrackingNumbersForOrder($order_id);

    } else {
        echo "Shipment Not Created Because It's already created or something went wrong <br>";
    }

    echo "--------<br>";

    return;

}
```
And this one for displaying the tracking number of an order.
```
function printTrackingNumbersForOrder($order_id) {
    // Reload order and Get the tracking number to see if it was correctly saved
    $order = $this->ordersModel->loadByIncrementId($order_id);
    $tracksCollection = $order->getTracksCollection();
    $tracks = $tracksCollection->getItems();
    $n = count($tracks);

    echo ("Getting the order's tracking number to check if it's been saved correctly <br>");

    foreach ($tracks as $track) {
        $trackNumbers[] = $track->getTrackNumber();
        echo("Tracking number: {$track->getTrackNumber()}<br>");
    }
}
```

When I run this:
```
updateOrderWithTrackingNumber("000000001", "ONE TRACKING");
updateOrderWithTrackingNumber("000000002", "DIFFERENT TRACKING");
```

I get the following output:

```
Adding track number ONE TRACKING to order #000000001
Shipment Successfully Generated for order: #000000001
Getting the order's tracking number to check if it's been saved correctly
Tracking number: ONE TRACKING
---------
Adding track number DIFFERENT TRACKING to order #000000002
Shipment Successfully Generated for order: #000000002
Getting the order's tracking number to check if it's been saved correctly
Tracking number: ONE TRACKING
```

Which shows that the tracking number is wrong for the second order.

**Comment by engcom-Delta** [comment]
Hi @rpelorosso thank you for your report. I am not able to reproduce issue by steps you described on clean 2.3-develop.

![#24381issueConsole](https://user-images.githubusercontent.com/51681379/68032435-5f0e2f00-fcc6-11e9-8e09-5fedfd0abb38.png)

![#24381issueOrder1](https://user-images.githubusercontent.com/51681379/68032444-61708900-fcc6-11e9-9c11-852029eba1b2.png)

![#24381issueOrder2](https://user-images.githubusercontent.com/51681379/68032453-63d2e300-fcc6-11e9-9f1d-9eb5ff755dbe.png)

If you still experience this issue You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by stefas1** [comment]
Hi @rpelorosso, We are having the same exact issue. Have you managed to figure it out ?

**Comment by rpelorosso** [comment]
Hi @stefas1 ! Sorry for my late response. As I send the shipping notifications right after generating the shipments, what I did in the end was to store the correct tracking number for each order in a map, and then when I generate the html for the notification emails, I get the tracking number from there instead of using  $track->getTrackNumber();  

It's not pretty, but it works. Let me know if you have any other doubts!

**Comment by stefas1** [comment]
Hi @rpelorosso. Thank you for your response. Yes, it seems the only way to avoid digging further into the problem. We, on the other hand, did it by shipping one order per cron run. Not very optimal but in the specific case it did the trick.
