### ISSUE TITLE
I cannot go to magento's backend

### ISSUE THREAD

**Issue by arnulfodr** [magento/magento2#2438]
Well, that, i cannot enter to the backend, I tried with the url I got in the instalation, which is: http://localhost/magentov2/admin_kj7cw0 and nothing, any idea??

**Comment by buskamuza** [comment]
Hi @arnulfodr , what happens?
Is it Admin Panel login is not opened at all (404)? Or you can't log in?
With non-dot host it can be possible that you can't log in, as some browsers do not work with cookies as expected. So, if you have an issue with logging in, I'd suggest to use another host name, which will include a dot (e.g., "magento.loc").

**Comment by arnulfodr** [comment]
Forget about it, I had a cookie problem
