### ISSUE TITLE
Downloadable Products status remain Pending after place an order

### ISSUE THREAD

**Issue by dankhrapiyush** [magento/magento2#24385]
### Preconditions (*)

1. Magento 2.2.9
2. Configure any payment method that generates an invoice on place an order

### Steps to reproduce (*)

1. Add a downloadable product to the cart
2. Place an order with PayPal or any other payment method that generates an invoice on place an order
3. Go to 'My Downloadable Products' section under My account
4. Check 'Status' column of order item

### Expected result (*)

1. Status should set to 'Available' instead of 'Pending' and customer can able to download the file
![2019-08-31_12-09-13](https://user-images.githubusercontent.com/1868477/64060301-427f4900-cbe8-11e9-95d6-501f392ec5df.jpg)

![2019-08-31_12-07-39](https://user-images.githubusercontent.com/1868477/64060281-051abb80-cbe8-11e9-8d88-854337df42cb.jpg)

### Actual result (*)

1. Status set to 'Pending' instead of 'Available'

**Comment by jmcharadva** [comment]
@dankhrapiyush 
I have checked this issue in the magento2.2.9 CE version. There is not an issue. It's working fine as per expected result.
I have checked with no sample data. 

(https://user-images.githubusercontent.com/47854937/64166789-73b87d00-ce65-11e9-81f0-c46aa100fd78.png)
(https://user-images.githubusercontent.com/47854937/64166779-6d2a0580-ce65-11e9-9af8-1c4ef8c4beed.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24385-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24385-2-3-develop.instances.magento-community.engineering/admin](https://i-24385-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@dankhrapiyush - I have verified this issue with your steps and payment mode. Order status is displaying 'Complete' after generating the invoice.
See attached the screenshot:
![Magento 2 3](https://user-images.githubusercontent.com/24711761/64316636-062a5f00-cfd3-11e9-92d2-d84cdde70a77.png)

Now I am closing this issue. If you have reproduced this issue again you can open it.

Thanks.

**Comment by dankhrapiyush** [comment]
@ajijshekh123 Please read the issue first.
I confirmed the issue in Magento 2.3.2 as well.

The problem is under **My Downloadable Products** section, the status remains 'Pending' instead of 'Available'.

**Comment by ajijshekh123** [comment]
Sorry @dankhrapiyush, It was my mistake. Let me check again and verify the issue.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24385-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24385-2-3-develop.instances.magento-community.engineering/admin](https://i-24385-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@dankhrapiyush - I have verified 'My Downloadable Product' Page, I have followed the same steps which you are added.
Place an Order using Paypal and Check Money order.

See the attached screenshot:
![2019-09-09 (1)](https://user-images.githubusercontent.com/24711761/64534391-027c3c80-d333-11e9-941f-ebddba25253a.png)
![2019-09-09](https://user-images.githubusercontent.com/24711761/64534393-0314d300-d333-11e9-8fe6-fb208587abbe.png)
