### ISSUE TITLE
Configurable product image not showing as per selected options

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24383]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.19

### Steps to reproduce (*)

1. Create a configurable product with swatches
2. Set image for each associated products
3. Navigate to product page at frontend
4. Select second or third image of main product
5. Then select any option it's  not showing the actual image, it's showing previous image.

### Expected result (*)

1. Actual selected configuration image should be display. 
![image-config](https://user-images.githubusercontent.com/44425160/64060202-0dbec200-cbe7-11e9-919a-fcfc3e82e190.png)

### Actual result (*)

1. Selected configuration image not showing
![image-issue](https://user-images.githubusercontent.com/44425160/64060210-216a2880-cbe7-11e9-9d62-a4af391ca521.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24383-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24383-2-3-develop.instances.magento-community.engineering/admin](https://i-24383-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @rani-webkul. Thank you for your report.
Issue is duplicate to #16409
