### ISSUE TITLE
shipping address lost so can not change shipping address

### ISSUE THREAD

**Issue by renard123** [magento/magento2#24386]
shipping address lost so can not change the shipping address

### Preconditions (*)
- Magento 2.3.2
- create the customer from admin
- add 3-4 additional addresses for that customer

### Steps to reproduce (*)
1. Login to Admin -> Sales -> Orders -> Create New Order  -> Select Customer -> Go to Address Information 
2. Select different Address For billing Address
3. Uncheck the "Same As Billing Address" for shipping address
4. Change the billing address again 
5. Check the "Same As Billing Address" for shipping address
6. See the shipping address section lost at one point

### Expected result (*)
The shipping address section should not be lost.
If admin wants to update shipping again then how can they do it as the shipping section is lost.

### Actual result (*)
![Peek 2020-08-05 16-00](https://user-images.githubusercontent.com/51679138/89415881-30c9ee00-d735-11ea-9275-44af824dfb74.gif)

**Comment by mahesh-rajawat** [comment]
@krishprakash i have checked this issue, its reproducible, please check from your end and mark as confirmed.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24386-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24386-2-3-develop.instances.magento-community.engineering/admin](https://i-24386-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19778` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @renard123. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24032` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
