### ISSUE TITLE
Design issue on sales order view page frontend

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24395]
### Preconditions (*)

1. Magento2.3.2
2. PHP 7.2.19

### Steps to reproduce (*)

1. Place an order with even number of items
2. Go to customer account section and view the order

### Expected result (*)

![order-list](https://user-images.githubusercontent.com/44425160/64064844-66f91680-cc24-11e9-882f-2326c20c2ebb.png)

### Actual result (*)

![order-list-issue](https://user-images.githubusercontent.com/44425160/64064845-6d878e00-cc24-11e9-8aed-86c1c432b80e.png)

**Comment by Stepa4man** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, here is your [Magento instance](https://i-24395-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24395-2-3-develop.instances.magento-community.engineering/admin](https://i-24395-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @rani-webkul. Thanks for applying. Seems we do not clearly understand what You mean. It's a grid, it is supposed to look like that, i.e lighter row, darker row, lighter row, darker row, isn't it?
![grid](https://user-images.githubusercontent.com/51680745/64108099-a6d70f80-cd84-11e9-854d-68beccc9aa0f.png)
Or You mean something else?

**Comment by rani-priya** [comment]
@engcom-Bravo yes it's a grid and differentiated by a lighter row and darker row. But two row must not be same in color. As you can see last row and total row have same dark background color.

**Comment by engcom-Bravo** [comment]
Ok @rani-webkul, but then Your Expected Result with two light items going one after the other should be changed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19787` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24396 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [3cebfd37293db2f8deac47cec078c7edc2290fd6](https://github.com/magento/magento2/commit/3cebfd37293db2f8deac47cec078c7edc2290fd6)

The fix will be available with the upcoming 2.3.4 release.
