### ISSUE TITLE
Order information in print order, invoice, credit memo and shipment is not proper aligned 

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24393]
### Preconditions (*)

1. Magento 2.3.2 ... 2.4-develop
1. PHP 7.2.19

### Steps to reproduce (*)

1. Place an order
1. Go to customer account section and open that order
1. Click on print order link

### Expected result (*)

1. Order information should be
![order-info](https://user-images.githubusercontent.com/44425160/64064204-082f9f00-cc1c-11e9-8823-2797fc233e11.png)

### Actual result (*)

![order-info-issue](https://user-images.githubusercontent.com/44425160/64064216-0f56ad00-cc1c-11e9-8913-0f8f8aa41c5f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19786` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cristhianss** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cristhianss. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cristhianss, here is your [Magento instance](https://i-24393-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24393-2-3-develop.instances.magento-community.engineering/admin](https://i-24393-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cristhianss** [comment]
Hi @magento-engcom-team, this issue has already been fixed.
I will close this issue.

**Comment by engcom-Bravo** [comment]
Hi @cristhianss. Would You please provide a reference to the PR that fixes this issue. Thank You.

**Comment by rani-priya** [comment]
Issue still exists in magento 2.3-develop branch

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-24393-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24393-2-3-develop.instances.magento-community.engineering/admin](https://i-24393-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hi @cristhianss. I can't really guess why You close reproducible issues. Here is the screenshot obtained on the just deployed instance from above:
![order](https://user-images.githubusercontent.com/51680745/64949161-42867680-d881-11e9-9c33-257078d3e13b.png)
Please next time be more carefull when closing an issue. Thank You.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20167` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Still actual for `2.4-develop`
[Order # 000000001.pdf](https://github.com/magento/magento2/files/4771879/Order.000000001.pdf)
