### ISSUE TITLE
So many users try to install Magento 2 on top-level domain like «localhost», and I think Magento 2 should warn such users during installation 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2439]

**Comment by realdigid** [comment]
Yes, agreed! I did fresh install only for admin login to break(infinite loop), and front end page loaded without css... I mean, this issue has been carried over from 1.x can't this be added or at minium a huge warning stating this will be problem... It would've saved me a few hours had i known this.

**Comment by dannamite** [comment]
Same here. If this is a common issue then at least a warning during installation is warranted.

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by techsoulman** [comment]
I don't know why this is a problem and how to fix it(I have no css and missing images/media), can someone link me to the solution? (btw I'm a noob so please language for dummies thanks)

**Comment by realdigid** [comment]
Add domain to your host file something like "magento.local" and point to 127.0.0.1

**Comment by brettsaguid** [comment]
@realdigid im using apache2 & ubuntu 14.04. i have a virtual host file:

i replaced my actual domain name, dont worry.
<VirtualHost *:80>                                                                                                   
        ServerAdmin support@mydomain.com                                                                         
        ServerName mydomain.com                                                                                  
        ServerAlias www.mydomain.com                                                                             
        DocumentRoot /var/www/html/mydomain.com/public_html/                                                     
        ErrorLog /var/www/html/mydomain.com/logs/error.log                                                       
        CustomLog /var/www/html/mydomain.com/logs/access.log combined                                            
#       <Directory /path/to/public/website/>                                                                         
#               Require all granted                                                                                  
#       </Directory>                                                                                                 
</VirtualHost>  

Is anything wrong here that would cause magento to be stuck when installing the sample data?

**Comment by andimov** [comment]
@mage2pro 
Could you please provide description according to the template.?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by likemusic** [comment]
Related to top-level domain issue https://github.com/magento/magento2/issues/5946
