### ISSUE TITLE
Database installation problem.

### ISSUE THREAD

**Issue by lonniebrodie** [magento/magento2#2440]
I am getting this intercept:

Database user does not have enough privileges. Please make sure SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER privileges are granted to table 'xxxxxxx_dbMagento2'.

I am using the "Full Access Username"

Installation was no problem, using the same setup, server, host, when using RC1.

**Comment by mazhalai** [comment]
@starphysique can you please login to mysql using the db user specified in setup wizard and 
show output from the command `SHOW GRANTS FOR CURRENT_USER();` exact details [here](https://dev.mysql.com/doc/refman/5.7/en/show-grants.html)

**Comment by lonniebrodie** [comment]
Per your request:

Grants for gtadmin_415@%
GRANT USAGE ON _._ TO 'gtadmin_415'@'%' IDENTIFIED...
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP...

**Comment by mazhalai** [comment]
@starphysique Please check if the privileges match those required by magento in your first comment.

**Comment by davidalger** [comment]
Closing due to lack of response
