### ISSUE TITLE
Vat ID not being included in Shipping Address in Magento 2.3.2

### ISSUE THREAD

**Issue by Jackcar** [magento/magento2#24402]
After updating to Magento 2.3.2, VAT ID is not included in the Shipping Address in the checkout anymore. My Magento works in Brazil and the VAT ID is required by the major payment solutions companies around here.
I found the problem and this field is missing in the file `\Magento\Customer\Model\Address\CustomerAddressDataFormatter.php` in the `prepareAddress(AddressInterface $customerAddress)` method.

### Preconditions (*)
1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)
1. Create customer account with correct VAT ID;
2. Login to account;
3. Place an order;
4. Go to Checkout Page;
5. Open the inspector tool;
6. Go to Network tab;
7. Fill up the shipping form;
8. Go to payment methods step;
9. Check the payload sent in the `/V1/carts/mine/shipping-information` request.

### Expected result (*)
<img width="1302" alt="Captura de Tela 2019-09-01 às 22 12 08" src="https://user-images.githubusercontent.com/7013608/64082353-a8152780-cd05-11e9-95d0-903d4a62c904.png">

### Actual result (*)
<img width="1318" alt="Captura de Tela 2019-09-01 às 22 13 47" src="https://user-images.githubusercontent.com/7013608/64082367-d0048b00-cd05-11e9-946d-4c19a2c3d364.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19815` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Jackcar. Thank you for your report. 
The issue has been fixed in magento/magento2#24403 by @edenduong in 2.3-develop branch
Related commit(s):
 - [0f38f03418d4228e4e3c4898f9e95508ecef25ca](https://github.com/magento/magento2/commit/0f38f03418d4228e4e3c4898f9e95508ecef25ca)

The fix will be available with the upcoming 2.3.4 release.
