### ISSUE TITLE
Field catalog_product_entity.attribute_set_id has no referential integrity

### ISSUE THREAD

**Issue by gibbotronic** [magento/magento2#24408]
Table *catalog_product_entity* has column *attribute_set_id* but there is no relation to *eav_attribute_set* at all.
This means deleting an attribute set will leave invalid ids (even though the admin panel warns that deleting an attribute set will delete the products associated with that set). It doesn't.
There should be a foreign key from catalog_product_entity.attribute_set_id with a cascading delete set on it.

### Preconditions (*)

1. Magento 2.3.2 with a created database
2. An attribute set
3. A product using that attribute set

### Steps to reproduce (*)

1. Delete the attribute set using either the admin interface or RESTful API

### Expected result (*)

1. The product should also be deleted as it uses the deleted attribute set

### Actual result (*)

1. The product remains but catalog_product_entity.attribute_set_id refers to a non-existent attribute set. My data is now bad.

The following SQL dumps are from the database profile mechanism which I have enabled to send their profile information elsewhere so I can review it without affecting the main page display.

You can see when deleting products via the admin panel that the following queries are ran (eg. a GET to /admin/catalog/product_set/delete/id/138/key/273574347ea0586d14968d99bcb64fafa09ec27188d9515c0a430474b63f4c90/):
```sql
connect
SET NAMES utf8
SELECT `store_website`.* FROM `store_website`
SELECT `store_group`.* FROM `store_group`
SELECT `store`.* FROM `store`
SELECT `flag`.* FROM `flag` WHERE (`flag`.`flag_code`='config_hash')
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'frontend') AND (`theme_path` = 'Magento/luma')
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'frontend') AND (`theme_path` = 'Magento/blank')
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'adminhtml') AND (`theme_path` = 'Magento/backend')
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`main_table`.`type` IN(0))
SELECT `main_table`.*, `parent`.`type` AS `parent_type` FROM `theme` AS `main_table` INNER JOIN `theme` AS `parent` ON main_table.parent_id = parent.theme_id WHERE (parent.type = 1) AND (main_table.type = 1)
SELECT `main_table`.*, `parent`.`type` AS `parent_type` FROM `theme` AS `main_table` INNER JOIN `theme` AS `parent` ON main_table.parent_id = parent.theme_id WHERE (parent.type = 0) AND (main_table.type = 2)
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'frontend') AND (`theme_path` = 'Magento/luma')
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'frontend') AND (`theme_path` = 'Magento/blank')
begin
UPDATE `theme` SET `parent_id` = ?, `theme_path` = ?, `theme_title` = ?, `preview_image` = ?, `is_featured` = ?, `area` = ?, `type` = ?, `code` = ? WHERE (theme_id='2')
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (main_table.area='frontend') AND (`main_table`.`type` IN(1))
commit
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'frontend') AND (`theme_path` = 'Magento/blank')
begin
UPDATE `theme` SET `parent_id` = ?, `theme_path` = ?, `theme_title` = ?, `preview_image` = ?, `is_featured` = ?, `area` = ?, `type` = ?, `code` = ? WHERE (theme_id='1')
commit
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'frontend') AND (`theme_path` = 'Magento/luma')
begin
UPDATE `theme` SET `parent_id` = ?, `theme_path` = ?, `theme_title` = ?, `preview_image` = ?, `is_featured` = ?, `area` = ?, `type` = ?, `code` = ? WHERE (theme_id='4')
commit
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`area` = 'adminhtml') AND (`theme_path` = 'Magento/backend')
begin
UPDATE `theme` SET `parent_id` = ?, `theme_path` = ?, `theme_title` = ?, `preview_image` = ?, `is_featured` = ?, `area` = ?, `type` = ?, `code` = ? WHERE (theme_id='3')
commit
SELECT `admin_user`.* FROM `admin_user` WHERE (`admin_user`.`user_id`='1')
SELECT `admin_user_session`.* FROM `admin_user_session` WHERE (`admin_user_session`.`session_id`='f39drg7qcu3e5jhbomhrug00dp')
begin
UPDATE `admin_user_session` SET `updated_at` = '2019-09-02 10:56:20' WHERE (id='36')
commit
SELECT `eav_attribute_set`.* FROM `eav_attribute_set` WHERE (`eav_attribute_set`.`attribute_set_id`='138')
begin
DELETE FROM `eav_attribute_set` WHERE (attribute_set_id='138')
commit
SELECT `e`.* FROM `catalog_product_entity` AS `e` WHERE (`e`.`attribute_set_id` = '138')
```

You can see when deleting products via the RESTful API that the following queries are ran (eg. DELETE to rest/V1/products/attribute-sets/147):
```sql
connect
SET NAMES utf8
SELECT `store_website`.* FROM `store_website`
SELECT `store_group`.* FROM `store_group`
SELECT `store`.* FROM `store`
SELECT `flag`.* FROM `flag` WHERE (`flag`.`flag_code`='config_hash')
SELECT `oauth_token`.* FROM `oauth_token` WHERE (`oauth_token`.`token`='asrv6pijsidv2ww0myh77ksqx0qnantk')
SELECT `main_table`.* FROM `authorization_role` AS `main_table` WHERE (`user_id` = '1') AND (`user_type` = '2')
SELECT `eav_attribute_set`.* FROM `eav_attribute_set` WHERE (`eav_attribute_set`.`attribute_set_id`=147)
SELECT `eav_attribute_set`.* FROM `eav_attribute_set` WHERE (`eav_attribute_set`.`attribute_set_id`=147)
begin
DELETE FROM `eav_attribute_set` WHERE (attribute_set_id='147')
commit
```

Note the complete lack of cleaning up of products that are associated with the attribute set, eg.

```sql
delete from catalog_product_entity where attribute_set_id not in (select attribute_set_id from eav_attribute_set)
```

My products now point to thin air for their attribute set ids.

**Comment by gibbotronic** [comment]
Additionally, attempting to now edit any of my products within the admin interface will fail with:

```Fatal error: Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /usr/local/var/www/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php on line 385 and defined in /usr/local/var/www/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php:335 Stack trace: #0 /usr/local/var/www/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(385): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataElement(Array, 'configurableExi...', NULL, false) #1 /usr/local/var/www/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(410): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #2 /usr/local/var/www/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(410): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #3 /usr/local/var/www/lib/internal/Magento/Framework/View/Element in /usr/local/var/www/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php on line 335```

**Comment by gibbotronic** [comment]
> @gibbotronic do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [x ]  yes
> 
>     * [ ]  no
> 

To confirm, I can reproduce this on vanilla Magento

**Comment by engcom-Bravo** [comment]
Hello @gibbotronic. Thanks for applying but currently we've been not able to reproduce Your issue nether on the 2.3-develop nor on 2.3.2 version You have reported this issue on.
![attributeset](https://user-images.githubusercontent.com/51680745/64118045-73ee4500-cd9f-11e9-94ca-259f14835fe3.gif)
Is there something wrong in our actions?

**Comment by gibbotronic** [comment]
Very odd! That looks correct (@engcom-Bravo thanks for the screen recording, very helpful).

How did you create your product? I am creating products using the RESTful API (eg. catalogProductRepositoryV1SavePost, a POST to rest/V1/products).

Does your catalog_product_entity table have referential integrity to eav_attribute_set that is causing the product to be deleted??
I am only asking in order to find out why mine does not delete the related products.

**Comment by engcom-Bravo** [comment]
@gibbotronic, my product was created simply in admin. Maybe it will make sense that You try to reproduce Your issue with the product, also created like that?

**Comment by engcom-Bravo** [comment]
@gibbotronic, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
