### ISSUE TITLE
Magento Installation with apache

### ISSUE THREAD

**Issue by abubakar-bilal** [magento/magento2#24404]
### Preconditions (*)

1. Apache
2. Magento 2.3

### Steps to reproduce (*)

1. Install apache.
2. Try to install magento with below conf file

### Expected result (*)

1. Proper setup wizard should display
2. All css and js should be intact.

### Actual result (*)

1. url of site doesn't redirect to setup.
2. After manual setup, css and js is broken.

Can anyone please provide me with apache.conf.sample just like we have nginx.conf.sample. Thanks in advance.

**Comment by krishprakash** [comment]
Hi @abubakar-bilal.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Thank You.
