### ISSUE TITLE
Shopping Cart Sidebar should be Minicart 

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#24409]
### Preconditions (*)

1. Latest Magento

### Steps to reproduce (*)

1. https://www.screencast.com/t/HjHNYc4Hrf 
this thing apply for the mini cart so it should be for mini cart
It is mis understanding word, as above setting apply for Mini Cart so Shopping Cart Sidebar should be Mini Cart 

### Expected result (*)

1. Text changes:- https://www.screencast.com/t/HjHNYc4Hrf it should be MiniCart 

### Actual result (*)

1. Shopping Cart Sidebar should be Mini Cart

**Comment by magento-engcom-team** [comment]
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19792` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-24409-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24409-2-3-develop.instances.magento-community.engineering/admin](https://i-24409-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by priti2jcommerce** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-24409-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24409-2-3-develop.instances.magento-community.engineering/admin](https://i-24409-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-24409-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24409-2-3-develop.instances.magento-community.engineering/admin](https://i-24409-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your report. 
The issue has been fixed in magento/magento2#24411 by @sunilit42 in 2.3-develop branch
Related commit(s):
 - [95cad1ae94b01bcef66ee7ff63a9d489d45ff911](https://github.com/magento/magento2/commit/95cad1ae94b01bcef66ee7ff63a9d489d45ff911)
 - [29a1544c59766e6d807db18daa941badf86a3d95](https://github.com/magento/magento2/commit/29a1544c59766e6d807db18daa941badf86a3d95)
 - [bc1657b298d55d024c3104cb94976019032f4f1f](https://github.com/magento/magento2/commit/bc1657b298d55d024c3104cb94976019032f4f1f)
 - [6b3c12e0a946855958d9136a06536297d94da8b5](https://github.com/magento/magento2/commit/6b3c12e0a946855958d9136a06536297d94da8b5)

The fix will be available with the upcoming 2.3.4 release.
