### ISSUE TITLE
{{config path='trans_email/ident_support/email'}} does not display support email

### ISSUE THREAD

**Issue by logicallimit** [magento/magento2#24419]
### Preconditions (*)

1. Magento CE 2.3.2
2. CentOS Linux release 7.6.1810
3. MySQL version: 10.1.40-MariaDB

### Steps to reproduce (*)

1. Login to Admin Panel.
2. Go to Marketing -> Email Templates -> Click on button "Add New Template"
3. For section "Template Content", click on button "Insert Variable". A list of available variables appears. This list does not shows variables for "Support Email and Name"

### Expected result (*)

1. The list show the variables for "Support Name and Email". Because this information is captured under Admin screen "Stores -> Configuration -> General -> Store Email Addresses -> Customer Support"
Refer below snapshot:
![image](https://user-images.githubusercontent.com/7191368/64147123-fc6ef300-ce3c-11e9-85cd-840d103e2c55.png)

2. Like other email variables {{config path='trans_email/ident_sales/email'}}, the support email should be rendering on emails if variable {{config path='trans_email/ident_support/email'}} is used.

### Actual result (*)

1. Refer below snapshot.
![image](https://user-images.githubusercontent.com/7191368/64146710-9e8ddb80-ce3b-11e9-9c2f-0279d752b655.png)

2. The list of variables does not show customer support name and email details.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19846` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @logicallimit. Thank you for your report. 
The issue has been fixed in magento/magento2#24425 by @edenduong in 2.3-develop branch
Related commit(s):
 - [ba3a134e1abcfc4365f22756735c3cf52b7269cb](https://github.com/magento/magento2/commit/ba3a134e1abcfc4365f22756735c3cf52b7269cb)

The fix will be available with the upcoming 2.3.4 release.
