### ISSUE TITLE
Create customer api taking too much time

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2441]
i am trying to create a new user with api call

http://MYHOST/rest/default/V1/customers

its taking approx two or three minutes to create a user, is there any way to reduce the api call time.

**Comment by mbrinton01** [comment]
@choukalos

**Comment by choukalos** [comment]
Hi @arunkasyakar can you provide your request payload?  Is this a first request before files are generated/etc (i.e. in Default mode, have you tried browsing on the front end and logging into the admin panel to make sure appropriate files are generated.  Either that or put the system into production mode).  I tried with this rather complex payload and got a reply back in 1072ms on my laptop using Postman.  Believe in load testing we're seeing responses back across the board in under 1 second.

Example Payload:
{
    "customer": {
  "email": "franky@smith.com",
  "firstname": "Franky",
  "lastname": "Smith",
  "gender": 1,
  "addresses": [ 
    {
    "region": {
        "region_code": "AL",
        "region": "Alabama",
        "region_id": 1
    },
    "country_id": "US",
    "street": [
        "Green str, 67"
    ],
    "company": "CompanyName",
    "telephone": "3468676",
    "postcode": "75477",
    "city": "CityM",
    "firstname": "Franky",
    "lastname": "Smith",
    "default_shipping": true,
    "default_billing": true
    }
  ]
}
}

**Comment by daim2k5** [comment]
@arunkasyakar i close the issue because you didn't responded after 28 days. Please feel free to reopen the issue if you have still the problem.
