### ISSUE TITLE
catalogProductTierPriceManagementV1GetListGet 'all' option does not work

### ISSUE THREAD

**Issue by gibbotronic** [magento/magento2#24412]
Calls to catalogProductTierPriceManagementV1GetListGet with the documented 'all' option (eg. rest/V1/products/testingSKU/group-prices/all/tiers) does not work. It will return an empty array even if there is a valid tiered price for a product and customer group. This is wrong.

If you then proceed to explicitly request a tiered price for this product for a customer group that you *know* exists (eg. rest/V1/products/testingSKU/group-prices/0/tiers), it will return the expected values, eg.
```json
[
  {
    "customer_group_id": 0,
    "qty": 20,
    "value": 24
  }
]
```

Also, if you fetch the product's data, it'll return the tiered pricing information too (eg. rest/V1/products/testingSKU):
```json
"tier_prices": [
  {
    "customer_group_id": 0,
    "qty": 20,
    "value": 24,
    "extension_attributes": {
      "website_id": 0
    }
  }
]
```

But explicitly asking for all/tiers will *not* return the data even though it is visible by either of the other methods mentioned above (asking the product for all of its data, or asking for the customer group's data).

### Preconditions (*)

1. Magento 2.3.2
2. A product eg. sku 'testingSKU'
3. A customer group
4. The product mentioned in (2) should have tier prices for the customer group mentioned in (3)

### Steps to reproduce (*)

1. Make a GET request to catalogProductTierPriceManagementV1GetListGet, eg. rest/V1/products/testingSKU/group-prices/all/tiers

### Expected result (*)

1. The response should include the tiered price, eg.
```json
"tier_prices": [
  {
    "customer_group_id": 0,
    "qty": 20,
    "value": 24,
    "extension_attributes": {
      "website_id": 0
    }
  }
],
```

### Actual result (*)

1. It returns an empty set, eg.
```json
"tier_prices": [] 
```

**Comment by gibbotronic** [comment]
> @gibbotronic do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [x]  yes
> 
>     * [ ]  no

I can confirm that this occurs on vanilla 2.3.2

**Comment by engcom-Bravo** [comment]
Hello @gibbotronic. Thanks for applying. Please take a note at the following:
![api1](https://user-images.githubusercontent.com/51680745/64121975-0515e980-cda9-11e9-90f3-a8c3881a7ae5.png)
from the documentation and
![api2](https://user-images.githubusercontent.com/51680745/64121983-0ba46100-cda9-11e9-9bbf-9dccf1bdacc5.png)
from the tier pricing section of the Product in a Magento instance.
ALL here means not ANY. Adding "all" to the URL is responsible for displaying only those tiered prices assigned to ALL customer GROUPS. In Your scenario the tier price is assigned only to one of the groups. So the request correctly brings an empty result. Change Your assignment from the particular customer group to ALL GROUPS and You'll get that tier price in response.

**Comment by gibbotronic** [comment]
Ah ok. Thank you, that makes sense. Apologies for the confusion.

What customer_group_id should be used if I wish to create a tiered price for all groups?

**Comment by engcom-Bravo** [comment]
@gibbotronic, You are welcome. It looks somewhat weird but customer_group_id for all groups is 32000. If You send a request with 'all' as in Your Steps to Reproduce You shall get back info with customer_group_id: 32000. The same response shall be obtained once You send directly 32000 instead of "all". So by Your favor we are closing this issue now. Thank You for applying.
