### ISSUE TITLE
Magento\Framework\Stdlib\DateTime\Timezone -> appendTimeIfNeeded didn't check input

### ISSUE THREAD

**Issue by dbsdsun** [magento/magento2#24417]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1.Magento\Framework\Stdlib\DateTime\Timezone -> date('2018-04-12') 

### Expected result (*)

1. It should return 2018 April 12

### Actual result (*)

1. it returns a date as 2180 Feb. 4

### Problem (*)
These are two lines in function Magento\Framework\Stdlib\DateTime\Timezone -> date()

                $date = $this->appendTimeIfNeeded($date, $includeTime);
                $date = $formatter->parse($date) ?: (new \DateTime($date))->getTimestamp();

$date can not be parsed by  $formatter initially, after appendTimeIfNeeded, $date can be parsed but results a wrong outcome.

These are the function Magento\Framework\Stdlib\DateTime\Timezone -> appendTimeIfNeeded()

    private function appendTimeIfNeeded($date, $includeTime)
    {
        if ($includeTime && !preg_match('/\d{1}:\d{2}/', $date)) {
            $date .= " 0:00am";
        }
        return $date;
    }

Here, appendTimeIfNeeded did check if $date is a date, it just append " 0:00am", and that causes the problem.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19816` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento I am working on it.

**Comment by gabrieldagama** [comment]
Hi @dbsdsun, thanks for highlighting this issue, I believe the `date` function at moment supports just `\IntlDateFormatter::SHORT` format, referenced herehttps://www.php.net/manual/en/class.intldateformatter.php#intl.intldateformatter-constants .

That is not ideal, but it can be refactored and maybe accept more formats.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
