### ISSUE TITLE
How to add new module from magento connect

### ISSUE THREAD

**Issue by vimalbaisla** [magento/magento2#2442]
I am trying to add a module from magento connect .But got no option to connect please tell me.

**Comment by ghost** [comment]
Hi, I think you should use the Component Manager, which is part of the Magento 2 Admin. Let us know if this helps: http://devdocs.magento.com/guides/v2.0/comp-mgr/bk-compman-upgrade-guide.html

**Comment by MomotenkoNatalia** [comment]
@vimalbaisla I close the issue for now. If you have further question to this issue please feel free to reopen
