### ISSUE TITLE
Can't partially invoice orders with ship separately/together mixed bundles

### ISSUE THREAD

**Issue by kassner** [magento/magento2#24424]
### Preconditions

1. Magento Open Source 2.3.2;

### Steps to reproduce

1. Create a simple product with price $10.00;
2. Create a bundle with dynamic price and ship together as option:

![Screenshot_2019-09-03 Bundle (dynamic price, ship together) Products Inventory Catalog Magento Admin](https://user-images.githubusercontent.com/301255/64174453-9ba1e380-ce59-11e9-9a4a-48d43621804c.png)

3. Create a bundle with dynamic price and ship separately as option:

![Screenshot_2019-09-03 Bundle (dynamic price, ship separately) Products Inventory Catalog Magento Admin](https://user-images.githubusercontent.com/301255/64174468-9fce0100-ce59-11e9-9ad9-ebbeffd0ec0f.png)

4. Place an order (edit: happens both on *admin* and *frontend*) adding both bundles:

![Screenshot_2019-09-03 #000000001 Orders Operations Sales Magento Admin](https://user-images.githubusercontent.com/301255/64174476-a5c3e200-ce59-11e9-8f76-ece052376ef5.png)

5. Click the `Invoice` button.

### Expected result

1. Be able to choose either bundle to create a partial invoice.

### Actual result

1. The bundle with ship separately chosen isn't available to set the quantity. 

![Screenshot_2019-09-03 New Invoice Invoices Operations Sales Magento Admin](https://user-images.githubusercontent.com/301255/64174485-ab212c80-ce59-11e9-89ca-2764ad732b82.png)

**Comment by engcom-Bravo** [comment]
Hello @kassner. Thanks for applying. As You can see we've got Your Expected and not Your Actual result trying to reproduce the issue:
![bundle](https://user-images.githubusercontent.com/51680745/64177114-75834000-ce67-11e9-99bb-60d8e19ffbe1.png)
Could You please try to reproduce this issue on the latest 2.3-develop version as You are advised above:
![Advised](https://user-images.githubusercontent.com/51680745/64177198-ac595600-ce67-11e9-8f4d-1879199184ad.png)
Thank You.

**Comment by engcom-Bravo** [comment]
@kassner, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
