### ISSUE TITLE
Select from gallery option not working in theme design configuration

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24430]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.19
3. Installed magento in some directory for ex: http://example.com/magento 

### Steps to reproduce (*)

1. Navigate to backend-> Content -> Configuration
2. Edit any row
3. select image form gallery for "Header logo image" 
4. then save

### Expected result (*)

![expected-sv](https://user-images.githubusercontent.com/44425160/64226388-d7da5000-cefc-11e9-9082-b638d917ea24.png)

### Actual result (*)

![issue-sv](https://user-images.githubusercontent.com/44425160/64226395-de68c780-cefc-11e9-8a99-84d28ea3fcf5.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24430-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24430-2-3-develop.instances.magento-community.engineering/admin](https://i-24430-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have verified this issue in Default Magento 2.3 Instance. Image uploading functionality is working fine.
Please see attached the issue video:
![Image_Issue](https://user-images.githubusercontent.com/24711761/64227522-74065600-cf01-11e9-82a4-0b6972f20651.gif)

**Comment by rani-priya** [comment]
@ajijshekh123 please check preconditions "magento must be installed in some directory for ex: http://example.com/magento"

**Comment by ajijshekh123** [comment]
@rani-webkul - I understand your preconditions but when I have verified the issue in default Magento it will provide the only instance, not to the default Magento source code.
Can you please update me how to reproduce this issue in default Magento 2.3 instance?

**Comment by rani-priya** [comment]
@ajijshekh123 Install magento2.3-develop on your local system and then check.

**Comment by ajijshekh123** [comment]
@rani-webkul  Okay Let me check and update you.

**Comment by ajijshekh123** [comment]
@rani-webkul - I have verified this issue in my local Magento 2.3 instance but it's working fine on my end.

**Comment by rani-priya** [comment]
could you please let me know your magento base url?

**Comment by rani-priya** [comment]
@ajijshekh123 I have checked this issue again by installing magento2.3-develop. It's reproducible make sure your magento base url must be like https://example.com/magento not https://example.com

**Comment by rani-priya** [comment]
@ajijshekh123 any update?

**Comment by ajijshekh123** [comment]
@rani-webkul - I have to review your issue in my local directory but in your selected section 'select image form gallery' options are not displaying.
See my URL:
http://10.16.16.160/m/m23/admin

Can you please suggest me why this option are not displaying?

**Comment by rani-priya** [comment]
@ajijshekh123 somehow http://10.16.16.160/m/m23/admin is not accessible.

**Comment by ajijshekh123** [comment]
This is our local server URL, So it maybe you can not access this URL. 
@rani-webkul  Can you please send your URL which is you have reproduced the issue?

**Comment by rani-priya** [comment]
@ajijshekh123 I think you are checking this issue on old version. "select from gallery" option are introduced in magento 2.3.
Please verify. I'm also checking this issue on my local server which is not accessible to anyone.

**Comment by ajijshekh123** [comment]
Sorry @rani-webkul, I don't have Latest Magento instance in my local directory.

**Comment by magento-engcom-team** [comment]
@rani-webkul Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20082` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24431 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [6b8c7eeae020a2c11f44e9237b1213ec8993a95b](https://github.com/magento/magento2/commit/6b8c7eeae020a2c11f44e9237b1213ec8993a95b)
 - [d8e82332ccc4309480e6d9f65c17eed0679a5afd](https://github.com/magento/magento2/commit/d8e82332ccc4309480e6d9f65c17eed0679a5afd)

The fix will be available with the upcoming 2.3.4 release.
