### ISSUE TITLE
Email content is empty only subject is showing on email ?

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [magento/magento2#24432]
### Preconditions (*)

1.Using Magento 2.3.1

### Steps to reproduce (*)

1.While sending email when customer register,order email,when admin send order via email

### Expected result (*)

1. Mail will be subject with content

### Actual result (*)

1. Mail is coming only with subject but content is empty.

**Comment by engcom-Bravo** [comment]
Hello @sumeetmobiwebtech. It may be caused by, for example, custom theme or any other custom code. Would You please try to reproduce Your issue on a fresh vanilla installation of 2.3-develop version. Thank You.

**Comment by sumeetmobiwebtech** [comment]
yes i override this
` <preference for="Magento\Framework\Mail\Message" type="CompanyName\ModuleName\Mail\Message"/>`
because of custom PDF attachment when i remove this,now mail is working properly
