### ISSUE TITLE
Magento 2.3.2 review module not working

### ISSUE THREAD

**Issue by divyeshmehta820** [magento/magento2#24435]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by krishprakash** [comment]
Hi @divyeshmehta820.
Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Fill all the require details for reproduce the issue
Thanks.

**Comment by krishprakash** [comment]
Hi @divyeshmehta820.
Feel free to reopen the issue with all details and also you can confirm that its reproducible on Vanilla Magento instance.
Thank you.
