### ISSUE TITLE
Autogenerating encryption key requires manually entering the key

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#24436]
### Preconditions (*)

1. Magento 2.3-dev
2.

### Steps to reproduce (*)
1. Navigate to `System / Manage Encryption Key`
2. Select `Yes` for `Auto-generate a Key`

### Expected result (*)

1. The `New Key` field should be hidden
2. You should be able to save the encryption key

### Actual result (*)

1. The `New Key` isn't hidden
2. And you aren't able to save it
![image](https://user-images.githubusercontent.com/15868188/64235867-ed9e4400-cf01-11e9-97d6-b96fa8ebc287.png)

**Comment by Leandry** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leandry. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leandry, here is your [Magento instance](https://i-24436-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24436-2-3-develop.instances.magento-community.engineering/admin](https://i-24436-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Leandry** [comment]
@eduard13 Thank you for reporting. I can confirm that issue reproduced on the vanilla environment.
![2019-09-04_11-00-14](https://user-images.githubusercontent.com/9416636/64236727-ad3fc580-cf03-11e9-9527-ecad05dc07c6.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19842` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#24437 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [c413b69322f3793313e899df210219a474f0d284](https://github.com/magento/magento2/commit/c413b69322f3793313e899df210219a474f0d284)

The fix will be available with the upcoming 2.3.4 release.
