### ISSUE TITLE
Magento 2.2.6: minicart still show value(count of products) after clear cart

### ISSUE THREAD

**Issue by DenisFaltsman** [magento/magento2#24439]
After clear(removing all products) shopping cart shows nothing, but still show count of products value on minicart.

tried to create sections.xml and flush cart after click 'distribution/cart/clear' route:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Customer:etc/sections.xsd">
    <action name="distribution/cart/clear">
        <section name="cart"/>
        <section name="checkout-data"/>
    </action>
</config>
```

and have no success. anyone knows? or maybe this issue already solved?

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24439-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24439-2-3-develop.instances.magento-community.engineering/admin](https://i-24439-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @DenisFaltsman.
Issue is already fixed in latest magento version.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Thank you.
