### ISSUE TITLE
After login the back end its not redirect properly?

### ISSUE THREAD

**Issue by ramsampathi** [magento/magento2#2444]
Hi,
After some time login the admin panel its not loggin.

hoe to resolve this issue?
![screenshot_4](https://cloud.githubusercontent.com/assets/7812791/11297617/b18cc7d4-8f9f-11e5-8477-9397ac5b5c81.png)

**Comment by mazhalai** [comment]
@ramsampathi can you please provide details of what server you are using? It is possibly a server setting issue.

**Comment by MomotenkoNatalia** [comment]
@ramsampathi Do you have any updates?

**Comment by MomotenkoNatalia** [comment]
@ramsampathi  Please feel free to reopen the issue if you have still the problem.
