### ISSUE TITLE
Scope icon and store view specific label text alignment issue

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#24440]
Scope icon and store view specific label text alignment issue

### Preconditions (*)
Magento 2.3.2

### Steps to reproduce (*)
1. Admin -> Store -> Settings ->  Order status -> Create new status

### Expected result (*)
Store View Specific Labels and scope (?) should aligned properly

### Actual result (*)
![actual](https://user-images.githubusercontent.com/49804008/64247798-3cad9e80-cf2d-11e9-9f31-03e7314c1e4b.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24440-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24440-2-3-develop.instances.magento-community.engineering/admin](https://i-24440-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19845` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hi @bhavik43
There is no any mismatch issue occur on latest venilla magento instance.
But issue in Store View Specific Labels and (?) not in same line.
![image](https://user-images.githubusercontent.com/46617848/64248520-f1948b00-cf2e-11e9-8300-7e2ded57ba26.png)

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#24449 by @edenduong in 2.3-develop branch
Related commit(s):
 - [4314d4b10baf74219c1caa8554a4fec50fba7191](https://github.com/magento/magento2/commit/4314d4b10baf74219c1caa8554a4fec50fba7191)

The fix will be available with the upcoming 2.3.4 release.
