### ISSUE TITLE
Minicart height calculated incorrectly when child items contain margins

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#24441]
### Preconditions (*)
1. magento 2.3-develop

### Steps to reproduce (*)
1. Deploy 2.3-develop
2. Create Test product and add to cart
3. View minicart
4. Open browser development tools
5. Locate the line
`<li class="item product product-item" data-role="product-item">`
6. In the style explorer locate the css item 
`.minicart-items .product-item`
7. Add the style
`padding-bottom: 100px !important;`
8. Close and reopen minicart to force reevaluation of height
9. Notice that the minicart height is correctly calculated and there is a padding of 100px in the minicart.
![image](https://user-images.githubusercontent.com/30697781/64247636-2b519b80-cf07-11e9-994b-3c0e321afd11.png)
10. Remove the style
`padding-bottom: 100px !important;`
11. Add the style 
`margin-bottom: 100px !important;`
12. Close and reopen minicart to force reevaluation of height

### Expected result (*)
1. minicart height is correctly calculated.

### Actual result (*)
1. minicart height is not correctly calculated.
2. Scroll bar appears in minicart
![image](https://user-images.githubusercontent.com/30697781/64247702-550ac280-cf07-11e9-977a-b5024eb17b17.png)

When padding is used in the product-item list item the minicart calculated height correctly, but does not when margins are used.

**Comment by gwharton** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gwharton, here is your [Magento instance](https://i-24441-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24441-2-3-develop.instances.magento-community.engineering/admin](https://i-24441-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gwharton** [comment]
Confirmed produced on test instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19847` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#24451 by @konarshankar07 in 2.3-develop branch
Related commit(s):
 - [25a90fbf6befadd85b093d0df9cf804112e9a7ce](https://github.com/magento/magento2/commit/25a90fbf6befadd85b093d0df9cf804112e9a7ce)

The fix will be available with the upcoming 2.3.4 release.
