### ISSUE TITLE
category "uscator de par" is missing, and can not add it

### ISSUE THREAD

**Issue by Cristishor201** [magento/magento2#24444]
I can not find settings or they did not exist for adding a new sub-category at the list.

**Comment by engcom-Bravo** [comment]
Hello @Cristishor201, thanks for applying. I'm not quite sure I understand You right, but probably this gif will help You to find the answer:
![categories](https://user-images.githubusercontent.com/51680745/64255824-d4f65400-cf2a-11e9-846c-f5295b5e02d2.gif)

**Comment by engcom-Bravo** [comment]
@Cristishor201, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
