### ISSUE TITLE
First time wysiwyg image is loaded by media storage, placeholder image is shown

### ISSUE THREAD

**Issue by lpouwelse** [magento/magento2#24446]
### Preconditions (*)
1. Magento version 2.3.1

### Steps to reproduce (*)
1. Fresh install of magento with sample data
2. Synchronize media files to datase, according the manual (https://docs.magento.com/m2/ce/user_guide/system/media-storage-database.html)
3. Add following record to core_config_data table 
    - scope: default
    - scope_id: 0 
    - path: web/seo/use_rewrites
    - value: 1
4. Remove an image from media/wysiwyg editor directory (so the get.php is called)
5. Load image by browser, placeholder image is shown

### Expected result (*)

1. Real image is shown

### Actual result (*)

1. Image is resized by ImageResizer for products wich not compatible for  wysiwyg images

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19879` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
Hi @lpouwelse,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2/issues/24442#issuecomment-1465980982. we are closing this issue.

Thanks.
