### ISSUE TITLE
Magento_Swatches modules failing on fresh install 

### ISSUE THREAD

**Issue by realdigid** [magento/magento2#2445]
I get the console error below upon doing a fresh install on develop or master branch. Setting it up on local env, on Mac OSX Yosemite 10.10.5 using latest MAMP stack. 

Module 'Magento_Swatches':
Installing data.. 
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Wrong attribute group ID' in /Users/jamesjones/Projects/magento2/app/code/Magento/Eav/Setup/EavSetup.php:622
Stack trace:
#0 /Users/jamesjones/Projects/magento2/app/code/Magento/Eav/Setup/EavSetup.php(1200): Magento\Eav\Setup\EavSetup->getAttributeGroupId('4', '13', 'General')
#1 /Users/jamesjones/Projects/magento2/app/code/Magento/Eav/Setup/EavSetup.php(799): Magento\Eav\Setup\EavSetup->addAttributeToSet('4', '13', 'General', 'swatch_image', 3)
#2 /Users/jamesjones/Projects/magento2/app/code/Magento/Swatches/Setup/InstallData.php(66): Magento\Eav\Setup\EavSetup->addAttribute('catalog_product', 'swatch_image', Array)
#3 /Users/jamesjones/Projects/magento2/setup/src/Magento/Setup/Model/Installer.php(798): Magento\Swatches\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#4 /Users/jamesjones/Projects/magento2/setup/src/Magento/Setup/Model/Installer.php(746): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#5 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#6 /Users/jamesjones/Projects/magento2/setup/src/Magento/Setup/Model/Installer.php(331): call_user_func_array(Array, Array)
#7 /Users/jamesjones/Projects/magento2/setup/src/Magento/Setup/Controller/Install.php(97): Magento\Setup\Model\Installer->install(Array)
#8 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /Users/jamesjones/Projects/magento2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /Users/jamesjones/Projects/magento2/setup/index.php(31): Zend\Mvc\Application->run()
#19 {main}

**Comment by realdigid** [comment]
This issue seems intermittent, as my install works now. Most likely it was the result of the database being used on a previous install that wasn't successful. I would recommend sanitizing the database prior to a fresh install, or atleast throwing a warning that a previous installation was found for that db. I'd love to contribute, and add this enhancement.

**Comment by mazhalai** [comment]
@realdigid thank you for your followup. Can you please clarify if your installed via CLI or Web Setup? 

Please feel free to contribute via a PR. Contributing guidelines can be found [here](http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html).

Closing this issue since it has been resolved.

**Comment by realdigid** [comment]
Web Setup
