### ISSUE TITLE
Import History Grid Rendering Empty HTML tag, when there is no import file name.

### ISSUE THREAD

**Issue by AkhilaKandisetty** [magento/magento2#24456]
### Preconditions (*)

1.Go to Admin , navigate to System > Import History
2.When you inspect <td> in Imported File column, you can find empty paragraph tag,when there is no imported   file name which is not as per standards.

### Steps to reproduce (*)

1.In admin navigate to System > Import History.
2.The default column has an empty paragraph tag.

### Expected result (*)

1.When there is no file name, empty paragraph tag should not be there.

### Actual result (*)

1. ![Empty tag](https://user-images.githubusercontent.com/54110310/64315841-c95d6880-cfd0-11e9-9c17-c222951e1b2b.png)
2. Empty paragraph tag is rendered when there is no file name.

**Comment by engcom-Bravo** [comment]
Hello @AkhilaKandisetty. Would You please guide Us how exactly You managed to obtain a row in Import History table without the imported  file name in it. Thank You.

**Comment by AkhilaKandisetty** [comment]
This row was there by default in admin Import History even before adding any import file.Thank you.

**Comment by engcom-Bravo** [comment]
@AkhilaKandisetty, we didn't notice such a behavior. Would You please try to reproduce Your issue on a clear instance as You are advised above:
![Advised](https://user-images.githubusercontent.com/51680745/64320760-e2ade700-cfc7-11e9-916e-be5af970fe3e.png)
Thank You.

**Comment by AkhilaKandisetty** [comment]
@magento-engcom-team  give me 2.3-develop instance

**Comment by engcom-Bravo** [comment]
@AkhilaKandisetty, sorry the comment has changed. This should prepare an instance for You. @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-24456-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24456-2-3-develop.instances.magento-community.engineering/admin](https://i-24456-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AkhilaKandisetty** [comment]
@engcom-Bravo Sorry I couldn't reproduce the issue in the vanilla instance.
Thanks for the support. Closing this issue.

**Comment by engcom-Bravo** [comment]
@AkhilaKandisetty, You are welcome.
