### ISSUE TITLE
ProductAlert is redirecting to 404 when customer is not logged.

### ISSUE THREAD

**Issue by igor-imaginemage** [magento/magento2#24454]
Hi, this is an issue that I reproduced today in 2 of our customers that are running Magento 2.3.2 and also in a vanilla Magento installation.

Magento has a core module **Magento_ProductAlert** that allow us to enable links to customers subscribe when a product is back in stock and also when price goes down (https://docs.magento.com/m2/ce/user_guide/catalog/inventory-product-alerts.html).

This module stores the customer_id when a customer subscribes, so, they have to be logged to proceed with this action. If a customer isn't logged Magento will show the login page and after the customer is logged, he/she will be redirected to the product page, with a message saying he/she was subscribed to be notified when the product come back in stock or when the price goes down (Depending of which link he/she is using).

### Preconditions (*)
- Magento 2.3.2 (Open Source or Commerce)
- Out of stock products visible in the frontend (https://prnt.sc/p1vi3t)
- "Allow Alert When Product Comes Back in Stock" or "Allow Alert When Product Price Changes" enabled (https://prnt.sc/p1vhzq).
- An out of stock product.

### Steps to reproduce (*)
Test scenario 1:
- Access the out of stock product in the storefront as a guest customer (not logged).
- Click in the "Notify me when this product is in stock" link (https://prnt.sc/p1viun).
- Provide your correct customer credentials and submit the form.

Test scenario 2:
- Access the out of stock product in the storefront as a guest customer (not logged).
- Click in the "Notify me when this product is in stock" link (https://prnt.sc/p1viun).
- Provide incorrect customer credentials and submit the form.

### Expected result (*)
- Be redirected to the product page with the appropriate message, a message saying the customer was subscribed to be notified (scenario 1), a message saying the provided credentials are incorrect (scenario 2).

### Actual result (*)
- The customer is redirect to a 404 page (https://prnt.sc/p1vkvh).

This is happening on Magento 2.3.2, I tried on Magento 2.2 but I wasn't able to reproduce same issue.

I created a Pull Request fixing this problem -> https://github.com/magento/magento2/pull/24453

**Comment by engcom-Bravo** [comment]
Hello @igor-imaginemage. Thanks for reporting, but this issue has already been fixed. You may try to reproduce it on 2.3-develop version - it is reproduced no more. So we are supposed to close this issue, but please feel free to reopen it if You find the way to reproduce it on the latest develop version.

**Comment by igor-imaginemage** [comment]
Yes, I confirm this was fixed on 2.3-develop.
