### ISSUE TITLE
Category Admin UI does not save tree changes unless OK button is clicked 

### ISSUE THREAD

**Issue by hutbert** [magento/magento2#24452]
### Preconditions

Magento 2.3.1

In Magento 2.3.1 when you change the structure of the category tree a warning dialog appears to confirm your changes and warn that the operation may take a long time. If you click the OK button with a mouse click the change is saved properly. If you use the enter button on the keyboard, the change is reflected in the UI but is not saved to the database so when you refresh the page your changes are lost. 

### Steps to reproduce
- Navigate to Catalog -> Categories 
- Drag a category to a different location in the tree
- When the warning dialog appears **hit enter on the keyboard**
- Note that a **no** spinner appears and changes are **not** saved 
- refresh the page and see that your changes were not saved. 

### Expected result
Changes to the structure should be saved 

### Actual result
Changes are not saved 

NOTE that clicking the OK button works properly. This only happens when using the enter key instead.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19876` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-24452-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24452-2-3-develop.instances.magento-community.engineering/admin](https://i-24452-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
