### ISSUE TITLE
Gallery is not updated when pre-selecting a configurable product that uses dropdown-input

### ISSUE THREAD

**Issue by dugunl** [magento/magento2#24450]
### Preconditions (*)
Magento 2.3.1

### Steps to reproduce (*)

1. Create a new attribute
- Set "Catalog Input Type for Store Owner" to Dropdown
- Set "Scope" to Global.
- Add at least one option to the attribute.

2. Create a new configurable product and add new configurations to the product, based on the attribute you've just created.

3. Upload photo A to the actual configurable product.

4. Upload photo B to the simple product (= the new configuration you just created in step 2).

5. Go to the product page and verify Magento loads the image B when you're selecting the configuration.

6. In a new tab, load the product page again, but with the pre-selected options this time. Example: https://magento.app/sample-product.html#89=1245

 
### Expected result (*)
The gallery should be updating, and display photo B instead of the default photo A.

### Actual result (*)
In reality, it's still stuck on photo A.

For some reason, it's only doing this to configurable products with a Dropdown-input.
It's updating just fine with Visual Swatches (= https://i.imgur.com/LEjZY99.png).
It also doesn't work on configurations that use a combination of Dropdown + Visual Swatches.

**Comment by dugunl** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dugnl. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dugnl, here is your [Magento instance](https://i-24450-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24450-2-3-develop.instances.magento-community.engineering/admin](https://i-24450-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dugunl** [comment]
> @dugnl do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

Yes, I can confirm. I've tried it on my own clean installation, but also on your instance in a previous ticket.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19864` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dynamicswebkul** [comment]
@magento i am working on it.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul, here is your [Magento instance](https://i-24450-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24450-2-3-develop.instances.magento-community.engineering/admin](https://i-24450-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by arushibansal013** [comment]
Hi @dugnl,

The issue is not reproducible, i tried the steps suggested by you. And found that images are coming correctly. For an associated/child product its changing as expected.

You can check once with Magento dev instance, and open the issue again at any instance.
