### ISSUE TITLE
Export Coupon Code Grid redirect to DashBoard when create New Cart Price Rule

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24468]
Coupon Grid in create new "Cart Price Rule" should be disabled. Because it is useless and when exporting, it has the error: 

### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Marketing-> Cart Price Rules, Create New Cart Price Rule
3. In " Coupon" choose Specific Coupon
4. Check "Use Auto Generation"
5. Scroll to Manage Coupon Codes
6. Export

### Expected result (*)

1. I think Should be disable the Grid, because in the New Cart Price Rule, there is No Coupon Code what is generated

### Actual result (*)

1. Redirect to dashboard
2.
![image](https://user-images.githubusercontent.com/8234209/64354464-b2973000-d029-11e9-90ca-00b5b3c21236.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24468-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24468-2-3-develop.instances.magento-community.engineering/admin](https://i-24468-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@edenduong - I have verified this issue in Magento 2.3 Instance. Please see attached the video:
![Magento Issue](https://user-images.githubusercontent.com/24711761/64401710-c2495f80-d08f-11e9-904e-eae92630e244.gif)

Please let me know if any issue missing in my side. Currently, I don't have to reproduce this issue.

**Comment by edenduong** [comment]
@ajijshekh123 : Please Check **"Use Auto Generation"** -> after that,  Scroll to Manage Coupon Codes , Export the Coupon Grid

**Comment by ajijshekh123** [comment]
@edenduong - It displays the '404 Error', Functionality should be working as expected result.
**See screenshot:**
![2019-09-06](https://user-images.githubusercontent.com/24711761/64403627-e9eff600-d096-11e9-99c5-694446843f87.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19907` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@ajijshekh123: Yes. Because in this Magento instance, it disable the form key, so 404 error. If the form key is enabled , the error "Redirect to the dashboard" will happen.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19907` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by soniaandrianow** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
@soniaandrianow thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by VladimirZaets** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24471 by @edenduong in 2.4-develop branch
Related commit(s):
 - [5d175a35f9b4f91fe94abe7dceb5155cb4fc54c3](https://github.com/magento/magento2/commit/5d175a35f9b4f91fe94abe7dceb5155cb4fc54c3)
 - [853a1e58107d7b9f95b6e0cf07df9b81fe2dabd3](https://github.com/magento/magento2/commit/853a1e58107d7b9f95b6e0cf07df9b81fe2dabd3)

The fix will be available with the upcoming 2.4.0 release.
