### ISSUE TITLE
cant upload logo & favicon on magento 2.3.2 

### ISSUE THREAD

**Issue by faraimupfuti** [magento/magento2#24469]
**Summary of the issue,**
- i am struggling to upload logo and favicon on my localhost magento 2.3.2 

**Information on your environment,**
- i am currently using xampp running on php 7.2 , windows 7

I went straight to the **design_config_form** file and the below lines have the correct formElement values (ImageUploader). eg **field name="head_shortcut_icon" formElement="imageUploader"** AND **field name="header_logo_src" formElement="imageUploader"**

I need assistance on how i can upload logo and favicon onto my site.

**Comment by faraimupfuti** [comment]
**Summary of the issue**
- Cannot upload logo on magento 2.3.2

 **Information on your environment**
- WampServer Version 3.1.9 64bit
-Apache 2.4.39
- PHP 7.2
- MYSQL 5.7.26
- localhost
- windows 7

 **Steps to reproduce**
Magento Admin panel -> content -> configuration ->  Luma Theme edit -> Header -> select logo

 **Expected and actual results**
_"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."_

The above error is what appears

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24469-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24469-2-3-develop.instances.magento-community.engineering/admin](https://i-24469-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @faraimupfuti 
thank you for you report , It seems this issue is already fixed on the 2.3-develop branch 
you can check commit ba69bfec127bed8c39c7d9e7b73d10b54449b158
