### ISSUE TITLE
Paypal standard payments labeled as " PayPal Express Checkout"

### ISSUE THREAD

**Issue by rydemods** [magento/magento2#2447]
magento 2.0 admin > Paypal Website Payments Standard >  configure settings > 
The checkout shows   'PayPal Express Checkout'  - when its just standard.

**Comment by asemenenko** [comment]
@rydemods 

Its a little bit complicated than it looks like :-) 

PayPal offers two solutions - PayPal Standard and PayPal Payments Pro, see https://www.paypal.com/webapps/mpp/compare-business-products

The main difference between those two is the fact that Pro allows to accept credit card using your own checkout pages, while Standard offers PayPal payments.

To accept PayPal payments we can use either Standard API or Express Checkout API. This is where the confusion starts. The Express Checkout API offers more reliable integration from technical point of view with more flexible checkout flow that merchant can configure. Standard API allows only the flow were customer confirms payment on PayPal side only. The difference between those described here: https://www.paypal.com/au/cgi-bin/webscr?cmd=_additional-payment-ref-impl1

**Comment by rydemods** [comment]
@asemenenko  thanks for the explanation on how Paypal works - which by the way if not correct for all countries.

Any way what i'm referring to is on the checkout it should not say "Paypal Express Checkout"  when only its not. Just Standard. thanks

**Comment by asemenenko** [comment]
This is a legacy\marketing thing, while it may sound confusing customers that are looking for a "Standard" solution after looking at https://www.paypal.com/us/webapps/mpp/compare-business-products will find it in the configuration settings. Both "Standard" and "Pro" include PayPal payments that in our case implemented via PayPal Express Checkout API
