### ISSUE TITLE
Error occured when creating new page and entering configurations in magento 2.3.2

### ISSUE THREAD

**Issue by Ashnetn** [magento/magento2#24473]
### Summary (*)
Unable to unserialize value. Error: Control character error, possibly incorrectly encoded

### Examples (*)
Error log record number: 873206708532

**Comment by Ashnetn** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @Ashnetn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Ashnetn, here is your [Magento instance](https://i-24473-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24473-2-3-develop.instances.magento-community.engineering/admin](https://i-24473-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Ashnetn** [comment]
vanilla magento instance is not showing any error at all

**Comment by shikhamis11** [comment]
hi @Ashnetn 
Thank you for your report . 
can you explain more about the issue you are facing ,with current description of issue I am not able to understand the issue .

**Comment by shikhamis11** [comment]
hello @Ashnetn 
Please update the description and message here to reopen the issue
