### ISSUE TITLE
sitemap image URLs has wrong cache path

### ISSUE THREAD

**Issue by bst2002git** [magento/magento2#24484]
I've search into the database for the cache (ID) path and onto the filesystem,
but ID 3e7668b51c2d31ea41d3695bfbe7fa89 is not found

### Preconditions (*)
Magento ver. 2.3.2 & 2.3-develop
 
### Steps to reproduce (*)
Create sitemap.xml File 

### Expected result (*)
https://shop.local/pub/media/catalog/product/cache/394c582e6ac26a409e94a110e9356eac/1/1/1125.main_1.jpg

### Actual result (*)
<url>
	<loc>https://shop.local/de_at/product-test.html</loc>
	<lastmod>2019-04-12T09:07:15+02:00</lastmod>
	<changefreq>daily</changefreq>
	<priority>1.0</priority>
	<image:image>
		<image:loc>https://shop.local/pub/media/catalog/product/cache/3e7668b51c2d31ea41d3695bfbe7fa89/1/1/1125.main_1.jpg</image:loc>
		<image:title>Product Test</image:title>
	</image:image>
	<image:image>
		<image:loc>https://shop.local/pub/media/catalog/product/cache/3e7668b51c2d31ea41d3695bfbe7fa89/1/1/1125.aw06.jpg</image:loc>
		<image:title>Product Test</image:title>
	</image:image>
	<PageMap xmlns="http://www.google.com/schemas/sitemap-pagemap/1.0">
		<DataObject type="thumbnail">
			<Attribute name="name" value="Product Test"/>
			<Attribute name="src" value="https://shop.local/pub/media/catalog/product/cache/3e7668b51c2d31ea41d3695bfbe7fa89/1/1/1125.main_1.jpg"/>
		</DataObject>
	</PageMap>
</url>

**Comment by bst2002git** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @bst2002git. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bst2002git, here is your [Magento instance](https://i-24484-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24484-2-3-develop.instances.magento-community.engineering/admin](https://i-24484-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bst2002git** [comment]
Reproduced on 2.3.x

Image Path in sitemap.xml:
https://i-24484-2-3-develop.instances.magento-community.engineering/pub/media/catalog/product/cache/209978c07816454757b5fa037e09ce14/w/t/wt09-white_main.jpg

Image included in website:
https://i-24484-2-3-develop.instances.magento-community.engineering/pub/media/catalog/product/cache/1d7f890985ae0797e578c8c1324cec15/w/t/wt09-white_main.jpg

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19910` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento i am working on it.

**Comment by krisdante** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
Hi @bst2002git. Thank you for your report. 
The issue has been fixed in magento/magento2#24605 by @krisdante in 2.3-develop branch
Related commit(s):
 - [6ab019b21eb90d9ebe119d8777a111a4b88bfad8](https://github.com/magento/magento2/commit/6ab019b21eb90d9ebe119d8777a111a4b88bfad8)
 - [b7059a615b59b673690f0f3d8187f684213fc72d](https://github.com/magento/magento2/commit/b7059a615b59b673690f0f3d8187f684213fc72d)
 - [861e9f9401dd7845a77e63fb6cddd5359064c027](https://github.com/magento/magento2/commit/861e9f9401dd7845a77e63fb6cddd5359064c027)

The fix will be available with the upcoming 2.3.4 release.

**Comment by simon-saurabh** [comment]
@krisdante Do we need to do anything else other than implementing the above 3 commits as I have applied all 3 commits and the image issue with sitemap is still there for me. It is still taking the Magento placeholder image. Also, my Magento version is 2.3.2 and the above patch is not working for me.

**Comment by krisdante** [comment]
How do you create a sitemap ? With cron on manually in admin pannel?

**Comment by krisdante** [comment]
It is strange that it takes placeholder image. It was generating wrong checksum - so the file was de-facto not existing (404) not placeholder.

**Comment by simon-saurabh** [comment]
@krisdante we are generating the sitemap.xml from the Magento Admin and yes you are right that it is generating the wrong checksum, as I had removed the cache path from the image URL to see the product image exist on the path then it is showing me the correct product image. 

For eg- this is the image URL in the sitemap.xml (http://abc.com/media/catalog/product/cache/8b5174bff07af2e5e6c6a9fb70572a9b/3/-/3-30-521-2_c.jpg) which is giving me placeholder image and if I am trying this (http://abc.com/media/catalog/product/3/-/3-30-521-2_c.jpg) then it is showing me the correct image. 

So do you have any idea how to fix this issue?
Thanks in advance.

**Comment by simon-saurabh** [comment]
@krisdante We have debugged it further and found out that only for Sitemap, we have `image_type` param inside MiscParams array that are set there as blank on file vendor/magento/module-catalog/Model/View/Asset/Image.php on the constructor. 
But if we are unsetting the blank `image_type` param from the miscParams then the image path is coming correctly. I mean it is generating the correct checksum. Do you know why it is happening?

**Comment by krisdante** [comment]
If they are blank it means that you do not have patch (emulation is not worked). It is the situation that was before the patch

**Comment by simon-saurabh** [comment]
@krisdante But my magento version is 2.3.2 which is the latest version so why the patch is required?

**Comment by krisdante** [comment]
Because it is merged to 2.3.4

**Comment by simon-saurabh** [comment]
@krisdante ok so can you please provide me the commit id on which the fix is implemented?

**Comment by krisdante** [comment]
It's like 4 messages up.
https://github.com/magento/magento2/commit/861e9f9401dd7845a77e63fb6cddd5359064c027

**Comment by simon-saurabh** [comment]
@krisdante But I have already tried the above but still having issues with checksum on the cached URL of the image on the sitemap xml

**Comment by krisdante** [comment]
If the checksum did not change - seems that you have not applied the patch correctly.
If it changed than it needs to be checked in settings of your current theme if you have the big image defined properly.

**Comment by krisdante** [comment]
product_page_image_large this image type needs to be defined.

**Comment by simon-saurabh** [comment]
@krisdante Thanks for the help, the above hint fix the issue for me as I have only created view.xml for frontend theme and I was specifying product_page_image_large  param there but there was no view.xml for backend and thats why setting was coming as blank for sitemap.xml as I was generating it from backend.

**Comment by krisdante** [comment]
You miss-understood me, and that also confirms that you did not apply patch properly. 
The pach reads this setting from frontend. It is good that this setting is not set for backend. THet's teh whole fix - settings age read from frontend view.xml.

**Comment by johncarlson21** [comment]
could you please tell me what the proper product_page_image_large params should be set to. I have it in my view.xml file but like this:

<image id="product_page_image_large" type="image"/>

and I'm running 2.3.4 and the patch changes are there.

**Comment by magento-quality-patches** [comment]
The patch solving a similar issue is available in [Magento Quality Patches](https://support.magento.com/hc/en-us/articles/360047139492) package (MQP)
 
**Patch**
MDVA-30357: Fixes the issue with wrong image URLs are created when generating a sitemap by cron.
 
**Compatible versions**
Magento OpenSource/Commerce/Commerce Cloud 2.3.2 - 2.4.0
 
:warning: We strongly recommend testing all patches in a staging or development environment before deploying to production.
 
**Applying a patch - Magento OpenSource/Commerce**
 
1. `$ composer require magento/quality-patches`
2. `$ ./vendor/bin/magento-patches apply MDVA-30357`
 
See [MQP Magento Commerce documentation](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/mqp.html)
 
**Applying a patch - Magento Commerce Cloud**
See [MQP Magento Commerce Cloud documentation](https://devdocs.magento.com/cloud/project/project-patch.html)
 
**Patch Details**
https://support.magento.com/hc/en-us/articles/360050277772
