### ISSUE TITLE
Performance degradation using plugins

### ISSUE THREAD

**Issue by Andreabont** [magento/magento2#24487]
## Summary
Hi,

We developed a job that massively create orders, and we had to change the behavior of the core for these orders, so we chose to use the plugin system.

But we had experience a strange performance degradation related to the duration of the job: the speed gradually slow down.

We had try to re-implement the modification with an extension of the core class and a preference statement in di.xml, and the performance degradation disappears.

I hope that our experience may be useful.

Thank you

### Versions in use
- Magento 2.2.6
- MySQL 5.6.27

### Examples

Here the charts of the time to make an order in seconds (y-axis) in relation of the order number (x-axis)

**Plugin version**
![before](https://user-images.githubusercontent.com/1214106/64427248-0b5ddb80-d0b1-11e9-8233-df0b65a61791.png)

**Rewrite version**
![after](https://user-images.githubusercontent.com/1214106/64427244-07ca5480-d0b1-11e9-8dbd-39e8cf3713f4.png)

**Comment by gaurangpadhiyar007** [comment]
:+1:

**Comment by engcom-Charlie** [comment]
Hello @sdzhepa !
This issue looks like a feature request.
Can you transfer this issue to the feature requests repository?

**Comment by sdzhepa** [comment]
Hello @Andreabont 

Could you please provide more details, such as:
1. Is it actual for the latest code-base `2.3`
2. What Magento mode did you use develop/production?
3. What type of plugin did you use after/before or around?

**Comment by sdzhepa** [comment]
Hello @Andreabont 

Any updates? 
We need more details to Confirm this issue
