### ISSUE TITLE
Country code coming empty during checkout

### ISSUE THREAD

**Issue by sufyaniksula** [magento/magento2#24486]
### Preconditions (*)

1. Install Magento version 2.1.8

### Steps to reproduce (*)

1. Select United Arab Emirates as default country
2. Select Saudi Arabia and  United Arab Emirates as allowed countries
3. Register a new user
4. Go to checkout and select a payment method to place an order

### Expected result (*)

1. Order successfully placed

### Actual result (*)

1. Error message comes as "An error occurred on the server. Please try to place the order again".

On printing the actual exception message, error message comes as "Please correct the country code". This message comes from 

> vendor/magento/module-directory/Model/ResourceModel/Country.php

The code is passed in the function:

`public function loadByCode(\Magento\Directory\Model\Country $country, $code)`

The $code being passed here comes empty during checkout.

**Comment by engcom-Bravo** [comment]
Hello @sufyaniksula, Thanks for applying. Probably this issue has already been fixed in later versions as we can not reproduce it on 2.3-develop version:
![uae](https://user-images.githubusercontent.com/51680745/64430569-34866800-d0c1-11e9-9f44-93459cf49eb4.gif)
Or probably we do miss something when trying to reproduce it? Also would you please try to reproduce it Your self on 2.3-develop version and tell us the result. Thank You.

**Comment by ryandiamond23** [comment]
@magento give me 2.1.18 instance

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by ryandiamond23** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23, here is your [Magento instance](https://i-24486-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24486-2-3-2.instances.magento-community.engineering/admin](https://i-24486-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
@sufyaniksula, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
