### ISSUE TITLE
Rest API error 401 authorization required in magento2 ?

### ISSUE THREAD

**Issue by devidas-magento** [magento/magento2#24480]
I am trying to use the Magento 2.3 Rest API, using token authorization. when I try to GET data back from one of the endpoints using the token in an Authorization Bearer heading, I get an HTTP 401 Basic Authentication error. The problem is that the server requires Basic Authentication. In my local project API is working but live site not work API.

### Expected result
All category related array

### Actual result
```
<html>
    <head>
        <title>401 Authorization Required</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>401 Authorization Required</h1>
        </center>
        <hr>
        <center>nginx/1.14.0 (Ubuntu)</center>
    </body>
</html>
```

**Comment by engcom-Charlie** [comment]
Hello @devidas-magento ! We can not reproduce this issue follow steps that you provide.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
