### ISSUE TITLE
Truncated Values when Indexing Product Attribute as "Multiselect" & Backend Type "Text"

### ISSUE THREAD

**Issue by llapgoch** [magento/magento2#24488]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Create an attribute programatically of backend type text and type multiselect, visible in product listing;

```
$eavSetup->addAttribute(
                Product::ENTITY,
                'my_attribute',
                [
                    'group'                      => 'General',
                    'type'                       => 'text',
                    'label'                      => 'My attribute',
                    'input'                      => 'multiselect',
                    'frontend'                   => '',
                    'source'                     => 'Vendor\Module\Model\Product\Attribute\MyAttribute',
                    'backend'                    => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
                    'global'                     => ScopedAttributeInterface::SCOPE_GLOBAL,
                    'visible'                    => true,
                    'required'                   => false,
                    'user_defined'               => true,
                    'default'                    => 0,
                    'searchable'                 => false,
                    'filterable'                 => true,
                    'comparable'                 => false,
                    'visible_on_front'           => true,
                    'visible_in_advanced_search' => true,
                    'used_in_product_listing'    => true,
                    'sort_order'                 => 10,
                    'is_used_in_grid'            => false,
                    'is_visible_in_grid'         => false,
                    'is_filterable_in_grid'      => false,
                    'used_for_promo_rules'       => false,
                    'unique'                     => false,
                    'apply_to'                   => 'simple',
                ]
            )
```
2. Create a lot of attribute options for this attribute - around 300.
3. Assign all of these attributes to a product.
4. Turn on flat catalog
5. Reindex catalog_product_flat

### Expected result (*)

1. I'd expect the attribute to appear as a column of type 'text' in the ```catalog_product_flat_*``` tables, with the full list of concatenated IDs bought across from the attribute value table.

### Actual result (*)

1. The column is created as type varchar with a length of 255. Because of this, the value data is truncated if it's over this length.

This seems to be caused by ```\Magento\Eav\Model\Entity\Attribute\Source\Table```'s ```getFlatColumns()``` method, which specifically sets multiselects to type text, with a length of 255, values which get transformed as varchar of length 255.

**Comment by llapgoch** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @llapgoch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @llapgoch, here is your [Magento instance](https://i-24488-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24488-2-3-develop.instances.magento-community.engineering/admin](https://i-24488-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by llapgoch** [comment]
> Hi @llapgoch. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @llapgoch do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment]
Hi @llapgoch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @llapgoch, here is your [Magento instance](https://i-24488-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24488-2-3-develop.instances.magento-community.engineering/admin](https://i-24488-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @llapgoch thank you for your report.  I am not able to reproduce issue by steps you described on 2.3-develop
My attribute `source` class contains two more methods:
- `getFlatColumns`
- `getFlatUpdateSelect`

![#24488Issue](https://user-images.githubusercontent.com/51681379/67376561-097ea780-f58d-11e9-8b28-2dbc039a739c.gif)

If you'd like to update the issue, please reopen it.
