### ISSUE TITLE
"Clear Shopping Cart" button not working in Internet Explorer

### ISSUE THREAD

**Issue by andrew-ebsco** [magento/magento2#24491]
### Preconditions (*)

1. Magento Commerce 2.3.2
2. PHP 7.2.21

### Steps to reproduce (*)

1. Open Magento 2 site in Internet Explorer
2. Add item to the cart
3. Click `Clear Shopping Cart` button

### Expected result (*)

1. All items are deleted from the shopping cart
2. The cart page is refreshed showing no items

### Actual result (*)

1. The page refreshes and all cart items are still in the cart

The issue is caused by line 18 of `app/code/Magento/Checkout/view/frontend/web/js/shopping-cart.js`. The on click handler for the `Clear Shopping Cart` button checks if `event.detail` is 0 before proceeding. There is a bug in Internet Explorer 11 that causes the `event.detail` attribute to always be 0. As a result, you cannot clear the cart in IE.

Here is the IE bug report explaining that `event.detail` will not be fixed: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16710370/

**Comment by andrew-ebsco** [comment]
@magento-engcom-team give me test instance

**Comment by andrew-ebsco** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @andrew-ebsco. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @andrew-ebsco, here is your [Magento instance](https://i-24491-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24491-2-3-develop.instances.magento-community.engineering/admin](https://i-24491-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by andrew-ebsco** [comment]
I was able to confirm the issue in a vanilla Magento instance using the `Magento Blank` theme. The Luma theme removes the `Clear Shopping Cart` button.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19934` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @andrew-ebsco. Thank you for your report. 
The issue has been fixed in magento/magento2#24499 by @edenduong in 2.3-develop branch
Related commit(s):
 - [7005d99ae4af1f3ffdf35ba8370c4295c0bfbfe6](https://github.com/magento/magento2/commit/7005d99ae4af1f3ffdf35ba8370c4295c0bfbfe6)
 - [5847d9f64dad423d83bf0c742d810783ca213639](https://github.com/magento/magento2/commit/5847d9f64dad423d83bf0c742d810783ca213639)

The fix will be available with the upcoming 2.3.4 release.
