### ISSUE TITLE
configurable product's associate are not selected by default for attributes default values

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24496]
### Preconditions (*)
Magento 2.3.*

### Steps to reproduce (*)

Create a new attribute
Set "Catalog Input Type for Store Owner" to Dropdown
Set "Scope" to Global.
Add two options to the attribute and set any one among them default.
Create a new configurable product and add new configurations to the product, based on the attribute you've just created.

Go to the product page and you will see that the default attribute value is not selected by default for the attribute option.

### Expected result (*)
The default value should be selected
![image](https://user-images.githubusercontent.com/2028541/99409369-32d14a80-28e9-11eb-947c-f581bde98f98.png)
![image](https://user-images.githubusercontent.com/2028541/99409381-35cc3b00-28e9-11eb-8986-07b98f32b40a.png)

### Actual result (*)
the option is unselected in product page
![image](https://user-images.githubusercontent.com/2028541/99409339-2c42d300-28e9-11eb-83fb-d487eb45e5f7.png)

**Comment by engcom-Bravo** [comment]
Works fine on Backend. The official user guide says about it the following ["Assigns a starting value to the attribute to help during data entry."](https://docs.magento.com/m2/ce/user_guide/stores/attributes-product.html). Highly likely it means the data entry on Backend. But unless the area of the data entry is clearly specified Default Value is supposed to work on Frontend as well.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19940` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mohith-ecommerce** [comment]
@magento-engcom-team I have found the solution,I will create pull request

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24071` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
