### ISSUE TITLE
Warning!!! Taiwan is a region of China, NOT a  Country!!! Pls fix this BUG!!!

### ISSUE THREAD

**Issue by mugua** [magento/magento2#24515]
As I know, M2.3.2 is shows Taiwan is a Country in List, BUT Taiwan is a region of China, NOT a  Country!!! Pls fix this BUG!!!

**Comment by mugua** [comment]
You should be: Taiwan, China...

**Comment by engcom-Charlie** [comment]
Hello @mugua ! 
Both the ROC and the PRC still officially (constitutionally) claim mainland China and the Taiwan Area as part of their respective territories. In reality, the PRC rules only Mainland China and has no control of but claims Taiwan as part of its territory under its "One China Principle".
https://en.wikipedia.org/wiki/Taiwan,_China
Taiwan is an independent state. 
So i close this issue.
Thanks for your report!

**Comment by mugua** [comment]
Taiwan is a Provence of China!
