### ISSUE TITLE
API "V1/attributeMetadata/customerAddress/attribute/prefix" and "V1/attributeMetadata/customerAddress/attribute/suffix" can not get options

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24518]
API "V1/attributeMetadata/customerAddress/attribute/prefix" and "V1/attributeMetadata/customerAddress/attribute/suffix" can not get options

The reason because Prefix and Suffix **get the Option from SYSTEM CONFIG**, not in SOURCE

### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend, Store->Configuration. Customer Configuration. 

In "Name and Address Options", "Show Prefix": "Optional". "Prefix Dropdown Options" is "mr;mrs"

Similar to Suffix.

2. Use Postman or Rest Client to create API request
3. Request to http://[Magento 2 Domain] /rest/default/V1/integration/admin/token to get TOKEN
4. Use the token to call the api: 

http://[Magento 2 Domain] /rest/default/V1/attributeMetadata/customerAddress/attribute/prefix

Similar to Suffix:

http://[Magento 2 Domain] /rest/default/V1/attributeMetadata/customerAddress/attribute/suffix

### Expected result (*)

1. 

![image](https://user-images.githubusercontent.com/8234209/64490134-3e0bfd80-d284-11e9-9837-84488d39bfbe.png)

### Actual result (*)

1. 

![image](https://user-images.githubusercontent.com/8234209/64490191-ba9edc00-d284-11e9-98e6-183d0896eb27.png)

**Comment by dmytro-ch** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-24518-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24518-2-3-develop.instances.magento-community.engineering/admin](https://i-24518-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19939` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24519 by @edenduong in 2.3-develop branch
Related commit(s):
 - [1da4f2ac4985ab6d1d348e93d6fa8670888a2f5c](https://github.com/magento/magento2/commit/1da4f2ac4985ab6d1d348e93d6fa8670888a2f5c)
 - [e779423e1a11fa930c43eed12ddf4833f2cd8cf7](https://github.com/magento/magento2/commit/e779423e1a11fa930c43eed12ddf4833f2cd8cf7)

The fix will be available with the upcoming 2.3.4 release.
