### ISSUE TITLE
SEO: Category URLs aren't being properly generated for Multi-Store Multi-Language websites.

### ISSUE THREAD

**Issue by dannydamsky** [magento/magento2#24517]
### Summary (*)
When we insert a category to Magento all of its data gets saved correctly.
When running $category->getData() we can see the correct url_key and url_path properties.
But when we run $category->getUrl() we get the default Magento URL.

This only happens in some categories, and only for some stores.
The data is there, so I don't know what could lead to this issue, but it seems to me that
it's a bug with the URL rewrites.

To be clear, the data is correctly shown in the Magento back-end,
and saving the category using the "Save" button does not fix the issue either.

### Preconditions (*)
1. Magento 2.3.2 CE, but I believe that this issue persists on older versions as well.

### Steps to reproduce (*)

1.Create the category using the following code:
`

    $data = [

            'data' => [
                'name' => $groupName,
                'is_active' => true,
                'include_in_menu' => true
            ],
            'custom_attributes' => [
                [
                    'attribute_code' => 'meta_title',
                    'value' => $groupName
                ],
                [
                    'attribute_code' => 'meta_description',
                    'value' => $groupName
                ],
                [
                    'attribute_code' => 'meta_keywords',
                    'value' => $groupName
                ],
                [
                    'attribute_code' => 'url_key',
                    'value' => $urlKey
                ]
            ]
        ];
        $category = $this->categoryRepository->save(
            $this->categoryFactory->create($data)
                ->setStoreId($storeId)
        );
        if ($category->getCustomAttribute('url_key') !== $urlKey) {
            $category->setCustomAttribute('url_key', $urlKey);
            $this->categoryResource->save($category);
        }
`
### Expected result (*)
1. URL should be SEO-friendly concatinated URL keys of the category and all its parents, separated by a '/' character.

### Actual result (*)
1. Default Magento URL is rendered on the front-end.
Confirmation: Vanilla Magento yields same results.

**Comment by anajoomi** [comment]
> Hi @dannydamsky. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @dannydamsky do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

missing  info is added in original message.

**Comment by magento-engcom-team** [comment]
Hi @anajoomi. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anajoomi, here is your [Magento instance](https://i-24517-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24517-2-3-develop.instances.magento-community.engineering/admin](https://i-24517-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19943` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by davidverholen** [comment]
I think we ran into the same problem. It seems that if the same url path exists in another store view and another category tree, the url rewrite is not generated.

The error says, that the request path already exists in the same store, but it's a different store

**Comment by gabrieldagama** [comment]
Hi @dannydamsky, are there steps to reproduce this issue manually? Without having to programmatically add a new category.

Also, in your description, you talk about the `getUrl` method, but on the code, we can see that you are checking just the `url_key`, can you clarify?

**Comment by dannydamsky** [comment]
> 
> 
> Hi @dannydamsky, are there steps to reproduce this issue manually? Without having to programmatically add a new category.
> 
> Also, in your description, you talk about the `getUrl` method, but on the code, we can see that you are checking just the `url_key`, can you clarify?

Hi @gabrieldagama, the steps to reproduce describe how to create the category in order for the `getUrl` method to not work properly. I don't know if there's a way to reproduce this issue manually.

**Comment by magento-engcom-team** [comment]
Hi @dannydamsky. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24073` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
