### ISSUE TITLE
All Travis CI tests are failing due to repo.magento.com authentication requirements

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#2452]
Magento added authentication to repo.magento.com two days ago. Since then, all Travis CI tests are failing. It looks like you'll need to use something like http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables to pass the public/private keys.

![pull_requests_ _magento_magento2](https://cloud.githubusercontent.com/assets/129031/11312112/aa46827c-8f99-11e5-82f7-7394c38cff5b.png)

Specific error message:

```
  - Installing magento/composer (1.0.2)
    Downloading: connection...

  [Composer\Downloader\TransportException]                                     
  The 'https://repo.magento.com/archives/magento/composer/magento-composer-1.  
  0.2.0.zip' URL required authentication.                                      
  You must be using the interactive console to authenticate  
```

Example job that is failing: https://travis-ci.org/magento/magento2/jobs/92344625

**Comment by buskamuza** [comment]
We're working on it. Internal ticket MAGETWO-45728

**Comment by erikhansen** [comment]
Ok. Any update?

**Comment by buskamuza** [comment]
Sorry, not done yet. But it's in progress.
