### ISSUE TITLE
Category path error

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#24524]
### Preconditions (*)

1. Magento 2.3.2
2. php 7.2

### Steps to reproduce (*)

1.Create sub category, click add new sub category and so on... so basicaly you create sub sub sub sub sub category
2.Drag last created category to it's parent sub

### Expected result (*)

1. Category path should change based on position of category
2.<img width="258" alt="Schermafbeelding 2019-09-09 om 10 58 42" src="https://user-images.githubusercontent.com/37579149/64517547-d3dd7200-d2f0-11e9-880c-3b0116a5d2b7.png">

### Actual result (*)

1. Category path is not changed but remains old.
2. koppel-accessoires/pouches/tac-pouches/tool-pockets/admin-ouches/multitool-pouches/zakmes-pouches/zaklamp-houders/lanyards-en-gearkeepers
3. the breadcrumbs are correct 
<img width="499" alt="Schermafbeelding 2019-09-09 om 11 02 35" src="https://user-images.githubusercontent.com/37579149/64517845-641bb700-d2f1-11e9-9a6c-ecdab6368d57.png">

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24524-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24524-2-3-develop.instances.magento-community.engineering/admin](https://i-24524-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Naberdz** [comment]
from what i understand problem lies within:
catalog_category_entity_varchar table field value is not updated.

table catalog_category_entity has correct path.

**Comment by shikhamis11** [comment]
@Naberdz Thank you for your report.
I checked the issue at 2.3-develop instance but not able to reproduce there can you recheck and confirm the issue on 2.3-develop instance . also If possible please share screenshots

**Comment by Naberdz** [comment]
Yes tested it in new developer version and it seem to be working fine.. in my case it doesn't create redirect.

<img width="920" alt="Schermafbeelding 2019-09-09 om 11 23 42" src="https://user-images.githubusercontent.com/37579149/64519822-3173bd80-d2f5-11e9-82ed-4a973ea39af3.png">
<img width="1190" alt="Schermafbeelding 2019-09-09 om 11 24 29" src="https://user-images.githubusercontent.com/37579149/64519823-3173bd80-d2f5-11e9-9680-2494b86d0e1e.png">
<img width="1581" alt="Schermafbeelding 2019-09-09 om 11 25 01" src="https://user-images.githubusercontent.com/37579149/64519824-3173bd80-d2f5-11e9-87e5-6607994e1f90.png">

**Comment by shikhamis11** [comment]
It seems this issue is already fixed in latest magento 2.3 version or It is caused by any custom development at your end.

**Comment by Naberdz** [comment]
i guess it's fixed in latest .. as it seem i have 2.3.1 thought i have it updated to 2.3.2.
