### ISSUE TITLE
Cannot Create Credit Memo On Order With No Postal Code

### ISSUE THREAD

**Issue by Sental** [magento/magento2#24522]
### Preconditions (*)
1. Magento 2.3.2
2. An order created using a country that does not require a postcode. ie. Ireland

### Steps to reproduce (*)
1. Create an order from a country without the postcode requirement, for example Ireland
2. Omit the postcode when creating/choosing the addresses for the order
3. Proceed through the system in the admin console to create a credit memo.

### Expected result (*)
1. The credit memo is created successfully with no errors.

### Actual result (*)
1. On pressing the Refund Offline Button you are greeted with the following error: 'Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address'

On Lines 76 - 79 of the file you find the function getPostcode(), this requires a string return type. In the case of an optional postcode where a customer doesn't use a postcode in the order it does not return a string and there are no checks on the function to prevent this error.

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24522-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24522-2-3-develop.instances.magento-community.engineering/admin](https://i-24522-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hi @Sental 
Thank You for reporting the issue, I checked on magento 2.3-develop instance and placed order with check/Money order and after invoice tried refund , but I am not able to reproduce the issue. Can you confirm are you getting this issue on 2.3-develop instance. 

also Please update issue description if it require any additional steps to reproduce the issue .

**Comment by Sental** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Sental. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sental, here is your [Magento instance](https://i-24522-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24522-2-3-develop.instances.magento-community.engineering/admin](https://i-24522-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Sental** [comment]
I am not able to reproduce this on the develop instance. Possibly this was fixed in develop and has not been added to the currently released branch yet.

**Comment by sourav88** [comment]
I get same issue on magento2.3.2

**Comment by dareenzo** [comment]
I get this same issue in 2.3.2-p2
