### ISSUE TITLE
Method _saveLinks on class Magento\CatalogImportExport\Model\Import\Product remove all links not only the related, upsell, crossell

### ISSUE THREAD

**Issue by magedevel** [magento/magento2#24520]
### Preconditions (*)

1. Magento 2.3.2
2. Php 7.2
3. Local Env with Nginx and Valet + on Mac Os 10.14.6

### Steps to reproduce (*)

1. Create grouped product with simple associated
2. Add related product to the grouped product
3. Create and export CSV using the Magento export functionality
4. Change the grouped product description
5. Import the exported CSV with the Magento import functionality

### Expected result (*)

1. Product description changed according to the data changed in CSV.

### Actual result (*)

1. Group link created in catalog_product_link are deleted
2. The grouped product lost the relations.

### Focus on _saveLinks method
at line 1360 we have :
```
if (Import::BEHAVIOR_APPEND != $this->getBehavior() && $productIds) {
                $this->_connection->delete(
                    $mainTable,
                    $this->_connection->quoteInto('product_id IN (?)', array_unique($productIds))
                );
            }
...
```
This code delete all relation type for the product ids parsed before. This is wrong. The code before has got this to find the links:

```
$bind = [':product_id' => $productId];
                foreach ($this->_connection->fetchAll($select, $bind) as $linkData) {
                    $linkKey = "{$productId}-{$linkData['linked_id']}-{$linkData['link_type_id']}";
                    $productLinkKeys[$linkKey] = $linkData['id'];
                }
                foreach ($this->_linkNameToId as $linkName => $linkId) {
                    $productIds[] = $productId;
```

Related group has got a link_type_id equal 3.

### Suggestion
We suggest to cicle on linkId and remove only the linkId parsed. Here a code suggestion:
```
if (Import::BEHAVIOR_APPEND != $this->getBehavior() && $productIds) {
                // we need to delete only the linkid type
                foreach ($this->_linkNameToId as $linkName => $linkId) {
                    $where = [];
                    $where [] = $this->_connection->quoteInto('product_id IN (?)', array_unique($productIds));
                    $where [] = $this->_connection->quoteInto('link_type_id = ?', $linkId);

                    $this->_connection->delete(
                        $mainTable,
                        $where
                    );
                }

            }
```

**Comment by engcom-Bravo** [comment]
Hello @magedevel. This issue seems to have already been fixed as we can not reproduce it in the latest develop version. Would You please try to reproduce it Yourself on 2.3-develop version. Thank You.

**Comment by magedevel** [comment]
ok i will check @engcom-Bravo

**Comment by engcom-Bravo** [comment]
Hi @magedevel. The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
