### ISSUE TITLE
Base Image Labels are not being imported in multiple store view Magento CE & EE 2.3.x

### ISSUE THREAD

**Issue by mdruguet** [magento/magento2#24527]
### Preconditions (*)

1. Magento EE 2.3.x & 2.3.x CE

### Steps to reproduce (*)

1. Create multiple store view
2. Create a csv file to import base images associated to a product and their labels (each label image must be different by store view, for example label 1 for store uk, label 2 for store fr)
3. Import

### Expected result (*)

1. Each image label must be different by store view

### Actual result (*)

1. The images labels are not different by store view and worse, some labels associated to a store view are applied to another store view

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20131` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mdruguet** [comment]
@engcom-Charlie Thank's a lot for your test and help.

Best regards

**Comment by magento-engcom-team** [comment]
Hi @mdruguet. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24190` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
