### ISSUE TITLE
Remove tax rule popup not same as per other default popup

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#24537]
Remove tax rule popup not same as per other default popup.

### Preconditions (*)
Magento 2.3.2

### Steps to reproduce (*)
1. Admin -> Store -> Taxes ->  Tax Rules -> Add new Tax Rules
2. Tax Rate -> Click on Delete icon any tax rule 
3. Review the popup

 ### Expected result (*)
Remove popup design should same throughout the back end

### Actual result (*)
![image](https://user-images.githubusercontent.com/49804008/64597992-8afee980-d3d4-11e9-8e8c-4b6c65bb6ba6.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24537-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24537-2-3-develop.instances.magento-community.engineering/admin](https://i-24537-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20083` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ryandiamond23** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ryandiamond23, here is your [Magento instance](https://i-24537-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24537-2-3-2.instances.magento-community.engineering/admin](https://i-24537-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#24538 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [635c38f3177b59125541fd2936c7ec48df829470](https://github.com/magento/magento2/commit/635c38f3177b59125541fd2936c7ec48df829470)
 - [054d959deb2c1bd7b5ebe5173d9604c90eb38403](https://github.com/magento/magento2/commit/054d959deb2c1bd7b5ebe5173d9604c90eb38403)

The fix will be available with the upcoming 2.3.4 release.
