### ISSUE TITLE
Line length is too long in emails

### ISSUE THREAD

**Issue by philippeaellig** [magento/magento2#24531]
# Preconditions (*)
Magento 2.2.8 in production mode. Use production mode to reproduce this bug, because only in this case, less code will compiled and minimized to one line.

### Steps to reproduce (*)
Send an email with the default magento header.
vendor/magento/module-email/view/frontend/email/header.html
Have a look at the source code of the mail.
The line with the rendered css from css/email.css is too long, in my case 5611 octets. this is too long. allowed are max. 998 characters for one line. some mails will not reach the reciver, because some mailservers do not accept mails with long lines.

### Expected result (*)
1. minimizes css, but not in one line. no line longer than 998 characters.

### Actual result (*)
1. one line, 5611 characters.

I think, this issue is about the same topic. https://github.com/mageplaza/magento-2-smtp/issues/156 (another magento extension, but this is not a mageplaza bug...)

**Comment by gwharton** [comment]
Fixed in 2.3-develop

**Comment by gwharton** [comment]
Fixed in 2.2-develop. Will be in 2.2.10 release

**Comment by gwharton** [comment]
See PR #23650
