### ISSUE TITLE
One Page Checkout : Long street address is incorrectly saved

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#2453]
`Magento 2.0.0 with sample data`

Expected result is the address should have been saved as customer entered no matter how long it is.

**::One Page Checkout::**
![1](https://cloud.githubusercontent.com/assets/11070293/11316588/cba825dc-903f-11e5-8ca1-4ae7e2bb369b.PNG)
![2](https://cloud.githubusercontent.com/assets/11070293/11316589/cc8ca388-903f-11e5-957b-6990dff68442.PNG)

**::Admin::**
![3](https://cloud.githubusercontent.com/assets/11070293/11316596/f898bcb4-903f-11e5-8acd-4d9976cf832c.PNG)
![4](https://cloud.githubusercontent.com/assets/11070293/11316592/d186871e-903f-11e5-9231-3123a41a39fd.PNG)

**::Invoice PDF::**
![5](https://cloud.githubusercontent.com/assets/11070293/11316622/402cd5fa-9041-11e5-83f8-9dd9f178a3bc.PNG)

**Comment by ishakhsuvarov** [comment]
@adzminz Thank you for reporting this issue.
We have created internal ticket `MAGETWO-45902` to track progress.

**Comment by joehenriod** [comment]
How many characters are allowed before the error occurs?

**Comment by ishakhsuvarov** [comment]
@joehenriod Currently it is 40 for the summary length of all Street Address lines.
Fix to this issue is going to be delivered in the nearest future in the scope of internal ticket `MAGETWO-45902`

**Comment by ishakhsuvarov** [comment]
@adzminz 
Fix for this issue had been delivered to the `develop` branch. Please see commit [e92ce8b](https://github.com/magento/magento2/commit/e92ce8b71fe30445a4bd35f0e91a10d3312dd88f).
