### ISSUE TITLE
Negative prices in layered navigation

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#24535]
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. Re-reporting https://github.com/magento/magento2/issues/14443 as this has been closed but is not fixed.
2. Multi store setup, different discounts for different stores.

### Expected result (*)

1. Layered navigation shows correct price ranges

### Actual result (*)

1. Layered navigation shows negative price ranges
![20190909_115604](https://user-images.githubusercontent.com/2926266/64558871-c973a600-d2f9-11e9-9e4a-98a8f7f035aa.png)

```
mysql> select * from catalog_product_index_price where min_price < 0 limit 10;
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
| entity_id | customer_group_id | website_id | tax_class_id | price   | final_price | min_price | max_price | tier_price |
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
|     44489 |                 2 |          3 |            2 | 69.0000 |     30.5000 |   -8.0000 |   -8.0000 |    30.5000 |
|     44489 |                 6 |          3 |            2 | 69.0000 |     30.7200 |   -7.5600 |   -7.5600 |    30.7200 |
|     34227 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     34227 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40003 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40003 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40005 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40005 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40011 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40011 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
10 rows in set (0.01 sec)
```

**Comment by engcom-Bravo** [comment]
Hello @MichaelThessel. We are not able to reproduce Your issue. We've got data like this:
![tiers](https://user-images.githubusercontent.com/51680745/64679912-60209e00-d485-11e9-89e9-742401e5e7e1.png)
Probably the issue has already been fixed. So let us ask You to try to reproduce it on a clear Magento installation of the latest develop version (2.3-develop). If You are still able to reproduce the issue on such one, please provide more detailed steps on how to reproduce it. Thank You.

**Comment by ihor-sviziev** [comment]
Hi @MichaelThessel,

We had similar issue, It was caused by using negative "price" in custom options, data was migraded from M1. In Magento 2.x you can't put negative price for custom option prices.

Hope it will help you to identify the issue

**Comment by MichaelThessel** [comment]
@engcom-Bravo

> Probably the issue has already been fixed.

How can I update my install to the latest develop branch? I'm sick of tracking down issues that have already been fixed. I cannot find a way to do this with composer. 

@ihor-sviziev 

Thanks for that. We don't utilize negative price custom options though. So that wasn't the issue.

**Comment by engcom-Bravo** [comment]
@MichaelThessel, please try to reproduce Your issue at least on 2.3.2 version which is available via composer. But do not update Your instance, just pull down the fresh official code free from any changes or ads-on install an instance with it and go on with the issue reproduction. Thank You.

**Comment by engcom-Bravo** [comment]
@MichaelThessel, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
