### ISSUE TITLE
when i add product in magento 2 from iphone the product image change to landscape

### ISSUE THREAD

**Issue by Asifjalil99** [magento/magento2#24536]
### Preconditions (*)
1. Using magento 2.3.0(reproduced on 2.3-develop) login to admin and adding products image take live from iphone camera
2. save it.
3. the product image is sudden change to landscape

### Steps to reproduce (*)
1. checked fotorama.js but not working
2. uploaded save image to product is ok, but when take direct from iphone camera its rotated to landscape and if added landscape image its totally showing upside down.

### Expected result (*)
1. when adding direct image from iphone camera should be in the same style Portrait should be Portrait and landscape should be landscape

### Actual result (*)
![image](https://user-images.githubusercontent.com/35948773/64610123-fb633600-d3e7-11e9-8b1e-028072986ede.png)

]

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-24536-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24536-2-3-develop.instances.magento-community.engineering/admin](https://i-24536-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @Asifjalil99
I can't reproduce this issue on fresh 2.3-develop instance.
Did you tried in this instance?
**My results(iphone):**
**1. In admin:**
**wysiwyg editor:**
![image](https://user-images.githubusercontent.com/51680850/64597798-25ecc900-d3bf-11e9-9c61-a5a12bc595c4.png)
**product image:**
![image](https://user-images.githubusercontent.com/51680850/64597822-38ff9900-d3bf-11e9-8f3d-a0e418e0fa44.png)
**2. Product page:**
**product image:**
![image](https://user-images.githubusercontent.com/51680850/64597851-4a48a580-d3bf-11e9-83ac-e35e65de0922.png)
**content:**
![image](https://user-images.githubusercontent.com/51680850/64597860-4f0d5980-d3bf-11e9-89b0-38e4e0da6ecd.png)

So i have to close this issue.
Please refer to [Codazon theme support](https://codazon.zendesk.com/hc/en-gb/requests/new), for advice or general discussion about this issue.
Thanks for your report!

**Comment by Asifjalil99** [comment]
can you just tel me the file path then i can fix it by my self :) i need only file location

**Comment by Asifjalil99** [comment]
@engcom-Charlie check this i have taken photo from iphone and added and check the result its change to landscape.
![image](https://user-images.githubusercontent.com/35948773/64600523-b4b81080-d3d4-11e9-81c1-73c3a3c812c3.png)

**Comment by engcom-Charlie** [comment]
@Asifjalil99 jush click "inspect the element" into img and you will see path to your img:
![image](https://user-images.githubusercontent.com/51680850/64602547-a9aab380-d3c7-11e9-8aeb-6751df309de2.png)

**Comment by Asifjalil99** [comment]
@engcom-Charlie i am not talking about image path, i am talking about coding file path, because this picture is taking in Portrait style and when added to product its automatic changed to landscape i want to fix this, so that the Portrait image show in Portrait style and Landscape should show in landscape, Just try to add a new product and try to add image direct taken from iphone camera in portrait style and save it, and then refresh your page you will see your image auto change to landscape. thats the issue

**Comment by Asifjalil99** [comment]
i thing the problem is in EXIF metadata magento 2 not reading correctly

**Comment by engcom-Charlie** [comment]
@Asifjalil99 ok, i understand you. Please update your issue(use it:https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and i will confirm it.

**Comment by Asifjalil99** [comment]
@engcom-Charlie  i already updated my issue with screenshot please i need urgent solution of this its very very urgent. many thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20086` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Asifjalil99** [comment]
respected magento team
how much time it will take to resolve the issue, as this is very urgent work and i need this to done today waiting for your positive response :)
many thanks

**Comment by Asifjalil99** [comment]
any have have fix for this please i need this

**Comment by Asifjalil99** [comment]
**Solved by my self:**
go to **vendor\magento\framework\File\Uploader.php** on line 228, inside try block add

**if ((strstr($_SERVER['HTTP_USER_AGENT'], 'iPhone') || strstr($_SERVER['HTTP_USER_AGENT'],'iPad')) && exif_imagetype($this->_file['tmp_name']) == IMAGETYPE_JPEG) {
            $source = imagecreatefromjpeg($this->_file['tmp_name']);
            $rotate = imagerotate($source, 270, 0);
            imagejpeg($rotate, $this->_file['tmp_name']);
        }**

before **$this->_result = $this->_moveFile($this->_file['tmp_name'], $destinationFile);** line

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
