### ISSUE TITLE
session_write_close() error on setup/nginx

### ISSUE THREAD

**Issue by markshust** [magento/magento2#2454]
I'm receiving the following error when running the install process:

```
[Progress: 359 / 362]
Caches clearing:
Cache cleared successfully
[Progress: 360 / 362]
Disabling Maintenance Mode:
[Progress: 361 / 362]
Post installation file permissions check...
For security, remove write permissions from these directories: '/src/app/etc'
[Progress: 362 / 362]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin_ahrtkt

Fatal error: Uncaught ErrorException: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/src/var/session/) in /src/vendor/magento/framework/Session/SessionManager.php:139
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'session_write_c...', '/src/vendor/mag...', 139, Array)
#1 /src/vendor/magento/framework/Session/SessionManager.php(139): session_write_close()
#2 [internal function]: Magento\Framework\Session\SessionManager->writeClose()
#3 {main}
  thrown in /src/vendor/magento/framework/Session/SessionManager.php on line 139
```

This is on Nginx 1.9 & latest PHP7. Is this caused by something with Nginx + PHP-fpm?

**Comment by markshust** [comment]
Any update on this? This is using official php 7.0.0 image.

**Comment by mazhalai** [comment]
We have created MAGETWO-46531 to investigate.

**Comment by mazhalai** [comment]
@markoshust we are unable to reproduce this. Do you have correct permissions set for your var folder?

**Comment by markshust** [comment]
@mazhalai I was thinking this could be the case, however all of the other functionality throughout Magento 2 works fine with the `var` folder, and new sessions are being written (files created) in `var/session` just fine.

**Comment by mazhalai** [comment]
Is it possible this is a PHP7 issue? We are unable to reproduce this issue. We tried with Nginx 1.6.2  and compiled PHP 7 GA. There have been other issues with PHP7, possibly when using a repo, see #2750 and #2827. Another suggestion is to clean your session save path.

**Comment by markshust** [comment]
I believe this is all fixed, as I haven't received the issue in a while. I'll close it up for now. Thanks!
