### ISSUE TITLE
Shopping Cart gets cleared after Password Reset

### ISSUE THREAD

**Issue by sjohn2016** [magento/magento2#24541]
### Preconditions (*)

1. Magento Open Source 2.3.1 
2. Issue Produced in a site with actual loaded client data

### Steps to reproduce (*)

1.  Add a Product to Cart in a Non Logged In State in the Magento Site
2. Click On `Sign-in` Link
3. Click on `Forgot Password` Link
4. Fill our the Form and submit it
5. Go to your email and Click the Reset password link which takes you back to the site and a `Set a New Password` Form Page. The Mini-Cart still seems to indicate that the product exists in the Cart.
6. Fill out the new password and reset the password .
7. You will see that the password got reset successfully But the Cart got emptied out. 

### Expected result (*)

1. The Shopping Cart be kept intact as it is the same user in session 

### Actual result (*)

1. The Shopping cart gets emptied out once the User resets their password

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-24541-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24541-2-3-develop.instances.magento-community.engineering/admin](https://i-24541-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @sjohn2016. Seems like this issue has been fixed:
![reset](https://user-images.githubusercontent.com/51680745/64673644-61e36500-d477-11e9-9b14-63f841e09d39.png)
(Don't pay attention to "admin" with password filled in to form. It was done by Chromes Autofill immediately after the page had been reloaded.)
So would You please try to reproduce Your issue on the latest develop version (i.e. 2.3-develop). Thank You.

**Comment by sjohn2016** [comment]
Looks like 2.3.2 release has fixed this issue. I see it in the release notes now. I will need to upgrade my application...along with the extensions involved..to see this change. 

Appreciate the really fast response !
