### ISSUE TITLE
Call to a member function count() on boolean in \Magento\Sales\Model\Order::hasCreditmemos()

### ISSUE THREAD

**Issue by est1986ad** [magento/magento2#24540]
### Preconditions (*)

1. 2.3.2
2.

### Steps to reproduce (*)

1.call  \Magento\Sales\Model\Order::hasCreditmemos()
2.

### Expected result (*)

1. return boolean
2.

### Actual result (*)

1. Uncaught Error: Call to a member function count() on boolean
2.

**Comment by engcom-Bravo** [comment]
Hello @est1986ad. Thanks for applying. The issue ether has been fixed or we've missed some essential detail while trying to reproduce it. We have created two orders with id 1 - has a credit memo and id 2 - hasn't. Then we created a simple CLI command where hasCreditmemos() was called. Please look what we obtained.
![orderhasCM](https://user-images.githubusercontent.com/51680745/64685128-1b016980-d48f-11e9-9f84-0004e49ce8d1.png)

**Comment by edenduong** [comment]
Seems it failed when call the hasCreditmemos() without load().

**Comment by engcom-Bravo** [comment]
Does that method have any sense to be used without load @edenduong?

**Comment by edenduong** [comment]
@engcom-Bravo : I don't think we should call it without load(), so I think it is not an issue. But it can improve by check the condition (it is not really useful now)

**Comment by engcom-Bravo** [comment]
I agree with You @edenduong. So lets wait yet for what the reporter has to say to that.

**Comment by engcom-Bravo** [comment]
@est1986ad, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
