### ISSUE TITLE
Merging of definition.xml fails on DOM elements with multiple children

### ISSUE THREAD

**Issue by HenKun** [magento/magento2#24543]
_Example: Adding a new export format to ExportButton._
It is not possible to add another export format to ExportButton by extending the defintion.xml.

### Preconditions (*)
1. Magento Version 2.3.2 & 2.3-develop
2. Fresh install

### Steps to reproduce (*)
1. Create a new module
2. Add `{vendor}/{module}/view/base/ui_component/etc/definition.xml` with following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_definition.xsd">
    <exportButton>
        <settings>
            <options>
                <option name="customcsv" xsi:type="array">
                    <item name="value" xsi:type="string">customcsv</item>
                    <item name="label" xsi:type="string" translate="true">CUSTOM CSV</item>
                    <item name="url" xsi:type="string">{frontname}/export/gridToCustomCsv</item>
                </option>
            </options>
        </settings>
    </exportButton>
</components>
```

3. Add controller `{vendor}\{module}\Controller\Adminhtml\Export\GridToCustomCsv.php` with content:

```
<?php

namespace {vendor}\{module}\Controller\Adminhtml\Export;

class GridToCustomCsv extends \Magento\Ui\Controller\Adminhtml\Export\GridToCsv
{
    const ADMIN_RESOURCE = 'Vendor_Module::gridtocustomcsv_export';
}
```

4. Compile/upgrade etc.

5. Go to admin sales order grid

### Expected result (*)

1. New entry "CUSTOM CSV" is added in export dropdown (in addition to csv and xml) above every grid, that already supports csv and xml export

### Actual result (*)

1. Exception `\Magento\Framework\Exception\LocalizedException` with message `More than one node matching the query: /components/exportButton/settings/options/option, Xml is: ...` is raised.

### Reason

The original `definition.xml` from `app/code/Magento/Ui/view/base/ui_component/etc/definition.xml` contains the following part:

```
<exportButton class="Magento\Ui\Component\ExportButton" component="Magento_Ui/js/grid/export" displayArea="dataGridActions">
        <settings>
            <options>
                <option name="cvs" xsi:type="array">
                    <item name="value" xsi:type="string">csv</item>
                    <item name="label" xsi:type="string" translate="true">CSV</item>
                    <item name="url" xsi:type="string">mui/export/gridToCsv</item>
                </option>
                <option name="xml" xsi:type="array">
                    <item name="value" xsi:type="string">xml</item>
                    <item name="label" xsi:type="string" translate="true">Excel XML</item>
                    <item name="url" xsi:type="string">mui/export/gridToXml</item>
                </option>
            </options>
        </settings>
    </exportButton>
```
Two tags `option` reside in the `options` tag. In `magento\framework\Config\Dom.php` line 330 in `_getMatchedNode` Magento tries to find a matching tag `option` (stated in the new `definition.xml`) in the original `defintion.xml` without considering the name of the tag. It now finds two `option` tags in the original document, which leads to the thrown exception.

The name of the tag is not considered in this function, but one function above in `_mergeNode` line 165, which is too late. It should be totally valid to add another `option` tag to the `options` tag, given another name. Note that it works fine, if the original document would only contain one `option` under `options`.

### Possible solution

The name (if available) should be already considered in `_getMatchedNode`. If this is done, then the check for  the name in `_mergeNode` from line 174 to 183 can completely be left out, since `_getMatchedNode` would return null on non-matching nodes (consideriug the name if available) and `_mergeNode` would instantly use the `else` branch in line 214, beautifully eliminating the duplicate code in line 179 and 216 at the same time.

**Comment by engcom-Charlie** [comment]
Hello @HenKun !
Sorry about closing(missclick).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20110` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saravanansp96** [comment]
#mm20in

**Comment by magento-engcom-team** [comment]
@saravanansp96 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sivaschenko** [comment]
The `exportButton` component can be configured on the instance level. It should be discussed if the declaration configuration should be extendable.

**Comment by HenKun** [comment]
Yes it could be configured on instance level, this is what I am currently doing. But actually you don't know all instances in a system as a third party developer. And it would be a massive overhead to configure for each instance seperately.  

Additionally, I see no reason why XML export and CSV export are configured on a general level but other export formats (e.g. offered by third party modules) cannot. That would be a different treatment of basically the same thing. Furthermore it would violate the Open-Closed-Principle in that it doesn't allow to extend the behavior equally to the existing behavior, but requires to hack the `definition.xml` in some way to get the same effect. 

And in fact, this declaration configuration is already perfectly extendable, if there would only be one `option` in the `options` array in the original `definition.xml`. So the difference of being extendable or not lies in the number of `option`s being configured in the original xml. This does not seem reasonable.

So I vote for either being able to extend the declaration configuration or offer another way of adding things to it to achieve the same effect.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
