### ISSUE TITLE
Configurable Product with Non-Default MSI Stock/Source displays $0.00 if "Display Out of Stock Products" set.

### ISSUE THREAD

**Issue by zw1111** [magento/magento2#24545]
### Preconditions (*)
1.  Fresh install of Magento 2.3.2
2.  All Multi-Source Inventory (MSI) modules enabled
3.  PHP 7.2
4.  Apache 2.4

### Steps to reproduce (*)
1.  In Magento Admin, set  "Display Out of Stock Products" to "Yes" under Stores > Configuration > Catalog > Inventory > [Stock Options]

2.  Create Two new MSI sources called "Main Source" and "Dropship Source"

3.  Create a new MSI Stock called "US Stock" and assign the Main Website to it, as well as assign the Two newly created sources "Main Source" and "Dropship Source".  DO NOT ASSIGN THE DEFAULT SOURCE.

4.  Create a new Configurable Product with three items differentiated by color, which are Red, Green, and Blue.

5.  Assign the "Main Source" and the "Dropship Source" to each one of those items and provide some combination of quantity to each, where the total quantity is > 0.  DO NOT ASSIGN THE DEFAULT SOURCE.

6.  Set the prices of those items to Red = $190.00, Green = $195.00, and Blue = $200.00

7.  View the Product in the Store.

### Expected result (*)
1.  Product price should display "As low as $190.00"
2.  Drop down options should display: "Red", "Green +$5.00", "Blue +$10.00"

### Actual result (*)
1.  Product price displays "As low as $0.00"
2.  Drop down options display: "Red +$190.00", "Green +$195.00", "Blue +$200.00"

### Additional Details
I originally posted this on the Magento Forums, hoping someone knew how to resolve this.  My original request for help on the Magento Forums, which includes some screenshots, is here:
[Magento Forum Posting](https://community.magento.com/t5/Magento-2-x-Technical-Issues/Default-Configurable-Product-Pricing-states-0-00-after-setting/m-p/141795#M10775)

I eventually came to an erroneous conclusion that this was being caused by an extenstion I bought from Amasty called "Custom Stock Status".  After working with Amasty customer support, they were able to recreate the issue without having their extension installed at all.  I then tried on my test server with a fresh install of Magento 2.3.2, and also was able to re-create the issue.  So this issue has been replicated by an independent source.

Also, if you have MAP enabled and set the MSRP to the same price as the item, the system still thinks there is a price difference and tells you to add to the cart to see the price.

All of these issues go away if you set the  "Display Out of Stock Products" option to "No"...

  - OR -

Keep  "Display Out of Stock Products" to "Yes" but Assign the "Default Source", in addition to the other sources, to any one of the Configurable Product items and set the quantity > 0.  The  "Display Out of Stock Products" option in conjunction with Multi-Source Inventory (MSI) seems to be the trigger for this issue.

Some screenshots attached...

![ManageStockConfiguration](https://user-images.githubusercontent.com/54848229/64654039-058c3100-d3f6-11e9-88bd-966d0ff4d8e2.jpg)
![ConfigurableProduct_MSI_Setup](https://user-images.githubusercontent.com/54848229/64654059-1472e380-d3f6-11e9-93ae-a3293eac05bc.jpg)
![DisplayOutOfStock_Set_Yes](https://user-images.githubusercontent.com/54848229/64654065-19379780-d3f6-11e9-8567-e60d6cf0d72c.jpg)
![DisplayOutOfStock_Set_No](https://user-images.githubusercontent.com/54848229/64654080-1d63b500-d3f6-11e9-8d3e-fe27914ca1d6.jpg)

**Comment by engcom-Charlie** [comment]
Hello @zw1111 !
Your issue for magento inventory modules.
Please duplicate this issue in [Magento Inventory repository](https://github.com/magento/inventory/issues), for advice or general discussion about this issue.
Thanks for your report!
