### ISSUE TITLE
[ERROR] Magento\Framework\Setup\Exception: Failed to set ini option "session.cookie_lifetime" to value "3600".

### ISSUE THREAD

**Issue by osa85eg** [magento/magento2#24554]
### Summary

This error message occur while installing Magento 2.3

`Installation is incomplete.
Check the console log for errors before trying again.`

**Console Log**

`[ERROR] Magento\Framework\Setup\Exception: Failed to set ini option "session.cookie_lifetime" to value "3600". mkdir(): File exists in /public/mamajit.com/vendor/magento/framework/Setup/Patch/PatchApplier.php:167
Stack trace:

#0 /public/mamajit.com/setup/src/Magento/Setup/Model/Installer.php(1002): Magento\Framework\Setup\Patch\PatchApplier->applyDataPatch('Magento_Catalog...')

#1 /public/mamajit.com/setup/src/Magento/Setup/Model/Installer.php(874): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data', Array)

#2 [internal function]: Magento\Setup\Model\Installer->installDataFixtures(Array)

#3 /public/mamajit.com/setup/src/Magento/Setup/Model/Installer.php(367): call_user_func_array(Array, Array)

#4/public/mamajit.com/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#5 /public/mamajit.com/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()

#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))

#7 /public/mamajit.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))

#8 /public/mamajit.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))

#9 /public/mamajit.com/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))

#10 /public/mamajit.com/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))

#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))

#12 /public/mamajit.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))

#13 /public/mamajit.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))

#14 /public/mamajit.com/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))

#15 /public/mamajit.com/setup/index.php(39): Zend\Mvc\Application->run()

#16 {main}`

All requirements of Magento 2.3 are met.

Can you help me with that issue please

**Comment by engcom-Charlie** [comment]
Hello @osa85eg !
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.
