### ISSUE TITLE
ElasticSearch doubled indices in alias trouble if exception was thrown

### ISSUE THREAD

**Issue by VaD1ke** [magento/magento2#24550]
### Preconditions 
1. Magento 2.2.* - 2.3.* (open-source and commerce editions )
2. Catalog search engine is Elasticsearch

### Steps to reproduce
1. Make your catalogsearch index invalid (I make it right in DB for testing)
2. Wait cron until it creates few pending cron jobs 
3. Now we need to get an catchable error during index saving. For reproducing I do it in code \Magento\Elasticsearch\Model\Indexer\IndexerHandler::saveIndex, just put an exception right after `$this->adapter->addDocs` line in the method (you need to send some docs before the exception to get them doubled in alias). 
4. Run cron
5. And if you go to category page for example, Magento will fall with exception "Item ... with the same ID ... already exists.".

### Expected result
1. Only one old index in ElasticSearch alias because reindex was end up with error
2. Working site

### Actual result
1. We got few indexes in ElasticSearch alias
2. And we got an error in category page

### Additional info
I gave more technical details in [pull-request](https://github.com/magento/magento2/pull/24552)

**Comment by engcom-Charlie** [comment]
Hello @VaD1ke 

I close this issue as not relevant since PR is already merged.
