### ISSUE TITLE
shop

### ISSUE THREAD

**Issue by manojvfx** [magento/magento2#24551]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by shikhamis11** [comment]
hi @manojvfx, Please correct the format of the issue you can check and update descriptions
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
