### ISSUE TITLE
/pub/media/styles.css   CSS file not found

### ISSUE THREAD

**Issue by patrickpeng2091** [magento/magento2#2456]
I use bin/magento setup:static-content:deploy en_US command ,

But style.css file not found , Access the directory, the file did not find Style.css

![Uploading mage2.png…]()

**Comment by patrickpeng2091** [comment]
![mage2](https://cloud.githubusercontent.com/assets/4326820/11317861/7478eb28-9078-11e5-9989-820c907d6be6.png)
![Uploading mage2.png…]()
![mage21](https://cloud.githubusercontent.com/assets/4326820/11317862/74ad9724-9078-11e5-9d97-720777521855.png)

**Comment by dmitrii-fediuk** [comment]
When you setup Magento 2 into a subdirectory (`/mage2` in your case), you need to do some extra configuration in the `.htaccess` files (in 4 places). Here is my working example: https://mage2.pro/t/23

**Comment by patrickpeng2091** [comment]
hello ,@dfediuk  
My vhost 
<VirtualHost *:80>
    ServerAdmin admin@oucart.com
    DocumentRoot "/home/wwwroot/default"
    ServerName 112.74.112.225
    ErrorLog "/home/wwwlogs/error_apache.log"
    CustomLog "/home/wwwlogs/access_apache.log" common
<Directory "/home/wwwroot/default">
    SetOutputFilter DEFLATE
    Options FollowSymLinks
    Require all granted
    AllowOverride All
    Order allow,deny
    Allow from all
    DirectoryIndex index.html index.php
</Directory>
</VirtualHost>

Add the rules to  4 .htaccess files ？

```
RewriteCond %{HTTP_HOST} ^112.74.112.225\$
RewriteCond %{REQUEST_URI} !^/mage2/
RewriteRule ^(.*)$ /mage2/$1
```

**Comment by patrickpeng2091** [comment]
But more 404 (Not Found)
![m1](https://cloud.githubusercontent.com/assets/4326820/11321663/4de13f0c-9103-11e5-9368-a824f36ca374.png)

**Comment by dmitrii-fediuk** [comment]
You should also grant the proper permissions to the PHP interpreter: http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html

**Comment by patrickpeng2091** [comment]
Thank you ,Finally, set the directory permissions,  solve this problem。

**Comment by daim2k5** [comment]
@oucart thanks for your feedback.

**Comment by Styopchik** [comment]
I'm on Windows 10 x64 with OpenServer. Permissions are set to 777 to entire magento folder. (it's development mashine). Still no /pub/media/styles.css :(
