### ISSUE TITLE
Product Gallery - Magnifier and Breakpoints not affected by view.xml

### ISSUE THREAD

**Issue by jesse-thomas** [magento/magento2#24561]
According to several sources editing the view.xml file should allow you to enable the magnifier on the product view image gallery but making the change 
<var name="enabled">true</var>
does not enable the magnifier, checking the html source shows that magnifierOpts is set to false. 

### Preconditions (*)
composer version 2.3.2
data imported from M1 

### Steps to reproduce (*)
edit the view.xml file for your theme setting enabled to true, clear cache and any static files. 

### Expected result (*)
the template: vendor/magento/module-catalog/view/frontend/templates/product/view/gallery.phtml
 should output the config for magnifierOpts 

### Actual result (*)
magnifierOpts is false. this applies to the breakpoints configured in view.xml as well. 

Editing: vendor/magento/module-catalog/Block/Product/View/Gallery.php
and modifying the getMagnifier() function's return statement like below and clearing cache will enable the magnifier.

public function getMagnifier()
{
    return $this->jsonEncoder->encode($this->getGalleryOptions()->getVar('magnifier'));
}

I know this is not a fix but does demonstrate that vendor/magento/module-catalog/Block/Product/View/Gallery.php does not have access to the data and vendor/magento/module-catalog/Block/Product/View/GalleryOptions.php does. So it feels like something is missing from one of those blocks and probably the template too.

**Comment by engcom-Charlie** [comment]
Hello @jesse-thomas !
I can't reproduce this issue on fresh Magento 2.3-develop & 2.3.2.

**Manual tesing scenario:**

1. Edit the view.xml file for your theme setting enabled to true
2. Clear cache
3. Clear static files
4. Go to the product page

**Actual result:**
Magnifier is ebabled
![image22](https://user-images.githubusercontent.com/51680850/64771232-4b143f80-d557-11e9-84e4-7db5cdf2900a.jpg)

So i close this issue.
Thanks for your report!
