### ISSUE TITLE
Account customer/account/index/ not active in sidebar

### ISSUE THREAD

**Issue by Luuk-Meijer** [magento/magento2#24563]
### Preconditions (*)
1. Magento 2.3.x

### Steps to reproduce (*)
1. Create a customer account
2. Login in that customer account

### Expected result (*)
1. In the sidebar the "Account" item gets an active class

### Actual result (*)
1.  Because the url is customer/account/index/ and not customer/account/ the sidebar gets no active

The "my-account-link" block does go to customer/account and the same with the account link in the sidebar of the customer account.
It's just the redirect when your login in.

**The same happens when you add something to your wishlist**

**Comment by Luuk-Meijer** [comment]
@m2-assistant I can confirm this happens on a vanilla Magento 2.3.2 instance. I'm sure it happens on 2.3.x though.

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24563-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24563-2-3-develop.instances.magento-community.engineering/admin](https://i-24563-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @DeLuuk 
thank you for your report , I checked the issue at magento 2.3-develop instance . It seems this is already fixed at 2.3-develop branch. Please check at magento 2.3-develop instance and update if it still persists

**Comment by Luuk-Meijer** [comment]
Hey @shikhamis11 I see!

Oke very good then.
It will be fixed in 2.3.3 then I presume.

Thanks for looking into this.
