### ISSUE TITLE
Fatal error when creating invoice for order which includes a bundle product with fixed price & sku

### ISSUE THREAD

**Issue by vseager** [magento/magento2#24566]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Create a bundle product. `Dynamic Price` and `Dynamic SKU` must be set to **No** .
2. Please an order which includes the bundle product using payment method "Purchase order".
3. Manually create an invoice for the new order via Magento admin

### Expected result (*)

1. Invoice is created

### Actual result (*)

1. 500 server error with the below stack trace in server logs:

```
[12-Sep-2019 09:22:56 UTC] PHP Fatal error:  Uncaught TypeError: Return value of Magento\InventorySourceSelection\Model\Request\InventoryRequest::getItems() must be of the type array, null returned in /chroot/home/www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102
Stack trace:
#0 /chroot/home/www/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php(97): Magento\InventorySourceSelection\Model\Request\InventoryRequest->getItems()
#1 /chroot/home/www/vendor/magento/module-inventory-source-selection/Model/Algorithms/PriorityBasedAlgorithm.php(73): Magento\InventorySourceSelectionApi\Model\Algorithms\Result\GetDefaultSortedSourcesResult->execute(Object(Magento\InventorySourceSelection\Model\Request\InventoryRequest), Array)
#2 /chroot/home/www/vendor/magento/module-inventory-source-selection-api/Model/SourceSelectionService.php(61) in /chroot/home/www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php on line 102
```

**Comment by ghost** [comment]
:white_check_mark: Confirmed by @vseager
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
@vseager Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24566-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24566-2-3-develop.instances.magento-community.engineering/admin](https://i-24566-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @vseager. 
I'm not able to reproduce the issue as provided steps by you.
Can you please confirm that issue is reproduce on vanilla magento instance.
![image](https://user-images.githubusercontent.com/46617848/64839067-a0ae2200-d613-11e9-805c-a2c21108eed1.png)
Thanks.

**Comment by vseager** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vseager. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vseager, here is your [Magento instance](https://i-24566-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24566-2-3-develop.instances.magento-community.engineering/admin](https://i-24566-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vseager** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @vseager. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @vseager, here is your [Magento instance](https://i-24566-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24566-2-3-2.instances.magento-community.engineering/admin](https://i-24566-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vseager** [comment]
Thanks, I can't reproduce on 2.3 or 2.3-develop.

**Comment by anujeetphj** [comment]
@vseager, were you able to resolve the issue?

Thanks

**Comment by vseager** [comment]
@anujeetphj it wasn't reproducible on 2.3-develop. What version of Magento are you using?

**Comment by anujeetphj** [comment]
I am using @magento2.3.3
And the issue reproduces when
Dynamic price = off
Bundle contains 1 simple and 1 virtual product

Were you able to resolve this in your application @vseager ?

**Comment by isevchris** [comment]
I can see this is an old issue that's been closed, but there still appears to be a bug here which I just encountered on Magento 2.4.1:

**vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php**

line 29: `private $items;`

That will be `null` when an InventoryRequest is instantiated an empty array is passed in for the `$items` parameter; the foreach on line 76 won't do anything.

```
//TODO: Temporary fix for resolving issue with webApi (https://github.com/magento-engcom/msi/issues/1524)
foreach ($items as $item) {
    if (false === $item instanceof ItemRequestInterface) {
        $this->items[] = $this->itemRequestFactory->create([
            'sku' => $item['sku'],
            'qty' => $item['qty']
        ]);
    } else {
        $this->items[] = $item;
    }
}
```

Which means `$this->items` _could_ still be `null` when `getItems()` is called... but that method has been defined that it *must* return an array:

```
public function getItems(): array
{
    return $this->items;
}
```

Which causes it to break.

### Possible fixes

Either add a default value to the $items parameter:
`private $items = [];`

Or ensure `getItems()` always returns an array:
```
public function getItems(): array
{
    return $this->items ?? [];
}
```
