### ISSUE TITLE
Admin order creation wrong address on collectRates

### ISSUE THREAD

**Issue by ageffray** [magento/magento2#24565]
### Preconditions (*)

1. Magento EE B2B 2.3.2 & 2.3-develop
2. Custom carrier
3. Multistore

### Steps to reproduce (*)

1. Create order from Admin
2. Use customer with default billing / shipping address 
3. Add one or more product 
4. Click on "get shipping methods and rates"
5. Use your custom carrier 
6. Change field (postcode, city, region, ...) on billing adress (make sure "Same as billing address" is checked on shipping address form
7. click again on "get shipping methods and rates"

### Expected result (*)

1. Received address information on collectRates() method of carrier must be same as entered on form in $request->getDestXXX (eg: $request->getDestPostcode()) -> $request is \Magento\Quote\Model\Quote\Address\RateRequest)

### Actual result (*)

1. Dest address data on $request is old values which correspond to original billing / shipping adress

**Comment by ageffray** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ageffray. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ageffray, here is your [Magento instance](https://i-24565-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24565-2-3-develop.instances.magento-community.engineering/admin](https://i-24565-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20130` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahsn** [comment]
#mmbr19

**Comment by mahsn** [comment]
#mahsn

**Comment by mahsn** [comment]
#mm19br mahsn

**Comment by magento-engcom-team** [comment]
@mahsn thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mahsn** [comment]
Hi @ageffray  I think this shouldn't be a bug , because there is another option 'Click to change shipping method' to change method of carrier , this option was added by magento especially for solve this problem of carrier selected.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
