### ISSUE TITLE
Catalog Products not updating showing an error of "The stock item was unable to be saved. Please try again."

### ISSUE THREAD

**Issue by grosoasap** [magento/magento2#24570]
### Preconditions (*)

1. Magento Version 2.3.1
2.Staging Website

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. Expect to update the products module like increase quantity and all

### Actual result (*)

1. The stock item was unable to be saved. Please try again. When trying to update the product

2. ![Capture](https://user-images.githubusercontent.com/54885657/64787047-7e71c100-d58d-11e9-93a3-174bac0aaef0.PNG)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-24570-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24570-2-3-develop.instances.magento-community.engineering/admin](https://i-24570-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@grosoasap , I'm unable to regenerate the issue. Please provide steps to regenerate the issue.

**Comment by engcom-Bravo** [comment]
@grosoasap, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
