### ISSUE TITLE
Replace nested arrays in the layout processor in favor of using Array Manager

### ISSUE THREAD

**Issue by iproger** [magento/magento2#24575]
### Summary (*)
There are several places with verbose code of checking and setting layout data that can be reduced.

### Examples (*)
Magento\Checkout\Block\Checkout\LayoutProcessor
```php
if (isset($jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
    ['step-config']['children']['shipping-rates-validation']['children'])) {
    $jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
    ['step-config']['children']['shipping-rates-validation']['children'] =
        $this->processShippingChildrenComponents(
            $jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
            ['step-config']['children']['shipping-rates-validation']['children']
        );
}
```

### Proposed solution
```php
$path = 'components/checkout/children/steps/children/shipping-step/children/step-config/children/shipping-rates-validation/children';
if ($fields = $this->arrayManager->get($path, $jsLayout)) {
    $this->arrayManager->set(...);
}
```

**Comment by engcom-Charlie** [comment]
@iproger Do you want to do PR for it?

**Comment by iproger** [comment]
Yes, I would like.

**Comment by engcom-Charlie** [comment]
@iproger okay, i confirm this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20163` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ronn0** [comment]
Can this one be assigned to me?

**Comment by roerlemans** [comment]
@magento I am working on it

**Comment by roerlemans** [comment]
@magento-engcom-team I am working on it.

**Comment by roerlemans** [comment]
I'm not allowed to add/edit labels. @magento-engcom-team @VitaliyBoyko

**Comment by VitaliyBoyko** [comment]
Hi @ronn0 
Labels being changed automatically and by members of the Magento organization.

The documentation says:
> When the Community Engineering Team works on reviewing the suggested changes, **we will** add a label to the issue to indicate certain information, like the status or who is working the issue. See Labels to learn more.

https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
