### ISSUE TITLE
Cleaning up quotes removes inactive quotes instead of active quotes

### ISSUE THREAD

**Issue by hostep** [magento/magento2#24572]
### Preconditions (*)
1. Magento 2.2.x, 2.3.x, 2.3-develop
2. Make sure you understand the difference between an **inactive** and **active** quote: https://magento.stackexchange.com/q/99224/2911
3. Read the documentation around the "Quote Lifetime" field: https://docs.magento.com/m2/ce/user_guide/sales/cart-quote-lifetime.html - notice that this is about **active** quotes

### Steps to reproduce (*)
1. Setup vanilla 2.3-develop shop
2. Create a product in backend
3. Configure the setting `Stores > Configuration > Sales > Checkout > Shopping Cart > Quote Lifetime (days)` to 1
3. In frontend put product in cart and go through checkout so you have an order (**the quote becomes inactive at this point**)
4. In frontend put a new product in your cart and abandon the shop (**this quote is active at this point**)
5. Sleep for 1 or 2 days
6. Return to shop, make sure the cronjob `sales_clean_quotes` executed a few times while you were asleep
7. Look at the `quote` table in your database

### Expected result (*)
1. You should find 1 quote entry in the database, namely the **inactive** quote (the first one, which is associated to the order)

### Actual result (*)
1. You find 1 quote entry in the database, namely the **active** quote (the one of the customer who abandoned the cart)

### Further discussion
Solution would be to change [this line](https://github.com/magento/magento2/blob/88d78b232184d329dd0af6b06e717a140422e744/app/code/Magento/Sales/Cron/CleanExpiredQuotes.php#L60) from
`$quotes->addFieldToFilter('is_active', 0);`
to
`$quotes->addFieldToFilter('is_active', 1);`

Please verify first if this expected result is correct, if this is validated by somebody who knows how this was supposed to be implemented, then I'll create a PR for fixing this.

**Comment by hostep** [comment]
After thinking on this for a while, I'm wondering why quotes should even be kept at all, even if they are inactive? All data is copied over to the order, so there is not much use anymore after an order was created for quotes?

So maybe we should just delete **all** quotes after the lifetime is expired?
Thoughts?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20172` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
Aha this is coincidental, it looks like this was recently fixed in [MC-19798: 'Quote Lifetime (days)' setting does not work](https://github.com/magento/magento2/commit/2f04e666aceba9bcbd863b78613714922a1f0f35), let's close this then 🙂
