### ISSUE TITLE
Filter groups not applying correctly for customer search

### ISSUE THREAD

**Issue by mlambley** [magento/magento2#24576]
### Preconditions (*)
magento/product-community-edition 2.3.2

### Steps to reproduce (*)
I'm trying to modify the customer filters. See `<backend>/customer/index/index`, click Filters, change a value and click Apply Filters. I'm trying to say "for this particular filter, also search for null values".

The documentation for `\Magento\Framework\Api\Search\FilterGroup` says that it "Groups two or more filters together using a logical OR" so in theory I just need to add an extra filter to the filter group.

To achieve this I've created a di.xml as follows:
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
  <type name="Magento\Framework\Api\Search\ReportingInterface">
    <plugin name="customer_grid_collection" type="Vendor\Module\Plugin\Reporting"/>
  </type>
</config>
```

The plugin class has:

```php
public function beforeSearch(ReportingInterface $subject, SearchCriteriaInterface $searchCriteria)
{
    foreach ($searchCriteria->getFilterGroups() as $filterGroup) {
        foreach ($filterGroup->getFilters() as $filter) {
            if ($myConditionsAreMet) {
                $filterGroup->setFilters(array_merge(
                    $filterGroup->getFilters(),
                    [new Filter([
                        'field' => $filter->getField(),
                        'value' => true,
                        'condition_type' => 'null',
                    ])]
                ));
                return [$searchCriteria];
            }
        }
    }
    return [$searchCriteria];
}
```

To debug this I have another function in the plugin class:

```php
public function afterSearch(ReportingInterface $subject, SearchResultInterface $collection)
{
    $this->log($collection->getSelect()->__toString());
    return $collection;
}
```

### Actual result (*)
The afterSearch function outputs the following:
```
SELECT `main_table`.* FROM `customer_grid_flat` AS `main_table` 
WHERE (`my_field` LIKE \'%value%\') AND (`my_field` IS NULL)
```

The filters are AND'd together. This is the same as https://github.com/magento/magento2/issues/4287 which says that the issue has been fixed. Rather than re-open it I thought I would post my issue here.

Looking at `\Magento\Framework\View\Element\UiComponent\DataProvider\FilterPool` the `applyFilters` function loops through each group, then each filter, and applies each filter one at a time, completely ignoring the fact that groups should be processed together. So even if I were to create my own filterApplier here, it won't fix my problem since my applier will receive the filters one at a time.

### Expected result (*)
I would expect to see, as per the intended behaviour of `FilterGroup`, for my filters to be OR'd together like the following:
```
... WHERE ((`my_field` LIKE \'%value%\') OR (`my_field` IS NULL))
```

Thank you.

**Comment by mlambley** [comment]
I have confirmed that this behaviour is still present in 2.3-develop https://github.com/magento/magento2/blob/48089771bfa460b842ea5be17dc8cc20e8fba9f5/lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/FilterPool.php#L37

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20143` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by adrianadi** [comment]
Hi @mlambley , @magento-engcom-team (cc @osrecio) trying to help you out as part of MM19ES Contribution Days

The reason why this happens is that the applier ultimately makes use of `\Magento\Framework\Data\Collection::addFieldToFilter()` who expects a certain format for getting an OR condition concatenation.

Therefore, a simple workaround, which would ultimately help out towards a solution would be to merge together field name and field value like this:

`$filter->setField([$filter->getField(), $filter->getField()]);
$filter->setValue([$filter->getConditionType() => $filter->getValue(), 'eq' => new \Zend_Db_Expr('null')]);`

Then we could use a custom applier injected into `Magento\Framework\View\Element\UiComponent\DataProvider\FilterPool` which is applying the filter as simple as:

`$collection->addFieldToFilter($filter->getField(), $filter->getValue());`

Just thinking it out loud, what do you think?

**Comment by adrianadi** [comment]
Otherwise, a cleaner solution (which at this point I don't know how to make it BC) would be passing the entire `FilterGroup` to a supposedly new `FilterGroupApplierInterface::apply()`.

**Comment by mlambley** [comment]
@adrianadi From my experience with Magento they're not afraid to make breaking changes so fixing it properly, even if it means waiting until 2.4, would be better.

I was thinking to add a second property `$filterAppliers` to `FilterPool`, then the `applyFilters` function could check both $appliers and $filterAppliers in a backwards compatible manner. Then the breaking change would be to remove $appliers altogether.

**Comment by gwharton** [comment]
```
        $statuses = [
            "holded",
            "pending",
            "payment_review",
            "pending_payment"
        ];
        $onHoldSearchCriteria = $this->searchCriteriaBuilder->create();
        foreach ($statuses as $status) {
            $filter = $this->filterBuilder->setField('status')
                ->setValue($status)
                ->setConditionType('eq')
                ->create();
            $this->filterGroupBuilder->addFilter($filter);
        }
        $filtergroup = $this->filterGroupBuilder->create();
        
        $pinnedSearchCriteria->setFilterGroups(([$filtergroup]));
```

Results in

`SELECT `main_table`.* FROM `sales_order` AS `main_table` WHERE (`main_table`.`status` = 'holded') AND (`main_table`.`status` = 'pending') AND (`main_table`.`status` = 'payment_review') AND (`main_table`.`status` = 'pending_payment') GROUP BY `main_table`.`entity_id``

Looks like this is still bad in 2.4

**Comment by rohit-wagento** [comment]
@magento I'm working on this

**Comment by rohit-wagento** [comment]
I will review on this, it seems takes time to debug into this, i will update into this if i found something.

**Comment by mlambley** [comment]
Which PR/commit if you don't mind me asking? Just curious.
