### ISSUE TITLE
The value you set has already been locked. To change the value, use the --lock-env option

### ISSUE THREAD

**Issue by rpss2** [magento/magento2#24574]
I trying change Base URL for Static View Files and Base URL for User Media Files by Magento CLI, but this message always appear, when I don't use --lock-env or --lock-config flag: "The value you set has already been locked. To change the value, use the --lock-env option". In Magento Admin, these fields are locks. I only get change by command: magento-cli config:sensitive:set --lock-env web/unsecure/base_static_url http://example.com/pub/static/.
How I unlock Magento Admin for edit these fields???

**Comment by rpss2** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rpss2. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rpss2, here is your [Magento instance](https://i-24574-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24574-2-3-develop.instances.magento-community.engineering/admin](https://i-24574-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rpss2** [comment]
In your instance, is possible edit, but if change by Magento CLI using --lock-env flag, don't possible editing more. I need access your instance by CLI.

**Comment by engcom-Bravo** [comment]
Hello @rpss2. Thanks for applying. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
