### ISSUE TITLE
Downloadable selected links price not added to product main price on cart configure page.

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24579]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.19

### Steps to reproduce (*)

1. Create a downloadable product with some downloadable links
2. Select link and add to cart
3. edit that product from cart

### Expected result (*)
![downloadable-expected](https://user-images.githubusercontent.com/44425160/64838272-10221280-d610-11e9-814d-6dacefef9a33.png)

### Actual result (*)

![downloadable](https://user-images.githubusercontent.com/44425160/64838293-1ca66b00-d610-11e9-94dc-618a49c6a72b.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24579-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24579-2-3-develop.instances.magento-community.engineering/admin](https://i-24579-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Issue reproduced on 2.3 Version.
@rani-webkul - In Prdocut page (After clicking on Edit link on Shopping cart page) in the first time it is displaying 0.0 price but after select any other downloadable links, Total price is displaying. 

**Expected result:** On the first time, Selected product price should be displayed on the update product page.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20140` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
@magento give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by sunilit42** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-24579-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24579-2-3-develop.instances.magento-community.engineering/admin](https://i-24579-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sunilit42** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-24579-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24579-2-3-develop.instances.magento-community.engineering/admin](https://i-24579-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24580 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [3d07b8ee783b70c1916c05a96f361ddeb9be7d63](https://github.com/magento/magento2/commit/3d07b8ee783b70c1916c05a96f361ddeb9be7d63)
 - [2f6332ca6be7eeb9a7abae0ab7ffd83fff725ee7](https://github.com/magento/magento2/commit/2f6332ca6be7eeb9a7abae0ab7ffd83fff725ee7)

The fix will be available with the upcoming 2.3.4 release.
