### ISSUE TITLE
Create new store with existing stores with  config.php

### ISSUE THREAD

**Issue by klict** [magento/magento2#24584]
### Preconditions (*)

1.Magento 2.3.2
2.php7.2
3.have few stores installed with products and categories

### Steps to reproduce (*)

1. Create or modify config.php file

```<?php
return [
    'modules' => [ /** enabled modules **/],
    'scopes' => [
        'websites' => [
            'existing1' => [
                'website_id' => '0',
                'code' => 'existing1',
                'name' => 'Existing1 Website',
                'sort_order' => '0',
                'default_group_id' => '0',
                'is_default' => '0'
            ],
            'existing2' => [
                'website_id' => '1',
                'code' => 'existing2',
                'name' => 'Existing2 Website',
                'sort_order' => '0',
                'default_group_id' => '1',
                'is_default' => '1'
            ],
            'toBeCreated' => [
                'website_id' => '2',
                'code' => 'toBeCreated',
                'name' => 'To Be Created Website',
                'sort_order' => '1',
                'default_group_id' => '2',
                'is_default' => '0'
            ],
        ],
        'groups' => [
            [
                'group_id' => '0',
                'website_id' => '0',
                'name' => 'Existing1 Store',
                'root_category_id' => '0',
                'default_store_id' => '0',
                'code' => 'existing1'
            ],
            [
                'group_id' => '1',
                'website_id' => '1',
                'name' => 'Existing2 Store',
                'root_category_id' => '2',
                'default_store_id' => '1',
                'code' => 'main_website_store'
            ],
            [
                'group_id' => '2',
                'website_id' => '2',
                'name' => 'To Be Created Store',
                'root_category_id' => '2',
                'default_store_id' => '2',
                'code' => 'toBeCreated'
            ]
        ],
        'stores' => [
            'existing1' => [
                'store_id' => '0',
                'code' => 'existing1',
                'website_id' => '0',
                'group_id' => '0',
                'name' => 'Existing1 Store View',
                'sort_order' => '0',
                'is_active' => '1'
            ],
            'existing2' => [
                'store_id' => '1',
                'code' => 'existing2',
                'website_id' => '1',
                'group_id' => '1',
                'name' => 'Existing2 Store View',
                'sort_order' => '0',
                'is_active' => '1'
            ],
            'toBeCreated' => [
                'store_id' => '2',
                'code' => 'toBeCreated',
                'website_id' => '2',
                'group_id' => '2',
                'name' => 'ToBeCreated Store View',
                'sort_order' => '1',
                'is_active' => '1'
            ],
        ]
    ]
];
```
3. run `bin/magento setup:upgrade`

### Expected result (*)
```
These Websites will be updated: Existing1 Website, Existing2 Website
These Websites will be created: To Be Created Website
These Groups will be updated: Existing1 Store, Existing2 Store
These Groups will be created: To Be Created Store
These Stores will be updated: Existing1 Store View, Existing2 Store View
These Stores will be created: ToBeCreated Store View
Do you want to continue [yes/no]?
yes
Stores were processed
The following new store groups must be associated with a root category: To Be Created Store. 
```

### Actual result (*)

1. I get following message `Import failed: Validation Failed`
2. From exception.log file:

> [2019-09-13 11:40:01] report.ERROR: Validation Failed {"exception":"[object] (Magento\\Framework\\Exception\\State\\InvalidTransitionException(code: 0): Validation Failed at /home/user/Documents/dev/project/project-magento/vendor/magento/module-store/Model/Config/Importer.php:115, Magento\\Framework\\Exception\\RuntimeException(code: 0): Validation Failed at /home/user/Documents/dev/project/project-magento/vendor/magento/module-store/Model/Config/Importer/Processor/Create.php:123, Magento\\Framework\\Validation\\ValidationException(code: 0): Validation Failed at /home/user/Documents/dev/project/project-magento/vendor/magento/module-inventory/Model/Stock/Command/Save.php:59)"} 

### Useful notes
The `app:config:import` command does not fail and if you run `setup:upgrade` command twice it will succeed

**Comment by luanalves** [comment]
@klict I try your issue, but i don't find this problem.
I think the problem is because the information about previously created websites and stores has changed. By default this information should be.

`
'scopes' => [
        'websites' => [
            'admin' => [
                'website_id' => '0',
                'code' => 'admin',
                'name' => 'Admin',
                'sort_order' => '0',
                'default_group_id' => '0',
                'is_default' => '0',
            ],
            'base' => [
                'website_id' => '1',
                'code' => 'base',
                'name' => 'Main Website',
                'sort_order' => '0',
                'default_group_id' => '1',
                'is_default' => '1',
            ],
        ],
        'groups' => [
            0 => [
                'group_id' => '0',
                'website_id' => '0',
                'name' => 'Default',
                'root_category_id' => '0',
                'default_store_id' => '0',
                'code' => 'default',
            ],
            1 => [
                'group_id' => '1',
                'website_id' => '1',
                'name' => 'Main Website Store',
                'root_category_id' => '2',
                'default_store_id' => '1',
                'code' => 'main_website_store',
            ],
        ],
        'stores' => [
            'admin' => [
                'store_id' => '0',
                'code' => 'admin',
                'website_id' => '0',
                'group_id' => '0',
                'name' => 'Admin',
                'sort_order' => '0',
                'is_active' => '1',
            ],
            'default' => [
                'store_id' => '1',
                'code' => 'default',
                'website_id' => '1',
                'group_id' => '1',
                'name' => 'Default Store View',
                'sort_order' => '0',
                'is_active' => '1',
            ],
        ],
    ],
`

Getting the complete solution like this

`
'scopes' => [
        'websites' => [
            'admin' => [
                'website_id' => '0',
                'code' => 'admin',
                'name' => 'Admin',
                'sort_order' => '0',
                'default_group_id' => '0',
                'is_default' => '0',
            ],
            'base' => [
                'website_id' => '1',
                'code' => 'base',
                'name' => 'Main Website',
                'sort_order' => '0',
                'default_group_id' => '1',
                'is_default' => '1',
            ],
            'toBeCreated' => [
                'website_id' => '2',
                'code' => 'toBeCreated',
                'name' => 'To Be Created Website',
                'sort_order' => '1',
                'default_group_id' => '2',
                'is_default' => '0',
            ],
        ],
        'groups' => [
            0 => [
                'group_id' => '0',
                'website_id' => '0',
                'name' => 'Default',
                'root_category_id' => '0',
                'default_store_id' => '0',
                'code' => 'default',
            ],
            1 => [
                'group_id' => '1',
                'website_id' => '1',
                'name' => 'Main Website Store',
                'root_category_id' => '2',
                'default_store_id' => '1',
                'code' => 'main_website_store',
            ],
            2 => [
                'group_id' => '2',
                'website_id' => '2',
                'name' => 'To Be Created Store',
                'root_category_id' => '2',
                'default_store_id' => '2',
                'code' => 'toBeCreated',
            ],
        ],
        'stores' => [
            'admin' => [
                'store_id' => '0',
                'code' => 'admin',
                'website_id' => '0',
                'group_id' => '0',
                'name' => 'Admin',
                'sort_order' => '0',
                'is_active' => '1',
            ],
            'default' => [
                'store_id' => '1',
                'code' => 'default',
                'website_id' => '1',
                'group_id' => '1',
                'name' => 'Default Store View',
                'sort_order' => '0',
                'is_active' => '1',
            ],
            'toBeCreated' => [
                'store_id' => '2',
                'code' => 'toBeCreated',
                'website_id' => '2',
                'group_id' => '2',
                'name' => 'ToBeCreated Store View',
                'sort_order' => '1',
                'is_active' => '1',
            ],
        ],
    ],

Evidences:
![Captura de tela de 2019-09-14 15-44-12](https://user-images.githubusercontent.com/1495258/64912496-9587ee80-d706-11e9-8bc8-4e4ef36ea51c.png)
![Captura de tela de 2019-09-14 15-44-29](https://user-images.githubusercontent.com/1495258/64912497-9587ee80-d706-11e9-9384-67836f2b3cdd.png)

`

**Comment by klict** [comment]
Hey @luanalves, thank you for your message. 

I still have  issue on my vanilla Magento instance. I took the following steps:

1. create new stores manually in Magento 
2. make sure that config.php aligns with existing stores.
3. Modified config.php to create new stores:
```
'scopes' => [
        'websites' => [
            'admin' => [
                'website_id' => '0',
                'code' => 'admin',
                'name' => 'Admin',
                'sort_order' => '0',
                'default_group_id' => '0',
                'is_default' => '0'
            ],
            'existing1' => [
                'website_id' => '1',
                'code' => 'existing1',
                'name' => 'Existing1 Website',
                'sort_order' => '0',
                'default_group_id' => '1',
                'is_default' => '1'
            ],
            'existing2' => [
                'website_id' => '2',
                'code' => 'existing2',
                'name' => 'Existing2 Website',
                'sort_order' => '0',
                'default_group_id' => '2',
                'is_default' => '0'
            ],
            'toBeCreated' => [
                'website_id' => '10',
                'code' => 'test10',
                'name' => 'To Be Created Website Test',
                'sort_order' => '1',
                'default_group_id' => '0',
                'is_default' => '0'
            ]
        ],
        'groups' => [
            [
                'group_id' => '0',
                'website_id' => '0',
                'name' => 'Default',
                'root_category_id' => '0',
                'default_store_id' => '0',
                'code' => 'default'
            ],
            [
                'group_id' => '1',
                'website_id' => '1',
                'name' => 'Existing1 Store',
                'root_category_id' => '2',
                'default_store_id' => '1',
                'code' => 'existing1'
            ],
            [
                'group_id' => '2',
                'website_id' => '2',
                'name' => 'Existing2 Store',
                'root_category_id' => '2',
                'default_store_id' => '2',
                'code' => 'existing2'
            ],
            [
                'group_id' => '10',
                'website_id' => '10',
                'name' => 'To Be Created Store Test',
                'root_category_id' => '2',
                'default_store_id' => '0',
                'code' => 'test10'
            ]
        ],
        'stores' => [
            'admin' => [
                'store_id' => '0',
                'code' => 'admin',
                'website_id' => '0',
                'group_id' => '0',
                'name' => 'Admin',
                'sort_order' => '0',
                'is_active' => '1'
            ],
            'existing1' => [
                'store_id' => '1',
                'code' => 'existing1',
                'website_id' => '1',
                'group_id' => '1',
                'name' => 'Existing1 Store View',
                'sort_order' => '0',
                'is_active' => '1'
            ],
            'existing2' => [
                'store_id' => '2',
                'code' => 'existing2',
                'website_id' => '2',
                'group_id' => '2',
                'name' => 'Existing2 Store View',
                'sort_order' => '0',
                'is_active' => '1'
            ],
            'test10' => [
                'store_id' => '10',
                'code' => 'test10',
                'website_id' => '10',
                'group_id' => '10',
                'name' => 'ToBeCreated Store View test',
                'sort_order' => '1',
                'is_active' => '1'
            ]
        ]
    ]
```
4. Run `bin/magento setup:upgrade`

Result 
`bin/magento setup:upgrade` : Import failed: Validation Failed
But when I run `bin/magento app:config:import'  it succeeds. 

So why does `bin/magento app:config:import'  work but not `bin/magento setup:upgrade' ? that's the issue I am stuck with.

Edit:
Could you also test with store_id, website_id and group_id above next incremental one?

**Comment by luanalves** [comment]
@klict 
I did as you said, created a new website, then ran the command bin / magento app: config: dump, it generated another app file / etc / config.php and then put another store in this file and ran the command bin / magento setup: upgrade.
Were these steps you used?
My tests consist of Magento 2.3.2, sample data and Luma theme.
If the steps are the same, could you share your database for testing?

**Comment by klict** [comment]
Hey,
For now, I am gonna close this issue because I can't seem to solve it. In the future it may be reopened  by my colleagues when they work on this.

Thank you for your help and time. I appreciate it allots.

**Comment by dasithaaligent** [comment]
I also found this error and it seems like we are getting it when we don't have the website code related record in the **store_website** table.

Because I found the below error when added some extra logs to get the validation error message.

```
Magento\Inventory\Model\Stock\Command\Save

 public function execute(StockInterface $stock): int
    {
        $validationResult = $this->stockValidator->validate($stock);
        $this->logger->info(
            'stock validation result : ',
            [
                'is_valid' => $validationResult->isValid(),
                'result' => $validationResult->getErrors()
            ]
        );
        if (!$validationResult->isValid()) {
            throw new ValidationException(__('Validation Failed'), null, 0, $validationResult);
        }

        try {
            $this->stockResource->save($stock);
            return (int)$stock->getStockId();
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage());
            throw new CouldNotSaveException(__('Could not save Stock'), $e);
        }
    }

```
`[2023-04-07T07:21:45.281032+00:00] report.INFO: stock validation result :  {"is_valid":false,"result":[{"Magento\\Framework\\Phrase":"The website with code \"website-code\" does not exist."}]} []`

```
Line 70 - vendor/magento/module-inventory-sales/Model/Stock/Validator/SalesChannelsValidator.php
Line 75 - vendor/magento/module-store/Model/WebsiteRepository.php
```

However, when we execute `app:config:import` or `setup:upgrade` again this record will not be seen since that record is already created at that time.

Cheers!
