### ISSUE TITLE
Custom Customer Address attribute does not get saved

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#2458]
LE: Nvm.

**Comment by daim2k5** [comment]
So basically your are on a old beta version and can't upgrade to 2.0.0 because?

**Comment by adragus-inviqa** [comment]
That's M2 EE merchant beta 7.

**Comment by daim2k5** [comment]
Maybe @mazhalai can tell us if we can help your here with a EE Version

**Comment by adragus-inviqa** [comment]
Finally, I made it work.

First, I had to a) create the attribute with `'system' => 0`, then b) I had to fix a possible bug which didn't insert a record in the `customer_form_attribute` when adding my new attribute - so I had to do it myself.

a) fixed my attribute now getting added in the `custom_attributes` of the Customer Address Data and b) fixed my attribute not getting saved in admin.

This is how my new setup script looks like now:
```php
public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
{
    /** @var \Magento\Customer\Setup\CustomerSetup $setup */
    $setup = $this->customerSetupFactory->create(['setup' => $setup]);

    $setup->addAttribute('customer_address', 'xxx', [
        'type' => 'varchar',
        'input' => 'text',
        'label' => 'Xxx',
        'global' => 1,
        'visible' => 1,
        'required' => 0,
        'system' => 0,
        'user_defined' => 0,
        'visible_on_front' => 1,
        'group' => 'General',
        // 'used_in_forms' => [ 'adminhtml_customer_address' ] <-- this doesn't work
    ]);

    $setup->getSetup()
          ->getConnection()
          ->insert(
              $setup->getSetup()->getTable('customer_form_attribute'),
              [
                  'form_code' => 'adminhtml_customer_address',
                  'attribute_id' => $setup->getAttribute('customer_address', 'xxx', 'attribute_id')
              ]
          );
}
```
So the Data transferring seems OK. Now the problems is the `used_in_forms` key _not_ being used when creating a Customer Address attribute.

**Comment by adragus-inviqa** [comment]
This seems to have the same solution/suggestions as https://github.com/magento/magento2/issues/1238#issuecomment-105034397. But don't worry, you guys marked it as resolved, so we're all good. Nothing wrong with creating an attribute which isn't saved.

**Comment by adragus-inviqa** [comment]
So when creating customer and customer address attributes, do we have to remember to add to customer_form assocation ourselves? So there's no point in having `used_in_forms` when creating such an attribute?

How's this _not_ a problem?

**Comment by adragus-inviqa** [comment]
Right. No more reporting in github from me. You people are so quick on closing issues.

**Comment by mazhalai** [comment]
@adragus-inviqa can you please be more specific about your problem? If it is an EE issue, please report an issue via the partner portal.

**Comment by benmarks** [comment]
@adragus-inviqa Can you elaborate on the original post? Did you edit it?

**Comment by adragus-inviqa** [comment]
@mazhalai - yes, that's the plan from now on. Thanks.

@benmarks - I've worked too hard not only _because_ of this particular issue, but for _reporting_ it clearly and detailed as well - just to end up closed so quickly. So I've lost my temper there for a second. If someone can delete this issue, that'll be fine by me.

**Comment by daim2k5** [comment]
Hi @adragus-inviqa i closed that ticket because i was thinking that issue was resolved. You written before "This seems to have the same solution/suggestions as #1238 (comment). But don't worry, you guys marked it as resolved, so we're all good. Nothing wrong with creating an attribute which isn't saved."

So maybe i misunderstood your sentence.

**Comment by daim2k5** [comment]
Also if you give me the permission i would like to restore your issue.

**Comment by Vinai** [comment]
:(

**Comment by sjavalv** [comment]
Trying to add attribute from admin to customer.

Error: _We can't save the customer address attribute right now._

Solutions?
