### ISSUE TITLE
actions.js does not support callbacks

### ISSUE THREAD

**Issue by j-robin-hunter** [magento/magento2#24594]
### Preconditions (*)

1. version 2.3.2 CE
2. Similar to #1527 but suggested approach will not work for actions.js

### Steps to reproduce (*)

1. Define a ui grid actionColumn for example:	
`<actionsColumn name="actions" class="name\module\Ui\Component\Listing\Product\Column\PostActions">
	<argument name="data" xsi:type="array">
		<item name="config" xsi:type="array">
			<item name="resizeEnabled" xsi:type="boolean">false</item>
			<item name="resizeDefaultWidth" xsi:type="string">10</item>
			<item name="indexField" xsi:type="string">attachment_id</item>
		</item>
	</argument>
</actionsColumn>`

2. Define actions

`if (isset($dataSource['data']['items'])) {
  foreach ($dataSource['data']['items'] as & $item) {
    $name = $this->getData('name');
    $this->_logger->info($name);
    if (isset($item['entity_id'])) {
      $item[$name]['edit'] = [
        'label' => __('Edit'),
        'callback' => 'myCustomCallbackName'
      ];
      $item[$name]['delete'] = [
        'href' => $this->urlBuilder->getUrl(self::DELETE, ['entity_id' => $item['entity_id']]),
        'label' => __('Delete'),
        'confirm' => [
          'title' => __('Delete'),
          'message' => __('Are you sure you wan\'t to delete this record?')
        ]
      ];
    }
  }
}`
### Expected result (*)

1.The callback should be detected as an object in action.js and used in place of the default

### Actual result (*)

1. action.js interprets 'myCustomCallbackName' as a string and not an object and calls default callback

**Comment by j-robin-hunter** [comment]
Confirmed as behaviour in vanilla 2.3 release

**Comment by VladimirZaets** [comment]
#mm19pl

**Comment by michalwolek** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
@miwol thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by j-robin-hunter** [comment]
Magento\Customer\Ui\Component\Listing\Address\Column\Actions.php shows how the callback can be specified as an array. However, there seems no way to specify a single callback function.

**Comment by engcom-Foxtrot** [comment]
Hello, @j-robin-hunter. Thank you for collaboration.
Currently, the callback cannot be a function, it should be an object implementing a [ColumnAction interface](https://devdocs.magento.com/guides/v2.3/ui_comp_guide/components/ui-column.html#column_action). If you think Magento should support defining callback with the function, please open a new feature request.
