### ISSUE TITLE
Cache and reindex select actions not overlapping

### ISSUE THREAD

**Issue by ClaudiuCreanga** [magento/magento2#2459]
When you're clicking on the select actions, for example to select all types of cache, it does nothing. You have to click higher in order to click the select. See attached screenshot, the select and label do not overlap. This happens on all screen sizes, chrome browser. 
![screen shot 2015-11-21 at 17 15 24](https://cloud.githubusercontent.com/assets/7690659/11319592/04dd1996-9074-11e5-97d6-073b83253ffe.png)

**Comment by MomotenkoNatalia** [comment]
Hi @ClaudiuCreanga! Thanks for reporting this bug. We have already fix this issue. Internal ticket MAGETWO-45546. Feel free to reopen if you have any questions.
