### ISSUE TITLE
logo.phtml, @var $storeName not defined

### ISSUE THREAD

**Issue by Amadeco** [magento/magento2#2460]
Line 20 :

```
<a href="<?php echo $block->getUrl(''); ?>" class="logo navbar-brand" title="<?php /* @escapeNotVerified */ echo $storeName ?>">

```

replace

```
<a href="<?php echo $block->getUrl(''); ?>" class="logo navbar-brand" title="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>">

```

Cheers

**Comment by daim2k5** [comment]
@mageho do you like to create a Pull Request?

**Comment by Amadeco** [comment]
Hello daim2k5,
I am not very familiar with Github, but ok, copy / paste to pull request section !

**Comment by davidalger** [comment]
Closing due to lack of response, also referenced template declares $storeName near top of template, so this undefined var error can't occur (in latest mainline at least) without the template having been modified.
