### ISSUE TITLE
Product Compare doesn't work for products with OUT_OF_STOCK status even when Display Out of Stock Products is enabled

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#24617]
### Preconditions (*)

1. Sample Data
2. Display Out of Stock Products is set to Yes

### Steps to reproduce (*)

1. Find the product in the admin panel by SKU: MH01 and open it
2. Expand Configurations tab
3. Click **Edit Configurations** > **Next** > **Next**
4. Under **Quantity** enable **Apply single quantity to each SKUs** and set it to 0
5. Click **Next** > **Generate Products**
6. Save the product.
7. Open the product by searching. Verify that it has OUT_OF_STOCK status.
8. Click **Add to compare**

### Expected result (*)

1. The product can be added to the comparison list or the button is disabled otherwise.

### Actual result (*)

1.  Page reloads without warnings or useful side-effects. You can verify it here http://graphql-ce.loc/catalog/product_compare/

**Comment by sudheers-kensium** [comment]
Hello @TomashKhamlai Thanks for your report, this issue is already confirmed you can check #24555

**Comment by TomashKhamlai** [comment]
@sudheers-kensium, yeah it almost a duplicate. Issue #24555 shows that it is reproducible after upgrading and this issue shows the problem on a clean install. My issue will be referenced to another project. We need detailed step-by-step scenarios to show different aspects of the problem. I believe that somebody from maintainers team will close this as duplicate as soon as the processing of the PR for this problem will be started by someone from community maintainers.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20169` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MaxSouza** [comment]
@TomashKhamlai Please, take a look at #24620

**Comment by TomashKhamlai** [comment]
Still an issue for me

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20199` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
