### ISSUE TITLE
Display Out of Stock Products configuration option has an impact on Product Compare functionality

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#24620]
### Preconditions (*)

1. Sample Data
2. Display Out of Stock Products is set to No (System Default value)

### Steps to reproduce (*)

1. Find the product **Chaz Kangeroo Hoodie** (SKU: MH01) from the Storefront and add to compare
2. Login to Admin
3. Find the product in the admin panel by SKU: MH01 and open it
4. Expand Configurations tab
5. Click **Edit Configurations** > **Next** > **Next**
6. Under **Quantity** enable **Apply single quantity to each SKUs** and set it to 0
7. Click **Next** > **Generate Products**
8. Save the product.
9. Copy the URL key of the product and construct the products URL:
{{base_url}} + / + {{URL_key}} + {{product_URL_suffix}}, for example http://graphql-ce.loc/chaz-kangeroo-hoodie.html
Verify that it has OUT_OF_STOCK status.
8. Navigate to {{base_url}}/catalog/product_compare/

### Expected result (*)

1. The Out of Stock Products configuration option has no impact on Product Compare functionality
![Screenshot_20190916_140835](https://user-images.githubusercontent.com/11827230/64958488-f5fa6580-d897-11e9-816f-51f858b03090.png)

### Actual result (*)

1.  We see in the top right that there is one item in the comparison list  
![image](https://user-images.githubusercontent.com/11827230/64958013-d7e03580-d896-11e9-8cc7-aafd8755ed1d.png)
2. We see the message "You have no items to compare."

**Comment by TomashKhamlai** [comment]
The problem with removing items from the comparison list is already described in #24582. This issue is about products visibility in the context of Product Compare functionality.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20170` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MaxSouza** [comment]
#mm19br

**Comment by MaxSouza** [comment]
@TomashKhamlai 

You need change "Display Out of Stock Products" to "Yes" and run reindex.

![image](https://user-images.githubusercontent.com/5350377/64984211-aff1d180-d898-11e9-9864-53a0ac88b9e9.png)

After this, we can see product to compare. If  "Display Out of Stock Products" is "No", magento cleans all records about price from product on  catalog_product_index_price

**Comment by TomashKhamlai** [comment]
Please, take a look at #24617

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20201` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @TomashKhamlai 

After a discussion with Product Manager, we close this issue.
It is expected behavior if "Display Out of Stock Products is set to No"
