### ISSUE TITLE
Can't see Add Product Page Backend

### ISSUE THREAD

**Issue by influxive** [magento/magento2#2462]
Add product page in backned is empty
plz sort and help

**Comment by vkholoshenko** [comment]
Hi, @influxive! I can't reproduce this on Magento 2 stable (2.0.0). 
Could you please verify whether the issue still present?

**Comment by influxive** [comment]
yes it is still
i tried to import products from 1.9.2 and all products were imported
but after that neither i can add products or edit products coz its always blank

**Comment by vkholoshenko** [comment]
@influxive, it looks like there is an exception during form rendering. Could you please attach your var/log/system.log and var/report/\* files ?

**Comment by vkholoshenko** [comment]
Hi, @influxive. We haven't heard back from you and, thus, will proceed with closing this issue. In case you have anything to add, please don't hesitate to reopen it.
