### ISSUE TITLE
2 Active categories after flushing Magento cache, while browser tab open on category page

### ISSUE THREAD

**Issue by Jeroen999** [magento/magento2#24629]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Open a browser and click on a category in the navigation menu.
2. Flush Magento cache.
3. Click on other categories.

### Expected result (*)

1. Only the last clicked category should have the active category css.
2. If I go to the home page, then there should be no active category.

### Actual result (*)

1. Two categories have the active category css.
2. When I navigate to the home page, one category still has the active category css.

This doesn't happen when I open another browser after flushing Magento cache or when I flush Magento cache while I'm on the home page.

**Comment by Jeroen999** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Jeroen999. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jeroen999, here is your [Magento instance](https://i-24629-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24629-2-3-develop.instances.magento-community.engineering/admin](https://i-24629-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jeroen999** [comment]
I have created 3 subcategories: Test category 1, Test category 2 and Test category 3. In the attached print screen, you can see that I have reproduced this issue in the develop instance.

![2019-09-17 two active categories](https://user-images.githubusercontent.com/55445180/65044883-1260d580-d95e-11e9-92f5-a3ec62e692d3.png)

**Comment by Jeroen999** [comment]
Issue: Confirmed

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20204` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kvydiuk** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kirillvidyuk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kirillvidyuk, here is your [Magento instance](https://i-24629-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24629-2-3-develop.instances.magento-community.engineering/admin](https://i-24629-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kvydiuk** [comment]
Hi @Jeroen999,

I couldn't reproduce issue with Built-In full page cache type.
Even when i enabled Varnish cache, the navigation menu disappeared from page at all.
The menu didn't appear even after an hour for me (expected that ESI ttl=3600 for this block will make the deal):
https://drive.google.com/file/d/1F7doA1e1dPUVwjnHMZBgEQ2rTt7E0LyD/view
Suppose that this could environment specific issue.
And could relates to https://github.com/magento/magento2/issues/3897
All testing was performed on develop instance that was provided by @magento-engcom-team.

Did you have any extra information which would help to reproduce a bug?

Regards,
Kirill

**Comment by engcom-Bravo** [comment]
Yes, @kirillvidyuk, it seems like some silent fix has taken its place. Now I am also not able to reproduce the issue on the develop instance though at that time it was easily reproducible. The issue still persists in 2.3.2 version (just tested) Could You @Jeroen999 also retest it now on the latest develop version. Thank You.

**Comment by Jeroen999** [comment]
Okay, give me 2.3-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance for @Jeroen999

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-24629-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24629-2-3-develop.instances.magento-community.engineering/admin](https://i-24629-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jeroen999** [comment]
I can't reproduce this issue in this development version, so I think this issue has been solved.

**Comment by engcom-Bravo** [comment]
Ok, Thank You all @Jeroen999 , @kirillvidyuk.

**Comment by duckchip** [comment]
I think this is related to https://github.com/magento/magento2/issues/24776#issuecomment-536212975
