### ISSUE TITLE
Webapi Swagger schema generation fail in case when Get endpoint has param with Extension Attributes [Case#2]

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#24626]
After refactoring which was done in 735024aef05ccf39412b343439b074129a8dfdaa, the issue https://github.com/magento/magento2/issues/24116 is come back.
Original report: [tap](https://testing-service.magento-community.engineering/reports/magento/inventory/pull/2509/c596c0daf17e77fc8ca757ec38e7d757/Integration/allure-report-ce/index.html#categories/f48e7d3623b476c0129b7c130cbc68bf/db7fff094b014ee3/)

### Preconditions (*)
1. Magento 2.3.1 & 2.3-develop
2. Created and enabled custom module 'DreamVendor\DreamModule'.

### Steps to reproduce (*)
1. Create php interface which will be used for the endpoint. E.g.
```
namespace DreamVendor\DreamModule\Api;

use Magento\Framework\Api\Search\SearchResultInterface;

/**
 * My Custom Endpoint API.
 */
interface MyCustomEndpointInterface
{
    /**
     * Get some awesome stuff!
     *
     * @param \DreamVendor\DreamModule\Api\Data\SearchRequestInterface $searchRequest
     *
     * @return \Magento\Framework\Api\Search\SearchResultInterface
     */
    public function execute(\DreamVendor\DreamModule\Api\Data\SearchRequestInterface $searchRequest): SearchResultInterface;
}
```
2. Create SearchRequestInterface. Make it extensible with extension attributes.
```
namespace DreamVendor\DreamModule\Api\Data;

use Magento\Framework\Api\ExtensibleDataInterface;

/**
 * Search Request Data Object.
 */
interface SearchRequestInterface extends ExtensibleDataInterface
{
    /**
     * Get Extension Attributes.
     *
     * @return \DreamVendor\DreamModule\Api\Data\SearchRequestExtensionInterface|null
     */
    public function getExtensionAttributes(): ?\DreamVendor\DreamModule\Api\Data\SearchRequestExtensionInterface;

    /**
     * Set Extension Attributes.
     *
     * @param \DreamVendor\DreamModule\Api\Data\SearchRequestExtensionInterface|null $extension
     */
    public function setExtensionAttributes(?\DreamVendor\DreamModule\Api\Data\SearchRequestExtensionInterface $extension): void;

```
3. Declare your endpoint via `webapi.xml` in `etc` folder of your module.
```
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Webapi:etc/webapi.xsd">
    <route url="/V1/my-custom-endpoint" method="GET">
        <service class="DreamVendor\DreamModule\Api\MyCustomEndpointInterface" method="execute"/>
        <resources>
            <resource ref="anonymous" />
        </resources>
    </route>
</routes>

```
4. Flush caches.
5. Try to generate schema. Go to `your.website.com/swagger/`.

### Expected result (*)
1. The page has been opened.
2. You can see your new endpoint.

### Actual result (*)
1. You can see message like `Failed to load API definition. Internal Server Error http://magento2.local/rest/all/schema?services=all`
2. Error message `Warning: array_merge() expects at least 1 parameter, 0 given in \/var\/www\/html\/app\/code\/Magento\/Webapi\/Model\/Rest\/Swagger\/Generator.php:762`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20198` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your report. 
The issue has been fixed in magento/magento2#24627 by @swnsma in 2.3-develop branch
Related commit(s):
 - [a7e043ca92266ae6c81ebbf655a57506159f1bb5](https://github.com/magento/magento2/commit/a7e043ca92266ae6c81ebbf655a57506159f1bb5)
 - [7e30a189028ecd77872989df5648ba033a55dd5f](https://github.com/magento/magento2/commit/7e30a189028ecd77872989df5648ba033a55dd5f)
 - [9bbbf045dc2931a55952f3b9b356b1a2a72ef341](https://github.com/magento/magento2/commit/9bbbf045dc2931a55952f3b9b356b1a2a72ef341)
 - [8dd87681d490a5958d1ea1435df9d6a2adc98ce6](https://github.com/magento/magento2/commit/8dd87681d490a5958d1ea1435df9d6a2adc98ce6)
 - [f1eb7a33bb28ff046c0ae3422084376331cb22d0](https://github.com/magento/magento2/commit/f1eb7a33bb28ff046c0ae3422084376331cb22d0)

The fix will be available with the upcoming 2.3.4 release.

**Comment by Sanjay-cod34082** [comment]
the worst thing about the Magento community is  - if anyone visited for any issue - then how he or she can know which solution  is correct and which need to use (only marketing and a big team will not help to grow your tools)

**Comment by swnsma** [comment]
Hi @Sanjay-cod34082,
You can find solution for described here issue in Pull Request: https://github.com/magento/magento2/pull/24627

I guess it should be already available in the code of all Magento versions above 2.3.4.
