### ISSUE TITLE
Getting error in console while selecting all downloadable links 

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24633]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.19

### Steps to reproduce (*)

1. Create a downloadable product with more than one downloadable links 
2. Open that product at frontend
3. click on select all link 
4. open developer tool and check console

### Expected result (*)

1. should not show any error in console

### Actual result (*)

1. 
![downloadable-issue](https://user-images.githubusercontent.com/44425160/65111336-3d4c3780-d9f9-11e9-9731-2d3cfcb1cee8.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24633-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24633-2-3-develop.instances.magento-community.engineering/admin](https://i-24633-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20219` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24634 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [66b7785aebd4e4570d789a308f6d40387cc56053](https://github.com/magento/magento2/commit/66b7785aebd4e4570d789a308f6d40387cc56053)

The fix will be available with the upcoming 2.3.4 release.
