### ISSUE TITLE
PUT /V1/products/:sku/media/:entryId is not idempotent

### ISSUE THREAD

**Issue by philippsander** [magento/magento2#24639]
### Preconditions (*)

1. Magento 2.3.x CE & EE 
2. Have a Product with an image uploaded (Luma sample data provides this)

### Steps to reproduce (*)

1. Send the following PUT request to "/rest/V1/products/24-MB01/media/60"
base64_encoded_data is empty as this would bloat the issue-text

`{"entry":{"media_type":"image","label":"Label for my Image","disabled":false,"types":["image","small_image","thumbnail"],"content":{"base64_encoded_data":"<base64 encoded img","type":"image/jpeg","name":"test"},"id":60}
}`

### Expected result (*)

1. Everything provided by the request is updated for the media entity
2. The actual file-content is replaced with what is provided in the base64_encoded_data
3. The endpoint returns true
4. Send them same request again
5. The endpoint returns true

### Actual result (*)

1. Everything provided by the request is updated for the media entity
2. The endpoint returns true
![image](https://user-images.githubusercontent.com/51680850/65219592-8cf63600-dac1-11e9-9d69-a3543605a210.png)

3. Send them same request again
4. Response contains:
 "message": "No image with the provided ID was found. Verify the ID and try again."
![image](https://user-images.githubusercontent.com/51680850/65219686-ba42e400-dac1-11e9-8dad-0321d780334c.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20259` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Could be the same or related
https://github.com/magento/magento2/issues/24037

**Comment by sdzhepa** [comment]
Hello @philippsander and @shikhamis11 

The fix for this issue is in progress by the internal Magento team.
It will be delivered in the scope of `MC-20259`.
At this moment development is done and `MC-20259` in code-review stage

**Comment by magento-engcom-team** [comment]
Hi @philippsander, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [b11f053bc29564ef13fb071161b52276a5701ed0](https://github.com/magento/magento2/commit/b11f053bc29564ef13fb071161b52276a5701ed0)

The fix will be available with the upcoming `2.3.5` release.
