### ISSUE TITLE
Create category returns : The "string" value's type is invalid. The "string[]" type was expected

### ISSUE THREAD

**Issue by LotsofPixels** [magento/magento2#24658]
### Preconditions (*)
1. Magento 2.3.2
2. <soap:Envelope xmlns:def="https://www.domaine.tld/soap/all?services=catalogCategoryRepositoryV1" xmlns:soap="http://www.w3.org/2003/05/soap-envelope">

### Steps to reproduce (*)

1. Message is an update, because category is already existing.
2.-<item>
<attributeCode>default_sort_by</attributeCode>
<value>position</value>

</item>

### Expected result (*)
A creation or update of the category

### Actual result (*)
<?xml version="1.0" encoding="UTF-8"?>
-<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
-<env:Body>
-<env:Fault>
-<env:Code>
<env:Value>env:Sender</env:Value>
</env:Code>
-<env:Reason>
<env:Text xml:lang="nl">Error occurred during "customAttributes" processing. Attribute "default_sort_by" has invalid value. The "string" value's type is invalid. The "string[]" type was expected. Verify and try again.</env:Text>
</env:Reason>
</env:Fault>
</env:Body>
</env:Envelope>

**Comment by kanthy-magento** [comment]
@magento give me 2.3.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3.2-develop instance for you

**Comment by magento-engcom-team** [comment]
@itsPranith Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21950` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
