### ISSUE TITLE
Welcome message lost when persistence enabled

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#24653]
# Preconditions (*)

1. Magento 2.3.2
2. Cart persistence enabled

### Steps to reproduce (*)

Note: These replicate steps may seem like steps an average user would never carry out. The issue we're having is the welcome message is lost when customers return to the site a few days later. These replication steps attempt to replicate the "waiting a few days".
1. Enable Cart Persistence in Magento Admin
2. Create a customer account and login
3. Add something to basket
4. Clear all cookies except for persistent_shopping_cart
5. Empty browser local storage
6. Refresh the page

### Expected result (*)

1. Welcome message appears (with "not you?" sign-out link) and cart information is maintained:
![image](https://user-images.githubusercontent.com/49071342/65231160-09d7de80-dac7-11e9-804e-f77df7cc46c8.png)

### Actual result (*)

1. No Welcome message, but "not you?" link appears and cart is remembered:
![image](https://user-images.githubusercontent.com/49071342/65231303-4a375c80-dac7-11e9-9656-f2284ce9232c.png)

**Comment by itmsenior** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-24653-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24653-2-3-develop.instances.magento-community.engineering/admin](https://i-24653-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
Unable to reproduce with development instance:
![image](https://user-images.githubusercontent.com/49071342/65231982-4fe17200-dac8-11e9-928d-df2191f7c6e5.png)

**Comment by itmsenior** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-24653-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24653-2-3-2.instances.magento-community.engineering/admin](https://i-24653-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
Reproduced on 2.3.2: 
![image](https://user-images.githubusercontent.com/49071342/65232895-dba7ce00-dac9-11e9-9b2e-c0ab92ce0aa1.png)

Could anyone confirm what the expected behavior should be with the above replication steps? I was under the impression I should have 
1. Welcome, Customer Name
2. Not you link (clear cookie)
3. Cart contents remembered.
Or should I be classed as logged out (i.e. completely a guest with nothing remembered?)

**Comment by engcom-Bravo** [comment]
Hello @itwebdev2. Thanks for applying. To achieve the behavior You expect would You please try to set Clear Persistence on Sign Out to "No" (if not already set):
![persist](https://user-images.githubusercontent.com/51680745/65325218-ef7d2e00-dbb6-11e9-8a96-d5b9f851ad09.png)

**Comment by itwebdev2** [comment]
Hi @engcom-Bravo.
Thank you, in the development instance this configuration works as expected.
In 2.3.2 regardless of the "Clear persistence on Sign Out" configuration, the exception still occurs when pressing the "Not You?" link. Do you know which PR was involved in fixing this issue?

**Comment by itmsenior** [comment]
Hi @engcom-Bravo.
In the development instance this configuration works as expected.
However, in 2.3.2, regardless of that configuration, if you follow my replicate steps the welcome message does not appear.
Do you know which PR fixed this in the development instance? Any ideas if it's scheduled for release line 2.3.3?

**Comment by engcom-Bravo** [comment]
Hello again @itwebdev2. Sorry for delay. I haven't  found the fixing PR. It could be the issue was fixed based on some Magento's internal ticket(s) I have no access to or it was fixed automatically while fixing some other issue(s). With that I'm closing this issue as I'm supposed to due to the issue is no more reproducible on the latest develop version. But please feel free to reopen it any time if deem necessary. Thank You for applying.
