### ISSUE TITLE
Magento Checkout UI Component SortOrder

### ISSUE THREAD

**Issue by Emanuel-23** [magento/magento2#24652]
I really hope i have understood the fundamental technique behind the knockout ui components in combination with xml. The following does not make much sense to me...

### Preconditions (*)
1. Magento CE 2.3.2
2. see hardcoded sortOrder in line `90` in `web/vendor/magento/module-checkout/view/frontend/web/js/view/shipping.js`
2. see hardcoded sortOrder in line `57` in `web/vendor/magento/module-checkout/view/frontend/web/js/view/payment.js`

### Steps to reproduce (*)
Install Magento2 and override `checkout_index_index.xml`: change or add sortorder to the already existing steps by adding
`<item name="sortOrder" xsi:type="string">CUSTOMORDERNUMBER</item>`
 
Or Even better, create a custom module and follow the steps from the official devdocs, in order to add a new checkout step:
https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_new_step.html

then try changing the order of the step components only by using the `<item name="sortOrder" xsi:type="string">CUSTOMORDERNUMBER</item>` in xml (your `checkout_index_index.xml` extension in your custom module).

### Expected result (*)
1. After changing the uiComponents SortOrder of the steps, they should display in a custom order 

### Actual result (*)
1. The custom order that has been set in xml is getting applied, but the js does not use it. Instead it uses the values that have been provided in the js.
(In the Browser inspector you can see that the sortOrder value from the xml is set as a components property)
2. The uicomponent (the step/custom step) on the other hand uses still the `hard coded` sortOrder value

So in order to change the sortOrder you have to change or override the registerStep part and provide hardcoded values. 

In the documentation tutorialis there is described:
1. On the one hand we should provide sortOrder between 0 and 3+ within xml see lines 14,15,16 in https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_new_step.html#checkout
2. On the other hand we should provide sortOrder between 0 and 30 + in js see lines 48-53 in https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_new_step.html#component

We could easily change this by not using hard coded values in he registerStep part of the checkout step (within initialize), but use `this.sortOrder` instead (of course add a default porperty value before). So the `registerStep` will use the components property, which is initialized in the js, but can be overridden using xml.

**Comment by anujwebkul** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul, here is your [Magento instance](https://i-24652-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24652-2-3-develop.instances.magento-community.engineering/admin](https://i-24652-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21766` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Emanuel-23. Thank you for your report. 
The issue has been fixed in magento/magento2#25015 by @anujwebkul in 2.3-develop branch
Related commit(s):
 - [36712c1e7167427acece84ed318d5609d28c5222](https://github.com/magento/magento2/commit/36712c1e7167427acece84ed318d5609d28c5222)

The fix will be available with the upcoming 2.3.4 release.
