### ISSUE TITLE
Logged out automatically after flush JS/CSS,Static files cache 

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#24651]
### Preconditions (*)

1. Magento 2.3.X , Apache2 ,MySQl

### Steps to reproduce (*)

1. Login to admin
2. Navigate to Cache management
3. Flush static files then JS/CSS cache

### Expected result (*)

1. Has to be logged in

### Actual result (*)

1. Got logged out automatically when flushed JS/CSS cache after static files cache

**Comment by VZeroCool** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-24651-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24651-2-3-develop.instances.magento-community.engineering/admin](https://i-24651-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VZeroCool** [comment]
@magento give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by engcom-Bravo** [comment]
Hello @VZeroCool, Thanks for applying. We are not able to reproduce Your issue on a vanilla instance of the latest develop version:
![cache](https://user-images.githubusercontent.com/51680745/65219247-deea8c00-dac0-11e9-8d0e-2316e1de1abb.gif)
Are we doing something wrong here?
