### ISSUE TITLE
Catalog > Product > Add Product > Set Product as New From > Calendar icons are off

### ISSUE THREAD

**Issue by jc9080** [magento/magento2#24662]
### Preconditions (*)

1. Megento ver.2.3.0
2.

### Steps to reproduce (*)

1. Go to Catalog/Product/Add Product/Set Product as New From
2.

### Expected result (*)

1. Calendar icons should be outside date fields
2.

### Actual result (*)

1. Calendar icons are off and located inside the fields
2. 
![magento_report_calendar_icon](https://user-images.githubusercontent.com/45600832/65255996-d39d5d80-dacc-11e9-87de-7eee5f0b3fbe.PNG)

**Comment by engcom-Bravo** [comment]
Hello @jc9080. Thanks for applying. Here is what we've got in the latest develop version:
![inside](https://user-images.githubusercontent.com/51680745/65256660-9060e000-db08-11e9-9b9f-c73cbce96f4e.png)
Could You please confirm You would face the same issue on a vanilla i.e. fresh, free of any customization and third party extensions instance of Magento. Thank You.

**Comment by hostep** [comment]
This was fixed in Magento 2.3.1 by https://github.com/magento/magento2/pull/18627 I believe.

**Comment by ajijshekh123** [comment]
This issue is fixed in Magento 2.3 Instance.  See the Issue Id: #18627
