### ISSUE TITLE
Magento 2 quickoder multiple sku issue

### ISSUE THREAD

**Issue by quocthai795vn** [magento/magento2#24669]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Enter Multiple SKUs -> Example 24-WB03, 24-WB04, the first time is correct but when we continue Enter skus 24-WB03, 24-WB04 again, it does not update qty to 2.

### Expected result (*)

1. [Screenshots, logs or description]
2.It should update Qty

**Comment by ajijshekh123** [comment]
Hi @quocthai795vn 
Please add this issue in below Magento Issue format. 
See the link: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24669-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24669-2-3-develop.instances.magento-community.engineering/admin](https://i-24669-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@quocthai795vn - I have followed the below scenario and verify the issue. It is working fine in Magento 2.3 Instance.
**Steps:**
1. Add 2 different simple product using  Example 24-WB03, 24-WB04 SKU.
2. On Front end Search the product using the same SKU 24-WB03, 24-WB04.
3. Add the Product Same product 2 times and Review the Shopping cart page.

Actual result: Product Qty is updated.

@quocthai795vn - Please add your Steps to be reproduced, Screenshot, Actual result and Expected result.

Thanks.

**Comment by quocthai795vn** [comment]
Hi @ajijshekh123 

+ Step 1: Access URL ....../quickorder
 => This is the image: [https://prnt.sc/p9039n](url)
+ Step 2: Enter 24-WB03, 24-WB04 SKU in: *Enter Multiple SKUs* and click Add to list, Even though the SKUs does exist, the system reported an error
[https://prnt.sc/p90493](url)
+ Step 3: Continue Enter 24-WB03, 24-WB04 SKU in: *Enter Multiple SKUs* and click Add to list, The system just have updated for SKU first and auto add blank field

Thanks,

**Comment by ajijshekh123** [comment]
Hi @quocthai795vn,

I can't see the below image URL. It is displaying 'No results matched your search.' error.
Please send the proper screenshot.

Thanks.

**Comment by ajijshekh123** [comment]
@quocthai795vn - Now I have close this issue, Please add proper details, steps, actual and expected result as per the Magento policy.
See the link: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

Thanks.
