### ISSUE TITLE
Unexpected localized exceptions when thrown via WebAPI

### ISSUE THREAD

**Issue by ValeSauer** [magento/magento2#24660]
### Preconditions (*)
1. Magento 2.3.2 & 2.3-develop
2. Change locale of main store to german
3. Create an integration

### Steps to reproduce (*)
Unfortunately I have no idea how to trigger a 500 error via REST API. It usually happens by chance when there are database issues or something similar. However, the following steps could help to reproduce it.

1. Enforce an exception by calling the REST API, for example too many concurrent product updates will cause a "Database deadlock found when trying to get lock" exception
2. Until 2.3.1 exception thrown by the REST API were always in english, irrespective of the actual store language. This made it easy to catch errors and for example retry on deadlocks. Since 2.3.2 exceptions are localized even via REST API. 

### Expected result (*)
1. "Database deadlock found when trying to get lock" exception message in english

### Actual result (*)
1. "Database deadlock gedetecteerd tijdens het verkrijgen van een lock" for a dutch store or any other language for a store in this language

**Comment by ValeSauer** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ValeSauer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ValeSauer, here is your [Magento instance](https://i-24660-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24660-2-3-develop.instances.magento-community.engineering/admin](https://i-24660-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20289` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zhartaunik** [comment]
The described issue contradicts this one: https://github.com/magento/magento2/issues/19908
Should we really leave WebAPI exceptions in English? And why English? They may be used for showing on the frontend. And I think this is not a good behavior.

**Comment by ValeSauer** [comment]
Software usually provides machine readable error codes in addition to human readable error descriptions to avoid this issue.
The Web-API is definitely not only intended to be used by frontend applications, but also by backend integrations such as syncs, imports, exports, so it should consider the requirements of a machine. Even a frontend application might be able to interprete error codes, e.g. to implement a retry-mechanism for deadlocks to improve usability. 

A frontend application that requires localized error messages must still contain localizations. So it could also handle the localization of error messages.

I think this code, which is necessary to react on error massages, says it all:
```javascript
   var apiCall = async function (request_data, retry = 0) {
        try {
            var result = await performApiCall(request_data, retry)
            return result
        } catch (e) {
            if (e && typeof (e) == 'string' && (
                e.indexOf("URL key for specified store already exists.") >= 0 || 
                e.indexOf("URL klíč ve zvoleném obchodě již existuje.") >= 0 || 
                e.indexOf("La clé d’URL pour la boutique existe déjà.") >= 0 || 
                e.indexOf("URL-Schlüssel für angegebenen Store ist bereits vorhanden") >= 0 || 
                e.indexOf("Esiste già una URL key per il negozio specificato.") >= 0 || 
                e.indexOf("URL sleutel voor opgegeven winkel bestaat al.") >= 0 || 
                e.indexOf("Klucz URL dla wybranego sklepu już istnieje.") >= 0 || 
                e.indexOf("Belirtilen mağaza için URL anahtarı zaten var.") >= 0 ||
                e.indexOf("La clave de URL para la tienda especificada ya existe.") >= 0
            ) && retry <= MAXURLRETRIES) {
```

Therefore I suggest the following approach:
1. Perfect solution: Additionally to the currently localized, human readable error messages, provide unique machine readable error codes for every error message.
2. If this is not possible, either switch back to english or make the language of the error messages configurable via backend.

**Comment by magento-engcom-team** [comment]
Hi @ValeSauer. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24222` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by isxam** [comment]
@magento give me 2.4.3 instance

**Comment by bfontaine** [comment]
This is still an issue and it’s very annoying because you can’t reliably identify errors in a generic way because the exact wording depends on the locale.
