### ISSUE TITLE
Issue on accessing admin after fresh 2.0.0 stable successful installation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2466]
Class Magento\User\Model\Resource\User does not exist

PHP Version 5.6.8
System Windows NT AMIT-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
Apache Version Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8
Mysql mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $

**Comment by dmitrii-fediuk** [comment]
All "Resource" was renamed to "ResourceModel" on 2015-10-07: https://mage2.pro/t/topic/130
You definitely use some old code.

**Comment by ghost** [comment]
I just downloaded yesterday from:
https://www.magentocommerce.com/download

Same issue in both Full Release with and without Sample Data.

**Comment by dmitrii-fediuk** [comment]
Publish the stack trace.
