### ISSUE TITLE
Adding variation from another configurable product to cart if variation belongs to same super attribute is possible

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2#24676]
### Preconditions (*)
1. Magento 2.3 from the latest `magento/graphql-ce/2.3-develop`

### Steps to reproduce (*)
1. Create 2 Configurable products SKU's: [sku-c1, sku-c2]
2. Add 1 super attribute option, etc. Color - Red 
![image](https://user-images.githubusercontent.com/20116393/65142241-f5d6a300-da1a-11e9-9672-299e42f34de3.png)
3. Create 1 variation with attribute Color -Red for each product SKU's:[sku-c1-Red, sku-c2-Red]
![image](https://user-images.githubusercontent.com/20116393/65142680-eefc6000-da1b-11e9-810e-4bc5737ebb69.png)
Don't forget fill out quantity and add all products to the category.

The result should look like: 
![image](https://user-images.githubusercontent.com/20116393/65142982-8feb1b00-da1c-11e9-9ba7-02612799ed80.png)

4. Create empty cart
5. Run mutation with the wrong parent SKU.
```
mutation {
  addConfigurableProductsToCart(
    input:{
      cart_id:"NEW_CART_ID"
      cart_items:{
        parent_sku: "sku-c1"
        data:{
          sku:"sku-c2-Red"
          quantity:1
        }
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
        }
        ... on ConfigurableCartItem {
          configurable_options {
            id
            option_label
            value_id
            value_label
          }
        }
      }
    }
  }
}
```

### Expected result (*)
1. Error is thrown.

### Actual result (*)
1. `sku-c1-Red` being added to cart.
![image](https://user-images.githubusercontent.com/20116393/65143341-61217480-da1d-11e9-855d-818cae115223.png)

I'm not sure whether it is bug or feature. Magento automatically selects the correct child product according to the super attribute. Consider this and unmark/fix the folowing test `\Magento\GraphQl\ConfigurableProduct\AddConfigurableProductToCartTest::testAddVariationFromAnotherConfigurableProductWithTheSameSuperAttributeToCart` added in PR magento/graphql-ce#866.

**Comment by lenaorobei** [comment]
There is no check in GraphQL that  `data/sku`(child)  belongs to `parent_sku`. See `\Magento\ConfigurableProductGraphQl\Model\Cart\BuyRequest\SuperAttributeDataProvider::execute`.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20530` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lenaorobei** [comment]
Fixed in https://github.com/magento/graphql-ce/pull/968
