### ISSUE TITLE
Magento 2 loses the problem Less file name in a «Compilation from source / Cannot read contents from file» error report (and my fix)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2467]
https://mage2.pro/t/233

**Comment by dmitrii-fediuk** [comment]
The same problem: http://magento.stackexchange.com/questions/92287

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
