### ISSUE TITLE
«Each getter must have description with @return annotation. See Magento\Tax\Api\Data\TaxDetailsInterface::getSubtotal()»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2468]
Is it a bug?
http://magento.stackexchange.com/questions/90647
https://mage2.pro/t/topic/240/3

**Comment by davidalger** [comment]
Closing as duplicate of #2555 since that one contains complete stack-trace information on issue.

**Comment by shwetabha** [comment]
In magento2, Take care of commenting in interface page. If you just add function without comment param type. It will return error. Example - interface AuthInterface {
/**
* Test function
*
* @api
* @param $param string
* @return string
*/
public function test(); } You have to add the return type in comment section
