### ISSUE TITLE
A

### ISSUE THREAD

**Issue by RomanKrut** [magento/magento2#24689]

**Comment by engcom-Bravo** [comment]
Hello @krutkoroma79911. Thanks for applying. You see, factory classes are not the ones that exist at the very beginning. They are not created by the developers and are not supposed to be created by the developers. Factory classes are generated by Magento itself and are put into the appropriate folder by the path starting with generated/code/... (in early versions generation/...) I hope this [article](https://alanstorm.com/magento_2_crud_models_for_database_access/) will make it clear. So I'm going to close the issue. But please feel free to reopen it if deem necessary.
