### ISSUE TITLE
Contact us: Form doesn't render the cms page

### ISSUE THREAD

**Issue by GDauer** [magento/magento2#24687]
### Summary
I'm working on the issue **Captcha not shown on contact form #24564** when found this bug. Would like to fix this one first before keeping my work on the captcha stuff. I think they are related somehow, however would like to keep things separated.

### Preconditions (*)

1. Magento version: 2.3
2. PHP version: 7.2.22
3. MySQL version: 5.7.27

### Steps to reproduce (*)

1. Install Magento 2.3
2. Install Sample Data
3. Follow this tutorial from oficial documentation (Method 2):
https://docs.magento.com/m2/ce/user_guide/stores/contact-us.html
4. (Optional) Enable Captcha for Contact Us Form
5. Fill the form
6. He will throw a _Exception_ with **Unable to send mail: Unknown error** OR **Invalid Captcha** OR **Thanks for contacting us with your comments and questions. We'll respond to you very soon.**
7. Magento will redirect you to **magento/contact/index** OR **magento/contact/index/index**
8. Magento will render the **Magento_Contact::form.phtml**

### Expected result (*)

1. Should render the custom CMS page

### Actual result (*)

1. Magento is rendering **Magento_Contact::form.phtml** not the CMS page

**Comment by GDauer** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GDauer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GDauer, here is your [Magento instance](https://i-24687-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24687-2-3-develop.instances.magento-community.engineering/admin](https://i-24687-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@GDauer Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20369` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
