### ISSUE TITLE
Punched Order Issuse

### ISSUE THREAD

**Issue by TNWINTERNATIONAL** [magento/magento2#24699]
Even though the Payment is confirmed in the Payment Gateway Portal we are still getting the orders marked as "Order Punched". same problem is explained to my gateway portal still no solution has been found,
![Screenshot (17)](https://user-images.githubusercontent.com/55585251/65428063-4beb8200-de31-11e9-826f-0a3dc2eedd09.png)
![Screenshot (18)](https://user-images.githubusercontent.com/55585251/65428064-4beb8200-de31-11e9-9968-ad075729246e.png)
![Screenshot (20)](https://user-images.githubusercontent.com/55585251/65428065-4c841880-de31-11e9-9045-7cf9a660da68.png)
![Screenshot (21)](https://user-images.githubusercontent.com/55585251/65428067-4c841880-de31-11e9-8066-85787fc169a5.png)
![Screenshot (22)](https://user-images.githubusercontent.com/55585251/65428069-4c841880-de31-11e9-94ef-ada0d26ea9dc.png)
![Screenshot (23)](https://user-images.githubusercontent.com/55585251/65428070-4d1caf00-de31-11e9-87cd-c883be08f6cb.png)
![Screenshot (24)](https://user-images.githubusercontent.com/55585251/65428071-4d1caf00-de31-11e9-8ad0-add2118f9a4e.png)
![Screenshot (25)](https://user-images.githubusercontent.com/55585251/65428072-4d1caf00-de31-11e9-84ad-ea960bd7ddc7.png)
![Screenshot (26)](https://user-images.githubusercontent.com/55585251/65428073-4db54580-de31-11e9-91c1-925d7ccc17b4.png)
![Screenshot (27)](https://user-images.githubusercontent.com/55585251/65428074-4db54580-de31-11e9-81e5-0579d4807d7a.png)
![Screenshot (28)](https://user-images.githubusercontent.com/55585251/65428075-4db54580-de31-11e9-8eb6-620b9cd9012e.png)
![Screenshot (29)](https://user-images.githubusercontent.com/55585251/65428077-4e4ddc00-de31-11e9-8532-62edb543897d.png)

The condition is not for all orders but specifically for some orders. Kindly check  and clarify.

**Comment by Lavazandra** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Lavazandra. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Lavazandra, here is your [Magento instance](https://i-24699-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24699-2-3-develop.instances.magento-community.engineering/admin](https://i-24699-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hello @TNWINTERNATIONAL 
Please follow issue [reporting guideline](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report your issue . Also please mention required steps to reproduce  the issue.
