### ISSUE TITLE
Errors after installation

### ISSUE THREAD

**Issue by emanueledibella** [magento/magento2#24702]
Hi,

I've installed Bicomart theme some day ago on my Magento 2.3.2, but when I activated the theme, It deleted my menu and my footer that I had imported by Magento 1.9.3. So I tried to create a new menu thanks to theme's option, but when I try to save the menu, it doesn't save: in fact I click on save button, but it doesn't do anything.

I hope you can help me,

**Comment by engcom-Charlie** [comment]
Hello @mrwebdesign 
The Bicomart theme is not supported on Magento 2.3.2 .
![image](https://user-images.githubusercontent.com/51680850/65499203-edbcae80-dec5-11e9-90b6-77df695565c8.png)
You can read it in [ this page](https://themeforest.net/item/bicomart-powerful-magento-2-theme-for-marketplace/22610207).
So i close this issue.
Thanks for your report!
