### ISSUE TITLE
Saving CMS Page Title from REST web API makes content empty

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#24704]
I am not sure if this is a bug or feature. I am trying to update the CMS Page title from POSTMAN. It updates title but also makes content and other fields empty.

### Preconditions (*)

1. At least 1 CMS page
2. Web API auth key

### Steps to reproduce (*)

1. Go to the [postman](https://www.getpostman.com/) and use this URL and body content with PUT method
URL: `http://www.example.com/rest/all/V1/cmsPage/ID` (replace ID with your id (integer)
Body: 
```
{"page":
	{
		"title": "My Title"
	}
}
```

### Expected result (*)

1. Update TITLE and keep all other fields same/unchanged
2. OR only update the field provided.

### Actual result (*)

1. Updates title and makes all other fields (not provided in the body) null.

**How do I update title only or content only? I want to update one field only (title at this stage).**

**Comment by adarshkhatri** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri, here is your [Magento instance](https://i-24704-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24704-2-3-develop.instances.magento-community.engineering/admin](https://i-24704-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20371` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jigneshkhunt** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jigneshkhunt. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jigneshkhunt, here is your [Magento instance](https://i-24704-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24704-2-3-develop.instances.magento-community.engineering/admin](https://i-24704-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lfolco** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lfolco. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lfolco, here is your [Magento instance](https://i-24704-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24704-2-3-develop.instances.magento-community.engineering/admin](https://i-24704-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lfolco** [comment]
I'm wondering if this is by design; some entities allow a patch-style update (products) while others do a replace-style update (customers and, apparently, CMS pages). Not sure if making such a change is in the scope of this ticket? Would love some clarification on this.

**Comment by manishmittalm** [comment]
Hello @magento
Please provide me 2.3 develop.

**Comment by manishmittalm** [comment]
@magento 

This issue still in open status so should need to fix or not?

**Comment by lfolco** [comment]
@manishmittalm I am trying to get clarification on whether this is by design or not.

**Comment by shikhamis11** [comment]
I am working on this issue at #MM20IN

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your report. 
The issue has been fixed in magento/magento2#27237 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [f91aff175c6a3e4701e69601a68d3333da702e0e](https://github.com/magento/magento2/commit/f91aff175c6a3e4701e69601a68d3333da702e0e)
 - [e74825a2e2e26e5a60a9152b2f3b58921fd660e4](https://github.com/magento/magento2/commit/e74825a2e2e26e5a60a9152b2f3b58921fd660e4)

The fix will be available with the upcoming 2.4.0 release.
