### ISSUE TITLE
While Enabling the Disabled Products from Product Grid (Catalog -> Products) "cataloginventory_stock_cl" table does not get the entries

### ISSUE THREAD

**Issue by nileshpgosai** [magento/magento2#24706]
### Preconditions (*)
1. Ensure that all magento indexers are set to "update on schedule"

### Steps to reproduce (*)
1. Go to Admin->Catalog->Products
2. Filter for disabled products
3. Select one or more disabled products using the checkbox on the right and Note the entity IDs of the selected products.
4. From the actions dropdown on top, select "change status"->Enable
5. Inspect contents of **cataloginventory_stock_cl** table

### Expected result (*)
1. **cataloginventory_stock_cl** table should contain entries with entity_id matching the updated products

### Actual result (*)
1. **cataloginventory_stock_cl** table contains no entries for updated products.

**Comment by nileshpgosai** [comment]
This issue is reproducible in 2.3.0,2.3.1 and 2.3.2

**Comment by engcom-Bravo** [comment]
Hello @nileshpgosai. Thanks for applying. The table You are talking about concerns stock status (In Stock or Out of Stock). It doesn't concern Product status in terms of Enabled - Disabled. You may check it Yourself. For that just change Stock Status of some product and Your table will get a new entry.

**Comment by nileshpgosai** [comment]
I agreed but when  we have indexers set update on schedule and it will not create entry here and those products are not re-index.

**Comment by engcom-Bravo** [comment]
@nialltiernan, I think it creates entry(is) in some other so to say cron table(s) ending in _cl. And as far as I checked after cron has run statuses are updated. Could You please check it too. Thank You.

**Comment by nileshpgosai** [comment]
I got the solution from magento support team.
[MDVA-20950_EE_2.3.2_COMPOSER_v1.zip](https://github.com/magento/magento2/files/3652534/MDVA-20950_EE_2.3.2_COMPOSER_v1.zip)
