### ISSUE TITLE
Magento 2 Payment Failed Email Not Working

### ISSUE THREAD

**Issue by grosoasap** [magento/magento2#24707]
### Preconditions (*)

1. Magento CE 2.3.1
2. PHP 7.1.3

### Steps to reproduce (*)

1.Enable Paycorp Credit Card Payment Method (or any other that require configuration) without configuring it
2.Add a product to cart and proceed to checkout
3.select Paycorp and input fake credit card information
get return to shopping cart with error " Transaction Failed with transaction id. No Email is send to merchant about transaction failed

### Expected result (*)

1. Automated mail to recipient with information regarding transaction failed
2.![error_failed_email](https://user-images.githubusercontent.com/54885657/65506975-751c1900-deea-11e9-9324-02c8e3cb411b.PNG)

### Actual result (*)

1.no emails are sent

**Comment by grosoasap** [comment]
yes

**Comment by engcom-Delta** [comment]
Hi @grosoasap thank you for your report. I am not able to reproduce issue by steps you described on clean 2.3-develop, seems like this related to your custom modules.
I used Braintree and get email after transaction was interrupted.
![#24707issue](https://user-images.githubusercontent.com/51681379/67575159-9ddf3a80-f744-11e9-85d3-e1ad0895da57.png)

If you'd like to update the issue, please reopen it.
