### ISSUE TITLE
Update countries list / CLDR to version 36

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#24710]
### Preconditions (*)
1. Magento 2.3.2 & 2.3-develop

### Steps to reproduce (*)
1. Go to stores -> configuration -> General -> General -> Countries list.

### Expected result (*)
1. All existing countries available.

### Actual result (*)
1. Missing countries. For example Curacao, Sint Maarten are missing and there are also 3 Municipalities (Bonaire, Sint Eustasius and Saba) which form the Caribbean Netherlands which is also missing. I have read that Kosovo and Canary Islands are also missing.
2. I looked into Magento's ZendFramework1 library that is currently using version 24 of the (Common Locale Data Repository) which is currently already at version 36.

We need to update the Locale data and fix the entries in the directory_country* tables.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20433` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by PascalBrouwers** [comment]
CLDR is at version 25 in Magento 2. The PR in this issue only updated the language list for BQ, CW, SX, XK.
