### ISSUE TITLE
Bad price

### ISSUE THREAD

**Issue by qmarlats** [magento/magento2#2471]
In my products I have a strange price that appear:
![capture](https://cloud.githubusercontent.com/assets/3251811/11324314/5a1922c8-912e-11e5-95b2-ed8c95060289.PNG)
I never entered 12.46€ so I suppose it's the price minus the VAT, but in Magento settings I've configured taxes to show all prices with VAT. This appear in configurable product, so configurable product don't have price, but simple products have price (14.95€).

**Comment by Davelaar** [comment]
Same issue here, only on configurable products

**Comment by tang-yu** [comment]
We opened internal ticket MAGETWO-47440 to track this issue. Thanks.

**Comment by tang-yu** [comment]
The issues has been fixed and merged into mainline. Thanks again for raising the issue.
