### ISSUE TITLE
Unable to set native session handler that is different from the one define in php.ini after update to Magento 2.3

### ISSUE THREAD

**Issue by mlindholm** [magento/magento2#24717]
### Preconditions (*)

2.4-develop

### Steps to reproduce (*)

1. Configure env.php to use memcached as save_handler as[ instructed in the documentation](https://devdocs.magento.com/guides/v2.3/config-guide/memcache/memcache_magento.html). 

### Expected result (*)

1. SessionManager should be setting memcached as used save handler in initOptions function. 

### Actual result (*)

1. SessionManager is not setting the memcached as save_handler, but is instead using the files session_handler. The save_path is set though, which result error message below:
> main.CRITICAL: Warning: SessionHandler::read(): open(127.0.0.1:11211/sess_0imeeaqmnvemdg4e3h57tat0ik, O_RDWR) failed: No such file or directory (2) in../vendor/magento/framework/Session/SaveHandler/Native.php on line 22 {"exception":"[object] (Exception(code: 0): Warning: SessionHandler::read(): open(127.0.0.1:11211/sess_0imeeaqmnvemdg4e3h57tat0ik, O_RDWR) failed: No such file or directory (2) in ../vendor/magento/framework/Session/SaveHandler/Native.php on line 22 at ../vendor/magento/framework/App/ErrorHandler.php:61)"} []

### Own foundings
New changes made in 2.3 for [SessionManager](https://github.com/magento/magento2/blob/2.3.0/lib/internal/Magento/Framework/Session/SessionManager.php#L605) are preventing the save_handler to be set as anything else than the one configured to php.ini for Native session handler.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20484` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by steverobbins** [comment]
A work around for the time being, find your `php.ini` file and set `session.save_handler = memcached`

```
File: /etc/php/7.2/fpm/php.ini
...
[Session]
; Handler used to store/retrieve data.
; http://php.net/session.save-handler
session.save_handler = memcached

; Argument passed to save_handler.  In the case of files, this is the path
; where data files are stored. Note: Windows users have to change this
; variable in order to use PHP's session functions.
...
```

Make sure you've installed the `memcached`  PHP plugin, see https://devdocs.magento.com/guides/v2.3/config-guide/memcache/memcache_ubuntu.html#config-memcache-install

**Comment by frilogg** [comment]
Any update on this issue?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38105` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
