### ISSUE TITLE
Not Able to set Rest API oAuth admin token expire in minutes or seconds

### ISSUE THREAD

**Issue by sangeetajain** [magento/magento2#24715]
How to set Rest API oAuth token expire in minutes or seconds in admin. Currently it's showing hours and it will not accept like 0.5(for 30 minute etc) magento2. Any One know about this, please help me asap.
![hvUMl](https://user-images.githubusercontent.com/4272871/65574113-2faf2880-df8a-11e9-9292-67cd5d42e16e.png)

**Comment by engcom-Bravo** [comment]
Hello @sangeetajain. The GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
