### ISSUE TITLE
Can't export Fixed Product Tax

### ISSUE THREAD

**Issue by orozcodiaz** [magento/magento2#24727]
### Preconditions (*)
1. Valet+ 1.0.27, MacOS and also Ubuntu 16.04 and 18.04
2. Nginx
3. Magento Commerce 2.3.1

### Steps to reproduce (*)
1. Create an attribute with type "Fixed Product Tax" and add it to "Default" attribute set
<img width="1792" alt="Screenshot 2019-09-25 10 11 12" src="https://user-images.githubusercontent.com/24477165/65608881-dc82a900-df7c-11e9-8f83-b4a2add1da88.png">
2. Add values to that attribute on product level
<img width="1792" alt="Screenshot 2019-09-25 10 07 29" src="https://user-images.githubusercontent.com/24477165/65608953-f91ee100-df7c-11e9-9b24-74a118ab475b.png">
3. Go to System - Export and export the product

### Expected result (*)
To see the fixed product tax values for a line item in CSV

### Actual result (*)
No signs of fixed product tax attribute and its values for any product

If we export from the same file we will see that the fixed price tax values are absent

![2020-08-05_15-55](https://user-images.githubusercontent.com/51679138/89415161-2bb86f00-d734-11ea-9872-64b7dfc5285a.png)

**Comment by orozcodiaz** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oroskodias. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @oroskodias, here is your [Magento instance](https://i-24727-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24727-2-3-develop.instances.magento-community.engineering/admin](https://i-24727-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orozcodiaz** [comment]
Can't test on your instance due to the file couldn't be generated. I'm getting this:
<img width="1792" alt="Screenshot 2019-09-25 10 27 31" src="https://user-images.githubusercontent.com/24477165/65610262-16ed4580-df7f-11e9-9804-dd97dad52aa1.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20482` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
