### ISSUE TITLE
Quote `customer_is_guest` set to 0 for guests

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24736]
### Preconditions
1. Magento 2.3.1

### Steps to reproduce (*)

1. Be guest
2. Put item in cart
3. Go to checkout
4. Fill in shipping information
5. Select shipping method
6. Proceed to payment screen

### Expected result (*)

1. In database, `quote.customer_is_guest` === 1

### Actual result (*)

1. `quote.customer_is_guest` === 0

:exclamation: **Take a note of the following:**
```
<column xsi:type="smallint" name="customer_is_guest" padding="5" unsigned="true" nullable="true"
                identity="false" default="0" comment="Customer Is Guest"/>
```
 in /app/code/Magento/Quote/etc/db_schema.xml. Though there probably everything works fine with quote.customer_is_guest in Core code it is still a bug of the code design. Once the field is 'nullable="true"' it would better remain null until it is set explicitly than be zero from the very beginning (default="0"). Or if for some reason it needs to be zero until being assigned a concrete value the comment="Customer Is Guest" is obviously not a sufficient one here. It's not right for the real guest customer to have its customer_is_guest being equal zero on any quote stage, at least unless there is something explanatory said on it. The side, i.e.  non-core developers (though probably some of the last ones too) may write wrong code being mislead by such a situation.

**Comment by ghost** [comment]
OK, so after a bit of digging, it seems that this flag is set to default as 0, and that it is only changed to 1 just before the order is placed, which seems like a bit of an odd way of doing things.

I'm my use case, I am trying to turn abandoned quotes into completed orders, but because a guest quote is initially set with `customer_is_guest = 0', when passing the quote through to submitted as an order, the validation kicks in to validate the customer details, which obv. don't exists for a guest quote.

**Comment by brunoroeder** [comment]
Hello @paul-gene 

This is how Magento works and not a bug so this issue should be closed.

**Comment by ghost** [comment]
@brunoroeder and that therein is the issue!

**Comment by Januszpl** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Januszpl. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Januszpl, here is your [Magento instance](https://i-24736-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24736-2-3-develop.instances.magento-community.engineering/admin](https://i-24736-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20528` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vpyatin** [comment]
@magento I am working on it

**Comment by ghost** [comment]
In the meantime, what are my options to work around this?

**Comment by engcom-Bravo** [comment]
@paul-gene, not sure, but I think there in the quote table another field like customer_id is supposed to exist. If it's there You may use it for checking on whether it is (was) guest customer or not. I mean if the customer_id is null or maybe zero then the customer is a guest, otherwise - a logged in one.

**Comment by nickpiro** [comment]
@sidolov this is a major issue still...Can we move it from 'Low Priority Backlog'? This causes the customer to not be able to checkout as it causes an error in the shopping cart.

**Comment by ihor-sviziev** [comment]
It looks like this issue duplicates https://github.com/magento/magento2/issues/23908 that has P1 priority, so I don't think we should re-open this one.
