### ISSUE TITLE
Suggested Terms Yes/No not in camel case

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#24739]
Suggested Terms Yes/No not in camel case

### Preconditions (*)
Magento 2.3

Steps to reproduce (*)
1. Admin -> Marketing 
2. SEO & Search -> Search Terms
3. Review the Suggested Terms drop-down text

Expected Result (*)
It should display in camel case as Yes/No

Actual Result (*)
![image](https://user-images.githubusercontent.com/49804008/65743037-7af34380-e110-11e9-8945-244820931d56.png)

**Comment by bhavik43** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bhavik43, here is your [Magento instance](https://i-24739-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24739-2-3-develop.instances.magento-community.engineering/admin](https://i-24739-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20525` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment]
@edenduong Please assign an issue to yourself and add WIP label before starting work to avoid duplicate work conflicts. Thanks.

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#24741 by @edenduong in 2.3-develop branch
Related commit(s):
 - [1ed98c65e632fc649de46cf5b97d994784cfe6f1](https://github.com/magento/magento2/commit/1ed98c65e632fc649de46cf5b97d994784cfe6f1)

The fix will be available with the upcoming 2.3.4 release.
