### ISSUE TITLE
MassAction: Grid's "Select All" feature is not transferring the correct list of selected IDs into the controller

### ISSUE THREAD

**Issue by skybreaker85** [magento/magento2#24732]
### Preconditions (*)
1. Magento Version 2.3.2 CE
2. ~10 Products you can add a Grid/Listing Filter on (e.g. by name)

### Steps to reproduce (*)

1. Have a clean magento Instance
2. Go to product Grid/Listing
3. Add some products (e.g. i added 5 with the name "product 1" (to ...5)  and 5 with the name "paper 1" (to ...5)
4. Filter products by name (e.g. "product")
5. Set the pagination to 2
6. Choose "Select all" from the Grid/Listings
7. now, it should be shown that 5 of 5 products are selected, the 2 visible ones have a checkmark (tbd: add screenshot)
8. choose a mass action (e.g. delete)

### Expected result (*)
1. All selected products should be deleted
2. (tbd: add screenshot)

### Actual result (*)
1. only the visible products are deleted
2. (tbd: add screenshot)

**Comment by skybreaker85** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @skybreaker85. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @skybreaker85, here is your [Magento instance](https://i-24732-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24732-2-3-develop.instances.magento-community.engineering/admin](https://i-24732-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by skybreaker85** [comment]
Does work on your system, but not with a fresh checked out instance (over composer create-project --repository=https://repo.magento.com/ magento/project-community-edition) on our side. will try to reproduce this on another system of ours.

**Comment by skybreaker85** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @skybreaker85. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @skybreaker85, here is your [Magento instance](https://i-24732-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24732-2-3-2.instances.magento-community.engineering/admin](https://i-24732-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by skybreaker85** [comment]
Ah well, so i found out why i could not reproducte this issue.
On the 2.3.2 instance, i could successfully reproduce this issue.
On the 2.3-develop instance, i could not, anymore. So it seems, it is already solved, although i previously have not found an issue where this was solved.

Sorry for the inconvenience.

**Comment by engcom-Bravo** [comment]
@skybreaker85 You are always welcome. Really I met at least two similar issues reported for the earlier versions, so I hope they have already been fixed.
