### ISSUE TITLE
Image in minicart is blurred on iPhone

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#24735]
### Preconditions (*)
1. Magento 2.3.2 with demo data

### Steps to reproduce (*)
1. Add some product to cart
2. Go to shopping cart
3. Open minicart and compare images that rendered on minicart and on shopping cart pages

### Expected result (*)
1. Both images should have good quality

### Actual result (*)
1. Image on cart page looks good, while image in minicart is blurred
![image](https://user-images.githubusercontent.com/1873745/65682814-60fc2700-e064-11e9-8379-6da277f257cd.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24735-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24735-2-3-develop.instances.magento-community.engineering/admin](https://i-24735-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have reproduced the issue in iPhoneXS Device.

**See attached the screenshot:**
![Product Image Issue_iPhoneXS](https://user-images.githubusercontent.com/24711761/65683712-9bbd8980-e07b-11e9-8296-d8c84c653989.jpg)

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20486` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kovinka** [comment]
@magento I'm working on it

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#24743 by @dmdanilchenko in 2.4-develop branch
Related commit(s):
 - [6950ead57dc9b17f8604401421fbf1339c81592d](https://github.com/magento/magento2/commit/6950ead57dc9b17f8604401421fbf1339c81592d)
 - [c7deb42a3b9b1875d4afe95ffea3c0f11cd1cb5d](https://github.com/magento/magento2/commit/c7deb42a3b9b1875d4afe95ffea3c0f11cd1cb5d)
 - [8f5f9a5274fced4667d938371ecd3337f2723369](https://github.com/magento/magento2/commit/8f5f9a5274fced4667d938371ecd3337f2723369)
 - [339168641792e42bd399dbed7b4d942b17315ce8](https://github.com/magento/magento2/commit/339168641792e42bd399dbed7b4d942b17315ce8)
 - [88d403ce8f9d78898a169be6eb75a3f9cd305f8a](https://github.com/magento/magento2/commit/88d403ce8f9d78898a169be6eb75a3f9cd305f8a)

The fix will be available with the upcoming 2.4.0 release.

**Comment by danieldespainTLS** [comment]
This was a terrible fix!  Now, with the width/2 code, you just get a teeny tiny image in a big white space.  The correct solution would be to put an image that's LARGER than the 75 pixel container into the space to accommodate the @2x resolution.

**Comment by palviggi-flagbit** [comment]
I'm too getting half sized images in the minicart on desktop now. was this tested?
i had to revert this one and  app/code/Magento/Checkout/view/frontend/web/template/summary/item/details/thumbnail.html (same problem, no ticket associated)

**Comment by danieldespainTLS** [comment]
We discovered that it was partly our fault.  The newer version of Magento updated the view.xml file to a value of 150 and then the .phtml file divides it (value from XML) in half.  We had modified the view.xml and still had the old value that was then divided by the phtml to result in tiny images.  If you haven't modified the xml or .phtml, then Magento works correctly "out of the box" but if you modified one or the other, you need to integrate the change into your code.

the XML:
app/design/frontend/{{vendor}}/{{module}}/etc/view.xml

look for <image id="mini_cart_product_thumbnail" type="thumbnail">

we had values of 75 (the old values). We removed this XML node to fix our problem, or you could change it to 150 which is what Magento uses by default now.
