### ISSUE TITLE
Duplicated regions on admin customer address

### ISSUE THREAD

**Issue by dzungnt** [magento/magento2#24738]
### Preconditions (*)
I'm using magento 2.3.2 version and getting issue that the regions are duplicated on admin customer address
### Steps to reproduce (*)
1. Go to Admin >> Customers >> All Customers
2. Select a customer
3. Go to Addresses tab and add new address
4. Select country is Australia

### Expected result (*)
1. The states should be listed with no duplicate

### Actual result (*)
1. All of states are duplicated
![Screenshot 2019-09-27 11:17:55](https://user-images.githubusercontent.com/11495948/65742000-8480a980-e118-11e9-8d3f-fe54659f8c4b.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24738-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24738-2-3-develop.instances.magento-community.engineering/admin](https://i-24738-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have added more than 3 customers added with new addresses. Still, not able to reproduce these issues.
I am using the latest Magento 2.3 instance. 
@dzungnt - Please update your status. If you have not found this issue again please update me define some steps to be reproduced or video.

**See attached screenshot:**
![2019-09-27](https://user-images.githubusercontent.com/24711761/65742751-256a6700-e10f-11e9-909a-2276f79122b7.png)

Thanks.

**Comment by ajijshekh123** [comment]
@dzungnt - This issue is reproduced in Magento 2.3 Enterprise Version.

See attached screenshot:
![Found issue](https://user-images.githubusercontent.com/24711761/65742910-d7a22e80-e10f-11e9-88e5-1e40c4992c09.png)

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by ajijshekh123** [comment]
https://github.com/magento/magento2/issues/22484
This issue is duplicate

**Comment by krishprakash** [comment]
@sdzhepa as this issue comes on enterprise version of manento and which already fixed in #22484 related commit for open source version.
So please move this issue to EE repository 
Thanks.
