### ISSUE TITLE
Error "Url key for specified store already existed" when saving category products on Chrome

### ISSUE THREAD

**Issue by nguyetnguyen** [magento/magento2#2474]
Dear team, 
I got an error when doing steps like this:
1. Go to the backend > Product > Categories > select an category
2. Click on tab "Category products"
3. Select "NO" in the 1st column 
4. Search for name or any attribute
5. Select all visible products 
6. Save the category
=> We got the error message "Url key for specified store already existed". This is only happened on Chrome. Firefox works fine. I used beta6 version.

**Comment by dmitrii-fediuk** [comment]
Looks related (but not the same) to https://github.com/magento/magento2/issues/2368 and https://github.com/magento/magento2/issues/2013

**Comment by vkholoshenko** [comment]
Hi, @nguyetnguyen. Thanks for reporting! It seems that issue doesn't appear on current develop branch. Could you please confirm that you don't have this problem on newest code?

**Comment by davidalger** [comment]
Closing as non-reproducible on latest mainline and no reply from OP
