### ISSUE TITLE
Unable to create credit memo when sku is numeric

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#24742]
### Preconditions (*)

1. Install Magento 2.3.2

### Steps to reproduce (*)

1. Create product with numeric SKU (like 1000)
2. Order that item
3. Create an invoice
4. Create a credit memo for that invoice

### Expected result (*)

1. Credit memo will be created

### Actual result (*)

1. Creation fails

`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\InventorySales\Model\ReturnProcessor\GetInvoicedItemsPerSourceByPriority::getSourceCodeWithHighestPriorityBySku() must be of the type string, integer given`

All ordered items are stored in an array `$invoicedItems[$itemSku]` (see `vendor/magento/module-inventory-sales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php:99`).

PHP doesn't allow "numeric strings" as array keys - they will be casted to integer values. Due to this automatic cast the signature of `getSourceCodeWithHighestPriorityBySku(string $sku, int $stockId)` doesn't match.

**Comment by klein0r** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @klein0r. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @klein0r, here is your [Magento instance](https://i-24742-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24742-2-3-develop.instances.magento-community.engineering/admin](https://i-24742-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by klein0r** [comment]
Sorry, wrong project. See duplicate https://github.com/magento/inventory/issues/2429
