### ISSUE TITLE
Duplicating product functionality doesn't support bundle products

### ISSUE THREAD

**Issue by Stepa4man** [magento/magento2#24757]
If bundle product was duplicated - simple products unlink from original bundle product

### Preconditions
1. Create bundle product with several bundle options and link simple products to them

### Steps to reproduce
1. Go to edit bundle product at the admin area
2. Hit save and duplicate btn
3. Enable newly created bundle product and save it

### Expected result
1. There are two bundle products with with the same options and products assigned to them

### Actual result
1. Duplicated product has all options and simple product assigned to them
![image](https://user-images.githubusercontent.com/15912461/65773312-5ad97980-e13c-11e9-9b83-be8f4041a7d9.png)

2. Original product has options but doesn't have any simple products assigned to options
![image](https://user-images.githubusercontent.com/15912461/65773228-29f94480-e13c-11e9-90a0-c8c90d8e3b04.png)

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20532` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MaxSouza** [comment]
I'm working on it

**Comment by hostep** [comment]
Let's close this as a duplicate to https://github.com/magento/magento2/issues/13126 which was fixed very recently in https://github.com/magento/magento2/pull/24703

If I'm mistaken, please let me know!
