### ISSUE TITLE
When currency set to CHF, second dezimal is removed in price

### ISSUE THREAD

**Issue by abombelli** [magento/magento2#24764]
### Preconditions (*)
1. Magento CE 2.3.2 without sample data is installed.
2. Default Luma theme installed.

### Steps to reproduce (*)
1. Set currency to CHF
2. Add product with price 50.00

### Expected result (*)
1. In the frontend the price should show the same (CHF 50.00)

### Actual result (*)
1. This is the actual result: https://prnt.sc/osh9bm
2. The HTML code contains 50.00, but it looks like some JS removes the last 0

**Comment by engcom-Bravo** [comment]
Hello @abombelli. Thanks for reporting. We've been not able to reproduce Your issue nether on the latest 2.3-develop nor on the reported 2.3.2 version. Could You please ask a bot for an instance as You are advised [above](https://github.com/magento/magento2/issues/24764#issuecomment-535966122) and try to reproduce the issue on that instance. Thank You in advance.

**Comment by sudheers-kensium** [comment]
@abombelli You need to set the both Base Currency and Default Display Currency

**Comment by abombelli** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @abombelli. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @abombelli, here is your [Magento instance](https://i-24764-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24764-2-3-develop.instances.magento-community.engineering/admin](https://i-24764-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by abombelli** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @abombelli. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @abombelli, here is your [Magento instance](https://i-24764-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24764-2-3-2.instances.magento-community.engineering/admin](https://i-24764-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by abombelli** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @abombelli. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @abombelli, here is your [Magento instance](https://i-24764-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24764-2-3-2.instances.magento-community.engineering/admin](https://i-24764-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by abombelli** [comment]
@sudheers-kensium I made some further testing. On our end we have price precision set to 1 (also in swatches).
`priceBoxes.priceBox({'priceConfig': {"productId":"29","priceFormat":{"pattern":"CHF\u00a0%s","precision":1,"requiredPrecision":1,"decimalSymbol":".","groupSymbol":"'","groupLength":3,"integerRequired":false},"prices":{"oldPrice":{"amount":21.5,"adjustments":[]},"basePrice":{"amount":21.5,"adjustments":[]},"finalPrice":{"amount":21.5,"adjustments":[]}},"idSuffix":"_clone","tierPrices":[],"calculationAlgorithm":"TOTAL_BASE_CALCULATION"}});`


```
{
--
  | "[data-role=swatch-options]": {
  | "Magento_Swatches/js/swatch-renderer": {
  | "jsonConfig": {"attributes":{"172":{"id":"172","code":"size","label":"Verpackungsgr\u00f6sse","options":[{"id":"9","label":"3 kg","products":["30"]},{"id":"10","label":"12 kg","products":["31"]}],"position":"0"}},"template":"CHF\u00a0<%- data.price %>","currencyFormat":"CHF\u00a0%s","optionPrices":{"30":{"oldPrice":{"amount":21.5},"basePrice":{"amount":21.5},"finalPrice":{"amount":21.5},"tierPrices":[],"msrpPrice":{"amount":null}},"31":{"oldPrice":{"amount":79.5},"basePrice":{"amount":79.5},"finalPrice":{"amount":79.5},"tierPrices":[],"msrpPrice":{"amount":null}}},"priceFormat":{"pattern":"CHF\u00a0%s","precision":1,"requiredPrecision":1,"decimalSymbol":".","groupSymbol":"'","groupLength":3,"integerRequired":false},"prices":{"oldPrice":{"amount":21.5},"basePrice":{"amount":21.5},"finalPrice":{"amount":21.5}},"productId":"29","chooseText":"Choose an Option...","images":[],"index":{"30":{"172":"9"},"31":{"172":"10"}}},
  | "jsonSwatchConfig": {"172":{"9":{"type":"0","value":"3 kg","label":"3 kg"},"10":{"type":"0","value":"12 kg","label":"12 kg"}}},
  | "mediaCallback": "https://demo.com/swatches/ajax/media/",
  | "gallerySwitchStrategy": "prepend",
  | "jsonSwatchImageSizeConfig": {"swatchImage":{"width":35,"height":35},"swatchThumb":{"height":35,"width":35}} }
  | },
  | "*" : {
  | "Magento_Swatches/js/catalog-add-to-cart": {}
  | }
  | }

```

Where can we change this setting and why is it set to 1 and on the Magento test instances it is 2?
