### ISSUE TITLE
Mail template footer

### ISSUE THREAD

**Issue by albsa** [magento/magento2#2477]
There are qoutes in de mail template footer. See screenshot.
![](http://i.imgur.com/fFHqrmS.jpg)

**Comment by MomotenkoNatalia** [comment]
@albsa  Thanks for reporting this issue! This is a known bug, internal ticket MAGETWO-45067

**Comment by parthviroja** [comment]
This is not an bug, Need to fill store information from Admin Side.

Admin -> Stores -> Configuration -> General -> General -> Store Information 

After fill this info, you can visible data in footer block of mail

**Comment by magento-engcom-team** [comment]
@albsa, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9
