### ISSUE TITLE
Menu contains duplicated "active"-css classes 

### ISSUE THREAD

**Issue by ulftietze** [magento/magento2#24776]
### Preconditions (*)

1. Magento 2.3.2 (but should be work on Magento 2.3.3 as well because the files don't change)
2. PHP 7.2 (should be irrelevant)
3. Active caches in Magento

### Steps to reproduce (*)

1. Create some categories and let them appear in MenuNav
2. Clear Cache
3. Click on a category
4. Click on another category.

### Expected result (*)

1. The active class should only be on the current active category

### Actual result (*)

1. Both categories (the one clicked before and the current) contain the 'active' class

### Notes
I did some research on here. The Menu Navigation is cached by block? cache, and the active CSS-Class is created in Backend in `Magento\Theme\Block\Html\Topmenu::320`.
The js file `mage/menu` in `lib/web/mage/menu.js` is generating the active status for the menu as well, but it never removes it. This process starts at line 125.
We have to decide between 2 options.
1. The first and the most easy way is to remove the lines 320-324 `Magento\Theme\Block\Html\Topmenu`. The JS will add the current active class after the document is loaded. But i don't know, if this will generate problems in another usage of the menu. Another disadvantage is: the active class is show just after all js was loaded (sometimes this could be half of a second) so the user see some non smooth "jumping" on page.
2. We could add a `delete` function while adding the active class to the menu. So just one category point could be active at time. Probleme is the user will see the wrong category for ~0,5 seconds. And after that he's going to see a jumping like in point 1.

I hope i can find some time to create a smooth fix for this. But i can't promise ^^

Greetz, Ulf

**Comment by hostep** [comment]
This is probably a duplicate of https://github.com/magento/magento2/issues/22407
Fix can be found in: https://github.com/magento/magento2/issues/22407#issuecomment-532954532 (fix will probably be part of Magento 2.3.4)

@ulftietze: can you confirm this fixes the issue? If yes you may close this issue, thanks! :)

**Comment by ulftietze** [comment]
@hostep Thanks for reference another issue here, i did not find that one.
But indeed this fixes the issue :+1:
