### ISSUE TITLE
Admin panel is frozen if Storefront is opened via Customer View

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#24779]
### Preconditions (*)

1. Self-registered Customer
2. An order placed from Storefront by Customer
3. A Merchant or Support Stuff that tries to reproduce some problems with order reported by Customer, let say by telephone call.

### Steps to reproduce (*)

1. Log in to Admin (Tab 1)
2. Navigate to Sales -> Orders (Tab 1)
3. Open an order (Tab 1)
4. Click **Customer View** in the top-right menu widget (Tab 1).
5. Create a test customer in the tab that was opened automatically (Tab 2)
6. Place an order and click print. You should see the print preview. (Tab 2)
7. Navigate to Tab 1. Try any button in admin. Reload the page.

### Expected result (*)

1. Admin panel does not hang

### Actual result (*)

1. Admin panel freeze. Reload never ends.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20623` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @drpayyne, here is your [Magento instance](https://i-24779-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24779-2-3-develop.instances.magento-community.engineering/admin](https://i-24779-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/magento2#24845 by @drpayyne in 2.3-develop branch
Related commit(s):
 - [8baeec344c5063d65eff5a79a0ddf7125ecc6951](https://github.com/magento/magento2/commit/8baeec344c5063d65eff5a79a0ddf7125ecc6951)
 - [5fc4b458e9ef0becfed3abb857cb81c860433b71](https://github.com/magento/magento2/commit/5fc4b458e9ef0becfed3abb857cb81c860433b71)

The fix will be available with the upcoming 2.3.4 release.
