### ISSUE TITLE
Magento 2.3.2 with ElasticSearch Sever 7.3 not working

### ISSUE THREAD

**Issue by extremeskillz** [magento/magento2#24777]
Server OS: ubuntu 16.04lts
Apache2.4
Magento2.3.2 with ElasticSearch 6.0+ enabled
ElasticSearch Server 7.3 (latest)

Hi All,
Not sure if this is a bug or not but I'm running the latest and greatest magento2.3.2 with elasticsearch 7.3. I have followed the magento2.3 dev docs to enable and configure the system but searches are coming up empty on the client front end of magento2. The admin back end search seem to be the same as it was before as I am able to search for product. All frontend searches come up blank.
When running the indexer from the cli I get this error:

Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}

The indexer running under mysql runs fine and runs normal as it should.

I know the server is running fine as Magento2 confirms it connects successfully and the on the cli side the curl results are as follows:
{
  "name" : "localhost",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "T2GTdh5GSmmZbQQ2mI3BSw",
  "version" : {
    "number" : "7.3.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "1c1faf1",
    "build_date" : "2019-09-06T14:40:30.409026Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

Any Ideas?

As of right now I swithced back to mysql search. Please advise.

Thanks,
Carlos

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by ihor-sviziev** [comment]
Not sure that Elasticsesrch 7.x is supported, I already reported an issue in devdocs https://github.com/magento/devdocs/issues/5488

**Comment by engcom-Charlie** [comment]
Hello @extremeskillz  @ihor-sviziev !
I tested Magento 2.3-develop with Elasticsearch 7.3 and he didn't work.
Magento 2.3.x supports Elasticsearch up to 6.x.  
![image](https://user-images.githubusercontent.com/51680850/65852974-9e143200-e360-11e9-9ae5-1dc71328cc66.png)
Info from [this](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html) topic.

**Comment by ihor-sviziev** [comment]
Hi @extremeskillz,

As @engcom-Charlie said - Elasticsearch 7.x isn't supported yet. Could you report this feature request  to https://github.com/magento/community-features?

I'm closing this issue as there are no action items left

**Comment by extremeskillz** [comment]
Sounds good but the issue is that in installed it from repo for ubuntu which is current with the latest elasticsearch 7.3 as of this writing. I will make a feature request but this will break anyones magento2.3 install if they are using the repo to update. Thanks for the update!

**Comment by ihor-sviziev** [comment]
Hi @extremeskillz,
Actually it will be the same with any other component, for instance php7.3 isn’t supported, but might be latest php version in some Linux distribution. So there we can do following - add feature request for es7.x support and update docs to make it more clear that current versions isn’t support it

**Comment by extremeskillz** [comment]
I see what your saying. Part of the issue ihor-sviziev is that elasticsearch is part of Ubuntu repos and gets updated as soon as a release comes out. So my install for this issue was 7.3, they just released 7.4 today in the repos. The only way to not do that is installing elasticsearch  manually with there standalone packages. The docs are not clear on this especially those using the CE versions of Magento2. Currently, I removed all versions of elasticsearch as even the older versions require dependencies no longer supported by either ubuntu or elasticsearch. I'm not doing down that rabbit hole for now until software is updated. I'm on ubuntu 16.04 lts but we plan on upgraded to 18.04lts soon so this will introduce its own set of issues.

**Comment by RHapani** [comment]
Hello All,
Any update for this query?
I also face same issue.
What should I need to do to configure elasticsearch 7.x?

Please help me.

**Comment by ihor-sviziev** [comment]
Update: in `2.4-develop` branch we already have Elasticsearch7 module, so it will be supported in 2.4.0.
https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento/Elasticsearch7

**Comment by RHapani** [comment]
If I want to add in 2.3.3 then, how can I configure? I can't able to add the library in Magento 2.3.3

**Comment by ihor-sviziev** [comment]
Unfortunately it’s not supported

**Comment by alexkrm** [comment]
Can we safely say, that starting from 2.3.5 version Magento CE supports ElasticSearch 7.x? 
https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html#es-spt-versions

**Comment by ihor-sviziev** [comment]
Yes, starting from 2.3.5 we have support for elasticsearch 7.x, here is
module
https://github.com/magento/magento2/tree/2.3.5/app/code/Magento/Elasticsearch7
