### ISSUE TITLE
encryption key screen escaping HTML

### ISSUE THREAD

**Issue by Lewiscowles1986** [magento/magento2#2478]
So brand new install of 2.0.0, seeing this

![encryption key other settings system magento admin](https://cloud.githubusercontent.com/assets/2605791/11327256/395bac64-9178-11e5-8389-46376d5d81a5.png)

**Note**  
I Copied the actual key into the input before thinking to take the screengrab

**Comment by monkeysee** [comment]
Thank you, @Lewiscowles1986 , we have internal bug MAGETWO-44034 for this problem.

**Comment by eddielau** [comment]
Issue will be fixed in internal bug ticket MAGETWO-47704

**Comment by sshrewz** [comment]
This issue has been fixed and merged to develop.  Feel free to reopen if you encounter any issues.

**Comment by Lewiscowles1986** [comment]
thank you :+1:
