### ISSUE TITLE
All selected values still display as Select all in downloadable product

### ISSUE THREAD

**Issue by renard123** [magento/magento2#24785]
All selected values still display as Select all in downloadable product

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Admin -> Catalog -> Products -> Add New downloadable product
2. Add 2 options for downloads so display Select all/ Unselect all feature.
3. Add product
4. Front end -> Add product with both options as select all
5. Go to shopping cart/Mini cart
6. Edit the product 
7. Review both options are selected and display feature as Select all 

### Expected result (*)
Unselect all should display if all options selected

### Actual result (*)
![09 27 2019-17 14](https://user-images.githubusercontent.com/50658701/65863180-4cce6780-e38d-11e9-8faa-d36b7c4d3277.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24785-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24785-2-3-develop.instances.magento-community.engineering/admin](https://i-24785-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20621` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @drpayyne, here is your [Magento instance](https://i-24785-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24785-2-3-develop.instances.magento-community.engineering/admin](https://i-24785-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by angelgonzalezi4** [comment]
I try to reproduce this task, but i can't do it. If i add to cart all the options that it has a downloadable product, I can click the link "select all" or "unselect all" without problems...

**Comment by drpayyne** [comment]
@angelgonzalezi4 Hi, this was fixed by me in the above mentioned PR. Not sure why this issue wasn’t auto closed. 

@sidolov @VladimirZaets any idea why?
