### ISSUE TITLE
product images not loading / infinite loading product Magento 2.3.2

### ISSUE THREAD

**Issue by Prareric** [magento/magento2#24787]
Magento 2.3.2 /  Porto 3.1.8 (Theme) / PHP 7.2 / Ubuntu 18.04

![problem loading](https://user-images.githubusercontent.com/44494027/65874160-653a8400-e385-11e9-9194-b806f68337b9.PNG)
![1www](https://user-images.githubusercontent.com/44494027/65874179-7aafae00-e385-11e9-9cf1-e4290a7b1e9d.PNG)

**Comment by krishprakash** [comment]
Hi @Prareric.
It works fine in venilla magento instance.
It should be Porto theme issue or any of your custom code issue.
Let me know the steps to reproduce for this issue if you confirm that it reproduce in venilla magento instance.
Thanks.

**Comment by krishprakash** [comment]
Hi @Prareric.
Feel free to reopen the issue if you confirm that it reproduce on venilla Magento instance.
Thanks
