### ISSUE TITLE
Elasticsearch 6 works with Elasticsearch 5 client on frontend

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#24781]
### Preconditions (*)
1. Magento 2.3.2 & 2.3-develop
2. Elasticsearch 6.5
3. XDebug

### Steps to reproduce (*)
1. Open PhpStorm, add breakpoints in:
- Elasticsearch 6.x client: https://github.com/magento/magento2/blob/6d6f11b3ff4dc290c1e53c8822e136547b38f05e/app/code/Magento/Elasticsearch6/Model/Client/Elasticsearch.php#L66
- Elasticsearch 5.x client: https://github.com/magento/magento2/blob/6d6f11b3ff4dc290c1e53c8822e136547b38f05e/app/code/Magento/Elasticsearch/Elasticsearch5/Model/Client/Elasticsearch.php#L71
2. Go to Admin >> Stores >> Configurations >> Catalog >> Catalog >> Search
3. Configure Elasticsearch settings to use "Elasticsearch 6.0+" option
4. Click "Test connection", see where your breakpoint was paused
5. Save all configs, do reindex
6. Go to any category page, see where your breakpoint was paused
7. Go to any search page, see where your breakpoint was paused

### Expected result (*)
1. In all cases you should see that code paused at Elasticsearch 6.x client

### Actual result (*)
1. During test connection code paused in **Elasticsearch 6.x** client ✔
2. On category page code paused in **Elasticsearch 5.x** client ❌
2. On search results page code paused in **Elasticsearch 5.x** client ❌

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20619` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
This issue was fixed by @p-bystritsky  in https://github.com/magento/magento2/pull/24974 and fix will be available in Magento 2.3.4.
