### ISSUE TITLE
Checks like `is customer locked` or `scope` should happen before the customer will even get a token

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#24780]
### Preconditions (*)

1. Two websites

|Web Site|Store|Store View|
|---|---|---|
|Main Website<br>`base`|Main Website Store<br>`main_website_store`|Default Store View<br>`default`|
|Test Website<br>`additional`|Test Website Store<br>`test_website_store`|Test Store View<br>`test`|
2. **Account Sharing Options** has its default global setting **Share Customer Accounts** = **Per Website**

### Steps to reproduce (*)

1. Create Customer on the `default` Store View
**Headers**
```json
{
  "Store": "default"
}
```

**Request**
```graphql
mutation {
  createCustomer(
    input: {
      prefix: "Prince"
      firstname: "John"
      suffix: "IV"
      middlename: "Ruel"
      lastname: "Doe"
      email: "John.Doe@example.com"
      dob: "10/10/10"
      gender: 1
      password: "123123qA"
    }
  ) {
    customer {
      prefix
      firstname
      lastname
      middlename
      suffix
      email
      dob
      gender
    }
  }
}
```
2. Create Customer on the `test` Store View
**Headers**
```json
{
  "Store": "test"
}
```

**Request**
```graphql
mutation {
  createCustomer(
    input: {
      prefix: "Prince"
      firstname: "John"
      suffix: "IV"
      lastname: "Doe"
      email: "John.Doe@example.com"
      dob: "11/11/11"
      gender: 3
      password: "123123qAqA"
    }
  ) {
    customer {
      prefix
      firstname
      lastname
      middlename
      suffix
      email
      dob
      gender
    }
  }
}
```
2. Generate Customer's token for the customer on `default` Store View
**Headers**
```graphql
{
  "Store": "default"
}
```
**Request**
```graphql
mutation {
  generateCustomerToken(
    email: "John.Doe@example.com"
    password: "123123qA"
  ) {
    token
  }
}
```
3. Get Customers information from the `test` Store View using token for `default` Store Virew
**Headers**
{
  "Authorization": "Bearer xo0aqut1x5erzjv2du6vu6qbbegkjpmr",
  "Store": "ssetview"
}
**Request**
```graphql
query {
  customer {
    created_at
    default_billing
    default_shipping
    dob
    email
    firstname
    gender
    group_id
    id
    is_subscribed
    lastname
    middlename
    prefix
    suffix
    taxvat
    group_id
  }
}
```
### Expected result (*)

1. Authorization problem

### Actual result (*)

1. Information was returned from the Default Store View.

**Comment by kisroman** [comment]
Working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20664` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
