### ISSUE TITLE
2.2.3 Could not open socket

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#24793]
Hello folks,
After upgrading 2.2.3 smtp extension (Magepal) stopped working.
With some investigations found error thrown from zendframework1/library/Zend/Mail/Protocol\Abstract.php line 271. Trace is below.
### Preconditions (*)

1. Magento 2.2.3
2. PHP 7.0.3

### Steps to reproduce (*)

1. Tried multiple smtp extensions
2. Same error 'Could not open socket'

### Expected result (*)

1. Send mail.

### Actual result (*)

1. in trace :`stream_socket_client(): php_network_getaddresses: getaddrinfo failed: System error`
2. at backend `Could not open socket`

**Comment by srenon** [comment]
@rbostan .. this is a server config issue and not a Magento or MagePal issue. 

To debug take a look at https://github.com/magepal/magento2-gmail-smtp-app/issues/30

**Comment by engcom-Charlie** [comment]
Hello @rbostan 
The GitHub issue tracker is intended for Magento Core technical issues only.
Thanks for your report!
