### ISSUE TITLE
Possibility to create non unique admin value for attribute option in configurable product modal

### ISSUE THREAD

**Issue by wilfriedwolf** [magento/magento2#24798]
### Preconditions (*)

1. Magento CE 2.3.2 is installed with sample data (also tested with CE 2.2.9)

### Steps to reproduce (*)

1. Edit any configurable product
2. Go to configurations and press "Edit Configurations"
3. Check "format" (or any attribute which allows the creation of new options), then press "Next"
4. Click on "Create New Value" there and create a new Option identical to one already existing (e.g. DVD)
5. Finish saving the Product
6. Now go to the chosen product attribute and try managing its options. 

### Expected result (*)

1. Managing the product options of this attribute should work
2. The admin values should be unique

### Actual result (*)

1. You get an error "The value of Admin must be unique."
2. There are two rows with the same admin value

**Comment by wilfriedwolf** [comment]
If I understand it right, the check for duplicate admin value is missing in
`\Magento\ConfigurableProduct\Controller\Adminhtml\Product\Attribute\CreateOptions::saveAttributeOptions`

**Comment by engcom-Bravo** [comment]
Hello @wilfriedwolf. Thanks for reporting. Could You please retest Your issue on the latest develop version. We  did that and obtained some other behavior not the one You've described in Your Actual Result but nevertheless definitely also a wrong one. There is an empty row appearing before the row with the newly added value when You open the attribute for editing it.
![format](https://user-images.githubusercontent.com/51680745/65970323-fdf8fe80-e46e-11e9-98e5-8253f72f6cc5.png)
But if You delete that empty row You can normally edit the attribute.

**Comment by wilfriedwolf** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wilfriedwolf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wilfriedwolf, here is your [Magento instance](https://i-24798-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24798-2-3-develop.instances.magento-community.engineering/admin](https://i-24798-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by wilfriedwolf** [comment]
On the 2.3-develop instance I found a totally correct behaviour. Since there was no sample Data, I created some colors on the attribute "color" (black, blue, green) and created a configurable test product. Editing this product I was not able to insert "green" again, it gave me a red mark and saving said that attribute option should be unique.
![m23-dev](https://user-images.githubusercontent.com/23700116/65996258-5e9c3180-e497-11e9-92e8-d5aa7771751e.png)
Saving another option ("purple") also results in correct behaviour, I did not find an empty line
![purple](https://user-images.githubusercontent.com/23700116/65996497-cd798a80-e497-11e9-9cf9-552779a9c343.png)
So I guess, you fixed it by now :)
Thanks and best regards.
Willi

**Comment by wilfriedwolf** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wilfriedwolf. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by wilfriedwolf** [comment]
Ok, so, will this be fixed in the 2.2 release line too, since the problem is in our shop with Magento CE 2.2.9

**Comment by engcom-Bravo** [comment]
@wilfriedwolf, Thank You for the work You've done. Unfortunately branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details. So, unfortunately, the fix won't be provided for 2.2 versions. Also we'd still like You to recheck the issue with the attribute You reported about. i.e. "format". Would You do that please. Thank You.

**Comment by wilfriedwolf** [comment]
I would, but i am not quite sure, how to get a Magent 2.3-develop Instance with sample Data.

**Comment by engcom-Bravo** [comment]
Really... @wilfriedwolf. And couldn't You download and install a vanilla 2.3-develop from github for that?

**Comment by wilfriedwolf** [comment]
I could and should, yes. give me a while...

**Comment by wilfriedwolf** [comment]
Didn't find out yet how to install sample data on cloned project, but I'll manage :)

**Comment by engcom-Bravo** [comment]
@wilfriedwolf, here is the repository to clone a simple data from. And in its Readme You can find the instruction on how to install it in particular for gitcloned instances.

**Comment by engcom-Bravo** [comment]
Sorry, here it is: https://github.com/magento/magento2-sample-data

**Comment by engcom-Bravo** [comment]
Hi @wilfriedwolf. The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by tuyennn** [comment]
The issue could be replicated on M2.4.1 @engcom-Bravo  @wilfriedwolf possible reopen the ticket

**Comment by wilfriedwolf** [comment]
Hi @tuyennn, actually I do not have the time to invest in this Bug and I do not know how to reopen the ticket. Anyhow, if @engcom-Bravo does, I'll happily discuss here with you :)
