### ISSUE TITLE
Front-end development workflow Error

### ISSUE THREAD

**Issue by nhimxugia** [magento/magento2#2479]
Front-end development workflow, i select Client side less compilation -> backend is broken.

http://prntscr.com/95uoha

Thanks!...

**Comment by zanilee** [comment]
Hi, @nhimxugia!

It seems you didn't clear caches from `pub/static/` and `var/` folders after changing the compilation mode to client side.
Please clear caches and check it again.

**Comment by MomotenkoNatalia** [comment]
@nhimxugia Any updates on this?

**Comment by MomotenkoNatalia** [comment]
@nhimxugia I close the issue for now. If you have further question to this issue please feel free to reopen
