### ISSUE TITLE
REST API. List products with parent/child relation (parent_sku is missing)

### ISSUE THREAD

**Issue by voronytskyi** [magento/magento2#24797]
### Description (*)
**parent_sku** is missing for **{{baseUrl}}/V1/products** API response

### Expected behavior (*)
**parent_sku** is null in case if doesn't have any parent product relation (configurable products)

### Benefits
easy way to build parent/child relations

### Additional information
I aware about **{{baseUrl}}/V1/configurable-products/{sku}/children** API. But it`s extra request each time in order to check if product has child product variants

**Comment by engcom-Charlie** [comment]
Hello @sdzhepa !
This issue looks like feature request.
Could you take a look?

**Comment by voronytskyi** [comment]
@engcom-Charlie  should I move it by my own?

**Comment by engcom-Charlie** [comment]
@voronytskyi yes, of course
