### ISSUE TITLE
Self help link pointing to old docs

### ISSUE THREAD

**Issue by fooman** [magento/magento2#2480]
The help button in the admin area under Stores > Configuration
![screenshot-a994db77dd85 local fooman co nz 2015-11-23 18-29-42](https://cloud.githubusercontent.com/assets/455508/11330526/89177e10-9211-11e5-87f1-c4255fd80db0.png)

points to this URL
http://www.magentocommerce.com/knowledge-base/entry/understanding-store-scopes
which currently redirects to here
http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#configuration/scope.html
which currently shows the user guide for Magento 1.9

**Comment by ghost** [comment]
Thank you for reporting this. We're tracking it via internal issue MAGETWO-45955

**Comment by mazhalai** [comment]
@fooman this issue has been fixed. Please check it in the develop branch. Also, if you still encounter any issues, please open a new issue.
