### ISSUE TITLE
Accordion widget buggy transition

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#24807]
When using the code sample from https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_accordion.html for an accordion widget - but setting the animate property to a numeric value - the transition works correctly for individual collapse elements, but when clicking to open a closed element the currently open element closes instantaniously without a transition.

### Preconditions (*)

1. Magento 2.3.2 & 2.3-develop

### Steps to reproduce (*)

1. Add an accordion widget to any page using the code sample from https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_accordion.html
2. Assign a numeric value to the 'animate' option e.g. `"animate": {"duration": 600}`
Using the following HTML for the accordion: 
```
<div id="accordion" data-mage-init='{
        "accordion":{
            "collapsible": true,
            "openedState": "active",
            "openOnFocus": true,
            "animate": {"duration": 600}
        }}'>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Title 1</h4>
    </div>
  </div>
  <div data-role="content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</div>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Title 2</h4>
    </div>
  </div>
  <div data-role="content">It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Title 3</h4>
    </div>
  </div>
  <div data-role="content">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</div>
</div>
```
3. Open a closed element and observe the transition of both it and the currently open element.

### Expected result (*)

1. Both elements transition according to the time set in the animate property.

### Actual result (*)

1. The element being clicked or focused transitions according to the animate property
2. The currently open element closes instantly causing a jerky transition.
![accordion](https://user-images.githubusercontent.com/33320744/65955548-4f3dc980-e440-11e9-9f25-86877609e9c0.gif)

**Comment by BezV8** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @BezV8, here is your [Magento instance](https://i-24807-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24807-2-3-develop.instances.magento-community.engineering/admin](https://i-24807-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by BezV8** [comment]
@magento I can confirm the problem is present on the test instance. 
![accordion](https://user-images.githubusercontent.com/33320744/65955548-4f3dc980-e440-11e9-9f25-86877609e9c0.gif)
Using the following HTML for the accordion: 
```
<div id="accordion" data-mage-init='{
        "accordion":{
            "collapsible": true,
            "openedState": "active",
            "openOnFocus": true,
            "animate": {"duration": 600}
        }}'>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Title 1</h4>
    </div>
  </div>
  <div data-role="content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</div>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Title 2</h4>
    </div>
  </div>
  <div data-role="content">It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>
  <div data-role="collapsible">
    <div data-role="trigger">
      <h4>Title 3</h4>
    </div>
  </div>
  <div data-role="content">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</div>
</div>
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21499` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
@magento I am working on it

**Comment by gabrieldagama** [comment]
The PR has been approved and merged.
