### ISSUE TITLE
Custom customer datetime attribute not saves

### ISSUE THREAD

**Issue by med-amin** [magento/magento2#24802]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2.22

### Steps to reproduce (*)

1. Create a new attribute with type DateTime for a customer using InstallData.php
2. do bin/magento setup:upgrade

### Expected result (*)

1. the attribute shows up in  "Account information" section
2. save the attribute value

### Actual result (*)

1. No error at all
2. the value is not saved 
3. I created a gist with my [InstallData ](https://gist.github.com/med-amin/f71e1246a8adbe2ebabe61a7137ad547)

**Comment by magento-engcom-team** [comment]
Hi @med-amin. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @med-amin, here is your [Magento instance](https://i-24802-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24802-2-3-develop.instances.magento-community.engineering/admin](https://i-24802-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21500` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Kilo** [comment]
Hello, @med-amin 
Thanks for your report. I'm not able to reproduce this issue on latest 2.4-develop
![CustomerCustomAttributeTypeDate](https://user-images.githubusercontent.com/60192090/103993537-6e2c1f00-519e-11eb-9ccc-28178dd2cb18.gif)
Please feel free to add more details and I reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @med-amin. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24868` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @med-amin. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24868` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
