### ISSUE TITLE
Inconsistent and Improper Capitalization of Heading

### ISSUE THREAD

**Issue by drpayyne** [magento/magento2#24803]
### Preconditions
- `2.3-develop` branch

### Steps to reproduce (*)
1. Log in to admin
2. Navigate to Marketing -> Communications -> Email Templates
3. Create a new template
4. Heading in the first line is inconsistent and improper

### Expected result (*)
![image](https://user-images.githubusercontent.com/22623301/65946659-422ad580-e454-11e9-8584-02202f57f3fc.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/22623301/65946560-0ee84680-e454-11e9-8076-69b648278379.png)

**Comment by drpayyne** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @drpayyne, here is your [Magento instance](https://i-24803-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24803-2-3-develop.instances.magento-community.engineering/admin](https://i-24803-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24803-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24803-2-3-develop.instances.magento-community.engineering/admin](https://i-24803-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
The issue has been reproduced.

See attached screenshot:
![Issue 1](https://user-images.githubusercontent.com/24711761/65948068-270d9500-e457-11e9-946a-35b690003e9f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20654` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your report. 
The issue has been fixed in magento/magento2#24804 by @drpayyne in 2.3-develop branch
Related commit(s):
 - [520d8f18788abfd81d190ebd0944d2ba9b986ee5](https://github.com/magento/magento2/commit/520d8f18788abfd81d190ebd0944d2ba9b986ee5)

The fix will be available with the upcoming 2.3.4 release.
