### ISSUE TITLE
Invisible reCaptcha does not replace default captcha on forgotten password form

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#24809]
When enabling the invisible recaptcha on 2.3.2 the default magneto recaptcha is not replaced on the forgotten password form and both captchas are presented to the user.

### Preconditions (*)

1. Magento 2.3.2
2. v3 reCaptcha enabled on frontend

### Steps to reproduce (*)

1. Add api keys for v3 invisible reCaptcha
2. Enable reCaptcha on all front-end pages.

### Expected result (*)

1. Default captcha is replaced with the v3 reCaptcha on forgotten password form.

### Actual result (*)

1. Both captchas are displayed on form.
![Screenshot_2019-10-01 Forgot Your Password](https://user-images.githubusercontent.com/33320744/65962391-7b614680-e450-11e9-9a67-d50176cf5d42.png)

**Comment by BezV8** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @BezV8, here is your [Magento instance](https://i-24809-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24809-2-3-develop.instances.magento-community.engineering/admin](https://i-24809-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by BezV8** [comment]
@magento Can't verify on test instance as it does not seem to have reCaptcha module enabled.

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24809-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24809-2-3-develop.instances.magento-community.engineering/admin](https://i-24809-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21433` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bartlomiejsz** [comment]
Hi @shikhamis11, @BezV8, @magento-engcom-team 
I wanted to work on this ticket but I believe there is no issue at all. Invisible reCaptcha is not replacement for default captcha, this is just different module. If both are turned on then both appear on frontend, but it is enough to disable default captcha in **Stores -> Configuration -> Customers -> Customer Configuration -> CAPTCHA**.

Then forgot password form looks like this:
![image](https://user-images.githubusercontent.com/9566840/66082292-1d288680-e56a-11e9-9545-627a6b268406.png)

I believe this should be closed.

**Comment by BezV8** [comment]
> Hi @shikhamis11, @BezV8, @magento-engcom-team
> I wanted to work on this ticket but I believe there is no issue at all. Invisible reCaptcha is not replacement for default captcha, this is just different module. If both are turned on then both appear on frontend, but it is enough to disable default captcha in **Stores -> Configuration -> Customers -> Customer Configuration -> CAPTCHA**.
> 
> Then forgot password form looks like this:
> ![image](https://user-images.githubusercontent.com/9566840/66082292-1d288680-e56a-11e9-9545-627a6b268406.png)
> 
> I believe this should be closed.

@Bartlomiejsz If that is the case I think the official magento docs need to be updated. It clearly states in the CE2.3 [user guide](https://docs.magento.com/m2/ce/user_guide/stores/security-google-recaptcha.html) that 

> If you have the standard Magento CAPTCHA enabled, reCAPTCHA will override it. You can have both enabled on your Magento instance without issues.

 and nowhere in the guide does it say to remove the default captcha. Clearly, either the documentation is incorrect, or the module is not working correctly.

**Comment by shikhamis11** [comment]
@Bartlomiejsz I agree with @BezV8 
in devdocs it is mentioned that `If you have the standard Magento CAPTCHA enabled, reCAPTCHA will override it. You can have both enabled on your Magento instance without issues.`
It means that only one should be at a time

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21458` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vivekkumar945744** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul, here is your [Magento instance](https://i-24809-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24809-2-3-develop.instances.magento-community.engineering/admin](https://i-24809-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
FYI: @phoenix128

**Comment by sdzhepa** [comment]
Hello @BezV8 @gauravagarwal1001 
FYI: @shikhamis11 

After a couple of internal discussion and clarification with module/functionality owner, I can confirm this is a mistake on DevDocs page.
>  The two captchas are supposed to be independent implementation. If you enable both of them, you should have them both.

So, it should be fixed in the dev docs

**Comment by sdzhepa** [comment]
Devdocs has been updated : https://docs.magento.com/user-guide/stores/security-google-recaptcha.html
>For the Admin, Google reCAPTCHA can be used on the Sign In page and when a user requests a password reset. If the standard Magento CAPTCHA is also enabled, Google reCAPTCHA can be used at the same time without any problem.
