### ISSUE TITLE
Backorders fulfillment improvements

### ISSUE THREAD

**Issue by eurobeautiful** [magento/magento2#24816]
### Description (*)
The current behavior of Magento 2.3.1 when it comes to fulfilling backorders doesn't allow for efficient fulfillment, even less for scaling.

There are two areas of improvement.

1) When an order is received that contains products that are entirely or partially out of stock, it is very easy for the operator to attempt to ship the order including all products ordered. Magento throws an error "Not all of your products are available in the requested quantity". Unfortunately this error message has little value to the operator because it doesn't inform what product(s) have insufficient stock, nor the amount of that stock.

The operator's only option is to check each of the products ordered, one by one, to find out which ones are out of stock, or in insufficient stock, and then manually adjust the quantity to be shipped.

2) After the order has been partially shipped, its status remains as Processing. When viewing all orders there is no way to identify backorder orders. This creates a problem because the operator will have to be constantly checking all Processing orders just to find out that there is no products in stock available.

### Expected behavior (*)
My suggestions are the following:

1) On the "New Shipment" screen, under "Products to Ship" the table should include a column that shows the current product inventory quantity. This will a tremendous improvement for operators. Other enhancements that can be considered are: 
  a) Automatically adjust the quantity to ship for a product to equal the current inventory quantity when the current inventory is less than the order quantity, and 
  b) Use colors or labels to call attention to backorder products.

2) On the Orders list screen, add a column (and matching filter) that indicates whether any products pending to be shipped can be shipped now. I can think of 4 possible statues: 
  a) All pending products are available can be fulfilled now, 
  b) Some of the pending products can be fulfilled now, and at least one pending product is available in the full quantity ordered, 
  c) Some of the pending products can be fulfilled now, but none of the products is available in the full quantity ordered
  d) None of the pending products can be fulfilled now

### Benefits
These enhancements will greatly increase the productivity for operators handling fulfillment of backorders. This will empower them to make decisions on how to handle backorders, and be able to ship them as soon as product is back in stock.

In regards to the statuses for suggestion Nbr.2 you may wonder why having the nuanced distinction between products available in the full quantity ordered. The reason I include this is because some businesses that accept backorders need to ship all products of one type in a single shipment. If we don't provide this specific status option, this feature will not be useful to them.

**Comment by shikhamis11** [comment]
hi @eurobeautiful 
Thanks for reporting this issue . It will be processed faster if you will report it on  [Magento Community Feature](https://github.com/magento/community-features)

**Comment by eurobeautiful** [comment]
Thank you @shikhamis11 !
I have opened https://github.com/magento/community-features/issues/200

**Comment by seansan** [comment]
This is an enormously important issue. How great that you are also on this track. We are curently working out a complete closed-loop diagram to finalize the backorder process.

One of the elements is a "can I ship it now" process that check if MSI contains enough stock to ship. When an order enters the system with 1 item from MSI and 1 item in backorder, then
- the order should receive a flag contains_bo = yes (to identify but also for reporting purposes)
- a 5 min cron process monitors MSI stock: do I have enough now?
- when the backorder is received from the supplier some "Incoming MSI source" is updated .... (and the 5 min process now returns "yes: enough stock!" and marks the order as New - Canship

Let me know if you want to discuss; we are now working on a process diagram

**Comment by seansan** [comment]
Backorders really needs some attention from the M2 team! There are some bugs in 2.3.5 + because of MSI some things have changed
