### ISSUE TITLE
Error 400 Bad Request on Customer API GET /customer/me

### ISSUE THREAD

**Issue by Feyks** [magento/magento2#24812]
Trying to get a customer by id from a REST Client, I'm confused because an error is asking to send the required field "customerId". But this field was sent as a GET parameter in the URL.

### Preconditions

1. Magento 2.3.1 on docker with image alexcheng/magento2:latest
2. Advanced REST Client

### Steps to reproduce

To reproduce, we will need an admin token from the /V1/integration/admin/token with user credentials. The URL /rest/V1/ was already tested and is working for other paths.

1. Write a GET Request on URL : 
- http://{magento_host}/rest/V1/customers/me?customerId=1
2. Put following headers 
- Content-Type : application/json
- Authorization : Bearer {admin_token}

### Expected result
1. Error HTTP 200 with in the response data the customer with ID 1 in JSON format.

### Actual result
1. Error 400 Bad Request Received with following JSON
`{
"message": ""%fieldName" is required. Enter and try again.",
"parameters": {
"fieldName": "customerId"
}`

**Comment by engcom-Bravo** [comment]
Hello @Feyks. Thanks for reporting. Requests with "me" seem to be intended only to be made directly from the customer and not from admin. Would You please try this: http://{magento_host}/rest/V1/customers/1 in stead.

**Comment by Feyks** [comment]
Hello @engcom-Bravo. Thanks for your quick answer. The url you have given is working perfectly fine.
Thanks for your help.

**Comment by engcom-Bravo** [comment]
You are always welcome @Feyks.
