### ISSUE TITLE
Payment Error - "We can't place the order... ... We can't save the address: Email has a wrong format"

### ISSUE THREAD

**Issue by jclark0** [magento/magento2#24823]
### Preconditions (*)

1. Magento 2.3.2
2. Upgraded installation from 2.2.5 to 2.3.2

### Steps to reproduce (*)

1. Add cart to basket, proceed to payment
2. Attempt to complete order

### Expected result (*)

1. Success and confirmation of order

### Actual result (*)

1. Error appears "We can't place the order... ... We can't save the address: Email has a wrong format"
2. Checkout returns back to cart.
![cart error](https://user-images.githubusercontent.com/56072496/66038313-af4c7280-e509-11e9-9809-775dd5374c90.PNG)

**Comment by korostii** [comment]
Hi @jclark0 

If you could provide an example of an email address that produces such an unfortunate result for you, that would be great and would probably speed up the fix significantly.

Thanks in advance & have a nice day!

**Comment by engcom-Delta** [comment]
Hi @jclark0 thank you for your report. I am not able to reproduce issue by steps you described on clean 2.3-develop, seems like this related to your custom modules.

If you'd like to update the issue, please reopen it.
