### ISSUE TITLE
Newly initialized quote has no address which prevents totals calculating

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#24826]
### Preconditions (*)

1. Magento 2.3.2 open source

### Steps to reproduce (*)

1. Place order
2. Get quote from session and add product
3. Save quote
4. Minicart and cart has no totals calculated as product has price 0
(Custom controller doing whole thing is POST and its added to `sections.xml` so it is not about caching, in db all totals and item prices are null.)

### Expected result (*)

1. After adding product to newly created quote (and its saving) it has final price calculated, also totals are calculated

### Actual result (*)

1. Quote has no addresses, so all totals are being set as 0 and there is no totals calculations
2. In cart and minicart product has price zero and subtotals are zero, unless you click calculate cart or add some new products to cart. Then all is fine.

In fact before saving quote (which triggers totals calculation), there is one workaround:
`
if (!$quote->getId()) {
            $quote->getShippingAddress();
            $quote->getBillingAddress();
        }
`

This calls causes address to be created if not exist. Without this, there is address collection beign created, but with no items.

**Comment by engcom-Charlie** [comment]
Hello @bartoszkubicki 
I can't reproduce this issue on a fresh Magento 2.3-develop.

**Manual testing scenario:**

1. Place order
2. Get quote  and add product(via API)
3. Check all totals values in  `quote` table 
4. Go to the frontend and check values of all totals in cart & minicart

**Actual result:**
After adding product to newly created quote it has final price calculated, also totals are calculated

So i have to close this issue.
Thanks for your report!

**Comment by bartoszkubicki** [comment]
I haven't added product via api, but using `Magento\Quote\Model\Quote` method `addProduct()`, something like:

`
$product = $this->productRepository->getById($orderItem->getProductId());
$addingResult = $quote->addProduct($product, $buyRequest);
$this->cartRepository->save($quote);
`

where `$buyRequest` is built something like this:

`
$previousBuyRequest = $orderItem->getProductOptionByCode('info_buyRequest');
$qtyOrdered = $orderItem->getQtyOrdered();
$buyRequest = empty($previousBuyRequest)
? new DataObject(['product' => $product->getId(), self::QTY_PARAM => $qtyOrdered])
: new DataObject($previousBuyRequest);
$buyRequest->setData(self::QTY_PARAM, $qtyOrdered);
return $buyRequest;
`

**Comment by engcom-Charlie** [comment]
@bartoszkubicki could you add file with your all code for it?

**Comment by bartoszkubicki** [comment]
Here it is:
[ReorderItem2.txt](https://github.com/magento/magento2/files/3694781/ReorderItem2.txt)

+ custom dependency used inside
[BuyRequestReconstructor.txt](https://github.com/magento/magento2/files/3694783/BuyRequestReconstructor.txt)

**Comment by engcom-Charlie** [comment]
@bartoszkubicki i need `Vendor\ReorderItem\Api\BuyRequestReconstructorInterface` and `webapi.xml` files too i think

**Comment by bartoszkubicki** [comment]
It is just a controller, I dont have `webapi.xml`. There is interface here, its implementation is poste above:
[BuyRequestReconstructorInterface.txt](https://github.com/magento/magento2/files/3698782/BuyRequestReconstructorInterface.txt)

**Comment by engcom-Charlie** [comment]
@bartoszkubicki 
sorry but i can't run this code.
i will put the "Triage" label and some developer will test it

**Comment by bartoszkubicki** [comment]
Issue is well described [here](https://github.com/magento/magento2/issues/26209), so I close this issue.
