### ISSUE TITLE
No service contract for adding product to cart

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#24820]
### Summary (*)

There is no clean, easy way for adding product to cart. Of course if there is any, please post it. For now you can use `Magento\Quote\Model\Quote`, but it requires additional steps like saving cart etc., what is not very comfortable. `Magento\Checkout\Model\Cart` works fine but it is deprecated, so you shouldn't use it. It has also nice wrapper around adding product, which allows you to add existing order item again to the cart. 

### Proposed solution

Add service contract, which you can call without any other operations, like cart saving, collecting totals or sth and have you your product in cart. The service also should throw different exceptions in case of errors, not return string as `Quote::addProduct()` does (if there is any problem while adding to cart, you have to compare messages to know what happened).

**Comment by engcom-Bravo** [comment]
Hello @bartoszkubicki, thanks for applying. We are supposed to close such issues referring the reporter  to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion on it as this repository is intended for Magento Core technical issues only. Of course You may try to visit them and probably get an answer for Your question. But if don't get such and You really have an idea on how exactly everything should look like to produce a better performance please rewrite the description so it matches the valid format (e. g. include Preconditions, Steps to Reproduce, etc.) and add more details to it. For now, at the first glance, statements like "...requires additional steps like saving cart..." sound not clear enough. Saving cart when it is updated seems to have always been being a necessary step in Magento. It's a part of the basic logic on what should happen to the cart when it is updated. So please add more details on what You dislike in current performance (Actual Result) and how would You improve it (Expected Result). Thus we can classify this issue as a Feature Request and transfer it to the appropriate repository for futher processing. Thank You.

**Comment by bartoszkubicki** [comment]
Ok now I see I can use CartItemRepository, which while saving CartItem adds it to the cart.
