### ISSUE TITLE
Profiler loggers generation issue

### ISSUE THREAD

**Issue by sablesoft** [magento/magento2#24837]
### Preconditions

Magento version 2.3.2 in docker container

### Steps to reproduce

Set env MAGE_PROFILER=2

### Expected result

Profiler enabled and the app runs without fatal errors in the core.

### Actual result

Got fatal errors in profiler loggers generation. Example:
>Fatal error: Declaration of Magento\Framework\App\Request\PathInfo\Logger::getPathInfo(string $requestUri, string $baseUrl) must be compatible with Magento\Framework\App\Request\PathInfo::getPathInfo(string $requestUri, string $baseUrl): string in /var/www/magento/generated/code/Magento/Framework/App/Request/PathInfo/Logger.php on line 83

How can I fix it?

**Comment by sablesoft** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @sablesoft. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sablesoft, here is your [Magento instance](https://i-24837-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24837-2-3-develop.instances.magento-community.engineering/admin](https://i-24837-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sablesoft** [comment]
There seems to be an error in this method:
>Magento\Framework\ObjectManager\Profiler\Code\Generator\Logger::_getMethodInfo

The return type getting is missing here!
For comparison:
>Magento\Framework\Interception\Code\Generator\Interceptor::_getMethodInfo

Here the return type option is added.

**Comment by sablesoft** [comment]
I fixed it locally but found another issue:

Class Magento\Framework\Session\SaveHandler\Redis already has own Logger class! And this logger uses not for profiling! So app crashed again..(

**Comment by engcom-Charlie** [comment]
Hello @sablesoft 
The GitHub issue tracker is intended for Magento Core technical issues only.

Please refer to the [Doker Magento issue tracker](https://github.com/clean-docker/Magento2/issues) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

Thanks for your report!

**Comment by multipasko** [comment]
Set env MAGE_PROFILER=2 .... after that you won't be able to even run bin/magento without exceptions ... this is no docker issue but general issue

**Comment by dchaykas** [comment]
Magento 2.3.3
`Fatal error: Declaration of Magento\Framework\App\Request\PathInfo\Logger::getPathInfo(string $requestUri, string $baseUrl) must be compatible with Magento\Framework\App\Request\PathInfo::getPathInfo(string $requestUri, string $baseUrl): string in /srv/www/alberta_dev/magento/generated/code/Magento/Framework/App/Request/PathInfo/Logger.php on line 0`

Enabled profiler by setting the environment variable through HTACCESS and got the above error. Why is this issue closed @engcom-Charlie ?
