### ISSUE TITLE
Details link on CMS page or block editing goes to Dashboard

### ISSUE THREAD

**Issue by paalsoberg** [magento/magento2#2483]
![screen shot 2015-11-23 at 10 38 53](https://cloud.githubusercontent.com/assets/8167929/11334690/ab295ff2-91ce-11e5-904d-b7cc408a0bc8.png)
The details link below which can be found under the 'Select' dropdown on CMS page grid or Blocks grid directs to the Magento Admin dashboard.

This is on Magento 2.0 EE (GA)

**Comment by MomotenkoNatalia** [comment]
Hi @paalsoberg  
Thanks for reporting this issue! This is a known bug, internal ticket MAGETWO-44966

**Comment by datbunneh** [comment]
No longer relevant.
Content Page grid has a "View" link which works correctly.
Content Block grid no longer has such link.

**Comment by MomotenkoNatalia** [comment]
Issue can be closed
