### ISSUE TITLE
Issue on the customer listing page in the admin backend

### ISSUE THREAD

**Issue by amitlmitm** [magento/magento2#24839]
I want to see my  customers listing but here is this type of  error : 
Magento ver. 2.3.1 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer_grid_flat' doesn't exist, query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main_table`

For this, I have run "php bin/magento indexer: reindex" but it still showing this error. What should I do to resolve this error? 

![image](https://user-images.githubusercontent.com/31549431/66126832-f02ab100-e607-11e9-9264-98def22edfcf.png)

**Comment by amitlmitm** [comment]
@m2-assistant  

**Summary Of the issue**
I want to see my customers listing in admin backend  but here is this type of error 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.customer_grid_flat' doesn't exist, query was: SELECT COUNT(*) FROM customer_grid_flat AS main_table

And one thing more, When I run this command  "php bin/magento setup:upgrade" for deploy the content then I am getting this error in the command prompt
"SQLSTATE[42000]: Syntax error or access violation: 1070 Too many key parts specified; max 16 parts allowed, query was: CREATE TABLE IF NOT EXISTS `customer_grid_flat` (
  `entity_id` int UNSIGNED NOT NULL COMMENT 'Entity ID' ,
  `name` text NULL COMMENT 'Name' ,
  `email` varchar(255) NULL COMMENT 'Email' ,
  `group_id` int NULL COMMENT 'Group_id' ,
  `created_at` timestamp NULL default NULL COMMENT 'Created_at' ,
  `website_id` int NULL COMMENT 'Website_id' ,
  `confirmation` varchar(255) NULL COMMENT 'Confirmation' ,
  `created_in` text NULL COMMENT 'Created_in' ,
  `dob` date NULL COMMENT 'Dob' ,
  `gender` int NULL COMMENT 'Gender' ,
  `taxvat` varchar(255) NULL COMMENT 'Taxvat' ,
  `lock_expires` timestamp NULL default NULL COMMENT 'Lock_expires' ,
  `aw_ca_business_name` varchar(255) NULL COMMENT 'Aw_ca_business_name' ,
  `aw_ca_business_addr` text NULL COMMENT 'Aw_ca_business_addr' ,
  `aw_ca_reseller_permitt` varchar(255) NULL COMMENT 'Aw_ca_reseller_permitt' ,
  `aw_ca_contactnumber` varchar(255) NULL COMMENT 'Aw_ca_contactnumber' ,
  `is_approved` varchar(255) NULL COMMENT 'Is_approved' ,
  `shipping_full` text NULL COMMENT 'Shipping_full' ,
  `billing_full` text NULL COMMENT 'Billing_full' ,
  `billing_firstname` varchar(255) NULL COMMENT 'Billing_firstname' ,
  `billing_lastname` varchar(255) NULL COMMENT 'Billing_lastname' ,
  `billing_telephone` varchar(255) NULL COMMENT 'Billing_telephone' ,
  `billing_postcode` varchar(255) NULL COMMENT 'Billing_postcode' ,
  `billing_country_id` varchar(255) NULL COMMENT 'Billing_country_id' ,
  `billing_region` varchar(255) NULL COMMENT 'Billing_region' ,
  `billing_street` varchar(255) NULL COMMENT 'Billing_street' ,
  `billing_city` varchar(255) NULL COMMENT 'Billing_city' ,
  `billing_fax` varchar(255) NULL COMMENT 'Billing_fax' ,
  `billing_vat_id` varchar(255) NULL COMMENT 'Billing_vat_id' ,
  `billing_company` varchar(255) NULL COMMENT 'Billing_company' ,
  PRIMARY KEY (`entity_id`),
  INDEX `CUSTOMER_GRID_FLAT_GROUP_ID` (`group_id`),
  INDEX `CUSTOMER_GRID_FLAT_CREATED_AT` (`created_at`),
  INDEX `CUSTOMER_GRID_FLAT_WEBSITE_ID` (`website_id`),
  INDEX `CUSTOMER_GRID_FLAT_CONFIRMATION` (`confirmation`),
  INDEX `CUSTOMER_GRID_FLAT_DOB` (`dob`),
  INDEX `CUSTOMER_GRID_FLAT_GENDER` (`gender`),
  INDEX `CUSTOMER_GRID_FLAT_BILLING_COUNTRY_ID` (`billing_country_id`),
  FULLTEXT `FTI_00A063FC834DF0A41CC9D8ACF8458ECB` (`name`, `email`, `created_in`, `taxvat`, `aw_ca_business_name`, `aw_ca_business_addr`, `aw_ca_contactnumber`, `shipping_full`, `billing_full`, `billing_firstname`, `billing_lastname`, `billing_telephone`, `billing_postcode`, `billing_region`, `billing_city`, `billing_fax`, `billing_company`)
) COMMENT='customer_grid_flat' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci
"

For this, I have run "php bin/magento indexer: reindex" but it still showing this error. What should I do to resolve this error?

**Information on your environment**
   Magento ver. 2.3.1

 Steps to reproduce

 Expected and actual results

**Comment by engcom-Bravo** [comment]
Hello @amitlmitm. Thanks for applying. The GitHub issue tracker is intended for Magento Core technical issues only. The problem You are facing doesn't belong to such. So please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by scholtz** [comment]
@amitlmitm  .. For me it seems as obvious magento bug, and by the description there might be some problem with migration, fault installation, or something... 
You have not described however what has caused this error, so i agree to close this issue.. also note that there is already version 2.3.2 and version 2.3.3 comming up, so i dont understand why with magento bug reports u dont provide them full information, for example if u can replicate it on dev.

Note that I am not magento releated stuff..
