### ISSUE TITLE
Remove JS loaded through RequireJS

### ISSUE THREAD

**Issue by bramvanderholst** [magento/magento2#24830]
### Description

Due to a large amount of JS files (loaded through RequireJS) which we do not need (in our custom theme), we would like a method to remove some of these files.

This is a feature request since such functionality is not yet implemented.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21452` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrtuvn** [comment]
deps is not the way to disable js. It's will include files in all page. I think we have misunderstand here and should update content in docs
@bramvanderholst you should check this
https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/requirejs.html#requirejs-config-deps

**Comment by gabrieldagama** [comment]
Documentation was updated and the approach that was suggested previously is not valid. Closing this issue as the problem is not actual anymore.

**Comment by ericmorand** [comment]
@gabrieldagama, can you please link to the documentation that explains how to remove the default JS loaded by Magento 2? I see that the issue that @bramvanderholst  has been fixed since you closed it, but I can't find where is the documentation you are talking about.

Thanks by advance.

**Comment by gabrieldagama** [comment]
Hi @ericmorand, the issue was closed mostly because the wrong information was removed, I've transformed this issue in a feature request since such functionality is yet not possible.

Thanks for highlighting it.

**Comment by haxor211** [comment]
how do I remove datepicker.js, timepicker.js, spectrum.js, tinycolor.js and so on... are just a few examples. from magento 2? this useless code is just slowing down the site, all these scripts combined weight like 2 mb while my whole site is 3.5..

Come on who the hell thought its good idea to force everyone to use these javascripts??!?!?!?

**Comment by haxor211** [comment]
I have found temporal solution.. disabled these useless scripts and saved like 1mb.

https://community.magento.com/t5/Magento-2-x-Programming/Remove-JS-files-from-beeing-loaded-through-require-js/m-p/459560/highlight/false#M11813

**Comment by ericmorand** [comment]
@haxor211 I couldn't agree more.

**Comment by haxor211** [comment]
just found out you have to leave `repeat:         require('knockoutjs/knockout-repeat'),
        fastForEach:    require('knockoutjs/knockout-fast-foreach'),`

Uncommented in bootstrap.php otherwise your orders won't show, dont ask me why lol

**Comment by haxor211** [comment]
so the post has been removed from magento forums.. a really good way to fix your product, just remove hard questions and puff they dissapear

**Comment by mrtuvn** [comment]
@haxor211 i can feel your pain here
This should be fix since frontend magento load too much js and make site so much slow for both customer and developers

**Comment by mrtuvn** [comment]
If you want colorpicker load only the needed 
Still have PR for this Please check this
https://github.com/magento/magento2/pull/28400

**Comment by haxor211** [comment]
@mrtuvn thats great to hear, when is the patch coming out? and what is the name? 2.4.2?
tbh, all these javascripts should be loaded only when required by the "dev", for example if I want to have datepicker on site, then I load it via require or some optional magento module.. also who uses js effects (yes Im speaking about around 8js files with name effects..js) in 2020, I know not everything can be done with css, but come on...

**Comment by mrtuvn** [comment]
i'm not sure when it's merged Because core team must check compatible across entire eco-system
b2b-modules, ee-modules, ce-modules. We could miss some testcase and make code break
you can follow the PR as i mentioned in previous reply

**Comment by johncarlson21** [comment]
Is this still on Backlog? seems a bit off that this is over another year old with no movement
