### ISSUE TITLE
Go To Checkout Button Magento2 not visible

### ISSUE THREAD

**Issue by influxive** [magento/magento2#2484]
I can see any buttons to proceed on checkout
![fb15-ext-fin-0224664001447672337](https://cloud.githubusercontent.com/assets/1584501/11335362/bdf1222c-9201-11e5-97f3-036eff4d664c.jpg)

![fb15-ext-fin-0224664001447672337](https://cloud.githubusercontent.com/assets/1584501/11335346/98bbbfe4-9201-11e5-95c4-83c288a34fa0.jpg)

**Comment by ishakhsuvarov** [comment]
@influxive Thank you for reporting this.
Please check if you have enabled `Enable Onepage Checkout` in you admin dashboard? (Stores > Configuration > Sales > Checkout).
