### ISSUE TITLE
Issue with admin configuration permission after create a user role

### ISSUE THREAD

**Issue by vivekkumar945744** [magento/magento2#24841]
### Preconditions (*)
1. Magento Community 2.2.9

### Steps to reproduce (*)

1. System > Permission > User Roles
2. Create a user role "testrole" with resource "Edit Category Design" and "Catalog Section"
3. Create a new user with that "testrole" role.
4. Login with that new user
5. Open catalog configuration using that: Store->Configuration

### Expected result (*)

1. After 5 step admin configuration page should be open

### Actual result (*)

1. After 5th step catalog category page will be open

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24841-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24841-2-3-develop.instances.magento-community.engineering/admin](https://i-24841-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @vivekkumar-webkul. Thanks for reporting. Here's what we've got trying to reproduce Your issue on the latest develop version.
![configuration](https://user-images.githubusercontent.com/51680745/66132327-8907ff00-e5fd-11e9-9c7a-4cdf196e73fc.png)
Seems everything works correctly. Could You please try to reproduce the issue on that version too as You are asked above in the [comment](https://github.com/magento/magento2/issues/24841#issuecomment-537941225)
Thank You.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-24841-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24841-2-3-develop.instances.magento-community.engineering/admin](https://i-24841-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Unable to regenerate the issue in 2.3-develop branch
