### ISSUE TITLE
Conflicting file paths

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#24846]
### Preconditions (*)

Conflicting paths:
```shell
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/AssertStoreFrontPasswordAutocompleteOffActionGroup.xml'
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/AssertStorefrontPasswordAutocompleteOffActionGroup.xml'
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/StoreFrontClickSignInButtonActionGroup.xml'
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/StorefrontClickSignInButtonActionGroup.xml'
```

### Steps to reproduce (*)

1. clone magento2 on macOS or another system with case-insensitive filenames
2. check the output

### Expected result (*)

1. No problems

### Actual result (*)

Conflicts due to same file names but different cases:
```shell
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/AssertStoreFrontPasswordAutocompleteOffActionGroup.xml'
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/AssertStorefrontPasswordAutocompleteOffActionGroup.xml'
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/StoreFrontClickSignInButtonActionGroup.xml'
  'app/code/Magento/Customer/Test/Mftf/ActionGroup/StorefrontClickSignInButtonActionGroup.xml'
```

**Comment by engcom-Charlie** [comment]
Hello @DanielRuf
Could you add any steps to reproduce this issue? 
At what stage is the conflict displayed?

**Comment by DanielRuf** [comment]
> Could you add any steps to reproduce this issue?

It happens on `git clone` on macOS at the very end.

**Comment by pa7751** [comment]
@magento-engcom-team give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @pa7751. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @pa7751, here is your [Magento instance](https://i-24846-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24846-2-3-2.instances.magento-community.engineering/admin](https://i-24846-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
The testinstance does not help here ;-)

In general there should not be any files with the same filename but different cases. This can break on many systems and produce other issues.

**Comment by DanielRuf** [comment]
Please simply rename the files.
```
StorefrontClickSignInButtonActionGroup.xml
StoreFrontClickSignInButtonActionGroup.xml
```

and

```
AssertStoreFrontPasswordAutocompleteOffActionGroup.xml
AssertStorefrontPasswordAutocompleteOffActionGroup.xml
```

**Comment by DanielRuf** [comment]
I'm currently on it.

**Comment by DanielRuf** [comment]
Will be fixed by https://github.com/magento/magento2/pull/24856

**Comment by engcom-Charlie** [comment]
I often clone magento 2 but have never seen a similar problem. 
There are no files specified in the `magento / magento2 `repository(
```
AssertStoreFrontPasswordAutocompleteOffActionGroup.xml
StoreFrontClickSignInButtonActionGroup.xml
``` 
).

It only has files with a small letter `f`:

https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/Test/Mftf/ActionGroup/AssertStorefrontPasswordAutocompleteOffActionGroup.xml
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/Test/Mftf/ActionGroup/StorefrontClickSignInButtonActionGroup.xml

So i can't reproduce this issue. 
![image](https://user-images.githubusercontent.com/51680850/66197549-4436a380-e6a3-11e9-8fac-58267acc810b.png)
I tried simply rename the files and i had no problems. 

This issue should be closed.
Thanks for your report!

**Comment by DanielRuf** [comment]
It was probably renamed and Git checked out the old and new version. That happened on a new clone.

I did a fresh clone today and both files appear there.

**Comment by DanielRuf** [comment]
You can verify this on Linux.

**Comment by hostep** [comment]
Hmm, @DanielRuf, Issue doesn't seem to be correct, I only notice one of those files in the git repo, have you checked [Github's rendering of that directory](https://github.com/magento/magento2/tree/2.3-develop/app/code/Magento/Customer/Test/Mftf/ActionGroup)?

I'm running a case sensitive file system on my macOS (as every web developer should do if they target linux machines in my opinion), and I'm only seeing a single file in a clone of this git repo.

*5 minutes later*: Aha, found it, you are probably using a not very up2date clone of the repo? Because those two files already got removed a while ago in https://github.com/magento/magento2/pull/21647

We should probably close this issue and your PR?

**Comment by DanielRuf** [comment]
I have done a simple clone on my macBook. It depends on your file system. See the PR. It is definitely there.

**Comment by DanielRuf** [comment]
The message that there are conflicting file paths with the list of these 4 files was output by Git at the initial clone.

**Comment by DanielRuf** [comment]
I had directly cloned from the latest version of magento/magento2.

**Comment by DanielRuf** [comment]
Hm, that is weird. I guess the issue is that it is still in the Git log.

Anyways, let's close it. Thanks for checking this.
