### ISSUE TITLE
Unable to delete custom option file in admin order create

### ISSUE THREAD

**Issue by adrian-martinez-interactiv4** [magento/magento2#24842]
Unable to delete custom option file in admin order create due to js error. See steps to reproduce and actual and expected results for further information.

### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Have a product with at least one custom option of type file as follows:

<img width="1333" alt="Captura de pantalla 2019-10-03 a las 15 26 08" src="https://user-images.githubusercontent.com/17545750/66131018-fa8e8000-e5f2-11e9-95b8-c4a2b6800552.png">

2. Go to Sales -> Orders, click Create New Order button
3. Select or create a customer, and proceed to order creation.
4. Select customizable product to be added to quote.
5. Configure it with a file, in this case is an image called test.png:

<img width="875" alt="Captura de pantalla 2019-10-03 a las 15 27 09" src="https://user-images.githubusercontent.com/17545750/66131319-81dbf380-e5f3-11e9-9f00-b2035ee2b431.png">

6. Click Ok, image gets uploaded and attached to custom option successfully.
7. Click on Configure button in item row again, in order to try to delete the just uploaded file:

<img width="429" alt="Captura de pantalla 2019-10-03 a las 15 36 49" src="https://user-images.githubusercontent.com/17545750/66131455-bea7ea80-e5f3-11e9-9003-5dd2e925b49b.png">

8. In configure sidebar, click on Delete checkbox, next to the file input.

### Expected result (*)

1. File name gets strikethrough, no js errors:

<img width="827" alt="Captura de pantalla 2019-10-03 a las 15 28 43" src="https://user-images.githubusercontent.com/17545750/66131702-3118ca80-e5f4-11e9-99d1-ba745c350dce.png">

2. When Ok clicked, and reopened through Configure button, I expect no file to be there:

<img width="510" alt="Captura de pantalla 2019-10-03 a las 15 41 57" src="https://user-images.githubusercontent.com/17545750/66131810-5c031e80-e5f4-11e9-9bef-398f34db9c85.png">

### Actual result (*)

1. Js error due to bad selector, that avoids to prepare fields for submit, so file does not get removed:

<img width="822" alt="Captura de pantalla 2019-10-03 a las 15 27 48" src="https://user-images.githubusercontent.com/17545750/66131890-7c32dd80-e5f4-11e9-96cf-c8087ea86bf0.png">

**Comment by adrian-martinez-interactiv4** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @adrian-martinez-interactiv4. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @adrian-martinez-interactiv4, here is your [Magento instance](https://i-24842-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24842-2-3-develop.instances.magento-community.engineering/admin](https://i-24842-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by adrian-martinez-interactiv4** [comment]
> @adrian-martinez-interactiv4 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

<img width="825" alt="Captura de pantalla 2019-10-03 a las 15 52 02" src="https://user-images.githubusercontent.com/17545750/66132813-f021b580-e5f5-11e9-974a-59e695e55fb1.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21498` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @adrian-martinez-interactiv4. Thank you for your report. 
The issue has been fixed in magento/magento2#24843 by @adrian-martinez-interactiv4 in 2.4-develop branch
Related commit(s):
 - [504dd9144be469897baf834e58ae057537a07288](https://github.com/magento/magento2/commit/504dd9144be469897baf834e58ae057537a07288)
 - [3eb4110c2b5d37df4a9d155d6dfe73042424b1c0](https://github.com/magento/magento2/commit/3eb4110c2b5d37df4a9d155d6dfe73042424b1c0)
 - [6e4a0410ada941c681310f480c788ed4b309b11b](https://github.com/magento/magento2/commit/6e4a0410ada941c681310f480c788ed4b309b11b)

The fix will be available with the upcoming 2.4.0 release.
