### ISSUE TITLE
Drop down icon invisible for a moment if not select value and click on Load Template

### ISSUE THREAD

**Issue by hasim32** [magento/magento2#24840]
### Preconditions (*)
M 2.3

### Steps to reproduce (*)
1. admin - email template - add new template
2. without select template click on Load Template

### Expected result (*)
drop down icon should be visible when click on Load Template

### Actual result (*)
![image](https://user-images.githubusercontent.com/56119534/66127383-23ba0b00-e609-11e9-8635-96680f71905c.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24840-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24840-2-3-develop.instances.magento-community.engineering/admin](https://i-24840-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21460` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [Magento instance](https://i-24840-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24840-2-3-develop.instances.magento-community.engineering/admin](https://i-24840-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by drpayyne** [comment]
Reopening this issue as using the `!important` from this linked PR has caused [another issue](https://github.com/magento/adobe-stock-integration/pull/715) to have to use `!important` too as the only way to override that style. Assigning myself and will submit a PR to revert this change and submit a better fix.

CC: @sivaschenko

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @drpayyne 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21460` were created

**Issue Available**: @drpayyne, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment]
Working on this now.

**Comment by VladimirZaets** [comment]
Hi @hasim32. Thank you for your report. 
The issue has been fixed in magento/magento2#25629 by @drpayyne in 2.3-develop branch
Related commit(s):
 - [16aabf76e99e00ba58ea133e4c140698acc17f17](https://github.com/magento/magento2/commit/16aabf76e99e00ba58ea133e4c140698acc17f17)

The fix will be available with the upcoming 2.3.5 release.

**Comment by drpayyne** [comment]
Hi @VladimirZaets, this PR: https://github.com/magento/magento2/pull/25629 doesn't have the fix. As it is mentioned in the description, it only reverts the PR which was already submitted for this issue. The fix is in progress.

**Comment by magento-engcom-team** [comment]
@drpayyne Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @drpayyne 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29036` were created

**Issue Available**: @drpayyne, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hasim32. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-29036` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @hasim32. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24865` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
