### ISSUE TITLE
Authorize.net Transaction Fails From Admin Order

### ISSUE THREAD

**Issue by touqeer-verve** [magento/magento2#24844]
### Description of the issue(*)
We successfully create order from frontend with Authorized.net in Magento 2.3.1, but when trying to place an order from admin, i showing me Transaction declined.

### Preconditions (*)

1. Magneto CE 2.3.1 is installed
2. Authorize.net (a new method, not the direct post) is configured correctly (Production mode). Enable debugging.

### Steps to reproduce (*)

1. Add item in the backend admin order.
2. Enter the billing address.
3. Enter the shipping address and shipping type
4. Enter card details
5. Submit order

### Expected result (*)

1. Order Should be successfully placed.

### Actual result (*)
I am getting the following error when placing an order from admin using authorized.net payment method on 2.3.1
'response' => '{"transactionResponse":{"SupplementalDataQualificationIndicator":0},"messages":{"resultCode":"Error","message":[{"code":"E00076","text":"dataDescriptor contains invalid value."},{"code":"E00076","text":"dataValue contains invalid value."}]}}

**Comment by touqeer-verve** [comment]
@magento-engcom-team  send me 2.3-develop instance credentials.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24844-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24844-2-3-develop.instances.magento-community.engineering/admin](https://i-24844-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@touqeer-verve  - It is displaying an error like "Transaction has been declined. Please try again later."
See attached the video:

![OrderFailed_Issue](https://user-images.githubusercontent.com/24711761/66181917-54915300-e690-11e9-919e-e208de1da254.gif)

Please update me on anyone who is fixed the issue Or update me on which issue is found placed order using the Authorize.net payment method.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21497` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by artursson** [comment]
**Additional info: (Magento 2.3.3 instance)**

The issue reproduces if only 1 Payment Method (new Authorize.Net module) is enabled (available for Order Creating in Admin Panel).

**Error:**

> Transaction has been declined. Please try again later.

**Comment by travish** [comment]
Reproduced on `2.3.1`

It should be noted that the `payment.log` contains empty values for `dataDescriptor` and `dataValue`:

```
array (
        'opaqueData' => 
        array (
          'dataDescriptor' => '',
          'dataValue' => '',
        ),
      ),
```

Looks like the missing value comes from `vendor/magento/module-authorizenet-acceptjs/view/adminhtml/templates/form/cc.phtml`

**Comment by tinchodev** [comment]
So.. I think I'm seeing the problem.
When the AuthorizeJS CC form is loaded via AJAX `new AuthorizenetAcceptjs(config);` instanciation at `vendor/magento/module-authorizenet-acceptjs/view/adminhtml/templates/payment/script.phtml` does not happens, leaving `opaqueDataDescriptor` and `opaqueDataValue` form hidden fields blank.
If the page refreshes, all will be good since form will be loaded on DOM Ready, so the seccond time it will work.

I had this worked around the follwing way :

For `vendor/magento/module-authorizenet-acceptjs/view/adminhtml/templates/payment/script.phtml`

Added the follwing lines the bottom :

```
<script>
    //<![CDATA[
    require(
        ['jquery'], function ($) {
            $(document).trigger('payment_form_<?= /* @noEscape */ $code ?>_loaded');
        });
    //]]>
</script>
```

-------------------------

For `vendor/magento/module-authorizenet-acceptjs/view/adminhtml/templates/payment/script.phtml`

I've replaced :

```
<script>
    //<![CDATA[
    require(
        [
            'Magento_AuthorizenetAcceptjs/js/authorizenet',
            'jquery',
            'domReady!'
        ], function(AuthorizenetAcceptjs, $) {
            var config = <?= /* @noEscape */ $block->getPaymentConfig() ?>,
                form = $('#payment_form_<?= /* @noEscape */ $block->escapeJs($block->escapeHtml($block->getMethodCode())) ?>');

            config.active = form.length > 0 && !form.is(':hidden');
            new AuthorizenetAcceptjs(config);
        });
    //]]>
</script>
```

with :

```
<script>
    //<![CDATA[
    require(
        [
            'Magento_AuthorizenetAcceptjs/js/authorizenet',
            'jquery',
            'domReady!'
        ], function (AuthorizenetAcceptjs, $) {
            let formId = 'payment_form_<?= /* @noEscape */ $block->escapeJs($block->escapeHtml($block->getMethodCode())) ?>';
            $(document).on(formId+'_loaded', function () {
                let config = <?= /* @noEscape */ $block->getPaymentConfig() ?>;
                let authorizeForm = $('#'+formId);
                config.active = authorizeForm.length > 0 && !authorizeForm.is(':hidden');
                new AuthorizenetAcceptjs(config);
            });
        });
    //]]>
</script>
```
If this is good enough, I'll create a PR to Magento_AuthorizenetAcceptjs repo, un fortunatelly I was not able fo find it.

Hope it helps.

**Comment by ihor-sviziev** [comment]
Hi @touqeer-verve ,
According to following announcement this extension was already removed from 2.4 version:
https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445

All future collaboration related to this extension should be on Marketplace using "Contacts" or "Bug reports" related to this extension.

I'm closing this issue.
