### ISSUE TITLE
The registration page is not showing thankyou message

### ISSUE THREAD

**Issue by shikharbhatnaggar** [magento/magento2#24863]
While customer register and form get submitted but not showing the page with thank you message. It shows only a blank white screen. However it is sending the confirmation email to customer on their email ID.

One can replicate the issue @ my website i. e. awscales.com

Environment:
Ubuntu v16.04.4
Magento 2.2.4

Anyone please help and support.

**Comment by krishprakash** [comment]
Hi @shikharbhatnagar
It's works fine in venilla Magento instance
GitHub issue tracker is intended for magento core issues only.
Please ask query at Magento forum or Magento stack exchange.
Thanks
