### ISSUE TITLE
magento2.3.2: Decrease stock qty and salable on invoice generate now

### ISSUE THREAD

**Issue by irshad-iflair** [magento/magento2#24869]
### Summary (*)
but the issue  is while generating invoice  salable quantity  decreases twice

**Comment by krishprakash** [comment]
Hi @irshad-iflair. 
Please explain the issue with proper reproducible steps.
Also follow issue reporting guidelines.
Thanks

**Comment by krishprakash** [comment]
Hi @irshad-iflair.
Feel free to reopen this issue with all reproducible steps.
Thanks.

**Comment by irshad-iflair** [comment]
To decrease of stock quantity on invoice-generate,  I created an event observer below. but the issue is stock quantity decrease twice while generating an invoice.

1> Ahmad/Extension/etc/adminhtml/event.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
       <event name="sales_order_invoice_save_after">
         <observer name="Ahmad_sales_order_invoice_save_after" instance="Ahmad\Extension\Observer\UpdateInventory"/>
       </event>
</config>

2> Ahmad/Extension/Observer/UpdateInventory.php
<?php
namespace Ahmad\Extension\Observer;
use Magento\CatalogInventory\Api\StockStateInterface; //added line 
use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\Event\Observer;
use Magento\CatalogInventory\Api\StockRegistryInterface;
use Magento\Catalog\Model\ProductRepository;
class UpdateInventory implements ObserverInterface
{
	protected $productRepository;
	protected $stockRegistry;
	public function __construct(
	ProductRepository $productRepository,
	StockRegistryInterface $stockRegistry
	)
	{
	$this->productRepository = $productRepository;
	$this->stockRegistry = $stockRegistry;
	}
	public function execute(Observer $observer)
	{
        try{ 
			
			$invoice = $observer->getEvent()->getInvoice();
                    $invoiceItems = $invoice->getAllItems();
                    foreach ($invoiceItems as $item) 
                    {
                    	
                    	//echo "<pre>"; print_r($item->debug()); die("dead");
                        $productId = $item->getProductId();
                        $product = $this->productRepository->getById($productId);
                        $sku = $product->getSku();
                        $stockItem = $this->stockRegistry->getStockItemBySku($sku);
                        $qty = $stockItem->getQty() - $item->getQty();
                        $stockItem->setQty($qty);
                        $stockItem->setIsInStock((bool)$qty);
                        $this->stockRegistry->updateStockItemBySku($sku, $stockItem);
                    }
		}   catch (\Exception $e) 
			{
			return $e->getMessage();
			}
	}
}

**Comment by irshad-iflair** [comment]
To decrease of stock quantity on invoice-generate,  I created an event observer below. but the issue is stock quantity decrease twice while generating an invoice.

1> Ahmad/Extension/etc/adminhtml/event.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
       <event name="sales_order_invoice_save_after">
         <observer name="Ahmad_sales_order_invoice_save_after" instance="Ahmad\Extension\Observer\UpdateInventory"/>
       </event>
</config>

2> Ahmad/Extension/Observer/UpdateInventory.php
<?php
namespace Ahmad\Extension\Observer;
use Magento\CatalogInventory\Api\StockStateInterface; //added line 
use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\Event\Observer;
use Magento\CatalogInventory\Api\StockRegistryInterface;
use Magento\Catalog\Model\ProductRepository;
class UpdateInventory implements ObserverInterface
{
	protected $productRepository;
	protected $stockRegistry;
	public function __construct(
	ProductRepository $productRepository,
	StockRegistryInterface $stockRegistry
	)
	{
	$this->productRepository = $productRepository;
	$this->stockRegistry = $stockRegistry;
	}
	public function execute(Observer $observer)
	{
        try{ 
			
			$invoice = $observer->getEvent()->getInvoice();
                    $invoiceItems = $invoice->getAllItems();
                    foreach ($invoiceItems as $item) 
                    {
                    	
                    	//echo "<pre>"; print_r($item->debug()); die("dead");
                        $productId = $item->getProductId();
                        $product = $this->productRepository->getById($productId);
                        $sku = $product->getSku();
                        $stockItem = $this->stockRegistry->getStockItemBySku($sku);
                        $qty = $stockItem->getQty() - $item->getQty();
                        $stockItem->setQty($qty);
                        $stockItem->setIsInStock((bool)$qty);
                        $this->stockRegistry->updateStockItemBySku($sku, $stockItem);
                    }
		}   catch (\Exception $e) 
			{
			return $e->getMessage();
			}
	}
}

**Comment by irshad-iflair** [comment]
To decrease of stock quantity on invoice-generate,  I created an event observer below. but the issue is stock quantity decrease twice while generating an invoice.

1> Ahmad/Extension/etc/adminhtml/event.xml
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
       <event name="sales_order_invoice_save_after">
         <observer name="Ahmad_sales_order_invoice_save_after" instance="Ahmad\Extension\Observer\UpdateInventory"/>
       </event>
</config>`

2> Ahmad/Extension/Observer/UpdateInventory.php
`<?php
namespace Ahmad\Extension\Observer;
use Magento\CatalogInventory\Api\StockStateInterface; //added line 
use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\Event\Observer;
use Magento\CatalogInventory\Api\StockRegistryInterface;
use Magento\Catalog\Model\ProductRepository;
class UpdateInventory implements ObserverInterface
{
	protected $productRepository;
	protected $stockRegistry;
	public function __construct(
	ProductRepository $productRepository,
	StockRegistryInterface $stockRegistry
	)
	{
	$this->productRepository = $productRepository;
	$this->stockRegistry = $stockRegistry;
	}
	public function execute(Observer $observer)
	{
        try{ 
			
			$invoice = $observer->getEvent()->getInvoice();
                    $invoiceItems = $invoice->getAllItems();
                    foreach ($invoiceItems as $item) 
                    {
                    	
                    	//echo "<pre>"; print_r($item->debug()); die("dead");
                        $productId = $item->getProductId();
                        $product = $this->productRepository->getById($productId);
                        $sku = $product->getSku();
                        $stockItem = $this->stockRegistry->getStockItemBySku($sku);
                        $qty = $stockItem->getQty() - $item->getQty();
                        $stockItem->setQty($qty);
                        $stockItem->setIsInStock((bool)$qty);
                        $this->stockRegistry->updateStockItemBySku($sku, $stockItem);
                    }
		}   catch (\Exception $e) 
			{
			return $e->getMessage();
			}
	}
}
`

**Comment by jpkileaf** [comment]
@irshad-iflair  got any solution?
