### ISSUE TITLE
Magento isn't charging shipping fees

### ISSUE THREAD

**Issue by shkaib** [magento/magento2#24879]
Hello guys

I'm facing an issue with my website. I've setup a shipping fees to a specific country. when someone from that country place the order, sometimes when a he select multiple products, website charging a shipping fees normally. but when there is only 1 product (doesn't matter how much qty) website isn't charging shipping fees.

I've set BD 10 shipping charges on this country. remaining no shipment fees required.

I can not understand the issue. Please guide how can I fix it.

Thanks

**Comment by engcom-Bravo** [comment]
Hello @shkaib. Please reformat Your description so it has a valid format, i.e includes Preconditions, Steps to Reproduce, Expected Result and Actual Result. We need to know the exact steps You've taken in order to get what You have. Thank You.

**Comment by engcom-Bravo** [comment]
Hi @shkaib.  The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
