### ISSUE TITLE
Small typo 'Magneto' in new Google Shopping Ads module (Magento 2.3.3)

### ISSUE THREAD

**Issue by hostep** [magento/magento2#24876]
### Preconditions (*)
1. Access to Magento 2.3.3 (will be publicly available on 8 October 2019)

### Steps to reproduce (*)
1. Setup vanilla Magento 2.3.3 installation (which comes with `magento/google-shopping-ads` version 3.0.1)
2. In the backend, go to Marketing > Advertising Channels > Google Shopping ads
3. Look at the popup

### Expected result (*)
1. No typo 'Magneto', should be 'Magento'

### Actual result (*)
1. Seeing a typo 'Magneto'.

<img width="730" alt="Screenshot 2019-10-06 at 09 26 46" src="https://user-images.githubusercontent.com/85479/66265763-f4c7b300-e81b-11e9-9f6e-4e20946d6f68.png">

### Discussion
I can't seem to find the source code for this module publicly available, I only find this extension on [the Marketplace](https://marketplace.magento.com/magento-google-shopping-ads.html), so if this issue is opened in the wrong place let me know.
Having access to the source code would allow us to send in PR's for these little problems btw 🙂

Ow btw: this popup is highly annoying, since you can't close it and therefore can't access anything else in the backend of Magento, so you need to change the url manually before you can access anything in the backend, which is not really user friendly. <del>If I need to create a separate issue for this, let me know.</del> Was created #24944

**Comment by YevheniiKR** [comment]
@magento i am working on it

**Comment by YevheniiKR** [comment]
@magento i am working on it

**Comment by YevheniiKR** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @YevheniiKR. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @YevheniiKR, here is your [Magento instance](https://i-24876-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24876-2-3-develop.instances.magento-community.engineering/admin](https://i-24876-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by YevheniiKR** [comment]
can not find menu Advertising Channels. Investigeting now

**Comment by hostep** [comment]
@YevheniiKR, It's not available yet. And I don't know if it even will be available after 2.3.3 gets released, probably because this is yet another "open source but not publicly available extension brought to you by some Magento partner we don't know anything about".

**Comment by engcom-Bravo** [comment]
Hello @hostep. Thanks for reporting. I think we better wait yet for a day. Theoretically, tomorrow we shall see whether this feature is a part of vanilla package or not and so considering that we will see what to do next with it.

**Comment by Den4ik** [comment]
Also found typos at
[CreateTest.php](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Braintree/Controller/Adminhtml/Invoice/CreateTest.php#L65)
and
[Magento Composer Installer](https://github.com/magento/magento-composer-installer/blob/master/README.md)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21649` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment]
Just FYI: @swetacedcoss created an issue for the not-being-able-to-close-the-popup-bug: https://github.com/magento/magento2/issues/24944

**Comment by sdzhepa** [comment]
Hello @hostep , @sadeeshmca 

I received an update on this issue from the internal team a couple of minutes ago.

> the fix for the typo has been deployed
> Google shopping is a react app and users should see the change in a few minutes

To be sure before closing the issue, may I ask you to confirm it?

**Comment by hostep** [comment]
@sdzhepa: yes confirmed, the typo has been fixed, thanks!

<img width="724" alt="Screenshot 2019-10-09 at 22 26 24" src="https://user-images.githubusercontent.com/85479/66517687-deec1380-eae3-11e9-90c1-5bdb5d441222.png">
