### ISSUE TITLE
Installation of enterprise via composer

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#2488]
Hi,

Is it possible at all to install enterprise via composer like it is possible community edition? In an ideal world I would have my own enterprise 2 ee github repo, and use composer to bring that down in to my own individual repos for different websites.

You can bring ce down via composer now, but I am unsure how do this easily for ee.

I have tried doing the following:

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition magento2ee
```

But I get:

```
  [InvalidArgumentException]                                                        
  Could not find package magento/project-enterprise-edition with stability stable
```

I created my auth keys as per the documentation

**Comment by marvincaspar** [comment]
+1

**Comment by alankent** [comment]
That is definitely the plan - I just need to check if we have the access control lists all set up correctly to grant EE access to the right people. The current repo is not the final experience with extensions etc - there should be no external difference when we do swap over to the "real final repo with extensions" - but there will be lots of "stuff" going on behind the scenes to make sure we have EE exposed correctly.

**Comment by alankent** [comment]
Steve (tech docs) pointed me at http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html#integrator-first-composer-ee - the delay may be in getting the right access control lists available. If you don't have access to EE and you think you should, you can either wait for a bit it see if it gets fixed behind the scenes shortly, or drop me a message and I will chase internally to make sure you were not listed. I don't think the internal effort has finished here yet, but it is under way.

**Comment by ghost** [comment]
@craigcarnell @mc388 Please open a Support issue and they will get you access.

**Comment by cscd98** [comment]
@xcomSteveJohnson It's working for me now thanks. But how it is intended to be used?

For my individual site, should use this to setup my base install, or should i use it to create my own magento2ee repo, that I could then use as a private composer package and then use composer to pull down from that into separate installs?

Or would I be better just installing the official zip and unziipping into my own repo, and pulling down from that into my projects using composer.. I can't simply create a private clone of magento 2 ee (including ce and ee files) in one go!

**Comment by alankent** [comment]
Hi @craigcarnell - sorry, I don't quite follow what you are asking. EE is a set of additional modules available via composer. I am not sure why you are talking about copying our repository (and whether you mean GIT or Composer).  My gut reaction is to keep using our Composer repository so you see patches immediately when released. I would also point you at Toran proxy (from the guy who built Composer) which acts as a local cache for speed (and financially supports the Composer developer). I have heard good things about it. That acts as a cache instead of you manually maintaining a copy of our Composer repository.

If you are talking about what to commit into a local GIT repository (e.g. whether to include the 'vendor' directory or not, where the EE modules will be installed), I have heard of two camps - "commit it all" and "exclude 'vendor' because it is official stuff". Both have pros and cons. (I personally prefer "commit it all" because I am paranoid - I like having all the files exactly under control.)

But I would also say we have ideas and plans, but are very interested in real world experiences around what works well and what does not in practice. So if you try something and it does not work, I would love to hear about that as well as advice for others to learn from as well.

**Comment by cscd98** [comment]
@alankent I think I have a solution that works here, but due to packages.firegento.com not working properly at the moment so I can't test it. I'll explain the problem it fixes.. if it works.

**Comment by cscd98** [comment]
@alankent It's working again now..

Basically I would like to:
create a repository
import Magento 2 EE using composer magento/project-enterprise-edition

This works fine so far.

Then in another repository:
create a new repository
use composer to pull down the content of mycompany/project-enterprise-edition

This allows me to not have to:
give out keys to developers and manage via github account settings instead
not have to mess with keys when deploying via jenkins
have a single copy of Magento 2 EE which I can update and then get the other repo's to pull down updates when required.
from the 2nd repo completely remove all core files from the individual repo and they can be gitignored. This keeps that repo down to modules, themes etc.
have a copy of the source in case your package goes down

I was able to recently get this working using magento core composer installer (but it's v1 only).

But when I try with M2 I get:

```
  Problem 1
    - Installation request for magento/project-enterprise-edition 2.0.0 -> satisfiable by magento/project-enterprise-edition[2.0.0].
    - magento/project-enterprise-edition 2.0.0 requires magento/product-enterprise-edition 2.0.0 -> no matching package found.
```

I'm not sure if I'm making this more complicated than it needs to be and I should just make each repo use magento/project-enterprise-edition instead of mycompany/project-enterprise-edition....

**Comment by cscd98** [comment]
@alankent Is there anyway when running the composer installer to have an option to omit core magento files (i.e. automatically adding to gitignore?)

The CE project has a gitignore, but the EE does not

**Comment by cscd98** [comment]
@alankent Also after trying it this morning the following error appears after:

composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition myproject

```
Writing lock file
Generating autoload files



  [ErrorException]                                                                                                   
  file_get_contents(app/etc/NonComposerComponentRegistration.php): failed to open stream: No such file or directory  



create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

**Comment by cscd98** [comment]
https://github.com/magento/magento2-community-edition/issues/15

**Comment by daim2k5** [comment]
as @craigcarnell mentioned 

Temporary workaround: downgrade Composer to lower version. Verified with the following version:
`composer self-update 1.0.0-alpha11`

**Comment by davidalger** [comment]
@craigcarnell The issue with composer noted at magento/magento2-community-edition#15 has been resolved in the latest version. Are you all set and ok with closing this issue?

**Comment by alankent** [comment]
Hi @craigcarnell. It sounds like you don't want to give developers access to the download keys - is there a reason why? The download keys cannot be used to make purchases, just download from our Composer repo.

If I understand, I think you are doing a combination of of GIT repo to share EE files with the developers and Composer to download some extensions (not EE). You can use command line composer commands to download from multiple repos. The built in support (in web install wizard) only supports one repo at present, as we want (in the future) to encourage base Merchants to download everything from one trusted repo (ours) where we have run various checks to improve quality and security, but with the command line you have full Composer capabilities as per normal.

At the moment I cannot see a use case that I think Magento needs to be extended to support. It sounds like there was a problem that was fixed. It is a pain until we have the full repo up with extensions - we are working hard on getting that out ASAP! If I understand however you have got your configuration worked out now? We are not likely to add support for automatically adding EE modules to .gitignore files or similar - you could write a shell script maybe to do that to encode the business rules you want.

Thanks!
Alan

**Comment by mwr** [comment]
composer create works with the latest composer version as @davidalger mentioned here https://github.com/magento/magento2-community-edition/issues/15#issuecomment-159972709
