### ISSUE TITLE
Facebook Shop Integration - Magento

### ISSUE THREAD

**Issue by RoshanMandrawalia** [magento/magento2#24893]
### Summary (*)

Hello, 

My facebook shop is showing products with blank images. How can I only show products with images?
How facebook shop is linked to magento?

### Examples (*)

My facebook shop shows product with magento logo watermarked blank images. The products are fetched from magento shop and displayed on facebook page.

**Comment by krishprakash** [comment]
Hi @RoshanMandrawalia. 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Thank You.
