### ISSUE TITLE
Change Password Link not Working 

### ISSUE THREAD

**Issue by rishabhchd19** [magento/magento2#24909]
### Preconditions (*)

1. Magento CE 2.3.2

### Steps to reproduce (*)

1. Change Password Forceful to Recommend in Store>Configuration
2. The Dashboard on log in the Admin, shows Reminder to 

> It's time to change your password.

 as a recommendation.

### Expected result (*)

1. Once the reminder is clicked, it must not be visible again on every login.
2. On Click the **CHANGE YOUR PASSWORD**, the Password change Page must be opened.

### Actual result (*)

1. On click Change Your Password, Page doesn't link to Reset Password Page.
2. It redirects to Dashboard and reloads the Dashboard Again

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-24909-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24909-2-3-develop.instances.magento-community.engineering/admin](https://i-24909-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
