### ISSUE TITLE
.htaccess not supported Apache 2.4

### ISSUE THREAD

**Issue by chrom** [magento/magento2#2490]
I have error with current htaccess:

[Mon Nov 23 18:07:23.430040 2015] [core:alert] [pid 30870] [client 127.0.0.1:52194] mage2/.htaccess: Invalid command 'order', perhaps misspelled or defined by a module not included in the server configuration

order not used in apache 2.4

**Comment by shiftedreality** [comment]
Hi @chrom 

Current problem was described in Apache 2.4 upgrading doc. Section "Common problems when upgrading" says:

> Invalid command 'Require', perhaps misspelled or defined by a module not included in the server configuration, or Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration - load module mod_access_compat, or update configuration to 2.4 authorization directives.

Did this helped to resolve your problem?

**Comment by chrom** [comment]
Tomorrow I will try.

**Comment by chrom** [comment]
Yes all work.

**Comment by victorgugo** [comment]
Closed as resolved
