### ISSUE TITLE
Media image data isn't deleted from store scope view when "Use default values" is checked

### ISSUE THREAD

**Issue by arendarenko** [magento/magento2#24916]
### Preconditions (*)

1. Magento CE 2.3.2

### Steps to reproduce (*)

1. Create multiple website store (for example: **"default"** and **"canada"**)
2. Create new Media Image attribute **"example_image"** for product and "Store view" scope and assign it to **"Default"** product attribute set
3. Create simple product **"example product"** -> upload image **"test.jpg"** on _**global scope**_ and set it's role as **"example_image"** -> Save product
4. Open "example product" for edit on **_canada_** website store view and unset checkbox **"Use Default Values"** in the "Images and Video" section -> Save product
5. Open "example product" for edit on _**canada**_ website store view and set checkbox **"Use Default Values"** in the Images and Video section -> Save product
6. Open **"example product"** for edit on **_global scope_** and remove **"example_image"** role from image **"test.jpg"** -> Save product
7. Open "example product" for edit on **_canada website store view_** and take eye on "Images and video" section

### Expected result (*)

1. Image **"test.jpg"** will not have role **"example_image"** because "Use Default Values" is checked and it's was already deleted on **_global scope_**.

### Actual result (*)

1. Image **"test.jpg"** have role "**example_image"** on _**canada website store view**_

### Additional information
I investigated this issue and found that "scope-level" data isn't deleting from `catalog_product_entity_varchar` table for media image attributes when somebody checks "Use Default Values" however on text fields data is deleting (which is expected behavior).

**Comment by arendarenko** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @arendarenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @arendarenko, here is your [Magento instance](https://i-24916-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24916-2-3-develop.instances.magento-community.engineering/admin](https://i-24916-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by arendarenko** [comment]
Issue isn't reproducing on vanilla Magento instance

**Comment by arendarenko** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @arendarenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @arendarenko, here is your [Magento instance](https://i-24916-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24916-2-3-develop.instances.magento-community.engineering/admin](https://i-24916-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
