### ISSUE TITLE
Items Ordered table missing with php 7.2

### ISSUE THREAD

**Issue by mybathgreg** [magento/magento2#24912]
This was driving me crazy. New fresh install of 2.3.2

Upon adding an order through the backend, the admin account can do it successfully however any other user experiences the items ordered table as blank. The following code does not display....

<section id="order-items" class="admin__page-section order-items">
            
<div class="admin__page-section-title">
    <strong class="title">Items Ordered</strong>
    <div class="actions"><button class="action-secondary action-add" type="button" id="add_products"><span>Add Products</span></button>
            </div>
</div>
    <div id="order-items_grid">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary order-tables">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span>Product</span></th>
                        <th class="col-price"><span>Price</span></th>
                        <th class="col-qty"><span>Qty</span></th>
                                                <th class="col-subtotal"><span>Subtotal</span></th>
                        <th class="col-discount"><span>Discount</span></th>
                        <th class="col-row-total"><span>Row Subtotal</span></th>
                        <th class="col-action"><span>Action</span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100">No ordered items</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
        </section>

Downgrading to php 7.1 fixes the issue... any ideas here?

**Comment by engcom-Bravo** [comment]
Hello @mybathgreg. Thanks for reporting. We assume You mean `sales_order_item table` so we tested the issue in relation to that table (If we are wrong please correct us). With that we were not able to reproduce it on the latest vanilla 2.3-develop instance. Please try also to reproduce Your issue on such an instance. Thank You.

**Comment by engcom-Bravo** [comment]
Hi @mybathgreg. The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Comment by mybathgreg** [comment]
Thanks for the help... turns out it was a plugin causing the table to disappear.

Greg Walker
Manager
Cannavape.com
(844) 827-3266 [tel:(844)%20827-3266] | (607) 242-8965 [tel:(607)%20242-8965]
greg@cannavape.com [mailto:greg@cannavape.com]
www.cannavape.com
311 Mount View Lane Colorado Springs, CO 80907
[facebook] [https://www.facebook.com/cannavape]
[twitter] [https://www.twitter.com/cannavape]
[linkedin] [https://www.linkedin.com/in/greg-walker-2b103a99/]
[instagram] [https://www.instagram.com/cannavape]
On 10/23/2019 4:18:44 AM, Alexander Potoky <notifications@github.com> wrote:
Closed #24912 [https://github.com/magento/magento2/issues/24912].
