### ISSUE TITLE
Admin page breaks when Magento root is moved to new location

### ISSUE THREAD

**Issue by naps1saps** [magento/magento2#24911]
### Preconditions (*)

1. Latest Magento 2.3.2 & 2.3-develop
2. Ubuntu Server

### Steps to reproduce (*)

1. Install Magento to root sub folder example: /wwwroot/test/ URL = https://wwwroot.com/test/
2. Change URLs in admin or SQL to https://wwwroot.com
3. Move Magento root structure to wwwroot/

### Expected result (*)

1. Admin should work fine and is now in the correct file location.

### Actual result (*)

1. Test only done with SSL.  Admin pages will not load Magento logos, sign in successful, no links work inside admin panel
5.  If you don't move the root folder and instead change the Apache config, it works fine.

Troubleshooting:
Please see my thread here:
https://community.magento.com/t5/Magento-2-x-Technical-Issues/Admin-not-working-after-changing-base-url/m-p/143956

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21655` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Usually, we can't perform actions based on Filesystem or MySQL direct changes. If you are changing the Magento installation place we recommend to run the whole build process again.

I don't believe this is an actual issue, please feel free to reopen it and we can discuss it further.

Thanks.
