### ISSUE TITLE
"Create Permanent Redirect for URLs if URL Key Changed" for categories

### ISSUE THREAD

**Issue by vseager** [magento/magento2#24922]
When setting the config option `Stores > Configuration > Catalog > Catalog > SEO > Create Permanent Redirect for URLs if URL Key Changed` to "No". The "Create Permanent Redirect for old URL" is unchecked by default for products but is still checked by default when you change the URL key on a category.

### Preconditions (*)

1. Magento 2.3.2  and `2.4-develop`

### Steps to reproduce (*)
1. Go to `Stores > Configuration > Catalog > Catalog > Search Engine Optimisation` and set `Create Permanent Redirect for URLs if URL Key Changed` to "No".
2. Go to any category and edit the URL key.

### Expected result (*)

1. "Create Permanent Redirect for old URL" is **unchecked** by default (like products)

### Actual result (*)

1. "Create Permanent Redirect for old URL" is **checked ** by default

![screenshot-magento staging edge-servers com-2019 10 08-12_41_44](https://user-images.githubusercontent.com/2035088/66392966-39dd1800-e9c9-11e9-9d8f-2ae60e40431d.png)

![screenshot-magento staging edge-servers com-2019 10 08-12_42_37](https://user-images.githubusercontent.com/2035088/66392969-3cd80880-e9c9-11e9-8a05-aca2e1bbd56f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21569` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-24922-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24922-2-3-develop.instances.magento-community.engineering/admin](https://i-24922-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-24875).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-21569).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35237` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @vseager. Thank you for your report. 
The issue has been fixed in magento/magento2#28752 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [733d72a13d816a70845fdef5e2e2414c7909c873](https://github.com/magento/magento2/commit/733d72a13d816a70845fdef5e2e2414c7909c873)
 - [4592de4372db8b8bde4546d01a271fac45f40671](https://github.com/magento/magento2/commit/4592de4372db8b8bde4546d01a271fac45f40671)
 - [a6182592e29de840493505b26c7ba1adb1222f48](https://github.com/magento/magento2/commit/a6182592e29de840493505b26c7ba1adb1222f48)
 - [efb73f7dfc146e1eff6f226f0181c358b69b6ede](https://github.com/magento/magento2/commit/efb73f7dfc146e1eff6f226f0181c358b69b6ede)
 - [3cbe1ea75e9769b9505629a9c5edef199638677c](https://github.com/magento/magento2/commit/3cbe1ea75e9769b9505629a9c5edef199638677c)
 - [fbf5d3e352de07b801b219700e5e70c390e4435a](https://github.com/magento/magento2/commit/fbf5d3e352de07b801b219700e5e70c390e4435a)
 - [0c9623a74a65fae3a2ce10abb4fecfd4b5ef144f](https://github.com/magento/magento2/commit/0c9623a74a65fae3a2ce10abb4fecfd4b5ef144f)
 - [b729b5af3854a42589043013f09c90a1b6a5415b](https://github.com/magento/magento2/commit/b729b5af3854a42589043013f09c90a1b6a5415b)

The fix will be available with the upcoming 2.4.1 release.
