### ISSUE TITLE
Deployment The XML in file module-service-bus/etc/webapi.xml is invalid

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#24920]
### Preconditions (*)

1. Magento 2.3.x
2. Using `module-service-bus`, package `"magento/mcom-connector": "3.2.0"`

### Steps to reproduce (*)

1. On developer mode, try to deployment using `php bin/magento setup:upgrade`
2. See the log on screen

### Expected result (*)

1. No error validation on `module-service-bus/etc/webapi.xml`

### Actual result (*)

1. Validator for `webapi.xml` was failed
```
The XML in file "/home/xxx/vendor/magento/module-service-bus/etc/webapi.xml" is invalid:
Element 'route', attribute 'method': [facet 'enumeration'] The value 'OPTIONS' is not an element of the set {'GET', 'PUT', 'POST', 'DELETE'}.
Line: 15

Element 'route', attribute 'method': 'OPTIONS' is not a valid value of the local atomic type.
Line: 15

Verify the XML and try again.
```
2. System hang on deployment failed.

**Comment by engcom-Charlie** [comment]
Hello @tuyennn 
What is `module-service-bus`?
Is this third-party extension?

**Comment by tuyennn** [comment]
@engcom-Charlie We using `"magento/mcom-connector": "3.2.0"`

**Comment by milindsingh** [comment]
@tuyennn  Is it Magento Commerce package ?

**Comment by C4rter** [comment]
We've encountered the same issue today. It works in production mode, fails in developer mode. Any help would be appreciated.
