### ISSUE TITLE
majento installation failed

### ISSUE THREAD

**Issue by ramu424** [magento/magento2#24939]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by shikhamis11** [comment]
hello @ramu424 
Please follow [issue reporting guideline ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and mention clear steps to repoduce the issue
