### ISSUE TITLE
The \Magento\Framework\Filesystem\Directory\Read::readFile() method should firsly check whether the $path argument is empty string and raise an exception with a proper and clear message in this case instead of the current cryptic message

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2493]
https://mage2.pro/t/234

**Comment by andimov** [comment]
@mage2pro thank you for reporting.
Please fill description according to the template and specify magento version here.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
