### ISSUE TITLE
Wrong shipping amount calculation when checkout with multiple address is used.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24938]
### Preconditions (*)

1. Magento  Version : 2.3.3

### Steps to reproduce (*)

1. Add 2 or more products into the cart.
2. Use "Checkout with Multiple Address" and choose different shipping methods for each address.

### Expected result (*)

1.  Every order (for a different address) should have shipping rate as per selected shipping method.

### Actual result (*)

1. Every order (for a different address) should have shipping rate as per selected shipping method, but the shipping rates for last address applied on each address.

![multi address checkout](https://user-images.githubusercontent.com/39259107/66468985-aa0c9c00-eaa4-11e9-92f4-1c87037f7598.png)

![multi address checkout step 2](https://user-images.githubusercontent.com/39259107/66468919-93664500-eaa4-11e9-8407-21db058d7f9a.png)

![multi address checkout step 4](https://user-images.githubusercontent.com/39259107/66468931-98c38f80-eaa4-11e9-89fa-698980bed1e7.png)

![multi address checkout order details](https://user-images.githubusercontent.com/39259107/66468946-9c571680-eaa4-11e9-81a5-24976122f4d9.png)

**Comment by YevheniiKR** [comment]
@magento i am working on it

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21653` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajijshekh123** [comment]
This issue is related to the below issue link:
https://github.com/magento/magento2/issues/23631

**Comment by hostep** [comment]
@ajijshekh123: please don't close confirmed issues and link to another closed issue. We need to have at least one issue open, otherwise people will forget about it, thanks! 🙂

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24938-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24938-2-3-develop.instances.magento-community.engineering/admin](https://i-24938-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Okay @hostep 
I have verified this issue in the latest Magneto 2.3 instances with 2 different products and shipping methods.
The issue is not reproduced.
**See attached screenshots:**

![Review Order](https://user-images.githubusercontent.com/24711761/66540370-32447d00-eb49-11e9-8c2d-067150220471.png)

![Shipping Methods - Magento Commerce](https://user-images.githubusercontent.com/24711761/66540371-32dd1380-eb49-11e9-8798-01356e0659b2.png)

**Comment by ajijshekh123** [comment]
@MrGangola-Webkul - Please let me know which Magento instance you are using to reproduce this issue.

**Comment by ghost** [comment]
@ajijshekh123 I've generated the issue on Magento 2.3.3 instance.

**Comment by ajijshekh123** [comment]
@MrGangola-Webkul - Can you please send me one video or send exactly the scenario?

**Comment by ajijshekh123** [comment]
@MrGangola-Webkul - Now I am closing this issue. If you have found this issue again. Please add 'Steps to be reproduced' or 'Video' then open it.

**Comment by ghost** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-24938-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-24938-2-3-3.instances.magento-community.engineering/admin](https://i-24938-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
