### ISSUE TITLE
p2 tag / release?

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#24933]
Was this accidentally pushed or what release is this?

https://github.com/magento/magento2/releases/tag/2.3.2-p2

@xmav

Seems to be one of these new security patches ;-)

There is only p1 mentioned at https://magento.com/security/patches/magento-2.3.3-and-2.2.10-security-update

**Comment by sdzhepa** [comment]
Hello @DanielRuf 

Additional information about p1 and p2 described in [Magento Commerce 2.3.3 Release Notes](https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-commerce.html#new-security-only-patch-available) 
Quote:
> **New security-only patch available**
>
> Merchants can now install time-sensitive security fixes without applying the hundreds of functional fixes and enhancements that a full quarterly release (for example, Magento 2.3.3) provides. Patch 2.3.2.2 (Composer package 2.3.2-p2) is a security-only patch that provides fixes for vulnerabilities that have been identified in our previous quarterly release, Magento 2.3.2.
>
> **If you have already upgraded to the pre-release version of this patch (2.3.2-p1), we strongly recommend that you upgrade to 2.3.2-p2 as soon as possible.**  Patch 2.3.2-p2 contains the critical security fixes that are included in Magento 2.3.3, 2.2.10, 1.9.4.3, and 1.14.4.3, but that are not included in patch 2.3.2-p1.
>
> For general information about security-only patches, see the Magento DevBlog post Introducing the [New Security-only Patch Release](https://community.magento.com/t5/Magento-DevBlog/Introducing-the-New-Security-only-Patch-Release/ba-p/141287). For instructions on downloading and applying security-only patches (including patch 2.3.2-p1), see [Install Magento using Composer](https://devdocs-beta.magento.com/guides/v2.3/install-gde/composer.html#get-the-metapackage).

Also,  https://magento.com/security/patches/magento-2.3.3-and-2.2.10-security-update was updated according to p2

I think this issue can be closed now, could you please confirm?

**Comment by DanielRuf** [comment]
Here is still no p1, or does p2 contain p2?

https://github.com/magento/magento2/releases

If this is the case the patches might get bigger and bigger.

And the patch seems to contain more than only security related changes.

**Comment by DanielRuf** [comment]
Also this somehow makes not much sense. 2.3.2-p1 is a patched version of 2.3.2. So these might be changes from 2.3.3. But now there is also 2.3.2-p2 so 2.3.3 was patched twice but got only one release and no extra -p release?

I think something went wrong.

**Comment by DanielRuf** [comment]
The overall security process could be improved. This case was very rushed.

**Comment by AnnaShepa** [comment]
I would say it is not actual problem any more, @sdzhepa should we close the issue?

**Comment by sdzhepa** [comment]
Thank you @AnnaShepa and @DanielRuf  for collaboration.
I just want to add that I have shared all feedback to the internal teams about it and about external communication related to p1-p2 etc.

I hope next time we will not have such a situation or at least it will be more transparent.

Sorry for inconveniences
