### ISSUE TITLE
Partial sitempas have wrong urls in sitemap index

### ISSUE THREAD

**Issue by mattijv** [magento/magento2#24946]
### Preface
I went through all the current **open** issues (5 at the time of writing) that come up when searching for 'sitemap' and none of them are related to this problem. There are several closed issues about this problem, but instead of reopening one of them, I decided to open a new one to clearly describe the issue and cause.

For example https://github.com/magento/magento2/issues/19565 describes this same problem but the issue has been closed even though it can be reproduced with the latest version (68c48d55231de6849195e090e2b3ce750db61825) of the codebase.

### Preconditions (*)
1. Magento 2.3-develop with products, installed to a folder one or more levels above the Magento user's home folder (/home/magento/public_html for example).
2. Webserver serving the installation folder.
3. Nginx(reproduced only with nginx)

### Steps to reproduce (*)
1. Create a sitemap for the store (I used /pub/sitemaps folder and sitemap.xml as the configuration).
2. Set the sitemap generation limits so that the sitemap will be split into parts (i.e. set the product limit to some number < number of products in the store).
3. Set up a cron schedule to generate the sitemap.
4. Either wait for the system cron to generate the sitemap, or run `bin/magento cron:run` to generate it manually. **NB: to reproduce the issue, you need to run the cron:run command from the Magento user's home directory like the system cron would.**

### Expected result (*)
1. The partial sitemaps listed in the sitemap index have the correct url (e.g. *storeurl/pub/sitemap-1-1.xml*)

### Actual result (*)
1. The partial sitemap urls contain the folder structure between the Magento user home folder and the installation folder (in my case that would be *storeurl/* **public_html** */pub/sitemap-1-1.xml*).

### Cause
The problem is caused by the `_getStoreBaseDomain` method in the `Magento\Sitemap\Model\Sitemap` class. The code initializes the variables `$documentRoot` and `$baseDir` so that the `$baseDir` variable holds the path to the directory where the Magento installation resides, and the `$documentRoot` contains the path to the directory where the code is run from. In my example these would be */home/magento/public_html/* and */home/magento*

The method then checks if the `$baseDir` path contains `$documentRoot` and strips the `$documentRoot` from the `$baseDir` and sets the result to the `$installationFolder` variable. In my example the `$installationFolder` would therefore be `'public_html'`. The `$installationFolder` is then appended to the store url. Because of this the partial sitemap urls contain the *public_html* part when they should not.

I'm not creating a pull request to fix this as I'm unsure what the correct way to handle this is, but the current code seems to work incorrectly when used with cron. When the sitemap is generated from the admin view it works as expected.

### Hacky workaround
You can get around the issue by adding a `cd /path/to/magento/folder &&` at the beginning of the `cron:run` line in your crontab.

**Comment by engcom-Charlie** [comment]
Hello @mattijv 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

**Manual testing scenario:**

1. Configure apache
![image](https://user-images.githubusercontent.com/51680850/66638641-fd562a00-ec1d-11e9-90c8-dd529b8b205e.png)
2. Install Magento 2.3-develop into `www/html/magento2pr3/public_html/`
3. Create a sitemap for the store (I used /pub/sitemaps folder and newsitemap1.xml as the configuration).
4. Set the sitemap generation limits so that the sitemap will be split into parts (i.e. set the product limit to some number < number of products in the store).
5. Set up a cron schedule to generate the sitemap.
6. Either wait for the system cron to generate the sitemap
7. Check generated file

**Actual result:**
The partial sitemaps listed in the sitemap index have the correct url 
![image](https://user-images.githubusercontent.com/51680850/66638926-8bcaab80-ec1e-11e9-8e9d-70665ba7e4df.png)

So i have to close this issue.
Thanks for your report!

**Comment by mattijv** [comment]
@engcom-Charlie Did you generate the sitemaps with a system cron of a user **whose home directory is /var/www/html**? Otherwise you did not follow the steps correctly and the report is probably still valid.

#### To reiterate:
Magento is installed one directory down from the magento user's home directory (/home/magento/public_html). When the system cron runs for the magento user, the `$baseDir` and `$documentRoot` are set as described in the original bug report, which leads to the wrong url generation.

If the installation folder is somewhere else besides the users home directory, the code in the `_getStoreBaseDomain` method follows the alternate path in which case the urls are generated correctly.

I'm going to reopen the issue since I don't think you have followed the steps to reproduce correctly.

It is fairly obvious just by looking that the code doesn't work correctly when the Magento installation folder is contained within the magento user's home directory. And I did not find any mention that this isn't a supported way to install Magento.

**Comment by engcom-Charlie** [comment]
@mattijv yes, you are right.
 `/var/www/html` is not a home directory of my user.

**Comment by engcom-Charlie** [comment]
@mattijv i reproduced this issue with same steps as before but i change this configuration of apache virtual host:
![image](https://user-images.githubusercontent.com/51680850/66647318-3ba91480-ec31-11e9-9090-0e15442c43eb.png)
**Result:**
![image](https://user-images.githubusercontent.com/51680850/66647405-7d39bf80-ec31-11e9-9dda-c2e997d7f130.png)

But is it valid?

**Comment by mattijv** [comment]
@engcom-Charlie As far as I know, the apache conf you are using doesn't affect how your cron process sets the document root when running the code on the cli. You don't even need a webserver to reproduce the problem (besides setting the sitemap settings in the admin view) as this is purely a CLI issue.

The problem happens when:
**the folder you run the cron:run command in is above the Magento installation folder but part of the same tree**

If you insist on keeping the Magento installation in */var/www/html/something* while trying to reproduce the issue, then try running the cron:run command from */var/www/html* (i.e. do `php ./something/bin/magento cron:run`). I'm pretty sure that triggers the same issue.

**Comment by mattijv** [comment]
@engcom-Charlie I did not notice before, but it seems you have the same issue in the above picture, i.e. the urls contain the /public_html/ there. My bad for missing it.

**Comment by engcom-Charlie** [comment]
@mattijv could you show me base URL of your magento instance?

**Comment by mattijv** [comment]
@engcom-Charlie Here's my test setup:

**Nginx configuration**
```nginx
server {
    listen 80;
    server_name sitemap.local;
    set $MAGE_ROOT /home/magento/public_html/;

    # Magento basic conf file
    include /etc/nginx/sites-available/m23php72.conf;
}
```

Magento installed into `/home/magento/public_html/`.

`core_config_data` url configs

| config_id | scope | scope_id | path | value |
|--------------|---------|--------------|--------|---------|
| 1             | default |        0 | web/unsecure/base_url | http://sitemap.local/ |
|        26    | default |        0 | web/secure/base_url          | http://sitemap.local/ |

When I generate the sitemap from the admin view manually the urls are correct:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>http://sitemap.local/pub/sitemaps/sitemap-1-1.xml</loc><lastmod>2019-10-14T07:37:21+00:00</lastmod></sitemap>
<sitemap><loc>http://sitemap.local/pub/sitemaps/sitemap-1-2.xml</loc><lastmod>2019-10-14T07:37:21+00:00</lastmod></sitemap>
</sitemapindex>
```

but when they are generated by the cron they contain the *public_html* as a part of the url, which then leads to a 404 page.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>http://sitemap.local/public_html/pub/sitemaps/sitemap-1-1.xml</loc><lastmod>2019-10-14T07:27:16+00:00</lastmod></sitemap>
<sitemap><loc>http://sitemap.local/public_html/pub/sitemaps/sitemap-1-2.xml</loc><lastmod>2019-10-14T07:27:16+00:00</lastmod></sitemap>
</sitemapindex>
```

Here's a screenshot of the sitemap settings
![Screenshot from 2019-10-14 10-38-12](https://user-images.githubusercontent.com/1974547/66735379-dcd0de80-ee6e-11e9-90b7-692d6107847e.png)

Cron was installed using the `bin/magento cron:install` command.

**Comment by engcom-Charlie** [comment]
Hello @mattijv 
I have installed ngnix and reproduced your issue.
Thank you for contribution and collaboration!
![image](https://user-images.githubusercontent.com/51680850/66903863-d88df800-f00b-11e9-9e4b-fe173f756707.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21860` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ejsexton82** [comment]
This issue is occurring in Magento Cloud Commerce, as well. The sitemaps generate fine from the Magento Admin, but they are incorrect when generated from the cron.

**Comment by magento-engcom-team** [comment]
Hi @mattijv. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [4e3e5bd5d387cdb4ba6358c7d9e3a49a2cd8a3d8](https://github.com/magento/magento2/commit/4e3e5bd5d387cdb4ba6358c7d9e3a49a2cd8a3d8)
 - [071b47b38d08fe8c092625a19dca09bb6059e211](https://github.com/magento/magento2/commit/071b47b38d08fe8c092625a19dca09bb6059e211)
 - [61303b69a2ea96d20db1f5b728af7ca5e714510d](https://github.com/magento/magento2/commit/61303b69a2ea96d20db1f5b728af7ca5e714510d)

The fix will be available with the upcoming `2.3.5` release.

**Comment by IbrahimS2** [comment]
Still an issue.

**Comment by pmonosolo** [comment]
Did this issue come back in 2.4.3? 2.3.3 it worked fine, but for some reason 2.4.3 its broken again.

**Comment by hostep** [comment]
Part of those code changes referenced above got changed again in https://github.com/magento/magento2/commit/5ae32934cda53256c35eabcce27d92cb516a7411 in Magento 2.4.0 and higher. Might be related ...

@pmonosolo: could you open a new issue for this with steps of how to reproduce? Thanks!

**Comment by Green2Matter** [comment]
Magento 2.4.3 -> issue exists. 
Sitemap generated by cron consists of urls with duplicated domain: https://domain.com/https://domain.com/folder

Any update on this?
