### ISSUE TITLE
Dimensions missing from new product

### ISSUE THREAD

**Issue by radua** [magento/magento2#24948]
### Preconditions (*)

1. Magento v2.3.3

### Steps to reproduce (*)

1. Magento Admin > Catalog > Products > Add new Product 

### Expected result (*)

1. Product attribute set 'Default' should show fields for Length, Width and Height

### Actual result (*)

1. Above mentioned fields are missing

![image](https://user-images.githubusercontent.com/14368934/66495561-69eaf080-ea87-11e9-9a19-a1bcb0470d0a.png)

### Triage Note
- The issue is reproducible on `2.3.3` release version
- The issue is NOT reproducible on `2.3-develop`
- `2.3.3` is not merged into `2.3-develop` at this moment

**Comment by drpayyne** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @drpayyne, here is your [Magento instance](https://i-24948-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24948-2-3-develop.instances.magento-community.engineering/admin](https://i-24948-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @radua.
You need to set scope as global for this attributes then after it display while add product.
Let me know is there anything 
Thanks.

**Comment by radua** [comment]
hi @krishprakash ,
Thanks for your comment.
I did change the scope to global, still these fields were not visible.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21731` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vinay-chhabra** [comment]
@magento I am working on it

**Comment by ghost** [comment]
@magento I am working on it

**Comment by dev-Z-Apx** [comment]
@vinay-chhabra  can you please tell me when this issue will be fixed, any idea?
and will it be available in this release as a fix or it will be provided in new release ?

**Comment by sagarppanchal** [comment]
I have Upgraded My Magento Version to 2.3.3 from 2.3.1, 
Using this version I found the solution for LInk (href) Removal from all CMS Pages while using wynsing editor but all the Dimension fields got invisible, have you guys found any solution for this ?

**Comment by dev-Z-Apx** [comment]
@sagarppanchal  It is still under Dev at Magento end, however there is a temporary fix  
just update the eav_attribute table and source_model = NULL WHERE attribute_code = 'ts_packaging_type'

it will make the attributes appear and working as it has to be.

**Comment by sagarppanchal** [comment]
@dev-Z-Apx 
Thank you so much for this Solution, this would be helpfull & work for me as of now.
I will also look forward to this issue and will let you guys know If can find anything related to this.

**Comment by sagarppanchal** [comment]
hello @dev-Z-Apx 
What I have done is inside SetupData.php

```
> const ATTRIBUTE_CODE_LENGTH = 'temando_dimensions_length';
> const ATTRIBUTE_CODE_WIDTH = 'temando_dimensions_width';
> const ATTRIBUTE_CODE_HEIGHT = 'temando_dimensions_height';
```

and this worked for me.
Hope this would be helpful.

**Comment by gabrielxavila** [comment]
Is there a solution to this? I’m on Magento 2.3.3 and my length, width, height aren’t populating when I creat a product

**Comment by radua** [comment]
> 
> 
> Is there a solution to this? I’m on Magento 2.3.3 and my length, width, height aren’t populating when I creat a product

Hi @gabrielxavila Turns out so long as the attribute_code is ts_dimensions_length, it won't show. If you change the attribute_code to something else like dimensions_length or just length, the fields show up. You will have to do this change in the database. The same applies to width and height.

Hope this helps!

**Comment by gabrielxavila** [comment]
> > Is there a solution to this? I’m on Magento 2.3.3 and my length, width, height aren’t populating when I creat a product
> 
> Hi @gabrielxavila Turns out so long as the attribute_code is ts_dimensions_length, it won't show. If you change the attribute_code to something else like dimensions_length or just length, the fields show up. You will have to do this change in the database. The same applies to width and height.
> 
> Hope this helps!

Hello @radua can you elaborate on the best to accomplish this, please. I’m relatively new to Magento and can use any help. My understanding is the only way to access or change the tables is through sql?

**Comment by sdzhepa** [comment]
Magento stops supporting of Temando module. Please see more details https://magento.com/shipping
Long story short: 
- The extension owner does not work and support this module anymore.
- Magento will support "_existing customers until November 15, 2020_" only through the support channel associated with your Magento account. 
- In the internal Magento backlog there is a ticket to completely remove Temando from Magento.
