### ISSUE TITLE
after installing majento it comes like this Not Found  The requested URL was not found on this server. Apache/2.4.29 (Ubuntu) Server at 192.168.0.205 Port 80

### ISSUE THREAD

**Issue by ramu424** [magento/magento2#24940]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by ramu424** [comment]
![issue](https://user-images.githubusercontent.com/49101677/66469618-cbba5300-eaa5-11e9-8e08-1f4d2ba8b8d8.png)
after installing majento it shows below error.please find the attached screen shot

**Comment by ramu424** [comment]
after installing majento it shows the above error

**Comment by shikhamis11** [comment]
hello @ramu424
Please follow [issue reporting guideline](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and mention clear steps to repoduce the issue.

> after installing majento it shows the above error

with the image it seems issue at your server end Please contact your server provider to the check the issue or check if you have opened correct url or not
