### ISSUE TITLE
i m getting this error [ErrorException] file_get_contents(app/etc/NonComposerComponentRegistration.php): failed to open

### ISSUE THREAD

**Issue by kobid** [magento/magento2#2494]
i am using nginx page-speed mod in Ubuntu
previously i have installed magento everything was fine but today i was trying for a fresh install got this error
![capture](https://cloud.githubusercontent.com/assets/10341684/11353886/26e71d02-926d-11e5-9278-6a77d827d606.JPG)

**Comment by buskamuza** [comment]
Duplicate of https://github.com/magento/magento2-community-edition/issues/15

**Comment by daim2k5** [comment]
Internal ticket: MAGETWO-45957.

Temporary workaround: downgrade Composer to lower version. Verified with the following version:

composer self-update 1.0.0-alpha11
