### ISSUE TITLE
Email not working with special characters in sender name (Magento 2.3.3)

### ISSUE THREAD

**Issue by michelecanal** [magento/magento2#24957]
### Preconditions (*)

1. Magento CE 2.3.3
2. Special Charapters (as "à") in sender name (store's emails)

### Steps to reproduce (*)

1. take ad action that generate email
2. email doesn't work

### Expected result (*)

1. email sent to recipient

### Actual result (*)

1.  email not sent to recipient

**Comment by michelecanal** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.3 release


Il giorno gio 10 ott 2019 alle ore 09:23 m2-assistant[bot] <
notifications@github.com> ha scritto:

**Comment by magento-engcom-team** [comment]
Hi @michelecanal. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @michelecanal, here is your [Magento instance](https://i-24957-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24957-2-3-develop.instances.magento-community.engineering/admin](https://i-24957-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by michelecanal** [comment]
Hi, I made some tests.
In this instance, no email work.
Can you check, please? (server configuration?)




Il giorno gio 10 ott 2019 alle ore 09:30 Magento Community Engineering <
notifications@github.com> ha scritto:

**Comment by oewean** [comment]
Bug also exists in contact us form, special characters in senders name resulting in error: Invalid header value detected

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21678` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by elvinristi** [comment]
this is duplicate to https://github.com/magento/magento2/issues/24902 which has fix in PR https://github.com/magento/magento2/pull/24906
