### ISSUE TITLE
Associated products attribute value returning false

### ISSUE THREAD

**Issue by med-amin** [magento/magento2#24952]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2.22

### Steps to reproduce (*)

1. Create a new attribute with backend type int .
2. Dates in mo_eav_attribute_option_value
2017-12-31 19:00:00
2018-01-01 20:30:00
2019-12-31 19:00:00
2020-01-01 20:30:00

### Expected result (*)

1. The attribute value should be date

### Actual result (*)

1. The attribute value is false
![associated product](https://user-images.githubusercontent.com/46812464/66504438-fc5bb600-eac0-11e9-9c3a-d95fa5c15888.PNG)

**Comment by magento-engcom-team** [comment]
Hi @med-amin. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @med-amin, here is your [Magento instance](https://i-24952-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24952-2-3-develop.instances.magento-community.engineering/admin](https://i-24952-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21762` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
@med-amin , could you please specify the steps clearly, like what is the process of Date that you have given in step 2. You just mentioned create an attribute and dates in this table : mo_eav_attribute_option_value.

**Comment by magento-engcom-team** [comment]
Hi @med-amin. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @med-amin, here is your [Magento instance](https://i-24952-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24952-2-3-develop.instances.magento-community.engineering/admin](https://i-24952-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by aleromano89** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @aleromano89. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleromano89, here is your [Magento instance](https://i-24952-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24952-2-4-develop.instances.magento-community.engineering/admin_afef](https://i-24952-2-4-develop.instances.magento-community.engineering/admin_afef)
Login: `07598191` Password: `22142b640dee`
Instance will be terminated in up to 3 hours.

**Comment by aleromano89** [comment]
@med-amin I'm not able to reproduce the issue on magento 2.4-develop instance. Can you add more details?

**Comment by aleromano89** [comment]
hi @med-amin , why do you need to access to the database?

**Comment by med-amin** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @med-amin. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by med-amin** [comment]
@aleromano89  I need database access to add attribute options

**Comment by sdzhepa** [comment]
Hello @med-amin 

Could you please provide more detailed steps on how you create these attributes in the Magento Admin panel?
Without clear steps, it is not to process this issue and define is it bug or wrong steps or expectations.

**Comment by sdzhepa** [comment]
Closed as cannot reproduce
