### ISSUE TITLE
Coupon used in Invoice but doesn't show up in Sales Coupon Report

### ISSUE THREAD

**Issue by 29sunil** [magento/magento2#24958]
### Preconditions (*)

1.magento version 2.3.2
2.

### Steps to reproduce (*)

1.Report-> coupon -> select date range
2.

### Expected result (*)

1. All used cupon result will show 
2.

### Actual result (*)

1. only few month reports is showing 
2.
![cuponrepostnew](https://user-images.githubusercontent.com/35294849/66551645-82313d00-eb65-11e9-8bf6-131d89227798.png)

**Comment by 29sunil** [comment]
yes we have shared all information

**Comment by 29sunil** [comment]
![cupon2](https://user-images.githubusercontent.com/35294849/66556614-359e2f80-eb6e-11e9-8e52-c84fe8c1f346.png)

**Comment by 29sunil** [comment]
is there any update regarding this issue

**Comment by sudheers-kensium** [comment]
@29sunil Not reproduced the issue, Please provide more information.

**Comment by 29sunil** [comment]
what kind of information you need.  We did not get cupon report of last three month. only july month cupon report is showing

**Comment by 29sunil** [comment]
![cupon2](https://user-images.githubusercontent.com/35294849/66565106-41deb880-eb7f-11e9-866c-2db6bd90011f.png)

**Comment by 29sunil** [comment]
![cupon3](https://user-images.githubusercontent.com/35294849/66565236-a4d04f80-eb7f-11e9-9bce-b8103439417c.png)

**Comment by 29sunil** [comment]
These orders are made at September month. these coupon codes are not showing at the cupon report section.

**Comment by sudheers-kensium** [comment]
> These orders are made at September month. these coupon codes are not showing at the cupon report section.

But your filter date from Feb 1st to Aug 10, Please check once.

**Comment by 29sunil** [comment]
this issues similar to this one (https://magento.stackexchange.com/questions/255448/coupon-used-in-invoice-but-doesnt-show-up-in-sales-coupon-report ) . there is no reply at all.
Thnaks

**Comment by sudheers-kensium** [comment]
@29sunil , issue not reproducible, I am closing this.

**Comment by 29sunil** [comment]
![cupon4](https://user-images.githubusercontent.com/35294849/66566165-e19d4600-eb81-11e9-804a-31a7db00f2b3.png)
Please see  this video (https://www.loom.com/share/29246fe71894481b805d1323994d0494 )
