### ISSUE TITLE
Inconsistency between the 2.3.3 Tag and 2.3-develop branch

### ISSUE THREAD

**Issue by joris-ati4** [magento/magento2#24951]
### Summary (*)

This issue concerns multiple bugs that I discovered while upgrading Magento to 2.3.3

Today I am having some bugs while upgrading magento to the 2.3.3 release. I opened a bug for an issue with the store switcher that is only present on 2.3.3. After spinning up an instance running the 2.3-develop branch, I wasn't able to reproduce this issue. (this was strange)

So I did some digging and found out that the file in question was a different version between the 2.3-develop branch and the 2.3.3 tag. No problem, I made a patch and everything worked fine.

Some time later I stumbled on another issue. While debugging this issue I discovered something really strange in the versionning of Magento

### Examples (*)

 The file in question 

https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/lib/internal/Magento/Framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php

was updated on june the 3th on the 2.3.3 Tag. But when looking at the history, I noticed that the same file on the 2.3.3 Tag and 2.3-develop branch wasn't updated since 2017.

2.3.2 => https://github.com/magento/magento2/blob/2.3.2/lib/internal/Magento/Framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php

2.3-develop => https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php

2.3.3 => https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php

### Proposed solution

Normally the updated file should have been on the 2.3-develop branch before getting in the release ? 

Am I missing something ? 

Thank you very much !

**Comment by hostep** [comment]
Yeah this is highly annoying.

Version 2.3.3 was already available 2 weeks ago in pre-release, so they should already have had plenty of time to prepare the merge into 2.3-develop.
With 2.3.2 we saw the same thing, it took many weeks until code from 2.3.2 finally made it in 2.3-develop.
Not really sure why this always takes so long.

> Normally the updated file should have been on the 2.3-develop branch before getting in the release ?

This is most likely done for security reasons, as this would be a bad idea to make security fixes already publicly available before the actual release.
But it doesn't mean they can't already prepare the merge in a private branch and then merge it in the 2.3-develop public branch when releasing, I'm not sure why this doesn't happen?

**Comment by joris-ati4** [comment]
Ok I can understand they don't want to merge it into the 2.3-develop branch because of security reasons but it should be merged once the release comes out. The problem now is when I report a bug present in 2.3.3, it is not possible to reproduce it on the instance that is spun up with the 2.3-develop branch and so people may think it is not even a bug...

**Comment by DanielRuf** [comment]
> This is most likely done for security reasons, as this would be a bad idea to make security fixes already publicly available before the actual release.
> But it doesn't mean they can't already prepare the merge in a private branch and then merge it in the 2.3-develop public branch when releasing, I'm not sure why this doesn't happen?

Exactly. And also there is now a p2 release but no p1 tag (only a p2 tag).
It seems there should be some things improved, especially when it comes to communication and a clear approach.

**Comment by hostep** [comment]
Yeah indeed, communication from Magento is lacking a bit in regards to explaining why or how some things are being done.

Regarding the `p2` tag, they were friendly enough to explain it in the security channel on Slack, so here are some quotes from Piotr:
> 2.3.2-p1 was prerelease version that missed some patches. 2.3.2-p2 is the most recent version that should be used. So yes, if you have -p1 applied, you should apply -p2
> the difference is only in EE modules
> but both had to be released as -p2
> CE and EE

(for the newcomers, CE means Magento Open Source, EE means Magento Commerce)

**Comment by DanielRuf** [comment]
Ok, that makes it more clear. I guess I can not join this channel as I am not a maintainer and just a normal contributor.

**Comment by hostep** [comment]
Everybody can join, and please do, it can be very informative: https://opensource.magento.com/slack (from: https://github.com/magento/magento2/wiki/Slack-Channels)

**Comment by DanielRuf** [comment]
Ah this is some public channel which was startedmid 2018. I thought you mean the internal one for the security team to discuss and improve the process.

Security updates / patches are still not so great imo.

**Comment by hostep** [comment]
It looks like the 2.3.3 release branch was finally merged in 2.3-develop some hours ago: https://github.com/magento/magento2/commit/0583fc3a88c948b2e95c6874c6dda1caaa4f9442

It would still be great if there could be some kind of explanation why it takes this long to get this merged and if this period could be shortened for the next release somehow.

**Comment by engcom-Charlie** [comment]
Hello @jojotjebaby 

I am closing this issue as not actual.
2.3.3 release branch was finally merged in 2.3-develop and `ConfigurableObject.php` is updated now.

Thanks for your report!

**Comment by hostep** [comment]
Hi @engcom-Charlie 

Any reaction to the following would be appreciated! :)

> It would still be great if there could be some kind of explanation why it takes this long to get this merged and if this period could be shortened for the next release somehow.

**Comment by engcom-Charlie** [comment]
Hi @hostep !

I'll try to find out something :)
