### ISSUE TITLE
Order Grid  - datepicker RTL issue

### ISSUE THREAD

**Issue by mtrzk** [magento/magento2#24963]
Hi, I have error in order grid with datepicker on RTL admin layout.

### Preconditions (*)
1. Magento 2.3.2
2. mageplaza/magento-2-arabic-language-pack

### Steps to reproduce (*)
1. Use arabic (ar_SA - Saudi Arabia) language in backend
2. Go to Sales -> Orders
3. Open Filters
4. Set Purchase date to some date
5. Try to apply.

### Expected result (*)

1. Normal working datepicker like in English:
![image](https://user-images.githubusercontent.com/3176887/66580792-3f7c5e80-eb7f-11e9-9434-4d1c7a6e1d97.png)

### Actual result (*)
1. When I click on datepicker for example 10th October this is result "10‏/10‏/2019 GGGGG": 
![image](https://user-images.githubusercontent.com/3176887/66580742-32f80600-eb7f-11e9-844b-455fbbff5dc3.png)

**Comment by mtrzk** [comment]
Hi, Could anyone help me with this issue?

**Comment by ammarabdulsalam** [comment]
I think this is because of RLM character. Unfortunately, I have to change Magento core class DateTime under Magento\Framework\Stdlib\DateTime\Filter to fix this.
try to debug this class to fix your issue.
note: There must be a better solution for this.

**Comment by mtrzk** [comment]
Thank for answer. I debugged this class and functions, unfortunately it doesn't used in datetime filter in the UI Component.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22860` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mtrzk** [comment]
Could anyone fix this issue? Because it's quite urgent.

**Comment by nitish-ranjan05** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05, here is your [Magento instance](https://i-24963-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24963-2-4-develop.instances.magento-community.engineering/admin_ceca](https://i-24963-2-4-develop.instances.magento-community.engineering/admin_ceca)
Login: `88f3977b` Password: `4ad41d64e3ce`
Instance will be terminated in up to 3 hours.

**Comment by creative-ae** [comment]
im facing same issue, any solution ?

**Comment by hielh** [comment]
Hi
I'm facing the same issue, any solution please ?.
Ater my investigation the problem comes from a library PHP 
`
 /**  \Magento\Framework\Stdlib\DateTime\Timezone
     * @inheritdoc
     */
    public function getDateFormat($type = \IntlDateFormatter::SHORT)
    {
        return (new \IntlDateFormatter(
            'ar',
            $type,
            \IntlDateFormatter::NONE
        ))->getPattern();
    }
`
IntlDateFormatter will generate a GGGGG in the picker even if you change xml file for Zendframework ar.xml and ar_SA.xml
referer to this link to see that IntlDateFormatter will generate GGGGG
https://icu4c-demos.unicode.org/icu-bin/locexp?d_=en&_=ar_SA

**Comment by menacoders** [comment]
check this module,
we have developed it to fix this issue and all date picker issues in Arabic dashboard.
https://github.com/menacoders/rtl-datepicker-magento2
@marcinmaterzok @hielh @zorox-1

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
