### ISSUE TITLE
Method chaining broken by refactor in Module_Catalog Product Collection

### ISSUE THREAD

**Issue by abdulmueid** [magento/magento2#24964]
The commit https://github.com/magento/magento2/commit/a77fd52e34a4f1f1b47e8275e4f671b37c92e20a refactors the method `addAttributeToFilter` in file `app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php` by adding two new methods `addIsSaleableAttributeToFilter` and `addTierPriceAttributeToFilter`.

However, there are missing return statements in the `if` statement which break method chaining. https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L1591-L1597

### Preconditions (*)

1. Magento Version 2.3.3

### Steps to reproduce (*)

1. Create an instance of \Magento\Catalog\Model\ResourceModel\Product\Collection
2. Call the method `addAttributeToFilter` with attribute `is_saleable`
3. Chain the method `addAttributeToFilter` with any other attribute to chain the function

### Expected result (*)

1. Method chaining works as expected

### Actual result (*)

1. `addAttributeToFilter` returns null when adding `is_saleable` to filter, therefore breaking method chaining

**Comment by electroidru** [comment]
I think that's critical. After update to 2.3.3 exception with porto theme PHP Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ResourceModel\Product\Collection::addIsSaleableAttributeToFilter()

**Comment by abdulmueid** [comment]
@electroidru that error is a related but separate problem. The new method signatures type check condition parameter for nullable array whereas the calling method `addAttributeToFilter` does not type check the condition at all.

This breaks a number of popular themes (Porto, Market) and modules which filter products. We can open another issue for this behavior. I'm still debugging and checking for all the misbehaviours.

**Comment by mahesh-rajawat** [comment]
@shikhamis11  Please look in to this, and confirm this issue. This issue is reproducible.

**Comment by shikhamis11** [comment]
Hello @abdulmueid 
thank you for reporting this issue 

> The commit a77fd52 refactors the method addAttributeToFilter in file app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php by adding two new methods addIsSaleableAttributeToFilter and addTierPriceAttributeToFilter.
However, there are missing return statements in the if statement which break method chaining. 

yes you are right Please make Pull request with it's solution 
you can check guide for contribution 
https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21707` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
@shikhamis11 Thanks for verifying this issue. @magento i am working on it.

**Comment by magento-engcom-team** [comment]
Hi @abdulmueid, @shikhamis11, @maheshWebkul721. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.4` release.

**Comment by hzubyrss** [comment]
You should contact your theme developer and ask them for the updated patch for Magento 2.3.3 if you using Porto theme follow this link:  [https://magento2expert.com/error-after-indexing-after-upgrade-to-magento-2-3-3-porto-theme/](url)
