### ISSUE TITLE
Coupon used in Invoice but doesn't show up in Sales Coupon Report

### ISSUE THREAD

**Issue by 29sunil** [magento/magento2#24960]
### Preconditions (*)

1.Login in admin section 
Report-> coupon -> select date range
2.

### Steps to reproduce (*)

1.login in the admin section and follow the 
![cupon3](https://user-images.githubusercontent.com/35294849/66566459-a2232980-eb82-11e9-8b7d-299f365b265f.png)
![cupon4](https://user-images.githubusercontent.com/35294849/66566460-a3545680-eb82-11e9-8f09-a0ecc7b2c1eb.png)
![cuponrepostnew](https://user-images.githubusercontent.com/35294849/66566471-a8b1a100-eb82-11e9-8dae-302648e479b2.png)
![cupon2](https://user-images.githubusercontent.com/35294849/66566472-a8b1a100-eb82-11e9-944b-fae981f42e9c.png)

https://www.loom.com/share/29246fe71894481b805d1323994d0494

below step.
2.Report-> coupon -> select date range

### Expected result (*)

1. [Screenshots, logs or description]
2. All month coupon code report will be shown

### Actual result (*)

1. [Screenshots, logs or description]
2.only few month reports is showing

**Comment by 29sunil** [comment]
All information is shared

**Comment by 29sunil** [comment]
kindly watch this video and print screen

**Comment by 29sunil** [comment]
We are facing same issues(https://magento.stackexchange.com/questions/255448/coupon-used-in-invoice-but-doesnt-show-up-in-sales-coupon-report )

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24960-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24960-2-3-develop.instances.magento-community.engineering/admin](https://i-24960-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 29sunil** [comment]
what is the use of this instance? There is no order at all. how can we check it .if you need then we will provide our website details.  did you check the video that is shared by us? what is the solutions of this issues
Thanks

**Comment by shikhamis11** [comment]
hello @29sunil 
I have created one order where I have used coupon code .. I tried to get report and thre it seems working fine .. 
can you check once on instance ?

**Comment by 29sunil** [comment]
yes it is showing. But it is not showing on my website.what will be the possible reason.

**Comment by shikhamis11** [comment]
may be it is fixed in any pull request or by magento internal team members

**Comment by 29sunil** [comment]
ok so we need to wait for reply of Magento team member

**Comment by shikhamis11** [comment]
@29sunil can you share magento version details on wich this issue is occuring ?

**Comment by shikhamis11** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24960-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-24960-2-3-2.instances.magento-community.engineering/admin](https://i-24960-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 29sunil** [comment]
For now, our live website Magento version is 2.3.0 (https://prnt.sc/phgh07). But we have upgraded the Magento version (2.3.2 )at our local system. But we get the same errors. Please see this video 
https://www.loom.com/share/34b306c9a762473dbeded46b28d276a8

**Comment by shikhamis11** [comment]
I checked on magento 2.2 version also It seems working fine 
at your end it may be due to any custom development please check at your end once

**Comment by shikhamis11** [comment]
hello @29sunil 
I am closing this issue as it is not reproducible .. Feel free to reopen the issue If you are able to reproduce it on 2.3-develop instance also share screenshots for that instance
