### ISSUE TITLE
 Design issue when applying filter by name in the category section at admin panel.

### ISSUE THREAD

**Issue by ghoshsweta** [magento/magento2#24961]
### Preconditions (*)

Issue on Magento 2.3.3
Magento Admin Account Sharing is disabled

### Steps to reproduce (*)
1.Login to magento admin panel on Chrome browser
2.Go to Catalog->categories->select a category
3.Go to Products in Category and enter any random text on name field. Do not hit search or enter button
4. In a Private run the magento admin panel and fill in the login details. Do not hit search or enter button
5. Now hit the search button on step 3 and and step 4 at the same time.

### Expected result (*)
1. A message related to session had expired should be returned

### Actual result (*)
1. Design issue is returned on step 3 when step 5 is followed
![screenshot-192 168 0 86-2019 10 10-11_11_05](https://user-images.githubusercontent.com/25763126/66570575-7ce6e900-eb8b-11e9-8605-1043fab4be60.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21690` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
This issue is not only category page, its appearing on each grid where grid is initiated by Block and setUseAjax is true in Block: https://prnt.sc/phx0lk https://prnt.sc/phx0r8
