### ISSUE TITLE
Amazon Pay Checkout Place Order redirect to the cart on success

### ISSUE THREAD

**Issue by livvly** [magento/magento2#24967]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Enable Amazon Pay
2.Checkout with Amazon Pay

### Expected result (*)

1. [Screenshots, logs or description]
2.Redirect to /checkout/onepage/success

### Actual result (*)

1. [Screenshots, logs or description]
2.redirected to /checkout/cart

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-24967-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24967-2-3-develop.instances.magento-community.engineering/admin](https://i-24967-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@livvly Thank you for your report.
I'm not able to reproduce the issue as provided steps by you. Can you provide more details.

**Comment by livvly** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @livvly. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @livvly, here is your [Magento instance](https://i-24967-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24967-2-3-develop.instances.magento-community.engineering/admin](https://i-24967-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by livvly** [comment]
@sudheers-kensium Well, I got everything linked up and it just seems like the only issue is at the last step of checkout. It first redirect to /checkout/onepage/success, and very soon redirect back to /checkout/cart.

**Comment by sudheers-kensium** [comment]
@livvly I'm not able to reproduced, if you reproduced the issue in Magento 2.3-develop instance please provide video link.
