### ISSUE TITLE
og:description Not loading as shortDescription attribute is no-longer available in product.

### ISSUE THREAD

**Issue by magearray** [magento/magento2#2496]
vendor\magento\module-catalog\view\frontend\templates\product\view\opengraph\general.phtml

in this file meta Tag is getting content from product ShortDescription

meta property="og:description" content="<?php /\* @escapeNotVerified */ echo $block->stripTags($block->getProduct()->getShortDescription()); ?>" 

But as we seen in Product there is no ShortDescription Attribute available in Magento 2.0.0 CE.

so, as we share product link on Facebook (or Social Media) it won't fetch description as Meta tag is empty due to above reason.

**Comment by dmitrii-fediuk** [comment]
Actually, Magento 2 Release has the `short_description` attribute: https://github.com/magento/magento2/blob/2.0.0/app/code/Magento/Catalog/Setup/InstallData.php#L265
The `getShortDescription` is just a magic method to access the `short_description` object property.

**Comment by magearray** [comment]
Yes, you are right but in back-end there is no box to add short description so how they get this short_description. 
i am aware of magic method to access the short_description.

**Comment by dmitrii-fediuk** [comment]
You are wrong again. There IS an input for the short description in the backend.

**Comment by dmitrii-fediuk** [comment]
https://mage2.pro/t/252
