### ISSUE TITLE
Magento 2.2.10, composer not working if you use php 7.2

### ISSUE THREAD

**Issue by gonzaloebiz** [magento/magento2#24965]
As per the documentation, magento 2.2.10 supports php 7.2, so i try to use it to install an extension via composer.
![image](https://user-images.githubusercontent.com/6222792/66582301-ef3dd600-eb57-11e9-91ba-71f7d0ce9504.png)

### Preconditions (*)
1.Install a vanilla magento 2.2.10 (the issue is present if you update from a previous version of magento too)

### Steps to reproduce (*)
1.Try to install any extension via composer using php 7.2

### Expected result (*)
1. The extension was correctly downloaded and installed

### Actual result (*)
1. the composer require command returns

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/composer 1.2.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.23) does not satisfy that requirement.
    - magento/composer 1.2.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.23) does not satisfy that requirement.
    - magento/composer 1.2.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.23) does not satisfy that requirement.
    - magento/composer 1.2.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.23) does not satisfy that requirement.
    - Installation request for magento/composer (locked at 1.2.0) -> satisfiable by magento/composer[1.2.0].

![image](https://user-images.githubusercontent.com/6222792/66582587-6b381e00-eb58-11e9-8845-76b0419f1aa3.png)

**Comment by hostep** [comment]
@gonzaloebiz: you should try to figure out what module (or maybe even your root `composer.json` file) is locking the `magento/composer` package at version 1.2.0.

When installing Magento 2.2.10 using PHP 7.2, it installs `magento/composer` version 1.2.2 which is marked as compatible with PHP 7.2.
See the changes between version 1.2.0 and 1.2.2: https://github.com/magento/composer/compare/1.2.0...1.2.2

Maybe you can also try to simply run `composer update magento/composer` and maybe it will upgrade to 1.2.2 and that might then also solve your problem?

Closing for now as everything seems to work as expected with PHP 7.2.

**Comment by gonzaloebiz** [comment]
If i download the zip file for 2.2.10 from the magento site, the vendor/magento/composer/composer.json file is
![image](https://user-images.githubusercontent.com/6222792/66596092-a2b3c400-eb72-11e9-922c-71c8ec002d1e.png)
(the version is clearly 1.2.0)

Also, in https://github.com/magento/magento2/blob/2.2/composer.json#L57 the version of composer is 1.2 (and not 1.2.2)

The described method thus is run first
composer update magento/composer

works, one i run this, i can install any extension via composer, but not before.
Is weird that i need to run an update of the magento/composer before installing any other extension in a vanilla installation, i think is not the expected.

**Comment by gonzaloebiz** [comment]
If i install magento via composer works. So, the issue is with the downloadable version in https://magento.com/tech-resources/download

Best

**Comment by hostep** [comment]
Yeah, it's a bit odd that they include 1.2.0 by default while they could also have included 1.2.2 in the zip. No idea why that happened.

Maybe always start with a 'composer update' after installing Magento, so all your dependencies are the latest at that moment.

But happy to hear you have a solution now! 🙂

(after playing around a bit with various php versions and Magento 2.2.10, I'm now suspecting it's [a bug in composer itself](https://github.com/composer/composer/issues/8370), something really odd is going on with that `magento/composer` package over here...)

**Comment by hostep** [comment]
I'm going to reopen this after [finding out](https://github.com/composer/composer/issues/8370#issuecomment-542645230) that composer's behavior is correct.

The correct solution for Magento here, would be to publish version 1.2.2 of `magento/composer` to repo.magento.com, which wasn't done yet for some reason.

**Comment by buskamuza** [comment]
> Yeah, it's a bit odd that they include 1.2.0 by default while they could also have included 1.2.2 in the zip. No idea why that happened.

Probably we were packaging it on a machine with PHP 7.1. In this case Composer downloads library versions compatible with PHP 7.1.
For now I'd recommend to run `composer update` for the zip-based installation. This should download libraries compatible with your system's PHP version.

**Comment by hostep** [comment]
> Probably we were packaging it on a machine with PHP 7.1. In this case Composer downloads library versions compatible with PHP 7.1.

It should have installed version 1.2.2 with PHP 7.1, but that only can happen when that version is available on repo.magento.com according to the discussion in https://github.com/composer/composer/issues/8370

**Comment by engcom-Charlie** [comment]
Hello @gonzaloebiz 

I am closing this issue as not actual.
Checked on Magento 2.2.10 
![image](https://user-images.githubusercontent.com/51680850/67853552-79ee7100-fb17-11e9-8e00-c89e5f55d783.png)

Thanks for your report!

**Comment by hostep** [comment]
@engcom-Charlie: can you confirm that version 1.2.2 is now available on repo.magento.com as that is the real issue here? Thanks!

*Update*: sorry it's in your screenshot, my bad, thanks! 🙂

**Comment by gonzaloebiz** [comment]
OK, for me work OK now

Thanks
