### ISSUE TITLE
Product Edit is broken after 2.3.3 update

### ISSUE THREAD

**Issue by jgahn-xom** [magento/magento2#24968]
### Preconditions (*)

1.Version 2.3.3

### Steps to reproduce (*)

1. Catalog -> Products -> edit any product

### Expected result (*)
1. Product edit page

### Actual result (*)
1. error and no edit page:
Warning: Use of undefined constant formName - assumed 'formName' (this will throw an Error in a future version of PHP) in /var/www/magento2/vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/helper/gallery.phtml on line 64

Fixed by adding a missing $ before formName on line 64 of referenced file.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-24968-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24968-2-3-develop.instances.magento-community.engineering/admin](https://i-24968-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Unable to reproduce the issue on 2.3-develop branch

**Comment by hostep** [comment]
@MrGangola-Webkul: please don't test on 2.3-develop when people report issues for Magento 2.3.3, parts of the code from Magento 2.3.3 aren't included yet in 2.3-develop at the moment of writing, we should [wait until that happens](https://github.com/magento/magento2/issues/24951) before we can use 2.3-develop again to test on.

The issue clearly exists in 2.3.3, there is a `$` missing over [here](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/helper/gallery.phtml#L64).

**Comment by hostep** [comment]
Sorry my bad, didn't dig into the git history enough.
The issue does already seem to be fixed by https://github.com/magento/magento2/pull/24086

Sorry about this.
