### ISSUE TITLE
not able to add payment method for placing order

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2497]
when i am calling the api   http://MYHOST/rest/default/V1/carts/142/selected-payment-method, with request data:
 {
    "cartId": "3",
    "method": {
        "method": "checkmo"
    }
}

OR 

 {
    "cartId": "3",
    "method": {
        "method": "banktransfer"
    }
}

OR

 {
    "cartId": "3",
    "method": {
        "method": "cashondelivery"
    }
}

i am getting the error:   

{
    "message": "The requested Payment Method is not available."
}

**Comment by ishakhsuvarov** [comment]
@arunkasyakar Thank you for reporting this.
Please check if the cart you attempting to update has subtotal greater then 0.

**Comment by arunkasyakar** [comment]
@ishakhsuvarov  how to check the subtotal for the cart

**Comment by arunkasyakar** [comment]
i have already added two items in the cart, so the total must be greater then 0

**Comment by arunkasyakar** [comment]
I just checked the subtotal in quote_address table its greater then 0

**Comment by ishakhsuvarov** [comment]
@arunkasyakar In the example above you are using different cartId in url and payload, could you please check that the correct cart id is present in url.

**Comment by arunkasyakar** [comment]
sorry for above mistake but i am using the same cartId for both that is cartId: 142

**Comment by SerhiyShkolyarenko** [comment]
@arunkasyakar could you please check that all methods you use are enabled?
I managed to reproduce error message "The requested Payment Method is not available." in case when the payment method was not enabled on backend Stores->Configuration->Sales->Payment Methods
If payment method is enabled, request is successful for me.

**Comment by pradeepsparx** [comment]
Skip to content
This repository

    Pull requests
    Issues
    Gist

    @pradeepsparx

727
3,229

    2,085

magento/magento2
Code
Issues 1,028
Pull requests 130
Wiki
Pulse
Graphs
not able to add payment method for placing order #2497
Closed
arunkasyakar opened this Issue on 24 Nov 2015 · 6 comments
Labels
CS
Milestone
No milestone
Assignee
@ishakhsuvarov ishakhsuvarov
Notifications

You’re not receiving notifications from this thread.
3 participants
@arunkasyakar
@ishakhsuvarov
@SerhiyShkolyarenko
@arunkasyakar

Pick your reaction
arunkasyakar commented on 24 Nov 2015

when i am calling the api http://MYHOST/rest/default/V1/carts/142/selected-payment-method, with request data:
{
"cartId": "3",
"method": {
"method": "checkmo"
}
}

OR

{
"cartId": "3",
"method": {
"method": "banktransfer"
}
}

OR

{
"cartId": "3",
"method": {
"method": "cashondelivery"
}
}

i am getting the error:

{
"message": "The requested Payment Method is not available."
}
@ishakhsuvarov ishakhsuvarov self-assigned this on 24 Nov 2015
@ishakhsuvarov

Pick your reaction
ishakhsuvarov commented on 24 Nov 2015

@arunkasyakar Thank you for reporting this.
Please check if the cart you attempting to update has subtotal greater then 0.
@ishakhsuvarov ishakhsuvarov added the CS label on 24 Nov 2015
@arunkasyakar

Pick your reaction
arunkasyakar commented on 24 Nov 2015

@ishakhsuvarov how to check the subtotal for the cart
@arunkasyakar

Pick your reaction
arunkasyakar commented on 24 Nov 2015

I just checked the subtotal in quote_address table its greater then 0
@ishakhsuvarov

Pick your reaction
ishakhsuvarov commented on 24 Nov 2015

@arunkasyakar In the example above you are using different cartId in url and payload, could you please check that the correct cart id is present in url.
@arunkasyakar

Pick your reaction
arunkasyakar commented on 24 Nov 2015

sorry for above mistake but i am using the same cartId for both that is cartId: 142
@ishakhsuvarov ishakhsuvarov referenced this issue on 26 Nov 2015
Closed
placing order is not working through REST api call #2517
@SerhiyShkolyarenko

Pick your reaction
SerhiyShkolyarenko commented on 9 Dec 2015

@arunkasyakar could you please check that all methods you use are enabled?
I managed to reproduce error message "The requested Payment Method is not available." in case when the payment method was not enabled on backend Stores->Configuration->Sales->Payment Methods
If payment method is enabled, request is successful for me.
@ishakhsuvarov ishakhsuvarov closed this on 9 Dec 2015
@pradeepsparx

SerhiyShkolyarenko commented on 9 Dec 2015

@arunkasyakar could you please check that all methods you use are enabled?
I managed to reproduce error message "The requested Payment Method is not available." in case when the payment method was not enabled on backend Stores->Configuration->Sales->Payment Methods
If payment method is enabled, request is successful for me.
@ishakhsuvarov ishakhsuvarov closed this on 9 Dec 2015
Styling with Markdown is supported

    Status API Training Shop Blog About 

    © 2016 GitHub, Inc. Terms Privacy Security Contact Help
