### ISSUE TITLE
New Email Template JS Confirm Message Popup Design is not Proper

### ISSUE THREAD

**Issue by RonakParmar** [magento/magento2#24978]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.2.13
3. I have found this issue in Adminhtml, Please follow bellow steps to reproduce the issue.

### Steps to reproduce (*)

1.Login Admin -> Marketing
2. Under Communication Section -> Open Email Templates and Newsletter Templates both in different browser tab.
3. Click on Add New Template button on both the views.
4. Click on Convert to Plain Text button.
5. Observe the js Confirmation Popup of both the views is different.

### Expected result (*)

1. The js Confirm message popup should be same as New Newsletter Template view.
2.
![Screenshot from 2019-10-11 14-24-29](https://user-images.githubusercontent.com/6551912/66638873-685e2b80-ec33-11e9-8d9a-c6726cda077e.png)

### Actual result (*)

1. It is not as per the other view.
2.
![Screenshot from 2019-10-11 14-24-25](https://user-images.githubusercontent.com/6551912/66638902-7449ed80-ec33-11e9-9d50-20f6dffe1ff2.png)

### Triage Note
- The issue is reproducible on `2.3.3` release version
- The issue is NOT reproducible on `2.3-develop`
- `2.3.3` is not merged into `2.3-develop` at this moment

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21711` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [Magento instance](https://i-24978-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24978-2-3-develop.instances.magento-community.engineering/admin](https://i-24978-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by saark-akash** [comment]
give me 2.3-develop instance

**Comment by saark-akash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @akashwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @akashwebkul, here is your [Magento instance](https://i-24978-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24978-2-3-develop.instances.magento-community.engineering/admin](https://i-24978-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
issue fixed in magento 2.3-develop.

**Comment by krishprakash** [comment]
Hi @ayazwebkul,
Already mentioned the issue is not reproduced in 2.3 develop and produced in 2.3.3
So review the issue description.
Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21764` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@krishprakash I mentioned that the issue is already fixed in 2.3-develop so doesn't require any action, the fix will be available in the next release. please check: https://github.com/magento/magento2/issues/24978#issuecomment-541305785

**Comment by krishprakash** [comment]
@ayazwebkul Once 2.3.3 merge into 2.3 develop then after will review it and close it.
Thanks

**Comment by krishprakash** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24978-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-24978-2-3-3.instances.magento-community.engineering/admin](https://i-24978-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
**Note:**
Issue is reproduced on 2.3.3 instance.

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-24978-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24978-2-4-develop.instances.magento-community.engineering/admin_756a](https://i-24978-2-4-develop.instances.magento-community.engineering/admin_756a)
Login: `c826255e` Password: `840eece67064`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Verified on the latest `2.4-develop` and using supported browsers https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements_browsers.html?itm_source=devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=browse

Not able to reproduce it now. Seems it was already fixed in the scope of another issue
