### ISSUE TITLE
Incorrect @var reference in docBlock of a class member variable

### ISSUE THREAD

**Issue by salmanazeez786** [magento/magento2#24971]
There is an incorrect @var reference in the doc block of the class member  variable **$queueIterator**  in class 
**\Magento\Framework\MessageQueue\Topology\Config**

### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Check the doc block of this class member variable \Magento\Framework\MessageQueue\Topology\Config::$queueIterator in file vendor/magento/framework-message-queue/Topology/Config.php

### Expected result (*)

![expected](https://user-images.githubusercontent.com/8183885/66632940-478fd900-ec27-11e9-9df6-31036842fe38.PNG)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/8183885/66632945-4c548d00-ec27-11e9-83af-cdcaaa52faec.PNG)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21708` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
@salmanazeez786 
Thank you for reporting this issue Please create Pull request for it's correction 
you can check guide for contribution
https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html

**Comment by salmanazeez786** [comment]
> @salmanazeez786
> Thank you for reporting this issue Please create Pull request for it's correction
> you can check guide for contribution
> https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html

@shikhamis11 

@UncleTioma  has created the pull request - https://github.com/magento/magento2/pull/24976

Do you still want me to create a new pull request ?

**Comment by magento-engcom-team** [comment]
Hi @salmanazeez786. Thank you for your report. 
The issue has been fixed in magento/magento2#24976 by @UncleTioma in 2.4-develop branch
Related commit(s):
 - [4c23a16eb20505a61edf317a1f6e75307aa6c05f](https://github.com/magento/magento2/commit/4c23a16eb20505a61edf317a1f6e75307aa6c05f)
 - [acb45f60b6cc825b4c7eccc7d06f7c9065c62291](https://github.com/magento/magento2/commit/acb45f60b6cc825b4c7eccc7d06f7c9065c62291)

The fix will be available with the upcoming 2.4.0 release.
