### ISSUE TITLE
Catalog price rule for groups does not work

### ISSUE THREAD

**Issue by amon81** [magento/magento2#24982]
### Preconditions

1. Magento 2.2.8
2. Nginx 1.12.2
3. MySql 5.6
4. Single Store

### Steps to reproduce
1. Create a new user group eg pippo
2. Create a new price rule with the name "Pippo discount" with the following parameters:
2.1. Status: Active
2.2. Siteweb: MainWebsite
2.3. Customer's Group: Pippo
2.4. From: 01/01/2017
2.5. To: 01/01/2056
2.6. Priority: X (I also tried 10)
2.7. Conditions: nothing
2.8. Actions:
     2.8.1. Apply: Apply as a percentage from the original
     2.8.2. Quantity discount: 30
     2.8.3. Discard the following rules: No
3. Reindex data with the CLI command
4. Clear Magento Cache with clean and flush CLI command

### Expected result
1. See the prices changed with the discount percentage for the Pippo group
2. https://ibb.co/s3XMrNs

### Actual result
1. https://ibb.co/s3XMrNs

It doesn't just seem like ONLY a browser cache problem.
If I go out and return with a Pippo group account in a new window in anonymous mode, sometimes I can see the discount, others not.
Same thing from the administration panel of the backend, if i change assigning a generic group to the test user (that is, without discounting rules), I continue to see the discounted prices in case I managed to show such discounts before forcing cache etc.
Is there a solution according to you?

**Comment by amon81** [comment]
Issue: Clear Description

**Comment by amon81** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amon81. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amon81, here is your [Magento instance](https://i-24982-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24982-2-3-develop.instances.magento-community.engineering/admin](https://i-24982-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amon81** [comment]
Ok, thanks, I've seen that only after logout procedure and relogin i see the tjhe correct rule price applyied. 
I think it's correct way.
thanks
