### ISSUE TITLE
Email transport builder does not add multiple recipients, when calling the ->addTo(..) for the first time

### ISSUE THREAD

**Issue by skybreaker85** [magento/magento2#24984]
### Preconditions (*)

1. Magento CE 2.3.3
2. A custom module to send E-Mails

### Steps to reproduce (*)
1. You cannot reproduce the Bug in a Vanilla Magento (see below "Expected result" for a comment on this)
2. Still, its a bug inside the Magento Framework Component, so i consider it a bug in the core Magento
3. Install the vanilla Magento 2.3.3
4. Implement a Custom Module (You know how it works, i do not write it down here)
5. Implement a class, where an Email will be sent and execute it
e.g.:
```
class Email
{
    /**
     * the builder to send mails
     * @var \Magento\Framework\Mail\Template\TransportBuilder
     */
    protected $_transportBuilder;

    /**
     * gather dependencies
     */
    public function __construct(
            \Magento\Framework\Mail\Template\TransportBuilder $transportBuilder
    ) {
        $this->_transportBuilder = $transportBuilder;
    }

    /**
     * the method where the error will happen
     */
    public function getTransportObject(
            string $template,
            array $templateVariables,
            array $recipients,
            $from = 'general',
            $area = \Magento\Framework\App\Area::AREA_FRONTEND,
            $store = \Magento\Store\Model\Store::DEFAULT_STORE_ID
    ) {
        //set data for the builder
        $this->_transportBuilder
                ->setTemplateIdentifier($template)
                ->setTemplateOptions(
                        [
                            'area' => $area,
                            'store' => $store,
                        ]
                )
                ->setTemplateVars($templateVariables)
                ->setFrom($from)
        //this does not break here, BUT it wont be accepted (there is no
        //  "to" data entry after this call)
                ->addTo($recipients);
        //due to a bug in 
        //  Magento\Framework\Mail\Template\TransportBuilder::addAddressByType(..)
        //  we cannot add the array'ed emails, because when there is no "to" set,
        //  yet... this add will be ignored
        //  -> for now, we have to loop our recipienht mails and add them via "string",
        //  which still works
        foreach ($recipients as $recipient)
        {
            $this->_transportBuilder->addTo($recipient);
        }
        //finally, this line will crash, because when you'll have a look into the
        //  $this->messageData array, when the message will be prepared, the "to" is not
        //  there. Its already not there, after the above called ->addTo(..)
        return $this->_transportBuilder->getTransport();
    }
```

### Expected result (*)
1. The "to" data should be set inside the message data and should be populated after the call to ->addTo(..) containing an array of recipients
2. a Unit Test, testing the ->addTo(..) with multiple recipients (currently there is just a test for adding one recipient)

A Comment on "Steps to Reproduce 1.":
I didnt find a call to ->addTo(..) containing multiple recipients, within the whole magento core code. So maybe, you dont want to allow that, but still. the framework has this option, so it should work (and did previously)

### Actual result (*)
1. there is no data that fits the "to"
2. it should work, like it already worked before (adding recipients via array)

**Hint:**
It seems, the concerned code was changed in the MC-15295 Ticket? The commit was: 2b77950a48fd301c84343b585b9d923fcf1e6444

**Comment by webkul-ratnesh** [comment]
@magento i am working on it

**Comment by vpietri-tbd** [comment]
Have an issue in place order if "Send Order Email Copy To" is defined in configuration
`"Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Email\\Model\\Template::setVars() must be of the type array, null given`

**Comment by webkul-ratnesh** [comment]
> Have an issue in place order if "Send Order Email Copy To" is defined in configuration
> `"Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Email\\Model\\Template::setVars() must be of the type array, null given`

I have not found this issue in 2.3-develop branch.

**Comment by webkul-ratnesh** [comment]
Unable to reproduce the issue mentioned in description.

**Comment by elvinristi** [comment]
@skybreaker85 this is solved in ongoing PR: https://github.com/magento/magento2/pull/24855

**Comment by skybreaker85** [comment]
@elvinristi thank you very much. I was just about to write a comment (with a sample module) on how to recreate this issue.

Thanks for the hint on this PR, i havent found that one as of the time of my original post.

@webkul-ratnesh, sorry for the inconvenience

**Comment by tanolalano** [comment]
Same issue to me!
Magento CE 2.3.3

**Comment by leosingh44** [comment]
How is the issue closed?

Just to update in my case the issue was related to 

`->addTo($emails)`

I checked this and found it was in 

> vendor/magento/framework/Mail/Template/TransportBuilder.php

So I added a small check in the function 

Replace 

```
public function addTo($address, $name = '')
    {
        $this->addAddressByType('to', $address, $name);

        return $this;
    }
```
To

```
public function addTo($address, $name = '')
    {
        if(is_array($address)){
            foreach ($address as $key => $email) {
                $this->addAddressByType('to', trim($email), $name);        
            }
        } else{
            $this->addAddressByType('to', $address, $name);
        }    
        return $this;
    }
```

**Comment by skybreaker85** [comment]
@leosingh44
What you are about to do in your code is indeed fixed. Your Question:
> 
> How is the issue closed?

And your suggestion
```
     public function addTo($address, $name = '')
     {
         if(is_array($address)){
             foreach ($address as $key => $email) {
                 $this->addAddressByType('to', trim($email), $name);        
             }
         } else{
             $this->addAddressByType('to', $address, $name);
         }    
         return $this;
     }
```

Is no longer needed, because the method: `->addAddressByType(..)` now contains this line:
https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php#L431

It indeed does work now, without changes on core files. The Community Edition, has this line too (i checked the current 2.3.4 release), so there is no need to change anything.

**Comment by leosingh44** [comment]
@skybreaker85  I have already applied the same code, but still it didn't hence I wanted to share the fix which I did. 

> @leosingh44
> What you are about to do in your code is indeed fixed. Your Question:
> 
> > How is the issue closed?
> 
> And your suggestion
> 
> ```
>      public function addTo($address, $name = '')
>      {
>          if(is_array($address)){
>              foreach ($address as $key => $email) {
>                  $this->addAddressByType('to', trim($email), $name);        
>              }
>          } else{
>              $this->addAddressByType('to', $address, $name);
>          }    
>          return $this;
>      }
> ```
> 
> Is no longer needed, because the method: `->addAddressByType(..)` now contains this line:
> https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php#L431
> 
> It indeed does work now, without changes on core files. The Community Edition, has this line too (i checked the current 2.3.4 release), so there is no need to change anything.

I tried that already but didn't worked for me, and hence I came up with the code that I shared.

**Comment by flamboy** [comment]
Present on M 2.3.3-p1
https://i.imgur.com/L18H5YR.png
