### ISSUE TITLE
What is the officially recommended way to protect the modified .htaccess files in a composer install from being overwritten later? 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2498]
For example, the `.htaccess` files could be modified (the `mod_rewrite` section) to [setup Magento a into a subdirectory](https://mage2.pro/t/topic/23).
What is the officially recommended way to preserve such modifications from being overwritten later?

**Comment by maksek** [comment]
Please submit question in Magento forum, GitHub only for issue reporting and PR.
