### ISSUE TITLE
Decimal tier price discount 0.5 not saved in the Magento Admin

### ISSUE THREAD

**Issue by proudnerduser88** [magento/magento2#24995]
Decimal tier price discount 0.5 not saved in the Magento Admin. When we use the API POST {base_url}/rest/all/V1/products/tier-prices, the 0.5 is saved correctly.

### Preconditions (*)
1. Magento 2.2.8
2. PHP 7.1

### Steps to reproduce (*)
Create product with tier price discount 0.5%

### Expected result (*)
Product must have the 0.5% tier price discount saved.

### Actual result (*)
Product has saved and changed the tier price 0.5% discount back on fixed 0%.

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24995-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24995-2-3-develop.instances.magento-community.engineering/admin](https://i-24995-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hello @proudnerduser88 
Thanks for reporting this issue but I am not able to reproduce this issue on magento 2.3-develop instance. I tried adding tier price for discount price type with decimal values and I am able to successfully create it with magento 2 backend as well as with APIs. 
Please check the issue at latest magento 2 versions and also share screenshots if you are able to find the issue

**Comment by proudnerduser88** [comment]
@shikhamis11  Thanks for checking, what decimal value have you tried? Because above 0 it works, but 0.5 it does not.
