### ISSUE TITLE
Action submenu css issue in customer group listing gird

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24999]
### Preconditions (*)

Magento 2.3.x is required.

### Steps to reproduce (*)

1. Add new columns in the customer group listing grid.
2. Open the action dropdown.

### Expected result (*)

1. The dropdown must be there just after the listing arrow.
![image](https://user-images.githubusercontent.com/56463897/66696204-8a18ea80-ece7-11e9-8357-53cf272893e0.png)

### Actual result (*)

1. The dropdown is at the right corner of the screen.
![image](https://user-images.githubusercontent.com/56463897/66696214-a0bf4180-ece7-11e9-89a4-d96c837eca9c.png)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @vishesh-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vishesh-webkul, here is your [Magento instance](https://i-24999-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24999-2-3-develop.instances.magento-community.engineering/admin](https://i-24999-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@ayazwebkul Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by mahesh-rajawat** [comment]
Duplicate issue: #23024

**Comment by krishprakash** [comment]
Hi @vishesh-webkul. Thank you for your report.
Closing this issue as this is duplicate to #23024 and issue is already open.
