### ISSUE TITLE
'Parse error: syntax error, unexpected end of file' due to open PHP tag

### ISSUE THREAD

**Issue by yeevy** [magento/magento2#24992]
### Preconditions (*)
This error is happening after updating to 2.2.10.
It seems this commit (https://github.com/magento/magento2/commit/7f346f38a54d0d5f2ff7a3c1a6cbbdf0aa3c338f) introduced loads of open PHP tags. Not sure why this is, it's not been done on the 2.3.x branch ...
Admin/backend loads, just frontend which is broken

### Steps to reproduce (*)
Not sure; updated from 2.2.9 to 2.2.10 and just deployed the changes to my Staging env.

### Expected result (*)
No errors, site should just load the homepage correctly.

### Actual result (*)
When trying to load the homepage I get a single error message;
`Parse error: syntax error, unexpected end of file in /...project-path.../http/var/view_preprocessed/pub/static/vendor/magento/module-reports/view/frontend/templates/js/components.phtml on line 1`

**Comment by yeevy** [comment]
@magento give me 2.2.10 instance

**Comment by magento-engcom-team** [comment]
Hi @yeevy. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by vivekkumar945744** [comment]
@magento I am working on it

**Comment by jissereitsma** [comment]
Two things that strike me about this bug, without knowing the actual solution yet: One, the PHTML file that throws the error is "minified" (so it becomes a single line with 2 opening tags). Two, why is this PHTML template copied to a `var/view_preprocessed/pub/static` folder anyway, while it should never end up in the folder `pub` because it is not a web-accessible file?

Did somebody create a deployment trick that minifies any (!) file that resides in any (!) `js` folder?

**Comment by petemcw** [comment]
This was quite the bug to track down. Running 2.2.10 in developer mode works fine but as soon as you switch to default or production mode, the problems start. Luckily, we caught it before any production merges/deployments.

How long do you figure we will have to wait for a patch?

**Comment by tiacocstoe** [comment]
Hi, same problem here. Quick fix is to override few files from modules view in a theme folder. 
Copy the files and remove <?php from the end of it.

**Comment by petemcw** [comment]
I started going that direction @tiacocstoe but found that there were so many. I ended up making a patch that runs as part of our deployment process. Here is [a link to the patch](https://gist.github.com/petemcw/3999fe86f7651838e54f5cca3cfab1cd) if anyone needs it until Magento fixes the issue.

**Comment by tiacocstoe** [comment]
Well @petemcw  as far as i can tell You're doing exactly same as i suggested but directlu in a core files. I'd rather do this my way, but suit Yourself :)
Still, it's a nasty bug and should never apear

**Comment by nickua** [comment]
Here is a simple script that will fix end of line `<?php` issue in core files
 **IMPORTANT: do not run it on production server**
For Mac OS
```bash
subj='<?php'
for file in `grep -rl "$subj" vendor/magento`; do
LINE_END=`tail -n 1 $file | grep -e $subj'$'`

if [[ -n $LINE_END ]]; then
echo $file;
sed -i '' -e '$ d'  $file;
fi

done
```

for Linux
```bash
subj='<?php'
for file in `grep -rl "$subj" vendor/magento`; do
LINE_END=`tail -n 1 $file | grep -e $subj'$'`

if [[ -n $LINE_END ]]; then
echo $file;
sed -i '$ d'  $file;
fi

done
```

**Comment by engcom-Charlie** [comment]
Hello @yeevy 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details.

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Comment by AndreiAghenii** [comment]
Hello Guys,

I have absolutely same issue after updating from 2.2.9 to 2.2.10.  Is there a solution to that issue? 

Sincerely,
Andrei.

**Comment by engcom-Charlie** [comment]
Hello @SigmaAndrei 
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

**Comment by AndreiAghenii** [comment]
@engcom-Charlie I tried to use the patch that @petemcw provided, but it doesn't work for cloud, maybe you guys have another thread I can look at?

**Comment by 0x15f** [comment]
Attached a patch that I tested on a Magento Cloud environment.

https://kayser-roth-public.s3.amazonaws.com/25551.patch

**Comment by SigmaAndrei** [comment]
Thank you @0x15f ,

Here is what Magento provided: 
diff --git a/vendor/magento/module-captcha/view/frontend/templates/js/components.phtml b/vendor/magento/module-captcha/view/frontend/templates/js/components.phtml
index 8e13059b231..1bd7e554a73 100644
--- a/vendor/magento/module-captcha/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-captcha/view/frontend/templates/js/components.phtml
@@ -5,4 +5,4 @@
  */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
+
diff --git a/vendor/magento/module-customer/view/frontend/templates/js/components.phtml b/vendor/magento/module-customer/view/frontend/templates/js/components.phtml
index 8e13059b231..1bd7e554a73 100644
--- a/vendor/magento/module-customer/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-customer/view/frontend/templates/js/components.phtml
@@ -5,4 +5,4 @@
  */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
+
diff --git a/vendor/magento/module-newsletter/view/adminhtml/templates/queue/list.phtml b/vendor/magento/module-newsletter/view/adminhtml/templates/queue/list.phtml
index 463417ff9f2..c0928f4723b 100644
--- a/vendor/magento/module-newsletter/view/adminhtml/templates/queue/list.phtml
+++ b/vendor/magento/module-newsletter/view/adminhtml/templates/queue/list.phtml
@@ -5,4 +5,3 @@
  */
 ?>
 <?= $block->getChildHtml('grid') ?>
-<?php
diff --git a/vendor/magento/module-newsletter/view/adminhtml/templates/template/list.phtml b/vendor/magento/module-newsletter/view/adminhtml/templates/template/list.phtml
index 463417ff9f2..c0928f4723b 100644
--- a/vendor/magento/module-newsletter/view/adminhtml/templates/template/list.phtml
+++ b/vendor/magento/module-newsletter/view/adminhtml/templates/template/list.phtml
@@ -5,4 +5,3 @@
  */
 ?>
 <?= $block->getChildHtml('grid') ?>
-<?php
diff --git a/vendor/magento/module-newsletter/view/frontend/templates/js/components.phtml b/vendor/magento/module-newsletter/view/frontend/templates/js/components.phtml
index 8e13059b231..5902a9f25cc 100644
--- a/vendor/magento/module-newsletter/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-newsletter/view/frontend/templates/js/components.phtml
@@ -5,4 +5,3 @@
  */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
diff --git a/vendor/magento/module-page-cache/view/frontend/templates/js/components.phtml b/vendor/magento/module-page-cache/view/frontend/templates/js/components.phtml
index 87de3a60afc..10d1a05a6ec 100644
--- a/vendor/magento/module-page-cache/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-page-cache/view/frontend/templates/js/components.phtml
@@ -7,4 +7,4 @@
 /** @var \Magento\Framework\View\Element\Js\Components $block */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
+
diff --git a/vendor/magento/module-paypal/view/frontend/templates/js/components.phtml b/vendor/magento/module-paypal/view/frontend/templates/js/components.phtml
index 8e13059b231..5902a9f25cc 100644
--- a/vendor/magento/module-paypal/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-paypal/view/frontend/templates/js/components.phtml
@@ -5,4 +5,3 @@
  */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
diff --git a/vendor/magento/module-reports/view/frontend/templates/js/components.phtml b/vendor/magento/module-reports/view/frontend/templates/js/components.phtml
index 8e13059b231..5902a9f25cc 100644
--- a/vendor/magento/module-reports/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-reports/view/frontend/templates/js/components.phtml
@@ -5,4 +5,3 @@
  */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
diff --git a/vendor/magento/module-wishlist/view/frontend/templates/js/components.phtml b/vendor/magento/module-wishlist/view/frontend/templates/js/components.phtml
index 8e13059b231..5902a9f25cc 100644
--- a/vendor/magento/module-wishlist/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-wishlist/view/frontend/templates/js/components.phtml
@@ -5,4 +5,3 @@
  */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
diff --git a/vendor/magento/module-customer-segment/view/adminhtml/templates/report/detail/grid/container.phtml b/vendor/magento/module-customer-segment/view/adminhtml/templates/report/detail/grid/container.phtml
index 56e983f667a..2d3ac905011 100644
--- a/vendor/magento/module-customer-segment/view/adminhtml/templates/report/detail/grid/container.phtml
+++ b/vendor/magento/module-customer-segment/view/adminhtml/templates/report/detail/grid/container.phtml
@@ -9,4 +9,3 @@
  */
 ?>
 <?= $block->getGridHtml() ?>
-<?php
diff --git a/vendor/magento/module-cybersource/view/frontend/templates/js/components.phtml b/vendor/magento/module-cybersource/view/frontend/templates/js/components.phtml
index 8e13059b231..5902a9f25cc 100644
--- a/vendor/magento/module-cybersource/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-cybersource/view/frontend/templates/js/components.phtml
@@ -5,4 +5,3 @@
  */
 ?>
 <?= $block->getChildHtml() ?>
-<?php
diff --git a/vendor/magento/module-gift-card-account/view/frontend/templates/js/components.phtml b/vendor/magento/module-gift-card-account/view/frontend/templates/js/components.phtml
index bb24132ae92..6cf15f47701 100644
--- a/vendor/magento/module-gift-card-account/view/frontend/templates/js/components.phtml
+++ b/vendor/magento/module-gift-card-account/view/frontend/templates/js/components.phtml
@@ -6,4 +6,3 @@
 
 ?>
 <?= $block->getChildHtml() ?>
-<?php
diff --git a/vendor/magento/module-reward/view/adminhtml/templates/customer/edit/management.phtml b/vendor/magento/module-reward/view/adminhtml/templates/customer/edit/management.phtml
index 5b1a1932914..b4393fa1298 100644
--- a/vendor/magento/module-reward/view/adminhtml/templates/customer/edit/management.phtml
+++ b/vendor/magento/module-reward/view/adminhtml/templates/customer/edit/management.phtml
@@ -7,4 +7,3 @@
 ?>
 <?= $block->getChildHtml('balance') ?>
 <?= $block->getChildHtml('update') ?>
-<?php
diff --git a/vendor/magento/module-reward/view/adminhtml/templates/customer/reward.phtml b/vendor/magento/module-reward/view/adminhtml/templates/customer/reward.phtml
index 843d15f6fac..7d6d7e01e47 100644
--- a/vendor/magento/module-reward/view/adminhtml/templates/customer/reward.phtml
+++ b/vendor/magento/module-reward/view/adminhtml/templates/customer/reward.phtml
@@ -7,4 +7,3 @@
 ?>
 <?= $block->getChildHtml('reward_management') ?>
 <?= $block->getChildHtml('history_accordion') ?>
-<?php
diff --git a/vendor/magento/module-versions-cms/view/frontend/templates/hierarchy/menu.phtml b/vendor/magento/module-versions-cms/view/frontend/templates/hierarchy/menu.phtml
index 4dc117f5a82..85efc2e8ef1 100644
--- a/vendor/magento/module-versions-cms/view/frontend/templates/hierarchy/menu.phtml
+++ b/vendor/magento/module-versions-cms/view/frontend/templates/hierarchy/menu.phtml
@@ -12,4 +12,3 @@ $_menu = $block->drawMenu($_tree);
 <?php if ($block->geMenuNodesQty() > 1) : ?>
     <?= /* @noEscape */ $_menu ?>
 <?php endif; ?>
-<?php

Sincerely,
Andrei

**Comment by mrichard-abso** [comment]
Having the same issue on our Magento Cloud 2.2.10, and unable to reproduce on a local machine. We've added @0x15f 's patch, and works great.

**Comment by Duong-146** [comment]
When I change my email in local repository, it not change and have error is: line 420: syntax error: unexpected end of file
This is line 419 and line 420 in file what had error
eval "$filter_env" < /dev/null ||
		die "env filter failed: $filter_env"
I hope fixing it. Thanks people ^^

**Comment by 0x15f** [comment]
> When I change my email in local repository, it not change and have error is: line 420: syntax error: unexpected end of file
> This is line 419 and line 420 in file what had error
> eval "$filter_env" < /dev/null ||
> die "env filter failed: $filter_env"
> I hope fixing it. Thanks people ^^

What file had this error?

**Comment by Duong-146** [comment]
git-filter-branch line 420, can you give me this file for comparing ?
