### ISSUE TITLE
Reviews not displaying on Product Page

### ISSUE THREAD

**Issue by igormatkovic** [magento/magento2#24997]
### Preconditions (*)
1. Magento 2.3.3 (Upgraded from 2.3.2)
2. Ubuntu 18.04 (Nginx/Php7.3/Redis/OpCache)

### Steps to reproduce (*)
1. Open a single product page that has published reviews
2 The reviews are not displayed in the small summary section

### Expected result (*)
1. Review stars should be visible

### Actual result (*)
1. Reviews are not visible

After a bit of investigation I located the culprits:

[ReviewRendered#L121](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Review/Block/Product/ReviewRenderer.php#L121)
[ReviewRendered#L131](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Review/Block/Product/ReviewRenderer.php#L121)

```
/**
     * Get ratings summary
     *
     * @return string
     */
    public function getRatingSummary()
    {
        return $this->getProduct()->getRatingSummary();
    }
    /**
     * Get count of reviews
     *
     * @return int
     */
    public function getReviewsCount()
    {
        return $this->getProduct()->getReviewsCount();
    }

```

The two methods above don't return what's expected.

The First Method: **getRatingSummary()** actually returns the Rating Summary DataObject
Example dump
```
object(Magento\Framework\DataObject)#2138 (1) {
["_data":protected]=>
  array(6) {
    ["primary_id"]=> string(1) "2"
    ["entity_pk_value"]=> string(1) "1"
    ["entity_type"]=> string(1) "1"
    ["reviews_count"]=> string(3) "152"
    ["rating_summary"]=> string(2) "96"
    ["store_id"]=> string(1) "1"
  }
}

```

While the second method **getReviewsCount()** just returns NULL.

After updating those two methods to look like this it started to work as expected.

```
/**
     * Get ratings summary
     *
     * @return string
     */
    public function getRatingSummary()
    {
        return $this->getProduct()->getRatingSummary()->getRatingSummary();
    }
    /**
     * Get count of reviews
     *
     * @return int
     */
    public function getReviewsCount()
    {
        return $this->getProduct()->getRatingSummary()->getReviewsCount();
    }
```

**Comment by igormatkovic** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @igormatkovic. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @igormatkovic, here is your [Magento instance](https://i-24997-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24997-2-3-develop.instances.magento-community.engineering/admin](https://i-24997-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by igormatkovic** [comment]
Cant replicate with vanilla. So it's probably an extension messing with me. Closing ticket
