### ISSUE TITLE
Missing Magento\Shipping\Model\Rate\Result\ProxyDeferredFactory causes setup:di:compile to fail

### ISSUE THREAD

**Issue by twoonesixdigital** [magento/magento2#24993]
### Preconditions (*)

1. Magento Open Source 2.3.3
2. Apache 2.4.29
3. PHP 7.2.19
4. MySQL 5.7.27
5. Single Store
6. Composer installation method
7. Instance Mode: Developer

### Steps to reproduce (*)

1. Perform a composer magento version update from Magento 2.3.2 to Magento 2.3.3 using a composer.json that requires magento/product-community-edition 2.3.3
2. Execute the command magento setup:upgrade
3. Execute the command magento setup:di:compile

### Expected result (*)

1. Magento should recompile and regenerate the required generated code successfully.

### Actual result (*)

1. The Magento executable throws the following error: "In ClassReader.php line 41: Class Magento\Shipping\Model\Rate\Result\ProxyDeferredFactory does not exist"

We found the following models attempting to use the Magento\Shipping\Model\Rate\Result\ProxyDeferredFactory class as parameters in their constructors:
	1. Magento\Usps\Model\Carrier
	2. Magento\Dhl\Model\Carrier
	3. Magento\Dhl\Model\Ups\Carrier

Upon further review, the class Magento\Shipping\Model\Rate\Result\ProxyDeferredFactory does not appear to exist in the codebase. We did however find the class Magento\Framework\Async\ProxyDeferredFactory. We updated the 3 shipping models to use that class rather than the missing class and were able to successfully execute the compile command.

Is this a typo in those shipping models or is Magento\Shipping\Model\Rate\Result\ProxyDeferredFactory truly meant to be a different class than Magento\Framework\Async\ProxyDeferredFactory and it's simply missing from the distribution?

**Comment by twoonesixdigital** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @twoonesixdigital. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @twoonesixdigital, here is your [Magento instance](https://i-24993-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24993-2-3-develop.instances.magento-community.engineering/admin](https://i-24993-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by twoonesixdigital** [comment]
As the issue relates to Magento CLI behavior, the vanilla Magento instance testing does not seem relevant nor practical.

**Comment by fascinosum** [comment]
@twoonesixdigital, have you tried to reproduce this issue using recommended flow https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html. Please add an instance mode in the description

**Comment by fascinosum** [comment]
`Magento\Shipping\Model\Rate\Result\ProxyDeferredFactory` is auto-generated class

**Comment by shahbaztariq** [comment]
I see a similar issue but with the following:

```
Fatal error:  Interface 'Vertex\Tax\Model\Flexfield\Processor\TaxCalculationFlexFieldProcessorInterface' not found in /www/releases/20191012162644/vendor/vertex/module-tax/Model/FlexField/Processor/OrderCurrencyGetterProcessor.php on line 24
```

**Comment by hostep** [comment]
@shahbaztariq: that's something completely different, you can follow https://github.com/magento/magento2/issues/24930 for that one (there is a patch in there which should fix the problem).

**Comment by shahbaztariq** [comment]
@hostep thanks for that... I was searching for that but must not have tried hard enough. 

Much appreciated!

**Comment by tiberiucontiu** [comment]
I have exactly the same problem:

![image](https://user-images.githubusercontent.com/2530506/66749096-9a6cc900-ee91-11e9-9492-76a2f67b8f17.png)

The install process uses composer:
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.3`

Any ideas?  Thanks.

**Comment by tiberiucontiu** [comment]
Figure it out by myself: in my case, some parts of the code were taken from other repo. The di.xml from app/etc/di.xml was not the M233 version but M232. It seems that di.xml in M233 has some relevant changes. So, if your project is created from different repositories - like mine -, make sure both contain the latest M233 code.

**Comment by twoonesixdigital** [comment]
> Figure it out by myself: in my case, some parts of the code were taken from other repo. The di.xml from app/etc/di.xml was not the M233 version but M232. It seems that di.xml in M233 has some relevant changes. So, if your project is created from different repositories - like mine -, make sure both contain the latest M233 code.

Great catch @tiberiucontiu  This was my problem as well. You made my day, thank you.

I believe this issue can now be closed. It was indeed a result of a non-standard /app/etc/di.xml file.

**Comment by webspeaks** [comment]
> Figure it out by myself: in my case, some parts of the code were taken from other repo. The di.xml from app/etc/di.xml was not the M233 version but M232. It seems that di.xml in M233 has some relevant changes. So, if your project is created from different repositories - like mine -, make sure both contain the latest M233 code.

It solved the issue for me in Magento 2.3.4-p2. Wonder why this file was not upgraded when I rain `composer update`?
Also there is no mention of it in the official docs!

**Comment by tiberiucontiu** [comment]
> > Figure it out by myself: in my case, some parts of the code were taken from other repo. The di.xml from app/etc/di.xml was not the M233 version but M232. It seems that di.xml in M233 has some relevant changes. So, if your project is created from different repositories - like mine -, make sure both contain the latest M233 code.
> 
> It solved the issue for me in Magento 2.3.4-p2. Wonder why this file was not upgraded when I ran `composer update`?
> Also there is no mention of it in the official docs!

When you run composer update, the files from app/etc, including di.xml, aren't affected.
Composer update affects only the vendor/ folder, based on composer.json configuration.

**Comment by hostep** [comment]
@tiberiucontiu: that's not correct.

When the `magento/magento2-base` module gets updated using composer, all files from in there are getting copied to the root directory (including that `di.xml` file), this happens because of this composer plugin: https://github.com/magento/magento-composer-installer
Magento calls this process "marshalling".

If the `app/etc/di.xml`  file doesn't get updated, it means an error occurred in the composer plugin and it didn't tell you about it. This might be related to https://github.com/magento/magento2/issues/10292

**Comment by tiberiucontiu** [comment]
@hostep You're right!

**Comment by quannguyenbkat** [comment]
> Figure it out by myself: in my case, some parts of the code were taken from other repo. The di.xml from app/etc/di.xml was not the M233 version but M232. It seems that di.xml in M233 has some relevant changes. So, if your project is created from different repositories - like mine -, make sure both contain the latest M233 code.

Thank you very much. you save my day
