### ISSUE TITLE
Invoice,Order Shipment - Print Slip at front end

### ISSUE THREAD

**Issue by hi-soni** [magento/magento2#2500]
I could not find any option to print Invoice,Order Shipment under my account > Order detail page.

There is one called "print" on order details page, but it always took me to print order details page only.

![order 000000003](https://cloud.githubusercontent.com/assets/4537207/11369406/b6799270-92e4-11e5-9627-04d3f3bed55d.png)

**Comment by NadiyaS** [comment]
Hi, @hirensoni2005 
Internal issue was created MAGETWO-46328

**Comment by hi-soni** [comment]
Thank you for update.

**Comment by NadiyaS** [comment]
Hi @hirensoni2005,
fix was delivered to mainline.

**Comment by davidalger** [comment]
Closing as this is fixed in mainline. Please re-open if you re-encounter the bug. Thanks again for reporting it!

**Comment by hi-soni** [comment]
Thank you @NadiyaS & @davidalger for updates.

**Comment by EnigmaWebdesign** [comment]
Hi all,

I have Magento 2.2.7 and I have the same issue as hirensoni2005.

Where can I find the code which needs fixing?

Br,

Steve
