### ISSUE TITLE
The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/magento/google-shopping-ads/magento-google-shopping-ads-3.0.1.0.zip)

### ISSUE THREAD

**Issue by DominicWatts** [magento/magento2#25028]
### Preconditions (*)

Blank Install

### Steps to reproduce (*)

composer install with 2.3.3 

```
  - Installing magento/google-shopping-ads (3.0.1): Downloading (100%)         
                                                                               
  [UnexpectedValueException]                                                   
  The checksum verification of the file failed (downloaded from https://repo.  
  magento.com/archives/magento/google-shopping-ads/magento-google-shopping-ad  
  s-3.0.1.0.zip)                                                               
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

```composer.lock
{
            "name": "magento/google-shopping-ads",
            "version": "3.0.1",
            "dist": {
                "type": "zip",
                "url": "https://repo.magento.com/archives/magento/google-shopping-ads/magento-google-shopping-ads-3.0.1.0.zip",
                "reference": null,
                "shasum": "5f5929ef9f2ec4ca048a2add261d22c92807630f"
            },
            "require": {
                "guzzlehttp/guzzle": ">=6.0",
                "guzzlehttp/psr7": "~1.0",
                "magento/framework": ">=101.0.4",
                "magento/module-backend": ">=100.2.4",
                "magento/module-bundle": ">=100.2.3",
                "magento/module-catalog": ">=102.0.4",
                "magento/module-catalog-inventory": ">=100.2.3",
                "magento/module-checkout": ">=100.2.4",
                "magento/module-config": ">=101.0.4",
                "magento/module-configurable-product": ">=100.2.4",
                "magento/module-directory": ">=100.2.3",
                "magento/module-downloadable": ">=100.2.3",
                "magento/module-eav": ">=101.0.3",
                "magento/module-store": ">=100.2.3",
                "magento/module-ui": ">=101.0.4",
                "php": "7.0.2||7.0.4||>=7.0.6 <7.4"
            },
            "type": "magento2-module",
            "autoload": {
                "files": [
                    "registration.php"
                ],
                "psr-4": {
                    "Magento\\GoogleShoppingAds\\": ""
                }
            },
            "license": [
                "OSL-3.0",
                "AFL-3.0"
            ],
            "description": "Connect your Magento admin with Google Merchant Center and Google Ads. Leverage Google machine learning through Google Smart Shopping campaigns"
        },
```

### Expected result (*)

Composer installs

### Actual result (*)

Composer errors

**Comment by DominicWatts** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DominicWatts. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DominicWatts, here is your [Magento instance](https://i-25028-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25028-2-3-develop.instances.magento-community.engineering/admin](https://i-25028-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DominicWatts** [comment]
Need shell access to confirm (I know not possible with above)

**Comment by markshust** [comment]
I can confirm this bug.

- in the official `Magento-CE-2.3.3.tar.gz` archive, the checksum in the composer.lock file for google-shopping-ads module  is `5f5929ef9f2ec4ca048a2add261d22c92807630f`
- if you create a new Magento 2.3.3 install with composer, the checksum in the composer.lock file for google-shopping-ads module is `ce31e720d60451784b9fdb3769e43e149f50d436`

there seems to be something odd going on in the release process, because these should 100% match each other.

@DominicWatts you can workaround this in the mean time by running:
`sed -e 's/5f5929ef9f2ec4ca048a2add261d22c92807630f/ce31e720d60451784b9fdb3769e43e149f50d436/' composer.lock > composer.lock`

**Comment by magento-engcom-team** [comment]
@markshust Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21823` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by matheusgontijo** [comment]
Hey @markshust, thank you so much for the quick workaround. That helped me a lot! But just a quick heads up. [You can't sed replace the same file.](https://stackoverflow.com/a/5171935/962814) You need to have at least to. Otherwise that would trunk the file. So the snippet code would be:

`sed -e 's/5f5929ef9f2ec4ca048a2add261d22c92807630f/ce31e720d60451784b9fdb3769e43e149f50d436/' composer.lock.bak > composer.lock`

Once again, thanks for your help @markshust!

**Comment by henkvalk** [comment]
I had same in 2.3.3 but the above sed replace is giving an empty file for me. The snippet code for me is:
`sed -i 's/5f5929ef9f2ec4ca048a2add261d22c92807630f/ce31e720d60451784b9fdb3769e43e149f50d436/g' composer.lock`

**Comment by vladthetech** [comment]
Since I am currently not using the Google Shopping Ads Module, I ran the composer remove command which basically changes the same line of code in the `composer.lock` file:
`composer remove magento/google-shopping-ads`

**Comment by rmanor1** [comment]
Hello, this should probably be closed as we've deprecated the Google Shopping ads Channel, and the [service was shut down ](https://docs.magento.com/user-guide/sales-channels/google-eol.html)as of Apr 28th.
