### ISSUE TITLE
add product

### ISSUE THREAD

**Issue by shm379** [magento/magento2#25029]
Notice: Use of undefined constant formName - assumed 'formName' in /home/takdigi/public_html/vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/helper/gallery.phtml on line 64

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by krishprakash** [comment]
Hi @shm379 please explain in which case you phase this issue.
And fill all the details Pre condition, Steps to reproduce, Expected result and Actual result.
All the details are required for issue confirmation
Thanks

**Comment by krishprakash** [comment]
Hi @shm379 
Feel free to reopen the issue once you update all required details.
Thanks

**Comment by hostep** [comment]
It's actually a duplicate of https://github.com/magento/magento2/issues/24968

Which was already fixed by https://github.com/magento/magento2/pull/24086
Fix will most likely be included in Magento 2.3.4

**Comment by Jilco** [comment]
Is there a work around or do i have to wait for 2.3.4 release? Because now i can't edit products...
