### ISSUE TITLE
"New Accounts Report" should disable the sort ability of "New Account" columns (because it can not run)

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25033]
"New Accounts Report" should disable the sort ability of "New Account" columns (because it can not run)

### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Reports-> Customers-> New
3. Show report
4. Click "New Account" column

Check this Gif:

![sort](https://user-images.githubusercontent.com/8234209/66736359-23d0cb00-ee93-11e9-8701-3c1720a478b4.gif)

### Expected result (*)

1. Nothing happened because the column can not be sortable

### Actual result (*)

1. Reload the page and nothing happened

**Comment by vivekkumar945744** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul, here is your [Magento instance](https://i-25033-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25033-2-3-develop.instances.magento-community.engineering/admin](https://i-25033-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21769` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#25034 by @edenduong in 2.3-develop branch
Related commit(s):
 - [f68dd1c700ee64bdb2571c8a64fdc561e710540e](https://github.com/magento/magento2/commit/f68dd1c700ee64bdb2571c8a64fdc561e710540e)

The fix will be available with the upcoming 2.3.4 release.
