### ISSUE TITLE
Product detail did not scroll to review tab after click on 'Review' anchor link

### ISSUE THREAD

**Issue by weeliem** [magento/magento2#25039]
**Preconditions**
1. Magento 2.3.3

**Steps to reproduce**
1. Go to product detail page
2. Click on 'review' or 'add your review' link (http://prntscr.com/pj0bg6)

**Expected result**
1. Auto scroll  to review tab at bottom.

**Actual result**
1. Did not scroll to review tab and encountered javascript error (http://prntscr.com/pj0d4g)

**Suspect**
1. Code issue on line 51-72 of Magento_Review/js/process-reviews.js (http://prntscr.com/pj0djj)

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25039-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25039-2-3-develop.instances.magento-community.engineering/admin](https://i-25039-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21771` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @weeliem. Thank you for your report. 
The issue has been fixed in magento/magento2#25051 by @gauravagarwal1001 in 2.3-develop branch
Related commit(s):
 - [0e02b40eb1b9d20c170328e1028e16857d7473e5](https://github.com/magento/magento2/commit/0e02b40eb1b9d20c170328e1028e16857d7473e5)

The fix will be available with the upcoming 2.3.4 release.

**Comment by bojjaiah** [comment]
@magento-engcom-team @magento-team @m2-backlog @gauravagarwal1001 @shikhamis11  I'm also having the same issue in Magento V2.3.3. Can we have solutions to fix this within MagentoV2.3.3 without the upgrade to Magento V2.3.4 Please suggest to us?

**Comment by jkg1996** [comment]
Any updates on this i am facing the same issue
i get the following error 
`Uncaught Error: cannot call methods on tabs prior to initialization; attempted to call method 'activate'`
