### ISSUE TITLE
"Shopping Cart Summary" in backend is different from frontend, and not following the setting

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25036]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Sign in to Customer
2. Add qty = 6 of 1 item to cart
3. Go to backend
4. Create order with that customer
5. View Shopping Cart

![image](https://user-images.githubusercontent.com/8234209/66741204-2afdd600-ee9f-11e9-8f5d-c76428c73315.png)

![image](https://user-images.githubusercontent.com/8234209/66741238-3c46e280-ee9f-11e9-9660-539bcccb488f.png)

### Expected result (*)

1. The summary is 6 like frontend because the settings is 

![image](https://user-images.githubusercontent.com/8234209/66741287-5d0f3800-ee9f-11e9-8c4a-d246ff7566bc.png)

### Actual result (*)

1. The summary is 1

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21770` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
