### ISSUE TITLE
Switch language stuck/blank in /stores/store/switchrequest

### ISSUE THREAD

**Issue by weeliem** [magento/magento2#25030]
**Preconditions (*)**
1. Magento 2.3.3+

**Steps to reproduce (*)**
1. Upgrade from Magento community 2.3.2 to 2.3.3.
2. We have 2 store language since Magento 2.3.2, English and Indonesia.
3. Change language

**Expected result (*)**
Successfully changed language strore.

**Actual result (*)**
Page stuck and blank in /stores/store/switchrequest. 
http://prntscr.com/pivc47

**Suspect (*)**
We suspect that the issue happen in line 91 of vendor/magento/module-store/Controller/Store/SwitchRequest.php, the hash validation function return empty.

**Comment by shikhamis11** [comment]
hello @weeliem 
Thank you for reporting this issue . It seems it is already reported Please check 
#24942
