### ISSUE TITLE
"Reindex all" will fail if there are greater than ~104 varchar attributes

### ISSUE THREAD

**Issue by gibbotronic** [magento/magento2#25048]
### Preconditions (*)

1. Version 2.3.2
2. A large number of varchar attributes. We have 104 and it is failing.

### Steps to reproduce (*)

1. Add a large number of varchar attributes to your Magento installation.
2. Run the cron job indexer_reindex_all_invalid

### Expected result (*)

1. The reindex should succeed.

### Actual result (*)

1. The reindex fails with: 

`The job indexer_reindex_all_invalid scheduled at 2019-10-14 13:55:05 failed with the following error message: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs, query was: CREATE TEMPORARY TABLE `catalog_product_entity_varchar_tmp_indexer` ( `entity_id` int UNSIGNED NULL COMMENT 'Entity_id' , `type_id` text NULL COMMENT 'Type_id' , `attribute_set_id` int NULL COMMENT 'Attribute_set_id' , `accessories` varchar(255) NULL COMMENT 'Accessories' , ... ) COMMENT='catalog_product_entity_varchar_tmp_indexer' ENGINE=innodb charset=utf8 COLLATE=utf8_general_ci`

I have truncated the middle of the statement as it is a series of varchar(255) columns.

Note that this is a limitation of MySQL where it has a row size limit. 

The issue is that the reindexer attempts to create a table with as many columns as there are attributes. As there are 104 varchar attributes in our system, this cause the MySQL row size limit to be reached, as that many varchar columns exceeds the row size.

I have not found the offending code but it seems odd that a table is being created with as many columns as there are attributes, since the EAV design of the system permits thousands of attributes of a given type to be created, yet there is not many/any DB systems that support thousands of columns on a table, so this would fail sooner or later.

2. Although the row size limit can be worked-around by forcing a different InnoDB storage engine (Barracuda), the MySQL configuration is not always available on hosted instances so the default for new tables (including temporary tables) cannot easily be set.
Also it is not a pre-requisite of Magento's installation that the Barracuda format for InnoDB tables be set.

3. I believe that it is possible to force compression on a table to work around the row size limit but this is not set on whatever code is creating the temporary table in this cron instance, which is why I am seeing this failure.

**Comment by gibbotronic** [comment]
do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

x YES

Saying yes at this point as we are vanilla

**Comment by gibbotronic** [comment]
Note that work arounds for this "row size" error can be found on https://stackoverflow.com/a/15585700 but I still think it is a bug that needs to be fixed in Magento because the rows -> columns design of the reindex mechanism seems wrong.

**Comment by sudheers-kensium** [comment]
@gibbotronic I am not able to reproduced the issue on Magento 2.3-develop instance.

**Comment by avoelkl** [comment]
I was just able to reproduce this (read: run into this issue) on a Magento 2.3.5 instance with 90 custom attributes.
