### ISSUE TITLE
Delete JS Confirmation Popup Design is not Proper

### ISSUE THREAD

**Issue by RonakParmar** [magento/magento2#25045]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.2

### Steps to reproduce (*)

1.Login Admin -> Marketing
2. Under Communication Section -> Open Email Templates and Newsletter Templates both in different browser tab.
3. Try to Edit Already Created Template on both the views.
4. Click on "Delete Template" button.
5. Observe the js Confirmation Popup of both the views is different.

### Expected result (*)

1.  The Popup should look like Newsletter delete template popup.
![newsletter-template-delete](https://user-images.githubusercontent.com/6551912/66751244-2ee42500-eeac-11e9-8f63-bf2bed1c2ab1.png)

### Actual result (*)

1. Current Popup is:
![email-template-delete](https://user-images.githubusercontent.com/6551912/66751279-491e0300-eeac-11e9-8f77-27b56cc422d2.png)

Triage Note

    The issue is reproducible on 2.3.3 release version
    The issue is NOT reproducible on 2.3-develop
    2.3.3 is not merged into 2.3-develop at this moment

**Comment by krishprakash** [comment]
Hi @RonakParmar. 
This issue will be fixed with PR #25035 
So closing this issue.
