### ISSUE TITLE
Unable to Load Theme after Migration Magento 1.9.3.7 to Magento 2.3.2

### ISSUE THREAD

**Issue by PhilEvansTBF** [magento/magento2#25044]
### Preconditions (*)

1. Install Magento version 2.2.3
2. Install Theme using instructions
3. Run Theme export from Magento 1.9.3.7 and import into Magento 2.3.2.
4. Test admin access and website both work satisfactorily.

### Steps to reproduce (*)
1. Run migration using instructions at https://devdocs.magento.com/guides/v2.3/migration/migration-tool-install.html
2. Test access to admin. This works satisfactorily
3. Test access to website. This fails.

### Expected result (*)
1. Website should be displayed using the Magento 2.3.2 installed theme.

### Actual result (*)
1. Log error and report file generated
2. The exception below is referencing the Magento 1.9.3.7 theme name 'ultimo/default' and not the new theme name infortis/ultimo.
Note : I have checked that the theme is correctly configured in content>design>themes

I have also checked the Theme table and the theme is correctly entered here.

*********

1 exception(s):
Exception #0 (LogicException): Unable to load theme by specified key: 'ultimo/default'

Exception #0 (LogicException): Unable to load theme by specified key: 'ultimo/default'
<pre>#1 Magento\Theme\Model\View\Design->setDesignTheme('ultimo/default', 'frontend') called at [generated/code/Magento/Theme/Model/View/Design/Proxy.php:111]
#2 Magento\Theme\Model\View\Design\Proxy->setDesignTheme('ultimo/default') called at [vendor/magento/module-theme/Model/Design.php:143]
#3 Magento\Theme\Model\Design->changeDesign(&Magento\Theme\Model\View\Design\Proxy#0000000034a151c1000000001a2ae562#) called at [vendor/magento/framework/App/Area.php:162]
#4 Magento\Framework\App\Area->detectDesign(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/View/DesignLoader.php:56]
#5 Magento\Framework\View\DesignLoader->load() called at [vendor/magento/framework/App/Action/Plugin/Design.php:48]
#6 Magento\Framework\App\Action\Plugin\Design->beforeDispatch(&Magento\Cms\Controller\Index\Index\Interceptor#0000000034a1513c000000001a2ae562#, &Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/Interception/Interceptor.php:121]
#7 Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php:39]
#9 Magento\Cms\Controller\Index\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/App/FrontController.php:159]
#10 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#, &Magento\Cms\Controller\Index\Index\Interceptor#0000000034a1513c000000001a2ae562#) called at [vendor/magento/framework/App/FrontController.php:99]
#11 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#12 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#13 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#14 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000034a15040000000001a2ae562#, &Closure#0000000034a1506b000000001a2ae562#, &Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#16 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000034a15040000000001a2ae562#, &Closure#0000000034a1506b000000001a2ae562#, &Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#17 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php:32]
#18 Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000034a15040000000001a2ae562#, &Closure#0000000034a1506b000000001a2ae562#, &Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#19 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#20 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#21 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000034a15bef000000001a2ae562#) called at [vendor/magento/framework/App/Http.php:137]
#22 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#23 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#24 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000034a15bfd000000001a2ae562#) called at [index.php:39]
</pre>
**********

**Comment by PhilEvansTBF** [comment]
Yes the issue can be reproduced on vanilla Magento instance.

**Comment by krishprakash** [comment]
Hi @PhilEvansTBF. Thank you for your report.
Data migration related issues should reported to its separate repository.
https://github.com/magento/data-migration-tool/issues
Thanks.

**Comment by krishprakash** [comment]
Hi @PhilEvansTBF. Thank you for your report.
Closing it as issue is now reported at Data Migration Repository.
Thanks.
