### ISSUE TITLE
Store logo inherits height and width from luma logo, if no height and width is provided

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#25042]
### Preconditions (*)
1. Magento 2.3-develop

### Steps to reproduce (*)
1. Create a test logo image of size 400x100 pixels
![examplelogo](https://user-images.githubusercontent.com/30697781/66748964-71900800-ee80-11e9-8061-b595979dffe7.jpg)
2. Deploy 2.3-develop
3. Content->Configuration->Global->Edit->Header->Upload Logo Image
4. Do not set any height and width in config
5. Refresh cache
6. View frontend and inspect size of logo image

### Expected result (*)
1. Logo should be 400x100px.

### Actual result (*)
1. Logo is actually 148x43px in size which is the dimensions of luma's logo.svg, even though it is no longer being used.

If the height and width is set in design config to 400x100 pixels, the logo is displayed correctly.

If no height and width are set in config, it should determine them from the actual logo, not luma's logo.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21772` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vivekkumar945744** [comment]
@magento I am working on it.

**Comment by mfickers** [comment]
#cd-cologne19

**Comment by VladimirZaets** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#25789 by @mfickers in 2.3-develop branch
Related commit(s):
 - [9abcf547c0d5160de4cfa0c5e3b907056fb8f311](https://github.com/magento/magento2/commit/9abcf547c0d5160de4cfa0c5e3b907056fb8f311)
 - [136cb0400b7e8beb50be8a4bef75c62ff08b0937](https://github.com/magento/magento2/commit/136cb0400b7e8beb50be8a4bef75c62ff08b0937)

The fix will be available with the upcoming 2.3.5 release.

**Comment by hostep** [comment]
In case people see a different sized logo after upgrading to Magento 2.3.5, please follow the [advice](https://github.com/magento/magento2/pull/25789) from @mfickers and update your layout xml from:
```xml
        <referenceBlock name="logo">
            <arguments>
                <argument name="logo_img_width" xsi:type="number">xxx</argument>
                <argument name="logo_img_height" xsi:type="number">yyy</argument>
            </arguments>
        </referenceBlock>
```

to:
```xml
        <referenceBlock name="logo">
            <arguments>
                <argument name="logo_width" xsi:type="number">xxx</argument>
                <argument name="logo_height" xsi:type="number">yyy</argument>
            </arguments>
        </referenceBlock>

```

**Comment by magentoexpert** [comment]
This is not a solution for Magento 2.4.1 installed with composer
The new folder structure is completely different and includes /pub
The folder structure /app/design/frontend/Magento is empty and obsolete
