### ISSUE TITLE
Since 2.3.3 Store logo automatic resize on mobile/smaller displays does not respect aspect ratio

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#25043]
### Preconditions (*)
1. Magento 2.3.3+

### Steps to reproduce (*)
1. Create a test logo image of size 400x100 pixels
![examplelogo](https://user-images.githubusercontent.com/30697781/66748920-5f15ce80-ee80-11e9-8b8f-81d46d87a819.jpg)
2. Deploy 2.3-develop
3. Content->Configuration->Global->Edit->Header->Upload Logo Image
4. Content->Configuration->Global->Edit->Header->Height = 100
5. Content->Configuration->Global->Edit->Header->Width = 400
6. Use browser developer tools to simulate resizing screen to small sizes.

### Expected result (*)
1. Header image aspect ratio is maintained when window is resized.
2. This screenshot is running on 2.3.2
![WRWU0MwQTm](https://user-images.githubusercontent.com/30697781/66748748-df87ff80-ee7f-11e9-9940-431ddbb666f4.gif)

### Actual result (*)
1. Header image does not respect aspect ratio and is resized incorrectly.
2. This screenshot is running on 2.3-develop
![QM0eu8VGdf](https://user-images.githubusercontent.com/30697781/66748846-1cec8d00-ee80-11e9-984a-63c1b0c2e25d.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21776` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment]
Infact, this looks like it affects many more images than just the logo. Any image that is too large in width to fit into the parent container is shrunk in width to fit, but not in height resulting in skewed aspect ratios everywhere.

**Comment by gwharton** [comment]
Seems related to the addition of max-height:100% and the removal of height:auto from the img tag in the luma style.

**Comment by extremeskillz** [comment]
I can confirm this on my install today. 
Interestingly enough 2.3.3 fixed an issue I was having in 2.3.2 where the mobile version wouldn't scale on mobile browsers. 2.3.3 is now doing that properly but the height isn't adjusting. See attached screenshot.
![Screenshot from 2019-10-15 19-29-20](https://user-images.githubusercontent.com/40648180/66877074-22320080-ef82-11e9-9f1c-58900a3936fe.png)

**Comment by fabriciosobral** [comment]
Can I work on this?  If yes, please assign

**Comment by fabriciosobral** [comment]
I am working on this

**Comment by fabriciosobral** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fabriciosobral. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fabriciosobral, here is your [Magento instance](https://i-25043-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25043-2-3-develop.instances.magento-community.engineering/admin](https://i-25043-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#25623 by @fabriciosobral in 2.3-develop branch
Related commit(s):
 - [d0167a0029358c0324abdf3a8f6313bf66cff2ff](https://github.com/magento/magento2/commit/d0167a0029358c0324abdf3a8f6313bf66cff2ff)

The fix will be available with the upcoming 2.3.5 release.
