### ISSUE TITLE
Unable to add product with required customizable checkbox option to the cart via POST /V1/carts/{id}/items

### ISSUE THREAD

**Issue by imkingdavid** [magento/magento2#25054]
### Preconditions (*)

1. 2.3.3
2. A simple product should be set up with a single, required Customizable Option of type Checkbox, with a single value.
![ Magento Admin 2019-10-14 15-57-37](https://user-images.githubusercontent.com/217426/66779068-5ed6fc80-ee9b-11e9-82b2-a1c4ca54a657.png)

### Steps to reproduce (*)

1. Using the API, create a cart and attempt to add the product using the following JSON body (obviously replacing the product, quote, and option data with the correct values):
```json
{
  "cartItem": {
    "sku": "Product with a Checkbox",
    "qty": 1,
    "quote_id": "31",
    "product_option": {
      "extension_attributes": {
        "custom_options": [
          {
            "option_id": "1",
            "option_value": "1"
          }
        ]
      }
    }
  }
}
```

### Expected result (*)

1. Request: 
![Swagger UI 2019-10-14 16-05-35](https://user-images.githubusercontent.com/217426/66779535-78c50f00-ee9c-11e9-9289-f06dffbf65d7.png)

2. Response: 
![Swagger UI 2019-10-14 16-05-05](https://user-images.githubusercontent.com/217426/66779522-6cd94d00-ee9c-11e9-8052-f1ca0aa2ddb4.png)

### Actual result (*)

1. Request:
![Swagger UI 2019-10-14 16-08-18](https://user-images.githubusercontent.com/217426/66779695-d9ece280-ee9c-11e9-92c6-68e0cf01659d.png)

2. Response: 
![Swagger UI 2019-10-14 16-07-51](https://user-images.githubusercontent.com/217426/66779679-cf324d80-ee9c-11e9-8432-c28b0a1cd426.png)

I've tracked this down to line ~88 in Magento\Model\Product\Option\Type\Select. Because it's validating the checkbox as a select box, it is expecting an array of values:
```php
$valueCount = is_array($value) ? count($value) : 0;
```

If I change the above line to the following, it works:
```php
$valueCount = (is_array($value) ? count($value) : (!empty($value) ? 1 : 0));
```

Please let me know if you need any additional information.

**Comment by imkingdavid** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @imkingdavid. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @imkingdavid, here is your [Magento instance](https://i-25054-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25054-2-3-develop.instances.magento-community.engineering/admin](https://i-25054-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by imkingdavid** [comment]
Hmm, it looks like I should have compared my 2.3.3 files with the develop branch. This appears to already be fixed in the vanilla version: 
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Product/Option/Type/Select.php#L86
