### ISSUE TITLE
Product AdditionalOptions "Read more" dots being escaped on invoice/shipment overview pages

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#25050]
### Preconditions (*)

1. Magento 2.3.2
2. Product with additionalOptions populated

### Steps to reproduce (*)

1. Create a product that includes an additionalOption value that is over 55 characters
2. Place order for product
3. View invoice for order in customer dashboard

### Expected result (*)

1. Product additional options appear with ".." and tooltip with full message

### Actual result (*)

1. Options are escaped causing html to show:
![image](https://user-images.githubusercontent.com/49071342/66767248-df035f00-eea7-11e9-8ab9-38cc46e5e303.png)

It's caused by the following commit: https://github.com/magento/magento2/commit/f15f42dd6727b44afbc25593e7c8d7030904cf50#diff-fac9e3967557f4a64daadb9e587360d1

Line: <?= $block->escapeHtml($_formatedOptionValue['value']) ?>

I appreciate it's a security fix, but the core code shouldn't be adding HTML in the ItemRenderer then escaping it in a template file.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25050-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25050-2-3-develop.instances.magento-community.engineering/admin](https://i-25050-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have not reproduced this issue. 
**Steps:**
1. In the Admin section > Create a simple product with additional product details.
2. In the front end section > Place one Order with selected additional product option.
3. In the Admin section > Generate Invoice > Review the Invoice in front end view.

**Actual result:** Text is displayed properly

**See attached screenshot:**

![2019-10-15](https://user-images.githubusercontent.com/24711761/66801942-76b08e00-ef38-11e9-9ea8-15858942a47c.png)

@itwebdev2 - Give me proper details and screenshot if you have found this issue again. Which version you have used please update me.

**Comment by itmsenior** [comment]
> I have not reproduced this issue.
> **Steps:**
> 
> 1. In the Admin section > Create a simple product with additional product details.
> 2. In the front end section > Place one Order with selected additional product option.
> 3. In the Admin section > Generate Invoice > Review the Invoice in front end view.
> 
> **Actual result:** Text is displayed properly
> 
> **See attached screenshot:**
> 
> ![2019-10-15](https://user-images.githubusercontent.com/24711761/66801942-76b08e00-ef38-11e9-9ea8-15858942a47c.png)
> 
> @itwebdev2 - Give me proper details and screenshot if you have found this issue again. Which version you have used please update me.

You've made the title really long but the actual content is only "test1". Could you please do another test but make the actual content of the additionalOption longer than 55 characters?

**Comment by itmsenior** [comment]
@ajijshekh123 could you please review my comment above?

**Comment by ajijshekh123** [comment]
@itwebdev2 - Sorry for the late response. Today I will review this issue again update it.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25050-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25050-2-3-develop.instances.magento-community.engineering/admin](https://i-25050-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
The issue has been reproduced as defined by the steps and details.
@itwebdev2 - Thanks for the Update.
**See attached screenshot:**

![2019-10-23](https://user-images.githubusercontent.com/24711761/67358670-c9182d00-f57e-11e9-8f0d-e8e22f03dc80.png)

**Comment by magento-engcom-team** [comment]
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22022` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @itwebdev2. Thank you for your report. 
The issue has been fixed in magento/magento2#25418 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [e42294213f19f3f8240e91c7299aeebf1a21e16c](https://github.com/magento/magento2/commit/e42294213f19f3f8240e91c7299aeebf1a21e16c)
 - [4b432f8f0600cda910a4e8752422565ec6838f02](https://github.com/magento/magento2/commit/4b432f8f0600cda910a4e8752422565ec6838f02)
 - [d4cae504fba92e4f0001a665d6b2ef02368d7650](https://github.com/magento/magento2/commit/d4cae504fba92e4f0001a665d6b2ef02368d7650)
 - [6e36d5e605e07d3a0f773de1a98884f75430aaf5](https://github.com/magento/magento2/commit/6e36d5e605e07d3a0f773de1a98884f75430aaf5)

The fix will be available with the upcoming 2.3.5 release.
