### ISSUE TITLE
while Flush Magento Cache i m getting this error

### ISSUE THREAD

**Issue by kobid** [magento/magento2#2505]
while Flush Magento Cache i m getting this error
"There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 596744697231"

**Comment by mazhalai** [comment]
@kobid is there any message in `var/log/exception.log`? Also, do you files and folders have the recommended [file permissions](http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html)?

**Comment by kobid** [comment]
there is nothing named exception.log
![capture](https://cloud.githubusercontent.com/assets/10341684/11396681/6ceefd6a-9399-11e5-8e89-be2d7b513ee5.JPG)

**Comment by kobid** [comment]
my permission is acc to this 

 chown -R :www-data .
sudo find . -type d -exec chmod 770 {} \; && sudo find . -type f -exec chmod 660 {} \; && sudo chmod u+x bin/magento

**Comment by sevos1984** [comment]
you can find log in var/report/596744697231

**Comment by dmitrii-fediuk** [comment]
Of course, if you see the message `Exception printing is disabled by default for security reasons.` then you should look for an additional information in the `var/report` folder, not `var/log/exception.log`

**Comment by kobid** [comment]
![capture](https://cloud.githubusercontent.com/assets/10341684/11411776/edad7430-93f9-11e5-978f-292a9338c95d.JPG)

**Comment by davidalger** [comment]
@kobid The message in the report file indicates that the apache user (or php-fpm if used) does not have write permission to the var/generation directory. Please ensure that directory is writable. You may check out #2412 for some ideas on the permissions trouble, as that is a duplicate of what you are running into. You may try heading over to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for additional questions regarding how to get this spun up and working.

**Comment by Janesmith03** [comment]
The error #2505 while flushing Magento Cache typically indicates an issue related to [Exception printing](https://devrims.com/blog/exception-printing-is-disabled-by-default-for-security-reasons-in-magento-solved/). This problem often stems from conflicts or permissions issues in the cache or log directories. To resolve it, check your file and directory permissions to ensure Magento can write to the necessary folders. Additionally, review the exception log for more detailed information about the error, which can guide further troubleshooting. Clearing all cache types and reviewing third-party extensions for compatibility may also help.
