### ISSUE TITLE
"Customer First Name" and "Customer Last Name" should display empty instead of "----" in Newsletter Subscribers 

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25057]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to frontend, subscribe the newsletter with Guest
2. Go to backend
3. Marketing->Newsletter Subscribers
4. Check the grid

"Customer First Name" and "Customer Last Name" should display empty instead of "----"

![image](https://user-images.githubusercontent.com/8234209/66792766-64c4f000-ef24-11e9-8928-b87c1d64591a.png)

You can not search by "----". No results. So it should be empty

### Expected result (*)

1."Customer First Name" and "Customer Last Name" should display empty 

### Actual result (*)

1. "Customer First Name" and "Customer Last Name"  display "----"

**Comment by krishprakash** [comment]
@edenduong Customer First Name and Last Name display as ---- in exported CSV as you explain it is as empty.
![image](https://user-images.githubusercontent.com/46617848/66800682-c3de3100-ef33-11e9-900d-71212ce5799b.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-25057-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25057-2-3-develop.instances.magento-community.engineering/admin](https://i-25057-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
Hi @krishprakash:

Sorry for my mistake. But, I think we should display it as "Empty" because we can not search "----". And the value is actually empty string. I updated the issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21819` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mohith-ecommerce** [comment]
@magento-engcom-team I have found the solution and I have create pull request
