### ISSUE TITLE
Category page filter option issue - Magento 2.3.3

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#25052]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.2, 7.3

### Steps to reproduce (*)

1. Click open someone a filter option on the category page.
example. category, style etc...

![filter](https://user-images.githubusercontent.com/26794034/66773905-d53e2380-eec8-11e9-9003-2c358e55f6ed.png)

### Expected result (*)

1. Click open someone filter option
2. Page doesn't automaticully scroll down

### Actual result (*)

1. Click open someone filter option
2. Page automaticully scroll down

**Comment by Userr017** [comment]
Hope so there is a temporary solution to fix this issue soon?

**Comment by krishprakash** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25052-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25052-2-3-3.instances.magento-community.engineering/admin](https://i-25052-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21824` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by boban-dj** [comment]
just to clear for myself, the issue is being worked on? same issue here 2.3.3, php7.2.
seems jquery-ui is not loading in frontend.

**Comment by Jilco** [comment]
Is there a sollution or work-around? Because categorie menu is dissapearing because of the jumping op the page (to top)

**Comment by Userr017** [comment]
@Jilco This works for me. https://github.com/magento/magento2/pull/25239/files

**Comment by Jilco** [comment]
@Userr017 thanks, that did the trick!

**Comment by eugene-shab** [comment]
This bug related to the PR - https://github.com/magento/magento2/pull/23390

**Comment by dmytro-ch** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-25052-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25052-2-3-develop.instances.magento-community.engineering/admin](https://i-25052-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vignesvaran** [comment]
@magento give me 2.3.3 with sample data

**Comment by vignesvaran** [comment]
@magento please give me 2.3.3 instance with sample data

**Comment by vignesvaran** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vignesvaran. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by engcom-Bravo** [comment]
Hello @Userr017 

Thank you for your report.

We have rechecked this issue on **Magento 2.3.3** and it is reproducible.
![233](https://user-images.githubusercontent.com/51680745/95842106-d067b600-0d4e-11eb-8c91-5a7a6c656762.gif)

But, we have rechecked the same steps on **Magento 2.4-develop**. And the issue seems to be fixed. The page is not scrolled Up. Please see the attachment
![Shopping Options](https://user-images.githubusercontent.com/51680745/95842204-eecdb180-0d4e-11eb-816a-dfc8301dc286.gif)

We are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by drinkingsouls** [comment]
Magento  2.4.2, I still experience this issue.

**Comment by pagesailor** [comment]
Issue is still present in Magento 2.4.1
