### ISSUE TITLE
Address Book Tab is not Active after Saving the Address at My Account Page

### ISSUE THREAD

**Issue by RonakParmar** [magento/magento2#25065]
### Preconditions (*)

1. Magento 2.3
2. PHP 7.2

### Steps to reproduce (*)

1. Do Login at Fronend
2. Go to My Account Page
3. Click on "Address Book", this tab is showing as selected.
4. Add New Address or Edit Address and save it.
5. Check the "Address Book" tab is not showing as selected. 

### Expected result (*)

1. The "Address Book" tab should be selected. 

### Actual result (*)

1. The "Address Book" tab is not showing as selected. 

### Triage Note
- The issue is reproducible on `2.3.3` release version
- The issue is NOT reproducible on `2.3-develop`
- `2.3.3` is not merged into `2.3-develop` at this moment

**Comment by krishprakash** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25065-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25065-2-3-3.instances.magento-community.engineering/admin](https://i-25065-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25065-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25065-2-3-develop.instances.magento-community.engineering/admin](https://i-25065-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21822` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @RonakParmar and @krishprakash 

The issue has been re-verified on the current `2.3-develop` code base with merged changes from `2.3.3` release https://github.com/magento/magento2/commit/0583fc3a88c948b2e95c6874c6dda1caaa4f9442
We cannot reproduce it now by provided steps from the description which means this issue has been fixed and not reproducible anymore.

This issue and related open PR https://github.com/magento/magento2/pull/25066 should be closed.
