### ISSUE TITLE
Add to cart buttons are disabled on category page

### ISSUE THREAD

**Issue by jsdupuis** [magento/magento2#25063]
### Preconditions (*)
1. Magento 2.2.10 Open Source
2. Php 7.1.3

### Steps to reproduce (*)
1. Upgrade from Magento 2.2.9 to 2.2.10
2. Log in as a customer
3. Navigate to any category page with products in stock

### Expected result (*)
1. Customer can click on an enabled "add to cart" button

### Actual result (*)
1. All "Add to cart" buttons on the category pages are disabled. This happens both for guests and logged in customers. See screenshot.
![screenshot](https://user-images.githubusercontent.com/28755070/66803997-82598000-ef4b-11e9-8634-e24414745429.jpg)

### Additional notes
1. This change listed in the 2.2.10 release notes might be the culprit:   "The Add to Cart button is no longer visible to users who do not have Add to Cart category permissions. Previously, guest users could add items to the cart without being granted Add to Cart permission."
2. Open Source does not have the "Catalog Permission" menu like Commerce Edition as part of the Configurations

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25063-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25063-2-3-develop.instances.magento-community.engineering/admin](https://i-25063-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @jsdupuis 
thank you for reporting this issue , It seems this issue is not reproducible at latest magento 2.3 instance . 
and magento now does not provide instance for 2.2 versions . 
Please try reproducing this error on latest magento 2 versions and update description if you are able to reproduce this issue

**Comment by jsdupuis** [comment]
@shikhamis11 
thank you for checking. we are not planning to upgrade to 2.3 shortly. Will try to find a solution by our own.

**Comment by dribblecastle** [comment]
Same issue here!  Running 2.2.10 and PHP 7.1.33.   I've also tried PHP 7.2 but had the same result.  I saw the "Add to Cart" reference in the release notes but haven't been able to make sense of it thus far.  

Any breakthroughs since your initial post?   I would love to run 2.2.10 for the security fixes over the holiday shopping season but this is a show stopper.   2.3.3 is not an option as we've had other compatibility issues upgrading to that in our test environment.

**Comment by jsdupuis** [comment]
@dribblecastle 
I'm not a developer (just running a small family business with a fancy Magento website), but here's what I did to solve the problem.

File to fix:
public_html/vendor/magento/module-catalog/view/frontend/templates/product/list.phtml

Line 95: change "disabled" to "enabled" to make buttons active again

I know it's not suggested to edit files directly, but that's all I could do without Magento's support. Flush your cache afterwards and wait a bit. Worked for me.

**Comment by dribblecastle** [comment]
@jsdupuis thank you so much for sharing that with me!  saved me a lot of troubleshooting time.  I understand editing vendor/ files isn't the best, but in this case its the only option that works on short notice.  Appreciate it.

**Comment by benjaminv** [comment]
> @dribblecastle I'm not a developer (just running a small family business with a fancy Magento website), but here's what I did to solve the problem.
> 
> File to fix: public_html/vendor/magento/module-catalog/view/frontend/templates/product/list.phtml
> 
> Line 95: change "disabled" to "enabled" to make buttons active again
> 
> I know it's not suggested to edit files directly, but that's all I could do without Magento's support. Flush your cache afterwards and wait a bit. Worked for me.

The more Magento2 way of doing this is to `override` the core template on the targeted page. In this case,
1. copy `vendor/magento/module-catalog/view/frontend/templates/product/compare/list.phtml` to   
2. `app/design/frontend/THEME_VENDOR/THEME/Magento_Catalog/templates/product/list.phtml` and make the change here and leave all other lines unchanged
3. compile and deploy to take effects by
    ```ruby
    bin/magento setup:di:compile
    # and then
    bin/magento setup:static-content:deploy -f
    ```
