### ISSUE TITLE
"Enable Single-Store Mode" is "Yes" but the create New Rating has store view title

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25060]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Settings -> Configuration-> General, "Enable Single-Store Mode" is "Yes"
2. Store-> Ratings -> Add New Rating
3. View the form

![image](https://user-images.githubusercontent.com/8234209/66798866-8381b180-ef39-11e9-926a-7473f9146b5c.png)

### Expected result (*)

That field should hidden, because it is in single-store mode

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/66798876-87153880-ef39-11e9-82fd-622a8adacf70.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25060-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25060-2-3-develop.instances.magento-community.engineering/admin](https://i-25060-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Issue reproduced in Default Magento 2.3 Instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21818` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
