### ISSUE TITLE
New Order not sending if a comma is followed by a blank space in the 'Send Order Email Copy To' field

### ISSUE THREAD

**Issue by jaxtheking** [magento/magento2#25072]
### Preconditions (*)

Magento 2.3.3
php7.1

### Steps to reproduce (*)

1. In the BO, go to Stores >> Configuration >> Sales >> Sales Emails
2. Under Orders, in the 'Send Order Email Copy To' field, enter a list of emails in the following format: 'admin1@email.com, admin2@email.com' (note the blank space after the comma)

### Expected result (*)

1. The New Order email should be sent to the customer and the two admins

### Actual result (*)

1. No emails are sent out (not even the customer!), due to the following error:
> main.ERROR: ' admin2' can not be matched against dot-atom format [] []

Obviously, Magento is not expecting a blank space before the email address: while not technically a bug, this could be easily avoided by trimming each email address after exploding the comma-separated string.

More importantly, this behaviour means that if an admin were to enter a list of emails containing one invalid email (e.g. correct@email.com,incorrect.com), the customer would not be receiving a new order email at all!
I think the error should be limited to the invalid email only.
I'm guessing this behaviour applies to all 'Send XXX Email Copy To' fields in the BO.

Regards,
Luca

**Comment by sakbari** [comment]
Centos 7
Magento CLI 2.3.3
PHP 7.2.23
nginx version: nginx/1.16.1
redis-cli 5.0.5


I have same issue we did not get a copy of order mail

**Comment by edenduong** [comment]
I am working to fix this issue

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21863` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
