### ISSUE TITLE
Response messages now showing in admin panel

### ISSUE THREAD

**Issue by usmanmaqsoodshahab** [magento/magento2#2507]
I am a <software engineer/> after deployed magento2 at my local server and dig into its core and optimize features at the time when i start analyzing the magento2 features to check its backend functionality and ease; i found some feature are not included in it. 
While using magento2,its good to use angular for its backend/frontend operations but response message not showing properly and when some request is initiated there is not message appears that says "Please wait" or "loader" so user may aware of what is going on?
Need to fix these issues and some developers not familiar with these trend to create theme/extension from scratch for magento2, documentation should be provided by MAGENTO official site for developers community.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
