### ISSUE TITLE
Magento Release 2.3.3 Product Dimensions

### ISSUE THREAD

**Issue by dev-Z-Apx** [magento/magento2#25073]
### Preconditions (*)

1. Fresh Magento version 2.3.3
2. Upgrade from 2.3.2 to 2.3.3

### Steps to reproduce (*)

1. You only need a fresh install of latest Magento Version 2.3.3 and just go to Catalog and try to add a New Product.
2. Just go to Catalog and try to edit any product.

### Expected result (*)

1. In this case the page should show Dimensions (Length, Width and Height) Attributes for the Product which are default shown as per last version 2.3.2 (Temando Shipping)
2. One should be able to see Dimensions (Length, Width and Height) Attributes for the Product.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/56595197/66837995-5bb43d00-ef7d-11e9-9d22-7a329f84df04.png)
There are no such type of Product Dimensions (Length, Width and Height) Attributes and when you try to load Add/Edit Product page an error is logged in system.log and temando.log as well which is 

> [2019-10-15 13:45:56] temando.CRITICAL: "accountId" is required. Enter and try again. {"exception":"[object] (Magento\\Framework\\Exception\\InputException(code: 0): \"accountId\" is required. Enter and try again. at /home/mag/public_html/m233/vendor/magento/framework/Exception/InputException.php:91)"} []

2. I am unable to see these Product Dimensions (Length, Width and Height) Attributes which I already have saved in the older version 2.3.2 and even can not get these old saved data of product from Backend i.e Length, Width and Height that makes me think that DB has been updated and I have to recreate all of my products.

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25073-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25073-2-3-develop.instances.magento-community.engineering/admin](https://i-25073-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25073-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-25073-2-3-2.instances.magento-community.engineering/admin](https://i-25073-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21834` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hi @dev-Z-Apx. Thank you for your report.
Closing this issue as Issue is duplicate to #24948 
Thanks

**Comment by dev-Z-Apx** [comment]
Hi @krishprakash 
Thank you for that
I just want to know till when this issue will be solved as there are many of my customers using my shipping Modules will be reporting this issue to me.

**Comment by gaiterjones** [comment]
@dev-Z-Apx are you actually using Magento shipping or just using the product attributes installed by the module? Disabling the Temando_Shipping module will let you access the product attributes again.

**Comment by dev-Z-Apx** [comment]
@gaiterjones  I am not using this I actually need product attributes but I have customers who might be using Temando_Shipping.
I have tried to disable it but the problem still persists.
