### ISSUE TITLE
Cannot update Google Analytics Code in Magento 2.2.8

### ISSUE THREAD

**Issue by admin-PMG** [magento/magento2#25079]
### Preconditions (*)

1. Magento 2.2.8
2. Firefox and Chrome browsers both tried

### Steps to reproduce (*)
1. Set up new Google Analytics account, grab Tracking ID from Google.
2. Log in to Magento site. Navigation = Stores >> Configuration >> Sales >> Google API >> Google Analytics >> (change Account Number) Enable = yes. Anonomize = no. Enable Content Experiments = no.
3. Click Save Config
4. Checkbox appears "You saved the configuration"
5. Error appears "One or more of the Cache are invalidated: Configuration, Page Cache. Please go to Cache Management and refresh cache types."
6. Google Analytics Account Number reverts back to old information.
7. Go to Cache Management. See Configuration & Page Cache are invalidated.
8. Select both and refresh cache.
9. Both cache are refreshed and enabled.
10. Go back to step 2, try again with same result.

### Expected result (*)
1. update Google Analytics Code
2. track usage

### Actual result (*)
1. Checkbox appears "You saved the configuration"
2. Error appears "One or more of the Cache are invalidated: Configuration, Page Cache. Please go to Cache Management and refresh cache types."
3. Google Analytics Account Number reverts back to old information.

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25079-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25079-2-3-develop.instances.magento-community.engineering/admin](https://i-25079-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@admin-PMG I am not able reproduced in Magento 2.3-develop instance. May be this issue fixed in latest Magento version.
