### ISSUE TITLE
Error While installing Magento 2.0

### ISSUE THREAD

**Issue by yasardesigns** [magento/magento2#2508]
Hi,
i am new to Magento.i have downloaded the Magento community edition and the sample data.i am using XAMPP and while when i try to install Magento on localhost,all the five steps are fine and when i click on the Install now button, the installation process stops with the following message
![error1](https://cloud.githubusercontent.com/assets/11024306/11389051/1c658ada-9362-11e5-8669-5d3dab41fd48.PNG)

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':
Installing schema.. 

Module 'Magento_Indexer':
Installing schema.. 

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':
Installing schema.. 

Module 'Magento_Rule':

Module 'Magento_Catalog':
Installing schema.. Upgrading schema.. 

Module 'Magento_Search':
Installing schema.. Upgrading schema.. 

Module 'Magento_CatalogUrlRewrite':
Installing schema.. 

Module 'Magento_Widget':
Installing schema.. 
[ERROR] exception 'Zend_Db_Exception' with message 'Column "code" does not exist in table "widget".' in C:\xampp\htdocs\Magento\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php:967 Stack trace: #0 C:\xampp\htdocs\Magento\vendor\magento\module-widget\Setup\InstallSchema.php(102): Magento\Framework\DB\Adapter\Pdo\Mysql->changeColumn('widget', 'code', 'widget_code', Array) #1 C:\xampp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(798): Magento\Widget\Setup\InstallSchema->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext)) #2 C:\xampp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(732): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema') #3 [internal function]: Magento\Setup\Model\Installer->installSchema() #4 C:\xampp\htdocs\Magento\setup\src\Magento\Setup\Model\Installer.php(331): call_user_func_array(Array, Array) #5 C:\xampp\htdocs\Magento\setup\src\Magento\Setup\Controller\Install.php(97): Magento\Setup\Model\Installer->install(Array) #6 C:\xampp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #8 C:\xampp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #9 C:\xampp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #10 C:\xampp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #11 C:\xampp\htdocs\Magento\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #13 C:\xampp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #14 C:\xampp\htdocs\Magento\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #15 C:\xampp\htdocs\Magento\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #16 C:\xampp\htdocs\Magento\setup\index.php(31): Zend\Mvc\Application->run() #17 {main}

Please help me to resolve this issue.

**Comment by buskamuza** [comment]
Hi @yasardesigns ,

are you sure that the DB was empty before you started installation?
Or maybe you retried the installation?

Looks like it thinks that you already have 'widget' table and tries to alter it. It should not happen, if you install on an empty DB.

**Comment by ghost** [comment]
If you install via CLI, add the optional flag --cleanup-database, which drops the database before adding tables to it.

**Comment by yasardesigns** [comment]
HI  @buskamuza 
the database was not empty before installation.i have imported the sql statement that came along with the sample data. i shall try cleaning up the database and try the installation again.

**Comment by yasardesigns** [comment]
Hi @xcomSteveJohnson 
i didn't install Magento through CLI, anyways i try clean up the database and install it again.Thanks for your suggestion

**Comment by yasardesigns** [comment]
Hi @buskamuza 
I have cleaned up the database and  installation was successful

.

**Comment by Mohammed-Tahair-Pasha** [comment]
1. First of all make sure that you have entered right database name at database details step.

2. Check your database it must be clean. If you have imported the database from your Magento theme then clean it or create empty database. (Note : Database should be empty during Magento installation)
