### ISSUE TITLE
Minicart Qty update button not aligned proper

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#25081]
Minicart Qty update button not aligned proper

### Preconditions (*)
1. php 7.2 
2. Magento 2.3.x

### Steps to reproduce (*)
1. Open Frontend 
2. Add any product in cart 
3. Make screen mobile view 
4. Now click on mini cart and update quantity (Like: from 1 to 2) update button will see there now
compare with screenshot 

### Expected result (*)
![image](https://user-images.githubusercontent.com/26018716/66899237-40e2d680-f018-11e9-8fe7-71b04773c39e.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/26018716/66899307-57892d80-f018-11e9-8ee6-22cb39833c6d.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21859` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
Please note, the issue has already been fixed by #25206 
Thank you!
