### ISSUE TITLE
Get Video Information button doesn't do anything on clicked

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#25088]
### Preconditions (*)
1. Magento 2.3-develop
2.

### Steps to reproduce (*)

1. Navigate to new product page
2. Scroll to `Images And Videos`
3. Click on `Add Video`
4. Click on `Get Video Information`

### Expected result (*)

1. We should see any feedback after clicking the button
![image](https://user-images.githubusercontent.com/15868188/66910110-9f0eba00-f016-11e9-81bc-522eb7df4ced.png)

### Actual result (*)

1. Nothing happens
2.

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25088-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25088-2-3-develop.instances.magento-community.engineering/admin](https://i-25088-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21865` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
