### ISSUE TITLE
2.3.2 Cart Price Rule for Free Shipping does not apply to matching items only when using Table Rates

### ISSUE THREAD

**Issue by TomR5** [magento/magento2#25098]
### Preconditions (*)

1. Magento Version 2.3.2
2. Theme is Alothemes/Expert1
3. Linux Server 
4. PHP version 7.1.32 (cli); Zend Engine v3.1.0 with Zend OPcache v7.1.32

### Steps to reproduce (*)

1. Enable table rates for shipping (Stores > Settings > Configuration > Sales > Shipping Methods > Table Rates) Condition is "Price vs. Destination". Import Table Rates table. Leave all other shipping methods disabled.
2. Create a free shipping cart price rule applicable only to certain categories of products (Marketing > Promotions >Cart Price Rules)
- Active: Yes
- Websites: Main Website (this is a Single Store site)
- Customer Groups: select all
- Coupon: select No Coupon or Specific Coupon with a Coupon Code; it doesn't matter
- Uses per Coupon and per Customer: 0
- Set valid dates and Priority to 0

Conditions:
- If ALL  of these conditions are TRUE :
- If total amount  equals or greater than  100  for a subselection of items in cart matching ANY  of these conditions: 
  -- Category  is  45, 46, 47, 48  
  
Actions:
- Apply: Percent of product price discount
- Discount Amount, Max Qty ... , Discount Qty Step ... all set to 0
- Apply to Shipping Amount: Yes
- Discard subsequent rules: Yes or No; it doesn't matter
- Apply the rule only to cart items matching the following conditions (leave blank for all items).
- If ANY  of these conditions are TRUE :
  -- Category  is  45, 46, 47, 48  
- Set Free Shipping to For matching items only

### Expected result (*)

1. Select $100 or more of free shipping eligible items. On Cart Page, the free shipping is applied (automatically, or with the coupon code if used).  Select a single item NOT eligible for free shipping. On Cart Page, the table rate shipping charge should ONLY be applied to the single item not eligible for free shipping.

If you could provide me a vanilla Magento instance on your environment, I could test there as well (@magento give me 2.3-develop instance - upcoming 2.3.x release)

### Actual result (*)

1. Select $100 or more of free shipping eligible items. On Cart Page, the free shipping is applied (automatically, or with the coupon code if used).  Select a single item NOT eligible for free shipping. On Cart Page, the table rate shipping charge for the total for ALL items is applied.

******************
Coupon_Code_Applied_Eligible_Items_In_Cart

![Coupon_Code_Applied_Eligible_Items_In_Cart](https://user-images.githubusercontent.com/41305756/66938442-c9f11200-f006-11e9-9a85-52210f526284.PNG)

******************
Coupon_Code_Not_Yet_Applied_Eligible_and_Non_Eligible_Items_In_Cart

![Coupon_Code_Not_Yet_Applied_Eligible_and_Non_Eligible_Items_In_Cart](https://user-images.githubusercontent.com/41305756/66938467-d1b0b680-f006-11e9-8208-1eb9cd691982.PNG)

******************
Coupon_Code_Applied_Eligible_and_Non_Eligible_Items_In_Cart

![Coupon_Code_Applied_Eligible_and_Non_Eligible_Items_In_Cart](https://user-images.githubusercontent.com/41305756/66939008-dcb81680-f007-11e9-86a0-46eac57c531a.PNG)

**Comment by kanthy-magento** [comment]
@magento give me 2.3.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3.2-develop instance for you

**Comment by TomR5** [comment]
We have narrowed down the problem.  The source of the problem has to do with the change from 2.3.0 to 2.3.1 (and persisting in 2.3.2) in module-offline-shipping/Model/Carrier/Tablerate.php where Magento has changed the condition_name of Table Rates "Price vs. Destination" when stored in the tables shipping_tablerate and core_config_data from 
                'package_value' => __('Price vs. Destination'),
to
                'package_value_with_discount' => __('Price vs. Destination'),
and from
                'package_value' => __('Order Subtotal (and above)'),
to
                'package_value_with_discount' => __('Order Subtotal (and above)'),

and added the Setup/Patch/Data/UpdateShippingTablerate.php file to modify those tables.

**Comment by TomR5** [comment]
Hi, @itsPranith, did you get that Magento 2.3.2 dev instance from the eng-com team?  I have not gotten one yet myself.  Thank you.

**Comment by kanthy-magento** [comment]
Hi TomR5,

 

I did not received Magento 2.3.2 dev instance from the eng-com team.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22561` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by TomR5** [comment]
Thank you @itsPranith and @webkul-ratnesh.

**Comment by Marcompaan** [comment]
I experience this issue also in M2.3.5 with Cart Rules
However it only is an issue when one or more items are in a different level of the same (sub) categorie.
So: 
- when I add 1 item in the cart that is over €75,- > Free Shipping is applied
- If I add another item that is in the same (sub) category level > Free Shipping is applied
- If I add another item that is in a deeper (sub) category level > no free shipping

www.moreofme.fashion

**Comment by crankycyclops** [comment]
Just curious if there's been any progress on this issue.

**Comment by TomR5** [comment]
I have confirmed the pblm still exists on a new client website on Magento 2.4.  The only fix I can figure out, which goes against the don't-modify-core-files rule, is to delete the file: 
vendor/magento/module-offline-shipping/Setup/Patch/Data/UpdateShippingTablerate.php 
and edit the getcode function in the file:
vendor/magento/module-offline-shipping/Model/Carrier/Tablerate.php replacing two lines as follows:

//                'package_value_with_discount' => __('Price vs. Destination'),
                'package_value' => __('Price vs. Destination'),

//                'package_value_with_discount' => __('Order Subtotal (and above)'),
                'package_value' => __('Order Subtotal (and above)'),

If someone has a better fix that does not involve core magento file changes, I'd like to hear about it.

**Comment by alexlabarces** [comment]
@TomR5 I'm having a similar issue in Magento 2.3.2 where the Free Shipping rule does NOT get applied to Matching Items Only when using the UPS shipping method. Have you seen this before? Any idea where to correct this? Thanks.

**Comment by TomR5** [comment]
No, I'm afraid I do not know how to address a specific UPS problem.  We have used different carriers, but we have always had a tablerate .csv uploaded that we use and we only enable "Tablerates" as our shipping method to use.

**Comment by alexlabarces** [comment]
Thanks for your comment, I appreciate you getting back to me on this.

**Comment by CFA2021** [comment]
Hi,
I am having a similar issue with the Megaplaza store pickup extension, I choose Free shipping, but free shipping is not applied (it does work with all other shipping methods.
I have another issue regarding coupons in magneto - I tried to create a coupon that will give the customer 100% discount on his order, when trying to place an order with this coupon, the cart shows the correct prices but when trying to checkout I get an error: Payment Method Not Allowed - I am using cardknox for the payment method

**Comment by shakil-codilar** [comment]
@magento give me 2.4-develop instance

**Comment by shakil-codilar** [comment]
@magentogive me 2.4.3 instance

**Comment by shakil-codilar** [comment]
Hi @magento give me 2.4.3-magento instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @TomR5,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1314" alt="Screenshot 2024-05-17 at 11 54 16" src="https://github.com/magento/magento2/assets/51680745/39c0b9f4-2d96-4b7c-97ee-a5a44fbcdb8f">


<img width="1342" alt="Screenshot 2024-05-17 at 11 55 26" src="https://github.com/magento/magento2/assets/51680745/afc4bf6f-f952-44db-b8f0-4b1a17f85d53">



For $100 or more of free shipping eligible items. On Cart Page, the free shipping is applied.the table rate shipping charge is applied to the single item not eligible for free shipping

Hence We are closing this issue.

Thanks.
