### ISSUE TITLE
Quotes for guests are saved with customer_is_guest = 1

### ISSUE THREAD

**Issue by vijay-prevaj** [magento/magento2#25095]
Magento saves some quotes from guests with customer_is_guest = 1. It usually happens when a customer was logged in before but his session expires or logs out.

**Comment by kanthy-magento** [comment]
HI vijay-prevaj,
Please provide the information as per below link.

https://github.com/magento/magento2/issues/25095#issuecomment-542707504


Thank You,
Pranith
