### ISSUE TITLE
Issue with Product Import - "Category has not been created. URL key for specified store already exists"

### ISSUE THREAD

**Issue by paras89** [magento/magento2#25096]
### Preconditions (*)
Magento verion 2.3.2

### Steps to reproduce (*)
1. Export and existing product
2. In the csv export, in the categories column add a new sub category:
Default Category/Gear,Default Category/Gear/SAMPLETEST
3. Import the products csv entity type with import behavior set to Add/Update

### Expected result (*)

1. I should not see any errors after the import
2. new category on path Default Category > Gear > SAMPLETEST should now exist

### Actual result (*)
Observe an error and the new sub category SAMPLETEST is not created

**Comment by paras89** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @paras89. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @paras89, here is your [Magento instance](https://i-25096-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25096-2-3-develop.instances.magento-community.engineering/admin](https://i-25096-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gsa83** [comment]
Note : If another category has been renammed, but the url-key not, this problem can happend (if another categ has the url-key sampletest ). In that case, it is not bug because the import is doing the mapping on categ name, so he think to create a new categ, but he can't because the url exist elsewhere.

**Comment by paras89** [comment]
I'm creating a new sub category with a unique name, however it still throws an error on a fresh Magento install.

________________________________

**Comment by engcom-Delta** [comment]
Hi @paras89 thank you for your report. I cannot reproduce issue by steps you described on clean 2.3-develop. 
In my case I was able to get this error message if add extra spaces into the field that contain categories:
[works.csv.txt](https://github.com/magento/magento2/files/3750280/works.csv.txt)
[notworks.csv.txt](https://github.com/magento/magento2/files/3750281/notworks.csv.txt)

If you'd like to update the issue, please reopen it.

**Comment by paras89** [comment]
Hello,

You are creating complete new categories like:
Default Category/cat1,Default Category/cat2,Default Category/cat1/cat1-1,Default Category/cat2/cat2-2,Default Category/cat2/cat2-2/cat2-2-2

Try creating sub categories within existing categories. You will see the error then.
Something like
Default Category/gear/bags/magento-bags

I am unable to re-open the issue, how can do it?

**Comment by engcom-Delta** [comment]
@paras89 I create nesting categories, like `Default Category/gear/bags`
![#25096CatTree](https://user-images.githubusercontent.com/51681379/67207548-84748080-f41c-11e9-8a6e-b26ba5c3625a.png)
Then modify my scv file and left only `Default Category/gear/bags/magento-bags` in category field
[works2.csv.txt](https://github.com/magento/magento2/files/3750924/works2.csv.txt)
Import this file successfully:
![#25096Result](https://user-images.githubusercontent.com/51681379/67207718-cb627600-f41c-11e9-9e67-c7789dce1a16.png)

**Comment by paras89** [comment]
You should have sample data when you try to create those cateogories. If the category tree already exists the importer does not allow you to add children cateogories.

Thank you!

________________________________

**Comment by engcom-Delta** [comment]
@paras89 I tried scenario when categories contain products:
![#25096CatogiriesWithProducts](https://user-images.githubusercontent.com/51681379/67212336-e89b4280-f424-11e9-987c-f174a461c19d.png)

- Edit scv file by adding `Default Category/Category 4/Category 4.1/Category 4.1.1/magento-bags`:

[works3.csv.txt](https://github.com/magento/magento2/files/3751208/works3.csv.txt)

- Import file is finished successfully and child category with product is present:

![#25096Import2](https://user-images.githubusercontent.com/51681379/67212604-4891e900-f425-11e9-83c3-063eba8c8b9c.png)
