### ISSUE TITLE
Confusing or incorrect bulk actions item count

### ISSUE THREAD

**Issue by DominicWatts** [magento/magento2#25093]
Confusing or incorrect bulk actions item count

### Preconditions (*)

Magento 2.3.3 & 2.3-develop

Create a small number of products (15 or so)

### Steps to reproduce (*)

Use mass action on admin product grid to update a product attribute for all SKUs

Assume you select all SKUs but only the visibility needs changing on 7 for example

### Expected result (*)

Bulk action executes

System > Action Logs  > Bulk Action

 Description of Operation
Update attributes for 16 selected products
Summary
16 items selected for mass update, 7 successfully updated
Start Time
10/16/2019 12:31:00 PM

### Actual result (*)

System > Action Logs  > Bulk Action

 Description of Operation
Update attributes for 16 selected products
Summary
1 items selected for mass update, 1 successfully updated
Start Time
10/16/2019 12:31:00 PM

Either item count refers to bulk action count (confusingly) or there is an issue with the update count mechanism.

**Comment by DominicWatts** [comment]
@magento give me 2.3-develop instance

**Comment by DominicWatts** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DominicWatts. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DominicWatts, here is your [Magento instance](https://i-25093-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25093-2-3-develop.instances.magento-community.engineering/admin](https://i-25093-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DominicWatts** [comment]
I tried in develop isntance but bulk action appeared to just be sat in a queue

![image](https://user-images.githubusercontent.com/7295705/66960114-b88a2300-f063-11e9-8fe3-af0cc7551d83.png)

So I can't test

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23034` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
