### ISSUE TITLE
Creating RTL theme - css,js 403 error  

### ISSUE THREAD

**Issue by refaelgold** [magento/magento2#2510]
Hey , i got 403 errors on the console.log of chrome  when i try to call the js,css files

```
(index):12 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/mage/calendar.css 
(index):13 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/css/styles-m.css 
(index):14 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/css/styles-l.css 
(index):18 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/requirejs/require.js 
(index):22 Uncaught ReferenceError: require is not defined(anonymous function) @ (index):22
(index):145 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/images/logo.svg 403 (Forbidden)
(index):15 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/css/print.css 
favicon.ico:1 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/Magento_Theme/favicon.ico 403 (Forbidden)
favicon.ico:1 GET http://www.magento2.dev/pub/static/frontend/Gold/dream/he_IL/Magento_Theme/favicon.ico 403 (Forbidden)
```

i try to duplicate the files from pub/static/frontend/Gold/dream/en_US
to pub/static/frontend/Gold/dream/he_Il put its not work

anyone can help me and tell me what is wrong with this installation? What is the proper way to create/copy css/js files to new language ?

Thanks,
Nir

**Comment by refaelgold** [comment]
Maybe be i need to duplicate all the folder to HE_IL and put Command line after it?

I really need your help to start developer Hebrew blank theme and put the translation he_IL package

**Comment by refaelgold** [comment]
I try to follow with the offical docs but i get stack

**Comment by dmitrii-fediuk** [comment]
You need setup the filesystem permissions and ownership for autogenerated content: http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html

**Comment by refaelgold** [comment]
I will do it! Thanks you for your support!!!
