### ISSUE TITLE
Elasticsearch Category Pages not showing products

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#25107]
### Preconditions (*)
1. Magento 2.3.3
2. Elasticsearch 6+

### Steps to reproduce (*)
1. Enable Elasticsearch 6+ in Magento
2. Reindex and go to a category page. First page shows products but the next ones doesn't.

### Expected result (*)
1. That all category pages list products.

### Actual result (*)
1. No products listed for the category pages except for the first.

**Comment by jorgb90** [comment]
Found the same issue here #24619 except I am using Magento 2.3.3 and not only 1 page layout.

**Comment by ihor-sviziev** [comment]
Hi @jorgb90,
If you're using NOT 1 column layout - it might be related: 
https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-open-source.html#apply-the-catalog-pagination-issue-on-elasticsearch-6x-patch-to-resolve-a-critical-search-result-pagination-issue

**Comment by jorgb90** [comment]
Hi @ihor-sviziev That was it! Thanks! Should have looked for a patch first..

**Comment by ihor-sviziev** [comment]
@jorgb90 great! So I'm closing the issue
