### ISSUE TITLE
"Collapse All | Expand All" in Media Gallery has wrong Cursor Icon

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25108]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Catalog->Category
3. Click "Content"
4. Click "Select from Gallery"
5. Hover to "Collapse All | Expand All"

### Expected result (*)

1. Cursor icon is "Pointer" 
### Actual result (*)

1. Cursor icon is "Text"

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21894` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by eduard13** [comment]
Hi @edenduong, I'm just wondering, does it make sense to open a such issue instead of just creating the PR to fix it?

**Comment by edenduong** [comment]
Hi @eduard13 : 
I don’t know when we need to create the issue before creating PR. I see in PR template, it has the fields to fill the issue so if I can reproduce it, I will create the issue and tag the PR to that issue.
