### ISSUE TITLE
Typo Bug and Invalid Return Type Given in Import Product Option's _parseRequiredData 

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#25103]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Typo Error in `https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1659` 
2. Only Boolean type given:` https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1665`  even function returning array too.

### Expected result (*)

1. return type must be array too in function doc.
2. Rarse must be Parse

### Actual result (*)

1.  return only Boolean given.
2.

**Comment by engcom-Delta** [comment]
Hi @maheshWebkul721 thank you for your report. Issue was fixed by commit:

- [2957f7782e01c7050b7dcf8562c5a19033bc0972](https://github.com/magento/magento2/commit/2957f7782e01c7050b7dcf8562c5a19033bc0972)
