### ISSUE TITLE
Magento 2 rest api - get orders with custom attributes

### ISSUE THREAD

**Issue by chrispooh15** [magento/magento2#2511]
i would like to have product custom attributes in Magento 2 with rest api.
I use this, but there are no custom attributes in the order result.

curl -X GET -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxx" -H "Cache-Control: no-cache" 'http://xxxxxx.xxx/index.php/rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=status&searchCriteria[filter_groups][0][filters][0][value]=pending'

What do i wrong? I get everything but not the product attributes and the custom product attributes.

**Comment by Vinai** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by chrispooh15** [comment]
Thank you for your answer. I just thought to write here, because it should work while in the rest api code is the function exists for the rest/v1/orders path but in the results it is not inside.

**Comment by Vinai** [comment]
Not sure about custom attributes, but for extension attributes check out the `extension_attributes.xml` configuration. A couple of core modules have that.  
But for your case I suspect the answer can actually be found in `catalog_attributes.xml`...
