### ISSUE TITLE
Magento 2.3.3 unable to apply filter as next page or color on category page

### ISSUE THREAD

**Issue by rosariomarsala** [magento/magento2#25118]
Preconditions

1. Magento CE 2.3.3
2. PHP Version 7.3

Steps to reproduce

1. navigate to categories page
2. click on next page example '2 page' or try to apply some filter example 'black color'

Expected result

1. click on next page '2 page'
2. page scroll-up with loader ajax
3. able to show all products from the '2 page'
4. the page show all products from the '2 page'

Actual result

1. click on next page '2 page'
2. page scroll-up with loader ajax
3. unable to show all products from the '2 page'
4. the page show all products from the '1 page'

**Comment by rosariomarsala** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wwwmage. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wwwmage, here is your [Magento instance](https://i-25118-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25118-2-3-develop.instances.magento-community.engineering/admin](https://i-25118-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rosariomarsala** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @wwwmage. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @wwwmage, here is your [Magento instance](https://i-25118-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25118-2-3-3.instances.magento-community.engineering/admin](https://i-25118-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rosariomarsala** [comment]
I'm not able to reproduce the issue on vanilla Magento instance. we can close ticket. I will check issue for some override in my template or plugin. thanks for support.
