### ISSUE TITLE
Magento2.3.x 多源库存bug:除了默认stock，其他stock不支持bundle product

### ISSUE THREAD

**Issue by Aiweline** [magento/magento2#25116]
**Magento2.3.x多源库存除了默认stock其余stock不支持bundle product**

### Preconditions (*)
1、支持多源库存的magento版本：2.3.X

### Steps to reproduce (*)
1、新建source
2、新建stock，并将设置为main website
3、新建sample product 并assign到非默认stock
4、新建bundle product并选择刚刚新建的sample product

### Expected result (*)

1、期望在新的stock中发现添加的bundle product

### Actual result (*)

1、在frontend尚未发现新建的bundle product

### 序言

**原本想直接修复，但是这将修改magento核心文件，在magento2.3.2时已经发现此问题，今天使用magento2.3.3测试时仍然未修复此问题，特向Magento team提交issue。**

**Comment by krishprakash** [comment]
Hi @Aiweline. can you please explain the issue in English.

**Comment by engcom-Delta** [comment]
Hi @Aiweline thank you for your report. Unfortunately, we are able to process issue only on English and according [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

If you'd like to update the issue, please reopen it.
