### ISSUE TITLE
Perfomance issue on product page with all product type

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#25111]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. go to any product and review all sql for this

### Expected result (*)

1. it should be call query only one time
### Actual result (*)

1. https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Bundle/Model/ResourceModel/Selection.php#L133 calling multiple times to get identifier all block

More info
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php#L71

it calling block->getIdentities()

and in bundle product created plugin for 

https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Bundle/Model/Plugin/Product.php#L35

and it is calling for me 24 times on the product page and 24 times run query for parent id of specific child id.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21949` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amenk** [comment]
@magento-engcom-team what is the status of the internal issue?

**Comment by viniciusbordinhao-blueacorn** [comment]
@magento I am working on this

**Comment by viniciusbordinhao-blueacorn** [comment]
@magento-engcom-team It has been resolving by this commit below:

https://github.com/magento/magento2/commit/c4c453565a7d0e35862bfc7ac0decb1ab60f4c8e

**Comment by amenk** [comment]
Interesting. was this just solved by adding type-hinting in https://github.com/magento/magento2/commit/c4c453565a7d0e35862bfc7ac0decb1ab60f4c8e? That would be great

**Comment by viniciusbordinhao-blueacorn** [comment]
@amenk 

I am sorry for the confusion I have just picked the last commit related to PR.

The complete PR is here: https://github.com/magento/magento2/pull/30746

Next time a simple question without sarcasm must be enough.

**Comment by amenk** [comment]
@viniciusbordinhao-blueacorn Thanks a lot for the clarification. I really did not try to by sarcastic. Sometimes such problems are really fixed by type hinting and the type conversion. Maybe I was a bit to optimistic. :)
