### ISSUE TITLE
Newsletter subscribe and unsubscribe issue for Customer

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25128]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Login as customer on frontend.
2. Click on Newsletter Subscriptions link.
3. Login into admin panel.
4. Disable Newsletter. Navigate to Store -> Configuration -> Customer -> Newsletter -> General Options and set enable to **NO**
5. Now go to opened Newsletter Subscriptions page and try to subscribe or unsubscrbe.
![1](https://user-images.githubusercontent.com/15954089/67046827-a5a04d00-f14e-11e9-93c3-13f98963e6bf.png)
![2](https://user-images.githubusercontent.com/15954089/67046838-aafd9780-f14e-11e9-9775-21d1d92cf234.png)

### Expected result (*)

1. There should be error or no route page.
![5](https://user-images.githubusercontent.com/15954089/67044652-5c4dfe80-f14a-11e9-8ee5-72d41e36afcc.png)

### Actual result (*)

1. Customer is able to subscribe or unsubscribe.
![3](https://user-images.githubusercontent.com/15954089/67046896-cec0dd80-f14e-11e9-96d5-69633f89eeac.png)
![4](https://user-images.githubusercontent.com/15954089/67046900-d1bbce00-f14e-11e9-8340-b58bd887fab0.png)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25128-2-3-develop.instances.magento-community.engineering/admin](https://i-25128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce issue on vanilla instance

**Comment by krishprakash** [comment]
Hi @rahulwebkul. Not able reproduce this issue on 2.3-Develop and 2.3.3 instances as provided steps by you.

**Comment by krishprakash** [comment]
Reproduced now

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21917` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @rahulwebkul 
fyi: @krishprakash

This report was considered as expected behavior but not an issue or bug. From the merchant perspective, it also could be expected behavior.
It is not a problem that the merchant receives additional emails to sent e.g. promo info. 
Otherwise, admin can remove emails from subscribers list and additionally communicate with a customer instead of showing 404 Magento page.

 Magento does not want to change the current result and the issue and related PR should be closed.
