### ISSUE TITLE
While editing options of item in cart, Options not selected at configuration page

### ISSUE THREAD

**Issue by webkul-ratnesh** [magento/magento2#25121]
### Triage Note
- The issue is reproducible on `2.3.3` release version
- The issue is NOT reproducible on `2.3-develop`
- `2.3.3` is not merged into `2.3-develop` at this moment

### Preconditions (*)

**Magento 2.3.3**
1. Must have configurable product in catalog with swatch enabled.
2. In my case product is /jupiter-all-weather-trainer.html of Magento sample data.

### Steps to reproduce (*)

1. Add a configurable product to cart.
2. Goto cart page and try editing that item.
3. At configuration page the previously selected options are not marked as selected.

### Expected result (*)

1. Options should get marked as selected in all type of swatch.

### Actual result (*)

1. Only visual type swatch is marked as selected.
2. Text Swatch not marked as selected.

**Comment by Januszpl** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Januszpl. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Januszpl, here is your [Magento instance](https://i-25121-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25121-2-3-develop.instances.magento-community.engineering/admin](https://i-25121-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25121-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25121-2-3-3.instances.magento-community.engineering/admin](https://i-25121-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21916` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment]
Hello @webkul-ratnesh 

We are not able to reproduce this issue on the latest 2.3-develop branch(2.3.3 code is merged now).

**Manual testing scenario:**

1. Add a configurable product to cart.
![image](https://user-images.githubusercontent.com/51680850/68594540-70162780-04a0-11ea-9772-205b3d5fa33f.png)

2. Go to cart page and try editing that item.
![image](https://user-images.githubusercontent.com/51680850/68594596-90de7d00-04a0-11ea-855d-1290f83d141b.png)

**Result:**
Options are selected as before:
![image](https://user-images.githubusercontent.com/51680850/68594637-abb0f180-04a0-11ea-8dc4-3c0f17d9212a.png)

So i have to close this issue.

Thank you for contribution and collaboration!
