### ISSUE TITLE
Newletter subscription issue

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25126]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Go to any page on frontend and find newsletter section at bottom right of the page.
2. Login into admin panel.
3. Disable Newsletter. Navigate to Store -> Configuration -> Customer -> Newsletter -> General Options and set enable to **NO**
4. Now go to opened page on frontend and try to subscribe.

![1](https://user-images.githubusercontent.com/15954089/67044487-ff524880-f149-11e9-8961-98c6438833b0.png)
![2](https://user-images.githubusercontent.com/15954089/67044494-05482980-f14a-11e9-84a4-3b9af7ac0ae3.png)

### Expected result (*)

1. There should be error or no route page.
![5](https://user-images.githubusercontent.com/15954089/67044652-5c4dfe80-f14a-11e9-8ee5-72d41e36afcc.png)

### Actual result (*)

1. email is getting subscribed
![3](https://user-images.githubusercontent.com/15954089/67044641-52c49680-f14a-11e9-983a-80aae8fc23a4.png)
![4](https://user-images.githubusercontent.com/15954089/67044644-56f0b400-f14a-11e9-9008-2570c16cd4be.png)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25126-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25126-2-3-develop.instances.magento-community.engineering/admin](https://i-25126-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce issue on vanilla instance

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25126-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25126-2-3-develop.instances.magento-community.engineering/admin](https://i-25126-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @rahulwebkul. Not able reproduce this issue on 2.3-Develop and 2.3.3 instances as provided steps by you.

**Comment by krishprakash** [comment]
Reproduced

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21918` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AndreyChorniy** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AndreyChorniy. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndreyChorniy, here is your [Magento instance](https://i-25126-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25126-2-4-develop.instances.magento-community.engineering/admin_3c03](https://i-25126-2-4-develop.instances.magento-community.engineering/admin_3c03)
Login: `9a64b94b` Password: `5ace0217f120`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @rahulwebkul 
fyi: @krishprakash @AndreyChorniy 

This issue has been reviewed on internal Triage meeting with Product Managers.
the same as for https://github.com/magento/magento2/issues/25128

This report was considered as expected behavior but not an issue or bug. From the merchant perspective, it also could be expected behavior.
It is not a problem that the merchant receives additional emails to sent e.g. promo info. 
Otherwise, admin can remove emails from subscribers list and additionally communicate with a customer instead of showing 404 Magento page.

 Magento does not want to change the current result and the issue and related PR should be closed.
