### ISSUE TITLE
[UI Issue] when select Product with custom option (datetime) at backend

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25135]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Create New Product with Custom Option (date time and required it)
3. Create New Order at backend
4. Add Product with custom option

Two asterisk:

![image](https://user-images.githubusercontent.com/8234209/67070863-5b998480-f1ab-11e9-9e53-70c93a0d9cd1.png)

### Expected result (*)

1. One * characater

### Actual result (*)

1. Two * charracter and bad UI

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21920` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @drpayyne, here is your [Magento instance](https://i-25135-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25135-2-3-develop.instances.magento-community.engineering/admin](https://i-25135-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by drpayyne** [comment]
@edenduong The asterisks appear only if a price is set for the custom option date time. _Even_ if the custom option is set to required.

**Comment by drpayyne** [comment]
@magento-engcom-team Why wasn't this auto closed when https://github.com/magento/magento2/pull/25149 was merged? :thinking:
