### ISSUE TITLE
In mobile view, go to mini cart and edit the quantity of product, at that time update button hide the delete button

### ISSUE THREAD

**Issue by Khushbu-Webkul-QA** [magento/magento2#25137]
### Preconditions (*)

1. magento version: 2.3.3/2.2.9
2. php version: 7.2/7.1
3. mode: production
4. Js, CSS, HTML merged and minified
5. Flat catalog/category – Yes

### Steps to reproduce (*)

1.  in mobile view
2.  add product into cart
3. go to minicart
4. edit the product quantity
5. update button hide the delete button

### Expected result (*)

1. update and delete both button should display
![Screenshot (54)](https://user-images.githubusercontent.com/45037885/67072172-e7a6ae80-f1a1-11e9-8045-29fb195065e4.png)

### Actual result (*)

1. in mini cart delete button hide under the update button
![Screenshot (53)](https://user-images.githubusercontent.com/45037885/67072236-0c028b00-f1a2-11e9-9efc-c18552a26ca7.png)

**Comment by Khushbu-Webkul-QA** [comment]
yes, give me instance

**Comment by Khushbu-Webkul-QA** [comment]
@magento give me instance

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25137-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25137-2-3-develop.instances.magento-community.engineering/admin](https://i-25137-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21968` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheers-kensium** [comment]
Alignment issue

![image](https://user-images.githubusercontent.com/50358141/67265865-68c8b300-f4cc-11e9-8ff4-adc5efefccef.png)

**Comment by sdzhepa** [comment]
fixed and delivered in https://github.com/magento/magento2/pull/25206
