### ISSUE TITLE
Fatal error: Uncaught TypeError: 

### ISSUE THREAD

**Issue by Cloudwaysaneeq** [magento/magento2#25141]
I am trying to log in from my Magento admin panel and no products are being displayed.
gets an error  /home/manomark/public_html/vendor/magento/framework/Encryption/Encryptor.php on line 274
 
![image](https://user-images.githubusercontent.com/50991101/67078999-d6fb3600-f1ab-11e9-8b43-7e390046f691.png)

**Comment by makkoff** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @makkoff. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @makkoff, here is your [Magento instance](https://i-25141-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25141-2-3-develop.instances.magento-community.engineering/admin](https://i-25141-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @Cloudwaysaneeq thank you for your report. I cannot reproduce issue according your description on clean 2.3-develop.
If you'd like to [update](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) issue , please reopen it.
