### ISSUE TITLE
"Redirect to CMS-page if Cookies are Disabled" is "No" but it still redirect

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25148]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store-> Configuration
3. General->Web
4. "Browser Capabilities Detection" , "Redirect to CMS-page if Cookies are Disabled" is "No"

![image](https://user-images.githubusercontent.com/8234209/67088492-7b42a400-f1cf-11e9-818e-01731bd51816.png)

5. Go to frontend
6. Disable cookie
7. Signin customer

### Expected result (*)

1. No redirect to Cookie CMS-page

### Actual result (*)

1. Redirect to Cookie CMS-page

**Comment by ajijshekh123** [comment]
give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25148-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25148-2-3-develop.instances.magento-community.engineering/admin](https://i-25148-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have verified this issue after disabled cookie in my browser then follow the same scenario which one added by the Reporter.

**See the attached video:**

![Enable Cookie_Issue](https://user-images.githubusercontent.com/24711761/67090527-f902b180-f1c7-11e9-83d3-56fb54f893df.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21922` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
