### ISSUE TITLE
 Fatal error: Uncaught TypeError: /home/manomark/public_html/vendor/magento/framework/Encryption/Encryptor.php on line 274

### ISSUE THREAD

**Issue by Cloudwaysaneeq** [magento/magento2#25140]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by ghost** [comment]
no steps have been provided in the description
