### ISSUE TITLE
Disabled swatch option shouldn't show box-shadow on click

### ISSUE THREAD

**Issue by drpayyne** [magento/magento2#25144]
### Preconditions 
1. `2.3-develop` branch

### Steps to reproduce
1. Login to Admin panel
2. Navigate to Stores -> Catalog -> Inventory
3. Change _Display Out of Stock Products_ dropdown to _Yes_
4. Navigate to Stores -> Attributes -> Product
5. Edit `color` attribute's _Catalog Input Type for Store Owner_ to _Visual Swatch_
6. Add multiple swatches with colors
7. Create a new configurable product
8. Click _Create Configurations_
9. Choose `color` and click _Next_
10. Select the created attribute values and click _Next_
11. Provide positive quantities for swatches except, set 0 for one swatch, and click _Next_
12. Click _Generate Products_
13. Save product and choose _Add configurable attributes to the current Attribute Set_ in the popup
14. Flush the cache, and navigate to the product in Storefront
15. Click the disabled swatch

### Expected result
- On clicking disabled swatch, box shadow **_MUST NOT_** appear
![image](https://user-images.githubusercontent.com/22623301/67085861-43326580-f1bd-11e9-82d8-62e337ac3d37.png)

### Actual result
- On clicking disabled swatch, box shadow appears
![image](https://user-images.githubusercontent.com/22623301/67085742-05cdd800-f1bd-11e9-9641-218a5322bdeb.png)

**Comment by Karlasa** [comment]
@drpayyne 

box-shadow is part of accessibility and is used in example to point out focus location if user is using keyboard only.

Due that I think this issue is not valid. 

 Feel free to re-open this issue if you thing otherwise or if you have any other questions feel free to ask.

Feel free to 
Cheers,
Karla

**Comment by drpayyne** [comment]
@Karlasa I didn't know that regarding box-shadow, thank you. Although, what is need to focus on something when there exists no functionality in it? This is pretty much a disabled button which should have **no** visible changes on hover, focus, active, etc., right?

**Comment by Karlasa** [comment]
good point...

tabindex="-1" and pointer-event: none; for disabled swatch would be an option

**Comment by drpayyne** [comment]
Thank you @Karlasa, I'll add your two suggestions and push the code

**Comment by drpayyne** [comment]
@krishprakash Could you please review and confirm my issue, thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21940` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Karlasa** [comment]
PR #25145 fixed the issue, Will close it for now.
