### ISSUE TITLE
Color swatches

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2514]
I know this is not the right place but can anybody tell me where i can enable/configure color swatches in Magento 2?

I did not find any info oin the forum...

**Comment by SidneyBilliet** [comment]
In Magento 1 this setting can be enabled under system/config/catalog/configurable swatches.
It shows a swatch image for product selection with configurable products, for example "color" kan have color swatches

**Comment by SidneyBilliet** [comment]
Closed it by accident. Still would like to know...

**Comment by buskamuza** [comment]
Admin Panel > Stores > Attributes > Product
Edit/add necessary Attribute.
"Catalog Input Type for Store Owner": Visual Swatch or Text Swatch

**Comment by SidneyBilliet** [comment]
@buskamuza,

Thank you very much!

**Comment by SidneyBilliet** [comment]
Closing this ticket

**Comment by dimple-vasoya** [comment]
How to fetch the visual color swatch value (color hash) of an attribute (color) option?

**Comment by jajanka** [comment]
How colour swatches can be shown in Product List widget? In product listing it works, line responsible for this is $block->getProductDetailsHtml($_product);
