### ISSUE TITLE
Configurable products go Out of Stock with MSI

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#25151]
### Preconditions (*)
1. Magento 2.3.3 CE
2. MSI enabled

### Steps to reproduce (*)
1. Configure Magento to allow backorders
2. Create an extra stock in MSI
3. Add a source to this new stock
4. Create a configurable product with simples
5. Add the newly created source to these simples, with the status In Stock, qty doesnt matter.
6. Remove the default source from this product if its assigned
7. Set the configurable product to In Stock
8. Edit a simple product, by just resaving the product
9. The configurable product will go Out of Stock

### Expected result (*)
1. The configurable product to stay in stock, cause the simples are in stock and backorders are allowed.

### Actual result (*)
1. The configurable product goes out of stock and will not be available for order at the frontend.

**Comment by gwharton** [comment]
I think its because you remove from default source. I have all products in default source with in stock set, but then have my real source linked to frontend website. If i remove products from default source they go out of stock so i just leave them there.

**Comment by engcom-Delta** [comment]
Hi @jorgb90 thank you for your report. It is MSI related issue. 
If [comment](https://github.com/magento/inventory/issues) doesn't help you, please, create issue in appropriate repository [Inventory](https://github.com/magento/inventory/issues)
