### ISSUE TITLE
Form Validation bug on Paypal Pro module 100.3.3 - resolved. 

### ISSUE THREAD

**Issue by mrossh** [magento/magento2#25155]
### Preconditions (*)

1. Magento 2.3.3 OS
2. Paypal payment Module 100.3.3

### Steps to reproduce (*)

1. The bug has been resolved. 

### Expected result (*)

1. [Screenshots, logs or description]
Module and version: 
![image](https://user-images.githubusercontent.com/46603128/67129805-8f85a180-f1cd-11e9-8afc-a4874790e172.png)
Original code: 
![image](https://user-images.githubusercontent.com/46603128/67129864-b9d75f00-f1cd-11e9-9a95-0480541c7c2a.png)
Fixed code. the cardInfo.title returns string and allowedTypes[i].type returns array.  You can not check equality between array and string rather check if string exist in array
![image](https://user-images.githubusercontent.com/46603128/67129889-ceb3f280-f1cd-11e9-9785-cf3b29c46596.png)

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Delta** [comment]
Hi @mrossh thank you for your report. I am not able to reproduce issue by steps you described on clean 2.3-develop
Inside `for` loop `allowedTypes[i].type` returns sting.
![#25155Issue](https://user-images.githubusercontent.com/51681379/67390804-02b05e80-f5a6-11e9-894f-e3e6f372d746.png)

![#25155issue_2](https://user-images.githubusercontent.com/51681379/67390808-05ab4f00-f5a6-11e9-8faa-39a0ad0cb956.png)

![#25155issue_3](https://user-images.githubusercontent.com/51681379/67390815-080da900-f5a6-11e9-9e3b-7e9114b19d23.png)

If you'd like to update the issue, please reopen it.
