### ISSUE TITLE
Mail not working 

### ISSUE THREAD

**Issue by domnoble** [magento/magento2#25153]
### Preconditions (*)
1. Magento 2.3.3
2. docker-library PHP 7.2

### Steps to reproduce (*)
1. Attempt to send email or submit an order with default settings using sendmail or using any 3rd party SMTP module

### Expected result (*)
1. email is sent without producing an error
2. users are returned to the success page

### Actual result (*)
1. using 3rd party plugins we can send an email but it still produces the error
2. using sendmail directly produces the error and doesnt send the email
`
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template::setVars() must be of the type array, null given, called in /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 368 and defined in /usr/local/apache2/htdocs/vendor/magento/module-email/Model/Template.php:403 Stack trace: #0 /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php(368): Magento\Email\Model\Template->setVars(NULL) #1 /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php(380): Magento\Framework\Mail\Template\TransportBuilder->getTemplate() #2 /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Magento\Framework\Mail\Template\TransportBuilder->prepareMessage() #3 /usr/local/apache2/htdocs/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(91): Magento\Framework\Mail\Template\TransportBuilder->getTransport() #4 /usr/local/apache2/htdocs/vendor/magento/module-sales/Model/Order in /usr/local/apache2/htdocs/vendor/magento/module-email/Model/Template.php on line 403
`

**Comment by domnoble** [comment]
duplicate of #24448

**Comment by domnoble** [comment]
so we managed to find the issue after investigating the file which was throwing the error i came to the conclusion that it must be missing some data with the email template or something must be wrong, in the end it turned out to be an error in the migration, what had happened is during the migration it must have moved over the sender email, but on the end of the email address there was a comma, which i assume made it think there was a null item after the email address, correcting the email sender fixed this issue

**Comment by vishalpatel14** [comment]
This issue still exist. Its not regarding any Email sender name issue or any "," at the end of string. Its the core 2.3.3 Bug. Below is the stack trace for the issue.

<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template::setVars() must be of the type array, null given, called in vendor/magento/framework/Mail/Template/TransportBuilder.php on line 368 and defined in vendor/magento/module-email/Model/Template.php:403
Stack trace:
#0 vendor/magento/framework/Mail/Template/TransportBuilder.php(368): Magento\Email\Model\Template-&gt;setVars(NULL)
#1 vendor/magento/framework/Mail/Template/TransportBuilder.php(380): Magento\Framework\Mail\Template\TransportBuilder-&gt;getTemplate()
#2 vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Magento\Framework\Mail\Template\TransportBuilder-&gt;prepareMessage()
#3 vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(91): Magento\Framework\Mail\Template\TransportBuilder-&gt;getTransport()
#4 vendor/magento/mod in <b>vendor/magento/module-email/Model/Template.php</b> on line <b>403</b><br />

**Comment by jayanta88** [comment]
Hello,

Can anyone tell me if this is fixed in Magento's latest version or not. Also how to add this fix in my 2.3.3 version without editing the core file.

Thanks
