### ISSUE TITLE
How to "export" this Docker container with Bitnami + Magento 2 to the WWW / a regular hosting provider using FTP?

### ISSUE THREAD

**Issue by bas1425** [magento/magento2#25157]
### Preconditions (*)
I am running 10.14.1 MacOS Mojave. I am using the latest version of Docker and this Bitnami container. I followed the guide; as such it is a very 'vanilla' install... 
+ 
I am very new to all of this... 

### Steps to reproduce (*)
See below for details. If you need more, ask me.

### Expected result (*)

How to "export" this Docker container with Bitnami + Magento 2 to the WWW / a regular hosting provider using FTP?

### Actual result (*)

I get a folder with all sorts of files running the command below. How do I proceed? 

---

Hi there! 

A **big** thank you to everyone for creating and sharing all this technology and information... Absolutely wonderful... 

I am trying to build a Magento2 store using Docker and Bitnami. I have used this "guide" and it works perfectly as I am now able to locally run and modify this Magento2 store. (I have edited the "volumes" of mariadb and magento in docker-compose.yml as outlined in the guide to make everything persistent.)

_Eventually, I would like this store to be accessible via the World Wide Web... 
What is the best way to do this?_ 

I can upload to my hosting provider using FTP (via f.i. Filezilla or Cyberduck). This hosting provider has all the required "technology" in place to run Magento2 as it also allows the installation of Magento2 via "Installatron". 

It unfortunately seems as if this hosting provider doesn't allow the option to upload / run "Docker" directly... 

_What's the best way to solve this issue?_ 

I tried "exporting" the Docker container using the command below. It does create a +-579,5 MB folder that seems to contain all Magento2 related files and some other files as well. See list of files below as well.

`sudo docker cp NAMEOFPROJECT_magento_1:/ /Users/USERNAME/Documents/Docker/PROJECTFOLDER/`

Should indeed copy this to the PUBLIC_HTML folder of my website using FTP? I guess I should also "copy paste" the mysql database (thus image mariadb?)? 

Thanks a lot in advance. I look forward to learn once again. _As such, forgive me for somehting seemingly obvious..._ 

**Thanks again,** 
Bas

---

Here's the output of `docker ps`

CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                      NAMES
f005be5b3977        bitnami/magento:2         "/app-entrypoint.sh …"   6 hours ago         Up 6 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   NAMEOFPROJECT_magento_1
4f10707586ba        bitnami/mariadb:10.2      "/entrypoint.sh /run…"   6 hours ago         Up 6 hours          3306/tcp                                   NAMEOFPROJECT_mariadb_1
19b4a0f68709        bitnami/elasticsearch:6   "/entrypoint.sh /run…"   6 hours ago         Up 6 hours          9200/tcp, 9300/tcp                         ]]

Output of `docker info`

Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 19
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.855GiB
 Name: docker-desktop
 ID: QLDA:3MH6:3MWI:W2E3:IN2P:5EAD:KJV3:4FBP:SCA7:426R:IDOL:T6EW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 53
  Goroutines: 64
  System Time: 2019-10-18T22:12:56.0974104Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

Here's the output of 
`ls /Compiled`

app-entrypoint.sh		entrypoint.sh			licenses			mysql-client-inputs.json	run.sh				usr
bin				etc				magento-init.sh			opt				sbin				var
bitnami				home				magento-inputs.json		proc				srv
boot				lib				media				root				sys
dev				lib64				mnt				run				tmp

![Content of folder  Compiled  : result of above command](https://user-images.githubusercontent.com/56743671/67139516-6dcdfe00-f251-11e9-9ad6-6f98ad981680.png)

**Comment by dmytro-ch** [comment]
Hi @bas1425,
the GitHub issue tracker is intended for Magento Core issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) for advice or general discussion about this.

Thank you!
