### ISSUE TITLE
Terms and Conditions css height do nothing on frontend

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25167]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Login into admin panel.
2. Enable Terms and Conditions on checkout page. Navigate to **Store > Configuration > Sales > Checkout > Checkout Options** and Enable Terms and Conditions
3. Now create any new condition. Navigate to Store > Terms and Conditions > Add New Condition
4. Set height 300px in this condition. I created new condition named **"Privacy Policy"**
5. Now add product in cart and go to checkout page.
6. Go to final step and click on "Privacy Policy".

![Selection_014](https://user-images.githubusercontent.com/15954089/67159962-115e0200-f369-11e9-8c45-7d22d8c82794.png)
![Selection_015](https://user-images.githubusercontent.com/15954089/67159966-18851000-f369-11e9-9e69-e40afdd06bf4.png)
![Selection_016](https://user-images.githubusercontent.com/15954089/67159968-1e7af100-f369-11e9-81e5-36a21c0e577f.png)

### Expected result (*)

1. Content height should be 300px in opened modal box.
![Selection_018](https://user-images.githubusercontent.com/15954089/67159986-4b2f0880-f369-11e9-87f7-1566dcfdc108.png)

### Actual result (*)

1. Height is not set in opened modal box.
![Selection_017](https://user-images.githubusercontent.com/15954089/67159999-6437b980-f369-11e9-84e7-cdc8f8fbde22.png)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25167-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25167-2-3-develop.instances.magento-community.engineering/admin](https://i-25167-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce issue on magento vanilla instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21943` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your report. 
The issue has been fixed in magento/magento2#25168 by @rahulwebkul in 2.3-develop branch
Related commit(s):
 - [a9d641617a5d384136b56a23d7fcdef54a24df87](https://github.com/magento/magento2/commit/a9d641617a5d384136b56a23d7fcdef54a24df87)
 - [66613c8ef36ff6ff6110e4665d96a56df7280cca](https://github.com/magento/magento2/commit/66613c8ef36ff6ff6110e4665d96a56df7280cca)

The fix will be available with the upcoming 2.3.4 release.
