### ISSUE TITLE
Issue with Guest Checkout when disabled guest checkout from admin

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25173]
There is no proper check for guest checkout at the time of order placement.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Add product in cart from frontend as a guest.
2. Go to checkout page
3. Now login into Admin.
4. Disable Guest Checkout from admin. Navigate to **Store > Configuration** then **Sales > Checkout** now find Allow Guest Checkout in **Checkout Options** section and disable it.
5. Now go to opened guest checkout page and try to place order
![1](https://user-images.githubusercontent.com/15954089/67163501-5b58df00-f38d-11e9-86b1-ea04835c7826.png)
![2](https://user-images.githubusercontent.com/15954089/67163503-5eec6600-f38d-11e9-94d8-4697911e9483.png)

### Expected result (*)

1. Order should not be placed and there should be an error like "Guest checkout is disabled."
![4](https://user-images.githubusercontent.com/15954089/67163506-6c095500-f38d-11e9-89bd-38b32d0f0443.png)

### Actual result (*)

1. Guest is able to place the order.
![3](https://user-images.githubusercontent.com/15954089/67163507-70ce0900-f38d-11e9-9825-e30b437b279c.png)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25173-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25173-2-3-develop.instances.magento-community.engineering/admin](https://i-25173-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce this issue on vanilla instance

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25173-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25173-2-3-develop.instances.magento-community.engineering/admin](https://i-25173-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21945` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by KarthickSelvam** [comment]
Is this fixed?

**Comment by sdzhepa** [comment]
Hello @rahulwebkul 
fyi: @krishprakash, @KarthickSelvam

This report was considered as expected behavior but not an issue. From the merchant perspective, it also could be expected behavior.
After disabling Guest Checkout current customers should be able to complete checkout.

 Magento does not want to change the current result and the issue and related PR should be closed.
