### ISSUE TITLE
Website Hang issue

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#25187]
Preconditions (*)
Magento 2.7.7

Steps to reproduce (*)
When i Open Website it Hangs while loading and you can't scroll the page while its loading.
Try Scrolling the page and it just get stuck.
We have this Script that caught my attention which is taking too long to load and is causing the issue. The Script load from here : https://magento-optimization.dev/events

Expected result (*)
Website should open and work without hanging, the issue is caused by script that is getting loaded from Magento side.

**Comment by terrybakshi** [comment]
HI can anyone help pls
![Screenshot_8](https://user-images.githubusercontent.com/13229022/67276530-9afc0400-f510-11e9-87f9-745a3d5a8c4a.png)

**Comment by engcom-Charlie** [comment]
Hello @terrybakshi 

Thank you for contribution and collaboration!

> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!
