### ISSUE TITLE
Special from / to date wrong on administrator Dutch locale

### ISSUE THREAD

**Issue by WalterSmulders** [magento/magento2#25182]
### Preconditions (*)

Magento 2.3.3 & 2.3-develop

### Steps to reproduce (*)

1. Login to admin panel
2. Use account with Dutch locale
3. Open a product to edit
4. Insert special price for product and leave Special Price From empty or fill in date
5. Save product
6. Special price from and/or Special price to will be wrong

### Expected result (*)

1. Special from / to date should be correct

### Actual result (*)

1. Special price from/to are wrong, mostly 1-2 years in the future, but I have also seen dates in the past

**Comment by Shubham0492** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-25182-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25182-2-3-develop.instances.magento-community.engineering/admin](https://i-25182-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by asim-vax** [comment]
We are having the same issue with UK/GB locales, has there been any progress on this?
It is hard work to have to delete dates that shouldn't be there (especially in EE, where there is no special_from_date option in the admin)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23224` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bubasuma** [comment]
Internal Magento team is working on this issue right now.

**Comment by jwbos-uhg** [comment]
I have exactly the same problem in the Magento 2.2.10 version, before the update everything was working fine (Updated from Magento 2.2.5, Admin in Dutch locale)

**Comment by RaphaelBronsveld** [comment]
Hi all,

We are also experiencing the same issue (M2.3.3), but it seems to be a general date input issue, not specifically related to the special price management.

Our customer also reported the issue for the following module: https://github.com/magefan/module-blog (published date field).

**Comment by magento-engcom-team** [comment]
Hi @WalterSmulders. 

Thank you for your report and collaboration!

The issue was fixed by Magento team.

**Comment by WalterSmulders** [comment]
Is there a pull request / link to the changes made?

**Comment by Jeroenll** [comment]
@magento-engcom-team Please post the commit references where this is fixed.

**Comment by magento-engcom-team** [comment]
Hi @WalterSmulders. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [b804ffa4a6dfcf50068504b0cdc2e047d87c1d86](https://github.com/magento/magento2/commit/b804ffa4a6dfcf50068504b0cdc2e047d87c1d86)
 - [7bde3dc5311b6085a489962180d5c0bcdf3624c9](https://github.com/magento/magento2/commit/7bde3dc5311b6085a489962180d5c0bcdf3624c9)
 - [e5752a1536975af1550ba9ad832186733fc00910](https://github.com/magento/magento2/commit/e5752a1536975af1550ba9ad832186733fc00910)

The fix will be available with the upcoming `2.3.5` release.

**Comment by magento-engcom-team** [comment]
Hi @WalterSmulders. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.4.0` release.

**Comment by Jeroenll** [comment]
@magento-engcom-team Commits show a 404 page. Are they already merged?

**Comment by ericclaeren** [comment]
Did some digging:

**Think it's this commit:**
https://github.com/magento/magento2/commit/3096b56dcebdd96d864ea09059997e4021333403

**The merge:**
https://github.com/magento/magento2/commit/d40c5fcdd290f0e99cefe01f27abb239016d7a45

It seems a direct merge of a remote branch, so don't think there's a pull request. Also a bit disappointed that it's planned for 2.4.x instead of the 2.3.x branch.

You can add create a patch by following this link:
https://github.com/magento/magento2/commit/3096b56dcebdd96d864ea09059997e4021333403.patch

Unfortunately it doesn't apply on 2.3.3.

**Comment by tdgroot** [comment]
Related PR: #27311

**Comment by TOIVI291** [comment]
I've edited and added the files in the commit that @ericclaeren shared, but it doesn't change anything. Magento version: 2.2.10

**Comment by mdehaan** [comment]
> Hi @WalterSmulders.
> 
> Thank you for your report and collaboration!
> 
> The issue was fixed by Magento team.
> 
> The fix will be available with the upcoming `2.4.0` release.

@magento-engcom-team 

I have updated to Magento 2.4 and the date issue on promo rules still exists.

**Catalog price rule:**

1. ![catalog price rule pre save - Dutch locale](https://user-images.githubusercontent.com/581336/90491711-97d9a080-e140-11ea-837f-944179e12d15.PNG)
2. ![catalog price rule after save - Dutch locale](https://user-images.githubusercontent.com/581336/90491717-9ad49100-e140-11ea-8cf8-bd2b9402e1be.PNG)
3. ![catalog price rule after save - English US locale](https://user-images.githubusercontent.com/581336/90491722-9c9e5480-e140-11ea-9979-20ada31dfb4a.PNG)

**Comment by Aquive** [comment]
@ericclaeren I tested the changes on 2.3.5 it didn't solve the issue either.

**Comment by slackerzz** [comment]
@magento give me 2.4-develop instance

**Comment by WalterSmulders** [comment]
1 year later, and still not fixed in 2.4.1
https://github.com/magento/magento2/issues/30382
https://github.com/magento/magento2/issues/28801

**Comment by choussamaster** [comment]
I confirm the bug still open on magento 2.4.1 french language, for expiration date field on edit backoffice user page
![image](https://user-images.githubusercontent.com/750352/113263133-af315c80-92d1-11eb-9a70-f0028bbcdba1.png)

**Comment by nuzil** [comment]
I can also confirm it for 2.4.3 with german locale

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Dear @WalterSmulders @thomas-harding @nuzil,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
