### ISSUE TITLE
URL rewrites are not being generated when Single-Store Mode is enabled

### ISSUE THREAD

**Issue by paul-blundell** [magento/magento2#25190]
### Preconditions (*)
1. Magento (Open Source) 2.3.3
2. PHP 7.1.32
3. MySQL 5.7.15

### Steps to reproduce
1. Ensure Single-Store Mode is disabled
2. Change the store code and store view code so they are not default (unsure if this step is needed)
3. Add a new product
4. Edit product and in drop down change to your store view.
5. Change product title
6. Confirm all changes are reflected on the frontend.
7. Enable Single-Store mode
8. Change product title of previously created product, note how this doesn't change on frontend.
9. Add a new simple product and specify a url_key
10. Check the url_rewrite database table and search the request_path column for the url_key you entered.

### Expected result
New URL key should be in the database table

### Actual result
Nothing is updated in the database

Once I disable the Single-Store mode and repeat the steps. It works perfectly and the url_rewrite table is updated as soon as I save. 

There seems to be an issue if you enable Single-Store mode after previously using multi-store mode and override values on a store level.

**Comment by paul-blundell** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell, here is your [Magento instance](https://i-25190-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25190-2-3-develop.instances.magento-community.engineering/admin](https://i-25190-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by paul-blundell** [comment]
I have been able to reproduce on the fresh instance of the develop branch. See my updated description for steps on how to reproduce.

I believe there is an underlying issue with Single-Store mode and others have reported similar issues: https://github.com/magento/magento2/issues/5929

**Comment by engcom-Delta** [comment]
Hi @paul-blundell thank you for your report. Unfortunately, I am not able to reproduce issue by steps you described on clean 2.3-develop.
![#25190issue](https://user-images.githubusercontent.com/51681379/67386267-4c487b80-f59d-11e9-8715-0bf3f4259e85.gif)

If you'd like to update the issue, please reopen it.

**Comment by paul-blundell** [comment]
@engcom-Delta Did you do step 4? With Single-Store mode set to No, did you change the scope to the store view, then edit & save the product. This is the critical step to reproducing this.

**Comment by engcom-Delta** [comment]
@paul-blundell I did step 4. But I didn't experience issue with generating URL keys. Tested with Enable Single-Store Mode=No and Enable Single-Store Mode=Yes. 
I noticed another issue:  **Product Name** cannot be changed in Single-Store Mode if it was edited in store view level( Default Store View in my case). For this case you could create separate issue.

**Comment by cmbilisim** [comment]
I have same problem on magento 2.3.3 release.

Additionally when I changed auto generated url key, its add new record for url key

**Comment by shrma-smit** [comment]
Please check this link for a workaround.

https://magento.stackexchange.com/questions/300948/magento-2-issue-with-product-url-rewrite-on-single-store-mode

**Comment by twoatechguy** [comment]
This is happening to me in 2.3.3 release as well. Quite unfortunate this bug with single store mode has gone on for years without resolution.

**Comment by victortodoran** [comment]
**\Magento\Catalog\Model\Product::getStoreIds()** this is the method were things go south.
More specifically the following:
`if ($this->_storeManager->isSingleStoreMode()) {
                    $websiteIds = array_keys($websiteIds);
 }`

**Comment by MatthijsBreed** [comment]
Can confirm @victortodoran 's comment
`public function getStoreIds()
    {
        if (!$this->hasStoreIds()) {
            $storeIds = [];
            if ($websiteIds = $this->getWebsiteIds()) {
                if ($this->_storeManager->isSingleStoreMode()) {
                    $websiteIds = array_keys($websiteIds);
                }
                foreach ($websiteIds as $websiteId) {
                    $websiteStores = $this->_storeManager->getWebsite($websiteId)->getStoreIds();
                    // phpcs:ignore Magento2.Performance.ForeachArrayMerge
                    $storeIds = array_merge($storeIds, $websiteStores);
                }
            }
            $this->setStoreIds($storeIds);
        }
        return $this->getData('store_ids');
    }`
When creating a new product with single-store mode enabled, $this->getWebsiteIds() returns an array [ 0 => "1" ], containing the main store as expected
Calling array_keys() makes this [ 0 => 0 ], the global scope, I don't know why Magento would do this

Magento\CatalogUrlRewrite\Model\ProductScopeRewriteGenerator::generateForGlobalScope doesn't generate rewrites this way, since the only store_id it gains is the global scope:
`public function generateForGlobalScope($productCategories, Product $product, $rootCategoryId = null)
    {
        $productId = $product->getEntityId();
        $mergeDataProvider = clone $this->mergeDataProviderPrototype;

        foreach ($product->getStoreIds() as $id) {
            if (!$this->isGlobalScope($id) &&
                !$this->storeViewService->doesEntityHaveOverriddenUrlKeyForStore(
                    $id,
                    $productId,
                    Product::ENTITY
                )) {
                $mergeDataProvider->merge(
                    $this->generateForSpecificStoreView($id, $productCategories, $product, $rootCategoryId)
                );
            }
        }

        return $mergeDataProvider->getData();
    }`

Commenting out the lines `if ($this->_storeManager->isSingleStoreMode()) { $websiteIds = array_keys($websiteIds); }` results in url-rewrites being properly generated for new products

**Comment by nadroj467** [comment]
I have experienced same issue in Magento 2.3.3 commenting the above line as mentioned by @MatthijsBreed resolved the issue for me. Thanks
