### ISSUE TITLE
DHL Shipping

### ISSUE THREAD

**Issue by insaurabh** [magento/magento2#25192]
### Preconditions (*)
Magento (Open Source) 2.2.4 & 2.3.x
PHP 7.1.32
MySQL 5.7.15

**Summary of the issue**
In  Non-Document, we don't get the desired Allowed Methods:

### Steps to reproduce (*)
Content-type in the setting of DHL have two options
- Document
- Non-Document
But while we make a selection of Document we get the desired Allowed methods:

### Expected result (*)
![image](https://user-images.githubusercontent.com/51680850/69950392-fcde5f00-14fb-11ea-8591-aca88898be61.png)

### Actual result (*)
![Screenshot_2](https://user-images.githubusercontent.com/26545067/67205075-8e9e7b00-f42c-11e9-9d3a-08622ac5e1d7.png)

but in case of Non-Document, we don't get the desired Allowed Methods:

![Screenshot_3](https://user-images.githubusercontent.com/26545067/67205207-db825180-f42c-11e9-867e-550f17dca5af.png)

I had a word with the DHL team and they said these settings are incorrect. We should be able to get the delivery type options of Document in Non-Document as well.

**Comment by insaurabh** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maddyBoy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maddyBoy, here is your [Magento instance](https://i-25192-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25192-2-3-develop.instances.magento-community.engineering/admin](https://i-25192-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @maddyBoy 
Could you explain what do you want to see in Non-Document Allowed Methods section?
And could you give me any links that confirm this information?

**Comment by insaurabh** [comment]
Hey @engcom-Charlie 
I would like to have the option of normal Domestic Express in Non-Document panel. As the one we've is restricted till the delivery of 12 PM due to which it's charging more cost from the client. 

I had a word with DHL about this and they've mentioned this specifically. 

![Screenshot_4](https://user-images.githubusercontent.com/26545067/67299224-0098c200-f50a-11e9-999d-4ef11b7d8464.png)

**Comment by ghost** [comment]
@maddyBoy will adding the mentioned option of Domestic Express in Non-Document panel will resolve this issue?

**Comment by insaurabh** [comment]
@vishalverma279 Yeah, that would resolve the issue. Possible to share some timeframe over this?

**Comment by ghost** [comment]
@maddyBoy will this work:
![image](https://user-images.githubusercontent.com/38008540/67397180-706c8280-f5c6-11e9-8158-9fea2b5c7d11.png)

**Comment by insaurabh** [comment]
Yeah, that should work, @vishalverma279

**Comment by insaurabh** [comment]
#25872

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29295` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @insaurabh. Thank you for your report. 
The issue has been fixed in magento/magento2#25244 by @vishalverma279 in 2.4-develop branch
Related commit(s):
 - [4ac223bb23fce658e1e14b01e3f75bfb44b1e0fb](https://github.com/magento/magento2/commit/4ac223bb23fce658e1e14b01e3f75bfb44b1e0fb)
 - [a220df1e08597bd04e97f531e654d11937725796](https://github.com/magento/magento2/commit/a220df1e08597bd04e97f531e654d11937725796)
 - [ab97e975d40c248a5b54648e67f0b312030113d0](https://github.com/magento/magento2/commit/ab97e975d40c248a5b54648e67f0b312030113d0)
 - [cef3fe7efc2403feec6eb550348d03ecb25c6f95](https://github.com/magento/magento2/commit/cef3fe7efc2403feec6eb550348d03ecb25c6f95)

The fix will be available with the upcoming 2.4.2 release.
