### ISSUE TITLE
core_url_rewrite.request_path should be case-sensitive

### ISSUE THREAD

**Issue by colinmollenhour** [magento/magento2#252]
I tried to add two rewrites for the same url with different case (customers kept entering it wrong) and I couldn't because the collation on the request_path is utf8_general_ci (ci for case-insensitive) so the unique index prevented it. I changed the collation like so:

    ALTER TABLE  `core_url_rewrite` CHANGE  `request_path`  `request_path` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT  'Request Path'

And was then able to add the rewrite. There may be other unexpected side-effects of this column being ci, and I can't see any harm in making it case-sensitive.

**Comment by verklov** [comment]
There is a ticket MAGETWO-23727 entered in the product backlog. We are closing this request on the GitHub now. We will update you on any changes on this request after the PM responsible for the area reviews it and makes a decision according to the priorities we have.

**Comment by kwasseem** [comment]
Hi @verklov , any updates on this?
Also, how can I view the ticket MAGETWO-23727 ? (may be I'm searching at the wrong place for it)

Thanks!
