### ISSUE TITLE
Bundle Item Qty is sent to Validate Child Qty

### ISSUE THREAD

**Issue by Orstio** [magento/magento2#25201]
### Preconditions (*)

1. Magento 2.3.2
2. A Bundle product where at least one child product has a qty step set greater than 1.

### Steps to reproduce (*)

1.  Put one bundle product as described above in the cart.
2.  The cart page will display an error message saying that the Qty is not correct.

### Expected result (*)

1. If the Qty of the child item is a multiple of the value for that child item, it should not display the error.

### Actual result (*)

1. An error message displays saying "You can buy this product only in quantities of X at a time.'

The error in the code for this is quite simple:

vendor/magento/module-catalog-inventory/Model/Quote/Item/QuantityValidator.php (Line 227):

`$quoteItem->getData('qty'),`

Should be:

`$option->getValue(),`

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25201-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25201-2-3-develop.instances.magento-community.engineering/admin](https://i-25201-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
It is not displaying an error. I have followed the same scenario as per the defined steps.
**See attached screenshot:**

![Child Bundle Product Issue](https://user-images.githubusercontent.com/24711761/67260111-29439c00-f4b7-11e9-9ba6-1b062d67e17b.png)

**Comment by ajijshekh123** [comment]
@Orstio - Till now, You haven't updated me about this issue. If you have found again this issue you can open it.
