### ISSUE TITLE
Subscribed to Newsletter Label and respective checkbox not aligned proper  

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#25207]
Subscribed to Newsletter Label and respective checkbox not aligned proper in customer edit section in admin panel

### Preconditions (*)
1. Magento 2.3.x
2. php7.2

### Steps to reproduce (*)
1. Login to admin panel 
2. Redirect Customers > All customers and view any customer details 
3. Now click in newsletter tab appear in left side 
4. And refer screenshot in sctual result 

### Expected result (*)
![image_2019_10_20T10_06_52_921Z](https://user-images.githubusercontent.com/26018716/67269596-a16c8a80-f4d4-11e9-92cb-031ed10f2365.png)

### Actual result (*)
![image_2019_10_20T10_07_24_201Z](https://user-images.githubusercontent.com/26018716/67269621-aa5d5c00-f4d4-11e9-9675-c0e504afb0bc.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25207-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25207-2-3-develop.instances.magento-community.engineering/admin](https://i-25207-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21970` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#25208 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [e28fa66447c96198dec9cc3603f30b940f1f067e](https://github.com/magento/magento2/commit/e28fa66447c96198dec9cc3603f30b940f1f067e)
 - [824ed399323d49815592e2975a0cadf821d77ade](https://github.com/magento/magento2/commit/824ed399323d49815592e2975a0cadf821d77ade)

The fix will be available with the upcoming 2.3.4 release.
