### ISSUE TITLE
Customer Address Country Options

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#25218]
### Triage Note
- The issue is reproducible on `2.3.3` release version
- The issue is NOT reproducible on `2.3-develop`
- `2.3.3` is not merged into `2.3-develop` at this moment

Preconditions (*)

1. 2.3.3

### Steps to reproduce (*)

1. Install new Magento 2.3.3
2. Set "Default Country" to Austria
3. Set "Allow Countries" to Austria and Germany
4. Add new customer in admin view and save
5. Click "Add new Address" in customer view

### Expected result (*)

1. Country select should contain Austria and Germany

### Actual result (*)

1. Country select contains Afghanistan and Åland Islands
2.![country](https://user-images.githubusercontent.com/2369089/67295254-2cef1700-f4e7-11e9-8204-4230513b2266.jpg)

**Comment by bernd-reindl** [comment]
https://fresh23.2mountain-group.com/phpinfo.php

**Comment by rparsi-boxycharm** [comment]
I'm getting same issue with magento 2.3.3; in my case default country is US, allowed countries are US, CA but in admin customer address add/edit form the countries list has Albania, Afghanistan

**Comment by LucasCalazans** [comment]
@krishprakash Are you working on this issue?

**Comment by krishprakash** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25218-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25218-2-3-3.instances.magento-community.engineering/admin](https://i-25218-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25218-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25218-2-3-develop.instances.magento-community.engineering/admin](https://i-25218-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22023` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jorgb90** [comment]
Same issue here on our 2.3.3 installation.

![Schermafbeelding 2019-10-23 om 12 56 35](https://user-images.githubusercontent.com/7294081/67386070-95480200-f594-11e9-9f46-4772e4cb658a.png)

**Comment by BrentRobert** [comment]
This is the commit that fixed the issue for me.
https://github.com/magento/magento2/commit/7211d50998f786dce0628346439649ac8d196c46

Seems to be in 2.3-develop but not in the 2.3.3 release

**Comment by jorgb90** [comment]
@BrentRobert Thanks! Works perfectly :)

**Comment by cscd98** [comment]
Magento - how can such a major bug be introduced when you have several weeks of QA?!?!?!

**Comment by jamie-selesti** [comment]
I have the same issue too - Whats the best way to fix it without editing core files directly if Magento is not going to release a fix

**Comment by rparsi-boxycharm** [comment]
@jamie-selesti Create a composer patch and update your `composer.json` to use it. Next time you run `composer install` it will be applied.

**Comment by chichitsai0517** [comment]
rparsi-boxycharm, can you tell me how to do so? I'm not sure what you mean by composer patch. Where do we download this?

**Comment by rparsi-boxycharm** [comment]
@chichitsai0517 You would use an IDE to generate the patch file (ie phpstorm).  Alternatively, you can just override the target file in your custom admin theme.
`Magento_Customer/view/adminhtml/ui_component/customer_address_form.xml`

Copy above file to your custom admin theme and modify the country `<select>` tag, to look like this
```
<select>
        <settings>
                <options class="Magento\Directory\Model\ResourceModel\Country\Collection"/>
        </settings>
</select>
```

**Comment by jamie-selesti** [comment]
> rparsi-boxycharm, can you tell me how to do so? I'm not sure what you mean by composer patch. Where do we download this?

https://devdocs.magento.com/guides/v2.3/comp-mgr/patching.html

**Comment by erikhansen** [comment]
Another article on how to create/apply patches: https://www.classyllama.com/blog/create-apply-patches-magento-2

Protip: you can append `.patch` to a Github commit or PR to get a diff that can be used as a patch. e.g.,  https://github.com/magento/magento2/commit/7211d50998f786dce0628346439649ac8d196c46.patch (you would need to remove the `app/code/Magento/Customer/` strings in that patch to get it to apply using composer-patches)

**Comment by kinjal153mehta** [comment]
Hello All, i have resolve this issue with the following step for the if from store configuration we set multiple country as allowed country.

this is the steps : 

1) ovverride the vendor/magento/module-customer/view/adminhtml/ui_component/customer_address_form.xml  this file with the new source class with : Magento\Directory\Model\ResourceModel\Country\Collection => Magento\Directory\Model\Config\Source\Country

2) override the vendor/magento/module-directory/Helper/Data.php file with newly added const variable : const XML_PATH_DEFAULT_ALLOW = 'general/country/allow';

3) used that  XML_PATH_DEFAULT_ALLOW variable in the following ovverride file : 
Magento\Directory\Model\ResourceModel\Country\Collection.php
create new function : 

/**
     * Adds allowed country to options
     *
     * @param array $options
     * @return void
     */
    public function addAllowedCountryToOptions(array &$options)
    {
        $defaultCountry = [];
        foreach ($this->storeManager->getWebsites() as $website) {
            $defaultCountryConfig = $this->_scopeConfig->getValue(
                \Magento\Directory\Helper\Data::XML_PATH_DEFAULT_ALLOW,
                ScopeInterface::SCOPE_WEBSITES,
                $website
            );
            $defaultCountry[$defaultCountryConfig][] = $website->getId();
        }
        
        foreach ($options as $key => $option) {
            if (isset($defaultCountry[$option['value']])) {
                $options[$key]['is_default'] = !empty($defaultCountry[$option['value']]);
            }
        }
    }

4) final step ovverride the : Magento\Directory\Model\Config\Source\Country.php file 
add \Magento\Framework\App\Request\Http $request this in the construct 

and add the following code in to the toOptionArray($isMultiselect = false, $foregroundCountries = '') function in that file

$moduleName = $this->_request->getModuleName();
        $controller = $this->_request->getControllerName();
        $action     = $this->_request->getActionName();
        $route      = $this->_request->getRouteName();
        if (!$this->_options) {
            if($moduleName == 'admin' && $controller == 'system_config' && $action == 'edit'){
                $this->_options = $this->_countryCollection->loadData()->setForegroundCountries(
                    $foregroundCountries
                )->toOptionArray(
                    false
                );
            } else {
                $this->_options = $this->_countryCollection->loadByStore()->setForegroundCountries($foregroundCountries)->toOptionArray(false);
            }
        }

this steps solve the issue for the multiple allowed country from system configuration but i am still try to set the code for the if only single country select then it gives blank.

if anybody find that solution then please let me know.

**Comment by kinjal153mehta** [comment]
> ### Triage Note
> * The issue is reproducible on `2.3.3` release version
> * The issue is NOT reproducible on `2.3-develop`
> * `2.3.3` is not merged into `2.3-develop` at this moment
> 
> Preconditions (*)
> 
> 1. 2.3.3
> 
> ### Steps to reproduce (*)
> 1. Install new Magento 2.3.3
> 2. Set "Default Country" to Austria
> 3. Set "Allow Countries" to Austria and Germany
> 4. Add new customer in admin view and save
> 5. Click "Add new Address" in customer view
> 
> ### Expected result (*)
> 1. Country select should contain Austria and Germany
> 
> ### Actual result (*)
> 1. Country select contains Afghanistan and Åland Islands
>    2.![country](https://user-images.githubusercontent.com/2369089/67295254-2cef1700-f4e7-11e9-8204-4230513b2266.jpg)

please read my comment is solve your issue if you select the multi country from system configuration.

**Comment by kinjal153mehta** [comment]
> This is the commit that fixed the issue for me.
> [7211d50](https://github.com/magento/magento2/commit/7211d50998f786dce0628346439649ac8d196c46)
> 
> Seems to be in 2.3-develop but not in the 2.3.3 release

Yes your soultion also work for signle and multion country if selected from store configuration.

**Comment by kinjal153mehta** [comment]
The same issue exist in magento 2.3.2 version also.

**Comment by hostep** [comment]
@sdzhepa: since https://github.com/magento/magento2/commit/7211d50998f786dce0628346439649ac8d196c46 has been included in Magento 2.3.4, this issue can probably be closed? Can you double check?

**Comment by kinjal153mehta** [comment]
@hostep i m not checked in 2.3.4 version for this issue

**Comment by chichitsai0517** [comment]
I upgraded to 2.3.4 and it has been fixed.

**Comment by kinjal153mehta** [comment]
@chichitsai0517  thanks for the checking

**Comment by hostep** [comment]
Ok, then we should close this issue, thanks for testing @chichitsai0517 !

**Comment by quochuy1508** [comment]
I have the same issue on M245p1, Please reopen issue.

**Comment by hostep** [comment]
@quochuy1508: could you open a new issue ticket with exact steps of how to reproduce please? This ticket here is a pretty old one, it might be slightly different than what you are experiencing. Thanks!
