### ISSUE TITLE
Sales > Tax admin configuration page does not load (Vertex Tax module related)

### ISSUE THREAD

**Issue by chris-pook** [magento/magento2#25213]
### Preconditions
1. Magento 2.3.3

### Steps to reproduce
1. Install Magento 2.3.3 (currently Vertex_Tax version "3.2.0")
2. Login to admin
3. Navigate to Stores > Configuration > Sales > Tax

### Expected result
1. Tax configuration screen should be displayed

### Actual result
1. The following error occurs and the configuration screen is not displayed:

`
Fatal error: Uncaught Error: Cannot instantiate interface Vertex\Tax\Api\QuoteInterface in /var/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116 Stack trace: #0 /var/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Vertex\\Tax\\Api\\...', Array) #1 /var/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Vertex\\Tax\\Api\\...') #2 /var/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Vertex\\Tax\\Api\\...') #3 /var/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Vertex\\Tax\\Mode...') #4 /var/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get(' in /var/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116`

**Comment by chris-pook** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @chris-pook. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @chris-pook, here is your [Magento instance](https://i-25213-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25213-2-3-develop.instances.magento-community.engineering/admin](https://i-25213-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by chris-pook** [comment]
Can't replicate the issue on the provided 2.3-develop instance so I'll close this for now. I assume the Vertex module has been updated.
