### ISSUE TITLE
After installing Magento the Admin Panel I just see the menu options but not working

### ISSUE THREAD

**Issue by gbaeza1** [magento/magento2#2522]
I just installed Magento in my server, but when I go to the Admin Panel don't see the Magento Panel, I just see this menu....

Can anyone help me?
![captura de pantalla 2015-11-25 a las 11 45 08 am](https://cloud.githubusercontent.com/assets/16020310/11403329/3c09862c-936a-11e5-9e83-1e6c68683d91.png)

**Comment by buskamuza** [comment]
Hi @gbaeza1 ,
does page refresh help?
If not (most likely), what web-server do you use?

**Comment by gbaeza1** [comment]
Hi Buskamuza,

Thank you for you reply.

I'm using a:
Versión Apache     2.4.16
Versión PHP    5.5.29
Versión MySQL  10.0.21-MariaDB
Arquitectura    x86_64
Sistema operativo   linux

You can also view the same in the URL http://tiendaonline.latamcapacitacion.com/

**Comment by buskamuza** [comment]
Please, look at http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_no-styles.html
Let me know, if it helps.

**Comment by MomotenkoNatalia** [comment]
@gbaeza1 Do you have any updates?

**Comment by MomotenkoNatalia** [comment]
I close the issue for now. If you have further question to this issue please feel free to reopen
