### ISSUE TITLE
Fullscreen gallery not swiping on touch devices

### ISSUE THREAD

**Issue by krzksz** [magento/magento2#25231]
### Preconditions (*)

1. Magento 2.3.x with sample data but older version may also be affected.

### Steps to reproduce (*)

1. Use touch device or enable touch events emulation in Chrome by choosing any mobile device.
2. Open fullscreen product gallery.
3. Try to change to another photo by swiping over image (`img`) element - almost always nothing happens.
4. Try to change to another photo by swiping on the sides of image (`img`) element - works normally.

![2019-10-23 09 54 09](https://user-images.githubusercontent.com/829189/67370764-915bb600-f57b-11e9-947f-2ce91663429a.gif)

### Expected result (*)

1. Images change normally no matter where does the touch start.

### Actual result (*)

1. Images are not changing reliably when swiping over `img` element.

**Comment by krzksz** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [Magento instance](https://i-25231-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25231-2-3-develop.instances.magento-community.engineering/admin](https://i-25231-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22033` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
