### ISSUE TITLE
Other PayPal Payment Solutions Title Not design like other and alignment not proper

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#25240]
Other PayPal Payment Solutions Title Not design like other and alignment not proper

### Preconditions (*)
1. Magento 2.3.x
2. php 7.2

### Steps to reproduce (*)
1. Login admin panel 
2. Redirect to Store > Configuration 
3. Collapse the Sales tab and click in Payment Methods links 
4. Then refer the screenshot

### Expected result (*)
![solution](https://user-images.githubusercontent.com/26018716/67385243-617ad580-f5b0-11e9-9107-9d7c0412c92f.png)

### Actual result (*)
![issue](https://user-images.githubusercontent.com/26018716/67385251-68a1e380-f5b0-11e9-8f91-2c8edddf616c.png)

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25240-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25240-2-3-develop.instances.magento-community.engineering/admin](https://i-25240-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22028` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
Hi @cedarvinda, please create the pull requests with minor fixes and obvious improvements without opening the issues.
Thank you!

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#25241 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [07040480b673c09284e47072288d7176aa9e06dc](https://github.com/magento/magento2/commit/07040480b673c09284e47072288d7176aa9e06dc)

The fix will be available with the upcoming 2.3.4 release.
