### ISSUE TITLE
permissions and owner reset everytime

### ISSUE THREAD

**Issue by magenx** [magento/magento2#2524]
does magento resets permissions every time you request new page after you delete all cache, and even in "default" mode??
 if we have correct permissions and user:group settings, anyway some folders are created as root with 600, and results 404/403 on frontend.

created few files in root folder with chmod +x file, and bum, it reset to 600.

just trying to understand how it works.

**Comment by daim2k5** [comment]
Hello see my comment #2525

**Comment by magenx** [comment]
i guess we need to closer look , because as i said when you flush cache storage and all caches, it creates files with different permissions. also sometimes product thumbnails not generated into cache folder..

maybe we need to reset staging server and install fresh
