### ISSUE TITLE
Validation issue for configuable product  in cart

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25254]
There is no proper validation for configurable product in cart. If we add configurable product in cart and then remove associated product from configurable product in admin then there is no error on cart page and guest/customer is able to place order.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create a configurable product. Here i am creating configurable product using color attribute with Maroon, Black and Green variation.
2. Add configurable product in cart with variation color Maroon.
3. Go to admin and remove Maroon color variation from configurable product.
4. Now go to cart page

![1](https://user-images.githubusercontent.com/15954089/67439323-92d8bd00-f613-11e9-8754-15d33bc7beee.png)

![2](https://user-images.githubusercontent.com/15954089/67438550-789ddf80-f611-11e9-8ca9-79f88be60193.png)
![3](https://user-images.githubusercontent.com/15954089/67438557-7d629380-f611-11e9-989c-9c59ebf4ff5f.png)
![4](https://user-images.githubusercontent.com/15954089/67438561-818eb100-f611-11e9-96f9-12544f8b7f7d.png)

### Expected result (*)

1. There should be error on cart page like variation does not exist

### Actual result (*)

1. There is no error on cart page and customer/guest is able to place order with added variation. But that variation does not exist.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25254-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25254-2-3-develop.instances.magento-community.engineering/admin](https://i-25254-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce the issue on vanilla Magento instance

**Comment by ghost** [comment]
@krishprakash - Please verify the issue. let me know if anything is not clear.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22121` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by madhurajawat** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @madhurajawat. Thank you for your request. I'm working on Magento 2.3-develop instance for you
