### ISSUE TITLE
Unable to edit product because of an error in catalog adminhtml gallery.phtml

### ISSUE THREAD

**Issue by robhuijben** [magento/magento2#25266]
I was trying to edit a product in an existing environment recently updated to Magento 2.2.10 when I stumbled upon an error when opening the product in the backend. It seems that the constant *formName* in magento/module-catalog/view/adminhtml/templates/catalog/product/helper/gallery.phtml should be *$formName*.

### Preconditions (*)
1. Magento version 2.2.10, clean install

### Steps to reproduce (*)
1. Install Magento 2.2.10;
2. Login to the backend and try to create a product;
3. The following error shall be thrown:

`Notice: Use of undefined constant formName - assumed 'formName' in /vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/helper/gallery.phtml on line 62`

4. Product can not be added because form fields do not render.

### Expected result (*)
1. Product should be editable and form fields should be rendered;

### Actual result (*)
1. Error:
`Notice: Use of undefined constant formName - assumed 'formName' in /vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/helper/gallery.phtml on line 62`

![m2-2-10-product-admin-bug](https://user-images.githubusercontent.com/7040758/67482315-dbb86200-f663-11e9-97ca-832596ac2169.png)

**Comment by robhuijben** [comment]
@magento give me 2.2.10 instance

**Comment by magento-engcom-team** [comment]
Hi @robhuijben. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by engcom-Delta** [comment]
HI @robhuijben thank you for your report. I cannot reproduce issue by steps you described on 2.3-develop.
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/helper/gallery.phtml#L64
It should not be replicated in the future released versions
If you'd like to update the issue, please reopen it.

**Comment by jissereitsma** [comment]
In reference: https://github.com/magento/magento2/commit/a2aaa56fad9369d3ce37247d25efce296a6759cc
