### ISSUE TITLE
blank page after new install

### ISSUE THREAD

**Issue by garry191091** [magento/magento2#25260]
I am using this given magento version and i have installed it on window os. After installation, now i am getting a blank page on click on admin URL.

And on front-end I am facing this issue.
#There has been an error processing your request
Exception printing is disabled by default for security reasons.

**Comment by engcom-Delta** [comment]
Hi @garry191091 thank you for your report. I am not able to reproduce issue by steps you described on clean 2.3-develop.
Please see magento OS [requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html)
You could check log with error in `magento_dir/var/log/` or `magento_dir/var/report/`
