### ISSUE TITLE
G. Chrome - Add to cart not working

### ISSUE THREAD

**Issue by albsa** [magento/magento2#2527]
Did a fresh magento 2.0 composer installation on local desktop.

Add to cart isn't working in Google Chrome Version 46.0.2490.86 (64-bit)

It stays stuck on faded button with text "Adding..."

It's working properly in Safari and Firefox.

**Comment by dmitrii-fediuk** [comment]
Magento does not work properly on a top-level domain like `localhost`.

**Comment by davidalger** [comment]
Please use a domain other than localhost, as it will not work properly in such case. Closing as duplicate of #2439

**Comment by agjalpm** [comment]
@mage2pro Why Magento does not work properly on top-level domain like `localhost`?

**Comment by mrkhoa99** [comment]
@agjalpm this issue occurs on Chrome. You can read more here: http://superuser.com/questions/274562/teach-google-chrome-to-understand-custom-tld
https://bugs.chromium.org/p/chromium/issues/detail?id=30636
