### ISSUE TITLE
Multiple Address Checkout - Products Parent Item not updated properly

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#25271]
### Preconditions (*)
1. Clean Magento 2.3.3, or previous version as well
2. Enable Allow Shipping to Multiple Addresses option to Yes

### Steps to reproduce (*)
1. Place configurable or bundle product to the basket
2. On Checkout Select Multiple Address Checkout
3. Place the order, go through all the steps

### Expected result (*)
1. The configurable product under my account should appear as configurable only once with the configurable options

### Actual result (*)

1.Currently 2 products are listed, one with the configurable options, and one with 0 price. Please see screenshoot.
![Selection_004](https://user-images.githubusercontent.com/4192062/67491909-49718780-f67e-11e9-8954-c2484e461f59.png)

2. It seems the parent items are not set properly when multiple address checkout is used.

Regards,
Szabi

**Comment by anujwebkul** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul, here is your [Magento instance](https://i-25271-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25271-2-3-develop.instances.magento-community.engineering/admin](https://i-25271-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by anujwebkul** [comment]
@ksz2013 issue not found in the 2.3-develop instance.

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-25271-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25271-2-3-develop.instances.magento-community.engineering/admin](https://i-25271-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
Confirm @anujwebkul, described issue not reproduced on 2.3-develop
![1m11b_2019-10-29_11-32-37](https://user-images.githubusercontent.com/1129623/67750350-19d8cb80-fa40-11e9-885d-015381ae75ef.jpg)
