### ISSUE TITLE
Magento_Contact module MUST NOT include any design-level LESS styling 

### ISSUE THREAD

**Issue by danemacmillan** [magento/magento2#25276]
### Preconditions (*)
Magento 2.3.x & 2.3-develop
The `Magento_Contact` module, under the `code` directory, includes its own `_module.less` file at: https://github.com/magento/magento2/tree/2.3-develop/app/code/Magento/Contact/view/frontend/web/css/source

### Steps to reproduce (*)
No other module under the `code` directory includes LESS of any kind. The Contact module is in violation of the division of concerns that **every other module** observes:
1. In `<magento root>/app` run `find . -type f -name "_module.less"`
### Expected result (*)
<code>
...

./design/adminhtml/Magento/backend/Magento_GiftRegistry/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Tax/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_ReleaseNotification/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Backend/web/css/source/_module.less
<b>./design/frontend/Magento/blank/Magento_Contact/web/css/source/_module.less</b>
<b>./design/frontend/Magento/blank/Magento_Cms/web/css/source/_module.less</b>
</code>

### Actual result (*)
<pre><code>
 ~/magento/app $ find . -type f -name "_module.less"
./design/frontend/Magento/luma/Magento_CustomerBalance/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_AdvancedCheckout/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_LayeredNavigation/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Reward/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Review/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Vault/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Wishlist/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Invitation/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Customer/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_CatalogSearch/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftCard/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftCardAccount/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Newsletter/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Rma/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Sales/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftMessage/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_MultipleWishlist/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Downloadable/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftWrapping/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_AdvancedSearch/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Msrp/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Multishipping/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GroupedProduct/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_InstantPurchase/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Checkout/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftRegistry/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Bundle/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_SendFriend/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_AdvancedCheckout/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_LayeredNavigation/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Theme/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Reward/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Braintree/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Paypal/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Review/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_CatalogEvent/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Vault/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Wishlist/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Invitation/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Customer/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_CatalogSearch/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftCard/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftCardAccount/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Newsletter/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Rma/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Sales/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftMessage/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_MultipleWishlist/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Downloadable/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftWrapping/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Msrp/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Multishipping/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GroupedProduct/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_SalesRule/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_ProductVideo/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Checkout/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Catalog/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftRegistry/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Weee/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Bundle/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_SendFriend/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Translation/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_VersionsCms/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_ConfigurableProduct/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_CustomerBalance/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_AdvancedCheckout/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Reward/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Braintree/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Ui/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Review/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Signifyd/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_CatalogPermissions/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Vault/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Customer/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Marketplace/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_GiftCard/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Banner/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Integration/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Rma/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_CurrencySymbol/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_AdminNotification/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Sales/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Downloadable/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_VisualMerchandiser/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_GiftWrapping/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Config/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Staging/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Analytics/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_ProductVideo/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Catalog/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Shipping/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_GiftRegistry/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Tax/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_ReleaseNotification/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Backend/web/css/source/_module.less
<b>./code/Magento/Contact/view/frontend/web/css/source/_module.less</b>
<b>./code/Magento/Cms/view/adminhtml/web/css/source/_module.less</b>
</pre></code>

LESS styling for `Magento_Contact` must be moved into the correct directory located under, `design`, either for the `blank` or `luma` theme.

In addition to the violation mentioned above, this also attempts to make use of LESS variables that have no guarantee of existing; this module assumes that either `blank` or `luma` are the implied parent themes that provide these variables. Given that no other module in the framework makes this assumption, and given that anyone with a custom parent theme will not have these variables, it's clear this needs to move under a directory located under `design`, where LESS and theme-related work belong.

Developers responsible for this inclusion and its continued inclusion:

@suryakant-krish 
@amol2jcommerce 
@p-bystritsky

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22205` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ptylek** [comment]
@magento I am working on it

**Comment by VladimirZaets** [comment]
Hi @danemacmillan. Thank you for your report. 
The issue has been fixed in magento/magento2#25355 by @ptylek in 2.3-develop branch
Related commit(s):
 - [42d2163e2d0afa261411ae174b6fca23fe189045](https://github.com/magento/magento2/commit/42d2163e2d0afa261411ae174b6fca23fe189045)
 - [2c6ad75fc12645c8d6a13ebd3c66bb4fbae18da5](https://github.com/magento/magento2/commit/2c6ad75fc12645c8d6a13ebd3c66bb4fbae18da5)

The fix will be available with the upcoming 2.3.5 release.

**Comment by danemacmillan** [comment]
@VladimirZaets Thanks!
