### ISSUE TITLE
require.js: Fallback to JQueryUI Compat activated 

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#25275]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Visit a category page through browser

### Expected result (*)

1. No console warnings

### Actual result (*)

1. Console warining: Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site.

**Comment by nadroj467** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nadroj467, here is your [Magento instance](https://i-25275-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25275-2-3-3.instances.magento-community.engineering/admin](https://i-25275-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bst2002git** [comment]
@nadroj467 Hello did you resolve the Problem, what was it?

**Comment by magulin** [comment]
@nadroj467 Did you find a fix?

**Comment by bst2002git** [comment]
@magulin Hello i found and resolved using this tips:
https://twitter.com/vova_yatsyuk/status/1182192753335324673?s=09
https://magento.stackexchange.com/questions/293714/magento-2-console-notice-fallback-to-jqueryui-compat-activated

**Comment by magulin** [comment]
Thanks! 👍
