### ISSUE TITLE
LinkManagement::getChildren() returns only children products which are in stock

### ISSUE THREAD

**Issue by princefishthrower** [magento/magento2#25287]
### Preconditions (*)
1. Version 2.3.x & 2.3-develop
2. Class `Magento\ConfigurableProduct\Mode\LinkManagement`

### Steps to reproduce (*)
1. Inject LinkManagement into any custom code.
2. Call getChildren() with an SKU of a given configurable product (for example let's say it has 5 child simple products, where 3 are in stock and 2 are out of stock.)

```
// ex. product with sku '1234' is a known configurable product with 5 simple product children
$childProducts = $this->linkManagement->getChildren("1234");
echo sizeof($childProducts);
// 3.... (further inspection shows it is the 3 products in stock)
```

### Expected result (*)
The children array should include ALL 5 children of the configurable product, as the method description states in LinkManagementInterface: `Get all children for Configurable product`

### Actual result (*)
The children array only includes the children which are in stock

I looked deeper into the stack, and found in

Magento\ConfigurableProduct\Model\Product\Type\Configurable::getUsedProducts()

which calls

Magento\ConfigurableProduct\Model\Product\Type\Configurable::loadUsedProducts()

which has the $isSaleable parameter. It appears to correctly be called with $isSaleable set to false (i.e., we want all children, not just the ones that are non-salable, which an out of stock product would be) 

In this case it uses the $cacheKey, which then returns the false list.

I did a second sanity check with a freshly cleaned and flushed cache, but the result remained the same.

So my guess is the error lies somewhere in the logic of how $cacheKey is generated - somewhere there is a setting restricting the products.

The only way I've found to get a the resulting true complete set of child products for a configurable product is with another method `getConfiguredUsedProductCollection()` in the same class and the 'skipStockFilter' parameter set to true:

$this->getConfiguredUsedProductCollection($product, true)

Actually this should anyway be the case in loadUsedProducts, when upon an invalidated cache call,

`$usedProducts = $this->readUsedProductsCacheData($cacheKey);`

will return null, and so getConfiguredUsedProductCollection should be called with the true option. Even when saleableOnly is set to true this would be okay, because there is the further step of processing the return collection (which I am assuming correctly cuts out non-saleable products)

```
if ($salableOnly) {
     $collection = $this->salableProcessor->process($collection);
}
```

I'd be happy to do a pull request on this if my logic is sound agreed upon.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22167` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by princefishthrower** [comment]
@engcom-Charlie - thanks for doing the confirmation on this - as I mentioned, I think this is simple a matter of setting that 'skipStockFilter' parameter to 'true'. 

I have since discovered that this setting also fixes the cache issue (i.e., subsequent calls to the same product are correctly stored in the cache) I will make a pull request ASAP
