### ISSUE TITLE
G. Chrome - Admin login: Too many redirects

### ISSUE THREAD

**Issue by albsa** [magento/magento2#2528]
When trying to acces back-end with chrome version 46.0.2490.86 (64-bit), Chrome reports that their are too many redirects.

Firefox and Safari are able to access the backend URL properly.

**Comment by dmitrii-fediuk** [comment]
Magento does not work properly on a top-level domain like `localhost`.

**Comment by sijad** [comment]
+1 same problem here

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2439

**Comment by davidalger** [comment]
Please use a domain other than localhost, as it will not work properly in such case. Closing as duplicate.
