### ISSUE TITLE
Some error display while add/update product after enable elastic search 6.0+ 

### ISSUE THREAD

**Issue by renard123** [magento/magento2#25284]
Some error display while add/update product after enable elastic search 6.0+ 

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
1. Admin -> Catalog product
2. Add New Product
3. After added product successfully
4. Enable elastic search from configuration
5. Now edit and update the added product OR Add new product and save

### Expected result (*)
Product should added/Updated successfully

### Actual result (*)
Display some error like "The stock item was unable to be saved. Please try again."
![image](https://user-images.githubusercontent.com/50658701/67544928-f3035800-f714-11e9-8fab-c75353a2760a.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22122` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @renard123 and @krishprakash 

FYI: @xmav 

Internal Magento team took this issue in progress `MC-22122` but we cannot reproduce this issue.
Only one case when we received such error was when Elasticsearch is enabled in Magento System Configuration but NOT INSTALLED on the server.

Could you please double-check it?
Share please your configuration for Elasticserach and what result if click **Test Connection** button in **Stores > Settings > Configuration > Catalog > Catalog > Catalog Search**

Note: 
1. Our  instance(`magento give me 2.3-develop instance`) deployer does NOT have installed Elasticsearch
2.  [Install and configure Elasticsearch](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html)

**Comment by renard123** [comment]
@sdzhepa Thanks.
I have installed elastic search again now it works fine.
Close this issue
