### ISSUE TITLE
Magento 2.3.3 category image remove if change another category image

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#25282]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Go to Admin > Catalog > Category > edit any category
2. Select any image (if multiple image option available in category) and save it

### Expected result (*)

1. In case of multiple image options in category page If the previously selected image already there and when uploading a new image then the previous image stay as it is

### Actual result (*)

1. If upload a new second image (in case of multiple image options) new image saved successfully but the previously selected image removed and in pub/media/catalog/category directory previously image name was changed.

**Comment by krishprakash** [comment]
Hi @aasim110. Thank you for your report.
Seems similar issue is already open
Please check #25099
