### ISSUE TITLE
Magento 2 makes its stack trace in the error reports uncomfortable to read by chopping the strings

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2530]
It is a long-term issue from Magento 1.x, and still is in Magento 2.
Looks an example here: https://github.com/magento/magento2/issues/2505#issuecomment-159754199
As you can see, the left half of screen contains the same file path in each line, and the right half chops significant parts of the messages.
I propose:
1. Show the **full** strings in a error report's stack trace
2. Additional improvement: skip the filesystem path to the Magento root in the stack traces because it is the same for each trace line. It would better to show it once above the stack trace.

**Comment by buskamuza** [comment]
I propose to not do # 2 because currently we're moving in the direction of having components anywhere. It still requires some fixes to make everything working from outside of Magento root, but we're moving in this direction.
So, I think, it would be better to avoid any additional processing and just show real paths.

**Comment by MauroNigrele** [comment]
Absolutely Agree

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-2-makes-its-stack-trace-in-the-error-reports/idi-p/45773).

**Comment by lshchur** [comment]
Guys, you can also use this trick to read error reports in a comforable way:

`
cat var/report/1157576833741 | php -r "print_r(json_decode(file_get_contents('php://stdin')));"
`
