### ISSUE TITLE
Mobile view issue on category page - Sort By label overlaps with Shop By button

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25300]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create one category
2. Assign 2, 3 products in category.
3 . Now in mobile view open category page on frontend

Note - 
1. View category page on less than 330px screen size.
2. If shop by option is not appearing on category page then try to add more product and attribute in products to activate the layered navigation.

### Expected result (*)

1. Design should look good on frontend.

### Actual result (*)

1. Sort By label overlaps with Shop By button

![sort_by_css_issue](https://user-images.githubusercontent.com/15954089/67626210-cc086b80-f865-11e9-914c-14ec303a166d.png)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25300-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25300-2-3-develop.instances.magento-community.engineering/admin](https://i-25300-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce the issue on vanilla Magento instance.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25300-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25300-2-3-develop.instances.magento-community.engineering/admin](https://i-25300-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22157` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by akartavtsev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @akartavtsev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @akartavtsev, here is your [Magento instance](https://i-25300-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25300-2-4-develop.instances.magento-community.engineering/admin](https://i-25300-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment]
Hi @rahulwebkul. Thank you for your report. 
The issue has been fixed in magento/magento2#26381 by @akartavtsev in 2.4-develop branch
Related commit(s):
 - [bf580e444c1da52f09bdde5932e914800a7a4721](https://github.com/magento/magento2/commit/bf580e444c1da52f09bdde5932e914800a7a4721)
 - [68ea88dded09735b0417390ed231a9125d093cd3](https://github.com/magento/magento2/commit/68ea88dded09735b0417390ed231a9125d093cd3)
 - [8ebcc46ceaa02fc225ed863d1ad5ba36f37f9e55](https://github.com/magento/magento2/commit/8ebcc46ceaa02fc225ed863d1ad5ba36f37f9e55)

The fix will be available with the upcoming 2.4.0 release.
