### ISSUE TITLE
I cant upload images on backend magento 2

### ISSUE THREAD

**Issue by jrodriguez1018** [magento/magento2#25303]
Well, my selected problem is reduced in the icon to upload images allows me to select the element I want to upload, however it does not upload.
Anyone know how to solve it?
Please be very grateful with your help.

**Comment by engcom-Delta** [comment]
Hi @jrodriguez1018 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
