### ISSUE TITLE
Add Colombian regions

### ISSUE THREAD

**Issue by magudelo62** [magento/magento2#25312]
### Summary of the issue
Magento does have some country regions by default and they are showing in dropdown when you select a country.
However, if your country does not have regions defined, then you will see just a text field.

In particularly, Colombian regions are missed.

### Description (*)
Add Colombia Regions

### Preconditions
Magento 2.2.X
Magento 2.3.X

### Steps to reproduce
Add product to cart
Go to checkout
Select Colombia as shipping / billing country

### Expected result
See dropdown with Colombia regions

### Actual result
See a text field to enter free text region

**Comment by magudelo62** [comment]
@magento I am working on it

**Comment by magento-engcom-team** [comment]
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22189` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @magudelo62. Thank you for your report. 
The issue has been fixed in magento/magento2#25313 by @magudelo62 in 2.3-develop branch
Related commit(s):
 - [a9f499ed76599deef689eaeb3d0cb9fb02498c49](https://github.com/magento/magento2/commit/a9f499ed76599deef689eaeb3d0cb9fb02498c49)

The fix will be available with the upcoming 2.3.5 release.
