### ISSUE TITLE
How to install custom module in  Magento ver. 2.0.0  release

### ISSUE THREAD

**Issue by vipin33** [magento/magento2#2532]
I am so confused to install custom module in  Magento ver. 2.0.0 release because structure has been changed ,as i assume core files moved  to vendor directory
Any help will be appreciated...........thanks in advance

**Comment by Vinai** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
