### ISSUE TITLE
Customer save issue. 

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#25332]
### Preconditions (*)

1. Magento 2.3.2 & 2.3.3 Community Edition
2. No 3rd party extensions which modify anything related to customer model
3. Create a script that will install new customer attribute "some_attribute", varchar
4. Create 2 customer accounts
5. Create an order as registered customer
6. Purpose of my code was to assign customer attribute value based on another customer settings. 

### Steps to reproduce (*)

So this issue is a little bit weird. Here is how to reproduce it. I think the best way is on `sales_order_save_after` observer when you create an invoice or do something to the order
1. In the observer, load customer by model (not by CustomerRepository, that is used to save data)
```
$customerId = $order->getEvent()->getOrder()->getCustomerId();
if ($customerId) {
    /** @var CustomerModel $customer */
    $customer = $this->customer->load(1);

    /** assign position in binary matrix */
    if ($customer->getSomeAttributeValueId()) {
        [...]
            // injhect any customer code that will also load customer to different valiable
            $secondCustomer = $this->customer->load(2);
            $customOptionValue = $secondCustomer->getId();
        [...]
                $customerDataModel = $customer->getDataModel();
                /** @var Customer $customer, opperate on Data Model to save attributes faster)
                $customerDataModel->setCustomAttribute('custom_attribute', $customOptionValue);
                $this->customerRepositoryInterface->save($customerDataModel);
        try {
            $customer->save();
        } catch (\Exception $e) {
            //TODO log exception
        }
    }
}
```
2. 

### Expected result (*)

1. $customer (ID = 1) is saved and assigned custom attribute value

### Actual result (*)

1. Value of custom attribute is assigned to the last loaded customer, not to the one passed in customerRepositoryInterface. 

I've tested this scenario multiple times and it seems like customerRepository always work on last loaded customer, not the one assigned to variable passed to save method in customer Repository.

**Important**: this also happens when I use $customer->save() operation, not just on CustomerRepositoryInterface.

**Comment by korostii** [comment]
> In the observer, load customer by model (not by CustomerRepository, that is used to save data)

Except model's `load()` method is, in fact, deprecated:
https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/lib/internal/Magento/Framework/Model/AbstractModel.php#L528-L542

`CustomerRepository::getById()` is the way to go.

**Comment by jakwinkler** [comment]
The same issue is with the customer repository.

**Comment by kanthy-magento** [comment]
@qsolutions-pl 

As per the Factory pattern you can use the "CustomerFactory" class to load the customer instead of "Customer" class, as factory pattern is for creation of new instance every time you use the particular class object.

For example:

Inject the class \Magento\Customer\Model\CustomerFactory and use it like below
$customer = $this->customer->create()->load(2);


Thank You,
Pranith
