### ISSUE TITLE
Wrong Reference to the product model in general catalog class

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#2533]
In the `Magento\Catalog\Model\ResourceModel\Attribute::deleteEntity` method when retrieving the attribute `entity attribute` based on `entity_attribute_id`, it is checked that the attribute belongs to the product entity : https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/ResourceModel/Attribute.php#L127

But `Magento\Catalog\Model\ResourceModel\Attribute` is a general class for all EAV entities in the catalog module (I mean categories also).  
So most probably this will fail when `deleteEntity` receives as parameter an instance of `Magento\Catalog\Model\Category`.  

Instead of `\Magento\Catalog\Model\Product::ENTITY` this value should be retrieved from the `$object` passed as parameter to the method.

**Comment by vkholoshenko** [comment]
@tzyganu, thanks for reporting! We've created an internal ticket to track this. MAGETWO-48165

**Comment by mslabko** [comment]
Hello @tzyganu, issue was fixed for develop branch.
Thank you for reporting!
