### ISSUE TITLE
Price Filter not showing when using elastic search 6+

### ISSUE THREAD

**Issue by vijay-prevaj** [magento/magento2#25341]
### Preconditions (*)

1. Magento 2.3.2
2. Elasticsearch 6+
3. Set "Price Navigation Step Calculation" to "Automatic (equalize product counts)" please see the screenshot below :

![Configuration   Settings   Stores   Magento Admin   World of Watches](https://user-images.githubusercontent.com/34272427/67741440-24469580-fa3f-11e9-8010-e7103e7848c1.jpg)

### Steps to reproduce (*)

1. Enable Elasticsearch 6+
2. See Category page layered navigation

### Expected result (*)

1. Price filter must show

### Actual result (*)

1. Price filter is missing

**Comment by vijay-prevaj** [comment]
> Hi @vijay-prevaj. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @vijay-prevaj do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

Yes, i able to reproduce the issue in vanilla magento instance.

**Comment by magento-engcom-team** [comment]
Hi @vijay-prevaj. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vijay-prevaj, here is your [Magento instance](https://i-25341-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25341-2-3-develop.instances.magento-community.engineering/admin](https://i-25341-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vijay-prevaj** [comment]
> 123123q

I need the Elasticsearch to test.

please see : 

![Configuration   Settings   Stores   Magento Admin](https://user-images.githubusercontent.com/34272427/67741825-48ef3d00-fa40-11e9-9372-a280b1c07562.jpg)

**Comment by taoufiqaitali** [comment]
we have same issue,

**Comment by gondas33** [comment]
probably related with #23793

**Comment by vijay-prevaj** [comment]
This patch resolve the issue but i don't know it a correct way.

```diff
diff --git a/etc/di.xml b/etc/di.xml
index 011dfa1..6fc22f3 100644
--- a/etc/di.xml
+++ b/etc/di.xml
@@ -174,7 +174,7 @@
     <virtualType name="elasticsearchLayerCategoryItemCollectionProvider" type="Magento\Elasticsearch\Model\Layer\Category\ItemCollectionProvider">
         <arguments>
             <argument name="factories" xsi:type="array">
-                <item name="elasticsearch6" xsi:type="object">elasticsearchCategoryCollectionFactory</item>
+                <item name="elasticsearch6" xsi:type="object">Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory</item>
             </argument>
         </arguments>
     </virtualType>



diff --git a/Model/ResourceModel/Fulltext/Collection/DefaultFilterStrategyApplyChecker.php b/Model/ResourceModel/Fulltext/Collection/DefaultFilterStrategyApplyChecker.php
index 1288720..f3fa482 100644
--- a/Model/ResourceModel/Fulltext/Collection/DefaultFilterStrategyApplyChecker.php
+++ b/Model/ResourceModel/Fulltext/Collection/DefaultFilterStrategyApplyChecker.php
@@ -21,6 +21,6 @@ class DefaultFilterStrategyApplyChecker implements DefaultFilterStrategyApplyChe
      */
     public function isApplicable(): bool
     {
-        return false;
+        return true;
     }
 }

**Comment by engcom-Charlie** [comment]
Hello @vijay-prevaj 

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

You can read info about `Price Navigation Step Calculation` in [this topic](https://docs.magento.com/m2/ce/user_guide/catalog/navigation-layered-price.html).
![image](https://user-images.githubusercontent.com/51680850/67849651-a605f400-fb0f-11e9-99e1-c5ad23b3016f.png)
As I offered in [this comment](https://github.com/magento/magento2/issues/25258#issuecomment-547388098) please change value of `Interval Division Limit` for your products count.

I am closing this issue as a duplicate of #25258
