### ISSUE TITLE
admin images and font folder empty

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#2534]
Hi, I just installed magento 2, the installation went smooth with no error but the admin panel shows no icons nor images nor fonts, the frontend shows images but no icons. Moreover, no matter where I click in the admin panel, no items in menu seems to work. If I open the admin panel with firefox, I see the admin interface (even if it is not working), if I open it with chrome, all I get is a blank page. I checked subfolders of pub/static/, where content for admin and frontend should be, but half of the subdirectories are empty! Worse, some of the directory that I see in the setup folder of the archive are not in the magento dir that I have installed. 

It's not a permission issue, since I'm on localhost and I have fully permission over my web folder. 

I've attached a screenshot showing the admin interface with firefox (as I said, with chrome I get only a blank page)

![screenshot](https://cloud.githubusercontent.com/assets/6501073/11425479/9a16c608-9455-11e5-8e96-d2bc3ae96cbc.jpg)

**Comment by LouNik1984** [comment]
Ok I managed somehow to have the admin panel working by deleting static folder and editing di.xml file. But now, the submit button in the reindex page is missing! Surely, I never struggled so much to have a magento ready! 

![screenshot](https://cloud.githubusercontent.com/assets/6501073/11428017/ae286acc-9467-11e5-8edd-36415423da54.jpg)

**Comment by daim2k5** [comment]
You cannot reindex anymore from the admin backend.

**Comment by blankapham** [comment]
@LouNik1984: please change to developer mode to check it. Now it is default mode, the static file will be cached in this mode

**Comment by LouNik1984** [comment]
@daim2k5

It's really un-friendly, useless and annoying not to be able to reindex from admin. But also the button in the cache manager is not there, is also the cache to be cleaned from cron? 

Honestly, I don't know what to think.. I've been expecting magento 2 since its first announcement and after 6 hours of a lost day of work, that's what I got: 

a magento that I will never be able to upgrade because upgrades are possible only through composer which I cannot use because _composer refuses to install and work_ on my environment

a magento that, on linux, I cannot install via composer because it keep on throwing errors (after the third time I gave up trying the installation via composer)

a magento that, via archive installation, it takes more than 40 min to install and, after installation, both admin and frontend page took more than 10 minutes to load

Finally I got into admin panel only to find out that it was broken, I had to google up to find solution because it was written nowhere else 

Finally I manually fixed the admin panel only to discover that I cant do anything because submit buttons are not there..

Now, maybe I'm naive, but I've always thought that things needs to be changed into faster, easier, more functional versions. But for what I've seen so far, Magento 2 is a downgrade from Magento 1: it's not faster, it's not easier, it's not functional for the simple reason that it's not working at all! 

Honestly, I gave up. Or better, I could keep on trying having this thing to work, but then I realize that I couldn't have it to upgrade it anyway because of this weird idea of composer-only upgrades (as I said, composer refuses to work on my environment, no matter if windows or linux are involved), so everything I try to have Magento 2 work is pointless: whatever I do, there's no point of installing something that you cannot upgrade..

**Comment by syntaxwanderer** [comment]
Try to use

php bin/magento setup:static-content:deploy

**Comment by bvboas** [comment]
@LouNik1984  Can you please provide more info on how to fix the non-displaying icons/fonts? I'm facing the same situation.

@ArniXXX didn't work.

**Comment by LouNik1984** [comment]
@bvboas 

Hi, sure, basically: 
- go to pub/static directory and remove everything except the htaccess,
- open app/etc/di.xml file and change the line 'Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink' with 'Magento\Framework\App\View\Asset\MaterializationStrategy\Copy' (you simply write 'Copy' instead of 'Symlink'),
- Then refresh admin and frontend page

that fixed my problem, I hope it works for you as well

**Comment by daim2k5** [comment]
@LouNik1984 i closed the issue because i think you got your solution. If I'm wrong please reopen the issue.

**Comment by ricardo4142** [comment]
Thanks @LouNik1984 it works for me.

**Comment by saqlainraza14** [comment]
Thanks @ArniXXX  below Command work well for me.

## **php bin/magento setup:static-content:deploy**

Thanks Bro

**Comment by udemethegrtman** [comment]
I have the same issue, in magento 2.18 CE and this is the question on stack exchange. https://goo.gl/nZusVW

**Comment by salehawal** [comment]
i did face this issue and it was not solved until i cleared our server Varnish cache
