### ISSUE TITLE
I have enabled extension on My site which is on Magento 2.3  and getting this error

### ISSUE THREAD

**Issue by syedkawish** [magento/magento2#25346]
Can't download file. Please try again! RecursiveDirectoryIterator::__construct(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP?

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by kanthy-magento** [comment]
@syedkawish 

Can you please the below details. 

 Summary of the issue
 Information on your environment
 Steps to reproduce
 Expected and actual results

Thank You,
Pranith

**Comment by samgranger** [comment]
Phar gets unregistered in `app/bootstrap.php` for security reasons. Which extension did you enable? Third party? If so, might be better contacting them for support?

**Comment by kanthy-magento** [comment]
@syedkawish I'm closing this ticket. due to no response. 
Feel free to provide more details(steps) and reopen this ticket..
