### ISSUE TITLE
My Wish List items should not display in left side bar from Customer Dashboard My Wish List page 

### ISSUE THREAD

**Issue by sudheers-kensium** [magento/magento2#25344]
### Preconditions (*)

1. Magento 2.3.3
2.

### Steps to reproduce (*)

1. Login customer in front-end.
2. Add products to wish-list
3. Go to Customer My Account -> My Wish List.

### Expected result (*)

1. My Wish List items should not display in left side bar.
![image](https://user-images.githubusercontent.com/50358141/67759996-7c44c280-fa66-11e9-8e58-11eb90ec6e52.png)

### Actual result (*)

1. My Wish List items displaying in left side bar.
![image](https://user-images.githubusercontent.com/50358141/67760008-836bd080-fa66-11e9-80b9-6810f85f209b.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22201` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chandu-pinpoint** [comment]
@magento I am working on this

**Comment by chandu-pinpoint** [comment]
@magento I am working on this

**Comment by sdzhepa** [comment]
Hello @sudheers-kensium 

Could you please provide more information on why you consider it as bug or incorrect behavior that should be changed?
Probably you have links to official documentation where described expected result? Or you have examples when the current result block other functional user flows?

**Comment by lenaorobei** [comment]
Hi @sudheers-kensium! Unfortunately I need to close this issue since this is an expected behaviour for Magento. 

If you consider this block as a redundant, it can be removed through you customization.

Thank you.

**Comment by sdzhepa** [comment]
Hello @sudheers-kensium

After a couple of discussions was found the additional potential value of issue.
It can remove not only block/view but also improve performance. As I understood not two requests happen to get  Wishlist items. One for the widget and one for page content

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, @sudheers-kensium. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-25056` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, @sudheers-kensium. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-22201` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
