### ISSUE TITLE
Problems with cache when Merchant configure state for United States as not required

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25348]
### Preconditions (*)

Magento 2.3-develop
1. Create Customer
2. In Address Book add an address (I suggest to choose Uruguay or United Kingdom because they are close to the United States option)
3. Save address.
4. Log out

### Steps to reproduce (*)

1. Navigate to Store -> Settings -> Configuration -> General -> General -> State Options: **State is Required for**
2. Find **United States** on the list. Press `<Ctrl>` or `<Cmd>` and remove United States from the selection and save the configuration
3. Flush cache
4. Log in as a Customer from preconditions
5. Click Address Book
6. Click Change Billing Address
7. Click Country and change to the United States
8. :x: Select Alabama from the list of states. If it doesn't work, press F5 and select Alabama from the list of states
9. Save Address
10. Click Change Billing Address
11. Click Country and change to Uruguay
12. Fill "Abc" in the state
13. Save address
14. Click Change Billing Address
15. Click Country and change to the United States

### Expected result (*)

1. :heavy_check_mark: I can set Alabama without refreshing the page

### Actual result (*)

1. :x: The state is optional but I still should be able to choose it from the list or type by hands
![image](https://user-images.githubusercontent.com/11827230/67769897-f4f35100-fa5d-11e9-9842-ea19e6f8ff82.png)

### Additional information
- Still actual for `2.4-develop` https://github.com/magento/magento2/issues/25348#issuecomment-645520274

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22562` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AleksLi** [comment]
@magento I am working on it

**Comment by sdzhepa** [comment]
This issue still actual for `2.4-develop`

The short variant of the problem can be described:

**Precondition**
- any customer with non-US address is created

**Steps**
1. in Admin Panel remove  United States from **State is Required for**  _Store -> Settings -> Configuration -> General -> General -> State Options_
2. Go to Storefront and login as test customer
3. Open for edit billing/shipping address in My Account
4. Change Country  to the United States

**Expected Result**
- User is able to edit(select) State from the predefined list for US

**Actual Result**
- State/Province is not editable
- The only workaround is save it as is and then open for edit. After its list of predefined states is available
![2020-06-17_12-35-39](https://user-images.githubusercontent.com/3409584/84930816-7ce2a580-b097-11ea-8605-a7fc416c5e9c.jpg)

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-25066` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-22562` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
