### ISSUE TITLE
Missing Countries from Google Shopping Ads

### ISSUE THREAD

**Issue by gondas33** [magento/magento2#25347]
### Preconditions (*)

1.Magento 2.3.3 CE (composer installation)

### Description (*)

Adding the same countries for the Content API Feed like on the google merchants page.
(There are about 40 countries on their system while in your module you only have about 14 countries)

### Expected result (*)

I wanted to mass-import products into their API for the 'Romania' country but failed as I didn't have the option.
`Romania` is present in [list](https://merchants.google.com/mc/products/sources/createPrimaryFeed)
![image](https://user-images.githubusercontent.com/51681379/68398422-5feb0900-017d-11ea-8c4b-9a59224f62ec.png)

### Actual result (*)
Country `Romania` is not present in list
![#25347IssueAdmin](https://user-images.githubusercontent.com/51681379/68398381-4ea1fc80-017d-11ea-846f-cb9018255cad.jpg)

### Benefits

-

### Additional information

magento/google-shopping-ads

**Comment by gondas33** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @an4rei. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @an4rei, here is your [Magento instance](https://i-25347-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25347-2-3-develop.instances.magento-community.engineering/admin](https://i-25347-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gondas33** [comment]
magento/google-shopping-ads is not available on the dev instance.

**Comment by VZeroCool** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-25347-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25347-2-3-develop.instances.magento-community.engineering/admin](https://i-25347-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @an4rei . Could you clarify what two country lists you compare?
Is this country list from Google Shopping ads configure page?
![#25347issue](https://user-images.githubusercontent.com/51681379/68383970-52268b00-015f-11ea-835f-c06c71879f3f.jpg)

**Comment by gondas33** [comment]
Hello @engcom-Delta 

That is indeed the Country field I was talking about. It defines the country+language of each product that gets sent to their API. Below you have the countries field from google merchant when creating a Content API:
![image](https://user-images.githubusercontent.com/11984860/68385705-07a70d80-0163-11ea-84e7-593df3a61e3d.png)

also found on https://merchants.google.com/mc/products/sources/createPrimaryFeed

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22916` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by robert-schmidt** [comment]
Any updates on this?

**Comment by gondas33** [comment]
Any idea who is developing this extension? The content is served via an API therefore direct interaction on the code from vendor won't help.

**Comment by rmanor1** [comment]
Hello, this should probably be closed as we've deprecated the Google Shopping ads Channel, and the [service was shut down ](https://docs.magento.com/user-guide/sales-channels/google-eol.html)as of Apr 28th.
