### ISSUE TITLE
No user type options when editing the role

### ISSUE THREAD

**Issue by oshanrube** [magento/magento2#2535]
Theres no option to edit the usertype when adding/editing the user role, although it shows up as backend user in grid view. is there another interface for this? 
also the webapiRoleLocator uses the user id when loading the permissions but customers and magento users are in completely different views therefore none of the customers have roles. how exactly does the new customer get a customer role?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by oshanrube** [comment]
this is actually about the class \Magento\Webapi\Model\WebapiRoleLocator:50 class requiring user ID for loading roles but theres no frontend option to set the user role to a user role type and also this scenario will not cover the Guest user role as it will not have a user id mapping
