### ISSUE TITLE
Invoice quantity round to whole integer

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#25367]
### Preconditions (*)

1. Magento Open Source 2.3.3

### Steps to reproduce (*)

1. Place order with qty of eg. 1.5 of product

### Expected result (*)

1. In the invoice the qty has to be 1.5 of the product
2. When making a credit if can select the 1.5 and put it back to stock and on the invoice

### Actual result (*)

![Naamloos](https://user-images.githubusercontent.com/23727130/67851623-2118db80-fb0b-11e9-9274-bdf191876ddc.jpg)

1. On the (email) invoice qty is 1
2. Credit is not possible

**Comment by Jilco** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jilco, here is your [Magento instance](https://i-25367-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25367-2-3-develop.instances.magento-community.engineering/admin](https://i-25367-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jilco** [comment]
@magento give me 2.3.3

**Comment by Jilco** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jilco, here is your [Magento instance](https://i-25367-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25367-2-3-3.instances.magento-community.engineering/admin](https://i-25367-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jilco** [comment]
I was able to reproduce in 2.3.3 instance

![Naamloos](https://user-images.githubusercontent.com/23727130/67853379-b8cbf900-fb0e-11e9-9d0c-df1a85327de1.jpg)

**Comment by Jilco** [comment]
Any idea about a work around? Because i now can't credit and invoices are incorrect

**Comment by webkul-ratnesh** [comment]
@magento give me 2.3-develop

**Comment by Jilco** [comment]
@webkul-ratnesh in develop the problem was not there in 2.3.3. it is. Any idea wich files i can replace to solve the problem?

**Comment by Jilco** [comment]
@webkul-ratnesh any progress?

**Comment by Jilco** [comment]
@magento-engcom-team were are the labels?

**Comment by gavinlimely** [comment]
Having this problem too, somebody looks to have put (int) in-front of where any qty is output. Which isn't ideal when the item has "Allow Qty as Decimals" set to "Yes".

**Comment by Jilco** [comment]
See #25521
