### ISSUE TITLE
Catalog Price Rule only applicable on original price, not on special price

### ISSUE THREAD

**Issue by MiomenteMUC** [magento/magento2#25364]
### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1. Give a product an original price i.e. 500€
2. Give this product a special price i.e. 400€
3. Create catalog price rule which reduces the price of products in a special category around 50€.

### Expected result (*)
1. Special price (my price for selling) is reduced by 50€ and is now 350€
2. Original price (strikethrough) stays 500€, new special price is now 350€
3. 
If (special_price != null){
     price = special_price - discount;
}
else{
    price = original_price - discount;
}

### Actual result (*)
1. Original price (strikethrough) stays 500€, new special price is still 400€, cause price rule is applied on original price (500€ - 50€ = 450€) so price rule is lower thant special price and special price is still applied
2.
If (original_price != null){
     price = original_price - discount;
}

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25364-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25364-2-3-develop.instances.magento-community.engineering/admin](https://i-25364-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tomekjordan** [comment]
its not a bug, its your private expectation. since M1 catalog price rules deduct price from original price. the lowest price is used. always. and its default Magento behavior

**Comment by engcom-Charlie** [comment]
Hello @Loqic2633 
I can confirm that this is the expected behavior of Magento https://github.com/magento/magento2/issues/25364#issuecomment-548555980. You can see options of Catalog Price Rules(percentage of original price):
![Screenshot from 2019-11-25 11-28-51](https://user-images.githubusercontent.com/51680850/69528572-28e76680-0f77-11ea-88ee-82b0fde1de66.png)

So i have to close your issue as non-issue.
Thanks for your report!
