### ISSUE TITLE
Tooltip is not aligned properly

### ISSUE THREAD

**Issue by ptylek** [magento/magento2#25376]
### Preconditions (*)

1. Magento version 2.3.2

### Steps to reproduce (*)

1. Go to Admin Panel -> Stores -> Settings -> Order Status -> Click any order status
2. Tooltip is not aligned properly

### Expected result (*)

![image](https://user-images.githubusercontent.com/34317830/67866889-e4a8a800-fb29-11e9-93f4-b554a1b93d6f.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/34317830/67866847-d9557c80-fb29-11e9-9155-2238cbac1626.png)

**Comment by ptylek** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ptylek. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ptylek, here is your [Magento instance](https://i-25376-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25376-2-3-develop.instances.magento-community.engineering/admin](https://i-25376-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ptylek** [comment]
Is not reproducible
