### ISSUE TITLE
Bulk Action Logs in backend missing if integration_id != user_id

### ISSUE THREAD

**Issue by WalterNu** [magento/magento2#25371]
### Preconditions (*)

1. Magento Commerce 2.3.2

### Steps to reproduce (*)

1. Create an integration for REST API usage
2. Do a bulk product update or any other bulk action
3. Check the "Bulk Actions" page in magento backend

### Expected result (*)

1. Log entries are in db table magento_bulk
2. Log entries show up in backend

### Actual result (*)

1. Log entries are in db table magento_bulk
2. Log entries don't show up in backend

In Database everything looks fine.
![grafik](https://user-images.githubusercontent.com/57180009/67858024-81624a00-fb18-11e9-913d-986eb0426408.png)
But in Magento Backend the Bulk Action Log entries just show up, if the integration_id of the used api matches the current backend user_id.
-> If i update the column user_id in table magento_bulk to the id of my current magento admin user id the entries are shown correctly.

**Comment by engcom-Golf** [comment]
HI @WalterNu thank you for you report, this is expected beheavior, there is a method to check for user id, i'm closing this as non-issue. 
![DeepinScreenshot_select-area_20191106145314](https://user-images.githubusercontent.com/51681547/68299910-58f0c780-00a5-11ea-97e0-9f3f4de49666.png)

**Comment by WalterNu** [comment]
Yes there is a method. And this method is wrong.
In my case a external seo consultant with restricted backend access sees all bulk action logs, but I as a admin shall not be allowed to see it? In my view I don't expect this behaviour.

**Comment by engcom-Golf** [comment]
@WalterNu I think that this behavior is correct, you can open an issue here -> https://github.com/magento/community-features/issues and discuss this feature.
Bulk Actions displayed for a user who has created an integration for this, so if your SEO have permission to create an integration this will be visible only for him
