### ISSUE TITLE
Bug for php bin/magento setup:static-content:deploy 

### ISSUE THREAD

**Issue by syntaxwanderer** [magento/magento2#2537]
I had a problem with pub/static a folder. And after delete this folder, I use this command.

php bin/magento setup:static-content:deploy

It works, but after, we have static files with location en_US. But my current location is uk_UA. I use uk_UA during installation.

**Comment by blankapham** [comment]
May be your Magento software is in default mode. You should run the Magento software in developer mode when you’re extending or customizing it. You can use this command line to show current mode : 
php bin/magento deploy:mode:show 
If you want to change to developer mode, you can use this command : 
php bin/magento deploy:mode:set developer
After change to developer mode, static files will be generated after reloading page.

**Comment by syntaxwanderer** [comment]
blankapham, you are right. My mode is default and I know it. And I think we have bug with command php bin/magento setup:static-content:deploy It does not work correct.

**Comment by mttjohnson** [comment]
```
bin/magento help setup:static-content:deploy
Usage:
 setup:static-content:deploy [-d|--dry-run] [languages1] ... [languagesN]

Arguments:
 languages             List of languages you want the tool populate files for. (default: ["en_US"])
```

It looks like the default of the command line may be always set to en_US, and why you are seeing those static files built. If you want another language then you need to specify it along with the command like

```
bin/magento setup:static-content:deploy uk_UA
```

**Comment by mazhalai** [comment]
@ArniXXX does @mttjohnson's solution solve your problem?

**Comment by syntaxwanderer** [comment]
Yes

**Comment by tohqecom** [comment]
Thanks @mttjohnson

**Comment by ghost** [comment]
hi,
 php bin/magento deploy:mode:show
Current application mode: default. (Note: Environment variables may override this value.)
i be also on default and i need this -> php bin/magento setup:static-content:deploy de_DE

but i get this issue -> [Magento\Framework\Exception\LocalizedException]
  NOTE: Manual static content deployment is not required in "default" and "developer" modes.
  In "default" and "developer" modes static contents are being deployed automatically on demand.
  If you still want to deploy in these modes, use -f option: 'bin/magento setup:static-content:deploy -f'

use 

xamp 7.1.2
win 10
php 7.1.2
