### ISSUE TITLE
Persistent Shopping Cart in magento 2.3.x

### ISSUE THREAD

**Issue by nambsscommerce** [magento/magento2#25389]
Magento 2.3.x

1. Config
1.1 Persistent Shopping Cart config: https://drive.google.com/file/d/1lDhGke_wf02xbekUXa3W4rumjbmE0LIU/view?usp=sharing
1.2. config cart price rule for wholesale customer group: discount 10$

2. Bug
You can see this video: https://www.loom.com/share/bc9ab26d3c4245a49aa8e90a078d2cd0

3. Expected result
Clear all cart price rule

4. Actual result
https://www.loom.com/share/bc9ab26d3c4245a49aa8e90a078d2cd0

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25389-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25389-2-3-develop.instances.magento-community.engineering/admin](https://i-25389-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@itsPranith Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by kanthy-magento** [comment]
@nambsscommerce  Please update the issue as per guidelines.

https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by sudheers-kensium** [comment]
@nambsscommerce I am not able to reproduced on Magento 2.3-development instance. If we logout the customer then cart will clear automatically.

**Comment by sudheers-kensium** [comment]
@nambsscommerce I am closing this issue.
