### ISSUE TITLE
 Configurable product is showing options for simple products not assigned to the current store

### ISSUE THREAD

**Issue by jerome-zhang** [magento/magento2#25391]
Reopen for https://github.com/magento/magento2/issues/17860#issue-355316051

**Summary**

When different simple products are available to a configurable product in different stores, the store filter is not being added to the collection on the category view page.

EXAMPLE
ConfigurableProduct
SimpleProduct1 (only available in StoreA)
SimpleProduct2 (available in StoreA and StoreB)
SimpleProduct3 (only available in StoreB)

StoreA is showing all three products on the category view page.

**Environment**

PHP 7.x
Apache 2.4
Magento 2.2.x & 2.3-develop

**Preconditions**

    Create a Magento instance with two stores (ex StoreA, StoreB)
    Create three simple products with different size attribute (any attribute will work). Assign Product1 only to StoreA, Assign Product2 to both StoreA and StoreB, Assign Product3 only to StoreB.
    Create a configurable product with all three Products.
    Add the configurable product to a category.
    Set the Theme to Luma for StoreA

**Steps to reproduce**

    In StoreA view the category that contains the configurable product.

**Expected result**

    Only simple products assigned to the store should be shown. In this example, only Product1 and Product2 should be shown on StoreA.

**Actual result**

    All three Products will be shown as an options when hovered over on the category page. In this example Product1, Product2, and Product 3 are shown.
    Click through to the product view page. All three products are available on StoreA because it's served from cache. NOTE! If you view on the product view page first, the category view will show the correct products as it will be cached from the product view page.

The problem appears to be coming from the store filter not being set in:
\Magento\ConfigurableProduct\Model\Product\Type\Configurable::getUsedProductCollection

        if (null !== $this->getStoreFilter($product)) {
            $collection->addStoreFilter($this->getStoreFilter($product));
        }

If the store filter is set, the correct products are returned. As an example, set the store filter in:
\Magento\ConfigurableProduct\Block\Product\View\Type\Configurable::getJsonConfig

$currentProduct->getTypeInstance()->setStoreFilter($store, $currentProduct);

**Comment by jerome-zhang** [comment]
Hi @magento-engcom-team , we still having this issue on 2.3, is there an official fixing for it?
Our developer provided a fixing, would you please help to review and see if that is the best way to solve the in correct store filter.

![2019-10-31_1459](https://user-images.githubusercontent.com/12635165/67925725-1df71b80-fbef-11e9-8aae-5a0c583baf4f.png)

[fixing_store_filter.zip](https://github.com/magento/magento2/files/3792500/fixing_store_filter.zip)

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-25391-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25391-2-3-develop.instances.magento-community.engineering/admin](https://i-25391-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22736` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jerome-zhang** [comment]
Hi @magento-engcom-team , when do you think this issue will be fixed?

**Comment by magento-engcom-team** [comment]
Hi @jerome-zhang. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.4.1` release.

**Comment by Nazar65** [comment]
this is not fixed in 2.4 or even i 2.5

**Comment by Nazar65** [comment]
@magento give me 2.4-develop instance
