### ISSUE TITLE
Magenta sees a new theme created

### ISSUE THREAD

**Issue by syntaxwanderer** [magento/magento2#2539]
I use this guide: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-create.html

1) Created folder: \app\design\frontend\Amrita\shop
2) Added theme.xml
`<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>Amrita Shop</title>
    <parent>Magento/blank</parent>
    <media>
        <preview_image>media/preview.jpg</preview_image>
    </media>
</theme>`
3) Added registration.php
`<?php
/**
- Copyright © 2015 Magento. All rights reserved.
- See COPYING.txt for license details.
  */

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::THEME,
    'frontend/Amrita/shop',
    **DIR**
);`

And, I can not see my new theme in Admin panel.

**Comment by syntaxwanderer** [comment]
I am sorry. I do not how, but it works for now, and I do not know why.

**Comment by jamescowie** [comment]
If you are still having issues can you open this on the developer forums please ? https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2

**Comment by syntaxwanderer** [comment]
Thx ) I will
