### ISSUE TITLE
Website Label is not properly visible in Advance pricing pop-up.

### ISSUE THREAD

**Issue by vikalps4** [magento/magento2#25401]
Website Label is not properly visible in Advance pricing pop-up.

### Preconditions (*)
1. Magento 2.3.x
2. PHP 7.2

### Steps to reproduce (*)

1.Login to Admin panel.
2. Navigate to Catalog->Products
3. Create/Edit a product.
4. Click on Advance Pricing link and check the section marked in screenshot.

### Expected result (*)
![screenshot-192 168 0 98-2019 10 31-16_45_14](https://user-images.githubusercontent.com/25526099/67942669-5d793400-fbfe-11e9-9b68-8174a910a46e.png)

### Actual result (*)
![screenshot-192 168 0 98-2019 10 31-16_42_23](https://user-images.githubusercontent.com/25526099/67942680-67029c00-fbfe-11e9-9a03-787138671687.png)

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25401-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25401-2-3-develop.instances.magento-community.engineering/admin](https://i-25401-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hello @vikalps4 
thank for reporting this issue . It seems this issue is already fixed .
