### ISSUE TITLE
Order creation from admin won't allow product quantity in decimal.

### ISSUE THREAD

**Issue by webkul-ratnesh** [magento/magento2#25400]
# Preconditions (*)

### Steps to reproduce (*)

1. Allow any simple product " Qty Uses Decimals", so that customer can purchase items in decimal qty(s) also.
2. Go to Sales->Order and try to create order for that products.
3. Add product to quote.
4. Update qty from integer to any of the decimal value.

### Expected result (*)

1. Quantity should be updated to decimal value.

### Actual result (*)

1. Quantity reset to the integer again.

**Comment by webkul-ratnesh** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-ratnesh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-ratnesh, here is your [Magento instance](https://i-25400-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25400-2-3-develop.instances.magento-community.engineering/admin](https://i-25400-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by webkul-ratnesh** [comment]
Not reproduced in 2.3-develop

**Comment by shamoon** [comment]
Im having this issue in 2.3.3, are you saying it was fixed in 2.3-develop? If so what is the fix?? I think it is causing a major issue or at least related where credit memos are also ignoring the decimals so customers are being refunded incorrect amounts. Please help!

**Comment by shamoon** [comment]
For the next lonely soul who finds this, fix is here: https://github.com/magento/magento2/pull/23943
Amazing how unreliable Magento is, cant update without breaking 10 other things, regression bugs out the wazoo.
