### ISSUE TITLE
Search by keywords : wrong number of records found and wrong  pagination in admin/products list page

### ISSUE THREAD

**Issue by aleks-2a** [magento/magento2#25406]
### Preconditions (*)

1. Magento CE and EE 2.2.x/2.3.x with sample datas
2. The issue is reproductible only if you do a request which return no result and only if the field **search by keywords** is filled lonely. In all other cases, the **number of records** and the **pagination form** is correct

### Steps to reproduce (*)
1. Go in Admin >> CATALOG >> Catalog >> Products to display the products list
2. Put a random string in **search by keywords**, in order to do a request which should return no result.

### Expected result (*)
1. Products list message : **We couldn't find any records**
2. 0 record found
3. pagination : 1 of 1

### Actual result (*)
1. Products list message : **We couldn't find any records** (correct)
2. 2096 records found (incorrect)
3. pagination : 1 of 105 (incorrect)
![Capture d’écran 2019-10-31 à 15 06 50](https://user-images.githubusercontent.com/4458940/67956473-6f55d980-fbf4-11e9-87c4-01ab97bfe534.png)

No issue if the search request returns at least 1 result - example with this test
![Capture d’écran 2019-10-31 à 15 09 42](https://user-images.githubusercontent.com/4458940/67956589-a2986880-fbf4-11e9-8cca-a026ccce7f30.png)

No issue if we use filter fields. 

Thanks you for your help.

**Comment by kanthy-magento** [comment]
@aleks-2a - I'm able to reproduce this issue in CE-2.3.3 by entering random string i.e. '#'.
It returned the below output.

![Category](https://user-images.githubusercontent.com/56586384/67961115-47309f80-fc21-11e9-94e0-4b40464ae9d3.PNG)


Thank You,
Pranith

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22626` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@magento I am working on it

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-25406-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25406-2-3-develop.instances.magento-community.engineering/admin](https://i-25406-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
I don't see this problem on 2.3-develop.

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25406-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25406-2-3-develop.instances.magento-community.engineering/admin](https://i-25406-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
@edenduong - I'm able to reproduce this issue on Magento instance which  is created with Magento sample data.

Please find the reproduce video url - https://www.screencast.com/t/AgCYuKfZQ


Thank You,
Pranith

**Comment by magento-engcom-team** [comment]
Hi @aleks-2a. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-22626` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
