### ISSUE TITLE
For JavaScript static tests, consider dropping jscs and consolidate using eslint

### ISSUE THREAD

**Issue by filmaj** [magento/magento2#25408]
### Summary (*)

The JavaScript static tests used in this project use two JavaScript linter programs: [eslint](https://eslint.org/) and [jscs](https://jscs-dev.github.io/). The [gruntfile that tests for various magento projects use includes running both](https://github.com/magento/magento2/blob/2.3-develop/dev/tools/grunt/tasks/static.js#L24-L25).

You will note on the jscs website that the project has merged with eslint and has not been actively maintained for 3 years. eslint is the single defacto JavaScript linter. I would propose this project considers dropping jscs and only using eslint. Why? For two reasons:

1. This would simplify testing configurations - only one JavaScript linter is needed and thus only one linter configuration needs to be maintained. Additionally, this reduces the development dependencies required by one. Leaner is faster is better 😄 
2. The current jscs linting rules raise false positives. I have listed what I have encountered while working on magento projects in the example section below.

### Examples (*)

JSCS false positive encountered thus far:

- The `requireCamelCaseOrUpperCaseIdentifiers` rule. It forces the use of a particular naming scheme for _all_ object keys - even object keys passed as parameters to third party libraries. Example of this failure being raised in the Adobe Stock Integration project's CI is [here](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/engcom-adobe-stock-integration-githubapp-prod/pull/4/585dc56b362e77e783c2914ab27c9c03/Statics/allure-report-ce/index.html#suites/3a29d43e5c1686787ff8c2a77e590abb/11fcffe8718efa44/); the `form_key` object key raising this warning is a parameter required by jQuery. Raising linter issues in third party libraries is not helpful as these third party libraries are not in the magento project's control. The only way around this issue is to ignore the rule or quote the key - neither of which help prevent issues in the project, which is the point of a linter.
- the `jsDoc` rule is triggered for copyright headers (see https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/adobe-stock-integration/pull/614/92ee3eb163204ef3c6cc4ba5084c046a/Statics/allure-report-ce/index.html#suites/3a29d43e5c1686787ff8c2a77e590abb/ff341d0d3df83cdc/)

### Proposed solution

Eliminate the need for and use of JSCS. That is, remove JSCS as a dependency, remove running JSCS as part of the typical JS static test suite run, and possibly review the JSCS rules currently enabled, together with reviewing the existing eslint rules, to a) ensure every rule enabled actually adds value to the testing process and helps us ensure quality and b) see what relevant eslint rule needs to be enabled to continue testing for that rule.

If this is deemed a worthwhile effort by the maintainers, I will happily put together a pull request for this.

**Comment by engcom-Charlie** [comment]
Hello @filmaj 

I close this issue as not relevant since PR(for this issue) is already merged.

Thank you for contribution and collaboration!
