### ISSUE TITLE
Error in Static Test Framework Dependency PHP Rule Test 

### ISSUE THREAD

**Issue by NicholasRoge** [magento/magento2#25413]
### Preconditions (*)

1. Magento Version: 2.3.3 EE
2. PHP Version:  7.2.24
3. Installed via `composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.3.3`

### Steps to reproduce (*)

1. `composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.3.3 magento2`
2. `cd magento2/dev/tests/static/framework/tests/unit` 
3. `../../../../../../vendor/bin/phpunit --configuration phpunit.xml.dist --filter '^Magento\\TestFramework\\Dependency\\PhpRuleTest'`

### Expected result (*)

1. All tests in the `Magento\TestFramework\Dependency\PhpRuleTest` class pass.

### Actual result (*)

1. `testGetDependencyInfoCaseGetUrl with data set "getUrl from same module" ('Magento\Cms\SomeClass', '$this->getUrl("cms/index/index")', array())` fails with error

```
Magento\Framework\Exception\LocalizedException: Invalid URL path: cms/index/index

/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:319
/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:126
/magento/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:206

Caused by
Magento\TestFramework\Exception\NoSuchActionException: cms/index/index

/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/Route/RouteMapper.php:185
/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:304
/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:126
/magento/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:206
```

2. `testGetDependencyInfoCaseGetUrl with data set "getUrl from another module" ('Magento\SomeModule\SomeClass', '$this->getUrl("cms/index/index")', array(array('Magento\Cms', 'hard', 'getUrl("cms/index/index"')))` fails with error:

```
Magento\Framework\Exception\LocalizedException: Invalid URL path: cms/index/index

/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:319
/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:126
/magento/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:206

Caused by
Magento\TestFramework\Exception\NoSuchActionException: cms/index/index

/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/Route/RouteMapper.php:185
/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:304
/magento/dev/tests/static/framework/Magento/TestFramework/Dependency/PhpRule.php:126
/magento/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:206
```

### Possible Cause

Both of these tests seem to be failing due to `dev/tests/static/framework/Magento/TestFramework/Dependency/Route/RouteMapper.php` because they're installed as vendor modules and the RouteMapper class is hardcoded to translate the module prefix (`Magento\Cms` in this case) to a path by a simple conversion of '\\' to the directory separator.  As a result, when [preg_grep is executed](https://github.com/magento/magento2/blob/67f525d70239d01ecbc04c1bfa4407f9250a7934/dev/tests/static/framework/Magento/TestFramework/Dependency/Route/RouteMapper.php#L315), no actions are found due to all of the applicable action files being filtered out because the RouteMapper is expecting them to be installed under `app/code`.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22761` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
