### ISSUE TITLE
Created New theme After removing Still showing in content->Themes

### ISSUE THREAD

**Issue by nishantbkw** [magento/magento2#2541]
Hi , I Created a new theme from scratch after testing i removed it fully 
1. Removed Whole Var Folder 
2. Flush Cache 
3. run magento setup:static-content:deploy again 

But still it's showing name and path of the theme in admin Content -> Themes 

Can you please suggest me how can i remove fully cache ?

**Comment by syntaxwanderer** [comment]
I had same a problem. Magenta behave unpredictably if you delete a folder. In admin panel we have 2 buttons. Flush magento cache and Flush static files cache. You need use this functions because you will have this a problem again. I do not know why for now.

**Comment by nishantbkw** [comment]
Hi ArniXXX , 
removing my custom theme row from theme table resolved the issue 
Next time i will try flush static files cache button . 
I wonder if there some method to stop cache as it slower down the development work

**Comment by buskamuza** [comment]
Hi @nishantbkw ,
in Magento themes are registered in DB (as you already found out). So just removing the theme folder does not lead to full removal of the theme, instead it puts the application in an invalid state.
Instead, please, use `./bin/magento theme:uninstall` command to remove a theme.
