### ISSUE TITLE
Throwing Error (Invalid Form Key. Please refresh the page.) on Form Submit in Chrome

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#25427]
Throwing Error On Form Submit in Google Chrome, i have Tried this with Different Magento Version and Couple of New Installation I tried in Mozilla Firefox its working Fine There

### Preconditions (*)

1. Installed Magento 2.x (Any Version)
2. Browser (Google Chrome Version 75.0.3770.142 (Official Build) (64-bit))
3.  Server Locahost
4. OS (Ubuntu 16.04)

### Steps to reproduce (*)

1. Install Magneto on Localhost
2. Open Browser Chrome
3. Click Sign In Or Create Account
4. Fill Required Info
5. Submit Form

### Expected result (*)
1. New User Will Register Or Login User to his Account

### Actual result (*)
1. Giving warning (Invalid Form Key. Please refresh the page.)
2. Redirecting to same page

Suggested Solution:
Hello People!
Well after a long time I found the solution on Magento Stackexchange it was actually an issue with base URL
My Previous URL Was http://locahost/magento233
My New URL is http://127.0.0.1/magento233

Now it is working fine

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25427-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25427-2-3-develop.instances.magento-community.engineering/admin](https://i-25427-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
We are able to replicate this issue in instance  @ https://i-25427-2-3-develop.instances.magento-community.engineering/admin/admin/

Please find the image for your reference
![Form Key Validation](https://user-images.githubusercontent.com/56586384/68012095-1eef8200-fcaf-11e9-8821-e9e5e4d51a24.PNG)
.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22675` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krunallucent** [comment]
Yes, I am facing this issue in many places.

I am facing this issue Invalid Form Key. Please refresh the page.

some times and sometimes not. 1. When I add Product to cart. 2. When I want to delete a product from a cart. 3. When I want to Update a cart. 4. When I want to Register. 5. When I load ajax Filter with own a javascript code.

**Comment by hostep** [comment]
I've seen this admin login problem happening a few times in Magento 2.3.1 and 2.3.2 (not seen yet on 2.3.3, but that doesn't mean it's not there). It's not easily reproducible, but what always seems to fix it in our case was executing `bin/magento config:set admin/security/session_lifetime 14400` (or some other number, `900` seems to be the default)

This is not the same problem as @WaqarAli123 or @krunallucent is reporting, but it's the issue @itsPranith is mentioning.

**Comment by sarveshlucent** [comment]
Yes, I am facing this issue in many places.

I am facing this issue Invalid Form Key. Please refresh the page.

some times and sometimes not. 1. When I add Product to cart. 2. When I want to delete a product from a cart. 3. When I want to Update a cart. 4. When I want to Register. 5. When I load ajax Filter with own a javascript code.

**Comment by TheRealHunzik** [comment]
> I've seen this admin login problem happening a few times in Magento 2.3.1 and 2.3.2 (not seen yet on 2.3.3, but that doesn't mean it's not there). It's not easily reproducible, but what always seems to fix it in our case was executing `bin/magento config:set admin/security/session_lifetime 14400` (or some other number, `900` seems to be the default)
> 
> This is not the same problem as @WaqarAli123 or @krunallucent is reporting, but it's the issue @itsPranith is mentioning.

i am Facing this Issue in Magento CE 2.3.3

**Comment by TomashKhamlai** [comment]
@hostep, as I could understand reporter is talking about the error that can be seen by the customer, but screenshots are from the admin login page...

**Comment by WaqarAli123** [comment]
> @hostep, as I could understand reporter is talking about the error that can be seen by the customer, but screenshots are from the admin login page...

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by hostep** [comment]
@TomashKhamlai: indeed, I got confused by the screenshots. Maybe a second issue could be opened for that? @itsPranith?

No idea why this issue got archived though, let me reopen.

**Comment by itsPranith** [comment]
@hostep - This issue is replicating on Magento instance which is created with Magento sample data. 

Please find the video of Magento instance which is created with sample data. 
Video URL - https://www.screencast.com/t/AgCYuKfZQ

**Comment by sarveshlucent** [comment]
I face this issue everywhere in chrome as well as firefox. also each and every form or jquery post page.

so please let me help.
My  staging server URL is ==> https://magento-331546-1017597.cloudwaysapps.com/

**Comment by engcom-Delta** [comment]
Hi @WaqarAli123 thank you for your report. Unfortunately, I am not able to reproduce issue by steps you described on clean 2.3-develop seems like this related to your custom modules. 
Checked on:
- Chrome Version 78.0.3904.70 
- Firefox 70.0

![#25427issue](https://user-images.githubusercontent.com/51681379/68125328-0505a780-ff1a-11e9-8607-586569e570b2.gif)

If you'd like to update the issue, please reopen it.

**Comment by sarveshlucent** [comment]
@engcom-Delta please checkout my problem please and let me know how can I resolve it?
I face this issue everywhere in chrome as well as firefox. also each and every form or jquery post page.

so please let me help.
My staging server URL is ==> https://magento-331546-1017597.cloudwaysapps.com/

**Comment by engcom-Delta** [comment]
@sarveshlucent I checked `Sign Up` and `Log In` on your [server](https://magento-331546-1017597.cloudwaysapps.com/) and I didn't experience issue that described here on browser versions  mentioned before.
You could refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by sarveshlucent** [comment]
@engcom-Delta So, what can I do. I need to fix it because I have to go live.

**Comment by TheRealHunzik** [comment]
> @sarveshlucent I checked `Sign Up` and `Log In` on your [server](https://magento-331546-1017597.cloudwaysapps.com/) and I didn't experience issue that described here on browser versions mentioned before.
> You could refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

I saw Many Issue Many times on Magento Stack Exchange i tried each an every solution but havn't got any success

**Comment by sarveshlucent** [comment]
@WaqarAli123 @engcom-Delta please see https://prnt.sc/psjm4y

**Comment by TheRealHunzik** [comment]
This issue is previously Reproduced By @itsPranith  But i don't Know why they closed this issue

**Comment by engcom-Delta** [comment]
@WaqarAli123 your steps describes issue on frontend that is not reproducible from your description.
This [comment](https://github.com/magento/magento2/issues/25427#issuecomment-548706715) is related to backend login page as was noted [here](https://github.com/magento/magento2/issues/25427#issuecomment-549094408)

**Comment by TheRealHunzik** [comment]
@engcom-Delta  i my question i write a Line "Throwing Error On Form Submit in Google Chrome," this happens on every form submit..  I don't Know @itsPranith  has tried on frontend or not

**Comment by engcom-Delta** [comment]
@WaqarAli123 Please, update appropriate steps to make clear where you experience this problem. You could use magento instance to verify if issue is reproducible according your steps.

**Comment by TheRealHunzik** [comment]
@engcom-Delta  Can you provide me a magento instance.. All the above instances are expired

**Comment by engcom-Delta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [Magento instance](https://i-25427-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25427-2-3-develop.instances.magento-community.engineering/admin](https://i-25427-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TheRealHunzik** [comment]
@engcom-Delta  Yes you are Right its working fine in this Magento Instance

But i am Still getting this issue on local server  :(

**Comment by TomashKhamlai** [comment]
### Little troubleshooting guide
If you have rich experience with Magento 2 you could try these steps to find the problem. But read this first [Merchant Docs: Backup](https://docs.magento.com/m2/ce/user_guide/system/backups.html)
1) Make sure that your Magento instance is in developer mode
2) Switch to the default Luma theme, remove all the content of `var` `generated` `pub/static` folders except hidden (dot) files like `.htacess` that are inside of those folders. :warning: If you accidentally remove that files storefront will fail to load. If no other people have access to your local server and you don't know how to change shell options then it should be safe to run in the ssh/terminal
```shell
rm -rf var/* generated/* pub/static/*
```
This command keeps hidden files when default shell options are not overridden. You cannon revert this action, make sure that you have a **backup**.
3) Check what happens
4) If it is still reproducible switch back the theme and try disabling modules.
5) Disable some module
6) Run `php bin/magento setup:upgrade`
7) Remove all the content of `var` `generated` `pub/static` folders except hidden (dot) files like `.htacess`.
8) Check what happens

I know it can be time-consuming but unfortunately, it is the best thing that I can suggest.

Have a nice day! :slightly_smiling_face:

**Comment by sarveshlucent** [comment]
Hi @engcom-Delta, I am facing form key invalid issue on https://magento-331546-1017597.cloudwaysapps.com/paint-mediums/oil-paint-mediums.html.

I changed in local server localhost to 127.0.0.1 and now no error comes.

But I am facing this issue in my staging server. ==> https://magento-331546-1017597.cloudwaysapps.com/paint-mediums/oil-paint-mediums.html

Please help m.
Thanks

**Comment by TomashKhamlai** [comment]
A good point to start is to figure out why response contains SID
![image](https://user-images.githubusercontent.com/11827230/68400709-24523e00-0181-11ea-9b9b-c7d9572fcdf8.png)
and get rid of warnings.

From the Magento Admin side, you can go to the Store > Configuration > General > Web > Session Validation Settings > Use SID on Storefront and set to No on your staging server, but session id can be set by PHP regardless of this Magento2 setting.

Sorry, I cannot help too much at all.

**Comment by sarveshlucent** [comment]
Perfect NOw It's working now.
Thanks a lot for your help.

you know what I am really happy, you save me lots of time.
Hope now in future invalid key related issue not come.

Thanks a lot.
Sarvesh Patel

**Comment by sarveshlucent** [comment]
So Sad, Still getting Invalid form key error!

**Comment by TheRealHunzik** [comment]
Hello People!
Well after a long time I found the solution on [Magento Stackexchange](https://magento.stackexchange.com/a/164382/78648) it was actually an issue with base URL  
My Previous URL Was http://locahost/magento233
My New URL is http://127.0.0.1/magento233

Now it is working fine

**Comment by itfork** [comment]
I was too getting this error "Invalid Form Key. Please refresh the page." on my local setup magento2 (2.3.4) when I setted local url as **http://magento2** (during magento installation) but when I changed url to **http://magento2.local** it solved my problem (my OS - Debian 9):
1) Edit `/etc/hosts` and add in it the `magento2.local 127.0.0.1`
2) Edit table **core_config_data** and change row where column `path` equal **web/unsecure/base_url** in `value` column paste the **http://magento2.local/**
3) Run `php bin/magento cache:flush`

**Comment by gaganmagento** [comment]
I face this issue in Magento 2.3.3. It works in chrome private window but not in normal browser. I found that it could be related to CsrfValidator or formKeyValidator, but unable to dig further. Any help will be appreciated.
Thanks

**Comment by azdeveloping** [comment]
> I was too getting this error "Invalid Form Key. Please refresh the page." on my local setup magento2 (2.3.4) when I setted local url as **http://magento2** (during magento installation) but when I changed url to **http://magento2.local** it solved my problem:
> 
> 1. Edit `/etc/hosts` and add in it the `magento2.local 127.0.0.1`
> 2. Edit table **core_config_data** and change row where column `path` equal **web/unsecure/base_url** in `value` column paste the **http://magento2.local/**
> 3. Run `php bin/magento cache:flush`

This worked for me but going to http://magento2.local/ had error finding IP address
so I changed /etc/hosts file to 127.0.0.1 magento2.local

**Comment by alok0590** [comment]
> ### Little troubleshooting guide
> If you have rich experience with Magento 2 you could try these steps to find the problem. But read this first [Merchant Docs: Backup](https://docs.magento.com/m2/ce/user_guide/system/backups.html)
> 
> 1. Make sure that your Magento instance is in developer mode
> 2. Switch to the default Luma theme, remove all the content of `var` `generated` `pub/static` folders except hidden (dot) files like `.htacess` that are inside of those folders. warning If you accidentally remove that files storefront will fail to load. If no other people have access to your local server and you don't know how to change shell options then it should be safe to run in the ssh/terminal
> 
> ```shell
> rm -rf var/* generated/* pub/static/*
> ```
> 
> This command keeps hidden files when default shell options are not overridden. You cannon revert this action, make sure that you have a **backup**.
> 3) Check what happens
> 4) If it is still reproducible switch back the theme and try disabling modules.
> 5) Disable some module
> 6) Run `php bin/magento setup:upgrade`
> 7) Remove all the content of `var` `generated` `pub/static` folders except hidden (dot) files like `.htacess`.
> 8) Check what happens
> 
> I know it can be time-consuming but unfortunately, it is the best thing that I can suggest.
> 
> Have a nice day!

This Actually worked for me, Thank You. :)

**Comment by drinkingsouls** [comment]
I have this issue that has appeared since upgrading to 2.4.3. Was there any progress made with this?

**Comment by hostep** [comment]
The issue @drinkingsouls refers to is this one: https://github.com/magento/magento2/issues/33749, which is not the same issue as this one, it's a new one in Magento 2.4.3, just leaving this here in case people end up here looking for some more info.
