### ISSUE TITLE
Bug: the mouse cursor has wrong type ("text") while it is above the frontend product gallery

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2542]
![](https://mage2.pro/uploads/default/original/1X/b296bc4965ba71910fcf6ae1e03d0b850336b750.png)

Similar to https://github.com/magento/magento2/issues/2405

**Comment by zanilee** [comment]
Hello, @dfediuk!
Thank you for reporting this issue. Internal ticket number: MAGETWO-46188

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-46188 is closed and delivered to mainline. Please let us know if you still have an issue.
