### ISSUE TITLE
Magento 2.3.3 issue on Backend Category Module

### ISSUE THREAD

**Issue by niku0911** [magento/magento2#25423]
Hi We are using magento 2.3.3 , but we facing issue on Backend Category page,

please check and update us,http://prntscr.com/pqyj6y

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25423-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25423-2-3-develop.instances.magento-community.engineering/admin](https://i-25423-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @niku0911 Not able to reproduce the issue on latest magento instance as described you in screenshot.
Feel free to reopen if you confirm that issue is reproduce on latest instance https://github.com/magento/magento2/issues/25423#issuecomment-548679283
Thanks

**Comment by niku0911** [comment]
Some error display in category Module in backend

**Preconditions (*)**
Magento : 2.3.3

**Steps to reproduce (*)**
Admin -> Catalog Category
Add New Category(Add Image)
After added Category successfully
update category

**Expected result (*)**
Category banner as same as firstly added image

**Actual result (*)**
Categoey Image blank and Frontside category Image linklike "imagename_1"

**Comment by niku0911** [comment]
can you reopen the issue?

**Comment by krishprakash** [comment]
Please confirm that issue is reproduced on latest instance as instructed you here 
 https://github.com/magento/magento2/issues/25423#issuecomment-548679283
Thanks

**Comment by krishprakash** [comment]
Seems the issue is already fixed in latest instance refer the issue  #25099

**Comment by niku0911** [comment]
yes got that solution, thanks for help @krishprakash
