### ISSUE TITLE
Magento 2.3.3 : Under Cache Management section, cache type checkboxes are not aligned 

### ISSUE THREAD

**Issue by sudhanshu-bajaj** [magento/magento2#25429]
### Summary (*)

GoTo System > Tools > Cache Management
The cache type checkboxes are not aligned. Also on click doesn't work it works when we click on empty area on the right.

### Examples (*)

![image](https://user-images.githubusercontent.com/5261059/68016579-d4323200-fccf-11e9-8f3c-8908b87bedc1.png)

### Proposed solution

Should be aligned and clicking on checkbox should work.

**Comment by kanthy-magento** [comment]
@sudhanshu-bajaj  - This is working fine on @ https://i-25427-2-3-develop.instances.magento-community.engineering/admin/admin/cache/
![Cache Management](https://user-images.githubusercontent.com/56586384/68017151-0f2a6a80-fcbc-11e9-84ec-1589816eec81.PNG)

Hence it is not reproduce able.

**Comment by hostep** [comment]
I can reproduce this on 2 installations of Magento 2.3.3 shops and on a local installation of Magento 2.3-develop (using commit 5b54f063700de1fbfd75654dba4138fb6e5ab71d).

This happens both in the Cache Management as in the Index Management grids.

I'm going to re-open for now, can somebody else reproduce this?
Thanks!

**Comment by kanthy-magento** [comment]
@hostep - I'm unable to reproduce even at Index management @ https://i-25427-2-3-develop.instances.magento-community.engineering/admin/indexer/indexer/list/

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25429-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25429-2-3-develop.instances.magento-community.engineering/admin](https://i-25429-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25429-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25429-2-3-3.instances.magento-community.engineering/admin](https://i-25429-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22678` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
Hi @itsPranith 
the issue is reproducible at magento 2.3-develop and magento 2.3.3 versions at chrome latest version Version 78.0.3904.87

**Comment by kanthy-magento** [comment]
> Hi @itsPranith
> the issue is reproducible at magento 2.3-develop and magento 2.3.3 versions at chrome latest version Version 78.0.3904.87

Thank You. I'll update chrome version and check.

**Comment by hostep** [comment]
@itsPranith: your answer seems to imply you were testing on an older version of Chrome and it would mean it worked over there? Is that correct? What version was that?

It looks like this problem seems to be 2 folded then.
Here are some other observations from my side:

### browser-related
- Issue occurs on Chrome 78.0.3904.70 and 78.0.3904.87
- Issue does not occur in Firefox 69.0.3 and 70.0.1
- Issue does not occur in Safari 13.0.3

### code related
- After testing various Magento versions using Chrome 78, I found out the issue was not there in Magento 2.3.1, but appeared in Magento 2.3.2 and 2.3.3
- After git bisecting between 2.3.1 and 2.3.2, I found https://github.com/magento/magento2/pull/21022 to have caused the problem

This is probably enough info for somebody to figure out a solution to this problem.

**Comment by kanthy-magento** [comment]
@hostep - The Chrome browser Version is 77.0.3865.120 (Official Build) (64-bit). On this it is working.

**Comment by itmsenior** [comment]
It's caused by a rendering change in chrome v78. Elements with display:unset now don't align correctly.

**Comment by ccondra** [comment]
I also came across this issue using  Chrome Version 78.0.3904.70.  It seems to affect pages with grids in the System menu (Cache Management, Index Management, Notifications) but not pages with grids in other menus, such as Catalog or Customer.
