### ISSUE TITLE
Ampersand or Plus sign in product attribute option value not saved

### ISSUE THREAD

**Issue by mattbolton-melon** [magento/magento2#25420]
### Preconditions (*)

1. Magento 2.3.2
2.

### Steps to reproduce (*)

1. Add or Edit a drop-down attribute
2. Save an attribute option value of "1 & 1"
3. Save an attribute option value of "1 + 1"
4. Save attribute

### Expected result (*)

1. Attribute option values are the same as entered originally
![Screen Shot 2019-10-31 at 3 10 23 PM](https://user-images.githubusercontent.com/56836835/67990166-4a606700-fbf2-11e9-8660-1fa49bc8a165.png)

### Actual result (*)

1. Attribute that was entered as "1 & 1" is now "1 "
2. Attribute that was entered as "1 + 1" is now "1   1"
![Screen Shot 2019-10-31 at 3 21 07 PM](https://user-images.githubusercontent.com/56836835/67990105-16854180-fbf2-11e9-808e-45b8ef32e353.png)

3. This appears to be a regression, since #18493 and #18263 appear to have fixed this issue previously.

**Comment by mattbolton-melon** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @mattbolton-melon. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mattbolton-melon, here is your [Magento instance](https://i-25420-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25420-2-3-develop.instances.magento-community.engineering/admin](https://i-25420-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mattbolton-melon** [comment]
Not reproducing on dev-2.3-develop
Just 2.3.2

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25420-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25420-2-3-develop.instances.magento-community.engineering/admin](https://i-25420-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@mattbolton-melon - I have verified this issue in the latest Magento 2.3 Instance. Attribute value saves on proper way whichever you have entered  "1 & 1" and "1 + 1".
Magento Team already verified and closed this issue #18493.

Let me know @mattbolton-melon, Can I close this issue or not?

Thanks.

**Comment by mattbolton-melon** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @mattbolton-melon. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mattbolton-melon, here is your [Magento instance](https://i-25420-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25420-2-3-develop.instances.magento-community.engineering/admin](https://i-25420-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mattbolton-melon** [comment]
@ajijshekh123 Please close. I found that we had an old version of 
_module-catalog/view/adminhtml/web/js/options.js_
which was the cause of our failure.

**Comment by ajijshekh123** [comment]
Okay @mattbolton-melon
