### ISSUE TITLE
Product edititing not possible with disabled Temando Shipping Extension in M 2.3.3 

### ISSUE THREAD

**Issue by itsolon** [magento/magento2#25430]
### Preconditions (*)
Magento 2.3.3 , PHP 7.2 FPM, NGINX , Ubuntu 18.04
we have following 3 installations
A installation migrated from 2.2 to 2.3.3 directly (migrated 1 day after release m2.3.3)
B installation directly installed 2.3.3 (installed within one week after release)
C installation 2.3.2 then migrated 2.3.3 (migrated yesterday)

### Steps to reproduce (*)
disable the module temando shipping as we do not need it and the module produces for us unneccessary elements in admin sales menu

### Expected result (*)
in C the module can safely be disabled without any issues, the sales admin menu points do not contain the related menu entries

### Actual result (*)
the difference is 
in the installations A & B when disabling temando shipping then i cannot edit products in 2 of them white screen(error 500) and following error in **debug.log**
![image](https://user-images.githubusercontent.com/51680850/68299908-57270400-00a5-11ea-8cb3-239f8910c983.png)

`[2019-11-01 09:49:37] main.INFO: Broken reference: the 'product.reviews' element cannot be added as child to 'product_tabs', because the latter doesn't exist [] []`

REMARK:
i have seen that in database the Version of temando differs, perhaps its important
Schema 1.6.0 Data version 1.6.0 for A & B
Schema 1.5.0 Data Version 1.5.0 for C

**Comment by DominicWatts** [comment]
Temando_Shipping module might have added an EAV attribute already with a specific source model that no longer exists. This could generate an exception Class Temando\Shipping\Model\Source\PackagingType does not exist when trying to edit product. To fix this, run the following SQL query in your database:

```
DELETE FROM `eav_attribute` WHERE `source_model` LIKE '%Temando%' 
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22866` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jaredchu** [comment]
> Temando_Shipping module might have added an EAV attribute already with a specific source model that no longer exists. This could generate an exception Class Temando\Shipping\Model\Source\PackagingType does not exist when trying to edit product. To fix this, run the following SQL query in your database:
> 
> ```
> DELETE FROM `eav_attribute` WHERE `source_model` LIKE '%Temando%' 
> ```

Worked for me, thanks a lot!!!

**Comment by itsolon** [comment]
worked for me too! Thank you very much!

**Comment by ray-moncada** [comment]
This worked for me on Magento 2.3.3 installation.

**Comment by BruceTranForix** [comment]
> Temando_Shipping module might have added an EAV attribute already with a specific source model that no longer exists. This could generate an exception Class Temando\Shipping\Model\Source\PackagingType does not exist when trying to edit product. To fix this, run the following SQL query in your database:
> 
> ```
> DELETE FROM `eav_attribute` WHERE `source_model` LIKE '%Temando%' 
> ```

nice solution, it helped me to save a lot of time.
I found another solution: we only need to set NULL for **source_model** instead of deleting attributes.

**Comment by jaimiedijstra** [comment]
> Temando_Shipping module might have added an EAV attribute already with a specific source model that no longer exists. This could generate an exception Class Temando\Shipping\Model\Source\PackagingType does not exist when trying to edit product. To fix this, run the following SQL query in your database:
> 
> ```
> DELETE FROM `eav_attribute` WHERE `source_model` LIKE '%Temando%' 
> ```

Worked for me too as the others! Just 3 rows effected, saved me a headache thank you!

**Comment by varun2287** [comment]
Hi All,

I am getting the same error so i deleted the 3 rows in the eav_attribute table using the above query.
Now i am getting this error-
Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /home/ampscooters/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 385 and defined in /home/xxxxxxx/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:335
Stack trace: 

Can someone help?? this is very urgent.Please

**Comment by inkobject** [comment]
Just throwing my hat in the ring: I have seen this problem on 2.3.4. after disabling Temando_Shipping. I reenabled it and the problem went away.

**Comment by seattletechworks** [comment]
Experience same issue in 2.3.4 after disabling Temando_Shipping. 

Ran the query on my magento database:  SELECT * FROM eav_attribute WHERE source_model LIKE "%Temando%" 

Set the 3 values to "NULL". Now I can edit products again.

**Comment by densen45** [comment]
I experienced the same issue in 2.3.5 (Temando_ShippingRemover is disabled). 

Setting the source_model for the three Temando's eav_attributes to NULL solved this issue.

Thanks to all who have pointed this out!

**Comment by haxor211** [comment]
I have ran the query in my database and removed 3 rows.. the problem still persists, what do I do?? I dont want to enable this useless module.

I also used the new module in 2.4.0 "Temando_ShippingRemover" and ran setup:upgrade, still doesnt work!!

I also tried deleting the attributes starting with "ts_%" in datatbase, this doesnt help either!!!!

The error "Exception #0 (ReflectionException): Class Temando\Shipping\Model\Source\PackagingType does not exist" is still here. Help me out please its driving me insane

**Comment by ChameleonDevil** [comment]
> Experiencing same issue in 2.3.4 after disabling Temando_Shipping.
> 
> Ran the query on my magento database: SELECT * FROM eav_attribute WHERE source_model LIKE "%Temando%"
> 
> Set the 3 values to "NULL". Now I can edit products again (and leave Temando_Shipping disabled).

Can also confirm that in `Magento 2.3.5` this still works, but overall just `DELETE`ing the unused attributes from the `eav_attribute` table as described is still better in some cases. 

NOTE:_**(I have a new migration from Magento 1, so have no need for these related attribute data_ **
