### ISSUE TITLE
Multi Currency - Price Import from webservice Not working

### ISSUE THREAD

**Issue by harshilpatwa** [magento/magento2#2544]
Stores->Currency Rates -> Import rates not working for multi currency.

**Comment by daim2k5** [comment]
@harshilpatwa sorry for the late response. Colud you please provide more details like a error messages?

**Comment by harshilpatwa** [comment]
There is no error message showing , it just about blank or keeping same rate as previous when importing the rates.

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @harshilpatwa thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
