### ISSUE TITLE
Composer issue when running composer require

### ISSUE THREAD

**Issue by faouzi53** [magento/magento2#25445]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. Warning: require(/home/nolimi2q/public_html/vendor/composer/../../registration.php): failed to open stream: No such file or directory in /home/nolimi2q/public_html/vendor/composer/autoload_real.php online 70

Fatal error: require(): Failed opening required '/home/nolimi2q/public_html/vendor/composer/../../registration.php' (include_path='/home/nolimi2q/public_html/vendor/magento/zendframework1/library:.:/opt/alt/php72/usr/share/pear') in /home/nolimi2q/public_html/vendor/composer/autoload_real.php on line 70
2. 
3. 

### Expected result (*)

1. i expected to install some extensions 

### Actual result (*)

1. i got the above error

**Comment by Den4ik** [comment]
Hi @faouzi53 Thank you for reporting but this is not Magento related issue. You may ask help at https://magento.stackexchange.com/
