### ISSUE TITLE
Cart Price Rule save x when you spend y with coupon rule gets removed incorrectly.

### ISSUE THREAD

**Issue by fuzzyjared** [magento/magento2#25440]
### Preconditions (*)
Magento 2.3.2

### Steps to reproduce (*)
1. Marketing -> Cart Price Rule
2. Create a rule for Save $50 when you spend over $300
3. Use Specific Coupon SAVE50
4. Conditions -> If ANY of these conditions are TRUE: Subtotal (Excl. Tax) equals to or greater than 300.
5. Actions -> Apply - Fixed amount discount for whole cart, Discount Amount - 50
6. Go to the store front and add products to cart to equal more than 300 but less than 349.
7. Go to shopping cart and apply the coupon code SAVE50

### Expected result (*)

1. The coupon should be applied and the subtotal should be less than 300.

### Actual result (*)

1. The coupon code is accepted and you get a SUCCESS message You used coupon code "SAVE50".
2. The Applied Coupons will list SAVE50
3. The coupon value appears to be applied initially but will be removed from order totals as soon as the /rest/default/V1/guest-carts/***/totals-information is hit.
4. Refreshing the page will continue to have the coupon applied but the order totals will not have the discount applied.

![Screen Shot 2019-11-01 at 4 28 09 PM](https://user-images.githubusercontent.com/1541668/68057687-ac899c80-fcc4-11e9-9c28-b3faa61c3ed9.png)

**Comment by engcom-Delta** [comment]
Hi @fuzzyjared thank you for your report. Unfortunately, I am not able to reproduce issue by steps you described on clean 2.3-develop.

![#25440issueCoupon](https://user-images.githubusercontent.com/51681379/68112045-26a26700-fef9-11e9-8886-23b95815a01a.png)

![#254440issue](https://user-images.githubusercontent.com/51681379/68112049-2904c100-fef9-11e9-8f9b-31ef51487fdc.png)

If you'd like to update the issue, please reopen it.

**Comment by Rickertje** [comment]
Not me but @fuzzyjared I suppose

**Comment by engcom-Delta** [comment]
@Rickertje thanks. Updated comment.
