### ISSUE TITLE
Move JS code to the bottom of the page eliminates bundling and signed static files

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25441]
Summary: 
You can't both defer loading of js and bundle javascript and have signed static files

### Preconditions (*)

1. Magento 2.3.2+ CE, PHP 7.1.26, mariadb 10.3, nginx 1.15.8

### Steps to reproduce (*)

1. Stores > Configuration > Developer > JavaScript Settings and enable the Move JS code to the bottom of the page option. 

### Expected result (*)

1. Signed static files should work
2. JS bundling and merging should work

### Actual result (*)

1. Signed static files do not work, it links to them without the version string in it
2. Merging and bundling to not work, every JS file is loaded individually 

Results in 203 javascript file requests on my site.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @SoloDevAtrix. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @SoloDevAtrix, here is your [Magento instance](https://i-25441-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25441-2-3-develop.instances.magento-community.engineering/admin](https://i-25441-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Seems to work on vanilla dev branch closing
