### ISSUE TITLE
Check Updater Application Availability - Updater application is not available

### ISSUE THREAD

**Issue by magenx** [magento/magento2#2546]
in magento admin when you go to System - Web Setup Wizard - Component manager -> disable extension

what it's all about?

```
Check Updater Application Availability
Updater application is not available. Hide detail

Download and install the updater.

For additional assistance, see updater application help.

http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/updater.html
```

updater page has no traces of this package. maybe i dont understand something.
where to get this updater? is it available to install?

**Comment by mazhalai** [comment]
@magenx if you deployed via composer, the `update` folder should be available. How did you deploy magento2?

**Comment by magenx** [comment]
we have used this manual page:
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/dev_install.html

cloned repository, then we run composer and installed with web interface.

**Comment by mazhalai** [comment]
Please clone https://github.com/magento/magento2-community-edition and copy the update folder to magento2 root. You will also have to setup updater related cron as specified [here](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html)

**Comment by magenx** [comment]
great , thank you.

**Comment by mazhalai** [comment]
@magenx closing this issue for now. Please feel free to open a new one if you encounter one.

**Comment by ghost** [comment]
For future reference,this is documented here: http://devdocs.magento.com/guides/v2.0/install-gde/install/dev_updater.html

**Comment by giusecapo** [comment]
Same issue here, Magento running on siteground host (installed from cPanel).
If I click on "For additional assistance, see updater application help." I read 
"This topic is obsolete. Magento no longer has a separate updater application.
If you are a contributing developer who installed the Magento application by cloning the GitHub repository, see instead Update the Magento application."
What should I do?

**Comment by giusecapo** [comment]
Someone can help? @mazhalai

**Comment by ships27** [comment]
@giusecapo I'm facing the same issue. Were you able to fix it?

**Comment by sonjaka** [comment]
Any news on this? I am getting the Error that the Updater is unavailable when trying to install an extension via the web setup wizard - but in the docs it is said to be obsolete. How can I fix this?
