### ISSUE TITLE
Unable to create an order from admin, when we enable authorize.net direct post payment method.

### ISSUE THREAD

**Issue by Nagamaiah007** [magento/magento2#25463]
### Preconditions (*)

1. Magento 2.3.3 instance.
2. PHP 7.2 version.
3. Created instance should get browsed in "**https**" mode.

### Steps to reproduce (*)

1. Go To the Magento admin.
3. Navigate to the stores--> configuration--> Sales--> Payment Methods--> expand- Authorize .Net Direct Post(Deprecated)
4. Enable the Payment method
5. Set the payment action as "**Authorize and capture**"
6. Provide valid "**API Login ID**" 
7. Provide valid "**Transaction Key**"
8. Provide Valid "**Signature Key**"
9. New Order Status as "**Processing**"
10. Test mode as "**NO**"
11. Gateway URL as "**https://test.authorize.net/gateway/transact.dll**"
12. Save the configuration
13. Flush the Magento cache management
14. Initially try to create an order from Magento front end
15. After creating an order, the success page should get occur in Magento front end
16. Try to Create an order from Magento admin
17. Navigate to Sales--> Orders
18. click on "**Create New Order**" button
19. select the customer
20. Select the product and click on "**Add selected products to Order**" button
21. the page get loaded, but the product is not added to the cart
22. still try to select the shipping method in the same page
23. submit the order
24.  After this we are Getting a broken page (invalid format) in the Magento admin

### Expected result (*)

1. Order should be get created without any error.
2. Page should not be broken.

### Actual result (*)

1. Selected details are not effecting, while creating order from Magento admin
2. Getting broken page After Submitting.

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25463-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25463-2-3-develop.instances.magento-community.engineering/admin](https://i-25463-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
I'm able to replicate this issue @ https://i-25463-2-3-develop.instances.magento-community.engineering/admin

Please find the video for the same-https://www.screencast.com/t/zt0um67UIL7

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22745` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
@magento give me 2.3-develop instanc

**Comment by sunilit42** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-25463-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25463-2-3-develop.instances.magento-community.engineering/admin](https://i-25463-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
