### ISSUE TITLE
Forward slash (/) in SKU not working REST API

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#25467]
### Preconditions (*)
1. Magento 2.3.3 

### Steps to reproduce (*)
1.  Create a product with a SKU with a forward slash in it (/).
2. Try to retrieve this article through a  "/V1/products/{sku}" request.
3. Its not working because of the slash, but its also not working when using an URL encode, changing the / in %2F.

### Expected result (*)
1. Retrieving the actual product information through the REST API.

### Actual result (*)
1. Not working at all.

I don't know if anything has changed in 2.3.3 according to the above, but we haven't had this problem before. It just came to our attention that since a short while products wont sync to our administration software.

### Solution (*)
Problem can be closed it was a change in our server config which caused this behaviour. We added "AllowEncodedSlashes NoDecode" again to our virtualhost template of Apache and it was solved.

**Comment by jorgb90** [comment]
Problem can be closed it was a change in our server config which caused this behaviour. We added "AllowEncodedSlashes NoDecode" again to our virtualhost template of Apache and it was solved.

**Comment by engcom-Charlie** [comment]
Hello @jorgb90 
So i have to close this issue.

Thank you for contribution and collaboration!
