### ISSUE TITLE
Wishlist total incorrect when containing disabled products

### ISSUE THREAD

**Issue by vseager** [magento/magento2#25462]
### Preconditions (*)

* Magento 2.3.3

If a product is added to a customer's wishlist and is later disabled, the total number of items in the wishlist that is displayed in the wishlist grid toolbar shows the incorrect amount.

### Steps to reproduce (*)
1. Log into customer account on frontend
2. Go to product A and add to wishlist
3. Go to product B and add to wishlist
3. Log into Magento admin and disable product B

### Expected result (*)
1. Only 1 product should show in wishlist
2. Wishlist count in grid toolbar should say "1 Item(s)"

### Actual result (*)
1. 1 item shows in wishlist
2. Wishlist count in grid toolbar says "2 Item(s)"

![screenshot-2019 11 04-15_06_11](https://user-images.githubusercontent.com/2035088/68131497-14362680-ff15-11e9-8065-008ca9898af2.png)

**Comment by torhoehn** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [Magento instance](https://i-25462-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25462-2-3-develop.instances.magento-community.engineering/admin](https://i-25462-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by torhoehn** [comment]
@vseager Thanks for creating this ticket, but I couldn't reproduce this issue on latest 2.3-develop.

Both products enabled:
<img width="1281" alt="Screenshot 2019-11-04 at 22 28 40" src="https://user-images.githubusercontent.com/1945725/68159717-9729a200-ff52-11e9-993d-d081387e24f8.png">

Disabled one of the products:
<img width="1276" alt="Screenshot 2019-11-04 at 22 29 01" src="https://user-images.githubusercontent.com/1945725/68159732-9db81980-ff52-11e9-893d-3f0f1a9846c2.png">

**Comment by rajeshsetblue** [comment]
Wishlist total showing a maximum 3 item count  when I add more than 3 items to my wishlist - magento 2.4.x
![Captursde](https://github.com/user-attachments/assets/f5bb20da-7ecb-4a42-bd60-2a61d1446dc3)
