### ISSUE TITLE
Fotorama preview images distortion

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#25477]
### Preconditions (*)

1. Magento 2.3.3
2. Product images that are wider than they are tall

### Steps to reproduce (*)

1. Add product images that are wider than they are tall to the product page
2.

### Expected result (*)

1. I would expect images to be resized to the containing frame limited by height or width (which ever is greater) and image centered to frame  
2.

### Actual result (*)

1. Screenshot below shows Fotorama main image and preview images, the preview images appear cropped and distorted as they haven't been correctly resized with respect to width.
![USB-RLY82](https://user-images.githubusercontent.com/43850303/68215299-e44f5780-ffd6-11e9-8bb5-bc8e6cd92ff7.png)

2.

**Comment by devchris79** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @devchris79. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @devchris79, here is your [Magento instance](https://i-25477-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25477-2-3-develop.instances.magento-community.engineering/admin](https://i-25477-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
