### ISSUE TITLE
magento 2.3 tier price for product in cart is not refreshing after customer login

### ISSUE THREAD

**Issue by bharanikonda** [magento/magento2#25474]
**Preconditions**

Magento 2.3.1
PHP 7.2

**Steps to reproduce**

Configure a product with two "tier prices". One for "not logged in" customer group and other is for "general" customer group. General is a default customer group which will be applied for all registered customers.

Let's assume the price for "not logged in" customer group is $10 and the price for the "general" customer group is $8.

Add this product to the cart as "not logged in" customer, so the product will be added to the cart for $10, then log in from the checkout page.

**Expected result**

As the customer is logged in (general group) now, the price of the item in cart and checkout should be reduced price to $8. 

**Actual result**
The price of the item in cart and checkout is not refreshing and it still shows $10.

**Comment by krishprakash** [comment]
Hi @bharanikonda. Not able to reproduce the issues as provided steps by you.
Please verify it on latest magento instance https://github.com/magento/magento2/issues/25474#issuecomment-549815041
Thanks
