### ISSUE TITLE
Vertex does not handle configurable product with correlative simple product numeric sku

### ISSUE THREAD

**Issue by kchevalier-mg** [magento/magento2#25470]
### Preconditions (*)
1. Magento 2.3.3
2. MariaDB 10.0.38

### Steps to reproduce (*)
1. Install Magento 2
2. Enable Vertex
3. Create new sub-category
4. Add attribute color to product details attribute group of default attribute-set
5. Add 2 options to color attribute
6. Create product 1 with one of the color option and SKU `211890`
7. Create product 2 with other color option and a random SKU
8. Create configurable product with previous products as its children and SKU `211890c`
9. Go to front-end and go on the category page, select the configurable product, select the option associated with the product 1
10. Click add to cart

### Expected result (*)
1. Product should be successfully added to the cart

### Actual result (*)
1. Error message "We can't add this item to your shopping cart right now."
2. Exception.log message: 

```
[2019-11-04 20:55:52] report.CRITICAL: Notice: Undefined index: 211890C in /vagrant/application2/mage2.vm/vendor/vertex/module-tax/Model/Plugin/CommonTaxCollectorPlugin.php on line 126 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: 211890C in /vagrant/application2/mage2.vm/vendor/vertex/module-tax/Model/Plugin/CommonTaxCollectorPlugin.php on line 126 at /vagrant/application2/mage2.vm/vendor/magento/framework/App/ErrorHandler.php:61)"} []
```

**Comment by kchevalier-mg** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kchevalier-mg. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kchevalier-mg, here is your [Magento instance](https://i-25470-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25470-2-3-develop.instances.magento-community.engineering/admin](https://i-25470-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kchevalier-mg** [comment]
Wrong user. Issue will be reopen with correct user account.
