### ISSUE TITLE
"0 and more" Decimal Filter gets ignored by addFieldToFilter

### ISSUE THREAD

**Issue by stkrelax** [magento/magento2#25475]
### Preconditions (*)
1. create 10 products
2. create decimal attribute volume
3. set volume to 2 on one product
4. make volume filterable

### Steps to reproduce (*)
1. go to product list an filter volume "0 and more"

### Expected result (*)
- only product with the volume set should be shown

### Actual result (*)
- all 10 products are shown

### Reason
Filter -> ?volume=-
volume with filter "-" will be ignored by addFieldToFilter here
https://github.com/magento/magento2/blob/d5104d52fc5e07f88be373ae2bc6a61d4d98c939/app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php#L364
https://github.com/magento/magento2/blob/d5104d52fc5e07f88be373ae2bc6a61d4d98c939/app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection.php#L369

### Connected 
#5291
#2842
MAGETWO-56736

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25475-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25475-2-3-develop.instances.magento-community.engineering/admin](https://i-25475-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @stkrelax thank you for your report. Could you clarify how your attribute was created and how you get filter "0 and more" for your attribute in layered navigation on catalog page?

**Comment by stkrelax** [comment]
hello @engcom-Delta,

we created the attribute ourself with eav setup.
![grafik](https://user-images.githubusercontent.com/48922246/68592551-a4371b80-0493-11ea-9efd-563cc5bec55c.png)

via di we are replacing the decimal LayerFilters

    
    <virtualType name="categoryFilterList" type="Magento\Catalog\Model\Layer\FilterList">
        <arguments>
            <argument name="filters" xsi:type="array">
                <item name="attribute" xsi:type="string">Magento\CatalogSearch\Model\Layer\Filter\Attribute</item>
                <item name="price" xsi:type="string">Magento\CatalogSearch\Model\Layer\Filter\Price</item>
                <item name="decimal" xsi:type="string">OurVendor\OurModule\Model\CatalogSearch\Layer\Filter\Decimal</item>
                <item name="category" xsi:type="string">Magento\CatalogSearch\Model\Layer\Filter\Category</item>
            </argument>
        </arguments>
    </virtualType>
    <virtualType name="searchFilterList" type="Magento\Catalog\Model\Layer\FilterList">
        <arguments>
            <argument name="filters" xsi:type="array">
                <item name="attribute" xsi:type="string">Magento\CatalogSearch\Model\Layer\Filter\Attribute</item>
                <item name="price" xsi:type="string">Magento\CatalogSearch\Model\Layer\Filter\Price</item>
                <item name="decimal" xsi:type="string">OurVendor\OurModule\Model\CatalogSearch\Layer\Filter\Decimal</item>
                <item name="category" xsi:type="string">Magento\CatalogSearch\Model\Layer\Filter\Category</item>
            </argument>
        </arguments>
    </virtualType>

OurVendor\OurModule\Model\CatalogSearch\Layer\Filter\Decimal
just extends from the original \Magento\CatalogSearch\Model\Layer\Filter\Decimal

and changes the visual appearance:
![grafik](https://user-images.githubusercontent.com/48922246/68593049-d7c67580-0494-11ea-9d44-a8ec96eebcc5.png)

so no CoreChanges made.

You are getting the 0 and more Filter only when the volume is just between 0-100 Range
so your volume values should be only in this Range or NULL for ALL Products.

**Comment by stkrelax** [comment]
The ATM dirty Fix is this in the OurVendor\OurModule\Model\CatalogSearch\Layer\Filter\Decimal
![grafik](https://user-images.githubusercontent.com/48922246/68593320-718e2280-0495-11ea-97ae-7271b4d03576.png)
setting $from to 0.00000001 when empty

**Comment by engcom-Charlie** [comment]
Hello @stkrelax 
Could you drop your module? Because we can't reproduce your issue.

**Comment by stkrelax** [comment]
no i actually do not have the time for that. Thank you for the time you invested. 

We will keep the "dirty hack"
