### ISSUE TITLE
Google Shopping Ads "Begin Onboarding" after Enter Google Account not continuing

### ISSUE THREAD

**Issue by Vogel335** [magento/magento2#25482]
### Preconditions (*)

1. Magento Version 2.3.3
2. Magento Api Key is saved in Magento Shop

### Steps to reproduce (*)

1. Go to Marketing -> Google shopping Ads
2. Press Begin Onboarding
3. Enter Google Account
4. Press Begin Onboarding again
5. no more Reaction

### Expected result (*)

1.  Go to next step according to the Magento Documents to create a GMC Account

2.

### Actual result (*)

1. <img width="1216" alt="Bildschirmfoto 2019-11-06 um 00 15 32" src="https://user-images.githubusercontent.com/57420558/68254448-df1bf800-002a-11ea-892c-cc3c5e3e90a6.png">
2. Process is stopped at this point. No error message no log file

**Comment by Vogel335** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @Vogel335. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Vogel335, here is your [Magento instance](https://i-25482-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25482-2-3-develop.instances.magento-community.engineering/admin](https://i-25482-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Vogel335** [comment]
not possible to reproduce in vanilla Magento instance. Google shopping ads entry is missing in the menu

![Bildschirmfoto 2019-11-06 um 11 41 46](https://user-images.githubusercontent.com/57420558/68291658-9ac04480-008a-11ea-8681-d1d389fe84cd.png)

**Comment by sea129** [comment]
Google shopping Ads comes with Magento 2.3.3.
@Vogel335 I think the module loads some external scripts from https://channels.magento.com/asset-manifest.json which conflict with legacy prototype.

**Comment by engcom-Delta** [comment]
Hi @Vogel335 thank you for your report. Seems like your browser blocks popup by default. You should allow it for configure [Google Shopping ads](https://docs.magento.com/m2/ce/user_guide/sales-channels/google-ads/link-accounts.html)

> Helpful tips for onboarding! Turn off pop-up blockers in your web browser. Some browsers may include pop-up blockers by default (like Chrome). You cannot complete onboarding with pop-up blockers enabled.

Closed as non-issue

**Comment by Vogel335** [comment]
Hi pop up blocker is disabled. I think its not a pop up blocker issue.. the window for login to google is appear. Tried Firefory and chrome with disabled pop up blocker both is same result.

**Comment by elfeffe** [comment]
I have the same problem, blank page and error in console
https://github.com/magento/magento2/issues/25506

**Comment by engcom-Echo** [comment]
Hello @Vogel335 @sea129 @elfeffe 

Thank you for contribution and collaboration!

Please, give more information about how are you reproduce it. 
Unfortunately I can not reproduce it.

**Comment by engcom-Echo** [comment]
Hello @Vogel335 @sea129 @elfeffe

Thank you for contribution and collaboration!

Please, give more information about how are you reproduce it.
Unfortunately I can not reproduce it by provided steps.
Thanks!

**Comment by engcom-Echo** [comment]
Hello @Vogel335 @sea129 @elfeffe

Thank you for contribution and collaboration!

Please, give more information about how are you reproduce it.
Unfortunately I can not reproduce it by provided steps. 
Thanks!

**Comment by engcom-Echo** [comment]
Hello @Vogel335 

Thank you for your report and collaboration!
We are not able to reproduce this issue on the 2.3.3 branch by provided steps.

**Testing scenario:**

**Preconditions:**

1. Magento Api Key is saved in Magento Shop 
2. Mozilla FF (70.0.1 (64-bit))

**Steps to reproduce:**

1. Go to Marketing -> Google shopping Ads
2. Press Begin Onboarding
3. Enter Google Account

**Result:**
No need to press Begin Onboarding again. "Welcome to Google Shopping ads Channel in Magento" popup is closed. Google Shopping ads settings is open
![Screenshot from 2019-11-13 14-19-18](https://user-images.githubusercontent.com/51681435/68763635-97483280-0621-11ea-9ddb-8eff9ffa7865.png)

So I close it.
Thanks for your report!

**Comment by elfeffe** [comment]
Well, I do the same, I have the API key installed in Magento, and look what a beautiful console I have in Chrome

![8f484af7974b6d63e30df6a052834a60](https://user-images.githubusercontent.com/4717507/68766156-a1b4fd00-061e-11ea-9ff1-aa433c9fdfd2.png)

**Comment by engcom-Echo** [comment]
Hello @elfeffe 
Seems like this issue is duplicate of [#25506](https://github.com/magento/magento2/issues/25506).
Could we close it as duplicate?

**Comment by Vogel335** [comment]
Hello
yes you can close it as duplicate

**Comment by engcom-Echo** [comment]
Closed as duplicate of  [#25506](https://github.com/magento/magento2/issues/25506).
