### ISSUE TITLE
Missing category image (Magento 2.3.3)

### ISSUE THREAD

**Issue by RomaChernii** [magento/magento2#25489]
### Preconditions (*)

1. PHP 7.2.15
2. Magento 2.3.3 EE

### Steps to reproduce (*)

1. Create a category in the backend
2. In the Content tab of the category, upload a Category Image with the 'Upload' button (let's assume the file is called imagename.jpg)
3. Save the category
4. Save the category again
### Expected result (*)

1. File is uploaded to the directory pub/media/catalog/category with name imagename.jpg
2. The attribute image value in the database in the catalog_category_entity_varchar table is  imagename.jpg after saving the category for the second time

### Actual result (*)

1. The attribute image value in the database in the catalog_category_entity_varchar table is imagename_1.jpg after saving the category for the second time.

**Comment by cscd98** [comment]
https://github.com/magento/magento2/issues/25209

**Comment by krishprakash** [comment]
Hi @RomaChernii.
Issue is duplicate to #25480 , #25099 and #25209
