### ISSUE TITLE
Error installing magento on composer step

### ISSUE THREAD

**Issue by justfeelgood** [magento/magento2#2548]
The files are from magento : https://www.magentocommerce.com/download/
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/framework 100.0.2 requires ext-mcrypt \* -> the requested PHP extension mcrypt is missing from your system.
    - magento/framework 100.0.2 requires ext-mcrypt \* -> the requested PHP extension mcrypt is missing from your system.
    - Installation request for magento/framework 100.0.2 -> satisfiable by magento/framework[100.0.2].

Tried installing mcrypt :
xxx@xxx:/var/www/html$ sudo apt-get install php5-mcrypt 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
php5-mcrypt is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Any hints ?

**Comment by exidoncom** [comment]
having the same problem on osx capitan, trying to install mag2 using composer

**Comment by notmii** [comment]
This thing also happen to me. It seems the installation of **php5-mcrypt** does not automatically enable it on **CLI**.

confirmed this by running **php -m**

To solve it just enable it on CLI by running the ff. command
**/etc/php5/cli/conf.d**$ sudo ln -s ../../mods-available/mcrypt.ini
