### ISSUE TITLE
Magento\Framework\Api\SimpleDataObjectConverter->camelCaseToSnakeCase has no concept of numbers 

### ISSUE THREAD

**Issue by antbates91** [magento/magento2#25490]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create a method for an object that contains a number at the end of the method name for example `getMondayWeek1`. This resolves to a db field `monday_week_1`.
2. Call `Magento\Framework\Api\ExtensibleDataObjectConverter`'s `toNestedArray` function passing in the interface data, and the data model.
3. Check the output of array properties after this method has executed

### Expected result (*)

1. `toNestedArray` should return a nested array with the correct object keys `monday_week_1` 

### Actual result (*)

1. `toNestedArray` returns incorrect object keys `monday_week1`

This appears to be caused by `Magento\Framework\Api\SimpleDataObjectConverter`'s `camelCaseToSnakeCase` method which does `preg_replace` without any numbers in the pattern. `return strtolower(preg_replace('/(.)([A-Z])/', "$1_$2", $name));`

`return strtolower(preg_replace('/(.)([A-Z0-9])/', "$1_$2", $name));` would fix the issue

**Comment by milindsingh** [comment]
I am working on this issue #mm20in

**Comment by milindsingh** [comment]
I am closing this issue as it seems the fix may break things in an unexpected manner.

Earlier:
`defaultShipping1` -> `default_shipping1`
Now:
`defaultShipping1` -> `default_shipping_1`

So, If my column is default_shipping1 then it will not store data now.

The recommended snake case is `default_shipping1` which is already followed by Magento.
