### ISSUE TITLE
Duplicated Row item with Zero price, when order placed from multi-address checkout

### ISSUE THREAD

**Issue by sudheer-gajjala** [magento/magento2#25493]
### Preconditions (*)

1. Magento versions-CE 2.3.2.

### Steps to reproduce (*)

1. Go To Magento admin.
2. create a configurable product with variant child items.
3. Try to create an order from Magento front end using multi-address checkout with the configurable child items
4. The orders created successful.
5. when we verify the Orders in Magento admin, duplicate Order Item is displaying in the Order information page with Original price, price, rowtotal as zero.

### Expected result (*)

1. Duplicate Line item in the Order should not be displayed.

### Actual result (*)

1. Displaying Duplicate Line Item with Zero price. 

![image](https://user-images.githubusercontent.com/51822411/68307704-b1d65500-00d1-11ea-98aa-7ee9f49fd17d.png)

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25493-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25493-2-3-develop.instances.magento-community.engineering/admin](https://i-25493-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
This issue is not replicating- https://i-25493-2-3-develop.instances.magento-community.engineering/admin/admin/

**Comment by kanthy-magento** [comment]
Closing ticket
