### ISSUE TITLE
Change private methods and functions to protected

### ISSUE THREAD

**Issue by matutetandil** [magento/magento2#25498]
This involves any Magento 2 version.

I know that probably there is a desition made based on design to have all variables and methods within core classes to be private. This is great if you don't need to override a class and just adding after or before plugins. But sometimes, when you need to override the hole method (even when you use around) or add some new functionality you may need to use variables and functions of that class, and all are privates, so you must redefine those functions and variables, and that's not a good practice, but is the only way to do it.

Changing the private to protected, will improve this and will make Magento more scalable.

**Comment by engcom-Delta** [comment]
Hi @matutetandil , thank you for your report. 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [community-features](https://github.com/magento/community-features/issues) for general discussion about this issue.

**Comment by fredden** [comment]
This has been re-raised as https://github.com/magento/community-features/issues/216
