### ISSUE TITLE
Product Page doesn't show category in breadcrumb (Magento 2.3.3)

### ISSUE THREAD

**Issue by Vlyav** [magento/magento2#25495]
### Preconditions (*)

1. PHP 7.2.15
2. Magento 2.3.3 EE

### Steps to reproduce (*)

1. Open Product from products list page

### Expected result (*)

1. Product Page show category in breadcrumb

### Actual result (*)

1. Go to products list page - http://joxi.ru/p27RD5ZTK1xXGm
2. Go to product from products list - http://joxi.ru/BA06BpQTMnVkJm
3. Product Page doesn't show category in breadcrumb

**Comment by subbu1993** [comment]
@magento-engcom-team Is there an update on this issue ?

**Comment by jackrevate** [comment]
Still think this is an issue in 2.3.4 - anyone got a fix? starting to annoy me now.
