### ISSUE TITLE
Admin -> Configuration -> Sales -> Tax browsers get frozen

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/magento2#25502]
### Preconditions (*)
Magento 2.3.3 (at least I'm getting the problem with multiple instances 2.3.3, tested with both Firefox 70.0.1 (64-bit)) 

### Steps to reproduce (*)

1. Simply go to admin and open Configuration -> Sales -> Tax.
2. Wait for some seconds, page seems to be finish
3. After a while, you get browser warning which pages slow down the browser and users can't interact with any input
(Varnish is disabled)

### Expected result (*)
Page should work normally

### Actual result (*)
Message appears (See screenshot)
![image](https://user-images.githubusercontent.com/22501570/68370951-3081cf80-0170-11ea-813f-4470872cddbe.png)

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25502-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25502-2-3-develop.instances.magento-community.engineering/admin](https://i-25502-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bradleybrecher** [comment]
I am also experiencing this issue on 2.3.3. This is the 3rd issue I have seen with the tax module.

https://github.com/magento/magento2/issues/25020
https://github.com/magento/magento2/issues/25403

Any update on a fix?

**Comment by onlinebizsoft** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @onlinebizsoft. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @onlinebizsoft, here is your [Magento instance](https://i-25502-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25502-2-3-develop.instances.magento-community.engineering/admin](https://i-25502-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by onlinebizsoft** [comment]
Vertex  seems to be not showing in configuration in latest 2.3-develop. Anyone has any idea?

**Comment by navarr** [comment]
Vertex is a bundled extension that is not part of this repository, and so is not in the 2.3-develop branch.

If you are not using Vertex for tax calculation, I recommend disabling the module for a performance improvement on this screen.  The slowness is caused by a UIComponent heavy user interface for selecting flexible fields.

It is unlikely we'll have a solution in the near future for the performance issues a subset of merchants are experiencing.  Again, my recommendation in this scenario is to disable the vertex module if you are not using it (`bin/magento module:disable Vertex_Tax`)

**Comment by navarr** [comment]
Please find a patch addressing this issue here: https://gist.github.com/navarr/2ec2f22f71a769d8438fb237f58eabd4

**Comment by navarr** [comment]
This issue has been fixed as of Vertex 3.3.0 and will be included with Magento 2.3.4

**Comment by amitbdigitalaptech** [comment]
@navarr 

If we upgrade  Vertex to version `3.3.0` for Magento Open source 2.3.3 Then the issue will resolve or not?

**Comment by navarr** [comment]
@amitbdigitalaptech The issue should resolve, yes.

**Comment by amitbdigitalaptech** [comment]
@navarr 
I don't think, it will work

I have  tried  by adding `"vertex/module-tax": "3.3.0",` at `composer.json`.


**Getting below Error:**

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/product-community-edition 2.3.3 requires vertex/product-magento-module 3.2.0 -> satisfiable by vertex/product-magento-module[3.2.0].
    - magento/product-community-edition 2.3.3 requires vertex/product-magento-module 3.2.0 -> satisfiable by vertex/product-magento-module[3.2.0].
    - vertex/product-magento-module 3.2.0 requires vertex/module-tax 3.2.0 -> satisfiable by vertex/module-tax[3.2.0] but these conflict with your requirements or minimum-stability.
    - vertex/product-magento-module 3.2.0 requires vertex/module-tax 3.2.0 -> satisfiable by vertex/module-tax[3.2.0] but these conflict with your requirements or minimum-stability.
    - Installation request for magento/product-community-edition 2.3.3 -> satisfiable by magento/product-community-edition[2.3.3].
```

**Comment by navarr** [comment]
@amitbdigitalaptech You need to add a replace directive to your composer.json:

```
replace: {
    "vertex/product-magento-module": "*"
}
```

Then, if address validation is desired, you'll have to require that module separately (like tax)

**Comment by amitbdigitalaptech** [comment]
@navarr 
 Thanks  for all  help

Can you please tell me, `VertexSMB_TaxCE` is Magento 1 module for vertax (officially)?

And How can I  avoid tax apply for Some specify customer group at current  M2 vertex module?

**Comment by navarr** [comment]
@amitbdigitalaptech: Customers can have a tax class or a tax code on their account.  Both of these are sent to Vertex and you would create a taxability rule in vertex to avoid tax.
