### ISSUE TITLE
How to win slot 918kiss

### ISSUE THREAD

**Issue by kingzoz88** [magento/magento2#25500]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by sdzhepa** [comment]
Please have a look at our guidelines article before adding a new issue https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
