### ISSUE TITLE
Why does Magento 2 ask an administrator for his password for just switching his backend locale?

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2550]
![](https://mage2.pro/uploads/default/original/1X/ffc12408d65b23a13115c1b0a7a8fffbcd3e2662.png)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by dmitrii-fediuk** [comment]
I think it is definitely a usability issue.
