### ISSUE TITLE
Can't import products after disabling Temando_Shipping 

### ISSUE THREAD

**Issue by gbitdev** [magento/magento2#25518]
### Preconditions
1. Magento 2.3.3 developer modeg

### Steps to reproduce
1. `php bin/magento module:disable Temando_Shipping`
2. `rm -rf ./generated/code/*`
3. `bin/magento cache:flush && bin/magento setup:upgrade && bin/magento setup:di:compile`
4. Try products import. After click on Check Data button recive error 500 from server.

### Expected result
Import products

### Actual result
```
[Thu Nov 07 15:38:32.176418 2019] [php7:error] [pid 167] [client 192.168.32.5:35650] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Temando\\Shipping\\Model\\ResourceModel\\Repository\\PackagingRepositoryInterface in /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50d
Stack trace:d
#0 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Temando\\\\Shippin...')d
#1 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\\Framework\\ObjectManager\\ObjectManager->get('Temando\\\\Shippin...')d
#2 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Temando\\\\Shippin...', NULL, 'packagingReposi...', 'Temando\\\\Shippin...')d
#3 /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolv in /opt/bitnami/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50, referer: http://magento.local/index.php/admin/admin/import/index/key/c79b78087ac2b53d4e053516184b374d9aa54329129d2c4ebba6ab16997df06f/
```

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22962` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmanners** [comment]
I'm guessing that this has the same root problem as https://github.com/magento/magento2/issues/25430

**Comment by sanjay-wagento** [comment]
#MM20IN

**Comment by sdzhepa** [comment]
Magento stops supporting of Temando module. Please see more details https://magento.com/shipping
Long story short: 
- The extension owner does not work and support this module anymore.
- Magento will support "_existing customers until November 15, 2020_" only through the support channel associated with your Magento account. 
- In the internal Magento backlog there is a ticket to completely remove Temando from Magento.
