### ISSUE TITLE
Category with layout 1 column does not load products

### ISSUE THREAD

**Issue by BrentRobert** [magento/magento2#25511]
### Preconditions (*)

1. M2.3.3

### Steps to reproduce (*)

1. Change the layout of a category to 1 column.
2. Flush Cache

### Expected result (*)

1. Category is 1 column
2. Products are loaded

### Actual result (*)

1. Category is 1 column
2. Products don't load anymore

**Comment by BrentRobert** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @BrentRobert. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @BrentRobert, here is your [Magento instance](https://i-25511-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25511-2-3-develop.instances.magento-community.engineering/admin](https://i-25511-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by BrentRobert** [comment]
Can not reproduce at this moment.

**Comment by BrentRobert** [comment]
Duplicate with #24619
