### ISSUE TITLE
Product item rating stars overlaps a hovered item on category page

### ISSUE THREAD

**Issue by tymzap** [magento/magento2#25517]
### Preconditions
1. Magento 2.3.3 with sample data

### Steps to reproduce
1. Go to category with "Hot Sellers" product list set up (preferably **Gear**).
2. Mouse hover on one of the product items, preferably the second to the left.

### Expected result 
1. Content of non-hovered product items doesn't overlap hovered product item.

### Actual result
1. Rating stars of a non-hovered product overlaps the hovered product item.
![image](https://user-images.githubusercontent.com/41994033/68401229-adfe0d80-0179-11ea-9ba8-2e0ce8de9eea.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22949` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Reproduced at local (with Sample data):
![image](https://user-images.githubusercontent.com/46617848/68450206-362ef200-0210-11ea-9896-4672c01f3777.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-25517-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25517-2-3-develop.instances.magento-community.engineering/admin](https://i-25517-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @tymzap. Thank you for your report. 
The issue has been fixed in magento/magento2#25524 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [e891e8184993eda1900763340d3454679e90a326](https://github.com/magento/magento2/commit/e891e8184993eda1900763340d3454679e90a326)

The fix will be available with the upcoming 2.3.5 release.
