### ISSUE TITLE
Warning: Declaration of CommunityEngineering\JapaneseName\Model\DataObject\Copy::setAttributeValueFromExtensibleDataObject($target, $code, $value) should be compatible with Magento\Framework\DataObject\Copy::setAttributeValueFromExtensibleDataObject(Magento\Framework\Api\ExtensibleDataInterface $target, $code, $value) in /data/magento/vendor/community-engineering/module-japanese-name/Model/DataObject/Copy.php on line 0

### ISSUE THREAD

**Issue by waqasamin225** [magento/magento2#25512]

**Comment by waqasamin225** [comment]
i have this issue when i add new product in any category in magento 2.3

**Comment by krishprakash** [comment]
@waqasamin225, Please update all the necessary details as per reporting guild lines below
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by krishprakash** [comment]
@waqasamin225, Feel free to reopen the issue once you update all details as per reporting guidelines.
Thanks.
