### ISSUE TITLE
Image resizing and watermarking do no take into consideration the relative dimensions of the watermark and watermarked image.

### ISSUE THREAD

**Issue by janssentwh** [magento/magento2#25514]
### Introduction
In Magento 2.3.3 it is possible to upload watermarks. By doing so your product images are watermarked indeed. But, when uploading product images of different sizes, the watermark's size is altered relative to the product image. These images below better illustrate my point:
Small base product image:
![image](https://user-images.githubusercontent.com/19301091/68397984-527d5100-0174-11ea-86d0-5886cfd37946.png)

Large base product image:
![image](https://user-images.githubusercontent.com/19301091/68398012-5dd07c80-0174-11ea-81f2-4cee165f5b75.png)

Reproduced in Luma 2.3-develop:
![image](https://user-images.githubusercontent.com/19301091/68399104-25ca3900-0176-11ea-9c3d-c20923d1817a.png)

### Preconditions (*)

The issue is reproducible in Magento 2.3.3

### Steps to reproduce (*)

1. Create two products.
2. Give one product an image of size 400x400.
3. Give the second product an image of size 1200x1200.
4. Add a watermark with width 200px.
5. Refresh image cache.
6. Generate cached images by visiting the product's product detail page.
7. Notice that the watermarks are not of equal size.

### Expected result (*)

1. I expect the watermark to take into consideration the relative size of the image, so that the watermark always is the same width and height regardless of the product image.

### Actual result (*)

1. The smaller product image gets a larger watermark, the larger product image gets a smaller watermark.

**Comment by janssentwh** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @janssentwh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @janssentwh, here is your [Magento instance](https://i-25514-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25514-2-3-develop.instances.magento-community.engineering/admin](https://i-25514-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @janssentwh. Thank you for your report. 
The issue has been fixed in magento/magento2#25528 by @Krielkip in 2.3-develop branch
Related commit(s):
 - [85415eff8ddd81c9b204ec6c093efe49d467ba9e](https://github.com/magento/magento2/commit/85415eff8ddd81c9b204ec6c093efe49d467ba9e)
 - [2263d2e9fe2359b86c26dc91597cf50b5a87def4](https://github.com/magento/magento2/commit/2263d2e9fe2359b86c26dc91597cf50b5a87def4)

The fix will be available with the upcoming 2.3.5 release.
