### ISSUE TITLE
2.3.3 decimals not shown in admin and invoice and credit not possible

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#25521]
### Preconditions (*)

1. Magento 2.3.3
2.

### Steps to reproduce (*)

1. Make product with "Qty Uses Decimals" to yes
2. Order 1.5 of the product

### Expected result (*)

1. In the admin 1.5 is shown
2. On the invoice 1.5 is shown
3. It is possible to credit 0.5 of the qty

### Actual result (*)

In case of order of 0.7 this happens:
![Naamloos](https://user-images.githubusercontent.com/23727130/68416738-5c637c00-0195-11ea-91f8-c92e3350a1a0.jpg)

In case of 1.5 the qty is 1

**Comment by Jilco** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jilco, here is your [Magento instance](https://i-25521-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25521-2-3-3.instances.magento-community.engineering/admin](https://i-25521-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jilco** [comment]
![test1](https://user-images.githubusercontent.com/23727130/68417990-ae0d0600-0197-11ea-9920-89eb3b74141f.jpg)
![05](https://user-images.githubusercontent.com/23727130/68417991-aea59c80-0197-11ea-98ae-8e5262453f28.jpg)
![amount](https://user-images.githubusercontent.com/23727130/68417993-aea59c80-0197-11ea-8717-a0db669735de.jpg)

**Comment by Jilco** [comment]
reproduced with 1.5 (ordered 1 in admin) and 0.5 (invoice not possible and credit) amount

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22956` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Jilco** [comment]
@krishprakash any idea in wich files the problem is? I asume that there is a float instead of a double somewere

**Comment by sdzhepa** [comment]
It seems could be the same https://github.com/magento/magento2/issues/25367

**Comment by sdzhepa** [comment]
Closed as fixed in https://github.com/magento/magento2/pull/23943
