### ISSUE TITLE
Bulk Action - Finished with Failure

### ISSUE THREAD

**Issue by agallart** [magento/magento2#25526]
**### Preconditions**

1.magento 2.3.3 developer mode

**### Steps to reproduce**

1.   POST  with postman https://www.test.com/rest/all/async/bulk/V1/products

```
[
  {
    "product": {
      "Sku": "sku11",
      "Name": "skuV111",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku21",
      "Name": "skuV222",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku31",
      "Name": "skuV311",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku41",
      "Name": "skuV411",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku51",
      "Name": "skuV511",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  }
]
```
**### Expected result**

Full import products

**### Actual result**
If i try less than 3 products it works..

![image](https://user-images.githubusercontent.com/16067982/68465686-38df1680-0213-11ea-81ca-469970e4b497.png)

![image](https://user-images.githubusercontent.com/16067982/68465695-3ed4f780-0213-11ea-8ff5-3b09fffc3a22.png)

Why I can't import the products?

**Comment by agallart** [comment]
@magento give me 2.3-develop instance(2.3.3)

**Comment by magento-engcom-team** [comment]
Hi @agallart. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @agallart, here is your [Magento instance](https://i-25526-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25526-2-3-develop.instances.magento-community.engineering/admin](https://i-25526-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by agallart** [comment]
How I can configure bulk with this Magento instance?

**Comment by taihuuho** [comment]
I am running into this issue as well. It's very intermittent. Wondering if there is way to retry the failed items

**Comment by agallart** [comment]
I execute the same posted json array 5 elements:
![image](https://user-images.githubusercontent.com/16067982/68574049-5ad1d680-0469-11ea-8541-d7e1c62589cb.png)

errors:
![image](https://user-images.githubusercontent.com/16067982/68574074-62917b00-0469-11ea-8757-1c5499124e61.png)

then I send elements with error:
![image](https://user-images.githubusercontent.com/16067982/68574148-8fde2900-0469-11ea-9d0a-783f48da77de.png)

I try with 20 elements:
`[
  {
    "product": {
      "Sku": "sku1",
      "Name": "skuV1",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku2",
      "Name": "skuV2",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku3",
      "Name": "skuV3",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku4",
      "Name": "skuV4",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku5",
      "Name": "skuV5",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
   {
    "product": {
      "Sku": "sku6",
      "Name": "skuV6",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku7",
      "Name": "skuV7",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku8",
      "Name": "skuV8",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku9",
      "Name": "skuV9",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku10",
      "Name": "skuV10",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
   {
    "product": {
      "Sku": "sku11",
      "Name": "skuV11",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku12",
      "Name": "skuV12",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku13",
      "Name": "skuV13",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku14",
      "Name": "skuV14",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku15",
      "Name": "skuV15",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
   {
    "product": {
      "Sku": "sku16",
      "Name": "skuV16",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku17",
      "Name": "skuV17",
      "attribute_set_id":4,
      "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku18",
      "Name": "skuV18",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku19",
      "Name": "skuV19",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  },
  {
    "product": {
      "Sku": "sku20",
      "Name": "skuV20",
       "attribute_set_id":4,
       "type_id":"simple",
      "Price": 4
    }
  }
]`

![image](https://user-images.githubusercontent.com/16067982/68574549-6f629e80-046a-11ea-8b38-9e1f56861575.png)

first try error:
![image](https://user-images.githubusercontent.com/16067982/68574572-7be6f700-046a-11ea-8a10-3d574835ad96.png)

try elements with error:



error:
![image](https://user-images.githubusercontent.com/16067982/68574759-e730c900-046a-11ea-92d1-6f9146c00d58.png)

![image](https://user-images.githubusercontent.com/16067982/68574781-f31c8b00-046a-11ea-9f19-9ee6c5681d0c.png)

but I think the problem is the size of array becouse if I send less then 4 elements it works ever.

**Comment by taihuuho** [comment]
Agreed. I was trying to import 100 products and got the same error. I guess it's something with the `cataloginventory_stock_item` being locked somehow, kind of race condition. In my cases, it's intermittently happening.

Also, most of the time, all of the single products imported successfully but when it comes to the configurable, I was always getting this error
```
The product that was requested doesn't exist. Verify the product and try again.
```
<img width="1348" alt="Screen Shot 2019-11-11 at 8 17 51 AM" src="https://user-images.githubusercontent.com/12061272/68593760-cad96000-045b-11ea-9ad0-4bce652ef17a.png">

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25526-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25526-2-3-develop.instances.magento-community.engineering/admin](https://i-25526-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
I was working with performance test using bulk and it was 100% successful even with 1000 simple products inside
@taihuuho could you please provide an example body of failed configurable product?

**Comment by AnnaShepa** [comment]
I tried with configurable products - 100% success as well
Once I've got the same error "The product was unable to be saved. Please try again.", but it was because of wrong product body in request. So, please try to send your failed items via sync request rest/V1/products - probably you will get the same error

**Comment by taihuuho** [comment]
Sorry, I will send over the request payload soon. I am pretty sure that it's working fine via sync requests, as the sync request doesn't fit my requirements, that's when I looked into Bulk API.
Also, you guys need to explicitly state what the requirements and the recommended configurations for RabbitMQ server. 
RabbitMQ was closing the connection somehow or something else was happening, but the consumer was crashing saying that `Broken pipe` error.

**Comment by taihuuho** [comment]
@AnnaShepa I would re-open the issue when I send over the request body

**Comment by taihuuho** [comment]
@AnnaShepa so you can find the whole payload attached
[payload.txt](https://github.com/magento/magento2/files/3878036/payload.txt)

Pretty interesting that now I am getting another error
<img width="1334" alt="Screen Shot 2019-11-21 at 11 09 52 PM" src="https://user-images.githubusercontent.com/12061272/69399521-0ffb5e80-0cb4-11ea-92f8-3d3d5337e17a.png">

Here is the meta info for that configurable product only
```
{"product":{"sku":"11539032-T-SHIRT","name":"1st grade here i come t shirt","attribute_set_id":9,"price":0,"status":1,"visibility":4,"type_id":"configurable","weight":0.5,"extension_attributes":{"category_links":[{"position":0,"category_id":"3"}],"configurable_product_options":[{"attribute_id":"93","label":"Color","position":0,"is_use_default":false,"values":[{"value_index":14},{"value_index":43},{"value_index":47},{"value_index":23},{"value_index":21},{"value_index":32},{"value_index":17},{"value_index":50},{"value_index":49},{"value_index":54},{"value_index":35}]},{"attribute_id":"138","label":"Size","position":1,"is_use_default":false,"values":[{"value_index":4},{"value_index":5},{"value_index":6},{"value_index":7},{"value_index":8},{"value_index":9},{"value_index":10},{"value_index":11}]}]},"product_links":[],"media_gallery_entries":[{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-black-11539032-5dae6732dc23f5c3b7986394.png","position":0,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-black-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-black-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-navy-11539032-5dae6732dc23f5c3b7986394.png","position":1,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-navy-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-navy-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-purple-11539032-5dae6732dc23f5c3b7986394.png","position":2,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-purple-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-purple-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-forest-green-11539032-5dae6732dc23f5c3b7986394.png","position":3,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-forest-green-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-forest-green-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-dark-heather-11539032-5dae6732dc23f5c3b7986394.png","position":4,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-dark-heather-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-dark-heather-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-irish-green-11539032-5dae6732dc23f5c3b7986394.png","position":5,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-irish-green-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-irish-green-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-charcoal-11539032-5dae6732dc23f5c3b7986394.png","position":6,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-charcoal-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-charcoal-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-royal-11539032-5dae6732dc23f5c3b7986394.png","position":7,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-royal-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-royal-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-red-11539032-5dae6732dc23f5c3b7986394.png","position":8,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-red-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-red-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-sky-11539032-5dae6732dc23f5c3b7986394.png","position":9,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-sky-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-sky-11539032-5dae6732dc23f5c3b7986394.png"}},{"media_type":"image","label":"1st-grade-here-i-come-t-shirt-kiwi-11539032-5dae6732dc23f5c3b7986394.png","position":10,"disabled":false,"types":["image","small_image","thumbnail"],"file":"1st-grade-here-i-come-t-shirt-kiwi-11539032-5dae6732dc23f5c3b7986394.png","content":{"base64_encoded_data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMM+MD2HwAFJQJHtvF3uQAAAABJRU5ErkJggg==","type":"image\/png","name":"1st-grade-here-i-come-t-shirt-kiwi-11539032-5dae6732dc23f5c3b7986394.png"}}],"tier_prices":[],"custom_attributes":[{"attribute_code":"description","value":"<div class=\"panel entry-content active\" id=\"tab-description\">\n<p>Best\u00c2\u00a0<a><strong>1st Grade Here I Come T-Shirt<\/strong><\/a>\u00c2\u00a0today.ALL PRODUCTS ARE PRINTED ON DEMAND, NOT GENUINE, MADE AND SHIP FROM USA.- Pre-shrunk 100% cotton \u00e2\u20ac\u201c Double-needle stitched neckline, bottom hem and sleeves \u00e2\u20ac\u201c Seven-eighths inch seamless collar \u00e2\u20ac\u201c Shoulder-to-shoulder taping \u00e2\u20ac\u201c Tearaway label \u00e2\u20ac\u201c Made in the USA. \u00e2\u20ac\u201c 100% satisfaction guaranteed! Not happy? Shoot us a message and we will do just about anything to change that! SHARE it with your friends, order together and save on shipping. You aslo can Best\u00c2\u00a0<strong><a href=\"\/products\/makes-me-wanna-hot-dog-real-bad-t-shirt\/\" title=\"Makes Me Wanna Hot Dog Real Bad T-Shirt\"><strong>Makes Me Wanna Hot Dog Real Bad T-Shirt<\/strong><\/a>. <\/strong>\u00c2\u00a0on my store.<br\/>-TIP: SHARE it with your friends, buy 2 shirts or more and you will save on shipping\u00c2\u00a0<br\/>-100% Printed In The USA \u00e2\u20ac\u201c Ship Worldwide!<br\/>-Guaranteed safe and secure checkout via:<br\/>-Paypal | VISA | MASTERCARD | DISCOVER | AMEX<\/p>\n<p><strong>1st Grade Here I Come T-Shirt<\/strong>\u00c2\u00a0detail item:<br\/>You find all the answers you need and more here!<br\/>See More Products ==&gt; <a href=\"\/products\/makes-me-wanna-hot-dog-real-bad-t-shirt\/\" title=\"Makes Me Wanna Hot Dog Real Bad T-Shirt\"><strong>Makes Me Wanna Hot Dog Real Bad T-Shirt<\/strong><\/a>. <\/p>\n<p><\/p>\n<ul>\n<li>5.3-ounce, 100% cotton<\/li>\n<li>Double-needle neck, sleeves <g class=\"gr_ gr_8 gr-alert gr_gramm gr_inline_cards gr_run_anim Punctuation only-ins replaceWithoutSep\" data-gr-id=\"8\" id=\"8\">and<\/g> hem; Roomy Unisex Fit<\/li>\n<li>Decoration type: Digital Print<\/li>\n<li>Made by Gildan<\/li>\n<\/ul>\n<p><\/p>\n<div id=\"gealistvariantscolor\" style=\"display:none\">Black-151514|Navy-0f142a|Purple-4c3873|Forest Green-10271b|Dark Heather-4d4d52|Irish Green-009b57|Charcoal-36454f|Royal-1d62a7|Red-d51a2a|Sky-71BDD7|Kiwi-93aa6a<\/div>\n<p><select class=\"form-control\" id=\"gearment_selectstyle\" onchange=\"location = this.options[this.selectedIndex].value;\"><option selected=\"selected\" value=\"\/products\/1st-grade-here-i-come-t-shirt\/\">T-Shirt<\/option><option value=\"\/products\/1st-grade-here-i-come-hoodie\/\">Hoodie<\/option><option value=\"\/products\/1st-grade-here-i-come-sweatshirt\/\">Sweatshirt<\/option><option value=\"\/products\/1st-grade-here-i-come-premium-mens-t-shirt\/\">Premium Men\u00e2\u20ac\u2122s T-Shirt<\/option><option value=\"\/products\/1st-grade-here-i-come-racerback-tank\/\">Racerback Tank<\/option><option value=\"\/products\/1st-grade-here-i-come-long-sleeve-t-shirt\/\">Long Sleeve T-Shirt<\/option><option value=\"\/products\/1st-grade-here-i-come-tank-top\/\">Tank Top<\/option><\/select><\/p>\n<\/div>"},{"attribute_code":"tax_class_id","value":0},{"attribute_code":"color","value":null}]},"saveOptions":false}
```

Would you mind re-opening this issue and taking a look?

Thanks

**Comment by agallart** [comment]
@AnnaShepa  can you post some example for bulk insert products to try with my envoirment ?

individually the products can insert with bulk ..I think this is not problem of format.

thnks

**Comment by AnnaShepa** [comment]
@tiagobnu I managed to create items using your request with only one change: I have only default attiribute_set_id, so I changed it from 9 to 4. According to the error from your screenshot you have to check that on your server you have listed ids: attribute_id 93 and 138 and value_index for those attributes.
I run as well a few bulk requests with 100 products like this and all were succeed. So @agallart  you can try as well use the product from @taihuuho comment or just simple example:
`[
{
            "product": {
                "sku": "conf3",
                "name": "conf3",
                "attribute_set_id": 4,
                "price": 100,
                "status": 1,
                "visibility": 4,
                "type_id": "configurable",
                "extension_attributes": {
                    "stock_item": {
                        "manage_stock": 1,
                        "is_in_stock": 1,
                        "qty": 10
                    },
                    "configurable_product_options": [
                        {
                            "attributeId": 93,
                            "position": 0,
                            "isUseDefault": "true",
                            "label": "Color",
                            "values": [
                                {
                                    "valueIndex": 60
                                },
                                {
                                    "valueIndex": 59
                                }
                            ]
                        }
                    ]
                }
            }
},
{
            "product": {
                "sku": "conf4",
                "name": "conf4",
                "attribute_set_id": 4,
                "price": 100,
                "status": 1,
                "visibility": 4,
                "type_id": "configurable",
                "extension_attributes": {
                    "stock_item": {
                        "manage_stock": 1,
                        "is_in_stock": 1,
                        "qty": 10
                    },
                    "configurable_product_options": [
                        {
                            "attributeId": 93,
                            "position": 0,
                            "isUseDefault": "true",
                            "label": "Color",
                            "values": [
                                {
                                    "valueIndex": 60
                                },
                                {
                                    "valueIndex": 59
                                }
                            ]
                        }
                    ]
                }
            }
}
]`

**Comment by taihuuho** [comment]
@AnnaShepa can you not the product description when importing?

Pretty interesting that I tried to import 100 products with consist of around 10,000 records in DB. I can see that 15 configurable products were created. And the 85 others were failed to import.

My best guess is because the description field contains some HTML tags?

I don’t know
