### ISSUE TITLE
Product assigned to grouped product does not show as grouped unless in stock

### ISSUE THREAD

**Issue by nyov** [magento/magento2#2552]
A product assigned to a 'Grouped Product' does not show up on the grouped product, unless it is in stock. It says `There are no grouped products.` which is wrong (The referenced product shows up again once it has a quantity/is in stock).

Aside: A 'Simple Product' shows up as a 'Virtual Product' in the product overview list. I don't know if that is an issue in itself, but it's slightly confusing.

**Comment by katmoon** [comment]
@nyov 

Thank you for reporting the issue, and sorry for the delay.
I have created internal ticket `MAGETWO-50416` to fix the issue suggesting to update the confusing message.

Thanks,
Kateryna.

**Comment by nyov** [comment]
Not a problem. Thanks.

**Comment by bh-ref** [comment]
There is an additional, important issue with this: if the child product is set to "out of stock" and you edit and save the grouped product (the parent), the relation will be deleted.

**Comment by ktruehl** [comment]
The problem lies in the `Magento\Catalog\Model\Product\Link` class in the `getProductCollection()` method. Here the in stock filter is always added to the product collection regardless of whether we are in the frontend or backend.

A patch/hack/woraround is to replace the line

```
        $this->stockHelper->addInStockFilterToCollection($collection);
```

with the following

```
        if ($this->_appState->getAreaCode() != \Magento\Backend\App\Area\FrontNameResolver::AREA_CODE)
            $this->stockHelper->addInStockFilterToCollection($collection);
```

**Comment by bh-ref** [comment]
As far as I can see it's fixed in Magento 2.1, correct?

**Comment by magento-engcom-team** [comment]
@nyov, thank you for your report.
We've created internal ticket(s) MAGETWO-50416 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@nyov, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
