### ISSUE TITLE
system import/export from magento commandline?

### ISSUE THREAD

**Issue by nyov** [magento/magento2#2553]
Is it possible to do the equivalent of the `System->Import` and `System->Export` screens from the 'magento cli' commandline?

Having at least the Importers available from the commandline would be a very big boon (without going through the requests-heavy rest or soap api).

**Comment by hgpit** [comment]
Seconded. This would be brilliant to have.

**Comment by pboisvert** [comment]
@tanya-soroka Tanya--are you the right owner for this until the item moves from backlog to development?

**Comment by tanya-soroka** [comment]
@pboisvert Looks like we have some other similar request "configuration via CLI  #3238."

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/system-import-export-from-magento-commandline/idi-p/44859).
