### ISSUE TITLE
glyphicon are not displaying in magento admin panel and frontend

### ISSUE THREAD

**Issue by vini1996** [magento/magento2#25539]
### Preconditions (*)

1.magento 2.3.3
2.php 7.3.10

### Steps to reproduce (*)

1. just go to the admin panel dashboard.
2. front end product details

### Expected result (*)

1. It should display the glyphicons in frontend and admin panel
2.
### Actual result (*)

1. It is not displaying glyphicons
![github1](https://user-images.githubusercontent.com/39683802/68527311-7c1cb080-030b-11ea-8b40-e4301858f9b9.JPG)
![github2](https://user-images.githubusercontent.com/39683802/68527312-7cb54700-030b-11ea-9acb-353b974fbe0f.JPG)

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-25539-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25539-2-3-develop.instances.magento-community.engineering/admin](https://i-25539-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
@vini1996 Currency symbol configuring at Stores->Currency->Currency Symbols and don't use glyphicon by default. Please check store configuration for first. O'm closing this issue. Please feel free to reopen if you will have more details about your situation
