### ISSUE TITLE
MAGENTO 2.3 Will not update ALL SELECTED from disabled to enabled

### ISSUE THREAD

**Issue by whyDidIMigrate** [magento/magento2#25532]
### Preconditions (*)

1. Magento version  2.3.1
2. Chrome

### Steps to reproduce (*)

1. Watch Video https://youtu.be/ab_Ug8gmMLc
2.

### Expected result (*)

1. ALL SELECTED product listings to be updated from disabled to enabled

### Actual result (*)

1. Only 20 products listings updated (1 page of 20 selected listings)

**Comment by Den4ik** [comment]
@whyDidIMigrate Issue not reproduced on fresh 2.3-develop instance. Please check customizations on your site.

**Comment by Den4ik** [comment]
![9p30o_2019-11-09_22-18-40](https://user-images.githubusercontent.com/1129623/68533865-f3b80300-033e-11ea-963c-5c74c73c9e26.jpg)
