### ISSUE TITLE
Magento ver. 2.3.3 Reindex issue

### ISSUE THREAD

**Issue by yiingfeiii** [magento/magento2#25535]
How Do I solve the problem of the reindex issue? I am using cpanel v. 73 but I cant find my terminal. Reindex issue will take how long if leave it untouch?

**Comment by andrewbess** [comment]
@yiingfeiii I think you should ask this question your hosting provider, but not Magento team.
In addition, you can find third-party modules that add reindex actions to admin panel.
@magento-engcom-team I think this task can be closed.

**Comment by sudheers-kensium** [comment]
@yiingfeiii This is not Magento issue, so I am closing this issue.
