### ISSUE TITLE
Apply Discount Code Not Working

### ISSUE THREAD

**Issue by TBFdirect** [magento/magento2#25536]
Voucher codes have stopped working since upgrading to 2.3.2 and also 2.3.3

This is how i have setup the voucher code:
![screenshot-www tbfdirect co uk-2019 11 08-22_13_31](https://user-images.githubusercontent.com/32652249/68514262-1c73c600-0275-11ea-9872-674a48b14ca0.png)

When i enter the code in the cart i get the error:
![screenshot-www tbfdirect co uk-2019 11 08-22_21_17](https://user-images.githubusercontent.com/32652249/68514616-2944e980-0276-11ea-9b70-b9f534a5070e.png)

I copied various tutorials online to setup a voucher and i'm sure i haven't missed anything. Is it a bug?

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25536-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25536-2-3-develop.instances.magento-community.engineering/admin](https://i-25536-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
Hi @TBFdirect unfortunately I cannot reproduce the error, so coupon code applied correct. Please try yourself on clean magento latest version, as well as please check payment method settings and probably   look into devtools if you have any errors there.
