### ISSUE TITLE
Getting issue while installing sample data with command line.

### ISSUE THREAD

**Issue by amanuni** [magento/magento2#2554]
Hi,

I have installed magento 2 on nginx server and tried to install sample data with below mentioned command from magento root directory.

php bin/magento sampledata:deploy

and i am getting below mentioned error.

[ErrorException]
  Argument 1 passed to Symfony\Component\Console\Input\ArrayInput::__construc
  t() must be of the type array, object given, called in /var/www/html/vendor
  /magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and
   defined

![image](https://cloud.githubusercontent.com/assets/2352740/11456325/1a691e8e-96ac-11e5-9104-361db7719e5a.png)

uploaded screen shot.

Thanks

**Comment by akamyself** [comment]
have you tried to run 'composer update' after sample data installation?

**Comment by DavidLambauer** [comment]
You have to run composer update. After installiing sample data you have to upgrade the db via cli command system:upgrade

**Comment by amanuni** [comment]
I have have updated system with client after i run this step

**Comment by amanuni** [comment]
Problem is when i trying to install sample data i am getting the above error.

**Comment by mazhalai** [comment]
@amanuni can you please try the command again with `-vvv` option, which will show more stack trace and help identify the problem.

**Comment by amanuni** [comment]
Hi,

I have uninstalled the previous version and downloaded the new version with sample data and again installed that, its installed now however i have got lots of problem while installing i am using low configuration server so most of the time mysql restarted and using nginx i have tried nginx.conf.sample configuration for my virtual host magento is working fine but i need to use phpmyadmin also i have created phpmyadmin symlink in pub folder and when i am going to access it index.php is downloading seems i have tried very much but not overcome with this problem. It would be great if you can suggest some solution for this.

**Comment by davidalger** [comment]
@amanuni My suggestion to resolve the issues with your hosting setup, which appear to be unrelated to Magento 2, would be to head over to one of the Stack Exchange forums and ask there. This tracker is intended to handle technical issues / bugs with the core platform. As the initial issue reported is no longer a problem, I'm going to go ahead and close this. Please re-open if you feel there is a bug with Magento 2.
