### ISSUE TITLE
X-Magento-Vary and Varnish Cache

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#25543]
### Preconditions (*)

1. Magento 2.3.3
2. Varnish 6 - with Magento VCL

### Steps to reproduce (*)

1. Visit website 
2. Log in to account
3. Browse website categories and products whilst logged in

### Expected result (*)

1. Varnish cache hits for customer logged in browsing website product and category pages

### Actual result (*)

1. X-Magento-Vary cookie added to requests 
2. Browsing category and product pages whilst customer logged into website results in Varnish cache miss

The website content is the same throughout category and product pages for logged-in customer yet X-Magento-Vary cookie is added rendering the benefits from Varnish cache useless for logged in customers.

**Comment by nadroj467** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nadroj467, here is your [Magento instance](https://i-25543-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25543-2-3-3.instances.magento-community.engineering/admin](https://i-25543-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mattijv** [comment]
This is intented behaviour. Varnish caches content separately for different customer groups, which includes guests and logged in customers.

If you don't need a separate cache for those two groups, you can always modify the behaviour of the `Magento\Framework\App\Http\Context` class so that the two groups get same cache identifier.
