### ISSUE TITLE
Version 2.3.3 : URL Suffix Category/Product

### ISSUE THREAD

**Issue by loibv5989** [magento/magento2#25549]
### Preconditions (*)

1. version 2.3.3
2. php7.2 , server nginx, mysql percona 5.7

### Steps to reproduce (*)

1. Go to Configuration->Catalog ->Search Engine Optimization (Product URL Suffix/Category URL Suffix->Set  /)
2. 
![image](https://user-images.githubusercontent.com/30828860/68565317-b742ef00-0485-11ea-8c43-10141cfe6968.png)

Command : php bin/magento indexer:reindex, clean:cache
Example Url : http://domain.com/shop/?color=5431

![image](https://user-images.githubusercontent.com/30828860/68565451-228cc100-0486-11ea-96a5-de5cdb46ca88.png)

Filter click color MANUFACTURER/PRICE/COlOR or any attribute => Not working
Layer Navigation: Do not have any changes or redirects to the attribute link filter.
It only encountered an error on 2.3.3, versions <2.3.2 did not encounter an error.

### Expected result (*)

1. It will be redirect to the feature/filter url attribute

### Actual result (*)

1. Any solution for this?

**Comment by andrewbess** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @andrewbess. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, here is your [Magento instance](https://i-25549-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25549-2-3-develop.instances.magento-community.engineering/admin](https://i-25549-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by loibv5989** [comment]
Exactly it will bug on version 2.3.3.
I have test it on branch 2.3 develop but it is fine.
It only bug on version 2.3.3

![image](https://user-images.githubusercontent.com/30828860/68600116-7de5a000-04d4-11ea-964f-732e4ebc4826.png)
![image](https://user-images.githubusercontent.com/30828860/68600227-b1c0c580-04d4-11ea-92dd-5e98605d21a4.png)

Video :
[simplescreenrecorder-2019-11-11_22.48.36.mkv.zip](https://github.com/magento/magento2/files/3832071/simplescreenrecorder-2019-11-11_22.48.36.mkv.zip)

**Comment by engcom-Charlie** [comment]
Hello @Denda69 
I have to close this issue because it is not reproducible on a fresh Magento 2.3-develop(2.3.3 code is merged). 

Thanks for your report!

**Comment by loibv5989** [comment]
Magento\UrlRewrite\Controller\Router class line 80 ?
2.3.2 to 2.3.3 : $request->getPathInfo() change to $this->getNormalizedPathInfo($request) .

###
    /**
     * Get normalized request path
     *
     * @param RequestInterface|HttpRequest $request
     * @return string
     */
    private function getNormalizedPathInfo(RequestInterface $request): string
    {
        $path = $request->getPathInfo();
        /**
         * If request contains query params then we need to trim a slash in end of the path.
         * For example:
         * the original request is: http://my-host.com/category-url-key.html/?color=black
         * where the original path is: category-url-key.html/
         * and the result path will be: category-url-key.html
         *
         * It need to except a redirect like this:
         * http://my-host.com/category-url-key.html/?color=black => http://my-host.com/category-url-key.html
         */
        if (!empty($path) && $request->getQuery()->count()) {
            $path = rtrim($path, '/');
        }

        return (string)$path;
    }

I'm temporarily not using rtrim($path = rtrim($path, '/');) to make it work for me, nonetheless looking forward to a better update

**Comment by Denda69** [comment]
/**
     * Match corresponding URL Rewrite and modify request.
     *
     * @param RequestInterface|HttpRequest $request
     * @return ActionInterface|null
     */
    public function match(RequestInterface $request)
    {
        $rewrite = $this->getRewrite(
            $this->getNormalizedPathInfo($request),
            $this->storeManager->getStore()->getId()
        );

        if ($rewrite === null) {
            //No rewrite rule matching current URl found, continuing with
            //processing of this URL.
            return null;
        }
        if ($rewrite->getRedirectType()) {
            //Rule requires the request to be redirected to another URL
            //and cannot be processed further.
            return $this->processRedirect($request, $rewrite);
        }
        //Rule provides actual URL that can be processed by a controller.
        $request->setAlias(
            UrlInterface::REWRITE_REQUEST_PATH_ALIAS,
            $rewrite->getRequestPath()
        );
        $request->setPathInfo('/' . $rewrite->getTargetPath());
        return $this->actionFactory->create(
            \Magento\Framework\App\Action\Forward::class
        );
    }
