### ISSUE TITLE
After v.2.3.3 updated: pagination, filtering, sorting on catalog page doesn't work

### ISSUE THREAD

**Issue by amiddio** [magento/magento2#25557]
### Preconditions (*)

1. M2.3.3.
2. PHP Version 7.1.22
3. Chrome, Firefox

### Steps to reproduce (*)

1. Go to catalog page
2. Click on pagination link (p2, p3 etc), or change product list mode, or change price rang, or change number of products display
3.
![Screenshot_1](https://user-images.githubusercontent.com/2463233/68595604-3995d800-04b3-11ea-91de-29f44bd77f18.png)

### Expected result (*)
1. 
![Screenshot_2](https://user-images.githubusercontent.com/2463233/68595820-a7da9a80-04b3-11ea-9ce4-d2ae457516ce.png)

### Actual result (*)

1. Pagination, filtering, sorting on catalog page doesn't work

---
I've deleted all extensions from app/code, and theme from design/frontend. Ran "php bin/magento setup:upgrade". The issue is still exist.

It worked correct on M2.3.2. The issue appears just after update to 2.3.3.
Any solution for this?

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25557-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25557-2-3-develop.instances.magento-community.engineering/admin](https://i-25557-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25557-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25557-2-3-3.instances.magento-community.engineering/admin](https://i-25557-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @amiddio 
I am not able to reproduce this issue as per your provided steps. Let me know here if you are still able to reproduce this issue or update the steps to reproduce this issue .

**Comment by Thomas-gt3** [comment]
I had the same problem, the Doofinder module was the cause.

**Comment by amiddio** [comment]
Thank you @Thomas-gt3 for your answer. I don't use extension Doofinder.

---
I've got "301 Moved Permanently" on all catalog pages:
/cables/network-cables./?product_list_mode=list
/cables/network-cables./?product_list_dir=desc
/cables/network-cables./?product_list_order=name
/cables/network-cables./?p=2
...
So, Magento doesn't manage all GET variables on catalog pages. How I see...

But, it works correct on search result page:
/catalogsearch/result/?q=cable
/catalogsearch/result/index/?q=cable&product_list_mode=list
/catalogsearch/result/index/?product_list_mode=list&q=cable&product_list_dir=asc
/catalogsearch/result/index/?p=2&product_list_dir=asc&product_list_mode=list&q=cable
...

I understand it's issue on my project (not M2.3.3), but what is the reason? How can I fix it?

**Comment by amiddio** [comment]
I found the reason of issue. It was suffix "./" of categories and products ("Admin > Configuration > Catalog > Catalog > Search Engine Optimization"). Deleted them and regenerated Url Rewrites (used https://github.com/karliuka/m2.IndexerUrlRewrite) and the issue gone.
