### ISSUE TITLE
FPT is not applied to configurable products

### ISSUE THREAD

**Issue by PaulEmich** [magento/magento2#25554]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Fresh Magento 2.3.3
2. Add FPT attribute
3. Configure FPT
4. Create a configurable product with a simple product (Price of 10$)
5. Set FPT attribute on simple product (Price of 0.15$)

### Expected result (*)
1. I expect the configurable product to show a price of 10.15$

### Actual result (*)
1. The configurable shows a price of 10$, the simple option shows a price of +0.15$

**Comment by PaulEmich** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pauluse. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pauluse, here is your [Magento instance](https://i-25554-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25554-2-3-develop.instances.magento-community.engineering/admin](https://i-25554-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by PaulEmich** [comment]
I was able to reproduce the issue on a vanilla Magento instance;

![image](https://user-images.githubusercontent.com/1635879/68590896-dcd4f600-048f-11ea-8db6-8b184f2546a3.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22990` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@pauluse this issue looks like  a Duplicate of https://github.com/magento/magento2/issues/28931

can you confirm or I missed something?

**Comment by sdzhepa** [comment]
Closed as Duplicate of #28931
