### ISSUE TITLE
[2.3.3] Bulk enablig products does not invalidate indexes

### ISSUE THREAD

**Issue by gioamato** [magento/magento2#25561]
### Preconditions (*)

1. Vanilla Magento 2.3.3 & 2.3-develop
2. Composer installation
3. PHP 7.3
4. Cron configured and working
5. Index Update by Schedule

### Steps to reproduce (*)

1. Select some disabled products
2. Select Action > Change Status
3. Select Enable

### Expected result (*)

1. Products' indexes invalidated (NOT 'ready')
2. Reindex Job added to cron schedule
3. Reindex during the next cron execution
4. Products showing on the frontend

### Actual result (*)

1. Products' indexes NOT invalidated (Staus 'ready')
2. Reindex not scheduled and not executed
3. Products not showing on the frontend until manual `bin/magento indexer:reindex`

**Comment by gioamato** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @gioamato. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @gioamato, here is your [Magento instance](https://i-25561-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25561-2-3-3.instances.magento-community.engineering/admin](https://i-25561-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gioamato** [comment]
Cron seems to be not correctly working on the test instance:

![Annotation 2019-11-11 200725](https://user-images.githubusercontent.com/1331480/68613477-1e30ca00-04bf-11ea-87ca-3c67e1d5de6f.png)

Can't test the issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23205` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gioamato** [comment]
The issue appears to be solved from 2.3.4
