### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by taihuuho** [magento/magento2#25565]
### Preconditions (*)

1. Magento v2.3.1 running in a docker container
2. Enabled MessageQueue consumer.
3. Ran `setup:upgrade`, `setup:di:compile` and `bin/magento setup:static-content:deploy`

### Steps to reproduce (*)

1. Login to admin portal
2. Click on Store > Configuration to change some settings

### Expected result (*)

1. The page should load fine

### Actual result (*)

1. The `Uncaught ReferenceError: require is not defined` threw in the chrome console window
2. The page loaded without styling
<img width="1291" alt="Screen Shot 2019-11-12 at 12 19 02 AM" src="https://user-images.githubusercontent.com/12061272/68646908-12a2ca80-04e2-11ea-994f-a7739b263410.png">

**Comment by taihuuho** [comment]
Closing as I figured it out

**Comment by MarcinJarowski** [comment]
@taihuuho I'm having the same issue, what steps did you take?

**Comment by SebastienPoncelet** [comment]
@taihuuho would you mind sharing how you solved this issue?
