### ISSUE TITLE
Reindexing issue

### ISSUE THREAD

**Issue by chauhanabhi88** [magento/magento2#2556]
I want to know from where I can reindex from admin panel because I tried to reindex from index management page but there is only 2 options available. One to update on save & another update by schedule. Can I reindex data manual from admin panel.

please let me know asap

Thanks

**Comment by daim2k5** [comment]
@chauhanabhi88 no you can't reindex from the admin panel only via cli or cron job

**Comment by mttjohnson** [comment]
http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-index.html#config-cli-subcommands-index-reindex

**Comment by daim2k5** [comment]
@chauhanabhi88 can we close the issue?

**Comment by chauhanabhi88** [comment]
yes. Thanks for replying me

**Comment by usmanmaqsoodshahab** [comment]
Create a new file with "**.bat**" extension

# Copy all code below in paste it into newly created **.bat** file.

`@echo off`
`REM -----`
`REM Created By Usman Shahab`
`REM Cron job in WAMP`
`php -c C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/bin/magento setup:static-content:deploy`
`php -c C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/bin/magento indexer:reindex`
`php -c C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/bin/magento cache:clean`
`php -c C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/bin/magento cache:flush`
`php -c C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/bin/magento customer:hash:upgrade`
`php -f C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/bin/magento cron:run`
`php -f C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/update/cron.php`
`php -f C:\wamp\bin\apache\apache2.4.9\bin\php.ini  C:/wamp/www/magento2/bin/magento setup:cron:run`
==============**NOTE**===================

# In my case,i have installed wamp server and location of my "php.ini" file is "C:\wamp\bin\apache\apache2.4.9\bin\php.ini" and magento installation directory is "C:/wamp/www/" with name of solution is "magento2", so change it accordingly.

Save the file and double click on it/Open this file...which shows a command-line interface.No input is required from your side
(Be patience! It may take some time to complete)
Hurraahh! You re-indexed successfully
