### ISSUE TITLE
Page jumps up once click on view detail to view products options on checkout

### ISSUE THREAD

**Issue by jignesh26** [magento/magento2#25564]
Page jumps up once click on view detail to view products options on checkout
Same issue while click on view details from mini cart

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
1. Front end -> Add product to cart which have product options
2. Go to checkout
3. Click on order summary
4. Now click on view details for any product options

### Expected result (*)
It should stay on the same section

### Actual result (*)
https://www.screencast.com/t/7RYVi0q15

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25564-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25564-2-3-develop.instances.magento-community.engineering/admin](https://i-25564-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23025` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Den4ik** [comment]
@jignesh26 @krishprakash Fixed at https://github.com/magento/magento2/pull/23862 but this PR not included into 2.3.3
