### ISSUE TITLE
Export stock sources: exports old products, that are no longer exists

### ISSUE THREAD

**Issue by vitmarks** [magento/magento2#25560]
### Preconditions (*)

1. Magento: 2.3.3 
2. Create products and configurable products with stock via REST. I always manage the stock and products over the REST API. Maybe there is an issue.

### Steps to reproduce (*)

1. Create some simple/configurable products via REST
2. Delete some of them via REST
3. Create the same products again but with different sku and name and stock via REST

### Expected result (*)

1. Old/deleted products should be "deleted" from the system/db 
2. The export of stock sources must contain data of existing products

### Actual result (*)

1. The export of stock sources list all products with stock and some products, that are already deleted from the system but still in the export.
2. in my case: I have 454 simple products, but the export shows 544

**Comment by engcom-Charlie** [comment]
Hello @vitmarks !
Your issue for Magento inventory modules.

Please duplicate this issue in [Magento Inventory repository](https://github.com/magento/inventory/issues), for advice or general discussion about this issue.

Thanks for your report!
