### ISSUE TITLE
Coupon code not valid when I add any condition through rest checkout

### ISSUE THREAD

**Issue by jaydalisay** [magento/magento2#25579]
### Summary (*)

As title stated, at the moment if a cart rule has conditions (subtotal >= etc), the response returns as "Coupon not valid"

**Comment by engcom-Echo** [comment]
Hello @jaydalisay

Could you provide more details for reproduce this issue?
Please add steps to reproduce and version of magento.

Thank you!

**Comment by jaydalisay** [comment]
I took a different route instead.
