### ISSUE TITLE
Cache control headers are missing when SDC is not pre-generated

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#25578]
### Preconditions (*)
1. Apache 2.4 + php 7.2
2. Magento 2.3.3 or 2.3-develop
3. Magento mode: default, developer OR production with [enabled SCD on demand](https://magento.stackexchange.com/questions/260918/is-scd-on-demand-variable-available-for-magento-2-open-source-version) and without running static content deploy

_This issue isn't reproducing in production mode with compiled static content and not reproducing with nginx+php_fpm._

### Steps to reproduce (*)
Case 1:
1. Open Google Chrome developer tools
2. Navigate to homepage
3. In Google Chrome dev tools looks at any .js file (I checked on domReady.js file), look at "Response Headers" section
4. Refresh the page, find the same JS file, looks at "Response Headers"

Case 2:
Try to curl some js file from Magento/blank two times(because you never request it before):
![image](https://user-images.githubusercontent.com/51680850/68941175-c2f82380-07ad-11ea-91c0-c1c59417bff4.png)

### Expected result (*)
1. First time file should contains Cache-Control header
2. Second time should also contains Cache-Control header

### Actual result (*)
1. At first time Cache-Control header is missing
![image](https://user-images.githubusercontent.com/1873745/68743069-4f61e500-05fa-11ea-9dc2-c54d3390aa80.png)

2. At second time - this header is there
![image](https://user-images.githubusercontent.com/1873745/68743080-5688f300-05fa-11ea-83c3-c3ba8098a5db.png)

### Additional info

In case if we'll have CDN - first response will be cached for many people and browser will not cache JS files in browser's cache. Also there are another headers missing (see screenshots) that could create incorrect behavior.

This issue caused by redirecting to static.php file when real .js file doesn't exists, and adding Cache-Control header isn't applying. 
https://github.com/magento/magento2/blob/dfffe34707e5a338118a3522c6759299d4390af8/pub/static/.htaccess#L75-L77

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-25578-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25578-2-3-develop.instances.magento-community.engineering/admin](https://i-25578-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-25578-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25578-2-3-develop.instances.magento-community.engineering/admin](https://i-25578-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23201` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
I would close this issue. It's quite rare case and reproducing only in case if you're using Apache web server. With Nginx + php-fpm issue isn't reproducing.

General recommendation will be switching to Nginx + php-fpm.
