### ISSUE TITLE
Calendar product custom option saves the day before when added to cart

### ISSUE THREAD

**Issue by textarea** [magento/magento2#25575]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Create a DATE custom option on one product 
2. Go to Stores -> Configuration -> Catalog -> Catalog -> Date & Time Custom Options
3. Set "Use JavaScript Calendar" to "Yes"
4. Go to product page, choose one date and add that product to cart

### Expected result (*)
1. same date on product options as I set on product page

### Actual result (*)
1. Got the day before the value I set

**Comment by textarea** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @textarea. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @textarea, here is your [Magento instance](https://i-25575-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25575-2-3-develop.instances.magento-community.engineering/admin](https://i-25575-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by textarea** [comment]
Can't reproduce the issue on Magento 2.3-develop instance.
Closing.
