### ISSUE TITLE
Email validation failure for customer via API

### ISSUE THREAD

**Issue by prasad167** [magento/magento2#25577]
### Preconditions (*)

1. Customer should be created through API or programmatically.

### Steps to reproduce (*)

1. Try to create a customer through API

URL: https://Magentoinstancepath/rest/V1/customers 

Data:
```
{
  "customer": {
    "email": "manna@gmail.com1",
    "firstname": "Manna",
    "lastname": "Test",
    "gender": 0
}
} 
```
method type: post

### Expected result (*)

1. Validation should behave in the same way as in Magento UI
2. Validation of .com1 should happen through API as well 

### Actual result (*)

1. Validation is not happening similar for Magento UI and API
2. Magento should not allow creating a customer with Email having .comXXX through API

**Comment by prasad167** [comment]
@magento give me 2.3-develop instance

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23208` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kanthy-magento** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25577-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25577-2-4-develop.instances.magento-community.engineering/admin](https://i-25577-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
Hi,

I'm able to replicate this issue on CE-2.4
Please find the video recording for the same - https://www.screencast.com/t/km8B1Orv

Thank You,
Pranith

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-25247` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lenaorobei** [comment]
Hi @prasad167,
Unfortunately I need to close this issue in favor of internal ticket.
This issue is requires more complex approach of resolving and should be consistant within REST, Storefront and GraphQL.

Taking into account that right now such validation for Storefront is happening through JS, the same approach can be used for your PWA implementation for example.

This is still under the discussion where we want to keep this kind of validation.

Thanks.
