### ISSUE TITLE
Products on wishlist search result show $0.00 price

### ISSUE THREAD

**Issue by dipak85shinde** [magento/magento2#25573]
Preconditions:
1)Magento version - 2.3.3
2)PHP version - 7.2
3)Multiple wishlist functionality should be enabled
4)Two customers should be registered and have "Public Wishlist" for each

Steps to reproduce:
1.Login to customer account A
2. Add some configurable products with options like color or size to the wishlist which is public
3.Login to customer account B
4. Go to search wishlist using http://your-domain/wishlist/search
5. Search wishlist by "Owner Email" (by customer A email Address) 
6. When a result comes click on "View" and check the products

Expected result:
1. Configurable products with options must be shown, respective simple product price 

 Actual result:
1. products are showing zero price even we have selected product options for configurable products
![wishlist](https://user-images.githubusercontent.com/20471885/68679213-7205e680-0585-11ea-94b0-78ec4d1f95fe.png)

**Comment by dipak85shinde** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dipak85shinde. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dipak85shinde, here is your [Magento instance](https://i-25573-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25573-2-3-develop.instances.magento-community.engineering/admin](https://i-25573-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dipak85shinde** [comment]
@magento-engcom-team issue is related to enterprise edition. I am not able to test on [https://i-25573-2-3-develop.instances.magento-community.engineering/admin](url)

**Comment by kanthy-magento** [comment]
@dipak85shinde - Please reach out to Enterprise team and they will guide you on this issue. 
To reach Enterprise team, you should login into Magento Enterprise  and from there you can start communicating. 

I'm closing this ticket. As this forum is for Community contributions.
