### ISSUE TITLE
Can not preview template when edit queue

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25570]
### Preconditions (*)

1. Magento 2.3-develop + 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. Marketing->Newsletter Templates
3. Create New Template and save
4. Go to grid, in the row of the template which is created,  choose "Queue Newsletter"
5. Click "Preview Template"

### Expected result (*)

1. Show the preview of template

### Actual result (*)

1. Nothing happened, Javascript error

![image](https://user-images.githubusercontent.com/8234209/68674166-e9d51080-0587-11ea-8623-c866f472a0ba.png)

![issue_25570](https://user-images.githubusercontent.com/3409584/81702152-86417800-9430-11ea-9d1c-1357be3eff91.gif)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25570-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25570-2-3-develop.instances.magento-community.engineering/admin](https://i-25570-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23032` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
