### ISSUE TITLE
Custom attribute is not working on advanced search 

### ISSUE THREAD

**Issue by smithjho** [magento/magento2#25572]
I have created a product attribute and assigned to default group. The attribute is configured with Visible in Advanced Search=Yes and used them with configurable products. The configurable products have at least two simple products associated with it.

When I use advanced search to search items with a specified attribute values, no results shows up on the result page. I noticed that the issue occurs on configurable product. The result shows simple products with the attribute value but not showing configurable products in the advanced search result. Visibility is "Catalog, Search" for the configurable product.

**Comment by smithjho** [comment]
@magento give me 2.1.10 instance

**Comment by magento-engcom-team** [comment]
Hi @smithjho. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by dev-ajaysaini** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-ajaysaini, here is your [Magento instance](https://i-25572-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25572-2-3-3.instances.magento-community.engineering/admin](https://i-25572-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25572-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25572-2-3-develop.instances.magento-community.engineering/admin](https://i-25572-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
Hi @smithjho thank you for your report. I tried to reproduce your issue in different ways, but always was able to find products by new attribute. Please provide more information about you steps to reproduce and setting what you are using (would be great to provide screenshots with full settings on attribute page). 
More information about ticket reporting you can find here https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by patricksabado** [comment]
this still don't work from my end. I'm using Magento 2.3.3 

from \Magento\CatalogSearch\Model\Advanced\ProductCollectionPrepareStrategy line 54. It will get all attribute that is "Used in Product Listing". In my part that the return array got the custom attribute that I'm expecting. But when I inspect the inspect the collection sql query i get the below instead.

`SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `cat_index`.`position` AS `cat_index_position` FROM `catalog_product_entity` AS `e` INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(3, 4) AND cat_index.category_id=2 WHERE (e.created_in <= 1) AND (e.updated_in > 1)`

I added $collection->getSelect() in line 61 of \Magento\CatalogSearch\Model\Advanced\ProductCollectionPrepareStrategy. I can't find the attibute code of my custom attribute and the select and also the filter.
