### ISSUE TITLE
Navigation menu 4th level/category does not appear consistently

### ISSUE THREAD

**Issue by dbabaev** [magento/magento2#25589]
### Preconditions (*)

1. Magento version 2.3.3

### Steps to reproduce (*)

1. We created 4 levels of categories. When we hover the 3rd level, the last 4th level/category does not appear consistently. It only appears maybe 1 out 3 times. We are running an unmodified Luma theme.

### Expected result (*)

1. The 4th level of menu fly out 100% of the time.
![2019-11-13_15-31-30](https://user-images.githubusercontent.com/57729709/68802270-9ddba780-062b-11ea-90f3-1d2ced002a00.png)

### Actual result (*)

1. The 4th level only flies out 1 out of 3 time we hover over level 3.

**Comment by ajijshekh123** [comment]
give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25589-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25589-2-3-develop.instances.magento-community.engineering/admin](https://i-25589-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @dbabaev,
I have reviewed this issue'sin latest default Magento 2.3 instance. Currently, I have reproduced this issue.

See attached the video:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/24711761/68828331-50167c00-06cb-11ea-9d7f-5c8396b4a738.gif)

Please do not close this issue. I know this issue related to the below reference issue.
https://github.com/magento/magento2/issues/7543

Please review this issue again and work on it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23129` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by fabriciosobral** [comment]
I'm working on this

**Comment by fabriciosobral** [comment]
give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fabriciosobral. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fabriciosobral, here is your [Magento instance](https://i-25589-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25589-2-3-develop.instances.magento-community.engineering/admin](https://i-25589-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @dbabaev. Thank you for your report. 
The issue has been fixed in magento/magento2#25613 by @fabriciosobral in 2.3-develop branch
Related commit(s):
 - [16fa4c4a6d4fd2e49cfbecef7a3fae11f18613cc](https://github.com/magento/magento2/commit/16fa4c4a6d4fd2e49cfbecef7a3fae11f18613cc)

The fix will be available with the upcoming 2.3.5 release.
