### ISSUE TITLE
Mixins are not applied for advanced bundled modules

### ISSUE THREAD

**Issue by krzksz** [magento/magento2#25586]
### Preconditions (*)

1. Bundle your JavaScript files using one advanced bundling technique of your choosing, e.g. https://github.com/magento/baler

### Steps to reproduce (*)

1. Open the shop.
2. Notice that mixins are neither loaded nor applied for any of the bundled modules.

### Expected result (*)

1. Mixins are properly loaded and applied for all modules.

### Actual result (*)

1. Mixins are neither loaded nor applied.

Please consult https://github.com/magento/baler/issues/23 where I described the root cause of the issue in great detail. I'm submitting a separate issue here because we believe that it would be best to fix it directly in core and I'm going to send a PR in a few minutes 🤗

**Comment by magento-engcom-team** [comment]
@drpayyne Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @drpayyne 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23196` were created

**Issue Available**: @drpayyne, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
