### ISSUE TITLE
\Magento\MediaStorage\Model\File\Storage\Synchronization::synchronize() contains a wrong PHPDoc comment for the $file variable

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2558]
https://github.com/magento/magento2/blob/2.0.0/app/code/Magento/MediaStorage/Model/File/Storage/Synchronization.php#L59-L60

Should be 

```
/** @var \Magento\Framework\Filesystem\File\WriteInterface $file */
```

**Comment by mazhalai** [comment]
Thank you for reporting, we have created ticket MAGETWO-46204 to fix it.

**Comment by okorshenko** [comment]
@dmitry-fedyuk thank you for reporting the issue
@renatocason thank you for fixing the issue in PR: magento/magento2#8762
