### ISSUE TITLE
Error with FAQ/ We cannot access and edit the FAQ questions.

### ISSUE THREAD

**Issue by Safegear** [magento/magento2#25598]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by krishprakash** [comment]
Hi @Safegear.
Please fill all necessary details to reproduce this issue as per below guidelines
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by krishprakash** [comment]
@Safegear.
Feel free to reopen the issue once you update reproducible steps and all the necessary details.
Thanks.
