### ISSUE TITLE
Links do not work in admin section.

### ISSUE THREAD

**Issue by gfxguru** [magento/magento2#2559]
Most links in admin section do nothing and only a couple links even work in the admin section. I've tried 2.0 and latest dev. Same with chrome and Mozilla.

**Comment by bh-ref** [comment]
are there any errors you see in the console of the chrome dev tools like javascript files that could not be loaded? that was the cause when I experienced this behaviour.

**Comment by mazhalai** [comment]
+1 to what @bh-ref  said

**Comment by davidalger** [comment]
Closing due to lack of response and possible duplicate of #2711
