### ISSUE TITLE
Review Summary not showing reviews on product page

### ISSUE THREAD

**Issue by NathMorgan** [magento/magento2#25599]
### Preconditions (*)
Magento Version: 2.3.3 / 2.2.10

Store reviews must be enabled

### Steps to reproduce (*)
1. Submit a product review
2. Approve review in admin (If required)

### Expected result (*)
1. Review should appear on the product page

### Actual result (*)
1. Text `Be the first to review this product` still shows on the product page even though in the review section it shows the newly added review

### Possible Cause

After reviewing it seems the issue is coming from these lines:

https://github.com/magento/magento2/blob/ac4af31bad1d28c3564d76cd87569969f2184ed2/app/code/Magento/Review/Block/Product/ReviewRenderer.php#L121

https://github.com/magento/magento2/blob/ac4af31bad1d28c3564d76cd87569969f2184ed2/app/code/Magento/Review/Block/Product/ReviewRenderer.php#L131

Changing them to include `getRatingSummary()` on both `$this->getProduct()->getRatingSummary()->getRatingSummary()` and `$this->getProduct()->getRatingSummary()->getReviewsCount()` allows the review summary to render correctly.

This commit seems to have changed those lines: https://github.com/magento/magento2/commit/f72f74d3654d8794dabac97bf8cf91925eea07cd

**Comment by NathMorgan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @NathMorgan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @NathMorgan, here is your [Magento instance](https://i-25599-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25599-2-3-develop.instances.magento-community.engineering/admin](https://i-25599-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by NathMorgan** [comment]
@magento give me 2.2 instance

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25599-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25599-2-3-develop.instances.magento-community.engineering/admin](https://i-25599-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @NathMorgan,

I have verified this issue on Fresh Default Magento 2.3 Instance. I have verified your steps but I can't reproduce this issue.
This issue is related to the below link:
https://github.com/magento/magento2/issues/24997
@NathMorgan - Can you please send the video?
This issue may be found on Magento 2.2 Instance.
Please update me.

Thanks.

**Comment by NathMorgan** [comment]
Hi @ajijshekh123

I'm unable to replicate on base 2.2/2.3 will close.

**Comment by ajijshekh123** [comment]
Okay Fine @NathMorgan
