### ISSUE TITLE
Product image url cache url mismatch

### ISSUE THREAD

**Issue by AbhijithHaridas** [magento/magento2#25594]
Products appear fine in admin, but on the frontend single product page all product images return a 404, because of the following url structure:

/media/catalog/product/cache/**3f23d2e4809353014f98c960f33015e5**/c/o/colibri-ii-1.jpg

the correct URL might be: 

/media/catalog/product/cache/**2079bcffb72cffec59b22238cd9743e6**/c/o/colibri-ii-1.jpg

Clearing Magento cache, product image cache not solving the issue

**Magento version: 2.3.3**

**Comment by engcom-Echo** [comment]
Hello @AbhijithHaridas 

Could you provide more details for reproduce this issue?
Please add steps to reproduce.

Thank you!

**Comment by AbhijithHaridas** [comment]
Hello, thanks for replying. The issue was due to a **server configuration** the image caches were not generating. It is solved by configuring the server settings properly

**Comment by engcom-Echo** [comment]
Hello @AbhijithHaridas 

According this [comment](https://github.com/magento/magento2/issues/25594#issuecomment-554204631) I close this issue as it was connected with environment configuration.
If you would like to update this issue, please reopen it.
