### ISSUE TITLE
Missing composer packages for magento 2.1.9

### ISSUE THREAD

**Issue by jwbeech** [magento/magento2#25607]
### Description
Not sure if this is the correct forum but it appears that today (14/11/2019) a number of the composer sub packages has been "unpublished".
Our builds all use composer to install dependencies and this morning started failing to locate a sub dependency of 'magento/product-community-edition 2.1.9'
In debugging this was found to be one of many missing dependencies.

Here is the error on install:
```
Problem 1
- Installation request for magento/product-community-edition 2.1.9 -> satisfiable by magento/product-community-edition[2.1.9].
- magento/product-community-edition 2.1.9 requires magento/module-marketplace 100.1.2 -> no matching package found.
```

Doing a bit of digging with composer shows that the 100.1.2 version of that module seems to no longer be available:

```
$ composer show magento/module-marketplace --all
name : magento/module-marketplace
descrip. : N/A
keywords :
versions : 100.3.3, 100.3.2, 100.3.1, 100.3.0, 100.2.5, 100.2.4, 100.2.3, 100.2.2, 100.2.1, 100.2.0, 100.2.0-rc30, 100.2.0-rc23, 100.2.0-rc22, 100.2.0-rc21, 100.2.0-rc20, 100.1.5, 100.1.4, 100.1.3, 100.1.1, 100.1.0, 100.1.0-rc3, 100.1.0-rc2, 100.1.0-rc1, 100.0.7, 100.0.6, 100.0.5, 100.0.4, 100.0.3, 100.0.2
type : magento2-module
license : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
source : []
dist : [zip] https://repo.magento.com/archives/magento/module-marketplace/magento-module-marketplace-100.3.3.0.zip
names : magento/module-marketplace

autoload
files
psr-4
Magento\Marketplace\ => .

requires
php ~7.1.3||~7.2.0||~7.3.0
magento/framework 102.0.*
magento/module-backend 101.0.*
```

**Comment by shiuh-yaw** [comment]
it also happened in magento 2.1.7
```
Problem 1
- Installation request for magento/product-community-edition 2.1.7 -> satisfiable by magento/product-community-edition[2.1.7].
- magento/product-community-edition 2.1.7 requires magento/module-advanced-pricing-import-export 100.1.2 -> no matching package found.
```

**Comment by engcom-Charlie** [comment]
Hello @jwbeech 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch & 2.3.3.

We are closing this issue due to branch `2.1-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.1 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!
