### ISSUE TITLE
Email template preview not working

### ISSUE THREAD

**Issue by jellebelle** [magento/magento2#25605]
### Preconditions (*)

1. Magento ver. 2.3.2
2. Safari 13.0.3. and Opera 64.0.3417.92
3. Mac OS 10.14.6 (18G95)

### Steps to reproduce (*)

1.Under 'Marketing' --> 'email templates' after selecting a template the preview does not work on Safari 13.0.3. and does not work on Opera 64.0.3417.92
2.

### Expected result (*)

1.  A preview so I can verify edits, zap bugs, correct typos before setting the template live!

### Actual result (*)

1. An empty popup / new browser tab with NO preview
2.

**Comment by jellebelle** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jellebelle. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jellebelle, here is your [Magento instance](https://i-25605-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25605-2-3-develop.instances.magento-community.engineering/admin](https://i-25605-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jellebelle** [comment]
Ok it works on your instance. But i see it is the upcoming 2.3.x release?

**Comment by jellebelle** [comment]
I should i request an instance of my version?

**Comment by krishprakash** [comment]
Hi @jellebelle 
Thank you for your report.
Issue not able to reproduce on latest magento instance.
So closing this
Thanks
