### ISSUE TITLE
Role resource tree not displaying in magento 2.3.3

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25608]
Magento 2.3.3

In the backend, going to system->roles, adding a new role and setting it to custom permissions, the resource tree is empty

![Schermata 2019-11-14 alle 16 46 35](https://user-images.githubusercontent.com/48567585/68872817-efa13200-06fe-11ea-88f7-f32ad3497977.png)

![Schermata 2019-11-14 alle 16 52 01](https://user-images.githubusercontent.com/48567585/68872997-32fba080-06ff-11ea-96af-ebafe137f763.png)

**Comment by abdulrafaywaqar** [comment]
please update is it fixed or not?

**Comment by ghost** [comment]
Fixed

**Comment by apaolino** [comment]
How did you fixed?

**Comment by abdulrafaywaqar** [comment]
Yes one of my module having issues in acl. The issue was existed in Uber
theme base module.

**Comment by apaolino** [comment]
And how did you understand which module was the cause?

**Comment by ghost** [comment]
Dovresti disabilitare tutti i moduli di terze parti e abilitarli, verificandoli ad uno alla volta

**Comment by abdulrafaywaqar** [comment]
I have printed the JSON which print the resource tree it was breaking from
a specific module in Uber theme base module then I have debug and fixed the
acl.xml file.

**Comment by ApacheThank** [comment]
Change your local language to English, sign out and reconnect and try now.
It's work for me on magento 2.3.3

**Comment by fabrice-dresscodes** [comment]
Hello,

With admin user with french package, I get the problem on 2.3.3

        "mageplaza/magento-2-french-language-pack": "dev-master"

It might be an issue with an "accent" :) 

No need to correct for now!
