### ISSUE TITLE
Error in Installing Magento 2.0

### ISSUE THREAD

**Issue by yasardesigns** [magento/magento2#2560]
Hi 
  i am new to Magento.when i install Magento on localhost.the installation was successful.as you can see below

![success](https://cloud.githubusercontent.com/assets/11024306/11470533/8ae62386-9784-11e5-9f5f-622bbdf5c4f1.png)

When i access the home page.there where no images ,it was so blank as you can see below

![home](https://cloud.githubusercontent.com/assets/11024306/11470551/b28226ec-9784-11e5-979f-696e360eb51e.png)

When i looked in the console i got the following errors

![error](https://cloud.githubusercontent.com/assets/11024306/11470564/d22da23c-9784-11e5-8852-c3fb38d59622.png)

And when i open the admin panel.i got the following error

![admin](https://cloud.githubusercontent.com/assets/11024306/11470571/ecf04d9a-9784-11e5-9b27-9fa34869307f.png)

I have no idea what is going on please guide me

**Comment by mazhalai** [comment]
1. It is not recommended to use localhost
2. Can you please give more details about your env?
3. Also, did you try running `bin/magento setup:static-content:deploy` on command line?

**Comment by nabilnazieh** [comment]
i face the same problem and i have xampp 5.6.14 installed on win7 
after run the command "bin/magento setup:static-content:deploy" on command line the first issue is solve but access to admin panel issue still exist

**Comment by yasardesigns** [comment]
HI  @mazhalai 

I am using Xammp 
i am installing Magento on windows 8 in localhost
PHP Version 5.5.30,
Apache 2.4.17,
phpMyAdmin 4.5.1,
MariaDB 10.1.8,
post_max_size= 750M,
max_file_uploads=  20,
memory_limit= 1000M,
max_execution_time= 259200

i didn't do anything on command line.this is what i did. 
1. i have downloaded the Magento community edition version 2.0 along with sample data
2. extracted the zip and copied the Magento files into my localhost directory named Store
3. copied the media folder from the sample-data-folder to the Store folder
4. Created a Database named online_store 
5. accessed the folder like this http://localhost:8080/Store
6. followed all the instructions and the installation was successfull
7. When i access the home page there is where the problem occur

Please guide me to resolve this issue

**Comment by mazhalai** [comment]
@yasardesigns after step 6 did you try running `bin/magento setup:static-content:deploy` on command line?

**Comment by yasardesigns** [comment]
HI  @mazhalai 
      i didn't run the above command in the command line at first.but when i tried it now ,following is what i got

![cmd](https://cloud.githubusercontent.com/assets/11024306/11523176/f671e434-98e5-11e5-9701-79532bf7acf3.png)

**Comment by wonderfan** [comment]
@yasardesigns , you should use php to run the magento command

**Comment by yasardesigns** [comment]
HI @mazhalai,@wonderfan ,the deployment was successful without any errors.i can able to access the admin pannel without any issues.but the home page is blank, i can see just a white screen.

Should i have to import the magento_sample_data_for_1.9.1.0.sql that comes along with the sample data into the database

**Comment by wonderfan** [comment]
yes, you need to install sample data.

**Comment by alankent** [comment]
Hi @yasardesigns - your problem is "magento" in the bin directory is not being picked up as an executable. There was a magento.bat file floating around internally, but it has not made the distribution yet. It basically ran "php magento" (with all the arguments), so using "php magento ..." is the safest cross platform approach for now.

**Comment by wonderfan** [comment]
@alankent alan explains the details, but you need to add the php into your path.
