### ISSUE TITLE
Unable to configure Subscription Options for newsletters

### ISSUE THREAD

**Issue by fongd** [magento/magento2#25628]
### Preconditions (*)

1. Magento CE 2.3.3 originally created from a Magento 1.9 site via data migration tool

### Steps to reproduce (*)

1. Navigate to Stores > Configuration > Customers > Newsletter in the administration area
2. Make sure "Enabled" is set to "Yes" under General Options
3. Click Subscription Options to expand that section

### Expected result (*)

Subscription Options should expand to show additional newsletter subscription configuration options

### Actual result (*)

Nothing happens. The disclosure indicator flips as if to suggest that a section was expanded but nothing appears.

![Uploading Screen Shot 2019-11-17 at 1.30.32 AM.png…]()

**Comment by fongd** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fongd. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fongd, here is your [Magento instance](https://i-25628-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25628-2-3-develop.instances.magento-community.engineering/admin](https://i-25628-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by fongd** [comment]
Closing - 1Blocker content blocker was breaking this specific page in Safari for some reason (other admin pages don't appear to be similarly affected).
