### ISSUE TITLE
Unable to save page and block changes using Page Builder with enabled js minification.

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#25620]
### Preconditions (*)
1. Magento 2.3.3 EE

### Steps to reproduce (*)
1. Stores->Settings->Configuration->Advanced->Developer->JavaScript Settings->Minify JavaScript Files = Yes
2. Set production `bin/magento deploy:mode:set production`
3. Go to Content->Elements->Blocks\Pages->Edit
4. Make changes and Save

### Expected result (*)
1. Possibility to edit and save blocks and pages.

### Actual result (*)
1. Changes are not saved.

### Additional Information
1. I can see in browser console that Page Builder tries to load not minified resources. Since we have js minification enabled, in static content exists only minified js.

**Comment by sdzhepa** [comment]
Hello @LordHansolo 

Thank you for contribution and collaboration!

This issue related to Page Builder functionality which is not part of Magento Open Source.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.


But I have asked internal Magento team(who is working on Page Builder) about this issue and
- This issue has been fixed and will be available with next release `2.3.4`
- The same issue was reported into the **private repository** related to [Page Builder](https://github.com/magento/magento2-page-builder/issues/306) on Oct 25 2019 and was fixed and delivered with internal Pull Request [#304](https://github.com/magento/magento2-page-builder/pull/304).

**Comment by ArtemPopenko** [comment]
@sdzhepa Could you please provide patch to fix the issue until 2.3.4 is not released?
Thanks a lot.

**Comment by mugua** [comment]
> ### Preconditions (*)
> 1. Magento 2.3.3 EE
> 
> ### Steps to reproduce (*)
> 1. Stores->Settings->Configuration->Advanced->Developer->JavaScript Settings->Minify JavaScript Files = Yes
> 2. Set production `bin/magento deploy:mode:set production`
> 3. Go to Content->Elements->Blocks\Pages->Edit
> 4. Make changes and Save
> 
> ### Expected result (*)
> 1. Possibility to edit and save blocks and pages.
> 
> ### Actual result (*)
> 1. Changes are not saved.
> 
> ### Additional Information
> 1. I can see in browser console that Page Builder tries to load not minified resources. Since we have js minification enabled in static content exists only minified js.

Hi Lordhansolo
Have you fixed this issue now?

**Comment by LordHansolo** [comment]
Thank You @sdzhepa.
Hello @mugua.
Yes I fixed it. I will provide You part of code and places where they should appear.

In my module I created block that extends Magento\PageBuilder\Block\Adminhtml\Stage\Render and adds two additional methods `isJsMinificationEnabled` and `getMinResolverAssetUrl`.

```
<?php

namespace Fix\PageBuilder\Block\Adminhtml\Stage;

use Magento\Framework\Serialize\Serializer\Json;
use Magento\Framework\View\Asset\Minification;
use Magento\Framework\View\Element\Template\Context;
use Magento\PageBuilder\Block\Adminhtml\Stage\Render as ParentRender;
use Magento\PageBuilder\Model\Stage\Config;
use Magento\RequireJs\Model\FileManager;

/**
 * Class Render
 */
class Render extends ParentRender
{
    /**
     * @var FileManager
     */
    private $fileManager;

    /**
     * @var Minification
     */
    private $minification;

    /**
     * Class constructor
     *
     * @param Context $context
     * @param FileManager $fileManager
     * @param Config $config
     * @param Json $json
     * @param Minification $minification
     * @param array $data
     */
    public function __construct(
        Context $context,
        FileManager $fileManager,
        Config $config,
        Json $json,
        Minification $minification,
        array $data = []
    ) {
        parent::__construct($context, $fileManager, $config, $json, $data);

        $this->fileManager = $fileManager;
        $this->minification = $minification;
    }

    /**
     * Check that js minification is enabled
     *
     * @return boolean
     */
    public function isJsMinificationEnabled()
    {
        return $this->minification->isEnabled('js');
    }

    /**
     * Get min resolver asset url
     *
     * @return string
     */
    public function getMinResolverAssetUrl()
    {
        $minResolver = $this->fileManager->createMinResolverAsset();
        $url = $minResolver ? $minResolver->getUrl() : '';

        return $url;
    }
}

```

Next I created template in My module scope `view/adminhtml/templates/stage/render.phtml` with content from `<magento_root>/vendor/magento/module-page-builder/view/adminhtml/templates/stage/render.phtml` and add code below after `<script src="<?= $block->escapeUrl($block->getRequireJsUrl()); ?>"></script>`.

```
<?php if ($block->isJsMinificationEnabled()) : ?>
    <script src="<?= $block->escapeUrl($block->getMinResolverAssetUrl()); ?>"></script>
<?php endif ?>
```

Next I created Controller that extends `Magento\PageBuilder\Controller\Adminhtml\Stage\Render`. Copy entire execute method and override part below.

```
$renderBlock = $layout->createBlock(
    \Fix\PageBuilder\Block\Adminhtml\Stage\Render::class,
    'stage_render'
);
$renderBlock->setTemplate('Fix_PageBuilder::stage/render.phtml');
```
Next I created adminhtml/di.xml to set preference for Magento\PageBuilder\Controller\Adminhtml\Stage\Render.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\PageBuilder\Controller\Adminhtml\Stage\Render" type="Fix\PageBuilder\Controller\Adminhtml\Stage\Render" />
</config>
```

Next in module.xml I add Magento_PageBuilder to sequence.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Fix_PageBuilder" setup_version="1.0.0">
        <sequence>
            <module name="Magento_PageBuilder"/>
        </sequence>
    </module>
</config>
```

Thats all. Now Page Builder should work fine with enabled js minification.

**Comment by mugua** [comment]
@LordHansolo, Could you add my Skype: john.lou@msn.com or offer yours, Thanks.
I have a little confuse about this, Thanks.

**Comment by LordHansolo** [comment]
@mugua Wait a moment. Something is broken and I can not paste my code to have proper format.

**Comment by theCapypara** [comment]
@mugua @LordHansolo If you have an active Magento Commerce subscription you can just ask the Commerce support and they'll send you a patch.

**Comment by kushaljindal92** [comment]
I have made module based on @LordHansolo reply,, it is working perfectly.
https://github.com/kushaljindal92/magentoee-pagebuilder-fix

**Comment by dfelton** [comment]
@Parakoopa Is this patch not listed in the Downloads section our accounts on Magento.com?

**Comment by theCapypara** [comment]
@dfelton As far as I know you have to open a support ticket and reference this GitHub issue. That's what we did and they sent us a patch.

**Comment by vbuck** [comment]
@sdzhepa I just want to thank you for carefully responding to the OP about this issue. There has been a habit of closing issues raised that mention Commerce Edition. Instead you chose to provide guidance _anyway_, and I think that's an example for Adobe to follow when dealing with the community, since Open-Source and Commerce are (for the time being) very closely related.

**Comment by minhducnho** [comment]
Does anyone have a patch to fix this, I have try to fix it but it still doesn't work? I have used  @kushaljindal92's module but it only fix js errors, it still can't save

**Comment by sdouma** [comment]
Does Magento just not test? It seems pretty common for production instances to minify js files.

**Comment by sunilit42** [comment]
@minhducnho  any solution

**Comment by anton-vidext** [comment]
It's happening to me in Magento 2.4.6

**Comment by rejith7** [comment]
Issue reported in 2.4.5 EE, especially while using google chrome with magento running on production mode and minified js enabled.

**Comment by rejith7** [comment]
@anton-vidext did you use google chrome ? can you try using firefox? I'm beginning to think it's browser related issue

**Comment by anton-vidext** [comment]
> @anton-vidext did you use google chrome ? can you try using firefox? I'm beginning to think it's browser related issue

I used google chrome, firefox and edge. It was happening in every browser. 

Disabled minified JS and CSS and I can now save page builder content.

**Comment by Hurrpadurr** [comment]
> Issue reported in 2.4.5 EE, especially while using google chrome with magento running on production mode and minified js enabled.

This is excatly what happens for me. Disabling minified doesn't help for me, but it only happens on Chrome.

**Comment by VitaliyBoyko** [comment]
Still reproducible in Magento 2.4.6

**Comment by VitaliyBoyko** [comment]
I made some investigation.


The CMS page form and the WYSIWYG editor are connected by the JQuery event which transfers the Page Builder instance from the editor to the form.


See:
src/vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/wysiwyg.js:91

 src/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js:27

```
events.on('pagebuilder:register', function (data) {
                if (data.ns === self.ns) {
                    self.pageBuilderInstances.push(data.instance);
                }
            });
```


 If the form is initialized earlier than the editor, the form is missing this event and doesn’t see the PB instance.
 
 
 I've made a temporary hotfix for my project (maybe someone needs a quick solution):
 
`
diff --git a/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js b/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js
--- a/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js	
+++ b/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js	(date 1683647187438)
@@ -44,6 +44,16 @@
                 timeout,
                 locks;
 
+            let self = this;
+            if (_.isEmpty(this.pageBuilderInstances) & this.name === 'cms_page_form.cms_page_form') {
+                var registry = require('uiRegistry');
+                let contentComponent = registry.get(
+                    "cms_page_form.cms_page_form.content.content"
+                );
+
+                self.pageBuilderInstances.push(contentComponent.pageBuilder);
+            }
+
             if (_.isEmpty(this.pageBuilderInstances)) {
                 submit();
             } else {
`

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance with enterprise edition modules enabled and the issue is reproducible.
Hence confirming the issue.
![image](https://github.com/magento/magento2/assets/60198231/dd58361c-3790-4e91-90b5-5b4bc85a16c0)

**Comment by Bilalyounas1234** [comment]
Hi @LordHansolo Could you please explain about the

<?php if ($block->isJsMinificationEnabled()) : ?>
    <script src="<?= $block->escapeUrl($block->getMinResolverAssetUrl()); ?>"></script>
<?php endif ?>

Why did you add this in render.phtml because I have seen this template but I have not seen the script "<script src="<?= $block->escapeUrl($block->getRequireJsUrl()); ?>"></script>" in this template maybe Magento remove this script from the latest version. if you can let me know the reason why you add this code then may I fix it in latest version thanks in advance

**Comment by LordHansolo** [comment]
Hello @Bilalyounas1234

In Magento 2.3.3 EE the template probably looked like in the link below.

https://github.com/magento/magento2-page-builder/blob/v1.1.0/app/code/Magento/PageBuilder/view/adminhtml/templates/stage/render.phtml

**Comment by engcom-Bravo** [comment]
Hi @LordHansolo,

Tested on the latest 2.4-develop version. Enabled “Minify JavaScript Files” in the JavaScript Settings of Store Configuration. In production mode, attempted to edit a Block/Page and save it. Despite multiple edits, changes were successfully saved. After exhaustive attempts to reproduce this issue, it has been determined that the problem is no longer reproducible. Hence we are closing this issue.


https://github.com/magento/magento2/assets/51680745/127790b1-8e28-47cc-9ece-c42e1accce3b


Thanks.

**Comment by mizuapo** [comment]
> I made some investigation.
> 
> The CMS page form and the WYSIWYG editor are connected by the JQuery event which transfers the Page Builder instance from the editor to the form.
> 
> See: src/vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/wysiwyg.js:91
> 
> src/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js:27
> 
> ```
> events.on('pagebuilder:register', function (data) {
>                 if (data.ns === self.ns) {
>                     self.pageBuilderInstances.push(data.instance);
>                 }
>             });
> ```
> 
> If the form is initialized earlier than the editor (that often happens after the first/second save of the CMS page/block and page reload), the form is missing this event and doesn’t see the PB instance.
> 
> I've made a temporary hotfix for CMS Page in my project (maybe someone needs a quick solution):
> 
> ```
> diff --git a/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js b/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js
> --- a/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js	
> +++ b/vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js	(date 1683647187438)
> @@ -44,6 +44,16 @@
>                  timeout,
>                  locks;
>  
> +            let self = this;
> +            if (_.isEmpty(this.pageBuilderInstances) & this.name === 'cms_page_form.cms_page_form') {
> +                var registry = require('uiRegistry');
> +                let contentComponent = registry.get(
> +                    "cms_page_form.cms_page_form.content.content"
> +                );
> +
> +                self.pageBuilderInstances.push(contentComponent.pageBuilder);
> +            }
> +
>              if (_.isEmpty(this.pageBuilderInstances)) {
>                  submit();
>              } else {
> ```

Many thanks @VitaliyBoyko , it works on 2.3.7-p4
