### ISSUE TITLE
extending default nginx config

### ISSUE THREAD

**Issue by magenx** [magento/magento2#2562]
hi

after we were able to "hack" a few new big Magento2 shops running on nginx, we immediately told them about the problem, 
and something they were able to fix, but unfortunately not all.

we came to the conclusion that users do not fully understand how the nginx server is configured and how it works.
not everyone have access to the System Administrator.
'cause with Apache basically a bunch of .htaccess files that simply regulate the application work. 
and you dont have to think about it.

in this case with nginx it is not so easy to just run the application out of the box, 
every configuration, every rule must be rewritten.

the main problem is incorrectly set the root location, then wrong regex in locations, plus lack of deny rules,
mistakes like these give you access to almost everything.

we decided to offer the community a ready configuration, assembled and tested
this configuration was created according to Magento2 folders structure and existing .htaccess files.

we know - those who understand, will be able to write your own configuration, 
but those people who blindly copy - they always make very serious errors that lead to problems.

We will be ready to improve the configuration on your request.

https://github.com/magenx/Magento-nginx-config/tree/master/magento2

**Comment by mazhalai** [comment]
Please submit a PR here https://github.com/magento/magento2/pulls
also, please follow guidelines mentioned here http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html

**Comment by magenx** [comment]
created PR, but i guess it must be reviewed manually

**Comment by mazhalai** [comment]
@magenx yes this will be reviewed internally. Since there is an open PR, closing this issue.
