### ISSUE TITLE
Banner ajax call is shot at every page

### ISSUE THREAD

**Issue by miloszowi** [magento/magento2#25637]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Add banner to Product Listing Page
2. Go to Network in developer tools and watch for `banner/ajax/load` route call

### Expected result (*)

Ajax call to be shot only if the banner is present on the page.

### Actual result (*)

Ajax call is shot at every page, even if the banner is not present on the page.

### Description 
Ajax call to URL  'banner/ajax/load' is shot at every page of the site, problem is that it is being called even if the banner is not present on the page.  This affects performance and should be removed at page without banner.

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25637-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25637-2-3-develop.instances.magento-community.engineering/admin](https://i-25637-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25637-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25637-2-3-develop.instances.magento-community.engineering/admin](https://i-25637-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
@miloszowi thank you for the report. Unfortunately I didn't manage to reproduce the issue. Please add more details. You can check as well yourself if the issue can be reproduce on current magento version using `@magento give me 2.3-develop instance `

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25637-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25637-2-3-develop.instances.magento-community.engineering/admin](https://i-25637-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@miloszowi I am not able to reproduced in Magento 2.3.3 instance. So I am closing this issue.

**Comment by botansatoh** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @botansatoh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by abdulmalik422** [comment]
Any update on this issue?

**Comment by Yonn-Trimoreau** [comment]
Any update on this issue?
