### ISSUE TITLE
Third party api doesn't authorize

### ISSUE THREAD

**Issue by amit-markupdesigns** [magento/magento2#25632]
I have proceed multiple times for third part api(cartrover) in magento 2.3.2 but not authorize.

Server response message: The consumer isn't authorized to access %resources.
Array
(
[resources] => Magento_Sales::actions_view
)

Thanks

**Comment by amit-markupdesigns** [comment]
Hi m2 assistant,

1) Third party api doesn't authorize
2) Information on your environment
=>PHP Version 7.1.33
=>System | Linux ip-xx-xxx-xxx-x.ip.secureserver.net 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64
=>Server API | CGI/FastCGI
3) Steps to reproduce
https://cartrover.atlassian.net/wiki/spaces/CART/pages/3997758/Setting+Up+Magento+2
4) Expected and actual results
![image](https://user-images.githubusercontent.com/57893585/69038935-eec71380-0a10-11ea-9c91-9a096cb97b52.png)

please can anyone help me.

thanks

**Comment by engcom-Echo** [comment]
Hello @amit-markupdesigns 

Thank you for contribution and collaboration!

This is related with CartRover is third party extension and not included in magento by default.
Please refer to the [CartRover support](https://www.cartrover.com/contact.php), for advice or general discussion about this issue.

So I have to close this issue.
Thanks for your report!

**Comment by amit-markupdesigns** [comment]
Hi engcom-Echo,

This issue not from cartrover whatever used another website is working fine. And cartrover is already support for this issue but not now any conclusion.

I thing, also issue here either magento 2 or server.

Thanks
Amit
