### ISSUE TITLE
Performance issue on category page with configurable product

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#25636]
### Preconditions (*)

1. latest Magento
2. category page contains some configurable product 

### Steps to reproduce (*)

1. go to a category page and you will it will load individual product 

### Expected result (*)

1. it should use collection data no need to load product
2. it should implement same like bundle product

Bundle Product Plugin:- 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Bundle/Model/Plugin/Product.php#L36

Configurable product plugin
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/Model/Plugin/ProductIdentitiesExtender.php#L50

on line 50, where the product is loaded and it will down performance of the product list page

### Actual result (*)

1. it is loading parent product

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25636-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25636-2-3-develop.instances.magento-community.engineering/admin](https://i-25636-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29008` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jlenzstaysafe** [comment]
Config products continue to be unacceptably slow.  On a category with 40 config products, load times are astronomically high.  Even on Magento 2.4.3 EE.
