### ISSUE TITLE
Where is the 2.3.3 hotfix?

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#25645]
### Preconditions (*)

> Important hotfix for Magento Open Source 2.3.3
> A hotfix for Magento Open Source 2.3.3 has been published to address an issue related to Elasticsearch that may present itself during or after upgrading to our latest 2.3.3 release. We strongly recommend that everyone upgrading to 2.3.3, download and apply this hotfix prior to deployment. For more information please visit our release notes. https://devdocs.magento.com/guides/v2.3/release-notes/bk-release-notes.html 

### Steps to reproduce (*)

1. Login to admin
2. Be greeted by yellow popup regarding 2.3.3 hotfix
3. Spend hours looking for it
4. Go to github and ask

### Expected result (*)

Link to hotfix in message.

### Actual result (*)

Link to some wiki page that does not contain any information regarding a hotfix for 2.3.3 or where to find it.

**Comment by jorgb90** [comment]
@Zyles Here you go https://magento.com/tech-resources/download?_ga=2.145851831.286978101.1574107906-349907245.1574107906#download2331

**Comment by Zyles** [comment]
I need to download these patches instead of using composer to update?

**Comment by jorgb90** [comment]
Yes download en patch (https://devdocs.magento.com/guides/v2.3/comp-mgr/patching.html), but this patch is so small that you can even open it and see what changes you need to apply so you can do it manually.

**Comment by Zyles** [comment]
Thanks I have applied it manually. The docs were incorrect as well on how to apply patching.

Should be: `patch -p1 < patch_file_name.patch`
