### ISSUE TITLE
Catalog Price Rule on configurable products not showing incorrect

### ISSUE THREAD

**Issue by cafefin** [magento/magento2#25649]
### Preconditions (*)

1. Magento 2.2.3 EE
2. PHP 7.0.33

### Steps to reproduce 

1. Create a discount rule based on attribute set which have configurable products
2. Save & Apply rule
3. Run command reindex to apply catalog price rules
4. Open Backend Magento 2 : Go to Customers -> All customers -> Choosen one customer ->
5. Click Manage Shoping Cart -> Selected product has discount rule ->  Click " Add selections to my cart " .

### Expected result 

1. Product has been added showing correct price with discount rule. ( Discount 30% )

![ATIZLYOeTmauLHkGy6A-qA](https://user-images.githubusercontent.com/33374759/69131914-9dd51f00-0ae5-11ea-8128-23686eaeff80.png)

### Actual result 
![QquC5fstQSaBG8jhAywhIg](https://user-images.githubusercontent.com/33374759/69131686-4e8eee80-0ae5-11ea-8803-6e25eb3de716.png)

1. Price product showing base price

**Comment by cafefin** [comment]
@magento give me 2.2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cafefin. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by cafefin** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cafefin. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cafefin, here is your [Magento instance](https://i-25649-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25649-2-3-develop.instances.magento-community.engineering/admin](https://i-25649-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25649-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25649-2-3-develop.instances.magento-community.engineering/admin](https://i-25649-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cafefin** [comment]
Hi , Just update some information, i found my solution same https://github.com/magento/magento2/issues/13476

**Comment by ajijshekh123** [comment]
Okay @cafefin, Let me close this issue.
This issue is duplicate #13476

Thanks for the Update @cafefin.
