### ISSUE TITLE
Backend M 2.3.3 > Missing configuration field "Use SID on Storefront"

### ISSUE THREAD

**Issue by angelflo** [magento/magento2#25663]
Hi,

I use SID to share basket for multi-websites but since last update on M 2.3.3 AND on M 2.2.10 the configuration field relative to this in the backend : "Use SID on Storefront" is missing and all my custom work stop working.

I can't find any information about this modification in forum, neither relese note.
Please can you tell me why this option suddently disapear ? is it a bug ?

Without this, my custom dev can't share order info between different websites domain name.

Thanks a lot for your help.

**Comment by ihor-sviziev** [comment]
Hi @angelflo,
AFAIK it was removed due to security reasons.

Could you describe use case when it's needed?

**Comment by angelflo** [comment]
It's needed when we use multiple website feature (rootdomain.com, domain1.com, domain2.com)
and when I need to centralise all the payment from a secure domain via rootdomain.com). 
So after saving the order in the corresponding website (for exemple domain1.com), i need to redirect to the SSL secured domain rootdomain.com who's approuved by our payment provider.
It seeems that without this SID param, I now can't share the order info with the rootdomain !

**Comment by ihor-sviziev** [comment]
This parameter was removed due to security reasons, I don’t believe it will
be added back, as security is more important.

What you describe - looks really custom flow. I suggest you to have SSL
certificates on all domains, for instance using Letsencrypt.

**Comment by angelflo** [comment]
Hi again,
Thanks a lot but we choose Magento especially because it's modular and allow this specific feature and we invest a lot in extensions + custom dev on this solution, now it's to late for us to switch on prestashop !
I really don't understand why Magento team remove it ... I can totally understand that it can create security breach but in specific situation it's really mandatory, this is why the solution where people can choose to enable or disable it (like this is the case previously) seems to be the good solution. 
I'm ok with you to disable it by default , but leave the choice to enable it if it's really mandatory for some specific case.
Also, thanks a lot for your suggestion with letsencrypt, but it doesn't fit what we need for our business...
Please, leave the choice to people to choose by himself between high security or medium ... this is exactly the same than if I block all ports on firewall ... i improve security but I can't use web server, if I allow traffic I add some risk but I can do business.

**Comment by ihor-sviziev** [comment]
In this case you could customize magento functionality to bring this
feature back for you

**Comment by angelflo** [comment]
does your code is still active ? can I force re-enable it easly (with just
one param ?)

Le mer. 20 nov. 2019 à 17:17, Ihor Sviziev <notifications@github.com> a
écrit :

> In this case you could customize magento functionality to bring this
> feature back for you
>

**Comment by ihor-sviziev** [comment]
I didn’t investigated how to add it back. You could review changes from
2.3.2 till 2.3.2-p2 ( there only security changes included) and see what
exactly was changed and just bring it back for you

**Comment by angelflo** [comment]
thanks for your reply ... i really hope that you'll take my suggestion in consideration and re-enable this feature on next update to leave the choice to your customers to manage their "risk vs feature" and not only destroy some things who work well since Magento 1 :-(

I can't invest again to re-anlayse and patch all the source code and create new problems after each update of magento because i use custom code. 

It was so easy to have enable/disable with disable by default ...

**Comment by ihor-sviziev** [comment]
Hi @angelflo,
Unfortunately it's not I did this decision to remove this option at all.
I even don't have details why it was removed, just know that it was as part of security patch, so it was removed because of some issue.

UPDATE: I wasn't correct, it was enabled by default. This code was removed as part of https://github.com/magento/magento2/commit/fe7fbce272c0c0fdd06b7eaadede0bd18cfe8212.
So you could review these changes and updated your code accordingly

**Comment by engcom-Charlie** [comment]
Hello @angelflo @ihor-sviziev 
I guess we can close this issue as non-issue & not actual.
Thank you for contribution and collaboration!

**Comment by 83rnd** [comment]
> thanks for your reply ... i really hope that you'll take my suggestion in consideration and re-enable this feature on next update to leave the choice to your customers to manage their "risk vs feature" and not only destroy some things who work well since Magento 1 :-(
> 
> I can't invest again to re-anlayse and patch all the source code and create new problems after each update of magento because i use custom code.
> 
> It was so easy to have enable/disable with disable by default ...

Hi, how did you fix your problem?

**Comment by duffner** [comment]
@magento-engcom-team, @engcom-Charlie, this is a critical feature of Magento, it's probably one of the main features which still make Magento more feature-rich than other platforms.  

This removal impacts almost every Commerce Edition Customer we maintain. Without this support, these customers have no reason to stay on Magento.  This is a huge SALES issue, please fix it immediately!

**Comment by collymore** [comment]
We've come up with a solution which I believe is more secure then the standard SID param sharing. 

When the user visits a page we make an AJAX request to a controller that gets the visitors session ID and encrypts it with the visitors IP address and a salt.

This encrypted string is then returned and appended to any cross store URL links on the page as a query parameter. 

So when a visitor clicks a cross store url we check for this parameter and decrypt the string with their IP address as the key and then set the Session ID so the session is restored.

The encrypted string can't be decoded without the key, so it won't work for session hijacking as  it can only be decrypted on the server with the IP address of the user as the key that generated it.

Hope this helps someone or does anyone see any problems with this approach?

**Comment by angelflo** [comment]
Hi, 

Please can someone tell me if the code to share the SID between multiple websites is still present in the code of magento 2.4.2 and if I can re-enabe it to restore this logic ?
Do you know what files was in charge of this feature in the previous version ?

@collymore : do you think you can share your custom code with the community ?

Thanks a lot to all people who can help me restore something who work to tranfert the SID between multiple domains on the same magento install.

King regards

**Comment by rimom** [comment]
> We've come up with a solution which I believe is more secure then the standard SID param sharing. 
> 
> When the user visits a page we make an AJAX request to a controller that gets the visitors session ID and encrypts it with the visitors IP address and a salt.
> 
> This encrypted string is then returned and appended to any cross store URL links on the page as a query parameter.
> 
> So when a visitor clicks a cross store url we check for this parameter and decrypt the string with their IP address as the key and then set the Session ID so the session is restored.
> 
> The encrypted string can't be decoded without the key, so it won't work for session hijacking as  it can only be decrypted on the server with the IP address of the user as the key that generated it.
> 
> Hope this helps someone or does anyone see any problems with this approach?

This is a very smart solution, however, please be aware that by doing this, you fail to be PCI compliant and may be subject to severe fines that could cost your entire business.

**Comment by collymore** [comment]
> > We've come up with a solution which I believe is more secure then the standard SID param sharing. 
> > When the user visits a page we make an AJAX request to a controller that gets the visitors session ID and encrypts it with the visitors IP address and a salt.
> > This encrypted string is then returned and appended to any cross store URL links on the page as a query parameter.
> > So when a visitor clicks a cross store url we check for this parameter and decrypt the string with their IP address as the key and then set the Session ID so the session is restored.
> > The encrypted string can't be decoded without the key, so it won't work for session hijacking as  it can only be decrypted on the server with the IP address of the user as the key that generated it.
> > Hope this helps someone or does anyone see any problems with this approach?
> 
> This is a very smart solution, however, please be aware that by doing this, you fail to be PCI compliant and may be subject to severe fines that could cost your entire business.

On what basis would you fail PCI compliance for using this code?

**Comment by rimom** [comment]
> > > We've come up with a solution which I believe is more secure then the standard SID param sharing. 
> > > When the user visits a page we make an AJAX request to a controller that gets the visitors session ID and encrypts it with the visitors IP address and a salt.
> > > This encrypted string is then returned and appended to any cross store URL links on the page as a query parameter.
> > > So when a visitor clicks a cross store url we check for this parameter and decrypt the string with their IP address as the key and then set the Session ID so the session is restored.
> > > The encrypted string can't be decoded without the key, so it won't work for session hijacking as  it can only be decrypted on the server with the IP address of the user as the key that generated it.
> > > Hope this helps someone or does anyone see any problems with this approach?
> > 
> > 
> > This is a very smart solution, however, please be aware that by doing this, you fail to be PCI compliant and may be subject to severe fines that could cost your entire business.
> 
> On what basis would you fail PCI compliance for using this code?

My base is PCI DSS v3.2 Requirement 6.5.10:
> Examine software development policies and procedures and interview responsible personnel to verify that broken authentication and session management are addressed via coding techniques that commonly include:
> - Flagging session tokens (for example cookies) as “secure”
> - Not exposing session IDs in the URL
> - Incorporating appropriate time-outs and rotation of session IDs after a successful login.
But actually, looking at it properly, it seems that there is a kind of a "gray area" on this statement. If your solution complies with the requirements above, theoretically you should have no problem. I would consult a Qualified Security Assessor first just in case.
