### ISSUE TITLE
Magento 2 Store Code validation regex: doesn't support uppercase letters in scope code

### ISSUE THREAD

**Issue by attheCube** [magento/magento2#25668]
### Preconditions (*)

1. Magento v2.3.3
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Setup stores/store-groups/websites with uppercase scope codes via setup script.
2. Try to use to show configuration for this store via console. <br>=> bin/magento config:show --scope=store --scope-code=de_AT

### Expected result (*)

1. Output of store configuration

### Actual result (*)

1. Output of error message:<br>"The scope code can include only lowercase letters (a-z), numbers (0-9) and underscores (_). Also, the first character must be a letter."

Similar report: https://github.com/magento/magento2/issues/11996

This report resulted in adjustment of the error message because the former reporter had no good reason.

One good reason why it should be possible to use uppercase letters in store code, is to differentiate regions in store code. Especially for using storecodes within url.
So you could use at least 'de_DE', 'de_AT', 'en_US' or 'en_UK' as store codes, which is very useful in urls.

To be RFC 4646 (https://tools.ietf.org/html/rfc4646) conform, there has to be the possibility to use hyphens for store codes, too.

Surely it would be possible to do something weird by having this possibility, but that lies in the responsibility of the projects lead.

### Additonal information:
See [comment](https://github.com/magento/magento2/issues/25668#issuecomment-719513986)

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25668-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25668-2-3-develop.instances.magento-community.engineering/admin](https://i-25668-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by attheCube** [comment]
Hi,
thanks for the instance to test.
In administration and in frontend no message are thrown in this instance.
But the message is thrown while using bin/magento config:show --scope=stores --scope-code=de_AT as I mentioned above and I don't have access to console to test.

The error message is thrown in the following files:
- vendor/magento/framework/App/Config/Scope/Validator.php
- vendor/magento/framework/App/Scope/Validator.php

The regular expression in these files does not allow uppercase characters.

It seems that this validation functionality is not used for saving scopes and using store codes in url, but it is used for the config-command and may be for setting store-codes via environment variables also.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29015` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AnnaShepa** [comment]
@attheCube  thank you for update, I managed to reproduce it as well
One more note: when I tried to change store name from admin BO, on save I've got the same error, but it was saved.

**Comment by ihor-sviziev** [comment]
Hi @attheCube @Usik2203,

Changing of this behavior could negatively affect some merchants, but I can't see any reason why we do need to change it, except just because we want to.
Actually store code IS NOT the same as lang code. Could you explain your use case, why you can't use for instance `de_at` instead of `de_AT`?

**Comment by attheCube** [comment]
Hi @ihor-sviziev ,

I know that store code is not the same lang code or better locale code. 
But if you use the store code in URL it's easier recognizing to whom this shop belongs by using well known standards. 
In fact our customer stills uses this standard for his website and besides the reason said before, it's more convenient for the customers not to be confused by changing this system.

Btw. why should merchants negatively affected by open the store code for usage of uppercase letters. As long as they do not willingly change their store codes, nothing will change for them?

**Comment by ihor-sviziev** [comment]
Hi @attheCube,
Such change will not bring any value for most of the customers, while will add additional cases that weren’t happening earlier, for instance in custom extension.

We talked with @lenaorobei and agreed that it’s better not to accept such change due to potential issues and too small value.

If you really need it - you still could adjust this behavior for your project(s) by writing custom extension.

Thank you for collaborating!

**Comment by lano-vargas** [comment]
2.3.4 still not allowing

**Comment by ihor-sviziev** [comment]
> 2.3.4 still not allowing

Hi we decided not to fix it. More details https://github.com/magento/magento2/issues/25668#issuecomment-608628584

**Comment by robolmos** [comment]
I wasn't clear on what the fix ended up being. What's the fix? The admin/backend allows uppercase store/website codes, but the command line doesn't. 

Thus, codes can be created in the admin/backend that can't be interacted with via config:set, config:show scope-code argument on the command line, which seems like a bug IMO.

Seems like the fix should be allowing the command line to use the same regex validation that the admin/backend uses, which is what the pull request supplied, right?

**Comment by ihor-sviziev** [comment]
@robolmos hm... interesting... I though it's just not supported everywhere... **I'm re-opening this issue.**

In case if it's supported from the admin - we should allow it also here. Could you create PR for fixing this consistency issue?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39077` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
