### ISSUE TITLE
Group Pricing Is Removed Once Exiting / Editing or removing from Cart

### ISSUE THREAD

**Issue by canofpopcom** [magento/magento2#25660]
#25359 # Preconditions (*)

1. 2.7.3

### Steps to reproduce (*)

First Login - Special Price (using plugin - latest version working well)

![Screenshot 2019-11-18 at 14 47 10](https://user-images.githubusercontent.com/1219059/69187553-b7d92680-0b12-11ea-82ee-eb0999abcbc2.png)

Viewing Product with discount - no problem:

![Screenshot 2019-11-18 at 14 47 58](https://user-images.githubusercontent.com/1219059/69187612-dc350300-0b12-11ea-88d9-722747d030b0.png)

Adding to Cart Fine:

![Screenshot 2019-11-18 at 14 48 24](https://user-images.githubusercontent.com/1219059/69187636-ee16a600-0b12-11ea-8578-4736abfeac49.png)

Cart View and Checkout all good too.

![Screenshot 2019-11-18 at 14 48 51](https://user-images.githubusercontent.com/1219059/69187663-f66ee100-0b12-11ea-9246-b076bde2b09d.png)

The issue occurs when going back out to store, special pricing is removed:

![Screenshot 2019-11-18 at 14 49 12](https://user-images.githubusercontent.com/1219059/69187765-20280800-0b13-11ea-84ef-944c2b53d53c.png)

### Expected result (*)

Discount / Customer Group Prices remains

### Actual result (*)
RRP / Normal Price remains on store / product view despite user being in Customer Group, persistence cart is set to config / on.

![Screenshot 2019-11-18 at 14 49 25](https://user-images.githubusercontent.com/1219059/69187875-4fd71000-0b13-11ea-8daa-4a9d6c19add3.png)

The good news is that once the product is added the discount is applied again at checkout but from a B2B customer perspective this isn't great as the discount seems to disappear.

We originally thought it was an issue with the plugin but this has been updated to 2.3.0 so have ruled out the issue here and we're trying to understand if we need to update Magento to the latest re:

https://github.com/magento/magento2/issues/22629 

We are however blocked by our Mircosoft Dynamics Plugin that at this time doesn't go past 2.7.3.

Many thanks

Andy

**Comment by canofpopcom** [comment]
I've managed to reproduce the issue on @magento give me 2.2.7 with Special Pricing Plugin installed: https://marketplace.magento.com/mageworx-module-customerpricesmeta.html

**Comment by AnnaShepa** [comment]
Hi @canofpopcom thank you for the report. As it was mentioned in #22629 the issue isn't reproducible in Magento 2.3 and I checked it one more time now with simple, configurable, grouped and bundle products.  I would recommend you to update Magento to version 2.3.
