### ISSUE TITLE
\Magento\MediaStorage\Model\File\Storage\Synchronization::synchronize() suppresses its exceptions for a questionably reason

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2566]
https://mage2.pro/t/271

See also: https://github.com/magento/magento2/issues/2558

**Comment by oserediuk** [comment]
Hello! To allow us research the issue, please, provide description according to the template.
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
