### ISSUE TITLE
Method checkIsAllRequiredOptions for Bundle product allows option without actual value

### ISSUE THREAD

**Issue by karyna-t** [magento/magento2#25676]
This issue is related to https://github.com/magento/graphql-ce/issues/1039

Case: Bundle product, one of the required options has type  Multiple Select.
It is possible to add the product to a Cart without this option selected, for example via graphql query (no front-end validation in this case).
![no-value](https://user-images.githubusercontent.com/55278634/69268165-49aa6780-0bd7-11ea-9377-ab3fa911bb10.png)

### Preconditions (*)

1. Magento ver. dev-2.3-develop

### Steps to reproduce (*)

Steps are described in details in this ticket https://github.com/magento/graphql-ce/issues/1039

### Expected result (*)
Exception 'Please select all required options.' should be thrown.

### Actual result (*)
Product was added to the quote without required option.

**Comment by magento-engcom-team** [comment]
@drpayyne Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @drpayyne 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29032` were created

**Issue Available**: @drpayyne, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
