### ISSUE TITLE
Authorize.net Acceptjs not checking transactional fields if they are too long

### ISSUE THREAD

**Issue by simonlandry0** [magento/magento2#25689]
### Preconditions (*)

1. Magento 2.3.3 or 2.3-develop installed
2. Authorize.net Accept JS installed and configured with API keys.

### Steps to reproduce (*)

1. Add something to cart and proceed to checkout
2. Enter a company name that is more than 50 characters long
3. Attempt to complete the payment

### Expected result (*)

1. It should refuse letting the user know that the company field can only have 50 characters.
2. Should also check the other field's lengths (first name, last name, address...). Should not exceed the max length referenced in the documentation https://developer.authorize.net/api/reference/#customer-profiles-create-customer-profile

### Actual result (*)

1. Gives out a generic error ("Invalid request to gateway.")
![image](https://user-images.githubusercontent.com/51680850/69415273-fe01d600-0d1c-11ea-9608-46dab0231491.png)

2. It will actually post the request to Authorize.net and generate a email report about the failed transaction.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29068` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
Hi @simonlandry0,
According to following announcement this extension was already removed from 2.4 version:
https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445

All future collaboration related to this extension should be on Marketplace using "Contacts" or "Bug reports" related to this extension.

I'm closing this issue.
