### ISSUE TITLE
Changes to one catalog price rule result in all catalog price rules being re-indexed

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#25687]
### Preconditions
1. Magento 2.3.3
2. [Indexing mode](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexing.html#m2devgde-indexing-modes) set to Update by Schedule

### Steps to reproduce
1. Make a change to a single catalog price rule
2. Run the index cron in order to generate [Mviews](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/indexing.html#m2devgde-mview) (e.g.  `magento cron:run --group=index`)

### Expected result
A change to one catalog price rule results in only that one catalog price rule being re-indexed.

### Actual result
A change to one catalog price rule results in all catalog price rules being re-indexed.

This is because at [app/code/Magento/CatalogRule/Model/Indexer/Rule/RuleProductIndexer.php the doExecuteList() function](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/Model/Indexer/Rule/RuleProductIndexer.php#L17) does a [full re-index](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/Model/Indexer/Rule/RuleProductIndexer.php#L19).

See [Magento/Framework/Mview/Processor::update()](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/Processor.php#L44) which calls [Magento/Framework/Mview/View::update()](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L241), generating the [full re-index](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L308). 

This is also by default done ([in batches of 1,000](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L28)). With 10,000 catalog price rules, this results in 10 full re-indexes of all prices, despite only one catalog price rule change. 

This can significantly increase server loads as during a full re-index, [every product is validated against every rule](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/Model/Indexer/ReindexRuleProduct.php#L82).

**Comment by engcom-Charlie** [comment]
Hello @jameswithers 
I can't confirm your issue because it is not valid to do re-index only for one catalog price rule.

**Explanation:**
for example you have 3 same catalog price rules with different discount % assigned to same products: 
`catalogrule` table:

![image](https://user-images.githubusercontent.com/51680850/69422486-820f8a00-0d2c-11ea-9607-e21d4d2e1141.png)

`catalog_product_index_price` table:
![image](https://user-images.githubusercontent.com/51680850/69422685-f5b19700-0d2c-11ea-82bf-4044d8ff3597.png)

These rules have different sort orders.
And when you wanted to change the value of sort order of third rule to 0 and did it, will be processed re-index only to this rule. That re-index can't be successfully finished without re-calculating `final price` of those products(need to do full re-index of all rules for it), because the third rule have to be calculated first and than other rules. 

So i have to close this issue as non-issue.
Thanks for your report!

**Comment by jameswithers** [comment]
@engcom-Charlie I now understand it is valid to re-index all catalog price rules in case there are sort orders.

What remains invalid is that - [as materialized views are processed in batches](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L307) - a full re-index is [generated every 1,000 records](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L295) - regardless of the number of catalog price rules.

This means for 10,000 catalog price rules, when one changes there are 10 (10,000 divided by [DEFAULT_BATCH_SIZE](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L28)) full re-indexes, 9 of which are redundant.

A [dependency injection can be used](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L86) to [set the batch size for catalog price rules](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L295) (to 10,000 for example), though this requires a code modification on each Magento installation.

**Comment by engcom-Charlie** [comment]
@jameswithers Thank you for contribution and collaboration!
I think your issue can be approved only like a feature request. 
So it is not for this tracker. 
Hello @sdzhepa . Could you transfer this issue to the feature requests repository?

**Comment by jameswithers** [comment]
> @jameswithers Thank you for contribution and collaboration!
> I think your issue can be approved only like a feature request.
> So it is not for this tracker.
> Hello @sdzhepa . Could you transfer this issue to the feature requests repository?

@engcom-Charlie so for confirmation: it is expected behaviour in Magento that a change to one catalog price rule will - when there are more than 1,000 catalog price rules - result in multiple re-indexes of the same data in sequence?

**Comment by engcom-Charlie** [comment]
@jameswithers yes, for now

**Comment by jameswithers** [comment]
> @jameswithers yes, for now

[The addition of the following in the indexer di.xml](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Indexer/etc/di.xml) is all that is needed (it's called [here](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L295)):

```
<config>
    <type name="Magento\Framework\Mview\View">
        <arguments>
            <argument name="changelogBatchSize" xsi:type="array">
                <item name="catalogrule_rule" xsi:type="string">100000</item>
                <item name="catalogrule_product" xsi:type="string">100000</item>
            </argument>
        </arguments>
    </type>
</config>
```

The 100,000 figure [comes from the max version query batch](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Mview/View.php#L33)

Can I submit the above as a pull request against this issue?

**Comment by engcom-Charlie** [comment]
@jameswithers yes, after this issue will be transferred to the feature requests repository

**Comment by jameswithers** [comment]
@engcom-Charlie 

The default Magento logic appears to do a re-index twice, [notwithstanding changes to the changelogBatchSize](https://github.com/magento/magento2/issues/25687#issuecomment-558093137):

1. Saving a catalog price rule invalidates the _catalogrule_rule_, _catalog_product_price_, and _catalogsearch_fulltext_ indexes, as well as MySQL triggers adding an entry to the `catalogrule_rule_cl`
2. [The Magento cron re-indexes invalid indexes first](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Indexer/etc/crontab.xml#L10)
3. As an entry has been added to `catalogrule_rule_cl`, the [next cron job](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Indexer/etc/crontab.xml#L13) (after the above) also [does a full re-index](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/Model/Indexer/Rule/RuleProductIndexer.php#L19).

**Comment by zkliouel** [comment]
@jameswithers and @engcom-Charlie
Hi all,
why do not only reindex products that matching the catalogRule ?
I mean instead of invalidate catalog_product_price and catalogsearch_fulltext that trigger a full reindex of all products, whe we don't only launch reindex in afterSave method of https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/Model/Rule.php#L589 for only matching products ids ?
