### ISSUE TITLE
Magento 2 - Catalog products disappear from frontend listings page when custom attribute is set to No on Used in Product Listing

### ISSUE THREAD

**Issue by iamrobreynolds** [magento/magento2#2568]
Magento 2.0.0 GA

Replicate problem:
1. Create a new attribute (size){text swatch} and add it to a Custom attribute set
2. Create a new simple product and then select Configurations and use new attribute (size), then save
3. Go back to edit the newly created attribute (size), and try to set "Used in Product Listing" to "No", then save (the select field goes back to "Yes") and product disappears from frontend catalog pages.

Related note: Unable to change values from "Yes" to "No" of the following fields on a custom attribute:
Visible on Catalog Pages on Storefront
Used in Product Listing

This seems to be a related issue discussed on StackExchange -> http://magento.stackexchange.com/questions/88081/magento2-products-suddenly-disappeared-on-frontend/92155

**Comment by vzabaznov** [comment]
seems like it cannot be reproduced on current version on magneto, @robbiereynolds please can you re-check this info?

**Comment by vzabaznov** [comment]
@robbiereynolds  thanks for reporting..
Fell free to write comment, or open a new GitHub issue if you feel that issue has not been resolved

**Comment by cbrews** [comment]
Hey @robbiereynolds, what was the version of Magento2 that you saw this on?

**Comment by rudy1976s** [comment]
I think I have a similar issue: after importing products from Magento 1.9.2 using official tool, I am not able to see any product in frontend: I have tried almost every solution found on the web, from reindexing, clearing cache and copied all the files again and again: in DB products are linked to website.

**Comment by deduoffice** [comment]
I think i have a problem similar like this in Magento CE 1.9.3.1 with the products not showing up in the catalog on the frontend and in the productsearch.

I am not a programmer and i dont have access to a shell with a command prompt to execute programs for on the server.

I have this issue also running on Magento Stackexchange: http://magento.stackexchange.com/questions/149945/is-magento-playing-with-me-products-are-not-showing-up-on-frontpage-in-the-cata

I hope you can help me out. 
If someone could help me out i would be very happy. I dont want to start all over again (for the 5th time). If so reply to me if you need some logindata for the server and the backoffice to inspect it deeper.

I ran out of options for what i can do myself.
I put all the options on to be visible on the frontoffice concerning websites, product options, catalog options, reindexing and flush caches.

Please help.

**Comment by shansari25** [comment]
Im facing this issue in Magento 2.2.4 - products disappeared after reindex. Pls suggest a solution.

Magento is seriously a very bad tool, i made a big mistake, i have gone through several issues. And now this one and no patch and no solution anywhere.
