### ISSUE TITLE
Inventory Reservation not taken into account when setting Product out of Stock

### ISSUE THREAD

**Issue by stkrelax** [magento/magento2#25696]
### Preconditions (*)

1. Magento 2.3.2
2. MSI with default Stock only ( default stock only is not a must but MSI is)

### Steps to reproduce (*)
1. set up one Product with qty 1 salable 
2. complete an order buying the product (a new entry in inventory_reservation was made)
3. post /V1/inventory/source-items set Product to qty 0 and status 0 (simulating the client updating the stock because it was purchased by you)
4. in admin or api try to ship the order.

### Expected result (*)
1. the order gets shipped

### Actual result (*)
1. Exception "Not all of your products are available in the requested quantity."
The Reason therefor is that normally without the clients update of the product the qty of the product would have been 1 and the shipping would have set it to 0. 
Now that the product has qty 0, magento is unable to substract the reservations. 

### Suggestion (*)
When updating a products qty the reservations should be included. So in this case the aty 0 would have become qty 1.

### Related 
https://github.com/magento/inventory/issues/2073
https://github.com/magento/magento2/issues/21646
https://github.com/magento/inventory/issues/2725

**Comment by engcom-Echo** [comment]
Hello @stkrelax 

The same [ticket](https://github.com/magento/inventory/issues/2725) has already been created and moved to the MSI repository.
So I close it.
