### ISSUE TITLE
Issue 404 Not found if there is an apostrophe in URL key

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25698]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Create a Product with URL key with **'** (apostrophe) like _te'st_
![Screenshot_552](https://user-images.githubusercontent.com/42089978/69420935-c4919080-0d45-11ea-95f1-374deb592172.png)
2. Search the product in front end and click on it.

### Expected result (*)
1. Should redirect to Product View page

### Actual result (*)
1.  Redirecting to "404 Not Found" Whoops, our bad... page
![Screenshot_553](https://user-images.githubusercontent.com/42089978/69420993-e2f78c00-0d45-11ea-8020-494743f53c97.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25698-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25698-2-3-develop.instances.magento-community.engineering/admin](https://i-25698-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29070` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by akondratenkeo** [comment]
@magento I am working on it

**Comment by andrewbess** [comment]
Hello @alexkwellbe 
Do you working on it?
Please assign this issue to yourself.

**Comment by sargan89** [comment]
#cdkharkiv19nov

**Comment by magento-engcom-team** [comment]
@sargan89 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sargan89** [comment]
Hi @sanjaychouhan-webkul. I couldn't identify the problem.
![Screenshot](https://user-images.githubusercontent.com/10529321/69477914-b6e71400-0df4-11ea-953b-d6853ba35b54.png)
You should do reindex command in the console and clear cache:
`php bin/magento indexer:reindex
php bin/magento cache:clean`

**Comment by Den4ik** [comment]
@sanjaychouhan-webkul Issue not reproduced on 2.3-develop branch. Looks like you have problems in url_rewrites table.
@sargan89 Magento regenerate index on save events. Reindex don't update url_rewrites table
