### ISSUE TITLE
RequireJs is not resolving CDN path for some js files

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#25690]
### Summary (*)
When we install an extension which requires a CDN file through the file `requirejs-config.js`, and our store is using production mode, the compilation changes the js path, including **.min**, so getting an error 404.

### Examples (*)
It's an example, https://github.com/rafaelstz/magento2-quicklink

### Proposed solution
I think it's related with the requirejs configuration when its compile everything, I was doing some researches and I found these links that can help with it.

- https://stackoverflow.com/a/49404783/2525701
- https://github.com/requirejs/requirejs/issues/1544
- https://requirejs.org/docs/api.html

**Comment by krzksz** [comment]
I can confirm that links outside of `baseUrl` are getting transformed with `min.js`/`min.css` suffix:
<img width="328" alt="obraz" src="https://user-images.githubusercontent.com/829189/69465300-17d50480-0d81-11ea-8aed-a3882c9ea821.png">

**Comment by magento-engcom-team** [comment]
@krzksz Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@krzksz Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krzksz 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29104` were created

**Issue Available**: @krzksz, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @rafaelstz. Thank you for your report. 
The issue has been fixed in magento/magento2#25869 by @krzksz in 2.3-develop branch
Related commit(s):
 - [23f0ced28aa4c065a771bcb0ec6368b8e85059aa](https://github.com/magento/magento2/commit/23f0ced28aa4c065a771bcb0ec6368b8e85059aa)

The fix will be available with the upcoming 2.3.5 release.
