### ISSUE TITLE
Payment gets captured in PayPal Payflow pro but order not created in Magento 2

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#25708]
### Preconditions (*)

1. Magento open source 2.3.3
2. PayPal Payflow Pro payment method configured either in the sandbox mode or live

### Steps to reproduce (*)

1. You need to throw an exception between order place call and order save call, edit file **vendor/magento/module-sales/Model/Service/OrderService.php**
and place below code before line#216 ($order = $this->orderRepository->save($order);)

`throw new \Magento\Framework\Exception\LocalizedException(__('Test error to interrupt order save'));`

2. Add any product to the cart at the storefront and go to the checkout. 
3. Select 'Credit card' payment method. Enter card details test/live based on if the method is configured in sandbox mode or live
![credire-card](https://user-images.githubusercontent.com/5336201/69474313-99f71480-0de5-11ea-8990-f276a1f9df79.png)

4. An exception "Test error to interrupt order save" will be thrown after clicking the 'Place Order' button
![error](https://user-images.githubusercontent.com/5336201/69474324-c6ab2c00-0de5-11ea-9d02-e247b8d9487e.png)

5. Now go to PayPal Manager(https://manager.paypal.com/) and you will see capture transaction there
6. But when you log in to the Magento admin there no order for this transaction

### Expected result (*)

1. Payment shouldn't be captured if the order fails to save
2. The error should be handled correctly if any occurs during the order save process.

### Actual result (*)

1. Payment captured but there is no order in the Magento admin

P.S. I know in this case, we threw the error ourselves, this is just to simulate an unexpected error during order save. As in a production environment, there can be many scenarios when an error can occur during order save call. 

For example in the worst scenario, the server crashed during code $order = $this->orderRepository->save($order);

In that case, payment is captured but there is no order in Magento.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29125` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bijalbhavsar** [comment]
We are facing the same issue with live website after upgrading Magento 2.3.1 to Magento 2.3.3

**Comment by serzhik** [comment]
It’s related to https://github.com/magento/magento2/issues/25862

**Comment by rav-redchamps** [comment]
> It’s related to #25862

Nope, it’s not specifically related to that issue.

This issue describes a general problem that in magento 2 core order is saved after payment processing. So, any scenario that breaks the order save call will cause this problem.

There can be thousands of such scenarios which can break the order save call and referenced issue only describes only one of the case.
