### ISSUE TITLE
Need margin bottom to new Widget in Checkout/Cart Summary box

### ISSUE THREAD

**Issue by fabriciosobral** [magento/magento2#25703]
### Preconditions (*)

1. Clean install Magento 2.3.3 Commerce
2. Sample data installed via composer
### Steps to reproduce (*)

1. Create one new BLOCK with text into this
![screenshot-local magento com br-2019 11 (2)](https://user-images.githubusercontent.com/51653844/69438292-88e5cf00-0d23-11ea-989d-83c0c1e3c0f0.png)

2. Create one new WIDGET 
![magento-dev1](https://user-images.githubusercontent.com/51653844/69437669-82a32300-0d22-11ea-90b8-9d44112a26a6.png)
3. Attributed the block in Widget Options
![screenshot-local magento com br-2019 11 (1)](https://user-images.githubusercontent.com/51653844/69437958-06f5a600-0d23-11ea-9883-3e831b4cb9bf.png)
4. Then make login
5. Add product in your Cart
6. Go to your cart and then "VIEW AND EDIT CART"
![screenshot-local magento com br-2019 11 (3)](https://user-images.githubusercontent.com/51653844/69438465-d3ffe200-0d23-11ea-82bc-219f9fc9a186.png)

### Expected result (*)

The text need margin bottom like this
![screenshot-live browserstack com-2019 11 (1)](https://user-images.githubusercontent.com/51653844/69438545-fc87dc00-0d23-11ea-93f0-fbdceee7e66c.png)

### Actual result (*)

The text dosen´t have margin bottom between the button PROCEED TO CHECKOUT

**Comment by fabriciosobral** [comment]
I am working on this issue

**Comment by fabriciosobral** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fabriciosobral. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fabriciosobral, here is your [Magento instance](https://i-25703-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25703-2-3-develop.instances.magento-community.engineering/admin](https://i-25703-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by fabriciosobral** [comment]
Reproduced in 2.3-develop
![screenshot-i-25703-2-3-develop instances magento-community engineering-2019 11](https://user-images.githubusercontent.com/51653844/69440881-60ac9f00-0d28-11ea-8427-0e4ea887abea.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25703-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25703-2-3-develop.instances.magento-community.engineering/admin](https://i-25703-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29175` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by fabriciosobral** [comment]
@niravkrish I was working on it before you, please remove your receipt request please

**Comment by VladimirZaets** [comment]
Hi @fabriciosobral. Thank you for your report. 
The issue has been fixed in magento/magento2#25729 by @fabriciosobral in 2.3-develop branch
Related commit(s):
 - [9b55f0ee31b3b1d68ce7112251d6c12b0f73119f](https://github.com/magento/magento2/commit/9b55f0ee31b3b1d68ce7112251d6c12b0f73119f)
 - [5a8e81589c82b478f95454151e35977a73b260fb](https://github.com/magento/magento2/commit/5a8e81589c82b478f95454151e35977a73b260fb)
 - [1ab336b33d26713f660ae4aade5aae35332a13f5](https://github.com/magento/magento2/commit/1ab336b33d26713f660ae4aade5aae35332a13f5)
 - [c4a3e5158af088b9735ff8c2abdd881960b344ae](https://github.com/magento/magento2/commit/c4a3e5158af088b9735ff8c2abdd881960b344ae)

The fix will be available with the upcoming 2.3.5 release.
