### ISSUE TITLE
Magento2 can not create new module

### ISSUE THREAD

**Issue by xiangkundavis** [magento/magento2#2570]
When I download archive following magento dev documenta, it always give me error like this :4:{i:0;s:58:"Setup version for module 'Tutorials_Page' is not specified";i:1;s:1452:"#0 /var/www/magento2stage2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(56): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Tutorials_Page', false).

When i run command php bin/magento module:enable Inchoo_Stripe --clear-static-content, it always give me error "unknown module".

SO i download magento2 from github and then useing merchant_beta, and create the same module.
When i run the command "php bin/magento module:enable Inchoo_Stripe --clear-static-content", it works

**Comment by xiangkundavis** [comment]
May I ask what is the version of the magento2 installing archive from dev documents ?
What is the tag for this archive?
It is the branch master code?

**Comment by mazhalai** [comment]
@davissuperman do you have module called `Tutorials_Page`? It should have setup_version in `etc/module.xml`
and you are attempting to clear another module `php bin/magento module:enable Inchoo_Stripe`
It should be `php bin/magento module:enable Tutorials_Page` correct?

**Comment by xiangkundavis** [comment]
Yes, ignore this question. I have fixed. it works for me now.
