### ISSUE TITLE
Product swatch doesn't show specific swatch image(s) with sample data

### ISSUE THREAD

**Issue by jeroenalewijns** [magento/magento2#25701]
### Preconditions (*)
1. Clean install Magento 2.3.3 Commerce
2. Sample data installed via composer

### Steps to reproduce (*)
1. Install Magento2.3.3 via composer (composer create-project --repository=https://repo.magento.com/ magento/project-enterprise-edition cleaninstall 2.3.3)
2. add correct auth.json credentials
3. run bin/magento setup:install
4. run bin/magento sampledata:deploy
5. run bin/magento setup:upgrade
6. run bin/magento indexer:reindex
7. Visit a catalog page; for example https://xxx.xxx/men/tops-men/jackets-men.html
8. Change color or size
9. visit a productpage from a product shown on the page (step 5).
10. Change color or size

### Expected result (*)
When I change the color of a product via swatch the product image has to change to that specific color. 
![color-change-1](https://user-images.githubusercontent.com/2510441/69430709-8345b480-0d36-11ea-8592-c8ad22a6011a.png)
*Expected an orange shirt*
![color-change-2](https://user-images.githubusercontent.com/2510441/69430710-8345b480-0d36-11ea-86bd-2ffb658cddaf.png)
*Expected a red shirt*
![color-change-3](https://user-images.githubusercontent.com/2510441/69430712-8345b480-0d36-11ea-807d-ad2213132bec.png)
*Expected a purple shirt*

### Actual result (*)
The swatch is selected as active but the image doesn't change and stays in default setting.

Every product I have tested with has different images per attribute (color and size). All settings default / sample data. Update Product Preview Image is set to "YES" for example.

**Comment by samgranger** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @samgranger. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @samgranger, here is your [Magento instance](https://i-25701-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25701-2-3-develop.instances.magento-community.engineering/admin](https://i-25701-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jeroenalewijns** [comment]
Something seems to be wrong with sample data. When I add a configurable product in a clean install without sample data installed it works like I expect.
color changes on category page changes product image and the same for the category product page.

**Comment by nkajic** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nkajic. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by nkajic** [comment]
Confirming that this does not work on 2.3.3 from composer 
but it seems to be working on 2.4-develop branch from github.
![ScreenRecording2019-12-11at19594](https://user-images.githubusercontent.com/3989412/70651492-3a0bc500-1c51-11ea-8d7e-918d836458d9.gif)
If someone can track changes to exact commit that would be wonderful.

**Comment by engcom-Charlie** [comment]
Hello @sdzhepa 
This issue related to sample data. 
Could you transfer this issue to the Magento sample data repository?

**Comment by sdzhepa** [comment]
We are not able to reproduce it now on the latest `2.4-develop`
It seems was already fixed

**Comment by kristssw** [comment]
Hello,
I recently added a test project with Magento 2 version 2.3.3
It seems that for me helped that I:
- for **Color** attribute set **Update Product Preview Image** to no
- run `bin/magento indexer:reindex && bin/magento c:f`
- for **Color** attribute set **Update Product Preview Image** to yes
- run `bin/magento indexer:reindex && bin/magento c:f`

<img width="801" height="126" alt="Image" src="https://github.com/user-attachments/assets/a28b6d03-bceb-4b96-9f18-01d9d3643c6b" />

<img width="1800" height="829" alt="Image" src="https://github.com/user-attachments/assets/4627d47e-4352-4361-b853-475310260763" />
