### ISSUE TITLE
Results are not shwoing but count shows as 13

### ISSUE THREAD

**Issue by sathish1228** [magento/magento2#25707]
### Preconditions (*)

1. 2.3.3
2. On Index Management page I don't see results but count showing as 13 records found

### Steps to reproduce (*)

1. Not sure how you reproduce this issue
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. 
![image](https://user-images.githubusercontent.com/6438852/69474234-908d8e00-0d8c-11ea-9284-d6be3665dd0f.png)

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by kkorushkin** [comment]
Hi @sathish1228 It's not reproducible for me on 2.3-develop with sample data. Needs steps to reproduce (maybe you have any issues in console that can point to this problem).

**Comment by kkorushkin** [comment]
Hi @sathish1228. Please take a look at the my record - it's clean 23-develop with sample data (there's 6 cms pages by default). I've played with all this grids and all seems to be ok. Confirm if i got you point.
![ui-grid](https://user-images.githubusercontent.com/13004402/69480881-3d5f1e00-0e14-11ea-9460-006d8a27487c.gif)

**Comment by krishprakash** [comment]
Hi @sathish1228.
Thank you for your report. Issue can not reproduce on clean magento instance.
Feel free to reopen if you confirm that issue is reproduced on venilla magento instance
