### ISSUE TITLE
Have no any images after install

### ISSUE THREAD

**Issue by mohsen9010** [magento/magento2#2571]
I have the same issue problem : https://github.com/magento/magento2/issues/1249
I can not see any images after i install magento 2
Also i check the host and i route the dir files .I have no any images dir !!! :-1: 
/pub/static/adminhtml/Magento/backend/en_US/images
Magento Admin Address:
http://rayasys.ir/admin_92lfpz/

**Comment by iamrobreynolds** [comment]
Is this a fresh install? (only partially relevant)
Do you use the command line?

If yes, it sounds like you need to run:

{magento_install_dir}: php bin/magento setup:static-content:deploy

then change file permissions

find -type d -print -exec chmod 755 {};
find -type f -print -exec chmod 644 {};

**Comment by magenx** [comment]
yes, but dont forget that the most important command is `chown`, all files must be owned by user who runs php/apache `chown -R user:user *`

to avoid any issues, this command must be run as the same user, not root, if you run it as root, you need to switch user:
`chmod +x bin/magento`
`su - user -s /bin/bash -c "php bin/magento setup:static-content:deploy"`

**Comment by mohsen9010** [comment]
@robbiereynolds
Yes i twice fresh install ! 

@magenx
I have no any access to root server, this is only a host

**Comment by ghost** [comment]
Do you know if Apache server rewrites are enabled?

**Comment by duongquyet** [comment]
Hi,
We have same problem. Did you fix it?

**Comment by IceReaper** [comment]
Had the same problem, fixed when using 775 and 664 instead on a shared hoster. However there is one magento php file which needs to be edited to use this permissions, or every time you clear the static cache, you need to reset permissions.

**Comment by mohsen9010** [comment]
@xcomSteveJohnson 
I don't know!
It is litespeed server
How can i check ?

**Comment by duongquyet** [comment]
Thanks @IceReaper, It work for me.
