### ISSUE TITLE
Product info details tab loading issue

### ISSUE THREAD

**Issue by manojpal29** [magento/magento2#25710]
### Preconditions (*)

1. Magento 2.3.3
2. Apache 2.4
3. Php 7.2
4. Mysql 5.7 

### Steps to reproduce (*)

1.  On Product page load product info details tab loading issue
![image](https://user-images.githubusercontent.com/12071553/69477656-d2f7af00-0e0e-11ea-8552-bd12db2aafde.png)

### Expected result (*)

1. It should be show only first tab only not other tab
![image](https://user-images.githubusercontent.com/12071553/69477660-dd19ad80-0e0e-11ea-8e72-aa30e359f6e8.png)

### Actual result (*)

1. It should be show only active tab only on page load

**Comment by DanielRuf** [comment]
@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25710-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25710-2-3-develop.instances.magento-community.engineering/admin](https://i-25710-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @manojpal29,
I have verified this issue with the latest Magento 2.3 Instance as per your steps to be reproduced.
I don't have to reproduce this issue. 
Can you please provide me the video or any configuration details which you have changed?

Thanks.

**Comment by manojpal29** [comment]
Please check this demo when page is loading review tab showing.
https://i-25710-2-3-develop.instances.magento-community.engineering/product-1.html

![image](https://user-images.githubusercontent.com/12071553/69516802-c68f6580-0f78-11ea-9f89-e847b5151475.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25710-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25710-2-3-develop.instances.magento-community.engineering/admin](https://i-25710-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Please check the below-attached video. It's working fine on our end.
![Reviews_Issue](https://user-images.githubusercontent.com/24711761/69528001-72de4580-0f93-11ea-8351-f655f6aa9c86.gif)

@manojpal29 - If it is not working on your end please send the steps or video.

Thanks.

**Comment by taoufiqaitali** [comment]
@manojpal29   this maybe just an issue in your side, check browser console for javascripts issues

**Comment by ajijshekh123** [comment]
Yes @manojpal29, This issue is related to the any third party issue or Javascript issue.
Please verify it in your end update me. I will close this issue.

Thanks.

**Comment by manojpal29** [comment]
Thanks @ajijshekh123 , I have resolved issue.
The issue arises on page loading time not after page loading.

Thanks.

**Comment by ajijshekh123** [comment]
Okay @manojpal29, Let me close this issue.
