### ISSUE TITLE
Product listing time taken profiling dump

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#25715]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

A bit of dump in here:

1. https://github.com/magento/magento2/blob/121fadd45061beede3fe302ae47ee6640faeb69f/app/code/Magento/Catalog/view/frontend/templates/product/listing.phtml#L101
2. https://github.com/magento/magento2/blob/121fadd45061beede3fe302ae47ee6640faeb69f/app/code/Magento/Catalog/view/frontend/templates/product/listing.phtml#L19

### Expected result (*)

Absent those lines.

### Actual result (*)
Couldn't find any usage of the time_taken variable, so I guess it's a forgotten piece of profiling.

### Proposed solution
Remove those lines.

**Comment by magento-engcom-team** [comment]
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29137` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#25770 by @AndreyChorniy in 2.3-develop branch
Related commit(s):
 - [ed92b99eae3b856a46aa903f8514ac118d1d808e](https://github.com/magento/magento2/commit/ed92b99eae3b856a46aa903f8514ac118d1d808e)

The fix will be available with the upcoming 2.3.5 release.
