### ISSUE TITLE
Testing 2.3.0

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#25714]
@magento give me 2.3.0 instance

**Comment by DanielRuf** [comment]
Seems to work only in comments.

@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by DanielRuf** [comment]
@magento give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by DanielRuf** [comment]
Seems the bot is broken?

**Comment by DanielRuf** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by DanielRuf** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-25714-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25714-2-3-develop.instances.magento-community.engineering/admin](https://i-25714-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
So, seems it does not work with a tag / release.

**Comment by sdzhepa** [comment]
@magento give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-25714-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-25714-2-3-0.instances.magento-community.engineering/admin](https://i-25714-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
The issue has been fixed.
It seems we can close this ticket

**Comment by DanielRuf** [comment]
Definitely, many thanks =)
