### ISSUE TITLE
Error Composer install - File Forbiden 

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#2573]
![image](https://cloud.githubusercontent.com/assets/610598/11500375/eaf428e2-9813-11e5-9377-777ede7af65c.png)

![image](https://cloud.githubusercontent.com/assets/610598/11500393/0a5b73b6-9814-11e5-80b9-96048792c29b.png)

**Comment by dmitrii-fediuk** [comment]
You shoud use HTTP Authentication.
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/dev_install.html#create-authjson
https://mage2.pro/t/256

**Comment by rafaelstz** [comment]
Thank's :smile: :+1:
