### ISSUE TITLE
Customer account automatically confirmed

### ISSUE THREAD

**Issue by flamboy85** [magento/magento2#25730]
So, after upgrade magento 2.3.2 to 2.3.2-p2 (2.3.3 also) new customers always got confirmed status.
@see https://github.com/magento/magento2/commit/ce3e108be879190254b2d5ae38b0125ca73abae6

### Expected result (*)
1. Customer receive confirmation email after registration (based on admin configs)
2. Only after confirm his account he can login to his account

### Actual result (*)
1. Customer authorized after account creation

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25730-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25730-2-3-develop.instances.magento-community.engineering/admin](https://i-25730-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
Hi @flamboy85 please check your configuration:
Stores - Configuration - Customers - Customer Configuration - Create New Account Options - Require Emails Confirmation

**Comment by flamboy85** [comment]
@AnnaShepa thanks, seems issue related to module https://marketplace.magento.com/extait-module-gdpr.html . They use around plugin for Magento\Customer\Controller\Account\CreatePost in latest 1.3.0 module version

**Comment by smartcaeser** [comment]
i have the same issue customer is automatically approved
