### ISSUE TITLE
Radio buttons for shipping methods are disabled in shopping cart and during checkout

### ISSUE THREAD

**Issue by bigbywolf-uk** [magento/magento2#25737]
### Preconditions (*)

1. Magento 2.3.3 Communtiy Edition
2. Flat Shipping Table Rates

### Steps to reproduce (*)

1. Add product to the cart
2. Proceed to checkout as a guest
3. Enter valid address details
4. Wait for shipping rates to be displayed
5. Refresh page (Ctrl + R for example)

### Expected result (*)

1. Page reloads showing shipping rates with active radio buttons

### Actual result (*)

1. Page reloads with shipping rates but radio buttons are disabled

Issue is the same as :
https://github.com/magento/magento2/issues/7497

**Comment by ajijshekh123** [comment]
Hello @Munszu,
I am using a different address with a different country list and also apply the different shipping methods. But I can't able to reproduce this issue.

Thanks.

**Comment by ajijshekh123** [comment]
@Munszu - Can you please provide video or step details?

**Comment by ajijshekh123** [comment]
@Munszu - If you have reproduce this issue, You can reopen it and update your video or steps.
Thanks.

**Comment by andresams** [comment]
I was able to reproduce it and found a solution. Please, see my comment on this topic — https://github.com/magento/magento2/issues/7497#issuecomment-612102395
