### ISSUE TITLE
Category List Page - Select custom option for a product and add to cart, it will redirect to product view page saying required options not selected

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#2574]
Hello,

On Product List Page, When we select all necessary custom options for a product and click on add to cart, it redirects to the product view page asking to re-select the custom options. 

Ideally when all mandatory custom options are already selected on list page the product should get added to cart directly. 

On debugging further i noticed that the `super_attribute` is not getting passed from the list page to add Action. This parameter in Request, stores the values of selected custom options. The selected values only get passed from Product view page. 

In following image, it appears that all necessary custom options have been selected on list page. The Add to cart button shows `"Adding"` and then redirects to product view page.

![list-page](https://cloud.githubusercontent.com/assets/11473888/11503354/220fa520-9866-11e5-81af-26647b611d6c.png)

**Comment by benmarks** [comment]
Team, this will be resolved in MAGETWO-47017, correct?

**Comment by kandy** [comment]
Yes, Ben, will be fixed in MAGETWO-47017.

**Comment by parekhreena** [comment]
Thank you team !!

**Comment by pivulic** [comment]
:+1:

**Comment by huyencodon** [comment]
Please help me. I can't find MAGETWO-47017. Please give me a link. Thanks all!

**Comment by mazhalai** [comment]
@huyencodon that is only for internal purposes.

**Comment by TommyKolkman** [comment]
Is that MAGETWO-47017 supposed to be in 2.0.4? I've upgraded to that one and it isn't working for me as well.

**Comment by RMcLeod79** [comment]
Still broken in 2.0.5

**Comment by ntoombs19** [comment]
@kandy @pivulic @parekhreena @huyencodon - Is a fix for this issue going to be released within the next three months? I have a client that is requesting this functionality be fixed. Adding a product to the cart from the category page is basic functionality that I am very surprised hasn't been fixed in the 10 months that this issue has been known.

**Comment by rickwhitehead** [comment]
Please may I have a link to the pull request for the code to resolve this issue? If not please advise how the rest of us can follow progress/roadmap so that we have some idea how long we're likely to be waiting?

**Comment by rganin** [comment]
Fixed under MAGETWO-47017 ticket.

**Comment by Ctucker9233** [comment]
@rganin Will MAGETWO-47017 be included in 2.1.3?

**Comment by twistedatrocity** [comment]
Are these fixes included in the 2.1.6 release? They are definitely not in 2.1.5

**Comment by nscott89** [comment]
Is there a fix for this yet? A workaround will do for now? 

I can't seem to get any products with options to add to the cart at all, the only way they will add to cart is if i keep as a simple product with custom options but make them non required - and even then it doesn't take the option through to cart with it as it isn't updating price or sku in the cart just adding another base product. As soon as the option is made required it gives the message "You need to choose options for your item."

Setting up as a configurable product gives the alternative message of "You need to choose options for your item."

This is the last thing i need to get working on my current project and I really don't fancy starting from scratch in magento 1.9!
