### ISSUE TITLE
Category list REST API page size & current page search criteria options return all items

### ISSUE THREAD

**Issue by nntoan** [magento/magento2#25740]
### Preconditions (*)

1. Magento 2.2.x or up to 2.3.2 with Sample Data installed.

### Steps to reproduce (*)

1. Make an API request for categories specifying page size as 1, current page as 1.

```
GET /rest/V1/categories/list?searchCriteria[pageSize]=1&amp; searchCriteria[currentPage]=1 HTTP/1.1
Host: m2.localhost:6996
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
```

### Expected result (*)

1. Only one item return in the response e.g:

```
{
    "items": [
        {
            "id": 1,
            "parent_id": 0,
            "name": "Root Catalog",
            "is_active": true,
            "position": 0,
            "level": 0,
            "children": "2,3",
            "created_at": "2019-07-12 04:40:32",
            "updated_at": "2019-11-25 08:17:38",
            "path": "1",
            "available_sort_by": [],
            "include_in_menu": true,
            "custom_attributes": [
                {
                    "attribute_code": "is_anchor",
                    "value": "1"
                },
                {
                    "attribute_code": "path",
                    "value": "1"
                },
                {
                    "attribute_code": "children",
                    "value": "2,3"
                },
                {
                    "attribute_code": "children_count",
                    "value": "11522"
                },
                {
                    "attribute_code": "url_key",
                    "value": "root-catalog"
                },
                {
                    "attribute_code": "use_name_in_product_search",
                    "value": "1"
                },
                {
                    "attribute_code": "is_virtual_category",
                    "value": "0"
                },
                {
                    "attribute_code": "virtual_rule",
                    "value": {
                        "condition": {
                            "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine",
                            "aggregator_type": "all",
                            "operator": null,
                            "value": true
                        }
                    }
                },
                {
                    "attribute_code": "use_store_positions",
                    "value": "0"
                },
                {
                    "attribute_code": "code",
                    "value": "rootcatalog"
                },
                {
                    "attribute_code": "display_child_categories",
                    "value": "0"
                }
            ]
        }
    ],
    "search_criteria": {
        "filter_groups": [],
        "page_size": 1,
        "current_page": 1
    },
    "total_count": 1921
}
```
![Screen Shot 2019-11-26 at 10 00 56 AM](https://user-images.githubusercontent.com/3891429/69595998-c7390200-1033-11ea-92f2-b0ef15a64de3.png)
_(notice to the lines)_

### Actual result (*)

![Screen Shot 2019-11-26 at 10 12 55 AM](https://user-images.githubusercontent.com/3891429/69596503-5eeb2000-1035-11ea-8d58-2162f1cd78d1.png)
_(notice to the lines)_

### Technical details

After investigation, we found it caused by this

```
$items = [];
foreach ($collection->getAllIds() as $id) {
     $items[] = $this->categoryRepository->get($id);
}
```

To make it works correctly, we might need to pass the pageSize and offset into `getAllIds()` as parameters

```
$items = [];
$pageSize = $searchCriteria->getPageSize();
$curPage = $searchCriteria->getCurrentPage();
$offset = ($curPage - 1) * $pageSize;
foreach ($collection->getAllIds($pageSize, $offset) as $id) {
     $items[] = $this->categoryRepository->get($id);
}
```

**Comment by nntoan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nntoan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nntoan, here is your [Magento instance](https://i-25740-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25740-2-3-develop.instances.magento-community.engineering/admin](https://i-25740-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25740-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25740-2-3-develop.instances.magento-community.engineering/admin](https://i-25740-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
On clean instance it works fine
<img width="484" alt="Screenshot 2019-11-26 at 17 09 48" src="https://user-images.githubusercontent.com/24183408/69650961-a68e9d80-106f-11ea-9e9e-22d13ffa8f92.png">
 But on one of my project stage even simple searchCriteria[pageSize]=2 returns all categories

**Comment by AnnaShepa** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by AnnaShepa** [comment]
Cannot be reproduced in Magento 2.3.3

**Comment by nntoan** [comment]
@AnnaShepa it seems that Magento identified the issue and fixed it themselves here: https://github.com/magento/magento2/commit/a48cd8b634e6042051e82727f264b18b7137c952#diff-339443673db966cb93653dd08339a8f7

Please create a patch for it if you are using version lower than 2.3.3
