### ISSUE TITLE
Page Action Edit not working

### ISSUE THREAD

**Issue by Naeemakhter1999** [magento/magento2#25755]
( ! ) Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to a member function addFieldToFilter() on null in D:\wamp64\www\magento2\vendor\magento\module-ui\Component\Wrapper\UiComponent.php on line 0

**Comment by Naeemakhter1999** [comment]
( ! ) Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to a member function addFieldToFilter() on null in D:\wamp64\www\magento2\vendor\magento\module-ui\Component\Wrapper\UiComponent.php on line 0

**Comment by krishprakash** [comment]
Hi @Naeemakhter1999. Thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Thank You.
