### ISSUE TITLE
Link (terms and conditions) is not opening new tab. Missing target="_blank" for anchor tag.

### ISSUE THREAD

**Issue by Nagamaiah007** [magento/magento2#25757]
### Preconditions (*)

1.Magento 2.3.3

### Steps to reproduce (*)

1. Go to Admin Page -> Menu
2. Stores -> Settings -> Configuration -> General -> Advanced Reporting Page

### Expected result (*)

1. Link should be opened in new tab.
2. 
![image](https://user-images.githubusercontent.com/54108580/69629652-5bc25500-1072-11ea-92ac-207a43f45756.png)

### Actual result (*)

1. Link is opened in the same page.

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25757-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25757-2-3-develop.instances.magento-community.engineering/admin](https://i-25757-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
I'm able to replicate this issue in CE-2.3.3

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29191` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @Nagamaiah007. Thank you for your report. 
The issue has been fixed in magento/magento2#25760 by @Nagamaiah007 in 2.3-develop branch
Related commit(s):
 - [e95fee449a70264c36e0e482bd3f56c3bf7cafb4](https://github.com/magento/magento2/commit/e95fee449a70264c36e0e482bd3f56c3bf7cafb4)

The fix will be available with the upcoming 2.3.5 release.
