### ISSUE TITLE
magento2 admin panel dashboard Revenue showing 0.00

### ISSUE THREAD

**Issue by anuradhachakraborti** [magento/magento2#25751]
The tabs amount and orders are not working. i.e there is no action on clicking amount and order magento2 admin panel .magento2 admin panel dashboard Revenue showing 0.00

**Comment by anuradhachakraborti** [comment]
magento2 admin panel dashboard Revenue showing 0.00  Magento ver. 2.3.2

**Comment by krishprakash** [comment]
Hi @anuradhachakraborti. Thank you for your report.
Please provide more details to reproduce the issue.
Follow the issue reporting guild lines as below
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by krishprakash** [comment]
Closing this issue as not provided the issue information.
Feel free to reopen it once update the all details for reproduce this issue
Thanks
