### ISSUE TITLE
Authorize.net Auth & Capture not Capturing

### ISSUE THREAD

**Issue by jasonparauka** [magento/magento2#25768]
### Preconditions (*)

1. Magento 2.3.3 & 2.3-develop

### Steps to reproduce (*)

1. Configure Authorize.net to auto-capture
![Screenshot from 2019-11-27 14-43-09](https://user-images.githubusercontent.com/51680850/69724648-02ffc480-1125-11ea-8703-220c4e494134.png)

2. Place order via Authorize.net
![Screenshot from 2019-11-27 14-42-15](https://user-images.githubusercontent.com/51680850/69724664-0a26d280-1125-11ea-9653-b62feafcc9da.png)
![Screenshot from 2019-11-27 14-42-38](https://user-images.githubusercontent.com/51680850/69724690-127f0d80-1125-11ea-8fb5-e1f6c5ffc62e.png)

3. Go to the order and check for capture 

### Expected result (*)

1. Transactions should be captured
![image](https://user-images.githubusercontent.com/51680850/69724528-c2a04680-1124-11ea-9463-efc712febde6.png)

### Actual result (*)

1. Transactions are not auto-capturing 
![Screenshot from 2019-11-27 14-44-14](https://user-images.githubusercontent.com/51680850/69724509-b6b48480-1124-11ea-8120-66a2075fe62c.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29222` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sam110386** [comment]
Guys, is this resolved in 2.3.4 ? Btw, I still see this issue in 2.3.4

**Comment by vovsky** [comment]
@sam110386  It is not resolved in 2.3.4, PR is not merged. But to fix that switch to website/store scope on Authorize.net configuration page and set "capture" action there.

**Comment by ihor-sviziev** [comment]
Hi @jasonparauka,
According to following announcement this extension was already removed from 2.4 version:
https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445

All future collaboration related to this extension should be on Marketplace using "Contacts" or "Bug reports" related to this extension.

I'm closing this issue.
