### ISSUE TITLE
Create Order in the admin panel: wrong price is displayed for Configurable Products with Customizable Options

### ISSUE THREAD

**Issue by bgorski** [magento/magento2#25766]
### Preconditions (*)
1. Magento 2.3.3 (2.3.2 is affected as well, not tested on any other version)

### Steps to reproduce (*)
1. Create a configurable product with a Customizable (customizable, not configurable!) Option added to the parent product. The option should have at least one value that increases price of the product
2. Go to the Create Order page in the admin panel. Select/create a customer and proceed to the page where you add all the information (products, addresses etc.)
3. Click Add Products to see a grid of products. Your product should be on it (use filters if necessary)
4. You should see no price associated with the product on the products grid (this is the expected behavior as it's not configured yet)
5. Click Configure
6. Select the child product and the custom option's value that increases the price of the product. 
7. Click OK to go back to the main view
8. Notice that the product's price displayed on the grid is now available

### Expected result (*)
1. The price should be a sum of the child product's price and the custom option's price (for example if the product costs $200 and there's additional $20 for the custom option, it should show $220)

### Actual result (*)
1. The displayed price is only the custom option's price. The actual product price is not included (for example if the product costs $200 and there's additional $20 for the custom option, only $20 is actually displayed)

### Additional information
1. This is broken only for configurable products that have Customizable Options.
2. Configurable Products without Customizable Options display their price correctly after a child product is chosen in Configure
3. Simple/Virtual Products with a Customizable Option also correctly add its price to the product price
4. Even if a wrong price is displayed before adding a product to order, when it gets added (the Add Selected Product(s) to Order button is clicked), product price gets computed correctly
5. Not tested on product types other than simple/virtual and configurable

Attaching a few screenshots to make it clearer what this is about:
https://i.ibb.co/sjvwW4R/Price0.png - before a product gets configured
https://i.ibb.co/1GwP2RQ/Price1.png - during configuration
https://i.ibb.co/Y3b3Zrx/Price2.png - after it's configured, with a wrong price shown

**Comment by bgorski** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bgorski. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bgorski, here is your [Magento instance](https://i-25766-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25766-2-3-develop.instances.magento-community.engineering/admin](https://i-25766-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bgorski** [comment]
Tested on the development instance provided above and I can confirm that the issue is still there.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29882` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by CarmineDamore78** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78, here is your [Magento instance](https://i-25766-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25766-2-4-develop.instances.magento-community.engineering/admin_012b](https://i-25766-2-4-develop.instances.magento-community.engineering/admin_012b)
Login: `25232d9a` Password: `04005903eab3`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment]
@magento-admin issue not reproducible on Magento 2.4-develop
<img width="1920" alt="Screenshot 2020-05-22 at 15 46 41" src="https://user-images.githubusercontent.com/49639257/82680096-b6b0bf80-9c43-11ea-8913-50f6721f57ac.png">
<img width="1920" alt="Screenshot 2020-05-22 at 15 45 14" src="https://user-images.githubusercontent.com/49639257/82680111-bca6a080-9c43-11ea-9ac5-7fc2805c0078.png">
<img width="1920" alt="Screenshot 2020-05-22 at 15 44 29" src="https://user-images.githubusercontent.com/49639257/82680141-c3351800-9c43-11ea-9410-d6879b923cd7.png">

**Comment by sdzhepa** [comment]
@CarmineDamore78 

Thank you for confirmation that issue has been fixed in the current `2.4-develop`
Closed as fixed
