### ISSUE TITLE
Endless recursion caused by Magento\SalesRule\Observer\CouponCodeValidation Observer

### ISSUE THREAD

**Issue by Helge-HBA** [magento/magento2#25776]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. create cart rule with coupon code
2. add some products to cart
3. proceed the checkout and apply the coupon (don't place the order!)
3. deactivate one of the products you have in the cart in the backend
4. call any page in frontend, e.g. reload the checkout page

### Expected result (*)

1. The requested page

### Actual result (*)

1. Error page / Error log "PHP Fatal error:  Allowed memory size of XXXX bytes exhausted"

**Comment by Helge-HBA** [comment]
This behaviour is caused by the Magento\SalesRule\Observer\CouponCodeValidation Observer   #https://github.com/magento/magento2/commit/58a82c592fa5d1c8b9a53a4e38279840d043a630 wich loads the quote from repository in order to compare the coupon code with a potential new one. Since the observer is hooked inside the total collection process it will be triggered on every call of `$quote->collectTotals()`. Since this call occurs in the described situation inside 
`Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_assignProducts()` we have the following endless recursion:

	Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_assignProducts
	Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_afterLoad
	Magento\Framework\Data\Collection\AbstractDb->loadWithFilter
	Magento\Framework\Data\Collection\AbstractDb->load
	Magento\Framework\Data\Collection->getIterator
	Magento\Quote\Model\Quote->getAllVisibleItems
	Magento\Quote\Model\Quote\Interceptor->getAllVisibleItems
	Magento\Quote\Model\QuoteRepository\LoadHandler->load
	Magento\Quote\Model\QuoteRepository->getList
	Magento\Quote\Model\QuoteRepository\Interceptor->getList
	Magento\SalesRule\Observer\CouponCodeValidation->execute
	Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod
	Magento\Framework\Event\Invoker\InvokerDefault->dispatch
	Magento\Framework\Event\Manager->dispatch
	Magento\Framework\Event\Manager\Proxy->dispatch
	Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals
	Magento\Quote\Model\Quote\TotalsCollector->collect
	Magento\Quote\Model\Quote->collectTotals
	Magento\Quote\Model\Quote\Interceptor->collectTotals

	Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_assignProducts
	Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_afterLoad
	Magento\Framework\Data\Collection\AbstractDb->loadWithFilter
	Magento\Framework\Data\Collection\AbstractDb->load
	Magento\Framework\Data\Collection->getIterator
	Magento\Quote\Model\Quote->getAllVisibleItems
	Magento\Quote\Model\Quote\Interceptor->getAllVisibleItems
	Magento\Quote\Model\QuoteRepository\LoadHandler->load
	Magento\Quote\Model\QuoteRepository->getList
	Magento\Quote\Model\QuoteRepository\Interceptor->getList
	Magento\SalesRule\Observer\CouponCodeValidation->execute
	[...]

**Comment by Helge-HBA** [comment]
One possible solution could be to extend the method `Magento\Quote\Model\QuoteRepository\LoadHandler->load()` and store the original data like the model loading does, e.g.:

	namespace Magento\Quote\Model\QuoteRepository;

	[...]
	class LoadHandler
	{
	
	public function load(CartInterface $quote)
    {
        [...]
        $quote->setExtensionAttributes($cartExtension);
        $quote->setOrigData();
		
        return $quote;
    }

In this case the observer can easily compare the actual coupon code with the original data, e.g.:

	namespace Magento\SalesRule\Observer;


	class CouponCodeValidation implements ObserverInterface
	{
		[...]
		public function execute(EventObserver $observer)
		{
			/** @var Quote $quote */
			$quote = $observer->getData('quote');
			$code = $quote->getCouponCode();
			if ($code) {
				if ((string)$quote->getOrigData('coupon_code') !== (string)$code) {
					try {
						$this->codeLimitManager->checkRequest($code);
					} catch (CodeRequestLimitException $exception) {
						$quote->setCouponCode('');
						throw $exception;
					}
				}
			}
		}
	}

If changing the LoadHandler is not an option for whatever reason, I would suggest to make a direct call to quote table to check for the coupon code. The following code in the observer solves the problem, too:

    namespace Magento\SalesRule\Observer;

    use Magento\Framework\App\ResourceConnection;
    use Magento\Framework\Event\Observer as EventObserver;
    use Magento\Framework\Event\ObserverInterface;
    use Magento\Quote\Api\Data\CartInterfaceFactory;
    use Magento\Quote\Model\Quote;
    use Magento\SalesRule\Api\Exception\CodeRequestLimitException;
    use Magento\SalesRule\Model\Spi\CodeLimitManagerInterface;

    
    class CouponCodeValidation implements ObserverInterface
    {
        /**
         * @var ResourceConnection
         */
        private $resourceConnection;

        /**
         * @var CodeLimitManagerInterface
         */
        private $codeLimitManager;

        public function __construct(
            CodeLimitManagerInterface $codeLimitManager,
            ResourceConnection $resourceConnection
        )
        {
            $this->codeLimitManager = $codeLimitManager;
            $this->resourceConnection = $resourceConnection;
        }
     
        public function execute(EventObserver $observer)
        {
            /** @var Quote $quote */
            $quote = $observer->getData('quote');
            $code = $quote->getCouponCode();
            if ($code) {
                //check the coupon code of the current quote with a direct database call
                //loading the quote from repository would create endless recursion in certain situations!
                $connection = $this->resourceConnection->getConnection();
                $select = $connection->select()
                    ->from($this->resourceConnection->getTableName('quote'), 'coupon_code')
                    ->where('entity_id = ?', $quote->getId());
                $couponCode = $connection->fetchOne($select);

                if ((string)$couponCode !== (string)$code) {
                    try {
                        $this->codeLimitManager->checkRequest($code);
                    } catch (CodeRequestLimitException $exception) {
                        $quote->setCouponCode('');
                        throw $exception;
                    }
                }
            }
        }
    }

**Comment by maile-it-solutions** [comment]
@magento I am working on it

**Comment by nige-one** [comment]
@magento i am working on it

**Comment by staniag** [comment]
@magento i am working on it

**Comment by staniag** [comment]
Issue is not reproducible on 2.3-develop
