### ISSUE TITLE
Magento 2.3.3: major issue with importing product links (e.g. upsells, crosssells,...)

### ISSUE THREAD

**Issue by a-dite** [magento/magento2#25778]
We use a custom import module which prepares data and then uses magento catalog-import-export module's model **vendor/magento/module-catalog-import-export/Model/Import/Product.php** to import the product recommendations (upsells, crosssells, related products). We are currently in an upgrade process 2.2.10 -> 2.3.3 and face the following issue on 2.3.3 instance. Only a part of approx. 60.000 relations is imported - about 14.900.  In 2.2.10 the import works. After several days of investigation we found the reason and a solution.

Take a look at the following method saving product links in **vendor/magento/module-catalog-import-export/Model/Import/Product.php:**
`/**
     * Gather and save information about product links.
     *
     * Must be called after ALL products saving done.
     *
     * @return $this
     */
    protected function _saveLinks()
    {
        /** @var Link $resource */
        $resource = $this->_linkFactory->create();
        $mainTable = $resource->getMainTable();
        $positionAttrId = [];
        $nextLinkId = $this->_resourceHelper->getNextAutoincrement($mainTable);

        // pre-load 'position' attributes ID for each link type once
        foreach ($this->_linkNameToId as $linkId) {
            $select = $this->_connection->select()->from(
                $resource->getTable('catalog_product_link_attribute'),
                ['id' => 'product_link_attribute_id']
            )->where(
                'link_type_id = :link_id AND product_link_attribute_code = :position'
            );
            $bind = [':link_id' => $linkId, ':position' => 'position'];
            $positionAttrId[$linkId] = $this->_connection->fetchOne($select, $bind);
        }
        while ($bunch = $this->_dataSourceModel->getNextBunch()) {
            $this->processLinkBunches($bunch, $resource, $nextLinkId, $positionAttrId);
        }
        return $this;
    }`

a **$nextLinkId** is calculated once and the same value (passed by value) used over and over in bunches of 100 products. This integer is used to calculate primary key to insert into the table **catalog_product_link** in the method **processLinkBunches()**. This leads to the phenomenon, starting from second bunch **insertOnDuplicate** does not insert rows because same IDs where already used. The fix for us was to create a patch for the method processLinkBunches() method and pass **$nextLinkId** by reference:

`/**
     * Processes link bunches
     *
     * @param array $bunch
     * @param Link $resource
     * @param int $nextLinkId
     * @param array $positionAttrId
     * @return void
     */
    private function processLinkBunches(
        array $bunch,
        Link $resource,
        int &$nextLinkId,
        array $positionAttrId
    ): void {
        $productIds = [];
        $linkRows = [];
        $positionRows = [];

        $bunch = array_filter($bunch, [$this, 'isRowAllowedToImport'], ARRAY_FILTER_USE_BOTH);
        foreach ($bunch as $rowData) {
            $sku = $rowData[self::COL_SKU];`

also i changed the increment of this value to be incremented only if used:

`$nextLinkIdUsed = false;
                    if (!isset($productLinkKeys[$linkKey])) {
                        $productLinkKeys[$linkKey] = $nextLinkId;
                        $nextLinkIdUsed = true;
                    }

                    $linkRows[$linkKey] = $linkRows[$linkKey] ?? [
                            'link_id' => $productLinkKeys[$linkKey],
                            'product_id' => $productId,
                            'linked_product_id' => $linkedId,
                            'link_type_id' => $linkId,
                        ];

                    if (!empty($linkPositions[$linkedKey])) {
                        $positionRows[] = [
                            'link_id' => $productLinkKeys[$linkKey],
                            'product_link_attribute_id' => $positionAttrId[$linkId],
                            'value' => $linkPositions[$linkedKey],
                        ];
                    }
                    if ($nextLinkIdUsed) {
                        $nextLinkId++;
                    }`

### Preconditions (*)

1. PHP 7.3
2. Magento 2.3.3

### Steps to reproduce (*)

1. Run an CSV Product Import with the link feature (crosssells, upsells, related products) with more than 100 (main) products, ideally 500+ products that have product links

### Expected result (*)

1. All links are imported correctly and are present in catalog_product_link table

### Actual result (*)

1. Only a part of product links are present in catalog_product_link table, in my case ~14.900 of ~61.000

**Comment by congrallion** [comment]
I face the same issue. Upsells, Crosssells & Related product not imported completly. Does anyone have patch for this

**Comment by Sorbog** [comment]
@congrallion I fixed this with the following patch
```diff --git a/vendor/magento/module-catalog-import-export/Model/Import/Product.php b/vendor/magento/module-catalog-import-export/Model/Import/Product.php
--- a/vendor/magento/module-catalog-import-export/Model/Import/Product.php
+++ b/vendor/magento/module-catalog-import-export/Model/Import/Product.php
@@ -3128,7 +3238,7 @@
     private function processLinkBunches(
         array $bunch,
         Link $resource,
-        int $nextLinkId,
+        int &$nextLinkId,
         array $positionAttrId
     ): void {
         $productIds = [];
@@ -3180,7 +3290,7 @@
                         continue;
                     }
                     $linkKey = $this->composeLinkKey($productId, $linkedId, $linkId);
-                    $productLinkKeys[$linkKey] = $productLinkKeys[$linkKey] ?? $nextLinkId;
+                    $productLinkKeys[$linkKey] = $productLinkKeys[$linkKey] ?? $nextLinkId++;

                     $linkRows[$linkKey] = $linkRows[$linkKey] ?? [
                             'link_id' => $productLinkKeys[$linkKey],
@@ -3196,7 +3306,6 @@
                             'value' => $linkPositions[$linkedKey],
                         ];
                     }
-                    $nextLinkId++;
                 }
             }
         }
@@ -3217,7 +3326,7 @@
         if (!empty($linksToDelete) && Import::BEHAVIOR_APPEND === $this->getBehavior()) {
             foreach ($linksToDelete as $linkTypeId => $productIds) {
                 if (!empty($productIds)) {
-                    $whereLinkId = $this->_connection->quoteInto('link_type_id', $linkTypeId);
+                    $whereLinkId = $this->_connection->quoteInto('link_type_id = ?', $linkTypeId);
                     $whereProductId =  $this->_connection->quoteInto('product_id IN (?)', array_unique($productIds));
                     $this->_connection->delete(
                         $resource->getMainTable(),
```

**Comment by mamsincl** [comment]
same issue with M2.3.5-p2

https://github.com/magento/magento2/issues/25778#issuecomment-673228380 fixed the issue
