### ISSUE TITLE
Not saving postcode in the cart page

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#25779]
### Preconditions (*)

1. It's present in Magento 2.2.9 and 2.3.2
2. Sampledata installed

### Steps to reproduce (*)

1. Add a physical product to the cart
2. Go to the cart page
3. Type a postcode and change the product quantity
4. Click in the **Update Shopping Cart** button

### Expected result (*)

1. Update the quantity and keep the postcode

### Actual result (*)

1. The page is updated and the postcode typed is lost.

![Screenshot 2019-11-27 14 33 39](https://user-images.githubusercontent.com/610598/69746974-3db52d00-1124-11ea-8b3c-757931e1acbf.png)

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by shikhamis11** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25779-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25779-2-3-develop.instances.magento-community.engineering/admin](https://i-25779-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hi @rafaelstz 
I check this issue but not able to reproduce this issue on latest develop instance . let me know If you still able to reproduce this issue
