### ISSUE TITLE
Backend wysiwyg image browser always calls php instead of loading directly the image file

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#25771]
### Preconditions (*)

1. Magento 2.3.x
2.

### Steps to reproduce (*)

1. Create a symlink to pub/media: `mkdir symlink && mv pub/media symlink && cd pub && ln -s ../symlink/media media`
2. Go to backend and open up a wysiwyg image browser and have a few images in there.
3. Note that all src to the image are in the format of `admin/cms/wysiwyg_images/thumbnail/file/`
4. Reload the image browser. By now all the images should have gotten a thumbnail.
5. Verify that src goes to the image directly instead of going to the php `admin/cms/wysiwyg_images/thumbnail/file/` again.

### Expected result (*)

1. src for images is directly going to the file

### Actual result (*)

1. src for images is not directly going to the file, but is still trying to process it with php

**Comment by PascalBrouwers** [comment]
Possible related: https://github.com/magento/magento2/issues/11304

**Comment by PascalBrouwers** [comment]
Not sure if symlink is what is causing this issue, but it clearly does not get the path correct and a `/` is missing.

**Comment by DanielRiezebos** [comment]
Patch to fix: https://gist.github.com/DanielRiezebos/6be4de18aaf24a44533686fc29dc5347
Works on Magento 2.3.3.

Thanks @tdgroot & @PascalBrouwers!

**Comment by engcom-Golf** [comment]
Hi @PascalBrouwers thank you for you report this issue has already fixed by this commit https://github.com/magento/magento2/commit/9a31aa2a0f5f238e1df601274d307308ac767659.
