### ISSUE TITLE
Index Management Grid: Align issue with checkboxes 

### ISSUE THREAD

**Issue by yurylapi** [magento/magento2#25773]
**Preconditions**
1. Install or update Magento 2.3 to the last version;

**Steps to reproduce**
1. Login to admin panel;
2. Go to the System->Tools->Index Mangement;
3. You will see a broken grid;
![_thumb_439969](https://user-images.githubusercontent.com/44709956/69720095-29683480-1112-11ea-9655-8063bfb85863.png)

**Expected result**
The grid table aligns checkboxes properly.

**Actual result**
1. Current styles breaks checkbox alignment in Index Management Grid table;

**Additional details**
1. Apparently this line was coming after merge-conflict resolving, but should not be there. 
https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/design/adminhtml/Magento/backend/Magento_Ui/web/css/source/module/_data-grid.less#L394
2. This line breaks the table alignment, but apparently it's already resolved in 2.3-development branch.
https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/design/adminhtml/Magento/backend/Magento_Ui/web/css/source/module/_data-grid.less#L1078

**Comment by engcom-Charlie** [comment]
Hello @yurylapi 
As you know this issue is resolved now. I think it was reported earlier. That fix will be included in Magento 2.3.4 . 
So no sense to confirm your issue.  We can just close it.

Thanks for your report!

**Comment by yurylapi** [comment]
Perfect, thanks
