### ISSUE TITLE
Update the cart qty via AJAX

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#25780]
### Description (*)

Would be great to have the cart page updated via AJAX as the postcode do.
![Screenshot 2019-11-27 14 33 39](https://user-images.githubusercontent.com/610598/69747147-8cfb5d80-1124-11ea-9999-3b2eab6d8920.png)

### Expected behavior (*)

When change the quantity in the cart page, update the shipping rates via ajax as changing the postcode.

### Benefits

It would improve the user experience and not lose the postcode when qty been updated.

**Comment by maksek** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maksek. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maksek, here is your [Magento instance](https://i-25780-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25780-2-3-develop.instances.magento-community.engineering/admin](https://i-25780-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @rafaelstz 
Thank you for reporting this issue. It will process faster if you report this at [Magento Feature request](https://github.com/magento/community-features)
