### ISSUE TITLE
Checkbox alignement on Cache Management and Index Management

### ISSUE THREAD

**Issue by jerome-zhang** [magento/magento2#25781]
### Preconditions (*)

1. Install latest magento 2.3.3

### Steps to reproduce (*)

1. Go to admin > Cache Management or Index Management
2. Check the checkbox alignement https://www.screencast.com/t/DZcexUvC
![2019-11-28_1052](https://user-images.githubusercontent.com/12635165/69773418-cb992280-11cd-11ea-83bc-02092f82bec9.png)

### Expected result (*)

1. (https://www.screencast.com/t/gbAsMm1MN)
![2019-11-28_1054](https://user-images.githubusercontent.com/12635165/69773433-d81d7b00-11cd-11ea-8e13-383230c90601.png)

### Actual result (*)

1. Check box mis-align and cannot be click https://www.screencast.com/t/DZcexUvC
![2019-11-28_1052](https://user-images.githubusercontent.com/12635165/69773418-cb992280-11cd-11ea-83bc-02092f82bec9.png)

**Comment by krishprakash** [comment]
Hi @jerome-zhang. 
This issue is resolved and reported earlier. That fix will be included in Magento 2.3.4 .
You can review it at #25773 
Review the PR #25443 
Thanks for your report!
