### ISSUE TITLE
Manage Stock = No and Backorders Config = Allow

### ISSUE THREAD

**Issue by will-wright1** [magento/magento2#25814]
### Preconditions (*)
Magento 2.3.3

### Steps to reproduce (*)
1 In Advanced Inventory change manage stock on a product to 'yes'
2 Untick 'use config settings' on backorders
3 Change backorders to 'Allow Qty Below 0 and Notify Customer'
4 Save product
5 Change manage stock on the product to 'no'
6 Save product
7 On the frontend of the website add that product to cart
8 Navigate to cart

### Expected result (*)
When you go to the cart you should just see the products in the cart as normal because the manage stock setting is set to no.

### Actual result (*)
When you go to the cart you get the message saying "We don't have as many quantity as you requested, but we'll back order the remaining 1." It seems to be picking up the Allow Backorders configuration even though the stock is set to not be managed.

![Screenshot 2019-11-28 at 16 17 59](https://user-images.githubusercontent.com/22942523/69821264-11201480-11fb-11ea-82f9-8bf9e2be3acc.png)

**Comment by will-wright1** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webamondo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webamondo, here is your [Magento instance](https://i-25814-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25814-2-3-develop.instances.magento-community.engineering/admin](https://i-25814-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29263` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @webamondo 

Re-checked this issue on the latest `2.4-develop` code.
I am not able to reproduce it now, it seems was already fixed
Closed
 
![issue_25814](https://user-images.githubusercontent.com/3409584/89348042-82a94000-d671-11ea-81b4-9bc5a15ad444.gif)
