### ISSUE TITLE
Problems with Magento sidebar menu 

### ISSUE THREAD

**Issue by RicardoEwertz** [magento/magento2#25824]
We changed our hosting and uploaded all files again for Magento 2
I can see and have access to the Magento admin, but the sidebar menu is not active.

 
![Screenshot_Magento sidebar Menu](https://user-images.githubusercontent.com/50683264/69832264-1043ae80-120c-11ea-9373-6f9c6fd3cc36.jpg)

**Comment by krishprakash** [comment]
Hi @RicardoEwertz. Thank you for your report.
Closing this issue as same Issue raised by you with proper issue format #25826 
Thanks
