### ISSUE TITLE
Magento 2 Problems with Magento Sidebar Menu

### ISSUE THREAD

**Issue by RicardoEwertz** [magento/magento2#25826]
We changed our hosting and uploaded all files again for Magento 2
I can see and have access to the Magento admin, but the sidebar menu is not active.

### Preconditions (*)

1.Magento ver. 2.3.1
2.

### Steps to reproduce (*)

1. Fix an issue and be able to acces the sidemenu on Magento/admin
2.

### Expected result (*)

1. 
![Screenshot_Magento sidebar Menu](https://user-images.githubusercontent.com/50683264/69832413-df17ae00-120c-11ea-85a7-6cefaf2b2d42.jpg)

2.Fix the problem

### Actual result (*)

1. the side menú is inactive or disabled
2.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25826-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25826-2-3-develop.instances.magento-community.engineering/admin](https://i-25826-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@RicardoEwertz - I can't able to reproduce this issue in Default Magento 2.3 Instance.
See attached screenshot:

![First](https://user-images.githubusercontent.com/24711761/69844317-ad94f600-1291-11ea-9f29-6e97f8f08afb.png)

@RicardoEwertz - Can you please provide me video Or proper steps?

Thanks.

**Comment by omaxmo** [comment]
https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-static-view.html
