### ISSUE TITLE
Order, Invoice change increment_id

### ISSUE THREAD

**Issue by Chowix** [magento/magento2#2583]
hello,
I'm sorry, my english is bad, but how can i change number of order, invoice, increment_id e.g 00000001 to 14120544 on magento 2 ??

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
