### ISSUE TITLE
After switching from default to developer mode, images and CSS are gone

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#2584]
New installation in default mode, run the tool 'setup:static-content:deploy' and front/backend displaying everything fine.

After switching from default to developer mode, images and CSS dont display on browser.

**Comment by mazhalai** [comment]
@lgarridoj if you are on apache, can you check if `mod_rewrite` is enabled?

**Comment by jibrandlr** [comment]
@mazhalai It is enabled on apache

**Comment by jibrandlr** [comment]
@mazhalai I reinstalled magento and set to **developer** mode. Now it looks like this:
![magento-developermode](https://cloud.githubusercontent.com/assets/8398744/11550362/12ac4ea6-9935-11e5-84b8-2fece23547ae.jpg)

**Comment by jibrandlr** [comment]
Found the following solution on stackexchange: (any comments about why this change is needed?)

When not in production mode Magento 2 will try to create symlinks for some static resources. You can change that behavior by doing the following.

Open up app/etc/di.xml and find the virtualType name="developerMaterialization" section. In that section you'll find an item name="view_preprocessed" that needs to be modified or deleted. You can modify it by changing the contents from Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink to Magento\Framework\App\View\Asset\MaterializationStrategy\Copy

Delete the files under pub/static to get rid of any existing symlinks. You may want to be careful not to delete the .htaccess file.

This should solve your error with the symlink.

**Comment by daim2k5** [comment]
@lgarridoj i hope its ok the close the issue because you found your solution. If not please reopen

**Comment by LiamKarlMitchell** [comment]
It is 2019, PHP supports symlinks on Windows 10.

Why is this still a problem, no symlinks are being made and I'm using XAMPP with PHP 7.1.29 running Magento 2.3.3 in development mode.

Yet pub static only contains directories no files.

Example vhost
```xml
<VirtualHost *:80>
    ServerAdmin liam@mydomain.com
    DocumentRoot "C:/xampp/htdocs/magento"
    ServerName test.mydomain.com
    ErrorLog "logs/test.mydomain.com-error.log"
    CustomLog "logs/test.mydomain.com-access.log" common
    <Directory "C:/xampp/htdocs/magento">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>
```

I want to use symlinks, don't want to have to copy/redeploy static content every time I make a simple change.

system.log is littered with errors.
```
[2019-11-08 12:42:10] main.ERROR: A symlink for "C:/xampp/htdocs/magento/lib/web/jquery/jstree/themes/default/style.css" can't be created and placed to "C:/xampp/htdocs/magento/pub/static/adminhtml/Magento/backend/en_US/jquery/jstree/themes/default/style.css". Warning!symlink(): Cannot create symlink, error code(1314) [] []
```
> The problem mostly occurs when you don't start the server or Xampp on local with administrative privilege. Try to start Xampp from the control panel if you are on windows.

https://stackoverflow.com/questions/51180811/symlink-cannot-create-symlink-error-code1314
https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/#SyhzahMUi629VLW0.97

**Solution**
Need to run console and apache / xamp control it as Administrator to create symlinks.... Thanks microsoft.

Right click on "XAMPP Control Panel" and "Run as administrator" or Properties Compatibility run as administrator so it remembers.

Note: I'm not running the webserver as a service.
