### ISSUE TITLE
\Magento\MediaStorage\Model\File\Storage\Synchronization::synchronize() wrongly leaves a file in the locked state in a case of an exception

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2586]
https://mage2.pro/t/274
See also: https://github.com/magento/magento2/issues/2578, https://github.com/magento/magento2/issues/2566, https://github.com/magento/magento2/issues/2558

**Comment by andimov** [comment]
Could you please add the description of steps, actual result and expected result to this ticket?
It will help other community members to find this problem when they use GitHub, which is, unfortunately, impossible when the full description is placed on the external resource.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
