### ISSUE TITLE
Swagger schema doesn't show all available services for Customer when customer token is used

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25861]
### Preconditions (*)

1. Magento 2.3-develop
2. Registered Customer

### Steps to reproduce (*)

1. Get Customers token
```shell
endpoint="http://magento2.loc/rest"
customer_token=$(curl -X POST "$endpoint/V1/integration/customer/token" \
 -H "Content-Type: application/json" \
 -d '{"username":"John.Doe@example.com","password":"123123qA"}') && echo $customer_token  && customer_token=$(echo $customer_token | tr -d '"')
```
2. Navigate to `/swagger`
3. Paste the token and click 'Apply' in the top-right corner
4. Can I update my details using customerCustomerRepository?

### Expected result (*)

1. Yes, I can

### Actual result (*)

1. No, I cannot.
![image](https://user-images.githubusercontent.com/11827230/69957241-e4c20c00-150a-11ea-8083-c0a252944c37.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29301` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by marcoaacoliveira** [comment]
I'm getting the same problem in Magento 2.4
