### ISSUE TITLE
Graphql classification search results are inconsistent with fontend

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento2#25873]
### Preconditions (*)

2.3-develop

### Steps to reproduce (*)

1.Start a search with keyword 'Luma' in frontend
2.Start a search with keyword 'Luma' in graphql, for example below
```
{
  products(search: "Luma", pageSize: 10) {
    total_count
    aggregations {
      attribute_code
      count
      label
      options {
        count
        label
        value
      }
    }
    
    items {
      name
      sku
      price {
        regularPrice {
          amount {
            value
            currency
          }
        }
      }
    }
    page_info {
      page_size
      current_page
    }
  }
}

```

### Expected result (*)

1. Graphql search results should be consistent with frontend search results.

### Actual result (*)

1. Frontend search result
![20191202175148](https://user-images.githubusercontent.com/4518013/69950367-42b41b00-152e-11ea-8e1a-fbaedbf4b2e3.png)

2.graphql search result
![20191202175126](https://user-images.githubusercontent.com/4518013/69950567-80b13f00-152e-11ea-8031-99cc9589b24f.png)
![20191202180619](https://user-images.githubusercontent.com/4518013/69950568-80b13f00-152e-11ea-98b7-20ad41e20f67.png)

**Comment by engcom-Charlie** [comment]
Hello @michaeldyl520 
Thank you for contribution and collaboration!
Your issue for Magento Graphql repository.

Please duplicate this issue in [Magento Graphql  repository](https://github.com/magento/graphql-ce/issues), for advice or general discussion about this issue.
