### ISSUE TITLE
DHL price not updated on store change

### ISSUE THREAD

**Issue by insaurabh** [magento/magento2#25872]
### Preconditions (*)
1.  Magento version 2.2.x & 2.3.x
2.  PHP 7.1 & 7.2

### Steps to reproduce (*)

1. Add a product
2. On Filling State and ZIP code the DHL ajax works and fill up the prices 
![image](https://user-images.githubusercontent.com/51680850/69954737-ab869d80-1504-11ea-8434-2a36ac9d1349.png)
3. Change the store form USD (Dollar) to EUR (Euro) 

### Expected result (*)
    The Price should change as per the currency of the current store selected by the user.

### Actual result (*)

    The Price of DHL is the same in all the Currency.
![image](https://user-images.githubusercontent.com/51680850/69954772-c1945e00-1504-11ea-80ad-37e09cb136dc.png)

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-25872-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25872-2-3-develop.instances.magento-community.engineering/admin](https://i-25872-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @maddyBoy 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

**Testing scenario:**
1. Add a product
2. On Filling State and ZIP code the DHL ajax works and fill up the prices 
![image](https://user-images.githubusercontent.com/51680850/69954737-ab869d80-1504-11ea-8434-2a36ac9d1349.png)
3. Change the store form USD (Dollar) to EUR (Euro) 

**Result:**
The Price is changed as per the currency of the current store selected by the user
![image](https://user-images.githubusercontent.com/51680850/69954772-c1945e00-1504-11ea-80ad-37e09cb136dc.png)

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

Thanks for your report!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29298` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by insaurabh** [comment]
Is there any patch available for this issue.

**Comment by insaurabh** [comment]
Hi, @magento-engcom-team 

Is there any timeline for this issue that when it will be added in the development phase?

Thank You.

**Comment by shubhamkhandelwalrtpl** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shubhamkhandelwalrtpl. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shubhamkhandelwalrtpl, here is your [Magento instance](https://i-25872-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25872-2-4-develop.instances.magento-community.engineering/admin_f35e](https://i-25872-2-4-develop.instances.magento-community.engineering/admin_f35e)
Login: `696cf150` Password: `b27123c7799d`
Instance will be terminated in up to 3 hours.

**Comment by insaurabh** [comment]
Hello @shubhamkhandelwalrtpl,

Are you working on this issue?

**Comment by maddyBoy** [comment]
@sdzhepa ,

Is there any update or patch for this.

Thank You.

**Comment by chiranjeevi-cj** [comment]
@magento give me 2.4-develop instance

**Comment by chiranjeevi-cj** [comment]
@magento give me 2.3-develop instance

**Comment by xls2802** [comment]
@magento I am working on this

**Comment by xls2802** [comment]
@magento add to contributors team

**Comment by chuckgreenman** [comment]
@magento add to contributors team

**Comment by chuckgreenman** [comment]
@magento I am working on this

**Comment by chuckgreenman** [comment]
@magento give me 2.3-develop instance

**Comment by chuckgreenman** [comment]
@magento give me 2.3-develop instance

**Comment by chuckgreenman** [comment]
When I picked up this issue I assumed that DHL would let me sign up for an account.  Unfortunately I can't get their form to work, I'm going to release this.

**Comment by engcom-Charlie** [comment]
Hello @insaurabh we are not able to reproduce the issue on the latest 2.4-develop by the following steps:
1. Set-up DHL.
2. Create a simple product with weight.
3. Open store configuration
4. Change the scope to `store view`
5. Open `General` -> `Currency Setup` -> `Currency Options` and set `Allowed Currencies` to **EUR** and **USD**.
5. Create a customer with an address and log in on the storefront.
5. Add product to cart
6. Open Shopping Cart
7. Observe prices in USD.
![image](https://user-images.githubusercontent.com/51680850/104917873-a997cc00-599c-11eb-88c2-96ae2160640c.png)

8. Switch currency to EUR and observe prices.
![image](https://user-images.githubusercontent.com/51680850/104917922-bae0d880-599c-11eb-9e0b-0211f755422c.png)

**AR**: Prices are different as expected
Could you please take a look?
Thank you.

**Comment by xls2802** [comment]
Hello!
Perhaps you made a mistake with the mailing address. Please don't send such
emails to this address any more. I'm not that person you need.
Kind regards!

пн, 18 янв. 2021 г. в 14:54, Vadim Malesh <notifications@github.com>:

**Comment by engcom-Charlie** [comment]
I'm closing this issue now due to inactivity.
Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for your collaboration.

Thanks for your report!
