### ISSUE TITLE
Produced in stock, despite the Salable QTY is at zero.

### ISSUE THREAD

**Issue by TerreFra** [magento/magento2#25877]
### Preconditions (*)

1. Magento 2.3.3 

### Steps to reproduce (*)

1. Salable Quantity and Quantity = 1 (https://prnt.sc/q50vv4)
2. An order is placed, and the Salable Quantity drops to zero, while the Quantity remains at 1. (https://prnt.sc/q50w91)

### Expected result (*)

1. The product, having Salable Quantity 0, goes out of stock.

### Actual result (*)

1. The product remains in stock, and is seen in the frontend. (https://prnt.sc/q50whk)

**Comment by abramchukm** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @abramchukm. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @abramchukm, here is your [Magento instance](https://i-25877-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25877-2-3-develop.instances.magento-community.engineering/admin](https://i-25877-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
You need to dispatch the item for the stock quantity value to drop. According to Magento MSI, this is correct behavior. The order creates the reservation, which lowers the salable quantity, however the actual quantity will be lowered when the order is dispatched to the customer.

**Comment by jayachandraoggy** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jayachandraoggy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayachandraoggy, here is your [Magento instance](https://i-25877-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25877-2-3-develop.instances.magento-community.engineering/admin](https://i-25877-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @TerreFra thank you for your report. This is [MSI](https://github.com/magento/inventory) functionality.
Please, refer to appropriate [repo](https://github.com/magento/inventory/issues) for further investigation
