### ISSUE TITLE
Magento 2.3.3. Wrong logic in get.php(static content serving) triggering exception ObjectManager isn\'t initialized

### ISSUE THREAD

**Issue by oncesk** [magento/magento2#25885]
### Preconditions (*)
1. Magento 2.3.3
2. Nginx dedicated server
3. Php 7.2

### Steps to reproduce (*)
1. We were faced with issue of incorrect logic in get.php after upgrading magento to 2.3.3.
2. Please take a look at get.php:

https://github.com/magento/magento2/blob/2.3-develop/pub/get.php#L56
![image](https://user-images.githubusercontent.com/2046092/70046331-e22ce880-15d6-11ea-825a-e89b37330faf.png)
3. Here we can see creation of new object (\Magento\Framework\File\Transfer\Adapter\Http) but if we go inside the class and look at his constructor
4. Construct is calling ObjectManger::getInstance 
https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/File/Transfer/Adapter/Http.php#L47
![image](https://user-images.githubusercontent.com/2046092/70045584-67af9900-15d5-11ea-9ff7-7eaa7f494f6d.png)

5. The main thing that ObjectManager is not initialized by this time and we are getting exception
https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/App/ObjectManager.php#L36
![image](https://user-images.githubusercontent.com/2046092/70045761-b4936f80-15d5-11ea-9df4-4728d7c639c1.png)

6. ObjectManager initialization will be done at application bootstrap, here
https://github.com/magento/magento2/blob/2.3-develop/pub/get.php#L75

### When this error occures?
In case you have different servers/nodes/containers for webserver and php, webserver will not serve static content and pass request to the backend (PHP magento)...

### Expected result
No exception during file serving process

### Actual result
RuntimeException - ObjectManager isn\'t initialized

**Comment by magento-engcom-team** [comment]
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29342` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @oncesk, can you provide a specific scenario where we can reproduce this issue? Thanks!

**Comment by thomasheller** [comment]
There seems to be a bug in `pub/get.php`:

- `$mediaDirectory` is read from `var/resource_config.json` where in our setup it is set to `/var/www/html/pub/media/`. 
- `$relativePath` is simply the URL path of the HTTP request, e.g. `/media/catalog/product/cache/ccd8d44c60afb81c13822e813fe440e5/0/1/01_065_0211_0_i_01_1eaf.jpg`
- `$mediaAbsPath` is set by joining `$mediaDirectory` and `$relativePath` with a `/`

This leads to a `$mediaAbsPath` like `/var/www/html/pub/media//media/catalog/product/cache/ccd8d44c60afb81c13822e813fe440e5/0/1/01_600_1002_0_i_01_265c.jpg`, i.e. the `media` directory appears twice in the path, which doesn't seem to be correct.

**Comment by pixel-paul** [comment]
I'm getting this issue after upgrading from 2.3.5-p1 to 2.3.5-p2.

**Comment by MarksAfanasevics** [comment]
We had similar problems, but I found the solution. Thanks @thomasheller for the information about get.php.
As I understand, in this get.php file path always has two media folders (this is how magento works). In our case, there was another folder in media folder, and get.php started to work incorrectly.
So, folders were like this (additional media folder from somewhere):
`pub/media/media`
And I renamed it to this 
`pub/media/media-bac`
After that, images works correctly. Happened only on one instance for us (on stage).

**Comment by denissdubinin** [comment]
Comments above are not related to reported issue.

In order to fix the issue you should move bootstrap somewhere at the beginning of the file, before Object manager is called.

Move this:
```
// Materialize file in application
$params = $_SERVER;
if (empty($mediaDirectory)) {
    $params[ObjectManagerFactory::INIT_PARAM_DEPLOYMENT_CONFIG] = [];
    $params[Factory::PARAM_CACHE_FORCED_OPTIONS] = ['frontend_options' => ['disable_save' => true]];
}
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
```

Somewhere before `if (file_exists($configCacheFile) && is_readable($configCacheFile)) {`.

`new \Magento\Framework\File\Transfer\Adapter\Http(` is called inside this statement, and there is ObjectManager call in constructor of this class
