### ISSUE TITLE
UX/UI fixes for Index Management Grid

### ISSUE THREAD

**Issue by artursson** [magento/magento2#25884]
### Preconditions (*)

Magento 2.3.2 and Magento 2.3.3 versions

### Steps to reproduce (*)

1. Open Magento Admin Panel
2. Go to System -> Index Management

### Expected result (*)

Checkboxes for select are centered and clickable
![image](https://user-images.githubusercontent.com/55872143/70044198-8d837080-15ca-11ea-8b14-2799d7f13cda.png)

### Actual result (*)

Checkboxes for select are shifted and not clickable
![image](https://user-images.githubusercontent.com/55872143/70044337-d804ed00-15ca-11ea-9b1f-f8f2e26ceac4.png)

**Comment by artursson** [comment]
yes

**Comment by krishprakash** [comment]
Hi @artursson.
This issue is resolved and reported earlier. That fix will be included in Magento 2.3.4 .
You can review it at #25773
Review the PR #25443
Thanks for your report!
