### ISSUE TITLE
Error Auth Api invalid client id Paypal

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#25887]
### Preconditions (*)
1. Magento 2.3.2 & 2.3-develop
2. paypal checkout 
3.All Extensions are disabled.

**Also tried that on Magento 2.3.3 fresh installation.** 

### Steps to reproduce (*)

1. Add product to cart.
2. Proceed to checkout.
3. Paypal express Checkout.

### Expected result (*)

1. Make an order

### Actual result (*)

1. Paypal client id invalid. 
![paypal_401](https://user-images.githubusercontent.com/33385380/70080833-4c448e00-15d5-11ea-8395-623ae0926469.PNG)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29387` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by alex-james** [comment]
I get exactly the same issue with Magento 2.3.3 running on PHP 7.1.33

**Comment by pbh-stu** [comment]
Same issue here after upgrading to Magento 2.3.3  - PHP 7.2.25 

![image](https://user-images.githubusercontent.com/20659255/70703853-d329f280-1cc8-11ea-8f05-88fce0182fb6.png)

**Comment by pbh-stu** [comment]
As a workaround we have managed to get the older magento-paypal "100.2.7" working on magento 2.3.3 simply by overwriting the vendor/magento/module-paypal folder with a folder from a magento 2.2.9 installation. Not ideal and not 100% tested but seems to address the issue at hand while a true fix is developed.

alternatively, just disable 'in context checkout' and it should work.

**Comment by testmagento2** [comment]
But why no one update this.
This is a big issue.

**Comment by pbh-stu** [comment]
@testmagento2 I couldn't agree more! A leading ecom platform major version release with a broken paypal module and no patch in sight. It's this sort of craziness that makes me question if i should continue with magento at all.
It will work if you turn off in context checkout but that's not good enough IMO we are paying magento £££/month for bugs and more bugs.

**Comment by mahesh-rajawat** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-25887-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25887-2-4-develop.instances.magento-community.engineering/admin_bcd2](https://i-25887-2-4-develop.instances.magento-community.engineering/admin_bcd2)
Login: `5082bb5b` Password: `5bc03f52e192`
Instance will be terminated in up to 3 hours.

**Comment by abdulmalik422** [comment]
Any Progress on this?  I'm also facing this error on magento 2.3.3 / 2.3.4

**Comment by pbh-stu** [comment]
> Any Progress on this? I'm also facing this error on magento 2.3.3 / 2.3.4

my advice is to turn off in context checkout and it will work, not ideal if you like in context checkout buts that's magento for ya.

**Comment by engcom-Delta** [comment]
@pbh-stu , @testmagento2 I'm not able to reproduce issue by steps you described on clean 2.4-develop and on the latest composer version 2.4.1
**Manual testing scenario:**
- Create simple product
- Configure Paypal express Checkout with sandbox credentials
![#25884IssueCheckout](https://user-images.githubusercontent.com/51681379/96500056-f44b6000-1256-11eb-8b22-1740971dbba4.png)
- Add product to cart and go to checkout page

**Result:**
:heavy_check_mark: Place order by Paypal express Checkout without errors
![Screenshot from 2020-10-19 21-51-29](https://user-images.githubusercontent.com/51681379/96500084-02997c00-1257-11eb-9254-4c327286d805.png)
![Screenshot from 2020-10-19 21-52-24](https://user-images.githubusercontent.com/51681379/96500093-05946c80-1257-11eb-95b1-d662feb4ced2.png)
![Screenshot from 2020-10-19 21-53-06](https://user-images.githubusercontent.com/51681379/96500099-07f6c680-1257-11eb-9d64-7a6ce4fbe1fd.png)
![Screenshot from 2020-10-19 21-55-00](https://user-images.githubusercontent.com/51681379/96500105-0a592080-1257-11eb-95f2-3cfd90bdf815.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
