### ISSUE TITLE
API is not available for customer's cart

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2588]
There is no api available to get the details of assigned cart to a customer. i want to get the details cart which is assigned to a particular customer, then what should i do?

**Comment by ishakhsuvarov** [comment]
@arunkasyakar Please refer to `quoteCartRepositoryV1` [section of REST api documentation](http://devdocs.magento.com/swagger/index.html#!/quoteCartRepositoryV1).

**Comment by arunkasyakar** [comment]
@ishakhsuvarov in quoteCartRepositoryV1 section we can get the details of a cart by using cartId, what if i have the customerId, i mean if i want to get the cart details for a customer then which api call will help me out

**Comment by ishakhsuvarov** [comment]
@arunkasyakar You may try using `GET /V1/carts/search`.

The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) site if you have additional questions.  Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
