### ISSUE TITLE
Country options works incorrectly when edit user addresses 

### ISSUE THREAD

**Issue by BKorotkiy** [magento/magento2#25883]
### Preconditions (*)

1. Magento 2.3.3
2. Stock Magento 2.3.3 with Sample Data

### Steps to reproduce (*)

1. In _Admin Panel_ -> _Stores_ -> _General_ -> _General_ -> _Country Options_ select **Default Country**: United States and in **Allow Countries** select one country: United States, click **Save Config**.
2. Refresh Magento's cache.
3. Go to _Customer_ -> _All Customers_ -> _Select any customer for edit_ -> _Addresses_ -> _Add New Address_ (or edit existing address).
4. Check the "Country" dropdown values. 

### Expected result (*)

1. Selected country in configuration are displayed . 

### Actual result (*)

1. Dropdown has not any values. 
[
![issuemagento](https://user-images.githubusercontent.com/51643095/70041114-38912b80-15c5-11ea-933b-aa2637c55774.png)
](url)

### Additional Information (*)

1. When selected in _Admin Panel_ -> _Stores_ -> _General_ -> _General_ -> _Country Options_  in **Allow Countries** select five country: United States, Uruguay, U.S. Outlying Islands, U.S. Virgin Islands,  Uzbekistan and click **Save Config**.
2. Refresh Magento's cache.
3. In _Customer_ -> _All Customers_ -> _Select any customer for edit_ -> _Addresses_ -> _Add New Address_ (or edit existing address) 
4. Dropdown has incorrect data
![Selection_332](https://user-images.githubusercontent.com/51643095/70043305-e520dc80-15c8-11ea-8c73-6849c38e27e7.png)
![Selection_333](https://user-images.githubusercontent.com/51643095/70043314-ec47ea80-15c8-11ea-8fe6-1a7004e65e6f.png)

**Comment by BKorotkiy** [comment]
yes

**Comment by BKorotkiy** [comment]
@magento yes

**Comment by krishprakash** [comment]
Hi @BKorotkiy. Thank you for your report.
Issue is already open
You can review the conversation at #25218
