### ISSUE TITLE
Alert appears twice when the folder creation is not successful

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25898]
### Preconditions (*)

1. M 2.3.3
2. Adobe Stock is configured

### Steps to reproduce (*)

1. On CMS edit page open media gallery
2. Click "Create Folder"
3. Type in "папка"
4. Click "OK"
5. When alert with a message "Please rename the folder Please rename the folder using only letters, numbers, underscores and dashes." appears, click "OK"
6. Click anywhere on the dark overlay

### Expected result (*)

1. I can get rid of the overlay

### Actual result (*)

1. The same alert second time

**Comment by AnnaShepa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25898-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25898-2-3-develop.instances.magento-community.engineering/admin](https://i-25898-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment]
Hi @TomashKhamlai  please try to reproduce on clean magento and may be fill more info to reproduce, as currently I'm getting only one message.

**Comment by TomashKhamlai** [comment]
@AnnaShepa, I am going to reopen after ASI release.
