### ISSUE TITLE
Currency caching issue Magento 2.3.3

### ISSUE THREAD

**Issue by Kleibert** [magento/magento2#25890]
Summary of the issue
Currency selection does not work.
### Preconditions (*)

Change currency to  in Magento currency selector header bar, but the prices not update  on homepage ,they keep the last currency
 ### Expected result (*)

I would like to show the new currency for the products.
### Actual result (*)

![Screen Shot 2019-12-03 at 7 32 28 PM](https://user-images.githubusercontent.com/42814600/70101715-d1469c00-1603-11ea-9199-ac6e3a31292c.png)

**Comment by engcom-Echo** [comment]
Hello @Kleibert 

Thank you for your report and collaboration!
We are not able to reproduce this issue on the 2.3.3 branch by provided steps.

**Testing scenario:**

**Preconditions:**

1. Magento 2.3.3
2. Simple product is created
3. Euro currency added

**Steps to reproduce:**

1. Go to Content -> Pages
2. Select -> Edit on "Home Page"
3. In Content section click on the "Show / Hide Editor" button
4. Click on the "Insert Widget..." button
5. Select "Widget Type" as "Catalog Products List" -> "Insert Widget" -> Save
6. Go to frontend
![CA](https://user-images.githubusercontent.com/51681435/70134454-cf76ea00-1690-11ea-951c-c3515ecc75b1.png)
7. Change Currency to Euro

**Result**
Currency is changed successfully.
![euro](https://user-images.githubusercontent.com/51681435/70134477-d9005200-1690-11ea-89a8-67d13ea70991.png)
Thank you!

**Comment by Kleibert** [comment]
Thanks, it's work !
