### ISSUE TITLE
A "500 (Internal Server Error)" appears in Developer Console if Delete the image that is added to Page Content

### ISSUE THREAD

**Issue by chalov-anton** [magento/magento2#25893]
### Preconditions (*)
1. Magento 2.3-develop 

### Steps to reproduce (*)
1. From Magento Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**, click **Show/Hide Editor**, click **Insert Image**
3. Click **Chose file** and browse for any image file from your computer, **Open**
4. In _Insert File..._ window select the previously opened image file and click **Add Selected**
5. From **Content** click **Insert Image** again. Select the previously added image and **Delete Selected**
6. Close the **Insert File...** window (X) 
7. Open the Developer Console in your web browser (F12 key)
8. Click **Show/Hide Editor**
### Expected result (*)
No error appears in Developer Console
### Actual result (*)
A _"500 (Internal Server Error)"_ appears in Developer Console
![500 internal server error_deleate added image](https://user-images.githubusercontent.com/45624059/70122172-cda12c80-1678-11ea-8c76-11063aeebd31.gif)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25893-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25893-2-3-develop.instances.magento-community.engineering/admin](https://i-25893-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29380` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by andrewbess** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @andrewbess. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, here is your [Magento instance](https://i-25893-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25893-2-3-develop.instances.magento-community.engineering/admin](https://i-25893-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @chalov-anton. Thank you for your report. 
The issue has been fixed in magento/magento2#25924 by @edenduong in 2.4-develop branch
Related commit(s):
 - [37a9929ad036fd8e8309111d87f8ce7f1e0e35cc](https://github.com/magento/magento2/commit/37a9929ad036fd8e8309111d87f8ce7f1e0e35cc)
 - [66bf8d18bf6d5f88ffd5dc674106c52a8fd066a2](https://github.com/magento/magento2/commit/66bf8d18bf6d5f88ffd5dc674106c52a8fd066a2)
 - [ab4fa339c24d0868fa7471d347ac98ad22f4d3fe](https://github.com/magento/magento2/commit/ab4fa339c24d0868fa7471d347ac98ad22f4d3fe)

The fix will be available with the upcoming 2.4.0 release.
