### ISSUE TITLE
 Object of class Magento\Framework\DataObject could not be converted to string in /home/xxx/public_html/vendor/magento/framework/Escaper.php on line 247

### ISSUE THREAD

**Issue by varun2287** [magento/magento2#25892]
Hi,
Summary of the issue-
I have found this issue with my subcategory pages, when i try to open some of my subcategory from the navigation bar i got this error on my page.

Information of the environment-
Magento 2.3.3
Php 7.1

Steps to reproduce-
1- After ugrading from magento 2.2.4 to 2.3.3 
Expected Result-
No errors

Actual Result-
It says something is not good in Escaper.php on line 247.
I have also attached the screenshot of the file.
Although it is happening to only some subcategories and other categories are opening fine.
Screenshot
![Screenshot (13)](https://user-images.githubusercontent.com/35400881/70118912-2976b000-168f-11ea-89ec-061fa517686b.png)

Please help
Thanks

**Comment by AjayKrP** [comment]
Getting same error
`Recoverable Error: Object of class Magento\Framework\DataObject could not be converted to string in ../vendor/zendframework/zend-escaper/src/Escaper.php on line 167`
Any update on this?

**Comment by engcom-Charlie** [comment]
Hello @varun2287 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the Magento 2.3.3 after upgrade from 2.2.4

**Testing scenario:**

1. Install Magento 2.2.4
2. Create some categories with subcategories & products
![category2 2 4 from 2019-12-05 13-31-00](https://user-images.githubusercontent.com/51680850/70238432-eccfb500-1771-11ea-9639-6d0d28bd7346.png)

3. Upgrade to 2.3.3
4. Check all categories on frontent

**Result:**
All categories are opening without errors
**GIF:**
![Peek 2019-12-05 15-16](https://user-images.githubusercontent.com/51680850/70238680-71bace80-1772-11ea-8fb1-8686107e116b.gif)

So i have to close this issue as not reproducible. 

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

Thanks for your report!

**Comment by AjayKrP** [comment]
@engcom-Charlie This issue was coming in configurable out of stock product. Did you checked that also?

**Comment by AjayKrP** [comment]
![Screenshot from 2019-12-06 09-48-32](https://user-images.githubusercontent.com/23704820/70295741-1b9b6900-180e-11ea-9626-1a5689ef79dc.jpg)

Here is the screenshot of the error

**Comment by AjayKrP** [comment]
Finally got solution: 
Need to serialize `<?php $rating = serialize($block->getRatingSummary()) ?>` in `vendor/magento/module-review/view/frontend/templates/helper/summary_short.phtml` on line 13.

**Comment by varun2287** [comment]
Hi @AjayKrP 
Thank you for the solution, it solved my problem also.

**Comment by rumbdev** [comment]
thanks a lot @AjayKrP , 
that solved our issue too.
Note that the exception will be hidden in production mode but in developer the exception will be thrown. We noticed it in production though, due to the fact that a particular search term was not found in catalogsearch fulltext (both with Elasticsearch6 and Mysql).
That can turn in a nightmare in a catalog with ten of thousands of products.
This is a bug present in Magento 2.3.3 but it is not easily reproducible, especially due to the fact that in production it won't throw an exception but will only affect returned fulltext result (using both Mysql and Elastic6). You must find which term present in catalog is not returned in a fulltext then switch to developer mode and check if the exception is thrown.
I hope your fix will be included in future Magento releases, that is a MAJOR BUG.

**Comment by DeElfos** [comment]
@AjayKrP I'm Brazilian and my English is terrible but come on.

I followed your suggestion and doing some tests I came up with a solution that does not demonstrate a JSON in should mode and presents the data correctly.

My Version: 2.3.4

Suggestion: Need to serialize `<?php $rating = serialize ($block->getRatingSummary())?>` In 

`vendor/magento/module-review/view/frontend/templates/helper/summary_short.phtml on line 13.`

My solution: `<?php $rating = $block->getRatingSummary()->getRatingSummary())?>`

**Comment by AjayKrP** [comment]
> @AjayKrP I'm Brazilian and my English is terrible but come on.
> 
> I followed your suggestion and doing some tests I came up with a solution that does not demonstrate a JSON in dev mode and presents the data correctly.
> 
> My Version: 2.3.4
> 
> Suggestion: Need to serialize `<?php $rating = serialize ($block->getRatingSummary())?>` In
> 
> `vendor/magento/module-review/view/frontend/templates/helper/summary_short.phtml on line 13.`
> 
> My solution: `<?php $rating = $block->getRatingSummary()->getRatingSummary())?>`
> 
> Edit.: 1
> 
> Doing some tests, I found that errors occurred in the list format and in other points, here is the correction:
> `vendor/magento/module-review/view/frontend/templates/helper/summary_short.phtml` e `vendor/magento/module-review/view/frontend/templates/helper/summary.phtml`
> 
> `<?php $rating = serialize ($block->getRatingSummary())?>`
> to:
> 
> ```
> <?php
>     if (is_string($block->getRatingSummary())) {
>      $rating = $block->getRatingSummary();
>     } else {
>      $rating = $block->getRatingSummary()->getRatingSummary();
>     }
> ?>
> ```

Thanks @DeElfos that's a great.
