### ISSUE TITLE
Mobile design issues in Minicart Dropdown Dialog

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#25901]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Add item to cart.
2. Now open minicart dropdown dialog in mobile Portrait and Landscape view.
3. Change the qty and click out of the qty box so that update button will be displayed

### Expected result (*)

1. Update button should not overlap with item qty field

![update-cart-expected-result](https://user-images.githubusercontent.com/54176640/70148650-93617a80-16cc-11ea-9cbf-de5232193562.png)

2.  Edit icon should be visible in mobile landscape view

![edit-delete-expected](https://user-images.githubusercontent.com/54176640/70150074-61054c80-16cf-11ea-83c0-b2b28a2e44ca.png)

### Actual result (*)

1. Update button overlaps with item qty field

![update-cart](https://user-images.githubusercontent.com/54176640/70147779-f81bd580-16ca-11ea-9e34-2baac2cc9ac6.png)

2.  Edit icon is not visible in mobile landscape view

![edit-hide](https://user-images.githubusercontent.com/54176640/70150154-87c38300-16cf-11ea-8852-e0196ba13987.png)

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25901-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25901-2-3-develop.instances.magento-community.engineering/admin](https://i-25901-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@itsPranith Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by divyajyothi5321** [comment]
I am unable to add the labels after this issue is posted

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29389` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by thurow** [comment]
Looks like this issue has already been solved on [#25206](https://github.com/magento/magento2/pull/25206). I'm closing this issue.
