### ISSUE TITLE
LNMP Magento 2.3.3 can not use CMS No Route page 

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#25902]
### Preconditions (*)

1.CentOS 7.6 + Nginx 16 + MySQL 5.6 + PHP 7.3
2.Clean install Magento 2.3.3

### Steps to reproduce (*)

1.I use Composer install magento 2.3.3. no problems in nginx config
2.stores > configuration > general > web > default page , settings are correct.
![TIM截图20191204222934](https://user-images.githubusercontent.com/45879513/70150881-b9474900-16e5-11ea-804c-c5fab30e05fb.jpg)
3. go to frontend and input something in address bar, click enter 
![TIM截图20191204223357](https://user-images.githubusercontent.com/45879513/70151247-47233400-16e6-11ea-9a75-9ac97683b45d.jpg)

### Expected result (*)

1. Go to cms no route page like this 
![TIM截图20191204223538](https://user-images.githubusercontent.com/45879513/70151354-75a10f00-16e6-11ea-9450-c9439fb24dde.jpg)

### Actual result (*)

1. nginx default 404 page like this 
![TIM截图20191204223646](https://user-images.githubusercontent.com/45879513/70151423-91a4b080-16e6-11ea-8e84-f234d4d990d0.jpg)

This function is normal in version 2.2.x. But when I upgraded to 2.3.x, it couldn't display normally.

**Comment by engcom-Echo** [comment]
Hello @Yuwei9291 

Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.3.3 branch by provided steps.

**Testing scenario:**

**Preconditions:**
Nginx/1.14.0 (Ubuntu)

**Steps to reproduce:**

1. Go to frontend 
2. Type something in address bar, click enter

**Result:**
404 Page is shown. URL is not changed, which is correct.
![rout](https://user-images.githubusercontent.com/51681435/70164607-251bb880-16ca-11ea-807e-40bd6ce35b97.png)
Could you provide more details for reproduce this issue?

**Comment by Yuwei9291** [comment]
Oh sorry, problem solved when I add "#" in front of "error_page 404 403 = /errors/404.php;" in nginx.conf.sample row 34 .
Maybe we should update this file ?

**Comment by Yuwei9291** [comment]
> Hello @Yuwei9291
> 
> Thank you for your report and collaboration!
> I am not able to reproduce this issue on the 2.3.3 branch by provided steps.
> 
> **Testing scenario:**
> 
> **Preconditions:**
> Nginx/1.14.0 (Ubuntu)
> 
> **Steps to reproduce:**
> 
> 1. Go to frontend
> 2. Type something in address bar, click enter
> 
> **Result:**
> 404 Page is shown. URL is not changed, which is correct.
> ![rout](https://user-images.githubusercontent.com/51681435/70164607-251bb880-16ca-11ea-807e-40bd6ce35b97.png)
> Could you provide more details for reproduce this issue?
Oh sorry, problem solved when I add "#" in front of "error_page 404 403 = /errors/404.php;" in nginx.conf.sample row 34 .
Maybe we should update this file ?

**Comment by engcom-Echo** [comment]
> Oh sorry, problem solved when I add "#" in front of "error_page 404 403 = /errors/404.php;" in nginx.conf.sample row 34 .
> Maybe we should update this file ?

Hello @Yuwei9291 

I don't think this is an issue in Magento 2. Please refer to [Nginx Support](https://nginx.org/ru/support.html) for advice or general discussion about this.

Thank you!
