### ISSUE TITLE
Issue when searching for related, up and cross sells

### ISSUE THREAD

**Issue by bartdelvaux** [magento/magento2#2592]
On the product edit page, when you are searching for related, up and cross sell products, and you hit the enter button when one of the filter fields is active, the product form will be submitted instead of the search form. 

This causes that the product will be saved. Normally I would expect that you will search in the grid of related products instead of saving the product (like it is in Magento 1).

**Comment by zamboni084** [comment]
Having the same issue!

**Comment by markoshust** [comment]
This is a pretty big UI issue for anything adding/editing crossell/upsell/related items. Need an `e.preventDefault

**Comment by markshust** [comment]
This is a pretty big UI issue for anything adding/editing crossell/upsell/related items. Need an `e.preventDefault` added someplace -- should be an easy fix

**Comment by vzabaznov** [comment]
@bartdelvaux thanks for reporting, our functionality has been changed and bug cannot be reproduced
Fell free to write comment, or open a new GitHub issue if you feel that issue has not been resolved
