### ISSUE TITLE
Regular Price Label Alignment Issues in Frontend

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#25936]
### Preconditions (*)

1.Magento 2.3.3 and Magento 2.4

### Steps to reproduce (*)

1. Admin->Catalog->Products->Add Product
2. Add Price ex:$20
3. Click on Advanced Pricing  and add regular price ex:$10
4. Save the product
3. Open product in frontend

### Expected result (*)

1.  Advanced Pricing should be Aligned in single line

 ![regularprice-expectedresult](https://user-images.githubusercontent.com/54176640/70319881-65ee0b80-1849-11ea-931c-518d0791ff1f.png)

### Actual result (*)

1. Advanced Pricing Alignment is not Proper

![regularprice-actuvalresult](https://user-images.githubusercontent.com/54176640/70319893-6e464680-1849-11ea-81fd-e84eb23a25f6.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29501` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hitesh-wagento** [comment]
I am working on this issue

**Comment by dmytro-ch** [comment]
Hi @divyajyothi5321 , feel free to create the pull requests with minor fixes and obvious improvements without opening the issues.

Thank you!

**Comment by VladimirZaets** [comment]
Hi @divyajyothi5321. Thank you for your report. 
The issue has been fixed in magento/magento2#26237 by @divyajyothi5321 in 2.4-develop branch
Related commit(s):
 - [c39e85c84449f86b2c9d27d377e548547273883f](https://github.com/magento/magento2/commit/c39e85c84449f86b2c9d27d377e548547273883f)

The fix will be available with the upcoming 2.4.0 release.
