### ISSUE TITLE
Integration Success Message Text Overflow Issue in Admin

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#25930]
### Preconditions (*)

1. Magento 2.3.3
 

### Steps to reproduce (*)

1. Go to admin->System->Extenstions->Integrations
2. Add new integration name with 255 characters and save the integration

### Expected result (*)

1. Success message should not disturb the page

### Actual result (*)

1. 
![integrationsuccessmess-actual](https://user-images.githubusercontent.com/54176640/70312506-c6754c80-1839-11ea-96ab-dbea20c8ba04.png)

2. Success message disturbing the page

**Comment by kanthy-magento** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25930-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25930-2-4-develop.instances.magento-community.engineering/admin](https://i-25930-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
Hi ,

I'm able to replicate this issue on CE-2.4 @https://i-25930-2-4-develop.instances.magento-community.engineering/


![image](https://user-images.githubusercontent.com/56586384/70313674-13f2b900-183c-11ea-85d1-f26c9957458b.png)

**Comment by magento-engcom-team** [comment]
@itsPranith Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29493` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheer-gajjala** [comment]
@magento-engcom-team what will be the suggested fix for this issue. Should the name filed be restricted to certain characters or the message should be trimmed ??

**Comment by VladimirZaets** [comment]
Hi @divyajyothi5321. Thank you for your report. 
The issue has been fixed in magento/magento2#26011 by @divyajyothi5321 in 2.4-develop branch
Related commit(s):
 - [70b199cd3660b9e581c618f27ac7adc7db3c4114](https://github.com/magento/magento2/commit/70b199cd3660b9e581c618f27ac7adc7db3c4114)

The fix will be available with the upcoming 2.4.0 release.
