### ISSUE TITLE
Email address mismatch with text in iPad(768) view

### ISSUE THREAD

**Issue by renard123** [magento/magento2#25935]
Email address mismatch with text in iPad view

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
1. Front end 
2. Register with email like "renard1.abcdefgtest56hijklm@gmail.com"
3. Review the my account dashboard in iPad view

### Expected result (*)
Email should not be mismatch with edit link

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/70320848-be260d00-184b-11ea-96d7-5512f6b023fc.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29500` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-25935-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25935-2-4-develop.instances.magento-community.engineering/admin](https://i-25935-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#25942 by @edenduong in 2.4-develop branch
Related commit(s):
 - [183dd645b733a65d57b3bf6ad42daef6da75923a](https://github.com/magento/magento2/commit/183dd645b733a65d57b3bf6ad42daef6da75923a)

The fix will be available with the upcoming 2.4.0 release.
