### ISSUE TITLE
MySQL is deprecated but Web Install doesn't support elasticsearch

### ISSUE THREAD

**Issue by NationwidePharma** [magento/magento2#25938]
### Preconditions (*)

1.  Magento 2.3.3
2.  When doing installation via the Web, user is prompted to enter database information.  I think this loads after pre-requisite check.

### Steps to reproduce (*)

1.  Install Magento
2.  Access Magento site from url.

### Expected result (*)

1.  Expect instructions to install elasticsearch
2.  Expect interface to accept elasticsearch critera.

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/42869757/70329044-146d5e80-1800-11ea-9380-d5b0ccf32fd2.png)
2.

**Comment by engcom-Charlie** [comment]
Hello @NationwidePharma @sdzhepa
This issue looks like a feature request.
@sdzhepa could you transfer this issue to the Feature requests repository?
Thanks for your collaboration!

**Comment by ihor-sviziev** [comment]
@engcom-Charlie I don't agree. This is not the feature, this is a bug, as you can't configure "recommended" search engine with web installer.

**Comment by korostii** [comment]
Is this still an issue, you really cannot set up elasticsearch connection during setup? @magento-engcom-team  @sdzhepa 
Just a reminder: since 2.4, having elasticsearch is an obligatory requirement for installing Magento, without the ability to setup elasticsearch connection the web setup would seem almost useless.

**Comment by ihor-sviziev** [comment]
Hi @NationwidePharma @korostii,
Thank you for your report!
Support of web wizard was deprecated in 2.3.x and dropped in Magento 2.4.0, you can see it was shown in the docs for 2.3.x version https://docs.magento.com/user-guide/v2.3/system/web-setup-wizard.html
![image](https://user-images.githubusercontent.com/1873745/92564757-5ab98780-f282-11ea-9220-c73eb96ef730.png)

As alternative you could install Magento using CLI https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli.html

As this functionality was already removed, I'm closing this issue as not relevant anymore.
