### ISSUE TITLE
Theme view.xml image background property issue

### ISSUE THREAD

**Issue by Weltpixel** [magento/magento2#2593]
Hi,

There seems to be a problem with the background property.
Recoverable Error: Argument 1 passed to Magento\Catalog\Model\Product\Image::setBackgroundColor() must be of the type array, string given
It requires an array for the  $rgbArray parameter public function setBackgroundColor(array $rgbArray)  
If i do a forced casting in it is working.

This is the schema for it

``` xml
<xs:element name="background" minOccurs="0">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\[(\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
```

Am i using an in-proper value for background property ?

This is my example.

``` xml
 <image id="category_page_grid" type="small_image">
                <width>250</width>
                <height>250</height>
                <aspect_ratio>false</aspect_ratio>
                <transparency>false</transparency>
                <background>[255,0,0]</background>
            </image>
```

THanks for checking,

**Comment by voleye** [comment]
Hi @Weltpixel, thank you for helping us make Magento better!

We have created internal "MAGETWO-50397" to track this.

**Comment by shiftedreality** [comment]
Fix was delivered to develop branch.
Closed.
