### ISSUE TITLE
Connect Manager Missing

### ISSUE THREAD

**Issue by seanlewisokc** [magento/magento2#2594]
Connect Manager is missing after install.

**Comment by daim2k5** [comment]
What do you mean with "Connect Manager" ? The Backend where you can install packages from magentocommerce.com?

**Comment by seanlewisokc** [comment]
Yes. The Magento Connection Manager. There is no download folder.

**Comment by daim2k5** [comment]
System -> Web Setup Wizard

The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) site if you have additional questions.  Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by seanlewisokc** [comment]
This is a technical issue. The Connection Manager to install themes or extensions is not found. Not listed in Component manager either.

**Comment by seanlewisokc** [comment]
Please reopen issue

**Comment by davidalger** [comment]
@seanlewisokc The downloader you're referring to is a part of Magento 1, but not Magento 2. @daim2k5 pointed you to the correct place in the admin, and the forums if you have further questions. This is not a bug in Magento 2, which is what this tracker is intended to be used for.
