### ISSUE TITLE
Install new component with Component manager impossible

### ISSUE THREAD

**Issue by quienti** [magento/magento2#2595]
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/11565373/0f41546a-99de-11e5-9818-4f3751dcacce.jpg)

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11565339/d2a765c6-99dd-11e5-9d68-ae9a7a9e6ecd.jpg)

My website work fine

**Comment by mazhalai** [comment]
@quienti you have not specified if you setup the [required crons and updater](http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_compman-updater.html).

**Comment by quienti** [comment]
Ok, I have setup cron and updater, but after install updater, I hava this issue from all page

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11566424/a4b660ae-99e2-11e5-8312-759cf41b7c4c.jpg)

**Comment by mazhalai** [comment]
Looks like you registered(via registration.php) a new module with same name as `Magento_CmsUrlRewite`. Please rename that to your own module name. It is thrown [here](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Component/ComponentRegistrar.php#L49)

**Comment by quienti** [comment]
I don't understand what I need to do...

And I have just install Magento 2.0, cron and updater
Why I need to change "Magento_CmsUrlRewite" ?

**Comment by mazhalai** [comment]
Can you please give more details how did you install Magento2.0? What version? Also, if you have any custom modules? Or a previous installation?

**Comment by quienti** [comment]
I installed Magento CE 2.0.0 and I never install custom module
This my first installation

**Comment by mazhalai** [comment]
But did you download the `zip` file, or install after `git clone` or `composer create-project`? Also did you use CLI or Web Setup? I would suggest to clean all caches, Magento's as well as browser.

**Comment by quienti** [comment]
I used zip file, I installed in first composer by ssh, after I used Web-Setup
And of course, I have clean Magento's cache and Re-Index by ssh

**Comment by mazhalai** [comment]
Can you perform a search on all `registration.php` files for `Magento_CmsUrlRewite` and post paths?

**Comment by quienti** [comment]
I don't understand, but I have 2 "Magento_CmsUrlRewite"

Before installation Updater and Cron
1 here => app/code/Magento/CmsUrlRewrite

After installation Updater and Cron
1 here => app/code/Magento/CmsUrlRewrite
and
1 here => /vendor/magento/module-catalog-url-rewrite

**Comment by mazhalai** [comment]
I would suggest to delete all files and start over by unzipping the files, and only setting up the cron jobs. I think this is the case since you had zip files (which already has the `update` folder) and you installed updater again. The instructions clearly says that is for `Contributing developers only` which is deployed via `git clone.`

**Comment by quienti** [comment]
I used zip from this github, so this zip aren't Update folder
This very strange...

**Comment by quienti** [comment]
Ok, I have found my problem with Updater

But now, I have a another problem

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11585788/c5d99fda-9a6e-11e5-8092-94e428aca574.jpg)

When I look here to try to resolve my problem : http://devdocs.magento.com/guides/v2.0/comp-mgr/trouble/cman/cron.html

I can see that : 

> Run the updater cron job
> Change to the <your Magento install dir>/update directory.
> Enter the following command:
> php cron.php

But, I don't have cron.php in my folder update

![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/11585883/7aaaeacc-9a6f-11e5-811c-1c323f933758.jpg)

Any idea ?

**Comment by ghost** [comment]
FWIW, this is what I see:

[magento_user@centos6-2 update]$ pwd
/var/www/html/magento2/update
[magento_user@centos6-2 update]$ ls -1
app
composer.json
composer.lock
cron.php
dev
index.php
pub
README.md
var
vendor

**Comment by quienti** [comment]
Sorry, but I don't understand...

**Comment by ghost** [comment]
You said you didn't see cron.php in the update directory... something must have gone wrong with your installation. How did you start, using a zip, cloning the repo, or composer create-project?

In any of the above cases, cron.php should be in the update directory.

**Comment by quienti** [comment]
I used a zip from this github ( version 2.0.0 ), then I installed with composer and after, I used Web-Setup to finish my installation

**Comment by ghost** [comment]
I believe that's equivalent to cloning the repo.

Maybe you should delete the update folder, [clone the updater repo again](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/prereq_updater.html), and copy it again. As you can see, [cron.php](https://github.com/magento/magento2-community-edition/blob/master/update/cron.php) is in that repo.

**Comment by mazhalai** [comment]
When we refer to zip version, we refer to the zipped package that can be downloaded from magento.com
The git version is meant for contributing devs, and since it is not installed via composer, it does not include the update folder, since component manager and updater rely on composer to check dependencies for various components in the system. Please refer to [this doc](http://devdocs.magento.com/guides/v2.0/install-gde/continue.html) which explains which way of installation makes sense, based on what you want to do.

**Comment by quienti** [comment]
Ok, I understand now, I think

Thank you for your help !

**Comment by DevMostafa** [comment]
Component Manager not showing for me.
In Admin: When I clicked on "System->Web Setup Wizard", it redirects me to the "Dashboard".
