### ISSUE TITLE
Google Shopping Ads - one website with different store domains

### ISSUE THREAD

**Issue by onepack** [magento/magento2#25960]
### Preconditions (*)

1. M 2.3.3

### Steps to reproduce (*)

1. Create 1 website end 4 store views with different domains
2. Connect to GMC

### Expected result (*)

1. Expect to start selling per domain after claiming the domains

### Actual result (*)

1. The website main Domain is connected to the GMC account
2. All products on other domains fail and due to all errors related to this nothing actually works.
3. Calling Google results in the notice that the **Magento account connected to GMC is already a Multi domain account** and there cannot be a multi-domain account under a multi domain account.
4. It seems that you basically need a website for every domain in your shop and connect every website to a GMC account. One website with multi domains just doesn't work.

**Comment by rmanor1** [comment]
Hello, this should probably be closed as we've deprecated the Google Shopping ads Channel, and the [service was shut down ](https://docs.magento.com/user-guide/sales-channels/google-eol.html)as of Apr 28th.
