### ISSUE TITLE
Temando breaking functionality in 2.3.3

### ISSUE THREAD

**Issue by george-vlahakis** [magento/magento2#25979]
There are multiple reports on the web about Temando throwing and error when you try to edit a product:

temando.CRITICAL: "accountId" is required. Enter and try again.

### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Stock install try to edit a product

### Expected result (*)
1. No error

### Actual result (*)
1. Error
`temando.CRITICAL: "accountId" is required. Enter and try again. {"exception":"[object] (Magento\\Framework\\Exception\\InputException(code: 0): \"accountId\" is required. Enter and try again. at /home/user/m23composer/vendor/magento/framework/Exception/InputException.php:91)"}`

Furthermore to the above, various people are proposing to disable the module but that does not actually work because more errors will occur due to the module's attributes still being in the database with a source model referencing their module. 

We tried removing the attributes from the attribute set and got past it but then getting into Google Shopping Ads which searches for is_visible = 1 (and matches these attributes again) breaks.

We cannot uninstall it and we cannot fix it without messing about in the db tables.

**Comment by george-vlahakis** [comment]
> Hi @georgios-2317. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @georgios-2317 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

Yes my dear bot, I have stated it above that the error is in "vanilla" Magento. 😉

**Comment by magento-engcom-team** [comment]
Hi @georgios-2317. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @georgios-2317, here is your [Magento instance](https://i-25979-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25979-2-4-develop.instances.magento-community.engineering/admin](https://i-25979-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by george-vlahakis** [comment]
> Hi @georgios-2317. Thank you for your request. I'm working on Magento 2.4-develop instance for you

No my dear bot... I want a working 2.3.3 Magento instance... (is this nuts or what)?

**Comment by george-vlahakis** [comment]
Temando is not part of dev 2.2.4 ... hence there is no error. (ridiculous)

**Comment by gujjwal00** [comment]
It was triggered by the command in quoted text.

PS: Your name has been added to 'The List' of Skynet 👽 for being hostile towards a fellow bot . 😋

**Comment by jorgb90** [comment]
Really **** extension that should be removed.

**Comment by janmyszkier** [comment]
I understand this is the moment Magento finally comes up with a solution that does NOT store the class reference in the database which will finally allow us to disable the modules we do not want anymore. Can't wait :)
PS. multiple instances affected, spamming our logs.

**Comment by sdzhepa** [comment]
Magento stops supporting of Temando module. Please see more details https://magento.com/shipping
Long story short: 
- The extension owner does not work and support this module anymore.
- Magento will support "_existing customers until November 15, 2020_" only through the support channel associated with your Magento account. 
- In the internal Magento backlog there is a ticket to completely remove Temando from Magento.
