### ISSUE TITLE
Can´t edit any product on backend

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#2597]
Just installed Magento 2 stable version in local machine, frontend works  fine and also backend, except I can´t edit products.

![magento2_bug_1](https://cloud.githubusercontent.com/assets/16081377/11567540/be63e7ec-99e7-11e5-94dc-d24a003be846.jpg)

**Comment by salelsol** [comment]
- Hi, just fixed for a particular attribute set, disabling older attribute in data importing without your corresponding associated extension.

**Comment by katmoon** [comment]
Hi salelsol,

Have you found a workaround for the described issue?

**Comment by vkholoshenko** [comment]
Possibly related to #2462

**Comment by vkholoshenko** [comment]
Since we haven't heard back from you, we'll proceed with closing this issue. Feel free to reopen if you have additional info.
