### ISSUE TITLE
Not required spacing in submenu on hover desktop

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#25972]
### Summary

No space required in sub menu top and bottom .

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
Go to the Home page and hover menu.

### Expected result

1. No space required in sub menu top and bottom .
![expected](https://user-images.githubusercontent.com/23443991/70523884-f5f1c500-1b69-11ea-83fb-c025e96a8aea.png)

### Actual result

1. Space in sub menu top and bottom .
![actual](https://user-images.githubusercontent.com/23443991/70524086-731d3a00-1b6a-11ea-93e9-572c44a216cf.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25972-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25972-2-4-develop.instances.magento-community.engineering/admin](https://i-25972-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29613` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#25973 by @hitesh-wagento in 2.4-develop branch
Related commit(s):
 - [200f51853bf8b5b10090d6ecd9abc46269ca364b](https://github.com/magento/magento2/commit/200f51853bf8b5b10090d6ecd9abc46269ca364b)

The fix will be available with the upcoming 2.4.0 release.
