### ISSUE TITLE
Many cron processes can wait locks and consume resources 

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#25987]
### Preconditions (*)

magento 2.3.x

1. Cron observer uses locks (db, cache, file or zookeper)
2. The job is locked after `cron:run` is sent to shell
see this method 
`\Magento\Cron\Observer\ProcessCronQueueObserver::execute`

The problem, I suppose, that magetno uses the same method to run all groups or one group
in \Magento\Cron\Observer\ProcessCronQueueObserver::execute
it creates commands in shell
```
            if ($this->_request->getParam(self::STANDALONE_PROCESS_STARTED) !== '1'
                && $this->getCronGroupConfigurationValue($groupId, 'use_separate_process') == 1
            ) {
                $this->_shell->execute(
                    $phpPath . ' %s cron:run --group=' . $groupId . ' --' . Cli::INPUT_KEY_BOOTSTRAP . '='
                    . self::STANDALONE_PROCESS_STARTED . '=1',
                    [
                        BP . '/bin/magento'
                    ]
                );
                continue;
            }
```
and only then, it runs the command like this 
`php bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`
it goes to this part 
```
            $this->lockGroup(
                $groupId,
                function ($groupId) use ($currentTime, $jobsRoot) {
                    $this->cleanupJobs($groupId, $currentTime);
                    $this->generateSchedules($groupId);
                    $this->processPendingJobs($groupId, $jobsRoot, $currentTime);
                }
            );
```
Technically possible to remove all locks and run many `bin/magento cron:run &` and see dozens of created processes in shell
e.g. indexer `php bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`

### Steps to reproduce (*)

1. Run `bin/magento cron:run &` a few times in background
2. See that it creates more than 1 process in shell
eg `php bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`

### Expected result (*)

1. If in shell one cron command is running the second should not be created
2. only one unique shell command should be processed
3. Lock for process or group should be checked before the command goes to shell

### Actual result (*)

1. Magento can create many processes at time
2. May simultaneously running processes check locks wait and consumes server resources
3. Lock for process or group is checked after the command is in shell
![Selection_248](https://user-images.githubusercontent.com/3192770/70610382-c5f70000-1c03-11ea-8d21-976373e41c19.png)
  
GIF:
![cron-lock](https://user-images.githubusercontent.com/3192770/70735378-6fc2b380-1d0e-11ea-8675-e7d09f9322a0.gif)

WORKAROUND:
Install each cron group separetely with flock instead adding default cron:run in crontab.

**Comment by engcom-Charlie** [comment]
Hello @ilnytskyi 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.
![1](https://user-images.githubusercontent.com/51680850/70710418-cff22f00-1ce7-11ea-8da9-13a3f3a7629b.png)
![3](https://user-images.githubusercontent.com/51680850/70710492-f87a2900-1ce7-11ea-9d6f-904a8d55b3be.png)

**Result:**
- `cron:run group` shows same behavior like as `cron:run`
- in shell one cron command is running the second should not be created
- only one unique shell command should be processed
- Lock for process or group is checked before the command goes to shell
![4](https://user-images.githubusercontent.com/51680850/70710598-2c554e80-1ce8-11ea-8bea-5126d9bfb5c4.png)

Could you verify my steps?

**Comment by ilnytskyi** [comment]
@engcom-Charlie 
Yes sure 
just run a few commands in background 
`php bin/magento cron:run & php bin/magento cron:run & php bin/magento cron:run & php bin/magento cron:run & php bin/magento cron:run & php bin/magento cron:run &`

![cron-lock](https://user-images.githubusercontent.com/3192770/70735378-6fc2b380-1d0e-11ea-8675-e7d09f9322a0.gif)
> Lock for process or group is **not** checked before the command goes to shellt

You can see it on gif. Although on local fresh installation it goes fast this can be a problem on live server with high load.
And `flock` for `bin/magento cron:run` will not help since `cron:run` creates another processes that can wait for locks

mb smth like this for cron command can be used
``` 
'/usr/bin/flock -w 0 ' . BP . '/var/' . self::LOCK_PREFIX . $groupId . '.lock ' . $phpPath . ' %s cron:run --group=' . $groupId . ' --' . Cli::INPUT_KEY_BOOTSTRAP . '='
```
or this
```
            if ($this->lockManager->isLocked(self::LOCK_PREFIX . $groupId)) {
                continue;
            }
```
However I noticed some command still try to execute simultaneously in second solution, and using it in the loop can froze other jobs. Probably smth like first solution should be used on the shell level

**Comment by engcom-Charlie** [comment]
@ilnytskyi 
Thank you for contribution and collaboration!
i just reproduced with your updates.
Now i can confirm this issue.
![image](https://user-images.githubusercontent.com/51680850/70789451-bc080500-1d9b-11ea-83cf-8f9c73190b82.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29752` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ilnytskyi** [comment]
The workaround can be like this:
Remove general `cron:run` from crontab.
Add each group to crontab with flock separately or use any other custom locker.
`* * * * * flock /path/to/lock php bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`

**Comment by darshanperpule** [comment]
@ilnytskyi I am also facing the same issue in my prod environment.

**Comment by kilis** [comment]
Applied fix (by @driskell) for issue mentioned [here](https://github.com/magento/magento2/issues/26809) by back-porting fix from 2.4.3 to 2.3.5p2 and issue still persists even with fix. Today we deployed changes to live site and i still got duplicated cron groups having deadlocks. This issue is still relevant.

**Comment by HenKun** [comment]
Same here with fix applied to 2.4.1. Only thing that really works is the workaround from the issue creator: "Install each cron group separetely with flock instead adding default cron:run in crontab."

**Comment by driskell** [comment]
> Applied fix (by @driskell) for issue mentioned [here](https://github.com/magento/magento2/issues/26809) by back-porting fix from 2.4.3 to 2.3.5p2 and issue still persists even with fix. Today we deployed changes to live site and i still got duplicated cron groups having deadlocks. This issue is still relevant.

The deadlocks still occur? Or the cron_schedule table still grows? Or do you refer to this issue occurring of overlapping groups? There’s 3 issues referenced. Worth noting the PR targeted 2.4 in the end and I think might not work on 2.3 completely as there are many other changes in 2.4 to assist in fixing the same issue.

**Comment by driskell** [comment]
I’m not sure if there might be confusion between the SQL Deadlock exception the PR targets and what is happening here which I guess is a process deadlock (or process queuing) due to some form of serialisation

**Comment by kilis** [comment]
@driskell 
Issue it more RAM an CPU resources issue here in crons. Cron task groups get duplicated like described in this issue and cause server resources to get a deadlock in resources causing it hang so that its not usable.

**Comment by memen45** [comment]
Is this fixed now? And if so, from which version onwards is it safe to remove the flock from cron without flooding the memory?

**Comment by hostep** [comment]
@memen45: `flock` was our workaround before Magento 2.2.5. Since https://github.com/magento/magento2/pull/12497 got included in Magento 2.2.5, `flock` was no longer needed in my experience.
I would recommend to [change the lock provider](https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-lock.html#instgde-cli-lockconfig) that Magento uses by default (`db`) to `file` if you can on your current Magento version. I've seen the `db` one causing strange issues on servers that have a high load.

Magento then added another lock fix for crons in 2.3.5 by [MC-25132](https://github.com/magento/magento2/search?q=MC-25132&type=commits) and then there were some other smaller improvements done by https://github.com/magento/magento2/pull/28007 which got included in Magento 2.4.3, but I'm not entirely sure how much that last bit helps.

Not sure if this is the full story though, but maybe it helps?

**Comment by Adel-Magebinary** [comment]
This still happens in 2.4.2 community. Introduced flock and separated the corn group now. Will report back if it still happens.

**Comment by hostep** [comment]
@Adel-Magebinary: as mentioned in the post above yours, some extra [smaller improvements](https://github.com/magento/magento2/pull/28007) were made in Magento 2.4.3, maybe you could try to upgrade Magento first?

**Comment by ilnytskyi** [comment]
related topic: https://github.com/magento/magento2/issues/35639

**Comment by rukrlf** [comment]
> The workaround can be like this: Remove general `cron:run` from crontab. Add each group to crontab with flock separately or use any other custom locker. `* * * * * flock /path/to/lock php bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`

@ilnytskyi would you mind letting me know how to find the "/path/to/lock" in the flock command pls? I did a debug in my local environment and noticed the lock was generated in DB. It would be great if you could elaborate on if the lock is generated differently (like the lock is generated in a file) in the server when in production mode.
Thanks for your answer!

**Comment by ilnytskyi** [comment]
@ilnytskyi just put that path to any location you want, the lock files are created automatically
https://www.thegeekdiary.com/flock-command-examples-in-linux/

**Comment by rukrlf** [comment]
Hey Stanislav,

Thanks for your quick response! and thanks a lot for your answer!

Cheers mate!

**Comment by magento360** [comment]
we are still getting the same problem with Magento 2.4.5-p5. Any other solution?
