### ISSUE TITLE
copyFieldsetToTarget not working after upgrading from M2.3.1 to M2.3.3

### ISSUE THREAD

**Issue by not-art** [magento/magento2#25981]
### Preconditions (*)

1. Have Magento 2.3.1 installed
2. Add some custom fields to database tables quote and sales_order (lets say "custom1", custom2", and custom3"); ensure their names are the same & their types are varchar(255)
3. Follow this devdocs guide to copy custom1, custom2, and custom3 from quote to sales_order when creating an order: https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/copy-fieldsets.html

### Steps to reproduce (*)

1. After implementing the above guide in the pre-conditions to create the module to copy fields, add an item to your 2.3.1 store's cart
2. Update your user's quote to populate custom1, custom2, and custom3 with some data
3. Place your order on 2.3.1 (we're using the API to place the order with a customer REST token after completing payment in our custom payment system)
4. You'll see custom1, custom2, and custom3 are copied from quote to sales_order
5. Upgrade your M2 from 2.3.1 to 2.3.3 (update your composer to require 2.3.3)
6. Repeat steps 1-3 to place an order with a quote that has data in custom1, custom2, and custom3

### Expected result (*)

1. You SHOULD see custom1, custom2, and custom3 populated with data on the sales_order, matching the data in the columns from the quote

### Actual result (*)

1. custom1, custom2, and custom3 have no data populated. It's like the observer fires but does not copy the data between quote and order.
2. The order IS placed, the quote is de-activated & a fresh quote is created for the user... but no data is copied between the quote  / order that we place. 
3. We've confirmed by adding logging, the observer is still firing in 2.3.3, and not erroring out, it's simply no longer working...? :( 

### Notes for Magento team:
1. Our code has NOT changed between M2.3.1 and M2.3.3 upgrade
2. We have no other custom code using the sales_model_service_quote_submit_before event, just our code intended to copy the data from the quote to the sales_order
3. We're not seeing any errors that would hint at what is causing this issue

We plan to roll back to 2.3.1, or to try to get our staging environment into developer mode to see if an error is being swallowed we're missing, but we're strongly assuming the 2.3.3 upgrade broke this functionality; our code has not changed since the 2.3.3 upgrade, at least nothing that touches this extension, or nothing that would impact this extension we used a Magento devdocs to create?

Again: our code is the EXACT same code you'll find in the best-practices devdoc for doing this:
https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/copy-fieldsets.html

And the code worked on 2.3.1, but has ceased to work on 2.3.3, without any errors or explanation why.

2.3.3's release notes state that the return type of copyFieldset method changed, perhaps some other underlying functionality was changed that accidentally broke quote-to-order copying?

Any advice is helpful! We don't know why 2.3.3 would have broken this devdocs extension.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29799` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dyushkin** [comment]
Hi @not-art, below you can find an explanation from one of our developers:

> In the 2.3.1 version the value from the extension attribute was initially taken from the getDataUsingMethod (), so an extension attribute value existed because you set data in to quote table field, but in 2.3.3 the value was initially taken from the getAttributeValueFromExtensibleObject ().
To copy the data, you must initially using setExtensionAttributes($extensionAttributes) for quote. And for the save in the table sales_order it is necessary to implement a plugin, which would properly process the data from extensions attributes for saving. See https://devdocs.magento.com/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html

I'm close this issue, for now, feels free to reopen it if you have a more detailed description or additional questions. Thank you for your collaboration.

**Comment by not-art** [comment]
Hi @dyushkin, thanks for finding out the root cause with one of the developers. I would like to share my frustration that this was not very well-documented in the 2.3.3 patch notes, which state:

> You can now use copy service on extension attributes for classes that extend Data Object. Fix submitted by Oleksandr Kravchuk in pull request 23387. GitHub-23386

This fix was a backwards-incompatible / breaking change for anyone who extension attributes in the previous manner (as suggested by Magento), but it isn't documented that previous code using the old extension attributes implementation would break. As a note for the Magneto release team, better attention to breaking changes would be appreciated.

If what the developer says is true, then someone on the Magento team needs to update https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/copy-fieldsets.html as this tutorial is 100% incorrect now, given the 2.3.3 changes. It's going to cause developers to write Magento-provided code that will never work (such as with my team's code no longer working after out 2.3.3 upgrade).

Thanks again, and happy New Year,
-Art

**Comment by jkenneydaniel** [comment]
I'm very sad to see this issue closed without any real/legitimate explanation as to why a breaking change was introduced in 2.3.3 without any highlight whatsoever, that the devdocs are still incorrect (even for 2.4) and the answer here is basically "oh well" without a decent explanation of a path forward.

Very. Disappointing.

**Comment by TerreFra** [comment]
Hi @not-art.
We have the same problem on our Magento application, we have upgraded Magento from 2.3.1 to 2.3.5-p2 and now our copyFieldsetToTarget from quote to Order doesn't work anymore.

You find a solution about this problem? What we need to change in order to resolve the issue?
Thank you.
