### ISSUE TITLE
site and admin panel open only text form 

### ISSUE THREAD

**Issue by zenovix** [magento/magento2#2599]
i just install magento in my domain but after complete installation my website and my admin panel not open correctly only open in text form like html ,my website is technofia.com, can anyone suggest me what is the problem with me, i'm new with magento

**Comment by sylvainraye** [comment]
Hi @zenovix , 

Into a terminal, run the following command:

```
cd /path/to/magento2/src/
./bin/magento setup:static-content:deploy
```

It will deploy the static files (images, css, js, locale etc) for Magento 2. It takes some times. Be patient, you will see a progress.

**Comment by zenovix** [comment]
@diglin i have install magento into hostgator hosting, so can you please help me where i found 
cd /path/to/magento2/src/
./bin/magento setup:static-content:deploy and how i can run this command

**Comment by okorshenko** [comment]
@zenovix , please go to Magento root directory (where index.php file is located) and run `php ./bin/magento setup:static-content:deploy`
Please, let me know if this works for you

**Comment by rohitpenmetsha** [comment]
@diglin  @okorshenko : I am also trying to install mangento 2 on hostgator account and i ran the command _php bin/magento setup:static-content:deploy_ but no luck loading the css/js files even though the command executed successfully .

**Comment by vzabaznov** [comment]
Hi @zenovix , please try fresh version,  if you still have such problems please provide description according to the template, provide the used version, and create new bug.

**Comment by vzabaznov** [comment]
Hi, @zenovix thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
