### ISSUE TITLE
Description Content is trimming after some content

### ISSUE THREAD

**Issue by Charanjet** [magento/magento2#25990]
### Preconditions (*)

I am facing issue in the product content editor. When I am writing content in the Description but when save the product. Content is trimming and showing broken html.

### Steps to reproduce (*)
1. Open any product or category
2. Fill more then 66k symbols in description
3. Save changes

### Expected result (*)
Description saved, trimmed by 65532 symbols with message about it

### Actual result (*)
Description saved, trimmed by 65532 symbols without any messages, user can not notice the trimming

### Proposed solution

Description should not trim content or let the typist know if have any text limitation.

**Comment by engcom-Echo** [comment]
Hello @Charanjet 

Could you provide more details for reproduce this issue?
Please add steps to reproduce and version of magento.

**Comment by AnnaShepa** [comment]
Hi @Charanjet thank you for the report. I edited it a bit, please take a look and use https://github.com/magento/magento2/wiki/Issue-reporting-guidelines for your next issue reports.

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by AnnaShepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @AnnaShepa, here is your [Magento instance](https://i-25990-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25990-2-4-develop.instances.magento-community.engineering/admin](https://i-25990-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@AnnaShepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@AnnaShepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29885` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by korostii** [comment]
Uhm, 64k seems like a rather reasonable limit for product description. Could you pleas elaborate on the exact business case where one would require such an abundant amount of text filled into this single field? I mean, your case might be valid, but I am pretty sure this isn't a common problem. 

It doesn't seem meaningful to extend the text attribute type used here any further. On the other hand, your other suggestion to put up some kind of length validation for length-limited text fields ("let the typist know if have any text limitation" as you put it) does seem like pretty good idea generally, albeit not as critical for the description field particularly.

**Comment by magento-engcom-team** [comment]
Hi @Charanjet. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-29885` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
