### ISSUE TITLE
When category selected from top level navigation, attributes populated from module-catalog-search instead of module-catalog

### ISSUE THREAD

**Issue by kotamreddy** [magento/magento2#26002]
### Preconditions (*)

1. Magento ver 2.3.3
2. PHP  7.2.24-0
3. Ubuntu 18.04.1

### Steps to reproduce (*)

1. Install Magento 
2. Add a log entry in /var/www/html/magento23/vendor/magento/module-catalog-search/Model/Layer/Filter/Attribute.php near line 81 (first line in _getItemsData() method
3. In the default LUMA store select Men -> Tops -> Jackets

### Expected result (*)

1. I expect the code from /var/www/html/magento23/vendor/magento/module-catalog/Model/Layer/Filter/Attribute.php to execute to populate the left hand navigation

### Actual result (*)

1. The code from /var/www/html/magento23/vendor/magento/module-catalog-search/Model/Layer/Filter/Attribute.php is executed instead.  I expect a clear demarcation of catalog and catalog-search functionality. When you do a search module-catalog-search should be executed and when you select a category module-catalog should be executed.

**Comment by engcom-Echo** [comment]
Hello @kotamreddy 

Thank you for your report and collaboration!
Could you please create a Pull Request for this issue?

Thank you!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29733` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kotamreddy** [comment]
Any progress on this?

**Comment by kotamreddy** [comment]
Is this issue resolved in the latest version of Magento?  How to keep this issue active?  Is someone working on it?
