### ISSUE TITLE
Magento 2 CLI returns 3 errors

### ISSUE THREAD

**Issue by cristienache** [magento/magento2#26008]
This morning the website was broken, with no access to admin dashboard. php bin/magento list returns the following:

```
Available commands:
  help  Displays help for a command
  list  Lists commands

In ServiceManager.php line 1130:
                                                                                         
  An abstract factory could not create an instance of magentosetupconsolecommandconfigs  
  etcommand(alias: Magento\Setup\Console\Command\ConfigSetCommand).                      
                                                                                         

In ServiceManager.php line 941:
                                                                                         
  An exception was raised while creating "Magento\Setup\Console\Command\ConfigSetComman  
  d"; no instance returned                                                               
                                                                                         

In File.php line 150:
                                                                                         
  The contents from the "/var/www/html/magento2/vendor/magento/module-catalog/etc/modul  
  e.xml" file can't be read. Warning!file_get_contents(/var/www/html/magento2/vendor/ma  
  gento/module-catalog/etc/module.xml): failed to open stream: No such file or director  
  y 
```
Magento 2.3.0 running on Lightsail.

Steps to reproduce:
Magento 2.3.0 installation on a 1 year old website.

Expected and actual results:
I have removed the cache folders contents, and tried other commands like composer install, setup:upgrade.
The error still appear.

Any help would be highly appreciated!

**Comment by engcom-Echo** [comment]
Hello @cristienache 

Could you provide more details for reproduce this issue?
Please add steps to reproduce.

**Comment by cristienache** [comment]
> Hello @cristienache
> 
> Could you provide more details for reproduce this issue?
> Please add steps to reproduce.

The error appeared on our live website. So basically it was a 1 year old Magento 2.3 website fully functional with a catalogue of 100+ products.

**Comment by engcom-Echo** [comment]
Hello @cristienache 

Try to check if module.xml is present on the file system.
Please also check your r/w permission.
`/var/www/html/magento2/vendor/magento/module-catalog/etc/module.xml`

**Comment by cristienache** [comment]
> Hello @cristienache
> 
> Try to check if module.xml is present on the file system.
> Please also check your r/w permission.
> `/var/www/html/magento2/vendor/magento/module-catalog/etc/module.xml`

Hi @engcom-Echo many thanks for your reply! The file is present in the system and the permissions are as follows: -rw-r--r--+

Kind regards,
Cristi Enache

***********UPDATE***********
After trying again "php/bin magento" command this morning, all the CLI commands were listed. Ran static content deploy and the website works again.

Thank you @engcom-Echo for your help!
