### ISSUE TITLE
CMS Pages Main Screen Errors. No pages listed

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#2600]
Using Stable Magento 2.0.0 Release installed via Composer.

Running latest PHP Version 5.6.15, Apache/2.4.10 OpenSSL/1.0.2d with MPM-Event. Opcache, Redis Cache, MariaDB 10.1.4 binary distribution.

Please see the Screenshot and the exception message output of the file that we have error loading in the CMS Pages List screen.

![image 5](https://cloud.githubusercontent.com/assets/8983883/11572586/a6611158-99c7-11e5-9e47-35e65307763a.png)

URL: https://zzzz.zzz/adasdada/mui/index/render/?namespace=cms_page_listing&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&paging%5BpageSize%5D=20&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=actions&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&isAjax=true

-------------------

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''))' at line 1, query was: SELECT COUNT(*) FROM `ddl2_cms_page` AS `main_table` WHERE (MATCH(title,meta_keywords,meta_description,identifier,content) AGAINST('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''))
#0 /var/www/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /var/www/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /var/www/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query(Object(Magento\Framework\DB\Select), Array)
#6 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(828): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /var/www/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(217): Zend_Db_Adapter_Abstract->fetchOne(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/magento2/vendor/magento/module-cms/Model/ResourceModel/Page/Grid/Collection.php(128): Magento\Framework\Data\Collection\AbstractDb->getSize()
#9 /var/www/magento2/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php(247): Magento\Cms\Model\ResourceModel\Page\Grid\Collection->getTotalCount()
#10 /var/www/magento2/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php(281): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->searchResultToOutput(Object(Magento\Cms\Model\ResourceModel\Page\Grid\Collection))
#11 /var/www/magento2/vendor/magento/module-ui/Component/Listing.php(37): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->getData()
#12 /var/www/magento2/vendor/magento/framework/View/Element/UiComponent/Context.php(234): Magento\Ui\Component\Listing->getDataSourceData()
#13 /var/www/magento2/vendor/magento/framework/View/Element/UiComponent/ContentType/Json.php(69): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData(Object(Magento\Ui\Component\Listing))
#14 /var/www/magento2/vendor/magento/module-ui/Component/AbstractComponent.php(118): Magento\Framework\View\Element\UiComponent\ContentType\Json->render(Object(Magento\Ui\Component\Listing), 'templates/listi...')
#15 /var/www/magento2/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(27): Magento\Ui\Component\AbstractComponent->render()
#16 /var/www/magento2/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(24): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#17 /var/www/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#18 /var/www/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#19 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#21 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('dispatch', Array)
#22 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminAuthentica...')
#23 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#24 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#26 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'designLoader')
#27 /var/www/magento2/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#30 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminMassaction...')
#31 /var/www/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#34 /var/www/magento2/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(52): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /var/www/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#38 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#40 /var/www/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /var/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#43 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#44 /var/www/magento2/vendor/magento/module-store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#47 /var/www/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#48 /var/www/magento2/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#49 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#50 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#51 {main}

**Comment by vzabaznov** [comment]
Hi @devdesco-ceo , please try out fresh version, if you still have such problems please provide description according to the template, provide the used version, and create new bug.

**Comment by vzabaznov** [comment]
Hi, @devdesco-ceo thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
