### ISSUE TITLE
Quote totals calculation looping

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#26018]
### Preconditions (*)

**1.** Create a `TestCoupon` on the back-end side

<img width="886" alt="26018" src="https://user-images.githubusercontent.com/13585327/70733684-769ff500-1d13-11ea-85de-c9f097906e00.png">

### Steps to reproduce (*)

**1.** Login as registered Magento customer on the front-end side
**2.** Add any product into shopping cart (in further = `Product A`)
**3.** Go to Shopping Cart and redeem a `TestCoupon`
**4.** Go to back-end and disable `Product A`
**5.** Refresh Shopping Cart page on the front-end side

### Expected result (*)

1. Disabled `Product A` should be removed from the customer's shopping cart. 
2. Customer should not see a blank screen in the described test case.

### Actual result (*)

1. Quote totals calculation goes to loop and as a result customer gets a blank screen.

### Root of issue
[MC-5844: Coupon Requests Limiter](https://github.com/magento/magento2/commit/58a82c592fa5d1c8b9a53a4e38279840d043a630#diff-0b9d72b83f54650b7125ed84f7865785)

`Magento\SalesRule\Observer\CouponCodeValidation` triggers `$this->cartRepository->getList` method which initiate total calculation for the loaded quote.

### Affected Magento versions
- 2.3.3 
- 2.3.2 
- 2.3.2-p2

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26018-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26018-2-4-develop.instances.magento-community.engineering/admin](https://i-26018-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @atwixfirster.
I'm not able to reproduce the issue as provided steps by you.
Please review below screencast for same
https://www.screencast.com/t/kN6U6QQBr
Kindly provide more information to reproduce this issue.
Thanks

**Comment by atwixfirster** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @atwixfirster. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @atwixfirster, here is your [Magento instance](https://i-26018-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26018-2-4-develop.instances.magento-community.engineering/admin](https://i-26018-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by atwixfirster** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @atwixfirster. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by atwixfirster** [comment]
>  I'm not able to reproduce the issue as provided steps by you.

@krishprakash thank you for the verification. Now, I am also unable to reproduce this issue in current **2.3-develop** and **2.4-develop** branches.

However, I was able to reproduce this bug in clear Magento Commerce **v2.3.2**.

Let's close this issue since it's not actual.
