### ISSUE TITLE
Bug: The backend «Image Detail» screen unnecessary stretches the small product images (shows it bigger than 100% of its size)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2601]
![](https://mage2.pro/uploads/default/original/1X/d90438fc28efeba48e472eb830704cb1cbf53dee.png)

**Comment by wonderfan** [comment]
Do you run `magento cache:clean` to clean the cache and see it again?

**Comment by MomotenkoNatalia** [comment]
@dfediuk Thanks for reporting this issue. Internal ticket: MAGETWO-47228

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-47228 is closed and delivered to mainline. Please let us know if you still have an issue.
