### ISSUE TITLE
Magento 2.3.3. Customer Reorder throws 500 error

### ISSUE THREAD

**Issue by alex-james** [magento/magento2#26010]
### Preconditions (*)

1. 2.3.3
2.

### Steps to reproduce (*)

1. Create an order containing at least one simple product with no product options
2. Browse to the My Account area in the frontend, locate the order and click the "Reorder" button

### Expected result (*)

1. Magento should add the items from the order to the basket and redirect you to the basket page
2.

### Actual result (*)

1. Magento throws the following HTTP 500 error "Uncaught TypeError: Argument 1 passed to Magento\\Framework\\DataObject::__construct() must be of the type array, null given"
2. This is because the Magento\Checkout\Model\Cart::addOrderItem() calls gets a null back from getProductOptionByCode() for an order item with no options which it then passes to the constructor for \Magento\Framework\DataObject which is expecting an array.

**Comment by krishprakash** [comment]
Hi @alex-james. Thank you for your report.
Not able to reproduce the issue in latest magento instance.
