### ISSUE TITLE
qty advanced inventory not reflect change in admin when add new product

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#26025]
### Preconditions (*)

1. CE 2.2.8
2.

### Steps to reproduce (*)

1. Add new product
2. Instead add qty > Go to advanced inventory
In new advanced inventory modal
Manager Stock : Yes
Qty: Add qty
Click Done

### Expected result (*)

1. [Screenshots, logs or description]
2. After modal advanced inventory done update  qty field outside in product form must update value

### Actual result (*)

1. [Screenshots, logs or description]
2. No update

**Comment by mrtuvn** [comment]
@magento give me 2.2 instance

**Comment by mrtuvn** [comment]
@magento can you deploy for me exactly 2.2.8 version

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26025-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26025-2-4-develop.instances.magento-community.engineering/admin](https://i-26025-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @mrtuvn,
I have verified your issue in the latest Magento 2.4 instance. It is working fine on our end.
The product is saved with the Advance Inventory.
If you face issues on your end please add a video or screenshot.

Thanks.

**Comment by mrtuvn** [comment]
@ajijshekh123 2.3.x will work fine. I dont get this behavior in higher version
But my problem happen in 2.2.8 (I'm not sure this problem fixed in 2.2.9 or not)
Can you provide link the fix/PR for such case related ?

**Comment by ajijshekh123** [comment]
@mrtuvn - I don't have a link but if you are migrating your Magento version. It will automatically be fixed your issue.

**Comment by ajijshekh123** [comment]
@mrtuvn - I don't have a link but if you are migrating your Magento version. It will automatically be fixed your issue.

**Comment by mrtuvn** [comment]
Solved my problem

**Comment by ajijshekh123** [comment]
Okay @mrtuvn
