### ISSUE TITLE
Magento 2.3.3 Recently viewed widget in category page sidebar, product image issue when currency is switched

### ISSUE THREAD

**Issue by Aravindh468** [magento/magento2#26039]
Hi guys,

 **Preconditions (*)**
1. Magento ver 2.3.3
2. PHP 7.2+

**Steps to reproduce (*)**

1. In single website, with one store view setup a Multiple currency with Minimum 3 currencies.

2. Create a recently viewed widget using following configuration,
**Content->widgets->Add widget**
Select Type as Recently viewed Product  and Design theme as Magento Blank and click continue
Click Add Layout and select display on -> Specified Page
Page -> Catalog Category
Container -> Sidebar Main
Then in left sidebar, click widget options select all the product attributes to show and all the buttons to show and finally save the widget.

3. In frontend, View few products such that it will be visible on recently viewed sidebar.

**Expected result (*)**

1. When currency is switched it should hold/display the same products in recently viewed widget without any misbehaviour/changes.

**Actual result (*)**

1. It is correctly showing all the selected product option for the widget without any misalignment/break.
2. But when I switch the currency only the last recently viewed products is displaying properly and for all other items the product image get break.
3. I get following error in my system.log

> [2019-12-14 07:20:22] main.ERROR: Unable to resolve the source file for 'frontend/_view/en_US/Magento_Catalog/images/product/placeholder/.jpg' [] []

**Comment by Aravindh468** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Aravindh468. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26039-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26039-2-4-develop.instances.magento-community.engineering/admin](https://i-26039-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @Aravindh468 , thank you for reporting this issue
I checked the issue at 2.4-develop instance .. not able to reproduce this issue at develop instance.
please update the description if it requires any additional steps to reproduce this issue . also If you still able to reproduce this then also share screenshots

**Comment by Aravindh468** [comment]
@shikhamis11 I have reproduced this issue in magento 2.3.3. But i couldn't reproduce in Magento 2.3.4 instance provided by you. Is this issue fixed in 2.3.4?

**Comment by shikhamis11** [comment]
hi @Aravindh468 , It seems it is fixed in 2.4-dev instance

**Comment by Aravindh468** [comment]
@shikhamis11 Thank you.. I have checked the code changes related to the file and it seems to be updated in Magneto 2.3.4 instance..

**Comment by trebb0r** [comment]
Hello @Aravindh468, I experience this exact same issue! Can you tell me what the code changes are in which file(s) compared from 2.3.3 to 2.3.4 that fixed this issue?

**Comment by Aravindh468** [comment]
@trebb0r there is a slight modification in 

> Magento\Catalog\Ui\DataProvider\Product\Listing\Collector\Image

**$this->design->setDesignTheme($currentTheme);** 

Above line should be moved before foreach in Collect method.

**Comment by VivekM296** [comment]
Moving this line above foreach not working for me. Is the only fix ??
