### ISSUE TITLE
Salable quantity does not decrement when using OrderCreate API

### ISSUE THREAD

**Issue by StratumWeb** [magento/magento2#26038]
When calling the OrderCreate API to add an order into Magento2, the Salable quantity does not get decremented. This is the API call we are using:

- https://devdocs.magento.com/redoc/2.3/admin-rest-api.html#tag/orderscreate

Is Salable inventory just not implemented via this API call? I am assuming that Magento2 would auto handle all inventory deductions based on the settings for the site. So if decrement Salable quantity is set globally, it should do it with this API call, correct?

**Comment by shikhamis11** [comment]
hi @StratumWeb , Please correct the format of issue reporting . you can take help from [here](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
apart from it .. did you check the quantity decrement issue just after order place ? or after order is completed ?

**Comment by engcom-Delta** [comment]
@StratumWeb , thank you for your report. Salable quantities is MSI functionality
Please, refer to **Magento Inventory Project (a.k.a MSI)** [repo](https://github.com/magento/inventory)  for further investigation
