### ISSUE TITLE
Can't install sample data

### ISSUE THREAD

**Issue by vvitkouski** [magento/magento2#2604]
I'm getting this when trying to install sample data in latest magento 2 develop:

[ErrorException]  
  Argument 1 passed to Symfony\Component\Console\Input\ArrayInput::__construct() must be of the type array, object given, called in /home/deploy/apps/lgk-solutions.com/current/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined

**Comment by wonderfan** [comment]
which way do you use?  command way or composer way?

**Comment by wonderfan** [comment]
The correct command line is `magento sampledata:deploy`

**Comment by vvitkouski** [comment]
I use magento sampledata:deploy
Looks like issue with arguments passing from \Magento\SampleData\Console\Command\SampleDataDeployCommand to \Magento\Framework\ObjectManager\Factory\Compiled::createObject

**Comment by mdevicariis** [comment]
Confirmed: I get the same error when trying to deploy sample data with the php ./bin/magento sampledata:deploy command

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Input\ArrayInput::__construct() must be of the type array, object given, called in /opt/cart01/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined in /opt/cart01/vendor/symfony/console/Symfony/Component/Console/Input/ArrayInput.php:37

**Comment by tonegolf71** [comment]
Further information that might be helpful... I had this same issue, I was running in production mode and had generated all the di code using `magento setup:di:compile`.

When I switched back to developer mode and cleared out `/var/generation` and `/var/di` I could then succesfully install the sample data using `magento sampledata:deploy`.

**Comment by toonvd** [comment]
I managed to fix my issue with @tonegolf71 his comment.

**Comment by angelorgoc** [comment]
hi @tonegolf71, I followed your instructions and the command works. thanks

**Comment by ghost** [comment]
Thanks for pointing this out. I added some [troubleshooting](http://devdocs.magento.com/guides/v2.1/install-gde/trouble/tshoot_sample-data.html#trouble-samp-prod) for this.
