### ISSUE TITLE
Notification Js file case sensitive reference error

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [magento/magento2#26047]
### Preconditions (*)
1. Setup default 2.3.3 Magento Commerce in an Ubuntu environment
2. Deploy frontend/backend theme

### Steps to reproduce (*)
1. Login/Open into magento admin
2. Try click any menus or go to system config directly via URL and try expand system config tabs

### Expected result (*)
1. Menu should be functional/clickable

### Actual result (*)
1. Getting this error in console and this causing javascript errors
![Admin Not loading](https://user-images.githubusercontent.com/54947876/70852142-ecb76f80-1e6b-11ea-8bf4-0a3a34d36457.png)

2. Could not go into inner pages since menu not opening and even from system config not able to save or update anything

### Possible Problem

Noticed Case sensitive reference of `'mage/backend/Notification'` in `lib/web/mage/backend/bootstrap.js` but the actual file name is `lib/web/mage/backend/notification.js` and when I change the reference of the file it loads ok. 

This seems to be with only Magento commerce code issue, Open source version shows different one https://github.com/elamurugan/magento2/blob/2.3.3/lib/web/mage/backend/bootstrap.js or may be this got fixed already. 

In my local I see 

![Screen Shot 2019-12-14 at 12 36 09 PM](https://user-images.githubusercontent.com/54947876/70852341-50429c80-1e6e-11ea-875b-79bd6d1cbc41.png)

**Comment by engcom-Golf** [comment]
Hi @Elamurugan-Nallathambi thank you for you report, this issue has already fixed in 2.4-develop and available on 2.3.4 release
