### ISSUE TITLE
If import external image url using csv showing Warning: Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s):

### ISSUE THREAD

**Issue by navneetkumar-pim-webkul** [magento/magento2#26040]
### Preconditions (*)
1. Magento 2.3.3
2. PHP 7.2.24

### Steps to reproduce (*)
1. Create Product CSV with the public Images URL.
2. Login Magento Admin => System => Import feature => Upload
2.  Showing Warning: Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 

### Expected result (*)
1. will import the CSV successfully with the public image URL like 
https://pixabay.com/photos/gent-mirroring-water-basin-belgium-4661419

### Actual result (*)

1. Warning: Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 
![image](https://user-images.githubusercontent.com/26001046/70847667-d077fa80-1e8c-11ea-8189-80cf50b54a78.png)

**Comment by navneetkumar-pim-webkul** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @navneetbhardwaj. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @navneetbhardwaj, here is your [Magento instance](https://i-26040-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26040-2-4-develop.instances.magento-community.engineering/admin](https://i-26040-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by navneetkumar-pim-webkul** [comment]
@magento give me 2.3.3

**Comment by navneetkumar-pim-webkul** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @navneetbhardwaj. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @navneetbhardwaj, here is your [Magento instance](https://i-26040-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26040-2-3-3.instances.magento-community.engineering/admin](https://i-26040-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by navneetkumar-pim-webkul** [comment]
@navneetbhardwaj do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
Yes
over Magento 2.3.3 issue is persist

**Comment by navneetkumar-pim-webkul** [comment]
But Not found 2.4-develop

**Comment by navneetkumar-pim-webkul** [comment]
@magento Yes, I confirmed that I was able to reproduce the issue on vanilla Magento instance version 2.3.3

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26040-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26040-2-4-develop.instances.magento-community.engineering/admin](https://i-26040-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @navneetbhardwaj 
thank you for reporting this issue .. it seems this issue is already fixed in 2.4-develop branch.

**Comment by CsSatter** [comment]
Hi @shikhamis11,
Could you link us the commit message related to the fix?
Thank you!

**Comment by flytomek** [comment]
I had the same issue one year ago on Magento 2.3.0, which has been patched. Now on Magento 2.3.3 it happens the same. I also checked 2.4-develop and loos like it's patched again.

Anyone has a hotfix of this issue for 2.3.3?

**Comment by tushhan** [comment]
I have exaxtly the same problem with Magento 2.3.3 and PHP 7.2.24
Tried many possible ways but no luck so far. Can anyone address how to resolve this issue?

**Comment by CsSatter** [comment]
Hi @tushhan & @flytomek,
I believe this is the file in question: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php

I'll be able to confirm at a later date wether this solves the issue. If anyone else wants to confirm the changes to fix the issue for 2.3.X feel free :)

**Comment by CsSatter** [comment]
> Hi @tushhan & @flytomek,
> I believe this is the file in question: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogImportExport/Model/Import/Uploader.php
> 
> I'll be able to confirm at a later date wether this solves the issue. If anyone else wants to confirm the changes to fix the issue for 2.3.X feel free :)

Just received word that changing this file alone will not solve the issue. Seems to be an open-source only issue for 2.3.X.

**Comment by flytomek** [comment]
Workaround can be:
- download all the images to _<img_folder>_ i.e. via external script
- upload images via FTP to _<magento_folder>/var/import/images/<img_folder>_
- generate CSV, but instead of URL to image, put image filename
- import csv (remember to set _Images File Directory_ to _/<img_folder>_)

**Comment by engcom-Delta** [comment]
Hi @navneetbhardwaj thank you for your report.  I am not able to reproduce issue by steps you described on clean 2.4-develop
Csv file is imported succesfully: [importImageUrl.csv.txt](https://github.com/magento/magento2/files/4090742/importImageUrl.csv.txt)

If you'd like to update the issue, please reopen it.
