### ISSUE TITLE
Path "/var/www/html/var" cannot be used with directory "/var/www/html/var"

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26052]
I figured out it was a permission issue after a bunch of Googling, but I mean come on. This stuff should be fixed.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Install Magento 2.3.3
2. Have permission problems
3. Do something

### Expected result (*)

Useful error message about what directory is not writeable.

### Actual result (*)

Useless error message.
The problem is here:

```
$ grep "cannot be used with directory" -R *
vendor/magento/framework/Filesystem/Directory/PathValidator.php:                    'Path "%1" cannot be used with directory "%2"',
```

**Comment by engcom-Echo** [comment]
Hello @Zyles 

Please check your r/w permission.

**Comment by Zyles** [comment]
> Hello @Zyles
> 
> Please check your r/w permission.

I think you missed the point of this issue.

**Comment by engcom-Echo** [comment]
Hello @Zyles 

Could you provide more details for reproduce this issue?
Please add a screenshot with an error.

Thank you!

**Comment by Zyles** [comment]
I forgot exactly which directory it was. It is a permission error and I already fixed it.

The problem is here:

```
$ grep "cannot be used with directory" -R *
vendor/magento/framework/Filesystem/Directory/PathValidator.php:                    'Path "%1" cannot be used with directory "%2"',
```

Please update the message to something meaningful.

Maybe:

'Can't write to directory "%1". Please check web server permissions.'

Or similar.

**Comment by engcom-Echo** [comment]
Hello @Zyles 

According [this](https://github.com/magento/magento2/issues/26052#issuecomment-567160072)  comment I close this issue as it was connected with environment configuration.

**Comment by Zyles** [comment]
Really? Do you find this error message to give adequate feedback to a developer on what the problem is?

No wonder Magento is pure nightmare to work with when you leave stupid issues like this in core all over the place.

I recommend reading this: https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29939` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by medigeek** [comment]
What's the status on this issue?

**Comment by magento-engcom-team** [comment]
Hi @Zyles. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-29939` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by torhoehn** [comment]
@magento-engcom-team What was fixed in `MC-29939`?

**Comment by timxsarus** [comment]
I don't have the opportunity to upgrade to  2.4.3, could you give me the link to the commit that fixed it? So maybe I can create my own patch until then.

**Comment by sdouma** [comment]
@magento-engcom-team Can we get a PR reference for this ticket?
