### ISSUE TITLE
Is there a way to view the internal issue tracker?

### ISSUE THREAD

**Issue by pantaoran** [magento/magento2#2605]
I'm trying to run Selenium tests and selected a simple test to start out: RegisterCustomerFrontendEntityTest

There is a variation of this test which references `ticketId="MAGETWO-12394"` and which fails. I don't understand why it fails.
Is there any way for me to find the status of the referenced issue 12394? Was this fixed already? Or is the test expected to fail for now?

I see you guys often including such internal issue references in your answers here. Are those of any use to me whatsoever or are they purely for the development team?

**Comment by wonderfan** [comment]
@pantaoran Selenium is used for automation test with browser driver. Can you paste your source code of RegisterCustomerFrontendEntityTest?

**Comment by pantaoran** [comment]
I did not modify that file, it's exactly in the same state as when you install the official MTF tests using the Magento 2.0.0 release. 
I want to know if this test is expected to fail or if my Selenium setup has some problem.

**Comment by mazhalai** [comment]
Issues are purely for the dev team. In this case, the ticket is a test case and is passing on our end. Can you please be more specific about what error you get when it fails?

**Comment by wonderfan** [comment]
```
public function test(Customer $customer)
{
    // Steps
    $this->cmsIndex->open();
    $this->cmsIndex->getLinksBlock()->openLink('Create an Account');
    $this->customerAccountCreate->getRegisterForm()->registerCustomer($customer);
}
```

**Comment by wonderfan** [comment]
It is your Selenium setup problem.

**Comment by davidalger** [comment]
Closing due to lack of response.
