### ISSUE TITLE
Incorrect Error Message While Sharing Wish list more than Specified Email Address Value in Admin Configuration

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#26064]
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Go to frontend and login as Cutomer.
2. Add any product to wish list.
3. Go to My account dashboard -> My Wish list
4. Enter arround 20 to 30 email addresses and share wish list.
5. The Error Message is Showed incorrect.

### Expected result (*)

1. Error Message Should be Similar to error shown in the below image
2.
 ![wishlist-expected](https://user-images.githubusercontent.com/54176640/70916457-b92e3e00-2041-11ea-8b62-64844f2806ff.png)

### Actual result (*)

1. Error Message Showing as follows
2. 
![wishlist-mess](https://user-images.githubusercontent.com/54176640/70916448-b3d0f380-2041-11ea-905b-9ee0c30df353.png)

**Comment by kanthy-magento** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-26064-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26064-2-4-develop.instances.magento-community.engineering/admin](https://i-26064-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
![wishlist](https://user-images.githubusercontent.com/56586384/70918018-630eca00-2044-11ea-907c-ae795128b99a.PNG)
Able to replicate in CE:2.4 instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29801` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by eduard13** [comment]
Fixed in scope of #26066.
Closing as not actual anymore.
