### ISSUE TITLE
Web Setup Wizard - 401 un authorized access -

### ISSUE THREAD

**Issue by Rijisha** [magento/magento2#26074]
### Preconditions (*)

1. Magento 2.3.2
2. php 7.2

### Steps to reproduce (*)

1. System->tool->Web Setup Wizard 
2. https://domainname/setup/index.php/session/unlogin
3. Already set Store->General ->Web ->Base URLs (Secure) ->
Use Secure URLs on Storefront	- Yes
Use Secure URLs in Admin - Yes	
Enable HTTP Strict Transport Security (HSTS)	- Yes
Upgrade Insecure Requests- Yes
![image](https://user-images.githubusercontent.com/19388118/70967280-4b206000-20af-11ea-8846-cd5a6a59dabb.png)

### Expected result (*)

1.Login screen of marketplace

### Actual result (*)

1.
![image](https://user-images.githubusercontent.com/19388118/70967240-32b04580-20af-11ea-88ac-3aad2c11bf8e.png)

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26074-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26074-2-4-develop.instances.magento-community.engineering/admin](https://i-26074-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @Rijisha 
Thank you for reporting this. I am not able to reproduce this issue . It seems it's not reproducible at magento 2.4-develop instance.
