### ISSUE TITLE
Recaptcha on newsletter creates error

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#26078]
### Preconditions (*)

1. Magento 2.3.3
2.

### Steps to reproduce (*)

1. Enable Google recaptcha on the frontend from Configuiration -> Security -> Google reCaptcha and make sure the newsletter option is enabled
2. 

### Expected result (*)

1. reCaptcha enabled with no errors
2.

### Actual result (*)

1. Chrome console reports a nodename undefined error
![error](https://user-images.githubusercontent.com/43850303/70987963-d6522380-20b8-11ea-9854-26d2d0872e14.png)
 
2.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26078-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26078-2-4-develop.instances.magento-community.engineering/admin](https://i-26078-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devchris79** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @devchris79. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @devchris79, here is your [Magento instance](https://i-26078-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26078-2-4-develop.instances.magento-community.engineering/admin](https://i-26078-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devchris79** [comment]
@engcom-Charlie Can you please verify this one, the develop instances don't allow a security configuration, but you verified the other bug with ReCaptcha #25735.

**Comment by engcom-Charlie** [comment]
Hello @devchris79 
I can't do it, because @shikhamis11 is testing your issue now.

**Comment by shikhamis11** [comment]
Hi @devchris79, I checked the issue on my local but it seems captcha keys not working on local .. I will check it on server and update the status of the issue soon

**Comment by devchris79** [comment]
@shikhamis11 Thanks for the update.

**Comment by shikhamis11** [comment]
hello @devchris79 
I checked the issue on chrome browser for both on magento version 
Magento ver. 2.3.3 for both reCaptchaV2 and invisible Recaptcha 
but getting error on console. 
let me know if it requires any additional step to reproduce this issue ?

**Comment by devchris79** [comment]
I assume you mean you don't get an error in the console? That's strange, I have found a second person that describes the same issue, they are working in Luma and an unadulterated core:
[https://magento.stackexchange.com/questions/286724/magento-2-recaptcha-uncaught-typeerror-cannot-read-property-nodename-of-undef](url) 

Here is our settings, the backend captcha is turned off and the frontend is running invisible type:
![image](https://user-images.githubusercontent.com/43850303/71163390-e8f96380-2244-11ea-8b58-7ecca6d2ef85.png)

**Comment by shikhamis11** [comment]
Hi @devchris79 , can you Please let me know the version of Chrome on which you are facing this issue ? 
@engcom-Charlie can you please also look into this issue ?

**Comment by engcom-Charlie** [comment]
@shikhamis11 yes, of course

**Comment by engcom-Charlie** [comment]
Hello @devchris79 
I can't reproduce this issue on the Magento 2.3.3

**Testing scenario:**
1. Enable Google recaptcha on the frontend from Configuiration -> Security -> Google reCaptcha and make sure the newsletter option is enabled
![image](https://user-images.githubusercontent.com/51680850/71247647-cf7a1980-2321-11ea-9b4e-f1b6e97eac09.png)
2. Go to the frontend and check console for errors


**Result:**
ReCaptcha works without any errors in console:
![image](https://user-images.githubusercontent.com/51680850/71247526-9f327b00-2321-11ea-802f-675e3a8fb8bd.png)

@shikhamis11 so i think this issue can be closed as not reproducible.
@devchris79 Thank you for contribution and collaboration!

**Comment by devchris79** [comment]
Closing issue as @shikhamis11 and @engcom-Charlie can't replicate. Thanks for investigating.
