### ISSUE TITLE
Checkout not working if order email copy contains multiple emails and copy method is Separate Email

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#26079]
### Preconditions (*)

1. Magento version 2.3.3
2. Setting Store > Configuration > Sales > Sales Emails > General Settings > Asynchronous sending set to "**Disable**"
3. Setting Store > Configuration > Sales > Sales Emails > Order > Send Order Email Copy To contains **multiple emails** like "john@yopmail.com,max@yopmail.com"
4. Setting Store > Configuration > Sales > Sales Emails > Order > Send Order Email Copy Method is set to "**Separate Email**"
![email-copy-settings](https://user-images.githubusercontent.com/5336201/70997992-36b68480-20fc-11ea-9f2a-33cffdd57b69.png)

### Steps to reproduce (*)

1. Add any product to cart in the storefront
2. Go to checkout and hit "Place Order" button

### Expected result (*)

1. Order should be created and success page should be shown

### Actual result (*)

1. Order is created in the system 
2. But customer see an error on checkout and have the option to click place order button again
3. If you see network tab in browser console then request to URL "/rest/default/V1/carts/mine/payment-information" throws error

Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template\Interceptor::setVars() must be of the type array, null given

<img width="1366" alt="Screenshot 2019-12-17 at 6 38 10 PM" src="https://user-images.githubusercontent.com/5336201/70998083-78472f80-20fc-11ea-811a-0587425da09b.png">

**Comment by krishprakash** [comment]
Hi @rav-redchamps. Thank you for your report.
I'm not able to reproduce the issue on latest magento instance as provided steps by you.
Kindly provide more information
Please review the below screencast and let me know if I'm missing any step.
https://www.screencast.com/t/HEaEzhSa
Thanks

**Comment by rav-redchamps** [comment]
I just checked and this is fixed in 2.4 develop branch in this commit https://github.com/magento/magento2/commit/dbf2c29bef8ec4a768156bd7ace0c99647bec631

and this was the pull request https://github.com/magento/magento2/pull/24855

So, it should be part of 2.3.4 and 2.4.0

Closing the issue as of now.
