### ISSUE TITLE
Page Should be scrolled towards the message area after product is added to cart.

### ISSUE THREAD

**Issue by sudheer-gajjala** [magento/magento2#26086]
### Preconditions (*)

1. Magento Version 2.4

### Steps to reproduce (*)

1. Go Product Listing Page and add product to cart from there.
2. After the ajax action customer does not know whether the product is added cart or not. Since the "success/error/notice" is rendered on the top of page.
3. He needs to scroll to the top and see the response of ajax action.

### Expected result (*)

1. Page should be scrolled Automatically towards message part after the add to cart button is clicked

### Actual result (*)

1. The Page is not Scrolled automatically.

**Comment by krishprakash** [comment]
Hi @sudheer-gajjala.
This is not an issue.
This is default magento behavior since magento 2.2.

**Comment by sudheer-gajjala** [comment]
@krishprakash Yes, but the user cannot understand what happened after he click on add to cart. So, in order to acknowledge him we can add some patch to scroll towards the message.

**Comment by krishprakash** [comment]
@sudheer-gajjala you can add this at [feature request repository](https://github.com/magento/community-features/issues)
**Here another use case:** If user want to add to cart 2-3 products from same product row or after next row then every time user need to scroll down to that product row and add product to cart

**Comment by sudheer-gajjala** [comment]
@krishprakash thanks for the update, I will try to put this in feature request and wait for the approval.
