### ISSUE TITLE
Internal error while adding the shipment details for an order

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2608]
i am trying to add shipment information for an order but i am getting internal error

 URL(POST): http://MYHOST/rest/default/V1/shipment/
payload:

```
{
```

  "entity": {
    "billingAddressId": 24,
    "customerId": 8,
    "emailSent": 0,
    "orderId": 12,
    "packages": [
      {
        "extensionAttributes": {}
      }
    ],
    "shippingAddressId": 23,
    "storeId": 1,
    "items": [
      {
        "orderItemId": 20,
        "qty": 1,
        "extensionAttributes": {}
      }
    ],
    "extensionAttributes": {}
  }
}

response:
   {
    "messages": {
        "error": [
            {
                "code": 500,
                "message": "Server internal error. See details in report api/266657385283"
            }
        ]
    }
}

api/266657385283:

s:200:"Fatal Error: 'Cannot instantiate interface Magento\Sales\Api\Data\ShipmentPackageInterface' in '/var/www/html/MYPROJECT/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php' on line 73";

**Comment by olysenko** [comment]
Internal story was created MAGETWO-54630

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Internal-error-while-adding-the-shipment-details-for-an-order/idi-p/46459).

**Comment by paalsoberg** [comment]
Why was this closed? Surely it is a bug - what's the progress of ticket MAGETWO-54630?
