### ISSUE TITLE
Customer Sharing Options not respected in REST API

### ISSUE THREAD

**Issue by cebesoft** [magento/magento2#26089]
### Preconditions (*)
1. PHP 7.3.12
2. Magento 2.4-develop

### Steps to reproduce (*)
1. Create multiple websites and store views. For example website1 with storeview1 and website2 with storeview2;
![Screenshot from 2020-06-15 15-33-37](https://user-images.githubusercontent.com/51679138/84657874-a081e080-af1d-11ea-8739-7508a247800d.png)

2. Go to Admin->Stores->Configuration->Customers->Customer Configuration->Account Sharing Options and set **Share Customer Accounts** to '**Per Website**';
3. Create a user account in website1;
4. Use REST API to login with user and password to retrieve the bearer token
![Screenshot from 2020-06-15 15-37-20](https://user-images.githubusercontent.com/51679138/84658173-26059080-af1e-11ea-92d0-a919cb1ef41a.png)

5. Read user details with **GET** `/rest/storeview1/V1/customers/me`
6. Read user details with **GET** `/rest/storeview2/V1/customers/me`

### Expected result (*)
1. /rest/storeview1/V1/customers/me should return user information
2. /rest/storeview2/V1/customers/me should return an error (e.g. unauthorized)

### Actual result (*)
1. /rest/storeview1/V1/customers/me returns user information
2. /rest/storeview2/V1/customers/me returns user information

**Comment by cebesoft** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @cebesoft. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cebesoft, here is your [Magento instance](https://i-26089-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26089-2-4-develop.instances.magento-community.engineering/admin](https://i-26089-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cebesoft** [comment]
This problem can be reproduced in the upcoming 2.4.x release.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26089-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26089-2-4-develop.instances.magento-community.engineering/admin](https://i-26089-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26089-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26089-2-4-develop.instances.magento-community.engineering/admin](https://i-26089-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29924` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @cebesoft. Thank you for your report. 
The issue has been fixed in magento/magento2#28213 by @p-bystritsky in 2.4-develop branch
Related commit(s):
 - [ddee80419bf117ba64a73ae5a1e4e872e9cbe925](https://github.com/magento/magento2/commit/ddee80419bf117ba64a73ae5a1e4e872e9cbe925)
 - [c17449a4b835b9a2b3f63bd14d22a7294049e8c5](https://github.com/magento/magento2/commit/c17449a4b835b9a2b3f63bd14d22a7294049e8c5)
 - [c09e59b1f8c909379b64076da26db5c011285bf4](https://github.com/magento/magento2/commit/c09e59b1f8c909379b64076da26db5c011285bf4)
 - [d21ded32be1c597a2547eae3ffb5a5d18a43f9d7](https://github.com/magento/magento2/commit/d21ded32be1c597a2547eae3ffb5a5d18a43f9d7)
 - [ce359e054eb18249e461a22ee0c954898a96b398](https://github.com/magento/magento2/commit/ce359e054eb18249e461a22ee0c954898a96b398)

The fix will be available with the upcoming 2.4.1 release.
