### ISSUE TITLE
Wrong price calculation for products with custom options

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#26091]
### Preconditions (*)

1.Magento 2.3.1 | `2.4-develop`

### Steps to reproduce (*)

1. Create a configurable products with price $52 for each option
2. Make Simple Products visible on frontend
3. Add custom option for the simple product that is not required and cost $2
4. On frontend go to configurable product and add it to the cart, check shopping cart
5. Open simple product that was just added to the cart as a part of configurable, add custom option and add product to the cart, check the cart - one product is $52 another is $54
6. Add to the cart the same product with custom option as was just added, check the cart

### Expected result (*)

One product with price $52 and 2 products with price $54

### Actual result (*)

All products are with price $54

### Additional information
- record with repro. steps https://github.com/magento/magento2/issues/26091#issuecomment-650304411

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26091-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26091-2-4-develop.instances.magento-community.engineering/admin](https://i-26091-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29922` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
![Issue_26091_gif](https://user-images.githubusercontent.com/3409584/85884785-cb372900-b7a8-11ea-8fb5-4e5c44bcc421.gif)

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
