### ISSUE TITLE
urlInput component doesn't work with JsonEncoded backend_model

### ISSUE THREAD

**Issue by viniciusfabri** [magento/magento2#26093]
### Preconditions (*)
1. Magento 2.3.3 & 2.4-develop
2. Add a varchar EAV "my_new_field" to a category with a _backend_ model "Magento\Eav\Model\Entity\Attribute\Backend\JsonEncoded::class":
```php
        $eavSetup->addAttribute(
            Category::ENTITY,
            'my_new_field',
            [
                'type' => 'varchar',
                'label' => 'My new field',
                'note' => 'My new field note',
                'input' => 'text',
                'required' => false,
                'global' => ScopedAttributeInterface::SCOPE_STORE,
                'sort_order' => 10,
                'group' => 'General',
                'backend' => \Magento\Eav\Model\Entity\Attribute\Backend\JsonEncoded::class,
            ]
        );
```

3. Add this new field to the category form as a urlInput:
```xml
        <urlInput name="my_new_field">
            <settings>
                <dataType>text</dataType>
                <label translate="true">Read More Link</label>
                <dataScope>read_more_link</dataScope>
                <urlTypes class="Magento\Ui\Model\UrlInput\LinksConfigProvider"/>
            </settings>
        </urlInput>
```

### Steps to reproduce (*)
1. Edit a category, set a link in your new field, and save the form

### Expected result (*)
1. The link is saved in the category in the database encoded as json, and upon loading the previous value is shown correctly

### Actual result (*)
1. No value is saved in the database (or sent to the server in the POST, actually)

### Technical details
After spending a couple of hours investigating this, I noticed that on the POST to the Save controller, this field is not sent on the payload. This value is being filtered out by the `utils.filterFormData(data)` function inside `Magento_Ui/js/form/client.js`
This is happening because its value is an Array, with the values being set as properties instead of values:
![image](https://user-images.githubusercontent.com/11316647/71083885-58fbe100-2194-11ea-9ddc-54bcce14cab8.png)

So the filter function thinks its empty and doesn't send the values. For comparison, if you look at the value of the component WITHOUT setting the backend_model in the EAV attribute, this is what it looks like:
![image](https://user-images.githubusercontent.com/11316647/71083942-70d36500-2194-11ea-9a56-544ffbbdc1e9.png)

But then the value arrives as an array to the server, and is not saved serialized in the field, because it has a default backend_model

My workaround was to create a plugin on beforeSave and afterLoad of the Category to serialize/unserialize the value, but it would be nice if these Magento features were compatible (or maybe I'm missing something on the field/form xml)

**Comment by DlennartD** [comment]
I'm having exactly the same problem, whatever I try, no value is getting saved in the database.

Also, when I put a value in the database by hand, it's not getting retrieved aswel. :(

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29948` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by PascalBrouwers** [comment]
- `Based on the provided information internal tickets MC-29948 were created`
- `we are archiving this ticket now as it did not get much attention from Core developers for an extended period`
- `This is done in an effort to create a quality, community-driven backlog`

No, you are closing issues but you choose not to solve them. Issues that have a clear description and are reproducible.
Either state that `JsonEncoded` is not to be used as a `backend_model` in the docs or admit that you don't want it solved.

**Comment by PascalBrouwers** [comment]
I think @viniciusfabri and allot of others will stop being contributors to this community-driven backlog if this is the way you handle it @magento-engcom-team

**Comment by rikwillems** [comment]
@viniciusfabri @DlennartD @PascalBrouwers I'm running into this ticket while search how to store the `urlInput` type. It seems like this issue has been resolved/fixed, using the `JsonEncoded` backend works now for me.
