### ISSUE TITLE
Cant get Customer Store Credit

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#26092]
### Preconditions (*)

1. Screen-recording (https://drive.google.com/file/d/1Xlz9Qoot06d7KNjHBh0SrU2s2Vce0JzI/view?usp=sharing) to get customer store credit .. no value

### Expected result (*)

1. Get Customer Store Credit : (https://user-images.githubusercontent.com/3238761/71081431-d7a64d80-2197-11ea-904f-9ba9f50aed32.jpeg)

### Actual result (*)

1. Empty Response

**Comment by salehawal** [comment]
still waiting ...

**Comment by salehawal** [comment]
any update?

**Comment by wagento-bhavin** [comment]
Hi @salehawal 
Please confirm which Magento version you are using (Open Source or Commerce). Store credit features not available in Open Source edition and that's the reason it gives error.
