### ISSUE TITLE
merge css and js

### ISSUE THREAD

**Issue by bkristl** [magento/magento2#2610]
When i use merge css and js, the path generated si wrong.

requested path in html
http://DOMAIN/static/version1449231043/_cache/merged/db6b6fc668e0d14d1ee9a8f367faf3db.css

real path on server
MAGENTO_INST_DIR/pub/static/_cache/merged/db6b6fc668e0d14d1ee9a8f367faf3db.css

So the difference is:
generate path for website  also have VERSION NUMBER, 

The same is for javascript

**Comment by magenx** [comment]
rewrite inside `/static/.htaccess` file

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
