### ISSUE TITLE
Sitemap.xml is not accessible with varnish 6 enabled

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26103]
### Preconditions (*)

1. Magento 2.4
2. Varnish 6
3. Nginx

### Steps to reproduce (*)

1. Make sure varnish 6 is configured with the VCL generated by Magento 2.3.3 admin
2. Access sitemap.xml and you will be able to access it.
3. Access after 5 or 10 minutes. You will see Error 503 Service Unavailable. Guru Meditation: XID: 1245816
4. Problem disappears after cache flush

### Expected result (*)

1. Sitemap accessible at all times

### Actual result (*)

1. Sitemap not accessible after first time.
in nginx log and screen.
[29/Dec/2019:17:49:57 +0530] "GET /sitemap.xml HTTP/2.0" 503 280 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0"

![Screenshot 2019-12-29 at 5 52 49 PM](https://user-images.githubusercontent.com/16968205/71556891-12479a00-2a64-11ea-9b1e-82b583d16ea1.jpg)

**Comment by engcom-Echo** [comment]
Hello @monotheist 

Thank you for contribution and collaboration!
Please check the [timeouts](https://info.varnish-software.com/blog/understanding-timeouts-varnish-cache) settings and varnish log (run `varnishncsa`)

**Comment by monotheist** [comment]
@engcom-Echo I don't see anything in the varnish logs. But this is what I see in nginx log and screen.
[29/Dec/2019:17:49:57 +0530] "GET /sitemap.xml HTTP/2.0" 503 280 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0"

![Screenshot 2019-12-29 at 5 52 49 PM](https://user-images.githubusercontent.com/16968205/71556891-12479a00-2a64-11ea-9b1e-82b583d16ea1.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30146` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by muthu-ziffity** [comment]
@magento-engcom-team I am working on this

**Comment by muthu-ziffity** [comment]
@magento I am working on this

**Comment by xpec-jdsp** [comment]
Hello,

I have same problem in magento 2.3.3 with varnish 6.0, is there any workaround to solve this problem?

**Comment by sergioarroyop** [comment]
@xpec-jdsp @monotheist  If you generate de varnish 6 configuration from the magento admin panel it has a restart in the vcl_hit subrutine when the object has no grace and ttl. You should pass or miss the request and fetch a new object instead of restarting the request again, it will make a loop and return the 503 at max restarts. In the `vcl_hit` change this:
`        } else {

            # Hit after TTL and grace expiration

            return (restart);

        }
`
To this:
`        } else {

            # Hit after TTL and grace expiration

            return (pass);

        }
`
