### ISSUE TITLE
Product disabled/not visible individually/doesn't exist

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#26115]
### Description
It is possible to get messages:
`"message": "Could not find a product with SKU \"simple-product-2\""`
`"message": "Could not add the product with SKU simple-product-1 to the shopping cart: Product that you are trying to add is not available."`

We see that `simple-product-2` doesn't exist and `simple-product-1` is disabled. On the storefront, the only thing that Customer knows is that the product is not available for him.

**Comment by sdzhepa** [comment]
Hi @TomashKhamlai 

Could you please help us with additional details about this issue?
- Actual/Expected results
- Steps to reproduce
- Magento version and Installation type (git or composer based)
- Example of query
