### ISSUE TITLE
Unable to sort categories on front end by Quantity

### ISSUE THREAD

**Issue by vDeggial** [magento/magento2#26124]
### Preconditions (*)

1. Magento 2.4-develop, 2.3.2-p2
2. PHP 7.2
3. MariaDB 10.3
> One thing that is missing is the fact that we have 2.3 Inventory modules disabled https://github.com/magento/magento2/issues/26124#issuecomment-572229769

### Steps to reproduce (*)

1. Update "Quantity" product attribute to be used in frontend sorting
![image](https://user-images.githubusercontent.com/51681379/71349526-e9149e80-2577-11ea-9abb-563b4ef5eee3.png)
2. Reindex and flush cache
3. Go into a category and try sorting by Quantity

### Expected result (*)

Category page with products sorted by Quantity

### Actual result (*)
"There has been an error" message and log number and this in logs
![image](https://user-images.githubusercontent.com/51681379/71349611-1bbe9700-2578-11ea-842d-c1fc5074a6a1.png)

```
[2019-12-19 01:24:41] main.INFO: SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `stock_status_index`.`stock_status` AS `is_salable` FROM `mg2e_catalog_product_entity` AS `e`
 INNER JOIN `mg2e_catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=47
 INNER JOIN `mg2e_catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 LEFT JOIN `mg2e_cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 INNER JOIN `mg2e_search_tmp_5dfad1594fde33_96411848` AS `search_result` ON e.entity_id = search_result.entity_id
 LEFT JOIN `cataloginventory_stock_item` AS `stock_item_table` ON e.entity_id=stock_item_table.product_id ORDER BY `stock_item_table`.`qty` DESC
 LIMIT 20 [] []
[2019-12-19 01:24:41] main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jri_magento.cataloginventory_stock_item' doesn't exist, query was: SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `stock_status_index`.`stock_status` AS `is_salable` FROM `mg2e_catalog_product_entity` AS `e`
 INNER JOIN `mg2e_catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=47
 INNER JOIN `mg2e_catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 LEFT JOIN `mg2e_cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 INNER JOIN `mg2e_search_tmp_5dfad1594fde33_96411848` AS `search_result` ON e.entity_id = search_result.entity_id
 LEFT JOIN `cataloginventory_stock_item` AS `stock_item_table` ON e.entity_id=stock_item_table.product_id ORDER BY `stock_item_table`.`qty` DESC
 LIMIT 20 [] []
[2019-12-19 01:24:41] main.ERROR: You cannot define a correlation name 'stock_item_table' more than once [] []
```

As you can see the cataloginventory_stock_item table somehow doesn't have table prefix as do other tables :(

**Comment by vDeggial** [comment]
@magento give me 2.3.2-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @shinoamakusa. Thank you for your request. I'm working on Magento 2.3.2-p2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shinoamakusa, here is your [Magento instance](https://i-26124-2-3-2-p2.instances.magento-community.engineering).
Admin access: [https://i-26124-2-3-2-p2.instances.magento-community.engineering/admin](https://i-26124-2-3-2-p2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vDeggial** [comment]
The issue is not there on vanilla. I contacted theme devs and they said not a theme issue ... I also disabled extensions we have one by one and no effect on the error

One thing I am thinking of ... originally the store was magento 2.2.5 then slowly upgraded to 2.3.2-p2  patch after patch almost ... the difference i can think of is that our client's store has new 2.3 magento inventory plugins disabled as we were coming from 2.2 and vanilla instance has those enabled as it is brand new 2.3.2 instance ... 

could this have anything to do with those 2.3 new inventory modules disabled? hm ...

**Comment by engcom-Delta** [comment]
Hi @shinoamakusa thank you for your report. Unfortunately , I'm not able to reproduce issue by steps you described on clean 2.4-develop. I also cannot reproduce it on magento 2.3.3 (composer installation) with disabled all Magento_Inventory modules.

**Steps to reproduce:**

- Install magento with table prefix
- Update "Quantity" product attribute to be used in frontend layered navigation
- ![image](https://user-images.githubusercontent.com/51681379/71253744-6c907e80-2331-11ea-9a12-fbd9290a3026.png)
- Reindex and flush cache
- Go into a category
- Click on QUANTITY->In Stock filter
- :heavy_check_mark: Products are filtered by **Quantity:In Stock** without errors
![image](https://user-images.githubusercontent.com/51681379/71253992-2be53500-2332-11ea-8850-0705644c70e1.png)

If you'd like to update issue, please reopen it.

**Comment by vDeggial** [comment]
You are still sorting by product name not quantity. I was talking about this toggle (Used in Storefront Sorting):
![image](https://user-images.githubusercontent.com/9992759/71295240-e9baf400-232f-11ea-9690-cc1204783a80.png)

When toggle enabled gives this upon sorting category by Quantity
![image](https://user-images.githubusercontent.com/9992759/71295315-36063400-2330-11ea-9244-c084abf1f67c.png)
 and error in logs is one i mentions in original post

**Comment by vDeggial** [comment]
The query that is being generated does not have table prefix specifically for cataloginventory_stock_item table and does for all others in the query

```
main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jri_magento.cataloginventory_stock_item' doesn't exist, query was: SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `stock_status_index`.`stock_status` AS `is_salable` FROM `mg2e_catalog_product_entity` AS `e`
 INNER JOIN `mg2e_catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=49
 INNER JOIN `mg2e_catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 LEFT JOIN `mg2e_cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 INNER JOIN `mg2e_search_tmp_5dfd42e0bb4d73_44927761` AS `search_result` ON e.entity_id = search_result.entity_id
 LEFT JOIN `cataloginventory_stock_item` AS `stock_item_table` ON e.entity_id=stock_item_table.product_id ORDER BY `stock_item_table`.`qty` DESC
 LIMIT 20 

No extension is modifying anything and theme is not affecting this in any way
All the other frontend category sortings are working  just fine

Our version is 2.3.2-p2 by the way :)
```

**Comment by vDeggial** [comment]
Could we please reopen and figure this out ;)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30001` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by augrinovska** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @augrinovska. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @augrinovska, here is your [Magento instance](https://i-26124-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26124-2-4-develop.instances.magento-community.engineering/admin](https://i-26124-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by augrinovska** [comment]
Hi @shinoamakusa thank you for your report. Unfortunately, I'm not able to reproduce the issue by steps you described on clean 2.4-develop.

**Steps to reproduce:**

- Install magento with table prefix
- Update "Quantity" product attribute to be used in frontend layered navigation
![Screenshot from 2020-01-03 12-17-18](https://user-images.githubusercontent.com/43642490/71720647-b776bf80-2e22-11ea-9cc8-93bfac62495a.png)

- Reindex and flush cache
- Go into a category
- Click on QUANTITY->In Stock filter
- heavy_check_mark Products are filtered by Quantity: In Stock without errors

![Screenshot from 2020-01-03 12-18-58](https://user-images.githubusercontent.com/43642490/71720713-edb43f00-2e22-11ea-8b08-64c5e1937fca.png)

![Screenshot from 2020-01-03 12-19-30](https://user-images.githubusercontent.com/43642490/71720732-01f83c00-2e23-11ea-932c-10e7c4897e0b.png)

**Comment by vDeggial** [comment]
One thing that is missing is the fact that we have 2.3 Inventory modules disabled
No other extension or plugin have any effect on the issue and SQL query generation is done by magento itself I believe

**Comment by shinoamakusa** [comment]
Got tired of waiting and just created a view in db called cataloginventory_stock_item and set it to select * from mg2e_cataloginventory_stock_itemand it works (mg2e is our table prefix)

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
