### ISSUE TITLE
Support webp

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26123]
### Description (*)

Add support for webp.

Because once you go webp, you don't go back.

A PNG file of 344 KB can be compressed down to 31 KB using webp without any visual loss.

### Expected behavior (*)

Able to upload and use webp images in WYSIWYG editor.

### Benefits

1. Faster store
1. Better pagerank score
1. Better mobile experience
1. Better third world internet experience
1. Better SEO
1. Less bandwidth
1. Less disk space
1. More profit
1. Happier CEO

**Comment by krishprakash** [comment]
Hi @Zyles. 
The GitHub issue tracker is intended for Magento Core technical issues only.
Seems you improve the magneto by supporting with new feature so please add this in [feature request repository ](https://github.com/magento/community-features/issues)
So closing this ticket.
Thank You.

**Comment by Zyles** [comment]
Oh yeah I forgot about that repo that nobody in the Magento 2 team reads.

Will re-post it there.

Thanks.

**Comment by kamephis** [comment]
Why is this closed. In which version has webp support been added?
