### ISSUE TITLE
Lock Error While Updating Products Websites Attributes Mass Action 

### ISSUE THREAD

**Issue by Feyks** [magento/magento2#26138]
### Context

Migrating data from Magento 1.9.3.8 to 2.3.3, i used the module data-migration-tool. When the migration succeeded, I began to look at the product on the frontend. Theproduct hadn't been associated to my new website.
So I intended to associate them with a mass action using Catalog->Products->Select All->Update Attributes->Websites.
The Bulk Action wasn't starting so I intended to launch the  queue by hand. 

### Preconditions
Magento version 2.3.3, MySQL 15.1

### Steps to reproduce

1. Create a Bulk Action with Update Attributes->Websites
2. In shell, launch : php bin/magento queue:consumers:start product_action_attribute.website.update (See )
3. Check in Mysql Client if base is used with `SHOW OPEN TABLES IN magento_database;`
4. In the Mysql Client try `UPDATE mg2_queue_message_status SET status = 3 WHERE (id = 2)`

### Expected result

1. Execute all queue with product_action_attribute.website.update type
2. Having products updated

### Actual result

1. Getting the following MySQL Error for Steps 3 and 4: 

> General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: UPDATE 'mg2_queue_message_status' SET 'status' = ? WHERE (id = '2')

I don't know if it's my configuration of Magento 2 or MySQL but whatever I try I can't either UPDATE or DELETE from `queue_messages` and `queue_messages_status` databases.

**Comment by Feyks** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Feyks. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Feyks, here is your [Magento instance](https://i-26138-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26138-2-4-develop.instances.magento-community.engineering/admin](https://i-26138-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
