### ISSUE TITLE
Bug with Search Engine Optimization

### ISSUE THREAD

**Issue by syntaxwanderer** [magento/magento2#2613]
We can use html for textarea of Meta Description or Meta Keywords. And any tag can broke all page. I think we need clear all html tags for this field. And, I see this bug because magento 2 added html code automatically from my product description. This is a bug.

**Comment by vil11** [comment]
@ArniXXX 
Taras, thanks for reporting the issue!
Internal ticket **MAGETWO-48511**.

Dmytro Vilchynskyi, M2 QA engineer.

**Comment by vzabaznov** [comment]
@ArniXXX bug was fixed and delivered to develop branch
