### ISSUE TITLE
Add new customer address error window.checkoutConfig is undefined due by postCodeValidator

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#26145]
### Preconditions (*)

1. Magento CE 2.3.3
2.

### Steps to reproduce (*)

1. Landing to create new customer address
2. Don't input anything at first but change the country to see State/Province changed accordingly

### Expected result (*)

1. Non of javascript error on log
2. State/Province changed accordingly follow country

### Actual result (*)

1. window.checkoutConfig is undefined
2. State/Province not changed while switching country

**Comment by tuyennn** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tuyennn, here is your [Magento instance](https://i-26145-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26145-2-4-develop.instances.magento-community.engineering/admin](https://i-26145-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tuyennn** [comment]
Closed due cannot replicate on vanilla Magento instance
