### ISSUE TITLE
PageBuilder disabled still shows layout on frontend for product page

### ISSUE THREAD

**Issue by ezequielalba** [magento/magento2#26143]
### Preconditions (*)

1. Magento 2.3.3
2. Clean instance by scratch, inheriting from Luma Theme

### Steps to reproduce (*)

1. Disable PageBuilder for global site scope configs or CLI
2. Flush cache and load Product Page
3. Layout should be default from Magento core not the PageBuilder overrides.

Here what DevDocs says it should happen: https://devdocs.magento.com/page-builder/docs/how-to/how-to-use-full-width-layouts.html#disabling-page-builder

### Expected result (*)

1. Product and Category pages layout should render default layouts
2. Custom overrides provided by Pagebuilder should not load. Like DevDocs says.

### Actual result (*)

1. Product and Category pages layouts are the ones coming from PageBuilder module overrides.
2. There's no config to change for me to change it via admin or CLI, these appears to have priority still over Magento fallback inheritance:

```
<default_layouts>
       <default_category_layout>category-full-width</default_category_layout>
       <default_product_layout>product-full-width</default_product_layout>
       <default_cms_layout>cms-full-width</default_cms_layout>
</default_layouts>
```
![Screen Shot 2019-12-19 at 4 35 33 PM](https://user-images.githubusercontent.com/14914190/71220526-a2742b00-227d-11ea-9deb-6142aab97126.png)

**Note**: I haven't changed any other configurations for layout desings under categories or product. Always working with global or store configs here. Just in case.

**Comment by ezequielalba** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @ezequielalba. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ezequielalba, here is your [Magento instance](https://i-26143-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26143-2-3-3.instances.magento-community.engineering/admin](https://i-26143-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ezequielalba** [comment]
@magento the instance I need has to be Enterprise edition with PageBuilder included. I can't replicate on 2.3.3 Open Source vanilla instance.

**Comment by ezequielalba** [comment]
**UPDATE**: 

The issue is that pagebuilder by being enabled by default on 2.3.3 overrides Default Layouts configurations, so even if pagebuilder is disabled the configurations stays the same because there's no automatic update (bad logic behind it). 

**FIX**: 
- Setup script to update `web/default_layouts/default_product_layout` with the default Magento layout for product you want.
- Via Admin Configuration > Web > Default Layouts > Default Product Layout.
