### ISSUE TITLE
"Found 2 elements with non-unique id" warning appears in browser console on pages where sticky headers are enabled

### ISSUE THREAD

**Issue by chalov-anton** [magento/magento2#26147]
### Preconditions (*)
1. Magento 2.4 
2. Chrome version(Version 79.0.3945.79)

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Content - Pages
- Open Chrome Developer Console (F12) and observe 

### Expected result (*)
No warning messages, all id's should be unique

### Actual result (*)
Warning message _Found 2 elements with non-unique id_
![two_elements_with_non_uniqu_id](https://user-images.githubusercontent.com/45624059/71238654-583a8a80-230d-11ea-8408-d4edde6d48db.png)

### Technical details

The issue can be reproduced on any UI listing grid with sticky header enabled

### Related issue
 https://github.com/magento/adobe-stock-integration/issues/862

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29966` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by madhurajawat** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @madhurajawat. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by madhurajawat** [comment]
@magento I am working on it

**Comment by magento-engcom-team** [comment]
Hi @madhurajawat, here is your [Magento instance](https://i-26147-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26147-2-4-develop.instances.magento-community.engineering/admin_8798](https://i-26147-2-4-develop.instances.magento-community.engineering/admin_8798)
Login: `8d75dc48` Password: `81f496f0f67e`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
