### ISSUE TITLE
Elasticsearch is not able to search “5600” when product name has “TW5600”

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#26146]
**My Product name:** `Epson EH TW5600 Full HD Home Cinema Projector | Lens Shift | 2500 Lumens | Bluetooth Audio`

**Search Term:** `"5600"` or `"Epson 5600"`

In the above condition, my elasticsearch is not able to search **"5600"**. It returns empty products. 

I was using `solr` in my Magento 1 and it was working fine.

### Preconditions (*)

1. Magento 2.3
2. Elastic Search 6+ and enabled
3. Product name having "TW5600"

### Steps to reproduce (*)

1. Search 5600

### Expected result (*)

1. Show that product at the top

### Actual result (*)

1. Empty result.

**Comment by engcom-Bravo** [comment]
Hello @adarshkhatri  
Thank you for your report.
We are aware of this problem, there is already a similar issue entered under Magento2 repository
https://github.com/magento/magento2/issues/25115
We are closing this issue as Duplicate
