### ISSUE TITLE
Table quote column customer_note uses wrong type

### ISSUE THREAD

**Issue by seppoviuh** [magento/magento2#26155]
### Preconditions (*)
Magento version 2.3.3 & 2.4-develop
The table "quote" column "customer_note" uses type varchar(255). It should be using type "text" instead. In every other sales table, the type is defined as "text".

Changing the data type from a custom module is also not possible with the declarative schema feature because the attribute length is not allowed.
![image](https://user-images.githubusercontent.com/39083752/71258819-5f768e00-2337-11ea-9f6f-82f721e523c6.png)

![image](https://user-images.githubusercontent.com/39083752/71258516-9f894100-2336-11ea-9e2b-a81dea8e6399.png)

### Steps to reproduce (*)

1. Install Magento 2.3.3
2. View database table quote and check the column customer_note

### Expected result (*)
1. Type is text

### Actual result (*)
1. Type is varchar 255

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29982` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @seppoviuh. Thank you for your report. 
The issue has been fixed in magento/magento2#26160 by @ravi-chandra3197 in 2.4-develop branch
Related commit(s):
 - [0621d52235993e3eec4835490e1939af09137481](https://github.com/magento/magento2/commit/0621d52235993e3eec4835490e1939af09137481)

The fix will be available with the upcoming 2.4.0 release.

**Comment by iproger** [comment]
Full error text (for searchers like me...):

	The XML in file "...etc/db_schema.xml" is invalid:
	Element 'column', attribute 'length': The attribute 'length' is not allowed.
	Line: 4

	Verify the XML and try again.

So, this is my fix:
```
use Magento\Framework\Setup\Declaration\Schema\Declaration\ReaderComposite;

class ReaderCompositePlugin
{
    public function afterRead(ReaderComposite $subject, $result)
    {
        if (isset($result['table']['quote']) && isset($result['table']['quote']['column']['customer_note'])) {
            $result['table']['quote']['column']['customer_note']['type'] = 'text';
            unset($result['table']['quote']['column']['customer_note']['length']);
        }

        return $result;
    }
}
```

**Comment by raghuiamsingh** [comment]
when can we expect a fix for this?
