### ISSUE TITLE
Magento\Quote\Model\Quote::removeItem() not working when the deprecated Magento\Checkout\Model\Cart::removeItem() does

### ISSUE THREAD

**Issue by Phennim** [magento/magento2#26153]
I'm trying to remove a quote item under certain conditions when adding another product to the cart.
Since the Cart shows a deprecated warning I tried the suggested Quote class. But I'm unable to us it to remove a quote item with it.

### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Subscribe to `checkout_cart_product_add_after` event
```
<event name="checkout_cart_product_add_after">
    <observer name="acme_checkout_cart_add_observer" instance="Acme\Catalog\Observer\CheckoutCartAddObserver" />
</event>
```
2. Inject the two classes:
```
public function __construct(\Magento\Checkout\Model\Cart $cart, \Magento\Quote\Model\Quote $quote)
{
    $this->cart = $cart;
    $this->quote = $quote;
}
```
3. Test both functions:
```
public function execute(EventObserver $observer)
{
    $quote_item_id_a = 1;
    $this->cart->removeItem($quote_item_id_a);  // does work
    $quote_item_id_b = 2;
    $this->quote->removeItem($quote_item_id_b); // does not work
}
```

### Expected result (*)
Both quote items should be removed from the database.

### Actual result (*)
Only the quote with `$quote_item_id_a` is removed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30629` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mcspronko** [comment]
Who works on this issue?

Please clarify @shikhamis11 @GovindaSharma

**Comment by shikhamis11** [comment]
@mcspronko I am working on this issue .. but I won't mind if you will provide solution or make PR for this

**Comment by sivaschenko** [comment]
@Phennim @shikhamis11 Cart removeItem method is actually proxies the call to quote removeItem method. Can you confirm that these methods really work differently?

**Comment by djamesmelon** [comment]
Was this issue ever fixed? I am running into this exact issue as well.
