### ISSUE TITLE
Class \Magento\Framework\Data\Form\Element\Textarea breaks specification of the parent class \Magento\Framework\Data\Form\Element\AbstractElement by not calling the method getAfterElementJs() 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2615]
https://mage2.pro/t/246

Similar to https://github.com/magento/magento2/issues/2202

**Comment by wert2all** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
