### ISSUE TITLE
Magento 2 Composer error when trying to install modules [UnexpectedValueException]

### ISSUE THREAD

**Issue by startshopNL** [magento/magento2#26151]
I'm trying to install a module with magento 2 composer. However, when I try the command:

    composer require sendcloud/sendcloud

**I see an error:**

    [UnexpectedValueException]
    RecursiveDirectoryIterator::__construct(vendor/magmodules/packages): failed to open dir: No such file or directory

**Earlier, I tried to install a module :** 

    composer config repositories.magmodulesartifacts artifact vendor/magmodules/packages
    composer require magmodules/GoogleShopping:1.1.4

But. that wasn't very successful. Probably, it's related with that. Then, I installed that module via FTP.

Please help me fix this error. 

Thanks!

**Comment by startshopNL** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @startshopNL. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @startshopNL, here is your [Magento instance](https://i-26151-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26151-2-4-develop.instances.magento-community.engineering/admin](https://i-26151-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by augrinovska** [comment]
Hi @startshopNL, 

This issue seems to be related to your composer/PHP version. I couldn't reproduce this error using Magento 2.4-develop branch and PHP 7.3.

**Comment by engcom-Delta** [comment]
@startshopNL thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop.
**Result:**
![image](https://user-images.githubusercontent.com/51681379/96756636-03f4b100-13dd-11eb-9ea2-4340ffa07c32.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
