### ISSUE TITLE
Unable to save shipment address. Firstname is required

### ISSUE THREAD

**Issue by krausenspb** [magento/magento2#26159]
### Summary

When I try to place an order after the customer registration/Login. Magento 2.3.3 shows "First Name is a required Field Error. Firstname field is not displayed. When I try create shipping address at profile page or at backend - firstname field is displayed but same validation error occured!

### Preconditions
Magento 2.3.3
Migration from 1.9.3.4

### Steps to reproduce
1. Login
2. Checkout order
3. Fill shipping form

### Expected result

1. Order has been placed.

### Actual result 
1.  Error displayed: Please check the shipping address information. "firstname" is required. Enter and try again.

<b>Place order - firstname is hidden</b>
![Place order - firstname is hidden](https://user-images.githubusercontent.com/17198710/71327928-e4bc9700-251f-11ea-8eb6-70c81ce32245.png)

<b>Profile create shipping address</b>
![Profile create shipping address](https://user-images.githubusercontent.com/17198710/71327909-9effce80-251f-11ea-8f17-3ba28e4b9370.png)

<b>Backend = customer edit - shipping adress add</b>
![Backend = customer edit - shipping adress add](https://user-images.githubusercontent.com/17198710/71327936-13d30880-2520-11ea-8d62-af22de5b39de.png)

###  Description

I read about same troubles in another versions magento but no solutions found

I try to play with eav_attribute and customer_eav_attribute. I put is_visible=1 and is_required=0 but It not helps

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26159-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26159-2-4-develop.instances.magento-community.engineering/admin](https://i-26159-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @krausenspb. Not able to reproduce the issue.
please update the steps to reproduce the issue with proper reproducible steps.
Thanks.

**Comment by krausenspb** [comment]
@krishprakash May be trouble because data migration from 1.9.3.4 so you can't reproduce it on clear magento?

Backend steps:
1. Login to backend
2. Go to cutomers->All customers-> Edit customer ->Addreses -> Add new address
3. Filll all required fields and submit form
4. Validation fails (firstname is required)

![222](https://user-images.githubusercontent.com/17198710/71349474-2846ed80-2580-11ea-8ea8-7cb705d37d0c.png)

**Comment by krishprakash** [comment]
Hi @krausenspb. Thank you for feedback.
Are you done the migration with data migration tool ?

**Comment by krausenspb** [comment]
@krishprakash  yes, data migration tool

Additional info: When I try to edit shipping address, all fields saved exept "firstname".

**Comment by krishprakash** [comment]
All the Data Migration tool related issues should reported in its separate [Data migration tool repository](https://github.com/magento/data-migration-tool/issues)
Please report issue here.
Thanks

**Comment by krausenspb** [comment]
@krishprakash Thanks for answer. 
But I don't know issue related with migration tool or not. But I will duplicate issue. Thanks

**Comment by Dragonisser** [comment]
Event tho i did an migration earlier, i also created two new customer and im getting the exact same error on both. 

Using Magento 2.3.5-p1.

![image](https://user-images.githubusercontent.com/4233773/83859957-f3d68080-a71e-11ea-8a81-6b807a9ba969.png)

**Comment by dekiakbar** [comment]
@Dragonisser @krausenspb did you solve this issue ? I got this issue after migration from Magento 1.9 to Magento 2.3, still got no luck for this issue

**Comment by dekiakbar** [comment]
@Dragonisser @krausenspb I have fix it for my end,  you can chech it on this link https://stackoverflow.com/questions/59453442/magento-2-3-3-customer-shipping-address-firstname-trouble-firstname-is-requir/62527887#62527887
