### ISSUE TITLE
Vertex_Tax module, "No such entity with addressId", excessive logging

### ISSUE THREAD

**Issue by brankoajzele** [magento/magento2#26152]
### Summary (*)
The `getDefaultBilling` and `getDefaultShipping` methods of `vendor/vertex/module-tax/Model/AddressDeterminer.php` log every exception.

```
private function getDefaultBilling($customerId)
{
    try {
        $customer = $this->customerRepository->getById($customerId);
        $addressId = $customer->getDefaultBilling();

        return $this->addressRepository->getById($addressId);
    } catch (\Exception $e) {
        $this->logger->warning($e);
        return null;
    }
}

private function getDefaultShipping($customerId)
{
    try {
        $customer = $this->customerRepository->getById($customerId);
        $addressId = $customer->getDefaultShipping();

        return $this->addressRepository->getById($addressId);
    } catch (\Exception $e) {
        $this->logger->warning($e);
        return null;
    }
}
```
The logging happens.
- whenever a new customer is registered and does not yet have any address assigned
- whenever existing customer, without address assigned, adds a product to cart

Given how try-catch code is already accounting for the NULL address state, why log an error?

It seems a bit excessive to log this, as it is clogging log files.

Is there a specific reason for logging?

### Proposed solution
Remove `$this->logger->warning($e);`?

**Comment by navarr** [comment]
Hi @ajzele,

Could you please provide information about your environment as is requested in the ticket template?

**Comment by brankoajzele** [comment]
It seems to be the same ting ... https://github.com/magento/magento2/issues/15115, in my case I was using Magento 2.3.3
