### ISSUE TITLE
Customer with Same Email Id Exists in the store. Please try to reset password

### ISSUE THREAD

**Issue by aloksparx** [magento/magento2#26166]
Hi, I have upgraded the magento 2 version from 2.2.3 - 2.3.3. After upgrade everything working as expected but the Customer registration is not working and throwing error "Customer with Same Email Id Exists in the store. Please try to reset password". Nothing can be found in the log files.
You can check the issue at https://www.pretmetled.nl/customer/account/create/

Website is live and we are loosing customers so any suggestion will be great help.

**Comment by shikhamis11** [comment]
Hi @aloksparx 
Please correct the issue format .. also please provide additional informations to reproduce this issue.

**Comment by aloksparx** [comment]
Please close the ticket. I found problem was due to extension i was using for mailchimp. Extension URL: https://store.ebizmarts.com/mailchimp4magento2.html
