### ISSUE TITLE
Cant find Magento Connect Section in System of Admin

### ISSUE THREAD

**Issue by Xinecraft** [magento/magento2#2616]
Hey,
      I am using Magento Community Edition 2.0 and was unable to find out Magento Connect in System section of Admin. Plz tell if its shifted to somewhere else.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by dmitrii-fediuk** [comment]
Connect for Magento 2 just does not exist yet.
If you want install an extension you should contact to the extension's developer for an installation instuctions.
