### ISSUE TITLE
Upgrading from 2.3.1 to 2.3.3 | Blank Page

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#26178]
### Preconditions (*)
1- Magento 2.3.3
2- php 7.1

### Steps to reproduce (*)
1. Upgrade from Magento 2.3.1 to 2.3.3

### Expected result (*)
1. site to work fine

### Actual result (*)
1. blank page with Error Code 500 in Request

**Comment by Zyles** [comment]
And what is the 500 error in logs?

Clean cache etc.

**Comment by nilesh2jcommerce** [comment]
Hi @salehawal ,

I have upgraded Magento version from 2.3.1 to 2.3.3. After executes all commands to upgrade .Magento upgraded successfully and working fine. 

You have to upgrade php version too from 7.1 to 7.2. Magento 2.3.3 now supports PHP 7.3.x (tested with PHP 7.3.8) and PHP 7.2.x (tested with 7.2.21)
As you using php 7.1 
Then execute composer require magento/product-enterprise-edition 2.3.3 --no-update
composer update
php bin/magento setup:upgrade

After that clean cache Magento will get upgraded and work.

**Comment by salehawal** [comment]
i have the community version not the enterprise .. and the issue was a missing vendor module which i copy from a backup and it worked

now i have a new issue: 

1 exception(s):
Exception #0 (Exception): Warning: filesize(): stat failed for https://cdn.jomlah.com/pub/media/mageplaza/brand/apple.jpg in /var/www/dev.jomlah.com/vendor/magento/framework/Image/Adapter/Gd2.php on line 63

Exception #0 (Exception): Warning: filesize(): stat failed for https://cdn.jomlah.com/pub/media/mageplaza/brand/apple.jpg in /var/www/dev.jomlah.com/vendor/magento/framework/Image/Adapter/Gd2.php on line 63
<pre>#1 filesize('https://cdn.joml...') called at [vendor/magento/framework/Image/Adapter/Gd2.php:63]
#2 Magento\Framework\Image\Adapter\Gd2->open('https://cdn.joml...') called at [app/code/Mageplaza/Shopbybrand/Block/Brand.php:498]
#3 Mageplaza\Shopbybrand\Block\Brand->resizeImage(&Magento\Eav\Model\Entity\Attribute\Option#000000001c99ac76000000001fbe77bf#, 80) called at [app/code/Mageplaza/Shopbybrand/view/frontend/templates/position/topmenu.phtml:41]
#4 include('/var/www/dev.jom...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#5 Magento\Framework\View\TemplateEngine\Php->render(&Mageplaza\Shopbybrand\Block\Brand#000000001c99ac68000000001fbe77bf#, '/var/www/dev.jom...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#6 Magento\Framework\View\Element\Template->fetchView('/var/www/dev.jom...') called at [vendor/magento/framework/View/Element/Template.php:301]
#7 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
#8 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1101]
#9 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
#10 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [app/code/Mageplaza/Shopbybrand/Plugin/Link/Topmenu.php:40]
#11 Mageplaza\Shopbybrand\Plugin\Link\Topmenu->afterGetHtml(&Magento\Theme\Block\Html\Topmenu\Interceptor#000000001c9988ec000000001fbe77bf#, '<li  class="leve...', 'level-top', 'submenu', 0) called at [vendor/magento/framework/Interception/Interceptor.php:146]
#12 Magento\Theme\Block\Html\Topmenu\Interceptor->Magento\Framework\Interception\{closure}('level-top', 'submenu', 0) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Theme\Block\Html\Topmenu\Interceptor->___callPlugins('getHtml', array('level-top', 'submenu', 0), array(array('catalogTopmenu'), array('brand-topmenu'))) called at [generated/code/Magento/Theme/Block/Html/Topmenu/Interceptor.php:26]
#14 Magento\Theme\Block\Html\Topmenu\Interceptor->getHtml('level-top', 'submenu', 0) called at [app/design/frontend/Sm/metro/Magento_Theme/templates/html/nav-mobile.phtml:20]
#15 include('/var/www/dev.jom...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#16 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Theme\Block\Html\Topmenu\Interceptor#000000001c9988ec000000001fbe77bf#, '/var/www/dev.jom...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#17 Magento\Framework\View\Element\Template->fetchView('/var/www/dev.jom...') called at [generated/code/Magento/Theme/Block/Html/Topmenu/Interceptor.php:154]
#18 Magento\Theme\Block\Html\Topmenu\Interceptor->fetchView('/var/www/dev.jom...') called at [vendor/magento/framework/View/Element/Template.php:301]
#19 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
#20 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/Cache/LockGuardedCacheLoader.php:79]
#21 Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('BLOCK_e2a139a7c3...', &Closure#000000001c999362000000001fbe77bf#, &Closure#000000001c999308000000001fbe77bf#, &Closure#000000001c9993a2000000001fbe77bf#) called at [vendor/magento/framework/View/Element/AbstractBlock.php:1133]
#22 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
#23 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [generated/code/Magento/Theme/Block/Html/Topmenu/Interceptor.php:479]
#24 Magento\Theme\Block\Html\Topmenu\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
#25 Magento\Framework\View\Layout->_renderBlock('nav.mobile') called at [vendor/magento/framework/View/Layout.php:533]
#26 Magento\Framework\View\Layout->renderNonCachedElement('nav.mobile') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#27 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('nav.mobile') called at [vendor/magento/framework/View/Layout.php:488]
#28 Magento\Framework\View\Layout->renderElement('nav.mobile', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#29 Magento\Framework\View\Layout\Interceptor->renderElement('nav.mobile', false) called at [vendor/magento/framework/View/Layout.php:585]
#30 Magento\Framework\View\Layout->_renderContainer('navigation.mobil...', false) called at [vendor/magento/framework/View/Layout.php:535]
#31 Magento\Framework\View\Layout->renderNonCachedElement('navigation.mobil...') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#32 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('navigation.mobil...') called at [vendor/magento/framework/View/Layout.php:488]
#33 Magento\Framework\View\Layout->renderElement('navigation.mobil...', true) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#34 Magento\Framework\View\Layout\Interceptor->renderElement('navigation.mobil...', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:518]
#35 Magento\Framework\View\Element\AbstractBlock->getChildHtml('navigation.mobil...') called at [app/design/frontend/Sm/metro/Magento_Theme/templates/html/header-style/header-1.phtml:181]
#36 include('/var/www/dev.jom...') called at [app/design/frontend/Sm/metro/Magento_Theme/templates/html/header.phtml:16]
#37 include('/var/www/dev.jom...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#38 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Theme\Block\Html\Header#000000001c9989e4000000001fbe77bf#, '/var/www/dev.jom...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#39 Magento\Framework\View\Element\Template->fetchView('/var/www/dev.jom...') called at [vendor/magento/framework/View/Element/Template.php:301]
#40 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
#41 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1101]
#42 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
#43 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
#44 Magento\Framework\View\Layout->_renderBlock('header.content') called at [vendor/magento/framework/View/Layout.php:533]
#45 Magento\Framework\View\Layout->renderNonCachedElement('header.content') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#46 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('header.content') called at [vendor/magento/framework/View/Layout.php:488]
#47 Magento\Framework\View\Layout->renderElement('header.content', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#48 Magento\Framework\View\Layout\Interceptor->renderElement('header.content', false) called at [vendor/magento/framework/View/Layout.php:585]
#49 Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:535]
#50 Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#51 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper') called at [vendor/magento/framework/View/Layout.php:488]
#52 Magento\Framework\View\Layout->renderElement('page.wrapper', false) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#53 Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:585]
#54 Magento\Framework\View\Layout->_renderContainer('root', false) called at [vendor/magento/framework/View/Layout.php:535]
#55 Magento\Framework\View\Layout->renderNonCachedElement('root') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#56 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root') called at [vendor/magento/framework/View/Layout.php:488]
#57 Magento\Framework\View\Layout->renderElement('root', true) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#58 Magento\Framework\View\Layout\Interceptor->renderElement('root') called at [vendor/magento/framework/View/Layout.php:954]
#59 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#60 Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#61 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#62 Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', array(), array(array('layout-model-cac...'))) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:494]
#63 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#64 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#000000001c998d9d000000001fbe77bf#) called at [vendor/magento/framework/View/Result/Layout.php:171]
#65 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#000000001c998d9d000000001fbe77bf#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#66 Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#000000001c998d9d000000001fbe77bf#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#67 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Response\Http\Interceptor#000000001c998d9d000000001fbe77bf#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#68 Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#000000001c998d9d000000001fbe77bf#), array(array('result-messages', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:130]
#69 Magento\Framework\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#000000001c998d9d000000001fbe77bf#) called at [vendor/magento/framework/App/Http.php:141]
#70 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#71 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#72 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000001c998d96000000001fbe77bf#) called at [index.php:39]
</pre>

**Comment by salehawal** [comment]
i have 2 sites using the same CDN, do i have to turn off the CDN on the test one? the one i am upgrading is dev.jomlah.com

**Comment by salehawal** [comment]
i did removed CDN and still the issue is present .. 

1 exception(s):
Exception #0 (Exception): Warning: filesize(): stat failed for https://dev.jomlah.com/pub/media/mageplaza/brand/apple.jpg in /var/www/dev.jomlah.com/vendor/magento/framework/Image/Adapter/Gd2.php on line 63

Exception #0 (Exception): Warning: filesize(): stat failed for https://dev.jomlah.com/pub/media/mageplaza/brand/apple.jpg in /var/www/dev.jomlah.com/vendor/magento/framework/Image/Adapter/Gd2.php on line 63
<pre>#1 filesize('https://dev.joml...') called at [vendor/magento/framework/Image/Adapter/Gd2.php:63]
#2 Magento\Framework\Image\Adapter\Gd2->open('https://dev.joml...') called at [app/code/Mageplaza/Shopbybrand/Block/Brand.php:498]
#3 Mageplaza\Shopbybrand\Block\Brand->resizeImage(&Magento\Eav\Model\Entity\Attribute\Option#0000000058890950000000004f7482ba#, 80) called at [app/code/Mageplaza/Shopbybrand/view/frontend/templates/position/topmenu.phtml:41]
#4 include('/var/www/dev.jom...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#5 Magento\Framework\View\TemplateEngine\Php->render(&Mageplaza\Shopbybrand\Block\Brand#000000005889d957000000004f7482ba#, '/var/www/dev.jom...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#6 Magento\Framework\View\Element\Template->fetchView('/var/www/dev.jom...') called at [vendor/magento/framework/View/Element/Template.php:301]
#7 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
#8 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1101]
#9 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
#10 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [app/code/Mageplaza/Shopbybrand/Plugin/Link/Topmenu.php:40]
#11 Mageplaza\Shopbybrand\Plugin\Link\Topmenu->afterGetHtml(&Magento\Theme\Block\Html\Topmenu\Interceptor#000000005889998d000000004f7482ba#, '<li  class="leve...', 'level-top', 'submenu', 0) called at [vendor/magento/framework/Interception/Interceptor.php:146]
#12 Magento\Theme\Block\Html\Topmenu\Interceptor->Magento\Framework\Interception\{closure}('level-top', 'submenu', 0) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Theme\Block\Html\Topmenu\Interceptor->___callPlugins('getHtml', array('level-top', 'submenu', 0), array(array('catalogTopmenu'), array('brand-topmenu'))) called at [generated/code/Magento/Theme/Block/Html/Topmenu/Interceptor.php:26]
#14 Magento\Theme\Block\Html\Topmenu\Interceptor->getHtml('level-top', 'submenu', 0) called at [app/design/frontend/Sm/metro/Magento_Theme/templates/html/nav-mobile.phtml:20]
#15 include('/var/www/dev.jom...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#16 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Theme\Block\Html\Topmenu\Interceptor#000000005889998d000000004f7482ba#, '/var/www/dev.jom...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#17 Magento\Framework\View\Element\Template->fetchView('/var/www/dev.jom...') called at [vendor/magento/framework/View/Element/Template.php:301]
#18 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
#19 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/Cache/LockGuardedCacheLoader.php:79]
#20 Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('BLOCK_e2a139a7c3...', &Closure#000000005889dc28000000004f7482ba#, &Closure#000000005889d33e000000004f7482ba#, &Closure#000000005889dc46000000004f7482ba#) called at [vendor/magento/framework/View/Element/AbstractBlock.php:1133]
#21 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
#22 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
#23 Magento\Framework\View\Layout->_renderBlock('nav.mobile') called at [vendor/magento/framework/View/Layout.php:533]
#24 Magento\Framework\View\Layout->renderNonCachedElement('nav.mobile') called at [vendor/magento/framework/View/Layout.php:488]
#25 Magento\Framework\View\Layout->renderElement('nav.mobile', false) called at [vendor/magento/framework/View/Layout.php:585]
#26 Magento\Framework\View\Layout->_renderContainer('navigation.mobil...', false) called at [vendor/magento/framework/View/Layout.php:535]
#27 Magento\Framework\View\Layout->renderNonCachedElement('navigation.mobil...') called at [vendor/magento/framework/View/Layout.php:488]
#28 Magento\Framework\View\Layout->renderElement('navigation.mobil...', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:518]
#29 Magento\Framework\View\Element\AbstractBlock->getChildHtml('navigation.mobil...') called at [app/design/frontend/Sm/metro/Magento_Theme/templates/html/header-style/header-1.phtml:181]
#30 include('/var/www/dev.jom...') called at [app/design/frontend/Sm/metro/Magento_Theme/templates/html/header.phtml:16]
#31 include('/var/www/dev.jom...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#32 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Theme\Block\Html\Header#0000000058899b76000000004f7482ba#, '/var/www/dev.jom...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#33 Magento\Framework\View\Element\Template->fetchView('/var/www/dev.jom...') called at [vendor/magento/framework/View/Element/Template.php:301]
#34 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
#35 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1101]
#36 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
#37 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
#38 Magento\Framework\View\Layout->_renderBlock('header.content') called at [vendor/magento/framework/View/Layout.php:533]
#39 Magento\Framework\View\Layout->renderNonCachedElement('header.content') called at [vendor/magento/framework/View/Layout.php:488]
#40 Magento\Framework\View\Layout->renderElement('header.content', false) called at [vendor/magento/framework/View/Layout.php:585]
#41 Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:535]
#42 Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') called at [vendor/magento/framework/View/Layout.php:488]
#43 Magento\Framework\View\Layout->renderElement('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:585]
#44 Magento\Framework\View\Layout->_renderContainer('root', false) called at [vendor/magento/framework/View/Layout.php:535]
#45 Magento\Framework\View\Layout->renderNonCachedElement('root') called at [vendor/magento/framework/View/Layout.php:488]
#46 Magento\Framework\View\Layout->renderElement('root') called at [vendor/magento/framework/View/Layout.php:954]
#47 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#48 Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#49 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#50 Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', array(), array(array('layout-model-cac...'))) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:39]
#51 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#52 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#0000000058899a57000000004f7482ba#) called at [vendor/magento/framework/View/Result/Layout.php:171]
#53 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000058899a57000000004f7482ba#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#54 Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000058899a57000000004f7482ba#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#55 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Response\Http\Interceptor#0000000058899a57000000004f7482ba#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#56 Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000058899a57000000004f7482ba#), array(array('result-messages', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:39]
#57 Magento\Framework\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000058899a57000000004f7482ba#) called at [vendor/magento/framework/App/Http.php:141]
#58 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#59 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000058899a55000000004f7482ba#) called at [index.php:39]
</pre>

**Comment by salehawal** [comment]
confirming that it is not a permission issue after applying 777 to pub/media/*

**Comment by Zyles** [comment]
Looks like a Mageplaza issue not Magento. Contact them.

**Comment by nilesh2jcommerce** [comment]
@salehawal 
Yes it is Mageplaza custom module issue not Magento issue.

**Comment by salehawal** [comment]
already did .. lets see their feedback

**Comment by salehawal** [comment]
ok they fixed the issue and now we are back to blank page issue and when i checked the error log i get this error:


2019-12-31 19:20:26.150087 [NOTICE] [19719] [102.46.38.208:36004:HTTP2-19] [STDERR] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ResourceModel\Product\Collection::addIsSaleableAttributeToFilter() must be of the type array or null, integer given, called in /var/www/dev.jomlah.com/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php on line 1582 and defined in /var/www/dev.jomlah.com/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php:2475
Stack trace:
#0 /var/www/dev.jomlah.com/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(1582): Magento\Catalog\Model\ResourceModel\Product\Collection->addIsSaleableAttributeToFilter(1)
#1 /var/www/dev.jomlah.com/app/code/Sm/FilterProducts/Block/FilterProducts.php(436): Magento\Catalog\Model\ResourceModel\Product\Collection->addAttributeToFilter('is_saleable', 1, 'left')
#2 /var/www/dev.jomlah.com/app/code/Sm/FilterProducts/Block/FilterProducts.php(192): Sm\FilterProducts\Block\FilterProducts->_newProducts()
#3 /var/www/dev.jomlah.com/app/code/Sm/FilterProducts/Block/FilterPro in /var/www/dev.jomlah.com/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php on line 2475
102.46.38.208 - - [31/Dec/2019:19:20:22 +0300] "GET /arabic HTTP/2" 500 21 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"

**Comment by salehawal** [comment]
yea i guess it is back to the theme again .. oh my god ):

**Comment by ashishsaxena84** [comment]
@salehawal 
I got the same issue 
My magento version is 2.3.4 and also my theme is Sm/etrostore
Did you find the solution yet

**Comment by salehawal** [comment]
i think the solution is to never change and stick with what you have
