### ISSUE TITLE
Country dropdown populating wrong countries while adding Customer Address from Backend.

### ISSUE THREAD

**Issue by aloksparx** [magento/magento2#26171]
### Preconditions (*)
1. Magento Community version 2.3.3 installed with/without sample data
2. Allowed countries are selected from Store->Configuration->General->Country Options 

### Steps to reproduce (*)
1. Please Allow Random countries from  Store->Configuration->General->Country Options->Allowed Countries
2. Try to Add customer Address from Admin->All Customer->Edit any Customer -> Add New Address -> Select Country
3. The Select Country Dropdown will not populate the list of Allowed countries. 

### Expected result (*)
1. The Select Country Dropdown should populate the list of Allowed countries only 

### Actual result (*)
1. The Select Country Dropdown is populating the list of countries in ascending order. The Total count is correct but it's not checking the allowed countries.

![add-address](https://user-images.githubusercontent.com/2031565/71410402-227a0680-266b-11ea-8c06-9f99940829ba.PNG)
![allowed-countries](https://user-images.githubusercontent.com/2031565/71410403-23129d00-266b-11ea-985b-11c8751aa105.PNG)

**Comment by krishprakash** [comment]
Hi @aloksparx. Thank you for your report.
Issue is already open
You can review the conversation at #25218

**Comment by kinjal153mehta** [comment]
Hello All, i have resolve this issue with the following step for the if from store configuration we set multiple country as allowed country.

this is the steps :

ovverride the vendor/magento/module-customer/view/adminhtml/ui_component/customer_address_form.xml this file with the new source class with : Magento\Directory\Model\ResourceModel\Country\Collection => Magento\Directory\Model\Config\Source\Country

override the vendor/magento/module-directory/Helper/Data.php file with newly added const variable : const XML_PATH_DEFAULT_ALLOW = 'general/country/allow';

used that XML_PATH_DEFAULT_ALLOW variable in the following ovverride file :
Magento\Directory\Model\ResourceModel\Country\Collection.php
create new function :

/**
* Adds allowed country to options
*
* @param array $options
* @return void
*/
public function addAllowedCountryToOptions(array &$options)
{
$defaultCountry = [];
foreach ($this->storeManager->getWebsites() as $website) {
$defaultCountryConfig = $this->_scopeConfig->getValue(
\Magento\Directory\Helper\Data::XML_PATH_DEFAULT_ALLOW,
ScopeInterface::SCOPE_WEBSITES,
$website
);
$defaultCountry[$defaultCountryConfig][] = $website->getId();
}

    foreach ($options as $key => $option) {
        if (isset($defaultCountry[$option['value']])) {
            $options[$key]['is_default'] = !empty($defaultCountry[$option['value']]);
        }
    }
}
final step ovverride the : Magento\Directory\Model\Config\Source\Country.php file
add \Magento\Framework\App\Request\Http $request this in the construct
and add the following code in to the toOptionArray($isMultiselect = false, $foregroundCountries = '') function in that file

$moduleName = $this->_request->getModuleName();
$controller = $this->_request->getControllerName();
$action = $this->_request->getActionName();
$route = $this->_request->getRouteName();
if (!$this->_options) {
if($moduleName == 'admin' && $controller == 'system_config' && $action == 'edit'){
$this->_options = $this->_countryCollection->loadData()->setForegroundCountries(
$foregroundCountries
)->toOptionArray(
false
);
} else {
$this->_options = $this->_countryCollection->loadByStore()->toOptionArray();
}
}

this steps solve the issue for the multiple allowed country from system configuration but i am still try to set the code for the if only single country select then it gives blank.

if anybody find that solution then please let me know.
