### ISSUE TITLE
Address Book tab keep not selected after add or edit customer address

### ISSUE THREAD

**Issue by mageprince** [magento/magento2#26174]
### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Log in as customer with username and password
2. Open address book
3. Add new address or edit existing address
4. Save address  

### Expected result (*)

1. Address Book tab not highlighted

### Actual result (*)

1. Address Book tab keep highlighted
![Address Book](https://user-images.githubusercontent.com/24751863/71414865-f4062680-267e-11ea-990f-24b353ad14b8.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26174-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26174-2-4-develop.instances.magento-community.engineering/admin](https://i-26174-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@mageprince - I have verified this issue latest Magento 2.4 Instance and In this instance, it is working fine.
Now I have close the issue. @mageprince - If you have reproduce again this issue you can open it and add the video or screenshot or steps.
