### ISSUE TITLE
Issue with Downloadable product status at FE

### ISSUE THREAD

**Issue by KaustubhBorate** [magento/magento2#26179]
I am facing an issue with downloadable products, Magento showing at status 'pending' instead of 'Available'. The order is completed but still shows pending and downloadable product link is not displaying.
 This Issue on Magento 2.2.9.
I have upgrade the magento from 2.2.3 to 2.2.9 and then after this issue occur.

**Comment by krishprakash** [comment]
Hi @KaustubhBorate. Thank you for your report.
Issue is already fixed in latest magento
You can review the previously added issue at #23549
