### ISSUE TITLE
More than one redirect with trailing slash in secure non-www url

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26177]
### Preconditions (*)

1. Magento 2.3.3
2. SSL enabled

### Steps to reproduce (*)

1. In Firefox browser enter https://example.com/mens-wear
2. There is more than one redirect with trailing slash in secure non-www url when you inspect the network tab in firefox browser. As you can see from below a secure non-www url is forwarded to a url with trailing slash and then again forwarded to one with no slash. Please note that other redirects are fine. Issue is only with secure non-www url. Also note that I am using the default nginx conf file that comes with magento installation. I have noticed this on two production stores.

https://example.com/mens-wear
https://www.example.com/mens-wear/
https://www.example.com/mens-wear

### Expected result (*)

1. Only one redirect.

### Actual result (*)

1. More than one redirect.

**Comment by Zyles** [comment]
Check if this helps: https://github.com/magento/magento2/pull/25603

**Comment by monotheist** [comment]
@Zyles Thank you. I see solution but I am finding it hard to understand. Could you please help me by pointing exact changes that are required to be done? Much appreciated.

**Comment by Zyles** [comment]
https://github.com/magento/magento2/commit/fa468e7298b42c0a233bbcb7db932f8a8ccbb32f

https://github.com/magento/magento2/pull/25603/files

**Comment by monotheist** [comment]
@Zyles Thank you. I am still finding it hard. I believe there are 3 files. Below are the files with fixes. Can you please confirm?

https://raw.githubusercontent.com/magento/magento2/fa468e7298b42c0a233bbcb7db932f8a8ccbb32f/app/code/Magento/UrlRewrite/Controller/Router.php
https://raw.githubusercontent.com/magento/magento2/fa468e7298b42c0a233bbcb7db932f8a8ccbb32f/app/code/Magento/UrlRewrite/Test/Unit/Controller/RouterTest.php
https://raw.githubusercontent.com/magento/magento2/fa468e7298b42c0a233bbcb7db932f8a8ccbb32f/dev/tests/integration/testsuite/Magento/UrlRewrite/Controller/UrlRewriteTest.php

**Comment by monotheist** [comment]
Or these 5 files.

https://raw.githubusercontent.com/magento/magento2/b1a2a29671de32d90dbc10a3b0ced6a3d71b2b72/dev/tests/integration/testsuite/Magento/UrlRewrite/_files/url_rewrite_rollback.php
https://raw.githubusercontent.com/magento/magento2/b1a2a29671de32d90dbc10a3b0ced6a3d71b2b72/app/code/Magento/UrlRewrite/Test/Unit/Controller/RouterTest.php
https://raw.githubusercontent.com/magento/magento2/b1a2a29671de32d90dbc10a3b0ced6a3d71b2b72/dev/tests/integration/testsuite/Magento/UrlRewrite/Controller/UrlRewriteTest.php
https://raw.githubusercontent.com/magento/magento2/b1a2a29671de32d90dbc10a3b0ced6a3d71b2b72/dev/tests/integration/testsuite/Magento/UrlRewrite/_files/url_rewrite.php
https://raw.githubusercontent.com/magento/magento2/b1a2a29671de32d90dbc10a3b0ced6a3d71b2b72/app/code/Magento/UrlRewrite/Controller/Router.php

**Comment by Zyles** [comment]
You need to do the rollback in the first link and then apply the changes in the pull request.

You can skip the test files in test directories.

Add lines with + and remove -

**Comment by monotheist** [comment]
@Zyles is it not possible to just replace my current file with below file?
https://raw.githubusercontent.com/magento/magento2/b1a2a29671de32d90dbc10a3b0ced6a3d71b2b72/app/code/Magento/UrlRewrite/Controller/Router.php

**Comment by Zyles** [comment]
Could work. Just make a backup of the original file.

**Comment by monotheist** [comment]
@Zyles Thank you so much. Essentially I just need to focus on one file which is Router.php in both the links.

**Comment by monotheist** [comment]
@Zyles I tried replacing Router.php file from both the links. Cleared cache and restarted php-fpm. My issue still exists.

**Comment by Zyles** [comment]
What is your category suffix setting? And "Auto-redirect to Base URL"?

Is the redirect 302 or 301?

I was unaware that the default nginx conf worked with SSL at all, since it is not even configured to.

I suggest installing a fresh 2.3.3 installation and trying to reproduce it. If you can't it sounds like a nginx config issue.

**Comment by monotheist** [comment]
@Zyles Category suffix setting is empty. I don't have anything in there. I am seeing this issue on two live stores. Please see attached image. Fresh install is out of scope. I have separate config for SSL which includes the default magento nginx conf. Please see below.

```
server {
    listen      443 ssl http2;
    server_name example.com www.example.com;
    ssl_protocols       TLSv1.2  TLSv1.3;

    ssl_certificate      /usr/local/vesta/ssl/certificate.crt;
    ssl_certificate_key  /usr/local/vesta/ssl/certificate.key;

    access_log  /var/log/nginx/domains/example.com.log combined;
    access_log  /var/log/nginx/domains/example.com.bytes bytes;
    error_log   /var/log/nginx/domains/example.com.error.log error;

    location / {
        proxy_pass http://127.0.0.1:6081;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Ssl-Offloaded "1";
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen    8080;
    server_name example.com www.example.com;
    set $MAGE_ROOT /home/example/web/example.com/public_html/pub;
    set $MAGE_MODE production; # or production

    include	/home/example/web/example.com/public_html/nginx.conf.sample;
    include     /etc/nginx/conf.d/phpmyadmin.inc*;
    include     /etc/nginx/conf.d/phppgadmin.inc*;
    include     /etc/nginx/conf.d/webmail.inc*;
    include     /home/example/conf/web/snginx.example.com.conf*;
}

```

![Screenshot 2019-12-28 at 10 17 10 AM](https://user-images.githubusercontent.com/16968205/71539122-b85cac80-295d-11ea-80fb-f508306f080c.jpg)
![Screenshot 2019-12-28 at 10 27 21 AM](https://user-images.githubusercontent.com/16968205/71539123-bbf03380-295d-11ea-9541-0df2d4f51769.jpg)

**Comment by Zyles** [comment]
You need to verify the issue on a fresh 2.3.3 install to determine if it is a M2 or nginx configuration issue or one of your extensions.
