### ISSUE TITLE
Adding two bundles to the cart, with a similar simple item causes checkout to fail

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#26186]
### Preconditions
1. Magento 2.3.3
2. PHP 7.2.26
3. MariaDB 10.3.21

### Steps to reproduce
1. Create 3 Simple products, SKU A, SKU B and SKU C. Ensure they are all active and sell-able (ie have qty)
2. Create 2 Bundle products:
Bundle SKU 1 should have SKU A and SKU B
Bundle SKU 2 should have SKU B and SKU C
3. Add bundle SKU 1 to to the shopping cart
4. Add bundle SKU 2 to to the shopping cart

### Expected result
1. On the cart page you should see:
Bundle SKU 1 should have SKU A and SKU B
Bundle SKU 2 should have SKU B and SKU C
2. You should be able to click on the checkout button

### Actual result
1. on the cart page:
Bundle SKU 1 has SKU A and SKU B
Bundle SKU 2 has SKU C
2. When you click the checkout button, the following shows up in the php error log:
[26-Dec-2019 22:19:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getPosition() on null in /var/www/html/vendor/magento/module-bundle/Model/Product/Type.php:1004
Stack trace:
#0 [internal function]: Magento\Bundle\Model\Product\Type->shakeSelections(Object(Magento\Catalog\Model\Product\Interceptor), Object(Magento\Catalog\Model\Product\Interceptor))
#1 /var/www/html/vendor/magento/module-bundle/Model/Product/Type.php(731): usort(Array, Array)
#2 /var/www/html/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php(455): Magento\Bundle\Model\Product\Type->_prepareProduct(Object(Magento\Framework\DataObject), Object(Magento\Catalog\Model\Product\Interceptor), 'full')
#3 /var/www/html/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php(469): Magento\Catalog\Model\Product\Type\AbstractType->prepareForCartAdvanced(Object(Magento\Framework\DataObject), Object(Magento\Catalog\Model\Product\Interceptor), 'full')
#4 /var/www/html/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php(1045): Magento\Catalog\ in /var/www/html/vendor/magento/module-bundle/Model/Product/Type.php on line 1004

Additionally, when you remove Bundle SKU 1 from the shopping cart, an error now pops for Bundle SKU 2: 
Some of the products below do not have all the required options.

**Comment by justinharris1986** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26186-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26186-2-4-develop.instances.magento-community.engineering/admin](https://i-26186-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @justinharris1986. Not able to reproduce this issue as provided steps by you.
Please review once on latest magento instance by adding this comment _**(@magento give me 2.4-develop instance)**_ and let me know if you phase this or not.
And update the steps if you reproduce the issue.
Thanks.

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26186-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26186-2-4-develop.instances.magento-community.engineering/admin](https://i-26186-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
