### ISSUE TITLE
Product with 2 varaibles does not have pre-selected values

### ISSUE THREAD

**Issue by JustinFu45** [magento/magento2#26188]
There are products in our magento2 store, which have different 
- package sizes
- different strengths

We want to have already a pre-selected values for them so that customers do not have to select anything themselves (example in the picture) this is how it should be.

At the moment when a client goes to a product page, they only see the possible variables to choose from and have to select them manually.

Can anyone suggest what the solution would be for this issue?
![preselected values](https://user-images.githubusercontent.com/52731887/71506704-fe156880-28bc-11ea-92fe-3cedc152a73e.png)

**Comment by engcom-Echo** [comment]
Hi, @JustinFu45  Thank you for your report.
You can use the guide to create a configurable product on Magento - https://docs.magento.com/m2/ce/user_guide/catalog/product-create-configurable.html

**Comment by engcom-Echo** [comment]
Hi, @JustinFu45. Look like this issue https://github.com/magento/magento2/issues/18017

**Comment by engcom-Echo** [comment]
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
