### ISSUE TITLE
Not able to uninstall Yotpo_Yotpo

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26187]
I have malware on my 2.3.3 default installation called Yotpo_Yotpo and it is not possible to uninstall it.

### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Install Magento 2.3.3 using composer
2. 
```

$ composer remove yotpo/magento2-module-yotpo-reviews
yotpo/magento2-module-yotpo-reviews is not required in your composer.json and has not been removed

```
```
$ php bin/magento module:uninstall -r Yotpo_Yotpo  --clear-static-content

$ php bin/magento maintenance:enable &&
$ php bin/magento cache:clean &&
$ php bin/magento cache:flush &&
$ php bin/magento setup:upgrade &&
$ php bin/magento setup:di:compile &&
$ php bin/magento setup:static-content:deploy en_US -j 4 -f &&
$ php bin/magento indexer:reindex &&
$ php bin/magento maintenance:disable

$ grep Yotpo app/etc/config.php
'Yotpo_Yotpo' => 1
```

### Expected result (*)

Able to uninstall Yotpo_Yotpo

### Actual result (*)

Unable to uninstall Yotpo_Yotpo

**Comment by mrtuvn** [comment]
add replace attribute to your composer.json to remove unused core modules
https://www.integer-net.com/make-magento-2-small-again/

**Comment by dasharath-wagento** [comment]
I am working on this issue #mm20in

**Comment by dasharath-wagento** [comment]
@Zyles 
You can simply remove  the Yotpo module using composer.json by below way in replace object of JSON,

"replace": {
        "yotpo/magento2-module-yotpo-reviews": "*"
    },


You have to add above data in your Magento root composer.json file with replace the object.

Run command from Magento SSH,

composer update
Your  the Yotpo module will be removed from the core code after composer update.
Run php bin/magento setup:upgrade and php bin/magento cache:clean
