### ISSUE TITLE
Unable to uninstall Braintree

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26189]
Not able to uninstall malware Braintree module.

### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Install Magento 2.3.3 using composer
2. `$ php bin/magento module:uninstall -r Magento_Braintree Magento_BraintreeGraphQl --clear-static-content`
3.
```
Modify composer.json:

"replace": {
        "magento/module-braintree": "*"
    },
```
4.
```
$ php bin/magento maintenance:enable &&
$ php bin/magento cache:clean &&
$ php bin/magento cache:flush &&
$ php bin/magento setup:upgrade &&
$ php bin/magento setup:di:compile &&
$ php bin/magento setup:static-content:deploy en_US -j 4 -f &&
$ php bin/magento indexer:reindex &&
$ php bin/magento maintenance:disable

```

### Expected result (*)

Able to uninstall module.

### Actual result (*)

Unable to uninstall module.

Error:
`Class Magento\Braintree\Gateway\Config\Config does not exist`

**Comment by Zyles** [comment]
Checkout:

`Exception #0 (ReflectionException): Class BraintreeFacade does not exist`

Why the hell does checkout depend on Braintree? We don't use it, we don't need it.

**Comment by engcom-Echo** [comment]
Hi, @Zyles. Hello, could You please provide more details? 
After what actions does the error appear?

Try to use it

Modify composer.json:

> "replace": {
>         "magento/module-braintree": "*",
>         "magento/module-braintree-graph-ql": "*"
>     }
> 

Thanks for your collaboration!

**Comment by engcom-Echo** [comment]
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
