### ISSUE TITLE
Category form not load when many products assigned to category

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#26199]
This actually happen in my client site with many product counts in category
default category (root) have more 800K products
### Preconditions (*)

1. Magento 2.3.3 CE
2. Production mode
3. php 7.2.24
4. Flat Category + Catalog enabled

### Steps to reproduce (*)

1. Assign many product to one default category
2. Visit Category page manager in admin

### Expected result (*)

1. Form category load successfull

### Actual result (*)

1. Form not loaded and got warning
2. Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : CData section too big found in vendor/magento/framework/View/TemplateEngine/Xhtml/Template.php on line 60

**Comment by mrtuvn** [comment]
Found error seem same behavior with issue
https://github.com/magento/magento2/issues/7658

**Comment by ktpl-rammohan** [comment]
@mrtuvn Yes verified the issue and behavior is same as issue mentioned #7658 
And also it moved to Ready for Dev in community backlog, so you can track the fix on the same issue.
Marking as Duplicate and closing the issue.

**Comment by interequipment** [comment]
Having same issue on our Magento 2.3.3 store.

*Flat Category + Catalog enabled
*There are more than 7100 categories and 900,000 products.
