### ISSUE TITLE
google ads setting showing null after configuration data

### ISSUE THREAD

**Issue by Rawpro1** [magento/magento2#26198]
### Preconditions (*)

1. magento 2.3
2. google shopping ads

### Steps to reproduce (*)

1. configuration the google shopping ads  extinction 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or d
![magento](https://user-images.githubusercontent.com/59303403/71539826-323b6880-2953-11ea-9dba-29f2cc346a71.PNG)
escription]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by sdzhepa** [comment]
Hello @Rawpro1 

Unfortunately, based on your report we are not able to reproduce this issue by provided steps.
Please feel free to update description with details according to https://github.com/magento/magento2/wiki/Issue-reporting-guidelines and reopen the issue if it still actual
