### ISSUE TITLE
Image of category uploaded in catgory info page will be lost after 2nd reopening and saving.

### ISSUE THREAD

**Issue by gxuqin** [magento/magento2#26197]
### Preconditions (*)

1. An image of category is uploaded in Category editing page: admin/catalog/category/edit/id/4

### Steps to reproduce (*)

1. Reopen the category with image attached with the category
2. Just click the Save button with nothing to do.
3. See the Category Image field, the previous uploaded image is gone.

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/27143038/71529948-3f495080-289c-11ea-8238-5f18afcbc16b.png)

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/27143038/71529965-5be58880-289c-11ea-9773-86eee2e04f48.png)

**Comment by krishprakash** [comment]
Hi @gxuqin. 
Issue is duplicate to #25099
Issue will be fixed in next 2.3.4 release
You can review the feedback from above given issue link.
Thanks.
