### ISSUE TITLE
Invoices, credit memos do not show up in the grid after creation

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26196]
### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Create an order
2. Create an invoice
3. On the next screen click "Invoices", does the invoice show up? No it does not.
4. Refresh the page, invoice shows up
5. Create a credit memo
6. Click "Credit Memos", does the credit memo show up? Nope.
7. Refresh page, now it shows up
8. Now try it with shipments and guess what happens

### Expected result (*)

Invoices, credit memos etc. should show up on the next screen after creation.

### Actual result (*)

They don't show up.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26196-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26196-2-4-develop.instances.magento-community.engineering/admin](https://i-26196-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @Zyles. Thank you for your report.
Not able to reproduce the issue as per your given steps.
Refer below screencast for same
https://www.screencast.com/t/C5mXrVZ2
Feel free to reopen if you confirm that issue is reproduce on latest magento instance.

**Comment by Zyles** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Zyles, here is your [Magento instance](https://i-26196-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26196-2-3-3.instances.magento-community.engineering/admin](https://i-26196-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Zyles** [comment]
Looks like another random Magento 2 bug with bad release QA because of upgrading from 2.3.1 to 2.3.3
