### ISSUE TITLE
Media and static files being served both from pub and non pub folder

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26203]
### Preconditions (*)

1. Magento 2.3.3 & 2.4-develop
2. Nginx (reproduced only on Nginx)

### Steps to reproduce (*)

1. Load some img in `pub `folder( banner.jpg in this case)
2. Type example.com/pub/banner.jpg and example.com/banner.jpg

### Expected result (*)

1. example.com/banner.jpg should throw 404 error

### Actual result (*)

1.  I am able to access example.com/pub/banner.jpg and example.com/banner.jpg

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30408` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment]
Hello @monotheist.
I haven't able to reproduce the issue. In my case (nginx version: nginx/1.18.0), it is possible to access static files only from the pub folder but not from the root of the project.
Described behaviour depends on your Nginx configuration and it is not related to Magento.
Please check [documentation](https://devdocs.magento.com/guides/v2.4/install-gde/tutorials/change-docroot-to-pub.html) to find Magento recommendations about it.
Thank you.

**Comment by magento-engcom-team** [comment]
@m2-backlog[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
