### ISSUE TITLE
Sorting issue for status column for Cache Management

### ISSUE THREAD

**Issue by hasim32** [magento/magento2#26208]
Sorting issue for status column for Cache Management

### Preconditions (*)
Magento 2.3.3

### Steps to reproduce (*)
Admin -> System -> Tools -> Cache Management
Change the status of any type to disabled 
check the status sorting

### Expected result (*)
Sorting should working fine

### Actual result (*)
it remains same
![image](https://user-images.githubusercontent.com/56119534/71578753-71b6b000-2b1f-11ea-8173-ca97d55220de.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30129` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lbajsarowicz** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, here is your [Magento instance](https://i-26208-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26208-2-4-develop.instances.magento-community.engineering/admin](https://i-26208-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lbajsarowicz** [comment]
Confirmed.

**Comment by VladimirZaets** [comment]
Hi @hasim32. Thank you for your report. 
The issue has been fixed in magento/magento2#26215 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [e4e4b4e3849dc4a645b352b03ec1535d9733a681](https://github.com/magento/magento2/commit/e4e4b4e3849dc4a645b352b03ec1535d9733a681)

The fix will be available with the upcoming 2.4.0 release.
