### ISSUE TITLE
Missing method in webapi.xml results in fatal error on setup:upgrade

### ISSUE THREAD

**Issue by milindsingh** [magento/magento2#26202]
Magento: 2.3.3

### Summary (*)

1. Create a custom module with a `webapi.xml` and add a route URL. For Example:
```xml
 <route url="/V1/mymodule/myurl" method="GET">
        <service class="MyVendor\MyModule\Api\MyRepositoryInterface" method="getMyContent"/>
    </route>
```
2. Create a repository interface and class `MyVendor\MyModule\Api\MyRepositoryInterface` **but do not add the method** `getMyContent` in any.

3. Run `php bin/magento setup:di:compile` and results success.

4. Run  `php bin/magento setup:upgrade` and results fatal error as below.

```
Notice: Undefined index: create in /magento-root/vendor/magento/framework/Reflection/MethodsMap.php on line 83
```

### Examples (*)

same as above.

### Proposed solution

The below method does not check if the index is available or throws any exception to debug.

https://github.com/magento/magento2/blob/6159dc859b8e5ed4b1baa7348befaca5b3f15335/lib/internal/Magento/Framework/Reflection/MethodsMap.php#L79-L82

I would suggest throwing an **Exception** with the interface name and function that is missing. which will really help in debugging the error.

**Comment by marcoaacoliveira** [comment]
Hi @milindsingh thanks for your issue, I'll check it. Are you using production mode, aren't you?

**Comment by milindsingh** [comment]
Thanks @marcoaacoliveira 
I am on developer mode still, I think the same will happen on production mode too.

**Comment by marcoaacoliveira** [comment]
@milindsingh I couldn't reproduced it neither on Magento 2.3.2 nor 2.4 (in setup:upgrade step, I don't have a clean instance of Magento 2.3.3 right now so I didn't try on it), but when I tried to access swagger I got strange errors (that doesn't mean anything). I think it would be a good improvement throws exceptions in this case.

**Comment by milindsingh** [comment]
Thanks @marcoaacoliveira I have tried in 2.4-develop but unable to reproduce. So closing it for now.
