### ISSUE TITLE
Escaping in Search Recommendations

### ISSUE THREAD

**Issue by Etje** [magento/magento2#26205]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Type "%27><qss%20a%3DX168794596Y1Z%20> as search query
2. The search recommendations are just raw query text. So, when you use the above mentioned search query, the output will be `"'>` 

### Expected result (*)

1. Search Recommendations should be escaped

### Actual result (*)

1. if the above mentioned search query is used, output will be 
`"'>` 
`"'>` 
`"'>` 
`"'>` 
`"'>` 

**Notice:** Result with string `<h1>"my tag"`
![#26205issue](https://user-images.githubusercontent.com/51681379/72258857-c6762280-3617-11ea-8c98-0503267b5776.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30379` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by deepaksnair** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @deepaksnair. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @deepaksnair, here is your [Magento instance](https://i-26205-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26205-2-4-develop.instances.magento-community.engineering/admin_3c13](https://i-26205-2-4-develop.instances.magento-community.engineering/admin_3c13)
Login: `d5aa8082` Password: `7b1bd3c9201d`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
