### ISSUE TITLE
Integrity constraint violation for guest users and non-existing quotes, causes guest users not being able to use the cart anymore.

### ISSUE THREAD

**Issue by TimQSO** [magento/magento2#26201]
When a guest visitor with an existing session and shopping cart returns to the shop while in the mean time his quote has been cleared (or removed), the guest user is not able to add items to his shopping cart until he removes his cookies. An error is logged in exception.log for a 'Integrity constraint violation'

### Preconditions (*)

- Magento 2.3.3 CE
- Production mode
- php 7.1 / 7.2 / 7.3

### Steps to reproduce (*)

1. Visit the shop as guest user.
2. Add one of more items to the shopping cart
3. Remove all quotes from the table 'quote'
4. Refresh go back to the shop and try to add something to your cart.
 

### Expected result (*)
The cart of the guest is empty because of the removal of the quotes in the quote table, but the guest user is able to (re)add products to his cart.
 
### Actual result (*)
The guest user is not able to use the shop anymore, because the cart is not working. The guest user is not able to add items to his cart and in the backend errors are logged. This situation can only be solved by clearing the cookies of the guest visitor.

`main.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails .`quote_id_mask`, CONSTRAINT `QUOTE_ID_MASK_QUOTE_ID_QUOTE_ENTITY_ID` FOREIGN KEY (`quote_id`) REFERENCES `quote` (`entity_id`) ON DELETE CASCADE),  query was: INSERT INTO `quote_id_mask` (`quote_id`, `masked_id`) VALUES (?, ?) {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails`

Note: if you test the above with a registered / logged in user, it works like expected. The above issue is only valid for guest users.

**Comment by TimQSO** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GuiltyNL. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GuiltyNL, here is your [Magento instance](https://i-26201-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26201-2-4-develop.instances.magento-community.engineering/admin](https://i-26201-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TimQSO** [comment]
To reproduce on that instance, I need to be able to empty the quote table. @magento-engcom-team

**Comment by marcoaacoliveira** [comment]
@GuiltyNL thanks for reporting the problem.

I tried to reproduce this bug in my instance with Magento 2.4 and I wasn't able to. 

Are you sure there is no other third party component causing this problem?

**Comment by TimQSO** [comment]
I will look at this. I wanted to try this on an instance here, but I'm not able to empty tables ;)

**Comment by TimQSO** [comment]
Dug into this and you are correct @marcoaacoliveira . Sorry for this. It was caused by a rewrite of @stephan-cream . Now removed and problem solved.

**Comment by shrma-smit** [comment]
Hi @GuiltyNL,

I'm facing same problem. Can you please share the rewrite code for my reference so I can debug it further.

Thanks in advance!

**Comment by GuiltyNL** [comment]
@stephan-cream made a rewrite to solve the issue of a flooding exception.log with this error:

`No such entity with customerId = 82343 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0)`

However the fix did remove the error messages in the log, but it caused the issues described in this ticket.

Removing the fix solved this ticket, but brought back the errors in the exception log. (And this is solved in 2.3.4 or 2.3.5)

**Comment by shrma-smit** [comment]
> @stephan-cream made a rewrite to solve the issue of a flooding exception.log with this error:
> 
> `No such entity with customerId = 82343 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0)`
> 
> However the fix did remove the error messages in the log, but it caused the issues described in this ticket.
> 
> Removing the fix solved this ticket, but brought back the errors in the exception log. (And this is solved in 2.3.4 or 2.3.5)

Thank you for explaining @GuiltyNL.

I've not applied this fix yet but facing this issue after removing customer quotes from the website and it come randomly for the customers not every customer which is strange.
