### ISSUE TITLE
Reviews will not load after clicking "Reviews"

### ISSUE THREAD

**Issue by adamstephenswod** [magento/magento2#26219]
When clicking to see and read reviews, the screen scrolls to the review section but will NOT display the reviews. It will only show the text box to write a review.
![image](https://user-images.githubusercontent.com/59397464/71628885-15579d00-2bc0-11ea-9279-a322602b2de5.png)

![image](https://user-images.githubusercontent.com/59397464/71628903-243e4f80-2bc0-11ea-871f-33f3ebcbb27c.png)

When pressing inspect and looking at console, I see that there is an error.

![image](https://user-images.githubusercontent.com/59397464/71628862-eb05df80-2bbf-11ea-8639-3b2670656a4a.png)

We cannot solve this issue and it is hiding all reviews of our website.

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26219-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26219-2-4-develop.instances.magento-community.engineering/admin](https://i-26219-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
Hi @adamstephenswod. Thank you for your report.
Not able to reproduce the issue as per description
Please refer below screencast:
https://www.screencast.com/t/oyeV7pSo7
