### ISSUE TITLE
How do get customer isLogin in product view?

### ISSUE THREAD

**Issue by xanka** [magento/magento2#2621]
I tried with customerSession it not success. So how do get customer isLogin in product view.

**Comment by dmitrii-fediuk** [comment]
https://mage2.pro/t/120

**Comment by xanka** [comment]
that is check. I want get object customer ex: getName(), GetEmail()... @magento-team , @dfediuk

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
