### ISSUE TITLE
Product image failure when importing through CSV

### ISSUE THREAD

**Issue by flytomek** [magento/magento2#26212]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18)
3. Debian GNU/Linux 10.2

### Steps to reproduce (*)

1. Create CSV file
```
sku,store_view_code,attribute_set_code,product_type,categories,product_websites,name,description,weight,product_online,tax_class_name,visibility,price,url_key,base_image
60035068000,,Default,simple,"Default Category/KTM recambios originales",base,"ANGLE CONNECTION EXPANS. TANK", "<p><strong>ANGLE CONNECTION EXPANS. TANK</strong><br><br>Número OEM: 60035068000</p>",1,1,Taxable Goods,"Catalog, Search",1.84,60035068000,https://sparepartsfinder.ktm.com/SPF/Images/maps/187210310.png
```
2. Go to System > Import, select Add/update product and upload file

### Expected result (*)
1. Import simple product with image

### Actual result (*)

1. When importing: Following Error(s) has been occurred during importing process: 1. Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 1
2. Poduct is imported but it has no image in Magento **(image has been successfully uploaded to var/tmp/ folder)**

It is the same issue I had 1 year ago with Magento 2.3.0. It has been patched [here](https://github.com/magento/magento2/commit/7f4dffdbd5b58a39ae043a9b47a5c75e19f6a552), but it looks like Magento 2.3.3 has exactly the same issue.

I have checked `exception.log` and this is what I have:

> [2019-12-30 14:19:28] main.CRITICAL: File 'var/tmp/187210310_8ph3N8PMRFkhHnuN.png' was not found or has read restriction. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): File 'var/tmp/187210310_8ph3N8PMRFkhHnuN.png' was not found or has read restriction. at /var/www/domain.com/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:261)"} []

**Comment by augrinovska** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @augrinovska. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @augrinovska, here is your [Magento instance](https://i-26212-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26212-2-4-develop.instances.magento-community.engineering/admin](https://i-26212-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by augrinovska** [comment]
Hi @magento-engcom-team, @flytomek 

**These steps were taken**:
1. Created CSV file
2. Go to System > Import, select Add/update product and upload file

**Actual Result:** 
The product was successfully imported with an image with a label Base. See image below.
![screencapture-i-26212-2-4-develop-instances-magento-community-engineering-admin-catalog-product-edit-id-1-2020-01-02-15_16_42](https://user-images.githubusercontent.com/43642490/71671192-ab332980-2d72-11ea-9ef5-ba8cddf6969e.png)

I couldn't reproduce the issue.

**Comment by flytomek** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @flytomek. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by flytomek** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @flytomek. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @flytomek, here is your [Magento instance](https://i-26212-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26212-2-3-3.instances.magento-community.engineering/admin](https://i-26212-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by flytomek** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @flytomek. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @flytomek, here is your [Magento instance](https://i-26212-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26212-2-4-develop.instances.magento-community.engineering/admin](https://i-26212-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by flytomek** [comment]
Looks like it's patched on 2.4-develop, but on 2.3.3 is not working on vanilla 2.3.3 installation.

**Comment by vikasebizon** [comment]
Hello, 
Is anyone found solution ? I am also having same issue.

**Comment by rightmarc** [comment]
Hello,
I also not import products from the CSV file.

When importing: Following Error(s) has been occurred during importing process: 1. Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 1

**Comment by flytomek** [comment]
Workaround can be:
- download all the images to _<img_folder>_ i.e. via external script
- upload images via FTP to _<magento_folder>/var/import/images/<img_folder>_
- generate CSV, but instead of URL to image, put image filename
- import csv (remember to set _Images File Director_y to _/<img_folder>_)

**Comment by rightmarc** [comment]
Hi @flytomek 
I followed your step then also give the same result.

- In CSV file image name as  APL-103-IP6-1.jpg

- image file directory /var/www/html/var/import/images

Get bellow Result

Created: 1, Updated: 0, Deleted: 0
Following Error(s) has been occurred during importing process:
Only the first 100 errors are shown. Download full report
1. Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 1
Import successfully done

**Comment by flytomek** [comment]
@rightmarc have you set proper _Images File Directory_ durning import (with leading slash)? Check under <magento_dir>/var/log/exception.log what kind of error this is.

**Comment by rightmarc** [comment]
Hi @flytomek after changing folders ownership and adding leading slash in image name product imported successfully.

But there is one more issue, image is not visible in product page.
Check below category page screenshot in this fist time image is not visible but when I click on it and load product page it will appear from next time.

![iphone 6](https://user-images.githubusercontent.com/57860784/71964060-e5914080-3222-11ea-9b78-0f6deb819da9.png)

Image is not visible in product page as bellow.
![iphone 6 page](https://user-images.githubusercontent.com/57860784/71964361-6ea87780-3223-11ea-9fce-eae74c9a033f.png)

**Comment by flytomek** [comment]
Maybe you put this image in column `thumbnail_image`? Try to import it as `base_image`

**Comment by rightmarc** [comment]
Image is already placed in base_image
please check the attached file.
[product import.zip](https://github.com/magento/magento2/files/4034578/product.import.zip)

**Comment by Becky1992j** [comment]
the same issue is coming on Magento ver. 2.3.6-p1 as explained by @rightmarc
why this issue is closed?
