### ISSUE TITLE
elasticsearch 7

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26220]
Does Magento work with elasticserach 7?

### Description (*)
add support for elasticsearch 7

### Additional information
some servers only have elasticsearch 7 available

**Comment by engcom-Charlie** [comment]
Hello @broros @sdzhepa
This issue looks like a feature request.
@sdzhepa could you transfer this issue to the Feature requests repository?
Thanks for your collaboration!

**Comment by sivaschenko** [comment]
Magento does support Elasticsearch 7 now https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html

**Comment by bfontaine** [comment]
> Magento does support Elasticsearch 7 now https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html

Am I reading your link incorrectly? It says it supports ElasticSearch 7 _only_:

> You must install and configure Elasticsearch 7.6.x before upgrading to Magento 2.4.x. […] Magento does not support Elasticsearch 2.x, 5.x, and 6.x.
