### ISSUE TITLE
qty_shipped and qty_canceled always at 0 for order item child

### ISSUE THREAD

**Issue by hatimeria-artur-jewula** [magento/magento2#26228]
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Place an order with configurable product
2. Create invoice for the order
3. Create shipment for the order

### Expected result (*)
1. qty_shipped set on the child level to be the same as on the parent item level

### Actual result (*)
1. qty_shipped on child level is always 0

The same issue is for cancelling an item. qty_caneled is only set correctly on parent item level and always 0 on child item level

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26228-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26228-2-4-develop.instances.magento-community.engineering/admin](https://i-26228-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hatimeria-artur-jewula** [comment]
@ajijshekh123 remember that this issue is not visible in admin panel as order item information there are taken from parent item (configurable) level. To see the problem you need to have access to the database.

**Comment by ajijshekh123** [comment]
@hatimeria-artur-jewula - This is not feasible for me to review the Default Magento database. 
If possible so Let me review this in My system default Magento database and update it.

**Comment by ajijshekh123** [comment]
@sdzhepa - Can you please verify this issue? I can't able to review the DB for the Default Magento 2.4 Instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30520` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
