### ISSUE TITLE
Checkbox alignment issue on Customer Account Create

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#26226]
### Summary

Checkbox alignment issue on Customer Account Create

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Go to Customer Account Create Page

### Expected result

1. Checkbox should be aligned.
![expected](https://user-images.githubusercontent.com/23443991/71652629-dc006800-2d4c-11ea-9282-3ae2b49f8a64.png)

### Actual result

1. Checkbox little bit up.
![actual](https://user-images.githubusercontent.com/23443991/71652628-db67d180-2d4c-11ea-9b89-bc2699fe1992.png)

**Comment by milindsingh** [comment]
Hi @hitesh-wagento What is the real difference in the two images you added?

**Comment by hitesh-wagento** [comment]
I am working on this issue

**Comment by hitesh-wagento** [comment]
@milindsingh Please see checkbox and label alignment

**Comment by dmytro-ch** [comment]
Hello, @hitesh-wagento, this is a pretty common and minor issue, which depends on many factors such as browser, OS, etc. No need to report and apply the fixes for each form separately.
It should be fixed globally if it even needs to be fixed...
Thank you!
