### ISSUE TITLE
Cart Price rules - Cannot enable "Apply to shipping amount" when you Apply "Fixed amount discount for whole cart"

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#26221]
### Preconditions
1. Magento 2.3.3
2. PHP 7.2.26
3. MariaDB 10.3.21

### Steps to reproduce
1. go to Marketing -> Cart Price Rules
2. Add a new rule
3. Open up actions section
4. Ensure "Apply" Is set to "Fixed amount discount for whole cart"

### Expected result
1. Apply to Shipping Amount is grayed out and cannot be set to Yes

### Actual result
1. You should be able to add your discount to the shipping (IE this option is enabled, and can be set to yes)
2. You could toggle this setting, and it worked properly in 2.2.8. It broke sometime in the 2.3.x branch

**Comment by justinharris1986** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986, here is your [Magento instance](https://i-26221-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26221-2-4-develop.instances.magento-community.engineering/admin](https://i-26221-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by justinharris1986** [comment]
I cannot recreate this in 2.4-develop, HOWEVER, I can create this in a vanilla 2.3.3 instance.

**Comment by justinharris1986** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986, here is your [Magento instance](https://i-26221-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26221-2-4-develop.instances.magento-community.engineering/admin](https://i-26221-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by justinharris1986** [comment]
yes I can recreate this in 2.4-develop:
![image](https://user-images.githubusercontent.com/7268384/71676963-811c4000-2d4f-11ea-9f36-f936793a8d05.png)

I CAN Confirm that this issue was NOT present in 2.2.8:
![image](https://user-images.githubusercontent.com/7268384/71677075-d3f5f780-2d4f-11ea-8462-4ec79623e8c7.png)

**Comment by justinharris1986** [comment]
I can confirm that this does not exist in 2.3.0:
![image](https://user-images.githubusercontent.com/7268384/71677676-706cc980-2d51-11ea-9092-df52c3bd15ea.png)
I dont have any other versions in my dev environment to test on

**Comment by justinharris1986** [comment]
I can confirm that this does not exist in 2.3.1:
![image](https://user-images.githubusercontent.com/7268384/71679518-bd529f00-2d55-11ea-8e5e-d225c35ad91d.png)

**Comment by justinharris1986** [comment]
I can confirm this issue appears in 2.3.2:
![image](https://user-images.githubusercontent.com/7268384/71682908-0f4bf280-2d5f-11ea-9b83-5a3c4acd46d4.png)


so the issue appeared between the releases of 2.3.1 and 2.3.2

**Comment by justinharris1986** [comment]
Appears to be because of commit https://github.com/magento/magento2/commit/1b6d64c316251604228c32667235b1df9467e0b8

I rolled back this XML File and it fixed the issue:
https://github.com/magento/magento2/commit/1b6d64c316251604228c32667235b1df9467e0b8#diff-0728831e0892a2382dc5fa797976f1d8

**Comment by justinharris1986** [comment]
Closing this as it is a duplicate of #24422
