### ISSUE TITLE
MAGE_MODE is changed back to default if database config is changed with setup:config:set

### ISSUE THREAD

**Issue by moleman** [magento/magento2#2623]
I'm not sure if this behaviour is intentional or not, but in our build / deploy pipeline we sometimes change the database configuration settings of a site depending on different environments. When we are building our production artifacts we are setting the MAGE_MODE to production with "deploy:mode:set production" because we only want to do it once (takes some time) and we don't want to do it during the deployment.

The problem comes when we want to change database configuration with "setup:config:set ...". After we do this, MAGE_MODE is changed back to 'default' which we didn't intend to do. Is this intentional? 
### Steps

$ php bin/magento deploy:mode:set production
…
Enabled production mode.

$ php bin/magento deploy:mode:show
Current application mode: production.

$ php bin/magento setup:config:set <another database settings>

$ php bin/magento deploy:mode:show
Current application mode: default.

**Comment by mazhalai** [comment]
@moleman thank you for reporting, we have created MAGETWO-46533 to investigate and fix this issue.

**Comment by mazhalai** [comment]
@moleman this is been fixed in the `develop` branch. Please have a look and reopen a new issue if it still persists.
