### ISSUE TITLE
No field name displayed while Company creation

### ISSUE THREAD

**Issue by IvanSemerenko** [magento/magento2#26239]
### Preconditions (*)

1.Magento version 2.3.3

### Steps to reproduce (*)

1.Go to Admin > Customers > Companies
2.Click Add New Company
3.Expand Legal Address section

### Expected result (*)

1. labels for all fields should be displayed
2.

### Actual result (*)

1. No label for the first field displayed

![screenshot](https://user-images.githubusercontent.com/19283694/71669630-fac72480-2d75-11ea-8c94-f8cd56041513.png)

**Comment by dmytro-ch** [comment]
Hi @IvanSemerenko,
the Companies feature is not a part of Magento Open Source.

Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Or feel free to report the issue in the scope of the fork of Magento 2 B2B repository (partners only).
[magento/magento2](https://github.com/magento/magento2/) repository is intended for Magento Open Source bug reports.

Thank you!
