### ISSUE TITLE
Braintree Creditmemo Issue with multi website

### ISSUE THREAD

**Issue by vertikacore** [magento/magento2#26232]
Preconditions
Magento 2.1.8

Steps to reproduce
Create two websites	
Set two different Braintree account credentials for different websites	
Place order with Braintree payment method in website that is not default	
Go to order in admin panel	
Select "Invoices" tab	
Go to "Credit Memo"	
Press "Refund"

Expected result
Successful message is displayed and refund is processed in Braintree

Actual result
Error is appears

Investigation showed for me that credentials for default store is initializes while performing refund request to Braintree. But order and invoice actually relates to not default (another) website.

**Comment by engcom-Charlie** [comment]
Hi @vertikacore thank you for your report but we are not able to reproduce this issue on a fresh 2.4-develop instance and 2.3.3
Manual testing scenario:
1. Create two websites
2. Set two different Braintree account credentials for different websites
3. Place an order with Braintree payment method in a website that is not default
4. Go to order in the admin panel
5. Make invoice for an order
6. Select the "Invoices" tab
7. Go to "Credit Memo"
8. Press "Refund"
AR: Successful message is displayed and refund is processed in Braintree

Could you take a look?
