### ISSUE TITLE
Advance reporting redirecting on 404

### ISSUE THREAD

**Issue by waqasali5006-dev** [magento/magento2#26242]
As per below advance reporting documentation
https://docs.magento.com/m2/ce/user_guide/reports/advanced-reporting.html

I followed each and every step and got success message and wait till night 2am as per the requirement cycle time but still getting 404 when clicking on advance reporting button, google analytics and integration are configured, advance reporting status is active not even pending but still not working.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26242-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26242-2-4-develop.instances.magento-community.engineering/admin](https://i-26242-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
Hi @waqasali5006-dev, thank you for your report.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
