### ISSUE TITLE
Frontend App is missing

### ISSUE THREAD

**Issue by johnbendi** [magento/magento2#2624]
I can't see the FrontendApp subsystem in my Magento2 installation.

**Comment by davidalger** [comment]
@johnbendi Please provide detail around what you are reporting as a bug?

**Comment by johnbendi** [comment]
I just learnt somewhere that `FrontendApp` and `Widget` tool under the `Content`  menu are synonymous right?
![content_menu_screenshot](https://cloud.githubusercontent.com/assets/1025834/11633282/c2b32a76-9d0a-11e5-884f-ded2477e34a3.png)

**Comment by davidalger** [comment]
@johnbendi Yes, at one point widgets were re-named to apps mid-development, but this was reverted to the term "widget" as it was in Magento 1 and earlier builds of Magento 2. Please take further technical questions to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) as the GitHub tracker is intended only for reporting bugs with the software. Thanks.
