### ISSUE TITLE
Website / Store scope for associated products of config products

### ISSUE THREAD

**Issue by WinstonN** [magento/magento2#26243]
### Description (*)
When you have a multi store setup, it would be beneficial to be able to set associated products of a configurable product per website / store 
Currently this cannot be done

### Expected behavior (*)
1. Within the Magento Admin navigate to a configurable product
2. Drop down to the correct website / store scope
3. Navigate to Configurations, and set associated products of config
4. Save product
5. Drop down to another website / scope
6. Navigate to Configurations, and set associated products of config
7. Save product

On the front end, Navigate to a store and find the config product. See it's associated products as set for that store.
Navigate to another store, and find the same config product. See a different set of associated products as set for that store

### Benefits
The benefits here would be a great deal of flexibility. Currently to achieve the same, you would have to assign all the simple products to the config, and manage this via simple product status in website / store scope

### Additional information
Can anyone tell me why this was not implemented? Perhaps I am missing some complexity, if so please give me more information

**Comment by WinstonN** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @WinstonN. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @WinstonN, here is your [Magento instance](https://i-26243-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26243-2-4-develop.instances.magento-community.engineering/admin](https://i-26243-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by WinstonN** [comment]
@magento-engcom-team  Issue can be reproduced on 2.4 develop

**Comment by engcom-Charlie** [comment]
Hello @WinstonN @sdzhepa 
This issue looks like a feature request.
@sdzhepa could you transfer this issue to the Feature requests repository?
Thanks for your collaboration!
