### ISSUE TITLE
Custom role with permissions not allowed to upload category image via custom attribute, 403 error

### ISSUE THREAD

**Issue by SGSJazzSingh** [magento/magento2#26253]
### Preconditions (*)
1. Magento 2.3.3
2. PHP 7.2.24
3. MariaDB 10.1.41

### Steps to reproduce (*)
1. Add an image attribute to the category via install script, I used the https://github.com/studioraz/magento2-category-image module to install the attribute.
2. Try to upload an image via the new attribute as admin, this should work as intended and save the image.
3. Create a new account and new user role; the user role has EVERY permission ticked but isn't set as an admin user.
4.) Log into this new account and try to upload an image via the attribute, you'll get a 403 error in the console and when you go to the link, it shows the following:

![image](https://user-images.githubusercontent.com/50570152/71725829-29ec9d00-2e2d-11ea-943b-f274100726dc.png)

### Expected result (*)
1. The new user with a user role which has every permission selected to be able to upload an image.

### Actual result (*)
1. The new user is unable to upload an image.

**Comment by sudheers-kensium** [comment]
@SGSJazzSingh This is not an issue. You need to  select the **Resource Access** to **All** for new user role and try. I am closing this issue.

![image](https://user-images.githubusercontent.com/50358141/71809485-33c50900-3096-11ea-8ebb-6843a1d446ce.png)

**Comment by SGSJazzSingh** [comment]
@sudheers-kensium When you set the **Resource Access** to **All**', you're setting the user role to use admin permissions. This **isn't** what I want - I need an account with limited permissions but still be able to upload images via custom category attributes.

I don't want 15 admin accounts that have access to everything under the sun, I need 15 accounts that can only edit categories and add images.

**Comment by sudheers-kensium** [comment]
@SGSJazzSingh Set Resource Access to Custom and select Catalog Categories. Feel free to reopen if  issue still exists.

**Comment by SGSJazzSingh** [comment]
@sudheers-kensium I have done this as I mentioned in my first post. I've even selected **everything** but when I try to upload an image with the custom category attribute, it gives me the error. 

From what I can see, setting the **Resource Access** to **All** grants the user with additional permissions than when you set **Resource Access** to **Custom** and select everything.

**Comment by sudheers-kensium** [comment]
@SGSJazzSingh You are using custom module, So Create ACL rule and assign that to new user role. This is not an Magento core issue.

**Comment by Asitis** [comment]
@SGSJazzSingh did you ever manage to tackle this issue? I'm facing the exact same, added ACL rules but that still doesn't work.
