### ISSUE TITLE
Input checkbox alignment issue at new rating creation in admin panel

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#26250]
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Go to Admin -> Stores -> Attributes -> Rating
2. Click on Add New Rating
3. In Rating Visibility, input checkbox not aligned properly with respective to label.

### Expected result (*)

1. In Rating Visibility, input checkbox should aligned properly.
2. 
![rating-box-expected](https://user-images.githubusercontent.com/54176640/71724669-17875900-2e57-11ea-95e5-8c03eedbb1ae.png)

### Actual result (*)

1. In Rating Visibility, input checkbox not aligned properly.
2.
![rating-box-actuval](https://user-images.githubusercontent.com/54176640/71724676-1e15d080-2e57-11ea-985d-264ca179cbef.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26250-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26250-2-4-develop.instances.magento-community.engineering/admin](https://i-26250-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30198` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
Hello @divyajyothi5321 , this is a pretty common and minor issue, which depends on many factors such as browser, OS, etc. No need to report and apply the fixes for each form separately.
It should be fixed globally if it even needs to be fixed...
Thank you!

**Comment by ajijshekh123** [comment]
Thanks for the Update @dmytro-ch
