### ISSUE TITLE
Zip archive contains full directory path of file

### ISSUE THREAD

**Issue by chaikivskyi** [magento/magento2#26262]
### Preconditions (*)
Magento  2.3.3

### Steps to reproduce (*)
When use class `\Magento\Framework\Archive\Zip` for creating zip archive, archive will contain full directory path to file. Example,

    $objectManager = \Magento\Framework\ObjectManager\ObjectManager::getInstance();
    $zip = $objectManager->create(\Magento\Framework\Archive\Zip::class);
    $file = '{{ABSOLUTE PATH TO FILE}}';
    $archive = '{{ABSOLUTE PATH TO ARCHIVE FOR CREATION}}';
    $zip->pack($file, $archive);

https://i.imgur.com/7jNorP1.png

### Expected result (*)
Root of archive will contain files 

### Actual result (*)

Root of archive contain directory structure where file was on server.

To fix this issue need refactor function

    public function pack($source, $destination)
    {
        $zip = new \ZipArchive();
        $zip->open($destination, \ZipArchive::CREATE);
        $zip->addFile($source);
        $zip->close();
        return $destination;
    }
to
   

    public function pack($source, $destination)
    {
        $zip = new \ZipArchive();
        $zip->open($destination, \ZipArchive::CREATE);
        $zip->addFile($source, basename($source));
        $zip->close();
        return $destination;
    }

in file https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Archive/Zip.php

**Comment by chaikivskyi** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @chaikivskyi. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @chaikivskyi, here is your [Magento instance](https://i-26262-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26262-2-4-develop.instances.magento-community.engineering/admin](https://i-26262-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by chaikivskyi** [comment]
Yes, it is still relevant.
