### ISSUE TITLE
Create Configuration Makes Duplicate Images

### ISSUE THREAD

**Issue by naps1saps** [magento/magento2#26267]
### Preconditions (*)

1. 2.3.3
2. 

### Steps to reproduce (*)

1. Create product
2. Create configurations
3. Assign images based on attribute

### Expected result (*)

1. Because we know each configured product will use the same color image per that attribute, it should be linked instead of duplicating for each product.

### Actual result (*)

1. Images will be imported per that attribute x (times) number of other attributes.
Example: 11 color images total 4MB.  After import for 88 configuration options 11 color images take up 200MB

This is absolute insanity to manage for backups, etc.  100 products with 500MB worth of images would take up 20GB.  If I add 3 images per color it would balloon to 60GB

**Comment by AnnaShepa** [comment]
Hello @naps1saps, thank you for the report. Sorry, but I cannot reproduce it on vanilla instance, please try it yourself and probably add some details to the description. I tried a few times in different ways, but always every generated simple product has only own image. Check that you selected "Apply unique images by attribute to each SKU" option.

**Comment by naps1saps** [comment]
When making a configurable product, the simple products it creates saves a duplicate photo example photo.png gets added photo_1.png, photo_2.png for each simple product of that photo attribute (each size of white color product).  This is a waste of space.  All products of that attribute should use the same photo unless you change it manually later.  This should be a simple change to the code so that when product 2, 3, 4 with that attribute are created, it uses the same photo path as product 1 (all product sizes of white color for example point to the same photo)
