### ISSUE TITLE
Multi currency symbols not reflecting in admin catalog

### ISSUE THREAD

**Issue by bharanikonda** [magento/magento2#26278]
### Preconditions
1. Configure multi-websites in Magento 2.3.3
2. Configure multi-currencies (Dollars for one website and Euro for another website)

### Steps to reproduce

1. Open admin catalog gird and edit any product which is assigned for two websites.
2. Change the store view to Euro website 
3. Price field still displaying with the dollar ($) currency

### Expected result

1. The price field should be displayed with the euro currency.

### Actual result

1. Price field still displaying with the dollar ($) currency
![image](https://user-images.githubusercontent.com/46315257/71812289-d4b6c280-309c-11ea-9850-95ef69f18d8a.png)

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-26278-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26278-2-4-develop.instances.magento-community.engineering/admin](https://i-26278-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@bharanikonda Price is global field and base currency symbol will display in Admin product edit. Currency will not change based on the Website/ Store view. 

So I am closing this issue.

**Comment by maderlock** [comment]
> Price is global field and base currency symbol will display in Admin product edit. Currency will not change based on the Website/ Store view.

This is wrong on all counts!
Price is not global - it can be specified per website.
So base currency can differ between websites and therefore currency should change per website, if not store.

> So I am closing this issue.

So you should not have done.

**Comment by maderlock** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maderlock. Thank you for your request. I'm working on Magento 2.3-develop instance for you
