### ISSUE TITLE
Cannot place order after migration from 1.9.4.1 to 2.3.3

### ISSUE THREAD

**Issue by codedge** [magento/magento2#26271]
When placing an order after running a migration from Magento 1.9.4.1 to Magento 2.3.3 I get the error message `Uncaught Error: Call to a member function getAdditionalInformation()` in `/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php:185`. 
The migration process ran without any problems. All orders and customers where migrated successfully.

The problem exists with online (Paypal) and offline (Cash on delivery) payment methods.

The issues is on this line `$paymentAdditionalInformation = $order->getPayment()->getAdditionalInformation();` wheere `$order->getPayment()` is null. 

### Preconditions (*)

1. After migration from Magento 1.9.4.1 to Magento 2.3.3
2. Migrated only order and customers using [these configs](https://gist.github.com/codedge/9937b20440eb93b5a7c789f6a8ab3c3d) (config.xml + map.xml)
3. Running migration command `php bin/magento migrate:data app/etc/data-migration/config.xml -r -a` which ran without any errors
4. Running indexing `php bin/magento indexer:reindex`

### Steps to reproduce (*)

1. Create an order, take one product, go to checkout
2. Online or offline payment method - no difference
3. After clicking the _Place order_ button the error happens

### Expected result (*)

The order should be created without any problem.

### Actual result (*)

The following error is created as a report file and you get redirected back to the cart page.

```
"Fatal Error: 'Uncaught Error: Call to a member function getAdditionalInformation() on null in \/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php:185
Stack trace:
#0 \/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php(144): Magento\\Sales\\Model\\OrderRepository->setPaymentAdditionalInfo(Object(Magento\\Sales\\Model\\Order\\Interceptor))
#1 \/usr\/share\/nginx\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Sales\\Model\\OrderRepository->get('7653')
#2 \/usr\/share\/nginx\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Sales\\Model\\OrderRepository\\Interceptor->___callParent('get', Array)
#3 \/usr\/share\/nginx\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Sales\\Model\\OrderRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}('7653')
#4 \/usr\/share\/nginx\/html\/generated\/code\/Magento\/Sales\/Model\/OrderRepository\/Interceptor.php(26): Magento\\Sales\\Model\\OrderRepository\\Interceptor->___callPlugins('get', Array, Arra' in '\/usr\/share\/nginx\/html\/vendor\/magento\/module-sales\/Model\/OrderRepository.php' on line 185"
```

**Comment by codedge** [comment]
For reproducing this issue on a vanilla instance I would need to run a migration between two databases. Any advice how to do that?

**Comment by krishprakash** [comment]
Hi @codedge
All the Data Migration tool related issues should reported in its separate Data migration tool repository
Please report issue here.
https://github.com/magento/data-migration-tool
Thanks

**Comment by codedge** [comment]
Ok, new issue here https://github.com/magento/data-migration-tool/issues/766.

Thanks!
