### ISSUE TITLE
logo not showing on header magento 2.3.3

### ISSUE THREAD

**Issue by sagar6692** [magento/magento2#26277]
### Preconditions (*)

1. upload website logo from admin on magento 2.3.3
2. PHP Version 7.3.12
3.Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.12
  Database client version: libmysql - mysqlnd 5.0.12

### Steps to reproduce (*)

1. open admin
2.select content-->design-->configuration-->select theme-->expand header-->change logo
### Expected result (*)

1.  display logo on header
![image](https://user-images.githubusercontent.com/48976799/71812930-683cc300-309e-11ea-9519-ce38ec2347de.png)

### Actual result (*)

1. i am uploading png image for logo from admin is shows .svg format on website

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26277-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26277-2-4-develop.instances.magento-community.engineering/admin](https://i-26277-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @sagar6692 ,
I am uploading PNG & JPG file but I can't able reproduce this issue.
Can you please share your reproduce video?

Thanks.

**Comment by ajijshekh123** [comment]
@sagar6692 - Any update?

**Comment by vimal-ranosys** [comment]
Hello @sagar6692 
I have applied this steps with my project. I have uploaded PNG image as logo. Which is looking fine after flushing the cache from admin.

![Ranosys-logo-admin](https://user-images.githubusercontent.com/56148053/72659749-a74a0d00-39ea-11ea-8f2e-ba7a6dbef6e3.png)
